### ISSUE TITLE
Multiple environments with conda installed

### ISSUE THREAD

**Issue by gabrielcnr** [conda/conda#10014]
I'd like to start this issue by apologising if this is not the best channel to raise such question.

_(In fact, in the [docs](https://groups.google.com/a/anaconda.com/forum/#!forum/conda) there is a mention of a conda email group which I couldn't access or request to subscribe)_

So, after doing quite a lot of research, I couldn't find in the official documentation, StackOverflow, etc. anything talking about **what to do when you need to have multiple environments with `conda` installed**.

My specific use case is one where I need to support and test different combinations of (`conda` and `conda-build` versions on the same installation.

I'm using `conda==4.8.3` on my base environment (properly initialised via `conda init` too).

What I tried to do was:

```
$ conda create -n conda47 conda=4.7
...

$ conda activate conda47


(conda47) $ conda --version
conda 4.8.3


(conda47) $ $CONDA_PREFIX/bin/conda --version
conda 4.7.12
```

So I was able to easily create a new environment named `conda47` with `conda==4.7.12` installed in it. But when I activated the environment, the version of conda being invoked was still the 4.8.3, the one from my base environment (because of the `conda init` effects).

The way I could get around that issue was by invoking conda directly from the absolute path to `conda47/bin/conda`.

So I'm curious to understand what are the general recommendations and best practices to achieve this.

Thanks

**Comment by kenodegard** [comment]
Better late than never but yes your understanding here is spot on.

Accessing the non-base conda via the explicit path is the correct approach, all commands except `activate` and `deactivate` will work as expected in this manner.

**But**, generally speaking having `conda`/`conda-build` installed in non-base envs isn't necessary. `conda-build` has evolved over the years to avoid needing the base env Python version to match the package being built's Python dependency.
