### ISSUE TITLE
Creating environment from .yml doesn't run scripts

### ISSUE THREAD

**Issue by cristi-neagu** [conda/conda#10013]
## Current Behavior
After creating an environment which contains Jupyter Notebook, i export it to a .yml file using `conda env export > environment.yml`. Note that after installing Jupyter it creates shortcuts in the start menu, in the same folder as the conda prompt shortcuts.
I then try to create an environment from this file using `conda env create -f environment.yml`. Everything installs but there are no Jupyter shortcuts in the start menu. These shortcuts are created at the end of an install, by running a script created by Jupyter. This doesn't seem to happen when installing from an yml file.

### Steps to Reproduce
On the first computer:
```
conda create -n environment python=3.8
conda activate environment
conda install Jupyter
conda env export > environment.yml
```
On another computer:
```
conda env create -f environment.yml
```

## Expected Behavior
Shortcuts to launch a Jupyter notebook should exist on the second computer, in the start menu, under the Anaconda3 menu.

I may not be correct about why this issue is occuring, but the only variable is the mechanism of creating an environment from a yml file. One would expect that the yml file would be used as a list of packages that need to be installed that would then be passed to `conda install`, but that doesn't seem to be the case.

Thank you.

**Comment by cristi-neagu** [comment]
So... Any update on this? Am i doing something wrong? Is this a known issue? Thanks.

**Comment by angloyna** [comment]
Hi @cristi-neagu , I apologize for the late response. I have a hunch that the Jupyter Notebook buttons in the anaconda program folder of the start menu are actually placed there when you install Anaconda using the windows installer and not when you install jupyter via `conda install` into an environment. If you're able,  install Anaconda onto a windows system (without another Anaconda installed) and then check the start menu for the Jupyter notebook. It should be there without having to `conda install`. I think the Jupyter you're seeing in the start menu is just the one that comes with the Anaconda distribution.

**Comment by cristi-neagu** [comment]
@angloyna Thank you for responding.
I tried reading my message a few times over when i posted it, to make sure everything i said is ok, and i still managed to miss a thing, and i'm sorry about that. I am using Miniconda, not Anaconda. And the Jupyter Notebook links are most definitely created when installing Jupyter in an environment, as they are environment specific.

**Comment by angloyna** [comment]
A ha. I thought you might be. Let me try to reproduce with miniconda to see if I see what you’re seeing.

**Comment by angloyna** [comment]
Well, I think I managed to follow your steps, but my second windows system did have the jupyter notebook for the new environment  in my start menu. I was thorough and used a Windows 10 VM as my second system. We recently released a new version of Jupyter (about a week ago ~7/15). Have you be able to reproduce this recently (within the last week or so)?

**Comment by cristi-neagu** [comment]
Ok, i'll try it with the latest version and let you know. Thank you.

**Comment by angloyna** [comment]
Please do let me know. It’s be so much easier if I could reproduce it!

**Comment by cristi-neagu** [comment]
Yeah, looks like the issue isn't there any longer. I suppose that this really was a Jupyter issue. The reason why i thought it's a conda issue is because i wasn't seeing the script being run after installing from an environment file, like i would when installing by hand, like in the image attached.
![image](https://user-images.githubusercontent.com/30549178/88328220-01bc8100-cd20-11ea-89af-a5c59ff76c6c.png)

But yeah, looks like it's working now. Thanks.

**Comment by angloyna** [comment]
@cristi-neagu yeah, sometimes its hard to tell whether the issue is package- or conda- specific, honestly. I'm just glad it's working now.
