### ISSUE TITLE
Installer hash doesn't match

### ISSUE THREAD

**Issue by alexomics** [conda/conda#10012]
## Current Behavior

Hash of `Miniconda3-latest-MacOSX-x86_64.sh` doesn't match the one on the website. The hash is still the one for `v4.8.2` as seen on the [miniconda hash information](https://docs.conda.io/en/latest/miniconda_hashes.html) page, while the installer is for `v4.8.3`.

### Steps to Reproduce

```bash
cd /tmp
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
shasum -a 256 Miniconda3-latest-MacOSX-x86_64.sh
# ccc1bded923a790cd61cd17c83c3dcc374dc0415cfa7fb1f71e6a2438236543d  Miniconda3-latest-MacOSX-x86_64.sh
openssl dgst -sha256 Miniconda3-latest-MacOSX-x86_64.sh
# SHA256(Miniconda3-latest-MacOSX-x86_64.sh)= ccc1bded923a790cd61cd17c83c3dcc374dc0415cfa7fb1f71e6a2438236543d
```

## Expected Behavior

website should be updated with the correct hash.

[Instructions on verifying hashes](https://docs.conda.io/projects/conda/en/latest/user-guide/install/download.html#hash-verification) should be updated to:
 - actually tell a user to compare the hashes
 - give instructions on what to do when the hashes don't match

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
#!/bin/sh
#
# NAME:  Miniconda3
# VER:   py37_4.8.3
# PLAT:  osx-64
# LINES: 569
# MD5:   7e4514208db7df698acbc4defb149699
```
</p></details>

<details open><summary><code> System details </code></summary><p>

 - MacOS High Sierra v10.13.1
</p></details>

**Comment by alexomics** [comment]
I took the opportunity to take a look at all of the hashes on the [latest miniconda](https://docs.conda.io/en/latest/miniconda.html) page:

Match | URL | SHA256 hash | website hash
--- | --- | --- | --- 
No | https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe | `6003dbd4d1a9f0c9e64943468d00cf9f6dd2d34cfa0d00c58fe9d175d64c056c` | `1701955cd637d1dad5a84958fd470649b79de973d1570541eb52857664b5056c` | 
No |https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86.exe | `e4b8fc4802c6481f37a409ac3099aa1016aa3abf68671036670c0ff6a1526b44` | `ca74cb6eb0731db2b972c0fb512e29661a84c3f01ac6133121b4372eb1c41f46` | 
No |https://repo.anaconda.com/miniconda/Miniconda2-latest-Windows-x86_64.exe | `6973025404832944e074bf02bda8c4594980eeed4707bb51baa8fbdba4bf326c` | `8647c54058f11842c37854edeff4d20bc1fbdad8b88d9d34d76fda1630e64846` | 
No |https://repo.anaconda.com/miniconda/Miniconda2-latest-Windows-x86.exe | `c8049d26f8b6b954b57bcd4e99ad72d1ffa13f4a6b218e64e641504437b2617b` | `0d106228d6a4610b599df965dd6d9bb659329a17e3d693e3274b20291a7c6f94` | 
No |https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh | `ccc1bded923a790cd61cd17c83c3dcc374dc0415cfa7fb1f71e6a2438236543d` | `d1fca4f74f9971c27220122723843f6c879a5d13ff59c01fca17ef62a1576732` | 
No |https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg | `4a132568b095dfd728838af2dd0da5e27ea3ddb21bdfadaa89c9ffeda7786234` | `f3ede3a58d82fb5dcbca52d291a9edb5cd962d84d823a20693dd4bb27506cdd0` | 
No |https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.sh | `0e2961e20a2239c140766456388beba6630f0c869020d2bd1870c3d040980b45` | `0db8f4037e40e13eb1d2adc89e054dfb165470cc77be45ef2bf9cb31c8b72f39` | 
No |https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.pkg | `9ca4313e8162a939c7a5a4f48d657722594f8db9a98472803d63c3a7f66fa1da` | `fcc30b2e18f7a292b34b2e24ad855786a66423f860157fa2b77e48b6392f0abb` | 
No |https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | `bb2e3cedd2e78a8bb6872ab3ab5b1266a90f8c7004a22d8dc2ea5effeb6a439a` | `957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b` | 
Yes |https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86.sh | `f387eded3fa4ddc3104b7775e62d59065b30205c2758a8b86b4c27144adafcc4` | `f387eded3fa4ddc3104b7775e62d59065b30205c2758a8b86b4c27144adafcc4` | 
No |https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh | `b820dde1a0ba868c4c948fe6ace7300a252b33b5befd078a15d4a017476b8979` | `383fe7b6c2574e425eee3c65533a5101e68a2d525e66356844a80aa02a556695` | 
Yes |https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86.sh | `2e20ac4379ca5262e7612f84ad26b1a2f2782d0994facdecb28e0baf51749979` | `2e20ac4379ca5262e7612f84ad26b1a2f2782d0994facdecb28e0baf51749979` |



<details><summary>Code for table:</summary><p>

```bash
while read -r mc_url mc_hash; do res=$(curl -s ${mc_url} | shasum -a 256 | cut -f1 -d' '); printf "%s\t%s\t%s\n" ${mc_url} ${res} ${mc_hash}; done < urls_hashes.tsv > output.tsv
```

_urls_hashes.tsv_
```
https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe	1701955cd637d1dad5a84958fd470649b79de973d1570541eb52857664b5056c
https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86.exe	ca74cb6eb0731db2b972c0fb512e29661a84c3f01ac6133121b4372eb1c41f46
https://repo.anaconda.com/miniconda/Miniconda2-latest-Windows-x86_64.exe	8647c54058f11842c37854edeff4d20bc1fbdad8b88d9d34d76fda1630e64846
https://repo.anaconda.com/miniconda/Miniconda2-latest-Windows-x86.exe	0d106228d6a4610b599df965dd6d9bb659329a17e3d693e3274b20291a7c6f94
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh	d1fca4f74f9971c27220122723843f6c879a5d13ff59c01fca17ef62a1576732
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg	f3ede3a58d82fb5dcbca52d291a9edb5cd962d84d823a20693dd4bb27506cdd0
https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.sh	0db8f4037e40e13eb1d2adc89e054dfb165470cc77be45ef2bf9cb31c8b72f39
https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.pkg	fcc30b2e18f7a292b34b2e24ad855786a66423f860157fa2b77e48b6392f0abb
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh	957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86.sh	f387eded3fa4ddc3104b7775e62d59065b30205c2758a8b86b4c27144adafcc4
https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh	383fe7b6c2574e425eee3c65533a5101e68a2d525e66356844a80aa02a556695
https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86.sh	2e20ac4379ca5262e7612f84ad26b1a2f2782d0994facdecb28e0baf51749979
```
</p></details>

**Comment by afrendeiro** [comment]
I'm getting the same using SHA256 on https://docs.conda.io/en/latest/miniconda.html, but the files on https://repo.anaconda.com/miniconda/ have matching md5sums.

**Comment by chenghlee** [comment]
Thanks for notifying us about this oversight when we made the release; the SHA256 checksums on https://docs.conda.io/en/latest/miniconda.html should be correct now.

**Comment by alexomics** [comment]
@chenghlee Thank you for updating the hashes! 

Could I suggest adding some text to the cryptographic hash verification guide (https://conda.io/projects/conda/en/latest/user-guide/install/download.html#cryptographic-hash-verification) outlining:
- What you're verifying, all it tells you to do is run a command
- Where the fallback MD5 hashes are (https://repo.anaconda.com/miniconda/) 
- What to do when theses hashes do not match

**Comment by ambimorph** [comment]
I still don't get a match on SHA256 for Miniconda2-latest-MacOSX-x86_64.sh, though the MD5 is correct.

**Comment by alexomics** [comment]
@ambimorph I’m getting the correct hash at the moment. Are you sure you’ve got the latest link?

**Comment by ambimorph** [comment]
I was comparing at https://docs.conda.io/en/latest/miniconda.html

**Comment by ambimorph** [comment]
Hmm. I was just rehashing it to show you a screenshot and now it matches. I can't imagine what I did differently, but I guess it's moot. Thanks.
