### ISSUE TITLE
Conda prompt crashes,failed to create process and Jupyter notebook works fine

### ISSUE THREAD

**Issue by NidhiRustagi** [conda/conda#10029]
I have installed miniconda3 and then used conda update Anaconda command to update to the recent version of Anaconda 5.0.
The installation had been working well, was able to start anaconda prompt or anaconda PowerShell prompt and work on notebooks. For Tensorflow, I created another env and installed Tensorflow and other packages in the same env.

Problem occurred yesterday when I tried installing gensim in the same environment. The environment crashed and I cannot open Anaconda prompt, it gives me the error message:

**& : The term 'C:\Users\Nikkie\miniconda3\shell\condabin\conda-hook.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:3

* & 'C:\Users\Nikkie\miniconda3\shell\condabin\conda-hook.ps1' ; conda  ...
*   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  * CategoryInfo          : ObjectNotFound: (C:\Users\Nikkie...\conda-hook.ps1:String) [], CommandNotFoundException
  * FullyQualifiedErrorId : CommandNotFoundException

failed to create process.**

The path to conda.exe and python.exe are added in the System environment variables and the file activate.bat is also present in the same folder. I **cannot locate conda-hook.ps1 in the conda bin folder** though.
For now the Jupyter notebook starts and is able to connect with the kernel but I don't know for how long.

How can **conda** be unrecognized after months of working due to the installation of a new package? The environment crashed at the time of installation only and prompted me to restart the system. After that, I am getting the above error message... failed to create process.

I have installed a couple of packages for my work during the last 3 months and am looking to update or rectify the current installation only.  It will be really inconvenient to reinstall the whole thing.
Any help is much appreciated. Also, an understanding of why it failed after months of usage would be good.

What is the purpose of conda-hook.ps1? Is it that I can download only conda-hook.ps1 file and then it will work? 
Thanks in advance

**Comment by MIy2003** [comment]
I meet the same problem as you.I even can't open Jupyter and everything depends on python.exe.Have you found a solution now?
Any reply will be appreciated.
