### ISSUE TITLE
`conda init` plan fails with hardly interpretable error, when `.bashrc` contains weird characters

### ISSUE THREAD

**Issue by jalsti** [conda/conda#10023]
With using the current miniconda3, and starting `conda init`, I get the following error message:
"'utf-8' codec can't decode byte 0xa1 in position 1508: invalid start byte"
The process stops and does not give any further hints what might been wrong.

Having a look into the installed miniconda python files, I could figure out during debugging, that it is a problem with a commented line in my `.bashrc` file.
The line looks like that:
––
#export PS1='¡     \w (\u@\h \t)\n¡ \#:#'
––
where the "¡" are inverted exclamation marks (my editor (SciTe) shows them as 'xA1' special characters)
After removing that line, `conda init`ran through without throwing errors.

Nevertheless I might not be the only person on the planet which may have weird characters in their `.bashrc`, so I decided to report this as bug, **weird characters in comments of a more or less unrelated user config file should not break conda**.

The error results from (line numbers come from github source which was just pulled)
_conda/core/initialize.py:1243_, line `rc_content = fh.read()` in function 'init_sh_user'

called by the last `conda init` plan step in 
_conda/core/initialize.py:637_, line `result = globals()[step['function']](*step.get('args', ()), **step.get('kwargs', {}))` in function 'run_plan'

For at least giving a more specific error output, one could, as naive approach, maybe add before current _conda/core/initialize.py:1246_ something like

```
      except UnicodeDecodeError as e:
        print(f"Could not read file '{user_rc_path}', because it contains a byte which can not be 
converted to Unicode. Error was:\n\t", e)
```

and before current _conda/core/initialize.py:641_ something like:

```
            except:
              print(f"Error during plan step '{step['function']}'. with arguments: '{step['kwargs']}'")
              raise
```

which would also be an advantage for other possible errors in plans.

Here the error report I got at first `conda init` error.

    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            return getattr(module, func_name)(args, parser)
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_init.py", line 51, in execute
            anaconda_prompt, args.reverse)
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/initialize.py", line 118, in initialize
            run_plan(plan2)
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/initialize.py", line 636, in run_plan
            result = globals()[step['function']](*step.get('args', ()), **step.get('kwargs', {}))
          File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/initialize.py", line 1242, in init_sh_user
            rc_content = fh.read()
          File "/opt/miniconda3/lib/python3.7/codecs.py", line 322, in decode
            (result, consumed) = self._buffer_decode(data, self.errors, final)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 1508: invalid start byte
    
    `$ /opt/miniconda3/bin/conda init`
    
      environment variables:
                     CIO_TEST=<not set>
                   CONDA_ROOT=/opt/miniconda3
          OLD_LD_LIBRARY_PATH=/usr/local/cuda/lib64:/home/myself/.local/lib/
                         PATH=/usr/local/cuda/bin:/usr/local/cuda/nsight-compute-2019.5.0:/home/myse
                              lf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u
                              sr/bin/X11:/home/myself/script:/usr/games:/home/myself:/usr/lib/oracle
                              /xe/app/oracle/product/10.2.0/server/bin/:/usr/NX/bin/:/opt/cisco/anyc
                              onnect/bin/:/home/myself/studium/bin:/home/myself/.wine/drive_c/Progra
                              mme/IrfanView:/opt/sage:/opt/yEd:/home/myself/projekte/chip/bin:/usr/l
                              ib/i386-linux-gnu/wine/wine/fakedlls/:/usr/lib/x86_64-linux-
                              gnu/wine/wine/fakedlls/:/home/myself/.local/bin/:/opt/miniconda/bin/
                   PYTHONPATH=/home/myself/.local/lib
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : None
           user config file : /home/myself/.condarc
     populated config files : /home/myself/.condarc
              conda version : 4.8.3
        conda-build version : not installed
             python version : 3.7.7.final.0
           virtual packages : __cuda=10.2
                              __glibc=2.29
           base environment : /opt/miniconda3  (writable)
               channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /opt/miniconda3/pkgs
                              /home/myself/.conda/pkgs
           envs directories : /opt/miniconda3/envs
                              /home/myself/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/4.19.0-6-amd64 debian/8.11 glibc/2.29
                    UID:GID : 1000:1000
                 netrc file : /home/myself/.netrc
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    
    Upload successful.
    

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-85)

**Comment by chenghlee** [comment]
I just ran into this issue when the locale was not UTF-8, and `~/.bash_profile` was not UTF-8 encoded. Can you please provide the value of your `$LANG` and `$LC_ALL` variables? And, if possible, the output of `grep "#export PS1" ~/.bashrc | od -t x1`?

**Comment by jalsti** [comment]
```
$ echo "'$LANG' '$LC_ALL'"
'de_DE.UTF-8' ''
```
grep might not be helpful, as the failing entry is gone long (and re-pasting from this report results in different appearance)
```
$ grep "#export PS1" ~/.bashrc | od -t x1
0000000 23 65 78 70 6f 72 74 20 50 53 31 3d 27 5c 30 33
0000020 33 5b 30 3b 33 36 6d 5c 75 40 5c 68 20 28 24 4b
0000040 45 52 4e 45 4c 5f 52 45 4c 45 41 53 45 29 2c 20
0000060 5c 30 33 33 5b 31 6d 24 7b 54 54 59 23 23 2f 64
0000100 65 76 2f 7d 5c 30 33 33 5b 30 3b 33 36 6d 20 28
0000120 5c 6a 20 6a 6f 62 73 29 20 61 74 20 5c 41 20 5c
0000140 30 33 33 5b 30 6d 5c 77 5c 6e 5c 24 5c 30 33 33
0000160 5b 30 6d 20 27 0a 23 65 78 70 6f 72 74 20 50 53
0000200 31 3d 27 5c 30 33 33 5b 30 3b 33 36 6d 5c 75 40
0000220 5c 68 2c 20 5c 30 33 33 5b 31 6d 24 7b 54 54 59
0000240 23 23 2f 64 65 76 2f 7d 5c 30 33 33 5b 30 3b 33
0000260 36 6d 20 28 5c 6a 20 6a 6f 62 73 29 2c 20 5c 41
0000300 20 5c 30 33 33 5b 30 6d 5c 77 5c 6e 2e 24 28 65
0000320 63 68 6f 20 5c 77 20 7c 20 73 65 64 20 73 25 2e
0000340 2a 2f 25 25 67 29 2f 24 5c 30 33 33 5b 30 6d 20
0000360 27 0a 23 65 78 70 6f 72 74 20 50 53 31 3d 22 5c
0000400 6a 5c 30 33 33 5b 30 3b 33 36 6d 40 5c 30 33 33
0000420 5b 30 6d 5c 68 5c 30 33 33 5b 30 3b 33 36 6d 7c
0000440 5c 30 33 33 5b 30 6d 5c 41 5c 30 33 33 5b 30 3b
0000460 33 36 6d 3a 5c 30 33 33 5b 30 6d 5c 57 5c 30 33
0000500 33 5b 30 3b 33 36 6d 20 5c 24 20 5c 30 33 33 5b
0000520 30 6d 22 0a
0000524

$ grep "#export PS1" ~/.bashrc 
#export PS1='\033[0;36m\u@\h ($KERNEL_RELEASE), \033[1m${TTY##/dev/}\033[0;36m (\j jobs) at \A \033[0m\w\n\$\033[0m '
#export PS1='\033[0;36m\u@\h, \033[1m${TTY##/dev/}\033[0;36m (\j jobs), \A \033[0m\w\n.$(echo \w | sed s%.*/%%g)/$\033[0m '
#export PS1="\j\033[0;36m@\033[0m\h\033[0;36m|\033[0m\A\033[0;36m:\033[0m\W\033[0;36m \$ \033[0m"
```
