### ISSUE TITLE
error while installing geoplot using conda

### ISSUE THREAD

**Issue by deep1305** [conda/conda#10039]
while i am installing geoplot using conda  then it shows this type of error.
![error4](https://user-images.githubusercontent.com/54547661/86008038-e8345c00-ba35-11ea-84b8-d2fce6f90cde.JPG)
![error](https://user-images.githubusercontent.com/54547661/86007884-adcabf00-ba35-11ea-834f-e3a0fbdf127d.JPG)

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-93)

**Comment by angloyna** [comment]
Hey @deep1305 , are you still seeing this issue? I was able to install these packages from conda-forge successfully on my system, so hoping this issue is resolved for you.
