### ISSUE TITLE
Why do --name and --path conflict?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [conda/conda#10044]
When attempting to use `conda create` with both the --name and --path options, I'm getting the following error message:

conda create: error: argument -n/--name: not allowed with argument -p/--prefix

I can't see any good reason why these should conflict.  If any path information is supposed to be included when specifying -n/--name, the documentation should state this.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-97)

**Comment by mingwandroid** [comment]
When using `--path` you are expected to give `conda` the full path to the final environment folder, when using -`-name` you are expected to give just a name, and that is prefixed with `CONDA_PREFIX/envs`. Allowing both of these options at once could result in you passing something that does not make any sense, such as:

`conda create -n foo -p $HOME/bar`

In that case, what do you want? `CONDA_PREFIX/envs/foo` or `$HOME/bar`?

Is this unclear?

**Comment by Phillip-M-Feldman** [comment]
I had understood that --path was providing the path to the *parent
directory* of the environment folder.  So, aside from a possible change to
the documentation, things are fine as they stand.  Thanks!
