### ISSUE TITLE
What's happening with conda?

### ISSUE THREAD

**Issue by alippai** [conda/conda#10053]
While there are 1500 active issues and 100+ PRs it looks like the number of commits is declining sharply:
![image](https://user-images.githubusercontent.com/240729/86782607-8f7d4880-c05f-11ea-8d85-b009d7353194.png)

Is there a source I can read on Conda related topics like what's happening with the Conda project, what's changing, what's planned?

**Comment by ahmedkhalf** [comment]
Yea, I'm really disappointed with the lack of community management regarding issues...

**Comment by alippai** [comment]
I'm grateful for the nice project, the right word is that I'm _curious_ about the background story. Everyone has the liberty to fork and manage the project, the license allows it ;)

**Comment by WestXu** [comment]
Looks like the main maintainer @kalefranz has been inactive on GitHub for months.

**Comment by cristi-neagu** [comment]
Well, this is not good. Very worrying. Hope everyone's ok.

**Comment by kenodegard** [comment]
The conda community experienced some significant churn in 2020-2021. Efforts have been underway in the past 2 years to recover lost ground, so you should see an uptick in releases and activities throughout the conda community.

Larger feature planning can be found in our [CEPs (conda enhancement proposals)](https://github.com/conda-incubator/ceps) and more detailed activity can be viewed in the [planning project](https://github.com/orgs/conda/projects/2).

Feel free to join the community on [Matrix](https://matrix.to/#/#conda:matrix.org) and [Discourse](https://conda.discourse.group/).
