### ISSUE TITLE
Important Feature Request: Add activate & deactivate commands to conda.cli.python_api

### ISSUE THREAD

**Issue by ahmedkhalf** [conda/conda#10052]
## Introduction
Hello, first of all I just wanna thank all developers of conda for making such awesome project. I was really frustrated when using tools such as venv, pipenv and et al. but conda is something else, it was easy to setup, and having many versions of python running on different environments was easy and straightforward.
I am currently making a project called [lazyconda](https://github.com/ahmedkhalf/lazyconda) which aims to make calling conda commands even simpler by utilizing an interactive TUI (terminal UI). This project has been inspired by other terminal UI's like lazygit and lazydocker. And has been fueled by my urge of eliminating the need of googling for a command every time I need to do something complex.

## Problem
Okay, now that you have enough background on why I'm making this issue it's time to tackle the problem I encountered when using conda.cli.python_api. When making my project, I wanted a simple way of activating/changing the current environment in the open shell using python. I tried many ways of doing so:

- Creating a shell using a subprocess with "conda activate"
- Changing os.environ

But this does not change the conda environment in my current shell because as far as I know changing environment variables has no effect on the parent shell but only on the children of the python script.

## Conclusion
Okay so now seeing that in conda you can call "conda activate" (which I believe is the children of the shell?? and cannot change it's environment variables of parent shell if so) is there a way of activating an environment from python? How does conda tackle this problem? And could you add support for activate Command in `conda.cli.python_api`?

Thank you for reading up to this point :). Here is an [image of lazyconda](https://imgur.com/axLTrSJ) at the moment if you are interested.

**Comment by alimuqtadir** [comment]
Hello sir. Did you find the solution for it? I also tried to do it but failed

**Comment by alimuqtadir** [comment]
Hello. Thanks alot for your quick response. can you show me the working example of it so that i can understand it better.
