### ISSUE TITLE
Installing a package in multiple environement [conda install -n * <package> ]

### ISSUE THREAD

**Issue by lhoupert** [conda/conda#10059]
Hi !

I have a list of several conda environment that I am using for different projects.
For example:

```bash
└[3417]± conda env list                                                                                             
# conda environments:
#
base                     /????/anaconda2
analysis_eel_data     *  /????/anaconda2/envs/analysis_eel_data
explore_cora             /????/anaconda2/envs/explore_cora
pygmt                    /????/anaconda2/envs/pygmt
python3                  /????/anaconda2/envs/python3
test_cookiecutter_pj1    /????/anaconda2/envs/test_cookiecutter_pj1
```

I was wondering if there is an 'easy' way to install the same package in several conda environments? 
By easy, I mean a solution that could hold in one or two command lines?  Something like:

```
conda install -n * <package> 
```

I didn't find anything on this here  [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#managing-environments)

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-106)

**Comment by Dr-Doofensmirtz** [comment]
anybody found any solutions???
