### ISSUE TITLE
Issue regarding installing any packages using pip in virtualenv created by anaconda

### ISSUE THREAD

**Issue by samyak1999** [conda/conda#10062]
I am trying to install tensorflow in my virtual environment. But the error persists even after doing multiple installations.If the issue lies in the path , I have already added it to the environment variables. After going through various similar posts in stackoverflow ,google and qoura  nothing has worked out yet.  Its a major showstopper due its never ending errors.
The issue is displayed in the images 
<img width="767" alt="Annotation 2020-07-11 152555" src="https://user-images.githubusercontent.com/43057462/87222792-988a5480-c394-11ea-9b06-8b996c54fc24.png">

<img width="626" alt="Annotation 2020-07-11 163700" src="https://user-images.githubusercontent.com/43057462/87222816-dd15f000-c394-11ea-9d08-be2f6b96f324.png">

**Comment by rahulbordoloi** [comment]
Can you check once if tf is already present in your system or not? Use `pip list`

**Comment by samyak1999** [comment]
Not it's not present and even I try to install it using "pip install tf" same error is displayed

**Comment by rahulbordoloi** [comment]
I suppose you're from KIIT? You cannot directly install `TF` into our system as the default one goes for `TF-GPU` which js not supported. So, better create a venv using `pip` or either `conda` (your choice). Activate. Then `pip install tensorflow-cpu` (with pip). The latest CPU version supported by your system would be downloaded. Let me know if you fail.

**Comment by samyak1999** [comment]
It's not just about tensorflow(I have used tensorflow just as a reference). Any package I want to install using either of pip or conda it's showing the error . Moreover, these entire operation are conducted in a "active" virtual environment. Simple commands like
"pip install --upgrade pip" is not working.

**Comment by rahulbordoloi** [comment]
I think the problem lies with your dependencies. try this out - [stackexchange](https://unix.stackexchange.com/questions/582868/warning-pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl). <br>
Or, try uninstalling `pip`, clearing all the paths, and then installing it again.

**Comment by samyak1999** [comment]
Tried it already.  After doing this I tried to install tensorflow-CPU version , pip worked fine in root directory but not in virtual environment . I am resorting to continue with my codes in Google Colab. These bugs are major hindrance to the progress.

**Comment by rahulbordoloi** [comment]
Yeah, Google Colab works fine until you need to stream videos for your project. And while initiating virtual environment did you import `--system-site-packages` as well? Sometimes it corrupts some dependencies when you try to install some heavy frameworks/libraries. And regarding virtual env error, can you share the error for the same?

**Comment by samyak1999** [comment]
The errors are shared in the SS above. Go through this link:- https://github.com/conda/conda/issues/8273. The issue is settled and virtualenv with required packages was created successfully. 
Thanks for your valuable contribution in our conversation.
