### ISSUE TITLE
Ao instalar o anaconda navigatoros aplicativos ficam em pasta, não parece baixar completamente

### ISSUE THREAD

**Issue by febmartins** [conda/conda#10060]
Após a instalação do anaconda navigator vou tentar abrir os aplicativos dele, jupiter, spyder etc. e apenas aparece a pasta que n tem praticamente nada dentro. Não consigo usar nem nada, parece que a instalação não foi finalizada senndo que fiz tudo certinho.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
