### ISSUE TITLE
***NEW*** Connection error ( HTTP 000 CONNECTION FAILED)

### ISSUE THREAD

**Issue by anner-paldor** [conda/conda#10067]
## Current Behavior

Every package I try to install results in a connection error (HTTP 000 CONNECTION FAILED).
I had installed Conda a couple of months ago and everything was running great, and then after trying to install the variable inspector extension for Jupyter I noticed that Spyder wasn't launching (I used Jupyer notebooks until that point). I tried opening the Conda navigator and it didn't launch too. Eventually I uninstalled and reinstalled and that is when everything went bad and now I can't restore any Conda packages/environments, etc. It all turns up with this connection error. I've tried following the steps in [this](https://github.com/conda/conda/issues/9555) issue, including defining the PATH, copying the .dll files to the DLLs folder, clean reinstallation of both Anaconda 3 and Miniconda. Nothing, it gives the exact same error every time. I was able to install packages from the command window using pip (after I defined the PATH, of course), but that doesn't solve the problem since I can't use them (e.g. Jupyter). I am not sure this is a server issue because this works:
```
conda --version
conda 4.8.3
```

### Steps to Reproduce

Install the variable inspector extension as explained [here](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html#install-the-python-package). After that, uninstall and reinstall Miniconda3 (or Anaconda3, I've also tried that). Then run any Conda command from the Conda prompt to get the connection error, e.g.:
```
conda install jupyter
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://localhost:3141/root/pypi/ simple/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'http://localhost:3141/root/pypi/ simple/win-64'
```

## Expected Behavior

After typing Conda install _____ I expect to see the package installed and launchable.
After typing anaconda-navigator I expect the navigator to launch.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : base
    active env location : C:\Users\anner\miniconda3
            shell level : 1
       user config file : C:\Users\anner\.condarc
 populated config files : C:\Users\anner\.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages :
       base environment : C:\Users\anner\miniconda3  (writable)
           channel URLs : http://localhost:3141/root/pypi/+simple/win-64
                          http://localhost:3141/root/pypi/+simple/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\anner\miniconda3\pkgs
                          C:\Users\anner\.conda\pkgs
                          C:\Users\anner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\anner\miniconda3\envs
                          C:\Users\anner\.conda\envs
                          C:\Users\anner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\anner\.condarc <==
ssl_verify: True
channels:
  - http://localhost:3141/root/pypi/+simple/
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\anner\miniconda3:
#
# Name                    Version                   Build  Channel
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.1.5                    pypi_0    pypi
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
colorama                  0.4.3                    pypi_0    pypi
conda                     4.8.3                    py37_0    defaults
conda-package-handling    1.6.1            py37h62dcd97_0    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              2.9.2            py37h7a1dbc1_0    defaults
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
idna                      2.9                        py_1    defaults
importlib-metadata        1.7.0                    pypi_0    pypi
ipykernel                 5.3.2                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.1                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
json5                     0.9.5                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.5                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jupyterlab                2.1.5                    pypi_0    pypi
jupyterlab-server         1.2.0                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
notebook                  6.0.3                    pypi_0    pypi
numpy                     1.19.0                   pypi_0    pypi
openssl                   1.1.1g               he774522_0    defaults
packaging                 20.4                     pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.0.2                   py37_3    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
pycosat                   0.6.3            py37he774522_0    defaults
pycparser                 2.20                       py_0    defaults
pygments                  2.6.1                    pypi_0    pypi
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.7                h81c818b_4    defaults
python-dateutil           2.8.1                    pypi_0    pypi
pywin32                   227              py37he774522_1    defaults
pywinpty                  0.5.7                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
requests                  2.23.0                   py37_0    defaults
ruamel_yaml               0.15.87          py37he774522_0    defaults
send2trash                1.5.0                    pypi_0    pypi
setuptools                46.4.0                   py37_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h2a8f88b_1    defaults
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.46.0                     py_0    defaults
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4    defaults
```
</p></details>

**Comment by Abb1989** [comment]
@anner-paldor unfortunately, I received this error and I couldnot resolve it till now. Please help us.

**Comment by anner-paldor** [comment]
If anyone has any suggestions I'd be super grateful.

**Comment by Abb1989** [comment]
> If anyone has any suggestions I'd be super grateful. 

I recently find a solution which works for me, i do not know whether it works for you or not. After trying all routine ways have been offered by people to solve the problem, it worked for me with another way. I understand that _rep.anaconda.com_ address has been blocked in my country recently!!. "_You can use a vpn or proxy to resolve the error_". This just work me. You can try it now! If your problem will solve, please vote for me 😀

**Comment by Phoenix2030Adobe** [comment]
> > If anyone has any suggestions I'd be super grateful.
> 
> I recently find a solution which works for me, i do not know whether it works for you or not. After trying all routine ways have been offered by people to solve the problem, another way does for me. I just understood that _rep.anaconda.com_ address has been blocked in my country recently!!.So, "_You can use a vpn or proxy to resolve the error_". This just work me. You can try it now! If your problem will solve, please vote for me 😀

Yeah, same problem! 
It just worked for me, tnx.

**Comment by arizhakov** [comment]
See my comment here: https://github.com/conda/conda/issues/9555#issuecomment-660353058

**Comment by anner-paldor** [comment]
Thanks to all.
@arizhakov, as I replied in the other thread, I have all files so I think that might not be thee issue. 
@Phoenix2030Adobe and @Abb1989, which country/ies are you referring to? I am in the US, so I believe if this was the issue the problem would've been far wider than me. Also, I am able to install things from anaconda using pip, so this makes me thing it is a Conda environment issue, not a proxy. But I may be wrong.
If anyone has other ideas I'd be super grateful. I hate giving up everything I've done in Python and switch back to Matlab just because of this bug...

**Comment by anner-paldor** [comment]
UPDATE:
I was able to install everything on a different ("clean") computer in my house, so apparently the problem is not related to blockage of websites in my country or something like that. Also made sure again that all 4 .dll and .pdb files are in the DLLs folder.
Anyone??? Is this how my Python adventure ends..?

**Comment by angloyna** [comment]
Hi, @anner-paldor. It looks like its making a request to your local machine `http://localhost:3141/root/pypi/+simple/win-64` Is there a reason why you're doing that? `conda config --remove channels http://localhost:3141/root/pypi/+simple/` would remove that channel from your channels list.

**Comment by anner-paldor** [comment]
Thank you so much, @angloyna, that did the trick. I really appreciate it!
