### ISSUE TITLE
How to don't use locally built packages when conda install?

### ISSUE THREAD

**Issue by tiramisutes** [conda/conda#10070]
Hi,
The conda can use locally built packages with the parameter `--use-local` when installed. But sometimes I don't want it and how to set? 
By the way, when I activate a conda environment with `conda activate XXXXX` and then install python packages with `pip`. It will check the locally built packages.  But I don't want it and I want all the dependency is independent in this environment.
Thanks.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-110)

**Comment by angloyna** [comment]
Hey @tiramisutes, do you mind filling out the github issue template? There's some environment/configuration info that might be helpful to figure out if you've got your local packages in your channel list, and I'd like to see if I can reproduce your issue.
