### ISSUE TITLE
CondaError: Invalid spec for 'conda update': anaconda=2020.02 Use 'conda install' instead.

### ISSUE THREAD

**Issue by JackGuoFranklin** [conda/conda#10087]
when i update anaconda 

conda update  ananconda = 2020.02

i  get  this error:

CondaError: Invalid spec for 'conda update': anaconda=2020.02 Use 'conda install' instead.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-121)

**Comment by ankitshah009** [comment]
`conda install anaconda=2020.07` worked for my environment.

**Comment by mcunha** [comment]
If the correct action is to use `conda install anaconda=<VersionNumber>` then it should be reflected here:
https://docs.anaconda.com/anaconda/install/update-version/

Otherwise it's confusing.

**Comment by nise** [comment]
`conda update anaconda=2021.0`
Result: 
Please provide me some help on how to update conda: 

Referring to https://docs.anaconda.com/anaconda/install/update-version/ the following line should be the right one after calling `conda update`:
```
CondaError: Invalid spec for 'conda update': anaconda=2021.0
Use 'conda install' instead.
```



`conda update anaconda=2020.10`
Result: 
```
CondaError: Invalid spec for 'conda update': anaconda=2020.10
Use 'conda install' instead.
```
