### ISSUE TITLE
Cannot create env in Conda 4.8.3

### ISSUE THREAD

**Issue by dtch1997** [conda/conda#10094]
## Current Behavior
When creating env, miniconda does not create an interpreter in the `/miniconda3/envs/MY_ENV_NAME` folder. 

### Steps to Reproduce
```
conda create --name my_env
ls ~/download/miniconda3/envs/my_env 
```
Result: Various directories seem to be missing
```
conda-meta
```

## Expected Behavior
There should be a `miniconda3/envs/my_env/bin` with the correct Python interpreter, and folders for holding packages etc. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : lung_seg
    active env location : /home/dtan/download/miniconda3/envs/lung_seg
            shell level : 2
       user config file : /home/dtan/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.23
       base environment : /home/dtan/download/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dtan/download/miniconda3/pkgs
                          /home/dtan/.conda/pkgs
       envs directories : /home/dtan/download/miniconda3/envs
                          /home/dtan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/4.4.0-79-generic ubuntu/16.04.1 glibc/2.23
                UID:GID : 1011:1014
             netrc file : None
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
# Empty result
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/dtan/download/miniconda3/envs/lung_seg:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by wolfv** [comment]
you need to add packages to your environment.
you have not specified any thus it's an empty env.

**Comment by dtch1997** [comment]
I usually install packages using `python -m pip install`. But with an empty env, `which python` defaults to `usr/bin/python`. 

I guess I could work around that using `conda install` some random package, but it seems arbitrary to require users to conda install a package before the default python becomes the correct one.

**Comment by chenghlee** [comment]
As of [Conda 4.2.0](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id371), `conda create` with no package specifications creates an empty environment. If you want to have the Anaconda Python installed in your environment, you will need to run something like `conda create -n myenv python=3.7`.
