### ISSUE TITLE
Error with entry point OPENSSL_sk_new_reserve when installing or upgrading through conda 

### ISSUE THREAD

**Issue by ropinheiro** [conda/conda#10109]
This issue was reported here first, as I thought that it was something specific to Spyder:

https://github.com/spyder-ide/spyder/issues/13024

But now I noticed it also happens with other things like installing pytorch.

Running this:

`> conda install pytorch torchvision cpuonly -c pytorch`

Causes:

![image](https://user-images.githubusercontent.com/19519494/88573612-ebbd0200-d038-11ea-94b7-9e3055246887.png)

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-133)

**Comment by chenghlee** [comment]
Can you please provide the outputs for `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls`?
