### ISSUE TITLE
I am still getting the error: Scripts\conda-script.py", line 11, in <module>     from conda.cli import main;ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by BlackBaiX** [conda/conda#10104]
I am still getting the error:
C:\ProgramData\Anaconda3\condabin>conda update conda
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

I have installed Anaconda3-2019.10-Windows-x86_64 on windows 10

_Originally posted by Vivek1717 in https://github.com/conda/conda/issues/9507#issuecomment-582954650_

**Comment by Xiaoshizaizi** [comment]
Did you solve it

**Comment by Sobre1018** [comment]
Did you solve it
