### ISSUE TITLE
Adding support for `nushell` to `conda` environment manager.

### ISSUE THREAD

**Issue by 00krishna** [conda/conda#10113]
**I'm submitting a...**

* [ ] bug report
* [ ] feature request
* [ X] question

## Current Behavior

```
1. start nushell
>>> nu

2. try to start a conda environment.
>>> conda activate myenv
```

## Expected Behavior
I should see the conda environment activated and accessible.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

`conda info` won't currently work from nu shell. 

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

This command won't work from nu shell currently. 

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

This command will not currently run in nu shell. But really the question addressed in this issue happens before even an environment can be created or used.

```

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-136)

**Comment by adhadse** [comment]
Let's reopen this in the name of developers.

**Comment by lee-plus-plus** [comment]
Is there any new progress now?
