### ISSUE TITLE
Error to link Python and R

### ISSUE THREAD

**Issue by tottokuschel** [conda/conda#10130]
When I try to link Python and R, this error appears in Python when I compilate this:

import rpy2.robjects as ro

OSError: cannot load library '/Users/tottokuschel/opt/anaconda3/lib/R/lib/libR.dylib': dlopen(/Users/tottokuschel/opt/anaconda3/lib/R/lib/libR.dylib, 2): Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/tottokuschel/opt/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found

Can you help me to fix that? I already install R and RStudio in my computer

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-143)

**Comment by chenghlee** [comment]
It seems you are either have the wrong version of the readline package or are missing it entirely. Without the output of `conda info` and `conda list`, we won't be able to help you further.

**Comment by tottokuschel** [comment]
I already fix that problem. Now I have another!
When I try to install the library extRemes, this is the result.
**ro.r("install.packages('extRemes')")**
**rpy2.rinterface.NULL**
Please if you can help me with that.

**Comment by owenyoung75** [comment]
Hi @tomkinsc , I've encountered the same problem for import rpy2.robjects as ro.
How did you solve it? Thx!

**Comment by hothri** [comment]
> I already fix that problem. Now I have another!
> When I try to install the library extRemes, this is the result.
> **ro.r("install.packages('extRemes')")**
> **rpy2.rinterface.NULL**
> Please if you can help me with that.

How did you fix this error?
