### ISSUE TITLE
Plugin mechanism for virtual packages

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#10131]
Virtual packages have been popular since their introduction with `__cuda` ( https://github.com/conda/conda/pull/8267 ). Since then we have added `__glibc` ( https://github.com/conda/conda/pull/9358 ), `__osx` ( https://github.com/conda/conda/pull/9349 ), and are now looking at architecture specific ones ( https://github.com/conda/conda/pull/9930 ). As the use cases here expand, wonder if we should begin discussing a plugin architecture for the community to supply virtual packages and how these can be enabled and which ones we include by default. Thinking about this in the context of maintenance, extensibility, ease of use, etc. Thoughts? :slightly_smiling_face:

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-144)

**Comment by chenghlee** [comment]
I think it's a great idea. I can definitely see the utility, especially for community-supported packages that relies on some platform/host feature that isn't common enough to pull into the conda core code base (e.g., anything that relies on certain hardware or OS features being present).

**Comment by jakirkham** [comment]
cc @kkraus14

**Comment by jezdez** [comment]
I'm in full support for this feature request, and would like to suggest to use the plugin mechanism that is used by pytest, datasette and tox (and others): https://pluggy.readthedocs.io/

**Comment by jakirkham** [comment]
To add something else here, it would be good to provide a way to override these virtual package plugins

**Comment by jezdez** [comment]
@jakirkham I think that's the idea, yup!

**Comment by hmaarrfk** [comment]
It would be good to have a package for the nvidia driver version. `__nvidia` ???

**Comment by carterbox** [comment]
It would be good to have a package for __cudaarch ?? So binaries can be less fat or ship without PTX?

**Comment by beeankha** [comment]
Due to the merging of the [virtual package plugin implementation feature](https://github.com/conda/conda/pull/11854), I'm going to go ahead and close this issue! If any specific virtual package plugins are requested to be implemented for the future, please feel free to create a new issue for it and add the https://github.com/conda/conda/labels/plugins label.
