### ISSUE TITLE
invaluable Invalid channel Conda-Forge code error 404

### ISSUE THREAD

**Issue by Anken-Aoudia** [conda/conda#10140]
Hello i tried for two days to find the solution on the internet and I wasn't successful to solve this problem, I have a fresh windows 7 64 bits , the windows I used before this one things worked just fine, since I'm new with anaconda I'm stuck and lost. 

![Capture-1.PNG](https://user-images.githubusercontent.com/55611734/89728532-cd3a0c00-da25-11ea-8e8c-e96d7d2846c1.PNG)

**Comment by mingwandroid** [comment]
You seem to have typed `-c forge-conda` when you probably meant `-c conda-forge`?

But since you have it in your channels this should not be necessary. `conda install kivy` should work fine.

**Comment by Anken-Aoudia** [comment]
> You seem to have typed `-c forge-conda` when you probably meant `-c conda-forge`?
> 
> But since you have it in your channels this should not be necessary. `conda install kivy` should work fine.

Hello sir thank you for replaying, I did try with " conda install -c conda-forge kivy " and with "conda install kivy" and I ended up with this ![Capture-2.PNG](https://user-images.githubusercontent.com/55611734/89739936-c4c0f000-da7c-11ea-9f4e-d3c1978b5e02.PNG)

**Comment by Anken-Aoudia** [comment]
I did mix the typing after several time of trying, the solution was to keep retrying to download kivy , thank you for the assistance and sorry for your time.
