### ISSUE TITLE
Conda installation failed due to "Failed to execute script entry_point"

### ISSUE THREAD

**Issue by yonghoonlee** [conda/conda#10143]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

I failed installing anaconda on my linux server.
I checked previous issues reported here, and non of the resolutions proposed before applied to me.

1. This is fresh new installation, so I do not have anaconda installed on my computer. Thus, resolutions using conda command do not apply my case.

2. I double checked with the HASH of the installer, so the installer sh file is not corrupted. (Regarding https://github.com/conda/conda/issues/9125#issuecomment-624479467 )

3. I have more than 900GB of free SSD space with enough space on my account quota setting (>150GB), thus it is not a drive size issue. (regarding https://github.com/conda/conda/issues/9125#issuecomment-542732661 )

```
...

Anaconda3 will now be installed into this location:
/home/ylee196/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/ylee196/anaconda3] >>> 
PREFIX=/home/ylee196/anaconda3
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:                                                                             
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 368, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[58501] Failed to execute script entry_point
```

### Steps to Reproduce
On Ubuntu 20.04 LTS, command line environment through ssh,
```
./Anaconda3-2020.07-Linux-x86_64.sh 
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

do not apply, since initial installation of anaconda failed, so I do not have conda on my system.

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

do not apply, since initial installation of anaconda failed, so I do not have conda on my system.

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

do not apply, since initial installation of anaconda failed, so I do not have conda on my system.

</p></details>

**Comment by Amberjay18** [comment]
thanks @yonghoonlee  you helped me. I have installed the corrupted file...
so deleted them, reloaded and resolved it.

**Comment by kizzlota** [comment]
the same issue for me.

**Comment by haiqinma** [comment]
the same issue for me too. And my OS is Ubuntu 20.04.1 LTS. 
I checked file as results : 38ce717758b95b3bd0b1797cc6ccfb76f29a90c25bdfa50ee45f11e583edfdbf  Anaconda3-2020.07-Linux-x86_64.sh
I seems the file is right as https://docs.anaconda.com/anaconda/install/hashes/all .
I have no idea how to fix this.

**Comment by yihong-chen** [comment]
the same issue here for Ubuntu 20.04.1 LTS.

**Comment by stefantaubert** [comment]
I had the same issue with fedora-32 and resolved it. The reason was insufficient disk space.

**Comment by kthumar1997** [comment]
I faced the same issue when I was trying to install miniconda on an external drive. For me the issue got solved when I change the file system of my drive from FAT to Ext4.

**Comment by rrrico** [comment]
I got the exact same error on CentOS 8, turns out it was caused by insufficiant memory.
I simply resized my AWS EC2 instance to 2 GB (instead of 512 MB) then successfully ran the install again in **update** mode;

`bash ./Miniconda3-latest-Linux-x86_64.sh -p /opt/miniconda3 -u`

**Comment by yonghoonlee** [comment]
I am not sure how I resolved the issue, but it worked when I deleted my account and created another on my server. It is now working, but do not know what was the problem before. I hope procedures commented in this issue helps others who experience similar issue. It looks like hard drive or memory shortage for many of those who get the same error, or in my case, unknown but resolved by just deleting and re-creating username on the linux server. Update mode mentioned by @rrrico  looks very useful for those who are trouble shooting similar issues. Thank you all for your comments. I will close the issue with this comment.

**Comment by ksato-dev** [comment]
I faced the nearly same issue that (@kthumar1997) mentioned the format of file-system.

When I imitated his how to resolve and I tried to convert the format on the external drive from fat32 to ext4(this is the same one of default drive), I managed to install anaconda.

**Comment by paulraines68** [comment]
On my NVIDIA DGX A100 system I was getting this error and after running strace on the install I found the Permission denied came from it trying to write to /dev/shm  with for reasons I have yet to discover had become unmounted on the box and so was not world writable.  

I certainly think the installer should be more detailed about errors like this so we don't have to search through a million lines of strace to find what operation is actually giving the permission denied.

**Comment by ftarlao** [comment]
In my case I got this error by not having enough memory (RAM) at disposal for the installation to complete for the Anaconda Power9 installer; in detail I executed the installation on a remote node (srun -i, with slurm scheduler, I have a multi-arch cluster) and it failed lot of times, the problem has been solved by raisin' the RAM memory for the task to 5GB, --mem=5G solved the issue.

**Comment by STTP585** [comment]
I had the same issue and the problem was bad downloading. You can redownload and install it again.

**Comment by arivle** [comment]
same issue. reproduce in Anaconda3-2021.05-Linux-x86_64, Ubuntu 20.04.3

**Comment by yilewang** [comment]
same issue when I tried to install conda in singularity image, ubuntu20.04, Miniconda3-latest-Linux-x86_64

**Comment by ubseeyou** [comment]
$ sudo ln -s /usr/share/pyshared/lsb_release.py /usr/local/lib/(your python version. example - python3.9)/site-packages/lsb_release.py
it works for me. ubuntu 18.04

**Comment by lazy-eb** [comment]
I am using Ubuntu 22.04 in WSL2.

For me it was related to access to shared memory as indicated here:
[https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied](url)

I had created a systemd service to fix a issue I has with systemd.
[https://github.com/microsoft/WSL/issues/8996](url)

Disabling the service temporarily solved the conda not installing issue for me.

**Comment by Miguel-LlamasLanza** [comment]
I had to do a fresh install of Ubuntu on my PC, but I had backed up the anaconda3 folder. After restoring this folder, I tried installing Anaconda into the same location (using the `-u` option as suggested in the when I first tried the installation:
`ERROR: File or directory already exists: '/home/lmiguel/anaconda3'
If you want to update an existing installation, use the -u option.`.

Then, when trying to install using this update option, I got the exact same error as yours.
However, deleting the `anaconda3` folder beforehand and then doing a normal installation worked well.

**Comment by amkartashov** [comment]
For me, update (_I had existing installation of anaconda_) was failing because installer tried to open read-only file for writing:

```
9221  10:32:24 openat(AT_FDCWD, "/home/me/anaconda/pkgs/intel-openmp-2021.4.0-h06a4308_3561/info/licenses/mkl/info/licenses/license.txt", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
...
9221  10:32:24 <... openat resumed>)    = -1 EACCES (Permission denied) <0.000044>
```

Above is excerpt of strace log from `strace -olog -fvtTq -s1024 bash Anaconda3-2023.03-1-Linux-x86_64.sh -u -b -p $HOME/anaconda`

File permissions:

```
-r--r--r-- 1 me me 4547 Sep 24  2021 /home/me/anaconda/pkgs/intel-openmp-2021.4.0-h06a4308_3561/info/licenses/mkl/info/licenses/license.txt
```

To fix, I run `chmod +w -R $HOME/anaconda` - next run of installer worked fine.

Note: I've checked sha256sum for installer and it is correct `95102d7c732411f1458a20bdf47e4c1b0b6c8a21a2edfe4052ca370aaae57bab`.

**Comment by sknightq** [comment]
I resolve it with ```sudo```
Full command:
```
sudo bash ~/Downloads/Anaconda3-2023.07-1-Linux-x86_64.sh -f -b -p [Your Prefix Path]
```

**Comment by somenewaccountthen** [comment]
Who of you have encrypted home directories? there's some max filename length -1 char issue for some things. I wonder if it's hitting that. Or a rights issue. But installer swallows the error so you don't know. :/
Since i can install fine with the same file to /tmp/anaconda it's not the file, memory or diskspace. (I have oodles of disk and mem)

Pity the msg doesn'tget send, i assume it's trying to tell us the actual error. Which can vary apparently.

**Comment by johnprakashgithub** [comment]
I too faced this issue due to 100% disk utilization in /var
Solution: Cleaned up and made lot more available speace

**Comment by dwnogino** [comment]
Though late here, but another solution would be checking your /dev/shm file.  It should have 777 permissions.

**Comment by slinky55** [comment]
> Who of you have encrypted home directories? there's some max filename length -1 char issue for some things. I wonder if it's hitting that. Or a rights issue. But installer swallows the error so you don't know. :/ Since i can install fine with the same file to /tmp/anaconda it's not the file, memory or diskspace. (I have oodles of disk and mem)
> 
> Pity the msg doesn'tget send, i assume it's trying to tell us the actual error. Which can vary apparently.
> 
> **Filename too long** Since when i install it to /tmp/anaconda and later move it it gives this error: admin_bert@linuxdesktop:~$ mv /tmp/anaconda . mv: cannot stat './anaconda/pkgs/arrow-cpp-11.0.0-py311ha0d4687_0/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long mv: cannot stat './anaconda/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long
> 
> Maybe that rings a bell for someone?

I do, is there any fix?

**Comment by stob2023** [comment]
I have a similar problem:
`PREFIX=/home/xxxxxx/miniconda3
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 609, in result_iterator
  File "concurrent/futures/_base.py", line 446, in result
  File "concurrent/futures/_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[31686] Failed to execute script 'entry_point' due to unhandled exception!
`
I unfortunately have CIFS as the file system for our network homedirs

`//server.domain.eu/pathto/xxxxxxx on /home/xxxxxxx type cifs (rw,relatime,vers=3.0,cache=strict,username=xxxxxxx,domain=DOMAIN,uid=55361,noforceuid,gid=100,noforcegid,addr=1.2.3.4,file_mode=0755,dir_mode=0700,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,closetimeo=1)`

If I choose a local /home2dir/xxxxxxx/miniconda3 as PREFIX everything works fine.
Because we use shared workstations, it would be better if users could install this in their CIFS homedir. 
Is there perhaps a chance for a patch that fixes this problem?
Greetings 
stob2023

**Comment by alvitawa** [comment]
> Who of you have encrypted home directories? there's some max filename length -1 char issue for some things. I wonder if it's hitting that. Or a rights issue. But installer swallows the error so you don't know. :/ Since i can install fine with the same file to /tmp/anaconda it's not the file, memory or diskspace. (I have oodles of disk and mem)
> 
> Pity the msg doesn'tget send, i assume it's trying to tell us the actual error. Which can vary apparently.
> 
> **Filename too long** Since when i install it to /tmp/anaconda and later move it it gives this error: admin_bert@linuxdesktop:~$ mv /tmp/anaconda . mv: cannot stat './anaconda/pkgs/arrow-cpp-11.0.0-py311ha0d4687_0/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long mv: cannot stat './anaconda/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long
> 
> Maybe that rings a bell for someone?

Thanks, it was the encrypted home directory for me. Fixed it by installing in directory outside of home:
sudo mkdir /public                                                                                                                                                                                                                                                            
sudo chmod 777 /public
./Anaconda3-2023.09-0-Linux-x86_64.sh

(And change the path to /public/anaconda)

**Comment by BinaryFarmer** [comment]
> > Who of you have encrypted home directories? there's some max filename length -1 char issue for some things. I wonder if it's hitting that. Or a rights issue. But installer swallows the error so you don't know. :/ Since i can install fine with the same file to /tmp/anaconda it's not the file, memory or diskspace. (I have oodles of disk and mem)
> > Pity the msg doesn'tget send, i assume it's trying to tell us the actual error. Which can vary apparently.
> > **Filename too long** Since when i install it to /tmp/anaconda and later move it it gives this error: admin_bert@linuxdesktop:~$ mv /tmp/anaconda . mv: cannot stat './anaconda/pkgs/arrow-cpp-11.0.0-py311ha0d4687_0/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long mv: cannot stat './anaconda/share/gdb/auto-load/croot/arrow-cpp_1681498246563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho': File name too long
> > Maybe that rings a bell for someone?
> 
> Thanks, it was the encrypted home directory for me. Fixed it by installing in directory outside of home: sudo mkdir /public sudo chmod 777 /public ./Anaconda3-2023.09-0-Linux-x86_64.sh
> 
> (And change the path to /public/anaconda)

thanks this worked for me. been trying to fix this for a couple hours now

**Comment by linchen111** [comment]
> I have a similar problem: `PREFIX=/home/xxxxxx/miniconda3 Unpacking payload ... concurrent.futures.process._RemoteTraceback: ''' Traceback (most recent call last): File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup File "multiprocessing/connection.py", line 256, in recv TypeError: **init**() missing 1 required positional argument: 'msg' '''
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "entry_point.py", line 69, in File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists File "concurrent/futures/_base.py", line 609, in result_iterator File "concurrent/futures/_base.py", line 446, in result File "concurrent/futures/_base.py", line 391, in __get_result concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending. [31686] Failed to execute script 'entry_point' due to unhandled exception! ` I unfortunately have CIFS as the file system for our network homedirs
> 
> `//server.domain.eu/pathto/xxxxxxx on /home/xxxxxxx type cifs (rw,relatime,vers=3.0,cache=strict,username=xxxxxxx,domain=DOMAIN,uid=55361,noforceuid,gid=100,noforcegid,addr=1.2.3.4,file_mode=0755,dir_mode=0700,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,closetimeo=1)`
> 
> If I choose a local /home2dir/xxxxxxx/miniconda3 as PREFIX everything works fine. Because we use shared workstations, it would be better if users could install this in their CIFS homedir. Is there perhaps a chance for a patch that fixes this problem? Greetings stob2023

+1

**Comment by yepezcode** [comment]
Thanks @rrrico the solution works for me. I'd like to add after run that you should execute

```
source /opt/miniconda3/bin/activate
conda init
```

Then restart the terminal and run `source ~/.bashrc` 

ref: https://docs.anaconda.com/anaconda/install/linux/

**Comment by jiyu5** [comment]
This was likely caused by a corrupted file. I resolved it by re-downloading the anaconda.sh file.

**Comment by xyx1926885268** [comment]
I performed this  “chmod 700 -R $HOME/anaconda3/” ，so ,it can be run。

**Comment by yhling** [comment]
`chmod 700 -R $HOME/anaconda3/`

this worked on second run
