### ISSUE TITLE
when i install anaconda ,i meet this problem

### ISSUE THREAD

**Issue by xingxinggui** [conda/conda#10141]
ubuntu14

`bash Anaconda3-2020.07-Linux-x86_64.sh`

subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-149)

**Comment by chenghlee** [comment]
You will need to install the `lsb_release` application first; on Ubuntu, this is done using the command `sudo apt-get install lsb-release`.
