### ISSUE TITLE
Conda brings package with known vulnerabilities by default

### ISSUE THREAD

**Issue by vizhur** [conda/conda#10157]
Running in 0bae6fff6735
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan
  environment location: /opt/miniconda

  added / updated specs:
    - python=3.6

The following packages will be downloaded:

|    package                    |            build|
|----|----|
|    brotlipy-0.7.0             |py36h7b6447c_1000         323 KB|
|    ca-certificates-2020.6.24  |                0         125 KB|
|    certifi-2020.6.20          |           py36_0         156 KB|
|    cffi-1.14.0                |   py36h2e261b9_0         223 KB|
|    chardet-3.0.4              |        py36_1003         180 KB|
|    conda-4.8.3                |           py36_0         2.8 MB|
|    conda-package-handling-1.6.1|   py36h7b6447c_0         797 KB|
|    cryptography-2.9.2         |   py36h1ba5d50_0         556 KB|
|    idna-2.10                  |             py_0          50 KB|
|    ld_impl_linux-64-2.33.1    |       h53a641e_7         568 KB|
|    libedit-3.1.20191231       |       h14c3975_1         116 KB|
|    ncurses-6.2                |       he6710b0_1         817 KB|
|    openssl-1.1.1g             |       h7b6447c_0         2.5 MB|
|    pip-20.2.1                 |           py36_0         1.8 MB|
|    pycosat-0.6.3              |   py36h7b6447c_0          82 KB|
|    pycparser-2.20             |             py_2          94 KB|
|    pyopenssl-19.1.0           |             py_1          48 KB|
|    pysocks-1.7.1              |           py36_0          30 KB|
|    python-3.6.10              |       h191fe78_1        29.7 MB|
|    requests-2.24.0            |             py_0          56 KB|

```
**ruamel_yaml-0.15.87        |   py36h7b6447c_0         257 KB**
setuptools-49.2.0          |           py36_0         748 KB
six-1.15.0                 |             py_0          13 KB
sqlite-3.32.3              |       h62c20be_0         1.1 MB
tqdm-4.36.1                |             py_0          50 KB
urllib3-1.25.10            |             py_0          98 KB
wheel-0.34.2               |           py36_0          51 KB
------------------------------------------------------------
                                       Total:        43.2 MB
```

If you continue on,

   **please include all requested information below.**

If a maintainer determines the information is required to understand 
your issue, and if it is not provided, your issue may be
closed automatically.

-->

## Current Behavior
conda install -y python=3.6

started to bring ruamel-yaml and causes security alert on our side

### Steps to Reproduce
```
conda install -y python=3.6
```

## Expected Behavior
no ruamel-yaml installed or at least safe >0.16.7 version

## Environment Information
```
package                    |            build
    ---------------------------|-----------------
    brotlipy-0.7.0             |py36h7b6447c_1000         323 KB
    ca-certificates-2020.6.24  |                0         125 KB
    certifi-2020.6.20          |           py36_0         156 KB
    cffi-1.14.0                |   py36h2e261b9_0         223 KB
    chardet-3.0.4              |        py36_1003         180 KB
    conda-4.8.3                |           py36_0         2.8 MB
    conda-package-handling-1.6.1|   py36h7b6447c_0         797 KB
    cryptography-2.9.2         |   py36h1ba5d50_0         556 KB
    idna-2.10                  |             py_0          50 KB
    ld_impl_linux-64-2.33.1    |       h53a641e_7         568 KB
    libedit-3.1.20191231       |       h14c3975_1         116 KB
    ncurses-6.2                |       he6710b0_1         817 KB
    openssl-1.1.1g             |       h7b6447c_0         2.5 MB
    pip-20.2.1                 |           py36_0         1.8 MB
    pycosat-0.6.3              |   py36h7b6447c_0          82 KB
    pycparser-2.20             |             py_2          94 KB
    pyopenssl-19.1.0           |             py_1          48 KB
    pysocks-1.7.1              |           py36_0          30 KB
    python-3.6.10              |       h191fe78_1        29.7 MB
    requests-2.24.0            |             py_0          56 KB
    **ruamel_yaml-0.15.87        |   py36h7b6447c_0         257 KB**
    setuptools-49.2.0          |           py36_0         748 KB
    six-1.15.0                 |             py_0          13 KB
    sqlite-3.32.3              |       h62c20be_0         1.1 MB
    tqdm-4.36.1                |             py_0          50 KB
    urllib3-1.25.10            |             py_0          98 KB
    wheel-0.34.2               |           py36_0          51 KB
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-156)

**Comment by TiemenSch** [comment]
Moreover, I've been running into versioning issues with ``ruamel_yaml`` (which is a patched 0.15.x version) versus ``ruamel.yaml`` which install the same Python package. This is especially annoying when your project needs 0.16.x but can't upgrade in a clean way. Also ``ruamel_yaml`` is considered essential for conda, so you can't uninstall.
