### ISSUE TITLE
Cannot import spacy + no 'importlib_metadata' package after conda update conda

### ISSUE THREAD

**Issue by U0M0Z** [conda/conda#10155]
Hi, 
recently I have started to use spacy with my team to do some NLP analysis. I had installed the package through the conda forge channel, as indicated in the spacy website. 

Now, I had to update scikit-learn from 0.22 to 0.23 to run some other people analysis and therefore I proceed with the following:

conda update conda (in the root environment)

and scikit-learn was updated to the latest version 0.23.1.

Afterwordws I had tried to run "jupyter notebook" from the root and it was not working due to some jsonschema dependency. I had downgraded jsonschema == 3.0.2 and now the jupyter notebook can be launched but spaCy cannot be imported. 

I have the following error:

Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
Traceback (most recent call last):
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/catalogue.py", line 8, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/thinc/__init__.py", line 8, in <module>
    from ._registry import registry
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/thinc/_registry.py", line 1, in <module>
    import catalogue
  File "/Users/tommaso/anaconda3/lib/python3.7/site-packages/catalogue.py", line 10, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

I would expect spacy to be loaded normally, as I have just updated the conda environment. at the same time once I do a conda list I can see both the following packages installed:

importlib-metadata        1.7.0                         py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge

It's two days I am trying to solve this issue without having to reinstall anaconda/python. Any help from the community?

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

     active environment : base
    active env location : /Users/tommaso/anaconda3
            shell level : 1
       user config file : /Users/tommaso/.condarc
 populated config files : /Users/tommaso/.condarc
          conda version : 4.8.4
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/tommaso/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tommaso/anaconda3/pkgs
                          /Users/tommaso/.conda/pkgs
       envs directories : /Users/tommaso/anaconda3/envs
                          /Users/tommaso/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

==> /Users/tommaso/.condarc <==
channels:
  - conda-forge
  - defaults
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

# packages in environment at /Users/tommaso/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.9.0            py37hc8dfbb8_1    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py37_1    defaults
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.3                      py_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.0           py37hc8dfbb8_1001    conda-forge
appscript                 1.1.1            py37h9bfed18_0    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astroid                   2.4.2            py37hc8dfbb8_0    conda-forge
astropy                   4.0.1.post1      py37h9bfed18_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.os              0.1.1           py37hc8dfbb8_1002    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       py37hc8dfbb8_1001    conda-forge
beautifulsoup4            4.9.1            py37hc8dfbb8_0    conda-forge
bitarray                  1.4.2            py37h60d8a13_0    conda-forge
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
blosc                     1.20.0               hb1e8313_0    conda-forge
bokeh                     1.4.0                    py37_0    defaults
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py37h10e2902_1    conda-forge
brotli                    1.0.7             h4a8c4bd_1004    conda-forge
brotlipy                  0.7.0           py37h9bfed18_1000    conda-forge
brunsli                   0.1                  hb1e8313_0    conda-forge
bzip2                     1.0.8                haf1e3a3_2    conda-forge
c-ares                    1.16.1               haf1e3a3_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
catalogue                 1.0.0                      py_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.1           py37hf5b7abd_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
charls                    2.1.0                h4a8c4bd_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda                     4.8.4            py37hc8dfbb8_2    conda-forge
conda-build               3.18.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h9bfed18_2    conda-forge
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              3.0              py37h94e4008_0    conda-forge
curl                      7.71.1               hbdca1c0_4    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cymem                     2.0.3            py37h570ac47_2    conda-forge
cython                    0.29.21          py37h570ac47_0    conda-forge
cython-blis               0.4.1            py37h9bfed18_1    conda-forge
cytoolz                   0.10.1           py37h0b31af3_0    conda-forge
dask                      1.1.4                    py37_1    defaults
dask-core                 1.1.4                    py37_1    defaults
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distlib                   0.3.1                    pypi_0    pypi
distributed               1.26.0                   py37_0    defaults
distro                    1.5.0                    pypi_0    pypi
docutils                  0.16             py37hc8dfbb8_1    conda-forge
en-core-web-lg            2.3.1                    pypi_0    pypi
en-core-web-sm            2.3.1                    pypi_0    pypi
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fastcache                 1.1.0            py37h9bfed18_1    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gevent                    20.6.2           py37h9bfed18_0    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.65.0               h577aef8_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                h4a8c4bd_2    conda-forge
gmpy2                     2.1.0b1          py37h4160ff4_0    conda-forge
greenlet                  0.4.16           py37h9bfed18_0    conda-forge
grpcio                    1.31.0           py37hbfa9a1b_0    conda-forge
h5py                      2.10.0          nompi_py37h106b333_102    conda-forge
hdf5                      1.10.5          nompi_h0cbb7df_1103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
hypothesis                5.24.3                     py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37h64a549b_2    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2019.4                      233    defaults
ipykernel                 5.3.4            py37h43977f1_0    conda-forge
ipython                   7.17.0           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h0b31af3_2002    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.15.2                   py37_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.0.2                    pypi_0    pypi
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.2.4                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jxrlib                    1.1                  h0b31af3_2    conda-forge
keras                     2.3.1                         0    defaults
keras-applications        1.0.8                      py_1    conda-forge
keras-base                2.3.1                    py37_0    defaults
keras-preprocessing       1.1.0                      py_0    conda-forge
keyring                   21.3.0           py37hc8dfbb8_0    conda-forge
kiwisolver                1.2.0            py37ha1cc60f_0    conda-forge
krb5                      1.17.1               h14dd6a4_2    conda-forge
lazy-object-proxy         1.4.3            py37h9bfed18_2    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
lerc                      2.2                  hb1e8313_0    conda-forge
libaec                    1.0.4                h4a8c4bd_1    conda-forge
libarchive                3.3.3             h02796b4_1008    conda-forge
libclang                  8.0.1                ha1b3eb9_2    conda-forge
libcurl                   7.71.1               he6690cf_4    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20191231         hed1e85f_1    conda-forge
libev                     4.33                 haf1e3a3_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblief                   0.10.1               hb1e8313_0    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libnghttp2                1.41.0               h8a08a2b_1    conda-forge
libpng                    1.6.37               hb0a8c7a_2    conda-forge
libprotobuf               3.12.4               hab81aa3_0    conda-forge
libsodium                 1.0.18               h01d97ff_0    conda-forge
libssh2                   1.9.0                h39bdce6_5    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
libzopfli                 1.0.3                h4a8c4bd_0    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
llvmlite                  0.33.0           py37h3986384_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.2            py37heb1707f_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markdown                  3.2.2                      py_0    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py37h886f89f_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h9bfed18_1001    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py37h0b31af3_0    conda-forge
mkl_fft                   1.1.0            py37h3b54f70_1    conda-forge
mkl_random                1.1.1            py37h959d312_0    defaults
mock                      4.0.2            py37hc8dfbb8_0    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
mpc                       1.1.0             ha57cd0f_1009    conda-forge
mpfr                      4.0.2                h65ac59c_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            1.0.0            py37ha1cc60f_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
murmurhash                1.0.0            py37h570ac47_0    conda-forge
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
networkx                  2.4                        py_1    conda-forge
ninja                     1.10.0               ha1b3eb9_0    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7           py37hc8dfbb8_1004    conda-forge
notebook                  5.7.10           py37hc8dfbb8_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numba                     0.50.1           py37h0b113e5_1    conda-forge
numexpr                   2.7.1            py37h94625e5_1    conda-forge
numpy                     1.19.1           py37h3b9f5b6_0    defaults
numpy-base                1.19.1           py37hcfb5961_0    defaults
numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openpyxl                  3.0.4                      py_0    conda-forge
openssl                   1.1.1g               haf1e3a3_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py37hdadc0f0_0    conda-forge
pandoc                    2.10.1               haf1e3a3_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.0              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
path                      15.0.0           py37hc8dfbb8_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.5            py37hc8dfbb8_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pdfminer-six              20200726                 pypi_0    pypi
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.2.0            py37hfd78ece_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
pipenv                    2020.6.2                 pypi_0    pypi
pkginfo                   1.5.0.1                    py_0    conda-forge
plac                      0.9.6                    py37_1    defaults
pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
ply                       3.11                       py_1    conda-forge
preshed                   3.0.2            py37h570ac47_3    conda-forge
progressbar2              3.37.1                   py37_0    anaconda
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
prompt_toolkit            3.0.6                         0    conda-forge
protobuf                  3.12.4           py37hdadc0f0_0    conda-forge
psutil                    5.7.2            py37h60d8a13_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py37hd03d408_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37h9bfed18_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py37h9bfed18_1004    conda-forge
pycurl                    7.43.0.5         py37h7d0efee_2    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.5.3            py37hc8dfbb8_0    conda-forge
pyodbc                    4.0.30           py37h4a8c4bd_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypdf2                    1.26.0                     py_2    conda-forge
pyqt                      5.12.3           py37ha62fc16_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37h9bfed18_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytables                  3.6.1            py37h6f8395a_1    conda-forge
pytest                    6.0.1            py37hc8dfbb8_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.7.0                      py_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
pytest-doctestplus        0.8.0                      py_0    conda-forge
pytest-openfiles          0.5.0                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python-utils              2.4.0                      py_0    conda-forge
python.app                2                        py37_9    defaults
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.1                   py3.7_0    pytorch
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h10e2902_1    conda-forge
pyyaml                    5.3.1            py37h9bfed18_0    conda-forge
pyzmq                     19.0.2           py37hf1e22d8_0    conda-forge
qt                        5.12.5               h1b46049_0    conda-forge
qtawesome                 0.7.2              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.24.0                     py_0    anaconda
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h9bfed18_1001    conda-forge
scikit-image              0.17.2           py37h94625e5_1    conda-forge
scikit-learn              0.23.1           py37h603561c_0    defaults
scipy                     1.5.0            py37h912ce22_0    defaults
seaborn                   0.10.1                        1    conda-forge
seaborn-base              0.10.1                     py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.3.2           py37hc8dfbb8_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py37_1000    conda-forge
sip                       4.19.23          py37h570ac47_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                h4a8c4bd_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.2.1              pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1            py37hc8dfbb8_0    conda-forge
spacy                     2.3.2            py37hb449ec0_0    conda-forge
sphinx                    3.2.0                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.2                    py37_0    defaults
sqlalchemy                1.3.18           py37h9bfed18_0    conda-forge
sqlite                    3.32.3               hffcf06c_0    defaults
srsly                     1.0.2            py37h570ac47_0    conda-forge
statsmodels               0.11.1           py37h9bfed18_2    conda-forge
sympy                     1.6.2            py37hc8dfbb8_0    conda-forge
tabula-py                 2.1.1                    pypi_0    pypi
tblib                     1.6.0                      py_0    conda-forge
tensorboard               1.14.0                   py37_0    conda-forge
tensorflow                1.14.0          mkl_py37h085be34_0    defaults
tensorflow-base           1.14.0          mkl_py37h5a24fda_0    defaults
tensorflow-estimator      1.14.0           py37h5ca1d4c_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thinc                     7.4.1            py37ha1cc60f_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.7.24                  py_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
torchvision               0.6.1                  py37_cpu    pytorch
tornado                   4.5.3                    py37_0    defaults
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
typed-ast                 1.4.1            py37h0b31af3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7             h72f44dd_1000    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
virtualenv                20.0.30                  pypi_0    pypi
virtualenv-clone          0.5.4                    pypi_0    pypi
wasabi                    0.7.1              pyh9f0ad1d_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
wordninja                 2.0.0                    pypi_0    pypi
wordsegment               1.3.1                    pypi_0    pypi
wrapt                     1.11.2           py37h9bfed18_0    conda-forge
wurlitzer                 2.0.0            py37hc8dfbb8_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                1.3.2              pyh9f0ad1d_0    conda-forge
xlwings                   0.20.1           py37hc8dfbb8_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0b31af3_0    conda-forge
zeromq                    4.3.2                h4a8c4bd_3    conda-forge
zfp                       0.5.5                h4a8c4bd_1    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11                     1007    conda-forge
zope.event                4.4                pyh9f0ad1d_0    conda-forge
zope.interface            5.1.0            py37h9bfed18_0    conda-forge
zstd                      1.4.5                h0384e3a_2    conda-forge
</p></details>

**Comment by angloyna** [comment]
@U0M0Z would you be able to try the spacy version in the defaults channel in a new environment? We've had an out-of-date spacy package in defaults for some time, but now we're tracking with the latest minor version.

`conda config --add channels defaults`
`conda create env -n spacy-test spacy`
`conda activate spacy-test`

Do you see the same problem?

**Comment by U0M0Z** [comment]
@angloyna hi, thanks for the quick answer. I do not see the same problem once a new environment is created; I am able to update scikit-learn and run spacy at the same time. Just out of curiosity, can you explain me what the core issue might be?

**Comment by angloyna** [comment]
Was the new environment using the conda-forge package or the one from defaults? Hard to say easily based the info I have.
