### ISSUE TITLE
Conda error : conda.core.link:_execute(698) 

### ISSUE THREAD

**Issue by quantisedboy** [conda/conda#10165]
```

> ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
> Rolling back transaction: done
> 
> LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
> location of failed script: D:\Anaconda3\envs\conda_tf_env\Scripts\.qt-post-link.bat
> ==> script messages <==
> <None>
> ==> script output <==
> stdout: Failed to create temp directory "C:\Users\Soumyajit Sarkar\AppData\Local\Temp\conda-<RANDOM>\"
> 
> stderr:
> return code: 1
> 
> ()

```

Can't create a virtual environment using the clone base method, gives this error! 
Even if I manage to create an environment without using the clone base option, if I try to install a package, this error pops up. 
Plus even though I managed to install Scikit-Learn in this environment, import throws an error, says 'no module found'. This is just frustrating and irritating. 

Conda and virtual environment is a nightmare for beginners, and I'm not even bringing the error it throws up with Visual studio code.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-161)

**Comment by mangonihao** [comment]
Bro, I also encounter this problem when I wanted to use jupter notebook in virtual environment!

**Comment by angloyna** [comment]
some context was included in this issue: #10163

**Comment by lacan** [comment]
Seeing as no-one felt it important to follow up on this or to post a solution, here is what we found out when one of our users had a similar problem.

The user had modified the PATH environment variable, which no longer contained ´%SystemRoot%\system32;%SystemRoot%;%SystemRoot%´ so common commands were no longer recognized. 

Adding these to the PATH again and restarting the Conda prompt fixed the issue. 

Hope this helps someone else.

**Comment by picasso999** [comment]
Hi! 

I have tried many ways, this below one worked for me

the (base) in anaconda file has no environment variable set.

you can know what envs is set by typing 
"conda info"

if it shows

-active environment : none-

then, 

create a new envs as below

conda create --name environment_name_of_your_own

after following the steps

conda activate environment_name_of_your_own

from (base) , it changes to (environment_name_of_your_own)

you can run your commands from here now, it will work mostly.

it worked for me.

AlSO,

change your PC/Laptop Environment Variables -> User Variables -> TEMP (double click and change directory to) -> C:/Temp
 also
TMP (double click and change directory to) -> C:/Temp


MY "code info"

active environment : D:\miniconda_envi_setup_here\some_folder\env
    active env location : D:\miniconda_envi_setup_here\some_folder\env
            shell level : 3
       user config file : C:\Users\PC Dell\.condarc
 populated config files : C:\Users\PC Dell\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\PC Dell\.conda\pkgs
                          C:\Users\PC Dell\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\PC Dell\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\PC Dell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.1 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
