### ISSUE TITLE
different  conda env use the same packages(result of ‘pip' list is the same )

### ISSUE THREAD

**Issue by Tridu33** [conda/conda#10164]
(base) PS C:\Download> pip install numpy-1.19.0+mkl-cp37-cp37m-win_amd64.whl
Looking in indexes: https://pypi.doubanio.com/simple
Processing c:\download\numpy-1.19.0+mkl-cp37-cp37m-win_amd64.whl
**ERROR: deepspeech 0.8.0 has requirement numpy<=1.17.0,>=1.14.5, but you'll have numpy 1.19.0+mkl which is incompatible.**
Installing collected packages: numpy
Successfully installed numpy-1.19.0+mkl
(base) PS C:\Download> pip uninstall deepspeech

  Successfully uninstalled deepspeech-0.8.0
(base) PS C:\Download> conda create --name deepspeech
(base) PS C:\Download>  conda activate deepspeech
(deepspeech) PS C:\Download> python --version
Python 3.7.6
(deepspeech) PS C:\Download> pip install numpy == 1.17.0
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0+mkl
    **Uninstalling numpy-1.19.0+mkl:**
      Successfully uninstalled numpy-1.19.0+mkl
Successfully installed numpy-1.17.0

(deepspeech) PS C:\Download> pip list
......
numpy                             1.17.0
......

- - -
?why install numpy 1.17 in env"deepspeech"  will uninstall numpy1.19+mkl in env "base"?
how can this two conda env keep different packages alone?

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-160)

**Comment by AlexanderCecile** [comment]
There might be some issues with your Conda installation, you should consider removing everything and reinstalling Anaconda/Miniconda.

Installing packages in the base environment like this, especially through pip, is a bad idea.
