### ISSUE TITLE
Add equivalent to --user in pip

### ISSUE THREAD

**Issue by rragundez** [conda/conda#10174]
Referring to https://github.com/conda/conda/issues/6702#issuecomment-675608853:

Okay so "pip install --user corresponded to conda install -p ~/.local " doesn't work. As .local is not a conda environment:

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
target directory: /home/username/.local

So how can I have a systemwide conda environment available to all users which they cannot modify for other users, but at the same time they can install new packages or update new packages by installing them in their own home folder or so (where they have permissions)?

This is possible with pip. For example (I could also have used --user):

```bash
$ pip install fire
Defaulting to user installation because normal site-packages is not writeable
Installing collected packages: fire
Successfully installed fire-0.3.1
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-167)

**Comment by sudhaker** [comment]
+1

This feature is much needed, especially in the container environments.

**Comment by rragundez** [comment]
Any update on this one?

**Comment by jakirkham** [comment]
One can already create an environment anywhere they want. Just use [`conda create -p <path> <reqs>`]( https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#specifying-a-location-for-an-environment )

**Comment by rragundez** [comment]
Hi @jakirkham  I think you didn't read the description of the issue fully.
```
So how can I have a systemwide conda environment available to all users which they cannot modify for other users, but at the same time they can install new packages or update new packages by installing them in their own home folder or so (where they have permissions)?
```

**Comment by jakirkham** [comment]
Probably not a single environment, but users can [stack environments]( https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#nested-activation )

**Comment by rragundez** [comment]
@jakirkham It doesn't work. Apart from other nuances of going this route. This only works for command line commands as it's just keeping the PATH. 

So, now what?

![image](https://user-images.githubusercontent.com/16643700/130347975-9b852883-0b9c-4487-bd9d-c1189c20e209.png)
