### ISSUE TITLE
Windows shortcuts were gone after updating IPython with conda (Anaconda3 2.1.0)

### ISSUE THREAD

**Issue by chriswcy** [conda/conda#1017]
After updating IPython with either conda in terminal or Anaconda3's "Launcher", the shortcuts of IPython in windows start menu were gone (Windows 7 64-bit). Did I do something wrong?

Please help.

**Comment by soapy1** [comment]
@chriswcy is this still an issue for you?

**Comment by chriswcy** [comment]
Sorry for belated reply. It's gone. Thanks.
