### ISSUE TITLE
 Illegal Instruction 24731 while Installing Miniconda

### ISSUE THREAD

**Issue by madprogramer** [conda/conda#10175]
## Current Behavior

Miniconda Installation on yocto-Linux fails during intermediate python 3.7 installation.

Similar issues: #9164 

### Steps to Reproduce

After downloading the appropriate installer (https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86.sh) I encounter the following error during execution of the installer:

```
Miniconda3 will now be installed into this location:
/home/root/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/root/miniconda3] >>> 
PREFIX=/home/root/miniconda3
installing: python-3.7.1-h0371630_7 ...
./conda.sh: line 358: 24731 Illegal instruction     "$PREFIX/pkgs/python-3.7.1-h0371630_7/bin/python" -E -s "$PREFIX"/pkgs/.install.py $INST_OPT --root-prefix="$PREFIX" --link-dist="$1"
```

## Expected Behavior

Installation _should_ be able to proceed as normal.

## Environment Information

Distribution: [Miniconda 3, Linux Installer, 32-bit](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86.sh)
OS: Linux 3.8.7-yocto-standard i586
Device: Intel Galileo

**Comment by mingwandroid** [comment]
We no longer support 32-bit Intel Linux.
