### ISSUE TITLE
Suddenly I cannot activate my condo ends. Source activate not working

### ISSUE THREAD

**Issue by doyarzunv** [conda/conda#10188]
Hi all
Until yesterday I could source my environments as usual, however, today source is not working at all, and also cloning the root gave error. I'm working remotely to a Linux cluster at my university. I have no permission to modify the root.
After doing source activate dophd_sat I got this:

-bash-4.2$ source activate dophd_sat
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.18.0
         python version : 2.7.11.final.0
       requests version : 2.24.0
       root environment : /opt/anaconda  (read only)
    default environment : /opt/anaconda
       envs directories : /home/uczldeo/.conda/envs
                          /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
                          /home/uczldeo/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/uczldeo/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.24.0 CPython/2.7.11 Linux/3.10.0-327.36.3.el7.x86_64 Red Hat Enterprise Linux Server/7.2 glibc/2.17
                UID:GID : 152082:2015

`$ /opt/anaconda/bin/conda ..checkenv dophd_sat`

    Traceback (most recent call last):
      File "/home/uczldeo/.local/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
        activate.main()
      File "/home/uczldeo/.local/lib/python2.7/site-packages/conda/cli/activate.py", line 125, in main
        shelldict = shells[shell]
    KeyError: 'dophd_sat'

**Comment by cjmartian** [comment]
Hey @doyarzunv 

Thanks for opening this issue. I see your conda version is `4.3.16`. The latest version is `4.8.4`. Could you try updating your conda version? 
`conda install conda -n base -y`

**Comment by cjmartian** [comment]
After you update conda, you should be able to just `conda activate $env`

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by cjmartian** [comment]
Glad I could help.

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'

**Comment by doyarzunv** [comment]
HI thanks for your quick reply!
I can't install it as I don't have the right permission in the cluster. But I just did this and worked. In the meantime, I will store it in an alias to make it easier. Maybe not the best but enough for now.
thanks!

bash-4.2$ source ../../opt/anaconda3/etc/profile.d/conda.sh
bash-4.2$ conda activate dophd_sat
bash-4.2$ python 
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable.split('/')[-3]
'dophd_sat'
