### ISSUE TITLE
Proposal: drop Python 2 and Python < 3.6 support

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#10180]
Plagiarizing heavily from the counterpart proposal conda/conda-build#4024:

Python 2.7 reached its end-of-life on 2020-01-01. Currently, conda still supports installation into a Python 2.7 environment, and code, tests, and CI infrastructure are still being developed with Python 2.7 support in mind. I am proposing dropping support for installing conda into a Python 2.7 environment. 

At the same time, it would be good to define the minimum Python 3 version for conda's install environment. I am proposing that this minimum be Python 3.6 because:
* [Python 3.5 reaches its end of life next month](https://devguide.python.org/#status-of-python-branches) (2020-09-13), which will be before this proposal is implemented.
* [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) recommended dropping Python 3.5 support two months ago (2020-06-23).
* Python 3.6 allow for using new language features and improvements, including f-strings, improved annotations, the `os.PathLike` interface, and the `secrets` module.

The end result would be that future conda releases would require Python 3.6 or newer for installation. The benefits of dropping Python 2.7 and pre-3.6 versions include the ability to simplify the source code using modern Python syntax and features. Additionally, the test matrix would be reduced allowing for quicker feedback and more stability from the CI on PRs.

The scope of this change should result in a major version bump (to 5.0.0).

**Note**: future conda releases will still be able to create environments containing Python 2.7 and pre-3.6 packages. This proposal would _only_ affect the environment where conda itself it installed.

What do others think?

**Comment by Anthchirp** [comment]
> NEP 29 recommended dropping Python 3.5 support two months ago (2020-06-23).

Just to point this out: [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule)  recommended dropping Python **3.6** support two months ago (2020-06-23).

**Comment by ZanderKraig** [comment]
I do believe that this is a sensible argument. Given the rate at which python releases are being made and the increase in efficiency of algorithms, it is important to keep up the pace. Therefore it might be prudent to decide on a minimum python version which conda should support. Python 3.5 is nearing its end of life 2020-09-13 according to PEP 478) and it might be worth noting this point just as mentioned by @chenghlee for choosing the minimum version to support. This is only my humble feedback. There possibly is a need for several rounds of discussion before a decision is arrived at however.

**Comment by chenghlee** [comment]
Closing; conda 4.10.0 now requires Python >=3.6.
