### ISSUE TITLE
Script file 'H:\anaconda\Scripts\pip-script.py' is not present.

### ISSUE THREAD

**Issue by akashAD98** [conda/conda#10200]
my anaconda & pip was working fine ,suddenly its giving me these pip- scrpt.py not present issue . i tried with updating of conda nevigator ,still its not worked. 

Im using 
      conda version : 4.8.3
       conda-build version : 3.18.9
       python version : 3.7.4.final.0
       virtual packages :
       base environment : H:\anaconda  (writable)

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-177)

**Comment by Nyahua** [comment]
try:
`easy_install pip`

**Comment by jacobwilliams** [comment]
I've seen this error recently, but after creating and then activating an environment. pip works fine in the base environment and `pip-script.py` is there. It seems `pip-script.py` doesn't get put in the new environment when it is created. It isn't consistent though. I can delete and recreate the env and then it works fine.
