### ISSUE TITLE
Packages are not installing.

### ISSUE THREAD

**Issue by SubhadipDatta** [conda/conda#10201]
I tried several fresh installation also tried most of the methods in web but Unable to install packages from any channel. Please I need help. 
```
(base) C:\Users\username>conda install -c conda-forge gdal
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
```

Every time it stopped at this stage this time I wait 2 hours but nothing happens.

**Comment by ChengchenLyu** [comment]
**Hi same here. I have installing isssues:**

D:\conda> conda create -n cv python=3.6
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

**However, it's not the network or connection issue. Actually, if you go to the https://repo.anaconda.com/pkgs/main/win-64/ There is only file called "repodata.json" but no file called "current_repodata.json" **

**I don't know what happens there. Anyone know how to solve the issue please? Thanks!**

**Comment by amojarro** [comment]
Same. I have tried fresh installations on Ubuntu 18.04 and OS X 10.15.6 and 'Solving environment: \' still hangs.

**Comment by SubhadipDatta** [comment]
This is because of the latest version of anaconda. It is due to package conflict. Now after installing Miniconda my problem solved.
