### ISSUE TITLE
Tools to inspect current state of installed dependencies and their versions

### ISSUE THREAD

**Issue by brianv0** [conda/conda#10210]
This could be a small feature, but I thought it would be good to explain it before I do any kind of PR.

As far as I can tell, there's not a whole lot of tooling telling you about the installed state of dependencies - how they relate to each other.

(I would also note that `conda search` is also not great for this because it tries to download data)

In my specific case, the thing I would really like to know is more concrete - I just want to find out the current versions of dependencies installed for a given package. Where this is really helpful is in creating a pinned file where you can clamp down the installed versions of a specific package

Consider the following bash/jq script:

```
#!/bin/bash
pkg=$1
# Get the current versions of a package's installed dependencies
# get dist_name for the package so we can find it's json file
pkg_dist_name=$(conda list --json | jq -r '.[] | select(.name=="'${pkg}'") | .dist_name')
# get dependencies in the form of a regex
name_regex=$(jq -r '.depends | map(. | split(" ")[0]) | join("$|")' ${CONDA_PREFIX}/conda-meta/${pkg_dist_name}.json)
# print list of dependency=version for installed dependencies
conda list --json | jq -r '.[] | select(.name | match("'${name_regex}'")) | "\(.name)=\(.version)"'
```

A (hacky) example in python:

```
def pinit(pkg_name) -> Dict[str, Dict[str, str]]:
    prefix_data = PrefixData(prefix, True)
    pkg = prefix_data._prefix_records[pkg_name]
    dep_names = [i.split(" ")[0] for i in pkg.depends]
    installed_info = [dict(name=d.name, version=d.version, build=b.build} for d in [records[name] for name in dep_names]]]
    return installed_info
```

Going a step further, in maven, for example, there are tools in the maven dependency plugin, like dependency tree, which are also very helpful:
https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html

**Comment by kalefranz** [comment]
The `conda.models.prefix_graph` module already has most of the logic needed here, and it even has old/outdated code that outputs graphviz-compatible dot files to render. It would also be useful to be able to output a text-based dependency tree to the terminal though, similar to what pipenv does.
