### ISSUE TITLE
Problem with "conda install geopandas", on pyzo, windows  

### ISSUE THREAD

**Issue by theofech** [conda/conda#10219]
## Current Behavior

Hello, 

I had a problem to install geopandas on my pc. i use pyzo, and I have try to write "conda install geopandas", but that return the bellow error. Could you please help to get geopandas installed ? ( I need to add a detail : I 'm totally novice on github .. ).

Thanks you very much

Theo

### Steps to Reproduce

    
    
    Current conda install:
    
                   platform : win-64
              conda version : 4.2.7
           conda is private : False
          conda-env version : 4.2.7
        conda-build version : not installed
             python version : 3.8.2.final.0
           requests version : 2.23.0
           root environment : d:\programmes  (writable)
        default environment : d:\programmes
           envs directories : d:\programmes\envs
              package cache : d:\programmes\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                              https://repo.continuum.io/pkgs/free/noarch/
                              https://repo.continuum.io/pkgs/pro/win-64/
                              https://repo.continuum.io/pkgs/pro/noarch/
                              https://repo.continuum.io/pkgs/msys2/win-64/
                              https://repo.continuum.io/pkgs/msys2/noarch/
                config file : None
               offline mode : False
    
    
    
    `$ conda install geopandas -c conda-forge -c pyzo`
    
    
    
    
        Traceback (most recent call last):
          File "d:\programmes\lib\site-packages\conda\install.py", line 201, in yield_lines
            with open(path) as fh:
        FileNotFoundError: [Errno 2] No such file or directory: 'd:\\programmes\\pkgs\\menuinst-1.4.16-py38_0\\info\\has_prefix'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "d:\programmes\lib\site-packages\conda\install.py", line 209, in yield_lines
            raise StopIteration
        StopIteration
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "d:\programmes\lib\site-packages\conda\cli\install.py", line 405, in install
            execute_actions(actions, index, verbose=not context.quiet)
          File "d:\programmes\lib\site-packages\conda\plan.py", line 643, in execute_actions
            inst.execute_instructions(plan, index, verbose)
          File "d:\programmes\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
            cmd(state, arg)
          File "d:\programmes\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
            link(state['prefix'], dist, lt, index=state['index'])
          File "d:\programmes\lib\site-packages\conda\install.py", line 943, in link
            has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
          File "d:\programmes\lib\site-packages\conda\install.py", line 248, in read_has_prefix
            return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
          File "d:\programmes\lib\site-packages\conda\install.py", line 248, in <dictcomp>
            return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
          File "d:\programmes\lib\site-packages\conda\install.py", line 247, in <genexpr>
            parsed_lines = (parse_line(line) for line in yield_lines(path))
        RuntimeError: generator raised StopIteration
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "d:\programmes\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "d:\programmes\lib\site-packages\conda\cli\main.py", line 144, in _main
            exit_code = args.func(args, p)
          File "d:\programmes\lib\site-packages\conda\cli\main_install.py", line 80, in execute
            install(args, parser, 'install')
          File "d:\programmes\lib\site-packages\conda\cli\install.py", line 420, in install
            raise CondaRuntimeError('RuntimeError: %s' % e)
        conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
    ## Expected Behavior

Maybe I haven't write the command at the right place ?

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.8.2.final.0
       requests version : 2.23.0
       root environment : d:\programmes  (writable)
    default environment : d:\programmes
       envs directories : d:\programmes\envs
          package cache : d:\programmes\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(nothing, ndlr)
```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64

```

</p></details>

**Comment by TheDerivator** [comment]
Have you tried `conda install geopandas -c conda-forge pyzo` instead of `conda install geopandas -c conda-forge -c pyzo` ?

**Comment by theofech** [comment]
Hi,

Thanks for your response.

A. In the pyzo windows, the response is :
--
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: pyzo
--
B. In the windows shell (I’m not sure where you I have to try it), the response is the same.

C. I have tried conda install geopandas -c conda-forge in the windows shell and the result is the same one than on my post on github.

Thanks a lot for your help, I would be very happy to use geopandas on my computer.

Theo


De : TheDerivator <notifications@github.com>
Envoyé : mardi 8 septembre 2020 18:25
À : conda/conda <conda@noreply.github.com>
Cc : Théodore Fechner <theodore@lebasic.com>; Author <author@noreply.github.com>
Objet : Re: [conda/conda] Problem with "conda install geopandas", on pyzo, windows (#10219)


Have you tried conda install geopandas -c conda-forge pyzo instead of conda install geopandas -c conda-forge -c pyzo ?
