### ISSUE TITLE
separate root env and conda env

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1022]
I'd like to suggest that the conda root env is separate from the env used by conda, so that any root-env updates don't impact conda's behavior.

@bkreider @tswicegood this one is for you

**Comment by bj0** [comment]
this would be useful for me (specifically #1023) as I am using conda primarily as python version management.  I just learned about it and am using it on windows (I use https://github.com/yyuu/pyenv on linux). 

pyenv solves this problem by using 'shims' (which are just shell scripts) in the path that pass commands (python, pip, etc) to pyenv and pyenv then determines which version to pass the commands to.

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/3912.  Rolling out cautiously with conda 4.4 so we can have it solid for the Anaconda 4.5 installer.
