### ISSUE TITLE
Window user conda environment is invalid if the username contains accent

### ISSUE THREAD

**Issue by Alcolo47** [conda/conda#10239]
## Current Behavior
Under Windows 10 with a French settings, with a windows user account with Accent ("Stéphane")
created conda environments are invalid.

### Steps to Reproduce
With Miniconda windows64 4.8.4 installed for all users:

```
(base) C:\Users\Stéphane>conda create -n myenv
(base) C:\Users\Stéphane>conda activate myenv
(myenv) C:\Users\Stéphane>conda install python

EnvironmentLocationNotFound: Not a conda environment: C:\Users\St├®phane\.conda\envs\myenv

```

## Expected Behavior
Having python under myenv

## Note:
Using path environment:

```
(base) C:\Users\Stéphane>conda create -y -p c:\myenv
(base) C:\Users\Stéphane>conda activate c:\myenv
(c:\myenv) C:\Users\Stéphane>conda install -y python
.....
Downloading and Extracting Packages
vc-14.1              | 6 KB      | ############################################################################ | 100%
python-3.8.5         | 15.7 MB   | ############################################################################ | 100%

InvalidArchiveError("Error with archive C:\\Users\\Stéphane\\.conda\\pkgs\\vc-14.1-h0510ff6_4q_zk5ma1\\info-vc-14.1-h0510ff6_4.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to open 'C:\\Users\\Stéphane\\.conda\\pkgs\\vc-14.1-h0510ff6_4q_zk5ma1\\info-vc-14.1-h0510ff6_4.tar.zst'")
InvalidArchiveError("Error with archive C:\\Users\\Stéphane\\.conda\\pkgs\\python-3.8.5-h5fd99cc_14aiupqze\\info-python-3.8.5-h5fd99cc_1.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to open 'C:\\Users\\Stéphane\\.conda\\pkgs\\python-3.8.5-h5fd99cc_14aiupqze\\info-python-3.8.5-h5fd99cc_1.tar.zst'")
```

My opinion is that's coming from the same root cause: Encoding problem of directory path.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\ProgramData\Miniconda3
            shell level : 1
       user config file : C:\Users\Stéphane\.condarc
 populated config files : C:\Users\Stéphane\.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\ProgramData\Miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Stéphane\.conda\pkgs
                          C:\Users\Stéphane\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Stéphane\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\Stéphane\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Stéphane\.condarc <==
channels:
  - defaults
  - conda-forge
report_errors: False
```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\ProgramData\Miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38he774522_1000    defaults
ca-certificates           2020.7.22                     0    defaults
certifi                   2020.6.20                py38_0    defaults
cffi                      1.14.2           py38h7a1dbc1_0    defaults
chardet                   3.0.4                 py38_1003    defaults
conda                     4.8.4                    py38_0    defaults
conda-package-handling    1.6.1            py38h62dcd97_0    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              3.1              py38h7a1dbc1_0    defaults
idna                      2.10                       py_0    defaults
menuinst                  1.4.16           py38he774522_0    defaults
openssl                   1.1.1g               he774522_1    defaults
pip                       20.2.2                   py38_0    defaults
powershell_shortcut       0.0.1                         3    defaults
pycosat                   0.6.3            py38he774522_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 19.1.0                     py_1    defaults
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.3                he1778fa_0    defaults
pywin32                   227              py38he774522_1    defaults
requests                  2.24.0                     py_0    defaults
ruamel_yaml               0.15.87          py38he774522_1    defaults
setuptools                49.6.0                   py38_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.33.0               h2a8f88b_0    defaults
tqdm                      4.48.2                     py_0    defaults
urllib3                   1.25.10                    py_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_3    defaults
wheel                     0.35.1                     py_0    defaults
win_inet_pton             1.1.0                    py38_0    defaults
wincertstore              0.2                      py38_0    defaults
yaml                      0.2.5                he774522_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
```

</p></details>

**Comment by chenghlee** [comment]
Can you please provide the output of `systeminfo | findstr /i /c:"locale:"` command (run in Powershell or cmd.exe)?

**Comment by Alcolo47** [comment]
```
> systeminfo | findstr /i "gion"
Option r?gionale du syst?me:                fr;Fran?ais (France)
Param?tres r?gionaux d'entr?e:              fr;Fran?ais (France)

```
(locale(s) -> régional / régionaux in french, and to avoid &eacute; encoding problem I'm looking for "gion" only)

I haven't seen they were 2 versions of anaconda console (ps and cmd). The lack of "(PS)" in my example means that my runs were made with cmd.exe. I just made same commands under PS: same results.

**Comment by Alcolo47** [comment]
I'm deeping into the code:
The problem is comming from `conda/activate.py:1207`:
`activator.execute()` add environments for powershell encoded in UTF-8.

My 1st reflex was to configure PS script `Conda.psm1` in UTF8 (with [Console]::OutputEncoding = [Text.Encoding]::Utf8;)
But, in the returned environment of `activator.execute()`, only ADDED items are in UTF-8, NOT existing ones (on PATH concatenation).

Returned PATH of `activator.execute()` is
 `$Env:PATH = "C:\Users\Stéphane\.conda\envs\ess;C:\Users\Stéphane\.conda\envs\ess\Library\mingw-w64\bin;C:\Users\Stéphane\.conda\envs\ess\Library\usr\bin;C:\Users\Stéphane\.conda\envs\ess\Library\bin;C:\Users\Stéphane\.conda\envs\ess\Scripts;C:\Users\Stéphane\.conda\envs\ess\bin;C:\ProgramData\Miniconda3\condabin;C:\Python27;C:\Python27\Scripts;C:\Python38;C:\Python38\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Users\St�phane\AppData\Local\Microsoft\WindowsApps"
`
(This post preview render correctly encoding subilities, to me, I hope to you too ...)
The prepend path ".conda/env" use UTF-8 encoding, but the existing path 'AppData\Local\Microsoft` use my locale (cp1252 alias ANSI alias western europe)

We have to run activator.execute() entirely in local encoding and avoid all UTF-8 here.

**Comment by javgs-bd** [comment]
Hello. Is there any solution or workaround to this issue?

**Comment by ubiq1er** [comment]
Same issue here, bless the french accents !

**Comment by ste2NY** [comment]
Hi, I also have the same issue. Is there a workaround to change the path of the library install ?

**Comment by chus73** [comment]
Hi, I have the same problem because my username is Jesús. Does anyone have any idea how to solve this problem? Please do.

**Comment by javgs-bd** [comment]
My solution was to drop anaconda and conda altogether and set my environments completely from scratch using the venvs library. It is native in python and provides full control to where the libraries are located. 
I would strongly recommend anyone moving to an independent Python installation, and customize the creation of virtual environments for different applications.
If your %USERPROFILE% folder has special characters you might want to choose another location for the Python installation or/and the folder where your virtual environment will be created. 
Give it a go. There is plenty of material out there to learn how to use venv and install a full Python distirbution by yourself.
