### ISSUE TITLE
conda remove gets stuck

### ISSUE THREAD

**Issue by monajalal** [conda/conda#10243]
I am trying to remove a couple of packages but they get stuck:

```
$ conda remove pytorch-nightly
Collecting package metadata (repodata.json): done
Solving environment:
```

```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by chenghlee** [comment]
Can you please provide the output of `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls` so we have the information needed to replicate this issue?

**Comment by zchrissirhcz** [comment]
I meet conda remove get stuck.

My conda version 4.8.3

It seems when run `conda remove xxx` it will connect to its channels via internet. But we don't need this!!

**Comment by m-ibm** [comment]
Encountered the same problem. I installed `pyarrow` using conda which apparently installed a *very* old version and now I am unable to remove it (and install the latest with pip)

[channels.log](https://github.com/conda/conda/files/5910986/channels.log)
[info.log](https://github.com/conda/conda/files/5910987/info.log)
[sources.log](https://github.com/conda/conda/files/5910988/sources.log)
