### ISSUE TITLE
set VIRTUAL_ENV when activate environment

### ISSUE THREAD

**Issue by jetojedno** [conda/conda#10244]
It would be helpful if the `conda activate <env>` command set the VIRTUAL_ENV environment setting as this is used by `pip`  to find (amongst other things) the `pip.conf` file.  This will make consistent management of a conda environment easier.

**Comment by mingwandroid** [comment]
You can create 'normal' python virtual envs from any conda env that contains python and in the interests of keeping inline with upstream's choices here I think the stdlib venv module should have exclusive control of the VIRTUAL_ENV environment variable.

In spite of this tricky precedence matter, I would not oppose a config variable to enable this behavior.

**Comment by kalefranz** [comment]
Possibly relates to #5861, #7707, #7173.

**Comment by jetojedno** [comment]
>  I think the stdlib venv module should have exclusive control of the VIRTUAL_ENV environment variable.

Could I suggest that a request is made to the venv devs for an option to set all the environment variables but not create libraries etc.  This runs the risk, for them, that someone (conda) will incorrectly create the folders etc. (which could be defined against with some basic checks) and allows pip etc to operate correctly within a conda env.

I think it's not possible to solve the conda <-> pip (venv) interoperation without some acknowledgement by each side of the requirements of the other side.  It would seem, to my simple view, in everyone's benefit that these things work without causing random, difficult to trace and unnecessary defects.  That just makes us all look bad.
