### ISSUE TITLE
Why is "conda env" not listed in docs?

### ISSUE THREAD

**Issue by Sieboldianus** [conda/conda#10253]
I used conda for a while now but only stumbled recently across this because I was not able to override the name of an env to be create from an `envronment.yml` with `--name`.

Why is `conda env` not listed in the [commands section](https://docs.conda.io/projects/conda/en/latest/commands.html#conda-general-commands) of the conda docs?

First, I thought `conda env` is perhaps depreciated and I tried to use `conda create --file environment.yml` But it seems that `conda create` expects a `requirements.txt`. Instead, for env created from a yml, it is still necessary to use `conda env --file environment.yml`.

The confusion started when I noticed that `conda env --file environment.yml` does not work with the `--name` flag, but `conda create` does.

It would help if these differences could be documented in the [general commands section](https://docs.conda.io/projects/conda/en/latest/commands.html#conda-general-commands). Otherwise, the only place to find info about `conda env` is [somewhere deep into the docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=environment.yml#creating-an-environment-from-an-environment-yml-file).

If I misunderstood something, many apologies - and many thanks in advance for clarification!

[edit]

Noticed that `--name` indeed works for both `conda env create` and `conda create`. But other flags are not shared such as `--strict-channel-priority`.

**Comment by astrojuanlu** [comment]
`conda env` is still not listed.
