### ISSUE TITLE
Uninstall a package leaves .pyc files making it import as a site package

### ISSUE THREAD

**Issue by hmaarrfk** [conda/conda#10255]
## Current Behavior

```
# Install a noarch package
conda install pytest-qt --yes
# compile the pyc files
python -c "import pytestqt"
conda uninstall pytest-qt --yes
# the follow command should error
python -c "import pytestqt"
# But uppon closer inspection, you can see that python is actually improting this as a namespace module.... sigh....
python -c "import pytestqt; print(pytestqt.__path__)"
```

### Steps to Reproduce
As above.

## Expected Behavior
I think it would be great to do a cleanhouse of the pyc files upon removing noarch packages

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : mcam_dev
    active env location : /home/mark/miniconda3/envs/mcam_dev
            shell level : 2
       user config file : /home/mark/.condarc
 populated config files : /home/mark/.condarc
          conda version : 4.8.5
    conda-build version : 3.20.3
         python version : 3.7.8.final.0
       virtual packages : __cuda=11.0
                          __glibc=2.27
       base environment : /home/mark/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/ramonaoptics/linux-64
                          https://conda.anaconda.org/ramonaoptics/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mark/miniconda3/pkgs
                          /home/mark/.conda/pkgs
       envs directories : /home/mark/miniconda3/envs
                          /home/mark/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.8 Linux/5.4.0-48-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/mark/.condarc <==
channels:
  - ramonaoptics
  - conda-forge
always_yes: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by chenghlee** [comment]
Can you please provide either the channel or the recipe for the `pytestqt` package you mentioned in your report? I haven't been able to replicate this behavior with other noarch packages.

**Comment by hmaarrfk** [comment]
Sorry, there is likely a dash in the `pytest-qt` package name. (dashes and imports still confuse me ;))

I used the `conda-forge` channel for most package. the ones in `ramonaoptics` are mostly mirrors

**Comment by hmaarrfk** [comment]
Your right. i can't reproduce on this other computer of mine.

Maybe there was some race condition that cuased the pyc to get deleted as soon as they were being created by an other process.

Not too sure. Thanks for your help.
