### ISSUE TITLE
Community suggestions for conda 5.0.0 

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#10265]
We are currently in the process of planning the conda 5.0.0 release, with a targeted release sometime around Q1 2021; the existing roadmap items are here: https://github.com/conda/conda/milestone/38. Please comment on this issue if you have suggestions for what you would like to see added to conda 5.0.0.

**Comment by beckermr** [comment]
I am having a bit of trouble following the repodata sharding proposal, especially given that conda indexing is located in conda build and not conda. Are there more details on this somewhere?

**Comment by BrenBarn** [comment]
Would be great to have #2379 dealt with.  It is a problem for using conda from within IDEs, etc.

**Comment by kenodegard** [comment]
Closing this since conda 5.0 is no longer on the books per [CEP8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md)
