### ISSUE TITLE
Offline index generates dependencies different from online causing conda envs to fail to be created offline

### ISSUE THREAD

**Issue by stevehaertel** [conda/conda#10269]
conda version 4.8.5

I've hit this same issue over and over again with various packages.

**Quick way to reproduce:**

1. Give your host an internet connection
1. Make a conda environment that only consists of `arrow-cpp=0.15.0`
1. Use this resulting environment to make an offline repo (index it), and export the env as an environment yaml so as to be able to create this same one again.
1. Cut your machine's internet access
1. Use the **same** environment file that you got from step 3 and create the same environment in --offline mode, pointing to your local channel that was just created.
1. Get hit with:

```
ResolvePackageNotFound:
  - snappy[version='>=1.1.7,<1.1.8.0a0']
```

1. Ask yourself "what the heck?" and go check that env yaml that you created and see that when it had online access, it gave you "snappy=1.1.8", which is technically **greater** than the offline repo requirement of <1.1.8.0a0

### What's going on here:
The indexer is generating dependencies with version requirements that are different from the package versions that auto-install from an online connection.

**Comment by TheDerivator** [comment]
Seems related to the issue I reported here: https://github.com/conda/conda/issues/10217
