### ISSUE TITLE
unable to open anaconda navigator

### ISSUE THREAD

**Issue by KomalRokade** [conda/conda#10264]
hello 
  The problem is that when you download & install anaconda then for a day spyder & navigator open without any difficulty but from the very next day both of them i.e anaconda navigator and spyder when tried to open a GPYTHON.EXE prompt window opens many times.This prompt tells "TYPE HELP, COPYWRIGHT, LICENSE FOR MORE INFO". Thus making it a cumbersome process.So my query is that why this issue persistently nags me up.
               Plz try to help me out with this by guiding me how to open anaconda navigator & spyder without any LICENSE ISSUE.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
