### ISSUE TITLE
Plugin mechanism for user to pick/utilize different solvers while using conda

### ISSUE THREAD

**Issue by awilliams-anaconda** [conda/conda#10271]
┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-219)

**Comment by kenodegard** [comment]
See https://github.com/conda/conda/issues/11639, [solver docs](https://docs.conda.io/projects/conda/en/stable/dev-guide/plugins/solvers.html), and https://github.com/conda/conda-libmamba-solver
