### ISSUE TITLE
Collecting package metadata (current_repodata.json): failed  CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json> Elapsed: -

### ISSUE THREAD

**Issue by CalendulaED** [conda/conda#10288]
try to install several things but not work
![image](https://user-images.githubusercontent.com/68514251/96044563-9bd32780-0e3e-11eb-977c-8083aac36531.png)

**Comment by jp555c** [comment]
Hi
similar pb addressed in this thread : https://github.com/conda/conda/issues/9746
2 workarounds proposed :
1) copy the following files
libcrypto-1_1-x64.*
libssl-1_1-x64.*
from D:\Anaconda3\Library\bin to D:\Anaconda3\DLLs

2) bypass ssl verification
(base) C:\Users\myUser>conda config --set ssl_verify False
(base) C:\Users\myUser>conda update conda

**Comment by samy0444** [comment]
Any of these solutions didn't work for me. I'm getting same error on miniconda, trying to resolve since few days nothing worked.

**Comment by DogmaT2** [comment]
I'm getting the same error, on OSX (11.6.1). There is no Anaconda/DLLs folder, so the above fix does not apply.
