### ISSUE TITLE
Conda env activating but PATH order is incorrect unless I deactivate and reactivate in tmux

### ISSUE THREAD

**Issue by himat** [conda/conda#10296]
## Current Behavior

I'm on macos with zsh shell. I have the conda initialization script in my `~/.zshrc` so my base conda env gets activated on every new shell. 

But `which python` is displaying my system python instead of the conda one!
It sees the conda python in a regular shell, but in a tmux shell, the PATH variable order seems to be wrong.

In a tmux session, I open a new shell and get this:

```
❯ echo $CONDA_DEFAULT_ENV
base
❯ which python3
/usr/local/bin/python3 
```

And the issue seems to be that `/usr/local/bin` is closer to the beginning of my PATH variable than `/Users/hima/anaconda/bin` is.

Again, the path ordering is fine in a regular shell, but within a tmux shell, it's not correct.

How would I go about debugging what is causing this?

The only thing that works right now is doing `conda deactivate`, and then `conda activate` which then puts `/Users/hima/anaconda/bin` as the first thing in the path which fixes it. But conda should work correctly on the automatic initialization.

## Expected Behavior

The correct python would be 
`/Users/hima/anaconda/bin/python3`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

conda info output (from inside tmux)

```

     active environment : base
    active env location : /Users/hima/anaconda
            shell level : 1
       user config file : /Users/hima/.condarc
 populated config files :
          conda version : 4.9.0
    conda-build version : not installed
         python version : 3.6.3.final.0
       virtual packages : __osx=10.14.5=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/hima/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/hima/anaconda/pkgs
                          /Users/hima/.conda/pkgs
       envs directories : /Users/hima/anaconda/envs
                          /Users/hima/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.6.3 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

I ran this command, but nothing was printed out. Is this expected?

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

I can add this output if necessary but I don't think it's relevant to my issue.

```

```

</p></details>

**Comment by LukeChannings** [comment]
This is still an issue for me.
