### ISSUE TITLE
conda create using explicit file does not respect --download-only

### ISSUE THREAD

**Issue by JJsrc** [conda/conda#10299]
On conda 4.8.5:
Using an explicit file (such as retrieved using conda list --explicit), when you use it  with --download only , the prefix is actually created.
Repro:

```
conda activate base
conda list --explicit > /tmp/explicitfile.yml
conda create --prefix /tmp/myprefix --file /tmp/explicitfile.yml --download-only
```

Now you can see the full install has been done in /tmp/myprefix

**Comment by jbouzaglou** [comment]
I believe in misc.py, if we add the below line 104 (like it s done elsewhere), it would work:
    if context.download_only:
        raise CondaExitZero('Package caches prepared. UnlinkLinkTransaction cancelled with '
                            '--download-only option.')

**Comment by jbouzaglou** [comment]
Is there a way for a user like me to somehow patch this / workaround the problem?

**Comment by jbouzaglou** [comment]
PR #10306
