### ISSUE TITLE
Markupsafe halts windows builds

### ISSUE THREAD

**Issue by mrocklin** [conda/conda#1029]
Blaze builds were failing on windows 64bit python3 for a while because

Blaze imported Flask
Flask imported Jinja2
Jinja2 imported markupsafe

Importing markupsafe caused windows error R6034

![python3exe](https://cloud.githubusercontent.com/assets/306380/5306064/26214844-7bb6-11e4-9409-0d114188c8d8.png)

Oddly removing and reinstalling markupsafe removed the problem.  

It may also be related to this ignored error that popped up 

```
C:\Users\binstar\Miniconda\envs\_build\Lib\SITE-P~1\MARKUP~1\_speedups.pyd - Access is denied.
```

Here is a log of a full conda build session that hangs.  https://binstar.org/blaze/blaze/builds/57/16

@srossross @mwiebe and I all looked at this for an hour or so and tracked it down to this.

**Comment by asmeurer** [comment]
This should really be a conda-build issue. I guess the problem is that conda build can't remove that file from the build environment when it is running, and somehow that breaks it.

**Comment by dragon788** [comment]
I have a feeling if conda is using virtualenv it is related to that. I'm seeing the same errors with MarkupSafe/Jinja2 on other projects, but only if they run in an virtualenv (ie virtualenv, pew, tox, etc).

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1999
