### ISSUE TITLE
Update to versioned Miniconda installers

### ISSUE THREAD

**Issue by mjsteinbaugh** [conda/conda#10302]
(I think this was brought up in a pull request previously, but I'm having trouble finding the link)

The [versioned Miniconda installers](https://repo.anaconda.com/miniconda/) were last updated in June to 4.8.3. Would it be possible to add the recent releases, including 4.9.0?

**Comment by chenghlee** [comment]
We are planning on a 4.9.0 release within the next few weeks.

**Comment by mjsteinbaugh** [comment]
Perfect thanks @chenghlee !

**Comment by FelixMoelder** [comment]
Any news on that issue?
As Apple M1 Macs are out in the wild and 4.9.0 introduced arm support for macOS a new installer would be helpful.

**Comment by mingwandroid** [comment]
> As Apple M1 Macs are out in the wild and 4.9.0 introduced arm support for macOS a new installer would be helpful.

Well, this will not be Arm-native. We have not yet built software that runs on osx-aarch64.

**Comment by FelixMoelder** [comment]
What exactly won't be arm-native?
I hoped installing conda would be possible as conda-forge is already cross compiling packages for osx-aarch64.

**Comment by mingwandroid** [comment]
Anaconda do not release (at present) osx-aarch64 installers. You'd have either use microconda osx-aarch64 when available or run our installer via rosetta then mess around with CONDA_SUBDIR and add conda-forge as a channel until then.

It might work. Who knows?

**Comment by mingwandroid** [comment]
The initial installer will not contain packages from conda forge. Just from
defaults where we don't yet have osx-aarxh64 packages.

You can use microconda for osx-aarch64 when it's available or else you'll
need to our installer with rosetta 2 and the CONDA_SUBDIR env var..

**Comment by FelixMoelder** [comment]
Maybe I'm getting something wrong, but are we talking about a miniconda or a (full) conda installer?
I'm referring to an updated miniconda installer which should not, as you say, include any packages at all.

**Comment by mingwandroid** [comment]
I think you are misunderstanding an aspect here yes. 

Miniconda consists of nothing more than a conda executable (made with pyinstaller) and a set of (mostly) arch specific packages to install in the base env. Once the executable installs those packages it gets removed leaving nothing but those packages. conda list shows what those packages are.

**Comment by FelixMoelder** [comment]
Oh, you are right! I was completely missing the base env containing arch specific packages.
Thank's for pointing that out.

**Comment by mjsteinbaugh** [comment]
The new versioned installers are working great. Thanks!
