### ISSUE TITLE
Activation of gcc, gxx, and gfortran does not work - Miniconda3-latest-Linux-x86_64.sh on Ubuntu 20.04

### ISSUE THREAD

**Issue by sreedta8** [conda/conda#10303]
**Architecture**: Installed latest *miniconda3* version downloaded from Anaconda website for Linux-64 bit on a Ubuntu 20.04

**Issue**: In the folder ~/miniconda3/etc/conda/activate.d/ are a sereis of shell scripts meant to activate the Anaconda built-in gcc suite of compilers. When i execute on them individually I get the following errors:

1. When I execute *activate-binutils_linux-64.sh* in terminal, I get the errors: 
ERROR: This cross-compiler package contains no program /bin/x86_64-conda_cos6-linux-gnu-addr2line
ERROR: activate-binutils_linux-64.sh failed, see above for details

2. When I execute *activate-gcc_linux-64.sh* in terminal, I get the same errors (but for gcc):
ERROR: This cross-compiler package contains no program /bin/x86_64-conda_cos6-linux-gnu-cc
ERROR: activate-gcc_linux-64.sh failed, see above for details

3. Same relevant errors happen for gxx_linux-64.sh and gfortran_linux.sh

4. So I checked the ~/miniconda3/bin location and I found the files which the errors indicate are missing, are actually in the /bin folder **but** the instead of these files having the symbol for executables, I instead saw an **exclamation mark !**
I compared the gcc, gxx and gfortran against x86_64-conda_cos6-linux-gnu-f95 which has a different sign that looks like **>_**

5. However when I execute the above x86_64-conda_cos6-linux-gnu-f95 file or the x86_64-conda_cos6-linux-gnu-cc I get the same (expected) error as there are no file inputs:

*x86_64-conda_cos6-linux-gnu-cc: fatal error: no input files
compilation terminated.*

All of this came about because I installed R-4.0.3 from conda-forge into miniconda3 and I was trying to compile packages using the command *install.packages("bayesm")*

The Anaconda documentation on built-in compilers says that the command "source activate root" should activate these compilers and that is not happening right now.

Any possible solutions to this problem. Researching on this website and issues I had found some thing like did happen in the past - see this 

https://github.com/conda/conda/issues/6600      (I tried the solutions mentioned here and they did not work)

Thanks for the amazing work all of you do in making these complex and amazing data science and programming tools and applications come to life.

Sree

**Comment by sreedta8** [comment]
I wanted to share more ofwhat I found in exploring the errors related to the gcc suite of compilers.

I mentioned in my previous post:
*4. So I checked the ~/miniconda3/bin location and I found the files which the errors indicate are missing, are actually in the /bin folder but the instead of these files having the symbol for executables, I instead saw an **exclamation mark !**
I compared the gcc, gxx and gfortran against x86_64-conda_cos6-linux-gnu-f95 which has a different sign that looks like **>_** *

When I examined the properties of say *x86_64-conda_cos6-linux-gnu-addr2line* file I found a *points to* attribute. When I click that I get **Invalid link target** error.

So I think I understand why the activation scripts are giving me errors such as:
ERROR: This cross-compiler package contains **no program /bin/x86_64-conda_cos6-linux-gnu-addr2line**

So I removed R completely and installed miniconda3 from scratch and examined the location of these gcc executables under

~/miniconda3/pkgs/binutils_impl_linux-64-2.31.1-h6176602_1/bin/**x86_64-conda_cos6-linux-gnu-addr2line**

These are valid executables. Then I created a new environment (without R) and these links again appear under

*~miniconda3/envs/qwe/etc/conda/activate.d/* and under *~miniconda3/envs/qwe/bin/* - the same errors and the same "invalid link target" appeared.

So the error / issue appears to be that when I create a new environment and, conda is creating links or shortcuts from the new environment to the compilers located in the main *miniconda3/pkgs/xyz/bin/x86_64-conda_cos6-linux-gnu-xyz*  **that linking process is broken.**

Sree

**Comment by chenghlee** [comment]
Can you please provide the output of `conda list --show-channel-urls` and `conda config --show-sources`?

**Comment by sreedta8** [comment]
Thanks for getting back. I was able to resolve the error by reading one of your comments on another post that you advise users not to mix channels. In the original set-up, I had most of my libraries / packages from defaults, pypi, and some from conda-forge.

In the new environment I built the environment from a yaml file that made conda-forge the primary channel and listed all the gcc compilers and a couple of critical libraries (see below).

name: asd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.11
  - libcurl
  - libv8
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libglib
  - libstdcxx-ng
  - conda
  - pip
  - wheel
  - r-base=4.0.3
  - pip:
      - rpy2==3.3.6
      - pybrms==0.0.33

Before testing for compilation I also installed three critical R libraries r-v8, r-rcpp, and r-rcpparmadillo from conda-forge before I tested my compilation capabilities (previously I only installed r-v8 and r-rcpp from conda-forge and tried to install rcpparmadillo from CRAN).

Defining the environment with the conda-forge as primary and including the gcc suite of libraries seems to be working. I want to test further so I can isolate what worked and what did not. I will share further here what I find.

Kindly let me know if you need any more diagnostics from my setup.

**Comment by sreedta8** [comment]
Here is a link to my detailed post that details the steps I took get R in a conda environment working with the conda built-in compilers

https://stackoverflow.com/questions/64451861/unable-to-compile-r-packages-in-ubuntu-conda-environment-x86-64-conda-linux-gnu/64473954#64473954
