### ISSUE TITLE
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by schorlton** [conda/conda#10314]
## Current Behavior

Trying to run `conda create` or `conda install` fails with ECONNRESET. I get this can be a network issue, as per https://github.com/conda/conda/issues/10274, but I'm connected directly to my modem, and the rest of my internet works without issue.

    conda create -n test -c bioconda artic
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): failed
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
        Traceback (most recent call last):
          File "/opt/conda/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
            return self.connection.recv_into(*args, **kwargs)
          File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
            self._raise_ssl_error(self._ssl, result)
          File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
            raise SysCallError(errno, errorcode.get(errno))
        OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
        During handling of the above exception, another exception occurred:
        Traceback (most recent call last):
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 425, in _error_catcher
            yield
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 752, in read_chunked
            self._update_chunk_length()
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 682, in _update_chunk_length
            line = self._fp.fp.readline()
          File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
            return self._sock.recv_into(b)
          File "/opt/conda/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
            raise SocketError(str(e))
        OSError: (104, 'ECONNRESET')
        During handling of the above exception, another exception occurred:
        Traceback (most recent call last):
          File "/opt/conda/lib/python3.7/site-packages/requests/models.py", line 750, in generate
            for chunk in self.raw.stream(chunk_size, decode_content=True):
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 560, in stream
            for line in self.read_chunked(amt, decode_content=decode_content):
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 781, in read_chunked
            self._original_response.close()
          File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
            self.gen.throw(type, value, traceback)
          File "/opt/conda/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
            raise ProtocolError("Connection broken: %r" % e, e)
        urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
        During handling of the above exception, another exception occurred:
        Traceback (most recent call last):
          File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/opt/conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/opt/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            return getattr(module, func_name)(args, parser)
          File "/opt/conda/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
            install(args, parser, 'create')
          File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
            should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
          File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
            should_retry_solve)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
            force_remove, should_retry_solve)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
            ssc = self._collect_all_metadata(ssc)
          File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
            index, r = self._prepare(prepared_specs)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 1011, in _prepare
            self.subdirs, prepared_specs, self._repodata_fn)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
            repodata_fn=repodata_fn)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
            result = tuple(concat(executor.map(subdir_query, channel_urls)))
          File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
            yield fs.pop().result()
          File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 435, in result
            return self.__get_result()
          File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
            raise self._exception
          File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
            package_ref_or_match_spec))
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
            self.load()
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
            _internal_state = self._load()
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
            repodata_fn=self.repodata_fn)
          File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
            timeout=timeout)
          File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
            return self.request('GET', url, **kwargs)
          File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
            resp = self.send(prep, **send_kwargs)
          File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 686, in send
            r.content
          File "/opt/conda/lib/python3.7/site-packages/requests/models.py", line 828, in content
            self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
          File "/opt/conda/lib/python3.7/site-packages/requests/models.py", line 753, in generate
            raise ChunkedEncodingError(e)
        requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
    `$ /opt/conda/bin/conda create -n test2 -c bioconda artic`
      environment variables:
                     CIO_TEST=<not set>
                    CONDA_EXE=/opt/conda/bin/conda
                    CONDA_MD5=87e77f097f6ebb5127c77662dfc3165e
             CONDA_PYTHON_EXE=/opt/conda/bin/python
                   CONDA_ROOT=/opt/conda
                  CONDA_SHLVL=0
                CONDA_VERSION=4.8.2
                         PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr
                              /sbin:/usr/bin:/sbin:/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
         active environment : None
                shell level : 0
           user config file : /root/.condarc
     populated config files : 
              conda version : 4.8.2
        conda-build version : not installed
             python version : 3.7.6.final.0
           virtual packages : __glibc=2.28
           base environment : /opt/conda  (writable)
               channel URLs : https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /opt/conda/pkgs
                              /root/.conda/pkgs
           envs directories : /opt/conda/envs
                              /root/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.4.69-1-lts alpine/3.9.5 glibc/2.28
                    UID:GID : 0:0
                 netrc file : None
               offline mode : False
    An unexpected error has occurred. Conda has prepared the above report.
    If submitted, this report will be used by core maintainers to improve
    future releases of conda.
    Would you like conda to send this report to the core maintainers?### Steps to Reproduce

Happens about 1 in 5 tries:

```
docker run --rm -it continuumio/miniconda3:4.8.2-alpine
# As per bioconda installing guide
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
# Try installing package
conda create -n test -c bioconda artic
```

## Expected Behavior

Create env as per normal

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.4.69-1-lts alpine/3.9.5 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False


```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                1.3.0                    py37_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2019.11.28               py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.8.2                    py37_0    defaults
conda-package-handling    1.6.0            py37h7b6447c_0    defaults
cryptography              2.8              py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.2                  he6710b0_0    defaults
openssl                   1.1.1d               h7b6447c_4    defaults
pip                       20.0.2                   py37_1    defaults
pycosat                   0.6.3            py37h7b6447c_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.6                h0371630_2    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_1    defaults
ruamel_yaml               0.15.87          py37h7b6447c_0    defaults
setuptools                45.2.0                   py37_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.42.1                     py_0    defaults
urllib3                   1.25.8                   py37_0    defaults
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</p></details>

**Comment by chenghlee** [comment]
From inside the container, can you provide the outputs for:
```
curl -s --head https://repo.anaconda.com/pkgs/main/linux-64/repodata.json
curl -s --head https://conda.anaconda.org/conda-forge/linux-64/repodata.json
```

**Comment by schorlton** [comment]
> From inside the container, can you provide the outputs for:
> 
> ```
> curl -s --head https://repo.anaconda.com/pkgs/main/linux-64/repodata.json
> curl -s --head https://conda.anaconda.org/conda-forge/linux-64/repodata.json
> ```

`curl` not found. But when I `apk add` it (and I should also mention, now running the docker container as the `root` user with (`-u root`), here's what I get:

```
e700a6d14a02:/# curl -s --head https://repo.anaconda.com/pkgs/main/linux-64/rep
odata.json
HTTP/2 200 
date: Mon, 26 Oct 2020 14:05:00 GMT
content-type: application/json
content-length: 23033436
set-cookie: __cfduid=d4aa446d565735466a2b7a3b4c6c5d7ba1603721100; expires=Wed, 25-Nov-20 14:05:00 GMT; path=/; domain=.anaconda.com; HttpOnly; SameSite=Lax; Secure
x-amz-id-2: q0lWKdu1rRzpSxB9jrZYIO/MmHxWeLUvDOquIzJpWOdSomSJHZW5hsWtK2Sa5ysOdIKf2wRQXq0=
x-amz-request-id: 1ED4138C72ACA57B
last-modified: Sun, 25 Oct 2020 17:52:23 GMT
x-amz-version-id: O2sWPZ97k9pF6XTtLEdiJ_CXEGkikrAv
etag: "e8da7d40d5947013f163b7d5525cee06-3"
cf-cache-status: HIT
age: 3398
expires: Mon, 26 Oct 2020 14:05:30 GMT
cache-control: public, max-age=30
accept-ranges: bytes
cf-request-id: 0606d312e10000137ea02e4000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5e84bacb0cbd137e-YVR

e700a6d14a02:/# curl -s --head https://conda.anaconda.org/conda-forge/linux-64/
repodata.json
HTTP/2 200 
date: Mon, 26 Oct 2020 14:05:01 GMT
content-type: application/json
content-length: 89992023
set-cookie: __cfduid=d2dfa388dd850d0f3b919a8bf7d6d53fd1603721101; expires=Wed, 25-Nov-20 14:05:01 GMT; path=/; domain=.anaconda.org; HttpOnly; SameSite=Lax
cf-ray: 5e84bad5989b137e-YVR
accept-ranges: bytes
cache-control: public, max-age=1200
etag: "3ed8b3e189a03b200d305ee21fc3d6ee-11"
expires: Mon, 26 Oct 2020 14:25:01 GMT
last-modified: Mon, 26 Oct 2020 13:56:15 GMT
vary: Accept-Encoding
cf-cache-status: HIT
cf-request-id: 0606d3197c0000137e8d1c9000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-amz-id-2: vTVwdlzkm9yofk6qEnuV+mTVVeqFE2xV3W911h3HQ+9Ffvlw1Ga9gEh+6rGDtmympJ/c+8v3VCA=
x-amz-request-id: A3ACA63DE42F603C
x-amz-version-id: null
server: cloudflare


```
