### ISSUE TITLE
RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by ChakritRakuang** [conda/conda#10312]
(base) C:\Users\xxx xxxxx>conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

* defaults/win-64::anaconda-client==1.7.2=py38_0
* defaults/win-64::anaconda==custom=py38_1
* defaults/win-64::anaconda-navigator==1.9.12=py38_0
* defaults/noarch::anaconda-project==0.8.4=py_0
* defaults/noarch::baycomp==1.0.2=py_1
* defaults/win-64::bokeh==2.2.2=py38_0
* defaults/noarch::cachecontrol==0.12.6=py_0
* defaults/win-64::conda==4.8.5=py38_0
* defaults/win-64::conda-build==3.20.3=py38_0
* defaults/noarch::dask==2.30.0=py_0
* defaults/win-64::glue-core==0.15.6=py38_0
* defaults/noarch::glue-vispy-viewers==0.12.2=py_0
* defaults/win-64::glueviz==1.0.0=0
* defaults/noarch::httpx==0.16.1=py_0
* defaults/noarch::imageio==2.9.0=py_0
* defaults/noarch::jupyterlab==2.2.6=py_0
* defaults/noarch::jupyterlab_server==1.2.0=py_0
* defaults/win-64::matplotlib==3.3.1=0
* defaults/win-64::matplotlib-base==3.3.1=py38hba9282a_0
* defaults/noarch::mpl-scatter-density==0.7=py_0
* defaults/noarch::numpydoc==1.1.0=py_0
* defaults/noarch::orange-canvas-core==0.1.15=py_0
* defaults/noarch::orange-widget-base==4.7.0=py_1
* defaults/win-64::orange3==3.26.0=py38ha925a31_0
* defaults/win-64::scikit-image==0.16.2=py38h47e9c7a_0
* defaults/noarch::seaborn==0.11.0=py_0
* defaults/win-64::serverfiles==0.3.0=py38_0
* defaults/noarch::sphinx==3.2.1=py_0
* defaults/win-64::spyder==4.1.5=py38_0
* defaults/noarch::urllib3==1.25.10=py_0
* defaults/win-64::_anaconda_depends==2020.07=py38_0
* defaults/win-64::_ipyw_jlab_nb_ext_conf==0.1.0=py38_0
done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.5
  latest version: 4.9.0

Please update conda by running

```
$ conda update -n base -c defaults conda
```

## Package Plan
  environment location: C:\Users\xxxxt xxxxx\anaconda3

The following NEW packages will be INSTALLED:

  idna               pkgs/main/noarch::idna-2.10-py_0
  pillow             pkgs/main/win-64::pillow-8.0.0-py38hca74424_0
  requests           pkgs/main/noarch::requests-2.24.0-py_0

The following packages will be UPDATED:

  bitarray                             1.5.3-py38he774522_0 --> 1.6.0-py38he774522_0
  colorama                                       0.4.3-py_0 --> 0.4.4-py_0
  conda-package-han~                   1.6.1-py38h62dcd97_0 --> 1.7.2-py38h76e460a_0
  freetype                                2.10.3-hd328e21_0 --> 2.10.4-hd328e21_0
  libxml2                                 2.9.10-h464c3ec_1 --> 2.9.10-hb89e7f3_3
  lxml                                 4.5.2-py38h1350720_0 --> 4.6.1-py38h1350720_0
  nbclient                                       0.5.0-py_0 --> 0.5.1-py_0
  nbformat                                       5.0.7-py_0 --> 5.0.8-py_0
  pip                                         20.2.3-py38_0 --> 20.2.4-py38_0
  pkginfo                                    1.5.0.1-py38_0 --> 1.6.0-py38_0
  regex                           2020.10.11-py38he774522_0 --> 2020.10.15-py38he774522_0
  traitlets                                      5.0.4-py_0 --> 5.0.5-py_0
  xlwings                                     0.20.7-py38_0 --> 0.20.8-py38_0
  zipp                                           3.3.0-py_0 --> 3.3.1-py_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

(base) C:\Users\xxxxxx xxxxxxxxxx>

**Comment by johann-petrak** [comment]
Same problem here conda is at 4.7.12 and wants to upgrade to 4.9.2 (on Ubuntu Linux 18.04)
Is there a workaround or anything that could help with this problem?
