### ISSUE TITLE
`conda env export` doesn't export URL for pip packages installed from git

### ISSUE THREAD

**Issue by mil-ad** [conda/conda#10320]
Sorry if this is a duplicate, I did a search and couldn't find a related issue. 

## Current Behaviour
`conda env export` list packages installed via `pip` however if that pip packaged was installed from a git url (e.g. `pip install git+https://github.com/deepmind/dm-haiku`) that URL is missing from the exported environment:

```
  - pip:
    - dm-haiku==0.0.2
```

Therefore the `environment.yml` cannot be used later to reproduce the environment.

## Expected Behavior
`pip freeze` does expose this information, for example:

```
colorama==0.4.3
dm-haiku @ git+https://github.com/deepmind/dm-haiku@24d17d498029bc388dda629aa6c46c79c8f82da6
docutils==0.16
feedparser==5.2.1
```

shouldn't conda does something similar?

**Comment by mil-ad** [comment]
So turns out although `conda env export` doesn't export URLs correctly if I manually put them in the `environment.yml` they're picked up by `conda update -f`. So I can do this at the end my yaml file:

```
  - pip:
    - jax
    - "-f https://storage.googleapis.com/jax-releases/jax_releases.html jaxlib==0.1.56+cuda110"
    - git+https://github.com/deepmind/dm-haiku
    - git+git://github.com/deepmind/optax.git
```

It's a bit wonky. For instance if I change the order of things and replace `"-f https://storage.googleapis.com/jax-releases/jax_releases.html jaxlib==0.1.56+cuda110"` with `"jaxlib==0.1.56+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html"` it breaks.

**Comment by mil-ad** [comment]
[A comment on stackoverflow](https://stackoverflow.com/a/59056234/298209) says you can directly put `requirement.txt` in your conda yaml file. I haven't tested that yet but it might get around some of the parsing issues.

```
name: test-env
dependencies:
  - python>=3.5
  - anaconda
  - pip
  - pip:
    - -r file:requirements.txt
```

**Comment by tshu-w** [comment]
same issue here.

**Comment by cafhach** [comment]
`conda env export` seems to use the output of `pip list` instead of `pip freeze`

**Comment by themantalope** [comment]
this is still an issue

**Comment by hrdxwandg** [comment]
this is still an issue

**Comment by TugdualKerjan** [comment]
Same issue.
