### ISSUE TITLE
changeps1: False does not work for PowerShell

### ISSUE THREAD

**Issue by mika-fischer** [conda/conda#10326]
It seems `Conda.ps1m` unconditionally renames the prompt function without checking the `changeps1` setting from `.condarc`: https://github.com/conda/conda/blob/a9f5f25d92d58d41c088e4513610b9c33ea3a683/conda/shell/condabin/Conda.psm1#L268-L275

So if I set `changeps1: False`, then my custom prompt function is renamed, conda does not set it's own and I'm left with `PS>`...

**Comment by stinos** [comment]
This was broken by https://github.com/conda/conda/commit/ca16da40117a759b13e9cd27feeeef05a32b28a7. PR with fix here: https://github.com/conda/conda/pull/10624
