### ISSUE TITLE
Anaconda pre installed pip packages in new env

### ISSUE THREAD

**Issue by blanpa** [conda/conda#10322]
every time when I create a new conda env, I have pre-installed pip packages which I have installed in other env with the same python version. Is this right? I want to create a new env just with the necessary pip packages for a clean env.

I create a new env with:

conda create --name newenv python=3.8

Thats the same env on the picture, i tryed to uninstall and reinstall Anaconda navigator but the problem is still there.

![nhLQc](https://user-images.githubusercontent.com/54003618/97494223-50546980-1966-11eb-84b7-de433b8e6539.png)

**Comment by mengjade** [comment]
same issue here.
as long as it has the same python version, the pre-installed pip packages will be in the new env. 
note: using `\my_env\Scripts\pip` does not help. it still has the pre-installed packages


For example, I have python 3.7.0 on my machine. 
create a new env: `conda env create --no-default-packages -n my_env python=3.7.0`
`\my_env\Scripts\pip list` shows a list of pre-installed packages on my machine
If I use `conda env create --no-default-packages -n my_env python=3.8.0` (which is not available on my machine), i get a clean pip.

**Comment by wolfv** [comment]
I wonder if you didn't accidentally install the pip packages into the user or system packages using `pip install --user` or similar?

Did you use conda or pip to install these packages?

**Comment by mengjade** [comment]
> I wonder if you didn't accidentally install the pip packages into the user or system packages using `pip install --user` or similar?
> 
> Did you use conda or pip to install these packages?



> I wonder if you didn't accidentally install the pip packages into the user or system packages using `pip install --user` or similar?
> 
> Did you use conda or pip to install these packages?

Yes, i used `pip install --user` for some of the packages. That's before I created the new env.

**Comment by wolfv** [comment]
@mengjade then it's not a conda problem, since the packages are installed in the pip user environment. Don't use `--user` if you want pure conda environments, I guess.
