### ISSUE TITLE
  SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by lammps-vasp** [conda/conda#10330]
-->
python run.py   
File "<stdin>", line 1      SyntaxError: invalid syntax  
      这个问题是路径的原因吗 不知道怎么设置

**Comment by chenghlee** [comment]
Closing; not enough information to suggest that this is a conda issue.

**Comment by lammps-vasp** [comment]
sorry 我是请教这个问题怎么解决 问题放错地方了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "conda/conda"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 凌晨1:36
收件人:&nbsp;"conda/conda"<conda@noreply.github.com&gt;;
抄送:&nbsp;"zhifeng Zhang"<1491668290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [conda/conda]   SyntaxError: invalid syntax  (#10330)





 
Closed #10330.
