### ISSUE TITLE
AssertionError()

### ISSUE THREAD

**Issue by lionweeps** [conda/conda#10338]
AssertionError('Prefix record insertion error: a record with name r-catools already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues')
()
AssertionError()

**Comment by chenghlee** [comment]
Please provide the command you were running, and the outputs for `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls` as requested in the template. Without it, we will not be able to help you.

**Comment by kenodegard** [comment]
The author did not provide the requested details.
