### ISSUE TITLE
Add a command line switch to abort immediately on finding unsatisfiable constraints

### ISSUE THREAD

**Issue by rs2** [conda/conda#10340]
See e.g. 

```bash
$ conda create -n foo ipywidgets=7.* ipykernel=4.3.* -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining ipywidgets=7: 100%|███████████████████████████
```

This search may enter a never-ending loop and not complete within hours. Instead, the users should have the choice to abort the command immediately.

Additionally, a conda lock is being held for the duration of this, potentially multi-hour, operation. This would prevent any other conda processes on the same host from succeeding.

There should be an option to skip this block and exit with an error instead: https://github.com/conda/conda/blob/8b5671d748b494876d9828fe1c9e0f29aa15fa40/conda/resolve.py#L345-L348

**Comment by jontwo** [comment]
This would be ideal for CI builds - currently the build hangs and creates a large queue of subsequent builds. It would be better if it just failed straight away without causing congestion.

**Comment by rs2** [comment]
@jontwo well said.

**Comment by vadimkantorov** [comment]
Stumbled on this as well: https://stackoverflow.com/questions/69630073/how-to-force-conda-to-skip-examining-conflicts

For my use-case I would have appreciated a switch to skip conflict checking altogether
