### ISSUE TITLE
Conda 4.9 broke conda-forge clean install

### ISSUE THREAD

**Issue by hyperknot** [conda/conda#10341]
From: https://github.com/conda-forge/conda-forge.github.io/issues/1176

- - -
Issue: An install command broke which I have been using for a long time without faults. In it's most minimal form something as simple as `conda install python=3.7` is broken as well.

<br/>
Environment (<code>conda list</code>)
Details about  <code>conda</code> and system ( <code>conda info</code> )

I cannot run it as install doesn't complete. It's an Ubuntu based 16.04 Docker image on x64, the install is always clean as its a Docker image.

Here is the command I've always been using:

```
wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
conda update conda -y
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install python=3.7
```

Install log
[conda.log](https://github.com/conda-forge/conda-forge.github.io/files/5467256/conda.log)

- - -
The problem is with `conda update conda`. If I skip that command (which means conda 4.8.3) or specify conda 4.8.5 it works.
However once updated to conda 4.9 it breaks install.

- - -
* information: I've changed the whole script to miniforge and it works out-of-the box, with and without update. (Although update seems to have no effect on miniforge).

I'll be changing my Dockerfiles to miniforge and leave this here because as of today, conda 4.9.x + conda-forge is broken.

**Comment by chenghlee** [comment]
Try `conda install python=3.7 conda=4.9.0`, or running the `conda config` commands _before_ running `conda update`. With your sequence of operations, `conda install python=3.7` is getting stuck because you have strict channel priority on, and that install command will implicitly trigger a replacement of the defaults conda with conda-forge conda that the solver can't easily handle without some human help.

**Comment by hyperknot** [comment]
- I have been following the official conda-forge instructions to get here.
- This has been working for years, but it broke in 4.9.
- I solved my issue by migrating to mini-forge, but I wanted to raise it here since it's broken in 4.9.
