### ISSUE TITLE
Conda 4.8.3  freezes ubuntu 20.04

### ISSUE THREAD

**Issue by Zehndiii** [conda/conda#10352]
Hello,
My conda installation is somehow broken. I updated to ubuntu 20.04 and since then i can't run conda info or conda update. Every time i start the comand the whole machine is freezing and no user input is accepted. There is no error shown. I tried a clean install and conda executables but even they failed. 
I think the problem lies deeper in the system but i have no clue were to start looking. Thx for your help. 

## Current Behavior
When I run conda info or conda update ANYPACKAGE the command starts executing and after a short time the whole Machine freezes and no keyboard or mouse input is possible. There are no error messages. Only a hard reboot is possible. 

### Steps to Reproduce

```
open terminal
run: conda info

or 

run: conda update conda
```

## Expected Behavior

Conda should update packages or show info. Or at least show a error message. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

Ubuntu 20.04
conda -V 
  4.8.3
conda info is crashing...

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

**Comment by rmurphy2718** [comment]
I am also facing this issue, have you solved it?

**Comment by Zehndiii** [comment]
No unfortunately not, I ended up doing a clean install of my whole system...

**Comment by rmurphy2718** [comment]
@Zehndiii : I did not have to reinstall ubuntu, but I did entirely wipe anaconda from my computer and reinstall from scratch.  It did work, although it's not a satisfying solution.

The following post shows what needs to be deleted (`rm -rf`) when completely wiping anaconda,
https://stackoverflow.com/questions/59166966/trying-to-use-conda-install-to-get-anaconda-clean-but-environment-fails-to-solve

**Comment by radscience** [comment]
Same issue here.  Went from working to not working.  There was a disk-full issue somewhere in between during  a conda install operation, suspect something got borked.

**Comment by bluelancer** [comment]
Same +1
working on `conda 4.12.0` 
`Ubuntu 20.04.4 LTS`
