### ISSUE TITLE
Update problem with pandas v0.15.1

### ISSUE THREAD

**Issue by MMCMA** [conda/conda#1035]
I have updated my pandas version from v0.14.1 to v0.15.1 and now it does not let me import pandas anymore - i downgraded back to v0.14.1 and it works fine with that. My OS is win8.1 and I use python 3.4. The following errors occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pandas__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib
ImportError: cannot import name 'hashtable'

**Comment by soapy1** [comment]
@MMCMA the newest version of pandas now is 0.19.0, is this still an issue for you?

**Comment by MMCMA** [comment]
No, I don't have this problem anymore. Feel free to close it.
