### ISSUE TITLE
How to repair miniconda? [Anaconda Prompt (Miniconda3) - ModuleNotFoundError: No module named 'conda']

### ISSUE THREAD

**Issue by ghuname** [conda/conda#10354]
## Current Behavior

I was using jupyterlab notebook and PyCharm professional at the same time.
At one moment I clicked on ipynb file in PyCharm and PyCharm opened view in which I was able to see notebook cells in two columns. Left input, right output.
At one moment PyCharm showed the notice that there is no package jupyter and asked do I want to install it.
As I was able to see notebook in PyCharm I havent installed anything, but from that point in time my conda environment is broken. I am not sure whether it is related to PyCharm. 

Anyway, the situation is now like this.
If I open Anaconda Prompt (Miniconda3) I get:

```
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

I tried:

```
C:\Users\user\Miniconda3\Scripts>conda
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

And (notice "_" before conda):

```
C:\Users\user\Miniconda3>_conda info --envs
# conda environments:
#
base                  *  C:\Users\user\AppData\Local\Temp\_MEI103562
                         C:\Users\user\Miniconda3
...
```

As I can see, I can still run different versions of pythons from my environments, but I cannot use conda commands.
What are my options now?
How to repair miniconda instalation?

### Steps to Reproduce

```
I don't know how it happened. I haven't installed or updated any package.
```

## Expected Behavior

Conda environment should never be broken.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
As conda is not working I cannot provide an information.



┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-275)

**Comment by chenghlee** [comment]
You could try `_conda install -p C:\Users\user\Miniconda3 --force-reinstall conda` (note the prefix `_`).

**Comment by ghuname** [comment]
@chenghlee Thanks for a suggestion.
I reinstalled everything and now I am looking for a docker solution.
At the moment I am experimenting with https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile
