### ISSUE TITLE
pip_interop_enabled = true but updating pip installed package to same version

### ISSUE THREAD

**Issue by memeplex** [conda/conda#10362]
## Current Behavior
I created a new environment with pip interoperability enabled. I installed numpy 1.19.4 using pip, then installed scipy using conda and I get:

```
The following packages will be UPDATED:

  numpy                      pypi/pypi::numpy-1.19.4-pypi_0 --> conda-forge/osx-64::numpy-1.19.4-py39hd3e5478_1
```

Maybe I'm wrong, but I had assumed that interoperability meant to keep the pip installed package when it happened to be of a compatible (or exactly the same, as in this case) version.

### Steps to Reproduce
1. Put `pip_interop_enabled: true` in `~/.condarc`.
1. Create and activate a new conda environment.
1. `pip install numpy`
1. `conda install scipy`.

## Expected Behavior
The pip installed package is used instead of being overwritten by a conda equivalent (?) package.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test
    active env location : /Users/carlos/Conda/miniconda3/envs/test
            shell level : 2
       user config file : /Users/carlos/.condarc
 populated config files : /Users/carlos/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/carlos/Conda/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/carlos/Conda/miniconda3/pkgs
                          /Users/carlos/.conda/pkgs
       envs directories : /Users/carlos/Conda/miniconda3/envs
                          /Users/carlos/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.8.6 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-280)

**Comment by chenghlee** [comment]
Can you please provide the output of `conda info --show-sources` and `conda list --show-channel-urls`? Something like channel priority or build number priority may be kicking in and triggering the replacement of the pypi package.
