### ISSUE TITLE
How to solve CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json> error while trying to create a new environment using conda

### ISSUE THREAD

**Issue by dohawaaelazab** [conda/conda#10367]
Hi  :raised_hand_with_fingers_splayed:, I am a beginner using conda and whenever i try to create a **virtual environment using conda** using the following code i do get this error 

>(base) C:\Users\Asus\Desktop>conda create -n myenv python=3.3 anaconda

```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/win-64'
```

pls help me and explain step by step as i am beginner 
thanks in advance

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-283)

**Comment by simondobers** [comment]
Hi :)

Do you use a VPN?
I got this error when I tried to create an environment or install packages from my employer's network.

If yes, then disable the VPN and try again :)

Best regards

**Comment by chenghlee** [comment]
@dohawaaelazab: are you still running into this issue?
