### ISSUE TITLE
version sorting wrong

### ISSUE THREAD

**Issue by Optiligence** [conda/conda#10395]
## Current Behavior

> The following packages will be DOWNGRADED:
> 
>   pytorch             1.7.0-py3.8_cuda10.1.243_cudnn7.6.3_0 --> 1.7.0-py3.8_cuda11.0.221_cudnn8.0.3_0

### Steps to Reproduce

`.condarc`

```
pinned_packages:
  - cudatoolkit < 10.2
```

install pytorch, remove pin, update

## Expected Behavior

it should show UPGRADED because the version naturally sorts higher
_or_ it should be under a category »different flavor« instead

## Environment Information
```
conda version : 4.9.2
```

**Comment by heplesser** [comment]
I observe similar behavior, e.g.

```
cython                             0.29.24-py38h23ab428_0 --> 0.29.24-py38he9d5cce_0
```

According to `conda search cython --info`, we have the following build dates

- py38h23ab428_0: 2021-07-14
- py38he9d5cce_0: 2021-11-04

So why does conda think this is a downgrade?
