### ISSUE TITLE
I'm getting problem with tensorflow and cuda versions regulary.. which is the stable configuration for tensorflow and cuda versions

### ISSUE THREAD

**Issue by Maneeshmohan1** [conda/conda#10408]
## Steps to Reproduce

```
< paste conda_debug_output.txt here, or attach it as a file to this report >

```

```
< paste contents of ~/.conda/instrumentation-record.csv here, or attach it as a file to this report >
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

- - -

**Comment by kenodegard** [comment]
Not enough details are included for us to investigate this issue. Please provide additional on how to replicate the problem/what the problem is.
