### ISSUE TITLE
channel_alias:: The term 'channel_alias:' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by GF-Huang** [conda/conda#10406]
![image](https://user-images.githubusercontent.com/4510984/101794461-dce76f80-3b41-11eb-8c04-8e50180251ea.png)

![image](https://user-images.githubusercontent.com/4510984/101794570-f8527a80-3b41-11eb-8bde-1046587f323d.png)

**Comment by GF-Huang** [comment]
![Uploading image.png…]()

**Comment by cjmartian** [comment]
Try doing:

conda config --add channel_alias <Your Channel>

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/101979937-5dba7e80-3c9c-11eb-825e-9caf4c536d06.png)

**Comment by cjmartian** [comment]
Ah! Appologies, it's `--set` not `--add`

`conda config --set channel_alias $Channel`

This should add a line to your `.condarc` file. 
You can also just edit that file manually.
