### ISSUE TITLE
no such option: --extra-index-url http://localhost:8080 / CondaValueError: pip returned an error

### ISSUE THREAD

**Issue by raffael-vogler-otto** [conda/conda#10415]
Hello!

This is the environment.yml file:

    name: project
    channels:
        - conda-forge
        - defaults
    dependencies:
      - black=19.10b0
      - numpy=1.19.1
      - pandas=1.1.2
      - pip=20.1.1
      - python=3.8
      - pip:
          - --extra-index-url http://localhost:8080

Based on it I intend to establish a virtual environment by:

    conda env create -f environment.yml

But this yield the following obscure error message:

    no such option: --extra-index-url http://localhost:8080
    
    CondaValueError: pip returned an error.

I don't know what to make of it as pip with version >= 20 definitely has such an option:

    john@dsb:~/workspace/project/python/project$ pip help install
    [...]
    Package Index Options:
    [...]
      --extra-index-url <url>     Extra URLs of package indexes to use in addition to --index-url. Should follow the same rules as --index-url.
    [...]

Any ideas?

Thanks

---

- Python 3.8.6
- pip 20.1.1
- conda 4.3.30

**Comment by mfansler** [comment]
It's likely the outdated Conda. The full parsing capabilities in the `pip:` section were introduced in Conda v4.4 (see #3969).

**Comment by raffael-vogler-otto** [comment]
Thanks @mfansler
