### ISSUE TITLE
root library access by conda

### ISSUE THREAD

**Issue by bernardchaurand** [conda/conda#10423]
┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-322)

**Comment by bernardchaurand** [comment]
i work with anaconda
i want to use root library
conda search root said that root is not accessible

**Comment by chenghlee** [comment]
Are you talking about the [CERN ROOT](https://root.cern/) libraries? If so, try using the `conda-forge` channel (i.e., `conda install -c conda-forge root`).

**Comment by bernardchaurand** [comment]
i try it in my anaconda version and i get the response
The following packages are not avaible from current channels 
- root
my current channels are :
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by bernardchaurand** [comment]
Je travaille avec anaconda je voudrais utiliser root la Library du CERN si j'utilise Conda pour la charger 
il ne la trouve pas dans les canaux accessibles
la liste de mes canaux actuels est:
https://conda.anaconda.org/conda-forge/win-64
https://conda.anaconda.org/conda-forge/noarch
https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
