### ISSUE TITLE
Command to remove orphaned dependencies

### ISSUE THREAD

**Issue by naught101** [conda/conda#10424]
Conda envs have a tendency to get bigger over time, especially when exploring avenues for new features that try out new packages. This becomes a problem, as the bigger the env gets, the slower conda gets. It's possible to manually trim the fat, but this can be hard, because the dependency graph isn't easily accessible, and even if you remove packages that you've installed, it's easy to leave tonnes of dependencies installed. It would be really nice to have a tool to list and/or remove all non-required packages, and all un-used dependencies.

One way to do this might be to allow packages to be marked as manually installed (not sure if this is already possible or not), and then remove all packages that are not required by those packages.

Another way might be to simply list all packages that are not a dependency of something else (leaf nodes on the dependency graph), and then the user can manually choose to remove the un-needed packages in that list. Doing this a few times in a row should clean out the environment of orphaned dependencies.

**Comment by Mathemilda** [comment]
Hello,
it is unpleasant. You may look at Miniconda, where at least not every Anaconda feature is installed.
A possible trick is that some packages may be removed if they are depreciated. 
Use the following command:
```
conda clean --all
```
Best regards,
Mya

**Comment by kenodegard** [comment]
As a rule of thumb, it is recommended to create new environments anytime you are experimenting and only selectively install new packages (if any) into your base environment.

Check out [conda-tree](https://github.com/conda-incubator/conda-tree) if you want to inspect the dependency graph, this will allow you to perform the selective leaf node pruning suggested above.
