### ISSUE TITLE
warning `.conda\pkgs` does not exist when running `conda clean --all`

### ISSUE THREAD

**Issue by mghanava** [conda/conda#10434]
I am not able to install `pgmpy` package. I get this error: 

```
InvalidArchiveError('Error with archive C:\\Users\\mghan\\miniconda3\\pkgs\\pgmpy-0.1.12-py37_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
```

I have tried `conda clean --all`. It cleans everything but raises these two warnings, too:

```
WARNING: C:\Users\mghan\.conda\pkgs does not exist 
WARNING: C:\Users\mghan\AppData\Local\conda\conda\pkgs does not exist
```

The package owner suggests there is a problem with my `conda` not their package. Any help is appreciated, I am really stuck!

**Comment by mghanava** [comment]
I am not able to install pgmpy package. I get this error: 
InvalidArchiveError('Error with archive C:\\Users\\mghan\\miniconda3\\pkgs\\pgmpy-0.1.12-py37_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
I have tried conda clean --all. It cleans everything but raises these two warnings, too:
WARNING: C:\Users\mghan\.conda\pkgs does not exist 
WARNING: C:\Users\mghan\AppData\Local\conda\conda\pkgs does not exist

Package holder suggests there is a problem with my conda not his package. Any help appreciated, I am really stuck!

**Comment by sbalk** [comment]
Hi @mghanava,

I had the same problem and ran `conda update conda`.
After completion I again ran `conda clean --all`.
This time, conda could find the correct /pkgs folder (for me it was in miniconda and not in .conda).

Hope that helps

**Comment by imingx** [comment]
My cache location should be `/Users/gmm/opt/miniconda3/pkgs`, but it got:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/54981719/169272908-08502c25-4cd9-40cf-9ba3-f72c86421643.png">
