### ISSUE TITLE
Suggestion: conda create should not remove existing environment so easily

### ISSUE THREAD

**Issue by vfilimonov** [conda/conda#10432]
When calling `conda create` without the option `--name`, conda asks if you would like to remove existing environment

```
~ ❯❯❯ conda create test
WARNING: A conda environment already exists at '/Users/user/miniconda3/envs/main'
Remove existing environment (y/[n])?
```

As it looks to me - this is a dangerous operation because hitting key `y` will immediately wipe user's active environment with all installed packages. I suggest that this step should not be performed that easily and instead the user should be asked to actively call `conda remove --name <name> --all` before calling conda create in this case.

It is quite rare that the user wants to recreate existing environment and more likely that the key `--name` is simply forgotten. So given the potential harm of accidental `y` I think it would be good to introduce some additional safeguard.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-330)

**Comment by BrenBarn** [comment]
I agree.  The `--name` argument should be mandatory for `conda create`.

**Comment by BrenBarn** [comment]
It looks like this has now been fixed, as conda create requires either `--name` or `--prefix` to be specified, and shows an error if neither is given.
