### ISSUE TITLE
Multiple dev_urls and doc_urls

### ISSUE THREAD

**Issue by BastianZim** [conda/conda#10455]
Hi, I was wondering if it is possible to use multiple _dev_urls_ and _doc_urls_ in a recipe? I originally created https://github.com/conda-forge/conda-smithy/issues/1432 at conda-forge to ask this question but we weren't sure if that might break something on Conda's side?

**Comment by jakirkham** [comment]
Any reason this was closed?

**Comment by BastianZim** [comment]
Because, at least to my understanding, this is impossible currently since the Anaconda infrastructure seems to be setup for only one url (Example: https://conda-static.anaconda.org/main/) and I didn't want to pollute the issues pages. 
Do you disagree?

**Comment by BastianZim** [comment]
I can definitely keep it open but I just don't see a way to support this currently.

**Comment by jakirkham** [comment]
Well it won't be supported if there isn't an open issue tracking the need 😉

Would recommend including your use case as well for context

**Comment by BastianZim** [comment]
Makes sense. 😄
I'll reformat this as a feature request and include everything there.

**Comment by BastianZim** [comment]
Has been re-added as a feature request.

**Comment by jakirkham** [comment]
Thanks Bastian! 😀

Feature request in issue ( https://github.com/conda/conda/issues/10504 )
