### ISSUE TITLE
Windows installer deleted all my files on desktop

### ISSUE THREAD

**Issue by yannickbt** [conda/conda#10451]
Hi,

I have installed Miniconda3 for "All Users" on my Windows 10 machine.

However, I wanted to a get rid of a petty/annoying warning about how I need to activate my conda environment (which I never had in previous versions). Since I set my PATHs like a big boy in .bat file ran at cmd execution, I thought perhaps reinstalling it with "Set PATH environment" checked would solve the issue. So I desinstalled it.

Except... when desinstalling it removed recursively my files in my desktop folder (the folders are there, but most files disappeared). Great.

I'm not sure if the bug can be reproduced unless you install just like I did, i.e. for "All Users" (thus gaining admin privileges).
Otherwise I used the default options (installed in C:\ProgramData\Miniconda3).

So the steps to reproduce would be :

* Install latest installer (SHA1 4fa22bba0497babb5b6608cb8843545372a99f5331c8120099ae1d803f627c61) disponible at https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
* Install for "All Users", give admin privileges upon asked
* Choose default options otherwise
* Wait for the installation to complete. Click "Finish".
* Go to control panel and "Program and Features"
* Uninstall Miniconda3
* The files in C:\users\username\Desktop should be removed. Like PDF files (all of mine have been wasted). Strangely some .doc and .xlsx files remain. Could it be a directory name issue? Mine is "C:\Users\y.bertrand\Desktop", I wondered if the "." in "y.bertrand" could make this happen. The directory structure remains intact though. It's the files inside those directories that aren't present anymore.

**Comment by Shigeto1** [comment]
this just happened to me too. what the fuck. 300gb of files just gone from my ssd. how is this possible?

**Comment by kenodegard** [comment]
Strictly speaking this isn't a conda issue and hence should instead be opened at https://github.com/ContinuumIO/anaconda-issues/.

But I will seek to escalate this.

**Comment by beeankha** [comment]
Hi @yannickbt  , I re-filed this issue in the  [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (the place for `conda` installer issues); closing this out, you can track your newly re-filed issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/12936)
