### ISSUE TITLE
miniconda on freebsd

### ISSUE THREAD

**Issue by xyderos** [conda/conda#10450]
Hi,

I recently migrated to FreeBSD and at the same time i am working concurrently on a project in Python.

I have been using miniconda for a while on a macOS but i figured out that i cannot download miniconda on FReeBSD(at least there is no available package).

Is there a way to build from source(eg a Makefile or a script)?

There is always the option to use jails or just run a linux kernel module but to be on the safe sife i wanted to try to see if i can actually build miniconda.

Thanks

**Comment by mingwandroid** [comment]
It can be installed via python setup.py develop. Then once installed you
can use it to build a package for itself.

But you'd need to add support for freebsd as a subdir too.

Good luck!

**Comment by mausch** [comment]
I'm also interested in this. However I can't seem to find the docs or scripts to build Miniconda from source...

**Comment by xyderos** [comment]
@mausch Hi, I solved this issue a long time ago, sorry for not mentioning that earlier. Instead of building miniconda from source and messing around with porting libraries and packages in order to fit FreeBSD, you should:

1) Enable the `Linux Compatibility Layer`.
2) Mount at `fstab` the appropriate filesystems that `Linux` supports.
3) Go [here](https://docs.conda.io/en/latest/miniconda.html) and choose which version suits you best (eg which `Python` version you want and the architecture of your machine) and download the .sh file that your browser will ask you based on your choice.
4) Open your terminal and then go ( `cd` ) at `Downloads`.
5) The default shell that FreeBSD uses is `sh` , so just type `bash` to change your shell and as soon as you swap to bash, type `bash theNameOfTheDotSHFile`.

This is an interactive guide that will help you install `Miniconda`, I don't exactly remember the questions but they are pretty straightforward and easy to follow.

For the first 2 steps, feel free to use the [handbook](https://docs.freebsd.org/en/books/handbook/) in order to activate and properly set it up.

HINT: If you want to be done fairly fast, check [this](https://www.youtube.com/watch?v=mxJ3vW8N9vw&list=PLblrruCjl0LPYoIACdGogUlMYRno0x7ry&index=5) out at 31:00 where there is a guy installing layer mentioned at step 1 fast and clear.

**Comment by xyderos** [comment]
Essentially, you are using the already ported libraries from Linux to FreeBSD and its working just as great. However, I had some issues when installing some packages from a `.yml` file so when you import your project, try to install the packages you need by hand since if your environment came from `Linux` most of the libraries you will download will be incompatible, so by doing that by hand `pip` will find what you need.

**Comment by granalberto** [comment]
> It would be a lot of work but its possible. Yoy need to build about 30 to 40 packages and add subdir support for frebsd to conda and conda-build too. I would initially cross compile it from Linux until you have enough to self host.

Kindly ask you to share where to find documentation with the process to follow. I'd like to use the FreeBSD's porting framework so we can just install `conda` as a native package.
