### ISSUE TITLE
New created environment was not taken as conda environment 

### ISSUE THREAD

**Issue by ahua217** [conda/conda#10463]
Hello! I used `conda create -n P2.7 python=2.7` to create a new environment. However, it does not show up in `conda info --envs` results. And `conda list` does not work in it either, though `source activate P2.7` works.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

![image](https://user-images.githubusercontent.com/71511628/104831290-70a10f80-5855-11eb-87be-ddc4ac2eab01.png)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

> (base) ahua217@DESKTOP-CVSDKH5:~$ conda activate P2.7
> (P2.7) ahua217@DESKTOP-CVSDKH5:~$ conda info
> 
>      active environment : P2.7
>     active env location : /e/biosoft/miniconda3/envs/P2.7
>             shell level : 2
>        user config file : /home/ahua217/.condarc
>  populated config files : /home/ahua217/.condarc
>           conda version : 4.9.2
>     conda-build version : not installed
>          python version : 3.8.5.final.0
>        virtual packages : __glibc=2.31=0
>                           __unix=0=0
>                           __archspec=1=x86_64
>        base environment : /e/biosoft/miniconda3  (writable)
>            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://conda.anaconda.org/bioconda/linux-64
>                           https://conda.anaconda.org/bioconda/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /e/biosoft/miniconda3/pkgs
>                           /home/ahua217/.conda/pkgs
>        envs directories : /mnt/e/biosoft/miniconda3/envs
>                           /e/biosoft/miniconda3/envs
>                           /e/biosoft/miniconda3/envs/P2.7
>                           /home/ahua217/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.4.0-19041-Microsoft ubuntu/20.04.1 glibc/2.31
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : False

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
All of them including miniconda itself were installed with the latest versions today. And the directory "/e/biosoft/miniconda3/envs/P2.7" indeed exist. How can I fix it? Thank you very much!

**Comment by MolianWH** [comment]
try to unactivate your base environment and then create another environment and check your envs list.

**Comment by ahua217** [comment]
Yeah, it works this way. Thank you very much MolianWH!
It is my first time to know that "conda create" can be used before the base environment is activated. I still have a question. How can I delete those "sub-environments" created under base environment if they are not taken as conda environments?

**Comment by ahua217** [comment]
I found all the environments I previously created cannot be created again even if I do this out of base environment and even if I uninstall and reinstall miniconda.

**Comment by ahua217** [comment]
I uninstall and reinstall conda, cleaned envs dir, and  tried `conda create -p /e/biosoft/miniconda3/P2.7 python=2.7`. However, it still failed  and I received such an error report
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 231, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 590, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 411, in _verify_individual_level
        error_result = axn.verify()
      File "/e/biosoft/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/e/biosoft/miniconda3/lib/python3.8/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/e/biosoft/miniconda3/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'

`$ /e/biosoft/miniconda3/bin/conda create -p /e/biosoft/miniconda3/P2.7 python=2.7`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/e/biosoft/miniconda3/bin/conda
             CONDA_PREFIX=/e/biosoft/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/e/biosoft/miniconda3/bin/python
               CONDA_ROOT=/e/biosoft/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/e/biosoft/miniconda3/bin:/e/biosoft/miniconda3/bin:/e/biosoft/minicon
                          da3/condabin:/home/ahua217/.local/bin:/usr/local/sbin:/usr/local/bin:/
                          usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/Program Fi
                          les/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_
                          x64__79rhkp1fndgsc:/c/Program Files (x86)/Intel/Intel(R) Management
                          Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management
                          Engine Components/iCLS:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/Syste
                          m32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System3
                          2/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine
                          Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine
                          Components/DAL:/e/Program Files (x86)/Paragon Software/LinuxFS for
                          Windows:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/Do
                          ckerDesktop/version-
                          bin:/c/Users/ahua2/AppData/Local/Microsoft/WindowsApps:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /e/biosoft/miniconda3
            shell level : 1
       user config file : /home/ahua217/.condarc
 populated config files : /home/ahua217/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /e/biosoft/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /e/biosoft/miniconda3/pkgs
                          /home/ahua217/.conda/pkgs
       envs directories : /e/biosoft/miniconda3/envs
                          /home/ahua217/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.4.0-19041-Microsoft ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by ahua217** [comment]
The problems were gone after I chose the default directory during miniconda installation.
