### ISSUE TITLE
Error installing Anaconda2

### ISSUE THREAD

**Issue by celinasjose** [conda/conda#10482]
Hi!
I used the following command to install Anaconda2, as depicted in the website.
> bash Anaconda2-2019.10-Linux-x86_64.sh

And got the following error
'''[/mnt/i3S/homes/cjose/anaconda2] >>>
PREFIX=/mnt/i3S/homes/cjose/anaconda2
WARNING: md5sum mismatch of tar archive
expected: 9d5bdede6f0bb1797422bb1a2284b4e6
     got: c7e5bd3ae7eb01dc90105a5e87eb03a1  -
Unpacking payload ...
[107588] Error -3 from inflate: incorrect header check
[107588] Error decompressing Crypto/Cipher/_AES.cpython-37m-x86_64-linux-gnu.so
Failed to write all bytes for Crypto/Cipher/_AES.cpython-37m-x86_64-linux-gnu.so
fwrite: Bad address
[107605] Error -3 from inflate: incorrect header check
[107605] Error decompressing Crypto/Cipher/_AES.cpython-37m-x86_64-linux-gnu.so
Failed to write all bytes for Crypto/Cipher/_AES.cpython-37m-x86_64-linux-gnu.so
fwrite: Bad address
'''

Python 2.7.5

Can you help me solve this issue?
thanks in advance,
Celina

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-356)

**Comment by chenghlee** [comment]
`WARNING: md5sum mismatch of tar archive` suggests that the installer was downloaded incorrectly. Can you please that the MD5 checksum of the installer (`md5sum Anaconda2-2019.10-Linux-x86_64.sh`) is 69c64167b8cf3a8fc6b50d12d8476337?
