### ISSUE TITLE
Debian package is not up-to-date

### ISSUE THREAD

**Issue by allefeld** [conda/conda#10489]
I have conda (Miniconda) installed from the [Debian repository](https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html). However, often when I run conda to install a package, it complains that I'm not using the latest version:

````
==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda
````

That's though I just updated all Debian packages, and apparently the newer version is not in the repository <https://repo.anaconda.com/pkgs/misc/debrepo/conda>. Could you please update the repository as soon as a new version is released?

As a minor thing: The message is misleading. The page linked to above says

> It is recommended to use this installation in a read-only manner and upgrade conda using the respective package manager only.

Updating the base environment would have to be done as root, and could interfere with the regular update mechanism.

**Comment by chenghlee** [comment]
I'll take a look and make sure the updated package is available.

**Comment by chenghlee** [comment]
@allefeld: the conda 4.9.2 deb should now be available.

**Comment by allefeld** [comment]
Thanks! Is there a way you can integrate deb-generation into your release workflow, so that every time there is a new conda version there is also a new Debian package?

**Comment by chenghlee** [comment]
Yes; we are currently re-working the conda release tooling to ensure rpm/deb packaging is included. Going ahead and closing this ticket.

**Comment by allefeld** [comment]
Is there any news on this? At least conda should not give wrong advice:

```
==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.

Please update conda by running

    $ conda update -n base -c defaults conda
```

**Comment by Phidica** [comment]
Still the same problem, months later. Stuck on 4.9.2 from the Debian repo, while conda warns me that 4.10.3 is available.

By the way, should I be worried that visiting the repository link https://repo.anaconda.com/pkgs/misc/debrepo/conda returns a 404 page, or is this normal?
