### ISSUE TITLE
Cross-compiler package problem. 

### ISSUE THREAD

**Issue by lisa-maiya** [conda/conda#10485]
Hello, I've been having problems recently when I open my terminal. This issue happened right after installing a conda package. Whenever I log in, I get these error messages:

ERROR: This cross-compiler package contains no program /home/ubuntu/miniconda3/bin/x86_64-conda-linux-gnu-cc
ERROR: This cross-compiler package contains no program /home/ubuntu/miniconda3/bin/x86_64-conda-linux-gnu-gfortran
ERROR: This cross-compiler package contains no program /home/ubuntu/miniconda3/bin/x86_64-conda-linux-gnu-c++
ERROR: activate-gxx_linux-64.sh failed, see above for details

I am no entirely sure how to proceed, can anyone help? Thanks very much in advance.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-359)

**Comment by chenghlee** [comment]
Can you provide the output of `conda list` in that environment?

**Comment by lisa-maiya** [comment]
Sure, see below: 

WARNING conda.core.prefix_data:_load_site_packages(295): Problem reading non-conda package record at lib/python3.7/site-packages/setuptools-49.6.0.post20210108-py3.7.egg-info/PKG-INFO. Please verify that you still need this, and if so, that this is still installed correctly. Reinstalling this package may help.
WARNING conda.core.prefix_data:_load_site_packages(295): Problem reading non-conda package record at lib/python3.7/site-packages/DendroPy-4.5.1-py3.8.egg-info/PKG-INFO. Please verify that you still need this, and if so, that this is still installed correctly. Reinstalling this package may help.
# packages in environment at /home/ubuntu/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
abricate                  1.0.1                h1341992_0    bioconda
alsa-lib                  1.2.3                h516909a_0    conda-forge
any2fasta                 0.4.2                         2    bioconda
aragorn                   1.2.38               h516909a_3    bioconda
argcomplete               1.11.1             pyh9f0ad1d_1    conda-forge
argh                      0.26.2                py37_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
barrnap                   0.9                           3    bioconda
bedtools                  2.30.0               hc088bd4_0    bioconda
binutils_impl_linux-64    2.34                 h53a641e_2    conda-forge
binutils_linux-64         2.34                h47ac705_27    conda-forge
biopython                 1.77             py37h8f50634_0    conda-forge
blas                      1.0                         mkl
blast                     2.9.0           pl526h3066fca_4    bioconda
blast-legacy              2.2.26                        2    bioconda
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost                     1.67.0                   py37_4
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
cd-hit                    4.8.1                h8b12597_3    bioconda
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
clonalframeml             1.12                 hc9558a2_0    bioconda
clustalw                  2.1                  hc9558a2_5    bioconda
conda                     4.9.2                    pypi_0    pypi
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cutadapt                  2.4              py37h14c3975_0    bioconda
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
dendropy                  4.4.0                      py_1    bioconda
dnaio                     0.3              py37h14c3975_1    bioconda
entrez-direct             13.3            pl526h375a9b1_0    bioconda
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
epride                    0.2dev                   pypi_0    pypi
expat                     2.2.9                h9c3ff4c_3    conda-forge
fasttree                  2.1.10               h516909a_4    bioconda
figtree                   1.4.4                         0    bioconda
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.9                h516909a_0    conda-forge
gcc_impl_linux-64         9.3.0               h70c0ae5_18    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
gffutils                  0.10.1                     py_0    bioconda
gfortran_impl_linux-64    7.5.0               h56cb351_18    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.40.1               h0dab3d1_0    conda-forge
gsl                       2.4                  h14c3975_4
gxx_impl_linux-64         9.3.0               hd87eabc_18    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hmmer                     3.3.1                he1b5a44_0    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
infernal                  1.1.3                h516909a_0    bioconda
intbitset                 2.4.0            py37h8f50634_1    conda-forge
intel-openmp              2019.4                      243
ipykernel                 5.3.0            py37h43977f1_0    conda-forge
ipython                   7.14.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
iqtree                    2.0.3                h176a8bc_0    bioconda
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab_server         1.1.5                      py_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_2    conda-forge
libboost                  1.67.0               h46d08c1_4
libcurl                   7.68.0               hda55be3_0    conda-forge
libdb                     6.1.26                        0    bioconda
libedit                   3.1.20191231         h46ee950_2    conda-forge
libfaketime               0.9.8                h516909a_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     9.3.0               h7864c58_18    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgd                     2.2.5             h0d07dcb_1005    conda-forge
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn11                  1.34                 h1cef754_0    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-devel_linux-64  9.3.0               hb016644_18    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h58526e2_1007    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
libxslt                   1.1.32            hae48121_1003    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
llvmlite                  0.32.0           py37h5202443_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mafft                     7.475                h516909a_0    bioconda
make                      4.3                  h516909a_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
mash                      1.1                           0    bioconda
matplotlib-base           3.1.1            py37hfd891ef_0    conda-forge
mcl                       14.137          pl526h516909a_5    bioconda
minced                    0.4.2                         0    bioconda
mistune                   0.8.4           py37h8f50634_1001    conda-forge
mkl                       2019.4                      243
mkl-service               2.3.0            py37h516909a_0    conda-forge
mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
mlst                      2.19.0                        0    bioconda
mothur                    1.40.5               hb16dc7f_0    bioconda
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
numba                     0.49.1           py37h0da4684_0    conda-forge
numpy                     1.16.4           py37h7e9f1db_0    anaconda
numpy-base                1.16.4           py37hde5b4d6_0
openjdk                   11.0.8               hacce0ff_0    conda-forge
openmp                    7.0.0                h2d50403_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
paml                      4.9                  h516909a_5    bioconda
panaroo                   1.2.2                      py_0    bioconda
pandas                    0.24.2           py37he6710b0_0    anaconda
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           he7ab937_1005    conda-forge
parallel                  20201122             ha770c72_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-aceperl              1.92                    pl526_2    bioconda
perl-algorithm-diff       1.1903                  pl526_2    bioconda
perl-algorithm-munkres    0.08                    pl526_1    bioconda
perl-apache-test          1.40                    pl526_1    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-appconfig            1.71                    pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-array-compare        3.0.1                   pl526_1    bioconda
perl-array-utils          0.5                     pl526_2    bioconda
perl-autoloader           5.74                    pl526_2    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-bio-asn1-entrezgene  1.73                    pl526_1    bioconda
perl-bio-coordinate       1.007001                pl526_1    bioconda
perl-bio-featureio        1.6.905                 pl526_2    bioconda
perl-bio-phylo            0.58                    pl526_2    bioconda
perl-bio-samtools         1.43            pl526h1341992_1    bioconda
perl-bio-tools-phylo-paml 1.7.3                   pl526_1    bioconda
perl-bio-tools-run-alignment-clustalw 1.7.4                   pl526_1    bioconda
perl-bio-tools-run-alignment-tcoffee 1.7.4                   pl526_2    bioconda
perl-bioperl              1.7.2                  pl526_11    bioconda
perl-bioperl-core         1.007002                pl526_2    bioconda
perl-bioperl-run          1.007002                pl526_4    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-cache-cache          1.08                    pl526_0    bioconda
perl-capture-tiny         0.48                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-class-data-inheritable 0.08                    pl526_1    bioconda
perl-class-inspector      1.34                    pl526_0    bioconda
perl-class-load           0.25                    pl526_0    bioconda
perl-class-load-xs        0.10            pl526h6bb024c_2    bioconda
perl-class-method-modifiers 2.12                    pl526_0    bioconda
perl-clone                0.42            pl526h516909a_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-convert-binary-c     0.78            pl526h6bb024c_3    bioconda
perl-convert-binhex       1.125                   pl526_1    bioconda
perl-crypt-rc4            2.02                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-data-optlist         0.110                   pl526_2    bioconda
perl-data-stag            0.14                    pl526_1    bioconda
perl-date-format          2.30                    pl526_2    bioconda
perl-db-file              1.852           pl526h14c3975_0    bioconda
perl-dbd-sqlite           1.64            pl526h516909a_0    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-devel-globaldestruction 0.14                    pl526_0    bioconda
perl-devel-overloadinfo   0.005                   pl526_0    bioconda
perl-devel-stacktrace     2.04                    pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-digest-md5-file      0.08                    pl526_2    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-digest-sha1          2.13            pl526h6bb024c_1    bioconda
perl-dist-checkconflicts  0.11                    pl526_2    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-email-date-format    1.005                   pl526_2    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-error                0.17027                 pl526_1    bioconda
perl-eval-closure         0.14            pl526h6bb024c_4    bioconda
perl-exception-class      1.44                    pl526_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-find-rule       0.34                    pl526_5    bioconda
perl-file-grep            0.02                    pl526_3    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-slurp-tiny      0.004                   pl526_1    bioconda
perl-file-slurper         0.012                   pl526_0    bioconda
perl-file-sort            1.01                    pl526_2    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-font-afm             1.20                    pl526_2    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.71            pl526he860b03_0    bioconda
perl-getopt-long          2.50                    pl526_1    bioconda
perl-graph                0.9704                  pl526_1    bioconda
perl-graph-readwrite      2.09                    pl526_2    bioconda
perl-graphviz             2.24            pl526h734ff71_0    bioconda
perl-html-element-extended 1.18                    pl526_1    bioconda
perl-html-entities-numbered 0.04                    pl526_1    bioconda
perl-html-formatter       2.16                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tableextract    2.13                    pl526_2    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tidy            1.60                    pl526_0    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-html-treebuilder-xpath 0.14                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-image-info           1.38                    pl526_1    bioconda
perl-image-size           3.300                   pl526_2    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-sessiondata       1.03                    pl526_1    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-io-stringy           2.111                   pl526_1    bioconda
perl-io-tty               1.12                    pl526_1    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-ipc-run              20180523.0              pl526_0    bioconda
perl-ipc-sharelite        0.17            pl526h6bb024c_1    bioconda
perl-jcode                2.07                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-lib                  0.63                    pl526_1    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-libxml-perl          0.08                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-log-log4perl         1.49                    pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-lwp-simple           6.15            pl526h470a237_4    bioconda
perl-mailtools            2.21                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-math-derivative      1.01                    pl526_0    bioconda
perl-math-random          0.72            pl526h14c3975_2    bioconda
perl-math-spline          0.02                    pl526_2    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mime-lite            3.030                   pl526_1    bioconda
perl-mime-tools           5.508                   pl526_1    bioconda
perl-mime-types           2.17                    pl526_0    bioconda
perl-mldbm                2.05                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-module-runtime-conflicts 0.003                   pl526_0    bioconda
perl-moo                  2.003004                pl526_0    bioconda
perl-moose                2.2011          pl526hf484d3e_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-mro-compat           0.13                    pl526_0    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-number-compare       0.03                    pl526_2    bioconda
perl-ole-storage_lite     0.19                    pl526_3    bioconda
perl-package-deprecationmanager 0.17                    pl526_0    bioconda
perl-package-stash        0.38            pl526hf484d3e_1    bioconda
perl-package-stash-xs     0.28            pl526hf484d3e_1    bioconda
perl-params-util          1.07            pl526h6bb024c_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-parse-recdescent     1.967015                pl526_0    bioconda
perl-parse-yapp           1.21                    pl526_0    bioconda
perl-path-tiny            0.108                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-pdf-api2             2.035                   pl526_0    bioconda
perl-perlio-utf8_strict   0.007           pl526h6bb024c_1    bioconda
perl-pod-escapes          1.07                    pl526_1    bioconda
perl-pod-usage            1.69                    pl526_1    bioconda
perl-postscript           0.06                    pl526_2    bioconda
perl-role-tiny            2.000008                pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-set-scalar           1.29                    pl526_2    bioconda
perl-soap-lite            1.19                    pl526_1    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-sort-naturally       1.03                    pl526_2    bioconda
perl-spreadsheet-parseexcel 0.65                    pl526_2    bioconda
perl-spreadsheet-writeexcel 2.40                    pl526_2    bioconda
perl-statistics-descriptive 3.0702                  pl526_0    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-sub-exporter         0.987                   pl526_2    bioconda
perl-sub-exporter-progressive 0.001013                pl526_0    bioconda
perl-sub-identify         0.14            pl526h14c3975_0    bioconda
perl-sub-install          0.928                   pl526_2    bioconda
perl-sub-name             0.21                    pl526_1    bioconda
perl-sub-quote            2.006003                pl526_1    bioconda
perl-sub-uplevel          0.2800          pl526h14c3975_2    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-svg-graph            0.02                    pl526_3    bioconda
perl-task-weaken          1.06                    pl526_0    bioconda
perl-template-toolkit     2.26                    pl526_1    bioconda
perl-test                 1.26                    pl526_1    bioconda
perl-test-deep            1.128                   pl526_1    bioconda
perl-test-differences     0.67                    pl526_0    bioconda
perl-test-exception       0.43                    pl526_2    bioconda
perl-test-harness         3.42                    pl526_0    bioconda
perl-test-leaktrace       0.16            pl526h14c3975_2    bioconda
perl-test-most            0.35                    pl526_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-test-warn            0.36                    pl526_1    bioconda
perl-text-csv             2.00                    pl526_0    bioconda
perl-text-diff            1.45                    pl526_0    bioconda
perl-text-glob            0.11                    pl526_1    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-tie-ixhash           1.23                    pl526_2    bioconda
perl-time-hires           1.9760          pl526h14c3975_1    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-timedate             2.30                    pl526_1    bioconda
perl-tree-dag_node        1.31                    pl526_0    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-type-tiny            1.004004                pl526_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-unicode-map          0.112           pl526h6bb024c_3    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-dom              1.46                    pl526_0    bioconda
perl-xml-dom-xpath        0.14                    pl526_1    bioconda
perl-xml-filter-buffertext 1.01                    pl526_2    bioconda
perl-xml-libxml           2.0132          pl526h7ec2d77_1    bioconda
perl-xml-libxslt          1.94                    pl526_1    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-regexp           0.04                    pl526_2    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-sax-writer       0.57                    pl526_0    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xml-twig             3.52                    pl526_2    bioconda
perl-xml-writer           0.625                   pl526_2    bioconda
perl-xml-xpath            1.44                    pl526_0    bioconda
perl-xml-xpathengine      0.14                    pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pigz                      2.5                  h27826a3_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
plotly                    4.7.1              pyh9f0ad1d_0    conda-forge
prank                     v.170427             hc9558a2_3    bioconda
primer3-py                0.6.0                    pypi_0    pypi
prinseq                   0.20.4                        2    bioconda
prodigal                  2.6.3                h516909a_2    bioconda
prokka                    1.14.6                  pl526_0    bioconda
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-boost                  1.67.0           py37h04863e7_4
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyfaidx                   0.5.8                      py_1    bioconda
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.3                h0371630_0    anaconda
python-dateutil           2.8.1                      py_0    conda-forge
python-edlib              1.3.8.post1      py37h99015e2_1    bioconda
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.1           py37hac76be4_0    conda-forge
raxml-ng                  0.6.0                         0    genomedk
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
retrying                  1.3.3                      py_2    conda-forge
roary                     3.13.0          pl526h516909a_0    bioconda
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
scikit-learn              0.22.1           py37hd81dba3_0
scipy                     1.4.1            py37h0b6359f_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.4.0           py37hc8dfbb8_0    conda-forge
simplejson                3.17.0           py37h8f50634_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snp-dists                 0.7.0                hed695b0_0    bioconda
sqlite                    3.28.0               h8b20d00_0    conda-forge
sysroot_linux-64          2.12                 h3a0023d_3    conda-forge
t_coffee                  11.0.8           py37hea885bf_8    bioconda
tbl2asn-forever           25.7.2f              h516909a_0    bioconda
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tidyp                     1.04                 h516909a_2    bioconda
tk                        8.6.10               h21135ba_1    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
unzip                     6.0                  h7f98852_2    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vsearch                   2.13.6               h76f5088_0    bioconda
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xopen                     0.9.0            py37hc8dfbb8_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
