### ISSUE TITLE
No miniconda3-latest

### ISSUE THREAD

**Issue by twiecki** [conda/conda#1050]
There is a very useful `Miniconda-latest-Linux-x86_64.sh` in `http://repo.continuum.io/miniconda/` but not a corresponding file for Miniconda3. Having a link that doesn't change but always installs the latest version is very useful for deployments (e.g. in travis-ci or docker).

**Comment by ilanschnell** [comment]
These have been added for all the Miniconda installers.

**Comment by twiecki** [comment]
:+1:
