### ISSUE TITLE
Portable Miniconda still references user config and libs

### ISSUE THREAD

**Issue by thouseweart** [conda/conda#10502]
I am trying to create a completely portable/sandboxed Miniconda install on a shared network drive (G:\), that will work reproducibly in the same manner for all users.

I invoked the Miniconda installer on Windows 10 using the following flags:

```
    /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1
```

After installation, running "conda info -a" shows my user-specific info in the following places:

```
user config file : C:\Users\\[username]\\.condarc
populated config files : C:\Users\\[username]\\.condarc
package cache : C:\Users\\[username]\\.conda\pkgs
                          C:\Users\\[username]\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\\[username]\\.conda\envs
                             C:\Users\\[username]\AppData\Local\conda\conda\envs
conda environments: C:\Anaconda3.7  (and related sub-environments)
user site dirs: C:\Users\\[username]\AppData\Roaming\Python\etc
                      C:\Users\\[username]\AppData\Roaming\Python\Python37
                      C:\Users\\[username]\AppData\Roaming\Python\Python38
                      C:\Users\\[username]\AppData\Roaming\Python\Python39
                      C:\Users\\[username]\AppData\Roaming\Python\share
```

And in python, if I run
    `for thing in sys.path: print(thing)`
one of the paths is:
    C:\Users\\[username]\AppData\Roaming\Python\Python38\site-packages

Is there a way to make an even more portable install which does not reference user libraries and configurations as shown above?

Any input or suggestions are greatly appreciated, thanks for your time!  :blush:

**Comment by RoyiAvital** [comment]
Have you had any success with thi?
