### ISSUE TITLE
Importing pyplot leads to libSM.so.6

### ISSUE THREAD

**Issue by twiecki** [conda/conda#1051]
``` python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-789bfcc4f04f> in <module>()
      6 
      7 import matplotlib as mpl
----> 8 import matplotlib.pyplot as plt
      9 import seaborn as sns
     10 

/miniconda/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

/miniconda/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/miniconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py in <module>()
     15 from matplotlib.figure import Figure
     16 
---> 17 from .backend_qt5agg import NavigationToolbar2QTAgg
     18 from .backend_qt5agg import FigureCanvasQTAggBase
     19 

/miniconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     16 
     17 from .backend_agg import FigureCanvasAgg
---> 18 from .backend_qt5 import QtCore
     19 from .backend_qt5 import QtGui
     20 from .backend_qt5 import FigureManagerQT

/miniconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     29     figureoptions = None
     30 
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33 

/miniconda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py in <module>()
     89     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
     90 
---> 91         from PyQt4 import QtCore, QtGui
     92 
     93         try:

ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

This is with latest miniconda for python 2 linux 64 bit. Any idea? There is no libSM in `miniconda/lib`

**Comment by garcia-marc** [comment]
In case it can be useful, I also had this problem, because I'm using a server without X or any graphical environment. I start ipython notebook there, but I access it from a browser in a different host.

To fix this error in this case, I changed the backend of matplotlib in the ipython notebook settings (~/.ipython/profile_default/ipython_notebook_config.py or equivalent) adding:

    c.IPKernelApp.matplotlib = u'inline'

Besides fixing the error, with this setting it's not necessary anymore to use inside your notebook the command:

    %matplotlib inline

**Comment by benrbray** [comment]
I had this same problem on a remote instance and found that it was the order of cell magic / pyplot import that was causing the issue.  The following works for me:

```
%matplotlib inline
import matplotlib.pyplot as plt;
```

Calling these lines in the reverse order results in the libSM error because matplotlib tries to set up its graphical end.

**Comment by jonathan-svds** [comment]
I just wanted to add that this thread saved me quite a bit of time. Switching the two commands worked like @benrbray says.

**Comment by thitchen** [comment]
For me, switching those two does not work. I have to install `pyqt4` to solve the issue. 
See [this answer](http://stackoverflow.com/a/32389631/4015990) on OS.

**Comment by vicros** [comment]
This worked for me:
c.IPKernelApp.pyplot = u'inline'

**Comment by JuanSebastanCho** [comment]
@vicros solution worked for me! :D

**Comment by aditya-chaturvedi** [comment]
@benrbray - you rock!! for me, it was 2 steps - 

1) re-install matplotlib to get rid of the *png.so.6 error. 
2) inline matplotlib.

**Comment by shre81** [comment]
@benrbray Thanks my friend - I wish I'd reached here an hour back!
