### ISSUE TITLE
HTTP 403 Forbidden for URL windows

### ISSUE THREAD

**Issue by rayamoh** [conda/conda#10519]
Current behavior: 
Running conda install python==3.9.2 using conda-forge channel to install python 3.9.2 in the environment. I am getting HTTP 403 Forbidden error (Complete log) below.  Packages from default channel works , having this issue only for conda-forge channel. I have to use conda-forge to get python 3.9.2 as it is not present in default channel

Tried below ones , but did not work. Please assist

* Disabling SSL 
* Adding root certificate and anaconda cerficate (https://conda.anaconda.org/conda-forge/win-64/) from browser to cacert.pem at c drive (Anaconda3\Lib\site-packages\certifi) on my laptop

Complete log:

    `(ltcappsenv392) C:\Users\#userid>conda install python==3.9.2
    Collecting package metadata (current_repodata.json): done
    Solving environment: done
    
    ## Package Plan ##
    
      environment location: C:\Users\#userid\Anaconda3\envs\ltcappsenv392
    
      added / updated specs:
        - python==3.9.2
    
    
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        sqlite-3.34.0              |       h8ffe710_0         1.2 MB  conda-forge
        ------------------------------------------------------------
                                               Total:         1.2 MB
    
    The following NEW packages will be INSTALLED:
    
      certifi            pkgs/main/win-64::certifi-2020.12.5-py39haa95532_0
      pip                pkgs/main/win-64::pip-21.0.1-py39haa95532_0
      python             conda-forge/win-64::python-3.9.2-h7840368_0_cpython
      setuptools         pkgs/main/win-64::setuptools-52.0.0-py39haa95532_0
      sqlite             conda-forge/win-64::sqlite-3.34.0-h8ffe710_0
      tzdata             pkgs/main/noarch::tzdata-2020f-h52ac0ba_0
      wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
      wincertstore       pkgs/main/win-64::wincertstore-0.2-py39h2bbff1b_0
    
    
    Proceed ([y]/n)? y
    
    
    Downloading and Extracting Packages
    sqlite-3.34.0        | 1.2 MB    |                                                                              |   0%
    
    CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/win-64/sqlite-3.34.0-h8ffe710_0.tar.bz2>
    Elapsed: 00:00.863214
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.`

**Comment by arvindmail** [comment]
I have same issue:

Downloading and Extracting Packages
libpng-1.6.37        | 724 KB    |                                                                                                                                                                                                                                                                                                                |   0%
nbconvert-6.0.7      | 563 KB    |                                                                                                                                                                                                                                                                                                                |   0%

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.37-h1d00b33_2.tar.bz2>
Elapsed: 00:01.129110

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/win-64/nbconvert-6.0.7-py39hcbf5309_3.tar.bz2>
Elapsed: 00:02.939952

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
