### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [conda/conda#10517]

**Comment by mingwandroid** [comment]
For conda I agree that could be useful.

We don't have scripts to rebuild miniconda from scratch! It is a rolling distro which is bootstrapped by hand traditionally.

**Comment by abebeos** [comment]
> For conda I agree that could be useful.

I could not locate any info re "build from source", it usually returs info on "building conda packages". Any pointers?
 
> We don't have scripts to rebuild miniconda from scratch! It is a rolling distro which is bootstrapped by hand traditionally.

The "hands" usually execute some scripts, are those at lease available?

## Conda-Forge

(as a reference)

Not sure which distribution is the main one, but miniforge has a simple build-system, documented right within the README:

https://github.com/conda-forge/miniforge#usage
