### ISSUE TITLE
Installing Keras: Solving environment - failed

### ISSUE THREAD

**Issue by anoldmaninthesea** [conda/conda#10513]
I'm trying to install Keras with anaconda, and on https://anaconda.org/conda-forge/keras , it's stated that I should run `conda install -c conda-forge keras`.

Below is the output I got:

    C:\pathname>conda install -c conda-forge keras
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.

And then I just interrupted the process.

Why is this happening?

**Comment by BerginJay** [comment]
Maybe you should upgrade your environment first, then try to install again.

**Comment by anoldmaninthesea** [comment]
I decided to create a new environment, and reinstall keras on it, and it worked.

**Comment by BerginJay** [comment]
Maybe you should consider closing this issue.
