### ISSUE TITLE
CLI help message. Clarify difference between --live-stream and --no-capture-output options to `conda run`

### ISSUE THREAD

**Issue by lemontheme** [conda/conda#10558]
I'm trying to figure out which of these two options to use when running a process that streams logs to stdout. Here's the relevant parts of the help message returned by `conda run --help`.

```
  --no-capture-output    Don't capture stdout/stderr                                                                    
  --live-stream          Display the output for the subprocess stdout and stderr on real time.
```

Okay, so neither captures the stdout/stderr. Good. But one supposedly does it in real time. My best guess at the moment is that `--live-stream` is unbuffered and `--no-capture-output` is buffered?

How close am I? Anyway, probably a good idea to update the help message to make it easier to distinguish between the two.

**Comment by kenodegard** [comment]
@lemontheme We opted to merge these two features together in conda 4.13.0, using either argument will now produce the same unbuffered results.
