### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by pmarshwx** [conda/conda#1056]
My Python development environment consists of a system version of Python (built using homebrew) and various environments created and maintained by conda. I know the warning I'm getting states that I shouldn't use conda in an non [ana|mini]conda environment, but I don't use [ana|mini]conda for my default python as I can't build things such as matplotlib from source due to issues in finding dynamic library dependencies. Up until recently, I had no problems as I never installed modules into the default environment via conda. I merely used it to switch between various environments.

After updating to conda version 3.7.4, I can no longer switch into different environments. I get the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/conda/cli/main.py", line 67, in main
    activate.main()
  File "/usr/local/lib/python2.7/site-packages/conda/cli/activate.py", line 99, in main
    conda.install.symlink_conda(join(binpath, '..'), conda.config.root_dir)
  File "/usr/local/lib/python2.7/site-packages/conda/install.py", line 374, in symlink_conda
    os.symlink(root_conda, prefix_conda)
OSError: [Errno 17] File exists
```

If I go in and manually remove the **conda**, **activate**, and **deactivate** symlinks from the <env>/bin directory of an environment, I can switch in. However, the symlinks are never removed. I have to go into the environment's directory and remove the symlinks each time I want to switch to that environment.

Is this a bug or is this to prevent people from doing what I'm trying to do?

**Comment by dawalama** [comment]
I am seeing the same problem on my Mac, and thanks for explaining it @pmarshwx

**Comment by asmeurer** [comment]
So this is the same issue as https://github.com/conda/conda/issues/1100.

**Comment by kalefranz** [comment]
Outdated. Closing.
