### ISSUE TITLE
Inform the user about any pinned packages in conda info (or list or update)

### ISSUE THREAD

**Issue by jganseman** [conda/conda#10560]
Lately I had some trouble with the dreaded quasi-infinite dependency solving, in an environment that I hadn't used for a while and tried to update leading to inconsistency. Eventually I discovered the cause was a package pinned to a an ancient version in the `./env/conda-meta/pinned` file, that I had put there myself for who knows what reason I had at that time.

It would have saved me loads of time if `conda info`, `conda list`, or maybe even `conda update`, would have outputted somewhere that the current environment had packages pinned. I think it's useful, as pinning does affect the dependency solving process, and thus carries some risks for introducing inconsistency down the road.

* I imagine that in `conda info` a good begin would be to just display whether `./env/conda-meta/pinned` exists and is not empty. Maybe by adapting [main_info.py](https://github.com/conda/conda/blob/master/conda/cli/main_info.py) ?
* Or in `conda list` some marker could be added in the `Version` column to indicate we're dealing with a pinned package. (This could break scripts that depend on the tabular output as it is now, so maybe not a good idea to change in a minor release.)
* Or in the depths of the solver, it could print a warning if it is encountering a package that is pinned but for which newer versions exist.

If I find time I might give a shot at implementing the first option myself. Feel free to delete this feature request if not relevant, or to merge with similar requests from others. In the meantime I leave the floor open for discussion!

**Comment by jezdez** [comment]
Related #7978.
