### ISSUE TITLE
Anaconda & Miniconda in a Single Shell 

### ISSUE THREAD

**Issue by davidleejy** [conda/conda#10564]
Been trying to get Anaconda & Miniconda to co-exist harmoniously in a single shell -- for example, `$ conda` to invoke Anaconda and `$ miniconda` to invoke miniconda. Both installations work fine when only one is initialized upon shell start.

I share my findings in the following sections. I am ok with contributing if needed.

More generally, can a single user work with multiple installations of Anaconda/Miniconda?

### Prior Work & Current State

In 2016 - 2017, two issues filed (#6046, #3109) raised the topic of multi-user support. Today, Anaconda supports [multi-user administration](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html). While this allows different users to have their own user conda config profiles `~/.condarc`, it doesn't allow a single user to operate multiple conda installations.

### Attempt at making Anaconda & Miniconda Work in a Single Shell

- Install Anaconda & Miniconda at different paths. 

- At this stage, both installations work fine when the other isn't initialized at shell start. So `$ conda` refers to whichever installation was initialized (`$ cd installedDir/whicheverConda/bin; ./conda init zsh`).

- Noticed that both Anaconda & Miniconda could modify User Conda Config `~/.condarc`. So I decided to put `rm ~/.condarc` in the shell profile (~/.zshrc for Mac) so that `.condarc` is removed at shell start to simplify my situation. Thus, Anaconda & Miniconda rely solely on their System Config (`.condarc` located in installations' dirs).

- At this stage, I can, say, disallow Miniconda to make requests to repo.anaconda.com for packages (by modifying channel permissions) while having no such restriction for Anaconda.

- As the goal is to let Anaconda & Miniconda co-exist harmoniously in a single shell, I thought a good place to start is to understand the snippet of code that executing `$ conda init` places into my shell profile: 
```bash
# >>> conda initialization >>>
     ... 
# <<< conda initialization <<<
```

- This code snippet calls `condaDir/etc/profile.user/conda.sh`. Realized that the conda command in the shell `$ conda` is a function defined in this `conda.sh` script:
```bash
conda () { 
  ...
}
```

- Changing this function name to, say, `miniconda`, lets me use `$ miniconda` in place of `$ conda`.

- So changed miniconda's `conda.sh` to define `miniconda( ) {... }` instead of `conda( ) { ... }` while not changing anything in Anaconda.

- At this stage I felt I was making progress towards letting Anaconda & Miniconda co-exist in a single shell,  so I modified my bash profile to initialize both installations this way:
``` bash
# Miniconda initialization:
. `[...]/miniconda3/etc/profile.user/conda.sh`

# >>> conda initialization >>>
     ... for Anaconda ...
# <<< conda initialization <<<
```

- To my dismay, this didn't work. 

- I realized that the script `[...]/miniconda3/etc/profile.user/conda.sh` (Anaconda has its own etc/profile.user/conda.sh) defines shell variables `$CONDA_EXE`, `$CONDA_PYTHON_EXE`, etc. . Searching for the occurrences of these variables in the anaconda/miniconda installation's directory reveals many files like `activate.py`, etc. that rely on these. Thus, when my shell profile executes `conda.sh` for conda initialization for both anaconda & miniconda, the later initialization snippet in the shell profile takes precedence -- and the shell variables take on values assigned by the later initialization snippet.

**Any hints/ideas to get Anaconda & Miniconda to work in a single shell would be appreciated.**

**Comment by mingwandroid** [comment]
This is not something I would attempt at all. It runs counter to the entire design of conda and conda environments.

**Comment by chenghlee** [comment]
@davidleejy: what's your motivation for wanting to do this? As @mingwandroid said, this would seriously break conda's ability to manage environments and is not functionality we would likely ever support.

If your goal is to have the _packages_ of an Anaconda [Individual Edition] installation along with a miniconda installation, I would:
1. Install miniconda and activate it.
2. Create an Anaconda environment managed by that miniconda installation: `conda create -n anaconda-yyyy.nn anaconda=yyyy.nn` (where `yyyy.nn` is the desired release, e.g., 2020.11).
3. `conda activate` the `anaconda-yyyy.nn` when needed.

**Comment by davidleejy** [comment]
Thank you everyone for the helpful comments. I think this issue can be closed.
