### ISSUE TITLE
Broken version comparison on Anaconda.org

### ISSUE THREAD

**Issue by ileasile** [conda/conda#10586]
I don't really know where to report my issue.
I've created a [question on SO](https://stackoverflow.com/questions/65321085/latest-displayed-version-on-anaconda-cloud) several months ago, but haven't received any answers.
Please give me the right link if I'm wrong.

## Current Behavior
Different "latest versions" are reported for this package:
https://anaconda.org/jetbrains/kotlin-jupyter-kernel:
![image](https://user-images.githubusercontent.com/20319593/113339968-f3eddf80-9333-11eb-83b1-385ccca4f4a4.png)
![image](https://user-images.githubusercontent.com/20319593/113340002-023bfb80-9334-11eb-8ef9-a68b8d2f589d.png)
![image](https://user-images.githubusercontent.com/20319593/113340041-108a1780-9334-11eb-8555-b5ebc894d4ee.png)
![image](https://user-images.githubusercontent.com/20319593/113340087-1c75d980-9334-11eb-9fa0-3cc8bcf58b79.png)

### Steps to Reproduce
Open the link above

## Expected Behavior
All the latest versions shown are the same and should be 0.9.0.14 at the moment of this issue creation

## Environment Information
Not applicable

**Comment by ileasile** [comment]
Shield from shields.io says that version is 0.9.0.6:
![alt](https://img.shields.io/conda/v/jetbrains/kotlin-jupyter-kernel)

**Comment by ileasile** [comment]
Shields.io makes a request to https://api.anaconda.org/package/jetbrains/kotlin-jupyter-kernel and gets
```
"latest_version":"0.9.0.6"
```
in the response.
But in the same response:
```
"versions": [
    "0.6.3.10", 
    "0.7.1.10", 
    "0.7.2.10", 
    "0.7.3.10", 
    "0.7_SNAPSHOT", 
    "0.7.29_add_teamcity_integration", 
    "11", 
    "0.7.12_add_teamcity_integration", 
    "0.7.17_add_teamcity_integration", 
    "0.7.dev18", 
    "0.7.dev19", 
    "0.7.dev21", 
    "0.7.dev22", 
    "0.7.12", 
    "0.8.0", 
    "0.8.dev23", 
    "0.7.15.64.dev1", 
    "0.7.40.145", 
    "0.8.0.2", 
    "0.8.0.7", 
    "0.8.0.10", 
    "0.8.0.25", 
    "0.8.0.28", 
    "0.8.1.74", 
    "0.8.1.75", 
    "0.8.1.76", 
    "0.8.1.78", 
    "0.8.1.83", 
    "0.8.1.98", 
    "0.8.1.114", 
    "0.8.1.118", 
    "0.8.1.120", 
    "0.8.1.121", 
    "0.8.2.1", 
    "0.8.2.2", 
    "0.8.2.4", 
    "0.8.2.5", 
    "0.8.2.53", 
    "0.8.2.61", 
    "0.8.3.1", 
    "0.8.3.64", 
    "0.8.3.122", 
    "0.9.0.3", 
    "0.9.0.5", 
    "0.9.0.6", 
    "0.9.0.7", 
    "0.9.0.14"
  ]
```
So... It's very strange

**Comment by ileasile** [comment]
It seems to be an Anaconda.org API bug, but where to report it? I don't know. And it is very annoying

**Comment by chenghlee** [comment]
Can you please report this to [Anaconda-Platform/anaconda-client](https://github.com/Anaconda-Platform/anaconda-client)?

**Comment by ileasile** [comment]
Thanks!
