### ISSUE TITLE
conda env create vastly slower than conda create

### ISSUE THREAD

**Issue by nhartwic** [conda/conda#10592]
I've noticed this with a lot of the environments I'm trying to build, usually because I'm specifying them for snakemake workflows. I've attached an example yml format text file, 
[general.txt](https://github.com/conda/conda/files/6263620/general.txt), with requirement specifications. If I attempt to build an environment from this file, conda takes forever to solve. If I instead simply pass in the package names at the command line, the environment is solved in only a few seconds. To be perfectly clear...

```
# this runs in tens of seconds
conda create -n test1 -c conda-forge -c bioconda python pandas snakemake seqtk scikit-learn statsmodels mafft plotly logomaker meme

# this takes apparently forever. Maybe it finishes, I'm not sure
mv general.txt general.yml
conda env create -n test2 -f general.yml
```

This is undesirable to say the least. Why does this happen? What is the "conda env create" doing so differently from "conda create" that it seemingly takes forever to solve? Is this a bug or expected behavior?

Thanks in advance for any input

**Comment by cjw296** [comment]
I've just had the same experience with this `environment.yaml`:

```
name: coronavirus
channels:
  - simplistix
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - ffmpeg
  - geopandas
  - holoviews
  - imageio  # from conda-forge
  - imagemagick  # from conda-forge
  - jupyter
  - matplotlib
  - moviepy
  - pandas
  - pip
  - picky-conda
  - python=3.8
  - python-dateutil
  - scipy
  - shapely
  - tqdm
  - pip:
    - mpl-axes-aligner
    - pygifsicle
```

`conda env create --file environment.yml` just spun until I got bored (~20-30 minutes)

The following completed in ~5 mins:

```
conda create -n coronavirus -c simplistix -c defaults bokeh geopandas holoviews imageio ffmpeg jupyter matplotlib pandas pip picky-conda python=3.8 python-dateutil scipy shapely tqdm
conda activate coronavirus
conda install -c conda-forge imageio imagemagick
pip install mpl-axes-aligner pygifsicle
```
