### ISSUE TITLE
Conda 4.10.0 cannot read linux kernel version "5.4.89+"

### ISSUE THREAD

**Issue by jamesp** [conda/conda#10596]
## Current Behavior
`conda update conda` using v4.10.0 fails to run on cirrus-ci, error message:
```InvalidVersionSpec: Invalid version '5.4.89+': empty version component```

### Steps to Reproduce
```
conda create -n conda4.10 conda=4.10
conda activate conda4.10
export CONDA_OVERRIDE_LINUX='5.4.89+'
conda update conda
```
Fails:
```
InvalidVersionSpec: Invalid version '5.4.89+': empty version component
```

## Expected Behavior
Conda should check for new versions regardless of the version number the linux kernel is reporting.

## Debugging 

I believe this is due to the change [`conda/core/index.py` at line 175](https://github.com/conda/conda/blob/296be7e9e1d38883fb1e46237fe55352016978c1/conda/core/index.py#L175) added to 4.10.0, which takes the linux kernel version string and passes it to `_make_virtual_package`.

On Cirrus-CI, the current linux kernel running ci is reported as "5.4.89+".  
```
$ uname -r
5.4.89+
```

This is breaking conda `VersionSpec` due to the "+" at the end I believe, due to this split in `conda/models/version.py`:
https://github.com/conda/conda/blob/aed799b56d9ee16a3653928527e2af6e41394e85/conda/models/version.py#L193-L199

I would suggest a simple fix by checking the existence of `version[1]`.  e.g.
```
        version = version[-1].split('+')
        if len(version) == 1:
            # no local version
            self.local = []
        elif len(version) == 2:
            # local version given
            if version[1]:
                self.local = version[1].replace('_', '.').split('.')
            else:
                self.local = []
```

I don't know enough about the internals of conda to understand if this is going to break something else. If this seems acceptable, please let me know and I will create a PR to this effect.

**Comment by fkorotkov** [comment]
Just wanted to note that the reason it's happening on Cirrus is because Cirrus hosts use [Container-Optimized OS](https://cloud.google.com/container-optimized-os) which always had version ending with `+`. Seems it's a regression on conda side since a lot of people have been using Cirrus with conda for a long time.

**Comment by chenghlee** [comment]
The intent was to expose the kernel's `{major}.{minor}.{patch}` version as the `__linux` virtual package's version. Unfortunately, our first pass at this naively assumed that the vendor components would be delimited by a `-`, which is clearly not the case.

I created PR #10599 to address this; it should be included in the 4.10.1 release, which we plan to release in the next week or two.

**Comment by jamesp** [comment]
Many thanks for the super quick response @chenghlee, look forward to seeing your PR in the next release 👍
Thanks!

**Comment by chenghlee** [comment]
@jamesp: conda 4.10.1 should be available on defaults Wednesday or Thursday of this week. The RC is available via the `conda-canary` channel if you want to give it a try.

**Comment by jamesp** [comment]
@chenghlee Great! I'll give the rc a go 👍
