### ISSUE TITLE
conda install invalidspec 

### ISSUE THREAD

**Issue by rudyvogt** [conda/conda#10594]
Hi,

Suddenly all my installs using conda-forge channel fails
I get InvalidSpecError: Invalid Spec: >=

If i remove the conda-forge channel install works OK - but then most of the time i get older packages

So has something changed in the channel space - or is my conda now to old to work?

Cheers
Rudy

**Comment by chenghlee** [comment]
Can you provide an example `conda install` or `conda create` command where this fails?

**Comment by rudyvogt** [comment]
HI @chenghlee 

it fails on all my install when it is anything else than **default**

conda searchit is an exiting environment just updating packages

conda install -c conda-forge wxpython
conda install -c conda-forge setuptools
conda install - c esri arcgis 
etc.

![image](https://user-images.githubusercontent.com/15167672/113954251-da312880-985c-11eb-8a88-a59609a0cadb.png)

I had the conda-forge in my channel config - took that out and then conda install runs fine - very weird as it worked until a 2 weeks ago

as you can see much more up to date in conda-forge channel

![image](https://user-images.githubusercontent.com/15167672/113954817-e9fd3c80-985d-11eb-9c90-6beb0ce48424.png)


as you can see - it works ok installing - only using default

![image](https://user-images.githubusercontent.com/15167672/113954605-79562000-985d-11eb-9f66-072d38322ae0.png)

**Comment by chenghlee** [comment]
Can you also please provide the output of `conda info` and `conda config --show-sources`?

**Comment by chpurna** [comment]
Hi,

We have similar issue while creating prefixes...

$ sudo /usr/bin/anaconda/bin/conda create --prefix /usr/bin/anaconda/envs/py355new python=3.7 anaconda=4.3 --yes
Fetching package metadata ...........
Solving package specifications:

InvalidSpecError: Invalid spec: >=

Requested info - 
$ sudo /usr/bin/anaconda/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.14.2
       root environment : /usr/bin/anaconda  (writable)
    default environment : /usr/bin/anaconda
       envs directories : /usr/bin/anaconda/envs
                          /root/.conda/envs
          package cache : /usr/bin/anaconda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/2.7.12 Linux/4.15.0-1109-azure debian/stretch/sid glibc/2.23
                UID:GID : 0:0

$ sudo /usr/bin/anaconda/bin/conda config --show-sources

$

**Comment by chpurna** [comment]
adding few more details to above - 

$ sudo /usr/bin/anaconda/bin/conda update conda
Fetching package metadata ...........
Solving package specifications:

InvalidSpecError: Invalid spec: >=



$ sudo /usr/bin/anaconda/bin/conda create --prefix /usr/bin/anaconda/envs/py355new python=3.7 anaconda=4.3 --yes
Fetching package metadata ...........
Solving package specifications:

InvalidSpecError: Invalid spec: >=


$ sudo /usr/bin/anaconda/bin/conda create --prefix /usr/bin/anaconda/envs/py355new python=3.6 anaconda=4.3 --yes
-- works good and installs all packages

**Comment by fyabc** [comment]
Hi,

I have similar issue when installing packages via conda-forge channel.

Here is my installation command:

```
C:\Users\DELL>conda install kivy -c conda-forge
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

C:\Users\DELL>activate games

(games) C:\Users\DELL>conda install kivy -c conda-forge
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7
```

My environment:

```
(games) C:\Users\DELL>conda info

     active environment : games
    active env location : D:\Anaconda3\envs\games
            shell level : 1
       user config file : C:\Users\DELL\.condarc
 populated config files : C:\Users\DELL\.condarc
          conda version : 4.5.11
    conda-build version : 1.20.0
         python version : 3.5.4.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\DELL\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\DELL\AppData\Local\conda\conda\envs
                          C:\Users\DELL\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.5.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

(games) C:\Users\DELL>conda config --show-sources
==> C:\Users\DELL\.condarc <==
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
channels:
  - defaults
channel_priority: False
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
show_channel_urls: True
```

**Comment by chpurna** [comment]
Its observed that conda create is failing with "anaconda" package along with "python=3.7" and works fine without anaconda.

Steps I followed to install anaconda at conda env are - 

1	sudo  conda  create  --prefix /usr/bin/anaconda/envs/pythn37testing  python=3.7  --yes
2. 	wget https://anaconda.org/anaconda/anaconda/2020.11/download/linux-ppc64le/anaconda-2020.11-py37_0.tar.bz2
3.     sudo conda install /xxxxx/anaconda-2020.11-py37_0.tar.bz2 -n pythn37testing
4.     sudo  /usr/bin/anaconda/bin/conda list -n pythn37testing

List had shown anaconda installed at step 2...
