### ISSUE TITLE
Spyder 5.0.0 not launching on Anaconda (4.10.0)

### ISSUE THREAD

**Issue by jaquprevert** [conda/conda#10608]
Hi, I just updated my Anaconda (4.10.0) as well as Spyder (5.0.0) and when I try to launch Spyder using the console I receive an error. It starts by: 

`No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect.`

and ends with:

`AttributeError: 'ShellWidget' object has no attribute 'shutdown_thread'`

**Comment by ank78** [comment]
Hi! I disabled several options in the configuration settings page "Completion and linking", after restarting Spyder 5.0 stopped loading. Reset settings helped: python spyder-script.py --reset
