### ISSUE TITLE
Conda delivers InvalidSpecError with no value, no matter what I try

### ISSUE THREAD

**Issue by infiltratorChris** [conda/conda#10606]
## Current Behavior

Hello everybody,

I'm currently trying to use conda to update all my packages and it delivers
```
Fetching package metadata ...............
Solving package specifications:

InvalidSpecError: Invalid spec: >=
```
and nothing else. And I see a similar behavior for any type of `install` or `update` command. `list` and `help` and those kind of commands still work though.

## Expected Behavior
I actually expected it to work since the last package I could install was `pydotplus`.
If any other information is needed, just guide me what you need and how to get it since I'm fairly new to conda. I've been googling a fair bit but all posts that reported a `InvalidSpecError` also delivered a numeric code. Mine didn't, which made me wonder even more.

## Environment Information
Below you can see my current installation:

```
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : D:\Users\user\Anaconda3  (writable)
    default environment : D:\Users\user\Anaconda3
       envs directories : D:\Users\user\Anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\.conda\envs
          package cache : D:\Users\user\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\user\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.19041
          administrator : True
```

Thank you in advance,
Chris

**Comment by infiltratorChris** [comment]
Updating anaconda navigator to 1.10 also didnt work since it delivered again a InvalidSpecError while in the UI (see picture below)
![Unbenannt](https://user-images.githubusercontent.com/81869246/114535975-ea784780-9c50-11eb-9db0-22117d82778c.PNG)

I'm trying too download the new verion manually.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
