### ISSUE TITLE
envs_dirs not being respected by conda create --name (conda 4.10 version)

### ISSUE THREAD

**Issue by ab2dridi** [conda/conda#10625]
Hi,

I'm facing the same issue as this issue in this old ticket https://github.com/conda/conda/issues/5366 but using conda 4.10 version

I created a .condarc in (/etc/conda/.condarc) for all users (all users can read this config file) and all users can write in this directory /data/conda-envs

```
envs_dirs:
- /data/conda-envs
```

conda info is displaying the correct envs directory for all users , but when i try with a simple user to create environnement using --name option (like conda create --name my_env_py37 python=3.7) is trying to install it to the home directory of the user under /.conda/envs/my_env_py37

For notice, using the root user with the --name option, it's working well and it installs the environnement under /data/conda-envs directory 

My conda version is 4.10, i tried to update to the conda version 4.10.1 but facing the same issue.

**Comment by elopezz** [comment]
In order to use the folders specified in `envs_dirs` the user executing the `conda create` command needs to have full permissions over those folders, that's why it's working with the root user but not with the other users.
