### ISSUE TITLE
Error while installing conda in ubuntu 18.04

### ISSUE THREAD

**Issue by debparth** [conda/conda#10646]
## Current Behavior

I'm trying to install conda in the remote server but it's giving me weird error. Even googling the error is not helpful. Each time installing conda is giving an error: `Unexpected EOF in archive`.

### Steps to Reproduce

```
curl -O https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
```
```
md5sum Anaconda3-2019.03-Linux-x86_64.sh
`43caea3d726779843f130a7fb2d380a2  Anaconda3-2019.03-Linux-x86_64.sh`
```
```bash Anaconda3-2019.03-Linux-x86_64.sh```

![image](https://user-images.githubusercontent.com/53347017/116782288-bf418500-aaa5-11eb-84c3-df1256bbb772.png)

## Expected Behavior
It should have installed without giving any kind of an error

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
