### ISSUE TITLE
Please explain why this package is important, whether we must install it manually and under what circumstances

### ISSUE THREAD

**Issue by richdevboston** [conda/conda#10645]
<!--

The documentation for this package is scant, meaning the main purpose (raison d'etre) for this package is not explained well enough.  

Can someone please enhance the Introduction to explain why this package is important, whether we must install it manually, and under what circumstances?   Is this now built into the core conda package?  

This is a documentation feature request.  

Thank you.

**Comment by jezdez** [comment]
I'm not clear what is being asked here. Feel free to open a new ticket providing more details.
