### ISSUE TITLE
conda-build creates uninstallable package

### ISSUE THREAD

**Issue by wvxvw** [conda/conda#10641]
You can see the build here:

https://github.com/drcandacemakedamoore/cleanX/runs/2460250648?check_suite_focus=true

You can download the package thus produced from here: https://github.com/drcandacemakedamoore/cleanX/releases/tag/v0.0.7 or do

``` sh
conda install -c doctormakeda cleanx
```

It doesn't matter what version of Python is installed in the user environment, the package won't install, claiming that the version of Python is somehow wrong for the package.

Note how package description never even mentions the version of Python. Why is `conda` trying to be "helpful" by specifying some absurd requirements, when literally nobody asked it to?

**Comment by wvxvw** [comment]
There's some more information (in the comments) here: https://stackoverflow.com/questions/67306701/conda-refuses-to-install-no-matter-python-version

So far my guess as to why this happens is this:

1. `conda` finds older versions of dependencies of `cleanx` in the main channel (whereas `conda-forge` was used during development and at build time).
2. It cannot install them (might be a genuine problem since those do depend on Python's ABI).
3. It reports the problem incorrectly (the problem is that some dependencies cannot be installed given a particular version of Python, not the package itself).

But, the problems aren't over yet. On top of misreporting the problem, the solver wrongly believes that the installation of package is possible (albeit with a different version of Python), but when asked to solve for any other version of Python -- still fails.

And, finally, `conda-build` produces a package with the metadata that was not intended by the programmer. The programmer never specified any requirements for Python version, but `conda-build` randomly decided that it should be exactly the same as the one used during build. I expect that there is some sort of workaround for this issue, but I also believe it to be a bug / unintended behavior: if the programmer doesn't specify a version of dependency, it means that they don't care, and so should `conda-build`. No need to second-guess the programmer. Don't assume you know better.

**Comment by wvxvw** [comment]
Oh, and on top of this all, `--no-deps` *should* have worked. The problem is with dependencies, not the package itself. But, it doesn't.

**Comment by jezdez** [comment]
I'm not sure how to deduce steps to reproduce from this issue and would appreciate if you would open a ticket with the "bug report" template on https://github.com/conda/conda/issues/new/choose. Thanks!

**Comment by wvxvw** [comment]
You have GitHub Actions build that produces the package that is not installable with the exact steps you need to take to reproduce the problem. It's the first link in the ticket. What other steps do you want?

**Comment by jezdez** [comment]
> You have GitHub Actions build that produces the package that is not installable with the exact steps you need to take to reproduce the problem. It's the first link in the ticket. What other steps do you want?

First, I saw the GitHub Actions run above, thank you for providing the link for it. But it would be even better to see more about how you ran conda to debug the reasons why installing your package didn't work.

The easiest way to do that is to recreate the bug with the "bug report" issue template since it has some instructions for what would be best. Would that work for you? Here's a direct [link to the form](https://github.com/conda/conda/issues/new?assignees=&labels=&template=Bug_report.md). Thank you!

**Comment by wvxvw** [comment]
> But it would be even better to see more about how you ran conda to debug the reasons why installing your package didn't work.

it's in the same ticket, just one line below, in the code listing section...

Seriously, if you don't care that it doesn't work, I don't really care either. It's your project, not mine... I just don't understand this attitude: you'd literally spend less time if you just tried to do what the ticket tells you doesn't work, then do this pointless red-taping. No, I'm not going to resubmit this ticket by jumping through your stupid hoops. If you don't like it - don't deal with it. I'm not forcing you to. Just spare me the nonsense.
