### ISSUE TITLE
Bug report: Anaconda3 installation fail

### ISSUE THREAD

**Issue by vandana1145** [conda/conda#10648]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by chenghlee** [comment]
If you are still having problems with this, please report with details in the [ContinuumIO/anaconda-issues](https://github.com/ContinuumIO/anaconda-issues) so the right team will see it? Thanks.
