### ISSUE TITLE
How can I install latest version of conda with a old GLIBC ()

### ISSUE THREAD

**Issue by Bosheng13** [conda/conda#10657]
**Hi, 

  I have a old server with a Red Hat Linux Server release 5.4 Beta. These days I tried to install conda in it, but when I perform "bash Miniconda2-latest-Linux-x86_64.sh", it comes this:**
 
[/root/miniconda2] >>>
PREFIX=/root/miniconda2
Unpacking payload ...
[26115] Error loading Python lib '/tmp/_MEIUelrRP/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by /tmp/_MEIUelrRP/libpython3.8.so.1.0)

[26118] Error loading Python lib '/tmp/_MEIar7Eu2/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by /tmp/_MEIar7Eu2/libpython3.8.so.1.0)

**It seems that my server have a very old version of GLIBC. After this, I used "rpm -qa | grep glibc", and get this:**

[root@localhost ~]# rpm -qa | grep glibc
glibc-headers-2.5-38
glibc-common-2.5-38
compat-glibc-2.3.4-2.26
glibc-2.5-38
glibc-devel-2.5-38
glibc-devel-2.5-38
glibc-2.5-38
compat-glibc-headers-2.3.4-2.26
compat-glibc-2.3.4-2.26

**and "ldd --version":**

[root@localhost ~]# ldd --version
ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**All this result indicate that my GLIBC version is 2.5 and cannot meet the requirement of latest conda version (maybe need GLIBC_2.10 ). I have no idea whether I need to update my GLIBC, please kindly how to deal with this things?

By the way, my python is version 2.7.**

Thanks

**Comment by chenghlee** [comment]
Unfortunately, there really isn't a good way to run a "modern" conda install on CentOS/RHEL 5; the [last supported version](https://docs.anaconda.com/anaconda/install/#old-os) for CentOS 5 was Anaconda 4.3. Updating glibc at a system level is _not_ recommended, as it can seriously break your operating system.

**Comment by chenghlee** [comment]
Closing; I don't think there's any feasible route to running current conda releases & packages on CentOS 5.
