### ISSUE TITLE
conda navigator takes long to initialize

### ISSUE THREAD

**Issue by UYGitH** [conda/conda#10658]
This is what I've tried so far:
1. conda config --set ssl_verify False
2. conda remove anaconda-navigator and conda install anaconda-navigator
3. sudo rm -rf ~/.continuum/

non of the above worked, initializing still takes a very long time and I can't find any other solutions

**Comment by jezdez** [comment]
Please file a ticket in the appropriate issue tracker: https://github.com/ContinuumIO/anaconda-issues/issues/new

Thank you!
