### ISSUE TITLE
conda pip install metadata directory missing, site-packages folder does not exist

### ISSUE THREAD

**Issue by Apprisco** [conda/conda#10655]
## Current Behavior

![image](https://user-images.githubusercontent.com/34324909/117374140-9c92e000-ae9a-11eb-913f-74c1c141b647.png)
Entire folder site-packages does not exist when I checked the directory.

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

**Comment by jezdez** [comment]
Please provide steps to reproduce this.
