### ISSUE TITLE
Spyder latest version is not included in update

### ISSUE THREAD

**Issue by srvmig** [conda/conda#10661]
When I am going to update using ```conda update --all``` for avoiding any inconsistent download. The spyder updated version is not there. Even when I am trying with ```conda install spyder=5.0.2```, it is not working.

Please add the spyder in update respiratory.

**Comment by Mathemilda** [comment]
I second this. I contact Spyder developers and they told me that you decided to remove Spyder. This is rather painful news for me, because for me as a data scientist Spyder is more convenient than Pycharm. I wish you would bring it back.

**Comment by jezdez** [comment]
Hi all, this isn't the right issue track to raise this problem as this repo is for conda the package manager, not the Anaconda Distribution and its included packages. Here's the right URL: https://github.com/ContinuumIO/anaconda-issues/issues/new 

Thank you!
