### ISSUE TITLE
An unexpected error has occurred in using anaconda prompt

### ISSUE THREAD

**Issue by tahiira** [conda/conda#10679]
Hi everybody.
when I open anaconda prompt, I face with this message:
`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues`
and 
`Traceback (most recent call last):
.
.
.
.
from .enums import ProbingState
ModuleNotFoundError: No module named 'chardet.enums'`

and in command prompt, when I used pip ..., this error is shown
`from tornado.util import Configurable, TimeoutError, import_object
ImportError: cannot import name 'TimeoutError'`
how can I resolved this?

**Comment by jezdez** [comment]
This seems to be related to your code that is importing tornado somewhere or shadowing the other ModuleNotFoundError about chardet.enums. Or at least I don't see information here that would indicate that it's an issue in the conda package manager.
