### ISSUE TITLE
installation fails for aarch64 on proot

### ISSUE THREAD

**Issue by casperdcl** [conda/conda#10675]
Opening as requested by https://github.com/conda/conda/issues/8297#issuecomment-843776237

## Current Behavior
Symlink installation errors with aarch64 proot miniconda (same ones which were partially solved by miniforge in conda-forge/miniforge#107 - see details there).

### Steps to Reproduce
> Do you have an android device? If so, easiest would be to install [termux](https://f-droid.org/en/packages/com.termux/) and then within the app run:
>
> ```bash
> pkg install proot
> pkg install proot-distro
> proot-distro install debian-buster
> proot-distro login debian-buster --termux-home
> ```
> 
> Then:

```bash
curl -OL https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-aarch64.sh
bash Miniconda3-py39_4.9.2-Linux-aarch64.sh
```

**Comment by jezdez** [comment]
@casperdcl I'm not sure I follow the issues you referenced above, but I would first like to clarify that support for proot simply doesn't exist at the moment and to my knowledge wasn't part of the aarch64 work recently. So it's probably not surprising that this fails.

I would appreciate if you would update the issue body with details what it is you're expecting and why support for proot would be beneficial for conda. I simply wasn't able to get that information and it would go along way to better prioritize work on conda. Thank you!

**Comment by casperdcl** [comment]
I opened this upon request (https://github.com/conda/conda/issues/8297#issuecomment-843776237). Just to clarify, `proot` is an env not an architecture. AFAIK the easiest way to get a full Linux distro on an android phone is using the termux app (which uses `proot`), as in the OP. There seems to be at least some amount of user interest in this feature based on the linked issues.

**Comment by personalizedrefrigerator** [comment]
I am also experiencing this issue (`proot` installed via `termux` on an Android device).

After the installer fails with `Miniconda3-latest-Linux-aarch64.sh: line 435: /home/mesozoic/miniconda3/bin/python: No such file or directory`, I see broken links in `~/miniconda3/bin`.

## Inspecting the broken links

<code>~/miniconda3$ cd ~/miniconda3/bin </code>

<details><summary><code>~/miniconda3/bin$ ls -la</code></summary>
<pre>
total 6071
drwxrwxr-x.  2 mesozoic mesozoic    3488 Jan 17 10:29 .
drwxrwxr-x. 16 mesozoic mesozoic    3488 Jan 17 10:36 ..
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 2to3 -> 2to3-3.9
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 2to3-3.9 -> /home/mesozoic/miniconda3/.condatmp/.l2s.a3a354ac-03d2-4029-a9f5-81ddcad9932c0001
-rwxrwxr-x.  1 mesozoic mesozoic 2828304 Mar 31  2021 aarch64-conda-linux-gnu-ld
lrwxrwxrwx.  1 mesozoic mesozoic      30 Jan 17 10:28 aarch64-conda_cos7-linux-gnu-ld -> aarch64-conda-linux-gnu-ld
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 activate -> /home/mesozoic/miniconda3/.condatmp/.l2s.6b49ce30-18e5-4f70-ab4a-d1aaf20d254c0001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 c_rehash -> /home/mesozoic/miniconda3/.condatmp/.l2s.cb37c6d1-936a-4b1c-acc0-917036e851b00001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 captoinfo -> tic
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 chardetect -> /home/mesozoic/miniconda3/.condatmp/.l2s.cb01d55d-ae99-42c6-996a-5bc47ff8bdd70001
-rwxrwxr-x.  1 mesozoic mesozoic   10200 Mar  4  2021 clear
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 conda -> /home/mesozoic/miniconda3/.condatmp/.l2s.e78cd4a1-120c-4f22-91df-61a03974f2020001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 conda-env -> /home/mesozoic/miniconda3/.condatmp/.l2s.4e6cc9a2-c903-4cad-bb73-58e15419437f0001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 cph -> /home/mesozoic/miniconda3/.condatmp/.l2s.37cae9be-7b5f-45fd-a29a-211cb22a323c0001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 deactivate -> /home/mesozoic/miniconda3/.condatmp/.l2s.0d87e400-a40e-43a9-b310-285cfc1c0dcb0001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 idle3 -> idle3.9
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 idle3.9 -> /home/mesozoic/miniconda3/.condatmp/.l2s.25aea893-931d-430a-8b4b-c06662e078900001
-rwxrwxr-x.  1 mesozoic mesozoic   67616 Mar  4  2021 infocmp
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 infotocap -> tic
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzcat -> xz
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzcmp -> xzdiff
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzdiff -> xzdiff
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzegrep -> xzgrep
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzfgrep -> xzgrep
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzgrep -> xzgrep
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzless -> xzless
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzma -> xz
-rwxrwxr-x.  1 mesozoic mesozoic   19040 Apr 24  2021 lzmadec
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 lzmainfo -> /home/mesozoic/miniconda3/.condatmp/.l2s.c673a7e0-327a-406b-b28f-3490f4511ce30001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 lzmore -> xzmore
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 ncursesw6-config -> /home/mesozoic/miniconda3/.condatmp/.l2s.1a391882-8bd6-485d-8c35-ea087fdc96880001
-rwxrwxr-x.  1 mesozoic mesozoic  883632 Apr 22  2021 openssl
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 pip -> /home/mesozoic/miniconda3/.condatmp/.l2s.a4159c52-59a7-41e6-8253-5df1ae11c3ca0001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:29 pip3 -> /home/mesozoic/miniconda3/.condatmp/.l2s.1b20685d-564a-4db5-a9fc-242a40b06cd60001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 pydoc -> pydoc3.9
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 pydoc3 -> pydoc3.9
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 pydoc3.9 -> /home/mesozoic/miniconda3/.condatmp/.l2s.d1751dc5-48cc-492c-a070-4de60b52ace00001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 python -> python3.9
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 python3 -> python3.9
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 python3-config -> python3.9-config
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 python3.9 -> /home/mesozoic/miniconda3/.condatmp/.l2s.dbca13ff-3efb-4f03-9331-af025f6625cd0001
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 python3.9-config -> /home/mesozoic/miniconda3/.condatmp/.l2s.7cc4c04c-d005-4747-9fc4-be3f4cec599c0001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 reset -> tset
-rwxrwxr-x.  1 mesozoic mesozoic 2114496 Apr 24  2021 sqlite3
-rwxrwxr-x.  1 mesozoic mesozoic   30301 Mar  4  2021 sqlite3_analyzer
-rwxrwxr-x.  1 mesozoic mesozoic   14288 Mar  4  2021 tabs
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 tclsh -> tclsh8.6
-rwxrwxr-x.  1 mesozoic mesozoic   13392 Mar  4  2021 tclsh8.6
-rwxrwxr-x.  1 mesozoic mesozoic   96320 Mar  4  2021 tic
-rwxrwxr-x.  1 mesozoic mesozoic   18384 Mar  4  2021 toe
-rwxrwxr-x.  1 mesozoic mesozoic   22512 Mar  4  2021 tput
-rwxrwxr-x.  1 mesozoic mesozoic     233 Jan 17 10:29 tqdm
-rwxrwxr-x.  1 mesozoic mesozoic   26584 Mar  4  2021 tset
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 unlzma -> xz
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 unxz -> xz
-rwxrwxr-x.  1 mesozoic mesozoic     234 Jan 17 10:29 wheel
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 wish -> wish8.6
-rwxrwxr-x.  1 mesozoic mesozoic   13544 Mar  4  2021 wish8.6
lrwxrwxrwx.  1 mesozoic mesozoic     162 Jan 17 10:28 xz -> /home/mesozoic/miniconda3/.condatmp/.l2s.7f2bc2a6-3b67-41b8-b0b9-9151eeba605b0001
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 xzcat -> xz
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 xzcmp -> xzdiff
-rwxrwxr-x.  1 mesozoic mesozoic   19040 Apr 24  2021 xzdec
-rwxrwxr-x.  1 mesozoic mesozoic    6633 Apr 24  2021 xzdiff
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 xzegrep -> xzgrep
lrwxrwxrwx.  1 mesozoic mesozoic      18 Jan 17 10:28 xzfgrep -> xzgrep
-rwxrwxr-x.  1 mesozoic mesozoic    5630 Apr 24  2021 xzgrep
-rwxrwxr-x.  1 mesozoic mesozoic    1799 Apr 24  2021 xzless
-rwxrwxr-x.  1 mesozoic mesozoic    2162 Apr 24  2021 xzmore
</pre>
</details>

<details><summary><code>~/miniconda3/bin$ stat python</code></summary>
<pre>
  File: python -> python3.9
  Size: 18              Blocks: 0          IO Block: 4096   symbolic link
Device: 10310h/66320d   Inode: 286187      Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (10290/mesozoic)   Gid: (10290/mesozoic)
Access: 2022-01-17 10:28:50.731442823 -0800
Modify: 2022-01-17 10:28:50.731442823 -0800
Change: 2022-01-17 10:28:50.731442823 -0800
 Birth: -
</pre>
</details>

<details><summary><code>~/miniconda3/bin$ file python</code></summary>
<pre>
python: broken symbolic link to python3.9
</pre>
</details>

<details><summary><code>~/miniconda3/bin$ stat python3.9</code></summary>
<pre>
  File: python3.9 -> /home/mesozoic/miniconda3/.condatmp/.l2s.dbca13ff-3efb-4f03-9331-af025f6625cd0001
  Size: 162             Blocks: 0          IO Block: 4096   symbolic link
Device: 10310h/66320d   Inode: 286200      Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (10290/mesozoic)   Gid: (10290/mesozoic)
Access: 2022-01-17 10:28:50.963442823 -0800
Modify: 2022-01-17 10:28:50.963442823 -0800
Change: 2022-01-17 10:28:50.963442823 -0800
 Birth: -
</pre>
</details>

<details><summary><code>~/miniconda3/bin$ file python3.9</code></summary>
<pre>
python3.9: cannot open `python3.9' (Operation not permitted)
</pre></details>

<details><summary><code>~/miniconda3/bin$ stat ../.condatmp</code></summary>
<pre>
stat: cannot statx '../.condatmp': No such file or directory
</pre></details>

<details><summary><code>~/miniconda3/bin$ ls -la ../</code></summary>
<pre>
total 86
drwxrwxr-x. 16 mesozoic mesozoic  3488 Jan 17 10:36 .
drwxr-xr-x. 29 mesozoic mesozoic  3488 Jan 17 10:35 ..
-rw-rw-r--.  1 mesozoic mesozoic 10201 Jul 15  2021 LICENSE.txt
drwxrwxr-x.  3 mesozoic mesozoic  3488 Jan 17 10:28 aarch64-conda-linux-gnu
drwxrwxr-x.  3 mesozoic mesozoic  3488 Jan 17 10:28 aarch64-conda_cos7-linux-gnu
drwxrwxr-x.  2 mesozoic mesozoic  3488 Jan 17 10:29 bin
drwxrwxr-x.  2 mesozoic mesozoic  3488 Jan 17 10:28 compiler_compat
drwxrwxr-x.  2 mesozoic mesozoic  3488 Jan 17 10:29 conda-meta
drwxrwxr-x.  2 mesozoic mesozoic  3488 Jan 17 10:29 condabin
drwxrwxr-x.  2 mesozoic mesozoic  3488 Jan 17 10:29 envs
drwxrwxr-x.  4 mesozoic mesozoic  3488 Jan 17 10:29 etc
drwxrwxr-x.  8 mesozoic mesozoic  4096 Jan 17 10:28 include
drwxrwxr-x. 15 mesozoic mesozoic  8192 Jan 17 10:28 lib
drwxrwxr-x. 88 mesozoic mesozoic 20480 Jan 17 10:36 pkgs
drwxrwxr-x. 11 mesozoic mesozoic  3488 Jan 17 10:28 share
drwxrwxr-x.  3 mesozoic mesozoic  3488 Jan 17 10:29 shell
drwxrwxr-x.  3 mesozoic mesozoic  3488 Jan 17 10:28 ssl
</pre>
</details>
