### ISSUE TITLE
lib\site-packages\torch\jit\_trace.py:727: UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.   warnings.warn(

### ISSUE THREAD

**Issue by SpongeBab** [conda/conda#10686]
lib\site-packages\torch\jit\_trace.py:727: UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.
  warnings.warn(

**Comment by jezdez** [comment]
I'm sorry, this issue doesn't contain enough information to be able to reproduce your issue.

**Comment by SpongeBab** [comment]
oh,that is the output when I run yolov5:https://github.com/ultralytics/yolov5.
From my review of the code, I believe that PyTorch is causing this warning. Sorry to have bothered you. :)
