### ISSUE TITLE
specify which channels each package should come from in environment.yml

### ISSUE THREAD

**Issue by cjw296** [conda/conda#10684]
Unless I'm mistaken, `environment.yml` does not currently allow you to specify which channel a particular package comes from.

This causes particularly unpleasant problems such as: 
https://github.com/conda-forge/geopandas-feedstock/issues/45

I do wonder if it also ends up significantly slowing down solver time, as reported here:
https://github.com/conda/conda/issues/10592

**Comment by mforbes** [comment]
What about if you specify the exact channel with `conda-forge::geopandas`?  I *think* this works, but am not sure what it does about dependencies required by `geopandas`.  These may need to be explicitly included similarly.

**Comment by cjw296** [comment]
Where's that documented? What would an environment.yaml look like that does this?

**Comment by mforbes** [comment]
Not sure where the official documentation is.  I found it mentioned in https://github.com/conda/conda/issues/5693#issuecomment-505579189.

**Comment by cjw296** [comment]
Yeah, this is a dupe of #5693, thanks for the link!
