### ISSUE TITLE
Miniconda not opening on localhost

### ISSUE THREAD

**Issue by akshit0201** [conda/conda#10683]
I've installed the docker image of miniconda and connected it to localhost:8888. Yet, the page isn't opening.
<img width="1433" alt="Screenshot 2021-05-23 at 10 47 35 PM" src="https://user-images.githubusercontent.com/57068848/119272812-f58fa180-bc18-11eb-83cd-b9540c95ef0e.png">

**Comment by jezdez** [comment]
Please file a ticket in the appropriate repo: https://github.com/ContinuumIO/anaconda-issues/issues/new
