### ISSUE TITLE
_tkinter.TclError: invalid command name ".!canvas"

### ISSUE THREAD

**Issue by lingxiao-Zhu** [conda/conda#10680]
## Current Behavior
I use “conda create” to create a env folder，and use python in the env to run code with turtle, window opened, but animation not work, when I close the window, I get this error:

![image](https://user-images.githubusercontent.com/22609330/119231829-4fc72e80-bb55-11eb-81d4-476a11b0e366.png)

### Steps to Reproduce
```python
import turtle
import time

t = turtle.Turtle()

turtle.bgpic('小八1.png') // remove this line, code run fine
turtle.forward(350)

pos = turtle.pos()  

turtle.done()
```

## Environment Information
miniconda  Python 3.8

**Comment by jezdez** [comment]
I'm sorry but this is unrelated to the conda package manager this issue tracker is about. Thank you!
