### ISSUE TITLE
Help of miniconda windows installer is missing doc for silent install mode

### ISSUE THREAD

**Issue by mbyt** [conda/conda#1068]
I was using the Miniconda windows installer from http://conda.pydata.org/miniconda.html --- and happily found out that a silent install mode is supported. It took quite a while to discover that, as the doc shown by running the installer with the `/?` option does not show these options at all. Running  `Miniconda-3.7.0-Windows-x86.exe /?` will show a window with:
```
Usage Miniconda-3.7.0-Windows-x86.exe [options]
Options:

/InstallationType=AllUsers [default: JustMe]

/AddToPath=[0|1] [default: 1]

/RegisterPython=[0|1] [default: AllUsers: 1, JustMe: 0]

Examples:
Install for all users, but don't add to PATH env var:
Miniconda-3.7.0-Windows-x86.exe /InstallationType=AllUsers
/AddToPath=0

Install for just me, but register the system Python:
Miniconda-3.7.0-Windows-x86.exe /RegisterPython=1
```

This option list is missing the available options
```
/S

/D=C:\Miniconda
```
for silent install mode (unattended install mode) and the installation directory respectively.

Also the documentation on http://conda.pydata.org/miniconda.html, or http://conda.pydata.org/docs/index.html are not mentioning the command line options of the installer for conda / miniconda.

The only hint I could find was: http://docs.continuum.io/anaconda/install.html#windows-install, which itself is not mentioning the supported options  `AddToPath` `RegisterPython` `InstallationType`.

**Comment by mbyt** [comment]
I was "greping" for the miniconda installation options (i.e. `AddToPath`) in the conda repo, but couldn't find the source.

I am happy to add a options section to https://github.com/conda/conda-docs however, a far as I see, the installation process of miniconda is not explained at all. I was looking for something analogous to http://docs.continuum.io/anaconda/install.html... how and where would you put such a doc?

**Comment by zonksoft** [comment]
Also, the path after /D does not support ", i.e. quotes. It also needs to be at the end of the parameter list because all parameters will be appended to the path otherwise. A working option string is therefore

Miniconda-3.7.0-Windows-x86_64.exe /AddToPath=1 /RegisterPython=1 /InstallationType=AllUsers /S /D=C:\my_directory

**Comment by faph** [comment]
Updated docs at: http://conda.pydata.org/docs/installation.html

@asmeurer issue can be closed, many thanks.
