### ISSUE TITLE
I cannot use the latest installed version of package in jupyter notebook

### ISSUE THREAD

**Issue by laurence-lin** [conda/conda#10681]
I've python independently installed, and another anaconda installed on my PC.

Usually I installed package via pip, but recently after viewing this post: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

I realize that using conda to install would prevent some package version error.

However, while I installed the latest version of pandas==1.2.4, then I run the jupyter notebook, I could only get pandas==1.0.5 which is installed in python.

I suspect that jupyter notebook get the package from original python installed, so I create an environment and installed latest version package on it, and launch the notebook in the environment, but the problem remains.

How could I use the latest version of pandas in the jupyter notebook? Even if I install the package in the notebook via conda, it stilled use the older version.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
