### ISSUE TITLE
conda install for python3-gdbm

### ISSUE THREAD

**Issue by kuro-obi** [conda/conda#1069]
Hi,
After installing python-3 via Continuum's python-Anaconda (http://continuum.io/blog/anaconda-python-3), I am still unable to import dbm.gnu package.

I have also tried installing gdbm package from:
$conda install --channel https://conda.binstar.org/xanderhsia gdbm

Any suggestions on how to continue?

Thanks

**Comment by soapy1** [comment]
Duplicate issue: https://github.com/ContinuumIO/anaconda-issues/issues/126
