### ISSUE TITLE
Switch from `ruamel_yaml(_conda)` to maintained `ruamel.yaml`

### ISSUE THREAD

**Issue by jezdez** [conda/conda#10691]
## Current Behavior
https://github.com/conda/conda/pull/10441 renamed the names of the `ruamel_yaml`/`ruamel.yaml` to `ruamel_yaml_conda` to both which effectively breaks Python packaging of conda.

### Steps to Reproduce

```
pip install -e .
```

```
$ pip install -e .
Obtaining file:///Users/jezdez/Code/git/conda
Collecting pycosat>=0.6.3
  Using cached pycosat-0.6.3-cp39-cp39-macosx_11_0_x86_64.whl
Collecting requests>=2.12.4
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
ERROR: Could not find a version that satisfies the requirement ruamel_yaml_conda>=0.11.14 (from conda)
ERROR: No matching distribution found for ruamel_yaml_conda>=0.11.14
```

## Expected Behavior

There shouldn't be a dependency error.

## Tasks

- [x] 🔍 Investigate and understand state of the world (timebox: two days)
- [x] 👨🏻‍💻 Aggregate community efforts add missing logic (https://github.com/conda/conda/pull/11837)
    - https://github.com/conda/conda/pull/11014
    - https://github.com/conda/conda/pull/11632
- [ ] 🕵🏻 Code review
- [ ] ✅ Merge

**Comment by jezdez** [comment]
@cjmartian Do you remember why ruamel_yaml_conda was used in the first place?

**Comment by cjmartian** [comment]
> @cjmartian Do you remember why ruamel_yaml_conda was used in the first place?

I do not, sorry

**Comment by jezdez** [comment]
Ugh, seems like this is kind of a long story of Anaconda forking ruamel.yaml and release it as "ruamel_yaml", and then tripping over pip's tightening project name validation.

Refs (note the difference in repo names) with the history:
https://github.com/conda-forge/ruamel_yaml-feedstock/issues/1
https://github.com/conda-forge/ruamel.yaml-feedstock/issues/7

I'm fairly sure we need to clean this up and simply use not the fork but the other one since it seems as if the changes are only superficial. @chenghlee have you seen this before?

**Comment by jezdez** [comment]
Seems like https://github.com/conda-forge/ruamel_yaml-feedstock/commit/8a5610bd2f31aa039527c0e792bdc33a44e74a74 has the info where the _conda suffix was added.

**Comment by jezdez** [comment]
https://github.com/conda/conda/issues/10178 is a good reason to tackle that, too

**Comment by willliu** [comment]
Dear Community:

I tried to build the condo from source as the first step to migrate conda ecosystem to the CPU ISA `loongarch64`. When I type

`sudo python3 setup.py install`

The following error about `ruamel_yaml` happens: (otherwise everything else successfully builds) 

```
creating build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/PKG-INFO -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/SOURCES.txt -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/dependency_links.txt -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/entry_points.txt -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/not-zip-safe -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/requires.txt -> build/bdist.linux-loongarch64/egg/EGG-INFO
copying conda.egg-info/top_level.txt -> build/bdist.linux-loongarch64/egg/EGG-INFO
creating 'dist/conda-4.10.3.post10+8bf56feb7-py3.7.egg' and adding 'build/bdist.linux-loongarch64/egg' to it
removing 'build/bdist.linux-loongarch64/egg' (and everything under it)
Processing conda-4.10.3.post10+8bf56feb7-py3.7.egg
removing '/usr/local/lib/python3.7/dist-packages/conda-4.10.3.post10+8bf56feb7-py3.7.egg' (and everything under it)
creating /usr/local/lib/python3.7/dist-packages/conda-4.10.3.post10+8bf56feb7-py3.7.egg
Extracting conda-4.10.3.post10+8bf56feb7-py3.7.egg to /usr/local/lib/python3.7/dist-packages
conda 4.10.3.post10+8bf56feb7 is already the active version in easy-install.pth
Installing conda script to /usr/local/bin

Installed /usr/local/lib/python3.7/dist-packages/conda-4.10.3.post10+8bf56feb7-py3.7.egg
Processing dependencies for conda==4.10.3.post10+8bf56feb7
Searching for ruamel_yaml_conda>=0.11.14
Reading https://pypi.org/simple/ruamel_yaml_conda/
Reading https://pypi.org/simple/ruamel-yaml-conda/
Couldn't find index page for 'ruamel_yaml_conda' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
```

And `pypi.org/simple/ruamel_yaml_conda` doesn't seem to exit, is it a side effect related to this issue?

Many thanks for you advise

**Comment by yuvipanda** [comment]
If my understanding of the patched ruamel_yaml is correct, https://github.com/conda-forge/ruamel_yaml-feedstock/blob/master/recipe/__init__.py is the only file being changed. I *think* perhaps a rename of what module is being imported would be enough now?

**Comment by nikonikoniko** [comment]
I am also getting the following error:
```
 (main)→ conda
Traceback (most recent call last):
  File "/home/uer/.pyenv/versions/3.7.4/bin/conda", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/uer/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel_yaml_conda>=0.11.14' distribution was not found and is required by conda
```
