### ISSUE TITLE
create a "register" command for conda

### ISSUE THREAD

**Issue by csoja** [conda/conda#107]
Create a "register" command for conda so that it modifies the Windows registry to point to the default conda environment (or a named conda environment).  Allow Windows users to do "conda update conda" and then they could easily register it with their registry. (Modify the registry.)

Particularly for environments to select them as selection targets. It might be nice to install the 'py' and 'pyw' commands (http://www.python.org/dev/peps/pep-0397/) by default as well, which uses this to know how to launch different pythons based on a script's #! line.

**Comment by johnmellor** [comment]
This seems to block using the standard [Python Launcher for Windows](https://docs.python.org/3/using/windows.html#launcher) (`py.exe` and `pyw.exe`) with non-root environments. Other than this missing registry data, the launcher works great with Anaconda/Miniconda when both Python 2 and 3 environments are installed. I posted more detailed analysis at https://github.com/ContinuumIO/anaconda-issues/issues/149#issuecomment-293206061.

**Comment by kalefranz** [comment]
I believe the majority of what's requested here will be covered by `conda init` in conda 4.6.  If there are specific behaviors we want to hook into `conda init`, lets open new tickets for those.
