### ISSUE TITLE
Can not connect to repo of pip when using conda 

### ISSUE THREAD

**Issue by coreyberry** [conda/conda#10706]
(C:\Program Files\Anaconda3) C:\Users\xdadmin> conda install pip
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : win-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 3.5.2.final.0
   requests version : 2.11.1
   root environment : C:\Program Files\Anaconda3  (read only)
default environment : C:\Program Files\Anaconda3
   envs directories : C:\Users\cberry\.conda\envs
                      C:\Program Files\Anaconda3\envs
      package cache : C:\Users\cberry\.conda\envs\.pkgs
                      C:\Program Files\Anaconda3\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : C:\Users\cberry\.condarc
       offline mode : False
```

**Comment by jezdez** [comment]
That's very unusual since that URL is hosted by a CDN called Cloudflare. Can you open any of the URLs in your browser?

**Comment by coreyberry** [comment]
I can open them in my browser.

**Comment by jezdez** [comment]
> I can open them in my browser.

Can you try again running the same command to install pip?
