### ISSUE TITLE
Where is the zoss-appdev/noarch directory?

### ISSUE THREAD

**Issue by vmdave9** [conda/conda#10711]
Hi, I am trying to use conda to create a new environment on IBM's z/OS USS. The command I am using is this:
conda create -n immudb
However I am getting the following error:
IBMUSER:/u/dave/Rocket/miniconda: >conda create -n immudb
Solving environment: done

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://anaconda.org/zoss-appdev/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='anaconda.org', port=443): Max retries exceeded with url: /zoss-appdev/noarch/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x500A8CA2B0>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.'))"))

So where is the anaconda.org/zoss-appdev/noarch/  directory and the repodata.json file?
Many thanks and take care.
DJ

**Comment by chenghlee** [comment]
Can you please provide the output of `conda info` and `conda config --show`? `https://anaconda.org/zoss-appdev/noarch/repodata.json` is not the standard URL for an Anaconda.org package repository, so there might be a misconfiguration issue somewhere.

**Comment by vmdave9** [comment]
Here they are, Cheng; many thanks for taking a look at this:
IBMUSER:/u/ibmuser: >conda info

    active environment : None
           shell level : 0
      user config file : /u/ibmuser/.condarc
populated config files : /u/dave/Rocket/miniconda/.condarc
                         /u/ibmuser/.condarc
         conda version : 4.5.8
   conda-build version : conda-build-3.12.0-py37_2+3.g8ab3902b
        python version : 3.7.0.final.0
      base environment : /u/dave/Rocket/miniconda  (writable)
          channel URLs : https://conda.anaconda.org/zoss-appdev/zos-z
                         https://conda.anaconda.org/zoss-appdev/noarch
         package cache : /u/dave/Rocket/miniconda/pkgs
                         /u/ibmuser/.conda/pkgs
      envs directories : /u/dave/Rocket/miniconda/envs
                         /u/ibmuser/.conda/envs
              platform : zos-z
            user-agent : conda/4.5.8 requests/2.19.1 CPython/3.7.0 z/OS/2.4
z/OS/0
               UID:GID : 0:0
            netrc file : None
          offline mode : False
---------------------------------------------------------------------------------------------
IBMUSER:/u/ibmuser: >conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: False
aggressive_update_packages:
 - ca-certificates
 - certifi
 - openssl
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
 - zoss-appdev
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
 pkgs/main: https://repo.anaconda.com
 pkgs/free: https://repo.anaconda.com
 pkgs/r: https://repo.anaconda.com
 pkgs/pro: https://repo.anaconda.com
custom_multichannels:
 defaults: ["https://repo.anaconda.com/pkgs/main", "
https://repo.anaconda.com/pkgs/free", "https://repo.anaconda.com/pkgs/r", "
https://repo.anaconda.com/pkgs/pro"]
 local: []
default_channels:
 - https://repo.anaconda.com/pkgs/main
 - https://repo.anaconda.com/pkgs/free
 - https://repo.anaconda.com/pkgs/r
 - https://repo.anaconda.com/pkgs/pro
disallowed_packages: []
download_only: False
envs_dirs:
 - /u/dave/Rocket/miniconda/envs
 - /u/ibmuser/.conda/envs
force: False
json: False
local_repodata_ttl: 1
max_shlvl: 2
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
 - /u/dave/Rocket/miniconda/pkgs
 - /u/ibmuser/.conda/pkgs
proxy_servers: {}
quiet: False
read_only_dirs: []
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
IBMUSER:/u/ibmuser: >

**Comment by chenghlee** [comment]
The `conda --info` and `conda config --show` output show no obvious configuration problems, so it's not clear why your installation is looking for `https://anaconda.org/zoss-appdev/noarch/repodata.json` instead of `https://conda.anaconda.org/zoss-appdev/noarch/repodata.json`. (Note the different hostname.)

Are these the most recent releases of conda and conda-build for z/OS? The core conda development team doesn't have access to z/OS systems, so you may have to ask the team who built the z/OS release if they modified something in the code and/or if they have an updated version available.
