### ISSUE TITLE
channel priority stuck on flexible

### ISSUE THREAD

**Issue by Emoshe** [conda/conda#10710]
My conda version is 4.10.1 on windows10 system; the output of 'conda info' is attached.
[conda_info.txt](https://github.com/conda/conda/files/6594768/conda_info.txt)

My .condarc file is:

 channels:
    - defaults
    - conda-forge
 channel_priority: strict

Running  'conda config --describe channel_priority'  I get  'channel_priority: flexible'

Running 'conda config --set channel_priority strict' from the command line I still get 'channel_priority: flexible'

How do I get strict channel priority?

Thanks,
Moshe Elitzur

**Comment by chenghlee** [comment]
Can you please provide the output of `conda config --show-sources`?

**Comment by Emoshe** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Here it is
    
    
    
    
    
    Thanks,
      Moshe Elitzur
    
    
    
    On 6/11/2021 6:58 AM, Cheng H. Lee
      wrote:
    
    
      
      Can you please provide the output of conda config
          --show-sources?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/conda/conda/issues/10710#issuecomment-859601257",
"url": "https://github.com/conda/conda/issues/10710#issuecomment-859601257",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
