### ISSUE TITLE
Conda Environments do not work with Pycharm

### ISSUE THREAD

**Issue by ckyleda** [conda/conda#10714]
## Current Behavior

Install miniconda3 on arch, use pycharm to set up a new conda environment, conda fails with error:

`Preparing transaction: ...working... failed
CondaError: Unable to create prefix directory '/opt/miniconda3/envs/xxxxx'.
Check that you have sufficient permissions.`

### Steps to Reproduce

See above

## Expected Behavior

Conda should not be writing **anything** to /opt/miniconda3/envs - this is not the directory designated in the config for conda environments, and there is no obvious way to change this.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

N/A not a conda package error.
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
N/A
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
N/A
```
</p></details>

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the Conda package manager. Thank you for understanding!
