### ISSUE TITLE
Conda Exception('No compatible shell found!') when creating virtual environment

### ISSUE THREAD

**Issue by imsaravan** [conda/conda#10729]
Hello Team,

Need your help here,

In my current project we are trying to upgrade our conda version. 

Currently we are using conda version 4.5.12 and we are trying to upgrade to 4.9.2.

The package is downloaded and installed perfectly.

But when we try to create virtual environment programmatically via shell file. It throws the below error while downloading and extracting packages.

## Package Plan ##

  environment location: xxx/yyy/zzz

  added / updated specs:
    - python=3.6

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    ca-certificates-2021.5.30  |       ha878542_0         136 KB  conda-forge
    certifi-2021.5.30          |   py36h5fab9bb_0         141 KB  conda-forge
    ld_impl_linux-64-2.35.1    |       hea4e1c9_2         618 KB  conda-forge
    libffi-3.3                 |       h58526e2_2          51 KB  conda-forge
    libgcc-ng-9.3.0            |      h2828fa1_19         7.8 MB  conda-forge
    libgomp-9.3.0              |      h2828fa1_19         376 KB  conda-forge
    libstdcxx-ng-9.3.0         |      h6de172a_19         4.0 MB  conda-forge
    ncurses-6.2                |       h58526e2_4         985 KB  conda-forge
    openssl-1.1.1k             |       h7f98852_0         2.1 MB  conda-forge
    pip-21.1.2                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    python-3.6.13              |hffdb5ce_0_cpython        38.4 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    readline-8.1               |       h46c0cb4_0         295 KB  conda-forge
    setuptools-49.6.0          |   py36h5fab9bb_3         936 KB  conda-forge
    sqlite-3.35.5              |       h74cdb3f_0         1.4 MB  conda-forge
    tk-8.6.10                  |       h21135ba_1         3.2 MB  conda-forge
    wheel-0.36.2               |     pyhd3deb0d_0          31 KB  conda-forge
    xz-5.2.5                   |       h516909a_1         343 KB  conda-forge
    zlib-1.2.11                |    h516909a_1010         106 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        62.0 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.5.30-ha878542_0
  certifi            conda-forge/linux-64::certifi-2021.5.30-py36h5fab9bb_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_19
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_19
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_19
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  openssl            conda-forge/linux-64::openssl-1.1.1k-h7f98852_0
  pip                conda-forge/noarch::pip-21.1.2-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.6.13-hffdb5ce_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.6-1_cp36m
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py36h5fab9bb_3
  sqlite             conda-forge/linux-64::sqlite-3.35.5-h74cdb3f_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010

Downloading and Extracting Packages

readline-8.1         | 295 KB    |            |   0% 
readline-8.1         | 295 KB    | 5          |   5% 
readline-8.1         | 295 KB    | ########## | 100% 
readline-8.1         | 295 KB    | ########## | 100% 

setuptools-49.6.0    | 936 KB    |            |   0% 
setuptools-49.6.0    | 936 KB    | #######6   |  77% 
setuptools-49.6.0    | 936 KB    | ########## | 100% 
sqlite-3.35.5        | 1.4 MB    |            |   0% 
sqlite-3.35.5        | 1.4 MB    | ########## | 100% 
sqlite-3.35.5        | 1.4 MB    | ########## | 100% 

ca-certificates-2021 | 136 KB    |            |   0% 
ca-certificates-2021 | 136 KB    | ########## | 100% 

zlib-1.2.11          | 106 KB    |            |   0% 
zlib-1.2.11          | 106 KB    | ########## | 100% 
python-3.6.13        | 38.4 MB   | #########9 | 100% 
python-3.6.13        | 38.4 MB   | ########## | 100% 

xz-5.2.5             | 343 KB    |            |   0% 
xz-5.2.5             | 343 KB    | ########## | 100% 
xz-5.2.5             | 343 KB    | ########## | 100% 

wheel-0.36.2         | 31 KB     |            |   0% 
wheel-0.36.2         | 31 KB     | ########## | 100% 
libgcc-ng-9.3.0      | 7.8 MB    | ######8    |  69% 
libgcc-ng-9.3.0      | 7.8 MB    | ########## | 100% 
libgcc-ng-9.3.0      | 7.8 MB    | ########## | 100% 

libgomp-9.3.0        | 376 KB    |            |   0% 
libgomp-9.3.0        | 376 KB    | ########## | 100% 
libgomp-9.3.0        | 376 KB    | ########## | 100% 

openssl-1.1.1k       | 2.1 MB    |            |   0% 
openssl-1.1.1k       | 2.1 MB    | #########6 |  96% 
openssl-1.1.1k       | 2.1 MB    | ########## | 100% 
libstdcxx-ng-9.3.0   | 4.0 MB    | ####9      |  49% 
libstdcxx-ng-9.3.0   | 4.0 MB    | ########## | 100% 
libstdcxx-ng-9.3.0   | 4.0 MB    | ########## | 100% 

ncurses-6.2          | 985 KB    |            |   0% 
ncurses-6.2          | 985 KB    | ########## | 100% 
ncurses-6.2          | 985 KB    | ########## | 100% 
_openmp_mutex-4.5    | 22 KB     |            |   0% 
_openmp_mutex-4.5    | 22 KB     | ########## | 100% 

tk-8.6.10            | 3.2 MB    |            |   0% 
tk-8.6.10            | 3.2 MB    | ######1    |  62% 
tk-8.6.10            | 3.2 MB    | ########## | 100% 
tk-8.6.10            | 3.2 MB    | ########## | 100% 
pip-21.1.2           | 1.1 MB    |            |   0% 
pip-21.1.2           | 1.1 MB    | ########## | 100% 
pip-21.1.2           | 1.1 MB    | ########## | 100% 

ld_impl_linux-64-2.3 | 618 KB    |            |   0% 
ld_impl_linux-64-2.3 | 618 KB    | ########## | 100% 
ld_impl_linux-64-2.3 | 618 KB    | ########## | 100% 

libffi-3.3           | 51 KB     |            |   0% 
libffi-3.3           | 51 KB     | ########## | 100% 

certifi-2021.5.30    | 141 KB    |            |   0% 
certifi-2021.5.30    | 141 KB    | ########## | 100% 

python_abi-3.6       | 4 KB      |            |   0% 
python_abi-3.6       | 4 KB      | ########## | 100% 

_libgcc_mutex-0.1    | 3 KB      |            |   0% 
_libgcc_mutex-0.1    | 3 KB      | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Rolling back transaction: ...working... done

Exception('No compatible shell found!')
()

## Current Behavior
Virtual Environment is not created successfully. We tried to pass the create virtual environment in the server itself and it ran successfully. Fails when the command ran via a shell.

## Expected Behavior
Virtual Environment should be created successfully.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
```
active environment : base
    active env location : xxx/yyy/zzz/miniconda
            shell level : 1
       user config file : /home/xxx/.condarc
 populated config files : /home/xxx/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : xxx/yyy/zzz/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : xxx/yyy/zzz/miniconda/pkgs
                          /home/xxx/.conda/pkgs
       envs directories : xxx/yyy/zzz/miniconda/envs
                          /home/xxx/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.1 Linux/3.10.0-1160.15.2.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 27650:26686
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>
```
# packages in environment at /xxx/yyy/zzz/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2020.12.8            h06a4308_0    defaults
certifi                   2020.12.5        py39h06a4308_0    defaults
cffi                      1.14.4           py39h261ae71_0    defaults
chardet                   3.0.4           py39h06a4308_1003    defaults
conda                     4.9.2            py39h06a4308_0    defaults
conda-package-handling    1.7.2            py39h27cfd23_1    defaults
cryptography              3.3.1            py39h3c74f83_0    defaults
idna                      2.10                       py_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1i               h27cfd23_0    defaults
pip                       20.3.1           py39h06a4308_0    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.0             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.1                hdb3f193_2    defaults
readline                  8.0                  h7b6447c_0    defaults
requests                  2.25.0             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.80          py39h27cfd23_0    defaults
setuptools                51.0.0           py39h06a4308_2    defaults
six                       1.15.0           py39h06a4308_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.54.1             pyhd3eb1b0_0    defaults
tzdata                    2020d                h14c3975_0    defaults
urllib3                   1.25.11                    py_0    defaults
wheel                     0.36.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults

```
</p></details>

**Comment by imsaravan** [comment]
@Team, Kindly help me why do i get Exception('No compatible shell found!') when i try to create virtual environment from a shell command. NOTE: conda create command works pretty well when using in CLI.

**Comment by comtihon** [comment]
Same problem for me. I am running conda from JVM as a process with sdtin/stdout piped.
Worked a year or two ago, but now stopped.
PATH variables were passed to the runtime config, so JVM knows where conda exec is.
