### ISSUE TITLE
DLL load failed while importing _arpack

### ISSUE THREAD

**Issue by iftaqul789** [conda/conda#10720]
![jypter](https://user-images.githubusercontent.com/70629137/121767100-e646a880-cb73-11eb-98b2-48754a254579.png)

**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the Conda package manager. Thank you for understanding!
