### ISSUE TITLE
New Environment taking base env packages even after activating the new env (Windows bug)

### ISSUE THREAD

**Issue by Deepankar-98** [conda/conda#10733]
## Current Behavior

On creating a new environment using `conda create --n test_env` & **activating** it, it is still taking the package from the "base" environment instead of installing the packages in the new environment.
But instead if I use `conda create --n test_env python==3.7`, its works as expected.

I am using **Windows 10** OS with build number **19041.867**. 

On reading online I found that this a Windows specific bug & others have also faced it.
<br>

### Steps to Reproduce

The steps are as follows:

```
(base) C:\Users\DEEPANKAR MULLICK>conda deactivate

C:\Users\DEEPANKAR MULLICK>conda create -n test_env_issue
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: F:\InstallationFolder\anaconda\envs\test_env_issue

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test_env_issue
#
# To deactivate an active environment, use
#
#     $ conda deactivate


C:\Users\DEEPANKAR MULLICK>conda activate test_env_issue

(test_env_issue) C:\Users\DEEPANKAR MULLICK>pip install sklearn
Requirement already satisfied: sklearn in c:\python38\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\python38\lib\site-packages (from sklearn) (0.23.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\python38\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\python38\lib\site-packages (from scikit-learn->sklearn) (1.5.4)
Requirement already satisfied: numpy>=1.13.3 in c:\python38\lib\site-packages (from scikit-learn->sklearn) (1.18.5)
Requirement already satisfied: joblib>=0.11 in c:\python38\lib\site-packages (from scikit-learn->sklearn) (0.17.0)

(test_env_issue) C:\Users\DEEPANKAR MULLICK>
```
**Note -- It shows requirements already satisfied even though it is a new environment & it happens for other packages as well.**
<br>

## Expected Behavior

On running the command 'pip install sklearn' or with other python packages in Windows 10 OS, it should install the package & its dependencies, instead of taking the packages from the **base** environment.

<br>

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(test_env_issue) C:\Users\DEEPANKAR MULLICK>conda info

     active environment : test_env_issue
    active env location : F:\InstallationFolder\anaconda\envs\test_env_issue
            shell level : 1
       user config file : C:\Users\DEEPANKAR MULLICK\.condarc
 populated config files : C:\Users\DEEPANKAR MULLICK\.condarc
          conda version : 4.10.1
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : F:\InstallationFolder\anaconda  (writable)
      conda av data dir : F:\InstallationFolder\anaconda\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : F:\InstallationFolder\anaconda\pkgs
                          C:\Users\DEEPANKAR MULLICK\.conda\pkgs
                          C:\Users\DEEPANKAR MULLICK\AppData\Local\conda\conda\pkgs
       envs directories : F:\InstallationFolder\anaconda\envs
                          C:\Users\DEEPANKAR MULLICK\.conda\envs
                          C:\Users\DEEPANKAR MULLICK\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.4 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

(test_env_issue) C:\Users\DEEPANKAR MULLICK>
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(test_env_issue) C:\Users\DEEPANKAR MULLICK>conda config --show-sources
==> C:\Users\DEEPANKAR MULLICK\.condarc <==
ssl_verify: True
channels:
  - defaults


(test_env_issue) C:\Users\DEEPANKAR MULLICK>
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(test_env_issue) C:\Users\DEEPANKAR MULLICK>conda list --show-channel-urls
# packages in environment at F:\InstallationFolder\anaconda\envs\test_env_issue:
#
# Name                    Version                   Build  Channel

(test_env_issue) C:\Users\DEEPANKAR MULLICK>
```
</p></details>

**Comment by msm1089** [comment]
Same problem here. Also, when creating a new env with 'conda create -n new_env' the 'new_env' folder contains only the metadata file.

**Comment by Deepankar-98** [comment]
Yes, this is a bug. 
You can try this command. It worked for me:
`conda create --n new_env python==<any-version>`

Hoping this issue to be fixed soon!!!

**Comment by chenghlee** [comment]
This is not a bug, but rather an issue with insufficient and/or out-dated documentation/online information. `conda create -n new_env` with no other arguments tells conda to create an empty environment with no packages installed in it; when that `new_env` is then activated, you are picking up the first Python interpreter in your `%PATH%` environment variable (which, in this case, happens to be the one inf the base environment).

If you want a Python interpreter in your conda environment, you need to explicitly request one as part of the environment creation process (i.e., `conda create -n new_env python`) or `conda install` one after you have activated the environment. Conda does not install a Python interpreter into a new environments by default because it is a cross-platform, cross-language package manager, and it's not a safe assumption that every environment will need a Python interpreter.

**Comment by Deepankar-98** [comment]
Hi @chenghlee,

I completely agree with the above explanation. 
But in this case, the issue I was facing is not with the python interpreter, but rather with my newly created & activated conda environment taking the package dependencies present in the base environment.

For example:
If I activate my new env & run `pip install sklearn`, it gives me **"Requirement already satisfied"** even though I am trying to install the package in this new environment for the first time.
