### ISSUE TITLE
current flow of tarball installs with `conda install --offline` is incorrect

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1075]
I'm attempting to install a directory of tarballs using `conda install --offline`.  The packages install, but after the `Linking packages ...` display I'm told it's fetching metadata, solving dependencies, and so on.  The output is:

```
$ conda install --offline ./conda/osx-64/*.tar.bz2
[      COMPLETE      ] |##############################################| 100%
Extracting packages ...
[      COMPLETE      ] |##############################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##############################################| 100%
Linking packages ...
[      COMPLETE      ] |##############################################| 100%
depends: [u'python 2.7*', u'openssl 1.0.1*', u'readline 6.2', u'sqlite', u'tk 8.5*', u'zlib 1.2.7']
Fetching package metadata:
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /Users/travis/anaconda/envs/zxc:
#
openssl                   1.0.1j                        4    defaults
python                    2.7.9                         1    defaults
readline                  6.2                           2    <unknown>
sqlite                    3.8.4.1                       0    defaults
tk                        8.5.15                        0    defaults
zlib                      1.2.7                         2    defaults
```

I had a hunch that it was trying to solve dependencies for the things it just installed and then install any missing dependencies.  To test that, I created a new environment, removed zlib from the directory and installed.  Sure enough it installed all of the tarballs I asked it to, then prompted me to see if I wanted to install zlib from (I presume) my package cache.
## Question: Is that behavior correct?

I would have thought that the prompt would include everything that was about to be installed.  Right now it appears that installing directly from `.tar.bz2` short-circuits the index lookup and confirmation.  I don't think we should do that.

The current code causes a problem for packages that are sent for offline installation without all of the dependencies attached.  For example, `python` requires version 8.5\* of `tk`.  If you have the tarball of `python` but not `tk` and install that tarball with `--offline`, the `python` package installs but the installation process fails when its unable to resolve the `tk` dependency.
## Proposal: Treat the installation process like a transaction

Installations that are handled via normal indexes are handled this way.  You can't install `python` if the index you're using does not have all of the requirements.  I believe we can achieve this by changing the way we install tarballs.

Instead of installing them without any checks, we can parse their meta data, create a package spec meta data, then treat that file as if it were part of the master index.  At that point, we'd send the code down through the rest of the installation process, which behaves like a transaction.

Thoughts @ilanschnell @teoliphant @asmeurer?

**Comment by tswicegood** [comment]
cc @csoja

**Comment by asmeurer** [comment]
Is the `depends: [u'python 2.7*', u'openssl 1.0.1*', u'readline 6.2', u'sqlite', u'tk 8.5*', u'zlib 1.2.7']` bit actually printed, or did you leave a print statement in there?

**Comment by tswicegood** [comment]
@asmeurer yes, the direct tarball install prints the `depends`.

**Comment by asmeurer** [comment]
OK, that's obviously a debug statement that was left in then.

**Comment by asmeurer** [comment]
Debug statement removed.

**Comment by asmeurer** [comment]
I think the issue here is related to the fact you are installing from a tarball, not the `--offline` flag.

**Comment by tswicegood** [comment]
@asmeurer you are correct, sort of.  The problem here was that `zlib` couldn't be found.  Had I not used the `--offline` parameter, `conda` would have fetched indexes remotely and found a copy.  It was definitely caused by the tarball, then exacerbated by `--offline`.

**Comment by asmeurer** [comment]
So I think it's the combination of the two that causes the issue then. If you had only used `--offline` or only used tarballs it probably would have worked.

**Comment by tswicegood** [comment]
@asmeurer no.  The issue is that python would have been installed without zlib (or any other library) if I delete that from the tarball.  Right now, tarballs do no checking of dependencies until after they're already installed.  I could be wrong, but that's the only way I could reason about this code as to how every package but zlib was installed even though `python` won't install without zlib.

**Comment by ilanschnell** [comment]
The reason the tarballs are installed first is to get their metadata.  However, now that I think of it, it would be also possible to:
  * extract the tarballs
  * determine the dependency packages
  * extract the dependency packages
  * link everything

This way, there would be a single link step at the end, and if anything goes wrong nothing would get linked.

**Comment by asmeurer** [comment]
Would the resolve code be used anywhere in that process?

**Comment by ilanschnell** [comment]
It would have to be used.  Wouldn't it?

**Comment by tswicegood** [comment]
@ilanschnell that seems reasonable, but it sounds like the tarball wouldn't be in the package cache after that.  That's not what I would expect to happen.

In offline mode, I expect to be able to:

* `conda install /path/to/some_pkg-1.0-0.tar.bz2`
* Then `conda install some_pkg` and re-use the tarball that was created above

If what you're suggesting does that, perfect!

**Comment by asmeurer** [comment]
To answer the question raised in the issue title, the current flow is not correct. Currently, the tarball is installed and then its dependencies. If the installation of dependencies fails it the tarball is still installed. The dependencies should be installed first, and then the tarball. And many of the command line flags, like --dry-run, are not respected.
