### ISSUE TITLE
(venv) (base) both environments active

### ISSUE THREAD

**Issue by ashutoshshukla2894** [conda/conda#10754]
Hi,

I am facing a recent issue with miniconda. I have created a new virtual environment `single_year` for some project. Now when I try to `conda activate single_year`, everything works fine without any error. But all installations that I do in this new environment gets installed in base. Also only recently I have started seeing (venv) (base) both appearing in the terminal. Otherwise it would always switch to `(venv)` from `(base)`.

Also I tried `which python` both in base in conda environment and they both point to same location. I do not think this is expected.
<img width="943" alt="Screen Shot 2021-06-26 at 7 39 04 PM" src="https://user-images.githubusercontent.com/7523117/123530331-2cdcec80-d6b6-11eb-8388-ae8b9c65d06c.png">

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
