### ISSUE TITLE
unable to update pandas package

### ISSUE THREAD

**Issue by jash-ai** [conda/conda#10755]
## Current Behavior
 hi am on the panadas package 0.23.4 and would to upgrade to 1.0.5 but everytime i have tried it has not worked in anaconda. is there any command shell way of doing this. as a number of functions in pandas has stopped working ie info(), and get back an error Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### Steps to Reproduce

import pandas as pd
import numpy as np

diabetes_dataset = pd.read_csv('Diabetes.csv')
diabetes_dataset.head(10)

diabetes_dataset.info()

and i get the following error
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by giladmaya** [comment]
@jash-ai 
Can you please share the output of `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls`?
Also, you've mentioned that you've tried to upgrade pandas but it didn't work - can you also share the exact command that you've tried and its' output?
Without this information, it would be hard to assist you in resolving this issue
