### ISSUE TITLE
Error while updating on Raspberry Pi 4

### ISSUE THREAD

**Issue by pucky429** [conda/conda#10760]
Hello,

I run into an error when I try to update openssl on a raspberry pi 4. The OS I am using is Raspbian 64bit.
I pasted all the information below.

Thanks in advance!

## Current Behavior

Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
/home/pi/miniconda3/bin/.openssl-post-link.sh: line 7: /home/pi/miniconda3/bin/.openssl-libcrypto-fix: cannot execute binary file: Exec format error
Error: Error: post-link failed for: openssl-1.0.2l-0

### Steps to Reproduce

```
$ conda update --prefix /clusterfs/miniconda/ openssl
```

## Expected Behavior

It should update openssl

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

             platform : linux-32
        conda version : 3.16.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /clusterfs/miniconda  (writable)
  default environment : /clusterfs/miniconda
     envs directories : /clusterfs/miniconda/envs
        package cache : /clusterfs/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --show-channel-urls

```
</p></details>

**Comment by chenghlee** [comment]
Are you running conda from a shared/network filesystem? The output of `conda info` shows your installation is a 32-bit x86 (i686) Linux install; this is the wrong architecture for a Raspberry Pi (aarch64).
