### ISSUE TITLE
bash: conda: No such file or directory

### ISSUE THREAD

**Issue by assia855** [conda/conda#10761]
Hello folks, 

I install miniconda2 it was working fine, but once I move it from a directory to another I can't launch conda. 

> source conda activate
bash: conda: No such file or directory

Please can you help me resolve that.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
