### ISSUE TITLE
Fix TravisCI tests

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1077]
TravisCI tests are currently broken because Python 3.3 tests are not passing.  @asmeurer said he knew a way to fix this without a release of Miniconda.  We need to get this fixed as soon as possible so we can rely on TravisCI to produce accurate results instead of ignoring a series of failed tests.

**Comment by tswicegood** [comment]
@ilanschnell it appears that @asmeurer is out until mid-week -- do you have any idea what's going on here and how to fix it?  See #1076 for examples of tests that pass, but TravisCI failures because of 3.3 support.

**Comment by asmeurer** [comment]
It fails because old conda's can't update themselves. We should really fix that, but a workaround is to `conda update --no-deps conda` before installing anything else.
