### ISSUE TITLE
Replace custom vendor solution with vendoring package

### ISSUE THREAD

**Issue by jezdez** [conda/conda#10778]
The way we currently vendor packages is done in a way that makes it harder to automate security patches. We should start using the [vendoring](https://pypi.org/project/vendoring/) for this which was extracted from pip which also vendors a number of core dependencies.

The [README for pip's vendor directory](https://github.com/pypa/pip/blob/main/src/pip/_vendor/README.rst) has some good reasons why we should follow their example.

**Comment by LtDan33** [comment]
If we are going to start using [vendoring](https://pypi.org/project/vendoring/) , wouldn't there be a concern over this? : `This tool has no stability promises -- it has only one intended user: pip. There may be unannounced changes to this codebase at any time, as long as the intended user (i.e. the pip project) is prepared for those changes.`

**Comment by kenodegard** [comment]
@jezdez @LtDan33 hm i hadn't thought about the `auxlib` license ([ISC](https://en.wikipedia.org/wiki/ISC_license)), how do we want to handle that? I'm wondering if that will make it a little more convoluted to go the absorbing route?
