### ISSUE TITLE
Add PyPy to test matrix

### ISSUE THREAD

**Issue by jezdez** [conda/conda#10773]
In #10772 we talked about PyPy support and found that it would be splendid to add PyPy as another Python version to run the tests in the CI.

@isuruf replied:

> we don't have all the dependencies needed for the full test suite built yet on conda-forge for PyPy windows. Will try to send a PR once they are built.

This is the ticket to track adding it to the test matrix as soon as that happens.

### Additional context

This is a https://github.com/conda/conda/labels/good%20first%20issue. To work on this, you should already be familiar with how GitHub Actions work. It would especially be nice if you have setup your own testing CI on other repositories.

Please comment on this issue if you would like to pick it up. If we are slow to respond, you can also head to our community chat: https://conda.org/community#chat

**Comment by isuruf** [comment]
We fully support PyPy3.8 and PyPy3.9 on Linux/macOS/Windows. All the dependencies of conda should be available.

**Comment by isuruf** [comment]
I guess for testing we need to make a github container as in https://github.com/conda/conda/blob/main/.github/workflows/ci.yml#L105 ?
