### ISSUE TITLE
The kofamscan can no be install from bioconda

### ISSUE THREAD

**Issue by honghh2018** [conda/conda#10789]
Hi all,
    It show no bin file in the conda environment , as i follow you tutorial to install the KEGG annotation software kofam_scan. 
    conda install kofamscan -c bioconda
    It even display the successfully, but the kofam_scan can not be used in the virtual environment.

Best,
Hanhuihong

**Comment by jezdez** [comment]
Please open the issue with the bioconda project. Thank you!
