### ISSUE TITLE
Support for query string in channel URLs

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#10793]
Currently, conda just throws away any query string portion of a channel URL and will not send
it to the server. This prevents the ability to use servers that require use of query string to hold
access tokens. 

One example of this, is when [hosting a conda channel in Azure blob storage](https://stackoverflow.com/questions/57156341/hosting-private-conda-packages-url-contains-querystring). Because you cannot 
include the Azure SAS token in the channel, as a result you can only host channels in publicly 
accessible locations.

It would be useful if conda would add the ability to pass on a query string in a channel URL
and would treat this attribute like the auth and token attributes in custom_channels entries
by not logging the query string in most cases.

**Comment by abdale** [comment]
Agreed. It would be great to add support for query strings in channel URLs so Conda can pass on the SAS tokens. Hosting private custom channels in a public container isn't a security best practice.
