### ISSUE TITLE
libcrypto asks for directory name that does not exist

### ISSUE THREAD

**Issue by dschult** [conda/conda#1080]
It looks like the libcrypto is supposed to be installed in 
/opt/anaconda1anaconda2anaconda3anaconda4ana....  up to a very large number of anacondas.
This is from a travis build. I haven't tried to isloate it locally, but I can if that would help.

error report:
==========
if [[ "${OPTIONAL_DEPS}" == miniconda ]]; then if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh; fi; bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH"; hash -r; conda info -a; conda config --set always_yes yes --set changeps1 no; conda update -q conda; fi
--2015-01-07 03:16:08--  http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 54.231.19.36
Connecting to repo.continuum.io (repo.continuum.io)|54.231.19.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20091157 (19M) [application/x-sh]
Saving to: `miniconda.sh'
100%[======================================>] 20,091,157  69.5M/s   in 0.3s    
2015-01-07 03:16:08 (69.5 MB/s) - `miniconda.sh' saved [20091157/20091157]
PREFIX=/home/travis/miniconda
installing: python-2.7.6-1 ...
installing: openssl-1.0.1g-0 ...
installing: pycosat-0.6.0-py27_0 ...
installing: pyyaml-3.11-py27_0 ...
installing: readline-6.2-2 ...
installing: sqlite-3.8.4.1-0 ...
installing: system-5.8-1 ...
installing: tk-8.5.13-0 ...
installing: yaml-0.1.4-0 ...
installing: zlib-1.2.7-0 ...
installing: conda-3.4.2-py27_0 ...
Python 2.7.6 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Current conda install:
             platform : linux-64
        conda version : 3.4.2
       python version : 2.7.6.final.0
     root environment : /home/travis/miniconda  (writable)
  default environment : /home/travis/miniconda
     envs directories : /home/travis/miniconda/envs
        package cache : /home/travis/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
# conda environments:
#
root                  *  /home/travis/miniconda
sys.version: 2.7.6 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/travis/miniconda
sys.executable: /home/travis/miniconda/bin/python
conda location: /home/travis/miniconda/lib/python2.7/site-packages/conda
conda-build: None
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /home/travis/.gvm/pkgsets/go1.4/global/overlay/lib:/home/travis/.gvm/pkgsets/go1.4/global/overlay/lib:
PATH: /home/travis/miniconda/bin:/home/travis/virtualenv/python2.7.9/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.4.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.33/bin:./node_modules/.bin:/usr/local/maven-3.2.3/bin:/home/travis/.gvm/pkgsets/go1.4/global/bin:/home/travis/.gvm/gos/go1.4/bin:/home/travis/.gvm/pkgsets/go1.4/global/overlay/bin:/home/travis/.gvm/bin:/home/travis/.gvm/bin:/usr/local/clang-3.4/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.4.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.3/bin:/home/travis/.gvm/pkgsets/go1.4/global/bin:/home/travis/.gvm/gos/go1.4/bin:/home/travis/.gvm/pkgsets/go1.4/global/overlay/bin:/home/travis/.gvm/bin:/home/travis/.gvm/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
WARNING: could import _license.show_info
# try:
# $ conda install -n root _license
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    conda-3.7.4                |           py27_0         160 KB
    openssl-1.0.1j             |                4         2.6 MB
    pycosat-0.6.1              |           py27_0         151 KB
    python-2.7.9               |                1        13.4 MB
    requests-2.5.1             |           py27_0         587 KB
    tk-8.5.15                  |                0         1.8 MB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:        18.8 MB
The following packages will be UN-linked:
    package                    |            build
    ---------------------------|-----------------
    conda-3.4.2                |           py27_0
    openssl-1.0.1g             |                0
    pycosat-0.6.0              |           py27_0
    python-2.7.6               |                1
    tk-8.5.13                  |                0
    zlib-1.2.7                 |                0
The following packages will be linked:
    package                    |            build
    ---------------------------|-----------------
    conda-3.7.4                |           py27_0   hard-link
    openssl-1.0.1j             |                4   hard-link
    pycosat-0.6.1              |           py27_0   hard-link
    python-2.7.9               |                1   hard-link
    requests-2.5.1             |           py27_0   hard-link
    tk-8.5.15                  |                0   hard-link
    zlib-1.2.8                 |                0   hard-link
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    import logging
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    def execute(args, parser):
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    # Shouldn't happen?
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 418, in execute_plan
    if 'conda' in must_have:
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 374, in link
    continue
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/install.py", line 443, in link
    os.lchown(p, 0, 0)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    except subprocess.CalledProcessError as e2:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an binary lib/libcrypto.so.1.0.0'

**Comment by asmeurer** [comment]
This is a known issue that we are working on fixing. The workaround for now is to start with a newer version of Miniconda.

**Comment by dschult** [comment]
Excellent-thank you
