### ISSUE TITLE
Anaconda3 does not support Kerberosv5

### ISSUE THREAD

**Issue by waveschou** [conda/conda#10800]
Hello everyone
My background is to use kerberosV5 for permission authentication in a cluster, and verify user permissions by interacting with KDC tickets.
I encountered a problem. In the mac or big sur system, the ticket obtained by the anaconda3/bin/kinit path request is invalid, and the /usr/bin/kinit request and authentication are completely normal.
The following are the full path and certification output in two ways:
This is my KRB5 kit: (Heimdal 1.5.1apple1)

/anaconda3/bin/kinit:
1./Users/zhou/opt/anaconda3/bin/kinit wavechou@TEST.COM
2./Users/zhou/opt/anaconda3/bin/klist
Ticket cache: KCM:502
Default principal: wavechou@TEST.COM
Valid starting Expires Service principal
07 1 2021 18:12:42 08 1 2021 18:12:37 krbtgt/TEST.COM@TEST.COM

/usr/bin/kinit:
1./usr/bin/kinit wavechou@TEST.COM
2./usr/bin/klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: wavechou@TEST.COM

Valid starting Expires Service principal
07/19/21 15:38:44 07/20/21 15:38:44 krbtgt/TEST.COM@TEST.COM

This is my krb5.conf
[libdefaults]
default_realm = TEST.COM
dns_canonicalize_hostname = false
dns_lookup_realm = false
dns_lookup_kdc = false

kdc_timesync = 1
ccache_type = 4
forwardable = true
proxiable = true

rdns = false
ignore_acceptor_hostname = true
[realms]
TEST.COM = {
kdc = krb5auth1.test.com
kdc = krb5auth2.test.com
kdc = krb5auth3.test.com
kdc = krb5auth.test.com
master_kdc = krb5auth.test.com
admin_server = krb5auth.test.com
default_domain = test.com
}

[domain_realm]
.test.com = TEST.COM
test.com = TEST.COM

[login]
krb4_convert = true
krb4_get_tickets = false

This is my conda message:
[message.txt](https://github.com/conda/conda/files/6839448/message.txt)

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
