### ISSUE TITLE
Cannot install miniconda on my Windows 10

### ISSUE THREAD

**Issue by 1900011604** [conda/conda#10814]
It stucks at post install...

![微信图片_20210727220141](https://user-images.githubusercontent.com/65082432/127167583-baaf6f68-a62d-431f-a324-e85604ffc9e8.jpg)

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
