### ISSUE TITLE
AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix.

### ISSUE THREAD

**Issue by ASHU-web** [conda/conda#10810]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jezdez** [comment]
I'm sorry but without more details there is nothing I can do with this issue.
