### ISSUE TITLE
conda update breaks if xxd (from vim-common) is not installed

### ISSUE THREAD

**Issue by cehbrecht** [conda/conda#1082]
after updating conda today on a minimal centos image the conda installation was broken. Python complained about problems with md5.

This probably happened because a postinstall script did not run because "xxd" was missing. The xxd program is part of the package vim-common. So installing vim-common first (sudo yum install vim-common) and then updating conda works.

To reproduce this you could use the binstar docker image:

$ docker run -i -u binstar -t binstar/linux-64 /bin/bash                                                  
[binstar@c9467ee0a86c ~]$ /opt/miniconda/bin/conda update conda
Fetching package metadata: ...
Solving package specifications: .
Package plan for installation in environment /opt/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.7.4                |           py27_0         160 KB
    openssl-1.0.1j             |                5         2.6 MB
    python-2.7.9               |                1        13.4 MB
    requests-2.5.1             |           py27_0         587 KB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:        16.8 MB

The following packages will be UPDATED:

    conda:    3.7.3-py27_0 --> 3.7.4-py27_0
    openssl:  1.0.1h-1     --> 1.0.1j-5    
    python:   2.7.8-1      --> 2.7.9-1     
    requests: 2.4.3-py27_0 --> 2.5.1-py27_0
    zlib:     1.2.7-0      --> 1.2.8-0     
 [...]
Linking packages ...
/opt/miniconda/bin/.openssl-post-link.sh: line 17: xxd: command not found
/opt/miniconda/bin/.openssl-post-link.sh: line 18: xxd: command not found
/opt/miniconda/bin/.openssl-post-link.sh: line 30: xxd: command not found
sed: couldn't write 4400512 items to stdout: Broken pipe

[...]

$ /opt/miniconda/bin/conda search python
ERROR:root:code for hash md5 was not found.

**Comment by asmeurer** [comment]
Hmm. Is there a more portable command that can convert a hex dump into a binary file?

**Comment by cehbrecht** [comment]
i don't know how you want to handle this but currently the binstar/linux-64 docker image is also missing the xxd executable. Could you add vim-common to that image? Otherwise the binstar-build does not work :(

**Comment by asmeurer** [comment]
We are working on converting the script into a C program, which should be much more portable.

**Comment by asmeurer** [comment]
This has been done.

**Comment by cehbrecht** [comment]
thanks :)
