### ISSUE TITLE
Unable to register environment. Path not writable or missing

### ISSUE THREAD

**Issue by Spadelion** [conda/conda#10824]
Hello, I've encountered a problem. I've looked for many ways to solve it. I could install the software normally before, but then I uninstalled and reinstalled and encountered this problem. I've tried many methods but haven't solved them. I want to ask everyone for help to see if others have encountered this problem. thank you.
When I install, a prompt appears:
Preparing transaction: ...working... done
Executing transaction: ...working... WARNING conda.core.envs_manager:register_env(50): Unable to register environment. Path not writable or missing.
  environment location: D:\Anaconda3
  registry file: C:\Users\qiqia\.conda\environments.txt
done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: ...working... done

[WinError 2] The system cannot find the specified file。
()

**Comment by Spadelion** [comment]
![pro](https://user-images.githubusercontent.com/88243384/127744549-7b2844f7-6e15-4c24-8977-1b5348510f8b.png)

**Comment by Spadelion** [comment]
Thank you for your help

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
