### ISSUE TITLE
Conda folders added to end of PATH when opening login shell using -l flag

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#10829]
## Current Behavior
When I start a shell (either zsh or fish) using the `-l` flag for *login*, the conda folders are added to the *end* of PATH rather than the beginning, how it should be.

I noticed this, because VS Code adds `-l` by default on mac OS. I opened an issue in VS code to address it from their end. But it may be better to fix it within conda, if this is unintended, rather than me not understanding something.

This is the issue I opened for VS Code: https://github.com/microsoft/vscode/issues/129979

### Steps to Reproduce

```
zsh -l
echo $PATH
```

## Expected Behavior

```
% echo $PATH
/usr/local/Caskroom/mambaforge/base/bin:/usr/local/Caskroom/mambaforge/base/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

## Actual Behaviour
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Caskroom/mambaforge/base/bin:/usr/local/Caskroom/mambaforge/base/condabin
```

## Environment Information
<details open><summary><code>
```
</code></summary><p>
<!-- between the ticks below, paste the output of 'conda info' -->

```

     active environment : base
    active env location : /usr/local/Caskroom/mambaforge/base
            shell level : 1
       user config file : /Users/cr/.condarc
 populated config files : /usr/local/Caskroom/mambaforge/base/.condarc
                          /Users/cr/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/mambaforge/base  (writable)
      conda av data dir : /usr/local/Caskroom/mambaforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/Caskroom/mambaforge/base/pkgs
                          /Users/cr/.conda/pkgs
       envs directories : /usr/local/Caskroom/mambaforge/base/envs
                          /Users/cr/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by jezdez** [comment]
Hmm, I'm not sure conda can do much about in which environment is run in, or at least I don't have an immediate idea how to prevent this from happening in a reproducible way. IIRC when -l is used the profile files are run during start of the shell, and that implies something is going on (either in your ~/.zprofile or in the global profile file). I see you're using mambaforge in the PATH, is the code for that essentially the same as Conda's?
