### ISSUE TITLE
Miniconda 3.9 x64 being picked up as infected by McAfee Endpoint Security 10.7

### ISSUE THREAD

**Issue by HobAnagerik** [conda/conda#10827]
When attempting to download Miniconda 3.9 x64. McAfee AV blocks the download.

https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Windows-x86_64.exe

I tested the 3.9 x86, and that worked.  So did 3.8 x64, and 3.7 x64.

We created an exception for the file, and I was then able to download it, however a 30 second pause is generated while right-clicking on it.  This does not occur on the other versions listed above.

The file has been submitted to McAfee for inspection.

## Current Behavior
Download is blocked, email report of the presumably false positive as below:

USER ran C:\Program Files (x86)\Google\Chrome\Application\chrome.exe which tried to access C:\Users\USER\Downloads\8a8336c0-0659-4e88-8e2c-fc54e6c959f9.tmp. The Trojan named Artemis!128F0CA2C554 was the Infected file deleted.

Event ID:1027
 
Threat name:Artemis!128F0CA2C554 

Threat handled? True at 08/02/21 08:25:43 UTC

Source User:

Target User:USER

Target File:C:\Users\USER\Downloads\8a8336c0-0659-4e88-8e2c-fc54e6c959f9.tmp

Target Process:

Source Process:C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Event Description:Infected file deleted.

### Steps to Reproduce
Click on the above link to download version 3.9 x64.  Must have McAfee Endpoint Security 10.7 installed

## Expected Behavior
The file should download as you would expect.

**Comment by HobAnagerik** [comment]
I just received an update that the installer for 3.9 that was submitted to McAfee has been accepted as a false positive, and after the exceptions were removed the installer can still be downloaded, and the 30 second delay when right-clicking on it has also been removed.

**Comment by jezdez** [comment]
I'm glad this worked out!
