### ISSUE TITLE
Navigator error

### ISSUE THREAD

**Issue by Max-Nguyen-2011** [conda/conda#10826]
i'm new at using the anaconda navigator and when i open it show this screen and i can't open it any more.
![image_2021-08-01_233145](https://user-images.githubusercontent.com/85738743/127778426-bca35a0f-84c6-4ad8-91d5-88cc44cd6407.png)

**Comment by Max-Nguyen-2011** [comment]
Someone help me pls

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
