### ISSUE TITLE
conda-env update does not respect `variables:`

### ISSUE THREAD

**Issue by mfansler** [conda/conda#10830]
## Overview

The `conda-env update` command does not update environment variables listed under the `variables:` key.

## Reproduce

**vars.yaml**
```yaml
variables:
  FOO: bar
```

**Steps**
```bash
## create an empty env
conda create -qyn foo

## update using YAML
conda env update -n foo -f vars.yaml

## activate, and list the env vars
conda activate foo
conda env config vars list
```

## Result

No variables are shown.

## Expected Result

The variable should be set and the result of the last command should be

```bash
FOO = bar
```

## Additional Details

Conda version 4.10.3

In contrast, running `conda env create -n bar -f vars.yaml` works just fine.

**Comment by jezdez** [comment]
Duplicate of #10448 and worked on in #10652.
