### ISSUE TITLE
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content

### ISSUE THREAD

**Issue by jaygshah** [conda/conda#10848]
## Current Behavior
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.9.0-py39.tar.bz2'.
  download saved to: /home/XXX/.conda/pkgs/torchaudio-0.9.0-py39.tar.bz2
  expected md5: 7224453f68125005e034cb6646f2f0a3
  actual md5: 6bbb8056603453427bbe4cca4b033361

ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchvision-0.10.0-py39_cu111.tar.bz2'.
  download saved to: /home/XXX/.conda/pkgs/torchvision-0.10.0-py39_cu111.tar.bz2
  expected md5: 78b4c927e54b06d7a6d18eec8b3f2d18
  actual md5: 69dd8411c573903db293535017742bd9

### Steps to Reproduce
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

from: https://pytorch.org/get-started/locally/

## Expected Behavior
Installed pytorch packages 

## Environment Information
active environment : XXX
    active env location : /home/XXX/.conda/envs/XXX
            shell level : 1
       user config file : /home/XXX/.condarc
 populated config files :
          conda version : 4.7.11
    conda-build version : 3.15.1
         python version : 3.7.2.final.0
       virtual packages : __cuda=11.4
       base environment : /packages/7x/anaconda3/5.3.0  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /packages/7x/anaconda3/5.3.0/pkgs
                          /home/XXX/.conda/pkgs
       envs directories : /home/XXX/.conda/envs
                          /packages/7x/anaconda3/5.3.0/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.25.1 CPython/3.7.2 Linux/3.10.0-1160.31.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1599893:1599893
             netrc file : None
           offline mode : False

**Comment by jezdez** [comment]
Hi @jaygshah, I would suggest to file an issue with the pytorch project since that seems to be something they can look into. This is the issue tracker for the Conda package manager, not for the pytorch Conda channel. Hope that helps!
