### ISSUE TITLE
upgrading openssl from version 1.0.1h-1 to 1.0.1j-5 gives empty libcrypto on Centos5

### ISSUE THREAD

**Issue by sstirlin** [conda/conda#1085]
Installing fresh in Centos5 using Miniconda-3.7.0.  Then ran

conda install conda-build

This updated openssl as well.  However, the file lib/libcrypto.so.1.0.0 is now zero bytes.  Now conda-build doesn't work.

Verified this twice (wiped away miniconda and started again).

**Comment by sstirlin** [comment]
Copying libcrypto.so.1.0.0 manually from pkgs/openssl-1.0.1j-5/lib to lib gives me a working system again.  Not sure what's special about libcrytpo (maybe some filename weirdness)

**Comment by ilanschnell** [comment]
The problem is the post install bash script which openssh-1.0.1j-5 uses.  We have been working on a more robust solution, which should be in place soon.

**Comment by asmeurer** [comment]
This should work now with the latest openssl.

**Comment by sstirlin** [comment]
Fix verified with version k.  Thanks
