### ISSUE TITLE
Conda environment is not shown in Powershell prompt

### ISSUE THREAD

**Issue by tanweihou** [conda/conda#10860]
Hi all, I am using Conda in Windows 10.
After updating conda to version 4.10.3, the conda environment is not shown in Powershell prompt.
Is there any way that I can fix this problem ?
Thanks.

## Current Behavior

```powershell
PS Username> conda activate abcd
PS Username> conda info -e
# conda environments:
#
base                     C:\Anaconda3
abcd                  *  C:\Anaconda3\envs\abcd

PS Username>
```

## Expected Behavior

```powershell
(base) PS Username> conda activate abcd
(abcd) PS Username> conda info -e
# conda environments:
#
base                     C:\Anaconda3
abcd                  *  C:\Anaconda3\envs\abcd

(abcd) PS Username>
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : abcd
    active env location : C:\Anaconda3\envs\abcd
            shell level : 2
       user config file : C:\Users\Username\.condarc
 populated config files : C:\Users\Username\condarc
          conda version : 4.10.3
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Anaconda3  (writable)
      conda av data dir : C:\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\Username\.conda\pkgs
                          C:\Users\Username\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\Username\.conda\envs
                          C:\Users\Username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.7.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Username\.condarc <==
ssl_verify: True
channels:
  - defaults
```

**Comment by LtDan33** [comment]
Hey @tanweihou , could you give some info as to what the solution was? It could help someone if they were seeing the same problem. Thanks!

**Comment by tanweihou** [comment]
Hi @LtDan33 , somehow conda script `profile.ps1` does not work well with user-defined Powershell prompt function. For my case, I used the environment variable `CONDA_PROMPT_MODIFIER` in my own prompt function to fix the problem, as shown in below. Thanks.

```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion

function prompt {
  $p = Split-Path -leaf -path (Get-Location)
  "$env:CONDA_PROMPT_MODIFIER$p> "
}
```

**Comment by yisen-cai** [comment]
> Hi @LtDan33 , somehow conda script `profile.ps1` does not work well with user-defined Powershell prompt function. For my case, I used the environment variable `CONDA_PROMPT_MODIFIER` in my own prompt function to fix the problem, as shown in below. Thanks.
> 
> ```powershell
> #region conda initialize
> # !! Contents within this block are managed by 'conda init' !!
> (& "C:\Anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
> #endregion
> 
> function prompt {
>   $p = Split-Path -leaf -path (Get-Location)
>   "$env:CONDA_PROMPT_MODIFIER$p> "
> }
> ```

Really useful~

**Comment by sohang3112** [comment]
> conda script `profile.ps1` does not work well with user-defined Powershell prompt function.

@tanweihou Have you considered creating an issue regarding this?
