### ISSUE TITLE
installing packages in an new environment break the python interpreter on MacOS

### ISSUE THREAD

**Issue by michelsanner** [conda/conda#10863]
I am using conda 4.10.3 on a macbook pro running Big Sur

I install miniconda, then install some python package in a new environment. After that
from _scproxy import _get_proxy_settings, _get_proxies fails

./Miniconda3-latest-MacOSX-x86_64.sh

conda config --add channels conda-forge
conda config --add channels anaconda
conda create --name pyside2 python=3.7 numpy pillow pyside2 biopython openbabel mmtf-python 
conda activate pyside2

(pyside2)  > python
>>> from _scproxy import _get_proxy_settings, _get_proxies
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/sanner/miniconda3/lib/python3.9/lib-dynload/_scproxy.cpython-39-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /usr/lib/libarchive.2.dylib
  Expected in: /Users/sanner/miniconda3/envs/pyside2/lib//libiconv.2.dylib
 in /usr/lib/libarchive.2.dylib

**Comment by chenghlee** [comment]
Can you please provide the output of `conda list --show-channel` so we can direct your question to the right team?
