### ISSUE TITLE
Conda package build fails on Linux systems

### ISSUE THREAD

**Issue by jheinen** [conda/conda#1087]
I run into the following problem on several Linux systems, e.g. CentOS 5 / 6 / 7, Fedora 20, Ubuntu 14.04, when I try to build a conda package for our GR framework (http://gr-framework.org).

    conda build --no-binstar-upload recipe
    BUILD START: gr
    Fetching package metadata: ...
    Solving package specifications: .
    The following NEW packages will be INSTALLED:

    openssl: 1.0.1j-4 
    python: 2.7.9-1 
    readline: 6.2-2 
    sqlite: 3.8.4.1-0
    system: 5.8-1 
    tk: 8.5.15-0 
    zlib: 1.2.8-0 

    Linking packages ...
    ERROR: placeholder '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an' too short in: openssl-1.0.1j-4

On Mac OS X 10.10, everything works fine. Anaconda is installed in /usr/local/anaconda on all of our systems.

**Comment by ilanschnell** [comment]
What is your install prefix?  What is the output from `conda info`?
The install prefix for openssl cannot be more than 128 characters, which should be plenty, given that the conda-build command uses a maximum of 80 characters.
Also, we fixed some remaining problems with the openssl install in version 1.0.1k.

**Comment by jheinen** [comment]
The install prefix is ``/usr/local/anaconda``. The output of ``conda info`` is:

    % conda info
    Current conda install:

                 platform : linux-64
            conda version : 3.7.4
      conda-build version : 1.7.0
           python version : 2.7.9.final.0
         requests version : 2.5.1
         root environment : /usr/local/anaconda  (writable)
      default environment : /usr/local/anaconda
         envs directories : /usr/local/anaconda/envs
            package cache : /usr/local/anaconda/pkgs
             channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                            http://repo.continuum.io/pkgs/pro/linux-64/
              config file : None
        is foreign system : False

After updating ``openssl``, the error was:

    conda build --no-binstar-upload recipe
    BUILD START: gr
    Fetching package metadata: ...
    Solving package specifications: .
    The following NEW packages will be INSTALLED:

        openssl:  1.0.1k-0
        python:   2.7.9-1
        readline: 6.2-2
        sqlite:   3.8.4.1-0
        system:   5.8-1
        tk:       8.5.15-0
        zlib:     1.2.8-0

    Linking packages ...
    Error: PREFIX too long: 144 characters, but only 128 allowed
    Error: post-link failed for: openssl-1.0.1k-0                             |  42%
    make: *** [conda] Error 1

BTW: There is also an open ticket (Id: 9154528) and a Anaonda issue (#241).

**Comment by ilanschnell** [comment]
Why is the build prefix 144 characters long?  Which is the directory you are building the package in?  Maybe you can add
```
echo "PREFIX: $PREFIX"
```
do the `build.sh` and show the output.

**Comment by jheinen** [comment]
Changing the home directory solved the problem:

    ln -s `pwd` /tmp/gr
    cd /tmp/gr
    export HOME=`pwd`
    conda build --no-binstar-upload recipe

**Comment by jheinen** [comment]
I added some debug output in the conda scripts which shows the problem:

    Linking packages ...
    link:  /usr/local/anaconda/envs/_build____________________________________________________________________________________________________ sqlite-3.8.4.1-0 /usr/local/anaconda/pkgs 1
    link:  /usr/local/anaconda/envs/_build____________________________________________________________________________________________________ zlib-1.2.8-0 /usr/local/anaconda/pkgs 1
    link:  /usr/local/anaconda/envs/_build____________________________________________________________________________________________________ openssl-1.0.1k-0 /usr/local/anaconda/pkgs 1
    Error: PREFIX too long: 131 characters, but only 128 allowed
    Error: post-link failed for: openssl-1.0.1k-0
    make: *** [conda] Error 1

**Comment by jheinen** [comment]
After updating ``conda-build`` to the latest version (1.10.0) everything works fine!

**Comment by psanghavi2410** [comment]
Hello, I have been facing a similar error as your openssl error. Even when I try to install condo-build, I get the same error. Could you kindly elaborate, how did you solve the error.

Thank you

**Comment by jheinen** [comment]
.. I  updated all packages (``conda update --all``) - this fixed the problem.

**Comment by psanghavi2410** [comment]
When I try doing conda update --all. I get the following error.


Linking packages ...
/home/pi/miniconda/bin/.openssl-post-link.sh: line 7: /home/pi/miniconda/bin/.openssl-libcrypto-fix: cannot execute binary file
Error: post-link failed for: openssl-1.0.1k-1####################                                                                                                 |  30%

I downloaded Miniconda from http://continuum.io/blog/raspberry on to my raspberry pi 2. I believe the that different ARM architecture is causing the error: Cannot execute binary file.

Is there a way I can make my Raspberry-2 to support these packages. I would really appreciate the help.

**Comment by brentp** [comment]
I'm having the same issue, my conda env has long paths:

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.0+73.g1dde5b8
       python version : 2.7.11.final.0
     requests version : 2.3.0
     root environment : /uufs/chpc.utah.edu/common/home/u6000771/Projects/gemini_install/data/anaconda  (writable)
  default environment : /uufs/chpc.utah.edu/common/home/u6000771/Projects/gemini_install/data/anaconda
     envs directories : /uufs/chpc.utah.edu/common/home/u6000771/Projects/gemini_install/data/anaconda/envs
        package cache : /uufs/chpc.utah.edu/common/home/u6000771/Projects/gemini_install/data/anaconda/pkgs
```
and the error is:
```

Linking packages ...
ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: gcc-4.8.5-3
```

**Comment by msarahan** [comment]
I'm not super familiar with this, but I imagine we can make the prefix placeholder as long as we want (within reason).  I think the maximum path length is 4096 characters (http://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs) - so maybe we want to get closer to that?

**Comment by brentp** [comment]
seems like there might also be a logic error, e.g. see: https://github.com/conda/conda-build/blob/master/conda_build/config.py#L60
I assume that means to take the longer string?

**Comment by brentp** [comment]
I see that max works as expected...
So is to get around this for now other than to figure out how to shorten my path?

**Comment by msarahan** [comment]
None that I know of.  =(  I'm OK to merge changes to conda-build on this, though.  Seems to me like 1000 characters is huge enough to cover us, but I'd be OK to go out to maybe 3K - don't want to cut it too close.
