### ISSUE TITLE
include statement in condarc and ~/.conda/condarc.d ignored

### ISSUE THREAD

**Issue by skwde** [conda/conda#10874]
It would be helpful to be able to outsource machine dependent parts of `.condarc` to e.g. `local.condarc`.
This makes it easier to maintain the configuration across different machines with e.g different `envs_dirs` and `pkgs_dirs`.

To do this, some kind of `Include` need to be introduced in the `.condarc`.

I tried to realize this using multiple files in `~/.conda/condarc.d/` but it seems this direcotry is completely ignored because even when placing a `.condarc` the changes are not reflected in `conda info`.

**Comment by jezdez** [comment]
Conda uses a YAML syntax for the .condarc file, which is pretty hard to extend generally speaking.

Could you please check if https://conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html would be along the lines of what you're looking for?

**Comment by skwde** [comment]
Unfortunately, this doesn't solve my issue. 

An extension of the YAML syntax is not necessarily needed (from my point of view) if <https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc> works as expected. Especially if really all locations are searched for config files, according to the stated `SEARCH_PATH`, which are then parsed in the specified order while the described merging and precedence is respected.

For example, I tried several combinations using the `condarc` locations / files such as `~/.condarc` or `~/.conda/condarc` for base setup (machine independent) and then the directory `~/.conda/condarc.d/` for specific setup using various files e.g. `envs_dir.condarc` which is then machine specific.

Though the files in `~/.conda/condarc.d/` seem to be ignored completely?!

Besides that I am wondering if there is a `conda` command to see from which config which settings is originating?

**Comment by qris** [comment]
> I am wondering if there is a conda command to see from which config which settings is originating?

Does this help?

```
conda config --show-sources
```

https://docs.conda.io/projects/conda/en/latest/commands/config.html#Config%20Subcommands

**Comment by skwde** [comment]
@qris, thanks for pointing that out. This command is indeed helpful.

As a matter of fact, independent of this thread, I learnt about it a while ago related to some other troubleshooting I was doing.
