### ISSUE TITLE
progress bar not update until download is complete when install package from nvidia channel

### ISSUE THREAD

**Issue by function2-llx** [conda/conda#10884]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I'm trying to download [the cudatoolkit package from nvidia channel](https://anaconda.org/nvidia/cudatoolkit/) with conda, i.e. by execute the following command in my shell:

```shell
conda install cudatoolkit -c nvidia
```

After start downloading, however, the progress bar stays at zero for a long time. But it should not be the network connection issue because I can download [the package tarball](https://anaconda.org/nvidia/cudatoolkit/11.4.1/download/linux-64/cudatoolkit-11.4.1-h8ab8bb3_9.tar.bz2) with wget successfully without any issue.  More importantly, by inspecting the size of cache file under `~/miniconda3/pkgs`, I find the package is actually being downloaded, though the progress bar does not move at all. 

In the screenshot there are two terminals, the one on the left is which executes the `conda install` command, and I use the one on the right continually inspect the size of package tarball, and find it keep increasing.
![image](https://user-images.githubusercontent.com/38486514/131245109-77438e33-7788-4b8f-9a2d-c8ce2a462f30.png)

The progress bar does not update until the download of the package is complete, move to 100% instantly, the package is installed properly at last nevertheless.
![image](https://user-images.githubusercontent.com/38486514/131245261-bcba31a4-895b-474a-982f-84c92faacbba.png)

This issue does not occur for other channel, e.g. if I try download this package from the pytorch channel instead of the nvidia channel, the progress bar works properly.
![image](https://user-images.githubusercontent.com/38486514/131245370-a30dee74-3e88-4ddb-a8c3-7af45b24efcd.png)

### Conda info

```shell
active environment : base
    active env location : /home/function2/miniconda3
            shell level : 1
       user config file : /home/function2/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/function2/miniconda3  (writable)
      conda av data dir : /home/function2/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/function2/miniconda3/pkgs
                          /home/function2/.conda/pkgs
       envs directories : /home/function2/miniconda3/envs
                          /home/function2/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.11 Linux/5.11.0-27-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda config

```shell
# output nothing
```

### Conda list

```shell
# packages in environment at /home/function2/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
certifi                   2021.5.30        py39h06a4308_0    defaults
cudatoolkit               11.3.1               ha36c431_9    nvidia
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.2.4           py37h06a4308_0    defaults
python                    3.9.6                h12debd9_1    defaults
readline                  8.1                  h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tzdata                    2021a                h5d7bf9c_0    defaults
wheel                     0.37.0             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

### Additional Context

Though the network connection seems not to be the direct cause, my machine is in mainland China and the issue could have been caused by GFW, though I've tried using proxy bypassing the GFW the issue still exists. I'm not able to do further test with machine outside mainland China.

**Comment by jezdez** [comment]
Huh, interesting, I was able to reproduce this on Ubuntu, but not on macOS. Don't think this had anything to do with GFW!

**Comment by Zian** [comment]
I was able to reproduce the problem with cudatoolkit-11.1.1 and conda 4.14.0 on Windows 10.

My ISP provides Internet service through a wire to my residence in the continental United States.
