### ISSUE TITLE
R-devel installation

### ISSUE THREAD

**Issue by ZheFrench** [conda/conda#10903]
Coul be great to install r-devel with conda as r-base.
For now, we can only install R specifying a release version.

`conda install -c conda-forge r-base=4.1.1
`

**Comment by jezdez** [comment]
Hey @ZheFrench, this is better suited as a ticket in the [r-base-feedstock](https://github.com/conda-forge/r-base-feedstock) repo I think. Could you recreate it there, please? Thanks for your help!
