### ISSUE TITLE
conda build (python2) fails to build package for python3

### ISSUE THREAD

**Issue by gabrielelanaro** [conda/conda#1091]
I have installed miniconda for python 2 in my system, and I created a python=3 environment to build a package.

That's the output of conda info.

    Current conda install:
    
                 platform : linux-64
            conda version : 3.7.4
      conda-build version : 1.9.1
           python version : 2.7.9.final.0
         requests version : 2.5.1
         root environment : /home/gabriele/miniconda  (writable)
      default environment : /home/gabriele/miniconda/envs/test_install
         envs directories : /home/gabriele/miniconda/envs
            package cache : /home/gabriele/miniconda/pkgs
             channel URLs : http://conda.binstar.org/gabrielelanaro/linux-64/
                            http://repo.continuum.io/pkgs/free/linux-64/
                            http://repo.continuum.io/pkgs/pro/linux-64/
              config file : /home/gabriele/.condarc
        is foreign system : False

When I run conda-build, however, I obtain this error.

    $ conda build --python 3.4 conda-recipe/

      File "/home/gabriele/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 225, in     get_contents
        loaders = [jinja2.PackageLoader('conda_build'),
      File "/home/gabriele/miniconda/lib/python2.7/site-packages/jinja2/loaders.py", line 212, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
    ImportError: No module named pkg_resources
(test_install)gabriele@gabriele-Lenovo-IdeaPad-Y500:~/workspace/chemview$ conda info

Is that supposed to happen? Can I build packages for python3 having installed conda for python2?

**Comment by gabrielelanaro** [comment]
I believe there's another distribute/setuptools issue

**Comment by asmeurer** [comment]
`conda install setuptools` should fix this.
