### ISSUE TITLE
Standard mechanism for adding custom metadata to an environment.yml file

### ISSUE THREAD

**Issue by aronchick** [conda/conda#10916]
Hi--

I'm looking to capture additional information about a user's environment and would prefer not to create a new file format to track. Given how widely used conda is, and the environment.yml file, I was hoping there'd be a standard way of extending the file without causing any issue to anyone not using these tools. Items that I am interested in tracking:
- SHA of a given commit
- Driver version the environment ran in (e.g. CUDA)
- System information (e.g.Ubuntu 20.04 LTS)
- Etc.

I thought I saw there was a standard technique, but it appears to conflict. Specifically, if I use "extras" (which is the standard for conda build), I get this warning:

```
EnvironmentSectionNotValid: The following section on '/private/tmp/s/environment.yml' is invalid and will be ignored:
 - extras
```

I get that conda just ignores it and moves on, but would prefer not to scare other people I pass this env to.

I'm guessing the answer is 'no' since, it doesn't appear that there's any extensible VALID_KEYS -`VALID_KEYS = ('name', 'dependencies', 'prefix', 'channels', 'variables').` - https://github.com/conda/conda/blob/ed96a06244eb820781dc872eb381f51b95ee48ae/conda_env/env.py#L31

**Comment by jamesp** [comment]
I think this would be a great addition to the environment.yml spec.  It would be good to know there was a key that was guaranteed to not conflict with future conda features.  Another great use case for this would be recording DOI numbers for referencing specific environments from academic papers, or including a changelog that exists within the fie.

As a concrete proposal, could we propose adding an additional top-level key to the conda environment spec that that is reserved for users to add their own valid yaml beneath?  `extras` is good, I have been using `meta` in my work. `about` would be similar to the format used in conda-build `meta.yaml`.  I'm agnostic to the key name, but it would be good to know it was reserved for user extensions.
