### ISSUE TITLE
[Question] What data is in the third column of `conda list`

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1092]
I've looked over the documentation and I can't figure out what the third column returned by `conda list` is:

```bash
conda list
...
svgwrite                  1.1.6                     <pip>
sympy                     0.7.5                    py27_0  
...
```

Presumably the entries with `<pip>` were installed via pip and not conda, but it isn't clear to me what `py27_0` means in the above example.

Is this information documented somewhere? If not, could you add it to `conda list -h`?

**Comment by asmeurer** [comment]
This is the build string. The build string could be anything, but by convention, it tells you what Python version the package is built against, and what the build number of the package is (the build number lets you rebuild the same version of a package and have conda view it as a newer version).

**Comment by goretkin** [comment]
Is `<pip>` displayed when a package ends up in `site-packages` without being installed by conda? I installed a package through its `setup.py`, not pip, and it is showing the build string `<pip>`.

**Comment by asmeurer** [comment]
Yes, the two would be seen by conda the same way. `<pip>` is essentially packages coming from `pip list `.

**Comment by jpeacock29** [comment]
Why was this closed? This information still does not appear in the docs, afaik!
