### ISSUE TITLE
ubuntu20.04 __conda_exe:2: No such file or directory: /home/anaconda3\Scripts\conda.exe.

### ISSUE THREAD

**Issue by elvisjade** [conda/conda#10927]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

My system is ubuntu 20.04, I want to update spyder, so I first executed the command to update anaconda
conda update anaconda

But after the update, I can't open the conda environment, and I can't execute any related commands.

It will report:
__conda_exe:2: No such file or directory: /home/jade/anaconda3\Scripts\conda.exe.

My environment variables were set correctly before, and I have reset them to make sure they are correct, but I still can't execute any conda commands, the conda directory and related files are still in the same place.

### Conda info

```shell
Cannot execute this command
```

### Conda config

```shell
Cannot execute this command
```

### Conda list

```shell
Cannot execute this command
```

**Comment by cypypccpy** [comment]
i got the same bug too:(

**Comment by chenghlee** [comment]
Is this in WSL, or a native Ubuntu install? Asking because you seem to have picked up the Windows conda executables for some reason.

**Comment by elvisjade** [comment]
> Is this in WSL, or a native Ubuntu install? Asking because you seem to have picked up the Windows conda executables for some reason.

This is in a native Ubuntu install. My code is conda update anaconda. I don't know why I have picked up the Windows conda .
