### ISSUE TITLE
Separate (optional) cache layers

### ISSUE THREAD

**Issue by FFY00** [conda/conda#10930]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Cache mechanisms should be standalone, instead of being glued to components.

### Why is this needed

Currently, we have cache baked into the components directly. This is not optimal as it hijacks data creation, and does not let us handle data directly without it being mangled by the cache system, which is a global of the program.
Among other things, this makes it harder to write tests, and makes the code much less modular.

### What should happen?

For every cache system we have, we should have a separate cache object, which we would use when constructing/fetching the data.

### Additional Context

Cache mechanism for `SubdirData`:
https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/conda/core/subdir_data.py#L82-L100

**Comment by dholth** [comment]
This is pretty confusing. It's not http caching; it's the fully constructed classes keeping copies of themselves in `<class>._cache_ = {}`  and then using metaclasses to construct `Class(argument) -> cached preexisting instance`.

I wonder how often we require `is` equality or if the system would work fine even if caching was disabled.
