### ISSUE TITLE
no_proxy environment variable support

### ISSUE THREAD

**Issue by rvianello** [conda/conda#1094]
I'm experiencing issues while trying to use the default conda channels from behind a proxy, together with a custom channel, located on the intranet. From what I'm seeing, conda correctly recognizes the http_proxy/https_proxy environment variables, but it is not affected by the no_proxy environment variable settings. Apparently conda suffers from an issue very similar to what I found described here: https://bitbucket.org/hpk42/devpi/issue/88/no_proxy-environment-variable-support

**Comment by asmeurer** [comment]
How does `NO_PROXY` work?

**Comment by rvianello** [comment]
The no_proxy environment variable allows specifying a list of hostnames and domains that should be excluded from proxying.. I'm not sure I can find any authoritative source of information about this, but it's described for example here https://wiki.archlinux.org/index.php/proxy_settings#Environment_variables

In a quick test I ran, if proxies are associated to the requests Session object they will be used on every following Request, making the no_proxy environment settings ineffective, and the local channel unavailable. Instead, if proxies are not set the requests library will selectively route each request through the configured proxies based on the url. I only did a brief investigation, but it looks like one could only set the Session's proxies when explicitly specified in the conda config file, and otherwise delegate to the requests library how to best make use of the environment configuration.

**Comment by asmeurer** [comment]
Your fix looks like it will probably work, although I might want to have some people test it out to make sure.

**Comment by rvianello** [comment]
of course, the intent for that patch was mainly illustrative. please let me know if I can help with testing.

**Comment by aldanor** [comment]
I'm interested in this as well. Most tools respect `NO_PROXY` whereas `conda` doesn't.

@asmeurer doesn't conda use `requests` whenever possible? Asking because `requests` does handle `NO_PROXY` properly -- so you wouldn't have to do anything if you just use their standard API without major hacks?

**Comment by asmeurer** [comment]
The patch listed above ought to fix this. @aldanor are you able to test it?

**Comment by kalefranz** [comment]
Conda let's requests handle the NO_PROXY environment variable.
