### ISSUE TITLE
error updating spyder-app

### ISSUE THREAD

**Issue by jonathanmorgan** [conda/conda#1095]
Hi,

I am using this:

Version: 1.0.0 (node-webkit 0.10.1)

Conda Version: 3.7.3

Root Prefix: /Users/jonathanmorgan/anaconda

Default Prefix: /Users/jonathanmorgan/anaconda

Python Version: 2.7.8.final.0

Platform: osx-64

I was trying to install an update to spyder through the launcher and I got an unknown error, with stack trace that follows.  Figured I'd submit it as the window suggested.

Thanks,

Jonathan Morgan

Traceback (most recent call last):
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    try:
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 397, in install
    common.error_and_exit("Cannot continue operation while processes "
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
    plan = plan_from_actions(actions)
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
    link(prefix, arg, index=index)
  File "/Users/jonathanmorgan/anaconda/lib/python2.7/site-packages/conda/install.py", line 577, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Users/jonathanmorgan/anaconda/conda-meta/conda-3.7.3-py27_0.json'

**Comment by fnurl** [comment]
I also got an error. Running Python 3 though.

**conda info**

    Current conda install:
    
                 platform : osx-64
            conda version : 3.8.0
      conda-build version : 1.8.2
           python version : 3.4.2.final.0
         requests version : 2.5.1
         root environment : /Users/userdir/anaconda  (writable)
      default environment : /Users/userdir/anaconda
         envs directories : /Users/userdir/anaconda/envs
            package cache : /Users/userdir/anaconda/pkgs
             channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                            http://repo.continuum.io/pkgs/pro/osx-64/
              config file : None
        is foreign system : False

**error log**

    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:
    
        https://github.com/conda/conda/issues
    
    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
        args.func(args, p)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 40, in execute
        install.install(args, parser, 'update')
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 411, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/plan.py", line 499, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
        cmd(state, arg)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
        link(state['prefix'], arg, index=state['index'])
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
        install.link(pkgs_dir, prefix, dist, lt, index=index)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/install.py", line 575, in link
        create_meta(prefix, dist, info_dir, meta_dict)
      File "/Users/userdir/anaconda/lib/python3.4/site-packages/conda/install.py", line 291, in create_meta
        json.dump(meta, fo, indent=2, sort_keys=True)
      File "/Users/userdir/anaconda/lib/python3.4/json/__init__.py", line 178, in dump
        for chunk in iterable:
      File "/Users/userdir/anaconda/lib/python3.4/json/encoder.py", line 422, in _iterencode
        yield from _iterencode_dict(o, _current_indent_level)
      File "/Users/userdir/anaconda/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
        yield from chunks
      File "/Users/userdir/anaconda/lib/python3.4/json/encoder.py", line 429, in _iterencode
        o = _default(o)
      File "/Users/userdir/anaconda/lib/python3.4/json/encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: b'iVBORw0KGgoAAAANSUhEUgAAADcAAAA3CAYAAACo29JGAAAABHNCSVQICAgIfAhkiAAAFxhJREFUaIHFent0ldWZ9+95r+dGQhISEgjhlohyEwwoEOAA4+UbBC840PmmFSu2+lmqjNV2TcXVaG2dzupURxxlBIV2bCkFwarF6hc1JBEQIQWpiRMSLoHczsk5OSfnft7Lfr4/ck5MEblYZ75nrXdlZe99nv389rOf6/sCXyExs97a2jrx1KlTw/8KHgQAfr9/Rl9fX1lmTPqqZPwyAikAEAwG1xmG0e73+9dmxuXL5EPMLHd2dhb4/f72QCDQ6vf7r86MXzbAr/pEPKqqljHz5Ky8l/PjnTt3SkRkq6r6w/z8/DIAKafT2UlETETiK5b10iiroWAwuCKVSll+v//1y+VRXV0tZXhcFwqFYtFoNBUIBJYAQG1trfLVSnwZlL0yoVBoQSwW40Ag8DEz68ysXMpz+PBhtampSWNmraen5z3TNNnn872U4a3+fwOWEYCYmbq6ukYEg0E7EAj0MV/WjQQABIPBNYZhcG9v75m+vr4x1dXVUlajX4a+KnXLRGR1dXXNB8DM7PH7/f/e09MTFkKQJEkCgOABxAxAKIoibNtmIQQriiIkSSIhxHeFEBYz/0t+fv7ZHTt2yKtWrbK/rFD016JiZoWILL/f/3cOh+O3hmEAgORyuSRZlsHMICJcSJPMDMMwIISAYRhnE4nEFadPn7YWLVpkE9HlX4EM/VXgmFkiItHX1zeNmesURRlmWRYJIeRgMGjFYjGW5YFoIEkDt4uIBh9JkkBE0HUdubm5EEJA13WRTCb/aeTIkf+WPbj/cXCZYCt1dXUNV1V1r8vlmurz+Sy/369Mnz6dn3vuOXrttdfg8XhgWdYguMxvBwELIbB+/Xpce+21iEajIicnBwBShmEsGzFiRG1tba2yePHiLwXwSxtrY2OjAkA4HI4XnE7nVCGE8fLLLyuHDh1il8tFLpdrEMC5xMxQFAWJRAILFizAvHnz4PP5+JlnnpE6OjpsWZYdQohfJZPJssWLF9vZrOV/BBwzK7NmzTIDgcBjqqquIqL0rl27tD179jAAYmZ4PB4I8fm4K4SALMswDAOFhYVYsWIFiAh79uyhd955h7ds2aLGYjHb6XSOiUajW5lZzxzkfz+4rB0Eg8EViqJUS5JkNDQ0aNu2bYOu6xQKhUBE8Hg8f+FMmBlCiMEx0zSxdOlSTJ48GUePHsUf//hHlJSUUENDA//mN79RAaRdLteSYDD401mzZplNTU3afys4ZpaJyAqFQtOZeZOiKDh58qTywgsvkBADnj4ejwMAXC4XiAi2bQ86EFmW4XA4kE6nUVFRgZtvvhmxWAy7du1CJBKBEAJut5t2797NNTU1mizLKUmSvhcIBO6cMmWKcbm56uVqjsPhcJ5pmr9SVbUgHA7zs88+K/n9flZVlWzbhi0EGICm63C73dA0DZIkwbZtpNNpxGIxCCGwcuVKjBo1CvX19Th48CDcbjcsywIzQ5ZlbN68mT755BNN0zRLCPF8OBy+hojs8yXQzCy1trbq585J5yyi7DN0vLq6WmJmDQCn0+kX3W73DADG1q1blU8//ZRzc3OJAegOByAEhGWBmNEfiSAYCkEIAY/Hg9LSUkyePBl33XUX5syZg/b2drz66quD+xARhBBQFIX6+/v5ueeek4KhEDtcLo8NbO1iLhgqZ21trZIxE1FRUZE+N7n+C0O9UMAkIqO3t/dHLpdrpRAivX37dv31119nt9tN/ZEIdElCLBhEMpmEYdsYnpeH22++GSUlJRgxahRKR4/GmDFjUFBQgFQqBVmWcfDgQZw6dQpOpxO2bQ8CtCwLLpeL/qulhbds3Kh+/+GHDackTefu7o2Pl5SsWrVzpzZl1SoDgAUAgUBgkhDiNiIqjUQij02cOLEfAA1qqLq6WnrggQfcQgguLCy0T58+zYlEQuTk5MiWZXFubu4tQohtmqbZR44e1Z55+mnWdZ1yhw9HvseDgvHj4cnLw8SCAlwzaRJsVYWjpAQ5kgQ2DAQiEUQjEfT19aG3txfTpk2Doih49NFH0dLSAqfTORAPicBEYCHgkGX0GAbfuWYNffPuuw1dCM3o7l5fUFr6VDQaLbRte75hGHcpijI3Ly+vCAD8fn/VyJEj9zOzQkOyjDLbtncQkYOZkwBsAGlmliRJkgHMkiTJIYRAOBwmTdcxPDcXMgDL6QT274f0hz9ANDXBbGuDKC4GTZqEpvJyvGtZCHd0oLOnB6FwGMlEAo888ghuu+02vPHGG3j66aeh6zqEbYMBSEQQACxJwoxgEFMSCV6+fDkPu+02NmfMMCge3w5NW5ibkzNRURQEAgFBRLsBvKtp2qs5OTlBYCAmyURkBwKBK5n5IBHlSJIEWZYhSdKg606lUiyEIMuyQJLEpmmSEY8jkE5j9PbtcG7YAE4kQABkACJj0P0AdhUWYucVV8AhSdB0HSnDwPhx4/DUU09BVVU8/vjjOHr0KJxOJ1gI2ERwWxbuPX4cC30+5AKIAhDDhkG88grn3XorRYNBWMAxWZJeMQzj7eLi4k/ONSWFiGwACIVCp3JzcxcKIdymaaqqqioA3ADiQoilBQUFD508eTL9wsaNWldnJwnDQFc8jq+3tODK9nbYAMjphJRMDhqz6XAg37bxUDCI4rNn8WJ5OUzDgKYoaG1rQ01NDVavXo2lS5eiqakJiqIgmUzCwYxHjx3DdZEIwgACRNA8HqZolJXnn6fQzTe3yP39D38yYcLbizPy79ixQ545c6ZSXl5uZH3HoEOpqKhIA/j4fM4kFAqZkUhk3fDhw6VkMolTra1QCgrw9ZYW3HXmDFKyDDBDTSZhjBkDTJmC8NGjKOjpQRpAAsCKM2dg2zY2XXEFlIxWa2pqsGDBAlRVVaHm3Xexb+9eFFZU4O4jRzArEkFQkqALAWIGJZMQREauLOu9kcjrhRMn7skWuxlHZGVMaZDODQUSM8vMLNfW1iqZ6lh2OBztsVisIz8/Xx0/erSdcjiw5vRprD5zBnEAwrahC4E3JkzAid/9Dtq2bfjXO+7AptJSuDPXNApgZWcn7m9pQVIIuF0unGhrw966OuTk5uLWW27BPWvX4tl778VNoRCiAPRMgs0AWJKImGGPGUO9+fkfM7PSlqkjv6hyODcUfC4ZZGbJ4XCcUWT5JElSWenUqfa9mzYp/zsDjAF4APznqFHYOWUKtowejUQqhd6eHhwsL4eq67jnxAkkAUSJcEdXFwQRNk+aBJfDgTd//3vMX7gQlVOn4trFi5F+9VWYfX1QAQhmEDDgPS1LSKqqh+64I+IAmonI4ouU+xfNUNra2lQiYpnoz+lUiha//z6tPnOGU5k6zQ3gt2PH4uXycozyeDDM7UYskUA0kUA+M7aNG4fN48fDk9ksCuDvOjtx3/HjiDNjREkJHEQwVRX9wSDir7wCCYAtSbCJYBFBliQoQljaz39O8qJFbZ5XXmllZsr6iy8N7v3ychsAUsXFHyXfeIOdGzbIKVUlW4gBYKWl2FJRAadlIW/ECCi6jp7ubkQiESRtGwVE2Flejk3jxsGROegYgNs7OvBoRwf+8c47UTB6NPpPnID+ne8g5803ASJIAJzMcDMjKsvcV10t9HXr2A6FjhevXh0HcNHG0UVLia4Brw5HR8dBe948i+6+W1G3bmUNoG2lpXi5ogI5zOi3LEyZNg22ZaG4uBh//7WvoXbvXnR2dsKtqvjdlVdCyDLuO3ECaVVFQgj8r9Onkbr9dhjDhyPX54McjcJWFEi2DUMINJSUoFnX0VZRQY+tXSsn+/uJFeUgADQ2Nl60/XDJRSDv2CH3Xn/9f8maVp5avdr6Q0ODsnXGDOTaNvrjcfzNDTfgwe9+F5quQ1EU6LqOEydOoKamBnvr6+E7cwaG242VJ09iTXs7GEAaA85GxoDtSroOTqcxTFWxs6oKG4ggCYEZ06bxv/zoRzAAVmR5bkFBwUfZ5ONCMl9SVcDMRCtX2lY8/mGu04kTDz3EWyZMQK4sIxyLYc68efg/992HYTk52L17N6qrq3Ho0CEUl5Rg7dq1+MmTT+LOe+5BqduNjxYtQuCxx6AXFqIQQCGAYQDyALjTaaTcbqReeAEzXnoJkwoLQbEYZl51lVBcLgKzPz8//8/A+Z3fuXSpFa4CIhM9PR/JkvT1vJwce2xZmdLe3k7z5s/HugcfRH5+Pt5880388pe/hGVZOHLkCK677jpcf/31uPbaa3HPmjVYsmQJkpEIxlxzDT695hp88PDDGJNMIjeVQkjXcdbtRuPYsbh72jR4R43CPfffjx8++iiPmzhROB0OORqJHCKi5CXKfHl9S1WWj0UiER5ZUiLn5uXhmsJCfP+RR5Cbm4uamhq8+OKLg1fStm3U1tbi0KFDuPrqq7Fs2TJMnToVRUVFaPvTn/DzXbvw6fjxcMoyXIaBqKIAigIlFsPLTz+Nsp/+FNfOno2HHnyQikeOtGVZVgDsBz7rBlxM3kstVm0AsCyrPZlMdrtcLnXFihVi3YMPoqCgAG+99RaeffbZwZ6JaZpgZgwbNgxCCBw4cABPPPEE9u3bB4/bjT+++y5am5owhgieVApEhDzTxPB4HMOcTpw8cwabN21CKpXC3y5dyqWlpZRKpUhV1WMZeS7JV1wSOCIStbW1SnFx8RlFUT7WNA1z58yxysrK+K233sLzzz8/mGALIQY7XoZhDIIEBppDQgikkkloDgdSkgRDksAADFmGoapIGwY8bjf279+PX//612yappAkSY9EIj5Zlv/MzMrjjz9+SV3oS3Uo6qJFi0RHR4dORE7TNNNCCNqzZw89+eSTAABFUYauH2y6ZkFKkgSXywXTNJFOpwfWZB4mAoSADEBV1WwziXfv3k0tLS2yqqqGLMs6M88iImvVqlWXZE4XBcfMGhGZ8Xi80Ol07nQ4HIuFELoQQh07dqyxZs0a5OTkIBaLwTRNaJr2Fx2vLGVt0TRNpDJXcXCeGZqmgZk5kUjAtm3MmTOH1q9fb48bNy7NzJrT6Rwuy/LmQCBwy5QpU4xL6YZ94QlkO01EZPh8vnmJROLfCwsLZ/b29nbKsnwYwNLZs2drV111lX3DDTeIt99+W6mvr6ezZ8/C4XBAVdXBVl626eNwOAYbRRneUBQFzIxwOMy5ubk0e/ZsLF261Jo2bRp7PB5VVVU5HA4fSafTHTk5Ocvj8fjv/H7/94qKijZeLNZ9Ibhs3tbb27uOiH48fPjwnHA4fBTANwsKCj4OBAJLenp67iGir40dO1b91re+hRtvvDFdW1ur19TUoLu7G4qiwOl0Dl5Lh8MB0zRhGMYg0EQiAY/Hg6VLl9KSJUvMmTNnQtM01TRNhEKhT4hos6ZpvyosLEwEAoHnHA7HfaZpvuDz+QoBPMUDSeblvSzp7u4e6/f7tyUSCY5GoxwIBH7V2dlZAACtra16dl1/f/8sn8+33efzxSzL4lgsZre2thobN260V65cyXPmzOG5c+eKFStWcFNTE3d2dvI3vvENnjlzJi9btoyfeOIJ8dFHH5nhcDgthOBgMMjd3d1HgsHg3cycc+5N8vl8j4VCIYOZORgMPg5cxpvXTE1HgUBgX4ZBbyAQuD87n2V0+PBhdWifMBKJzPX5fFu7u7vTqVSK4/E4t7a2pl566SWxYsUKvummm/j48ePc3t4uvv3tb/NTTz3FR44cSUWjUTuVSnE4HGa/318bCAS+MbT5OvQgs3v7/f67ksnkhz6fb9pQ4BelLAOfz/cP/f39dT6fb3qWwfleSGTGBzP0eDx+dW9v71a/3x9Jp9OcTCbF8ePHje3bt4u2tjb2+Xzc3NxsxmIx07Zt9vv9ls/nqw0EAsuZWQcG+6TK+fbLynfw4MGcc+cul6QMgIuWF9kG6RCQM/x+/4tdXV0x0zQ5EolwIBAQgUBApFIp7unp4Z6ent+HQqFlQ/lkmr8XpKymvsznG1kGEjPTjh07LvdbEnmoDcRisSnBYPB5n88XCQQCdjAYtPx+/2t9fX3zs2s2bNigP/DAAzm4nCrlS7xzvxBdaOPzXVcaqvG+vr65wWDQCAQC/lgsVgQA1dXVnsOHD6tVVVXLvV7v/vPwkS9336F0KWqlyspKFZ99MJNlKFVWVqper1fJzGXXDSwiUojIzLygkFtbW88ahpEGgHA4rFVXV3uam5uNWbNmmZqm5QGYMGQPKcPXBsBD+QKQM3PSkPV/HU2fPt1dWlrqPN+c1+sdgYFTBs7zciXzd2RfX1/Y5/P1JRKJ0QCwZMmSkaWlpc4FCxbc5PV6j5/7+7lz546tqqoalvn3c1qaPn26+0IyX0zlXFlZWeLxeJ4BUCLLsm5Z1qb6+votCxcuXE9E4wFIRDSTiCzbtv+jvr7+5cmTJxcXFRVtTKfTPz5w4MARZkZlZeXaH/zgB79Yvnx55L333lv8s5/97Juapi2xbbtJluUKZqZYLLagsbHRnD179hUul2sDABeAHAC/qaur+/mMGTMKc3Nzf2Hb9gFZlm+TJGmkbdu319fXn8rKOxTAFwa/yZMnq83NzYbb7X4aQL+iKGsNw5hkmmYUAIjoKiK61TCMG2VZ7gDwdVmWNy9cuPAsEb0PYJamaXcBOAIAkiStFkLoLpcrun379v+QZdkly/Kdtm2HANwLYHljY6NdWVnpcrlcLwN4o7Ozc0NxcfEsRVG2L1y48IN4PH5YkqR/ADCDmX9i2zaEEOEvwnApkT1NRLNM0xzV0NCwPzvIzKeZ+Z39+/cfwMCV/JnX611KRN+tq6v7v16v9wcAfgHgH6dNm3bl+PHjRy5evLi/vb19Qnd391iXy3X1O++80wwACxYsqJUk6Q4AwuVyLSei0lQq9VpRUdE1AHqZOS5J0u2NjY0HvF5vp23bP/7ggw9ePUfOz9nfF4Jrbm42ACAejz/i8Xi2KIry/qJFi46kUqnvfPjhh22Z3HNEeXm5npeX50mn0ykAp5h5ZIZFDTMnlixZMi+VSl3NzB8VFxfHa2tr/yaRSCTz8vJi5eXluqZpjIE2CgOALMvjmHm4pmnVAJxEFCGiZiHEhxm+MVmWUVlZqSaTSb25uTnbG/4cXVRzjY2NAQC3VFVVXa1p2k90Xf83AMsAmMxstbW1padPn64cO3Ys7vV6xxBRGwDU1dUFvF7vbsuy7lcUJdjf3/8iEb1XVlZWWV5efqCjo8Nua2tLZzTXnc3uhRAhSZJCdXV1d36BSEnbttHY2GhWVlbii4BdDBwB4KqqqjJN09QRI0Z8kvnU8AEAYGZDkqT8+fPnF/b09EQWLlyYtYWHswxM03xRVdU/EdEmv9/fsGPHDm3v3r0tTU1NZ5xO57Nz5sz5tiRJCjNfz8w55eXlus/n+21JSckPvV7vHwzDWJtMJhM5OTmeZDIZOXToUJCIiohIAYCioqILhrILgZMA2LIsP8HMU/x+fy+AfCHE9zLgBBGNk2X5n0eNGjWSiMoAfKe+vv5I5mDk/fv3n/R6ve3MfKK5udlYt26dq7u7O1ZVVfX3mqZt1HX9AwBtGOiyN8qyrLW0tESLiopulWX5XzVNq9E0LQBA1jTtnwDUAjhh23YfALS3t18wzl0I3EAbPZVa53Q6i5hZjcfjbY2NjSYAZN6yNqdSqfW6rk+wLOuTffv2RfFZeLEyh9Bu23YtAHR3dycBYN++fYfLy8vnl5SUTAIQamhoOFtZWZnb0tISBUANDQ3HANw4b968iaqqOgGE9+3b1wEAlmWtCIfDceAzv/CV0eTJkz0A4PV6f+L1ehuHzmUyBwCQq6qqyrxe7/Ner/f1c+aAzwI+AGDlypXn5q/yecYumy4p/fJ6vUpWuHg8nu0XDiMiDYCUAUx1dXUWBjRnK4qyHsD1iUTi+wBQV1c3tGNlA0AmrZJ37txp4y8TCnvnzp32kH2HAr3k5Pr/AVb9URPaeT+pAAAAAElFTkSuQmCC' is not JSON serializable

**Comment by ilanschnell** [comment]
This issue should be fixed in conda 3.8.1, please let us know if it isn't.
