### ISSUE TITLE
run_constrained not applied on windows

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda#10975]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

While building for the newest [modin](https://github.com/conda-forge/modin-feedstock/pull/27) version in conda-forge, there's an issue with the openssl 3 backports for python 3.7 on windows. To unblock the situation, I added a `run_constrained`
```
      run_constrained:
        # openssl 3.0 backports to python 3.7 are somehow broken
        - openssl ==1.1.1  # [py37]
```

This works as expected on osx & linux - i.e. it pulls in openssl 1.1.1 - but on windows, the environment _still_ picks up openssl 3.0.0 and fails.

```
The following NEW packages will be INSTALLED:

    bokeh:              2.4.0-py37h03978a9_0        conda-forge
    [...]
    mkl:                2021.3.0-hb70f87d_564       conda-forge
    modin-core:         0.11.1-py37h03978a9_0       local      
    modin-dask:         0.11.1-py37h03978a9_0       local      
    msgpack-python:     1.0.2-py37h8c56517_1        conda-forge
    [...]
    openssl:            3.0.0-h8ffe710_1            conda-forge
    packaging:          21.0-pyhd8ed1ab_0           conda-forge
    [...]
```
```
  File "D:\bld\modin-packages_1633683011256\_test_env\lib\ssl.py", line 482, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: unknown error (_ssl.c:4034)
```

CC @chrisburr @vnlitvinov

**Comment by vnlitvinov** [comment]
This blocks making a [Windows build](https://github.com/conda-forge/modin-feedstock/pull/27) for `modin-0.11.1`, could someone please take a look at that issue?

**Comment by h-vetinari** [comment]
Tried this in https://github.com/conda-forge/modin-feedstock/pull/28, OpenSSL 3.0 gets installed into the test environment in all cases (linux, osx, windows).

**Comment by chenghlee** [comment]
Can you use `[py==37]` rather than `[py37]` as the selector?

**Comment by h-vetinari** [comment]
Or in other words, something about `# [py3x]` is broken at the moment, because I cannot see a defensible case for having such radically different behaviour depending on a syntactic detail.
