### ISSUE TITLE
tables is listed as installed by pip

### ISSUE THREAD

**Issue by moorepants** [conda/conda#1097]
If you `conda install pytables` it will create two entries in the `conda list`. The `tables` entry says it is installed from `<pip>`.

```
(pydy-dev)moorepants@moorepants-2170p:pydy(ode-func-speed)$ conda list
# packages in environment at /home/moorepants/anaconda/envs/pydy-dev:
#
cairo                     1.12.18                       0  
cython                    0.21.2                   py27_0  
dateutil                  2.1                      py27_2  
freetype                  2.4.10                        0  
hdf5                      1.8.14                        0  
ipython                   2.3.1                    py27_0  
libpng                    1.5.13                        1  
matplotlib                1.4.2                np19py27_0  
mpmath                    0.19                     py27_0  
nose                      1.3.4                    py27_0  
numexpr                   2.3.1                np19py27_0  
numpy                     1.9.1                    py27_0  
openssl                   1.0.1k                        0  
pip                       1.5.6                    py27_0  
pixman                    0.26.2                        0  
py2cairo                  1.10.0                   py27_2  
pyparsing                 2.0.1                    py27_0  
pyqt                      4.10.4                   py27_0  
pytables                  3.1.1                np19py27_2  
python                    2.7.9                         1  
python-dateutil           1.5                       <pip>
pytz                      2014.9                   py27_0  
qt                        4.8.5                         0  
readline                  6.2                           2  
scipy                     0.15.0               np19py27_0  
setuptools                3.6                      py27_0  
sip                       4.15.5                   py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       0  
sympy (/home/moorepants/src/sympy) 0.7.6 git                 <pip>
system                    5.8                           1  
tables                    3.1.1                     <pip>
theano                    0.6.0                np19py27_0  
tk                        8.5.15                        0  
wsgiref                   0.1.2                     <pip>
zlib                      1.2.8                         0  
```

**Comment by asmeurer** [comment]
I guess the Python package name is `tables`.

**Comment by moorepants** [comment]
Yes, that is true. So `conda list` shows both the conda packages and the python packages. If a conda package contains, for example, 10 python packages then it would show them all as installed from `<pip>`. Sorta confusing, but I understand now.

**Comment by ilanschnell** [comment]
I agree, it is confusing, but renaming the conda package would be confusing as well, so I guess we have to deal with it.

**Comment by moorepants** [comment]
For what its worth, it'd be nice if the third column beside `tables` read `<conda>` instead of  `<pip>`.  If you point me to the pertinent code I can look into it.

**Comment by ilanschnell** [comment]
The third column list the (conda build string).  It is necessary to list this because of the ability to replicate environments.  Anything which is not a conda package, should be listed with `<...>`.

**Comment by moorepants** [comment]
Yes, I understand that. But a Python distribution could hold any number of packages. If a Conda package is built from that Python distribution, then all of the packages that are installed when the Conda package is installed will be listed as installed from `<pip>`. How hard would it be to simply detect all of the Python packages installed by a Conda package and ensure that the build string reads `<conda>` instead of  `<pip>`?

Example Python distribution with a name "MyPackages":

```
setup.py
package1
-->__init__.py
package2
-->__init__.py
package3
-->__init__.py
```

Conda `list` should produce (added more info to tie to main Conda package):

```
# packages in environment at /home/moorepants/anaconda/envs/test:
#
MyPackage                 1.12.18                       py27_0  
package1                    1.12.18                      <conda:MyPackage>  
package2                    1.12.18                      <conda:MyPackage>  
package3                    1.12.18                      <conda:MyPackage> 
```

**Comment by asmeurer** [comment]
So you want, effectively, a duplicate entry for every conda Python package?

**Comment by ilanschnell** [comment]
Conda is really Python agnostic.  Listing "Python packages" would not seem like good idea to me.  It would make the output of conda list very long, and be very Python specific.

**Comment by moorepants** [comment]
So it seems then that the entry `tables` (from top of thread) should not be listed at all, which is also a fine solution that would remove the confusion.

**Comment by ilanschnell** [comment]
Correct.  However, if the PyPI name was also `pytables` it would not be listed.

**Comment by moorepants** [comment]
So if the conda package is named `pytables` and the pypi distribution name is `pytables` and it contains contains one python package named `tables`. It seems that `conda list` should only show a single entry for `pytables` (because that is the conda package name). I'm not sure how the Python Package distribution name plays into this. Does `conda list`, for `<pip>` entries, display the Python distribution name or the python package name(s)?

I guess this begs the question, if conda is python agnostic, why are pip installed packages displayed at all in conda list? For example, why doesn't it also list linux distribution package manager installed python packages (or any other software, for that matter).

I'm now exclusively using conda and conda environments over virtualenv, but I install all Python software that doesn't have an official anaconda binary using pip because I still find creating conda binaries to be difficult. So the `<pip>` feature is nice in `conda list` for that reason, but I guess I should just use `conda list` + `pip freeze` to see what are in my environments.

Anyways, this is all a minor issue I suppose. It's fine the way it is, regardless of the minor confusion.

**Comment by ilanschnell** [comment]
The way that `conda list` works is the following: It looks at all conda packages, and then (if pip is even installed) it calls out to `pip` and adds the "pip" packages, for which there is no conda package name.  It is true that this is Python specific behavior.  Removing `pip` will make `conda list` only list the conda packages.

**Comment by moorepants** [comment]
Ok, thanks for the explanation.

**Comment by asmeurer** [comment]
To clarify something, the pip packages are read from parsing `pip list`.

This is done for convenience, since most conda users are also Python users. You can disable it entirely if you want with `conda config --set use_pip no`. 

I don't think this particular situation warrants engineering around.

**Comment by moorepants** [comment]
And to clarify, at least for me, `tables` is the PyPi/setup.py `name` for the PyTables distribution, which contains a top level package also called `tables`. `pip list` gives the PyPi/setup.py name of the installed distribution, not the name of the individual packages.
