### ISSUE TITLE
conda build also define C_INCLUDE_PATH and CPLUS_INCLUDE_PATH

### ISSUE THREAD

**Issue by sstirlin** [conda/conda#1098]
"conda build" currently defines the environment variable INCLUDE_PATH=$PREFIX/include.  However, gcc doesn't use this, but instead uses C_INCLUDE_PATH and CPLUS_INCLUDE_PATH.

Because of this, all of my build.sh files look like this

C_INCLUDE_PATH=$PREFIX/include make install

Instead of the simpler

make install

Should these env vars also be defined?  Thanks

**Comment by ilanschnell** [comment]
What is wrong with having:
```
export C_INCLUDE_PATH=$PREFIX/include
```
in your build script?
I would argue that the more explicit the build script is, the better.

**Comment by sstirlin** [comment]
I agree that less magic is better, but *some* magic is useful.

The treatment of includes vs libs is inconsistent.  conda-build defines LIBRARY_PATH=$PREFIX/lib, so why wouldn't it do the same for includes?

The answer is that is does *try* - it defines INCLUDE_PATH=$PREFIX/include, but that isn't honored by gcc (nor by clang I think).

This seems confusing.  Why define INCLUDE_PATH if it has no effect?  I would argue that either all four (INCLUDE_PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, LIBRARY_PATH) should be defined, or none.

I'm not going to lose sleep over it, but it does seem like a trap of confusion and bugs.  Thanks

**Comment by ilanschnell** [comment]
I'm not sure who added INCLUDE_PATH, but I would find it better if it wasn't defined.

**Comment by sstirlin** [comment]
Too late.  You could make a breaking change I guess.

The reason that most recipes don't encounter this is that people usually do a ./configure --prefix=blahblah before running make.

However, some packages just supply a straight make (perl, I think, and git) and so autotools doesn't save us.

**Comment by ilanschnell** [comment]
Yes, I didn't realize that `PKG_CONFIG_PATH`, `INCLUDE_PATH` and `LIBRARY_PATH` got added.  Removing them now is not probably not a good idea.  I would encourage people not to use them, but to construct them in `build.sh` instead.

**Comment by sstirlin** [comment]
Thanks.  I'll follow your advice.  I guess you could put a deprecation warning on it and remove it in a year or two.  Probably not worth the hassle, though
