### ISSUE TITLE
Docs: function of wildcard in environment.yml not documented

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#10985]
### What happened?

The behaviour of the wildcard `*` in environment.yml is not documented (properly). I found disputing explanations in the conda docs, on StackOverflow and in a conda issue.

The [docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) state ominously but don't actually explain properly:
> Note the use of the wildcard `*` when defining the patch version number. Defining the version number by fixing the major and minor version numbers while allowing the patch version number to vary allows us to use our environment file to update our environment to get any bug fixes whilst still maintaining consistency of software environment.

There's an example environment.yml that doesn't explain it either:
```
name: stats2
channels:
  - javascript
dependencies:
  - python=3.6   # or 2.7
  - bokeh=0.9.2
  - numpy=1.9.*
  - nodejs=0.10.*
  - flask
  - pip:
    - Flask-Testing
```

On StackOverflow, wildcard isn't mentioned at all, while the top question says itself that the author couldn't find this behaviour documented (so I'm not the first to think so): https://stackoverflow.com/a/54849994/7483211

There are conflicting comments from _merv_ https://stackoverflow.com/a/65210951/7483211
>  You don't need the .* to spec Python 3.7; just python=3.7 is more idiomatic.

Then I found this issue which says wildcards are deprecated? Agreeing with merv above: https://github.com/conda/conda/issues/9140

But the docs still state wildcards... Very confusing.

Can someone explain and then someone else can clean up the docs? Thanks!

**Comment by maresb** [comment]
I am also wondering what's going on. I'm confused by different behavior between `==` and `=` when using wildcards (see https://github.com/conda-incubator/grayskull/issues/348) and I'm currently searching for documentation.

**Comment by corneliusroemer** [comment]
Quickly testing this, it seems that at least `conda search` requires wildcards, and doesn't accept the short form `numpy=1.17`:

```console
$ conda search "conda-forge/linux-64::numpy 1.17.* py38*"
Loading channels: done
# Name                       Version           Build  Channel             
numpy                         1.17.3  py38h95a1406_0  conda-forge         
numpy                         1.17.5  py38h18fd61f_1  conda-forge         
numpy                         1.17.5  py38h95a1406_0  conda-forge         

$ conda search "conda-forge/linux-64::numpy 1.17 py38*"  
Loading channels: done
No match found for: conda-forge/linux-64::numpy==1.17[build=py38*]. Search: conda-forge/linux-64::*numpy*==1.17[build=py38*]

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/linux-64::numpy==1.17[build=py38*]

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
