### ISSUE TITLE
conda build should be sensitive to hardlinks.  Suggest using SHA hash to keep only *unique* files

### ISSUE THREAD

**Issue by sstirlin** [conda/conda#1099]
Some packages install with many hardlinks.  The resulting tarball in binstar then contains dozens of copies of the same file because conda-build doesn't recognize that they all point to the same underlying file.

git, for example, does this.  In the libexec/git-core directory are dozens of files (e.g. git-merge, git-rebase, etc) that are all hardlinks to git.  The resulting tarball in binstar is over 300MB.

Fortunately, in the case of git, I can pass the NO_INSTALL_HARDLINKS=YesPlease option on the make command line.  The installer then uses symbolic links instead (which conda seems to handle correctly).  The resulting tarball is reduced to 25MB.

However, other packages may not be so easy.  Also, this cost me at least an hour to figure out.

Speaking of git, maybe conda-build should use a similar method to determine unique files?  git computes a SHA hash for each file and directory.  In this way it can reproduce the directory structure  exactly (even hardlinks).

Thanks!

**Comment by asmeurer** [comment]
Perhaps https://github.com/conda/conda/pull/623 fixes this. Or does it need to be fixed in conda build as well?

**Comment by sstirlin** [comment]
Strange.  It must be a problem in conda build then.  I'm using the latest conda, so a fix from March would definitely be in there.

**Comment by kalefranz** [comment]
From #623 

> This can actually be closed. With the new `info/paths.json` file, if conda-build records a path type as `directory`, then that will be respected by conda as of conda 4.3.
