### ISSUE TITLE
Invalid root_dir for pip installed conda on ubuntu 14.04

### ISSUE THREAD

**Issue by sklam** [conda/conda#1100]
These lines https://github.com/conda/conda/blob/4b51cd79bf17f59d1c1db95eeae539b4831baba9/conda/config.py#L115-L116 expect sys.prefix be the same as conda's prefix.  This is not true on ubuntu 14.04.

```
$ which python
/usr/bin/python
$ which conda
/usr/local/bin/conda
```

As a result, the symlink in an environment points to /usr/bin/conda, which does not exist.  The if-condition in https://github.com/conda/conda/blob/4b51cd79bf17f59d1c1db95eeae539b4831baba9/conda/install.py#L387-L388 is True and the os.symlink call will raise an exception due to "OSError: File exists".

It seems like this can be workaround by setting CONDA_ROOT=/usr/local

**Comment by asmeurer** [comment]
What variable does distutils/setuptools use to decide where to install `scripts` in this setup?

**Comment by sklam** [comment]
I don't know.  Everything should be using the default value.  This is the first time I use the system Python in this machine.

**Comment by ilanschnell** [comment]
The workaround Siu suggested, ie. `setting CONDA_ROOT=/usr/local` is the best solution.  It appears that Ubuntu has changed the standard Python behavior.

**Comment by asmeurer** [comment]
I'm not convinced this is nonstandard Python behavior. https://github.com/conda/conda/issues/1056 reports the same thing on OS X. I think distutils can install things to a different directory than `join(sys.prefix, 'bin')` in some cases.
