### ISSUE TITLE
Conda config not using ssl_verify value shown in 'conda config --show'

### ISSUE THREAD

**Issue by jlynchMicron** [conda/conda#11006]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Any network related conda operations fail for me.  Figured out the values in my .bashrc file were overriding what conda config variables, but this was not being shown in my "conda config --show" output.

These .bashrc settings were set: 
CURL_CA_BUNDLE, REQUESTS_CA_BUNDLE, HTTPLIB2_CA_CERTS

This was my conda config setting for ssl_verify:
`conda config --show | grep ssl
  - openssl
client_ssl_cert: None
client_ssl_cert_key: None
ssl_verify: False`

Error example:
`conda update --all -v
Collecting package metadata (current_repodata.json): ...working... Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /pkgs/main/linux-64/current_repodata.json
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /pkgs/main/noarch/current_repodata.json`

So based on "SSL: CERTIFICATE_VERIFY_FAILED", it was clearly trying to use SSL even though my ssl_verify setting was shown to be false.  Even when I ran a "conda update --all --insecure", it failed for the same error.  I am guessing the conda logic for ssl variable setting is skrewy or something.

I am behind a cooperate proxy too, but figured out this was a SSL issue.  After I commented out those variables in my .bashrc, conda update worked again.

### Conda info

```shell
active environment : base
    active env location : /home/jlynch/miniconda3
            shell level : 2
       user config file : /home/jlynch/.condarc
 populated config files : /home/jlynch/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jlynch/miniconda3  (writable)
      conda av data dir : /home/jlynch/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jlynch/miniconda3/pkgs
                          /home/jlynch/.conda/pkgs
       envs directories : # HIDDING
                          # HIDDING
                          # HIDDING
                          # HIDDING
                          # HIDDING
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/3.10.0-957.27.2.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 1173703:1173703
             netrc file : None
           offline mode : False
```

**Comment by dholth** [comment]
Do we think it respects the "no verify" flag when a proxy is not being used
