### ISSUE TITLE
Conda not finding correct directory to install packages into

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1101]
I'm trying to install `yaml` into a conda env.  `which conda` and `which python` are in agreement about my current env: `/opt/wakari/wakari-compute`, but `conda info -a` says that the _default env_ is `/opt/wakari/anaconda`, and that is where any `conda install foo` operations put packages.  My `PATH` has `/opt/wakari/wakari-compute/bin` first, but it also has `/opt/wakari/anaconda/bin`:

``` bash
[root@showtime installer]# env | grep -i conda
PATH=/opt/wakari/wakari-compute/bin:\
/opt/wakari/wakari-gateway/bin:\
/opt/wakari/anaconda/bin:\
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

and my bash envs have no other conda-related vars set.

What am I doing wrong?

**Comment by tswicegood** [comment]
@ijstokes what's the output of `echo $CONDA_DEFAULT_ENV` -- if that's out of sync it would be causing this issue.  Not sure how it would be out of sync.

**Comment by kalefranz** [comment]
Outdated. Closing.
