### ISSUE TITLE
conda env update doesn't update variables

### ISSUE THREAD

**Issue by bmillspaugh** [conda/conda#11055]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

`conda env create` sets the environment variables listed in the `environment.yml` file...

https://github.com/conda/conda/blob/f47dc5e6f1a894ffeea22584b38d162a90192035/conda_env/cli/main_create.py#L154-L159

...but `conda env update` doesn't update them.  The update routine reads the `environment.yml` file for everything else when it runs, but it skips the variables.  If they were included you could maintain your list of `variables` in `enviroment.yml` just like you do your lists of `channels` & `dependencies`, allowing you to easily add/remove variables by simply changing that file.

Adding those 3 lines of code (see lines 154-156 above) to the `conda_env.cli.main_update` module should fix this bug:

https://github.com/conda/conda/blob/f47dc5e6f1a894ffeea22584b38d162a90192035/conda_env/cli/main_update.py#L124-L126

**Comment by kenodegard** [comment]
This is already in the works!

**Comment by bmillspaugh** [comment]
Thanks Ken! I can submit this as a pull request if you prefer since it looks like a pretty simple fix.

**Comment by kenodegard** [comment]
Sorry! Forgot to explicitly mention, there's already a PR open for this, see #10652, hopefully that'll get merged shortly.

**Comment by bmillspaugh** [comment]
Perfect, thanks!
