### ISSUE TITLE
add option to disable or change "conda activate" message shown after creating new environment

### ISSUE THREAD

**Issue by lastephey** [conda/conda#11067]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Dear Anaconda developers,

We use Anaconda at NERSC, a large supercomputing center with two large systems and several shared filesystems. We find that the message automatically shown when creating a new environment that encourages users to use `conda activate` causes a lot of user confusion. For example:

```
stephey@cori06:~> conda create -n test python=3.9 -y

...

#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

Our feature request is either
1. Allow us to turn off this message
2. Allow us to edit the test of this message

Thank you,
Laurie

### Why is this needed

This would help us alleviate a lot of user confusion and support tickets on our systems. In general we suggest that users use `source activate` instead of `conda activate` on our systems instead to avoid making center-wide/permanent changes to their configuration. For more background you can see our [Python user facing documentation](https://docs.nersc.gov/development/languages/python/nersc-python/).

### What should happen?

We would either like to edit the contents of this message:

```

#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

to say `source activate test`, for example, or have the option to turn off this message altogether.

**Comment by kenodegard** [comment]
@lastephey I think this is a perfectly reasonable request!

BUT do be aware that `source activate`/`source deactivate` is not recommended as is has been deprecated and there is no longterm guarantee for it.

Further since y'all use Environment Modules/LMOD I would recommend invoking the init script in your module recipe which will expose `conda activate`/`conda deactivate` without impacting any system/user profile configurations.

Heres a snippet from my own LMOD lua recipe:

```lua
local _CONDA_ROOT = ...
execute{cmd="source '"..pathJoin(_CONDA_ROOT, "/etc/profile.d/conda."..myShellType()).."'", modeA={"load"}}
```

**Comment by lastephey** [comment]
Hi @kenodegard thanks for this very helpful suggestion! 

I'll experiment with integrating this into our modules (TCL on Cori and LMOD on Perlmutter). If we don't run into any snags then I'll close this issue. Thanks again!

**Comment by lastephey** [comment]
Hi @kenodegard,

Thanks again for this suggestion. For you/anyone else who might find this thread, the solutions we used were

TCL:

```
set name    python
set version 3.9-anaconda-2021.11
set root    /usr/common/software/$name/$version


if { [ module-info shell ] == "bash" } {
    puts stdout "source $root/etc/profile.d/conda.sh ;"
}

if { [ module-info shell ] == "csh" } {
    puts stdout "source $root/etc/profile.d/conda.csh ;"
}
```


LMOD:

```
local root        = pathJoin("/global/common/software/nersc/pm-2021q4/sw", name, version)
execute{cmd="source '"..pathJoin(root, "/etc/profile.d/conda."..myShellType()).."'", modeA={"load"}}
```

Since this seems to be working ok in our testing so far, I'll go ahead and close this request.

Thank you again,
Laurie

**Comment by kenodegard** [comment]
@lastephey wonderful! thanks for sharing!
