### ISSUE TITLE
Fish shell 2.x support broken by removed evals

### ISSUE THREAD

**Issue by w-m** [conda/conda#11079]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
I'm running Ubuntu 18.04 LTS. Using fish shell, version 2.7.1. This is an outdated version of fish, but it's the one that ships with that Ubuntu version.

After updating conda, I got the following error when creating a new shell: 

```
~/anaconda3/etc/fish/conf.d/conda.fish (line 2): Variables may not be used as commands. In fish, please define a function or use 'eval $CONDA_EXE'.
        $CONDA_EXE
        ^
in function “conda”
        called on standard input
```

The environment is completely broken, it's not possible to use `conda` in this state. The cause seems to be #10696, which removed the evals. This breaks fish shell v2.7.1 support.

A fix for me was to update fish shell by installing release 3 through the ppa (https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

### Conda info
```shell
active environment : base
    active env location : /home/morgenstern/anaconda3
            shell level : 1
       user config file : /home/morgenstern/.condarc
 populated config files : /home/morgenstern/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.3=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/morgenstern/anaconda3  (writable)
      conda av data dir : /home/morgenstern/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/morgenstern/anaconda3/pkgs
                          /home/morgenstern/.conda/pkgs
       envs directories : /home/morgenstern/anaconda3/envs
                          /home/morgenstern/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.10 Linux/5.4.0-91-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by kenodegard** [comment]
@johnflavin as the author of the #10696 fix do you have any insight here?

**Comment by johnflavin** [comment]
For context on the change I made to remove the `eval`s: I noticed issues using conda in fish where strings needed to be double quoted. I investigated here and saw that other people had reported similar issues. I found that when I removed the `eval` statements in the conda fish shell functions all those issues were fixed.

Sorry about breaking this! I didn't realize that the `eval`s were crucial for older versions of fish. I did all my testing with fish versions above 3. I didn't even realize that 2.x fish versions were still being used. The last version in the 2.x series, 2.7.1, was [released almost four years ago](https://github.com/fish-shell/fish-shell/releases/tag/2.7.1) and the first version in the 3.x series, 3.0.0, [almost three years ago](https://github.com/fish-shell/fish-shell/releases/tag/3.0.0).

A possible fix could be to detect the fish version within the `conda` function in [`conda.fish`](https://github.com/conda/conda/blob/master/conda/shell/etc/fish/conf.d/conda.fish#L64). If it is `< 3.0.0` then use the old version of the function with the extra `eval`s, otherwise use the function as it is now.

**Comment by sjdh** [comment]
> I'm running Ubuntu 18.04 LTS. Using fish shell, version 2.7.1.

Me too and I have exactly the same problem. Conda became unusable.

**Comment by KumaTea** [comment]
I also came across this error. 

I solved it by manually updating `fish` to its latest version following the instructions on [its official website](https://fishshell.com).

It might not be a perfect solution but works.

### Ubuntu

```
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install fish
```

### Debian

```bash
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_9.0/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
sudo apt update
sudo apt install fish
```

**Comment by w-m** [comment]
Makes sense to not keep supporting the outdated fish version. But I would suggest to add an explicit error message when conda discovers that it runs under fish < 3, for people updating, like us who reported here.

I was looking for issues with my config / conda.fish for quite a while before I realised the problem is with the fish version.

**Comment by arteymix** [comment]
What would be the latest version of Conda that supports fish 2? We are still running Cent OS 7 and I don't think we could use fish 3 yet.

**Comment by johnflavin** [comment]
Just looking at the timing of when #10696 got merged and when the releases came out, `4.11.0` is the version that broke compatibility with fish 2.x. So if you’re able to pin conda to < 4.11 I expect that would restore the previous behavior.

Alternatively, you could always manually load the old definition of the `conda` function. That's what I did while I was waiting for them to merge my update; I ran the ordinary `conda.fish` which at the time still had the old function but I also defined the new function in my config.

All you would need to do to restore the old behavior is paste the old function definition into your config _after_ the `conda.fish` definitions are loaded. That way the old behavior you want overwrites the new behavior you don't want.

```fish
function conda --inherit-variable CONDA_EXE
    if [ (count $argv) -lt 1 ]
        eval $CONDA_EXE
    else
        set -l cmd $argv[1]
        set -e argv[1]
        switch $cmd
            case activate deactivate
                eval (eval $CONDA_EXE shell.fish $cmd $argv)
            case install update upgrade remove uninstall
                eval $CONDA_EXE $cmd $argv
                and eval (eval $CONDA_EXE shell.fish reactivate)
            case '*'
                eval $CONDA_EXE $cmd $argv
        end
    end
end
```

**Comment by youralmight** [comment]
> I also came across this error.
> 
> I solved it by manually updating `fish` to its latest version following the instructions on [its official website](https://fishshell.com).
> 
> It might not be a perfect solution but works.
> 
> ### Ubuntu
> ```
> sudo apt-add-repository ppa:fish-shell/release-3
> sudo apt update
> sudo apt install fish
> ```
> 
> ### Debian
> ```shell
> echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
> curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_9.0/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
> sudo apt update
> sudo apt install fish
> ```

I tried to install fish>=3 on ubuntu 18.04. It worked

**Comment by arteymix** [comment]
@johnflavin 

> Just looking at the timing of when #10696 got merged and when the releases came out, `4.11.0` is the version that broke compatibility with fish 2.x. So if you’re able to pin conda to < 4.11 I expect that would restore the previous behavior.

I ended up adding `conda<4.11` to `conda-meta/pinned` to prevent Conda update.

**Comment by fengerzh** [comment]
CentOS 7 upgrade fish to 3 solved the issue:

```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_7/shells:fish:release:3.repo
yum install fish
```

**Comment by diklios5768** [comment]
> 

This worked! Though not the newest version.

**Comment by diklios5768** [comment]
> CentOS 7 upgrade fish to 3 solved the issue:
> 
> ```
> cd /etc/yum.repos.d/
> wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_7/shells:fish:release:3.repo
> yum install fish
> ```

This worked! Though not the newest version.

**Comment by yiGmMk** [comment]
> > CentOS 7 upgrade fish to 3 solved the issue:
> > ```
> > cd /etc/yum.repos.d/
> > wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_7/shells:fish:release:3.repo
> > yum install fish
> > ```
> 
> This worked! Though not the newest version.
To install v3,I erase fish v2 first
`yum erase fish`
then install v3,it works(fish, version 3.5.1)
