### ISSUE TITLE
Support shared cache, e.g. in remote Docker builds for concurrent conda invocations

### ISSUE THREAD

**Issue by therc** [conda/conda#11078]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
* [x] I confirmed that it's not related to another project (see the above section)

### What is the idea?
We build a lot of Docker images with lots of Conda packages. We have a remote build service to increase caching, but we still got to the point where network times (fetching the packages) are a considerable chunk of the total it takes to complete a build. I tried enabling cache mounts (see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache), but came across an interesting race condition. Even if we use lockfiles to reduce version churn, there can be a case where two concurrent builds see a new Conda package that is not in the cache yet. The first instance will start downloading the package as expected. The second one will see that the partial file already exists, but it will complain that the package is corrupted, because it's not the expected size (yet), so it will crash and burn. This scenario is more likely to trigger when similar builds start very close to each other and when the new packages are very large. The basic idea is that conda could handle these scenarios more gracefully.

I could turn on locking in the Dockerfile for the cache, so that only one build at a time will try to use it. But that means that for entire minutes, these conda operations are pretty much serialized.

There might be more, but I thought of two possible solutions:

1) We could write the partial packages to a temporary filename, then rename them at the end. This is not optimal, because you might fetch packages multiple times, but at least it's not breaking things (and it's not any worse than with the cache off).
2) Any instances running after the first could detect that there is a partial file getting downloaded and thus check again after some delay. This still has a race condition, but the time window is much smaller, plus it can be addressed with file locking (and a FS that supports it).

You could argue that the first option might even make sense as a default (but it has ramifications in terms of garbage collecting old temporary files that were left behind after a crash). For the latter, perhaps an opt-in flag might be better.

### Why is this needed
This benefits anyone who downloads large Conda packages (hello CUDA, hello PyTorch) unnecessarily, especially in Docker environments. Yes, you could set up a local HTTP cache, but that's not always easy or feasible.

### What should happen?
The user (or a build service) runs two parallel conda commands involving an overlapping set of packages and they don't fail. Ideally, downloads would be kept at an absolute minimum.

**Comment by dholth** [comment]
mamba lock implementation: is it locking the entire repodata cache, and then individual package archives

https://github.com/mamba-org/mamba/commit/2b7b230613a2712e62b54234f685ffab5efb8fb1

https://github.com/mamba-org/mamba/blob/main/libmambapy/libmambapy/__init__.pyi#L586

**Comment by kaanchan** [comment]
> Ideally, downloads would be kept at an absolute minimum.

Yes please to keeping downloads to an absolute minimum. I support non-profit projects that leverage tech to make educational resources more accessible. Many of the locations I am at are remote and/or lack modern internet download speeds or consistent/reliable electricity. Solutions that work for the more extreme cases will almost certainly benefit everyone in a more tech-friendly environment.
