### ISSUE TITLE
I am trying to generate polish.vcf and consensus sequence for virus using nanopolish --consensus. I am unable to generate vcf using given documentation. please give me an idea about the same.

### ISSUE THREAD

**Issue by sachinharle** [conda/conda#11073]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

A wild Caterpie appeared!

**Comment by kenodegard** [comment]
If you are having trouble **installing** `nanopolish` we will need further details in order to help.

If you need help with how `nanopolish` works, please ask your questions on the project's page: https://github.com/jts/nanopolish.

Thanks!
