### ISSUE TITLE
Recovering conda environments from a backedup anaconda3 folder

### ISSUE THREAD

**Issue by tenres** [conda/conda#11077]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
* [x] I confirmed that it's not related to another project (see the above section)

### What is the idea?
Firstly, I would like to thank you all for such quick responses!

We have a problem, and not a feature request. Our hard drive running Ubuntu 18 crashed few days ago. We had setup regular rsync backups of the drive, which included the anaconda3 installation folder. There were a lot of conda envs, but barring a few, we were ignorant to not have backed up all their conda env yamls or conda pack backups; we only have the old anaconda3 installation folder, which has the environment files inside the envs folder. Now, we have re-installed a new drive with Ubuntu 20 (note the older one was 18), and are hoping if there is any way at all to recover the envs from the older anaconda folder? For e.g., if we install anaconda on the new OS and copy just the backed up old envs folder to the newly installed envs folder, with potentially requiring changes elsewhere, would it work? We would be elated to hear any advice on any possible hacky ways to recover the envs from backed up folders (even if only partially). Thanks again!

**Comment by kenodegard** [comment]
If I understand correctly you were only backing up the `anaconda3/envs` folder?

If that's the case then all of those envs are still entirely valid and usable (with some potential caveats). You can actually access them as absolute paths (not as names):

```bash
$ conda activate ~/anaconda3_old/envs/old_env
```

Just move this old envs folder into your new anaconda3 installation and everything will work again.

**Comment by keshavak** [comment]
Thanks for the quick reply @kenodegard. That sounds encouraging. I copied an older env folder from anaconda3_old/envs/old_env to anaconda3/envs in the new installation. I was able to activate it as well. But for some reason, in the python terminal, the backspace behaves strangely. It keeps going forward like tabs or pastes text. This does not happen with an env created in the new installation itself. Have you come across this, and if this could this be fixed my editing some file in the copied old env? Thanks!

**Comment by kenodegard** [comment]
Hm that's not good and probably suggests that curses is broken.

You can try to reinstall the python package (feel free to specify the version):

```bash
conda install --force-reinstall python=M.M.M
```

**Comment by keshavak** [comment]
I see. Tried re-installing different versions of python 3.6 (later pythons are not compatible with the rest of the env) with the same result. Would you have any other hacky suggestions to save the envs, even partially? Thanks!

**Comment by kenodegard** [comment]
Hm you could also try to activate the env and exporting the env and then importing that output into a new conda env:

```bash
$ conda activate /path/to/old_env
(/path/to/old_env) $ conda env export > env.yaml
(/path/to/old_env) $ conda env create --file env.yaml --name new_env
```

**Comment by keshavak** [comment]
With the above, I am not seeing the strange behavior with backspace in new_env. But seems like some packages from the old environment are missing; i.e. the new env created from the old env yaml file is not complete for some reason. When I activate the old_env itself, i.e. using just "conda activate /path/to/old_env", I see all the packages, but has the strange backspace issue. Also, the anaconda3/envs/new_env folder itself has only conda-meta/history folder, and nothing else. Could there be any easy way to make sure all of the old env packages are installed in the new_env as well? Thank you!

**Comment by kenodegard** [comment]
Are all of the packages in the old env conda packages or are they include a mix of conda and pip packages (or even from other package managers like npm)? If you have a mix then conda will try to its best to replicate the setup but ultimately you will need to manually review the new environment and ensure the non-conda packages are installed as desired.

As for only getting the conda-meta/history folder, I am unable to replicate that happening, using the above `conda env export` and `conda env create` commands I get the expected folder structure:

```bash
/path/to/miniconda/envs/env
├── bin
│   ├── python -> python3.9
│   ├── python3 -> python3.9
│   ├── python3.9
│   └── ...
├── conda-meta
│   ├── history
│   ├── python-3.9.7-h88f2d9e_1.json
│   └── ...
├── include
│   └── ...
├── share
│   └── ...
└── ssl
    └── ...
```
