### ISSUE TITLE
Consider PEP 440

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#1107]
We should consider switching the version comparison to PEP 440, instead of PEP 386.  The reference implementation of PEP 440 looks much cleaner, and it would possibly solve some of the existing problems when comparing version numbers.

**Comment by asmeurer** [comment]
https://github.com/conda/conda/issues/915

**Comment by shoyer** [comment]
Would this simply be a matter of plugging in `distlib.version` from [distlib](http://distlib.readthedocs.org/)? It appears to be derived from verlib, but implements PEP 440: https://bitbucket.org/pypa/distlib/src/712bebbecb6f8f29d16f7b10f6ac05b8b04c7dda/distlib/version.py?at=default

**Comment by asmeurer** [comment]
Actually swapping the two out will not be hard, but we should take a look at how the two differ and how that will affect the existing packages.

**Comment by asmeurer** [comment]
There are actually two issues here. One is to use PEP 440 for internal version parsing in some way, sone another is to make conda's own versions 440 compatible. For the latter, see https://github.com/warner/python-versioneer/pull/45.

**Comment by patricksnape** [comment]
Just to jump in here: versioneer master (0.13+dev) now implements PEP 440 compatible version strings, which I am now moving to for my projects. It would be great to see conda/binstar move to this since releasing alpha/beta version using conda is currently pretty broken.

For example, I had a package v0.1.0a and then I released the final version as v0.1.0, but v0.1.0a is recognized as a 'newer' version, which makes it difficult to tell people to upgrade!

**Comment by asmeurer** [comment]
An issue we just noticed. OpenSSL versions (like 1.0.1k) are not 440 compliant, except, the ones that end in a, b, or c. Those ones, it treats as alpha versions. So when OpenSSL version 1.0.2a is released, conda will see it as less than version 1.0.2 (this is the case both for the current code and for PEP 440).

**Comment by shoyer** [comment]
@asmeurer  Perhaps conda needs different rules for Python and non-Python projects?

**Comment by flub** [comment]
I did wonder about this before. In our own pre-conda build system we used
Debian version numbers which can adjust to pretty much anything. But for
pep 440 one could translate openssl's j, k etc into .post0, .post1 etc. As
long as one remains consistent and keeps increasing the version number all
is fine.

At the end of the day there will always be versions that don't directly
match the version scheme chosen and will need translating. It might be nice
for conda to have a public API to check how version numbers compare for
those edge cases.

Taking this slightly further it could be nice for meta.yaml to have a
upstream version field for those cases where translations are needed.

Regards
Floris

**Comment by asmeurer** [comment]
See https://github.com/conda/conda/pull/1601#issuecomment-142586245 for a full rundown, but we are effectively now PEP 440 compliant, except in some cases where versions for a package are not consistant. 

We still need to move to the newer verlib, though.

**Comment by ukoethe** [comment]
> But for pep 440 one could translate openssl's j, k etc into .post0, .post1 etc

I suggest to keep openssl's version strings intact, except for the plain version which should be translated as `1.0.2 => 1.0.2_`. This works because underscores are less than any lowercase letter in the order implemented by class `VersionOrder`.

**Comment by ukoethe** [comment]
> We still need to move to the newer verlib, though.

Note that I removed `verlib` entirely in PR https://github.com/conda/conda/issues/1601. Version comparison is now purely native conda code.

**Comment by asmeurer** [comment]
Sorry, I meant the newer versioneer (for the versions of conda itself).

**Comment by jseabold** [comment]
Is this documented anywhere other than [this blog post](https://www.continuum.io/blog/developer/advanced-features-conda-part-1) and this issue? This is the only mention I could find of how version comparison is done after a reasonable amount of searching.

**Comment by mcg1969** [comment]
I'd say [this issue](https://github.com/conda/conda/pull/1601) is the best one. In fact, this issue should be closed, since it has basically been accomplished by ukoethe's PR.

**Comment by mcg1969** [comment]
But yes it would be good to have better documentation on versioning. [This text](http://conda.pydata.org/docs/spec.html#build-version-spec) mentions PEP 386, but that's obviously out of date.

**Comment by jseabold** [comment]
> But yes it would be good to have better documentation on versioning. This text mentions PEP 386, but that's obviously out of date.

Thanks for the link. Yeah, I kind of intentionally avoided looking at the build docs, because I wanted to know if I could find it with my consumer hat on and what I could put in `environment.yml` or the like.
