### ISSUE TITLE
conda update conda cannot update conda

### ISSUE THREAD

**Issue by Firestar-Reimu** [conda/conda#11083]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
I am using `conda 4.10.3`, but `conda 4.11` has released

I ran `conda update conda` or `conda update --all`, but they cannot update conda

PS: https://docs.conda.io/en/latest/miniconda.html Miniconda has also been not updating for 5 months.

**Comment by kenodegard** [comment]
This is correct, we've been blocked by internal testing, 4.11.0 will be made available to the defaults channel in the coming days.

**Comment by Firestar-Reimu** [comment]
Will a new version of miniconda update when conda 4.11 and python 3.10 is out?

**Comment by joancafom** [comment]
Hi!

> This is correct, we've been blocked by internal testing, 4.11.0 will be made available to the defaults channel in the coming days.

Is there any news about this? Thanks

**Comment by Firestar-Reimu** [comment]
`conda                     4.11.0           py39h06a4308_0    defaults`

**Comment by FraPazGal** [comment]
Hello!

Would it be possible to have an approximate ETA on the next miniconda release?

Thanks in advance!
