### ISSUE TITLE
Plotly install error

### ISSUE THREAD

**Issue by pepo83** [conda/conda#11088]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Fresh installation of Anaconda3-2021.11-Windows-x86_64.

When I try to install plotly with: `conda install -c plotly plotly`

The following error occurs:

```batch
Downloading and Extracting Packages
plotly-5.4.0         | 6.8 MB    | ############################################################################ | 100%
tenacity-8.0.1       | 34 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File ".\Anaconda3\Lib\site-packages\plotly\io\__init__.py", line 54, in <module>
  File ".\Anaconda3\Lib\site-packages\plotly\plotly\__init__.py", line 4, in <module>
  File ".\Anaconda3\Lib\site-packages\_plotly_future_\__init__.py", line 43, in _chart_studio_error
ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.
```

**Comment by kenodegard** [comment]
I am unfortunately unable to replicate this issue. I suggest you try to reinstall `plotly`.

If the error persists since this pertains to the `plotly` package itself (and not to conda) please open this issue with the `plotly` project [itself](https://github.com/plotly/plotly.py).

Thanks!
