### ISSUE TITLE
Conda has wrong root_prefix etc

### ISSUE THREAD

**Issue by sjpb** [conda/conda#11091]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
I've installed Conda twice, using EasyBuild, on paths `.../h{p,t}c/...` for different slurm partitions/architectures.

I can see that the `htc` conda picks up environments created using the `hpc` conda and that's clearly the `~/.conda/environments.txt` [issue](https://github.com/conda/conda/issues/8804).

More worrying is that the `htc` conda looks wrong: 

```
$ conda config --show
croot: /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/conda-bld
<snip>
envs_dirs:
  - /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/envs
  - /shared/home/steveb/.conda/envs
<snip>
pkgs_dirs:                                                                                                                         [23/409]
  - /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/pkgs
  - /shared/home/steveb/.conda/pkgs
<snip>
root_prefix: /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05
```

but the conda install itself looks right:

```
$ which conda
/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/bin/conda
(base) [steveb@htc-1 ~]$ module show Anaconda3
---------------------------------------------------------------------------------------------------------------------------------------
   /mnt/azfiles/apps/htc/easybuild/modules/all/Anaconda3/2021.05.lua:
<snip>
conflict("Anaconda3")
prepend_path("MANPATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/man")
prepend_path("MANPATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/share/man")
prepend_path("PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/bin")
prepend_path("PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/sbin")
prepend_path("PKG_CONFIG_PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/lib/pkgconfig")
setenv("EBROOTANACONDA3","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05")
setenv("EBVERSIONANACONDA3","2021.05")
setenv("EBDEVELANACONDA3","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/easybuild/Anaconda3-2021.05-easybuild-devel")
prepend_path("PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05")
```

So it doesn't appear to be an easybuild install problem to me. Is there way other than the actual install path that conda uses to construct the `root_prefix`?

### Conda info
```shell
active environment : base
    active env location : /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05
            shell level : 1
       user config file : /shared/home/steveb/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05  (writable)
      conda av data dir : /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/pkgs
                          /shared/home/steveb/.conda/pkgs
       envs directories : /mnt/azfiles/apps/hpc/easybuild/software/Anaconda3/2021.05/envs
                          /shared/home/steveb/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 20003:20003
             netrc file : None
           offline mode : False
```

### Conda config
```shell
No output from command. See trimmed output from `conda config --show` above though.
```

### Conda list
```shell
(not sure this is relevant here, can post if it is)
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-52)

**Comment by kenodegard** [comment]
If `root_prefix` is not explicitly defined in your `.condarc` it defaults to `sys.prefix` of the Python installed in your base environment. This suggests that your `htc` environment is picking up and using the `hpc` base env's Python.

As outlined here this is not a `~/.conda/environments.txt` issue but sounds more like a `PATH`/`LMOD` recipe issue (btw it is not recommended to add the base env bin to your `PATH`, see #11087 #11067).

**Comment by sjpb** [comment]
Ah, thank you, the `lmod` suggestions make sense conceptually at least (will have to read up on details).

You say it's not recommended to add the base env's [python] bin to your PATH - I haven't deliberately done that, is that something `conda init` does?

**Comment by kenodegard** [comment]
In the `lmod` recipe you shared above you are prepending your `PATH` with `conda`'s `bin`/`sbin`:

> ```lua
> prepend_path("PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/bin")
> prepend_path("PATH","/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05/sbin")
> ```

This exposes `conda` as an _executable_ whereby most `conda` commands will work as expected (e.g. `conda create`, `conda install`, etc.) however you will not be able to activate/deactivate environments in the recommended manner (`conda activate`/`conda deactivate`). To do this we need `conda` to be a _shell function_. This is what `conda init` seeks to do for you. `conda init` will modify your profile(s) and inject a block of code that will ensure every new shell loads `conda` correctly as a _shell function_ (`lmod` and `conda` actually works in much the same ways in this regard, see `type module` and `type conda`).

However since you are seeking to use `lmod` to control which/when `conda` is available in your shell modifying your profile would be undesired (this is where #11067 is coming from). So instead of adding `bin`/`sbin` to your `PATH` or invoking `conda init` you want to include the following in your `lmod` recipe:

```lua
local root = "/mnt/azfiles/apps/htc/easybuild/software/Anaconda3/2021.05"
execute{cmd="source '"..pathJoin(root, "/etc/profile.d/conda."..myShellType()).."'", modeA={"load"}}
```
