### ISSUE TITLE
ENH: conda skeleton -t python https://github.com/org/project 

### ISSUE THREAD

**Issue by westurner** [conda/conda#1109]
It would be really convenient to be able to generate a `meta.yml`  w/ `conda skeleton` from:
- a GitHub URL
- a pypi package w/ a "Homepage URL" that matches `github.com` and/or `bitbucket.org/`

Use case: https://github.com/audreyr/cookiecutter/issues/232

```
conda skeleton -t python https://github.com/audreyr/cookiecutter/
```

Where `-t python` would hint that there should be a setup.py found in the root directory.

**Comment by asmeurer** [comment]
conda skeleton pypi already supports building from a url so this should be pretty easy to add using the same logic.

**Comment by westurner** [comment]
Maybe ``github-py`` or ``github-python`` instead of ``-t python``?

**Comment by westurner** [comment]
Is there support for ``hg``?

**Comment by asmeurer** [comment]
conda build has support for hg yes

**Comment by xguse** [comment]
Sooo...... Has this gotten any love?  I REALLY want this to be a thing.  I have a lot of my code that is mostly for personal use as `pip` installable git repos.  Being able to build a conda package with `conda skeleton -t python https://github.com/USER/PROJECT/` would REALLY help me complete my transition from pip/virtaulenv.  If its not too complicated I would even offer to prepare a pull request but I wouldn't mind being pointed in the right direction regarding conda's code etc.

If not from git repos specifically, why not be able to point to a pip installable directory and just use the setup.py as a guide to generate the `meta.yaml`.  This might even be possible but I cant find it any of the docs.

**Comment by westurner** [comment]
On Aug 14, 2015 3:19 PM, "Augustine (Gus) Dunn" <notifications@github.com>
wrote:
>
> Sooo...... Has this gotten any love? I REALLY want this to be a thing. I
have a lot of my code that is mostly for personal use as pip installable
git repos. Being able to build a conda package with conda skeleton -t
python https://github.com/USER/PROJECT/ would REALLY help me complete my
transition from pip/virtaulenv. If its not too complicated I would even
offer to prepare a pull request but I wouldn't mind being pointed in the
right direction regarding conda's code etc.

https://github.com/conda/conda-build/search?utf8=%E2%9C%93&q=skeleton

https://github.com/conda/conda-build/blob/master/conda_build/pypi.py

>
> If not from git repos specifically, why not be able to point to a pip
installable directory and just use the setup.py as a guide to generate the
meta.yaml. This might even be possible but I cant find it any of the docs.

* Host packages with http://doc.devpi.net/latest/

* create a cookiecutter and paste the github uris:
https://github.com/audreyr/cookiecutter/issues/232

* http://conda.pydata.org/docs/building/meta-yaml.html#source-section

**Comment by jakereps** [comment]
```bash
$ conda skeleton pypi --manual-url https://github.com/user/repo/archive/master.zip
```

**Comment by asmeurer** [comment]
Ideally this would work with the real github url and create a recipe that downloads the source from git.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1975
