### ISSUE TITLE
Want to link/Register copied conda environment.

### ISSUE THREAD

**Issue by Psp29onetwo** [conda/conda#11100]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
* [x] I confirmed that it's not related to another project (see the above section)

### What is the idea?
I've moved my conda env to another folder and I want to register or link that moved conda env which I think is not possible after I did a google search.

### Why is this needed
Because anyone who wants to copy and paste the entire conda env folder can register that env on their machine as well.

### What should happen?
As far as I know, If I copy or cut the conda created env folder to another destination then there should be a command to register that copied or moved the folder to conda environments after verifying files.

Like:
> conda register [..path/to/env/directory]

or

> conda link [..path/to/env/directory]

### Additional Context
I've seen conda pack [conda pack](https://conda.github.io/conda-pack/) but it has to zip and unzip the environment I want to simply copy or move the entire env folder and link/register that folder to conda environments.

**Comment by chenghlee** [comment]
This may be an extension to `conda rename` (#3097). However, registering an environment that's been moved may be complicated by having to find a sensible way to re-do prefix replacement and filesystem links.
