### ISSUE TITLE
Miniconda installer fails on aarch64 with CentOS 7. 

### ISSUE THREAD

**Issue by fields** [conda/conda#11107]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Trying to install Miniconda in a docker image based off of the stock CentOS 7 image, the installer fails with a glibc 2.25 dependency. Presumably this won't work because CentOS 7 includes glibc 2.17. This built fine using the x86_64 architecture (everything else the same), but the aarch64 one is failing.

This is the installer:
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh

It gives this error output:
```
Unpacking payload ...
[119] Error loading Python lib '/tmp/_MEImCe6Zl/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEImCe6Zl/libpython3.8.so.1.0)
[122] Error loading Python lib '/tmp/_MEI6pem7s/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI6pem7s/libpython3.8.so.1.0)
```

**Comment by fields** [comment]
Any update on this? Has anyone else been able to confirm this?

**Comment by beeankha** [comment]
Hi @fields thank you for filing this issue! I have been able to recreate the errors with a `centos/aarch64` Docker image; currently investigating possible fixes.

**Comment by chenghlee** [comment]
The linux-aarch64 Miniconda installer and conda packages from Anaconda "defaults" channel currently require glibc >=2.26. They will not work with CentOS 7, Ubuntu 16.04, or Debian 9 ("stretch").

**Comment by beeankha** [comment]
It appears that `conda` is behaving as expected; closing this issue. 

@fields , if you would like to see future support for installation on CentOS 7 `aarch64`, please open a ticket in https://github.com/ContinuumIO/anaconda-issues/

As a follow-up, I will be filing an issue in the [`conda-docs` repository](https://github.com/conda/conda-docs) to request clarification in the [Systems Requirements section](https://docs.conda.io/en/latest/miniconda.html#system-requirements) of the Miniconda documentation.

**Comment by fields** [comment]
Thanks for verifying this. This is quite bad, as CentOS 7 is still supported until 2024 and there are substantial issues with CentOS 8 which make its future uncertain. I will file a request for that.
