### ISSUE TITLE
Updating ipython-qtconsole, and this

### ISSUE THREAD

**Issue by pirsq** [conda/conda#1110]
Traceback (most recent call last):
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 411, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 499, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/home/eric/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 593, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/home/eric/opt/anaconda/conda-meta/ipython-2.3.0-py27_0.json'

~~~~~~~~~~~~~~~~~~~~~

conda info:

Current conda install:

             platform : linux-64
        conda version : 3.8.1
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /home/eric/opt/anaconda  (writable)
  default environment : /home/eric/opt/anaconda
     envs directories : /home/eric/opt/anaconda/envs
        package cache : /home/eric/opt/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False


Close

**Comment by ilanschnell** [comment]
Can other packages be updated without problems?
I would try, the following to solve the problem:
```
$ conda install -f ipython
```

**Comment by pirsq** [comment]
Yes, all other except Spyder updated OK. I tried qtconsole once more and it went fine the second time.

Also, I was finally able to get Spyder to install into a 3.4 environment. For some reason it's not working with 3.3 (this is on 2 computers).  All good for now. Thanks for the reply.

On January 27, 2015 12:56:47 AM EST, Ilan Schnell <notifications@github.com> wrote:
>Can other packages be updated without problems?
>I would try, the following to solve the problem:
>```
>$ conda install -f ipython
>```
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/conda/conda/issues/1110#issuecomment-71593718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ccordoba12** [comment]
One recommendation for the future: always close Spyder before running a `conda update`. Else you'll get errors like the one you saw.

**Comment by ccordoba12** [comment]
Since everything is working correctly for you, I'm going to close this issue.

Thanks for reporting :-)
