### ISSUE TITLE
UnsatisfiableError that is perfectly satisfied

### ISSUE THREAD

**Issue by eli-osherovich** [conda/conda#11117]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
Following is an error that I do not understand....
The version is perfectly satisfied, yet conda raises UnsatisfiableError

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - feature:|@/linux-64::__glibc==2.33=0
  - modin -> omniscidbe4py -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.33
```

**Comment by kenodegard** [comment]
Unfortunately this is not enough detail for us to offer any solutions. Please provide all of the requested information above.

**Comment by eli-osherovich** [comment]
At least, please confirm that I understand the error correctly: conda requires version 2.33 and installed versionn is 2.33. Is this correct?

**Comment by kenodegard** [comment]
The error message is saying that you have `glibc 2.33` installed and that the package `modin` depends on `omniscidbe4py` which in turn depends on `glibc >=2.17,<3.0.a0`. Yes, based on the error message here this appears satisfied (as you have indicated). This indicates that there's some other issue that `conda` was unable to resolve hence we would need additional details to debug.
