### ISSUE TITLE
confusing update error message if -p option spelled incorrectly or does not exist

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1111]
I just tried the following command:

``` bash
# /opt/wakari/miniconda/bin/conda update -p /opt/wakari/wakari-gateway --all
Error: too few arguments, must supply command line package specs or --file
```

The problem was that the path was invalid (in this case, it did not exist), but the error message was confusing to me.  This would also be the error message someone would get if they typed the wrong path in.

**Comment by asmeurer** [comment]
Is this with the latest version of conda? I get `Error: There are no packages installed in the prefix /opt/wakari/wakari-gateway`. And I vaguely remember fixing this already.

**Comment by rilut** [comment]
@asmurer have you solved this issue?
