### ISSUE TITLE
Unable to import cryptography after openssl 3.0.0 is avaliable in conda-forge

### ISSUE THREAD

**Issue by jinxudb** [conda/conda#11111]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
Recently,  conda-forge repo introduced openssl version 3.0.0,

https://anaconda.org/conda-forge/openssl/3.0.0/download/linux-64/openssl-3.0.0-h7f98852_0.tar.bz2

When I run `conda update conda -y`,  openssl 3.0.0 will be installed,  however,  this is a showstopper to import `crypograhphy` package.

I have raised an issue to cryptography team here:   https://github.com/pyca/cryptography/issues/6712 

Their conclusion is conda shouldn't "building against one OpenSSL and then linking against a system OpenSSL."

Our environment:

* RHEL 8.5,
* conda 4.11.0
* Python 3.7

### Conda info
```shell
platform : linux-64
user-agent : conda/4.11.0 requests/2.26.0 CPython/3.7.12 Linux/5.10.47-linuxkit rhel/8.5 glibc/2.28
```

**Comment by jezdez** [comment]
The cryptography package in the main channel is compiled against openssl 1.x and not conda-forge's 3.x. I'd suggest installing cryptography from conda-forge as well to work-around the incompatibility, the pull-request for openssl 3.x support there has been open for a while: https://github.com/conda-forge/cryptography-feedstock/pull/80

One interesting comment there may shed some light on what you'd need to do to get it working locally:

> If cryptography doesn't support openssl 3, could you add a <3 version bound to the recipe? I just installed something that depends on cryptography with anaconda and it pulled in openssl3 from conda-forge rather than 1.1.x, and thus failed with:
>
> ImportError: .../lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0
>
> Pinning openssl<3 solved the problem.

from https://github.com/conda-forge/cryptography-feedstock/pull/80#issuecomment-1001927901

Either way, this isn't a bug in conda, but merely a packaging problem that needs to be solved, which conda, the package manager, can't do anything about. Hope that helps!

**Comment by jinxudb** [comment]
I don't really like the workaround adding "_openssl<3_",  it is easy to add,  but difficult to remove.  will definitely give us trouble later :(
