### ISSUE TITLE
Conda export environment contains local path in the prefix `field`

### ISSUE THREAD

**Issue by mihaiginta** [conda/conda#11114]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
* [x] I confirmed that it's not related to another project (see the above section)

### What is the idea?
When executing `conda env export -f environment.yml` the last line in the `environment.yml` file will always be the field `prefix` that contains the local path to the environment. 

### Why is this needed
When sharing environments, the local path is irrelevant and there is no conda-specific way to remove the prefix field from the file

### What should happen?
It would be nice to have a conda parameter that allows to export an environment file without the prefix field, e.g `conda env export -f --no-prefix environment.yml`

**Comment by kenodegard** [comment]
As a temporary workaround we suggest using `tail` to accomplish this:

```bash
# linux
conda env export | head -n -1 > environment.yml

# macOS (doesn't support negative head)
conda env export | tail -r | tail -n +2 | tail -r > environment.yml
```

**Comment by Bigous** [comment]
Workaround for windows:
```powershell
# Windows
$f=(conda env export) && $f[0..($f.count - 2)] > environment.yml
```
