### ISSUE TITLE
Provide virtual package for nvidia driver version

### ISSUE THREAD

**Issue by hmaarrfk** [conda/conda#11124]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Similar to the `__cuda` package and the `__glibc` package, I think it would be worthwhile to have a package for the nvidia driver version. Certain packages like ffmpeg can make use of the driver given that it is compiled with the right version.

- https://github.com/conda/conda/pull/9358 
- https://github.com/conda/conda/pull/8267

### Why is this needed

The ffmpeg package could be compiled with nvidia headers, but they need to match the system installation.
https://github.com/conda-forge/ffmpeg-feedstock/pull/101

### What should happen?

At install time, if the same package is compiled against multiple versions of the nvidia driver, the one with the most updated version should be chosen.

**Comment by jezdez** [comment]
There is some overlap with adding the ability to specify additional virtual packages using the in-development conda plugins API. See #10131 for the progress.

**Comment by hmaarrfk** [comment]
Closing here them
