### ISSUE TITLE
Registry key left behind after uninstall, breaks CMD

### ISSUE THREAD

**Issue by roelandschoukens** [conda/conda#11125]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
This problem appeared on Windows 10 Home 21H1.

After uninstalling `HKCU\Software\Microsoft\Command Processor` was set to `if exist`. As a consequence CMD will fail to start at all.

This is documented on superuser: [Cmd crashes with exit code 1 after uninstalling anaconda](https://superuser.com/questions/1628947/cmd-crashes-with-exit-code-1-after-uninstalling-anaconda).

Miniconda was installed using the installer from https://docs.conda.io/en/latest/miniconda.html#windows-installers, and uninstalled by using the _Apps & features_ page in Windows settings.

### Conda info
```shell
(other than the problem above I think conda installed and uninstalled successfully.)
```

**Comment by beeankha** [comment]
Hi @roelandschoukens   , I re-filed this issue in the  [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (the place for `conda` installer issues); closing this out, you can track your newly re-filed issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/12938)
