### ISSUE TITLE
distutils deprecation in Python 3.12

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#11136]
### What is the idea?
[PEP 0632](https://www.python.org/dev/peps/pep-0632/) announced the deprecation of the `distutils` package in Python 3.10 and the removal of said package in Python 3.12.  `conda` should be prepared for when this happens.

### Why is this needed
conda will likely break with Python 3.12 if no updates are made. (That or a `distutils` shim package will need to be added as a dependency.)

### What should happen?
Use of `distutils` should be replaced (or supplemented) with non-distutils equivalents; as of the latest `master` @ [commit fb5c95f1f](https://github.com/conda/conda/tree/fb5c95f1f), it's being used in the following places:

```
$ egrep -rnIH '(from|import) distutils' conda
conda/common/path.py:17:from distutils.spawn import find_executable
conda/auxlib/packaging.py:70:from distutils.command.build_py import build_py
conda/auxlib/packaging.py:71:from distutils.command.sdist import sdist
conda/auxlib/packaging.py:72:from distutils.util import convert_path
conda/auxlib/path.py:3:from distutils.sysconfig import get_python_lib
```

**Comment by kenodegard** [comment]
Not to mention where its being used within `conda-build`:

```
$ egrep -rnIH '(from|import) distutils' conda_build
conda_build/bdist_conda.py:11:from distutils.command.install import install
conda_build/bdist_conda.py:12:from distutils.errors import DistutilsOptionError, DistutilsGetoptError
conda_build/bdist_conda.py:13:from distutils.dist import Distribution
conda_build/_load_setup_py_data.py:12:    import distutils.core
conda_build/skeletons/pypi.py:99:+import distutils.core
conda_build/windows.py:10:    from distutils.msvc9compiler import find_vcvarsall as distutils_find_vcvarsall
conda_build/windows.py:11:    from distutils.msvc9compiler import Reg, WINSDK_BASE
```

**Comment by MauritsDescamps** [comment]
Might be of interest: https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html

**Comment by jezdez** [comment]
The use of `find_executable` was fixed in #12550.

**Comment by jezdez** [comment]
> Not to mention where its being used within `conda-build`:
> 
> ```
> $ egrep -rnIH '(from|import) distutils' conda_build
> conda_build/bdist_conda.py:11:from distutils.command.install import install
> conda_build/bdist_conda.py:12:from distutils.errors import DistutilsOptionError, DistutilsGetoptError
> conda_build/bdist_conda.py:13:from distutils.dist import Distribution
> conda_build/_load_setup_py_data.py:12:    import distutils.core
> conda_build/skeletons/pypi.py:99:+import distutils.core
> conda_build/windows.py:10:    from distutils.msvc9compiler import find_vcvarsall as distutils_find_vcvarsall
> conda_build/windows.py:11:    from distutils.msvc9compiler import Reg, WINSDK_BASE
> ```

Most of this was done in #4852.

**Comment by Masterxilo** [comment]
Removal of that package absolutely broke our CI, and we have other issues with 3.12 that other people fact too

https://stackoverflow.com/questions/77247893/modulenotfounderror-no-module-named-distutils-in-python-3-12

https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

we happily downgraded to 3.11 and everything works again. Why does a minor update break so many things?

**Comment by jezdez** [comment]
@Masterxilo I hear you, but I think you misunderstand the situation. The removal of the `distuils` library from the Python standard library happened upstream, [in CPython itself](https://github.com/python/cpython/issues/85454), and doesn't have anything to do with conda, the package manager. This issue here merely documented conda's own reliance on `distuils` to make sure it continues working on Python 3.12 (which it does). I hope that helps!
