### ISSUE TITLE
sort the output of conda info package by version

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1114]
Currently the output of `conda info package` is sorted alphabetically.

**Comment by justlurking** [comment]
I might be interested in taking a shot at this next week. I currently don't find `conda info package` very useful and can think of some ways to make it better. 

Who could I work with to get input / approval for how the modified functionality should work? Some of the ideas I outline below are beyond what I'd be comfortable attempting, but if there's interest, I'm happy to help define a spec and some requirements for a set of related feature enhancements, even if I only deliver a PR for some of the more basic functionality.

For example, I just tested the function on several packages, and found one with several different s/w versions, each of which had several different python version dependencies, going back as far as Python 2.6 (out-of-support for four years now).

I can't imagine the Python 2.6* version of this package is very useful to too many people and I can see the value in suppressing such old versions by default, but perhaps there is a design requirement for this feature to exhaustively list every package version in the defaults channel**?

*Does the enhanced MatchSpec 4.4 allow for sub-searching `conda info package`, e.g. `conda info package y=36`? That could be very useful.

**Speaking of defaults channel, is there a way to specify a non-default channel (e.g. -c conda-forge) to the `conda info` command? Seems like this would also be useful.

Finally, is there an equivalent command that provides details about only a currently installed package? Strikes me another possible logical enhancement to `conda info`.

**Comment by kalefranz** [comment]
> I currently don't find `conda info package` very useful and can think of some ways to make it better.

In conda 4.4 (the 4.4.x git branch, which is what you should target, master is currently 4.5.x) we've basically duplicated functionality between `conda info package` and `conda search --info package`.  The functionality is more consistent with `conda search`, and we may eventually end up deprecating `conda info package`.  Focus on `conda search` first.

> Who could I work with to get input / approval for how the modified functionality should work?

I'm probably the best person right now.

> Does the enhanced MatchSpec 4.4 allow for sub-searching

Yes.  I encourage you to play with it and try it out.  There is an API change to `conda search` in 4.4. The argument is no longer a regex by default, but a MatchSpec. So it unifies the query language among `create`, `install`, `update`, `remove`, and `search` (I guess technically `conda info package` also).

> Speaking of defaults channel, is there a way to specify a non-default channel (e.g. -c conda-forge) to the conda info command?

Try `conda search bioconda::perl*` (there's apparently no perl interpreter in that channel, but a bunch of perl-specific packages).

> Finally, is there an equivalent command that provides details about only a currently installed package? Strikes me another possible logical enhancement to conda info.

That seems to be more logically consistent with what `conda list` does.  And maybe we need a `conda list --info` command that parallels `conda search --info`.

**Comment by kalefranz** [comment]
In conda >=4.4, we sort by package name first, and then by version.
