### ISSUE TITLE
Package interdependencies block usage of `update --all`

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#1115]
For many months now, the `basemap` package requests matplotlib-1.4.0, while since long matplotlib-1.4.2 has been released.
I have enough packages to make it worth-while to use `condo update --all` as a general update procedure (in a safe environment for testing), but having matplotlib-1.4.2 installed is braking the `update --all` function, because basemap has a conflicting requirement.
To be able to use the `--all` flag still, I have been doing this for several months now:
* `conda install basemap`  (downgrades matplotlib)
* `conda update --all`
* `conda install matplotlib` (upgrades it again).

While I do not expect that package managers always keep up to date with all existing updates, I myself want to be able to tell `conda` that a current set of packages is okay for me. I don't know if that makes sense in terms of how conda works, but there must be something better then my above workaround?

**Comment by asmeurer** [comment]
@ilanschnell why does basemap depend on the exact version of matplotlib?

**Comment by ilanschnell** [comment]
I guess nothing which depends on matplotlib should require the exact version.  Let me make a change, which is going to make anything which depends on matplotlib, only depend on the name.

**Comment by michaelaye** [comment]
this works great now! I see that the dependency list of baseman has been updated to only say matplotlib instead of matplotlib 1.4.0. Thanks.

**Comment by asmeurer** [comment]
I've also suggested changes to conda update --all [here](https://github.com/conda/conda/pull/1138) that would make these sorts of issues less likely to fail completely.
