### ISSUE TITLE
Create new package for libmamba integrations

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11152]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
* [x] I confirmed that it's not related to another project (see the above section)

### What is the idea?
The new solver logic will be released experimentally with a separate package so users can opt-in by installing.

### Why is this needed
To allow users to opt-in and test the experimental work.

### What should happen?
A user can install `conda-libmamba-solver` on their `base` environment and select it as the default solver for non-base environment operations.

### Additional Context
Things to take into account:

* Some changes of #10881 involve commits to the conda core code. 
  * This can't be taken to a separate package.
  * That PR should be merged, but it will only contain the glue code for the new solver backend.
* The history of these PRs is useful. Backup branches will be available at `jaimergp/conda` for future investigations if that's needed.

**Comment by jezdez** [comment]
The repo was proposed in the conda community meeting and created at https://github.com/conda-incubator/conda-libmamba-solver 🥳

**Comment by jaimergp** [comment]
Closed by https://github.com/conda-incubator/conda-libmamba-solver/pull/1 🚀
