### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getproxies'

### ISSUE THREAD

**Issue by Cils** [conda/conda#1117]
c:\pyzo2013c\Scripts>conda install -f numpy
Fetching package metadata: An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "c:\pyzo2013c\Scripts\conda-script.py", line 9, in <module>
    load_entry_point('conda==unknown', 'console_scripts', 'conda')()
  File "C:\pyzo2013c\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\pyzo2013c\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\pyzo2013c\lib\site-packages\conda\cli\main_install.py", line 46, in e
xecute
    install.install(args, parser, 'install')
  File "C:\pyzo2013c\lib\site-packages\conda\cli\install.py", line 224, in install
    unknown=args.unknown, json=args.json)
  File "C:\pyzo2013c\lib\site-packages\conda\cli\common.py", line 416, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\pyzo2013c\lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\pyzo2013c\lib\site-packages\conda\utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "C:\pyzo2013c\lib\site-packages\conda\fetch.py", line 177, in fetch_index

    session = CondaSession()
  File "C:\pyzo2013c\lib\site-packages\conda\connection.py", line 60, in __init_
_
    self.proxies = get_proxy_servers()
  File "C:\pyzo2013c\lib\site-packages\conda\config.py", line 299, in get_proxy_servers
    return requests.utils.getproxies()
AttributeError: 'module' object has no attribute 'getproxies'

----------------------------------------
Conda info:

Current conda install:

             platform : win-64
        conda version : unknown
  conda-build version : not installed
       python version : 3.3.2.final.0
     requests version : 1.2.3
     root environment : C:\pyzo2013c  (writable)
  default environment : C:\pyzo2013c
     envs directories : C:\pyzo2013c\envs
        package cache : C:\pyzo2013c\pkgs
         channel URLs : http://conda.binstar.org/pyzo/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\pyzo2013c\.condarc
    is foreign system : False

**Comment by asmeurer** [comment]
Your requests version is too old. Can you show me `conda info -a`.

**Comment by Cils** [comment]
Hi,

C:\pyzo2013c\Scripts>conda info -a
Current conda install:

             platform : win-64
        conda version : unknown
  conda-build version : not installed
       python version : 3.3.2.final.0
     requests version : 1.2.3
     root environment : C:\pyzo2013c  (writable)
  default environment : C:\pyzo2013c
     envs directories : C:\pyzo2013c\envs
        package cache : C:\pyzo2013c\pkgs
         channel URLs : http://conda.binstar.org/pyzo/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\pyzo2013c\.condarc
    is foreign system : False

# conda environments:
#
root                  *  C:\pyzo2013c

sys.version: 3.3.2 |Continuum Analytics, Inc.| (defau...
sys.prefix: C:\pyzo2013c
sys.executable: C:\pyzo2013c\python.exe
conda location: C:\pyzo2013c\lib\site-packages\conda
conda-build: None
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Programme\Oracle\product\11.2.0\client_1;C:\Programme\Oracle\product\11.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\SysWOW64\Empirum;C:\Program Files\MATLAB\R2013b\runtime\win64;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Programme\Oracle\product\11.2.0\client_1;C:\Programme\Oracle\product\11.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System\WindowsPowerShell\v1.0\;C:\Windows\SysWOW64\Empirum;C:\Program Files\MATLAB\R2013\runtime\win64;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Python33
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

I tryed the command: conda install -n root _license but I got again the error: 'module' object has no attribute 'getproxies'

**Comment by asmeurer** [comment]
OK, try `pip install --upgrade requests`.

**Comment by Cils** [comment]
Great it works.
many thanks.
