### ISSUE TITLE
Miniconda 4.11.0 Installer missing?

### ISSUE THREAD

**Issue by corydolphin** [conda/conda#11178]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

It looks like there is no available 4.11.0 installer for miniconda available, and latest does not point to it. Is it possible to have a binary/sh installer built, ideally with Python 3.10? 
https://repo.anaconda.com/miniconda/

### Conda info

```shell
N/a
```

### Additional Context

Thank you all for supporting and building conda! 🙌

**Comment by jezdez** [comment]
Thank you for asking! We're currently working on an update for the miniconda installer containing conda 4.11.0 and plan to make a release soon.

FWIW I'll close this ticket for now since this repo is technically about issues in conda - the package manager - alone. Hope that's okay!
