### ISSUE TITLE
Bash tab completion docs out of date

### ISSUE THREAD

**Issue by zmoon** [conda/conda#11171]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

[The docs page](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/enable-tab-completion.html) still says optional Bash completion support is just deprecated, starting in v4.4, but actually it seems it was *removed* for v4.4.0 (https://github.com/conda/conda/commit/25f58e3546cd055477e38b3dca88bcb7c1d45740).

Related:
* https://github.com/conda/conda/issues/9178
* https://github.com/conda/conda/issues/9975

**Comment by tartansandal** [comment]
Just to note there is support for bash-completion via a conda-forge package (see https://github.com/tartansandal/conda-bash-completion).Pperhaps the docs could be updated?

**Comment by rainu-handshake** [comment]
It seems like this has now been documented? 

```
Conda versions up to 4.3 supports tab completion in Bash shells via the argcomplete package. Bash tab completion has been removed starting with version 4.4.0.
```

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/enable-tab-completion.html

**Comment by timhoffm** [comment]
Since the removal in version 4.4 was in 2017, that description can be removed completely. The current docs don't need to describe  features that are obsolete for more than 5 years.
