### ISSUE TITLE
conda install --no-deps still installing deps when installing tarball

### ISSUE THREAD

**Issue by jolos** [conda/conda#1118]
When running the following command:

`conda install --no-deps ./matplotlib-1.4.0-np18py27_0.tar.bz2 `
You would assume that no dependencies are installed, but conda seems to install the dependencies anyway.

**Comment by jolos** [comment]
fwiw: This seemed to work with conda 3.7.0

**Comment by asmeurer** [comment]
That's because conda used to never install the dependencies of a tarball. This feature was added, but the `--no-deps` flag was neglected.

**Comment by asmeurer** [comment]
Just fixing this issue should be much simpler than fixing that, though. We just need to make it respect the command line flag.

**Comment by cpcloud** [comment]
What is the status here?

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1613
