### ISSUE TITLE
Conda install unable to parse PEP 508 dependency specifications

### ISSUE THREAD

**Issue by mcflugen** [conda/conda#11198]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

I would like *conda* to be able to parse a requirements file that contains dependency specifications as defined in [PEP 508](https://www.python.org/dev/peps/pep-0508/). For example, I would like the following to work,
```
$ cat requirements.txt
some_package ; sys_platform != 'win32' or python_version < '3.10'
$ conda install --file=requirements.txt
```
Ideally, it would be wonderful if *conda* would include the package if the marker evaluates to True and ignore the line otherwise. Less ideal, but still helpful, would be if *conda* could at least able to parse the file but simply ignore the marker and include the dependency regardless of how it would evaluate.

### Why is this needed

This would be helpful to me (and others, I hope) when I want to support both *pip* and *conda* users. That is, I would like users of my packages to be able to install my package's requirements with either *pip* or *conda*. For example, I would like users to be able to do either of the following,
```bash
$ cat requirements.txt
some_package ; sys_platform != 'win32' or python_version < '3.10'
$ pip install -r requirements.txt
```
or
```bash
$ conda install --file=requirement.txt
```
If *conda* could parse such a file, it would allow me to only maintain a single file that contains my package's requirements.

### What should happen?

Given a requirements file that looks like the following,
```
# file: requirements.txt
some_package ; sys_platform != 'win32' or python_version < '3.10'
```
a user should be able to install the requirements in the file with the following,
```bash
$ conda install --file=requirements.txt
```
In this particular example, if the user is on Windows and using Python 3.10 then nothing would be installed but, otherwise, *conda* would install *some_package*.

### Additional Context

To be more concrete about what I think should be done, the following code snippet adds this feature to *conda* (at least for my use case, I haven't done extensive testing),
```python
                 line = strip_comment(line)
                 if ";" in line:
                     from pkg_resources import evaluate_marker
                     ndx = line.index(";")
                     line, marker = line[:ndx].strip(), line[ndx + 1:]
                     line = line if evaluate_marker(marker) else ""
```
I've added the above code in the *specs_from_url* function in *conda/cli/common.py* at the beginning of the `for line in open(path)` loop.

**Comment by basnijholt** [comment]
This _should_ also work like:
```yaml
name: test-pip
channels:
  - conda-forge
dependencies:
  - python
  - pip:
      - qsimcirq; sys_platform=='linux' or sys_platform=='darwin'
```

@mcflugen, I am developing a [package `conda-join`](https://github.com/basnijholt/conda-join) that manages pip and conda dependencies in a single file. Check it out :)

**Comment by mcflugen** [comment]
@basnijholt Amazing! I'll definitely check it out!
