### ISSUE TITLE
Split out MatchSpec into a new library conda-matchspec

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/conda#11234]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Seperate out MatchSpec from conda into a smaller library conda-matchspec that is pip installable so that tool builders can depend on that instead of depending on conda

### Why is this needed

Allows pip installable tools to be able to easily parse conda requirements and specifiers

**Comment by chenghlee** [comment]
I support this idea; among other things, it would also make writing repodata patches much easier (e.g., by avoiding having to re-write version parsing logic).
