### ISSUE TITLE
`devenv`: Install test dependency in base environment, not per-Python version environment

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11252]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

While trying to write a test case for #11174 I noticed that the changes to the development setup done in #11233 contain a major regression I missed in the code review: the test dependencies [aren't installed in the base environment](https://github.com/conda/conda/pull/11233/files#diff-0da549fc3fb0b16c808b4c8172a4d14bf0ab79646b097db802395e88fe62fb1fR181) anymore but instead in a separate sub-environment (I think for ease of use).

I only now realize that this is counter-productive for dev/CI parity (since in CI we are also running the tests from the base environment) and prevents us from running tests that start at the lowest environment stack level (at least with the way the integration tests are written at the moment).

Please roll back the change to the dev environment again while we're in the run-up to the 4.12.0 release so we can consider alternatives again.

I think a way forward mid-term would be to simplify the new start script again to not create a separate environment that gets activated.

### Conda info

```shell
-
```

### Conda config

```shell
-
```

### Conda list

```shell
-
```

**Comment by kenodegard** [comment]
AFAIK we're initialing this non-**base** env as the **base** env (see `conda info --all`), if you run `conda create` it makes it local to this env. What are you seeing that's causing it to not act as a `base` env?
