### ISSUE TITLE
Clarify cmd line help text in "conda search" about what flavor of regex is expected

### ISSUE THREAD

**Issue by pzwang** [conda/conda#1125]
Right now it just says "regex", but it's not clear if this is Python's `re` module, `vim`, `sed`, PCRE, etc...

**Comment by asmeurer** [comment]
We're definitely shelling out to Perl.

**Comment by kerrywatson1** [comment]
@asmeurer can this be closed?

**Comment by asmeurer** [comment]
I guess not. It doesn't say anything about this in the command help.

**Comment by kerrywatson1** [comment]
@asmeurer who does the command help now?

**Comment by asmeurer** [comment]
I guess the conda developers, or you guys.

**Comment by electronwill** [comment]
@pzwang, I want to be sure I understand correctly. We should edit the text that displays when a user runs 'conda search -h' so that it says "Python regular expression" in each of the two places where it currently just says "regular expression"?

**Comment by msarahan** [comment]
@electronwill, we need to be sure that we're specifying the exact kind of regular expression in the documentation.  From Aaron's reply above, it seems we're "shelling out to Perl."  That would mean we need to document it as PCRE, not as Python regular expression.

However, I think the relevant line of code is https://github.com/conda/conda/blob/df086864e6cebf6077e023c29130279edf363d77/conda/cli/main_search.py#L144

Which seems to show that this is a Python regex.  I would appreciate confirmation from one of the other Conda developers, though.

**Comment by electronwill** [comment]
Yeah, I understand that Python, Perl, sed, vim, emacs, bash, and so on all have their own usually slightly different standards for regexes and that we need to explain which we use, but given the company's deep roots in Python, I think Aaron was joking about using Perl and intended to imply that conda uses Python regular expressions. I could be wrong. Shows the need for "/sarcasm" tags, I guess. Regardless, you're exactly right, a quick confirmation from someone in the know is the solution.

**Comment by kerrywatson1** [comment]
Would somebody please make a suggestion on recommended wording?

Appreciate it,
Kerry

_______________________________

Kerry Watson
Documentation and web project manager

[image: Continuum Analytics]
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzsQHMRbPXMfDgQnW2BFNn256dBBnf974Gsn02?t=http%3A%2F%2Fcontinuum.io%2F&si=5890486390751232&pi=95ba9c0a-7134-4ec1-adb3-080612b893a5>

**Comment by electronwill** [comment]
This issue should be fixed by https://github.com/conda/conda/pull/1709 and ready to close.
