### ISSUE TITLE
Incorrect description of `RegisterPython` in Windows installer arguments

### ISSUE THREAD

**Issue by yak1ex** [conda/conda#11266]
### What is the idea?

https://github.com/conda/conda/blob/master/docs/source/user-guide/install/windows.rst describes as:
```
/RegisterPython=[0|1]---Make this the system's default Python. 0 indicates JustMe, which is the default. 1 indicates AllUsers.
```
According to https://github.com/conda/constructor/blob/master/constructor/nsis/main.nsi.tmpl, `RegisterPython` controlls only whether registration into registry is processed or not.
It is controlled by `InstallationType` via `SetShellVarContext` whether `JustMe` or `AllUsers`.

### Why is this needed

This is an official document and similar descriptions have already been spread into other resources, not only in English.
It seems that investigating https://github.com/conda/constructor/blob/master/constructor/nsis/main.nsi.tmpl is the only way to understand actual behavior.

### What should happen?

It should be like:
```rst
* ``/RegisterPython=[0|1]``---Make this the system's default
  Python. 
  ``0`` indicates no registration, which is the default. ``1``
  indicates to be registered as ``/InstallationType`` specifies.
```
I'm not a native speaker of English, so please correct appropriately...

### Additional Context

This issue should be under `type::documentation` label.

**Comment by awwad** [comment]
You're right that this is described confusingly.  Thanks!  We'll make an edit to the documentation.

**Comment by ChrisPanopoulos** [comment]
my pr needs review to proceed . can we arrange it?
