### ISSUE TITLE
Document `conda run`

### ISSUE THREAD

**Issue by astrojuanlu** [conda/conda#11293]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

The `conda run` command is in use by several folks already, as it provides a nice way to:

1. Install `pip` packages inside a conda environment before activation (useful for CI):

```
conda create -n env ...
conda run -n env pip install ...
```

2. Generally run cli applications without going through the hurdles of activating a conda environment, which is a bit painful.

`conda run` has been there for a few years (first created in 2018), and from what I understand, the last major problems were fixed in gh-9665. `conda run --help` provides nice output already, but it's nowhere to be seen in [the list of `conda` commands](https://docs.conda.io/projects/conda/en/latest/commands.html).

### Why is this needed

To help (1) users discover `conda run` by browsing online docs and (2) instructors and educators point to a HTML hyperlink for reference material.

### What should happen?

`conda run` should be listed in https://docs.conda.io/projects/conda/en/latest/commands.html

**Comment by rishabh11336** [comment]
Hey! I am having problem with (Conda Contributor License Agreement)CLA check. I have already signed it but this getting failed, I am trying to make my 1st contribution
Kindly help me with this
https://www.linkedin.com/in/rishabh11336/ DM on linked in
or twitter
https://twitter.com/rishabh11336
![image](https://user-images.githubusercontent.com/67859818/220266612-c0070b43-b8fd-4c2d-91eb-99ce79a1dd5b.png)
