### ISSUE TITLE
Package type

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1132]
We have a problem, which will be amplified quite a bit when the R support gets fleshed out, that there are naming conflicts between different packages from different languages. We already see this a little bit with `lxml`.  I'll use `bokeh` as an example, because we are about to have both Python and R bindings for it.

The solution I've been using so far with R is to prefix all R package names with `r-`, but @kriehl pointed out that many R users aren't going to like this, or will be confused by it. 

My idea (and I'm not sure how this would be implemented yet) would be for each package to optionally have an associated "type". Two packages with the same name can coexist, if they have different types. Whenever a package name is used ambiguously on the command line, conda would ask which type you meant. You could also specify the type using some syntax (like say `r:bokeh`). You could also specify some configuration value to always prefer some given type (like say if you only use Python and don't care about R).

Note that this shouldn't be confused with https://github.com/conda/conda-build/issues/155, which is a completely different feature.

**Comment by asmeurer** [comment]
Here's one suggested way to implement this:

Pick some special character not currently allowed in package names to designate this, and literally name the package `py:bokeh-0.7.1-np19py33_0.tar.bz2`, and have conda manage this internally. 

Upsides of this idea: 

- Quite easy to implement. Currently packages are indexed by their filename, so allowing two packages with the same filename to be different is a big no no. 

- Makes it clear that this distinction is at the UI level (or rather, at the spec level). 

- Since it is only a change at the spec level, no lower level code will need to be changed.

- Should be backwards compatible, minus the UI conveniences. We should probably require dependency specs to specify the full name in order to guarantee this (plus that's a good idea anyway).

Downsides:

- Some packages (like bokeh) already exist, and are named normally, so we'd have to somehow maintain backwards compatibility with them. And I think just deprecating the old way is not good enough, because this sort of thing can happen to any package. I wouldn't want to require every package to have this, though, or even necessarily recommend it.

- The list of potential characters isn't so hot. Windows reserves `<`, `>`, `:`, `"`, `/`, `\`, `|`, `?`, and `*`.  If we want to use the same character in the file name as at the command line, it's harder, because some characters are bad to use because they would have to be quoted in most shells (such as bash), including `>`, `;`, `#`, `$`, `&`, `"`, and `'`. `=` is already used at the command line.  The character we use pretty much has to be a typable ASCII character.

Good choices that remain (that I can think of): `bokeh~py`, `bokeh(py)`, `bokeh[py]`, `bokeh%py`, `bokeh,py` (or the same with the `py` first). Please bikeshed on this.

- Technically speaking, this changes the package spec.

**Comment by asmeurer** [comment]
Another idea: completely ditch this "type" idea and focus on https://github.com/conda/conda/issues/988, and separating different types into different channels. 

**Advantages:**

- Channels are already a well developed feature of Binstar, and are managed by conda well.

- Doesn't change the package name spec at all. The only part of the package spec that changes is the dependency spec.

**Disadvantages:**

- Not so easy, at least with current tooling, to split out packages into different channels.

- One of the original concerns from #988 comes to the forefront here, which is that you end up requiring packages to come from some "official" channel only. Hence, we can't *really* say that the "r" Binstar channel is the same as an "r" type, because only official maintainers of the "r" Binstar channel can upload packages to that channel.  This would also encourage people to depend on the packages from that specific channel rather than on the package alone when they otherwise wouldn't, which I think is a bad thing.

**Comment by asmeurer** [comment]
And for completeness, the idea of using a prefix naming convention, as I've already been doing. With this, we'd have `r-bokeh`:

**Advantages:**

- Requires absolutely no changes to conda at all. 

**Disadvantages:**

- Not very user-friendly, compared to what I am suggesting. We could possibly make the conda CLI know about prefix conventions (or at least the most common ones) and provide a nicer wrapper on them. So, e.g., conda install `nloptr` (instead of `r-nloptr`) "just works", and `conda install bokeh` asks which bokeh (again with the potential to configure "always python" or whatever in the .condarc).  However, any CLI command that can't receive user interaction (like `--yes` or `--json`) would have no choice but to only use literal package names, which could potentially lead to some confusion. 

  It's also worth noting that the existing user experience is not too bad unless there is a name conflict, because conda will suggest name corrections automatically:

```
# conda install nloptr
Fetching package metadata: ...
Error: No packages found in current linux-64 channels matching: nloptr

Did you mean one of these?

    nlopt, r-nloptr

You can search for this package on Binstar with

    binstar search -t conda nloptr
```

- Python elitist. The existing conda packages, which are primarily Python, do not have prefixes, and they probably won't ever grow them.

**Comment by asmeurer** [comment]
Here is a list of all packages that have the same name on PyPI and CRAN, when put in all lowercase:

['abc', 'abn', 'acid', 'ada', 'adhoc', 'ads', 'agree', 'aml', 'ape', 'apt', 'argparse', 'arm', 'arnie', 'ars', 'ash', 'aspect', 'atelier', 'audio', 'audit', 'aws', 'babel', 'baboon', 'bam', 'bamboo', 'bandit', 'barcode', 'bb', 'bear', 'beeswarm', 'benchmark', 'benchmarking', 'bh', 'biotools', 'bizdays', 'bmd', 'boa', 'bold', 'boom', 'boot', 'boss', 'breakpoint', 'breeze', 'ca', 'calibrate', 'caribou', 'cat', 'ccm', 'ccp', 'cdm', 'cec', 'changepoint', 'checkmate', 'checkpoint', 'cheddar', 'circe', 'circular', 'classgraph', 'classify', 'clime', 'cluster', 'cobra', 'cobs', 'codetools', 'commandr', 'compare', 'cop', 'core', 'corpora', 'cosine', 'cosmophotoz', 'couchdb', 'countrycode', 'cpe', 'cr', 'crank', 'crawl', 'css', 'dae', 'dagger', 'dashboard', 'datamap', 'datautils', 'dataview', 'davies', 'dcluster', 'ddd', 'debug', 'descr', 'desire', 'devtools', 'diagram', 'dice', 'differ', 'digest', 'direct', 'distance', 'distillery', 'dna', 'dnet', 'doby', 'docopt', 'dodge', 'dotenv', 'downloader', 'drat', 'ds', 'dse', 'dst', 'dtw', 'dummy', 'dyn', 'edison', 'elastic', 'ema', 'emd', 'emma', 'energy', 'enigma', 'enrich', 'entropy', 'equivalence', 'erp', 'etm', 'events', 'experiment', 'expsmooth', 'extremes', 'ez', 'falcon', 'fast', 'fastcluster', 'fastr', 'features', 'ff', 'fields', 'fimport', 'fincal', 'fingerprint', 'fitsio', 'flam', 'flip', 'flower', 'flux', 'fma', 'fossil', 'frontier', 'fso', 'fun', 'functional', 'gabi', 'gap', 'gcat', 'gdata', 'geomap', 'geonames', 'geotools', 'gimme', 'gitter', 'giza', 'gmm', 'gof', 'graf', 'grain', 'grc', 'grt', 'gse', 'gsw', 'gtools', 'guts', 'h2o', 'hankel', 'hiero', 'histogram', 'hive', 'hiver', 'hoarder', 'holidays', 'hts', 'ice', 'ics', 'ifa', 'ifs', 'igraph', 'im', 'indicoio', 'inflection', 'infra', 'insol', 'interact', 'interval', 'intervals', 'isoweek', 'its', 'jpeg', 'julia', 'klar', 'kohonen', 'korpus', 'lars', 'lazy', 'lctools', 'lda', 'lga', 'lineup', 'lint', 'list', 'lmoments', 'logbin', 'logging', 'loop', 'lsa', 'luca', 'luminescence', 'lunar', 'mac', 'magic', 'magma', 'mail', 'mallet', 'mar', 'markdown', 'marked', 'mass', 'matlab', 'matrix', 'mcs', 'mdr', 'memoise', 'meta', 'metagen', 'metatron', 'metrics', 'metrology', 'mf', 'mime', 'minerva', 'misctools', 'mist', 'mistral', 'mix', 'mixer', 'mm', 'moments', 'monitor', 'monopoly', 'morse', 'mosaic', 'move', 'mpm', 'mrmr', 'mtk', 'mts', 'muscle', 'mvc', 'namespace', 'naturalsort', 'nb', 'netgen', 'neural', 'ngram', 'nlp', 'norm', 'nose', 'numbers', 'ocean', 'odb', 'onemap', 'ops', 'orderbook', 'oz', 'pack', 'paf', 'pan', 'panda', 'parma', 'parsedate', 'party', 'pass', 'pastis', 'pbs', 'pcs', 'pcse', 'pear', 'pequod', 'permtest', 'permute', 'pez', 'picasso', 'piper', 'pips', 'pki', 'plan', 'planar', 'plyr', 'pmr', 'pomp', 'portfolio', 'power', 'powerlaw', 'pp', 'prc', 'prob', 'propagate', 'proto', 'proxy', 'pse', 'psi', 'pso', 'pt', 'pvr', 'pwr', 'pyramid', 'qp', 'qtutils', 'quandl', 'quint', 'quipu', 'rad', 'radar', 'rainbow', 'rambo', 'ramp', 'rapport', 'rattle', 'rebus', 'registry', 'relations', 'relax', 'remix', 'remote', 'rex', 'rgr', 'ringbuffer', 'rjson', 'rose', 'rpdb', 'rsa', 'sam', 'sampling', 'samurai', 'sandwich', 'sas7bdat', 'scales', 'scio', 'scraper', 'scrypt', 'sel', 'sequential', 'settings', 'sfa', 'shiny', 'ship', 'shrink', 'shuffle', 'simpletable', 'single', 'sis', 'skewt', 'smart', 'smcp', 'smr', 'sms', 'snapshot', 'snow', 'snptools', 'solar', 'solr', 'sp', 'space', 'spam', 'spark', 'sparql', 'spartan', 'spate', 'spc', 'spe', 'spi', 'spider', 'spin', 'spot', 'sprinter', 'sqlshare', 'squash', 'sse', 'sss', 'star', 'stellar', 'stem', 'stm', 'storm', 'stosim', 'strap', 'stream', 'sudoku', 'survey', 'swirl', 'symbols', 'synth', 'tables', 'tau', 'tensor', 'tess', 'tester', 'tiger', 'timedate', 'timeline', 'timemachine', 'timeseries', 'titan', 'tm', 'toaster', 'tolerance', 'topmodel', 'track', 'translate', 'treemap', 'triangle', 'trotter', 'trueskill', 'tsne', 'tumblr', 'tvd', 'tvm', 'twiddler', 'twitter', 'unittest', 'uplift', 'urltools', 'useful', 'uuid', 'v8', 'webutils', 'wq', 'xkcd', 'xlsx', 'yaml', 'yhat']

There are 437 of them. That's from a total of 54977 PyPI packages and 6275 CRAN packages.

**Comment by asmeurer** [comment]
Here's the same list (possibly not entirely accurately) sorted by PyPI total download count (I think the 0s might be because they don't host on PyPI):

{nose: 18765971, argparse: 1710864, docopt: 1443032, rsa: 499651, uuid: 352479, gdata: 245906, commandr: 91337, pyramid: 89962, scrypt: 67470, tables: 56932, flower: 51114, logging: 43971, lazy: 40178, intervals: 27940, powerlaw: 27269, storm: 27100, twitter: 25456, functional: 23362, inflection: 20243, cobs: 19834, debug: 19785, isoweek: 18933, sse: 14919, aml: 13906, meta: 13682, timeline: 13243, aws: 12431, ngram: 12032, fastcluster: 10914, single: 10731, interval: 9620, tolerance: 8945, dyn: 8753, experiment: 8129, synth: 8037, geotools: 6877, registry: 6828, panda: 6308, shrink: 6234, pbs: 6075, audit: 5523, unittest: 5510, rose: 5451, sms: 5324, lda: 4860, planar: 4763, caribou: 4757, dotenv: 4435, hiver: 4337, mime: 4314, twiddler: 4167, metagen: 4167, compare: 4153, spc: 4098, radar: 3978, rad: 3955, treemap: 3911, sss: 3765, triangle: 3739, rapport: 3559, fingerprint: 3474, samurai: 3457, dagger: 3404, swirl: 3373, cpe: 3355, bamboo: 3284, mcs: 3226, spark: 3170, solr: 2981, hive: 2978, solar: 2952, igraph: 2936, pki: 2917, benchmark: 2834, stream: 2806, css: 2742, rpdb: 2716, boot: 2662, tsne: 2652, arnie: 2650, classify: 2637, boom: 2563, codetools: 2492, desire: 2483, rainbow: 2454, digest: 2454, barcode: 2447, bb: 2437, lmoments: 2401, metrics: 2381, morse: 2379, simpletable: 2353, tiger: 2326, magma: 2310, gabi: 2277, grain: 2277, benchmarking: 2244, its: 2237, plyr: 2211, dae: 2210, namespace: 2192, sam: 2148, flam: 2148, grc: 2132, lsa: 2112, cobra: 2105, squash: 2075, translate: 2055, etm: 2020, fma: 1994, shiny: 1988, mpm: 1970, gse: 1969, scraper: 1962, lars: 1926, cluster: 1920, ops: 1915, grt: 1910, stem: 1875, cop: 1863, fun: 1855, sandwich: 1851, neural: 1827, mrmr: 1814, baboon: 1801, countrycode: 1788, track: 1758, mixer: 1755, sp: 1753, shuffle: 1752, gsw: 1745, datautils: 1726, hiero: 1725, mass: 1715, prob: 1714, ramp: 1664, hoarder: 1656, lineup: 1637, plan: 1630, bandit: 1626, relations: 1612, fimport: 1597, toaster: 1593, quipu: 1535, spot: 1535, entropy: 1530, metrology: 1520, falcon: 1502, descr: 1482, trueskill: 1478, survey: 1440, star: 1434, korpus: 1426, matrix: 1423, memoise: 1417, biotools: 1413, v8: 1411, bold: 1400, ringbuffer: 1388, smr: 1386, guts: 1379, classgraph: 1377, pez: 1374, luca: 1370, rebus: 1340, move: 1323, pwr: 1317, ice: 1309, graf: 1307, gap: 1302, ship: 1292, spartan: 1283, piper: 1270, pan: 1266, features: 1253, xkcd: 1223, fso: 1195, mvc: 1168, lctools: 1154, norm: 1154, edison: 1153, stm: 1141, hankel: 1140, klar: 1139, interact: 1136, sel: 1135, gimme: 1129, bmd: 1127, naturalsort: 1125, ape: 1124, rambo: 1124, uplift: 1123, pomp: 1114, mts: 1103, geomap: 1090, dst: 1087, urltools: 1086, dummy: 1053, holidays: 1050, proxy: 1041, marked: 1041, dataview: 1006, dtw: 999, downloader: 986, calibrate: 976, parsedate: 976, mm: 973, rjson: 950, quint: 927, ds: 926, spi: 917, pastis: 913, ads: 901, elastic: 897, dse: 880, propagate: 873, clime: 859, titan: 850, stellar: 835, tvm: 819, energy: 807, pmr: 806, differ: 805, webutils: 803, dice: 801, ccm: 781, parma: 766, sprinter: 765, julia: 746, logbin: 723, matlab: 719, mdr: 711, circular: 700, ics: 685, remix: 674, frontier: 669, smcp: 663, lunar: 648, kohonen: 621, sfa: 607, mf: 605, ccp: 598, dodge: 589, gof: 582, metatron: 552, bizdays: 551, dna: 546, fitsio: 529, diagram: 511, mtk: 509, sis: 492, drat: 492, cheddar: 484, breakpoint: 476, fields: 475, spate: 463, pequod: 451, stosim: 443, boss: 423, sequential: 411, distillery: 404, tess: 398, flux: 390, onemap: 382, cec: 381, geonames: 375, nb: 374, mist: 372, power: 338, dnet: 329, gitter: 325, ddd: 322, checkmate: 310, topmodel: 294, mar: 245, audio: 235, expsmooth: 234, sas7bdat: 229, tvd: 224, useful: 218, ifs: 158, changepoint: 139, netgen: 118, yhat: 100, scales: 21, wq: 7, davies: 6, mac: 6, h2o: 5, giza: 5, space: 4, lint: 3, qtutils: 2, atelier: 2, mistral: 2, crank: 2, ifa: 1, ez: 1, breeze: 0, xlsx: 0, magic: 0, babel: 0, im: 0, snapshot: 0, ars: 0, psi: 0, permute: 0, tau: 0, strap: 0, boa: 0, agree: 0, skewt: 0, tumblr: 0, scio: 0, devtools: 0, minerva: 0, checkpoint: 0, cat: 0, histogram: 0, lga: 0, tester: 0, pvr: 0, pse: 0, settings: 0, aspect: 0, party: 0, dashboard: 0, extremes: 0, proto: 0, qp: 0, gcat: 0, beeswarm: 0, enrich: 0, crawl: 0, couchdb: 0, spider: 0, snptools: 0, events: 0, mail: 0, symbols: 0, permtest: 0, rgr: 0, relax: 0, pt: 0, nlp: 0, oz: 0, cr: 0, spin: 0, ema: 0, markdown: 0, equivalence: 0, apt: 0, odb: 0, emma: 0, tm: 0, indicoio: 0, insol: 0, orderbook: 0, rattle: 0, mallet: 0, trotter: 0, sampling: 0, sudoku: 0, pips: 0, timedate: 0, erp: 0, pear: 0, loop: 0, misctools: 0, infra: 0, mix: 0, distance: 0, spam: 0, muscle: 0, abc: 0, core: 0, yaml: 0, monitor: 0, gtools: 0, ash: 0, list: 0, sqlshare: 0, sparql: 0, fastr: 0, mosaic: 0, smart: 0, bam: 0, adhoc: 0, dcluster: 0, cosine: 0, pp: 0, acid: 0, pass: 0, gmm: 0, timeseries: 0, ff: 0, quandl: 0, pcs: 0, fossil: 0, fast: 0, circe: 0, emd: 0, ca: 0, picasso: 0, jpeg: 0, cosmophotoz: 0, pcse: 0, corpora: 0, numbers: 0, bear: 0, doby: 0, snow: 0, datamap: 0, luminescence: 0, arm: 0, tensor: 0, spe: 0, prc: 0, ada: 0, flip: 0, ocean: 0, paf: 0, direct: 0, moments: 0, bh: 0, cdm: 0, fincal: 0, hts: 0, pso: 0, portfolio: 0, pack: 0, monopoly: 0, enigma: 0, rex: 0, timemachine: 0, abn: 0, remote: 0}

So at least those first few packages are worrisome.

**Comment by amfarrell** [comment]
Brainstorming here, one possible variant on #988 might be requiring channels to be type-homogenous. Then, if you depend on a uuid package of type 'R', then it must come from a channel of type 'R'. However, what happens then if you run `conda install uuid` and have two channels of different type that conda could install from?
* Conda responds that this is ambiguous and requires you to pass --channel or --type. This is an annoying, if safe, UI for a single package.
* Your conda environment also has a type and will only look in channels of that type. I can't quite put my finger on why this seems like the wrong way to do it.
* Your conda environment has a default type but and will look at channel of that type first and then fall back to other channel types. This fails silently and dangerously if you think a package in the default type exists but it does not.

Also, given that existing channels are hetrogenous, that would require some sort of migration script to split them up.

**Comment by bkreider** [comment]
I really like type information even if it doesn't completely solve all of the issues.  The Anaconda Cluster team is writing salt states as conda packages, and it would be nice to tag them in some way as salt packages.

I'm -1 on channels being typed, because we have a mix of python and salt packages on our release channel.  Channel-type seems like an implementation detail rather than something we want to foist onto users.

**Comment by ilanschnell** [comment]
I think that naming the R and Python differently is the most feasible solution, maybe with conda doing some special things, such as prepending 'r-' to the package name when you type something into the command line and have R installed.  How this exactly should look like, I'm not sure about, but underneath all package names would be unique and no low level changes to conda would be required.

**Comment by asmeurer** [comment]
I'm also currently leaning towards this solution.

**Comment by kalefranz** [comment]
This will be handled with conda ecosystem namespaces.  @mcg1969 has written out a spec https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1
