### ISSUE TITLE
anaconda fails during install on arm64 architecture (raspbian64 on pi400) with arm64 linux installer "Anaconda3-2021.11-Linux-aarch64.sh : ligne 408 :  1962 Instruction non permise "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs"

### ISSUE THREAD

**Issue by teoverton** [conda/conda#11339]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Anaconda3 will now be installed into this location:
/home/pi/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/pi/anaconda3] >>>                 
PREFIX=/home/pi/anaconda3
Unpacking payload ...
Anaconda3-2021.11-Linux-aarch64.sh : ligne 408 :  1962 Instruction non permise "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs

What should have happened?
Anaconda should have completed install. Instead exits without finishing.

### Conda info

```shell
install fails so conda command not recognised
```

### Conda config

```shell
install fails so conda command not recognised
```

### Conda list

```shell
install fails so conda command not recognised
```

### Additional Context

There is a similar report (#11141) but that report has 2 error messages the first being a core dump and the report is titled that way.  It has also been relegated to support instead of bug.  This bug report is necessary to separate this specific issue and have it resolved as the bug that it is  Any workaround would be greatly appreciated.

**Comment by teoverton** [comment]
computer: pi 400
operating system: raspbian64
installer: Anaconda3-2021.11-Linux-aarch64.sh

**Comment by Python-37** [comment]
You could use an older version of installer, like 2021.05, I met the same issue while I installing Miniconda, use an older version (4.9.2) works fine.
