### ISSUE TITLE
Check if conda clean deletes log files

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11345]
### What happened?

@beckermr wrote on Slack:

> Another question on the logs. Are those cleaned up periodically or do I need to do that myself?

We should check if `conda clean` does indeed delete the logs in `.logs` and if not what would need to be done to enable it.

**Comment by kenodegard** [comment]
Even though the logfile is only written to the first writeable `context.pkgs_dirs` location we might as well check all `context.pkgs_dirs` locations just in case.

**Comment by kenodegard** [comment]
The clean command also doesn't correctly handle `--dry-run`; (1) it's not uniformly checked before removing stuff, and (2) it's only in effect if also `--json` which renders all "normal" usage of `--dry-run` **not** a dry-run:
https://github.com/conda/conda/blob/d13f2f533862ff5cdf91bab80d214f2f0cf7dbce/conda/cli/main_clean.py#L69-L70
