### ISSUE TITLE
Drop Python 3.6 Support

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11358]
### Summary

Python 3.6 reached EOL on 23 Dec 2021.

### Linked Issues & PRs
- https://github.com/conda/conda/pull/11364 
- Remove Python 3.6 references (e.g. `setup.py`)
- Include announcement in release notes

**Comment by jezdez** [comment]
As a point of reference, Anaconda has stopped regularly building [Python 3.6 packages when Python 3.10 was released](https://anaconda.cloud/anaconda-repo-news). That's just another data point for this to be done rather sooner than later.

**Comment by jaimergp** [comment]
conda-forge also dropped it recently.
