### ISSUE TITLE
[Windows] activate doesn't work on Powershell

### ISSUE THREAD

**Issue by keisuke-nakata** [conda/conda#1136]
I found that `activate envname` doesn't work on Powershell.

On cmd.exe it works well: 
```cmd
>activate ver2007
Activating environment "ver2007"...

[ver2007] >python --version
Python 2.7.8 :: Anaconda 2.1.0 (64-bit)

[ver2007] >deactivate
Deactivating environment "ver2007"...

>python --version
Python 3.4.1 :: Anaconda 2.1.0 (64-bit)
```

But in Powershell it doesn't work:
```cmd
PS > activate ver2007
Activating environment "ver2007"...
PS > python --version
Python 3.4.1 :: Anaconda 2.1.0 (64-bit)
PS > deactivate
PS > python --version
Python 3.4.1 :: Anaconda 2.1.0 (64-bit)
```

What confused me is that it says "Activating environment" on Powershell
but actually it didn't.
It's ok to use cmd.exe to switch environments, but for beginners (like me), 
it should say "don't use powershell, try cmd.exe" or something.

**Comment by asmeurer** [comment]
This is a known issue https://github.com/conda/conda/issues/626
