### ISSUE TITLE
Document the `#!final` flag for condarc options

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#11377]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

The `#!final` flag for condarc options is noted in an [old Anaconda blog post](https://www.anaconda.com/blog/conda-configuration-engine-power-users), but as far as I can `grep`, appears nowhere in [the project documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html).

As of conda 4.12.0, this flag still works and is particularly useful in multi-user or managed installations, so it should be described in the conda project documentation.

### Conda info

```shell
N/A (documentation issue)
```

### Conda config

```shell
N/A (documentation issue)
```

### Conda list

```shell
N/A (documentation issue)
```

**Comment by jezdez** [comment]
@kathatherine Let's take a look at the blog post above and move the content or even the whole thing into the conda docs.

**Comment by jonashaag** [comment]
Please reopen this as it is not fixed
