### ISSUE TITLE
Allowing conda installation with `/InstallationType=JustMe` with non-ascii user directory names

### ISSUE THREAD

**Issue by temeddix** [conda/conda#11370]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

If the user directory is `C:/Users/SomeUserName` then conda is installed properly.
If the user directory is `C:/Users/User木` then conda is not installed at all.
This is because conda still prevents non-ascii user directory names because it says some packages do not support non-ascii user directory names. However, since Python 3.0 all strings are treated as unicode and the case where the package makes error due to the folder structure is rare. Shouldn't conda be installed even if the user directory contains non-ascii characters?

### Why is this needed

Non-alphabetical users usually have user directory names with non-ascii characters. This is why it's needed.
<img width="416" alt="화면 캡처 2022-03-26 230306" src="https://user-images.githubusercontent.com/66480156/160242990-73df2baa-98fb-4b4c-9fb8-3aca7fcc26c1.png">

### What should happen?

Non-alphabetical users should be able to install conda on their machine(not as allusers)

**Comment by travishathaway** [comment]
We believe this is related to the following issue: https://github.com/conda/conda/issues/11370

Please follow this for any future updates.
