### ISSUE TITLE
Cannot install MiniConda 3 on Raspberry OS 64-bit

### ISSUE THREAD

**Issue by 4535jacks** [conda/conda#11371]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I tried to install Miniconda 3 on a Pi400 running Raspberry OS 64-bit using bash.  I accepted the T&Cs and during unpackaging got the following message:

Unpacking payload ...
Miniconda3-py39_4.11.0-Linux-aarch64.sh: line 417: 12321 Illegal instruction "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs

My system is running Python 3.9

### Conda info

```shell
bash: conda: command not found
```

### Conda config

```shell
conda config --show-sources
```

### Conda list

```shell
conda config --show-sources
```

**Comment by beeankha** [comment]
Hi @4535jacks , thanks for filing this issue. We currently no longer build installers for this architecture; one option you can try is to use the old installer (`http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh`) and then upgrade `conda` once it's installed.

**Comment by tylermneher** [comment]
> Hi @4535jacks , thanks for filing this issue. We currently no longer build installers for this architecture; one option you can try is to use the old installer (`http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh`) and then upgrade `conda` once it's installed.

Just tried myself and the installation fails with status "ERROR:
cannot execute native linux-armv7l binary, output from 'uname -a' is:
Linux neherseaside-house-pi4 5.13.0-1022-raspi #24-Ubuntu SMP PREEMPT Wed Mar 16 07:19:33 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux"

**Comment by beeankha** [comment]
You could try the `linux-aarch64` installer [here](https://github.com/conda-forge/miniforge#download), though please keep in mind this is the `conda-forge` miniforge installer and not supported by Anaconda, Inc.
