### ISSUE TITLE
Miniconda3-latest-Linux-aarch64.sh: line 417:  3913 Illegal instruction

### ISSUE THREAD

**Issue by pauljurczak** [conda/conda#11394]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I run the most current installer from https://docs.conda.io/en/latest/miniconda.html on Raspberry Pi 4 Model B Rev 1.4 with current Debian GNU/Linux 11 (bullseye) aarch64 and it failed with this output:
```
[/home/pi/miniconda3] >>> 
PREFIX=/home/pi/miniconda3
Unpacking payload ...
Miniconda3-latest-Linux-aarch64.sh: line 417:  3913 Illegal instruction     "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs
```
I verified SHA256 hash for installer file.

**Comment by travishathaway** [comment]
Hi @pauljurczak,

Thanks for reporting this. This is a known issue: https://github.com/conda/conda/issues/11395

As I work around, I suggest checking out the miniforge conda installer here: https://github.com/conda-forge/miniforge#download  Please keep in mind this is from the `conda-forge` project and doesn't receive official support from Anaconda Inc.
