### ISSUE TITLE
linux-64/zlib-1.2.12 missing .so dynamic lib

### ISSUE THREAD

**Issue by kftsehk** [conda/conda#11417]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

New `linux-64/zlib-1.2.12` build in anaconda channel is missing dynamic library `libz.so.*`, only `libz.a` is available.

[linux-64/zlib-1.2.12-h7f8727e_0.tar.bz2](https://anaconda.org/anaconda/zlib/1.2.12/download/linux-64/zlib-1.2.12-h7f8727e_0.tar.bz2) 

```
(base) [kftse@localhost zlib-1.2.12-h7f8727e_0]$ find
.
./info
./info/run_exports.json
./info/files
./info/hash_input.json
./info/index.json
./info/has_prefix
./info/paths.json
./info/about.json
./info/git
./info/recipe
./info/recipe/bld.bat
./info/recipe/meta.yaml.template
./info/recipe/conda_build_config.yaml
./info/recipe/meta.yaml
./info/recipe/build.sh
./info/recipe/license.txt
./info/test
./info/test/run_test.sh
./info/licenses
./info/licenses/license.txt
./include
./include/zconf.h
./include/zlib.h
./lib
./lib/pkgconfig
./lib/pkgconfig/zlib.pc
./lib/libz.a
```

**Comment by travishathaway** [comment]
Hi @kftsehk,

Thanks for issue. Unfortunately, this is not the correct place for your issue.

Please file an issue here instead: [https://github.com/ContinuumIO/anaconda-issues/issues](https://github.com/ContinuumIO/anaconda-issues/issues)

Regards,
