### ISSUE TITLE
Failing to build conda dependency from scratch on mips64el debian

### ISSUE THREAD

**Issue by luyanaa** [conda/conda#11429]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Background: 
I am personally working on an experimental mips64el build for conda. 

How to reproduce the problem: 
System: Debian 10 mips64el port (loongson64_debian10_en_20200525.zip) from debian mips64el community
When executing python setup.py install, ruamel-yaml-conda 's python setup.py egginfo throw "ValueError: 'ruamel_yaml/ext/_ruamel_yaml.pyx' doesn't match any files"
Package Related: ruamel.yaml: both the Debian "python3-ruamel.yaml/oldstable 0.15.34-1+b1 mips64el", and the pip one ruamel.yaml.clib & ruamel.yaml. 

Result:
Failing to build ruamel-yaml-conda. 

### Additional Context

Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-biu59k5m/ruamel-yaml-conda_e5ab6fbf4b2d4c5cbeddcfeac9266624/setup.py", line 35, in <module>
          ext_modules=cythonize(extensions),
        File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 977, in cythonize
          aliases=aliases)
        File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ruamel_yaml/ext/_ruamel_yaml.pyx' doesn't match any files

**Comment by luyanaa** [comment]
Working on this problem further, finding that problem might be in setup.py of ruamel-yaml-conda. 
```python
extensions = [Extension("ruamel_yaml.ext._ruamel_yaml",
                        ['ruamel_yaml/ext/_ruamel_yaml.pyx'],
                        libraries=['yaml'],
                        library_dirs=library_dirs,
                        include_dirs=[os.path.join(PREFIX, 'include')],
                        runtime_library_dirs=[] if sys.platform == 'win32' else library_dirs)]

setup(
# ... 
    ext_modules=cythonize(extensions),
# ... 
)
```

But there's no `_ruamel_yaml.pyx` at ruamel_yaml/ext. Instead, only a _ruamel_yaml.c present. Using `#` to commentize the line allows me to build this wheel and conda, but `AttributeError: module 'ruamel_yaml' has no attribute 'representer'` will be met when using most conda commands.

**Comment by core3750x** [comment]
Same thing here:

`ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v33jrpnt/ruamel-yaml-conda_6f3cb2fac12245d6b7cf489c3e13bc37/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v33jrpnt/ruamel-yaml-conda_6f3cb2fac12245d6b7cf489c3e13bc37/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0tbt0lb_
         cwd: /tmp/pip-install-v33jrpnt/ruamel-yaml-conda_6f3cb2fac12245d6b7cf489c3e13bc37/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v33jrpnt/ruamel-yaml-conda_6f3cb2fac12245d6b7cf489c3e13bc37/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/94/ef/31bfa8456e01ff13d8d98bdbc80ab2e592c830e52ccaff62c35d5f890357/ruamel_yaml_conda-0.15.80.tar.gz#sha256=d0d3f33dfc40085e46de6729b64c2792755504a899ef1ab2e55233f882df9566 (from https://pypi.org/simple/ruamel-yaml-conda/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by reatang** [comment]
see: https://github.com/llv22/ruamel_yaml_conda-0.15.80
