### ISSUE TITLE
Debian package is not up-to-date - Need 4.12.0

### ISSUE THREAD

**Issue by samruddhikhandale** [conda/conda#11427]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I want to install `conda 4.12.0` from Debian repository - https://repo.anaconda.com/pkgs/misc/debrepo/conda, but it is not available.

Could you help add the latest version ?  

### Conda info

```shell
NA
```

### Conda config

```shell
NA
```

### Conda list

```shell
NA
```

### Additional Context

NA

**Comment by beeankha** [comment]
Hi @samruddhikhandale , thank you for filing this issue! Unfortunately, this ticket is off-topic for this repo.

If you are still encountering this problem, please open an issue in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where `conda` package issues are addressed.
