### ISSUE TITLE
Is there currently a way to upload conda packages to a Nexus private repo and then download them via conda?

### ISSUE THREAD

**Issue by scaladevspark** [conda/conda#11445]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Is there currently a way to upload conda packages to a Nexus private repo and then download them via conda? Thanks a lot!

### Why is this needed

Nexus currently seems to support only pip, not sure about conda.

### What should happen?

Be able to upload conda packages to a Nexus private repo and then download them via conda

**Comment by LtDan33** [comment]
Unfortunately, this issue is outside the scope of support we offer via GitHub;
if you still need support for this,
please post details to the [Nucleus forums](https://community.anaconda.cloud/).
