### ISSUE TITLE
Deleting an environment is also super slow.

### ISSUE THREAD

**Issue by MausamGaurav** [conda/conda#11449]
### What happened?

I am trying to simply remove an environment. My environment is on a shared drive. So I was using the below command:

```
conda env remove --prefix P:\......\my_env
```

I see the below message:
Remove all packages in environment P:\...\my_env

The message remains on the screen for at least 5-10 minutes.

Why does this take so much time? Shouldn't this mean simply deleting the environment and making a couple of changes in some conda files?

### Conda info

```
N/A
```

### Conda config

```
N/A
```

### Conda list

```
N/A
```

### Additional Context

N/A

**Comment by LtDan33** [comment]
Can you provide more info? When you say : 

> The message remains on the screen for at least 5-10 minutes.

Do you mean the prompt doesn't reappear in that time? 

Also, the other info in the ticket 'not applicable' is useful as it helps us know what your setup is. Some like `Conda list` would of course need to be done prior to deleting the environment.

If you don't supply package names then it will delete the path and then unregister the environment. This should be quick but there are a few reasons why this could take a while but one could be if there are a large number of files/packages in the env hence why it would be useful to see what the conda list command shows before you try and remove the env.
