### ISSUE TITLE
CEP 1: Replacing root environment with default environment

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1145]
https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment

**Comment by asmeurer** [comment]
Why would Anaconda be different from Miniconda?

**Comment by asmeurer** [comment]
I think you are conflating two issues here, which is quite confusing, as it (incorrectly) makes it sound like they are both required to fix all the issues you bring up. One issue is putting conda in a separate environment from the default one (https://github.com/conda/conda/issues/1022), and one is changing how conda resolves the root environment location (https://github.com/conda/conda/pull/1093).

**Comment by asmeurer** [comment]
I think fixing #1022 is only a matter of putting conda in a special environment (like say `_conda`), and keeping the root environment as the default (so the root environment would be `sys.prefix/../`). We would also probably special case `conda update conda` to mean `conda update -n _conda conda`. 

The only issue here is the difficulty of changing existing installations (something which I'm not clear if your proposal even addresses).

**Comment by asmeurer** [comment]
OK, going to try numbering these to help keep track of them :grinning: 

1. Why would Anaconda be different from Miniconda? (I already asked this above)
2. What would be the resulting line in bashrc with this proposal?
3. Regarding question 2, what about Windows?
4. Can you explain what your conception of `conda init` is? I feel like your conception of it is different from what it currently does. 
5. In a similar vein, I'm unclear how this affects `pip install conda`. Note that the main fundamental issue with `pip install conda` is that the Python is not managed by conda (which is basically by definition). 
5. Some of your activate issues could be solved by https://github.com/conda/conda/issues/813 (there's a lot of stuff in that issue, but the crux of it is to replace `deactivate`'s path mangling with swapping out `PATH` with `OLD_PATH`, which was set by `activate`). 
6. If you were going to completely reimplement conda in another language, why would you even need to access conda at all? If this were truly done, Python would not even be needed.
7. With this proposal, what files would be in the `~/anaconda` directory (say, with a default installation)?
8. Wait, what exactly does the `--system` flag do? Does the "system level" mean, e.g., `/usr/`? If so, -100. If not, that's a bad name. 
9. Accordingly, I don't understand what the system type means. It makes a package uninstallable??

**Comment by ilanschnell** [comment]
Is the goal to make it so that the root environment does not contain conda anymore (because changes to the root environment might break conda)?  Conda itself always ensures that conda and it's dependencies are installed into the root environment.
Which specific current problem does this CEP solve?  I guess I'm confused about the objective.

**Comment by asmeurer** [comment]
Something else that Ilan pointed out to me is that conda being in the root environment makes it easy to keep conda up to date (because we just inject it into the dependencies).

**Comment by ilanschnell** [comment]
A major design decision to have conda in the root environment was that when you install Anaconda you get only a single root environment.  For many people this is enough, and they don't have to worry about the concept of multiple environments.

**Comment by tswicegood** [comment]
Going to respond in one comment and quote the relevant parts.

> Why would Anaconda be different from Miniconda?

This is based on my understanding of the two and their different audiences: Anaconda is bootstrap Conda and populate it with the entire scientific Python stack.  The goal of downloading Anaconda is to have everything ready-to-use.  Miniconda is meant when you need to bootstrap Conda onto a system without Python or where you can't write to the system Python using something like `pip install conda`.

The only code other than Conda that ships with Miniconda is Python and that's only shipped because Conda needs Python to run.  We could create a default environment with just Python in it.  I don't see any problem in that, but for the cases where I've used Miniconda (mostly Wakari) I just wanted the ability to run `conda` commands to create the environments that I needed.

> I think you are conflating two issues here, which is quite confusing, as it (incorrectly) makes it sound like they are both required to fix all the issues you bring up. One issue is putting conda in a separate environment from the default one (#1022), and one is changing how conda resolves the root environment location (#1093).

You're correct in identifying those as separate issues.  They are and they can both be solved separately.  Where I think they're connected is that conda has to be installed into a root environment because it uses `sys.prefix` to resolve its location.  That's what gives rise to the concept of a system environment (open to a better name to avoid overloading the term environment).

I should probably make it more clear.  Let me try restating and see if this makes more sense:

---

Anaconda and Miniconda should create a so-called system environment that is always on the PATH.  Ideally, for backwards compatibility, this would default to what is currently called the root environment.  Things should not be allowed to install into that environment unless they have a `type` of `system` (for example, conda, conda-build, conda-env) or the user specifically overrides that behavior.

For pip-based installations, we don't worry about this system environment, though we expose the mechanism for creating that environment via a command like: `conda create --system` which would move conda over to that and walk the user through updating their PATH appropriately.  It should be noted that `conda update --system conda` should not work in this type of deployment without converting to a more standard conda-like environment.

---

Does that make it more clear or less?

My goal is to take Conda out of the environments and such that it manages.  Once we make that a separate concern, then conda is focused on manipulating files that exist in a specified place that's addressed by: 1) environment variable, 2) configuration; 3) convention.  This makes it easier to ensure that the conda system I'm looking at from Node.js is the same one that Python sees.  Otherwise, I have to ask the Python version.

Combining these two issues is to focus on the benefits of that goal rather than focusing on a fix for one.

---

As I got to this point the rest of the comments came in:

> 2. What would be the resulting line in bashrc with this proposal?


This depends on where we end up with code located.  Let's assume `~/.conda` becomes the default location for everything and that's where Anaconda and Miniconda initialize themselves.

```bash
export PATH=$HOME/.conda/bin:$PATH
source activate $(conda config --get core.default_env)
```

> 3. Regarding question 2, what about Windows?

I would have to figure this out.  Something like `anaconda.bat` would make it trivial, but I'm not sure what our options are doing startup script style initialization on Windows.

> 4. Can you explain what your conception of conda init is? I feel like your conception of it is different from what it currently does.

Yup -- sorry I didn't call that out.  When I talk about `conda init`, I mean what I want it to do, not what it does.  So here's what I'm thinking:

* Determines if the root directory exists along with some signifier that it's been initialized
* If so, displays an error saying its already there and stop
* If not, creates that directory and the envs and pkgs directories and touches the `.initialized` or what have you file.

Done.  Now `conda install` would use that as the basis for finding local packages, storing environments, and so on.

To reiterate, at this point the `conda` package can exist anywhere.  There wouldn't be any bootstrapping of new packages or anything like that that we need to do as that newly minted conda system/environment/install is now setup to be worked on from the outside.  This feeds into question 5…

> 5. In a similar vein, I'm unclear how this affects pip install conda. Note that the main fundamental issue with pip install conda is that the Python is not managed by conda (which is basically by definition).

Correct.  That said, conda simply needs Python to run and can be run using any Python as far as I'm aware.

I wasn't involved in the development process, so please correct me if I'm wrong, but it appears that the main motivation here was that conda grew out of Anaconda.  Anaconda's main goal is to be ready-to-use.  As such, Python has to be on the path when you start.  As far as I'm aware, there are no technical reasons that Ubuntu's `python` package can't be the Python that executes the `conda` command other than the reliance on `sys.prefix`.

> Some of your activate issues could be solved by #813 …

I don't see how this is directly relevant.  It addresses one of the concerns, but not the overarching goals of removing the root environment from the equation entirely.

> 7. If you were going to completely reimplement conda in another language, why would you even need to access conda at all? If this were truly done, Python would not even be needed.

Currently there is no way to interoperate with a Python-based installation of conda from the outside.  I'm running into this in my work with Anaconda Launcher where I'm implementing a read-only version of conda to handle gathering information about what's installed.  I can't know where to start without using `conda info` because the location of the conda installation depends entirely on where it was installed.

This is an issue for ecosystems that want to re-implement the conda spec in their own language but want to play nicely with other installations of conda that might be managed by Python.  @pzwang might have some thoughts on this as I know he's talked to other communities that love conda as a concept but will not install Python to manage packages.

> 8. With this proposal, what files would be in the ~/anaconda directory (say, with a default installation)?

Here's an example structure of what I think should be in a conda installation:

```
./.conda-initialized <-- denotes an initialized install
./envs/ <-- environments directory
./pkgs/ <-- contains the local packages
```

For an environment with the a system environment as well, you would drop the appropriate directories needed for that (`bin`, `lib`, `share`, and so on).  That said, their location is entirely independent of the conda installation it operates on so you could just as easily install it into `/usr/local` or `~`.

> 9. Wait, what exactly does the --system flag do? Does the "system level" mean, e.g., /usr/? If so, -100. If not, that's a bad name.

Consider it a short-hand for `conda update --prefix=~/anaconda conda` (assuming the default location for Miniconda/Anaconda was used).  I'm definitely open for a name, but there needs to be a short-hand for updating the main prefix that contains conda and the related packages that are always available.

For a self-managed conda (something installed via Miniconda/Anaconda and not via pip or rpm or any other package manager), it would be a short-hand to the system environment: the environment that contains conda.  It should be an environment that's always on the PATH (if configured by the user -- if they didn't add it it should never be on the PATH) and should not be activate-able.  For pip-based installations (i.e., one where `$(which conda)/../conda-meta` does not exist), it would provide an error and give the user an error message that prompts them to create a conda-managed installation (`conda init --system`, for example).

> 10. Accordingly, I don't understand what the system type means. It makes a package uninstallable??

This is actually going to end up being two-fold:

* Environments would have an allowable type of package that can be installed into it (i.e., everything, system, and so on)
* When installing a package into an environment, the package type would need to be allowed by that environment or the user would have to explicitly state that they want to ignore that.

The reason is to avoid this:

```bash
$ source activate dev
$ conda install conda
```

And instead require:

```bash
$ source activate dev
$ conda install conda --override
```

At that point they're saying they want that installed for sure into that environment and are willing to go against the wishes of the package maintainer and/or really know what you're doing.

**Comment by tswicegood** [comment]
@ilanschnell:
> A major design decision to have conda in the root environment was that when you install Anaconda you get only a single root environment. For many people this is enough, and they don't have to worry about the concept of multiple environments.

Yes!  We're view the end goal the same I think.  I want users to just use Anaconda without having to think about environments if they don't want to.

The difference is that I want conda to maintain that by having a separate, default environment that's activated when their shell starts.  That completely removes the need to re-install to change the "base python" in Miniconda/Anaconda because the user never sees that.

**Comment by tswicegood** [comment]
*head desk* -- that moment when Markdown tries to be helpful and change all of my "#." prefixes to ordered lists.  Give me a second and I'll edit it.

**Comment by asmeurer** [comment]
Yeah, I actually took advantage of this feature when I wrote my comment because I wanted to insert a question in the middle without renumbering everything.

**Comment by ilanschnell** [comment]
Thanks for your detailed answers, Travis.  I still have the following questions.
1) Which specific current problem does this CEP solve?
2) What is the objective (other than changing many things)?
3) How would the installers (Miniconda, Anaconda) have to change?
4) Would cas-installer have to change as well?
5) What would migration look like?  (We have to ensure `conda update conda` still works.)

**Comment by asmeurer** [comment]
I think I understand what you are suggesting here now. You are calling it "system" because there would be literally one conda installed on a given system.

**Comment by tswicegood** [comment]
@ilanschnell:

> 1) Which specific current problem does this CEP solve?
> 2) What is the objective (other than changing many things)?

Here's an abbreviated version of [this][1] inside the CEP.

[1]: https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment#technical-simplification

* pip installation is hard because of `sys.prefix`
* mixing managing an installation of `conda` (the package) and managing a conda installation (the environments and packages) makes updating on Windows hard
* we have special case code for conda that other code can't opt-in and can't be overridden (see #1128)
* testing packages that rely on conda have to circumvent conda's built in checks
* activation logic is more brittle than it needs to be because it has to remove as well as add values
* there's no way to deactivate a Miniconda / Anaconda root install and still keep `conda` on the command line
* we're providing user's a method of using Anaconda that will eventually make it harder for them to use by not putting them in an environment that's separate from conda at the outset

But the driving motivation behind this is that there is no way to ensure that I'm looking at the same conda installation that `conda info` is without running that command (or reading `head -n1 $(which conda)` doing `dirname(dirname())` on it.

As a side note, the parenthetical comment makes it seem as though I'm simply changing things for the sake of change.  I'm disappointed that you would think I would suggest such a non-trivial change just for the sake of change itself. :-(

> 3) How would the installers (Miniconda, Anaconda) have to change?

These are still kind of a black box so I can't say with 100% certainty.  At a very meta level:

* Unpack / install conda
* Initial conda installation
* Populate the package cache in that system
* Create the default environment

> 4) Would cas-installer have to change as well?

I don't believe so.  `cas-installer` is meant to be used absent Conda, correct?  If so, there's no reason for it to change.

> 5) What would migration look like? (We have to ensure conda update conda still works.)

This is actually the reason to add a `.conda-initialized` file or some such.  We can use that to detect whether it's been upgraded, then prompt the user to upgrade.  The upgrade process would essentially:

* Run the new `conda init` to initialize the system environment (not sure what all that would entail until we start fleshing out the code)
* Use the history file to reconstruct a new default env (failing a history file, look for `anaconda` and use that which assumes nothing new was installed)
* Remove existing packages from the root/system environment that are not supposed to be there (for example: all packages without type `system`)
* Prompt the user to include the new `source activate` code and offer an option to add it ourselves where we can.

This migration should be optional for a long time which would give us a long time to get it figured out correctly.

**Comment by tswicegood** [comment]
@asmeurer:

> I think I understand what you are suggesting here now. You are calling it "system" because there would be literally one conda installed on a given system.

Exactly! :-)  Conda isn't necessarily managed by itself, but when it is it's a system install.  All that ever has is `conda`, `conda-build`, `conda-env`, and so on.

To put it another way, right now we have this concept of a single package that can only be installed in the root environment: `conda`.  I want to remove that special case and let environments specify what types of packages they'll accept, then put it on the package to use the correct meta data to get into that environment.

I'm renaming it from "root" to "system" to avoid any confusion by having an entirely separate concept.

**Comment by tswicegood** [comment]
@ilanschnell I just realized I didn't address `conda update conda`.  My goal would be `conda update conda` is translated to `conda update --system conda` unless the environment has a version of `conda` installed into it (something the user already had to override to get there).

When a user runs `conda update conda` and its translated it should display a warning to them that they're using a deprecated command and tell them the new command.  Eventually, once we are ready to release 4.0 and break backwards compatibility, we can remove it all together.

If the user runs `conda update conda` and the environment has `conda` installed in it, they would get the normal warning about it being a system package and prompting them to either type `conda update --system conda` or `conda update conda --override`.  Just like any other system package in an environment that doesn't accept them.

**Comment by ilanschnell** [comment]
Thanks for the response, Travis.

> pip installation is hard because of sys.prefix
pip installation is also hard because UCS issues, and we don't recommend it

> mixing managing an installation of conda (the package) and managing a conda installation (the environments and packages) makes updating on Windows hard
Aaron is working on that

> we have special case code for conda that other code can't opt-in and can't be overridden (see #1128)
Sure, but we have done that

> testing packages that rely on conda have to circumvent conda's built in checks
Yes, but we can do that now

> activation logic is more brittle than it needs to be because it has to remove as well as add values
Yes, but we have a working solution for that, and only one thing is added to the path

> there's no way to deactivate a Miniconda / Anaconda root install and still keep conda on the command line
There is a way:
```
$ cd $HOME
$ mkdir bin
$ cp anaconda/bin/conda bin/
$ export PATH=$HOME/bin
```
But why would you have to do that in the first place? 

> we're providing user's a method of using Anaconda that will eventually make it harder for them to use by not putting them in an environment that's separate from conda at the outset
Why does it make harder for users?

> But the driving motivation behind this is that there is no way to ensure that I'm looking at the same conda installation that conda info is without running that command (or reading head -n1 $(which conda) doing dirname(dirname()) on it.
The normal user has exactly one conda installation, and the details of `conda info` tell them where the installation is located.

For all points you address, we either (i) have a solution already (ii) we're working on one or (iii) I don't see or understand the problem.  We have a working conda system which may not be the most elegant from a pure software design perspective, but many people are using it, which has allowed us to fix many little problems real-world people run into.

**Comment by tswicegood** [comment]
@ilanschnell I'm going to skip right to this because I feel like this is the crux of the matter:

> We have a working conda system which may not be the most elegant from a pure software design perspective, but many people are using it, which has allowed us to fix many little problems real-world people run into.

I am definitely not questioning the value of what Conda has created.  Most of that praise belongs to you.  It's amazing.  It solves a lot of problems and makes daily usage of Python and the various scientific stack much much better.  All I want to do is take it to the next level.

With that out of the way, there are a few other comments I want to address.

> The normal user has exactly one conda installation, and the details of `conda info` tell them where the installation is located.

This misses a key point.  To quote from CEP-1:

> Implementation of conda in other languages is more difficult because other languages still require access to conda at the command line to know where the root is because of its implicit location

I am working on a read-only implementation of conda in CoffeeScript right now for Anaconda Launcher.  I've implemented much of it.  However, I can not create a fully independent implementation precisely because `conda info` is the only way to accurately determine where the root conda installation is located.  That is the entire point of #1093.

I'm not saying that original design decision was bad.  I'm certain you made it for perfectly valid reasons at the time.  Now there's another use case and pain points caused by that decision so we have to evolve it.

> Why does it make harder for users?

If users start using their root conda environment, install a few packages, maybe add pip and install a thing or two with that, then want to switch to another version of Python our current suggestion (that's been made publicly on Twitter) is to re-install Miniconda.

There's a mechanism for this already in Conda: environments.  If they did everything in environments like this proposes with a way to automatically select one, we could simply tell them to create a new environment and update a setting.  I'm reiterating what I mentioned earlier today already.

> There is a way:
>
> ```
> $ cd $HOME
> $ mkdir bin
> $ cp anaconda/bin/conda bin/
> $ export PATH=$HOME/bin
> ```
> 
> But why would you have to do that in the first place?

You can also abuse `deactivate` to remove conda entirely from the path.

```
source activate /path/to/anaconda
source deactivate
... do whatever without conda or any of its Python on the path ...
source ~/.profile (or in bash-it, reload)
```

Both of our solutions are hacky, though.  `conda` being on the PATH along with `activate` and `deactivate` rarely get in the way of other code.  Adding `python` and all of its files to the PATH just so `conda` can execute can introduce problems.

I had two people at the San Diego Python meetup ask me afterward how to get conda's version of `python` off of their PATH without explicitly modifying the `PATH` it so they could run scripts that relied on the OS installed `python`.  The best I could give them was the hack above.


> pip installation is also hard because UCS issues, and we don't recommend it

I'm not familiar with this.  When you say UCS, are you talking about the unicode handling that Python was built with?  Does that effect how the `conda` command runs, or is it something that has more to do with how libraries are used within the context of conda/anaconda?

---

There's a fundamental difference in how we approach problems.  I see a problem and try to figure out what caused it, then go after that source to make the problem go away.  It appears to me that you focus on fixing the immediate problem.  I think I understand why: you've put a lot of blood, sweat, and tears into getting conda to the state it's in and don't want to put any of that in jeopardy.  I don't want any of that to be for naught either.

I need you to work with me.  Of all of the feedback I've gotten today, the comment on UCS is the most helpful.  That's potentially a technical reason for why this wouldn't work that I have no context of.  That's why I'm asking these questions rather than simply going off and refactoring code and opening up big PRs with changes.  You've been in through the battle already.  Now that we've got something working, let's polish it and turn it into the robust, tested, documented tool it should be.

I think a documented method for determining where a conda system is installed that doesn't rely on Python and the concept of a system environment where `conda` is always on the `PATH` are two big steps in that direction.

**Comment by ilanschnell** [comment]
Thanks for the response.  I see your point of view clearer now.

> If users start using their root conda environment, install a few packages, maybe add pip and install a thing or two with that, then want to switch to another version of Python our current suggestion (that's been made publicly on Twitter) is to re-install Miniconda.
I don't know who said that publicly on Twitter, but my response would have been to use `conda create`.

The UCS problem is the following.  Python 2 has a configuration option `--enable-unicode` which may be set equal to `ucs2` or `ucs4`, which sets the number of bytes used to represent unicode characters in memory.  The problem is that C extensions compiled against a Python using one setting will generally not work with a Python which was using the other one.  On Mac and Windows, `ucs2` is used by the binary installer from python.org, which is why we use `ucs2` on Mac and Windows in Anaconda as well, such that binary packages from other sources play well with Anaconda.  Now for Linux, there is no de-facto standard.  Some Linux distros use `ucs2`, and some `ucs4`.  We've decided early on to use `ucs4` on Linux.  Now if someone pip installs conda on a Linux system which uses `ucs2`, then our Python packages (the ones with C extensions) will not work with their system Python.

**Comment by tswicegood** [comment]
Thanks for the explanation.  I see the one thing that I haven't explained well and/or just took for obvious.

> Now if someone pip installs conda on a Linux system which uses ucs2, then our Python packages (the ones with C extensions) will not work with their system Python.

That would never happen.  Conda packages would never be in an environment with the system Python.  One of the reasons to enforce everything in an environment is that when you install `numpy` it would download *all* dependencies, including the appropriate version of Python, and install those via conda.  The system Python would only be used to run `conda` which in turn only operates on a conda installation.

It sounds like the USC2/4 issue wouldn't effect us here unless the `conda` package got into a state where it used compiled C code that we somehow shipped with it.  I can't see that happening, so I think we're in the clear.

**Comment by asmeurer** [comment]
> pip installation is also hard because UCS issues, and we don't recommend it

We don't recommend `conda init` (the existing version). pip installing conda is fine, but you can't use it to manage the environment that you install it into. 

> Aaron is working on that

I'm still uneasy about my fix FWIW. This is to me one of the best motivations to move conda to a separate environment. But this CEP goes above and beyond just that (which only requires https://github.com/conda/conda/issues/1145#issuecomment-74144453).

> I am working on a read-only implementation of conda in CoffeeScript right now for Anaconda Launcher. 

Why can't you take the same approach as conda, and require it to be installed into the root environment? 

> I had two people at the San Diego Python meetup ask me afterward how to get conda's version of python off of their PATH without explicitly modifying the PATH it so they could run scripts that relied on the OS installed python. The best I could give them was the hack above.

Another trick is to activate an empty environment. #813 is highly relevant here as well.

> activation logic is more brittle than it needs to be because it has to remove as well as add values

It still has to do this, because if you 

```
source activate a
source activate b
```

the second activate has to remove `a` and add `b`.

Again, though, the `OLD_PATH` suggestion from #813 would make this simpler, and can be done completely independently of the other suggestions here.

**Comment by asmeurer** [comment]
Disallowing multiple conda's to be installed at once would break my personal workflow. I use it to test conda and conda-build in Python 2 and Python 3, 32-bit and 64-bit conda, and to test changes to conda that have the potential to break the root environment (like #1133 is the most recent example of this).  Non-conda developers probably don't need this, with the exception of the 32-bit/64-bit thing.

**Comment by tswicegood** [comment]
> Disallowing multiple conda's to be installed at once would break my personal workflow.

Yes, I can see that.  It's like working with git -- you blow away parts of your repo by your new command and you're hosed. :-)

FWIW, it's not that they're disallowed, they're just not implicitly supported under this proposal.  You could still override the root directory two ways:

```bash
$ CONDA_ROOT=/path/to/other/system /path/to/other/system/bin/conda
# or
$ CONDARC=/path/to/config /path/to/other/system/bin/conda
```

You could use something like [autoenv][] to set those values automatically when you switch to a given directory (what I'd probably do).

[autoenv]: https://github.com/kennethreitz/autoenv

**Comment by aldanor** [comment]
I use multiple root conda installations as well -- have to run it as the same user on a cluster of boxes with different incompatible Linux distros installed, and we also run multiple servers that host our custom conda packages built specifically for each distro. Then in the user config just set `CONDARC` to use proper channels, amend the `PATH` and that's it.

**Comment by tswicegood** [comment]
@aldanor is `CONDARC` always set specific to the various installs when working with different installs?

**Comment by kalefranz** [comment]
Supersedes by #3912
