### ISSUE TITLE
CEP 0: Adding Conda Enhancement Proposals

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1146]
Following the example of [Bokeh](https://github.com/bokeh/bokeh), I would like to start CEPs for larger discussions.

https://github.com/conda/conda/wiki/CEP-0:-Conda-Enhancement-Proposals

**Comment by tswicegood** [comment]
:+1: from me (as one would hope).  @bryevdv and the Bokeh team are using these quite successfully.  Using the wiki provides a clear way to document the outcome of new feature discussions along with a history of all of its changes without having to read through a full issue discussion.

@ilanschnell @asmeurer @teoliphant @pzwang: any thoughts one way or the other?

@bryevdv any thing we should modify and/or watch out for before going down this path?

**Comment by bkreider** [comment]
CEP with a short e sounds good too.  "Conda is great, 'CEP for one thing i like to fix...."

**Comment by asmeurer** [comment]
Shouldn't it be pronounced "keep" or "kep"?

I propose we leave the pronunciation open ended but highly contentious, like GIF.

**Comment by teoliphant** [comment]
I think this is fine.  I see it as a tagging mechanism and prioritization mechanism for issues --- so as long as it does not become too heavy-weight.   In NumPy, the EP's got too heavyweight and actually become a barrier to change.
