### ISSUE TITLE
Add "pyfakefs" to testing dependencies

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11463]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

I would like to have "pyfakefs" added to this project's testing dependencies.

### Why is this needed

While writing tests, it is often very useful to have a "virtual" file system. pyfakefs enables this with a nice API exposing virtual file systems as a testing fixture.

This PR has an example of how I intend to use this library:
- https://github.com/conda/conda/pull/11462

### What should happen?

`pyfakefs` should be added to the projects testing dependencies.

**Comment by jezdez** [comment]
My worries around adding this as a runtime dependency come from not knowing if it's practical to rely on, from http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#modules-not-working-with-pyfakefs:

> A list of Python modules that are known to not work correctly with pyfakefs will be collected here: multiprocessing, subprocess, ...

An alternative would be to use [fsspec](https://github.com/fsspec/filesystem_spec)'s memory backend and use it to write new tests. The upside is that given [its features](https://filesystem-spec.readthedocs.io/en/latest/features.html) we can access the local file system if a test requires it (or even wrap consecutive calls in a cache) without additional overhead of maintenance or change of interface.

A memory backend fsspec pytest fixture is defined in its own tests [here](https://github.com/fsspec/filesystem_spec/blob/c18902b278c18000cd93e54f0fb319602fa91e74/fsspec/conftest.py#L13-L27) and used [here](https://github.com/fsspec/filesystem_spec/blob/c18902b278c18000cd93e54f0fb319602fa91e74/fsspec/implementations/tests/test_memory.py). It's also available on the defaults channel already.
