### ISSUE TITLE
Improve the landing page of the documentation website

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11482]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

I would like to propose a total re-work of the home page for the conda documentation. As it stands, the content consists of multiple paragraphs, which are not easily skimmed and provide little visual hierarchy.

We could potentially include:
- Terminal animations showing how various commands work (e.g. creating a new environment)
- More information on how to install it
- A better way to highlight the benefits of using conda and lay this content out in a more visually appealing manner

### Why is this needed

I believe that the landing page for any project documentation should help users quickly figure out what they need and where to go. As it currently stands, the landing page of our document is a lot of text and could benefit greatly from some re-imagination.

For example, https://fastapi.tiangolo.com/ has a nice intro page highlighting why this is a useful project (making the sell) and then shows how to install it and how to use it all on the same page. I don't see we wouldn't be able to do this for `conda` too.

### What should happen?

Users should see a front page of documentation that clearly introduces the project. It should attempt to sell them on its benefits while also providing a high level intro on how to use it before the user digs any deeper in to the docs. The user should also have a clear idea of who the sponsors are and how they may get involved in the project if they desire (by contributing or file a bug/feature request).

**Comment by awwad** [comment]
To be discussed in a few sprints, once we have a sense of how soon the conda.org work will be done
