### ISSUE TITLE
Set conda platform in environment creation subcommands and record it in environment config

### ISSUE THREAD

**Issue by seibert** [conda/conda#11505]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

An argument (maybe `--platform`?) added to all conda subcommands that create environments which sets the platform subdirectory to something other than the default platform and also records the platform in the environment-specific configuration so it will be used in subsequent commands when the environment is active.

### Why is this needed

The M1 Macs offer a novel situation where the OS supports two different conda platforms: `osx-64` and `osx-arm64`.  As not all software has been ported to the M1, it is frequently useful to create an x86 environment when the base environment is ARM, or vice versa.  The current workaround is either:
* Set the `CONDA_SUBDIR` environment whenever running conda.  However, if you forget on a subsequent update, you could mess up the environment.
* Create an empty environment and set the environment config.  Example:
```
# starting from osx-64 base environment
conda create -n m1 
conda activate m1
# set the platform in just this environment (--env) to osx-arm64
conda config --env --set subdir osx-arm64
# all future installs and updates will use osx-arm64 packages
conda install python=3.8 notebook pandas
```

I can imagine future use cases where this could be useful (say, for conda managing a micropython environment), but those are speculative.  The immediate driving use case is for M1 Macs.

### What should happen?

I would like to run the command:
```
conda create --platform osx-64 -n x86_test python=3.7 notebook
```
and have the new environment populated with x86 packages, and also have the platform preference recorded in the conda environment-specific configuration file.

**Comment by jaimergp** [comment]
Hi @seibert! Take a look at #11794 to see if it provides the functionality you needed!

**Comment by jaimergp** [comment]
Not stale.
