### ISSUE TITLE
[windows] conda venv listed twice, using uppercase/lowercase drive letter

### ISSUE THREAD

**Issue by ghylander** [conda/conda#11501]
### What happened?

One of my venvs is listed twice, once with an uppercase 'C', then again with a lowercase 'c':
![Screenshot_1](https://user-images.githubusercontent.com/74593034/169974814-4c97f4b0-cbf6-4513-9ada-fb76e748db8e.png)

Only found one reference to this issue. Searching for the issue on the internet and this repo revealed it may be caused by the use of [upper case in the venv name](https://github.com/ContinuumIO/anaconda-issues/issues/8623#issuecomment-602330741)?

<details>
<summary>Additional Context</summary>

The issue I linked was about Anaconda reporting venvs twice, but env list did not show duplicates. The specific comment I linked does show what I'm experiencing.
I do not use Anaconda, all the venvs were created through the cli

</details>

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
     active environment : base
    active env location : C:\Users\gus_h\miniconda3
            shell level : 1
       user config file : C:\Users\gus_h\.condarc
 populated config files : C:\Users\gus_h\.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\gus_h\miniconda3  (writable)
      conda av data dir : C:\Users\gus_h\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\gus_h\miniconda3\pkgs
                          C:\Users\gus_h\.conda\pkgs
                          C:\Users\gus_h\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\gus_h\miniconda3\envs
                          C:\Users\gus_h\.conda\envs
                          C:\Users\gus_h\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> C:\Users\gus_h\.condarc <==
channels:
  - conda-forge
  - defaults
```

</details>

**Comment by kenodegard** [comment]
@ghylander I believe this is a duplicate of #11277.

We are unsure of how these duplicates appear in the first place. Have you perhaps invoked the same conda installation from different prompts/subsystems? cmd.exe, Powershell, Git Bash, Cygwin, etc.?

**Comment by ghylander** [comment]
on windows, I work with PowerShell and a WSL bash
conda is not even initialized in cmd or other prompts

I do use VSC, and execute scripts, IPython and jupyter notebooks
Running a python script from VSC opens the VSC integrated PowerShell and sends the python command, complete with conda envs support

perhaps this could also be triggered by updates to PowerShell? I noticed it shortly after updating to PowerShell v7.2.4, but I can't really point at the update as the culprit as prior to that I had not invoked `conda env list` in a relatively long time

**Comment by ghylander** [comment]
I was trying to get a screenshot of the VSC integrated terminal, and I think it may be a good candidate. This is what it looks like when in VSC:
- I open a python script 
- I select the venv I want to use as the "python kernel"
- I execute the script

![Sin título](https://user-images.githubusercontent.com/74593034/170434312-8ba058bd-7873-4c6e-9c33-d0b5528c0157.png)

The command run invokes the venv the python kernel and then calls the python script, but the string used as the path to the script has a lower case 'c'

Also, checked the `%USERPROFILE%\.conda\environments.txt` file, an there was indeed a line duplicating the venv using the lowercase c as the drive letter
