### ISSUE TITLE
Docs | Sentence funkiness on Conda channels page

### ISSUE THREAD

**Issue by idanenglander** [conda/conda#11525]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

[This sentence ](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html#:~:text=By%20default%2C%20packages%20are%20automatically%20downloaded%20and%20updated%20from%20the%20default%20channel%20https%3A//repo.anaconda.com/pkgs/%20which%20may%20require%20a%20paid%20license%2C%20as%20described%20in%20the%20repository%20terms%20of%20service%20a%20commercial%20license.)ends in a peculiar way. Not sure if it's a missing word or if "a commercial license" should just be removed. 

@kathatherine

**Comment by jezdez** [comment]
@idanenglander Could you please copy the sentence that is in question into the PR description? The link added there doesn't work for me.

**Comment by jezdez** [comment]
Oh actually, looking at the history of the file this seems to have been fixed in #12395!
