### ISSUE TITLE
Stacking environments (using --stack) in fish shell is not working (the base environment will not be in PATHS)

### ISSUE THREAD

**Issue by timhansinger** [conda/conda#11523]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Conda --stack option doesn't work in fish shell.
Side note: Under zsh or bash shell it works correctly.

Steps to reproduce:

Tested on fish v3.4.1 (installed via homebrew) on an M1 Macbook.

- create a second environment, e.g. `conda create --name py310 python=3.10`
- make sure the base environment is activated via `conda activate`
- check the path output `echo $PATH | tr " " "\n"`, it will look something like this:
```
/Users/tim/miniconda3/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/Users/tim/miniconda3/condabin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
- now try to stack the second environment to it `conda activate py310 --stack`
- check the path output `echo $PATH | tr " " "\n"`, it will look something like this:
```
/Users/tim/miniconda3/envs/py310/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/Users/tim/miniconda3/condabin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

Issue:
The path of the base environment is missing in $PATH after stacking the second environment.

Expected output of `echo $PATH | tr " " "\n"` would be:
```
/Users/tim/miniconda3/envs/py310/bin
/Users/tim/miniconda3/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/Users/tim/miniconda3/condabin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

### Conda info

```shell
active environment : None
            shell level : 0
       user config file : /Users/tim/.condarc
 populated config files : 
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.4=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/tim/miniconda3  (writable)
      conda av data dir : /Users/tim/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tim/miniconda3/pkgs
                          /Users/tim/.conda/pkgs
       envs directories : /Users/tim/miniconda3/envs
                          /Users/tim/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Darwin/21.5.0 OSX/12.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by michaelaye** [comment]
Problem also exists with fish 3.5.0 on CentOS 7.9.2009.

**Comment by michaelaye** [comment]
I'd like to help fixing this. Is this the right file to study? https://github.com/conda/conda/blob/fe481c7d89d0ddd46bac12b3931ee4e096c6b442/conda/shell/etc/fish/conf.d/conda.fish
