### ISSUE TITLE
Miniconda3-latest-Linux-x86_64.sh does not support zsh, need add path to zshrc manually 

### ISSUE THREAD

**Issue by Firestar-Reimu** [conda/conda#11524]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I installed miniconda 2022 by `zsh ./Miniconda3-latest-Linux-x86_64.sh` and this happened:

1. The installer prompts “Do you wish the installer to initialize Anaconda3 by running `conda init`?” **I choose “yes”.**
2. But when I **close and open my terminal window** for the installation to take effect, zsh do not recognize conda
3. I run `source <path to conda>/bin/activate` and then run `conda init`, then zsh recognize conda
4. But when I **close and open my terminal window** for the installation to take effect, zsh do not recognize conda **again**
5. I tried adding `export PATH=/home/firestar/.miniconda/bin:$PATH` to `.zshrc` and `source ./.zshrc`
6. The problem has solved.
### Conda info

```shell
active environment : base
    active env location : /home/firestar/.miniconda
            shell level : 1
       user config file : /home/firestar/.condarc
 populated config files : 
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.10.4.final.0
       virtual packages : __linux=5.18.1=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/firestar/.miniconda  (writable)
      conda av data dir : /home/firestar/.miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/firestar/.miniconda/pkgs
                          /home/firestar/.conda/pkgs
       envs directories : /home/firestar/.miniconda/envs
                          /home/firestar/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.10.4 Linux/5.18.1-1-MANJARO manjaro/21.2.6 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager and not the miniconda installer. Thank you for understanding!
