### ISSUE TITLE
Add support for userid placeholder in .condarc values

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#1156]
In Enterprise settings it is often necessary to manage an Anaconda / conda installation on systems that multiple users have access to.  The users userid (username) is typically the main token used to control what the user has access to.  By allowing .condarc entries to contain userid placeholders that are substituted with the current users userid, centralized setup and management of Enterprise systems can be simpler, faster and more secure.

As an example, the envs_dirs directive allows an admin to set the default location of envs to be the users home directory, but what if the admin needs to make the default location a non-home sub-directory and the path includes the user's userid.  If the system has a mounted drive called /dev and the users want their envs created in /dev/&lt;userid&gt;/envs then this could be accomplished with one entry in the system .condarc file.  Using this approach users on the system can freely create envs using the centrally managed install of Anaconda.  The envs are on an admin managed disk with plenty of space.  The user didn't have to setup a .condarc file in their home directory.

<pre>
envs_dirs:
  - /dev/&lt;userid&gt;/envs

conda-build:
  root_dir: /dev/&lt;userid&gt;/build

channels:
  - http://server/&lt;userid&gt;/
  - file:///dev/&lt;userid&gt;/pkgs
</pre>

**Comment by ilanschnell** [comment]
Isn't this possible already by using `~` in the (central) condarc file?  This gets expanded to each users home directory.

**Comment by joelhullcio** [comment]
@ilanschnell Not exactly, the point of this enhancement is to be able to use the userid in paths that are NOT under the users home directory.  At JPM we have a case where we want users to create envs on a mounted partition that isn't under their home directory and it isn't under the Anaconda prefix.  We want the envs organized by their userid.

**Comment by ilanschnell** [comment]
So what would that look like?  After the condarc file is loaded, `<userid>` is replaced with `os.getuid()`?
This would not work on Windows, because you only have `os.getuid()` on Unix like systems, but that's probably fine.

**Comment by ilanschnell** [comment]
@joelhullcio Is this a feature which is needed soon?  Any timeline?

**Comment by danamid** [comment]
Any update on whether this functionality was implemented? My team is working on deploying the client in an Enterprise setting, and we're very much interested in using this functionality.

**Comment by kalefranz** [comment]
@joelhullcio conda expands environment variables for many/most config parameters where they're relevant.  If you run across a particular config parameter where you want to use environment variables but it's not working quite right for you, file a new ticket and I'll get that expansion added.
