### ISSUE TITLE
Conda install doesn't work.

### ISSUE THREAD

**Issue by chayanroyc** [conda/conda#11579]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Conda doesn't seem to work. Even downgrading it doesn't work (install doesn't work). I am in a HPC Cluster, but the packages must be up to date. 

### Conda info

```shell
active environment : /glade/work/chayan/miniconda3/envs/geo_scipy
    active env location : /glade/work/chayan/miniconda3/envs/geo_scipy
            shell level : 2
       user config file : /glade/u/home/chayan/.condarc
 populated config files : /glade/u/apps/opt/conda/.condarc
                          /glade/u/home/chayan/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.10.final.0
       virtual packages : __linux=4.12.14=0
                          __glibc=2.22=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /glade/u/apps/opt/conda  (read only)
      conda av data dir : /glade/u/apps/opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/ncar/linux-64
                          https://conda.anaconda.org/ncar/noarch
          package cache : /glade/scratch/chayan/.conda/pkgs
       envs directories : /glade/u/apps/opt/conda/envs
                          /glade/work/chayan/conda-envs
                          /glade/u/home/chayan/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.10 Linux/4.12.14-95.51-default sles/12.4 glibc/2.22
                UID:GID : 35728:1000
             netrc file : /glade/u/home/chayan/.netrc
           offline mode : False
```

### Conda config

```shell
==> /glade/u/apps/opt/conda/.condarc <==
auto_activate_base: False
notify_outdated_conda: False
env_prompt: ({name})
default_threads: 2
envs_dirs:
  - /glade/u/apps/opt/conda/envs
  - /glade/work/${USER}/conda-envs
pkgs_dirs:
  - /glade/scratch/${USER}/.conda/pkgs
channel_priority: strict
channels:
  - conda-forge
  - ncar
show_channel_urls: True

==> /glade/u/home/chayan/.condarc <==
allow_conda_downgrades: True
auto_activate_base: False
pip_interop_enabled: True
channel_priority: disabled
channels:
  - conda-forge
  - defaults
show_channel_urls: True
offline: False
```

### Additional Context

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): \ failed

**Comment by kenodegard** [comment]
@chayanroyc Unfortunately we need additional information to help debug.

Please provide:
1. the command you attempted to run,
2. the packages installed into the environment you are trying to modify, and
3. the complete failure message `conda` outputs.

**Comment by mzannoni** [comment]
I also have this problem, I think.
Extensively described [here](https://github.com/conda/conda/issues/6941#issuecomment-1166315668).

It seems the issue comes from `conda-forge` channel.
I'm not able to install anything whenever I either add that channel or simply specify it as install option.

Is it something broken with `conda-forge` and the latest anaconda?
(Everything as always worked fine for me until a few days ago)

**Comment by jaimergp** [comment]
Mamba is using an incredibly amazing solver, agreed! We have been working on a plugin to bring it over to conda: https://github.com/conda-incubator/conda-libmamba-solver

Maybe you can add it to your `base` environment (conda-libmamba-solver is on defaults too, so you don't need to add conda-forge) and enable it as the solver with `conda install --experimental-solver=libmamba ...`?
