### ISSUE TITLE
'ipykernel' can not be installed

### ISSUE THREAD

**Issue by Morhafhaedar** [conda/conda#11587]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

i can not install ipkernel in my env "python3.10.4 "

i aleady used the command:  'conda install -n Morhaf ipykernel --update-deps --force-reinstall'. then i becam the following masseg.
'Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues')

**Comment by jaimergp** [comment]
Can you go to `$CONDA_PREFIX/conda-meta` and temporarily rename `ca-certificates-*.json` to `ca-certificates-*.json.bak` and re-run the command?
