### ISSUE TITLE
Allow for custom platforms?

### ISSUE THREAD

**Issue by aldanor** [conda/conda#1159]
I don't know if this has come up before but I see this as a low hanging fruit and an immensely useful feature.

Platform detection is currently done like so in `config.py`:

``` python
_sys_map = {'linux2': 'linux', 'linux': 'linux',
            'darwin': 'osx', 'win32': 'win'}
platform = _sys_map.get(sys.platform, 'unknown')
bits = 8 * tuple.__itemsize__

if platform == 'linux' and machine() == 'armv6l':
    subdir = 'linux-armv6l'
    arch_name = 'armv6l'
else:
    subdir = '%s-%d' % (platform, bits)
    arch_name = {64: 'x86_64', 32: 'x86'}[bits]
```

Would it be possible to allow user to add custom platforms?

You can potentially have multiple "linux" builds of a package which is quite common in the unix world (e.g. we have a use case where we build Cython extensions that are not portable between Linux platforms due to mismatching glibc versions etc -- so we have to serve multiple "linux-64" channels). It would be nice if conda could be pointed to look at user-defined platform subdirs (sort of like it does with noarch) like

```
<url>/my-platform-1
<url>/my-platform-2
```

(or combine the default platform with that to have `my-platform-1/linux-64` or `/linux-64/my-platform-1`).

One way of doing this, I guess, would be to allow for `CONDA_PLATFORM` environment variable -- if not set, the current default platform detection method is used; if set, the urls looked up will be

``` sh
<url>/$CONDA_PLATFORM/
<url>/noarch/
```

**Comment by ilanschnell** [comment]
Yes, I agree that having the ability to change the platform is helpful is some case.  This issue hasn't come up often, however.  Adding the environment variable `CONDA_PLATFORM`, but also the ability to change this in the `~/.condarc` file like
```
conda_platform: linux-armv7
```
is a good idea.

**Comment by aldanor** [comment]
@ilanschnell Yep, being able to set that in `.condarc` would make sense (particularly so now that the config file location itself can be specified by `CONDARC` environment variable). 

So the platform lookup could then look like this:
- Is `CONDA_PLATFORM` set? If yes, use that
- Otherwise, is `conda_platform` set in `.condarc`? If yes, use that
- Otherwise, execute the code that infers it in `config.py`

From the looks of it, it's a fairly trivial fix to `conda.config` (unless the exact list of available platforms is also hardcoded somewhere else) without any breaking changes.

**Comment by asmeurer** [comment]
Note that for glibc we generally solve this issue by building against the lowest common version (like the version on CentOS 5), since it is backwards compatible.

**Comment by aldanor** [comment]
@asmeurer Yep, I'm aware of that, that's what is most commonly done in situations like this and we do that as well... sometimes if you're really nitpicky about optimization you do want to compile things on the target for the target using the latest gcc and the toolchain available...

**Comment by kalefranz** [comment]
The `CONDA_SUBDIR` and `subdir` condarc parameter can now be specified.  Also undocumented, you can specify `CONDA_SUBDIRS` as a string-delimited list and `subdirs` as a list in condarc.  These remain undocumented and experimental for now.  We have plans to expand the power of what we use subdirs for.  Any specific custom implementation might not be completely compatible with what is eventually settled on.  Thus the reason these remain experimental and undocumented.  Some related PRs are https://github.com/conda/conda/pull/4178 and https://github.com/conda/conda/pull/5030.
