### ISSUE TITLE
Unexpected behavior with deactivate

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#116]
```
$deactivate
Usage: source deactivate [ENV]

removes the 'bin' directory of the environment ENV from PATH.
ENV may either refer to just the name of the environment, or the full
prefix path.  ENV defaults to: /Users/aaronmeurer/anaconda
discarding /Users/aaronmeurer/anaconda/bin from PATH
$source deactivate py3k
Usage: source deactivate [ENV]

removes the 'bin' directory of the environment ENV from PATH.
ENV may either refer to just the name of the environment, or the full
prefix path.  ENV defaults to: /Users/aaronmeurer/anaconda
discarding /Users/aaronmeurer/anaconda/envs/py3k/bin from PATH
```

In each instance, it tells the usage as if it is typed incorrectly, but it still removes (or at least claims to remove) the given bin directory from PATH (I think it doesn't actually do it unless you `source`).

**Comment by aaros-web** [comment]
Hi,

I think my current problem is related to this issue...

I'm using git bash on windows and when I use `source deactivate` I lose most of the commands (`conda`, `git` or even `ls`), but `cd` and `echo` are still available... I looked a bit further by comparing PATH before/after activating and before/after deactivating and the behavior is weird: after deactivating the PATH still has directories related to the deactivated environnement and there are new directories related to Git:
`C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;`

Do you have any idea why it behaves like that ?
My conda is 4.3.17.
