### ISSUE TITLE
Using asyncio/threads to download packages

### ISSUE THREAD

**Issue by shughes-uk** [conda/conda#11608]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other speed issues and didn't find a duplicate

### What happened?

This is a continuation of an email thread with @LtDan33 and @pzwang 

I wrote a hacky little experiment that pre-populates the `pkgs` cache using asyncio to download packages listed in a conda-lock lockfile. I found it to be much faster than the default conda implementation. I suspect it would be faster than using multiple threads too. 

Mostly looking to optimize start time for dask clusters, I can create the environment and wrap it up as a docker image, but it ends up being slower than doing this.

In benchmarking I found this to be as fast or faster than mamba's implementation. Definitely much faster when mamba falls back to what I think is conda's single threaded implementation!

My very hacky use of a processpool executor to farm out validation/extraction of the package tarballs probably needs some extra thought, it was quite fast though!

```python
import asyncio
import hashlib
from concurrent.futures import ProcessPoolExecutor
from functools import partial
from pathlib import Path
from typing import Dict
from urllib.parse import urlparse

import aiofiles
import aiohttp
import yaml
from conda_package_handling import api

cheap = yaml.load(Path("./conda-lock.yml").open(), Loader=yaml.SafeLoader)
root = Path("~/miniconda3/pkgs").expanduser()
root.mkdir(exist_ok=True)


def extract(sha256: str, file: str, target: str):
    hasher = hashlib.new("sha256")
    with open(file, "rb") as fh:
        for chunk in iter(partial(fh.read, 8192), b""):
            hasher.update(chunk)
    assert hasher.hexdigest() == sha256
    print("Extracting", file, target)
    api.extract(file, target)


async def main(packages: Dict):
    async with aiohttp.ClientSession() as session:
        tasks = []
        urls = []
        for package in packages:
            if package["platform"] == "linux-aarch64" and package["manager"] == "conda":
                url = package["url"]
                parsed = urlparse(url)
                pth = Path(parsed.path)
                pth.name
                tasks.append(
                    download_url(
                        sha256=package["hash"]["sha256"],
                        session=session,
                        fp=root / pth.name,
                        url=package["url"],
                    )
                )
                urls.append(url)
        await asyncio.gather(*tasks)
        async with aiofiles.open(root / Path("urls.txt").expanduser(), mode="w") as f:
            for url in urls:
                await f.write(url + "\n")
        async with aiofiles.open(root / Path("urls").expanduser(), mode="w") as f:
            await f.write("\n")


async def download_url(session: aiohttp.ClientSession, sha256: str, fp: Path, url: str):
    print("Downloading", url)
    async with session.get(url) as resp:
        async with aiofiles.open(fp, mode="wb") as f:
            async for chunk in resp.content.iter_chunked(10000):
                await f.write(chunk)

    loop = asyncio.get_running_loop()
    target_dir = (
        str(fp).removesuffix(".tar.bz2").removesuffix(".tar").removesuffix(".conda")
    )
    await loop.run_in_executor(p, extract, sha256, str(fp), target_dir)


if __name__ == "__main__":
    with ProcessPoolExecutor(max_workers=10) as p:
        asyncio.run(main(cheap["package"]))
```

### Debug

```shell
na
```

### Conda info

```shell
na
```

### Conda config

```shell
na
```

### Conda list

```shell
na
```

**Comment by jaimergp** [comment]
There are a couple of places where conda can already use threads and/or processes:

Fetching the index:

https://github.com/conda/conda/blob/86447b6bc47eb9549db9c857fef941e2111cb7a4/conda/core/index.py#L76-L83

Verifying the transaction:

https://github.com/conda/conda/blob/86447b6bc47eb9549db9c857fef941e2111cb7a4/conda/core/link.py#L182-L183

Executing the transaction:

https://github.com/conda/conda/blob/86447b6bc47eb9549db9c857fef941e2111cb7a4/conda/core/link.py#L185-L186

I think the default value is set to 1 for a stability reason, but the code for the executors can be found in `conda.common.io`. It should be easy to add a similar logic to the download and extraction logic:

https://github.com/conda/conda/blob/86447b6bc47eb9549db9c857fef941e2111cb7a4/conda/core/package_cache_data.py#L653-L657

However, I wonder why this haven't been done before. If it's such a low-hanging fruit, are there any caveats we might not be aware of? 🤷

**Comment by dholth** [comment]
This is very cool. It is funny that conda hasn't figured this out? I've found that network transfers can be CPU limited too, and that normal Python threads can take advantage of multiple CPU's when they're spending a lot of time calling e.g. hash functions, and presumably https:// implementations too

**Comment by shughes-uk** [comment]
asyncio is way faster than threads for stuff like this i've found. I did not try just upping the thread count from 1 for the executors @jaimergp shows, but i'd put good money on it not being as fast as the asyncio option.

**Comment by dholth** [comment]
Another problem I've noticed is that the # of threads for downloading things ought to be e.g. 10 and not "number of CPUs", it looks like conda does this https://github.com/conda/conda/blob/fdbedc49d4a61fb2121614de22795cfccc562b0b/conda/common/io.py#L527 and requests agrees to use that many connections (per host?) by default. With newer libraries http/2 might be happening which is also awesome...

**Comment by shughes-uk** [comment]
@dholth did you intend to close this?

**Comment by dholth** [comment]
No! It's just a big button next to the comment button, sorry.

**Comment by dholth** [comment]
I also noticed the session is threadlocal in the current code.

**Comment by dholth** [comment]
I've copied this code into an asv benchmarking project to better understand its performance. So far I have it downloading packages from a local threaded flask web server, and the extract-bz2 part has been taken out to time just the networking part. https://github.com/dholth/conda-benchmarks

**Comment by dholth** [comment]
https://dholth.github.io/conda-benchmarks/#download_asyncio.TimeDownloadPackages.time_download_aiohttp shows some benchmarks with or without a `time.sleep(0.01)` before each response. I wasn't able to get `aiohttp` to outperform calling `conda.exports.download` in a threadpool but the asyncio version isn't very sensitive to latency. Oddly it seems like the results were closer when the test web server was running in the same process as the benchmark. Check out next to a conda checkout, install asv and run `asv run`, `asv preview`

Parallel bzip2 extraction will scale linearly by # of cores. Should release the gil too, in a threadpool without the overhead of separate processes.

**Comment by shughes-uk** [comment]
So might be worth trying `httpx` too, and i'm also curious how much the performance of the flask server impacts things, a single process `werkzeug` server is not very representative of something like cloudflare

**Comment by dholth** [comment]
Thanks for your continued interest!

The benchmarks should be pretty easy to run - disable the fixup-urls function to keep the original CDN urls instead of the testing localhost URLs, and see what happens.

Try it without asyncio file handling.

I do wonder about the extra https negotiation compared to e.g. multiplexing all the transfers over http/2, we don't see any of that from a test server.

**Comment by dholth** [comment]
I installed  a development version of conda, to have it use a separate `pkgs` I can later delete `rm -rf $HOME/miniconda3/envs/conda-build/pkgs`
Rendered `conda-lock render conda-lock.yml`, ran
`time python -m conda install --download-only --file ../conda-benchmarks/conda-osx-64.lock`
Now to put it in the benchmarks suite. Maybe there is a different way to override the cache directory.

**Comment by dholth** [comment]
`time CONDA_PKGS_DIRS=/tmp/howslo python -m conda install --download-only --file ../conda-benchmarks/conda-osx-64.lock`

**Comment by dholth** [comment]
https://dholth.github.io/conda-benchmarks/#conda_install.TimeInstall.time_download_lockfile

**Comment by dholth** [comment]
https://github.com/conda/conda/blob/main/conda/core/package_cache_data.py#L657

conda executes a download, and then an extract action, in series with each other, and then proceeds to the next file.

It would be sensible to have a separate download pool and extract pool based on how much we expect parallelism to benefit each operation. When a download completes it should queue up an extract. It might be possible to get tqdm to cooperate with this by manually setting position= on the progress bars.

**Comment by dholth** [comment]
Finally an interesting graph after configuring the benchmark correctly. This test downloads and extracts 30 `.conda` packages. On the `main` branch, it takes almost 12 seconds with latency=0.25 (30 * 0.25s/package ~= 10, the thread count does nothing since threads are unsupported there).

The `parallel-package` branch uses threads and `conda-package-streaming`; `libarchive` is not threadsafe the way conda uses it. 1 thread at 0.25s latency takes 10.065s (seems too fast, where's the extract time?), 3 threads takes 3.4s, 7 threads takes 1.7s.

https://dholth.github.io/conda-benchmarks/#conda_install.TimeInstall.time_explicit_install?branch=main&branch=parallel-package-cache&x-axis=threads

**Comment by shughes-uk** [comment]
Asyncio also introduces some annoyances compared to threads so i'd be delighted if threads are all that is needed here!

**Comment by shughes-uk** [comment]
Very very cool, thanks so much for pushing this forward @dholth!

My next thought is multithreading the symlinking/postinstall steps for packages if it can be achieved, even mamba does not do that.

**Comment by jaimergp** [comment]
Wow @dholth, that looks incredible!!!

**Comment by dholth** [comment]
As for the link/unlink transaction, there are a few more parameters like this one, or `default_threads`; we should experiment again, it would not be surprising if 2 or 3 shows a gain.

```
            execute_threads=dals(
                """
                Threads to use when performing the unlink/link transaction.  When not set,
                defaults to 1.  This step is pretty strongly I/O limited, and you may not
                see much benefit here.
                """
            ),
```

**Comment by yzhang-gh** [comment]
This is amazing. However, it doesn't seem to always show the unfinished downloads and now I cannot see the "more hidden" progress (for quite a while) 😂

![image](https://user-images.githubusercontent.com/7588612/209442638-4393d75a-e47f-409a-9fe6-e1ae19014fa3.png)

**Comment by divideconcept** [comment]
Is there a parameter to increase the limit of simultaneous download shown ? It's pretty annoying to have this ... (more hidden) ... at the end, we have no idea what's happening beyond this limit and if any download is blocking or slow.
Or at least we should have a global progress indicator shown in addition to individual packages, if the limit can't be increased.

**Comment by RafailFridman** [comment]
Yes, this `more hidden` is very annoying. Is there currently a way to show all the packages/global progress bar?

**Comment by ThibaultFaney** [comment]
I second the comments above, it is useful to know which individual package prevents completion sometimes

**Comment by dholth** [comment]
This ticket summarizes the UX issues https://github.com/conda/conda/issues/12259 and https://github.com/conda/conda/issues/12210 is most closely related to your comment.

We attempted to replace completed progress bars with more relevant downloads while writing the parallel downloads implementation, but the current progress bars are barely threadsafe; if you try to hide or replace one then the whole set of progress bars tends to get corrupted. It will require some rework to be beautiful.

**Comment by barabo** [comment]
If the package download list were sorted in order of size (descending), that might improve the situation in the short term, since I'm guessing the big ones are going to take the longest to complete.
