### ISSUE TITLE
can't install packages in new conda environment except base environment

### ISSUE THREAD

**Issue by zihaoxingstudy1** [conda/conda#11607]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

![image](https://user-images.githubusercontent.com/58220227/177703146-7db22b1c-27dc-4e7e-8135-c5bc233950fe.png)
![image](https://user-images.githubusercontent.com/58220227/177703234-2b2eec35-1d99-4962-b668-b0f4db295cd1.png)
![image](https://user-images.githubusercontent.com/58220227/177703275-a454da93-707d-4b95-b531-df049994b26b.png)
![image](https://user-images.githubusercontent.com/58220227/177703409-32b34a3b-0020-4f7a-b286-fa489f262124.png)
![image](https://user-images.githubusercontent.com/58220227/177703450-d58948e7-5e21-4c78-aa12-156497ae78bf.png)

### Conda Info

```shell
active environment : protein
    active env location : /mnt/d/soft/linux/miniconda/envs/protein
            shell level : 1
       user config file : /home/zihaoxing/.condarc
 populated config files : /home/zihaoxing/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.10.102.1=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/d/soft/linux/miniconda  (writable)
      conda av data dir : /mnt/d/soft/linux/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/d/soft/linux/miniconda/pkgs
                          /home/zihaoxing/.conda/pkgs
       envs directories : /mnt/d/soft/linux/miniconda/envs
                          /home/zihaoxing/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/5.10.102.1-microsoft-standard-WSL2 ubuntu/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/zihaoxing/.condarc <==
auto_activate_base: True
```

### Conda list

```shell
# packages in environment at /mnt/d/soft/linux/miniconda/envs/protein:
#
# Name                    Version                   Build  Channel
```

### Additional Context

can't install packages in new conda environment except base environment

**Comment by jaimergp** [comment]
Your system is having issues with the hardlinks, possibly because the cache and the environment are in different filesystems. Is `/mnt/d` a network mountpoint for Windows that... hosts Linux software? 😬 

That's going to be tricky to make it work, but you can try several [settings in your `.condarc` file](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#creating-and-editing):

1. Use a different location for the cache storage (see [`pkgs_dirs`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-package-directories-pkgs-dirs)). You should probably have it under your personal directory.
2. Do not fallback to symlinks, but hard copies, with [`disallow_symlinks: false`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#disallow-soft-linking-allow-softlinks). This WILL result in more storage usage.
3. Do not even attempt to hardlink, default to hard copies: `always_copy: yes`.

**Comment by zihaoxingstudy1** [comment]
> Your system is having issues with the hardlinks, possibly because the cache and the environment are in different filesystems. Is `/mnt/d` a network mountpoint for Windows that... hosts Linux software? 😬
> 
> That's going to be tricky to make it work, but you can try several [settings in your `.condarc` file](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#creating-and-editing):
> 
> 1. Use a different location for the cache storage (see [`pkgs_dirs`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-package-directories-pkgs-dirs)). You should probably have it under your personal directory.
> 2. Do not fallback to symlinks, but hard copies, with [`disallow_symlinks: false`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#disallow-soft-linking-allow-softlinks). This WILL result in more storage usage.
> 3. Do not even attempt to hardlink, default to hard copies: `always_copy: yes`.

i reset the .condarc but it still can't install packages in the 'protein' environment , at last , i copy all the files (bin, compiler_compat,condabin,conda-meta,data,etc,include,lib,licenses,man,pkgs,scripts,share,shell,ssl,x86_64-conda_cos6-linux-gnu,x86_64-conda-linux-gpu) to 'protein' environment, and it can install the packages .
`
cp -r  /mnt/d/soft/linux/miniconda/* /mnt/d/soft/linux/miniconda/envs/protein/

rm -rf /mnt/d/soft/linux/miniconda/envs/protein/envs
`
