### ISSUE TITLE
Publish conda on pypi, specifically to support API users

### ISSUE THREAD

**Issue by shughes-uk** [conda/conda#11609]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Users of the conda api would find it somewhat helpful if conda was published on pypi, either as a new 'conda_api' package just having the current very stale version updated.

### Why is this needed?

If we want to introduce a dependency on the conda api into our package, it would require us to only allow users to install via conda so we can pull in conda itself as a dependency.

Users often mix `conda install` and `pip install` in their conda environments, and our package should work in either case. Our package can also be used outside of a conda environment and falls back to not using the api.

### What should happen?

Either update the current conda package or publish a new 'conda.api' package to prevent confusing regular conda users.

**Comment by travishathaway** [comment]
Hi @shughes-uk,

Thank you for submitting this issue. This is actually currently on our backlog under this ticket:

https://github.com/conda/conda/issues/7472

I will link this issue there so it doesn't get lost.

We can't say for sure when we will complete it, but we want to let you know that it is something we are discussing.

Again, thank you.
