### ISSUE TITLE
Extend `anaconda copy` to allow name & version changes

### ISSUE THREAD

**Issue by msaroufim** [conda/conda#11613]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I'd like to be able to download some conda binaries from https://anaconda.org/pytorch-nightly/torchserve-nightly and then promote them to https://anaconda.org/pytorch/torchserve. Version numbers for nightly scripts will include some date like `20220709` and the official release versions will look something like `0.6.0` https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/copy-pkg/

So basically I'd like an extension of `anaconda copy --old-name conda-forge/glueviz/20220101 --to jsmith/glueviz/0.23`

But I'm not sure how to go about renaming a conda package even manually (would happily do so if an automated solution is ways out)

### Why is this needed?

My team has a Github Action that takes care of uploading conda binaries for our package on a nightly basis https://github.com/pytorch/serve/pull/1685

When that PR is landed we will be able to do official releases by using another manually triggerable Github Action which takes in as arguments a nightly release date to promote from and an official release version to promote to. The script will work by downloading a nightly release, renaming it and then reuploading to an official channel. This is somewhat easy to do with PyPi https://github.com/pytorch/serve/blob/master/binaries/pip/retag_pypi_binary.sh and especially easy with Docker with their `docker tag`

**Comment by LtDan33** [comment]
Hey @msaroufim thanks for the request! I'm not able to transfer this as it's a different org, so can you open this on the [Anaconda Client](https://github.com/Anaconda-Platform/anaconda-client/issues/new) repo? That is what the 'anaconda` command is and will put it in the right queue to be sorted through. Thanks!
