### ISSUE TITLE
JSON output for errors should be properly formatted instead of text

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1163]
Here's example output:

``` json
{
  "error": "No packages found in current osx-64 channels matching: ipython-notebookzzz\n\nDid you mean one of these?\n\n    ipython-notebook\n\nYou can search for this package on Binstar with\n\n    binstar search -t conda ipython-notebookzzz\n\nYou may need to install the Binstar command line client with\n\n    conda install binstar",
  "error_type": null
}
```

Note all of the new lines.  There's valid structured data hidden in there, but it requires that I write a text processor in each environment I want to use it in.  Here's an alternative:

``` json
{
  "error": "No packages found in current osx-64 channels matching: ipython-notebookzzz",
  "packageName": "ipython-notebookzzz",
  "channels": [
    "http://example.com/foo/",
    "http://example.com/bar/"
  ],
  "platform": "osx-64",
  "alternatives": [
    "ipython-notebook"
  ]
}
```

Note, this problem is created by the `conda.cli` modules providing formatted text data rather than raw python data structures to an output/render function that then handles formatting the display depending on the context (see [these lines](https://github.com/conda/conda/blob/41607615d422a3b20c9a485bf070c3cdd7c29de2/conda/cli/install.py#L355-L371) for an example).  To make these changes we'll either need to refactor `common.error_and_exit` or write a text parser inside it.

**Comment by asmeurer** [comment]
No need to parse things. The structure is all in the `NoPackagesFound` exception (`NoPackagesFound.pkgs`), which is caught in the conda.cli.install module. We just need to output something different when `json` is True.

**Comment by tswicegood** [comment]
@asmeurer correct -- the issue is simply that we go through all of the trouble of building out the response before we even know what type of response we want to build.  Maybe the correct thing here is to add an `as_json()` and `as_text()` (or some other name) to `NoPackagesFound`, then let the error and exit code rely on that instead of expecting a full message.

**Comment by asmeurer** [comment]
The message that is part of the NoPackagesFound object itself is just a small error message (one sentence) describing the reason no packages were found (I think there are three distinct possibilities, e.g., could not find dependencies, bad metadata, ...). The long error message with the hint is generated in the conda.cli.install module, and it would be easy to add a `if json` branch that prints something else instead.

**Comment by tswicegood** [comment]
So in that case the API would to cast the exception to a string?  I like the idea of `e.message` (or not `str(e)` I guess) staying short and simple and adding other methods that can force explicit output -- easier to test, moves complexity away from the exception into the place where its needed.  In the grand scheme of things, though, I just want the actual info for launcher without having to parse it.

**Comment by kalefranz** [comment]
Done.
