### ISSUE TITLE
CondaHTTPError: HTTP 403 FORBIDDEN

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [conda/conda#11638]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm getting 403 from conda install:
```
Downloading and Extracting Packages
tensorflow-deps-2.9. | 3 KB      |                                                                                                                                                                       |   0% 

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/apple/osx-arm64/tensorflow-deps-2.9.0-0.tar.bz2>
Elapsed: 00:00.302020
CF-RAY: 72dc4e426bd05a37-MXP

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

I've seen other issue like this, but they does not fit my case... is this just a rate limiter?

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /Users/user/miniforge3
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : /Users/user/miniforge3/.condarc
                          /Users/user/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __osx=12.4=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/user/miniforge3  (writable)
      conda av data dir : /Users/user/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/user/miniforge3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/miniforge3/envs
                          /Users/user/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Darwin/21.5.0 OSX/12.4
                UID:GID : 501:20
             netrc file : /Users/user/.netrc
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /Users/user/miniforge3/.condarc <==
channels:
  - conda-forge

==> /Users/user/.condarc <==
channels:
  - conda-forge
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/user/miniforge3:
#
# Name                    Version                   Build  Channel
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb18efdd_2    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py39hb18efdd_1004    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
certifi                   2022.5.18.1      py39h2804cbe_0    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39h2804cbe_0    conda-forge
conda-package-handling    1.8.1            py39hb18efdd_1    conda-forge
cryptography              37.0.2           py39h4cb6239_0    conda-forge
debugpy                   1.6.0            py39h0ef5a74_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39h2804cbe_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   8.4.0            py39h2804cbe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py39h2804cbe_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.7.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39h2804cbe_7    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.0           py39h2804cbe_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libzlib                   1.2.12               h90dfc92_0    conda-forge
markupsafe                2.1.1            py39hb18efdd_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h5161555_1005    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
openssl                   1.1.1q               ha287fd2_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
psutil                    5.9.1            py39h9eb174b_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb18efdd_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py39hb18efdd_1    conda-forge
pysocks                   1.7.1            py39h2804cbe_5    conda-forge
python                    3.9.13          hc596b02_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyzmq                     23.2.0           py39h8faa4b9_0    conda-forge
qtconsole                 5.3.1                    pypi_0    pypi
qtpy                      2.1.0                    pypi_0    pypi
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39h9eb174b_1007    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                62.3.2           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               h40dfcc0_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0           py39h2804cbe_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tornado                   6.2              py39h9eb174b_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h90dfc92_0    conda-forge
```

</details>

### Additional Context

I've tried both with an hotspot and with a wifi, same error, multiple times...

**Comment by AlexandreBrown** [comment]
Hello @AlbertoSinigaglia , I'm getting the same issue.  
We have multiple gitlab CI pipeline and all fail with the same message than you (it was working fine less than 24h ago).  
  
```
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/torchvision-0.11.1-py39_cu102.tar.bz2>
Elapsed: 00:00.261145
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2>
Elapsed: 00:00.024297
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.10.0-py3.9_cuda10.2_cudnn7.6.5_0.tar.bz2>
Elapsed: 00:00.248455
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.023488
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by AlbertoSinigaglia** [comment]
Hi @AlexandreBrown any idea on when this might be solved? because it fails for `tensorflow-deps` which is not such an unusual package...

**Comment by schniter** [comment]
Same error for me with PyTorch related files:

```
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/osx-64/torchvision-0.13.0-py39_cpu.tar.bz2>
Elapsed: 00:00.290983

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/osx-64/pytorch-1.12.0-py3.10_0.tar.bz2>
Elapsed: 00:00.136265
```

**Comment by kenodegard** [comment]
**[From Twitter @condaproject](https://twitter.com/condaproject/status/1549778710219444225):**
> Some package downloads from [http://conda.anaconda.org](https://t.co/x8d3zzxZoN) are currently being affected. The 
[@anacondainc](https://twitter.com/anacondainc) team has traced it back to Cloudflare's system outages and is actively working to resolve it. In the interim, please check  [https://cloudflarestatus.com](https://t.co/lW08XZpPeC) for Cloudflare updates.

**Comment by AlbertoSinigaglia** [comment]
> **[From Twitter @condaproject](https://twitter.com/condaproject/status/1549778710219444225):**
> 
> > Some package downloads from [http://conda.anaconda.org](https://t.co/x8d3zzxZoN) are currently being affected. The
> > [@anacondainc](https://twitter.com/anacondainc) team has traced it back to Cloudflare's system outages and is actively working to resolve it. In the interim, please check  [https://cloudflarestatus.com](https://t.co/lW08XZpPeC) for Cloudflare updates.

I mean, how can this be possible... I'm still getting the error, and the affected packages are not "small/unused"...

**Comment by bsassoli** [comment]
Same issue.

**Comment by eghosaohenhen** [comment]
yea, I just deleted my conda installation, moved it to a different location and i'm getting this error rn when running "conda env create -n env_name -f environment_env_name.yml" when it gets to installing pytorch things. Does this mean all I can do is wait?

**Comment by AlbertoSinigaglia** [comment]
> yea, I just deleted my conda installation, moved it to a different location and i'm getting this error rn when running "conda env create -n env_name -f environment_env_name.yml" when it gets to installing pytorch things. Does this mean all I can do is wait?

I have the same for tensorflow, and I'm waiting...

**Comment by thrichardson-twist** [comment]
Same issue with plotly-orca

**Comment by v-kylegre** [comment]
Started seeing this today aswell. Reproducible with a fairly thin dockerfile 

```
FROM ubuntu:20.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y wget \
    && apt-get clean

RUN wget -v https://conda.anaconda.org/intel/linux-64/memkind-1.10.1-0.tar.bz2
```

Resolving binstar-cio-packages-prod.s3.amazonaws.com (binstar-cio-packages-prod.s3.amazonaws.com)... 52.216.144.27
Connecting to binstar-cio-packages-prod.s3.amazonaws.com (binstar-cio-packages-prod.s3.amazonaws.com)|52.216.144.27|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-07-20 23:04:19 ERROR 403: Forbidden.

AWS problem?

**Comment by AlbertoSinigaglia** [comment]
> Started seeing this today aswell. Reproducible with a fairly thin dockerfile
> 
> ```
> FROM ubuntu:20.04
> 
> RUN apt-get update \
>     && DEBIAN_FRONTEND=noninteractive apt-get install -y wget \
>     && apt-get clean
> 
> RUN wget -v https://conda.anaconda.org/intel/linux-64/memkind-1.10.1-0.tar.bz2
> ```
> 
> Results in a lot of red, but the same root issue:
> 
> ```
> Resolving binstar-cio-packages-prod.s3.amazonaws.com (binstar-cio-packages-prod.s3.amazonaws.com)... (IP ADDRESS REDACTED)
> Connecting to binstar-cio-packages-prod.s3.amazonaws.com (binstar-cio-packages-prod.s3.amazonaws.com)|(IP ADDRESS REDACTED)|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2022-07-20 23:04:19 ERROR 403: Forbidden.
> ```
> 
> AWS problem?

idk, actually changing even slightly the version, it works, e.g. i was trying to install tensorflow-macos=2.5.0 and it doesn't work, but tensorflow-macos=2.6.0 downloads just fine...

**Comment by miccio-dk** [comment]
getting the same error for pytorch, specifically file https://conda.anaconda.org/pytorch/linux-64/pytorch-1.11.0-py3.9_cuda11.3_cudnn8.2.0_0.tar.bz2

**Comment by chengstark** [comment]
I just encountered the same issue, a possible conda server issue?

**Comment by AlbertoSinigaglia** [comment]
@chengstark, from @kenodegard:

> **[From Twitter @condaproject](https://twitter.com/condaproject/status/1549778710219444225):**
> 
> > Some package downloads from [http://conda.anaconda.org](https://t.co/x8d3zzxZoN) are currently being affected. The 
> 
> [@anacondainc](https://twitter.com/anacondainc) team has traced it back to Cloudflare's system outages and is actively working to resolve it. In the interim, please check  [https://cloudflarestatus.com](https://t.co/lW08XZpPeC) for Cloudflare updates.

**Comment by bvmcode** [comment]
Was having the same issues running `conda install pytorch torchvision torchaudio -c pytorch -y` where ffmpeg and pytorch were failing with 403s. I kept trying repeatedly and was finally successful.

**Comment by M1kep** [comment]
Currently having issues with pytorch and pytorch-mutex, so I don't think so @jmoon0714

**Comment by mezhaka** [comment]
I see the same issue when accessing a repository through a tag. The tag could only be used once. After the initial usage it expires after about a minute. If I curl a file, I get:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  <X-Amz-Expires>60</X-Amz-Expires>
  <Expires>2022-07-20T17:53:21Z</Expires>
  <ServerTime>2022-07-20T17:53:45Z</ServerTime>
  <RequestId>YQNDY4ZFG41JEN6W</RequestId>
  <HostId>YHXJhik336Dybmjrqu08
6lVU5Fh2Z6mc1leBtWI2DkzAq/pNg8QQRiA2lp9Y07d9+o2mPDh5v9c=</HostId>
</Error>
```
A verbose output of the curl with some uninteresting bits substituted for <...> and some company-specific names "anonymized":
```
$ curl -vL https://conda.anaconda.org/t/<my-token-was-here>/mezhaka/noarch/mezhaka-storage-5.1.0-pypy_0.tar.bz2
> GET /t/my-token-was-here/mezhaka/noarch/mezhaka-storage-5.1.0-pypy_0.tar.bz2 HTTP/2
> Host: conda.anaconda.org
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/2 302
< date: Wed, 20 Jul 2022 17:52:21 GMT
< content-type: text/html; charset=utf-8
< location: https://<...>.s3.amazonaws.com/<...>/<...>?response-content-disposition=attachment%3B%20filename%3D%22mezhaka-storage-5.1.0-pypy_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27mezhaka-storage-5.1.0-pypy_0.tar.bz2&X-Amz-Expires=60&X-Amz-Date=20220720T175221Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=<...>&X-Amz-Credential=<...>&X-Amz-Signature=<...>
< cf-ray: 72dd8cd298b7266d-TXL
< cache-control: public, max-age=30
< expires: Wed, 20 Jul 2022 17:52:51 GMT
< strict-transport-security: max-age=31536000
< vary: Accept-Encoding
< cf-cache-status: EXPIRED
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< set-cookie: __cf_bm=<...>; path=/; expires=Wed, 20-Jul-22 18:22:21 GMT; domain=.anaconda.org; HttpOnly; Secure; SameSite=None
< server: cloudflare
<
* Ignoring the response-body
* Connection #0 to host conda.anaconda.org left intact
* Issue another request to this URL: 'https://binstar-cio-packages-prod.s3.amazonaws.com/<...>/<...>?response-content-disposition=attachment%3B%20filename%3D%22mezhaka-storage-5.1.0-pypy_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27mezhaka-storage-5.1.0-pypy_0.tar.bz2&response-content-type=application%2Fx-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=60&X-Amz-Date=20220720T175221Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=<...>&X-Amz-Credential=<...>&X-Amz-Signature=<...>'
*   Trying 52.216.37.81...
* TCP_NODELAY set
> GET /t/my-token-was-here/mezhaka/noarch/mezhaka-storage-5.1.0-pypy_0.tar.bz2 HTTP/2
> Host: conda.anaconda.org
> User-Agent: curl/7.64.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 302
< date: Wed, 20 Jul 2022 17:53:45 GMT
< content-type: text/html; charset=utf-8
< location: https://binstar-cio-packages-prod.s3.amazonaws.com/<...>/<...>?response-content-disposition=attachment%3B%20filename%3D%22mezhaka-storage-5.1.0-pypy_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27mezhaka-storage-5.1.0-pypy_0.tar.bz2&response-content-type=application%2Fx-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=60&X-Amz-Date=20220720T175221Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=<...>&X-Amz-Credential=<...>&X-Amz-Signature=<...>
< cf-ray: 72dd8ee04a0eaca9-TXL
< age: 84
< cache-control: public, max-age=30
< expires: Wed, 20 Jul 2022 17:54:15 GMT
< strict-transport-security: max-age=31536000
< vary: Accept-Encoding
< cf-cache-status: HIT
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< set-cookie: __cf_bm=<...>; path=/; expires=Wed, 20-Jul-22 18:23:45 GMT; domain=.anaconda.org; HttpOnly; Secure; SameSite=None
< server: cloudflare
<
> GET /<...>/<...>?response-content-disposition=attachment%3B%20filename%3D%22mezhaka-storage-5.1.0-pypy_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27mezhaka-storage-5.1.0-pypy_0.tar.bz2&response-content-type=application%2Fx-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=60&X-Amz-Date=20220720T175221Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=<...>&X-Amz-Credential=<...>&X-Amz-Signature=<...> HTTP/1.1
> Host: binstar-cio-packages-prod.s3.amazonaws.com
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< x-amz-request-id: YQNDY4ZFG41JEN6W
< x-amz-id-2: YHXJhik336Dybmjrqu086lVU5Fh2Z6mc1leBtWI2DkzAq/pNg8QQRiA2lp9Y07d9+o2mPDh5v9c=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Wed, 20 Jul 2022 17:53:45 GMT
< Server: AmazonS3
```

**Comment by siamak-attarian** [comment]
same here:

 conda install pytorch cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: #########/.conda/envs/nequip

  added / updated specs:
    - cpuonly
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-2.0                |                0           2 KB  pytorch
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch
    ------------------------------------------------------------
                                           Total:           5 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda_channel/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      conda_channel/linux-64::_openmp_mutex-4.5-1_gnu
  blas               intel/linux-64::blas-1.0-mkl
  bzip2              conda_channel/linux-64::bzip2-1.0.8-hb9a14ef_9
  ca-certificates    conda_channel/linux-64::ca-certificates-2021.10.26-h06a4308_2
  certifi            conda_channel/linux-64::certifi-2021.10.8-py39h06a4308_0
  cpuonly            pytorch/noarch::cpuonly-2.0-0
  intel-openmp       conda_channel/linux-64::intel-openmp-2022.0.2-intel_3658
  intelpython        conda_channel/linux-64::intelpython-2022.0.0-0
  libffi             conda_channel/linux-64::libffi-3.3-14
  libgcc-ng          conda_channel/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            conda_channel/linux-64::libgomp-9.3.0-h5101ec6_17
  mkl                conda_channel/linux-64::mkl-2022.0.2-intel_136
  openssl            conda_channel/linux-64::openssl-1.1.1l-h7f8727e_0
  pip                conda_channel/linux-64::pip-21.2.4-py39h06a4308_0
  python             conda_channel/linux-64::python-3.9.7-h718aa4a_4
  pytorch            pytorch/linux-64::pytorch-1.12.0-py3.9_cpu_0
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cpu
  setuptools         conda_channel/linux-64::setuptools-58.0.4-py39h06a4308_0
  sqlite             conda_channel/linux-64::sqlite-3.36.0-hb9a14ef_3
  tbb                conda_channel/linux-64::tbb-2021.5.1-intel_738
  tk                 conda_channel/linux-64::tk-8.6.10-hbc83047_0
  typing_extensions  intel/noarch::typing_extensions-4.1.1-pyh06a4308_0
  wheel              conda_channel/noarch::wheel-0.37.0-pyhd3eb1b0_1
  xz                 conda_channel/linux-64::xz-5.2.5-h7b6447c_0
  zlib               conda_channel/linux-64::zlib-1.2.11.1-h1e99aa7_5


Proceed ([y]/n)? y


Downloading and Extracting Packages
cpuonly-2.0          | 2 KB      |                                                                               |   0%
pytorch-mutex-1.0    | 3 KB      |                                                                               |   0%

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/cpuonly-2.0-0.tar.bz2>
Elapsed: 00:00.328468

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cpu.tar.bz2>
Elapsed: 00:00.334620

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by TinaJin0228** [comment]
Still facing the same issue when running `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch `:
```
Downloading and Extracting Packages
torchaudio-0.12.0    | 3.7 MB    | ############################################################################ | 100%
pytorch-mutex-1.0    | 3 KB      |                                                                              |   0%

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.232709

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by xym4869** [comment]
Still facing the same issue
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2>
Elapsed: 00:00.085156

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by chengstark** [comment]
Same here, issue persists
`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=10.2 -c pytorch
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /pytorch/noarch/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f910ce4dba8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"))`

**Comment by rdutta1999** [comment]
Issue still persists. 
Created a fresh conda environment and ran `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`.

Fails with the same `CondaHTTPError: HTTP 403 FORBIDDEN` errors.

**Comment by wbjeon2k** [comment]
FYI, installing via pip is available, which is also commented below

https://github.com/pytorch/pytorch/issues/81760#issuecomment-1191008769

**Comment by chenghlee** [comment]
Anaconda.org is having caching issues with its CloudFlare CDN. We are working with CloudFlare to resolve that issue, and in parallel, deploying a hotfix to anaconda.org that should alleviate the problem.

**Comment by chenghlee** [comment]
We've pushed a hotfix to the anaconda.org servers that should mitigate this issue; we will be monitoring it for the next 24 hours or so to verify it works. Please let us know if it does not.

**Comment by bsassoli** [comment]
I just managed to do `conda install -c apple tensorflow-deps` which was what previously failed with `HTTP 403 Forbidden` in my case.

**Comment by GF-Huang** [comment]
I found that it is fixed now in my region.

**Comment by AlexandreBrown** [comment]
It is fixed for me as well (could depend on your dependencies).

**Comment by BrainSlugs83** [comment]
Seems to be working again for some of the pytorch stuff that was broken yesterday.

**Comment by BrainSlugs83** [comment]
Seems like a bit of a miss though that the package outage didn't get logged on the status page yesterday -- as this affected quite a few packages yesterday.

https://anaconda.statuspage.io/

It seems like in the past (4/26 - 4/27) -- this type of issue was logged on this status tracker: https://anaconda.statuspage.io/incidents/t1xrstmkf13x

**Comment by mezhaka** [comment]
I saw the same issue, I described above today around 16:00 UTC.

**Comment by robertsd** [comment]
The issue still persists today and I agree with @mezhaka it should be reported on the status page.

**Comment by adonak** [comment]
I am encountering this issue now. Trying to update Anaconda, gets tripped up at

> Downloading and Extracting Packages
> dal-2021.6.0         | 46.5 MB   | 

Was this just caching issue?

**Comment by Cassieyy** [comment]
I encountered the same error and was able to solve it by running the command "conda config --set offline true".

Ref:https://blog.csdn.net/JJ1018RR/article/details/105395287?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-105395287-blog-125913928.235%5Ev38%5Epc_relevant_sort_base1&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-105395287-blog-125913928.235%5Ev38%5Epc_relevant_sort_base1&utm_relevant_index=1

**Comment by lucasfcnunes** [comment]
Thought maybe the issue was with [another project](https://github.com/devcontainers/images/issues/859#issuecomment-1820028394).

It's still happening. Can someone reopen this?

```bash
# works (alpine)
$ docker run --rm -it alpine wget https://anaconda.org/conda-forge/micromamba/1.5.3/download/linux-64/micromamba-1.5.3-0.tar.bz2

# doesn't work (ubuntu)
$ docker run --rm -it mcr.microsoft.com/devcontainers/base:ubuntu-22.04 wget https://anaconda.org/conda-forge/micromamba/1.5.3/download/linux-64/micromamba-1.5.3-0.tar.bz2
```
