### ISSUE TITLE
Installing R packages within Conda

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#1164]
Dear all,

I have had a look at your article regarding "preliminary support for R with Conda":
http://continuum.io/blog/preliminary-support-R-conda

It is amazing that you are working on this, so thanks so much in advance!

One of our users wanted to install "WGCNA":
http://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/#cranInstall

in our Conda installation, so I tried the following steps:
```
bash ../Miniconda-latest-Linux-x86_64.sh -b -p install
install/bin/conda update conda
install/bin/conda install --override-channels --channel defaults --channel https://conda.binstar.org/asmeurer r
```

Then, opened R and executed:
```
source("http://bioconductor.org/biocLite.R")
biocLite("impute")
install.packages("WGCNA") 
```

as indicated by the installation instructions.

These packages were installed:
"Formula"
"RColorBrewer"
"Rcpp"
"acepack"
"colorspace"
"dichromat"
"digest"
"dynamicTreeCut"
"fastcluster"
"gtable"
"impute"
"iterators"
"labeling"
"matrixStats"
"munsell"
"plyr"
"proto"
"reshape"
"reshape2"
"scales"
"stringr"

While these other packages were not:
'MASS'
'lattice'
'survival'
'ggplot2'
'latticeExtra'
'cluster'
'rpart'
'nnet'
'foreign'
'Hmisc'
'foreach'
'survival'
'doParallel'
'preprocessCore'
'GO.db'
'AnnotationDbi'
'WGCNA'

I see that you are creating R packages for Conda:
https://github.com/conda/conda-recipes/tree/master/r-packages

However, I am wanted to ask you this before going forward and creating the Conda recipes for the R/Bioconductor packages that I could not find on your repository: why is not possible to install packages from CRAN directly? It is going to be a lot of work to add/maintain every R package in sync with Conda recipes. I am sure there must be a reason for that.

Many thanks in advance for your answers.

Best regards,
Sebastian.

**Comment by asmeurer** [comment]
It should be possible to install from CRAN directly. If that doesn't work, it needs to be fixed.

Note that I have currently packaged `r-recommended` separately, so you'll need to install `r-recommended` to get those packages (including many of the ones you found were missing). Quite a few of the ones you want are also in my binstar channel (note that all the R packages are prefixed with `r-`, like `r-ggplot2`). I hope to eventually build packages for them all.

**Comment by asmeurer** [comment]
The reason we are building conda packages for R is the same reason we build conda packages for Python packages. Not everyone is able to compile packages (especially Windows users), and even when you can, it's faster to install things as a conda package, and you get the ability to manage things with conda (e.g., using conda environments for your R workflows).

**Comment by asmeurer** [comment]
I'm going to close this, as it's not an actual issue that needs to be fixed and I don't want to clutter up the open issues list, but feel free to continue discussing things here.

**Comment by jolespin** [comment]
I also need help with this.

**Comment by mingwandroid** [comment]
@jolespin, can you detail your exact problem? This issue is nearly a year and a half old and refers to R-on-Conda when it was more of a work in progress than it is now.

I do not recommend installing packages directly from CRAN as we are not then able to manage `Binary Compatibility` carefully ourselves which is important for any R packages that use compiled language parts since I am not in control of the toolchains used by the CRAN packagers.

I do aim to make sure that you can build packages from CRAN from source on all platforms easily, including Windows via `install.packages(.., type="source")`.

.. before trying that on Windows you want to do:

`conda install posix m2w64-toolchain`
