### ISSUE TITLE
Implement .jlap incremental repodata

### ISSUE THREAD

**Issue by dholth** [conda/conda#11640]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Implement jlap repodata to reduce bandwidth fetching repodata.json

### What should happen?

The conda HTTP cache needs to be replaced. We want to have a per-user cache that better understands http caching rules, and transparently applies diffs when available. This cache may be compatible with mamba. The pickled solver data might remain per-environment.

```[tasklist]
- [ ] https://github.com/conda/conda/pull/12003
- [ ] https://github.com/conda-incubator/ceps/pull/20
- [ ] https://github.com/conda/conda/pull/11447
- [ ] https://github.com/conda/conda/pull/11914
- [ ] https://github.com/conda/conda/pull/12090
- [ ] write unit tests / code coverage tests for branch
- [ ] asv benchmarks?
- [ ] Write test asserting "304 not modified" adds 30 seconds to the local cache validity (avoids checking again for 30s) instead of checking every time after the cache expires once
- [ ] locking: never write cached repodata.json without rewriting cache headers at the same time, while a lock is held. Necessary for jlap only, but wouldn't hurt to have correct locking always.
- [ ] Audit for XXX TODO markers
- [ ] Trace through the code to double-chechk "equivalent when jlap is not enabled" behavior
```

**Comment by dholth** [comment]
Spending time getting up to speed with conda & its tests

**Comment by dholth** [comment]
Work continues at https://github.com/conda/conda/pull/11914

**Comment by LtDan33** [comment]
Is there any test data on how much of an improvement this results in?

**Comment by dholth** [comment]
@LtDan33 For example,

https://repo.anaconda.com/pkgs/main/linux-64/repodata.json is a 37MB file, normally downloaded as a 5.3M gzip'd response.

The `jlap` feature also adds support for  zstandard-compressed `repodata.json.zst`. On an empty cache, the `jlap` feature will download the complete 37M `repodata.json` as a 4.7M https://repo.anaconda.com/pkgs/main/linux-64/repodata.json.zst.

On the second request, the `jlap` feature will look for and download the complete `repodata.jlap`. Right now this is a 603k compressed transfer of a 3.8M file; the server limits this file to 10MB by removing older patches.

On subsequent requests, the `jlap` feature only downloads any new bytes added to the end of a growing `repodata.jlap`, which depends on how much the repository has changed. As I write this, the last five patches are 19K.

That's 7.8 times fewer bytes transferred for the first update, and 247 times fewer bytes transferred for subsequent updates.
