### ISSUE TITLE
Conda crashed after installing nvidia driver

### ISSUE THREAD

**Issue by mastermert** [conda/conda#11656]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Hello all; 

I have been using Ubuntu 22.04 virtual machine and installed conda via miniconda with no problem, after some time I have added GPU(RTX3090) to my ubuntu VM and installed additional drivers with no problem (Nvidia-driver 515). However after installing driver conda crashed. I cannot create any environment and `conda info` returns nothing also I cannot run any Python code. I removed and tried to reinstall conda with both mini forge and mamba forge however nothing is changed. 

I even tried to delete and rebuild whole virtual machine from zero, and this time I installed Nvidia-drivers first then tried to install conda but nothing is changed. 

I don't think this issue related with my Proxmox Virtual Environment since I can install drivers and `nvidia-smi` works with no problem.

### Linked Issues & PRs

- [x] #9942

**Comment by jaimergp** [comment]
Might be related to the CUDA version detection logic. What happens if you set `CONDA_OVERRIDE_CUDA=11 conda info`?

**Comment by EmileForker** [comment]
@mastermert From my experience cuda runtime version (installed with driver) doesn't matter. What matters is cuda toolkit version & python. 

Could you please tell: 

CUDA runtime (from `nvidia-smi`)
CTK version (`nvcc --version` or `ls -l /usr/local | grep cuda`)
Python version (`python -V`)

**Comment by mastermert** [comment]
@EmileForker Thank you for your answer. Here are the versions;
CUDA runtime: 11.7 
CTK version: 11.7, V11.7.64
Python version: 3.9.12

**Comment by mastermert** [comment]
@jaimergp Thank you for your answer and sorry for my late response, I set `CONDA_OVERRIDE_CUDA=11 conda info` and it returns `conda info` with no problem. 
Also I can create environments if I set `CONDA_OVERRIDE_CUDA=11 conda create -n test python=3.9`.  it seems that I should make this virtual package override permament from CONDA source files.

**Comment by jaimergp** [comment]
Yes, that's an annoying but safe workaround. Just make sure that env var is set to the version of your CUDA runtime (11.7, if I am reading correctly). The problem with `conda` is in this [module](https://github.com/conda/conda/blob/e69b9efd5fc96e26bb2aa3b180e3c504c65ce65f/conda/common/cuda.py#L46); for some reason loading `libcuda.so` results in a crash in your setup. Maybe we could check it in a subprocess to make it safer or something, but that adds some overhead in _every_ conda execution.

**Comment by jaimergp** [comment]
I think if you run this code, without running conda, you can reproduce the errors:

```
$ conda activate base
$ python -v -c "from conda.common.cuda import cuda_detect; print(cuda_detect())" 2>&1 | tee log.txt
```

This will generate a `log.txt` you can attach here, which will hopefully contain some details to help debug the reason of the crash.

**Comment by mastermert** [comment]
@jaimergp I don't understand why problem is related with `libcuda.so`. I ran `sudo find /usr/ -name 'libcuda.so*' and it returns;

/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.515.48.07
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so

I checked the [module](https://github.com/conda/conda/blob/e69b9efd5fc96e26bb2aa3b180e3c504c65ce65f/conda/common/cuda.py#L46) you shared and `libcuda` paths seem to be correct. Can we try a method makes `CONDA_OVERRIDE_CUDA=11.7` default every time I run `conda info` ?

**Comment by mastermert** [comment]
@jaimergp Thank you for sharing codes. Here is the `log.txt` file. 
[log.txt](https://github.com/conda/conda/files/9220297/log.txt)

**Comment by jaimergp** [comment]
As expected, the last line is the `ctypes` import:

```
import 'ctypes' # <_frozen_importlib_external.SourceFileLoader object at 0x7f64075f3910>
```

And we don't see anything after (like Python cleaning up tasks), so that's when it crashes. The path might be correct, but there's a weird interaction between your `libcuda.so` and your Python install; or more accurately, CUDA 11.7 as packaged on Ubuntu and the way we are checking the CUDA version. Maybe that API is no longer correct for the libraries/drivers in use?

We can schedule a videocall if you want, so we debug together. DM me on gitter.im to arrange details in that case!  https://gitter.im/jaimergp
