### ISSUE TITLE
Installing packages from Binstar on Travis-CI is failing with SSL verification errors

### ISSUE THREAD

**Issue by shoyer** [conda/conda#1166]
I'm not sure if this was an update to Binstar or Travis but something has gone wrong today with continuous integration tests run on Travis-CI that rely on conda. Any build that installs from a non-default channel is getting errors like the following:
```
Could not connect to https://conda.binstar.org/ajdawson/linux-64/cdat-lite-6.0rc2-np18py27_1.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581): https://conda.binstar.org/ajdawson/linux-64/cdat-lite-6.0rc2-np18py27_1.tar.bz2
```

For examples, see [pandas](https://travis-ci.org/pydata/pandas/builds/51915152) and [xray](https://travis-ci.org/xray/xray/builds/51917430) (the failing builds here are exactly those that use non-default channels)

**Comment by Cadair** [comment]
I am getting this error on my desktop linux machine with miniconda.

**Comment by jreback** [comment]
``conda config --set ssl_verify false`` will turn off this feature, e.g. [here](https://github.com/pydata/pandas/commit/9796a9f10b11318f0a214d77db3ad79023491d72)

**Comment by Cadair** [comment]
@jreback thanks for the workaround.

**Comment by asmeurer** [comment]
Don't disable your ssl verification. We are building the new version of requests that will fix this now.

**Comment by asmeurer** [comment]
`conda update requests` should fix this.

**Comment by asgarJ** [comment]
In my case, neither of ways mentioned above worked separately, but both together worked fine!

`conda config --set ssl_verify false`
`conda update requests`
`conda install <package_name>` (`pyodbc` in my case)

**Comment by asmeurer** [comment]
I recommend re-enabling ssl verification if you can.

**Comment by vineetp13** [comment]
I am upgrading conda and did the following with the resulting error:

```
conda config --set ssl_verify false
conda update requests
conda config --set ssl_verify true
```
Could not connect to https://repo.continuum.io/pkgs/free/osx-64/libpng-1.6.17-0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/osx-64/libpng-1.6.17-0.tar.bz2

**Comment by caseyjlaw** [comment]
This workaround is not working for me. I am still seeing this on linux and mac osx with miniconda.

    > conda config --set ssl_verify false
    > conda update requests
    Fetching package metadata: ....
    # All requested packages already installed.
    # packages in environment at /users/claw/miniconda:
    #
    requests                  2.7.0                    py27_0  
    > conda config --set ssl_verify true
    > conda install scipy
    Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    .SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    .SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    .SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by hargup** [comment]
None of the workarounds is working for me either. I'm on GNU/Linux 64 bit using the python 2.7 version of anaconda.

**Comment by hargup** [comment]
@vineetp13 @caseyjlaw After struggling for few hours I got my issue resolved, taking a hint from https://github.com/ContinuumIO/anaconda-issues/issues/137 I used `strace` and found that conda was using certificates from the package `certifi`. Removing `certifi` fixed the issue for me.

**Comment by zbessinger** [comment]
@hargup Thanks! This resolved my issue!

**Comment by liujiantong** [comment]
this works on my ubuntu:
conda config --set ssl_verify false

**Comment by m1sta** [comment]
@hargup +1

**Comment by juhucoding** [comment]
For me, 

    conda config --set ssl_verify false
    conda config --set ssl_verify true

did work.

**Comment by eroicaleo** [comment]
@hargup +1
I did the following and it works for me. I am using Mac OS X 10.11.1.
```
conda remove certifi
conda install certifi
```
