### ISSUE TITLE
Encoding error occure when use conda activate command in git-bash for windows

### ISSUE THREAD

**Issue by LSun0717** [conda/conda#11661]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

**when use conda activate command in git-bash for windows ,** 
**error info are as follows**
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Development_DL\miniconda\lib\site-packages\conda\exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "D:\Development_DL\miniconda\lib\site-packages\conda\cli\main.py", line 111, in main_sourced
        print(activator.execute(), end="")
    UnicodeEncodeError: 'gbk' codec can't encode character '\u202a' in position 1445: illegal multibyte sequence

reason:
windows username is Chinese characters, and it is included in some path

solution:
modify the source code in miniconda\lib\site-packages\conda\cli\main.py, line 110
print(activator.execute(), end="")
modified: print(activator.execute().encode('gbk', 'ignore').decode('gbk'), end="")

### Conda Info

```shell
active environment : base
    active env location : D:\Development_DL\miniconda
            shell level : 2
       user config file : C:\Users\孙龙\.condarc     
 populated config files : C:\Users\孙龙\.condarc     
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __cuda=11.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Development_DL\miniconda  (writable)
      conda av data dir : D:\Development_DL\miniconda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Development_DL\miniconda\pkgs
                          C:\Users\孙龙\.conda\pkgs
                          C:\Users\孙龙\AppData\Local\conda\conda\pkgs
       envs directories : D:\Development_DL\miniconda\envs
                          C:\Users\孙龙\.conda\envs
                          C:\Users\孙龙\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.13 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : C:\Users\孙龙/.netrc
           offline mode : False
```

**Comment by travishathaway** [comment]
This is a known issue and we currently have a ticket for this issue in our backlog: https://github.com/conda/conda/issues/11064

Please follow this issue for future updates.
