### ISSUE TITLE
XGBoostError: [19:55:25] c:\users\administrator\workspace\xgboost-win64_release_1.6.0\src\data\array_interface.h:462: Unicode-3 is not supported

### ISSUE THREAD

**Issue by namandalsania** [conda/conda#11685]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While running a streamlit app I am facing an error mentioned below:

`XGBoostError: [19:55:25] c:\users\administrator\workspace\xgboost-win64_release_1.6.0\src\data\array_interface.h:462: Unicode-3 is not supported.`

![image](https://user-images.githubusercontent.com/86463390/182877160-b2e72650-2a40-436e-8ac6-95fe3b17ce38.png)

The model works perfectly. Attaching the code used in the model below:

`step1 = ColumnTransformer(transformers=[
  ('col_tnf',OneHotEncoder(sparse=False,drop='first'),[0,1,7,10,11])
],remainder='passthrough')

step2 = XGBRegressor(n_estimators=45, max_depth=5, learning_rate=0.5)

pipe = Pipeline([
  ('step1', step1),
  ('step2', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

print('R2 score', r2_score(y_test, y_pred))
print('MAE score', mean_absolute_error(y_test, y_pred))`

Need some help to solve it. Thanks.

**Comment by sah003** [comment]
same issue , did u got any solution ?

**Comment by namandalsania** [comment]
No mate.

**Comment by jaimergp** [comment]
This is not related to `conda`, I am afraid. Your dataset must have some Unicode in it that is breaking XGBoost.

**Comment by VaishnaviKrishnamoorthy** [comment]
hi facing same error when i load it in fastapi frame work what i need to do now any way

**Comment by rkatriel** [comment]
I got the same type of error on a Mac

`xgboost.core.XGBoostError: [12:19:20] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-37/xgboost/src/c_api/../data/array_interface.h:462: Unicode-3 is not supported.`

It was caused by (unintentionally) passing non-numerical (string) feature values in the training data to XGBClassifier (when calling the fit method).

**Comment by Ansh13579** [comment]
[namandalsania] should your error is fixed
