### ISSUE TITLE
DYLD_LIBRARY_PATH not correctly set

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#1169]
In the current environment that I created with conda, it seems ``DYLD_LIBRARY_PATH`` is not set:

```
$ conda info -s
sys.version: 3.4.2 |Continuum Analytics, Inc.| (defau...
sys.prefix: /Volumes/Raptor/miniconda3
sys.executable: /Volumes/Raptor/miniconda3/bin/python3
conda location: /Volumes/Raptor/miniconda3/lib/python3.4/site-packages/conda
conda-build: None
conda-env: /Volumes/Raptor/miniconda3/bin/conda-env
user site dirs: ~/.local/lib/python2.6
                ~/.local/lib/python2.7
                ~/.local/lib/python3.1

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: production
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /opt/local/bin:/opt/local/sbin:/Volumes/Raptor/miniconda3/envs/production/bin:/Volumes/Raptor/Library/Python/3.4/bin:/opt/pgi/osx86-64/13.2/bin:/Volumes/Raptor/anaconda/bin:/Volumes/Raptor/usr/hyperion/bin:/usr/texbin:/Volumes/Raptor/.gem/ruby/1.9.1/bin:/opt/local/bin:/opt/local/sbin:/opt/local/lib/mysql5/bin:/opt/local/lib/postgresql90/bin:/usr/local/hdf5/ifort/bin:/usr/local/mpich2/ifort/bin:/Volumes/Raptor/usr/Montage_v3.3/bin:/opt/pgi/osx86-64/11.10/bin:/Volumes/Raptor/Dropbox/usr/bin:/Volumes/Raptor/usr/bin:/Volumes/Raptor/Library/Python/3.4/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
```

This is causing issues because when installing h5py, which links against the HDF5 installation in ``/Volumes/Raptor/miniconda3/envs/production/lib/``, if I try and import the module, I get:

```
ImportError: dlopen(/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/h5py-2.5.0a0-py3.4-macosx-10.5-x86_64.egg/h5py/_errors.so, 2): Library not loaded: libhdf5.9.dylib
  Referenced from: /Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/h5py-2.5.0a0-py3.4-macosx-10.5-x86_64.egg/h5py/_errors.so
  Reason: image not found
```

If I manually set:

```
export DYLD_LIBRARY_PATH=/Volumes/Raptor/miniconda3/envs/production/lib/:$DYLD_LIBRARY_PATH
```

then import ``h5py``, everything works.

This suggests that there is a bug in conda and ``DYLD_LIBRARY_PATH`` should be set to the environment's ``lib`` directory.

Running ``export`` manually is not a good long-term solution because it has to be re-run anytime I switch environments.

**Comment by astrofrog** [comment]
Huh, but once ``DYLD_LIBRARY_PATH`` is set, Matplotlib no longer works:

```
In [2]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/backends/__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/backends/backend_macosx.py in <module>()
     22 
     23 import matplotlib
---> 24 from matplotlib.backends import _macosx
     25 
     26 

ImportError: dlopen(/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/backends/_macosx.so, 2): Symbol not found: __cg_png_create_info_struct
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Volumes/Raptor/miniconda3/envs/production/lib//libpng15.15.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

Any ideas?

**Comment by asmeurer** [comment]
DYLD_LIBRARY_PATH should not be set. As you noticed, setting it leads to problems. Your best bet for fixing this now is to install the h5py conda package, which doesn't have the issue you described. If you for some reason can't, DYLD_FALLBACK_LIBRARY_PATH is better (although note that it has a default that you should include, see `man dyld`). 

See https://github.com/conda/conda-build/pull/312 for more information.

**Comment by astrofrog** [comment]
@asmeurer - thanks - just out of curiosity, is there a reason that conda doesn't then set ``DYLD_FALLBACK_LIBRARY_PATH`` for this kind of situation?

For some background, the reason I needed the latest developer version of h5py is because it contains a critical bug fix (and the release cycle of h5py is quite slow)

**Comment by asmeurer** [comment]
It's not needed. Conda build automatically changes the paths of the libraries using install_name_tool when they are built, so that they are relative (look at `otool -L` on one of the library files installed by conda). If DYLD_FALLBACK_LIBRARY_PATH were required, then an environment would *have* to be activated to be useable (meaning you couldn't just call the absolute paths to an environment). This further complicates things if you want to combine run programs from different conda environments. Also, DYLD_LIBRARY_PATH changes everything, not just the conda packages it is intended to change, meaning that setting it could break something else. It's not as likely as DYLD_LIBRARY_PATH, but still possible. The current approach with install_name_tool on the other hand only changes those libraries that specifically link against the dependent libraries to use relative paths. 

For your h5py, you will either need to use that DYLD_FALLBACK_LIBRARY_PATH, or build a conda package for it with conda build (there is a conda recipe for h5py in the conda-recipes repo that you should be able to modify).

**Comment by astrofrog** [comment]
@asmeurer - thanks for the clarification!
