### ISSUE TITLE
SPIKE 🔍: fetch plugin feature research

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11696]
### What is the idea?

In preparation to work on #11600 we need a spike to:
- figure out what features we're trying to cover with plugin hooks when it comes to repo interaction
- which level they should be provided in conda and
- what do we do with the existing implementation.

Much of this has already been proposed as part of https://github.com/conda-incubator/ceps/pull/14 but it's worth spelling out what the repo interaction plugin hooks need before we dive into implementation.

### Timebox

_3 days_

### What should happen?

- [x] The deliverables should include at least one case study and how the fetch plugin will address this. This should cover at least the use case in [the above mentioned CEP proposal](https://github.com/conda-incubator/ceps/pull/14) but could also include others. The case study could be written as an extensive comment on this issue or as a separate document on [HackMD](https://hackmd.io).

**Comment by LtDan33** [comment]
Shouldn't we rename this to the "fetch plugin feature research" or is this something different?

**Comment by travishathaway** [comment]
Here is a link to the HackMD article I wrote which includes my case study for implementing a fetch plugin for conda:

- https://hackmd.io/@IwbgOGzZSMevbee5x54nzg/HJTT7X3zs

Additionally, I have also created a "prototype" pull request which illustrates some of the ideas introduced in that HackMD article:

- https://github.com/conda/conda/pull/11971
