### ISSUE TITLE
Two recipes present?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#11701]
### What is the idea?

Currently, there are two recipes in this repo. Wonder if we should consolidate these down to one.

* https://github.com/conda/conda/tree/bb62b3becf611ad57950c7d16e4e9faa9856eabe/conda.recipe
* https://github.com/conda/conda/tree/bb62b3becf611ad57950c7d16e4e9faa9856eabe/recipe

### Why is this needed?

Remove confusion over which recipe to update.

### What should happen?

Delete one.

**Comment by kenodegard** [comment]
Not 100% sure why we have two. I'm guessing `recipe` is for local/dev/debug builds? `conda.recipe` is the one used for our [canary builds](https://github.com/conda/actions/blob/f1e744d3e212034f62962cd9a0dcd70fa2f0dee6/canary-release/action.yml#L75).
