### ISSUE TITLE
app/summary section in meta.yaml not respected in binstar after forced re-push

### ISSUE THREAD

**Issue by sstirlin** [conda/conda#1172]
I pushed a package without a summary to binstar.  Realizing my folly, I added a summary section to my meta.yaml recipe like so:

app:
  summary:  An awesome library that kicks ass

Then I rebuilt and did a

binstar upload --force

to replace the package.  However, the summary is not showing up in the binstar web browse.  Is this intended?

For example, see the 'p4python' package in our channel:

binstar.org/ActivisionGameScience

Thanks!

**Comment by ilanschnell** [comment]
This is either conda-build or a binstar issue.  Let me look into it.
