### ISSUE TITLE
anaconda does not launch

### ISSUE THREAD

**Issue by Alejandro58581** [conda/conda#11733]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When I click the anaconda button  after 2 seconds only appear a window and never launch

![image](https://user-images.githubusercontent.com/82003215/185422277-b5e1a624-0460-4266-8ace-844cd362fbbf.png)

**Comment by kenodegard** [comment]
Please provide the following details (this can be run in a normal CMD.exe terminal):

```
C:\Users\alega\anaconda3\Scripts\conda.exe info
C:\Users\alega\anaconda3\Scripts\conda.exe config --show-sources
C:\Users\alega\anaconda3\Scripts\conda.exe list --show-channel-urls
```

**Comment by Alejandro58581** [comment]
![image](https://user-images.githubusercontent.com/82003215/185440205-a47853e6-6589-4889-87bc-686056d3ae98.png)
![image](https://user-images.githubusercontent.com/82003215/185440320-a2792878-60c0-4c18-84a1-99f1d94ef781.png)
![image](https://user-images.githubusercontent.com/82003215/185440580-6babcd06-7efc-4ecc-8e19-d527c998acb8.png)
![image](https://user-images.githubusercontent.com/82003215/185440705-0ab7bb88-94df-45ee-af52-42e9212b0419.png)
![image](https://user-images.githubusercontent.com/82003215/185440783-85d8fa78-ed89-4e9b-ab15-5d4b06258b46.png)
With the last command, the channel for all of them is default

I don´t know if it is important but I recently  update anaconda and also update spyder but some issue happened and I had to close the prompt window

**Comment by kenodegard** [comment]
@Alejandro58581 assuming the Anaconda update was successful I suggest uninstalling `spyder` and seeing if that fixes the issue:

```
C:\Users\alega\anaconda3\Scripts\conda.exe remove -n base spyder
```
