### ISSUE TITLE
`conda shell.posix activate/deactivate` should write out to `fd` 3, not `stdout`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11748]
### Description

~Since `conda activate` and `conda deactivate` are special commands that actually invoke hidden subcommands (i.e. `conda shell.posix activate|deactivate`) and evaluate what is printed to `stdout` we need a different way to communicate with the user for things like `conda activate --help`.~

After the initial PR #11749 we realized that we didn't like the consequences of moving everything over to `stderr`.

Instead, we reimagined the problem and realized it should instead be possible to use different file descriptors (`fd`) to pipe out the content that the `conda activate/deactivate` command is expected to evaluate.

```[tasklist]
- [x] https://github.com/conda/conda/pull/11862
- [ ] https://github.com/conda/conda/pull/11865
- [ ] https://github.com/conda/conda/pull/11812
- [ ] Change: Need to update `dev/**/*` scripts to use the new `--fd` and `--tmp` arguments when calling `conda init --dev`
- [ ] Change: Expose `--fd` and `--tmp` to `conda shell.* hook`
- [ ] Add: Implement `argparse` for `conda.cli.main.main_sourced`
```

**Comment by travishathaway** [comment]
@kenodegard, see my comment in the open pull request related to this issue. I don't think this is the right way forward.

Currently, `conda activate --help` returns a help message albeit with an exit code of `1` (`conda --help` returns with the appropriate error code of `0`). This isn't ideal, but seems like a fair work around. What exactly is the main motivation for changing this behavior?

I would be happy to help brainstorm another approach with you.

**Comment by travishathaway** [comment]
@kenodegard, see my comment in the open pull request related to this issue. I don't think this is the right way forward.

Currently, `conda activate --help` returns a help message albeit with an exit code of `1` (`conda --help` returns with the appropriate error code of `0`). This isn't ideal, but seems like a fair work around. What exactly is the main motivation for changing this behavior?

I would be happy to help brainstorm another approach with you.
