### ISSUE TITLE
Inconsistency in meta data `icon` field

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1176]
There are multiple different things that the `icon` could be:
- An md5 filename (local packages)
- Full remote URL to a file (repo data)
- Local installed packages have `icondata` which is a base64 field of the contents of the data

Currently I have to check multiple things to simply display an image:
- Is `icondata` not null?  Display base64-embedded image
- Is `icon` present and contains `://`?  Assume it references full URL and display without change
- Is `icon` present without `://`?  Assume it references a filename and prefix with base URL

There needs to be some form of consistency here.

**Comment by ilanschnell** [comment]
I suggest taking the icon handling completely out of conda, and not treat it has metadata anymore.
Simply have a special location in the install prefix where icon png's get installed, eg:
`share/icons/<pkg_name>.png`
However, there still needs to be a way to handle remove icons.

**Comment by asmeurer** [comment]
The repos still need to serve the icons somehow, though, so that the launcher doesn't have to download packages just to show icons for them.

**Comment by tswicegood** [comment]
@asmeurer you are correct.  My suggestion is to make all of the meta data available the same way it would be on the file system so I could simply ask for `pkgspec/icon.png` from the index and get the correct thing back.  It's the same way I can ask for that data out of the tarball or the package cache.

At this point, I have a work around in the launcher.  This is more a note to myself to remember when I'm going about fixing things that need fixing.

**Comment by kalefranz** [comment]
FYI @goanpeca
