### ISSUE TITLE
Conda creates $HOME/.condarc even if another configuration file exists

### ISSUE THREAD

**Issue by slavistan** [conda/conda#11765]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I keep my *$HOME* clean and store my Conda configuration in *$XDG_CONFIG_HOME/conda/.condarc*. Unfortunately, whenever I use the Conda cli to add or set configuration parameters, a new config file at *$HOME/.condarc* is created.

Here's what happens:

```
conda config --show-sources
# ==> /home/stan/.config/conda/.condarc <==
# channels:
#   - conda-forge
#   - defaults

conda config --add channels conda-canary
conda config --show-sources
# ==> /home/stan/.config/conda/.condarc <==
# channels:
#   - conda-forge
#   - defaults
# 
# ==> /home/stan/.condarc <==
# channels:
#   - conda-canary
#   - defaults
```

I would have expected Conda to use the existing configuration file instead of creating a new one.

Thank you!

### Conda Info

```shell
active environment : pytorch_cuda3090
    active env location : /home/stan/.conda/envs/pytorch_cuda3090
            shell level : 1
       user config file : /home/stan/.condarc
 populated config files : /home/stan/.config/conda/.condarc
                          /home/stan/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.19.1=0
                          __glibc=2.36=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/stan/.conda/pkgs
       envs directories : /home/stan/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.12 Linux/5.19.1-arch2-1 arch/rolling glibc/2.36
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/stan/.config/conda/.condarc <==
channels:
  - conda-forge
  - defaults
```

**Comment by travishathaway** [comment]
Hi @slavistan,

Thank you for submitting this. In our documentation, it's state that:

> The `.condarc` file is not included by default, but it is automatically created in your home directory the first time you run the conda config command.

Following from that, I would say that this behavior, although undesirable in your case, does not represent a bug. I think what you want is to be able to specify a custom default location for this configuration file. For example, this could be accomplished by defining a `CONDA_CONFIG_FILE` environment variable. In that case, this would be a feature request.

I would encourage you to submit a feature request instead if this is in fact the behavior you'd like to see in future releases. In the meantime, I am going to close this issue.

**Comment by slavistan** [comment]
@travishathaway Thank you for the kind reply.

>I think what you want is to be able to specify a custom default location for this configuration file.

No, not quite. My issue is that conda's behavior is inconsistent with respect to the  *$XDG_CONFIG_HOME* envvar. The sole purpose of the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is to standardize the location of configuration files (among others). conda acknowledges the existence of *$XDG_CONFIG_HOME*, as it is explicitly included in the [list of searched .condarc paths](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc), but then proceeds to ignore it completely when writing out user configuration created via the cli.

This behavior is very surprising and I respectfully suggest to you that this is an outright error. Usage of *$XDG_...* implies certain semantics, which are not accounted for by conda. 

I recognize that my initial question was poorly worded. I should have titled it "Conda creates *$HOME/.condarc* even if *$XDG_CONFIG_HOME/conda/.condarc* exists".
