### ISSUE TITLE
'Error: Unsatisfiable package specifications' shows no conflicting packages

### ISSUE THREAD

**Issue by soerendip42** [conda/conda#1177]
Hi, 

I just installed theano:
conda install theano

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.5.3             |           py27_0         593 KB
    conda-env-2.1.3            |           py27_0          15 KB
    scipy-0.15.1               |       np19py27_0        37.0 MB
    conda-3.9.1                |           py27_0         164 KB
    ------------------------------------------------------------
                                           Total:        37.7 MB

Now, I cannot connect to the chembl database anymore:
import chembl_webresource_client as cwc
from chembl_webresource_client.settings import Settings
targets   = cwc.TargetResource()
targets.status()
<ipython-input-11-6502be524350> in <module>()
      2 from chembl_webresource_client.settings import Settings
      3 targets   = cwc.TargetResource()
----> 4 targets.status()

/usr/lib/python2.7/site-packages/chembl_webresource_client/web_resource.pyc in status(self)
     89     def status(self):
     90         service = self.get_service()
---> 91         if not 'status' in service:
     92             return False
     93         return service['status'] == 'UP'

So, I thought, maybe I need to upgrade the other packages.

conda update --all
Fetching package metadata: ....
Solving package specifications: ..
Error: Unsatisfiable package specifications

Is all I get. There is no information about the conflicting packages, although it should be the case according to http://conda.pydata.org/docs/examples/update.html:
"[...] will generate a hint regarding which packages conflict with one another."

What can I do? Can I undo the changes from the last package installation somehow?

**Comment by asmeurer** [comment]
Conda no longer tries to generate a hint when it would take forever (which is going to always be the case with `conda update --all`). You can get a different kind of hint with `--alt-hint`. 

Also make sure you have the latest version of conda (3.9.1). There were some changes recently that make `conda update --all` work much better.

**Comment by teramind** [comment]
Thanks! So, there is no undo, right? I haven't found anything.

Yes, I have 3.9.1:
             platform : linux-64
        conda version : 3.9.1
  conda-build version : 1.9.1
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /home/swacker/Programme/anaconda  (writable)
  default environment : /home/swacker/Programme/anaconda
     envs directories : /home/swacker/Programme/anaconda/envs
        package cache : /home/swacker/Programme/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
You can list previous installed states with `conda list --revisions` and revert to one with `conda install --revision=<rev number>`.

**Comment by teramind** [comment]
Thanks! That worked!

**Comment by ArthurZ** [comment]
And that did not work for me. I ended up deleting the Anaconda folder. Then re-installing it.

**Comment by asmeurer** [comment]
The latest version of conda (`conda update conda`) will generate a hint with `conda update --all`.
