### ISSUE TITLE
`pip install conda` fails on Python 3.10

### ISSUE THREAD

**Issue by bitplane** [conda/conda#11771]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`pip install conda` fails with the following error on Python 3.10:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]

      WARNING: Your current install method for conda only supports conda
      as a python library.  You are not installing a conda executable command
      or activate/deactivate commands.  If your intention is to install conda
      as a standalone application, currently supported install methods include
      the Anaconda installer and the miniconda installer.  If you'd still like
      for setup.py to create entry points for you, use `utils/setup-testing.py`.

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gaz\AppData\Local\Temp\pip-install-99j1hrxr\conda_bc085c2aa1d94c45a7efc1f261ebcfb6\setup.py", line 35, in <module>
          import conda._vendor.auxlib.packaging  # NOQA
        File "C:\Users\gaz\AppData\Local\Temp\pip-install-99j1hrxr\conda_bc085c2aa1d94c45a7efc1f261ebcfb6\conda\__init__.py", line 13, in <module>
          from .common.compat import iteritems, text_type
        File "C:\Users\gaz\AppData\Local\Temp\pip-install-99j1hrxr\conda_bc085c2aa1d94c45a7efc1f261ebcfb6\conda\common\compat.py", line 77, in <module>
          from collections import Iterable
      ImportError: cannot import name 'Iterable' from 'collections' (C:\Users\gaz\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
      [end of output]
```

`Iterable` is now under `collections.abc`, it's been deprecated for a while and was finally removed in Python 3.10

### Additional Context

> Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9.

**Comment by travishathaway** [comment]
Hi @bitplane 

conda is currently not intended to be installed via `pip`. If you'd like to install conda, please use the appropriate `miniconda` installer for your operating system: https://docs.conda.io/en/latest/miniconda.html

We are planning to entire remove `conda` from PyPI. You can follow progress on that issue here: https://github.com/conda/conda/issues/11715

**Comment by bitplane** [comment]
Ah that kinda sucks given that `pip` is the standard way to install things in Python. I can see why you wouldn't care about it as most of the ML people are used to installing Anaconda, but it seems a bit wierd and ugly to Python people
