### ISSUE TITLE
always have an env started in any case (for entry points on all OS too)

### ISSUE THREAD

**Issue by ReimarBauer** [conda/conda#11787]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently when I  setup an entry point 
```

 entry_points:
    - msui = mslib.msui.msui:main

```

this creates on linux a shell script, on windows an executable which starts over the python in the env the script

e.g. for linux

```
#!/home/reimar/miniconda3/envs/mssenv/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from mslib.msui.msui import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

I would prefer this activates the env and afterwards calls the main program (entry point)

### Why is this needed?

all environment vars are set identical to a program version started manually from the env.

e.g. 
PROJ_LIB
CONDA_PREFIX

### What should happen?

We have not to fix the symptoms just because how the program was started, see discussion on

https://github.com/Open-MSS/MSS/pull/1543#pullrequestreview-1089831573

The entrypoint starter should look similiar to:

```
#!/bin/bash
__conda_setup="$('/home/reimar/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/reimar/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/reimar/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/reimar/miniconda3/bin:$PATH"
    fi
fi
conda activate mssenv

python -m mslib.msui.msui
```

### Additional Context

This is a design change for entry points.
Always initialize envs similiar as with `conda activate`.

**Comment by ReimarBauer** [comment]
@jezdez please have a look on this.

**Comment by ReimarBauer** [comment]
see also discussuib about env var PROJ_LIB in this thread
https://github.com/conda-forge/basemap-feedstock/issues/30#issuecomment-419155681

"""Jupyterlab (and similar things) that uses the kernel without activating the envs are a problem."""

**Comment by ReimarBauer** [comment]
windows is not having this problem.

**Comment by travishathaway** [comment]
@ReimarBauer,

Have you considered using something `conda run` to execute your entry points instead? (https://docs.conda.io/projects/conda/en/stable/commands/run.html)

I wondering whether you have also considered simply writing custom scripts to the `bin` location while building your package? This could be a potential work-around.

I will leave this feature request open but will warn you that it is not very likely going to be implemented. Also, https://github.com/conda/conda-build is the more appropriate place to file this types of feature requests.
