### ISSUE TITLE
Python 2 conda doesn't work with Unicode directory names

### ISSUE THREAD

**Issue by heekyungyoon** [conda/conda#1180]
![conda install launcher unicode error](https://cloud.githubusercontent.com/assets/9113419/6526187/44e75734-c452-11e4-9cac-6ff0ef34e7ef.PNG)

For some reason, Anaconda Launcher was not included in the package and I tried to install myself with 'conda install launcher' command.

However, it doesn't seem to work.

I'm suspecting that my folder name being Korean is a reason but I can't change the folder name...

How can I install 'Anaconda Launcher'?

**Comment by asmeurer** [comment]
Looks like a bug in conda for Python 2. I suspect this will work if you use Anaconda3 or Miniconda3.

**Comment by asmeurer** [comment]
Can you paste the directory name here so I can copy it and test against it (I don't know how to type it)?

**Comment by heekyungyoon** [comment]
Thanks for quick response!

Here's the directory name.

C:\Users\윤희경\Anaconda

**Comment by asmeurer** [comment]
This looks like it will be a pain to fix. I *highly* recommend using Anaconda3. This problem won't exist at all there.

**Comment by heekyungyoon** [comment]
Thanks for your help:)
Maybe I'll try with my Ubuntu virtual machine since I need to use 2.7 version for my coursework.
-----Original Message-----

**Comment by asmeurer** [comment]
You can still use Python 2.7 with Anaconda3. Use conda to create a Python 2 environment, like

```
conda create -n py2 python=2 anaconda
activate py2
```

The important thing is that in Anaconda3, conda itself will be running in Python 3, so there won't be any issues (even if you use it to create a Python 2 environment).

**Comment by asmeurer** [comment]
Did this actually get fixed?

**Comment by jin10086** [comment]
![image](https://cloud.githubusercontent.com/assets/15347911/26759866/46749bbc-493d-11e7-87b8-d89c3b872634.png)
I found the same problem here
but i add one line `print result_path`
and run conda 
![image](https://cloud.githubusercontent.com/assets/15347911/26759872/6f4edcd2-493d-11e7-8c7d-8689d95d8221.png)
i find chinese，and i remove this ,
 But this directory is still here，

**Comment by asmeurer** [comment]
@jin10086 Looks like asnlcrypto has a bug there. Your best bet is to use Anaconda3, which shouldn't have this issue.

**Comment by jin10086** [comment]
@asmeurer ok thanks

**Comment by kedarpathak** [comment]
def read_dataset(file_path):
	with open(file_path, 'rb') as f:
		return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5: ordinal not in range(128)

**Comment by mbargull** [comment]
> We are not on Python 3 yet and can't migrate anytime soon..

If you are tied to some Python 2-only software stack, I highly recommend to put this into a separate Conda environment. That way you are free to use Python 3 in other environments, esp. `base`, and you would be able to avoid many of those Python 2 related problems.
