### ISSUE TITLE
trust: CI/CD trust metadata testing

### ISSUE THREAD

**Issue by awwad** [conda/conda#11805]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Part of #11804:
Add integration tests for trust metadata operations (e.g. verification, discarding, warning) for:
- a good root update
  - including after a purge of $CONDAROOT .json files
- a bad root update
- key_mgr updates
  - be sure to include key mgrs with multiple signatures and a threshold of 2 or more

Currently, tests exist only in conda-content-trust, which is not helpful.

**Comment by jezdez** [comment]
It seems as if https://github.com/conda/conda/pull/12591 satisfies some of the points here, but I also don't completely know.

@sven6002 @kenodegard Could you please review the changes in the PR in the context of this ticket and decide how much was done?
