### ISSUE TITLE
Why is the `conda initialize` block placed in `.bashrc` on Linux, but in `.bash_profile` on macOS + Windows?

### ISSUE THREAD

**Issue by pavelzw** [conda/conda#11830]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I don't really understand why the `conda initialize` section is placed in the `.bashrc` when using conda on Linux and in the `.bash_profile` when initialising conda on macOS or Windows (see [here](https://github.com/conda/conda/blob/0dbf85e0546e0b0dc060c8265ec936591ccbe980/conda/core/initialize.py#L439)). 

I created a small git blame timeline [here](https://github.com/mamba-org/mamba/issues/1913#issuecomment-1242991342). 

@kalefranz you were responsible for adding the conda initialize block to the `.bash_profile` instead of `.bashrc` on macOS. Is there a reason for it?

This seems weird to me, especially since the macOS terminal sources the `.bashrc` by default when executing `bash` in the command line. 
`bash` sources the `.bashrc` when executed in the interactive mode (i.e. `bash -i`) and the `.bash_profile` when using the login mode (i.e. `bash -l`). In a regular terminal, the interactive mode is the default. See the [bash man page](https://man7.org/linux/man-pages/man1/bash.1.html#INVOCATION).

Here is a small list when which rcfile gets sourced (this is the same for Ubuntu and macOS, haven't tested Windows but I suppose it's the same...):
* `.bashrc` gets sourced when executing `bash` or `bash -i` in the terminal. 
* `.bash_profile` gets sourced when executing `bash -l` in the terminal. 
* *Only* `.bash_profile` gets sourced when executing `bash -il`

### What should happen?

This can be confusing; therefore, we should have better documentation surrounding this behavior. Please update the documentation for this repository accordingly.

**Comment by jaimergp** [comment]
From https://scriptingosx.com/2017/04/about-bash_profile-and-bashrc-on-macos/:

> However, Terminal.app on macOS, does not follow this convention. When Terminal.app opens a new window, it will run .bash_profile. Not, as users familiar with other Unix systems would expect, .bashrc.

🤷

**Comment by pavelzw** [comment]
Thanks! It may be that Apple changed this though during their switch to zsh in 2019 with macOS Catalina… I’ll look into this.

**Comment by jonashaag** [comment]
- On recent versions of macOS, Terminal.app comes preconfigured with zsh. I'm assuming it doesn't source either of the `.bash*` files?
- If you override the default shell in Terminal.app to bash (even if it's `/opt/homebrew/bin/bash`) it will start `login -pfq <username> bash` instead. In this case `.bashrc` will not be sourced and `.bash_profile` will be sourced.

I didn't check: What's iTerm2's behaviour when using bash?

**Comment by pavelzw** [comment]
> What's iTerm2's behaviour when using bash?

It's loading `.bash_profile`, too.

I think it would make sense to add a comment in the code to document this whole `.bashrc`/`.bash_profile` thing.

**Comment by travishathaway** [comment]
Hi @pavelzw,

I think that's a great idea to document it. I will categorize and put it in our backlog. We will get to it when we can, but this isn't a high priority issue for us.

If you would like to help out by making a contribution yourself, you are more than welcome and we will be happy to assist.

**Comment by pavelzw** [comment]
Okay, so I did some testing on Windows. Git Bash, Cygwin as well as MSYS2 all use `.bash_profile` by default so using this makes sense. I'll open a PR with some documentation soon.
