### ISSUE TITLE
conda init mess up AutoRun

### ISSUE THREAD

**Issue by YouJiacheng** [conda/conda#11832]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Previously there is https://github.com/conda/conda/issues/10309, PR https://github.com/conda/conda/pull/10305 add `if exist` try to fix it.
But it introduce new problem:
+ https://stackoverflow.com/questions/66901281/the-conda-init-command-is-messing-up-my-cmd-startup-in-win10
Said conda init change `AutoRun` to `if exist & if exist`
+ https://github.com/pre-commit/pre-commit/issues/2402#issuecomment-1133662353
Said conda change `AutoRun` improperly and cause "The system cannot find the path specified."(might caused by an old version conda)
+ For me, it change `AutoRun` to `if exist` (after uninstall conda) and break VSCode Remote SSH and pre-commit.

This problem seems hard to reproduce...

**Comment by jaimergp** [comment]
It might be the combination of an old uninstaller not accounting for the `if exist` clause and a new installation after the faulty uninstall.

See https://github.com/conda/constructor/pull/521 for the fix in newer constructor versions (to be released).

**Comment by YouJiacheng** [comment]
I believe https://github.com/conda/constructor/pull/521 will solve my problem!
