### ISSUE TITLE
Binary nose package not properly registering the distutils entry point.

### ISSUE THREAD

**Issue by mforbes** [conda/conda#1183]
Currently, the ``nose-1.3.4-py27_0`` package contains ``lib/python2.7/site-packages/nose-1.3.4-py2.7.egg-info`` rather than the directory ``lib/python2.7/site-packages/nose-1.3.4.dist-info`` installed by ``pip install nose``.  This somehow does not properly register the ``distutils`` ``nosetest`` entry-point, breaking ``python setup.py nosetests`` as described in [this nose issue](https://github.com/nose-devs/nose/issues/873).

I'm not sure exactly what the problem is, but it would probably be solved by rebuilding the current package with a recent version of ``pip`` or ``setuptools``.

P.S. If this is not the correct place for submitting broken package issues, please let me know where the should go instead as it is not clear from the documentation.

**Comment by mforbes** [comment]
This is also an issues with the ``flake8`` package for which ``python setup.py flake8`` fails with the binary installation of ``flake8``.

**Comment by asmeurer** [comment]
A better place is https://github.com/continuumio/anaconda-issues.

**Comment by mforbes** [comment]
Okay.  I have migrated the issue.

**Comment by mforbes** [comment]
@asmeurer The migrated issue seems to be ignored.  Any suggestions on how to go about fixing this?
