### ISSUE TITLE
conda env create gives confusing message if environment file does not exist and name is given

### ISSUE THREAD

**Issue by AdrianFreundQC** [conda/conda#11839]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Related to #5681.

`conda env create` gives a confusing error message if a non existing env file *and* a name are given.

* `conda env create -f missing.yml`: `EnvironmentFileNotFound: '/Users/adrian/missing.yml' file not found`
* `conda env create -f missing.yml -n test`: `SpecNotFound: Invalid name, try the format: user/package`

The reason for this behaviour is in https://github.com/conda/conda/blob/main/conda_env/specs/__init__.py#L20 and I'm currently looking into fixing it.

**Comment by travishathaway** [comment]
Thanks for submitting this @AdrianFreundQC 

Please let us know once you have a fix. We'll be happy to review it.

**Comment by AdrianFreundQC** [comment]
I have created #11883 14 days ago and signed the CLA. The bot says someone has to manually review my CLA signature. How long does that usually take?

**Comment by AdrianFreundQC** [comment]
@travishathaway Any update on the review?

**Comment by travishathaway** [comment]
Hi @AdrianFreundQC,

Thanks for linking to your pull request. I will take a look at this later today. Follow the pull request for further updates.
