### ISSUE TITLE
CondaError: Operation failed. Privileged install disallowed for 'conda init --dev'.

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11848]
### What happened?

If running `.\dev\start.bat` and the `devenv` already exists, we are consistently getting a misleading error:

```
> .\dev\start.bat
Updating devenv-3.8-c...
Initializing shell integration...
menuinst called from non-root env C:\Users\kodegard\.conda\devenv\Windows\envs\devenv-3.8-c

CondaError: Operation failed. Privileged install disallowed for 'conda init --dev'.

'dev-init.bat' is not recognized as an internal or external command,
operable program or batch file.
Error: failed to initialize shell integration
```

**Comment by kenodegard** [comment]
This is caused by the updated binaries from #11676.

What happens is:
1. we launch the `conda init` process which attempts to update all of the entry points
3. since the `cli-*.exe` binaries were updated in #11676 `conda init` attempts to update `conda.exe` (which is just a renamed copy of, e.g., `cli-64.exe`)
4. the update fails because we cannot replace/modify the executable while in use (shakes fist at Windows)

This appears to resolve itself if we instead do a `conda install` from canary (in other words `conda install` is smarter with copying files than `conda init`). Alternatively, we can also just do a manual copy of the correct `cli-*.exe` and update `conda.exe` on our own:

```cmd.exe
cd <path\to\conda\source>

copy conda\shell\cli-64.exe devenv\Windows\envs\devenv-3.8-c\Scripts\conda.exe

.\dev\start.bat
```

**Comment by jezdez** [comment]
@jaimergp Do you have time to take a look at this?

**Comment by kenodegard** [comment]
With the conda 22.9.0 release, this should no longer be an issue since running `dev/start`/`dev\start.bat` will update the environment (and hence these `.exe` entry points) before running `conda init --dev`.
