### ISSUE TITLE
`conda update conda` doesn't update root.

### ISSUE THREAD

**Issue by Ismael-VC** [conda/conda#1184]
The [FAQ](http://docs.continuum.io/anaconda/faq.html#update-anaconda) states that using `conda update conda` and `conda update anaconda` should update the root environment, however this is what I get:

* Anaconda version:
```
C:\Users\CSM>python
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1
500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>>
```

* Update `conda`:

```
C:\Users\CSM>conda update conda
Error: This installation of conda is not initialized. Use 'conda create -n
envname' to create a conda environment and 'source activate envname' to
activate it.

# Note that pip installing conda is not the recommended way for setting up your
# system.  The recommended way for setting up a conda system is by installing
# Miniconda, see: http://repo.continuum.io/miniconda/index.html
```

* Update `anaconda`:

```
C:\Users\CSM>conda update anaconda
Error: This installation of conda is not initialized. Use 'conda create -n
envname' to create a conda environment and 'source activate envname' to
activate it.

# Note that pip installing conda is not the recommended way for setting up your
# system.  The recommended way for setting up a conda system is by installing
# Miniconda, see: http://repo.continuum.io/miniconda/index.html
```

I don't want to install a new updated environment, I just want `conda` to update the root environment as mentioned in the documentation.

**Comment by asmeurer** [comment]
How did you install conda?

**Comment by Ismael-VC** [comment]
Hello @asmeurer.

I installed Anaconda some weeks ago, using the default Windows installer: 

* [`Anaconda-2.1.0-Windows-x86_64.exe`](http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.1.0-Windows-x86_64.exe)

**Comment by asmeurer** [comment]
I think your Anaconda install may be broken. I recommend deleting it and reinstalling.

**Comment by Ismael-VC** [comment]
Ok thanks! I will do that and let you know. Right now I'm at work (this is my workstation) and I don't have more time left to do that, but I will do it tomorrow first thing in the morning.

On a side note, I had Anaconda installed, then I installed [GitStack](http://gitstack.com/), which I uninstalled immediately as it screwed up my `PATH` (it installed it's own Python) rendering Anaconda unable to load any non-standard module, but I also re installed Anaconda that day, so do you think that garbage left by another Python install might still be messing with my Anaconda install somehow or something like that?

Cheers.

**Comment by asmeurer** [comment]
I can't say for sure what happened.

**Comment by Ismael-VC** [comment]
@asmeurer I re installed and had the same problem, after that I downloaded again de `.exe` re installed again and it worked. 

It would be nice if you provided `md5sum`s on the download page or something like that to check the integrity of the installer, thanks!

**Comment by asmeurer** [comment]
There are md5 sums at http://repo.continuum.io/archive/index.html.

**Comment by Ismael-VC** [comment]
Thanks for the link!
