### ISSUE TITLE
--use-local breaks on missing file:/// repos

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda#1185]
I've got a system install in /opt (root owned)  I run conda-build (as a local user, not as root) and so the package is written to /Users/hugo/conda-bld/osx-64/.    Then if I try to install the package using conda install <pgname> --use-local, I get an error because file:///opt/anaconda/conda-bld/osx-64 is not a valid url (presumably because I've never built a package there, and so there is no repo there)

If I run conda-build with sudo, then the package is built into /opt/anaconda/conda-bld, and then the problem goes away

My guess is that the fix is that --use-local should be robust to missing local repos?

**Comment by asmeurer** [comment]
I take it you're running conda install with sudo.

**Comment by hhuuggoo** [comment]
yes

**Comment by asmeurer** [comment]
I don't think this can be fixed then, as you are currently using conda. If conda can't write to the conda-bld directory in the root environment directory, it uses `~/conda-bld`. But `~` is going to be a different directory when you are sudo, so even if we made `--use-local` fallback, it would look in a different place than where the package is. 

The easiest fix for you is to add

```
conda-build: /Users/hugo/conda-bld
```

to your `.condarc` (to whatever rc file will be seen by sudo).

**Comment by hhuuggoo** [comment]
oh sorry - I think I understand what you are saying and now I agree that the current behavior is correct. thanks
