### ISSUE TITLE
'conda update -n base conda'  interrupted and all anaconda products disabled

### ISSUE THREAD

**Issue by 664787022** [conda/conda#11867]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I try to update conda with `conda update -n base conda`, but something wrong happened and it is interrupted.  After i restart my computer, i cannot use Anaconda Navigator, spyder or Anaconda Prompt. 
I also found my environment variable path was changed, so i manually add `/anaconda/Script`, '/anaconda/Library/bin' into the path. However, it didn't help.
Another phenomeno is that filenames of many files in 'anaconda/Script' are added with a suffix of '.c~'
I attempted to run python with vscode using previous environment and anaconda interpreter. However, when i entered 'pip list', it showed only two module (pip 22.2.1 and setuptools 63.2.0). And when i entered 'conda list', it raised an error:
Traceback (most recent call last):
  File "D:\Software\anaconda\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ImportError: cannot import name 'main' from 'conda.cli' (unknown location)

I don't know what happened to my conda. How can i fix it?

### Conda Info

```shell
raise an error
Traceback (most recent call last):
  File "D:\Software\anaconda\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ImportError: cannot import name 'main' from 'conda.cli' (unknown location)
```

### Conda Config

```shell
raise an error
Traceback (most recent call last):
  File "D:\Software\anaconda\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ImportError: cannot import name 'main' from 'conda.cli' (unknown location)
```

### Conda list

```shell
raise an error
Traceback (most recent call last):
  File "D:\Software\anaconda\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ImportError: cannot import name 'main' from 'conda.cli' (unknown location)
```

**Comment by travishathaway** [comment]
Hi @664787022,

Thanks for filing this issue. At this point, I would recommend a complete re-install. It seems like something has been corrupted on your local computer.

In meantime, I will be closing this issue.
