### ISSUE TITLE
conda should check write permissions of $PWD immediately (or stop using $PWD)

### ISSUE THREAD

**Issue by michaelkarlcoleman** [conda/conda#11861]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently, if $PWD is unwritable, this will eventually fail, but only after the "Solving environment" step, which may take many hours.  If would be best to attempt to write a junk file immediately, so that this problem can be discovered without a lengthy waste of time.

Or, alternatively, just stop trying to write to $PWD completely (using a temp dir instead).

### Why is this needed?

This would reduce user frustration, etc., with a rather trivial change.

### What should happen?

Determine on startup whether $PWD is unwritable, and quit immediately if so.

**Comment by travishathaway** [comment]
Hi @michaelkarlcoleman,

Thanks for the feature request. For your information, we now have a better dependency solver available: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community Perhaps that will help with those long solving times.

I'll add this issue to a general user experience epic we've been collecting similar too:

- https://github.com/conda/conda/issues/12259
