### ISSUE TITLE
PREFIX replacement on Windows is too greedy

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1187]
Seeing issues where:

``` batch
@"/opt/anaconda1anaconda2anaconda3\Scripts\iojs.exe" %* 
```

Is turning in to:

``` batch
@"C:\Miniconda\envs\some-env\iojs.exe" %* 
```

Once linked.  That shouldn't be the case.

**Comment by asmeurer** [comment]
What are the contents of `info\has_prefix` for that package?

**Comment by tswicegood** [comment]
@asmeurer here's the contents:

```
"/opt/anaconda1anaconda2anaconda3" text "Scripts/node.cmd"
"/opt/anaconda1anaconda2anaconda3" text "Scripts/node_modules/npm/bld.bat"
```

**Comment by asmeurer** [comment]
Hmm. I can't guess from the code why this would be happening. It's literally just using Python's str.replace on the contents of the file https://github.com/conda/conda/blob/7b8e4425f8d3bc1ccb6daedd72e25247f37626ba/conda/install.py#L257. 

I'll see if I can reproduce it.

**Comment by asmeurer** [comment]
Do you already have a build uploaded somewhere? If not, I'll build it. It's https://github.com/conda/conda-javascript-recipes/commit/015081936d0fa1757570f795caf95f6b3dea63e4 right?

**Comment by tswicegood** [comment]
That's the one.

Note, the workaround for now is to use `%~dp0`.

**Comment by asmeurer** [comment]
I tried it out, but I'm unable to reproduce this, both in Python 2 and Python 3.
