### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by MAQI7** [conda/conda#11876]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

![error](https://user-images.githubusercontent.com/97730261/191951277-09490f48-1512-4c87-bd46-e68397eb236f.png)
An error is reported when executing conda.exe. Where can I find the associated code

**Comment by travishathaway** [comment]
Hi @MAQI7,

If you are still having a problem with this issue we ask you to create a new issue on this project:

- https://github.com/ContinuumIO/anaconda-issues/

This GitHub project is not for any issues that arise during the installation process.
