### ISSUE TITLE
Confirmation request when installing packages in base environment

### ISSUE THREAD

**Issue by tjex** [conda/conda#11878]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Sometimes the mistake can be made where package installation is done accidentally in the base environment, rather than a project environment. 
This can happen because of lack of experience or just accidentally when opening a new terminal window for a new process - meaning that the user default / base conda environment is activated for that interactive shell session. 

This feature request approaches mitigating the ramifications of this mistake. 

### Why is this needed?

Having a clean and smooth base environment is a nice thing. And installing a bunch of packages in the default environment by mistake is also a pain. 
So having an option confirmation request only when installing packages in the base environment could be a valuable feature. 

### What should happen?

If the user is in the default / base environment, and they install a package, a confirmation request needs to be answered, eg: this will install <packages> in the _**default**_ conda environment, do you wish to proceed?

**Comment by ForgottenProgramme** [comment]
Thank you for raising this. It is a reasonable request but right now the base env is not supposed to be special. We are investigating extracting conda from the base env and in which case something like this would be more important. 
See: https://github.com/conda/conda/issues/11342

**Comment by jezdez** [comment]
FWIW this is somewhat related to #11878.
