### ISSUE TITLE
Example links 404 in Sample Recipes page on conda docs

### ISSUE THREAD

**Issue by kathatherine** [conda/conda#11894]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The links to the GitHubs for example recipes on https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/sample-recipes.html currently return 404 errors.

Looks like these links might have been mistakenly changed to include `main` during our inclusive language push, when conda-archive still uses `master` as its main repo name.

**Comment by ForgottenProgramme** [comment]
>Looks like these links might have been mistakenly changed to include main during our inclusive language push, when conda-archive still uses master as its main repo name.

@kathatherine 
Yes, looks like that. Because I can access the recipes when I replace 'main' with 'master' in the links to the recipes.
I think we need to move the 'conda-archive' repo from 'master' to 'main' as well.

**Comment by jezdez** [comment]
I just unarchived the repo and renamed the branch real quick. Thanks for bringing this up!
