### ISSUE TITLE
Docs needed on `channel::package` syntax available in environment.yaml file

### ISSUE THREAD

**Issue by kathatherine** [conda/conda#11890]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Per comments on #7202, the documentation is lacking on the `channel::package` syntax available in environment.yaml files, in order to specify the channel from which a package should be downloaded during environment creation. Docs on this should be added to https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually, and probably referenced elsewhere in the Managing environments page.

### Why is this needed?

So users are aware this feature exists and can more easily specify package locations during environment creation.

**Comment by jezdez** [comment]
Closed in #12213.

**Comment by skandermoalla** [comment]
I couldn't find anywhere whether the channel would also apply to the dependencies of the package prefixed with the channel, or if it only applies to the package itself (and its dependencies would be searched in the other channels first).
Anyone can help?
@jezdez
