### ISSUE TITLE
"conda install" could create a "hint list" of symlinks to be used by "conda clean"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1191]
I just noticed that `conda clean -p` states "Warning: this does not check for symlinked packages".  

Presumably this is potentially very bad: someone who runs "conda clean -p" could blast a stack of packages that are only linked to via symlinks, and destroy the operational environment of many other people, perhaps even including their own.

Perhaps a first-step improvement on this would be for "conda install" (and, I suppose, "conda create" by implication) commands that are going to create symlinks to also have those operations somehow register a sym-link "hint" for the package so there is a two-way record that the sym-link exists.  Flat files would be the easiest way to do this, accepting that there will be file/directory permission issues, and problems if there is ever concurrent operations.

In any case, if such a "sym-link hint list" existed it would then be possible for "conda clean" to check to see if those sym-links existed (assuming a uniform file system view from the environment where "conda clean" is being executed, and anywhere else the associated conda environments are accessible).  Packages would only be cleaned if there were no valid sym-link hints.

**Comment by Lothiraldan** [comment]
:+1:

**Comment by kalefranz** [comment]
This proposal is technically incompatible with multi-user conda systems and read-only package caches.  We actively discourage symlinks directly to package caches.
