### ISSUE TITLE
Builds on conda-canary channel are surprisingly large

### ISSUE THREAD

**Issue by dholth** [conda/conda#11938]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Around https://anaconda.org/conda-canary/conda/files?page=32 the conda-canary builds went from 3.1MB to 16MB. conda appears to have a large amount of test data in its info/ part.

Apply https://github.com/AnacondaRecipes/conda-feedstock/pull/6/files to conda's embedded recipe (or the recipe used on conda-canary) and conda's package should be < 1MB.

**Comment by jezdez** [comment]
This has been fixed by #12603.
