### ISSUE TITLE
Control order of list when calling `conda list`

### ISSUE THREAD

**Issue by mattijn** [conda/conda#11954]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Include an order control option for `conda list`. 
This can be something as `conda list --reverse` or `conda list --descending` or `conda list --desc`

### Why is this needed?

I often have to deal with a package that starts with an `a`. When I check the installed packages in a terminal of a large environment (~500 packages) using `conda list` I see myself scrolling a loong way up.

### What should happen?

Reverse the order of the list of installed packages.

So instead of the following result:
```cmd
# packages in environment at D:\Software\Miniconda3\envs\stable:
#
# Name                    Version                   Build  Channel
adagio                    0.2.3                    pypi_0    pypi
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
...
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge

(stable) D:\Software>
```
You will get the following result:
```cmd
# packages in environment at D:\Software\Miniconda3\envs\stable:
#
# Name                    Version                   Build  Channel
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
...
adagio                    0.2.3                    pypi_0    pypi
affine                    2.3.1              pyhd8ed1ab_0    conda-forge

(stable) D:\Software>
```

**Comment by jaimergp** [comment]
You can use `conda list --json` and pipe it into `jq` to post-process it to your liking! Or use a pager like `less`? I know this is Windows but you can still install those packages with `conda` :)

**Comment by travishathaway** [comment]
Hi @mattijn,

I just wanted to let you know that I have added the https://github.com/conda/conda/labels/good-first-issue label to the issue so that it may get more attention. I believe this would be a relatively easy task for a new contributor.

Unfortunately, this most likely won't be completed by the core maintainers any time soon. Keep an eye on this issue for updates.

**Comment by HeavenEvolved** [comment]
Hi @travishathaway,

I would like to work on this. Kindly assign it to me. Thank you!
