### ISSUE TITLE
Conda create fails with --file

### ISSUE THREAD

**Issue by michs** [conda/conda#1195]
The following command sequence fails. Manual changes of the created package list are necessary.

```
$ conda list -e >conda-packages
$ conda create -m -p $(pwd)/myenv --file conda-packages 
Error: Package 'conda' may only be installed in the root environment
```

Packages that cannot be installed should be ignored and the user be informed by a warning. Alternatively a question for continuation of the command without installing this packages could be asked.

**Comment by asmeurer** [comment]
Alternately, we could make `conda list -e` not include conda and packages that depend on conda by default.

**Comment by michs** [comment]
Yes, or a new option for creating a package list intended for installation purposes would work.

Any solution that works straightforward is fine. The problem now is that the approach "take the editor and remove this or that" cannot be used with less experienced users, and, even if it is documented now, things could change...
