### ISSUE TITLE
Slimming down the conda package by splitting the test data into a separate package

### ISSUE THREAD

**Issue by seibert** [conda/conda#11972]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

While doing some investigation to understand why a fresh miniconda install uses 406 MB on disk, I discovered that one of the largest single users of space on disk is the [test data](https://github.com/conda/conda/tree/main/tests/data) that is included in the package.  This subtree is installed to `$CONDA_PREFIX/info/test/tests/data`. (ok, technically the files are unpacked into the package cache and hardlinked to the to conda prefix, but you get the idea.)  This test data accounts for 91MB of the 96MB used by the entire the conda package (version 4.12.0 in this case), which is also 22% of the disk space of a freshly installed miniconda base environment.

### Why is this needed?

Making miniconda as minimal as possible is a good goal for minimizing resource usage across all use cases, especially as people try to make environments super small for Docker and "serverless" situations.  I do like the idea of conda packages to be self-testing whenever possible, but I think in this case a small exception would be merited.

### What should happen?

If possible, I think the idea solution would be for the 91MB of test data to be split out into a `conda-test-data` package that is a test dependency of the `conda` package.  I don't know if conda-build would allow one recipe to produce both packages (since one package would be the test dependency of another package in the same recipe), but if possible, that would be a straightforward solution.  Then if someone wants to run the conda tests on their own system, they only need to `conda install conda-test-data`.  The `conda-test-data` package could then be left out of the miniconda installer, reducing the size of the conda base environment by 22%.

**Comment by dholth** [comment]
This may have already been fixed in the newest conda feedstock.

**Comment by seibert** [comment]
Oh neat!  Is there a link to that?

**Comment by dholth** [comment]
https://github.com/AnacondaRecipes/conda-feedstock/commit/35b26285a076ec12dc06275422f56221aabeaf5e

**Comment by seibert** [comment]
OK, i can confirm that the conda-22.9.0 package unpacks to only 5.2 MB, which is great.  Now we just need new Miniconda installers with that version of conda.  :)

**Comment by dholth** [comment]
I think this is still an issue for conda's embedded recipe. I have mixed feelings about including tests in packages. The test data is also unnecessarily big and contains third-party packages.
