### ISSUE TITLE
Move 'governance' from conda-incubator to conda

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda/conda#11984]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Governance is now mature enough to exist in conda instead of conda-incubator.

### Why is this needed?

We have a Code of Conduct Committee, our Code of Conduct has been written, we're also now fiscally sponsored by NumFOCUS. 

### What should happen?

- [ ] [Governance](https://github.com/conda-incubator/governance) should be migrated to conda from conda-incubator.

**Comment by jezdez** [comment]
Closing in favor of https://github.com/conda-incubator/governance/issues/80
