### ISSUE TITLE
Remove pyupgrade from merge requirements

### ISSUE THREAD

**Issue by dholth** [conda/conda#11997]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

pyupgrade is amazing. It automatically translates working code to equivalent code, making our code more fashionable but not more functional. We are spending time struggling with pyupgrade for no technical benefit. It can also crash on valid Python code.

Allow PR's to be merged even if they don't pass pyupgrade.

**Comment by travishathaway** [comment]
I think this is worth discussing if it is causing problems for you, but I also think it's worth getting other's input too.

I, for one, have not run into any issues with `pyupgrade` 🤷. Is there an example of a particular problem you've had?

**Comment by dholth** [comment]
I feel like I spend a significant amount of time dealing with trivial nitpicks from these linters.
