### ISSUE TITLE
source deactivate gives unhelpful "No environment" message

### ISSUE THREAD

**Issue by cjerdonek** [conda/conda#1199]
When I try executing `source deactivate`, I get the unhelpful message:

    $ which python
    /Users/chris/anaconda/bin/python
    $ source deactivate
    Error: No environment to deactivate

This is on Mac OS X.  I'm not sure why deactivate isn't working.  It seems like either deactivate should work or the error message should be more helpful (e.g. say what the corrective action is or where to go for more help on this issue).

**Comment by cjerdonek** [comment]
And here is some more info:

    $ conda info
    Current conda install:

                 platform : osx-64
            conda version : 3.7.0
      conda-build version : 1.8.2
           python version : 2.7.8.final.0
         requests version : 2.4.1
         root environment : /Users/chris/anaconda  (writable)
      default environment : /Users/chris/anaconda
         envs directories : /Users/chris/anaconda/envs
            package cache : /Users/chris/anaconda/pkgs
             channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                            http://repo.continuum.io/pkgs/pro/osx-64/
              config file : None
        is foreign system : False

**Comment by asmeurer** [comment]
There is no environment to deactivate because you need to use `source activate` to activate an environment first.

**Comment by cjerdonek** [comment]
Okay, thanks.  Maybe saying that in the error message would help.

I had the misunderstanding that deactivate was the way to deactivate anaconda itself (i.e. by removing `/Users/chris/anaconda/bin` from my path, a viewpoint which is supported by the output of `conda info`).  You can improve the message or close this issue.  Thanks for the help.
