### ISSUE TITLE
Make conda's tests 10% faster

### ISSUE THREAD

**Issue by dholth** [conda/conda#11994]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

On a successful conda test run like this one https://github.com/conda/conda/actions/runs/3265018387/usage, the CI tests (not other tasks like building images or checking the CLA) take `15h 2m 10s` running several times across multiple platforms.

(Since they run in parallel, we don't have to wait quite that long).

Make the tests 5% faster repeatedly.

95% 14.25h
90% 13.5h
85% 12.h

**Comment by travishathaway** [comment]
@dholth, so what should happen here? 😅 It's not clear to me...

**Comment by travishathaway** [comment]
Okay, that sounds like that is going to be quite a bit of work! No idea when/if this will ever get prioritized... 😭😭😭

Although, this could potentially be a nice "hackathon" project if we ever manage to get a group of people together in real life to work on such a thing. There is hope!

**Comment by travishathaway** [comment]
I went ahead and assigned you to this issue so you can help advocate for it 😉

**Comment by dholth** [comment]
I'll run the tests from 23.9 and 22.9 locally and see how they compare.
