### ISSUE TITLE
Improve/hide `failed with initial frozen solve. Retrying with flexible solve`

### ISSUE THREAD

**Issue by maximlt** [conda/conda#12007]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I often see this message when installing packages with conda:

    Solving environment: failed with initial frozen solve. Retrying with flexible solve.

The message is:

- quite difficult to understand: what is a frozen/flexible solve?
- seems alarming. While as far as I understand, it indicates that conda couldn't solve my request (e.g. install numpy=1.0.0) with the current package versions available in my environment and that it has to upgrade/downgrade/remove some of them to find a solution. conda anyway lists the changes it has to make, if any, to the users when it asks for confirming the install.

I suggest two alternative improvements:
- Improving the error message to make it more understandable and not alarming, with e.g. `Solving environment: found that changes to the current set of installed packages are required.`
- Or, only show this message in verbose mode

**Comment by THEdavehogue** [comment]
similar to #12008  -- see comments added there
