### ISSUE TITLE
Add auth handler plugin hook

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12018]
### What's the idea?

In order to allow conda to handle more means of authentication, a new plugin hook will be created. Please see the following pull request for more detailed information:

- https://github.com/conda/conda/pull/12911

### More background information

- [Conda Fetch Plugin Case Study: HTTP Basic Authentication](https://hackmd.io/hEfgjgMsT-WSQYVRc_9N2A?view) HackMD Document
- https://github.com/conda/conda/issues/11696
- https://github.com/conda/conda/pull/11971

**Comment by dholth** [comment]
We need a good test harness that spins up proxies with various authentication methods, and any other flavor of repository we can think of.

**Comment by travishathaway** [comment]
> 

This is work that should be included in a separate issue.

**Comment by dholth** [comment]
Also, it may want to accept a Channel object instead of a channel string.

**Comment by dholth** [comment]
e.g.

1. Conda opens 5 parallel requests to protected-repo
2. They all fail, but they pause, blocking conda
3. The session manager opens a user's web browser exactly once to do an OIDC flow (log in)
4. They all try again with the new login cookie
5. Conda finishes the transfer
6. If they tried again (step 4) but the new login cookie did not work, do not repeat step 3.
