### ISSUE TITLE
Show all subcommands, including `activate` and `deactivate`, from `conda --help`

### ISSUE THREAD

**Issue by benjamin-heasly** [conda/conda#12029]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

It would be helpful to see all available `conda` subcommands when I type `conda help` or `conda --help`.  Currently (I have conda 4.9.2) I don't see `activate` or `deactivate` in the help text, even though `activate` is what I learned to do from the (excellent) [Getting started](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) guide, and even though I do have conda 4.6+.

### Why is this needed?

As a new user, I needed a reminder of what to type, to get back into conda on my second day.  IMO, `conda --help` should be the source of truth for the version I have installed, but in this case I had to resort to external means like googling for the pan-version docs on the web.

Since `activate` isn't in the help text, I'm wondering what other important commands I might have but don't know about!

### What should happen?

When supported, like in versions 4.6+, the help text from `conda --help` should list `activate` and `deactivate` as available (important!) commands.  Something along the lines of

```
$ conda --help
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    activate     Activate an existing environment by name <-- *new*
    deactivate   Return to the base environment           <-- *new*
    clean        Remove unused packages and caches.
etc...
```

### Additional Context

```
$ conda info

     active environment : base
    active env location : /home/***/anaconda3
            shell level : 1
       user config file : /home/***/.condarc
 populated config files : /home/***/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/***/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/***/anaconda3/pkgs
                          /home/***/.conda/pkgs
       envs directories : /home/***/anaconda3/envs
                          /home/***/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-113-generic linuxmint/19.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

**Comment by travishathaway** [comment]
Hi @benjamin-heasly,

Thanks for this feature request. This is definitely reasonable.

The reason it is not currently listed alongside those other commands is because `activate` and `deactivate` are actually run as shell functions. To be honest, `conda` itself is actually a shell function (you can see this for yourself by  running `which conda` in your terminal).

The commands that you see on the help page are the ones that are actually primarily implemented and in Python.

Anyways, we actually already have an issue for tracking this feature defect:

- https://github.com/conda/conda/issues/6353

Please follow the progress over there, and if you believe you have a solution to this issue and would like to submit a pull request please do so and reference the issue above.

In the meantime, I will be closing this issue.
