### ISSUE TITLE
conda.testing.integration.make_temp_env is slow

### ISSUE THREAD

**Issue by dholth** [conda/conda#12025]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The integration tests call `with make_temp_env()`, executing conda in a subprocess, and calling out to the network.

```
In [1]: from conda.testing.integration import *
In [2]: import logging
In [3]: logging.basicConfig(level=logging.DEBUG)
In [4]: with make_temp_env('pip') as p: ...

EXECUTING COMMAND >>> $ conda create --dev -p 
... lots of output
```

This might be sped up by forcing offline mode (if the cache exists), specifying an exact pre-solved set of packages, making one temp enviroment per run and copying it, running a local tests package server, ...

**Comment by dholth** [comment]
Possibly make the test environment, run conda export, and import that again when making the next one during a single test run...

**Comment by dholth** [comment]
#12026

**Comment by kenodegard** [comment]
@dholth is this moot since we now have the `conda_cli` fixture?

**Comment by dholth** [comment]
Probably not.
