### ISSUE TITLE
Remove most pytest arguments from setup.cfg

### ISSUE THREAD

**Issue by dholth** [conda/conda#12030]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`setup.cfg` has a complicated set of pytest arguments that conflict with running the tests in a debugger (coverage and debugging conflict).

Instead, we could have a separate test configuration for CI.

Is there another convenient way to toggle a big set of pytest arguments?

**Comment by kenodegard** [comment]
@dholth Which arguments are causing issues for you locally?

**Comment by dholth** [comment]
I comment out these locally. `--cov` also slows the tests down, but mainly I need to run them in the debugger.

```
    # --cov-report xml
    # --cov-report term-missing
    # --cov conda
    # --cov-append
```

**Comment by kenodegard** [comment]
Ah, yeah I'm always running pytest with `--no-cov`
