### ISSUE TITLE
ncl not available in conda installed using Miniconda3-latest-MacOSX-arm64.sh

### ISSUE THREAD

**Issue by prabshr** [conda/conda#12036]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I installed conda in my Mac Book (Apple M2 chip) using the "Miniconda3-latest-MacOSX-arm64.sh"
However, when I try to install ncl, it does not seems to be available. Could anyone help out here?

**Comment by ihaseeburrehman** [comment]
I am also struggling with the same issue, I have Mac M1-max. I think we need to install using precompiled libraries. You can see this (https://www.ncl.ucar.edu/Download/install_from_binary.shtml). 
NCL is currently available for osx64 not for arm64 ,through condo.
