### ISSUE TITLE
conda intermittent seg-fault when packaging on MacOSX-x86_64

### ISSUE THREAD

**Issue by KrisThielemans** [conda/conda#12034]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm not 100% sure if I should file this here or on mambaforge, conda-forge, so feel free to close this here.

I'm updating our [stir-feedstock](https://github.com/conda-forge/stir-feedstock), and am getting occasional seg-faults on the Azure pipelines on OSX when it is packaging the installed files. An example is at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=600355&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=43154
```
Packaging stir
INFO:conda_build.build:Packaging stir
Packaging stir-5.0.2-py39h578b638_3
INFO:conda_build.build:Packaging stir-5.0.2-py39h578b638_3
compiling .pyc files...
number of files: 1047

/Users/runner/miniforge3/etc/profile.d/conda.sh: line 23:  4769 Segmentation fault: 11  ( "$CONDA_EXE" $_CE_M $_CE_CONDA "$@" )
/Users/runner/miniforge3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
```
I don't know if the seg-fault is related to the resource_tracker warning. Some issues that mention that: https://github.com/python/cpython/issues/89372, https://github.com/conda/conda/issues/9589

### Conda Info

```shell
The conda-forge pipelines use latest `Mambaforge-MacOSX-x86_64.sh`. I cannot do any of the following commands (I don't have a Mac).
```

**Comment by KrisThielemans** [comment]
I forgot to add that this occurred 3 times with Python 3.9 in the last 2 days, while it passed 9 times.

**Comment by wolfv** [comment]
this is most likely related to LIEF and lief 0.12.x releases that have not been super stable for us yet.

**Comment by jaimergp** [comment]
More updates about this issue in this thread @KrisThielemans
https://github.com/conda-forge/conda-forge.github.io/issues/1823

Not a `conda` issue per se, I'd say!

**Comment by KrisThielemans** [comment]
ok perfect. thanks all!
