### ISSUE TITLE
The official version of python 3.11 has been released. When will it be supported?

### ISSUE THREAD

**Issue by kingmo888** [conda/conda#12035]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

At least envs can support python 3.11,
It is better that anaconda or miniconda can release python version 3.11.
If only there was a timetable.

**Comment by johnnynunez** [comment]
any news?

**Comment by leoentersthevoid** [comment]
@johnnynunez, @kingmo888, there are some advancements, guess mostly experimental. you can install 3.11.0 on your machine by running:
```shell
conda create -n ENV python=3.11 -c conda-forge -y
```
no issues on my Ventura 13.1 so far.

**Comment by johnnynunez** [comment]
> @johnnynunez, @kingmo888, there are some advancements, guess mostly experimental. you can install 3.11.0 on your machine by running:
> 
> ```shell
> conda create -n ENV python=3.11 -c conda-forge -y
> ```
> 
> no issues on my Ventura 13.1 so far.

yess I knew it but Pytorch Vision needs python 3.11 in conda mainline

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues/new/choose). This is the issue tracker for the conda package manager software. Thank you for understanding!
