### ISSUE TITLE
conda update --all error

### ISSUE THREAD

**Issue by rbuckley-nv** [conda/conda#1205]
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\Scripts\conda-script.
py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\cli\install.py", line 355, in install
    return install(args, parser, command=command)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\cli\install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\resolve.py", line 540, in solve2
    version_constraints, evaluate_func=evaluate_func)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\logic.py", line 509, in bisect_constraints
    constraints = func(*rhs)
  File "C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\lib\site-packages\con
da\resolve.py", line 535, in version_constraints
    return set(generate_constraints(eq, m, [lo, hi], alg=alg))
MemoryError

C:>conda info
Current conda install:

```
         platform : win-32
    conda version : 3.10.0
```

  conda-build version : 1.3.1
       python version : 2.7.6.final.0
     requests version : 2.6.0
     root environment : C:\Users\rbuckley\AppData\Local\Continuum\Anaconda  (wri
table)
  default environment : C:\Users\rbuckley\AppData\Local\Continuum\Anaconda
     envs directories : C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\envs
        package cache : C:\Users\rbuckley\AppData\Local\Continuum\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
Can you paste the output of `conda list --export`.

**Comment by rbuckley-nv** [comment]
conda list --export
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-32
_license=1.1=py27_0
apptools=4.2.1=py27_0
argcomplete=0.8.1=py27_0
astropy=0.4.2=np19py27_0
atom=0.3.9=py27_0
beautiful-soup=4.3.2=py27_0
binstar=0.7.1=py27_0
biopython=1.63=np18py27_0
bitarray=0.8.1=py27_1
blaze=0.6.3=np19py27_0
blz=0.6.2=np19py27_0
bokeh=0.8.1=np19py27_0
boto=2.32.1=py27_0
casuarius=1.1=py27_0
cdecimal=2.3=py27_1
cffi=0.8.6=py27_0
chaco=4.4.1=np19py27_0
chardet=2.2.1=py27_0
colorama=0.3.3=py27_0
conda=3.10.0=py27_0
conda-build=1.3.1=py27_0
conda-env=2.1.3=py27_0
configobj=5.0.6=py27_0
cryptography=0.5.4=py27_0
cubes=0.10.2=py27_4
cython=0.21=py27_0
cytoolz=0.7.0=py27_0
datashape=0.3.0=np19py27_1
dateutil=2.4.1=py27_0
decorator=3.4.0=py27_0
docutils=0.12=py27_0
dynd-python=0.6.5=np19py27_0
enable=4.3.0=np19py27_2
enaml=0.9.8=py27_0
envisage=4.4.0=py27_1
flask=0.10.1=py27_1
future=0.13.1=py27_0
futures=2.1.6=py27_0
gevent=1.0.1=py27_0
gevent-websocket=0.9.3=py27_0
gevent_zeromq=0.2.5=py27_3
greenlet=0.4.5=py27_0
grin=1.2.1=py27_2
h5py=2.3.1=np19py27_0
ipython=3.0.0=py27_0
ipython-notebook=2.2.0=py27_0
ipython-qtconsole=2.2.0=py27_0
itsdangerous=0.24=py27_0
jdcal=1.0=py27_0
jinja2=2.7.3=py27_1
keyring=3.3=py27_0
kiwisolver=0.1.3=py27_0
launcher=1.0.0=1
libpython=1.0=py27_1
llvmpy=0.12.7=py27_0
lxml=3.4.0=py27_0
markupsafe=0.23=py27_0
matplotlib=1.4.0=np19py27_0
mayavi=4.3.1=np18py27_0
mdp=3.3=np18py27_0
menuinst=1.0.4=py27_0
mingw=4.7=1
mock=1.0.1=py27_0
multipledispatch=0.4.7=py27_0
netcdf4=1.0.8=np18py27_0
networkx=1.9.1=py27_0
nltk=3.0.0=np19py27_0
node-webkit=0.10.1=0
nose=1.3.4=py27_0
numba=0.14.0=np19py27_0
numexpr=2.3.1=np19py27_0
numpy=1.9.2=py27_0
openpyxl=1.8.5=py27_0
pandas=0.15.2=np19py27_0
patsy=0.3.0=np19py27_0
pep8=1.5.7=py27_0
pil=1.1.7=py27_0
pip=6.0.8=py27_0
ply=3.4=py27_0
psutil=1.2.1=py27_0
py=1.4.25=py27_0
pycosat=0.6.0=py27_1
pycparser=2.10=py27_0
pycrypto=2.6.1=py27_2
pyface=4.4.0=py27_0
pyflakes=0.8.1=py27_0
pygments=2.0.2=py27_0
pykit=0.2.0=np18py27_0
pyopenssl=0.14=py27_0
pyparsing=2.0.1=py27_0
pyqt=4.10.4=py27_0
pyreadline=2.0=py27_0
pysal=1.6.0=np18py27_1
pyside=1.2.1=py27_0
pytables=3.1.1=np19py27_1
pytest=2.6.3=py27_0
python=2.7.6=0
pytz=2014.9=py27_0
pywin32=219=py27_0
pyyaml=3.11=py27_0
pyzmq=14.5.0=py27_0
requests=2.6.0=py27_0
rope=0.9.4=py27_1
runipy=0.1.1=py27_0
scikit-image=0.10.1=np19py27_0
scikit-learn=0.15.2=np19py27_0
scipy=0.15.1=np19py27_0
setuptools=14.3=py27_0
six=1.9.0=py27_0
sockjs-tornado=1.0.1=py27_0
sphinx=1.2.3=py27_0
spyder=2.3.3=py27_0
spyder-app=2.3.1=py27_0
sqlalchemy=0.9.7=py27_0
ssl_match_hostname=3.4.0.2=py27_0
statsmodels=0.5.0=np19py27_2
sympy=0.7.5=py27_0
toolz=0.7.0=py27_0
tornado=4.1=py27_0
traits=4.4.0=py27_0
traitsui=4.4.0=py27_0
ujson=1.33=py27_0
unicodecsv=0.9.4=py27_0
vtk=5.10.1=py27_0
werkzeug=0.10.1=py27_0
wxpython=3.0=py27_0
xlrd=0.9.3=py27_0
xlsxwriter=0.5.7=py27_0
xlwings=0.2.2=py27_0
xlwt=0.7.5=py27_0

**Comment by asmeurer** [comment]
Can you also run 

```
conda config --set show_channel_urls yes
conda list
```

and show me the output. Some of your packages are coming from non-default channels.

**Comment by rbuckley-nv** [comment]
C:\Users\rbuckley>conda config --set show_channel_urls yes

C:\Users\rbuckley>conda list
# packages in environment at C:\Users\rbuckley\AppData\Local\Continuum\Anaconda:

#
_license                  1.1                      py27_0    <unknown>
apptools                  4.2.1                    py27_0    <unknown>
argcomplete               0.8.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/argcomplete-0.8.1-py27_0.tar.bz2
astropy                   0.4.2                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/astropy-0.4.2-np19py27_0.tar.bz2
atom                      0.3.9                    py27_0    http://repo.continuum.io/pkgs/free/win-32/atom-0.3.9-py27_0.tar.bz2
backports.ssl-match-hostname 3.4.0.2                   <pip>
beautiful-soup            4.3.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/beautiful-soup-4.3.2-py27_0.tar.bz2
beautifulsoup4            4.3.2                     <pip>
binstar                   0.7.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/binstar-0.7.1-py27_0.tar.bz2
biopython                 1.63                 np18py27_0    <unknown>
bitarray                  0.8.1                    py27_1    <unknown>
blaze                     0.6.3                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/blaze-0.6.3-np19py27_0.tar.bz2
blz                       0.6.2                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/blz-0.6.2-np19py27_0.tar.bz2
bokeh                     0.8.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/bokeh-0.8.1-np19py27_0.tar.bz2
boto                      2.32.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/boto-2.32.1-py27_0.tar.bz2
casuarius                 1.1                      py27_0    <unknown>
cdecimal                  2.3                      py27_1    <unknown>
cffi                      0.8.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cffi-0.8.6-py27_0.tar.bz2
chaco                     4.4.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/chaco-4.4.1-np19py27_0.tar.bz2
chardet                   2.2.1                    py27_0    primer
colorama                  0.3.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/colorama-0.3.3-py27_0.tar.bz2
conda                     3.10.0                   py27_0    http://repo.continuum.io/pkgs/free/win-32/conda-3.10.0-py27_0.tar.bz2
conda-build               1.3.1                    py27_0    <unknown>
conda-env                 2.1.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/conda-env-2.1.3-py27_0.tar.bz2
configobj                 5.0.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/configobj-5.0.6-py27_0.tar.bz2
cryptography              0.5.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cryptography-0.5.4-py27_0.tar.bz2
cubes                     0.10.2                   py27_4    <unknown>
cython                    0.21                     py27_0    http://repo.continuum.io/pkgs/free/win-32/cython-0.21-py27_0.tar.bz2
cytoolz                   0.7.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cytoolz-0.7.0-py27_0.tar.bz2
datashape                 0.3.0                np19py27_1    http://repo.continuum.io/pkgs/free/win-32/datashape-0.3.0-np19py27_1.tar.bz2
dateutil                  2.4.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/dateutil-2.4.1-py27_0.tar.bz2
decorator                 3.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/decorator-3.4.0-py27_0.tar.bz2
docutils                  0.12                     py27_0    http://repo.continuum.io/pkgs/free/win-32/docutils-0.12-py27_0.tar.bz2
dynd-python               0.6.5                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/dynd-python-0.6.5-np19py27_0.tar.bz2
enable                    4.3.0                np19py27_2    http://repo.continuum.io/pkgs/free/win-32/enable-4.3.0-np19py27_2.tar.bz2
enaml                     0.9.8                    py27_0    http://repo.continuum.io/pkgs/free/win-32/enaml-0.9.8-py27_0.tar.bz2
envisage                  4.4.0                    py27_1    <unknown>
flask                     0.10.1                   py27_1    <unknown>
future                    0.13.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/future-0.13.1-py27_0.tar.bz2
futures                   2.1.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/futures-2.1.6-py27_0.tar.bz2
gevent                    1.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/gevent-1.0.1-py27_0.tar.bz2
gevent-websocket          0.9.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/gevent-websocket-0.9.3-py27_0.tar.bz2
gevent-zeromq             0.2.2                     <pip>
gevent_zeromq             0.2.5                    py27_3    <unknown>
greenlet                  0.4.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/greenlet-0.4.5-py27_0.tar.bz2
grin                      1.2.1                    py27_2    <unknown>
h5py                      2.3.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/h5py-2.3.1-np19py27_0.tar.bz2
ipython                   3.0.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-3.0.0-py27_0.tar.bz2
ipython-notebook          2.2.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-notebook-2.2.0-py27_0.tar.bz2
ipython-qtconsole         2.2.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-qtconsole-2.2.0-py27_0.tar.bz2
itsdangerous              0.24                     py27_0    http://repo.continuum.io/pkgs/free/win-32/itsdangerous-0.24-py27_0.tar.bz2
jdcal                     1.0                      py27_0    http://repo.continuum.io/pkgs/free/win-32/jdcal-1.0-py27_0.tar.bz2
jinja2                    2.7.3                    py27_1    http://repo.continuum.io/pkgs/free/win-32/jinja2-2.7.3-py27_1.tar.bz2
keyring                   3.3                      py27_0    <unknown>
kiwisolver                0.1.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/kiwisolver-0.1.3-py27_0.tar.bz2
launcher                  1.0.0                         1    http://repo.continuum.io/pkgs/free/win-32/launcher-1.0.0-1.tar.bz2
libpython                 1.0                      py27_1    <unknown>
llvmpy                    0.12.7                   py27_0    http://repo.continuum.io/pkgs/free/win-32/llvmpy-0.12.7-py27_0.tar.bz2
lxml                      3.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/lxml-3.4.0-py27_0.tar.bz2
markupsafe                0.23                     py27_0    http://repo.continuum.io/pkgs/free/win-32/markupsafe-0.23-py27_0.tar.bz2
matplotlib                1.4.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/matplotlib-1.4.0-np19py27_0.tar.bz2
mayavi                    4.3.1                np18py27_0    <unknown>
mdp                       3.3                  np18py27_0    <unknown>
menuinst                  1.0.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/menuinst-1.0.4-py27_0.tar.bz2
mingw                     4.7                           1    <unknown>
mock                      1.0.1                    py27_0    <unknown>
multipledispatch          0.4.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/multipledispatch-0.4.7-py27_0.tar.bz2
netcdf4                   1.0.8                np18py27_0    <unknown>
networkx                  1.9.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/networkx-1.9.1-py27_0.tar.bz2
nltk                      3.0.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/nltk-3.0.0-np19py27_0.tar.bz2
node-webkit               0.10.1                        0    http://repo.continuum.io/pkgs/free/win-32/node-webkit-0.10.1-0.tar.bz2
nose                      1.3.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/nose-1.3.4-py27_0.tar.bz2
numba                     0.14.0               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/numba-0.14.0-np19py27_0.tar.bz2
numexpr                   2.3.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/numexpr-2.3.1-np19py27_0.tar.bz2
numpy                     1.9.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/numpy-1.9.2-py27_0.tar.bz2
openpyxl                  1.8.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/openpyxl-1.8.5-py27_0.tar.bz2
pandas                    0.15.2               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/pandas-0.15.2-np19py27_0.tar.bz2
patsy                     0.3.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/patsy-0.3.0-np19py27_0.tar.bz2
pep8                      1.5.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pep8-1.5.7-py27_0.tar.bz2
pil                       1.1.7                    py27_0    <unknown>
pip                       6.0.8                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pip-6.0.8-py27_0.tar.bz2
ply                       3.4                      py27_0    <unknown>
psutil                    1.2.1                    py27_0    <unknown>
py                        1.4.25                   py27_0    http://repo.continuum.io/pkgs/free/win-32/py-1.4.25-py27_0.tar.bz2
pycosat                   0.6.0                    py27_1    <unknown>
pycparser                 2.10                     py27_0    <unknown>
pycrypto                  2.6.1                    py27_2    http://repo.continuum.io/pkgs/free/win-32/pycrypto-2.6.1-py27_2.tar.bz2
pyface                    4.4.0                    py27_0    <unknown>
pyflakes                  0.8.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pyflakes-0.8.1-py27_0.tar.bz2
pygments                  2.0.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pygments-2.0.2-py27_0.tar.bz2
pykit                     0.2.0                np18py27_0    <unknown>
pyopenssl                 0.14                     py27_0    http://repo.continuum.io/pkgs/free/win-32/pyopenssl-0.14-py27_0.tar.bz2
pyparsing                 2.0.1                    py27_0    <unknown>
pyqt                      4.10.4                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pyqt-4.10.4-py27_0.tar.bz2
pyreadline                2.0                      py27_0    <unknown>
pysal                     1.6.0                np18py27_1    <unknown>
pyserial                  2.7                       <pip>
pyside                    1.2.1                    py27_0    <unknown>
pytables                  3.1.1                np19py27_1    http://repo.continuum.io/pkgs/free/win-32/pytables-3.1.1-np19py27_1.tar.bz2
pytest                    2.6.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pytest-2.6.3-py27_0.tar.bz2
python                    2.7.6                         0    <unknown>
python-dateutil           2.4.1                     <pip>
pytz                      2014.9                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pytz-2014.9-py27_0.tar.bz2
pywin32                   219                      py27_0    http://repo.continuum.io/pkgs/free/win-32/pywin32-219-py27_0.tar.bz2
pyyaml                    3.11                     py27_0    http://repo.continuum.io/pkgs/free/win-32/pyyaml-3.11-py27_0.tar.bz2
pyzmq                     14.5.0                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pyzmq-14.5.0-py27_0.tar.bz2
requests                  2.6.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/requests-2.6.0-py27_0.tar.bz2
rope                      0.9.4                    py27_1    http://repo.continuum.io/pkgs/free/win-32/rope-0.9.4-py27_1.tar.bz2
runipy                    0.1.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/runipy-0.1.1-py27_0.tar.bz2
scikit-image              0.10.1               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scikit-image-0.10.1-np19py27_0.tar.bz2
scikit-learn              0.15.2               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scikit-learn-0.15.2-np19py27_0.tar.bz2
scipy                     0.15.1               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scipy-0.15.1-np19py27_0.tar.bz2
setuptools                14.3                     py27_0    http://repo.continuum.io/pkgs/free/win-32/setuptools-14.3-py27_0.tar.bz2
six                       1.9.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/six-1.9.0-py27_0.tar.bz2
sockjs-tornado            1.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sockjs-tornado-1.0.1-py27_0.tar.bz2
sphinx                    1.2.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sphinx-1.2.3-py27_0.tar.bz2
spyder                    2.3.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/spyder-2.3.3-py27_0.tar.bz2
spyder-app                2.3.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/spyder-app-2.3.1-py27_0.tar.bz2
sqlalchemy                0.9.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sqlalchemy-0.9.7-py27_0.tar.bz2
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.5.0                np19py27_2    http://repo.continuum.io/pkgs/free/win-32/statsmodels-0.5.0-np19py27_2.tar.bz2
sympy                     0.7.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sympy-0.7.5-py27_0.tar.bz2
tables                    3.1.1                     <pip>
toolz                     0.7.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/toolz-0.7.0-py27_0.tar.bz2
tornado                   4.1                      py27_0    http://repo.continuum.io/pkgs/free/win-32/tornado-4.1-py27_0.tar.bz2
traits                    4.4.0                    py27_0    <unknown>
traitsui                  4.4.0                    py27_0    <unknown>
ujson                     1.33                     py27_0    <unknown>
unicodecsv                0.9.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/unicodecsv-0.9.4-py27_0.tar.bz2
vtk                       5.10.1                   py27_0    <unknown>
werkzeug                  0.10.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/werkzeug-0.10.1-py27_0.tar.bz2
wxpython                  3.0                      py27_0    http://repo.continuum.io/pkgs/free/win-32/wxpython-3.0-py27_0.tar.bz2
xlrd                      0.9.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlrd-0.9.3-py27_0.tar.bz2
xlsxwriter                0.5.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlsxwriter-0.5.7-py27_0.tar.bz2
xlwings                   0.2.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlwings-0.2.2-py27_0.tar.bz2
xlwt                      0.7.5                    py27_0    <unknown>

**Comment by soapy1** [comment]
@rbuckley-nv is this still an issue for you?
