### ISSUE TITLE
Errors in package spec documentation

### ISSUE THREAD

**Issue by jonashaag** [conda/conda#12055]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Example 1: Meaning of whitespace

In the [package spec documentation](https://conda.io/projects/conda-build/en/latest/resources/package-spec.html) it says

> `python >= 2.7` is an invalid match specification. Furthermore, `python>=2.7` is matched as any version of a package named `python>=2.7`.

This isn't actually the case in practice and also contradicts other examples:

> `conda install "numpy>=1.8,<2"`

### Example 2: Meaning of `pkg=ver`

> EXAMPLE: python=3.4 is translated to python 3.4*.

Should this be `3.4.*`? `conda search 'python=3.1'` does NOT bring up Python 3.10, only Python 3.1.*.

### Example 3: Meaning of `pkg =ver =build`

I wonder if this a bug in the documentation or the code. `conda search micromamba =0.25 =0` brings up a single entry while `conda search micromamba =0.25` brings up two entries that each have build number 0.

**Comment by travishathaway** [comment]
Hi @jonashaag,

Thanks for submitting this issue. I have added the correct labels to it and also added the https://github.com/conda/conda/labels/good-first-issue label, so it hopefully gets more attention from would-be contributors.

As always, we welcome any pull request you may have to resolve this particular issue.

**Comment by rishabh11336** [comment]
I have made pull request for this issue
https://github.com/conda/conda-build/pull/4782
Kindly review it
