### ISSUE TITLE
`conda install /path/to/some_pkg-1.0.0-0.tar.bz` doesn't upgrade package

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1207]
If a package is installed and you re-install again with a tarball a new `conda-meta/` file is created which makes your `conda list` look odd: the same package will be installed N times.

This would be particularly harmful for changes where a file was removed.

**Comment by asmeurer** [comment]
There's a situation at https://github.com/conda/conda/issues/1203 where someone has many duplicate packages installed, although I don't know if this is the same source of that problem, since that guy has a lot of them.

**Comment by tswicegood** [comment]
Not sure if they got them the same way or not, but I managed to install a half dozen versions of the launcher before I realized what was up.

I'm still unclear why the installer treats a tarball as different.  I would have thought it simply treated it like repodata with one package in it, then goes through the rest of the installation process.  I vaguely recall @ilanschnell talking about doing something like this.

**Comment by asmeurer** [comment]
I thought it was implemented (c.f. https://github.com/conda/conda/issues/1075). Clearly whatever it is doing is wrong, though.

**Comment by ilanschnell** [comment]
I haven't gotten around to implement my suggestion mentioned in issue #1075, yet.  Installing conda tarballs directly was initially only done for debugging and testing.

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/6147

**Comment by kalefranz** [comment]
fixed in https://github.com/conda/conda/commit/973d6bf4b8dd1bf995af663f334b9fca618a8150
