### ISSUE TITLE
Test with basetmp on same filesystem as TMP

### ISSUE THREAD

**Issue by dholth** [conda/conda#12073]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

conda's test suite complains verbosely about copying files instead of hardlinking. This is the recipe for using a different temporary directory. One environment variable for Python's tempfile module, and an argument for pytest's tempdir.

```
export TMP=$HOME/pytesttmp/
pytest --basetemp=$HOME/pytesttmp ...
```

We might want to use github actions' tempdir instead, or whatever is available in a docker run.

On my machine setting the temporary directories up this way is a little bit faster but more importantly we avoid seeing all these OSError's, and hopefully test in a way that is more faithful to a typical setup.

```
DEBUG conda.gateways.disk.create:create_link(361): OSError(18, 'Invalid cross-device link')
DEBUG conda.gateways.disk.create:create_link(362): hard-link failed. falling back to copy
  error: OSError(18, 'Invalid cross-device link')
  src: /home/dholth/conda/devenv/Linux/x86_64/envs/devenv-3.10-c/pkgs/pip-22.2.2-py39h06a4308_0/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_securetransport/bindings.py
  dst: /tmp/15db fdbaec/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_securetransport/bindings.py
  ```

**Comment by jezdez** [comment]
Fixed in #12077.
