### ISSUE TITLE
Finalize/Add More Plugins-Related Documentation

### ISSUE THREAD

**Issue by beeankha** [conda/conda#12072]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

As the conda plugins effort is currently underway, we need to add more details to the conda documentation in order to provide more information about this new feature to users and as well as potential contributors.

### What should happen?

- [x] Add a new "Conda plugins" concept in the [User Guide](https://docs.conda.io/projects/conda/en/stable/user-guide/concepts/index.html) (much of this information can be taken from the [CEP for plugins implementation](https://github.com/conda-incubator/ceps/blob/main/cep-4.md))
- [x] Add a definition for plugins in the [Glossary](https://docs.conda.io/projects/conda/en/stable/glossary.html) section
- [x] Add info about how virtual packages are implemented via plugin hooks now in the [Managing Virtual Packages section](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-virtual.html) (maybe link to the [related section of the developer guide](https://docs.conda.io/projects/conda/en/latest/dev-guide/plugins/virtual_packages.html))

**Comment by jezdez** [comment]
Closing since #12088 has been merged.
