### ISSUE TITLE
Conda Initialize PowerShell 7

### ISSUE THREAD

**Issue by langshangyuan** [conda/conda#12080]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

## Currently

Now conda only support the init to the Windows Powershell (a.k.a PowerShell 1.0), which is a bit out of date.

## Hope

I'm using pwsh (PowerShell 7.2.7), I wish conda could support `conda init pwsh` to inititlize the modern cross-platform shell (Powershell).

**Comment by travishathaway** [comment]
Hi @langshangyuan 

Thanks for filing this feature request. Having better support for power shell is definitely something that people want (e.g. #12094). I cannot promise when we will get to this, but we will keep updated via this issue if and when we do.

In the meantime, contributions are always welcome. We would be happy to review a pull request which adds better support for power shell.
