### ISSUE TITLE
Conda blocks powershell startup when in a screen session

### ISSUE THREAD

**Issue by CCRcmcpe** [conda/conda#12094]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I upgraded to powershell 7.3.0, then opening pwsh in a screen session will stuck indefinitely.

I assume the problem source is conda, then:

Tried running `conda "shell.powershell" "hook"` outside a screen session is normal.
Tried running `screen -S test pwsh -nop` then run  `conda "shell.powershell" "hook"`. Stuck indefinitely.

So that's a problem of the conda hook.

As a tempoary resolution, downgrading to powershell 7.2.7 can solve the issue. (`sudo apt install powershell=7.2.7-1.deb`)

### Conda Info

```shell
active environment : base
    active env location : /home/ubuntu/mambaforge
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/mambaforge/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ubuntu/mambaforge  (writable)
      conda av data dir : /home/ubuntu/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/ubuntu/mambaforge/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/mambaforge/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.25.1 CPython/3.10.6 Linux/5.4.0-131-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/ubuntu/.netrc
           offline mode : False
```

### Conda Config

```shell
==> /home/ubuntu/mambaforge/.condarc <==
channels:
  - conda-forge
```

**Comment by travishathaway** [comment]
Hi @CCRcmcpe,

Thank you for filing this bug report. I can confirm that I was able to reproduce it. Here were the steps I took on my OSX computer:

```
brew install powershell screen
screen
# ... launches screen session
pwsh
conda --help 
# at this point everything freezes
```

I can't promise for sure when we will get to this issue, but if you are able to make a fix for it, I encourage you to submit a pull request. We will be more than happy to review it for you.
