### ISSUE TITLE
conda install should not update other dependencies

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda#1210]
from http://continuum.io/blog/advanced-conda-part-1

"conda by default will update all dependencies of any package you install"  Why does this happen?  Is there a way to turn this off?  --no-deps seems nice, but that's not what you want - you want to install any necessary deps, and leave everything else alone

**Comment by asmeurer** [comment]
Dupe: https://github.com/conda/conda/issues/337

**Comment by hhuuggoo** [comment]
sorry - had forgotten about that one
