### ISSUE TITLE
Quick way to generate explicit env YML file

### ISSUE THREAD

**Issue by mohitmv** [conda/conda#12106]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Support a way to generate `env_explicit.yml` file from a given `env.yml` file.

The content of `env.yml` file could be of kind:

```
dependencies:
  - python=3.7.6
  - pandas=0.25.3
  - numpy
  - conda
  - pyyaml
  - ...
```

The generated `env_explicit.yml` should look like:

```
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - beautifulsoup4=4.11.1=pyha770c72_0
  - boto3=1.26.1=pyhd8ed1ab_0
  - botocore=1.29.1=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h540881e_1004
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.14.4=py37h11fe52a_0
  - .......
```

The generated env_explicit.yml should list all the dependency cover as well as a fixed version. Basically it should be what we get from `conda env export`... but without having to first create conda env from `env.yml` file.... A direct command to generate it would be very very helpful for us, because we want to checkin env_explicit.yml in git repo and conda env would be created in our build pipelines using env_explicit.yml .

### Why is this needed?

Explained above.

### What should happen?

Support a new conda command.

### Additional Context

Explained above.

**Comment by marcelm** [comment]
You may want to try [conda-lock](https://github.com/conda-incubator/conda-lock).

**Comment by travishathaway** [comment]
Hi @mohitmv,

I believe this use case is covered well by conda-lock as @marcelm mentioned. Therefore, I think it's best to close this feature request.

Please re-open if you would like to continue this discussion.
