### ISSUE TITLE
`root_prefix` property in `conda info --json` contains incorrect path if conda is installed inside the environment 

### ISSUE THREAD

**Issue by karrtikr** [conda/conda#12113]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi VSCode dev here 👋
- Run the following commands to install conda in the env:
```
conda create -n conda-rube-goldberg --yes "python" "conda-libmamba-solver" "flake8"
conda activate conda-rube-goldberg
conda info --json
```
- Check the output of `conda info --json`:
![image](https://user-images.githubusercontent.com/13199757/202665878-252d3c5f-e186-4b0e-b053-59a0cb4d4b10.png)

We expected the value to be `"C:\\Users\\karraj\\Miniconda3"` instead. We use the `root_prefix` to figure out which environment is the base, so this leads us in thinking `conda-rube-goldberg` is the base env.

### Additional Context

I don't think the information asked above matters, let me know if you need it though. Originally reported by @bitplane.

**Comment by karrtikr** [comment]
Related https://github.com/conda/conda/issues/12082 likely caused due to the same bug.

**Comment by kenodegard** [comment]
This is a Windows-specific issue.

Since conda is exposed as a batch script on the PATH, the activated environment's conda obfuscates the base environment's conda.

**Comment by lgonzalezsa** [comment]
Linux user here and facing same issue with vscode not listing the correct conda environment.

**Comment by karrtikr** [comment]
@kenodegard FYI we're also seeing this on linux.
