### ISSUE TITLE
Atlas should depend on system

### ISSUE THREAD

**Issue by dmitry-kabanov** [conda/conda#1212]
I've installed `atlas` package into the `_build` environment as a dependency for a library that I try to build with `conda`.

Now I have the following issue: library `<conda-build-env>/lib/liblapack.a` says that it has undefined symbol `_gfortran_copy_string`. If I install `system` package, then I have `libgfortran.so.1.0.0` that contains the above symbol.

However, `atlas` package doesn't have `system` package as a dependency.

It seems to me that `atlas` must have `system` package as a dependency.

UPDATE: actually, the problem is even deeper. `Atlas` installs only static libraries (*.a). Therefore, it doesn't have any references to libgfortran.so.1.0.0, although it definitely depends on it.

**Comment by asmeurer** [comment]
@ilanschnell
