### ISSUE TITLE
Make conda pip installable via pypi

### ISSUE THREAD

**Issue by costrouc** [conda/conda#12126]
### What is the idea?

Users should be able to `pip install conda` . Looks like[ in the past](https://pypi.org/project/conda/) this worked and was abandoned around `4.3.16 `

### Why is this needed?

First I wanted to outline some of the reasons that conda should be pypi instalable:
 - other package managers e.g. npm are pip installable
 - conda already supports installing conda within it wouldn't be much different than pip installing conda into an environment
 - conda is also a library and often times I need access to conda.core.*
 - it feels wrong in my setup.py etc. to list all dependencies except conda
 - installation instructions for conda vary by OS/distribution. Why not just use `python -m ensure-pip; pip install conda` this certainly isn't saying that the other install instructions aren't important. setup.py can do anything it likes so we could

Some use cases:
  - using conda as a library (not as a command for interacting with conda internals e.g. package cache) without requiring installing conda via miniconda etc. I've often seen myself needing access to `conda.core.*`
 
My personal primary motivation is the new build system for python https://hatch.pypa.io/latest/. It has great support for plugins into the build, run, environments, publish. All of this is controlled via the `pyproject.toml`. This is an opportunity for conda to share a common file `pyproject.toml`  without conda having to make any changes. 

There is already a plugin https://pypi.org/project/hatch-conda/ which allows using conda environments within the pyproject.toml. But there is one major drawback to this package... it assumes that conda is already installed. It would be nice if conda could be boostrapped via pip so that conda can be effortlessly used in pyproject.toml files.

### What should happen?

The user should be able to 
```
pip install conda
```

**Comment by jezdez** [comment]
Thank you for the issue, repeating what we shortly discussed on the conda Slack:

> I don’t have the full history of why it’s like that, but it’s come up a few time since I’ve worked on conda. I think it’s fundamentally a question of how bootstrapping works. `ensurepip` and `ensureconda` imply that there is already a trustworthy Python installation available on the system to run them. I think there was a design decision in the past that this would not suffice to create a "viable" environment for conda to run in.
>
> In other words, the question isn’t particularly about whether conda can be installed with pip, but whether there is the ability and interest in maintaining conda when it runs in environments that haven’t been bootstrapped with conda itself (think package verification, ABI compatibility etc)

That said, I'm interested in exploring this as an alternative way to integrate the conda stack with the PyPA stack, as I totally hear you on the reasons why this would be useful.

As a next step, we should probably do some more research on why the conda package on PyPI was abandoned and how (if at all) we can retrofit the package. Besides `ensureconda`, there is of course also the conda-standalone project, which some might be interested in seeing as the artifact of installing conda from PyPI.
