### ISSUE TITLE
QUESTION: Does building pure python modules w/ conda require setuptools?

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1213]
This weekend I've been reading up on [conda](http://conda.pydata.org/docs/) and the [python packaging user guide](https://python-packaging-user-guide.readthedocs.org/en/latest/) because I have a [simple pure python project](https://github.com/jrsmith3/physicalproperty) that depends on `numpy`. It seemed to me that distributing/installing this project via `conda` was better than `pip` due to this dependency. 

One thing on which I'm still not clear: `conda` will install a python package from a recipe in `build.sh`, but it seems like `build.sh` just ends up calling `python setup.py install` for most python packages.

So even if I want to distribute/install my python package with `conda`, I still end up depending on `setuptools` (or `distutils`) for the actual installation, correct? I was unable to find a `conda` utility analogous to `setuptools`; am I missing something?

**Comment by asmeurer** [comment]
Typically you will still be using distutils (or setuptools if the library requires it) to install things, yes. It is not technically required. The build.sh can be anything. If you wanted to, you could just copy the code into site-packages. Using setup.py install is recommended, though, as libraries will already have setup.py working, it will install metadata that can be read by pip, and it will compile any extension modules and install any data files.

**Comment by jrsmith3** [comment]
Thanks for the clear answer!
