### ISSUE TITLE
Permission denied when conda install mingw on windows

### ISSUE THREAD

**Issue by klmh001** [conda/conda#1214]
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 140, in execute_instructions

    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 55, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 448, in extract
    t.extractall(path=path)
  File "C:\Anaconda\lib\tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "C:\Anaconda\lib\tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Anaconda\lib\tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Anaconda\lib\tarfile.py", line 2204, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Anaconda\\pkgs\\mingw-4.7-1\\MinGW\\x86_64-w64-min
gw32\\lib\\libkbdsg.a'

BTW, I run conda from admin cmd.

Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by klmh001** [comment]
C:\windows\system32>conda list
# packages in environment at C:\Anaconda:
#
_license                  1.1                      py27_0
anaconda                  2.1.0                np19py27_0
argcomplete               0.8.1                    py27_0
astropy                   0.4.2                np19py27_0
atom                      0.3.9                    py27_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
beautiful-soup            4.3.2                    py27_0
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py27_3
bitarray                  0.8.1                    py27_1
blaze                     0.6.3                np19py27_0
blz                       0.6.2                np19py27_0
bokeh                     0.6.1                np19py27_0
boto                      2.32.1                   py27_0
casuarius                 1.1                      py27_0
cdecimal                  2.3                      py27_1
cffi                      0.9.2                    py27_0
chaco                     4.4.1                np19py27_0
clyent                    0.3.4                    py27_0
colorama                  0.3.1                    py27_0
conda                     3.10.0                   py27_0
conda-build               1.8.2                    py27_0
conda-env                 2.1.3                    py27_0
configobj                 5.0.6                    py27_0
cryptography              0.8                      py27_0
cython                    0.21                     py27_0
cytoolz                   0.7.0                    py27_0
datashape                 0.3.0                np19py27_1
dateutil                  2.1                      py27_2
decorator                 3.4.0                    py27_0
docutils                  0.12                     py27_0
dynd-python               0.6.5                np19py27_0
enable                    4.3.0                np19py27_2
enaml                     0.9.8                    py27_0
enum34                    1.0.4                    py27_0
flask                     0.10.1                   py27_1
future                    0.13.1                   py27_0
futures                   2.1.6                    py27_0
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
greenlet                  0.4.4                    py27_0
grin                      1.2.1                    py27_2
h5py                      2.3.1                np19py27_0
ipython                   3.0.0                    py27_0
ipython-notebook          2.2.0                    py27_0
ipython-qtconsole         2.2.0                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jinja2                    2.7.3                    py27_1
kiwisolver                0.1.3                    py27_0
launcher                  1.0.0                         1
libpython                 1.0                      py27_1
llvmpy                    0.12.7                   py27_0
lxml                      3.4.0                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.0                np19py27_0
menuinst                  1.0.4                    py27_0
mock                      1.0.1                    py27_0
multipledispatch          0.4.7                    py27_0
networkx                  1.9.1                    py27_0
nltk                      3.0.0                np19py27_0
node-webkit               0.10.1                        0
nose                      1.3.4                    py27_0
numba                     0.14.0               np19py27_0
numexpr                   2.3.1                np19py27_0
numpy                     1.9.2                    py27_0
openpyxl                  1.8.5                    py27_0
pandas                    0.14.1               np19py27_0
patsy                     0.3.0                np19py27_0
pep8                      1.5.7                    py27_0
pil                       1.1.7                    py27_0
pip                       6.0.8                    py27_0
ply                       3.4                      py27_0
psutil                    2.1.1                    py27_0
py                        1.4.25                   py27_0
pyasn1                    0.1.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.10                     py27_0
pycrypto                  2.6.1                    py27_2
pyface                    4.4.0                    py27_0
pyflakes                  0.8.1                    py27_0
pygments                  1.6                      py27_0
pyopenssl                 0.14                     py27_0
pyparsing                 2.0.1                    py27_0
pyqt                      4.10.4                   py27_0
pyreadline                2.0                      py27_0
pytables                  3.1.1                np19py27_1
pytest                    2.6.3                    py27_0
python                    2.7.8                         0
python-dateutil           2.4.1                    py27_0
pytz                      2014.9                   py27_0
pywin32                   219                      py27_0
pyyaml                    3.11                     py27_0
pyzmq                     14.3.1                   py27_0
requests                  2.6.0                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.1                    py27_0
scikit-image              0.10.1               np19py27_0
scikit-learn              0.15.2               np19py27_0
scipy                     0.15.1               np19py27_0
setuptools                14.3                     py27_0
six                       1.9.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.2.3                    py27_0
spyder                    2.3.1                    py27_0
spyder-app                2.3.1                    py27_0
sqlalchemy                0.9.7                    py27_0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.5.0                np19py27_2
sympy                     0.7.5                    py27_0
tables                    3.1.1                     <pip>
toolz                     0.7.0                    py27_0
tornado                   4.0.2                    py27_0
traits                    4.4.0                    py27_0
traitsui                  4.4.0                    py27_0
ujson                     1.33                     py27_0
unicodecsv                0.9.4                    py27_0
werkzeug                  0.9.6                    py27_1
xlrd                      0.9.3                    py27_0
xlsxwriter                0.5.7                    py27_0
xlwings                   0.2.2                    py27_0
xlwt                      0.7.5                    py27_0

**Comment by soapy1** [comment]
@klmh001 is this still an issue for you?

**Comment by klmh001** [comment]
@soapy1 no, thanks.

**Comment by AllenChen0958** [comment]
@klmh001 How did you solve it?

**Comment by klmh001** [comment]
I didn't actually "solve" it. I switched to a new PC with a new OS and
installed new conda, and there was no such problem.
