### ISSUE TITLE
An unexpected error has occurred, please consider sending... updating ipython.

### ISSUE THREAD

**Issue by mlisanke** [conda/conda#1216]
```
C:\Users\Mike\Anaconda3>Scripts\conda.exe update ipython
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Users\Mike\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.6.0             |           py34_0         621 KB
    setuptools-14.3            |           py34_0         747 KB
    ipython-3.0.0              |           py34_0         3.5 MB
    pip-6.0.8                  |           py34_0         1.6 MB
    ------------------------------------------------------------
                                           Total:         6.5 MB

The following packages will be UPDATED:

    ipython:    2.2.0-py34_0 --> 3.0.0-py34_0
    pip:        1.5.6-py34_0 --> 6.0.8-py34_0
    requests:   2.4.1-py34_0 --> 2.6.0-py34_0
    setuptools: 5.8-py34_0   --> 14.3-py34_0

Proceed ([y]/n)? y

Fetching packages ...
requests-2.6.0 100% |###############################| Time: 0:00:00   1.30 MB/s
setuptools-14. 100% |###############################| Time: 0:00:00 924.13 kB/s
ipython-3.0.0- 100% |###############################| Time: 0:00:01   2.04 MB/s
pip-6.0.8-py34 100% |###############################| Time: 0:00:00   1.80 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  75%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Mike\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Users\Mike\Anaconda3\lib\site-packages\conda\install.py", line 523, in link
    os.makedirs(dst_dir)
  File "C:\Users\Mike\Anaconda3\lib\os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Mike\\Anaconda3\\Lib/site-packages/IPython/__pycache__'

C:\Users\Mike\Anaconda3>
```

**Comment by mlisanke** [comment]
hmm, I'm not as certain as you that #1217 is related to the failure to update ipython in #1216. And, I believe #1217 to be a more significant problem. After reporting the problem, I attempted to update ipython from conda update, and while none of these attempts failed as in this problem (requesting a report to you), they All failed to run ipython notebook script... after running from the anaconda path with a static window prompt, it was clear that ipython module could not be found... indicating a path setting problem.

**Comment by asmeurer** [comment]
My theory of what happened is that conda failed to completely install ipython due to permissions issues (this issue), thereby breaking the ipython install (the other issue). Are you able to `conda install -f ipython`?

**Comment by mlisanke** [comment]
After the initial failure to work with ipython after update failed... I
tried uninstall + install combination, and that still fails... I then
removed + reinstallled Anaconda collectively, restored ipython function
completely, then performed conda update ipython, and broke ipython (fails
to run) again... that was originally done with Anaconda with python 3.4;
then, I moved to testing Anaconda with python 2.7, where updating ipython
with conda update ipython Also causes ipython notebook script to fail to
load. I repeated restoring by reinstalling Anaconda ipython function and
then breaking it again via conda update ipython. In my experience, on my
system, conda update ipython always causes failure of ipython notebook to
run.

On Wed, Mar 25, 2015 at 1:01 PM, Aaron Meurer <notifications@github.com>
wrote:

> My theory of what happened is that conda failed to completely install
> ipython due to permissions issues (this issue), thereby breaking the
> ipython install (the other issue). Are you able to conda install -f
> ipython?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1216#issuecomment-86122097>.
>



-- 
Best regards,  Mike

**Comment by asmeurer** [comment]
Are you performing any of these steps as administrator?

**Comment by mlisanke** [comment]
No, I executed the Anaconda command prompt shortcut and executed the
commands. No prompt to escalate privilege was requested.

On Thu, Mar 26, 2015 at 11:42 AM, Aaron Meurer <notifications@github.com>
wrote:

> Are you performing any of these steps as administrator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1216#issuecomment-86579933>.
>



-- 
Best regards,  Mike

**Comment by soapy1** [comment]
@mlisanke is this still an issue for you?
