### ISSUE TITLE
Can't install mamba " metadata-repodata-json-killed"

### ISSUE THREAD

**Issue by kuturabailey** [conda/conda#12168]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

I am trying to install mamba through conda on my linux terminal on my chormebook. Please help. I need to install this for a final exam. My professor just tells me look online. I am not a programmer and I am new to bioinformatics so please provide explanations with suggestions.

I keep getting an error message. I have tried reassigning space according to another thread and it did not work: https://stackoverflow.com/questions/64821441/collecting-package-metadata-repodata-json-killed

The output after ```sudo swapon /swapfile```

Was
 ```swapon: /swapfile: swapon failed: Function not implemented```

I also tried curl -H 'Cache-Control: no-cache' https://repo.anaconda.com/pkgs/r/noarch/repodata.json

I got a bunch of script then tried ```conda create -n py34d20 python=3.4 pip=9 django -c conda-forge``` per this thread: https://github.com/conda/conda/issues/9728

I get the same results which are:

Collecting package metadata (current_repodata.json): done Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. Collecting package metadata (repodata.json): - Killed

I've also tried an older version of conda ```wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh```

I still get the same message. 

I've even tried ```conda activate mamba``` and it did not work either. Please help!!!

### Linked Issues & PRs

- [ ] #

**Comment by travishathaway** [comment]
Hi @kuturabailey,

I am really sorry to hear about your troubles. I would recommend going either to your professor or classmates to get help on this issue. This is not the appropriate place to file these types of help requests.

I hope you are able to resolve your troubles soon.

Regards,
