### ISSUE TITLE
Latest version of Black breaks Darker in pre-commit

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12171]
### What happened?

Our pre-commits started breaking because of this issue with the latest release of Black and its effect on Darker:

https://github.com/akaihola/darker/issues/412

### Tasks

- [x] Pin version: https://github.com/conda/conda/pull/12170
- [ ] Revert pin once darker is updated

**Comment by dholth** [comment]
🙀

**Comment by kenodegard** [comment]
Superseded by https://github.com/conda/conda/issues/12522
