### ISSUE TITLE
`conda install streamlit` installs older version or fails

### ISSUE THREAD

**Issue by alex180500** [conda/conda#12177]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm getting troubles installing Streamlit on multiple python versions using `conda install streamlit -c conda-forge` on the **conda-forge channel**.
Trying to install on fresh conda environments with python 3.10 or 3.9 takes a very long time and at the end **installs streamlit version 1.8.0 or 1.9.0** (kind of randomly).
For environments with other packages (like jupyter notebook), it fails completely. This started happening after the latest **22.11** update.
Just for testing, with the same setups `pip install` worked flawlessly, also this bug happens to me on multiple pc.

### Conda Info

```shell
active environment : physics_3.11
    active env location : C:\Users\aless\miniconda3\envs\physics_3.11
            shell level : 2
       user config file : C:\Users\aless\.condarc
 populated config files : C:\Users\aless\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\aless\miniconda3  (writable)
      conda av data dir : C:\Users\aless\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aless\miniconda3\pkgs
                          C:\Users\aless\.conda\pkgs
                          C:\Users\aless\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aless\miniconda3\envs
                          C:\Users\aless\.conda\envs
                          C:\Users\aless\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.15 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\aless\.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

### Additional Context

- **Python:** 3.9 and 3.10
- **Conda:** 22.11.1
- **OS:** Win 11 22h2

**Comment by travishathaway** [comment]
Hi @alex180500,

Thanks for submitting this bug report. I tried recreating this issue with the latest conda `22.11.1`, but I was not able to do so. I  also did this across several operating systems (Windows, OSX and Linux).

Regardless of whether or not this can be reproduced, this issue tracker is not the best place for this bug.  would invite you to following the issue you have created over at the feedstock for this package instead:

- https://github.com/conda-forge/streamlit-feedstock/issues/68

In the meantime, I will be closing this issue. If you feel that this is incorrect, I invite you to reopen it so we can continue this discussion.
