### ISSUE TITLE
After successful conda update ipython... ipython script no longer runs. 

### ISSUE THREAD

**Issue by mlisanke** [conda/conda#1217]
The script reports that ipython module does not exist even though it's present in Lib/

**Comment by asmeurer** [comment]
Assumedly this is related to https://github.com/conda/conda/issues/1216.

**Comment by mlisanke** [comment]
See comment in #1216 (still open). IMHO, this is the more serious problem. Also, the reason for my testing ipython update is rooted in yet another problem running cython from anaconda ipython notebook cell... which fails. This is the link, but; not certain it's a conda problem...  http://stackoverflow.com/questions/29204148/anaconda-ipython-notebook-cell-using-cython-magic-fails-at-imp-load-dynamic
