### ISSUE TITLE
source conda.sh fails on windows bash with conda 22.11.X

### ISSUE THREAD

**Issue by dbast** [conda/conda#12176]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Running this with git bash on windows:
```
conda create -c defaults -p ./test conda
source ./test/etc/profile.d/conda.sh
```

fails with `... Scripts/conda.exe: No such file or directory`.

Longer failure messages from non-public repo looks like this:
```
+++++ __conda_exe shell.posix activate
+++++ /cygdrive/c/b/abs_abd6jkdorj/croot/conda_1670452022046/_h_env/Scripts/conda.exe shell.posix activate
C:/Users/runneradmin/miniconda/etc/profile.d/conda.sh: line 10: /cygdrive/c/b/abs_abd6jkdorj/croot/conda_1670452022046/_h_env/Scripts/conda.exe: No such file or directory
++++ ask_conda=
```

This does not fail with conda 22.9.0 (only happens with 22.11.X).

**Comment by dbast** [comment]
This is maybe a bug not in conda but in the defaults build of conda, where the path substitution in conda.sh failed during the package build.

**Comment by kenodegard** [comment]
conda 22.11.1's `etc/profile.d/conda.sh` before path substitution: 

<img width="921" alt="Screen Shot 2022-12-13 at 11 23 09 AM" src="https://user-images.githubusercontent.com/4546435/207404792-2dc62482-ebe2-4d8e-8b5b-c9cbc0df1e3a.png">

conda 22.9.0's `etc/profile.d/conda.sh` before path substitution: 

<img width="889" alt="Screen Shot 2022-12-13 at 11 27 33 AM" src="https://user-images.githubusercontent.com/4546435/207404849-17979b0b-313d-4c46-b214-22393c480d3c.png">

**Comment by adam-urbanczyk** [comment]
I have the same issue. FWIW for me it did work with `4.12` and stopped with `2.11.1`. I don't have any data in between.

**Comment by dbast** [comment]
Looking at the code/process: This is the initial [conda.sh](https://github.com/conda/conda/blob/main/conda/shell/etc/profile.d/conda.sh) which gets the additional lines 1-4 with variable definitions visible in above screenshots injected during *package build* by the [activate.py](https://github.com/conda/conda/blob/f356172ccbb38c7aef0a925de165c671af387657/conda/activate.py#L818). The PREFIX in those variables gets replace during *installation* with the current PREFIX (what we call binary relocation). 

Is that correct?

**Comment by jezdez** [comment]
This might be mitigated by https://github.com/AnacondaRecipes/conda-feedstock/pull/22

**Comment by dbast** [comment]
yep. confirmed conda 22.11.1 build 4 has this solved.

**Comment by chucklesoclock** [comment]
For future users wondering how to update out of a broken command, use the actual `conda` file location to update. For example on Windows search for `conda.exe` and run something like:
```bash
$ /c/Users/{username}/miniconda3/Scripts/conda update conda
```
