### ISSUE TITLE
Recipe missing tqdm dependency?

### ISSUE THREAD

**Issue by jonashaag** [conda/conda#12189]
### What happened?

Building the `recipe` seems to be broken currently. I'm not quite sure what's going on here but adding `tqdm` to the `host:` dependencies in `meta.yaml` fixes the issue.

### Prior discussions in https://github.com/conda/conda/issues/12005

_Originally posted by @jonashaag in https://github.com/conda/conda/issues/12005#issuecomment-1346551765_:

> Could it be that this broke the recipe in the repo? We test Conda nightly with Mamba and a few days ago the build broke: https://github.com/mamba-org/mamba/actions/workflows/conda_nightly.yml Although I'm not quite sure why the build broke on this particular day, adding `tqdm` to the `host:` requirements seems to fix it. If this is the case, does the Conda CI not test the recipe?

_Originally posted by @kenodegard in https://github.com/conda/conda/issues/12005#issuecomment-1357910532_

> @jonashaag I wonder if this is potentially related to the need to introduce the isolated mode in conda-build:
> - https://github.com/conda/conda-build/pull/4604
> - https://github.com/conda/conda-build/pull/4625
> 
> > If this is the case, does the Conda CI not test the recipe?
> 
> What do you mean?
> 
> Let's discuss further in a new issue for better visibility

I was wondering if there is no CI step that builds and tests the `recipe/` (ie. ensure that creating a package out of the `recipe/` works correctly).

**Comment by kenodegard** [comment]
yes, we have canary builds, see the very last job in the testing workflow:
- https://github.com/conda/conda/blob/6d9415be6bb68daebb6f61d044801b1fa09ac160/.github/workflows/tests.yml#L352-L396
- https://github.com/conda/conda/actions/runs/3711734167

**Comment by jonashaag** [comment]
Thanks, didn't see those! I guess we can simply change to the canary releases.

There difference between those canaries and our nightly tests is that we test against `conda-package-handling=2` whereas the canaries test against 1.9, _which has a tqdm dependency_. So if I'm understanding things correctly, the canary build is broken with `conda-package-handling=2` because the _Conda_ recipe misses a `tqdm` dependency.

**Comment by dholth** [comment]
conda's recipe is missing a tqdm dependency. conda-package-handling=2 doesn't use tqdm.

**Comment by kenodegard** [comment]
@dholth you're right, the canary recipe was missing `tqdm` in the `requirements.host` section

see https://github.com/conda/conda/pull/12191

**Comment by dholth** [comment]
Are we planning to remove the vendored tqdm after a deprecation cycle?
