### ISSUE TITLE
Allow root to use a user's conda without modifying that conda

### ISSUE THREAD

**Issue by natefoo** [conda/conda#12186]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When an unprivileged user (alice) uses `conda install --prefix` with a conda install owned by another user (bob) or root, conda automatically switches to using `~alice/.conda` to store pkgs and cache. However, if root uses bob's conda install, this is not the case - packages will be written to bob's `$CONDA_PREFIX/pkgs/` as root. It'd be great if there was a way to explicitly invoke the "unprivileged" mode, even when running as root.

### Why is this needed?

[Galaxy](https://github.com/galaxyproject/galaxy) uses conda to install dependencies for the tools installed into Galaxy by admins, but we also sometimes use conda to install the python interpreter used to run Galaxy itself. For best practice security, this python is owned by a different user from the one that runs Galaxy, whereas the conda for tool dependencies must be writable by Galaxy since that action of installing tool dependencies is performed by Galaxy itself. The "other user" to use is up to the site administrator who's installing Galaxy, but our training materials use root.

### What should happen?

```console
$ ls -ld /opt/galaxy/dependencies/conda
drwxr-xr-x 55 galaxy galaxy 4096 Dec 16  2022 /opt/galaxy/dependencies/conda/
$ sudo /opt/galaxy/dependencies/conda/bin/conda create --prefix /opt/galaxy/python --copy --some-new-flag-that-does-the-thing python=3.9
```

Results in 0 modification to `/opt/galaxy/dependencies/conda`.

### Additional Context

There are a few workarounds that are already possible, so "won't implement" is a totally reasonable answer. But adding a way to do this would simplify the install scenarios. Here are the workarounds:

- We could of course use a second conda install, but would prefer to avoid the extra setup time and space
- We could chown post-install but that's a bit clunky, plus this process is designed to be run from config management (e.g. Ansible)
- We can set `$CONDA_PKGS_DIRS` to a tempdir [as we do here](https://github.com/galaxyproject/ansible-miniconda/pull/4), again a bit clunky but this works reasonably well and can be used for both scenarios (even though it's unnecessary for the "other unprivileged user" scenario).

**Comment by travishathaway** [comment]
Hi @natefoo,

Thank you for contributing this feature request. This sounds very reasonable, and I really appreciate the example you've included of how this should look in action.

Perhaps a `--set-owner=user_a` flag would be the best thing to add to the `create` command? We'd also need to explore if this would be necessary for `update` and `install` commands.

I can't say for sure when we will have time to work on this, but we always welcome community contributions. I will also share this issue with my colleagues, so that they can chime in on this matter.
