### ISSUE TITLE
Including conda build recipe with package source and single-sourcing version data

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1218]
It seems reasonable that the conda build recipe should be included in a project's source repo, and indeed it looks like a few conda projects [use this approach](https://github.com/conda/conda-env/tree/develop/conda.recipe). In addition, verison information for a python project should be kept in a single location; the [Python Packaging User Guide gives a few strategies](https://packaging.python.org/en/latest/single_source_version.html).

Is it possible to single-source a package's version data and include the conda build recipe in the same repo?

**Comment by asmeurer** [comment]
You can use the jinja2 templating to write in the version on the meta.yaml, or in the build script, you can write `__conda_version__.txt` to the source directory with the version. Note that the build script can access the recipe directory with the `RECIPE_DIR` environment variable.

**Comment by jrsmith3** [comment]
> or in the build script, you can write __conda_version__.txt to the source directory with the version.

I now see [similar information in the docs](http://conda.pydata.org/docs/build.html#post-build-version).

To make sure I understand: using this approach, I would include some code in `build.sh` to write a file called `__conda_version__.txt` inside the directory defined by `SRC_DIR`. Would this file just include a string with the version number, e.g. "2.0.7" and not `__version__ = 2.0.7`?

Additionally, if I were taking this approach, I would write an arbitrary version string in `meta.yaml` like so:

```
package:
  name: mypkg
  version: "0.0.0" 
```

correct? Could I use a version string like the literal "x.y.z"? If I understand correctly, `conda` will ignore the version data in `meta.yaml` in favor of `$SRC_DIR/__conda_version__.txt`, if it exists.

**Comment by asmeurer** [comment]
Yes, the string of the number, like `echo "2.0.7" > __conda_version__.txt`. The [contents of the file](https://github.com/conda/conda-build/blob/67a3d04d346eccbf8827c2f6ec5dd109068885bd/conda_build/post.py#L278-L282) (minus whitespace) are used as the version string.

**Comment by jrsmith3** [comment]
Thanks for the help!
