### ISSUE TITLE
package resolve assertion error

### ISSUE THREAD

**Issue by bekozi** [conda/conda#1219]
I'm encountering an issue with the package resolver during a build. The same issue occurs when attempting an install after a build. I think the issue boils down to the use of [this package specification](https://github.com/NESII/conda-esmf/blob/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/esmf/meta.yaml#L20) related to this [build number and string](https://github.com/NESII/conda-esmf/blob/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/gcc/meta.yaml#L10) for `gcc`. I am building `gcc` with a fortran compiler and was having trouble differentiating that build from the standard `gcc`. The build string seemed like a reasonable way to do this following from [this discussion](https://groups.google.com/a/continuum.io/forum/#!searchin/conda/features/conda/-abfo_yzVLU/mDgdkB3MvzsJ).

The build steps were:
1. [gcc](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/gcc)
2. [gcc-fortran](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/gcc-gfortran) (metapackage)
3. [f90netcdf](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/f90netcdf)
4. [esmf](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/esmf)

The build failed when attempting to build [`esmpy`](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/esmpy) due to the error below. I also noticed that the build number is not part of the filename of the built `gcc` package:

``` sh
(test_esmf)[centos@ip-172-31-38-248 linux-64]$ pwd;ls
/home/centos/anaconda/conda-bld/linux-64
esmf-HEAD-1.tar.bz2  f90netcdf-4.4.1-0.tar.bz2  gcc-4.8.2-gfortran.tar.bz2  gcc-gfortran-4.8.2-0.tar.bz2  repodata.json  repodata.json.bz2
```

Traceback:

``` sh
(test_esmf)[centos@ip-172-31-47-197 gcc]$ conda install esmf --use-local
Traceback (most recent call last):
  File "/home/centos/anaconda/envs/test_esmf/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/centos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: gcc-4.8.2-gfortran.tar.bz2 MatchSpec(u'gmp')
```

conda info:

``` sh
(test_esmf)[centos@ip-172-31-47-197 gcc]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/centos/anaconda  (writable)
  default environment : /home/centos/anaconda/envs/test_esmf
     envs directories : /home/centos/anaconda/envs
        package cache : /home/centos/anaconda/pkgs
         channel URLs : https://conda.binstar.org/bekozi/channel/dev/linux-64/
                        https://conda.binstar.org/bekozi/channel/dev/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/centos/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment]
This is a [known issue](https://github.com/conda/conda/issues/918) that if your dependencies are specified fully (down to the build string), you have to also specify all the dependencies of that package.

**Comment by bekozi** [comment]
I gave that a try and encountered an issue with the upstream package [``esmpy``](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/esmpy) having a package conflict due to the full specification in [``esmf``](https://github.com/NESII/conda-esmf/tree/b3f2ae8fd2bc675a273d0ba80b50c87e456e7308/esmf). Hence, I'm guessing the full dependency chain has to propagate all the way up. I didn't test this though.

Thanks for the help. I'll leave the issue open in case you care about the build number missing. I'll return to trying the features approach once the known issue is fixed.
