### ISSUE TITLE
A typo when setting PATH env var in conda.sh?

### ISSUE THREAD

**Issue by riven314** [conda/conda#12198]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

in https://github.com/conda/conda/blob/main/conda/shell/etc/profile.d/conda.sh#L59, I see `PATH` is appended by some paths from conda, i.e.
```
PATH="$(\dirname "$CONDA_EXE")/condabin${PATH:+":${PATH}"}"
```

should `condabin` be `conda:bin` instead? i.e.
```
PATH="$(\dirname "$CONDA_EXE")/conda:bin${PATH:+":${PATH}"}"
```

**Comment by travishathaway** [comment]
Hi @riven314,

Thanks for filing this bug. This not a typo. There actually is a `condabin` folder in conda installations.

Here is a listing of the files and folders in my own conda installation:

```
ls  ~/opt/conda
LICENSE.txt conda-bld   condabin    etc         lib         locks       pkgs        sbin        shell
bin         conda-meta  envs        include     libexec     man         python.app  share       ssl
```

That folder is specifically for the `conda` executable. I hope this helps clear things up! I will be closing this issue now.
