### ISSUE TITLE
Scroll down the package-list when downloading in parallel.

### ISSUE THREAD

**Issue by DuoLife-QNL** [conda/conda#12204]
### Checklist

- [x] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When conda starts downloading the packages in parallel, it presents a list of packages being downloaded currently or waiting to be downloaded. However, this list only has approximately 20 items. After downloading packages in this list, I lost track of the whole downloading progress, since this list does not scroll down automatically. Is it possible now to show more lines of downloading packages, or automatically scroll down this list, so that I am aware of the time about to take for the rest of the downloading progress?

**Comment by travishathaway** [comment]
Hi @DuoLife-QNL,

Thank you for filing this feature request. This is something I have experienced myself and can be quite annoying when downloading and installing many packages at once.

The library we have been using so far for this is `tqdm` but we have been considering add others in future releases to address this. We cannot promise a deliver date for any of this. I would suggest to keep an eye on our upcoming release notes to see when this layout issue will be addressed.

**Comment by travishathaway** [comment]
Hi @DuoLife-QNL,

I just realized that this work is being tracked in the following issue:

- https://github.com/conda/conda/issues/12210

I am going to close this issue and encourage you to follow the one above for updates.
