### ISSUE TITLE
Installation fails using sh

### ISSUE THREAD

**Issue by muued** [conda/conda#12207]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Installation of `Miniconda3-py310_22.11.1-1-Linux-x86_64.sh` using `sh` fails even though the install script claims it can be run using sh (`Please run using "bash"/"dash"/"sh"/"zsh", but not "." or "source".`) and the shebang points to sh (`#!/bin/sh`).

The [installation instructions](https://conda.io/projects/conda/en/stable/user-guide/install/linux.html) say `bash` should be used, so why not point to bash in the shebang, best in a portable way ```#!/usr/bin/env bash```.

Otherwise do not use bash-specific features such as `[[`.

### Additional Context

Command and script output (actual path replaced by ...):
```
sh .../Miniconda3-py310_22.11.1-1/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh -b -u -p .../Miniconda3-py310_22.11.1-1

PREFIX=.../Miniconda3-py310_22.11.1-1
Unpacking payload ...

Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
.../Miniconda3-py310_22.11.1-1/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh: 438: [[: not found

Installing * environment...

.../Miniconda3-py310_22.11.1-1/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh: 444: [[: not found

CondaFileIOError: '.../Miniconda3-py310_22.11.1-1/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '.../Miniconda3-py310_22.11.1-1/pkgs/envs/*/env.txt'`
```

**Comment by jaimergp** [comment]
Please see details in https://github.com/conda/conda/issues/10431.

The fixes were already submitted in https://github.com/conda/constructor/pull/599. In the meantime, you can use `bash` to run it. Sorry!

**Comment by muued** [comment]
Version 23.1.0-1 fixes this issue. Thank you
