### ISSUE TITLE
conda update --file

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#1220]
I believe that the `conda update` command does not supply thee --file option, but that the help text is wrong and not that typing `conda update --file` should result in an error.

**Comment by adamklein** [comment]
It would be awesome if `conda update --file` worked to alter an environment to a specific set of packages!

**Comment by ilanschnell** [comment]
I think that `conda install --file` does exactly this, ie. it alters the environment to the specific set of packages (leaving packages which are already installed, but not mentioned in the file alone).

**Comment by michs** [comment]
`Conda create --file` has some problems that probably will apply here too. See #1195
