### ISSUE TITLE
its not opening 

### ISSUE THREAD

**Issue by TjAthena** [conda/conda#12202]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Anaconda Navigator is not opening instead of open or throw an error it will open the cmd terminal repeatedly for 100 time 

### Conda Info

```shell
anaconda for windows 10 64bit
```

**Comment by LtDan33** [comment]
Thanks for the issue! This actually deals with Anaconda Navigator and not conda. You can file a ticket about Navigator here: https://github.com/ContinuumIO/anaconda-issues/issues/new/choose
