### ISSUE TITLE
Making PS1 point to link referrent of current conda environment

### ISSUE THREAD

**Issue by zbs** [conda/conda#12227]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

For convenience, we use links to organize our conda environments. For diagnostic purposes, it's useful to know what the underlying environment is. Is there a reasonable way to modify the conda activation scripts to make the PS1 prompt point to
`basename $(realpath CONDA_PATH)`?

For example, if the envs directory of our conda install were:
```
foo
bar
default -> foo
```
then, upon activating `default`, we would like the PS1 to say `(foo) user@host $`

**Comment by travishathaway** [comment]
Hi @zbs,

Thanks for submitting this issue. I have changed it from a bug to a feature request.

Implementing this wouldn't be terribly difficult. It would involve updating these lines to add a new choice of variable for the prompt:

https://github.com/conda/conda/blob/48f51e6c1d412270efbbdb1d9ff571087568b6ea/conda/activate.py#L675

We could add something like `realpath_name`. After doing that, you could configure conda to use it by setting `env_prompt: '({realpath_name}) '`. Would you be interested in working on this and submitting a pull request?

I need to let you know though, that it is very unlikely that we would change the default behavior to use `realpath`.

**Comment by zbs** [comment]
Thanks for the update! Once I have a bandwidth, I would love to work on that. TBD when that will be, however.
