### ISSUE TITLE
having problem with solving environment

### ISSUE THREAD

**Issue by thatianelimag** [conda/conda#12220]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver) and didn't see anything to help

### What happened?

I'm configuring a new pc according to the document Technical Onboarding (I'm a Business analyst). I'm having trouble in the phase of Python installed, and the process is not working correctly. What do you think I should do?

**Comment by travishathaway** [comment]
Hi @thatianelimag,

Thanks for submitting this issue. I believe it would be best to turn to your internal IT support for this type of issue. The issues for this project are for either submitting bug reports or feature requests.

If you still have this issue and you truly believe you have discovered a bug, then we will need more information from you. Ideally everything that was asked of you while submitting this issue:

The output of this command:
```
conda info
```

The output of this command:
```
conda config --show-sources
```

The output of this command:
```
conda list --show-channel-urls
```

Additionally, it would also be very helpful to know exactly which commands you were running when you came across this issue initially.
