### ISSUE TITLE
Conda deletes files it didn't create

### ISSUE THREAD

**Issue by kitswas** [conda/conda#12222]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I created a new Conda environment in a directory that already had files and subdirectories.

Later, I told Conda to remove the environment.  
Conda started emptying the directory with no furthur output.  
I interrupted (<kbd>Ctrl</kbd>+<kbd>C</kbd>) Conda when it was taking too long. 

Half of the directory was gone by then. 

### Conda Info

```shell
active environment : base
    active env location : C:\Users\swast\miniconda3
            shell level : 1
       user config file : C:\Users\swast\.condarc
 populated config files :
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.7=0
                          __win=0=0
       base environment : C:\Users\swast\miniconda3  (writable)
      conda av data dir : C:\Users\swast\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\swast\miniconda3\pkgs
                          C:\Users\swast\.conda\pkgs
                          C:\Users\swast\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\swast\miniconda3\envs
                          C:\Users\swast\.conda\envs
                          C:\Users\swast\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.4 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda list

```shell
# packages in environment at C:\Users\swast\miniconda3:
#
# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
autopep8                  1.6.0                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2022.10.11           haa95532_0    defaults
certifi                   2022.12.7       py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
colorama                  0.4.6           py310haa95532_0    defaults
conda                     22.11.1         py310haa95532_4    defaults
conda-package-handling    1.9.0           py310h8cc25b3_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              38.0.1          py310h21b164f_0    defaults
debugpy                   1.5.1           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
entrypoints               0.4             py310haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
idna                      3.4             py310haa95532_0    defaults
ipykernel                 6.9.1           py310haa95532_0    defaults
ipython                   8.7.0           py310haa95532_0    defaults
jedi                      0.18.1          py310haa95532_1    defaults
jupyter_client            7.4.8           py310haa95532_0    defaults
jupyter_core              5.1.1           py310haa95532_0    defaults
libffi                    3.4.2                hd77b12b_6    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
matplotlib-inline         0.1.6           py310haa95532_0    defaults
menuinst                  1.4.17          py310h59b6b97_0    defaults
nest-asyncio              1.5.6           py310haa95532_0    defaults
openssl                   1.1.1s               h2bbff1b_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pip                       22.3.1          py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
powershell_shortcut       0.0.1                         3    defaults
prompt-toolkit            3.0.36          py310haa95532_0    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pycodestyle               2.8.0                    pypi_0    pypi
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.4               hbb2ffb3_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pyzmq                     23.2.0          py310hd77b12b_0    defaults
requests                  2.28.1          py310haa95532_0    defaults
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
setuptools                65.5.0          py310haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.40.0               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.0          py310haa95532_0    defaults
tornado                   6.2             py310h2bbff1b_0    defaults
tqdm                      4.64.1          py310haa95532_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.13         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
xz                        5.2.8                h8cc25b3_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
```

**Comment by Prathamesh-Joshi** [comment]
Hey @kitswas , I couldn't reproduce this . Please see logs below. 
Did you deactivate env before removing it?

> (base) prathamesh@Prathamesh-MBA ~ % mkdir conda_#12222
> (base) prathamesh@Prathamesh-MBA ~ % cd conda_\#12222 
> (base) prathamesh@Prathamesh-MBA conda_#12222 % mkdir dir1 dir2
> (base) prathamesh@Prathamesh-MBA conda_#12222 % ls
> dir1	dir2
> (base) prathamesh@Prathamesh-MBA conda_#12222 % touch dir1/new.txt
> (base) prathamesh@Prathamesh-MBA conda_#12222 % ls -l
> total 0
> drwxr-xr-x  3 prathamesh  staff  96 Jan 15 01:53 dir1
> drwxr-xr-x  2 prathamesh  staff  64 Jan 15 01:53 dir2
> (base) prathamesh@Prathamesh-MBA conda_#12222 % cd dir1
> (base) prathamesh@Prathamesh-MBA dir1 % ls -lart
> total 0
> drwxr-xr-x  4 prathamesh  staff  128 Jan 15 01:53 ..
> -rw-r--r--  1 prathamesh  staff    0 Jan 15 01:53 new.txt
> drwxr-xr-x  3 prathamesh  staff   96 Jan 15 01:53 .
> (base) prathamesh@Prathamesh-MBA dir1 % cd ../  
> (base) prathamesh@Prathamesh-MBA conda_#12222 % ls -lart
> total 0
> drwxr-x---+ 84 prathamesh  staff  2688 Jan 15 01:52 ..
> drwxr-xr-x   2 prathamesh  staff    64 Jan 15 01:53 dir2
> drwxr-xr-x   4 prathamesh  staff   128 Jan 15 01:53 .
> drwxr-xr-x   3 prathamesh  staff    96 Jan 15 01:53 dir1
> (base) prathamesh@Prathamesh-MBA conda_#12222 % conda deactivate
> prathamesh@Prathamesh-MBA conda_#12222 % 
> prathamesh@Prathamesh-MBA conda_#12222 % 
> prathamesh@Prathamesh-MBA conda_#12222 % ls
> dir1	dir2
> prathamesh@Prathamesh-MBA conda_#12222 % conda create --name myenv
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
>  Package Plan ##
> 
>   environment location: /Users/prathamesh/opt/miniconda3/envs/myenv
> 
> 
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
>  To activate this environment, use
> #
>      $ conda activate myenv
> #
>  To deactivate an active environment, use
> #
>     $ conda deactivate
> 
> prathamesh@Prathamesh-MBA conda_#12222 % conda activate myenv
> (myenv) prathamesh@Prathamesh-MBA conda_#12222 % python3 --version
> Python 3.9.6
> (myenv) prathamesh@Prathamesh-MBA conda_#12222 % python3 new1.py 
> hello conda#12222 user
> (myenv) prathamesh@Prathamesh-MBA conda_#12222 % conda info --envs
> # conda environments:
> #
> base                     /Users/prathamesh/opt/miniconda3
> myenv                 *  /Users/prathamesh/opt/miniconda3/envs/myenv
> 
> (myenv) prathamesh@Prathamesh-MBA conda_#12222 % conda deactivate
> prathamesh@Prathamesh-MBA conda_#12222 % conda remove --name myenv --all
> 
> Remove all packages in environment /Users/prathamesh/opt/miniconda3/envs/myenv:
> 
> No packages found in /Users/prathamesh/opt/miniconda3/envs/myenv. Continuing environment removal
> prathamesh@Prathamesh-MBA conda_#12222 % ls -lart
> total 8
> drwxr-xr-x   2 prathamesh  staff    64 Jan 15 01:53 dir2
> drwxr-xr-x   3 prathamesh  staff    96 Jan 15 01:53 dir1
> -rw-r--r--   1 prathamesh  staff    32 Jan 15 01:58 new1.py
> drwxr-x---+ 84 prathamesh  staff  2688 Jan 15 01:58 ..
> drwxr-xr-x   5 prathamesh  staff   160 Jan 15 02:03 .
> prathamesh@Prathamesh-MBA conda_#12222 % conda info --envs              
> # conda environments:
> #
> base                     /Users/prathamesh/opt/miniconda3
> 
> prathamesh@Prathamesh-MBA conda_#12222 %

**Comment by kitswas** [comment]
>  Did you deactivate env before removing it?

Yes. I had `base` active.

> I couldn't reproduce this.

I see you tried it on Linux. I was on Windows 10, if that helps.  
Once bitten, twice shy. After losing plenty of files, I dare not try to reproduce it.

**Comment by travishathaway** [comment]
Hi @kitswas,

Thank you for filing this bug issue, and I am sorry hear of your file loss.

I did some investigation and was able to recreate your issue. These were steps I followed:

```
mkdir custom_envs
mkdir custom_envs/env_one
touch custom_envs/env_one/test.txt
conda create -p custom_envs/env_one python -y
conda env remove -p custom_envs/env_one
```

When running all these commands, the `custom_envs/env_one` will be deleted along with all it's contents (I also tested this on Windows too). Please let me know if this is similar to how you were creating and removing your environments.

I would immediately recommend only creating conda environments in their own directories going forward to avoid this situation. But, I think that conda currently provides a bad user experience by not first warning its users about exactly what is about to happen. Therefore, I would recommend that we at the very least add a "yes/no" prompt with a better summary of the actions that are about to be taken in order to better inform our users.

Let me know what you think and thanks again for filing this bug report.

**Comment by kitswas** [comment]
> Please let me know if this is similar to how you were creating and removing your environments.

Yes, it's similar. I was using the `-p` option to specify paths.

> add a "yes/no" prompt with a better summary of the actions that are about to be taken 

This would be extremely welcome.  
An alternative would be to have Conda refuse to create environments in non-empty directories (like `git clone`) as a default configuration option or similar.

**Comment by travishathaway** [comment]
Hi @kitswas,

Thanks for the feedback. I will be discussing this with our development team to see how it can be prioritized.

I have also added the https://github.com/conda/conda/labels/good-first-issue label to signal this could be a relatively easy task to complete for a would-be contributor.

We will provide further updates via this issue in the future.
