### ISSUE TITLE
Conda  remote_read_timeout_secs parameter is not being passed to pip install section

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [conda/conda#12237]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When performing a build using conda environment on CI, I have experienced following exception when performing pip install:

```
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_internal/network/download.py", line 145, in __call__
    for chunk in chunks:
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 144, in iter
    for x in it:
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/miniconda/envs/part_type_annotator/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

Ran pip subprocess with arguments:
['/usr/share/miniconda/envs/part_type_annotator/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/vsts/work/1/s/env/condaenv.r2wec809.requirements.txt']
Pip subprocess output:

The recommended way for fixing such issues for pip is to increase default_timeout
(see, for example, https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port)

For conda, the recommended way for dealing with read timeouts is to set the remote_read_timeout_secs (see, for example, https://stackoverflow.com/questions/42797957/changing-timeout-limit-when-using-conda-install)

However, changing the default read timeout does not lead to the improvement of the situation in my case, and from output of the parameters, which were passed to pip, one could see, that parameter remote_read_timeout_secs is not influencing the command line arguments, which are passed to pip installation section of conda environments.
(even after setting the parameter to 300 s, the command line used to run pip installations during conda environment creation has not changed):

conda config --set remote_read_timeout_secs 300
==> /home/vsts/.condarc <==
remote_read_timeout_secs: 300.0

Command line used to call pip install during conda environment creation:

Ran pip subprocess with arguments:
['/usr/share/miniconda/envs/part_type_annotator/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/vsts/work/1/s/env/condaenv.r2wec809.requirements.txt']

This situation leads to significant time lost due to failed builds.

**Comment by travishathaway** [comment]
Hi @serhiy-yevtushenko,

Thanks for submitting this bug. I checked out the stackoverflow link you sent along, and on the post, I found the mention of an environment variable, `PIP_DEFAULT_TIMEOUT` (more information here: https://pip.pypa.io/en/stable/topics/configuration/#environment-variables)

Have you considered trying this route?

You are correct in assuming that conda will not pass its `remote_read_timeout_secs` parameter along to pip. I personally don't agree with having it work this way, and I think that either using pip environment variables or the [pip config file ](https://pip.pypa.io/en/stable/topics/configuration/#pip-config-file)would be a better to modify the behavior of pip.

Let us know what you think and please reach out if you need any more assistance.

If my proposed solution fixes your problem, I kindly ask that you close out this issue.

**Comment by serhiy-yevtushenko** [comment]
Hi, Travis.

Thank you for providing this feedback and suggesting a way to solved problem.

I will investigate the solution that you have suggested.

At the same time, I believe that it makes sense to cover this behavior in the documentation of the conda.

The reason for this, for example, that I experienced this problem while running the CI/CD builds, where conda was working properly and pip parts of conda build was failing with ReadTimeOut error. 
The conda way for fixing read_timeout_error has not fixed a problem for me (and my assumption was, that conda should manage pip parameters as well, as pip invocation is being configured inside the conda environment).

So, I think that in case, when workaround will be working, this information should be documented in conda documentation.

**Comment by travishathaway** [comment]
Hi @serhiy-yevtushenko,

I think that adding documentation to cover this is a very good idea. I would specifically suggestion this section:

https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-environments.html#using-pip-in-an-environment

I will go ahead and create another issue to suggest doing this.

Please let us know if this actually ends up being a valid solution for you.
