### ISSUE TITLE
Already locally satisfied dependencies must be available in remote repositories for "install"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1223]
I am installing a package which requires `flask-login` (any version).  It is already available locally in `conda-meta` and `pkgs` directories for the env I am installing to:

```
flask-login-0.2.9-py27_33.tar.bz2
flask-login-0.2.9-py27_33.json
```
However when I go install a package that lists `flask-login` as a dependency, I'm told:
```
Error: No packages found in current linux-64 channels matching: flask-login
Did you mean one of these?
    flask-ldap-login
```
It is surprising to me that conda doesn't realize that the package is already installed, or at least that it is already available in the local package cache.

If I provide a binstar channel where `flask-login` exists, `conda install` happily proceeds and at *that point* realizes that it is already installed so no additional action is required.

**Comment by asmeurer** [comment]
Use the `--unknown` flag. We had this flag as the default at one point, but it lead to more issues than it solved.
