### ISSUE TITLE
Anaconda.org channels being fetched in addition to channels defined in .condarc

### ISSUE THREAD

**Issue by andreostrovsky** [conda/conda#12243]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver) and didn't see anything to help

### What happened?

When using `solver: libmamba`, conda fetches repodata for Anaconda.org channels whenever solving the environment:
```
pkgs/r/win-64
pkgs/msys2/noarch
pkgs/main/noarch
pkgs/msys2/win-64
pkgs/r/noarch
pkgs/main/win-64
```
despite these channels not being configured anywhere. My .condarc explicitly only lists conda-forge, accessed through my organization's jfrog artifactory. 
When using the classic solver, conda respects this. As does mamba. Yet when using the libmamba solver, it ignores this and pulls repodata for these channels regardless.
This is a security issue, as I do not want connections made to any sources outside my organization, and have explicitly configured conda as such.

I have verified: 
- In `prefix/pkgs/cache` the Anaconda.org channel repodata is in fact being downloaded.
- There are no packages installed in the environment from any of these channels.
- There is no mention of any of these channels in `prefix/pkgs/urls.txt`
- There is no mention of any of these channels in `prefix/conda-meta/history`
- I have run `conda clean --all`

### Conda info

```Shell
active environment : base
   active env location : C:\Users\xxx\prefix
           shell level : 0
      user config file : C:\Users\xxx\.condarc
populated config files : C:\Users\xxx\.condarc
         conda version : 22.11.1
   conda-build version : not installed
        python version : 3.9.13.final.0
      virtual packages : __archspec=1=x86_64
                         __win=0=0
      base environment : C:\Users\xxx\prefix   (writable)
     conda av data dir : C:\Users\xxx\prefix\etc\conda
 conda av metadata url : None
          channel URLs : https://xxx:yyy@zzz/api/conda/remote-conda-forge-public/win-64
                         https://xxx:yyy@zzz/api/conda/remote-conda-forge-public/noarch
         package cache : C:\Users\xxx\prefix\pkgs
                         C:\Users\xxx\.conda\pkgs
                         C:\Users\xxx\AppData\local\conda\conda\pkgs
      envs directories : C:\Users\xxx\prefix\envs
                         C:\Users\xxx\.conda\envs
                         C:\Users\xxx\AppData\local\conda\conda\envs
              platform : win-64
            user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.19044
         administrator : False
            netrc file : None
          offline mode : False
```

### Conda config

```Shell
==> C:\Users\xxx\.condarc <==
ssl_verify: False
channel_alias: https://xxx:yyy@zzz/api/conda/
channels:
  - remote-conda-forge-public
show_channel_urls: False
solver: libmamba
```

### Conda list

```Shell
I cannot provide this due to the organization's security policies. The conda info and config above was typed out manually. 
Since I can't type out the entire package list, here are some relevant ones:
conda                   22.11.1   py39hcbf5309_1
conda-libmamba-solver   22.12.0   pyhd8ed1ab_0
libmamba                1.1.0     hd18bbca_2
libmambapy              1.1.0     py39h608c70e_2
mamba                   1.1.0     py39hca8391b_2
python                  3.9.13    hcf16a7b_0_cpython
```

**Comment by travishathaway** [comment]
Hi @andreostrovsky,

Thank you for taking the time make these detailed bug report. I have reported this to the group responsible for resolving `libmamba` related issues, and we hope to get to it as soon as possible.

In the meantime, I will be moving it over to https://github.com/conda/conda-libmamba-solver as that is the better place for this particular issue.

**Comment by travishathaway** [comment]
Hi @andreostrovsky,

Looks like you have already created the same issue in `conda-libmamba-solver`. Thanks for doing that. I will be closing this issue for now.
