### ISSUE TITLE
Remove coverage options from default `setup.cfg`; ensure in CI scripts

### ISSUE THREAD

**Issue by dholth** [conda/conda#12246]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`setup.cfg` has a few options enabling `--cov conda`, and other coverage options. These are a nuisance when debugging, since they have to be commented out for the debugger. They will also slow the tests a bit. Remove them, add them back in the CI scripts.

**Comment by travishathaway** [comment]
I too find myself commenting out everything generating coverage reports while running tests. It would be nice to have a way to easily run things without the "kitchen sink" being the default.

**Comment by dholth** [comment]
Sounds good, we can easily comment those lines out and test that in a PR (assuming we still want coverage on the github actions runs), and we only have to pass a --cov or two in the pytest invocations.

**Comment by dholth** [comment]
[Fixed.](https://github.com/conda/conda/pull/12268)
