### ISSUE TITLE
Can't support 3.11 codes yet?

### ISSUE THREAD

**Issue by Mu-Xiu-Yulin** [conda/conda#12258]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Compared with 3.10, 3.11 is a lot better, we don't need it to be the default python, only the main branch of conda can be upgraded to 3.11.1

### Why is this needed?

Compared with 3.10, 3.11 is a lot better, we don't need it to be the default python, only the main branch of conda can be upgraded to 3.11.1

### What should happen?

no

### Additional Context

no

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues/new/choose). This is the issue tracker for the conda package manager software. Thank you for understanding!
