### ISSUE TITLE
CONDA_OVERRIDE_GLIBC="" => AttributeError: A value for size has not been set

### ISSUE THREAD

**Issue by croth1** [conda/conda#12267]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

conda-lock currently does not work with conda>22.9, see: https://github.com/conda-incubator/conda-lock/issues/292

Between 22.9 and 22.11 there seems to be a change in how CONDA_OVERRIDE_* variables work:

```bash
# fine on 22.9
docker run --rm -e CONDA_OVERRIDE_GLIBC="" -v $(pwd)/mock_repo:/mock_repo condaforge/mambaforge:22.9.0-3  bash -c "conda create -c file:///mock_repo -n foo --dry-run python=3.9  gdal"

# fine on 22.11 without setting CONDA_OVERRIDE_GLIBC=""
docker run --rm -v $(pwd)/mock_repo:/mock_repo condaforge/mambaforge:22.9.0-3  bash -c "conda install conda=22.11 -n base -y; conda create -c file:///mock_repo -n foo --dry-run python=3.9 gdal"

# breaks with 22.11
docker run --rm -e CONDA_OVERRIDE_GLIBC="" -v $(pwd)/mock_repo:/mock_repo condaforge/mambaforge:22.9.0-3  bash -c "conda install conda=22.11 -n base -y; conda create -c file:///mock_repo -n foo --dry-run python=3.9 gdal"

# breaks with main:
docker run --rm -e CONDA_OVERRIDE_GLIBC="" -v $(pwd)/mock_repo:/mock_repo condaforge/mambaforge:22.9.0-3  bash -c "git clone https://github.com/conda/conda.git; cd conda; pip install . ; conda --version; conda init; conda create -c file:///mock_repo -n foo --dry-run python=3.9 gdal"
```
channel: [mock_repo.zip](https://github.com/conda/conda/files/10483679/mock_repo.zip)

Error:
```
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/auxlib/entity.py", line 406, in __get__
        val = instance.__dict__[self.name]
    KeyError: 'size'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/install.py", line 334, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/install.py", line 350, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 952, in print_transaction_summary
        change_report_str = self._change_report_str(change_report)
      File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 1002, in _change_report_str
        size = prec.size
      File "/opt/conda/lib/python3.10/site-packages/conda/auxlib/entity.py", line 412, in __get__
        raise AttributeError(f"A value for {self.name} has not been set")
    AttributeError: A value for size has not been set

`$ /opt/conda/bin/conda create -c file:///mock_repo -n foo --dry-run python=3.9 gdal`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_DIR=/opt/conda
     CONDA_OVERRIDE_GLIBC=
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.1.0.post7+d5281f611
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=0=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : file:///mock_repo/linux-64
                          file:///mock_repo/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0.post7+d5281f611 requests/2.28.1 CPython/3.10.8 Linux/5.15.49-linuxkit ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### Conda Config

```shell
==> /opt/conda/.condarc <==
channels:
  - conda-forge
```

**Comment by travishathaway** [comment]
Hi @croth1,

Thanks for filing the bug. We hope to get a fix for this as soon as possible and to include it in our next upcoming release. 

We will keep you updated via this issue.

**Comment by jezdez** [comment]
I wonder if this is related to #12219 and could be fixed by #12257 to be released in 23.1.0?

**Comment by croth1** [comment]
@jezdez, I checked with conda main branch yesterday (23.1.0.post7+d5281f611) - and I still get the error, where the fix should already be in, so might not be exactly the same issue.

**Comment by dholth** [comment]
https://github.com/conda/conda/pull/11854/files#diff-a2a8adb5655f8100ed16e96feed682b9d2982d2010503cf4976b48847a608930L201

**Comment by croth1** [comment]
@dholth, I think this is all done deliberately, in fact the whole repository seems to be just for satisfying virtual packages: see the code here: https://github.com/conda-incubator/conda-lock/blob/main/conda_lock/virtual_package.py#L50
I feel this has to do with conda-lock have to solve cross-platform, but I need to double check that. I think those are fake dependencies that are just for making it solvable, and are filtered out later. I need to check the code in depth, but I won't have time for this today anymore :(

**Comment by croth1** [comment]
So a bit more testing. One aspect is that `size` seems to have accidentally(?) become mandatory in conda 22.11's PackageRecord (see also observations from @dholth in https://github.com/conda-incubator/conda-lock/issues/292). In fact if I change the repodata.json and add `"size" : 0` in all PackageRecords, the error seems to disappear with conda=22.11 and conda-lock works again.

However mamba would still fail, even when `size` is present. Not sure why mamba would behave differently in this case - my assumption was that it would also just use conda's plugin infrastructure. Maybe @wolfv might have an educated guess what's different there? I can again try to build docker container reproducing the issue if that helps.

**Comment by dholth** [comment]
Didn't immediately notice the diff where size was made mandatory

**Comment by croth1** [comment]
Okay, I played a bit around with the debugger:
It seems losing this part changed the behavior between 22.9 and 22.11. Before if `CONDA_OVERRIDE_GLIBC=""` was set, no virtual package for glibc was exported.
https://github.com/conda/conda/blob/60e11b4f1859874c1cb1a3ae324e599e0867a086/conda/core/index.py#L203-L206

In the new plugin code, it seems this logic has been lost:

https://github.com/conda/conda/blob/82fa24baedcb42a9504912f6f851aeeae2fc478f/conda/core/index.py#L184-L185

i.e. the virtual glibc package gets exported either way.

The channel hackery in conda-lock however relies on no glibc package being exported, otherwise an update of a virtual package is generated, which causes mayhem.
