### ISSUE TITLE
Cleanup `conda._vendor.tqdm`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#12264]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

There is a [patch]( https://github.com/conda/conda/blob/4df3f7815054e5c3fc66a1a861e2de1bdf09b5fa/tools/vendoring/patches/tqdm.patch ) for the vendored `tqdm`. However `tqdm` has been unvendored ( https://github.com/conda/conda/pull/12005 ). So this patch shouldn't be needed any more. Think we can drop it.

**Comment by jakirkham** [comment]
Oops missed that you had renamed this, Ken. Had thought I simply forgot to specify "patch" in the title.

In any event, think `tqdm` vendoring is mostly removed already. There is just a lingering piece. It's probably an easy PR. That is unless I've missed something (hence the issue to check my reasoning)

**Comment by kenodegard** [comment]
@jakirkham sorry! I was torn since the vendored tqdm codes haven't been removed yet (just pending deprecation per CEP9), either way thanks for starting this discussion, this will be a good place to coordinate the remaining cleanup

**Comment by jakirkham** [comment]
Ah ok. Was not aware there were other remaining pieces. Thank you for correcting me. Have updated the title to hopefully better capture that

**Comment by jakirkham** [comment]
@kenodegard do you know the current status on this issue?

**Comment by kenodegard** [comment]
`tqdm` was de-vendored in #12005 (22.11.0) and removed in #12948 (23.9.0)

so this is moot/resolved

**Comment by jakirkham** [comment]
Thanks Ken! 🙏
