### ISSUE TITLE
Update packaging.python.org cross-reference to conda

### ISSUE THREAD

**Issue by ncoghlan** [conda/conda#1226]
I'm pretty sure the conda reference at https://packaging.python.org/en/latest/science.html#the-conda-cross-platform-package-manager is out of date in various respects, but I don't know what it should say instead.

A PR from the conda team to modernise it appropriately would be appreciated :)

**Comment by asmeurer** [comment]
Where is the source code where I can submit a pull request?

**Comment by kerrywatsonking** [comment]
I'll update this description of conda and post it here. Kerry

**Comment by ncoghlan** [comment]
Edit link from the bottom left of the RTFD page: https://github.com/pypa/python-packaging-user-guide/edit/master/source/science.rst

**Comment by asmeurer** [comment]
https://github.com/pypa/python-packaging-user-guide/pull/150

**Comment by asmeurer** [comment]
By the way, I would have never figured out that that RTD footer expanded like that.
