### ISSUE TITLE
Introduce deprecation tooling

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12276]
### What is the idea?

With CEP9 we define a deprecation schedule. To make adherence as easy as possible we want to introduce appropriate tooling that makes it easy to deprecate functions/methods, arguments, constants, modules, or even specific logic paths within the code.

### Why is this needed?

Deprecating code is annoying since we need to remember when to switch from pending deprecation (the comment period) to deprecated to raising errors once it needs to be removed.

### What should happen?

Either introduce a third-party package or implement something custom that can be easily extended to all conda projects for their deprecation needs.

```[tasklist]
- [ ] #12125
- [ ] #12452
```

**Comment by timhoffm** [comment]
FYI, we have internal deprecation tooling over at https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_api/deprecation.py

Beyond simply deprecating functions, we can define deprecations in preparation of
- making attributes private
- renaming parameters
- deleting parameters
- making parameters keyword-only
- renaming methods that may be overridden by downstream users

Feel free to borrow.

**Comment by kenodegard** [comment]
Completed via #12125 #12452
