### ISSUE TITLE
Remove `NotebookSpec` from conda env

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12307]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Apparently, `NotebookSpec` was planned to be removed in conda 4.5 and never was, so let's do it. See this warning for more information:

https://github.com/conda/conda/blob/main/conda_env/specs/notebook.py#L21

### What should happen?

Remove this from conda env commands. This is the module you will need to update:

https://github.com/conda/conda/tree/main/conda_env/specs

**Comment by kannanjayachandran** [comment]
Hi, I would like to work on this issue, do I just need to remove the warning (the  print statement)  ?

**Comment by beeankha** [comment]
Hi @kannanjayachandran, go for it! All instances of `NotebookSpec` need to be removed from the `conda env` code, so you'll have to either update or delete the following:

- [`__init__.py` file](https://github.com/conda/conda/blob/main/conda_env/specs/__init__.py)
- [`notebook.py` file](https://github.com/conda/conda/blob/main/conda_env/specs/notebook.py)
- [Related test file](https://github.com/conda/conda/blob/main/tests/conda_env/specs/test_notebook.py)

Please let us know if you have questions, or if you end up not having the time to do this fix.

**Comment by beeankha** [comment]
@kannanjayachandran when you file a pull request, please remember to assign yourself to this issue and also add a link to this issue on your PR.

**Comment by kannanjayachandran** [comment]
Hi @beeankha I have removed;

- [`__init__.py` file](https://github.com/conda/conda/blob/main/conda_env/specs/__init__.py)
- [`notebook.py` file](https://github.com/conda/conda/blob/main/conda_env/specs/notebook.py)
- [Related test files](https://github.com/conda/conda/blob/main/tests/conda_env/specs/test_notebook.py)

Can you please assign this issue to me I am not able to assign this issue to myself. Thank you

**Comment by kannanjayachandran** [comment]
> Hi @kannanjayachandran , I don't see a pull request related to this issue; did you file one?

@beeankha  I have made the pull request please check if it is fine

**Comment by beeankha** [comment]
@kannanjayachandran I'm currently in the process of adding you to the contributor's list; once that goes through, I'll review your PR 👍

**Comment by kannanjayachandran** [comment]
HI @travishathaway  sorry to bother you, could please review the  [new pull request](https://github.com/conda/conda/pull/12363) I have submitted

**Comment by travishathaway** [comment]
Hi @kannanjayachandran,

Thanks for your revisions. The pull request just needs a news file, which I can add for you. If you're curious, you can look in the "news" folder of the repository for examples of what this looks like.
