### ISSUE TITLE
`conda create --name MyEnv -c conda-forge python=3.9` installs pypy in place of python 

### ISSUE THREAD

**Issue by MordicusEtCubitus** [conda/conda#12308]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When installing python in a new environment with conda and conda forge, pypy is installed in place of python:

```bash
conda create --name MyEnv -c conda-forge python=3.9 

...
python             conda-forge/linux-64::python-3.9.16-0_73_pypy None
...
```
Need to specify python=3.9.15 to get around this

**Comment by exs-bbutt** [comment]
Experiencing this issue also.

**Comment by JosephWagner** [comment]
I hit this same issue. I found a workaround was to use python_abi package to help limit to cpython.

`conda create --name MyEnv -c conda-forge python=3.9  python_abi=3.9=*cp*`

https://github.com/conda-forge/python_abi-feedstock

**Comment by beeankha** [comment]
Hi @MordicusEtCubitus , thanks for taking the time to file this issue.

I tried recreating this on both MacOS and Windows, without success. When I run either `conda create --name MyEnv -c conda-forge python=3.9` or the workaround command `conda create --name MyEnv -c conda-forge python=3.9  python_abi=3.9=*cp*`, I get:

```
...
python             conda-forge/win-64::python-3.9.16-h4de0772_0_cpython
...
```

Could you please re-try installing `conda-forge python=3.9` in a new env to see if maybe it was a conda-forge issue that is now fixed?

**Comment by MordicusEtCubitus** [comment]
I confirm on my linux the issue no more exists
Also on my server installed with mambaforge

It appears the issue seems to be solved !

**Comment by beeankha** [comment]
Wonderful, thank you for checking and for updating this issue! I'll go ahead and close this out.
