### ISSUE TITLE
Remove optimization to match `track_features`

### ISSUE THREAD

**Issue by dholth** [conda/conda#12314]
### What happened?

https://github.com/conda/conda/blob/main/conda/core/subdir_data.py#L154-L161 is code to match `track_features`, but it looks for the match against a nonexistent field `track`.

This has been broken since at least 2017 https://github.com/conda/conda/commit/12669896ecaa7c853ea8028958c44ef86515402f#diff-ca5dabe5c431ae6f12bae85508e4f38520d264980ba10060eb882cdeff8fc5f4L120

And the SubdirData._track_features index doesn't split features by commas, instead, it creates one-letter features.

Remove the index used for searching on track_features when the exact package name is not given '*[track_features=<name>]'

**Comment by jezdez** [comment]
Hm, given that there are [plenty of uses in the wild](https://github.com/search?q=track_features+language%3AYAML&type=code&l=YAML), I think a better way to handle this would be to fix the feature?

**Comment by dholth** [comment]
@jezdez the PR fixes searching on track-features, and that has been broken for at least five years. I'm a little concerned _fixing it_ will break something.

AFAIK solver constraints on track_features work differently than "`conda search *[track_features=<name>]`"

**Comment by jezdez** [comment]
Right, what I'm saying is that you're removing a feature instead of fixing the bug in the search implementation, I believe the age of the bug doesn't really matter if it's a thing that users might search for.

**Comment by dholth** [comment]
@jezdez I added the feature back in.

For the longest time, "`conda search *[track_features=x]`" would look for the nonexistent "track" property, and always return zero results. But it would be fast, because it used the index.

Now that kind of search may return results but it will check against all available packages, instead of using the removed index.
