### ISSUE TITLE
Miniconda for apple silicon M2 (pro/max chipsets)

### ISSUE THREAD

**Issue by horsto** [conda/conda#12317]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Are there any estimates on when installers will be available for miniconda for the newest apple silicon M2 (pro/max)? The current installers (https://conda.io/en/latest/miniconda.html#latest-miniconda-installer-links) all run into system not supported errors.

**Comment by dbast** [comment]
Please try again with:
* https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh OR
* https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.pkg

they both should work.

**Comment by horsto** [comment]
Thanks, that did actually work. Mac OS Ventura throws exceptions in the installer since it wants to access disk folders (not sure about the specific reason it is forbidden).

**Comment by ayulockin** [comment]
The `.pkg` installer is not working and throws the system incompatible error. The `.sh` file is working fine.

**Comment by CGCooke** [comment]
> The `.pkg` installer is not working and throws the system incompatible error. The `.sh` file is working fine.

I experienced the same thing.

**Comment by pseudoyim** [comment]
If you run into the `This package is incompatible with this version of macOS` error, we've posted a workaround [here](https://docs.anaconda.com/free/anaconda/reference/troubleshooting/#this-package-is-incompatible-with-this-version-of-macos-error-when-running-a-pkg-installer-on-osx).

**Comment by frankl1** [comment]
> If you run into the `This package is incompatible with this version of macOS` error, we've posted a workaround [here](https://docs.anaconda.com/free/anaconda/reference/troubleshooting/#this-package-is-incompatible-with-this-version-of-macos-error-when-running-a-pkg-installer-on-osx).

This worked for me like a charm

**Comment by gregv** [comment]
Ensure you're using ZSH: https://discussions.apple.com/thread/250777998

**Comment by naosuzuki** [comment]
I'm getting the following errors for the .sh version.   Any workaround ideas?  Thanks!

Preparing transaction: done
Executing transaction: | 
done
Miniconda3-latest-MacOSX-arm64.sh:367: no matches found: /Users/mydirectory/miniconda3/pkgs/envs/*/

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
