### ISSUE TITLE
conda can not install anaconda 

### ISSUE THREAD

**Issue by NaseemYehya** [conda/conda#12326]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I needed to install anaconda in order to upgrade Conda to a newer version in the virtual environment.
unfortunately, after I wrote "conda install anaconda" in the PyCharm terminal
and then Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

       root environment : C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv  (writable)
    default environment : C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv
       envs directories : C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\envs
          package cache : C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Naseem Yehya\.condarc
           offline mode : False

 During handling of the above exception, another exception occurred:
      File "C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\lib\site-packages\conda\cli\main_install.py", line 80, in execute    
        install(args, parser, 'install')
      File "C:\Users\Naseem Yehya\Documents\GitHub\byzantine-robust-optimizer\venv\lib\site-packages\conda\cli\install.py", line 420, in install        
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration

what can i do

### Conda Info

```shell
Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.11.final.0
       requests version : 2.28.2
```

**Comment by travishathaway** [comment]
Hi @NaseemYehya,

Thank you for submitting this issue. You are currently running a pretty old version of conda, and therefore cannot do the required upgrade. You will need to reinstall conda using one of our more up to date installers:

https://docs.conda.io/en/latest/miniconda.html

Inquiries like this are considered off topic for this repository, so this issue will be closed.
