### ISSUE TITLE
Conda update conda failing due to incompatible packages, directly after installing miniconda

### ISSUE THREAD

**Issue by pig-raffles** [conda/conda#12325]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi,

I recently had to uninstall anaconda and I reinstalled miniconda. Now, whenever I try and install a package, I get loads of packaging conflicts, which shouldn't exist as I have just installed miniconda. I running miniconda on a Mac M1

For instance when I use the command: conda update conda, I get the following error messages:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda):

  - conda -> conda[version='>=23.1.0']
  - conda -> ruamel.yaml[version='>=0.11.14,<0.18'] -> setuptools
  - conda -> setuptools[version='>=31.0.1']

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Apologies if this is a simple error but I haven't found someone with a similar issue yet. Thanks in advance for any help you can give

### Conda Info

```shell
active environment : base
    active env location : /Users/alan02/miniconda3
            shell level : 1
       user config file : /Users/alan02/.condarc
 populated config files : /Users/alan02/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.2=0
                          __unix=0=0
       base environment : /Users/alan02/miniconda3  (writable)
      conda av data dir : /Users/alan02/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/alan02/miniconda3/pkgs
                          /Users/alan02/.conda/pkgs
       envs directories : /Users/alan02/miniconda3/envs
                          /Users/alan02/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.8 Darwin/22.3.0 OSX/13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/alan02/.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
```

### Conda list

```shell
# packages in environment at /Users/alan02/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py310h1a28f6b_1002    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
ca-certificates           2023.01.10           hca03da5_0    defaults
certifi                   2022.12.7       py310hca03da5_0    defaults
cffi                      1.15.1          py310h80987f9_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.1.0          py310hca03da5_0    defaults
conda-content-trust       0.1.3           py310hca03da5_0    defaults
conda-package-handling    2.0.2           py310hca03da5_0    defaults
conda-package-streaming   0.7.0           py310hca03da5_0    defaults
cryptography              38.0.4          py310h834c97f_0    defaults
idna                      3.4             py310hca03da5_0    defaults
libffi                    3.4.2                hca03da5_6    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   1.1.1s               h1a28f6b_0    defaults
pip                       22.3.1          py310hca03da5_0    defaults
pluggy                    1.0.0           py310hca03da5_1    defaults
pycosat                   0.6.4           py310h1a28f6b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1           py310hca03da5_0    defaults
python                    3.10.8               hc0d8a6c_1    defaults
python.app                3               py310h1a28f6b_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
requests                  2.28.1          py310hca03da5_0    defaults
ruamel.yaml               0.17.21         py310h1a28f6b_0    defaults
ruamel.yaml.clib          0.2.6           py310h1a28f6b_1    defaults
setuptools                65.5.0          py310hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.40.1               h7a7dc30_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
toolz                     0.12.0          py310hca03da5_0    defaults
tqdm                      4.64.1          py310hca03da5_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.14         py310hca03da5_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.10               h80987f9_1    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.18.0          py310h1a28f6b_0    defaults
```

**Comment by dholth** [comment]
Does this still happen if you remove `channel_priority: strict` or put defaults first?

**Comment by pig-raffles** [comment]
The settings conda has right now on my system are those recommended by
Bioconda.

"First, install conda. Then perform a one-time set up of Bioconda with the
following commands
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict"

I tried moving the defaults channel to the highest priority using "conda
config --add channels defaults" again and it seems to have resolved the
conflicts. Thanks!

So, why is using the Bioconda default settings is suddenly causing these
problems?

**Comment by travishathaway** [comment]
Hi @pig-raffles,

I'm glad you found a solution to this issue. The Bioconda and conda-forge channels are not static. This means that they are constantly changing as new packages are being added. This can lead to scenarios where seemingly nothing has but yet the solver fails to find solutions. This can also happen when mixing the "defaults" and "conda-forge" channels.

I would recommend just relying on the "conda-forge" channel only as it provides everything that "defaults" does.

I will now be closing this issue.
