### ISSUE TITLE
Prevent conda from being installed in conda environment

### ISSUE THREAD

**Issue by tierriminator** [conda/conda#12321]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

For packages which list a dependency for conda, conda will be installed in a conda environment, even if the currently available version fulfills the requirement.
I would expect conda to recognize the requirement as already installed and to not install another version of conda.

I experienced this issue in a project where I provide my own conda recipe and have conda-build installed in my environment.
Since conda is a dependency of conda-build, conda will be installed in my current environment, which triggers microsoft/vscode-python#19069, which is based on #12082.

**Comment by jaimergp** [comment]
If a Python package depends on the `conda` Python library, then it needs it in its own separate environment; i.e. it can't `import conda` from the `base` environment.

**Comment by tierriminator** [comment]
Ok, I guess this resolves the issue. Thanks for the answer.
