### ISSUE TITLE
Deprecate `use_only_tar_bz2` flag or warn when it is in use, since conda-forge only produces `.conda` now

### ISSUE THREAD

**Issue by dholth** [conda/conda#12332]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Now that `.conda` is widely, and sometimes exclusively used, the use-only-tar-bz2 flag has outlived its usefulness. 

e.g. https://github.com/scipy/scipy/pull/17921

Users who are using this flag will increasingly miss out on all new conda-forge packages, and it's likely that all conda publishers will switch to `.conda`-only in the future.

We could warn if the flag is in use, and especially add text to PackageNotFound's error message warning about the flag.

It might not be practical to search for the missing packages in the .conda section of repodata.json, since at that point in the code we may have thrown away that part of the data.

**Comment by jezdez** [comment]
I think this can be closed via #12353.

**Comment by jaimergp** [comment]
I think we need to add a similar warning to `conda search`. See conversation in https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$168245707744TmQdB:gitter.im?via=matrix.org&via=gitter.im&via=staffchat.ethz.ch
