### ISSUE TITLE
Packaging for Debian and Ubuntu

### ISSUE THREAD

**Issue by cowlicks** [conda/conda#1235]
Is there any current plan for packaging Conda for Debian/Ubuntu/Mint?

**Comment by asmeurer** [comment]
Not really. Would conda fulfill their requirements?

**Comment by cowlicks** [comment]
`conda/LICENSE.txt` does not say what *kind* of license continuum gives it, but I think it is BSD? And it includes some GPL libraries. So I think it meets the legal requirements.

I was mostly asking because I don't want to duplicate effort, I can look more into this.

**Comment by ccordoba12** [comment]
Given that conda is an alternate package manager (whose packages will surely conflict with the ones provided by Debian), I really doubt Debian maintainers will accept it in their repos.

Not to discourage you, but I think it's not worth the effort :-)

**Comment by asmeurer** [comment]
Yes, everything is BSD (except for progressbar, which is LGPL). 

I wasn't referring to legal requirements. The various distros have many technical requirements for packages in their repos. For instance, would they be OK with conda installing its own Python, rather than using the Debian, etc. Python? Debina has a [huge](https://www.debian.org/doc/debian-policy/) document of requirements. 

You're welcome to try. I don't think it's something that Continuum should really be spending its resources trying to do. We benefit from building our own ecosystem (which is open source and extendable by others), so that we are not restricted by arbitrary rules from other authorities. The recommended way to install conda on Linux is and will remain installing Anaconda or Miniconda.

**Comment by bignose-debian** [comment]
> Given that conda is an alternate package manager […] I really doubt Debian maintainers will accept it in their repos

The Python “pip” package manager is already in the Debian system, available to install with the `python3-pip` package.

> The recommended way to install conda on Linux is and will remain installing Anaconda or Miniconda.

So, how can we install that on a Debian system?

Running some arbitrary shell script via “download shell script and run it” is – quite rightly – deprecated as a security flaw; we expect users to be very wary of such advice. Much better to have `conda` installable using the operating system package manager.

**Comment by kalefranz** [comment]
deb, ppa, and rpm (signed) repos are in the works.

**Comment by bignose-debian** [comment]
@kalefranz, thank you!

Who are you working with in the Debian Project, to get Anaconda into the Debian repositories?

**Comment by chrysn** [comment]
> Given that conda is an alternate package manager (whose packages will surely conflict with the ones provided by Debian), I really doubt Debian maintainers will accept it in their repos.

I don't think that being an alternate package manager is by itself a reason not to be included in Debian. (eg. [flatpak](https://packages.debian.org/flatpak) is shipped in Debian, as are tools like [alien](https://packages.debian.org/alien) for converting between packaging formats and various rpm tools). Also, browsers are their package managers these days, and while there are efforts to package addons so they can be installed system-wide with well-understood update policies, and programs are discouraged to give away users starting them by asking for online updates of addons without user confirmation, they are being shipped in Debian.

> For instance, would they be OK with conda installing its own Python, rather than using the Debian, etc. Python? Debian has a huge document of requirements.

Those are mainly on how the package installs itself into the system (eg. "no files in those areas", "when can you use statically linked libraries"), how it behaves during build (eg. "no network access") and how it's licensed (eg. be free software). What it does when it is invoked during regular operation is much less regulated, and as I understand conda so far, it could use the system's Python for running itself, and if it then installs a different Python in a directory given by a user on their behalf, that's fine.

@kalefranz, if you start working on debs, please announce your Intent To Package by opening an issue in Debian's [WNPP](https://www.debian.org/devel/wnpp/) bug tracker (and ideally crossreference with this issue). This will ensure that people interested in packaging Conda for Debian will find it from the other side too.

**Comment by kalefranz** [comment]
> Given that conda is an alternate package manager (whose packages will surely conflict with the ones provided by Debian), I really doubt Debian maintainers will accept it in their repos.

I also disagree. I'm sure `apt-get install python-pip` works just fine.  Having debs and rpms as a way to bootstrap conda onto a system instead of just the miniconda shar installer is definitely on our TODO list.

**Comment by GbengaOdesanmi** [comment]
@all please does anyone have the idea of how to solve this problem
Thanks in advance.

bash: /home/gbenga/miniconda2/etc/profile.d/conda.sh: No such file or directory
(base) gbenga@gbenga-Lenovo:~/baselines$ conda activate my_envCould not find conda environment: my_env
You can list all discoverable environments with `conda info --envs`.

(base) gbenga@gbenga-Lenovo:~/baselines$ conda create my_env

CondaValueError: The target prefix is the base prefix. Aborting.

**Comment by Evidlo** [comment]
I think this should still be pursued.  The standard method for installing conda is via shell script as root, which is bad practice.

**Comment by mingwandroid** [comment]
> The standard method for installing conda is via shell script as root

Those is untrue. No one should use root by default,  unless they're doing a multiuser install or something, but even then a group and group permissions will work out better in most cases. 

Miniconda can be installed without root just fine.

**Comment by daissi** [comment]
Hi,
There is a [discussion](https://lists.debian.org/debian-med/2019/04/msg00003.html) within the Debian Med team to package conda. The packaging takes place [here](https://salsa.debian.org/med-team/conda/).

Best,
Dylan

**Comment by magicgoose** [comment]
> Given that conda is an alternate package manager (whose packages will surely conflict with the ones provided by Debian), I really doubt Debian maintainers will accept it in their repos.

I think it's less about whether it will be accepted and more about whether this is doable at all (with a 3rd party PPA if needed), right?

**Comment by allefeld** [comment]
Not sure whether this is the right place, but I couldn't think of another:

In the [Debian repository for miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html), `conda` is still at version 4.7.11, which is now 8 months old, while the last release here is 4.8.2.

Is the Debian repository still maintained? If yes, can we expect an update anytime soon?

In the meantime, conda bugs me with requests to update itself in the base environment. Should I do that, then necessarily as root? Normally deb-installed files should not be overwritten...

***

A comment regarding the larger discussion here: I very much prefer a deb package over any other kind of installation method. I don't care much whether it is in Debian proper or I get it from the Anaconda repositories. The second best method in my view would be to run the Miniconda installer as root. What I really, really don't want is to have a software installation under $HOME. $HOME is for user files, not for executables.

**Comment by mestia** [comment]
>The second best method in my view would be to run the Miniconda installer as root. What I really, >really don't want is to have a software installation under $HOME. $HOME is for user files, not for >executables.

I totally disagree here, the default should be to install non-apt stuff ( such as perl/python/ruby/name it modules, conda binaries ) in $HOME. There are a number of reasons for this:

1. Users still can install all they need on the systems where they don't have root privileges. And this is one of the most important features of {ana,mini}conda.
2. Environments, it is very useful to maintain envs with different setups, I don't understand how it suppose to work under system locations.
3. Security. I don't want other tools to pollute my system. There is no issue to install conda/python/whaterver in /usr/local/ so it is available for all users.

**Comment by allefeld** [comment]
The issue of the deb package being outdated is still unresolved.

Current version of conda here 4.10.3,
current version of conda from the deb package 4.9.2.
