### ISSUE TITLE
Release source code for creating Anaconda Distribution

### ISSUE THREAD

**Issue by Delengowski** [conda/conda#12351]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Release source code creating the Anaconda Distribution installers.

### Why is this needed?

Anaconda Distribution (previously Anaconda Individual Edition) is free for download and use but not necessary open source and therefore does not fall under the FOSS category causing unnecessary work to be able to use at my work.

### What should happen?

There should exist a public repository with the necessary steps for recreating the Anaconda Distribution installer from source.

### Additional Context

To my understanding the Anaconda Distribution is created using Constructor tool. This requires an environment specification yaml file and nothing else. My work, because of procedures, requires a link to source code for recreating the executable to consider it FOSS. Right now Anaconda Distribution is only considered freeware.

**Comment by jaimergp** [comment]
I think the default `construct.yaml` for [this package](https://anaconda.org/anaconda/anaconda) should get you 90% there.

**Comment by Delengowski** [comment]
I might be misunderstanding, but repo provided by your link 404s

I.e. this link

https://github.com/ContinuumIO/anaconda

**Comment by jaimergp** [comment]
I meant having a `construct.yaml` like this:

```yaml
name: my-project
version: 2022.10
channels:
  - anaconda
specs:
  - anaconda 2022.10
```

**Comment by Delengowski** [comment]
Gotcha I understand. Sorry, right over my head.

**Comment by beeankha** [comment]
@Delengowski I'm gonna go ahead and close this issue (thanks @jaimergp for that info!); please ping me (via a comment here) to re-open it if you feel like there are any unresolved problems related to your original request.
