### ISSUE TITLE
`conda config --append` injects the default value too (e.g. `--append channels conda-forge` results in `channels: [conda-forge, defaults]`

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#12356]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

> This might be already reported but searching for `conda config default append` didn't give me any good results, so sorry in advance!

The issue is that in a fresh configuration file, a user might expect that `conda config --append channels conda-forge` only implies having a `.condarc` file like:

```yaml
channels:
  - conda-forge
```

But in reality is

```yaml
channels:
  - defaults
  - conda-forge
```

> Note how `defaults` has higher priority! We _appended_. Instead, the user is expected to know that they want to _prepend_ instead. A bit unrealistic!

I get that the default value was _always_ `defaults`, and now we are adding one more. However, `conda config --set channels conda-forge` is not supported because, confusingly,  `--set` is only for "primitives" (aka scalars, aka anything that is not a list or dict), but `channels` expects a list. There's no obvious way to set the default channels to `conda-forge` (or anything else) in a single command. For an example, look at the [required acrobatics to do so in the conda-forge based CI](https://github.com/conda/conda/pull/12350/files#diff-1e27c53a97d6c9242ea92544453665b553fe9fdf63f08717dc915f80e76fd60cR1019-R1025). 

### Things I've tried

Assuming I am on a fresh Miniconda install and I want to configure it to use for `conda-forge`, I need this:

```shell
$ conda config --append channels conda-forge
$ conda config --remove channels defaults  # why do I need this!
```

Instead I wish we could do something like this:

```shell
$ conda config --set channels conda-forge
# or if we get strict: conda config --set channels '[conda-forge]'
```

But having the default value injected can be surprising and lead to errors like:

- https://github.com/conda-incubator/setup-miniconda/issues/207

### Conda Info

```shell
conda info

     active environment : base
    active env location : /Users/jrodriguez/.local/anaconda
            shell level : 1
       user config file : /Users/jrodriguez/.condarc
 populated config files : /Users/jrodriguez/.local/anaconda/.condarc
                          /Users/jrodriguez/.condarc
          conda version : 22.11.1
    conda-build version : 3.23.3
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=arm64
                          __osx=11.2.3=0
                          __unix=0=0
       base environment : /Users/jrodriguez/.local/anaconda  (writable)
      conda av data dir : /Users/jrodriguez/.local/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jrodriguez/.local/anaconda/pkgs
                          /Users/jrodriguez/.conda/pkgs
       envs directories : /Users/jrodriguez/.local/anaconda/envs
                          /Users/jrodriguez/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.15 Darwin/20.3.0 OSX/11.2.3 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.1.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

**Comment by jaimergp** [comment]
Still an issue.

**Comment by jakirkham** [comment]
@jezdez how should we move this forward?

Right now users are expected to follow the TOS when using the `defaults` channel

However that is hard for them to do if they are unknowingly having the `defaults` channel added to the list

It feels like this is turning into an awkward footgun with legal implications

**Comment by jaimergp** [comment]
I think if we make the default value of `channels` just an empty list `[]` as per #14178, this problem goes away.

**Comment by jezdez** [comment]
I'm not sure if setting the channels to an empty list would solve this problem fully, given that it would require explicit channels configuration instead of relying on a default. Maybe I'm misunderstanding the bigger picture here though, are you suggesting we're moving that into an installer-level feature?

In other words, the key part of this ticket is a rollout plan to make sure existing users don't end with broken conda environments where no channel is configured (since their `condarc` files are empty).

**Comment by jaimergp** [comment]
They way I see this is:

- A fresh, barebones `conda` installation (e.g. from source) doesn't have `channels` defined. Miniconda and Miniforge would provide their own `ROOT_PREFIX/condarc` file, defining `channels` as necessary.
- For existing installations, we would spend a couple releases warning about the fact that they are running on "implicit configuration". After the warning period is over, we error out and provide an informative message saying what they want to do: `conda config --append channels [autodetected channel based on which channel 'conda' was installed from]`.

**Comment by jezdez** [comment]
@jaimergp I agree with this, let's start implementing.
