### ISSUE TITLE
ISSUE_SORTING.md is missing

### ISSUE THREAD

**Issue by fyu17** [conda/conda#12367]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The issue sorting process at conda on conda's [documentation](https://docs.conda.io/projects/conda/en/stable/dev-guide/contributing.html#issue-sorting) gives 404. looks like the ISSUE_SORTING.md file is missing.

**Comment by rishabh11336** [comment]
hello @ForgottenProgramme 
I have made a pull request for issue ##12371
Pull Request  "changed link in doc to HOW_WE_USE_GITHUB.md" #12374

But for some reason CLA check is not getting passed https://github.com/conda/conda/pull/12374

![image](https://user-images.githubusercontent.com/67859818/220160202-5fe8ed27-4c58-4295-9769-56c917174f3f.png)
I have signed already CLA
Kindly review it

**Comment by rishabh11336** [comment]
@ForgottenProgramme Thank you for replying 
Kindly check this out [ Made changes as suggested by Issue #12055 #4782 ](https://github.com/conda/conda-build/pull/4782)
and guide me, Is there anything more I need to do?
For Issue [ Errors in package spec documentation #12055 ](https://github.com/conda/conda/issues/12055)
