### ISSUE TITLE
Conda does not install largest version of importlib_metadata from conda-forge

### ISSUE THREAD

**Issue by rly** [conda/conda#12390]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

On both a linux machine using conda with python==3.7 and on a github actions linux runner using the [conda-incubator/setup-miniconda github action](https://github.com/conda-incubator/setup-miniconda/) with python==3.7, and channels set to conda-forge, `conda install importlib_metadata` installs `importlib_metadata==1.7` from conda-forge (see [github action log](https://github.com/rly/actions-scratch/actions/runs/4245285143/jobs/7380587823)). However, `importlib_metadata==4.11.4` is available from conda-forge. In fact, I can even run `conda install "importlib_metadata==4.11.4"` and the correct version is installed.

It might have to do with the fact that `importlib_metadata` has an underscore in its name and there is some special processing around that. `importlib_metadata` with the underscore requires `importlib-metadata` with the hyphen. `conda install importlib-metadata` installs `importlib-metadata==4.11.4` just fine. And I haven't seen this issue with any other package.

I've documented those tests plus a few more here: https://github.com/rly/actions-scratch/pull/3

This comes up when one package (e.g., `tox`) has dependencies that require both `importlib_metadata` and `importlib-metadata`. Somehow, different versions of the packages get installed, resulting in incompatibilities ([see failure log](https://github.com/rly/actions-scratch/actions/runs/4245625764/jobs/7381387794) where `importlib-metadata==4.11.4` and `importlib_metadata==1.5.0` are installed).

I can work around this issue easily, so it is not pressing to resolve, but it seemed like a strange bug worth reporting.

### Conda Info

```shell
active environment : test
    active env location : /usr/share/miniconda/envs/test
            shell level : 2
       user config file : /home/runner/.condarc
 populated config files : /home/runner/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/5.15.0-1033-azure ubuntu/22.04.1 glibc/2.35
                UID:GID : 1001:123
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/runner/.condarc <==
auto_update_conda: False
auto_activate_base: True
notify_outdated_conda: False
changeps1: False
pkgs_dirs:
  - /home/runner/conda_pkgs_dir
channels:
  - conda-forge
  - defaults
always_yes: True
```

### Conda list

```shell
# packages in environment at /usr/share/miniconda/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
importlib-metadata        1.7.0              pyhd8ed1ab_1    conda-forge
importlib_metadata        1.7.0                hd8ed1ab_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.14.0             pyhd8ed1ab_0    conda-forge
```

**Comment by travishathaway** [comment]
Hi @rly,

Thanks for filing this issue. I wanted to add a little more details for those in the future who may want to debug.

To recreate the problem you found, you can run the following command:

```bash
$ conda create -n test -c conda-forge python=3.7 tox

# ... snip, snip ✂️ 

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2022.12.7-h033912b_0
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
  distlib            conda-forge/noarch::distlib-0.3.6-pyhd8ed1ab_0
  filelock           conda-forge/noarch::filelock-3.9.0-pyhd8ed1ab_0
  importlib-metadata conda-forge/osx-64::importlib-metadata-4.11.4-py37hf985489_0  # Here is the problem
  importlib_metadata conda-forge/osx-64::importlib_metadata-1.5.0-py37_0           # These two do not match
  libcxx             conda-forge/osx-64::libcxx-15.0.7-h71dddab_0
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libsqlite          conda-forge/osx-64::libsqlite-3.40.0-ha978bb4_0
```

Furthermore, as you stated in the linked issue the `libmamba` solver does not experience this problem.

Here's how to install the lib-mamba solver for conda and test this out:

```bash
$ conda install -y conda-libmamba-solver
$ conda config --set solver libmamba
$ conda create -n derpy -c conda-forge python=3.7 tox

# ... snip, snip ✂️ 

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/linux-aarch64::ca-certificates-2022.12.7-h4fd8a4c_0
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
  distlib            conda-forge/noarch::distlib-0.3.6-pyhd8ed1ab_0
  filelock           conda-forge/noarch::filelock-3.9.0-pyhd8ed1ab_0
  importlib-metadata conda-forge/linux-aarch64::importlib-metadata-4.11.4-py37hd9ded2f_0
  importlib_metadata conda-forge/noarch::importlib_metadata-4.11.4-hd8ed1ab_0
  libffi             conda-forge/linux-aarch64::libffi-3.4.2-h3557bc0_5
```

Above, you can see that thees versions do indeed match; therefore, I would recommend installing the `libmamba` solver as one possible work around.

Thanks again for filing this issue as it highlights some interesting differences in the behavior of these two dependency solvers.

**Comment by travishathaway** [comment]
Hi @rly,

I wish I had an answer for why the `current_repodata.json` file doesn't work as expected for conda-forge, but I do not.

One thing the conda maintainers are currently working on is an experimental file format call JLAP for conda's `repodata.json`. In future versions of conda, this will essentially make `current_repodata.json` obsolete as this file format solves the problem of having to download a large files every time the cache expires.

You can read more about it here:

- https://conda.org/blog/2023-05-05-how-we-reduced-the-conda-index-fetch-bandwidth

This is currently available as an experimental feature (see the article for more information about how to turn in on 😄).

**Comment by rly** [comment]
Thanks @travishathaway ! Good to know that this problem should be resolved eventually once `current_repodata.json` is effectively replaced with the JLAP-based method.
