### ISSUE TITLE
Auto-generate cheatsheets

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#12397]
### What happened?

The most recent cheatsheet is for version 4.14.0, which is quite out of date.

For example, it includes references to `conda env` which is a deprecated subcommand.

https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html

**Comment by kenodegard** [comment]
Thanks for raising this! Our cheat sheets are still manually generated, so they tend only to get updated when there's a significant change. We aspire to automate the cheatsheet generation to avoid this issue. This is a great place to start that discussion.

Regarding `conda env`, while there are ongoing [discussions](https://github.com/conda/conda/issues/11633) and efforts to combine `conda_env` with `conda`, the subcommand has not been deprecated yet and certain functionality is still only possible via `conda env`.

**Comment by corneliusroemer** [comment]
Thanks @kenodegard - my understanding of `legacy` was essentially `deprecated` which apparently it is not, so thanks for educating me!

**Comment by whoisvishesh** [comment]
Hey, @corneliusroemer this issue is still open? If yes, please help me to understand what is needed here. 
I am making my hands dirty by playing around and contributing my bit to the same. 

Looking forward to hearing from you on this bit.
