### ISSUE TITLE
To include conda-libmamba-solver in the default installation

### ISSUE THREAD

**Issue by marceloandrioni** [conda/conda#12409]
### What is the idea?

To include the conda-libmamba-solver package in the Anaconda Installers (win/linux/osx).

### Why is this needed?

The [addition of libmamba](https://www.anaconda.com/blog/conda-is-fast-now) to the repository was a great help. But the need to install it the first time using the "classical conda solver" can still take a long time. To bypass this problem, conda-libmamba-solver could come standard with the rest of the "popular" packages (e.g.: numpy, pandas, etc) in the Anaconda Installer.

### What should happen?

The Anaconda Installer could ask during the installation which solver the user wished to use: the classical one or conda-libmamba-solver. In case the user selected the classical one, a message could be shown instructing the user how to activate libmamba later on:

`conda config --set solver libmamba`

This would be similar to what is already done when requesting user input about adding the startup script to .bashrc.

Thank you.

**Comment by kenodegard** [comment]
This is in the works; however, this is out of scope for the conda project itself, so I'll close this issue.

Please feel free to raise this on the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) to discuss it more with the Anaconda Distribution folks.
