### ISSUE TITLE
Make `strict` be the default `channel_priority`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12400]
### What is the idea?

Currently, the default `channel_priority` is flexible which can cause issues when mixing complex channels (e.g. defaults and conda-forge). A potential resolution would be to change the default to `strict` instead.

**Comment by isuruf** [comment]
cc @beeankha.

This was supposed to be the default in 5.0, but it was missed.

**Comment by dholth** [comment]
I've had many dependency problems that are resolved only by turning strict off. Is it more likely to succeed with the new solver? I don't think strict is a good default.

**Comment by kenodegard** [comment]
@isuruf FYI, conda 5.0 has not happened and will not happen as previously envisioned, this was part of the reasoning for the switch to CalVer, see https://github.com/conda-incubator/ceps/blob/main/cep-8.md#backwards-compatibility for more details

**Comment by isuruf** [comment]
> I've had many dependency problems that are resolved only by turning strict off. 

Any concrete issues?
