### ISSUE TITLE
Make `conda info -v` work

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda/conda#12420]
### What is the idea?

There is no `conda info -v` command to display a detailed/verbose `conda info` report. It is `conda info --all` instead, which is a bit unintuitive. The most commonly used flag for displaying detailed versions of the regular command is `-v`. 

### Why is this needed?

conda CLI should support the standard CLI commands

### What should happen?

`conda info -v` should work. 
`conda info --all` should also continue to work, as users/developers might have gotten used to that command.

### Additional Context

See [comment](https://github.com/conda/conda/issues/12259#issuecomment-1430309637).

**Comment by kenodegard** [comment]
So the plan here is to make `-v`/`--verbose` mean the same thing as `-a`/`--all`?
