### ISSUE TITLE
Mark `conda/plan.py` for Deprecation (and do related refactoring work as necessary)

### ISSUE THREAD

**Issue by beeankha** [conda/conda#12421]
### What is the idea?

There is [a `TODO` comment](https://github.com/conda/conda/blob/main/conda/plan.py#L42) marking the `conda/plan.py` module for deprecation that got added in the pull request titled ["separate conda package metadata under new root-level key in repodata (#8639)"](https://github.com/conda/conda/pull/8639).

Deprecating/removing that module (and [related test file](https://github.com/conda/conda/blob/main/tests/test_plan.py)) entirely is not a straightforward task, as there are references to the contents of `conda/plan.py` in files such as [`conda/misc.py`](https://github.com/conda/conda/blob/main/conda/misc.py) and [`conda/exports.py`](https://github.com/conda/conda/blob/main/conda/exports.py). This deprecation will require:

```[tasklist]
- [x] Investigations into which files contain references to any functions/methods in [`conda/plan.py`](https://github.com/conda/conda/blob/main/conda/plan.py)
- [x] Figuring out what sort of refactoring efforts are required as a result of those references
```

**Comment by jezdez** [comment]
@beeankha Is there anything we need to do about this ticket?

**Comment by beeankha** [comment]
@jezdez nothing in particular is blocking this work afaik, we just need to get started on it; if it's more complicated than anticipated we can move it to the 24.7.x milestone. I'll do at least the preliminary research (task 1) this week!

**Comment by beeankha** [comment]
Discoveries for Step 1 of this task:

* **[`print_dists()`](https://github.com/conda/conda/blob/main/conda/plan.py#L45):** 
  * only used within `conda/plan.py`, in the `display_actions()` function

* **[`display_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L56):**
  * used in `conda/exports.py` in [`display_actions()`](https://github.com/conda/conda/blob/main/conda/exports.py#L171) (it's [imported as `_display_actions` with a leading underscore added](https://github.com/conda/conda/blob/main/conda/exports.py#L67)
  * found in tests in `tests/test_plan.py`, specifically [`test_display_actions_0()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L70), [`test_display_actions_show_channel_urls()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L307), [`test_display_actions_link_type()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L617), [`test_display_actions_features()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L950)

* **[`add_unlink()`](https://github.com/conda/conda/blob/main/conda/plan.py#L267):**
  * used in `tests/test_plan.py` in [`test_simply_adds_unlink_on_non_windows()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L55) and [`test_adds_to_existing_actions()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L63)

* **[`add_defaults_to_specs()`](https://github.com/conda/conda/blob/main/conda/plan.py#L277):**
  * no references/usage found

* **[`_get_best_prec_match()`](https://github.com/conda/conda/blob/main/conda/plan.py#L281):**
  * used in `conda/plan.py` in [`revert_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L296)
  * also found in `conda/misc.py` in [`clone_env()`](https://github.com/conda/conda/blob/main/conda/misc.py#L221)

* **[`revert_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L296):**
  * used internally in `conda/plan.py` in [`main` execution code](https://github.com/conda/conda/blob/main/conda/plan.py#L638)
  * also found in `conda/install.py` in [`install()`](https://github.com/conda/conda/blob/main/conda/cli/install.py#L135) function

* **[`execute_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L339):**
  * imported but unused in `conda/exports.py` with a [`#noqa: F401 comment`](https://github.com/conda/conda/blob/main/conda/exports.py#L69)

* **[`_plan_from_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L344):**
  * only used in `conda/plan.py` module in [`execute_actions()` function](https://github.com/conda/conda/blob/main/conda/plan.py#L339) directly above

* **[`_inject_UNLINKLINKTRANSACTION()`](https://github.com/conda/conda/blob/main/conda/plan.py#L393):**
  * only used internally in `conda/plan.py` module in [`_plan_from_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L344) helper method

* **[`_handle_menuinst()`](https://github.com/conda/conda/blob/main/conda/plan.py#L439):**
  * only used internally in `conda/plan.py` module in [`_inject_UNLINKLINKTRANSACTION()`](https://github.com/conda/conda/blob/main/conda/plan.py#L393) helper method directly above


* **[`install_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L469):**
  * imported but unused in `conda/exports.py` with a [`#noqa: F401` comment](https://github.com/conda/conda/blob/main/conda/exports.py#L72)

* **[`get_blank_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L534):**
  * only used internally in the [`install_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L469) function, which is [imported but unused in `conda/exports.py`](https://github.com/conda/conda/blob/main/conda/exports.py#L72)

* **[`execute_plan()`](location):**
  * imported but unused in `conda/exports.py` with a [`#noqa: F401` comment](https://github.com/conda/conda/blob/main/conda/exports.py#L71)
  * also found in `tests/test_plan.py` in [`test_execute_plan()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L1302)

* **[`execute_instructions()`](execute_instructions):**
  * used internally in `conda/plan.py` module in [`execute_actions()`](https://github.com/conda/conda/blob/main/conda/plan.py#L339) and [`execute_plan()`](https://github.com/conda/conda/blob/main/conda/plan.py#L567) functions
  * found in `tests/test_instructions.py` in [`test_simple_instruction()`](https://github.com/conda/conda/blob/main/tests/test_instructions.py#L29) and [`test_state()`](https://github.com/conda/conda/blob/main/tests/test_instructions.py#L46)
  * imported but unused in `conda/exports.py` with a [`#noqa: F401` comment](https://github.com/conda/conda/blob/main/conda/exports.py#L70)

* **[`_update_old_plan()`](https://github.com/conda/conda/blob/main/conda/plan.py#L615):**
  * found internally in `conda/plan.py` module in `execute_plan()` which is imported but unused in `conda/exports.py` with a [`#noqa: F401` comment](https://github.com/conda/conda/blob/main/conda/exports.py#L71)
  * also found in `tests/test_plan.py` in [`test_update_old_plan()`](https://github.com/conda/conda/blob/main/tests/test_plan.py#L1291), imported as [`update_old_plan` (without the leading underscore)](https://github.com/conda/conda/blob/main/tests/test_plan.py#L1291)
