### ISSUE TITLE
Local tests don't use proper durations file

### ISSUE THREAD

**Issue by dholth** [conda/conda#12433]
### What happened?

Tests are using `${OS}` set in github actions to choose an appropriate test-durations filename, or just ".json" if the OS is not set. Instead, they should either use a generic `durations.json` or update the OS-specific one when running locally. Or we might choose to gitignore or not store the durations at all to keep local diffs clean.

**Comment by kenodegard** [comment]
IMO we should ignore test duration files. They should only be included if we are explicitly trying to update them.

**Comment by dholth** [comment]
They might need to be *read* any time we run the tests with splits which we usually don't do locally; they should be written at least when GH CI runs, but it's not useful if they show up in git diffs when you're trying to do something else.

**Comment by amrullahfarook** [comment]
Hi there! I am new to OS contributions, can I take this?

**Comment by dholth** [comment]
Yes. This is related to the durations files which are used to split tests into multiple parallel runners. We might not bother with any of that locally and just run the tests serially, or, we might want to split them to better mimic what happens in CI. What would you like to do with them?

**Comment by amrullahfarook** [comment]
Hey, sorry but I'm a bit confused. Based on my understanding from the initial discussions in this thread, it was necessary to generate duration files during the execution of the CI script. Simultaneously, adding these files to gitignore so that we maintain clean local git diffs. Is that still the issue at hand?
