### ISSUE TITLE
Why use two different build scripts: build.sh and bld.bat?

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1243]
I've been trying to port a few of my projects to be built and distributed with conda and binstar, and I am confused as to why [conda supports](http://conda.pydata.org/docs/build.html) two different build scripts: `build.sh` and `bld.bat`. I understand that `build.sh` is intended to be executed on posix systems and `bld.bat` on windows, but why not simply have a single python build script (e.g. `build.py`)? If conda is being  used to build a package, python is available. Additionally, a single `build.py` seems like it would simplify things for the package maintainer -- they would only have to maintain a single build script.

**Comment by srossross** [comment]
I like this idea.  A lot of the time the build script is the same for posix and windows.  Also, this can be done in a completely backwards compatible way.

**Comment by asmeurer** [comment]
Because it's a lot easier to write build scripts in bash/batch than in Python. Adding support for build.py would be fine, but we need to continue to support and recommend build.sh/bld.bat.

**Comment by jrsmith3** [comment]
It seems like you could use the [`build/script`](https://github.com/conda/conda/pull/509) field in `meta.yaml` to specify an arbitrary build script file. In this way the user could use bash, python, batch, or whatever they want. If the field points to a file, execute the file. Otherwise, execute the command specified by the field.

**Comment by asmeurer** [comment]
Most nontrivial recipes require different build scripts for Unix and Windows. Typically the only instance where they are the same is if they are just `python setup.py install` (and even then if you use the PYTHON environment variable, the syntax is different).

**Comment by kalefranz** [comment]
Add `posix` as a build requirement on windows, and then in `bld.bat` put only the two lines

```
bash %RECIPE_DIR%/build.sh
if errorlevel 1 exit 1
```

Guessing that should work.  Might have to pass `%RECIPE_DIR%/build.sh` through `cygpath`.

**Comment by kalefranz** [comment]
Of course, then you have to put correct conditionals and branching in your `build.sh` file to handle Windows particulars.

**Comment by mingwandroid** [comment]
`bash -lc`, and you need to convert a few vars from Windows to MSYS2-form (MSYS2 converts the other way automatically).

I'd support automating the conversion if `build/script:` is a bash script. You probably also want to use the exact `cygpath.exe` in the build prefix for people who prefer to use `Cygwin`.
