### ISSUE TITLE
CI for conda-forge is (re)adding defaults in unit tests

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#12447]
### What happened?

Observed in https://github.com/conda/conda/pull/12438, probably an oversight.

Unit tests for conda-forge are reinstalling many packages from defaults, causing a slow setup and defeating the purpose of that matrix entry. See https://github.com/conda/conda/actions/runs/4328144068/jobs/7557536999#step:3:156

This is coming from this line https://github.com/conda/conda/blob/2162224b68367e62cabb40fea71372b49d4f6031/dev/linux/unit.sh#L12

**Comment by kenodegard** [comment]
@jaimergp ah yeah, definitely an oversight

**Comment by jezdez** [comment]
Good catch!
