### ISSUE TITLE
`devenv` fails to update if a new dependency is added

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12467]
### What happened?

```
(devenv-3.10-c) dholth@Daniels-MBP repodata-hotfixes % cd ~/prog/conda
(devenv-3.10-c) dholth@Daniels-MBP conda % . dev/start -p 3.10
Deactivating 1 environment(s)...
Updating devenv-3.10-c...
Traceback (most recent call last):
  File "/Users/dholth/prog/conda/devenv/Darwin/arm64/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/Users/dholth/prog/conda/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "/Users/dholth/prog/conda/conda/deprecations.py", line 9, in <module>
    from packaging.version import parse, Version
ModuleNotFoundError: No module named 'packaging'
Error: failed to update development environment
```

**Comment by kenodegard** [comment]
The issue is that our `dev/start` script modifies the `PYTHONPATH` to include the source directory. This means that when we try to run the update commands on the base environment, instead of using the stable conda installation, it imports and uses the source code.

cc @dholth

**Comment by kenodegard** [comment]
There are actually 2+ conda environments generated by the `dev/start` script:

```
./devenv/${OS}/${ARCH}/      ← this is the stable miniconda base env
├── bin/conda
├── envs/
│   ├── devenv-${PYTHON}-c/  ← this is the devenv env that gets activated as base when you run ./dev/start
│   │   ├── bin/conda
│   │   └── ...
│   └── ...
└── ...
```

There's the stable _miniconda_ base environment and the devenv environment (e.g., `devenv-3.8-c`) that's created with conda and the works using the Python version specified via `. dev/start -p PYTHON`. When the `dev/start` script is updating it first does a `conda update --all`:

https://github.com/conda/conda/blob/dcf517e6cc9eee9ebf68a364556040f0dfc92267/dev/start#L235-L238

After the stable miniconda base environment is updated we then update the devenv:

https://github.com/conda/conda/blob/dcf517e6cc9eee9ebf68a364556040f0dfc92267/dev/start#L240-L250

---

The problem outlined here and fixed in https://github.com/conda/conda/pull/12468 is that we also set the `PYTHONPATH` so Python will import from our source code:

https://github.com/conda/conda/blob/dcf517e6cc9eee9ebf68a364556040f0dfc92267/dev/start#L280

This meant that the first update would magically start failing (even though its the stable conda environment) because it was actually running the source code (which was not supposed to happen).

**Comment by dholth** [comment]
So maybe I had a working conda environment that had been depending on `packaging` for some weeks, then I switched to another branch, updated it again, switched back, and experienced the problem again?

**Comment by kenodegard** [comment]
No, your devenv always had `packaging`, it never lost it.

Here's a rundown of how to replicate the issue (at no point do I change the working branch and these commands are run sequentially):

```bash
$ echo $PYTHONPATH

$ . dev/start -u
Updating devenv-3.8-c...
Initializing shell integration...
Activating devenv-3.8-c...

(base) $ echo $PYTHONPATH
/Users/kodegard/dev/conda:

(base) $ . dev/start -u
Deactivating 1 environment(s)...
Updating devenv-3.8-c...
Traceback (most recent call last):
  File "/Users/kodegard/.conda/devenv/Darwin/x86_64/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/Users/kodegard/dev/conda/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "/Users/kodegard/dev/conda/conda/deprecations.py", line 9, in <module>
    from packaging.version import parse, Version
ModuleNotFoundError: No module named 'packaging'
Error: failed to update development environment
```

The first time we run `dev/start`, everything appears to work correctly, but once we run the update a second time, it appears to fail. The only meaningful change is the presence of `PYTHONPATH`, which, if we unset it before running the second `dev/start` this error does not occur:

```bash
$ echo $PYTHONPATH

$ . dev/start -u
Updating devenv-3.8-c...
Initializing shell integration...
Activating devenv-3.8-c...

(base) $ unset PYTHONPATH

(base) $ . dev/start -u
Deactivating 1 environment(s)...
Updating devenv-3.8-c...
Initializing shell integration...
Activating devenv-3.8-c...
```
