### ISSUE TITLE
Review and handle Python 2 related test cases

### ISSUE THREAD

**Issue by jezdez** [conda/conda#12471]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While working on #12470, @travishathaway wrote:

> @jezdez, it appears there are even more references to old Python. Here's just a few I found:

> - https://github.com/conda/conda/blob/9c48e10bad9d68a98ef2a11ced4a1320fa741a3d/tests/test_create.py#L831
> - https://github.com/conda/conda/blob/9c48e10bad9d68a98ef2a11ced4a1320fa741a3d/tests/test_create.py#L838
> - https://github.com/conda/conda/blob/9c48e10bad9d68a98ef2a11ced4a1320fa741a3d/tests/test_create.py#L431

Let's review those tests and decide what to do about them (:this-is-fine:)

**Comment by kenodegard** [comment]
Closing as inactionable.

While `conda` depends on newer versions of Python that shouldn't impact its ability to install older versions of Python into an environment. So these tests referencing older versions of Python are still valid as they're referencing Python as a package, not as a dependency.
