### ISSUE TITLE
ENH(remove): Add option to keep the (empty) environment despite removal of all packages

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#12485]
### What is the idea?

Conda environments are more than a list of packages. Metadata like channel priority, subdir etc. are also a crucial part.

However, the CLI seems to assume that empty environments serve no purpose - this is implicit in the behaviour of `conda remove`: when you remove all packages, it deletes the environment: `conda remove --all -n ENV_NAME` not just removes all packages, it _also_ removes the environment and its metadata.

Also, when you remove all packages without explicitly passing `--all` the environment itself _with_ the metadata is removed, despite this not necessarily being what the user wants. This has been discussed before in https://github.com/conda/conda/issues/10467

I would like to suggest a CLI option for `conda remove` that tells `conda remove` _not_ to delete the environment even if all packages are uninstalled.

This is consistent with environment creation: `conda create` can create _empty_ environments, so the existence of empty environments _is_ valid. Hence there's no reason why one shouldn't go back to empty environments from a full environment with remove.

### What should happen?

Ideally, the behaviour of `conda remove` would be changed to not delete the environment if all packages are gone. But since this is quite a deep change, it may be easier to add a new option that changes that default behaviour: `conda remove --all --keep-env -n ENV_NAME` could be how one tells remove to not remove the environment.

This should also work for `conda remove --keep-env scipy` in cases where remove would remove all packages without the shortcut `--all` being passed.

### Additional Context

See this StackOverflow question for further context: https://stackoverflow.com/questions/75731916/how-to-remove-all-packages-from-a-conda-environment-but-not-keep-environment-i

### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

**Comment by travishathaway** [comment]
Hi @corneliusroemer,

I think this sounds like a very reasonable feature request. That's why I'm going to apply the https://github.com/conda/conda/labels/good-first-issue and add it to our backlog.

We can't promise when something like this will be finished, but we are always more than happy to consider and review new contributions in the form of a pull request. Please keep an eye on this issue for all future developments.

**Comment by pravincoder** [comment]
I am interested to work on it .😅
@corneliusroemer  I understood your idea and will follow it !
