### ISSUE TITLE
Powershell init error: Invoke-Expression The string is missing the terminator: ".

### ISSUE THREAD

**Issue by jayagami** [conda/conda#12501]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After clean intall lastest miniconda on latest Windows11.

```
conda init powershell
```
it gives `Invoke-Expression: The string is missing the terminator: ". `  when open pwsh7.

```
> conda activate base
Invoke-Expression: The string is missing the terminator: ".
```

and for windows powershell

```

Invoke-Expression : At line:9 char:62
+ $Env:CONDA_PYTHON_EXE = "C:\Users\yagami\miniconda3\python.exe"
+                                                              ~
The string is missing the terminator: ".
At C:\Users\yagami\miniconda3\shell\condabin\Conda.psm1:76 char:9
+         Invoke-Expression -Command $activateCommand;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Microsoft.PowerShell.Commands.InvokeExpressionCommand

Invoke-Expression : At line:9 char:62
+ $Env:CONDA_PYTHON_EXE = "C:\Users\yagami\miniconda3\python.exe"
+                                                              ~
The string is missing the terminator: ".
At C:\Users\yagami\miniconda3\shell\condabin\Conda.psm1:76 char:9
+         Invoke-Expression -Command $activateCommand;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Microsoft.PowerShell.Commands.InvokeExpressionCommand

```

### Conda Info

```shell
> conda info

(base) PS C:\Users\yagami> conda info

     active environment : base
    active env location : C:\Users\yagami\miniconda3
            shell level : 1
       user config file : C:\Users\yagami\.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\yagami\miniconda3  (writable)
      conda av data dir : C:\Users\yagami\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\yagami\miniconda3\pkgs
                          C:\Users\yagami\.conda\pkgs
                          C:\Users\yagami\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\yagami\miniconda3\envs
                          C:\Users\yagami\.conda\envs
                          C:\Users\yagami\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by travishathaway** [comment]
Hi @jayagami,

Can you please provide us with the output of `conda list --channel-urls`?

Thanks.

**Comment by jayagami** [comment]
> conda list --channel-urls

```
(base) C:\Users\yagami>conda list --channel-urls
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: --channel-urls

```

**Comment by jaimergp** [comment]
I think @travishathaway meant `conda list --show-channel-urls`.

**Comment by paulxu** [comment]
Pretty much the same issue, but I launched it from Navigator > Powershell Prompt. 

Clear install of Anaconda3-2023.03-1-Windows-x86_64.exe on Windows 10.

"conda info" output

     active environment : base
    active env location : C:\Users\Fn Ln\anaconda3
       user config file : C:\Users\Fn Ln\.condarc
 populated config files : C:\Users\Fn Ln\.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\Fn Ln\anaconda3  (writable)
      conda av data dir : C:\Users\Fn Ln\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Fn Ln\anaconda3\pkgs
                          C:\Users\Fn Ln\.conda\pkgs
                          C:\Users\Fn Ln\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Fn Ln\anaconda3\envs
                          C:\Users\Fn Ln\.conda\envs
                          C:\Users\Fn Ln\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False

I added "-Verbose" to the following line in function Enter-CondaEnvironment in Conda.psm1
        Write-Verbose "[conda shell.powershell activate $Name]`n$activateCommand" -Verbose;

And got the following output:

VERBOSE: [conda shell.powershell activate base]
$Env:PATH ="" <- details removed for my personal full search path
$Env:CONDA_PREFIX = "C:\Users\Fn Ln\anaconda3"
$Env:CONDA_SHLVL = "1"
$Env:CONDA_DEFAULT_ENV = "base"
$Env:CONDA_PROMPT_MODIFIER = "(base) "
$Env:CONDA_EXE = "C:\Users\Fn Ln\anaconda3\Scripts\conda.exe"
$Env:_CE_M = ""
$Env:_CE_CONDA = ""
$Env:CONDA_PYTHON_EXE = "C:\Users\Fn Ln\anaconda3\python.exe"

So far all looks good at this point.

#### workaround

If I manually set 
$Env:CONDA_EXE = "C:\Users\Fn Ln\anaconda3\Scripts\conda.exe"

Then run "conda shell.powershell activate base" with success. 

conda info --env
# conda environments:
#
base                  *  C:\Users\Fn Ln\anaconda3

#### end of workaround

Lazy to read into the source code of conda/activate.py. Please fix it. 

Thanks.

**Comment by paulxu** [comment]
A recent update breaks my fix again. I'd better update here. So I can come back to check my fix next time. 

C:\Users\<username>\anaconda3\shell\condabin\Conda.psm1

## the cause is the space in my username
--- origin
+++ changed
@@ -76 +76 @@
-        Invoke-Expression -Command $activateCommand;
+        Invoke-Expression -Command '$activateCommand';
