### ISSUE TITLE
UrlsData.get_url fails with packages ending with .conda

### ISSUE THREAD

**Issue by tl-hbk** [conda/conda#12516]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following function in `UrlsData` does not work correctly with packages with the `.conda` extension because of line 515

https://github.com/conda/conda/blob/b482e51f6d24343334da862b8d940b5f1faa9ac4/conda/core/package_cache_data.py#L507-L517

Should be the following instead 

`if not package_path.endswith(CONDA_PACKAGE_EXTENSIONS):`

otherwise `package_path` for `.conda` packages end up being `<package-name>.conda.tar.bz2` which will not be found in `self._urls_data`

### Additional Context

This issue occurs in the edge case of doing an install/create with an `@EXPLICIT` spec.txt and the package cache contains a package that isn't extracted yet but is in `urls.txt`.  After extracting the already downloaded package, it redownloads and extracts again because `get_url` returns nothing.

**Comment by travishathaway** [comment]
Hi @tl-hbk,

Thanks for submitting this issue. Would you be interested in submitting a pull request yourself to address this? If so, we would appreciate you adding test coverage to cover the error case you mentioned.

Otherwise, we will leave this issue open for now. Anymore details about exactly what causes this error case would be greatly appreciated.

**Comment by tl-hbk** [comment]
Yeah this is something I can create a pull request for.  Just need to get approval to sign the CLA from my employer.

**Comment by tl-hbk** [comment]
@travishathaway hey Travis I've gone ahead and created a pull request with the fix.

**Comment by travishathaway** [comment]
The following pull request has been merged: https://github.com/conda/conda/pull/12604

Closing this issue.
