### ISSUE TITLE
conda installed package lacks installed files metadata required by pip and confuses users

### ISSUE THREAD

**Issue by ogrisel** [conda/conda#1251]
`pip show --files numpy` fails to return the list of installed files of this package when it was installed with conda. The list of installed files of a python package is expected to be found in the `site-packages/package_name-version.egg-info/installed-files.txt` entry of packages installed by setuptools or better in the [officially documented](https://www.python.org/dev/peps/pep-0376/#one-dist-info-directory-per-installed-distribution) `packages/package_name-version.dist-info/RECORD`, for instance when a package is [installed by pip from wheel](https://www.python.org/dev/peps/pep-0427/#the-dist-info-directory).

This is problematic because this prevents pip from correctly uninstalling or upgrading a package previously installed by conda.

I know that packages installed by conda are supposed to be upgraded or removed by conda instead of pip but many users are not aware of that and the resulting error messages caused by a partially upgraded packages are very confusing, see for instance the discussion: https://github.com/scikit-learn/scikit-learn/issues/4472.

**Comment by asmeurer** [comment]
Is this file added by pip? Conda packages are typically build from a `setup.py install` install, so any files not installed with that command won't be there.

**Comment by ogrisel** [comment]
Indeed. When I run `python setup.py` install in the scikit-learn source folder I only get the `.egg-info` file, not folder. When I do `pip install .` from within the scikit-learn source folder I get the `.egg-info` folder with the `installed-files.txt` folder. So pip seems to indeed be fixing stuff under the hood to make it possible to uninstall the package properly later.

When I do `python setup.py bdist_wheel && pip install --pre -f ./dist scikit-learn` to install the generated wheel I get the `.dist-info` folder and with its `RECORD` file. So generating a wheel seems like another way to force computation of the manifest (because it's part of the wheel specification).

**Comment by ogrisel** [comment]
Apparently, it's possible to record the list of files installed by distutils with the `--record files.txt` command:

```
python setup.py install --record files.txt
```

But that does not generate the proper `.egg-info` nor `.dist-info` folders per se.

**Comment by asmeurer** [comment]
Maybe you should see if the setuptools developers will enable writing this file for setup.py installed packages.

**Comment by asmeurer** [comment]
This also is arguably a pip bug. Conda does include the metadata for pip to know that a package is installed, so pip should probably warn or prevent the user from upgrading such a package that has no installed-files.txt file. 

Anyway, we could probably workaround this in our build system, but it would be better to upstream a fix to pip and/or setuptools, as this same issue would occur for a setup.py installed package (no conda).

**Comment by ogrisel** [comment]
The fact that `python setup.py install` does not record the list of installed files by default is apparently a known limitation that prevents `pip uninstall` to work in that case:

https://pip.pypa.io/en/latest/reference/pip_uninstall.html#description

**Comment by ogrisel** [comment]
Arguably one could consider that this is limitation of pip / distutils that is unrelated to conda. Still in practice 2 users have reported issues caused by this problem the week following the release of scikit-learn 0.16.0. I guess many more users were impacted without even knowing it.

**Comment by asmeurer** [comment]
It looks like scikit-learn doesn't use setuptools when installing (I don't blame you guys). Probably we should add support for writing this file in the build system.

**Comment by ogrisel** [comment]
I think the problem is the same with numpy. scikit-learn uses the ``setup`` command from ``numpy.distutils`` to be able to build the compiled extensions in a consistent way.

I think that using the ``setup`` / ``install`` command from ``setuptools`` creates ``.egg`` folders in the ``site-packages`` which I find really ugly. I much prefer the external ``.egg-info`` or ``.dist-info`` directories with package metadata next to the python packages themselves.

**Comment by asmeurer** [comment]
Yes I know. conda build actually removes those egg directories unless they are needed (for setuptools entrypoint plugins).

**Comment by ogrisel** [comment]
I think the best solution would be to have conda generate a new-style `.dist-info` folder in case they are not created by default by `python setup.py install` which is likely to be the case in most cases. 

This might be useful (pip is using a vendored copy of it).

http://distlib.readthedocs.org/en/latest/

Or alternatively, to convert an egg into new-style dist-info metadata:

https://bitbucket.org/pypa/wheel/src/bdf053a70200c5857c250c2044a2d91da23db4a9/wheel/egg2wheel.py?at=default#cl-17

Now I understand that this can be a lot of work for little benefit for pure-conda users. Still the fact that dist-info has now been promoted has a static metadata format specifically devised to be installer / distribution agnostic makes me think that conda should try its best to generate those metadata as well for general interoperability purpose.

It's unfortunate that only the `wheel` package and tooling support it at the moment.

**Comment by ogrisel** [comment]
To mitigate the problem I opened a PR on the scikit-learn install documentation:

https://github.com/scikit-learn/scikit-learn/pull/4542

But very few users read the documentation anyway.

**Comment by cournape** [comment]
A possible solution would be for numpy.distutils generate a .dist-info folder following `PEP-376`.

In the short term, for conda, I would suggest installing numpy/scipy using the `setupegg.py` command that will product those metadata. You could reuse that `setupegg.py` in scikits learn as well.

**Comment by ogrisel** [comment]
Another possible solution would be to have the `install` command of our setup script actually call `bdist_wheel` and then `wheel install` to install the package correctly along with its `.dist-info` metadata. The problem is that `wheel install` does not supports upgrades or uninstall (not implemented in the [wheel](https://wheel.readthedocs.org/) library itself, AFAIK only pip implements such features at the moment).

**Comment by kalefranz** [comment]
I'm going to close this issue on, as it pertains to the conda tracker.  This really concerns how packages are built, and what best practices are with regard to python packages.  The conda-build issue tracker might be a good place to continue the discussion.  Another good place might be within the conda-forge community.
