### ISSUE TITLE
Failed to activate devenv-3.8-c in setting up Conda development env

### ISSUE THREAD

**Issue by pravincoder** [conda/conda#12525]
### What happened?

I am trying to set up development env for conda on window's 

My Reference :- [Development Environment, Windows cmd.exe shell](https://docs.conda.io/en/latest/contributing.html#development-environment-windows-cmd-exe-shell)

did everything as specified git is set to path ..etc

Ran the following command, on cmd.exe

`set GITHUB_USERNAME=pravincoder`

`git clone https://github.com/pravincoder/conda.git "%CONDA_PROJECT_ROOT%"`

`cd "%CONDA_PROJECT_ROOT%"`

`git remote add %GITHUB_USERNAME% https://github.com/pravincoder/conda.git`

ERROR Command :- C:\Users\WIN10\conda>`.\dev\start`

Error info:-
```
Downloading miniconda...
Installing development environment...
Creating devenv-3.8-c...
Updating devenv-3.8-c...
Initializing shell integration...
menuinst called from non-root env C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c
rm -rf C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\Lib\site-packages\conda-23.1.0-py3.8.egg-info
rm -rf C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\Lib\site-packages\conda
rm -rf C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\Lib\site-packages\conda_env
Activating devenv-3.8-c...
Traceback (most recent call last):
  File "C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
  File "C:\Users\WIN10\conda\conda\__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "C:\Users\WIN10\conda\conda\deprecations.py", line 266, in <module>
    deprecated = DeprecationHandler(__version__)
  File "C:\Users\WIN10\conda\conda\deprecations.py", line 29, in __init__
    self._version = parse(version)
  File "C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\Users\WIN10\conda\devenv\Windows\envs\devenv-3.8-c\lib\site-packages\packaging\version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
Error: failed to activate devenv-3.8-c
```

If you have any suggestion or need more info do let me know !

**Comment by travishathaway** [comment]
Hi @pravincoder,

I'm not immediate sure what your problem is, but I can provide a work around. If you install docker for windows you can get an interactive prompt by running this command from the conda repository root:

```
docker compose run interactive
```

This should drop you into to a Linux docker container where you will be able to test out the changes you make to conda.

Anyone else know what might be going on here? Could it be something awry with the `conda/.version` file?

**Comment by kenodegard** [comment]
@travishathaway I can replicate the issue if I delete my `conda/.version`, I'll look into it some more

**Comment by kenodegard** [comment]
@pravincoder you can follow @travishathaway's suggestion or if you manually generate the version file it'll work for you:

```cmd
$ echo 0.0.0 > conda\.version
$ .\dev\start.bat
```

**Comment by pravincoder** [comment]
Thank you @travishathaway , @kenodegard
