### ISSUE TITLE
Disk related issue but that's not the problem

### ISSUE THREAD

**Issue by antoniaprn** [conda/conda#12532]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello, sorry to be repetitive but I put the wrong label on my other issue. My problem is that I can't create a new env with a yaml file. 

The error that I got is this one:
`Collecting package metadata (repodata.json): done
Solving environment: - Killed`

In the docs it said that:

> This may be because your system lacks sufficient disk space or memory to complete the process.

But I have at least 100GB of disk space and a lot of memory RAM too. I can't really tell what could be.

**Comment by travishathaway** [comment]
Hi @antoniaprn,

Can you please post more information about your conda installation?

We need the outputs of the following commands to make our best attempt at debugging this:

```
conda info
```

```
conda config --show-sources
```

```
conda list --show-channel-urls
```

Also, please provide any other details you think may be important (e.g. is this running on a server or your local desktop, etc.).

Thanks ✌️
