### ISSUE TITLE
better error reporting if bzip2 is not available

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1253]
As @malev discovered, some modern OSes don't include bzip2 in their base OS image, meaning that conda won't work out of the box when it tries to `tar jxvf` any packages.  Noticing this and providing a nicer error message would be great.

```
installing: python-2.7.8-1 ...
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/opt/wakari/wakari-gateway/tmp/.functions.sh: line 686: /opt/wakari/miniconda/bin/conda: No such file or directory
```

**Comment by asmeurer** [comment]
What "modern" OS doesn't have bzip2? 

Anyway, this should be an issue in https://github.com/continuumio/anaconda. conda does not use the bzip2 command (the Anaconda/Miniconda installers do).

**Comment by malev** [comment]
We have this problem in a Digital Ocean box with CentOS

**Comment by ijstokes** [comment]
CentOS 7 base install doesn't appear to include bzip2.  Does `conda`, to uncompress packages, use an entirely Python internal bzip2 library?

**Comment by asmeurer** [comment]
Yes, conda uses the tarfile library. But I'm guessing the installer has to run this step before Python is installed.

**Comment by ilanschnell** [comment]
Exactly.  During the bootstrap process, the installer has to untar (with the -j option (bz2)) the conda package of Python.

**Comment by Buzut** [comment]
I had this issue too in an Online.net bow with Ubuntu 16.04LTS

**Comment by mingwandroid** [comment]
I want to remove the need for any external programs (except a POSIX compliant shell).

**Comment by justlurking** [comment]
@mingwandroid Yes please. While you're on the subject of non-POSIX shell support, it would be wonderful if the next conda 4.4.0 release candidate were to fix the (previously working) support for Fish shell.
