### ISSUE TITLE
Move conda to src/ to avoid unwanted build-time imports

### ISSUE THREAD

**Issue by dholth** [conda/conda#12542]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

We need to move conda to `src/` so that system conda, and not development conda, is used to build conda. Unfortunately this isn't great for PR's but git might be better at guessing renames than it used to be. Bundle with black reformat?

### Why is this needed?

When conda is being built, conda-build may import symbols from the build version of conda instead of the system version. This can cause failures or unexpected behavior, making it more difficult to control compatibility between versions of conda and conda-build. It is especially problematic when introducing new dependencies.

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-feedstock/pull/204#issuecomment-1488257409 for an alternative implementation at the recipe level.

**Comment by dholth** [comment]
I love that idea, and would prefer it to a src layout which would require us to update all our dev scripts.
