### ISSUE TITLE
Issue installing Anaconda3-2023.03 - Failed to link extracted packages

### ISSUE THREAD

**Issue by neverax** [conda/conda#12552]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm trying to install the newest anaconda version on Windows 10 and there is an error that i put the screenshot of. I also put in thse from the installer. The weird thing is that when I tried installing the previous version, it was installed without any issues, however cmd didn't recognize either conda nor python and I couldn't get it to work. I have tried putting in the PATH manually, several times in different ways - none of which had worked. If you need any additional info feel free to request it, im fairly new to this so I'm not sure what information I should include.

When installing the system version not the user one it was working but I've had some other issues with it
Version I'm trying to install: Anaconda3-2023.03-Windows-x86_64
Version that I had installed successfully: Anaconda3-2022.10-Windows-x86_64

### Additional Context

```
Output folder: C:\Users\never\anaconda3\pkgs
Extract: env.txt
Output folder: C:\Users\never\anaconda3\conda-meta
Extract: history

Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working... WARNING conda.core.envs_manager:register_env(49): Unable to register environment. Path not writable or missing.
  environment location: C:\Users\never\anaconda3
  registry file: C:\Users\never\.conda\environments.txt


    Windows 64-bit packages of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py


done
ERROR conda.core.link:_execute(740): An error occurred while installing package 'defaults::scikit-learn-1.2.1-py310hd77b12b_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package defaults::scikit-learn-1.2.1-py310hd77b12b_0
location of failed script: C:\Users\never\anaconda3\Scripts\.scikit-learn-post-link.bat
==> script messages <==


    Windows 64-bit packages of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py


==> script output <==
stdout: subdir: win-64

stderr: The system cannot find the file specified.
The system cannot find the file specified.

return code: 1
```
()
![anaconda](https://user-images.githubusercontent.com/129283188/228590714-ee913a4e-f921-4166-86b9-0342d9c843e5.png)

**Comment by neverax** [comment]
Can somebody help please?

**Comment by travishathaway** [comment]
Hi @neverax,

Thank you for filing this issue. Unfortunately, this is off-topic for this repo. If you are still encountering this issue please reopen in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where `conda` installer/package issues are addressed.

You might also be able to find another user who posted a similar issue which has already been answered.

In the meantime, I suggest using the "miniconda" installer instead:

- https://docs.conda.io/en/latest/miniconda.html

**Comment by laghaout** [comment]
Why would  this be off-topic? I'm having the exact same problem as the original poster. There is clearly something wrong with the installer for `Anaconda3-2023.03`.

**Comment by pseudoyim** [comment]
@laghaout - this repo is for the `conda` project which maintains the source code for the `conda` binary itself. Issues regarding the _Anaconda Distribution_ installer (e.g. `Anaconda3-2023.03`) should be opened and tracked [here](https://github.com/ContinuumIO/anaconda-issues/issues/new/choose). Thank you.
