### ISSUE TITLE
Make `conda compare` work with `.lock` files

### ISSUE THREAD

**Issue by epassaro** [conda/conda#12571]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently `conda compare` works out of the box with `.txt`, `yml` or `.yaml` files, but not with `.lock` files made with `conda-lock`. A workaround is just change the file extension manually before doing the comparison.

### Why is this needed?

Because `conda-lock` provides `.lock` files, not `.txt`.

### What should happen?

`conda compare --name <env_name> conda-linux-64.lock`

Should return the comparison between the environment and the dependencies listed in the lockfile.

### Additional Context

I'd like to work on this feature (if the feature is desirable, of course)

**Comment by travishathaway** [comment]
Hi @epassaro,

Thanks for submitting this feature request. I had a chance to speak with the maintainers of conda-lock and they thought would be a great idea. This functionality currently not available in conda or elsewhere.

One thing they said to watch out for is that there are two lock file formats. The classic `.lock` format and the newer yaml based format. If I was you, I would focus on submitting a pull request for just one at first and then add support for the other in a separate pull request.

Please let us know if you need help with this. You can reach out directly via our Matrix chat room: https://matrix.to/#/#conda_conda:gitter.im or simply keep the conversation here.

Happy developing ✌️
