### ISSUE TITLE
Bug in displot with pandas 2.0.0

### ISSUE THREAD

**Issue by Riki96** [conda/conda#12573]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The error occurs using seaborn latest version 0.12 displot with a DataFrame as data, x variable, hue and kind as arguments. 

This is the error:

`ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.`

**Comment by travishathaway** [comment]
Hi @Riki96,

This is not the appropriate place to file an issue. Please only file issues that are relevant to the conda package manager itself and not the software that it installs.
