### ISSUE TITLE
Add a "pre-command" hook to conda

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12593]
### What is the idea?

To allow plugin authors to add extra functionality to conda, we would like to add new plugin hook that gets invoked before calling a conda sub-command (e.g. create, install, etc.).

### Why is this needed?

This is needed to give plugin authors the flexibility they need when adding new features to conda. A good example would be interrupting program to start-up to ask for and store credentials for a login protected channel.

### What should happen?

- [x] Do some preliminary research on other examples like this that use pluggy (regarding the hook call order)
- [ ] A new `pre_command` plugin hook should be added to conda
- [ ] Tests for this new hook will be written and execute a working example of it
- [ ] Documentation will be updated to describe this new plugin hook

### Additional Context

More information about the technical specifications can be found in this CEP proposal:

- https://github.com/conda-incubator/ceps/pull/45

**Comment by travishathaway** [comment]
One question that came up today while working on the `pre_command` plugin hook was:

- What happens if the underlying pre-command action function raises an error?
  - [ ] Log it and continue on with normal program flow
  - [ ] Treat it like any other error in conda and route it through our exception handler?

I'm leaning towards the first. In my opinion, the authors should be doing their due diligence to catch and handle errors and if one happens to slip through the cracks, it shouldn't negatively affect the rest of the command.

If anyone has any other ideas of how to handle this, please let me know.

**Comment by jezdez** [comment]
> One question that came up today while working on the `pre_command` plugin hook was:
> 
> * What happens if the underlying pre-command action function raises an uncaught exception?
>   
>   * [ ]  Log it and continue on with normal program flow
>   * [ ]  Treat it like any other error in conda and route it through our exception handler?
> 
> I'm leaning towards the first. In my opinion, the authors should be doing their due diligence to catch and handle errors and if one happens to slip through the cracks, it shouldn't negatively affect the rest of the command.
> 
> If anyone has any other ideas of how to handle this, please let me know.

We can’t assume plugins to always work but also can’t deduce if the successful run of a plugin might be required for a user or not. In other words we need to fail loudly and not ignore a bad run and just move on (by default).

The user has made a choice about installing and configuring the pre_command plugin, so they’ll need to be able to debug it as well. We could add an option to ignore the result of a plug-in optionally, but that’s maybe over engineering.
