### ISSUE TITLE
Conda meta data should support an array of licenses

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1259]
Not all software has one license.  Currently the meta data stores a string.  It should be able to store an array as well.

**Comment by asmeurer** [comment]
Dual license should just be in a string like "MIT or GPL". Licenses aren't programmatic anyway.

**Comment by tswicegood** [comment]
@asmeurer when dealing with the meta data I shouldn't have to re-parse it to figure out what they are.  How would I compare that two packages have the same license when one is "MIT or GPL" and the other is "GPL or MIT" if they're not an array?

**Comment by kalefranz** [comment]
Maybe implement along with SPDX license identifiers someday, but it'll have to be a new field. Too late to change the data shape now.
