### ISSUE TITLE
Create Docker Image for running server based tests

### ISSUE THREAD

**Issue by sven6002** [conda/conda#12597]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The idea is to create a docker image that will contain the dependencies with the `nginx` server for the channel server to run integration tests in efficient and a stable environment. 

1.  A docker image that would contain the channel server with the `NGINX` HTTP protocol editing the docker-compose file
2. To route the test case to use the docker image to run the test case against (conda-env)
3. To maintain the docker image within the test environment

### Why is this needed?

Currently the  test cases that test against external servers which can fail and make the test cases unstable.. if we decide to host a local server to find dependencies.. 

For example what these test files do: 
- [fixtures_jlap.py](https://github.com/conda/conda/blob/main/tests/fixtures_jlap.py)
- [test_https_server.py](https://github.com/conda/conda/blob/main/tests/http_test_server.py)

so with this ticket instead of test case starting there own local server the docker image will start the server itself.. so that now the test cases can use that.. so this will reduce those steps for set ups and will boost performance and stability of the test cases, This will also help on stability by testing against the local server instead of testing against an external server.

### What should happen?

- [ ] Create pull request showing this can be run locally using the `docker-compose.yml` configuration for the project. This should also include one example test case we can run showing how to use this channel.
- [ ] Report how this can best be setup on GitHub actions (create a separate issue for this if necessary)
- [ ] Compare this to existing approaches (https://github.com/conda/conda/blob/main/tests/http_test_server.py) and make a recommendation on which one would be easiest to implement and maintain.

**Comment by dholth** [comment]
conda has two Python test package or index servers now in https://github.com/conda/conda/blob/main/tests/http_test_server.py and https://github.com/conda/conda/blob/main/tests/fixtures_jlap.py

If we had the necessary packages locally or in a github actions cache, we could point these servers to those files.

[http_test_server.py](https://github.com/conda/conda/blob/main/tests/http_test_server.py)
<https://github.com/[conda/conda](https://github.com/conda/conda)|conda/conda>conda/conda | Added by [GitHub](https://anaconda.slack.com/services/B026B7WE8BG)

[fixtures_jlap.py](https://github.com/conda/conda/blob/main/tests/fixtures_jlap.py)
<https://github.com/[conda/conda](https://github.com/conda/conda)|conda/conda>conda/conda | Added by [GitHub](https://anaconda.slack.com/services/B026B7WE8BG)

**Comment by dholth** [comment]
IMO finding out which packages and index data we need to perform the tests is the most interesting part.

**Comment by travishathaway** [comment]
I'm not sure we will be able to load it up with everything we need at first. It will most likely be a slow a migration over.

I'm more interested to see what type of performance boost this offers. So, perhaps as you come up with the example test cases, be sure to compare against identical test cases testing against an external service.

**Comment by dholth** [comment]
Sure, if it always can fall back to a cache miss, then the cache will be faster or slower depending on how good it is.

We also do a number of requests for the same files during one test session, so we would probably see a benefit from an external cache even if we did not pre-load it at the beginning of the run.
