### ISSUE TITLE
Ability to set a default Conda environment at launch

### ISSUE THREAD

**Issue by linem-davton** [conda/conda#12608]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently, when we launch the Conda prompt, it always starts with the base environment. For users who primarily work in a specific environment other than base, it would be more convenient if the Conda prompt started in their preferred environment. I propose a new configuration option to set a default Conda environment that will be activated at the launch of the Conda prompt. This could be implemented as a parameter in the .condarc file, e.g., default_start_environment. When this parameter is set, the specified environment will be activated automatically when the Conda prompt is launched.

### Why is this needed?

This feature is needed to provide a more seamless and efficient workflow for users who primarily work in a specific Conda environment other than the base environment. By allowing users to set a default environment that automatically activates upon launching the Conda prompt, it eliminates the repetitive and manual step of activating their preferred environment each time.

The main beneficiaries of this feature would be users who consistently work within a particular Conda environment for their projects, research, or development tasks. For instance, users who work on multiple projects that require different dependencies and configurations may have set up dedicated environments for each project. In such cases, they might prefer having their most frequently used environment as the default rather than the base environment.

This feature adds value to users by simplifying their workflow and saving time that would otherwise be spent on manual environment activation. Furthermore, it reduces the risk of users accidentally working in the wrong environment, which could lead to dependency conflicts, incorrect results, or other issues.

In summary, the ability to set a default Conda environment at launch solves the problem of repetitive manual environment activation and enhances the user experience by streamlining workflows and minimizing the risk of errors.

### What should happen?

With the implementation of this feature, users should be able to easily set their preferred default Conda environment and experience a streamlined workflow when launching the Conda prompt. Here's a detailed description of the user experience with the new feature:

Users would update their .condarc configuration file to include the new parameter default_start_environment, followed by the name of their preferred environment. 
For example:
default_start_environment: NewEnv

After saving the changes to the .condarc file, users would launch the Conda prompt, either through a terminal or a dedicated application shortcut.

Upon launching the Conda prompt, instead of automatically activating the base environment, the Conda prompt would now activate the environment specified in the default_start_environment parameter (e.g., the NewEnv environment).

**Comment by travishathaway** [comment]
Hi @linem-davton,

Thanks for this well written feature request. This sounds like a very reasonable request that would make a good addition to conda. We cannot promise when this would be added, but we are always welcoming pull requests from the community to add such features.

In the meantime, we will be keeping this issue open to facilitate a discussion around this issue. I will also be adding the "good-first-issue" label as I believe this would be an interesting piece of work for any new contributors out there.
