### ISSUE TITLE
post-link failed for: openssl-1.0.1k-1

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#1260]
Dear all,

If you do:

```
conda create -n test-glibc python glibc --override-channels --channel defaults --channel https://conda.binstar.org/asmeurer --yes
```

The following error message is displayed:

```
Linking packages ...
/conda-install/envs/test-glibc/bin/.openssl-post-link.sh: line 7:  8560 Segmentation fault      (core dumped) $PREFIX/bin/.openssl-libcrypto-fix $PREFIX
Error: Error: post-link failed for: openssl-1.0.1k-1## 
```

I am using a newly created Conda environment with the latest version of the packages, do you know what is going on here?

Many thanks in advance for your help!

**Comment by asmeurer** [comment]
I don't know what my glibc package is, but it probably doesn't work. It could be what caused the segfault, I suppose.

**Comment by kreczko** [comment]
@asmeurer Just experienced the same problem on Centos 6.5. The installation of your glibc causes a segfault when calling conda/conda-build afterwards.

**Comment by kalefranz** [comment]
Guessing this was fixed a long time ago.  If not, file a new issue at https://github.com/ContinuumIO/anaconda-issues/issues/new
