### ISSUE TITLE
Automatically activate environment after creating it

### ISSUE THREAD

**Issue by kito323** [conda/conda#12600]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Why isn't this a default?

### Why is this needed?

Because I have messed up my `base` too many times because I just always forget to do the tedious task of activating just created env.

### What should happen?

The environment created should be be activated right away. I have never been in situation where I want to change something on previous env after just creating new one...

### Additional Context

I hate that once every half-year I need to reinstall anaconda just because some pip install screwed it up (because there is no easy way to "uninstall" libraries, just reverting env, which I have not had nice experience too). Please add extra warning in red saying "you are in base, are you sure" because once the base is messed up it's just a matter of time when things stop working in general.

**Comment by travishathaway** [comment]
Hi @kito323,

Thanks for submitting this feature request. I hear your frustrations around messing up the base environment. This is something that all the maintainers are well aware of. We want to eventually remove conda entirely from the base environment altogether to address these issues. You can follow that progress on this epic:

- https://github.com/conda/conda/issues/11342

One thing I recommend is to check out the micromamba project. Micromamba is a conda compatible package manager that has already achieved this separation from the base environment. More information available here:

- https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html

Regarding your initial feature request, I too have thought this would be a good idea to add, but I do not think it should become the default. I could imagine it working like the following:

```bash
conda create -n new_env --auto-activate python=3.11
```

Where `auto-activate` would be a command line and configuration file option. You want this to always be on, you could define it as follows in the `.condarc` file:

```yaml
auto_activate: true
```

We could potentially add a feature like that, or a community member could submit a pull request to add such a feature. That's just one idea though. Let's keep this feature request open to start a conversation and figure out the best way forward.

Thanks again for submitting this feature request. I hope I've been helpful.

**Comment by jaimergp** [comment]
Tricky to implement right now given that we would need to add some extra logic in the shell layer (e.g. [this block for POSIX](https://github.com/conda/conda/blob/7ec97d67e05f63260628c33647c68cf455dfbc40/conda/shell/etc/profile.d/conda.sh#L37-L51)), but I'd love this feature too.

**Comment by kito323** [comment]
Thank you for your responses!

I like @travishathaway 's idea of having this kind of configuration variable. Unfortunately, I do not feel like I understand the inner workings of conda well enough to contribute such feature myself. That said, I am a very simple user of conda - I just have few different projects from time to time and I like separating them. Some of them can also be just learning purposes. Being such a user I have never experienced a situation where I need to stay in the `base` after creating new environment and most conda guides/tutorials, that I have ever followed, have had those two steps literally sequentially (some have some useless step or sth that can also be done from the created env too in between)
```
conda create -n my_env
conda activate my_env
```
And this is why, IMHO, this should be a default feature all along. I can only see that if you are new to the virtual environments then this step could help you better understand the different envs and how to navigate between them, but after 2 times it just becomes tedious, especially because creating an environment takes time and it is perfect to read on into the tutorial one is following and forget the activation step all together. If there are any specific reasons why it shouldn't be a default(/suggested to be set as default after doing it 2-3 times manually) that I am not aware of, please, share them with me!

**Comment by timhoffm** [comment]
Combining commands vs. not combing commands is a purity vs. usability decision. Should all operations be minimal (and thus logically separated) or should they common user tasks most efficiently? I'm leaning towards the latter.

I support auto activation. From my experience this is what 98% of the users want. In a green field scenario this should be the default with an `--no-activate` option. Given the current behavior this is not possible - at least not right away.

Depending on how important backward compatibility is to the project, we could either
- follow @travishathaway's suggestion of an opt-in config parameter
- or do that and switch the default of the configuration parameter via a deprecation period, so that people who do not want activation can adapt their config.

**Comment by jaimergp** [comment]
I wonder if we can run a little experiment with shell aliases, something like:

```
conda-create-activate=conda create $* && conda activate $2
```

The env name should always go in the 2nd argument (after `-n`).

Is that more or less the expected behaviour?

**Comment by kito323** [comment]
I think I previously forgot to mention that I am mainly working on Windows machine (but ideally this should be solved for all platforms anyway) so I'll describe my process on Windows, if relevant for anybody.

I was not familiar with "shell aliases" but thank you for the tip @jaimergp . After gathering some new knowledge about those things I learned that `doskey` command is for that purpose but it has to be first saved in a batch (.bat) file and then added to the AutoRun (or some other form of auto-initialization for the cmd) to have it every time prompt is opened. Luckily, there is `activate.bat` already existing for anaconda prompt and with admin privileges it can be edited, so I added the following lines just before the `:End` tag in there:
```
@REM Here you can add your aliases
doskey conda_create=conda create $* $t$t conda activate $2
```
Note the substitution of `&` signs to `$t` as the doskey command otherwise thinks the alias command ends at `&`. I also chose to give alias a name more similar to the regular `conda create` with an idea of if I ever follow some tutorials on conda then I can still copy-paste the commands with minimal editing. If anybody has suggestions how it should be done more properly then feel free to point out my mistakes.

Regarding of expected behaviour I'll say that this workaround pretty much does what I was looking for, although it also prints some extra lines when prompt is started/alias is used, but this is very minor inconvenience. So for now, I will continue with this solution/workaround. Still, it would be nice to see it being a default and not people wasting time on figuring out this sorts of workaround which is also somewhat platform specific as far as I understood (the `doskey`). So from my perspective I would count this thread closed (especially as this will not be relevant anyway after some bigger updates mentioned by @travishathaway ) but if anybody wants to continue to discuss workarounds for other platforms or how should I do it differently then it would make sense to keep it open.

**Comment by hasibagen** [comment]
I have seen several related posts, but it seems that I didn't get any suggestions related to this feature when I directly googled or asked ai. I want to ask if it has been released?
https://github.com/conda/conda/pull/12618
https://github.com/conda/conda/issues/12823
https://github.com/conda/conda/issues/12600

**Comment by travishathaway** [comment]
@hasibagen,

This is not currently available as a feature in conda.

**Comment by hasibagen** [comment]
> @hasibagen,
> 
> This is not currently available as a feature in conda.

Thank you very much for your reply.
Then I would like to ask if there is any alternative method?
Because if I change the shell directly now, this error will be reported 

https://github.com/conda/conda/issues/14216
