### ISSUE TITLE
Anaconda hash verification page yields 404

### ISSUE THREAD

**Issue by Timmate** [conda/conda#12605]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The page that is supposed to house Anaconda installation hashes ([this one](https://docs.continuum.io/free/anaconda/install/hashes/all)) yields a 404 error. The link to that page was found [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/download.html#cryptographic-hash-verification).

PS. Apologies for using this issue template, didn't know which one is more appropriate.

**Comment by travishathaway** [comment]
Hi @Timmate,

Thanks for filing this issue. Unfortunately, this is off-topic for this repo. If you are still encountering this issue please reopen in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where `conda` installer/package issues are addressed.
