### ISSUE TITLE
`conda clean` cannot delete directory because `rsync` error handling code is broken

### ISSUE THREAD

**Issue by JubilantJerry** [conda/conda#12606]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Overview
`conda clean --all` results in `WARNING: cannot remove, file permissions: [directory]` for several directories in the package cache.
All the inner contents of the directories are deleted. But the directories themselves are not.
A `.empty` file gets created in whatever directory my shell is currently on while running `conda clean --all`, and stays even after the end of the `conda clean --all` command.

### About the directories
The directories are all writeable. I can successfully delete the directories by directly running `rm -r [directory]` in the shell.
The directory's owner is not the same as the user running the command. But the group permissions are such that the directory can still be deleted.
The below shows one of the directories that `conda clean --all` could not delete:
```
(pytorch) jerry:~/Documents$ ls -l /srv/mambaforge/pkgs/ | grep pyzmq-24.0.1-py37h0c0c2a8_0
drwxrwsr--+  2 henry conda-users   4096  4月 20 17:38 pyzmq-24.0.1-py37h0c0c2a8_0
(pytorch) jerry:~/Documents$ groups
jerry sudo conda-users
```

### Root cause
I've looked into the code and the culprit is that the deletion is handled using `rsync`, which attempts to change the permissions, group, ownership, and timestamps of the directory because it is called with the `-a` flag.

This alone is only part of the problem. If `rsync` fails `conda` intends to fall back to using `shutil.rmtree`, which works fine in my case.
But the debug logging line itself raises a `NameError`, because it references a non-existent variable. So the error handling code that uses `shutil.rmtree` is unreachable.

The buggy line of code is: https://github.com/conda/conda/blob/main/conda/gateways/disk/delete.py#L128 :
```
except CalledProcessError:
    log.debug(
        f"removing dir contents the fast way failed.  Output was: {out}"  # 'out' is not defined because the exception prevents the variable from being set
    )
```

### Proposed solution
Fixing the logging line to not reference the variable will suffice, because the `shutil.rmtree` will work.
Alternatively, `rsync` should be run with flags `-rlD` instead of `-a`, to produce the same behavior as `shutil.rmtree`.
I've prepared a pull request with both changes made.

### Conda Info

```shell
active environment : pytorch
    active env location : /home/jerry/mambaforge/envs/pytorch
            shell level : 6
       user config file : /home/jerry/.condarc
 populated config files : /home/jerry/mambaforge/.condarc
                          /home/jerry/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/jerry/mambaforge  (writable)
      conda av data dir : /home/jerry/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
          package cache : /srv/mambaforge/pkgs
       envs directories : /home/jerry/mambaforge/envs
                          /home/jerry/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.9.13 Linux/5.19.0-38-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/jerry/mambaforge/.condarc <==
channels:
  - conda-forge
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True

==> /home/jerry/.condarc <==
pkgs_dirs:
  - /srv/mambaforge/pkgs
channels:
  - conda-forge
```

### Conda list

```shell
Very long output that is inconvenient to copy.
I believe this information is not needed for my issue.
```

**Comment by travishathaway** [comment]
Hi @JubilantJerry,

Thanks for submitting this bug report and a pull request to fix it! 👏. At least one of the project maintainers will review it this week.
