### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by 18248406464** [conda/conda#12615]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

base) C:\Users\舒子风>conda create -n voice-clone python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.7

### Conda Info

```shell
...
```

### Conda Config

```shell
...
```

### Conda list

```shell
...
```

### Additional Context

...

**Comment by travishathaway** [comment]
Hi @18248406464,

Thanks for filing this issue. This error can happen for a variety of valid reasons (e.g. some architectures do not have python 3.7 builds available). This does not represent an error in conda, so I will be closing this issue.
