### ISSUE TITLE
Dead link of ToS

### ISSUE THREAD

**Issue by bitsnaps** [conda/conda#12616]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The link to ToS is dead at download page:
https://www.anaconda.com/terms-of-service-anaconda-nucleus
Sorry, I couldn't find a better place to report this issue.

**Comment by beeankha** [comment]
Hi @bitsnaps , thank you for filing this issue! I've created a [new issue in the relevant repository](https://github.com/ContinuumIO/anaconda-issues/issues/13184), so I'll go ahead and close this one.
