### ISSUE TITLE
git clone with --depth=1 in conda-build

### ISSUE THREAD

**Issue by naught101** [conda/conda#1262]
if you're using conda-build with a recipe that uses github as the source, the in most cases, there isn't much point in downloading the whole repository history. The whole history of mature repositories can be orders of magnitude larger than the size of a working copy. It would be good to at least have the option to clone with `--depth=1` (shallow clone) when building. Personally, I think that it should be the default.

**Comment by asmeurer** [comment]
There is, because you typically checkout a tag. Even if there is no tag to checkout, the cached download would be incomplete if a later build was against a tag (and as far as I know, there's no way to clone a repo deeper once you clone it using --depth, but I could be wrong on that).

**Comment by naught101** [comment]
`git pull --depth=<depth>` allows you to deepen a shallow repository (I'm not sure, but `--depth=0` might make it full history?)

I don't really understand your comment. Checking out a tag is effectively the same a checking out a commit - it's a fixed reference to a point in time in the repository, and it doesn't matter what the history is before (or after) that tag/commit. The cached download would be incomplete if you built against a *different* tag, yes. But then you'd only need to download the shallow version of that tag (which you would have to do anyway, with a non-shallow clone, and it might be smaller (if not much has changed), or it might be bigger (if more data in the intervening history than in the single commit)). Basically the same as having to download a new .tar.gz from pypi or whatever.

In any case, I don't mind if it's *not* the default, but it would still be great to have the option. I'm on a poor (and expensive) connection, and downloading a new 2Mb shallow copy of the latest version of pylearn2 every time I update is a *lot* less pain than trying to download the whole 200Mb repository history, only to have it fail at 150Mb multiple times...

**Comment by asmeurer** [comment]
I haven't used the --depth option very much but if this can be made to work seamlessly, then I'm +1 for it.

**Comment by srossross** [comment]
This sounds like a good idea.  The depth argument should warn or even be omitted if any of the  `GIT_DESCRIBE_*` env vars are used

**Comment by naught101** [comment]
Hrm.. in the meantime, I worked around this my just making my own shallow clone, and using a recipe with a local file path instead of with a git repo as the source. Maybe that's more sensible than adding extra code... feel free to close if you think so.

**Comment by kalefranz** [comment]
Wrong issue tracker.  Closing.  File at github.com/conda/conda-build if the feature isn't already built into conda-build by now.
