### ISSUE TITLE
SPIKE: Research for potential shell plugin hook

### ISSUE THREAD

**Issue by kalawac** [conda/conda#12621]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Determine the proposed architecture method for plugins that handle, at minimum, conda's `activate`, `deactivate` and `reactivate` processes.

### Why is this needed?

As per #12451:

> Shell interfaces are difficult to support as they differ widely, and the development team has limited experience with many of the exotic shells supported to offer meaningful support.
> Let's rely on the plugin infrastructure to allow plugins that extend the supported shell interfaces. This means that most of the shells supported out of the box today will be moved into standalone plugins, and we will request community support for future development efforts.

An example that ports the desired functionality into a plugin is [here](https://github.com/kalawac/simple-bash-plugin). The current process flow for the activate process can be seen [here](https://github.com/kalawac/conda/tree/activate-flow/conda/shell#readme). 

Currently, there are three core decision points that will require exploration and, ultimately, consensus:
- What are the architectural criteria that plugins should conform to? For example:
    - Should the plugin have a shell script bundled with it?
    - Should conda or the plugin modify the user's shell profile to allow for automatic evaluation?
    - Is it possible and/or desirable to have a plugin that avoids using a shell script at all?
    - Do we need a new plugin hook? If yes, what should that plugin hook do?
- What are the minimum criteria for a plugin's UX?
- How should the plugin be packaged? What is the migration path?
- In simplifying the code, should we keep `hook` and `command` functionality bundled in with `activate`, `deactivate`, and `reactivate`?

### What should happen?

- [x] Research approaches on plugin architecture, in alignment with the questions and decision points outlined above
- [x] Create document to track arguments for and against each approach
- [x] Create prototypes to better understand UX considerations for each approach

### Additional Context

I’m currently considering the following approaches:

- Inject code logic into the user’s shell profile that will allow the statements printed by the python subcommand to be evaluated (as `conda init` does now)
    - Would likely require a new plugin hook implementation that would actually yield the relevant shell logic and make the changes
- Use modules and functions available in more recent versions of Python (e.g., argparse, [os.execve](https://docs.python.org/3/library/os.html#os.execve)) to simplify the code logic and evaluate the shell commands without needing to exit Python (that is, eliminate the need for separate shell scripts) and implement the plugins as a pure Python subcommand
- Continue to use shell scripts: each new plugin would require the subcommand and the related shell script.
    - Would likely require a new plugin hook implementation that would make the associated shell script the default entry point for the conda executable
    - This also implies “inject code logic into the user’s shell profile”

**Comment by kalawac** [comment]
Document to track arguments for and against each approach: https://gist.github.com/kalawac/8a05141237a59f0f4e9830096704eb4f

Plugin prototypes: https://github.com/conda/conda/pull/12662

**Comment by kenodegard** [comment]
A standalone plugin is in the works at https://github.com/conda-incubator/conda-shell, further research and discussion belongs there
