### ISSUE TITLE
conda update got interrupted, and then conda command got removed

### ISSUE THREAD

**Issue by zmz1988** [conda/conda#12628]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

It has already happened the same things to me twice. I updated conda with command `conda update --all`, and then at the final stage `Executing transaction:`, the connection to the serve was lost (I don't know why it's always at this step when the connection got lost). Then after I reconnect to the server, the `conda` command is gone. 

```
$ conda env list
-bash: conda: command not found
```

I thought probably I could try the installed mamba, but when I call mamba:
```
$ mamba env list
Traceback (most recent call last):
  File "/miniconda3/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 14, in <module>
    from conda.base.constants import ChannelPriority, DepsModifier, UpdateModifier
ModuleNotFoundError: No module named 'conda.base.constants'
```
None of the mamba call works either. 

May I ask how to fix it? I actually just re-installed conda and all the packages two weeks ago, because of the same problem last month.

### Conda Info

```shell
Can't run `conda`. it's the newest conda version.
```

### Conda Config

```shell
Same as above.
```

### Conda list

```shell
Same as above.
```

**Comment by travishathaway** [comment]
Hi @zmz1988,

Thanks for filing this issue. During the `Executing transaction` phase of the update command, conda has actually retrieved everything it needs (i.e. packages) from the remote server. Instead, it is going through all of the newly collected packages and installing them to their desired location.

I suspect their may be something wrong with your file system, but I cannot determine this without having more information.

Could you please provide more information about your system?

- OS type (windows)
- File system capacity and current file system usage
- Which drive or folder is conda being installed to

In the meantime, I also suggest you experiment with installing [micromamba](https://mamba.readthedocs.io/en/latest/installation.html#micromamba). Unlike mamba, it doesn't share a dependency with conda, so it may work better in your case.

**Comment by zmz1988** [comment]
Hi @travishathaway ,

Thanks for replying me so fast. 

I installed conda on our computer cluster, which is linux system. My won computer is MacOS.
I didn't install conda in my personal folder on the cluster, instead on a shared folder, which still have 970G space available (7 T space in total).

I guess I could give these information from me. I'm not sure whether I answer your questions. If you need more information, I could ask our computer cluster admin. just let me know.

Thanks a lot for your help!

**Comment by dholth** [comment]
It may be possible to use the miniconda or anaconda installer to either reinstall on top of the old environment, or, to install conda into a new environment; then `~/newconda/bin/conda install -n /path/to/broken/environment conda`

**Comment by dholth** [comment]
This command will use the path instead of the name of an environment, from a "miniconda5" environment with conda installed. `miniconda5 % ./bin/conda install -p ~/miniconda3 conda`

**Comment by travishathaway** [comment]
Hi @zmz1988,

I suspect there may  also be something weird going on with your shared folder. I would instead install this to your personal folder if you have enough space.

The "server connection" issue you are seeing is probably because this is a network file storage issue and not actually a problem with conda itself. I would urge you to talk with your cluster admin to find a way to resolve this issue.

Because this doesn't represent problem with conda, I will be closing this issue for now. If you believe you have found a bug within conda itself that needs to be addressed, I would encourage you to re-open this issue and provide a justification for doing so.

In the meantime, I wish you luck with getting this up and running successfully.
