### ISSUE TITLE
Add a better version print out for `conda --version`

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12635]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The GitHub CLI includes a link to the release notes when `gh --version` is run. Example below:

```
$ gh --version
gh version 2.28.0 (2023-04-25)
https://github.com/cli/cli/releases/tag/v2.28.0
```

This would be pretty neat to add to conda as well. I hope this would be relatively straightforward to implement, but I am not 100% sure.

### Why is this needed?

This would provide users with a quicker link to our release notes which outline what has changes in various versions. This could help users write more informed bug reports/feature requests.

### What should happen?

- [ ] When `conda --version` is run, a link to the release notes is also shown (see the `gh --version` example for details)
- [ ] The link to the release notes should reference our documentation (e.g. https://docs.conda.io/projects/conda/en/stable/release-notes.html#release-notes) and note the GitHub page.
- [ ] Add a new `release notes` entry to `conda info`

### Additional Context

Because this could break existing behavior, the new output should be opt-in with a migration path to making it the default.

**Comment by wolfv** [comment]
Nice idea! 

I could imagine that some tools rely on the way that `--version` used to be printed on the command line, maybe one can offer them a nice migration path (e.g. `conda info --select version` or something like that?

**Comment by travishathaway** [comment]
Ahh yes, [Hyrum's Law](https://www.hyrumslaw.com/) 😂 

We could definitely do that. Additionally, we could also just add new entry to the "conda info" listing.

Example:

```
active environment : base
    active env location : /Users/travishathaway/opt/conda_x86_64
            shell level : 1
       user config file : /Users/travishathaway/.condarc
 populated config files : /Users/travishathaway/.condarc
          conda version : 23.3.1
          release notes : https://github.com/conda/conda/releases/tag/23.3.1
...
```
