### ISSUE TITLE
md5sum error in linux installer python3.8

### ISSUE THREAD

**Issue by LordBagheera** [conda/conda#12632]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I've just download miniconda(Python 3.8) installer for GNU/Linux from: https://docs.conda.io/en/latest/miniconda.html#id31

<html>
<body>

Miniconda3 Linux 64-bit | 65.8 MiB | d1f3a4388c1a6fd065e32870f67abc39eb38f4edd36c4947ec7411e32311bd59
-- | -- | --

</body>
</html>

from my docker machine i ran:
<code>
bb71ddc7522c:~/wip# wget https://repo.anaconda.com/miniconda/Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
Connecting to repo.anaconda.com (104.16.130.3:443)
Miniconda3-py38_23.3 100% |*****************************************************************************************************************************************************| 65.8M  0:00:00 ETA
bb71ddc7522c:~/wip#
bb71ddc7522c:~/wip# md5sum Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
48ac6b8e4cbcaa3a85d4c3fce067e33f  Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
</code>

this would be a potential security issue.

please review

### Conda Info

```shell
N/A
```

**Comment by travishathaway** [comment]
Hi @LordBagheera,

Thanks for filing this issue. The listed hash is actually a SHA 256 hash and correctly matches the file:

```
shasum -a 256 Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
d1f3a4388c1a6fd065e32870f67abc39eb38f4edd36c4947ec7411e32311bd59  Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
```

Therefore, I will be closing this issue. We do appreciate your concern though!
