### ISSUE TITLE
about add a proxy to access the internet

### ISSUE THREAD

**Issue by leizhu1989** [conda/conda#12648]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After upgrading from Conda 4.5 to version 23.3 ，the proxy was unable to use . When I run Command ‘conda install -c anaconda cudatoolkit=11.7’  or 'conda create -n train python=3.8' 

and have a error :
ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.

the condarc like:
proxy_servers:
    http: http://username:password@proxy_host:proxy_port
    https: https://username:password@proxy_host:proxy_port

In version 4.5 ,there has no this error when add proxy in condarc.  Why is it ,and how can I use proxy to install package for has no network

### Conda Info

```shell
version 23.3.1
```

### Conda Config

```shell
null
```

### Conda list

```shell
null
```

### Additional Context

null

**Comment by travishathaway** [comment]
Hi @leizhu1989,

Thanks for filing this issue. I would encourage you to read our documentation regarding authenticating through a proxy to make sure that your settings are still be correctly configured:

https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html?#configure-conda-for-use-behind-a-proxy-server-proxy-servers

Please let us know if you are still experiencing issues.

**Comment by leizhu1989** [comment]
thanks for your reply . When I restarted SSH, It can use proxy for install package, thank you !
