### ISSUE TITLE
Variable expansion when setting environment variables from env.yaml

### ISSUE THREAD

**Issue by CIaran-Lundy** [conda/conda#12645]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

at present writing:

```
variables:
  PARAMS: ${CONDA_PREFIX}/share/params
```

yeilds

```
$ echo $PARAMS
${CONDA_PREFIX}/share/params
```

it would be great if it could yeild something like:

```
/home/ciaran/mambaforge/envs/env/share/params
```

### Why is this needed?

This would allow the user to set environment variables that point to files in the conda environment, without requiring the CONDA_PREFIX to be hardcoded in. 

This would allow the environment to be shareable, whilst still allowing the environment variable to be set (my CONDA_PREFIX is /home/ciaran/mambaforge, someone elses CONDA_PREFIX could be /home/OTHERNAME/mambaforge, and so my environment variables do not travel well)

### What should happen?

the user should be able to rely on variable expansion within the variables section of the yaml - i.e. writing ${CONDA_PREFIX}/share/params leads to the variable being set in conda with ${CONDA_PREFIX} replaced by their CONDA_PREFIX

**Comment by travishathaway** [comment]
Hi @CIaran-Lundy,

Thanks for filing this feature request. We actually implemented something very similar recently for putting tokens into you URLs:

- https://github.com/conda/conda/pull/12074

So, this could potentially implemented in a similar way. I will add the "first-good-issue" label, so this might hopefully get some more attention.

**Comment by CIaran-Lundy** [comment]
Hi @travishathaway - thats great! thanks!

**Comment by jezdez** [comment]
Sorry, but we'll have to go back to https://github.com/conda/conda/issues/11633 first before implementing this. I've left a comment in #12742 about this, we're piling on `conda env update` here without plan.
