### ISSUE TITLE
Problem with update on Windows

### ISSUE THREAD

**Issue by istaheev** [conda/conda#1264]
I tried to update some packages in my Anaconda installation. All packages were updated successfully except for pandas.

> C:\Langs\Anaconda>conda info
> Current conda install:
>
>                   platform : win-32
>              conda version : 3.10.1
>        conda-build version : 1.11.0
>             python version : 2.7.9.final.0
>           requests version : 2.6.0
>           root environment : C:\Langs\Anaconda  (writable)
>        default environment : C:\Langs\Anaconda
>           envs directories : C:\Langs\Anaconda\envs
>              package cache : C:\Langs\Anaconda\pkgs
>               channel URLs : https://repo.continuum.io/pkgs/free/win-32/
>                              https://repo.continuum.io/pkgs/free/noarch/
>                              https://repo.continuum.io/pkgs/pro/win-32/
>                              https://repo.continuum.io/pkgs/pro/noarch/
>                config file : None
>          is foreign system : False

> C:\Langs\Anaconda> conda list
> ...
> `pandas                    0.15.2               np19py27_1`
> ...

> C:\Langs\Anaconda>conda install pandas
> Fetching package metadata: ....
> Solving package specifications: .
> Package plan for installation in environment C:\Langs\Anaconda:
> 
> The following NEW packages will be INSTALLED:
> 
>     pandas: 0.16.0-np19py27_1
> 
> Proceed ([y]/n)? y
> 
> Linking packages ...
> An unexpected error has occurred, please consider sending the            |   0%
> following traceback to the conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> Include the output of the command 'conda info' in your report.
> 
> 
> Traceback (most recent call last):
>   File "C:\Langs\Anaconda\Scripts\conda-script.py", line 4, in <module>
>     sys.exit(main())
>   File "C:\Langs\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
>     args_func(args, p)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
>     args.func(args, p)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
>     install.install(args, parser, 'install')
>   File "C:\Langs\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
>     plan.execute_actions(actions, index, verbose=not args.quiet)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\plan.py", line 502, in execute_actions
>     inst.execute_instructions(plan, index, verbose)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\instructions.py", line 141, in execute_instructions
>     cmd(state, arg)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\instructions.py", line 84, in LINK_CMD
>     link(state['prefix'], arg, index=state['index'])
>   File "C:\Langs\Anaconda\lib\site-packages\conda\instructions.py", line 80, in link
>     install.link(pkgs_dir, prefix, dist, lt, index=index)
>   File "C:\Langs\Anaconda\lib\site-packages\conda\install.py", line 523, in link
>     os.makedirs(dst_dir)
>   File "C:\Langs\Anaconda\lib\os.py", line 157, in makedirs
>     mkdir(name, mode)
> WindowsError: [Error 5] Access is denied: 'C:\\Langs\\Anaconda\\Lib/site-packages/pandas/core'

**Comment by ccordoba12** [comment]
It seems you're using Pandas while trying to update it.

**Comment by istaheev** [comment]
Yes, you are right. After closing all notebooks update went fine, Sorry for disturbing.
