### ISSUE TITLE
conda init prepending to PATH overwriting existing CMake location

### ISSUE THREAD

**Issue by GLivshits** [conda/conda#12655]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello. Conda init prepends its bin locations to path, overwriting some already existing binaries.
For example, I do have cmake 3.26.3, and inside anaconda cmake is 3.25.0.
After conda init "cmake --version" output: 3.25.0

"which conda" output:
$HOME/anaconda3/bin/cmake

"which -a conda" output:
$HOME/anaconda3/bin/cmake
/usr/local/bin/cmake

Appending conda ($HOME/anaconda3/bin and $HOME/anaconda3/condabin) to PATH instead of prepending also breaks conda  activate:

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

      Currently supported shells are:
        - bash
        - fish
        - tcsh
        - xonsh
        - zsh
        - powershell
      
      See 'conda init --help' for more information and options.
      
      IMPORTANT: You may need to close and restart your shell after running 'conda init'.

As an outcome, I would like anaconda not to break paths to my system packages.
Thanks!

### Conda Info

```shell
active environment : base
    active env location : /home/grigoriy/anaconda3
            shell level : 1
       user config file : /home/grigoriy/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : 3.24.0
         python version : 3.9.13.final.0
       virtual packages : __cuda=12.1=0
                          __linux=5.19.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/grigoriy/anaconda3  (writable)
      conda av data dir : /home/grigoriy/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/grigoriy/anaconda3/pkgs
                          /home/grigoriy/.conda/pkgs
       envs directories : /home/grigoriy/anaconda3/envs
                          /home/grigoriy/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.19.0-41-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : /home/grigoriy/.netrc
           offline mode : False
```

**Comment by travishathaway** [comment]
Hi @GLivshits,

Thanks for filing this issue. The output of `which conda` should not be pointing to a file, rather it should be pointing to a shell function. Because you are seeing this, I would advise you to run `conda init` once more to ensure that it has been appropriately initialized in your environment.

This does not represent an actual bug with conda, so I will be closing this issue now.
