### ISSUE TITLE
Cannot get conda-build skeleton for projects on pypi that have with pyproject.toml.

### ISSUE THREAD

**Issue by ubaldot** [conda/conda#12659]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to build a conda package from an available package on pypi.
I am following  [conda commands](https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-skeleton-pypi.html) by running `conda skeleton --recursive mypackage`.

However, it seems that to create recipes from pypi the package must have a `setup.py`, whereas said package has a `pyproject.toml `file.

Is there any method to create a `conda skeleton` from pipy packages that have a `pyproject.toml `file?

But regardless of the presence on pypi, is there a simple and comprehensive way to build conda packages for projects that have `pyproject.toml`?

**Comment by travishathaway** [comment]
Hi @ubaldot,

Thanks for filing this issue. `conda skeleton` has not been actively developed for quite some time now and therefore has not kept up with the latest trends in packaging.

Instead, I would recommend using a tool called [Grayskull](https://github.com/conda/grayskull). The author of that project was/is also a conda contributor.

I've personally used this tool to generate recipes for projects of mine using `pyproject.toml` files generated by [poetry](https://python-poetry.org/). You can checkout this repository for an example of how that looks:

- https://github.com/travishathaway/latz

(check out the https://github.com/travishathaway/latz/blob/main/recipe/meta.yaml for example of what it generates).

I think this should be enough information to get you going, so I will be closing this issue for now. Please reach out to the Grayskull project directly on GitHub if you run in to any issues.

Good luck ✌️

**Comment by ubaldot** [comment]
Thanks. Sure, you can close this. 
Related question: is there any **updated** and **comprehensive** guide that describe how to create conda packages and distribute on conda channels such as anaconda and conda-forge? 
I would gladly avoid following obsolete guidelines that are around :)
