### ISSUE TITLE
Yes does nothing when presented with Y/N/F

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1265]
Steps to reproduce:
- Install `pandas=0.14*` into an environment
- Open python console and `import pandas` -- leave open
- In another Window, attempt to install.

You will be prompted that there is a suspected issue and told to confirm with yes, no, and force.  If you choose `y`, nothing happens.

**Comment by asmeurer** [comment]
It's a confusing dialog. The yes is supposed to me "try again", as in, it will only actually work if you go in and close pandas.
