### ISSUE TITLE
Manually-downloaded packages are missing channel metadata

### ISSUE THREAD

**Issue by AcylSilane** [conda/conda#12675]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

# Background

On unstable connections (e.g. mobile in remote areas) it is common for the connection to be interrupted during a download. Conda will notice the download is incomplete (the classic "Downloaded bytes did not match what was expected" message) and refuses to install. This is the expected behavior, but there is no way to restart a download from the last byte found. If the connection is particularly bad, this can make it impossible to install packages.

The workaround for this is to manually download the package from Anaconda's repository. This can cause Conda to not handle dependencies correctly, as the manually-installed packages do not contain the same metadata that a regular install has. Even if they're from the exact same URL `conda install` uses.

# Steps to reproduce:
1. Make a fresh conda environment with Python:

```bash
conda create --name temp_env python=3.10
conda activate temp_env
```

2. Let's manually install a package. We'll use MKL (here we use the .conda format, but this will reproduce with the .tar.bz2 packages as well) because it's a widely-used library, and also pretty large. Because of that, it's a prime candidate to cause problems on an unstable connection.

```bash
mkdir tmp
cd tmp
curl -LOC - https://repo.anaconda.com/pkgs/main/win-64/mkl-2021.4.0-haa95532_640.conda

# OpenMP is needed for MKL
# In the original post this was installed before MKL. See my comment below for further explanation, but
# if we don't install OpenMP, there's a higher chance it will try to "upgrade" mkl
# conda install "intel-openmp=2021.4.0"
conda install mkl-2021.4.0-haa95532_640.conda
```

3. Check the metadata of the package you just installed. It has lost information about the channel this was obtained from:

```bash
head -n 9 /path/to/your/anaconda/envs/temp_env/conda-meta/mkl-2021.4.0-haa95532_640.json
```
```json
{
  "arch": "x86_64",
  "build": "haa95532_640",
  "build_number": 640,
  "channel": "<unknown>",
  "constrains": [],
  "depends": [
    "intel-openmp 2021.*"
  ],
```

In addition, there doesn't seem to be any way to manually pin a version of an environment to the specific version of the package downloaded this way. This combined with every channel having a higher priority than `<unknown`> (seems to happen more frequently when Channel Priority is disabled), will frequently cause conda try to re-install the manually-installed package from the internet - even if it's the same version. 

### Conda Info

```shell
active environment : base
    active env location : C:\Users\user\anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files :
          conda version : 23.3.1
    conda-build version : 3.23.3
         python version : 3.9.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : C:\Users\user\anaconda3  (writable)
      conda av data dir : C:\Users\user\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
N/A
```

**Comment by travishathaway** [comment]
Hi @AcylSilane,

Thanks for submitting this very well documented issue. My gut feeling tells me that this appears as "unknown" in the metadata because it technically was not installed via that channel. The conda package was downloaded and installed manually from the the filesystem.

Regardless, this does point to a deficiency in our documentation. This was the only reference I was able to find:

- https://docs.conda.io/projects/conda/en/stable/user-guide/concepts/installing-with-conda.html?#installing-conda-packages-offline

At the end, there is only a vague statement about resolving dependencies manually, and it does not talk about the implications of doing so or how one might go about doing.

I'm not sure that adding the "channel" to the metadata is the correct thing to do here, but I do think that we can better document your use case in our documentation.

I'm going to leave this issue open so that we can discuss the best thing to do going forward.

**Comment by bkreider** [comment]
What happens if you put the package in $PREFIX_ROOT/pkgs?  Will conda re-download it or will it find it there?  ie: does it need to be in a metadata file somewhere?

If you can pre-populate the $PREFIX_ROOT/pkgs directory manually, that seems like a better workaround than `conda install <filename>` which just that package without andy dependencies.

**Comment by AcylSilane** [comment]
No luck placing the .conda file into either the environment's pkgs dir, or the conda root's pkgs dir. In either case, attempting to install mkl will use the internet if I don't explicitely give it the path to the file. Even when the `mkl-2021.4.0-haa95532_640` folder already exists in the pkgs dir from a previous install. Unless there is some other place it checks for cached downloads, it doesn't seem to see the one I manually put there. Is there some manifest file it checks first to see what's been downloaded already?

Another thing is that while trying your suggestion, I uninstalled mkl first. After that, when I was testing `conda install mkl`, for some reason it kept trying to re-install the 2021.4.0 version of the library, even though multiple versions have been released since then. Turns out, it's because I had installed Intel OpenMP 2021.4.0 in the original post. I originally did that because MKL depends on it, since local installs don't bring in their dependencies automatically, but that might actually hint to an intermediate solution if anyone else runs into this.

Here are a few cases I tried, to see what causes it to decide to upgrade:

- If I install intel-openmp=2021.4.0 first, then install the local copy of MKL, then `conda install mkl-devel` (which needs MKL), it will not try to re-download MKL. This is because the solver sees that I've pinned OpenMP to 2021.4.0.

- If I install the local MKL first, then `intel-openmp` (no version specified), it tries to install the latest OpenMP (2023.1.0). This is not compatible with MKL 2021.4.0, so it tries to upgrade MKL to 2023.1.0.

- If I install the local MKL first, then specify the version `intel-openmp=2021.4.0`, it will not try to update MKL. 

- Likewise, installing mkl-devel=2021.4.0 won't try to upgrade MKL either. I assume what happens here is that mkl 2021.4.0 is the only version supported by mkl-devel 2021.4.0, so there's nothing for it to try and upgrade to.

- If I install the local MKL first, then try `conda install mkl=2021.4.0`, this command will not attempt to upgrade MKL, and will correctly grab the OpenMP 2021.4.0 dependency. I had hoped this would also pin the version of MKL to 2021.4.0, but unfortunately it does not. A `conda install mkl-devel` will try to upgrade to 2023 and re-download.

- If I install the local MKL and OpenMP (no versions pinned) first, then try `conda install --freeze-installed mkl-devel` or `conda install --no-update-deps mkl-devel`, it will attempt to upgrade both the MKL and Intel-OpenMP packages. I had hoped this would work, since `conda install -h` says for either option: "Do not update or change already-installed dependencies."

**Workaround So Far**
The easiest solution right now for the "locally-installed versions are likely to be upgraded" thing seems to be to take advantage of version pinning. 

If you already know a dependency that strictly requires the version of your local package, then you can pin that one and you're good to go. 

If you're installing something that has no dependencies or dependents you can take advantage of, you can create a dummy package that depends on your specific version and install that:

```bash
mkdir my_force_mkl
cd my_force_mkl
vi meta.yaml
```

And inside meta.yaml:

```yaml
package:
  name: my_force_mkl
  version: 2021.4.0

requirements:
  run:
    - mkl==2021.4.0
```

Then,

```bash
conda build .
conda install --use-local my_force_mkl=2021.4.0
```

And at that point, because you've created a package  that can only depend on the specific version of the package you downloaded, the solver shouldn't\* attempt to re-download it

\* I haven't been able to reproduce the other issue I mentioned in the OP, where I've seen conda try to re-download an existing version of a package because a channel is higher-priority than another.
