### ISSUE TITLE
conda channel api idea

### ISSUE THREAD

**Issue by cjw296** [conda/conda#1267]
Another one from chatting to @tswicegood at pycon:

Have the channel api be a REST request thing where you ask a channel what it knows about a package, eg:

```
GET /channel/mypackage

{..., 'platforms': ['0.5.0x', '10.1.1']}
```

So:
- be able to look up a package, rather than having to download the 'total set of available package'
- have a compact notation (the two element list above) for the range of available versions available, so you know whether this channel can serve you the version you require

**Comment by tswicegood** [comment]
Assigned this one to myself -- still thinking about this and what it would need to be.
