### ISSUE TITLE
conda can try to use a missing temporary file when `repodata.json` was not found, and `{}` was returned instead

### ISSUE THREAD

**Issue by dholth** [conda/conda#12689]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The new RepodataFetch feature tries to replace the index file with a temporary file, for locking reasons, in gateways/repodata/RepodataFetch.fetch_latest(). However the underlying RepoInterface might not write to that file e.g. when it returns {} in place of a 404 or possibly in "offline" mode (which uses the cache even when it would normally be expired).

**Comment by dholth** [comment]
It's not clear why this can happen because the save function always writes to that file: https://github.com/conda/conda/blob/main/conda/gateways/repodata/__init__.py#L631-L645

Are there shenanigans in the RepoInterface class?

**Comment by kenodegard** [comment]
Resolved by #12690
