### ISSUE TITLE
feature request: "conda destroy <env>"

### ISSUE THREAD

**Issue by cjw296** [conda/conda#1269]
To delete an environment, I currently do:

```
$ cd ~/anaconda/envs/
$ rm -rf <env>
```

Is that correct? will it always be correct?

Would be great if "conda destroy <env>" existed and did the right thing.

**Comment by ccordoba12** [comment]
There is

    conda env remove -n foobar

already. That's what I use :-)

**Comment by cjw296** [comment]
This insistency of 'conda env x' for some things and 'conda x' for others is really annoying :-(

**Comment by ccordoba12** [comment]
I think the only thing missing from `conda env` is creating environments because currently you have to use `conda create` for that :-(

I think `conda` (without subcommands) should be used only to install/remove packages.

**Comment by cjw296** [comment]
There is both "conda create" and "conda env create".

My gut feel is that the 'env' namespace shouldn't exist.

**Comment by asmeurer** [comment]
This is a dupe: https://github.com/conda/conda/issues/723

And yes, deleting an environment is the same as `rm -rf`. You can also use `conda remove -n env --all`, which does the same thing but shows a progress bar.
