### ISSUE TITLE
Anaconda3 Command Line Install for MacOS 13.3.1: TypeError Bug 

### ISSUE THREAD

**Issue by Rahul-Rut** [conda/conda#12698]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

OS: MacOS 13.3.1
File: Anaconda3-2023.03-1-MacOSX-arm64
I had previously installed Anaconda, but had to uninstall it for various reasons, and now when I tried reinstall-ing it using the pkg file, I kept running into an error and failed to install it. Upon trying the Command Line Install, I ran into the following Error Report:

`>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/cli/main_init.py", line 33, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/core/initialize.py", line 113, in initialize
        run_plan_elevated(plan2)
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/core/initialize.py", line 709, in run_plan_elevated
        result = subprocess_call(
      File "/Users/USERNAME/anaconda3/lib/python3.10/site-packages/conda/gateways/subprocess.py", line 98, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/Users/USERNAME/anaconda3/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/Users/USERNAME/anaconda3/lib/python3.10/subprocess.py", line 1985, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'

### Conda Info

```shell
active environment : None
       user config file : /Users/USERNAME/.condarc
 populated config files : /Users/USERNAME/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3.1=0
                          __unix=0=0
       base environment : /Users/USERNAME/anaconda3  (writable)
      conda av data dir : /Users/USERNAME/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/USERNAME/anaconda3/pkgs
                          /Users/USERNAME/.conda/pkgs
       envs directories : /Users/USERNAME/anaconda3/envs
                          /Users/USERNAME/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Darwin/22.4.0 OSX/13.3.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /opt/homebrew/Caskroom/miniforge/base/.condarc <==
channels:
  - conda-forge

==> /Users/USERNAME/.condarc <==
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at /opt/homebrew/Caskroom/miniforge/base:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py310h8e9501a_1005    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.1.0          py310hbe9552e_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              40.0.1          py310hfc83b78_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
libcxx                    16.0.0               h75e25f2_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   3.1.0                h03a7124_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pycosat                   0.6.4           py310h8e9501a_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.10         h3ba56d0_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.17.21         py310h8e9501a_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h8e9501a_1    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstandard                 0.19.0          py310had9512b_1    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

### Additional Context

The following were presented as environment variables:

environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/USERNAME/anaconda3
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.10/
                          bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Crypte
                          xes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:
                          /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/v
                          ar/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleint
                          ernal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

**Comment by travishathaway** [comment]
Hi @Rahul-Rut,

Thanks for submitting this issue. It looks like you also installed conda via `brew`? Is there a chance this could be interfering with the Anaconda Distribution install? Perhaps you can try to uninstall it there too and then try a fresh install.

Please let us know if this works.

Also, you can check out this issue queue for Anaconda Distribution related issue to see if anyone else is having similar problems:

- https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by jaimergp** [comment]
This is a bug in `conda.gateways.subprocess`. `stdin` is being passed as `str` and should be encoded into `bytes` in some contexts.

We ran into this bug because the initialization routines require `sudo` access, which involves a process relaunch. You might get around it by installing to a location that does not require `sudo` access, or running the installer with `sudo` from the beginning:

```
$ sudo bash Anaconda-installer.sh
```

**Comment by travishathaway** [comment]
Thanks for creating a "meta-issue" to link these issues together. It appears as if we have found a real bug 🐛.

Let's keep this issue open for now as an example. We can close once this bug has been addressed.

**Comment by kenodegard** [comment]
Closing this since https://github.com/conda/conda/pull/13240 was just merged
