### ISSUE TITLE
Too many anaconda prompts are opening while opening the navigator app

### ISSUE THREAD

**Issue by ReemaMohanty** [conda/conda#12705]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The anaconda command prompt keeps popping up while opening the navigator app.I am using anaconda 2022.10 version for Windows.

### Conda Info

```shell
conda is not recognized as an internal command- message showing in the command prompt
```

**Comment by travishathaway** [comment]
Hi @ReemaMohanty,

Thanks for filing this issue. This is unfortunately the wrong spot for it. Could you please file an issue over at this issue tracker instead?

- https://github.com/ContinuumIO/anaconda-issues/issues

You might also be able to find users having the same problem as you there. I will be closing this issue for now.
