### ISSUE TITLE
conda update error

### ISSUE THREAD

**Issue by ccyganow** [conda/conda#1271]
When trying to run conda update  I got the following error, which it suggested I report.

The error seems to have broken the anaconda install, e.g. after the error 
[cc243@thistle3 sma_data_2013]$ conda info
conda: Command not found.
[cc243@thistle3 sma_data_2013]$ python -V
Python 2.6.6 (instead of 2.7.7)

Output:
[cc243@thistle3 sma_data_2013]$ python -V
Python 2.7.7 :: Anaconda 1.9.0 (64-bit)
[cc243@thistle3 sma_data_2013]$ conda update astropy
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /data/cc243/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astropy-1.0.1              |       np19py27_0         7.2 MB
    conda-3.10.1               |           py27_0         164 KB
    conda-env-2.1.4            |           py27_0          15 KB
    numpy-1.9.2                |           py27_0         7.8 MB
    openssl-1.0.1k             |                1         2.6 MB
    python-2.7.9               |                2        13.4 MB
    requests-2.6.0             |           py27_0         594 KB
    sqlite-3.8.4.1             |                1         2.5 MB
    system-5.8                 |                2         170 KB
    tk-8.5.18                  |                0         1.9 MB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:        36.3 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    astropy-0.3.0              |       np18py27_0
    conda-3.5.5                |           py27_0
    numpy-1.8.1                |           py27_0
    openssl-1.0.1h             |                0
    python-2.7.7               |                2
    requests-2.3.0             |           py27_0
    sqlite-3.8.4.1             |                0
    system-5.8                 |                1
    tk-8.5.15                  |                0
    zlib-1.2.7                 |                0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    astropy-1.0.1              |       np19py27_0   hard-link
    conda-3.10.1               |           py27_0   hard-link
    conda-env-2.1.4            |           py27_0   hard-link
    numpy-1.9.2                |           py27_0   hard-link
    openssl-1.0.1k             |                1   hard-link
    python-2.7.9               |                2   hard-link
    requests-2.6.0             |           py27_0   hard-link
    sqlite-3.8.4.1             |                1   hard-link
    system-5.8                 |                2   hard-link
    tk-8.5.18                  |                0   hard-link
    zlib-1.2.8                 |                0   hard-link

Proceed ([y]/n)? y

Fetching packages ...
astropy-1.0.1- 100% |#####################################################################################################################################################################| Time: 0:00:02   3.28 MB/s
conda-3.10.1-p 100% |#####################################################################################################################################################################| Time: 0:00:00 376.65 kB/s
conda-env-2.1. 100% |#####################################################################################################################################################################| Time: 0:00:00 170.56 kB/s
numpy-1.9.2-py 100% |#####################################################################################################################################################################| Time: 0:00:02   3.39 MB/s
openssl-1.0.1k 100% |#####################################################################################################################################################################| Time: 0:00:01   1.62 MB/s
python-2.7.9-2 100% |#####################################################################################################################################################################| Time: 0:00:02   5.78 MB/s
requests-2.6.0 100% |#####################################################################################################################################################################| Time: 0:00:01 570.80 kB/s
sqlite-3.8.4.1 100% |#####################################################################################################################################################################| Time: 0:00:01   1.54 MB/s
system-5.8-2.t 100% |#####################################################################################################################################################################| Time: 0:00:00 392.78 kB/s
tk-8.5.18-0.ta 100% |#####################################################################################################################################################################| Time: 0:00:01   1.37 MB/s
zlib-1.2.8-0.t 100% |#####################################################################################################################################################################| Time: 0:00:00 287.19 kB/s
Extracting packages ...
[      COMPLETE      ] |#######################################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#######################################################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the#############################                                                                                                                     |  36%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/data/cc243/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 278, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    execute_plan(plan, index, verbose)
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/history.py", line 57, in __exit__
    self.update()
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/history.py", line 73, in update
    self.write_changes(last, curr)
  File "/data/cc243/anaconda/lib/python2.7/site-packages/conda/history.py", line 144, in write_changes
    with open(self.path, 'a') as fo:
IOError: [Errno 13] Permission denied: '/data/cc243/anaconda/conda-meta/history'
[cc243@thistle3 sma_data_2013]$ conda info
conda: Command not found.

**Comment by ilanschnell** [comment]
Was Anaconda (or Miniconda) previously installed as a different user?

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1257 should make this error go away.
