### ISSUE TITLE
Convert a conda env yaml file to a list of requirements for a settings.ini file accounting for channels and conversions for pypi

### ISSUE THREAD

**Issue by dsm-72** [conda/conda#12727]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I wrote a detailed [question on StackOverflow](https://stackoverflow.com/questions/76352457/how-to-convert-a-conda-env-yaml-file-to-a-list-of-requirements-for-a-settings-in) with my [current solution](https://stackoverflow.com/q/76352457/5623899) as well.

The general idea is that given an conda environment file `env.yml` I can run something like `conda env export -n my_env --to-pypi` and all of the dependencies and the versions get converted to their corresponding pypi format.

### Why is this needed?

Please read the detailed [question on StackOverflow](https://stackoverflow.com/questions/76352457/how-to-convert-a-conda-env-yaml-file-to-a-list-of-requirements-for-a-settings-in). It gives a more thorough breakdown. 

Briefly:
- version specifier requirements in conda are _not_ the same as `pypi`. Most notably `=` vs `==`, amongst others.
- package names for conda may not be the same for `pypi`. For example [`pytorch`][pytorch] is listed as [`torch`][pytorch pypi] for `pypi` and [`pytorch`][pytorch conda] for conda.
- the environment yaml file may have channel specifiers e.g. `conda-forge::<package-name>`

[nbdev]: https://nbdev.fast.ai/tutorials/tutorial.html
[conda yml]: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
[pytorch]: https://pytorch.org
[pytorch pypi]: https://pypi.org/project/torch/
[pytorch conda]: https://anaconda.org/pytorch/pytorch
[example env file]: https://stackoverflow.com/questions/76352457/how-to-convert-a-conda-env-yaml-file-to-a-list-of-requirements-for-a-settings-in/76352458/#example-conda-file
[problem formulation]: https://stackoverflow.com/questions/76352457/how-to-convert-a-conda-env-yaml-file-to-a-list-of-requirements-for-a-settings-in/76352458/#problem-formulation

### What should happen?

My ideal solution takes the contents of `env.yml` and exports them so I can paste them into a `settings.ini` file (or it puts it there directly).

### Additional Context

Please see my [question on StackOverflow](https://stackoverflow.com/questions/76352457/how-to-convert-a-conda-env-yaml-file-to-a-list-of-requirements-for-a-settings-in) with my [current solution](https://stackoverflow.com/q/76352457/5623899). I put a bit of effort into it :)

**Comment by dsm-72** [comment]
@travishathaway Thank you for the information. I when ahead and cleaned up the script a bit more an made it into a proper package ([pypi], [conda], [docs], [repo]). It even supports some more features :). It has a submodule `nbs/conda.ipynb` where I think I did the `conda.plugins.CondaSubcommand` correctly (although I forgot the `toml`)? Unfortunately the [dev plugin guide][dev plugin guide] was not too useful for me..., but your [envlock][envlock] package helped. 

What should I do in regards to [conda-incubator][conda-incubator]?

I'd appreciate your help!

[repo]: https://github.com/dsm-72/env2ini
[pypi]: https://pypi.org/project/env2ini/
[docs]:  https://dsm-72.github.io/env2ini/
[conda]: https://anaconda.org/dsm-72/env2ini

[dev plugin guide]: https://docs.conda.io/projects/conda/en/stable/dev-guide/plugins/index.html
[envlock]: https://github.com/travishathaway/conda-envlock
[conda-incubator]: https://github.com/conda-incubator/

**Comment by travishathaway** [comment]
@dsm-72, thanks for sharing your project with me and providing some feedback on the plugins guide.

The good news is that you don't need a `pyproject.toml` file to get this working (I think that's what you meant). I believe the piece that you are missing is adding the appropriate entry point so conda can find it.

I think adding this to your entry points in your `setup.py` file will be enough to get everything registered correctly.

```python
    entry_points={
        # ... other lines
        "conda": ["env2ini" = "env2ini.conda"]},
    }
```

When people install your package, they will see it appear under, "conda commands available from other packages:" on the `conda --help` page, and they will be able to invoke it by running `conda env2ini`.

As far as putting something on conda-incubator, we are still figuring out the process plugin authors can follow to have their projects listed there. Just to let you know, there is no need to have your project there for now, and it's probably better to host it yourself for now. I apologize for not being clear on this initially. If enough people take an interest in the project and want to help maintain it, conda-incubator could be a nice home for it in the future though.

We really appreciate you taking the time to use these still quite new plugin hooks we've been working on. Let us know if we can be of any more help.
