### ISSUE TITLE
HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>  

### ISSUE THREAD

**Issue by flamzee01** [conda/conda#12739]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

```
(base) C:\Users\BestEmpireLTD>cd avatarify-python-youtube

(base) C:\Users\BestEmpireLTD\avatarify-python-youtube>scripts\install_windows.bat
conda found
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.



EnvironmentNameNotFound: Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.


Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.


Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.


Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.


The system cannot find the file specified.
Cloning into 'fomm'...
remote: Enumerating objects: 211, done.
R
```

### Why is this needed?

conda problem

### What should happen?

i need help on this

**Comment by travishathaway** [comment]
Hi @flamzee01,

Thanks for filing this issue. We need the output of the following two commands to get more information about what is going on:

- `conda config --show channels`
-  `conda config --show-sources`

It looks like the channel you are configured to retrieve does not exist.

**Comment by MICKYGEM** [comment]
> ### Checklist
> 
> - [X] I added a descriptive title
> - [X] I searched open requests and couldn't find a duplicate
> 
> ### What is the idea?
> 
> 
> 
> (base) C:\Users\BestEmpireLTD>cd avatarify-python-youtube
> 
> 
> 
> (base) C:\Users\BestEmpireLTD\avatarify-python-youtube>scripts\install_windows.bat
> 
> conda found
> 
> Collecting package metadata (current_repodata.json): failed
> 
> 
> 
> UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>
> 
> 
> 
> The channel is not accessible or is invalid.
> 
> 
> 
> You will need to adjust your conda configuration to proceed.
> 
> Use `conda config --show channels` to view your configuration's current state,
> 
> and use `conda config --show-sources` to view config file locations.
> 
> 
> 
> 
> 
> 
> 
> EnvironmentNameNotFound: Could not find conda environment: avatarify
> 
> You can list all discoverable environments with `conda info --envs`.
> 
> 
> 
> 
> 
> Collecting package metadata (current_repodata.json): failed
> 
> 
> 
> UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>
> 
> 
> 
> The channel is not accessible or is invalid.
> 
> 
> 
> You will need to adjust your conda configuration to proceed.
> 
> Use `conda config --show channels` to view your configuration's current state,
> 
> and use `conda config --show-sources` to view config file locations.
> 
> 
> 
> 
> 
> Collecting package metadata (current_repodata.json): failed
> 
> 
> 
> UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>
> 
> 
> 
> The channel is not accessible or is invalid.
> 
> 
> 
> You will need to adjust your conda configuration to proceed.
> 
> Use `conda config --show channels` to view your configuration's current state,
> 
> and use `conda config --show-sources` to view config file locations.
> 
> 
> 
> 
> 
> Collecting package metadata (current_repodata.json): failed
> 
> 
> 
> UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel defaultscls <https://conda.anaconda.org/defaultscls>
> 
> 
> 
> The channel is not accessible or is invalid.
> 
> 
> 
> You will need to adjust your conda configuration to proceed.
> 
> Use `conda config --show channels` to view your configuration's current state,
> 
> and use `conda config --show-sources` to view config file locations.
> 
> 
> 
> 
> 
> The system cannot find the file specified.
> 
> Cloning into 'fomm'...
> 
> remote: Enumerating objects: 211, done.
> 
> R
> 
> ### Why is this needed?
> 
> conda problem
> 
> ### What should happen?
> 
> i need help on this
> 
> ### Additional Context
> 
> _No response_


Dm WhatsApp for beta instruction

‪+234 811 513 3627‬

**Comment by travishathaway** [comment]
Hi @flamzee01,

I think the problem may be with the `defaults` channel. I think it you removed that with the following command:

```
conda config --remove channels defaults
```

You might be able to get things working again. Please let me know if that is successful.
