### ISSUE TITLE
Colon in parent dir name breaks environment activation

### ISSUE THREAD

**Issue by srepmub** [conda/conda#12749]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

```
mkdir woef:waf
cd woef:waf
conda create python=3.9 --prefix=./lib
..
conda activate ./lib
which python
```
this prints /usr/bin/python for me. also running lib/bin/python directly doesn't work, and shows that sys.path at least ends up broken:

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'lib/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/srepmub/woef:waf/lib/bin/python'
  sys.base_prefix = '/home/srepmub/woef:waf/lib'
  sys.base_exec_prefix = '/home/srepmub/woef:waf/lib'
  sys.platlibdir = 'lib'
  sys.executable = '/home/srepmub/woef:waf/lib/bin/python'
  sys.prefix = '/home/srepmub/woef:waf/lib'
  sys.exec_prefix = '/home/srepmub/woef:waf/lib'
  sys.path = [
    '/home/srepmub/woef',
    'waf/lib/lib/python39.zip',
    '/home/srepmub/woef',
    'waf/lib/lib/python3.9',
    '/home/srepmub/woef',
    'waf/lib/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fcda6339740 (most recent call first):
<no Python frame>
```

**Comment by travishathaway** [comment]
Hi @srepmub,

Thanks for filing this issue. I can confirm that I have replicated this myself. The problem occurs because we update the shell's `PATH` variable when activating conda, so when there's a colon in the path name, the `PATH` cannot be set properly (the `:` character is the separation character).

I'm going to add the https://github.com/conda/conda/labels/good%20first%20issue label to this as it could be a good issue for a would-be contributor to investigate 🧐.

**Comment by HeavenEvolved** [comment]
Hi @srepmub! What should be done with this? Just throw an error if there is a colon in the dirname? I don't see a reliable way to have colons in dirname. If you have a solution in mind, I would be happy to make the changes. Kindly suggest @travishathaway 

Thanks!

**Comment by srepmub** [comment]
hiya, an error would be nicer but if the operating system supports colons in dirnames, I would expect conda to be able to deal with this..? :P
