### ISSUE TITLE
Add a `--no-plugins` option to conda for core commands

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12748]
### What's the idea?

When a plugin triggers an error, we need a way to temporarily disable all plugins so that it can be uninstalled if necessary.

### What should be done?

- [ ] Add a new option called `--no-plugins` that will be used to temporarily disable plugins (this should apply to all "[core commands](https://github.com/conda/conda/tree/main/conda/cli)").
- [ ] We should update the the error report page to mention this option.
- [ ] Write tests to ensure this behavior works as expected.

### Additional context

This is probably how we will be able to disable plugins:

- https://pluggy.readthedocs.io/en/stable/#blocking

**Comment by jezdez** [comment]
(didn't know @travishathaway had already asked @dholth about working on this)
