### ISSUE TITLE
Add pre-solve and post-solve plugin hooks

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12760]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Similar to the pre-/post-command hooks (see https://github.com/conda/conda/issues/12595), the pre-/post-solve hooks will occur directly before and after the sovler is invoked.

### Why is this needed?

This will provide a clean interface for functionality like conda-content-trust or even refactoring features like `pinned_packages`.

### What should happen?

Introduce new pre-/post-command hooks.

**Comment by travishathaway** [comment]
@kenodegard I think it would be really nice to have a specification document for this feature like we did for pre/post commands: https://github.com/conda-incubator/ceps/pull/45

**Comment by kenodegard** [comment]
Both pre- and post-solve hooks have been added in #13053

**Comment by jezdez** [comment]
w00t!
