### ISSUE TITLE
conda create --file does not understand pip file specifications

### ISSUE THREAD

**Issue by chrish42** [conda/conda#1277]
It would be nice to be able to install at least of a subset of pip requirements files via conda. Right now, as soon as the requirements file has an exact version specification, this does not work, as pip expects "==" while conda uses "=".

Is there a reason why conda could not also understand "==" for exact version specifications? This would make `conda create --file` compatible with a broader subset of pip requirements.txt files. (I am willing to work on a patch.)

**Comment by asmeurer** [comment]
conda should be understanding ==. Can you post the file you are using and your `conda info`?

**Comment by chrish42** [comment]
As far as I can see in the doc, the supported syntax is for example `conda create -n test python=2`. Trying `conda create -n test python==2` results in the following error for me:

```
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: python ==2

Did you mean one of these?

    python, ipython

You can search for this package on Binstar with

    binstar search -t conda python ==2
```

Same error with "python==2" in a text file and calling `conda create -n test --file that_file`, which (if it worked) would allow conda to work directly on pip requirements files.

Here is the output of conda info:
```
Current conda install:

             platform : osx-64
        conda version : 3.12.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : /Users/chrish/anaconda  (writable)
  default environment : /Users/chrish/anaconda
     envs directories : /Users/chrish/anaconda/envs
        package cache : /Users/chrish/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by kalefranz** [comment]
> Is there a reason why conda could not also understand "==" for exact version specifications?

Actually conda does now.
