### ISSUE TITLE
`conda init` should write to `~/.bashrc`, not `~/.bash_profile`

### ISSUE THREAD

**Issue by BEFH** [conda/conda#12787]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda init bash` writes to `~/.bash_profile`, which is only sourced for interactive sessions, as opposed to `~/.bashrc` which is sourced for all sessions. I believe this change was made after #8072, which incorrectly states the opposite.

Is there any way that could be changed back, or an option could be added to override the default? 

More info is here: https://linuxize.com/post/bashrc-vs-bash-profile/

**Comment by travishathaway** [comment]
Hi @BEFH,

Thanks for filing this feature request. You bring up a valid point. I want to leave this feature request open so that we can discuss the advantages and disadvantages of making such a change. I'm sorry, but I cannot provide a yes or no answer at this point.

**Comment by BEFH** [comment]
what would be the purpose of only making anaconda available to interactive sessions?
