### ISSUE TITLE
Avast claims that miniconda windows installers contain Win32:malware-gen

### ISSUE THREAD

**Issue by mmagnuski** [conda/conda#1279]
I am sure this is false positive, but thought I will let you know. Some potential users may be discouraged by avast threat warnings.

**Comment by asmeurer** [comment]
Thanks for reporting. I'll check it out.

**Comment by asmeurer** [comment]
I can reproduce it. Win32-malware-gen seems to be a generic Avast malware definition, so I'm not sure how to fix it. I did report it as a false positive, though.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1702
