### ISSUE TITLE
set LD_LIBRARY_PATH when activate

### ISSUE THREAD

**Issue by jinmingyi1998** [conda/conda#12800]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

when activate an env, a PATH will be set, but LD_LIBRARY_PATH doesn't.
if I install some library in this conda env, I need ld first find in `$CONDA_PREFIX/lib` instead of system default `/usr/lib:/usr/local/lib`.

If there are any other way, please tell me. I looked for something like `.bashrc` but I did not found

### Why is this needed?

Now, every time I activate a env, I have to manually `export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH`

### What should happen?

automatically set LD_LIBRARY_PATH just like conda did for PATH

**Comment by travishathaway** [comment]
Hi @jinmingyi1998,

Thanks for filing this issue. This is currently discouraged and therefore will not be adopted (more information here: https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html#shared-libraries-in-macos-and-linux)

If you want to do this yourself, you could look at setting these as environment variables on your individual environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables

**Comment by JackCaster** [comment]
> Hi @jinmingyi1998,
> 
> Thanks for filing this issue. This is currently discouraged and therefore will not be adopted (more information here: https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html#shared-libraries-in-macos-and-linux)
> 
> If you want to do this yourself, you could look at setting these as environment variables on your individual environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables

Hey @travishathaway if setting the `LD_LIBRARY_PATH` manually is discouraged, what is the recommended way of getting those library properly linked in Linux (for example).

Currently, I am facing the problem of `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found` when working in a new Conda env.

**Comment by travishathaway** [comment]
Hi @JackCaster,

I'm unable to get give a definitive answer here. I actually do not do any C++ exclusively in conda environments.

But, you may be able to find help via one of our community chats listed here:

- https://conda.org/community#chat

I hope you can find the answer you are looking for!

**Comment by malcook** [comment]
Finding I was not alone in wanting this, and having written a bash function to do just this, I thought I'd share here, maybe raise and eyebrow or two, or get some suggestions for improvement, or related war stories...

``` bash
conda_auto_ld () {
    ## PURPOSE: Contrive to create/modify 'Activation/deactivation
    ## scripts' for a conda environment to automatically set/reset
    ## LD_LIBRARY_PATH by prepending its lib directory to
    ## LD_LIBRARY_PATH.  $1 is the optional environment prefix needing
    ## these scripts, defaulting to ${CONDA_PREFIX}.
    ##
    ## ASSUMES: this function will only be run once for any installed
    ## conda environment, since it modifies any pre-existing scripts.
    ##
    ## AUTHOR: malcolm_cook@stowers.org
    conda_prefix=${1-${CONDA_PREFIX:?must be set if not supplied as parameter to conda_auto_ld}}
    [ -w ${conda_prefix} ] || 
	{ printf 'ERROR: conda_prefix [%s] must exist and be writable (in conda_auto_ld)\n' ${conda_prefix}; return;  }
    [ -d ${conda_prefix}/lib ] || 
	{ printf 'ERROR: conda_prefix [%s] lacks required /lib subdirectory (in conda_auto_ld)\n' ${conda_prefix}; return;  }
    condalib=${conda_prefix}/lib
    mkdir -p ${conda_prefix}/etc/conda/{de,}activate.d # which may (not?) already exist!
    printf '#ADDED BY: conda_auto_ld:\nexport LD_LIBRARY_PATH='${condalib}'${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\n' >> \
	   ${conda_prefix}/etc/conda/activate.d/env_vars.sh
    printf '#ADDED BY: conda_auto_ld:\nLD_LIBRARY_PATH=${LD_LIBRARY_PATH/'${condalib@Q}'/}\nLD_LIBRARY_PATH=${LD_LIBRARY_PATH#:}\n' >> \
	   ${conda_prefix}/etc/conda/deactivate.d/env_vars.sh
}
```

WHY?: It implements the request raised in these issues:

 - https://github.com/conda/conda/issues/12800
 - https://github.com/conda/conda-build/issues/50
 - https://github.com/conda/conda/issues/308

In those issues, the request to provide for this generically, across
the board, for all conda environments, was considered and rejected and
in general was discouraged; however doing so on a case-by-case basis
was suggested as reasonable.  Doing so may in turn provide a concise
approach to resolving issues issues such as:

 - https://github.com/rstudio/reticulate/issues/1285
 - https://github.com/rstudio/reticulate/issues/1467

WHY NOT?: "Including conda environment paths in LD_LIBRARY_PATH or
DYLD_LIBRARY_PATH is not recommended" 
(https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html#shared-libraries-in-macos-and-linux)

**Comment by jucor** [comment]
Issue [rstudio/reticulate#1285 ](https://github.com/rstudio/reticulate/issues/1285) is *exactly* what brings me here too. Thanks @malcook !

**Comment by ethanc8** [comment]
@travishathaway Why does conda-build use $ORIGIN/@loader_path instead of setting LD_LIBRARY_PATH when activating the environment? Setting LD_LIBRARY_PATH is the standard way to load libraries from outside of the system-defined paths on Linux.
