### ISSUE TITLE
Conda environment stuck in portrait mode from Mac Video Effects

### ISSUE THREAD

**Issue by ayushpai** [conda/conda#12805]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm experiencing an unexpected issue while using OpenCV in a Conda environment on my Mac. When I run my OpenCV code in this environment, my video output is blurred as if a "portrait" mode (background blur) is enabled. This happens even when the camera effects on my Mac are turned off. The blurring issue does not occur when running the same code using a regular Python environment outside of Conda.

This problem started after I had used the Mac's video background blur effect for a video call, but persisted in the Conda environment even after turning the effect off. The effect does not persist when using the regular Python interpreter, only in the Conda environment.

I have stripped down my code and just opening my camera with OpenCV, and the issue persists.

Here is the code (although this should not affect it):

  
    cap = cv2.VideoCapture(0)

    while True:
        ret, frame = cap.read()

        cv2.imshow('Webcam', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

I have tried various troubleshooting steps, including creating a new Conda environment, updating all packages, rebooting my system, and checking for interferences from other applications, but none of these have solved the issue.

Does anyone know why this might be happening and how I can prevent the background blur when using OpenCV in a Conda environment?

Thank you for your help.

### Conda Info

```shell
active environment : exercise-tracking
    active env location : /Users/ayushpai/miniconda3/envs/exercise-tracking
            shell level : 2
       user config file : /Users/ayushpai/.condarc
 populated config files : 
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/ayushpai/miniconda3  (writable)
      conda av data dir : /Users/ayushpai/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ayushpai/miniconda3/pkgs
                          /Users/ayushpai/.conda/pkgs
       envs directories : /Users/ayushpai/miniconda3/envs
                          /Users/ayushpai/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Darwin/22.5.0 OSX/13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
n/a
```

### Conda list

```shell
# packages in environment at /Users/ayushpai/miniconda3/envs/exercise-tracking:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h620ffc9_4    defaults
ca-certificates           2023.05.30           hca03da5_0    defaults
libffi                    3.4.4                hca03da5_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
numpy                     1.24.3                   pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   3.0.8                h1a28f6b_0    defaults
pip                       23.1.2          py311hca03da5_0    defaults
python                    3.11.3               hb885b13_1    defaults
readline                  8.2                  h1a28f6b_0    defaults
setuptools                67.8.0          py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
wheel                     0.38.4          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
```

**Comment by travishathaway** [comment]
Hi @ayushpai,

We appreciate you filing this issue here, but there's really no guidance we can provide in regards to this issue. You will have to inquire with the authors of the library that are manipulating the video settings on your computer.

This issue queue is only for problems encountered while running conda itself and not for any of the libraries that you may install with it.

With this in mind, I will now be closing this issue as "off-topic", but I wish you luck in trying to solve this problem.
