### ISSUE TITLE
Conda removed everything related to Anaconda

### ISSUE THREAD

**Issue by munael** [conda/conda#12801]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

- Honestly not a clue.
- I had anaconda installed.
- A number of environments including one with `Python 3.10`.
- At some point a month or so ago I tried to update `conda` in the `base` env in order to be able to use the `libmamba` resolver.
- Today, I find that neither `conda` nor `python` are recognized in the terminal.
- VSCode can't see any of my envs.
- I check the folders and under `AppData/Local/Continuum/anaconda3` almost nothing remains (just some empty folders).
- The only remaining thing is this installation entry (image appended).
- The installation was working _fine_ only 3 days ago. I did _**not**_ try to do any updates meanwhile.
- Running on Windows 11 22H2 `22621.1702`.
- Anaconda version: `Anaconda3 py310_2023.03-O (Python 3.109 64-bit)`.
  - This is _not_ the version I had had installed. I had my installation since 2020 or so.
![image](https://github.com/conda/conda/assets/5769148/bad0399b-b3d4-4cdf-b834-551eadb42b4d)

### Conda Info

```shell
N/A
No conda exe
```

### Conda Config

```shell
N/A
No conda exe
```

### Conda list

```shell
N/A
No conda exe
```

### Additional Context

Please let me know ASAP if there may be any logs living somewhere that I can share with you before I remove the remaining stuff and install anew.

**Comment by travishathaway** [comment]
Hi @munael,

Thanks for filing this issue. When you installed Anaconda, did you specifically choose `AppData/Local/Continuum/anaconda3` as the installation location? If not, there may be additional files in your `C:\Users\<username>\anaconda3` location. That's the default location (at least for recent installers).

Also, is this a personal computer or does it belong to a network? (e.g. corporate or university).

I don't have enough information to give you any answers now as to what happen, but I could recommend trying to reinstall Anaconda at this point.

**Comment by shivamMg** [comment]
+1 for this issue. My system: Windows 11 Enterprise 64-bit

`conda` was working fine a couple of hours ago. Now:
- Anaconda3 directory at `C:\Users\<username>\` isn't there anymore.
- Can't find my envs: `conda env list` just returns base.  
- From Installed apps I see new version of Anaconda3 even though I didn't trigger an install/update.
![image](https://github.com/conda/conda/assets/7882752/44324e95-571e-4c0b-ab8e-60c983908069)

**Comment by kenodegard** [comment]
@munael do you have a `%HOME%\.conda\environments.txt` file? if so can you provide the contents?

@shivamMg since you have a working `conda` can you run the following and provide the outputs?

```
conda info
conda config --show-sources
conda list --show-channel-urls
```

**Comment by munael** [comment]
@kenodegard 

`.conda/environments.txt` has only the `AppData\Local\anaconda3` path.

But that path does _not_ have any of the envs I had before.

The other path, under `AppData/Continuum/anaconda3` had all the envs I was using before.

@travishathaway 

And I had not specified it manually during installation. It was just there.

It was an old installation, from around 2020 maybe?

The machine is under a corporate domain, but the anaconda installation was done by the user. No policies for it.

**Comment by munael** [comment]
I just got another automatic update today and needed to tell you about it.

Everything `anaconda` yeeted itself out of my machine.

I had to use that word. The situation is so bizarre I'm cry-laughing :'D

Like, I lost my environments, which is _really bad_ but survivable.

So for next steps:
1. Do I just reinstall it? How to prevent that from happening again?
   - I can try disabling the automatic updates next time. But they had _never_ activated even once before so that was already a surprise function.
2. How do I make sure my environments are safe from then on?

**Comment by kenodegard** [comment]
conda does **not** run background tasks and doesn't auto update in this sense, auto update for conda means that when running commands like `conda update -n base --all` the conda package is **eligible** to be updated

so unless you ran a conda command, conda is unlikely to have caused this

**Comment by munael** [comment]
@kenodegard 
> conda does **not** run background tasks and doesn't auto update in this sense, auto update for conda means that when running commands like `conda update -n base --all` the conda package is **eligible** to be updated
> 
> so unless you ran a conda command, conda is unlikely to have caused this

Anaconda then?

I saw a box from the installer flash when it happened. Don't know what it said, but it had the green circle logo.

Should this Issue be copied elsewhere?

**Comment by shivamMg** [comment]
@kenodegard here: https://gist.github.com/shivamMg/b1de7d04c0d2073cb48b8de55992c2ef

**Comment by travishathaway** [comment]
Hi @munael,

I would first recommend that you contact your corporate IT support to further debug what is going. As @kenodegard said before, there are no background jobs running that would be causing this. At this point, I very strongly suspect a policy being enacted on your computer that may be removing unauthorized software being installed (i.e. Anaconda Distribution). As the managers of this computer, I would hope that your IT department would be able to give you all the answers you need regarding the installation and usage the Anaconda Distribution.

For further reference, here is the documentation for installing Anaconda on Windows:

- https://docs.anaconda.com/free/anaconda/install/windows/

Also, after having debugged this with your IT department, if you truly believe this to be a problem with the installer itself, we encourage you to file an issue at the following GitHub project:

- https://github.com/ContinuumIO/anaconda-issues/issues

This is where all issues with the Anaconda Distribution installer belong.

I wish you luck in debugging this issue and hope that you and your IT department can figure out what is going on with your computer.

**Comment by travishathaway** [comment]
Hi @shivamMg,

I noticed that you are using the "Enterprise" version of Windows. This also usually means that you are on a corporate or university network (please correct me if I am wrong).

In this case, I would also ask you to contact your local IT department to ask them about the best way to install and use Anaconda Distribution.

One piece of advice I can give you is that installing Anaconda to `C:\Users\smamgain\AppData\Local\anaconda3` is not a good idea and is probably causing these environment losses. This folder is typically meant for storing application cache. I can't advise on the best way to install Anaconda Distribution. Only your IT department can help you here.

I also wish you luck in figuring this out and hope this answer helps others with similar problems.
