### ISSUE TITLE
unexpected error when NO conda environment is active and issuing comand 'conda rename -n old_env -d new_env'

### ISSUE THREAD

**Issue by PeterBrummer** [conda/conda#12825]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I use conda under Ubuntu 22.4.
Recently I decided to rename one of my exiting conda environments.
But before I issueed the proposed command in the ubuntu terminal I deactivated any conda environment 
in the terminal session by isuuing the comand 'conda deactivate' so often that no environment information was seen at the beginning of the command line prompt.
Then I invoked the command:
'conda rename -n <<old_env>> -d <<new_env>>'
where <<old_env>> stands for a name of an existing conda environment on my system and <<new_name>> stands for the new name for that existing conda environment.

The invoked command lead to:
'An unexpected error has occurred....'

preceded by the stack trace:
```
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/main_rename.py", line 53, in execute
        source = validate_src(args.name, args.prefix)
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/main_rename.py", line 28, in validate_src
        if common.is_active_prefix(prefix):
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/common.py", line 87, in is_active_prefix
        paths_equal(prefix, context.active_prefix)
      File "/home/peter/anaconda3/lib/python3.10/site-packages/conda/common/path.py", line 57, in paths_equal
        return abspath(path1) == abspath(path2)
      File "/home/peter/anaconda3/lib/python3.10/posixpath.py", line 379, in abspath
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

``` 

I searched for the cause and found that in the case when no conda environment is active 
context.active_prefix is equal to None. 
Therefore when function "def is_active_prefix(prefix)" is called it leads 
at line 87 
in the file /home/peter/anaconda3/lib/python3.10/site-packages/conda/cli/common.py
to a call of 'paths_equal(prefix, context.active_prefix)" with  a "None"-Value for the second argument.
But if path2 in the function 'paths_equal(path1, path2)' is None then
we get the type erro at line 57 in path.py, i.e. by calling abspath(path2).

There is more than one way to get rid of this annoying error.
I recommend to add the expression 'common.is_active_prefix(prefix) is not None and(...)' to the return as follows

```python
def is_active_prefix(prefix):
    """
    Determines whether the args we pass in are pointing to the active prefix.
    Can be used a validation step to make sure operations are not being
    performed on the active prefix.
    """
    return (
        context.active_prefixi is not None and ( paths_equal(prefix, context.active_prefix)
        # normcasing our prefix check for Windows, for case insensitivity
        or normcase(prefix) == normcase(env_name(context.active_prefix)))
    )

``` 
Enjoy Coding!

**Comment by travishathaway** [comment]
Hi @PeterBrummer,

I just wanted to follow up on this bug report. I really appreciate how you were able to dig into the code and propose a solution. The maintainers will organize this amongst our other open issues and address it accordingly.

In the meantime, we also encourage others to open their own pull requests to address this. We are always happy to review new contributions.
