### ISSUE TITLE
Add --yes / -y flag to `conda env create` command

### ISSUE THREAD

**Issue by ktaletsk** [conda/conda#12837]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In my workflow I manually create conda environment files as described [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually), i.e.

```
name: stats2
channels:
  - javascript
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - conda-forge::numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - pip
  - pip:
    - Flask-Testing
```
and then build them in CI inside of the container using `conda env create --prefix <path> --file environment.yaml`

However, I recently encountered a package with pre-link script, requiring me to agree to license terms:
```
The following PRELINK MESSAGES are INCLUDED:


  File nvcomp.txt:

  By downloading and using the libcudf conda package, you accept the terms
  and conditions of the NVIDIA NVCOMP Software License Agreement:
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt


Proceed ([y]/n)? 
```

I have to manually type `y` to continue and this would not work in CI. 

My suggestion is to add --yes / -y flag to `conda env create` command, to have the similar functionality as `conda create` command

### Why is this needed?

Anyone building conda environments in CI that include license agreements

### What should happen?

New command flag should be added:

`conda env create ... -y` should automatically agree and skip and prompts

### Additional Context

I am able to achieve the desired effect by using `conda create -c <channels> <package1> ... <packageN> -y`, but I 
1. Lose ability to install pip packages together with conda ones
2. Have to have track package versions in the long string as opposed to nicely formatted yaml file

**Comment by travishathaway** [comment]
Hi @ktaletsk,

Thanks for filing this issue. I have some good news! There is actually already an option that does this, `--force`.

You can also already use `--yes` too, but it is currently not documented on the help page. I will open a separate issue to make sure it appears there though.

In the meantime I will be closing this feature request as there is nothing to do. Our apologies if the documentation was not clear enough 😅.

**Comment by travishathaway** [comment]
Quick correction to my response: the the `--yes` option is already there in the latest release of conda.
