### ISSUE TITLE
`conda activate` broken in fish shell (in `native_path_to_unix`)

### ISSUE THREAD

**Issue by mdealencar** [conda/conda#12836]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda activate` fails. MSYS2, fish shell. It used to work just fine on that same system up until a month ago.

Cause of error: `native_path_to_unix(paths)` is being called with an empty string in argument `paths` and can't handle it.

As a workaround, I changed this code inside [`native_path_to_unix(paths)`](https://github.com/conda/conda/blob/26c74a12042bf035b76ed8186c3dddabd1f10606/conda/activate.py#L826):
```
if paths is None:
    return None
```
to that:
```
if not paths:  # this will be true for both None and ''
    return ''
```

Additional info: the code fails on another place if `native_path_to_unix` returns `None`, that's why my workaround returns `''`. Does it make sense at all to return `None`?

[ERROR_REPORT_native_path_to_unix.txt](https://github.com/conda/conda/files/11898703/ERROR_REPORT_native_path_to_unix.txt)

### Conda Config

```shell
==> C:\Users\theuser\.condarc <==
auto_activate_base: False
channel_priority: strict
channels:
  - conda-forge
  - defaults
  - intel
```

**Comment by travishathaway** [comment]
Hi @mdealencar,

Thanks for reporting this bug. We recently did some work on this on the following issue:

- https://github.com/conda/conda/issues/12626

I'm not sure if the changes we recently introduced triggered this or not.

Regardless, I think your change may be valid. I was looking around the code that calls that function and found at least one potential latent bug:

https://github.com/conda/conda/blob/26c74a12042bf035b76ed8186c3dddabd1f10606/conda/activate.py#L645-L648

(a conversion from `None` to `list` would cause that method to fail)

We'll go ahead and put this in our backlog and prioritize accordingly, but if you or anyone else would like to submit your own pull request, feel free to do so. We'll be happy to review it.

**Comment by travishathaway** [comment]
Hi @mdealencar,

I just wanted to give you an update on this. We have just merged the following pull request which will fix your problem:

- https://github.com/conda/conda/pull/12880

This will be in an upcoming patch release for conda, so please keep an eye on when we release that (should be soon). In the meantime, I will now be closing this issue.

Thanks again for reporting this issue.
