### ISSUE TITLE
add_pip_dependency

### ISSUE THREAD

**Issue by orodbhen** [conda/conda#1283]
I'm compiliing a custom version of Python and putting it in an offline conda repo. In the code for "conda index" it checks if the unknown flag is set, and if it is pip is added as a dependency. What does the unknown flag mean and why does it need this? There's no documentation in the code explaining the reason for this.

**Comment by ilanschnell** [comment]
I'm not sure which piece of code you are referring to.  Do you mean the "conda index" command?  This would be part of the "conda-build" project: https://github.com/conda/conda-build
