### ISSUE TITLE
conda update hint

### ISSUE THREAD

**Issue by luopuya** [conda/conda#1284]
Hi, I try to update all packages but meet unsatisfiable clauses.
I find it hard to understand the hint.

does it means that I must downgrade the numpy ?
(My default Python is 2.7, and create Python 3.3, this is the hint after activate Python 3)

>
numpy-1.8.1-py27_0 => not numpy-1.9.2-py33_0
numpy-1.7.0-py27_0 => not numpy-1.9.0-py33_0
numpy-1.8.2-py27_0 => not numpy-1.9.1-py27_0
numpy-1.7.0-py33_0 => not numpy-1.9.0-py33_0
numpy-1.8.2-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
python-3.3.4-0 => not python-3.4.0-0
python-3.3.5-1 => not python-3.4.1-2
numpy-1.7.1-py27_0 => not numpy-1.9.0-py33_p0
python-3.3.5-0 => not python-3.4.1-2
pykit-0.1.0-np18py27_2 => numpy-1.8.0-py26_0 or numpy-1.8.0-py26_p0 or numpy-1.8.0-py27_0 or numpy-1.8.0-py27_p0 or numpy-1.8.0-py33_0 or numpy-1.8.0-py33_p0 or numpy-1.8.1-py26_0 or numpy-1.8.1-py26_p0 or numpy-1.8.1-py27_0 or numpy-1.8.1-py27_p0 or numpy-1.8.1-py33_0 or numpy-1.8.1-py33_p0 or numpy-1.8.1-py34_0 or numpy-1.8.1-py34_p0 or numpy-1.8.2-py26_0 or numpy-1.8.2-py26_p0 or numpy-1.8.2-py27_0 or numpy-1.8.2-py27_p0 or numpy-1.8.2-py33_0 or numpy-1.8.2-py33_p0 or numpy-1.8.2-py34_0 or numpy-1.8.2-py34_p0
numpy-1.8.2-py33_0 => not numpy-1.9.0-py33_p0
python-3.3.0-4 => not python-3.4.1-1
numpy-1.7.1-py33_2 => not numpy-1.9.1-py27_0
numpy-1.8.1-py33_0 => not numpy-1.9.0-py27_0
python-3.3.2-0 => not python-3.4.2-0
numpy-1.7.1-py33_0 => not numpy-1.9.0-py33_0
python-2.6.8-5 => not python-3.3.0-4
numpy-1.8.2-py27_0 => not numpy-1.9.0-py33_0
numpy-1.8.1-py27_0 => not numpy-1.9.1-py33_0
numpy-1.7.0-py33_0 => not numpy-1.9.1-py27_0
numpy-1.8.0-py27_0 => not numpy-1.9.2-py33_0
python-3.3.0-4 => not python-3.4.3-0
numpy-1.7.1-py33_1 => not numpy-1.9.2-py33_0
numpy-1.8.2-py27_0 => not numpy-1.9.2-py27_0
numpy-1.8.0-py33_0 => not numpy-1.9.2-py33_0
python-2.6.8-5 => not python-3.3.4-0
numpy-1.7.1-py27_1 => not numpy-1.9.0-py27_0
numpy-1.7.1-py33_2 => not numpy-1.9.0-py27_0
numpy-1.7.1-py27_3 => not numpy-1.9.2-py33_0
numpy-1.8.2-py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
not numpy-1.9.2-py27_p0
numpy-1.8.1-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.1-py33_2 => not numpy-1.9.2-py27_0
numpy-1.8.2-py27_0 => not numpy-1.9.2-py34_0
numpy-1.7.1-py27_3 => not numpy-1.9.0-py33_p0
numpy-1.8.1-py33_0 => not numpy-1.9.1-py27_0
numpy-1.7.0-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
seaborn-0.5.0-np19py33_0 => numpy-1.9.0-py26_0 or numpy-1.9.0-py26_p0 or numpy-1.9.0-py27_0 or numpy-1.9.0-py27_p0 or numpy-1.9.0-py33_0 or numpy-1.9.0-py33_p0 or numpy-1.9.0-py34_0 or numpy-1.9.0-py34_p0 or numpy-1.9.1-py26_0 or numpy-1.9.1-py26_p0 or numpy-1.9.1-py27_0 or numpy-1.9.1-py27_p0 or numpy-1.9.1-py33_0 or numpy-1.9.1-py33_p0 or numpy-1.9.1-py34_0 or numpy-1.9.1-py34_p0 or numpy-1.9.2-py26_0 or numpy-1.9.2-py26_p0 or numpy-1.9.2-py27_0 or numpy-1.9.2-py27_p0 or numpy-1.9.2-py33_0 or numpy-1.9.2-py33_p0 or numpy-1.9.2-py34_0 or numpy-1.9.2-py34_p0
numpy-1.7.1-py27_0 => not numpy-1.9.0-py33_0
python-2.6.8-6 => not python-3.3.0-4
seaborn-0.5.1-np19py33_0 => numpy-1.9.0-py26_0 or numpy-1.9.0-py26_p0 or numpy-1.9.0-py27_0 or numpy-1.9.0-py27_p0 or numpy-1.9.0-py33_0 or numpy-1.9.0-py33_p0 or numpy-1.9.0-py34_0 or numpy-1.9.0-py34_p0 or numpy-1.9.1-py26_0 or numpy-1.9.1-py26_p0 or numpy-1.9.1-py27_0 or numpy-1.9.1-py27_p0 or numpy-1.9.1-py33_0 or numpy-1.9.1-py33_p0 or numpy-1.9.1-py34_0 or numpy-1.9.1-py34_p0 or numpy-1.9.2-py26_0 or numpy-1.9.2-py26_p0 or numpy-1.9.2-py27_0 or numpy-1.9.2-py27_p0 or numpy-1.9.2-py33_0 or numpy-1.9.2-py33_p0 or numpy-1.9.2-py34_0 or numpy-1.9.2-py34_p0
python-3.3.1-0 => not python-3.4.2-0
not numpy-1.7.1-py33_p1
pykit-0.1.0-np17py33_1 => numpy-1.7.0-py26_0 or numpy-1.7.0-py27_0 or numpy-1.7.0-py33_0 or numpy-1.7.1-py26_0 or numpy-1.7.1-py26_1 or numpy-1.7.1-py26_2 or numpy-1.7.1-py26_3 or numpy-1.7.1-py26_p0 or numpy-1.7.1-py26_p1 or numpy-1.7.1-py26_p2 or numpy-1.7.1-py26_p3 or numpy-1.7.1-py27_0 or numpy-1.7.1-py27_1 or numpy-1.7.1-py27_2 or numpy-1.7.1-py27_3 or numpy-1.7.1-py27_p0 or numpy-1.7.1-py27_p1 or numpy-1.7.1-py27_p2 or numpy-1.7.1-py27_p3 or numpy-1.7.1-py33_0 or numpy-1.7.1-py33_1 or numpy-1.7.1-py33_2 or numpy-1.7.1-py33_3 or numpy-1.7.1-py33_p0 or numpy-1.7.1-py33_p1 or numpy-1.7.1-py33_p2 or numpy-1.7.1-py33_p3
python-2.6.9-1 => not python-3.3.1-0
not numpy-1.7.1-py27_p2
numpy-1.8.1-py27_0 => not numpy-1.9.0-py33_0
numpy-1.8.0-py27_0 => not numpy-1.9.1-py33_0
numpy-1.7.1-py33_2 => not numpy-1.9.2-py34_0
python-3.3.2-0 => not python-3.4.0-0
numpy-1.7.1-py33_0 => not numpy-1.9.1-py33_0
numpy-1.7.1-py27_1 => not numpy-1.9.1-py27_0
python-3.3.5-1 => not python-3.4.0-0
python-2.6.9-1 => not python-3.3.5-0
numpy-1.7.0-py33_0 => not numpy-1.9.1-py33_0
pykit-0.2.0-np18py33_0 => numpy-1.8.0-py26_0 or numpy-1.8.0-py26_p0 or numpy-1.8.0-py27_0 or numpy-1.8.0-py27_p0 or numpy-1.8.0-py33_0 or numpy-1.8.0-py33_p0 or numpy-1.8.1-py26_0 or numpy-1.8.1-py26_p0 or numpy-1.8.1-py27_0 or numpy-1.8.1-py27_p0 or numpy-1.8.1-py33_0 or numpy-1.8.1-py33_p0 or numpy-1.8.1-py34_0 or numpy-1.8.1-py34_p0 or numpy-1.8.2-py26_0 or numpy-1.8.2-py26_p0 or numpy-1.8.2-py27_0 or numpy-1.8.2-py27_p0 or numpy-1.8.2-py33_0 or numpy-1.8.2-py33_p0 or numpy-1.8.2-py34_0 or numpy-1.8.2-py34_p0
python-2.6.8-6 => not python-3.3.5-1
python-2.6.8-6 => not python-3.3.4-0
numpy-1.8.1-py33_0 => not numpy-1.9.2-py27_0
numpy-1.8.0-py33_0 => not numpy-1.9.2-py27_0
numpy-1.7.1-py33_3 => not numpy-1.9.0-py33_p0
python-2.6.9-0 => not python-3.3.3-0
python-3.3.3-0 => not python-3.4.1-1
python-3.3.4-0 => not python-3.4.2-1
numpy-1.7.1-py27_1 => not numpy-1.9.2-py34_0
pykit-0.1.0-np17py33_0 => numpy-1.7.0-py26_0 or numpy-1.7.0-py27_0 or numpy-1.7.0-py33_0 or numpy-1.7.1-py26_0 or numpy-1.7.1-py26_1 or numpy-1.7.1-py26_2 or numpy-1.7.1-py26_3 or numpy-1.7.1-py26_p0 or numpy-1.7.1-py26_p1 or numpy-1.7.1-py26_p2 or numpy-1.7.1-py26_p3 or numpy-1.7.1-py27_0 or numpy-1.7.1-py27_1 or numpy-1.7.1-py27_2 or numpy-1.7.1-py27_3 or numpy-1.7.1-py27_p0 or numpy-1.7.1-py27_p1 or numpy-1.7.1-py27_p2 or numpy-1.7.1-py27_p3 or numpy-1.7.1-py33_0 or numpy-1.7.1-py33_1 or numpy-1.7.1-py33_2 or numpy-1.7.1-py33_3 or numpy-1.7.1-py33_p0 or numpy-1.7.1-py33_p1 or numpy-1.7.1-py33_p2 or numpy-1.7.1-py33_p3
numpy-1.7.0-py27_0 => not numpy-1.9.1-py33_0
python-2.6.8-6 => not python-3.3.5-0
numpy-1.8.1-py33_0 => not numpy-1.9.2-py34_0
not numpy-1.8.2-py27_p0
numpy-1.7.1-py26_p0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
not numpy-1.7.1-py33_p0
python-3.3.3-0 => not python-3.4.3-0
not numpy-1.8.1-py27_p0
python-3.3.4-0 => not python-3.4.1-0
numpy-1.7.1-py27_1 => not numpy-1.9.2-py27_0
numpy-1.7.1-py27_3 => not numpy-1.9.0-py33_0
python-3.3.5-0 => not python-3.4.1-1
python-3.3.0-4 => not python-3.4.1-2
not numpy-1.9.0-py27_p0
numpy-1.7.1-py26_p3 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.0-py33_0 => not numpy-1.9.0-py33_p0
python-3.3.2-0 => not python-3.4.1-0
numpy-1.7.1-py33_p2 => not numpy-1.9.0-py27_0
numpy-1.7.1-py26_1 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
not numpy-1.7.1-py27_p0
python-3.3.5-1 => not python-3.4.2-0
python-3.3.5-0 => not python-3.4.3-0
numpy-1.7.0-py27_0 => not numpy-1.9.2-py33_0
numpy-1.7.1-py27_0 => not numpy-1.9.1-py33_0
not numpy-1.9.1-py27_p0
numpy-1.8.2-py33_0 => not numpy-1.9.2-py27_0
python-3.3.2-0 => not python-3.4.2-1
numpy-1.7.1-py33_1 => not numpy-1.9.1-py33_0
python-3.3.1-0 => not python-3.4.0-0
python-2.6.8-5 => not python-3.3.1-0
numpy-1.7.1-py27_2 => not numpy-1.9.2-py27_0
numpy-1.7.1-py27_2 => not numpy-1.9.0-py27_0
numpy-1.8.2-py33_0 => not numpy-1.9.2-py34_0
seaborn-0.5.1-np19py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
pykit-0.1.0-np17py27_0 => numpy-1.7.0-py26_0 or numpy-1.7.0-py27_0 or numpy-1.7.0-py33_0 or numpy-1.7.1-py26_0 or numpy-1.7.1-py26_1 or numpy-1.7.1-py26_2 or numpy-1.7.1-py26_3 or numpy-1.7.1-py26_p0 or numpy-1.7.1-py26_p1 or numpy-1.7.1-py26_p2 or numpy-1.7.1-py26_p3 or numpy-1.7.1-py27_0 or numpy-1.7.1-py27_1 or numpy-1.7.1-py27_2 or numpy-1.7.1-py27_3 or numpy-1.7.1-py27_p0 or numpy-1.7.1-py27_p1 or numpy-1.7.1-py27_p2 or numpy-1.7.1-py27_p3 or numpy-1.7.1-py33_0 or numpy-1.7.1-py33_1 or numpy-1.7.1-py33_2 or numpy-1.7.1-py33_3 or numpy-1.7.1-py33_p0 or numpy-1.7.1-py33_p1 or numpy-1.7.1-py33_p2 or numpy-1.7.1-py33_p3
numpy-1.8.1-py33_0 => not numpy-1.9.0-py33_p0
numpy-1.7.1-py33_3 => not numpy-1.9.2-py27_0
python-2.6.8-5 => not python-3.3.5-0
not numpy-1.9.2-py26_p0
numpy-1.7.1-py33_1 => not numpy-1.9.0-py33_0
numpy-1.7.1-py27_2 => not numpy-1.9.2-py34_0
pykit-0.1.0-np17py26_0 or pykit-0.1.0-np17py26_1 or pykit-0.1.0-np17py27_0 or pykit-0.1.0-np17py27_1 or pykit-0.1.0-np17py33_0 or pykit-0.1.0-np17py33_1 or pykit-0.1.0-np18py26_2 or pykit-0.1.0-np18py27_2 or pykit-0.1.0-np18py33_2 or pykit-0.2.0-np18py26_0 or pykit-0.2.0-np18py27_0 or pykit-0.2.0-np18py33_0 or pykit-0.2.0-np18py34_0
python-2.6.9-0 => not python-3.3.1-0
numpy-1.7.1-py33_1 => not numpy-1.9.1-py27_0
python-2.6.8-6 => not python-3.3.3-0
numpy-1.8.2-py33_0 => not numpy-1.9.1-py27_0
numpy-1.7.1-py33_p2 => not numpy-1.9.2-py34_0
not numpy-1.7.1-py27_p3
python-3.3.1-0 => not python-3.4.1-2
numpy-1.7.1-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
pykit-0.1.0-np18py26_2 => numpy-1.8.0-py26_0 or numpy-1.8.0-py26_p0 or numpy-1.8.0-py27_0 or numpy-1.8.0-py27_p0 or numpy-1.8.0-py33_0 or numpy-1.8.0-py33_p0 or numpy-1.8.1-py26_0 or numpy-1.8.1-py26_p0 or numpy-1.8.1-py27_0 or numpy-1.8.1-py27_p0 or numpy-1.8.1-py33_0 or numpy-1.8.1-py33_p0 or numpy-1.8.1-py34_0 or numpy-1.8.1-py34_p0 or numpy-1.8.2-py26_0 or numpy-1.8.2-py26_p0 or numpy-1.8.2-py27_0 or numpy-1.8.2-py27_p0 or numpy-1.8.2-py33_0 or numpy-1.8.2-py33_p0 or numpy-1.8.2-py34_0 or numpy-1.8.2-py34_p0
numpy-1.7.1-py33_0 => not numpy-1.9.2-py27_0
numpy-1.7.1-py27_0 => not numpy-1.9.2-py27_0
numpy-1.7.1-py27_2 => not numpy-1.9.1-py27_0
numpy-1.7.1-py33_2 => not numpy-1.9.0-py33_p0
python-2.6.9-1 => not python-3.3.0-4
numpy-1.7.1-py33_3 => not numpy-1.9.1-py33_0
numpy-1.7.1-py27_3 => not numpy-1.9.0-py27_0
numpy-1.7.1-py33_p2 => not numpy-1.9.2-py27_0
numpy-1.8.0-py33_0 => not numpy-1.9.0-py27_0
python-2.6.9-0 => not python-3.3.4-0
not numpy-1.7.1-py33_p3
not numpy-1.9.1-py26_p0
numpy-1.7.1-py27_3 => not numpy-1.9.2-py27_0
python-2.6.9-1 => not python-3.3.4-0
numpy-1.8.1-py27_0 => not numpy-1.9.2-py27_0
numpy-1.7.1-py26_3 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.1-py27_0 => not numpy-1.9.0-py27_0
python-3.3.3-0 => not python-3.4.1-0
python-3.3.4-0 => not python-3.4.3-0
python-3.3.5-1 => not python-3.4.2-1
numpy-1.8.1-py27_0 => not numpy-1.9.2-py34_0
numpy-1.7.1-py33_p2 => not numpy-1.9.1-py27_0
numpy-1.9.0-py26_p0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.1-py33_3 => not numpy-1.9.0-py27_0
python-3.3.3-0 => not python-3.4.2-1
numpy-1.7.0-py33_0 => not numpy-1.9.0-py27_0
numpy-1.7.1-py33_p2 => not numpy-1.9.0-py33_p0
numpy-1.7.1-py33_0 => not numpy-1.9.0-py27_0
pykit-0.1.0-np17py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
python-3.3.4-0 => not python-3.4.1-1
python-3.3.5-1 => not python-3.4.1-0
python-3.3.5-0 => not python-3.4.1-0
numpy-1.8.2-py27_0 => not numpy-1.9.0-py27_0
numpy-1.8.0-py26_p0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.8.0-py33_0 => not numpy-1.9.1-py33_0
numpy-1.8.1-py27_0 => not numpy-1.9.1-py27_0
python-3.3.0-4 => not python-3.4.2-0
python-3.3.2-0 => not python-3.4.1-1
python-3.3.5-0 => not python-3.4.2-1
numpy-1.7.1-py27_3 => not numpy-1.9.1-py33_0
seaborn-0.5.1-np19py27_0 => numpy-1.9.0-py26_0 or numpy-1.9.0-py26_p0 or numpy-1.9.0-py27_0 or numpy-1.9.0-py27_p0 or numpy-1.9.0-py33_0 or numpy-1.9.0-py33_p0 or numpy-1.9.0-py34_0 or numpy-1.9.0-py34_p0 or numpy-1.9.1-py26_0 or numpy-1.9.1-py26_p0 or numpy-1.9.1-py27_0 or numpy-1.9.1-py27_p0 or numpy-1.9.1-py33_0 or numpy-1.9.1-py33_p0 or numpy-1.9.1-py34_0 or numpy-1.9.1-py34_p0 or numpy-1.9.2-py26_0 or numpy-1.9.2-py26_p0 or numpy-1.9.2-py27_0 or numpy-1.9.2-py27_p0 or numpy-1.9.2-py33_0 or numpy-1.9.2-py33_p0 or numpy-1.9.2-py34_0 or numpy-1.9.2-py34_p0
numpy-1.7.1-py27_0 => not numpy-1.9.1-py27_0
numpy-1.8.0-py27_0 => not numpy-1.9.2-py27_0
seaborn-0.5.0-np19py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
numpy-1.7.0-py27_0 => not numpy-1.9.0-py27_0
numpy-1.7.1-py33_2 => not numpy-1.9.1-py33_0
numpy-1.7.1-py33_1 => not numpy-1.9.2-py34_0
numpy-1.8.2-py27_0 => not numpy-1.9.1-py33_0
numpy-1.8.1-py33_0 => not numpy-1.9.0-py33_0
python-3.3.2-0 => not python-3.4.3-0
python-2.6.8-5 => not python-3.3.2-0
python-3.3.1-0 => not python-3.4.3-0
numpy-1.7.1-py27_1 => not numpy-1.9.0-py33_0
numpy-1.9.1-py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
numpy-1.7.1-py33_1 => not numpy-1.9.0-py33_p0
numpy-1.8.1-py27_0 => not numpy-1.9.0-py27_0
numpy-1.8.0-py27_0 => not numpy-1.9.2-py34_0
numpy-1.9.1-py34_p0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
pykit-0.2.0-np18py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.8.0-py27_0 => not numpy-1.9.0-py33_p0
pykit-0.1.0-np18py33_2 => numpy-1.8.0-py26_0 or numpy-1.8.0-py26_p0 or numpy-1.8.0-py27_0 or numpy-1.8.0-py27_p0 or numpy-1.8.0-py33_0 or numpy-1.8.0-py33_p0 or numpy-1.8.1-py26_0 or numpy-1.8.1-py26_p0 or numpy-1.8.1-py27_0 or numpy-1.8.1-py27_p0 or numpy-1.8.1-py33_0 or numpy-1.8.1-py33_p0 or numpy-1.8.1-py34_0 or numpy-1.8.1-py34_p0 or numpy-1.8.2-py26_0 or numpy-1.8.2-py26_p0 or numpy-1.8.2-py27_0 or numpy-1.8.2-py27_p0 or numpy-1.8.2-py33_0 or numpy-1.8.2-py33_p0 or numpy-1.8.2-py34_0 or numpy-1.8.2-py34_p0
python-2.6.8-5 => not python-3.3.5-1
python-3.3.1-0 => not python-3.4.1-1
numpy-1.7.1-py33_0 => not numpy-1.9.2-py34_0
numpy-1.7.1-py27_0 => not numpy-1.9.2-py34_0
numpy-1.8.2-py33_0 => not numpy-1.9.0-py33_0
numpy-1.8.2-py26_p0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.8.0-py33_0 => not numpy-1.9.1-py27_0
numpy-1.7.1-py33_2 => not numpy-1.9.0-py33_0
numpy-1.8.0-py27_0 => not numpy-1.9.1-py27_0
numpy-1.7.1-py27_2 => not numpy-1.9.0-py33_p0
numpy-1.7.1-py33_2 => not numpy-1.9.2-py33_0
numpy-1.8.2-py27_0 => not numpy-1.9.2-py33_0
numpy-1.8.1-py33_0 => not numpy-1.9.1-py33_0
not numpy-1.7.1-py27_p1
numpy-1.8.0-py33_0 => not numpy-1.9.0-py33_p0
numpy-1.7.0-py33_0 => not numpy-1.9.2-py27_0
not numpy-1.8.2-py34_p0
numpy-1.7.1-py27_1 => not numpy-1.9.1-py33_0
python-2.6.9-1 => not python-3.3.3-0
numpy-1.8.1-py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
python-2.6.9-0 => not python-3.3.5-0
python-3.3.3-0 => not python-3.4.2-0
not numpy-1.8.1-py33_p0
python-3.3.0-4 or python-3.3.1-0 or python-3.3.2-0 or python-3.3.3-0 or python-3.3.4-0 or python-3.3.5-0 or python-3.3.5-1
numpy-1.7.1-py26_2 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.8.1-py33_0 => not numpy-1.9.2-py33_0
not numpy-1.8.0-py33_p0
numpy-1.8.1-py26_p0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.1-py33_p2 => not numpy-1.9.0-py33_0
numpy-1.7.1-py33_0 => not numpy-1.9.2-py33_0
python-3.3.4-0 => not python-3.4.1-2
numpy-1.7.1-py27_0 => not numpy-1.9.2-py33_0
numpy-1.7.1-py27_1 => not numpy-1.9.2-py33_0
python-3.3.5-1 => not python-3.4.3-0
seaborn-0.5.0-np19py27_0 => numpy-1.9.0-py26_0 or numpy-1.9.0-py26_p0 or numpy-1.9.0-py27_0 or numpy-1.9.0-py27_p0 or numpy-1.9.0-py33_0 or numpy-1.9.0-py33_p0 or numpy-1.9.0-py34_0 or numpy-1.9.0-py34_p0 or numpy-1.9.1-py26_0 or numpy-1.9.1-py26_p0 or numpy-1.9.1-py27_0 or numpy-1.9.1-py27_p0 or numpy-1.9.1-py33_0 or numpy-1.9.1-py33_p0 or numpy-1.9.1-py34_0 or numpy-1.9.1-py34_p0 or numpy-1.9.2-py26_0 or numpy-1.9.2-py26_p0 or numpy-1.9.2-py27_0 or numpy-1.9.2-py27_p0 or numpy-1.9.2-py33_0 or numpy-1.9.2-py33_p0 or numpy-1.9.2-py34_0 or numpy-1.9.2-py34_p0
python-3.3.5-0 => not python-3.4.0-0
numpy-1.7.1-py33_3 => not numpy-1.9.1-py27_0
not numpy-1.9.1-py33_p0
numpy-1.8.2-py33_0 => not numpy-1.9.0-py27_0
numpy-1.9.0-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.0-py33_0 => not numpy-1.9.2-py33_0
python-3.3.5-1 => not python-3.4.1-1
python-3.3.5-0 => not python-3.4.2-0
not numpy-1.9.2-py33_p0
numpy-1.7.0-py27_0 => not numpy-1.9.1-py27_0
python-3.3.0-4 => not python-3.4.0-0
numpy-1.7.1-py33_1 => not numpy-1.9.2-py27_0
python-3.3.0-4 => not python-3.4.1-0
numpy-1.9.2-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.0-py27_0 => not numpy-1.9.0-py33_p0
numpy-1.7.1-py26_p1 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.9.0-py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
python-3.3.3-0 => not python-3.4.0-0
python-3.3.2-0 => not python-3.4.1-2
numpy-1.7.1-py33_0 => not numpy-1.9.0-py33_p0
numpy-1.7.1-py27_1 => not numpy-1.9.0-py33_p0
numpy-1.7.0-py27_0 => not numpy-1.9.2-py34_0
numpy-1.8.2-py27_0 => not numpy-1.9.0-py33_p0
pykit-0.1.0-np17py27_1 => numpy-1.7.0-py26_0 or numpy-1.7.0-py27_0 or numpy-1.7.0-py33_0 or numpy-1.7.1-py26_0 or numpy-1.7.1-py26_1 or numpy-1.7.1-py26_2 or numpy-1.7.1-py26_3 or numpy-1.7.1-py26_p0 or numpy-1.7.1-py26_p1 or numpy-1.7.1-py26_p2 or numpy-1.7.1-py26_p3 or numpy-1.7.1-py27_0 or numpy-1.7.1-py27_1 or numpy-1.7.1-py27_2 or numpy-1.7.1-py27_3 or numpy-1.7.1-py27_p0 or numpy-1.7.1-py27_p1 or numpy-1.7.1-py27_p2 or numpy-1.7.1-py27_p3 or numpy-1.7.1-py33_0 or numpy-1.7.1-py33_1 or numpy-1.7.1-py33_2 or numpy-1.7.1-py33_3 or numpy-1.7.1-py33_p0 or numpy-1.7.1-py33_p1 or numpy-1.7.1-py33_p2 or numpy-1.7.1-py33_p3
python-2.6.9-0 => not python-3.3.0-4
not numpy-1.9.0-py34_p0
python-3.3.0-4 => not python-3.4.2-1
numpy-1.8.2-py33_0 => not numpy-1.9.2-py33_0
numpy-1.8.0-py27_0 => not numpy-1.9.0-py27_0
numpy-1.7.1-py33_0 => not numpy-1.9.1-py27_0
numpy-1.7.1-py27_3 => not numpy-1.9.2-py34_0
pykit-0.1.0-np17py26_1 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
python-2.6.8-5 => not python-3.3.3-0
python-3.3.1-0 => not python-3.4.2-1
numpy-1.7.1-py33_3 => not numpy-1.9.2-py33_0
numpy-1.7.0-py27_0 => not numpy-1.9.2-py27_0
numpy-1.7.1-py27_2 => not numpy-1.9.2-py33_0
numpy-1.7.1-py27_2 => not numpy-1.9.0-py33_0
numpy-1.7.0-py33_0 => not numpy-1.9.2-py34_0
numpy-1.8.1-py34_p0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
numpy-1.7.1-py33_p2 => not numpy-1.9.2-py33_0
numpy-1.7.1-py27_3 => not numpy-1.9.1-py27_0
python-3.3.1-0 => not python-3.4.1-0
pykit-0.2.0-np18py34_0 => python-3.4.0-0 or python-3.4.1-0 or python-3.4.1-1 or python-3.4.1-2 or python-3.4.2-0 or python-3.4.2-1 or python-3.4.3-0
python-2.6.8-6 => not python-3.3.2-0
numpy-1.7.1-py33_1 => not numpy-1.9.0-py27_0
not numpy-1.9.2-py34_p0
numpy-1.8.1-py27_0 => not numpy-1.9.0-py33_p0
python-2.6.8-6 => not python-3.3.1-0
numpy-1.8.2-py33_0 => not numpy-1.9.1-py33_0
not numpy-1.8.0-py27_p0
numpy-1.8.0-py33_0 => not numpy-1.9.0-py33_0
python-2.6.9-0 => not python-3.3.5-1
numpy-1.7.1-py27_2 => not numpy-1.9.1-py33_0
python-2.6.9-1 => not python-3.3.2-0
pykit-0.2.0-np18py27_0 => numpy-1.8.0-py26_0 or numpy-1.8.0-py26_p0 or numpy-1.8.0-py27_0 or numpy-1.8.0-py27_p0 or numpy-1.8.0-py33_0 or numpy-1.8.0-py33_p0 or numpy-1.8.1-py26_0 or numpy-1.8.1-py26_p0 or numpy-1.8.1-py27_0 or numpy-1.8.1-py27_p0 or numpy-1.8.1-py33_0 or numpy-1.8.1-py33_p0 or numpy-1.8.1-py34_0 or numpy-1.8.1-py34_p0 or numpy-1.8.2-py26_0 or numpy-1.8.2-py26_p0 or numpy-1.8.2-py27_0 or numpy-1.8.2-py27_p0 or numpy-1.8.2-py33_0 or numpy-1.8.2-py33_p0 or numpy-1.8.2-py34_0 or numpy-1.8.2-py34_p0
numpy-1.9.1-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
numpy-1.7.1-py33_p2 => not numpy-1.9.1-py33_0
numpy-1.7.1-py33_3 => not numpy-1.9.0-py33_0
python-2.6.9-0 => not python-3.3.2-0
python-3.3.3-0 => not python-3.4.1-2
numpy-1.8.0-py27_0 => not numpy-1.9.0-py33_0
numpy-1.7.1-py33_3 => not numpy-1.9.2-py34_0
seaborn-0.5.0-np19py27_0 or seaborn-0.5.0-np19py33_0 or seaborn-0.5.0-np19py34_0 or seaborn-0.5.1-np19py27_0 or seaborn-0.5.1-np19py33_0 or seaborn-0.5.1-np19py34_0
python-2.6.9-1 => not python-3.3.5-1
numpy-1.8.0-py26_0 => python-2.6.8-5 or python-2.6.8-6 or python-2.6.9-0 or python-2.6.9-1
not numpy-1.8.2-py33_p0
not numpy-1.7.1-py26_p2
numpy-1.8.0-py33_0 => not numpy-1.9.2-py34_0
python-3.3.4-0 => not python-3.4.2-0

**Comment by luopuya** [comment]
And this is the conda info
>     
platform : win-64
conda version : 3.10.1
conda-build version : 1.3.1
python version : 2.7.6.final.0
requests version : 2.6.0
root environment : C:\Anaconda  (writable)
default environment : C:\Anaconda\envs\py3k
envs directories : C:\Anaconda\envs
package cache : C:\Anaconda\pkgs
channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False

**Comment by asmeurer** [comment]
A good thing to try with this is to look at all the packages in the hint and remove any that you don't care about. In this case, you probably don't want `pykit`, as it's no longer actively developed (`conda remove pykit`).

**Comment by luopuya** [comment]
Thanks a lot~
