### ISSUE TITLE
When will miniconda installer build a version for python 3.11?

### ISSUE THREAD

**Issue by aweffr** [conda/conda#12848]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I have a initialize script for linux to install conda & python, but now i want to upgrade the python version to 3.11.

In miniconda doc (https://docs.conda.io/en/latest/miniconda.html), the lastest version is python 3.10. Is there any plan to release a new installer for python 3.11?

### Why is this needed?

minicoda installer with python3.11 included

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager and not the miniconda installer. Thank you for understanding!
