### ISSUE TITLE
conda clean -p breaks hard linking of new installs

### ISSUE THREAD

**Issue by ARF1** [conda/conda#1285]
@asmeurer 
Following on from conda/conda#68:

On Windows 8 (and probably equally on all other windows versions), `conda clean -p` removes all extracted packaged from the `pkgs` directory even if they are hard linked in some environments.

While all existing environments will continue to function, creation of a new environment with the same packages causes conda to extract the packages again and  to hard link to the newly extracted files. This massively increases disk usage and results in the opposite of what a user running `conda clean` was attempting to achieve.

The problem lies in `main_clean.py` and the fact that on Windows  `lstat(file).st_nlink` always returns 0, even if `file` is hard linked. (This seems to have been fixed from python 3.2 onwards: https://bugs.python.org/issue10027)

As a stop gap measure `conda clean -p` should be prevented from being run on windows until a better solution can be found.

```
C:\>conda list
# packages in environment at C:\Anaconda:
#
conda                     3.10.1                   py27_0
conda-env                 2.1.4                    py27_0
menuinst                  1.0.4                    py27_0
psutil                    2.2.1                    py27_0
pycosat                   0.6.1                    py27_0
python                    2.7.9                         1
pyyaml                    3.11                     py27_0
requests                  2.6.0                    py27_0
```

**Comment by tico-tico** [comment]
Yep, pretty annoying issue.

> The problem lies in main_clean.py and the fact that on Windows lstat(file).st_nlink always returns 0, even if file is hard linked. (This seems to have been fixed from python 3.2 onwards: https://bugs.python.org/issue10027)

If it's really the case then WinAPI **GetFileInformationByHandle** should be used. The nNumberOfLinks field of the BY_HANDLE_FILE_INFORMATION structure is exactly what we want. **ntfsutils** has very nice implementation of the thing here http://pydoc.net/Python/ntfsutils/0.1.3/ntfsutils.fs/ , I guess it can be borrowed. You know, `if getfileinfo(path).nNumberOfLinks > 1: ...`

**Comment by ARF1** [comment]
@tico-tico Thanks for the hint. I coded up your suggestion in #1944.

**Comment by tico-tico** [comment]
Oh, tnx ARF1 for doing stuff instead of just saying things as I did.  :thumbsup:
