### ISSUE TITLE
There was an error importing jinja2. Unable to parse meta.yaml file

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1287]
I am trying to build a package I'm working on using Travis-CI, but I keep getting the same [error](https://travis-ci.org/jrsmith3/datac/jobs/58916763#L678-L694):

```
$ conda build -c jrsmith3 conda.recipe
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
----------------------------------------------------------------------
Unable to parse meta.yaml file
It appears you are missing jinja2.  Please install that package, then
attempt to build.
Error Message:
--> while parsing a flow mapping
-->   in "<string>", line 13, column 14:
-->         string: {{ environ.get('GIT_BUILD_STR', ' ... 
-->                  ^
--> expected ',' or '}', but got '<scalar>'
-->   in "<string>", line 13, column 47:
-->      ...  environ.get('GIT_BUILD_STR', '') }}
-->                                          ^
```

The relevant section of my `.travis.yml` is

``` yaml
  - conda install conda-build
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda
  - source activate test-environment
  - conda build -c jrsmith3 conda.recipe
```

The [`meta.yaml` file](https://github.com/jrsmith3/datac/blob/18f149ee230817ef03f1e5d643fafdac17afc6d4/conda.recipe/meta.yaml) can be found in the source repo.

This issue may be related to [PR 248](https://github.com/conda/conda-build/pull/248).

Even if I install `jinja2` into the build environment, I still get the same error. The build works on my local machine.

Thanks for the help!

**Comment by asmeurer** [comment]
Don't install jinja2 into the build environment, install it into the root environment.

**Comment by jrsmith3** [comment]
Thanks! It [seemed to work](https://travis-ci.org/jrsmith3/datac/jobs/58944696) (I'm getting a different error now).

Shouldn't `conda-build` depend on `jinja2` to avoid this kind of error?

**Comment by srossross** [comment]
I was also discussing with Philip Cooper that we should use `meta.yaml.in` for jinja2 templated  `meta.yaml` files.
This would also let us inspect the resulting `meta.yaml` if anything goes wrong.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2000
