### ISSUE TITLE
Make it easier to run conda from a cron job

### ISSUE THREAD

**Issue by barabo** [conda/conda#12884]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

See [this](https://unix.stackexchange.com/questions/454957/cron-job-to-run-under-conda-virtual-environment) SE thread for context.

Since the boilerplate shell init code is appended to the bottom of shell `.rc` files (`.bashrc`, for example), it can not always be sourced from a `cron` script because some `.rc` files exit early when a non-interactive session is detected.

If the init code were saved to a separate file which was sourced from the `.rc` files, it would be easier to `source` that file in a `cron` script before invoking `conda`.

Also, if `conda` emitted a different hint when it detected it was run from a non-interactive session (instead of the one that suggests `conda init` was needed) - it would make troubleshooting easier for setting up `cron`-run `conda` jobs.

### Why is this needed?

Running `conda` from a non-interactive session (especially `cron`) often fails with an error about `conda init` not having been run yet.  This is a bit misleading, and could be improved with better error messaging.

### What should happen?

When `conda` is run in a non-interactive session, it would be better to suggest that the `conda init` boilerplate is missing from the shell environment because the shell is non-interactive.

The boilerplate code _could_ be separated into a file which is sourced from `.rc` files.  This feature could then enable to a suggestion to `source` this file before attempting to run `conda` in a non-interactive session.

**Comment by kenodegard** [comment]
you can bootstrap your shell by running the following:

```
eval $(/path/to/bin/conda shell.posix hook)
```

**Comment by barabo** [comment]
Awesome!  What about having conda provide a hint when run from a non-interactive session and it's not yet bootstrapped?

Something like this, maybe?

```
When running conda from a non-interactive session, you may provide bootstrapping by adding the following to your script:

eval $(/path/to/bin/conda shell.posix hook)
```
