### ISSUE TITLE
Getting LookUpError after not changing any conda settings from the previous session

### ISSUE THREAD

**Issue by jthornton-0** [conda/conda#12892]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have Conda installed on my universities supercomputer HPC, `Miniconda3-latest-Linux-x86_64.sh` from 16/04/23 (when I downloaded it and uploaded it to my home on the HPC). This error has happened to me around 4 times but it is frustrating as I need to manually reinstall the Conda environments and Conda. I logged out the night before of the HPC server with no jobs running, went to activate an environment the next day and the issue appeared like it has done the previous times, it appears to just be random. There were no changes to Python environment variables in the time between logins. The error message appears as:

```
[[USER]@login1(kelvin2) ~]$ conda
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/mnt/scratch2/users/[USER]/miniconda3/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/mnt/scratch2/users/[USER]/miniconda3/bin/python'
  sys.base_prefix = '/mnt/scratch2/users/[USER]/miniconda3'
  sys.base_exec_prefix = '/mnt/scratch2/users/[USER]/miniconda3'
  sys.platlibdir = 'lib'
  sys.executable = '/mnt/scratch2/users/[USER]/miniconda3/bin/python'
  sys.prefix = '/mnt/scratch2/users/[USER]/miniconda3'
  sys.exec_prefix = '/mnt/scratch2/users/[USER]/miniconda3'
  sys.path = [
    '/mnt/scratch2/users/[USER]/miniconda3/lib/python310.zip',
    '/mnt/scratch2/users/[USER]/miniconda3/lib/python3.10',
    '/mnt/scratch2/users/[USER]/miniconda3/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007fec91002740 (most recent call first):
  <no Python frame>

```
I am not sure what I am doing to cause the issue, Conda works fine the day before and then the next it breaks after no modifications and I need to reinstall. Whilst it is annoying to have to reinstall environments it only takes 20 minutes or so to do but it is just how unexpected it is that is the most frustrating (typically when I am against a deadline!). Is there any advice for this error please or what should I do short of just reinstalling?

### Conda Info

```shell
(base) [[USER]@login2(kelvin2) ~]$ conda info

     active environment : base
    active env location : /mnt/scratch2/users/[USER]/miniconda3
            shell level : 1
       user config file : /users/[USER]/.condarc
 populated config files : /users/[USER]/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /mnt/scratch2/users/[USER]/miniconda3  (writable)
      conda av data dir : /mnt/scratch2/users/[USER]/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /mnt/scratch2/users/[USER]/miniconda3/pkgs
                          /users/[USER]/.conda/pkgs
       envs directories : /mnt/scratch2/users/[USER]/miniconda3/envs
                          /users/[USER]/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/3.10.0-1160.92.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 406600693:406600001
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /users/[USER]/.condarc <==
channel_priority: flexible
channels:
  - conda-forge
  - defaults
  - bioconda
restore_free_channel: True
offline: False
```

### Conda list

```shell
Cannot activate any conda environment to show this
```

**Comment by jthornton-0** [comment]
I have emailed my system admins and will provide a response here especially if it is being caused by a process on their end, I hope you don't mind keeping this open till then so that this can act as a source for anyone in the future encountering this issue, thanks for the quick response!

**Comment by travishathaway** [comment]
Hi @jthornton-0,

We'll be happy to do that. Please tag either myself or @kenodegard when you have heard any news. It will help us stay organized.

**Comment by millsks** [comment]
Howdy all.  Any updates with this?  I just started getting this error early this morning.  I even tried reinstalling and recreating my environments.  The funny thing is that we have individual conda installs per user and it is affecting one user and not another.  I reached out to our platform team to see what changed, but very weird I have never seen this before.
