### ISSUE TITLE
Add health check for environment variables like `REQUESTS_CA_BUNDLE`

### ISSUE THREAD

**Issue by bkreider** [conda/conda#12905]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The env variable REQUESTS_CA_BUNDLE can break conda/anaconda-client if it is pointing to a file that doesn't exist.  Since anaconda-client is integrated/used by conda this can cause problems even if conda has `ssl_verify: false` set.  

It would be nice to catch and report this error so a user knows what to do to fix it -- the windows command to run and the *nix command to run to fix this error.

### Why is this needed?

This is a rare but very subtle problem that most users wouldn't notice.  It's an environment variable that can break anaconda-client and therefore break conda when running normal commands.  But since the problem is twice removed from conda, it is hard to diagnose (ie: it is an env variable used by anaconda-client that breaks conda commands). 

### What should happen?

`conda doctor` could do any of the following:

1. report that this environment variable is set and affects operations of conda (???) and anaconda-client
2. If it is pointing to a file that doesn't exist or has bad file permissions, report that it is a bad setting and how to fix it.

**Comment by jezdez** [comment]
@ForgottenProgramme Could this be a neat use case for another built-in health check or even one for the potential plugin hook for additional health checks?
