### ISSUE TITLE
Miniconda3 MacOSX-x86_64.pkg  macOS 10 not supported ?

### ISSUE THREAD

**Issue by denis-bz** [conda/conda#12916]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Just a suggested doc improvement --
On macOS 10.15.7 (Catalina),
```
sudo open -a /System/Library/CoreServices/Installer.app  .../Miniconda3-py39_23.5.2-0-MacOSX-x86_64.pkg
```
gives a popup with
>This package is incompatible with this version of macOS

Fair enough.
Would it be easy to check the user's macOS version early, and not even download .pkg that won't work ?
Or improve the doc

Bytheway conda 23.3.1 from May seems to work; is there a legacy .pkg with py310 ?
Thanks, cheers

### Why is this needed?

people with macOS 10.15
(who dislike planned obsolescence)

### What should happen?

better doc: macOS 10 is not supported

**Comment by travishathaway** [comment]
Hi @denis-bz,

Thanks for submitting this issue. I do not think we will pursue this feature request because we believe there exists a valid work around. Have you tried using the shell installer instead? (e.g. https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh).

Please let us know if that works for you.

**Comment by denis-bz** [comment]
Thanks @travishathaway, looks good, IOU a 🍺
(How about a note "prefer .sh to .pkg" on https://docs.conda.io/en/latest/miniconda.html  ?
would've saved me some time)

**Comment by travishathaway** [comment]
@denis-bz, glad that worked. I will bring this up with some of the other maintainers, but I can't make any promises that we will actually change that page.

In the meantime, I'm going to go ahead and close this issue.
