### ISSUE TITLE
Installation failed on Mac M2 - opens navigator but incorrectly installs python?

### ISSUE THREAD

**Issue by AmyKWood** [conda/conda#12926]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Downloaded the anaconda software for Mac M1/M2 and went through the installation wizard. At the end of the installation anaconda navigator opens but the wizard does this:

<img width="1512" alt="Screenshot 2023-07-25 at 14 44 35" src="https://github.com/conda/conda/assets/127393845/674276a2-0852-4d7c-977f-9a9a9418facf">

I have tried installing in the default location and choosing MacintoshHD/Users/Mypersonalfolder. 

Currently using MacOS Ventura Version 13.4 1 (c)

### Conda Info

```shell
zsh: command not found: conda
```

### Conda Config

```shell
zsh: command not found: conda
```

### Conda list

```shell
zsh: command not found: conda
```

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
