### ISSUE TITLE
If `~/.condarc` is a symlink non-default channels do not work

### ISSUE THREAD

**Issue by andrsd** [conda/conda#12956]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In my setup, I have several `.condarc.XYZ` files and  I used a symlink from `.condarc` to one of those based on what I needed. This was done for debugging purposes when I was developing a new conda adapter.

I upgraded conda from 23.5.x to 23.7.0 and my non-default channel (conda-forge) disappeared.

This is what `conda info` gave with `23.5.x`:
```
     active environment : bld
    active env location : /<homedir>/miniconda3/envs/bld
            shell level : 2
       user config file : /<homedir>/.condarc
 populated config files : /<homedir>/.condarc
          conda version : 23.5.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.5=0
                          __unix=0=0
       base environment : /<homedir>/miniconda3  (writable)
      conda av data dir : /<homedir>/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /<homedir>/miniconda3/pkgs
                          /<homedir>/.conda/pkgs
       envs directories : /<homedir>/miniconda3/envs
                          /<homedir>/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.5.1 requests/2.31.0 CPython/3.9.16 Darwin/22.6.0 OSX/13.5 solver/libmamba conda-libmamba-solver/23.7.0 libmambapy/1.4.9
                UID:GID : 501:20
             netrc file : /<homedir>/.netrc
           offline mode : False
```

This is `conda info` with `23.7.0`:
```
     active environment : bld
    active env location : /<homedir>/miniconda3/envs/bld
            shell level : 2
       user config file : /<homedir>/.condarc
 populated config files : 
          conda version : 23.7.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.5=0
                          __unix=0=0
       base environment : /<homedir>/miniconda3  (writable)
      conda av data dir : /<homedir>/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /<homedir>/miniconda3/pkgs
                          /<homedir>/.conda/pkgs
       envs directories : /<homedir>/miniconda3/envs
                          /<homedir>/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.0 requests/2.31.0 CPython/3.9.16 Darwin/22.6.0 OSX/13.5
                UID:GID : 501:20
             netrc file : /<homedir>/.netrc
           offline mode : False
```

Notice that  `populated config files` is empty.

The content of `~/.condarc`:
```
report_errors: false
channels:
  - conda-forge
  - defaults
```

I tested this on OSX (macbook pro with apple M1) and linux (amd64 debian).

This is not a show stopper for me, I can go back to the regular file for `.condarc`. Thought you may want to know about this. Or, if somebody runs into a the same problem, hopefully they will find this issue.

### Conda Info

```shell
See above for more details...
```

### Conda Config

```shell
==> envvars <==
number_channel_notices: 0
```

**Comment by travishathaway** [comment]
Hi @andrsd,

Thanks for reporting this. I have been able to recreate this issue myself, so I can confirm this regression. Your workaround seems reasonable in the meantime, but I think we should restore this behavior.

I cannot promise when we will get around to fixing this, but I will tag it as a good-first issue so it hopefully gets more attention and will bring it up with my colleagues.

**Comment by dholth** [comment]
This code resolves the symlink, and THEN checks that the resolved path is in `CONDARC_FILENAMES` (.condarc, condarc) or if the suffix (extension) is in `YAML_EXTENSIONS` (.yml, .yaml). https://github.com/conda/conda/blob/e67f5e4a48e6f12ae7ebddfe79f2f2f5b7afc45c/conda/common/configuration.py#L1395-L1401

I copied ~/.condarc to ~/linkto-condarc and then symlinked it. Conda ignores the file because the symlink's target does not pass the test.

**Comment by andrsd** [comment]
Thanks for fixing this! 👍
