### ISSUE TITLE
DEB package for version 23.1.0-1 installation fails with bad interpreter

### ISSUE THREAD

**Issue by tgagor** [conda/conda#12973]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

We're running monthly upgrade of our Docker base images and one of them installs recent "conda" package (as [documented here](https://conda.io/projects/conda/en/stable/user-guide/install/rpm-debian.html)).

Recent package fails with error:
```bash
Preparing to unpack .../conda_23.1.0-1_amd64.deb ...
Unpacking conda (23.1.0-1) ...
Setting up conda (23.1.0-1) ...
/bin/sh: /opt/conda/bin/conda: /home/runner/work/conda-rpm-deb/conda-rpm-deb/conda-prefix/opt/conda/bin/python: bad interpreter: No such file or directory
The command '/bin/sh -c apt-get update &&     apt-get install conda
returned a non-zero code: 126
```

Same error is generated on both Ubuntu 20.04 and 22.04.

Installing older package version: `23.1.0-0` works as expected and this is our workaround for now.

### Conda Info

```shell
Can't get it as it can't be installed :(
```

**Comment by cvquesty** [comment]
Same issue exists on RHEL based systems.  The conda file in /opt/conda/bin/conda has a shebang line of:

`#!/home/runner/work/conda-rpm-deb/conda-rpm-deb/conda-prefix/opt/conda/bin/python`

You can get conda to work by changing that line to:

`#!/opt/conda/bin/python`

This looks like a build bug where the shebang simply needs to be changed on the build box before executing the build.

**Comment by cvquesty** [comment]
I would request this gets higher priority than just "bug", as the default install doesn't even run, killing Conda.  This should be a pull request, which I will attempt to do right now.  Until this gets pushed, Conda will be non-functional in the current run.

**Comment by travishathaway** [comment]
Hi @tgagor and @cvquesty,

Thanks for bring this to our attention. I just want to let everyone know that the team responsible for managing both DEB and RPM distributions of conda is aware of the issue and is currently working to resolve it.

We will update this issue once we can confirm these packages are working again.

**Comment by cvquesty** [comment]
That one’s easy.  Distros settle on a version and go to repo, usually freezing a version unless there’s an overwhelming reason to update it.  My son is at RedHat, so I’ve already let them know to increment the version.Sent from my iPhoneOn Aug 8, 2023, at 7:09 AM, Tom ***@***.***> wrote:﻿
Thank you guys!
Just out of curiosity - DEB package is 23.1.0, but latest released is 23.7.2. Is there any reason for such big gap between releases and official packaging?

**Comment by cvquesty** [comment]
Travis,Thank you for the hard work!Also note that at some later version it’s already been fixed. It just isn’t in the distro’s official repos.Sent from my iPhoneOn Aug 8, 2023, at 6:40 AM, Travis Hathaway ***@***.***> wrote:﻿
Hi @tgagor and @cvquesty,
Thanks for bring this to our attention. I just want to let everyone know that the team responsible for managing both DEB and RPM distributions of conda is aware of the issue and is currently working to resolve it.
We will update this issue once we can confirm these packages are working again.

**Comment by tgagor** [comment]
I was referring to the Anaconda repo: https://repo.anaconda.com
Isn't this one owned by Conda?
My expectation would be, that when new version is released, it should be available in this repo within minutes (not months).

**Comment by pseudoyim** [comment]
@tgagor thank you for reporting this issue. We have rebuilt the `.deb` and `.rpm` package for `conda-23.1.0` (latest has build number `2`; look for `conda-23.1.0-2`). This rebuild fixes the shebang issue and should resolve the `bad interpreter` error you reported.

Please let us know if you have any other questions or concerns. Thanks again.

**Comment by tgagor** [comment]
I can confirm - 23.1.0-2 deb package works fine.
Thanks again.

**Comment by travishathaway** [comment]
> I was referring to the Anaconda repo: https://repo.anaconda.com Isn't this one owned by Conda? My expectation would be, that when new version is released, it should be available in this repo within minutes (not months).

@tgagor, this is managed by the company [Anaconda](https://anaconda.com). Unfortunately, updating these packages is still a manual process, but we are currently exploring automating it, which should ensure faster releases there.

I'll go ahead and close this issue for now considering this has been reported as resolved.
