### ISSUE TITLE
(base) C:\Users\Tanya_21>conda install -c conda-forge netcdf4 Collecting package metadata (current_repodata.json): done Solving environment: -

### ISSUE THREAD

**Issue by tanyagupta8942** [conda/conda#12978]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

(base) C:\Users\Tanya_21>conda install -c conda-forge netcdf4
Collecting package metadata (current_repodata.json): done
Solving environment: -

### Conda Info

```shell
keep on running no output
```

### Conda Config

```shell
(base) C:\Users\Tanya_21>conda install -c conda-forge netcdf4
Collecting package metadata (current_repodata.json): done
Solving environment: -
```

**Comment by travishathaway** [comment]
Hi @tanyagupta8942,

Thanks for filing this issue. I'm guessing that you are experience long wait times for this command to finish? (if it even does finish?). If that's the case, I encourage you to install and configure the "conda-libmamba-solver".

Here's how to do that...

First, install it to your base environment:
```
conda install -n base conda-libmamba-solver
```

Now, configure it as your default solver:

```
conda config --set solver libmamba
```

After running those two commands, please trying installing the `netcdf4` package again to see if it goes quicker.

More information about the "conda-libmamba-solver" can be found here: https://conda.github.io/conda-libmamba-solver/getting-started/
