### ISSUE TITLE
Remote environment definition support

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda/conda#13017]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In addition to anaconda.org support it would be great to consider using something like fsspec to expand the capability of installing an environment from a remote definition.

### What should happen?

For example, using fsspec you can specify a uri using any of the [built-in protocols](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations) or from a growing list of [3rd party packages](https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations) that can be installed.

```
conda env create https://github.com/AlbertDeFusco/windturbines/raw/main/environment.yml
conda env create github://albertdefusco:windturbines@main/environment.yml
```

**Comment by AlbertDeFusco** [comment]
Given work underway in #11633 and #5253 perhaps this would be well suited to an extension. Also, I can see where the current `conda env create -f file` can cause confusion since `-f` supports a limited collection of remote sources like https, ftp, and s3.

**Comment by jezdez** [comment]
I left a few notes in https://github.com/conda/conda/pull/12952#issuecomment-1688839243 about this
