### ISSUE TITLE
Fast check if a conda env exists and valid

### ISSUE THREAD

**Issue by alippai** [conda/conda#13030]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

A fast check like `conda env valid -n some_env` or `conda info -n some_env` or `conda activate some_env --dry-run` would be nice. 

### Why is this needed?

Currently one can't get metadata from the envs. The full list of packages or full list of envs is available, also I can check if the directory exists in the `/envs` directory but none of them are great (maybe I'm wrong and they should suffice?). 

### What should happen?

Exit code 0 or 1 set. 

### Additional Context

I'm using "content addressed", immutable environments, where the hash of the explicit package list and versions is part of the environment name. If it doesn't exist, I create the env, if it already exists, I skip this step.

**Comment by travishathaway** [comment]
@alippai,

Thanks for filing this issue. I think you can get what you need by running the following command:

```
conda list --name <environment>
```

This will exit with a `1` when an environment cannot be found and also print an `EnvironmentLocationNotFound` error message.

Furthermore, environments really are just folders, so you could do a very basic check just by seeing if that folder exists and has contents in it. A more detailed check could even examine the contents of the `conda-meta` folder within it to see what is currently installed.

That's basically what `conda list` does when determining what to return ☝️.
