### ISSUE TITLE
ipython installation does not work properly in new environment

### ISSUE THREAD

**Issue by kingj90** [conda/conda#1304]
Hi,

I think there is a bug when ipython is installed within a new conda environment

I have python 3.4.3 in my root environment, now I want to create a new environment with python 2.7, so I execute

conda create -n test python=2.7
source activate test

which python    -> somepath/conda/envs/test/bin/python
which ipython   -> somepath/conda/bin/ipython

now, **I start ipython** and naturally it loads python 3.4.3 because its still using the ipython from the root installation, so I go

conda install ipython

which python    -> somepath/conda/envs/test/bin/python
which ipython   -> somepath/conda/envs/test/bin/ipython

when starting ipython now, it still loads the wrong python version (3.4.3. instead of 2.7). Note that this behaviour only occurs if the wrong ipython is started before the conda installation. So the problem can be avoided by installing ipython right from the start:

conda create -n test1 python=2.7 ipython

I don't understand why this happens but I though it might be worth mentioning it here.

Cheers!

**Comment by hargup** [comment]
@asmeurer I also faced the same issue while creating a build environment for Numba.

**Comment by asmeurer** [comment]
See http://conda.pydata.org/docs/help/troubleshooting.html#shell-command-location for more explaination of why this happens.

**Comment by jonide** [comment]
http://conda.pydata.org/docs/help/troubleshooting.html#shell-command-location appears to be a dead link.

**Comment by andreasmoegelmose** [comment]
You're looking for http://conda.pydata.org/docs/troubleshooting.html#shell-command-location

**Comment by tshrjn** [comment]
The solution suggested at https://conda.io/docs/user-guide/troubleshooting.html#shell-commands-open-from-the-wrong-location does not work.
