### ISSUE TITLE
Treat JSONDecodeError on repodata.info.json as a warning, equivalent to a missing repodata.info.json

### ISSUE THREAD

**Issue by dholth** [conda/conda#13056]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Parallel downloads can corrupt the repodata metadata. Since we will soon lock by default, this will probably be less of an issue. If `<repodata cache key>.info.json` can't be decoded, show a warning, then behave as if `*.info.json` was missing, download fresh repodata.

**Comment by dholth** [comment]
#13037
#13026 
#12570
#9590 ? (older than any of the recent repodata.info.json changes)

**Comment by travishathaway** [comment]
I would even bother with showing a warning here. If it's corrupted, we need to just remove it and create a new one. I doubt most users care to know about the internals of conda.

**Comment by dholth** [comment]
Since we aim not to corrupt the file, if we started doing that again how would we find the bug without a warning?

**Comment by najtin** [comment]
Here is how i did this. It would be easy to add a warning. https://github.com/conda/conda/compare/main...najtin:conda:fix-decode-error
