### ISSUE TITLE
conda fails if PATH contains unreadable directories

### ISSUE THREAD

**Issue by jgoodson** [conda/conda#13058]
### What happened?

The most recent conda patch added a feature where conda will manually scan all of the directories in PATH variable for files beginning with `conda-`. This was added in https://github.com/conda/conda/pull/13006. This method does not account for the possibility that there may be unreadable or non-existent directories in the PATH like shells do. When any conda process is run with this condition, it will exit with 

```[Errno 13] Permission denied: '/path/to/unreadable/directory/in/PATH'```

or similar.

This module should either handle such errors gracefully by skipping that directory or checking whether the directory exists and is readable before calling `os.listdir()`. Another tool could be used that collects all executables in the system PATH, but despite the commit title, the current version of this module doesn't appear to check if the file is executable, so perhaps that is not desired.

This occurs with in all cases with 23.7.3 on Linux systems with a PATH variable containing an unreadable directory.

**Comment by dzieko** [comment]
Same problem happen for me and our conda users.
If PATH contains a dir that is not accessible for the user, conda will fail.
Please see attached error report.
[report.txt](https://github.com/conda/conda/files/12505343/report.txt)

**Comment by kenodegard** [comment]
resolved in `conda 23.7.4`
