### ISSUE TITLE
update in conda issue

### ISSUE THREAD

**Issue by ymmx** [conda/conda#1305]
hi everyone.
I have an issue with updating anaconda's packages with conda. when I make a conda update --all there is an issue which says to me: 
Error: Unable to remove files for package: cryptography
Please close all processes running code from cryptography and try again.
however, none process are running, I have just the cmd window open.
Same story when I want update dateutile for instance.
It is like if conda uses some package and then I cannot update them??
Somebody knows a method to close or remove those packages in order to reinstall them?

For information: 
C:\Anaconda3\Scripts>conda info -a
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.6.2
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://conda.binstar.org/juanlu001/win-64/
                        https://conda.binstar.org/juanlu001/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\maxime\.condarc
    is foreign system : False

**Comment by tanderl** [comment]
I'm getting what I presume is the same issue.  When I attempt to update jinja2, I get that same error that:

    Unable to remove files for package: jinja2

Full trace is below.  Please let me know if there's any further information that would be useful.

        C:\Users\tanderl>conda install jinja2 -y
        Fetching package metadata: ....
        Solving package specifications: .
        Package plan for installation in environment C:\Miniconda:
        
        The following packages will be UPDATED:
        
            jinja2:   2.7.3-py27_1 --> 2.7.3-py27_2
            requests: 2.6.2-py27_0 --> 2.7.0-py27_0
        
        Error: Unable to remove files for package: jinja2
        
        Please close all processes running code from jinja2 and try again.
        
        
        C:\Users\tanderl>conda info -a
        Current conda install:
        
                     platform : win-32
                conda version : 3.11.0
          conda-build version : not installed
               python version : 2.7.7.final.0
             requests version : 2.6.2
             root environment : C:\Miniconda  (writable)
          default environment : C:\Miniconda
             envs directories : C:\Miniconda\envs
                package cache : C:\Miniconda\pkgs
                 channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                                https://repo.continuum.io/pkgs/free/noarch/
                                https://repo.continuum.io/pkgs/pro/win-32/
                                https://repo.continuum.io/pkgs/pro/noarch/
                  config file : None
            is foreign system : False
        
        # conda environments:
        #
        other_one                C:\Miniconda\envs\other_one
        root                  *  C:\Miniconda
        
        sys.version: 2.7.7 |Continuum Analytics, Inc.| (defau...
        sys.prefix: C:\Miniconda
        sys.executable: C:\Miniconda\python.exe
        conda location: C:\Miniconda\lib\site-packages\conda
        conda-build: None
        conda-env: C:\Miniconda\Scripts\conda-env.exe
        user site dirs:
        
        CIO_TEST: <not set>
        CONDA_DEFAULT_ENV: <not set>
        CONDA_ENVS_PATH: <not set>
        PATH: C:\Perl\bin\;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Onlin
        e Services;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\90\To
        ols\binn\;C:\Program Files (x86)\Graphviz 2.28\bin;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\doxygen\bin;C:\Program Files (x86)\M
        iKTeX 2.9\miktex\bin\;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\HDF_Group\HDFView\2.10.1\bin;C:\Program Files (x86)\Git\cmd;C:\HashiCorp\Vagrant\bin;C:
        \Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Ruby187\bin;C:\Windows\System32;c:\bin;
        c:\program files\apache-maven-2.2.1\bin;C:\Users\tanderl\AppData\Local\Pandoc\;c:\Program Files (x86)\IAR Systems\Embedded Workbench 6.5\common\bin;c:\users\tan
        derl
        PYTHONHOME: <not set>
        PYTHONPATH: <not set>
        
        WARNING: could not import _license.show_info
        # try:
        # $ conda install -n root _license
        
        C:\Users\tanderl>

**Comment by ymmx** [comment]
I have got an answer for my issue.
http://stackoverflow.com/questions/29949087/python-anaconda-conda-issue-updating-anaconda-package-impossible-because-proces
Hope this can help you.

**Comment by tanderl** [comment]
After a little more spelunking, I determined that in my specific case, conda is determining that it cannot open `C:\Miniconda\Lib/site-packages/Jinja2-2.7.3-py2.7.egg-info` for writing.  However, when I look in my system, that particular path is actually a directory, not a file.  The `C:\Miniconda\Lib\site-packages` directory on my machine has a mixture of entries that end with `.egg-info`.  Some of them are files and some are directories.  This mix of files and directories appears to be confusing the writability detection in conda/utils.py.

Looking at the logs, it appears to me that the writability detection got added in version 3.11.  As a stop-gap workaround, I was able to downgrade conda to 3.10.1, and got the symptom to go away (I was able to upgrade jinja2 without the error message).

**Comment by asmeurer** [comment]
That should work. We are planning to remove this completely in the next version of conda.

**Comment by tanderl** [comment]
What do you mean by "remove this completely"?  I think the writability checking is important to indicate to the user when an update is going to fail (see the "pandas-0.14.1 fails to import on windows" conversation in the anaconda-public google group; sorry I couldn't figure out how to provide a link).  In reading the stackoverflow link above, I think that ymmx's root issue is slightly different from mine.  In that case, the conda process actually does have the file open and locked because the conda process is using it.  In my case, conda is attempting to open a file whose path actually corresponds to a directory and thus flagging it as locked.

If when you wrote "remove this completely", you were referring to the conda dependency on `cryptography`, then I don't know enough to have an opinion.

If instead, you were referring to the writability check, I'd much prefer if the heuristic were tweaked to handle the directory vs file case instead of being removed.

**Comment by asmeurer** [comment]
It will be removed in favor of https://github.com/conda/conda/pull/1133, which allows us to remove files that are locked by the file system.

**Comment by grisaitis** [comment]
Thanks to both of you for your help on this. I had this issue with the package pywin32. Downgrading from conda 3.11 to 3.10.1, installing stuff, and then upgrading back again fixed the issue. For a while I thought antivirus software was locking the files / folders, similar to an issue with pip pre-6.1.1 (https://github.com/pypa/pip/issues/306). But I guess it was something else...

**Comment by ymmx** [comment]
This issue seems to be corrected on the last version of anaconda 3.2.2

**Comment by flutefreak7** [comment]
I couldn't figure out how to downgrade to 3.10.1 or whatever (I googled and tried some stuff, but it was very not-obvious and I gave up), so instead I installed a fresh Anaconda to C:\Anaconda3_fresh, upgraded conda in that installation (with `conda upgrade conda`), then copied the contents of C:\Anaconda3_fresh\Lib\site-packages\conda to C:\Anaconda3\Lib\site-packages\conda and then upgraded conda in the C:\Anaconda3 installation and it appears to have worked... a bit hackish, but it made sense to me as a workaround since I couldn't figure out the downgrading part.

**Comment by grisaitis** [comment]
Glad you fixed it! 

For future reference, though, to install a specific version of a package (ie a py lib, Python itself, conda itself), you just do "conda install <package name>=<version>". See here: https://groups.google.com/a/continuum.io/forum/m/#!topic/conda/s6GbcODB8D0

**Comment by grisaitis** [comment]
Agh, my comment text did non parse as I expected. 

You'd do this, basically, to change versions of a program:

conda install conda=3.10.1

**Comment by asmeurer** [comment]
This is fixed in the latest version so there should no longer be a need to downgrade conda. `conda update conda` should give you a version that works.

**Comment by rlabbe** [comment]
conda update conda

gives me this error message

    Error: Unable to remove files for package: conda

conda info tells me I have 3.11 installed.

    conda install conda=3.14.0 

gives me the same error (Error: Unable to remove files for package: conda)

How do I update if conda is the one that is out of date and causing the problem?

**Comment by flutefreak7** [comment]
I got around this problem by creating a fresh anaconda installation and
copying the conda folder over to my messed up installation, giving conda
the ability to update itself.  Messy, but it appeared to work for me.

**Comment by rlabbe** [comment]
Thank you flutefreak7. I deleted my question almost immediately because after I actually read the provided links I saw that I could force the install with conda install -f conda. That seemed to work.

I say "seemed" because a subsequent run of 'conda update anaconda' crashed, but everything seems to be working now.

**Comment by hum3** [comment]
conda install -f conda seems to have worked for me as well
