### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by johnnynunez** [conda/conda#13072]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

3.12 Python support

### Why is this needed?

Could Python 3.12 Enhance ONNX's Multithreading Capabilities?

The official release of Python 3.12 is fast approaching, scheduled for October 2, 2023. What heightens my anticipation even more is Python 3.12's potential to significantly improve ONNX's multithreading performance.

For a considerable amount of time, Python's Global Interpreter Lock (GIL) has acted as an obstacle to efficient multithreading, particularly in CPU-intensive tasks such as deep learning through ONNX. However, Python 3.12 is set to debut a revolutionary feature: PEP 684, otherwise known as A Per-Interpreter GIL.

Why is this significant? ONNXRuntime, the core engine for executing ONNX deep learning models, is largely dependent on CPU resources. With the introduction of Python 3.12's per-interpreter GIL, there's an optimistic outlook for fully leveraging multi-core processors, thereby unleashing ONNX's untapped potential in deep learning applications.

As Python 3.12 is about to make its significant debut, it provides an ideal moment for me to re-engage with ONNX's multithreading capabilities, invigorated by these promising developments.

Keep an eye out for the upcoming release and join me in exploring the compelling opportunities that lie at the crossroads of ONNX and Python 3.12.

### What should happen?

Support 3.12 ASAP to create conda environments

**Comment by cbouss** [comment]
Hi Johnny,

Thank you for reaching out. This year Anaconda introduced a preview channel featuring Python-3.12-compatible packages. 

Please note that while these packages provide a sneak peek into the upcoming release, functionality may vary, and availability on all architectures may be limited. Some packages may be in beta or release candidate versions. Currently, the channel includes for all architectures Python 3.12.0 RC2, pip, setuptools, certifi, and cython. Additional packages have also been uploaded for linux-64.

If you’re eager to get a head start with Python 3.12, simply run the following command to install it from the preview channel:

`conda create -n python-312-preview -c ad-testing/label/py312 python`

**Comment by travishathaway** [comment]
Hi @johnnynunez,

We appreciate you reaching out to us, but unfortunately this is not the correct place to do so. For issues related to individual packages on the Anaconda defaults channel, please open an issue at this project: https://github.com/ContinuumIO/anaconda-issues/

I'll be closing this issue now.

**Comment by makslevental** [comment]
> If you’re eager to get a head start with Python 3.12, simply run the following command to install it from the preview channel:
> 
> `conda create -n python-312-preview -c ad-testing/label/py312 python`

where is this channel? this command no longer works.

**Comment by johnnynunez** [comment]
how fast this time, although it is only a 5% improvement over python 3.11. The previous version was a significant improvement.

**Comment by jezdez** [comment]
A reminder that the actual Python package is only the start, and the build-out of Python 3.12 compatible packages on Anaconda's main channel has only started.

**Comment by Tunneller** [comment]
incidentally doing ` conda create -n Test_312 python=3.12``just creates a complete mess of mangled DLL's

**Comment by ubaldot** [comment]
Not sure it is related but when I try to `conda install conda-build` I get:

```
│  └─ conda-build [3.21.4|3.21.5|...|3.28.1] conflicts with any installable versions previously reported;
└─ python 3.12**  is not installable because there are no viable options
   ├─ python 3.12.0 would require
   │  └─ python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported;
   ├─ python 3.12.0rc3 would require
   │  └─ _python_rc, which does not exist (perhaps a missing channel);
   └─ python 3.12.0 conflicts with any installable versions previously reported.
```
working with conda `23.7.4` (I also run `conda update --name base --channel defaults --yes conda`and it says I am using the latest version)

**Comment by matthewacarson** [comment]
@aaravind100 

> something like `conda create -n py312 python=3.12` or `conda create -c anaconda -n py312 python=3.12` should work

Is there any way to install this to the base environment? I'm a bit short on disk space, and creating a new environment just to update python takes up too much space.

**Comment by kenodegard** [comment]
@matthewacarson you can always try to update the Python (or any package for that matter) installed into your `base` environment by explicitly specifying the version you want:

```
conda install -n base python=3.12
```

> [!WARNING]
> 1. this may not necessarily work depending on what other packages are installed in your `base` environment
> 2. upgrading your Python version in your `base` environment has been known to break conda so proceed at your own risk and don't be surprised if you need to reinstall

**Comment by ispanos** [comment]
> I'm a bit short on disk space, and creating a new environment just to update python takes up too much space.

I have the opposite issue. I just installed anaconda3, mainly because it comes with almost all the packages I need. Since I'm new here, I don't want to touch with base yet. 

`conda create -n py312 python=3.12 -y` installs just python.

Are there any meta-packages (or _package groups_) I could use, to install most of the packages I will need? E.g. "data-science" or "statistics" packages.

Since I have space, I would be willing to re-install **all** the packages in base (those available for 3.12) in a new environment.

**Comment by cbouss** [comment]
Hi @ispanos, the last anaconda metapackage also comes with a 3.12 variant.
You can create a 3.12 environment with `conda create -n py312 anaconda=2024.02 python=3.12`

**Comment by ispanos** [comment]
> Hi @ispanos, the last anaconda metapackage also comes with a 3.12 variant.
> You can create a 3.12 environment with `conda create -n py312 anaconda=2024.02 python=3.12`

Thank you very much!
