### ISSUE TITLE
Support operating system root certificate stores for TLS connections

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13097]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

This would enable us to work around issues that show up often in corporate environments, e.g. #11563.

### Why is this needed?

Increasing the likelihood that connections to repos are secure and pass through corporate proxies, for example.

### What should happen?

We should adopt the [truststore](https://truststore.readthedocs.io/) package as a core dependency.

**Comment by davisagli** [comment]
@jezdez A couple notes --

Normally, `requests` adds the CA certs from `certifi` (i.e. the ones trusted by Mozilla) to the default SSLContext. When using truststore, this means you'll end up with an SSLContext that trusts both certs from the system trust store and from `certifi`. So you'll need to decide whether you want that or not. (I think the `certifi` CA certs are currently not included, the way @zeehio has implemented it in https://github.com/conda/conda/pull/13075)

On platforms other than Mac and Windows, `truststore` uses the default capath from OpenSSL. So keep in mind that which `OpenSSL` conda is using will have an impact on which certs are trusted.

/cc @dholth @sethmlarson
