### ISSUE TITLE
"conda env remove" should not remove empty parent directories outside of a dedicated environment repository

### ISSUE THREAD

**Issue by barryd15** [conda/conda#13113]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I created a conda environment at my_project/conda:
```
mkdir my_project
cd my_project
conda create -p ./conda
```
I removed the conda environment:
```
conda env remove -p ./conda
```
This resulted in not only the `conda` directory, but also the `my_project` directory being removed, while my shell cwd was still there.
Not realising my cwd was gone, I tried to recreate the environment:
```
conda create -p ./conda
```
This command gave output that was confusing and disturbing - as it seemed it was about to overwrite my base conda environment:
```
WARNING: A conda environment already exists at '/home/barry/miniconda3/conda'
```

Full log:
  ```
(base)
  2023-09-16 10:59:37 barry@Barry-PC23 ~
  $ cd proj
  (base)
  2023-09-16 10:59:43 barry@Barry-PC23 ~/proj
  $ mkdir my_project
  (base)
  2023-09-16 10:59:50 barry@Barry-PC23 ~/proj
  $ cd my_project/
  (base)
  2023-09-16 10:59:52 barry@Barry-PC23 ~/proj/my_project
  $ conda create -p ./conda
  Collecting package metadata (current_repodata.json): done
  Solving environment: done
  
  ## Package Plan ##
  
    environment location: /home/barry/proj/my_project/conda
  
  
  
  Proceed ([y]/n)? y
  
  Preparing transaction: done
  Verifying transaction: done
  Executing transaction: done
  #
  # To activate this environment, use
  #
  #     $ conda activate /home/barry/proj/my_project/conda
  #
  # To deactivate an active environment, use
  #
  #     $ conda deactivate
  
  (base)
  2023-09-16 11:00:06 barry@Barry-PC23 ~/proj/my_project
  $ ls -l ~/proj/my_project
  total 4
  drwxr-xr-x 3 barry barry 4096 Sep 16 11:00 conda
  (base)
  2023-09-16 11:00:19 barry@Barry-PC23 ~/proj/my_project
  $ conda env remove -p ./conda
  
  Remove all packages in environment /home/barry/proj/my_project/conda:
  
  (base)
  2023-09-16 11:00:36 barry@Barry-PC23 ~/proj/my_project
  $ ls -l ~/proj/my_project
  ls: cannot access '/home/barry/proj/my_project': No such file or directory
  (base)
  2023-09-16 11:00:46 barry@Barry-PC23 ~/proj/my_project
  $ conda create -p ./conda
  WARNING: A conda environment already exists at '/home/barry/miniconda3/conda'
  Remove existing environment (y/[n])? n
  
  
  CondaSystemExit: Exiting.

```
What should have happened:
1. Given that the environment being removed did not exist within a dedicated conda environment repository tree, `conda env remove` should not have removed additional empty parent directories, outside of the specified environment path `my_project/conda` itself.  `my_project` should not have been removed.

2. When `conda create -p ./conda` was run from the non-existent cwd of `my_project`, it appears to have defaulted the cwd to a path relative to the conda bin dir.  It probably should not have done this defaulting *before* interpreting the ./conda path from the command line.  Ideally, if the cwd is required (eg. to interpret relative paths), a non-existent cwd would raise an error.  This situation can be detected as a FileNotFoundError from os.getcwd().

### Conda Info

```shell
active environment : base
    active env location : /home/barry/miniconda3
            shell level : 1
       user config file : /home/barry/.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.35=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/barry/miniconda3  (writable)
      conda av data dir : /home/barry/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/barry/miniconda3/pkgs
                          /home/barry/.conda/pkgs
       envs directories : /home/barry/miniconda3/envs
                          /home/barry/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.4 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> cmd_line <==
debug: False
json: False
```

### Additional Context

A couple of related issues:

#9688 Conda env remove removes environment directory and empty parent directories
This is similar but:
* does not draw a distinction between environments inside and outside an environment repository tree,
* does not highlight how the behaviour of `conda env remove` and `conda create` together cause potentially serious issues,
* and has been closed due to inactivity.

#10588 conda env remove tries to remove parent path /tmp/, fails & crashes 
This is related but:
* does not draw a distinction between environments inside and outside an environment repository tree,
* and focuses specifically on the fact that attempting to remove `/tmp` causes errors, not on the fact that we never should have tried to remove it in the first place.

**Comment by travishathaway** [comment]
Hi @barryd15,

Thanks for creating this issue and clearly documenting what you have found.

Changing the way this works should be relatively easy. Here is the line where the directory removal takes place:

https://github.com/conda/conda/blob/21409746c2833a010a18e027c4297fb8270d790c/conda/cli/main_remove.py#L86

Note the `clean_empty_parents` option. My only reservation about changing the way this works is breaking the way other users currently expect this to work. My proposal would be to instead add a `--clean-empty-parents` option that would default to true that you could optionally set to false.

Regarding attempting to create an environment in a non-existent folder, this will require a little more research to figure out the best solution. Could you please create a separate issue for that so we can stay better organized?

**Comment by kenodegard** [comment]
This was solved in https://github.com/conda/conda/pull/14173
