### ISSUE TITLE
Friendly JSONDecodeError alternative when repodata.json can't be parsed?

### ISSUE THREAD

**Issue by dholth** [conda/conda#13110]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Users can see a `JSONDecodeError` with basically no information, that goes something like this, when we try to parse the direct http body of a repodata request.

```
fetched https://the-repository/platform/repodata.json
JSONDecodeError <expected json on byte 0>
```

It might be because you got HTML "please log into the cafe wifi" instead of JSON.

Instead, we could print the HTTP response headers "content-type was ..." and we could print the first ~80 characters of the response string.

'Could not decode repodata.json. Got "<html><head><title>I am a Proxy</ti"..., Content-Type: html" instead.' 

### Why is this needed?

Better support users behind a proxy.

Unfortunately JSON is not necessarily decoded until after we discard HTTP headers. IIRC JLAP stores a selection of headers in the `<repodata>.info.json` i.e. the cache object's state property which could be retrieved to fill out the error message.

We should be able to test this with the same techniques used in `test_jlap` or `test_repodata_gateway / test_subdir_data`, by setting up a local package server and putting e.g. a html file named 'repodata.json' in one of our test folders.

**Comment by jezdez** [comment]
Moving this since there is more testing needed

**Comment by jezdez** [comment]
Possibly related to #13514
