### ISSUE TITLE
The illegal instruction error is reported during conda installation.

### ISSUE THREAD

**Issue by yejianbang** [conda/conda#13116]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello, esteemed contributor！

I was trying to customize the directory to install conda.
However, the following error message is displayed:

**Do you accept the license terms? [yes|no]
[no] >>> yes

Anaconda3 will now be installed into this location:
/root/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/root/anaconda3] >>> /home/anaconda3
PREFIX=/home/anaconda3
Unpacking payload ...
Anaconda3-2023.07-2-Linux-aarch64.sh: line 354: 51774 Illegal instruction     (core dumped) "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs**

and then,I tried installing conda by default,so,The installation directory is /root/anaconda3,It's amazing. This installation was a success!
But, but I went on to execute conda's related commands.The error is Illegal instruction still reported.I consulted the relevant documentation to replace libcrypto.so.1.1.But it still doesn't work

My System Architecture:aarch64
My Operating System:openEuler20.03 (LTS-SP3)
Details:
`cat /etc/os-release`
NAME="openEuler"
VERSION="20.03 (LTS-SP3)"
ID="openEuler"
VERSION_ID="20.03"
PRETTY_NAME="openEuler 20.03 (LTS-SP3)"
ANSI_COLOR="0;31"

`uname -a`
Linux localhost.localdomain 4.19.90-2112.8.0.0131.oe1.aarch64 #1 SMP Fri Dec 31 19:53:20 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

`lscpu`
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    4
Vendor ID:                       ARM
Model:                           2
Model name:                      Cortex-A72
Stepping:                        r0p2
BogoMIPS:                        100.00
L1d cache:                       2 MiB
L1i cache:                       3 MiB
L2 cache:                        16 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-15
NUMA node1 CPU(s):               16-31
NUMA node2 CPU(s):               32-47
NUMA node3 CPU(s):               48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

### Conda Info

```shell
Illegal instruction (core dumped)
```

### Conda Config

```shell
Illegal instruction (core dumped)
```

### Conda list

```shell
Illegal instruction (core dumped)
```

**Comment by travishathaway** [comment]
Hi @yejianbang,

Thanks for filing this issue. After asking around about your problem, my guess is that this could be related to a hardware compatibility issue. Anaconda arm packages are compiled to target sever arm architectures and may not work elsewhere.

For example, our arm packages are currently incompatible on Raspberry Pi.

My advice to you would be to try one of the [miniforge conda installers](https://github.com/conda-forge/miniforge) instead. I'm not sure if that will work better though. If that's the case, then there's not much more I could recommend.

Please let us know if this works for you.

**Comment by yejianbang** [comment]
Thank you for your advice, @travishathaway 
Maybe like you said, my server is aarch64 architecture.So, I chose the anaconda installation package for the aarch64.
I'm trying to install https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh

Luckily, the installation was a success!No error message is "Illegal instruction (core dumped)" displayed.The commands related to conda are running properly.

But,What is the difference between Miniforge3 and Anaconda3?Will Anaconda3 be a little more complete than Miniforge3?

Finally, thank you again for your reply！

**Comment by travishathaway** [comment]
@yejianbang,

The Miniforge and Anaconda installers are compiled slightly differently for the aarm64 architecture. The Mininforge installer targets a more generic class of aarm64 processors and therefore works on a wider variety of hardware whereas the Anaconda installer targets server-class aarm64 processors and therefore supports fewer pieces of hardware. I'm guess that your particular piece of hardware is currently unsupported by the Anaconda installer and cannot be used with it.

When you install Miniforge, you also end up with a version of conda that is configured to use conda-forge as its primary channel. To learn more about conda-forge, I suggest you head over here: https://conda-forge.org/#about

For now, I think you should be good to go as using Miniforge seems to have resolved your issue. I will be closing this issue now.

P.S.

If you are interested in learning more about conda in general, I suggest you check out our "FAQ" article here: https://conda.org/learn/faq. You might also find this recent blog interesting too: https://www.anaconda.com/blog/is-conda-free
