### ISSUE TITLE
Importing ctypes causes an ImportError on Windows 64-bit (Python 3.4)

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#1313]
This is from a fresh install of Anaconda (64-bit, Windows 8.1, Python 3.4) on a machine that has never had it before. Since conda depends on ctypes, it's pretty much hosed. I'll drop down to 32-bit for now. 

Some searching on the Googles suggests that this can occur when a 32-bit package is installed in a 64-bit Python environment. That may be the case, but again this is a fresh install.

```
C:\Users\continuum\Anaconda3>python
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\continuum\Anaconda3\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by mcg1969** [comment]
More information: the PC *does* have an installation of Python in `C:\Python27`, placed at the end of the  PATH.

**Comment by mcg1969** [comment]
I was able to resolve the issue by renaming `C:\Python27` to `C:\Python27.old`, thereby taking it out of the PATH. Here is the PATH variable, with non-Python elements redacted (not my computer).

```
PATH=C:\Users\...\Anaconda3;C:\Users\...\Anaconda3\Scripts;C...‪;C:\Python27;‪C:\Python27\scripts\;‪C:\Python27\;C:\Users\continuum\Anaconda3;C:\Users\...\Anaconda3\Scripts;
```                                                                                

So Anaconda's install is indeed both before and after the conflicting installation.

**Comment by kalefranz** [comment]
We're wrestling with getting PATH issues right in the installer for Anaconda 4.4.  Ongoing issue I think.  Closing this ticket though.  Ray has a good handle on the problem.
