### ISSUE TITLE
Deleted miniconda3/bin/ by mistake

### ISSUE THREAD

**Issue by acv21** [conda/conda#13134]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Hello,

I deleted the `miniconda3/bin/` directory by mistake, and I think this has messed up conda. When I try to activate any of my environments, this is the error message I get:
`bash: /home/miniconda3/bin/conda: No such file or directory`

Is there any way I could fix this without having to delete conda/miniconda3, all my environments and packages and reinstall everything from scratch?

Thanks for your time

**Comment by kenodegard** [comment]
@acv21 unfortunately there is no easy way to restore your missing `bin` directory. As you can see the `conda` executable itself is now missing as it was in the `bin` directory.

The best (and safest) solution will be to reinstall miniconda. I would first try to run the installer without deleting `/home/miniconda3`, the installer should do a graceful "upgrade" and keep any environments that you had previously created.
