### ISSUE TITLE
Cloudflare cache returns old InRelease file

### ISSUE THREAD

**Issue by henrisota** [conda/conda#13147]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Recently, I started noticing that my conda installation through apt-get is working locally, but failing on AWS eu-west-1 region. Following the installation procedure for Debian-based distros, we run:

```
apt-get update
apt-get install -y software-properties-common apt-transport-https ca-certificates apt-utils gnupg curl
add-apt-repository "deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main"
curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor | apt-key add -
apt-get -
apt-get update
apt-get install -y conda
```

The installation on AWS fails on the second “apt-get update”

```
E: Failed to fetch https://repo.anaconda.com/pkgs/misc/debrepo/conda/dists/stable/main/binary-amd64/Packages.bz2 File has unexpected size (3287 != 3127). Mirror sync in progress? [IP: 104.16.131.3 443]
```

Based on this, I had a look over the InRelease file retrieved through my local machine and through the AWS instance.

Locally retrieved version of InRelease through a Cloudflare cache in Germany

```
Hash: SHA256

Origin: . stable
Label: . stable
Suite: stable
Codename: stable
Date: Tue, 19 Sep 2023 22:11:53 UTC
Architectures: amd64
Components: main
Description: Generated by aptly
MD5Sum:
...
0b6cada8bf459b31895205810e72dc18 3287 main/binary-amd64/Packages.bz2
...
```

AWS retrieved version of InRelease through a Cloudflare cache in Ireland

```
Hash: SHA256

Origin: . stable
Label: . stable
Suite: stable
Codename: stable
Date: Fri, 25 Aug 2023 15:22:57 UTC
Architectures: amd64
Components: main
Description: Generated by aptly
MD5Sum:
...
4e3f4fef2e27a41c7db375ada107276f 3127 main/binary-amd64/Packages.bz2
...
```

Notice the difference in the reported/expected file size for the `Packages.bz2`

Looking at the other files, they appear to have been updated and match the ones I retrieve locally.

This issue started happening on September 20th, 2023, after the release.

Therefore, we want to know what the maintainers can do about the invalid Cloudflare cache. We would appreciate if the cache is updated/invalidated for this particular region. We also want to pose the question what could be done to avoid this kind of issue from happening again.

### Additional Context

Cached response headers for the `InRelease` file:
```
last-modified: Fri, 25 Aug 2023 17:10:15 GMT
cf-cache-status: HIT
cf-ray: 80ca0375d9fe956f-DUB
```

**Comment by travishathaway** [comment]
Hi @henrisota,

Thanks for filing this issue. Unfortunately, this is the wrong place for it. Issues like these relating to the Anaconda Distribution and their channel servers belong in this GitHub project:

- https://github.com/ContinuumIO/anaconda-issues/issues

Feel free to simply reference this issue there when re-filing.

I will now be closing this issue as "off-topic".
