### ISSUE TITLE
Problem Installing Local Package to Environment with Absolute Path (-p param)

### ISSUE THREAD

**Issue by detroitcoder** [conda/conda#1316]
I created a package using `conda build mypackage` successfully and I can install the local version just fine to a conda enviornment  `conda install -n testenv  --use-local /anacondapath/anaconda/conda-bld/linux-64/example.tar.bz2` 

However when I specify an exact path using -p, only the directory name of my module is placed in the enviroment's site-packages, excluding __init__.py and other modules making it unaccessible. eg. `conda install -p /pathto/myother/environment/testenv  --use-local /anacondapath/anaconda/conda-bld/linux-64/example.tar.bz2`. I want to do this to test the build before uploading to binstar and want to keep anaconda's global environments clean because multiple users use the same root environment.

$ conda info:
platform : linux-64
conda version : 3.11.0
conda-build version : 1.12.1
python version : 2.7.9.final.0

**Comment by kalefranz** [comment]
Should be fixed. Closing.
