### ISSUE TITLE
Getting Started needs updates

### ISSUE THREAD

**Issue by kathatherine** [conda/conda#13160]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html needs updates for the last three or so years of updates, and also just a general refresh.

### What should happen

- [x] Simplify instructions to basic tasks (opening shell, creating environment, installing packages, updating conda)
- [x] Remove references to Anaconda Prompt
- [x] Version example in Managing conda needs update (also updated section to Updating conda instead)
- [x] Add Miniconda and Miniforge as conda download options
- [x] Link out to more areas of the docs where users can find more info on the beginner subject they’re learning about (i.e., linking to the larger https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-environments.html environments page from the Managing environments section of the Getting Started)

**Comment by jezdez** [comment]
Let's try to make the cheatsheet something we can autogenerate with Sphinx, instead of creating it manually.

**Comment by kathatherine** [comment]
Linking https://github.com/conda/conda/issues/12397 because it mentions that exact thing.

**Comment by travishathaway** [comment]
@kathatherine,

Could you please be a little more specific about exactly what needs to be done regarding the "general referesh"?

A checkbox list in the "What should happen section" would be very nice 😄.

Let me know if you need help writing it. I recently read the [getting started guide](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) and also thought that it deserves an update.

**Comment by kathatherine** [comment]
I think I'll also make this ticket just about the Getting Started guide, since the Cheatsheet has its own ticket already and the work will be a bit different.
