### ISSUE TITLE
conda remove --dry-run actually removes the package

### ISSUE THREAD

**Issue by jeanconn** [conda/conda#1317]
Is there anything set around here:

https://github.com/conda/conda/blob/ded940c3fa845bbb86b3492e4a7c883c1bcec10b/conda/cli/main_remove.py#L196

to actually exit before removing the package if --dry-run is set but --json is not?

I'm just running 3.11.0 and haven't grabbed and functionally tested master to see if this is still a problem.

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1318
