### ISSUE TITLE
`conda init` breaks ability to run `which conda`

### ISSUE THREAD

**Issue by tjdodson** [conda/conda#13180]
### What happened?

I borked my homebrew installation trying to install an x86_64 version in parallel using the following guide

 https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#m1chip
![image](https://github.com/conda/conda/assets/35269233/5837b0e2-71e6-426b-81aa-e3b0d6a8bb66)

this made brew now point to `/usr/local/bin/brew` instead of `opt/homebrew/`

and after lots of research the "only solution" was a `brew bundle dump` reinstall

which meant I reinstalled miniconda

### Issue

```shell
brew install --cask miniconda
```
installs conda and everything works just fine until I run
```shell
❯ conda init "$(basename "${SHELL}")"
```

which then breaks
```shell
❯ which conda
conda () {
	\local cmd="${1-__missing__}"
	case "$cmd" in
		(activate | deactivate) __conda_activate "$@" ;;
		(install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
			__conda_reactivate ;;
		(*) __conda_exe "$@" ;;
	esac
}
```

### Steps to Reproduce

```shell
❯ which conda
conda not found
❯ brew install --cask miniconda
==> Caveats
Please run the following to setup your shell:
  conda init "$(basename "${SHELL}")"

Alternatively, manually add the following to your shell init:
  eval "$(conda "shell.$(basename "${SHELL}")" hook)"

==> Downloading https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-MacOSX-arm64.sh
Already downloaded: /Users/t0d00bh/Library/Caches/Homebrew/downloads/beb353965889b1b94c57334b00fd2cd5202f194af103d2e748b961e6dcdc9249--Miniconda3-py311_23.5.2-0-MacOSX-arm64.sh
==> Installing Cask miniconda
==> Running installer script 'Miniconda3-py311_23.5.2-0-MacOSX-arm64.sh'
PREFIX=/opt/homebrew/Caskroom/miniconda/base
Unpacking payload ...
                                                                                                                 
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working... 
done
installation finished.
==> Linking Binary 'conda' to '/opt/homebrew/bin/conda'
🍺  miniconda was successfully installed!
❯ which conda
/opt/homebrew/bin/conda
❯ conda init "$(basename "${SHELL}")"
no change     /opt/homebrew/Caskroom/miniconda/base/condabin/conda
no change     /opt/homebrew/Caskroom/miniconda/base/bin/conda
no change     /opt/homebrew/Caskroom/miniconda/base/bin/conda-env
no change     /opt/homebrew/Caskroom/miniconda/base/bin/activate
no change     /opt/homebrew/Caskroom/miniconda/base/bin/deactivate
no change     /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
no change     /opt/homebrew/Caskroom/miniconda/base/etc/fish/conf.d/conda.fish
no change     /opt/homebrew/Caskroom/miniconda/base/shell/condabin/Conda.psm1
modified      /opt/homebrew/Caskroom/miniconda/base/shell/condabin/conda-hook.ps1
no change     /opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.csh
modified      /Users/t0d00bh/.zshrc

==> For changes to take effect, close and re-open your current shell. <==

❯ source ~/.zshrc
❯ which conda
conda () {
	\local cmd="${1-__missing__}"
	case "$cmd" in
		(activate | deactivate) __conda_activate "$@" ;;
		(install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
			__conda_reactivate ;;
		(*) __conda_exe "$@" ;;
	esac
}

```

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
❯ conda info

     active environment : None
            shell level : 0
       user config file : /Users/t0d00bh/.condarc
 populated config files : /Users/t0d00bh/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.6=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/miniconda/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/anaconda/osx-arm64
                          https://conda.anaconda.org/anaconda/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/pkgs
                          /Users/t0d00bh/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniconda/base/envs
                          /Users/t0d00bh/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Darwin/22.6.0 OSX/13.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
❯ conda config --show-sources
==> /Users/t0d00bh/.condarc <==
auto_activate_base: False
channels:
  - conda-forge
  - defaults
  - anaconda
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
❯ conda list --show-channel-urls
# packages in environment at /opt/homebrew/Caskroom/miniconda/base:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py311hca03da5_0    defaults
brotlipy                  0.7.0           py311h80987f9_1002    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.0               h80987f9_0    defaults
ca-certificates           2023.05.30           hca03da5_0    defaults
certifi                   2023.5.7        py311hca03da5_0    defaults
cffi                      1.15.1          py311h80987f9_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.5.2          py311hca03da5_0    defaults
conda-content-trust       0.1.3           py311hca03da5_0    defaults
conda-libmamba-solver     23.5.0          py311hca03da5_0    defaults
conda-package-handling    2.1.0           py311hca03da5_0    defaults
conda-package-streaming   0.8.0           py311hca03da5_0    defaults
cryptography              39.0.1          py311h834c97f_2    defaults
fmt                       9.1.0                h48ca7d4_0    defaults
icu                       68.1                 hc377ac9_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.1.1                h3e2b118_1    defaults
libcxx                    14.0.6               h848a8c0_0    defaults
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
libmamba                  1.4.1                h1c5506f_1    defaults
libmambapy                1.4.1           py311h1c5506f_1    defaults
libnghttp2                1.52.0               h62f6fdd_1    defaults
libsolv                   0.7.22               h98b2900_0    defaults
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.3               h372ba2a_0    defaults
lz4-c                     1.9.4                h313beb8_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.9                h1a28f6b_0    defaults
packaging                 23.0            py311hca03da5_0    defaults
pcre2                     10.37                h37e8eca_1    defaults
pip                       23.1.2          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.4               hb885b13_0    defaults
python.app                3               py311h80987f9_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.29.0          py311hca03da5_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                67.8.0          py311hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
toolz                     0.12.0          py311hca03da5_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311hca03da5_0    defaults
wheel                     0.38.4          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
yaml-cpp                  0.7.0                hc377ac9_1    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

</details>

**Comment by tjdodson** [comment]
Not sure if this is breaking more so than annoying

**Comment by kenodegard** [comment]
@tjdodson That is expected behavior. When you run `conda init` the appropriate initialization code is added to your shell profile which initializes `conda` as a shell function:

```bash
$ type conda
conda is a shell function
```

To inspect the path to your conda installation echo the `$CONDA_EXE` environment variable:

```bash
$ echo $CONDA_EXE
...
```

**Comment by tjdodson** [comment]
well prior to me running `conda init`
```zsh
❯ which conda
conda () {
	\local cmd="${1-__missing__}"
	case "$cmd" in
		(activate | deactivate) __conda_activate "$@" ;;
		(install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
			__conda_reactivate ;;
		(*) __conda_exe "$@" ;;
	esac
}
```

would result in the same output as

```zsh
❯ echo $CONDA_EXE
/opt/homebrew/Caskroom/miniconda/base/bin/conda
```

**Comment by kenodegard** [comment]
Correct, prior to running `conda init`, the `conda` command is simply the executable found on your `$PATH`. After running `conda init` the code injected into your shell profile initializes the `conda` command as a shell function. This is expected and necessary behavior for certain commands to work correctly (e.g. `conda activate` would not work prior to running `conda init`).

**Comment by dholth** [comment]
What if we put a comment in there?

```
(store) dholth@Daniels-MBP conda % which conda
conda () {
        \local cmd="${1-__missing__}"
        case "$cmd" in
                (activate | deactivate) __conda_activate "$@" ;;
                (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
                        __conda_reactivate ;;
                (*) __conda_exe "$@" ;;
        esac
}
(store) dholth@Daniels-MBP conda % which __conda_exe
__conda_exe () {
        (
                "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
        )
}
(store) dholth@Daniels-MBP conda % echo $CONDA_EXE
/Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.11-c/bin/conda
```

Instead, could it say
```
% which conda
conda () {
        # conda apologizes for breaking `which conda`; check $CONDA_EXE.
        \local cmd="${1-__missing__}"
        case "$cmd" in
                (activate | deactivate) __conda_activate "$@" ;;
                (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
                        __conda_reactivate ;;
                (*) __conda_exe "$@" ;;
        esac
}
```

**Comment by tjdodson** [comment]
> @tjdodson That is expected behavior. When you run `conda init` the appropriate initialization code is added to your shell profile which initializes `conda` as a shell function:
> 
> ```shell
> $ type conda
> conda is a shell function
> ```
> 
> To inspect the path to your conda installation echo the `$CONDA_EXE` environment variable:
> 
> ```shell
> $ echo $CONDA_EXE
> ...
> ```

I guess I expected `which conda` to still print to stdout the full path of the executables that would have been exe- cuted when this argument had been entered at the shell prompt. Like when you pass any number of arguments to `which`, is that not the case anymore?

<img width="773" alt="image" src="https://github.com/conda/conda/assets/35269233/80f42126-a77f-4d51-9103-1be2c531343c">

When did this become not the standard behavior? Also like I said if I install miniconda and run `which conda` it still works as expected until I run `conda init <shell_to_be_initialized>`

I only opened this because it was unexpected behavior and I was worried not figuring I out would come to bite me later, but after a couple weeks I am using conda as I always have and everything else is working just fine.

**Comment by tjdodson** [comment]
> What if we put a comment in there?
> 
> ```
> (store) dholth@Daniels-MBP conda % which conda
> conda () {
>         \local cmd="${1-__missing__}"
>         case "$cmd" in
>                 (activate | deactivate) __conda_activate "$@" ;;
>                 (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
>                         __conda_reactivate ;;
>                 (*) __conda_exe "$@" ;;
>         esac
> }
> (store) dholth@Daniels-MBP conda % which __conda_exe
> __conda_exe () {
>         (
>                 "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
>         )
> }
> (store) dholth@Daniels-MBP conda % echo $CONDA_EXE
> /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.11-c/bin/conda
> ```
> 
> Instead, could it say
> 
> ```
> % which conda
> conda () {
>         # conda apologizes for breaking `which conda`; check $CONDA_EXE.
>         \local cmd="${1-__missing__}"
>         case "$cmd" in
>                 (activate | deactivate) __conda_activate "$@" ;;
>                 (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
>                         __conda_reactivate ;;
>                 (*) __conda_exe "$@" ;;
>         esac
> }
> ```
> 
> On zsh, I was able to set a comment in a function, and see the comment when typing `which <function name>`.

What is the point of that output, lol?

**Comment by dholth** [comment]
This changed about a year ago. I also am constantly wondering what the path to my conda is. When you type `which conda` it shows the source code of the shell function `conda ()` instead.

It was changed to work this way because processes like `python -m conda activate` cannot change the environment of the parent shell, for example to set PATH to the currently activated conda environment. You can see that the shell function handles activate/deactivate at the shell level, otherwise it deletgates to `__conda_exe` which is another shell function that calls `$CONDA_EXE`.

If we added a comment to the function that is displayed when you type `which conda` then I could remind myself how to find the currently active `conda` script.

**Comment by tjdodson** [comment]
Thanks that's really helpful.

I just didn't know it changed which explains how long it has been since I've ran that command. I probably wouldn't have either, but I took my stupid mistake of messing up my homebrew installation as an opportunity to update my dev setup playbook. This is one of the commands I show in that guide to explain where conda is installed, and how that relates to the versions of python (or whatever language) you have installed to isolate your system installations.

`cmd="${1-__missing__}"`

yeah I didn't change any of that.

**Comment by kenodegard** [comment]
> This changed about a year ago.

Correction, conda has been a shell function since `conda 4.4.0` released in 2017 (https://github.com/conda/conda/pull/5044).

The most recent change that I'm aware of impacting how conda appears to users is Apple changing the default shell on macOS from Bash to ZSH in 2019. See the comparison below on how this impacts running `which conda`.

---

> I also am constantly wondering what the path to my conda is. When you type which conda it shows the source code of the shell function conda () instead.

Each shell has different preferred ways to get this information. As seen below, Bash and ZSH do different things for the `which` command for the same setup. In other words, the fact that you are seeing the shell function itself and not the executable isn't conda's fault but rather ZSH's.

Another helpful trick is to specify the `-a` flag to list all instances of executables found.

<table>
<tr>
<th>Bash</th>
<th>ZSH</th>
</tr>
<tr>
<td>

```bash
$ which -a conda
/Users/kodegard/miniconda/condabin/conda

$ type conda
conda is a function
conda ()
{
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}
```

</td>
<td>

```zsh
$ which -a conda
conda () {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}
/Users/kodegard/miniconda/condabin/conda

$ type conda
conda is a shell function
```

</td>
</tr>
</table>

---

> I guess I expected `which conda` to still print to stdout the full path of the executables that would have been executed when this argument had been entered at the shell prompt. Like when you pass any number of arguments to `which`, is that not the case anymore?

You are correct that most other shell commands out there are not shell functions and hence `which program` will display the executable path. As outlined by @dholth this is because most commands are not trying to mutate the shell environment itself as we need to do to make `conda activate` work.

As previously stated the correct way to check the conda executable is to either echo the `$CONDA_EXE` environment variable, run `conda info` which will also contain the base environment prefix, or as done above use `which -a conda`.

```bash
$ echo $CONDA_PREFIX
/Users/kodegard/miniconda

$ echo $CONDA_EXE
/Users/kodegard/miniconda/bin/conda

$ conda info | grep base
       base environment : /Users/kodegard/miniconda  (writable)

$ which -a conda
...
```

---

> is it really supposed to say `${1-__missing__}`?

Yes. See [Bash shell parameter expansion docs](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html):

<img width="730" alt="Screenshot 2023-10-18 at 1 47 01 PM" src="https://github.com/conda/conda/assets/4546435/10c0741b-6f54-4292-b5df-b2fcc8c2f72c">
