### ISSUE TITLE
Conda installation failed due to "Failed to execute script entry_point" due to unhandled exception!

### ISSUE THREAD

**Issue by cataratoru-fara-cap** [conda/conda#13200]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I failed installing anaconda on my linux MInt 21.2 laptop.
I checked previous issues reported here, and found the same issue for a server instalation, yet the solution did not apply to me
   
 This is fresh new installation, so I do not have anaconda installed on my computer. Thus, resolutions using conda command do not apply my case.

    I double checked with the HASH of the installer, so the installer sh file is not corrupted. (Regarding 

https://github.com/conda/conda/issues/9125#issuecomment-624479467 )

I have about 60GB of free storage left, thus it is not a drive size issue. (regarding
https://github.com/conda/conda/issues/9125#issuecomment-542732661 )

### Conda Info

```shell
Do you accept the license terms? [yes|no]
[no] >>> yes

Anaconda3 will now be installed into this location:
/home/legion/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/legion/anaconda3] >>> 
PREFIX=/home/legion/anaconda3
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:                                                                                                              
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 609, in result_iterator
  File "concurrent/futures/_base.py", line 446, in result
  File "concurrent/futures/_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[7862] Failed to execute script 'entry_point' due to unhandled exception!
```

**Comment by travishathaway** [comment]
Hi @cataratoru-fara-cap,

For issues related to the Anaconda installer, please head over to this GitHub project:

- https://github.com/ContinuumIO/anaconda-issues/issues

You may find a similar issue with the installer there.

This repository is for the the conda package manager software itself and not the associated installer. I will now be closing this issue as "off-topic".
