### ISSUE TITLE
Why not use absolute imports everywhere?

### ISSUE THREAD

**Issue by scruel** [conda/conda#13241]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In this project, we use both "relative imports" and "absolute imports", "relative imports" requires adding project path to `sys.path`, related workaround you code is [here](https://github.com/conda/conda/blob/95b40e677571ce21b9c6cd58f70d8fef3f104ac0/conda/shell/bin/conda#L8C1-L11C1)?
The mixed use of these two import methods is easy to cause confusion, so why not use absolute imports uniformly?

**Comment by travishathaway** [comment]
Hi @scruel,

This code is primarily for testing purposes. The person who made this change isn't around any more, so it's hard to know exactly why it was done that way.

@kenodegard, maybe you could help shed some more light on this? 🤷

**Comment by jaimergp** [comment]
napari switched to absolute imports last year, IIRC. @jni, would you mind elaborating how you reached that decision? Thanks!

**Comment by jezdez** [comment]
Relative imports are implicitly preferred for the conda code base, except for the pytest tests given its test discovery system. The fact that the code base has mixed imports is simply a side-effect of the age of the conda codebase, and when we're refactoring code we've usually moved from absolute to relative imports.

Napari seems to have [switched to help with developer experience](https://github.com/napari/napari/pull/5308), which I don't think is as important as to override a best practice for local imports.

**Comment by scruel** [comment]
@jezdez Oh, thank you for your explanation, but can you explain a bit more about why conda prefer relative imports?
IMO relative imports have many disadvantages:
- It's really inconvenient for debugging a single source code file, even with the project installed.
- It's kind of against the zen of Python: "Explicit is better than implicit.".
- It's better for one man task rather than a team work project
- IDE won't support relative imports really well (e.g., VSCode) while moving code files.
For example, if we have function with same name both in `conda.cli.utils` and `conda.utils`, then misuse `..` and `.` may cause unexpected behaviors.

The only advantage which bring to my head is that it can reduce the line length.

.

**Comment by scruel** [comment]
@jezdez Oh, thank you for your explanation, but can you explain a bit more about why conda prefer relative imports?
IMO relative imports have many disadvantages:
- It's really inconvenient for debugging a single source code file, even with the project installed.
- It's kind of against the zen of Python: "Explicit is better than implicit.".
- It's better for one man little demo project rather than a team work huge project.
- IDE don't support relative imports really well while moving code files (~VSCode, are you here?~).

For example, if we have functions with same name both in `conda.cli.utils` and `conda.utils`, then misuse `..` and `.` may cause unexpected behaviors, and for a negligible little dot, we do may make mistakes.

The only advantage which bring to my head now is that it can reduce the line length.

**Comment by jezdez** [comment]
Not really, this is a out-of-scope topic for this issue tracker.

If you're interested in learning more about Python's import system and best practices for existing code bases, I would recommend Stackoverflow or the Python Discord where this topic has been discussed a lot over the years. Thanks for asking the question, I'll close it now as not actionable.
