### ISSUE TITLE
Implement conda-sphinx-theme for conda

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#13300]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Recently, a new theme for conda documentation websites has been developed:

- https://github.com/conda-incubator/conda-sphinx-theme

We want to begin using this theme for the conda documentation website.

While we're at it, we also want to redesign the index page of the website.

### What should happen?

- [x] Set up the new theme for the conda website
- [x] Create new layout and content for the index page of the documentation site

### Additional Context

The roll out of this will be coordinated across all existing documentation sites:

- conda
- conda-build
- conda-docs

### Relevant PRs

- #13298 
- #13331

**Comment by jezdez** [comment]
@travishathaway Please remove miniconda from this list, it's not a conda project and shouldn't be using the same theme. Since miniconda is an Anaconda product, we need to apply the Anaconda theme to that.
