### ISSUE TITLE
Add `__conda` virtual package functionality

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13308]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Ahead of the work to make conda's virtual packages pluggable in #11811, @isuruf opened https://github.com/conda/conda/pull/11764 to add a `__conda` virtual packages, so that packages can rely on a specific version of conda as part of their dependencies. As he described in the PR:

> This is useful for when limiting a package to a conda version. (For eg: we wanted to limit python 3.10 installation to conda <4.13 because of noarch: python issues there, but couldn't and had to use an ugly hack to allow python 3.10 to work on conda 4.13)

**Comment by wolfv** [comment]
I am not against it but I think from a "multi-tool" perspective it could be cool to make this mention some sort of "conda-metadata-revision" instead or something like that.

**Comment by jaimergp** [comment]
Likewise, came here to say this. How are mamba or pixi supposed to use that metadata (I'm assuming this goes in run_constrained). It sounds like an "ASI" (abstract solver interface), which need to be bumped everytime a critical fix or breaking feature is added? Not sure.

**Comment by kenodegard** [comment]
@wolfv I don't understand, do you have an example?

**Comment by wolfv** [comment]
Basically we could make it a mandatory field of every CEP that says "bump `conda-metadata-support`" to N.N and then, when that CEP is implemented in the respective package manager, the virtual package would be bumped. 

I think the `__conda` virtual package is a way of expressing the same intent, but much less precise and harder for other tools to follow (if that makes sense?).

**Comment by isuruf** [comment]
@wolfv, that would require CEPs to be implemented in order.

My original intent was to do something like
```
run_constrained:
  - __conda >=4.20
  - __mamba >=1.3
```

Tying this to CEPs would be wrong IMO. For eg: this was triggered by python 3.10 support in conda because conda had an assumption that python minor versions was one digit.

**Comment by wolfv** [comment]
An alternative idea could be to add __cep13 __cep2 etc packages... but i don't want to complicate things too much

**Comment by jezdez** [comment]
> I am not against it but I think from a "multi-tool" perspective it could be cool to make this mention some sort of "conda-metadata-revision" instead or something like that.

That's a very good point. Could we sidestep the problem by moving the definition of the virtual packages (conda, mamba, pixi etc) into a separate package, e.g. "conda-installer-versions", which would know how to load the current version of a tool in Python and provide it to the conda solver?

**Comment by isuruf** [comment]
It seems like we are talking about different things. Your suggestions do not account for bugs in the tool itself (older conda not supporting python minors with two digits) which was the whole reason for the PR originally.

**Comment by wolfv** [comment]
Ok, point taken. If this is only ever used in the run constraints then it would be fine for mamba/pixi etc as well :)

**Comment by jezdez** [comment]
To clarify, would you be okay with https://github.com/conda/conda/pull/13266 being merged?
