### ISSUE TITLE
Add option to skip flexible search in `conda search`

### ISSUE THREAD

**Issue by mfansler** [conda/conda#13315]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Provide an option to `conda search` to prevent the flexible search from being executed. For example, a flag like `--exact-name` to skip the code:

https://github.com/conda/conda/blob/25e4b1f77faa10c8efd44508de8a5bb011ff3520/conda/cli/main_search.py#L226-L233

### Why is this needed?

There is currently no way to do *only* an exact search with the existing code. If a user only wants exact search and the package is missing, they unnecessarily incur a second flexible search. Further, if the second search is successful, the exit code comes out as 0 - only if both searches are unsuccessful is an exit code 1 given.

For example, I was checking the status of a package `conda-forge::r-nlmixr2` and expecting to get an exit code 1 when it was not found. However, instead the search changed to `*r-nlmixr2*` which enable other packages to be found, resulting in an exit code 0. One thus needs to parse the output or work with JSON to determine if the exact search failed.

### What should happen?

If a package is not available with the exact name provided, then no flexible search should be performed and an exit code of 1 should be returned.

**Comment by mbargull** [comment]
Hi @mfansler,
yes I agree (I never liked this implicit fallback).
As a workaround, you can use a (full string matching) regular expression for the package name, e.g., `conda search '^r-nlmixr2$'`. The regex is applied separately for the channel and name, so even `conda search 'conda-forge::^r-nlmixr2$'` should work.

**Comment by mfansler** [comment]
Thanks, yes that does at least help me get back a non-zero exit code! I put in a PR, but I am not settled on the flag name (draft is `--no-flexible-search`). Let me know if you have an alternative suggestion.
