### ISSUE TITLE
Installer for Linux RISC-V

### ISSUE THREAD

**Issue by luhenry** [conda/conda#13314]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Since https://github.com/conda/conda/pull/12319 released in https://github.com/conda/conda/releases/tag/23.3.0, conda supports the `linux-riscv64` platform. However, I cannot find an installer with miniconda [1] or anaconda [2] for that platform.

The idea is to have such installer available so that users can easily install and use conda on their linux-riscv64 environments.

[1] https://repo.anaconda.com/miniconda/
[2] https://repo.anaconda.com/archive/

### Why is this needed?

Linux RISC-V is gaining momentum, and conda is a fundamental tool in the Python ecosystem. It is then necessary to have an easily accessible installer to install and use conda on RISC-V.

### What should happen?

Have the [Miniconda3-latest-Linux-riscv64.sh](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-riscv64.sh) available for easy installation.

### Additional Context

Conda comes regularly as a required dependency for numerous Python packages.

**Comment by travishathaway** [comment]
Hi @luhenry,

Thanks for filing this issue. We do not manage the available installers for conda. To formally request this, you will need to reach out directly to Anaconda via this project's issue queue:

- https://github.com/ContinuumIO/anaconda-issues/issues

You may also consider reaching out to conda-forge to see if this is something they are currently considering:

- https://conda-forge.org/

They provide additional installers for conda via their "miniforge" project:

- https://github.com/conda-forge/miniforge

I hope this helps! I will now be closing this issue as "off-topic".

**Comment by luhenry** [comment]
@travishathaway perfect, thank you very much for the quick answer! I’ll contact the relevant projects you’ve pointed me to.
