### ISSUE TITLE
Scipy only runs after `conda install -f`

### ISSUE THREAD

**Issue by tdhopper** [conda/conda#1331]
I'm on `conda 3.12.0`. 

I ran 

``` bash
$ conda create -n scipy-test numpy=1.8.2 scipy=0.14.0 python=2.7
$ source activate scipy-test
$ python -c "import scipy"
```

This returns

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tdhopper/anaconda/envs/scipy-test/lib/python2.7/site-packages/scipy/__init__.py", line 114, in <module>
    from scipy.version import version as __version__
ImportError: No module named version
```

At that point, I can run `$ conda list` to get:

```
# packages in environment at /Users/tdhopper/anaconda/envs/scipy-test:
#
numpy                     1.8.2                    py27_0    defaults
openssl                   1.0.1k                        1    <unknown>
pip                       6.1.1                    py27_0    defaults
python                    2.7.9                         1    <unknown>
readline                  6.2                           2    <unknown>
scipy                     0.14.0               np18py27_0    defaults
setuptools                15.2                     py27_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
tk                        8.5.18                        0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

If I then run `$ conda install -f scipy=0.14.0`, `$ python -c "import scipy"` runs without error. `$ conda list` appears to be unchanged:

```
# packages in environment at /Users/tdhopper/anaconda/envs/scipy-test:
#
numpy                     1.8.2                    py27_0    defaults
openssl                   1.0.1k                        1    <unknown>
pip                       6.1.1                    py27_0    defaults
python                    2.7.9                         1    <unknown>
readline                  6.2                           2    <unknown>
scipy                     0.14.0               np19py27_0    defaults
setuptools                15.2                     py27_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
tk                        8.5.18                        0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

I initially assumed it was a numpy/scipy compatability thing, but since it works the second time around I figure it's more likely a conda thing.

**Comment by tdhopper** [comment]
Seems similar to https://github.com/ContinuumIO/anaconda-issues/issues/260 and https://github.com/ContinuumIO/anaconda-issues/issues/240.

**Comment by asmeurer** [comment]
`install -f ` fixing something typically means the package in the package cache was corrupted somehow. `install -f ` re-downloads (if necessary) and re-extracts the package in the package cache before installing it, giving a fresh install. It is a little worrisome that this seems to happen a lot with scipy specifically, but I have no idea why that would be.

**Comment by tdhopper** [comment]
@asmeurer: Does closing mean you're blaming scipy?

**Comment by asmeurer** [comment]
I'm not sure who to blame. But unless you still have a broken installation that you can investigate, there's no way to even tell what is going on.

**Comment by tdhopper** [comment]
@asmeurer: It's reproducible (at least on my system). It happens each time I follow the steps above.

**Comment by asmeurer** [comment]
Oh awesome. Maybe we can get to the bottom of this then.

**Comment by asmeurer** [comment]
So can you run 

```
conda create -n scipy-test scipy=0.14.0 --no-deps
find /Users/tdhopper/anaconda/envs/scipy-test | xargs md5sum
```

and paste the output here. That will help me see what files are missing or corrupted.

**Comment by tdhopper** [comment]
https://gist.github.com/anonymous/4c5a2d9e959f022cc943

**Comment by asmeurer** [comment]
Oh, my bad. Those all match up, but it looks like it was the wrong build of scipy (I didn't notice you were using numpy 1.8). Do the same with `conda create -n scipy-test scipy=0.14.0=np18py27_0 --no-deps`. And maybe reverify that `conda create -n scipy-test2 scipy=0.14.0=np18py27_0` still creates the broken scipy in `scipy-test2` (without ever using `-f`).

**Comment by tdhopper** [comment]
```
tdhopper@~ $ conda create -n ___scipy-test2 scipy=0.14.0=np18py27_0
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /Users/tdhopper/anaconda/envs/___scipy-test2:

The following NEW packages will be INSTALLED:

    numpy:      1.8.2-py27_0      defaults
    openssl:    1.0.1k-1          defaults
    pip:        6.1.1-py27_0      defaults
    python:     2.7.9-1           defaults
    readline:   6.2-2             defaults
    scipy:      0.14.0-np18py27_0 defaults
    setuptools: 15.2-py27_0       defaults
    sqlite:     3.8.4.1-1         defaults
    tk:         8.5.18-0          defaults
    zlib:       1.2.8-0           defaults

Linking packages ...
[      COMPLETE      ]|###########################################################################################| 100%
#
# To activate this environment, use:
# $ source activate ___scipy-test2
#
# To deactivate this environment, use:
# $ source deactivate
#
(reverse-i-search)`scipy': use scipy-test
(reverse-i-search)`python-c': python-config
tdhopper@~ $ python -c "import scipy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/scipy/__init__.py", line 114, in <module>
    from scipy.version import version as __version__
ImportError: No module named version
```

Then: https://gist.github.com/anonymous/a14bc14fcedb5e27ce79

**Comment by tdhopper** [comment]
Doh. Didn't activate the env in that first test. Just a sec.

**Comment by tdhopper** [comment]
```
tdhopper@~ $ source activate ___scipy-test2
discarding /Users/tdhopper/anaconda/bin from PATH
prepending /Users/tdhopper/anaconda/envs/___scipy-test2/bin to PATH
tdhopper@~ (___scipy-test2) $ python -c "import scipy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tdhopper/anaconda/envs/___scipy-test2/lib/python2.7/site-packages/scipy/__init__.py", line 114, in <module>
    from scipy.version import version as __version__
ImportError: No module named version```

**Comment by asmeurer** [comment]
Interesting. All the md5sums seem to be OK (so no files are being corrupted), but you are missing about 500 files, including all of scipy.spatial, scipy.stats, and scipy.weave (as well as some of scipy.sparse, and scipy.version, which is the cause of your error). 

Can you see if `/Users/tdhopper/anaconda/pkgs/scipy-0.14.0-np18py27_0/lib/python2.7/site-packages/scipy/weave/` exists and has files in it?

**Comment by asmeurer** [comment]
And if it does, you might as well jump ahead to the next step, which will be to run `conda --debug create -n ___scipy-test2 scipy=0.14.0=np18py27_0` and paste the output of that (but heads up if the top part has any binstar urls with long tokens in them you'll want to delete that part before pasting as those tokens should not be made public).

**Comment by tdhopper** [comment]
Doesn't exist:

```
tdhopper@~ $ ls -lh ~/anaconda/pkgs/scipy-0.14.0-np18py27_0/lib/python2.7/site-packages/scipy/
total 168
-rw-r--r--   4 tdhopper  staff    24B May  6  2014 ANACONDA_DIST.txt
-rw-r--r--   4 tdhopper  staff   848B Dec  8  2013 BENTO_BUILD.txt
-rw-r--r--   4 tdhopper  staff    20K Feb 26  2014 HACKING.rst.txt
-rw-r--r--   4 tdhopper  staff    11K Feb 16  2014 INSTALL.txt
-rw-r--r--   4 tdhopper  staff   1.5K Dec  8  2013 LICENSE.txt
-rw-r--r--   4 tdhopper  staff   7.3K Apr  2  2014 THANKS.txt
-rw-r--r--   4 tdhopper  staff   1.2K May  6  2014 __config__.py
-rw-r--r--   2 tdhopper  staff   1.6K May  6  2014 __config__.pyc
-rw-r--r--   4 tdhopper  staff   4.5K Feb 26  2014 __init__.py
-rw-r--r--   4 tdhopper  staff   4.6K May  6  2014 __init__.pyc
drwxrwxr-x   6 tdhopper  staff   204B May  7 13:16 _build_utils
drwxrwxr-x  13 tdhopper  staff   442B May  7 13:16 cluster
drwxrwxr-x  11 tdhopper  staff   374B May  7 13:16 constants
drwxrwxr-x  20 tdhopper  staff   680B May  7 13:16 fftpack
drwxrwxr-x  20 tdhopper  staff   680B May  7 13:16 integrate
drwxrwxr-x  30 tdhopper  staff   1.0K May  7 13:16 interpolate
drwxrwxr-x  20 tdhopper  staff   680B May  7 13:16 io
drwxrwxr-x  19 tdhopper  staff   646B May  7 13:16 lib
drwxrwxr-x  67 tdhopper  staff   2.2K May  7 13:16 linalg
drwxrwxr-x  16 tdhopper  staff   544B May  7 13:16 misc
drwxrwxr-x  23 tdhopper  staff   782B May  7 13:16 ndimage
drwxrwxr-x  14 tdhopper  staff   476B May  7 13:16 odr
drwxrwxr-x  52 tdhopper  staff   1.7K May  7 13:16 optimize
-rw-r--r--   4 tdhopper  staff   1.1K Dec  8  2013 setup.py
-rw-r--r--   4 tdhopper  staff   1.4K May  6  2014 setup.pyc
drwxrwxr-x  39 tdhopper  staff   1.3K May  7 13:16 signal
drwxrwxr-x  35 tdhopper  staff   1.2K May  7 13:16 sparse
```

**Comment by asmeurer** [comment]
Interesting. So they get extracted properly (otherwise `install -f` wouldn't work), but somehow at some point they get deleted from the package cache.  It does look like the files that are missing are all alphabetical (the second half of sparse and everything after that). I'm not sure what that means, though. 

If you say you can completely reproduce this (even after doing an `install -f`) then my only suggestion is to run through the reproduction steps and try to notice at exactly what point `~/anaconda/pkgs/scipy-0.14.0-np18py27_0/lib/python2.7/site-packages/scipy/version.py` and the others disappear. Doing everything with `conda --debug` will also help to point out any errors that might otherwise be silenced.

**Comment by tdhopper** [comment]
Unfortunately, I ran `rm -rf ~/anaconda/pkgs/scipy-0.1*`, and everything seems to have worked ever since...

**Comment by asmeurer** [comment]
Well if it ever happens again, let me know here what conda commands were run (they will also be recorded in the `conda-meta/history` file in the environment).

**Comment by asmeurer** [comment]
Actually I want to leave it open this time :) The information you gave me plus the fact that I've seen this several times before has convinced me that there's a legitimate bug in conda somewhere (and even if I can't reproduce it there's still hope that someday I'll figure out what is going on).

**Comment by tdhopper** [comment]
👍 Thanks Aaron.
