### ISSUE TITLE
Improve handling of env_prompt defined in env config

### ISSUE THREAD

**Issue by astaric** [conda/conda#13323]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When a `.condarc` file in an environment defines `env_prompt`, it's value should be used when that environment is activated. Currently the `env_prompt` value from the currently active environment is used.

Given an installation with environments `a` (env_prompt: custom-a) and `b` (env_prompt: custom-b), switching environments produces the following prompts:
```
(base) ➜  envs conda activate a      
(a) ➜  envs conda activate b
custom-a➜  envs conda activate base
custom-b➜  envs 
```

### Why is this needed?

When custom prompts are set in environments to differentiate between them, the current behaviour produces confusing result where the prompt does not match the one defined in an active environment.

Discussions on existing issues about custom env_prompt mention activating the environment twice but that should not be necessary.

### What should happen?

Given an installation with environments `a` (env_prompt: custom-a) and `b` (env_prompt: custom-b), desired prompts should be:
```
(base) ➜  envs conda activate a                                                        
custom-a➜  envs conda activate b                                                        
custom-b➜  envs conda activate base                                                     
(base) ➜  envs 
```

### Additional Context

If a change like this would be acceptable, I can submit a PR with the change.

**Comment by travishathaway** [comment]
Hi @astaric,

Thanks for filing this issue and thanks for choosing the https://github.com/conda/conda/labels/type%3A%3Afeature type too.

I definitely understand where you are coming from and having the env prompt function in this way makes a lot of sense, but the thing I fear is that many of our users may have come to rely on this behavior, and changing it may break the way in which they use conda.

I would encourage you to try and brainstorm some ways you could introduce the new functionality without breaking the way it currently works.

I also encourage anyone else with ideas about how this could implemented to chime in too.

**Comment by astaric** [comment]
@travishathaway, we could limit the new functionality to the cases where `env_prompt` does not use any of the template variables.

I would assume most of the users that modify `env_prompt` use it with template variables. One could argue that using `env_prompt` configured in an environment `.condarc` without template variables does not make much sense with the current implementation. Doing so would use the same prompt for all environments activated from that specific environment which does not seem very useful.

I am open to any other ideas or suggestions on how to avoid breaking existing workflows.

**Comment by astaric** [comment]
Another thing worth mentioning is that implementing this change would provide a nice way of addressing https://github.com/conda/conda/issues/8169 .

If `env_prompt` from the environment being activated is used, disabling the prompt for base environment (only) is as simple as running `conda config --set env_prompt "" --env` from the base environment to disable its prompt and `conda config --set env_prompt "({default_env}) "` to enable the default prompt for all the other environments (for some reason root environment configuration is part of the configuration chain, if it weren't only the first step would be necessary).
