### ISSUE TITLE
Current anaconda/miniconda installer for Debian Linux on Raspberry Pi 4 Model B fails on Unpacking payload step

### ISSUE THREAD

**Issue by MBraddock** [conda/conda#13363]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary
Attempting to install miniconda on Debian, when trying to run bash script, installer fails with note saying that there is no file or directory ~/miniconda3/conda.exe

### Steps to Reproduce
Steps taken per instructions at https://docs.conda.io/projects/miniconda/en/latest/:

```
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O ~/miniconda3/miniconda.sh
sha256sum ~/miniconda3/miniconda.sh ## This shows the right hash per https://repo.anaconda.com/miniconda/ (a60e70ad7e8ac5bb44ad876b5782d7cdc66e10e1f45291b29f4f8d37cc4aa2c8)
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
```

At this point, I get:

```
PREFIX=/home/[My Username]/miniconda3
Unpacking payload ...
/home/[My Username]/miniconda3/miniconda.sh: line 355: /home/[My Username]/miniconda3/conda.exe: No such file or directory
```

`dir miniconda3` now has the following files
conda.exe  install_tmp	miniconda.sh

I have tried this with multiple versions of miniconda, anaconda (also trying without first making the directory) but get the same behaviour with all.

I've looked in my directory to remove all old files that may be interfering, directories - didn't/dont have any .condarc or .conda files.

### Environment Information
OS - Raspbian GNU/Linux 11 (bullseye)
Kernel - Linux 6.1.21-v8+
Architecture - arm64
Raspberry Pi 4 Model B, Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz.

Any help/advice would be much appreciated.

### Conda Info

```shell
N/A - Fails on install
```

### Conda Config

```shell
N/A - Fails on install
```

### Conda list

```shell
N/A - Fails on install
```

**Comment by travishathaway** [comment]
Hi @MBraddock,

The aarch64 installer for Linux from Anaconda/Miniconda does not work on Raspberry Pi 4 Model B. If you would like to use conda on this platform, we recommend using the Miniforge installer instead:

- https://github.com/conda-forge/miniforge

This should get you going. I will be closing this issue now.
