### ISSUE TITLE
Get rid of max_only block in solve2 in resolve

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1338]
Specifically, [this block](https://github.com/conda/conda/blob/0af7790afb6f1e0b532c3c81c67cd2dc325b8873/conda/resolve.py#L468-L495) needs to be removed.  The main blocker for it is performance issues. 

This would fix several issues:
- https://github.com/conda/conda/issues/1334 (features are ignored if a newer version exists without the feature)
- `conda create -n test anaconda python=2` creates an environment with Python 2.6 instead of 2.7.

Probably others as well. Basically, the short circuit can cause the solver to do the "wrong" thing, because it doesn't use the full resolution algorithm. 

`conda create -n test anaconda python=2 --dry` is a good test of the performance. As it is now, it takes 4 seconds (including fetching the index) and with the code removed it takes 55 seconds. 

If we can improve the performance, we should be able to fix https://github.com/conda/conda/issues/918 as well.

**Comment by pelson** [comment]
@asmeurer - any thoughts on how to improve the performance? Right now I'm burning ~10 minutes solving [this specification](https://github.com/SciTools/iris/blob/master/conda-requirements.txt) with the default + scitools channels, and this is because we are not solving for max_only.

Is there anything I can do to help?

**Comment by asmeurer** [comment]
Write a lightweight, fast, open source, Python MILP or Pseudo-boolean optimization solver that beats out the thing conda is using.

**Comment by pelson** [comment]
> Write a lightweight, fast, open source, Python MILP or Pseudo-boolean optimization solver that beats out the thing conda is using.

Cool. Have you already started?

**Comment by pelson** [comment]
I'm guessing you are already familiar with 0install? Did you ever read this document: http://0install.net/solver.html - looks like it is of extreme relevance.

**Comment by QuLogic** [comment]
> Write a lightweight, fast, open source, Python MILP or Pseudo-boolean optimization solver that beats out the thing conda is using.

[libsolv](https://github.com/openSUSE/libsolv) (possibly with [hawkey](https://github.com/rpm-software-management/hawkey) for the Python API)? It's specifically created for package dependency solving. It might need some tweaking to read the conda package database, but the solver is pretty fast (e.g., I can tell it to install ~5000 texlive packages and it can leave out the 200 installed packages, determine the 250-300 conflicts and spit out the remaining in a matter of seconds.)

**Comment by pelson** [comment]
Just as a datapoint, #1702 took a travis-ci install of iris from 800s to 40s. That includes the download and install time. Pretty monumental improvement right there. (that is going to save ```760s * 5``` **per** travis run that Iris does)

**Comment by mcg1969** [comment]
I agree with this change as well.

**Comment by kalefranz** [comment]
Solver logic was reworked in conda 4.0.  Closing this issue.
