### ISSUE TITLE
Publish stable artifacts with checksums during release

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#13399]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently GH provides autogenerated archives with releases. However these have the downside of having unstable checksums. As a result, when they are used as a source in package builds (like in conda-forge), they may pass at one point in time and later fail due to checksum mismatches

Given this, wonder if we can consider a different option where an artifact is generated and uploaded as part of the release process with a checksum. That way consumers of these artifacts will know the artifacts are static and have a checksum they can count on to verify those artifacts

### Why is this needed?

Would improve downstream packaging experience by providing better reliability

### What should happen?

Am a little unsure what the current release process looks like. So what should be done will depend a bit on how that release process is run

Do see that we have [a Rever file]( https://github.com/conda/conda/blob/08a19a3d84c024b8a8c3fdc0e5246cff3175d0c5/rever.xsh#L1 ). If that is what we are using, we could specify [`$GHRELEASE_ASSETS` (like in `conda-smithy`)]( https://github.com/conda-forge/conda-smithy/blob/7a6269113a525205dbef32140280f14d74479c8d/rever.xsh#L19 )

If we are not using Rever, maybe we could use [a GH Actions step to upload artifacts]( https://github.com/actions/upload-artifact )

There might be other reasonable choices depending on what fits best in our release process

### Additional Context

Recently ran into this when releasing 23.11.0 ( https://github.com/conda-forge/conda-feedstock/pull/228#issuecomment-1839685975 ). Though this is not the first time we have seen this issue with GH autogenerated artifacts

**Comment by jezdez** [comment]
This is indeed a good callout, we've seen this a few times (@dbast helped the last time), I wasn't aware of a better way and your ticket is quite timely. 

FWIW https://github.com/conda/conda/blob/main/RELEASE.md is most of the release process, and here are some of the release tickets we've been using: https://github.com/conda/conda/issues/13080, https://github.com/conda/conda/issues/13324 etc.

We're using rever FWIW and make the work for the January release to publish these artifacts.

**Comment by jezdez** [comment]
https://github.com/conda/conda-build/issues/4667 is the relevant ticket for conda-build
