### ISSUE TITLE
Cloning fails with very large untracked files

### ISSUE THREAD

**Issue by birone** [conda/conda#1339]
(Originally raised on [StackExchange](http://stackoverflow.com/questions/30291733/cloning-root-environment-with-anaconda).)

Going through one of (very few available) tutorials on Anaconda, I tried:

```
$ conda create -n rootclone --clone root
```

This failed:

```
src_prefix: '/home/bir/conda'
dst_prefix: '/home/bir/conda/envs/rootclone'
Packages: 49
Files: 471
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/bir/conda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/install.py", line 170, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet)
  File "/home/bir/conda/lib/python2.7/site-packages/conda/cli/install.py", line 91, in clone
    quiet=quiet)
  File "/home/bir/conda/lib/python2.7/site-packages/conda/misc.py", line 177, in clone_env
    data = s.encode('utf-8')
MemoryError
```

This doesn't **appear** to be a swap issue - cloning non-root envs works fine:

```
bir@N2C:~/python$ conda create -n oracleclone --clone oracle
src_prefix: '/home/bir/conda/envs/oracle'
dst_prefix: '/home/bir/conda/envs/oracleclone'
Packages: 9
Files: 0
Fetching package metadata: ....
Linking packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate oracleclone
#
# To deactivate this environment, use:
# $ source deactivate
#
bir@N2C:~/python$ .activate oracleclone
.activate: command not found
bir@N2C:~/python$ . activate oracleclone
discarding /home/bir/conda/bin from PATH
prepending /home/bir/conda/envs/oracleclone/bin to PATH
(oracleclone)bir@N2C:~/python$ which python
/home/bir/conda/envs/oracleclone/bin/python
```

After discussions on StackExchange, it's not clear whether cloning root is needed or desirable. If not, perhaps conda could output some relevant explanation rather than failing like this.

**Comment by asmeurer** [comment]
Do you always get this same error every time you try to clone root?  Cloning root should work just fine.

**Comment by birone** [comment]
Yep 3 times out of 3...

**Comment by asmeurer** [comment]
Oh, I see what is happening. `conda clone` tries to include files that are not tracked by conda. In this instance, it loads the files in memory so it can replace any instances of the prefix in the file. It looks like you have a large file that doesn't fit in memory. We should handle this more intelligently.

**Comment by asmeurer** [comment]
`conda package -u` will show you your untracked files by the way.

**Comment by birone** [comment]
Ok :) I guess if cloning root isn't often needed (?) and this is tricky to fix, modifying `conda package -u` to show the size of the files might be an adequate workaround? (I tried piping the output to `wc -c` but that just gave a single number. & then I was out of linux-fu.)

**Comment by asmeurer** [comment]
The fact that this is the root environment is irrelevant. 

The command `cd ~/conda; conda package -u | xargs du -h -d0` will show you the file sizes.
