### ISSUE TITLE
Incompatibility between conda 23.11.0 and mamba CLI 1.5.3

### ISSUE THREAD

**Issue by mbargull** [conda/conda#13400]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Reported in https://github.com/conda-forge/staged-recipes/pull/24670#issue-2025198169 .
```
mamba install --yes --quiet 'conda-forge-ci-setup=3.*' 'conda-smithy>=3.7.1,<4.0.0a0' conda-forge-pinning 'conda-build>=3.16' 'gitpython>=3.0.8,<3.1.20' requests ruamel.yaml 'pygithub>=2.1.1'
Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
```

### Conda Info

```shell
active environment : base
    active env location : /home/runner/Mambaforge
            shell level : 1
       user config file : /home/runner/.condarc
 populated config files : /home/runner/Mambaforge/.condarc
                          /home/runner/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.12.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/runner/Mambaforge  (writable)
      conda av data dir : /home/runner/Mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/runner/Mambaforge/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /home/runner/Mambaforge/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-1016-azure ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 1001:127
             netrc file : None
           offline mode : False
```

**Comment by jezdez** [comment]
@mbargull I've updated the title of the ticket to not jump to conclusions.

Given that conda is the upstream project, there is a chance that this is just a module deprecation triggering an error in Mamba, which can't be fixed in conda.

**Comment by jezdez** [comment]
Long story short, this seems to be a side effect of https://github.com/conda/conda/pull/13173 and assumptions around the return value of conda internals related to the conda CLI parsing.

I've left the details of my investigation and a patch in https://github.com/mamba-org/mamba/issues/3033#issuecomment-1840688624 and https://github.com/mamba-org/mamba/pull/3036.

Since there is no action to be done on conda's side, I'm inclined to close this issue, but would be interested to hear other opinions from @kenodegard, @travishathaway and @beeankha who worked on https://github.com/conda/conda/pull/13173 at the time.

**Comment by mbargull** [comment]
> Since there is no action to be done on conda's side, I'm inclined to close this issue

I agree.
But maybe let's keep it open for a bit for visibility -- at least until we know what the downstream action items are (e.g., merge https://github.com/mamba-org/mamba/pull/3036 and do a quick patch release or patching on the packaging side).

**Comment by mbargull** [comment]
We have https://github.com/conda-forge/mamba-feedstock/pull/204 on the conda-forge side; needs porting to AnacondaRecipes once ready.

**Comment by jezdez** [comment]
> We have [conda-forge/mamba-feedstock#204](https://github.com/conda-forge/mamba-feedstock/pull/204) on the conda-forge side; needs porting to AnacondaRecipes once ready.

The Mamba 1.x CLI isn't distributed as part of Anaconda's main channel, only `conda-libmamba-solver`, `libmamba` and `libmambapy`, so this should not be necessary. Unless I'm missing something, which is totally possible.

**Comment by mbargull** [comment]
> The Mamba 1.x CLI isn't distributed as part of Anaconda's main channel, only `conda-libmamba-solver`, `libmamba` and `libmambapy`, so this should not be necessary. Unless I'm missing something, which is totally possible.

Ah, didn't know! Then I think we can declare the issue solved on all fronts once we have `conda-forge::mamba=1.5.4` up!
