### ISSUE TITLE
conda config --remove doesn't remove a key

### ISSUE THREAD

**Issue by g24swint** [conda/conda#1342]
I have a very simple .condarc file in my home directory

``` yaml
envs_dirs:
- /prod/user/sam/coaf/adhoc/tjy118/python/conda_flask_envs
- /prod/user/sam/coaf/adhoc/tjy118/python/conda_envs
```

When I then run 

``` shell
conda config --remove envs_dirs 'prod/user/sam/coaf/adhoc/tjy118/python/conda_flask_envs'
```

The key is not removed from the condarc file and I get the error:
`Error: --remove without --force is not implemented yet`

**Comment by asmeurer** [comment]
As the error indicates, at present, you cannot use `--remove` without also using `--force`.

**Comment by anntzer** [comment]
Kindly bumping this issue: it would be nice if the error mentioned that the correct invocation is `conda config --force --remove` and not `conda config --remove --force` (which seems more usual but doesn't actually work -- actually I think that options that are ordered should just be implemented as subcommands instead).

**Comment by soapy1** [comment]
This has been resolved in the more current versions of conda
