### ISSUE TITLE
In "Managing environments" > "Updating an environment", the suggested command can be misleading

### ISSUE THREAD

**Issue by narFnarF** [conda/conda#13444]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In the documentation "[Managing environments](https://docs.conda.io/projects/conda/en/23.11.x/user-guide/tasks/manage-environments.html)" > "[Updating an environment](https://docs.conda.io/projects/conda/en/23.11.x/user-guide/tasks/manage-environments.html#updating-an-environment)", the suggested command can be misleading.

The documentation currently suggest this command:
`$ conda env update --prefix ./env --file environment.yml  --prune`

This can be misleading. Why does it specify `--prefix ./env`? Shouldn't it warn the user that the command need to be edited?
As a new user, it caused me problem because my environment wasn't in `./env`; it was in the default location `/home/MYNAME/miniconda3/envs/MYENV`

My suggestion:
1. Provide the default command to update an environment without specifying a prefix: `$ conda env update --file environment.yml  --prune`
2. If there's a good reason, provide another command specifying the prefix, but explain why the user would need to specify the prefix. Also, make it clear that the user need to adjust the command to point the `--prefix` to the correct location.

**Comment by travishathaway** [comment]
Hi @narFnarF,

Thanks for creating this issue. I am actually planning to go through our "Managing Environments" page soon to revise and update it. I think this is a good recommendation, and I will try to incorporate while doing that work.
