### ISSUE TITLE
When I use #conda install acellerate, it fails:Error: post-link failed for: openssl-1.0.1k-1

### ISSUE THREAD

**Issue by winlandiano** [conda/conda#1344]
When I use this command:

```
#conda install acellerate
```

After downloading, it fails with:Error: post-link failed for: openssl-1.0.1k-1. Just like #1260 ,failed at [Linking Packages...]

Same things happens when I tried `conda update conda`. Does anyone knows why this keeps happening and help me out? Thanks!

Meanwhile,  while downloading, it failed several times with MD5 mismatch. I tried to fix it by `wget url` and download all files needed(at least i think).

What's odd is, after it failed with ''Error: post-link failed for: openssl-1.0.1k-1'', my ~/miniconda/bin/python2.7 is gone. I have to re-setup conda again and  again.

Here is the screen-shot:

![image](https://cloud.githubusercontent.com/assets/5996396/7783727/b75902b8-017e-11e5-8caf-49ffa3ee2a61.png)

before i run `#conda install acellerate` i have these in my /miniconda/bin:
![image](https://cloud.githubusercontent.com/assets/5996396/7783742/29a06ce4-017f-11e5-9c1a-0fb69f78ebc2.png)

afterwards, these are left:
![image](https://cloud.githubusercontent.com/assets/5996396/7783745/3b90ecd0-017f-11e5-9ec3-40ff920bb6be.png)

then i can't execute `conda` anymore for `-bash: /home/ubuntu/miniconda/bin/conda: /home/ubuntu/miniconda/bin/python: bad interpreter: No such file or directory`

**Comment by psanghavi2410** [comment]
I was wondering,  if you would solve this error. Kindly let me know if you found  a way out.

**Comment by winlandiano** [comment]
@psanghavi2410 Haven't yet. I suspect it's maybe that model accelerate support ARM badly since i changed my environment to intel-based-ubuntu then the problem disappeared. That's just what the error info says: post-link failed. Your idea?

**Comment by psanghavi2410** [comment]
I am trying to install it on raspberry2. I get this error every time I try to install or update any package!! I thought conda-build would help. However it fails showing the same error.

**Comment by soapy1** [comment]
@winlandiano is this still an issue for you?
