### ISSUE TITLE
conda init failed on vscode terminal 

### ISSUE THREAD

**Issue by crispto** [conda/conda#13451]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Conda works well on system terminal, but failed to init on vscode's terminal.  well, it can eventually init success, but i have to wait a while, and a bug report is generated

### Conda Info

```shell
active environment : dl
    active env location : /home/boo/miniconda3/envs/dl
            shell level : 2
       user config file : /home/boo/.condarc
 populated config files : /home/boo/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=skylake
                          __cuda=11.4=0
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : /home/boo/miniconda3  (writable)
      conda av data dir : /home/boo/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /home/boo/miniconda3/pkgs
                          /home/boo/.conda/pkgs
       envs directories : /home/boo/miniconda3/envs
                          /home/boo/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/4.15.0-211-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 840473152:840434177
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
channels:
  - defaults
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True
```

### Conda list

```shell
too many packages, this is an init problem, so i dont't paste them up.
```

### Additional Context

this is the error like 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 94, in main_sourced
        print(activator.execute(), end="")
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/activate.py", line 171, in execute
        return getattr(self, self.command)()
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/activate.py", line 143, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/activate.py", line 304, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/activate.py", line 385, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
      File "/home/boo/miniconda3/lib/python3.10/site-packages/conda/activate.py", line 698, in _get_deactivate_scripts
        entry.path for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
      File "/home/boo/miniconda3/lib/python3.10/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /home/boo/miniconda3/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/boo/miniconda3/bin/conda
           CONDA_PREFIX_4=/home/boo/miniconda3/envs/dl
           CONDA_PREFIX_5=/home/boo/miniconda3
         CONDA_PYTHON_EXE=/home/boo/miniconda3/bin/python
               CONDA_ROOT=/home/boo/miniconda3
              CONDA_SHLVL=6
       CPLUS_INCLUDE_PATH=:/usr/include/vtk-6.3
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
                   GOPATH=/home/boo/go
          LD_LIBRARY_PATH=${WorkspaceFolder}/install/deps/lib:
               LD_PRELOAD=<not set>
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/boo/.local/bin:/usr/local/sbin:/usr/local/bin
                          :/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/
                          sbin:/home/boo/scripts:/home/boo
                          /.local/bin:/usr/local/cuda/bin:/home/boo/keshub/ke
                          shub:/usr/local/go/bin:/home/boo/go/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
            shell level : 6
       user config file : /home/boo/.condarc
 populated config files : /home/boo/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=skylake
                          __cuda=11.4=0
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : /home/boo/miniconda3  (writable)
      conda av data dir : /home/boo/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /home/boo/miniconda3/pkgs
                          /home/boo/.conda/pkgs
       envs directories : /home/boo/miniconda3/envs
                          /home/boo/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/4.15.0-211-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 840473152:840434177
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

And i have found how to fix it 
int conda/activate.py,  I add a check  if prefix is None（the code being commented ）, the problem vanished.
 but i think there is a bug in the code of upstream , there should not be a None value of prefix come in !
  
![image](https://github.com/conda/conda/assets/18901859/719951e1-3187-4366-b519-6521662c3687)

**Comment by travishathaway** [comment]
Hi @crispto,

Thanks for reporting this providing some important background data. We will look into this issue at our nearest convenience, but we cannot promise that this will be resolved timely as there are currently many other issues in our backlog.

Feel free to submit a pull request yourself if you are interested in coming up with your own fix. We'll be happy to review it.

**Comment by JiayouZhang** [comment]
I met this issue today. Before today I've never met this issue.

The bug seems to be related to the vscode. If I directly login the terminal using ssh, this error message doesn't show up. 

I log in 3 vscode-servers from the same windows PC:

```
VSCode client: 1.85.1
Remote - SSH 0.107.1

Python extension 2022.20.1 # wsl -> bug!
Python extension 2022.4.0 # remote server1 -> no bug
Python extension 2023.22.1 # remote server2 -> bug!
```

I don't know why the bug can only be reproduced in 2 of the 3 servers. Maybe it's some AB-testing?

More detailed version information:

VSCode:
```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```
WSL conda error info:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 111, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 191, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 157, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 335, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 423, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kialan/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 755, in _get_deactivate_scripts
        for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 76, in join
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /home/kialan/miniconda3/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/kialan/miniconda3/bin/conda
           CONDA_PREFIX_2=/home/kialan/miniconda3/envs/e3nn
           CONDA_PREFIX_3=/home/kialan/miniconda3
         CONDA_PYTHON_EXE=/home/kialan/miniconda3/bin/python
               CONDA_ROOT=/home/kialan/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/kialan/.vscode-
                          server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/us
                          r/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/
                          usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/NVIDIA GPU
                          Computing Toolkit/CUDA/v12.2/bin:/mnt/c/Program Files/NVIDIA GPU
                          Computing Toolkit/CUDA/v12.2/libnvvp:/mnt/c/WINDOWS/system32:/mnt/c/WI
                          NDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowe
                          rShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program
                          Files/NVIDIA Corporation/Nsight Compute 2023.2.1/:/mnt/c/Program Files
                          (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/dotnet/:/mnt/c/Program
                          Files (x86)/ZeroTier/One/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/ki
                          alan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/kialan/AppData/L
                          ocal/Programs/Microsoft VS Code/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 4
       user config file : /home/kialan/.condarc
 populated config files : /home/kialan/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=5.15.133.1=0
                          __unix=0=0
       base environment : /home/kialan/miniconda3  (writable)
      conda av data dir : /home/kialan/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /home/kialan/miniconda3/pkgs
                          /home/kialan/.conda/pkgs
       envs directories : /home/kialan/miniconda3/envs
                          /home/kialan/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Linux/5.15.133.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


Timeout reached. No report sent.
```

Server 2 conda error info:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 110, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 203, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 168, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 347, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 437, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/home/jiayou.zhang/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 769, in _get_deactivate_scripts
        for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 76, in join
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /lustre/home/jiayou.zhang/miniconda3/bin/conda shell.posix activate openfold_env`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/lustre/home/jiayou.zhang/miniconda3/bin/conda
           CONDA_PREFIX_2=/lustre/home/jiayou.zhang/miniconda3/envs/colabfold
           CONDA_PREFIX_3=/lustre/home/jiayou.zhang/miniconda3
         CONDA_PYTHON_EXE=/lustre/home/jiayou.zhang/miniconda3/bin/python
               CONDA_ROOT=/lustre/home/jiayou.zhang/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                  MANPATH=::/opt/clmgr/man:/opt/sgi/share/man:/opt/clmgr/share/man:/opt/clmgr/li
                          b/cm-cli/man
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/shar
                          e/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles:/
                          lustre/apps/modules/modulefiles:/opt/nvidia/hpc_sdk/modulefiles
                     PATH=/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/lustre/home
                          /jiayou.zhang/.vscode-
                          server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/lu
                          stre/scratch/users/Jiayou.Zhang/biotools/mmseqs/bin:/lustre/home/jiayo
                          u.zhang/miniconda3/envs/colabfold/bin:/lustre/home/jiayou.zhang/minico
                          nda3/condabin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bi
                          n:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local
                          /sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bi
                          n:/sbin:/bin:/sbin:/bin:/sbin:/bin:/lustre/scratch/users/Jiayou.Zhang/
                          biotools/mmseqs/bin/:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt
                          /sgi/bin:/lustre/home/jiayou.zhang/.vscode-
                          server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/lu
                          stre/scratch/users/Jiayou.Zhang/biotools/mmseqs/bin:/lustre/home/jiayo
                          u.zhang/miniconda3/envs/colabfold/bin:/lustre/home/jiayou.zhang/minico
                          nda3/condabin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bi
                          n:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local
                          /sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bi
                          n:/sbin:/bin:/sbin:/bin:/sbin:/bin:/lustre/home/jiayou.zhang/.vscode-
                          server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/op
                          t/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/sbin
                          :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/sb
                          in:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 4
       user config file : /lustre/home/jiayou.zhang/.condarc
 populated config files : 
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen3
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /lustre/home/jiayou.zhang/miniconda3  (writable)
      conda av data dir : /lustre/home/jiayou.zhang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /lustre/home/jiayou.zhang/miniconda3/pkgs
                          /lustre/home/jiayou.zhang/.conda/pkgs
       envs directories : /lustre/home/jiayou.zhang/miniconda3/envs
                          /lustre/home/jiayou.zhang/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/5.15.0-60-generic ubuntu/22.04.2 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 923002912:923000513
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>


Timeout reached. No report sent.
```

**Comment by JiayouZhang** [comment]
Just tried. If I turn off python extension in vscode, there will be no bug information showing up.

**Comment by juandpinto** [comment]
I'm also having the same issue. Disabling the Python extension solves it, but re-enabling the extension brings it back.

**Comment by okkymabruri** [comment]
Hi All, I'm also experiencing the same issue. 

Disabling the Python extension resolves it, but re-enabling the extension causes the problem to return. 

There's a problem with Conda in `os.scandir(join(prefix, 'etc', 'conda', 'deactivate.d'))`

**Comment by Daraan** [comment]
The problem is the extensions *unsets* `CONDA_PREFIX` which causes `join(prefix, ...)` to fail.

---

For the time being you have to manually set `CONDA_PREFIX` for the time being which depends on the environment.

For the `base` environment you can use:  
`export CONDA_PREFIX=$CONDA_ROOT`

for others craft it manually:  
`export CONDA_PREFIX=$CONDA_ROOT/envs/<yourenvname>`

**Comment by okkymabruri** [comment]
@crispto 
I resolved that issue by enabling terminal.integrated.inheritEnv setting.

`"terminal.integrated.inheritEnv": true`

**Comment by csanry** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

Faced a similar issue. This worked for me.

**Comment by bobmayuze** [comment]
> terminal.integrated.inheritEnv

This workaround works for me as well

**Comment by CurssedCoffin** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

This works, thanks

**Comment by piwawa** [comment]
> I don't know why the bug can only be reproduced in 2 of the 3 servers. Maybe it's some AB-testing?

Brilliant! How did you figure it out?

**Comment by yeahdongcn** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

This works great for me too. The only problem that bothers me is my terminal displays the conda env twice. 

<img width="463" alt="Screenshot 2024-02-27 at 10 02 08" src="https://github.com/conda/conda/assets/2831050/e010bb0d-e7c5-4f63-a3c6-f3f6fc026ac5">

**Comment by ablozhou** [comment]
The same error on:
```
linux ubuntu 22.04
conda env
python 3.12
```
after add 
```
"terminal.integrated.inheritEnv": true
```
to vscode application settings.json, it works, but there are too env previx like:

(myenv)(myenv) aaa@svr:~/git/ttt $

**Comment by jiho264** [comment]
> The same error on:
> 
> ```
> linux ubuntu 22.04
> conda 23.7.4
> venv python 3.12
> os python 3.10
> ```
> 
> after add
> 
> ```
> "terminal.integrated.inheritEnv": true
> ```
> 
> to vscode application settings.json, it works, but there are two env prefixes like:
> 
> ```
> (myenv) (myenv) user@svr:~/git/prj $ 
> ```
> 
> if I disable the python extention, then it looks ok. But I can't debug. And then I found I installed another "Python extension pack", and I disabled it. All works very well.

I saw same problem.... I recommend to try """conda deactivate""" double times. that is all. if you add "source activate myenv" on ~/.bashrc, plz remove that.

**Comment by mhy1264** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

works for me, thanks for help

**Comment by lrtz-v** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

Brilliant!! thanks for help

**Comment by siavava** [comment]
> @crispto I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

Works &mdash; thanks! 😄

**Comment by SAKURA-CAT** [comment]
> 同样的错误：
> 
> ```
> linux ubuntu 22.04
> conda 23.7.4
> venv python 3.12
> os python 3.10
> ```
> 
> 添加后
> 
> ```
> "terminal.integrated.inheritEnv": true
> ```
> 
> 对于 vscode 应用程序 settings.json，它可以工作，但有两个 env 前缀，例如：
> 
> ```
> (myenv) (myenv) user@svr:~/git/prj $ 
> ```
> 
> 如果我禁用 python 扩展，那么看起来没问题。 但我无法调试。 然后我发现我安装了另一个“Python扩展包”，然后我禁用了它。 一切都运转良好。

Set `"terminal.integrated.shellIntegration.enabled": true` can solve two conda's problem

**Comment by wey-gu** [comment]
Thanks @crispto  @SAKURA-CAT ! this helps.



```json
{
    "terminal.integrated.inheritEnv": true,
    "terminal.integrated.shellIntegration.enabled": true
}
```

**Comment by Willian-Zhang** [comment]
having this again, working around with
```
        if prefix is None:
          prefix = ""
```


can confirm 
```
{
    "terminal.integrated.inheritEnv": true,
    "terminal.integrated.shellIntegration.enabled": true
}
```

env
```
VSCode Version: 1.90.2 (Universal)
Python plugin v2024.10.0
```

**Comment by piwawa** [comment]
> Set `"terminal.integrated.shellIntegration.enabled": true` can solve two conda's problem

I have set this, but still got double env name:

![image](https://github.com/user-attachments/assets/2fb1c03d-f9d7-4bbb-b810-3f5a9fabf3de)

**Comment by YuGui1027** [comment]
> [@crispto](https://github.com/crispto) I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

omg bro, thank you so much! this damn problem has been bothering me all afternoon.

**Comment by sheyestherrr** [comment]
> [@crispto](https://github.com/crispto) I resolved that issue by enabling terminal.integrated.inheritEnv in VScode setting.
> 
> `"terminal.integrated.inheritEnv": true`

It works fine, thanks for help !!

**Comment by marsxw** [comment]
"terminal.integrated.inheritEnv": true,
or reenable python extensions work.

**Comment by sheyestherrr** [comment]
您发给我的信件已经收到。             我们将尽快回复您并与您取得联系。             感谢您的来信！            ***@***.*** is an automatic reply, confirming that your e-mail was received.Thank you!

**Comment by Edenzzzz** [comment]
You can also add this line in conda init in ~/.zshrc or ~/.bashrc.

![Image](https://github.com/user-attachments/assets/325a0590-c443-41a3-8e83-d3766d32b69e)

**Comment by sheyestherrr** [comment]
您发给我的信件已经收到。             我们将尽快回复您并与您取得联系。             感谢您的来信！            ***@***.*** is an automatic reply, confirming that your e-mail was received.Thank you!

**Comment by g-h-chen** [comment]
`conda init bash` works for me.

**Comment by Xu-Huihui** [comment]
> terminal.integrated.inheritEnv

thanks god. It saves my life.
