### ISSUE TITLE
Command window immediately closes when I try to open the conda app

### ISSUE THREAD

**Issue by Iampicklerick** [conda/conda#13462]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I think there's a larger issue with my installation, but admittedly I am new to this stuff. When I type Conda into the windows search panel, nothing comes up which is an issue because the application is definitely installed.

I can manually navigate to c:\users\username\anaconda3 and find the _conda application. When I click on it, I get the error where the cmd window opens and I see text running for a second, and then it immediately closes. Does anyone know how to fix this?

One other thing that may cause issues is that my username has a space in it. I realized after I set up the computer that I made the mistake but I never fixed it. I'm not sure if that contributes to the issue. Thank you in advance.

### Conda Info

```shell
conda : The term 'conda' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ conda info
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNo
   tFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Conda Config

```shell
conda : The term 'conda' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ conda config --show-sources
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNo
   tFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Conda list

```shell
conda : The term 'conda' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ conda lise --show-channel-urls
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNo
   tFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Additional Context

Obviously something is wrong with the install given the responses above. I ran a general installation so I am not sure what causes this issue.

**Comment by travishathaway** [comment]
Hi @Iampicklerick,

Thanks for filing this and sorry to hear you are having trouble with your installation. Unfortunately, the maintainers of conda do not have the capacity to provide individualized support.

It looks like you are trying to use Anaconda Distribution, so I would recommend going over their installation instructions and troubleshooting guides:

- [Anaconda Distribution - Installing on Windows](https://docs.anaconda.com/free/anaconda/install/windows/)
- [Anaconda Distribution - Troubleshooting](https://docs.anaconda.com/free/anaconda/reference/troubleshooting/)
