### ISSUE TITLE
Installing python library rembg inside Anaconda Navigator

### ISSUE THREAD

**Issue by TonyVM** [conda/conda#13505]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to install rembg in a python 3.11.5 env inside conda and I got this error
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==14.2.1=0
  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__osx==14.2.1=0
  - feature:|@/osx-arm64::__unix==0=0
  - rembg -> click -> __unix
  - rembg -> click -> __win
  - rembg -> numpy -> __osx[version='>=10.9']

Your installed version is: not available
-------------------
Note: my OS is MacOS Sonoma 14.2.1 with Apple M1 chip

Any suggestion?
Thanks

**Comment by travishathaway** [comment]
Hi @TonyVM,

First off, make sure you are installing this in a new environment:

```
conda create -n rembg -c conda-forge rembg
```

If that still fails, I would suggestion filing an issue with the package maintainers here:

- https://github.com/conda-forge/rembg-feedstock

Hope that helps.
