### ISSUE TITLE
Unable to install anaconda on MacBook Air with M2 Chip

### ISSUE THREAD

**Issue by bcheerla4509** [conda/conda#13525]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After writing files and configuration when I click on continue, installation final page shows installation failed and please contact manufacturer. Can't find any install log file as such. How can I proceed?

**Comment by bcheerla4509** [comment]
[install.log](https://github.com/conda/conda/files/14047081/install.log)
Please find the install log file attached.

**Comment by travishathaway** [comment]
Hi @bcheerla4509,

We unfortunately cannot provide direct support for the Anaconda installer. To file an issue for that, please visit https://github.com/ContinuumIO/anaconda-issues/issues

There's currently another issue open there reporting similar troubles using the Anaconda installer on macOS:

- https://github.com/ContinuumIO/anaconda-issues/issues/13341

It might be worth just commenting on that issue. Please include as much information about your system as possible.

The last piece of advice I can give you is to try an alternative installer. Anaconda also makes a command line installer for macOS that you could use:

- https://repo.anaconda.com/archive/Anaconda3-2023.09-0-MacOSX-x86_64.sh

I hope this helps.
