### ISSUE TITLE
Set up conda maintainer team per conda governance policy

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13526]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Following the success of the equivalent for conda-build in https://github.com/conda/conda-build/issues/4698, I'd like to propose setting up a conda team under the conda governance policy that would eventually replace the current Anaconda-heavy `conda-core` team.

### Why is this needed?

`conda-core` is mostly a historic artifact from when conda was primarily maintained by Anaconda staff and would be disbanded in favor of a new `conda-maintainers` team (to be actively inclusive of non-developer members).

### What should happen?

- [x] Set up a list of people in this ticket that currently can at least write to conda repo
- [x] Add people that are trusted community members and ask if they would like to be members of that team
- [x] Inform members of the `conda-core` team of this effort
- [x] Commit to the change by updating the CI and `CODEOWNERS` files and documentation
  - [x] https://github.com/conda/conda/pull/14183 
- [x] Remove the conda repo from the legacy `conda-core` team

### Conda maintainer team

The **conda maintainer team** is a team of individuals that have shown a proven track record of contributions to the conda project (the package and environment manager software hosted under https://github.com/conda/conda) and a commitment to the [conda governance policy](https://github.com/conda/governance) and its focus on a multi-stakeholder community. The team is a _project team_ per conda governance policy.

- A petition for commit rights is made to the current members. If this petition passes according to the voting rules for how to [nominate a new member of a Project Team](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/README.md#nominate-new-member-of-a-community-project-team) (or its successor voting rule), the petitioner is granted write access and added to the team.

- Removal of individuals from the team is following the voting rules for how to [remove a member of a Project Team](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/README.md#remove-a-project-team-member) (or its successor voting rule).

### List of people with permissions

This is a list of current permissions, plus the proposal for a new "conda maintainers" team with write and merge permissions for the conda repo.

| User | legacy "conda-core" | write, but not merge | Quansight | new "conda maintainers" |
|------| -----------|----------------------|-----------|-----------------------|
| Abaal | | x | x | |
| beeankha | x | | | x |
| chenghlee | x | | | x |
| dholth | x | | | x |
| ForgottenProgramme | x | | | x |
| goanpeca (individual) | | x | | |
| isuruf | | x | x | |
| jaimergp | | x | x | x |
| jezdez | x | | | x |
| kathatherine (docs) | | x | | |
| kenodegard | x | | | x |
| marcoesters | x | | | |
| mbargull (individual) | | x | | x |
| pseudoyim | x | | | |
| trallard | | x | x | |
| travishathaway | x | | | x |
| zklaus | | x | x | |

**Comment by jaimergp** [comment]
> current Anaconda-heavy conda-core team

I would add that is Anaconda-only 😄 

> new conda-maintainers team (to be actively inclusive of non-developer members)

I'd like to bring merge rights here. Which group will be granted merge rights? Current `main` branch is protected so only conda-core can merge. This in practice means that only Anaconda contributors can merge, regardless the seniority or experience.

I'd advocate for a new team (not sure about the name) where the members are chosen by seniority and proven contribution record to the project. This team would be the only one that can merge to `main` and other release branches. We would probably need to elaborate a bit on eligibility and the "adding a new member" process but for now I want to fly this idea and see what the thoughts are.

**Comment by jezdez** [comment]
> > current Anaconda-heavy conda-core team
> 
> I would add that is Anaconda-only 😄
> 
> > new conda-maintainers team (to be actively inclusive of non-developer members)
> 
> I'd like to bring merge rights here. Which group will be granted merge rights? Current `main` branch is protected so only conda-core can merge. This in practice means that only Anaconda contributors can merge, regardless the seniority or experience.

Yes, this is the reason for this ticket, to set up a team that is not focused on Anaconda-only maintainers, but also includes members from the larger community.

> I'd advocate for a new team (not sure about the name) where the members are chosen by seniority and proven contribution record to the project. This team would be the only one that can merge to `main` and other release branches. We would probably need to elaborate a bit on eligibility and the "adding a new member" process but for now I want to fly this idea and see what the thoughts are.

Yes, we should call it `conda-maintainers` since that's the function of someone who can write changes and merge things as well.

The next step is to set up a small charter that describes these levels of permissions IMO.

**Comment by jezdez** [comment]
Oh btw, I've updated the list of people with specific access to the conda repo.

**Comment by jezdez** [comment]
@conda/conda-core Hey team, could you please take a look at the proposed new `conda maintainers` team above?

The core goal of the new conda maintainer team is to have a track record of contribution to conda, which conda-core has essentially only gotten by way of being employed at Anaconda. We intend to overcome this and switch to a team charter that follows the multi-stakeholder model as described in the conda governance policy, where other community members who have contributed to conda, can join the new `conda maintainer` team on request. [See the governance policy about teams](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/README.md#project-teams-details).

In particular to note compared to the legacy conda-core team: 

- @pseudoyim and @marcoesters would _lose_ merge permissions (but not write permissions) given that they haven't contributed long to conda itself
- @jaimergp and @mbargull would gain full permissions

**Comment by jezdez** [comment]
@jaimergp I've added a blurb in the issue description that describes a proposed process to ask for team membership, which boils down to "ask the team for permission", with a team vote needed and a simple majority to pass (as described in the governance policy).

**Comment by jezdez** [comment]
Added.

**Comment by rootsmusic** [comment]
And [conda-docs](https://github.com/conda/conda-docs)?

**Comment by jaimergp** [comment]
What needs to be done here so the proposed teams are configured as described above?

**Comment by jezdez** [comment]
I think we've waited appropriately long for this to get feedback, I'll set up the new team `conda-maintainers` team in the conda org.

**Comment by jezdez** [comment]
I've created the new @conda/conda-maintainers team and opened #14183.

**Comment by jakirkham** [comment]
Is it too late to sign up?

**Comment by jezdez** [comment]
@jakirkham per governance policy, it's never "too late" since the new team follows governance policy rules around project teams. See above what I wrote, copying from the governance policy:

> A petition for commit rights is made to the current members. If this petition passes according to the voting rules for how to [nominate a new member of a Project Team](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/README.md#nominate-new-member-of-a-community-project-team) (or its successor voting rule), the petitioner is granted write access and added to the team.

Since you haven't been in the original conda-core team, I think it's sensible to follow this voting rule.

To quote:

> **Nominate new member of a Community Project Team**
>
> The proposer must provide a sufficient justification as to why the nominee should be welcomed into the Project Team. Prior work on the project is an essential part of the nomination process. The voting body for these votes are the current members of the [Project Team](https://github.com/conda/governance/blob/e30676d2cc16545a495b4b09ab4ada0a63f5836c/README.md#project-teams) at the time the nomination is made.
>
> - Sensitive
>   Voting: One of the following:
>        at least 3 members voting, with all votes being "yes"
>        at least 50% participation, with greater than 50% "yes" votes to pass

**Comment by jezdez** [comment]
I've completed the steps above, thank you everyone for the help making this happen. Please let me know if there are concerns or any bugs/setup issues surfacing following the changes.

@jakirkham I'm going to close the ticket since I think the original issue has been resolved, but that doesn't take away what I said above about joining the new team following the official rules!

**Comment by jaimergp** [comment]
Just realized that the `source::` issue labels might still hint at the previous composition of the team. Maybe it's worth updating them:

https://github.com/conda/conda/labels?page=3&sort=name-asc

<img width="918" alt="image" src="https://github.com/user-attachments/assets/f67029e3-e2cc-40d2-99cd-dd222995e47f">
