### ISSUE TITLE
Add matching `use_repodata_zst` flag, environment variable to match command line argument.

### ISSUE THREAD

**Issue by dholth** [conda/conda#13528]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The `--no-repodata-zst` flag, used to suppress a default check for `repodata.json.zst`, should have counterparts in `.condarc` and an environment variable.

Also renamed to `--[no-]use-repodata-zst`

**Comment by dholth** [comment]
So we do have a test for the environment variable here https://github.com/conda/conda/blob/main/tests/gateways/test_jlap.py#L371-L378
but, on the command line, 
`CONDA_NO_REPODATA_ZST=True CONDA_DEBUG=True python -m conda search -c conda-forge "conda>23.9"`
shows
`DEBUG conda.gateways.repodata.jlap.interface:__init__(38): Using ZstdRepoInterface`.
What's going on here?

**Comment by dholth** [comment]
Tempted to change all to (no_)use_repodata_zst matching mamba, and have a --no/--use-repodata-zst command line argument?

**Comment by jezdez** [comment]
> Considering changing all to (no_)use_repodata_zst matching mamba, and have a --no/--use-repodata-zst command line argument

If that brings us to alignment with mamba, let's go for it

**Comment by dholth** [comment]
Renamed.

**Comment by jezdez** [comment]
Fixed via #13530
