### ISSUE TITLE
failed to upgrade from anaconda 1.9.1

### ISSUE THREAD

**Issue by biocyberman** [conda/conda#1353]
Something went terribly wrong, I lost my anaconda setup. Is there a way for me to reinstall anaconda while keeping my environments?

I ran this command as 
conda update --prefix /home/user/bin/opt/anaconda anaconda

Some from stdout:

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    anaconda-1.9.1             |       np18py27_0
    argcomplete-0.6.7          |           py27_0
    astropy-0.3.0              |       np18py27_0
    beautiful-soup-4.3.1       |           py27_0
    binstar-0.4.4              |           py27_1
    blz-0.6.1                  |       np18py27_0
    bokeh-0.4.1                |       np18py27_0
    boto-2.25.0                |           py27_0

```zsh
An unexpected error has occurred, please consider sending the#########################                                                                                                                                                                                           |  25%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/user/bin/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    # Silence logging info to avoid interfering with JSON output
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 266, in install
    build_inst = [m['build_number'] for m in installed_metadata if
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 392, in execute_actions
    specs.append('conda')
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 375, in execute_plan
    log.debug('HF specs=%r' % specs)
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 331, in link
    names_linked = {install.name_dist(dist): dist for dist in linked}
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 428, in link
    if fn.endswith('.tar.bz2'))
  File "/home/user/bin/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    except OSError as e:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an binary lib/libfontconfig.so.1.8.0'
user@myserver conda info 
zsh: /home/user/bin/opt/anaconda/bin/conda: bad interpreter: /home/user/bin/opt/anaconda/bin/python: no such file or directory
```

**Comment by biocyberman** [comment]
Here is what I did so fa:
1. move `anaconda/envs` out of `anaconda`. 
2. remove `anaconda` dir.
3. install the latest anaconda 
4. move `envs` back into anaconda.

Things seems to works so far.

**Comment by asmeurer** [comment]
That would fix it. `conda update conda` should have also fixed it.

**Comment by biocyberman** [comment]
`conda update conda` did not work because the installation somehow broke completely as you can see in the last command above `conda info` failed because it could not find `python`

**Comment by lzkelley** [comment]
I'm having the same problem --- initially from trying to install matplotlib --- but it occurs when trying to update anaconda as well.  I don't have root access, is there a way to fix this without reinstalling?

**Comment by biocyberman** [comment]
@lzkelly you can try 4 steps i mentioned above.  That can preserve your installed package and setting

**Comment by lzkelley** [comment]
Thanks @biocyberman, but I don't have permissions to remove/modify anaconda itself.  I can only modify the environments I create locally in my User directory.

**Comment by biocyberman** [comment]
I missed to address that aspect of your question. Look at it again, I think you need to ask you administrator to upgrade anacoda first. Alternatively,  and now I am talking off topic again: One of the best merit of using anacoda is that it lets you manage totally ISOLATED python evironments. And I would say most of the case people do NOT use/need root access to setup anaconda. You can do the same. 
Just download and install anaconda at your home folder (i.e. ~/bin/opt). And following is my setup:

Add the following in to one of these files: bashrc/.profile/.zshrc depending on which shell you use:

```shell
# Because I installed conda on ~/bin/opt
alias activate_conda='export PATH="$HOME/bin/opt/anaconda/bin:$PATH"'
# Make some other fancy alias if you like. 
```
So ancodna is not activated by default, when use want to use it, just type this first:
`activate_conda` 

After that you can use `source activate your_env` and run python programs that were installed on your conda_env.
