### ISSUE TITLE
`UnavailableInvalidChannel: HTTP 404 NOT FOUND`; channels when `conda install` does not follow `conda config --show channels` nor `./condarc`

### ISSUE THREAD

**Issue by klai001** [conda/conda#13533]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

my goal was to remove the url link as a channel in my conda because anything i have tried to `conda install`
loops back to searching the url even with the `-c` flag. e.g.
`conda install -c conda-forge r-magick`
gives 

> Channels:
>  - conda-forge
>  - genomedk
>  - bioconda
>  - defaults
>  - https://anaconda.org/conda-forge/r-seurat/4.3.0/download
>  - anaconda
> Platform: linux-64
> Collecting package metadata (repodata.json): failed
> 
> UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel conda-forge/r-seurat/4.3.0/download <https://anaconda.org/conda-forge/r-seurat/4.3.0/download>

things i have tried:
1)`conda config --remove channels `https://anaconda.org/conda-forge/r-seurat/4.3.0/download`. but it says its
not a valid channel on my list

2)so i tried `conda config --show channels` this gives nothing like the channels showed when i wanted to run `conda install -c conda-forge r-magick`

```
> conda config --show channels
> channels:
>   - genomedk
>   - bioconda
>   - defaults
>   - conda-forge
```

3)searching .condarc again shows nothing like the channels when i run  `conda install -c conda-forge r-magick`

> solver: libmamba
> channels:
>   - genomedk
>   - bioconda
>   - defaults
>   - conda-forge
> channel_priority: strict

4) i ran a `conda clean -all` but that doesnt help in anyway 

### Conda Config

```shell
conda config --show-sources
==> /home/abcd/.condarc <==
channel_priority: strict
channels:
  - genomedk
  - bioconda
  - defaults
  - conda-forge
solver: libmamba

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
r-rstudioapi              0.15.0            r42hc72bb7e_0    conda-forge
r-rtsne                   0.17              r42h7ce84a7_0    conda-forge
r-rversions               2.1.2             r42hc72bb7e_2    conda-forge
r-rvest                   1.0.3             r42hc72bb7e_2    conda-forge
r-sass                    0.4.8             r42ha503ecb_0    conda-forge
r-scales                  1.3.0             r42hc72bb7e_0    conda-forge
r-scattermore             1.2               r42ha503ecb_1    conda-forge
r-sctransform             0.4.1             r42h08d816e_0    conda-forge
r-selectr                 0.4_2             r42hc72bb7e_3    conda-forge
r-sessioninfo             1.2.2             r42hc72bb7e_2    conda-forge
r-seurat                  4.3.0             r42h38f115c_0    https://anaconda.org/conda-forge/r-seurat/4.3.0/download
r-seuratobject            5.0.1             r42ha503ecb_0    conda-forge
r-shiny                   1.8.0             r42h785f33e_0    conda-forge
r-sitmo                   2.0.2             r42ha503ecb_2    conda-forge
r-sourcetools             0.1.7_1           r42ha503ecb_1    conda-forge
r-sp                      2.1_2             r42h57805ef_0    conda-forge
```

**Comment by jaimergp** [comment]
This is https://github.com/conda/conda-libmamba-solver/issues/411. Can you try setting `CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1` and re-running? I wonder if you installed `r-seurat` from a direct URL.
