### ISSUE TITLE
libffi*.so is not downward compatible

### ISSUE THREAD

**Issue by xuancong84** [conda/conda#13548]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am running `python-vlc` and `pygame` on Linux x86_64 to play any video or screen rendering. I have two `miniconda3` environments, one is old, one is new. The old one is working while the new one does not work with the following error:
```
xuancong@mx:~/projects/*$ ./miniconda3/bin/python -i debug.py 
>>> libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  43
  Current serial number in output stream:  44
```

I used `lsof -p <PID>` to poke all dynamic libraries that is used. It turns out that the problem lies in `miniconda3/lib/libffi*.so`.
The old conda environment (working) has:
```
67214 Jul  7  2020 libffi.a
   15 Apr 28  2022 libffi.so -> libffi.so.7.1.0
   15 Apr 28  2022 libffi.so.6 -> libffi.so.7.1.0
   15 Apr 28  2022 libffi.so.7 -> libffi.so.7.1.0
50664 Jul  7  2020 libffi.so.7.1.0
```
while the new conda environment (not working) has:
```
    15 Jan 31 17:14 libffi.7.so -> libffi.so.8.1.2
    15 Jan 31 17:14 libffi.8.so -> libffi.so.8.1.2
 97758 May 10  2023 libffi.a
    15 Jan 31 17:14 libffi.so -> libffi.so.8.1.2
    15 Jan 31 17:14 libffi.so.7 -> libffi.so.8.1.2
    15 Jan 31 17:14 libffi.so.8 -> libffi.so.8.1.2
 72144 May 10  2023 libffi.so.8.1.2
```
The root cause of this error turns out to be that `libffi.so.8` is not downward compatible with `libffi.so.7`, so that you cannot simply soft-link all versions of `libffi.so` to `libffi.so.8`. So all I did was to copy over `libffi.so.7.1.0` from the old conda environment to the new environment and do the soft-link properly as follows:
```
   15 Jan 31 17:03 libffi.7.so -> libffi.so.7.1.0
   15 Jan 31 09:48 libffi.8.so -> libffi.so.8.1.2
97758 May 10  2023 libffi.a
   15 Jan 31 17:09 libffi.so -> libffi.so.8
   15 Jan 31 17:17 libffi.so.7 -> libffi.so.7.1.0
50664 Jan 31 17:02 libffi.so.7.1.0
   15 Jan 31 09:48 libffi.so.8 -> libffi.so.8.1.2
72144 May 10  2023 libffi.so.8.1.2
```
And then everything runs correctly. Take note that you can still link the default `libffi.so` to the highest version, i.e., `libffi.so -> libffi.so.8`, it will still work. This is because the runtime dynamic library loader will always try to load the closest-and-no-lower version of the library.

### Conda Info

```shell
active environment : None
       user config file : /home/xuancong/.condarc
 populated config files : /home/xuancong/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=23.11.0=0
                          __cuda=12.1=0
                          __glibc=2.36=0
                          __linux=6.1.55=0
                          __unix=0=0
       base environment : /dev/shm/miniconda3  (writable)
      conda av data dir : /dev/shm/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /dev/shm/miniconda3/pkgs
                          /home/xuancong/.conda/pkgs
       envs directories : /dev/shm/miniconda3/envs
                          /home/xuancong/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/6.1.55 debian/11.8 glibc/2.36 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
xuancong@mx:/dev/shm$ ./miniconda3/bin/conda config --show-sources
==> /home/xuancong/.condarc <==
channels:
  - intel
  - defaults
```

### Conda list

```shell
# packages in environment at /dev/shm/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
archspec                  0.2.1              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotli-python             1.0.9           py311h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.12.12           h06a4308_0    defaults
certifi                   2023.11.17      py311h06a4308_0    defaults
cffi                      1.16.0          py311h5eee18b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.11.0         py311h06a4308_0    defaults
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.12.0            pyhd3eb1b0_1    defaults
conda-package-handling    2.2.0           py311h06a4308_0    defaults
conda-package-streaming   0.9.0           py311h06a4308_0    defaults
cryptography              41.0.7          py311hdda0065_0    defaults
distro                    1.8.0           py311h06a4308_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.4.0                h251f7ec_1    defaults
libedit                   3.1.20230828         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.5.3                haf1ee3a_0    defaults
libmambapy                1.5.3           py311h2dafd23_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libsolv                   0.7.24               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
menuinst                  2.0.1           py311h06a4308_1    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.12               h7f8727e_0    defaults
packaging                 23.1            py311h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.3.1          py311h06a4308_0    defaults
platformdirs              3.10.0          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.5               h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                68.2.2          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
truststore                0.8.0           py311h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311h06a4308_0    defaults
wheel                     0.41.2          py311h06a4308_0    defaults
xz                        5.4.5                h5eee18b_0    defaults
yaml-cpp                  0.8.0                h6a678d5_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by travishathaway** [comment]
Hi @xuancong84,

This might be happening because you are trying to run the Python executable directly. Please make sure you have either activated the environment or are running the Python execute via `conda run`. There are some important things happen during the activation process. Omitting these may be the source of this error.

**Comment by xuancong84** [comment]
Thanks @travishathaway for your reply! I have tried activating conda environment, but it still fails as following:  
![image](https://github.com/conda/conda/assets/10172392/cc6d1288-d884-493b-b4bc-d8cf68bc7439)

FYI, activating conda environment simply prepends the conda's bin path to the PATH environment variable, so that it runs the `python` executable in `miniconda/bin` rather than `/usr/bin/python`. Actually, the `python` binary executable is designed such that it will always tries to find libraries in `../lib/` (relative to the `python` executable itself) first, e.g., if you run `/dev/shm/miniconda3/bin/python`, it will load `/dev/shm/miniconda3/lib/*`, and if you run `/usr/bin/python`, it will load `/usr/lib/*` first. Thus, unless your Python program will launch other programs in `miniconda3/bin`, running `miniconda3/bin/python` will suffice. And "activating conda environment" is for those novice people who knows little about Linux system and environment variables. In particular, prepending conda path in `PATH` variable in `.bashrc` will break certain system UI programs because they are dependent on libraries of version in `/usr/lib/*`, rather than your `miniconda/lib/*`. But this is what Anaconda/Miniconda installer is doing.

So, it seems that the problem I am presenting is not relevant to conda environment activation/setup.

**Comment by travishathaway** [comment]
@xuancong84,

Thanks for running that in the activated environment. I now think the problem lies with the package itself, so at this point, I would recommend filing an issue with the package maintainers. This GitHub project is saved specifically for problems that arise while using conda and the not packages it installs.

Also, I just wanted to let you know that environment activation is perhaps a bit more complicated than you think. Each package in conda can optionally define both "activate" and "deactivate" scripts that are able to run arbitrary code during activation and deactivation. This is mostly used to set additional environment variables that may affect the operation of libraries. More on that here:

- https://docs.conda.io/projects/conda/en/stable/dev-guide/deep-dives/activation.html#activation-deactivation-scripts

**Comment by xuancong84** [comment]
@travishathaway Thanks for explaining the activation/deactivation script to me. I am interested to know that.

Yup, I agree with you that it is a package maintenance issue. They should keep individual library versions rather than soft-linking all to only the latest version. Btw, do you have a team to do that? Since Anaconda/Miniconda is quite popular among open-source communities, I do feel that it is quite important for you to also maintain packages correctly.

For example, I also realize another package maintenance issue for conda: your arm64 Linux installer crashes on certain devices such as Raspberry Pi, it throws "illegal instruction error" during installation, so now many people are switching to `conda-forge` instead. Another example is that Ubuntu has become the most popular Linux OS although almost all of its packages come from Debian, because it does a much better job in package maintenance than Debian.

**Comment by travishathaway** [comment]
@xuancong84,

Anaconda maintains what we call the "defaults" or "main" channel. To manage and keep this channel up to date requires a full time team of engineers, so yes, we definitely have a team doing it 😄.

But, managing such a large amount of packages is quite a bit of work, so Anaconda supports the open source community that provides other channels such as conda-forge and bioconda. For example, the cost for running and maintaining anaconda.org, the place where conda-forge hosts its packages, is fully paid for by Anaconda.

The people who manage packages for conda-forge and bioconda are largely volunteers or are being paid by their employers to do this work. Without this support, the conda ecosystem would not be what it is today. With that being said, it is best to think of the conda ecosystem and the packages available there as not just the company Anaconda but as the thousands of volunteers and contributors who make it possible.

Regarding the Raspberry PI, not supporting this particular architecture was a conscious decision made by Anaconda, and there are no plans in the near future to add support for it. This is why we are glad that the conda-forge community has stepped in to make a conda installer that is compatible with it. We fully endorse using it.

I hope this helps clarify some of your concerns. We appreciate your questions.

**Comment by xuancong84** [comment]
@travishathaway Thanks to your diligent reply with detailed explanation! Honestly speaking, the removal of the support for Raspberry Pi (RPI) makes sense to me because Anaconda is mainly for data science analytics and given the relatively low computing power of RPI, few people use that for data science analytics. So, it totals makes sense that Anaconda officially do not and will not provide explicit support for RPI.

However, my point is that if someone in the open-source community has figured out the solution to a known problem (e.g., library version issue or installer crash on RPI) and you have verified that it is correct, even if Conda is not officially supporting RPI, should you adopt the solution and make it better in terms of compatibility on non-advertised non-officially-supported platforms? Some kind of effortless no-harm non-official improvement.
