### ISSUE TITLE
Conda clone does not handle symlinks consistently depending on where it resides

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#1357]
As part of the install of some packages the customer creates a symlink to a directory at the root of the current conda env.

When cloning this conda environment containing a symlink, conda resolves this symlink and then copies (or hard links) the files it finds into the cloned environment. On the other hand, if instead of creating a symlink at the root level of the conda env, they create a symlink in a subdirectory.  The clone operation just recreates the original symlink. 

```
/conda_env_path/{symlink} 
```

This copies the entire symlinked directory to the new clone environment.

```
/conda_env_path/subdir/{symlink}
```

Recreates the symlink in the new clone environment.

Why is this the case? The customers preference would be for symlinks to be recreated and not resolved/copied during cloning but we should at least be consistent on how it handles symlinks in the root as well as in a sub directory of that environment.

**Comment by asmeurer** [comment]
It isn't clear to me from the code why the two cases would be handled differently. It looks to me like in both cases the link wouldn't be copied correctly.

**Comment by kalefranz** [comment]
@JeremyEnns I'm going to close this dated issue.  If you feel like it should be re-opened, please do so.
