### ISSUE TITLE
I wonder if it is possible to recover revised codes by using conda revert

### ISSUE THREAD

**Issue by HelloWorldLTY** [conda/conda#13586]
### What is the idea?

Hi, I updated a package in conda by mistake, and I found that I lost information from one of my revised code base. I have one lib which contained revised information, that is:

I modified the content under:

lib/python3.9/site-packages/XXX

And I found that the revert option actually went back to its unconverd version. Could you please help me? Thanks.

**Comment by kenodegard** [comment]
No, `conda` is not designed to preserve any modifications you make to installed packages.
