### ISSUE TITLE
`DYLD_FALLBACK_LIBRARY_PATH` + Library not loaded: `@rpath/libz.1.dylib`

### ISSUE THREAD

**Issue by anirban-mu** [conda/conda#13592]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I think these two open issues: https://github.com/rstudio/rstudio/issues/13967 and https://github.com/numba/llvmlite/issues/320 fundamentally relate to https://github.com/conda/conda/issues/7113. Namely, when using the Python interpreter on Mac, due to SIP, `DYLD_FALLBACK_LIBRARY_PATH` is not set. In this case llvmlite/numba works as expected. However, when `DYLD_FALLBACK_LIBRARY_PATH` is set as happens when using Reticulate through R on terminal or the newer versions of RStudio then a bug manifests where the llvmlite dylib looks for `@rpath/libz.1.dylib`. AFAIK this is what people would get with this file (copy and pasting from one of the earlier bug reports)

```
jaten@Jasons-MacBook-Pro / $ file /usr/lib/libz.1.dylib
/usr/lib/libz.1.dylib: Mach-O universal binary with 2 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64]
/usr/lib/libz.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/lib/libz.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
jaten@Jasons-MacBook-Pro / $ 
```

` /usr/lib/libz.1.dylib` no longer exists so that suggests that when `DYLD_FALLBACK_LIBRARY_PATH` is set, some where in the stack, the logic corresponds to an older x86_64 install. 

This does not affect many people because of System Integrity Protection where, when enabled, `DYLD_FALLBACK_LIBRARY_PATH` cannot be set in many cases. However, in the embedded Python environment, Reticulate surfaces `DYLD_FALLBACK_LIBRARY_PATH` and that triggers the issue.

I am guessing this is old cruft. Unfortunately, I have no idea where it is buried. I can point to replications but none is super straightforward as one needs `DYLD_FALLBACK_LIBRARY_PATH` to be set for the issue to surface. 

An alternative is to always enforce the requirement that `DYLD_FALLBACK_LIBRARY_PATH` is unset but that is not going to always be the case because Mac's SIP can be disabled and `DYLD_FALLBACK_LIBRARY_PATH` can be set even without Reticulate and R. SIP is enabled by default but it does not have to be enabled in a system (Mac provides the option). Of course, in an embedded environment, `DYLD_FALLBACK_LIBRARY_PATH` can be used.

TBH, I am not a developer but rather an end user bit with this bug. I am only chasing it down because I understand the position of the developers of downstream developers where this is not a priority. All of that said because I should put a disclaimer that I am speculating on the source of the issue that I can document--the issue in llvmlite bindings.

**Comment by travishathaway** [comment]
@anirban-mu,

Can you please share with us the exact packages causing this issue and which channel you are installing it from? (e.g. `defaults` or `conda-forge`).

I think this is a problem that has to be solved at the package level and cannot be solved within conda itself. Each package can define it's own installation routine, and I have a feeling that this is what is causing the error. That means that you need to track down who exactly manages this package to have this error resolved. If you share where you are getting these packages from, I'll be more than happy to help you find that information.

**Comment by anirban-mu** [comment]
I see. I have already raised the issue downstream with the developers of numba/llvmlite, the package in question. I will work with them to resolve. Closing here.
