### ISSUE TITLE
env must be deactivated/activated after installing ipython notebook

### ISSUE THREAD

**Issue by anderspitman** [conda/conda#1361]
I've noticed that if I `conda install ipython-notebook` from within a conda environment, I have to deactivate then reactive the environment before it comes up as the latest Jupyter notebook.

Steps to reproduce:

1.

```
conda create -n test python=2
source activate test
ipython notebook
```

Launches old version of ipython notebook as expected.

2.
```
conda install ipython-notebook
ipython notebook
```

Still old version - not expected.

3.
```
source deactivate
source activate test
ipython notebook
```

Launches latest Jupyter notebook.

**Comment by asmeurer** [comment]
This is an artifact of the way Unix shells work. See https://github.com/conda/conda/issues/1258#issuecomment-91035641 for an explaination.  Basically, they cache the location of command names that you type, but `source activate` runs a command that clears this cache.

**Comment by anderspitman** [comment]
Makes sense, thanks. I understand that you can't automatically run a rehash, but would it be possible to detect this situation and issue a warning to the user telling them to run `source activate`?
