### ISSUE TITLE
environment activation fails on OS X

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#1362]
I'm running Anaconda 2.2 on OS X 10.10, and have created an environment to run Python 2.7. I have updated and upgraded both conda and anaconda. However, when I try to activate the environment, I get a failure associated with the `activate` script:

```
$ source activate py2
/Users/fonnescj/anaconda/bin/activate:36: parse error near `fi'
```

**Comment by asmeurer** [comment]
Maybe your activate script got corrupted. Try `conda install -f conda-env`.

**Comment by fonnesbeck** [comment]
That did not work; the error persists. I even tried blowing away my `~/anaconda` directory and starting from scratch, but no dice.

**Comment by asmeurer** [comment]
Ah there is probably an issue with a variable not being quoted in the script.

**Comment by asmeurer** [comment]
@tswicegood @malev can one of you go through activate and deactivate and fix all [shellcheck](https://github.com/koalaman/shellcheck) warnings? There are several, and I suspect `$f` not being quoted is the source of this error (there are a lot of other warnings that will require more testing than I have time to do).

**Comment by soapy1** [comment]
@fonnesbeck I believe this is not longer an issue in the newest version of conda. If the problem persists for you after `conda update conda` please reopen this issue
