### ISSUE TITLE
Use commit hashes for GH Action versions

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13657]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

> It would be better to use hashes for the 3rd party GHA Actions instead of version tags. Dependabot should be compatible with that (https://github.com/conda-forge/docker-images/pull/256).

See https://github.com/conda/conda/pull/13162#pullrequestreview-1917653355

> Dependabot usually recommends pinning the hash to avoid tag replacement attacks. Dependabot can recognize the hashes as version approach and update them as necessary too, so I'd recommend switching back to hashes in 3rd party (i.e. no `actions/*`) actions.

See https://github.com/conda/conda/pull/13162#discussion_r1507296704

### Why is this needed?

Secure ourselves against tag replacement attacks.

### What should happen?

- [ ] Modify dependabot config to update commit hashes
- [ ] Switch GH Actions to use commit hashes

**Comment by dbast** [comment]
this requires activating dependabot for the repo... and it will propose updates for all actions in and outside of test.yaml

**Comment by kenodegard** [comment]
well what do you know this has been completed, see #13792!
