### ISSUE TITLE
"Encountered an SSL error"

### ISSUE THREAD

**Issue by adina17** [conda/conda#13665]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have been running miniconda on Mac M1. Recently, I started getting the same error when trying to run any command (even creating a new environment, conda update -all or other):
CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/osx-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

I chedk the forum and tried various solutions with no success, now I am not able to run conda. any help appreciated

### Conda Info

```shell
active environment : base
    active env location : /Users/adina/miniconda3
            shell level : 1
       user config file : /Users/adina/.condarc
 populated config files : /Users/adina/.condarc
          conda version : 23.10.0
    conda-build version : not installed
         python version : 3.11.6.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=14.3.1=0
                          __unix=0=0
       base environment : /Users/adina/miniconda3  (writable)
      conda av data dir : /Users/adina/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/adina/miniconda3/pkgs
                          /Users/adina/.conda/pkgs
       envs directories : /Users/adina/miniconda3/envs
                          /Users/adina/.conda/envs
               platform : osx-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.6 Darwin/23.3.0 OSX/14.3.1
                UID:GID : 503:20
             netrc file : None
```

### Conda Config

```shell
(base) adina@AdinaMac ~ % conda config --show-sources
Error while loading conda entry point: conda-content-trust (dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): Library not loaded: @rpath/libssl.3.dylib
  Referenced from: <07FD4547-EB50-3FED-858D-E84A2E67EFC2> /Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so
  Reason: tried: '/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache))
Error while loading conda entry point: conda-libmamba-solver (dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libcrypto.3.dylib
  Referenced from: <82998893-D7F1-3A7E-8F6D-BFBE7A8D70A8> /Users/adina/miniconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))
==> /Users/adina/.condarc <==
solver: classic

==> envvars <==
subdir: osx-64
```

### Conda list

```shell
anyio                     4.1.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
archspec                  0.2.1              pyhd3eb1b0_0    defaults
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311h2725bcf_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.13.1             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0          py311hca03da5_0    defaults
brotli-python             1.0.9           py311h313beb8_7    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.1               h80987f9_0    defaults
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h80987f9_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
conda                     23.10.0         py311h267d04e_1    conda-forge
conda-content-trust       0.2.0           py311hca03da5_0    defaults
conda-libmamba-solver     23.11.1         py311hca03da5_0    defaults
conda-package-handling    2.2.0           py311hca03da5_0    defaults
conda-package-streaming   0.9.0           py311hca03da5_0    defaults
cryptography              41.0.3          py311hd4332d6_0    defaults
debugpy                   1.8.0           py311hdf8f085_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fmt                       10.1.1               h1995070_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.4             py311hca03da5_0    defaults
importlib-metadata        7.0.0              pyha770c72_0    conda-forge
importlib_metadata        7.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.26.0             pyh3cd1d5f_0    conda-forge
ipython                   8.18.1             pyh707e725_3    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.20.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.11.2          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.20.0             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.1              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.5.0           py311h6eed73b_0    conda-forge
jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.12.1             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.2             pyhd8ed1ab_0    conda-forge
krb5                      1.20.1               hf3e1bf2_1    defaults
libarchive                3.7.2                h82b9b87_0    conda-forge
libcurl                   8.4.0                h3e2b118_0    defaults
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.17                 he4db4b2_0    conda-forge
libmamba                  1.5.3                h0a6dc31_2    conda-forge
libmambapy                1.5.3           py311hab8398d_2    conda-forge
libnghttp2                1.57.0               h62f6fdd_0    defaults
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsolv                   0.7.24               h514c7bf_0    defaults
libsqlite                 3.44.0               h091b4b1_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.11.6               h0d0cfa8_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
lz4-c                     1.9.4                h313beb8_0    defaults
lzo                       2.10              h642e427_1000    conda-forge
mamba                     1.5.3           py311hb045da1_2    conda-forge
markupsafe                2.1.3           py311h2725bcf_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.12.0             pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h313beb8_0    defaults
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
notebook                  7.0.6              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
openssl                   3.2.0                hd75f5a5_1    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.1            py311hca03da5_0    defaults
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                hb066dcc_0    defaults
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.3            py311hca03da5_0    defaults
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py311hca03da5_1    defaults
prometheus_client         0.19.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.41             pyha770c72_0    conda-forge
psutil                    5.9.5           py311h2725bcf_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.0            py311hf110eff_0    conda-forge
pyobjc-framework-cocoa    10.0            py311hf110eff_1    conda-forge
pyopenssl                 23.2.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.6          h47c9636_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python.app                3               py311h80987f9_0    defaults
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h2725bcf_1    conda-forge
pyzmq                     25.1.2          py311h889d6d6_0    conda-forge
readline                  8.2                  h1a28f6b_0    defaults
referencing               0.31.1             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.31.0          py311hca03da5_0    defaults
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.13.2          py311h5e0f0e4_0    conda-forge
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.0.0          py311hca03da5_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlite                    3.41.2               h80987f9_0    defaults
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.18.0             pyh31c8845_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py311h2725bcf_1    conda-forge
tqdm                      4.65.0          py311hb6e6a13_0    defaults
traitlets                 5.14.0             pyhd8ed1ab_0    conda-forge
truststore                0.8.0           py311hca03da5_0    defaults
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h04d1e81_0    defaults
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.18         py311hca03da5_0    defaults
wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
yaml                      0.2.5                h0d85af4_2    conda-forge
yaml-cpp                  0.8.0                h313beb8_0    defaults
zeromq                    4.3.5                h93d8f39_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

### Additional Context

I am encountering this at the base when trying to create an environment or updating conda etc

**Comment by travishathaway** [comment]
Hi @adina17,

I would recommend trying the steps outlined in our "Troubleshooting" guide to try to fix this:

- https://docs.conda.io/projects/conda/en/stable/user-guide/troubleshooting.html#ssl-verification-errors

Additionally, we have seen these types of errors pop up in the past when users decide to mix both the `defaults` and `conda-forge` channels. In the future, I would not attempt to install `conda-forge` packages to your base environment. If you need conda-forge packages, install them into their own separate environments.

Please let us know if this works for you so we can make sure that this troubleshooting guide is actually useful.

**Comment by adina17** [comment]
Hi Travis
thanks for this. Unfortunately, nothing seems to work, I cannot get even
past the 2 solutions.
Basically it says it needs an ARM64 architecture (which is what I have),
output from uname -m command. Output from which bash command is

(base) ***@***.*** ~ % file `which bash`

/bin/bash: Mach-O universal binary with 2 architectures: [x86_64:Mach-O
64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]

/bin/bash (for architecture x86_64): Mach-O 64-bit executable x86_64

/bin/bash (for architecture arm64e): Mach-O 64-bit executable arm64e


I had the x86_64 on my Intel system (which was migrated to this M1 computer)

Not sure where to go from here

thanks

Adina

------


conda config --set ssl_verify truststore


this fails too...


Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is
an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libcrypto.3.dylib' (no such file),
'/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))

**Comment by travishathaway** [comment]
That's good information to have.

Is it is possible for you to run install commands after setting `ssl_verify=false`? (i.e. `conda config --set ssl_verify false`) If you could temporarily disable SSL verification you could potentially repair your installation by trying to re-install `python` with `conda install python`.

Be sure to re-enable SSL afterwards to test that this works with `conda config --set ssl_verify=true`.

Please let us know if this works.

**Comment by adina17** [comment]
Hi Travis
I had tried that, but I get a long error message. I am copying it below.
Again it says it needs arc64 architecture, but this is what I have.
I really don;t understand how things got broken after the new changes, as I
had used conda until Mid December, then I think the new settings with SSL
made everything crash. I struggled to create environments with x86_64
architecture as I really wouldn;t want to wipe everything and try a fresh
install.
thanks
Adina

Error while loading conda entry point: conda-content-trust
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so, 0x0002): Library not loaded: @rpath/libssl.3.dylib

  Referenced from: <07FD4547-EB50-3FED-858D-E84A2E67EFC2>
/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so

  Reason: tried:
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an
incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib'
(no such file, not in dyld cache))

Error while loading conda entry point: conda-libmamba-solver
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/
bindings.cpython-311-darwin.so, 0x0002): Library not loaded:
@rpath/libcrypto.3.dylib

  Referenced from: <82998893-D7F1-3A7E-8F6D-BFBE7A8D70A8>
/Users/adina/miniconda3/lib/libmamba.2.0.0.dylib

  Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is
an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libcrypto.3.dylib' (no such file),
'/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))

(base) ***@***.*** ~ % conda config --set ssl_verify false


Error while loading conda entry point: conda-content-trust
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so, 0x0002): Library not loaded: @rpath/libssl.3.dylib

  Referenced from: <07FD4547-EB50-3FED-858D-E84A2E67EFC2>
/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so

  Reason: tried:
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an
incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib'
(no such file, not in dyld cache))

Error while loading conda entry point: conda-libmamba-solver
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/
bindings.cpython-311-darwin.so, 0x0002): Library not loaded:
@rpath/libcrypto.3.dylib

  Referenced from: <82998893-D7F1-3A7E-8F6D-BFBE7A8D70A8>
/Users/adina/miniconda3/lib/libmamba.2.0.0.dylib

  Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is
an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libcrypto.3.dylib' (no such file),
'/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))

**Comment by adina17** [comment]
Hi Travis
had tried that too with no success. I really do not understand where the
issue comes from..
thanks
-------
(base) ***@***.*** ~ % conda config --set solver=classic
Error while loading conda entry point: conda-content-trust
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so, 0x0002): Library not loaded: @rpath/libssl.3.dylib

  Referenced from: <07FD4547-EB50-3FED-858D-E84A2E67EFC2>
/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so

  Reason: tried:
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an
incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib'
(no such file, not in dyld cache))

Error while loading conda entry point: conda-libmamba-solver
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/
bindings.cpython-311-darwin.so, 0x0002): Library not loaded:
@rpath/libcrypto.3.dylib

  Referenced from: <82998893-D7F1-3A7E-8F6D-BFBE7A8D70A8>
/Users/adina/miniconda3/lib/libmamba.2.0.0.dylib

  Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is
an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libcrypto.3.dylib' (no such file),
'/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))

usage: conda config [-h] [--json] [-v] [-q] [--system | --env | --file
FILE] [--show [SHOW ...] |

                    --show-sources | --validate | --describe [DESCRIBE ...]
| --write-default]

                    [--get [KEY ...] | --append KEY VALUE | --prepend KEY
VALUE | --set KEY VALUE |

                    --remove KEY VALUE | --remove-key KEY | --stdin]

conda config: error: argument --set: expected 2 argument

**Comment by travishathaway** [comment]
@adina17,

I apologize. The `conda config` command I shared is actually not correct. This is the correct way to run that command:

```
conda config --set solver classic
```

Maybe give that a shot and let me know what happens. I appreciate your patience.

**Comment by adina17** [comment]
Thanks Travis

no luck with this one either// another long set of error messages about
needing arm64..while yes it is (and I unclicked "open Using Rosetta" in the
terminal settings)
thanks for your patience as well!
Adina

Error while loading conda entry point: conda-content-trust
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so, 0x0002): Library not loaded: @rpath/libssl.3.dylib

  Referenced from: <07FD4547-EB50-3FED-858D-E84A2E67EFC2>
/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/_
rust.abi3.so

  Reason: tried:
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/cryptography/hazmat/bindings/../../../../../libssl.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libssl.3.dylib' (mach-o file, but is an
incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib'
(no such file, not in dyld cache))

Error while loading conda entry point: conda-libmamba-solver
(dlopen(/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/
bindings.cpython-311-darwin.so, 0x0002): Library not loaded:
@rpath/libcrypto.3.dylib

  Referenced from: <82998893-D7F1-3A7E-8F6D-BFBE7A8D70A8>
/Users/adina/miniconda3/lib/libmamba.2.0.0.dylib

  Reason: tried: '/Users/adina/miniconda3/lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')),
'/Users/adina/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libcrypto.3.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need
'arm64')), '/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o
file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/Users/adina/miniconda3/bin/../lib/libcrypto.3.dylib' (mach-o file, but is
an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/lib/libcrypto.3.dylib' (no such file),
'/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache))

**Comment by travishathaway** [comment]
Hi @adina17,

At this point, I would recommend installing conda again. You can preserve you installation as long as you install the new version to a different folder (e.g. `/Users/adina/minicoda3-new`).

You should still be able to interact with and use your old environments, but you may have to point conda at them using the full path (e.g. `conda activate /Users/adina/miniconda3/envs/your-env`).

**Comment by Liiiiaictx** [comment]
@adina17 你解决了吗，我也是创建虚拟环境出错，请问怎么解决
