### ISSUE TITLE
CondaKeyError: 'pkgs_dirs': key 'pkgs_dirs' is not in the config file

### ISSUE THREAD

**Issue by JingjingBai2021** [conda/conda#13677]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi, 
I am trying to remove the home directory out of the configuration file using  the following command:

```
conda config --remove envs_dirs "/home/.conda/envs"
```

I got the following error:

```
CondaKeyError: 'envs_dirs': key 'envs_dirs' is not in the config file
```

**Comment by kenodegard** [comment]
@JingjingBai2021 that means `envs_dirs` is not defined in your `~/.condarc`. Run `conda config --show-sources` to see what values have been customized for your conda installation (and what values can be removed).

Furthermore, `/home/.conda/envs` is a default environment location and cannot be overridden. You can add additional paths with a higher priority but that default will remain.

To prevent environments from being created in `/home/.conda/envs`, change the directory permissions to read only.
