### ISSUE TITLE
Authenticode Sign cli-32.exe and cli-64.exe prebuilt binaries

### ISSUE THREAD

**Issue by Callek** [conda/conda#13685]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Windows users when they `conda install` a package with entrypoints end up with an executable that is not codesigned. We should provide a codesigned copy of our stubs to make the executables produced as part of that process also signed.

### Why is this needed?

Users may be on a more locked down system requiring executable files, like this, be signed.  Having codesigned copies of these stubs helps unlock that potential for our users.

### What should happen?

The conda release process, and possibly CI, ensures these binaries are signed such that they may be used by windows users for launching python entrypoints on windows packages.

### Additional Context

Anaconda Inc, is willing to sign the existing binaries ahead of a more inclusive solution designed in the open for the Conda Community.

This would apply both to `conda`'s https://github.com/conda/conda/tree/main/conda/shell and `conda-build`'s [https://github.com/conda/conda-build/blob/main/conda_build/cli-{32,64}.exe](https://github.com/conda/conda-build/blob/main/conda_build/cli-%7B32,64%7D.exe) as sourced at https://github.com/conda/conda-build/tree/main/conda_build/launcher_sources

**Comment by jaimergp** [comment]
There are some launchers in conda/menuinst too which might need the same treatment.

**Comment by Callek** [comment]
> There are some launchers in conda/menuinst too which might need the same treatment.

Those are not pre-built though correct?  And they can be signed as part of the build process itself?

**Comment by jaimergp** [comment]
Yes, they are, check menuinst/data.

**Comment by Callek** [comment]
> Yes, they are, check menuinst/data.

Ahhh - https://github.com/conda/menuinst/tree/main/menuinst/data - those are osx-only binaries (from what I can tell) and the recipe for menuinst seems to be compiling the windows ones. (Authenticode signing is windows only)

References:
* https://github.com/conda/menuinst/blob/db528854422d765d9423eb7c705e06b0c7ade905/setup.py#L11
* https://github.com/conda-forge/menuinst-feedstock/blob/100bc037d6759541cb8e55194037ae1239f0c90b/recipe/meta.yaml#L35
* https://github.com/AnacondaRecipes/menuinst-feedstock/blob/692c881bd53914f1283b68b310ff62cf17b6d814/recipe/meta.yaml#L36

**Comment by jezdez** [comment]
Resolved by #13721.

**Comment by jezdez** [comment]
FYI https://github.com/conda/conda-build/pull/5252 has been merged as well.
