### ISSUE TITLE
Add `reporters` as a new configuration option

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#13709]
### What's the idea?

Add a new configuration option, `reporters`, to conda.

### Why is this needed?

We want to be able to support multiple backends for writing to various output streams (e.g. files and stdout) and adding this new configuration option will make this process easier. Our primary use case for this is to add additional backends such as [rich](https://rich.readthedocs.io) in the future.

### What should be done?
- [ ] Add new `reporters` configuration option. This will be a list of mappings (see examples below). This will only be configurable via configuration files.
- [ ] Currently available options for verbosity (e.g. `--verbose`)  and output type (e.g. `--json`) will implicitly set values within `reporters` to make the CLI interface more user friendly (see examples below).
- [ ] ~Make sure this is documented~ _This is not being documented right now because setting this option has no effect, and we do not want to confuse users with such options at this point._

#### Examples

This is the default setting. It prints the regular command output to standard out:

```yaml
reporters:
  - backend: stdlib
    output: stdout
```

Setting JSON as output for standard out:

```yaml
reporters:
  - backend: json
    output: stdout
```

Writing JSON to a file and printing the normal output to stdout:

```yaml
reporters:
  - backend: json
    output: file
    filename: file.json
  - backend: stdlib
    output: stdout
```

**Comment by jaimergp** [comment]
This assumes users can only have one output set a time. That's an ok assumption, but I want to discuss whether simultaneous outputs would make sense (e.g. regular output to stdout, json to file). In that case, should this allow for a more complex type like a list of dicts too? That can be done in further PRs, but again, just making sure we are not making an assumption implicitly.

**Comment by jezdez** [comment]
> This assumes users can only have one output set a time. That's an ok assumption, but I want to discuss whether simultaneous outputs would make sense (e.g. regular output to stdout, json to file). In that case, should this allow for a more complex type like a list of dicts too? That can be done in further PRs, but again, just making sure we are not making an assumption implicitly.

I concur, I wouldn't mind if we'd make --output basically a list and design the interface so that it can behave as a stream of outputs, with optional filters

**Comment by chenghlee** [comment]
I like the idea, but I'm not sure that calling this option simply `output` is the best choice, especially as an "top-level" key-value pair in `condarc`. IMO, just seeing  `output: json` or `output: ["json", "text"]` doesn't make it at least somewhat obvious _which_ output is being referenced.

Also, the `--output` argument already exists for `conda-build`:
```
$ $  conda build --help | grep -A4 -- '--output' 
usage: conda build [-h] [-V] [-n] [--output] [--python PYTHON] [--perl PERL]
                   [--numpy NUMPY] [--R R_BASE] [--lua LUA]
                   [--bootstrap BOOTSTRAP]
                   [--append-file APPEND_SECTIONS_FILE]
                   [--clobber-file CLOBBER_SECTIONS_FILE]
--
                   [--output-folder OUTPUT_FOLDER]
                   [--no-prefix-length-fallback] [--prefix-length-fallback]
                   [--prefix-length _PREFIX_LENGTH] [--no-locking]
                   [--no-remove-work-dir] [--error-overlinking]
                   [--no-error-overlinking] [--error-overdepending]
--
  --output              Output the conda package filename which would have
                        been created
  --python PYTHON       Set the Python version used by conda build.
  --perl PERL           Set the Perl version used by conda build.
  --numpy NUMPY         Set the NumPy version used by conda build.
--
  --output-folder OUTPUT_FOLDER
                        folder to dump output package to. Package are moved
                        here if build or test succeeds. Destination folder
                        must exist prior to using this.
  --no-prefix-length-fallback
```

**Comment by jaimergp** [comment]
Agreed, but I can't think of super obvious alternatives. Maybe some options to start the conversation:

```
--display
--print
--show
--result
--view
--format
--ui
--tui
--interface
```

**Comment by travishathaway** [comment]
I took a look around at other package managers and saw:

- `pip` uses a `--no-color` option
- `cargo` and `pixi` use a `--color` option that can be set to `always`, `never` and `auto`

I don't think that's going to work for what we to do with conda, but I figured I'd at least mention that here.

@jaimergp, I had initially thought `display` would be a good option, and I think @chenghlee's feedback is valid and warrants us changing the option. So, `display` seems like the best option to go with.

I'm also trying to think through the implications of having the `display` option as a list (e.g. `--display=json,stdlib`). In this invocation, I would expect both JSON and stdlib output to mixed:

```
conda create --display=json,stdlib
# ... normal output of command here
{"key": "With JSON at the end of everything"}
```

That doesn't really do much for our users, imo. So, it seems that on top of having that set as a list, you would also need to more settings that would actually specify where you wanted them to go:

```
conda create --display=json,stdlib --to-file=json --to-stdout=stdlib --to-file-name=test.json
```

As you can see, that blows up in complexity pretty quick. Is that actually useful enough to warrant that type of complexity? I guess that would actually be cool to be able to do. This would enable us to save both stdlib output to a file and json to a file with something like this:

```
conda create --display=json,stdlib --to-file=json --to-stdout=stdlib --to-file-name=test.json > stdlib.txt
```

But that looks kind of confusing as a command invocation 😵.

I'm thinking aloud here, and I'm not entirely sold on the idea of setting `display` as a list. I could be convinced otherwise though with a more compelling use-case.

**Comment by travishathaway** [comment]
Also, this:

- https://clig.dev/#output

(not necessarily entirely related to this conversation but definitely good tidbits there)

I feel like the idea of multiple output streams would break away from the standard UNIX model of providing a single stdout stream. What are other's thoughts on this?

**Comment by jaimergp** [comment]
I don't think we need the CLI flags to map the exact underlying configuration model. We could have more UI friendly flags:

`--json` would mean

```
display:
  - json: <stdout>
```

`--json=some_file.json` would mean

```
display:
  - json: some_file.json
  - stdlib
```

and `-vv --json=some_file.json` could be

```
display:
  - json: some_file.json
  - stdlib:
     verbosity: 2
```

and so on. It's more about enabling several streams in the configuration model than exposing all the possibilities to the end user.

**Comment by travishathaway** [comment]
@jaimergp,

Yes, that makes more sense. Thanks for providing those examples. At this point I have been sufficiently persuaded to pursue this approach 😄.

**Comment by jaimergp** [comment]
Yea, that's a good compromise and even a good choice, in case someone wants different verbosities in different streams or something.

**Comment by travishathaway** [comment]
I like reporters and will go that.

Also, given that the "reporters" will not be expected to be set via CLI options or environment variables, I think also the added verbosity of what you described above will work. I do want to repeat that we cannot mix data types in our configuration definitions, so:

```yaml
reporters:
  - backend: stdlib
    with:
      output: stdlib
      verbosity: 2
```

Will need to be:

```yaml
reporters:
  - backend: stdlib
    output: stdout
    verbosity: 2
```

I'm going to go ahead work on drafting a pull request with this approach. Will report back once it's done.

**Comment by jaimergp** [comment]
We can mix strings and integers but not strings and dicts? 🤔

**Comment by travishathaway** [comment]
> We can mix strings and integers but not strings and dicts? 🤔

@jaimergp I know. Not fun. It's because strings and integers fall under what the configuration system calls a `PrimitiveParameter`. Mappings are not in this club 😦.
