### ISSUE TITLE
Requesting documentation for what "latest" miniconda install corresponds to during different date ranges

### ISSUE THREAD

**Issue by john-b-yang** [conda/conda#13701]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello, I would like to figure out what the "latest" miniconda installation corresponds to in terms of the specific version of the installer link as detailed in the [archive](https://repo.anaconda.com/miniconda/).

I had a project that was working with the `latest` version of `miniconda` around last September.

I recently have attempted to reproduce this project, but with the latest `miniconda`, the resolver is no longer correctly setting up my environment. I don't know how to identify which miniconda version I was last using.

I was very much hoping to find out what the `latest` installation points to at different points in time.

Could you point me to this documentation if it exists? If not, would it be possible to know what `latest` pointed to during the month of September 2023?

**Comment by travishathaway** [comment]
Hi @john-b-yang,

I think this page should give you the information you are looking for:

- https://repo.anaconda.com/miniconda/

Notice the "Last modified" column. That will tell you when that version first appeared. This is currently linked to in the [Miniconda Documentation](https://docs.anaconda.com/free/miniconda/).

Please let us know if this provides enough information to solve your problem.

**Comment by john-b-yang** [comment]
@travishathaway Gotcha, thanks so much for the direction!

I just want to clarify whether I'm interpreting the index properly. I see this entry:
```
Miniconda3-latest-MacOSX-x86_64.sh | 103.9M | 2024-02-27 12:46:51
-- | -- | --
[Miniconda3-latest-MacOSX-x86_64.sh](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh)	103.9M	2024-02-27 12:46:51
```

I also see a bunch of `Miniconda3-py(.*)_24.1.2-(.*)` entries with a last modified date of `2024-02-27 12:46:51` (same as `latest`'s last modified date).

Does this mean that if I use the latest endpoint, it points at the `Miniconda3-py39_24.1.2-*` entries?

If this logic is correct, does that mean if I was using the `latest` endpoint last year September 2023, I was actually using the `Miniconda3-py3*_23.5.2-0-*` endpoint (since it was the most recently modified at that time, with the modification date of `2023-07-13 13:55:52`)?

I'm also curious whether `latest` defaults to a specific version of Python. Which one would it have been out of `py[11|10|9|8]`?

Thanks so much again for the response, it's already quite helpful! I think answers to these questions will help me fully resolve my issues.

**Comment by travishathaway** [comment]
@john-b-yang,

I believe you are correct in your first assumption.

Regarding Python versions, I think latest points to the latest possible release of Python available (e.g. Python 3.12 at this time).

**Comment by john-b-yang** [comment]
Gotcha, thanks a bunch! Closing.
