### ISSUE TITLE
Unable to activate environment in OS X with Zsh

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [conda/conda#1371]
```
$ source activate py34
discarding /Users/avazquez/anaconda3/envs/py34/bin from PATH
prepending /Users/avazquez/anaconda3/envs/py34/bin to PATH
/Users/avazquez/anaconda3/envs/py34/bin/activate:export:70: not valid in this context: /Users/avazquez/anaconda3/envs/py34
```

I just tried `$ conda install -f conda-env`, and run into the same problem. [Here](https://gist.github.com/amelio-vazquez-reina/6017da9cfb31cb16f2bc) is my pip freeze in case it helps

This is all in Zsh with oh-my-zsh. I do not have this problem with Bash.

**Comment by amelio-vazquez-reina** [comment]
Not sure where to make the fix, but [this](http://unix.stackexchange.com/questions/208607/zsh-export-not-valid-in-this-context/208609#208609) did it for me.

**Comment by timsnyder** [comment]
We ran into this issue today at work and patched the activate script as Amelio described in his stackexchange post.  Amelio, are you going to submit a pull-request for this change?  I can if you aren't planning to.

**Comment by amelio-vazquez-reina** [comment]
Thanks @timsnyder Yes, I'd love. I was unable to find the `activate` **shell** script in the repo (the one to modify). All I found is [activate.py](https://github.com/conda/conda/blob/master/conda/cli/activate.py) but that is different. Is `activate` [shell script] generated programmatically?

**Comment by asmeurer** [comment]
Activate is at https://github.com/conda/conda-env.

**Comment by jackjchen** [comment]
@timsnyder The zsh version we were using is zsh 4.3.11 (x86_64-unknown-linux-gnu) on RHEL6.5

**Comment by soapy1** [comment]
Can't reproduce this issue on the newest version of conda and zsh
