### ISSUE TITLE
Upgrade python offline

### ISSUE THREAD

**Issue by sichengyan** [conda/conda#13734]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I would like to upgrade my offline machine python version to the newest. since it's an offline machine, I copied the entire packages of python, including the related dependencies(attached the environment list). Also I have created a local channel that is a directory on my desktop with win64/noarch everything, the packages are also in it. whenever i try to install it from the directory/channel, its saying cannot found packages. and if i were to create a new env based on it, it will create the python version that is same as my base. I dont have conda pack nor conda-build on my offline machine and want to know how to update the python version
[Conda_packages_list.txt](https://github.com/conda/conda/files/14748602/Conda_packages_list.txt)

**Comment by travishathaway** [comment]
@sichengyan,

Thanks for filing this issue. I think that we could improve our documentation by adding a better guide for how to interact with offline repositories.

Your use case provides a good starting point for researching this.

**Comment by sichengyan** [comment]
@travishathaway 
I agree with you 100%, but I soon realized maybe I should also put it as a support request since till now I still have not find a good way to solve it.

**Comment by travishathaway** [comment]
@sichengyan, I will change this to a support request then.

We still need to research the right way to do this. I encourage you to keep reaching out to others in the community and report your findings back here.

**Comment by sichengyan** [comment]
Also on top of that, I have encountered another problem: Collecting package metadata (repodata.json): / WARNING conda.conda_libmamba_solver.index:_json_path_to_repo_info(266): No repodata found for channel defaults. Solve will fail.
I get this message on my offline machine, when I have download the packages using --download-only and copied to the other machine, then using install --offline
