### ISSUE TITLE
Plugin system: improve error handling

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13741]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Add a new configuration option for subcommand plugins:

```diff
  @conda.plugins.hookimpl
  def conda_subcommands():
      yield conda.plugins.CondaSubcommand(
          name="build",
          summary="Build conda packages from a conda recipe.",
          action=build,
+         base_exception_class=CondaBuildError,
      )
```

This is then exposed by the plugin manager to conda's exception handling logic to consider them "expected exceptions" instead of unexpected. The kwarg name can also be `expected_exception_type` and so on.

### Why is this needed?

Subcommands plugins will run their code under conda's exception handler. If the exceptions raised are _not_ covered by this logic:

https://github.com/conda/conda/blob/bfc82e177904c8e18ebcb5deed25de69eb558369/conda/exception_handler.py#L49-L75

Then conda will create an error report with added verbosity.

This is creating UX issues in conda-build, where it is normal to raise CalledProcessError for a failed build script. See https://github.com/conda/conda-build/issues/5263.

### What should happen?

If a subcommand plugin registers an expected exception type, then conda will not create an error report. The full traceback will be available in `--debug` and `-vvv` modes, as usual.

Some documentation on how to use this feature should be added too.

### Additional Context

Comes from https://github.com/conda/conda-build/issues/5263. For this to benefit conda-build, conda-build will also need to change the types of their expected exceptions.

**Comment by jaimergp** [comment]
An alternative proposed by @jezdez would be to instead have a general "expected_exception_type" plugin hook so any plugin can register their known exception types.

I guess we shouldn't allow generic builtins there, but that can be discussed in the eventual PR.

**Comment by jaimergp** [comment]
Another alternative that is floating is that all plugins that wish to have special treatment by the exception handler subclass `conda.CondaError`. Maybe we just need to document this "requirement" / API.

**Comment by jezdez** [comment]
> Another alternative that is floating is that all plugins that wish to have special treatment by the exception handler subclass `conda.CondaError`. Maybe we just need to document this "requirement" / API.

That seems like the best course of action TBH.

**Comment by jaimergp** [comment]
Let's document that then. I'll open a PR.
