### ISSUE TITLE
condarc proxy server and passwords

### ISSUE THREAD

**Issue by Joehurley** [conda/conda#1375]
Everything is working wonderfully with our .condarc proxy server settings...outside of the fact that (i) our login and password is saved in it for wandering eyes to see and (ii) we have to keep changing our password in this file as our company asks (actually we have a number of other config files we have to update with changing passwords).

We developed an encryption/decryption module via python code where it requires one password entered, and then the config files call a modules to obtain the specified login/password. My question is if anyone has had experience calling a function from .condarc (i.e. login and password) and using the result to set the proxy servers?

I can generate the string in a bash script easy enough (pseudo code), but the YAML syntax is not working for me:
DCRYPT_PWD=$(python C:/some_path/get_password.py)
USR_ID=$(python C:/some_path/get_id.py)
PXY_STR=$'http://'$USR_ID':'$DCRPT_PWD'@[server]:[port]

Any help/direction would be welcomed. Thanks.

**Comment by asmeurer** [comment]
Depending on what OS you use, you should be able to store your proxy information in the system settings (which will be encrypted), and requests should read them. 

If you want to set things dynamically, you might be better off setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. They will still be readable in clear text in the shell and any program started in the shell, however.

**Comment by Joehurley** [comment]
Thanks. Not sure if this was the right forum, but I appreciate your
response. I will see if I can make this work.
