### ISSUE TITLE
conda update --all needs more info when downgrading a package

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#1378]
When you run conda update --all sometimes a package dependency will be out of date or point to a specific version, this causes a downgrade but the end user has no way to know which package is causing this.  We should display more information when a downgrade happens and display which package is requesting the the older version in its dependencies.  This would help isolate where the problem is and which package needs to have its dependencies updated.

**Comment by asmeurer** [comment]
I'm trying to think of what the best way to do this is. Probably a good start would be to add a way to do a reverse dependency search.
