### ISSUE TITLE
Refine JLAP benchmark tests

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13800]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The tests we use to run the benchmark testing via codspeed.io has been acting odd in the JLAP related tests that I naively marked for benchmark testing. I think we might need to look into refining the used tests for that feature, maybe just the core fetching?

### Conda Info

```shell
-
```

### Conda Config

```shell
-
```

### Conda list

```shell
-
```

**Comment by dholth** [comment]
We need to time how long it takes to read existing repodata, apply patches and write out the modified repodata.

**Comment by dholth** [comment]
Closing since sharded repodata is becoming a thing.
