### ISSUE TITLE
Conda update Conda - "Error: Unable to remove files for package: conda"

### ISSUE THREAD

**Issue by ddofer** [conda/conda#1385]
I'm trying to update some packages (e.g. pandas), and keep getting the following error when trying to update them via Conda, and when trying to update Conda itself:

C:\Users\User>conda update scikit-learn numpy pandas
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment E:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.2.2            |           py34_0          61 KB
    pyyaml-3.11                |           py34_1         117 KB
    setuptools-17.1.1          |           py34_0         651 KB
    conda-3.14.0               |           py34_0         216 KB
    pandas-0.16.2              |       np19py34_0         4.7 MB
    ------------------------------------------------------------
                                           Total:         5.7 MB

The following packages will be UPDATED:

    conda:           3.11.0-py34_0     --> 3.14.0-py34_0
    conda-env:       2.1.4-py34_0      --> 2.2.2-py34_0
    nose:            1.3.6-py34_0      --> 1.3.7-py34_0
    pandas:          0.16.0-np19py34_1 --> 0.16.2-np19py34_0
    pip:             6.1.1-py34_0      --> 7.0.3-py34_0
    python-dateutil: 2.4.1-py34_0      --> 2.4.2-py34_0
    pytz:            2015.2-py34_0     --> 2015.4-py34_0
    pyyaml:          3.11-py34_0       --> 3.11-py34_1
    requests:        2.6.2-py34_0      --> 2.7.0-py34_0
    setuptools:      15.1-py34_0       --> 17.1.1-py34_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.2. 100% |###############################| Time: 0:00:00 103.05 kB
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 153.37 kB
setuptools-17. 100% |###############################| Time: 0:00:01 569.46 kB
conda-3.14.0-p 100% |###############################| Time: 0:00:00 295.24 kB
pandas-0.16.2- 100% |###############################| Time: 0:00:05 841.78 kB
Extracting packages ...
[      COMPLETE      ]|##################################################| 10
Error: Unable to remove files for package: conda

Please close all processes running code from conda and try again.

C:\Users\User>conda update conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment E:\Anaconda3:

The following packages will be UPDATED:

    conda:      3.11.0-py34_0 --> 3.14.0-py34_0
    conda-env:  2.1.4-py34_0  --> 2.2.2-py34_0
    pip:        6.1.1-py34_0  --> 7.0.3-py34_0
    pyyaml:     3.11-py34_0   --> 3.11-py34_1
    requests:   2.6.2-py34_0  --> 2.7.0-py34_0
    setuptools: 15.1-py34_0   --> 17.1.1-py34_0

Proceed ([y]/n)? y

*Error: Unable to remove files for package: conda*

Please close all processes running code from conda and try again.

C:\Users\User>conda install conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment E:\Anaconda3:

The following packages will be UPDATED:

    conda:      3.11.0-py34_0 --> 3.14.0-py34_0
    conda-env:  2.1.4-py34_0  --> 2.2.2-py34_0
    pip:        6.1.1-py34_0  --> 7.0.3-py34_0
    pyyaml:     3.11-py34_0   --> 3.11-py34_1
    requests:   2.6.2-py34_0  --> 2.7.0-py34_0
    setuptools: 15.1-py34_0   --> 17.1.1-py34_0

Proceed ([y]/n)? y

*Error: Unable to remove files for package: conda*

Please close all processes running code from conda and try again.

Windows 7. Python 3.4 . Anaconda 3.

**Comment by david-gang** [comment]
I have the same problem

**Comment by david-gang** [comment]
Inspired by http://stackoverflow.com/questions/29949087/python-anaconda-conda-issue-updating-anaconda-package-impossible-because-proces

I tried to write 
> conda update -f conda 

and it worked.

**Comment by ddofer** [comment]
That fixed it!
Thanks!

**Comment by asmeurer** [comment]
Yes, the fix for this is `conda update -f conda`.

**Comment by wildlyclassyprince** [comment]
Wow!
It worked. 
Thanks.

**Comment by ArtemSokoliuk** [comment]
Cool! That worked!

**Comment by vickyting0910** [comment]
It works. Thanks!

**Comment by eli-b** [comment]
Works for me too.

**Comment by binary10** [comment]
Worked for me.

**Comment by dwgoon** [comment]
It worked for me too.
