### ISSUE TITLE
conda connection fail

### ISSUE THREAD

**Issue by fly2mun** [conda/conda#13866]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

$ conda update -n base conda
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/linux-64'

**Comment by travishathaway** [comment]
@fly2mun,

Is this still an issue? If so, can you please re-run the command with `-v` flags so we can get more debugging output?

For example:

```
conda update -n base conda -v -v -v
```

**Comment by fly2mun** [comment]
@travishathaway 

I re-try your guide but not good.
please guide me.

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f99d46146e0>: Failed to resolve 'conda.anaconda.org' ([Errno -2] Name or service not known)")': /conda-forge/noarch/repodata.json.zst

failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/linux-64'

**Comment by travishathaway** [comment]
@fly2mun,

Can you please try running the following command and share the output with us?

```
curl -v https://conda.anaconda.org/conda-forge/linux-64/repodata.json > /dev/null
```

I'm trying to figure out where this error is coming from, and if this `curl` command fails to retrieve this file, I can say that the error probably has something to do with your network. In that case, there is no further advice that we could offer and you will have to speak with your network administrators.
