### ISSUE TITLE
Can not change the PATH in deactivate.d/env_vars.sh script

### ISSUE THREAD

**Issue by toihr** [conda/conda#13879]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I need to have a certain path added to my PATH environmental variable only whilst in a specific conda environment. I have added it as follows:
```sh
#!/bin/bash

export PATH=$PATH:/home/tihro/.miniforge3/envs/isis/bin
```
this adds the path to the variable without any problems. Now as the path is not important for other tasks, as it requires a set of other set environmental variables. I want to remove this on deactivation: Which i try to do as follows:
```sh
#!/bin/bash

tempPath=$(echo "$PATH" | tr ":" "\n" | grep -Fv "/home/tihro/.miniforge3/envs/isis/bin" | paste>

export test="$tempPath"
echo "doing something" #Check if something is actually done
export PATH="$tempPath"
```
When one now attempts to `echo $PATH` I will receive PATH still including the path i wanted to remove.
If i do `echo $test` I will obtain the collection of paths with the path removed.

I think this might be a bug with conda as it seems to work when executed as a normal bash file.

### Conda Info

```shell
active environment : base
    active env location : /home/tihro/.miniforge3
            shell level : 3
       user config file : /home/tihro/.condarc
 populated config files : /home/tihro/.miniforge3/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.1.2=0
                          __cuda=12.4=0
                          __glibc=2.35=0
                          __linux=5.15.153.1=0
                          __unix=0=0
       base environment : /home/tihro/.miniforge3  (writable)
      conda av data dir : /home/tihro/.miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/tihro/.miniforge3/pkgs
                          /home/tihro/.conda/pkgs
       envs directories : /home/tihro/.miniforge3/envs
                          /home/tihro/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.10.14 Linux/5.15.153.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.7
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/tihro/.miniforge3/.condarc <==
channels:
  - conda-forge
```

**Comment by toihr** [comment]
Ok some additional information i just figured out, this seems to be a problem using zsh, if one does this in the bash this seems to work. 

Addditionaly after some tinkering I did find that there is a problem with the env variable setting when one just calls `conda deactivate` this gives an error as follows:
```
(eval):unset:8: /home/tihro/Dropbox/masters_tom_ihro/Data/ISIS/: invalid parameter name
```

This error does not pop up when one does `conda activate` to return to base.

**Comment by travishathaway** [comment]
Hi @toihr,

I played around wit this a little myself and came up with the following...

All the paths you see below are relative to the conda installation directory.

#### `envs/test-project/etc/conda/activate.d/env_vars.sh`

Here's what my activate script looks like. It's inside an environment called "test-project":

```bash
CUSTOM_PATH=$HOME/apps/bin
export PATH="$PATH:$CUSTOM_PATH"
```

#### `envs/test-project/etc/conda/deactivate.d/env_vars.sh`

```bash
CUSTOM_PATH="$HOME/apps/bin"
export PATH=$(echo $PATH | sed "s#:$CUSTOM_PATH##g")
```

This works for me on `zsh`.  Let me know if this works for you.

Just FYI, this isn't an issue with conda. It's an error that is being raised during the shell scripts that were written.
