### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.api_export' problem when runnning the code with from keras.api_export import keras_export

### ISSUE THREAD

**Issue by carbondioxideox** [conda/conda#13887]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

running the code with pycharm configure the conda env but when import keras appears the api_export missing and the file folder cannot find the api_export.

tensorflow ver 2.0
keras ver  2.3.1

**Comment by carbondioxideox** [comment]
![image](https://github.com/conda/conda/assets/132559203/1d17b9e1-bbc6-4a05-b370-421ccc6d9163)

**Comment by travishathaway** [comment]
Hi @carbondioxideox,

This is not the place to receive support for PyCharm. Please inquire with support for PyCharm instead.

I will now be closing this as https://github.com/conda/conda/labels/off-topic.
