### ISSUE TITLE
Add --channel parameter to conda info command

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#1390]
Add the --channel parameter to the conda info command.
It needs to support all channel types:
- conda repo
- anaconda.org 
- local file:// channels
- enterprise anaconda server channels.

**Comment by kalefranz** [comment]
As of conda 4.4, use `conda search` with the `--info` flag.  You can add a `--channel` parameter here, or use channel in the match spec query, e.g.

    conda search conda-forge::numpy --info
