### ISSUE TITLE
Can't uninstall miniconda (after failed install): "Failed to run pre_uninstall"

### ISSUE THREAD

**Issue by morrisseyj** [conda/conda#13905]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

On Windows 11. I am trying to uninstall miniconda. I run the uninstaller but get the message: "Failed to run pre_uninstall". Note this was after a failed install when I got a similar message during the installer. Searching online i saw that you should just ignore this message, during the install. I did that but the install failed - I could not access conda from the cmd line. Now i can' uninstall. 

If, during the uninstall, I ignore the "Failed to run pre_uninstall" prompt, I get another error: "Failed to run rmpath". If i ignore that i get another one: "Failed to run rmreg". If i ignore that, the uninstaller completes. I finish and exit, however miniconda remains in my programs - even though its not working. 

I can't run conda info/conda config as conda did not install. 

How can i clean everything up to try and get things installed correctly?

**Comment by pseudoyim** [comment]
Hi @morrisseyj - could you please open an issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/new?assignees=&labels=type-bug&projects=&template=bug_report.yml) instead (and provide details on exactly which installer file you're using)? Miniconda installers are actually an Anaconda product, while this repo is for the codebase of `conda`. Thank you!

**Comment by morrisseyj** [comment]
@pseudoyim Apologies for the confusion. Done here: https://github.com/ContinuumIO/anaconda-issues/issues/13381
