### ISSUE TITLE
noarch only repositories do not work as expected

### ISSUE THREAD

**Issue by meawoppl** [conda/conda#1391]
A http based conda repository with only:

```
/channel-name
   /noarch
      repodata.json
      [packages]
```

Will not work for _any_ platform, as the sub-folder for a given os-bits (win-64/osx-64 etc) [must exist as a requirement](https://github.com/conda/conda/blob/972ad5d5f6d4c987d683aa6bedfbed3ba7753c5c/conda/fetch.py#L107).  The workaround we use currently is to make empty folders for the supported platforms with empty `repodata.json` and `.index.json`, but it feels hacky:

```
/channel-name
   /noarch
      repodata.json
      packages ...
   /win-64
      repodata.json
      [no packages]
```

In the related fetch code [here](https://github.com/conda/conda/blob/972ad5d5f6d4c987d683aa6bedfbed3ba7753c5c/conda/fetch.py#L124) if the "noarch" folder missing it is ignored silently, can we do a similar thing for platform-bits?  I am happy to file a PR on this if that is an acceptable solution.  It add's the capacity for silent failures of repositories, which does not feel good.  Perhaps provide a list of failed repo-fetches at the end?  From this angle, I can see some clear reasons that noarch needs to be treated specially.  

Similarly I also think it seems sane to treat the noarch and platform folders similarly, as the ideal behavior is basically merging the noarch and platform package list at a later step.

See also:
https://github.com/conda/conda-build/issues/462

**Comment by meawoppl** [comment]
Another potential solution is to make repodata.json exist above the OS folder level.  This is probably a bit more involved and would need updates in other parts, but seems cleaner IMHO.  This would almost certainty make fetching repo-data faster as a side effect.

**Comment by frol** [comment]
Bumped into this issue also :(

**Comment by frol** [comment]
@ilanschnell It seems that you have implemented the noarch feature. Could it be finished to a usable state?

**Comment by frol** [comment]
@asmeurer @ilanschnell Please, just say how we should deal with it and I or @meawoppl will send a pull request.

**Comment by meawoppl** [comment]
I started figuring out how noarch packages depart from their counterparts.  
This PR was the result of my starting to untangle this: https://github.com/conda/conda-build/pull/477

**Comment by kalefranz** [comment]
As of conda 4.3 a noarch-only repository should work just fine.  Please file a new issue if you encounter further problems.
