### ISSUE TITLE
conda environment breaks after initial usage - missing files in env_dir/lib/python3.X - due to changing .condarc for storage mgmt?

### ISSUE THREAD

**Issue by finchnSNPs** [conda/conda#13923]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm a facilitator for a shared HPC, we provide help and documentation for users to set up Miniconda3 [see our docs for reference](https://hyak.uw.edu/docs/tools/python#miniconda3). The default configuration for miniconda3 is in the user's $HOME directory where we have a 10G storage limit. Users run into "Disk quota exceeded" often when using miniconda3 because of package storage and the package cache. We encourage the use of environments for each project rather than a large environment for all projects, as well as using `--prefix` or `-p` and a path outside of the home directory where storage isn't limited for their environments. However, users still run into storage limits due to the package cache. 

Recently we have been suggesting to edit .condarc to designate a directory outside of $HOME for envs_dir and pkg_cache [see this blog post for reference](https://hyak.uw.edu/blog/conda-disk-storage/). I'm concerned this advice was a mistake or is missing a step. The reason I have opened this issue in Documentation is that I didn't see any warnings of this issue in Documentation; indeed, it is suggested in some situations https://docs.anaconda.com/free/working-with-conda/packages/shared-pkg-cache/. 

Users build their new environment and initial tests are successful. However, after deactivating the environment and returning to it, they face the following error:
![error](https://github.com/conda/conda/assets/22206944/3ed05847-749e-4507-b948-0d09d59a9e62)

env name: wu_tlaxe in this case
prefix: /gscratch/scrubbed/user/envs/wu_tlaxe

$HOME/.condarc:
![condarc](https://github.com/conda/conda/assets/22206944/5f2f0952-8415-43a3-8387-14e1c1d07b0a)

Miniconda is in $HOME/miniconda3 as is the base environment. 

Following the error, after activating the environment, I found that indeed aliases.py is missing from the encodings module in the environment directory (specifically, /gscratch/scrubbed/user/envs/wu_tlaxe/lib/python3.10/encodings/). Other basic utils of python were also missing in the environment directory, namely, site.py, _collections_abc.py, and posixpath.py. These files are present in $HOME/miniconda3 installation directory (in this case, $HOME/miniconda3/lib/python3.12/). 

I made symbolic links from $HOME/miniconda3/lib/python3.12/ encodings/aliases.py, site.py, _collections_abc.py, and posixpath.py in /gscratch/scrubbed/user/envs/wu_tlaxe/lib/python3.10/ and was able to run python3 import sys -c "print(sys.path)" without error, but the user found more missing files when running their protocol. Obviously making numerous symbolic links is not a solution, but was part of my process to better understand the issue. 

My hypothesis is that during the initial build of the environment, there is a connection to $HOME/miniconda3/lib so the essential files are available and everything works well. After the environment is deactivated, `conda activate` is no longer opening the links to $HOME/miniconda3/lib resulting in the error. 

Three users who designated envs_dirs and pkgs_dirs outside of $HOME/miniconda3 have gotten to this error via distinct miniconda builds, distinct environments, multiple versions of python, and distinct packages and goals. Additionally, CondaVerification errors might also follow, requiring the user to clear the package cache. 

My questions: 

1. Is there better solution for users to install miniconda3 elsewhere on the gpfs mount (where there is no storage limit), so that envs and pkgs can remain within the miniconda3 directory and avoid exceeding disk quota? 
2. Some users do not have permanent storage without a 10GB quota, do you have suggestions for how to configure miniconda3 to manage storage, but also not lead to the issues described above? Have I overlooked additional settings that could be used to use the .condarc configuration in the way described above? Perhaps by using a default package list when building environments?

Thank you for your time replying. 

### Additional Context

Our cluster is Linux Rocky8.

**Comment by travishathaway** [comment]
Hi @finchnSNPs,

Thank you for writing such a detailed issue! We'll be more than happy to try and figure out the best way forward for you and your organization. I am hoping we may also be able to use this as a case study to help improve our documentation too.

Regarding question number one, I'm curious whether you have tried to just install Miniconda itself to this other mount location. This would be possible by running the following commands:

```
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O
bash Miniconda3-latest-Linux-x86_64.sh -p /gscratch/scrubbed/user/miniconda
```

`/gscratch/scrubbed/user/miniconda` would be the location of the Miniconda install. That would place the installation entirely there and there would be no need to reconfigure it afterwards.

As for what the underlying reason is for the environments breaking by having missing files, my gut feeling tells me it has something to do with the way conda creates hard links between the package cache and the environments itself, but I am not sure.

Regarding your second question, are you asking whether there's a way for conda to provide earlier warnings about reaching disk quota? Unfortunately, this is currently not possible, but sounds like a great feature request. Please clarify if you meant something else.

**Comment by finchnSNPs** [comment]
@travishathaway thank you for the quick response. 

## New Information

The user whose files I used as examples in my initial issue reinstalled miniconda3 in `/gscratch/scrubbed/user/miniconda3` as you suggested. Here are some relevant commands from their history: 

```
bash Miniconda3-latest-Linux-x86_64.sh -p /gscratch/scrubbed/user/miniconda3
conda init bash
```
They deleted `/gscratch/scrubbed/user/envs` and `/gscratch/scrubbed/user/conda_pkgs` and rebuilt the environment:
```
conda create -p /gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe python=3.10 -y
conda activate wu_tlaxe
```
The user reported that the conda worked properly without error in an interactive shell and via a bash script submitted to out job scheduler. It looks like there were some errors, but not with the environment itself (for example the job ended because CUDA ran out of memory). 

The batch script for our job scheduler (SLURM):
```
[user@klone-login03 user]$ a40_llama.sbatch
#!/bin/sh

#SBATCH --job-name=dwnsmpl_llama_a40
#SBATCH --mail-type=BEGIN,END
#SBATCH --chdir=/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama

#SBATCH --account=stf
#SBATCH --partition=ckpt
#SBATCH --nodes=1
#SBATCH --cpus-per-gpu=4
#SBATCH --mem=48G
#SBATCH --gres=gpu:a40:1
#SBATCH --time=8:00:00 # Max runtime in DD-HH:MM:SS format.

#SBATCH --export=all
#SBATCH --output=/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/models/dwnsmpl/logs/a40_%x_%j.out # where STDOUT goes- %x is the job name above, and %j is the job ID, unique to each job
#SBATCH --error=/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/models/dwnsmpl/logs/a40_%x_%j.err # where STDERR goes

sh llama.sh
```

And (notice a // typo in the source line to activate, but the job seemed to go through anyway):
```
[user@klone-login03 user]$ cat llama.sh
#!/bin/sh

#source /gscratch/stf/jmeld/miniconda3/etc/profile.d/conda.sh
#conda activate /gscratch/stf/jmeld/miniconda3/envs/kidzbop
#source /mmfs1/home/jmeld/miniconda3/bin/activate /gscratch/scrubbed/jmeld/envs/wu_tlaxe
source /gscratch/scrubbed/jmeld/miniconda3//bin/activate wu_tlaxe

python /gscratch/scrubbed/jmeld/exalt/wu_tlaxe/neural_nets/llama/main.py -train /gscratch/scrubbed/jmeld/exalt/wu_tlaxe/dataset/d4/dwnsmpl_balanced_no_translationese_train.jsonl -dev /gscratch/scrubbed/jmeld/exalt/wu_tlaxe/dataset/d4/dwnsmpl_balanced_no_translationese_validation.jsonl -test /gscratch/scrubbed/jmeld/exalt/wu_tlaxe/dataset/d4/exalt_emotion_test_participants.jsonl -mode train -checkpoint meta-llama/Meta-Llama-3-8B -epochs 100 -patience 2 -dir /gscratch/scrubbed/jmeld/exalt/wu_tlaxe/neural_nets/llama/models/dwnsmpl/

conda deactivate
```

STDOUT: 
```
[user@klone-login03 user]$ cat a40_dwnsmpl_llama_a40_18302494.out
beginning of main loop:
total    : 48305799168
free     : 47605481472
used     : 700317696
device: cuda
before model loaded, after dataset dataloaders loaded:
total    : 48305799168
free     : 47605481472
used     : 700317696
after model loaded:
total    : 48305799168
free     : 41004367872
used     : 7301431296
===== Epoch 1 =====
total    : 48305799168
free     : 41004367872
used     : 7301431296
Training...
batch: {'input_ids': tensor([[128000,  30854,    757,   1759,  60642,  76743,   1001,    612,   1141,
           2652,   4864,   2145,    665,  27584,  27138,   1744,   4864,    436,
           3064,   2070,   1647,  77072,   1765,    514,  23068,    409,    364,
             82,     13,  12095,   9189,    841,    514,    924,    535,     89,
           6502,     11,  15265,  17536,   1826,  10998,  40770,     13,    220]]), 'attention_mask': tensor([[1
(TRUNCATED)
```
STDERR:
```
[user@klone-login03 user]$ cat a40_dwnsmpl_llama_a40_18302494.err
/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
`low_cpu_mem_usage` was None, now set to True since model is quantized.
Loading checkpoint shards: 100%|██████████| 4/4 [00:24<00:00,  6.09s/it]
Downloading builder script: 100%|██████████| 6.77k/6.77k [00:00<00:00, 43.1MB/s]
Traceback (most recent call last):
  File "/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/main.py", line 188, in <module>
    main()
  File "/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/main.py", line 136, in main
    training_loop(model, train_dataloader, valid_dataloader, num_epochs, patience, seed_val, path)
  File "/mmfs1/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/train_settings.py", line 82, in training_loop
    outputs= model(**batch)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mmfs1/gscratch/scrubbed/user/exalt/wu_tlaxe/neural_nets/llama/model_settings.py", line 54, in forward
    outputs= self.model(input_ids= input_ids, attention_mask= attention_mask)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/peft/peft_model.py", line 1129, in forward
    return self.base_model(
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1211, in forward
    outputs = self.model(
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1018, in forward
    layer_outputs = decoder_layer(
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 756, in forward
    hidden_states = self.mlp(hidden_states)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 240, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 468, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 509, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
  File "/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1349, in dequantize_4bit
    out = torch.empty(quant_state.shape, dtype=quant_state.dtype, device=A.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 
```
As you can see, the new version of the environment under `/gscratch/scrubbed/user/miniconda3/envs/wu_tlaxe/` is active.

stdout and stderr were last edited May 14 at 22:15. This morning I logged in as the user and:
```
[user@klone-login03 user]$ conda info
Could not find platform independent libraries <prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/gscratch/scrubbed/user/miniconda3/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/gscratch/scrubbed/user/miniconda3/lib/python3.12'
  sys._base_executable = '/gscratch/scrubbed/user/miniconda3/bin/python'
  sys.base_prefix = '/gscratch/scrubbed/user/miniconda3'
  sys.base_exec_prefix = '/gscratch/scrubbed/user/miniconda3'
  sys.platlibdir = 'lib'
  sys.executable = '/gscratch/scrubbed/user/miniconda3/bin/python'
  sys.prefix = '/gscratch/scrubbed/user/miniconda3'
  sys.exec_prefix = '/gscratch/scrubbed/user/miniconda3'
  sys.path = [
    '/gscratch/scrubbed/user/miniconda3/lib/python312.zip',
    '/gscratch/scrubbed/user/miniconda3/lib/python3.12',
    '/gscratch/scrubbed/user/miniconda3/lib/python3.12/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007fb4f7677240 (most recent call first):
  <no Python frame>
``` 
For further reference, 

```
[user@klone-login03 user]$ pwd
/gscratch/scrubbed/user
[user@klone-login03 user]$ ls -a
.   .cache  .condarc                           datasets          exalt       miniconda3
..  .conda  Miniconda3-latest-Linux-x86_64.sh  environment.yaml  exalt_demo
[user@klone-login03 user]$ cat .condarc
channels: 
  - conda-forge
  - bioconda
  - defaults
auto_activate_base: true
envs_dirs:
  - /gscratch/scrubbed/user/miniconda3/envs
pkgs_dirs:
  - /gscratch/scrubbed/user/miniconda3/pkgs
[user@klone-login03 user]$ ls -a .cache
.  ..  conda
[user@klone-login03 user]$ ls -a .cache/conda/
.  ..  notices
[user@klone-login03 user]$ ls -a .cache/conda/notices/
.  ..  notices.cache
[user@klone-login03 user]$ ls -a .conda
.  ..  .conda  aau_token  environments.txt
[user@klone-login03 user]$ ls -a .conda/.conda/
.  ..  aau_token
[user@klone-login03 user]$ echo $PATH
/gscratch/scrubbed/user/miniconda3/condabin:/mmfs1/home/user/.local/bin:/mmfs1/home/user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
[user@klone-login03 user]$ cat $HOME/.bashrc 
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/gscratch/scrubbed/user/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/gscratch/scrubbed/user/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/gscratch/scrubbed/user/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/gscratch/scrubbed/user/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

```

I know this is not ideal because the previous installation could be effecting this new installation, but in this case package cache and envs directories are within miniconda3. 

## In Response & Clarifications

Users have methods available for monitoring their storage. I wouldn't expect this of a particular software.

My larger concern is, are there solutions for maintaining hard links after designating directories outside of miniconda3/ for package cache and envs, making configuration of these directories an option for storage management especially for users with limited storage resources? 

We suggest on our documentation that if it is possible, miniconda3 installation should be elsewhere on /gscratch/, for example some user groups have larger storage quotas. I haven't gotten reports of this type of error from users who kept their installation "intact" in a location with adequate storage. 

Two types of users experience this error. Both groups edited ~/.condarc to designate storage for package cache and envs directories outside of the miniconda3 directory: 
1. users who have miniconda3/ in their $HOME and hit storage limits and so set up package cache and envs directories elsewhere with adequate storage.
2. users who are using a shared miniconda3/ and need package cache and envs directories for packages their projects and environments they build. By default, their "individual" package cache goes to $HOME where storage is limited and they use ~/.condarc to pick a different directory with adequate storage.  

*(3. I guess the third case is now second attempt install, miniconda3 enclosing package cache and envs directories, conda broken after initial usage.)*

If the answer is that package cache and envs directories should remain within miniconda3/ (although multiple installs might complicate matters), that will work for users with access to storage resources. However, we have some student users who only have 10G in $HOME and /gscratch/scrubbed or our "free-tier" storage. Another wrinkle, /gscratch/scrubbed storage expires. Files are deleted automatically if not used for several weeks. A miniconda3 install in scrubbed (package cache and envs directories as well) might be a temporary solution. To be clear, the issue here is environments or conda itself breaking after initial usage, not usage after a number of weeks.

**Comment by travishathaway** [comment]
@finchnSNPs,

To answer your question, the `envs_dirs` and `pkgs_dirs` settings should be all that you need in order to get this working. You should be able to relocate this to any arbitray location on your system as long as the users have read and write access, but clearly you are running into difficulties with this. The setup you are speaking about is something that is not currently well documented from our side, but we wish to improve that situation.

I think the ideal thing to do would be for the maintainers to first experiment with this setup ourselves and then document it in a tutorial on our documentation. While completing this tasks, we may unearth bugs or potential problems in conda itself and deal with those in turn.

The conda maintainers unfortunately have no access to HPC systems, so this is where your help would be greatly appreciated. Once we have written a tutorial we feel is adequate, we would like to have you verify it on your own systems.

We cannot promise when this will be completed, but this has been on our radar for quite some time, and you represent a group of users we would like to serve better. I will bring this up soon with the other maintainers for discussion.

Please let us know if you have any more questions.

**Comment by finchnSNPs** [comment]
@travishathaway,

Thank you for your time. I'm happy to test potential solutions when you have a protocol for us.

Please let me know if I can provide any additional information.

**Comment by travishathaway** [comment]
I've begun looking at this issue more and wanted to give a brief update.

I tried as best as possible to recreate an environment with mount network drives. I accomplished this by creating to Ubuntu Server VMs and then designating one as an NFS filesystem host. On the other, I installed conda into the user's home directory and then configured `envs_dirs` and `pkgs_dirs` to be stored on the NFS mount. I unfortunately wasn't able to recreate any of the errors seen here.

While doing that though, I did have the opportunity to document the procedure I took in conda to set this up and wrote the following how-to article for our documentation:

- https://continuumio-conda-docs--13954.com.readthedocs.build/projects/conda/en/13954/user-guide/configuration/custom-env-and-pkg-locations.html

This is part of the following pull request:

- https://github.com/conda/conda/pull/13954 (comments welcome)

@finchnSNPs,

While research this some more, I came across the following setting: `always_copy`. Setting this to `true` would remove the hard linking. It would take up more disk space, but perhaps this could fix the issue of missing files? Do you have the ability to test this out for me?

If so, I could add that as a possible recommendation to the article above if users come across the same problem.

**Comment by finchnSNPs** [comment]
@travishathaway Thank you for preparing the article. I commented on the PR. 

I can test `always_copy=true` this is my plan: 
1. build two identical new environments
* one with `always_copy=true`
* one default (`always_copy=false`)
* note: these would be in separate sessions (shells)
2. activate the environments and perform some limited usage to confirm the environment is free of other issues. 
3. end session and log out
4. log in and reactivate environments, try to recreate the error
5. trace error back by confirming missing files (files that were previously hard linked) in the `always_copy=false` environment. 

Please send feedback if necessary. I think the users have moved on to different solutions, but I hope to create this test soon and reply with the results. 

Thank you for your time.

**Comment by finchnSNPs** [comment]
`always_copy` appears to be the solution after some testing. The way to include it in the `.condarc` configuration file is with `always_copy: true` rather than the above utilizing the `=`.

Thank you @travishathaway for looking into this matter.
