### ISSUE TITLE
conda build should warn instead of faile when a file:// channel does not exist

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#1393]
Change conda build to warn only when a file:// channel in the .condarc file or from the command line doesn't exist.

**Comment by asmeurer** [comment]
I like having an error on bad urls. It makes it clearer if you mistype a binstar username at the command line, for instance.

**Comment by kalefranz** [comment]
Bad things happen to the solver and environments when the full set of channels that user has requested doesn't exist or is unavailable.  The fail-early situation here is by far the better user experience when balancing the full flow.
