### ISSUE TITLE
ctypes find_library() on osx

### ISSUE THREAD

**Issue by rokuingh** [conda/conda#1394]
When used on osx, the ctypes find_library() command does not find dependency libraries (probably because it does not search anaconda lib directories - seems to work fine on linux).  This can be worked around by setting DYLD_LIBRARY_PATH.  A similar issue was discussed in ticket [#308](https://github.com/conda/conda/issues/308#issuecomment-26323101), with the final decision being that the underlying issues in the library (ZMQ::FFI) should be fixed rather than depending on DYLD_LIBRARY_PATH.  What is the suggested solution for building conda distributions on osx for libraries that depend on ctypes.find_library()?

**Comment by asmeurer** [comment]
I've seen this issue [before](https://github.com/ioos/conda-recipes/issues/184). We may need to patch find_library so that it does the right thing in Anaconda.

**Comment by rokuingh** [comment]
We've seen some similar issues in other libraries which use ctypes. Will 
work on tracking those back to their source as well, if you like.  Do 
you have a handle on the patch to find_library()?  Let me know if there 
is anything my team can do to help.

**Comment by rokuingh** [comment]
Sorry about that last mail, I meant to say that we've seen some similar 
issues in libraries that use Cython!

**Comment by richlewis42** [comment]
Any developments on this? [cairocffi](https://github.com/SimonSapin/cairocffi) uses find_library to find cairo's dylibs, but can't find those from the conda cairo package on Mac, as these are put in the anaconda libs dir - it works when you add the lib dir to DYLD_LIBRARY_PATH, but from reading above, this is clearly not the way to fix this.

**Comment by rokuingh** [comment]
Not much development here, although there is another developer in our group @bekozi working on a possibly related issue with Darwin systems not correctly linking the installed version of a library.  It is currently being handled using install_name_tool : https://sourceforge.net/p/esmf/tix/3613956/

**Comment by basnijholt** [comment]
> We may need to patch find_library so that it does the right thing in Anaconda.
 
This would be great! Is it somehow on a list somewhere?

**Comment by kalefranz** [comment]
CC @mingwandroid

**Comment by rolando** [comment]
I had this issue with `ijson` (requires `yajl` lib from the `conda-forge` channel).

```
In [1]: import ijson.backends.yajl2
---------------------------------------------------------------------------
YAJLImportError                           Traceback (most recent call last)
<ipython-input-1-cad02275774a> in <module>()
----> 1 import ijson.backends.yajl2

/Users/rolando/miniconda3/envs/py35/lib/python3.5/site-packages/ijson/backends/yajl2.py in <module>()
     10
     11
---> 12 yajl = backends.find_yajl_ctypes(2)
     13
     14 yajl.yajl_alloc.restype = POINTER(c_char)

/Users/rolando/miniconda3/envs/py35/lib/python3.5/site-packages/ijson/backends/__init__.py in find_yajl_ctypes(required)
     25     so_name = util.find_library('yajl')
     26     if so_name is None:
---> 27         raise YAJLImportError('YAJL shared object not found.')
     28     yajl = cdll.LoadLibrary(so_name)
     29     require_version(yajl.yajl_version(), required)

YAJLImportError: YAJL shared object not found.

In [5]: import os

In [6]: os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = '/Users/rolando/miniconda3/envs/py35/lib/'

In [7]: import ijson.backends.yajl2

In [8]:
```

**Comment by kalefranz** [comment]
Moving this to anaconda-issues. The proposal here is to patch python `find_library`, so it'll have to go through that issue tracker anyway.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1716
