### ISSUE TITLE
Installation of conda on Azure arm64 VM with Ubuntu OS

### ISSUE THREAD

**Issue by MikeB2019x** [conda/conda#13951]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Azure is offering arm64 environments with Ubuntu OS.  None of the installer links [here](https://docs.anaconda.com/free/miniconda/) seem appropriate.

**Comment by travishathaway** [comment]
Hi @MikeB2019x,

The Linux Arm installer should work:

- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh

Can you please try it out and let us know if works for you?

**Comment by MikeB2019x** [comment]
@travishathaway Using `aarch64.sh` has worked so far.  I had some troubles with installing Jupyter Notebook 6.5.6 but don't believe it has much to do with aarch64.  So this approach is a solution for:  

[Azure Standard E20ps v5](https://learn.microsoft.com/en-us/azure/virtual-machines/epsv5-epdsv5-series) (20 vcpus, 160 GiB memory) with Ubuntu 22.04
