### ISSUE TITLE
Signatures are not secure or safe

### ISSUE THREAD

**Issue by dstufft** [conda/conda#1395]
Taking a look at the signature verification in conda, I see several issues which result in the signature system being fairly broken as is.
- Currently it's using 1024 bit RSA keys (according to [teoliphant](https://twitter.com/teoliphant/status/614173906358943744)). This is not a safe size for RSA keys, there is some indication that some nation state adversaries can already brute force a private key from a public key, and attacks only get better and faster. This should be at least 2048 if not 4096.
- It's using "Textbook" or "Raw" RSA. This is really bad and more or less breaks the security of the crypto system. The exact math behind it is opaque to me, but you can see it being discussed [here](http://rdist.root.org/2009/10/06/why-rsa-encryption-padding-is-critical/), [here](https://crypto.stackexchange.com/questions/20085/which-attacks-are-possible-against-raw-textbook-rsa), and many more papers and presentations from cryptographers about the topic if you google for it.

My suggestion would be to deprecate this feature immediately and try to attract a cryptographer or a security engineer to help design the secure system. In particular the folks behind [TUF](http://theupdateframework.com/) have been extremely helpful and will likely be the solution used by pip/PyPI. At the very least you should just use gpg or NaCl for signatures if you don't want to or can't find someone willing to help.

**Comment by coderanger** [comment]
Additionally the signature documentation mostly hand-waves about how to distribute and manage which keys are trusted for which packages. This should have clearer guidelines and processes for the user to follow that will result in safe operation.

**Comment by ilanschnell** [comment]
I just added an option `--size` to change the size of the RSA keys to the `conda sign --keygen` option.  The default is now 2048 bit, keys pairs using 4096 (or even larger) can also be handled.
https://github.com/conda/conda-build/commit/1d394e0f99015117dfdd9cd690874bd0a02f6f0f

**Comment by dlitz** [comment]
No, @ilanschnell, stop.  It's 2015.  You ought to know by now that implementing your own crypto is not OK.

Increasing the key size in a textbook RSA implementation is not helpful.  @dstufft told you something that you could do:

> deprecate this feature immediately and try to attract a cryptographer or a security engineer to help design the secure system. ... At the very least you should just use gpg or NaCl for signatures if you don't want to or can't find someone willing to help.

I'll go further and say that there are already too few experts working on too many crypto implementations, so even if this implementation were correct (which it definitely isn't), just having Another Crypto Implementation undermines everyone's security.

Conda and pip should not have different signature systems.

**Comment by asmeurer** [comment]
@dstufft @coderanger @dlitz are you volunteering to help out with this?

**Comment by coderanger** [comment]
Surely, would you like me to submit a pull request removing all signature related code? I don't mean to be (much of) a jerk, but that would be the right move if you don't think you have the resources to build this correctly. Security is a place where "close enough" is not.

**Comment by dstufft** [comment]
I'm happy to provide advice, but I'm unlikely to have time to submit code. I have a packaging toolchain I actually use to work on (and which I'm paid to work on, improving a toolchain my employer doesn't use is probably outside the scope of my directive..). The code was pointed out to me (as things that tend to involve some subset of {Python, Packaging, Crypto} tends to cause people to point things out to me) and I noticed the issues so I figured I'd let you know.

Personally I think that no signatures is a better answer than a fundamentally broken one, but given that I don't use nor have time to work on it what y'all do about it is ultimately not going to affect me. However the current code does not do what it's intended to do and at a minimum a CVE should be requested for it even if y'all don't do anything else with it.

**Comment by ilanschnell** [comment]
@dlitz 
>> No, @ilanschnell, stop. It's 2015. You ought to know by now that implementing your own crypto is not OK.

I didn't implement my own crypto.  I'm using `pycrypto` for all cryptographic functionality.

**Comment by teoliphant** [comment]
@dstufft  We do appreciate the advice, but it's hard to parse.  Are you saying that pycrypto is fundamentally broken?   That use of RSA is fundamentally broken for all cases?   These are both rather strong statements.     Would pycrypto's other signing approaches (i.e. DSA) be appropriate? 

There are many different applications of package signing with different API needs, different deployment factors involving different risk needs and attack surfaces.   Is this really an area where one size fits all?  Is pycrypto's RSA implementation, raw RSA?

**Comment by dstufft** [comment]
The part of PyCrypto you're using is the textbook/raw RSA, unfortunately that by itself isn't secure so you need to use a construction to ensure that the problems with raw RSA are worked around. This is actually in the documentation for the method that conda is using in the PyCrypto docs where they recommend the use of PSS or PKCS#1 v1.5 instead. My memory is a little foggy around those two, I think that v1.5 is "probably ok" but that PSS is the one you likely want to use if you're using RSA now. Things like DSA have similar stories if i recall correctly, where you need to make sure you use them in the correct way, and the correct way is often non-obvious and the wrong way is equally non-obvious.

PyCrypto unfortunately (sorry @dlitz!) follows the pattern of many crypto libraries where it gives you a box full of crypto legos and (mostly) leaves it up to you to figure out which legos are safe and in which combination. This isn't an uncommon situation to find yourself in and people using an otherwise secure algorithm in an insecure construct is the cause of a lot of CVEs.

As far as where to go from here, I want to first preface this with the statement that I am not a cryptographer and a lot of the math is beyond my abilities. I do however have a working knowledge of how to implement some parts of a secure cryptosystem (at least at a level higher than average). If you want to be really sure you're doing the right thing engaging a real expert is the best thing to do.

That being said, what I think you should do depends on what you're trying to achieve here. Signatures are great but there are a number of ways to attack a package repository even with signed packages where the signatures were done in a completely correct way. [TUF](http://theupdateframework.com/) is a system designed to handle securely fetching updates and it is my intent to integrate that with PyPI/pip once I get far enough down the stack to that point. It protects against a number of things like people blocking updates for a particular version of a library (say you have versions 1.0 and 1.0.1, where 1.0 is insecure but 1.0.1 has the fix, they'd block clients from seeing 1.0.1), or presenting the client with a inconstent state of the repository where the combination of packages may combine to be insecure, as well as other attacks. The folks behind it are friendly and helpful and I'm sure they'd be willing to help integrate it (It was a PhD project).

If you're not looking to protect against those kinds of attacks and you're just looking for something that will verify the files itself, then my first suggestion would be to throw away RSA completely and just use the signature support in NaCl. NaCl is a library written by an actual cryptography (Daniel J Bernstein) where the idea was that the interface of existing libraries make it too easy for people to get things wrong, so it won't let them do that. The biggest problem with NaCl is it uses "less standard" primitives (in particular, signing uses ed25519) which are still fairly standard and wide used but which might matter in some regulatory situations (such as if you're trying to comply with the FIPS 140-2 requirements of the United States Government). I'm *probably* going to use ed25519 in PyPI/pip because it produces deterministic signatures and the keys and signatures are quite small (64 byte signatures, 32 byte keys). The interface provided by the C library (which if you do, you want to use libsodium, not the original NaCl library) is similar to what you're using here, you get a simple sign/unsign API with the exception that it makes all the decisions for you, and those decisions were made by an actual cryptographer. There are a number of Python bindings to do this, including one I wrote called PyNaCl.

If for whatever reason you're not comfortable using ed25519 (which I would think long and hard before deciding I wasn't comfortable using it), I *think* that if you use RSA-PSS with at least 2048 bit keys (though I'd suggest larger if possible) then the actual "sign this file and verify it" part would be safe.

On top of all of that, the point that @coderanger made about needing more guidance about how to deal with trust is an important one as well. Even the most secure signature scheme is only as good as the trust model that is in play. The typical linux model is that the signing keys are associated with a particular repository, and if you trust that repository you generally trust it for *anything*. I don't know enough about conda to know if that is acceptable, but it's not for PyPI (because just because you trust me to sign a release for pip, that doesn't mean you trust me to sign a release for bokeh). TUF can help here if you need to be able to delegate portions of a single repository to different signing keys, but the simpler, "flat" model of the Linux repositories isn't wrong if each Conda repository is assumed to be owned by a single entity (be it a person, a project, or a company) and you generally assume you trust them entirely across the entire namespace.

Another problem with the current approach (which would persist even if you swapped out RSA for NaCl) is that these signature schemes have no concept of revocation or key expiration. That means you need to bake the idea into conda itself how you're going to handle the case where a key becomes compromised and how you handle that. A simple, but not particularly friendly, way is to just swap your singing key and tell everyone to manually update the signing keys to the new one in their conda installs. This is again something that TUF can help with.

I know I wrote a ton of words, so just to summarize:

1. If you can talk to the folks behind TUF and use TUF to secure conda, that would cover a lot of cases that you've probably not thought about and they've done a lot of the hardwork in designing a secure cryptosystem for package managers.
2. If you can't or don't want to use TUF, I would suggest ed25519 via NaCl with the understanding that there are going to be things you're not handling, but that the basic case of "verify this file was signed by this key" would be correct.
3. If you can't or don't want to use ed25519, then I would suggest RSA-PSS with at least 2048bit keys (but recommend larger) with the same understanding about things you're not handling from above.

Hopefully if anything I said is incorrect here, one of the other folks who have participated will point it out quickly :)

**Comment by dstufft** [comment]
Oh, and in either case, I recommend getting a CVE from cve-assign@mitre.org. This isn't a bad/negative thing to have, it just makes it so that people know that the affected versions of conda have an unsafe signature mechanism.

**Comment by dstufft** [comment]
Another thing:

It's typically better to settle on something called a threat model before you start implementing protections against particular attacks. The reason for this is just so you have some idea of what you're trying to protect against, because there is no such thing as a completely secure system, just ones that protect against particular attacks. Knowing what you're trying to protect against will influence what choices you want to make.

An example using pip (since it's what I'm most familar):

We currently operate under a threat model which says that the operators of the repository (e.g. PyPI), the machines running the repository, as well as the authors of the projects that the user has chosen to install are considered "trusted" and we don't attempt to protect against any of them being malicious. This means that our threat model are network attackers who sit between the user executing pip and PyPI, but does not include a malicious repository administrator, or a compromised machine running PyPI.

Looking at that threat model, TLS is the best fit for us right now since it is designed to protect against network attackers but not anyone on either side of the connection. 

In the future we intend to expand that threat model to include other attackers and types of attacks, but by defining the threat model first, we give ourselves a set of success criteria to evaluate any potential solution against and we guard against scope creep where we try to protect against extra stuff by making things more complicated without fully thinking through to figure out what threat we're trying to protect against and whether or not the total solution actually protects against it or whether the system is vulnerable to the software equivalent of:

![grbesk2](https://cloud.githubusercontent.com/assets/145979/8370266/6f9e016a-1b93-11e5-945b-29ffffa4be80.gif)

**Comment by teoliphant** [comment]
@dstufft  Thanks for the detailed write-up and sharing your experience and knowledge.    Our use-case for the signed packages currently implemented is for orgs using conda internally on their own networks, clusters, or VPN systems in a smaller scale.     We are not using it to secure packages available from anaconda.org or repo.continuum.io.  

Do you have a recommendation for a cryptography expert for hire who could help review our use-case and implementation?

**Comment by bkreider** [comment]
@dstufft Thank you for writing all of that.  I know bug reports are a thankless job.  It's obvious that you have spent a lot of time thinking about this problem and looking at the alternatives.  

@teoliphant Do we have any documentation around the threat model?

**Comment by ilanschnell** [comment]
I've created a PR https://github.com/conda/conda/pull/1399 , which makes use of PKCS1 PSS.  Along this is also a PR for `conda-build` https://github.com/conda/conda-build/pull/469

**Comment by asmeurer** [comment]
If I am reading https://github.com/theupdateframework/tuf/blob/develop/tuf/interposition/README.md correctly, tuf interfaces over urllib (whereas we use requests), and if I am reading the last line correctly, it doesn't support Python 3.

**Comment by dstufft** [comment]
TUF the library does that I believe yes, TUF the protocol is library (and language) agnostic.

**Comment by asmeurer** [comment]
But if I'm getting anything from this thread it's that you should reuse existing libraries, not try to reimplement protocols. I'm not seeing a clear way forward with tuf and conda, at least from what I've read of tuf so far (which is admittedly not a ton).

**Comment by dstufft** [comment]
It is preferable to use something off the shelf yes, though if a suitable off the shelf library doesn't exist it's not unusual to be forced to implement yourself. This is especially true for higher level cryptosystems like a package update system rather than lower level primitives. I believe they have a fork of pip that uses TUF and pip itself uses requests (though it's possible they forked it from before we did).

Hopefully y'all don't mind, but I'm going to ping @vladimir-v-diaz and @JustinCappos (I know there are others, but their github names are escaping me right this moment). They are the folks behind TUF and perhaps they can offer some more targeted advice or maybe even help.

**Comment by asmeurer** [comment]
I would love input from TUF folks on this. That would be much more efficient than me trying to read through its docs and code to see what it can and cannot do.

**Comment by dstufft** [comment]
They also having a mailing list fwiw, it's pretty low traffic but might be a better place to reach them as well. I don't know how much they look at Github. It's at https://groups.google.com/forum/?fromgroups#!forum/theupdateframework.

**Comment by vladimir-v-diaz** [comment]
@asmeurer You are welcome to ask questions (about the framework or the Python library) on our mailing list.  We can also chat over voice / video if you prefer.

@dstufft Thank you for the excellent replies. :+1: 

NOTE: The current TUF Python library does support Python 3.  The interposition option (one method of integrating our framework with an update system) cannot currently interpose on `urllib3` and `requests` calls, but support will be added in the future.  The integration method we recommend is outlined [here](https://github.com/theupdateframework/tuf/tree/develop/tuf/client#updaterpy), which should work with conda.  We can chat over Skype / GH about adding specific features and libraries needed by conda.

**Comment by asmeurer** [comment]
I'll read through that and see if I have any questions.

**Comment by vladimir-v-diaz** [comment]
You may also review [PEP 458: Securing the Link from PyPI to the End User](https://github.com/pypa/interoperability-peps/blob/master/pep-0458-tuf-online-keys.rst#abstract) if you need more information about the framework, an example integration, PyPI's threat model, etc.

**Comment by asmeurer** [comment]
It looks like that may be doing more than what conda really needs. conda only needs to worry about two kinds of files from its repositories, the repodata.json.bz2, which contains the metadata for all the files in the repository, and the files for the packages themselves (see e.g., https://repo.continuum.io/pkgs/free/win-64/). conda in general takes multiple repositories (like repo.continuum.io and conda.anaconda.org/username) and merges the repodata together. I'm not sure how the "role" system (which isn't really explained in that document) would apply to this case.

**Comment by vladimir-v-diaz** [comment]
The [Survivable Key Compromise in Software Update Systems](http://freehaven.net/~arma/tuf-ccs2010.pdf) paper discusses the role system in more detail.  The framework relies on the role system to protect against [these weaknesses](https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md#security) in software update systems, and support design principles like responsibility separation and resilience to key compromise.   I'm not intimately familiar with conda's repository layout and use case, but we can discuss over Skype if conda should be concerned about these other security issues.

Sorry to the other participants for the flood of messages.

**Comment by nealmcb** [comment]
What is the status of the move to TUF?  I just ran across this issue, and I'm hoping that my [interaction last year](https://twitter.com/kalefranz/status/741094414085435392) with @kalefranz is bearing fruit.

To recap from 2016, since one of the pages where I discussed this is currently unavailable:

I'm alarmed to (still) see these instructions for installing Anaconda 4.3.0 for Linux, and similar approaches for Windows and Mac:
> 1. Download the installer
> 1. Optional: Verify data integrity with MD5 or SHA-256   More info
> 1. In your terminal window type one of the below and follow the instructions ... :
> `bash Anaconda2-4.3.0-Linux-x86_64.sh`

Suggesting the use of MD5 is a big red flag.  First, MD5 is a hash function that was broken in 2005, and it takes just a moment to produce packages that have the same MD5 sum, one of which is malicious and the other of which is good.  If there was a reason to rely on hash functions, you should avoid MD5 and only document a SHA-256 option.

But really, you should use a mechanism in which you sign the package with a private key which is protected in depth (e.g. in hardware). Even SHA-256 is just a hash function, not a signature mechanism.

Why? Stepping up a level, we should indeed invoke @dstufft's call above for a focus on proper threat modeling.  

While the https://www.continuum.io/downloads page uses https, that doesn't actually provide much protection against attackers, who might well target Continuum as a distribution providing a great way to infiltrate lots of computers. It is well known that online web sites, like the ones you deliver your install script from, are vulnerable to determined attackers, as we see every day in the news.

Continuum's https-based security measures are nothing like the real signatures tied to individual packages provided by Ubuntu, or similar package-level signatures used in installation schemes for Windows, Mac etc. Those are provided by highly secured keys, presumably never put at risk on a computer attached to the Internet.

This is explained more at [Does hashing a file from an unsigned website give a false sense of security? - Information Security Stack Exchange](http://security.stackexchange.com/questions/1687/does-hashing-a-file-from-an-unsigned-website-give-a-false-sense-of-security)

As noted nearly two years ago in this bug, the best way for distributions and developers to do this right is via [The Update Framework (TUF)](https://theupdateframework.github.io/). E.g. Docker has done this via the [Docker Notary (Docker Blog) service](https://blog.docker.com/tag/docker-notary/).

In the meantime, one positive step would be to provide a "conda downloader / key management" package for Debian/Ubuntu systems, along with packages using the related mechanisms for other distributions and operating systems. Then updates could also be verified indirectly via keys trusted by the operating system.

**Comment by JustinCappos** [comment]
I'd like to chime in and say that the TUF team would be happy to help with
this.  Just let us know how best we can help...

**Comment by kalefranz** [comment]
We released conda 4.3 in January, and in that release we removed package signing support altogether.  Largely because of discussion here, we were concerned that its existence provided an illusion of security that was worse than not having it at all.

I'm working on wrapping up conda 4.4.0 into a canary release, and after we get conda 4.4 released to GA, my next big feature development project will probably be working on TUF implementation.

@JustinCappos I actually spent last night reading over the TUF spec and looking at the code again.  I promise not to be shy about reaching out with questions once I'm able to dig in.  What's the best/preferred way to contact the TUF team?

**Comment by kalefranz** [comment]
I'm going to close this ticket now.  I've created #5282 for future work.  A clear result of this ticket was the full removal of signing support in conda 4.3.

**Comment by JustinCappos** [comment]
Okay, glad to hear this!  We're happy to help.

You're welcome to email me directly or to email the TUF mailing list
(CCed).  Either way, someone should get back to you soon.

By the way, I have been working this week with Hannes Mehnert who mentioned
the roles part of the documentation is particularly hard to follow.  If you
find this confusing, definitely let us know.  We will be trying to clean
things up over the next few months though.

Justin
