### ISSUE TITLE
CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

### ISSUE THREAD

**Issue by Liiiiaictx** [conda/conda#13974]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I create a virtual environment on a Linux server and use the pip installation package, I encounter CondaSSLError. How can I solve this problem?

### Additional Context

![00](https://github.com/conda/conda/assets/151444958/3c5fbc00-cd0a-4b07-86e7-93d2763db03d)

**Comment by travishathaway** [comment]
@Liiiiaictx,

What are you installing with pip? There a chance that pip is re-arranging things in a way that conda is unaware and then causing this issue.
