### ISSUE TITLE
conda update all not working on windows 7

### ISSUE THREAD

**Issue by nsteinme** [conda/conda#1398]
Hey - hope I haven't done something very stupid, but "conda update --all" isn't working for me. It says I have to "close all processes running code from conda and try again." I tried rebooting and keeping everything closed, and it still doesn't work. I found a similar bug report (https://github.com/conda/conda/issues/1305) but "conda install conda=3.10.1" (to downgrade) and "conda update conda" both wouldn't run. I ran with the debug flag and got this:

![image](https://cloud.githubusercontent.com/assets/7590975/8385439/1a04b9d0-1c40-11e5-91c9-232684861a08.png)

**Comment by asmeurer** [comment]
`conda install -f conda` should fix this for you.

**Comment by nsteinme** [comment]
Thanks, worked.

**Comment by ThomasLecocq** [comment]
:+1: to add this in the "help" message ("please close..." is not clear)
