### ISSUE TITLE
Allow to build in parallel

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#140]
The build environments should be split out using tempfile, so that you can build in parallel. This has already bitten me twice today, because my instinct is to go and do something else while I am waiting for something to compile, but often that something else is to build something else, which stops the thing that was compiling.

**Comment by frol** [comment]
I hope this will be eventually implemented.

**Comment by tadeu** [comment]
:+1:

**Comment by jolos** [comment]
Just want to express my interest in this. Certainly for CI this would be very handy. Atm it's not possible to build several packages at the same time. I'm wondering how people solve this atm. For now we just use multiple vms/containers but you're still limited to 1 build/machine

**Comment by frol** [comment]
@jolos We internally implemented a sort of a wrapper around conda-build, which runs each conda-build in a fresh Docker container (which contains a prepared build environment).

**Comment by jolos** [comment]
@frol that's an interesting approach, but I guess that's not a solution when you also need to build for windows.

**Comment by frol** [comment]
@jolos oh yeah, we use Linux builds as a mainline, and OS X and Windows builds are usually gotten ready a couple hours later.

**Comment by mingwandroid** [comment]
Docker for Windows is coming in Server 2016. The license is, I believe, per-CPU, but it's an approach I'm interested in exploring.

**Comment by goanpeca** [comment]
Should this be migrated to https://github.com/conda/conda-build repo? @msarahan, @kalefranz

**Comment by kalefranz** [comment]
At this point, this will be broken out into tasks within the API project, along with all the new conda-build stuff. I think this ticket is safe to close.
