### ISSUE TITLE
`https://repo.anaconda.com/miniconda` returns `429: Too many requests`

### ISSUE THREAD

**Issue by harupy** [conda/conda#14005]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Sorry if this repository is not the right place to report this. When I tried to download a miniconda installer (https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh) on https://docs.anaconda.com/miniconda/, I got the following message. Is this expected?

```
{
"reason":"terms of service rate limit exceeded",
"message":"It has been determined that you are in violation of the Anaconda terms of service, and may not be licensed for usage."
}
```

**Comment by jan-golda** [comment]
We are also experiencing this - almost every request to `https://repo.anaconda.com/miniconda` returns `429: Too many requests`

This looks like a DDoS or a misconfiguration of the Anaconda server... and it has a serious impact on our systems

**Comment by kenodegard** [comment]
We are aware of this issue and are looking into it.

**Comment by kenodegard** [comment]
https://anaconda.statuspage.io/incidents/dd7q4ksyy55n

A fix has been deployed, let us know if the issue persists

**Comment by ZzEeKkAa** [comment]
@kenodegard could you take a look at #14007 . It looks like it is related to the issue. I have access to the miniconda installer, but I don't have access to the non default channels. Thank you!

**Comment by harupy** [comment]
@kenodegard thanks for the fix!

**Comment by aleto1999** [comment]
This issue has persisted for me with all requests to conda-forge

**Comment by suketududhat** [comment]
@kenodegard, we are still facing this issue using Miniconda3 on the conda-forge channels. Does the fix you mentioned apply to this as well?

**Comment by alwortma2** [comment]
@suketududhat @aleto1999 this is most likely an Intel issue. I installed miniforge3 on a clean VM in Azure and everything worked fine. Probably has something to do with the very limited number of network endpoints funneling all these requests from across the company.

**Comment by kteo1** [comment]
Hi, I'm getting this error when accessing https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh. 
{
"reason":"terms of service limit exceeded",
"message":"It has been determined that you are in violation of the Anaconda terms of service, and may not be licensed for usage."
}

Need to download later version in order to resolve vulnerability issue reported with the old version.  Appreciate if someone could look into this and resolve ASAP.
