### ISSUE TITLE
Option to create a standalone conda environment

### ISSUE THREAD

**Issue by peterbandi** [conda/conda#14032]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I use conda environment for development and in production. Miniconda is installed in a docker image and the environment is created from a .yaml file. Unfortunately, the Miniconda adds about 500MB to the image size above the size of the conda environment. I would like to have an option to create a "standalone" conda environment for production. This environment should work without the original Anaconda/Miniconda installation around it.

### Why is this needed?

- Reduce size of the docker images containing a conda environment.
- Remove the unnecessary support for multiple environments and their modification from the docker images.

### What should happen?

- The creation of a standalone conda environment might still need a standard Anaconda/Miniconda installation.
- The standalone environmet could be copied elsewhere (eg. to a docker image) and work without an Anaconda/Miniconda installation.
- The `conda` executable would not be part of the standalone environment and the environment would not facilitate the modification of it.

### Additional Context
This feature would be extremely useful in multi-stage docker builds where a separate stage could download and install Miniconda, and create the standalone environment, while the target image would copy only the created standalone environment from the aforementioned stage.

**Comment by travishathaway** [comment]
@peterbandi,

I would encourage you to check out the following project:

- https://conda.github.io/conda-pack/

I believe the use case it addresses closely aligns with what you have described here.

**Comment by jaimergp** [comment]
You might want to use a copy of https://github.com/conda/conda-standalone instead of an environment.

**Comment by peterbandi** [comment]
> @peterbandi,
> 
> I would encourage you to check out the following project:
> 
>     * https://conda.github.io/conda-pack/
> 
> 
> I believe the use case it addresses closely aligns with what you have described here.

Thank you! This is **exactly** what I was looking for. Probably, I didn't search for the right terms. I was able to install miniconda, build a conda environment, and pack it in a separate docker build stage. Then I could just copy the packaged environment to the target image in a single step. It works like a charm. 🙂
