### ISSUE TITLE
Support Custom dataset in training configuration of llamafactory-cli 

### ISSUE THREAD

**Issue by rudaoshi** [conda/conda#14035]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

To support custom dataset,  one must currently checkout the source and edit the dataset_info.json. However, since the repo gradually becomes a pip installable package (I'm very happy to see the llamafactory-cli), the custom dataset definition should also be supported as a parameter to llamafactory-cli.

**Comment by travishathaway** [comment]
@rudaoshi,

This is not the correct project for submitting feature requests for "llamafactory-cli". Please find where this project is hosted and submit a feature request there. Feature requests submitted here are specifically for the conda package manager and not the packages that it installs.

I will now be closing this as "off-topic". Thank you for understanding.
