### ISSUE TITLE
Installing python=3.8 or lower, got python=3.9.7

### ISSUE THREAD

**Issue by RoManInv** [conda/conda#14055]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Trying to install a conda env with python=3.8/3.8.8/3.7/3.6, all got python version 3.9.7. But installing python with higher versions gets the correct one. Upgrading python leads to the correct, latest version.

The python version listed here is inconsistent with what I have seen with `conda list`. The version with `conda list` shows the correct version that I have installed, but running `python --version` within this environment shows `Python 3.9.7`.

### Conda Info

```shell
active environment : pyprose
    active env location : F:\anaconda\condaenv\pyprose
            shell level : 3
       user config file : C:\Users\steve\.condarc
 populated config files : C:\Users\steve\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=12.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : F:\anaconda\anaconda  (writable)
      conda av data dir : F:\anaconda\anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : F:\anaconda\anaconda\pkgs
                          C:\Users\steve\.conda\pkgs
                          C:\Users\steve\AppData\Local\conda\conda\pkgs
       envs directories : F:\anaconda\condaenv
                          F:\anaconda\anaconda\envs
                          C:\Users\steve\.conda\envs
                          C:\Users\steve\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\steve\.condarc <==
env_prompt: ({name})
envs_dirs:
  - F:\anaconda\condaenv
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at F:\anaconda\condaenv\pyprose:
#
# Name                    Version                   Build  Channel
ca-certificates           2024.7.2             haa95532_0    defaults
certifi                   2024.7.4         py38haa95532_0    defaults
libffi                    3.4.4                hd77b12b_1    defaults
openssl                   3.0.14               h827c3e9_0    defaults
pip                       24.0             py38haa95532_0    defaults
python                    3.8.19               h1aa4202_0    defaults
setuptools                69.5.1           py38haa95532_0    defaults
sqlite                    3.45.3               h2bbff1b_0    defaults
vc                        14.2                 h2eaa2aa_4    defaults
vs2015_runtime            14.29.30133          h43f2093_4    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
```

**Comment by travishathaway** [comment]
@RoManInv,

Can you please share which commands you are running? I am having a hard time figure out exactly what is happening here.

**Comment by wolfv** [comment]
Your env has 3.8, but somehow `conda info` picks up a different `python`?

**Comment by RoManInv** [comment]
Hello travishathaway and wolfv,
here is the full replication of my issue.

## Initial Attempt
1. Activate conda env that I want to work with `conda activate pyprose`
2. The Python version using `python --version` under this env is `Python 3.10.4`. Additionally, there is only one package `pandas` (latest version) along with its dependencies installed.
3. Trying to replace Python with lower version using `conda install python=3.8.8`, got information of successfully installed
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: F:\anaconda\condaenv\pyprose

  added / updated specs:
    - python=3.8.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.7.2   |       haa95532_0         128 KB
    certifi-2024.7.4           |   py38haa95532_0         159 KB
    openssl-1.1.1w             |       h2bbff1b_0         5.5 MB
    pip-24.0                   |   py38haa95532_0         2.8 MB
    setuptools-69.5.1          |   py38haa95532_0        1003 KB
    ------------------------------------------------------------
                                           Total:         9.6 MB

The following packages will be REMOVED:

  wincertstore-0.2-py310haa95532_2

The following packages will be UPDATED:

  ca-certificates                     2022.07.19-haa95532_0 --> 2024.7.2-haa95532_0
  certifi                         2022.6.15-py310haa95532_0 --> 2024.7.4-py38haa95532_0
  openssl                                 1.1.1q-h2bbff1b_0 --> 1.1.1w-h2bbff1b_0
  pip                                22.1.2-py310haa95532_0 --> 24.0-py38haa95532_0
  setuptools                         61.2.0-py310haa95532_0 --> 69.5.1-py38haa95532_0

The following packages will be DOWNGRADED:

  python                                  3.10.4-hbb2ffb3_0 --> 3.8.8-hdbf39b2_5


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-24.0             | 2.8 MB    | ########################################################################################################################################################################################################################################## | 100%  
openssl-1.1.1w       | 5.5 MB    | ########################################################################################################################################################################################################################################## | 100%  
setuptools-69.5.1    | 1003 KB   | ########################################################################################################################################################################################################################################## | 100%  
certifi-2024.7.4     | 159 KB    | ########################################################################################################################################################################################################################################## | 100%  
ca-certificates-2024 | 128 KB    | ########################################################################################################################################################################################################################################## | 100%  
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
4. Check Python version again with `python --version` under this specific env, got `Python 3.9.7`

## Attempting to freshly create a new env
1. Creating env using `conda create -n newtestenv python=3.8.8`
2. After successfully installed, check Python version using `python --version`, got `Python 3.9.7`.
3. Repeating the steps to replace Python using `conda install python=3.8.8`, still got version `Python 3.9.7`.

## Other Attempts
1. Attempt to update conda with `conda update -n base -c defaults conda` as provided, and restart the PC. Got the same result as attempting to replace or fresh creation.

## Attempting to install on another machine
1. The conda on this machine has much lower version. It is not updated since long ago.
2. Repeating the attempts to replace Python and create a freshly new env, got the correct `Python 3.8.8` for both attempts.

## Additional Comments
I tried the same replacement and creation steps on other machines. I got the same problem on only one machine, but it is solved by simply uninstalling anaconda and removing all conda/anaconda-related files and restart the PC, then reinstall Anaconda. However, it would be really nice if I could find a way to install the lower version of Python without uninstalling Anaconda, as it has been taking much effort to create my current envs and it might still be risky even if I could export the package list of each env. I would not risk uninstalling anaconda if there might be other possible solutions.

**Comment by wolfv** [comment]
But your package list says:

```
python                    3.8.19               h1aa4202_0    defaults
```

**Comment by RoManInv** [comment]
That is exactly the issue. After replacing Python, the versions of Python are shown differently, and the wrong version is actually used. The following result come from the result of different commands after attempting to replace Python.

1. Installation info after `conda install python=3.8.8`
Here I get 
```
The following packages will be DOWNGRADED:

  python                                  3.10.4-hbb2ffb3_0 --> 3.8.8-hdbf39b2_5
```
2. Using `conda info` with the correct active env, got the info as in my initial post:
```
python version : 3.9.7.final.0
```
3. Using `python --version`, got `Python 3.9.7`
4. Using `conda list` under the desired env, got
```
python                    3.8.8               something    defaults
```
The `conda list` result in my first post (as you referred to) was after I tried to install different under-versions of 3.8.x. After I have tried 3.8.19 there is still no success and I came here for help.
5. When running python code and installing new packages, `Python 3.9.7` is actually in use.

**Comment by travishathaway** [comment]
@RoManInv,

It looks like your PATH maybe set incorrectly.  Can you please run the following command and share the output?

```
conda info --all --name pyprose
```

**Comment by jaimergp** [comment]
Yea, I'm curious about the output of `where python` and whether it comes from `%CONDA_PREFIX%`.

**Comment by RoManInv** [comment]
Hi all,
I have run `conda info --all` command (invalid argument --name) and here is the info related to `pyprose` env:

```
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: F:\anaconda\condaenv\pyprose
CONDA_EXE: F:\anaconda\anaconda\Scripts\conda.exe
CONDA_PREFIX: F:\anaconda\condaenv\pyprose
CONDA_PREFIX_1: F:\anaconda\anaconda
CONDA_PROMPT_MODIFIER: (pyprose)
CONDA_PYTHON_EXE: F:\anaconda\anaconda\python.exe
CONDA_ROOT: F:\anaconda\anaconda
CONDA_SHLVL: 2
CURL_CA_BUNDLE: <not set>
HOMEPATH: \Users\steve
PATH: F:\anaconda\anaconda;
F:\anaconda\anaconda\Library\mingw-w64\bin;
F:\anaconda\anaconda\Library\usr\bin;
F:\anaconda\anaconda\Library\bin;
F:\anaconda\anaconda\Scripts;
F:\anaconda\anaconda\bin;
F:\an\bin;
F:\anaconda\condaenv\pyprose;
F:\anaconda\condaenv\pyprose\Library\mingw-w64\bin;
F:\anaconda\condaenv\pyprose\Library\usr\bin;
F:\anaconda\condaenv\pyprose\Library\bin;
F:\anaconda\condaenv\pyprose\Scripts;
F:\anaconda\condaenv\pyprose\bin;
F:\anaconda\anaconda;
F:\anaconda\anaconda\Library\mingw-w64\bin;
F:\anaconda\anaconda\Library\usr\bin;
F:\anaconda\anaconda\Library\bin;
F:\anaconda\anaconda\Scripts;
F:\anaconda\anaconda\bin;
C:\Program Files\Common Files\Oracle\Java\javapath;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
F:\vm-workstation-16\vmworkstation\bin;
C:\Program Files (x86)\Razer[This is not relevant];
C:\Program Files\Razer[This is not relevant];
C:\Program Files (x86)\Razer[This is not relevant];
C:\Program Files\Razer[This is not relevant;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0;
C:\Windows\System32\OpenSSH;
C:\Program Files (x86)\NVIDIA[This is not relevant];
C:\Program Files\NVIDIA[This is not relevant];
C:\Users\steve\AppData\Local\Microsoft\WindowsApps;
C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;
F:\putty;
C:\Program Files\dotnet;
F:\github\Git\cmd;
F:\princexml\engine\bin;
.;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0;
C:\WINDOWS\System32\OpenSSH;
C:\Users\steve\AppData\Local\Microsoft\WindowsApps;
F:\vscode\Microsoft VS Code\bin;
C:\Users\steve\AppData\Local\GitHubDesktop\bin;
C:\Users\steve\.dotnet\tools;
F:\gcloud[This is not relevant]

PSMODULEPATH: 
C:\Users\steve\Documents\WindowsPowerShell\Modules;
F:\gcloud\google-cloud-sdk\platform\PowerShell;
C:\Program Files\WindowsPowerShell\Modules;
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: F:\anaconda\condaenv\pyprose\Library\ssl\cacert.pem
```

An update to this issue is that the python version is the correct `Python 3,8,19` version under env `pyprose` on Saturday. This happened directly **on the new system startup without any operation**. Until today, the python called in this env is the desired one. However, before Saturday, a reboot of the system does not result in a correct python version.

Additional info on my system is that I don't have Python installed standalone. After checking all the environment variables, I did not see any path related to python at all. All my Python interpreters are installed with conda. I also have not made any changes to the system since my post. 

I would say this error is "somehow resolved" for now. But if you need any further investigation, I'm happy to provide additional information. Should this version problem happen again, I would also continue posting the issue on this thread.

@jaimergp I don't get any result after running `where python` command.
![image](https://github.com/user-attachments/assets/6579d4ee-76b9-4bc4-8a51-e1d94a2c0996)

**Comment by jaimergp** [comment]
Ah, you are on PowerShell. You might need `where.exe python` or one of the alternatives provided at https://superuser.com/questions/34492/powershell-equivalent-to-the-unix-which-command.
