### ISSUE TITLE
Investigate compatibility with pytest 8.3.1

### ISSUE THREAD

**Issue by jezdez** [conda/conda#14069]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

As @RonnyPfannschmidt [wrote on Mastodon](https://fosstodon.org/@ossronny/112837662322781627?kjy=spring):

> it seems like a recent [#pytest](https://fosstodon.org/tags/pytest) enhancement for detecting virtualenvs causes a [#regression](https://fosstodon.org/tags/regression) as conda ones are no longer accidentally detected (https://github.com/pytest-dev/pytest/issues/12652) is there a easy way to figure if a folder is a conda environment to in-cooperate?

I'm opening this ticket to make sure we're following up to my first response in https://github.com/pytest-dev/pytest/issues/12652#issuecomment-2246274332.

**Comment by jezdez** [comment]
Looking into it, seems like https://github.com/pytest-dev/pytest/issues/12652#issuecomment-2246300732 is the summary. We'll need to prioritize https://github.com/conda/conda/issues/13337 to start retrofitting conda envs with `pyvenv.cfg` files if we want to keep pretending that conda envs are "venvs-in-spirit".

**Comment by RonnyPfannschmidt** [comment]
for pytest i choose to explicitly check for conda environments https://github.com/pytest-dev/pytest/pull/12656 will add support on the mainline and a backport to the 8.3.x branch will be released in a timely manner

thanks for the extra input

**Comment by jezdez** [comment]
This was resolved in https://github.com/pytest-dev/pytest/pull/12656 by detecting conda envs via `<env>/conda-meta/history` until we can merge #13337, at which point the `pyvenv.cfg` would also match.
