### ISSUE TITLE
conda stucks

### ISSUE THREAD

**Issue by MordehayM** [conda/conda#14081]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Trying to do "conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia" or "conda update conda"  but keep getting this:

```
Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
......
```

It's just stuck.

Do you know what I can do?
I have tried to do "conda clear --all", creating a new env, and then installing the package there but I got the same issue

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /home/dsi/mor/.condarc
 populated config files : /home/dsi/mor/.condarc
          conda version : 22.9.0
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=12.0=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dsi/mor/anaconda3-new  (writable)
      conda av data dir : /home/dsi/mor/anaconda3-new/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dsi/moradim/anaconda3-new/pkgs
                          /home/dsi/moradim/.conda/pkgs
       envs directories : /home/dsi/moradim/anaconda3-new/envs
                          /home/dsi/moradim/.conda/envs
               platform : linux-64
```

### Conda Config

```shell
==> /home/dsi/mor/.condarc <==
auto_activate_base: False
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at /home/dsi/mor/anaconda3-new/envs/tryenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.10.14         hd12c33a_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

**Comment by travishathaway** [comment]
@MordehayM,

I recommend updating your conda to latest version. If you are unable to update with `conda update --name base conda`, you try the following:

1. Revert base environment to initial state with: `conda install --rev 0 --name base`
2. Update conda: `conda update --name base conda`

After that, you will have a faster solver that should be able to handle creating the pytorch environment you're trying to create.

Let us know if that helps.

**Comment by MordehayM** [comment]
Almost half an hour passed and I didn't see any output for this command:
conda install --rev 0 --name base

**Comment by MordehayM** [comment]
I did the command, `conda install --rev 0 --name base`, and then update conda but I still have difficult with the following command: 
`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`
Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(538): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(538): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(538): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(538): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: \

**Comment by travishathaway** [comment]
@MordehayM,

Can you please share which version of conda you currently have? I'm wondering if the update ran successfully.

**Comment by MordehayM** [comment]
I see now the version is very old (it wasn't that old before the above commands):
`conda version : 4.14.0`
I tried as you suggested to do this command:
`conda update --name base conda` but I got the same version, this is the output of the commnads:
conda update --name base conda
Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(538): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /home/dsi/moradim/anaconda3-new

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    backports.functools_lru_cache-1.6.4|     pyhd3eb1b0_0           9 KB
    backports.tempfile-1.0     |     pyhd3eb1b0_1          11 KB
    backports.weakref-1.0.post1|             py_1           8 KB
    heapdict-1.0.1             |             py_0           9 KB
    jdcal-1.4.1                |             py_0          11 KB
    jsonschema-3.2.0           |             py_2          47 KB
    path.py-12.5.0             |                0           4 KB
    xmltodict-0.13.0           |   py38h06a4308_0          19 KB
    ------------------------------------------------------------
                                           Total:         121 KB

The following packages will be UPDATED:

  backports.tempfile conda-forge::backports.tempfile-1.0-p~ --> pkgs/main::backports.tempfile-1.0-pyhd3eb1b0_1

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex                                 conda-forge --> pkgs/main
  backports.functoo~ conda-forge::backports.functools_lru_~ --> pkgs/main::backports.functools_lru_cache-1.6.4-pyhd3eb1b0_0
  backports.weakref  conda-forge::backports.weakref-1.0.po~ --> pkgs/main::backports.weakref-1.0.post1-py_1
  heapdict                                      conda-forge --> pkgs/main
  jdcal                                         conda-forge --> pkgs/main
  jsonschema                                    conda-forge --> pkgs/main
  path.py                                       conda-forge --> pkgs/main
  xmltodict          conda-forge/noarch::xmltodict-0.13.0-~ --> pkgs/main/linux-64::xmltodict-0.13.0-py38h06a4308_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
jdcal-1.4.1          | 11 KB     | ################################################################# | 100% 
path.py-12.5.0       | 4 KB      | ################################################################# | 100% 
backports.functools_ | 9 KB      | ################################################################# | 100% 
backports.weakref-1. | 8 KB      | ################################################################# | 100% 
backports.tempfile-1 | 11 KB     | ################################################################# | 100% 
xmltodict-0.13.0     | 19 KB     | ################################################################# | 100% 
heapdict-1.0.1       | 9 KB      | ################################################################# | 100% 
_libgcc_mutex-0.1    | 3 KB      | ################################################################# | 100% 
jsonschema-3.2.0     | 47 KB     | ################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
moradim@dgx03:~/SpeechRepainting$ conda info

     active environment : None
            shell level : 0
       user config file : /home/dsi/moradim/.condarc
 populated config files : /home/dsi/moradim/.condarc
          conda version : 4.14.0

**Comment by travishathaway** [comment]
@MordehayM,

I have another recommendation for. It looks like you are using Anaconda Distribution, so you could also try to update the metapackage it uses. This will also update conda itself.

Here's how to do that:

Revert your environment like before:

```
conda install --rev 0 --name base
```

And then update the anaconda metapackage with the following command:

```
conda update --name base anaconda
```

**Comment by travishathaway** [comment]
@MordehayM,

At this point I would reinstall conda. Please follow the instructions for doing that here:

- https://docs.anaconda.com/reference/troubleshooting/#recovering-your-anaconda-installation

**Comment by travishathaway** [comment]
@MordehayM,

Yes, that's the idea. Once everything is copied over, you will remove the `anaconda_old` folder.

**Comment by hgsgyf175** [comment]
I solved this problem by deleting everything in ~/.condarc and adding these:

channels:
 - bioconda
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
 - https://repo.anaconda.com/pkgs/main
 - https://repo.anaconda.com/pkgs/r
 - conda-forge
show_channel_urls: true

**Comment by GostInShell** [comment]
@MordehayM Hi! I've encountered a similar problem. Could I ask that whether you have tried removing the anaconda_old and is the version correct afterwards? Thank you!

**Comment by MordehayM** [comment]
I don't really remember but I think this was the solution
