### ISSUE TITLE
Option `--platform/--subdir` is not mentioned in documentation

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#14100]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In release `23.10` we added a new `--platform/--subdir` option to the `install` and `create` commands. Unfortunately, this is only mentioned on the command help page (e.g. `conda create --help`). It would be useful for the conda documentation to have examples of how this is used.

I recommend adding the following to the documentation:

- Add a new section to [Managing environments](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-environments.html) called, "Create an environment with a different platform"
- More?

### Additional Context

The following pull request contains a great description of why this was necessary and how it works:

- https://github.com/conda/conda/pull/11794

The following release notes also mention this option:

- https://github.com/conda/conda/releases/tag/23.10.0

**Comment by jaimergp** [comment]
Opened https://github.com/conda/conda/pull/14181
