### ISSUE TITLE
sqlite3 is built without readline support

### ISSUE THREAD

**Issue by ncoghlan** [conda/conda#1411]
Helping out at a Software Carpentry bootcamp last week, several attendees encountered problems with up-arrow not working at the sqlite3 prompt.

In at least one case, this appears to have been due to the conda provided sqlite3 being built without readline support.

(Filing this against the base conda project as sqlite3 doesn't appear to be part of conda-recipes)

**Comment by asmeurer** [comment]
Issues like this are better suited to https://github.com/continuumio/anaconda-issues/issues

**Comment by ncoghlan** [comment]
Thanks. Turns out this was already reported, but as a Mac OS X specific issue: https://github.com/ContinuumIO/anaconda-issues/issues/307

I've commented there.
