### ISSUE TITLE
Anaconda installer `.bashrc` modifications cannot be easily reversed

### ISSUE THREAD

**Issue by ncoghlan** [conda/conda#1412]
(Filing against conda as I can't find a public issue tracker for the Anaconda installer)

In helping out an attendee at a Software Carpentry bootcamp that had run into issue #1411, I found that Anaconda had added a line to the end of the attendee's `.bashrc` file that placed Anaconda's `bin` directory at the head of `PATH`. This meant that *all* affected commands were shadowed in *every* terminal session, in a way that *couldn't* be easily reverted via:

    source `which deactivate`

The additions to the user's shell config when they instruct the installer to enable the use of Anaconda by default should either:

1. Activate the main environment properly so that it can be deactivated as needed (currently attempting to deactivate claims that it isn't activated); or
2. Be more selective about which binary commands `conda` shadows, since losing access to the system versions without manually editing PATH can pose a significant problem, especially when there's a problem with the way the conda provided version is built (as appears to be the case in #1411)

**Comment by asmeurer** [comment]
The current behavior is intended. We don't want users to type `source deactivate` when no environment is active and have `conda`, `activate`, and `deactivate` all removed from their PATH. 

If you want to use a system command, the easiest way is to use the full path to it (like `/usr/bin/python`).

By the way, source \`which deactivate\` is redundant. `source` already searches the PATH when given a command.

**Comment by ncoghlan** [comment]
Thanks for the clarification. I've refiled this as https://github.com/ContinuumIO/anaconda-issues/issues/372 specifically requesting that Anaconda be more selective in which system commands it overrides when there's no conda environment active.
