### ISSUE TITLE
Spyder cannot set the expected configuration according to the turtle.cfg configuration file of Turtle

### ISSUE THREAD

**Issue by Wangsutan** [conda/conda#14136]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

# Spyder cannot set the expected configuration according to the turtle.cfg configuration file of Turtle

The test code `main.py` is as follows:

```python
import turtle
import pkgutil

print(pkgutil.get_loader('turtle').get_filename())

turtle.fd(100)
turtle.done()
```

The `turtle.cfg` configuration file in the same folder is as follows:

```ini
shape = turtle
```

In the same path as the used `Turtle` library `/home/wst/anaconda3/lib/python3.11`, create a `turtle.cfg` configuration file as follows:

```ini
shape = circle
```

Run the program through the terminal of Manjaro, and the shape of turtle is as expected: the configuration of the configuration file in the path where the script `main.py` is located overrides the configuration of the configuration file in the path where the `Turtle` library is located. The run result is as follows:

```
python main.py
/home/wst/anaconda3/lib/python3.11/turtle.py
```

![Screenshot_20240808_124556](https://github.com/user-attachments/assets/7ff2243c-4f74-4b5a-839f-255d2fef3f46)

However, in the same code and configuration, running the related code through Spyder gives the turtle shape `circle`.

```
runfile('/home/wst/Desktop/cfg_test/main.py', wdir='/home/wst/Desktop/cfg_test')
/home/wst/anaconda3/lib/python3.11/turtle.py
```

![Screenshot_20240808_125103](https://github.com/user-attachments/assets/cb6e98ea-71a7-426b-96f9-8e68c6b5dca6)

---

My operating system information is as follows:

```
screenfetch

 ██████████████████  ████████     wst@wst-h310ms220
 ██████████████████  ████████     OS: Manjaro 24.0.5 Wynsdey
 ██████████████████  ████████     Kernel: x86_64 Linux 6.9.10-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 1h 23m
 ████████            ████████     Packages: 1782
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Disk: 116G / 558G (22%)
 ████████  ████████  ████████     CPU: Intel Core i3-8100 @ 4x 3.6GHz [40.0°C]
 ████████  ████████  ████████     GPU: NVIDIA GeForce GTX 960M
                                  RAM: 4517MiB / 15937MiB
```

The relevant software versions are as follows:

```
conda: 24.7.1
Python: 3.11.9
Spyder IDE: 5.5.1
```

I use the default Anaconda environment.

**Comment by travishathaway** [comment]
@Wangsutan,

This is not the correct project for this issue. Please file it with the Spyder project:

- https://github.com/spyder-ide/spyder
