### ISSUE TITLE
Unexpected error updating r packages

### ISSUE THREAD

**Issue by kriehl** [conda/conda#1413]
(topik)0106-kriehl:topik kriehl$ conda env update -n topik
Fetching package metadata: ........
Solving package specifications: ...........................Fetching packages ...
libxml2-2.9.2- 100% |####################################################################################################################| Time: 0:00:01   1.23 MB/s
r-base-3.2.0-0 100% |####################################################################################################################| Time: 0:00:17   1.24 MB/s
h5py-2.5.0-np1 100% |####################################################################################################################| Time: 0:00:00   1.25 MB/s
bokeh-0.9.1-np 100% |####################################################################################################################| Time: 0:00:13   1.18 MB/s
r-3.2.0-0.tar. 100% |####################################################################################################################| Time: 0:00:00 579.47 kB/s
r-boot-1.3_17- 100% |####################################################################################################################| Time: 0:00:00   1.26 MB/s
r-chron-2.3_47 100% |####################################################################################################################| Time: 0:00:00   1.37 MB/s
r-cluster-2.0. 100% |####################################################################################################################| Time: 0:00:00   1.16 MB/s
r-codetools-0. 100% |####################################################################################################################| Time: 0:00:00   1.63 MB/s
r-foreign-0.8_ 100% |####################################################################################################################| Time: 0:00:00   1.27 MB/s
r-kernsmooth-2 100% |####################################################################################################################| Time: 0:00:00   1.27 MB/s
r-lattice-0.20 100% |####################################################################################################################| Time: 0:00:00   1.25 MB/s
r-mass-7.3_42- 100% |####################################################################################################################| Time: 0:00:00   1.25 MB/s
r-nnet-7.3_9-r 100% |####################################################################################################################| Time: 0:00:00   1.43 MB/s
r-rcpp-0.11.6- 100% |####################################################################################################################| Time: 0:00:01   1.23 MB/s
r-rpart-4.1_9- 100% |####################################################################################################################| Time: 0:00:00   1.24 MB/s
r-spatial-7.3_ 100% |####################################################################################################################| Time: 0:00:00   1.35 MB/s
r-survival-2.3 100% |####################################################################################################################| Time: 0:00:03   1.22 MB/s
r-class-7.3_13 100% |####################################################################################################################| Time: 0:00:00   1.37 MB/s
r-matrix-1.2_1 100% |####################################################################################################################| Time: 0:00:02   1.16 MB/s
r-nlme-3.1_121 100% |####################################################################################################################| Time: 0:00:01   1.24 MB/s
r-mgcv-1.8_6-r 100% |####################################################################################################################| Time: 0:00:01   1.25 MB/s
r-data.table-1 100% |####################################################################################################################| Time: 0:00:00   1.21 MB/s
r-recommended- 100% |####################################################################################################################| Time: 0:00:00 605.10 kB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the#####################################                                                            |  56%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/kriehl/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 63, in main
    return args_func(args, parser)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 101, in execute
    installer.install(prefix, specs, args, env)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 21, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/kriehl/anaconda/lib/python2.7/site-packages/conda/install.py", line 598, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Users/kriehl/anaconda/envs/topik/conda-meta/r-mass-7.3_40-0.json'

(topik)0106-kriehl:topik kriehl$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.14.1
  conda-build version : 1.10.2
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/kriehl/anaconda  (writable)
  default environment : /Users/kriehl/anaconda/envs/topik
     envs directories : /Users/kriehl/anaconda/envs
        package cache : /Users/kriehl/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
This was an issue with some of the r packages, which should be fixed in the latest versions. You may need to recreate your environment, which should be easy since you are using conda-env.
