### ISSUE TITLE
macos codesign mixup

### ISSUE THREAD

**Issue by Anton-4** [conda/conda#14151]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`anaconda3/bin` contains `codesign`, in the installation, this folder is prepended to the PATH. The widely used macOS xcode command line tools also have an application called codesign. Because anaconda puts its folder first in the PATH, this means that anaconda's codesign will be used any time a user or program calls codesign while they probably intended to use the xcode codesign.

### Why is this needed?

To prevent bugs, confusion, and time spent investigating this mixup.

### What should happen?

From my limited context I recommend renaming anaconda's codesign.

**Comment by travishathaway** [comment]
@Anton-4,

Unfortunately, this is isn't the correct spot for submitting this feature request. We do not have any say with what goes into the Anaconda Distribution. You can reach out to those responsible for managing Anaconda Distribution via the resources listed below:

- [Anaconda community forums](https://community.anaconda.cloud)
- [Anaconda issue tracker on GitHub](https://github.com/ContinuumIO/anaconda-issues/issues)

I'm going to be closing this as "off-topic" for now.
