### ISSUE TITLE
Problem updating conda and anaconda

### ISSUE THREAD

**Issue by bootkey781** [conda/conda#1415]
I encountered the following error when trying to update conda and anaconda:

Warning: could not import binstar_client (failed to parse CPython sys.version: '2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34) \n[GCC 4.2.1 (Apple Inc. build 5577)]')Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

I've attached screen shots of the traceback and of the conda info command.

![image](https://cloud.githubusercontent.com/assets/1548382/8537227/331a5b38-2419-11e5-8c9f-6a713144cb2d.png)

![image](https://cloud.githubusercontent.com/assets/1548382/8537237/4db0eb6a-2419-11e5-8c3f-f451156a2e86.png)

**Comment by ilanschnell** [comment]
I believe the images, were not attached correctly.  All I see are large PNG icons.

**Comment by bootkey781** [comment]
Sorry about the missing screen shots.  

![conda_info](https://cloud.githubusercontent.com/assets/1548382/8548232/d1a8ae78-2480-11e5-9e99-ef824ba4961f.png)
![conda_update_traceback](https://cloud.githubusercontent.com/assets/1548382/8548231/d1a888bc-2480-11e5-8981-b9a2d219e784.png)

**Comment by ilanschnell** [comment]
Somehow the Anaconda Python is interacting strangely with the Framework Python (in `/Library/Frameworks/Python.framework`).  This could be the result of having some special environment variables set.  What is the output of:
```
$ env | sort
```
?

**Comment by bootkey781** [comment]
I've attached the results of $ env | sort > env_sort.txt

On Tue, Jul 7, 2015 at 8:25 AM, Ilan Schnell <notifications@github.com>
wrote:

> Somehow the Anaconda Python is interacting strangely with the Framework
> Python (in /Library/Frameworks/Python.framework). This could be the
> result of having some special environment variables set. What is the output
> of:
>
> $ env | sort
>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1415#issuecomment-119220677>.
>



-- 
Please reply to: bootkey@gmail.com

Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Zh8SGTYwkF/Render
CLASSPATH=/Users/jacook/atomic-scala/
DISPLAY=/private/tmp/com.apple.launchd.9pzJ3G803m/org.macosforge.xquartz:0
GIT_PS1_SHOWDIRTYSTATE=1
GOPATH=/Users/jacook/go
GOROOT=/usr/local/go
HOME=/Users/jacook
LANG=en_US.UTF-8
LOGNAME=jacook
OLDPWD=/Users/jacook/.astropy
PATH=/Users/jacook/Scala/bin/:/Users/jacook/anaconda/bin:/usr/local/git/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/Users/jacook/go/bin:/Users/jacook/bin
PS1=\[\033[0;35m\]\u\[\033[0;32m\]$(__git_ps1)\[\033[0;34m\] \W $ \[\033[0m\]
PWD=/Users/jacook
PYTHONPATH=/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
PYTHONSTARTUP=/Users/jacook/_py/pythonstartup.py
SECURITYSESSIONID=186a6
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.IPkOyQsQeh/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=C975D6C5-D8F6-4D93-88C8-0971F535D5F7
TMPDIR=/var/folders/k8/p5ltlrk567bfqhsq518sw2cm0000gn/T/
USER=jacook
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0

**Comment by ilanschnell** [comment]
The problem is the `PYTHONPATH` environment variable.  Try:
```
unset PYTHONPATH
```
and run the update command again.

**Comment by bootkey781** [comment]
Thanks, the "conda update conda" and "conda update anaconda" commands were
successful after unsetting PYTHONPATH. Is there a way to "pip install
pygame" into the anaconda environment?

On Tue, Jul 7, 2015 at 3:59 PM, Ilan Schnell <notifications@github.com>
wrote:

> The problem is the PYTHONPATH environment variable. Try:
>
> unset PYTHONPATH
>
> and run the update command again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1415#issuecomment-119356591>.
>



-- 
Please reply to: bootkey@gmail.com
