### ISSUE TITLE
"conda update spyder" fails

### ISSUE THREAD

**Issue by redlus** [conda/conda#1416]
My spyder 2.3.4 has broken, and is hung upon every restart of the app.
I've tried to update it using "conda update spyder", but I get the following exception:

> Traceback (most recent call last):
>  File "C:\Miniconda3\Scripts\conda-script.py", line 4, in <module>
>    sys.exit(main())
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in main
>    args_func(args, p)
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 207, in args_func
>    args.func(args, p)
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 40, in execute
>    install.install(args, parser, 'update')
>  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 400, in install
>    if not pscheck.main(args):
>  File "C:\Miniconda3\lib\site-packages\conda\cli\pscheck.py", line 66, in main
>    while not check_processes():
>  File "C:\Miniconda3\lib\site-packages\conda\cli\pscheck.py", line 33, in check_processes
>    for n in psutil.get_pid_list():
> AttributeError: 'module' object has no attribute 'get_pid_list'

"conda info" returns the following:

> Current conda install:
> 
> ```
>         platform : win-64
>    conda version : 3.9.0
> ```
> 
>  conda-build version : not installed
>       python version : 3.3.3.final.0
>     requests version : 2.5.1
>     root environment : C:\Miniconda3  (writable)
>  default environment : C:\Miniconda3\envs\py34
>     envs directories : C:\Miniconda3\envs
>        package cache : C:\Miniconda3\pkgs
>         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
>                        http://repo.continuum.io/pkgs/free/noarch/
>                        http://repo.continuum.io/pkgs/pro/win-64/
>                        http://repo.continuum.io/pkgs/pro/noarch/
>          config file : None
>    is foreign system : False

Any idea what the problem is?

**Comment by ccordoba12** [comment]
Please try:

    conda install -f psutil

then

    conda update conda

and finally

    conda update spyder

to see if that helps

**Comment by redlus** [comment]
"conda install -f psutil" throws the same exception:
>Traceback (most recent call last):
>  File "C:\Miniconda3\Scripts\conda-script.py", line 4, in <module>
>    sys.exit(main())
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in main
>    args_func(args, p)
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 207, in args_func
>    args.func(args, p)
>  File "C:\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 46, in execute
>    install.install(args, parser, 'install')
>  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 400, in install
>    if not pscheck.main(args):
>  File "C:\Miniconda3\lib\site-packages\conda\cli\pscheck.py", line 66, in main
>    while not check_processes():
>  File "C:\Miniconda3\lib\site-packages\conda\cli\pscheck.py", line 33, in check_processes
>    for n in psutil.get_pid_list():
>AttributeError: 'module' object has no attribute 'get_pid_list'

The same goes for "conda install psutil" and "conda update psutil".

**Comment by asmeurer** [comment]
Can you run `conda update -f conda`?

**Comment by msarahan** [comment]
I have bumped into this as well, but for me, the issue cropped up when running conda build.

 - conda 3.15.1, py27
 - psutil 3.1.1, py27

If I manually import psutil in IPython, the get_pid_list function indeed does not exist.  There is instead a pids function that is perhaps what you want?  Shall I do a quick PR for conda-build's windows.py, or is there a better place to fix this?

**Comment by asmeurer** [comment]
`conda update conda --force-pscheck` I believe would also fix this. pscheck has been removed from conda as of version 3.15.0.

**Comment by DawoodChanti** [comment]
pip install --upgrade spyder

will do the work
