### ISSUE TITLE
Do not populate `channels` (or `defaults`) by default

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#14178]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`conda` should not hardcode `defaults` to `repo.anaconda.com/pkgs/*`. It should leave this field blank and error out if not configured. `conda` _distributions_ (e.g. constructor-made installers) should provide this configuration themselves (like Miniforge does).

We should start warning folks in case they are packaging their own conda installer. And then error out.

### Why is this needed?

As an open-source project, it should not rely _implicitly_ on maybe-paid services that have TOS.

### What should happen?

* The first deprecation phase would warn users that they are using the hardcoded default (as in the `conda` source code), and that in the future this will cause an error. The warning can be removed if they configure `conda` accordingly
  * The warning will ask users to run `conda config --append channels XXX` with `XXX` being their choice (e.g. `defaults` or `conda-forge`; `XXX` should probably be the name of the channel that shipped their `conda` artifact locally), and that can be the original suggestion.
* Once we fully deprecated, the `channels` setting will have no default value.
  * new installations will ship a `condarc` file with the right `channels` configuration for each distributor (`defaults` for Miniconda, `conda-forge` for Miniforge)
  * existing ones will have the same `conda config` suggestion

### Additional Context

This has come up after trying to come up with solutions for #14176

Also: `defaults` as a name and concept it's a bad idea, imo. People use it to refer to the Anaconda commercial channels, but it can technically be anything. The UI should simply mark the channel as default with `*` or `(D)` or something, but not RENAME it completely! We might need to talk about deprecation of this concept in a separate issue.

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

Didn't see this one before. Appreciate you writing up

Is there any risk users would encounter no channels being set? IOW is there a possibility they would see an error message to start? Or can we sufficiently avoid that possibility by baking preconfigured channels into installers and the like?

Just worry a little that users would see a confusing error message about channels and walk away. Though maybe I'm worrying too much 😅

**Comment by jaimergp** [comment]
The error message I'm envisioning is at the CLI level, and would inform folks to run `conda config --append channels XXX` very nicely. But in principle distributions like Miniforge or Miniconda would have populated `$PREFIX/condarc` with their default value.

Note that these days you can run conda-libmamba-solver without channels and it errors out (more or less) nicely if nothing's found on the cache.

**Comment by jezdez** [comment]
Just wanted to note that I've seen this, and that in the short-term resolving https://github.com/conda/conda/issues/14176 is preferable. Doesn't take away the value of this ticket of course.

**Comment by jaimergp** [comment]
Agreed. Both suggestions complement each other nicely. This ticket wouldn't prevent folks from adding `-c defaults` by accident in CLI or something; it would just avoid the https://github.com/conda/conda/issues/12356 footgun and force installers to make a decision explicitly (looking at `constructor` users).

**Comment by jakirkham** [comment]
Just for my 2 cents, I don't want to deny users the opportunity to use `defaults`. It is a great service with a lot of work going into it

Would merely like to make sure users know when they are making that choice (as opposed to it happening as a side-effect under-the-hood)

It's awkward for users if they think they did one thing (and something else is actually happening unbeknownst to them)
