### ISSUE TITLE
Raise error if attempting to remove a non-conda env path

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#14174]
> shouldn't attempting to remove a non-existent env fail? currently it silently succeeds which is confusing:
> <img width="805" alt="Screenshot 2024-08-23 at 15 34 57" src="https://github.com/user-attachments/assets/03d5d697-4e16-4272-850d-8ec72f8b2c1c">

_Originally posted by @kenodegard in https://github.com/conda/conda/pull/14173#discussion_r1729489413_

**Comment by beeankha** [comment]
The plot thickens... [this issue from 2016](https://github.com/conda/conda/issues/3489) was filed specifically to _remove_ the error output when attempting to remove a non-existent env. There is even a [regression test](https://github.com/conda/conda/blob/main/tests/test_create.py#L2306-L2310) for it. Adding the "pending discussion" label to this issue.
