### ISSUE TITLE
"conda install opencv" fails on Windows 64-bit (Win 8.1)

### ISSUE THREAD

**Issue by prjemian** [conda/conda#1419]
Same problem as #1417.  See comment entered after previous issue was closed.

**Comment by soapy1** [comment]
@prjemian is this still an issue for you?

**Comment by prjemian** [comment]
Things have changed and opencv is not in the supply stream now.  The OS has been upgraded to Win 10, as well.

	PS C:\Users\Pete> conda install opencv
	Fetching package metadata .........
	Solving package specifications: .


	PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
	  - opencv

	You can search for packages on anaconda.org with

	    anaconda search -t conda opencv

	PS C:\Users\Pete> conda --version
	conda 4.2.12
