### ISSUE TITLE
Pre- and post command plugin hooks not working for env activation and deactivation

### ISSUE THREAD

**Issue by jezdez** [conda/conda#14211]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While working on anaconda-anon-usage, I've noticed that we've never implemented pre- and post-command plugin invocation for the activation and deactivation of conda environments, due to the way they are currently handled outside the regular CLI system.

I'd guess we maybe should also add a bit of extra error handling to prevent the plugins from stopping the environment activation?

**Comment by kenodegard** [comment]
> I'd guess we maybe should also add a bit of extra error handling to prevent the plugins from stopping the environment activation?

Idk, I can see valid arguments either way. It makes sense to treat pre/post as "optional" that only warn on failures but it also makes sense for them to raise errors that prevent activation. I think I'm in favor of letting the plugins decide this just as we do for the other subcommands.
