### ISSUE TITLE
Issues from a conda discussion on Hacker News

### ISSUE THREAD

**Issue by cowlicks** [conda/conda#1424]
From here: https://news.ycombinator.com/item?id=9861234

Agreed (although biased since I used to work at Continuum.) I am wondering what others think of conda?
- We have used Conda for our first python deployment and the process has been seamless. It provides the same sandboxing concept using virtualenvs and also uses prebuilt binaries for native dependencies so you don't have to build them every time. The only drawback I would say is that we have to install miniconda in our production servers rather than just deploying an standalone package.
-  My team has been rolling our own conda packages for (frequent) internal software releases to local servers and have been pretty happy overall pulling down code from a locally managed conda package repo.
  With that said, Conda is not a perfect solution. One thing that can be frustrating is that a package can include compiled code (shared objects/dylibs) that may be incompatible with your system. Unfortunately, while you can indicate dependencies on other conda packages, python versions, etc there isn't currently a convenient way to indicate things like GLIBC dependencies.

**Comment by ccordoba12** [comment]
My comments:

> The only drawback I would say is that we have to install miniconda in our production servers rather than just deploying an standalone package.

I don't know how that could change, unless pip would accept conda packages as wheels, or something like that.

> Unfortunately, while you can indicate dependencies on other conda packages, python versions, etc there isn't currently a convenient way to indicate things like GLIBC dependencies

I can't see how that could be solved. If I understand things correctly, it's not possible to make glibc relocatable, so there won't be a conda package for it.
