### ISSUE TITLE
conda pipbuild error

### ISSUE THREAD

**Issue by ericmjl** [conda/conda#1425]
Hey guys, I know conda pipbuild is experimental, but I thought I'd like to report this error. Hopefully it's reproducible.

	$ conda pipbuild hiveplot --binstar-upload
	Fetching package metadata: ......
	Creating standard recipe for hiveplot-0.1.7.4
	An unexpected error has occurred, please consider sending the
	following traceback to the conda GitHub issue tracker at:

	    https://github.com/conda/conda-build/issues

	Include the output of the command 'conda info' in your report.

	Traceback (most recent call last):
	  File "/Users/ericmjl/anaconda/bin/conda-pipbuild", line 5, in <module>
	    sys.exit(main())
	  File "/Users/ericmjl/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 77, in main
	    args_func(args, p)
	  File "/Users/ericmjl/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 312, in args_func
	    args.func(args, p)
	  File "/Users/ericmjl/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 350, in execute
	    build_package(package, version)
	  File "/Users/ericmjl/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 300, in build_package
	    directory = build_recipe(package, version=version)
	  File "/Users/ericmjl/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 161, in build_recipe
	    output = result.strip().split('\n')
	TypeError: 'str' does not support the buffer interface

Conda Info:

	Current conda install:

	             platform : osx-64
	        conda version : 3.14.1
	  conda-build version : 1.10.2
	       python version : 3.4.3.final.0
	     requests version : 2.7.0
	     root environment : /Users/ericmjl/anaconda  (writable)
	  default environment : /Users/ericmjl/anaconda
	     envs directories : /Users/ericmjl/anaconda/envs
	        package cache : /Users/ericmjl/anaconda/pkgs
	         channel URLs : https://conda.binstar.org/t/<TOKEN>/ericmjl/osx-64/
	                        https://conda.binstar.org/t/<TOKEN>/ericmjl/noarch/
	                        https://repo.continuum.io/pkgs/free/osx-64/
	                        https://repo.continuum.io/pkgs/free/noarch/
	                        https://repo.continuum.io/pkgs/pro/osx-64/
	                        https://repo.continuum.io/pkgs/pro/noarch/
	          config file : /Users/ericmjl/.condarc
	    is foreign system : False

**Comment by jakirkham** [comment]
Yes, was able to reproduce using a miniconda3 environment. The problem here is a mix of `str` (unicode) and `byte` types.

The issue here can be reproduced in a much simpler context (code in Python 3).

    >>> b"sdkfasdkfjasld\nasdsadfasdf          ".strip().split('\n')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'str' does not support the buffer interface

This could be resolved by doing the following in Python 3.

    >>> b"sdkfasdkfjasld\nasdsadfasdf          ".strip().split(b'\n')
    [b'sdkfasdkfjasld', b'asdsadfasdf']

However, a fix for both 2 and 3 would be better. This can be done easily as so.

    >>> b"sdkfasdkfjasld\nasdsadfasdf          ".strip().splitlines()
    [b'sdkfasdkfjasld', b'asdsadfasdf']

**Comment by jakirkham** [comment]
I should add this is not an issue with [conda]( https://github.com/conda/conda ), but with [conda-build]( https://github.com/conda/conda-build ), which contains all of the building capabilities.

**Comment by ericmjl** [comment]
Oh, I see! Shall I cross-report it there then?

**Comment by jakirkham** [comment]
@ericmjl, I wouldn't worry about it. I put the PR against the right repo. Hopefully, that will be enough. Besides some of the same issues show up in `conda` proper, for which I have also offered fixes.
