### ISSUE TITLE
Re-activate the classic solver for pull requests

### ISSUE THREAD

**Issue by zklaus** [conda/conda#14264]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In https://github.com/conda/conda/pull/13694, we deactivated the classic solver for PRs. This saves a good amount of resources during development, but it also means that some test failures can slip past the checks pre-merge, as evidenced, e.g. in https://github.com/conda/conda/pull/13880.

To mitigate this, we could find a compromise, such as activating the classic solvers for a subset of test even in the PR checks.

Since the main bottleneck seems to be the large repodata that is associated with the conda-forge channel, activating the classic solver for the defaults channel might represent a good compromise.

**Comment by jezdez** [comment]
I agree we should enable the classic solver on Linux, for the latest supported Python version to have some coverage.
