### ISSUE TITLE
Creating a virtual environment starting with '.' (dot/period)

### ISSUE THREAD

**Issue by joelostblom** [conda/conda#1427]
Hi,
Is there any way to create a virtual environment that starts with a '.' (dot/period)? I am running a program that searches for virtual python environments in a specific dot-prefixed folder name. The developers for that software use `virtualenv`  for their environment, but I would like to keep using conda and was wondering if there is a workaround for this.

Cheers

**Comment by kalefranz** [comment]
What error do you get? I didn't know there was a restriction.

**Comment by kalefranz** [comment]
Ah, it looks like we do indeed restrict it.

```
kfranz@0283:~/continuum/conda *test-requests ❯ python -m conda create -n .someenv

CondaValueError: environment name cannot start with '.': .someenv
```

**Comment by kalefranz** [comment]
I've traced that restriction down to b9f5528c1399612f8513b81eb432af0e3fd8c186.  I also don't understand the technical reason it was implemented.  The commit author also didn't remember much context.

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda/pull/5284

**Comment by joelostblom** [comment]
Great thank you!
I am not any longer using the program that was creating the virtual environments prefixed with a period, but it is good to know that this is fixed!
