### ISSUE TITLE
missing windows magic

### ISSUE THREAD

**Issue by mmckerns** [conda/conda#1428]
I gave `conda` a try for testing on windows.  I found that with the install of miniconda 3.10.1 (64-bit), there were a few things that had to be manually patched so stuff worked as expected.

If you want to run python from the command line:
- associate .py file with conda's python.exe

Not sure if `conda` could or should assume that's what you want.  I think probably.

The bigger issue is that there was some command line magic missing from the registry keys.
These two registry entries needed editing with regedit:
- HKEY_CLASSES_ROOT\Applications\python27.exe\shell\open\command
- HKEY_CLASSES_ROOT\py_auto_file\shell\open\command

Each key needed a `%*` to be added to the end of the existing command string -- otherwise conda python ignores all but the first command line argument.

**Comment by kalefranz** [comment]
Closing, because I think we've incorporated most of this into the installers by now, or at least thought a lot about it and made a tradeoff not to (if we decided not to). Tagging @mingwandroid just to be aware of this ticket.
