### ISSUE TITLE
Windows Msysgit Bash shell cannot run conda's activate.bat.

### ISSUE THREAD

**Issue by AnneTheAgile** [conda/conda#1429]
due to an upstream issue [1], the windows bash shell (which comes with git for windows) cannot run activate. Is there an easy workaround? (Maybe not and we should close this, but I wanted to be sure to ask.)
thank you!
AnneTheAgile

Update; One answer to my question is to use another terminal, eg 
4.[] ; ; ; ; ; ; ; ; ; ; ; ; ; ;  X.ConEmu - Handy Windows Terminal
http://conemu.github.io/

1.[] ; ; ; ; ; ; ; ; ; ; ; ; ; ;  X.MinGW - Minimalist GNU for Windows / Issues / #1902 Add ability to execute .bat files from an MSYS shell
http://sourceforge.net/p/mingw/bugs/1902/
2.[] ; ; ;Could we please add .bat program support to Git Bash ; ; ; ; ; ; ; ; ; ; ;  X.Git Bash can't run .bat programs · Issue #101 · msysgit/msysgit
https://github.com/msysgit/msysgit/issues/101 
3.Conda now has activate and deactivate scripts on Windows.  ; ; ;  X.Environment activate script for Windows · Issue #118 · conda/conda
https://github.com/conda/conda/issues/118

**Comment by mikofski** [comment]
I tried to copy the bash activate and deactivate shell scripts to my Anaconda/Miniconda root Python scripts folder and save them as activate.sh and deactivate.sh. Then find this line in activate:

    export CONDA_DEFAULT_ENV="$(echo ${firstpath} | sed "s|/bin$||")" &>/dev/null

and replace `bin` with `Scripts`

    export CONDA_DEFAULT_ENV="$(echo ${firstpath} | sed "s|/Scripts$||")" &>/dev/null

Then from msysgit or msys or msys2 I tried

    source full/path/to/activate.sh <root or other env>

but that calls `conda.cli.main`, `activate` and `common` which all also have `bin` hardcoded as the `Scripts` folder. Evidently there is a parallel code base for *nix vs windows, and not wanting to go down a rabbit hole, I'm stopping here and applying a +1 to this issue as I think it would be very useful to be able to use conda from msysgit, msys and msys2.

**Comment by mingwandroid** [comment]
I've been looking at this recently, I will keep you updated when I make more progress.

**Comment by mikofski** [comment]
Thanks @mingwandroid - are you planning on uniting both Windows and *Nix together into the `conda.cli.main`, `conda.cli.activate` and `conda.cli.common` modules? Is it enough to check `sys.platform` and decide if the location of executables should be `bin` or `scripts`? Isn't there a value for this already in `sys`? Seems like hardcoding `bin` into `conda.cli` is the problem. Also I wonder if it isn't a headache to have to manage separate codebases for Windows and *Nix or perhaps it's just not possible to unite them. Sorry for noobiness, just my 2&cent;

**Comment by msarahan** [comment]
Conda PR #1727 included a lot of work to make this happen.  The master branch or the 4.1 pre-release should work.  @mingwandroid is making it better, but our test suite passed with the merge of #1727.  There is logic in there to figure out which paths to use and how to behave regarding slashes and path joins, depending on which shell is found to be the parent process.

**Comment by klvbdmh** [comment]
Is there any progress on this fix?

**Comment by kalefranz** [comment]
Shouldn't this be fixed and closed? @mingwandroid @msarahan

**Comment by mingwandroid** [comment]
Running a batch file from a bash prompt is not something I would recommend. As the bash environment does not get modified appropriately (a new Windows cmd processor shell is created and the environmental changes vanish when it exits).

For bash, I would rather use the shell scripts. I think most things work, but I have seen a weird thing where the activate shell script ends up sourcing itself and that's does not end well.

So I'd rather this was kept open but the title changed to something like: "Fix activate shell script issues with MSYS2 bash"

**Comment by mikofski** [comment]
I honestly haven't tried it (using `source activate.sh` from msys2) since I last commented on this issue. Although it might be a nice feature to have (ability to use Anaconda/Miniconda within msys), I don't really need it. Instead I just use the CMD shell with Anaconda/Miniconda, and keep it all MS Windows, and that works fine.

**Comment by kalefranz** [comment]
conda 4.4 will have full testing for activate with msys2 bash
