### ISSUE TITLE
--json flag broken by warnings issued to stdout

### ISSUE THREAD

**Issue by bdice** [conda/conda#14294]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I use `conda create` with the flags `--json --dry-run` and parse the JSON results to assess whether an environment is solvable, and what packages would go into it.

Example command:
```
conda create -n rapids-24.10 -c rapidsai-nightly -c conda-forge -c nvidia rapids=24.10 python=3.11 cuda-version=12.0 --dry-run --json
```

Recently I noticed that the JSON formatting is broken by a warning message issued to stdout:

```
==> WARNING: A newer version of conda exists. <==
    current version: 24.9.0
    latest version: 24.9.1

Please update conda by running

    $ conda update -n base -c conda-forge conda
```

I can pass `--quiet` to make this warning go away, so that the result is valid JSON. However, this seems like unintentional behavior from conda. The docs from `conda create --help` say:
```
--json                Report all output as json. Suitable for using conda programmatically.
```

To be programmatically usable, no warnings should be issued via stdout when `--json` is provided. The warnings should either be embedded in the JSON output, be silenced, or possibly go to stderr.

xref: https://github.com/rapidsai/integration/pull/729

**Comment by tdhock** [comment]
I'm having the same issue, https://github.com/necaris/conda.el/issues/163
it would be great if those warnings could be moved to stderr, is that possible please?

**Comment by bdice** [comment]
Oops. I found that there my environment has a wrapper command around `conda` and this warning _IS_ going to stderr instead of stdout -- it's just that this wrapper command is piping `2>&1`. I apologize, this is invalid.

```bash
$ conda create -n rapids-24.10 -c rapidsai-nightly -c conda-forge -c nvidia rapids=24.10 python=3.11 cuda-version=12.0 --dry-run --json 2> err 1> out
$ cat err


==> WARNING: A newer version of conda exists. <==
    current version: 24.7.1
    latest version: 24.9.1

Please update conda by running

    $ conda update -n base -c conda-forge conda


$ cat out
{
  "actions": {
...
```

**Comment by bdice** [comment]
However, perhaps the `--json` flag should still silence this warning instead of sending it to stderr. If others think that is appropriate, this issue could be reopened.
