### ISSUE TITLE
conda install cudatoolkit windows error

### ISSUE THREAD

**Issue by wybert** [conda/conda#1430]
C:\Users\pig>conda install cudatoolkit
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment D:\Anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| cudatoolkit-6.0 | p0       172.1 MB |

The following NEW packages will be INSTALLED:

```
cudatoolkit: 6.0-p0
```

The following packages will be UPDATED:

```
conda:       3.10.0-py27_0 --> 3.14.1-py27_0
conda-env:   2.1.3-py27_0  --> 2.3.0-py27_0
pip:         6.0.8-py27_0  --> 7.1.0-py27_0
pyyaml:      3.11-py27_0   --> 3.11-py27_1
requests:    2.6.0-py27_0  --> 2.7.0-py27_0
setuptools:  14.3-py27_0   --> 18.0.1-py27_0
```

Proceed ([y]/n)? y

Fetching packages ...
cudatoolkit-6. 100% |###############################| Time: 1:09:56  42.99 kB/s
cudatoolkit-6. 100% |###############################| Time: 1:27:30  34.37 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  16%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func

```
args.func(args, p)
```

  File "D:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in instal
l
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Anaconda\lib\site-packages\conda\plan.py", line 502, in execute_actio
ns
    inst.execute_instructions(plan, index, verbose)
  File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 140, in execu
te_instructions
    cmd(state, arg)
  File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 88, in UNLINK
_CMD
    install.unlink(state['prefix'], arg)
  File "D:\Anaconda\lib\site-packages\conda\install.py", line 613, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] : 'D:\Anaconda\conda-meta\conda-3.10.0-py27_0.json'

C:\Users\pig>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.10.0
```

  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : D:\Anaconda  (writable)
  default environment : D:\Anaconda
     envs directories : D:\Anaconda\envs
        package cache : D:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by wybert** [comment]
same error when i install other package like blaze...

**Comment by physhik** [comment]
Same error when I installed glueviz using launcher

**Comment by soapy1** [comment]
I can't reproduce this issue on the newest versions of conda. Please `conda update conda`, if you still have problems, please reopen this issue 🎆
