### ISSUE TITLE
sha256sum of the anaconda miniconda .sh file for linux does not match

### ISSUE THREAD

**Issue by jerabaul29** [conda/conda#14339]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I install anaconda / miniconda in some container, using the following code:

```
RUN wget --https-only https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# this is hardcoded for now; retrieved from https://docs.anaconda.com/miniconda/
# TODO: find a programmatic way to retrieve the hash? or just update by hand when it breaks?
RUN echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check
```

this was working yesterday, but today I get a mismatch in the sha256sum:

```
Error: building at STEP "RUN echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check": while running runtime: exit status 1
```

I also tried by hand downloading the latest [Miniconda3 Linux 64-bit](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh) installer from https://docs.anaconda.com/miniconda/ . I get the following sha256sum, that does not match the expected sha256sum:

```
✔ pc6012:~/Downloads> wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
...
✔ pc6012:~/Downloads> echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check
Miniconda3-latest-Linux-x86_64.sh: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

Any idea why? If I should report it somewhere else, where should I report it?

**Comment by travishathaway** [comment]
@jerabaul29,

Miniconda is an Anaconda product so you will have to report this via their community channels:

- [Anaconda community forums](https://community.anaconda.cloud)
- [Anaconda issue tracker on GitHub](https://github.com/ContinuumIO/anaconda-issues/issues)

I'll be closing this issue for now as "off-topic".

**Comment by marcoesters** [comment]
@jerabaul29, this problem is due to unfortunate timing: a new Miniconda was uploaded and the documentation takes some time to update. It looks like you looked at the link at just the "right" time.

A more synchronized source for hashes is this page: https://repo.anaconda.com/miniconda/
