### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 67: character maps to <undefined>

### ISSUE THREAD

**Issue by shanmukh05** [conda/conda#14333]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to activate Conda Environment and whenever I run conda command, I got following error:

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "E:\anaconda\lib\site.py", line 589, in <module>
    main()
  File "E:\anaconda\lib\site.py", line 576, in main
    known_paths = addsitepackages(known_paths)
  File "E:\anaconda\lib\site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "E:\anaconda\lib\site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "E:\anaconda\lib\site.py", line 164, in addpackage
    for n, line in enumerate(f):
  File "E:\anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 67: character maps to <undefined>
```

### Conda Info

Running this command gives the same error

### Conda Config

Running this command gives the same error

### Conda list

Running this command gives the same error

**Comment by shanmukh05** [comment]
[Update] I reinstalled in the same location and now it's working fine. I still don't know the cause of this issue.

**Comment by travishathaway** [comment]
Thanks for the information. Feel free to close this issue if you want to; otherwise, we'll leave it open for future reference.
