### ISSUE TITLE
Conda is broken no module tqdm found

### ISSUE THREAD

**Issue by sjg2203** [conda/conda#14354]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

After updating from macOS Sequoia 15.0.1 to 15.1, I ran `conda update conda` and did not find any update so I then ran `conda update --all` which was immediately followed by this error message. Since then any command is followed by the same error message. I tried `conda init`, the same error prompted. Could anyone help me with this?
```
❯ conda update --all
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 51, in main_subshell
        parser = generate_parser(add_help=True)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 150, in generate_parser
        configure_parser_create(sub_parsers)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main_create.py", line 74, in configure_parser
        add_parser_solver(solver_mode_options)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/helpers.py", line 417, in add_parser_solver
        choices=context.plugin_manager.get_solvers(),
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 254, in get_solvers
        for solver_plugin in self.get_hook_results("solvers")
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in get_hook_results
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in <listcomp>
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/solvers.py", line 12, in conda_solvers
        from ..core.solve import Solver
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/core/solve.py", line 38, in <module>
        from ..resolve import Resolve
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/resolve.py", line 16, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /Users/macos/miniforge3/bin/conda update --all`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/macos/miniforge3/bin/conda
             CONDA_PREFIX=/Users/macos/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/macos/miniforge3/bin/python
               CONDA_ROOT=/Users/macos/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                     PATH=/Users/macos/miniforge3/bin:/Users/macos/miniforge3/condabin:/Library/
                          Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Pyth
                          on.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/L
                          ibrary/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/S
                          ystem/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com
                          .apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run
                          /com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/c
                          om.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bi
                          n:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Little
                          Snitch.app/Contents/Components
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/macos/miniforge3
            shell level : 1
       user config file : /Users/macos/.condarc
 populated config files : /Users/macos/miniforge3/.condarc
                          /Users/macos/.condarc
          conda version : 24.9.1
    conda-build version : 24.9.0
         python version : 3.10.15.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.1=0
                          __osx=15.1=0
                          __unix=0=0
       base environment : /Users/macos/miniforge3  (writable)
      conda av data dir : /Users/macos/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/apple/osx-arm64
                          https://conda.anaconda.org/apple/noarch
          package cache : /Users/macos/miniforge3/pkgs
                          /Users/macos/.conda/pkgs
       envs directories : /Users/macos/miniforge3/envs
                          /Users/macos/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.1 requests/2.32.3 CPython/3.10.15 Darwin/24.1.0 OSX/15.1 solver/libmamba
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: Y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

### Conda Info

❯ conda info
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 51, in main_subshell
        parser = generate_parser(add_help=True)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 150, in generate_parser
        configure_parser_create(sub_parsers)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main_create.py", line 74, in configure_parser
        add_parser_solver(solver_mode_options)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/helpers.py", line 417, in add_parser_solver
        choices=context.plugin_manager.get_solvers(),
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 254, in get_solvers
        for solver_plugin in self.get_hook_results("solvers")
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in get_hook_results
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in <listcomp>
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/solvers.py", line 12, in conda_solvers
        from ..core.solve import Solver
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/core/solve.py", line 38, in <module>
        from ..resolve import Resolve
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/resolve.py", line 16, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /Users/macos/miniforge3/bin/conda info`

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

### Conda Config

❯ conda config --show-sources
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 51, in main_subshell
        parser = generate_parser(add_help=True)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 150, in generate_parser
        configure_parser_create(sub_parsers)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main_create.py", line 74, in configure_parser
        add_parser_solver(solver_mode_options)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/helpers.py", line 417, in add_parser_solver
        choices=context.plugin_manager.get_solvers(),
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 254, in get_solvers
        for solver_plugin in self.get_hook_results("solvers")
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in get_hook_results
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in <listcomp>
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/solvers.py", line 12, in conda_solvers
        from ..core.solve import Solver
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/core/solve.py", line 38, in <module>
        from ..resolve import Resolve
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/resolve.py", line 16, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /Users/macos/miniforge3/bin/conda config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/macos/miniforge3/bin/conda
             CONDA_PREFIX=/Users/macos/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/macos/miniforge3/bin/python
               CONDA_ROOT=/Users/macos/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                     PATH=/Users/macos/miniforge3/bin:/Users/macos/miniforge3/condabin:/Library/
                          Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Pyth
                          on.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/L
                          ibrary/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/S
                          ystem/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com
                          .apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run
                          /com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/c
                          om.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bi
                          n:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Little
                          Snitch.app/Contents/Components
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/macos/miniforge3
            shell level : 1
       user config file : /Users/macos/.condarc
 populated config files : /Users/macos/miniforge3/.condarc
                          /Users/macos/.condarc
          conda version : 24.9.1
    conda-build version : 24.9.0
         python version : 3.10.15.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.1=0
                          __osx=15.1=0
                          __unix=0=0
       base environment : /Users/macos/miniforge3  (writable)
      conda av data dir : /Users/macos/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/apple/osx-arm64
                          https://conda.anaconda.org/apple/noarch
          package cache : /Users/macos/miniforge3/pkgs
                          /Users/macos/.conda/pkgs
       envs directories : /Users/macos/miniforge3/envs
                          /Users/macos/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.1 requests/2.32.3 CPython/3.10.15 Darwin/24.1.0 OSX/15.1 solver/libmamba
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

### Conda list

❯ conda list --show-channel-urls
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')
Error while loading conda entry point: conda-libmamba-solver (No module named 'tqdm')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 51, in main_subshell
        parser = generate_parser(add_help=True)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 150, in generate_parser
        configure_parser_create(sub_parsers)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/main_create.py", line 74, in configure_parser
        add_parser_solver(solver_mode_options)
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/cli/helpers.py", line 417, in add_parser_solver
        choices=context.plugin_manager.get_solvers(),
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 254, in get_solvers
        for solver_plugin in self.get_hook_results("solvers")
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in get_hook_results
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 212, in <listcomp>
        plugins = [item for items in hook() for item in items]
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/plugins/solvers.py", line 12, in conda_solvers
        from ..core.solve import Solver
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/core/solve.py", line 38, in <module>
        from ..resolve import Resolve
      File "/Users/macos/miniforge3/lib/python3.10/site-packages/conda/resolve.py", line 16, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /Users/macos/miniforge3/bin/conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/macos/miniforge3/bin/conda
             CONDA_PREFIX=/Users/macos/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/macos/miniforge3/bin/python
               CONDA_ROOT=/Users/macos/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                     PATH=/Users/macos/miniforge3/bin:/Users/macos/miniforge3/condabin:/Library/
                          Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Pyth
                          on.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/L
                          ibrary/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/S
                          ystem/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com
                          .apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run
                          /com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/c
                          om.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bi
                          n:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Little
                          Snitch.app/Contents/Components
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/macos/miniforge3
            shell level : 1
       user config file : /Users/macos/.condarc
 populated config files : /Users/macos/miniforge3/.condarc
                          /Users/macos/.condarc
          conda version : 24.9.1
    conda-build version : 24.9.0
         python version : 3.10.15.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.1=0
                          __osx=15.1=0
                          __unix=0=0
       base environment : /Users/macos/miniforge3  (writable)
      conda av data dir : /Users/macos/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/apple/osx-arm64
                          https://conda.anaconda.org/apple/noarch
          package cache : /Users/macos/miniforge3/pkgs
                          /Users/macos/.conda/pkgs
       envs directories : /Users/macos/miniforge3/envs
                          /Users/macos/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.1 requests/2.32.3 CPython/3.10.15 Darwin/24.1.0 OSX/15.1 solver/libmamba
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by travishathaway** [comment]
@sjg2203,

Not sure how your conda installation got to this state, but you may be able to fix it with `pip`. Try the following:

```
conda activate base
pip install tqdm
```

This will install the missing python dependency. But, I'm guessing there may be more missing dependencies if that is missing. Worth trying though. Let us know if that works.

**Comment by sjg2203** [comment]
`tqdm` package is already installed when using `pip`, I tried `conda activate base` but got the same error message. Could be that `conda` is broken in miniforge 24.9.0. When trying with miniconda with conda 24.9.2, everything works great somehow. Any idea why?

> @sjg2203,
> 
> Not sure how your conda installation got to this state, but you may be able to fix it with `pip`. Try the following:
> 
> ```
> conda activate base
> pip install tqdm
> ```
> 
> This will install the missing python dependency. But, I'm guessing there may be more missing dependencies if that is missing. Worth trying though. Let us know if that works.

**Comment by travishathaway** [comment]
@sjg2203,

If you suspect this is a problem with Miniforge, please file an issue in their project:

- https://github.com/conda-forge/miniforge

Unfortunately, this is a very difficult issue to debug as there are a number of things that could've gone wrong, so I am unable to provide any further advice at this point.

**Comment by sjg2203** [comment]
Thanks @travishathaway, I opened this issue [#671](https://github.com/conda-forge/miniforge/issues/671) if anyone faced a similar bug
