### ISSUE TITLE
Call for issue sorters

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#14373]
### Checklist

- [x] I added a descriptive title
- [x] I searched open requests and couldn't find a duplicate

### What is the idea?

This issue is a call for those interested in participating in issue sorting duties (as [defined here](https://github.com/conda/infrastructure/blob/main/HOW_WE_USE_GITHUB.md)). List are the current members of the conda project. Please put a checkbox near your name if you wish to continue being a part of issue sorting.

- [x] @travishathaway 
- [x] @jezdez 
- [ ] @dholth 
- [x] @kenodegard 
- [ ] @beeankha 
- [ ] @ForgottenProgramme 
- [ ] @jaimergp 
- [ ] @mbargull 
- [ ] @chenghlee 
- [x] @dashagurova

This will remain open for the next two weeks to give members enough time to vote.

**Comment by travishathaway** [comment]
Closing this issue as we have acquired enough issue sorters for now.

**Comment by george-lorch** [comment]
I would like to participate as I become more educated on all things conda.
