### ISSUE TITLE
Cannot specify exact version of a package during installation

### ISSUE THREAD

**Issue by julian-belina** [conda/conda#14392]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

Hello,

Unfortunately, I cannot specify an exact version of a package I want to install. The following command fails:

`conda create -n test_env_4 -c conda-forge matplotlib=2.0.0`.

with the following error message:

> (test_env_2) [j-belina@iek3028 ~]$ conda create -n test_env_4 -c conda-forge matplotlib=2.0.0
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - matplotlib=2.0.0
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/linux-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/nodefaults/linux-64
>   - https://conda.anaconda.org/nodefaults/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

While the following command will install

`conda create -n test_env_4 -c conda-forge matplotlib=2`.

However, version 2.0.0 definitely exists on conda-forge https://anaconda.org/conda-forge/matplotlib/files

### Conda Info

```shell
active environment : /fast/home/j-belina/micromamba/envs/test_env_2
    active env location : /fast/home/j-belina/micromamba/envs/test_env_2
            shell level : 3
       user config file : /fast/home/j-belina/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /fast/home/j-belina/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr  (read only)
      conda av data dir : /usr/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
          package cache : /var/cache/conda/pkgs
                          /fast/home/j-belina/.conda/pkgs
       envs directories : /fast/home/j-belina/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.27.1 CPython/3.6.8 Linux/4.18.0-477.15.1.el8_8.x86_64 rocky/8.8 glibc/2.28
                UID:GID : 1080:1083
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /usr/share/conda/condarc.d/defaults.yaml <==
pkgs_dirs:
  - /var/cache/conda/pkgs
  - ~/.conda/pkgs

==> /fast/home/j-belina/.condarc <==
auto_activate_base: False
channel_priority: strict
channels:
  - conda-forge
  - nodefaults
```

### Conda list

```shell
# packages in environment at /fast/home/j-belina/micromamba/envs/test_env_2:
#
# Name                    Version                   Build  Channel
```

**Comment by travishathaway** [comment]
@julian-belina,

Thanks for submitting this. I can't help but notice that the version of conda you are running is quite old. If possible, could you please attempt to update to a more recent version and let us know if you are experiencing the same difficulties? We only support the latest version of conda and will not patch previous releases.

**Comment by julian-belina** [comment]
@travishathaway, thank you for you fast reply. In order to update the conda version i had to switch to another computer. However, the problem still persists.

`(base) C:\Programming>conda create -n test_env_4 -c conda-forge matplotlib=2.0.0
Channels:
 - conda-forge
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - matplotlib=2.0.0*

Current channels:

  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

The updatet **conda info** is added here:

> active environment : base
>     active env location : C:\Users\j.belina\AppData\Local\miniforge3
>             shell level : 1
>        user config file : C:\Users\j.belina\.condarc
>  populated config files : C:\Users\j.belina\AppData\Local\miniforge3\.condarc
>                           C:\Users\j.belina\.condarc
>           conda version : 24.9.2
>     conda-build version : not installed
>          python version : 3.10.14.final.0
>                  solver : libmamba (default)
>        virtual packages : __archspec=1=skylake
>                           __conda=24.9.2=0
>                           __win=0=0
>        base environment : C:\Users\j.belina\AppData\Local\miniforge3  (writable)
>       conda av data dir : C:\Users\j.belina\AppData\Local\miniforge3\etc\conda
>   conda av metadata url : None
>            channel URLs : https://conda.anaconda.org/conda-forge/win-64
>                           https://conda.anaconda.org/conda-forge/noarch
>           package cache : C:\Users\j.belina\AppData\Local\miniforge3\pkgs
>                           C:\Users\j.belina\.conda\pkgs
>                           C:\Users\j.belina\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\j.belina\AppData\Local\miniforge3\envs
>                           C:\Users\j.belina\.conda\envs
>                           C:\Users\j.belina\AppData\Local\conda\conda\envs
>                platform : win-64
>              user-agent : conda/24.9.2 requests/2.31.0 CPython/3.10.14 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.10
>           administrator : False
>              netrc file : None
>            offline mode : False

conda config

> ==> C:\Users\j.belina\AppData\Local\miniforge3\.condarc <==
> channels:
>   - conda-forge
> 
> ==> C:\Users\j.belina\.condarc <==
> auto_activate_base: False
> channels:
>   - conda-forge

conda list --show-channel-urls

> # packages in environment at C:\Users\j.belina\AppData\Local\miniforge3:
> #
> # Name                    Version                   Build  Channel
> archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
> boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
> brotli-python             1.1.0           py310h00ffb61_1    conda-forge
> bzip2                     1.0.8                hcfcfb64_5    conda-forge
> ca-certificates           2024.8.30            h56e8100_0    conda-forge
> certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
> cffi                      1.16.0          py310h8d17308_0    conda-forge
> charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
> colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
> conda                     24.9.2          py310h5588dad_0    conda-forge
> conda-libmamba-solver     24.1.0             pyhd8ed1ab_0    conda-forge
> conda-package-handling    2.2.0              pyh38be061_0    conda-forge
> conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
> distro                    1.9.0              pyhd8ed1ab_0    conda-forge
> fmt                       11.0.2               h7f575de_0    conda-forge
> frozendict                2.4.6           py310ha8f682b_0    conda-forge
> idna                      3.6                pyhd8ed1ab_0    conda-forge
> jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
> jsonpointer               2.4             py310h5588dad_3    conda-forge
> krb5                      1.21.3               hdf4eb48_0    conda-forge
> libarchive                3.7.4                haf234dc_0    conda-forge
> libcurl                   8.10.1               h1ee3ff0_0    conda-forge
> libffi                    3.4.2                h8ffe710_5    conda-forge
> libiconv                  1.17                 hcfcfb64_2    conda-forge
> libmamba                  1.5.10               h81425b0_1    conda-forge
> libmambapy                1.5.10          py310h38857ff_1    conda-forge
> libsolv                   0.7.30               hbb528cf_0    conda-forge
> libsqlite                 3.45.2               hcfcfb64_0    conda-forge
> libssh2                   1.11.0               h7dfc565_0    conda-forge
> libxml2                   2.13.5               h442d1da_0    conda-forge
> libzlib                   1.3.1                h2466b09_2    conda-forge
> lz4-c                     1.9.4                hcfcfb64_0    conda-forge
> lzo                       2.10              he774522_1000    conda-forge
> mamba                     1.5.10          py310hd9d798f_1    conda-forge
> menuinst                  2.0.2           py310h00ffb61_0    conda-forge
> miniforge_console_shortcut 1.0                  h57928b3_0    conda-forge
> openssl                   3.4.0                h2466b09_0    conda-forge
> packaging                 24.0               pyhd8ed1ab_0    conda-forge
> pip                       24.0               pyhd8ed1ab_0    conda-forge
> platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
> pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
> pybind11-abi              4                    hd8ed1ab_3    conda-forge
> pycosat                   0.6.6           py310h8d17308_0    conda-forge
> pycparser                 2.22               pyhd8ed1ab_0    conda-forge
> pysocks                   1.7.1              pyh0701188_6    conda-forge
> python                    3.10.14         h4de0772_0_cpython    conda-forge
> python_abi                3.10                    4_cp310    conda-forge
> reproc                    14.2.4.post0         hcfcfb64_1    conda-forge
> reproc-cpp                14.2.4.post0         h63175ca_1    conda-forge
> requests                  2.31.0             pyhd8ed1ab_0    conda-forge
> ruamel.yaml               0.18.6          py310h8d17308_0    conda-forge
> ruamel.yaml.clib          0.2.8           py310h8d17308_0    conda-forge
> setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
> tk                        8.6.13               h5226925_1    conda-forge
> tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
> truststore                0.8.0              pyhd8ed1ab_0    conda-forge
> tzdata                    2024a                h0c530f3_0    conda-forge
> ucrt                      10.0.22621.0         h57928b3_0    conda-forge
> urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
> vc                        14.3                hcf57466_18    conda-forge
> vc14_runtime              14.38.33130         h82b7239_18    conda-forge
> vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
> wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
> win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
> xz                        5.2.6                h8d14728_0    conda-forge
> yaml-cpp                  0.8.0                h63175ca_0    conda-forge
> zstandard                 0.23.0          py310he5e10e1_1    conda-forge
> zstd                      1.5.6                h0ea2cb4_0    conda-forge

**Comment by travishathaway** [comment]
Thanks for following up with us @julian-belina.

It looks like this version is available on their channel but only by using a specific "testing" label. I would advise against using packages with such labels as you cannot rely at all on the packages stability.

For more information about the availability of this package version, I strongly recommend reaching out to the maintainers of conda-forge directly. More information about how to do that can be found here:

- https://conda-forge.org/community/getting-in-touch/

**Comment by travishathaway** [comment]
@julian-belina,

I was able to successfully create an environment with the `environment.yml` file you shared, so I can verify that the syntax is valid.

One thing you have to watch out for is the which platforms (e.g. `win-64`, `linux-64`, etc.) it is valid for. I run `osx-arm64`, and that environment file won't work because there are no builds available for that platform. Trying it instead with `--platform=win-64` did work though (that environment obviously wouldn't run on my computer though).

Maybe that's your issue?

**Comment by julian-belina** [comment]
@travishathaway Thanks for the suggestion. The platform does not seem to be the problem as both libraries are available for both wind 64 and linux-64.

However, there seems to be a conflict with __glibc for both matplotlib and pvlib.

> UnsatisfiableError: The following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.28=0
>   - conda-forge/label/testing::matplotlib=2.0.0 -> libpng[version='>=1.6.28,<1.7'] -> __glibc[version='>=2.17,<3.0.a0']
> 
> Your installed version is: 2.28


> UnsatisfiableError: The following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.28=0
>   - pvlib/label/main::pvlib=0.9.0 -> cftime[version='>=1.1.1'] -> __glibc[version='>=2.17,<3.0.a0']
> 
> Your installed version is: 2.28
> 

There is probably no way to fix this without upgrading or downgrading __glibc on the linux machine?

**Comment by travishathaway** [comment]
@julian-belina,

Yes, that's fair assumption.

**Comment by julian-belina** [comment]
@travishathaway, thanks for the confirmation. As far as possible, the issue has been resolved.
