### ISSUE TITLE
RPM and DEB packages are not uptodate with the current conda versions.

### ISSUE THREAD

**Issue by vigneshmanick** [conda/conda#14407]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

The RPM and DEP repos currently only have conda version 24.5.0 whereas the current conda version is 24.11.0. Please update the repos too.

Thanks!

### Conda Info

```shell

```

### Conda Config

```shell

```

### Conda list

```shell

```

**Comment by travishathaway** [comment]
@vigneshmanick,

These installers are managed by Anaconda, so please file an issue at this project to request that these installers be kept up to date:

- https://github.com/ContinuumIO/anaconda-issues/issues

I'll be closing this issue now as off-topic.
