### ISSUE TITLE
Conda install --clone doesn't respect dependency order

### ISSUE THREAD

**Issue by frol** [conda/conda#1451]
For example, there are gcc-4.8 and gcc-5 packages that test whether gcc works on `post-link` signal, but since not all gcc dependencies get cloned before this signal is fired, the tests fail.

**Comment by stuarteberg** [comment]
I haven't looked at `--clone` specifically, but you've probably rediscovered conda/conda-build#401.  Basically, the package install order is partially random if there are any circular dependencies in your environment.  (As it turns out, python is part of a circular dependency: pip<-->python.)
