### ISSUE TITLE
Conda logo?

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#1453]
It is a very minor issue, but with the work on the [conda-manager](https://github.com/spyder-ide/conda-manager) in [Spyder](https://github.com/spyder-ide/spyder), it would be nice to have a logo to display in the interface (in the preferences dialog...) that can be immediately associated with conda itself.

Any ideas on this?

**Comment by ccordoba12** [comment]
I think we can just select a font awesome icon for packages or something like that.

**Comment by goanpeca** [comment]
Sure, I know this, my suggestions is that conda being the heart of anaconda could use a dedicated logo

**Comment by asmeurer** [comment]
I've asked our marketing team about this, and will let you know what they tell me. It will likely either be the new Anaconda circle logo or a generic font-awesome icon, since conda itself does not have a logo at this time.

**Comment by 153957** [comment]
This is/was the conda logo (for a short while at least; f613034936e9d2c57183ff9820cba12000c8fa41, f6ec2153367e29fa932cc865c2c733ff91760de8 , 2616a538ada16d8ab6712b1f1241ebf7ac0e799c):
![](https://s3.amazonaws.com/conda-dev/conda_logo.svg)

**Comment by Juanlu001** [comment]
In the release notes it's mentioned that "Conda finally has an official logo", but I don't find it anywhere. Any hints?

**Comment by ccordoba12** [comment]
Pinging @csoja about this.

**Comment by kalefranz** [comment]
* https://s3.amazonaws.com/conda-dev/conda.svg
* https://s3.amazonaws.com/conda-dev/conda.png
* https://s3.amazonaws.com/conda-dev/conda-2x.png
* https://s3.amazonaws.com/conda-dev/conda-square.svg
* https://s3.amazonaws.com/conda-dev/conda-square.png
* https://s3.amazonaws.com/conda-dev/conda-square-512.png
