### ISSUE TITLE
conda broken when using older versions of argcomplete

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#1454]
Using conda with a version of argcomplete prior the the introduction of argcomplete.CompletionFinder (for example version 0.6.7) results in a unusable conda command.   The Traceback is as follows:

```
$ conda info
Traceback (most recent call last):
  File "/Users/jhelmus/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/jhelmus/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 106, in main
    from conda.cli import conda_argparse
  File "/Users/jhelmus/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 41, in <module>
    class CondaSubprocessCompletionFinder(argcomplete.CompletionFinder):
AttributeError: 'module' object has no attribute 'CompletionFinder' 
```

Since conda is broken one cannot use conda to update argcomplete.  A workaround is to use pip to upgrade argcomplete to a compatible version compatible and then use conda to reinstall argcomplete if desired.  

A check could be added to the try/except block in the conda_argparse.py module to detect this.

**Comment by asmeurer** [comment]
Fixed with https://github.com/conda/conda/commit/84404b3f259394a25e9a1a33ef4c623cb2ca6f38. We should be making a bugfix version of conda today. For now, the workaround is to `pip install -U argcomplete`.
