### ISSUE TITLE
docs: cheatsheet typo

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1456]
From the mailinglist:
```
http://conda.pydata.org/docs/_downloads/conda-cheatsheet.pdf

"conda update andaconda"
```

**Comment by asmeurer** [comment]
@electronwill

**Comment by electronwill** [comment]
Yikes. Thank you for tagging me on this. I'll get it fixed and post here when it's done.

**Comment by asmeurer** [comment]
I didn't see it on the printed version.

**Comment by electronwill** [comment]
No, the printed version is OK. I went ahead and made https://github.com/conda/conda-docs/pull/172 to fix the pdf, which we should go ahead and merge so people can see the right thing when they download it at PyData Seattle. Amenity will send the .ai source file for it ASAP, and as soon as she does I'll create a second pull request to update that too.

**Comment by electronwill** [comment]
Ah, I see 172 is merged already. Thanks!

**Comment by electronwill** [comment]
https://github.com/conda/conda-docs/pull/173 is done, so this issue should be solved and ready to close.
