### ISSUE TITLE
Remaining references to `binstar` when package has been removed from `root` environment

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#1459]
`conda update -n root --all` tries to update `binstar` when it is no longer present.

**Comment by asmeurer** [comment]
What specifically happens? `conda update --all` will update binstar if it is installed (just as it will every other package). The latest version of binstar will tell you to install conda-server when it is installed.

**Comment by jakirkham** [comment]
Sorry should have provided a log. Here is an example.

    $ conda update -n root --all
    Fetching package metadata: ......
    Solving package specifications: .
    Package plan for installation in environment /zopt/conda:
    
    The following NEW packages will be INSTALLED:
    
        binstar: 0.11.0-py27_0 defaults
    
    Proceed ([y]/n)? ^C
    Operation aborted.  Exiting.

**Comment by jakirkham** [comment]
I should add that I use to have `binstar` installed. So, I am wondering if there is some lingering info about it somewhere. I also have `binstar-build` as `conda-server-build` does not exist yet. Maybe it is picking up this dependency.

**Comment by jakirkham** [comment]
Yeah, sorry this is because of `binstar-build`.

**Comment by asmeurer** [comment]
This reminded me that I should get https://github.com/conda/conda/pull/1379 merged. It would make discovering that easier.

**Comment by jakirkham** [comment]
Added issue about this here ( https://github.com/Anaconda-Server/conda-server-build/issues/64 ).
