### ISSUE TITLE
updating miniconda

### ISSUE THREAD

**Issue by eumiro** [conda/conda#1462]
I have a current miniconda installation with a handful of packages I need and I would like to see if any update is available.

I tried "conda update conda", but it checked the "conda" package only (no update needed).
I also tried "conda update anaconda", but it tells me, that anaconda is not installed.
I also tried "conda update miniconda" with the same result.

Is there a way to see if any updates are available and process them automatically? Thank you!

**Comment by asmeurer** [comment]
Run `conda update --all`.

**Comment by gwvr** [comment]
`conda update --all`
Updates the packages within a miniconda environment. I've used this repeatedly over the months since I installed miniconda, but eventually hit the following error:
`Installing conda-forge::pyasn1-0.3.6-py_0 requires a minimum conda version of 4.3.`

To update miniconda itself, download the latest installer and run it with the upgrade option.
On linux:
```bash
bash Miniconda3-latest-Linux-x86_64.sh -u
```

**Comment by kalefranz** [comment]
In general just do `conda update conda` before `conda update —all`

**Comment by gwvr** [comment]
I tried that. Didn't work for me.

**Comment by gwvr** [comment]
Ok, I've tested this on another machine, and found that the *root* conda/miniconda environment must be activated before running `conda update conda` or `conda update --all`.
Of those commands are run in a different environment conda is not updated.

**Comment by sharbie88** [comment]
@gwvr 

> Ok, I've tested this on another machine, and found that the _root_ conda/miniconda environment must be activated before running `conda update conda` or `conda update --all`. Then it will attempt to update conda.

Can you tell me how to 

> activate the root conda/miniconda environment

 please?

**Comment by gwvr** [comment]
@sharbie88 try `conda activate base`
Afraid I can't help much beyond that - I've stopped using miniconda to manage my environments.
