### ISSUE TITLE
conda update with https_proxy

### ISSUE THREAD

**Issue by MichaelWS** [conda/conda#1468]
I need to constantly update my password for my https_proxy so I cannot put the password into the condarc file.  Also, my HTTPS_PROXY is at a http address.  This works for pip, wget, curl, etc.    On the new update of anaconda, when I do 

      conda update anaconda
    

I put my username then password.   It now seems to hang for a very long time period then I get the error.

      Error: maximum recursion depth exceeded while calling a Python object.

**Comment by asmeurer** [comment]
I just pushed a fix that will make conda show the full traceback for the recursion error.

>  Also, my HTTPS_PROXY is at a http address.

I thought I had remembered reading that that could be a problem, but I can't find anything in the documentation about it. If it works with pip it should work with conda, since they are both using requests.

**Comment by asmeurer** [comment]
Unfortunately, I can't really do much with this until I can see the full traceback. You'll either need to wait for the next version of conda, or test the git master using `PYTHONPATH=.`.

**Comment by MichaelWS** [comment]
well, the current master just works

**Comment by asmeurer** [comment]
There were some other changes around the proxy code recently. That must have fixed it. Let me know if you still see the issue.

**Comment by MichaelWS** [comment]
Is there anyway not to attempt to authenticate with the proxy?
pip just works if my user is logged in and calling pip with the proxy

**Comment by MichaelWS** [comment]
is it caching a log in for proxy?

**Comment by asmeurer** [comment]
conda doesn't cache the login, but if your OS has your proxy credentials they may be cached there.

**Comment by MichaelWS** [comment]
if I put the username/password in a file, conda works. I can remove, and conda still works for a bit.  
However, it is does not work after a few hours.

**Comment by asmeurer** [comment]
Maybe requests does some caching. I'm not sure.
