### ISSUE TITLE
Error: HTTPError: 403 Client Error: Forbidden: https://conda.binstar.org/r/linux-64/r-cluster-2.0.3-r3.2.1_0.tar.bz2

### ISSUE THREAD

**Issue by muxuezi** [conda/conda#1473]
I'd like to install rpy2 from conda with Python 3.4 and Python 2.7:
```bash
conda install -c https://conda.binstar.org/r rpy2
```
The downloading packages of Conda was discontinuous and even interrupt and show `Error: HTTPError: 403 Client Error ...` with `r-.*` packages at `https://conda.binstar.org/r`.

This is the fifth times I had tried and 3 packages was downloaded completely.

**Comment by jakirkham** [comment]
First off, [binstar.org]( https://binstar.org ) is being retired. So, you should use [anaconda.org]( https://anaconda.org ) instead (as shown below). 

    conda install -c https://conda.anaconda.org/r rpy2

Second, you can save some typing by just using the channel name and not the full URL.

    conda install -c r rpy2

Third, it sounds like you may have some connectivity issues. If you are using a proxy, you will need to configure it ( http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server ).

**Comment by sebastian-luna-valero** [comment]
Hello,

I am having the same error message on Travis:
https://travis-ci.org/CGATOxford/CGATPipelines/jobs/105375829#L590
https://travis-ci.org/CGATOxford/CGATPipelines/jobs/105375828#L590

for different packages (r-nlme, pybedtools) on different channels (r, bioconda)

Many thanks!

**Comment by sebastian-luna-valero** [comment]
This seems to be working now. Many thanks!
