### ISSUE TITLE
conda creating env is not working

### ISSUE THREAD

**Issue by iamrps** [conda/conda#1474]
While creating a env :myenv, it is getting stuck.
$conda info
Current conda install:
             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/rps/bin/python-2.7.9  (writable)
  default environment : /home/rps/bin/python-2.7.9
     envs directories : /home/rps/bin/python-2.7.9/envs
        package cache : /home/rps/bin/python-2.7.9/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
---

Issue : Not responding.
$ conda create -n myenv python
Fetching package metadata:

^C^C^C^C
^Z
[1]+  Stopped                 conda create -n myenv python

Anaconda downloaded version (2.7.9-Linux-x86_64)
How to fix this?? Please help...

**Comment by asmeurer** [comment]
Conda is hanging fetching the package metadata. It could be an intermittant issue either with your internet connection or with our servers. If you have a proxy, you may need to configure it (see http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server).

**Comment by soapy1** [comment]
@iamrps is this still an issue for you?
