### ISSUE TITLE
Set the default CondaSession.verify default from the config setting

### ISSUE THREAD

**Issue by jasongrout** [conda/conda#1495]
Currently, the .condarc config setting must be explicitly used when making a request with a CondaSession object.  This means that anyone who wants to use CondaSession must check the .condarc ssl_verify value and appropriately interpret it, etc.  (For example, see https://github.com/conda/conda/blob/47e300b0e2cd5aad1dfe18d26eada5995b058004/conda/fetch.py#L101)

I think it would be much cleaner for CondaSession itself to set the default verify value in its __init__: `self.verify = <code to get the .condarc ssl_verify setting`.  See https://github.com/kennethreitz/requests/blob/8b5e457b756b2ab4c02473f7a42c2e0201ecc7e9/requests/sessions.py#L314 to see that this is correct.

This change would mean that we don't need the verify argument here: https://github.com/conda/conda/blob/47e300b0e2cd5aad1dfe18d26eada5995b058004/conda/fetch.py#L101, and would also solve this issue: https://github.com/conda/conda-build/issues/523

**Comment by asmeurer** [comment]
Sounds good to me.
