### ISSUE TITLE
PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES in a conda environment

### ISSUE THREAD

**Issue by ovz** [conda/conda#1497]
Hi,

Is there a way to instruct conda to define PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES when creating an environment? 

These are required for CMake to discover python development tools. If I do 

sudo apt-get install python-dev

CMake complains that

CMake Warning at sscmake/Modules/salford_declare_targets.cmake:118 (add_library):  Cannot generate a safe linker search path for target ssSPM because files in  some directories may conflict with libraries in implicit directories:    link library [libpython2.7.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:      /home/ovz/spm/SPM80_dll/build/conda/current_platform/lib  Some of these libraries may not be found correctly.Call Stack (most recent call first): 

Thus it would be good if I could rely exclusively on conda for python-dev.

**Comment by seibert** [comment]
This describes how to have environment variables automatically set (and unset) when you activate a conda environment:

http://conda.pydata.org/docs/using/envs.html#saved-environment-variables

You can either make these files manually in an environment, or have a conda package that installs the desired activate/deactivate scripts.

**Comment by msarahan** [comment]
@ovz, I think it's unwise to have variables set when *creating* environments, though I'm definitely in favor of being able to set them when *activating* environments.

What @seibert points out are good examples of things that we could/should add to our Python packages.  You will still need to ```source activate <environment>```, but at least you'd never need to keep these variables in mind.

Finally, are you using conda-build?  I have not seen errors like this with conda-build.  I know we set several variables like these (though I don't think exactly these) there.  It might make your life easier to create conda packages.  Feel free to post any pain points that might be preventing you from using conda build or conda packages in general.

**Comment by ovz** [comment]
My request is about particular environment variables  PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES. If conda environment replaces system-wide python with a specific version, it would be good if it _automatically_ defines said variables so that all the build tools that are running in the environment only see environment-specific include and lib files.

**Comment by kalefranz** [comment]
These environment variables shouldn't be hard-coded into conda, but set via installing the python package (right now through the activate.d and deactivate.d directories).

**Comment by kalefranz** [comment]
I'm going to close this issue, given the solution.  Feel free to open a new issue at https://github.com/ContinuumIO/anaconda-issues for adjustment to the python package if you feel strongly about it.
