### ISSUE TITLE
Old repos (repodata) made with index can't be read by conda

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1498]
Anyone with an old repodata created with `conda index` before some period of time are unreadable by conda.  Some people have production repos that they don't upgrade and conda fails in non-obvious ways.  I'm not sure if the "bad" metadata needs to come from a package is a transitive dependency, but in some cases there is no error: "bad metadata".  If you try to install the package by itself, conda will finally give you a generic "bad metadata" error, but there is no indication of how to solve this problem. 

Depending on what "bad metadata" is caused by, conda could advise re-indexing the repodata.  Either way, the repodata format should be versioned to prevent more hidden errors like this.

**Comment by ilanschnell** [comment]
How old?  Which version of `conda index` was used?  It could also be that bad conda packages have been used.

**Comment by asmeurer** [comment]
Yeah, we need more information here. I thought these issues were fixed.
