### ISSUE TITLE
option to adjust output level of conda

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#150]
This is a low-priority request.

It would be great if conda could be adjusted to reduce the level of output.  I've used --quiet but that just gets rid of progress bars.  I'd love to suppress the copying, compiling, and other messages and only get warnings or errors.  I can do it via a pipe through grep, but that is error prone, and doesn't work in our Wakari fabric scripts (TTBOMK).

**Comment by lumeng** [comment]
I have the following in a cron job to take care of updating conda on a schedule:

    conda update conda >/dev/null

but it still prints non-warning messages and delivers to my mail box (/var/mail/XXX).  Pretty annoying.
