### ISSUE TITLE
Add documentation on how to bootstrap conda

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1500]
Bootstrapping conda, either on a new architecture or just building some of the packages that conda depends on, is not trivial. It would be useful to have some documentation on how to do it.

**Comment by kerrywatson1** [comment]
@asmeurer if you can do a rough draft we can do the rest.

**Comment by asmeurer** [comment]
I realized after opening this that it's not as easy as I thought, since I've never actually done this, I'd have to run through the whole process to make sure I didn't miss anything. Ilan has done it, so maybe he could help. It's not high priority, though.

**Comment by kerrywatson1** [comment]
@asmeurer can you please recommend someone to work on this with after you leave?

**Comment by asmeurer** [comment]
Ilan or Ryan. Again, someone would have to actually work through it and document what they did. But it's not a high priority item I'd say.

**Comment by adam-urbanczyk** [comment]
Are there any resources on the topic available (scripts, notes, actually anything)? I guess it is not at all critical but somewhat important from the philosophical point of view (free as in freedom...).

**Comment by mingwandroid** [comment]
You build all packages in dependency order from the recipes which are included with every package. Move info/meta.yaml.template to meta.yaml first though.

**Comment by adam-urbanczyk** [comment]
Thanks! Is it enough to build conda+deps this way to bootstrap an environment?

**Comment by mingwandroid** [comment]
Yes, but be careful to include both build and test deps and then topologically sort them all. Before that you need to build our crosstool-ng compilers and crosstool-ng itself. They're just conda recipes but you need to take care to build the compilers on centos6 first and to use the build matrix file in the recipe. These can be found at Anaconda Recipes on GitHub.

Once you have those in place you can simply (I wish!) pass a massive command line listing all the other packages in order.

I have scripts to help out with these but is he too embarrassed yup share them

**Comment by mingwandroid** [comment]
Didn't mean to close this. If you think I've answered everything the please do but also happy to keep this open for discussion purposes l.
