### ISSUE TITLE
git compile fails when curl is installed

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#1501]
I just discovered this obscure bug that I'm unable to compile git (I don't have root on some of my Linux servers, that's why I do that) when the `curl` package is installed, due to some C_PATH problem caused by that:

``` bash
imap-send.c: In function ‘setup_curl’:
imap-send.c:1428: error: ‘CURLOPT_LOGIN_OPTIONS’ undeclared (first use in this function)
imap-send.c:1428: error: (Each undeclared identifier is reported only once
imap-send.c:1428: error: for each function it appears in.)
imap-send.c:1428: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
make: *** [imap-send.o] Error 1
```

This is probably explained by this:
http://git.661346.n2.nabble.com/Compiling-2-4-0-doesn-t-seem-to-honour-C-INCLUDE-PATH-td7629976.html

and/or by the harshly different versions that exist on this system?:

``` bash
klay6683 at maven-iuvs-itf in ~/src/iuvs (master●●)
$ /usr/bin/curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.3.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

klay6683 at maven-iuvs-itf in ~/src/iuvs (master●●)
$ curl --version
curl 7.43.0 (x86_64-unknown-linux-gnu) libcurl/7.43.0 OpenSSL/1.0.1k zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

Anyhow, this can be avoided by creating an environment that does **NOT** have `curl` installed (confirmed).
Can this be somehow avoided for the case when the `curl` package is installed?

Edit: System: Linux, CentOS6

**Comment by kemin711** [comment]
I am having the same problem trying to compile git because it is too old in my system and IT won't update git.  I am trying to build my own version.  
imap-send.c:1428:26: error: ‘CURLOPT_LOGIN_OPTIONS’ undeclared (first use in this function)

**Comment by cfi** [comment]
I'm using the `make configure` flow.

    ./configure --with-curl=$myroot/bin/curl

fixed it for me.

**Comment by hyunjun** [comment]
@cfi Thanks, it works for me with 2.6.2 on Redhat 6.6

**Comment by hefangdotcom** [comment]
@cfi works for me. Thanks!
