### ISSUE TITLE
Not obvious how to incorporate custom channels into conda recipe

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1504]
I am creating a package where I know that the only place to find some of the required dependency packages come from certain not-obvious channels.  How do I specify that in the `meta.yaml` file?

I would like to be able to do:

```json
requirements:
  build:
    - cyclus/java-jre
```

or failing that to do:

```json
channels:
  - cyclus

requirements:
  build:
    - java-jre
```
I can’t see any way to do this in `meta.yaml` and I can't find any guidance on how to address this issue in any of the conda documentation.  This seems like such an obvious use case.  People who build packages will often have them be dependent on other "non-standard" packages.  There needs to be a package-creator mechanism for encoding the channels those "non-standard" packages come from.

I appreciate that the end-user *may* want to grab dependencies from some different set of channels: we should certainly support that.  But the default (if the end-user installing the package hasn't said anything different) surely must be to take whatever packages from whatever channels the package creator specifies.

Having to include external documentation (to make it a manual process) saying “and by the way to build or install this package you need to add `-c foo -c bar` or it absolutely won’t work” seems like the wrong answer.

**Comment by chdoig** [comment]
+1

I would also suggest that the option chosen is consistent between conda-build and conda-env. There was also some discussion around ``conda env export`` to include channel information: https://github.com/conda/conda-env/pull/103

**Comment by asmeurer** [comment]
For the first suggestion, see https://github.com/conda/conda/issues/988. For the second suggestion, I have opened https://github.com/conda/conda-build/issues/532.

**Comment by ijstokes** [comment]
@asmeurer I'm confused about the status of this: build-time is not what I'm concerned with.  Package builders are expert enough to do whatever complicated thing they need to do to make this all work, so I'm realizing my example is not exactly right, because what I want is something that at package definition and package build-time will end up *in* the package, thus allowing down-stream people installing the package to automatically get *my* package source "suggestions".

I think what I really care about is PR https://github.com/conda/conda/pull/1025 and it is not clear that there is any progress on that 1-commit PR from 8 months ago.
