### ISSUE TITLE
conda install python=3 now defaults to py33 packages not py34

### ISSUE THREAD

**Issue by nippoo** [conda/conda#1505]
We used to run `conda install conda python=3 pip numpy matplotlib scipy h5py pyqt ipython-notebook requests vispy six -y` in our automated install script.

On the default miniconda3 install this would install the py3.4 packages.

Now this seems to install a bunch of py3.3-build packages, while still having a python 3.4 install, which breaks everything.

Fix is to manually specify `python=3.4` but this isn't ideal (it's in an automated install script and it should install the correct packages if the user has python 3.3 already installed in their root environment)

**Comment by nippoo** [comment]
Running this command produces as output (among other lines):

```
The following packages will be UPDATED:
 
    conda:            3.10.1-py34_0 --> 3.15.1-py33_0                
    conda-env:        2.1.4-py34_0  --> 2.3.0-py33_0                 
    pyyaml:           3.11-py34_0   --> 3.11-py33_1                  
    requests:         2.6.0-py34_0  --> 2.7.0-py33_0  
```

Confusingly it's actually removing the py3.4 packages and installing (incorrectly) py3.3 packages...

**Comment by asmeurer** [comment]
If you remove `python=3` it will default to keeping the version of Python that is already installed.

**Comment by nippoo** [comment]
Yep, that works too. But `python=3` used to match any installed Python 3 versions (would keep py33 if it was already installed, for example). So we could use that to specify Python 3.*. It used to work correctly as expected up until a couple of days ago when it ends up downgrading packages while leaving the python 3.4 package installed leaving the user with a broken install.

So it's definitely a bug, or at least a recently introduced change. It shouldn't ever install py33 packages on a py34 environment...!

**Comment by asmeurer** [comment]
I agree. This is probably an instance of https://github.com/conda/conda/issues/1338.

**Comment by kalefranz** [comment]
Closing per #1338
