### ISSUE TITLE
Replace /bin/bash with /usr/bin/env bash

### ISSUE THREAD

**Issue by FRidh** [conda/conda#1509]
Currently `conda` hardcodes `#!/bin/bash`. If instead `#!/usr/bin/env bash` would be used, then the version of the current environment would be used.

I'm attempting to package `conda` at the moment for an OS where `#!/bin/bash` is unavailable, but `#!/usr/bin/env bash` does work.

The same by the way applies to some of the packages offered via `conda`.

Edit:
I can understand if such change wouldn't be made since there might be distributions where exactly that option isn't available.

**Comment by ilanschnell** [comment]
What exactly do you mean when say "`conda` hardcodes `#!/bin/bash`?  Do you mean the Miniconda installer?

**Comment by FRidh** [comment]
Installing packages on a system where `#!/bin/bash` isn't available but `#!/usr/bin/env bash` wouldn't work because of:
https://github.com/conda/conda/blob/master/conda/install.py#L339

The same applies for many of the packages offered by Anaconda as well as many of the recipes at
https://github.com/conda/conda-recipes/search?utf8=%E2%9C%93&q=bash

**Comment by ilanschnell** [comment]
https://github.com/conda/conda/blob/master/conda/install.py#L339 is only concerning the pre/post link scripts, which are not often used.  I've never come across a Unix system, which does not have `/bin/bash` installed.  I think it is safer to assume that `/bin/bash` exists than `/usr/bin/env`.  What system are you having this problem with?  And where is `bash` installed?  The easiest fix would be to create a link in `/bin/bash` to the location where bash is located on that system, I would say.  Do you have similar problems with other software of this system?

**Comment by FRidh** [comment]
I was using NixOS which puts all software in a store on a not so standard place.
When packaging software for Nix it is common to replace direct calls to /bin/bash since it doesn't exist on this system. `/usr/bin/env` is however available and is more portable.
