### ISSUE TITLE
'source activate' only works with bash, fails with other shells (e.g. dash)

### ISSUE THREAD

**Issue by Maggie-M** [conda/conda#1512]
I tried to activate a conda environment on linux with dash and encountered this error 

```
/bin/sh: 1: source: not found
```

I'm using **conda 3.15.1**

**Comment by asmeurer** [comment]
It only supports bash and zsh. There's nothing we can do for dash, since it apparently doesn't even support `source`.

**Comment by nsoranzo** [comment]
`source` is a bashism, can be safely replaced with `.` , see e.g. https://wiki.ubuntu.com/DashAsBinSh
