### ISSUE TITLE
Could not import Crypto

### ISSUE THREAD

**Issue by pitrou** [conda/conda#1515]
With latest conda (for Python 3):

```
$ conda --version
conda 3.16.0
$ conda --help
usage: conda [-h] [-V] [--debug] command ...

[...]

Traceback (most recent call last):
  File "/home/antoine/miniconda3/bin/conda-server", line 6, in <module>
    sys.exit(main())
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 60, in binstar_main
    add_subparser_modules(parser, sub_command_module, 'conda_server.subcommand')
TypeError: add_subparser_modules() takes 2 positional arguments but 3 were given
failed: /home/antoine/miniconda3/bin/conda-server --help
Error: could not import Crypto (required for "conda sign").
    Run the following command:

    $ conda install -n root pycrypto

failed: /home/antoine/miniconda3/bin/conda-sign --help
    skeleton     Generates a boilerplate/skeleton recipe, which you can then edit to create a
                 full recipe. Some simple skeleton recipes may not even need edits.
```

**Comment by frol** [comment]
I can confirm the issue with Crypto.

**Comment by DanielTakeshi** [comment]
Did you fix this issue?

**Comment by frol** [comment]
It seems that this issue is fixed. At least it doesn't throw any traceback now.

**Comment by DanielTakeshi** [comment]
What was your solution? (if you remember)

**Comment by frol** [comment]
@DanielTakeshi What do you mean by the "solution"? The issue was only in `conda --help` command (and possibly in `conda sign` command) and it didn't bother me at all, so I haven't fixed it as I haven't used either `--help` or `sign` in my build scripts.

**Comment by DanielTakeshi** [comment]
@frol  I meant it seemed like you had run into that same error as posted by @pitrou , but now things are working fine. I was just asking if you had remembered how you had "solved the problem" by avoiding the error message now. (Though given that it was a few months ago, I don't know if you remember.)

**Comment by frol** [comment]
@DanielTakeshi I haven't solved it by myself, I have just checked on the latest conda (3.18.8) version now and it is working fine for me. Do you still see the traceback that @pitrou posted on the latest conda version?
