### ISSUE TITLE
Error on "Conda Update Conda"

### ISSUE THREAD

**Issue by robertcatgithub** [conda/conda#1520]
# 

PS C:\Users\robert> conda update conda
Fetching package metadata: C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWar
ning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause
certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insec
ureplatformwarning.
  InsecurePlatformWarning
....
Solving package specifications: .
Package plan for installation in environment C:\Miniconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-env-2.3.0 | py27_0          63 KB |
| pyyaml-3.11 | py27_1         167 KB |
| requests-2.7.0 | py27_0         590 KB |
| conda-3.16.0 | py27_0         215 KB |

```
------------------------------------------------------------
                                       Total:         1.0 MB
```

The following packages will be UPDATED:

```
conda:      3.10.0-py27_0 --> 3.16.0-py27_0
conda-env:  2.1.3-py27_0  --> 2.3.0-py27_0
pip:        6.0.8-py27_0  --> 7.1.0-py27_0
pyyaml:     3.11-py27_0   --> 3.11-py27_1
requests:   2.6.0-py27_0  --> 2.7.0-py27_0
setuptools: 14.3-py27_0   --> 18.0.1-py27_0
```

Proceed ([y]/n)? y

Fetching packages ...
C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obj
ect is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
conda-env-2.3. 100% |###############################| Time: 0:00:00   2.00 MB/s
C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obj
ect is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
pyyaml-3.11-py 100% |###############################| Time: 0:00:00   3.64 MB/s
C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obj
ect is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
requests-2.7.0 100% |###############################| Time: 0:00:00   7.74 MB/s
C:\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext obj
ect is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
conda-3.16.0-p 100% |###############################| Time: 0:00:00   4.68 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  16%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-script.py", line 4, in <module>
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 202, in main
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
  File "C:\Miniconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
  File "C:\Miniconda\lib\site-packages\conda\cli\install.py", line 420, in install
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 502, in execute_actions
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 140, in execute_instructions
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 88, in UNLINK_CMD
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 613, in unlink
WindowsError: [Error 5] Access is denied: 'C:\Miniconda\conda-meta\conda-3.10.0-py27_0.json'
PS C:\Users\robert> conda info
Cannot open C:\Miniconda\Scripts\conda-script.py
PS C:\Users\robert>
# 

C:\Miniconda\Scripts\conda-script.py does not exist

**Comment by soapy1** [comment]
@robertcatgithub is this still an issue for you?

**Comment by tyler-thetyrant** [comment]
Closing due to lack or response.
