### ISSUE TITLE
Question on meta.yaml file structure

### ISSUE THREAD

**Issue by pmart123** [conda/conda#1521]
I have a question in regards to creating a meta.yaml file for a custom package.  After reading through the docs, I still don't have a good understanding of what to put in the "run" sub-section of requirements, i.e.:

requirements:
    build:
        - python
        - numpy
    run:
        ???

**Comment by PedroCardoso** [comment]
You should add the packages you need to add when installing the package (meaning, what it will need to run)
On your example, you might add python and numpy.

Build are only those required to build, I guess you would not need numpy there, but maybe setuptools

**Comment by soapy1** [comment]
Some documentation for this is here: http://conda.pydata.org/docs/building/meta-yaml.html
