### ISSUE TITLE
Error when changing to py3

### ISSUE THREAD

**Issue by idichekop** [conda/conda#1525]
C:\BIN\Anaconda>conda create -n py3k python=3 anaconda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\BIN\Anaconda\envs\py3k:

The following packages will be downloaded:

| package | build |
| --- | --- |
| alabaster-0.7.3 | py33_0          13 KB |
| beautiful-soup-4.3.2 | py33_1         114 KB |
| bitarray-0.8.1 | py33_1          54 KB |
| boto-2.38.0 | py33_0         1.6 MB |
| certifi-14.05.14 | py33_0         154 KB |
| clyent-0.3.4 | py33_0          13 KB |
| colorama-0.3.3 | py33_0          17 KB |
| cython-0.22.1 | py33_0         1.8 MB |
| cytoolz-0.7.3 | py33_0         188 KB |
| decorator-3.4.2 | py33_0           5 KB |
| docutils-0.12 | py33_1         657 KB |
| enum34-1.0.4 | py33_0          50 KB |
| fastcache-1.0.2 | py33_0          24 KB |
| greenlet-0.4.7 | py33_0          14 KB |
| idna-2.0 | py33_0         122 KB |
| itsdangerous-0.24 | py33_0          16 KB |
| jdcal-1.0 | py33_0           9 KB |
| jedi-0.8.1 | py33_0         181 KB |
| jsonschema-2.4.0 | py33_0          94 KB |
| llvmlite-0.5.0 | py33_0         4.8 MB |
| lxml-3.4.4 | py33_0         1.4 MB |
| markupsafe-0.23 | py33_0          24 KB |
| mistune-0.5.1 | py33_1         108 KB |
| mock-1.0.1 | py33_0          37 KB |
| multipledispatch-0.4.7 | py33_0          11 KB |
| networkx-1.9.1 | py33_0         995 KB |
| nose-1.3.7 | py33_0         255 KB |
| numpy-1.9.2 | py33_0        22.3 MB |
| astropy-1.0.3 | np19py33_0         5.5 MB |
| bcolz-0.9.0 | np19py33_0         313 KB |
| dynd-python-0.6.5 | np19py33_0         832 KB |
| numba-0.19.1 | np19py33_0         1.2 MB |
| numexpr-2.4.3 | np19py33_0         107 KB |
| blz-0.6.2 | np19py33_1         292 KB |
| openpyxl-1.8.5 | py33_0         169 KB |
| pep8-1.6.2 | py33_0          66 KB |
| pillow-2.8.2 | py33_0         936 KB |
| ply-3.6 | py33_0          71 KB |
| psutil-2.2.1 | py33_0          99 KB |
| py-1.4.27 | py33_0         126 KB |
| pyasn1-0.1.7 | py33_0          50 KB |
| pycosat-0.6.1 | py33_0          49 KB |
| pycparser-2.14 | py33_0         150 KB |
| cffi-1.1.0 | py33_0         106 KB |
| pycrypto-2.6.1 | py33_3         470 KB |
| pyflakes-0.9.2 | py33_0          97 KB |
| pygments-2.0.2 | py33_0         1.2 MB |
| pyparsing-2.0.3 | py33_0          66 KB |
| pyqt-4.10.4 | py33_1        30.6 MB |
| pyreadline-2.0 | py33_0         135 KB |
| ipython-3.2.0 | py33_0         3.6 MB |
| pytest-2.7.1 | py33_0         233 KB |
| python-3.3.5 | 1        21.6 MB |
| pytz-2015.4 | py33_0         170 KB |
| pywin32-219 | py33_0         7.6 MB |
| pyyaml-3.11 | py33_1         166 KB |
| pyzmq-14.7.0 | py33_0         598 KB |
| requests-2.7.0 | py33_0         586 KB |
| rope-0.9.4 | py33_1         237 KB |
| scipy-0.15.1 | np19py33_0        69.4 MB |
| setuptools-17.1.1 | py33_0         660 KB |
| six-1.9.0 | py33_0          17 KB |
| snowballstemmer-1.2.0 | py33_0          76 KB |
| sphinx_rtd_theme-0.1.7 | py33_0         209 KB |
| sqlalchemy-1.0.5 | py33_0         1.4 MB |
| sympy-0.7.6 | py33_0         6.6 MB |
| toolz-0.7.2 | py33_0          50 KB |
| tornado-4.2 | py33_0         573 KB |
| ujson-1.33 | py33_0          17 KB |
| werkzeug-0.10.4 | py33_0         415 KB |
| xlrd-0.9.3 | py33_0         161 KB |
| xlsxwriter-0.7.3 | py33_0         187 KB |
| xlwt-1.0.0 | py33_0         157 KB |
| argcomplete-0.8.9 | py33_0          84 KB |
| babel-1.3 | py33_0         2.3 MB |
| configobj-5.0.6 | py33_0          51 KB |
| cryptography-0.9.1 | py33_0         1.1 MB |
| h5py-2.5.0 | np19py33_1         563 KB |
| ipython-qtconsole-3.2.0 | py33_0           4 KB |
| jinja2-2.7.3 | py33_2         364 KB |
| nltk-3.0.3 | np19py33_0         1.6 MB |
| patsy-0.3.0 | np19py33_0         358 KB |
| pip-7.0.3 | py33_0         1.5 MB |
| pytables-3.2.0 | np19py33_0         1.5 MB |
| python-dateutil-2.4.2 | py33_0         220 KB |
| scikit-learn-0.16.1 | np19py33_0         3.5 MB |
| sockjs-tornado-1.0.1 | py33_0          32 KB |
| xlwings-0.3.5 | py33_0         238 KB |
| binstar-0.11.0 | py33_0         138 KB |
| datashape-0.4.5 | np19py33_0          98 KB |
| flask-0.10.1 | py33_1         135 KB |
| ipython-notebook-3.2.0 | py33_0           5 KB |
| matplotlib-1.4.3 | np19py33_1        42.3 MB |
| pandas-0.16.2 | np19py33_0         4.8 MB |
| pyopenssl-0.15.1 | py33_1         1.2 MB |
| sphinx-1.3.1 | py33_0         1.2 MB |
| bokeh-0.9.0 | np19py33_0        12.7 MB |
| odo-0.3.2 | np19py33_0         191 KB |
| runipy-0.1.3 | py33_0          48 KB |
| scikit-image-0.11.3 | np19py33_0        15.7 MB |
| statsmodels-0.6.1 | np19py33_0         4.8 MB |
| blaze-core-0.8.0 | np19py33_0         332 KB |
| anaconda-2.3.0 | np19py33_0          30 KB |

```
------------------------------------------------------------
                                       Total:       288.8 MB
```

The following NEW packages will be INSTALLED:

```
alabaster:         0.7.3-py33_0
anaconda:          2.3.0-np19py33_0
argcomplete:       0.8.9-py33_0
astropy:           1.0.3-np19py33_0
babel:             1.3-py33_0
bcolz:             0.9.0-np19py33_0
beautiful-soup:    4.3.2-py33_1
binstar:           0.11.0-py33_0
bitarray:          0.8.1-py33_1
blaze-core:        0.8.0-np19py33_0
blz:               0.6.2-np19py33_1
bokeh:             0.9.0-np19py33_0
boto:              2.38.0-py33_0
certifi:           14.05.14-py33_0
cffi:              1.1.0-py33_0
clyent:            0.3.4-py33_0
colorama:          0.3.3-py33_0
configobj:         5.0.6-py33_0
cryptography:      0.9.1-py33_0
cython:            0.22.1-py33_0
cytoolz:           0.7.3-py33_0
datashape:         0.4.5-np19py33_0
decorator:         3.4.2-py33_0
docutils:          0.12-py33_1
dynd-python:       0.6.5-np19py33_0
enum34:            1.0.4-py33_0
fastcache:         1.0.2-py33_0
flask:             0.10.1-py33_1
greenlet:          0.4.7-py33_0
h5py:              2.5.0-np19py33_1
hdf5:              1.8.15.1-2
idna:              2.0-py33_0
ipython:           3.2.0-py33_0
ipython-notebook:  3.2.0-py33_0
ipython-qtconsole: 3.2.0-py33_0
itsdangerous:      0.24-py33_0
jdcal:             1.0-py33_0
jedi:              0.8.1-py33_0
jinja2:            2.7.3-py33_2
jsonschema:        2.4.0-py33_0
llvmlite:          0.5.0-py33_0
lxml:              3.4.4-py33_0
markupsafe:        0.23-py33_0
matplotlib:        1.4.3-np19py33_1
mistune:           0.5.1-py33_1
mock:              1.0.1-py33_0
multipledispatch:  0.4.7-py33_0
networkx:          1.9.1-py33_0
nltk:              3.0.3-np19py33_0
nose:              1.3.7-py33_0
numba:             0.19.1-np19py33_0
numexpr:           2.4.3-np19py33_0
numpy:             1.9.2-py33_0
odo:               0.3.2-np19py33_0
openpyxl:          1.8.5-py33_0
pandas:            0.16.2-np19py33_0
patsy:             0.3.0-np19py33_0
pep8:              1.6.2-py33_0
pillow:            2.8.2-py33_0
pip:               7.0.3-py33_0
ply:               3.6-py33_0
psutil:            2.2.1-py33_0
py:                1.4.27-py33_0
pyasn1:            0.1.7-py33_0
pycosat:           0.6.1-py33_0
pycparser:         2.14-py33_0
pycrypto:          2.6.1-py33_3
pyflakes:          0.9.2-py33_0
pygments:          2.0.2-py33_0
pyopenssl:         0.15.1-py33_1
pyparsing:         2.0.3-py33_0
pyqt:              4.10.4-py33_1
pyreadline:        2.0-py33_0
pytables:          3.2.0-np19py33_0
pytest:            2.7.1-py33_0
python:            3.3.5-1
python-dateutil:   2.4.2-py33_0
pytz:              2015.4-py33_0
pywin32:           219-py33_0
pyyaml:            3.11-py33_1
pyzmq:             14.7.0-py33_0
requests:          2.7.0-py33_0
rope:              0.9.4-py33_1
runipy:            0.1.3-py33_0
scikit-image:      0.11.3-np19py33_0
scikit-learn:      0.16.1-np19py33_0
scipy:             0.15.1-np19py33_0
setuptools:        17.1.1-py33_0
six:               1.9.0-py33_0
snowballstemmer:   1.2.0-py33_0
sockjs-tornado:    1.0.1-py33_0
sphinx:            1.3.1-py33_0
sphinx_rtd_theme:  0.1.7-py33_0
sqlalchemy:        1.0.5-py33_0
statsmodels:       0.6.1-np19py33_0
sympy:             0.7.6-py33_0
toolz:             0.7.2-py33_0
tornado:           4.2-py33_0
ujson:             1.33-py33_0
werkzeug:          0.10.4-py33_0
xlrd:              0.9.3-py33_0
xlsxwriter:        0.7.3-py33_0
xlwings:           0.3.5-py33_0
xlwt:              1.0.0-py33_0
zlib:              1.2.8-0
```

Proceed ([y]/n)? y

Fetching packages ...
alabaster-0.7. 100% |###############################| Time: 0:00:00 130.83 kB/s
beautiful-soup 100% |###############################| Time: 0:00:00 325.50 kB/s
bitarray-0.8.1 100% |###############################| Time: 0:00:00 199.59 kB/s
boto-2.38.0-py 100% |###############################| Time: 0:00:03 455.10 kB/s
certifi-14.05. 100% |###############################| Time: 0:00:00 346.09 kB/s
clyent-0.3.4-p 100% |###############################| Time: 0:00:00 127.61 kB/s
colorama-0.3.3 100% |###############################| Time: 0:00:00 169.86 kB/s
cython-0.22.1- 100% |###############################| Time: 0:00:04 438.34 kB/s
cytoolz-0.7.3- 100% |###############################| Time: 0:00:00 394.65 kB/s
decorator-3.4. 100% |###############################| Time: 0:00:00 621.61 kB/s
docutils-0.12- 100% |###############################| Time: 0:00:01 358.88 kB/s
enum34-1.0.4-p 100% |###############################| Time: 0:00:00 254.07 kB/s
fastcache-1.0. 100% |###############################| Time: 0:00:00 235.01 kB/s
greenlet-0.4.7 100% |###############################| Time: 0:00:00 133.00 kB/s
idna-2.0-py33_ 100% |###############################| Time: 0:00:00 345.42 kB/s
itsdangerous-0 100% |###############################| Time: 0:00:00 176.21 kB/s
jdcal-1.0-py33 100% |###############################| Time: 0:00:00   1.13 MB/s
jedi-0.8.1-py3 100% |###############################| Time: 0:00:00 509.60 kB/s
jsonschema-2.4 100% |###############################| Time: 0:00:00 332.01 kB/s
llvmlite-0.5.0 100% |###############################| Time: 0:00:04   1.02 MB/s
lxml-3.4.4-py3 100% |###############################| Time: 0:00:01 853.28 kB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00 251.46 kB/s
mistune-0.5.1- 100% |###############################| Time: 0:00:00 302.98 kB/s
mock-1.0.1-py3 100% |###############################| Time: 0:00:00 200.77 kB/s
multipledispat 100% |###############################| Time: 0:00:00   1.27 MB/s
networkx-1.9.1 100% |###############################| Time: 0:00:01 571.79 kB/s
nose-1.3.7-py3 100% |###############################| Time: 0:00:00 334.16 kB/s
numpy-1.9.2-py 100% |###############################| Time: 0:00:31 752.26 kB/s
astropy-1.0.3- 100% |###############################| Time: 0:00:17 330.66 kB/s
bcolz-0.9.0-np 100% |###############################| Time: 0:00:01 296.54 kB/s
dynd-python-0. 100% |###############################| Time: 0:00:01 594.37 kB/s
numba-0.19.1-n 100% |###############################| Time: 0:00:02 420.89 kB/s
numexpr-2.4.3- 100% |###############################| Time: 0:00:00 268.53 kB/s
blz-0.6.2-np19 100% |###############################| Time: 0:00:00 471.14 kB/s
openpyxl-1.8.5 100% |###############################| Time: 0:00:00 285.81 kB/s
pep8-1.6.2-py3 100% |###############################| Time: 0:00:00 231.31 kB/s
pillow-2.8.2-p 100% |###############################| Time: 0:00:01 498.57 kB/s
ply-3.6-py33_0 100% |###############################| Time: 0:00:00 186.01 kB/s
psutil-2.2.1-p 100% |###############################| Time: 0:00:00 280.52 kB/s
py-1.4.27-py33 100% |###############################| Time: 0:00:00 331.00 kB/s
pyasn1-0.1.7-p 100% |###############################| Time: 0:00:00 273.09 kB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00 251.74 kB/s
pycparser-2.14 100% |###############################| Time: 0:00:00 310.93 kB/s
cffi-1.1.0-py3 100% |###############################| Time: 0:00:00 282.71 kB/s
pycrypto-2.6.1 100% |###############################| Time: 0:00:00 575.94 kB/s
pyflakes-0.9.2 100% |###############################| Time: 0:00:00 269.69 kB/s
pygments-2.0.2 100% |###############################| Time: 0:00:01 628.60 kB/s
pyparsing-2.0. 100% |###############################| Time: 0:00:00 248.42 kB/s
pyqt-4.10.4-py 100% |###############################| Time: 0:00:36 890.65 kB/s
pyreadline-2.0 100% |###############################| Time: 0:00:00 283.78 kB/s
ipython-3.2.0- 100% |###############################| Time: 0:00:06 583.21 kB/s
pytest-2.7.1-p 100% |###############################| Time: 0:00:00 353.62 kB/s
python-3.3.5-1 100% |###############################| Time: 0:00:30 749.63 kB/s
pytz-2015.4-py 100% |###############################| Time: 0:00:00 358.10 kB/s
pywin32-219-py 100% |###############################| Time: 0:00:13 609.01 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 374.71 kB/s
pyzmq-14.7.0-p 100% |###############################| Time: 0:00:01 393.42 kB/s
requests-2.7.0 100% |###############################| Time: 0:00:01 518.66 kB/s
rope-0.9.4-py3 100% |###############################| Time: 0:00:01 194.62 kB/s
scipy-0.15.1-n 100% |###############################| Time: 0:01:20 899.44 kB/s
setuptools-17. 100% |###############################| Time: 0:00:01 411.42 kB/s
six-1.9.0-py33 100% |###############################| Time: 0:00:00 175.11 kB/s
snowballstemme 100% |###############################| Time: 0:00:00 263.08 kB/s
sphinx_rtd_the 100% |###############################| Time: 0:00:00 396.29 kB/s
sqlalchemy-1.0 100% |###############################| Time: 0:00:01 733.76 kB/s
sympy-0.7.6-py 100% |###############################| Time: 0:00:04   1.40 MB/s
toolz-0.7.2-py 100% |###############################| Time: 0:00:00 252.07 kB/s
tornado-4.2-py 100% |###############################| Time: 0:00:00 590.57 kB/s
ujson-1.33-py3 100% |###############################| Time: 0:00:00 176.80 kB/s
werkzeug-0.10. 100% |###############################| Time: 0:00:00 487.87 kB/s
xlrd-0.9.3-py3 100% |###############################| Time: 0:00:00 226.80 kB/s
xlsxwriter-0.7 100% |###############################| Time: 0:00:00 308.59 kB/s
xlwt-1.0.0-py3 100% |###############################| Time: 0:00:00 354.31 kB/s
argcomplete-0. 100% |###############################| Time: 0:00:00 311.80 kB/s
babel-1.3-py33 100% |###############################| Time: 0:00:05 416.01 kB/s
configobj-5.0. 100% |###############################| Time: 0:00:00 190.03 kB/s
cryptography-0 100% |###############################| Time: 0:00:02 465.71 kB/s
h5py-2.5.0-np1 100% |###############################| Time: 0:00:01 315.89 kB/s
ipython-qtcons 100% |###############################| Time: 0:00:00 428.89 kB/s
jinja2-2.7.3-p 100% |###############################| Time: 0:00:00 515.61 kB/s
nltk-3.0.3-np1 100% |###############################| Time: 0:00:03 449.35 kB/s
patsy-0.3.0-np 100% |###############################| Time: 0:00:00 457.77 kB/s
pip-7.0.3-py33 100% |###############################| Time: 0:00:02 742.93 kB/s
pytables-3.2.0 100% |###############################| Time: 0:00:02 530.21 kB/s
python-dateuti 100% |###############################| Time: 0:00:00 412.90 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:08 416.50 kB/s
sockjs-tornado 100% |###############################| Time: 0:00:00 165.86 kB/s
xlwings-0.3.5- 100% |###############################| Time: 0:00:00 316.53 kB/s
binstar-0.11.0 100% |###############################| Time: 0:00:00 383.77 kB/s
datashape-0.4. 100% |###############################| Time: 0:00:00 259.93 kB/s
flask-0.10.1-p 100% |###############################| Time: 0:00:00 353.05 kB/s
ipython-notebo 100% |###############################| Time: 0:00:00 535.44 kB/s
matplotlib-1.4 100% |###############################| Time: 0:01:11 623.19 kB/s
pandas-0.16.2- 100% |###############################| Time: 0:00:09 521.18 kB/s
pyopenssl-0.15 100% |###############################| Time: 0:00:01 731.53 kB/s
sphinx-1.3.1-p 100% |###############################| Time: 0:00:03 345.69 kB/s
bokeh-0.9.0-np 100% |###############################| Time: 0:00:09   1.39 MB/s
odo-0.3.2-np19 100% |###############################| Time: 0:00:00 429.91 kB/s
runipy-0.1.3-p 100% |###############################| Time: 0:00:00 265.93 kB/s
scikit-image-0 100% |###############################| Time: 0:00:23 687.35 kB/s
statsmodels-0. 100% |###############################| Time: 0:00:06 836.12 kB/s
blaze-core-0.8 100% |###############################| Time: 0:00:01 270.44 kB/s
anaconda-2.3.0 100% |###############################| Time: 0:00:00 296.62 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\BIN\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\BIN\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\BIN\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "C:\BIN\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\BIN\Anaconda\lib\site-packages\conda\cli\main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "C:\BIN\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\BIN\Anaconda\lib\site-packages\conda\plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\BIN\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\BIN\Anaconda\lib\site-packages\conda\instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\BIN\Anaconda\lib\site-packages\conda\install.py", line 455, in extract
    t.extractall(path=path)
  File "C:\BIN\Anaconda\lib\tarfile.py", line 2072, in extractall
    self.extract(tarinfo, path)
  File "C:\BIN\Anaconda\lib\tarfile.py", line 2109, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\BIN\Anaconda\lib\tarfile.py", line 2177, in _extract_member
    os.makedirs(upperdirs)
  File "C:\BIN\Anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\BIN\Anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\BIN\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: u'C:\BIN\Anaconda\pkgs\zlib-1.2.8-0'

---

Also here the result of 'conda info'

C:\BIN\Anaconda>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.14.1
```

  conda-build version : 1.14.1
       python version : 2.7.10
     requests version : 2.7.0
     root environment : C:\BIN
  default environment : C:\BIN
     envs directories : C:\BIN
        package cache : C:\BIN
         channel URLs : https:
                        https:
                        https:
                        https:
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
I can't reproduce this issue on newer versions of conda. Please `conda update conda`. If the problem persists, please reopen this issue
