### ISSUE TITLE
PATH error when activating environments in the Anaconda Command Prompt

### ISSUE THREAD

**Issue by Maggie-M** [conda/conda#1531]
If you create an activate an env in the Windows Anaconda command prompt and run `where python`, the output will show that is still selecting the system python over the env's.

![screen shot 2015-08-14 at 2 53 02 pm](https://cloud.githubusercontent.com/assets/1417520/9282741/3c2c37e8-4294-11e5-8158-6cb1b30af653.png)

On the windows command prompt, however, everything works correctly and the path is properly set.

**Comment by kalefranz** [comment]
Is this still an issue?
