### ISSUE TITLE
Support for finding libraries in LD_LIBRARY_PATH/DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#1533]
Some packages like [`pylibtiff`]( https://github.com/pearu/pylibtiff ) use `ctypes.util.find_library` to search for a library that they are not built against. This requires the library to be found on `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`. Is it possible we could support this?

**Comment by jakirkham** [comment]
For the record, I tried changing `PATH` as suggested by the `ImportError` message provided by `pylibtiff` and this did **not** work.

**Comment by ilanschnell** [comment]
Sure, you can se `LD_LIBRARY_PATH` if you want.  I don't see how this is a conda issue, though.

**Comment by jakirkham** [comment]
@ilanschnell, the issue does not concern setting the `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH` during the build it concerns having it set after installation. Is there a way to do that at present?

**Comment by ilanschnell** [comment]
There is a way to set environment variables when activating a conda environment.  To do this, there need to be a bash script in `<PREFIX>/etc/conda/activate.d/*.sh`.  When `source activate` is run, all these scripts are "sourced".  For example, a conda package could have `etc/conda/activate.d/foo.sh`.

**Comment by jakirkham** [comment]
Does this work on a per environment case? My main concern is having an easy-to-install package for `pylibtiff` or anything else suffering from this issue that works out of the box.

**Comment by ccordoba12** [comment]
Yes, it works on deactivation too. The only thing is that that doesn't work on the root environment.

**Comment by ilanschnell** [comment]
Using this hook to set `LD_LIBRARY_PATH` is really an really ugly way to try and get `pylibtiff` to work.  The `LD_LIBRARY_PATH` should never be used in production as it might cause other things to break.  Using `LD_LIBRARY_PATH` in production is as bad as using `PYTHONPATH` in production.

If I had to build `pylibtiff` for Anaconda, I would first try to understand **why** and how it uses `LD_LIBRARY_PATH`, and then patch it such that it doesn't make use  of `LD_LIBRARY_PATH` anymore.

**Comment by jakirkham** [comment]
So, in the case of `pylibtiff`, this is due to the behavior of `ctypes.util.find_library`. I am only looking at setting the setting the environment variable as I feel like this patch is even more of a hack. ( https://github.com/jakirkham/conda-recipes/commit/bc58d66beb32f7941af876b0be83d72018c91663#diff-4c1bcb38135ed7938338f3b7cdbd7cd6R8 )

**Comment by ilanschnell** [comment]
There is a conda package for `libtiff`, and when `pylibtiff` depends on `libtiff`, the library is always in a known location, i.e. `<PREFIX>/lib/libtiff.so`.  So there should not be the need to search for it.  Trust me, you don't want to set `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH`.  Setting these will cause hard to debug issues in other packages down the road.

**Comment by jakirkham** [comment]
I hear what you are saying. Unfortunately, it did not work out of the box, which is why I added these horrible hacks in the first place. I will continue to investigate whether there isn't a better fix.

**Comment by jakirkham** [comment]
It turns out `ctypes.util.find_library` will check the current working directory. So, one can temporarily switch to a relevant directory, find the library, and switch back afterwards.

**Comment by ilanschnell** [comment]
Yes, so in the code of `pylibtiff`, I would so something like:
```
os.chdir(os.path.join(sys.prefix, 'lib'))
```
before the call to `ctypes.util.find_library`.  And then when the conda `libtiff` is installed as a `pylibtiff` dependency, all should be fine.

**Comment by jakirkham** [comment]
That's certainly one way. I did it a little differently in the hopes that it might be added to pylibtiff itself.
