### ISSUE TITLE
`-q` not working in `conda env create -q`

### ISSUE THREAD

**Issue by ctaggart** [conda/conda#1536]
See  https://ci.appveyor.com/project/elehack/lenskit/build/3.0.276
![image](https://cloud.githubusercontent.com/assets/80104/9316822/67322ed4-44ec-11e5-8a39-934a03e7b2d8.png)

as well as 
https://github.com/lenskit/lenskit/pull/756
https://github.com/appveyor/ci/issues/359

**Comment by soapy1** [comment]
This is no longer an issue in the newest version of conda. Please `conda update conda`. If this problem persists please reopen the issue 🍰
