### ISSUE TITLE
Unable to Update pandas using conda

### ISSUE THREAD

**Issue by GTaneja** [conda/conda#1542]
Hi All,
I am pretty new to Python and am using Anaconda as the go to for starting python. My problem is when i update pandas ( currently I have a 0.12.0 pandas version) the following happens

C:\Users\A021768\AppData\Local\Continuum\Anaconda>conda install pandas
Error: unknown host: http://repo.continuum.io/pkgs/pro/win-64/
Error: unknown host: http://repo.continuum.io/pkgs/free/win-64/
Error: Unsatisfiable package specifications
Hint: the following combinations of packages create a conflict with the
remaining packages:
- numpy 1.7*
- pandas

I am not sure what the conflict is with other packages and if I need to uninstall some packages to resolve the conflict. 

I just need to update my pandas version to the most recent one supporting Python 2.7

Thanks,
GT

**Comment by asmeurer** [comment]
Do you have the latest version of conda (`conda update conda`)?

**Comment by soapy1** [comment]
@GTaneja is this still an issue for you?
