### ISSUE TITLE
ssl.CertificateError: hostname 'conda.alpha.binstar.org' doesn't match either of '*.binstar.org', 'binstar.org'

### ISSUE THREAD

**Issue by twiecki** [conda/conda#1545]
This must be a left-over from an older installation but I can't find any reference to conda.alpha.binstar.org in ~/.condarc.

**Comment by bkreider** [comment]
Can you try "conda info -a"?  That will dump everything that conda knows about.

**Comment by twiecki** [comment]
Apparently having -asmeurer as a channel in there somehow linked to it. After removing it it works. Thanks!
