### ISSUE TITLE
how to use conda develop?

### ISSUE THREAD

**Issue by arsenovic** [conda/conda#1546]
im not sure how to use this command. is this supposed to operate like `python setup.py develop`?

**Comment by asmeurer** [comment]
Yes, it is. Note that there have been some improvements to it in recent versions of `conda-build`.

**Comment by arsenovic** [comment]
so, the usage is to:

    git clone xyz 
    conda develop /path/to/xyz

**Comment by Hornswoggles** [comment]
Bump. I also don't understand how this is supposed to be used. I've read through the documentation. Can you give an example? The documentation as written is insufficient.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1992
