### ISSUE TITLE
Adding a Root CA cert to conda's cert store

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1553]
I know I can force conda to ignore cert validation, but how does one add a new Root CA to conda's cert store (without ENV variables)?  

There are enterprises that run very tight networks where they man-in-the-middle all SSL connections (for inspection).  To do this, they "forge" the SSL cert and conda needs to trust it.

**Comment by asmeurer** [comment]
Is it just a matter of putting something in ~/anaconda/ssl?

**Comment by JeremyEnns** [comment]
could this also be related? https://github.com/conda/conda/issues/1387

**Comment by bkreider** [comment]
Thanks, Jeremy.  That is related.  I looked at the PR and i can't figure if the SSL path is actually used in that PR and I don't see any documentation around this.

**Comment by bkreider** [comment]
Ok.  I think i figured it out and can close this one and open some new issues around this feature.  It looks like you can specify a path to the certs now.
