### ISSUE TITLE
NOT FOUND error trying to install paramiko under conda

### ISSUE THREAD

**Issue by martinlipman** [conda/conda#1554]
Trying to install paramiko under Anaconda via Windows 64 using the command

conda install -c https://conda.binstar.org/anaconda paramiko

Receive the following, ending with a "Client Error:  NOT FOUND:"

Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment C:\Users\rdmal\AppData\Local\Continuum\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.4.2            |           py34_0          64 KB
    ecdsa-0.11                 |           py34_0          74 KB
    pyyaml-3.11                |           py34_1         117 KB
    requests-2.7.0             |           py34_0         622 KB
    setuptools-18.1            |           py34_0         650 KB
    wheel-0.24.0               |           py34_0         118 KB
    conda-3.16.0               |           py34_0         219 KB
    paramiko-1.15.2            |           py34_0         206 KB
    pip-7.1.2                  |           py34_0         1.5 MB
    ------------------------------------------------------------
                                           Total:         3.5 MB

The following NEW packages will be INSTALLED:

    ecdsa:      0.11-py34_0
    paramiko:   1.15.2-py34_0
    wheel:      0.24.0-py34_0

The following packages will be UPDATED:

    conda:      3.10.0-py34_0 --> 3.16.0-py34_0
    conda-env:  2.1.3-py34_0  --> 2.4.2-py34_0
    pip:        6.0.8-py34_0  --> 7.1.2-py34_0
    pyyaml:     3.11-py34_0   --> 3.11-py34_1
    requests:   2.6.0-py34_0  --> 2.7.0-py34_0
    setuptools: 14.3-py34_0   --> 18.1-py34_0

Proceed ([y]/n)? y

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/anaconda/win-64/conda-env-2.4.2-py34_0.tar.bz2

How do I get around this NOT FOUND error and install paramiko?

**Comment by ilanschnell** [comment]
There is no need to use the special binstar URL.  Using
```
conda install -c paramiko
```
should work.

**Comment by asmeurer** [comment]
Worth noting that the binstar site itself says to use the full url.
