### ISSUE TITLE
Verify_ssl doesn't expand paths

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1566]
#1432, #1387 Added a SSL Root CA Certs option but it doesn't expand paths like ~bkreider.  Now that it can be a filename, it should expand the string when it is treating it as a filename like it does for other settings.

**Comment by ilanschnell** [comment]
I wouldn't call this a bug, but an enhancement.

**Comment by asmeurer** [comment]
ssl_verify is passed directly to requests, so this should probably be considered an upstream issue with them.

**Comment by bkreider** [comment]
That might be true, but we can easily solve it right now.

**Comment by ilanschnell** [comment]
This should be fixed upstream in requests.  Closing issue.

**Comment by bkreider** [comment]
I'm confused as to why we think requests should expand the path?  It has a contract where it accepts a string that is a full system path.  I'm not sure requests should assume that it is an expandable path, but our software can reasonably assume that CA roots might be in a user's home directory.
