### ISSUE TITLE
Cannot have patch under Windows and Python 3

### ISSUE THREAD

**Issue by pitrou** [conda/conda#1568]
First `conda build` instructs me to install the patch executable on Windows, because my recipe uses a patch file:

```
    You can install 'patch' using apt-get, yum (Linux), Xcode (MacOSX),
    or conda, cygwin (Windows),
```

So I try to install it using conda and boom:

```
Z:\llvmlite>conda install patch
Fetching package metadata: ........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - patch
  - python 3.4*

Use 'conda info patch' etc. to see the dependencies for each package.
```

**Comment by asmeurer** [comment]
The patch package on Windows is not a very good one. I recommend installing http://gnuwin32.sourceforge.net/packages/patch.htm. Not sure why we haven't made a conda package out of that yet.

**Comment by groutr** [comment]
We have made a package of gnuwin32 coreutils.  I don't know if coreutils includes patch or not.  If not, we can update the package.

**Comment by asmeurer** [comment]
Whatever package contains patch should be made as a dependency of conda-build on Windows.

**Comment by kalefranz** [comment]
At this point I'm guessing something like `conda install m2-patch` will have you covered.
