### ISSUE TITLE
Config docs readibility

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1569]
I'm having trouble finding all of the .condarc options in one place.  I think the documentation lags behind the features here.

**Comment by asmeurer** [comment]
Everything should be at http://conda.pydata.org/docs/config.html

**Comment by bkreider** [comment]
I guess i'll maintain my own easy to read documentation externally.

**Comment by asmeurer** [comment]
If there are readability issues please let us know. CC @electronwill @kerrywatson1

**Comment by electronwill** [comment]
@bkreider we definitely want a single public documentation that's complete and readable. Is that page missing any .condarc options, or is it strictly the readability that you'd like to see changed?

**Comment by electronwill** [comment]
http://conda.pydata.org/docs/config.html links to a very brief sample config file at http://conda.pydata.org/docs/install/sample-condarc.html and we could also link to a longer sample config file such as the one at https://docs.google.com/document/d/1v2-dum_aZLZgCGKDvBY8yn-wkrBZqQ29AxZ6oz7zsQ0/edit .

http://conda.pydata.org/docs/config.html seems to show 13 options: channels, always_yes, show_channel_urls, changeps1, use_pip, proxy_servers, offline, allow_softlinks, channel_alias, create_default_packages, track_features, binstar_upload, conda-build.

https://docs.google.com/document/d/1v2-dum_aZLZgCGKDvBY8yn-wkrBZqQ29AxZ6oz7zsQ0/edit seems to have those 13 and 4 more: ssl_verify, disallow, add_binstar_token, envs_dirs .

**Comment by asmeurer** [comment]
Those are the ones we put in the admin page http://conda.pydata.org/docs/install/central.html

**Comment by electronwill** [comment]
Thank you, Aaron! I see the admin page also has allow_other_channels, and uses add_anaconda_token instead of add_binstar_token. (That reminds me that binstar_upload on the config.html page needs to become anaconda_upload-- I'll go ahead and do that.)

**Comment by bkreider** [comment]
Thanks, electronwill.  I'd love to see the brief sample supplemented with the "everything" config file.  Maybe move the "table of contents" to the very top.  After reading the page a few times, I mainly go back for a reference to look up one option.

Sometimes it is easier having a concise list of all options versus reading through paragraphs of text.  The text is very nice, but you have to read through all of it.

**Comment by asmeurer** [comment]
Maybe it would help if the table of contents were moved up on the page.

**Comment by asmeurer** [comment]
FWIW I've also noticed this issue, both on the config page and the recipe reference page.

**Comment by electronwill** [comment]
Yeah, looking at it, I agree about moving the TOC to the very top, and maybe adding the channel name in parenthesis to each link.

**Comment by kerrywatson1** [comment]
The docs are being completely overhauled over the next few months, this is one of many items we will address. @bkreider

**Comment by electronwill** [comment]
https://github.com/conda/conda-docs/pull/202 should fix these problems. Please tell me if anything further is needed to close this issue.
