### ISSUE TITLE
numpydoc=0.5 contains embedded sphinx=1.2.3

### ISSUE THREAD

**Issue by Korijn** [conda/conda#1584]
When creating an environment like this:

`conda create -n testenv python=2.7 sphinx numpydoc`

Conda will install sphinx 1.3.1 and numpydoc 0.5 just fine.

However, the environment will have both sphinx 1.2.3 and sphinx 1.3.1 in the site-packages, and if you import sphinx you'll get 1.2.3.  Apparently the 1.2.3 version is embedded within numpydoc!

Here's a fixed version: https://anaconda.org/prkrekel/numpydoc

**Comment by asmeurer** [comment]
@ilanschnell @groutr this is a problem with the Anaconda numpydoc package.

**Comment by ilanschnell** [comment]
Yes, I see now.  Let me fix the numpydoc package.

**Comment by ilanschnell** [comment]
The fix numpydoc is available.

**Comment by Korijn** [comment]
Thanks for the quick resolution guys!
