### ISSUE TITLE
Feature Request: version check

### ISSUE THREAD

**Issue by Korijn** [conda/conda#1586]
It cost me two hours to understand why `import sphinx; print sphinx.__version__` printed `1.2.3` while `conda list` indicated `sphinx 1.3.1` in issue #1584.

This type of problem could be prevented by testing if the two mentioned versions match.

I'd like to request such a test to be included in conda, to prevent more time being wasted on this kind of issue, as it is bound to come up more often. If necessary, I can create a PR for this feature, but I'd need to be pointed in the right direction first.

**Comment by asmeurer** [comment]
How exactly do you see the feature working?

**Comment by Korijn** [comment]
Well, since packages expose their version in different ways, it would need to be possible supply a method that extracts the version from the package in the conda build recipe.

Then, when a package is installed, you can compare the version from the conda package metadata with the version that is returned using the version extraction method, if it was supplied during the package build.

That's about it, it's not much special. It's just a safeguard.

**Comment by Korijn** [comment]
I can give an example of the feature at work for the faulty numpydoc package mentioned in #1584.

The numpydoc package has a run-time requirement for sphinx. When conda-build is running, it will create an environment with the package being built (numpydoc) installed together with it's dependencies (which includes sphinx). This environment is used to perform import tests, which I guess only checks if the package can be imported without raising an exception.

I propose to add the following steps to the import testing step:

For each package in the environment:
* grab the version according to `conda list`
* grab the version according to `{package}.__version__` (if the attribute exists)
* if both versions could be collected:
  * assert that the versions match, otherwise packaging has apparently gone wrong

This would have caught the faulty numpydoc package before the upload step.

**Comment by Korijn** [comment]
Should I move this to a conda-build issue.

**Comment by asmeurer** [comment]
If it's something that you see running during conda build (which would definitely be a better way to do it) then yes, it should go in that issue tracker.

**Comment by Korijn** [comment]
See https://github.com/conda/conda-build/issues/586 for the new issue.
