### ISSUE TITLE
Error in function Package.__lt__()

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#1590]
There are two problems in function `Package.__lt__()`

A. The code in [resolve.py:203](https://github.com/conda/conda/blob/master/conda/resolve.py#L203)
```python
            return ((self.norm_version, self.build_number, other.build) <
                    (other.norm_version, other.build_number, self.build))
```
should read
```python
            return ((self.norm_version, self.build_number, self.build) <
                    (other.norm_version, other.build_number, other.build))
```

B. When version numbers do not conform to [PEP 386](https://www.python.org/dev/peps/pep-0386/) (i.e. are not of the form `N.N[.N]+[{a|b|c|rc}N[.N]+][.postN][.devN]` with `N` representing natural numbers), the above comparison fails, and conda falls back to a lexicographic comparison between version strings ([resolve.py:206](https://github.com/conda/conda/blob/master/conda/resolve.py#L206)):
```python
            return ((self.version, self.build_number) <
                    (other.version, other.build_number))
```
This fall-back is a bad choice because it leads to unpleasant surprises when people are not aware of the concept of conforming version numbers. For example
```
1.0.9b < 1.0.10c => True  (both are conforming)
1.0.9b < 1.0.10d => False (1.0.10d is non-conforming)
```
I see two solutions:
* reject non-conforming versions numbers during `conda build`
* implement the fall-back comparison in terms of the rule 'numbers are compared numerically, strings of letters are compared lexicographically'

I highly favor the latter solution.

**Comment by asmeurer** [comment]
The first issue was an intentional workaround for an issue where conda needed to pick the right version. I think the issue has been fixed, so it can probably be made to be what you would expect. 

The second issue is https://github.com/conda/conda/issues/915.

**Comment by asmeurer** [comment]
More info on the first one https://github.com/conda/conda/commit/3cc3ecc662914abe1d98b8d9c4caaa7c932a838e.

**Comment by ukoethe** [comment]
regarding A: I honestly think that the workaround decribed in https://github.com/conda/conda/commit/3cc3ecc662914abe1d98b8d9c4caaa7c932a838e makes things worse. When the underlying issue has been fixed in the meantime, the workaround should really be removed.

regarding B: I think the traditional behavior described in [PEP 386 > Distutils](https://www.python.org/dev/peps/pep-0386/#distutils) would make for a better fall-back. It could be implemented by something along the lines of
```python
version_split = re.findall(r'([0-9]+|[^0-9]+|\.)', version_string)
version_list = [int(k) if k.isdigit() else k for k in version_split if k != '.']
```
Now, `version_list1 < version_list2` will compare correctly.

**Comment by ukoethe** [comment]
See PR https://github.com/conda/conda/pull/1591 for a proposed solution to problem B.

**Comment by ukoethe** [comment]
PR #1591 has been replaced with improved PR #1601

**Comment by asmeurer** [comment]
That was merged.
