### ISSUE TITLE
`conda.install.rm_rf` can't delete old environments in Windows + Python 2.7

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda#1594]
This issue hit me when trying to use `--force` option in `conda env create` (I added this in #102), and it revealed a possible problem with how conda handles links in Windows + Python 2.7.

# Symptom

Trying to delete an environment (not active) from within Python fails because the original file being linked is locked by Windows.

# Context

* Windows
* Python 2.7 (`os.islink` does not work here, which might affect the `rm_rf` function from `conda.install`)

# Reproducing

This command line is enough to reproduce the problem:

```bat
$ conda create -n test pyyaml && python -c "import yaml;from conda.install import rm_rf;rm_rf('C:\\Miniconda\\envs\\test')"
Fetching package metadata: ......

#
# To activate this environment, use:
# > activate test
#

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 204, in rm_rf
    shutil.rmtree(path)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Miniconda\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Acesso negado: 'C:\\Miniconda\\envs\\test\\Lib\\site-packages\\yaml.dll'
```

Note that when I import `pyyaml`, I'm locking file `C:\\Miniconda\\Lib\\site-packages\\yaml.dll` (root environment), but that also prevents me from deleting `C:\\Miniconda\\envs\\test\\Lib\\site-packages\\yaml.dll` (another hard link).

# Solution?

Maybe we should add some improved support for detecting and unlinking hardlinks in Windows with Python 2.7, and handle those cases individually instead of trying to `shutil.rmtree` everything.

Possibly from [jarako.windows](https://bitbucket.org/jaraco/jaraco.windows/src/default/jaraco/windows/filesystem/__init__.py#cl-76) or [ntfs/fs.py](https://github.com/sid0/ntfs/blob/master/ntfsutils/fs.py#L88)

**Comment by campos-ddc** [comment]
A possible solution would to force all conda requirements ( python, pycosat, pyyaml, conda, openssl, requests) to be copied in Windows (never linked).

This might also be enough to remove some code in `install.py` that already has a different behavior when linking python (just need to do the same for the other ones)

**Comment by asmeurer** [comment]
I think it should work to put the trash stuff in `rm_rf`.

**Comment by nicoddemus** [comment]
Curiously, `conda env remove` has no trouble removing the same environment... hmm...

**Comment by campos-ddc** [comment]
@nicoddemus it might not be going through a path that imports `yaml`

**Comment by campos-ddc** [comment]
@asmeurer moving trash to other folders is allowed when the file is 'in use'?

**Comment by Korijn** [comment]
This problem is already semi-solved, except that it's not been wired up in all parts of conda yet. See #1133 and for conda-build see https://github.com/conda/conda-build/pull/521 

I say semi because you could theoretically run out of disk space before the environments actually get removed. But that's certainly an edge case.
