### ISSUE TITLE
"conda update --file pkgs.txt" results in "Error: no package names supplied"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1603]
This is a weird result:

```bash
[root@silver ~]# /opt/wakari/anaconda/bin/conda update -p /opt/wakari/anaconda --file install.txt 
Error: no package names supplied
# If you want to update to a newer version of Anaconda, type:
#
# $ conda update --prefix /opt/wakari/anaconda anaconda

[root@silver ~]# cat install.txt 
bokeh=0.9.2=np19py27_0
```

I thought maybe it was because `install.txt` had version information, so I created `update.txt` without version info and tried again, but same result.

```bash
[root@silver ~]# /opt/wakari/anaconda/bin/conda update -p /opt/wakari/anaconda --file update.txt 
Error: no package names supplied
# If you want to update to a newer version of Anaconda, type:
#
# $ conda update --prefix /opt/wakari/anaconda anaconda

[root@silver ~]# cat update.txt 
bokeh
```

In contrast, doing the same thing but replacing `--file update.txt` with \` ` cat update.txt ` \` worked fine.

But AFAICT, the `--file` option doesn't let me do what the help says it should allow:

```
[root@silver ~]# /opt/wakari/anaconda/bin/conda update -h
...
optional arguments:
  --file FILE           Read package versions from FILE.
```

**Comment by ijstokes** [comment]
Insight/guess: the `--file` option is silently ignored by conda.  If so, that is really confusing and probably a bad idea.

**Comment by asmeurer** [comment]
Does it work if you replace `conda update` with `conda install`?

**Comment by ijstokes** [comment]
yes it does.
