### ISSUE TITLE
anaconda 3.5

### ISSUE THREAD

**Issue by Carreau** [conda/conda#1604]
Hey there, 

Would it be possible to have (a beta of) anaconda with python 3.5. 
Python 3.5 is meant to be release relatively soon, and it would be great
to be able to test libraries while we can still send feedback to CPython team. 

Also ubuntu is trying to get 3.5 in October release, it would be a shame to have incompatible 
python packages.  Having a conda with 3.5 to test would be of great help. 

Thanks,

Ping @mrocklin.

**Comment by mrocklin** [comment]
CC @asmeurer @ilanschnell do you know if there are plans for 3.5 builds before the core release?

I would personally be quite happy with builds for python 3.5, miniconda, and a very small set of core packages (numpy, pandas, sklearn)  It would be nice to have this a bit before Python 3.5 goes widespread (well, as widespread as new releases of Python go anyway.)  

I'm not sure what other developers are doing but I've become so accustomed to depending on Anaconda that changing my testing systems to use anything else feels unpleasant.  

I see value in @Carreau's request but I don't know how hard it is to build the core packages.

**Comment by ccordoba12** [comment]
@ilanschnell and @msarahan are working (internally) to test our packages with Python 3.5.

They're not planning to do a public build before 3.5 final, but AFAIK most packages will be released one or two days after 3.5 is released (which I think is tomorrow :-).

**Comment by ilanschnell** [comment]
We already have Python 3.5.0rc4 available to the public on Unix, as well as most Python 3.5 packages that we officially support.  Tomorrow or Monday, we are going to update to 3.5.0 final and also add Windows.  Also, on Monday we are going to announce the new Python 3.5 support in a blog post.

**Comment by Carreau** [comment]
OK,  awesome thanks !

I saw the python3.5 recipe but fail to find the 3.5rcX env last time I checked. Looking forward to Monday release. Will a be a 3.5 root environment ?

**Comment by ilanschnell** [comment]
Python 3.5 can only be in the root environment once we create Miniconda3 installers based on Python 3.5, which we are going to switch to after the Anaconda 2.4 release.
