### ISSUE TITLE
Travis-CI "Conda" language.

### ISSUE THREAD

**Issue by Carreau** [conda/conda#1605]
Hi there, 

This is a proposal to have a [Travis-CI community supported language](http://docs.travis-ci.com/user/languages/community-supported-languages/) that would be "conda". 

Conda is becoming more and more the way to install Python (and R), and make it particularly easy to have some dependencies that are otherwise hard to build. 

It is [not uncommon](https://github.com/blaze/dask/blob/master/.travis.yml#L14-L25)  to install conda in `.travis.yml` file, I think it would be even greater if one could just say `language:conda`. 

Ping @mrocklin.

**Comment by mrocklin** [comment]
The current docs on how to use travis.ci and conda [live here](http://conda.pydata.org/docs/travis.html).  I've used them to decent benefit.  I see these in many other projects as well.

That being said, it would be pretty slick to just say "I'm using miniconda" or "I'm using anaconda" in travis.ci.

```yaml
python:
  - "miniconda-2.7"
  - "miniconda-3.4"
install:
  - 
```

Interestingly @izaid brought this up in conversation earlier today.

Looking at the process that @Carreau brought up this doesn't look like a particularly onerous process.  It also seems like the sort of thing that Continuum doesn't necessarily need to be in full control over (though clearly some long-term commitment would probably go a long way.)
