### ISSUE TITLE
conda install reports "Error: No packages found" for pkgs that are already installed

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1608]
`ncurses` version `5.9-4` is already installed, so I don't care that it can't be found in any package source.  The error below makes no sense:

``` bash
# /opt/wakari/anaconda/bin/conda list -p /opt/wakari/wakari-compute  | grep ncur
ncurses                   5.9                           4  

[root@gold ~]# /opt/wakari/anaconda/bin/conda install -p /opt/wakari/wakari-compute -c wakari --file wakari-compute-update-latest
Fetching package metadata: ........
Error: No packages found in current linux-64 channels matching: ncurses 5.9 4

Did you mean one of these?

    ncurses

You can search for this package on Binstar with

    binstar search -t conda ncurses 5.9 4
```

The offending entry from the file:

``` bash
[root@gold ~]# grep ncur wakari-compute-update-latest 
ncurses=5.9=4
```

**Comment by asmeurer** [comment]
You should be able to use the `--unknown` flag to fix this.

**Comment by ijstokes** [comment]
@asmeurer are you saying that is a work-around or that is "the right thing to do"? 

And from a different angle, why is this package not found?  What should I have in my `.condarc` as for channels in order to pick up `ncurses=5.9=4`

**Comment by asmeurer** [comment]
`--unknown` is the way to make conda find packages that aren't in the channels. There isn't a condarc option for it but one could be added.

**Comment by ijstokes** [comment]
@asmeurer that wasn't what I meant: I meant "What standard channel is ncurses 5.9 build 4 in?"

**Comment by asmeurer** [comment]
Oh that is coming from the r channel (or my channel; it's the same package).

**Comment by ijstokes** [comment]
Thanks, I think that should help solve the short-term problem.

What do you think about whether this situation should be an error?  If the exact package conda is looking for is already installed then why should it report an error?  I could imagine this happening a lot as users do `conda list -e` and `conda env export` (or whatever the `kapsel` future version of that is) for their environments that have their own custom packages in them.  They'll want to be able to (re-)create or update envs from those package definition files just based on the local package cache *or* add to (effectively an *upsert*) an existing environment based on a package spec file that *possibly* has some overlap with already-installed custom packages.

**Comment by kalefranz** [comment]
I think this ticket is outdated after the 4.0 solver work.
