### ISSUE TITLE
`conda install virtualenv` caused python installation to be removed

### ISSUE THREAD

**Issue by chishaku** [conda/conda#1617]
I ran `conda install virtualenv` and didn't look at the package plan before confirmation.  

It turns out, removing python was part of the package plan.  Not sure why.  Now conda is broken.  

See below:

jeffs-Mac:mkutil jeff$ conda install virtualenv
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/jeff/Dropbox/dot/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.4.2            |           py27_0          24 KB
    setuptools-18.1            |           py27_0         341 KB
    wheel-0.24.0               |           py27_0          75 KB
    conda-3.17.0               |           py27_0         172 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    virtualenv-13.0.1          |           py27_0         1.6 MB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

    virtualenv: 13.0.1-py27_0
    wheel:      0.24.0-py27_0

The following packages will be REMOVED:

    python:     2.7.9-1
    pyyaml:     3.11-py27_0
    requests:   2.6.0-py27_0
    yaml:       0.1.4-1

The following packages will be UPDATED:

    conda:      3.15.1-py27_0 --> 3.17.0-py27_0
    conda-env:  2.3.0-py27_0  --> 2.4.2-py27_0
    pip:        7.1.0-py27_0  --> 7.1.2-py27_0
    setuptools: 18.0.1-py27_0 --> 18.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.4. 100% |#######################################| Time: 0:00:00 626.64 kB/s
setuptools-18. 100% |#######################################| Time: 0:00:00   3.83 MB/s
wheel-0.24.0-p 100% |#######################################| Time: 0:00:00   1.98 MB/s
conda-3.17.0-p 100% |#######################################| Time: 0:00:00   4.25 MB/s
pip-7.1.2-py27 100% |#######################################| Time: 0:00:00   3.62 MB/s
virtualenv-13. 100% |#######################################| Time: 0:00:00   5.07 MB/s
Extracting packages ...
[      COMPLETE      ]|##########################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##########################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################| 100%

**Now conda is broken**

jeffs-Mac:mkutil jeff$ virtualenv env
-bash: /Users/jeff/Dropbox/dot/miniconda/bin/virtualenv: /Users/jeff/Dropbox/dot/miniconda/bin/python: bad interpreter: No such file or directory
`

**Comment by ilanschnell** [comment]
I cannot reproduce this.  Which version of Miniconda did you begin with?

**Comment by chishaku** [comment]
Not sure the best way to determine the version since the `conda` command is broken without the python interpreter.  

The packages present in `conda/pkgs` are:

 conda-3.10.0-py27_0
conda-3.10.0-py27_0.tar.bz2
conda-3.15.1-py27_0
conda-3.15.1-py27_0.tar.bz2
conda-3.17.0-py27_0
conda-3.17.0-py27_0.tar.bz2
conda-3.7.0-py27_0
conda-3.7.3-py27_0
conda-3.7.3-py27_0.tar.bz2
conda-3.7.4-py27_0
conda-3.7.4-py27_0.tar.bz2

I doubt that helps to narrow it down much.
