### ISSUE TITLE
error msg for ipython-qtconsole updated

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda#1620]
The error below happened after updating the qtconsole from the launcher. Seems the update worked though.

ipython-qtconsole updated.

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 265, in install
    m['name'] == name]
TypeError: 'NoneType' object has no attribute '**getitem**'

(bjorn)bjorn@bjorn-ThinkPad-T450s:~$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.17.0
```

  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/bjorn/anaconda  (writable)
  default environment : /home/bjorn/anaconda/envs/bjorn
     envs directories : /home/bjorn/anaconda/envs
        package cache : /home/bjorn/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/BjornFJohansson/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/BjornFJohansson/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/bjorn/.condarc
    is foreign system : False

(bjorn)bjorn@bjorn-ThinkPad-T450s:~$ 

(bjorn)bjorn@bjorn-ThinkPad-T450s:~$ conda list
# packages in environment at /home/bjorn/anaconda/envs/bjorn:
# 

_license                  1.1                      py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.0.0                np18py27_0  
appdirs                   1.4.0                    py27_1  
apptools                  4.2.1                    py27_0  
argcomplete               0.6.7                    py27_0  
astroid                   1.3.4                    py27_0  
astropy                   1.0.3                np19py27_0  
atom                      0.3.7                    py27_0  
babel                     1.3                      py27_0  
backports.functools-lru-cache 1.0.1                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports.ssl_match_hostname 3.4.0.2                  py27_0  
beautiful-soup            4.3.1                    py27_0  
beautifulsoup4            4.3.1                     <pip>
binstar                   0.11.0                   py27_0  
binstar-build             0.10.5                    <pip>
biopython                 1.65                 np19py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.5.0                np18py27_0  
blz                       0.6.2                np18py27_0  
bokeh                     0.4.4                np18py27_1  
boto                      2.28.0                   py27_0  
bsddb                     1.0                      py27_0  
cairo                     1.12.18                       4  
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
chaco                     4.4.1                np18py27_0  
cloog                     0.18.0                        0  
clyent                    0.3.4                    py27_0  
colorama                  0.2.7                    py27_0  
conda-build               1.3.1                    py27_0  
configobj                 5.0.5                    py27_0  
coverage                  3.7.1                    py27_0  
cubes                     0.10.2                   py27_4  
curl                      7.30.0                        0  
cython                    0.20.1                   py27_0  
datashape                 0.2.0                np18py27_1  
dateutil                  2.1                      py27_2  
db                        5.3.28                        0  
decorator                 4.0.2                    py27_0  
disco                     0.4.4                    py27_0  
docopt                    0.6.2                    py27_0  
docutils                  0.12                     py27_0  
docutils-htmlwriter       0.1                       <pip>
dynd-python               0.6.2                np18py27_0  
enable                    4.3.0                np18py27_2  
enaml                     0.9.1                    py27_1  
envisage                  4.4.0                    py27_1  
erlang                    R15B01                        0  
ezodf                     0.2.5                     <pip>
flask                     0.10.1                   py27_1  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
future                    0.12.1                   py27_0  
gcc                       4.8.3                         1  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
gevent-zeromq             0.2.2                     <pip>
gevent_zeromq             0.2.5                    py27_3  
gistapi                   0.2.4                     <pip>
glob2                     0.4.1                     <pip>
glueviz                   0.5.1                np19py27_0  
gluttony                  0.8                       <pip>
gmp                       5.1.2                         2  
greenlet                  0.4.2                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.3.0                np18py27_0  
hdf5                      1.8.9                         1  
ipykernel                 4.0.3                    py27_0  
ipython                   4.0.0                    py27_0  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0  
isl                       0.12.2                        0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.9.0                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py27_0  
jupyter-client            4.0.0                     <pip>
jupyter-core              4.0.4                     <pip>
jupyter_client            4.0.0                    py27_0  
jupyter_core              4.0.4                    py27_0  
keyring                   3.3                      py27_0  
kiwisolver                0.1.2                    py27_0  
launcher                  1.0.0                         1  
lcms                      1.19                          0  
libdynd                   0.6.2                         0  
libgfortran               1.0                           0  
libnetcdf                 4.2.1.1                       1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvm                      3.3                           0  
llvmpy                    0.12.4                   py27_0  
logilab-common            0.63.2                   py27_0  
lxml                      3.3.5                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_2  
mayavi                    4.3.1                np18py27_0  
mdp                       3.3                  np18py27_0  
mistune                   0.7.1                    py27_0  
mock                      1.0.1                    py27_0  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
mpi4py                    1.3                      py27_0  
mpich2                    1.4.1p1                       0  
multipledispatch          0.4.3                    py27_0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.0                    py27_0  
ncurses                   5.9                           5  
netcdf4                   1.0.8                np18py27_0  
networkx                  1.9.1                    py27_0  
nltk                      2.0.4                np18py27_0  
node-webkit               0.11.5                        0  
nose                      1.3.3                    py27_0  
notebook                  4.0.1                    py27_0  
notedown                  1.4.4                    py27_0  
numba                     0.13.1               np18py27_0  
numexpr                   2.3.1                np18py27_0  
numpy                     1.9.2                    py27_1  
numpydoc                  0.4                      py27_0  
openblas                  0.2.14                        1  
opencv                    2.4.6                np18py27_0  
openpyxl                  2.0.2                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
pandoc-attributes         0.1.7                    py27_0  
pandocfilters             1.2.4                    py27_0  
patchelf                  0.6                           0  
path.py                   7.6                      py27_0  
patsy                     0.2.1                np18py27_0  
pep8                      1.6.2                    py27_0  
percache                  0.3.0                     <pip>
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pil                       1.1.7                    py27_1  
pillow                    2.9.0                    py27_0  
pip                       7.1.2                    py27_0  
pixman                    0.26.2                        0  
pkginfo                   1.2.1                     <pip>
ply                       3.4                      py27_0  
prettytable               0.7.2                    py27_0  
proxychecker              0.0.2                     <pip>
psutil                    2.1.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.26                   py27_0  
py2cairo                  1.10.0                   py27_2  
pycallgraph               1.0.1                     <pip>
pycosat                   0.6.1                    py27_0  
pycparser                 2.10                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.3.1                 py27_2  
pydna                     0.8.4                     <pip>
pyface                    4.4.0                    py27_0  
pyflakes                  0.9.2                    py27_0  
pyglet                    1.1.4                     <pip>
pygments                  2.0.2                    py27_0  
pygraphviz                1.2                       <pip>
pykit                     0.2.0                np18py27_0  
pylint                    1.4.2                    py27_0  
pylzma                    0.4.4                     <pip>
pypandoc                  0.9.9                     <pip>
pyparsing                 2.0.3                    py27_0  
pypdf2                    1.22                      <pip>
pyqt                      4.11.3                   py27_1  
pysal                     1.6.0                np18py27_1  
pysam                     0.6                      py27_0  
pyside                    1.2.1                    py27_0  
pytables                  3.1.1                np18py27_0  
pytest                    2.6.4                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_0  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
qtconsole                 4.0.1                    py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.9.1                    py27_0  
regex                     2014.6.28                 <pip>
reportlab                 3.1.8                    py27_0  
requests                  2.7.0                    py27_0  
rope                      0.9.4                    py27_1  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.14.1               np18py27_1  
scipy                     0.15.1               np19py27_0  
setuptools                18.1                     py27_0  
setuptools-markdown       0.2                       <pip>
shiboken                  1.2.1                    py27_0  
simplegeneric             0.8.1                    py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snakefood                 1.4                       <pip>
snowballstemmer           1.2.0                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.6                    py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                0.9.4                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.5.0                np18py27_0  
sympy                     0.7.5                    py27_0  
system                    5.8                           2  
tables                    3.1.1                     <pip>
terminado                 0.5                      py27_0  
testfixtures              4.1.2                     <pip>
theano                    0.6.0                np18py27_0  
tk                        8.5.18                        0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
twine                     1.5.0                     <pip>
ujson                     1.33                     py27_0  
util-linux                2.21                          0  
versioneer                0.15                      <pip>
vtk                       5.10.1                   py27_1  
wand                      0.3.8                     <pip>
werkzeug                  0.9.4                    py27_0  
wheel                     0.24.0                   py27_0  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.5.5                    py27_0  
xlwt                      0.7.5                    py27_0  
yaml                      0.1.4                         0  
ypkpathway (/home/bjorn/python_packages/ypkpathway) 0.9.0                     <pip>
zen-library               0.9                       <pip>
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
(bjorn)bjorn@bjorn-ThinkPad-T450s:~$

**Comment by kalefranz** [comment]
Report is for conda 3.17.0.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.
