### ISSUE TITLE
conda env on windows 8 not working

### ISSUE THREAD

**Issue by callmeskywalker** [conda/conda#1622]
I'm sure I am missing something stupid. 

In windows powershell:

    conda create --name kyle flask
    Fetching package metadata: ....
    Solving package specifications: .
    Package plan for installation in environment C:\Users\Jo\Anaconda\envs\kyle:

    The following NEW packages will be INSTALLED:

    flask:        0.10.1-py27_1
    itsdangerous: 0.24-py27_0
    jinja2:       2.8-py27_0
    markupsafe:   0.23-py27_0
    pip:          7.1.2-py27_0
    python:       2.7.10-1
    setuptools:   18.1-py27_0
    werkzeug:     0.10.4-py27_0
    wheel:        0.24.0-py27_0

    Proceed ([y]/n)? y

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    #
    # To activate this environment, use:
    # > activate kyle
    #
    PS C:\Users\Jo> activate kyle
    Activating environment "kyle"...
    PS C:\Users\Jo> conda env list
    # conda environments:
    #
    kyle                     C:\Users\Jo\Anaconda\envs\kyle
    venv                     C:\Users\Jo\Anaconda\envs\venv
    root                  *  C:\Users\Jo\Anaconda

Clearly I am still in the root environment. I have also tried doing this in Cygwin. Which would be the preferred location to get things working.

Here is the relevant part of my .bashrc in Cygwin.

    export PATH=/cygdrive/c/users/jo/anaconda:$PATH
    export PATH=/cygdrive/c/users/jo/anaconda/scripts:$PATH
    export PATH=/cygdrive/c/users/jo/anaconda/envs/venv:$PATH

Here is the behavior in cygwin:

    Jo@Monk ~
    $ activate.bat venv
    Activating environment "venv"...
    $ conda env list
    # conda environments:
    #
    kyle                     C:\users\jo\anaconda\envs\kyle
    venv                     C:\users\jo\anaconda\envs\venv
    root                  *  C:\users\jo\anaconda

`activate` is recognized in powershell, but not in cygwin. `activate.bat` is recognized in cygwin as well as powershell.

I cannot switch to the environments either way. Using native windows powershell or cygwin terminal.

**Comment by willyd** [comment]
`conda activate` is known to be broken in Powershell. See: https://github.com/conda/conda/issues/626.

**Comment by callmeskywalker** [comment]
The problem is that I was trying to use a Windows install of Anaconda through a Cygwin terminal. This cannot be done, as far as I know. If using Cygwin, one needs to install a Linux version of Anaconda in Cygwin.
