### ISSUE TITLE
Upgraded from Python 2.7.2 -> 2.7.9, SSL Certificate Nightmare

### ISSUE THREAD

**Issue by vgoklani** [conda/conda#1624]
I just upgraded to Python 2.7.9, and I'm getting all these SSL errors:

```
conda install python=2.7.7
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

I already own an SSL certificate, how do I point conda/python to the location of the .crt file? 

I'm running this on Ubuntu and using the latest version of Anaconda.

**Comment by asmeurer** [comment]
It's likely an issue of configuring the conda `openssl`.

**Comment by vgoklani** [comment]
not sure what that means, could you please be more specific

**Comment by bkreider** [comment]
Each one of those errors is a channel (.condarc) using HTTPS that is not being validated properly.  Can you do a `conda info -a` and post the results?  There is a .condarc option to specify your RootCA path, but I can't remember it off the top of my head.  @asmeurer do you remember the option name?  It was something like "validate_certs" and it has been turned from a boolean to being able to accept a path to your RootCA. 

Are you going through some kind of SSL reverse-proxy that is forging the SSL certs?  Normally cert validation should work just fine with the CARoots bundled either with your OS or inside Anaconda.

**Comment by vgoklani** [comment]
conda info -a
  Current conda install:

               platform : linux-64
          conda version : 3.17.0
    conda-build version : 1.8.2
         python version : 2.7.10.final.0
       requests version : 2.7.0
       root environment : /opt/anaconda  (writable)
    default environment : /opt/anaconda
       envs directories : /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
      is foreign system : False

  # conda environments:
  #
  root                  *  /opt/anaconda

  sys.version: 2.7.10 |Anaconda 2.3.0 (64-bit)| (defaul...
  sys.prefix: /opt/anaconda
  sys.executable: /opt/anaconda/bin/python
  conda location: /opt/anaconda/lib/python2.7/site-packages/conda
  conda-build: /opt/anaconda/bin/conda-build
  conda-convert: /opt/anaconda/bin/conda-convert
  conda-develop: /opt/anaconda/bin/conda-develop
  conda-env: /opt/anaconda/bin/conda-env
  conda-index: /opt/anaconda/bin/conda-index
  conda-metapackage: /opt/anaconda/bin/conda-metapackage
  conda-pipbuild: /opt/anaconda/bin/conda-pipbuild
  conda-server: /opt/anaconda/bin/conda-server
  conda-skeleton: /opt/anaconda/bin/conda-skeleton
  user site dirs:

  CIO_TEST: <not set>
  CONDA_DEFAULT_ENV: <not set>
  CONDA_ENVS_PATH: <not set>
  LD_LIBRARY_PATH: <not set>
  PATH: /opt/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  PYTHONHOME: <not set>
  PYTHONPATH: /root/metricle/src

  License directories:
      /opt/anaconda/licenses
      /root/.continuum
  License files (license*.txt):
  Package/feature end dates:

**Comment by ilanschnell** [comment]
Is there a specific reason you have the `PYTHONPATH` environment variables set?  What Python packages (or modules) do you have in `/root/metricle/src`?

**Comment by fspaolo** [comment]
I am having the same problem. I did upgrade recently my OSX (10.6 => 10.10). See full message below:

```shell
$ conda install blaze
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
..
Solving package specifications: ........................
Package plan for installation in environment /Users/fpaolo/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    decorator-4.0.4            |           py27_0          11 KB
    multipledispatch-0.4.8     |           py27_0          11 KB
    psutil-3.2.2               |           py27_0          99 KB
    pymongo-3.0.3              |           py27_0         241 KB
    sqlalchemy-1.0.8           |           py27_0         1.3 MB
    toolz-0.7.4                |           py27_0          51 KB
    bcolz-0.11.3               |           py27_0         378 KB
    h5py-2.5.0                 |      np110py27_3         711 KB
    llvmlite-0.7.0             |           py27_3         6.4 MB
    networkx-1.10              |           py27_0         1.1 MB
    numexpr-2.4.4              |      np110py27_0         103 KB
    singledispatch-3.4.0.3     |           py27_0          12 KB
    datashape-0.4.7            |           py27_0          80 KB
    numba-0.21.0               |      np110py27_0         1.2 MB
    pytables-3.2.2             |      np110py27_0         1.6 MB
    odo-0.3.4                  |           py27_0         159 KB
    blaze-core-0.8.3           |           py27_0         503 KB
    blaze-0.8.3                |           py27_0          369 B
    ------------------------------------------------------------
                                           Total:        13.8 MB

The following NEW packages will be INSTALLED:

    singledispatch:   3.4.0.3-py27_0    

The following packages will be UPDATED:

    bcolz:            0.9.0-np19py27_0  --> 0.11.3-py27_0     
    blaze:            0.6.3-np19py27_0  --> 0.8.3-py27_0      
    blaze-core:       0.8.0-np19py27_0  --> 0.8.3-py27_0      
    datashape:        0.4.5-np19py27_0  --> 0.4.7-py27_0      
    decorator:        4.0.2-py27_0      --> 4.0.4-py27_0      
    h5py:             2.5.0-np19py27_3  --> 2.5.0-np110py27_3 
    llvmlite:         0.5.0-py27_0      --> 0.7.0-py27_3      
    multipledispatch: 0.4.7-py27_0      --> 0.4.8-py27_0      
    networkx:         1.9.1-py27_0      --> 1.10-py27_0       
    numba:            0.19.1-np19py27_0 --> 0.21.0-np110py27_0
    numexpr:          2.4.3-np19py27_0  --> 2.4.4-np110py27_0 
    odo:              0.3.2-np19py27_0  --> 0.3.4-py27_0      
    psutil:           2.2.1-py27_0      --> 3.2.2-py27_0      
    pymongo:          2.8-py27_0        --> 3.0.3-py27_0      
    pytables:         3.2.0-np19py27_0  --> 3.2.2-np110py27_0 
    sqlalchemy:       1.0.5-py27_0      --> 1.0.8-py27_0      
    toolz:            0.7.2-py27_0      --> 0.7.4-py27_0      

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/osx-64/decorator-4.0.4-py27_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/osx-64/decorator-4.0.4-py27_0.tar.bz2
```

And

```shell
$ conda info -a
Current conda install:

             platform : osx-64
        conda version : 3.18.1
  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.8.0
     root environment : /Users/fpaolo/anaconda  (writable)
  default environment : /Users/fpaolo/anaconda
     envs directories : /Users/fpaolo/anaconda/envs
        package cache : /Users/fpaolo/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/fpaolo/.condarc
    is foreign system : False

# conda environments:
#
root                  *  /Users/fpaolo/anaconda

sys.version: 2.7.10 |Anaconda 2.3.0 (x86_64)| (defaul...
sys.prefix: /Users/fpaolo/anaconda
sys.executable: /Users/fpaolo/anaconda/bin/python
conda location: /Users/fpaolo/anaconda/lib/python2.7/site-packages/conda
conda-build: /Users/fpaolo/anaconda/bin/conda-build
conda-convert: /Users/fpaolo/anaconda/bin/conda-convert
conda-develop: /Users/fpaolo/anaconda/bin/conda-develop
conda-env: /Users/fpaolo/anaconda/bin/conda-env
conda-index: /Users/fpaolo/anaconda/bin/conda-index
conda-metapackage: /Users/fpaolo/anaconda/bin/conda-metapackage
conda-pipbuild: /Users/fpaolo/anaconda/bin/conda-pipbuild
conda-server: /Users/fpaolo/anaconda/bin/conda-server
conda-skeleton: /Users/fpaolo/anaconda/bin/conda-skeleton
user site dirs: ~/.local/lib/python2.7
                ~/.local/lib/python3.3
                ~/.local/lib/python3.4

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: /usr/OpenMotif/lib
PATH: /Applications/Julia-0.4.0-rc4.app/Contents/Resources/julia/bin:/Users/fpaolo/anaconda/bin:/usr/local/grace/bin:/usr/OpenMotif/bin:/Library/PostgreSQL/9.2/bin:/Library/Frameworks/GDAL.framework/Versions/Current/unix/bin:/usr/local/cuda/bin:/opt/local/sbin:/opt/local/bin:/opt/local/lib/gmt4/bin:/Library/Frameworks/Canopy.framework/bin:/Library/Frameworks/EPD64.framework/Versions/Current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/sw/bin:/sw/sbin:/Applications/MATLAB_R2015a.app/bin:/Applications/MATLAB_R2014b.app/bin:/Applications/MATLAB_R2007b/bin:/usr/X11/bin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin
PYTHONHOME: <not set>
PYTHONPATH: /Library/Frameworks/GDAL.framework/Versions/Current/Python/site-packages:

License directories:
    /Users/fpaolo/.continuum
    /Users/fpaolo/Library/Application Support/Anaconda
    /Users/fpaolo/anaconda/licenses
License files (license*.txt):
Package/feature end dates:
```

**Comment by vgoklani** [comment]
Exactly! Please let me know if you find a solution

**Comment by linkTDP** [comment]
For me `<conda update requests>` solved the issue.

**Comment by fspaolo** [comment]
Didn't solve the issue for me.

```Shell
$ conda update requests
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
....
# All requested packages already installed.
# packages in environment at /Users/fpaolo/anaconda:
#
requests                  2.8.0                    py27_0  
```

**Comment by gcwenger** [comment]
What worked for me (based on reading: https://github.com/conda/conda/issues/1166) was to do this:
```
$ conda remove certifi
$ conda update requests
$ conda install certifi
```

**Comment by fspaolo** [comment]
nope

**Comment by gcwenger** [comment]
What version of openssl is installed for you? After doing the 'conda update requests' it took me to openssl-1.0.2d.

**Comment by QuLogic** [comment]
What I've found is that conda doesn't actually update the metadata when that error occurs, so it doesn't notify you of the _actual_ latest version available. I didn't find a way to download the metadata in a browser (which would check the SSL cert properly), so I had to temporarily disable SSL verification. That is,
```
$ conda config --set ssl_verify False
$ conda update requests openssl
$ conda config --set ssl_verify True
```
Make sure to do that in the root environment.

**Comment by fspaolo** [comment]
This is what I have:

openssl                   1.0.1k

And of course, conda doesn't let me update it (for the same reason as
before).



On Sun, Oct 25, 2015 at 8:28 PM, gcwenger <notifications@github.com> wrote:

> What version of openssl is installed for you? After doing the 'conda
> update requests' it took me to openssl-1.0.2d.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1624#issuecomment-151013667>.
>



-- 
Fernando Paolo
Institute of Geophysics & Planetary Physics
Scripps Institution of Oceanography
University of California, San Diego

web: fspaolo.net

**Comment by gcwenger** [comment]
Go w/ QuLogic's suggestion. I should have specified updating openssl while certifi was uninstalled. Disabling ssl_verify temporarily is another way to go to get the initial update to work.

**Comment by fspaolo** [comment]
Excellent suggestion. Disabling `ssl_verify` to update `openssl` (1.0.1k-1 --> 1.0.2d-0) worked fine. Now everything is back to normal. Many thanks!

**Comment by gcwenger** [comment]
Good to hear. (Looking at your profile I see you're SD - which funny enough is where I live too).

**Comment by flaviobarros** [comment]
I was having the same problem (Linux Debian Jessie) and this procedure worked:

```
$ conda config --set ssl_verify False
$ conda update requests openssl
$ conda config --set ssl_verify True
```

OBS: Thanks to QuLogic

**Comment by fspaolo** [comment]
The question is: is this a work around or the standard conda procedure?

(yes, thanks to @QuLogic and @gcwenger)

**Comment by ilovepandas** [comment]
I run:
$ conda config --set ssl_verify False
$ conda install openssl
$ conda update requests openssl
$ conda config --set ssl_verify True
and removes issue but now 'openss;' has unsatisfiable dependency when running conda update --all and not possible to remove openssl.

Any suggestions?

            platform : win-64
       conda version : 3.18.3
 conda-build version : 1.18.1
      python version : 3.4.3.final.0
    requests version : 2.8.1
    root environment : C:\Users\xxx\AppData\Local\Continuum\Anaconda3  (writable)
 default environment : C:\Users\xxx\AppData\Local\Continuum\Anaconda3
    envs directories : C:\Users\xxx\AppData\Local\Continuum\Anaconda3\envs
       package cache : C:\Users\xxx\AppData\Local\Continuum\Anaconda3\pkgs
        channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                       https://repo.continuum.io/pkgs/free/noarch/
                       https://repo.continuum.io/pkgs/pro/win-64/
                       https://repo.continuum.io/pkgs/pro/noarch/
         config file : C:\Users\xxx\AppData\Local\Continuum\Anaconda3\.condarc
   is foreign system : Falseintranet.nrk.com:8080

**Comment by KelseyJustis** [comment]
This worked for me:

1: conda config --set ssl_verify false
2: conda update requests
3: conda config --set ssl_verify true

Used last line to reset change I made (just in case/don't really know what I am doing)
