### ISSUE TITLE
py.test 2.7.3+ required for Python 3.5

### ISSUE THREAD

**Issue by jiffyclub** [conda/conda#1634]
Conda currently ships py.test 2.7.2 as the latest version, but that version doesn't work with Python 3.5. I've confirmed that py.test 2.8 does work, and according to the [py.test release notes](http://pytest.org/latest/changelog.html#compared-to-2-7-2) version 2.7.3 should work as well.

**Comment by ilanschnell** [comment]
Thanks for the feedback.  We are going to update py.test before the next Anaconda release which will have full Python 3.5 support.

**Comment by asmeurer** [comment]
We should update it soon.

**Comment by ilanschnell** [comment]
I just updated to pytest 2.8.0
