### ISSUE TITLE
Using system install of conda

### ISSUE THREAD

**Issue by opoplawski** [conda/conda#1643]
I'm experimenting with using a system install of conda/conda-env in /usr/bin.  The problem I'm running into is:
~~~~~
$ source /opt/anaconda/envs/scipy/bin/activate /opt/anaconda/envs/scipy
discarding /usr/bin from PATH
prepending /opt/anaconda/envs/scipy/bin to PATH
~~~~~
In this situation we don't really have a "root" environment, or at least not one managed by conda.  I know this a strange use case, but I think a potentially useful one.

**Comment by opoplawski** [comment]
Some motivation: http://orionlibre.blogspot.com/2015/09/using-system-installed-conda.html

**Comment by ilanschnell** [comment]
Thanks for pointing this out.  I understand what you're trying to do.  In that case, I would not use conda's `activate`, but change `PATH` and `CONDA_DEFAULT_ENV` by some other means.
