### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Flaviolib** [conda/conda#1645]
I see may posts on forums about it, but no one could help me to solve my problem.
I'm not a Python pro

I'm having this certificate problem using conda and pip. conda for all packages and pip for some.

this is my conda info -a:

Current conda install:

```
         platform : win-64
    conda version : 3.17.0
```

  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : C:\Users\Flavio\Anaconda3  (writable)
  default environment : C:\Users\Flavio\Anaconda3
     envs directories : C:\Users\Flavio\Anaconda3\envs
        package cache : C:\Users\Flavio\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
# conda environments:
# 

root                  \*  C:\Users\Flavio\Anaconda3

sys.version: 3.4.3 |Anaconda 2.3.0 (64-bit)| (default...
sys.prefix: C:\Users\Flavio\Anaconda3
sys.executable: C:\Users\Flavio\Anaconda3\python.exe
conda location: C:\Users\Flavio\Anaconda3\lib\site-packages\conda-3.17.0-py3.4.egg\conda

conda-build: C:\Users\Flavio\Anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\Flavio\Anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\Flavio\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\Flavio\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\Flavio\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\Flavio\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\Flavio\Anaconda3\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\Flavio\Anaconda3\Scripts\conda-pipbuild.exe
conda-server: C:\Users\Flavio\Anaconda3\Scripts\conda-server.exe
conda-sign: C:\Users\Flavio\Anaconda3\Scripts\conda-sign.exe
conda-skeleton: C:\Users\Flavio\Anaconda3\Scripts\conda-skeleton.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Ruby22\bin;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\AMD APP\b
in\x86_64;c:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windo
ws\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\ATI
Technologies\ATI.ACE\Core-Static;C:\Program Files\Dell\Dell Data Protection\Access\Advan
ced\Wave\Gemalto\Access Client\v5\;C:\Program Files (x86)\Security Innovation\SI TSS\bin
\;C:\blp\API;C:\blp\API\dde;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Progr
am Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\
bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Microsoft S
QL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\12
0\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Bin
n\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsof
t SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance T
oolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Mic
rosoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Window
s\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program
 Files (x86)\Skype\Phone\;C:\Users\Flavio\Anaconda3;C:\Users\Flavio\Anaconda3\Scripts;C:
\blp\API;C:\blp\API\dde
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\Users\Flavio.continuum
    C:\Users\Flavio\Anaconda3\licenses
    C:\Users\Flavio\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

**Comment by Flaviolib** [comment]
any luck?

**Comment by kalefranz** [comment]
Report is for conda 3.17.0.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.
