### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] python 3.4 enviroment

### ISSUE THREAD

**Issue by FrancescElies** [conda/conda#1646]
Hi,

I saw other issues with similar problems but I could not find out exactly what's going on.
While creating an environment with python 3.4 works fine `conda create --yes -p env3.3 --use-index-cache python=3.3 pip` but once I try to make the same for python 3.4 fails

```
$ conda create --yes -p env3.4 --use-index-cache python=3.4 pip
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /home/xesc/src/bcolz/env3.4:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.26.0               |           py34_0          77 KB

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1     
    pip:        7.1.2-py34_0 
    python:     3.4.3-1      
    readline:   6.2-2        
    setuptools: 18.1-py34_0  
    sqlite:     3.8.4.1-1    
    system:     5.8-2        
    tk:         8.5.18-0     
    wheel:      0.26.0-py34_0
    xz:         5.0.5-0      
    zlib:       1.2.8-0      

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/wheel-0.26.0-py34_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/linux-64/wheel-0.26.0-py34_0.tar.bz2
```

Am I doing something wrong?

Thanks in advance for your help.
Regards

**Comment by bjodah** [comment]
I experienced problems with this today, when trying to do a fresh install of miniconda/anaconda.
Here's the work around for me:
```
$ conda config --set ssl_verify false
```
which obviously is far from ideal but it let me download the packages.

**Comment by FrancescElies** [comment]
Hi,

thanks, shall i close this for the tip, shall I close the issue?

**Comment by bjodah** [comment]
In my humble opinion no. I am for example currently unable to upload using the anaconda client (does it work for you?).

So my guess is that something is wrong with the servers handling SSL connections at continuum. (though, one could argue that continuum's servers are not part of the open source project)

**Comment by bjodah** [comment]
Hmmm.. it might be an outdated requests local package causing these issues for me.
This allows me to connect to anaconda.org (by circumventing loading my local package):
```
$ export PYTHONNOUSERSITE=1
```

**Comment by bjodah** [comment]
So there is something wrong with my non-conda Python packages (in `~/.local`). So from my point of view you may close this.

**Comment by FrancescElies** [comment]
@bjodah `export PYTHONNOUSERSITE=1` solves the issue for me too, thanks for your help!
