### ISSUE TITLE
show_channel_urls option from CLI

### ISSUE THREAD

**Issue by quasiben** [conda/conda#1648]
`conda list` does not currently offer any methods for returning channels except with  `show_channel_urls: yes in .condarc` or having previously invoked `config --set show_channel_urls yes`.  It would be great if `conda list` could have an optional parameter to show channels which does **not** change the state of `.condarc`

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1647

**Comment by quasiben** [comment]
:+1:
