### ISSUE TITLE
'source activate named-environment' targets anaconda root, not named-environment

### ISSUE THREAD

**Issue by jay-tyler** [conda/conda#1649]
I'm running conda through a Linux Mint system. I've installed it and am able to create environments, but each time I call `source activate environment-name` it targets the anaconda root. An example set of commands might look like this:

```
$ source activate anaconda-test
$ conda info --env
# conda environments:
#
anaconda-test            /home/jason/anaconda3/envs/anaconda-test
dato-env                 /home/jason/anaconda3/envs/dato-env
root                  *  /home/jason/anaconda3
```

The root environment is activated each time. 

Some additional info:
- On issue #1362, a suggestion was made to reinstall activate. I've tried that with no change.
- Since installing (ana)conda, each time I run a command that isn't present, I get a Python traceback (**example below**). Not sure if this is related or not (should I open another issue?)

```
$ foo
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
ImportError: No module named 'CommandNotFound'
```

**Comment by soapy1** [comment]
@jay-tyler is this still an issue for you. I believe this is no longer a problem in the newest version of conda
