### ISSUE TITLE
Make it possible (and intuitive) to install a package directly from search results

### ISSUE THREAD

**Issue by philbb** [conda/conda#1653]
After performing a search like `anaconda search -t conda python-geohash`, and getting some results, it's not obvious to newbies what needs to be done next in order install the package displayed in the search results and searching this way is the default route that newbies take when a package is not found since it is what is suggested in the terminal when an installation command fails to come up with a package matching the name typed by the user.

I would maybe recommend putting numbers next to the search results and offering users to press that number for it to start installing.

**Comment by kalefranz** [comment]
We develop and maintain Anaconda Navigator for users requiring this level of support.
