### ISSUE TITLE
Offline conda dependencies cannot resolve

### ISSUE THREAD

**Issue by mnazbro** [conda/conda#1660]
I'm trying to use Miniconda offline. During the process, I discovered that certain packages have trouble resolving.
If I were to download all of the transitive dependencies for `pandas` and put it in a custom channel, then I can easily do `conda install --offline --channel file:///path/to/channel pandas`. That will work without a problem.
However, if I try to do the same for `ipython`, I get an unresolved dependency. These are the exact reproduction steps:
1. Download all transitive dependencies of the latest `ipython` for linux-64.
2. Create a custom channel by placing all of the packages into a linux-64 folder.
3. Run `conda index` to create the channel.
4. Run `conda install --offline --channel file:///path/to/channel ipython`.

The response is:

```
Fetching package metadata: ..
Solving package specifications:
Error: Could not find some dependencies for pickleshare: path.py 7.6

Did you mean one of these?

    pickleshare

Did you mean one of these?

    path.py

You can search for this package on anaconda.org with

    anaconda search -t conda path.py 7.6

 (and similarly for the other packages)

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

**Comment by mnazbro** [comment]
I have another example which doesn't work. If you try to download `ipython-4.0.0-py27_0.tar.bz2` offline using `linux-64`, you end up with `wheel` conflicting. I'm pretty sure this means that the canonical conda repo does not use the same index which `conda index` creates.

**Comment by jhoare** [comment]
I have encounted this same problem, it looks to me that the metadata in the pacakges differ from the metadata in the repodata.json that is on the official channel. See #1797

**Comment by mnazbro** [comment]
The current workaround we've been using is to download the relevant packages, and then indexing that before looking up dependencies. This is a really bad workaround, and should be fixed.

**Comment by Earthson** [comment]
+1 
package gcc has the same problem!

**Comment by kalefranz** [comment]
This is mostly the same issue as #2371 and #2317.
