### ISSUE TITLE
Feature Request: Install `test/requires` dependencies

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#1665]
It would be very useful to have a command line option to allow for the test dependencies to be also installed into an environment - e.g. something like

```
conda create --include-test-deps -n tmp_test_env TEST_PACKAGE
```

```
conda install --include-test-deps TEST_PACKAGE
```

**Comment by tyler-thetyrant** [comment]
Constrained, optional dependency is a thing in Conda 4.4! #HYPE
