### ISSUE TITLE
conda environment inconsistent

### ISSUE THREAD

**Issue by JanSchulz** [conda/conda#1666]
I just spend some time debugging a matplotlib problem [which seems to be the result of a not updated pyd file](https://github.com/matplotlib/matplotlib/issues/5156):

```
λ dir *_agg.*
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: E0FA-598A

 Verzeichnis von C:\portabel\miniconda\envs\monte-carlo_off\Lib\site-packages\matplotlib\backends

19.02.2015  18:59            21.106 backend_agg.py
19.02.2015  18:59            23.435 backend_agg.pyc
23.10.2014  19:59           319.488 _backend_agg.pyd
               3 Datei(en),        364.029 Bytes
               0 Verzeichnis(se), 361.723.437.056 Bytes frei
```

Unfortunately, I've no idea how that happened :-(

**Comment by ilanschnell** [comment]
This probably happened because the `.pyd` file was used by a process, which causes problems in Windows because of the file lock.  Newer versions of conda have a workaround for the Windows file lock.  Which version of conda did you use when this happened?

**Comment by JanSchulz** [comment]
I remember upgrading conda a few weeks ago and being surprise about the version jump. So if you are telling me that something changed about such cases, it seems that this was fixed. Thanks a lot!
