### ISSUE TITLE
issue when trying to upgrade conda and scikit-learn

### ISSUE THREAD

**Issue by gmet1** [conda/conda#1670]
hi I am trying to upgrade scikit learn. I get the following error.  Can someone please take a look. Thanks.

C:\Anacondax32>conda update scikit-learn
Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/p
ro/win-32/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
..Could not connect to https://repo.continuum.io/pkgs/free/win-32/
..
Solving package specifications: .
Package plan for installation in environment C:\Anacondax32:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda311fix-1.0 | 0           7 KB |
| conda-env-2.1.4 | py27_0          51 KB |
| nose-1.3.6 | py27_0         233 KB |
| requests-2.7.0 | py27_0         590 KB |
| setuptools-16.0 | py27_0         643 KB |
| conda-3.11.0 | py27_0         207 KB |
| pip-6.1.1 | py27_0         1.4 MB |
| scikit-learn-0.16.1 | np19py27_0         3.3 MB |

```
------------------------------------------------------------
                                       Total:         6.4 MB
```

The following NEW packages will be INSTALLED:

```
conda311fix:  1.0-0
```

The following packages will be UPDATED:

```
conda:        3.10.0-py27_0     --> 3.11.0-py27_0
conda-env:    2.1.3-py27_0      --> 2.1.4-py27_0
nose:         1.3.4-py27_1      --> 1.3.6-py27_0
pip:          6.0.8-py27_0      --> 6.1.1-py27_0
requests:     2.6.0-py27_0      --> 2.7.0-py27_0
scikit-learn: 0.15.2-np19py27_0 --> 0.16.1-np19py27_0
setuptools:   14.3-py27_0       --> 16.0-py27_0
```

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anacondax32\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anacondax32\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anacondax32\lib\site-packages\conda\cli\main.py", line 207, in args_f
unc
    args.func(args, p)
  File "C:\Anacondax32\lib\site-packages\conda\cli\main_update.py", line 40, in
execute
    install.install(args, parser, 'update')
  File "C:\Anacondax32\lib\site-packages\conda\cli\install.py", line 404, in ins
tall
    if not pscheck.main(args):
  File "C:\Anacondax32\lib\site-packages\conda\cli\pscheck.py", line 66, in main

```
while not check_processes():
```

  File "C:\Anacondax32\lib\site-packages\conda\cli\pscheck.py", line 33, in chec
k_processes
    for n in psutil.get_pid_list():
AttributeError: 'module' object has no attribute 'get_pid_list'

C:\Anacondax32>conda info
Current conda install:

```
         platform : win-32
    conda version : 3.10.0
```

  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anacondax32  (writable)
  default environment : C:\Anacondax32
     envs directories : C:\Anacondax32\envs
        package cache : C:\Anacondax32\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
@gmet1 is this still an issue for you?
