### ISSUE TITLE
requests update error: conda installs version 2.3.0 but thinks it's 2.7.0

### ISSUE THREAD

**Issue by Syrus** [conda/conda#1672]
'conda update requests' says it's installing version 2.7.0, but it actually installs 2.3.0 which breaks my code that depends on methods introduced between version 2.3 and 2.6. My workaround was to force conda to install version 2.6.

**Comment by ilanschnell** [comment]
Is this problem reproducible?  I've never seen this before.

**Comment by Syrus** [comment]
It is not reproducible. Somehow the requests package in my local pkgs
folder got installed incorrectly. When I deleted the requests*2.7* folder
and forced conda to download it again, I indeed got version 2.7.0. We
should close the issue. Thanks for following up!

**Comment by ilanschnell** [comment]
Thanks for the feedback and closing the issue.
