### ISSUE TITLE
 Non-versatile shebang usage

### ISSUE THREAD

**Issue by am11** [conda/conda#1675]
Hello,

I tried installing Minoconda on Mac using `sudo ~/Downloads/Miniconda-latest-MacOSX-x86_64.sh`, but turned out shebang is hard-coded, so user need to explicitly invoke the command prefixed with `bash`.

I would have sent a PR, but I could not locate the install script in the repo.

The fix is to replace:

```sh
#!/bin/bash
```

with `env` based path:

```sh
#!/usr/bin/env bash
```

in all `.sh` files, which would support multiple directory structures and work on most, if not all, Unix-like operating systems.

Thanks in anticipation!

**Comment by ilanschnell** [comment]
`/bin/bash` is installed on all system, `/usr/bin/env` only on some.

**Comment by am11** [comment]
Not sure how, but in my experience: `#!/usr/bin/env bash` works on CentOS, Suse, Fedora, OSX, FreeBSD, Ubuntu and Firefly in their default configuration, while `/bin/bash` gives trouble on some of them.
