### ISSUE TITLE
Hint: the following packages conflict with each other:   - numba   - python 3.5*

### ISSUE THREAD

**Issue by shongololo** [conda/conda#1677]
Is there a manner in which to get access to a python 3.5 compatible version of numba via the conda installer? From browsing the numba forums it appears that the current versions should be compatible with python 3.5?

<code>
Error message:
    Hint: the following packages conflict with each other:
      - numba
      - python 3.5*
</code>

Thanks.

**Comment by msarahan** [comment]
We are working to build all packages against Python 3.5, but some of the ones with compiled components are taking longer to work out issues.  We will have this available as soon as possible.

What platform are you on?

**Comment by shongololo** [comment]
Thanks for the update. Is there a general timeframe in mind?

Platform: Mac OS 10.11

**Comment by ilanschnell** [comment]
October 29th the latest
