### ISSUE TITLE
VTK does not display anything when running sample code

### ISSUE THREAD

**Issue by toinsson** [conda/conda#1678]
I use an environment with python2.7 and vtk created with conda3 on ubuntu 14.04:

```
conda --version -> 3.17.0
conda create -n vtk-py2 python=2
source activate vtk-py2
conda install vtk
```

The installation goes through and reports no issue.

The sample is VTK first python [example](http://www.vtk.org/Wiki/VTK/Examples/Python/Cylinder). 
The code execute but returns directly without opening a window and displaying the cylinder.

**Comment by ccordoba12** [comment]
This is right. I'm investigating why this is happening right now.

**Comment by soapy1** [comment]
This issue seems to be resolved in the newest version of conda
