### ISSUE TITLE
Document CIO_TEST system variable

### ISSUE THREAD

**Issue by scw** [conda/conda#1680]
I see it from a default listing of `conda info -e`, but don't see it documented anywhere. I see it [gets used in config.py](https://github.com/conda/conda/blob/4f2efdbb55624de04a7b84bcf9bece2f4be05a26/conda/config.py#L271) for setting up what appear to be a special packaging test server, `filer`, used on the Continuum end. Is this something that others should see and control, or only useful internally?

**Comment by ilanschnell** [comment]
`CIO_TEST` is only used internally for testing purposes.  This is why it is not documented.  The exact behavior may also change in the future.
