### ISSUE TITLE
Could not import binstar client while updating Pandas.

### ISSUE THREAD

**Issue by ford27t** [conda/conda#1681]
This problem began when I could not import dataframe from pandas.  After researching this issue, it was suggested a re-install of Pandas.  I tried updating first (see output attached).  I have also un-installed and re-installed Pandas with the same error.

C:\Python27\Scripts>conda info
Warning: could not import binstar_client (failed to parse CPython sys.version: '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]')Current conda install:

             platform : win-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : C:\Users\ford2\Anaconda  (writable)
  default environment : C:\Users\ford2\Anaconda
     envs directories : C:\Users\ford2\Anaconda\envs
        package cache : C:\Users\ford2\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Python27\Scripts>conda update pandas
Warning: could not import binstar_client (failed to parse CPython sys.version: '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]')Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\ford2\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\install.py", line 255, in install
    offline=args.offline)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\cli\common.py", line 549, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\fetch.py", line 228, in fetch_index
    session = CondaSession()
  File "C:\Users\ford2\Anaconda\lib\site-packages\conda\connection.py", line 59, in __init__
    super(CondaSession, self).__init__(*args, **kwargs)
  File "C:\Users\ford2\Anaconda\lib\site-packages\requests\sessions.py", line 291, in __init__
    self.headers = default_headers()
  File "C:\Users\ford2\Anaconda\lib\site-packages\requests\utils.py", line 573, in default_headers
    'User-Agent': default_user_agent(),
  File "C:\Users\ford2\Anaconda\lib\site-packages\requests\utils.py", line 542, in default_user_agent
    _implementation = platform.python_implementation()
  File "C:\Python27\Lib\platform.py", line 1498, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1463, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]'

**Comment by msarahan** [comment]
Hi,  your conda version is out of date.  Please run

    conda update conda

And then try to install pandas again.

**Comment by ford27t** [comment]
Thanks for your prompt reply.  I did try to update conda with that conda command with the same result.  When I return home I will try to uninstall and re-install Anaconda.

**Comment by msarahan** [comment]
OK.  Please try to download the latest installer from the Continuum website - that might help.

**Comment by ford27t** [comment]
O.K. I uninstalled Anaconda.  I installed the latest version I could find v2.3.0 which is what I started with.  After the installation, I entered "conda update conda".  I still have the same problem and message.  Any ideas?

**Comment by ford27t** [comment]
Update, I wasn't using the Anaconda command processor.  I entered 'conda update conda' with the result that I now have v3.18.2 and Anaconda 2.3.0 is the latest version.  But I still cannot import dataframe from pandas.

**Comment by msarahan** [comment]
Great!  Glad you got that to work.  The anaconda command prompt sets your
PATH environment variable so that the right things get found first.  At
installation time, you can optionally have your PATH variable modified, so
you then don't need to use the Anaconda command prompt.

Have you been able to "conda install pandas"?

**Comment by ford27t** [comment]
-- Attached is listings for panda install and results of python program - same as before.

Added C:\Users\ford2\Anaconda and C:\Users\ford2\Anaconda\Scripts to PATH.

C:\Users\ford2\Anaconda>conda install pandas
Fetching package metadata: ....
Solving package specifications: ............
Package plan for installation in environment C:\Users\ford2\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                1        17.9 MB
    numpy-1.9.3                |           py27_0        23.5 MB
    pytz-2015.6                |           py27_0         168 KB
    ------------------------------------------------------------
                                           Total:        41.6 MB

The following packages will be UPDATED:

    numpy:  1.9.2-py27_0  --> 1.9.3-py27_0
    python: 2.7.10-0      --> 2.7.10-1
    pytz:   2015.4-py27_0 --> 2015.6-py27_0

Proceed ([y]/n)? y

Fetching packages ...
python-2.7.10- 100% |###############################| Time: 0:00:45 416.29 kB/s
numpy-1.9.3-py 100% |###############################| Time: 0:00:58 422.51 kB/s
pytz-2015.6-py 100% |###############################| Time: 0:00:00 211.25 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\Users\ford2\Anaconda>

-- Python error after installing pandas and running program:

Traceback (most recent call last):
  File "C:\Users\ford2\Desktop\pandaspgm.py", line 1, in <module>
    import pandas as pd
  File "C:/Python27/Lib/idlelib\pandas.py", line 2, in <module>
ImportError: cannot import name dataframe
>>>

**Comment by msarahan** [comment]
Do you have more than one Python version installed?  It looks like you are
finding a different Python installation (anaconda in your home folder, but
Python27 in C:\).  Make sure that you do not have PYTHONPATH set, unless
you really have a reason to do so, and you know what you are doing with it
(NOT picking up other pandas installations!)

**Comment by ford27t** [comment]
-- BTW, this is the test program I'm using:

import pandas as pd
import datetime
import pandas.io.data
from pandas import DataFrame
import matplotlib.pyplot as plt
from matplotlib import style





sp500 = pd.io.data.get_data_yahoo('%5EGSPC',
                                  start = datetime.datetime(2000, -1, 1),
                                  end = datetime.datetime(2014,6,11))
print sp500

**Comment by ford27t** [comment]
O.K., I think I have it now.  I uninstalled Python and re-installed it. I am using Notepad ++ now and my test program works, after I fixed a pgming glitch (my month ref was -1 and not 1).
I thank you all for your assistance.

**Comment by msarahan** [comment]
Excellent, I am closing this issue.
