### ISSUE TITLE
conda package plan includes removing python

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1685]
I just tried to do `conda install conda-build anaconda-client` on my root env (`conda-build` can only be installed in the root env) and the package plan proposed removing `python`.  I didn't notice this, ran the install, and now have broken my root environment.

```
[root@we-release-trial ~]# /opt/wakari/anaconda/bin/conda install conda-build anaconda-client
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /opt/wakari/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.4.2            |           py27_0          24 KB
    pillow-3.0.0               |           py27_0         788 KB
    pytz-2015.6                |           py27_0         173 KB
    setuptools-18.3.2          |           py27_0         342 KB
    wheel-0.26.0               |           py27_1          76 KB
    clyent-0.4.0               |           py27_0          14 KB
    conda-3.18.1               |           py27_0         172 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    anaconda-client-1.0.2      |           py27_0          91 KB
    conda-build-1.18.0         |           py27_0         205 KB
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

    anaconda-client: 1.0.2-py27_0 
    wheel:           0.26.0-py27_1

The following packages will be REMOVED:

    python:          2.7.10-0     

The following packages will be UPDATED:

    clyent:          0.3.4-py27_0  --> 0.4.0-py27_0 
    conda:           3.14.1-py27_0 --> 3.18.1-py27_0
    conda-build:     1.14.1-py27_0 --> 1.18.0-py27_0
    conda-env:       2.2.3-py27_0  --> 2.4.2-py27_0 
    pillow:          2.8.2-py27_0  --> 3.0.0-py27_0 
    pip:             7.0.3-py27_0  --> 7.1.2-py27_0 
    pytz:            2015.4-py27_0 --> 2015.6-py27_0
    setuptools:      17.1.1-py27_0 --> 18.3.2-py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.4. 100% |########################################| Time: 0:00:00   3.19 MB/s
pillow-3.0.0-p 100% |########################################| Time: 0:00:00   8.44 MB/s
pytz-2015.6-py 100% |########################################| Time: 0:00:00   4.77 MB/s
setuptools-18. 100% |########################################| Time: 0:00:00   5.27 MB/s
wheel-0.26.0-p 100% |########################################| Time: 0:00:00   3.19 MB/s
clyent-0.4.0-p 100% |########################################| Time: 0:00:00   2.25 MB/s
conda-3.18.1-p 100% |########################################| Time: 0:00:00   3.98 MB/s
pip-7.1.2-py27 100% |########################################| Time: 0:00:00  11.85 MB/s
anaconda-clien 100% |########################################| Time: 0:00:00   3.88 MB/s
conda-build-1. 100% |########################################| Time: 0:00:00   4.38 MB/s
Extracting packages ...
[      COMPLETE      ]|########################################| 100%
Unlinking packages ...
[      COMPLETE      ]|########################################| 100%
Linking packages ...
[      COMPLETE      ]|########################################| 100%
```

**Comment by ijstokes** [comment]
Oh, and in case it isn't obvious, there is no easy way to fix this since now `conda` won't run.  I can hand-patch the `/opt/wakari/anaconda/pkgs/python-2.7.10` files back into place with rsync, but even that isn't quite re-creating what existed before (which would, I suppose, require some complicated combination of `find` and `ln` operations to re-build hard-links).

This looks like this rsync command saved my bacon:

```bash
rsync -a /opt/wakari/anaconda/pkgs/python-2.7.10-0/ /opt/wakari/anaconda/
```

Although it also provided hints as to the problem: after I ran this command I wanted to try and get `conda` on the same page as to which Python version was installed, so I did:

```bash
# conda update python
Fetching package metadata: ......
Solving package specifications: ..................
# All requested packages already installed.
# packages in environment at /opt/wakari/anaconda:
#
python                    2.7.10                        1
```

Notice that it is saying build 1, although the "remove" had been build 0.  Weird!  I tried to "fix" this by doing:

```bash
# conda install --force python=2.7.10
Fetching package metadata: ......
Solving package specifications: ..................
Package plan for installation in environment /opt/wakari/anaconda:

The following packages will be UPDATED:

    python: 2.7.10-1 --> 2.7.10-1

Proceed ([y]/n)? y

[      COMPLETE      ]|########################################| 100%
Extracting packages ...
[      COMPLETE      ]|########################################| 100%
Unlinking packages ...
[      COMPLETE      ]|########################################| 100%
Linking packages ...
[      COMPLETE      ]|########################################| 100%
```

Which seemed to get everyone on the same page.

**Comment by ijstokes** [comment]
OK, this is just speculation, but I think I have an idea about what happened.  Re-creating it to confirm would take me close to an hour, which I don't have time to do right now, but here is my hunch: somehow conda got to thinking that both `2.7.10-0` and `2.7.10-1` versions of the `python` package were installed.  The `conda install` command wanted to use the latest version `2.7.10-1` (already installed) and to do so, it identified that `2.7.10-0` (already installed) should be removed.  Since `2.7.10-1` was already installed, it wasn't installed again, but "removing" `2.7.10-0` meant (effectively) deleting a set of files that were, in fact, the `2.7.10-1` files.

If this is the case (TBD by myself or @mmarchetti), how can conda allow the environment get into a state where there are multiple copies of the same package installed?

**Comment by ijstokes** [comment]
Looks like there is a history of this problem, in reverse chronological order:

https://github.com/conda/conda/issues/1602
https://github.com/conda/conda/issues/1384
https://github.com/conda/conda/issues/1207
https://github.com/conda/conda/issues/1203
https://github.com/conda/conda/issues/1075

I'd like to request that it get bumped up the priority list for resolution.

**Comment by pitrou** [comment]
> somehow conda got to thinking that both 2.7.10-0 and 2.7.10-1 versions of the python package were installed

I already got in a similar situation, not with the python package, but other ones. Apparently it can happen when you `conda install` a package tarball directly, rather than a package specification (but perhaps it can happen in other circumstances).

**Comment by ilanschnell** [comment]
Ian, so how did `2.7.10-0` and `2.7.10-1` get installed at the same time in the first place?

**Comment by pzwang** [comment]
@pitrou Can you dig into that a little bit more?  Why would either of those installation entry points be different?

**Comment by mmarchetti** [comment]
The Wakari installer was previously running a stock Anaconda installer, then conda installing a collection of addon packages. Ilan suggested that we not use the 'extra_files' feature that way (and, to be fair, it was not a great way to do it). We just changed over to bundling the extra packages into a cas-installer and running that after the Anaconda installer. That cas-installer had 2.7.10-1 in it.

**Comment by ilanschnell** [comment]
I can reproduce the issue when a create a `2.7.10-1` environment, and `conda install python-2.7.10-0.tar/bz2`.  Now when I install any other package, conda wants to remove `python 2.7.10-0`.
However, under normal conditions this will never happen, as `conda install <conda package file>` is for debugging and experimental use only.

**Comment by ijstokes** [comment]
@ilanschnell what has happened here seems to be a `cas-installer` issue perhaps, but I'd say linked to what `conda` allows you to do (or perhaps `cas-installer` is doing something nefarious).  Basically the Anaconda *base* results in 2.7.10-0 being installed, but then due to `cas-installer` we immediately update it via the bundled tarball to 2.7.10-1 being installed.  But conda doesn't see that this replaces/updates 2.7.10-0, so it thinks *both* are installed (which should never happen).  Then at some later point `conda install` or `conda update` builds a package plan that specifies the newest version of python (2.7.10-1), sees that an old version is installed (2.7.10-0), assumes only one version is installed, adds to the installation plan the action to remove the files listed against the old version (2.7.10-0), but at that point does notice that 2.7.10-1 *is* installed already, so it doesn't add to the plan that 2.7.10-1 should be installed (since it is there before the install starts, but doesn't realize that the associated files are about to be blown away: at least the ones that overlap with the old version, which is almost all of them).

**Comment by ijstokes** [comment]
@ilanschnell I do not believe that the case of installing from a tarball should be for debugging and experimental use only.  These two operations should be identical (this is pseudo-valid):

```bash
conda install -c ijstokes foo=1.2.3
```
and
```bash
wget http://anaconda.org/ijstokes/foo/foo-1.2.3.tar.bz2
conda install foo-1.2.3.tar.bz2
```

And the strongest reason for why it needs to work this way is because this is what `cas-installer` seems to be doing, and *not* supporting these two operations (network-based, versus specific tarball file) as equivalent leads to this difficult bug.

**Comment by ijstokes** [comment]
@stephenakearns and @csoja and @mrduane I thought I'd tagged you on this.

**Comment by ilanschnell** [comment]
@ijstokes The two operations you bring up are not identical.  I don't know how exactly the Wakari installer works, but if it uses `conda install foo-1.2.3.tar.bz2` (combined with the `extra_files` feature), then this is a problem.

**Comment by pitrou** [comment]
> However, under normal conditions this will never happen, as conda install <conda package file> is for debugging and experimental use only.

I find it useful to install a package without uploading it first (sometimes of the packages I generate can be 70 MB large, for example).

**Comment by ilanschnell** [comment]
Yes, it is a useful feature for experts, and doing so it at your risk.  It is not a feature for which should be used for production Wakari installers.

**Comment by pitrou** [comment]
Well, I do not claim to be an expert. I happened to discover it by chance. If there are issues with it then it should probably display a warning message, and perhaps suggest an alternative.

**Comment by mmarchetti** [comment]
The Wakari installers currently in the field (0.8.0) do `conda install pkg.tar.bz2` and that works (we are not installing any packages that duplicate ones in Anaconda so we don't hit this problem). We tried to get away from that by building the packages into a secondary cas-installer, and that led us to this problem.

**Comment by ilanschnell** [comment]
Secondary cas-installer?  What does that mean?

**Comment by mmarchetti** [comment]
The wakari-compute installer is a cas-installer that creates an environment called wakari-compute (our app runs from this environment). It also creates a separate, anaconda environment for our users by including the Anaconda 2.3.0 linux-64 installer under extra_files and running it during the post-install step.

We need to install some additional user packages into the Anaconda environment we just created. In the 0.8.0 release, we include the package tarballs under extra_files, and then conda install them.

In 0.9.0, we took those packages and built them into a cas-installer, and we run that after the Anaconda installer. That's what I was referring to as a "secondary installer".

**Comment by teoliphant** [comment]
I agree this needs to be fixed.   Even if installing from a tar/bz2 manually is "only for experts" (which I don't agree it is), then we still shouldn't be setting people up to break their conda installation in that way inappropriately removing python.    It sounds like @ilanschnell can reproduce the problem and can therefore work on a fix.

**Comment by ilanschnell** [comment]
I fixed it in this PR https://github.com/conda/conda/pull/1687

**Comment by ilanschnell** [comment]
However, the real fix that needs to happen is that the Wakari team needs to remove `conda install pkg.tar.bz2` (and maybe other messy things) from their cas-installer.

**Comment by mmarchetti** [comment]
We got to where we are today by trying to stop installing tarballs directly, and bundle them together into a cas-installer instead. It seems like if you run a cas-installer on top of a clean Anaconda installation, you can get into trouble that way too.

**Comment by ilanschnell** [comment]
Yes, of course you can get in trouble installing a cas-installer on top of Anaconda.  Why would you even do that?  The cas-installer tool allows you create an installer with whatever packages you want, such that there is no need to first install Anaconda, and then replace packages.

**Comment by mmarchetti** [comment]
Wakari had gotten far behind the Anaconda releases. It was difficult to tell which of the packages came from Anaconda, and which were added by the Wakari team (due in part to changes in the Anaconda package set between version ~1.9 and 2.3, as well as changing requirements on the Wakari side). We'd like to have our custom packages cleanly separated so we can simply take an updated Anaconda installer whenever it is released.

**Comment by ilanschnell** [comment]
Making this clean distinction is still possible, even when you are dealing with a single installer.

**Comment by damianavila** [comment]
> Making this clean distinction is still possible, even when you are dealing with a single installer.

How? :wink:

**Comment by ilanschnell** [comment]
By using a script like https://github.com/ContinuumIO/internal/blob/master/test-ilan/wi.sh and feeding the output of this script directly into the cas-installer meta.yaml file.
