### ISSUE TITLE
Failure to create Python 2.7 environment

### ISSUE THREAD

**Issue by jjkane** [conda/conda#1691]
I am trying to create a Python 2.7 environment after having recently installed Anaconda3 on a Windows 7 64-bit system.

Command:
        conda create -n py27 python=2.7 anaconda

Error message:
       Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/free/win-64/menuinst-1.0.4-py27_0.tar.bz2

Complete output:

C:\Anaconda3>conda create -n py27 python=2.7 anaconda
Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
...
Solving package specifications: .
Package plan for installation in environment C:\Anaconda3\envs\py27:

The following packages will be downloaded:

| package | build |
| --- | --- |
| _license-1.1 | py27_0          50 KB |
| beautiful-soup-4.3.2 | py27_1         109 KB |
| bitarray-0.8.1 | py27_1          52 KB |
| boto-2.36.0 | py27_0         1.5 MB |
| cdecimal-2.3 | py27_1         117 KB |
| certifi-14.05.14 | py27_0         154 KB |
| clyent-0.3.4 | py27_0          13 KB |
| colorama-0.3.3 | py27_0          17 KB |
| cython-0.22 | py27_0         1.8 MB |
| cytoolz-0.7.2 | py27_0         171 KB |
| decorator-3.4.0 | py27_0           8 KB |
| docutils-0.12 | py27_1         637 KB |
| enum34-1.0.4 | py27_0          48 KB |
| fastcache-1.0.2 | py27_0          23 KB |
| funcsigs-0.4 | py27_0          19 KB |
| futures-2.2.0 | py27_0          21 KB |
| greenlet-0.4.5 | py27_0          13 KB |
| gevent-1.0.1 | py27_0         293 KB |
| grin-1.2.1 | py27_2          23 KB |
| itsdangerous-0.24 | py27_0          15 KB |
| jdcal-1.0 | py27_0           9 KB |
| jedi-0.8.1 | py27_0         171 KB |
| jsonschema-2.4.0 | py27_0          92 KB |
| llvmlite-0.2.2 | py27_1         4.7 MB |
| lxml-3.4.2 | py27_0         1.5 MB |
| markupsafe-0.23 | py27_0          23 KB |
| menuinst-1.0.4 | py27_0          52 KB |
| mistune-0.5.1 | py27_0          18 KB |
| mock-1.0.1 | py27_0          36 KB |
| multipledispatch-0.4.7 | py27_0          11 KB |
| networkx-1.9.1 | py27_0         928 KB |
| nose-1.3.4 | py27_1         233 KB |
| numpy-1.9.2 | py27_0        23.2 MB |
| astropy-1.0.1 | np19py27_0         5.2 MB |
| bcolz-0.8.1 | np19py27_0         310 KB |
| dynd-python-0.6.5 | np19py27_0         890 KB |
| h5py-2.4.0 | np19py27_0         1.4 MB |
| numba-0.17.0 | np19py27_0         830 KB |
| numexpr-2.3.1 | np19py27_0         115 KB |
| blz-0.6.2 | np19py27_0         287 KB |
| openpyxl-1.8.5 | py27_0         127 KB |
| pep8-1.6.2 | py27_0          87 KB |
| pillow-2.7.0 | py27_0         917 KB |
| ply-3.4 | py27_0          67 KB |
| psutil-2.2.1 | py27_0          99 KB |
| py-1.4.26 | py27_0         121 KB |
| pyasn1-0.1.7 | py27_0          48 KB |
| pycosat-0.6.1 | py27_0          47 KB |
| pycparser-2.10 | py27_0         144 KB |
| cffi-0.9.2 | py27_0         117 KB |
| pycrypto-2.6.1 | py27_3         454 KB |
| pyflakes-0.8.1 | py27_0          50 KB |
| pygments-2.0.2 | py27_0         1.1 MB |
| pyparsing-2.0.3 | py27_0          63 KB |
| pyqt-4.10.4 | py27_1        31.2 MB |
| pyreadline-2.0 | py27_0         127 KB |
| ipython-3.0.0 | py27_1         3.4 MB |
| pytables-3.1.1 | np19py27_1         2.4 MB |
| pytest-2.6.4 | py27_0         221 KB |
| python-2.7.9 | 1        18.8 MB |
| pytz-2015.2 | py27_0         169 KB |
| pywin32-219 | py27_0        10.4 MB |
| pyyaml-3.11 | py27_0         167 KB |
| pyzmq-14.5.0 | py27_0         397 KB |
| requests-2.6.0 | py27_0         590 KB |
| rope-0.9.4 | py27_1         225 KB |
| scipy-0.15.1 | np19py27_0        71.3 MB |
| setuptools-14.3 | py27_0         742 KB |
| six-1.9.0 | py27_0          16 KB |
| sqlalchemy-0.9.9 | py27_0         1.2 MB |
| ssl_match_hostname-3.4.0.2 | py27_0           6 KB |
| sympy-0.7.6 | py27_0         6.2 MB |
| toolz-0.7.1 | py27_0          27 KB |
| ujson-1.33 | py27_0          17 KB |
| unicodecsv-0.9.4 | py27_0          17 KB |
| werkzeug-0.10.1 | py27_0         374 KB |
| xlrd-0.9.3 | py27_0         160 KB |
| xlsxwriter-0.6.7 | py27_0         173 KB |
| xlwt-0.7.5 | py27_0         172 KB |
| argcomplete-0.8.4 | py27_0          80 KB |
| configobj-5.0.6 | py27_0          49 KB |
| cryptography-0.8 | py27_1         1.0 MB |
| gevent-websocket-0.9.3 | py27_0          24 KB |
| ipython-qtconsole-3.0.0 | py27_1           4 KB |
| jinja2-2.7.3 | py27_2         307 KB |
| nltk-3.0.2 | np19py27_0         1.5 MB |
| patsy-0.3.0 | np19py27_0         308 KB |
| pip-6.0.8 | py27_0         1.6 MB |
| python-dateutil-2.4.1 | py27_0         218 KB |
| scikit-learn-0.15.2 | np19py27_0         3.3 MB |
| tornado-4.1 | py27_0         475 KB |
| xlwings-0.3.4 | py27_0         234 KB |
| binstar-0.10.1 | py27_3         124 KB |
| datashape-0.4.4 | np19py27_1          95 KB |
| flask-0.10.1 | py27_1         128 KB |
| ipython-notebook-3.0.0 | py27_2           5 KB |
| matplotlib-1.4.3 | np19py27_1        41.9 MB |
| pandas-0.15.2 | np19py27_1         4.3 MB |
| pyopenssl-0.14 | py27_0         122 KB |
| sockjs-tornado-1.0.1 | py27_0          31 KB |
| sphinx-1.2.3 | py27_0         1.0 MB |
| bokeh-0.8.1 | np19py27_1        13.5 MB |
| odo-0.3.1 | np19py27_0         180 KB |
| runipy-0.1.3 | py27_0          48 KB |
| scikit-image-0.11.2 | np19py27_0        15.8 MB |
| spyder-2.3.4 | py27_1         4.0 MB |
| statsmodels-0.6.1 | np19py27_0         4.6 MB |
| blaze-core-0.7.3 | np19py27_0         305 KB |
| spyder-app-2.3.4 | py27_0           7 KB |
| anaconda-2.2.0 | np19py27_0          30 KB |

```
------------------------------------------------------------
                                       Total:       291.9 MB
```

The following NEW packages will be INSTALLED:

```
_license:           1.1-py27_0
anaconda:           2.2.0-np19py27_0
argcomplete:        0.8.4-py27_0
astropy:            1.0.1-np19py27_0
bcolz:              0.8.1-np19py27_0
beautiful-soup:     4.3.2-py27_1
binstar:            0.10.1-py27_3
bitarray:           0.8.1-py27_1
blaze-core:         0.7.3-np19py27_0
blz:                0.6.2-np19py27_0
bokeh:              0.8.1-np19py27_1
boto:               2.36.0-py27_0
cdecimal:           2.3-py27_1
certifi:            14.05.14-py27_0
cffi:               0.9.2-py27_0
clyent:             0.3.4-py27_0
colorama:           0.3.3-py27_0
configobj:          5.0.6-py27_0
cryptography:       0.8-py27_1
cython:             0.22-py27_0
cytoolz:            0.7.2-py27_0
datashape:          0.4.4-np19py27_1
decorator:          3.4.0-py27_0
docutils:           0.12-py27_1
dynd-python:        0.6.5-np19py27_0
enum34:             1.0.4-py27_0
fastcache:          1.0.2-py27_0
flask:              0.10.1-py27_1
funcsigs:           0.4-py27_0
futures:            2.2.0-py27_0
gevent:             1.0.1-py27_0
gevent-websocket:   0.9.3-py27_0
greenlet:           0.4.5-py27_0
grin:               1.2.1-py27_2
h5py:               2.4.0-np19py27_0
ipython:            3.0.0-py27_1
ipython-notebook:   3.0.0-py27_2
ipython-qtconsole:  3.0.0-py27_1
itsdangerous:       0.24-py27_0
jdcal:              1.0-py27_0
jedi:               0.8.1-py27_0
jinja2:             2.7.3-py27_2
jsonschema:         2.4.0-py27_0
launcher:           1.0.0-1
llvmlite:           0.2.2-py27_1
lxml:               3.4.2-py27_0
markupsafe:         0.23-py27_0
matplotlib:         1.4.3-np19py27_1
menuinst:           1.0.4-py27_0
mistune:            0.5.1-py27_0
mock:               1.0.1-py27_0
multipledispatch:   0.4.7-py27_0
networkx:           1.9.1-py27_0
nltk:               3.0.2-np19py27_0
node-webkit:        0.10.1-0
nose:               1.3.4-py27_1
numba:              0.17.0-np19py27_0
numexpr:            2.3.1-np19py27_0
numpy:              1.9.2-py27_0
odo:                0.3.1-np19py27_0
openpyxl:           1.8.5-py27_0
pandas:             0.15.2-np19py27_1
patsy:              0.3.0-np19py27_0
pep8:               1.6.2-py27_0
pillow:             2.7.0-py27_0
pip:                6.0.8-py27_0
ply:                3.4-py27_0
psutil:             2.2.1-py27_0
py:                 1.4.26-py27_0
pyasn1:             0.1.7-py27_0
pycosat:            0.6.1-py27_0
pycparser:          2.10-py27_0
pycrypto:           2.6.1-py27_3
pyflakes:           0.8.1-py27_0
pygments:           2.0.2-py27_0
pyopenssl:          0.14-py27_0
pyparsing:          2.0.3-py27_0
pyqt:               4.10.4-py27_1
pyreadline:         2.0-py27_0
pytables:           3.1.1-np19py27_1
pytest:             2.6.4-py27_0
python:             2.7.9-1
python-dateutil:    2.4.1-py27_0
pytz:               2015.2-py27_0
pywin32:            219-py27_0
pyyaml:             3.11-py27_0
pyzmq:              14.5.0-py27_0
requests:           2.6.0-py27_0
rope:               0.9.4-py27_1
runipy:             0.1.3-py27_0
scikit-image:       0.11.2-np19py27_0
scikit-learn:       0.15.2-np19py27_0
scipy:              0.15.1-np19py27_0
setuptools:         14.3-py27_0
six:                1.9.0-py27_0
sockjs-tornado:     1.0.1-py27_0
sphinx:             1.2.3-py27_0
spyder:             2.3.4-py27_1
spyder-app:         2.3.4-py27_0
sqlalchemy:         0.9.9-py27_0
ssl_match_hostname: 3.4.0.2-py27_0
statsmodels:        0.6.1-np19py27_0
sympy:              0.7.6-py27_0
toolz:              0.7.1-py27_0
tornado:            4.1-py27_0
ujson:              1.33-py27_0
unicodecsv:         0.9.4-py27_0
werkzeug:           0.10.1-py27_0
xlrd:               0.9.3-py27_0
xlsxwriter:         0.6.7-py27_0
xlwings:            0.3.4-py27_0
xlwt:               0.7.5-py27_0
```

Proceed ([y]/n)? y

Could not connect to https://repo.continuum.io/pkgs/free/win-64/menuinst-1.0.4-py27_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/free/win-64/menuinst-1.0.4-py27_0.tar.bz2

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by twtina** [comment]
I am seeing this issues as well. Were you able to resolve the issues?

**Comment by kalefranz** [comment]
Is this still an issue?

**Comment by jjkane** [comment]
This certificate problems have been resolved.

John J. Kane, Ph.D.
Member, Research Staff
Cost Analysis and Research Division
Institute for Defense Analyses
4850 Mark Center Drive
Alexandria, Virginia 22311-1882
703-575-4688
