### ISSUE TITLE
conda search -o errors: anaconda, anconda3 on Ubuntu 14.04 

### ISSUE THREAD

**Issue by lyndb** [conda/conda#1697]
#### [Using anaconda Py 2.7]

lynd@zdog:~$ conda search -o
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/lynd/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/lynd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/lynd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/lynd/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 120, in execute
    execute_search(args, parser)
  File "/home/lynd/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 253, in execute_search
    assert len(vers_inst) == 1, name
AssertionError: jupyter_client
lynd@zdog:~$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.18.1
```

  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 2.8.0
     root environment : /home/lynd/anaconda  (writable)
  default environment : /home/lynd/anaconda
     envs directories : /home/lynd/anaconda/envs
        package cache : /home/lynd/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/lynd/.condarc
    is foreign system : False
#### [Using anaconda3 Py 3.4]

conda search -o
Fetching package metadata: ....
astropy                      0.2                  np17py33_0  defaults  
                             0.2                  np17py27_0  defaults  
[snip]
                           1.0.3                np19py33_0  defaults  
                             1.0.3                np19py27_0  defaults  
                             1.0.3                np19py26_0  defaults  
                             1.0.4                np19py35_0  defaults  
                          \*  1.0.4                np19py34_0  defaults  
                             1.0.4                np19py27_0  defaults  
                             1.0.5               np110py35_1  defaults  
                             1.0.5               np110py34_1  defaults  
                             1.0.5               np110py27_1  defaults  
gensim                       0.10.0               np19py34_0  defaults  
                             0.10.0               np19py33_0  defaults  
                             0.10.0               np19py27_0  defaults  
                             0.10.0               np19py26_0  defaults  
                             0.10.0               np18py34_0  defaults  
                             0.10.0               np18py33_0  defaults  
                             0.10.0               np18py27_0  defaults  
                             0.10.0               np18py26_0  defaults  
                             0.10.2               np19py34_0  defaults  
                             0.10.2               np19py33_0  defaults  
                             0.10.2               np19py27_0  defaults  
                             0.10.2               np19py26_0  defaults  
                          \*  0.10.3               np19py34_0  defaults  
                             0.10.3               np19py33_0  defaults  
                             0.10.3               np19py27_0  defaults  
                             0.10.3               np19py26_0  defaults  
                             0.12.1               np19py27_0  defaults  
                             0.12.2               np19py27_0  defaults  
                             0.12.2              np110py27_0  defaults  
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/lynd/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/lynd/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/lynd/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/lynd/anaconda3/lib/python3.4/site-packages/conda/cli/main_search.py", line 120, in execute
    execute_search(args, parser)
  File "/home/lynd/anaconda3/lib/python3.4/site-packages/conda/cli/main_search.py", line 253, in execute_search
    assert len(vers_inst) == 1, name
AssertionError: jupyter_client
lynd@zdog:~$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.18.1
```

  conda-build version : 1.18.0
       python version : 3.4.3.final.0
     requests version : 2.8.0
     root environment : /home/lynd/anaconda3  (writable)
  default environment : /home/lynd/anaconda3
     envs directories : /home/lynd/anaconda3/envs
        package cache : /home/lynd/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/lynd/.condarc
    is foreign system : False

**Comment by soapy1** [comment]
This error message should be more clear with pr: https://github.com/conda/conda/pull/3802
