### ISSUE TITLE
`conda reload` command

### ISSUE THREAD

**Issue by naught101** [conda/conda#1698]
I often find myself needing to re-load the current environment, using `source activate <env>`, for example after rebuilding and re-installing a package that I'm working on. It would be helpful to have an env-agnostic command that could be called from a rebuild script, like this:

```
conda build <recipe>
conda uninstall <package>
conda install <package> --use-local
conda reload
```

where `conda reload` basically does `source activate <current-env>`, without having to specify the env name.

**Comment by ilanschnell** [comment]
Use `conda install --force` to reinstall a package.

**Comment by jessehoff** [comment]
Hey i'd like this too. Conda intall --force doesn't do the same thing.
