### ISSUE TITLE
conda info and lock-file for non-root users

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#170]
a non-root user using a system-installed version of conda can't execute "conda info", and the error message is confusing:

```
$ conda info
Error: It looks like conda is already doing something.  The lockfile /opt/anaconda/.conda_lock was found. Wait for it to finish before continuing. If you are sure that conda is not running, remove it and try again.

$ ls /opt/anaconda/.conda_lock
ls: /opt/anaconda/.conda_lock: No such file or directory

$ sudo conda info

Current conda install:

             platform : osx-64
conda command version : 1.7.1
       root directory : /opt/anaconda
       default prefix : /opt/anaconda
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
```

A conversation with @asmeurer explained that this is because conda tries to write the lockfile and catches _any_ IOError with the same code block, assuming it is due to an existing lockfile, rather than a failure to write a lockfile.

This is low priority, but I probably won't be the first person to get this error and be confused by it.  While I can execute `sudo conda info`, most users without sudo access on a system-wide conda install probably won't have the same luxury.

**Comment by imanojkumar** [comment]
if you are using ANACONDA... just type at command prompt
    $ conda clean --lock
This will remove any locks in python restricting fresh install of packages.
