### ISSUE TITLE
conda create is too slow in Windows

### ISSUE THREAD

**Issue by lucidfrontier45** [conda/conda#1700]
Creating conda virtual python env in Windows is to slow compared to Linux.
For example, `conda create -n py34 python=3.4` with Windows note PC took 1-2 min while it only took a few sec with Ubuntu 14.04 (in VirtualBox for the same note PC).

Does `conda create` do different things in Windows and Linux?

**Comment by kalefranz** [comment]
You probably already had the packages downloaded and extracted in your package cache on linux.  Also, windows can be slower in some situations just because of the way it locks files.  No getting around that.
