### ISSUE TITLE
Error from trying to update Anaconda

### ISSUE THREAD

**Issue by Elliebee79** [conda/conda#1703]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 198, in instal
l
    assert len(vers_inst) == 1, name
AssertionError: conda

**Comment by ilanschnell** [comment]
What was the exact command you tried to run?  What is the output from `conda info`?

**Comment by Elliebee79** [comment]
I was able to get the issue resolved with assistance from John so you can close this ticket. Thank you for following up.

Lauralea

**Comment by rosydawn1** [comment]
can you indicate how this was solved.  I am having this issue

**Comment by jgmorrison** [comment]
This particular issue was due to permissions issues on Windows. It was installed with elevated privileges for all users but the user did not have the elevated privileges when trying to use conda. 

There were additional issues of this being rolled back with Windows restore rather than "conda revisions"
