### ISSUE TITLE
cannot install py35 anaconda

### ISSUE THREAD

**Issue by Alchemist45** [conda/conda#1711]
I get the following error if I follow the online directions:

conda create -n py35 python=3.5 anaconda
Fetching package metadata: ....
Solving package specifications: .......
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%

Hint: the following packages conflict with each other:
  - python 3.5*
  - anaconda

Use 'conda info python' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
Anyone know what is happening?

**Comment by msarahan** [comment]
There is no official anaconda metapackage for Python 3.5 yet.  That will come with the Anaconda 2.4 release at the end of this month.

**Comment by Alchemist45** [comment]
Thanks for your reply.  Could you please email when the anaconda package for 3.5 is ready.

 

Thanks,

 

Scott
