### ISSUE TITLE
Show python version in conda environment list

### ISSUE THREAD

**Issue by tlnagy** [conda/conda#1712]
It would be nice if the `conda info -e` and `conda env list` commands also showed what version of python was used in the virtual environment. I have a lot of environments and sometimes it's hard to remember which python version is in each environment without activating the env and running `python --version`.

**Comment by tyler-thetyrant** [comment]
It is now supported!

**Comment by juharris** [comment]
@tyler-thetyrant how?

**Comment by yehjames** [comment]
how?
