### ISSUE TITLE
It would be nice if conda suggested to install from conda instead of the OS's package manager

### ISSUE THREAD

**Issue by moorepants** [conda/conda#1716]
In this case:

```
(pelican)moorepants@caramelmonkey:eme150a-website(master)$ ipython
The program 'ipython' is currently not installed. You can install it by typing:
sudo apt-get install ipython
```

it would be nice if the suggestion was from conda instead of apt because I'm in a conda environment (at least for packages that are available in the current channels).

**Comment by msarahan** [comment]
ooo, good idea.  Seems a little evil to hijack the system's machinations for this, though.  Do you know how Ubuntu does it?

I guess as long as you're in a conda environment other than root, this would be OK.

**Comment by moorepants** [comment]
Yes, this should only happen in envs. I assume apt caches the packages and then simply searches for matches on the executable call. We'd have to investigate the apt code or ask them.

**Comment by msarahan** [comment]
Yes, it's some cooperative deal using apt, and also some hijacking of what
the shell itself is doing (because the shell itself has to make that query
for what packages are or are not installed, then go find candidates).  I'll
bring this up internally and try to put it on a roadmap.

**Comment by kalefranz** [comment]
I guess we'd have to hook into whatever the command not found callback is for each shell.  https://superuser.com/questions/787424/hook-into-command-not-found-handler-in-ubuntu for example.  Configuration like that, on top of being per-shell, is also usually in a hard-coded location.  I don't know of a feasible technical solution to actually make this happen.
