### ISSUE TITLE
A command to pin packages

### ISSUE THREAD

**Issue by pitrou** [conda/conda#1718]
It would be nice to have a command to pin packages, e.g. `conda pin numpy=1.6`. This would be more user-friendly than having to edit a file in a non-trivial location (IIUC, I have to look into `$ENV/conda-meta/pinned`).

**Comment by jnmclarty** [comment]
+1

**Comment by kalefranz** [comment]
Undocumented in conda 4.3 (because it has some weird behavior), but will be implemented well in conda 4.4, is `conda config --env --add pinned_packages python=2`.

The `--env` flag sets the condarc file for the current active env only.
