### ISSUE TITLE
setinternet2 for Windows strict firewalls

### ISSUE THREAD

**Issue by AntonioSuriano** [conda/conda#1719]
R and Rstudio bypass corporate proxies using a dll to connect to internet explorer.

It is called internet2.dll.

At present it is the only language I can download packages in my workplace.

http://www.inside-r.org/r-doc/utils/setInternet2
Why don't you put it also in conda?

**Comment by mingwandroid** [comment]
I will not fix this because https://cran.r-project.org/doc/manuals/r-devel/NEWS.html states:

```
DEPRECATED AND DEFUNCT

(Windows only) Function setInternet2() is defunct.
```
