### ISSUE TITLE
conda list not working after conda create

### ISSUE THREAD

**Issue by willyd** [conda/conda#1723]
Hi, 

conda seems broken on Windows with a system wide install. If I create an environment like so:

``` shell
conda create -n test
```

and activate it

``` shell
activate test
```

everything works ok but when I do:

``` shell
conda list
```

I get the following error message:

``` shell
Error: Error: environment does not exist: C:\Users\user0804\"C:\Anaconda\envs"\test
#
# Use 'conda create' to create an environment before listing its packages.
```

**Comment by willyd** [comment]
Ok this seems to be related to the `CONDA_ENVS_PATH` variable being set to `"C:\Anaconda\Scripts\..\envs"` with double quotes `"`. This makes the call to `abspath(_default_env)` in `conda.config` to fail to recognize that _default_env is already an abosulte path. I am not sure what is the best way to fix this though. Remove the quotes around the path in the env var? Check for quotes in conda.config.py and remove them?

**Comment by willyd** [comment]
Removing the double quotes indeed solves the problem.

**Comment by willyd** [comment]
cc @msarahan 

Commit https://github.com/conda/conda-env/commit/7909385ba7771687a26228984804e914e2840703 seems to have caused this problem. Should I make a PR with the quotes removed?

**Comment by clembou** [comment]
I had a similar issue on my machine, I could not use activate or deactivate to switch enviroments because double quotes had crept in my path on windows (java was the culprit). While it is not conda's fault it might be worth seeing if this problem can be handled gracefully on the conda side.

**Comment by soapy1** [comment]
I can't reproduce this issue on the newest version of conda. If this issue is still a problem for you please reopen
