### ISSUE TITLE
Trying to update with conda update -all getting many warnings No packages found in current linux-64 channels matching: <package>, skipping

### ISSUE THREAD

**Issue by ArthurZ** [conda/conda#1726]
Trying to update using conda update -all getting many warnings 
No packages found in current linux-64 channels matching: <package name>, skipping
e.g. Warning: No packages found in current linux-64 channels matching: r-rbokeh, skipping
etc.

**Comment by soapy1** [comment]
@ArthurZ is this still an issue for you?

**Comment by ArthurZ** [comment]
Hi @soapy1 not at all, it was my bad. The proper command has two hyphens:
```conda update --all```

**Comment by soapy1** [comment]
Cool, thanks!
