### ISSUE TITLE
conda info --file

### ISSUE THREAD

**Issue by remram44** [conda/conda#1739]
A lot of commands seem to be missing a way to operate on local files. A very obvious one is `conda info`, which is very useful and could probably be patched very easily (`conda install` supports it).

```
usage: conda info [-h] [--json] [-a] [-e] [-l] [-s] [--root]
                  [--unsafe-channels]
                  [packages [packages ...]]
```

**Comment by ilanschnell** [comment]
What should `conda info --file` do?  This is not obvious to me.

**Comment by remram44** [comment]
The same thing it does without --file, print out the metadata. Something like this:
```
$ conda info --file reprounzip-1.0.2-py2.7.tar.bz2
reprounzip 1.0.2 py2.7
----------------------
file name   : reprounzip-1.0.2-py2.7.tar.bz2
name        : reprounzip
version     : 1.0.2
build number: 0
build string: py2.7
size        : 49 KB
arch        : x86_64
license     : BSD License
machine     : x86_64
md5         : 84e8cf0db857b8993557cf6caecac0d1
operatingsystem: darwin
platform    : osx
subdir      : osx-64
target-triplet: x86_64-any-darwin
installed environments:
dependencies:
    python 2.7*
    pyyaml
    rpaths >=0.8
    setuptools
    usagestats >=0.3
```

**Comment by msarahan** [comment]
It would also be nice if conda --info showed the contents of the about: section of the recipe.

**Comment by remram44** [comment]
This issue has been *manually* marked as not stale because it has not been fixed. If you would like to keep sending your bots after people, please note:

1. This is a feature request and therefore could hardly go stale
1. No attempt or comment has been left by the team in the last 6 years, not even a "pull requests welcome"
1. Sending bots after people is rude. You might think you have no choice, still ouch

Thanks!

**Comment by remram44** [comment]
@conda You force us to talk to a bot and the bot doesn't work. What do I do here?
