### ISSUE TITLE
`conda list` doesn't have column headers

### ISSUE THREAD

**Issue by stuartarchibald** [conda/conda#1741]
The `conda list` command outputs 3 columns of data for which there are no column headers. The first appears to be `package name`, the second `version`, the third is possibly `feature+build number`? It would be great to have these headers added and could be done so in the already hash-prefixed lines so as not to upset filters/pipes relying on the package list format. Thanks.

**Comment by ChristianZimpelmann** [comment]
In addition, what would be the fourth column?

**Comment by kalefranz** [comment]
> and could be done so in the already hash-prefixed lines so as not to upset filters/pipes relying on the package list format

If you're doing that, just use the `--json` flag.  Otherwise, text parsing at your own risk!
