### ISSUE TITLE
conda install with a filename doesn't check dependencies

### ISSUE THREAD

**Issue by remram44** [conda/conda#1742]
I just installed a package from a file, and no additional download, failure or error message happened though the package had unmet dependencies.

**Comment by kalefranz** [comment]
That is by design.  Don't know how I feel about it, but tarballs get installed as-is.

**Comment by remram44** [comment]
Even pip is not that insane.

Is there any way to install dependencies, short of uploading it to anaconda.org to make conda download it?

**Comment by kalefranz** [comment]
Sure.  Use `conda index` and create a local channel.  conda-build actually does this for you automatically, with channel name `local`.  If you want to specify a local path to your own channel, use a `file://` url.
