### ISSUE TITLE
explicit environment with pip requirements? 

### ISSUE THREAD

**Issue by dkoppstein** [conda/conda#1745]
Hi, I recently found out about the explicit environment file format, created by, which allows you to specify which channel you get a particular package from. E.g.,

```
conda list --explicit > explicit-spec-file.txt
```

However, AFAIK it seems that this doesn't support pip dependencies supported by the old environment.yml format. Is there a way to put pip dependencies into the new "explicit" file format, or alternatively, to specify the channels in the old format?

**Comment by darribas** [comment]
Same problem here. Any new developments on this?

**Comment by bk-m** [comment]
I'd be interessted in this too.
