### ISSUE TITLE
Size of the Scipy library on Windows

### ISSUE THREAD

**Issue by rth** [conda/conda#1746]
At present Scipy takes 290 MB of disk space on Windows 8.1 64bit (using Python 3.4 and conda 3.16) and went up by almost 80 MB between Scipy versions 0.15 and 0.16 because of the addition of two Cython extensions: `scipy.linalg.cython_lapack` and `scipy.linalg.cython_blas`  with ~ 40 MB of disk space for each.

As a a comparison, the scipy wheel on pypi only takes 18 MB, a full install on Linux 64 bit takes 36 MB (and 96 MB with conda), which is much more reasonable. In the later case, the `cython_lapack` and `cython_blas` only take 500 kB. 

I understand that on Windows, necessary libraries are statically liked in the produced `.pyd` file. However this feels like the scipy install includes those libraries multiple times (i.e. for every cython or C extension). Can something be done about it? 

This  poses a problem when one has to make standalone executables with Pyinstaller or py2exe on Windows and the resulting `.exe` files become huge, particularly since scipy is a core dependency for a number of scientific python modules.

**Comment by tyler-thetyrant** [comment]
Closing as outdated.
