### ISSUE TITLE
"conda create -n dato-env python=2.7"  is blocked by SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

### ISSUE THREAD

**Issue by cpoptic** [conda/conda#1747]
I'm trying to create a new environment using the python 2.7 kernel but when I run the above command, there's an SSL cert that's not verified.  Any idea how to update/fix the SSL certificate?

C:\Anaconda3>conda create -n dato-env-2_7 python=2.7
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
....
Solving package specifications: ..........
Package plan for installation in environment C:\Anaconda3\envs\dato-env-2_7:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.0         |            vc9_0         583 KB
    python-2.7.10              |                3        17.9 MB
    ------------------------------------------------------------
                                           Total:        18.5 MB

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.0-vc9_0   [vc9]
    pip:          7.1.2-py27_0
    python:       2.7.10-3
    setuptools:   18.4-py27_0
    wheel:        0.26.0-py27_1

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/msvc_runtime-1.0.0-vc9_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/free/win-64/msvc_runtime-1.0.0-vc9_0.tar.bz2

**Comment by groutr** [comment]
can you post the output of `conda list`?

**Comment by cpoptic** [comment]
C:\Anaconda3>conda list
# packages in environment at C:\Anaconda3:
#
_license                  1.1                      py34_0
alabaster                 0.7.3                    py34_0
anaconda                  2.3.0                np19py34_0
argcomplete               0.8.9                    py34_0
astropy                   1.0.3                np19py34_0
babel                     1.3                      py34_0
bcolz                     0.9.0                np19py34_0
beautiful-soup            4.3.2                    py34_1
binstar                   0.11.0                   py34_0
bitarray                  0.8.1                    py34_1
blaze                     0.6.3                np19py34_0
blaze-core                0.8.0                np19py34_0
blz                       0.6.2                np19py34_1
bokeh                     0.9.0                np19py34_0
boto                      2.38.0                   py34_0
bottleneck                1.0.0                np19py34_0
certifi                   2015.9.6.2               py34_0
cffi                      1.1.0                    py34_0
clyent                    0.3.4                    py34_0
colorama                  0.3.3                    py34_0
conda                     3.18.3                   py34_0
conda-build               1.8.2                    py34_0
conda-env                 2.4.4                    py34_0
conda311fix               1.0                           0
configobj                 5.0.6                    py34_0
cryptography              0.9.1                    py34_0
cython                    0.22.1                   py34_0
cytoolz                   0.7.3                    py34_0
datashape                 0.4.5                np19py34_0
dateutil                  2.1                      py34_2
decorator                 4.0.4                    py34_0
docutils                  0.12                     py34_1
dynd-python               0.6.5                np19py34_0
fastcache                 1.0.2                    py34_0
flask                     0.10.1                   py34_1
future                    0.13.1                   py34_0
greenlet                  0.4.7                    py34_0
h5py                      2.5.0                np19py34_1
hdf5                      1.8.15.1                      2
idna                      2.0                      py34_0
ipykernel                 4.1.0                    py34_0
ipython                   4.0.0                    py34_0
ipython-notebook          4.0.4                    py34_0
ipython-qtconsole         3.2.0                    py34_0
ipython_genutils          0.1.0                    py34_0
itsdangerous              0.24                     py34_0
jdcal                     1.0                      py34_0
jedi                      0.8.1                    py34_0
jinja2                    2.8                      py34_0
jsonschema                2.4.0                    py34_0
jupyter_client            4.1.1                    py34_0
jupyter_core              4.0.6                    py34_0
launcher                  1.0.0                         1
libpython                 1.0                      py34_1
llvmlite                  0.5.0                    py34_0
llvmpy                    0.12.7                   py34_0
lxml                      3.4.4                    py34_0
markupsafe                0.23                     py34_0
matplotlib                1.4.3                np19py34_1
menuinst                  1.0.4                    py34_0
mingw                     4.7                           1
mistune                   0.7.1                    py34_0
mock                      1.0.1                    py34_0
multipledispatch          0.4.7                    py34_0
nbconvert                 4.0.0                    py34_0
nbformat                  4.0.1                    py34_0
networkx                  1.9.1                    py34_0
nltk                      3.0.3                np19py34_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py34_0
notebook                  4.0.6                    py34_0
numba                     0.19.1               np19py34_0
numexpr                   2.4.3                np19py34_0
numpy                     1.9.2                    py34_0
odo                       0.3.2                np19py34_0
openpyxl                  1.8.5                    py34_0
pandas                    0.16.2               np19py34_0
path.py                   8.1.2                    py34_0
patsy                     0.3.0                np19py34_0
pep8                      1.6.2                    py34_0
pickleshare               0.5                      py34_0
pillow                    2.8.2                    py34_0
pip                       7.1.2                    py34_0
ply                       3.6                      py34_0
psutil                    2.1.1                    py34_0
py                        1.4.27                   py34_0
pyasn1                    0.1.7                    py34_0
pycosat                   0.6.1                    py34_0
pycparser                 2.14                     py34_0
pycrypto                  2.6.1                    py34_3
pyflakes                  0.9.2                    py34_0
pygments                  2.0.2                    py34_0
pyopenssl                 0.15.1                   py34_1
pyparsing                 2.0.3                    py34_0
pyqt                      4.10.4                   py34_1
pyreadline                2.1                      py34_0
pytables                  3.2.0                np19py34_0
pytest                    2.7.1                    py34_0
python                    3.4.3                         0
python-dateutil           2.4.2                    py34_0
pytz                      2015.4                   py34_0
pywin32                   219                      py34_0
pyyaml                    3.11                     py34_2
pyzmq                     14.7.0                   py34_0
requests                  2.8.1                    py34_0
rope                      0.9.4                    py34_1
runipy                    0.1.3                    py34_0
scikit-image              0.11.3               np19py34_0
scikit-learn              0.16.1               np19py34_0
scipy                     0.15.1               np19py34_0
setuptools                18.4                     py34_0
simplegeneric             0.8.1                    py34_0
six                       1.9.0                    py34_0
snowballstemmer           1.2.0                    py34_0
sockjs-tornado            1.0.1                    py34_0
sphinx                    1.3.1                    py34_0
sphinx_rtd_theme          0.1.7                    py34_0
spyder                    2.3.5.2                  py34_0
spyder-app                2.3.5.2                  py34_0
sqlalchemy                1.0.5                    py34_0
statsmodels               0.6.1                np19py34_0
sympy                     0.7.6                    py34_0
toolz                     0.7.2                    py34_0
tornado                   4.2.1                    py34_0
traitlets                 4.0.0                    py34_0
ujson                     1.33                     py34_0
werkzeug                  0.10.4                   py34_0
wheel                     0.26.0                   py34_1
xlrd                      0.9.3                    py34_0
xlsxwriter                0.7.3                    py34_0
xlwings                   0.3.5                    py34_0
xlwt                      1.0.0                    py34_0
zlib                      1.2.8                         0

**Comment by groutr** [comment]
The latest certifi packages requires an updated cryptography and openssl.  I see you are using an old version of cryptography, though I don't see openssl.

**Comment by cpoptic** [comment]
I tried installing both the openssl and cryptography packages but alas, the SSL verification error blocks me.

C:\Anaconda3>conda install openssl
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
....
Solving package specifications: ................
Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2d             |           vc10_0         3.4 MB

The following NEW packages will be INSTALLED:

    openssl: 1.0.2d-vc10_0 [vc10]

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/openssl-1.0.2d-vc10_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/free/win-64/openssl-1.0.2d-vc10_0.tar.bz2


C:\Anaconda3>conda install cryptography
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
....
Solving package specifications: ......................
Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    six-1.10.0                 |           py34_0          17 KB
    cffi-1.2.1                 |           py34_0         109 KB
    cryptography-0.9.3         |           py34_0         1.1 MB
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following packages will be UPDATED:

    cffi:         1.1.0-py34_0 --> 1.2.1-py34_0
    cryptography: 0.9.1-py34_0 --> 0.9.3-py34_0
    six:          1.9.0-py34_0 --> 1.10.0-py34_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py34_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py34_0.tar.bz2

**Comment by groutr** [comment]
You may *temporarily* disable ssl verification (via .condarc) to install the updated cryptography and openssl.  In your .condarc add the line `ssl_verify: False`.  After updating cryptography and openssl, make sure you remove the ssl_very line in your .condarc.  Let me know if that solves the problem.

**Comment by cpoptic** [comment]
I created a .condarc file and added the ssl_verify: False  line and this allowed the openssl and cryptography packages to install successfully.  Thanks!  I commented out the ssl_verify line from the .condarc file too.

**Comment by SimonBiggs** [comment]
I received this exact same bug after I ran "conda update --all". My fix unfortunately was to uninstall and reinstall Anaconda.
