### ISSUE TITLE
conda clean -pt as non-root user with root anaconda install

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda#1751]
I have installed root miniconda at /opt/anaconda.  When running 
```
conda clean -pt
```
as a lesser user than root, I am seeing errors indicating conda is not checking permissions before attempting to delete package dirs:

```
conda clean -pt
Cache location: /opt/anaconda/pkgs
Will remove the following tarballs:

/opt/anaconda/pkgs
------------------
conda-3.18.3-py27_0.tar.bz2                  175 KB
conda-env-2.4.4-py27_0.tar.bz2                24 KB
itsdangerous-0.24-py27_0.tar.bz2              16 KB
markupsafe-0.23-py27_0.tar.bz2                30 KB
flask-0.10.1-py27_1.tar.bz2                  129 KB
jinja2-2.8-py27_0.tar.bz2                    263 KB
anaconda-build-0.12.0-py27_0.tar.bz2          69 KB
flask-wtf-0.8.4-py27_1.tar.bz2                12 KB
flask-ldap-login-0.3.0-py27_1.tar.bz2         13 KB

---------------------------------------------------
Total:                                       730 KB

removing conda-3.18.3-py27_0.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/envs/anaconda.org/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_clean.py", line 331, in execute
    rm_tarballs(args, pkgs_dirs, totalsize, verbose=not args.json)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_clean.py", line 156, in rm_tarballs
    os.unlink(os.path.join(pkgs_dir, fn))
OSError: [Errno 13] Permission denied: '/opt/anaconda/pkgs/conda-3.18.3-py27_0.tar.bz2'

```

**Comment by stephenakearns** [comment]
Hi @csoja - this issue is blocking some key Build System stability fixes. LMK if this can be prioritized (along with #1752 above)

**Comment by srossross** [comment]
@stephenakearns and @PeterDSteinberg and @csoja this issue is also now preventing us from moving forward with the anaconda-cluster build scripts.

**Comment by stephenakearns** [comment]
@csoja - I know you're strapped for resources and may have a new person taking a look at this. Can we bring it up in the platform meeting to discuss a possible solution

**Comment by ijstokes** [comment]
I believe this is yet another consequence of the more fundamental issue #1329

**Comment by pzwang** [comment]
@srossross Does Jason Vestuto's commit fix this problem sufficiently to allow you guys to move forward?

I think this doesn't really resolve the problems that @ijstokes has pointed out, but it might be enough for the build stuff.

**Comment by srossross** [comment]
I was under the impression that conda caches packages in the user home directory if it can not access the conda root. 

If this is true, a fix that would address the build issues would remove the cache in the user directory as well.

**Comment by srossross** [comment]
@groutr can you please address the question above?

**Comment by groutr** [comment]
I believe it does.  pkg_dirs is ultimately created from config.pkgs_dirs.
https://github.com/conda/conda/blob/master/conda/config.py#L164-L170

**Comment by srossross** [comment]
Given that info, is this issue still resolved?

**Comment by stephenakearns** [comment]
@csoja - spoke with @groutr about a dev build but @srossross isn't going to work in this scenario for us to get unblocked. Can we talk about scheduling a patch release of conda?
