### ISSUE TITLE
Create .condarc file in Windows

### ISSUE THREAD

**Issue by Isaacsh** [conda/conda#1757]
Hi

I have been trying to setup a .condarc file in Windows specifically for proxy_servers keys as suggested [here](http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers). One thing I figured out is that unlike Linux ( in which filenames starting with a dot is a convention for hidden files), starting a filename with dot does not do anything, so what I did was to create a text file with  
```
proxy_servers:
         http: http://19.12.2.105:83
```
and name it as .condarc without any extension, then put it in my root directory and anaconda directory and make them hidden. The result of running
```
conda info
```
is then
```
Current conda install:

             platform : win-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : C:\Users\[...]\AppData\Local\Continuum\Anaconda3  (writable)
  default environment : C:\Users\[...]\AppData\Local\Continuum\Anaconda3
     envs directories : C:\Users\[...]\AppData\Local\Continuum\Anaconda3\envs
        package cache : C:\Users\[...]\AppData\Local\Continuum\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
which shows 'None' for the config file.
Any hints/comments would be appreciated.

**Comment by groutr** [comment]
.condarc needs to be in your home directory or in the root environment.  I prefer having it my home directory (which on windows 7+ is usually `C:\Users\<username>`

**Comment by Isaacsh** [comment]
It currently is in the home directory as mentioned. Invoking ```conda config --get channels --system``` does not create any file in the directory neither.

**Comment by Isaacsh** [comment]
Invoking ```conda config --add channels r``` creates a .conda file for me then I modified it manually. Thx

**Comment by agine** [comment]
Thank you this helped me!

**Comment by jithurjacob** [comment]
Thanks a lot this helped me!!!!

**Comment by linwoodc3** [comment]
Can you add this to the http://conda.pydata.org/docs/config.html#the-conda-configuration-file-condarc page as an example.  It's not clear how to automatically create the file so adding a simple code block would save a lot of time if anyone agrees.

```python
conda config --add channels r
```

add that one block...would have saved me pain from reading the entire page several times :-(

**Comment by kerrywatson1** [comment]
@csoja FYI

**Comment by Qberto** [comment]
> Invoking conda config --add channels r creates a .conda file for me then I modified it manually. Thx

Thank you @Isaacsh ! This comment helped me!

**Comment by peteristhegreat** [comment]
By default it drops it at the root of `%home%` in windows.

**Comment by number161** [comment]
> Invoking `conda config --add channels r` creates a .conda file for me then I modified it manually. Thx

modify it how?

**Comment by Times125** [comment]
我也遇到这种情况，只能靠命令才有效。环境是win10专业版，用的miniconda

**Comment by jordan-carson** [comment]
> Invoking `conda config --add channels r` creates a .conda file for me then I modified it manually. Thx

For those working behind a firewall Isaacsh comment on does create the file, you can replace r with the actual channel to jfrog etc. Finally, you can run conda config --set ssl_verify no, OR if you edit the file manually you can add a line item beneath your channels and not indented with ssl_verify: false. So your file structure will look like the below (you should

channels:
     - [link to ur internal condo repo such as Jfrog]
ssl_verify: false
