### ISSUE TITLE
'conda update -all' versions confusion

### ISSUE THREAD

**Issue by wikiped** [conda/conda#1767]
Running `conda update -all` results in:

	The following packages will be downloaded:

		package                    |            build
		---------------------------|-----------------
		numpy-1.9.3                |           py27_0        23.5 MB
		numexpr-2.4.4              |       np19py27_0         120 KB
		scipy-0.16.0               |       np19py27_0        83.7 MB
		pandas-0.16.2              |       np19py27_0         4.6 MB
		pytables-3.2.2             |       np19py27_0         1.4 MB
		------------------------------------------------------------
											   Total:       113.4 MB

	The following packages will be UPDATED:

		numexpr:  2.4.4-np110py27_0  --> 2.4.4-np19py27_0
		pytables: 3.2.2-np110py27_0  --> 3.2.2-np19py27_0
		scipy:    0.16.0-np110py27_0 --> 0.16.0-np19py27_0

	The following packages will be DOWNGRADED:

		numpy:    1.10.1-py27_0      --> 1.9.3-py27_0
		pandas:   0.17.0-np110py27_0 --> 0.16.2-np19py27_0

It looks like `conda` considers `np19` to be an update to `np110`, which forces pandas to downgraded.

    conda info

				 platform : win-64
			conda version : 3.18.3
	  conda-build version : 1.18.1
		   python version : 2.7.10.final.0
		 requests version : 2.8.1
		 root environment : D:\Anaconda  (writable)
	  default environment : D:\Anaconda
		 envs directories : D:\Anaconda\envs
			package cache : D:\Anaconda\pkgs
			 channel URLs : https://repo.continuum.io/pkgs/free/win-64/
							https://repo.continuum.io/pkgs/free/noarch/
							https://repo.continuum.io/pkgs/pro/win-64/
							https://repo.continuum.io/pkgs/pro/noarch/
			  config file : C:\Users\User\.condarc
		is foreign system : False

**Comment by wikiped** [comment]
It appears the problem was caused by one of the packages being dependent on `np19` which pushed the rest of environment to live with that. After all packages using `numpy` were updated/reinstalled (with `np110` as dependency) `conda` did not offer downgrades.

**Comment by soupault** [comment]
thanks, worked for me!
to find the "blocking" package use `conda list` and look for `np19` versions.
for me it was shithole `dynd-python` package by Continuum...
