### ISSUE TITLE
online vs offline difference behavior

### ISSUE THREAD

**Issue by charlesconrad** [conda/conda#1768]
I am trying to install matplotlib offline. My conda info shown below. 

(testbuild)[cconrad@strangelove linux-64]$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.18.3
```

  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Projects/cconrad/miniconda  (writable)
  default environment : /Projects/cconrad/miniconda/envs/testbuild
     envs directories : /Projects/cconrad/miniconda/envs
        package cache : /Projects/cconrad/miniconda/pkgs
         channel URLs : file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/linux-64/
                        file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/noarch/
          config file : /home/cconrad/.condarc
    is foreign system : False

With offline = True in my .condarc file this is my output.

(testbuild)[cconrad@strangelove ~]$ conda install matplotlib
Fetching package metadata: ..
Solving package specifications: ....
Error: Could not find some dependencies for matplotlib: py2cairo 1.10.0, cairo 1.12.18

Did you mean one of these?

```
matplotlib
```

You can search for this package on anaconda.org with

```
anaconda search -t conda cairo 1.12.18
```

 (and similarly for the other packages)

You may need to install the anaconda-client command line client with

```
conda install anaconda-client
```

Both cairo and py2cairo are installled, as shown below.

(testbuild)[cconrad@strangelove ~]$ conda info cairo
Fetching package metadata: ..
## cairo 1.12.18 5

file name   : cairo-1.12.18-5.tar.bz2
name        : cairo
version     : 1.12.18
build number: 5
build string: 5
channel     : file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/linux-64/
size        : 592 KB
license     : LGPL 2.1, MPL 1.1
license_family: LGPL
md5         : 4dccfee9316c2d72d7baacc074fef661
sig         : None
subdir      : linux-64
installed environments:
    /Projects/cconrad/miniconda
    /Projects/cconrad/miniconda/envs/oncsq
    /Projects/cconrad/miniconda/envs/testbuild
dependencies:
    fontconfig 2.11.1
    freetype 2.5.5
    libpng 1.6.17
    pixman 0.26.2
    zlib 1.2*

(testbuild)[cconrad@strangelove ~]$ conda info py2cairo
Fetching package metadata: ..
## py2cairo 1.10.0 py27_2

file name   : py2cairo-1.10.0-py27_2.tar.bz2
name        : py2cairo
version     : 1.10.0
build number: 2
build string: py27_2
channel     : file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/linux-64/
size        : 36 KB
license     : LGPL 2.1 and MPL 1.1
md5         : 3e6c28f080cd2515fa262212ab153f0d
sig         : None
installed environments:
    /Projects/cconrad/miniconda
    /Projects/cconrad/miniconda/envs/oncsq
    /Projects/cconrad/miniconda/envs/testbuild
dependencies:
    cairo 1.12.18
    python 2.7*

With offine = False

(testbuild)[cconrad@strangelove ~]$ conda install matplotlib
Fetching package metadata: ......
Solving package specifications: ...................
Package plan for installation in environment /Projects/cconrad/miniconda/envs/testbuild:

The following NEW packages will be INSTALLED:

```
matplotlib: 1.4.3-np110py27_2
```

Proceed ([y]/n)? 

Conda recognizes that when I try to install with online enabled.

Any clues to why I'm getting this behavior would be helpful. In an issue related to this trying to update wheel from 0.24 to 0.26 while offline tells me it has unsatisfiable dependencies.

(testbuild)[cconrad@strangelove ~]$ conda install wheel==0.26
Fetching package metadata: ..
Solving package specifications: ......
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|###################################################| 100%

Hint: 'wheel' has unsatisfiable dependencies (see 'conda info wheel')

(testbuild)[cconrad@strangelove ~]$ conda info wheel
Fetching package metadata: ..
## wheel 0.24.0 py27_0

file name   : wheel-0.24.0-py27_0.tar.bz2
name        : wheel
version     : 0.24.0
build number: 0
build string: py27_0
channel     : file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/linux-64/
size        : 75 KB
license     : MIT
md5         : 51bb94c9f9f33d2013663af450df76dd
sig         : None
subdir      : linux-64
installed environments:
    /Projects/cconrad/miniconda
    /Projects/cconrad/miniconda/envs/oncsq
dependencies:
    python 2.7*
## wheel 0.26.0 py27_1

file name   : wheel-0.26.0-py27_1.tar.bz2
name        : wheel
version     : 0.26.0
build number: 1
build string: py27_1
channel     : file:///Projects/cconrad/ONCSTools/trunk/CondaRepo/linux-64/
size        : 76 KB
license     : MIT
md5         : 831d08e31a80c2f4c01d456c018c6ee1
sig         : None
subdir      : linux-64
installed environments:
    /Projects/cconrad/miniconda/envs/testbuild
dependencies:
    python 2.7*

**Comment by ijstokes** [comment]
I'm not a conda expert, and I've had these same sort of issues.  Hopefully an "expert" will respond, but in the mean time I'd try:

`conda install --offline --use-local --use-index-cache matplotlib`

and see if that works for you.  Let us know the results!

**Comment by jhoare** [comment]
I believe I've determined the cause of this and have reported it: #1797
