### ISSUE TITLE
Improve conda search

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1772]
@ahmadia identified problems with current search results in https://github.com/Anaconda-Server/anaconda-server/issues/710.  I believe we need to improve the results by:
- we need to prioritize exact matches first
- then we need to use some distance metric factored in to the remaining order

I have also created an issue for this on the Anaconda Server side (which impacts the web GUI and the CLI client): https://github.com/Anaconda-Server/anaconda-server/issues/919

**Comment by anna-liao** [comment]
Does https://github.com/conda/conda/pull/5597 resolve this issue?
