### ISSUE TITLE
recursion bug attempting to install r-irkernel

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1777]
See output of `conda install r-irkernel` in this file, as well as output of `conda info -a` (at the end).

[conda_recursion_bug.txt](https://github.com/conda/conda/files/26788/conda_recursion_bug.txt)

**Comment by ahmadia** [comment]
@ijstokes - didn't this get resolved in the latest version of conda?

**Comment by ahmadia** [comment]
Can you check this isn't a dupe of https://github.com/conda/conda/issues/1748 and resolved by https://github.com/conda/conda/pull/1749

**Comment by ijstokes** [comment]
@ahmadia and @mcg1969 looks like the bug might still be there.  The above `conda_recursion_bug.txt` file has the output of `conda info-a` at the end and I'm using `conda version : 3.18.3`

**Comment by mcg1969** [comment]
It definitely looks like it, and yet I can't reproduce it on mac for some reason (even if I include `-c wakari` `-c r`). Will investigate further.

**Comment by mcg1969** [comment]
Ah, I got it. Had to create a new environment, not just install `r-irkernel`

**Comment by mcg1969** [comment]
Actually, it looks like my fix was reverted in 3.18.3 somehow.

**Comment by mcg1969** [comment]
It hasn't been reverted; the new version hasn't been pushed out. Definitely a duplicate then.

**Comment by ijstokes** [comment]
FWIW, 3.17.0 works OK.

**Comment by mcg1969** [comment]
Yes, that's to be expected.

**Comment by mcg1969** [comment]
This is solved by 3.18.4, which was just released.
