### ISSUE TITLE
Add authentication property to `.condarc`

### ISSUE THREAD

**Issue by vmuriart** [conda/conda#1784]
I been trying to set up a private conda channel on a private webserver that requires the user to authenticate for access. This is similar to [this](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/tLUFkHd7DDc) or [this](https://github.com/pypa/pip/issues/1182) from `pip`. 

A more generic solution is to allow the use of requests `auth` property to pass along method/library and parameters needed  to authenticate into the network. 
The `.condarc` file would look like:

```
Authenticate:
  library: requests-ntlm
  username: "Joe"
  password: "pass"
```

where `library` can be any python package that can be used by requests. The other fields will then be passed to the library as parameter when the `CondaSession` is created.

**Comment by cometchaser** [comment]
An user authentication is already feasible. Just use 
http://[user]:[passwd]@your-repo-server.foo 
in your .condarc

However, writing the password in plain text is not a good idea..
Please have a look at #6969

**Comment by szhem** [comment]
@cometchaser user and password in the authority party of the channel's URL seems not to be very secure. 
Just consider the following configuration
```
channel_alias: https://user:password@<corporate-proxy>/repository/raw-conda-channels-cache/
default_channels:
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/
```
In that case if you will try to search for a package that cannot be found, then conda will print all the credentials onto the screen 
```
$ conda search fasttext 
Loading channels: done
No match found for: fasttext. Search: *fasttext*

PackagesNotFoundError: The following packages are not available from current channels:

  - fasttext

Current channels:

  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/noarch
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/noarch
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mwimpelb18** [comment]
Is there any workaround for this?  I'm trying to separate the authentication piece from the .condarc file altogether.

**Comment by dataslicer** [comment]
The password requirements goes beyond just a simple alphanumeric characters to include special characters.  
Passwords that complies to these requirements are breaking the .condarc parsers.  


```
$ conda config --show
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 30, in execute
    execute_config(args, parser)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 135, in execute_config
    d = OrderedDict((key, getattr(context, key)) for key in paramater_names)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 135, in <genexpr>
    d = OrderedDict((key, getattr(context, key)) for key in paramater_names)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/base/context.py", line 615, in channel_alias
    location, scheme, auth, token = split_scheme_auth_token(self._channel_alias)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/common/url.py", line 317, in split_scheme_auth_token
    url_parts = urlparse(cleaned_url)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
    result = func(*args, **kwargs)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/common/url.py", line 130, in urlparse
    return parse_url(url)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/urllib3/util/url.py", line 196, in parse_url
    raise LocationParseError(url)

conda._vendor.urllib3.exceptions.LocationParseError: Failed to parse: USERID:PasswordWithSpecialCharacters
```

Context:
```
$ conda -V
conda 4.9.2

$ grep -A1 channel .condarc
show_channel_urls: true

channel_alias: https://USERID:PasswordWithSpecialCharacters#me2@YOURDOMAIN.com/conda-proxy/

channels:
  - conda-forge
```

Hopefully this provides another perspective why this is enhancement is necessary.

Is there another workaround available for this situation?

**Comment by jamesp** [comment]
For basic authentication, at least, there is a workaround for this. 

Under the covers conda uses `requests` for the session management and has support for header-based basic authentication.  Specifically, if there is no authentication encoded in the url, it will fall back to the netrc protocol. These lines in the codebase: https://github.com/conda/conda/blob/ed96a06244eb820781dc872eb381f51b95ee48ae/conda/gateways/connection/session.py#L122-L127

For your example above @dataslicer, this would mean adding the following to `~/.netrc`:
```
machine YOURDOMAIN.com
username USERID
password PasswordWithSpecialCharacters#me2
```
and setting its permissions appropriately: `chmod 700 ~/.netrc`.

In my testing, this has the effect of authenticating all conda requests to the given domain without printing the password to stdout or disk.  The following `.condarc` works:
```
channel_alias: https://YOURDOMAIN.com/conda-proxy/

channels:
  - conda-forge
```
Then
```
conda install -c conda-forge ...
```

Packages are installed via the proxy (specifically JFrog Artifactory in our use case #9973) using header-based rather than url-based authentication.  This also has the additional benefit that the username and password are not written in plain text in the conda tool output, nor the conda-meta JSON files written to disk.

It would be great if the conda core development team considered expanding this support for basic authentication a little further, for example offering a mechanism to use a "Authorization: Bearer [Token]" style header, and documenting this as an alternative to including the username and password in the channel url.
