### ISSUE TITLE
Error when trying to install scikit-learn 0.17 - post-link failed for: conda-env-2.4.4-py35_1

### ISSUE THREAD

**Issue by mathusuthan** [conda/conda#1786]
Hi,
When I tried to update scikit-learn to the latest version, I get the error 
"not was unexpected at this time.                                         |   0%
Error: Error: post-link failed for: conda-env-2.4.4-py35_1"

The entire log from the command prompt is given below 
PS C:\WINDOWS\system32> conda install scikit-learn
Fetching package metadata: ....
Solving package specifications: .......................
Package plan for installation in environment C:\Anaconda3:

The following NEW packages will be INSTALLED:

    conda-env:    2.4.4-py35_1
    scikit-learn: 0.17-np110py35_1

Proceed ([y]/n)? y

Linking packages ...
not was unexpected at this time.                                         |   0%
Error: Error: post-link failed for: conda-env-2.4.4-py35_1

**Comment by msarahan** [comment]
Hi,

Can you tell us more about your system?

That post-link script is new, intended to make sure that (PREFIX)\Library\bin is on your PATH environment variable.  It has been tested on Windows 7 with Miniconda 3.16 system-level and user-level installations.

It may fail if PATH is already too long.

Can you please post back with:
  - Your PATH (User and system PATH, please)
  - Your anaconda version that you're updating from (plus 32 or 64-bit)
  - Your system info (windows 7, 32 or 64 bit)

**Comment by msarahan** [comment]
One further detail that would be helpful: this appears to be a system-wide installation.  Are you logged in as the same user that you did the initial install with?  It doesn't have to be the same user, but it does have to be a user with administrative rights.  For system-wide installations, PATH modification requires elevation.  If your user can't elevate, or if you cancel the elevation dialog, this problem might arise.

**Comment by mathusuthan** [comment]
Hi,

I am running Windows 10  Anaconda 2.4.0  64-bit ...

And yes, I am trying to update the package logged in as the same user when
I installed Anaconda ...

My PATH variables:

USER PATH:
--------------
C:\Users\mathusuthan\AppData\Roaming\cabal\bin;D:\Program Files
(x86)\Git\bin;C:\Program Files\Oracle\VirtualBox;C:\Program
Files\Intel\WiFi\bin\;C:\Program Files\Common
Files\Intel\WirelessCommon\;E:\apache\maven-3.3.1\bin\;%JAVA_HOME%\bin;%SPARK_HOME%\bin;C:\Program
Files
(x86)\scala\bin;C:\blaslapack;C:\Users\mathusuthan\AppData\Local\atom\bin;C:\Users\mathusuthan\AppData\Roaming\npm

SYSTEM PATH:
---------------
C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;d:\gcc-4.6.3\bin;d:\gcc-4.6.3\libexec\gcc\x86_64-pc-mingw32\5.1.0;C:\Program
Files\Haskell\bin;D:\Program Files\Haskell
Platform\2014.2.0.0\lib\extralibs\bin;D:\Program Files\Haskell
Platform\2014.2.0.0\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Rtools\bin;D:\Rtools\gcc-4.6.3\bin;%R_HOME%\bin\x64\;C:\Program
Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\MiKTeX
2.9\miktex\bin\x64\;C:\Program Files (x86)\Skype\Phone\;C:\Program
Files\Intel\WiFi\bin\;C:\Program Files\Common
Files\Intel\WirelessCommon\;C:\Users\mathusuthan\.dnx\bin;C:\Program
Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\sbt\\bin;C:\Program Files
(x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\Haskell
Platform\2014.2.0.0\mingw\bin;%USERPROFILE%\.dnx\bin;D:\Program Files
(x86)\scala\bin;D:\Program Files
(x86)\Git\cmd;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;D:\Program
Files\nodejs\;D:\HashiCorp\Vagrant\bin;C:\Program Files\MATLAB\R2015b\bin;

Thanks !!

**Comment by msarahan** [comment]
Yes, PATH length is the problem.  SETX seems to barf if PATH is > 1024 characters long.  I will try to come up with a workaround.  For now, please confirm that the post-script failing to run has not broken your system.  I think the error may well be harmless here, but I want to confirm with you.

**Comment by msarahan** [comment]
PS: in case you're curious, yours is 1131 characters.

**Comment by mathusuthan** [comment]
Thank you ...

BTW, what happened was scikit-learn was removed and I am now unable to
reinstall the older version 0.16.1  or update to the new version 0.17.

Will wait for your fix or try tomorrow with a truncated PATH.

Again, thank you very much for the support.

**Comment by sinepigen87** [comment]
Hi,

I get the same error. I've installed Anaconda2-2.4.0-Windows-x86 on Windows 7, 32-bit using the default installation settings. I checked my Path and it seems that it created a new User variable named PATH with C:\Users\siro\AppData\Local\Continuum\Anaconda2;C:\Users\siro\AppData\Local\Continuum\Anaconda2\Scripts;C:\Users\siro\AppData\Local\Continuum\Anaconda2\Library\bin

Nothing was added to the system variable Path:
C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Dwimperl\perl\bin;C:\Dwimperl\perl\site\bin;C:\Dwimperl\c\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\;C:\Program Files\QuickTime\QTSystem

Maybe this can help.

Thanks,

Sine (...who is new to anaconda and python)

**Comment by sinepigen87** [comment]
...I uninstalled anaconda2-2.4.0 and installed anaconda 2.3.0 instead and it seem doesn't produce any error so far!

Sine

**Comment by senis000** [comment]
Exact same here with windows 7 and anaconda 2.4.0 64 bits

the update of scikit-learn 0.17 not only failed but removed all the previous files of scikit-learn

**Comment by vrtsig** [comment]
Same here on Win 8.1, 64 bit, single user install, full anaconda 3-2.4.0-64. My PATH is only 299 characters, though.

```
>conda update scikit-learn
Fetching package metadata: ....
Solving package specifications: .......................
Package plan for installation in environment C:\Users\Fabian\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.1         |           vc14_0         2.2 MB
    conda-env-2.4.4            |           py35_1          52 KB
    scikit-learn-0.17          |      np110py35_1         3.5 MB
    ------------------------------------------------------------
                                           Total:         5.7 MB

The following packages will be UPDATED:

    conda-env:    2.4.4-py35_0       --> 2.4.4-py35_1
    msvc_runtime: 1.0.0-vc14_0       [vc14] --> 1.0.1-vc14_0     [vc14]
    scikit-learn: 0.16.1-np110py35_0 --> 0.17-np110py35_1

Proceed ([y]/n)?

Fetching packages ...
msvc_runtime-1 100% |###############################| Time: 0:00:04 554.56 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00  86.63 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:08 407.72 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
not was unexpected at this time.#######                                  |  33%
Error: Error: post-link failed for: conda-env-2.4.4-py35_1
```

**Comment by woosungpil** [comment]
same issue on WIn7, single user install, anaconda2-2.4.0-64, my path is also short. same error with above

**Comment by jelmelk** [comment]
I'm getting the same issue as @senis000, the issues started by trying to upgrade `scikit-learn` to `v0.17`. I received the error: `Error: Error: post-link failed for: conda-env-2.4.4-py35_1` which caused `scikit-learn` and `conda-env` to uninstall.

If I try to install either `scikit-learn` or `conda-env` I get the error mentioned above. When trying to do  `conda update -all`, the following error is generated:

    [Anaconda3] C:\WINDOWS\system32>conda update --all
    Fetching package metadata: ....
    Solving package specifications: ....................................................................................................................................................................................................................................
    Error: Unsatisfiable package specifications.
    Generating hint:
    [      COMPLETE      ]|##################################################| 100%
    
    
    Hint: 'libpng' has unsatisfiable dependencies (see 'conda info libpng')
    
    Note that the following features are enabled:
      - vc9
      - vc14
      - vc10
    
    
    [Anaconda3] C:\WINDOWS\system32>conda update conda-env
    Error: package 'conda-env' is not installed in C:\Anaconda3
    
    [Anaconda3] C:\WINDOWS\system32>

**Comment by ebyrne** [comment]
+1 on a similar issue.  Win 10, new Anaconda install, getting this for any conda-env install with the same error.

My path is below, below 1024 char, and no user path.  Tried a few permutations of removing portions and doesn't seem to have an effect.  No residual effects on either path post-failure.  Happy to test as needed..

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Anaconda;C:\Anaconda\Scripts;C:\Anaconda\Library\bin

**Comment by allthedata** [comment]
Also have the same issue, Win 8.1, fresh single user install of Anaconda 64-bit 3.5. Trying to install any new packages makes conda try to update conda-env, which fails with the post-link error. And then trying to reinstall any of the versions of conda-env for py35 (by forcing the version) results in the same error. My PATH is also less than 1024 characters.

**Comment by msarahan** [comment]
Hi,

We are working on a fix.  Please see https://github.com/conda/conda/issues/1783#issuecomment-154713946

I will post here and at the many other issues when we have a tested, known-good fix.

**Comment by msarahan** [comment]
This issue should be fixed.  The relevant fixed packages were:

python-2.7.10-4.
python-3.4.3-4
python-3.5.0-3

conda-env-2.4.4 (build 2)
menuinst-1.2.2

The fix is that the conda-env post-link script has been removed.  It has been replaced by a modified Lib/site.py file in each Python installation, plus a library_bin.pth file in each Python installation.  The combination of these lead to Library/bin being added to os.environ["PATH"] for any Python process.  Any programs you install that end up in Library/bin (for example, patch) will still not be on PATH for older installations.  You can either modify PATH to add Library/bin yourself, or uninstall and reinstall using a new installer (Anaconda >= 2.4.0; Miniconda >= 3.18)

I'm closing this issue, but please reopen it if you are still having issues.

**Comment by jelmelk** [comment]
I'm receiving the following error when I'm trying to install `conda-env` since it was uninstalled due to the original error:

    [Anaconda3] C:\WINDOWS\system32>conda install conda-env
    Fetching package metadata: ....
    Solving package specifications: ....................
    Package plan for installation in environment C:\Anaconda3:
    
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        python-3.5.0               |                3        36.2 MB
        conda-env-2.4.4            |           py35_2          51 KB
        ------------------------------------------------------------
                                               Total:        36.3 MB
    
    The following NEW packages will be INSTALLED:
    
        conda-env: 2.4.4-py35_2
    
    The following packages will be UPDATED:
    
        python:    3.5.0-2 --> 3.5.0-3
    
    Proceed ([y]/n)? y
    
    Fetching packages ...
    python-3.5.0-3 100% |###############################| Time: 0:00:07   5.11 MB/s
    conda-env-2.4. 100% |###############################| Time: 0:00:00 418.14 kB/s
    Extracting packages ...
    [      COMPLETE      ]|##################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Linking packages ...
    not was unexpected at this time.################                         |  50%
    Error: Error: post-link failed for: conda-env-2.4.4-py35_2
    
    [Anaconda3] C:\WINDOWS\system32>

**Comment by vrtsig** [comment]
fixed for me after a clean install. Thank you!

**Comment by msarahan** [comment]
@jelmelk you need to manually delete the .conda-env-post-link.bat script in C:\Anaconda3\Scripts - the conda-env package no longer includes it.  I am hesitant to write another post-link script to try to remove it, but will do so if too many people get stuck here.

**Comment by jelmelk** [comment]
@msarahan, that did fix the issue, now `conda update --all` is giving dependency issue for `tk` should I open a new ticket or is this known?

**Comment by msarahan** [comment]
I think it's related in general to the broad dependency issues people are having all over the place.  We have a lot of work to do to figure out how things got into an inconsistent state, and figure out how to restore consistency.  Please go ahead and file a new issue, though, for tracking purposes.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.
