### ISSUE TITLE
error installing r-essentials package

### ISSUE THREAD

**Issue by david-romano** [conda/conda#1789]
![page1](https://cloud.githubusercontent.com/assets/15707628/11016933/42877e2a-8544-11e5-81fc-a489dcfe8ef7.png)
![page2](https://cloud.githubusercontent.com/assets/15707628/11016934/50c6ba82-8544-11e5-82aa-cd9837ba24ab.png)

**Comment by mcg1969** [comment]
This is solved by 3.18.4, which was just released.

**Comment by ccordoba12** [comment]
Closing then.

**Comment by david-romano** [comment]
Excellent -- thanks!
