### ISSUE TITLE
pip installs incompatible package in python 3 enviornment

### ISSUE THREAD

**Issue by hargup** [conda/conda#1791]
This happens with the [gevent](https://pypi.python.org/pypi/gevent/1.0.2) package. Even though `gevent` is incompatible with python 3, running `pip install gevent` in a python 3 environment installs it which later leads to unexpected syntax errors.

**Comment by msarahan** [comment]
Is this really a conda issue?  Pip has nothing to do with Conda - if Pip happily installs a Python 2-only package into Python3, then that is a problem likely with the package itself not specifying that it is compatible with Python3.  I actually don't know if Pip even has a way to specify a particular Python version dependency. =(

In a Conda recipe, you would specify this with a version pin in the gevent package.

**Comment by hargup** [comment]
> Is this really a conda issue?

Depends on how do you specify what is a conda issue. pip installs the package in a conda environment so it definitely affects a conda user, also conda is aware of the package as it lists it with `conda list -n <env>` so it might be possible for conda to check for package dependencies after pip installs it. I worked on `conda skeleton` during my internship and as far as I remember there were ways check for python version dependency from PyPI, not sure about it though.

BTW this package is available with `conda install` which works correctly test for python version dependency, so feel free to skip this issue if you feel it is out of scope
