### ISSUE TITLE
Unsatisfiable dependency when using conda update -all

### ISSUE THREAD

**Issue by jelmelk** [conda/conda#1793]
The issue presists with not only this package, but many others. Everytime I run `conda update -all` it errors on a new package. So far running it 5 times resulted in dependency issue for: `tk`, `hdf5`, `libpng`, `tk`, and `jpeg`.

    Activating environment "C:\Anaconda3"...
    
    [Anaconda3] C:\WINDOWS\system32>conda update --all
    Fetching package metadata: ....
    Solving package specifications: ..............................................................................................................................................................................................................................................
    Error: Unsatisfiable package specifications.
    Generating hint:
    [      COMPLETE      ]|##################################################| 100%
    
    
    Hint: 'jpeg' has unsatisfiable dependencies (see 'conda info jpeg')
    
    Note that the following features are enabled:
      - vc14
      - vc10
      - vc9
    
    
    [Anaconda3] C:\WINDOWS\system32>

**Comment by j9ac9k** [comment]
This is a duplicate issue of #1779 and some other issues that have been reported; TL;DR you're not alone! :)

**Comment by jelmelk** [comment]
@j9ac9k, you're correct, this one was opened as mentioned here https://github.com/conda/conda/issues/1786#issuecomment-154875347 If it needs to be closed that's fine.

**Comment by jelmelk** [comment]
`conda update --all` works now.

[Anaconda3] C:\WINDOWS\system32>conda update --all
    Fetching package metadata: ....
    Solving package specifications: .......................................................................................................................................................................................................................................................
    Package plan for installation in environment C:\Anaconda3:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        patch-2.5.9                |                1          56 KB
        pytz-2015.7                |           py35_0         167 KB
        sip-4.16.9                 |           py35_2         229 KB
        astropy-1.0.6              |      np110py35_0         3.6 MB
        clyent-1.0.0               |           py35_0          13 KB
        pyqt-4.11.4                |           py35_3         3.8 MB
        anaconda-client-1.1.2      |           py35_0          92 KB
        ------------------------------------------------------------
                                               Total:         8.0 MB

    The following NEW packages will be INSTALLED:

        patch:           2.5.9-1

    The following packages will be UPDATED:

        anaconda-client: 1.1.0-py35_0      --> 1.1.2-py35_0
        astropy:         1.0.5-np110py35_1 --> 1.0.6-np110py35_0
        clyent:          0.4.0-py35_0      --> 1.0.0-py35_0
        pyqt:            4.11.4-py35_2     --> 4.11.4-py35_3
        pytz:            2015.6-py35_0     --> 2015.7-py35_0
        sip:             4.16.9-py35_1     --> 4.16.9-py35_2

    Proceed ([y]/n)?

**Comment by thomco** [comment]
I am now seeing this issue with `conda update anaconda`.  This seems to be since the latest anaconda update to 2.5 a few days ago.   As `update -all` is working, should I create a new issue for this?

```
conda update anaconda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ..............................................................................................................................................................................................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - anaconda
  - python 3.5*

Use 'conda info anaconda' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
```
