### ISSUE TITLE
Color and graphical elements in terminals for progress, success, failure, etc.

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1800]
The conda CLI would be improved from a user experience perspective by incorporating color and graphical elements into standard operations such as package install, info, etc.  Some inspiration for this comes from homebrew and powerline:

https://github.com/riobard/bash-powerline

**Comment by ijstokes** [comment]
I think the Anaconda Server team has developed `clyent` which is a very nice toolset for building powerful and aesthetically pleasing CLIs: 

https://github.com/Anaconda-Server/clyent

It has now been incorporated into `anaconda-client` (AFACIT) and has provided exactly some of the visual features I was mentioning/requesting in this issue.  I'm sure @srossross or @dsludwig would be happy to talk to whoever on the Conda team might be in a position to incorporate some `clyent` functionality.

**Comment by srossross** [comment]
Thanks @ijstokes , I would be happy to give a tour of clyent if anyone wants to learn.
