### ISSUE TITLE
Valid package names?

### ISSUE THREAD

**Issue by Jorge-C** [conda/conda#1804]
The [docs](http://conda.pydata.org/docs/spec.html#package-metadata) don't seem to pose any restrictions, as long as it's lowercase.

At the [biocore/conda-recipes](https://github.com/biocore/conda-recipes) repo we're building conda packages for many bioinformatics tools, and we just found that it's possible to build a package called `blast+`, but uploading it to anaconda does not work. Is anaconda being overzealous at error checking, or should conda build fail outright? We hope it's the former :)

See a travis log where it builds successfully but fails to upload [here](https://travis-ci.org/biocore/conda-recipes/jobs/90430498#L487).

Thanks!

**Comment by tyler-thetyrant** [comment]
Assuming from the name of packaage, `blash+`, I think it was an UnicodeError, which is now support with the recent versions of conda (on most systems).
