### ISSUE TITLE
PyQT Broken on Conda

### ISSUE THREAD

**Issue by elakhna** [conda/conda#1811]
Getting the following error:

Error: Error: post-link failed for: pyqt-4.11.4-py27_3

**Comment by wulmer** [comment]
Try to install the latest `qt` package first before installing the `pyqt` package.

Somehow, the post-link script of `pyqt` is executed before the `qt` package is properly installed. And the post-link script tries to copy a Qt configuration file which doesn't exist at that time.
Installing them one at a time fixes this dependency issue.

**Comment by ccordoba12** [comment]
@msarahan, This seems to require a fix in our pyqt package.

**Comment by msarahan** [comment]
Yes, I agree, but I think it is more a fix for the package installation process, rather than the pyqt package.  The problem is that installation happens in alphabetical order, so pyqt comes before qt.

**Comment by ccordoba12** [comment]
Yep, the package is fine, the things that's failing is running the post-link script.

**Comment by gregbehm** [comment]
I confirmed that (my prefix)\Library\bin is in PATH, but file qt.conf is not in \Library\bin. Copying qt.conf from another location into \Library\bin gives me a work-around until this problem gets resolved.

**Comment by CostGranda** [comment]
@gregbehm where did you found the qt.conf file?

**Comment by gregbehm** [comment]
In C:\Users\{me}\Anaconda2\ or in C:\Users\{me}\Anaconda2\pkgs\pyqt-4.11.4-py27_3\

**Comment by wulmer** [comment]
Hm... the manual copying of `qt.conf` or changing the installation order manually works, but what is really annoying is the fact that any manual workarounds will not work when running `conda build`. I currently can't build any package that requires `pyqt`. Only workaround is to fix the dependency to the old version `4.10.4` manually in the `meta.yaml` file.

@msarahan Is there a way to collect all the post-link scripts that fail and then retry executing them after all other packages have been linked? I think this could easily go into [instructions.py](https://github.com/conda/conda/blob/master/conda/instructions.py#L148) where the `LINK` commands are executed. Catch all failed post-links (need a special error category for that?) and then retry linking those packages. Might be helpful running a dependency analysis for those failed packages, but I think a simple retry will work in most cases.

**Comment by wulmer** [comment]
I just successfully tried a patch for the [old `execute_plan`](https://github.com/conda/conda/blob/3.7.3/conda/plan.py#L537), which is similar to the [current `execute_instructions`](https://github.com/conda/conda/blob/master/conda/instructions.py#L116) method.

1. I simply create a list for the failed commands before [line 547](https://github.com/conda/conda/blob/3.7.3/conda/plan.py#L547) (`failed_commands = []`)
2. Then add a `try: ... except SystemExit: failed_commands.append((cmd, arg))` around [line 569](https://github.com/conda/conda/blob/3.7.3/conda/plan.py#L569) which adds all failed link actions to the `failed_commands` list.
3. Then, just before the end of the method, I simply retry those failed packages: `for cmd, arg in failed_commands: link(prefix, arg, index=index)`.

Works for me, and seems like a pragmatic solution which might solve most of the post-link issues.

Sorry that it's only a solution for the old conda 3.7.3, but that's the version we are currently using.

**Comment by msarahan** [comment]
@Wulmer, thanks.  I will try to work this into a PR very soon.  Anything that makes post-link scripts work more reliably will be a good thing.

**Comment by msarahan** [comment]
For the sake of completeness, here's a link to the PR implementing @wulmer suggestion: https://github.com/conda/conda/pull/1874

**Comment by rbinnun2** [comment]
PyQT now installs as a dependency with Conda - thanks!
