### ISSUE TITLE
Error in Package Cache Location

### ISSUE THREAD

**Issue by BafBar** [conda/conda#1817]
I recently reinstalled Anaconda with Anaconda2.

Right after installation, i run conda update conda and obtain the following error:

![image](https://cloud.githubusercontent.com/assets/11828197/11152186/16ea2b86-89ff-11e5-8adb-7721af8848b1.png)

The folder Users\%UserName%\.pkgs indeed does not exist. After checking the conda info:

![image](https://cloud.githubusercontent.com/assets/11828197/11152213/3d38aaec-89ff-11e5-8073-48645eb7cd87.png)

The package cache is wrong. I want to update it to the real one which is inside the %username%\Anaconda2 folder.

Is that an error from the installer or did I do something wrong ? Thanks for the help.

**Comment by groutr** [comment]
Looks like conda is not handling spaces very well in some cases.  I'll look into it.  Thanks for filing the issue.

**Comment by groutr** [comment]
Could you please post the output of the following commands, run inside the python interpreter in your root environment?
```
from conda import config
print(config.envs_dirs)
print(config.pkgs_dirs)
```
Also, do you have `CONDA_ENVS_PATH` set in your environment?

**Comment by BafBar** [comment]
Hi @groutr ,

I actually renamed my %username% folder to remove the space before i saw your reply and it worked.
If you need feedback to fix the issue and want additional info, let me know.

Thank you.

**Comment by kalefranz** [comment]
Outdated. Closing.
