### ISSUE TITLE
Wrong python version with conda init when using python 2.7.10

### ISSUE THREAD

**Issue by tomashek** [conda/conda#1821]
We are building a python distribution and want to include conda. A simple way to add conda to our python is using pip. I understand that pip-installing conda is deprecated, but don't know how else to install conda when we need to use our own python installation.
After installing conda using pip, I ran into what looks like a parsing bug now that the minor version of cpython has two digits:

$ ./pip install conda
Collecting conda
Collecting conda-env (from conda)
Collecting pycosat (from conda)
Collecting requests (from conda)
  Using cached requests-2.8.1-py2.py3-none-any.whl
Collecting pyyaml (from conda)
Installing collected packages: conda-env, pycosat, requests, pyyaml, conda
Successfully installed conda-3.17.0 conda-env-2.4.2 pycosat-0.6.1 pyyaml-3.11 requests-2.8.1
$ ./conda init

WARNING: conda init is deprecated.....
Initializing conda into: /myhome/pythonwithconda
$ ./conda list
# packages in environment at /myhome/pythonwithconda:
#
conda                     3.17.0                        0
conda-env                 2.4.2                     <pip>
pip                       7.1.2                     <pip>
pycosat                   0.6.1                     <pip>
python                    2.7.1                         0  
pyyaml                    3.11                      <pip>
requests                  2.8.1                     <pip>
setuptools                18.2.dev0                 <pip>

NOTICE the python version is listed as 2.7.1 when it is actually 2.7.10.

$ ./conda update conda
Fetching package metadata: ......
Error: No packages found in current linux-64 channels matching: python 2.7.1 0

You can search for this package on anaconda.org with
    anaconda search -t conda python 2.7.1 0
You may need to install the anaconda-client command line client with
    conda install anaconda-client
Note that you have pinned specs in /myhome/pythonwithconda/conda-meta/pinned:
    ['python 2.7.1 0']

Manually editing the "pinned" file to remove the space between the 1 and 0 allows "conda update conda" to work, but "conda list" still shows the python version as 2.7.1.

**Comment by tyler-thetyrant** [comment]
We cannot guarantee the full functionality of the pip-installed conda. The only way to get fully functioning conda to any systems is to following the official conda installation guide.
