### ISSUE TITLE
Incorrect result for np.rint on Win32, numpy 1.10.1, MKL

### ISSUE THREAD

**Issue by matthew-brett** [conda/conda#1824]
Sorry for the repetition - I just reported this to numpy : https://github.com/numpy/numpy/issues/6685

However, it seems to be an issue specific to MKL, and therefore to the (only?) conda numpy packages for Windows 32-bit.

With 32-bit numpy + MKL on Windows:

```
>>> import numpy as np
>>> ds = 4607998452777363968
>>> int(float(ds))
4607998452777363968L
>>> int(np.rint(ds))
4607998452777363456L
```

I do not get this error from:
- conda 32-bit + numpy 1.9.3;
- conda 64-bit + numpy 1.10.1;
- Python.org Python + the sourceforge numpy 1.10.1 superpack installers;

I do get the same error from the (now removed?) Christoph Gohlke numpy 1.10.1 32-bit MKL wheels.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1711
