### ISSUE TITLE
wrong install directory in boost 1.57.0 for Python 3.5 on Windows

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#1834]
Executing the following on Windows:
```
conda create -n python3 python=3.5
activate python3
conda install boost
```
installs the boost DLLs in `$CONDA_ACTIVE_ENV/Library/lib` instead of `$CONDA_ACTIVE_ENV/Library/bin` where they belong.

**Comment by ccordoba12** [comment]
I'll take it into account when updating Boost this week. Thanks for reporting.

**Comment by ccordoba12** [comment]
This was fixed on our Boost recipe present in conda-recipes. New packages will be available soon.
