### ISSUE TITLE
Anaconda prepends to path upon "activate"

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda#1846]
On installations where adding Anaconda to the path is not desired apparently activating an environment will prepend Anaconda to the PATH even after deactivating the source. This will stay until a new terminal session is started. If a user needs to run system python this will cause an issue as Anaconda will take over the PATH. This is true for Linux and Mac OS X.

**Comment by ispmarin** [comment]
Confirmed here too. 

http://stackoverflow.com/questions/33955516/anaconda-activate-deactivate-cycle-messes-up-path
