### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__' when update Anaconda

### ISSUE THREAD

**Issue by a3n** [conda/conda#1848]
> conda update --prefix C:\Anaconda anaconda
> ...
> Extracting packages ...
> [      COMPLETE      ]|##################################################| 100%
> An unexpected error has occurred, please consider sending the
> following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '**getitem**'

> c:\anaconda\lib\site-packages\conda\install.py(658)ensure_write()
> -> files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")](Pdb)
> 
> conda info
> Current conda install:

```
         platform : win-64
    conda version : 3.11.0-dirty
```

  conda-build version : 1.10.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by waterguy77** [comment]
I am having the same error message.

C:\Users\Matt\Anaconda>conda update conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Users\Matt\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.1         |            vc9_0         1.1 MB
    conda-env-2.4.5            |           py27_0          65 KB
    menuinst-1.3.1             |           py27_0          96 KB
    pyyaml-3.11                |           py27_2         167 KB
    requests-2.8.1             |           py27_0         609 KB
    setuptools-18.5            |           py27_0         648 KB
    wheel-0.26.0               |           py27_1         116 KB
    conda-3.18.9               |           py27_0         219 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:         4.4 MB

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.1-vc9_0   [vc9]
    wheel:        0.26.0-py27_1

The following packages will be UPDATED:

    conda:        3.11.0-py27_0 --> 3.18.9-py27_0
    conda-env:    2.1.4-py27_0  --> 2.4.5-py27_0
    menuinst:     1.0.4-py27_0  --> 1.3.1-py27_0
    pip:          6.1.1-py27_0  --> 7.1.2-py27_0
    pyyaml:       3.11-py27_0   --> 3.11-py27_2
    requests:     2.7.0-py27_0  --> 2.8.1-py27_0
    setuptools:   16.0-py27_0   --> 18.5-py27_0

Proceed ([y]/n)? y

menuinst-1.3.1 100% |###############################| Time: 0:00:00 298.90 kB/s
Fetching packages ...
msvc_runtime-1 100% |###############################| Time: 0:00:01 796.78 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00 255.27 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 318.58 kB/s
requests-2.8.1 100% |###############################| Time: 0:00:01 604.45 kB/s
setuptools-18. 100% |###############################| Time: 0:00:01 534.76 kB/s
wheel-0.26.0-p 100% |###############################| Time: 0:00:00 267.22 kB/s
conda-3.18.9-p 100% |###############################| Time: 0:00:00 307.98 kB/s
pip-7.1.2-py27 100% |###############################| Time: 0:00:01 785.53 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Matt\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Users\Matt\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'

C:\Users\Matt\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Users\Matt\Anaconda  (writable)
  default environment : C:\Users\Matt\Anaconda
     envs directories : C:\Users\Matt\Anaconda\envs
        package cache : C:\Users\Matt\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by a3n** [comment]
I "solved" this issue on Windows by deleting Anaconda and installing the most recent Anaconda. It didn't take too long.

I didn't see the issue on Linux.

**Comment by waterguy77** [comment]
Thanks for the reply.  I actually did the same.

**Comment by kalefranz** [comment]
Outdated. Closing.
