### ISSUE TITLE
'conda install -c pandas pandas' doesn't see the available package

### ISSUE THREAD

**Issue by wikiped** [conda/conda#1849]
Trying to update `pandas` to the latest available version (0.17.1) from pandas channel with:

`conda install -c pandas pandas --override-channels`

results in:

```
Fetching package metadata: ..
Error: No packages found in current win-64 channels matching: python 2.7*

You can search for this package on anaconda.org with

    anaconda search -t conda python 2.7*
```

While the package is clearly there:
`https://anaconda.org/pandas/pandas/v0.17.1/download/win-64/pandas-v0.17.1-np110py27_0.tar.bz2`

Current conda install:

```
             platform : win-64
        conda version : 3.18.5
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
```

**Comment by naught101** [comment]
Have you tried `conda install -c https://conda.anaconda.org/pandas pandas`?

**Comment by wikiped** [comment]
I had tried that as well.

It is not a 'dead end' kind of issue, since there is local install and `pandas` has been updated in conda channel. Just thought this is something worth to be aware of.

**Comment by tyler-thetyrant** [comment]
I cannot replicate the error with the recent version of conda.
