### ISSUE TITLE
graphviz causing erorrs when installed

### ISSUE THREAD

**Issue by jelmelk** [conda/conda#1851]
I tried installing [graphviz v2.38](https://anaconda.org/asmeurer/graphviz) by running `conda install graphviz`. The installation causes error when trying to launch Qtconsole and that wouldn't let spyder to launch at all. https://github.com/ContinuumIO/anaconda-issues/issues/552

I got it to work by doing `conda install -f qt` after installing `graphviz`, but now I get this:

```
import graphviz
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3813d87ba683> in <module>()
----> 1 import graphviz

ImportError: No module named 'graphviz'
```

I'm assuming it's because it's an outdated module, maybe it could be built with this other setup of [graphviz v0.4.8](https://pypi.python.org/pypi/graphviz).

Also realized the module is OSX only.

**Comment by QCaudron** [comment]
I'm having the same issue. graphviz 2.38.0 is installed successfully through conda, but calling `import graphviz` in Python gives me `ImportError: No module named graphviz`. I realised this when I tried importing `dot_graph` from `dask.dot`, which tries to import graphviz.

Also running OSX. Any help would be fantastic.

**Comment by zhang01GA** [comment]
I am having the same issue in anaconda 2.5.0

**Comment by Horta** [comment]
Same here. I get "ImportError: No module named graphviz" after installing it using conda.

I'm using Anaconda 2.5.0, OSX.

**Comment by brickerino** [comment]
I installed graphviz with pip, looks like it works, so far.
Bug with conda exists, though.

**Comment by jcrist** [comment]
The conda  package `graphviz` is for the `graphviz` library/command-line tool. There are many python wrappers for this, but they all have different names (`pydot`, `pygraphviz`, etc...).

**Comment by LesGuessing** [comment]
Same problem. Conda install error.  pip install graphviz   worked.

**Comment by ccordoba12** [comment]
Thanks for reporting. Right now we're working to fix this and several other problems with graphviz.

**Comment by rolando** [comment]
I was following `dask` documentation and stumble upon this issue. Running `pip install graphviz` *after* `conda install graphviz` fixed this issue for me.

**Comment by ilanschnell** [comment]
When you `conda install graphviz` you get the "C/C++" package (from the default conda repo), not the Python bindings to graphviz.

**Comment by jeiros** [comment]
So why is it still not detecting it even if I just install it from pip?

**Comment by jorisvandenbossche** [comment]
@ilanschnell I understand that you only get the C package with `conda install graphviz`, but this is pretty confusing when one of the python bindings is *also* called `grapviz`(https://pypi.python.org/pypi/graphviz), when that is also the name for the python library to install suggested in the dask error message, and when pip installing it does actually work.

**Comment by Atcold** [comment]
So, is there any official solution to this? Should a warning message be issued specifying the package name conflict?

**Comment by LesGuessing** [comment]
I don't know, I gave up long ago. thanks for asking.

**Comment by Atcold** [comment]
@LesGuessing, thank you for getting back to me.
As a newbie, I've been told "don't use `pip` if you have `conda`". And here I had to do so.
So, you know, it feels a tad hack-ish...
If `conda` would prompt the user to use `pip`, that would be just fine, IMO.

**Comment by kalefranz** [comment]
We have a solution for this.  The specification is [here](https://gist.github.com/mcg1969/20667002c79f702e3c7003c81b5f24c8).  It'll hopefully be complete over the coming months.

**Comment by LesGuessing** [comment]
thanks. I have recently been using PIP and it seems fine.
appreciate your attention on it.

On Fri, Jan 27, 2017 at 10:27 AM, Alfredo Canziani <notifications@github.com

**Comment by tskarsten** [comment]
Following steps worked for me on my windows machine:
1. Install Graphviz from http://www.graphviz.org/Download_windows.php
2. Add C:\Program Files (x86)\Graphviz2.38\bin to the PATH 
3. Run "pip install graphviz" in the command line

**Comment by QtRoS** [comment]
I am facing this issue now.

**Comment by Juanlu001** [comment]
Perhaps add a `post-link` note to inform the users that they still need to `pip install graphviz`?

**Comment by leighton613** [comment]
OSX Sierra, Python 2.7, Graphviz 2.38

Using `pip install graphviz` and `conda install graphviz` BOTH resolves the problem.

`pip` only gets path problem and `conda` only gets `ImportError` same as here.

**Comment by mindlessbrain** [comment]
I did both `conda install -c anaconda graphviz` and `conda install -c anaconda python-graphviz` and then `import graphviz` started to work.

**Comment by LesGuessing** [comment]
very cool. Thanks much.

**Comment by keithwoj** [comment]
I performed the steps mindlessbrain recommended and graphviz now works. It seems that, as some of the other posters suggested, the `conda install graphviz` command merely installs the C-bindings, you need the `python-graphviz` command as well.

**Comment by Melech** [comment]
mindlessbrain's recommendation worked for me in windows

**Comment by zhugw** [comment]
but when I install graphviz in osx I met this error

```
(base) ➜  ~ conda install -c anaconda graphviz
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - graphviz -> freetype=2.5 -> libpng==1.6.17
  - seaborn -> matplotlib -> freetype[version='>=2.8,<2.9.0a0']
Use "conda info <package>" to see the dependencies for each package.
```
and I do not know how to solve it?

**Comment by yoavo1984** [comment]
@zhugw, I did :
`conda update matplotlib` 

and then followed mindlessbrain advice and now it works.

**Comment by zhugw** [comment]
@yoavo1984 

Thanks! unfortunately in my machine it seems `graphviz` especially difficult to install

```
# After update matplotlib successfully

(base) ➜  ~ conda install -c anaconda graphviz
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - graphviz -> freetype=2.5 -> libpng==1.6.17
  - graphviz -> jpeg=8
  - pillow -> freetype[version='>=2.8,<2.9.0a0']
Use "conda info <package>" to see the dependencies for each package.
```
So this time should I remove `pillow`?

**Comment by babuasian** [comment]
Had the same issue of not working, post install through Anaconda.
Able to accomplish this library deployment with the help of Terminal install using the std. command.

**Comment by Deepanshu8391** [comment]
Hey,
I have followed the following steps and it worked fine for me.
1 . Download and install graphviz-2.38.msi from
    https://graphviz.gitlab.io/_pages/Download/Download_windows.html

2 . Set the path variable
    (a) Control Panel > System and Security > System > Advanced System Settings > Environment Variables > Path > Edit
    (b) add 'C:\Program Files (x86)\Graphviz2.38\bin'

**Comment by IraMix** [comment]
Running pip install graphviz after conda install graphviz has also fixed this issue for me. Many thanks

**Comment by yw5aj** [comment]
`conda install python-graphviz` worked the best for me. `pip install graphviz` sometimes causes `graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng'], make sure the Graphviz executables are on your systems' PATH`.
