### ISSUE TITLE
[FR] Conda should have more aggressive HTTP caching

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda#1853]
It would be nice to have more aggressive HTTP caching in conda (and repo.continuum.io and conda.anaconda.org), especially for the `fetch_index` call that occurs at the beginning of many user interactions. With a couple channels added, this often takes ~1000ms for me.
1. Currently, my understanding is that some caching is used only when the user supplies a special flag (`--use-index-cache`), which I assume is rare. But even this cache is pretty ineffective.
2. On anaconda.org, the `repodata.json.bz2` file is not served with any ETag / Expires  / Cache-Control headers.
3. On `https://repo.continuum.io/`, the `repodata.json.bz2` file is served with ETag, but not Expires or Cache-Control headers. Without those headers, you can't avoid a trip to the server, even if the response is cached.
4. Instead of manually operating a cache, as is done in `fetch_repodata()`, all of this could be done transparently with a library like [CacheControl](http://cachecontrol.readthedocs.org/en/latest/index.html). IIRC, this is what pip does as well. But obviously it requires the right HTTP headers.

**Comment by rmcgibbo** [comment]
(cc https://github.com/conda/conda/issues/400#issuecomment-41204714)

**Comment by kalefranz** [comment]
Conda's caching is pretty aggressive at this point.  Or as aggressive as it can be.  We *do* respect Cache-Control headers by default as of conda 4.3.  You can also override the default behavior or respecting the Cache-Control value via condarc config.

```
local_repodata_ttl
  default: 1
  For a value of False or 0, always fetch remote repodata (HTTP 304
  responses respected). For a value of True or 1, respect the HTTP
  Cache-Control max-age header. Any other positive integer values is the
  number of seconds to locally cache repodata before checking the remote
  server for an update.
```
