### ISSUE TITLE
activate.bat

### ISSUE THREAD

**Issue by jnfred** [conda/conda#1854]
on windows anaconda 2.4, activate.bat first lines are

if "%CONDA_ENVS_PATH%" == "" (
    REM turn relative path into absolute path
    FOR /F %%i IN ("%~dp0..\envs") DO set CONDA_ENVS_PATH=%%~fi

so for anaconda2 install  on c:\program files, result is CONDA_ENVS_PATH=program

is it the expected result?

**Comment by msarahan** [comment]
No, that's a bug.  This will be fixed for the Anaconda 2.4.1 release in early December.
