### ISSUE TITLE
Suggestion for unsatisfiable packages hint

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda#1859]
A lot of issues that are reported come down to, in some sense, the unsatisfiable package specifications hint being not particularly helpful. e.g. #517,  #1801, https://github.com/ContinuumIO/anaconda-issues/issues/556, others.

One thing I noticed when stepping through is that (at least in all of the cases that I was looking at), the logging in [prune_packages](https://github.com/conda/conda/blob/master/conda/resolve.py#L458) is actually the quite useful. Especially once the minimal subset of the matchspecs has been identified, the error often comes in that method, and the package that gets pruned down to zero matching files is often the "critical" one has a dependency that can't be met.

For example, currently the triple `('python 3.5*', 'numpy 1.9*', 'statsmodels')` is unsatisfiable on win-64, and the "hint" is obviously just that they conflict. This isn't too helpful because you go look and see a `statsmodels-0.6.1-np19py35` package available in the index. But if you look in `prune_packages`, you see pretty that the cause is really `patsy`, which gets pruned to zero doesn't have a np19py35 release. 

I'm sure this won't help in all cases, but as a heuristic, I think that if toposort the matchspecs and then 
applying the pruning, the first thing to crash out might be a pretty good hint to report.

**Comment by rmcgibbo** [comment]
Here is a reference implementation of the idea. It works pretty well from what I've tried: https://github.com/rmcgibbo/conda-hint.

**Comment by groutr** [comment]
This is a promising idea.  I'll bring it up with the team and see what happens from there.

**Comment by mcg1969** [comment]
Yes, I thought of this when I worked on the pruning patch! It is a promising idea, and you might have taken it further than I did. Ultimately I was not satisfied it could cover cases as well as the current hint generation. That is why I explicitly decided to just punt if prune_packages found an unsatisfiable scenario.

**Comment by rmcgibbo** [comment]
Were there any hard cases that you think it didn't work for? The cases I tried worked pretty well, but I'm sure they weren't exhaustive.

**Comment by mcg1969** [comment]
I can't recall a specific set, no. But I did encounter some challenges during my testing, and ultimately felt that I didn't have sufficient time to spend fleshing it out. What you've done here is far more work than I put into the effort!
