### ISSUE TITLE
IOError while creating env from local tar.bz2 file

### ISSUE THREAD

**Issue by vnitinv** [conda/conda#1872]
[nitinkr@svl-junos-d056 ~]$ pwd
/homes/nitinkr
[nitinkr@svl-junos-d056 ~]$ env
SHELL=/bin/bash
TERM=xterm-256color
SSH_CLIENT=172.29.226.54 56342 22
OLDPWD=/homes/nitinkr/conda-3.17.0
SSH_TTY=/dev/ttyp8
USER=nitinkr
SSH_AUTH_SOCK=/tmp/ssh-4hsrhxwEfU/agent.23106
FTP_PASSIVE_MODE=YES
UNAME_r=7.1-RELEASE-JNPR-8
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/homes/nitinkr/bin:/homes/nitinkr/pyez/bin
MAIL=/var/mail/nitinkr
BLOCKSIZE=K
PWD=/homes/nitinkr
SHLVL=1
HOME=/homes/nitinkr
PYTHONPATH=/homes/nitinkr/pyez:/homes/nitinkr/pyez/lib/python2.7/site-packages
LOGNAME=nitinkr
SSH_CONNECTION=172.29.226.54 56342 10.160.2.59 22
_=/usr/bin/env
[nitinkr@svl-junos-d056 ~]$ conda create -n nits linux-64-junos-eznc-1.2.3-py27_0.tar.bz2 
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/homes/nitinkr/pyez/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/homes/nitinkr/pyez/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/homes/nitinkr/pyez/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/homes/nitinkr/pyez/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/homes/nitinkr/pyez/lib/python2.7/site-packages/conda/cli/install.py", line 204, in install
    verbose=not args.quiet)
  File "/homes/nitinkr/pyez/lib/python2.7/site-packages/conda/misc.py", line 204, in install_local_packages
    shutil.copyfile(src_path, dst_path)
  File "/usr/local/lib/python2.7/shutil.py", line 82, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/homes/nitinkr/.conda/envs/.pkgs/linux-64-junos-eznc-1.2.3-py27_0.tar.bz2'
[nitinkr@svl-junos-d056 ~]$ ls linux-64-junos-eznc-1.2.3-py27_0.tar.bz2
linux-64-junos-eznc-1.2.3-py27_0.tar.bz2
[nitinkr@svl-junos-d056 ~]$ pwd
/homes/nitinkr
[nitinkr@svl-junos-d056 ~]$ conda info
Current conda install:

```
         platform : unknown-32
    conda version : 3.17.0
```

  conda-build version : not installed
       python version : 2.7.2.final.0
     requests version : 2.8.1
     root environment : /usr/local  (read only)
  default environment : /usr/local
     envs directories : /homes/nitinkr/.conda/envs
                        /homes/nitinkr/envs
                        /usr/local/envs
        package cache : /homes/nitinkr/.conda/envs/.pkgs
                        /homes/nitinkr/envs/.pkgs
                        /usr/local/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/unknown-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/unknown-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : True
# NOTE:
# root directory '/usr/local' is uninitialized

**Comment by kalefranz** [comment]
Report is for conda 3.17.0.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.
