### ISSUE TITLE
conda on offline devices

### ISSUE THREAD

**Issue by vnitinv** [conda/conda#1873]
I created junos-eznc package at https://anaconda.org/vnitinv/junos-eznc/files
this has dependencies on many (including lxml) https://github.com/Juniper/py-junos-eznc/blob/master/requirements.txt

Now I installed conda on a linux box (without internet connectivity) 
when I did
conda create -n nits linux-64-junos-eznc-1.2.3-py27_0.tar.bz2 --offline

I get 

[nitinkr@svl-junos-d056 ~]$ conda create -n nits linux-64-junos-eznc-1.2.3-py27_0.tar.bz2 --offline
[      COMPLETE      ]|###################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|###################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################################################| 100%
Fetching package metadata: 
Error: No packages found in current unknown-32 channels matching: lxml >=3.2.4

You can search for this package on anaconda.org with

```
anaconda search -t conda lxml >=3.2.4
```

You may need to install the anaconda-client command line client with

```
conda install anaconda-client
```

Is that when I did conda build for junos-eznc It didnt included it dependencies inside its package.
If not is there a way. As my linux box is behind firewall, no access to internet. Either I will have to download each dependencies and then install it individually. In that case conda doesnt serve any purpose on top of pip for me. 

Anticipating your help.

**Comment by kalefranz** [comment]
You can use local `file://` channels and `conda index`, which is part of conda-build.
