### ISSUE TITLE
`conda install -f` implies `--no-deps` which is a problem for meta-packages

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1878]
I believe this is related to #466 and #1255, but perhaps not.

First, it is unclear to me _why_ the `-f` option to `conda install` should imply `--no-deps`.  Certainly I would say that most people would not expect this to be the case.

But that issue aside, it is a problem for meta-packages which _only_ consist of dependencies.  If I do `conda install -f jupyter` then I want to force-install all the dependency packages specified the jupyter meta-package.  More than "I want", in fact "I expect" that is what will happen.  But it doesn't.  And I would suggest that the average user is not going to pick up on the visual hints that force-install of meta-packages do not install the dependencies.  They will just be confused that it hasn't happened or oblivious that it hasn't happened.

**Comment by robintw** [comment]
I've just been hit by this problem too.

What is the reason behind `-f` implying `--no-deps`? And is there any possibility of it being changed?

**Comment by mcg1969** [comment]
@robintw, perhaps you might want to weigh in on #2928. It is genuinely not clear to me how it is supposed to work in a logical and consisten manner to do `--force` with dependencies, but if we can spec it out, it could be done.

**Comment by ijstokes** [comment]
@kalefranz and @mcg1969 can someone explain why @tyler-thetyrant closed this issue with no further comment?

@mcg1969 If someone is doing a force install then they should be warned that this means they may end up with an inconsistent environment.  Since conda can figure out if it WILL be an inconsistent environment it would be nice if it could actually tell the user if this is going to be the case or not.  And then provide a `[y/N]` option to proceed (default to `N`).  And I would go further to suggest that this should not imply `--no-deps` unless the user explicitly specifies it.  When would they specify it?  When installing dependencies makes it impossible to force install **a set of packages** (either from their abstract names or from actual tarballs).  But if I'm only specifying a single "thing" (abstract package name, `MatchSpec`, or `/path/to/a/single/tarball`), then there will only be a single dependency tree to resolve and all those dependencies should be "force installed" as well.

Does that make sense?

I hope it is OK if I re-open this.  I'm happy for it to be closed if there is some explanation as to why it was closed.

**Comment by kalefranz** [comment]
I don't know.  Thanks for reopening it.

**Comment by kalefranz** [comment]
Part of the problem is that we've overloaded `--force` to have way too mean meanings at this point.  The Solver code in conda 4.4 does try to disentangle these somewhat.  We've used `--force` for at least the following:

* force-remove a package, bypassing the solver entirely
* force-install just a single package, bypassing the solver entirely,
* force-reinstall a package (i.e. uninstall then install again)
* force-remove a package that is a dependency of conda itself in the root environment
* force-clobbering paths that already exist in a new environment

**Comment by ChrisBarker-NOAA** [comment]
I actually like that -f implies --no-deps, and for that matter that installing a particular package directly implies --force, and thus --no-deps.

Hard to say way exactly, but I know that I get really frustrated with pipi when it keeps trying to install does that I don't want it to.

But it would be nice if there was a --with-deps option. In fact, maybe it would install the deps, but not the package itself...

`conda install-deps package_name`

maybe?

**Comment by kalefranz** [comment]
Conda 4.4 has the following different modes that can be given to the solver, along with separate boolean `force_remove` and `force_reinstall` flags.

```python
class DepsModifier(Enum):
    """Flags to enable alternate handling of dependencies."""
    NO_DEPS = 'no_deps'
    ONLY_DEPS = 'only_deps'
    UPDATE_DEPS = 'update_deps'
    UPDATE_DEPS_ONLY_DEPS = 'update_deps_only_deps'
    UPDATE_ALL = 'update_all'
    FREEZE_INSTALLED = 'freeze_installed'  # freeze is a better name for --no-update-deps
```

**Comment by ChrisBarker-NOAA** [comment]
awesome!

That should do it -- as long as it's documented were we can find it :-)

-CHB

**Comment by kalefranz** [comment]
We're working on figuring out how to update the docs for conda 4.4.  Might just move everything to readthedocs so we can have them versioned properly.

**Comment by mcg1969** [comment]
Frankly, I _still_ have yet to see a complete explanation of how `--force` would work if it _didn't_ also imply no-deps. I'm open to being convinced but I almost invariably find that people are asking for `conda` to work some sort of magic it simply cannot. #2928 captures my best thinking on the topic.

So if I had to guess why this was closed, it was because it basically duplicated #2928, and is a "wontfix".

I _do_ like the idea of `--deps-only` or something like that.

**Comment by ijstokes** [comment]
@mcg1969 you are persuading me with your #2928 arguments.  I will close this issue since I think it now, for me, boils down to appropriate documentation for the other flags @kalefranz has listed above, and appropriate warnings to users that:

* dependencies are not installed if `--force` is used
* dependencies are not installed if a tarball is specified
* a meta-package (consisting entirely of dependencies) will not install any of those dependencies (I appreciate this is a special case we may not want to identify/handle differently)
* `--force` may break the current environment (and warn the user if that is going to happen)
