### ISSUE TITLE
pyproj package is built incorrectly.

### ISSUE THREAD

**Issue by mtreiber** [conda/conda#1879]
The pyproj package is built incorrectly and as a result the proj.4 library isn't being linked properly.  This has incorrectly been identified as an issue on the proj.4 issue tracker here:

https://github.com/jswhit/pyproj/issues/17

but the anaconda.org package available here:

https://anaconda.org/ioos/pyproj

installs and works fine.

**Comment by ccordoba12** [comment]
Pinging @groutr about this one :-)

**Comment by jorisvandenbossche** [comment]
See also https://github.com/ioos/conda-recipes/pull/539#issuecomment-152817656 where this was fixed in the ioos channel

**Comment by groutr** [comment]
I will investigate this as soon as I can.

**Comment by ocefpaf** [comment]
Maybe https://github.com/ioos/conda-recipes/issues/534#issuecomment-157354393 is also relevant.
