### ISSUE TITLE
Conda packages should contain authoritative dependency information

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1882]
A package's `meta.yaml` or its equivalent should be embedded into every package.  I should be able to look at a package tarball and find out _exactly_ what its dependencies are.  Right now that isn't the case.  In fact the situation is (I would argue) worse than that because it _appears_ that the dependencies are embedded, but what is in there is not, in fact, the "real" details of the package dependency.  I still don't understand what the `requires` and `info.json` files contain, but I'm told that the definitive dependencies live elsewhere in a `repodata.json` file that is managed on the package server but not (easily? at all?) available to the conda user who has fetched the package.

A concrete discussion of this can be found here with lots of examples:

https://github.com/ContinuumIO/anaconda-issues/issues/563

**Comment by ilanschnell** [comment]
Closing issue, as https://github.com/ContinuumIO/anaconda-issues/issues/563 had also been closed.

**Comment by ijstokes** [comment]
@ilanschnell I don't think this issue is resolved: I've read over ContinuumIO/anaconda-issues#563 again and it seems like this in-package "dependency" information is non-authoritative.  I don't understand how that can come to pass except by intentional manual manipulation or construction of a bad conda package.

**Comment by ilanschnell** [comment]
As mentioned earlier, `repodata.json` is the definite source of truth, as far as conda is concerned.  I'm not sure this is still confusing.

**Comment by kalefranz** [comment]
Statements above no longer accurate.  The source of truth for package information is within the package itself.  This change happened within the last several months.
