### ISSUE TITLE
Conda install <file.tar.bz2> still does not install dependencies

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#1884]
Even though this seems to have been addressed by #992, it is not working for me in the latest version, 3.18.7.

conda install package_file.tar.bz2 only uncompresses the file without looking at the dependencies.

**Comment by ccordoba12** [comment]
This feature was removed in conda 3.18.2 (I think). You need to use the `--use-local` install option to install local packages.

**Comment by Zaharid** [comment]
Are there any plans to fix this? At the moment trying to install a local package that is also in the channels is an absolute nightmare (e.g to test conda build)..

I believe that:

 - `conda install <file.tar.bz2>` should do the obvious thing: Resolve the dependencies in the current environment and install the package. It should also check for the architecture but is not so urgently required.

 - `conda install package --use-local` should behave exactly as described above if there is a compatible file in conda-bld, and possibly warn the user or even fail otherwise. It should not try to find the packages in the channels because the obvious use case for `--use-local` is testing local packages. Right now it pulls the remote package even if the version is lower.

**Comment by ccordoba12** [comment]
Support for pulling dependencies when installing from tarballs was removed several months ago and it's not coming back. I clearly said it above, I don't know why you keep insisting with that.

When using `--use-local` you need to explicitly specify the version of your package in the command line, if it's for a package that's also distributed by us.

**Comment by ccordoba12** [comment]
I'm closing this because we don't plan to go back to the old behavior, and `--use-local` is a perfectly fine alternative to install from tarballs.

**Comment by Zaharid** [comment]
Well, I'd argue that neither is it documented anywhere nor is it the behaviour I'd guess most people would expect.  Why not disable conda install tarball altogether then?

As for `--use-local`, only removing the corresponding channel from .condarc was the only thing that worked for me. I believe it should be easier and proposed how.

**Comment by Zaharid** [comment]
E.g.
http://docs.continuum.io/anaconda/faq#id4

doesn't say anything about not installing properly from a tarball.

**Comment by PierreKiwi** [comment]
Good evening,
Actually using *--use-local* does not work because it systematically installs the latest locally built package!

Use case
- My project named Baker has 2 branches: `workflows` and `pipeline` respectively 53 and 62 commits ahead of master so their versions are `1.0.5-py27_53` and `1.0.5-py27_62` (I am using GIT_DESCRIBE_TAG and GIT_DESCRIBE_NUMBER).
- I have two jobs building each branch separately in a specific and independent conda env.
- I need to install the locally built package in this environment so I use the option `--use-local`.

So far so good BUT conda is not smart enough to distinguish between the locally built packages... So in my workflows job's environment, I actually installed the build built by the pipeline branch which is highly incompatible!!!

OK fair enough, what about the real .tar ball? I can install it using `conda install <tar ball file>` BUT Conda does not install the dependencies when you install a tar ball directly...

What's the solution to install a specific build?
Does the test phase install the `.tar` ball file?

**Comment by jkroes** [comment]
Is there any update on documentation and behavior of the `--user-local` option? It sounds like the default behavior is to try and install a local package on disk, but otherwise conda attempts to pull from a package from a channel. Has this changed, and if not, where is this documented?

**Comment by ezyang** [comment]
Yeah, the big problem seems to be there is no way via `--user-local` to force a specific locally built package to be installed. Best workaround I can think of is to upload your packages and label them appropriately.

**Comment by sandys** [comment]
im facing the same issue. we have a private packages that we have to audit and only then upload. not able to figure out how to install a local package which has its own dependencies

**Comment by msarahan** [comment]
if your packages are in the ``conda-bld/(something like linux-64)`` folder, you can use ``-c local``

like

``conda install -c local mypkg``

``local`` is a name that conda understands to be that conda-bld subfolder.

**Comment by sandys** [comment]
Hi ,
Tried that. But it is not installing dependencies.
Is this disabled (based on a comment above)?

This will break private distribution of libraries

**Comment by sandys** [comment]
Hi Mike
Thanks for the reply - if I could just request for additional
clarification, that would be awesome.

So it would be

"conda -c file:///opt/private/ install mypkg"

Where, mypkg-01234.tar.bz2 is the actual package file in the /opt/private/
directory?

**Comment by stuarteberg** [comment]
@sandys That example ALMOST works. But `-c` is an argument to the `install` command, so it needs to be placed AFTER `install`:

```bash
conda install -c file:///path/to/my-packages mypkg
```

With that command, the package is installed along with all dependencies.

**Comment by stuarteberg** [comment]
To elaborate on Mike's suggestion above:

>If you set up a channel instead (can be a file:// url to a local location), and install from that, dependencies will be installed.


1. Create a directory to serve as the local channel, with a subdirectory for your platform (OS).
2. Move your package tarball into that subdirectory.
3. Run `conda index` on the local channel directory.
4. Run `conda install -c file://${my_local_channel}`

```
mkdir -p /tmp/my-local-channel/osx-64
mv ~/Downloads/mypackage-2.40-py37hc48c483_1.tar.bz2 /tmp/my-local-channel/osx-64
conda index /tmp/my-local-channel
conda install -c file:///tmp/my-local-channel mypackage
```
