### ISSUE TITLE
Bug when mixing CONDA_ENVS_PATH with win32 and win64 environments

### ISSUE THREAD

**Issue by tarcisiofischer** [conda/conda#1885]
Usually, Miniconda installs environments in the *Miniconda/envs/* path.
Packages are usually copied in *Miniconda/pkgs/* and *Miniconda/pkgs32/* paths.

CONDA_ENVS_PATH can override the *envs/* path location to somewhere else, and then it creates a new folder *envs/.pkgs* to override the *Miniconda/pkgs/* AND *Miniconda/pkgs32* path location (Both will be used in the same location and this is the problem).
Since it does not create a envs/.pkgs32 path, changing between 32 and 64bit environments and downloading packages can lead to wrong package installation in environments.

The problem seems to be in this function:
https://github.com/conda/conda/blob/master/conda/config.py#L164
Since it is explicitly using '.pkgs' in the else statement, I'm unsure if this is really a bug or by design.
I found it to be a bug in MY usecase (see below).

**Configuration**
S.O.: Windows 7
Conda version: 3.18.3

**Steps to reproduce (Example)**
```
> set CONDA_ENVS_PATH=D:/tmp/A/envs2
> conda info
(...)
     root environment : D:\Miniconda  (writable)
     default environment : D:\Miniconda
     envs directories : D:\tmp\A\envs2
     package cache : D:\tmp\A\envs2\.pkgs
(...)

> set CONDA_FORCE_32BIT=
> conda create -n env64 python=2
> activate env64
> python -c "import platform; print platform.architecture()"
('64bit', 'WindowsPE')
> deactivate

> set CONDA_FORCE_32BIT=1
> conda create -n env32 python=2
> activate env32
> python -c "import platform; print platform.architecture()"
('64bit', 'WindowsPE')
> deactivate
```

**Comment by ilanschnell** [comment]
Thanks for reporting the issue.  Did you read the comment https://github.com/conda/conda/blob/master/conda/config.py#L24 ?  Your usecase is currently unsupported.  Whether or not, your usecase *should* be supported is a separate question.  I welcome you to open a separate issue on your usecase.  Supporting your usecase *will* require a wider discussion, and more thought.

**Comment by tarcisiofischer** [comment]
Nice, @tadeu :)
