### ISSUE TITLE
conda env prompt

### ISSUE THREAD

**Issue by ywang007** [conda/conda#1887]
activate.bat change the PROMPT to show activated conda env, which is nice. However, it has conflict with other software that also tries to set PROMPT, for example, git use prompt to show current branch.

I found on google group the discussion about this:
https://groups.google.com/a/continuum.io/forum/#!topic/conda/C4ll3MeLku0

which suggest an option to not change the PROMPT. 

However if I just change the following line:

set PROMPT=[%CONDA_NEW_NAME%] $P$G
to:
set PROMPT=[%CONDA_NEW_NAME%] %PROMPT%

It adds conda evn while keeping the PROMPT set by git.

I did not test other scenarios. BTW, I'm on Windows with conda version 3.18.8:

**Comment by msarahan** [comment]
Fixed in https://github.com/conda/conda-env/pull/208
