### ISSUE TITLE
Fails to make package available to base environment.

### ISSUE THREAD

**Issue by statwonk** [conda/conda#1889]
Here's a minimal example on `OS X.

I'd like to install the most recent version of `scikit-learn` (it seems this library used to go by `sklearn`).
```
statwonk:~ $ conda install scikit-learn
Fetching package metadata: ....
Solving package specifications: ...................
# All requested packages already installed.
# packages in environment at /Users/statwonk/anaconda:
#
scikit-learn              0.17                np110py27_1    defaults
```
Okay, it's installed and is listed in the environment ...
```
statwonk:~ $ conda list
# packages in environment at /Users/statwonk/anaconda:
#
...
scikit-learn              0.17                np110py27_1    defaults
sklearn                   0.0                       <pip>
...
```
Now I fire up the base binary,
```
statwonk:~ $ python
Python 2.7.10 |Anaconda 2.4.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> print sys.executable
/Users/statwonk/anaconda/bin/python
>>> import sklearn
>>> sklearn.__version__
'0.16.1'
>>> __import__("scikit-learn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named scikit-learn
```
I can import the existing `sklearn`-named module just fine, but no such luck for `scikit-learn`.

**Comment by ilanschnell** [comment]
The project name is `scikit-learn`, but you import `sklearn`.  The project and import name do not have to be the same, and there are a number of projects for which they are not.  Other examples are:
```
Project name   | import
--------------------------------
pyzmq             | zmq
scikit-image    | skimage
pycurl             | curl
pyyaml           | yaml
pywin32         | win32api, pywintypes
```

**Comment by msarahan** [comment]
I think there may also be some PYTHONPATH issue at play here.  What is the output of

    import sklearn
    sklearn.__file__

**Comment by ilanschnell** [comment]
I don't think there is a problem with `PYTHONPATH` being set, because `import sklearn` works just fine.  However, `__import__("scikit-learn")` (obviously) fails, which I tried to explain.

**Comment by msarahan** [comment]
The tricky thing is that he installed sklearn version 0.17 with conda, but 0.16.1 is the version that gets imported.  That's why PYTHONPATH might be an issue here.

**Comment by ilanschnell** [comment]
Ah, good catch.  I though his only problem was that `__import__("scikit-learn")` didn't work.

**Comment by statwonk** [comment]
@msarahan here's the output,

```
statwonk:~ $ python
Python 2.7.10 |Anaconda 2.4.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sklearn
>>> sklearn.__file__
'/Library/Python/2.7/site-packages/sklearn/__init__.pyc'
>>> 
```
so it does look like I have the wrong path set,
```
echo $PYTHONPATH
/Library/Python/2.7/site-packages/
```
I guess I wouldn't expect `conda` to set its own `PYTHONPATH` inside its own directory.

**Comment by ilanschnell** [comment]
That explains it.  You are importing `sklearn` from `/Library/Python/2.7/site-packages/`, instead of `/Users/statwonk/anaconda/lib/python/2.7/site-packages/`.  If you
```
$ unset PYTHONPATH
```
you will get the `sklearn` from Anaconda.  The `PYTHONPATH` environment variable does not need to be set when importing packages from Anaconda's own site-packages directory.  In fact, we always  recommend unsetting `PYTHONPATH`.

**Comment by statwonk** [comment]
@ilanschnell ah, thank you! I see there's a warning in the installer shell script, whoops. Do you think this might warn a snippet in [`troubleshooting`](https://github.com/conda/conda-docs/edit/master/docs/source/troubleshooting.rst)? If so, I don't mind proposing via PR.
