### ISSUE TITLE
Password for proxy is not hidden if typed in the terminal

### ISSUE THREAD

**Issue by AlexS12** [conda/conda#1897]
If .condarc file is configured to operate behind a proxy, but without specifying the user and the password, so conda prompts for a username and password; the password typed in the terminal is completely visible in the screen. This could represent a security issue, specially in work environments. Would it be possible to hide it? Thanks in advance.

**Comment by kalefranz** [comment]
Conda now uses the `getpass` function from `getpass` in the python stdlib.

**Comment by kalefranz** [comment]
Other bugs with conda's interaction with proxy servers are now being tracked in #5220
