### ISSUE TITLE
wish: for auto proxy sites, process proxy.pac

### ISSUE THREAD

**Issue by majidaldo** [conda/conda#190]
proxy.pac is javascript that tells the browser what proxy to use for a destination. it's possible to process that so that conda can communicate. it looks like pac files are being used for proxy mgt at larger corps. here is a pac parser that could be used
https://code.google.com/p/pacparser/

**Comment by jasongrout** [comment]
I don't know how reasonable it is for conda to depend on a C library that implements a javascript interpreter.  But I have another solution that might work in many cases at https://github.com/conda/conda/issues/1527

**Comment by jasongrout** [comment]
It looks like @kalefranz closed this accidentally with a typo. However, I agree with the decision that the item should be closed :).
