### ISSUE TITLE
test_fft.py issue in numpy

### ISSUE THREAD

**Issue by XuesongYang** [conda/conda#1901]
Hi there,

I used `$ conda install numpy=1.10.1` and made a `$ python -c "import numpy; numpy.test()"`. However, there was a bug as follows:
# 
## ERROR: test_rfft (test_fft.TestFFT1D)

Traceback (most recent call last):
  File "/home/xyang45/anaconda2/lib/python2.7/site-packages/numpy/fft/tests/test_fft.py", line 72, in test_rfft
    x = np.fft.rfft([0, 1+5j, 0+7j, -3j])
  File "/home/xyang45/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 359, in rfft
    a = array(a, copy=True, dtype=float)
TypeError: can't convert complex to float

I checked https://github.com/numpy/numpy/tree/master/numpy/fft/tests, and found that `test_fft.py` was removed. But this test file is still in conda's folder.

**Comment by lucapton** [comment]
I have the same issue. Installed anaconda for 64 bit linux this morning and ran into that same error in numpy.test().

**Comment by zym1010** [comment]
same issue here. Looks like a packaging mistake...
