### ISSUE TITLE
change default directory in launcher

### ISSUE THREAD

**Issue by jjstarn-usgs** [conda/conda#1903]
I would like to change the default directory for launcher.  According to the docs,

---

Each time Launcher is run it will check for a file called .anaconda-launcher.rc in the user’s home directory (~).

If the file doesn’t exist Launcher will create it with the default settings. 

---

however, the default file is not created by Launcher.

I'm using Windows 7 and Miniconda2

**Comment by kalefranz** [comment]
Outdated. Launcher doesn't even exist any longer.
