### ISSUE TITLE
Issues linking some packages

### ISSUE THREAD

**Issue by linoush** [conda/conda#1907]
Here is the list of errors I got while installing some packages. The problem can also be isolated if I do "conda install cython" and gives the same error.

 conda install --file req.txt 
Fetching package metadata: ..
Solving package specifications: 
Package plan for installation in environment /n/home09/lnecib/envs/ody:

The following packages will be downloaded:

| package | build |
| --- | --- |
| h5py-2.5.0 | np110py27_4         2.4 MB |
| hdf5-1.8.15.1 | 2         1.9 MB |
| libgfortran-1.0 | 0         170 KB |
| numpy-1.10.1 | py27_0         5.9 MB |
| openblas-0.2.14 | 3         3.5 MB |
| pip-7.1.2 | py27_0         1.4 MB |
| python-2.7.10 | 2        12.0 MB |
| scipy-0.16.0 | np110py27_1        23.9 MB |
| setuptools-18.5 | py27_0         342 KB |
| six-1.10.0 | py27_0          16 KB |
| wheel-0.26.0 | py27_1          76 KB |

```
------------------------------------------------------------
                                       Total:        51.5 MB
```

The following packages will be UN-linked:

| package | build |
| --- | --- |
| cython-0.20.1 | py27_0 |
| h5py-2.2.1 | np18py27_0 |
| hdf5-1.8.9 | 1 |
| numpy-1.8.0 | py27_0 |
| openssl-1.0.1g | 0 |
| pip-1.5.2 | py27_0 |
| python-2.7.6 | 1 |
| scipy-0.13.3 | np18py27_0 |
| setuptools-2.2 | py27_0 |
| six-1.5.2 | py27_0 |
| sqlite-3.7.13 | 0 |
| tk-8.5.13 | 0 |
| zlib-1.2.7 | 0 |

The following packages will be linked:

| package | build |
| --- | --- |
| cython-0.23.4 | py27_0   hard-link |
| h5py-2.5.0 | np110py27_4   hard-link |
| hdf5-1.8.15.1 | 2   hard-link |
| libgfortran-1.0 | 0   hard-link |
| numpy-1.10.1 | py27_0   hard-link |
| openblas-0.2.14 | 3   hard-link |
| openssl-1.0.2d | 0   hard-link |
| pip-7.1.2 | py27_0   hard-link |
| python-2.7.10 | 2   hard-link |
| scipy-0.16.0 | np110py27_1   hard-link |
| setuptools-18.5 | py27_0   hard-link |
| six-1.10.0 | py27_0   hard-link |
| sqlite-3.8.4.1 | 1   hard-link |
| tk-8.5.18 | 0   hard-link |
| wheel-0.26.0 | py27_1   hard-link |
| zlib-1.2.8 | 0   hard-link |

Proceed ([y]/n)? y

Fetching packages ...
h5py-2.5.0-np110py27_4.tar.bz2 100% |######################################################################################| Time: 0:00:00   7.82 MB/s
hdf5-1.8.15.1-2.tar.bz2 100% |#############################################################################################| Time: 0:00:00   8.05 MB/s
libgfortran-1.0-0.tar.bz2 100% |###########################################################################################| Time: 0:00:00   2.05 MB/s
numpy-1.10.1-py27_0.tar.bz2 100% |#########################################################################################| Time: 0:00:00  13.13 MB/s
openblas-0.2.14-3.tar.bz2 100% |###########################################################################################| Time: 0:00:00  10.06 MB/s
pip-7.1.2-py27_0.tar.bz2 100% |############################################################################################| Time: 0:00:00   6.86 MB/s
python-2.7.10-2.tar.bz2 100% |#############################################################################################| Time: 0:00:00  20.83 MB/s
scipy-0.16.0-np110py27_1.tar.bz2 100% |####################################################################################| Time: 0:00:01  22.30 MB/s
setuptools-18.5-py27_0.tar.bz2 100% |######################################################################################| Time: 0:00:00   2.66 MB/s
six-1.10.0-py27_0.tar.bz2 100% |###########################################################################################| Time: 0:00:00 963.99 kB/s
wheel-0.26.0-py27_1.tar.bz2 100% |#########################################################################################| Time: 0:00:00   1.44 MB/s
Extracting packages ...
[      COMPLETE      ] |########################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |########################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                   |   6%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/n/home09/lnecib/envs/ody/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    execute_plan(plan, index, verbose)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    link(prefix, arg)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 438, in link
    update_prefix(join(prefix, f), prefix)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/cygdb'
###### #############################33

$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.4.1
   python version : 2.7.6.final.0
 root environment : /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x  (read only)
```

  default environment : /n/home09/lnecib/envs/ody
     envs directories : /n/home09/lnecib/envs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/envs
        package cache : /n/home09/lnecib/envs/.pkgs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
This issue is filed for conda 3.4.1.  Please update to a recent version of conda (latest is 4.3.17).  If you continue to have the issue, please file a new ticket with the updated stack trace.
