### ISSUE TITLE
conda error linking packages during Jupyter install 

### ISSUE THREAD

**Issue by kclemens67** [conda/conda#1913]
kclemens:~ kristinaac$ conda install jupyter
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /Users/kristinaac/anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| appnope-0.1.0 | py27_0           4 KB |
| backports_abc-0.4 | py27_0           5 KB |
| conda-3.18.9 | py27_0         176 KB |
| conda-env-2.4.5 | py27_0          24 KB |
| decorator-4.0.4 | py27_0          11 KB |
| freetype-2.5.5 | 0         732 KB |
| ipykernel-4.1.1 | py27_0         112 KB |
| ipython-4.0.1 | py27_0         917 KB |
| ipython_genutils-0.1.0 | py27_0          32 KB |
| ipywidgets-4.1.0 | py27_0          98 KB |
| jinja2-2.8 | py27_0         263 KB |
| jsonschema-2.4.0 | py27_0          51 KB |
| jupyter-1.0.0 | py27_1           2 KB |
| jupyter_client-4.1.1 | py27_0          89 KB |
| jupyter_console-4.0.3 | py27_0          22 KB |
| jupyter_core-4.0.6 | py27_0          48 KB |
| libpng-1.6.17 | 0         184 KB |
| markupsafe-0.23 | py27_0          22 KB |
| mistune-0.7.1 | py27_0         173 KB |
| nbconvert-4.0.0 | py27_0         266 KB |
| nbformat-4.0.1 | py27_0         112 KB |
| notebook-4.0.6 | py27_0         4.3 MB |
| openssl-1.0.2d | 0         3.0 MB |
| path.py-8.1.2 | py27_1          45 KB |
| pexpect-3.3 | py27_0          60 KB |
| pickleshare-0.5 | py27_0           8 KB |
| ptyprocess-0.5 | py27_0          19 KB |
| pycosat-0.6.1 | py27_0          56 KB |
| pygments-2.0.2 | py27_0         1.0 MB |
| pyqt-4.11.4 | py27_1         4.0 MB |
| python-2.7.11 | 0         9.9 MB |
| python.app-1.2 | py27_4           7 KB |
| pyyaml-3.11 | py27_1         142 KB |
| pyzmq-15.1.0 | py27_0         314 KB |
| qt-4.8.7 | 1        39.0 MB |
| qtconsole-4.1.1 | py27_0         125 KB |
| requests-2.9.0 | py27_0         604 KB |
| setuptools-18.8.1 | py27_0         346 KB |
| simplegeneric-0.8.1 | py27_0           6 KB |
| singledispatch-3.4.0.3 | py27_0          12 KB |
| sip-4.16.9 | py27_0         234 KB |
| six-1.10.0 | py27_0          16 KB |
| sqlite-3.8.4.1 | 1         824 KB |
| terminado-0.5 | py27_1          17 KB |
| tk-8.5.18 | 0         1.9 MB |
| tornado-4.3 | py27_0         542 KB |
| traitlets-4.0.0 | py27_0          88 KB |
| yaml-0.1.6 | 0          79 KB |
| zeromq-4.1.3 | 0         577 KB |
| zlib-1.2.8 | 0          83 KB |

```
------------------------------------------------------------
                                       Total:        70.6 MB
```

The following packages will be UN-linked:

| package | build |
| --- | --- |
| conda-3.4.2 | py27_0 |
| freetype-2.4.10 | 1 |
| ipython-2.0.0 | py27_0 |
| jinja2-2.7.2 | py27_0 |
| libpng-1.5.13 | 1 |
| markupsafe-0.18 | py27_0 |
| openssl-1.0.1g | 0 |
| pycosat-0.6.0 | py27_0 |
| pygments-1.6 | py27_0 |
| python-2.7.6 | 1 |
| python.app-1.2 | py27_1 |
| pyyaml-3.11 | py27_0 |
| pyzmq-2.2.0.1 | py27_1 |
| qt-4.7.4 | 0 |
| requests-2.2.1 | py27_0 |
| setuptools-2.2 | py27_0 |
| six-1.5.2 | py27_0 |
| sqlite-3.7.13 | 1 |
| tk-8.5.13 | 1 |
| tornado-3.2.0 | py27_0 |
| yaml-0.1.4 | 1 |
| zeromq-2.2.0 | 1 |
| zlib-1.2.7 | 1 |

The following packages will be linked:

| package | build |
| --- | --- |
| appnope-0.1.0 | py27_0   hard-link |
| backports_abc-0.4 | py27_0   hard-link |
| conda-3.18.9 | py27_0   hard-link |
| conda-env-2.4.5 | py27_0   hard-link |
| decorator-4.0.4 | py27_0   hard-link |
| freetype-2.5.5 | 0   hard-link |
| ipykernel-4.1.1 | py27_0   hard-link |
| ipython-4.0.1 | py27_0   hard-link |
| ipython_genutils-0.1.0 | py27_0   hard-link |
| ipywidgets-4.1.0 | py27_0   hard-link |
| jinja2-2.8 | py27_0   hard-link |
| jsonschema-2.4.0 | py27_0   hard-link |
| jupyter-1.0.0 | py27_1   hard-link |
| jupyter_client-4.1.1 | py27_0   hard-link |
| jupyter_console-4.0.3 | py27_0   hard-link |
| jupyter_core-4.0.6 | py27_0   hard-link |
| libpng-1.6.17 | 0   hard-link |
| markupsafe-0.23 | py27_0   hard-link |
| mistune-0.7.1 | py27_0   hard-link |
| nbconvert-4.0.0 | py27_0   hard-link |
| nbformat-4.0.1 | py27_0   hard-link |
| notebook-4.0.6 | py27_0   hard-link |
| openssl-1.0.2d | 0   hard-link |
| path.py-8.1.2 | py27_1   hard-link |
| pexpect-3.3 | py27_0   hard-link |
| pickleshare-0.5 | py27_0   hard-link |
| ptyprocess-0.5 | py27_0   hard-link |
| pycosat-0.6.1 | py27_0   hard-link |
| pygments-2.0.2 | py27_0   hard-link |
| pyqt-4.11.4 | py27_1   hard-link |
| python-2.7.11 | 0   hard-link |
| python.app-1.2 | py27_4   hard-link |
| pyyaml-3.11 | py27_1   hard-link |
| pyzmq-15.1.0 | py27_0   hard-link |
| qt-4.8.7 | 1   hard-link |
| qtconsole-4.1.1 | py27_0   hard-link |
| requests-2.9.0 | py27_0   hard-link |
| setuptools-18.8.1 | py27_0   hard-link |
| simplegeneric-0.8.1 | py27_0   hard-link |
| singledispatch-3.4.0.3 | py27_0   hard-link |
| sip-4.16.9 | py27_0   hard-link |
| six-1.10.0 | py27_0   hard-link |
| sqlite-3.8.4.1 | 1   hard-link |
| terminado-0.5 | py27_1   hard-link |
| tk-8.5.18 | 0   hard-link |
| tornado-4.3 | py27_0   hard-link |
| traitlets-4.0.0 | py27_0   hard-link |
| yaml-0.1.6 | 0   hard-link |
| zeromq-4.1.3 | 0   hard-link |
| zlib-1.2.8 | 0   hard-link |

Proceed ([y]/n)? y

Fetching packages ...
appnope-0.1.0-py27_0.tar.bz2 100% |##########################################################| Time: 0:00:00   2.11 MB/s
backports_abc-0.4-py27_0.tar.bz2 100% |######################################################| Time: 0:00:00   2.46 MB/s
conda-3.18.9-py27_0.tar.bz2 100% |###########################################################| Time: 0:00:00 345.81 kB/s
conda-env-2.4.5-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 277.63 kB/s
decorator-4.0.4-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00   5.66 MB/s
freetype-2.5.5-0.tar.bz2 100% |##############################################################| Time: 0:00:01 647.12 kB/s
ipykernel-4.1.1-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 265.36 kB/s
ipython-4.0.1-py27_0.tar.bz2 100% |##########################################################| Time: 0:00:01 707.18 kB/s
ipython_genutils-0.1.0-py27_0.tar.bz2 100% |#################################################| Time: 0:00:00 188.05 kB/s
ipywidgets-4.1.0-py27_0.tar.bz2 100% |#######################################################| Time: 0:00:00 286.13 kB/s
jinja2-2.8-py27_0.tar.bz2 100% |#############################################################| Time: 0:00:00 430.40 kB/s
jsonschema-2.4.0-py27_0.tar.bz2 100% |#######################################################| Time: 0:00:00 284.08 kB/s
jupyter-1.0.0-py27_1.tar.bz2 100% |##########################################################| Time: 0:00:00 999.94 kB/s
jupyter_client-4.1.1-py27_0.tar.bz2 100% |###################################################| Time: 0:00:00 252.74 kB/s
jupyter_console-4.0.3-py27_0.tar.bz2 100% |##################################################| Time: 0:00:00 235.17 kB/s
jupyter_core-4.0.6-py27_0.tar.bz2 100% |#####################################################| Time: 0:00:00 271.81 kB/s
libpng-1.6.17-0.tar.bz2 100% |###############################################################| Time: 0:00:00 353.57 kB/s
markupsafe-0.23-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 238.51 kB/s
mistune-0.7.1-py27_0.tar.bz2 100% |##########################################################| Time: 0:00:00 335.68 kB/s
nbconvert-4.0.0-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 437.62 kB/s
nbformat-4.0.1-py27_0.tar.bz2 100% |#########################################################| Time: 0:00:00 320.31 kB/s
notebook-4.0.6-py27_0.tar.bz2 100% |#########################################################| Time: 0:00:02   1.54 MB/s
openssl-1.0.2d-0.tar.bz2 100% |##############################################################| Time: 0:00:02   1.42 MB/s
path.py-8.1.2-py27_1.tar.bz2 100% |##########################################################| Time: 0:00:00 242.53 kB/s
pexpect-3.3-py27_0.tar.bz2 100% |############################################################| Time: 0:00:00 228.89 kB/s
pickleshare-0.5-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00   3.53 MB/s
ptyprocess-0.5-py27_0.tar.bz2 100% |#########################################################| Time: 0:00:00 209.23 kB/s
pycosat-0.6.1-py27_0.tar.bz2 100% |##########################################################| Time: 0:00:00 220.66 kB/s
pygments-2.0.2-py27_0.tar.bz2 100% |#########################################################| Time: 0:00:01 762.07 kB/s
pyqt-4.11.4-py27_1.tar.bz2 100% |############################################################| Time: 0:00:02   1.59 MB/s
python-2.7.11-0.tar.bz2 100% |###############################################################| Time: 0:00:04   2.46 MB/s
python.app-1.2-py27_4.tar.bz2 100% |#########################################################| Time: 0:00:00   2.78 MB/s
pyyaml-3.11-py27_1.tar.bz2 100% |############################################################| Time: 0:00:00 323.36 kB/s
pyzmq-15.1.0-py27_0.tar.bz2 100% |###########################################################| Time: 0:00:00 367.98 kB/s
qt-4.8.7-1.tar.bz2 100% |####################################################################| Time: 0:00:07   5.28 MB/s
qtconsole-4.1.1-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 350.36 kB/s
requests-2.9.0-py27_0.tar.bz2 100% |#########################################################| Time: 0:00:01 587.39 kB/s
setuptools-18.8.1-py27_0.tar.bz2 100% |######################################################| Time: 0:00:00 452.73 kB/s
simplegeneric-0.8.1-py27_0.tar.bz2 100% |####################################################| Time: 0:00:00   2.05 MB/s
singledispatch-3.4.0.3-py27_0.tar.bz2 100% |#################################################| Time: 0:00:00   4.16 MB/s
sip-4.16.9-py27_0.tar.bz2 100% |#############################################################| Time: 0:00:00 389.74 kB/s
six-1.10.0-py27_0.tar.bz2 100% |#############################################################| Time: 0:00:00 190.90 kB/s
sqlite-3.8.4.1-1.tar.bz2 100% |##############################################################| Time: 0:00:01 690.19 kB/s
terminado-0.5-py27_1.tar.bz2 100% |##########################################################| Time: 0:00:00 198.09 kB/s
tk-8.5.18-0.tar.bz2 100% |###################################################################| Time: 0:00:02 958.58 kB/s
tornado-4.3-py27_0.tar.bz2 100% |############################################################| Time: 0:00:01 443.28 kB/s
traitlets-4.0.0-py27_0.tar.bz2 100% |########################################################| Time: 0:00:00 233.26 kB/s
yaml-0.1.6-0.tar.bz2 100% |##################################################################| Time: 0:00:00 291.69 kB/s
zeromq-4.1.3-0.tar.bz2 100% |################################################################| Time: 0:00:01 533.61 kB/s
zlib-1.2.8-0.tar.bz2 100% |##################################################################| Time: 0:00:00 236.96 kB/s
Extracting packages ...
[      COMPLETE      ] |##########################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##########################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                     |  28%
following traceback to the conda GitHub issue tracker at:

Traceback (most recent call last):
  File "/Users/kristinaac/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main

  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    if not pkgs:
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    else:
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/plan.py", line 418, in execute_plan
    if is_root_prefix(prefix):
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/plan.py", line 374, in link

  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/install.py", line 443, in link
    return False
  File "/Users/kristinaac/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    except OSError as e:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/jupyter-kernelspec'

**Comment by tyler-thetyrant** [comment]
Closing as I cannot replicate the error with the most recent version of conda.
