### ISSUE TITLE
Abnormal behavior of Miniconda on Ubuntu 14.04.3 LTS 64bit

### ISSUE THREAD

**Issue by antinucleon** [conda/conda#1920]
When running conda install, it will raise error
```
Error: Could not open u'/home/xxx/deps/conda/pkgs/jpeg-8d-0.tar.bz2.part' for writing (seek)
```
By replace download function in ```fetch.py``` with wget or use miniconda 3.7 will solve this problem.

Also find other report at stackoverflow

When running ```pip``` in miniconda, it will fail to locate package and install, no matter use 3.7, 3.8 or 3.9, eg:
```
Could not fetch URL https://pypi.python.org/simple/httpretty/0.8.8: 404 Client Error: Not Found
```

Native environment works well for fetching and pip.

Everything works well on Ubuntu 12.10

**Comment by ilanschnell** [comment]
Thanks for reporting this issue.  This sounds like a permissions problem to me.

**Comment by antinucleon** [comment]
I tried sudo, but doesn't work

**Comment by ilanschnell** [comment]
I doubt that the problem has anything to so with the exact Ubuntu version.

**Comment by antinucleon** [comment]
I tried newest, now it works.
