### ISSUE TITLE
BUG: conda install override-channels broken

### ISSUE THREAD

**Issue by cpelley** [conda/conda#1924]
The override-channels argument breaks the install command:

```
$ conda install <package_name> --override-channels -c <channel_name>
Fetching package metadata: ..
Error: No packages found in current linux-64 channels matching: python 2.7*

You can search for this package on anaconda.org with

    anaconda search -t conda python 2.7*
```

No problems in finding the package in the channel with:

```
$ conda search <package_name> --override-channels -c <channel_name>
```

I have not provided the real use case above as it utilises a custom channel, however, #1849 appears to have a real use case that can be shared for this bug.  I should highlight that this problem extends beyond that issue (hence my raising this issue).

```
win-64
Python 2.7.11
conda 3.19.0
conda-build 1.17.0
```

Thanks

**Comment by koverholt** [comment]
I'm also running into this bug for custom packages we are building:

```
$ conda install protobuf -c blaze --override-channels
Fetching package metadata: ..
Error: No packages found in current linux-64 channels matching: conda

You can search for this package on anaconda.org with

    anaconda search -t conda conda
```

**Comment by kalefranz** [comment]
I just reproduced and confirmed for myself.  Will probably need input from @csoja to help prioritize and/or delegate.

**Comment by kalefranz** [comment]
tracking via #5158
