### ISSUE TITLE
Problems updating conda

### ISSUE THREAD

**Issue by sastephe** [conda/conda#1929]
PS C:\Users\Sam> conda update conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-env-2.4.5 | py27_0          65 KB |
| requests-2.9.0 | py27_0         611 KB |
| setuptools-19.1.1 | py27_0         651 KB |
| conda-3.19.0 | py27_0         219 KB |

```
------------------------------------------------------------
                                       Total:         1.5 MB
```

The following NEW packages will be INSTALLED:

```
msvc_runtime: 1.0.1-vc9_0   [vc9]
wheel:        0.26.0-py27_1
```

The following packages will be UPDATED:

```
conda:        3.11.0-py27_0 --> 3.19.0-py27_0
conda-env:    2.1.4-py27_0  --> 2.4.5-py27_0
menuinst:     1.2.1-py27_0  --> 1.3.1-py27_0
pip:          6.1.1-py27_0  --> 7.1.2-py27_0
pyyaml:       3.11-py27_0   --> 3.11-py27_2
requests:     2.7.0-py27_0  --> 2.9.0-py27_0
setuptools:   15.2-py27_0   --> 19.1.1-py27_0
```

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.4. 100% |###############################| Time: 0:00:00 213.41 kB/s
requests-2.9.0 100% |###############################| Time: 0:00:00 650.96 kB/s
setuptools-19. 100% |###############################| Time: 0:00:01 652.58 kB/s
conda-3.19.0-p 100% |###############################| Time: 0:00:00 329.89 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '**getitem**'
PS C:\Users\Sam> conda info
Current conda install:

```
         platform : win-64
    conda version : 3.11.0-dirty
```

  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

PS C:\Users\Sam>

**Comment by tyler-thetyrant** [comment]
Closing outdated.
