### ISSUE TITLE
Conda create without explicit Python version has incorrect msvc_runtime package

### ISSUE THREAD

**Issue by rlee287** [conda/conda#1932]
New environments do not work at first in MiniConda.

I created an environment with `conda create ...`. After activating it, I cannot run Python in the new environment. When I type in `python` to get an interactive shell, I get a dialog box saying that Python cannot find "vcruntime140.dll" and that I should reinstall Python. However, I do not have this problem with the root environment.
After some digging, I found out that Conda fails to copy over the previously mentioned dll when creating a new environment. My workaround so far has been to open an elevated command prompt and create a symlink in the environment directory pointing to the vcruntime140.dll of the root environment. The screenshot below shows a new environment with the symlink.
![capture](https://cloud.githubusercontent.com/assets/14067959/12067728/c12a70ae-afb3-11e5-848d-4f01c3ad0187.PNG)
I have also attached several screenshots below showing conda's root directory. Unfortunately, I do not have enough screenspace to show all the files at once. Duplicate entries are due to overlapping screenshots. I have created a `py` and `pyw` symlink  emulate the py launcher, but I have not modified this directory otherwise.
![capture2_1](https://cloud.githubusercontent.com/assets/14067959/12067804/3735a934-afb5-11e5-8335-e14b676bf788.PNG)
![capture2_2](https://cloud.githubusercontent.com/assets/14067959/12067805/37388258-afb5-11e5-9530-c911ed14d1c3.PNG)
![capture2_3](https://cloud.githubusercontent.com/assets/14067959/12067806/3739cc12-afb5-11e5-8d21-5536de0a3f04.PNG)

Output of `conda info --all` with private information removed:

Current conda install:

platform : win-64
conda version : 3.19.0
conda-build version : not installed
python version : 3.5.1.final.0
requests version : 2.9.0
root environment : C:\Users\<USERNAME>\AppData\Miniconda3  (writable)
default environment : C:\Users\Ryan\AppData\Miniconda3
envs directories : C:\Users\Ryan\AppData\Miniconda3\envs
package cache : C:\Users\Ryan\AppData\Miniconda3\pkgs
channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                         https://repo.continuum.io/pkgs/free/noarch/
                         https://repo.continuum.io/pkgs/pro/win-64/
                         https://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False

*...List of Conda Environments...*

sys.version: 3.5.1 |Continuum Analytics, Inc.| (defau...
sys.prefix: C:\Users\Ryan\AppData\Miniconda3
sys.executable: C:\Users\Ryan\AppData\Miniconda3\python.exe
conda location: C:\Users\Ryan\AppData\Miniconda3\lib\site-packages\conda
conda-build: None
conda-env: C:\Users\Ryan\AppData\Miniconda3\Scripts\conda-env.exe
user site dirs:

CIO_TEST: `<not set>`
CONDA_DEFAULT_ENV: `<not set>`
CONDA_ENVS_PATH: `<not set>`
PATH: *(only showing Conda related paths)*
C:\Users\Ryan\AppData\Miniconda3
C:\Users\Ryan\AppData\Miniconda3\Scripts
C:\Users\Ryan\AppData\Miniconda3\Library\bin
PYTHONHOME: `<not set>`
PYTHONPATH: `<not set>`

**Comment by msarahan** [comment]
Sorry you're having trouble here.  This is a very strange situation.  The VCRuntime140.dll is provided by the msvc_runtime package.  You should be obtaining version 1.0.1 of that package when you get Python 3.5.  You should not have MSVCR100.dll there - rather, you should have copies of those many DLLs, as in your root environment.

What is your root installation?  Have you done a ```conda update conda``` before creating your environment?

Please post your complete ```conda create``` command, so that we can more easily reproduce your issue.

**Comment by rlee287** [comment]
I apparently have 1.0.1 version of `msvc_runtime` already. Here is the output of `conda list -e` in my root environment:

\# This file may be used to create an environment using:
\# $ conda create --name <env> --file <this file>
\# platform: win-64
conda=3.19.0=py35_0
conda-env=2.4.5=py35_0
menuinst=1.3.1=py35_0
msvc_runtime=1.0.1=vc14_0
pip=7.1.2=py35_0
pycosat=0.6.1=py35_0
pycrypto=2.6.1=py35_3
python=3.5.1=0
pyyaml=3.11=py35_2
requests=2.9.0=py35_0
setuptools=19.1.1=py35_0
wheel=0.26.0=py35_1

`conda update --dry-run conda` tells me that I am using the lastest version of conda already. Here is its output in my root environment:

Fetching package metadata: ....
\# All requested packages already installed.
\# packages in environment at C:\Users\Ryan\AppData\Miniconda3:
\#
conda                     3.19.0                   py35_0

**Comment by msarahan** [comment]
I have reproduced your issue with a clean installation of Miniconda3-3.19-x64.  When I run:

    conda create -n test35 python=3.5

This creates an env with python 3.5.1 and msvc_runtime, as it should.  Everything works.

I also tried

    conda create -n test35 python

(omitting the python version spec)

This includes msvc_runtime, but it includes msvc_runtime WITHOUT the vc14 feature, and seems to default to some package that includes vc10 dlls somehow.  This is a bug that we need to address.  I am renaming your issue.

Pinging @ilanschnell @csoja

**Comment by rlee287** [comment]
Found something interesting with the `--debug` option:
`conda --debug list` (using root environment):
\# packages in environment at C:\Users\Ryan\AppData\Miniconda3:
\#
conda                     3.19.0                   py35_0
conda-env                 2.4.5                    py35_0
menuinst                  1.3.1                    py35_0
msvc_runtime              1.0.1                    vc14_0  [vc14]
pip                       7.1.2                    py35_0
pycosat                   0.6.1                    py35_0
pycrypto                  2.6.1                    py35_3
python                    3.5.1                         0
pyyaml                    3.11                     py35_2
requests                  2.9.0                    py35_0
setuptools                19.1.1                   py35_0
wheel                     0.26.0                   py35_1

When I do the same in the environment without an explicit Python version but a vcruntime140.dll symlink, I get this:
`conda --debug list -n testwopyversion` output:
\# packages in environment at C:\Users\Ryan\AppData\Miniconda3\envs\testwopyversion:
\#
DEBUG:conda.cli.main_list:'NoneType' object has no attribute 'get'
DEBUG:conda.cli.main_list:'NoneType' object has no attribute 'get'
msvc_runtime              1.0.1                         0
pip                       7.1.2                    py35_0
python                    3.5.1                         0
setuptools                19.1.1                   py35_0
wheel                     0.26.0                   py35_1

**Comment by rlee287** [comment]
This is a long time after I filed this issue, but I can confirm that as of version `4.0.7` (or possibly earlier), `conda create -n test35 python` creates a `test35` environment that works out of the box. I am now closing this issue.
