### ISSUE TITLE
EOFError raised when creating a new python2 environment

### ISSUE THREAD

**Issue by loveohno13** [conda/conda#1940]
![qq 20160108075320](https://cloud.githubusercontent.com/assets/15681450/12186405/539ff6b4-b5dd-11e5-906d-946043e7efd8.png)
![qq 20160108075555](https://cloud.githubusercontent.com/assets/15681450/12186406/53a2515c-b5dd-11e5-9bba-5dde967d955d.png)

**Comment by msarahan** [comment]
This looks like you have a corrupt package from something like an incomplete download.  You should run this command:

    conda clean --tarballs --packages

and try to create your environment again.

**Comment by loveohno13** [comment]
![qq 20160108092044](https://cloud.githubusercontent.com/assets/15681450/12187704/2aca0138-b5e9-11e5-8a3d-54713abaf0f8.png)
Thanks for your reply!
I tried the command, but it failed again……

What should I do? Thanks again!

**Comment by msarahan** [comment]
Unfortunately, that's a new error, pointing to your internet connection not
being able to make a secure connection for some reason.  I searched around,
but no clear answer here.  Some people run into this error when using
multiple processes and not creating enough sessions.  We're dealing with
only one process here, so it shouldn't be that issue.  Please try again.
It's encouraging that the first package worked - I'm hoping it is just a
fluke with your internet connection.  Is your connection generally bad?

HTH,
Michael

**Comment by loveohno13** [comment]
internet connection issue...eh.. I agree with that too


Last night I tried to create a snowflake environment many times but all failed.
Today morning I just reboot my PC and it just succeed smoothly...

I'll try it again, and what should I do to deal with the bad connection? Is a proxy useful?

Thanks!
Valerie
