### ISSUE TITLE
'ASCII decode' error revisit, how to identify and fix ?

### ISSUE THREAD

**Issue by zlqs1985** [conda/conda#1946]
OK, it seems a duplicated issue, error arise when I trying to pip install a package name pymaclab within conda. The error message is ” 'ascii' codec can't decode byte 0xb2 in position 0: ordinal not in range(128)“. Well, since I'm from China and my OS (Win10) is Chinese, it's most likely that some non-unicode pathname cause the trouble. But I use `conda info' to check it , it seems not the case.
![conda info](https://cloud.githubusercontent.com/assets/10328230/12220864/91d6e978-b7be-11e5-907e-32bfdec64511.png)
My user name "Zhanglu" is of course of unicode. So **how can I to identify the source of problem and fix it ?** ( I prefer not to switch to Anaconda3 by this time). Appreciapte for any help.

**Comment by ilanschnell** [comment]
You say the problem arises when you try to `pip install` a package.  In this case, it is more important which version of pip you are using.  In fact, I would argue that this is probably a pip issue and not relevant to conda at all.
