### ISSUE TITLE
binaries from sub-environ on different volume can't find shared libraries

### ISSUE THREAD

**Issue by bmflynn** [conda/conda#1947]
When executing a binary installed in an environment created from a parent environment binaries with dependencies outside their package can't find their shared libraries.

Two examples of binaries that require libraries from other packages and are therefore broken:
- curl: requires openssl package
- ncdump (from libnetcdf): required hdf5 package

To reproduce:

```
$ which conda
/opt/anaconda/bin/conda

$ conda create -y -p ./env curl

$ source activate ./env
(/data/brucef/env)$ conda install -y curl

(/data/brucef/env)$ which curl
/data/brucef/env/bin/curl

(/data/brucef/env)$ ldd ./env/bin/curl | grep libssl
    libssl.so.1.0.0 => /data/brucef/./env/bin/../lib/libssl.so.1.0.0 (0x00007fc2af726000)

(/data/brucef/env)$ curl
curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

The problem seems to be that the RPATH is causing the lib loader to look for the library relative the actual binary path not the softlinked path:

```
(/data/brucef/env)$ ll ./env/bin/curl
lrwxrwxrwx 1 brucef domain users 53 Jan 11 23:17 ./env/bin/curl -> /home/brucef/.conda/envs/.pkgs/curl-7.45.0-0/bin/curl

(/data/brucef/env)$ readelf -a ./env/bin/curl | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib]

(/data/brucef/env)$ LD_DEBUG=all curl
... snip ...
     23406:  search path=/home/brucef/.conda/envs/.pkgs/curl-7.45.0-0/bin/../lib        (RPATH from file curl)
     23406:   trying file=/home/brucef/.conda/envs/.pkgs/curl-7.45.0-0/bin/../lib/libssl.so.1.0.0
... snip ...
```

Seems like it should be using the path of the softlink `/data/brucef/env/bin/../lib/libssl.so.1.0.0`

**Comment by kalefranz** [comment]
Hey @bmflynn, in conda 4.3.17 (or maybe it was 4.3.16) we made a change that should have fixed this.  Can you `conda update conda` and let us know?

**Comment by kalefranz** [comment]
Closing as fixed.  If not, we can reopen.
