### ISSUE TITLE
Explain/improve relocation support for non-relocatable code

### ISSUE THREAD

**Issue by nicowilliams** [conda/conda#1950]
I watched the video at http://conda.pydata.org/docs/ and I noticed the claim that Conda does various things about relocating code, but other than mentioning shebangs, not much is said.  Conda seems to depend strongly on all pkgs being relocatable, so this is an important subject.

Because of things like autoconf, a great number of open source codebases are non-relocatable out of the box.  Absolute install paths can be encoded in a large number of places:

 - ELF objects, in rpath/runpath
 - shebangs
 - in object code (for example, valgrind execs a helper program using the absolute install path)
 - in data files

Fixing all of these is hard, as the number of ways in which an absolute install path could be hardcoded at build-time is effectively infinite.

The rpath/runpath case can be addressed with `patchelf(1)` using `$ORIGIN`-relative paths.  Shebangs can be addressed with `sed(1)`.  The rest looks harder to me.  `LD_PRELOAD` can be used to some degree (but not on all platforms) to intercept references to build-time hardcoded install paths and rewrite them to run-time relative install paths.

So I'm curious as to what all Conda does to address this.  Perhaps I've missed something.  (I looked a bit in the sources, but nothing stuck out.)

(It really is a terrible thing that autoconf makes it so easy to write non-relocatable code...)

**Comment by nicowilliams** [comment]
Oh, I just happened on this http://conda.pydata.org/docs/building/meta-yaml.html#making-packages-relocatable

**Comment by nicowilliams** [comment]
What Conda does do seems a lot like an 80% solution that requires a fair bit of manual labor (to identify and list files needing relocation).  For binary files... C strings are assumed.  Is UTF-16 supported?

Maybe Conda can learn to do better over time?

And maybe we need a better (and more liberally-licensed) alternative to [the GNU `relocatable-prog` module](https://www.gnu.org/software/gnulib/manual/html_node/Supporting-Relocation.html), but getting open source projects to use it will take time.

**Comment by nicowilliams** [comment]
BTW, I can't find where Conda uses `chrpath(1)` or `patchelf(1)`.  The docs mention `patchelf` being used on Linux, and the ChangeLog mentions `chrpath`...

**Comment by nicowilliams** [comment]
It might be useful to write a set of autoconf macros to generate and substitute macros whose values are paths to `XYZDIR` relative to `ABCDIR`, then programs can use those, and then there would be no need for things like the `relocate()` function provided by the GNU `relocatable-prog` module.  Also, programs generally need to be able to run in place, in the build tree, for testing purposes, so additional macros may be needed, and programs may need to try two paths to reach installed artifacts, or else the built tree may need to be re-organized.

Clearly it will be hard to boil the oceans, but at least stopping the rot should be valuable.

**Comment by nicowilliams** [comment]
Oh, the use of `chrpath` was in `conda/builder/post.py`, but `conda/builder/` has been removed.

Maybe the docs need updating as to how to deal with non-relocatable packages?

Can someone give a testimonial as to how easy/difficult it is to use Conda to distribute/install typical Unix software, such as found in Debian/NixOS/whatever distro?

**Comment by kalefranz** [comment]
Hey @nicowilliams, see github.com/conda/conda-build for the builder code.  It was moved a while back.

I'm not aware of any bugs or flaws in conda's core functionality.  I just started working on the project, but I've been a user of it in Linux (and some OS X) for a while now.  The system is solid.

**Comment by stuarteberg** [comment]
>BTW, I can't find where Conda uses chrpath(1) or patchelf(1)

That code lives in the `conda-build` repo.

>What Conda does do seems a lot like an 80% solution that requires a fair bit of manual labor (to identify and list files needing relocation).

Your recipe can ask `conda-build` to automatically detect which files need to be patched, via the [`detect-binary-files-with-prefix`][1] setting in `meta.yaml`.

[1]: http://conda.pydata.org/docs/building/meta-yaml.html#detect-binary-files-with-prefix

>For binary files... C strings are assumed. Is UTF-16 supported?

This, I do not know.  I'm not a conda dev, but I'm sure a pull request would be welcomed if there is a need for it.

>Can someone give a testimonial as to how easy/difficult it is to use Conda to distribute/install typical Unix software, such as found in Debian/NixOS/whatever distro?

I use it on Linux and Mac.  It works.  But don't take my word for it -- try it yourself.  It's incredibly easy to get started and there's plenty of documentation and example recipes.

**Comment by nicowilliams** [comment]
Thanks.  I did eventually notice that the builder code moved.

I guess what I want is for this to be more prominent in the docs.  Dealing with non-relocatable code is really difficult, so for people who need to (and that includes most users of Conda, I would think), making this more prominent seems likely to be useful.  Should I re-file this against the conda-docs codebase?

**Comment by stuarteberg** [comment]
>I guess what I want is for this to be more prominent in the docs.

IMHO, I think the docs are reasonably clear on this point.

>Should I re-file this against the conda-docs codebase?

I wouldn't bother creating an issue to clarify a minor point in the docs. I doubt it will receive much attention.  Instead, if you have a suggestion for improving the docs, your best option is to make the change yourself and submit a pull request.  That will be easier to handle quickly.

**Comment by nicowilliams** [comment]
OK.
