### ISSUE TITLE
Getting error when setting up anaconda environment

### ISSUE THREAD

**Issue by SrikanthPeddada** [conda/conda#1954]
I was setting up anaconda environment in shell(.tcsh). When I try to Create a new environment by copying the root environment , I am getting the following error.

I have attached the error message as well as conda info. Can anybody help me with this?

![anaconda_error](https://cloud.githubusercontent.com/assets/16673994/12298125/143acbb4-b9d6-11e5-9ea9-f9fc3c319544.PNG)
![conda_info](https://cloud.githubusercontent.com/assets/16673994/12298126/143c7c8e-b9d6-11e5-9403-392b7a7852cb.PNG)

**Comment by tyler-thetyrant** [comment]
Closing outdated.
