### ISSUE TITLE
Proposal: Use jinja2 templates to configure conda features automatically

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#1959]
## Summary

Conda `features` are a great tool to distinguish variants of the same package, but manual configuration of features does not scale when this capability gets used for a wide variety of properties. This issue proposes to apply the existing jinja2 templating mechanism to configure features automatically at package build time. Recipes equipped with suitable jinja2 code can be build with a specific set of properties in three simple steps:
- Create an environment where the desired features are tracked.
- Activate that environment.
- Run `conda build my-package`. It applies jinja2 preprocessing to `my-package/meta.yaml`, re-creates the current setup in the temporary `_build` environment and then compiles my-package with the desired features.

The proposed solution does not require changes to conda itself, just enhanced recipes. A successful preliminary implementation (which differs from the present proposal in some details) can be found in the recipe collection https://github.com/ilastik/ilastik-build-conda/tree/toolset-config.
## Rationale

One and the same version of a package can exist in several incompatible variants. For example, we may compile boost with different compilers (say, vc10 and vc14) and link the boost::python library against different Python versions (say, 2.7 and 3.5) to end up with four incompatible builds of the same boost version. Similarly, we may build numpy with various choices of the BLAS library such as Intel MKL or OpenBLAS. Other packages that also require BLAS should then choose the same variant as numpy did to ensure compatibility.

Conda uses clever conventions to avoid coexistence of incompatible variants whenever possible:
- There is a one-to-one correspondence between Python versions and compiler versions.
- Packages are updated in lock-step so that the set of newest versions (at any given time) is compatible.

When this is not possible, conda encodes compatibility information into the build string. For example, `_np110py27` means that a package requires Python 2.7 and numpy 1.10. This approach works reasonably, but is not always reliable because conda's version resolution algorithm treats build strings as secondary entities: (i) build strings are only looked at when version and build numbers are identical; (ii) build string comparison only supports exact matching, no relational comparisons or wild cards as in version numbers.

Moreover, the above conventions may be too restrictive in certain situations: Some users may be forced by external circumstances to use a different compiler than conda's default, or may be restricted to a particular version of a package so that packages cannot be updated in lockstep. Therefore, conda needs a more powerful mechanism to specify requirements for compatible variants.

Fortunately, such a mechanism already exists: conda's 'features' capability. For example, to ensure that a package is only used in combination with packages that were built by the same compiler, a recipe would specify:

```
build:
  features:
    - vc10
```

if the package requires Visual Studio 2010. As a consequence, this particular package would only be considered in conda environments that are based on this compiler. A conda environment acquires this feature-enforcing behavior by installing a package which tracks the feature, i.e. whose recipe contains:

```
build:
  track_features:
    - vc10
```

To make full use of 'features', three questions need to be answered:
1. Which packages need to enforce (i.e. track) features in order to ensure that only compatible dependents are installed, and what conventions/standards shall be observed to specify those features?
2. How can we insert the appropriate 'features' and 'track_features' specifications into the recipes automatically, especially when requirements are transitive?
3. How can we guarantee that 'conda install' always respects the feature specifications?
## 1) Which features?

As an introductory example, consider the problem of incompatible compilers on Windows. Conda already uses the features 'vc10', 'vc14' etc. to distinguish compilers on windows. Since each Python version in conda is tied to a particular compiler version, the corresponding 'track_features' spec is found in the Python recipe. This leads to the slight oddity that pure C++ packages must still list Python as a build requirement in order to activate the appropriate compiler (Insteadt, it might be better to create a dedicated 'visual-studio' package which installs the appropriate runtime libaries and activates the appropriate 'track_features'.) More importantly, it prevents users from compiling Python with a different compiler. For example, it is impossible to build extension modules that require C++11 for Python 2.7 on Windows because Visual Studio 2008 (conda's default for Python 2.7) only supports C++98. Conversely, one cannot use Python 3.5 when one is forced (by whatever reason) to an older compiler than conda's default.

At present, this problem is most pronounced on Windows, because Visual Studio versions produce mutually incompatible code. In contrast, the gcc 4.x compiler series on Linux generally generate compatible binaries. However, incompatibilities may arise with the more widespread use of gcc 5.x and clang, and by incompatible versions of the C++ standard library (libstdc++ vs. libc++ on Mac is a case in point). Moreover, compilers are not the only source of incompatibility, as the above example of numpy with MKL vs. numpy with OpenBLAS demonstrates. I will look into this example in the next section. In conclusion:
1. Packages where the same version number exists in multiple, binary incompatible variants must define (i.e. `track_features`) a feature.
2. Dependents of such packages must be built in the same variants, and those variants are distinguished by the appropriate `features` specification.
3. Feature names should follow the established conventions of 'vc10' and 'vc14' or 'np100' and 'np110'.
4. The set of properties supported by features must be clearly documented in the conda manuals. There should be an well-documented open process to discuss and accept proposed additions to the set.
## 2) How to add feature specs to recipes automatically?

At present, conda features are specified manually in a package recipe's `meta.yaml` file, e.g.

```
build:
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
```

to select the appropriate compiler runtime according to the Python version. However, this approach does not scale to more widespread application of the 'features' mechanism, and is not flexible enough to allow Python to be compiled with a non-standard compiler.

However, the actual difficulty is more fundamental: `meta.yaml` are static text files by nature, whereas the information about features is only available at build time (because it depends on the build environment), and may differ between different builds of the same recipe. Conda currently solves this by means of conditionals (the `[win and py27]` above), but this technique is severely limited by the restricted set of supported conditions.

But once again, conda already offers a solution: the possibility to customize `meta.yaml` files at build time by means of jinja2 preprocessing. A simple `meta.yaml` that configures the compiler feature at build time looks like this:

```
# import the feature spec of the active compiler
{% import '$CONDA_ACTIVE_ENV/conda-meta/features/compiler.yaml' as compiler %}

package:
  name: zlib
  version: "1.2.8"

build:
  features:
    - {{compiler.feature}}  # add feature for the current build
                            # (expands into 'vc10', 'vc14' etc. as appropriate)

requirements:
  build:
    - {{compiler.build_requirement}}  # list the correct compiler as a requirement

  run:
    - {{compiler.run_requirement}}    # list the compiler runtime as a requirement

source:
  ... # as usual
about:
  ... # as usual
```

Specifically, for a vc14 (Visual Studio 2015) build, the variables resolve into

```
{{compiler.feature}}            => vc14
{{compiler.build_requirement}}  => visual-studio-build  14.0
{{compiler.run_requirement}}    => visual-studio        14.0
```

The file `conda-meta/features/compiler.yaml` is installed by the command `conda install visual-studio-build=14.0` which prepares the current environment for conda builds with this compiler. Ideally, this command would also install the compiler into the current environment, but since this is not permitted by Microsoft's license and would be too time consuming anyway, it just checks that the correct compiler is in the PATH, and terminates otherwise (e.g. if it finds Visual Studio 10.0 instead). The package `visual-studio` just installs the compiler runtime DLLs. Moreover, both packages contain a `track-features:` specification with the appropriate feature tag.

The technique can be easily extended to other sources of variation. For example, anaconda currently enforces a one-to-one relationship between compilers and Python versions (e.g. Python 2.7 is tied to Visual Studio 2008 on Windows). Thus, the compiler feature implies the Python version. If anaconda drops this restriction, an additional feature will be needed to distinguish between Python versions, e.g. `py27` and `py35`. Another interesting case is the BLAS library to be used by numpy, where users may want to choose between Atlas, Intel MKL, OpenBLAS and possibly others. Once numpy is compiled against a specific BLAS library, all other packages that need BLAS should use the same one. This is again best handled by a feature that takes values like `blas_atlas3_10`, `blas_mkl11_3`, `blas_open0_2`.

Using features for the compiler, Python version and BLAS variant, the numpy recipe's `meta.yaml` may look like

```
{% import '$CONDA_ACTIVE_ENV/conda-meta/features/compiler.yaml' as compiler %}
{% import '$CONDA_ACTIVE_ENV/conda-meta/features/python.yaml'   as python %}
{% import '$CONDA_ACTIVE_ENV/conda-meta/features/blas.yaml'     as blas %}

package:
  name: numpy
  version: "1.10.1"

build:
  features:
    - {{compiler.feature}}
    - {{python.feature}}
    - {{blas.feature}}

requirements:
  build:
    - {{compiler.build_requirement}}
    - {{python.build_requirement}}
    - {{blas.build_requirement}}
    - fftw
    - cython
    - setuptools

  run:
    - {{compiler.run_requirement}}
    - {{python.run_requirement}}
    - {{blas.run_requirement}}
    - fftw

source:
  ... # as usual
about:
  ... # as usual
```

In summary, to build a package variant aginst a specific collection of dependencies, you
- Create an environment that contains the desired dependencies. Specifically, the required jinja2 template files must be installed under `conda-meta/features/`.
- Activate that environment.
- Run `conda build pkg-name`. It applies jinja2 preprocessing to `meta.yaml`, re-creates the current setup in the temporary `_build` environment and then compiles the new package with the desired features.

No changes to conda itself are needed to implement the approach outlined above - everything can be achieved by providing suitable recipes. Specifically, packages that track features must specify the appropriate `track_features` tag and install a jinja2 template under `conda-meta/features/`. Packages that want to use a feature must read the jinja2 template from `conda-meta/features/` and apply the appropriate configurations in the `features` and `requirements` sections of their `meta.yaml` file.
## 3) How to enforce features in 'conda install'?

In theory, conda's version resolution algorithm resolves feature requirements automatically, provided the settings have been correctly configuered in the package recipes. Unfortunately, the present version resolution has a bug that prevents this from working in all situations, see issue https://github.com/conda/conda/issues/1589 and references therein for details. It appears to be difficult to fix this bug without making version resolution very slow.

A possible work-around is to add feature tags to the version number. For example, zlib compiled with Visual Studio 2015 would become `zlib-1.2.8.vc14`. This is similar to conda's current convention to add feature tags to the build string, but is much more powerful: it makes all the sophistication of conda's version comparison available to feature matching as well. It is easy to use this technique to make sure that all packages in a given conda environment are built with the same compiler. Foe example, when we build the recipe for libtiff with Visual Studio 2015, we can specify its dependency on zlib as:

```
requirements:
  run:
    - zlib   *.vc14*
```

Incompatible zlib variants lack the `.vc14` tag in their version number and will thus be excluded from version resolution. Hard-wiring a specific tag value can again be avoided by means of jinja2 variables:

```
{% import '$CONDA_ACTIVE_ENV/conda-meta/features/compiler.yaml' as compiler %}

requirements:
  run:
    - zlib   *{{compiler.version_tag}}*
```

Version tags would also simplify the process of setting up a conda environment with specific properties. For example, to create an environment containing scipy and numpy build against the OpenBLAS library, one could simply write

```
conda create -n scipy-openblas   scipy=0.16.1.blas_open0_2
```

This command would recursively install openblas and numpy with the desired feature.

A potential problem with version tags is that a version number should probably only contain at most two or three of them to avoid clutter. Thus, issue https://github.com/conda/conda/issues/1589 still needs to be solved. Nonetheless, version tags may remain a useful technique to simplify conda installation commands.

Of course, many details need to be discussed and improved before this proposal can be made an official part of the conda infrastructure. However, a working preliminary implementation (which uses jinja2 templates for just the compiler configuration and differs in various details from the present text) can be found in the recipe collection https://github.com/ilastik/ilastik-build-conda/tree/toolset-config. It provides around 130 recipes to compile a Python 2.7 ecosystem with Visual Studio 2012 and has worked very well for creating the ilastik interactive learning and segmentation toolkit on Windows (see http://ilastik.org).

Please comment!

**Comment by msarahan** [comment]
This is awesome.  Nice work, and thanks for such a detailed writeup.  I
will spend some time reviewing this in greater detail over the next few
days.

**Comment by groutr** [comment]
Very thorough writeup.  I think you should be able to use the info from repodata.json/index.json instead of relying on the file's name.

**Comment by kalefranz** [comment]
Hi @ukoethe, this is all awesome.  I'm working on putting together a draft roadmap for conda now, and definitely appreciate the input.  The roadmap at least initially will focus on use cases rather than full technical implementations, so I'll make sure the use patterns you're after are being fully addressed.

**Comment by ukoethe** [comment]
>  I think you should be able to use the info from repodata.json/index.json instead of relying on the file's name.

This may be possible (provided all the necessary information is present in repodata.json/index.json, which needs to be checked). But extracting this information during parsing of meta.yaml will probably require changes to conda itself.

**Comment by jakirkham** [comment]
Sorry I haven't read all of this yet. I am making my way through it. I see many of the recipes in the linked repo have a line like the one below.

    {% import '$CONDA_ACTIVE_ENV/toolset-info/config.yaml' as toolset %}

Could you give us some idea what is in this `config.yaml`? Also, I have seen some other files being imported in other recipes there. What do these different files offer that would not fit in `config.yaml`?

**Comment by ukoethe** [comment]
> Could you give us some idea what is in this `config.yaml`? 

`config.yaml` in my preliminary implementation corresponds to `compiler.yaml` in the above description. The file is automatically generated and installed by the compiler recipe's `build.sh/bld.bat` scripts and simply defines a number of jinja2 variables. For example, the `visual-studio-build-14.0` recipe would create a `$CONDA_ACTIVE_ENV/conda-meta/features/compiler.yaml` file that looks like this:
```
{% set name='visual-studio' %}
{% set version='14.0' %}
{% set feature='vc14' %}
{% set version_tag='.vc14' %}
{% set build_requirement='visual-studio-build 14.0' %}
{% set run_requirement='visual-studio 14.0' %}
```

> I have seen some other files being imported in other recipes there. What do these different files offer?

These files are unrelated to conda features and define a number of variables (e.g. the path to the compiler) and convenience functions (e.g. to convert between Linux and Windows paths) that are useful in `bld.bat` scripts.

**Comment by msarahan** [comment]
This is an elegant generalization of compiler/environment specification.  I am wholeheartedly for this.  As you say, on Linux, there haven't been compiler version issues in the past, but they are starting to crop up, and this proposal is a very good way to handle them.

My only concern is minimization of additional configuration at build time (just to keep things simple for recipe authors).  I see that as just an implementation detail - something to make sure that we keep in mind as we develop this.

Do you think there two steps to implementing this: a first step keeping things in the string, to avoid #1589 , and then a version after that once #1589 is fixed?  That is how you present it, and indeed it could go either way - it's just a matter of which things should get the most attention, and the timescale this change should be done on.  @kalefranz has the say here.

**Comment by jakirkham** [comment]
As far as minimization of the burden on recipe developers goes, maybe a good strategy that stays inline with this proposal is to add a template ( https://github.com/conda/conda-build/tree/master/conda_build/templates ). Though that should probably be hashed out as this handles more use cases.

**Comment by jakirkham** [comment]
I have given your proposal more thought, @ukoethe. As far as compilers go, this seems like a nice strategy. It would be really nice to get features out of the version strings, but you have said as much.

Personally, I still think features are somewhat limited when it comes to BLAS selection for instance ( https://github.com/conda/conda/issues/1476 ). The current notion of features views them as tacked on to an essentially bare recipes. It also requires the feature package be installed before installing packages that are tied to it. This becomes problematic if a package requires a dependency that tracks the feature. The resolution currently fails in this case. I wonder if this problem would surface on Windows when having a package that requires a particular version of Python.

**Comment by msarahan** [comment]
Ah, one other facet to this problem that we have discussed internally is the notion of mutual exclusivity of features.  BLAS implementations probably should not be mixed.  VC versions should not be mixed in a single runtime environment, but is it OK for standalone executables to use a different runtime?  I think it's OK to say "no" as a simplifying assumption, even though it really is OK.

I'm not sure if that really has a place here, but if it does, let's consider it.

**Comment by ukoethe** [comment]
> minimization of the burden on recipe developers

The burden is not very significant. In my implementation, the compiler recipes simply contain a file `%RECIPE_DIR%\compiler.yaml.in` with placeholders:
```
{% set name='visual-studio' %}
{% set version='@PKG_VERSION@' %}
{% set feature='@PKG_FEATURE@' %}
{% set version_tag='.@PKG_FEATURE@' %}
{% set build_requirement='visual-studio-build @PKG_VERSION@' %}
{% set run_requirement='visual-studio @PKG_VERSION@' %}
```
that can be configured by a straightforward call to `sed` in `bld.bat`. (Recall that `%RECIPE_DIR%`, `%PKG_VERSION%`, and `%PREFIX%` are all pre-defined by conda-build. I assume that unxutils or MSYS are installed.)
```
set PKG_FEATURE=vc%PKG_VERSION:.0=%
cat "%RECIPE_DIR%\compiler.yaml.in" ^
   | sed -e "s/@PKG_VERSION@/%PKG_VERSION%/g" ^
         -e "s/@PKG_FEATURE@/%PKG_FEATURE%/g" ^
   > "%PREFIX%\conda-meta\features\compiler.yaml"
```

**Comment by msarahan** [comment]
Cool. How much of that can be built into conda-build directly, so that people are only required to change meta.yaml?  I guess it should not be done only there for the sake of customizability, but providing defaults of that file if it doesn't exist and doing the sed stuff seems like good simplification from a user perspective.

**Comment by ukoethe** [comment]
> This becomes problematic if a package requires a dependency that tracks the feature.

Let's consider `conda install scipy` as an example. We must distinguish two cases: 

1. The active environment already contains a BLAS package that defines appropriate `track_featues`. Then the version resolution algorithm must only include scipy versions that define matching `features`. This should normally happen automatically, but at present the version resolution algorithm needs some help due to https://github.com/conda/conda/issues/1589 (see next post below).
2. The active environment contains no BLAS package. Then the version resolution algorithm can choose the scipy variant freely, but must make sure that a matching BLAS version gets installed as a dependency. This should be taken care of by scipy's runtime requirements, and there are again two possibilities:

  * In most cases, the feature is implied and thus uniquely defined by a package name and version (note that these requirements can be automatically configured by the jinja2 templates): 

    ```
requirements:
  run:
    - visual-studio 14.0     # contains 'track_features: - vc14'
    - openblas 0.2.*         # contains 'track_features: - blas_open0_2'
    ```
  * When this is not possible (i.e. the same package can come with different `track_features` specifications), a version tag must be appended to the package name or its version number:

    ```
requirements:
  run:
    - foo   2.*.bar1*    # contains 'track_features: - bar1'
    - baz-bar1   1.2*    # contains 'track_features: - bar1'
    ```

Please see also https://github.com/conda/conda/issues/1963 for a question about how run requiremets get specialized at package build time.

**Comment by jakirkham** [comment]
So, I think there are few more issues that can occur than just these.

Case 1 can fail due to a higher build number or version resulting in a feature not being respected ( https://github.com/conda/conda/issues/1334 ).

Case 2 can fail in another way, as well. Suppose you have a package that is dependent on SciPy and a particular BLAS. If there is no way to install these without features, it fails entirely to resolve. ( https://github.com/conda/conda/issues/1476 ) If it is possible to install both of these without features, they will be installed without features. Running an update will then install the packages with features only if they have higher version or build number ( https://github.com/conda/conda/issues/1334 ).

**Comment by ukoethe** [comment]
> Do you think there two steps to implementing this: a first step keeping things in the string, to avoid https://github.com/conda/conda/issues/1589 , and then a version after that once https://github.com/conda/conda/issues/1589 is fixed?

Obviously, I'd prefer a design where https://github.com/conda/conda/issues/1589 is fixed. Then, version tags like `.vc14` in package names or version numbers will rarely be needed. It may still be a good idea to list feature tags in the build string, but only for informative purposes (so that users don't have to open the package in order to find out about features), not for version matching (as this is too fragile, given the second class nature of build strings).

However, if https://github.com/conda/conda/issues/1589 cannot be fixed before going 'all in' on features, feature tags in version numbers (or package names) are a great help for the version resolution algorithm. For example, a package that needs at least version 1.46 of boost would specify
```
requirements:
  run:
    - visual-studio 14.0
    - boost    >=1.46,*.vc14*
```
Thus, the version matching algorithm will only consider packages that have the right feature, because version number matching excludes everything else to begin with. Additional requirements (more features) can simply be concatenated with the 'and' (comma) operator. Using jinja2 templates, this generalizes into
```
requirements:
  run:
    - {{compiler.run_requirement}} 
    - boost    >=1.46,*{{compiler.version_tag}}*
```

**Comment by ukoethe** [comment]
> So, I think there are few more issues that can occur than just these.

You are right, but aren't all of these problems just bugs in the version resolution algorithm? When I talk about https://github.com/conda/conda/issues/1589, I implicitly include similar problems like https://github.com/conda/conda/issues/1334 and https://github.com/conda/conda/issues/1476 that also need to be solved. Would the trick with `*{{compiler.version_tag}}*` serve as a workaround there as well?

**Comment by jakirkham** [comment]
> You are right, but aren't all of these problems just bugs in the version resolution algorithm?

This should definitely be true of issue ( https://github.com/conda/conda/issues/1334 ).

Not sure that is true of issue ( https://github.com/conda/conda/issues/1476 ), but it may work.

**Comment by ukoethe** [comment]
> How much of that can be built into conda-build directly, so that people are only required to change meta.yaml?

If the functionality is built into conda-build directly, we should also consider adding the required information to `index.json` as @groutr suggested. Then we could pre-define a set of variables that can be used in `meta.yaml` instead of the jinja2 variables. My solution was intentionally designed to be non-intrusive on conda, but the pros and cons of an intrusive solution should be seriously discussed. 

Although my solution requires some biolerplate, it has the advantage that it is very transparent -- everyone can readily see what's going on in the jinja templates and what effects they have on `meta.yaml`. A simple thing we could provide to help recipe developers reducing their boilerplate is a utility that creates stubs for `package.yaml.in` etc.

**Comment by ukoethe** [comment]
I recently found another important situation where jinja2 configuration will be helpful: conda-build version 1.8.2 on Windows silently adds the default compiler to the PATH, unless this is explicitly overridden in the recipe by:
```
build:
  msvc_compiler: vc11  # request a specific compiler
```
Apart from the question if conda's default behavior is desirable (it took me several hours of debugging to find out why conda used inconsistent compiler settings -- the errors were really weired), the compiler version should not be hard-coded in the recipe. Instead, one might use a jinja2 variable:
```
build:
  msvc_compiler: {{compiler.version}}  # [win]
```

**Comment by mwiebe** [comment]
I've added a feature proposal https://github.com/conda/conda/issues/2901 to try and make a more generic mechanism related to this issue. Ideally `conda build` shouldn't hard-code anything specific about MSVC versions. If a `build.d` script as described set up the compiler to use, there could be a convention that it always sets up an environment variable giving the matching runtime a built package must depend on.

**Comment by kalefranz** [comment]
I think all of this is being incorporated into conda-build 3.  Further discussion should happen under those conda-build issue threads.

**Comment by ukoethe** [comment]
Thanks for your great work!
