### ISSUE TITLE
document per URL proxy config

### ISSUE THREAD

**Issue by electronwill** [conda/conda#1960]
Conda proxy configuration per URL needs to be documented, as discussed in https://github.com/conda/conda/issues/1527 by @bkreider @jasongrout and others. Also created issue https://github.com/conda/conda-docs/issues/231 in the conda-docs repo to track it. To start we need someone who understands the functionality to write a brief plain text first draft of what should be added to the docs. @jasongrout , can you please jot down a first draft? Posting it as a reply here is fine.

**Comment by jasongrout** [comment]
See https://github.com/conda/conda/issues/1527#issuecomment-172094053

**Comment by jasongrout** [comment]
Thanks for following up on this!
