### ISSUE TITLE
Conda install homemade package leave Pip listing in 'conda list'

### ISSUE THREAD

**Issue by eL0ck** [conda/conda#1962]
I have build a conda package from a git repo, referring to (http://conda.pydata.org/docs/build_tutorials/pkgs2.html) . 

The code is public:
https://tlelson@bitbucket.org/tlelson/tims_py_utils.git

It is build it with 'conda build' and uploaded to anaconda.  Installing into a new conda environment with:

``` bash
conda install -c https://conda.anaconda.org/tle tims_py_utils
```

Doing a 'conda list' returns 2 entries! 

``` bash
...
tims-py-utils-2.1-12      g81423b5                  <pip>
tims_py_utils             2.1                 12_g81423b5    file:///Users/tims-MBP/miniconda3/conda-bld/osx-64/tims_py_utils-2.1-12_g81423b5.tar.bz2
...
```

Why is the package listed like it has been installed separately with pip? '--no-pip' option does not display the listing but my understanding was that this option removes "pip-only" listings which this is not.

``` bash
$ conda list -h
...
  --no-pip              Do not include pip-only installed packages.
```

**Actual Questions**
Should I be doing something different in the build.sh to avoid the package going to 'site-packages'?
Why does the package list as being installed from file not the anaconda channel?
What am I doing differently to other conda packages that install without the pip item?

**Comment by groutr** [comment]
Can you post a link to the recipe?

**Comment by telson** [comment]
Hi @groutr,
The recipe is in the repo with the code.  Heres the [meta.yaml] (https://bitbucket.org/tlelson/tims_py_utils/src/7aee719584a46842780dec144578dc94b3e06e9c/tims_py_utils/meta.yaml?at=master&fileviewer=file-view-default "meta.yaml") and the [build.sh](https://bitbucket.org/tlelson/tims_py_utils/src/7aee719584a46842780dec144578dc94b3e06e9c/tims_py_utils/build.sh?at=master&fileviewer=file-view-default)
