### ISSUE TITLE
How to specialize a package's runtime requirements during a build?

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#1963]
When a package has a dependency, but is very flexible about which version of that dependency is used, one would define the recipe's build and run requirements very generally. For example, the `hdf5` recipe needs `zlib`, but the version doesn't matter much. Therefore, https://github.com/conda/conda-recipes/blob/master/hdf5/meta.yaml simply specifies:

```
package:
  name: hdf5
  version: 1.8.14

requirements:
  build:
    - zlib
  run:
    - zlib
```

However, once hdf5 is built against a _specific_ version of zlib (say, `zlib-1.2.8`), the run requirement must be restricted to zlib versions that are binary compatible with the one used during the build. This is indeed the case in official anaconda packages (the ones I get by calling `conda install hdf5`), whose `index.json` specifies

```
"depends": [
    "zlib 1.2*"
  ],
  "requires": [
    "zlib 1.2.8"
  ], 
```

However, I have not found any documented way to achieve an automatic specialization from `zlib` to `zlib 1.2*` in one's own recipes and builds. What am I missing?

**Comment by jakirkham** [comment]
There was this proposal ( https://github.com/conda/conda-build/pull/728 ) to extend `x.x` previously to achieve this behavior.

**Comment by jakirkham** [comment]
Of course, @stuarteberg made a bit more robust counter proposal, but I don't know whatever became of it.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1993
