### ISSUE TITLE
conda update astropy

### ISSUE THREAD

**Issue by ckreisch** [conda/conda#1964]
linking failed and now packages are unlinked. Error below. How do I resolve the issues?

atlas@atlas-Inspiron-5537:~$ conda update astropy
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/atlas/anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| astropy-1.1.1 | np110py27_0         8.1 MB |
| conda-3.19.0 | py27_0         176 KB |
| conda-env-2.4.5 | py27_0          24 KB |
| mkl-rt-11.1 | p0       100.1 MB |
| numpy-1.10.2 | py27_p0         5.9 MB |
| openssl-1.0.2e | 0         3.2 MB |
| pycosat-0.6.1 | py27_0         151 KB |
| python-2.7.11 | 0        12.0 MB |
| pyyaml-3.11 | py27_1         295 KB |
| requests-2.9.1 | py27_0         605 KB |
| sqlite-3.9.2 | 0         3.9 MB |
| tk-8.5.18 | 0         1.9 MB |
| yaml-0.1.6 | 0         246 KB |
| zlib-1.2.8 | 0         100 KB |

```
------------------------------------------------------------
                                       Total:       136.6 MB
```

The following packages will be UN-linked:

| package | build |
| --- | --- |
| astropy-0.3.0 | np18py27_0 |
| conda-3.4.1 | py27_0 |
| numpy-1.8.0 | py27_0 |
| openssl-1.0.1g | 0 |
| pycosat-0.6.0 | py27_0 |
| python-2.7.6 | 1 |
| pyyaml-3.10 | py27_0 |
| requests-2.2.1 | py27_0 |
| sqlite-3.7.13 | 0 |
| tk-8.5.13 | 0 |
| yaml-0.1.4 | 0 |
| zlib-1.2.7 | 0 |

The following packages will be linked:

| package | build |
| --- | --- |
| astropy-1.1.1 | np110py27_0   hard-link |
| conda-3.19.0 | py27_0   hard-link |
| conda-env-2.4.5 | py27_0   hard-link |
| mkl-rt-11.1 | p0   hard-link |
| numpy-1.10.2 | py27_p0   hard-link |
| openssl-1.0.2e | 0   hard-link |
| pycosat-0.6.1 | py27_0   hard-link |
| python-2.7.11 | 0   hard-link |
| pyyaml-3.11 | py27_1   hard-link |
| requests-2.9.1 | py27_0   hard-link |
| sqlite-3.9.2 | 0   hard-link |
| tk-8.5.18 | 0   hard-link |
| yaml-0.1.6 | 0   hard-link |
| zlib-1.2.8 | 0   hard-link |

Proceed ([y]/n)? y

Fetching packages ...
astropy-1.1.1-np110py27_0.tar.bz2 100% |#############################################################################| Time: 0:00:03   2.30 MB/s
conda-3.19.0-py27_0.tar.bz2 100% |###################################################################################| Time: 0:00:00 492.74 kB/s
conda-env-2.4.5-py27_0.tar.bz2 100% |################################################################################| Time: 0:00:00 195.17 kB/s
mkl-rt-11.1-p0.tar.bz2 100% |########################################################################################| Time: 0:01:01   1.70 MB/s
numpy-1.10.2-py27_p0.tar.bz2 100% |##################################################################################| Time: 0:00:04   1.43 MB/s
openssl-1.0.2e-0.tar.bz2 100% |######################################################################################| Time: 0:00:01   1.71 MB/s
pycosat-0.6.1-py27_0.tar.bz2 100% |##################################################################################| Time: 0:00:00 409.30 kB/s
python-2.7.11-0.tar.bz2 100% |#######################################################################################| Time: 0:00:04   2.54 MB/s
pyyaml-3.11-py27_1.tar.bz2 100% |####################################################################################| Time: 0:00:00 632.58 kB/s
requests-2.9.1-py27_0.tar.bz2 100% |#################################################################################| Time: 0:00:00 735.13 kB/s
sqlite-3.9.2-0.tar.bz2 100% |########################################################################################| Time: 0:00:05 768.00 kB/s
tk-8.5.18-0.tar.bz2 100% |###########################################################################################| Time: 0:00:01   1.08 MB/s
yaml-0.1.6-0.tar.bz2 100% |##########################################################################################| Time: 0:00:00 419.37 kB/s
zlib-1.2.8-0.tar.bz2 100% |##########################################################################################| Time: 0:00:00 294.71 kB/s
Extracting packages ...
[      COMPLETE      ] |##################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                             |   7%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/atlas/anaconda/bin/conda", line 5, in <module>
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/plan.py", line 357, in link
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/install.py", line 438, in link
  File "/home/atlas/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/fits2bitmap'

atlas@atlas-Inspiron-5537:~$ ipython --pylab
bash: /home/atlas/anaconda/bin/ipython: /home/atlas/anaconda/bin/python: bad interpreter: No such file or directory
atlas@atlas-Inspiron-5537:~$ conda update astropy
bash: /home/atlas/anaconda/bin/conda: No such file or directory

atlas@atlas-Inspiron-5537:~$ conda info
bash: /home/atlas/anaconda/bin/conda: No such file or directory

**Comment by tyler-thetyrant** [comment]
Closing outdated.
