### ISSUE TITLE
`conda install flask-sqlalchemy` fails.

### ISSUE THREAD

**Issue by abdulmuneer** [conda/conda#1966]
``` shell
$conda install Flask-SQLAlchemy
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: flask-sqlalchemy
Did you mean one of these?
    sqlalchemy
You can search for this package on Binstar with
    binstar search -t conda flask-sqlalchemy
You may need to install the Binstar command line client with
    conda install binstar
```

However, I see that the package is listed under http://anaconda.org/pypi/flask-sqlalchemy .
I am trying this on Mac OS-X with a virtual env created using conda.

**Comment by ahmadia** [comment]
Looks like you are using an out of date conda.  Can you update?

```
conda update conda
```

I'm not sure if `pypi` has `flask-sqlalchemy`, but I know that the jakirkham channel does, so you could:

```
conda install -c jakirkham flask-sqlalchemy
```

I think this may be Python 2.7-only, does this fix your issue?

**Comment by kalefranz** [comment]
Yeah there isn't a `flask-sqlalchemy` conda package yet in the Anaconda Distribution repo at repo.continuum.io.  There are, however, multiple people who have created the package and posted it to anaconda.org.  Just search there.  Here's another one...

    conda install -c coursera flask-sqlalchemy

There's also no reason you can't `pip install` also, assuming it's a simple all-python (no C-code) package.
