### ISSUE TITLE
conda install r-essentials error harfbuzz.pc no such file or directory

### ISSUE THREAD

**Issue by lstavr** [conda/conda#1969]
Hi, I tried to install r-essentials to use with Jupyter and I get the following:

conda install -c r r-essentialsFetching package metadata: ......
Solving package specifications: ..........................................................................................
Package plan for installation in environment /home/username/anaconda3:

The following NEW packages will be INSTALLED:

```
harfbuzz:        0.9.35-6          
ipykernel:       4.2.2-py35_0      
ipython:         4.0.2-py35_0      
ipywidgets:      4.1.1-py35_0      
jupyter_console: 4.1.0-py35_0      
nbconvert:       4.1.0-py35_0      
notebook:        4.1.0-py35_0      
pango:           1.36.8-3          
r:               3.2.2-0           
r-assertthat:    0.1-r3.2.2_1      
r-base:          3.2.2-0           
r-base64enc:     0.1_3-r3.2.2_0    
r-bh:            1.58.0_1-r3.2.2_0 
r-bitops:        1.0_6-r3.2.2_1    
r-boot:          1.3_17-r3.2.2_0   
r-car:           2.1_0-r3.2.2_0    
r-caret:         6.0_62-r3.2.2_0   
r-catools:       1.17.1-r3.2.2_2   
r-chron:         2.3_47-r3.2.2_0   
r-class:         7.3_14-r3.2.2_0   
r-cluster:       2.0.3-r3.2.2_0    
r-codetools:     0.2_14-r3.2.2_0   
r-colorspace:    1.2_6-r3.2.2_0    
r-data.table:    1.9.6-r3.2.2_0    
r-dbi:           0.3.1-r3.2.2_2    
r-dichromat:     2.0_0-r3.2.2_2    
r-digest:        0.6.8-r3.2.2_2    
r-dplyr:         0.4.3-r3.2.2_0    
r-essentials:    1.1-r3.2.2_0      
r-evaluate:      0.8-r3.2.2_0      
r-foreach:       1.4.3-r3.2.2_0    
r-foreign:       0.8_66-r3.2.2_0   
r-formatr:       1.2.1-r3.2.2_0    
r-ggplot2:       1.0.1-r3.2.2_0    
r-glmnet:        2.0_2-r3.2.2_0    
r-gtable:        0.1.2-r3.2.2_2    
r-hexbin:        1.27.1-r3.2.2_0   
r-highr:         0.5.1-r3.2.2_0    
r-htmltools:     0.2.6-r3.2.2_2    
r-htmlwidgets:   0.5-r3.2.2_0      
r-httpuv:        1.3.3-r3.2.2_0    
r-irdisplay:     0.3-r3.2.2_0      
r-irkernel:      0.5-r3.2.2_1      
r-iterators:     1.0.8-r3.2.2_0    
r-jsonlite:      0.9.17-r3.2.2_0   
r-kernsmooth:    2.23_15-r3.2.2_0  
r-knitr:         1.11-r3.2.2_0     
r-labeling:      0.3-r3.2.2_1      
r-lattice:       0.20_33-r3.2.2_0  
r-lazyeval:      0.1.10-r3.2.2_2   
r-lme4:          1.1_10-r3.2.2_0   
r-magrittr:      1.5-r3.2.2_1      
r-maps:          3.0.0_2-r3.2.2_0  
r-markdown:      0.7.7-r3.2.2_1    
r-mass:          7.3_45-r3.2.2_0   
r-matrix:        1.2_2-r3.2.2_0    
r-matrixmodels:  0.4_1-r3.2.2_0    
r-mgcv:          1.8_9-r3.2.2_0    
r-mime:          0.4-r3.2.2_0      
r-minqa:         1.2.4-r3.2.2_1    
r-munsell:       0.4.2-r3.2.2_1    
r-nlme:          3.1_122-r3.2.2_0  
r-nloptr:        1.0.4-r3.2.2_1    
r-nnet:          7.3_11-r3.2.2_0   
r-pbkrtest:      0.4_2-r3.2.2_2    
r-plyr:          1.8.3-r3.2.2_0    
r-proto:         0.3_10-r3.2.2_1   
r-quantmod:      0.4_5-r3.2.2_0    
r-quantreg:      5.19-r3.2.2_0     
r-r6:            2.1.1-r3.2.2_0    
r-randomforest:  4.6_12-r3.2.2_0   
r-rbokeh:        0.2.2-r3.2.2_0    
r-rcolorbrewer:  1.1_2-r3.2.2_2    
r-rcpp:          0.12.2-r3.2.2_0   
r-rcppeigen:     0.3.2.5.1-r3.2.2_0
r-recommended:   3.2.2-r3.2.2_0    
r-repr:          0.3-r3.2.2_0      
r-reshape2:      1.4.1-r3.2.2_1    
r-rjsonio:       1.3_0-r3.2.2_1    
r-rmarkdown:     0.8.1-r3.2.2_0    
r-rpart:         4.1_10-r3.2.2_0   
r-rzmq:          0.7.7-r3.2.2_3    
r-scales:        0.3.0-r3.2.2_0    
r-shiny:         0.12.2-r3.2.2_0   
r-sparsem:       1.7-r3.2.2_0      
r-spatial:       7.3_11-r3.2.2_0   
r-stringi:       1.0_1-r3.2.2_0    
r-stringr:       1.0.0-r3.2.2_0    
r-survival:      2.38_3-r3.2.2_0   
r-tidyr:         0.3.1-r3.2.2_0    
r-ttr:           0.23_0-r3.2.2_0   
r-uuid:          0.1_2-r3.2.2_0    
r-xtable:        1.8_0-r3.2.2_0    
r-xts:           0.9_7-r3.2.2_0    
r-yaml:          2.1.13-r3.2.2_1   
r-zoo:           1.7_12-r3.2.2_1   
```

Proceed ([y]/n)? y 

Linking packages ...

Traceback (most recent call last):
  File "/home/username/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/install.py", line 645, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/home/username/anaconda3/lib/python3.5/site-packages/conda/install.py", line 277, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/anaconda3/lib/pkgconfig/harfbuzz.pc'

My conda info output:

platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/username/anaconda3  (writable)
  default environment : /home/username/anaconda3
     envs directories : /home/username/anaconda3/envs
        package cache : /home/username/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Thank you

**Comment by kalefranz** [comment]
Sounds like a corrupt/bad package.  If this is still a problem, consider filing an issue with https://github.com/ContinuumIO/anaconda-issues.
