### ISSUE TITLE
Add "Portable" command line option to miniconda installer

### ISSUE THREAD

**Issue by Korijn** [conda/conda#1977]
We've tried to deploy a web application on Azure's web apps, using the silent install functionality of the miniconda installer. Since we're deploying to a sandbox there, we can't modify global machine state, such as the registry. We thought that we could install portably, but of course, among others, the installer registers the uninstaller, and this causes the deployment to fail. See https://github.com/projectkudu/kudu/issues/1862

I've tried to find the source for your .msi installer so I could open a PR, but I guess they're closed source as I couldn't find them. Can you add an option to the installer so miniconda installs 100% portable, e.g. without touching the registry, program files and environment variables? Alternatively, please open-source the installer so I can submit a PR?

**Comment by msarahan** [comment]
It's an NSIS installer, not an msi.  Several default ways of dealing with NSIS installers apply (such as silent installation) - so consider documentation of NSIS also applicable here.  The options you're looking for are custom options, though, documented at http://conda.pydata.org/docs/help/silent.html

Namely:

    /AddToPath=0
    /RegisterPython=0

**Comment by Korijn** [comment]
I don't think you've read my post carefully enough: we used those features, but the installer still writes to the registry so that Windows can find the uninstaller, among others.

**Comment by msarahan** [comment]
Nope, sorry, I didn't read it closely enough.  I'll poke around and see if I can fix that.

**Comment by msarahan** [comment]
This should be an easy fix with an additional flag.  I will ask today about when we can make a new installer available to you.

**Comment by Korijn** [comment]
Excellent news! Thanks for your efforts. :)

So if I understand correctly, this additional flag will prevent *all* registry manipulation, allowing installation in sandboxed environments?

**Comment by msarahan** [comment]
Yes, I think that's what you need.  I'm just making sure WriteRegStr will never get called, since that is what seems to be tripping you up.

This is only going to be a command line parameter.  I don't want to add an esoteric checkbox to the GUI installer.

**Comment by Korijn** [comment]
No problem. :) Sounds good to me!

**Comment by kalefranz** [comment]
Let's make sure @ilanschnell we get this out with the next Anaconda Distribution release at the latest.

**Comment by kalefranz** [comment]
@msarahan Do we have a PR for this?  @ilanschnell wants to make sure it gets in the release we're cutting tomorrow.

**Comment by msarahan** [comment]
Sorry, can't remember. It sick today. Might have appendicitis. Will look
into this asap, but might not make tomorrow.

**Comment by Korijn** [comment]
Any news? :)

**Comment by msarahan** [comment]
I did not have appendicitis. ;)

This change has been merged, and will be present in the next miniconda release.

**Comment by Korijn** [comment]
Sweet! Thanks. :)

**Comment by ilanschnell** [comment]
Let's wait until we get conda 4.0 (which includes the improved solver) out.  This will happen next week.

**Comment by Korijn** [comment]
So did it come out? I didn't notice [the silent install instructions page](http://conda.pydata.org/docs/help/silent.html) update after the 4.x release.

**Comment by CTrauma** [comment]
Just stumbled on this exact same issue and found running the installer with /? gives the following usage:

Usage: miniconda.exe [options]
Options:

/InstallationType=AllUsers [default: JustMe]

/AddToPath=[0|1] [default: 1]

/RegisterPython=[0|1] [default: AllUsers: 1, JustMe: 0]

/NoRegistry=[0|1] [default: AllUsers: 0, JustMe: 0]

Examples:
Install for all users, but don't add to PATH env var:
miniconda.exe /InstallationType=AllUsers /AddToPath=0

Install for just me, but register as system Python:
miniconda.exe /RegisterPython=1

Install for just me, with no registry modification (for CI):
miniconda.exe /NoRegistry=1

**Comment by Korijn** [comment]
Closing since it appears to be implemented!

**Comment by GandalfSaxe** [comment]
Ah I finally found it: https://conda.io/docs/user-guide/install/windows.html

Turns out there are quite a few anaconda and conda installation doc pages that's pretty similar.

It does not mention the /NoRegistry option though so that should probably be included.
