### ISSUE TITLE
python crashes when creating an environment

### ISSUE THREAD

**Issue by dacoex** [conda/conda#1978]
In reference to 
http://conda.pydata.org/docs/using/envs.html#create-an-environment

I tried to create an environment by
`conda create --name pvlib_pvsystem anaconda`

then, Python crashes.

but the following works:
`conda create -n pvlib_pvsystem python=3.5 anaconda`

System: Windows, 64bit

**Comment by msarahan** [comment]
pinging @csoja @kalefranz @ilanschnell - this is probably more of the VC features not getting enabled when python version is not explicitly specified.

**Comment by kalefranz** [comment]
Guessing we have this nailed down and solved by now?  Going to go ahead and close this here.

**Comment by zangruirui** [comment]
how did you resoved this question?
