### ISSUE TITLE
`conda update ipython` fails

### ISSUE THREAD

**Issue by tombaker** [conda/conda#1980]
```
Traceback (most recent call last):
  File "/Users/tbaker/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/install.py", line 616, in link
    os.makedirs(dst_dir)
  File "/Users/tbaker/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/tbaker/anaconda/lib/python2.7/site-packages/traitlets/utils/tests'

conda info
Current conda install:

             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.14.1
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : /Users/tbaker/anaconda  (writable)
  default environment : /Users/tbaker/anaconda
     envs directories : /Users/tbaker/anaconda/envs
        package cache : /Users/tbaker/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by msarahan** [comment]
One thing that might cause this sort of error is if files are in use by
some running Python process.  Please make sure to kill all running IPython
processes before trying to update.  To be completely sure, I guess you
could reboot your computer, but that should not really be necessary.  Also
avoid ever doing any "sudo" commands (pip or conda) - this will leave files
with root permissions, leading to these sorts of errors.

**Comment by tombaker** [comment]
Thank you, Mike!

My log showed that I routinely ran pip and conda with sudo :-(

I fixed the problem by deleting the entire ~/anaconda directory
and reinstalling from scratch.

Best regards,
Tom

On Thu, Jan 21, 2016 at 06:09:17AM -0800, Mike Sarahan wrote:
> One thing that might cause this sort of error is if files are in use by
> some running Python process.  Please make sure to kill all running IPython
> processes before trying to update.  To be completely sure, I guess you
> could reboot your computer, but that should not really be necessary.  Also
> avoid ever doing any "sudo" commands (pip or conda) - this will leave files
> with root permissions, leading to these sorts of errors.
> 
> On Thu, Jan 21, 2016 at 7:40 AM tombaker <notifications@github.com> wrote:
> 
> > Traceback (most recent call last):
> >   File "/Users/tbaker/anaconda/bin/conda", line 5, in <module>
> >     sys.exit(main())
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
> >     args_func(args, p)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
> >     args.func(args, p)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
> >     install.install(args, parser, 'update')
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
> >     plan.execute_actions(actions, index, verbose=not args.quiet)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
> >     inst.execute_instructions(plan, index, verbose)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
> >     cmd(state, arg)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
> >     link(state['prefix'], arg, index=state['index'])
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
> >     install.link(pkgs_dir, prefix, dist, lt, index=index)
> >   File "/Users/tbaker/anaconda/lib/python2.7/site-packages/conda/install.py", line 616, in link
> >     os.makedirs(dst_dir)
> >   File "/Users/tbaker/anaconda/lib/python2.7/os.py", line 157, in makedirs
> >     mkdir(name, mode)
> > OSError: [Errno 13] Permission denied: '/Users/tbaker/anaconda/lib/python2.7/site-packages/traitlets/utils/tests'
> >
> > conda info
> > Current conda install:
> >
> >              platform : osx-64
> >         conda version : 3.19.0
> >   conda-build version : 1.14.1
> >        python version : 2.7.11.final.0
> >      requests version : 2.9.0
> >      root environment : /Users/tbaker/anaconda  (writable)
> >   default environment : /Users/tbaker/anaconda
> >      envs directories : /Users/tbaker/anaconda/envs
> >         package cache : /Users/tbaker/anaconda/pkgs
> >          channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
> >                         https://repo.continuum.io/pkgs/free/noarch/
> >                         https://repo.continuum.io/pkgs/pro/osx-64/
> >                         https://repo.continuum.io/pkgs/pro/noarch/
> >           config file : None
> >     is foreign system : False
> >
> > ???
> > Reply to this email directly or view it on GitHub
> > <https://github.com/conda/conda/issues/1980>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/conda/conda/issues/1980#issuecomment-173579628

-- 
Tom Baker <tom@tombaker.org>
