### ISSUE TITLE
Remove packages using wildcard

### ISSUE THREAD

**Issue by alexbw** [conda/conda#1984]
While developing, I find it would be useful to remove packages via wildcard, like to cleanse all perl, R or lua packages I might do `conda remove perl-*`.

This doesn't seem to work, but is this something folks would be interested in?

**Comment by msarahan** [comment]
+1, especially with namespace prefixes like you mention.  The thing to be careful of is just to not get it mixed up with wildcards for versioning.

**Comment by ilanschnell** [comment]
So what would `conda remove python-*` mean?  Would it remove all of these:
```
python-2.7.11-0
python-3.4.3-2
python-dateutil-2.4.2-0
```
Since wildcards usually apply to filenames, I think the answer should be YES.

**Comment by mcg1969** [comment]
I will disagree with @ilanschnell here. The wildcard should be applied only to the filename, not to the version number.

**Comment by ilanschnell** [comment]
Yes, because you normally give `conda remove` just the package name, it would indeed make more sense if the wildcard only applies to the package name.  So `conda remove python-*` removes all packages for which the package name matches `python-*` (which `python` itself does not).

**Comment by mcg1969** [comment]
We do need to get proper namespace support in conda soon, but regardless, this wildcard strategy looks good. I have a pretty decent idea of how we could implement it with the current code.

**Comment by ilanschnell** [comment]
I think we should match all currently installed package names, against a regex, where `*` is replaced by `.*`.  So, for example `python-*` becomes the regex `python-.*$`.  The `$` is always added to match the end of the string.

**Comment by amodig** [comment]
How is this going? E.g. uninstalling all R packages is now pain in the ass, even though they have a namespace.

**Comment by kalefranz** [comment]
Wouldn't `conda uninstall r` or `conda uninstall python` be better for this?  You'll grab all dependencies in the uninstall and not have to worry about missing something with the wildcard match.

**Comment by kalefranz** [comment]
Plus, it's already implemented.

**Comment by michaelaye** [comment]
I don't understand @kalefranz 's comment here. It's not what the OP had in mind. If I accidentally install a lot of stuff into an environment using `--file`, it would be really nice to be able to efficiently remove stuff as well. So, for example, remove all sphinxcontrib packages using `conda remove sphinxcontrib-*`, which is not possible using simply `conda uninstall sphinxcontrib`?
