### ISSUE TITLE
Scipy v0.17 update fails

### ISSUE THREAD

**Issue by methodds** [conda/conda#1987]
I need to update Scipy to v0.17 (because the latest gensim version which I need depends on it). However when the process fails via pip because of  a long  error message ending with:
`no lapack/blas resources found`
The corresponding packages (on Linux Mint, x64) are already installed. How can I adjust my anaconda environment so that the update works?

**Comment by Carrie0302** [comment]
I ran into the same problem when updating gensim on anaconda.  I had to update my setuptools before installing gensim.

conda update setuptools

**Comment by tyler-thetyrant** [comment]
Closing outdated.
