### ISSUE TITLE
Doesn't handle recursion ('**') in package_data setup.py option

### ISSUE THREAD

**Issue by filmackay** [conda/conda#1993]
conda is not handling the following setup.py line: `package_data={'sandman2': ['templates/**.html']}`

Building without conda correctly picks up the `templates/admin/index.html` file, whereas conda does not. It should?

eg. `https://github.com/jeffknupp/sandman2/blob/master/setup.py`

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2003
