### ISSUE TITLE
conda install geos still requires geos install 

### ISSUE THREAD

**Issue by bryanSME** [conda/conda#1995]
I'm trying to figure out why when installing geos with conda i still need to install geos. There is no issue in Windows. In all three cases (OS-X, Ubuntu, Fedora), this works.  Why am I using conda to install geos when I'm also installing geos with the os package manager?

After a fresh install on Anaconda2 1.4.x on Ubuntu, Fedora, OS-X, I'm performing,   

```
conda install geos pyproj django
```

which among others, installs "geos: 3.4.2-0 defaults".  To test this, I'm running,   

```
from django.contrib.gis.geos import Point
```

which errors out with geos not being found.  sorry im not posting the exact error.  It's a lot of work to recreate. I'll add it in later if needed.  

To fix this I'm running
#### Ubuntu:

```
apt-get install libgeos-c1 libgeos-3.4.2
```
#### Fedora:

```
dnf install geos-python
```

geos-python installs: geo x86_6 3.4.2-6.fc2
#### OSX:

```
brew install gdal
```

not 100% sure what this installs

**Comment by tyler-thetyrant** [comment]
Conda default channel doesn't have geos and django.
You'll have to do `conda install -c anaconda geos=3.5. django=1.10.5`
