### ISSUE TITLE
How to select a package from a particular channel?

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1997]
I am trying to install the `geos` package which is available from many different channels on Anaconda Cloud.  I also have it in my local package cache.  I would like to install the `SciTools` version, but I am failing to do so.  What command or sequence of commands will give me the latest  SciTools channel OS X platform version of the `geos` package?

https://anaconda.org/SciTools/geos/files

**Comment by kalefranz** [comment]
conda install -c SciTools geos
