### ISSUE TITLE
Conda doesn't set the correct environment variables for pre/pos-link scripts

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#2008]
I would like to be  able to access some details of my package when running the post-link script (mainly which files are installed).

The documentation ( http://conda.pydata.org/docs/building/build-scripts.html ) says that there is an environment variable called RECIPE_DIR containing the path to the recipe. However I do not see it being set.

**Comment by kalefranz** [comment]
The docs have apparently been updated.  RECIPE_DIR is no longer an option.
