### ISSUE TITLE
remove --all doesn't delete the environment

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#201]
`conda remove -n env --all` removes everything from the environment, but it leaves the empty env dir there.

**Comment by nathanielatom** [comment]
Issue still present in conda 3.19.0. The env directory is not empty, it still contains /lib/python2.7/site-packages/ and all everything inside. Platform: darwin 15

**Comment by zhongdai** [comment]
Hey, I got the same problem, you may need to run in sudo mode to get the folder deleted.

Here is my sample, I run
```bash
conda env remove --name myenvname
```
then I run
```bash
conda env list
```
I still saw the `myenvname` appears in the list. I tried
```bash
sudo conda env remove --name myenvname
```
It worked!

**Comment by aiMojica10** [comment]
Conda does not remove environment 
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda2  (read only)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\Users\xxxx\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda2\envs
                          C:\Users\xxxx\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\xxxx\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py remove -n surprise --verbose`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_remove.py", line 121, in execute
        raise CondaValueError('no package names supplied,\n'
    CondaValueError: no package names supplied,
           try "conda remove -h" for more details

**Comment by lucainnocenti** [comment]
Is there a solution that doesn't require sudo access?

**Comment by cramjaco** [comment]
I can confirm that directly removing the environment folder rm /home/cramjaco/Programs/anaconda3/envs/myenv does indeed make that environment stop showing up with `conda env list` in my machine. Can't confirm this won't have any interesting side effects though.

**Comment by thisisreallife** [comment]
Still the same issue on Win10 with conda version 4.8.

**Comment by ma-sadeghi** [comment]
Same here (Win10 conda 4.8) -> the env folder is still there after remove

**Comment by qqgg231** [comment]
Same with conda 4.8.3 on win10

**Comment by BrenBarn** [comment]
Me too, and for me there are some "conda trash" in a Scripts directory in the environment directory.

**Comment by QLutterYin** [comment]
me too

**Comment by agilevic** [comment]
Same thing. The Scripts folder with bunch of .exe and .conda_trash files remains, likely preventing the package directory removal. Among the files in Scripts are autogenerated entry point exe, pip, pip3 and wheel. Windows 10, conda 4.8.5.

**Comment by Mereep** [comment]
Having the same problem. It just does something for a while. The environment remains. No error given. Conda 4.8.5

**Comment by sven5s** [comment]
I faced a similar issue and I also couldn't delete it with the Explorer. My problem was a running jupyter notebook instance with nb_conda_kernels.

**Comment by sonnyarora** [comment]
I ran into this issue with conda 4.3.30 running on Redhat 6.10. Turns out I had the environment active in another terminal window. Deactivating all instances of the environment allowed me to delete the environment.

**Comment by mganglb** [comment]
same problem.
Win10, conda 4.8.5

i tried the two commands below (also as administrator). The environment seems to be removed but the directory still exists and is activateable (bigger problem).
conda remove -n <env> --all
conda env remove -n <env>

Now with conda 4.9.2 it is solved for me. No administrator rights needed.

**Comment by agilevic** [comment]
@asmeurer this might need to be reopened. I suspect there may be some side effect of conda becoming a batch script (conda.bat). One thing that comes to mind with .bat scripts is if you execute one script from another without using the "call" keyword the calling script will immediately exit. Conda.bat is first on the PATH, so chances are it gets invoked from within itself under some circumstances?

```
(dev37) C:\Users\volex>where conda
C:\Users\volex\AppData\Local\Continuum\anaconda3\condabin\conda.bat

(dev37) C:\Users\volex>dir C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts\conda.*
 Volume in drive C is Local Disk
 Volume Serial Number is 1AA7-F49F

 Directory of C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts

11/10/2020  06:08 PM            74,752 conda.exe
08/07/2020  04:05 AM            74,752 conda.exe.c~.conda_trash
               2 File(s)        149,504 bytes
               0 Dir(s)  38,567,014,400 bytes free

```

**Comment by Sofia-Neira** [comment]
> @asmeurer this might need to be reopened. I suspect there may be some side effect of conda becoming a batch script (conda.bat). One thing that comes to mind with .bat scripts is if you execute one script from another without using the "call" keyword the calling script will immediately exit. Conda.bat is first on the PATH, so chances are it gets invoked from within itself under some circumstances?
> 
> ```
> (dev37) C:\Users\volex>where conda
> C:\Users\volex\AppData\Local\Continuum\anaconda3\condabin\conda.bat
> 
> (dev37) C:\Users\volex>dir C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts\conda.*
>  Volume in drive C is Local Disk
>  Volume Serial Number is 1AA7-F49F
> 
>  Directory of C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts
> 
> 11/10/2020  06:08 PM            74,752 conda.exe
> 08/07/2020  04:05 AM            74,752 conda.exe.c~.conda_trash
>                2 File(s)        149,504 bytes
>                0 Dir(s)  38,567,014,400 bytes free
> ```

I agree with this comment, the issue persists for me and I would like to re-open (I'm new here, maybe I should start a new issue?). 

I try to delete environment, it doesn't show up in list of environments, but I can still activate it so it is definitely there. However, when activating, it says conda.bat activate myenv and then opens the environment. 

Anyone have advice on how I can fully delete this environment?

**Comment by clgarciga** [comment]
> 
> 
> @asmeurer this might need to be reopened. I suspect there may be some side effect of conda becoming a batch script (conda.bat). One thing that comes to mind with .bat scripts is if you execute one script from another without using the "call" keyword the calling script will immediately exit. Conda.bat is first on the PATH, so chances are it gets invoked from within itself under some circumstances?
> 
> ```
> (dev37) C:\Users\volex>where conda
> C:\Users\volex\AppData\Local\Continuum\anaconda3\condabin\conda.bat
> 
> (dev37) C:\Users\volex>dir C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts\conda.*
>  Volume in drive C is Local Disk
>  Volume Serial Number is 1AA7-F49F
> 
>  Directory of C:\Users\volex\AppData\Local\Continuum\anaconda3\Scripts
> 
> 11/10/2020  06:08 PM            74,752 conda.exe
> 08/07/2020  04:05 AM            74,752 conda.exe.c~.conda_trash
>                2 File(s)        149,504 bytes
>                0 Dir(s)  38,567,014,400 bytes free
> ```

I'm having the same issue.

**Comment by 610yilingliu** [comment]
Same issue  on Win10

**Comment by VolkerSiep** [comment]
I have the same issue (Windows 10). The remaining files in the env are exclusively `*.conda_trash` files. All of them are locked by a process and thus I cannot delete them before logging out/in. With my limited rights on this cooperate PC, I don't know how to find the specific process that locks them. There is no obvious candidate (like python or conda) that I can see.

**Comment by 610yilingliu** [comment]
> I have the same issue (Windows 10). The remaining files in the env are exclusively `*.conda_trash` files. All of them are locked by a process and thus I cannot delete them before logging out/in. With my limited rights on this cooperate PC, I don't know how to find the specific process that locks them. There is no obvious candidate (like python or conda) that I can see.

I solve this problem by close all processes related to python & Anaconda. Maybe there are some programs based on Python on your computer are still running?

**Comment by SalmonellaIIB** [comment]
I had the same issue. 
First, you can make sure that all your python processes are not working in your environment. Then you can try to remove the environment.
Second, Remove the environment using: `conda remove -n <env> --all` or `conda env remove --name <env>`
Third, try removing the environment by specifying the complete path: conda env remove -p <complete_path _env>

I am not sure what is the problem with conda, but one of these combinations should work.

**Comment by billcgold** [comment]
having the same issue
conda v4.6.14
windows 10

ran commands
conda remove --name myenv --all
conda info --envs

conda info does not display environment, however environment directory persists.  contents include *.conda_trach.conda_trash and a few subdirectories

**Comment by abhilash-ingale** [comment]
Hi all, 

I was facing the same problem on Win10 running conda 4.10.3. When I tried to delete the envs manually by going into the conda directory (C:/Users/User/miniconda/env) it was unable to delete it because two processes were using it in background (gszerver and Python in my case).

I solved it by looking up these processes in Task Manager and manually killing them.

**Comment by leehaust** [comment]
I had this problem on many environments in Windows 10 and I did this from CMD:
del /s c:\miniconda\envs\<env name>\*.*

After responding Y to all the prompts, I was able to delete the folder with the following command in cmd:
rd c:\miniconda\envs\<env name>

And also with this command in python:
import shutil; shutil.rmtree("c:\\miniconda\\envs\\<env name>")

**Comment by Psp29onetwo** [comment]
**For those who can't find a name or have the same name env for every environment they've created then you need to execute this command to remove the conda env from specific directory**

> conda remove --prefix /path/to/conda-env/ --all

**Comment by excalamus** [comment]
> I solved it by looking up these processes in Task Manager and manually killing them.

On Windows, you must use the Resource Monitor to find what process you need to kill .  

Quoting a response from StackExchange:

```
You can use the Resource Monitor for this which comes built-in with Windows 7, 8, 10 and 11!

    Open Resource Monitor, which can be found
        By searching for Resource Monitor or resmon.exe in the start menu, or
        As a button on the Performance tab in your Task Manager
    Go to the CPU tab
    Use the search field in the Associated Handles section
        See blue arrow in screen shot below

When you've found the handle, you can identify the process by looking at the Image and/or PID column.

You can then try to close the application as you normally would, or, if that's not possible, just right-click the handle 
and kill the process directly from there. Easy peasy!
```

Source: https://superuser.com/a/643312
