### ISSUE TITLE
newer version of pexpect needed for jupyter

### ISSUE THREAD

**Issue by rdhyee** [conda/conda#2010]
After running `conda install jupyter` in an environment with Python 2 and starting `ipython` caused  a`No module named exceptions` exception.  This problem was already reported at [ImportError: No module named exceptions · Issue #9065 · ipython/ipython](https://github.com/ipython/ipython/issues/9065#issuecomment-176909684).  I copy what I [wrote on that thread](https://github.com/ipython/ipython/issues/9065#issuecomment-176909684) as a way of reporting the problem to the `conda` developers:

I just ran into this problem while installing `jupyter` in a new conda env on Mac OS X 10.9.5.  

After doing:
```
conda create -n ipyw-test python=2 pip
. activate ipyw-test
conda install jupyter
```
I got an error running `ipython` because of the missing `exceptions` package.  I used the [suggested fix](https://github.com/ipython/ipython/issues/9065#issuecomment-162163512):

```
conda remove pexpect
conda clean --tarballs --packages
conda install pexpect
```
but then had to add

```
pip install -U pexpect
```

because conda didn't have the correct version of `pexpect`.

**Comment by mforbes** [comment]
Confirmed.  Please update the conda package to pull in the correct version of `pexpect`.

**Comment by mcg1969** [comment]
This needs to be moved over to https://github.com/ContinuumIO/anaconda-issues ... this issue tracker is specifically related to issues with the conda package manager itself.
