### ISSUE TITLE
Conda install doesn't pick up the latest version of a package

### ISSUE THREAD

**Issue by mjuric** [conda/conda#2011]
We're encountering a problem where `conda` doesn't select the most recent available version of a package from a channel. All the dependencies exist on the channel (i.e., when I add the version number to `conda install` line, the install succeeds), and the versions seem to compare correctly (see below). Could this be a solver bug?

Details: I have the following on the channel:

```
[mjuric@lsst-dev ~]$ conda search lsst-sims --full-name
Fetching package metadata: ......
lsst-sims                    master_gac1855abae.0125    ac1855abae_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150626170402.post157    ac1855abae_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150928224422.post8    c2d9827e8b_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150928224422.post46    c2d9827e8b_0  http://research.majuric.org/conda/xxx/linux-64/
```

Testing by comparing `conda.resolve.normalized_version()`-s of all of these confirms that `master.20150928224422.post46` is the highest version:

```
In [1]: from conda.resolve import normalized_version as nv
In [2]: a = nv('master_gac1855abae.0125')
In [3]: b = nv('master.20150626170402.post157')
In [4]: c = nv('master.20150928224422.post8')
In [5]: d = nv('master.20150928224422.post46')

In [6]: a < b, b < c, c < d
Out[6]: (True, True, True)

In [7]: a < c, b < d
Out[7]: (True, True)

In [8]: a < d
Out[8]: True

In [9]: a > b, b > c, c > d
Out[9]: (False, False, False)

In [10]: a > c, b > d
Out[10]: (False, False)

In [11]: a > d
Out[11]: False
```

However, when I run the install, this is what I get (abbreviated output; I've pasted the full output [here](https://gist.github.com/mjuric/b59eedfbf2198c07d78f)):

```
[mjuric@lsst-dev ~/public_html/conda]$ conda --debug install lsst-sims
DEBUG:conda.fetch:channel_urls=('http://research.majuric.org/conda/xxx/linux-64/', 'http://research.majuric.org/conda/xxx/noarch/', 'https://repo.continuum.io/pkgs/free/linux-64/', 'https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pro/linux-64/', 'https://repo.continuum.io/pkgs/pro/noarch/')

...[snip]...

Package plan for installation in environment /ssd/mjuric/projects/lsst_packaging_conda/miniconda:
....
    lsst-sims:                     master.20150626170402.post157-ac1855abae_0
....

Proceed ([y]/n)?
```

. When I specify the version explicitly, it works:

```
[mjuric@lsst-dev ~]$ conda --debug install lsst-sims=master.20150928224422.post46
Fetching package metadata: ......
....
    lsst-sims:                     master.20150928224422.post46-c2d9827e8b_0
...
Proceed ([y]/n)? n
```

(so I don't think it's an issue with missing dependencies).

The channel in question is public -- see http://research.majuric.org/conda/xxx for the channel.
The full outputs of the above commands is at https://gist.github.com/mjuric/b59eedfbf2198c07d78f

PS: Do let me know if there's anything else I can try or provide you with to make debugging easier; happy to help!
PPS: Discussion of this problem begun [on issue 1919](https://github.com/conda/conda/issues/1919#issuecomment-177105531); @mcg1969 advised to open a separate issue, as it's likely this is a different problem.

**Comment by mjuric** [comment]
I have a smaller test case at http://research.majuric.org/conda/yyy channel that reproduces the issue; just two packages, `foo-1.0.0`, `foo-2.0.0` and `bar-1.0.0`. I ran this on fully updated miniconda (i.e., installed a fresh Miniconda, followed by `conda update --all`).

Results:
```
[mjuric@lsst-dev ~]$ conda list
# packages in environment at /ssd/mjuric/delme:
#
conda                     3.19.0                   py27_0
conda-env                 2.4.5                    py27_0
openssl                   1.0.2f                        0
pip                       8.0.1                    py27_0
pycosat                   0.6.1                    py27_0
pycrypto                  2.6.1                    py27_0
python                    2.7.11                        0
pyyaml                    3.11                     py27_1
readline                  6.2                           2
requests                  2.9.1                    py27_0
setuptools                19.4                     py27_0
sqlite                    3.9.2                         0
tk                        8.5.18                        0
wheel                     0.26.0                   py27_1
yaml                      0.1.6                         0
zlib                      1.2.8                         0

[mjuric@lsst-dev ~]$ conda config --get channels
--add channels 'defaults'
--add channels 'http://research.majuric.org/conda/yyy'

[mjuric@lsst-dev ~]$ conda search foo
Fetching package metadata: ......
foo                          1.0.0                    py27_0  http://research.majuric.org/conda/yyy/linux-64/
                             2.0.0                    py27_0  http://research.majuric.org/conda/yyy/linux-64/

[mjuric@lsst-dev ~]$ conda install foo --dry-run
Fetching package metadata: ......
Solving package specifications: ...................
Package plan for installation in environment /ssd/mjuric/delme:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    foo-1.0.0                  |           py27_0          15 KB

The following NEW packages will be INSTALLED:

    foo: 1.0.0-py27_0

Dry run: exiting

[mjuric@lsst-dev ~]$ conda install foo=2.0.0 --dry-run
Fetching package metadata: ......
Solving package specifications: .........................
Package plan for installation in environment /ssd/mjuric/delme:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-1.0            |                0         170 KB
    openblas-0.2.14            |                3         3.5 MB
    numpy-1.9.0                |           py27_0         7.7 MB
    scipy-0.16.0               |       np19py27_1        28.2 MB
    bar-1.0.0                  |           py27_0         626 KB
    foo-2.0.0                  |           py27_0          17 KB
    ------------------------------------------------------------
                                           Total:        40.2 MB

The following NEW packages will be INSTALLED:

    bar:         1.0.0-py27_0
    foo:         2.0.0-py27_0
    libgfortran: 1.0-0
    numpy:       1.9.0-py27_0
    openblas:    0.2.14-3
    scipy:       0.16.0-np19py27_1

Dry run: exiting
```

**Comment by mjuric** [comment]
A further simplified test case for the issue is at http://research.majuric.org/conda/yyy . The repodata is now short enough to be pasted here:
```
{
  "info": {},
  "packages": {
    "foo-1.0.0-py27_0.tar.bz2": {
      "build": "py27_0",
      "build_number": 0,
      "depends": [
      ],
      "md5": "bb379dda06746be7bf5ad5657a6216e9",
      "name": "foo",
      "sig": null,
      "size": 15687,
      "subdir": "linux-64",
      "version": "1.0.0"
    },
    "foo-2.0.0-py27_0.tar.bz2": {
      "build": "py27_0",
      "build_number": 0,
      "depends": [
        "numpy ==1.9",
        "scipy"
      ],
      "md5": "386110864a148efb1557723614de83ce",
      "name": "foo",
      "sig": null,
      "size": 17286,
      "subdir": "linux-64",
      "version": "2.0.0"
    }
  }
}
```

Again:
```
[mjuric@lsst-dev ~]$ conda config --get channels
--add channels 'defaults'
--add channels 'http://research.majuric.org/conda/zzz'

[mjuric@lsst-dev ~]$ conda install foo --dry-run
Fetching package metadata: ......
Solving package specifications: ...................
Package plan for installation in environment /ssd/mjuric/delme:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    foo-1.0.0                  |           py27_0          15 KB

The following NEW packages will be INSTALLED:

    foo: 1.0.0-py27_0

Dry run: exiting
```
Interestingly, if `numpy ==1.9` is changed to `numpy >=1.9` in the dependency list for `foo-2.0.0`, `foo-2.0.0` gets selected. This feels like a solver problem.

**Comment by mcg1969** [comment]
Wait, is NumPy already installed in this case? What if you use the --update-deps flag?

I appreciate the work! In fact we have a solver overhaul PR in progress so I would want to make sure this works.

**Comment by mcg1969** [comment]
Also, what if you change it from `==1.9` to `=1.9`? or `1.9*`?

**Comment by mjuric** [comment]
`numpy` is not installed -- this is a fresh miniconda install (I've pasted the output of `conda list` into [this coment above](https://github.com/conda/conda/issues/2011#issuecomment-177353655]). If I add `--update-deps`, nothing changes either.

If I change `==1.9` to `1.9` or `1.9*`, there's no change (`foo-1.0.0` still gets selected). Using `=1.9` results in an error (`Error: Did not recognize version specification: u'=1.9'`).

Installing `numpy` either `1.9`, or the latest (`1.10.0-py27_0`) also changes nothing (`foo-1.0.0` still gets selected).

**Comment by mjuric** [comment]
Another data point: if I have `numpy ==1.10.2` or `1.10*` as a dependency in `repodata.json`, `foo-2.0.0` gets selected.

**Comment by mcg1969** [comment]
OK, I understand what's going on here. In order to select the best set of packages to install, conda employs a "version metric" that assigns a value to every version of a package. The smaller the value, the more recent the package. So for instance, `foo-1.0.0` gets a metric of `1`, and `foo-2.0.0` gets a metric of `0`. 

However, it currently applies this metric to  _all_ packages, _including dependencies_. If it installs `foo-1.0.0`, the total metric is just `1`, because there are no dependencies. If I install `foo-2.0.0`, the metric is much larger, because it is pulling in other dependencies.

I agree this is suboptimal behavior, but it's not clear the best way to handle it. I think that if both version of the package had the same set of dependencies this wouldn't be an issue.

**Comment by mjuric** [comment]
That's sort of what I was guessing myself, given the observed behavior (not knowing anything about the innards of the dependency solver). Would it be possible to have the solver in effect pin the latest version (perhaps subject to any feature constraints) of the package that was requested to be installed, and then just solve for the rest? As a user, that is what one would expect (at least in the case of installing a single package).

> I agree this is suboptimal behavior, but it's not clear the best way to handle it. I think that if both version of the package had the same set of dependencies this wouldn't be an issue.

Right, but I suspect it's quite common for a package to start off with fewer dependencies and then accumulate more as the development goes on :(.

**Comment by mcg1969** [comment]
What's nice about the new solver (if I do say so myself) is that it becomes easy to define a list of priorities. Currently, the priority is this:

1. Maximize the versions of all packages installed
2. Minimize the number of packages installed

I think if we adjust this to:

1. Maximize the versions of the requested packages
2. Maximize the versions of the _dependencies_
3. Minimize the number of packages installed

then your use case will be covered, because priority 1 will be to pull `foo-2.0.0`.

**Comment by mjuric** [comment]
Agreed, this looks like the right thing to do!

**Comment by kkraus14** [comment]
@mcg1969 @tyler-thetyrant Was this issue closed because the behavior described in the below was implemented? We're working on releasing an updated version of https://anaconda.org/rapidsai/cuml but the conda solver seems to prioritize pulling older versions due to having less dependencies.

> I think if we adjust this to:
> 
> 1. Maximize the versions of the requested packages
> 2. Maximize the versions of the _dependencies_
> 3. Minimize the number of packages installed
> 
> then your use case will be covered, because priority 1 will be to pull `foo-2.0.0`.

**Comment by kalefranz** [comment]
@kkraus14 I suggest filing a new issue with full details on how to reproduce what you’re currently seeing.
