### ISSUE TITLE
Official support for CONDA_FORCE_32BIT

### ISSUE THREAD

**Issue by tadeu** [conda/conda#2014]
We are using this undocumented environment variable in order to support both 32-bit and 64-bit environments in the same machine, with the same installation of `conda`.

It is working really well, with the exception of a few minor (but really annoying) glitches, so I'd like to request this to be moved to "official documented" support.

See also:

https://github.com/conda/conda/issues/1885

**Comment by tadeu** [comment]
@kalefranz, just to check if you have any new comment on this, we would be very happy if you could officially support `CONDA_FORCE_32BIT`, as we are using this on your daily work in order to choose 32-bit or 64-bit environments (and it is working really well, besides a small bug related to this that we would like to have it fixed on mainstream).

**Comment by kalefranz** [comment]
I would switch to using the `CONDA_SUBDIR` environment variable, an specifying `linux-32`/`linux-64` or `win-32`/`win-64`.  You may also want to specify `CONDA_PKGS_DIRS` to use different package caches for the different platforms.

`CONDA_FORCE_32BIT` is still supported, but it's mostly only used for conda-build at this point, and conda-build is switching to configuring subdirs explicitly.
