### ISSUE TITLE
conda-build does not run install_headers command when package uses setuptools

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#2017]
Distutils' command `distutils.command.install_headers` installs C/C++ header files into the Python include directory. The list of these header files is specified with the `headers` keyword argument in `distutils.core.setup`.

However, in the case when the package's setup.py uses setuptools instead of distutils, the headers don't get installed when simply running `python setup.py install`. Still, `pip install` does install the headers.

Since conda-build runs `python setup.py install`, it does not detect the header installation.

The reason why pip detects the headers seems to be that pip runs `python setup.py install` with a flag, that is `--single-version-externally-managed`. Should conda-build use the same flag as pip?

**Comment by SylvainCorlay** [comment]
cc @groutr

**Comment by groutr** [comment]
I think this decision is largely left to the packager to execute the correct commands inside the build scripts (build.sh/bld.bat).  There is a pretty common usage of `--single-version-externally-managed` flag (and its equivalent `--old-and-unmanageable`) in our internal recipes.  Are you suggesting this be the default?

**Comment by SylvainCorlay** [comment]
I think that it is fine including it into the command. Thanks for your response. Closing the issue.
