### ISSUE TITLE
Conda is prioritizing .condarc in user directory, instead of system

### ISSUE THREAD

**Issue by tadeu** [conda/conda#2022]
According to the documentation:

> A .condarc file may also be located in the root environment, in which case it overrides any in the home directory.

But this is not what happens in the code, the priorities are inverted:

https://github.com/conda/conda/blob/63b289304b022c2a5868cf7516a21924ffb029c4/conda/config.py#L102

**Comment by mdengler** [comment]
The implemented behavior seems preferable.

**Comment by mcg1969** [comment]
Agreed. Surely there has to be a way to customize conda behavior on a per-user basis. The behavior in the documentation would prevent that.

**Comment by kalefranz** [comment]
Details on configuration with conda 4.2 and later at 
https://www.continuum.io/blog/developer-blog/conda-configuration-engine-power-users

If docs aren't already updated, the team is working on it and will be done soon.
