### ISSUE TITLE
undefined symbol: mkl_serv_getenv in numexpr

### ISSUE THREAD

**Issue by joshowen** [conda/conda#2031]
We are not using any MKL optimized libraries, but are getting this, where we didn't previously

```
python: symbol lookup error: /app/.heroku/miniconda/envs/heroku-env/lib/python2.7/site-packages/numexpr/../../../libmkl_vml_avx.so: undefined symbol: mkl_serv_getenv 
```

**Comment by ilanschnell** [comment]
This blog post: https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations
Describes how to not use MKL linked versions of packages (on Unix).  Nevertheless, the symbol error indicates that a MKL library is missing in the linkage.  We have to look into that.

**Comment by ozancaglayan** [comment]
So somehow this morning conda brought to me the mkl package and I've hit the same problem. Now I did an update --all and it downgrades some numexpr, numpy, scipy and scikit-learn and installs mkl-rt package. And it's working correctly now.

**Comment by kmdouglass** [comment]
I have also received this error. One of my environments needed PyTables so I performed a `conda install pytables`, which also upgraded a package related to MKL (I can't remember what package specifically; if you could point me towards a relevant log file I can find it.)

After this, I would receive the following error message from a Jupyter Notebook session when performing matrix-heavy operations:

>/home/douglass/anaconda3/envs/homogenizer/bin/python: symbol lookup error: /home/douglass/anaconda3/envs/homogenizer/lib/python3.5/site-packages/numexpr/../../../libmkl_vml_mc3.so: undefined symbol: mkl_serv_getenv

A `conda update -all` in both my root conda environment and my homogenizer environment fixed the problem like @ozancaglayan suggested above.

**Comment by endrebak** [comment]
The previous solution did not work for me. I had to

```
conda install mkl-rt
```

to avoid those errors.

**Comment by kapil0187** [comment]
Same as endrebak for me. I had to reinstall mkl-rt.

**Comment by endrebak** [comment]
I got an `Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so` sometimes after this fix, but using 

```
conda install --yes mkl mkl-service
```

got rid of those too. See https://github.com/ContinuumIO/anaconda-issues/issues/698
