### ISSUE TITLE
MKL automatically installed?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2032]
Appears when installing NumPy it now installs MKL with it automatically. Is this intentional?

**Comment by msarahan** [comment]
yes, blog post here: https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations

You can remove it and go to openblas on Mac and Linux - instructions on the post.

Feedback welcome.

**Comment by jakirkham** [comment]
Ah ok. I tried to look, but somehow must have missed that page in the search results. Thanks for clarifying. So, this doesn't run into some licensing restrictions?

**Comment by jakirkham** [comment]
IANAL so I wouldn't know. Just wanted to make sure.

**Comment by msarahan** [comment]
I think anyone can buy MKL and get redistribution rights.  We used to charge for that, but now it's free (and MKL also has a personal-use free use license now, too).

Closing this issue, but still welcome feedback.

**Comment by jakirkham** [comment]
Cool, thanks for the clarification.

**Comment by egentry** [comment]
Even when I remove MKL, and `conda install nomkl` (and go through the steps on the blog post linked above), it keeps trying to re-install MKL. If I let it install MKL, it leads to a conflict the next time I `conda update --all` due to having both `mkl` and `nomkl` installed (e.g. `pandas` doesn't know whether to use MKL or not)

Is there a good way to stop having it try to install MKL?

**Comment by msarahan** [comment]
Pinging @ilanschnell

**Comment by ilanschnell** [comment]
`pandas` itself does not depend on `mkl`.  What matters is whether or not the `nomkl` meta-package is installed.  If `nomkl` is installed, then the non-MKL versions of `numpy`, `scipy`, etc. are preferred over the MKL linked versions (regardless of what package you install).

**Comment by egentry** [comment]
Ahh, I see. Installing `nomkl` and removing `mkl` was necessary but not sufficient.  I also had to remove `conda remove mkl-service`, otherwise it would try to re-install MKL every time I ran `conda update --all` (leading to a conflict for `numpy`, `scipy`, etc).

After running some tests on my machine, it looks like the instructions on your blog post will work if you change `conda remove mkl` to `conda remove mkl mkl-service`

**Comment by ilanschnell** [comment]
Thanks, @egentry.  That makes sense, I'll make sure that this change concerning `mkl-service` gets added to the post.  I didn't have the `conda update --all` senario in mind.

**Comment by ilanschnell** [comment]
The blog post is updated to say:
```
conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service
```

**Comment by jakirkham** [comment]
@stuarteberg @chaubold, thought you guys might find this interesting.

**Comment by jakirkham** [comment]
So, it appears to still say, "Message: trial mode expires in 29 days", when starting up iPython.

**Comment by bilderbuchi** [comment]
How can I opt-out of mkl on Windows? The trial message appearing by default is annoying (imo this should have been opt-in), but if I do `conda install nomkl` I get 
```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Error: No packages found in current win-64 channels matching: nomkl

Did you mean one of these?

    mkl

You can search for this package on anaconda.org with

    anaconda search -t conda nomkl
```

**Comment by jakirkham** [comment]
Yeah, that is weird. There doesn't appear to be a [`win-64`](https://repo.continuum.io/pkgs/free/win-64/) or [`win-32`](https://repo.continuum.io/pkgs/free/win-32/) package of `nomkl`. Well, from what I can tell, there isn't that much going on in that package so you could roll your own. I have included what I believe is going on in this PR ( https://github.com/conda/conda-recipes/pull/586 ) so you can build it yourself with `conda-build` until it gets added.

**Comment by jakirkham** [comment]
Also, I think I agree with you that `mkl` should be opt-in. In other words, I think `nomkl` should be the default.

**Comment by jakirkham** [comment]
@bilderbuchi, sounds like the answer is no. Windows builds have always been using MKL. There is a possibility for a Windows build that uses OpenBLAS. If you have a working Windows dev environment, we would really appreciate your help. :) Otherwise, honestly, I can't say when this will get done.

**Comment by bilderbuchi** [comment]
>  Windows builds have always been using MKL. 

Really? Why is it, then, that I have only with the most recent anaconda started getting messages about mkl trial versions, and not in the past year(s)? I have never had an MKL license..

**Comment by bilderbuchi** [comment]
btw, I don't want to get away from MKL because of some nag-text, but because of other problems (#2048) that I'm encountering with it, I thought going "back" to a non-MKL env would avoid this problem.

**Comment by msarahan** [comment]
MKL requires a license for redistribution, not for usage.  The messages
about mkl trial versions are growing pains for us.  We used to provide MKL
as a paid add-on with a license required (our license, not MKL's).  Now
it's free, but the transition to not requiring a license hasn't been as
smooth as we hoped.

**Comment by bilderbuchi** [comment]
I see, thanks for the clarification.

**Comment by jakirkham** [comment]
So, is one still required to have an Intel MKL license to use the copy of `mkl` installed via `conda`? Is there some sort of Intel MKL license that is bundled with it? Are packages built with `mkl` in `conda` still constrained by the Intel MKL license? I am still a bit unclear on the licensing point.

**Comment by msarahan** [comment]
We hold the license to MKL that lets us redistribute it.  No additional
license is required for users of Anaconda.  There's probably some gray area
when it comes to third parties redistributing Anaconda that contains MKL.
IANAL.

**Comment by alreadyexists** [comment]
Hello. This thread seems to be an appropriate for this post.
Couldn't find a nomkl version of `gensim`. Everything else seems to be fine with nomkl metapackage. But this one ruins everything:

```
u@e1:~$ conda install gensim
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ..........

Package plan for installation in environment /usr/share/anaconda:

The following NEW packages will be INSTALLED:

    mkl:          11.3.1-0          

The following packages will be UPDATED:

    numexpr:      2.5-np110py27_nomkl_0    [nomkl] --> 2.5-np110py27_0   
    numpy:        1.10.4-py27_nomkl_1      [nomkl] --> 1.10.4-py27_1     
    scikit-learn: 0.17.1-np110py27_nomkl_0 [nomkl] --> 0.17.1-np110py27_0
    scipy:        0.17.0-np110py27_nomkl_2 [nomkl] --> 0.17.0-np110py27_2
```

Any suggestions?

**Comment by ilanschnell** [comment]
The reason there is no 'nomkl' for gensim, is that gensim does not link to
MKL (I'm not sure if it could).
There are only a few packages with the nomkl feature: numpy, scipy,
scikit-learn, numexpr
Most packages don't have a 'nomkl' feature, because they cannot be linked
to MKL, such as: python, pandas, openssl, conda, pycosat, bokeh, pyyaml,
freetype, ... <hundreds more>....

**Comment by alreadyexists** [comment]
Sure, gensim pulling mkl, that looks pretty odd. How do I prevent it?

**Comment by ilanschnell** [comment]
Well, the reason it is pulling in mkl is because of numpy (which is a
gensim dependency).

**Comment by alreadyexists** [comment]
Okay, added `--no-deps` switch, seems to work so far. Thanks.

**Comment by gciccarelli3** [comment]
How does the new license interact with clusters?  Is mkl still limited to 4 nodes?
https://www.continuum.io/anaconda-academic-subscriptions
