### ISSUE TITLE
conda config --force --remove channels <channel url> yields invalid .condarc

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2039]
Indentation is not preserved by --remove.  This leaves an invalid condarc.

Before removing channel:

```
channels:
  - http://conda.anaconda.org/community
  - defaults
```

After:
```
channels:
- defaults
```

**Comment by kalefranz** [comment]
I'm hopeful this is fixed in master now with the use of ruamel_yaml. Will confirm before release though.

**Comment by kalefranz** [comment]
I've manually tested `conda config` and it looks to be working as expected as long as `ruamel_yaml` is installed.  `--force` is also a no-op now I think.
