### ISSUE TITLE
503 error when creating conda environment

### ISSUE THREAD

**Issue by desilinguist** [conda/conda#2040]
Running
```
 conda create -p /tmp/foobar python=3.4
```
on my mac gives me:

```
Fetching package metadata: ..Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/noarch/
```

**Comment by mcg1969** [comment]
I think that was a temporary server-side error that should pass in time (if not already).

**Comment by jakirkham** [comment]
Have you tried again @desilinguist.

**Comment by desilinguist** [comment]
Yes, it works now. Thanks!

**Comment by jakirkham** [comment]
Could you please closing this then?

**Comment by jakirkham** [comment]
Thanks.

**Comment by ssbarnea** [comment]
Can we reopen this? Today it seems to be mostly down.

**Comment by jim-kukla** [comment]
@ssbarnea It _just_ started working for me in the last few minutes, so that may be resolved.

**Comment by kalefranz** [comment]
Our sysadmins are aware of 500 errors from repo.continuum.io.  They're working hard on a solution now.

**Comment by ssbarnea** [comment]
Thanks for letting us know. I observed that the errors are intermittent which makes me think that it may be one server of many which is messed and not all. Or maybe is just one that is running out of memory trying to generate or parse a huge json file.
