### ISSUE TITLE
python segfault after updating conda

### ISSUE THREAD

**Issue by jayvius** [conda/conda#2042]
Attempted to install cython in Python 3.5 environment. Got error message described in issue #2041. Deactivated current environment and did a 'conda update conda' to make sure I had the latest version of conda. After updating to conda version 3.19.1, python segfaults no matter what script is run (even just attempting to open a python shell results in a segault). Stack trace and 'conda update conda' output below:

**Stack trace**
Process 37889 launched: '/Users/jayvius/anaconda/bin/python' (x86_64)
Process 37889 stopped
* thread #1: tid = 0x366f02, 0x00007fff5fc26de8 dyld`__munmap + 20, stop reason = EXC_BAD_ACCESS (code=1, address=0x7fff5bffed08)
    frame #0: 0x00007fff5fc26de8 dyld`__munmap + 20
dyld`__munmap:
->  0x7fff5fc26de8 <+20>: retq   
    0x7fff5fc26de9 <+21>: nop    
    0x7fff5fc26dea <+22>: nop    
    0x7fff5fc26deb <+23>: nop    

**conda update conda**
Fetching package metadata: ......
Solving package specifications: ......................
Warning: 2 possible package resolutions (only showing differing packages):
	['openssl-1.0.2f-0.tar.bz2', 'python-3.5.0-conda_build_0.tar.bz2'],
	['openssl-1.0.2d-0.tar.bz2', 'python-3.5.1-0.tar.bz2'],

Package plan for installation in environment /Users/jayvius/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.29.0               |           py35_0          82 KB
    conda-3.19.1               |           py35_0         180 KB
    ------------------------------------------------------------
                                           Total:         261 KB

The following packages will be UPDATED:

    conda:      3.19.0-py35_0 --> 3.19.1-py35_0      
    openssl:    1.0.2e-0      --> 1.0.2f-0           
    pip:        8.0.1-py35_0  --> 8.0.2-py35_0       
    setuptools: 19.4-py35_0   --> 19.6.2-py35_0      
    wheel:      0.26.0-py35_1 --> 0.29.0-py35_0      

The following packages will be DOWNGRADED:

    python:     3.5.1-0       --> 3.5.0-conda_build_0

Proceed ([y]/n)? 

Fetching packages ...
wheel-0.29.0-p 100% |############################################################################################################################################################| Time: 0:00:00 614.45 kB/s
conda-3.19.1-p 100% |############################################################################################################################################################| Time: 0:00:00 821.67 kB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%

**Comment by jayvius** [comment]
Forgot to mention that this is on OS X 10.10.5. Also, downloading and installing anaconda3-2.5.0 immediately produces the same situation after creating a python 3.5 environment, but python 3.4 environments work fine.

**Comment by msarahan** [comment]
Closing.  Issue was the conda_build_0 package causing segfaults.  That package came from the asmeurer channel, which was present in .condarc.  Investigating version number prioritization.
