### ISSUE TITLE
`conda search` needs overhaul

### ISSUE THREAD

**Issue by pitrou** [conda/conda#2046]
Currently `conda search` isn't very helpful as it:
- can list of ton of irrelevant versions (e.g. too old)
- can list all different build types (platforms, Python versions...)
- doesn't given any package information

I suggest to study what e.g. `apt-cache search` does (or the equivalent `yum` commands) and try to give something equally useful:
- shows the latest version
- perhaps shows the installed version
- gives useful meta-information (optionally or by default), such as package description, dependencies, size, etc.

**Comment by tyler-thetyrant** [comment]
Closing since #5597
