### ISSUE TITLE
Abort if not tty ?

### ISSUE THREAD

**Issue by Carreau** [conda/conda#2047]
long story short, in a Notebook, using the IPython kernel.

```
!conda unpgrade whatever
...
Proceed ([y]/n)?
```

And then... you need to interrupt kernel to send a KeyboardInterrupt, which is far from intuitive for many users. 
Could it be possible  if not tty or not interactive or any other sensible condition to fail/exit and print that user should use `-y` ? The point being to not leave the kernel blocked regardless of the solution.

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1124

**Comment by Carreau** [comment]
> #1124

Thanks ! I  think the progress might be  important, it's more the prompt-user behavior which is problematic.
