### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2048]
Seeing this on Travis CI (Linux) and in Docker containers during install. ( https://travis-ci.org/jakirkham/nanshe/builds/108187039#L749 )

**Comment by bilderbuchi** [comment]
I just encountered a similar one: `Intel MKL FATAL ERROR: Cannot load mkl_avx.dll or mkl_def.dll.
`

**Comment by msarahan** [comment]
Pinging @ilanschnell

**Comment by bilderbuchi** [comment]
[Here](https://github.com/astropy/ci-helpers/pull/67#issue-132452942) is another instance of this error, apparently. It provides a repro procedure (which doesn't repro on my side, though), and hints that maybe scipy 0.17 is the culprit, and downgrading to 0.15 could circumvent it?

**Comment by jakirkham** [comment]
FWIW, this problem does not occur on Mac. So, it is only Linux and Windows.

**Comment by jakirkham** [comment]
It appears like the libraries are in the packages.

@bilderbuchi, are using Windows natively or are using it in a VM? If the latter what are you using for virtualization? If the former, do you know what architecture you have?

**Comment by bilderbuchi** [comment]
natively, 64bit, Windows 8.1.

**Comment by desilinguist** [comment]
Yes, I am having the same issue on my RHEL box. Works fine on my Mac. Seems like `scipy` is the culprit but all the paths seem so the set correctly when I run `show_config()`.

**Comment by jakirkham** [comment]
Sorry, by architecture, @bilderbuchi, I was meaning what kind of processor are you using.

**Comment by bilderbuchi** [comment]
An Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz

**Comment by kalefranz** [comment]
Does this issue still exist?  Regardless, going to kick it over to anaconda-issues.  Pretty sure it's packaging-related.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#698
