### ISSUE TITLE
mkl and nomkl installed at the same time

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2049]
Happens in a few cases. One case ends up being the testing phase of `python setup.py bdist_conda` when `nomkl` is required and `mkl` is not required by anything. ( https://travis-ci.org/jakirkham/nanshe#L686-L689 )

**Comment by desilinguist** [comment]
This seems very similar to #2064.

**Comment by kalefranz** [comment]
@jakirkham What is the status of this with the new `4.0.4` release?

**Comment by jakirkham** [comment]
From what I can tell this seems to behaving correctly now. I will close this, but will reopen if I see any more issues.
