### ISSUE TITLE
install datashader on Windows-64

### ISSUE THREAD

**Issue by dr-glenn** [conda/conda#2058]
I want to install **datashader **package for use with Bokeh. Suggested command:
**conda install -c bokeh datashader**
Will not work for Windows, so I do a **conda search** and find that the package is available as _ahmadia/datashader_. This install fails because ot requires **odo >=0.4.1**.
I manage to install a newer **odo **- now I'm at 0.4.2. 
But **conda install -c ahmadia datashader **continues to fail, complaining that odo is not correct version. Here's the relevant output. Does anyone know what I need to do?

[Anaconda2] C:\Users\gnelson\Documents\Work\Ensemble\software>conda install -c ahmadia datashader
Fetching package metadata: ......
Solving package specifications: ........
Error: Could not find some dependencies for datashader: odo >=0.4.1

Did you mean one of these?

    datashader, datashape

You can search for this package on anaconda.org with

    anaconda search -t conda odo >=0.4.1

 (and similarly for the other packages)

[Anaconda2] C:\Users\gnelson\Documents\Work\Ensemble\software>python
Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import odo
>>> print odo.__version__
0.4.2
>>>

**Comment by ahmadia** [comment]
Heh, the `ahmadia` channel wasn't publicly advertised.  Can you try:

`conda install -c bokeh datashader` 

again?  We just uploaded the dependencies for Windows.

**Comment by ahmadia** [comment]
Also, in the future, you can report these issues directly to https://github.com/bokeh/datashader
