### ISSUE TITLE
conda install python=3.5 leaves environment broken

### ISSUE THREAD

**Issue by amueller** [conda/conda#2065]
I wanted to upgrade my conda installation from Python 3.4 to 3.5. I used `conda install python=3.5` as suggested [in the docs](http://conda.pydata.org/docs/py2or3.html).

When doing `conda install python=3.5` in a 3.4 environment, this only updates python and some core packages, but not all packages. That means that most packages will still be in the 3.4 version and not found. Running `ipython` for example will tell you there is no `IPython` module - because the file in the `bin` folder still exists, but the module is not installed in the 3.5 module path.

I think the expected behavior of `conda install python=3.5` is that all python packages are updated to their 3.5 version.
What I did now is `conda update anaconda` which will update at least the anaconda packages. I probably still have some 3.4 packages in my 3.5 environment now, though.

**Comment by asmeurer** [comment]
The docs are wrong. You need to do `conda update --all python=3.5` to update to Python 3.5.

**Comment by amueller** [comment]
Thanks :) (obv fixing the docs would be nice ;)
