### ISSUE TITLE
wrong dependency resolution for numpy 1.9.3

### ISSUE THREAD

**Issue by zym1010** [conda/conda#2068]
I have no idea why installing numpy 1.9.3 would require MKL by `conda`. 
I ran `~/miniconda/bin/conda create --name stimulus_generation  numpy=1.9.3` and got the following.

```
Fetching package metadata: ....
Solving package specifications: ..............
Package plan for installation in environment /Users/yimengzh/miniconda/envs/stimulus_generation:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.1                 |                0        99.1 MB
    numpy-1.9.3                |           py27_1         2.9 MB
    ------------------------------------------------------------
                                           Total:       102.0 MB

The following NEW packages will be INSTALLED:

    mkl:        11.3.1-0
    numpy:      1.9.3-py27_1
    openssl:    1.0.2f-0
    pip:        8.0.2-py27_0
    python:     2.7.11-0
    readline:   6.2-2
    setuptools: 19.6.2-py27_0
    sqlite:     3.9.2-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0

Proceed ([y]/n)?
```

If I tried numpy==1.9.2, then the problem disappears. Also, adding `nomkl` doesn't work. I'm not sure why `mkl` is added at all since I downloaded the package for numpy 1.9.3 and found `mkl` is not required at all by it. Instead, by `/info/requires` and `/info/index.json`, it depends on `openblas`, which is not installed at all in this case.

**Comment by desilinguist** [comment]
`mkl` is now the default backend for `numpy` and `scipy` packages. Try adding the `nomkl` package to the list of packages you are installing.

**Comment by zym1010** [comment]
@desilinguist as I said in the original post, it didn't work.
This is the result with using `nomkl`. `mkl` will be installed as well.

```
yimengzh_everyday@leelabgpu:~$ ~/miniconda2/bin/conda create --name stimulus_generation numpy=1.9.3 nomkl
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment /home/yimengzh_everyday/miniconda2/envs/stimulus_generation:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.1                 |                0       121.2 MB
    nomkl-1.0                  |                0          402 B
    openssl-1.0.2f             |                0         3.2 MB
    sqlite-3.9.2               |                0         3.9 MB
    numpy-1.9.3                |           py27_1         5.7 MB
    setuptools-19.6.2          |           py27_0         365 KB
    wheel-0.29.0               |           py27_0          81 KB
    pip-8.0.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:       135.9 MB

The following NEW packages will be INSTALLED:

    mkl:        11.3.1-0
    nomkl:      1.0-0
    numpy:      1.9.3-py27_1
    openssl:    1.0.2f-0
    pip:        8.0.2-py27_0
    python:     2.7.11-0
    readline:   6.2-2
    setuptools: 19.6.2-py27_0
    sqlite:     3.9.2-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0

Proceed ([y]/n)?
```

**Comment by desilinguist** [comment]
Yup, that definitely seems broken.

**Comment by zym1010** [comment]
seems that now this is fixed?

**Comment by jakirkham** [comment]
Is it fixed? If not, as a workaround you could create an environment with `nomkl` first (no `numpy`) then install `numpy` and friends afterwards. This seemed to be a good workaround for `conda` version that saw this problem previously.

**Comment by prj-** [comment]
@jakirkham, no, I don't think it is fixed, cf. this Travis [log](https://travis-ci.org/hpddm/hpddm/jobs/117117518#L511).

**Comment by jakirkham** [comment]
@mcg1969, I think this is worth look into. There appear to still be recent problems (using the latest `conda` of `mkl`/`nomkl` being installed at the same time).

@prj- as a workaround could you add `conda remove --force mkl` immediately after that install step. Then let me know what occurs from there.

**Comment by prj-** [comment]
This will remove `mkl` but not replace `numpy-1.10.4-py27_1` by `numpy-1.10.4-py27_nomkl_1` (at least that's what happened on my machine).

**Comment by jakirkham** [comment]
Could you then try breaking out the numpy and scipy installs into a separate step afterwards?

**Comment by prj-** [comment]
I've fixed my problem by just installing `scipy` instead of `numpy` + `scipy`. It turns out that `scipy` picks up the correct dependency, i.e. `numpy` with `nomkl`, so I think there is definitely something wrong with either `conda` or `numpy`. Thank you @jakirkham.

**Comment by jakirkham** [comment]
> I've fixed my problem by just installing `scipy` instead of `numpy` + `scipy`.

Strange. Definitely something is going on with the solver here. @mcg1969 may know what is going on here. Glad you have an effective workaround.

**Comment by mcg1969** [comment]
What version of `conda` are you running? With the latest version of `conda` I am seeing the correct behavior all around:

1) With `conda create -n test numpy=1.9.3` it does pick up `mkl`---which is correct. The latest build of `numpy 1.9.3` does indeed depend on `mkl` by default; Continuum is now allowed to distribute `mkl` to all customers _and_ to enable those customers to in turn redistribute MKL.
2) With `conda create -n test numpy=1.9.3 nomkl`, the `mkl` package is not installed.

**Comment by jakirkham** [comment]
It was 4.0.5 in the [log]( https://travis-ci.org/hpddm/hpddm/jobs/117117518#L459 ).

**Comment by mcg1969** [comment]
OK, that's a different recipe than I'm seeing here.

**Comment by mcg1969** [comment]
Hmm, `conda create -n test1 python=2.7 nomkl numpy scipy` is picking up both the `nomkl` versions of `numpy` and `scipy` for me. I guess we don't have `libgfortran` in the default channel for OSX.

**Comment by jakirkham** [comment]
Now that I am thinking about it I think it is the `libgfortran` that is throwing it all off. Though there have been reports of linking errors so I believe the user is trying to install the old version to avoid some of these issues. May be a package issue and not a solver issue in the end. Sorry if I was wrong in my reading of the situation.

**Comment by mcg1969** [comment]
Why would libgfortran throw it off? It doesn't do anything with features, does it?

**Comment by jakirkham** [comment]
Yeah, I think it got packaged with `openblas` as it needs `libgfortran`. Really, I think it should have been linked against the `libgcc` package, which there is at least an open source copy of the recipe for.

**Comment by jakirkham** [comment]
Because the user is pinning it to version `1.0`, which was before the `mkl` release IIRC.

**Comment by jakirkham** [comment]
The version I believe was corrected to match what it actually should be, which is `3.0`. However, there are still some packages that require the old version so it is kind of a mess.

**Comment by mcg1969** [comment]
OK, I'm confused. I thought the issue was that `numpy` wasn't picking up the `nomkl` feature. I don't see why pinning `libgfortran` could be the cause of that. It's still picking up the right version of `openblas`, which is the direct dependency the `nomkl` version of `numpy` needs, right?

**Comment by mcg1969** [comment]
Nevermind, I see it. `numpy-1.10.4-py27_nomkl_1.tar.bz2` *does* have a direct dependency on `libgfortran 3.0`.

**Comment by mcg1969** [comment]
Damn this solver is good.

**Comment by mcg1969** [comment]
OK. So @zym1010 or @prj: the problem is that you have `libgfortran` pinned to version 1.0. The `nomkl` version of `numpy 1.10.4` requires version 3.0 of `libgfortran`. Since you're preventing that version from being installed, it has no choice but to pull in a different build of `numpy 1.10.4`, which in this case happens to be the MKL version.

**Comment by mcg1969** [comment]
And @jakirkham, I never mind you cc:-ing me on a potential solver-related issue, even if it turns out not to be the solver's fault. Thank you!

**Comment by jakirkham** [comment]
@prj-, could you please elaborate as to why you need to pin to `libgfortran` 1.0? It would be nice to understand if there is a packaging issue you are running into here so someone can try to correct it.

**Comment by prj-** [comment]
@jakirkham @mcg1969, thanks for your insights. This is somehow going off topic but if you are willing to cary on, I need to pin to `libgfortran` 1.0 because of another library, cf. this Travis [failed build](https://travis-ci.org/hpddm/hpddm/jobs/114113348#L619). Maybe there is a better workaround, or maybe I should just switch to the Trusty beta of Travis (to have newer Aptitude packages that would work with `libgfortran.so.3`) :smile:

**Comment by mcg1969** [comment]
I'm afraid I can't help with that one.
