### ISSUE TITLE
conda create fails

### ISSUE THREAD

**Issue by Prooffreader** [conda/conda#2070]
When I run the command `conda create -n h2o anaconda python=2.7`

There is the following error:

```
AssertionError: qt-4.8.7-vc10_5.tar.bz2 MatchSpec('openssl 1.0.2*')
```

Current conda install:

```
         platform : win-64
    conda version : 3.14.1
```

  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\e74281.condarc
    is foreign system : False

**Comment by jakirkham** [comment]
Could you please update `conda`? It appears that you are using a fairly old version.
