### ISSUE TITLE
WindowsError: [Error 5] : 'C:\\Anaconda2\\conda-meta\\menuinst-1.3.1-py27_0.json'

### ISSUE THREAD

**Issue by Solin1292** [conda/conda#2074]
C:\Users\alkor> conda install --no-update-deps -c https://conda.binstar.org/simpleitk SimpleITK
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment C:\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.11              |                2        23.2 MB  defaults
    menuinst-1.3.2             |           py27_0          96 KB  defaults
    requests-2.9.1             |           py27_0         612 KB  defaults
    setuptools-19.6.2          |           py27_0         671 KB  defaults
    simpleitk-0.9.1            |           py27_0        16.6 MB  https://conda.binstar.org/simpleitk/win-64/
    wheel-0.29.0               |           py27_0         121 KB  defaults
    conda-3.19.1               |           py27_0         220 KB  defaults
    pip-8.0.2                  |           py27_0         1.5 MB  defaults
    ------------------------------------------------------------
                                           Total:        42.9 MB

The following NEW packages will be INSTALLED:

    simpleitk:  0.9.1-py27_0  https://conda.binstar.org/simpleitk/win-64/

The following packages will be UPDATED:

    conda:      3.18.8-py27_0 defaults --> 3.19.1-py27_0 defaults
    menuinst:   1.3.1-py27_0  defaults --> 1.3.2-py27_0  defaults
    pip:        7.1.2-py27_0  defaults --> 8.0.2-py27_0  defaults
    python:     2.7.11-0      defaults --> 2.7.11-2      defaults
    requests:   2.8.1-py27_0  defaults --> 2.9.1-py27_0  defaults
    setuptools: 18.5-py27_0   defaults --> 19.6.2-py27_0 defaults
    wheel:      0.26.0-py27_1 defaults --> 0.29.0-py27_0 defaults

Proceed ([y]/n)? y

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 713, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] : 'C:\\Anaconda2\\conda-meta\\menuinst-1.3.1-py27_0.json'

C:\Users\alkor>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Users\alkor>

**Comment by msarahan** [comment]
Conda appears to be failing to remove an older menuinst version.  I don't
know why. Did you manually delete the menuinst folder?  If not, is this a
system wide install? This may be a permission issue.

**Comment by Solin1292** [comment]
thanks. it was a permission issue. I have add current user to list of owners of this file. trouble is solved.
