### ISSUE TITLE
Conda breaks py.test package discovery

### ISSUE THREAD

**Issue by bjodah** [conda/conda#2075]
Hi alll, this has been troubling me for a while:

Using `py.test --pyargs mypackage` under a `conda` environment seems to be broken
(last command in [this Dockerfile](https://github.com/bjodah/dummypkg/blob/master/revised-docker-environment/Dockerfile) fails).
I went ahead and made a minimally reproducible example here:

https://github.com/bjodah/dummypkg

`pytest` is from the defaults channel (i.e. ContinuumIO's default channel).
I only experience the bug when using pytest in a conda environment but perhaps the problem is still with `py.test`?

Has anyone else come across this issue? (googling showed at least this: https://anaconda.org/blaze/into/builds/87/15#L192)

**Comment by groutr** [comment]
Interesting issue.  I think there might be an issue with the packages you have created.  Using the package that you created (from your channel), I get the same error as you.

However when I clone your repo and make the package myself, the tests pass (on both linux-64 and osx)

**Comment by bjodah** [comment]
@groutr interesting. What os are you running? I created a Dockerfile based on the [miniconda image](https://hub.docker.com/r/continuumio/miniconda/), and there I can reproduce my error:

```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM continuumio/miniconda:3.19.0
 ---> bc9d0fb804ac
Step 1 : MAINTAINER Björn Dahlgren <bjodah@DELETEMEgmail.com>
 ---> Using cache
 ---> f81cd6785b68
Step 2 : ENV PATH /opt/miniconda2/bin:$PATH
 ---> Using cache
 ---> 3227b31b6bd9
Step 3 : RUN git clone https://github.com/bjodah/dummypkg.git &&     cd dummypkg &&     conda install conda-build  &&     conda build conda-recipe &&     conda create -c bjodah -n dummy2 python=2.7 dummypkg pytest
 ---> Using cache
 ---> 3ede56d6340e
Step 4 : RUN bash -c "cd /tmp; source activate dummy2 && python -c 'import dummypkg; print(dummypkg.__file__)' && python -m pytest --pyargs dummypkg"
 ---> Running in 9dd52c86c4b2
discarding /opt/conda/bin from PATH
prepending /opt/conda/envs/dummy2/bin to PATH
/opt/conda/envs/dummy2/lib/python2.7/site-packages/dummypkg-0.1.0-py2.7.egg/dummypkg/__init__.pyc
============================= test session starts ==============================
platform linux2 -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /tmp, inifile: 

========================= no tests ran in 0.00 seconds =========================
ERROR: file or package not found: dummypkg
INFO[0000] The command [/bin/sh -c bash -c "cd /tmp; source activate dummy2 && python -c 'import dummypkg; print(dummypkg.__file__)' && python -m pytest --pyargs dummypkg"] returned a non-zero code: 4 
```

here's the Dockerfile:
https://github.com/bjodah/dummypkg/tree/master/docker-environment

**Comment by groutr** [comment]
I tested it on both OSX and Ubuntu 64bit.

**Comment by kalefranz** [comment]
@groutr, @bjodah's Dockerfile runs `conda-build`, but then installs `dummypkg` from https://conda.anaconda.org/bjodah.  Can you reproduce the error using the py27 or py34 files at https://anaconda.org/bjodah/dummypkg/files?

**Comment by bjodah** [comment]
@groutr @kalefranz 
Using my private channel was an oversight by me, here is an updated Dockerfile (same error):
https://github.com/bjodah/dummypkg/tree/master/revised-docker-environment

**Comment by bjodah** [comment]
So this issue turns out to be related to python setup.py install being different from `pip install ...` (which conda uses I presume?). See https://github.com/pytest-dev/pytest/issues/1445 for solving the issue. Thank you for your help and sorry about it not really being a conda issue.
