### ISSUE TITLE
Make .condarc files more visible and easy to use

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2090]
The default `.condarc` files are actually "no .condarc file exists, so fall back to default behavior."  As a user, I want to easily know what all of my available options are within a `.condarc` file.  The file should always be present, in the root conda env, in any user's home directory who has ever invoked the conda command, and anywhere else.  When conda looks for a `.condarc` file that doesn't exist, it should populate that location with the "default" file.  And that file should be in similar spirit to what e.g. elasticsearch does

https://gist.github.com/zsprackett/8546403#file-elasticsearch-yml

**Comment by groutr** [comment]
We'd have to be careful with the comments until we get the roundtrip parser in place.  A `conda config` would wipe out all the helpful comments.

**Comment by kalefranz** [comment]
Ohhhh right. Good point @groutr

**Comment by jakirkham** [comment]
So, given @groutr's point would this just be an empty file or just one with the `defaults` channel added? That seems harmless. At least having it show up in the standard places is probably a good idea.

**Comment by joelhullcio** [comment]
May I also request an enhancement to where conda looks for the .condarc file.  During development and testing, especially within enterprises, I often need to vary the .condarc values based on what directory I am in (what dev I am doing or tests I am running).  It would be better if conda would support an env var for the location of the .condarc file and also look in the current directory, then look in the usual places that it looks now.  The ability to override the default .condarc or the $HOME/.condarc file with a .condarc in the current directory allows for various conda configurations.

**Comment by jakirkham** [comment]
Interesting, though for that use case I think an explicit flag would be better than an env var. Would that not work? Probably should be a new issue.

**Comment by joelhullcio** [comment]
A flag would work but might not be as convenient.  If I knew conda would check the current directory first then I don't have to vary the conda command I use I only have to change directories.

**Comment by jakirkham** [comment]
That was the other thought I had in mind.

**Comment by kalefranz** [comment]
Basically done with the new config engine in 4.2.
