### ISSUE TITLE
conda create --copy with --clone does not copy, it creates symlinks

### ISSUE THREAD

**Issue by rcthomas** [conda/conda#2091]
I would like to be able to clone an environment but would like the contents copied instead of symlinked.  I thought combining --clone and --copy would work but my new environment is full of symlinks.  Is there a way to do this?

**Comment by kalefranz** [comment]
Have you tried just using `--clone` alone without `--copy`?  I don't think you'll get an environment full of symlinks that way. I don't think...

**Comment by rcthomas** [comment]
Yes, that didn't work and was why I thought --copy might work.  Here is an example.  First I create a new environment with one package in it.  Then I create a new one with --clone.

    rthomas@cori11:~> conda create --yes --copy -p $HOME/env1 yaml
    Fetching package metadata: ....
    Solving package specifications: ....
    Package plan for installation in environment /global/homes/r/rthomas/env1:

    The following NEW packages will be INSTALLED:

        yaml: 0.1.6-0 defaults (copy)

    Linking packages ...
    [      COMPLETE   ]|###################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate /global/homes/r/rthomas/env1
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    rthomas@cori11:~> ls -lat env1/lib/
    total 976
    drwxr-x--- 6 rthomas rthomas    512 Mar 16 16:36 ..
    drwxr-x--- 2 rthomas rthomas    512 Mar 16 16:36 pkgconfig
    -rwxrwxr-x 1 rthomas rthomas    963 Mar 16 16:36 libyaml.la
    drwxr-x--- 3 rthomas rthomas    512 Mar 16 16:36 .
    lrwxrwxrwx 1 rthomas rthomas     18 Mar 16 16:36 libyaml.so -> libyaml-0.so.2.0.4
    lrwxrwxrwx 1 rthomas rthomas     18 Mar 16 16:36 libyaml-0.so.2 -> libyaml-0.so.2.0.4
    -rwxrwxr-x 1 rthomas rthomas 389426 Jun 19  2015 libyaml-0.so.2.0.4
    -rw-rw-r-- 1 rthomas rthomas 599528 Jun 19  2015 libyaml.a

Then the clone attempt:

    rthomas@cori11:~> conda create --yes --clone $HOME/env1 -p $HOME/env2
    Fetching package metadata: ....
    src_prefix: '/global/homes/r/rthomas/env1'
    dst_prefix: '/global/homes/r/rthomas/env2'
    Packages: 1
    Files: 0
    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate /global/homes/r/rthomas/env2
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    rthomas@cori11:~> ls -la env2/lib
    total 0
    drwxr-x--- 3 rthomas rthomas 512 Mar 16 16:37 .
    drwxr-x--- 5 rthomas rthomas 512 Mar 16 16:37 ..
    lrwxrwxrwx 1 rthomas rthomas  18 Mar 16 16:37 libyaml-0.so.2 -> libyaml-0.so.2.0.4
    lrwxrwxrwx 1 rthomas rthomas  81 Mar 16 16:37 libyaml-0.so.2.0.4 -> /usr/common/software/python/2.7-anaconda/pkgs/yaml-0.1.6-0/lib/libyaml-0.so.2.0.4
    lrwxrwxrwx 1 rthomas rthomas  72 Mar 16 16:37 libyaml.a -> /usr/common/software/python/2.7-anaconda/pkgs/yaml-0.1.6-0/lib/libyaml.a
    -rwxrwxr-x 1 rthomas rthomas 964 Mar 16 16:37 libyaml.la
    lrwxrwxrwx 1 rthomas rthomas  18 Mar 16 16:37 libyaml.so -> libyaml-0.so.2.0.4
    drwxr-x--- 2 rthomas rthomas 512 Mar 16 16:37 pkgconfig

**Comment by kalefranz** [comment]
Is this still a problem with conda 4.3?  Latest is conda 4.3.17.
