### ISSUE TITLE
Enhance update --all with new solver

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2092]

**Comment by mcg1969** [comment]
So what do you mean by "enhance" here? It should take less than 30 minutes? ;-) If so, I'm done...

**Comment by kalefranz** [comment]
Ha! I *actually* mean make `update --all` act and behave perfectly in all situations.  Just how users intuitively expect. Always. Should be nbd for you... :-p

**Comment by kalefranz** [comment]
Oh, and with 100% coverage and limited cyclomatic complexity. Still nbd :)
