### ISSUE TITLE
Proxy errors that aren't caused by a proxy

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2095]
From a customer:

> conda wrongly reports that the proxy is not set when it can't reach a channel.
> 
> Reason of the problem is actually that the proxy expects requests to be routed to the internet. There is no route from the proxy to the lab's LAN. Therefore conda cannot reach the anaconda server within the lab’s LAN.
> 
> The workaround has been to add a NO_PROXY environment variable and exclude the lab's network domain. IP ranges does not seems to be accepted.
> 
> However it would have been easier to understand what the problem is if errors were reported more accurately

**Comment by kalefranz** [comment]
> conda wrongly reports that the proxy is not set when it can't reach a channel.

To take action on this, I'd need the exact stack trace or output that conda gives.  Also `conda info`.
