### ISSUE TITLE
Make MKL optional

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2097]
It seems MKL wants to always install itself by default. This causes problems when building recipes that try to link against another BLAS (e.g. OpenBLAS). So, these now have to be designed to somehow keep MKL out, as well. This unfortunately is not simple and often requires ugly hacks that break in different ways. Instead it seem it would be simpler to just prefer the `nomkl` variant of packages by default unless `mkl` is explicitly requested.

**Comment by rcalsaverini** [comment]
I'm having a similar problem were I remove mkl and it keeps installing itself back when I update my packages.

It seems that my environment is considering the mkl version of the packages to be the latest versions and always installing them instead of the non-mkl version.

**Comment by jhoblitt** [comment]
I ran into an issue with `mkl` symbols colliding with other software linked against blas.  If you install the `nomkl` package and then manually re-install any packages that depend on `mkl` and the `mkl` package itself, it doesn't come back.  If you uninstall `nomkl`, `mkl` is re-installed automatically.  For new installs, we are specifing the pedantic package name as the no mkl version and installing `nomkl`.

**Comment by jseabold** [comment]
We ran into some issues around this switch too. How do you install openblas-linked numpy now? It's not clear to me. Trying to install the nomkl builds to check seem to fail for me with "unsatisfiable dependencies."

Maybe we should move this to conda-recipes given the mailing list discussion today?

**Comment by kalefranz** [comment]
@ilanschnell

**Comment by jhoblitt** [comment]
@jseabold E.g. https://github.com/lsst/lsstsw/blob/232cacf73593f910f9af277fa1f0ed1231784596/etc/conda_packages.txt#L17

**Comment by jseabold** [comment]
Yeah, that's what I figured. It was just unclear that nomkl == openblas, and

```
|10160 $ conda install numpy=1.10.4=py35_nomkl_0
Fetching package metadata: ....
Solving package specifications: ......
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|############################################################| 100%


Hint: 'numpy' has unsatisfiable dependencies (see 'conda info numpy')
```

**Comment by kalefranz** [comment]
The package is there for unix.
http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.4-py35_nomkl_0.tar.bz2
http://repo.continuum.io/pkgs/free/osx-64/numpy-1.10.4-py35_nomkl_0.tar.bz2

@ilanschnell Can you discuss here the mkl history on Windows?

**Comment by ilanschnell** [comment]
On Windows, we have always been linking against MKL.  However, with the Anaconda 2.5 release we separated the MKL runtime into its own conda package, in order to things uniformly on all platforms.

**Comment by kalefranz** [comment]
So, @jseabold, to summarize, Windows Anaconda Distribution has always been using MKL.  The MKL change-to-default with Anaconda Distribution 2.5 really only affects unix systems.

For the packages
http://repo.continuum.io/pkgs/free/win-64/numpy-1.10.1-py35_0.tar.bz2
http://repo.continuum.io/pkgs/free/win-64/numpy-1.10.4-py35_0.tar.bz2
both identically are linked against MKL.

For the packages
http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.1-py35_0.tar.bz2
http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.4-py35_nomkl_0.tar.bz2
neither are linked against MKL, and
http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.4-py35_0.tar.bz2
*is* linked against MKL.

**Comment by kalefranz** [comment]
Also, this really isn't a conda issue.  It's an Anaconda Distribution packaging issue.  We should have moved it as soon as the discussion started.  If there needs to be further discussion, please open a new issue at https://github.com/ContinuumIO/anaconda-issues/

**Comment by jseabold** [comment]
Well I'm not using anaconda. I'm using miniconda, and I'm installing through the conda tool. I hav things like `- numpy=1.10.2=py35_0` in an environment.yml that were created using conda. The silent change to mkl makes it so that things like my symlinks to `/opt/conda/lib/libopenblas.so` are broken.

**Comment by ilanschnell** [comment]
Did you read https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations
?

**Comment by jakirkham** [comment]
I have added this issue here ( https://github.com/ContinuumIO/anaconda-issues/issues/672 ). FWIW, I still don't think this problem is solved yet, but I do hope we can find a solution.

**Comment by jseabold** [comment]
On Tue, Feb 23, 2016, 1:39 PM Ilan Schnell <notifications@github.com> wrote:

> Did you read
> https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations
> ?
>
Thanks that's helpful. No I hadn't seen that exact post. Still seems odd
that I have to change my pinned environment to keep my pinned environment.

Also not clear what the connection to anaconda is. I thought it was a
distribution that I had opted out of by using miniconda, so that I could
have a bit more fine grained control.

>

**Comment by jseabold** [comment]
On Tue, Feb 23, 2016, 1:39 PM jakirkham <notifications@github.com> wrote:

> I have added this issue here ( ContinuumIO/anaconda-issues#672
> <https://github.com/ContinuumIO/anaconda-issues/issues/672> ). FWIW, I
> still don't think this problem is solved yet, but I do hope we can find a
> solution.
>
This speaks a bit to my question on the mailing list. Why is this an
anaconda issue vs a conda issue vs a conda-recipes issue? Anaconda issues
would be the last place I'd look for this since I'm not using it.

>

**Comment by asmeurer** [comment]
I think there is a conda issue here (https://github.com/conda/conda/issues/2062). `conda update --all` installs the `mkl` feature metapackage, even if you have `nomkl` installed (which causes additional `conda update --all` calls to give Unsatisfiable Package Specifications errors). I didn't check the metadata so I can't say if the issue is that you set up the features for the mkl packages incorrectly or that conda's solver is doing the wrong thing with features. Given what I know about the solver, though, I'm guessing it's the latter. And even if the metadata is wrong, `conda update --all` ought to be idempotent, and it definitely shouldn't put the environment in an unsatisfiable state.

**Comment by jseabold** [comment]
Maybe that's a symptom of the same problem? I was installing from an `environment.yml` that didn't change but what got installed changed, so I don't see how it's directly the same thing. That said, I do not have a deep understanding here at all.

**Comment by jakirkham** [comment]
I know you have been working on the solver @mcg1969. Do you have any thoughts on this? Are there recent changes to the solver that may have affected how this works out?

**Comment by mcg1969** [comment]
The current version of conda really doesn't have the new solver. Its primary improvement on that front is caused not by changing the solver behavior but by pruning the search tree so that it has smaller problems to solve. But we know that the current solver has issues handling features properly.

**Comment by asmeurer** [comment]
Does the new solver have this problem? It's easy to check. Create a new environment with numpy, then run conda update --all in that environment, and see if it installs `mkl`.
