### ISSUE TITLE
Find solutions for conda project badges

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2101]
See https://github.com/ionelmc/python-aspectlib for a few examples.

**Comment by jakirkham** [comment]
Personally, I would lean towards breaking up that "tests" row further. Feels a little cluttered in their case. Maybe "CI Builds", "Coverage", and "Code Quality" or something like that. Some projects also do a license badge, which is easy on the eyes. The gitter badge should get its own row so it is easy to find. Also, some things worth looking at ( http://shields.io/ ) ( http://sam.pikesley.org/projects/badger/ ).

**Comment by kalefranz** [comment]
@jakirkham Yeah, feel free to submit a PR to clean it up and make it look nice :)

This ticket is *actually* meant to be about working through what *conda* and *anaconda.org* badges might look like for other projects.  And then getting them added to shield.io and badger.  Probably of interest to the conda-forge guys and community channels too.  It should all probably be compatible and be basically the same thing.

+ @mcg1969 @msarahan @pelson @ocefpaf

**Comment by jakirkham** [comment]
I see. Sorry. I saw the example and thought you were referring to the current badges here.

Also, it may be worth trying [landscape.io]( https://landscape.io/ ) too. They will use existing Python linting tools like `pylint`, `pep8`, `pep256`, etc. to lint your code. Provides an optional status for PRs, as well.

**Comment by kalefranz** [comment]
In the last several weeks when I've been experimenting with these tools,
landscape.io always seemed to be broken.  Like their workers were down or
something.

On Sat, Feb 27, 2016 at 3:28 PM, jakirkham <notifications@github.com> wrote:

> I see. Sorry. I saw the example and thought you were referring to the
> current badges here.
>
> Also, it may be worth trying landscape.io too. They will use existing
> Python linting tools like pylint, pep8, pep256, etc. to lint your code.
> Provides an optional status for PRs, as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/2101#issuecomment-189729198>.
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by kalefranz** [comment]
I think anaconda.org has this implemented now.

**Comment by jakirkham** [comment]
So I think you and others here may also be interested in PR ( https://github.com/badges/shields/pull/1001 ), which is proposing a badge for [shields.io]( https://shields.io/ ). The emphasis there is on including the channel name in the badge (e.g. available from `conda-forge` 😉).

Anyways it is pretty easy to create a demo of that PR using their [Docker]( https://github.com/badges/shields/blob/master/INSTALL.md ) build. Got that up in running in a couple of minutes (build time 😄).

**Comment by epruesse** [comment]
shields.io also allows putting a logo into the badge. See e.g. the AppVeyor badge, where the build status is shown as '<logo> build | <status>'. The logos are hosted in the shield repo though, and need to be smallish SVG. Who has the sources for the anvil?

**Comment by jakirkham** [comment]
It's a good question. I only know of the PNG, but I sent Phil an email to see if has an SVG lying around. If not, we can always run the PNG through Inkscape and make some tweaks to get a decent SVG from it.

**Comment by jakirkham** [comment]
> Who has the sources for the anvil?

They now live [here]( https://github.com/conda-forge/marketing ), @epruesse. 😉

**Comment by epruesse** [comment]
Thx! saw the mugs project.  :) Still waiting on the PR at shield... not sure if they're ever going to merge.
