### ISSUE TITLE
Store the processed yaml file in the built package

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#211]
Conda currently stores the recipe in the built package, which binstar reads to get the metadata. But really, it needs to store the built recipe, with all the preprocessing selectors removed, so binstar can use that. I suggest creating a file processed_meta.yaml and storing that in the recipe with everything else.

**Comment by bgruening** [comment]
@ilanschnell it seems that the anaconda builds do not have this info/recipe.json file. Is this intended?
For example this one: https://anaconda.org/anaconda/biopython also the numpy one.
