### ISSUE TITLE
Conda install of R and Jupyter broken on OSX?

### ISSUE THREAD

**Issue by joaquinvanschoren** [conda/conda#2117]
I have a clean install of Conda for Mac (64bit), and have installed r and r-essentials as well. However, when I want to start a Jupyter Notebook with the R kernel or run IRkernel::main from the R shell, it crashes with a segfault:

```
 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 4: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 5: loadNamespace(name)
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8: tryCatchList(expr, classes, parentenv, handlers)
 9: tryCatch(loadNamespace(name), error = function(e) stop(e))
10: getNamespace(ns)
11: asNamespace(ns)
12: getExportedValue(pkg, name)
13: IRkernel::main
aborting ...
```

Even weirder, something similar happens when I try to load ggplot2 from the R terminal:

```
> library(ggplot2)
…
 *** caught segfault ***
address 0x18, cause 'memory not mapped'
Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
...
```

This only happens with the R environment in conda, not in my other R environments. This looks like a bug?

Any help is greatly appreciated.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#696

**Comment by joaquinvanschoren** [comment]
I am not so sure anymore. I solved the second error by reinstalling a compiler. Maybe that also solved the first issue but I haven't checked that yet.

**Comment by guoruijiao** [comment]
I'm seeing the exact same issue on my installation as well. Anyone know how to resolve this?

**Comment by charlessutton** [comment]
I have the same problem for the first error, and I don't find any answer in ContinuumIO/anaconda-issues#696 ,
Help Anyone ? Thanks
