### ISSUE TITLE
Cannot pass environment.yml file to conda create.

### ISSUE THREAD

**Issue by brittainhard** [conda/conda#2124]
When I try to pass my `environment.yml` file to conda create, using the command `conda create -n scraper --file environment.yml` it throws an error,
```
Error: could not parse 'name: scraper' in: environment.yml
```

How do I get conda create to take my `environment.yml` file?

**Comment by ivoflipse** [comment]
This would also require cond, conda-env and conda-build to agree on the format of a version string as conda-env seems to allow formats which conda doesn't understand at the moment (like ==0.1*)

**Comment by msarahan** [comment]
Yes, I'm hoping https://github.com/conda/conda/issues/2071 will resolve that issue.

**Comment by kalefranz** [comment]
Definitely aware of this issue.  Being tracked in other places.  Solutions are coming...

**Comment by AnneTheAgile** [comment]
sadness. Sigh.

**Comment by AnneTheAgile** [comment]
I tried deleting the line name= and it had no effect. the other ticket #2071 is not closed yet.

**Comment by young-acecrc** [comment]
"Cannot parse name:"
This is most likely a cross-platform issue of line termini encoding.
If the environment file was created on a unix (LF stream) system and imported into a MS-Windows environment without conversion to a CR-LF stream then this error occurs.
Use an editor on MS-Windows to convert line termini to CR-LF format.  
I have not tried the reverse direction of MS-Windows export to unix/linux environment.

**Comment by grenkoca** [comment]
For those still running into this issue: try using `conda list --explicit > oldenv.txt` to export and then use `conda create --name newenv --file oldenv.txt` to import. Obviously replace `oldenv.txt` and `newenv` with whatever you want
