### ISSUE TITLE
Conda update fails

### ISSUE THREAD

**Issue by ptracton** [conda/conda#2125]
Attempting to update conda on a Windows 10 PC.

C:\WINDOWS\system32>c:\Anaconda3\Scripts\conda.exe  update --prefix c:\Anaconda3 anaconda
Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "c:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "c:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "c:\Anaconda3\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "c:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "c:\Anaconda3\lib\site-packages\conda\cli\install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "c:\Anaconda3\lib\site-packages\conda\plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "c:\Anaconda3\lib\site-packages\conda\resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "c:\Anaconda3\lib\site-packages\conda\resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "c:\Anaconda3\lib\site-packages\conda\resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.7-vc14_5.tar.bz2 MatchSpec('openssl 1.0.2*')

****************************************************************************************************************************

C:\WINDOWS\system32>c:\Anaconda3\Scripts\conda.exe info
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.6.0
     root environment : c:\Anaconda3  (writable)
  default environment : c:\Anaconda3
     envs directories : c:\Anaconda3\envs
        package cache : c:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\WINDOWS\system32>

**Comment by simlan123** [comment]
I have the same problem on Win7.
`Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
`
Also fails in an python 3 environment although that shouldn't make a difference. 

`Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\py3
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
`

**Comment by simlan123** [comment]
conda update conda
works. That solved my problem. The command that is suggested by conda to do an update still fails.

**Comment by jakirkham** [comment]
@simlan123 could you please confirm what version of `conda` you are using that solves the problem.

**Comment by simlan123** [comment]
I started out with conda version:

**Comment by kalefranz** [comment]
Should be fixed with conda `>= 4.0`.
