### ISSUE TITLE
conda skeleton pypi name case search incompatible with --version

### ISSUE THREAD

**Issue by pmlandwehr** [conda/conda#2133]
When I try to make a skeleton of CherryPy version 3.7.0, conda denies that it exists in PyPi:
```
$ conda skeleton pypi cherrypy --version 3.7.0
Error: Version 3.7.0 of cherrypy is not available on PyPI.
$ 
```

However, [there *is* a page for it in PyPi,](https://pypi.python.org/pypi/CherryPy/3.7.0) with source. What's going on?

**Comment by pmlandwehr** [comment]
So, easy answer: you need to get capitalization correct if you want to get an old version:
`$ conda skeleton pypi CherryPy --version 3.7.0` works fine.

**Comment by msarahan** [comment]
Thanks for posting this.  Here's the relevant code section:

https://github.com/conda/conda-build/blob/master/conda_build/pypi.py#L307-L325

I see this as conda trying to be overly helpful with fixing the case in the first place.  I would instead return an error saying:

    cherrypy not found.  Possible matches:
    CherryPy

I'm changing the name of this issue accordingly.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#819
