### ISSUE TITLE
Error: CMAKE_OSX_DEPLOYMENT_TARGET is '10.6'

### ISSUE THREAD

**Issue by jakevdp** [conda/conda#2134]
Hi,
I'm trying to create a conda package for flann; my current build scripts are here: https://github.com/jakevdp/conda-recipes/tree/master/flann

When I run this locally (on OSX 10.11) I get the following:
```
D-173-250-176-151:conda-recipes jakevdp$ conda build flann
Removing old build environment
Removing old work directory
BUILD START: flann-1.8.5dev-1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ........
The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0  
    cmake: 3.3.1-0   
    gcc:   4.8.5-3   
    gmp:   5.1.2-6   
    hdf5:  1.8.15.1-2
    isl:   0.12.2-1  
    mpc:   1.0.1-0   
    mpfr:  3.1.2-0   
    zlib:  1.2.8-0   

Linking packages ...
[      COMPLETE      ]|################################################################| 100%
Removing old work directory
checkout: 'b8a442fd98f8ce32ae3465bfd3427b5cbc36f6a5'
Cloning into '/Users/jakevdp/anaconda/conda-bld/work'...
done.
Note: checking out 'b8a442fd98f8ce32ae3465bfd3427b5cbc36f6a5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b8a442f... Merge pull request #270 from rfmcpherson/patch-1
==> git log -n1 <==

commit b8a442fd98f8ce32ae3465bfd3427b5cbc36f6a5
Merge: 9a01507 58a7f91
Author: Marius Muja <mariusmuja@gmail.com>
Date:   Wed Sep 16 10:44:08 2015 -0700

    Merge pull request #270 from rfmcpherson/patch-1
    
    Updated comments in lsh_index


==> git describe --tags --dirty <==

1.8.1-src-145-gb8a442f


==> git status <==

HEAD detached at b8a442f
nothing to commit, working directory clean


Package: flann-1.8.5dev-1
source tree in: /Users/jakevdp/anaconda/conda-bld/work
+ mkdir build
+ cd build
++ uname
+ [[ Darwin == Darwin ]]
+ export CC=gcc
+ CC=gcc
+ export LD=gcc
+ LD=gcc
+ export CXX=g++
+ CXX=g++
+ cmake .. -DCMAKE_INSTALL_PREFIX=/Users/jakevdp/anaconda/envs/_build -DBUILD_MATLAB_BINDINGS:BOOL=OFF -DBUILD_PYTHON_BINDINGS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
CMake Error at /Users/jakevdp/anaconda/envs/_build/share/cmake-3.3/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.6' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Users/jakevdp/anaconda/envs/_build/share/cmake-3.3/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/jakevdp/anaconda/conda-bld/work/build/CMakeFiles/CMakeOutput.log".
Command failed: /bin/bash -x -e /Users/jakevdp/repos/conda-recipes/flann/build.sh
```
I've found that if I explicitly set ``CMAKE_OSX_DEPLOYMENT_TARGET=""`` in ``build.sh``, the package compiles without a problem. Is this the right solution here? If I change the deployment target, is there a danger that the package will not be installable by people with older OSX versions? Thanks

**Comment by ahmadia** [comment]
I believe so. With the caveat that your code will run on 10.8 or later.

**Comment by msarahan** [comment]
Hi Jake, for future reference, this is more of a conda-recipes or
conda-build issue.

Setting CMAKE_OSX_DEPLOYMENT_TARGET to "" is fine, but the implication is
that you no longer explicitly know what your OSX deployment target is (it
is variable based on what computer you use to build the recipe).  In order
to get older or newer deployment targets, you sometimes have to have old
(or newer) SDKs/XCode versions, and those are hard to come by.

My advice would be: proceed as you suggest, and if you have compatibility
issues coming from consumers of your built package(s), then explore
alternative build platforms (Travis CI with Mac support, or perhaps
anaconda.org with a mac worker.)  We keep old OS X machines around for this
exact reason.

**Comment by jakevdp** [comment]
Got it – thanks!

**Comment by ccordoba12** [comment]
@jakevdp, I think it's better for you to install the right SDK to build packages because you're going to encounter this issue for all projects that use CMake as a build system.

I have a copy around if you need it :-)

**Comment by jakevdp** [comment]
Thanks @ccordoba12 – is it different than what's available on github [here](https://github.com/phracker/MacOSX-SDKs)?

**Comment by ccordoba12** [comment]
I don't think so, but I didn't know about that resource (thanks for it!). I had to dig my 10.6 SDK from an old XCode dmg i had :-)

**Comment by jakevdp** [comment]
Thanks! Do you have any resource that goes through how to make one of these SDKs available on your computer?

**Comment by ccordoba12** [comment]
I think SDKs need to go to `/Developer` but I'm away from my Mac right now. I'll let you know this afternoon.

**Comment by jakevdp** [comment]
I did some poking around and found this script: https://gist.github.com/rnapier/3370649

Seems you can find the xcode path using
```
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```
Then the SDKs go in a folder that looks like this:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
```

**Comment by ccordoba12** [comment]
But that's if you have XCode installed. If you're using command line tools, there's a different story.

**Comment by jakevdp** [comment]
Good point – let me know if you find info on how to do it with Command Line Tools
