### ISSUE TITLE
create an option to disable menu installation in Windows OS

### ISSUE THREAD

**Issue by eugenschindler** [conda/conda#2144]
related to #1717 and #2136
Please create an option or flag to disable menu installation upon "conda create" in the Windows OS. As mentioned in the related issues, this will give an option to circumvent the PermissionError problems in Windows when creating a new conda environment in an admin installation as a non-admin on Windows.

rationale (may be TL;DR):
People that care about this, usually have a use case where they want to be flexible installing packages as non-admins (because for example going via the admin has too much lead time) but still want to offer a system-wide miniconda system with the environments centralized to users that don't know or care about how to create environments but want these environments maintained system-wide.

**Comment by maitlahcen** [comment]
Dear @msarahan. Any fix on the horizon for this issue?

Best,

**Comment by msarahan** [comment]
I think that this has been an option for quite a while.  Does #2623 and #3032 do what you want?

**Comment by maitlahcen** [comment]
So if I remove menuinst from the package list will it get rid of this issue?

**Comment by maitlahcen** [comment]
Great! It worked just by removing `menuinst` from the environment. Thank you very much!

**Comment by msarahan** [comment]
I was more suggesting the .condarc change from #3032, but if removing menuinst is a better solution for you, then that's great, too.  I'm going to close this issue, but please reopen or open a new one if this is still a problem for anyone.
