### ISSUE TITLE
Since update to El Capitan `conda update conda` and `conda update any_package` returns url error

### ISSUE THREAD

**Issue by kungfujam** [conda/conda#2150]
Mac OS 10.11.3 
Conda 3.19.1

```
$ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: .........Error: Could not find URL: http://repo.continuum.io/pkgs/gpl/osx-64/
```

Navigating to http://repo.continuum.io/pkgs/gpl/osx-64/ I see this is down (404 Not Found). I'm presuming this is a temporary issue and not than I need to change a url?

**Comment by kungfujam** [comment]
This is still an issue for me since upgrading to El Capitan. Any clues?

**Comment by kungfujam** [comment]
This is still an issue. Have updated title to be more descriptive.

**Comment by groutr** [comment]
the GPL repo is no longer used (and I think has been removed).  You can fix this by removing from your channels list in .condarc

**Comment by kungfujam** [comment]
Perfect. Quick fix. Removed the line 

`    -  http://repo.continuum.io/pkgs/gpl/`

from the file in home directory `~/.condarc`. Cheers.
