### ISSUE TITLE
new auxlib needs to call git subprocess with cwd set

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2162]
@kalefranz the new auxlib just gave me the strangest error, which took me a while to figure out.  The reason was because I was working on a project (constructor) which is also under git revision control.  After some debugging, I realized that calling `git` in the new `auxlib` is the problem.  You need to ensure that all subprocess calls to `git` use the `cwd` keyword argument (with value set to the conda root directory).  Otherwise `git` is called on whatever other project you happen to work on, and you get errors which are hard to debug.

**Comment by ilanschnell** [comment]
Also, I noticed that `auxlib` is now shipped with the conda package (of conda), because the `setup.py` lists `conda.auxlib` in the `packages` keyword argument.  This is something versioneer does smarter.  In the currently shipped conda packages there is `conda._version`, which is only a tiny module with:
```
version_version = '3.19.3'
version_full = '3ef79312b9351a9a82f379039005e1c9091aca0c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}
```
We should not be shipping `auxlib`.

**Comment by ilanschnell** [comment]
@kalefranz `auxlib` is way to complicated for deployment I think.  The version should be hard-coded into the Python code.  If needed, I will patch the source when I create the final builds of conda.  The patch would result into having the following code in `conda/__init__.py`:
```
...
__version__ = '4.0.0'
...
```

**Comment by kalefranz** [comment]
Resolved in other PRs and discussion :)
