### ISSUE TITLE
Miniconda installation in chroot fails

### ISSUE THREAD

**Issue by macurie** [conda/conda#2164]
I have a chroot environment created with vmbuilder (debootstrap) like this:

`vmbuilder kvm ubuntu -o -v --suite precise --arch amd64 --rootsize 9216 --user myuser --pass mypass --hostname $dname --addpkg libjson-perl --addpkg liburi-encode-perl --addpkg curl --addpkg acpid --addpkg openssh-server --addpkg wordpress --addpkg memcached --addpkg php5-memcache --addpkg nfs-common --addpkg dmidecode --addpkg unzip --addpkg mysql-server --addpkg libstring-shellquote-perl --tmpfs - --domain mydomain.com --ip 10.1.1.2 --execscript="./$me"`

I then try to install Miniconda like this:

```
chroot $chroot_dir wget -q https://repo.continuum.io/miniconda/Miniconda3-3.19.3-Linux-x86_64.sh -O /tmp/miniconda.sh
chroot $1 chmod +x /tmp/miniconda.sh
chroot $1 bash /tmp/miniconda.sh -f -b -p /opt/conda
```

But I get:

`/opt/conda/pkgs/python-3.5.1-0/bin/python: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
cannot execute native linux-64 binary, output from 'uname -a' is:`
How do I fix this?

**Comment by ilanschnell** [comment]
What is the output from `uname -a`?  I suspect that they OS is incompatible.  Are you only having this problem when using `chroot`?  Have you tried installing Miniconda into your home directory?

**Comment by macurie** [comment]
The output from `uname -a` seems to be empty inside the chroot!

I am only having this problem when using chroot, I can boot the image afterwards and run miniconda.sh and install it fine.

**Comment by bpinaya** [comment]
Hey there, any updates on this? I am trying to install miniconda on aarch. Output on my uname -a is:
Linux tegra-ubuntu 4.4.15-tegra #1 SMP PREEMPT Wed Feb 8 18:06:32 PST 2017 aarch64 aarch64 aarch64 GNU/Linu
Any help is appreciated

**Comment by H-Plus-Time** [comment]
@bpinaya You should be able to use the Linux-armv7l.sh variant of Miniconda (available at [repo.continuum.io/miniconda](https://repo.continuum.io/miniconda/)). aarch64 is backwards compatible with armv7l; that said, conda detects aarch64 as linux-32 or linux-64 (depending on the results of ```getconf LONG_BIT```) for the moment. I've submitted a PR to fix this (its a 4 line fix to conda/base/context.py), which should rectify this for the moment. Eventually aarch64 might be supported explicitly by conda, but we'll have to wait and see.

**Comment by bpinaya** [comment]
hey @H-Plus-Time thanks for the help, I checked your fork and will apply that fix and see how it goes.

**Comment by H-Plus-Time** [comment]
Oops, as it turns out, it isn't quite as simple as I had thought :-S. If you're running a 64 bit kernel (aarch64), and a 32 bit user space (similar to how SPARC systems are set up) - armhf - everything will work (with the above changes to conda/base/context.py). If, however, you are running both a 64 bit kernel _and_ 64 bit userspace, you need to add the armhf architecture, and libc6:armhf (which provides the ld-linux-armhf.so.3 linker binary). For debian-based systems, the below works:

```bash
sudo dpkg --add-architecture armhf && sudo apt-get update
sudo apt-get install libc6:armhf
ln -s /path/to/ld-linux-armhf.so.3 <parent dir of ld-linux-aarch64.so.3>/
```

You may also need to add a symlink from <parent dir of ld-linux-aarch64.so.3>/ld-linux.so.3 to ld-linux.armhf.so.3.

**Comment by supermanhuyu** [comment]
> Oops, as it turns out, it isn't quite as simple as I had thought :-S. If you're running a 64 bit kernel (aarch64), and a 32 bit user space (similar to how SPARC systems are set up) - armhf - everything will work (with the above changes to conda/base/context.py). If, however, you are running both a 64 bit kernel _and_ 64 bit userspace, you need to add the armhf architecture, and libc6:armhf (which provides the ld-linux-armhf.so.3 linker binary). For debian-based systems, the below works:
> 
> ```shell
> sudo dpkg --add-architecture armhf && sudo apt-get update
> sudo apt-get install libc6:armhf
> ln -s /path/to/ld-linux-armhf.so.3 <parent dir of ld-linux-aarch64.so.3>/
> ```
> 
> You may also need to add a symlink from /ld-linux.so.3 to ld-linux.armhf.so.3.

i have the get the files libc6 and ld-linux-aarch64.so ,but i still do not know how to install miniconda or anaconda in the aarch64, can you tell me how to install it ? or tell me where can i get the tutorial? 

thanks
