### ISSUE TITLE
Changing the shebang line to use python.app

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#217]
IPython 1.0.0a1 doesn't work with the qtconsole in Mac OS X unless it's run from pythonw. How can I make the shebang line point to this instead of python in my conda package?

Alternately, as I mentioned on another issue, is there any reason why we cannot make Python.app the default Python interpreter in Mac OS X?

**Comment by kerrywatson1** [comment]
@asmeurer can this be closed now?

**Comment by asmeurer** [comment]
Yeah, this is documented at http://conda.pydata.org/docs/building/meta-yaml.html#python-app
