### ISSUE TITLE
conda's gcc can't find OpenGL

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#2170]
I'm trying to build a C++ package using conda's gcc. The package uses cmake and requires OpenGL. However, cmake can't find OpenGL within the build environment using conda's gcc:

```
CMake at... (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
```

I have configured `build.sh` according to [this comment](https://github.com/ContinuumIO/anaconda-issues/issues/483#issuecomment-149262721), but I'm still seeing the OpenGL error.

Does anyone have a suggestion on how to get conda's gcc to find opengl?

Note: I accidentally fat-fingered the "Submit New Issue" button before I finished writing this issue. Sorry.

**Comment by jrsmith3** [comment]
Also, is the recommended practice for building and distributing C++ packages to use conda's gcc?

**Comment by Maxyme** [comment]
requirements:
 I've managed to make it work with mesa by turning use X in the bash:
 -DVTK_USE_X=OFF

and adding mesa as requirement.
 build:
    - gcc
    - mesa
    - cmake
    - python

Maybe there's a opengl package in Anaconda that can be referenced as requirement to fix this. At this moment, I haven't found a way to enable X in VTK.

**Comment by jrsmith3** [comment]
Including the `mesa` package in `meta.yaml` didn't help. It doesn't look like the `mesa` package comes with any OpenGL libraries. :/

**Comment by jrsmith3** [comment]
I'm still getting the same error from `cmake`.

Here is the relevant code in the generic `FindOpenGL.cmake`

```
  find_library(OPENGL_gl_LIBRARY
    NAMES GL MesaGL
    PATHS /opt/graphics/OpenGL/lib
          /usr/openwin/lib
          /usr/shlib /usr/X11R6/lib
          ${_OPENGL_LIB_PATH}
  )
```

Here's the list of files the conda `mesa` package installs:

```
  "files": [
    "include/GL/gl.h", 
    "include/GL/gl_mangle.h", 
    "include/GL/glcorearb.h", 
    "include/GL/glext.h", 
    "include/GL/glx.h", 
    "include/GL/glx_mangle.h", 
    "include/GL/glxext.h", 
    "include/GL/osmesa.h", 
    "include/GL/wglext.h", 
    "include/GL/wmesa.h", 
    "lib/libOSMesa.la", 
    "lib/libOSMesa.so", 
    "lib/libOSMesa.so.8", 
    "lib/libOSMesa.so.8.0.0", 
    "lib/pkgconfig/gl.pc", 
    "lib/pkgconfig/osmesa.pc"
  ], 
```

So maybe `cmake` should be looking for `lib/libOSMesa.so` instead of `lib/libMesaGL.so`?

**Comment by Maxyme** [comment]
Did you add this to the build script? I haven't managed to make it work otherwise.

-DVTK_USE_X=OFF

**Comment by jrsmith3** [comment]
Unfortunately adding that flag to the build script didn't work.

**Comment by Maxyme** [comment]
Can you try this recipe?

It built successfully for me with the latest conda version - 4.0.0

https://github.com/ClinicalGraphics/conda-recipes/tree/master/vtk

**Comment by jrsmith3** [comment]
Thanks for sticking with this issue.

I will try out your suggestion and let you know what happens soon.
In the meantime, do you know why `cmake` from within `build.sh` can't see the system libraries?
If I add a call to `ldconfig` in `build.sh`,

```
ldconfig -p | grep libGL
```

I get the following output:

```
    libGLU.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLU.so.1
    libGLU.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLU.so
    libGLEWmx.so.1.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.10
    libGLEW.so.1.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLEW.so.1.10
    libGLESv2.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2
    libGLESv2.so.2 (libc6,x86-64) => /usr/lib/nvidia-352/libGLESv2.so.2
    libGLESv2.so.2 (libc6) => /usr/lib32/nvidia-352/libGLESv2.so.2
    libGLESv2.so (libc6,x86-64) => /usr/lib/nvidia-352/libGLESv2.so
    libGLESv2.so (libc6) => /usr/lib32/nvidia-352/libGLESv2.so
    libGLESv1_CM.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv1_CM.so.1
    libGLESv1_CM.so.1 (libc6,x86-64) => /usr/lib/nvidia-352/libGLESv1_CM.so.1
    libGLESv1_CM.so.1 (libc6) => /usr/lib32/nvidia-352/libGLESv1_CM.so.1
    libGLESv1_CM.so (libc6,x86-64) => /usr/lib/nvidia-352/libGLESv1_CM.so
    libGLESv1_CM.so (libc6) => /usr/lib32/nvidia-352/libGLESv1_CM.so
    libGL.so.1 (libc6,x86-64) => /usr/lib/nvidia-352/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib32/nvidia-352/libGL.so.1
    libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
    libGL.so (libc6,x86-64) => /usr/lib/nvidia-352/libGL.so
    libGL.so (libc6) => /usr/lib32/nvidia-352/libGL.so
```

So the environment within `build.sh` can see `libGL`, but for some reason `cmake` can't see it and fails.

**Comment by jrsmith3** [comment]
I was able to build your `vtk` recipe with conda 4.0.1.

I think the problem might be in the arguments I'm passing to `cmake` in `build.sh`:

```
CMAKE_GENERATOR="Unix Makefiles"

if [ "$(uname)" == "Linux" ]; then
  cmake .. -G "$CMAKE_GENERATOR" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_apps:BOOL=OFF \
    -DBUILD_tools:BOOL=OFF \
    -DBUILD_examples:BOOL=OFF \
    -DBUILD_global_tests:BOOL=OFF \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DBOOST_LIBRARYDIR=$PREFIX/lib \
    -DCMAKE_C_COMPILER="${PREFIX}"/bin/gcc \
    -DCMAKE_CXX_COMPILER="${PREFIX}"/bin/g++ \
    -DCMAKE_PREFIX_PATH="${PREFIX}" \
    -DCMAKE_EXE_LINKER_FLAGS=-L"${PREFIX}"/lib \
    -DCMAKE_MODULE_LINKER_FLAGS=-L"${PREFIX}"/lib \
    -DCMAKE_SHARED_LINKER_FLAGS=-L"${PREFIX}"/lib
fi
```

**Comment by kalefranz** [comment]
Hey guys, going to move this issue to the conda-recipes repo (even though that's not an exact fit either).

Just one note first...

> Also, is the recommended practice for building and distributing C++ packages to use conda's gcc?

We're working on clarification of this exact issue right now, with the goal of having the tools and best-practices documentation ready before Ubuntu 16.04 hits.  @msarahan might have more to add here.

**Comment by looooo** [comment]
I guess this is a problem because libglu is a system library but handled different in debian and centos.

for ubuntu16.04 this worked:
```
  mkdir -p /opt/graphics/OpenGL/lib \
    && ln -s /usr/lib64/mesa/* /opt/graphics/OpenGL/lib \
    && ln -s /usr/lib/x86_64-linux-gnu/libGLU.so /opt/graphics/OpenGL/lib \
    && ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib64
```

**Comment by chrisdembia** [comment]
@looooo are those commands for your user machine? Which conda package were you trying to use? I'm running into similar issues.

**Comment by mingwandroid** [comment]
Please do not follow this advice. Use CDT packages instead. They guarantee the software you build is compatible with a range of linux distros whereas @looooo's suggestion will work only for your current distro and those compatible with it.

An example of this can be seen [here](https://github.com/AnacondaRecipes/libglu-feedstock/blob/master/recipe/meta.yaml#L18).

**Comment by chrisdembia** [comment]
Thanks @mingwandroid. I understand. I'm just trying to get a grasp on the issue. Any help you can provide for https://github.com/conda-forge/simbody-feedstock/pull/23 would be appreciated.
