### ISSUE TITLE
`conda info` has no support for `-c` option

### ISSUE THREAD

**Issue by stefanseefeld** [conda/conda#2174]
`conda install -c <channel> <package>` sometimes informs me about conflicting dependencies, suggesting to use `conda info <package>` to find out the details of those conflicts. However, if <package> comes from a default channel <channel>, I'd need a way to specify the above `-c <channel>` option with the `conda info` command. Unfortunately that option isn't supported.

**Comment by kalefranz** [comment]
duplicate of #1390
