### ISSUE TITLE
developing conda now requires auxlib

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2182]
As of the conda 4.0 release, developing conda requires @kalefranz 's `auxlib` to be installed.  Is there any way, we could make this optional?

**Comment by ilanschnell** [comment]
Actually this is worse than I initially thought it would be.  When somebody on conda they will:
  * `git pull`
  * `conda info`  # oh, this is broken now saying auxlib is missing
  * `conda install auxlib` # not found (even if it was available, they'd had to `git revert`)
  * `pip install auxlib` # hmm, we tell people to pip install stuff?
  * `conda info` # Yay!  It finally works.

I'm not complaining here, as I can work through this.  But many develops may find all very confusing.

I suggest that we put auxlib (or the pieces we need from it) into the conda source root.  This will also mean that the `import auxlib` in `setup.py` will always work.

**Comment by pelson** [comment]
Similar position. Depending on a package which has 0 anaconda.org builds is a bit awkward (as you end up having to pip install it). In terms of automatic versioning, I completely agree that versioneer is less than perfect, but it is head and shoulders above anything else I've seen out there (unless you want the age-old approach of ```commit to change version -> release -> commit to change to dev version```).

**Comment by mcg1969** [comment]
I am agnostic on auxlib vs versioneer but not on the need to pip install!

**Comment by msarahan** [comment]
I am anti auxlib, at least without a technical review of auxlib.  It sounds
and looks good at a glance to me, but it is Kale's personal project.
Compared to any of the existing libraries for versioning, this imposes an
additional maintenance burden on Kale directly and on continuum less
directly (until Kale leaves, then it depends on the nature of Kale's
departure.)

Are we absolutely certain that an update of versioneer or a patch to
versioneer would not be sufficient?  What have we done to investigate other
more well-established (and not maintained by continuum staff) libraries?

**Comment by mcg1969** [comment]
Well, Kale is never leaving Continuum, so that I'm not so concerned about :-)

**Comment by kalefranz** [comment]
#2188 addresses this for now.  @msarahan while it's a personal project, it's not intended to always be.  The biggest reason it's still `0.0.x` is because I haven't written up this sphinx stuff and hooked into readthedocs.

**Comment by pelson** [comment]
I confess I share @msarahan's concern about depending on a pretty fresh library vs the tried and tested of versioneer (for all its quirks). Though I accept it has to cut its teeth somewhere...

Anyway, thanks for fixing this. :+1:
