### ISSUE TITLE
Source Deactivate Causes Too Many Arguments

### ISSUE THREAD

**Issue by seanlaw** [conda/conda#2184]
I did my research and saw that this type of error was typically caused by having a `set` keyword in setting an environment variable. However, I had none. Finally, it dawned on me that between July 2015 and March 2016 that the way to deactivate was changed from:

`source deactivate py34`

to simply

`source deactivate`

When did this happen and how/why is it not make backwards compatible by simply ignoring extra argument?

**Comment by msarahan** [comment]
It looks like this has been this way since 2013: https://github.com/conda/conda/commit/bf5ce8f6443aa1ff3002d78e3b37c62d5d2d42c1

I don't know why.  I have removed this in #1727, which hopefully will be merged soon.

Windows may not have had this restriction - maybe you're used to that?

**Comment by kalefranz** [comment]
I think this should be resolved once we merge #1727 in the next couple days.  Going to close the issue for now.
