### ISSUE TITLE
A proper explanation of conda's mysterious choices

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#2185]
A sizeable fraction of the support volume for Conda and Anaconda stems from apparently "mysterious" solutions produced by the `conda` solver. The most common red flag for users are downgrades---when `conda` determines that it must install an older version of a package due to dependency conflicts. If a user has been content with their installed version of the package, why should they accept a downgrade?

Now, I am biased, because I revamped the new solver, but I tend to think that conda is actually _doing the right thing_ in most of these cases. The problem is not that conda is wrong, but that it is making decisions based on information that is generally invisible to the end user: the depdenency requirements hidden in the metadata.

What `conda` needs, therefore, is the ability to print out a _cause_ for every "non-intuitive" action that it takes. In the case of a downgrade/older package selection, it should scan the final environment for the packages that are preventing the newer version from being selected, and list them.

But it's not just downgrades that merit explanation. If a package is being installed or upgraded that wasn't explicitly requested, it's because of some dependency relationship. In those cases, `conda` should identify the dependency chain that causes this installation/upgrade.

Supplying this information will accomplish two goals. First of all, it will reassure the users that `conda` knows what it is doing. But it will also help us reveal potential problems with the underlying metadata. In some cases, we will find that the dependencies imposed by a particular package are too strict, and need to be relaxed. When users file a support request with this information in hand, it will be a lot easier for us to see the problem and fix it.

I'm doing a lot of handwaving here but hopefully it is clear what I'm saying; if not, let me know and I will clarify.

**Comment by kalefranz** [comment]
I agree that we should make improved output logging and user hints a priority for 4.1, which I'd like to have available in time for Anaconda 2.6.

**Comment by janssen** [comment]
See https://github.com/conda/conda/issues/2207 and https://github.com/conda/conda-build/issues/807.  I'd sure love to know what's going on there -- this 4.0 release has clobbered my entire build system.

**Comment by marscher** [comment]
At least we have a serious problem with our software (A) here, because of an API change in a dependent package (B) requires an update, but it is not performed (even though the new version is available). This is IMHO a bug, not a feature. Downgrading to conda prior version 4 resolves this problem. Eg. it works like expected (updating A triggers a update on B).

It is totally non obvious to me, why B is not updated any more. And I do not think that this could be explained in this case by any more information on resolution (B is more recent on the channel, default policy used to be "update as many packages as possible").

see markovmodel/pyemma#723 for details.

**Comment by mcg1969** [comment]
For the sake of readers here, I've responded directly to the PyEmma issue in https://github.com/markovmodel/PyEMMA/issues/723 . It certainly speaks to the need to give people a clear understanding of the best practices for `conda` recipes and proper documentation of how we _intend_ `conda` to work (even if sometimes `conda` fails to live up to those intentions).
