### ISSUE TITLE
Using Anaconda Cloud message should say Anaconda Repo

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#2201]
When doing a conda search against a local Anaconda Repo, conda shows the message Using Anaconda Cloud api: <repo channel>.  Can we change the message to say Anaconda Repo instead of Anaconda Cloud.  It would be more accurate and it would not raise red flags within the enterprise about accessing external (Internet/Cloud) resources.

**Comment by kalefranz** [comment]
Message is now suppressed and not shown at all.
