### ISSUE TITLE
BUG: Cannot activate env on Windows with envs_dirs is set in .condarc

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#2202]
Using conda 4.0.1
Add envs_dirs to .condarc file on Windows.
Create a new env.
Do conda info -e to see the new env in the envs_dirs directory.
activate new env

The **activate will fail**.  It seems that activate doesn't support the envs_dirs config in .condarc.
The activate command is only looking in the default envs location on Windows.

**Comment by msarahan** [comment]
Please try setting the CONDA_ENVS_PATH environment variable for now.  This is a problem that PR #1727 will fix by using Conda's internals, rather than completely separate batch file logic.

**Comment by joelhullcio** [comment]
@msarahan the CONDA_ENVS_PATH work-around worked.  Thank you.

**Comment by kalefranz** [comment]
FYI #1727 will be merged within the coming days for the conda `4.1` release that should be ready for Anaconda `2.6`.
