### ISSUE TITLE
Matplotlib 1.5.1 broken on Windows 10

### ISSUE THREAD

**Issue by nihalarju** [conda/conda#2204]
With Anaconda, trying to import matplotlib.pyplot leads to error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 36, in <module>
>     from matplotlib.figure import Figure, figaspect
>   File "C:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 35, in <module>
>     from matplotlib import _image
>   File "C:\Anaconda3\lib\site-packages\matplotlib\_image.py", line 7, in <module>
>     __bootstrap__()
>   File "C:\Anaconda3\lib\site-packages\matplotlib\_image.py", line 6, in __bootstrap__
>     imp.load_dynamic(__name__,__file__)
>   File "C:\Anaconda3\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.

Version and system info:  Python 3.5.1 |Anaconda 2.5.0 (64-bit)| [MSC v.1900 64 bit (AMD64)] on win32

Tried:
```
conda update conda
conda update --all
```
with no effect. 

Thanks for looking into this.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#689
