### ISSUE TITLE
Invalid version spec: ==

### ISSUE THREAD

**Issue by markunsworth** [conda/conda#2212]
We've noticed over the last couple of days that we are seeing this error when creating conda environments.

Our command to create the environment is:

```
conda create --yes -p env --file conda.txt 
```

Our conda.txt looks like this:

```
pandas
requests
openssl
cryptography
```

We run this as part of a chef script. Debug output:

```
    ---- Begin output of "bash"  "/tmp/chef-script20160309-6131-969nbt" ----
STDOUT: Fetching package metadata: ....
STDERR: DEBUG:conda.fetch:channel_urls=('https://repo.continuum.io/pkgs/free/linux-64/', 'https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pro/linux-64/', 'https://repo.continuum.io/pkgs/pro/noarch/')
INFO:stdoutlog:Fetching package metadata: 
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'session': <conda.connection.CondaSession object at 0x7fd19355c490>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/linux-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/linux-64/',) kwargs {'session': <conda.connection.CondaSession object at 0x7fd19355c490>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'session': <conda.connection.CondaSession object at 0x7fd19355c490>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/linux-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/linux-64/',) kwargs {'session': <conda.connection.CondaSession object at 0x7fd19355c490>, 'use_cache': False}
INFO:stdoutlog:

DEBUG:conda.plan:Pinned specs=[]
Error: Invalid version spec: ==
---- End output of "bash"  "/tmp/chef-script20160309-6131-969nbt" ----
```

Output from `conda info`

```
Current conda install:

         platform : linux-64
         conda version : 4.0.2
         conda-build version : 1.14.1
         python version : 2.7.10.final.0
         requests version : 2.7.0
```

What can we do to fix this or is it a problem with one of the repodata.json files?

**Comment by mcg1969** [comment]
I'm having some trouble reproducing this problem. Is there any way to get a traceback for that error?

**Comment by kalefranz** [comment]
@markunsworth I also can't reproduce this problem on either OS X or CentOS.

I've started to notice that when I can't reproduce a problem, it's often because of a corrupted conda cache.  Can you run the following clean command and then see if your problem persists?  If it does, please re-open the issue...

    conda clean --index-cache --lock --tarballs --packages --source-cache

**Comment by markunsworth** [comment]
@kalefranz This is occurring with a completely fresh install of anaconda so not down to a cache issue as nothing has been downloaded at that point. I have also run the `conda clean` command and still get the same issue.

What is strange though is if I ssh to the box and run the same commands manually it does run successfully.

**Comment by markunsworth** [comment]
So i've tweaked the debug logging in conda and have found this to be due to `specs` at [line 407 in plan.py](https://github.com/conda/conda/blob/887646a59913695019dcd2f204e57fad90ea4f9c/conda/plan.py#L407) having the value:

    ['pandas', 'requests', 'openssl', 'cryptography', 'pip ==']

This was due to us setting pip as a default package using the following command:

    conda config --force --add create_default_packages pip==#{node['python']['pip_version']}

Unfortunately `#{node['python']['pip_version']}` evaluates to nil in our chef recipe so the condarc ends up looking like this:
  
    create_default_packages:
    - pip==

There should probably be some error checking when using `conda config` command.

**Comment by mcg1969** [comment]
Great forensics, @markunsworth, thanks. This means that the error message was correct, but not helpful, because it didn't show you which package spec was broken. That's something that can be tweaked. And I agree this suggests an improvement to `conda config`.

@kalefranz, I know you're on an issue handling tear today but I think this one should be reopened simply as a placeholder for that fix to `conda config`.

**Comment by kalefranz** [comment]
Agreed. We need to have a condarc lint tool maybe.

Also, I think it's awesome you are using conda with chef. Are there any plugins/modules/whatever-chef-calls-them yet? Or have you basically hacked it and shelled out to conda?

**Comment by mwjackson** [comment]
I'm not sure a lint tool is required TBH, just outputting the file and line
number or content would have been enough to help us narrow this down a lot
quicker

Re: chef. No nothing yet, just a few bash commands has been sufficient and
is pretty robust.

**Comment by markunsworth** [comment]
At the moment, as @mwjackson suggests we are just shelling out to bash, it does the job, but I'd like to get something put together to simplify it. @poise has a nice set of chef recipes/providers for python and he's working on allowing other python implementations to be installed/used so anaconda might fit nice I to that. If not it might be a good starting point

**Comment by apahl** [comment]
Hi all,

since today, I get the same error with conda 4.1.3, when attempting an update:
```
((chem)) ~$ conda update --all
Fetching package metadata .......
Error: Invalid version spec: ==
```
Kind regards,
Axel

**Comment by apahl** [comment]
I found the violating code:

I had a `pinned` file in `<env>/conda-meta` that contained this line: `boost == 1.56.0`.
When I removed the space after the two equal signs and before the word boost (i.e. `boost ==1.56.0`), the error disapperared.

Kind regards,
Axel

**Comment by mcg1969** [comment]
Thanks for the discovery! We should investigate the code that led to this extra space. In fact, `conda` expects the format of a match spec to be `package version build`. So in other words, that extra space was putting `1.56.0` in the `build` field, and a broken `==` in the version field.

**Comment by apahl** [comment]
Sorry, I was not completely clear. I generated the `pinned` file myself and also put the extra space between the equal signs and the word `boost`, because it looked *nicer* and I didn't think it would be significant.

**Comment by mcg1969** [comment]
Ah, I got it. Still, I would say that we need to provide better error messaging here, perhaps even detect this type of "mistake" and provide the user with more constructive feedback. I definitely think that adding the extra space looks nicer!

**Comment by jezdez** [comment]
Closing in favor of #7978.
