### ISSUE TITLE
conda update conda interruption fix

### ISSUE THREAD

**Issue by zeneofa** [conda/conda#2222]
Hi,

Is there an easy/simple way to recover from an interrupted 'conda update conda'. It has happened to me several times when installing a package, that conda asks to update itself and other packages, there is generally more than one package involved. Then if any of those packages fail to update, the whole process exits and my conda installation is broken. Is there a way to recover from this? 

P

**Comment by kalefranz** [comment]
Try running `conda clean -i -l -t -p -s`.  If that doesn't help, Please provide more information about the error :)

**Comment by zeneofa** [comment]
Hi,

The problem is that when any update of a set of packages, which includes
among it an upgrade of conda itself, is unsuccessful, then conda is removed
and the entire installation is corrupted. Thus, there is no 'conda' command
in:

miniconda/bin

So far the only way that I have found to fix this, is to re-install
miniconda and then reinstall each and every package individually again. So
I was wondering if there was an easier way? For recent installations, this
is not that much of a problem, however as additional tweaks get made to a
current anaconda installed python (ie custom packages, configurations,
etc), it becomes rather a pain to re-install everything. So apart from
regular backups is there an alternative?

P

**Comment by kalefranz** [comment]
Oh! It's that problem.  This is another path where it's triggered I guess.  Going to re-open the ticket.  That "conda uninstalls itself" problem is something we really need to get to the bottom of.

@ijstokes I think you had set of steps in another ticket that reproduced this in a slightly different way?

**Comment by kalefranz** [comment]
#2222 This is even an awesome ticket number to memorialize this problem.  Leaving this open until this dragon is slayed and dead.

**Comment by mcg1969** [comment]
Hadn't thought of this. It's a great argument for having a _conda environment that very few packages can actually touch.

**Comment by kalefranz** [comment]
Yes, I'd like conda to NOT be in the root environment.  Conda is an end-user application with its own dependencies, not a library.  If we want to lock it down to python 3.5, for example, we should be able to.

The conda root environment and the "user default" environment don't have to be and shouldn't be the same.

**Comment by mcg1969** [comment]
It seems _particularly_ dangerous to have packages in the root environment with install scripts.

**Comment by kalefranz** [comment]
Fixed with transactions in conda 4.3.
