### ISSUE TITLE
conda build test phase, package still thinks it is installed in _build

### ISSUE THREAD

**Issue by davidslac** [conda/conda#2223]
I made my own conda package for mpi4py, following the conda recipe for it, I added a test section that did 
```
import mpi4py.MPI
```
however I got an error which looked like
```
===== testing package: mpi4py-1.3.1-py27_openmpi_0 =====
import: u'mpi4py'
import: u'mpi4py.rc'
import: u'mpi4py.dl'
import: u'mpi4py.MPI'
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /reg/g/psdm/sw/conda/miniconda2/envs/_build/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
```
This seems like a bug in conda, this is the test phase, and the environment available is _test, but openmpi is looking in _build. I did get a warning that my condabuild package is one behind:
```
WARNING: conda-build appears to be out of date. You have version 1.19.0 but the
latest version is 1.19.1. Run

conda update -n root conda-build

to get the latest version.
```
maybe that will fix it?

**Comment by msarahan** [comment]
What's happening is that that prefix is getting hard-coded into your package, but not replaced appropriately at install time.   You might find some insight at http://conda.pydata.org/docs/building/meta-yaml.html#making-packages-relocatable

If not, please tell us where you get to with it.

**Comment by davidslac** [comment]
Thanks! I will check out that page.

**Comment by kalefranz** [comment]
@davidslac going to close this issue here, since it's really not related to the conda code itself.  Feel free to keep discussing here though with @msarahan if you want.
