### ISSUE TITLE
Cannot update within an env

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2231]
From @seibert

    Rover:~ stan$ conda --version
    conda 4.0.2
    Rover:~ stan$ conda update requests
    Fetching package metadata: ....
    # All requested packages already installed.
    # packages in environment at /Users/stan/anaconda:
    #
    requests                  2.9.1                    py27_0
    Rover:~ stan$ source activate kershner
    discarding /Users/stan/anaconda/bin from PATH
    prepending /Users/stan/anaconda/envs/kershner/bin to PATH
    (kershner)Rover:~ stan$ conda update requests
    Fetching package metadata: ....
    Solving package specifications: ...........

    Error: 'conda' can only be installed into the root environment

**Comment by mcg1969** [comment]
I'm having trouble reproducing this here. Can you do a `conda update --debug requests` in that kershner environment?

**Comment by mcg1969** [comment]
So for some reason, `conda-env` is in that environment. That's what it is choking on. The error message doesn't make that clear but neither `conda` _nor_ `conda-env` are supposed to be installed outside of root. It's not clear how that happened, but my hope is that removing it will fix your problem.
