### ISSUE TITLE
conda update conda failing due to md5 mismatch

### ISSUE THREAD

**Issue by flybonzai** [conda/conda#2236]
Any new environments I try to create (including updating my current one) fails with an error similar to the following:

(Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/osx-64/conda-4.0.4-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != f4763f3ffa7789fee3b8b6287a175771))

**Comment by talumbau** [comment]
+1 Linux 64-bit.

**Comment by mcg1969** [comment]
https://github.com/conda/conda/issues/2236

**Comment by talumbau** [comment]
@mcg1969  means: Please see: https://github.com/conda/conda/issues/2232

**Comment by mcg1969** [comment]
Ha ha! Yep.

**Comment by kalefranz** [comment]
#DowngradeToUpgrade
