### ISSUE TITLE
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/linux-64 [FIXED]

### ISSUE THREAD

**Issue by lyndb** [conda/conda#2241]
I am getting errors like:

Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/linux-64/conda-4.0.4-py27_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != b3d769833c59bae5ccc11fcbe2e96ba4)

With either Anaconda or Anaconda3 and conda 4.0.3 when I try to update any package.

Unbuntu 14.04 64 bit
conda 4.0.3

**Comment by lyndb** [comment]
Looks like the problem has resolved, at least for me.  Downgraded conda to 4.0.2, and then upgraded it to 4.0.4.

**Comment by mcg1969** [comment]
Yes, here's the full discussion: https://github.com/conda/conda/issues/2232#issuecomment-195125055

**Comment by kalefranz** [comment]
I'm going to reopen this issue for today so it's more visible if people are searching for it.

**Comment by kalefranz** [comment]
For anyone still coming across this thread needing the solution...

You need to back up to your previous version of conda, and then you can update to conda latest (right now 4.0.4).

The output of

    ls $(/conda/bin/conda info | grep cache | cut -d: -f2) | grep -E "^conda-\d"

should show you the version numbers available in your cache. Then from there, for example if 3.19.3 was the version number indicated

    conda install conda=3.19.3

You can also just install miniconda over the top of your current installation, and then also upgrade from there.  You can download the latest miniconda installer from this page: http://conda.pydata.org/miniconda.html

**Comment by kalefranz** [comment]
Actually, here's a better solution...

    conda list --revisions

Figure out which rev number you want to roll back to...

    conda install --revision NUMBER

**Comment by sebastian-luna-valero** [comment]
Hello,

Our travis builds are failing due to similar problem:
```
Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-acepack-1.3_3.3-r3.2.2_1.tar.bz2 (ba387b95acee58fa81e355e728c922ca != 37c504b279cb00d6bd45f2b27a15f92e)
```

We follow what is the documentation for travis:
http://conda.pydata.org/docs/travis.html

Specifically `conda update -q conda`. We could enforce the installation of `conda=3.19.3` but I guess that is a temporary solution and then we'll have to revert back to `conda update -q conda`.

What do you suggest?

Many thanks,
Sebastian.

**Comment by sebastian-luna-valero** [comment]
It's working now for me.

Many thanks!

**Comment by kalefranz** [comment]
The r packages issue was with anaconda.org.  Verified that it's now fixed for https://conda.anaconda.org/r/linux-64/r-bh-1.58.0_1-r3.2.2_0.tar.bz2
