### ISSUE TITLE
BUG: LinAlgError raised by scipy.linalg.svd for valid matrix

### ISSUE THREAD

**Issue by Eric89GXL** [conda/conda#2244]
There is some bug in Anaconda's build of `scipy` that causes a `LinAlgError` to be raised when computing SVDs using MKL. They happen frequently to me when doing SVDs of large matrices. The matrices do not have `inf` or `nan` in them, and I [have] (https://github.com/numpy/numpy/issues/1588) read [some] (https://github.com/scipy/scipy/issues/3868) relevant [issues] (https://github.com/scipy/scipy/issues/4994).

Bad file located [here] (https://staff.washington.edu/larsoner/bad.npy). Code to reproduce, assuming `numpy` (1.10.4), `scipy` (0.17), and `mkl` (11.3.1) are all installed:
```
from scipy import linalg
import numpy as np
bad = np.load('bad.npy')
linalg.svd(bad)
```
This error does not occur with OpenBLAS numpy/scipy installed via `conda`.

I have built my own versions of `numpy` and `scipy` linked to MKL from source, and I cannot reproduce the error.

If someone can share the `site.cfg` (and any other changes) that Anaconda uses to build with MKL as well as the Intel release version, I'm happy to see if I can reproduce the errors and maybe do some debugging/isolating myself.

**Comment by mcg1969** [comment]
This probably needs to be moved to Anaconda's issue page.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#695

**Comment by Eric89GXL** [comment]
Ahh sorry about the incorrect placement, thanks for the move @kalefranz
