### ISSUE TITLE
conda list ImportError: cannot import name HTTPSHandler

### ISSUE THREAD

**Issue by KevKeyingLi** [conda/conda#2245]
when using conda list, I get the following

```
    userA ~ $ conda list
    \# packages in environment at /Users/userA/anaconda2:
    #
    Traceback (most recent call last):
    File "/Users/userA/anaconda2/bin/pip", line 4, in <module>
      import pip
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
      from pip.vcs import git, mercurial, subversion, bazaar  # noqa
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
      from pip.index import Link
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/index.py", line 29, in <module>
      from pip.wheel import Wheel, wheel_ext
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
      from pip._vendor.distlib.scripts import ScriptMaker
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
      from .compat import sysconfig, detect_encoding, ZipFile
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
      from urllib2 import (Request, urlopen, URLError, HTTPError,
    ImportError: cannot import name HTTPSHandler
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

      https://github.com/conda/conda/issues

    Include the output of the command 'conda info' in your report.


    Traceback (most recent call last):
    File "/Users/userA/anaconda2/bin/conda", line 5, in <module>
      sys.exit(main())
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
      args_func(args, p)
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
      args.func(args, p)
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
      json=args.json, show_channel_urls=args.show_channel_urls)
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
      add_pip_installed(prefix, installed, json=json)
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
      for pip_pkg in installed(prefix, output=output):
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
      args = pip_args(prefix)
    File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
      pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
    File "/Users/userA/anaconda2/lib/python2.7/subprocess.py", line 573, in check_output
      raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/Users/userA/anaconda2/bin/python', '/Users/userA/anaconda2/bin/pip', '-V']' returned non-zero exit status 1
```

The info for conda: 
        userA ~ $ conda info
        Using Anaconda Cloud api site https://api.anaconda.org
        Current conda install:

```
               platform : osx-64
          conda version : 3.19.1
    conda-build version : 1.19.0
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : /Users/userA/anaconda2  (writable)
    default environment : /Users/userA/anaconda2
       envs directories : /Users/userA/anaconda2/envs
          package cache : /Users/userA/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
      is foreign system : False
```

**Comment by kalefranz** [comment]
What is the output of this for you?

    /Users/baroc/anaconda2/bin/python /Users/baroc/anaconda2/bin/pip -V

**Comment by StephGS** [comment]
Traceback (most recent call last):
      File "/Users/userA/anaconda2/bin/pip", line 4, in <module>
        import pip
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
        from pip.vcs import git, mercurial, subversion, bazaar  # noqa
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
        from pip.index import Link
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/index.py", line 29, in <module>
        from pip.wheel import Wheel, wheel_ext
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
        from pip._vendor.distlib.scripts import ScriptMaker
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
        from .compat import sysconfig, detect_encoding, ZipFile
      File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
        from urllib2 import (Request, urlopen, URLError, HTTPError,
    ImportError: cannot import name HTTPSHandler

**Comment by kalefranz** [comment]
Ok so this is an issue with pip.  Let's keep digging...

This may be relevant: http://stackoverflow.com/questions/20688034/importerror-cannot-import-name-httpshandler-using-pip

Can you give me the output of `conda list`?  And, how did you install pip?  Did you use `conda install pip` or did you get it by some other method?

**Comment by StephGS** [comment]
The output of `conda list` is in the original post. Namely:

        userA ~ $ conda list
        \# packages in environment at /Users/userA/anaconda2:
        #
        Traceback (most recent call last):
        File "/Users/userA/anaconda2/bin/pip", line 4, in <module>
          import pip
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
          from pip.vcs import git, mercurial, subversion, bazaar  # noqa
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
          from pip.index import Link
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/index.py", line 29, in <module>
          from pip.wheel import Wheel, wheel_ext
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
          from pip._vendor.distlib.scripts import ScriptMaker
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
          from .compat import sysconfig, detect_encoding, ZipFile
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
          from urllib2 import (Request, urlopen, URLError, HTTPError,
        ImportError: cannot import name HTTPSHandler
        An unexpected error has occurred, please consider sending the
        following traceback to the conda GitHub issue tracker at:

          https://github.com/conda/conda/issues

        Include the output of the command 'conda info' in your report.


        Traceback (most recent call last):
        File "/Users/userA/anaconda2/bin/conda", line 5, in <module>
          sys.exit(main())
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
          args_func(args, p)
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
          args.func(args, p)
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
          json=args.json, show_channel_urls=args.show_channel_urls)
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
          add_pip_installed(prefix, installed, json=json)
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
          for pip_pkg in installed(prefix, output=output):
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
          args = pip_args(prefix)
        File "/Users/userA/anaconda2/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
          pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
        File "/Users/userA/anaconda2/lib/python2.7/subprocess.py", line 573, in check_output
          raise CalledProcessError(retcode, cmd, output=output)
        subprocess.CalledProcessError: Command '['/Users/userA/anaconda2/bin/python', '/Users/userA/anaconda2/bin/pip', '-V']' returned non-zero exit status 1

I didn't install pip separately. I encounter this problem yesterday, and reinstalled anaconda2. There is a pip pre-installed in the anaconda package right? 

Actually, I have read that post on StackOverFlow already. I did what is instructed in "OSX + homebrew users" solution, before I post it here. Apparently it didn't help. 

Is this problem related to openssl? The output didn't suggest that explicitly. Thanks

**Comment by kalefranz** [comment]
ohhh, right.  Can you try `conda list --explicit`? Or if that gives a stack trace too, `conda list --no-pip`?

**Comment by jakirkham** [comment]
If you run `env`, what do you see?

**Comment by StephGS** [comment]
@kalefranz  I see no trace. Here: 

	userA ~ $ conda list --explicit
	# This file may be used to create an environment using:
	# $ conda create --name <env> --file <this file>
	# platform: osx-64
	@EXPLICIT
	https://repo.continuum.io/pkgs/free/osx-64/abstract-rendering-0.5.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/alabaster-0.7.7-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/anaconda-2.5.0-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/anaconda-client-1.2.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/appnope-0.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/appscript-1.0.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/argcomplete-1.0.0-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/astropy-1.1.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/babel-2.2.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/backports_abc-0.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/beautifulsoup4-4.4.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/bitarray-0.8.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/blaze-core-0.9.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/bokeh-0.11.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/boto-2.39.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/bottleneck-1.0.0-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cdecimal-2.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cffi-1.2.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/clyent-1.2.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/colorama-0.3.6-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/conda-3.19.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/conda-build-1.19.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/conda-env-2.4.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/configobj-5.0.6-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cryptography-1.0.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/curl-7.45.0-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cycler-0.9.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cython-0.23.4-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/cytoolz-0.7.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/datashape-0.5.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/decorator-4.0.6-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/docutils-0.12-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/dynd-python-0.7.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/enum34-1.1.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/et_xmlfile-1.0.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/fastcache-1.0.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/flask-0.10.1-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/freetype-2.5.5-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/funcsigs-0.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/futures-3.0.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/gevent-1.0.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/gevent-websocket-0.9.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/greenlet-0.4.9-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/grin-1.2.1-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/h5py-2.5.0-np110py27_4.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/hdf5-1.8.15.1-2.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/idna-2.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipaddress-1.0.14-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipykernel-4.2.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipython-4.0.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipython-notebook-4.0.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipython-qtconsole-4.0.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipython_genutils-0.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ipywidgets-4.1.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/itsdangerous-0.24-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jbig-2.1-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jdcal-1.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jedi-0.9.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jinja2-2.8-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jpeg-8d-1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jsonschema-2.4.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jupyter-1.0.0-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jupyter_client-4.1.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jupyter_console-4.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/jupyter_core-4.0.6-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/launcher-1.0.0-3.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/libdynd-0.7.1-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/libpng-1.6.17-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/libtiff-4.0.6-1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/libxml2-2.9.2-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/libxslt-1.1.28-2.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/llvmlite-0.8.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/lxml-3.5.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/markupsafe-0.23-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/matplotlib-1.5.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/mistune-0.7.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/mkl-11.3.1-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/mkl-service-1.1.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/multipledispatch-0.4.8-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/nbconvert-4.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/nbformat-4.0.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/networkx-1.11-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/nltk-3.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/node-webkit-0.10.1-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/nose-1.3.7-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/notebook-4.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/numba-0.23.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/numexpr-2.4.6-np110py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/numpy-1.10.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/odo-0.4.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/openpyxl-2.3.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/openssl-1.0.2f-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pandas-0.17.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/path.py-8.1.2-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/patsy-0.4.0-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pep8-1.7.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pexpect-3.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pickleshare-0.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pillow-3.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pip-8.0.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ply-3.8-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/psutil-3.4.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ptyprocess-0.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/py-1.4.31-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyasn1-0.1.9-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyaudio-0.2.7-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pycosat-0.6.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pycparser-2.14-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pycrypto-2.6.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pycurl-7.19.5.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyflakes-1.0.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pygments-2.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyopenssl-0.15.1-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyparsing-2.0.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyqt-4.11.4-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pytables-3.2.2-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pytest-2.8.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/python-2.7.11-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/python-dateutil-2.4.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/python.app-1.2-py27_4.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pytz-2015.7-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyyaml-3.11-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/pyzmq-15.2.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/qt-4.8.7-1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/qtconsole-4.1.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/readline-6.2-2.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/redis-2.6.9-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/redis-py-2.10.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/requests-2.9.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/rope-0.9.4-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/scikit-image-0.11.3-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/scikit-learn-0.17-np110py27_2.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/scipy-0.17.0-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/setuptools-19.6.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/simplegeneric-0.8.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/singledispatch-3.4.0.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sip-4.16.9-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/six-1.10.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/snowballstemmer-1.2.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sockjs-tornado-1.0.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sphinx-1.3.5-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sphinx_rtd_theme-0.1.9-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/spyder-2.3.8-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/spyder-app-2.3.8-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sqlalchemy-1.0.11-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sqlite-3.9.2-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/ssl_match_hostname-3.4.0.2-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/statsmodels-0.6.1-np110py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/sympy-0.7.6.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/terminado-0.5-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/tk-8.5.18-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/toolz-0.7.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/tornado-4.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/traitlets-4.1.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/unicodecsv-0.14.1-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/werkzeug-0.11.3-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/wheel-0.26.0-py27_1.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/xlrd-0.9.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/xlsxwriter-0.8.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/xlwings-0.6.4-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/xlwt-1.0.0-py27_0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/xz-5.0.5-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/yaml-0.1.6-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/zeromq-4.1.3-0.tar.bz2
	https://repo.continuum.io/pkgs/free/osx-64/zlib-1.2.8-0.tar.bz2

**Comment by StephGS** [comment]
@jakirkham You mean `conda env` or `conda env list`? These two show no erroneous output. If you mean `env`. It outputs: 

	userA ~ $ env
	GIT_PS1_SHOWDIRTYSTATE=1
	TERM_PROGRAM=Apple_Terminal
	SHELL=/bin/bash
	TERM=xterm-256color
	TMPDIR=/var/folders/mf/n_kvr5h5603496gmm3sx9wqr0000gn/T/
	Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.7J12RE6r2a/Render
	TERM_PROGRAM_VERSION=361.1
	TERM_SESSION_ID=3A49ADDD-1632-4EF9-BFBF-2C92F6FF5C6D
	USER=userA
	SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.BfXUTbu3Mu/Listeners
	__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
	PATH=/Users/userA/anaconda2/bin:/Users/userA/anaconda2/bin:/Users/userA/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/bin/python:/Users/userA/Spark/spark-1.6.0-bin-hadoop2.6/bin
	PWD=/Users/userA
	LANG=en_US.UTF-8
	XPC_FLAGS=0x0
	PS1=\[\033[0;35m\]\u\[\033[0;32m\]$(__git_ps1)\[\033[0;34m\] \W $ \[\033[0m\]
	XPC_SERVICE_NAME=0
	SHLVL=1
	HOME=/Users/userA
	LOGNAME=userA
	_=/usr/bin/env

**Comment by kalefranz** [comment]
`conda list` no longer invokes `pip`.  Closing.
