### ISSUE TITLE
Update breaks numpy: ImportError: libmkl_intel_lp64.so: cannot open...

### ISSUE THREAD

**Issue by k7hoven** [conda/conda#2248]
After updating numpy with `conda update numpy`as follows: 

 
```
The following packages will be UPDATED:
       numpy: 1.10.2-py35_0 --> 1.10.4-py35_1
``` 

Importing numpy gives an error:
```
k7hoven@nbe-dr001 ~ % python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/05/k7hoven/unix/miniconda3/lib/python3.5/site-packages/numpy/__init__.py", line 184, in <module>
    from . import add_newdocs
  File "/u/05/k7hoven/unix/miniconda3/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/u/05/k7hoven/unix/miniconda3/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/u/05/k7hoven/unix/miniconda3/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/u/05/k7hoven/unix/miniconda3/lib/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
>>> 
```

After doing a `conda install nomkl`, numpy imports normally:

```
The following NEW packages will be INSTALLED:

    nomkl: 1.0-0                   

The following packages will be UPDATED:

    numpy: 1.10.4-py35_1      --> 1.10.4-py35_nomkl_1      [nomkl]
    scipy: 0.17.0-np110py35_2 --> 0.17.0-np110py35_nomkl_2 [nomkl]
```

This is on Ubuntu 14.04:
```
k7hoven@nbe-dr001 ~ % uname -a
Linux nbe-dr001 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Or can this be a numpy issue?

**Comment by hcarvalhoalves** [comment]
Same error for me. Can only use `nomkl` builds and can't figure out the exact combination of numpy/pandas/scikit-learn builds that won't break.

`conda` has been a mess lately, this is around the 5th time one of my CI builds break due to mkl non-sense. I'm almost giving up and just compiling my packages by hand + docker images because not only conda dependency resolution is less than deterministic, they also push broken builds to the official repo.

**Comment by NelleV** [comment]
I am running into similar issues. I've resorted to uninstalling all packages from the conda environment and pip installing them. It fixed my issues.

**Comment by ahmadia** [comment]
Is this being tracked anywhere by Continuum?

**Comment by ahmadia** [comment]
So I was able to resolve this issue on my end because we were using `conda` for a non-networked install and `conda install numpy.bzip2` doesn't resolve dependencies (even though the dependencies are available in the package). @mcg1969 - Is this work a deeper look?

**Comment by kalefranz** [comment]
All mkl-related issues should have long-ago been fixed. If issues persist, definitely need to know about them. Probably best to file a new issue actually. But will leave this open for another few days yet.

**Comment by mcg1969** [comment]
That's not the problem here, Kale... the problem is that a tarball install doesn't include dependencies. It's effectively a force install, and that's known and intended behavior. We've been talking about changing that. But if you want to do a non-networked install with dependency resolution you have to build a local channel.

**Comment by mcg1969** [comment]
Or rather, that was @ahmadia's problem; it may not have been the original author's.

**Comment by ahmadia** [comment]
A local channel? Like this? http://conda.pydata.org/docs/custom-channels.html

That might address our use case, which is to set up an offline install of a set of packages and make sure we're not missing any dependencies. It would be a nice-to-have if the packages could be resolved for us, although I think we could do something similar with a `conda list --export` when online.

**Comment by ahmadia** [comment]
Thanks for the quick feedback @kalefranz / @mcg1969 - this is closed/resolved on my end.

**Comment by mcg1969** [comment]
Yes, that's the setup. I definitely recommend the custom channel approach described there for offline installs.
