### ISSUE TITLE
Failed to update conda & anaconda

### ISSUE THREAD

**Issue by mathursomyak** [conda/conda#2250]
C:\Users\skmathur\Anaconda>conda update anaconda

Fetching package metadata: C:\Users\skmathur\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Users\skmathur\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\skmathur\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\resolve.py", line 870, in install
    specs, preserve = self.install_specs(specs, installed or [], update_deps)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\resolve.py", line 851, in install_specs
    limit, preserve = self.bad_installed(installed, specs)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\resolve.py", line 819, in bad_installed
    solution = C.sat(constraints)
  File "C:\Users\skmathur\Anaconda\lib\site-packages\conda\logic.py", line 422, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
TypeError: list expected

C:\Users\skmathur\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 4.0.4
  conda-build version : 1.2.0
       python version : 2.7.6.final.0
     requests version : 2.9.1
     root environment : C:\Users\skmathur\Anaconda  (writable)
  default environment : C:\Users\skmathur\Anaconda
     envs directories : C:\Users\skmathur\Anaconda\envs
        package cache : C:\Users\skmathur\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Users\skmathur\Anaconda>C:\Users\skmathur\Anaconda>conda update anaconda

**Comment by mcg1969** [comment]
I think this is identical to https://github.com/conda/conda/issues/2229 here. I'd like to merge these two simply because between the two of you we might be able to get this figured out.

**Comment by mcg1969** [comment]
Please head over to https://github.com/conda/conda/issues/2229 for further discussion.
