### ISSUE TITLE
Support of resuming download

### ISSUE THREAD

**Issue by show0k** [conda/conda#2266]
If a download is interrupted half way through, there is no way to continue the download. If the download take to much time it will be re-started from scratch. Worse, if an install of multiple packages is interrupted, all packages will be downloaded again, even if it last only one package.

For those who have to work with mobile internet connection, it's painful.

**Comment by kalefranz** [comment]
Packages are now only downloaded once.  If the tarball download succeeds, but the download of another tarball fails, all successful downloads won't be repeated.

**Comment by CTimmerman** [comment]
That's not resuming a download, is it? I wrote a simple function for Pip, but couldn't figure out Pip's codebase. Perhaps Conda is easier to understand.

https://gist.github.com/CTimmerman/ccf884f8c8dcc284588f1811ed99be6c
