### ISSUE TITLE
OpenMPI package broken on OSX?

### ISSUE THREAD

**Issue by fperez** [conda/conda#2277]
Hi,

I just installed `mpi4py`, which pulls in `openmpi` on OSX El Cap from the default channel:

```
Kerbin[~]> conda list | grep mpi
mpi4py                    2.0.0                    py35_0
openmpi                   1.6.3                         0
```

but when I run _any_ `mpiexec` call, I get this:

```
Kerbin[log]> mpiexec -V
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orterun:version
But I couldn't open the help file:
    /opt/anaconda1anaconda2anaconda3/share/openmpi/help-orterun.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
```

With an actual command to execute, there's a bit more info:

```
Kerbin[log]> mpiexec -n 4 /Users/fperez/usr/conda/bin/python -m ipyparallel.engine --profile-dir /Users/fperez/.ipython/profile_default --cluster-id  --log-to-file --log-level=20
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /opt/anaconda1anaconda2anaconda3/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
[Kerbin.local:88088] [[INVALID],INVALID] ORTE_ERROR_LOG: Error in file runtime/orte_init.c at line 79
[Kerbin.local:88088] [[INVALID],INVALID] ORTE_ERROR_LOG: Error in file orterun.c at line 694
```

A bit of platform info:

```
 'os_name': 'posix',
 'platform': 'Darwin-15.3.0-x86_64-i386-64bit',
 'sys_executable': '/Users/fperez/usr/conda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, '
                '11:24:55) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}
```

Any input/ideas much appreciated.

**Comment by sccolbert** [comment]
ping @ilanschnell

**Comment by mingwandroid** [comment]
Hi @fperez 

I built a new openmpi on my 10.11 OS X and uploaded it to my anaconda.org channel for you until @ilanschnell reads his messages. If you want to try it out:

    conda install -c https://conda.anaconda.org/rdonnelly openmpi --force

**Comment by fperez** [comment]
Thanks! For now I got going with installing openmpi via homebrew and mpi4py
with pip.

But I figured it would be a good idea to report it so you guys could fix
the package.

**Comment by tkchris93** [comment]
Has there been any progress or any other work arounds for this? When I tried the work around suggested by @mingwandroid I got the following output
```
mac-pro-2:Documents acme$ mpiexec -V
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orterun:version
But I couldn't open the help file:
    /Users/rdonnelly/mc3-3.5/envs/_build/share/openmpi/help-orterun.txt: No such file or directory.  Sorry!
```
Was there a step I missed?

**Comment by fperez** [comment]
My workaround was to use homebrew for openmpi, for now foregoing anaconda.  It meant pulling mpi4py with pip, but so be it, that one is a quick install... I do hope the upstream anaconda package does get fixed eventually...

**Comment by tkchris93** [comment]
I'm new to OS X, so sorry for the confusion on my part. I got it working through homebrew + pip. Thank you!

**Comment by fperez** [comment]
No worries, glad it worked out!

**Comment by msarahan** [comment]
Not a ready-made solution for you yet, but I have started putting together a package on conda-forge: https://github.com/conda-forge/staged-recipes/pull/557.  I know we're all busy, but if anyone has time to add to that PR, I welcome contributions.

**Comment by gwhammett** [comment]
I had the same problem when trying to use conda to install mpi4py on my Mac OS X.   It appears that the conda installation of openmpi is not correct.

A fix that worked for me is a variant of the workaround that fperez posted above.  Instead of homewbrew, I used macports to install openmpi, and then I used pip to install mpi4py.  (It is important that conda's openmpi *not* be installed, because its erroneous files might be in the path before where the macports version of openmpi will be.)  Here is my recollection of the main commands I did:

sudo port install openmpi
# make openmpi's wrapper commands (like mpiexec) the default by doing:
sudo port select --set mpi openmpi-mp-fortran
pip install mpi4py

**Comment by fperez** [comment]
Any updates on this? I just tested again with a fresh environment:

```
((mpi)) denali[nersc]> conda list
# packages in environment at /Users/fperez/usr/conda/envs/mpi:
#
mpi4py                    2.0.0                    py35_0  
openmpi                   1.6.3                         0  
openssl                   1.0.2h                        2  
pip                       8.1.2                    py35_0  
python                    3.5.2                         0  
readline                  6.2                           2  
setuptools                25.1.6                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
zlib                      1.2.8                         3  
```

 and I'm getting the exact same error I originally reported... Should I file this elsewhere?

For now I'll keep using brew, but it's a bummer not to be able to have reliable, self-contained conda envs for MPI work...

**Comment by msarahan** [comment]
Hi @fperez, we have mpich at conda-forge: https://github.com/conda-forge/mpich-feedstock

I'm not familiar with whether that's compatible with openmpi.  Is that a solution for you?  I will add this to the package build list, regardless, but we are swamped.

**Comment by fperez** [comment]
Thanks @msarahan! For now I can just continue using brew, that's OK.  It's just that when I advertise Anaconda to HPC colleagues, it's a bit awkward to have to keep saying "... and for MPI, we need to switch to brew/c-forge/etc because the built-in package is completely broken and doesn't even start" :)

So no worries, I'll just keep an eye on the issue and hopefully the fixes will eventually propagate to the official package.  I'm hopeful the problem isn't too hard to fix, given that the Homebrew build works fine.  Perhaps you guys can compare your build to that one?

**Comment by msarahan** [comment]
@fperez the issue at hand on the mac is the fortran compiler.  Our GCC package needs some updating pretty severely.

Our error is

```
configure:32570: checking if Fortran compiler works
configure:32599: gfortran -o conftest   -arch x86_64  conftest.f  >&5
configure:32599: $? = 0
configure:32599: ./conftest
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/work/openmpi-1.10.3/./conftest
  Reason: image not found
./configure: line 4859: 30835 Trace/BPT trap: 5       ./conftest$ac_exeext
```

If you can help resolve that, or if we can drop fortran support for now, I could get a package out faster.  I don't know if it is an RPATH problem with our gcc package, or a missing flag to the openmpi configuration tests.

CC @mingwandroid - you might know best here.

**Comment by msarahan** [comment]
this is the configure line:

```
Configured with: ./configure --prefix=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_pl
ac/gcc --with-gxx-include-dir=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac/gcc/i
nclude/c++ --bindir=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac/bin --datarootd
ir=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac/share --libdir=/Users/msarahan/m
iniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac/lib --with-gmp=/Users/msarahan/miniconda2/conda-bld/
openmpi_1472266095137/_b_env_placehold_plac --with-mpfr=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_
b_env_placehold_plac --with-mpc=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac --w
ith-isl=/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac --with-cloog=/Users/msaraha
n/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_n
ames -Wl,-L/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137/_b_env_placehold_plac/lib -Wl,-L/usr/lib' --wi
th-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/msarahan/miniconda2/conda-bld/openmpi_1472266095137
/_b_env_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
```

**Comment by fperez** [comment]
Mmh, I'm using gfortran from homebrew, so I can't really comment on the conda gfortran.  And sadly I'm not really sure about the problem above, sorry not to be of more help...

Thanks for looking into it!

**Comment by mingwandroid** [comment]
lt;dr: SIP broke autotools!

@msarahan, you tried to do this build on El Capitan I guess? If so that's SIP getting in your way. One of my first commits to conda was to add an extra rpath during the build and remove it at the end to avoid these issues, but it caused trouble, exercising bugs in some versions of install_name_tool leading to broken Mach-O files.

One 'fix' may be to disable SIP but you may need to ask whether that's allowed on a company MBP. The other 'fix' is to build it on OS X 10.7 which I'll try to do when I get a chance.

**Comment by CraigLoomis** [comment]
openmpi puts the _build_ directory in libraries/executables. See https://www.open-mpi.org/faq/?category=building#installdirs

The quick fix is to set OPAL_PREFIX to the anaconda root. If you use conda envs, OPAL_PREFIX=$CONDA_PREFIX seems to do the trick.

For the future, could anaconda package builders arrange to do this? Would be nice.

**Comment by rainwoodman** [comment]
@CraigLoomis  you method didn't work. I just tried this with @nbatta. The program compiles but when running it cannot find the dynlib files for mpi. The cleanest approach so far is to make a symlink to /opt/anaconda1anaconda2anaconda3.

**Comment by fperez** [comment]
Ping... any progress on this one? 

I would suggest removing the openmpi/mpi4py packages from anaconda altogether if it's not possible to fix this, at least on osx... Right now I think it's more confusing than beneficial, since it will stop all attempts to use mpi via conda for osx users.

BTW, since the homebrew build works fine, perhaps you could crib some of their build pipeline for conda?

In any case, thanks for looking into it!

**Comment by msarahan** [comment]
Does the conda forge recipe work satisfactorily?

If it does, I am happy to port that over, but am pretty overextended for any actual development.

**Comment by rainwoodman** [comment]
Oh please don't remove these two packages. We depend on having mpi4py and openmpi in anaconda to scale our software down from NERSC to MAC laptops. 

It feels like it is just a little bit of a push to get this right. Besides the OPAL env, one also need to set LD_LIBRARY_PATH etc to get it working. rpath probably won't be the right solution to solve this. 
For now the easiest explanatoin to the user is to say, 

```
conda install mpi4py
ln -s path_to_conda_directory /opt/anaconda1anaconda2anaconda3
```

Maybe the author of mpi4py @dalcinl have some wisdom on this to share?

**Comment by rainwoodman** [comment]
Here is a list of environment variables that can be fiddled.

https://github.com/open-mpi/ompi/blob/9c3ae64297e034b30cb65298908014764216c616/opal/mca/installdirs/env/opal_installdirs_env.c#L61

**Comment by fperez** [comment]
@rainwoodman, I meant removing them from the OSX distribution only: note that right now, they simply don't work *at all*.  I'm not sure how you can be using conda to help your OSX users, since `mpirun` simply fails to run at all on OSX.

**Comment by rainwoodman** [comment]
It works if they add that symlink.  It is very unfortunate, but most of scholars and students we are working with use Macs.
I am willing to look at this and fix it, at least ensure it works on my wife's Mac.

But the bar to conda packaging seems to be high. Do you know of a document that describes how to rebuild conda packages on OSX? What is the best way to start? Any recommendations @msarahan ?

**Comment by msarahan** [comment]
@rainwoodman Continuum's recipe for this is at https://github.com/ContinuumIO/anaconda-recipes/tree/master/openmpi

It might be sufficient to just add the symlink in build.sh - are you familiar with building conda packages at all?  Feel free to ping me if you have issues.

Submitting a PR against that repo is the best way to get changes incorporated into Continuum's packages.  If you submit a PR against that repository, please ping me.  I will ensure that it is handled quickly.

**Comment by fperez** [comment]
Got it @rainwoodman, that helps! It would indeed be great to have this sorted out if it's only that...

FWIW, I just tested here (removing homebrew/pip install, putting back conda mpi4py/openmpi, manually symlinking) and it seems to be ok so far.  Haven't done more extensive testing yet but this is encouraging info.

If that missing symlink is the whole story, this should be much easier to fix than perhaps originally thought, and we could have a conda that works for MPI!

Thanks :)

**Comment by rainwoodman** [comment]
If macs behave like linux then a user is not supposed to be able to create files in /opt. So we really need to somehow change the prefix at runtime. 

To my surprise, the mpi on linux I get is mpich2. Is there a reason why on Mac it is openmpi instead?

**Comment by rainwoodman** [comment]
@msarahan what is the relation between anaconda-recipe and conda-recipe?

**Comment by rainwoodman** [comment]
I wonder the magic build/detect_binary_files_with_prefix is the key to the issue.

**Comment by rainwoodman** [comment]
Adding that single line to meta.yaml fixes the issue. No longer needs the symlink.

Incidentally this change was also proposed by @minrk for conda-forge here https://github.com/conda-forge/staged-recipes/pull/1490 

I will file a PR to Continuumio/anaconda-recipes.

**Comment by ilanschnell** [comment]
I've rebuild openmpi with the `detect_binary_files_with_prefix : true` (thanks @rainwoodman for https://github.com/ContinuumIO/anaconda-recipes/pull/68).  It is now available.

**Comment by msarahan** [comment]
``detect_binary_files_with_prefix`` is implicitly True on conda-build 2.0+ - it went from opt-in to opt-out.

I have tested this locally with ``mpiexec -V`` and it appears to be in order.  I'm going to close this issue for now, but please reopen it if this doesn't work for you for any reason.

Thanks @rainwoodman for doing the leg-work on finding the necessary fix here, and thanks @ilanschnell for closing the loop.  Closing this issue.

**Comment by fperez** [comment]
Awesome, thanks everyone!! Much appreciated, this is great.

Ping @mlhenderson who was bitten by this yesterday: you can roll back the homebrew/pip solution and pull in again mpi4py from conda, that way you'll get proper updates henceforth.

**Comment by rainwoodman** [comment]
@ilanschnell 

I noticed the updated version is not visible at

https://anaconda.org/anaconda/openmpi/files

(We just had an user noted about still needing to install mpi from homebrew)

Is this an issue?

**Comment by ilanschnell** [comment]
I not sure about anaconda.org, but what matters is https://repo.continuum.io/pkgs/free/

**Comment by rainwoodman** [comment]
Thanks for the clarification. There seems to be a lot of infrastructures..

**Comment by rainwoodman** [comment]
With the current version (1.6.3-1) of openmpi, mpicc processes unrunable executables.

The error is due to the executable tries to look for libmpi from `@rpath/../lib` but libmpi is actually under the conda root.

However, 

1. mpi4py works fine.

2. If I prefix `LD_LIBRARY_PATH`=conda_root/lib the executable runs.

3. An extension modules that links against openmpi, works after being installed (via pip) to the conda environment. (sometimes adding `LD_LIBRARY_PATH` helps the configue scripts to run through cross compilation detection.)

I am not sufficiently experienced with path handling in macs to find a proper solution. This is not very important since we never intended to use mpicc from conda package to build an executable ;; we only use it to build python extensions which still works after they are installed to the conda env. But it's worth keeping an record of this here.

**Comment by rainwoodman** [comment]
With the new cross compilation tools we shall no longer have this issue. But the new openmpi has to be merged to the default anaconda channel first.
