### ISSUE TITLE
Problem with loading order of `tensorflow` and `scipy.misc`

### ISSUE THREAD

**Issue by ritsu1228** [conda/conda#2288]
Not sure if this is the right place to ask. I am encountering a weird problem with loading `tensorflow` and `scipy.misc`.

If I load `scipy.misc` first, I will have no problem with `imread`,

```
import scipy.misc
import tensorflow as tf

im = scipy.misc.imread('1.jpg')
```

`im` will be a normal `array` with `dtype=uint8`.

However, if I load `tensorflow` first,

```
import tensorflow as tf
import scipy.misc

im = scipy.misc.imread('1.jpg')
```

`im` will be something like `array(<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=178x218 at 0x7F85ED8AA050>, dtype=object)`.

[StackOverflow post](http://stackoverflow.com/questions/16612293/scipy-misc-imread-creates-an-image-with-no-size-or-shape) suggests this could be caused by incomplete installation of `PIL` or `pillow`. However, after I reinstall `pillow` as suggested, the problem persists. Actually running `ldd` on `_imaging.so`, I noticed the bundled `libjpeg` was used.

I installed `pillow`, `scipy` and `numpy` all through `conda install`. I built `tensorflow` from source myself and installed it using `pip install`. Would this cause a conflict?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1689
