### ISSUE TITLE
Problem with conda install of package 'brian2' for win64

### ISSUE THREAD

**Issue by spala-mosxou** [conda/conda#2293]
While trying to install brian simulator with the conda install at win64 system I got the following error output:
![problem](https://cloud.githubusercontent.com/assets/6384503/13918037/ed3b9f2e-ef64-11e5-8c39-92f72a704089.jpg)

**Comment by kalefranz** [comment]
Code path no longer exists in recent versions of conda.  Should be long-ago resolved.
