### ISSUE TITLE
The conda recipe in this repo is version-less

### ISSUE THREAD

**Issue by pelson** [conda/conda#2298]
https://github.com/conda/conda/blob/master/conda.recipe/meta.yaml

Doesn't contain a package/version section. That sounds like a very bad idea. Please close if this was intentional though.

**Comment by groutr** [comment]
I should contain a version.  It technically is not a valid conda recipe without package/version.

**Comment by groutr** [comment]
Looks like it was removed in this commit https://github.com/conda/conda/commit/cf1fded5ae8f95496fd43257386698e3f86ae048#diff-bd134fa847b11c75aba174f834eb80df

**Comment by kalefranz** [comment]
When this ticket was created the version was written in the `build.sh` file using the `__conda_version__.txt` file, or whatever that was at the time.  It's now switched to using the jinja2 conda-build has built in.
