### ISSUE TITLE
TCL / TK isn't properly configured

### ISSUE THREAD

**Issue by dusans** [conda/conda#2299]
**I have**: Python 2.7.11 :: Anaconda 2.4.0 (64-bit)
### Test script:

``` python
from Tkinter import *


class Controler(object):
    def __init__(self):
        self.root = Tk(className="Name")


def main():
    co = Controler()

if __name__ == '__main__':
    main()
```
### Exception:

> Traceback (most recent call last):
>   File "c:\temp\anaconda_tk_bug\main.py", line 14, in <module>
>     main()
>   File "c:\temp\anaconda_tk_bug\main.py", line 11, in main
>     co = Controler()
>   File "c:\temp\anaconda_tk_bug\main.py", line 7, in **init**
>     self.root = Tk(className="Name")
>   File "c:\python\Python_27_64_anaconda\lib\lib-tk\Tkinter.py", line 1814, in **init**
>     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
> _tkinter.TclError: Can't find a usable init.tcl in the following directories:
>     {c:\dev\programs\system\PyCmd\tcl} c:/dev/programs/system/PyCmd/tcl8.5 c:/python/Python_27_64_anaconda/lib/tcl8.5 c:/python/lib/tcl8.5 c:/lib/tcl8.5 c:/python/library c:/library c:/tcl8.5.15/library c:/tcl8.5.15/library
### It works if i copy:
- \tcl\tcl8.5\
- \tcl\tk8.5\

to 
- \Lib\tcl8.5\
- \Lib\tk8.5\

**Comment by santegoeds** [comment]
I happened to look at this same issue on Linux yesterday.  I used `virtualenv` to create a new environment (`conda create` appears to do the right thing on Linux).

As a workaround I exported environment variable TCL_LIBRARY.  I'm just mentioning it here in case it's helpful for you too.

**Comment by dusans** [comment]
I forgot to mention. I'm using Windows 7 64 bit.

**Comment by hclivess** [comment]
same issue in win 7 64 bit

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1688
