### ISSUE TITLE
Improved documentation on the version comparison code

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#2304]
The current conda docs imply that the version comparison code mimics PEP 386:

http://conda.pydata.org/docs/spec.html#build-version-spec

This is out of date. In fact, thanks to @ukoethe, it mimics PEP 440, with some deliberate exceptions.

The [docstring for the VersionOrder class](https://github.com/conda/conda/blob/master/conda/version.py#L21-L127) is probably the best documentation we have for the current implementation, and should be added to the documentation somehow, preferably in its own section.

cc: @jseabold @cel4 @ukoethe #1107 #2297 #2300 #1601

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-docs#436
