### ISSUE TITLE
Conda Install Package error. Please help.

### ISSUE THREAD

**Issue by mayordwells** [conda/conda#2305]
I am trying to install some packages with conda but I got these errors. Please guide me

conda install -c https://conda.anaconda.org/auto bitstring
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
- bitstring -> python 2.7*
- conda -> conda-env
- conda -> pycosat
- conda -> python 2.7*
- conda -> pyyaml
- conda -> requests
- conda-env (target=conda-env-2.4.5-py35_0.tar.bz2) -> python 2.7_|3.3_|3.4_|3.5_
- pip (target=pip-8.1.1-py35_0.tar.bz2) -> python 2.7*
- pycosat (target=pycosat-0.6.1-py35_0.tar.bz2) -> python 2.6_|2.7_|3.3_|3.4_|3.5*
- python 3.5*
- pyyaml (target=pyyaml-3.11-py35_1.tar.bz2) -> python 2.6_|2.7_|3.3_|3.4_|3.5*
- requests (target=requests-2.9.1-py35_0.tar.bz2) -> python 2.6_|2.7_|3.3_|3.4_|3.5*
- setuptools (target=setuptools-20.3-py35_0.tar.bz2) -> python 2.6_|2.7_|3.3_|3.4_|3.5*
- wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7_|3.3_|3.4_|3.5_
  Use "conda info <package>" to see the dependencies for each package.

**Comment by msarahan** [comment]
You are trying to install a Python-2.7-only package from that channel into
a Python 3.5 environment.  That won't work.  You need to find a different
source of that package - one that is built for Python 3.5.

If you don't see your platform at https://anaconda.org/search?q=bitstring,
I recommend you use pip to install this package instead.

HTH,
Michael

**Comment by mayordwells** [comment]
Yes I pip installed but got this error instead. Is there a bitstring package built for Python 3.5? I am getting this same error for some other packages as well
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "//anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "/Users/Mayor/Documents/PythonPractices/Ex_Files_Python_3_EssT/Exercise Files/17 Modules/modules.py", line 7, in <module>
    import bitstring
ImportError: No module named 'bitstring'
>>>

**Comment by mayordwells** [comment]
Issue Resolved. Thank you. 
Here's what i did.
pip install --upgrade pip
Requirement already up-to-date: pip in /anaconda/lib/python3.5/site-packages
pip install bitstring

**Comment by snowman907** [comment]
Hello, I think I have the same problem:
When trying to install opencv using conda:
`conda install -c https://conda.anaconda.org/menpo opencv`
#I am currently running python 3.5, so I have a dependency problem like described above. Do I need to downgrade to python 2.7 in order to use conda to install opencv.
Also, I tried 
```
C:\Users\Administrator>pip install opencv
Collecting opencv Could not find a version that satisfies the requirement opencv (from versions:  )
No matching distribution found for opencv
 ```
Thanks for the help!

**Comment by snowman907** [comment]
Ok, I figured out, if I want to install gdal, to just stay away from Python 3. There is opencv3, but there is no gdal3.

**Comment by aacharya14** [comment]
I'm trying to downgrade my version of scipy using
`conda install --force scipy=0.17.0`
and get this error:
`CondaError: dist_name is not a valid conda package: old`

does anyone know how I can fix this?

**Comment by ivankeller** [comment]
same issue while trying to upgrade scikit-learn:
```
$ conda install scikit-learn
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/ivan/anaconda:

The following packages will be UPDATED:

    conda:        4.3.4-py27_0       --> 4.3.9-py27_0      
    mkl:          11.3.3-0           --> 2017.0.1-0        
    numexpr:      2.5.2-np110py27_1  --> 2.6.1-np111py27_2 
    numpy:        1.10.4-py27_2      --> 1.11.3-py27_0     
    scikit-learn: 0.17.1-np110py27_2 --> 0.18.1-np111py27_1
    scipy:        0.17.1-np110py27_1 --> 0.18.1-np111py27_1

Proceed ([y]/n)? y

CondaError: dist_name is not a valid conda package: rfoo

```
