### ISSUE TITLE
conda: xlwings installation failed

### ISSUE THREAD

**Issue by dmarsw** [conda/conda#2307]
Proceed ([y]/n)? y

menuinst-1.3.2 100% |###############################| Time: 0:00:00 210.01 kB/s
Fetching packages ...
vs2008_runtime 100% |###############################| Time: 0:00:01 575.86 kB/s
comtypes-1.1.2 100% |###############################| Time: 0:00:00 259.30 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00 224.57 kB/s
pytz-2016.2-py 100% |###############################| Time: 0:00:00 301.52 kB/s
pywin32-220-py 100% |###############################| Time: 0:00:23 586.11 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 243.40 kB/s
requests-2.9.1 100% |###############################| Time: 0:00:01 422.01 kB/s
setuptools-20. 100% |###############################| Time: 0:00:02 364.44 kB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00 267.91 kB/s
conda-4.0.5-py 100% |###############################| Time: 0:00:00 272.52 kB/s
pip-8.1.1-py27 100% |###############################| Time: 0:00:03 517.17 kB/s
xlwings-0.7.0- 100% |###############################| Time: 0:00:01 435.28 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Programs\Coding\Anaconda\Scripts\conda-script.py", line 4, in <module
>
    sys.exit(main())
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\cli\main.py", line 2
07, in main
    args_func(args, p)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\cli\main.py", line 2
12, in args_func
    args.func(args, p)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\cli\common.py", line
 609, in inner
    return func(args, parser)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\cli\main_install.py"
, line 51, in execute
    install.install(args, parser, 'install')
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\cli\install.py", lin
e 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\plan.py", line 531,
in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\instructions.py", li
ne 156, in execute_instructions
    cmd(state, arg)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\instructions.py", li
ne 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Programs\Coding\Anaconda\lib\site-packages\conda\install.py", line 65
8, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'

conda info
Current conda install:

             platform : win-32
        conda version : 3.11.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Programs\Coding\Anaconda  (writable)
  default environment : C:\Programs\Coding\Anaconda
     envs directories : C:\Programs\Coding\Anaconda\envs
        package cache : C:\Programs\Coding\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by msarahan** [comment]
Yikes, that's a very old version of Conda.  Please try to update conda by itself first:

```
conda update conda
conda install xlwings
```

**Comment by dmarsw** [comment]
I noticed that after I posted the issue. I'm installing the lastest
version and will close this bug if xlwings now installs

-----Original Message-----

**Comment by dmarsw** [comment]
Successful xlwings install w/Anaconda2-2.5.0.
