### ISSUE TITLE
/usr/bin/ld: cannot find -lmkl_lapack95_lp64

### ISSUE THREAD

**Issue by TT-Toolbox** [conda/conda#2308]
In the new Anaconda, with conda 4.0.5, 
the code that previously worked with cython compilation 

(from https://bitbucket.org/muxas/maxvolpy/)
now fails after python setup.py install on the linking stage:

```
gcc -pthread -shared -L/home/oem/miniconda2/lib -Wl,-rpath=/home/oem/miniconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/maxvolpy/_maxvol.o -L/home/oem/miniconda2/lib -L/home/oem/miniconda2/lib -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lpython2.7 -o build/lib.linux-x86_64-2.7/maxvolpy/_maxvol.so
/usr/bin/ld: cannot find -lmkl_lapack95_lp64
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lmkl_lapack95_lp64
collect2: error: ld returned 1 exit status
error: Command "gcc -pthread -shared -L/home/oem/miniconda2/lib -Wl,-rpath=/home/oem/miniconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/maxvolpy/_maxvol.o -L/home/oem/miniconda2/lib -L/home/oem/miniconda2/lib -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lpython2.7 -o build/lib.linux-x86_64-2.7/maxvolpy/_maxvol.so" failed with exit status 1
```

It seems that numpy was linked with -lmkl_lapack95_lp64 but it was not included with anaconda.
`conda install nomkl` 
fixes the problem, but it is not a good way to work without mkl.

**Comment by oseledets** [comment]
Any updates on that? 

It seems that the whole **numpy** package is broken: it was compiled with -lmkl_lapack95_lp64, but this library was not included in the package!!
Manually fixing numpy/distutils/system_info.py saves the day, but again, not for distribution of the stuff.

**Comment by hobboy** [comment]
I've also run into this issue, `install nomkl`solves the problem but this is less than ideal.

**Comment by kalefranz** [comment]
These issues have been fixed in more recent Anaconda releases I think.

**Comment by kalefranz** [comment]
If I'm wrong, please file a new issue at http://github.com/ContinuumIO/anaconda-issues
