### ISSUE TITLE
Missing consistent way to get the full path of active env (on Windows and Unix)

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2312]
@tadeu commented on [Wed Nov 04 2015](https://github.com/conda/conda-env/issues/197)

Since merge #60 the environment variable `CONDA_ENV_PATH` is not defined by `activate` anymore. Is this an intended change or is this a bug?

Some user scripts rely on this variable and it still exists in Linux.

I'll be happy to send a PR if you consider this a bug.

---

@tadeu commented on [Wed Mar 02 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191419307)

@msarahan and @kalefranz, what is the status of `CONDA_ENV_PATH` and `CONDA_DEFAULT_ENV` on Windows and Unix?

Is there documentation for these variables?

Thanks!

---

@msarahan commented on [Thu Mar 03 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191767203)

No docs that I know of yet. Please excuse capitalization here. On my phone.

Conda_default_env should be the full path of the active env.  I don't know when conda_env_PATH changed, but I don't think there is intent to bring it back.

There was discussion about changing conda_default_env to conda_active_env at https://github.com/conda/conda/pull/1727 - ultimately it was decided to not change it.

If you mean conda_envs_PATH (manually setting where envs are stored and found, then its absence is/was a bug. I think it works now, and I'm making sure #1727 keeps it working.

---

@tadeu commented on [Thu Mar 03 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191777238)

Ok, thanks for the quick explanation. :)

(I was meaning about `CONDA_ENV_PATH`, without the `S`)

In this case, since `CONDA_DEFAULT_ENV` is the "official" one, it's ok in Windows, but it seems there are inconsistencies in Unix:
- `CONDA_ENV_PATH` still exists, and is a full path (this should be removed)
- `CONDA_DEFAULT_ENV` may or may not be a full path (if passed something with slashes, it's a full path, otherwise it's just the env name)

---

@msarahan commented on [Thu Mar 03 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191781786)

Thanks, I'll try to iron out those inconsistencies as part of #1727 - the goal there is really to unify the activation/deactivation process across platforms.

---

@kalefranz commented on [Thu Mar 03 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191803227)

For the record, I prefer `CONDA_ENV_PATH` over `CONDA_ENVS_PATH` since the variable should be holding a path to a single env. If we're going to change the name of this important environment variable, let's get it right now so that we don't have to change it again in the future.

Also, we should make a separate task/PR to support the old env var for a while with a strongly-worded deprecation warning. 

> On Mar 3, 2016, at 8:21 AM, Mike Sarahan notifications@github.com wrote:
> 
> Thanks, I'll try to iron out those inconsistencies as part of #1727 - the goal there is really to unify the activation/deactivation process across platforms.
> 
> —
> Reply to this email directly or view it on GitHub.

---

@msarahan commented on [Thu Mar 03 2016](https://github.com/conda/conda-env/issues/197#issuecomment-191804947)

No, you're getting mixed up.  
- `CONDA_ENV_PATH` is a variable that has only been present on linux.  It always held the path of the active environment.
- `CONDA_ENVS_PATH` is used on both Windows and Linux, and is a platform-native list of paths where Conda should look for environments when a name is provided for activation.
- `CONDA_DEFAULT_ENV` is used on both Linux and Windows, and had inconsistent behavior; sometimes showing env name, and sometimes showing env path.

The proposed change is to make `CONDA_DEFAULT_ENV` consistent (always full path), and remove `CONDA_ENV_PATH`.  `CONDA_ENVS_PATH` would not be changed.

---

@tadeu commented on [Mon Mar 28 2016](https://github.com/conda/conda-env/issues/197#issuecomment-202580225)

conda/conda#1727 was resolved (good job there!), but it still doesn't touch this issue here, right?

---

@msarahan commented on [Mon Mar 28 2016](https://github.com/conda/conda-env/issues/197#issuecomment-202582966)

It didn't remove CONDA_ENV_PATH, unfortunately.  Thanks for reminding us of this issue.  I'm going to move it to conda, now that the activate scripts live there (in master, anyway)

**Comment by tacaswell** [comment]
Does `CONDA_DEFAULT_ENV` hold the _active_ enviroment path or the root environment path?  If the first, and the name is up for bike shedding, can it have `ACTIVE` or `CURRENT` in it?

**Comment by msarahan** [comment]
active.  There was an attempt to change it to CONDA_ACTIVE_ENV, but it was removed because it was blocking PR #1727: https://github.com/conda/conda/pull/1727#issuecomment-177597754

**Comment by odoublewen** [comment]
Is CONDA_PREFIX reliable?   It seems to exists on both linux and osx and seems to hold the path to the activated conda env.

**Comment by kalefranz** [comment]
As of conda 4.1, `CONDA_PREFIX` will always hold the full, absolute path the the current active conda environment.

**Comment by matrs** [comment]
Still a problem for me (Linux)
https://github.com/Microsoft/microsoft-r-open/issues/23

Clean Install R MRO using conda, then
`$ R
my_user/anaconda3/envs/r/bin/R: line 207: /etc/ldpaths: No such file or directory`

**Comment by mingwandroid** [comment]
Your problem isn't *really* related to this issue. Your issue is that conda's MRO packages are deprecated.

**Comment by matrs** [comment]
Isn't my issue, is anaconda issue .It is in their official documentation.
