### ISSUE TITLE
conda skeleton pypi should use pip to build/install

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda/conda#2314]
conda skeleton creates build  scripts that do:

setup.py install

which is the "old" way to install python packages. It has the advantage of working with either setuptool sor raw distutils, but it has the disadvantage of not creating the proper pip meta-data, and sometimes using easy-install under the hood to build and install dependencies.

The "Modern" way to do it is with pip:

pip install ./

pip will monkey-patch setuptools in if necessary and create the proper pip meta-data.

(we probably want --no-deps, too, and maybe another flag or two.)

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1977
