### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#2315]
(py35)└─❱❱❱ conda create --name py35xarray --clone py35                         1 ⏎  +3365 11:43 ❰─┘
Fetching package metadata: ......
src_prefix: '/Users/klay6683/miniconda3/envs/py35'
dst_prefix: '/Users/klay6683/miniconda3/envs/py35xarray'
Packages: 114
Files: 9665
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py35/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'mistune-0.7.2-py35_0.tar.bz2'

System: OSX, conda is python 3 based.

**Comment by grlee77** [comment]
I recently ran across this bug as well.

In my case, the only packages that gave the type of `KeyError` reported above were ones that I had installed separately from a non-default channel.  If I uninstall those handful of packages first, then the clone proceeds successfully.

Here is the conda info for my system:
```
             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.8.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/lee8rx/anaconda  (writable)
  default environment : /home/lee8rx/anaconda/envs/py35
     envs directories : /home/lee8rx/anaconda/envs
        package cache : /home/lee8rx/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by grlee77** [comment]
As a further detail to help reproduce the issue, a specific packages that was crashing the clone operation was the following build of VTK7:

`conda install --channel https://conda.anaconda.org/grlee77 vtk`

The issue also occurred for a couple of packages from another channel as well, so it is not a problem unique to that package.

**Comment by kadrlica** [comment]
I have also been seeing this issue with conda 4.0.5 for packages installed from non-standard channels. For me the package was `pyfits 3.4.0` from `jochym`:
```
https://conda.anaconda.org/jochym/linux-64/pyfits-3.4.0-py27_3.tar.bz2
```
I was able to work around the problem by finding the explicit url of the package with `conda list --explicit` and then adding it to the `channels` listed in my `.condarc`.
```
channels:
  - defaults
  - jochym
  ...
```

**Comment by michaelaye** [comment]
FYI, it doesn't happen for me currently with a clean-ish install that only consists of conda and pip packages, plus pips of my own libraries, but no other channels or GH versions of conda packages mixed in.

**Comment by michaelaye** [comment]
I don't see a solution to this?

**Comment by michaelaye** [comment]
Sorry, wrong ticket commented.
