### ISSUE TITLE
conda install new env picks up pip installs

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#2316]
There seems to be a problem with conda install, it seems to pick up my pip install in one environment for a new environment.
1. `conda create -n debug python=3`
2. `conda install --yes conda install --yes pandas pytables matplotlib basemap scipy numpy scikit-learn scikit-image gdal bokeh dask ipython notebook ipywidgets ipyparallel astropy cython pyzmq ipykernel jupyter pip nomkl`

The suggested packages are this (removed irrelevant):

``` bash
nbformat:         4.0.1-py35_0
    networkx:         1.11-py35_0
    nomkl:            1.0-0
    notebook:         4.1.0-py35_2
    numexpr:          2.5-np110py35_nomkl_0    [nomkl]
    numpy:            1.10.4-py35_nomkl_0      [nomkl]
    pandas:           0.18.0-np110py35_0
    partd:            0.3.2-py35_1
```

and when done I do a `conda list` and suddenly a dev version of notebook appears:

``` bash
nbformat                  4.0.1                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nomkl                     1.0                           0    defaults
notebook (/Users/klay6683/src/notebook) 5.0.0.dev0                <pip>
notebook                  4.1.0                    py35_2    defaults
numexpr                   2.5             np110py35_nomkl_0  [nomkl]  defaults
numpy                     1.10.4             py35_nomkl_0  [nomkl]  defaults
openssl                   1.0.2g                        0    defaults
pandas                    0.18.0              np110py35_0    defaults
partd                     0.3.2                    py35_1    defaults
path.py                   8.1.2                    py35_1    defaults
```

which is also active in the new environment:

``` bash
┌─( ~ )───────────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(debug)└─❱❱❱ jupyter notebook --version                                        127 ⏎  +4607 17:12 ❰─┘

Correct jupyter to .jupyter ? [nyae] n
5.0.0.dev
```

I'm on OSX, using newest conda:

``` bash
┌─( ~ )───────────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(debug)└─❱❱❱ conda --version                                                          +4608 17:15 ❰─┘
conda 4.0.5
```

**Comment by kalefranz** [comment]
Can you reproduce this behavior in recent version of conda? Latest is conda 4.3.17.

**Comment by michaelaye** [comment]
Sorry, can't test, because I'm using conda-forges conda which is still on 4.2.x

**Comment by kalefranz** [comment]
conda install -c defaults conda
    conda config --set auto_update_conda false

**Comment by michaelaye** [comment]
Wouldn't a non-fitting conda create problems when I manage stuff I get from conda-forge? Or only when I am creating packages? (Which I don't do yet)

**Comment by kalefranz** [comment]
I don't think it would in either case. Pretty sure the only reason conda-forge hasn't bumped to 4.3 yet is that conda-build-all imports some of conda's internals, and that API changed slightly between 4.2 and 4.3. I think that's been pretty much resolved though also.

**Comment by michaelaye** [comment]
hm, the 
`conda config --set auto_update_conda false`
does not protect it when I do an `update --all` which is what I do all the time. So that doesn't really work for me.

**Comment by kalefranz** [comment]
We have open issues for better pip interoperability.  See the pip-interop tag.  What's needed here is being tracked in other issues.
