### ISSUE TITLE
dependency issues when using channels indexed by conda index

### ISSUE THREAD

**Issue by david-ewc** [conda/conda#2317]
Hi everyone,

first let me thank you for that awesome piece of software you are writing! 
While testing a custom channel I encountered some issue with indexing that channel. I have tried to install a package named msgpack from the custom channel and I got an output like:

```
(P21603)david@xxx:/tmp/conda_env_creator4$ conda install msgpack
Fetching package metadata: ..
Solving package specifications: .
Error:  Dependency missing in current linux-64 channels: 
  - msgpack -> python 2.7

Did you mean one of these?

    python, ipython

You can search for this package on anaconda.org with

    anaconda search -t conda python 2.7

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

Well actually it isn't true that python 2.7 is missing as a depedency. The selected env reads as:
```
(P21603)david@xxx:/tmp/conda_env_creator4$ conda list
# packages in environment at /tmp/conda_env_creator4/envs/P21603:
#
openssl                   1.0.2d                        0    defaults
pip                       8.1.1                    py27_1    defaults
python                    2.7.11                        0    defaults
readline                  6.2                           2    defaults
setuptools                20.3                     py27_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.8                         0    defaults
```

The conda version of the system is:
```
             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
```

If I try to install msgpack from defaults channel however, it all works flawless. I did some research and believe to found the root of that problem in the repodata.json files. 

The file from from https://repo.continuum.io/pkgs/free/linux-64/repodata.json for the package is:
```
    "msgpack-0.2.3-py27_0.tar.bz2": {
      "build": "py27_0",
      "build_number": 0,
      "date": "2014-08-22",
      "depends": [
        "python 2.7*"
      ],
      "license_family": "Other",
      "md5": "4d66130cc34f3270c0ec46d13373bba7",
      "name": "msgpack",
      "requires": [],
      "size": 102353,
      "version": "0.2.3"
    },
```

The repodata  for the exact same file created with "conda index ..." is in contrast:
```
  "msgpack-0.2.3-py27_0.tar.bz2": {
    "arch": "x86_64", 
    "build": "py27_0", 
    "build_number": 0, 
    "md5": "4d66130cc34f3270c0ec46d13373bba7", 
    "mtime": 1408732571.0, 
    "name": "msgpack", 
    "platform": "linux", 
    "requires": [
      "python 2.7"
    ], 
    "sig": null, 
    "size": 102353, 
    "ucs": 4, 
    "version": "0.2.3"
  }, 
```

One may note that there is a missing * after "python 2.7" in "requires" in the latter json snippet. This missing * seems to do the trick. After adding it manually the installation from the local custom channel worked. 

Finally let me point out that the behaviour of "conda index" is theoretically correct. The index.json file of msgpack-0.2.3-py27_0.tar.bz2 is:
```
{
  "arch": "x86_64", 
  "build": "py27_0", 
  "build_number": 0, 
  "name": "msgpack", 
  "platform": "linux", 
  "requires": [
    "python 2.7"
  ], 
  "ucs": 4, 
  "version": "0.2.3"
}
```
Therefore it appears that the problem is determined by the package itself. But maybe you could add some fault tolerance to the indexer. That would be really great!

Thank you and kind regards!

**Comment by kalefranz** [comment]
Hi @david-ewc, 

> Therefore it appears that the problem is determined by the package itself.

You've indeed identified your problem correctly!

> But maybe you could add some fault tolerance to the indexer. That would be really great!

I'm going to close this issue, but I'll chat with some folks about this version spec.  Because I might have myself thought at one point `python 2.7` might be equivalent to `python 2.7*`.

**Comment by mcg1969** [comment]
On the _command line_, `python=2.7` is equivalent to `python=2.7*`. But in the dependencies, it denotes an exact match.

**Comment by kalefranz** [comment]
Thanks for the extra info Mike. Guess I'll chat with Ilan sometime about the history of the discrepancy.

**Comment by mcg1969** [comment]
Incidentally this is related to #2371

**Comment by david-ewc** [comment]
Hi @kalefranz and @mcg1969 
thank you for your replies! Actually I see that the problem is caused by the package itself, however I have a larger conda env and a few of the packages seem to have that issue with the missing `*` after the specification of the dependency. I have to admit that I am too lazy to fix all the package meta data, especially b/c those packages are located in  https://repo.continuum.io/pkgs/free/linux-64 ;) 

However, it appears that the repodata file at  https://repo.continuum.io/pkgs/free/linux-64/repodata.json was not created with `conda index` as it is listed there:  
```
"msgpack-0.2.3-py27_0.tar.bz2": {
....
"depends": [
        "python 2.7*"
      ],
....
}
```
Would you mind telling me how you created that repodata.json file? 

Thank you again!

**Comment by kalefranz** [comment]
@david-ewc, @mcg1969 and I were discussing this very issue today.  We are (apparently) manually updating repodata.json on repo.continuum.io without rebuilding the packages, and this obviously breaks `conda index` when used to create an offline repo.  @mcg1969 and I just discovered all of this today.  We will be discussing at a weekly meeting we have on Thursdays.

**Comment by david-ewc** [comment]
@kalefranz, ok in this case I will no stop bothering you ;) Wish you both happy troubleshooting!

**Comment by stilley2** [comment]
Hi all. I know this is an old issue, but does anyone have an update? My repodata.json doesn't have the `*`, and I'm not sure why. My meta.yaml has ` - numpy x.x` for both build and run requirements, and I'm specifying `--numpy=1.12` on the command line. Should I open up a new issue for this?
Thanks
Steve

**Comment by david-ewc** [comment]
Hi @stilley2,
without understanding your problem, I still would like to document what we actually did to solve the problem I mentioned above. The problem I described at first only occurred to us when processing  packages copied from https://repo.continuum.io, and the problem was indeed located in the package meta.yaml files. So  we ended up with a script that copied the repodata.json entries for those packages from the repodata.json file hosted on  https://repo.continuum.io and voila it worked. Not a nice solution though.

**Comment by stilley2** [comment]
Hi @david-ewc,
Thanks for the update. That doesn't sound quite like the issue I'm seeing, so if I can't resolve it I'll open a separate issue.
Thanks again!

**Comment by Tych0n** [comment]
Hi, @kalefranz ! Still facing this issue with "glog" package. In https://repo.continuum.io/pkgs/main/linux-64/repodata.json "glog-0.3.5-hf484d3e_1" both .bz2 and .conda has "libgcc-ng >=7.2.0". But if i download package itself, in ...bz2/info/index.json i see "libgcc-ng 7.2.0.*".

**Comment by jjhelmus** [comment]
@Tych0n `repodata.json` needs to be patched to correct issues in the metadata recoreded in the packages.  These fixes for the `main` channel are published to https://github.com/AnacondaRecipes/repodata-hotfixes.  
These patches can be applied when running `conda index` using the `-p` argument which is documented in the help message available by running `conda index --help`
