### ISSUE TITLE
Can not update Anaconda

### ISSUE THREAD

**Issue by johnzzzz** [conda/conda#2322]
I have the same problem as:
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/Lyl_OLAzdHY

Note that this is happening on only one of our servers and that server is running the Jupyter server

conda remove anaconda
conda update --all
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
- bottleneck -> numpy 1.10_|1.9_
- bottleneck -> python 3.4_|3.5_
- fontconfig -> freetype 2.5*
- fontconfig -> libpng 1.6.17
- runipy
  Use "conda info <package>" to see the dependencies for each package.
  [conda_list.txt](https://github.com/conda/conda/files/200367/conda_list.txt)
  [install_anaconda.txt](https://github.com/conda/conda/files/200375/install_anaconda.txt)

**Comment by dgwakeman** [comment]
I also have a similar problem: 

```conda update anaconda```
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda
  - bottleneck (target=bottleneck-1.0.0-np19py27_0.tar.bz2) -> numpy 1.10*|1.11*|1.9*
  - bottleneck (target=bottleneck-1.0.0-np19py27_0.tar.bz2) -> python 3.4*|3.5*
  - fontconfig (target=fontconfig-2.11.1-4.tar.bz2) -> freetype 2.5*
  - fontconfig (target=fontconfig-2.11.1-4.tar.bz2) -> libpng 1.6.17
Use "conda info <package>" to see the dependencies for each package.

```conda remove anaconda```

```conda update --all```

Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
  - blaze-core
  - bottleneck -> numpy 1.10*|1.11*|1.9*
  - bottleneck -> python 3.4*|3.5*
  - fontconfig -> freetype 2.5*
  - fontconfig -> libpng 1.6.17
Use "conda info <package>" to see the dependencies for each package.

**Comment by tyler-thetyrant** [comment]
Please try with the most recent version of conda.
Closing as outdated.
