### ISSUE TITLE
scipy.weave missing?

### ISSUE THREAD

**Issue by tjragan** [conda/conda#2326]
I just tried importing scipy.weave, only to find it missing.  I've gone all the way back to the downloaded scipy-0.17.0-np110py35.tar.bz2 file and the weave directory is missing.  I've tried the solutions in
#1331 to no avail. 
Am I doing something silly?
```python
Python 3.5.1 |Anaconda 2.4.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.version
>>> scipy.version.version
'0.17.0'
>>> import scipy.weave
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'scipy.weave'
>>>
```

**Comment by msarahan** [comment]
weave has been moved out into its own separate project.  See
https://github.com/scipy/weave

**Comment by tjragan** [comment]
Right, something silly...
Thanks.
