### ISSUE TITLE
Pandas 0.16.2 installs incorrect version of file on Windows

### ISSUE THREAD

**Issue by zrisher** [conda/conda#2328]
With this `environment.yml`:
```
name: taxcalc-dev
dependencies:
- pytest
- setuptools
- python
- numpy
- pandas <=0.16.2
- numba
- toolz
- six
- ipython
- ipython-notebook
- pip:
  - pytest-pep8
```

and this `conda info`:

```
platform : win-64
conda version : 4.0.5
conda-build version : not installed
python version : 3.4.2.final.0
requests version : 2.9.1
root environment : C:\Dev\Miniconda3  (writable)
default environment : C:\Dev\Miniconda3\envs\taxcalc-dev
envs directories : C:\Dev\Miniconda3\envs
package cache : C:\Dev\Miniconda3\pkgs
channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                         https://repo.continuum.io/pkgs/free/noarch/
                         https://repo.continuum.io/pkgs/pro/win-64/
                         https://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False
```

And the corresponding pandas package installed:
`pandas 0.16.2 np19py35_0 http://repo.continuum.io/pkgs/free/win-64/pandas-0.16.2-np19py35_0.tar.bz2`

If I `import pandas`, I am presented with this error:

```
C:\Dev\Miniconda3\envs\taxcalc-dev\lib\site-packages\pandas\__init__.py:22: in <module>
    from pandas.compat.numpy_compat import *
E   ImportError: No module named 'pandas.compat.numpy_compat'
```

This appears to occur because the `pandas/__init__.py` installed for pandas has content that's more recent than the version I'm attempting to install - it's incompatible with the rest of the files.

If I look at the commit referenced for the `0.16.2` release of `pandas` on its github repo:
https://github.com/pydata/pandas/tree/06832891870119984c6a5404bc7f7a471f43b99c

there is no line importing from `pandas.compat`. If I look at my local file, there is (line 22 as mentioned in the error).

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#760
