### ISSUE TITLE
installing bz2 files does not install dependencies

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda#2333]

**Comment by mcg1969** [comment]
Yes, this is known behavior, and very handy to have sometimes I might add. The secret is to treat a local directory as a channel and install from there. @groutr, you have some secret sauce here, right?

**Comment by groutr** [comment]
I use the conda-bld directory as a local repo.  Then I use `conda install --use-local <pkgname>` to install.

Another solution, is to create a local channel.  Assuming you're on OSX and want to install OSX packages, then you simply need a folder with the following structure
```
my_local_channel/
|_>  osx-64/
```
copy your packages to the `osx-64` directory and run `conda index /path/to/my_local_channel/osx-64`.  `conda index` will create the `repodata.json` and `repodata.json.bz2` files that conda looks for.  Now all that remains is to add the path to your new channel to your `.condarc`.

**Comment by kalefranz** [comment]
@groutr `conda index` often fails to create a valid repo now.  To be discussed on Thursday!
