### ISSUE TITLE
Activate enable the wrong version of python

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#2336]
This is related to issue #166 which has been opened with the following:

> Having a symlink to conda in every environment would allow to only have that environment's bin directory added to PATH, and would avoid potential confusion.

And closed with

> Each environment has a symlink to conda, activate, and deactivate, and activate removes the root environment from the PATH.

So on a machine which has its own (old) python in /usr/bin running 

`source activate blah`

removes the root environment from PATH (as described above in the close issue #166 message) and that causes the wrong version of python being active (and a bunch of other stuff). I would suggest adding everything else from the root environment to the environment, but of course not removing the root environment may be a sensible choice too

**Comment by kalefranz** [comment]
This is resolved in conda 4.4 with #5044.
