### ISSUE TITLE
conda activate instead of source activate?

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#2337]
Is there any reason why conda is not using the same trick module is using to deal with avoiding source? See https://github.com/TACC/Lmod/blob/master/init/bash.in for one implementation of that trick, if you are not familiar with it.

**Comment by nealmcb** [comment]
Yes - I ran into this hassle also!

Note that the referenced bash.in demonstrates using shell functions rather than python/shell scripts....

**Comment by kalefranz** [comment]
Hey guys,
This request is similar to #341 and #2080.  Implementing something like this is definitely on the radar.  Going to close the issue though as it will be tracked elsewhere.
