### ISSUE TITLE
Add --build flag to conda clean

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2339]
_From @srossross on April 5, 2016 3:37_

Re: #255 perhaps we should move conda-clean-build-dir into conda build? 

I am not sure of the original reasons this was not added directly to conda.

current: removes the conda_bld directory

Request: add flag to conda clean to remove the build directory if it exists

_Copied from original issue: Anaconda-Server/anaconda-build#262_

**Comment by kalefranz** [comment]
_From @stephenakearns on April 8, 2016 19:9_

@kalefranz agreed - moving to the conda/conda repo

**Comment by srossross** [comment]
@kalefranz another alternative would be to allow an alternative directory to store the build results. I think this was implemented but never worked: https://github.com/conda/conda-build/issues/82

**Comment by kalefranz** [comment]
duplicate of #3592
