### ISSUE TITLE
Conda-build: Remove dependency on setuptools and setup.py for python packages. (redundant meta.yaml)

### ISSUE THREAD

**Issue by telson** [conda/conda#2341]
All the information is in the meta.yaml.  Why not do away with setuptools and setup.py?

Build.sh can already replace setup.py by:
- Extracting tarball into site-packages
- Add package to conda.pth
- Add entrypoints to bin/
- ... etc

... so why have so much information duplicated in both meta.yaml and setup.py, requiring manual transcription?

(If it's absolutely necessary, why not have a conda-build step that generates one from the other)

**Comment by msarahan** [comment]
This is a good idea, but I don't think the answer is to totally remove setup.py.  That would further divide the two packaging communities.  As it is, we need to find ways to better interoperate with pip, not toss them aside.  A tool for updating conda recipes from PyPI/pip would be really nice - we have conda skeleton pypi, but that is only for creating new recipes.  We welcome any thoughts you have on the matter.

**Comment by marscher** [comment]
I think a tool for updating this information would be a great improvement. Removing setup.py is an absolute no-go since it is a well established way of distributing packages.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#884
