### ISSUE TITLE
BeeGFS hard-links

### ISSUE THREAD

**Issue by dfroger** [conda/conda#2345]
[BeeGFS](http://www.beegfs.com), a parallel cluster file system, [does not support](https://groups.google.com/forum/#!topic/fhgfs-user/cTJcqGZceVA) `hard-links` between files in differents directories.

Depending on the [configuration](https://groups.google.com/forum/#!topic/fhgfs-user/pvQSo0QWicw), either an error is issued, or a `symbolic-link` is created.

If a `symbolic-link` is created instead of a `hard-link`, it can cause problem, for example:

    pkgs/bin/mpicc
    pkgs/lib/libopen-pal.so
    envs/bin/mpicc
    envs/lib/libopen-pal.so

Here, when `envs/bin/mpicc` is executed, it is actually `pkgs/bin/mpicc` that is executed, and the library `$PREFIX/../lib/libopen-pal.so` actually loaded is `pkgs/lib/libopen-pal.so,` which is different from `envs/lib/libopen-pal.so` for which conda has fixed hard-coded prefix path, and as a final consequence `mpicc` fails to find its configuration file.

#805 is another (closed) related to `BeeGFS`.

Would we need a new conda options to turn hard-link into copy?

**Comment by dfroger** [comment]
This [commit](https://github.com/dfroger/conda/commit/742ca641c390e3fdaca207bf2136209d0f545bd2) fix the problem for me.

**Comment by groutr** [comment]
I'd suggest submitting a PR with that commit for review.

**Comment by dfroger** [comment]
I submitted #2355
