### ISSUE TITLE
can't update numpy to 1.11.0 with conda update, current version 1.10.4

### ISSUE THREAD

**Issue by menglin0320** [conda/conda#2348]
The following specifications were found to be in conflict:
  - blaze (target=blaze-0.9.1-py27_0.tar.bz2) -> numba
  - numba -> numpy 1.10*|1.5*|1.6*|1.7*|1.8*|1.9*
  - numba -> python 2.6*|3.3*|3.4*|3.5*
  - numba (target=numba-0.25.0-np110py27_0.tar.bz2)
  - numpy 1.11|1.11.0*

**Comment by menglin0320** [comment]
@mcg1969

**Comment by mcg1969** [comment]
It looks to me like `numba` isn't yet available in a `numpy 1.11` version.

**Comment by menglin0320** [comment]
So if I remove numba, this problem is solved?

**Comment by mcg1969** [comment]
Possibly. There may be other packages that aren't ready for NumPy 1.11, too.

**Comment by menglin0320** [comment]
Ok, so I should remove every package that conflicts with numpy11 right?

**Comment by mcg1969** [comment]
Yes. But do you have a pressing need to update to NumPy 1.11? If so, in my view, a better solution is not to upgrade yet.

**Comment by menglin0320** [comment]
I'm not sure. I'm new to python and I'm trying to do a research in university. The numpy version specified on the document for the project is 1.11.0.

**Comment by menglin0320** [comment]
Thank you. I've updated numpy.
