### ISSUE TITLE
Exporting conda environments - can the channel information be included?

### ISSUE THREAD

**Issue by DamienIrving** [conda/conda#2350]
In constructing the conda environments I use, I install packages from various channels at anaconda.org. When I export those environments using `conda env export`, the resulting `.yml` file doesn't include the channel information.

For instance, it will look like this:
```
name: my-environment
dependencies:
- appnope=0.1.0=py27_0
- backports_abc=0.4=py27_0
- biggus=0.13.0=py27_0
- ...
```
when it should look like this:
```
name: my-environment
channels:
- ioos
dependencies:
- appnope=0.1.0=py27_0
- backports_abc=0.4=py27_0
- biggus=0.13.0=py27_0
- ...
```
I then have to manually edit the file to add the channel information before uploading the environment to anaconda.org. This isn't such a big deal, but for the uninitiated it might cause errors that they can't figure out how to fix (i.e. it isn't immediately obvious that you'd need to manually edit an exported `.yml` file).

**Comment by dotsdl** [comment]
Was just about to post this issue myself. Related: is the ``environment.yml`` schema documented anywhere? I came across the existence of ``channels`` as a valid key by way of an issue elsewhere, but couldn't find mention of it anywhere in the docs.

**Comment by kalefranz** [comment]
Hi @DamienIrving,

Your best bet right now is to use

    conda list --explicit > my-environment.txt
    conda create --name new-environment --file my-environment.txt

I agree it's not ideal, and making channel information a "first class citizen" for a package specification is something we're actively working on.

@dotsdl  I wish.  Actually, while conda envs are incredibly useful, they're (in my opinion) not at all user friendly.  Working to outline a proposal for discussion and input over the next week or so.

**Comment by dorukkarinca** [comment]
Any update on this?

**Comment by kalenkovich** [comment]
> Any update on this?

Currently, `conda env export` does include channels information.
