### ISSUE TITLE
Conda / Anaconda-Server Integration Points

### ISSUE THREAD

**Issue by srossross** [conda/conda#2357]
Here are some of the pain points of using conda 
1. Anaconda-Server provides a dynamic view on live changing user-data. The `repodata.json` is far from efficient in this case. This is the cause of most of the server CPU bottlenecks and db-server IO bottlenecks. It would be great if conda could use the anaconda repository RESTful API and assemble the repodata.json internally. This was demo'd in Kapsel and benchmarked a large performance gain when using multiple channels. (Kale has all the context on this issue after speaking with Sean)
2. Errors messages - anaconda server provides json error messages that conda can use
3. Login - it would be great if conda and anaconda could prompt or require login before `conda install` calls. for example in the `.condarc` a setting like `using_private_packages: yes` would prompt users to login before continuing.
4. Channel syntax. Conda is designed to be fully reproducible, however the number of channels on anconda.org makes this very difficult. A new syntax like `@sean/package` would allow installation of a specific package that could be installed without a user having to modify the global conda state and prevents ambiguous package resolutions. eg `conda install -c sean -c ben numpy salt` - what packages of numpy and salt will be installed in this scenario? That is currently undefined. This could be better written as  `conda install @sean/numpy @ben/salt`

**Comment by mcg1969** [comment]
Hey Sean! Regarding #4, we're actually in the process of improving the channel handling internally. There are a number of improvements that immediately suggest themselves after that. Some sort of command-line syntax like yours is an obvious choice, and I like your specific proposal. We also need environment-level channel lists.

**Comment by mcg1969** [comment]
@srossross @kalefranz can you think of a reason why we need something like the leading ampersand above; e.g., why can't we do `conda install sean/numpy ben/salt`?

**Comment by srossross** [comment]
> @srossross @kalefranz can you think of a reason why we need something like the leading ampersand above; e.g., why can't we do conda install sean/numpy ben/salt?

No, there may  not be a valid reason for it.  My two data points are:

 1. Distinctly different from the file system
 1. NPM already has a similar syntax https://docs.npmjs.com/misc/scope

**Comment by csoja** [comment]
@srossross Do you have a priority and impact for these 4 items?

**Comment by srossross** [comment]
> conda could use the anaconda repository RESTful API and assemble the repodata.json internally. 

This will alleviate the bulk of the CPU and data transfer load of the tar.bz2 endpoint. The impact is very high. 

> Errors messages - Login 

Would greatly increase the usability of anaconda.org with conda. this is an easy fix, but it is low priority

> - it would be great if conda and anaconda could prompt or require login before conda install calls. for example in the .condarc a setting like using_private_packages: yes would prompt users to login before continuing.

> Channel syntax. 

@kalefranz already has plans to address this.

**Comment by kalefranz** [comment]
@srossross Can you create a ticket with the details we discussed for a better content-encoding request header?

**Comment by srossross** [comment]
Done conda/conda#2794

**Comment by mcg1969** [comment]
> conda could use the anaconda repository RESTful API and assemble the repodata.json internally.

Can you elaborate further on how you see this working? I'm not seeing the source of savings here.
