### ISSUE TITLE
conda wants to mess everything up, when I'm simply asking to remove a package

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#2360]
This is on a freshly installed anaconda, so it should be as clean as it gets

```
$ conda remove numba
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for package removal in environment /glade/apps/contrib/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hdf5-1.8.14                |                0         1.8 MB
    numpy-1.9.3                |           py27_2         5.7 MB
    astropy-1.0.4              |       np19py27_0         7.2 MB
    bcolz-0.7.2.dev            |       np19py27_0         955 KB
    bottleneck-1.0.0           |       np19py27_0         533 KB
    h5py-2.3.1                 |       np19py27_1         2.4 MB
    numexpr-2.3.1              |       np19py27_0         319 KB
    patsy-0.4.0                |       np19py27_0         325 KB
    scipy-0.17.0               |       np19py27_2        29.9 MB
    pandas-0.17.1              |       np19py27_0        12.2 MB
    py2cairo-1.10.0            |           py27_2          36 KB
    pytables-3.1.1             |       np19py27_2         3.2 MB
    scikit-learn-0.16.1        |       np19py27_0         7.9 MB
    into-0.2.2                 |       np19py27_0         130 KB
    matplotlib-1.4.3           |       np19py27_2        44.5 MB
    statsmodels-0.6.1          |       np19py27_0         5.0 MB
    blaze-0.7.0                |       np19py27_0         289 KB
    scikit-image-0.11.3        |       np19py27_0        23.8 MB
    ------------------------------------------------------------
                                           Total:       146.2 MB

The following NEW packages will be INSTALLED:

    bcolz:        0.7.2.dev-np19py27_0
    into:         0.2.2-np19py27_0    
    py2cairo:     1.10.0-py27_2       

The following packages will be REMOVED:

    numba:        0.24.0-np110py27_0

The following packages will be UPDATED:

    bottleneck:   1.0.0-np110py27_0  --> 1.0.0-np19py27_0    
    patsy:        0.4.0-np110py27_0  --> 0.4.0-np19py27_0    
    scipy:        0.17.0-np110py27_2 --> 0.17.0-np19py27_2   
    statsmodels:  0.6.1-np110py27_0  --> 0.6.1-np19py27_0    

The following packages will be DOWNGRADED:

    astropy:      1.1.2-np110py27_0  --> 1.0.4-np19py27_0    
    blaze:        0.9.1-py27_0       --> 0.7.0-np19py27_0    
    h5py:         2.5.0-np110py27_4  --> 2.3.1-np19py27_1    
    hdf5:         1.8.15.1-2         --> 1.8.14-0            
    matplotlib:   1.5.1-np110py27_0  --> 1.4.3-np19py27_2    
    numexpr:      2.5-np110py27_0    --> 2.3.1-np19py27_0    
    numpy:        1.10.4-py27_1      --> 1.9.3-py27_2        
    pandas:       0.18.0-np110py27_0 --> 0.17.1-np19py27_0   
    pytables:     3.2.2-np110py27_1  --> 3.1.1-np19py27_2    
    scikit-image: 0.12.3-np110py27_0 --> 0.11.3-np19py27_0   
    scikit-learn: 0.17.1-np110py27_0 --> 0.16.1-np19py27_0   

Proceed ([y]/n)? n
```

Problems:

1. why does it want to install stuff that wasn't installed before, e.g. bcolz?
2. why does it want to downgrade numpy which certainly does not depend on numba, nor of any of the other stuff conda decided to mess up with???

@mcg1969 I've seen several possibly related issues with this, e.g.  issue #1967

**Comment by mcg1969** [comment]
Thanks for cc:-ing me! Can you paste in the full output of `conda --debug remove numba`? Yeah I know it's long, but it will help us figure this out.

**Comment by davidedelvento** [comment]
Happy to do that, but do you want also the stuff that it writes to the tty, or only stdout and stderr redirection?

**Comment by mcg1969** [comment]
I'm reasonably sure the stdout/stderr will do.

**Comment by mcg1969** [comment]
Actually, nevermind, I can reproduce it here!

**Comment by davidedelvento** [comment]
Good (because github don't let me upload that file).

**Comment by mcg1969** [comment]
I believe this is being caused by the fact that one or more of of the packages being downgraded depend on `numba`. Still investigating.

**Comment by mcg1969** [comment]
Yes, that's it. The latest version of `blaze` depends on `numba`. So if you do
```
conda remove blaze numba
```
everything works as expected. Unfortunately, if you remove numba but not blaze, then you are forced to downgrade blaze to an older version that does *not* depend on numba, and this is causing a cascade of downgrades to NumPy 1.9 and others.

cc: @ilanschnell

**Comment by mcg1969** [comment]
This gets back to a general issue we have with conda, and that's that it doesn't give you hints about why it is doing what it is doing.

**Comment by davidedelvento** [comment]
Great thanks. Maybe (before you guys implement a nice way to provide these hints) you can implement a "verbose" or "debug" option  to simply "spit out" everything it does while traversing the DAG of dependencies? Or at least an easier way to study those dependencies manually (see issue #2361)?
Anyway, as far as I'm concerned, you may close this issue, thanks

**Comment by mcg1969** [comment]
Indeed, that's really what I'm talking about when it comes to those "hints" above. I certainly agree that it's an important issue.

**Comment by mcg1969** [comment]
@davidedelvento, you might be interested in #2385

**Comment by davidedelvento** [comment]
Thanks for linking that.
