### ISSUE TITLE
List dependencies of a given package?

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#2361]
Trying to debug issue #2360 (maybe some dependencies were to blame, not conda) I **really** wanted to be able to run things like `conda info numpy=1.10.4-py27_1` but that does not work. So I had to rely on `conda info numpy | grep -A 15 1.10.4-py27_1`. I spent a fair amount of time in `conda help` and on the web, but could not find anything to specify a particular version (heck, even finding that `conda info package` was hard -- for a newbie to conda -- maybe you should add that info to http://conda.pydata.org/docs/faq.html#managing-packages?)

Anyway, an option to specify a particular version of the package would be extremely useful (or if such a thing already exist, telling about it into the conda help or online would be great).

**Comment by cfobel** [comment]
I'm using the following command as a workaround:

    conda create --dry-run --json -n dummy <package descriptor>

It determines the actions required to create an environment containing the specified package without actually creating the environment.  This includes generating a list of all dependencies that would be installed under the path `actions.LINK` in the JSON output.

The `--json` flag triggers JSON output to make it easy to work with in code.  Note that the [`conda create` command][1] requires a name for the environment to be specified using the `-n` flag.  However, since the environment is *not* actually created when using the `--dry-run` flag, the name is not actually used here.

For example:

     > conda create --dry-run --json -n dummy ipython
    {
      "actions": {
        "LINK": [
          "vs2008_runtime-9.00.30729.1-2 1",
          "conda-forge::python-2.7.12-1 1",
          "conda-forge::backports.shutil_get_terminal_size-1.0.0-py27_1 1",
          "conda-forge::certifi-2016.9.26-py27_0 1",
          "conda-forge::colorama-0.3.7-py27_0 1",
          "conda-forge::decorator-4.0.10-py27_0 1",
          "conda-forge::enum34-1.1.6-py27_1 1",
          "conda-forge::ipython_genutils-0.1.0-py27_0 1",
          "conda-forge::simplegeneric-0.8.1-py27_0 1",
          "conda-forge::six-1.10.0-py27_1 1",
          "conda-forge::wcwidth-0.1.7-py27_0 1",
          "conda-forge::win_unicode_console-0.5-py27_0 1",
          "conda-forge::wincertstore-0.2-py27_0 1",
          "conda-forge::pathlib2-2.1.0-py27_0 1",
          "conda-forge::setuptools-32.3.1-py27_0 1",
          "conda-forge::traitlets-4.3.1-py27_0 1",
          "conda-forge::pickleshare-0.7.3-py27_0 1",
          "conda-forge::pygments-2.1.3-py27_1 1",
          "conda-forge::wheel-0.29.0-py27_0 1",
          "conda-forge::pip-9.0.1-py27_0 1",
          "conda-forge::prompt_toolkit-1.0.9-py27_0 1",
          "conda-forge::ipython-5.1.0-py27_2 1"
        ],
        "PREFIX": "C:\\Users\\chris\\Miniconda2\\envs\\none",
        "SYMLINK_CONDA": [
          "C:\\Users\\chris\\Miniconda2"
        ],
        "op_order": [
          "RM_FETCHED",
          "FETCH",
          "RM_EXTRACTED",
          "EXTRACT",
          "UNLINK",
          "LINK",
          "SYMLINK_CONDA"
        ]
      },
      "dry_run": true,
      "success": true
    }

**Comment by jdamato3** [comment]
@davidedelvento this should work for you:
```
conda info <package>=<version>=<build_num>
```
For example:
```
conda info numpy=1.11.1=py27_0
```
and this should display the dependencies:
```
Fetching package metadata .......

numpy 1.11.1 py27_0
-------------------
file name   : http://<repo>/conda/anaconda::numpy-1.11.1-py27_0.tar.bz2
name        : numpy
version     : 1.11.1
build number: 0
build string: py27_0
channel     : http://<repo>/conda/anaconda/osx-64
size        : 3.1 MB
arch        : x86_64
binstar     : {u'package_id': u'5637fd389c73330b8ae82766', u'channel': u'main', u'owner_id': u'<id>'}
date        : 2016-06-29
fn          : numpy-1.11.1-py27_0.tar.bz2
license     : BSD
md5         : c2d04cd764596bd2626e29a752bd477e
platform    : osx
priority    : 2
schannel    : http://<repo>/conda/anaconda
url         : http://<repo>/conda/anaconda/osx-64/numpy-1.11.1-py27_0.tar.bz2
dependencies:
    mkl 11.3.3
    python 2.7*
```

**Comment by sebma** [comment]
@jdamato3 Hi, Your method does not give the sub-dependencies, that is to say the whole dependency tree

**Comment by jdamato3** [comment]
@sebma you're right, good catch. I didn't consider sub-dependencies. Thanks for the clarification.

**Comment by justlurking** [comment]
@sebma @jdamato3 @cfobel @davidedelvento 

There is an (experimental?) graphing function in 4.4 that may be helpful. Haven't had a chance to try it myself. It's mentioned in #4942.

HTH.

**Comment by kalefranz** [comment]
As of conda 4.4, you can get the information you're looking for with

    conda info numpy=1.10.4=py27_1 --search

**Comment by wvxvw** [comment]
@kalefranz either the syntax for specifying package version changed since your comment, or the command doesn't work anymore. Bottom line, that command results in an error, and I'm not able to find documentation on how to accomplish what OP wanted. My `conda` version is 4.10.1.

**Comment by wvxvw** [comment]
Just to clarify on documentation point: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#listing-package-dependencies this suggests using unsupported commands, eg. `conda info`. And further, what's written there doesn't match reality anyways.
