### ISSUE TITLE
Can't run conda install conda-build as requested by docs

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#2364]
According to http://conda.pydata.org/docs/build_tutorials/pkgs.html I should run:

`conda install conda-build` 

however that results in

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Error: 'conda' can only be installed into the root environment
```
Is one supposed to run conda skeleton only in the root environment? If so the docs should state so, and it should also state how "risky" is that for the whole installation (since this is for a multi-user machine, and I don't want to break anything)

**Comment by kalefranz** [comment]
You can *run* `conda skeleton` from any environment, but right now, you need to initially *install* `conda skeleton` via `conda install conda-build` *into* the root environment.  Make sense?

**Comment by davidedelvento** [comment]
Understood, thanks. I suggest clarifying the issue on the webpage I linked
