### ISSUE TITLE
pyfaidx MD5 mismatch

### ISSUE THREAD

**Issue by vanzod** [conda/conda#2367]
While trying to install the pyfaidx package via conda it failed with a MD5 sums mismatch. I manually downloaded it and the sum seems different from the one in the repo metadata:

Error: MD5 sums mismatch for download: https://conda.anaconda.org/bcbio/linux-64/pyfaidx-0.4.1.1-py27_0.tar.bz2 (7643ba3b47a8680888825727fd7c5edd != ff0b2bb78c56b6b5f327194a678566fe)
$ wget https://conda.anaconda.org/bcbio/linux-64/pyfaidx-0.4.1.1-py27_0.tar.bz2
[...]
$ md5sum pyfaidx-0.4.1.1-py27_0.tar.bz2 
7643ba3b47a8680888825727fd7c5edd  pyfaidx-0.4.1.1-py27_0.tar.bz2

**Comment by kalefranz** [comment]
@srossross @stephenakearns Where should we file repo issues now for anaconda.org?  I verified that the md5 sum for the file is 7643...5edd but is ff0b...66fe in https://conda.anaconda.org/bcbio/linux-64/repodata.json.  Also, FWIW, the info pop-up associated with the file [here](https://anaconda.org/bcbio/pyfaidx/files) has the correct hash.

**Comment by srossross** [comment]
@kalefranz it is not clear where each MD5 is coming from. where are you getting this error `7643ba3b47a8680888825727fd7c5edd != ff0b2bb78c56b6b5f327194a678566fe` ?

**Comment by srossross** [comment]
OK, it  looks like the linux-64 repodata is picking up some of the osx packages. I will look into the cause of this.

**Comment by srossross** [comment]
From https://conda.anaconda.org/bcbio/linux-64/repodata.json the pyfaidx osx package has been uploaded with incorrect metadata.  The `"subdir": "linux-64",`  is the reason why it is overwriting the real linux-64 version of this file.

```
    "pyfaidx-0.4.1.1-py27_0.tar.bz2": {
      "arch": "x86_64", 
      "binstar": {
        "channel": "main", 
        "owner_id": "53c4249de1dad12c844e770b", 
        "package_id": "55170a095e76835d0fc7977a"
      }, 
      "build": "py27_0", 
      "build_number": 0, 
      "depends": [
        "python 2.7*", 
        "setuptools", 
        "six"
      ], 
      "license": "MIT", 
      "machine": "x86_64", 
      "md5": "ff0b2bb78c56b6b5f327194a678566fe", 
      "name": "pyfaidx", 
      "operatingsystem": "darwin", 
      "platform": "osx", 
      "requires": [], 
      "size": 27347, 
      "subdir": "linux-64", 
      "target-triplet": "x86_64-any-darwin", 
      "version": "0.4.1.1"
    }, 

```

**Comment by srossross** [comment]
Could this be a package created with `conda convert`?

**Comment by kalefranz** [comment]
@srossross I see it now too.

@vanzod Do you know how this package was created?

**Comment by brentp** [comment]
cc @chapmanb

**Comment by chapmanb** [comment]
Brent, thanks for the cc. This is my package and it's outdated. We've moved all of our package development to the bioconda project and here is the latest for pyfaidx:

https://anaconda.org/bioconda/pyfaidx

So you should be able to install with:
```
conda install -c bioconda pyfaidx
```
I did use conda convert for the older packages (although to convert to OSX) so that could be the source of the underlying error, but hopefully switching to bioconda avoids it.
