### ISSUE TITLE
rpy2 package is broken on Py3.5, bug has been fixed upstream.

### ISSUE THREAD

**Issue by fperez** [conda/conda#2372]
When loading the IPython magic from rpy2 on python 3.5, the current result is (trimming the traceback):

```
/Users/fperez/usr/conda/lib/python3.5/site-packages/rpy2/robjects/__init__.py in <module>()
     17 
     18 from rpy2.robjects.robject import RObjectMixin, RObject
---> 19 from rpy2.robjects.vectors import (BoolVector,
     20                                    IntVector,
     21                                    FloatVector,

/Users/fperez/usr/conda/lib/python3.5/site-packages/rpy2/robjects/vectors.py in <module>()
    334 
    335 
--> 336 class StrVector(Vector, StrSexpVector):
    337     """      Vector of string elements
    338 

TypeError: type 'rpy2.rinterface.StrSexpVector' is not an acceptable base type
```

This particular bug is [known and already fixed in rpy2 upstream, since version 2.7.4](https://bitbucket.org/rpy2/rpy2/issues/312).  The current version of rpy2 as of Apr 18, 2016 is [2.7.8](https://pypi.python.org/pypi/rpy2). Unfortunately conda still ships the outdated 2.7.0.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#759
