### ISSUE TITLE
Conda 4 is missing `conda package -L`

### ISSUE THREAD

**Issue by tadeu** [conda/conda#2378]
This was a nice command to check the contents of a package. Is there a new command to do this?

**Comment by tadeu** [comment]
Do your have a replacement for this command? Did it change into a different flag?

**Comment by nicoddemus** [comment]
Any answer on this one? I've used it more than once.

**Comment by kalefranz** [comment]
conda package and conda bundle both did things that made tarballs, which is more the prerogative of conda-build. The 4.2 feature release is a functionality cleanup that also removed conda init, all of them being experimental. 

conda package definitely had some useful flags that didn't have to do with building tarballs. We'll be bringing that functionality back in a future feature release.

**Comment by nicoddemus** [comment]
OK, thanks for the response!

**Comment by kalefranz** [comment]
Glad you bumped the ticket too.  We'll use it to track adding that functionality back.

**Comment by kalefranz** [comment]
`conda package` was added back some time ago.
