### ISSUE TITLE
When no condarc is found "no path!" is printed

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2389]
Why was https://github.com/conda/conda/blob/master/conda/config.py#L115 added?
Is this a debug statement which never got removed?

**Comment by msarahan** [comment]
Yes, sorry. I'll fix.

**Comment by wesm** [comment]
I just ran into this. Aside: is there good guidance for users looking to use conda outside of Anaconda (e.g. with some custom repo of packages but not really using anything in defaults)?
