### ISSUE TITLE
Flag to disable looking at installed packages?

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#2396]
Is there a flag to `install` to disable looking at installed packages? This is breaking my [sudoku](https://github.com/asmeurer/sudoku) example.

**Comment by mcg1969** [comment]
What do you mean in particular here? Any reason you can't just use `conda create` instead of `conda install`?

**Comment by asmeurer** [comment]
I did end up doing a conda create, but I was expecting to have a flag to do this.
