### ISSUE TITLE
gdal package failed to open kml

### ISSUE THREAD

**Issue by norbertbarbosa** [conda/conda#2398]
Seen Win8.1 x64 and win7 x64, after a clean 'conda install gdal' on a clean anaconda install

``` python
from osgeo import ogr
driver = ogr.GetDriverByName("KML")  # succeed: the KML driver is registered. Note that LIBKML not available
ds = driver.Open('mytest.kml') # always return None 
```

Note that creating a KML works:

``` python
ds = driver.CreateDataSource("out.kml")  # work: can add geometry, and generate KML
```

from KML driver documentation: http://www.gdal.org/drv_kml.html

> KML reading is only available if GDAL/OGR is built with the Expat XML Parser, otherwise only KML writing will be supported.'

-> seems the case

**Comment by fergalm** [comment]
I've encountered this same problem. Is there a work around, or something I can install to read kml files?

**Comment by pymonger** [comment]
conda-forge has v2.1.2 with Expat XML parser linked in but it causes downgrade of some packages. I created a conda package here v2.1.0 if you want to build it yourself. Otherwise you can just run "conda install -c gmanipon gdal".

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1690
