### ISSUE TITLE
KeyError: 'ansible-1.7.2-py27_0.tar.bz2' cloning env

### ISSUE THREAD

**Issue by merc85garcia** [conda/conda#2404]
conda create --name multiway --clone root
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
src_prefix: '/lium/buster1/garcia/miniconda'
dst_prefix: '/lium/buster1/garcia/miniconda/envs/multiway'
Packages: 171
Files: 1260
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/lium/buster1/garcia/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/lium/buster1/garcia/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'ansible-1.7.2-py27_0.tar.bz2'

conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.5
```

  conda-build version : not installed
       python version : 2.7.10.final.0
     requests version : 2.9.1
     root environment : /lium/buster1/garcia/miniconda  (writable)
  default environment : /lium/buster1/garcia/miniconda
     envs directories : /lium/buster1/garcia/miniconda/envs
        package cache : /lium/buster1/garcia/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

conda list
# packages in environment at /lium/buster1/garcia/miniconda:
# 

abstract-rendering        0.5.1               np110py27_0    defaults
alabaster                 0.7.7                    py27_0    defaults
anaconda                  2.5.0               np110py27_0    defaults
anaconda-client           1.2.2                    py27_0    defaults
ansible                   1.7.2                    py27_0    ActivisionGameScience
argcomplete               1.0.0                    py27_1    defaults
astropy                   1.1.1               np110py27_0    defaults
babel                     2.2.0                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.4.1                    py27_0    defaults
binstar                   0.12                          2    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.9.0                     <pip>
blaze-core                0.9.0                    py27_0    defaults
blocks (/lium/buster1/garcia/workspace/blocks) 0.0.1                     <pip>
bokeh                     0.11.0                   py27_0    defaults
boto                      2.39.0                   py27_0    defaults
bottleneck                1.0.0               np110py27_0    defaults
cairo                     1.12.18                       6    defaults
cdecimal                  2.3                      py27_0    defaults
cffi                      1.2.1                    py27_0    defaults
clyent                    1.2.0                    py27_0    defaults
colorama                  0.3.6                    py27_0    defaults
conda                     4.0.5                    py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
configobj                 5.0.6                    py27_0    defaults
cryptography              1.0.2                    py27_0    defaults
curl                      7.45.0                        0    defaults
cycler                    0.9.0                    py27_0    defaults
cython                    0.23.4                   py27_0    defaults
cytoolz                   0.7.5                    py27_0    defaults
datashape                 0.5.0                    py27_0    defaults
decorator                 4.0.6                    py27_0    defaults
docutils                  0.12                     py27_0    defaults
dynd                      f641248                   <pip>
dynd-python               0.7.1                    py27_0    defaults
ecdsa                     0.13                     py27_0    defaults
enum34                    1.1.2                    py27_0    defaults
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_0    defaults
flask                     0.10.1                   py27_1    defaults
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         0    defaults
fuel                      0.0.1                     <pip>
funcsigs                  0.4                      py27_0    defaults
futures                   3.0.3                    py27_0    defaults
gevent                    1.0.2                    py27_0    defaults
gevent-websocket          0.9.5                    py27_0    defaults
greenlet                  0.4.9                    py27_0    defaults
grin                      1.2.1                    py27_1    defaults
groundhog (/lium/buster1/garcia/workspace/GroundHog) 0.1.dev0                  <pip>
h5py                      2.5.0               np110py27_4    defaults
hdf5                      1.8.15.1                      2    defaults
idna                      2.0                      py27_0    defaults
ipaddress                 1.0.14                   py27_0    defaults
ipdb                      0.8.1                     <pip>
ipykernel                 4.2.2                    py27_0    defaults
ipython                   4.0.3                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0    defaults
ipython-qtconsole         4.0.1                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py27_0    defaults
jedi                      0.9.0                    py27_0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            0    defaults
jsonschema                2.4.0                    py27_0    defaults
jupyter                   1.0.0                    py27_1    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0    defaults
jupyter_console           4.1.0                    py27_0    defaults
jupyter_core              4.0.6                    py27_0    defaults
libdynd                   0.7.1                         0    defaults
libffi                    3.0.13                        0    defaults
libgfortran               1.0                           0    defaults
libpng                    1.6.17                        0    defaults
libsodium                 1.0.3                         0    defaults
libtiff                   4.0.6                         1    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        0    defaults
llvmlite                  0.8.0                    py27_0    defaults
lxml                      3.5.0                    py27_0    defaults
markupsafe                0.23                     py27_0    defaults
matplotlib                1.5.1               np110py27_0    defaults
mistune                   0.7.1                    py27_0    defaults
mkl                       11.3.1                        0    defaults
mkl-service               1.1.2                    py27_0    defaults
multipledispatch          0.4.8                    py27_0    defaults
nbconvert                 4.1.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.1                      py27_0    defaults
nmtpy (/lium/buster1/garcia/workspace/nmtpy) 0.1                       <pip>
nose                      1.3.7                    py27_0    defaults
notebook                  4.1.0                    py27_0    defaults
numba                     0.23.1              np110py27_0    defaults
numexpr                   2.4.6               np110py27_1    defaults
numpy                     1.10.4                   py27_0    defaults
odo                       0.4.0                    py27_0    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2f                        0    defaults
pandas                    0.17.1              np110py27_0    defaults
paramiko                  1.15.3                   py27_0    defaults
patchelf                  0.8                           0    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0               np110py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pexpect                   3.3                      py27_0    defaults
picklable-itertools       0.1.0                     <pip>
pickleshare               0.5                      py27_0    defaults
pillow                    3.1.0                    py27_0    defaults
pip                       8.1.1                    py27_1    defaults
pixman                    0.32.6                        0    defaults
ply                       3.8                      py27_0    defaults
progressbar2              2.7.3                     <pip>
psutil                    3.4.2                    py27_0    defaults
ptyprocess                0.5                      py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycosat                   0.6.1                    py27_0    <unknown>
pycparser                 2.14                     py27_0    defaults
pycrypto                  2.6.1                    py27_0    defaults
pycurl                    7.19.5.3                 py27_0    defaults
pydot                     1.0.28                   py27_0    defaults
pyflakes                  1.0.0                    py27_0    defaults
pygments                  2.1                      py27_0    defaults
pyopenssl                 0.15.1                   py27_1    defaults
pyparsing                 1.5.6                    py27_0    defaults
pyqt                      4.11.4                   py27_1    defaults
pytables                  3.2.2               np110py27_0    defaults
pytest                    2.8.5                    py27_0    defaults
python                    2.7.10                        2    defaults
python-dateutil           2.4.2                    py27_0    defaults
pytz                      2015.7                   py27_0    defaults
pyyaml                    3.11                     py27_1    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                         1    defaults
qtconsole                 4.1.1                    py27_0    defaults
readline                  6.2                           2    <unknown>
redis                     2.6.9                         0    defaults
redis-py                  2.10.3                   py27_0    defaults
requests                  2.9.1                    py27_0    defaults
rope                      0.9.4                    py27_1    defaults
scikit-image              0.11.3              np110py27_0    defaults
scikit-learn              0.17                np110py27_2    defaults
scipy                     0.17.0              np110py27_0    defaults
setuptools                19.6.2                   py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.1                    py27_0    defaults
sphinx                    1.3.5                    py27_0    defaults
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0    defaults
spyder                    2.3.8                    py27_0    defaults
spyder-app                2.3.8                    py27_0    defaults
sqlalchemy                1.0.11                   py27_0    defaults
sqlite                    3.9.2                         0    defaults
ssl_match_hostname        3.4.0.2                  py27_0    defaults
statsmodels               0.6.1               np110py27_0    defaults
sympy                     0.7.6.1                  py27_0    defaults
system                    5.8                           2    <unknown>
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_1    defaults
theano (/lium/buster1/garcia/workspace/Theano_new/Theano) 0.8.0.dev0                <pip>
tk                        8.5.18                        0    <unknown>
toolz                     0.7.4                    py27_0    defaults
tornado                   4.3                      py27_0    defaults
traitlets                 4.1.0                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
util-linux                2.21                          0    defaults
werkzeug                  0.11.3                   py27_0    defaults
wheel                     0.26.0                   py27_1    defaults
xlrd                      0.9.4                    py27_0    defaults
xlsxwriter                0.8.4                    py27_0    defaults
xlwt                      1.0.0                    py27_0    defaults
xz                        5.0.5                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         0    <unknown>

**Comment by tyler-thetyrant** [comment]
Closing outdated.
