### ISSUE TITLE
Activate virtual env by Python script 

### ISSUE THREAD

**Issue by FrankMN** [conda/conda#2411]
When I use virtual env, I can do the following in my wsgi script to activate venv 
`activate_this = '/path/to/env/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))`

But when I use conda,  I only can activate venv by shell script. Is it necessary to create a python script to do this?

**Comment by KBoehme** [comment]
I would also like to know this.

**Comment by kalefranz** [comment]
related: https://github.com/conda/conda/issues/6820
