### ISSUE TITLE
Error while "conda update anaconda"

### ISSUE THREAD

**Issue by tejasvinee** [conda/conda#2418]
Traceback: 
Traceback (most recent call last):
  File "<home>/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "<home>/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "<home>/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "<home>/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "<home>/anaconda/lib/python2.7/site-packages/conda/install.py", line 631, in link
    os.makedirs(dst_dir)
  File "<home>/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '<home>/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/tests'

Output of "conda info": 
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : osx-64
    conda version : 4.0.5
```

  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : <home>/anaconda  (writable)
  default environment : <home>/anaconda
     envs directories : <home>/anaconda/envs
        package cache : <home>/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by mcg1969** [comment]
We've been getting a lot of issues with Mac OSX installations outside of user's home directories. This is definitely something that needs to be diagnosed and addressed, but until it is, I strongly discourage attempts to install Anaconda outside of your home directory.

**Comment by tejasvinee** [comment]
I had installed it under <home>/anaconda - this is within the home
directory. Anything else you suspect to be the reason?

**Comment by mcg1969** [comment]
According to the output above, you installed it in "/" -- the system root directory.

**Comment by tejasvinee** [comment]
Hi,

Somehow the github formatting substituted "<home>" with "". Anaconda is
installed in "<home>/ anaconda" on my system.


Here's the output of "conda info".

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/tejaswiniganapathi/anaconda  (writable)
  default environment : /Users/tejaswiniganapathi/anaconda
     envs directories : /Users/tejaswiniganapathi/anaconda/envs
        package cache : /Users/tejaswiniganapathi/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

And here's the traceback without the substitution:
Traceback (most recent call last):
  File "/Users/tejaswiniganapathi/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/cli/main.py",
line 139, in main
    args_func(args, p)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/cli/main.py",
line 146, in args_func
    args.func(args, p)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py",
line 64, in execute
    install.install(args, parser, 'update')
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/cli/install.py",
line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/plan.py",
line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/instructions.py",
line 149, in execute_instructions
    cmd(state, arg)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/instructions.py",
line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/instructions.py",
line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File
"/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/conda/install.py",
line 631, in link
    os.makedirs(dst_dir)
  File "/Users/tejaswiniganapathi/anaconda/lib/python2.7/os.py", line 157,
in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied:
'/Users/tejaswiniganapathi/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/tests'

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.
