### ISSUE TITLE
Failure to install: ImportError: No module named auxlib

### ISSUE THREAD

**Issue by ssbarnea** [conda/conda#2420]
`pip install conda fails to install `auxlib`. Workaround is to manually install it before with pip install auxlib but that's clearly not normal.

I found this on OS X with pip 8.1.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
```
 pip install conda
Collecting conda
  Downloading conda-4.0.5.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 654kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5s/866_p9c16k59ygvyqnkmpv000000gn/T/pip-build-a1nv80ul/conda/setup.py", line 30, in <module>
        import auxlib  # a build-time dependency only
    ImportError: No module named 'auxlib'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5s/866_p9c16k59ygvyqnkmpv000000gn/T/pip-build-a1nv80ul/conda/
```

**Comment by kalefranz** [comment]
At the moment it's not safe to pip install conda.  The recommended way for Travis would be something like we have here: https://github.com/conda/conda/blob/master/utils/travis-bootstrap-conda.sh#L18

**Comment by entheologist** [comment]
I'm experiencing this problem too. I ran `pip3 install -U setuptools` hoping it would fix something but the problem just changed to an incompabiility problem:
```
  Could not find a version that satisfies the requirement condo (from versions: )
No matching distribution found for condo
```

**Comment by kalefranz** [comment]
Use miniconda to install conda.  Just like you can't `pip install python3`, you can't `pip install conda`.  At least if you're wanting to use conda as an application.

You can get miniconda from https://conda.io/miniconda.html
