### ISSUE TITLE
``deactivate`` adds miniconda/bin from path

### ISSUE THREAD

**Issue by montefra** [conda/conda#2424]
I have just installed miniconda3 for testing purposes. When installing I've said **not** to add the path to miniconda3/bin to the ``.bashrc`` file.

I've created an environment and activated.

    source miniconda3/bin/activate my_env
    discarding /home/user/miniconda3/bin from PATH  # which I don't have
    prepending /home/user/miniconda3/envs/my_env/bin to PATH

When I deactivated it it told me 

    discarding /home/user/miniconda3/envs/conda_hetdex/bin from PATH

but it silently added the path to miniconda3/bin, messing up my environment.

Since I asked not to add miniconda to my path, I would call it a bug.
Upon activation, conda should remember whether miniconda3/bin is on the path. When deactivating it should read it only if it was already there. I guess that it would be something similar to the way PS1 is saved in the CONDA_OLD_PS1 environment variable.

**Comment by msarahan** [comment]
Thanks for filing this issue.  This is fixed in master, but has not yet been released.  I'm going to leave this issue open until that release is verified to fix your issue.

**Comment by montefra** [comment]
Good to know :+1: and thanks for being so fast

Do you know when the next version is expected to be released?

**Comment by msarahan** [comment]
I don't know, unfortunately.  Sometime very soon, though - 1-2 week timescale.

**Comment by montefra** [comment]
I'll keep an eye for updates.

**Comment by kalefranz** [comment]
If you want to preview the release candidates for conda 4.1 and conda-env 2.5,

    conda config --add channels conda-team
    conda update conda conda-env
