### ISSUE TITLE
Conda update conda error

### ISSUE THREAD

**Issue by RobBW** [conda/conda#2426]
Traceback is in the middle of the following listing.
Only other notable fact is that I was updating after upgrading to El Capitan from Yosemite.

Log printout attached
[Log at 2016-05-03 21.55.16.txt](https://github.com/conda/conda/files/246647/Log.at.2016-05-03.21.55.16.txt)

RobW
:

**Comment by kalefranz** [comment]
@RobBW that just looks like your download failed.  Can you just try the operation again?

We should probably add in some retries when downloads fail rather than just bailing like that with an ugly stack trace.  But until then...

**Comment by RobBW** [comment]
thanks for the quick response.
You were right. It went perfectly the second time.
Herewith the short log:

[robw]$ conda update anaconda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/robw/anaconda:

The following packages will be UPDATED:

    anaconda:           custom-py27_0 --> 4.0.0-np110py27_0

The following packages will be DOWNGRADED:

    anaconda-navigator: 1.1.1-py27_0  --> 1.1.0-py27_0     
    conda-manager:      0.4.0-py27_0  --> 0.3.1-py27_0     

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
