### ISSUE TITLE
"undefined symbol: PyUnicodeUCS4_AsEncodedString" error during Anaconda2 Installation

### ISSUE THREAD

**Issue by zachnap** [conda/conda#2433]
Hello,

I am using CentOS 6.5 64-bit. I am trying to install Anaconda2-4.0.0-Linux-x86_64.sh. During installation I get the following error:

> ...
> installing: anaconda-4.0.0-np110py27_0 ...
> installing: conda-4.0.5-py27_0 ...
> installing: conda-build-1.20.0-py27_0 ...
> installing: conda-env-2.4.5-py27_0 ...
> Python 2.7.5
> creating default environment...
> Traceback (most recent call last):
>   File "/home/admin/anaconda2/pkgs/conda-4.0.5-py27_0/lib/python2.7/site-packages/conda/install.py", line 31, in <module>
>     import json
>   File "/home/admin/anaconda2/pkgs/python-2.7.11-0/lib/python2.7/json/**init**.py", line 108, in <module>
>     from .decoder import JSONDecoder
>   File "/home/admin/anaconda2/pkgs/python-2.7.11-0/lib/python2.7/json/decoder.py", line 5, in <module>
>     import struct
>   File "/home/admin/anaconda2/pkgs/python-2.7.11-0/lib/python2.7/struct.py", line 1, in <module>
>     from _struct import *
> ImportError: /home/admin/anaconda2/pkgs/python-2.7.11-0/lib/python2.7/lib-dynload/_struct.so: undefined symbol: PyUnicodeUCS4_AsEncodedString

I do have another version of Python installed, but I have installed Anaconda on multiple machines with alternate Python versions with no problems. Would appreciate any assistance, thanks.

**Comment by msarahan** [comment]
Ping @ilanschnell  - something is going wrong and your system Python is interfering.  I don't know why or how, unfortunately.  It certainly appears to be finding the correct packages.

**Comment by zachnap** [comment]
Is it possible to just uninstall Python 2.7.5 to correct the issue?

**Comment by msarahan** [comment]
Sure, that's worth a try.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1691
