### ISSUE TITLE
Tried to Install scikit-learn with conda, conda and Python modules removed

### ISSUE THREAD

**Issue by seancrowell** [conda/conda#2434]
Hi, I just tried to use conda to install scikit-learn on my Mac OS X Yosemite machine, and the install failed at the linking stage.  After the failure, I tried to run the install again, and the conda executable was nowhere to be found, as well as typical python modules (Numpy, etc) when I ran python directly.  I am reinstalling Anaconda now, which will replace the python modules, but I can't give any info from conda because it is gone!

**Comment by kalefranz** [comment]
This behavior has been completely fixed with transactions and rollbacks in conda 4.3.  No more conda uninstalling itself!
