### ISSUE TITLE
Can't Install opencv - caused by conflict

### ISSUE THREAD

**Issue by lunchboxav** [conda/conda#2448]
Thank you @msarahan for the suggestion in #2436 

Anyway, I tried installing `opencv` using

`conda install opencv`

Because I see that the package is available for Mac and I'm trying to utilize Conda as much as I can, even though, yes I know that I can simply build `opencv` and have the python package copied to the site-package.

However, this failed and I got this output 

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
  - bottleneck (target=bottleneck-1.0.0-np110py27_0.tar.bz2) -> numpy 1.10*|1.11*|1.9*
  - bottleneck (target=bottleneck-1.0.0-np110py27_0.tar.bz2) -> python 3.4*|3.5*
  - opencv
Use "conda info <package>" to see the dependencies for each package.
```

This is the output of `conda list`

```
#
alabaster                 0.7.7                    py27_0
anaconda                  4.0.0               np110py27_0
anaconda-client           1.4.0                    py27_0
anaconda-navigator        1.1.0                    py27_0
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               1.0.0                    py27_1
astropy                   1.1.2               np110py27_0
babel                     2.2.0                    py27_0
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bitarray                  0.8.1                    py27_0
blaze                     0.9.1                    py27_0
bokeh                     0.11.1                   py27_0
boto                      2.39.0                   py27_0
bottleneck                1.0.0               np110py27_0
cdecimal                  2.3                      py27_0
cffi                      1.5.2                    py27_0
chest                     0.2.3                    py27_0
cloudpickle               0.1.1                    py27_0
clyent                    1.2.1                    py27_0
colorama                  0.3.7                    py27_0
conda                     4.0.5                    py27_0
conda-build               1.20.0                   py27_0
conda-env                 2.4.5                    py27_0
conda-manager             0.3.1                    py27_0
configobj                 5.0.6                    py27_0
cryptography              1.3                      py27_0
curl                      7.45.0                        0
cycler                    0.10.0                   py27_0
cython                    0.23.4                   py27_1
cytoolz                   0.7.5                    py27_0
dask                      0.8.1                    py27_0
datashape                 0.5.1                    py27_0
decorator                 4.0.9                    py27_0
dill                      0.2.4                    py27_0
docutils                  0.12                     py27_0
dynd                      0.7.3.dev1                <pip>
dynd-python               0.7.2                    py27_0
enum34                    1.1.2                    py27_0
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
flask-cors                2.1.2                    py27_0
freetype                  2.5.5                         0
funcsigs                  0.4                      py27_0
futures                   3.0.3                    py27_0
gevent                    1.1.0                    py27_0
greenlet                  0.4.9                    py27_0
grin                      1.2.1                    py27_1
h5py                      2.5.0               np110py27_4
hdf5                      1.8.15.1                      2
heapdict                  1.0.0                    py27_0
idna                      2.0                      py27_0
ipaddress                 1.0.14                   py27_0
ipykernel                 4.3.1                    py27_0
ipython                   4.1.2                    py27_1
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.2                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
jpeg                      8d                            1
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_2
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0
jupyter_console           4.1.1                    py27_0
jupyter_core              4.1.0                    py27_0
libdynd                   0.7.2                         0
libpng                    1.6.17                        0
libtiff                   4.0.6                         1
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvmlite                  0.9.0                    py27_0
locket                    0.2.0                    py27_0
lxml                      3.6.0                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.5.1               np110py27_0
mistune                   0.7.2                    py27_1
mkl                       11.3.1                        0
mkl-service               1.1.2                    py27_0
mpmath                    0.19                     py27_0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.1.0                    py27_0
nbformat                  4.0.1                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2                      py27_0
nose                      1.3.7                    py27_0
notebook                  4.1.0                    py27_2
numba                     0.24.0              np110py27_0
numexpr                   2.5                 np110py27_0
numpy                     1.10.4                   py27_0
odo                       0.4.2                    py27_0
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2g                        0
pandas                    0.18.0              np110py27_0
partd                     0.3.2                    py27_1
path.py                   8.1.2                    py27_1
patsy                     0.4.0               np110py27_0
pep8                      1.7.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.5                      py27_0
pillow                    3.1.1                    py27_0
pip                       8.1.1                    py27_1
ply                       3.8                      py27_0
psutil                    4.1.0                    py27_1
ptyprocess                0.5                      py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.3                 py27_0
pyflakes                  1.1.0                    py27_0
pygments                  2.1.1                    py27_0
pyopenssl                 0.15.1                   py27_2
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_1
pytables                  3.2.2               np110py27_1
pytest                    2.8.5                    py27_0
python                    2.7.11                        0
python-dateutil           2.5.1                    py27_0
python.app                1.2                      py27_4
pytz                      2016.2                   py27_0
pyyaml                    3.11                     py27_1
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                         1
qtawesome                 0.3.2                    py27_0
qtconsole                 4.2.0                    py27_0
qtpy                      1.0                      py27_0
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.9.1                    py27_0
rope                      0.9.4                    py27_1
scikit-image              0.12.3              np110py27_0
scikit-learn              0.17.1              np110py27_0
scipy                     0.17.0              np110py27_0
setuptools                20.3                     py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.1                    py27_0
speechrecognition         3.4.3                     <pip>
sphinx                    1.3.5                    py27_0
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    2.3.8                    py27_1
sqlalchemy                1.0.12                   py27_0
sqlite                    3.9.2                         0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1               np110py27_0
sympy                     1.0                      py27_0
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_1
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.2.1                    py27_0
unicodecsv                0.14.1                   py27_0
werkzeug                  0.11.4                   py27_0
wheel                     0.29.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.8.4                    py27_0
xlwings                   0.7.0                    py27_0
xlwt                      1.0.0                    py27_0
xz                        5.0.5                         1
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         0
```

Also, this is the output of `conda info`

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/kotakmakan/anaconda  (writable)
  default environment : /Users/kotakmakan/anaconda
     envs directories : /Users/kotakmakan/anaconda/envs
        package cache : /Users/kotakmakan/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

As this is the first time using Conda, I'd really love to tackle this issue so that in the future I know what to do

Cheers :)

**Comment by mcg1969** [comment]
According to `conda install opencv`, the only version we have on Mac OSX requires `numpy 1.7*`. It's way out of date. You need a different build of opencv.

**Comment by mcg1969** [comment]
It looks like `conda-forge` has a build of `opencv` that will work for you. Try `conda install -c conda-forge opencv`.

**Comment by UkiDLucas** [comment]
```
$ conda install -c conda-forge opencv

  - opencv -> python 2.7*
  - python 3.6*
```

**Comment by jd20** [comment]
I'm seeing the same issue with Python 3.6, trying to install opencv using conda install fails. I get:

```
$ conda install -c conda-forge opencv

UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv -> python 3.5* -> sqlite 3.9.*
  - opencv -> python 3.5* -> xz 5.0.*
  - python 3.6*
```

**Comment by vivekpatani** [comment]
@jd20 Any work around yet?

**Comment by jd20** [comment]
@vivekpatani Not really, other than to switch to using virtualenv specifically for OpenCV 3.x on Sierra. These instructions worked for me (with some tweaks for Python 3.6 instead of 3.5): http://www.pyimagesearch.com/2016/12/05/macos-install-opencv-3-and-python-3-5/

**Comment by kalefranz** [comment]
Perhaps file an issue with conda-forge to update opencv for python 3.6 compatibility?

**Comment by sml0820** [comment]
@vivekpatani @jd20 I put together a work around here: http://stackoverflow.com/questions/41873941/cant-install-opencv3-on-anaconda3-python3-6-on-macos/42704182#42704182

**Comment by awithey** [comment]
As you are using Python 3, install opencv3:
conda install -c menpo opencv3

**Comment by jo-m** [comment]
@awithey the menpo opencv3 package does not seem to work together with python3 (Windows 10):

```
$ conda install -c menpo opencv3

UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv3 -> python 2.7*
  - python 3.6*
```

**Comment by vivekpatani** [comment]
@jo-m @sml0820 @jd20
The only workaround I found is to dumb down your python by a version.
```
 conda install python=3.5
conda install -c menpo opencv3
```

Until conda finds a solution to this, it would be a good work around, since you'd be staying in the conda environment without breaking a sweat!

**Comment by jo-m** [comment]
Yes, I did the same now. However, I did it in a conda venv:

    conda create -yn opencvenv python=3.5.2
    activate opencvenv
    conda install -c menpo opencv3

**Comment by irobiul** [comment]
UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv -> numpy 1.9* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by irobiul** [comment]
How to fix that problem ? I got a suggestion that to use `conda install -c menpo opencv3` . now I got above error. 

<img width="994" alt="screenshot 2017-02-25 00 32 50" src="https://cloud.githubusercontent.com/assets/1263093/23824298/16087886-069e-11e7-8319-93b155b9c489.png">


`Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.1.6
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : /Users/robiulislam/anaconda  (writable)
    default environment : /Users/robiulislam/anaconda
       envs directories : /Users/robiulislam/anaconda/envs
                          /Users/robiulislam/.conda/envs
          package cache : /Users/robiulislam/anaconda/pkgs
                          /Users/robiulislam/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`


`# packages in environment at /Users/robiulislam/anaconda:
#
_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-clean            1.1.0                    py36_0  
anaconda-client           1.6.2                    py36_0  
anaconda-fusion           1.0.2                    py36_0    anaconda-fusion
anaconda-navigator        1.5.0                    py36_0  
anaconda-project          0.4.1                    py36_0  
appdirs                   1.4.3                     <pip>
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bokeh                     0.12.3                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
bzip2                     1.0.6                         3  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
cmake                     3.6.3                         0    anaconda
colorama                  0.3.7                    py36_0  
conda                     4.3.14                   py36_0    anaconda
conda-build               2.1.6                    py36_0  
conda-env                 2.6.0                         0    anaconda
conda-verify              2.0.0                    py36_0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.0                   py36_0  
datashape                 0.5.4                    py36_0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
Django                    1.10.5                    <pip>
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_1  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
filelock                  2.0.7                    py36_0  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
graphviz                  0.5.2                     <pip>
greenlet                  0.4.12                   py36_0  
h5py                      2.6.0               np111py36_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.5                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.0                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
Keras                     1.2.1                     <pip>
launcher                  1.0.0                         3  
lazy-object-proxy         1.2.2                    py36_0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.16.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mccabe                    0.6.1                     <pip>
mistune                   0.7.3                    py36_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
ncurses                   5.9                          10  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py36_1  
notebook                  4.2.3                    py36_0  
numba                     0.31.0              np111py36_0  
numexpr                   2.6.2               np111py36_0  
numpy                     1.11.3                   py36_0  
numpy                     1.12.0                    <pip>
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
opencv-python             3.2.0.6                   <pip>
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py36_1  
pandocfilters             1.4.1                    py36_0  
partd                     0.3.7                    py36_0  
path.py                   10.1                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_1  
pip                       9.0.1                    py36_1  
pkginfo                   1.4.1                    py36_0  
ply                       3.10                     py36_0  
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.2.0                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pylint                    1.6.5                     <pip>
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyparsing                 2.1.10                    <pip>
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.6                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
pytz                      2016.10                  py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         0  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.13.0                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.3                    py36_0  
sqlalchemy                1.1.6                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np111py36_0  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
Theano                    0.8.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        1.2.6                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.2                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
`

**Comment by vivekpatani** [comment]
@irobiul Can you please make sure you are importing the correct packages? Can you paste complete code on pastebin and send us a link?

**Comment by irobiul** [comment]
`import cv2

img = cv2.imread('test1.png')

cv2.imshow('Amanda', img)
cv2.waitKey(1000)
cv2.destroyAllWindows()` 


@vivekpatani  I got error 

`error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage`

**Comment by vivekpatani** [comment]
@irobiul Your issue is not related to the current issue, it is about failing to find GTK - Image viewer or whatever equivalent lib works for your OS.
```cv2.imshow('Amanda',img)``` is causing the issue.

**Comment by irobiul** [comment]
@vivekpatani; So, how can I solve that problem ?

**Comment by anonym24** [comment]
@connect2robiul can your read the comment higher you first comment? downgrade you python 3.6 to python 3.5 first!

**Comment by ariaaay** [comment]
I had the following error when I try 
`conda install -c menpo opencv3`

UnsatisfiableError: The following specifications were found to be in conflict:
  - caffe
  - opencv3

Could anyone help with this?

**Comment by DaliaMarzouk** [comment]
I encountered the same error and the following steps solved the problem
1- conda uninstall -c conda-forge opencv3
2- conda install python=3.5
3- conda install -c conda-forge opencv3

**Comment by farazahmad759** [comment]
**My command:**
conda install -c menpo opencv3 python=3.6
===========================================================
**Error:**
UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv3 -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
===========================================================
**Solution:**
conda install -c menpo opencv3 python=2.7
It downgrades the packages to python2.7 from python3.6.

**Comment by anonym24** [comment]
@farazahmad759 bad solution (from python 3 to python 2...)
just see previous comments above yours
you just need to install opencv 3.5 (not 3.6)

**Comment by iqqmuT** [comment]
I had to create a new conda environment:

1. `conda create -n myenv python=3.5`
2. `conda activate myenv`
3. `conda install -c menpo opencv3`

I'm using conda v4.7.10 on Linux.

**Comment by ekellogg** [comment]
I fixed it using pip
https://pypi.org/project/opencv-python/

**Comment by RorySpeirs** [comment]
On Windows at least, OpenCV can be installed by DOWNGRADING some packages. This can be done automatically by updating _anaconda_ using the following commands:

`conda update conda
conda update anaconda
conda install opencv`

**Comment by lemon-bean** [comment]
A conflict lived 4 years......

**Comment by zealous331** [comment]
Well, the conflict still occurs today..... wow....

**Comment by 21Ansh** [comment]
strange after 4 year there is no solution yet
