### ISSUE TITLE
downgrading from conda 4.1.0rc1 to 4.0.5 removes activate script

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2450]
see trace below

``` bash
$ conda install conda=4.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications ............

Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be DOWNGRADED:

    conda: 4.1.0rc1-py27_0 conda-team --> 4.0.5-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|############################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################| 100%

$ source activate testenv
-bash: activate: No such file or directory
```

**Comment by ijstokes** [comment]
I needed to also downgrade `conda-env`.  Not sure if that should have been obvious to me, or if it should have happened automatically:

```
conda install conda-env=2.4.5 conda=4.0.5
```

**Comment by msarahan** [comment]
This is something we're going to have to be very careful about.  Those two are tied intimately at this version, because this version is where the activate scripts moved (back) from conda-env to conda.  If there's an automatic way to do this with pinning, we should do it.

**Comment by mcg1969** [comment]
@msarahan, try adjusting the dependencies for your new version of `conda-env` so that it depends on `conda >=4.1.0rc1`. I think I'd go ahead and add a circular dependency to `conda` too; that is, make the RC depend on your latest version of `conda-env`.

**Comment by ijstokes** [comment]
@msarahan and @mcg1969 I would like to mention this issue: https://github.com/Anaconda-Platform/anaconda-client/issues/236

In my head it makes sense that conda, anaconda-client, and conda-env are three different Python packages, but I also feel like we should consider if everyone would be best served by them being linked into a single Conda package and installed together.  I believe they are tightly linked.

**Comment by mcg1969** [comment]
I agree about unifying `conda` and `conda-env`. From an OSS perspective it doesn't strike me that we can or should include `anaconda-client` in the same way. Strictly speaking it is not essential for situations where `conda` is used outside of our ecosystem (which is something we intend to enable).

**Comment by ijstokes** [comment]
Yes, I understand your point.  But Conda references `anaconda-client` commands (e.g. see https://github.com/ContinuumIO/docs/issues/156).  So they are already coupled.  The issue I referenced has some examples of the weird situations one gets into right now when Anaconda is not installed.

**Comment by mcg1969** [comment]
That doesn't convince me, I'm afraid. If anything it tells me anaconda-client is _too_ entangled into `conda`, or its branding needs to be removed.

I'm seeing two different things happening in your linked example. The first is the `Using Anaconda Cloud api` message. That only appears if `anaconda-client` is installed; `conda` functionality degrades gracefully if that is not the case. You lose functionality like binstar token processing but if someone relies wholly on open channels they don't need it.

The other thing is the reference to `anaconda search`. That reference should be made conditional on the existence of `anaconda-client`; at the very least, it should instruct the user to install anaconda-client to obtain that functionality. 

Alternatively, the API elements that `anaconda-client` folds into `conda` should be made more generic, so that `anaconda search` becomes `conda search`.

**Comment by mcg1969** [comment]
OK, I find myself softening to the idea of linking them together.

I do think we need to do a better job of making `conda`'s references to Anaconda more generic. We can figure out how to do that. We need `conda` to behave sensibly if `anaconda-client` is not installed. But I think we should define a very plugin API that `conda` could use for search functionality and perhaps even the token-based authentication. `anaconda-client` would then be but an *instance* of this plugin. 

With this in mind, it may indeed make sense for `anaconda-client` to be installed whenever `conda` is installed from anaconda.org. If a third party implemented their own conda server, _they_ could configure their `conda` dependencies to automatically pull down _their_ client.

If the plugin API were properly designed, `conda` could interact with multiple instances of these API plugins, supporting search and authentication across multiple servers.

**Comment by kalefranz** [comment]
I think we can close this ticket now.  All of these problems have been addressed.  Conda no longer has any `binstar_client` imports whatsoever.
