### ISSUE TITLE
conda remove curl

### ISSUE THREAD

**Issue by mpbill** [conda/conda#2455]
I am trying to remove the version of curl which conda includes because I believe it is causing an issue with another program.  [yaourt issue](https://github.com/archlinuxfr/yaourt/issues/86)  however the command `conda remove curl` results in conda saying it is going to downgrade python and several other packages.  I am attaching the full output of `conda remove curl`.
[condaRemoveCurl.txt](https://github.com/conda/conda/files/256290/condaRemoveCurl.txt)

**Comment by mcg1969** [comment]
OK, now that is weird. I believe the new version of `conda` will fix this. In the meanwhile, I recommend doing `conda remove anaconda` before you do `conda remove curl`. That will remove the `anaconda` metapackage, but not any of the truly useful packages, and I think that's part of the problem.

**Comment by mcg1969** [comment]
@kalefranz, I have confirmed that `master` does not do this, but rather removes `anaconda`, `pycurl`, and `curl`.
