### ISSUE TITLE
'noarch_python' and header files

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#2456]
I made a conda-forge recipe for pybind11, which is producing platform-dependent packages. 

I think that pybind11 should be a `noarch_python` package. It does not hold any binaries and has a universal pypi wheel.

The issue is that it holds headers (it is a header-only library), plus some pure python. `noarch_python` does not support the case where there are headers.

**Comment by msarahan** [comment]
What is the error?

Also, on conda-forge, noarch needs modification of the CI scripts also, so that they won't build the same noarch package with each python version.  This is definitely something that needs work, and it needs work in both conda-build and in conda-forge.

**Comment by msarahan** [comment]
Issue moved to [conda/conda-build #934](https://github.com/conda/conda-build/issues/934) via [**ZenHub.io**](https://www.zenhub.io/)
