### ISSUE TITLE
4.x solver

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2462]
Attempting to take my root environment from python 2.7 to python 3. 
Terminal output in second message.

**Comment by kalefranz** [comment]
kfranz@0283:~/continuum/conda *4.0.x ❯ conda install python=3
    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata: ....
    Solving package specifications: ....

    The following specifications were found to be in conflict:
      - enum34 (target=enum34-1.0.4-py27_0.tar.bz2) -> python 2.6*|2.7*|3.3*
      - gevent-websocket (target=gevent-websocket-0.9.3-py27_0.tar.bz2) -> gevent 0.13.7|0.13.8|1.0|1.0.1|1.0.2
      - gevent-websocket (target=gevent-websocket-0.9.3-py27_0.tar.bz2) -> python 2.6*|2.7*
      - grin (target=grin-1.2.1-py27_1.tar.bz2) -> python 2.6*|2.7*
      - ipaddress (target=ipaddress-1.0.14-py27_0.tar.bz2) -> python 2.6*|2.7*
      - pyaudio (target=pyaudio-0.2.7-py27_0.tar.bz2) -> python 2.7*
      - python 3*
      - raml (target=raml-0.11.7-py27_0.tar.bz2) -> python 2.7*
      - uwsgi (target=uwsgi-2.0.12-py27_0.tar.bz2) -> python 2.7*
    Use "conda info <package>" to see the dependencies for each package.
    (1)kfranz@0283:~/continuum/conda *4.0.x ❯ conda uninstall enum34 gevent-websocket grin ipaddress pyaudio raml
    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for package removal in environment /conda:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        krb5-1.13.2                |                0         1.2 MB
        libdynd-0.6.5              |                0         3.9 MB
        openssl-1.0.1k             |                1         2.5 MB
        curl-7.43.0                |                1         391 KB
        python-3.4.0               |                0        18.8 MB
        _license-1.1               |           py34_1          72 KB
        alabaster-0.7.6            |           py34_0          14 KB
        appnope-0.1.0              |           py34_0           4 KB
        appscript-1.0.1            |           py34_0         125 KB
        backports_abc-0.4          |           py34_0           5 KB
        beautifulsoup4-4.4.1       |           py34_0         122 KB
        bitarray-0.8.1             |           py34_0          55 KB
        boto-2.38.0                |           py34_0         1.4 MB
        cdecimal-2.3               |           py34_0         131 KB
        colorama-0.3.3             |           py34_0          17 KB
        conda-env-2.4.5            |           py34_0          25 KB
        cython-0.23.4              |           py34_1         2.2 MB
        cytoolz-0.7.4              |           py34_0         244 KB
        decorator-4.0.4            |           py34_0           6 KB
        docutils-0.12              |           py34_0         672 KB
        et_xmlfile-1.0.1           |           py34_0          15 KB
        fastcache-1.0.2            |           py34_0          23 KB
        funcsigs-0.4               |           py34_0          19 KB
        futures-3.0.3              |           py34_0          14 KB
        greenlet-0.4.9             |           py34_0          13 KB
        idna-2.0                   |           py34_0         122 KB
        ipython_genutils-0.1.0     |           py34_0          34 KB
        itsdangerous-0.24          |           py34_0          16 KB
        jdcal-1.0                  |           py34_0           9 KB
        jedi-0.9.0                 |           py34_0         196 KB
        jsonschema-2.4.0           |           py34_0          53 KB
        llvmlite-0.8.0             |           py34_0         6.4 MB
        markupsafe-0.23            |           py34_0          23 KB
        mkl-service-1.1.2          |           py34_0           6 KB
        multipledispatch-0.4.8     |           py34_0          12 KB
        nose-1.3.7                 |           py34_0         195 KB
        numpy-1.9.3                |           py34_1         2.6 MB
        path.py-8.1.2              |           py34_1          46 KB
        pep8-1.6.2                 |           py34_0          27 KB
        pexpect-3.3                |           py34_0          62 KB
        pillow-3.0.0               |           py34_1         489 KB
        ply-3.8                    |           py34_0          72 KB
        psutil-3.3.0               |           py34_0         104 KB
        ptyprocess-0.5             |           py34_0          19 KB
        py-1.4.30                  |           py34_0         127 KB
        pyasn1-0.1.9               |           py34_0          57 KB
        pycosat-0.6.1              |           py34_0          53 KB
        pycparser-2.14             |           py34_0         151 KB
        pycrypto-2.6.1             |           py34_0         459 KB
        pycurl-7.19.5.1            |           py34_2          42 KB
        pyflakes-1.0.0             |           py34_0          57 KB
        pygments-2.0.2             |           py34_0         1.1 MB
        pymongo-3.0.3              |           py34_0         255 KB
        pyparsing-2.0.3            |           py34_0          66 KB
        python.app-1.2             |           py34_4           7 KB
        pytz-2015.7                |           py34_0         173 KB
        pyyaml-3.11                |           py34_1         144 KB
        pyzmq-14.7.0               |           py34_1         310 KB
        redis-py-2.10.3            |           py34_0          73 KB
        requests-2.9.1             |           py34_0         648 KB
        rope-0.9.4                 |           py34_1         239 KB
        ruamel_yaml-0.11.7         |           py34_0         165 KB
        setuptools-20.7.0          |           py34_0         459 KB
        simplegeneric-0.8.1        |           py34_0           6 KB
        sip-4.16.9                 |           py34_0         210 KB
        six-1.10.0                 |           py34_0          17 KB
        snowballstemmer-1.2.0      |           py34_0          78 KB
        sphinx_rtd_theme-0.1.7     |           py34_0         209 KB
        sqlalchemy-1.0.9           |           py34_0         1.4 MB
        ssl_match_hostname-3.4.0.2 |           py34_0           6 KB
        toolz-0.7.4                |           py34_0          53 KB
        ujson-1.33                 |           py34_0          19 KB
        unicodecsv-0.14.1          |           py34_0          21 KB
        werkzeug-0.11.2            |           py34_0         420 KB
        xlrd-0.9.4                 |           py34_0         182 KB
        xlsxwriter-0.7.7           |           py34_0         185 KB
        xlwt-1.0.0                 |           py34_0         158 KB
        abstract-rendering-0.5.1   |       np19py34_0          43 KB
        argcomplete-1.0.0          |           py34_1          33 KB
        astropy-1.0.4              |       np19py34_0         5.3 MB
        babel-2.1.1                |           py34_0         2.3 MB
        bottleneck-1.0.0           |       np19py34_0         153 KB
        cffi-1.2.1                 |           py34_0         172 KB
        clyent-1.2.0               |           py34_0          13 KB
        conda-4.0.5                |           py34_0         189 KB
        configobj-5.0.6            |           py34_0          51 KB
        cycler-0.9.0               |           py34_0           6 KB
        dynd-python-0.6.5          |       np19py34_0         390 KB
        gevent-1.1.0               |           py34_0         470 KB
        h5py-2.5.0                 |       np19py34_3         688 KB
        jinja2-2.8                 |           py34_0         301 KB
        lxml-3.4.4                 |           py34_0         946 KB
        networkx-1.10              |           py34_0         1.1 MB
        nltk-3.1                   |           py34_0         1.8 MB
        numba-0.22.1               |       np19py34_0         1.4 MB
        numexpr-2.4.4              |       np19py34_0         105 KB
        patsy-0.4.0                |       np19py34_0         367 KB
        pickleshare-0.5            |           py34_0           8 KB
        pip-8.1.1                  |           py34_1         1.6 MB
        pyqt-4.11.4                |           py34_1         4.0 MB
        pytest-2.8.5               |           py34_0         226 KB
        python-dateutil-2.4.2      |           py34_0         221 KB
        scipy-0.16.0               |       np19py34_1        11.4 MB
        singledispatch-3.4.0.3     |           py34_0          13 KB
        sympy-0.7.6.1              |           py34_0         6.5 MB
        tornado-4.3                |           py34_0         578 KB
        traitlets-4.0.0            |           py34_0          93 KB
        virtualenv-13.0.1          |           py34_0         1.6 MB
        xlwings-0.5.0              |           py34_0         289 KB
        anaconda-client-1.4.0      |           py34_0         102 KB
        conda-build-1.20.1         |           py34_0         226 KB
        cryptography-1.0.2         |           py34_0         377 KB
        datashape-0.5.0            |           py34_0          91 KB
        flask-0.10.1               |           py34_1         135 KB
        ipython-4.0.1              |           py34_0         973 KB
        jupyter_core-4.0.6         |           py34_0          49 KB
        matplotlib-1.4.3           |       np19py34_3        41.1 MB
        openpyxl-2.2.6             |           py34_0         186 KB
        pandas-0.16.2              |       np19py34_0         5.5 MB
        pytables-3.2.2             |       np19py34_0         1.6 MB
        scikit-learn-0.16.1        |       np19py34_0         3.3 MB
        sockjs-tornado-1.0.1       |           py34_0          32 KB
        sphinx-1.3.1               |           py34_0         1.2 MB
        terminado-0.5              |           py34_1          18 KB
        anaconda-build-0.14.1      |           py34_0          95 KB
        bokeh-0.10.0               |           py34_0         3.9 MB
        jupyter_client-4.1.1       |           py34_0          92 KB
        nbformat-4.0.1             |           py34_0         114 KB
        odo-0.3.4                  |           py34_0         163 KB
        pyopenssl-0.15.1           |           py34_1         157 KB
        scikit-image-0.11.3        |       np19py34_0        15.9 MB
        statsmodels-0.6.1          |       np19py34_0         4.7 MB
        blaze-core-0.8.3           |           py34_0         511 KB
        ipykernel-4.1.1            |           py34_0         115 KB
        nbconvert-4.0.0            |           py34_0         270 KB
        jupyter_console-4.0.3      |           py34_0          23 KB
        notebook-4.0.6             |           py34_0         4.3 MB
        qtconsole-4.1.1            |           py34_0         129 KB
        ipython-notebook-4.0.4     |           py34_0           5 KB
        ipython-qtconsole-4.0.1    |           py34_0           4 KB
        ipywidgets-4.1.0           |           py34_0         100 KB
        spyder-2.3.8               |           py34_0         2.0 MB
        jupyter-1.0.0              |           py34_1           2 KB
        spyder-app-2.3.8           |           py34_0           7 KB
        ------------------------------------------------------------
                                               Total:       179.2 MB

    The following NEW packages will be INSTALLED:

        krb5:               1.13.2-0

    The following packages will be REMOVED:

        enum34:             1.0.4-py27_0
        gevent-websocket:   0.9.3-py27_0
        grin:               1.2.1-py27_1
        ipaddress:          1.0.14-py27_0
        pyaudio:            0.2.7-py27_0
        raml:               0.11.7-py27_0
        uwsgi:              2.0.12-py27_0

    The following packages will be UPDATED:

        _license:           1.1-py27_1         --> 1.1-py34_1
        abstract-rendering: 0.5.1-np110py27_0  --> 0.5.1-np19py34_0
        alabaster:          0.7.6-py27_0       --> 0.7.6-py34_0
        anaconda-build:     0.14.1-py27_0      --> 0.14.1-py34_0
        anaconda-client:    1.4.0-py27_0       --> 1.4.0-py34_0
        appnope:            0.1.0-py27_0       --> 0.1.0-py34_0
        appscript:          1.0.1-py27_0       --> 1.0.1-py34_0
        argcomplete:        1.0.0-py27_1       --> 1.0.0-py34_1
        babel:              2.1.1-py27_0       --> 2.1.1-py34_0
        backports_abc:      0.4-py27_0         --> 0.4-py34_0
        beautifulsoup4:     4.4.1-py27_0       --> 4.4.1-py34_0
        bitarray:           0.8.1-py27_0       --> 0.8.1-py34_0
        blaze-core:         0.8.3-py27_0       --> 0.8.3-py34_0
        bokeh:              0.10.0-py27_0      --> 0.10.0-py34_0
        boto:               2.38.0-py27_0      --> 2.38.0-py34_0
        bottleneck:         1.0.0-np110py27_0  --> 1.0.0-np19py34_0
        cdecimal:           2.3-py27_0         --> 2.3-py34_0
        cffi:               1.2.1-py27_0       --> 1.2.1-py34_0
        clyent:             1.2.0-py27_0       --> 1.2.0-py34_0
        colorama:           0.3.3-py27_0       --> 0.3.3-py34_0
        conda-build:        1.20.1-py27_0      --> 1.20.1-py34_0
        configobj:          5.0.6-py27_0       --> 5.0.6-py34_0
        cryptography:       1.0.2-py27_0       --> 1.0.2-py34_0
        cycler:             0.9.0-py27_0       --> 0.9.0-py34_0
        cython:             0.23.4-py27_1      --> 0.23.4-py34_1
        cytoolz:            0.7.4-py27_0       --> 0.7.4-py34_0
        datashape:          0.4.7-np110py27_1  --> 0.5.0-py34_0
        decorator:          4.0.4-py27_0       --> 4.0.4-py34_0
        docutils:           0.12-py27_0        --> 0.12-py34_0
        et_xmlfile:         1.0.1-py27_0       --> 1.0.1-py34_0
        fastcache:          1.0.2-py27_0       --> 1.0.2-py34_0
        flask:              0.10.1-py27_1      --> 0.10.1-py34_1
        funcsigs:           0.4-py27_0         --> 0.4-py34_0
        gevent:             1.0.1-py27_0       --> 1.1.0-py34_0
        greenlet:           0.4.9-py27_0       --> 0.4.9-py34_0
        idna:               2.0-py27_0         --> 2.0-py34_0
        ipykernel:          4.1.1-py27_0       --> 4.1.1-py34_0
        ipython:            4.0.1-py27_0       --> 4.0.1-py34_0
        ipython-notebook:   4.0.4-py27_0       --> 4.0.4-py34_0
        ipython-qtconsole:  4.0.1-py27_0       --> 4.0.1-py34_0
        ipython_genutils:   0.1.0-py27_0       --> 0.1.0-py34_0
        ipywidgets:         4.1.0-py27_0       --> 4.1.0-py34_0
        itsdangerous:       0.24-py27_0        --> 0.24-py34_0
        jdcal:              1.0-py27_0         --> 1.0-py34_0
        jedi:               0.9.0-py27_0       --> 0.9.0-py34_0
        jinja2:             2.8-py27_0         --> 2.8-py34_0
        jsonschema:         2.4.0-py27_0       --> 2.4.0-py34_0
        jupyter:            1.0.0-py27_1       --> 1.0.0-py34_1
        jupyter_client:     4.1.1-py27_0       --> 4.1.1-py34_0
        jupyter_console:    4.0.3-py27_0       --> 4.0.3-py34_0
        jupyter_core:       4.0.6-py27_0       --> 4.0.6-py34_0
        llvmlite:           0.8.0-py27_0       --> 0.8.0-py34_0
        lxml:               3.4.4-py27_0       --> 3.4.4-py34_0
        markupsafe:         0.23-py27_0        --> 0.23-py34_0
        mistune:            0.7.2-py27_0       --> 0.7.2-py34_1
        mkl-service:        1.1.2-py27_0       --> 1.1.2-py34_0
        multipledispatch:   0.4.8-py27_0       --> 0.4.8-py34_0
        nbconvert:          4.0.0-py27_0       --> 4.0.0-py34_0
        nbformat:           4.0.1-py27_0       --> 4.0.1-py34_0
        networkx:           1.10-py27_0        --> 1.10-py34_0
        nltk:               3.1-py27_0         --> 3.1-py34_0
        nose:               1.3.7-py27_0       --> 1.3.7-py34_0
        notebook:           4.0.6-py27_0       --> 4.0.6-py34_0
        numba:              0.22.1-np110py27_0 --> 0.22.1-np19py34_0
        numexpr:            2.4.4-np110py27_0  --> 2.4.4-np19py34_0
        odo:                0.3.4-py27_0       --> 0.3.4-py34_0
        openpyxl:           2.2.6-py27_0       --> 2.2.6-py34_0
        path.py:            8.1.2-py27_1       --> 8.1.2-py34_1
        patsy:              0.4.0-np110py27_0  --> 0.4.0-np19py34_0
        pep8:               1.6.2-py27_0       --> 1.6.2-py34_0
        pexpect:            3.3-py27_0         --> 3.3-py34_0
        pickleshare:        0.5-py27_0         --> 0.5-py34_0
        pillow:             3.0.0-py27_1       --> 3.0.0-py34_1
        pip:                8.1.1-py27_1       --> 8.1.1-py34_1
        ply:                3.8-py27_0         --> 3.8-py34_0
        psutil:             3.3.0-py27_0       --> 3.3.0-py34_0
        ptyprocess:         0.5-py27_0         --> 0.5-py34_0
        py:                 1.4.30-py27_0      --> 1.4.30-py34_0
        pyasn1:             0.1.9-py27_0       --> 0.1.9-py34_0
        pycosat:            0.6.1-py27_0       --> 0.6.1-py34_0
        pycparser:          2.14-py27_0        --> 2.14-py34_0
        pycrypto:           2.6.1-py27_0       --> 2.6.1-py34_0
        pyflakes:           1.0.0-py27_0       --> 1.0.0-py34_0
        pygments:           2.0.2-py27_0       --> 2.0.2-py34_0
        pymongo:            3.0.3-py27_0       --> 3.0.3-py34_0
        pyopenssl:          0.15.1-py27_1      --> 0.15.1-py34_1
        pyparsing:          2.0.3-py27_0       --> 2.0.3-py34_0
        pyqt:               4.11.4-py27_1      --> 4.11.4-py34_1
        pytables:           3.2.2-np110py27_0  --> 3.2.2-np19py34_0
        pytest:             2.8.5-py27_0       --> 2.8.5-py34_0
        python:             2.7.11-0           --> 3.4.0-0
        python-dateutil:    2.4.2-py27_0       --> 2.4.2-py34_0
        python.app:         1.2-py27_4         --> 1.2-py34_4
        pytz:               2015.7-py27_0      --> 2015.7-py34_0
        pyyaml:             3.11-py27_1        --> 3.11-py34_1
        pyzmq:              14.7.0-py27_1      --> 14.7.0-py34_1
        qtconsole:          4.1.1-py27_0       --> 4.1.1-py34_0
        redis-py:           2.10.3-py27_0      --> 2.10.3-py34_0
        requests:           2.9.1-py27_0       --> 2.9.1-py34_0
        rope:               0.9.4-py27_1       --> 0.9.4-py34_1
        ruamel_yaml:        0.11.7-py27_0      --> 0.11.7-py34_0
        scikit-image:       0.11.3-np110py27_0 --> 0.11.3-np19py34_0
        scipy:              0.16.0-np110py27_1 --> 0.16.0-np19py34_1
        setuptools:         20.7.0-py27_0      --> 20.7.0-py34_0
        simplegeneric:      0.8.1-py27_0       --> 0.8.1-py34_0
        singledispatch:     3.4.0.3-py27_0     --> 3.4.0.3-py34_0
        sip:                4.16.9-py27_0      --> 4.16.9-py34_0
        six:                1.10.0-py27_0      --> 1.10.0-py34_0
        snowballstemmer:    1.2.0-py27_0       --> 1.2.0-py34_0
        sockjs-tornado:     1.0.1-py27_0       --> 1.0.1-py34_0
        sphinx:             1.3.1-py27_0       --> 1.3.1-py34_0
        sphinx_rtd_theme:   0.1.7-py27_0       --> 0.1.7-py34_0
        spyder:             2.3.8-py27_0       --> 2.3.8-py34_0
        spyder-app:         2.3.8-py27_0       --> 2.3.8-py34_0
        sqlalchemy:         1.0.9-py27_0       --> 1.0.9-py34_0
        ssl_match_hostname: 3.4.0.2-py27_0     --> 3.4.0.2-py34_0
        statsmodels:        0.6.1-np110py27_0  --> 0.6.1-np19py34_0
        sympy:              0.7.6.1-py27_0     --> 0.7.6.1-py34_0
        terminado:          0.5-py27_1         --> 0.5-py34_1
        toolz:              0.7.4-py27_0       --> 0.7.4-py34_0
        tornado:            4.3-py27_0         --> 4.3-py34_0
        traitlets:          4.0.0-py27_0       --> 4.0.0-py34_0
        ujson:              1.33-py27_0        --> 1.33-py34_0
        unicodecsv:         0.14.1-py27_0      --> 0.14.1-py34_0
        virtualenv:         13.0.1-py27_0      --> 13.0.1-py34_0
        werkzeug:           0.11.2-py27_0      --> 0.11.2-py34_0
        wheel:              0.29.0-py27_0      --> 0.29.0-py34_0
        xlrd:               0.9.4-py27_0       --> 0.9.4-py34_0
        xlsxwriter:         0.7.7-py27_0       --> 0.7.7-py34_0
        xlwings:            0.5.0-py27_0       --> 0.5.0-py34_0
        xlwt:               1.0.0-py27_0       --> 1.0.0-py34_0

    The following packages will be DOWNGRADED:

        astropy:            1.0.6-np110py27_0  --> 1.0.4-np19py34_0
        conda:              4.1.0rc1-py27_0    --> 4.0.5-py34_0
        conda-env:          2.5.0rc1-py27_0    --> 2.4.5-py34_0
        curl:               7.45.0-0           --> 7.43.0-1
        dynd-python:        0.7.0-py27_0       --> 0.6.5-np19py34_0
        futures:            3.0.5-py27_0       --> 3.0.3-py34_0
        h5py:               2.5.0-np110py27_4  --> 2.5.0-np19py34_3
        libdynd:            0.7.0-0            --> 0.6.5-0
        matplotlib:         1.5.0-np110py27_0  --> 1.4.3-np19py34_3
        numpy:              1.10.1-py27_0      --> 1.9.3-py34_1
        openssl:            1.0.2h-0           --> 1.0.1k-1
        pandas:             0.17.1-np110py27_0 --> 0.16.2-np19py34_0
        pycurl:             7.19.5.1-py27_3    --> 7.19.5.1-py34_2
        scikit-learn:       0.17-np110py27_1   --> 0.16.1-np19py34_0

    Proceed ([y]/n)? y

**Comment by mcg1969** [comment]
I'm not sure what the proper behavior should be here. There are packages in your environment they are not compatible with Python 3, right? So they need to be removed before you can upgrade the environment.

**Comment by kalefranz** [comment]
I was going to talk you through this in person to clarify, but let me attempt it here.

The curious part for me here isn't needing to remove packages.  Totally fine with that part.  Once I remove those packages though, I'd expect to remain at python 2.7.11.  Instead removing that set of packages makes me upgrade to python 3.4.0.

Ohhh, ok.  It's probably the enum34 package.  When I remove it, to maintain the rest of the packages I have in my environment, I have to upgrade python to at least 3.4.0 because enum34 is for python < 3.4.

But... just like the openssl downgrade being a problem here, if conda decides it's going to *change* a package for me, I want it to change it to the latest available (and still compatible with my environment).  At least I think I do.

In the specific context of what to do with python here, the "minimum change" strategy puts us at 3.4.0.  That's clearly wrong to me.  It should at least be 3.4.4 (3.4 latest).  However... that's complicated because each package potentially has it's own versioning strategy.  I would be fine here getting python 3.5.1.  (Actually, upgrading to 3.5.1 was going to be my next step after the conda remove anyway.)

So I think the minimum change pass is good, but we might need another pass...  If we *do* need to change the package, then upgrade to the latest that still gives us a consistent environment.

**Comment by mcg1969** [comment]
I think what may work here is to minimize the number of upgrades of *any* kind to existing packages. Once that's locked in, we can maximize those package versions.

**Comment by mcg1969** [comment]
Per our conversation, the real problem here is that `conda uninstall` is causing an upgrade to Python 3.4. That certainly should not be happening. But I'm having trouble reproducing the issue. Can you? If so, can you give me a full `conda --debug uninstall`... output?

**Comment by mcg1969** [comment]
Nevermind, I reproduced it:
```
conda create -n  testA anaconda python=2.7
conda uninstall -n testA enum34
```

**Comment by mcg1969** [comment]
https://github.com/conda/conda/pull/2480

**Comment by kalefranz** [comment]
Should be fixed in master now. I'll verify.

**Comment by mcg1969** [comment]
Yep:
```
0203-mgrant:conda mgrant$ conda remove -n testA enum34
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications .............

Package plan for package removal in environment /Users/mgrant/miniconda2/envs/testA:

The following packages will be REMOVED:

    anaconda:     4.0.0-np110py27_0 
    blaze:        0.9.1-py27_0      
    cryptography: 1.3-py27_0        
    enum34:       1.1.2-py27_0      
    llvmlite:     0.9.0-py27_0      
    numba:        0.24.0-np110py27_0
    pyopenssl:    0.15.1-py27_2     
```

**Comment by mcg1969** [comment]
Note that `anaconda` is *removed* because switching to the `custom` build is considered a downgrade, and we've prevented downgrades during a `remove`.
