### ISSUE TITLE
Repeated creation and removal of environments with -p fails because of files left in .trash

### ISSUE THREAD

**Issue by ctyler-wapiti** [conda/conda#2466]
Creating an environment with -p, removing it, creating it again and removing it again fails because of files left in the .trash folder.

Steps to reproduce:
1. c:\Work>conda create -p ./envs/delete_me pip
2. c:\Work>conda remove -p ./envs/delete_me
3. c:\Work>conda create -p ./envs/delete_me pip
4. c:\Work>conda remove -p ./envs/delete_me

Result: shutil.Error: Destination path 'C:\Miniconda\pkgs.trash\tmpvjeoz_..\Work\envs\delete_me\DLLs_ctypes.pyd' already exists

**Comment by kalefranz** [comment]
Are you still seeing this behavior with recent versions of conda?  Latest is 4.3.17.

**Comment by ctyler-wapiti** [comment]
On version 4.3.11 I no longer see the issue.
