### ISSUE TITLE
Not able to install scikit-learn

### ISSUE THREAD

**Issue by sagavia** [conda/conda#2468]
OS Windows 8.1 64 bit os, 64 bit processor 
Processor: AMD A8-4500M APU  1.90 GHZ
RAM:   16GB

c:>
c:>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.18.0
```

  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

c:>

C:\Windows\system32>conda install scikit-learn
Fetching package metadata: ....
Solving package specifications: ..........An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main     args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 337, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 421, in install_actions
    for name in install.win_ignore_root:
AttributeError: 'module' object has no attribute 'win_ignore_root'

C:\Windows\system32>

**Comment by ijstokes** [comment]
This is a surprising error.  Can you try doing `conda update conda` and then try again?  If that still fails, could you then try:

```
conda create -n testsklearn scikit-learn python=3.4
```

and let us know what result you get?  If **that** also fails, you could see if changing the Python version (say to 2.7 or 3.5) has any effect, but I doubt it -- I think the problem seems to be with conda.
