### ISSUE TITLE
Revisit conda config

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2474]
Figure out how to stack configs/condarc for global, user, and environment.  Integrate appropriately with anaconda.org and other parts of Anaconda.

**Comment by ijstokes** [comment]
@kalefranz I think this is tied to my two old issues:

* #654 Centralized control over `.condarc`
* #1329 Better support for conda envs accessed by multiple users

And possibly to this one related to conda/anaconda-client:

* https://github.com/Anaconda-Platform/anaconda-client/issues/236 Create conda-tools meta-package for unified "root-env" common commands

**Comment by kalefranz** [comment]
Thanks for linking the issues for me @ijstokes

**Comment by kalefranz** [comment]
Relates to https://github.com/Anaconda-Platform/anaconda-server/issues/2009

**Comment by jakirkham** [comment]
Also, this issue ( https://github.com/conda/conda/issues/2132 ).

cc @rcthomas

**Comment by kalefranz** [comment]
Being addressed in #2537.
