### ISSUE TITLE
Python `mkl` slower than `nomkl`

### ISSUE THREAD

**Issue by zimoun** [conda/conda#2476]
My machine is 32 cores.

I use the really simple benchmark:
```
python -m timeit -s 'import numpy as np; A = np.random.rand(5000, 5000); b = np.random.rand(5000);' 'A.dot(b)'
```
And the results are:

- numpy from Ubuntu
`100 loops, best of 3: 11.2 msec per loop`

- numpy with `mkl`: `conda create -n mkl python=2.7 numpy mkl`
`10 loops, best of 3: 24.1 msec per loop`

- numpy with `nomkl`: `conda create -n nomkl python=2.7 numpy nomkl`
`10 loops, best of 3: 11.8 msec per loop`

The issue seems coming from the multiprocessing/thread, the `mkl` option does not and `nomkl` does.
After I have read blog [there](https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations), then I have played around `mkl-service` without success (issue [#2](https://github.com/ContinuumIO/mkl-service/issues/2))

It is the same, Python 3.5 or 2.7

Note:
it is not the case on my desktop machine (8 cores), `mkl` vs `nomkl`:
100 loops, best of 3: 10.6 msec per loop
100 loops, best of 3: 11.8 msec per loop

**Comment by msarahan** [comment]
Do you have an Intel processor, or AMD?

**Comment by zimoun** [comment]
Damn it ! 
Newbie mistake, sorry. I forgot the basics...
it's AMD, and everything make sense.

Thank you
(and sorry)
