### ISSUE TITLE
Conda install with python3.4 never finishes

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2477]
Well, I don't know about never, actually.  Python 2.7 build/test runs take about 10 minutes for conda-build.  The python 3.5 runs are about the same.  Python 3.4 runs are hanging for me - so far the longest I have waited on appveyor is 35 minutes:

https://ci.appveyor.com/project/msarahan/conda-build/build/1.0.118/job/4bhwugf4xb5eg9et

It appears to hang at:

```
conda install -q pytest requests pycrypto git anaconda-client
Fetching package metadata: .... 
Solving package specifications: ......... 
```

ping @mcg1969 @kalefranz

**Comment by mcg1969** [comment]
Any way you can get me a debug run up to the point that seems to take forever? It is probably hanging in the SAT solve...

**Comment by msarahan** [comment]
Of course - just ```conda --debug install ...``` - or something else?

**Comment by mcg1969** [comment]
That's it, yes

**Comment by msarahan** [comment]
Changes made at: https://github.com/conda/conda-build/pull/948

I'll ping you when I see that we have some results on appveyor.

**Comment by mcg1969** [comment]
Great, thanks. I'm not able to reproduce this in my personal test notebook. I artificially force `subdir='win=64'` and create an installed list with these packages:
```
[u'conda-4.0.6-py34_0.tar.bz2',
 u'conda-env-2.4.5-py34_0.tar.bz2',
 u'menuinst-1.3.2-py34_0.tar.bz2',
 u'pip-8.1.1-py34_1.tar.bz2',
 u'pycosat-0.6.1-py34_0.tar.bz2',
 u'python-3.4.4-4.tar.bz2',
 u'pyyaml-3.11-py34_3.tar.bz2',
 u'requests-2.9.1-py34_0.tar.bz2',
 u'setuptools-20.7.0-py34_0.tar.bz2',
 u'vs2010_runtime-10.00.40219.1-0.tar.bz2',
 u'wheel-0.29.0-py34_0.tar.bz2']
```
Then I do `r.install(['pytest','requests','pycrypto','git','anaconda-client','python 3.4*'], installed=installed)` and I get this result:
```
[u'anaconda-client-1.4.0-py34_0.tar.bz2',
 u'clyent-1.2.2-py34_0.tar.bz2',
 u'colorama-0.3.7-py34_0.tar.bz2',
 u'conda-4.0.6-py34_0.tar.bz2',
 u'conda-env-2.4.5-py34_0.tar.bz2',
 u'git-2.6.4-0.tar.bz2',
 u'menuinst-1.3.2-py34_0.tar.bz2',
 u'pip-8.1.1-py34_1.tar.bz2',
 u'py-1.4.31-py34_0.tar.bz2',
 u'pycosat-0.6.1-py34_0.tar.bz2',
 u'pycrypto-2.6.1-py34_3.tar.bz2',
 u'pytest-2.9.1-py34_0.tar.bz2',
 u'python-3.4.4-4.tar.bz2',
 u'python-dateutil-2.5.3-py34_0.tar.bz2',
 u'pytz-2016.4-py34_0.tar.bz2',
 u'pyyaml-3.11-py34_3.tar.bz2',
 u'requests-2.9.1-py34_0.tar.bz2',
 u'setuptools-20.7.0-py34_0.tar.bz2',
 u'six-1.10.0-py34_0.tar.bz2',
 u'vs2010_runtime-10.00.40219.1-0.tar.bz2',
 u'wheel-0.29.0-py34_0.tar.bz2']
```
The solver takes very little time to complete.

**Comment by msarahan** [comment]
Hung in https://ci.appveyor.com/project/msarahan/conda-build/build/1.0.134/job/4b0bku4gd9e91wx0

**Comment by mcg1969** [comment]
It seems to have gotten past the solver pretty quickly. Seems to be hanging during the linking stage

**Comment by mcg1969** [comment]
```
[00:01:19] DEBUG:conda.instructions: PRINT('Linking packages ...')
[00:01:19] INFO:print:Linking packages ...
[00:01:19] DEBUG:conda.instructions: PROGRESS('10')
[00:01:19] INFO:progress.start:10
[00:01:19] DEBUG:conda.instructions: LINK('git-2.6.4-0 C:\\Miniconda3-x64\\pkgs 1')
[00:01:19] INFO:progress.update:('git-2.6.4', 0)
[00:01:19] DEBUG:conda.install:pkgs_dir='C:\\Miniconda3-x64\\pkgs', prefix='C:\\Miniconda3-x64', dist='git-2.6.4-0', linktype=1
```
It's been at this point for 40 minutes.

**Comment by tyler-thetyrant** [comment]
No longer supported!
