### ISSUE TITLE
uninstall should remove unneeded packages

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2478]
Simple case I just encountered.  Pretty sure `pastedeploy` (whatever that is) should have been removed here.

```
kfranz@0283:~/continuum/conda *master ❯ conda install gunicorn
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications ............

Package plan for installation in environment /conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pastedeploy-1.5.2          |           py27_1          23 KB
    gunicorn-19.1.0            |           py27_0         137 KB
    ------------------------------------------------------------
                                           Total:         160 KB

The following NEW packages will be INSTALLED:

    gunicorn:    19.1.0-py27_0
    pastedeploy: 1.5.2-py27_1

Proceed ([y]/n)? y

kfranz@0283:~/continuum/conda *master ❯ conda uninstall gunicorn
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications ............

Package plan for package removal in environment /conda:

The following packages will be REMOVED:

    gunicorn: 19.1.0-py27_0

Proceed ([y]/n)? y
```

**Comment by mcg1969** [comment]
It is a desirable behavior but definitely not implemented currently. 4.2 seems reasonable.

**Comment by mcg1969** [comment]
Actually, I changed my mind, this shouldn't be done automatically. If I install `pandas`, knowing it will install `numpy`, then later decide I don't need the Pandas machinery, I should be able to remove `pandas` without `numpy` being removed as well. The logic doesn't change just because the packages are less prominent.

**Comment by kalefranz** [comment]
I agree.  I think though we need an extra flag `--prune` for `conda remove` that would implement this behavior.

**Comment by kalefranz** [comment]
Not happening in the 4.3 timeframe though.  We have other priorities for your conda time @mcg1969.

**Comment by kalefranz** [comment]
Conda 4.4 will probably have a `--prune` command line flag.
