### ISSUE TITLE
update license documentation with 4.1 release

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2481]
https://github.com/conda/conda/pull/2334
http://conda.pydata.org/docs/license.html

**Comment by kalefranz** [comment]
This should only be one coincident with the 4.1 release because that's when the licensing in the source code was actually changed.

**Comment by kalefranz** [comment]
Also update logo

**Comment by kalefranz** [comment]
CC @electronwill

**Comment by electronwill** [comment]
@kalefranz update logo?

**Comment by kalefranz** [comment]
Oh, that too! Yes!  We should add/update the logo on the conda docs website. I can get you some links.

**Comment by kalefranz** [comment]
https://s3.amazonaws.com/conda-dev/conda_logo.svg

**Comment by electronwill** [comment]
I see that license.txt does not mention verlib.py and the license on the docs site does. Which is correct?

**Comment by kalefranz** [comment]
I'm not sure what verlib.py is, so we're probably not even using it anymore.

On Thu, Jun 16, 2016 at 3:48 PM, Will Warner <notifications@github.com>
wrote:

> I see that license.txt does not mention verlib.py and the license on the
> docs site does. Which is correct?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda/conda/issues/2481#issuecomment-226609206>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABWks9LW0E78_ZLcI2XN_QZVPlZ4Lot7ks5qMbaNgaJpZM4IeMu4>
> .
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by electronwill** [comment]
Makes sense-- it was probably removed from license.txt and not yet from the site, so I'll do that.

**Comment by electronwill** [comment]
Yup, was removed 2015-09-22 https://github.com/conda/conda/commits/master/LICENSE.txt

**Comment by electronwill** [comment]
Fixed license in https://github.com/conda/conda-docs/pull/298

**Comment by electronwill** [comment]
Was there a png version of the logo? Imagemagick is having some trouble with the conversion.

**Comment by kalefranz** [comment]
![logo_conda_rgb](https://cloud.githubusercontent.com/assets/1418419/16138861/6f475404-3407-11e6-868a-3d78d46eca05.png)

**Comment by kalefranz** [comment]
Might have to crop that though.

**Comment by kalefranz** [comment]
Going to go ahead and close this so it's cleaned up and off my radar now.

**Comment by electronwill** [comment]
Great-- thank you!

**Comment by electronwill** [comment]
I was wrong: the Sphinx documentation does work on SVGs. So I went ahead and used that one. New logo is now visible at http://conda.pydata.org/docs/ . Thank you for your help with all this!
