### ISSUE TITLE
Miniconda Linux install fails if directory contains space

### ISSUE THREAD

**Issue by pbalm** [conda/conda#2487]
Installing miniconda on Linux in a directory that has a space in its name fails.

**Details**

I just downloaded the Miniconda install for Linux. The install script says at the start:

```
# NAME:  Miniconda3
# VER:   4.0.5
# PLAT:  linux-64
# DESCR: 4.0.0-3-g3118a73
# BYTES:  32912085
# LINES: 357
# MD5:   464c87475075f583339fd75e948454bc
```

I'm using Linux Mint 17.2, but I think this is a generic issue with the install script:
Linux zbox 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

When I run this script in a directory that has a space, it will fail. Example:

```
$ mkdir test\ it
$ cd test\ it
$ ../Miniconda3-latest-Linux-x86_64.sh -b -p newinstall
PREFIX=/home/pbalm/test it/newinstall
installing: _cache-0.0-py35_x0 ...
tar (child): /home/pbalm/test: Cannot read: Is a directory
tar (child): At beginning of tape, quitting now
tar (child): Error is not recoverable: exiting now

bzip2: Compressed file ends unexpectedly;
    perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
    Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Let me know if I should submit an (attempt at) a fix. Thanks.

**Comment by msarahan** [comment]
In the past, our policy has been that we don't support this.  However, if you're willing to try to fix it, that might change.

CC @ilanschnell @csoja

**Comment by kalefranz** [comment]
Constructor has recently been refactored by @mingwandroid to handle a lot of extra edge cases like these.

**Comment by mingwandroid** [comment]
I have a [PR](https://github.com/conda/constructor/pull/72) but it's not been merged yet.
