### ISSUE TITLE
scitools installations: scpecification conflict

### ISSUE THREAD

**Issue by zillurbmb51** [conda/conda#2489]
Hi,
I am having this problem for few days. I was trying to run "conda install -c asmeurer scitools" but it gave me specification conflict. Herewith some output of my commands. Any help please. Thanks in advance. 
Best Regards
Zillur
[conda-info.txt](https://github.com/conda/conda/files/265369/conda-info.txt)
[conda-install-scitools.err.txt](https://github.com/conda/conda/files/265367/conda-install-scitools.err.txt)
[conda-list.txt](https://github.com/conda/conda/files/265370/conda-list.txt)
[conda-update-all.txt](https://github.com/conda/conda/files/265368/conda-update-all.txt)

**Comment by mcg1969** [comment]
The so-called "hint" that conda is trying to give you is admittedly useless. We're working on that. 

Fortunately, the problem is a simple one: `asmeurer/scitools` is compiled only for Python 2.7. You have Python 3.5 installed. You should create a Python 2.7 environment with the other packages you need, and scitools should install there.

**Comment by zillurbmb51** [comment]
Thank you very much. But how can I create a older environment concurrently?
Best Regards
Zillur

**Comment by mcg1969** [comment]
I think you'll find [this section of the documentation](http://conda.pydata.org/docs/using/envs.html) useful. If you're determined to use Aaron's conda package you'll need an environment with Python 2.7 and NumPy 1.7. The easiest way to get it is with this command:
```
conda create -n scitools_env -c asmeurer scitools python=2.7
```
`conda` will automatically select the version of NumPy needed. Then you can do
```
source activate scitools_env
```
to switch over to that environment and use it.

Finding a more recent version of scitools, or one that is compiled against a newer version of NumPy, is beyond our scope here. You'll need to build it yourself or find someone else who can.
