### ISSUE TITLE
conda not working when I ssh to my ubuntu

### ISSUE THREAD

**Issue by suiyuan2009** [conda/conda#2496]
command `python` is not linked to conda's python

**Comment by ericdill** [comment]
What does `which conda` report?

**Comment by suiyuan2009** [comment]
@ericdill return nothing, just empty, weird

**Comment by ericdill** [comment]
Are you running bash? What does `cat ~/.bashrc` and `cat ~/.bash_profile` show

**Comment by ericdill** [comment]
Probably also worth noting is that since `which conda` doesn't show anything, it is unlikely that this is a `conda` problem

**Comment by suiyuan2009** [comment]
@ericdill `~/.bashrc` contains
```
121 # added by Anaconda2 2.5.0 installer                                             
122 export PATH="/home/suiyuan2009/anaconda2/bin:$PATH"                              
123 export PYTHONNOUSERSITE=True                                                     
124 export PATH="$PATH:$HOME/bin" 
```

**Comment by suiyuan2009** [comment]
seems ok after I `source ~/.bashrc`, so ssh will not source bashrc automatically?

**Comment by ericdill** [comment]
Try this: http://stackoverflow.com/a/820533/3781327

**Comment by suiyuan2009** [comment]
@ericdill it works, thx~
