### ISSUE TITLE
Check permissions first

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2504]
If you search for "permission" in the issue tracker you'll find lots of people who have suffered greatly from Conda starting to do something and then borking out because of a permission problem:

https://github.com/conda/conda/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+permission

There are too many to list here, and I don't think it would help for me to include the most recent time (just now) when this has happened to me -- because it is one of the variants many other people have already reported.

I would suggest that Conda should check permissions **first**, then warn or abort if there are issues.  A frequent outcome of this problem is an inoperative Anaconda instance, requiring full reinstallation  (there are a few manual recovery strategies, but they require some expert insight into how things work).

Additionally if a permissions problem (or `OSError`) does crop up it should be caught and a helpful error message passed to the user.  Instead right now we return a stack trace.  Yuck.

**Comment by mcg1969** [comment]
I 100% agree, and yet one of the issues here is the conditions under which a permissions problem occurs seems quite random and unpredictable. So while we should do a better job of trapping these errors and exiting gracefully, we're still going to be left with half-baked and non-functioning environments.

Do you have a reliable way to generate these errors? That would go a long way towards us figuring out why they occur.

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed in 4.3 is conda uninstalling itself.
