### ISSUE TITLE
Msys2 activate does not work on current master

### ISSUE THREAD

**Issue by MaxNoe** [conda/conda#2509]
I'm on windows 10 using msys2. I installed the current conda master using

```
pip install git+http://github.com/conda/conda
```

When I try to do 
```
source activate test
```

I get:
```
$ source activate test
Traceback (most recent call last):
  File "C:\Users\maxnoe\Anaconda3\Scripts\conda-script.py", line 9, in <module>
    load_entry_point('conda==4.0.6.dev387+78b2441', 'console_scripts', 'conda')()
  File "C:\Users\maxnoe\Anaconda3\lib\site-packages\conda\cli\main.py", line 48, in main
    activate.main()
  File "C:\Users\maxnoe\Anaconda3\lib\site-packages\conda\cli\activate.py", line 120, in main
    shelldict = shells[shell]
KeyError: 'sh.exe'
```

**Comment by mingwandroid** [comment]
This should have been fixed by 4.1rc3 which was released today. I tested it locally just now and had no problem.

Can you verify that `activate` is the correct one via:

`which source`

Also, verify that you ran `bash.exe` and not `sh.exe` to launch `MSYS2` (if you used any of the offical batch files or msys2.exe this should be the case). For example, look in Task Manager to ensure `bash.exe` is being run.

Many thanks.

**Comment by kalefranz** [comment]
Go ahead and give us `conda info` too here.  That'll be helpful

**Comment by MaxNoe** [comment]
I had been using `sh.exe` via ConEmu, with `bash.exe` it works now. thanks.

**Comment by mingwandroid** [comment]
Ah that explains it. We might put support for `sh.exe` in too then since you are likely not the only person who'll do this, @kalefranz, what do you reckon?

**Comment by kalefranz** [comment]
There's nothing special we're doing with bash in the activate script I don't think, so it should be trivial I'd guess.

**Comment by mingwandroid** [comment]
We'd need to duplicate this block: https://github.com/conda/conda/blob/ddef048f1f2d6fa2ed72366f3e54bebbd96bbcfb/conda/utils.py#L378-L384

.. or do it like the bash / zsh bit just below to avoid repetition.

**Comment by mingwandroid** [comment]
@MaxNoe, out of interest, is there some documentation online that you followed to setup `MSYS2` with `ConEmu that recommended to use `sh.exe` instead of `bash.exe`? I'd like to request them to change it to `bash.exe` if so.

**Comment by MaxNoe** [comment]
@mingwandroid 

I did not setup anything manually. I just hit `Add default tasks` in the ConEmu Settings/Tasks dialog.

**Comment by mingwandroid** [comment]
@MaxNoe, ok thanks for the info. I'm going to re-open this to remind me that we should handle `sh.exe`.
