### ISSUE TITLE
Add option to avoid creating 'Navigator' desktop icon

### ISSUE THREAD

**Issue by rldotai** [conda/conda#2521]
Whenever I create a new environment (and potentially during other operations as well) Conda creates a desktop icon named "Navigator".
Previous versions didn't do this, and that I cannot find a way to avoid creating these re-creating these icons at some point is very irritating.

I have reviewed the documentation and can find no way to disable this behavior.
A solution suggested in a previous issue (regarding an icon named "Launcher") doesn't really work here-- attempting to uninstall `anaconda-navigator` via

```
conda remove -n root anaconda-navigator
```

Leads to downgrading of dozens of packages, some to extremely old versions.
Could you guys show me how to avoid this behavior, or implement an option to disable it?

**Comment by kalefranz** [comment]
This is done. The option is

    conda config --set shortcuts false
