### ISSUE TITLE
conda.install imports other conda modules

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2525]
I just noted https://github.com/conda/conda/blob/master/conda/install.py#L47,
however, it has always been a policy that `conda.install` has to be standalone, see:
https://github.com/conda/conda/blob/master/conda/install.py#L22

The problem is that all our installers depend on this, that is, they use `conda.install` as a module for bootstrapping.  This means that currently (even though we can build installers) they are broken.

**Comment by ilanschnell** [comment]
CC @kalefranz @csoja

**Comment by mcg1969** [comment]
Hmm. This is a more vexing challenge.

**Comment by mcg1969** [comment]
@mingwandroid, I think some functions of yours are in here, too?

**Comment by mcg1969** [comment]
Here's what I'm seeing:
- `iteritems` and `iterkeys` from `conda.compat` are easily removed.
- `url_path` from `conda.utils` can be duplicated.
- `pkgs_dirs`: this is needed by the `package_cache` function. `install.main` can populate that value if it is needed. So we can try to import it from conda.config; if that fails we set it to the empty list and let `main` populate that list.
- `root_dir`: this is used by `move_path_to_trash`, which the standalone installer doesn't need.
That leaves `url_channel`. That one will be a little complicated but I believe we can replace it with a sensible default.

**Comment by kalefranz** [comment]
Wow @mcg1969 you beat me to digging into all of this.  It's like there are three of you.

**Comment by mcg1969** [comment]
@mingwandroid: according to `config.py`, "root_dir should only be used for testing", but it looks like it's used in `move_path_to_trash`.

**Comment by mingwandroid** [comment]
Checking now ..

**Comment by mcg1969** [comment]
@mingwandroid I don't think the standalone installer relies on any of that logic, so you shouldn't need to participate in the fix here. I just found that when investigating how to remove the `root_dir` import.

**Comment by mingwandroid** [comment]
I tracked down the `move_path_to_trash` usage of `config.root_dir` to a very old commit. It seems that the specific layout is maintained to make things easier to debug, and I don't personally have a problem with *not* doing that.

```
Revision: 56539db682df784a02c71c7768fa88104c90ae11
Author: Diogo de Campos <campos@esss.com.br>
Date: 15/09/2015 21:36:37
Message:
move_to_trash will always try to delete old trash

Files moved to trash will keep the same directory structure relative to
conda root dir. This makes it easier to debug and find out where files are
coming from.
----
Modified: conda/install.py
```

**Comment by kalefranz** [comment]
I strongly dislike this "root_dir should only be used for testing" thing, and intend to unwind it in the coming weeks, unless one of you guys beat me to it.

**Comment by kalefranz** [comment]
Side note, when I was at 23andMe, I used a `CONDA_ROOT` environment variable *on every machine I provisioned*.  Usually set to `/usr/conda`.  I had no idea this little gotcha was buried in the code.
