### ISSUE TITLE
Another clone bug

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2546]
kfranz@0283:~/continuum/conda *master ❯ conda create --clone root -n rootclone
    Source:      '/conda'
    Destination: '/conda/envs/rootclone'
    The following packages cannot be cloned out of the root environment:
     - conda-team::conda-4.1.0rc2-py27_0
     - conda-build-1.20.1-py27_0
    Error: no URL found for package: <unknown>::gcc-4.8.5-3

But /conda/conda-meta/gcc-4.8.5-3.json has, in part,

     "channel": "https://repo.continuum.io/pkgs/free/osx-64/",

so the information is there.  The logic here is located around line 273 of `conda/misc.py`.

**Comment by mcg1969** [comment]
#2547
