### ISSUE TITLE
Jupyter config doesn't play nicely with conda environments

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2548]
I have installed a few of the Jupyter extensions from here into a Conda environment where I could try them out:

https://github.com/jupyter/jupyter/issues/124

This is a normal sort of thing to do: there is a lot of power in extensions.

The problem is that these create "shared" configuration information that causes problems when I then run Jupyter from inside a Conda environment where those extensions are **not** installed.  Below is some terminal output to demonstrate the issue.

Because Anaconda is the recommended way to get Jupyter, because we want people to use Jupyter with Anaconda, because we think extensions are the bees knees, and because Conda environments are awesome -- we need to figure out how to make Jupyter extensions play nicely with Conda environments which right now (for popular extensions) they do not.

@bollwyvl and @damianavila, this is definitely one for you to consider, and perhaps is tied to my woes here: https://github.com/Anaconda-Platform/nb_conda/issues/23

```
[W 22:49:55.635 NotebookApp] 404 GET /nbextensions/nb_delta/tree.js?v=20160524224953 (::1) 6.70ms referer=http://localhost:8888/tree
[W 22:49:55.640 NotebookApp] 404 GET /nbextensions/jupyter_cms/dashboard/main.js?v=20160524224953 (::1) 1.55ms referer=http://localhost:8888/tree
[W 22:49:55.702 NotebookApp] 404 GET /clusters?_=1464144594557 (::1) 1.27ms referer=http://localhost:8888/tree
[I 22:49:58.697 NotebookApp] Creating new notebook in 
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
[W 22:50:00.189 NotebookApp] 404 GET /nbextensions/genepattern.js?v=20160524224953 (::1) 1.42ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=matlab
[W 22:50:00.205 NotebookApp] 404 GET /nbextensions/jupyter_cms/notebook/main.js?v=20160524224953 (::1) 1.32ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=matlab
[W 22:50:00.209 NotebookApp] 404 GET /nbextensions/nb_delta/main.js?v=20160524224953 (::1) 1.36ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=matlab
[W 22:50:00.212 NotebookApp] 404 GET /nbextensions/nbbrowserpdf/index.js?v=20160524224953 (::1) 1.31ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=matlab
Using Anaconda Cloud api site https://api.anaconda.org
```

**Comment by mcg1969** [comment]
Ian, can you clarify how you think conda is part of the cause here? I am genuinely not trying to sound like I'm defending conda.  It's just not clear to me what you think conda is doing wrong, or what it is not doing that i should. I guess I really don't understand what I'm supposed to see in the sample output you've given us.

**Comment by mcg1969** [comment]
For instance, if these extensions are creating data outside of the conda environment itself, I don't see use being able to do anything about that. We would have to find a way to move that data to somewhere within the environment directory.

**Comment by ijstokes** [comment]
@mcg1969 I totally understand what you're saying: "This isn't conda doing something strange".  Broadly speaking, I agree, however there is a pretty rich set of Jupyter extensions and I think we need to understand that Jupyter + Extensions + Anaconda + Conda environments is an operational reality where people may be tempted to dump Conda (and perhaps by association distrust Anaconda) if that combination doesn't play well, as opposed to saying "I guess I can't use this really valuable Jupyter extension, because the extension author hasn't implemented it in a Conda-compatible way".

I feel like it is incumbent upon us to pick up the work we started in December around extension configuration, consider the lay-of-the-land post Jupyter 4.2 (which re-worked extension configuration), and then see if there is anything we can do to make Jupyter extensions have a happier existence with Conda environments.  If that isn't achievable then we can at least consider how extensions could be created/adapted so as to play nicely with Conda environments (while also working in non-Conda environments), then clearly document "Best Practice for Jupyter Extension Configuration to work with Conda" and circulate it in the community.

**Comment by ijstokes** [comment]
@mcg1969 I also didn't provide enough clear information about the Jupyter terminal output and how that indicated the problem: The stack of 404s reported there are all due to extensions which have "per-user" configuration that is picked up by the Jupyter Notebook server, however within the Conda environment where that Jupyter Server is running none of those extensions are actually installed: `nb_delta`, `jupyter_cms`, `genepattern`, `nbbrowserpdf`.

**Comment by mcg1969** [comment]
The problem, it seems to me, is that something in the Jupyter system is pulling from some sort of globally defined configuration file. That doesn't seem friendly to _any_ environment isolation approach, and it raises an obvious question: do virtualenv environments already work well with these extensions? Or do they exhibit similar problems? If they don't, what does virtualenv provide that conda does that enables them to work?

I do think I understand you better now. But I guess I'm a curmudgeon when it comes to issues. This one seems open ended, with no suggestions at all for what needs to be changed in conda. All signs point to this being something for Jupyter extension developers to figure out. This just doesn't strike me as something that should be here, in _this_ issue tracker, yet. But more specifics may help.

**Comment by damianavila** [comment]
> The problem is that these create "shared" configuration information that causes problems when I then run Jupyter from inside a Conda environment where those extensions are not installed. Below is some terminal output to demonstrate the issue.

Where are those config files located? Our extension should install their config files into the prefix... so I guess you have there config files in ./jupyter or the system location... how they end up there?

> The stack of 404s reported there are all due to extensions which have "per-user" configuration that is picked up by the Jupyter Notebook server, however within the Conda environment where that Jupyter Server is running none of those extensions are actually installed: nb_delta, jupyter_cms, genepattern, nbbrowserpdf.

And this is expected and correct... I mean.... if there is a "per-user" configuration is because the user want to have the extension enable all over the place... in all their environment, so, he has to install the extensions in all the environments... but this should not the the default behaviour, it is something that the experience user wants to customize (for instance, per user config + .condarc to install the extension by defualt in every environment).

For novice users, we should, from the conda point of view, install and enable the extension in a prefix basis... we can not do things outside the prefix... so, my guess is that we need to document all theses possibilities and let the user choose the proper one...

**Comment by ijstokes** [comment]
@mcg1969 I think you are right: this issue belongs somewhere else.  I posted it here because  I felt like the opportunity to figure out how to fix the problem is more likely to come from the conda team who can think clearly about this scenario and what could be done and what should be done, rather than attempting to put it on the Jupyter team to resolve.

This is a very real issue that impacts Conda usage.  I do think it is OK for us to just say "Other people need to do it our way" (IOW, in a way compatible with conda environments).  But it would be helpful if, in high value situations like this (Jupyter extensions), we were prepared to articulate the details of what "our way" looks like, and perhaps (again, in situations like this) even go so far as to figure out and document what we believe is the "best practice" way to deal with software configuration in a manner that is compatible with Conda environments.

@damianavila do you have suggestions of where this issue could get moved to if the Conda team is unable to consider this issue further?

@bollwyvl what is your perspective on this, as you consider how to get Conda packages for Jupyter extensions that will work in the Anaconda 4.1 release?

**Comment by damianavila** [comment]
>@damianavila do you have suggestions of where this issue could get moved to if the Conda team is unable to consider this issue further?

Probably the https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config repo is a good place to discuss this...

**Comment by bollwyvl** [comment]
So here is where the config files are [actually loaded](
https://github.com/ipython/traitlets/blob/d3a47c217053bc280c196ef1d133e2afb26c82c6/traitlets/config/application.py#L569).

If I install a package (into $PREFIX), and then configure *anything* out in user-land, i see this:
```
[W 12:27:56.599 NotebookApp] Collisions detected in jupyter_notebook_config.py and jupyter_notebook_config.json config files. jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "nbserver_extensions": "{'nbpresent': True} ignored, using {'nbpresent': False}"
      }
    }
```

`~/.jupyter` always wins. I think what would be expected is to merge these sub-values, and actually thought I had tested this in the past. Looking some more into this.

**Comment by damianavila** [comment]
> I think what would be expected is to merge these sub-values, and actually thought I had tested this in the past. Looking some more into this.

Nop, there was never a merge procedure, well... as far as I remember... 
Also, a merge could be very complicated depending on the pattern to merge... so there is a hierarchy model which is more easy to implement...

**Comment by bollwyvl** [comment]
@damianavila raised that issue ^^^ 

Turns out the merging works, but backwards, on nbextensions, while on serverextensions it doesn't really merge at all, but it does so in the right order. Wheee!

**Comment by damianavila** [comment]
Interesting...

**Comment by kalefranz** [comment]
Why isn't Jupiter just using a `.d` directory to pick up these configs? Is there a good technical reason?

**Comment by damianavila** [comment]
> Why isn't Jupiter just using a .d directory to pick up these configs? Is there a good technical reason?

Lack of time/resources :wink:

**Comment by kalefranz** [comment]
Perfectly legit.  I just wanted to make sure there weren't technical objections/concerns to work through and discuss :)

**Comment by kalefranz** [comment]
And in that case, I really do think this topic is more squarely a jupyter ticket.  The post-link callback configuration mechanism isn't good for a lot of package managers (e.g. yum, apt-get).  It's not just conda in this case.

**Comment by damianavila** [comment]
> Perfectly legit. I just wanted to make sure there weren't technical objections/concerns to work through and discuss :)

Well, in fact, there is some other work that would be nice to make happen first or at the same time (split into a jupyter server).

Some references:
* https://github.com/jupyter/notebook/issues/1706
* https://groups.google.com/forum/#!msg/jupyter/L1VFwE9roQM/euV57tzPCAAJ

**Comment by damianavila** [comment]
> And in that case, I really do think this topic is more squarely a jupyter ticket.

I agree.

**Comment by ijstokes** [comment]
@kalefranz @damianavila see my May 25th comment: I'm just concerned we're going to loose Anaconda users or at least lose the battle of "Anaconda is the best way to run Jupyter" if we don't address this.  My Jupyter 5.x experience suggests that we should continue to think of Jupyter 4.x being the primary tool our customers will use through 2017 and 2018

**Comment by kalefranz** [comment]
Do we need to schedule a meeting to discuss?

**Comment by ijstokes** [comment]
I'd like to take 15-20 minutes to talk about it, if you and @damianavila have time.
