### ISSUE TITLE
conda skeleton picked oldest version instead of newest

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2549]
Oldest version was 2.0.8, newest was 2.8.0.  `conda skeleton` picked 2.0.8.  Weird!

```
$ conda skeleton pypi rpy2
Warning, the following versions were found for rpy2
2.0.8
2.1.0
2.1.1
2.1.2
2.1.3
2.1.4
2.1.5
2.1.6
2.1.7
2.1.8
2.1.9
2.2.0
2.2.1
2.2.2
2.2.3
2.2.4
2.2.5
2.2.6
2.2.7
2.3.0alpha1
2.3.0beta1
2.3.0
2.3.1
2.3.2
2.3.3
2.3.4
2.3.5
2.3.6
2.3.7
2.3.8
2.3.9
2.3.10
2.4.0
2.4.1
2.4.2
2.4.3
2.4.4
2.5.0
2.5.1
2.5.2
2.5.3
2.5.4
2.5.5
2.5.6
2.6.0
2.6.1.dev0
2.6.1
2.6.2
2.6.3
2.7.0
2.7.1
2.7.2
2.7.3
2.7.4
2.7.5
2.7.6
2.7.7
2.7.8
2.7.9
2.8.0
Using 2.0.8
```

This is with conda 4.1.0rc3

**Comment by msarahan** [comment]
I have seen things like this. I think it has to do with source releases vs wheel releases. Often times later versions are wheel only. 

This is really a conda build issue. Feel free to move it there or refile there.

**Comment by ijstokes** [comment]
This issue was moved to conda/conda-build#974
