### ISSUE TITLE
Error: Could not locate 'conda-depends'

### ISSUE THREAD

**Issue by mrclary** [conda/conda#2552]
According to this [article](https://www.continuum.io/blog/developer-blog/python-packages-and-environments-conda) I should be able to list package dependencies (of numpy, for example) via the command:
`# conda depends numpy`

but instead I get "Error: Could not locate 'conda-depends'"

Any thoughts?

**Comment by mcg1969** [comment]
well, `conda info numpy` gives you a lot of information for each package, _including_ the dependencies. Looks like a documentation issue.

**Comment by mrclary** [comment]
Well, that does list dependencies, but not quite as convenient as the result shown in the documentation. Info lists every version available, which is hard to sift through...
Oh, well
