### ISSUE TITLE
Activate Saved Environments on Windows

### ISSUE THREAD

**Issue by tokejepsen** [conda/conda#2560]
Activating enviroments on Windows execute the batch scripts in ```..\etc\conda\activate.d```, but the variables can't be used in the environment.

Example of terminal;

```
C:\Users\admin\Documents\pipeline>activate test
Deactivating environment "C:\Users\admin\Documents\pipeline\miniconda"...
Activating environment "C:\Users\admin\Documents\pipeline\miniconda\envs\test"..
.
C:\Users\admin\Documents\pipeline\miniconda\envs\test\etc\conda\activate.d\

[test] C:\Users\admin\Documents\pipeline>echo %SOMETHING%
%SOMETHING%

[test] C:\Users\admin\Documents\pipeline>
```

with this ```env_vars.bat``` in ```..\etc\conda\activate.d```;
```
set SOMETHING=%~dp0
echo %SOMETHING%
```

**Comment by msarahan** [comment]
Thanks for filing this.  We have had this discussion on the conda mailing list at https://groups.google.com/a/continuum.io/forum/#!topic/conda/CJEV6H7gjOU

This problem will be solved with the conda 4.1 release.  You can try a prerelease version with:

conda update -c conda-team conda

**Comment by tokejepsen** [comment]
Thanks @msarahan :smile: 

Can confirm that it is working with 4.1 prerelease. Should I close this issue then?

**Comment by kalefranz** [comment]
Yeah let's close it now. Thanks @tokejepsen.
