### ISSUE TITLE
503 errors when running conda update

### ISSUE THREAD

**Issue by desilinguist** [conda/conda#2561]
All my CI builds have been failing since last night at midnight giving the 503 error about backend server being at full capacity.

**Comment by desilinguist** [comment]
https://circleci.com/gh/EducationalTestingService/rsmtool/66

**Comment by freeman-lab** [comment]
Seeing the same thing on TravisCI, for example:

https://travis-ci.org/thunder-project/thunder-extraction/jobs/133365621

**Comment by freeman-lab** [comment]
Update: seems to be working again.

**Comment by desilinguist** [comment]
Nope, now I am getting a timeout error instead (https://circleci.com/gh/EducationalTestingService/rsmtool/67)

**Comment by desilinguist** [comment]
okay, my build seems to be passing again.

**Comment by kalefranz** [comment]
Aware of the issue. Trying to figure out the cause now.

**Comment by kalefranz** [comment]
We've added extra servers to repo.continuum.io.  Still investigating root cause.  Being tracked in other places though, so closing issue.
