### ISSUE TITLE
hardcoded 'python' and 'lua' behave like landmines for custom package/environment setups

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#2572]
Was setting up some metapackages to simplify our conda build configurations, and ran into this mysterious error:

```
2016-05-29 06:21:19:  0: STDOUT: Removing old build environment
2016-05-29 06:21:19:  0: STDOUT: BUILD START: sequoiacore-1.0-wilypy35_0
2016-05-29 06:21:19:  0: STDOUT: Fetching package metadata: ....
2016-05-29 06:21:19:  0: STDOUT: Solving package specifications: .
2016-05-29 06:21:19:  0: STDOUT: WARNING: Could not find any versions of conda-build in the channels
2016-05-29 06:21:19:  0: STDOUT: Error:  Package missing in current linux-64 channels: 
2016-05-29 06:21:19:  0: STDOUT:   - lua None*
2016-05-29 06:21:19:  0: INFO: Process exit code: 1
```

This appears to be caused by the line

https://github.com/conda/conda/blob/f705ab14600cfe02a0335814cffcd6dd96a717d6/conda/plan.py#L348

which has some hardcoded stuff for 'python' and 'lua'. I can obviously get around this in many ways, but this kind of thing provides annoying landmines for custom setups isolated from the mainline default packages.

**Comment by mwiebe** [comment]
An aside, note the "WARNING: Could not find any versions of conda-build in the channels." It's kind of odd that conda-build wants to put itself into the build environment?

**Comment by mcg1969** [comment]
Heh. Well, I'm afraid a _lot_ of work has gone into `add_defaults_to_specs`. It serves a pretty essential purpose. For instance, it ensures that a Python 2 environment is not accidentally upgraded to Python 3 simply by attempting to add or remove a package.

This looks like an outright bug however. Would you mind working on a way for us to reproduce the error? In particular, it shouldn't be trying too look for version "None" of lua. And it shouldn't be attempting to add "lua" to your specs at all if none of your packages depend on it.

**Comment by mcg1969** [comment]
Actually, I see why it's trying to find version `None` of `lua`. That's not right. I can't recall who worked on the `lua` support in `add_defaults_to_specs`, but we'll need to figure that out.

**Comment by mcg1969** [comment]
Looks like the latest Lua support was added in #1934 by a user-driven PR accepted by @ilanschnell. Ilan, it looks like in Mark's case here, the `lua` version of the loop is getting all the way to the end, where it is adding `lua None*` to the specs. That's certainly not right. 

A simple fix, I think, is to add a condition to [this line](https://github.com/conda/conda/blob/f705ab14600cfe02a0335814cffcd6dd96a717d6/conda/plan.py#L394) that so that it is run _only_ if `dev_ver is not None`. But I'm actually surprised that it got that far. You might have more insight than I on that.

**Comment by mcg1969** [comment]
And regarding the conda-build warning. It's not trying to insert conda-build into the build environment. That warning is apparently generated by conda-build itself when creating the build environment. I agree that both its wording and placement is confusing; @msarahan you might want to look at that, and possibly create a conda-build issue out of it. The offending function is `warn_on_old_conda_build`, called by `create_env` in `build.py`. [See here](https://github.com/conda/conda-build/blob/c8853905cc99206371ee81ed7e794db1ee5d5f73/conda_build/build.py#L337)

**Comment by kalefranz** [comment]
I think we resolved this issue.  And we may be scaling back the add_defaults_to_specs behavior even more in conda 4.4 given some new tools we now have available.
