### ISSUE TITLE
cant use conda-build - osx 10.11 , conda 4.0.7

### ISSUE THREAD

**Issue by epifanio** [conda/conda#2583]
On a mac osx 10.11:

I'm using python from homebrew, for some reason (needs to learn how to buuld conda recipes) I'm now trying to switch to conda.
I first encountered a weird problem, after a fresh conda installation I was receinving this log at evey conda related command:

```
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
```

I fixed this, removing the files:

```
sitecustomize.py
sitecustomize.pyc
sitecustomize.pyo
```
This: https://gist.github.com/10875d8114d6aeae1da401ac276d82ce the content of *sitecustomize.py*.

After removing the offending file and removing anaconda, a fresh install. then: ```conda install condo-build``` when attempting to build the gdal recipe from ```conda-recipes``` I got: 
```
Massimos-MacBook-Pro:~ epi$ cd dev/conda-recipes/
Massimos-MacBook-Pro:conda-recipes epi$ conda-build gdal
Traceback (most recent call last):
  File "/Users/epi/anaconda/bin/conda-build", line 3, in <module>
    from conda_build.main_build import main
  File "/Users/epi/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 23, in <module>
    from conda_build.build import bldpkg_path
  File "/Users/epi/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 33, in <module>
    from conda_build.render import parse_or_try_download, output_yaml, bldpkg_path
  File "/Users/epi/anaconda/lib/python3.5/site-packages/conda_build/render.py", line 18, in <module>
    import yaml
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named ‘error'
```

Have you any clue on what is wrong on my system? Why conda is looking into ```/usr/local``` ?
```
which python
/Users/epi/anaconda/bin/python
```

this the output of ```env```:

```
epi$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/y6/s6576tz52fzg64wh876f1yyh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9ou9USiWqk/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=AFA092C6-8EBC-446B-B62C-B9258FD449FF
USER=epi
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Ze6Hgoi6x6/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/epi/anaconda/bin:/Users/epi/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
PWD=/Users/epi/dev/conda-recipes
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/epi
LOGNAME=epi
DISPLAY=/private/tmp/com.apple.launchd.H9CtgFotve/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/epi
```

**Comment by msarahan** [comment]
Ordinarily, this happens when PYTHONPATH is set.  I don't see that in your environment variables, though.

Is pyyaml installed in your conda environment?  It is a requirement of conda-build, and would be strange if it were not getting picked up when you installed conda-build, but still...

How did you install conda-build?  What version is it?

**Comment by msarahan** [comment]
Issue moved to [conda/conda-build #1000](https://github.com/conda/conda-build/issues/1000) via [**ZenHub.io**](https://www.zenhub.io/)
