### ISSUE TITLE
Check all dependencies of conda with a test of a working conda

### ISSUE THREAD

**Issue by jankatins** [conda/conda#2585]
This is from https://github.com/conda-forge/staged-recipes/issues/666#issuecomment-221294317

Another suggestion: all packages which are in the dependency chain of conda should get a test which installs conda (not sure if that's possible in a test environment) and use it to install and remove/downgrade a package. That way the real disaster of installing a broken package into the root environment which disables conda itself could be prevented.

**Comment by mcg1969** [comment]
@kalefranz, while you're working on new tests... ^^^
