### ISSUE TITLE
Consider unsetting PYTHONPATH

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#2590]
As the documentation correctly points out,
http://conda.pydata.org/docs/troubleshooting.html
having a PYTHONPATH environment variable interact with conda is asking for trouble. To give an example of how crazy it gets, when calling conda-build on some python 3 package, the tests were failing with a traceback from `/random/path/to/python27/site-packages/<package>/xxx.py` because the corresponding location happened to be in PYTHONPATH.

Given that having that environment variable causes trouble much more often than does something useful (and goes against all about reproducible builts and environments), I wonder if it would be possible to unset it in the activate script. Maybe also affecting the root enviornment would be too invasive.

**Comment by msarahan** [comment]
I'd be uncomfortable unsetting it.  I'd be OK with warning people about it being set, though.

**Comment by ilanschnell** [comment]
The Miniconda and Anaconda installers warn about `PYTHONPATH` being set already.

**Comment by Zaharid** [comment]
Unfortunately the installer is a little far away from where the average user sees the warning, and thus is not always helpful to diagnose problems. Could there be a warning in the activate script?

**Comment by kalefranz** [comment]
As commented in #3162, any environment variable manipulation for python should really be done as part of the python package, and not hard-coded into conda itself with specific cutouts for python.

**Comment by kalefranz** [comment]
I'm going to close this issue, given the solution. Feel free to open a new issue at https://github.com/ContinuumIO/anaconda-issues for adjustment to the python package if you feel strongly about it.
