### ISSUE TITLE
document bash completion for "source activate"

### ISSUE THREAD

**Issue by electronwill** [conda/conda#2595]
@nevermindewe commented on [Wed Apr 22 2015](https://github.com/conda/conda-docs/issues/37)

TODO: 
- make a robust version of bash completion for source activate:

```
_complete_source_activate_conda(){
  if [ ${COMP_WORDS[COMP_CWORD-1]} != "activate" ]
  then
    return 0
  fi
  local current_string=${COMP_WORDS[COMP_CWORD]}
  local env_list=$(conda env list | sed '1d;2d;$d' | awk {'print $1'})
  COMPREPLY=($(compgen -W '${env_list[@]}' -- "$current_string"))
  return 0
}

complete -F _complete_source_activate_conda source
```
- add usage and installation to docs

**Comment by electronwill** [comment]
It looks like this will require code changes before docs changes, so I've moved it to the conda issues. Looks like it relates to https://github.com/conda/conda/issues/822 https://github.com/conda/conda/pull/341 and https://github.com/conda/conda/pull/2080 .

**Comment by kalefranz** [comment]
We've removed tab completion in 4.4 after pretty broad internal discussion. Biggest reason was performance. Secondary was maintenance and lack of testing. Could bring it back again someday, especially after #5044 settles in, and if we bring in a better cli framework.
