### ISSUE TITLE
Conda breakes Matplotlib when used with Tkinter

### ISSUE THREAD

**Issue by akshaybabloo** [conda/conda#2600]
I am using Anaconda for Python 3.5.

```
platform : win-64
conda version : 4.0.7
conda-build version : 1.20.3
python version : 3.5.1.final.0
requests version : 2.10.0
```

When I use Matplotlib with Tkinter, I get nothing, but the program exits with an `exit code -1073741819 (0xC0000005)`. The workaround I found is to do the following

```
conda uninstall matplotlib
pip install matplotlib
```

Will this be rectified in the future release?

**Comment by mcg1969** [comment]
I've moved this over https://github.com/ContinuumIO/anaconda-issues/issues/814.
