### ISSUE TITLE
`ANACONDA_TOKEN` exposed in travis ci build

### ISSUE THREAD

**Issue by rlee287** [conda/conda#2601]
In `.travis.yml`, special care is taken to avoid exposing the value of `ANACONDA_TOKEN`. However, the `printenv` command exposes this value in plaintext (see line 199 of [this travis log](https://travis-ci.org/conda/conda/jobs/135147989).) As a suggestion, `printenv` could be replaced with something like this (note: have not verified sed expression yet):

``` bash
printenv | sed -e 's/ANACONDA_TOKEN=*/ANACONDA_TOKEN=[secured]' > env.txt; cat env.txt; rm env.txt
```

Moreover, the exposed token needs to be revoked and replaced with a new one.

**Comment by kalefranz** [comment]
I don't know of any instance of 'printenv' existing in the conda code base.
