### ISSUE TITLE
Odd behavior when specifying a version

### ISSUE THREAD

**Issue by birdsarah** [conda/conda#2602]
- conda 4.0.7
- OSX

`conda install nodejs`   - get the familiar `Fetching package metadata: ....
Solving package specifications: .........` etc. great :D

`conda install -c javascript nodejs` get the familiar `Fetching package metadata: ....
Solving package specifications: .........`

All good so far. But specifying a version is not good.

`conda install nodejs>=4.1` returns no feedback just spits me onto a new line

`conda install -c javascript nodejs>=4.1` returns no feedback but stalls and I'm just left waiting for my prompt to return

**Comment by birdsarah** [comment]
Have just checked it's specifically `>=` `==` doesn't have the same problem.

Also doesn't matter whether it's a clean env or not.

**Comment by mcg1969** [comment]
In each case, can you do `conda --debug install`... and either 1) paste the output here or 2) email it?

**Comment by mcg1969** [comment]
Nevermind, @birdsarah, I'm able to reproduce the hanging here. Thank you for the report!

**Comment by mcg1969** [comment]
Hey, wait. Can you look in the directory where you ran this, and confirm the existence of a file called '=4.1'?

Looks like this is an interaction with the shell; it is interpreting '>' as a redirection. Try this:
```
conda install "nodejs>=4.1"
```
What's happening is that it's redirecting conda's output to `=4.1`, and then it's waiting for you to respond for input---but because the output is gone, you don't know it's waiting for that :-)

**Comment by birdsarah** [comment]
yes - I was getting a '=4.1' and '=4.3'!!!

**Comment by mcg1969** [comment]
OK. So this is not a conda bug, then; it is a consequence of the way Unix/Mac shells work. You'll have to add quotes around any spec with a '>' in for it to work. In fact, conda isn't even *seeing* the `>=4.1`, so it's simply not possible for us to fix it on our end.

**Comment by birdsarah** [comment]
Fair enough! Thanks for helping me figure this out.

**Comment by mcg1969** [comment]
Absolutely! Thanks for reporting it. In fact this is probably something we need to put in the documentation. I'm going re-open the issue and mark it as such.
