### ISSUE TITLE
Can't source fish setup file

### ISSUE THREAD

**Issue by RSully** [conda/conda#2611]
I installed a clean miniconda3 distribution and updated to 4.0.8. I found [this](https://github.com/conda/conda/blob/4.0.8/bin/conda.fish#L14) instruction to integrate with fish (as out of the box, it seems `source activate` does not work) but the .fish file does not exist. Are there other instructions I couldn't find to finish my installation?

**Comment by msarahan** [comment]
The fish integration is only present in the pending 4.1 release.  You can
download the relevant files and put them in place manually.  Those files
are in https://github.com/conda/conda/tree/master/bin

**Comment by RSully** [comment]
As I mentioned in #2680, I'm still not seeing the .fish file there in 4.1.0.

**Comment by jaimergp** [comment]
For the moment, grab the file from the repo and copy it anywhere. Then, make sure to source it in your user config.fish file.

For example, I have mine in $ANACONDA_INSTALL/bin, and my `config.fish` (in `~/.config/fish`) looks like this:

```
set -gx PATH ~/.local/anaconda/bin $PATH
source (conda info --root)/bin/conda.fish
```

**Comment by RSully** [comment]
Still a problem on 4.1.1 even after #2694

**Comment by RSully** [comment]
Still a problem on 4.1.2

**Comment by RSully** [comment]
I was expecting 4.1 to be 'year of the fish', but 4 minor versions in and no dice. After @kalefranz's #2694 I thought the next release might include it. Is there anything I can do to make progress on this?

**Comment by kalefranz** [comment]
A PR that fixes it? :-p

Or more details. I actually thought we had gotten close to fixing this here: https://github.com/conda/conda/pull/2694

**Comment by RSully** [comment]
Honestly I don't even know where I'd begin. Looking at my 4.1.4 miniconda, it looks like maybe conda.recipe/build.sh is not even being executed? $PREFIX/exec does not exist either.

**Comment by kalefranz** [comment]
You're right, it's not there.  Communication problem between me and @ilanschnell.

@ilanschnell, I know we had an issue with the conda.recipe in this repo at one point, but can you add

    # link to exec folder as a more contained proxy.  Idea is that people can add exec folder to PATH
    #    instead of bin, and have only activate & conda on PATH - no trampling other stuff.
    mkdir -p $PREFIX/exec
    ln -s $PREFIX/bin/activate $PREFIX/exec/activate
    ln -s $PREFIX/bin/conda $PREFIX/exec/conda

    mkdir -p $PREFIX/etc/fish/conf.d/
    cp $SRC_DIR/shell/conda.fish $PREFIX/etc/fish/conf.d/

to `build.sh` for your conda recipe?

The `bld.bat` probably needs some work too, but I'm not sure how much of what's in https://github.com/conda/conda/tree/master/conda.recipe we should pull.

**Comment by kalefranz** [comment]
@RSully `4.1.5` was released today.  And I've just verified that `$CONDA_ROOT/etc/fish/conf.d/conda.fish` exists for you.

**Comment by RSully** [comment]
Thanks! Should add that to the changelog :).

**Comment by RSully** [comment]
@kalefranz This was fixed, and conda.fish is available in `(conda info --root)/etc/fish/conf.d/` however [conda.fish](https://github.com/conda/conda/blob/d44a98c80f5ef9e6dbb88c9649843fe6e4ff0182/shell/conda.fish#L14) shows the wrong path as part of its install guide. Also, there is a UX problem since `conda create` says to use `source activate` when really the fish file defines `activate` and `conda activate`, no `source`.

**Comment by soxofaan** [comment]
I had a bit of the same struggle, but eventually found `conda.fish` as noted above (using conda 4.2.13 at the moment)
This line in my `~/.config/fish/config.fish` works for me:
```
source (conda info --root)/etc/fish/conf.d/conda.fish
```

**Comment by alexbw** [comment]
Getting the following error:

```
 ~/a/bin> source activate python27
'case' builtin not inside of switch block
activate (line 22): case "$(uname -s)" in
                    ^
from sourcing file activate
	called on standard input

source: Error while reading file 'activate'
```

**Comment by abhigenie92** [comment]
```
source activate ppo
source: Error encountered while sourcing file 'activate':
source: No such file or directory
```


```
 ~  cat ./.config/fish/config.fish
set -gx PATH /anaconda/bin $PATH
set -x PYTHONPATH /Users/abhishek/Packages/rllab $PYTHONPATH
set -x MUJOCO_PY_MJKEY_PATH /Users/abhishek/.mujoco/mjkey.txt
set -x MUJOCO_PY_MJPRO_PATH /Users/abhishek/.mujoco/mjpro131
set -x HOMEBREW_NO_AUTO_UPDATE 1
set -x PATH $HOME/.cargo/bin $PATH
test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish


# useful functions
function take
    command mkdir $argv;and cd $argv
end
#


eval (python -m virtualfish)

if set -q VIRTUAL_ENV
    echo -n -s (set_color -b blue white) "(" (basename "$VIRTUAL_ENV") ")" (set_color normal) " "
end


# Show the conda environment, calculate __fish_prompt_conda only once
if set -q CONDA_DEFAULT_ENV
    if not set -q __fish_prompt_conda
        set -g __fish_prompt_conda (set_color --bold -b blue red)$CONDA_DEFAULT_ENV"$__fish_prompt_normal "
    end
    echo -n $__fish_prompt_conda
end

# to make conda activate/create work for virtual envs
source (conda info --root)/etc/fish/conf.d/conda.fish


alias envact='source /anaconda/bin/activate'
```

**Comment by RSully** [comment]
There's no `source` support in fish at all for conda. You want `conda activate $env`. Just tested on conda 4.3.24 and fish 2.6.0.

**Comment by marcstreeter** [comment]
History of events.
- installed conda
- months passed
- installed fish 2.6.0
- updated conda to 4.3.27

then I added line in `~/.config/fish/config.fish`

     source (conda info --root)/etc/fish/conf.d/conda.fish

and opened a new terminal session

Now instead of doing  `source activate $env` I do `conda activate $env`.

**Comment by Davidnet** [comment]
Any followup to this?

**Comment by jaimergp** [comment]
@Davidnet What problems are you facing? What @marcstreeter said is a perfect step-by-step guide on how to make it work.

Btw, all fish users here, since `conda` is in `$PATH`, so is Anaconda `python`. That allows us to change to a faster source mechanism that avoids those ~500ms when launching a new terminal:

Replace `(conda info --root)` by `(python -c "import sys; print(sys.prefix)")`. I'll make a PR to update the built-in docs.

**Comment by RSully** [comment]
@jaimergp that may be problematic for those with other python installs that are higher in PATH (common name conflict, as opposed to conda being unique). I personally have another python install as my "default" and only activate conda as needed (sometimes even just as `conda activate root`)

**Comment by jaimergp** [comment]
> @jaimergp that may be problematic for those with other python installs that are higher in PATH (common name conflict, as opposed to conda being unique). I personally have another python install as my "default" and only activate conda as needed (sometimes even just as conda activate root)

Fair enough, I hadn't considered that use case. Is there any possibility to have `conda` installer hardcode the path directly?

**Comment by endolith** [comment]
> then I added line in ~/.config/fish/config.fish
> 
>  source (conda info --root)/etc/fish/conf.d/conda.fish

But

**Comment by tkkcc** [comment]
I prefer just put `conda.fish` in `functions` without changing `PATH` or `config.fish`
```sh
ln -s /opt/anaconda/etc/fish/conf.d/conda.fish $HOME/.config/fish/functions/
```
when run `conda ...`, `PATH` will be modified automatically

**Comment by henryiii** [comment]
> Like, you have to add this command to make `conda` available... but this command depends on `conda`, which isn't available until after you run this command? 😕

You can temporarily add the anaconda bin directory to your path to do this. But if you know the bin directory, you also know the root directory of anaconda and can just use that directly. But @tkkcc's solution is much better, IMO.
