### ISSUE TITLE
Newest HDF5 package doesn't link on Windows

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#2614]
After updating HDF5 to version 1.8.16 (specifically, https://repo.continuum.io/pkgs/free/win-64/hdf5-1.8.16-vc14_0.tar.bz2), I get link errors like
```
unresolved external symbol H5T_NATIVE_INT_g 
unresolved external symbol H5T_NATIVE_DOUBLE_g 
unresolved external symbol H5P_CLS_DATASET_CREATE_ID_g
```
The problem is a missing line in a configuration header: Since HDF5 was compiled into a DLL, the file `include/H5pubconf.h` should contain
```
#define H5_BUILT_AS_DYNAMIC_LIB 1
```
This line used to be present in version 1.8.15.1 (specificaly, https://repo.continuum.io/pkgs/free/win-64/hdf5-1.8.15.1-vc14_4.tar.bz2), but is missing in the new package version. The HDF5 documentation claims that the line in question is automatically inserted by cmake, so this looks like an error in Continuum's build scripts. Please correct!

**Comment by mcg1969** [comment]
Seems to me this should have gone to [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/issues)?

**Comment by mcg1969** [comment]
Migrated it for you.
