### ISSUE TITLE
condo does not install R 3.3.0

### ISSUE THREAD

**Issue by randy3k** [conda/conda#2621]
While https://anaconda.org/r/r says that R 3.3.0 is available, I could't find it via conda.

```sh
root@jupyter:~# conda install -c r r=3.3.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - r 3.3|3.3.0*

You can search for this package on anaconda.org with

    anaconda search -t conda r 3.3|3.3.0*
```

**Comment by mcg1969** [comment]
R 3.3.0 is available only on Windows: https://anaconda.org/r/r/files?version=3.3.0
@mingwandroid, any ideas about when it can be made available for other platforms?

**Comment by mingwandroid** [comment]
@mcg1969 I have two things to look at until I can get onto R, a scipy on Windows issue and Qt5 on Centos5, I hope to get those out of the way by Monday then focus on R. I don't expect the task will take too long, maybe 3 days for Linux and 5 for OS X.

**Comment by mcg1969** [comment]
That's great. If anything, this suggests primarily a need to improve the web site so that the version numbers are broken down by OS.

**Comment by DoaneAS** [comment]
Would be great to get this up and running.  The current Bioconductor requires the current R version 3.3

**Comment by mingwandroid** [comment]
I'll commence working on it today I hope.

**Comment by naymikm** [comment]
Thanks!

**Comment by psinger** [comment]
Any news on that?

**Comment by mingwandroid** [comment]
I have test packages for R 3.3.1 up on https://anaconda.org/rdonnellyr for all platforms. The linux versions have a known problem with ncurses that I'm looking at fixing today, but you are welcome to test and provide feedback.

**Comment by naymikm** [comment]
Hmm I installed your R 3.3.1 in a new environment and 'conda list' shows it as 3.3.1 but when I run R its says 3.1.1

**Comment by mingwandroid** [comment]
What operating system are you using? Did you install via:

`conda install r-essentials -c rdonnellyr`

**Comment by naymikm** [comment]
Thanks that worked!

**Comment by drramki-chop** [comment]
Is there a way to specify rdonnellyr/r-essentials in a recipe's meta.yaml file?

**Comment by stevekm** [comment]
Sorry, but was there a solution to this? I am trying to install R 3.3.0 through conda: 

```bash
$ conda env create -f r.3.3.0.yml
Fetching package metadata ...............

NoPackagesFoundError: Package missing in current linux-64 channels:
  - r 3.3.0*
```
Using this YAML:
```bash
$ cat r.3.3.0.yml
name: r.3.3.0
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - r=3.3.0
  - r-essentials
```

Is there a reason why this doesn't work? If I install `r=3.3`, I actually get R version 3.3.2, and not 3.3.0.
