### ISSUE TITLE
tarball install windows

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2642]
@msarahan @mingwandroid What *should* the `file://` url format be on Windows?

    ________________________ IntegrationTests.test_python3 ________________________ 
    Traceback (most recent call last):
      File "C:\projects\conda\tests\test_create.py", line 146, in test_python3
        run_command(Commands.INSTALL, prefix, flask_tar_file)
      File "C:\projects\conda\tests\test_create.py", line 104, in run_command
        args.func(args, p)
      File "C:\projects\conda\conda\cli\main_install.py", line 62, in execute
        install(args, parser, 'install')
      File "C:\projects\conda\conda\cli\install.py", line 195, in install
        explicit(args.packages, prefix, verbose=not args.quiet)
      File "C:\projects\conda\conda\misc.py", line 111, in explicit
        index.update(fetch_index(channels, **fetch_args))
      File "C:\projects\conda\conda\fetch.py", line 266, in fetch_index
        for url in iterkeys(channel_urls)]
      File "C:\projects\conda\conda\fetch.py", line 67, in func
        res = f(*args, **kwargs)
      File "C:\projects\conda\conda\fetch.py", line 149, in fetch_repodata
        raise RuntimeError(msg)
    RuntimeError: Could not find URL: file:///C|/projects/conda/
    ---------------------------- Captured stdout call ----------------------------- 
     
The relevant lines to look at here are line 64 in `conda/misc.py`

    url_p = utils_url_path(url_p).rstrip('/')

and line 147 in `conda/utils.py`

    def url_path(path):
        path = abspath(path)
        if sys.platform == 'win32':
            path = '/' + path.replace(':', '|').replace('\\', '/')
        return 'file://%s' % path

Help here is definitely appreciated.

**Comment by groutr** [comment]
Maybe this might be useful. 
https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

Python's (3.4+) pathlib module might give a hint
```
In [1]: import pathlib

In [2]: pathlib.Path(r"C:\projects\conda").as_uri()
Out[2]: 'file:///C:/projects/conda'
```

I'm unable to reproduce this, however maybe the code that interprets the file uri might also be relevant.  This would include conda's `LocalFSAdapter()` in connection.py (https://github.com/conda/conda/blob/231e9db898b3d7720b49e9e2050a88be6978fd38/conda/connection.py#L205-L235) which makes a call to `url_to_path()` (https://github.com/conda/conda/blob/231e9db898b3d7720b49e9e2050a88be6978fd38/conda/connection.py#L238-L251).  These functions seem to interpret that format correctly.

One final observation: line 64 in `misc.py` strips the rightmost `/`, yet the uri in the error message seems to still have one.  Is that supposed to be happening?

**Comment by mingwandroid** [comment]
Hi @groutr. thanks for looking at this and good to see you again! @kalefranz yeah, you need to keep the :

**Comment by groutr** [comment]
@mingwandroid no problem.  I hope to keep active here as time permits.
