### ISSUE TITLE
trouble with 'conda install -c r r-essentials'

### ISSUE THREAD

**Issue by Luxios** [conda/conda#2643]
An unexpected error has occurred, please consider sending the:02:52   2.37 kB/s
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 226, in _error_catcher
    yield
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 301, in read
    data = self._fp.read(amt)
  File "D:\Program Files\Python\Anaconda3\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "D:\Program Files\Python\Anaconda3\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "D:\Program Files\Python\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "D:\Program Files\Python\Anaconda3\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by mingwandroid** [comment]
Please show the output of `conda info`

Also, would it be possible to check two if this was a transitory network issue, test this by trying again and seeing if you get the same result.

Also, this error could be related to https://support.microsoft.com/en-us/kb/981344

.. can you try disabling your firewall and trying again?

**Comment by Luxios** [comment]
This time I have closed the Firewall.

D:\Program Files\Python\Anaconda3>conda install -c r r-essentials
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment D:\Program Files\Python\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    m2w64-gcc-libgfortran-5.3.0|                5         350 KB  r
    m2w64-gcc-libs-5.3.0       |                6         706 KB  r
    m2w64-gettext-0.19.7       |                1         4.3 MB  r
    m2w64-libjpeg-turbo-1.4.2  |                2         693 KB  r
    m2w64-libmetalink-0.1.3    |                1          76 KB  r
    m2w64-libpng-1.6.21        |                1         384 KB  r
    m2w64-libtasn1-4.7         |                1         219 KB  r
    m2w64-libvorbis-1.3.5      |                1         492 KB  r
    m2w64-nettle-3.1.1         |                3         671 KB  r
    m2w64-openssl-1.0.2.g      |                1         4.9 MB  r
    m2w64-pcre-8.38            |                1         1.3 MB  r
    m2w64-speexdsp-1.2rc3      |                2         513 KB  r
    m2w64-tcl-8.6.5            |                1         3.5 MB  r
    m2w64-libidn-1.32          |                3         310 KB  r
    m2w64-libssh2-1.7.0        |                1         275 KB  r
    m2w64-libtre-git-122.c2f5d13|                4          89 KB  r
    m2w64-nghttp2-1.9.2        |                1         203 KB  r
    m2w64-p11-kit-0.23.2       |                1         297 KB  r
    m2w64-speex-1.2rc2         |                2         592 KB  r
    m2w64-tk-8.6.5             |                1         2.1 MB  r
    m2w64-xz-5.2.2             |                1         397 KB  r
    m2w64-libsndfile-1.0.26    |                1         555 KB  r
    m2w64-libsystre-1.0.1      |                2          12 KB  r
    m2w64-libtiff-4.0.6        |                1         1.2 MB  r
    m2w64-libxml2-2.9.3        |                2         2.1 MB  r
    m2w64-tktable-2.10         |                4         111 KB  r
    m2w64-gnutls-3.4.11        |                1         2.4 MB  r
    r-base-3.3.0               |                0        37.2 MB  r
    m2w64-rtmpdump-git-499.a107cef|                3         204 KB  r
    r-assertthat-0.1           |         r3.3.0_2          49 KB  r
    r-base64enc-0.1_3          |         r3.3.0_0          31 KB  r
    r-bh-1.60.0_2              |         r3.3.0_0         8.4 MB  r
    r-bitops-1.0_6             |         r3.3.0_2          30 KB  r
    r-boot-1.3_18              |         r3.3.0_0         641 KB  r
    r-chron-2.3_47             |         r3.3.0_0         111 KB  r
    r-cluster-2.0.4            |         r3.3.0_0         530 KB  r
    r-codetools-0.2_14         |         r3.3.0_0          49 KB  r
    r-colorspace-1.2_6         |         r3.3.0_0         391 KB  r
    r-dbi-0.4_1                |         r3.3.0_0         227 KB  r
    r-dichromat-2.0_0          |         r3.3.0_2         151 KB  r
    r-digest-0.6.9             |         r3.3.0_0         119 KB  r
    r-foreign-0.8_66           |         r3.3.0_0         232 KB  r
    r-formatr-1.4              |         r3.3.0_0          49 KB  r
    r-gtable-0.2.0             |         r3.3.0_0          64 KB  r
    r-highr-0.6                |         r3.3.0_0          33 KB  r
    r-iterators-1.0.8          |         r3.3.0_0         309 KB  r
    r-jsonlite-0.9.20          |         r3.3.0_0        1018 KB  r
    r-kernsmooth-2.23_15       |         r3.3.0_0          94 KB  r
    r-labeling-0.3             |         r3.3.0_2          45 KB  r
    r-lattice-0.20_33          |         r3.3.0_0         777 KB  r
    r-lazyeval-0.1.10          |         r3.3.0_2          52 KB  r
    r-magrittr-1.5             |         r3.3.0_2         161 KB  r
    r-maps-3.1.0               |         r3.3.0_0         3.4 MB  r
    r-mass-7.3_45              |         r3.3.0_0         1.1 MB  r
    r-mime-0.4                 |         r3.3.0_0          34 KB  r
    r-nloptr-1.0.4             |         r3.3.0_2         586 KB  r
    r-nnet-7.3_12              |         r3.3.0_0         111 KB  r
    r-openssl-0.9.3            |         r3.3.0_0         1.9 MB  r
    r-r6-2.1.2                 |         r3.3.0_0         236 KB  r
    r-randomforest-4.6_12      |         r3.3.0_0         165 KB  r
    r-rcolorbrewer-1.1_2       |         r3.3.0_2          29 KB  r
    r-rcpp-0.12.5              |         r3.3.0_0         2.2 MB  r
    r-repr-0.7                 |         r3.3.0_0          62 KB  r
    r-rpart-4.1_10             |         r3.3.0_0         897 KB  r
    r-sparsem-1.7              |         r3.3.0_0         763 KB  r
    r-spatial-7.3_11           |         r3.3.0_0         139 KB  r
    r-stringi-1.0_1            |         r3.3.0_0        10.4 MB  r
    r-uuid-0.1_2               |         r3.3.0_0          21 KB  r
    r-xtable-1.8_2             |         r3.3.0_0         705 KB  r
    r-yaml-2.1.13              |         r3.3.0_2          97 KB  r
    m2w64-curl-7.48.0          |                1         1.1 MB  r
    r-catools-1.17.1           |         r3.3.0_2         190 KB  r
    r-class-7.3_14             |         r3.3.0_0          95 KB  r
    r-data.table-1.9.6         |         r3.3.0_0         1.6 MB  r
    r-dplyr-0.4.3              |         r3.3.0_0         1.3 MB  r
    r-foreach-1.4.3            |         r3.3.0_0         374 KB  r
    r-hexbin-1.27.1            |         r3.3.0_0         811 KB  r
    r-htmltools-0.3.5          |         r3.3.0_0         128 KB  r
    r-httpuv-1.3.3             |         r3.3.0_0         285 KB  r
    r-irdisplay-0.3            |         r3.3.0_2          26 KB  r
    r-markdown-0.7.7           |         r3.3.0_2         116 KB  r
    r-matrix-1.2_6             |         r3.3.0_0         3.2 MB  r
    r-minqa-1.2.4              |         r3.3.0_2         109 KB  r
    r-munsell-0.4.3            |         r3.3.0_0         137 KB  r
    r-nlme-3.1_128             |         r3.3.0_0         2.1 MB  r
    r-pbdzmq-0.2_2             |         r3.3.0_0         2.1 MB  r
    r-plyr-1.8.3               |         r3.3.0_0         749 KB  r
    r-stringr-1.0.0            |         r3.3.0_0          88 KB  r
    r-zoo-1.7_13               |         r3.3.0_0         899 KB  r
    r-curl-0.9.7               |         r3.3.0_0         2.4 MB  r
    r-evaluate-0.9             |         r3.3.0_0          45 KB  r
    r-glmnet-2.0_5             |         r3.3.0_0         1.6 MB  r
    r-htmlwidgets-0.6          |         r3.3.0_0         737 KB  r
    r-matrixmodels-0.4_1       |         r3.3.0_0         261 KB  r
    r-mgcv-1.8_12              |         r3.3.0_0         2.1 MB  r
    r-pryr-0.1.2               |         r3.3.0_0         197 KB  r
    r-rcppeigen-0.3.2.8.1      |         r3.3.0_0         1.2 MB  r
    r-reshape2-1.4.1           |         r3.3.0_2          98 KB  r
    r-scales-0.4.0             |         r3.3.0_0         218 KB  r
    r-shiny-0.13.2             |         r3.3.0_0         2.1 MB  r
    r-survival-2.39_4          |         r3.3.0_0         4.6 MB  r
    r-tidyr-0.4.1              |         r3.3.0_0         161 KB  r
    r-xts-0.9_7                |         r3.3.0_2         640 KB  r
    r-ggplot2-2.1.0            |         r3.3.0_0         2.0 MB  r
    r-httr-1.1.0               |         r3.3.0_0         266 KB  r
    r-irkernel-0.6.1           |         r3.3.0_0          77 KB  r
    r-knitr-1.13               |         r3.3.0_0         777 KB  r
    r-lme4-1.1_12              |         r3.3.0_0         4.1 MB  r
    r-quantreg-5.24            |         r3.3.0_0         1.8 MB  r
    r-ttr-0.23_1               |         r3.3.0_0         441 KB  r
    r-pbkrtest-0.4_6           |         r3.3.0_0         221 KB  r
    r-quantmod-0.4_5           |         r3.3.0_2         517 KB  r
    r-rmarkdown-0.9.6          |         r3.3.0_0         1.7 MB  r
    r-car-2.1_2                |         r3.3.0_0         1.5 MB  r
    r-gistr-0.3.6              |         r3.3.0_0         1.7 MB  r
    r-caret-6.0_68             |         r3.3.0_0         4.5 MB  r
    r-rbokeh-0.4.2             |         r3.3.0_0         1.2 MB  r
    r-3.3.0                    |         r3.3.0_1          652 B  r
    r-recommended-3.3.0        |         r3.3.0_0          842 B  r
    r-essentials-1.3           |                1           1 KB  r
    ------------------------------------------------------------
                                           Total:       154.5 MB

The following NEW packages will be INSTALLED:

    m2w64-bwidget:           1.9.10-1             r
    m2w64-bzip2:             1.0.6-5              r
    m2w64-c-ares:            1.11.0-1             r
    m2w64-ca-certificates:   20150426-101         r
    m2w64-curl:              7.48.0-1             r
    m2w64-expat:             2.1.1-1              r
    m2w64-fftw:              3.3.4-5              r
    m2w64-flac:              1.3.1-2              r
    m2w64-gcc-libgfortran:   5.3.0-5              r
    m2w64-gcc-libs:          5.3.0-6              r
    m2w64-gettext:           0.19.7-1             r
    m2w64-gmp:               6.1.0-1              r
    m2w64-gnutls:            3.4.11-1             r
    m2w64-gsl:               2.1-1                r
    m2w64-jansson:           2.7-2                r
    m2w64-libffi:            3.2.1-3              r
    m2w64-libiconv:          1.14-5               r
    m2w64-libidn:            1.32-3               r
    m2w64-libjpeg-turbo:     1.4.2-2              r
    m2w64-libmetalink:       0.1.3-1              r
    m2w64-libogg:            1.3.2-2              r
    m2w64-libpng:            1.6.21-1             r
    m2w64-libsndfile:        1.0.26-1             r
    m2w64-libssh2:           1.7.0-1              r
    m2w64-libsystre:         1.0.1-2              r
    m2w64-libtasn1:          4.7-1                r
    m2w64-libtiff:           4.0.6-1              r
    m2w64-libtre-git:        122.c2f5d13-4        r
    m2w64-libvorbis:         1.3.5-1              r
    m2w64-libwinpthread-git: 5.0.0.4634.697f757-1 r
    m2w64-libxml2:           2.9.3-2              r
    m2w64-mpfr:              3.1.4-3              r
    m2w64-nettle:            3.1.1-3              r
    m2w64-nghttp2:           1.9.2-1              r
    m2w64-nlopt:             2.4.2-2              r
    m2w64-openssl:           1.0.2.g-1            r
    m2w64-p11-kit:           0.23.2-1             r
    m2w64-pcre:              8.38-1               r
    m2w64-rtmpdump-git:      499.a107cef-3        r
    m2w64-speex:             1.2rc2-2             r
    m2w64-speexdsp:          1.2rc3-2             r
    m2w64-tcl:               8.6.5-1              r
    m2w64-tk:                8.6.5-1              r
    m2w64-tktable:           2.10-4               r
    m2w64-wineditline:       2.101-4              r
    m2w64-xz:                5.2.2-1              r
    m2w64-zlib:              1.2.8-9              r
    msys2-conda-epoch:       20160418-0           r
    r:                       3.3.0-r3.3.0_1       r
    r-assertthat:            0.1-r3.3.0_2         r
    r-base:                  3.3.0-0              r
    r-base64enc:             0.1_3-r3.3.0_0       r
    r-bh:                    1.60.0_2-r3.3.0_0    r
    r-bitops:                1.0_6-r3.3.0_2       r
    r-boot:                  1.3_18-r3.3.0_0      r
    r-car:                   2.1_2-r3.3.0_0       r
    r-caret:                 6.0_68-r3.3.0_0      r
    r-catools:               1.17.1-r3.3.0_2      r
    r-chron:                 2.3_47-r3.3.0_0      r
    r-class:                 7.3_14-r3.3.0_0      r
    r-cluster:               2.0.4-r3.3.0_0       r
    r-codetools:             0.2_14-r3.3.0_0      r
    r-colorspace:            1.2_6-r3.3.0_0       r
    r-curl:                  0.9.7-r3.3.0_0       r
    r-data.table:            1.9.6-r3.3.0_0       r
    r-dbi:                   0.4_1-r3.3.0_0       r
    r-dichromat:             2.0_0-r3.3.0_2       r
    r-digest:                0.6.9-r3.3.0_0       r
    r-dplyr:                 0.4.3-r3.3.0_0       r
    r-essentials:            1.3-1                r
    r-evaluate:              0.9-r3.3.0_0         r
    r-foreach:               1.4.3-r3.3.0_0       r
    r-foreign:               0.8_66-r3.3.0_0      r
    r-formatr:               1.4-r3.3.0_0         r
    r-ggplot2:               2.1.0-r3.3.0_0       r
    r-gistr:                 0.3.6-r3.3.0_0       r
    r-glmnet:                2.0_5-r3.3.0_0       r
    r-gtable:                0.2.0-r3.3.0_0       r
    r-hexbin:                1.27.1-r3.3.0_0      r
    r-highr:                 0.6-r3.3.0_0         r
    r-htmltools:             0.3.5-r3.3.0_0       r
    r-htmlwidgets:           0.6-r3.3.0_0         r
    r-httpuv:                1.3.3-r3.3.0_0       r
    r-httr:                  1.1.0-r3.3.0_0       r
    r-irdisplay:             0.3-r3.3.0_2         r
    r-irkernel:              0.6.1-r3.3.0_0       r
    r-iterators:             1.0.8-r3.3.0_0       r
    r-jsonlite:              0.9.20-r3.3.0_0      r
    r-kernsmooth:            2.23_15-r3.3.0_0     r
    r-knitr:                 1.13-r3.3.0_0        r
    r-labeling:              0.3-r3.3.0_2         r
    r-lattice:               0.20_33-r3.3.0_0     r
    r-lazyeval:              0.1.10-r3.3.0_2      r
    r-lme4:                  1.1_12-r3.3.0_0      r
    r-magrittr:              1.5-r3.3.0_2         r
    r-maps:                  3.1.0-r3.3.0_0       r
    r-markdown:              0.7.7-r3.3.0_2       r
    r-mass:                  7.3_45-r3.3.0_0      r
    r-matrix:                1.2_6-r3.3.0_0       r
    r-matrixmodels:          0.4_1-r3.3.0_0       r
    r-mgcv:                  1.8_12-r3.3.0_0      r
    r-mime:                  0.4-r3.3.0_0         r
    r-minqa:                 1.2.4-r3.3.0_2       r
    r-munsell:               0.4.3-r3.3.0_0       r
    r-nlme:                  3.1_128-r3.3.0_0     r
    r-nloptr:                1.0.4-r3.3.0_2       r
    r-nnet:                  7.3_12-r3.3.0_0      r
    r-openssl:               0.9.3-r3.3.0_0       r
    r-pbdzmq:                0.2_2-r3.3.0_0       r
    r-pbkrtest:              0.4_6-r3.3.0_0       r
    r-plyr:                  1.8.3-r3.3.0_0       r
    r-pryr:                  0.1.2-r3.3.0_0       r
    r-quantmod:              0.4_5-r3.3.0_2       r
    r-quantreg:              5.24-r3.3.0_0        r
    r-r6:                    2.1.2-r3.3.0_0       r
    r-randomforest:          4.6_12-r3.3.0_0      r
    r-rbokeh:                0.4.2-r3.3.0_0       r
    r-rcolorbrewer:          1.1_2-r3.3.0_2       r
    r-rcpp:                  0.12.5-r3.3.0_0      r
    r-rcppeigen:             0.3.2.8.1-r3.3.0_0   r
    r-recommended:           3.3.0-r3.3.0_0       r
    r-repr:                  0.7-r3.3.0_0         r
    r-reshape2:              1.4.1-r3.3.0_2       r
    r-rmarkdown:             0.9.6-r3.3.0_0       r
    r-rpart:                 4.1_10-r3.3.0_0      r
    r-scales:                0.4.0-r3.3.0_0       r
    r-shiny:                 0.13.2-r3.3.0_0      r
    r-sparsem:               1.7-r3.3.0_0         r
    r-spatial:               7.3_11-r3.3.0_0      r
    r-stringi:               1.0_1-r3.3.0_0       r
    r-stringr:               1.0.0-r3.3.0_0       r
    r-survival:              2.39_4-r3.3.0_0      r
    r-tidyr:                 0.4.1-r3.3.0_0       r
    r-ttr:                   0.23_1-r3.3.0_0      r
    r-uuid:                  0.1_2-r3.3.0_0       r
    r-xtable:                1.8_2-r3.3.0_0       r
    r-xts:                   0.9_7-r3.3.0_2       r
    r-yaml:                  2.1.13-r3.3.0_2      r
    r-zoo:                   1.7_13-r3.3.0_0      r

The following packages will be UPDATED:

    conda:                   4.0.5-py35_0 defaults --> 4.0.8-py35_0         defaults

Proceed ([y]/n)? y

Fetching packages ...
m2w64-gcc-libg 100% |###############################| Time: 0:00:20  17.82 kB/s
m2w64-gcc-libs 100% |###############################| Time: 0:00:08  87.76 kB/s
m2w64-gettext- 100% |###############################| Time: 0:03:09  23.70 kB/s
m2w64-libjpeg- 100% |###############################| Time: 0:00:06 110.16 kB/s
m2w64-libmetal 100% |###############################| Time: 0:00:03  21.09 kB/s
m2w64-libpng-1 100% |###############################| Time: 0:00:07  54.36 kB/s
m2w64-libtasn1 100% |###############################| Time: 0:00:02  85.49 kB/s
m2w64-libvorbi 100% |###############################| Time: 0:00:05  89.47 kB/s
m2w64-nettle-3 100% |###############################| Time: 0:00:24  28.56 kB/s
An unexpected error has occurred, please consider sending the:07:17   4.90 kB/s
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 226, in _error_catcher
    yield
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 301, in read
    data = self._fp.read(amt)
  File "D:\Program Files\Python\Anaconda3\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "D:\Program Files\Python\Anaconda3\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "D:\Program Files\Python\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "D:\Program Files\Python\Anaconda3\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "D:\Program Files\Python\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Program Files\Python\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

D:\Program Files\Python\Anaconda3>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : D:\Program Files\Python\Anaconda3  (writable)
  default environment : D:\Program Files\Python\Anaconda3
     envs directories : D:\Program Files\Python\Anaconda3\envs
        package cache : D:\Program Files\Python\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Luxio\.condarc
    is foreign system : False



________________________________
发件人: Ray Donnelly <notifications@github.com>
发送时间: 2016年6月10日 13:12
收件人: conda/conda
抄送: Luxios; Author
主题: Re: [conda/conda] trouble with 'conda install -c r r-essentials' (#2643)


Please show the output of conda info

Also, would it be possible to check two if this was a transitory network issue, test this by trying again and seeing if you get the same result.

Also, this error could be related to https://support.microsoft.com/en-us/kb/981344


.. can you try disabling your firewall and trying again?

―

**Comment by mingwandroid** [comment]
Thanks. Another thing to test is installing `anaconda` to a path without spaces in it, like C:\Users\Luxio\Anaconda3.

**Comment by Luxios** [comment]
I am sorry but I have met another problem as following :
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序       |  12%
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
系统找不到指定的路径。
系统找不到指定的路径。
系统找不到指定的路径。
[      COMPLETE      ]|##################################################| 100%

After this I open the jupyter notebook, and build a new R script , it happens to me that
[cid:54b94674-8a75-4332-8a8b-03cf12468b1e]
the kernel is always dead.But I change  to use python ,it works well. How can I solve this problem?
________________________________
发件人: Ray Donnelly <notifications@github.com>
发送时间: 2016年6月11日 8:35
收件人: conda/conda
抄送: Luxios; Author
主题: Re: [conda/conda] trouble with 'conda install -c r r-essentials' (#2643)


Thanks. Another thing to test is installing anaconda to a path without spaces in it, like C:\Users\Luxio\Anaconda3.

―

**Comment by kalefranz** [comment]
Intermittent HTTP error.
