### ISSUE TITLE
OSX: Error: `Error:  Package missing in current osx-64 channels:    - package_name`

### ISSUE THREAD

**Issue by jboissard** [conda/conda#2647]
After installing Anaconda (both for python 2 and 3), when I run `conda create` the following error is displayed:
`Error:  Package missing in current osx-64 channels:    - package_name`

I realised the file `.condarc` had `PACKAGE_NAME` included which caused the error. I removed manually and solved the issue.

(OS X 10.10)

**Comment by nktvys** [comment]
Hi!
How did you manually remove the PACKAGE_NAME? 
Where can I find the .condarc file?

**Comment by kalefranz** [comment]
> Where can I find the .condarc file?

The location is given by `conda info`.
