### ISSUE TITLE
No such file or directory sqlite3.pc  in creating environment

### ISSUE THREAD

**Issue by emafermon** [conda/conda#2655]
emanuel@emanuel-Inspiron-560:~$ conda create -n nombrecito pandas seaborn
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /home/emanuel/anaconda3/envs/nombrecito:

The following packages will be downloaded:

| package | build |
| --- | --- |
| libgfortran-3.0.0 | 1         281 KB |
| freetype-2.5.5 | 1         2.5 MB |
| pyparsing-2.1.4 | py35_0          72 KB |
| pytz-2016.4 | py35_0         177 KB |
| python-dateutil-2.5.3 | py35_0         237 KB |
| qt-4.8.7 | 2        34.1 MB |
| scipy-0.17.1 | np111py35_0        29.5 MB |
| pandas-0.18.1 | np111py35_0        14.1 MB |
| pyqt-4.11.4 | py35_2         3.5 MB |
| matplotlib-1.5.1 | np111py35_0         8.4 MB |
| seaborn-0.7.0 | py35_0         274 KB |

```
------------------------------------------------------------
                                       Total:        93.2 MB
```

The following NEW packages will be INSTALLED:

```
cycler:          0.10.0-py35_0     
fontconfig:      2.11.1-5          
freetype:        2.5.5-1           
libgfortran:     3.0.0-1           
libpng:          1.6.17-0          
libxml2:         2.9.2-0           
matplotlib:      1.5.1-np111py35_0 
mkl:             11.3.3-0          
numpy:           1.11.0-py35_1     
openssl:         1.0.2h-1          
pandas:          0.18.1-np111py35_0
pip:             8.1.2-py35_0      
pyparsing:       2.1.4-py35_0      
pyqt:            4.11.4-py35_2     
python:          3.5.1-0           
python-dateutil: 2.5.3-py35_0      
pytz:            2016.4-py35_0     
qt:              4.8.7-2           
readline:        6.2-2             
scipy:           0.17.1-np111py35_0
seaborn:         0.7.0-py35_0      
setuptools:      23.0.0-py35_0     
sip:             4.16.9-py35_0     
six:             1.10.0-py35_0     
sqlite:          3.13.0-0          
tk:              8.5.18-0          
wheel:           0.29.0-py35_0     
xz:              5.0.5-1           
zlib:            1.2.8-3           
```

Proceed ([y]/n)? y

Fetching packages ...
libgfortran-3. 100% |################################| Time: 0:00:00 395.32 kB/s
freetype-2.5.5 100% |################################| Time: 0:00:04 634.65 kB/s
pyparsing-2.1. 100% |################################| Time: 0:00:00 187.14 kB/s
pytz-2016.4-py 100% |################################| Time: 0:00:00 319.76 kB/s
python-dateuti 100% |################################| Time: 0:00:00 370.38 kB/s
qt-4.8.7-2.tar 100% |################################| Time: 0:00:55 647.15 kB/s
scipy-0.17.1-n 100% |################################| Time: 0:00:49 625.79 kB/s
pandas-0.18.1- 100% |################################| Time: 0:00:21 672.28 kB/s
pyqt-4.11.4-py 100% |################################| Time: 0:00:05 642.37 kB/s
matplotlib-1.5 100% |################################| Time: 0:00:13 670.10 kB/s
seaborn-0.7.0- 100% |################################| Time: 0:00:00 405.86 kB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  17%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/emanuel/anaconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/install.py", line 679, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/home/emanuel/anaconda3/lib/python3.5/site-packages/conda/install.py", line 278, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/emanuel/anaconda3/envs/nombrecito/lib/pkgconfig/sqlite3.pc'

emanuel@emanuel-Inspiron-560:~$ conda --info
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --info
emanuel@emanuel-Inspiron-560:~$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.8
```

  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/emanuel/anaconda3  (writable)
  default environment : /home/emanuel/anaconda3
     envs directories : /home/emanuel/anaconda3/envs
        package cache : /home/emanuel/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

emanuel@emanuel-Inspiron-560:~$

**Comment by tyler-thetyrant** [comment]
Closing outdated.
