### ISSUE TITLE
"conda search" should have additional filtering option for requirement

### ISSUE THREAD

**Issue by tomkinsc** [conda/conda#2664]
**Background:**
This is the result of a [conversation](https://github.com/bioconda/bioconda-recipes/issues/1734) in the GitHub repo for the bioconda channel. In general, I'm not convinced language-specific package prefixes make much sense in the conda universe, since conda packages can depend on combinations of languages. The requirements list should define the language(s), and the package name should only be used to disambiguate the package from other packages.

**Problem:**
Packages can have the same name but exist for multiple languages.

**Proposed solution:**
I'd love for `conda search` to expose a `--requires` argument so we can filter by language (or any other requirement), similar to how `--platform` allows us to filter by platform. It would accept a package name (ex. `--requires python`). Not sure if it would accept a full version string, or if multiple packages could be specified.

Would this require changes to anaconda.org, or does the anaconda API already expose dependencies when searching?

**Comment by kalefranz** [comment]
We actually have a proposal/spec here that I'm really existed about.  It's a concept we're calling ecosystem namespaces.

https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1

Hopefully we get some bandwidth to implement it soon.
