### ISSUE TITLE
Offline Environment Creation Fails with KeyError

### ISSUE THREAD

**Issue by aagnone3** [conda/conda#2666]
When trying to create a new environment in offline mode via cloning, the creation fails with a KeyError for packages that are installed in the environment being cloned.

Steps to re-produce:
mkdir temp
cd temp
conda create -n bare numpy
conda create --offline -n offline_bare --clone bare

Creating the "bare" environment with numpy installed a few dependencies. Repeatedly calling the above command to create the cloned environment will fail with a KeyError for the .tar.bz2 file of one of those dependencies.

![error_capture](https://cloud.githubusercontent.com/assets/10716867/16052571/d306f4c6-3232-11e6-962b-6cce5e76eefd.PNG)

[conda_info.txt](https://github.com/conda/conda/files/314510/conda_info.txt)

**Comment by kalefranz** [comment]
@aagnone3 I have several tests that indicate this should work as of conda 4.1.2.  Can you update conda and then confirm if the issue is fixed?

**Comment by aagnone3** [comment]
Confirmed, thank you!
