### ISSUE TITLE
Conda will hang after executing 'conda install conda=4.0.8'

### ISSUE THREAD

**Issue by aguzmanballen** [conda/conda#2671]
After upgrading to the latest conda package on Windows, I found that there were times executing certain conda commands would cause conda to hang, and Ctrl+C wouldn't get me out.

Here is exactly what was executed:
it freezes.
 
C:\Users\aguzmanb>conda list -e
This file may be used to create an environment using:
$ conda create --name <env> --file <this file>
platform: win-64
conda=4.0.5=py35_0
conda-env=2.4.5=py35_0
menuinst=1.3.2=py35_0
pip=8.1.1=py35_1
pycosat=0.6.1=py35_0
pycrypto=2.6.1=py35_3
python=3.5.1=4
pyyaml=3.11=py35_3
requests=2.9.1=py35_0
setuptools=20.3=py35_0
vs2015_runtime=14.00.23026.0=0
wheel=0.29.0=py35_0
 
C:\Users\aguzmanb>conda install conda=4.0.8
Fetching package metadata: ....
Solving package specifications: .........
 
Package plan for installation in environment C:\Users\aguzmanb\Development\Miniconda3:
 
The following packages will be downloaded:
 
    package                    |            build
    ---------------------------|-----------------
    conda-4.0.8                |           py35_0         234 KB
 
The following packages will be UPDATED:
 
    conda: 4.0.5-py35_0 --> 4.0.8-py35_0
 
Proceed ([y]/n)? y
 
Fetching packages ...
conda-4.0.8-py 100% |###############################| Time: 0:00:00 612.31 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
 
C:\Users\aguzmanb>conda update conda
Fetching package metadata: ....
.Solving package specifications: .........
 
Package plan for installation in environment C:\Users\aguzmanb\Development\Miniconda3:
 
The following packages will be downloaded:
 
    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.0            |           py35_0          69 KB
    ruamel_yaml-0.11.7         |           py35_0         203 KB
    conda-4.1.0                |           py35_0         246 KB
    ------------------------------------------------------------
                                           Total:         518 KB
 
The following NEW packages will be INSTALLED:
 
    ruamel_yaml: 0.11.7-py35_0
 
The following packages will be UPDATED:
 
    conda:       4.0.8-py35_0 --> 4.1.0-py35_0
    conda-env:   2.4.5-py35_0 --> 2.5.0-py35_0
 
Proceed ([y]/n)? y
 
Fetching packages ...
conda-env-2.5. 100% |###############################| Time: 0:00:00 314.38 kB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00 592.07 kB/s
conda-4.1.0-py 100% |###############################| Time: 0:00:00 619.87 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
 
C:\Users\aguzmanb>conda install conda=4.0.8
Fetching package metadata ...
 
What is also peculiar is that after hitting Ctrl+C 5 times and waiting for 7 minutes, I am able to escape the process with the following information:
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/

I am pretty certain it is not a proxy issue at my end because I was able to conda install conda=4.0.8 a few commands before it failed. Here is the debug information:
C:\Users\aguzmanb>conda --debug install conda=4.0.8
DEBUG:conda.fetch:channel_urls=OrderedDict([('https://repo.continuum.io/pkgs/free/win-64/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/free/noarch/', ('
defaults', 1)), ('https://repo.continuum.io/pkgs/pro/win-64/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/pro/noarch/', ('defaults', 1))])
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io

**Comment by kalefranz** [comment]
As of 7:04pm Central Time, we've updated the conda 4.0.x dependencies to specify `conda-env <2.5.0`.  We're aware that this had been causing a problem for some people.  Can you confirm that this has also fixed your problem?

**Comment by aguzmanballen** [comment]
Someone else on my team experienced this problem today. However, we work behind a proxy and specifying http_proxy in ~/.condarc fixed this problem for me. What is strange however is that the problem didn't occur before so upgrading to conda=4.1.0 did something to change the behavior. Perhaps conda now does not look at the condarc environment variable but instead relies solely on ~/.condarc?

**Comment by msarahan** [comment]
Consolidating to #2677
