### ISSUE TITLE
conda update ipython failed on a clean install

### ISSUE THREAD

**Issue by ChristopherShort** [conda/conda#2673]
On OSX - reporting issue after ```conda update ipython``` failed on a clean install.

foolishly I tried to update ipython whilst an ipython session (in jupyter) was running.  It lost the $PATH reference to anaconda and despite putting it back in the bash_profile, conda commands still wouldn't execute in the terminal, nor would ipython launch.

Removed the anaconda3 installation, and reinstalled (via the OSX graphical installer).

Conda commands now work, jupyter starts up (and runs python)

but ```conda update ipython``` fails again and asks to report issue - and jupyter loses track of python kernel.

```jupyter kernelspec list``` returns:

[ListKernelSpecs] WARNING | Native kernel (python3) is not available
[ListKernelSpecs] WARNING | Native kernel (python3) is not available
No kernels available

Traceback and conda info below:

Traceback (most recent call last):
  File "/Users/ChristopherShort/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 80, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/install.py", line 1040, in link
    os.makedirs(dst_dir)
  File "/Users/ChristopherShort/anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/simplegeneric-0.8.1-py3.5.egg-info'

```Conda info``` returns
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.0
  conda-build version : 0+unknown
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/ChristopherShort/anaconda  (writable)
  default environment : /Users/ChristopherShort/anaconda
     envs directories : /Users/ChristopherShort/anaconda/envs
        package cache : /Users/ChristopherShort/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ChristopherShort/.condarc
    is foreign system : False

Prior to trying to update ipython, installed feather (via conda forge), and ran ```conda update conda``` and ```conda update anaconda``` - both reported all up to date

cheers  
(I'll reinstall again - but not update ipython  :-)

**Comment by kalefranz** [comment]
> It lost the $PATH reference to anaconda

I don't understand why or how that happened. Definitely frustrating.

> despite putting it back in the bash_profile, conda commands still wouldn't execute in the terminal, nor would ipython launch

After you modify `~/.bash_profile`, for those changes to take effect, you need to either `source ~/.bash_profile` in your current terminal, or close that terminal tab/window and start a new terminal session.

> but `conda update ipython` fails again and asks to report issue

Oh, so now I understand the reason for creating the issue ticket.

> FileExistsError: [Errno 17] File exists: '/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/simplegeneric-0.8.1-py3.5.egg-info'

Looks like the anaconda 4.0 version of ipython is 4.1.2 and the most recent version in the repo is 4.2.0.

@ilanschnell Do you know what's getting tripped up here?

**Comment by ChristopherShort** [comment]
thanks - apologies I wasn't clearer that the first part was background only and in case it mattered - it was the subsequent clean install  issue that was the surprise.

Love the anaconda work - much appreciated.

**Comment by kalefranz** [comment]
Duplicated by #2714 and #2722

**Comment by kalefranz** [comment]
@mingwandroid I'm stumped by this one so far, and I think msarahan has enough on his plate right now.  Any chance your eyes could take a look?

**Comment by mingwandroid** [comment]
Sure thing @kalefranz. I'm actually working on Jupyter stuff for R on OS X, so it's in my field of vision already.

**Comment by mingwandroid** [comment]
I cannot reproduce this at present. In order, I did the following:

    1. Closed all my terminal windows and quit Terminal.app (CMD+Q to make sure it was really gone).
    2. Downloaded and installed http://repo.continuum.io/archive/Anaconda3-4.0.0-MacOSX-x86_64.pkg to `/Users/rdonnelly/anaconda`, selecting to add to PATH.
    3. Opened Terminal.app and verified that `which conda` gave the correct result.
    4. Issued `conda update ipython` which gave me the following:
```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/rdonnelly/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-custom            |           py35_0           3 KB
    backports-1.0              |           py35_0           1 KB
    conda-env-2.5.0            |           py35_0          29 KB
    ruamel_yaml-0.11.7         |           py35_0         165 KB
    conda-4.1.1                |           py35_0         202 KB
    get_terminal_size-1.0.0    |           py35_0           5 KB
    ipython-4.2.0              |           py35_1         988 KB
    ------------------------------------------------------------
                                           Total:         1.4 MB

The following NEW packages will be INSTALLED:

    backports:         1.0-py35_0   
    get_terminal_size: 1.0.0-py35_0 
    ruamel_yaml:       0.11.7-py35_0

The following packages will be UPDATED:

    conda:             4.0.5-py35_0      --> 4.1.1-py35_0 
    conda-env:         2.4.5-py35_0      --> 2.5.0-py35_0 
    ipython:           4.1.2-py35_1      --> 4.2.0-py35_1 

The following packages will be DOWNGRADED:

    anaconda:          4.0.0-np110py35_0 --> custom-py35_0

Proceed ([y]/n)?
```

    5. From Terminal, I entered `jupyter notebook`, created a new Python 3 notebook and tested with `print('Hello World!')`

Everything worked as expected.

**Comment by mingwandroid** [comment]
@kalefranz, correct me if I'm wrong, but I don't think this report is related to https://github.com/conda/conda/issues/2722 since this bug report mentions trying the steps I listed which would mean that the run of `conda update ipython` was performed by the old `conda` that's in `Anaconda3-4.0.0`

I guess you want me to have a go at https://github.com/conda/conda/issues/2722 anyway? I'll get on it.

**Comment by kalefranz** [comment]
Oh I saw this line in the stack trace, and assumed they were all related to the same root cause.

    File "/Users/ChristopherShort/anaconda/lib/python3.5/site-packages/conda/install.py", line 1040, in link
    os.makedirs(dst_dir)

#2722 and #2714 both look very similar to me too.

**Comment by ChristopherShort** [comment]
On a clean macbook in the house, I installed anaconda following most of the above steps, and it worked as reported by @mingwandroid.

The only differences being I used the 3.5 graphical installer - so path added automatically.  And that the conda package was updated to 4.1.2 instead of 4.1.1.

But  on the attempts on my machine on Wednesday - I'm certain there was no `downgrade` of `anaconda`.   If I knew better, I'd search my bash history to confirm  :-)  

And my machine is busy analysing data today, so I can't redo an install at the moment to check that way.

**Comment by ChristopherShort** [comment]
You can probably close this.  It was probably something specific to what I did in updating ipython whilst having an ipython process running.

Unistalled anaconda again today  including  the .condarc and .conda and .continuum files.

Installed from the previously downloaded installer.  

After some tests issued `conda update ipython` and same instructions as @mingwandroid (w/o the downgrade).  

It ran fine.  And notebooks subsequently launched.

Interestingly, the anaconda navigator wasn't happy first time running.  It spent 15 minutes trying to `update package list` (or something like that).  

I killed it, relaunched a while later, and it worked fine.

thanks again for looking at it. Like you, I'm still stumped - but working now.

cheers

**Comment by kalefranz** [comment]
Explanation of bug given by @mcg1969 [here](https://github.com/conda-forge/python-simplegeneric-feedstock/issues/1#issuecomment-227312147).  Turns out to be a packaging bug and not a conda bug.

**Comment by ChristopherShort** [comment]
Interesting, iirc correctly I think I only installed feather and the latest matplotlib 2.0 beta from conda-forge

**Comment by kalefranz** [comment]
If `simplegeneric` is a dependency for either of those packages (or a dependency of a dependency), and conda-forge has specified the dependency name as `python-simplegeneric`, it's going to want to trample on the simplegeneric files already installed from the defaults channel.  There are other vectors to reach this clash, but I'm guessing that's the most likely.
