### ISSUE TITLE
`defaults` channel no longer installed by default

### ISSUE THREAD

**Issue by Korijn** [conda/conda#2675]
On AppVeyor, since last night, we have to add the `defaults` channel manually using `conda config --add channels defaults` before any packages are picked up. We think it has something to do with the release of conda 4.1.0.

**Comment by mcg1969** [comment]
Thanks for the report and sorry for the trouble. We've identified the issue and have already created a patch. It turns out that the bug manifests itself only if your `.condarc` is not empty when you add your first custom channel.

**Comment by Korijn** [comment]
Thanks for the update.

cc @ivoflipse

**Comment by kalefranz** [comment]
fixed in #2670.  Will be released with `4.1.1` today.
