### ISSUE TITLE
conda env remove fails with AttributeError: module 'conda.plan' has no attribute 'PREFIX'

### ISSUE THREAD

**Issue by ronert** [conda/conda#2679]
I tried this on three separate machines with conda 4.1.0. Every machine fails with `AttributeError: module 'conda.plan' has no attribute 'PREFIX'` when running `conda env remove -n environment_name` or `conda env remove -p environment_path`. This also happens on my Travis environment now causing my builds to fail. Any ideas?

**Comment by mcg1969** [comment]
I'm sorry for the trouble; we'll try and identify a fix quickly. In the meanwhile, can you do `conda remove -n environment_name --all` instead?

**Comment by ronert** [comment]
That works, thank you!

**Comment by kalefranz** [comment]
Moved issue to the conda-env repo
