### ISSUE TITLE
conda 4.1 breaks fish integrations

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#2680]
The new version does not work with fish at all. While the .fish script is finally there in the bin directory, it does not seem to kick in, since the new activate.py command is messing with it. How is it supposed to work?

This is the error I get:

```
$ conda activate myenv
Traceback (most recent call last):
  File "/home/jrodriguez/.local/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/jrodriguez/.local/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/home/jrodriguez/.local/anaconda/lib/python3.5/site-packages/conda/cli/activate.py", line 119, in main
    shelldict = shells[shell]
KeyError: 'myenv'
```

Meanwhile, I had to downgrade to conda 4.0 with `conda install conda=4.0`. Thank you!

**Comment by mcg1969** [comment]
I'd actually recommend downgrading to `4.0.8`. But we'll investigate this quickly!

**Comment by msarahan** [comment]
Working on it.  This is because we have to explicitly name the shell when calling ..activate and such.  Detecting the parent shell proved to be unreliable.

**Comment by kalefranz** [comment]
@jaimergp @frol For fish, where's the right place to put this `conda.fish` file.  I really don't want to put it in the `bin` directory, and I doubt that's the canonical fish place to put it anyway.

**Comment by frol** [comment]
@kalefranz How about `<env>/share/fish/conda-activate.fish`?

*Disclaimer: I haven't actually used conda fish integration, but rather wrote a simple script using `autoenvstack` fish plugin, `.env.fish`:*

```fish
set -gx VIRTUAL_ENV (dirname (status --current-filename))"/conda_env"
set -gx CONDA_DEFAULT_ENV "$VIRTUAL_ENV"
set -gx PATH "$VIRTUAL_ENV/bin" $PATH
```

**Comment by kalefranz** [comment]
Someday I intend to deprecate the `activate` script altogether, and then for bash/zsh have a conda.sh file that can be sourced on shell startup. The canonical bash location for something like this is `$PREFIX/etc/profile.d/conda.sh`.  Guess I just want to confirm the `$PREFIX/share/fish` directory is correct for whatever convention fish uses.

**Comment by jaimergp** [comment]
Well, all my custom files go into `~/.config/fish`, but fish also places some stuff in `~/.local/share/fish`.

According to this [issue](https://github.com/fish-shell/fish-shell/issues/1956) in their GH, there are more locations involved, as commented in this [commit](https://github.com/fish-shell/fish-shell/commit/c1b384e5d3f2f46e7d7a1b41e31c7aadc1d9ce28):

> Right after reading /usr/share/fish/config.fish and before reading /etc/fish/config.fish, fish will also read files in ~/.config/fish/conf.d/, /etc/fish/conf.d and /usr/share/fish/vendor_conf.d (the exact values depend on $XDG_CONFIG_HOME, $__fish_sysconfdir and $__fish_datadir). If there are files with the same name in two or all of these, fish will only attempt to read the first (skipping all files with that name if it is unreadable). ~/.config takes precedence over /etc/ which takes precedence over /usr. The path to the latter can also be gotten via `pkg-config` as "confdir", and is meant for third-party applications to integrate with fish.

Hope it helps!

**Comment by RSully** [comment]
> While the .fish script is finally there in the bin directory

I'm not seeing this. I just downloaded miniconda and upgraded to 4.1.0, but my bin is still lacking any fish files.

**Comment by jaimergp** [comment]
Yes, you are right, @RSully. My `conda.fish` dates from Nov 2015, when I grabbed the original PR and simply put it there. Then I saw the file in the bin folder of the master branch and assumed it was working. Sorry about that!

**Comment by kalefranz** [comment]
Thanks for the references @jaimergp. We'll put the file at `$PREFIX/etc/fish/conf.d/conda.fish`. And then if you want it in /etc/fish/conf.d/ you can symlink it.

**Comment by orangecms** [comment]
The `conf.d` directories are only supported since fish 2.3.0 actually. I put the script into `/usr/share/fish/functions/conda.fish` in the [package I created for AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-conda), but it doesn't work anymore since 4.1.0 with the same errors that @jaimergp mentioned.
