### ISSUE TITLE
conda run command removed in 4.1.0

### ISSUE THREAD

**Issue by davechallis** [conda/conda#2682]
After upgrading to 4.1.0:

```
$ conda run
```

outputs:

```
Error: Could not locate 'conda-run'
```

Also, when running `conda --help`, the documentation about the run command is no longer present.

**Comment by frol** [comment]
There is at least one good thing about this completely buggy release; I learned about `conda run`. (Hopefully, it is not too late.)

**Comment by kalefranz** [comment]
We took the conda-run command out I think. Didn't know anybody was using it.  We're releasing a 4.0.9 today with an `auto_update_conda` flag in `.condarc` and `conda config`.  You can now disable what had been an aggressive auto update.

https://github.com/conda/conda/pull/2686

We'll also consider just bringing it back.  I'll go back and look at the code that implemented it.  Won't happen in today's 4.1.1 release though.

**Comment by kalefranz** [comment]
To be clear, to back up and stay there, once 4.0.9 is released

    conda install conda=4.0.9
    conda config --set auto_update_conda false

**Comment by davechallis** [comment]
I'd forgotten I was using it too... (turns out we're using it inside a Dockerfile to run some commands with a conda environment at build time, since `source activate` doesn't work there, due to /bin/sh being used instead of /bin/bash).

Should be able to change that though :)

**Comment by michaelbrooks** [comment]
@kalefranz Was this breaking change announced or discussed somewhere?

**Comment by daler** [comment]
@kalefranz an example use-case for `conda-run`:

I build a lot of [snakamake](https://bitbucket.org/snakemake/snakemake/wiki/Home) workflows. Snakemake requires py3. Unfortunately it's pretty common to have py27-dependent tools. So how to run them from a snakemake workflow living in a py3 env?

The solution was to provide requirements-py3.txt and requirements-py2.txt and have users create 2 conda envs respectively. Call them py27 and py35. Activate py35, and run the workflow. Inside the workflow, I can assume that the user has a py27 env, so I can call `conda run -n py27 -- py2-specific-toolname arg1`.

Without `conda run`, an alternative is to supply the full path `/path/to/anaconda/envs/py27/bin/py2-specific-toolname`, but the user then has to configure their conda installation directory. Of course that can be done (e.g. as part of setup, have them export an environmental variable specifying where conda is living and check that within the workflow), but conda-run was really convenient. If it's not breaking anything or conflicting with anything, it would be great to have it back.

**Comment by kalefranz** [comment]
> Was this breaking change announced or discussed somewhere?

No, it wasn't.  We will do better in the future.

Especially when it comes to communication.  I've started an announcement list that you can sign up for at conda.pydata.org.  Please sign up.  The purpose is for communication directly from the conda core team. It will be low spam: three or so emails per month. We'll use it to announce major releases, upcoming features, and new policies and procedures.

With regard to `conda run` removal, the offending commit is 92ff4c8839874c8560ede7e77b5e33e3f2caffaf.  We *did* reserve merging that to the `4.1.0` release, and not in the middle of the `4.0.x` series.  If you still want to use `conda run`, you can roll back to `4.0.9` or the forthcoming `4.0.10`.

    conda install conda=4.0.9
    conda config --set auto_update_conda false

I think Ilan thought it was probably dead code when he removed the command.  I'm not opposed to bringing it back.  Actually, I'll re-open this ticket to represent that work.  I'm not sure I can make it for 4.2 though--I hope to have that out in the next week or two (at least a "canary" version).

**Comment by kalefranz** [comment]
The PR associated with 92ff4c8 is https://github.com/conda/conda/pull/2374.

**Comment by michaelbrooks** [comment]
Thanks, I'll sign up for that list. I can understand the motivation from that PR to remove `conda run`. We use conda run to programmatically check the version of pip inside of a specific conda environment (e.g. `conda run -n envname pip -- --version`). This is a reasonably clean, platform-independent way to access pip inside the environment without manually finding the full path to pip or manipulating the PATH.

**Comment by dan-svd** [comment]
Yea, please bring conda-run back, else programmatic starts of eg Pythonscripts in different testing environments won't work!!

**Comment by bollard** [comment]
Any more on bringing `conda run` back? It was a really useful little feature

**Comment by bollard** [comment]
Ran into this again today... Fingers crossed for 4.5!

**Comment by zevisert** [comment]
Bit of a bump, still wanting this feature again 👍

**Comment by NightMachinary** [comment]
Please add it back. Feature bloat in CLI doesn't hurt anybody.

**Comment by jakirkham** [comment]
Since `conda activate` is a thing, does this get any easier to readd?

**Comment by kalefranz** [comment]
There's no technical way to do this right until we have https://github.com/conda/conda/issues/6820, and in fact this issue is one component of the motivation for #6820.

**Comment by kalefranz** [comment]
Some people who find their way to this issue may find conda-execute helpful.  From https://github.com/conda/conda/issues/7154#issuecomment-385005511

> As you mentioned scripts, you may want to look at [`conda-execute`]( https://github.com/conda-tools/conda-execute ). That gives one the option to list dependencies in the script and use transient environments to run the script. Here's a [quick example]( https://github.com/conda-tools/conda-execute#running-a-conda-execute-script-from-the-command-line-without-the-conda-execute-prefix ).

**Comment by jakirkham** [comment]
Interesting, have not seen that issue. Why would that block running in existing shells that `conda` already supports?

Yeah, `conda-execute` is not really what I'm looking for. Thanks for the reminder though. :)

**Comment by kalefranz** [comment]
@jakirkham I think https://github.com/conda/conda/issues/7066#issuecomment-375043710 captures my thoughts here.
