### ISSUE TITLE
Conda install from file fails in version 4.1

### ISSUE THREAD

**Issue by heironeous** [conda/conda#2688]
I've recently installed linux-32 conda on CentOS 6.2. I confirmed this on linux-64 version as well.

If I run: `conda install ./FILE_1.tar.bz2`, I always get the error:
`Fetching package metadata ...Error: Could not find URL: file:///root/dir1/
`
If i downgrade to conda 4.0.8, it works fine.

Here's the command with the added `--debug` option:
```
$ conda --debug install ./FILE_1.tar.bz2
DEBUG:conda.fetch:channel_urls={'file:///root/dir1/': ('file:///root', 0)}
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:conda.fetch:Could not find URL: file:///root/dir1/
Error: Could not find URL: file:///root/dir1/
```

**Comment by kalefranz** [comment]
relates to #2642, but not exactly the same

**Comment by mcg1969** [comment]
I'll take this
