### ISSUE TITLE
Recursive shells created with source activate

### ISSUE THREAD

**Issue by jlafon** [conda/conda#2699]
I create ready to use Docker images as part of an automated build process, where the images contain ready to use conda environments. The last step of the build process is to populate the bash startup files with a line to activate the environment. As of conda 4.1.0 the behavior of source activate has changed, apparently executing a command in a shell, leading to the amusing image attached (output from pstree). This behavior should be documented, to prevent people from adding a 'source activate' to their autoenv or .profile files.

<img width="1722" alt="screenshot 2016-06-15 16 45 36" src="https://cloud.githubusercontent.com/assets/236514/16100414/5dabfdc2-331b-11e6-8090-885df9237b7c.png">

**Comment by msarahan** [comment]
Ah ha!  thank you hugely for enlightening us on this.  I think this was also reported as https://github.com/conda/conda/issues/2668

CC @kalefranz

**Comment by jakirkham** [comment]
Yep that does sound like the same thing.

**Comment by kalefranz** [comment]
fixed in #2831
