### ISSUE TITLE
conda update --all fails with unexpected error

### ISSUE THREAD

**Issue by je-miralles** [conda/conda#2709]
After updating OSX from 10.10 to 10.11 I did : 
`conda update conda`
`conda update anaconda`
no problem, but on doing : 
`conda update --all`
I get : 

>Traceback (most recent call last):
  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
>TimeoutError: [Errno 60] Operation timed out

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "/Users/juanemiliomiralles/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 49, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 324, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 404, in download
    chunk = resp.raw.read(2**14)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
>  File "/Users/juanemiliomiralles/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
>requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: TimeoutError(60, 'Operation timed out')", TimeoutError(60, 'Operation timed out'))

    $ conda info
    Current conda install:

    platform : osx-64
    conda version : 4.1.0
    conda-build version : 0+unknown
    python version : 3.5.1.final.0
    requests version : 2.9.1
    root environment : /Users/juanemiliomiralles/anaconda  (writable)
    default environment : /Users/juanemiliomiralles/anaconda
    envs directories : /Users/juanemiliomiralles/anaconda/envs
    package cache : /Users/juanemiliomiralles/anaconda/pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
    config file : None
    is foreign system : False

**Comment by mcg1969** [comment]
That looks like a server overload problem.

**Comment by kalefranz** [comment]
Agreed.  Can you try one more time?

On Thu, Jun 16, 2016 at 12:39 AM, Michael C. Grant <notifications@github.com
> wrote:

> That looks like a server overload problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda/conda/issues/2709#issuecomment-226392855>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABWks6Ahr4IN-l4UNrOWlr1OIkbYvixqks5qMOGGgaJpZM4I3Crk>
> .
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by je-miralles** [comment]
Indeed, worked when I ran it again.
