### ISSUE TITLE
Anaconda update issue from Windows 10.

### ISSUE THREAD

**Issue by benbrock26** [conda/conda#2714]
Hi Conda Community.

 I was using older version of Anaconda Python 2.7 on a Windows 10 machine.  I updated notebook using Anaconda launcher.  But once  did that I was able to launch anything again.  I tried looking on line to see if anyone else experienced the same problem.  I installed so good python packages since using Anaconda.  I may have to uninstall and install the newest version of Anaconda.  It seems now, I should install Anaconda Navigator.

Help!!!!

I found that others in the Anaconda community experienced the same issue: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/xRzg9zaOL98

conda update conda
conda update anaconda

C:\Users\Ben\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.0
  conda-build version : 1.14.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\Ben\Anaconda  (writable)
  default environment : C:\Users\Ben\Anaconda
     envs directories : C:\Users\Ben\Anaconda\envs
        package cache : C:\Users\Ben\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Ben\.condarc
    is foreign system : False

C:\Users\Ben\Anaconda>conda update anaconda
Fetching package metadata .......
Solving package specifications .............

Package plan for installation in environment C:\Users\Ben\Anaconda:

The following NEW packages will be INSTALLED:

    anaconda:           4.0.0-np110py27_0
    anaconda-client:    1.4.0-py27_0
    anaconda-navigator: 1.1.0-py27_0
    argcomplete:        1.0.0-py27_1
    astropy:            1.1.2-np110py27_0
    babel:              2.2.0-py27_0
    blaze:              0.9.1-py27_0
    bokeh:              0.11.1-py27_0
    bottleneck:         1.0.0-np110py27_0
    cffi:               1.5.2-py27_0
    chest:              0.2.3-py27_0
    clyent:             1.2.1-py27_0
    conda-manager:      0.3.1-py27_0
    configobj:          5.0.6-py27_0
    cryptography:       1.3-py27_0
    cycler:             0.10.0-py27_0
    dask:               0.8.1-py27_0
    datashape:          0.5.1-py27_0
    flask:              0.10.1-py27_1
    flask-cors:         2.1.2-py27_0
    gevent:             1.1.0-py27_0
    h5py:               2.5.0-np110py27_4
    ipykernel:          4.3.1-py27_0
    ipython:            4.1.2-py27_1
    ipywidgets:         4.1.1-py27_0
    jupyter:            1.0.0-py27_2
    jupyter_client:     4.2.2-py27_0
    jupyter_console:    4.1.1-py27_0
    jupyter_core:       4.1.0-py27_0
    llvmlite:           0.9.0-py27_0
    markupsafe:         0.23-py27_1
    mistune:            0.7.2-py27_0
    mkl-service:        1.1.2-py27_0
    mpmath:             0.19-py27_0
    multipledispatch:   0.4.8-py27_0
    nbconvert:          4.1.0-py27_0
    networkx:           1.11-py27_0
    nltk:               3.2-py27_0
    nose:               1.3.7-py27_0
    notebook:           4.1.0-py27_2
    numba:              0.24.0-np110py27_0
    numexpr:            2.5-np110py27_0
    odo:                0.4.2-py27_0
    openpyxl:           2.3.2-py27_0
    pandas:             0.18.0-np110py27_0
    partd:              0.3.2-py27_1
    patsy:              0.4.0-np110py27_0
    pep8:               1.7.0-py27_0
    pillow:             3.1.1-py27_0
    ply:                3.8-py27_0
    psutil:             4.1.0-py27_0
    py:                 1.4.31-py27_0
    pyasn1:             0.1.9-py27_0
    pycosat:            0.6.1-py27_0
    pycparser:          2.14-py27_0
    pycrypto:           2.6.1-py27_3
    pyflakes:           1.1.0-py27_0
    pygments:           2.1.1-py27_0
    pyopenssl:          0.15.1-py27_2
    pyparsing:          2.0.3-py27_0
    pyqt:               4.11.4-py27_5
    pytables:           3.2.2-np110py27_2
    pytest:             2.8.5-py27_0
    python-dateutil:    2.5.1-py27_0
    pytz:               2016.2-py27_0
    pywin32:            220-py27_1
    pyzmq:              15.2.0-py27_0
    qt:                 4.8.7-vc9_7        [vc9]
    qtawesome:          0.3.2-py27_0
    qtconsole:          4.2.0-py27_1
    qtpy:               1.0-py27_0
    rope:               0.9.4-py27_1
    scikit-image:       0.12.3-np110py27_0
    scikit-learn:       0.17.1-np110py27_0
    snowballstemmer:    1.2.1-py27_0
    sockjs-tornado:     1.0.1-py27_0
    sphinx:             1.3.5-py27_0
    sphinx_rtd_theme:   0.1.9-py27_0
    spyder:             2.3.8-py27_1
    sqlalchemy:         1.0.12-py27_0
    ssl_match_hostname: 3.4.0.2-py27_0
    statsmodels:        0.6.1-np110py27_0
    sympy:              1.0-py27_0
    toolz:              0.7.4-py27_0
    traitlets:          4.2.1-py27_0
    unicodecsv:         0.14.1-py27_0
    werkzeug:           0.11.4-py27_0
    xlsxwriter:         0.8.4-py27_0
    xlwings:            0.7.0-py27_0
    xlwt:               1.0.0-py27_0

The following packages will be DOWNGRADED:

    pip:                8.1.2-py27_0       --> 8.1.1-py27_1
    setuptools:         23.0.0-py27_0      --> 20.3-py27_0
    vs2008_runtime:     9.00.30729.1-1     --> 9.00.30729.1-0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |   1%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Ben\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\instructions.py", line 80, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "C:\Users\Ben\Anaconda\lib\site-packages\conda\install.py", line 1040, in link
    os.makedirs(dst_dir)
  File "C:\Users\Ben\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\Ben\\Anaconda\\Lib/site-packages/MarkupSafe-0.23-py2.7-win-amd64.egg-info'

**Comment by kalefranz** [comment]
fixed with #2717
