### ISSUE TITLE
`conda install foo.tar.bz2` doesn't work in 4.1

### ISSUE THREAD

**Issue by havocp** [conda/conda#2720]
In 4.0.8 I can `conda install /tmp/foo.tar.bz2` for example where foo.tar.bz2 is a package.

In 4.1.0, it gives an error about a bad file: URL or something.

**Comment by mcg1969** [comment]
Duplicate of https://github.com/conda/conda/issues/2688, and fixed in https://github.com/conda/conda/pull/2708. Thanks for the report!
