### ISSUE TITLE
Basic access authentification channels broken in 4.1.0

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#2725]
Previously it was possible to have a channel like:

https://user:password@myserver.com

or even have the user and password saved in `.netrc`. conda 4.1.0 and up ignore the credentials and give a 401 error (causing everything to break for users).

````
$ conda install conda=4.1.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........Error: HTTPError: 401 Client Error: Unauthorized for url:https://user:password@myserver.com
````

**Comment by kalefranz** [comment]
See this PR that is in 4.1.1. 
https://github.com/conda/conda/pull/2695

We disabled the requests library's use of .netrc. You can set `proxy_servers` in .condarc if you want. 

Besides reverting back to sucking up .netrc by default, how can we make things work best with your setup?

**Comment by Zaharid** [comment]
There is 4.1.0 that disables `.netrc`, but there is something else in 4.1.1 that furthermore disables urls with user and password explicitly in the channel urls (which I don't like very much anyway because the credentials appear in all the logs).

Thinks that could be good for me are:

 - Explicit support for basic auth in condarc (since it isn't in .netrc).
 - Support for client SSL certificates (which I believe is easy with requests).

Thanks.

**Comment by kalefranz** [comment]
> Explicit support for basic auth in condarc 

I'll add this tonight or tomorrow.  Will be in 4.1.2.

> Support for client SSL certificates (which I believe is easy with requests).

Already done. 

    conda config --set ssl_verify PATH_TO_CERT_BUNDLE
