### ISSUE TITLE
4.1.* post-link fails on 32b Windows py3.5 from conda-forge

### ISSUE THREAD

**Issue by bollwyvl** [conda/conda#2727]
When trying on appveyor to build and minimally test (via `imports`) a [conda-forge feedstock](https://github.com/conda-forge/nb_conda_kernels-feedstock/pull/7#issuecomment-226194960) that has a post-link script (i know, i know, [strongly discouraged](http://conda.pydata.org/docs/building/build-scripts.html)), i am getting `DLL load failed: The specified module could not be found` for the package i just installed.

Here are the [work/builds](https://github.com/conda-forge/nb_conda_kernels-feedstock/pull/7#issuecomment-226194960).

I am seeing the following conditions:

```batch
REM no condarc!
conda clean -y --all
conda install -f "conda>=4.1.0" conda-build
conda build recipe -c conda-forge
```

I see:
```
C:\projects\nb-conda-kernels-feedstock>"C:\conda\envs\_test\python.exe" -m nb_conda_kernels.install --enable --prefix="C:\conda\envs\_test" 
C:\conda\envs\_test\python.exe: Error while finding spec for 'nb_conda_kernels.install' (<class 'ImportError'>: DLL load failed: The specified module could not be found.)
Error: post-link failed for: local::nb_conda_kernels-1.0.3-py35_0
```

If I repeat this with various bits twiddled (after much `conda clean`ing), here are my results:

| conda | -c conda-forge | result |
|:-----:|:--------------:|:------:|
| 4.0.8 | no             | win    |
| 4.0.8 | yes            | win    |
| 4.1.0 | yes            | fail   |
| 4.1.1 | yes            | fail   |
| 4.1.1 | no             | win    |
| 4.1.0 | no             | win    |

Here's the last [good build](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.3089/job/7nwn9e8we4yiqpoh#L609) of the recipe (which allowed it to become a feedstock). It uses `defaults` [python 3.5.1-4](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.3089/job/7nwn9e8we4yiqpoh#L609).

Here is an [example fail](https://ci.appveyor.com/project/conda-forge/nb-conda-kernels-feedstock/build/1.0.15/job/n270ktxq2w0lke68#L575) from 4.1.0. It uses python 3.5.1-0 from conda-forge.

Any thoughts on this? Since, much as I would like to, I cannot remove post-link scripts, the ways forward I see are:
- hack my conda-forge stuff to:
  - use 4.0.8 (I see there is 4.0.9 as well, haven't checked it out yet)
    - boo: people will be getting the 4.1 line pretty automatically, soon
  - prefer `defaults` by adding explicitly in .condarc (or wherever that goes on windows)
   - boo: kind of the idea of conda-forge

However, I really can't tell where the issue lies... certainly a large argument against post-link scripts!

**Comment by kalefranz** [comment]
Could be something in conda-build too.  CC @msarahan

**Comment by bollwyvl** [comment]
@kalefranz good point. i can expand the matrix to see if that has an impact... there is no spoon.

**Comment by msarahan** [comment]
I think this is a subtlety of channel priority.  You are getting Python from conda-forge:
https://ci.appveyor.com/project/conda-forge/nb-conda-kernels-feedstock/build/1.0.14/job/olrwesvd2sy34en8#L575

but vs2015-runtime from defaults: https://ci.appveyor.com/project/conda-forge/nb-conda-kernels-feedstock/build/1.0.14/job/olrwesvd2sy34en8#L582

This is important, because AppVeyor might be on a different VS update version than we last updated vs2015 runtime with.

VS 2015 update 2 (from my local PC, supposedly matches AppVeyor): 14.00.23918.0
vs2015_runtime in defaults: 14.00.23026.0

I will work with Ilan to get an update to defaults.  We also need to get conda-forge building these packages, so that what conda-forge ships will match the appveyor build environment.

**Comment by bollwyvl** [comment]
Ah, the runtimes! Always the runtimes. So is there any approach to pin this that won't break immediately?

**Comment by msarahan** [comment]
Order your channels so that default is preferred. I hope that might work.

**Comment by kalefranz** [comment]
@bollwyvl ok to close this ticket at this point?  We've got per-package channel pinning coming soon now that channel priority is done.

**Comment by bollwyvl** [comment]
Yep, I can deal with that for now!
