### ISSUE TITLE
conda config --set show_channel_urls yes doesn't work anymore

### ISSUE THREAD

**Issue by janschulz** [conda/conda#2732]
This is happening since the latest conda update:

```bat
λ conda config --set show_channel_urls yes
Error: Key: show_channel_urls; yes is not a YAML boolean.
```

It happens with both conda 4.1.1 (local windows py 3.5) and 4.1.0 (appveyor, https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.1774) and it worked with 4.0.8 (https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.1765/job/bkldg98f8p087xmf)

**Comment by kalefranz** [comment]
This one is CC @mcg1969

**Comment by mcg1969** [comment]
I didn't mess with the section of code. I don't mind fixing it, don't get me wrong, but I am guessing that this is a difference between our old YAML library and our new one

**Comment by mcg1969** [comment]
Try using true/false instead of yes/no... @msarahan?

**Comment by kalefranz** [comment]
Ahhhh, interesting.  I thought I had tested for that.  But we can change
the ruamel_yaml version back to using yaml 1.1 (if it isn't already), and
then yes/no should work for yaml booleans.

On Thu, Jun 16, 2016 at 5:33 PM, Michael C. Grant <notifications@github.com>
wrote:

> Try using true/false instead of yes/no... @msarahan
> <https://github.com/msarahan>?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda/conda/issues/2732#issuecomment-226633230>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABWks12m0vAh-7R3sO7oVkpihlF1YwIhks5qMc8tgaJpZM4I33Ze>
> .
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by mcg1969** [comment]
I think the ship is sailed on the new library. I think we have to work around it

**Comment by mcg1969** [comment]
Looks like YAML 1.2 drops Yes/No and On/Off support: http://yaml.readthedocs.io/en/latest/pyyaml.html

**Comment by mcg1969** [comment]
Good news, we can fix

**Comment by mcg1969** [comment]
Changing `version="1.2"` to `version="1.1"` on line 298 of `utils.py` restores this behavior. I'm concerned we may be breaking other things though by doing this, so my inclination is to create a `yaml_bool` function to wrap around the output of `yaml.load` in cases like this.

**Comment by mcg1969** [comment]
Even better: drop the use of `yaml.load` to parse the boolean strings in `cli/main_config.py` in the first place.

**Comment by kalefranz** [comment]
@mcg1969 I don't think I have any issues at all setting the yaml version to `1.1`.  @msarahan any thoughts?

**Comment by mcg1969** [comment]
Well, keep in mind, this code concerns itself with the `config` command line, _not_ the reading of the `.condarc` files. I have no problem with the idea of staying at YAML 1.2 for the file itself, but being more liberal on the command line. We've set a precedent of accepting "yes" on the command line, we should honor that.

**Comment by mcg1969** [comment]
So then the question is: why is YAML even involved here? Because the code chose to use `yaml.load()` to parse the command-line strings! I see no reason to do that _anyway_.
