### ISSUE TITLE
conda env update: install() got an unexpected keyword argument 'prune'

### ISSUE THREAD

**Issue by rschroll** [conda/conda#2733]
I'm trying to update a root conda environment from a environment.yml file, and I get a traceback with this error.  Here's the full traceback:

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 118, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
TypeError: install() got an unexpected keyword argument 'prune'
```
Here's information on the install:
```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.1
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /opt/conda  (writable)
  default environment : /opt/conda
     envs directories : /opt/conda/envs
        package cache : /opt/conda/pkgs
         channel URLs : https://conda.anaconda.org/spacy/linux-64/
                        https://conda.anaconda.org/spacy/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vagrant/.condarc
    is foreign system : False
```

I have been messing around with the install in some potentially stupid ways, so it may be that I've screwed something up.  But this should be a new install of conda, so I don't *think* this is the problem.

**Comment by kalefranz** [comment]
@mcg1969 Do we just need to remove this argument from the conda-env cli?

On Thu, Jun 16, 2016 at 5:49 PM, Robert Schroll <notifications@github.com>
wrote:

> I'm trying to update a root conda environment from a environment.yml file,
> and I get a traceback with this error. Here's the full traceback:
>
> Traceback (most recent call last):
>   File "/opt/conda/bin/conda-env", line 6, in <module>
>     sys.exit(conda_env.cli.main.main())
>   File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
>     return args_func(args, parser)
>   File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
>     args.func(args, p)
>   File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 118, in execute
>     installer.install(prefix, specs, args, env, prune=args.prune)
> TypeError: install() got an unexpected keyword argument 'prune'
>
> Here's information on the install:
>
> $ conda info
> Current conda install:
>
>              platform : linux-64
>         conda version : 4.1.1
>   conda-build version : not installed
>        python version : 2.7.11.final.0
>      requests version : 2.10.0
>      root environment : /opt/conda  (writable)
>   default environment : /opt/conda
>      envs directories : /opt/conda/envs
>         package cache : /opt/conda/pkgs
>          channel URLs : https://conda.anaconda.org/spacy/linux-64/
>                         https://conda.anaconda.org/spacy/noarch/
>                         https://repo.continuum.io/pkgs/free/linux-64/
>                         https://repo.continuum.io/pkgs/free/noarch/
>                         https://repo.continuum.io/pkgs/pro/linux-64/
>                         https://repo.continuum.io/pkgs/pro/noarch/
>           config file : /home/vagrant/.condarc
>     is foreign system : False
>
> I have been messing around with the install in some potentially stupid
> ways, so it may be that I've screwed something up. But this should be a new
> install of conda, so I don't *think* this is the problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda/conda/issues/2733>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABWks1Yowru51Ymy6CdzN_BS8s1vI99dks5qMdLlgaJpZM4I34oL>
> .
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by mcg1969** [comment]
I have no experience with this section of the code, as a developer or user. I am reluctant to remove anything, but I don't know what was supposed to happen here.

**Comment by kalefranz** [comment]
Yeah @mcg1969 I thought the install function here was imported from conda. Definitely not you.

**Comment by kalefranz** [comment]
Fixed in https://github.com/conda/conda-env/pull/246

**Comment by rschroll** [comment]
Thanks for pointing me to the solution!
