### ISSUE TITLE
conda doesn't update an updatable package?

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#2735]
With conda 4.1.1 I'm observing the below behaviour:
```
λ conda update --all
<SNIP>
The following packages will be DOWNGRADED:

    dynd-python:       0.7.2-py35_1233        dynd/channel/dev       --> 0.7.2-py35_0
    numba:             0.27.0.dev-np110py35_6 numba                  --> 0.26.0-np110py35_0
    sphinx:            1.4.1-py35_0                                  --> 1.3.4-py35_0         dhirschfeld
```
Why does an upgrade downgrade packages? If a new package had a hard dep on an earlier package, fair enough, but both the newer numba and newer sphinx should also satisfy constraints so shouldn't be touched.

Even though I haven't included the numba channel conda should see that a newer version is already installed than what it can see in the defaults so should just leave it alone if it also satisfies all constraints.

Below I show that conda refuses to update sphinx even though it will happily do so if I explicitly specify the version which implies that the newer version must also satisfy the constraints so should have been chosen when the original update was requested
```
λ conda update sphinx
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................
Solving package specifications .............

# All requested packages already installed.
# packages in environment at C:\Python:
#
sphinx                    1.3.4                    py35_0    dhirschfeld

λ conda install sphinx=1.4.1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................
Solving package specifications .............

Package plan for installation in environment C:\Python:

The following packages will be UPDATED:

    sphinx: 1.3.4-py35_0 dhirschfeld --> 1.4.1-py35_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

**Comment by kalefranz** [comment]
I suspect this is because of channel ordering, which now very much matters.  We have a patch that didn't quite make it in 4.1.1 to provide better hints. 4.1.2 will be out tomorrow or the next day.

**Comment by dhirschfeld** [comment]
My guess is there's something fishy going on with channel priorities and that there's inconsistent behaviour between a "normal" update and `update --all`

```
λ conda update sphinx
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................
# All requested packages already installed.
# packages in environment at C:\Python:
#
sphinx                    1.4.1                    py35_0
C:\dev\code
λ conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................
Solving package specifications .............

Package plan for installation in environment C:\Python:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mistune-0.7.2              |           py35_0         113 KB

The following packages will be UPDATED:

    mistune: 0.7.1-py35_0                 --> 0.7.2-py35_0

The following packages will be DOWNGRADED:

    numba:   0.27.0.dev-np110py35_6 numba --> 0.26.0-np110py35_0
    sphinx:  1.4.1-py35_0                 --> 1.3.4-py35_0       dhirschfeld

Proceed ([y]/n)?
```

**Comment by dhirschfeld** [comment]
Ha, beat me to it! I still think there's an issue to be resolved when `update` and `update --all` have inconsistent behaviour.

**Comment by dhirschfeld** [comment]
Specifically, I don't think an update should downgrade my sphinx even if my channel has higher priority.

**Comment by kalefranz** [comment]
VERY soon I am going to work on better pinning of packages to specific channels.  Probably by default the channel the package was initially installed from, or maybe only pinning if a channel is specified with the package.  Regardless is something we need to address soon now after releasing channel priority.

**Comment by kalefranz** [comment]
The `update` vs `update --all` problem appears to be similar to what's described and I'm trying to address in #2779.

**Comment by kalefranz** [comment]
Closing, and tracking with #2779.
