### ISSUE TITLE
conda -h spits out a stack trace for one of the "other commands"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2745]
Conda 4.1.1, executed `conda -h`, got (in the "Other Commands" section of the output):

```
    index        Update package index metadata files in given directories.
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/bin/conda-inspect", line 3, in <module>
    from conda_build.main_inspect import main
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_build/main_inspect.py", line 23, in <module>
    from conda.cli.install import check_install
ImportError: cannot import name check_install
failed: /Users/ijstokes/anaconda/bin/conda-inspect --help
```

**Comment by kalefranz** [comment]
The `check_install` function moved to conda-build. I think there's a new release of conda-build that fixes that.

**Comment by kambysese** [comment]
It's like wackamole 
conda 4.1.11 as conda --help does the same:

> Traceback (most recent call last):
>   File "/Users/../anaconda/bin/conda-inspect", line 3, in <module>
>     from conda_build.main_inspect import main
>   File "/Users/.../anaconda/lib/python2.7/site-packages/conda_build/main_inspect.py", line 22, in <module>
>     from conda.cli.install import check_install
> ImportError: cannot import name check_install
> failed: /Users/.../anaconda/bin/conda-inspect --help
>     metapackage  Tool for building conda metapackages.  A metapackage is a package with no
>                  files, only metadata.  They are typically used to collect several packages
>                  together into a single package via dependencies.
>     pipbuild     Tool for building conda packages using pip install. NOTE: this command is
>                  experimental.  The recommended way to build conda packages from packages on
>                  PyPI is using conda skeleton pypi and conda build.
>                          
> Traceback (most recent call last):
>   File "/Users/.../anaconda/bin/conda-server", line 6, in <module>
>     sys.exit(main())
>   File "/Users/.../anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
>     description=__doc__, version=version)
>   File "/Users/.../anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 60, in binstar_main
>     add_subparser_modules(parser, sub_command_module)
>   File "/Users/.../anaconda/lib/python2.7/site-packages/clyent/__init__.py", line 115, in add_subparser_modules
>     for command_module in get_sub_commands(module):
>   File "/Users/.../anaconda/lib/python2.7/site-packages/clyent/__init__.py", line 105, in get_sub_commands
>     this_module = __import__(module.__package__ or module.__name__, fromlist=names)
>   File "/Users/.../anaconda/lib/python2.7/site-packages/binstar_client/commands/download.py", line 14, in <module>
>     from binstar_client.utils.notebook import Downloader, parse, has_environment
> ImportError: cannot import name has_environment
> failed: /Users/.../anaconda/bin/conda-server --help
>     sign         Tool for signing conda packages.  Signatures will be written alongside the
>                  files as FILE.sig.
>     skeleton     Generates a boilerplate/skeleton recipe, which you can then edit to create a
>                  full recipe. Some simple skeleton recipes may not even need edits.
>
