### ISSUE TITLE
Give more control over activated prompt

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2747]
From #2744 

We should add code to the prompt setting logic to let people customize this more with condarc. Similar to `config.changeps1`, but giving even more control.

---

I've got to say I'm not fond of the double either. Or the extra added space.  Prompts should be as short as possible for the screen real estate, and we've added three extra characters that probably aren't necessary.

I _would_ like to disambiguate from virtualenv, because someday conda envs and virtualenv **will** play nice together.

How about angle brackets?  `<ana40py35>ijstokes@petawawa:~%`

**Comment by alanwilter** [comment]
Hi, just to add something else, I found this:
http://conda.continuum.narkive.com/VBicWhga/disable-modification-of-ps1-with-activate-deactivate

`> conda config --set changeps1 no
`

And then, ideally, an oh-my-zsh plugin (like git, screen etc) to handle conda envs. I really like my zshell PS1 giving extra info, my, e.g., shows:

```bash
┌─(/tmp)──────────────────────────(awilter@ebi-005:pts/3)─┐
└─(18:44:06)──>                             ──(Fri,Jun17)─┘
```
and when I am at a git branch:
```bash
┌─(~/Dropbox/uniparc)─────────────────────────────────────────────────────(alan@demonia:s001)─┐
└─(18:49:26 on master)──>                                                       ──(Fri,Jun17)─┘

```

Right now,  when I go to a conda env, my prompt change to:
```bash
(py27)┌─(/tmp)──────────────────────────────────────────────────────────────(awilter@ebi-005:pts
/3)─┐
└─(18:53:14)──>                                                                 ──(Fri,Jun17)─┘
```

A bit messed up, but still informative.
I use oh-my-zsh with `ZSH_THEME="jonathan"` and `plugins=(git osx extract screen)`.

**Comment by njalerikson** [comment]
This would be best accomplished by making the call `conda ..changeps1` return the actual prompt prefix/suffix based on a format defined in the user's `.condarc`. Currently `conda ..changeps1

**Comment by kalefranz** [comment]
Probably best to get #3175 into 4.3, and then implement this in 4.4.
