### ISSUE TITLE
'source activate -h' reports weird help string

### ISSUE THREAD

**Issue by pzwang** [conda/conda#276]
Same thing goes for 'source activate --help':

```
(ipy1.0)pwang@hyperion [~]$ source activate -h
Usage: source deactivate

removes the 'bin' directory of the environment activated with 'source
activate' from PATH.
(ipy1.0)pwang@hyperion [~]$ source activate --help
Usage: source deactivate

removes the 'bin' directory of the environment activated with 'source
activate' from PATH.
```

I looked over the activate script and the only thing I can guess is that somehow the 'conda ..deactivate' command is being called with the "-h" parameter?

**Comment by elviseno** [comment]
hi @asmeurer, I recently installed VW 4.3.2 to make venv with non-default python and the same issue still exist when using workon to activate the environment. Is the bug fix in this version already? Or at least does this affect the usage? Thank you.

**Comment by asmeurer** [comment]
I don't know what VW stands for, but the fix has been there for over a year.
