### ISSUE TITLE
PREFIX environment variable for activated env

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2764]
Consider setting `PREFIX` and/or `CONDA_PREFIX` as an environment variable for activated envs.

CC @msarahan

**Comment by insertinterestingnamehere** [comment]
This is a really great idea. It'd help a lot with managing rpaths when developing against libraries in a conda environment. I'd vote for `CONDA_PREFIX` rather than just `PREFIX` though. It's less invasive.
It may be worth bringing in a few other environment variables from the list at http://conda.pydata.org/docs/building/environment-vars.html. This could help simplify things like finding the R and Python executables, or finding Python's site packages directory.

**Comment by msarahan** [comment]
Looks fine to me, and +1 on Ian's suggestion here.

**Comment by kalefranz** [comment]
Related work: https://github.com/conda/conda/issues/2691

**Comment by mwiebe** [comment]
+1 from me, it looks like `CONDA_DEFAULT_ENV` got changed away from this on Windows? What's the current recommended way to access the current activated environment prefix cross-platform?

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/2796

`CONDA_ENV_PATH`

Except don't settle on it yet.  I might add in `CONDA_PREFIX` too.  I think it's easier to remember.  I guess maybe that's just me though.

**Comment by mwiebe** [comment]
Looks to me like `CONDA_DEFAULT_ENV` got changed without `CONDA_ENV_PATH being added, might be considered a functionaliy regression bug:

```
C:\Dev\SequoiaAll>activate sequoia_all_msvc2012rel
prepending C:\\Anaconda3\\envs\\sequoia_all_msvc2012rel and C:\\Anaconda3\\envs\\sequoia_all_msvc2012rel\\Library\\mingw-w64\\bin and C:\\Anaconda3\\envs\\sequoia_all_msvc2012rel\\Library\\usr\\bin and C:\\Anaconda3\\envs\\sequoia_all_msvc2012rel\\Library\\bin and C:\\Anaconda3\\envs\\sequoia_all_msvc2012rel\\Scripts to PATH

(sequoia_all_msvc2012rel) C:\Dev\SequoiaAll>echo %CONDA_DEFAULT_ENV%
sequoia_all_msvc2012rel

(sequoia_all_msvc2012rel) C:\Dev\SequoiaAll>echo %CONDA_ENV_PATH%
%CONDA_ENV_PATH%
```

**Comment by mwiebe** [comment]
The only place the full environment prefix is available is in PATH:

```
(sequoia_all_msvc2012rel) C:\Dev\SequoiaAll>set | grep sequoia_all
CONDA_DEFAULT_ENV=sequoia_all_msvc2012rel
Path=C:\Anaconda3\envs\sequoia_all_msvc2012rel;C:\Anaconda3\envs\sequoia_all_msvc2012rel\Library\mingw-w64\bin;C:\Anaconda3\envs\sequoia_all_msvc2012rel\Library\usr\bin;C:\Anaconda3\envs\sequoia_all_msvc2012rel\Library\bin;C:\Anaconda3\envs\sequoia_all_msvc2012rel\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\TortoiseHg\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Gow\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\CMake\bin;C:\Program Files\Git\cmd;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Ruby22-x64\bin;C:\Users\mwiebe\bin;C:\Program Files\Docker Toolbox;C:\Users\mwiebe\AppData\Roaming\MiKTeX\2.9\miktex\bin\x64\;C:\Program Files\LAStools\bin
PROMPT=(sequoia_all_msvc2012rel) $P$G
```

**Comment by msarahan** [comment]
Might be a bad merge.  In any case, there was a bug that it wouldn't show up anyway, because it was defined only in a setlocal region.  I'll submit a PR.

**Comment by insertinterestingnamehere** [comment]
FWIW, getting an environment's prefix is actually doable via a conda package right now. You can make a package with nothing but an activate and deactivate script that sets the needed environment variables correctly. I can throw together an example if there's interest.

**Comment by mGalarnyk** [comment]
@insertinterestingnamehere there is plenty of interest here!

**Comment by msarahan** [comment]
@mGalarnyk the $CONDA_PREFIX variable is the full path to the active env.  I don't see that this is documented, unfortunately, but I think it does what you need.  Have you tried that?
