### ISSUE TITLE
source activate without arguments breaks source activate/deactivate commands

### ISSUE THREAD

**Issue by insertinterestingnamehere** [conda/conda#2765]
Running `source activate` without any further arguments on Linux with the latest release makes it so that further activate/deactivate commands do not work. For example:
```
ihenriksen@ubuntu:~$ source activate
prepending /home/ihenriksen/miniconda2/envs/bin to PATH
ihenriksen@ubuntu:~$ source activate py27
bash: activate: No such file or directory
ihenriksen@ubuntu:~$ source deactivate
bash: deactivate: No such file or directory
ihenriksen@ubuntu:~$
```
This isn't at all a blocking issue for me, but it seems like something worth revisiting when we can.

**Comment by msarahan** [comment]
Pretty sure it is getting an empty string, then considering that a valid env, somehow.  ugh.  Thanks for reporting.
