### ISSUE TITLE
Cannot conda a new environment

### ISSUE THREAD

**Issue by NoraGithub** [conda/conda#2768]
I was using pyenv to manager my environment, and  I needed the anaconda-1.9.2 to do the development. However, while creating a copy of it, I got the trouble as below. 

>An unexpected error has occurred, please consider sending the             |  66%
>following traceback to the conda GitHub issue tracker at:

>    https://github.com/conda/conda/issues

>Include the output of the command 'conda info' in your report.
>

>Traceback (most recent call last):
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/bin/conda", line 5, in <module>
>    sys.exit(main())
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
>    args.func(args, p)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
>    install.install(args, parser, 'create')
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
>    plan.execute_actions(actions, index, verbose=not args.quiet)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
>    execute_plan(plan, index, verbose)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
>    link(prefix, arg)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/plan.py", line 357, in link
>    install.link(pkgs_dir, prefix, dist, lt)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/install.py", line 438, in link
>    update_prefix(join(prefix, f), prefix)
>  File "/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
>    with open(path, 'rb') as fi:
>IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text lib/libsqlite3.la'

Here's my **conda info**
>Current conda install:
>
> platform : osx-64
> conda version : 3.4.1
> python version : 2.7.6.final.0
> root environment : /Users/NoraChan/.pyenv/versions/anaconda-1.9.2  (writable)
> default environment : /Users/NoraChan/.pyenv/versions/anaconda-1.9.2
> envs directories : /Users/NoraChan/.pyenv/versions/anaconda-1.9.2/envs
> package cache : /Users/NoraChan/.pyenv/versions/anaconda-1.9.2/pkgs
>channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
> http://repo.continuum.io/pkgs/pro/osx-64/
>config file : None
> is foreign system : False

Thanks

**Comment by NoraGithub** [comment]
https://github.com/conda/conda/issues/2586

**Comment by NoraGithub** [comment]
I read some code and found that separately,  I executed this can cause the same issue:
>conda create --name test --yes python

Would you please help me with it?
Plus, more information if it would help:
>Noras-MacBook-Air:~ NoraChan$ which python
>/Users/NoraChan/.pyenv/shims/python
>Noras-MacBook-Air:~ NoraChan$ pyenv which python
>/Users/NoraChan/.pyenv/versions/anaconda-1.9.2/bin/python
>Noras-MacBook-Air:~ NoraChan$ $PATH
>-bash: /usr/local/Cellar/pyenv-virtualenv/20160315/shims:/Users/NoraChan/.pyenv/shims:/usr/local/opt/nvm/versions/node/v5.0.0/bin:/Users/NoraChan/Library/Enthought/Canopy_64bit/User/bin:/Users/NoraChan/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin: No such file or directory

**Comment by kalefranz** [comment]
Conda 3.4.1 and Anaconda 1.9.2 are very old.  I'm also unsure how pyenv interacts with conda; I guess it's completely untested and unspecified.

I'd recommend starting from a fresh Anaconda install rather than trying to update and fix your current setup if that's possible.

https://www.continuum.io/downloads
