### ISSUE TITLE
conda update conda doesn't get latest conda-env

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2771]
It's annoying we even have this problem, but...

    root@default:~ # conda update conda
    Fetching package metadata: ......
    .Solving package specifications: .........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        conda-env-2.5.0            |           py27_0          28 KB
        conda-4.1.2                |           py27_0         198 KB
        ------------------------------------------------------------
                                               Total:         226 KB

    The following NEW packages will be INSTALLED:

        ruamel_yaml: 0.11.7-py27_0

    The following packages will be UPDATED:

        conda:       4.0.5-py27_0 --> 4.1.2-py27_0
        conda-env:   2.4.5-py27_0 --> 2.5.0-py27_0

    Proceed ([y]/n)? y

    Fetching packages ...
    conda-env-2.5. 100% |#########################################################################################| Time: 0:00:00 587.12 kB/s
    conda-4.1.2-py 100% |#########################################################################################| Time: 0:00:00 994.90 kB/s
    Extracting packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    root@default:~ # conda update conda-env
    Fetching package metadata .........
    Solving package specifications: ..........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        conda-env-2.5.1            |           py27_0          26 KB

    The following packages will be UPDATED:

        conda-env: 2.5.0-py27_0 --> 2.5.1-py27_0

    Proceed ([y]/n)? y

    Fetching packages ...
    conda-env-2.5. 100% |#########################################################################################| Time: 0:00:00 569.65 kB/s
    Extracting packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%

**Comment by mcg1969** [comment]
No, this is not a bug. The dependencies did not require conda-env to be updated, so it didn't.
