### ISSUE TITLE
default to channel-priority = False

### ISSUE THREAD

**Issue by janschulz** [conda/conda#2782]
The current (new) default changes the old behaviour of conda which means that a lot of users will be surprised when they update to the new conda versions (I certainly was :-/).

IMO it's also a more sane behaviour: currently the priorities mean that newer versions gets downgraded on updates which is not what I want when I use both conda-forge and defaults. 

Its also potentially harmfull as new new channels are added as the highest priority and so this channel can bring back old packages: with the old conda versions and a user adding a channel for "just one newer package", old leftover packages are not used -> New channels were only harmful when the channel owner explicitly would add a harmful package with a newer version number but now a not updated test package can happen to be installed.

It would also be nice if the help would tell one how to influence channel priority.

The current option is also advertised as beta and subject to change which is IMO an argument to not make it active on default.

```
 --channel-priority, --channel-pri, --chan-pri
                        Channel priority takes precedence over packaage
                        version (default: True). Note: This feature is in beta
                        and may change in a future release.
```

[`packaage` -> `package`?]

**Comment by kalefranz** [comment]
Hi @janschulz,

We hear and understand your frustration. The 4.1.x implementation of channel priority is only the first step. We **will** continue to both refine and add to these capabilities. More intelligent "stickiness" of packages to their original channels is part of the plan. 

There is also much more coming with the aim of improving all of conda features, stability, and communication. Both process improvements along with code improvements. 

For example, conda 4.2 will be released initially under a new *conda canary* program (which I hope you'll opt in to participating in).

Conda definitely has a huge backlog of open issues still, but in the last couple months we've dramatically improved on our responsiveness to open pull requests. Especially for things like better documentation both in command-line help and online documentation, contributed pull requests are very much appreciated. 

As the conda community and ecosystem grows (e.g. conda-forge awesomeness, Intel distribution, etc), we're working hard to make sure users get what they need, want, and expect. We know we're not done yet and have further to go.

Definitely appreciate your feedback and input.

**Comment by kalefranz** [comment]
Going to go ahead and close this issue. I think we're capturing relevant discussion in #2779.
