### ISSUE TITLE
IPython terminal wrapping problems

### ISSUE THREAD

**Issue by atedstone** [conda/conda#2792]
When using Python 3.x -based conda environments I am experiencing problems with wrapping of long commands in the IPython terminal:

![screenshot_2016-06-21_15-58-08](https://cloud.githubusercontent.com/assets/2922144/16234306/fba8e056-37c8-11e6-8945-e6786693c6f1.png)

In this case I was trying to scroll back left along a previous command in order to edit it. The act of scrolling along the line triggered this observed behaviour where the line replicated several times vertically, garbling the line contents as it did so. As evidenced in the outputs I had to Ctrl-C to stop the vertical scrolling.

This happens with every command that I try to edit which exceeds the width of the window.

This behaviour does not occur when I am using my system's IPython with Python 2.7 (i.e. no conda environment active). 

I have previously tried opening a new terminal with a 'clean' .bashrc and adding conda to the PATH myself before activating the environment and this also causes problems so I don't think it's a PS1-related problem, at least not one that I've brought upon myself with a custom .bashrc.

Conda specs for environment:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
armadillo=6.200.2=2
backports=1.0=py35_0
backports.shutil_get_terminal_size=1.0.0=py35_0
basemap=1.0.8.dev0=np110py35_1
bokeh=0.11.1=py35_0
bottleneck=1.0.0=np110py35_0
ca-certificates=2016.2.28=0
cartopy=0.14.2=np110py35_0
chest=0.2.3=py35_0
click=6.6=py35_0
click-plugins=1.0.3=py35_0
cligj=0.2.0=py35_0
cloudpickle=0.2.1=py35_0
curl=7.45.0=0
cycler=0.10.0=py35_0
dask=0.9.0=py35_0
decorator=4.0.9=py35_0
descartes=1.0.2=py35_0
entrypoints=0.2.1=py35_0
eofs=1.1.0=py35_0
fiona=1.6.3=np110py35_5
fontconfig=2.11.1=5
freetype=2.5.5=0
gdal=1.11.4=py35_10
geopandas=0.2.0.dev0=py35_0
geopy=1.10.0=py35_0
geos=3.4.2=0
get_terminal_size=1.0.0=py35_0
hdf4=4.2.11=0
hdf5=1.8.15.1=2
heapdict=1.0.0=py35_0
ipykernel=4.3.1=py35_0
ipython=4.2.0=py35_1
ipython_genutils=0.1.0=py35_0
ipywidgets=5.1.5=py35_0
jbig=2.1=0
jinja2=2.8=py35_0
jpeg=8d=0
jsonschema=2.5.1=py35_0
jupyter=1.0.0=py35_3
jupyter_client=4.2.2=py35_0
jupyter_console=4.1.1=py35_0
jupyter_core=4.1.0=py35_0
kealib=1.4.5=10
krb5=1.13.2=0
libgdal=1.11.2=2
libgfortran=3.0.0=1
libnetcdf=4.3.3.1=3
libpng=1.6.17=0
libsodium=1.0.10=0
libspatialindex=1.8.5=1
libtiff=4.0.6=1
libxml2=2.9.2=0
libxslt=1.1.28=0
locket=0.2.0=py35_0
lxml=3.6.0=py35_0
markupsafe=0.23=py35_0
matplotlib=1.5.1=np110py35_0
mistune=0.7.2=py35_0
mkl=11.3.3=0
mock=2.0.0=py35_0
munch=2.0.4=py35_0
nbconvert=4.2.0=py35_0
nbformat=4.0.1=py35_0
ncurses=5.9=7
netcdf4=1.2.2=np110py35_0
nose=1.3.7=py35_0
notebook=4.2.1=py35_0
numpy=1.10.4=py35_2
openjpeg=2.1.0=0
openssl=1.0.2h=0
owslib=0.11.0=py35_0
pandas=0.18.1=np110py35_0
partd=0.3.3=py35_0
path.py=8.2.1=py35_0
patsy=0.4.1=py35_0
pbr=1.8.0=py35_0
pexpect=4.0.1=py35_0
pickleshare=0.5=py35_0
pillow=3.2.0=py35_0
pip=8.1.1=py35_1
proj.4=4.9.1=0
proj4=4.9.1=0
psycopg2=2.6.1=py35_1
ptyprocess=0.5=py35_0
pyepsg=0.2.0=py35_1
pygments=2.1.3=py35_0
pyparsing=2.1.1=py35_0
pyproj=1.9.4=py35_1
pyqt=4.11.4=py35_1
pysal=1.11.1=py35_0
pyshp=1.2.3=py35_0
python=3.5.1=0
python-dateutil=2.5.3=py35_0
python-simplegeneric=0.8.1=py35_0
pytz=2016.4=py35_0
pyyaml=3.11=py35_1
pyzmq=15.2.0=py35_1
qt=4.8.7=1
qtconsole=4.2.1=py35_0
readline=6.2=2
requests=2.10.0=py35_0
rtree=0.8.2=py35_2
scipy=0.17.1=np110py35_0
seaborn=0.7.0=py35_0
setuptools=20.7.0=py35_0
shapely=1.5.15=np110py35_0
simplegeneric=0.8.1=py35_0
sip=4.16.9=py35_0
six=1.10.0=py35_0
sqlalchemy=1.0.13=py35_0
sqlite=3.9.2=0
statsmodels=0.6.1=np110py35_0
terminado=0.6=py35_0
tk=8.5.18=0
toolz=0.7.4=py35_0
tornado=4.3=py35_0
traitlets=4.2.1=py35_0
wheel=0.29.0=py35_0
widgetsnbextension=1.2.3=py35_1
xarray=0.7.2=py35_0
xerces-c=3.1.2=0
xz=5.0.5=1
yaml=0.1.6=0
zeromq=4.1.4=3
zlib=1.2.8=0
```

Thanks for any insight here.

**Comment by kalefranz** [comment]
Sorry @atedstone, but this really has nothing to do with conda or conda-env.  The problem you are experiencing and need support with could be in any number of places... The difference between python2 and python3, your terminal, ipython itself, etc etc.  But it most assuredly has nothing to do with the conda code base itself.  Consider trying to better isolate the cause of your issue, and then file a ticket with that more isolated code base.  You can also consider posing a question on StackOverflow.
