### ISSUE TITLE
error when running debug

### ISSUE THREAD

**Issue by arothste24** [conda/conda#2801]
I recieved this error today when running debug for conda:

Traceback (most recent call last):
  File "/Users/andyrothstein/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/andyrothstein/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/andyrothstein/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
AttributeError: 'Namespace' object has no attribute 'func'

Here is my conda info:

conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : 0+unknown
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/andyrothstein/anaconda  (writable)
  default environment : /Users/andyrothstein/anaconda
     envs directories : /Users/andyrothstein/anaconda/envs
        package cache : /Users/andyrothstein/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/andyrothstein/.condarc
    is foreign system : False

Any ideas? Much appreciated!

**Comment by kalefranz** [comment]
What command did you run that triggered that behavior?

**Comment by arothste24** [comment]
$ conda --debug

**Comment by mcg1969** [comment]
That's it? No additional commands?
```
0203-mgrant:~ mgrant$ conda --debug
usage: conda [-h] [-V] [--debug] command ...
conda: error: too few arguments
```

**Comment by arothste24** [comment]
I would have expected that I would have gotten the error above as @mcg1969 shows but I get the above traceback when I run it **without** additional commands.  It was a mistake command on my end but I was confused by the output. Again the output with the command as well:

$ conda --debug
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/andyrothstein/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/andyrothstein/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/andyrothstein/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
AttributeError: 'Namespace' object has no attribute 'func'

**Comment by mcg1969** [comment]
Also #2864.

**Comment by kalefranz** [comment]
fixed!
