### ISSUE TITLE
Conda Perf on A-Cloud: reduce volume of repodata JSON being requested per operation

### ISSUE THREAD

**Issue by stephenakearns** [conda/conda#2802]
## Overview
When a user goes to perform a basic operation like install a conda package, the way it's asking for the information to perform the operation is hammering the server.... 

## Example:
* .condarc includes: anaconda, bioconda, r and conda-forge channels
* user goes to install python: `conda install python` (a very basic operation that will pull down python and 4 supporting files - see details below) 
* conda requests repo-data for every package, every file in all channels specified in .condarc
* Based on the way conda asks for the information, A-Cloud has to iterate over 5272 packages, and 100,000 files in those 5000 packages to gather the requested information. (for every anaconda install command - even if the request is fulfilled by repo.continuum.io
* conda's approach - fetch all the metadata for everything before calling teh solver to determine which source package to use for the installation

`conda create -n ENV_NAME python=2.7` results in....

`The following packages will be downloaded:`

    package                    |            build
    ---------------------------|-----------------
    vs2008_runtime-9.00.30729.1|                1         1.2 MB
    python-2.7.11              |                4        23.1 MB
    setuptools-23.0.0          |           py27_0         688 KB
    wheel-0.29.0               |           py27_0         121 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                         |  Total:        26.7 MB

**Comment by stephenakearns** [comment]
related to #2357

**Comment by mcg1969** [comment]
> Based on the way conda asks for the information, A-Cloud has to iterate over 5272 packages, and 100,000 files in those 5000 packages to gather the requested information. (for every anaconda install command - even if the request is fulfilled by repo.continuum.io

What? How is this the case? All it is doing is asking for `repodata.json.bz2`, once per channel. Why is Anaconda Cloud iterating over all of these packages when this one file is being requested?

For repo.continuum.io in particular, this is a _static file_. There's no way it is iterating over all of the packages in defaults to get this information.

I could definitely see `conda` doing a better job of relying on its internal cache. As far as I can tell, `conda` always asks for a new copy of each channel's `repodata.json.bz2` file with every conda command unless `--use-cache` is specified. We could do a much smaller query of the modification time for the `repodata` file and compare it to the modification time of the local cached copy.

**Comment by mcg1969** [comment]
Why not generate the `repodata.json.bz2` files only when a file in the given channel is updated---possibly with minimum regeneration interval---and offer them up on a CDN along with the packages themselves?

**Comment by mcg1969** [comment]
The conda channel specification is actually well-tuned to be served from an entirely static location. Any dynamic generation we're doing is unnecessary from conda's perspective, although I certainly concede there may be useful reasons to intervene in some sort of dynamic fashion (e.g., analytics collection)

**Comment by mcg1969** [comment]
> user goes to install python: conda install python (a very basic operation that will pull down python and 4 supporting files - see details below)

This is by no means a "very basic operation". After all, when the user types this command, `conda` needs the following information:

- Which versions of python are available?
- What are this packages' dependencies?
- What versions of those packages are available?
- Do those packages have any second-level dependencies?
- If so, which versions of those packages are available?
- etc. etc.

It also needs to incorporate information about the target environment. It is possible, for instance, that some of the versions of Python or its dependencies are incompatible with the current environment, and suitable substitutes must be sought.

I think a full understanding of the task `conda` is required to perform would quickly lead you to agree that the download of the `repodata.json.bz2` files is in fact a rather *efficient* way to communicate the information it needs. 

Again, there's no doubt that improving conda's _caching_ of this repodata would provide a significant benefit. But we simply can't do _without_ that information.

**Comment by kalefranz** [comment]
Immediate piece of information not captured here so far...

The repo.continuum.io web server is set up to send HTTP `304 Not Modified` when repodata is requested but hasn't changed.  Conda is equipped to handle and respect this.

**Comment by teoliphant** [comment]
From what I can see, this is primarily an Anaconda Cloud issue and not a conda issue.    Anaconda Cloud is not intelligent about the way it handles repo-data requests as far as I can tell.
