### ISSUE TITLE
No differentiation between 'local' installtions and 'file://' installation

### ISSUE THREAD

**Issue by jarondl** [conda/conda#2805]
With conda 4.1.2, and packages installed from `file://` channels,
`conda list --explicit` outputs invalid urls:

    file:///data/packages/conda/linux-64pyside-1.2.4-py34_0.tar.bz2

Notice that there is no '/' between `linux-64` and `pyside`.
The reason is this fix:
https://github.com/conda/conda/commit/1b30ba65b004c97957bf383a8dbb07e56d2f5f0e
Which was intended to fix a 'local' installation, but inadvertently handles `file://` as well.
This is related to #2781, which is also the result of this kind of mix-up.

I think the only robust solution is to add metadata to `local` installations.
CC @mcg1969

**Comment by mcg1969** [comment]
Yes, this is a regression, for which I apologize! We'll be working on this today.

**Comment by kalefranz** [comment]
fixed in #2812
