### ISSUE TITLE
offline: True not being honored

### ISSUE THREAD

**Issue by tomashek** [conda/conda#2808]
Having "offline:True" in condarc seems to have no effect any longer. The appearance/behavior is different in 4.1\* than it was in 4.0*.

Previously, online channels would not appear in "conda info" when "offline: True" was specified. In 4.1.2, the online channels appear:

((root)) C:\Users\tmtomash\projects\buildstack>conda info
Current conda install:

```
    platform : win-64
    conda version : 4.1.2
    conda-build version : 1.21.0
    python version : 3.5.1.final.0
    requests version : 2.10.0
    root environment : C:\Users\tmtomash\Miniconda3  (writable)
    default environment : C:\Users\tmtomash\Miniconda3
    envs directories : C:\Users\tmtomash\Miniconda3\envs
    package cache : C:\Users\tmtomash\Miniconda3\pkgs
    channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                    https://repo.continuum.io/pkgs/free/noarch/
                    https://repo.continuum.io/pkgs/pro/win-64/
                    https://repo.continuum.io/pkgs/pro/noarch/
    config file : C:\Users\tmtomash\Miniconda3\.condarc
    is foreign system : False
```

Further, both "conda search" and "conda install" draw data and files from the defaults channel.
This was not the case with 4.0.6.

Verified that custom channels also appear in "conda info", search, and install, so this doesn't only affect "defaults".

Likely related to Issue #2766 

Currently seeing this on Windows.

**Comment by mcg1969** [comment]
I can reproduce this on the Mac _as long as the channel list is empty_. So for instance:
```
offline: True
channels:
  - file:///Users/mgrant/tmp
```
Just gives me the local channels. On the other hand, if the channel list is empty, I get the default channel set even with `offline: True`.

**Comment by tomashek** [comment]
I can reproduce on Linux as well. Same behavior as my original post.

**Comment by mcg1969** [comment]
I just pushed #2813, but note that this only addresses the output of `conda info`, not the other symptoms that `offline: True` is not being honored.

**Comment by tomashek** [comment]
My behavior on Mac doesn't match yours. It acts like my original description of Windows (and Linux).

The only time default channels do not appear is when "defaults" is removed from my condarc list of channels. "offline: True" seems to be ignored.  Here is info from my OSX test using miniconda:

Current conda install:
        
                     platform : osx-64
                conda version : 4.1.2
          conda-build version : 1.19.0
               python version : 3.5.1.final.0
             requests version : 2.10.0
             root environment : /localdisk/tmtomash/miniconda3  (writable)
          default environment : /localdisk/tmtomash/miniconda3
             envs directories : /localdisk/tmtomash/miniconda3/envs
                package cache : /localdisk/tmtomash/miniconda3/pkgs
                 channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                                https://repo.continuum.io/pkgs/free/noarch/
                                https://repo.continuum.io/pkgs/pro/osx-64/
                                https://repo.continuum.io/pkgs/pro/noarch/
                  config file : /nfs/site/home/tmtomash/.condarc
            is foreign system : False

$ conda list

        # packages in environment at /localdisk/tmtomash/miniconda3:
        # 
        conda                     4.1.2                    py35_0    defaults
        conda-build               1.19.0                   py35_0    defaults
        conda-env                 2.5.1                    py35_0    defaults
        jinja2                    2.8                      py35_0    defaults
        markupsafe                0.23                     py35_0    defaults
        openssl                   1.0.2h                        1    defaults
        pip                       7.1.2                    py35_0    defaults
        pycosat                   0.6.1                    py35_1    defaults
        pycrypto                  2.6.1                    py35_0    defaults
        python                    3.5.1                         0    defaults
        pyyaml                    3.11                     py35_4    defaults
        readline                  6.2                           2    defaults
        requests                  2.10.0                   py35_0    defaults
        ruamel_yaml               0.11.7                   py35_0    defaults
        setuptools                20.6.7                   py35_0    defaults
        sqlite                    3.13.0                        0    defaults
        tk                        8.5.18                        0    defaults
        wheel                     0.26.0                   py35_1    defaults
        xz                        5.0.5                         1    defaults
        yaml                      0.1.6                         0    defaults
        zlib                      1.2.8                         3    defaults

**Comment by mcg1969** [comment]
Just to be clear: what I'm seeing on the Mac is that `conda info` does not filter out _any_ of the online channels from the list when `offline: true` is set.
```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.2.dev34+44c9f2a
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/mgrant/miniconda2  (writable)
  default environment : /Users/mgrant/miniconda2
     envs directories : /Users/mgrant/miniconda2/envs
        package cache : /Users/mgrant/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/intel/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/intel/noarch/
          config file : /Users/mgrant/.condarc
    is foreign system : False
```
On the other hand, with my patch, I get this:
```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.2.dev35+8c9cc0e
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/mgrant/miniconda2  (writable)
  default environment : /Users/mgrant/miniconda2
     envs directories : /Users/mgrant/miniconda2/envs
        package cache : /Users/mgrant/miniconda2/pkgs
         channel URLs : 
          config file : /Users/mgrant/.condarc
         offline mode : True
    is foreign system : False
```

**Comment by tomashek** [comment]
@mcg1969 Okay, yes, that looks like what I was seeing with the pre-patch version.

**Comment by mcg1969** [comment]
Alas, the problem is that this isn't affecting install or build functionality :-) Those issues are elsewhere.

**Comment by kalefranz** [comment]
> Further, both "conda search" and "conda install" draw data and files from the defaults channel.
This was not the case with 4.0.6.

@mcg1969 This is the central issue I'm most concerned about, and it still appears to be the case.  If `offline: true` is set, and `conda info` list NO channels, then basic searches and installs should never find any matching packages.

**Comment by mcg1969** [comment]
That's a good point. But what about data in the cache? We could still use cached repodata and packages in solves.

**Comment by kalefranz** [comment]
> But what about data in the cache? We could still use cached repodata and packages in solves.

Oh yes, that's true.  As *long* as the tarballs are still in the cache.  i.e. someone hasn't done `conda clean --all --yes`.

**Comment by kalefranz** [comment]
The integration test I have yet to write will neuter requests, only allowing `file://` urls.

**Comment by tomashek** [comment]
The cache is something I wanted to ask about anyways. Is there a command-line switch or configuration option for disabling the cache? Or is clearing it with "conda clean" the only option?

**Comment by kalefranz** [comment]
> Or is clearing it with "conda clean" the only option?

Right now, just this.  Good idea to add more flexibility here though.

**Comment by kalefranz** [comment]
`offline: True` is now strictly enforced in conda 4.3.  If there are code paths that still aren't honoring that, we fail early so we can identify those remaining paths.
