### ISSUE TITLE
All package versions should include the revision version number on the package?

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#2809]
To put an example with astropy

http://repo.continuum.io/pkgs/free/linux-64/

```
astropy-1.1-np110py27_0.tar.bz2	8.1M	2015-12-11 15:50:36	3b444fa61f0e55d4c7ab67d07719f26d
astropy-1.1-np110py34_0.tar.bz2	8.6M	2015-12-11 15:53:41	87aafeb63ca5ff00d91ed5ab5b232248
astropy-1.1-np110py35_0.tar.bz2	8.4M	2015-12-11 15:56:45	29746f708e111d1af8bd884701b986e0
astropy-1.1.1-np110py27_0.tar.bz2	8.1M	2016-01-11 13:20:52	4c6b7595416aa1ffef47e2a13a855d77
astropy-1.1.1-np110py34_0.tar.bz2	8.6M	2016-01-11 13:24:05	198dd3306503097e52aefe76ff624fdf
astropy-1.1.1-np110py35_0.tar.bz2	8.4M	2016-01-11 13:27:09	3b10c254399e0332e0ad29fc8878e128
astropy-1.1.2-np110py27_0.tar.bz2	8.1M	2016-03-12 21:45:08	d5ad289bd0db6003e8306746f79c515c
astropy-1.1.2-np110py34_0.tar.bz2	8.5M	2016-03-12 21:51:18	004549573ce597bf25c48435fb613350
astropy-1.1.2-np110py35_0.tar.bz2	8.4M	2016-03-12 21:56:08	0454d01bdc78f73dcb6dc684a9f0c53c
astropy-1.1.2-np111py27_0.tar.bz2	8.1M	2016-03-31 17:32:24	79579be1648c62c3515def4a52646c6d
astropy-1.1.2-np111py34_0.tar.bz2	8.5M	2016-04-03 21:02:58	ebc3228c521b0d8ccd87b43d205392b8
astropy-1.1.2-np111py35_0.tar.bz2
```

The 1.1 version of astropy should be tagged as 1.1.0 and not just 1.1. Conda seems to be smart enough to do the right thing when one specifies

`conda install astropy=1.1.0 --dry`

But this seems like magic, cause in reality there is no package named (note the extra .0)
**astropy-1.1.0-np110py34_0.tar.bz2**

# Navigator specific issue

On Navigator when offering the available versions for a package we take it based on the repodata

![image](https://cloud.githubusercontent.com/assets/3627835/16272672/4a99cb94-3864-11e6-9349-e0843b4431fd.png)

And this includes version 0.3, 0.4,.... 1.0, 1.1  (0.2.0 seems to be the exception)

Should not all packages include X.X.X even if it is the first minor release? This would make things consistent and predictable.

If a user selects to install 1.1 version, he will get the latest 1.1.x version, so the user cant install the first minor version (X.X.0) of any package that follows this convention.

**Comment by kalefranz** [comment]
I'm not sure it's safe to assume every package uses semantic versioning, or three elements to version.  I'm sure there are plenty of packages that don't.  Am I wrong?

**Comment by kalefranz** [comment]
Ohhh, I get it.  I think.  If a `1.1.1` exists, conda should display `1.1.0` *with* the last `.0` even if the package itself wasn't created that way.  If a `1.1.1` or other `1.1.X` doesn't exist, then it's fine for conda to use `1.1` here.  Do you agree @goanpeca?

**Comment by goanpeca** [comment]
Hi @kalefranz 

>I think. If a 1.1.1 exists, conda should display 1.1.0 with the last .0 even if the package itself wasn't created that way.

Not sure if this is the best option, cause it is also doing some magic, or assuming things. If we are building those packages and "we know" there is a revision already, should not we strive to use the full version name? 1.1.0? (or at least for packages that seem to follow semantic versioning?)

On Navigator (for now at least) we are using the **repodata.json** directly to gather information, so any "magic" on conda side will still leave the **repodata.json** untouched. We could on navigator check all this, but seems like an unnecessary (maybe error prone) way of handling it.

**Comment by mcg1969** [comment]
Is this really a conda issue at all? conda doesn't really care how the version is formatted in the filename.

**Comment by mcg1969** [comment]
I'm not even convinced this is a conda-build issue. This is about standardizing a process for specifying the version within conda-build.

**Comment by mcg1969** [comment]
> But this seems like magic, cause in reality there is no package named (note the extra .0)

There's no magic. PEP440 says `1.1` and `1.1.0` are equivalent (as is `1.1.0.0`, `1.1.0.0.0`...)

**Comment by goanpeca** [comment]
Hi @mcg1969 

>There's no magic. PEP440 says 1.1 and 1.1.0 are equivalent (as is 1.1.0.0, 1.1.0.0.0...) From the text:

Fair enough, but if that is the case and conda follows PEP440 (which is not necessarily the best idea as that was a Python only spec)

`conda install astropy=1.1` actually installs the latest revision whatever that is (1.1.1, 1.1.2), instead of 1.1.0, so conda doe not equate 1.1 to 1.1.0 as PEP440 says.

**Comment by mcg1969** [comment]
That's intentional. `conda install astropy=1.1` installs any 1.1 version. If you want 1.1.0 specifically, use the pip equality operator: `conda install astropy==1.1`

**Comment by goanpeca** [comment]
Ok, I did not know that, I will change Navigator to use `==` instead of `=`

**Comment by goanpeca** [comment]
>I think people intuitively understand this; that is, conda install python=2.7 is widely understood to install the latest version of Python 2.7.

True, but it does lead to this strange behavior, was not aware I needed `==`, that should fix things on our side

**Comment by goanpeca** [comment]
@mcg1969 thanks for the clarification

**Comment by goanpeca** [comment]
@martindurant FYI, the issues is fixed on Navigator by adding an extra `=` so packages are specified as `<package-name>==<version>`, and this will guarantee the right version is installed.
