### ISSUE TITLE
activating conda environment broken with git bash in Windows 7

### ISSUE THREAD

**Issue by okyere** [conda/conda#2810]
Windows 7
conda 4.1.2
Using git bash terminal

$ conda create -n newenv python=3.4
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3\envs\newenv:

The following NEW packages will be INSTALLED:

    pip:            8.1.2-py34_0
    python:         3.4.4-4
    setuptools:     23.0.0-py34_0
    vs2010_runtime: 10.00.40219.1-1
    wheel:          0.29.0-py34_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# $ source activate newenv
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate newenv
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 48, in main
    activate.main()
  File "C:\Anaconda3\lib\site-packages\conda\cli\activate.py", line 119, in main
    shelldict = shells[shell]
KeyError: 'bash'

Standard windows cmd.exe works with "activate newenv" but this seem broken in git bash.

**Comment by msarahan** [comment]
Fixed by #2795 - closing.
