### ISSUE TITLE
System-wide Anaconda installs on Windows are problematic

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2823]
Copied from the Anaconda mailing list.  Suggests that we need to improve behavior for system-wide installs of Anaconda onto Windows systems.

---
**Comment from @msarahan:**

If you install system-wide, rather than user-local, then the installation is done with administrative rights.  Depending on where you put things, you might see permissions errors.

Unless you have good reason to want a system-wide install, user-local installs are much less likely to go wrong this way.

---
**Original post:**

During the installation of Anaconda 2.7, nothing indicated that it needed admin privileges to run.  However, virtually nothing runs without it.

If I open a powershell and try to run IPython, it crashes and the message is cryptic.  However, if I run IPython in a PowerShell as admin, it runs fine.  

I'm also having problems installing add-ons, which I assume is another admin issue.

Why is this necessary to run as admin??  Can this be fixed?

**Comment by kalefranz** [comment]
@csoja has promised me some of @mingwandroid's time in the near future for things just like this

**Comment by kalefranz** [comment]
I think `4.1.5` released today will fix a lot of issues people have been seeing on Windows.
