### ISSUE TITLE
epoch specification (bang !) in versions confuse conda

### ISSUE THREAD

**Issue by jarondl** [conda/conda#2824]
PEP440 allows to use `!` to specify epochs. This confuses some of the conda commands, because `!` can also be the first char of `!=`.

Some examples follow:

### Specific version installation fails:

    $ conda install -c msys2 m2-mintty=1!12.2.3
    Error: invalid package specification: m2-mintty=1!12.2.3

### `env export` fails if any package has a `!` in its version

    $ conda env export -n m2tty
     Error: invalid package specification: msys2::m2-mintty=1!2.2.3=1

### The regexp of `conda.cli.common.spec_from_line`  is the reason for this:

    >>> from conda.cli import common
    >>> print(common.spec_from_line('msys2::m2-mintty-1!12.2.3'))
    msys2::m2-mintty-1 !12.2.3
    >>> print(common.spec_from_line('msys2::m2-mintty-112.2.3'))
    msys2::m2-mintty-112.2.3

**Comment by mcg1969** [comment]
Good find. Our `VersionSpec` operator supports epochs but clearly it is not supported in other places.

**Comment by kalefranz** [comment]
fixed by #2832

**Comment by jarondl** [comment]
Thank you for the very quick fix

**Comment by kalefranz** [comment]
4.1.4 will be released today.
