### ISSUE TITLE
new dependencies for 4.2

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2825]
* click, first to refine progressbar, and later as a more sophisticated argparse
* toolz, because conda core logic will start to look more and more functional
* boltons, because there's too much quality code not to reuse
* auxlib, finally as a full dependency
* responses, as a test dependency for mocking requests
* enum34, for python27
* futures, for python27
* effect, not for sure yet, but under consideration

Some of these may be vendored like progressbar.

I don't see many dependencies beyond these for 4.X releases.

**Comment by kalefranz** [comment]
After some recent issues with certain dependencies in the root environment, I'm considering vendoring all pure-python dependencies starting in 4.2.  We'd do this as long as conda remains in the root/default environment.  As of conda 5.0, it will be in its own private environment with executables symlinked into the root environment, but that's farther down the road.  Until then, vendoring will help prevent some dependency problems with the only drawback being a bit bigger package size and extra files within conda's own conda package.

**Comment by jakirkham** [comment]
Thanks for pointing this out @kalefranz. I'll keep an eye on this as 4.2 approaches.

cc @pelson

**Comment by pelson** [comment]
>  As of conda 5.0, it will be in its own private environment with executables symlinked into the root environment

At last! :tada: Death to the idea of a root environment!? :smile:

**Comment by kalefranz** [comment]
> Death to the idea of a root environment!

Yes, the "root environment" will be split into a "user default" environment and a "conda private" environment.  In general, the creation of a new environment will just be creating an empty directory.  The requirement to have at least one package in a conda environment has been kind of dumb to me.  The "user default" environment won't be quite blank; there will be a symlink to the conda executable within conda's private environment.

**Comment by pelson** [comment]
> there will be a symlink to the conda executable within conda's private environment.

Have you considered not doing that? You can achieve complete isolation for conda if you don't do it, and so long as the "conda private" environment is on your path, it doesn't matter what you do to the user default environment - users could completely blow it away without a care in the world... :smile:

**Comment by kalefranz** [comment]
> Have you considered not doing that? 

There could definitely be alternate ways of achieving the same thing.  Symlinking to `/usr/local/bin/conda` for example.  I guess 5.0 is far enough off I haven't thought about it fully yet.

**Comment by pelson** [comment]
>  Symlinking to /usr/local/bin/conda for example

Careful of needing root to install though :wink:

**Comment by kalefranz** [comment]
> Careful of needing root to install though

Of course.  I don't think we'll need to *actually* implement everything before we know exactly how we'll implement it.  It's pretty clear to me though that there will need to be several different "modes" that are fully supported.  Single user non-system (not /usr/local/bin/conda), single user system, multi-user non-system, multi-user system, etc...

**Comment by mcg1969** [comment]
I was talking with @msarahan yesterday about his idea of having a directory, perhaps called `exec`, that would be included in the user's PATH and contain the symlinks to the various routines like `conda`, `activate`, `deactivate`, etc. This directory could stay in the user's path no matter which environment is selected (including root).

**Comment by kalefranz** [comment]
This is starting to verge into discussion that should be had here: https://github.com/conda/conda/issues/2502

Can we move discussion there for things that aren't dependency related?

**Comment by kalefranz** [comment]
Adding appdirs to the list of potential packages useful in the 4.x series of feature releases.
