### ISSUE TITLE
Partial permissions errors in conda install leads to partially-installed package

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2830]
Observed behavior: numba team had a docker image for building.  Docker image installed miniconda as root, but changed permissions on install folder to 777.  At some point, some install or update may have changed those permissions, leading to the lib/python2.7/site-packages/conda folder not being writable by the user.  However, the bin folder was writable.

conda update conda ran "successfully" - but updated only the activate scripts, not the conda folder.  Since the new conda 4.1.2 activates things with an extra argument, the old conda code was barfing.

We probably need to fail and roll back if any part of a package fails.

**Comment by kalefranz** [comment]
Will be fixed in 4.3 with #3571.
