### ISSUE TITLE
Let conda create empty env

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2833]
`conda create -n ENV_NAME` and `conda create -p /tmp/env-location` should both work, and should create "empty" envs with only the symlinks in `$CONDA_PREFIX/bin`.

**Comment by pjbull** [comment]
In case anyone else ends up here through a Google search, this workaround is currently working for my purposes: http://stackoverflow.com/a/37216638/1692709

**Comment by dorzel** [comment]
Should work now, changes in #3072

**Comment by dorzel** [comment]
done as of #3072
