### ISSUE TITLE
Potential Conda bug "prefix already exists"

### ISSUE THREAD

**Issue by illuzioner** [conda/conda#2834]
I posted this on the Anaconda Google group, and somone responded that they believe this might be a Conda bug.   I'm taking a Coursera course, and they gave instructions on installing their software on top of Anaconda.  Their very first command fails. As I didn't know what it did, I followed blindly:
`conda create -n dato-env python=2.7 anaconda`

I have a fresh installation of Anaconda for Python 2.7 on Windows 7 for the local user only.  After issuing the command, it gave a listing a bunch of packages it said it was going to install, I chose to proceed and got the following error:

```
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
        1 file(s) copied.#################################               |  71%
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):

  File "D:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "D:\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "D:\Anaconda2\lib\site-packages\conda\cli\install.py", line 445, in install
    misc.append_env(prefix)
  File "D:\Anaconda2\lib\site-packages\conda\misc.py", line 195, in append_env
    os.mkdir(dir_path)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\Derek;\\.conda'

```

After it failed, I tried again, and then it complains again with a different error:

`Error: prefix already exists: D:\Anaconda2\envs\dato-env`

I attempted this directly after installing Anaconda, so nothing would have gotten corrupted.

Here's the info from "conda info -a"

c:\Windows\system32>conda info -a
conda info -a
Current conda install:

```
         platform : win-64
    conda version : 4.0.5
```

  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : D:\Anaconda2  (writable)
  default environment : D:\Anaconda2
     envs directories : D:\Anaconda2\envs
        package cache : D:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
# conda environments:
# 

dato-env                 D:\Anaconda2\envs\dato-env
root                  \*  D:\Anaconda2

sys.version: 2.7.11 |Anaconda 4.0.0 (64-bit)| (defaul...
sys.prefix: D:\Anaconda2
sys.executable: D:\Anaconda2\python.exe
conda location: D:\Anaconda2\lib\site-packages\conda
conda-build: D:\Anaconda2\Scripts\conda-build.exe
conda-convert: D:\Anaconda2\Scripts\conda-convert.exe
conda-develop: D:\Anaconda2\Scripts\conda-develop.exe
conda-env: D:\Anaconda2\Scripts\conda-env.exe
conda-index: D:\Anaconda2\Scripts\conda-index.exe
conda-inspect: D:\Anaconda2\Scripts\conda-inspect.exe
conda-metapackage: D:\Anaconda2\Scripts\conda-metapackage.exe
conda-pipbuild: D:\Anaconda2\Scripts\conda-pipbuild.exe
conda-server: D:\Anaconda2\Scripts\conda-server.exe
conda-sign: D:\Anaconda2\Scripts\conda-sign.exe
conda-skeleton: D:\Anaconda2\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: D:\Anaconda2\Library\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;D:\Revolution\Rtools\bin;D:\Revolution\Rtools\gcc-4.6.3\bin;C:\Python27;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Windows Azure\CLI\wbin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Python27\Scripts\;d:\Program Files\MATLAB\R2013b\bin;D:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\bin;C:\ProgramData\chocolatey\bin;D:\Anaconda2;D:\Anaconda2\Scripts;D:\Anaconda2\Library\bin;C:\Python27;C:\Tcl\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;D:\Revolution\Rtools\bin;D:\Revolution\Rtools\gcc-4.6.3\bin;C:\Python27;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Windows Azure\CLI\wbin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Python27\Scripts\;d:\Program Files\MATLAB\R2013b\bin;D:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\bin;C:\ProgramData\chocolatey\bin;
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

Using Anaconda Cloud api site https://api.anaconda.org

**Comment by kalefranz** [comment]
'C:\\Users\\Derek;\\.conda'

That looks fishy to me.  The semicolon.

What is the output of `conda config --get`?

**Comment by kalefranz** [comment]
for the `prefix already exists` error, `conda remove -n dato-env --all` should fix that.

**Comment by illuzioner** [comment]
Yes, the semicolon looked suspicious to me too, but I haven't modified a thing.  I just downloaded and ran the conda command.

Here is the output of conda config:

`D:\Anaconda2\envs>conda config --get
conda config --get
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "D:\Anaconda2\lib\site-packages\conda\cli\main_config.py", line 212, in execute
    execute_config(args, parser)
  File "D:\Anaconda2\lib\site-packages\conda\cli\main_config.py", line 332, in execute_config
    with open(rc_path, 'w') as rc:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Derek;\\.condarc'
`

Is this an installation bug?  Should the semicolon not be there?

To get around it initially, I renamed the directory, and tried the command again and got this error (which looks similar to the above):

`WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\Derek;\\.conda'`

There's a 'Derek' directory, of course, but none with the semicolon.  What process creates this directory or is it an install script typo?

**Comment by kalefranz** [comment]
What do you have in your `.condarc` file?  Probably `C:\Users\Derek\.condarc`.

**Comment by illuzioner** [comment]
I don't see a .condarc file in C:\Users\Derek\  or anywhere on my system.  The only things in that directory that look related are .anaconda and .condamanager folders.

**Comment by kalefranz** [comment]
@msarahan Do you know what's going on here with the semicolon? Have you ever seen it before?

**Comment by msarahan** [comment]
Nope.  Best place to start, IMHO, would be https://github.com/conda/conda/blob/master/conda/misc.py#L238

**Comment by illuzioner** [comment]
Let me know if you need further info from me.This is the install file name:
Anaconda2-4.0.0-Windows-x86_64.exe
which is dated 6/11/16 on my system.

**Comment by illuzioner** [comment]
I just remembered something that may be relevant.  I originally installed Anaconda and must have accidentally chosen for all users.  I was having so many problems with everything requiring admin privileges, so I uninstalled, rebooted and reinstalled for a single user with the configuration as above.

**Comment by illuzioner** [comment]
I uninstalled everything and rebooted.  While the Anaconda directory was deleted, there were dangling Anaconda ipython references in the registry.

I reinstalled everything and attempted the conda create command as before, but got the same error.

Is there a way around these errors? Something I can do by hand?

**Comment by kalefranz** [comment]
I'm still confused by this.  It's still open because I just don't know.  That semicolon seems like the smoking gun to me.  I just don't have the Windows chops at the moment to know exactly where it's coming from.

**Comment by illuzioner** [comment]
Do you need something else from me? Is there a way I can help?  I still can't get these things to work, so ...

**Comment by msarahan** [comment]
I recommend opening a python prompt (from your anaconda install), and running:

```
from os.path import abspath, expanduser
print(expanduser('~/.condarc'))
print(abspath(expanduser('~/.condarc')))
```

(from https://github.com/conda/conda/blob/2f32ff4f67268eff55955379340d9db1dc79c684/conda/config.py#L103 )

Please paste that output here.

Next, do you have an environment variable named CONDARC set?  Probably not.  Try creating a trivial .condarc file, and set CONDARC to be the path to that file.  There's a sample at http://conda.pydata.org/docs/install/sample-condarc.html

That CONDARC file *might* be a workaround, but it would still be good to understand the problem.

**Comment by mcg1969** [comment]
This is the best idea so far but yes I am stumped too.

**Comment by illuzioner** [comment]
I think you may have hit on something.  I looked at my environmental variables and I see the following with HOME (under the new username Gene):

HOME                           C:\Users\Gene;
HOMEPATH                       \Users\Gene

So, HOME has that semicolon in it.  I don't know how it got there, but it hasn't seemed to cause any problems.  Is that a legitmate semicolon or did some software flub it up?

Here's the output of the requested commands:


In [2]: print(expanduser('~/.condarc'))
C:\Users\Gene;/.condarc

In [3]: print(abspath(expanduser('~/.condarc')))
C:\Users\Gene;\.condarc

In [4]: print(expanduser('~/'))
C:\Users\Gene;/

**Comment by msarahan** [comment]
Something flubbed it up. Get rid of the ; in HOME and things should work.

**Comment by cristobal23** [comment]
Thank you for keeping this issue open.  It definitely seems like a bug. Here is my MVCE:
```
$ docker run -it --rm continuumio/miniconda conda create -f -p . python
Error: prefix already exists: /
```

**Comment by kalefranz** [comment]
@cristobal23 just change your command to 

    docker run -it --rm continuumio/miniconda conda install --mkdir -f -p . python

**Comment by kalefranz** [comment]
OP problem should be solved by fixing the HOME environment variable.
