### ISSUE TITLE
conda pkgs subdir doesn't track different channels for same package

### ISSUE THREAD

**Issue by davidslac** [conda/conda#2835]
I created a conda package with the same name in two different channels. I then created two different conda environments. The different environments had this package but it is from the two different channels.
Aftewards, both environments seem to have the correct version of the package, but the conda/pkgs subdirectory now only includes the latter install. I guess this is Ok, but worries me a bit. For managing lots of packages and disk space, I think it would be good to be able to find packages from different channels in the conda install. That is, what I think happens is

1. install mypkg from channelA into envA
creates miniconda2/pkgs/mypkg  say inode is 100 for some header file, mypkg/include/mypkg.h
creates miniconda2/envs/envA/include/mypkg.h with inode 100, using hard link

2. install mypkg from channelB into envB
overwrites miniconda2/pkgs/mypkg  say inode is now 200 for that header file, mypkg/include/mypkg.h
creates miniconda2/envs/envB/include/mypkg.h with inode 200

 I can see that the inode for envA/include/mypkg.h is still 100, so it is still there, (I am on rhel7 linux).

Anyways, maybe this is fine? The application I have in mind is using different channels to keep track of builds on different OS's. We have C++ code I'd like to get into conda packages - I have some understanding of how conda builds things for all the variants of linux (namely build on the lowest common demoninator, I think CensOS 5?) - but I'm hesitant to give up building with a more recent gcc compiler on rhel7. I was thinking of having one channel where we build with rhel5, presumably we can make that available to people offsite, and then another channel where we build on rhel7.

**Comment by kalefranz** [comment]
With where we are right now, an identical tarball package placed in two different channels is considered two different packages by conda.  At some point we might consider a way to be smarter about this (e.g. checking hashes or something like that), but we're not there right now. Definitely something we could consider in the future though.  @mcg1969 might want to weigh in.

Yes, we try to build everything on CentOS 5, but not with the CentOS 5 compiler (only that kernel and glibc version).  There is currently a conda package for gcc 4.8.2 that has worked very well for me, and @msarahan is working on a gcc 5.x or 6.x conda package (I'm not sure what he's decided on).

**Comment by mcg1969** [comment]
> Aftewards, both environments seem to have the correct version of the package, but the conda/pkgs subdirectory now only includes the latter install. 

Yes, this is exactly the expected behavior now; and indeed it has been the behavior from the beginning. The package cache can handle only one package with the same name at the same time. The package found in the cache will always be the last one that needed installing. In a future version we plan to rework the package cache, and possibly enable this kind of application.

**Comment by davidslac** [comment]
Thanks Kale! I added gcc>=4.8.2,<5 as a requirement for something I was 
building and it picked up 4.8.5, nice to get the latest. I'll try it, 
but let me know if you if you think 4.8.2 vs 4.8.5 might cause a problem.

best,

David

**Comment by kalefranz** [comment]
Oh maybe it is 4.8.5.  Or maybe we've updated it recently.  But I think you have the right one now.
