### ISSUE TITLE
Would be nice if conda config --get channels listed the channels in priority order

### ISSUE THREAD

**Issue by mwcraig** [conda/conda#2841]
As far as I can tell it currently lists them in reverse order.

**Comment by mcg1969** [comment]
Good idea!

**Comment by kalefranz** [comment]
Wow, I was about to change this, but the code has a note

    # Note, since conda config --add prepends, these are printed in
    # the reverse order so that entering them in this order will
    # recreate the same file

It's a good point.  And as implemented was intended to be a feature.  I don't think this is a bug anymore.  And if we change it, would have to go in 4.2.x instead of 4.1.x.  I have to think more about it.

**Comment by kalefranz** [comment]
I think one problem is that `--add` prepends.  It seems more natural to me that `--add` would append, and there should be a separate `--prepend` flag.

As a new feature (maybe not in 4.2.x), we should probably add both `--append` and `--prepend` flags.  Keep the `--add` flag as-is for a while, but warn on use, and eventually change the behavior for `--add` from prepend to append.

**Comment by mcg1969** [comment]
Good news: we already have append and prepend.

**Comment by mcg1969** [comment]
As a stopgap, you could perhaps add `# lowest priority` and `# highest priority` to the first and last lines of the output?

**Comment by kalefranz** [comment]
> Good news: we already have append and prepend.

Oh perfect. I thought we had added one of them.  Didn't remember if we put in both.
