### ISSUE TITLE
Installing from AE Repository channel not working with conda 4.1

### ISSUE THREAD

**Issue by vestuto** [conda/conda#2842]
Different behavior seen between conda 4.0.5 (works) and conda 4.1.2 (not working).

The following works with conda 4.0.5:

```
conda install my_package -c my_repo_user
```

**Comment by vestuto** [comment]
@kalefranz per your request and our discussion, details sent directly to you, but please let me know if you need me to add more detail in this thread for others.

**Comment by kalefranz** [comment]
@vestuto Conda 4.1.3 is out now.  Could you do me a huge favor and just make sure the problem is still there for you (before I go chase down a bug that's already been fixed).

**Comment by kalefranz** [comment]
old issue that should be fixed now.
