### ISSUE TITLE
file:// URLs don't work anymore with conda 4.1.3

### ISSUE THREAD

**Issue by ciupicri** [conda/conda#2845]
Conda 4.1.3 does not work anymore with __file://__ URLs:

```
(E:\Anaconda3) C:\Windows\system32>conda update --override-channels --channel file:///A:/pkgs/free --all
Fetching package metadata ....Error: Could not find URL: file:///A:/pkgs/free/win-64/
```

But `A:\pkgs\free\win-64` really exists:

```
(E:\Anaconda3) C:\Windows\system32>dir A:\pkgs\free\win-64
 Volume in drive A is Software
 Volume Serial Number is 4546-3CD9

 Directory of A:\pkgs\free\win-64

06/24/2016  12:31 AM    <DIR>          .
01/23/2016  06:27 PM    <DIR>          ..
06/24/2016  12:28 AM           259,605 repodata.json.bz2
07/07/2015  12:54 AM            85,764 argcomplete-0.9.0-py34_0.tar.bz2
```

Before upgrading from 4.0.8-py35_0 everything worked fine. The same happened to the Linux version.

**Comment by kalefranz** [comment]
@mcg1969 I think I was going to write an integration test for this but obviously let it slip.

**Comment by mcg1969** [comment]
ARGH! No, actually, we have integration tests for file URLs and for file-based channels. This is madness! :-( @ciupicri, I apologize.

**Comment by mcg1969** [comment]
Hold on! @ciupicri, can you please create an _uncompressed_ `repodata.json` in that channel directory?

**Comment by mcg1969** [comment]
(You do recall, do you not, @kalefranz, that you removed the `bzip2` support from my test...)

**Comment by kalefranz** [comment]
:facepalm:

**Comment by mcg1969** [comment]
Looks like we need to refer to `bzip2` for file:// base URLs. Should be a simple fix, not quite one-line.

**Comment by ciupicri** [comment]
@mcg1969, I've uncompresses the `repodata.json` that I had, and now conda fails at the next stage:

        unicodecsv:       0.14.1-py35_0      --> 0.14.1-py35_0     file:///A:/pkgs/free
        vs2015_runtime:   14.00.23026.0-0    --> 14.00.23026.0-0   file:///A:/pkgs/free
        wheel:            0.29.0-py35_0      --> 0.29.0-py35_0     file:///A:/pkgs/free

    Proceed ([y]/n)? y

    DEBUG:conda.instructions: PREFIX('E:\\Anaconda3')
    DEBUG:conda.instructions: PRINT('Fetching packages ...')
    Fetching packages ...
    INFO:print:Fetching packages ...
    DEBUG:conda.instructions: FETCH('file:///A:/pkgs/free::libdynd-0.7.2-0')
    DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
    DEBUG:conda.fetch:url='file:///A:/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2'
    DEBUG:conda.fetch:HTTPError: 404 Client Error: None for url: file:///A:/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2: file:///A:/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2

    Error: HTTPError: 404 Client Error: None for url: file:///A:/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2: file:///A:/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2

`conda list` show that I already have libdynd-0.7.2.

**Comment by insertinterestingnamehere** [comment]
We're seeing something like this again in the DyND CI tests with conda 4.1.8. See https://travis-ci.org/libdynd/dynd-python/jobs/144685868#L4538 for an example. It's not a blocker on our end (I already have a workaround), but still something to be aware of.
