### ISSUE TITLE
Updating conda to v.4.1 is failing

### ISSUE THREAD

**Issue by kcnwogu** [conda/conda#2857]
the command I ran:
`conda install -c conda conda=4.1.0rc3`
`Error: No packages found matching: conda 4.1.0rc3*`

But I see that the package exist in [conda](https://anaconda.org/conda/conda) repo

`conda info`
`Current conda install:

```
         platform : win-64
    conda version : 2.3.1-84-g69dc93b`
```

**Comment by kalefranz** [comment]
any reason you need `4.1.0rc3`?  `conda update conda` should give you `4.1.3`

**Comment by kcnwogu** [comment]
I tired that too but to no avail.

**Comment by kalefranz** [comment]
Can you give me the output of both `conda info` and `conda update conda`?

**Comment by kcnwogu** [comment]
`conda update conda`
>Error: No packages found matching: conda-env >=2.5.0

`conda info`

> Current conda install:

             platform : win-64
        conda version : 2.3.1-84-g69dc93b
     root environment : C:\Continuum\Miniconda  (writable)
  default environment : C:\Continuum\Miniconda
     envs directories : C:\Continuum\Miniconda\envs
        package cache : C:\Continuum\Miniconda\pkgs
         channel URLs : https://conda.binstar.org/conda/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\.condarc
    is foreign system : False

**Comment by kalefranz** [comment]
Yeah I see the problem.  Try `conda update conda` now.

**Comment by kcnwogu** [comment]
I am still getting the error message:
`conda update conda`
`Error: No packages found matching: conda-env >=2.5.0`

**Comment by kalefranz** [comment]
How about

    conda config --remove channels conda
    conda update conda

**Comment by kcnwogu** [comment]
I am still getting the error.
`conda config --remove channels conda`
Error: --remove without --force is not implemented yet

`conda config --remove channels conda --force`

`conda update conda`
Error: No packages found matching: conda-env >=2.5.0

**Comment by kalefranz** [comment]
The base conda install at the time this issue was created was conda 2.3.1.  This conda version is extremely old and outdated.  If problems persist, the easiest solution will be to just download a new miniconda installer and use that.
