### ISSUE TITLE
Installing Matplotlib change permissions error

### ISSUE THREAD

**Issue by RGCheek** [conda/conda#2863]
I tried installing matplot lib and permission was denied...
[rgcheek@vm64-243 ~]$ conda install matplotlib
Fetching package metadata: ......
Solving package specifications: ...........................
Package plan for installation in environment /usr/local/anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| libpng-1.6.17 | 0         214 KB |
| mkl-11.3.3 | 0       122.1 MB |
| openssl-1.0.2h | 1         3.2 MB |
| pixman-0.32.6 | 0         2.4 MB |
| sqlite-3.13.0 | 0         4.0 MB |
| yaml-0.1.6 | 0         246 KB |
| zlib-1.2.8 | 3         101 KB |
| freetype-2.5.5 | 1         2.5 MB |
| libxml2-2.9.2 | 0         4.2 MB |
| fontconfig-2.11.1 | 5         402 KB |
| cairo-1.12.18 | 6         594 KB |
| qt-4.8.7 | 3        34.1 MB |
| conda-env-2.5.1 | py27_0          26 KB |
| numpy-1.11.0 | py27_1         6.2 MB |
| pycairo-1.10.0 | py27_0          81 KB |
| pycosat-0.6.1 | py27_1         190 KB |
| pyparsing-2.1.4 | py27_0          70 KB |
| python-2.7.11 | 0        12.0 MB |
| pytz-2016.4 | py27_0         178 KB |
| pyyaml-3.11 | py27_4         297 KB |
| requests-2.10.0 | py27_0         611 KB |
| ruamel_yaml-0.11.7 | py27_0         352 KB |
| setuptools-23.0.0 | py27_0         455 KB |
| sip-4.16.9 | py27_0         247 KB |
| six-1.10.0 | py27_0          16 KB |
| wheel-0.29.0 | py27_0          81 KB |
| conda-4.1.3 | py27_0         197 KB |
| cycler-0.10.0 | py27_0          11 KB |
| pip-8.1.2 | py27_0         1.5 MB |
| pyqt-4.11.4 | py27_3         3.4 MB |
| python-dateutil-2.5.3 | py27_0         236 KB |
| matplotlib-1.5.1 | np111py27_0         8.2 MB |

```
------------------------------------------------------------
                                       Total:       208.4 MB
```

The following NEW packages will be INSTALLED:

```
cycler:          0.10.0-py27_0    
mkl:             11.3.3-0         
pycairo:         1.10.0-py27_0    
ruamel_yaml:     0.11.7-py27_0    
wheel:           0.29.0-py27_0    
```

The following packages will be UPDATED:

```
cairo:           1.12.18-1        --> 1.12.18-6        
conda:           3.12.0-py27_0    --> 4.1.3-py27_0     
conda-env:       2.1.4-py27_0     --> 2.5.1-py27_0     
fontconfig:      2.11.1-2         --> 2.11.1-5         
freetype:        2.5.2-0          --> 2.5.5-1          
libpng:          1.5.13-1         --> 1.6.17-0         
libxml2:         2.9.0-0          --> 2.9.2-0          
matplotlib:      1.4.3-np19py27_1 --> 1.5.1-np111py27_0
numpy:           1.8.2-py27_0     --> 1.11.0-py27_1    
openssl:         1.0.1k-1         --> 1.0.2h-1         
pip:             7.0.1-py27_0     --> 8.1.2-py27_0     
pixman:          0.26.2-0         --> 0.32.6-0         
pycosat:         0.6.1-py27_0     --> 0.6.1-py27_1     
pyparsing:       2.0.3-py27_0     --> 2.1.4-py27_0     
pyqt:            4.11.3-py27_0    --> 4.11.4-py27_3    
python:          2.7.10-0         --> 2.7.11-0         
python-dateutil: 2.4.1-py27_0     --> 2.5.3-py27_0     
pytz:            2015.4-py27_0    --> 2016.4-py27_0    
pyyaml:          3.11-py27_0      --> 3.11-py27_4      
qt:              4.8.6-0          --> 4.8.7-3          
requests:        2.7.0-py27_0     --> 2.10.0-py27_0    
setuptools:      17.0-py27_0      --> 23.0.0-py27_0    
sip:             4.16.5-py27_0    --> 4.16.9-py27_0    
six:             1.9.0-py27_0     --> 1.10.0-py27_0    
sqlite:          3.8.4.1-1        --> 3.13.0-0         
yaml:            0.1.4-0          --> 0.1.6-0          
zlib:            1.2.8-0          --> 1.2.8-3          
```

Proceed ([y]/n)? y

Fetching packages ...
libpng-1.6.17- 100% |################################| Time: 0:00:00 513.07 kB/s
mkl-11.3.3-0.t 100% |################################| Time: 0:00:06  20.15 MB/s
openssl-1.0.2h 100% |################################| Time: 0:00:01   3.00 MB/s
pixman-0.32.6- 100% |################################| Time: 0:00:01   1.42 MB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:01   2.62 MB/s
yaml-0.1.6-0.t 100% |################################| Time: 0:00:00 509.60 kB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00 359.71 kB/s
freetype-2.5.5 100% |################################| Time: 0:00:01   1.97 MB/s
libxml2-2.9.2- 100% |################################| Time: 0:00:01   2.58 MB/s
fontconfig-2.1 100% |################################| Time: 0:00:00 746.35 kB/s
cairo-1.12.18- 100% |################################| Time: 0:00:00 847.77 kB/s
qt-4.8.7-3.tar 100% |################################| Time: 0:00:03   9.20 MB/s
conda-env-2.5. 100% |################################| Time: 0:00:00 394.34 kB/s
numpy-1.11.0-p 100% |################################| Time: 0:00:01   4.84 MB/s
pycairo-1.10.0 100% |################################| Time: 0:00:00 398.66 kB/s
pycosat-0.6.1- 100% |################################| Time: 0:00:00 474.18 kB/s
pyparsing-2.1. 100% |################################| Time: 0:00:00 348.25 kB/s
python-2.7.11- 100% |################################| Time: 0:00:02   6.04 MB/s
pytz-2016.4-py 100% |################################| Time: 0:00:00 442.23 kB/s
pyyaml-3.11-py 100% |################################| Time: 0:00:00 630.58 kB/s
requests-2.10. 100% |################################| Time: 0:00:00 821.71 kB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00 656.29 kB/s
setuptools-23. 100% |################################| Time: 0:00:00 753.29 kB/s
sip-4.16.9-py2 100% |################################| Time: 0:00:00 528.46 kB/s
six-1.10.0-py2 100% |################################| Time: 0:00:00 245.14 kB/s
wheel-0.29.0-p 100% |################################| Time: 0:00:00 397.30 kB/s
conda-4.1.3-py 100% |################################| Time: 0:00:00 488.50 kB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00   5.27 MB/s
pip-8.1.2-py27 100% |################################| Time: 0:00:01   1.59 MB/s
pyqt-4.11.4-py 100% |################################| Time: 0:00:01   2.85 MB/s
python-dateuti 100% |################################| Time: 0:00:00 505.31 kB/s
matplotlib-1.5 100% |################################| Time: 0:00:01   4.56 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  37%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/local/anaconda/bin/conda", line 5, in <module>

  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 93, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 89, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/install.py", line 539, in link
    os.makedirs(dst_dir)
  File "/usr/local/anaconda/lib/python2.7/os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/usr/local/anaconda/lib/python2.7/site-packages/conda_env/specs'

I tried changing permissions, and now conda is no longer recognized on my iplant virtual machines. 
[rgcheek@vm64-243 ~]$ ls -lh /usr/local/anaconda/lib/python2.7/site-packages/conda_env/specs
ls: cannot access /usr/local/anaconda/lib/python2.7/site-packages/conda_env/specs: No such file or directory
[rgcheek@vm64-243 ~]$ ls -lh /usr/local/anaconda/lib/python2.7/site-packages/conda_env
total 52K
drwxr-xr-x 2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 cli
-rw-rw-r-- 2 brantfaircloth iplant-everyone  283 Apr  6  2015 compat.py
-rw-rw-r-- 2 brantfaircloth iplant-everyone  749 Apr  6  2015 compat.pyc
-rw-rw-r-- 2 brantfaircloth iplant-everyone 3.3K Apr  6  2015 env.py
-rw-rw-r-- 2 brantfaircloth iplant-everyone 4.9K Apr  6  2015 env.pyc
-rw-rw-r-- 2 brantfaircloth iplant-everyone  308 Apr  6  2015 exceptions.py
-rw-rw-r-- 2 brantfaircloth iplant-everyone  992 Apr  6  2015 exceptions.pyc
-rw-rw-r-- 2 brantfaircloth iplant-everyone    1 Apr  6  2015 **init**.py
-rw-rw-r-- 2 brantfaircloth iplant-everyone  169 Apr  6  2015 **init**.pyc
drwxr-xr-x 2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 installers
-rw-rw-r-- 2 brantfaircloth iplant-everyone  684 Apr  6  2015 yaml.py
-rw-rw-r-- 2 brantfaircloth iplant-everyone 1.1K Apr  6  2015 yaml.pyc
[rgcheek@vm64-243 ~]$ ls -alh /usr/local/anaconda/lib/python2.7/site-packages/conda_env
total 68K
drwxr-xr-x   4 brantfaircloth iplant-everyone 4.0K Jun  2  2015 .
drwxrwxr-x 117 root           users            12K Jun 24 15:56 ..
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 cli
-rw-rw-r--   2 brantfaircloth iplant-everyone  283 Apr  6  2015 compat.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  749 Apr  6  2015 compat.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone 3.3K Apr  6  2015 env.py
-rw-rw-r--   2 brantfaircloth iplant-everyone 4.9K Apr  6  2015 env.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone  308 Apr  6  2015 exceptions.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  992 Apr  6  2015 exceptions.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone    1 Apr  6  2015 **init**.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  169 Apr  6  2015 **init**.pyc
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 installers
-rw-rw-r--   2 brantfaircloth iplant-everyone  684 Apr  6  2015 yaml.py
-rw-rw-r--   2 brantfaircloth iplant-everyone 1.1K Apr  6  2015 yaml.pyc
[rgcheek@vm64-243 ~]$ chmod u+x /usr/local/anaconda/lib/python2.7/site-packages/conda_env/*
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/cli': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/compat.py': Operation not permitted
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/compat.pyc': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/env.py': Operation not permitted
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/env.pyc': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/exceptions.py': Operation not permitted
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/exceptions.pyc': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/**init**.py': Operation not permitted
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/__init__.pyc': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/installers': Operation not permitted
chmod: changing permissions of `/usr/local/anaconda/lib/python2.7/site-packages/conda_env/yaml.py': Operation not permitted
chmod: changing permissions of`/usr/local/anaconda/lib/python2.7/site-packages/conda_env/yaml.pyc': Operation not permitted
[rgcheek@vm64-243 ~]$ sudo chmod u+x /usr/local/anaconda/lib/python2.7/site-packages/conda_env/*
[sudo] password for rgcheek: 
[rgcheek@vm64-243 ~]$ ls -alh /usr/local/anaconda/lib/python2.7/site-packages/conda_env
total 68K
drwxr-xr-x   4 brantfaircloth iplant-everyone 4.0K Jun  2  2015 .
drwxrwxr-x 117 root           users            12K Jun 24 15:56 ..
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 cli
-rwxrw-r--   2 brantfaircloth iplant-everyone  283 Apr  6  2015 compat.py
-rwxrw-r--   2 brantfaircloth iplant-everyone  749 Apr  6  2015 compat.pyc
-rwxrw-r--   2 brantfaircloth iplant-everyone 3.3K Apr  6  2015 env.py
-rwxrw-r--   2 brantfaircloth iplant-everyone 4.9K Apr  6  2015 env.pyc
-rwxrw-r--   2 brantfaircloth iplant-everyone  308 Apr  6  2015 exceptions.py
-rwxrw-r--   2 brantfaircloth iplant-everyone  992 Apr  6  2015 exceptions.pyc
-rwxrw-r--   2 brantfaircloth iplant-everyone    1 Apr  6  2015 **init**.py
-rwxrw-r--   2 brantfaircloth iplant-everyone  169 Apr  6  2015 **init**.pyc
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 installers
-rwxrw-r--   2 brantfaircloth iplant-everyone  684 Apr  6  2015 yaml.py
-rwxrw-r--   2 brantfaircloth iplant-everyone 1.1K Apr  6  2015 yaml.pyc
[rgcheek@vm64-243 ~]$ conda install matplotlib
-bash: /usr/local/anaconda/bin/conda: No such file or directory
[rgcheek@vm64-243 ~]$ conda install matplotlib
-bash: /usr/local/anaconda/bin/conda: No such file or directory
[rgcheek@vm64-243 ~]$ ls -alh /usr/local/anaconda/conda
ls: cannot access /usr/local/anaconda/conda: No such file or directory
[rgcheek@vm64-243 ~]$ ls -alh /usr/local/anaconda
total 128K
drwxrwxr-x  19 root           users           4.0K Jun 24 15:56 .
drwxr-xr-x  14 root           root            4.0K Jun  2  2015 ..
drwxrwxr-x   4 root           users            20K Jun 24 15:56 bin
drwxrwxr-x   2 root           users            12K Jun 24 15:56 conda-meta
-rwxrwxr-x   1 root           users             67 Jun  2  2015 .condarc
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 config
drwxrwxr-x   2 root           users           4.0K Jun  2  2015 envs
drwxr-xr-x   3 rgcheek        iplant-everyone 4.0K Jun 24 15:56 etc
drwxrwxr-x   3 root           users           4.0K Jun  2  2015 Examples
drwxrwxr-x  19 root           users           4.0K Jun 24 15:56 include
drwxrwxr-x   2 root           users           4.0K Jun 24 15:56 .index
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 .ipynb_checkpoints
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 jar
drwxrwxr-x  11 root           users            12K Jun 24 15:56 lib
drwxr-xr-x   3 brantfaircloth iplant-everyone 4.0K Jun  2  2015 libexec
-rwxrwxr-x   1 root           users           3.7K Nov  7  2013 LICENSE.txt
drwxrwxr-x 213 root           users            16K Jun 24 15:56 pkgs
drwxrwxr-x  12 root           users           4.0K Jun 24 15:56 share
drwxr-xr-x   3 rgcheek        iplant-everyone 4.0K Jun 24 15:56 ssl
drwxr-xr-x   3 brantfaircloth iplant-everyone 4.0K Jun  2  2015 test
drwxr-xr-x   3 rgcheek        iplant-everyone 4.0K May 19 15:41 var
[rgcheek@vm64-243 ~]$ sudo chmod u-x /usr/local/anaconda/lib/python2.7/site-packages/conda_env/_.py
[rgcheek@vm64-243 ~]$ sudo chmod u-x /usr/local/anaconda/lib/python2.7/site-packages/conda_env/_.pyc
[rgcheek@vm64-243 ~]$ conda install matplotlib-bash: /usr/local/anaconda/bin/conda: No such file or directory
[rgcheek@vm64-243 ~]$ ls -alh /usr/local/anaconda/lib/python2.7/site-packages/conda_env
total 68K
drwxr-xr-x   4 brantfaircloth iplant-everyone 4.0K Jun  2  2015 .
drwxrwxr-x 117 root           users            12K Jun 24 15:56 ..
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 cli
-rw-rw-r--   2 brantfaircloth iplant-everyone  283 Apr  6  2015 compat.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  749 Apr  6  2015 compat.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone 3.3K Apr  6  2015 env.py
-rw-rw-r--   2 brantfaircloth iplant-everyone 4.9K Apr  6  2015 env.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone  308 Apr  6  2015 exceptions.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  992 Apr  6  2015 exceptions.pyc
-rw-rw-r--   2 brantfaircloth iplant-everyone    1 Apr  6  2015 **init**.py
-rw-rw-r--   2 brantfaircloth iplant-everyone  169 Apr  6  2015 **init**.pyc
drwxr-xr-x   2 brantfaircloth iplant-everyone 4.0K Jun  2  2015 installers
-rw-rw-r--   2 brantfaircloth iplant-everyone  684 Apr  6  2015 yaml.py
-rw-rw-r--   2 brantfaircloth iplant-everyone 1.1K Apr  6  2015 yaml.pyc

Is there any way to solve this issue?
Thanks!

**Comment by kalefranz** [comment]
permissions errors and multi-user installs are fixed in conda 4.3.
