### ISSUE TITLE
coala-bears and conda

### ISSUE THREAD

**Issue by Adrianzatreanu** [conda/conda#2867]
Hello, 

[coala](https://github.com/coala-analyzer/coala) is a code analysis tools that helps you fix your code and many style problems. It uses [bears](https://github.com/coala-analyzer/coala-bears) as plugins, (has over 65) to fix specific problems in many different languages.

However, these bears use external dependencies, some from `pip`, some from `npm`, even more. We are planning to decentralize our bears instead of holding them all together and make them `conda` packages, because we thought that would be awesome. However, for this to happen, we also need to make their requirements conda packages as well!

We were planning to make a script that would automatically upload commands that would install those dependencies our bears need and upload them to Anaconda using conda. But before doing this, we thought that maybe you would have something already that does something similar, or maybe you could help us a little in doing this if you're interested?

Thanks a lot for your time!

CC @sils1297, @justuswilhelm

**Comment by msarahan** [comment]
This sounds like a neat tool.  I think you should head over to conda-forge, which is growing to be the central community hub for conda packaging.  Their intro website is at https://conda-forge.github.io/

To submit new recipes, you clone the repo here: https://github.com/conda-forge/staged-recipes and add your recipe.  Many of your dependencies are probably already there.

I am one of the maintainers there, and am Continuum's representative.  It is a very good place to get started with your effort.

**Comment by sils1297** [comment]
So to be clear, we'd probably be generating lots of conda recipes for all our pip, npm, go, ... packages that are not yet in conda. You don't accidentally already have a tool or something that automatically makes such packages?

**Comment by sils1297** [comment]
So we would probably be adding something like 20-100 packages to conda forge for our dependencies and another 60 or so for our bears. I feel like you should try to make an automated way to mirror pip and go etc. packages, that would make maintenance of those a lot easier. We could write a tool that generates packages but probably not maintain them since you'd still have to clone lots of repositories.

**Comment by mcg1969** [comment]
We have experimented with automated pypi -> conda conversions. It's not as automatable as you may think---too many individual tweaks are required. Conda-forge is the best solution conceived to date for scaling out conda package building beyond what Continuum can provide itself.

**Comment by msarahan** [comment]
One hot topic of discussion at conda-forge is how to have pypi-derived recipes in which the metadata is readily updatable by pulling in current information from PyPI.  The current way to do things is to either 1) grab an existing recipe and modify it by hand; or 2) use ```conda skeleton pypi```, and then modify the skeleton by hand, to add things like the conda-forge maintainer list, and strip out comments.

Conda-build has good support for Jinja2 templating, which certainly allows for any dynamic recipes you can dream up, but we're missing an implementation of how to use that for having more dynamic metadata (recomputed/rediscovered at build time).  Beyond this, automatic mirroring is little more than monitoring package release RSS feeds, or something similar.  There's a lot of interest in that kind of thing at conda-forge.  Please raise this issue at conda-forge's staged-recipes issue tracker - I'm not sure it is something we have as an issue yet.  We have discussed it a fair bit in meetings.  Our meeting notes, agendas, and schedule are at https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG

**Comment by sils1297** [comment]
Ok, it seems that this solution doesn't scale as we need it. We'll probably end up making packages for non pip/gem/npm/... stuff for conda and supporting conda/pip/gem/npm/... in out installation tool to perform installation for the user or at least give him commands that do that.
