### ISSUE TITLE
trouble with the linking part of 'conda install -c r r-essentials'

### ISSUE THREAD

**Issue by Luxios** [conda/conda#2868]
I am sorry but I have met  problems as following :
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序       |  12%
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mingw-w64\bin\p11-kit.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
系统找不到指定的路径。
系统找不到指定的路径。
系统找不到指定的路径。
[      COMPLETE      ]|##################################################| 100%

After this I open the jupyter notebook, and build a new R script , it happens to me that
[cid:54b94674-8a75-4332-8a8b-03cf12468b1e]
the kernel is always dead.But I change  to use python ,it works well. How can I solve this problem?

**Comment by digitalimageprocessingboy** [comment]
you need put C:\Users\xxx\Anaconda\Scripts into your envirment
