### ISSUE TITLE
`conda config --remove channels r --force` results in malformed YAML

### ISSUE THREAD

**Issue by brendancol** [conda/conda#2889]
(env)bcollins@0206-bcollins:~/projects/training-products% conda config --add channels r
(env)bcollins@0206-bcollins:~/projects/training-products% conda config --remove channels r --force
(env)bcollins@0206-bcollins:~/projects/training-products% cat ~/.condarc
```yaml
channels:
- defaults
```

**Comment by mcg1969** [comment]
This has been fixed in 4.1.x; we've upgraded the YAML parser.
