### ISSUE TITLE
Package dependency warnings

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#290]
Are these warnings to be considered bugs?

```
$conda create -n numpy16 numpy=1.6
Warning: 2
     ['numpy-1.6.2-py26_4.tar.bz2', 'python-2.6.8-9.tar.bz2', 'readline-6.2-1.tar.bz2', 'sqlite-3.7.13-1.tar.bz2', 'tk-8.5.13-1.tar.bz2', 'zlib-1.2.7-1.tar.bz2']
     ['numpy-1.6.2-py27_4.tar.bz2', 'python-2.7.5-2.tar.bz2', 'readline-6.2-1.tar.bz2', 'sqlite-3.7.13-1.tar.bz2', 'tk-8.5.13-1.tar.bz2', 'zlib-1.2.7-1.tar.bz2']
Error: Unsatisfiable package specifications
Hint: the following combinations of packages create a conflict with the
remaining packages:
  - python 3.3*
  - numpy 1.6*
```

I get them quite often using the Python 3 version of conda trying to install packages that don't support Python 3. Even if I do `conda install numpy16 numpy=1.6 python=2` I still get the warning (it ends up picking Python 2.7, but is that just random?).

**Comment by pzaback** [comment]
Has this been resolved but not yet cross-referenced here? The default option for a package I'm trying to install (Cartopy) seems not to work, and I don't know how to attempt to use the alternate solution. The relevant dependencies are geos and shapely. The latest version of shapely depends on an earlier version of geos, but attempting to import cartopy throws an error that a newer dylib is required.

**Comment by kalefranz** [comment]
Outdated. Closing.
