### ISSUE TITLE
Add "build.d" analogous to "activate.d" to activate script to support compiler configurations

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#2901]
I'm putting this feature proposal here instead of in `conda build`, because I think it could be structured here generically as a support mechanism that both `conda build` and other build systems using conda could utilize.

The idea is to do two things:
1. Add `$PREFIX/etc/conda/build.d` which is shell scripts or batch files which are sourced on activation in package building/development mode.
2. Add `-b` option to `activate`, so `$ source activate -b mydevenv` would source both `activate.d` scripts and `build.d` scripts.

With this mechanism in place, `conda build` can fully remove its hardcoded knowledge about Python versions <-> compiler settings, and recipes designed to work with multiple compiler settings can be written generically instead of having to do a `source compiler_config.sh` as described in https://github.com/conda/conda-build/issues/911. Basically, `conda build` would no longer call the MSVC `vcvars.bat` file, it would instead use `source activate -b _build` instead of `source activate _build`, so that the compiler setup would happen in a `build.d` file.

To keep Anaconda working the same, the `python` package could add a file to `build.d` which replicates the current behaviour. It would be nicer in my opinion for there to be a different metapackage for this purpose, that depend on the installed `python`, so that it would be possible to have `python` installed for scripting use without polluting the build environment. That would seem to require changing Anaconda and establishing new conventions for python recipes that build C/C++ extensions.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2011
