### ISSUE TITLE
"conda run" command removed?

### ISSUE THREAD

**Issue by daler** [conda/conda#2904]
Previously we were able to use `conda run -n envname -- toolname arg1 arg2` to run a specific tool in a specific environment without activating it first. Conveniently, this worked even in a different active environment and allowed the temporary use of py27-dependent code within an otherwise py3 environment.

However in conda 4.1.2, I get the error, `Error: Could not locate 'conda-run'`. I have been unable to find documentation for `conda run`, or any release notes indicating it has been removed or even git log entries indicating it was removed. It was there at least in 3.7.0, haven't dug though individual commits yet to see exactly where it was lost.

Currently my workaround is to provide the full path to the program within its environment dir (which requires knowing the user's conda installation path), or to downgrade conda. Is there any replacement for conda-run that I'm missing?

**Comment by tomkinsc** [comment]
You're not alone: https://github.com/conda/conda/issues/2682
It looks like `conda run` was removed in 4.10.0, possibly [here](https://github.com/conda/conda/compare/4.0.9...master#diff-120c3055b361dcfd98b6b650d9b7db69L1).

Much of conda is in flux, it seems...

**Comment by daler** [comment]
Thanks for the sleuthing, somehow I missed that issue when searching github issues.

I'll close this and join in over on #2682.

**Comment by ab-w** [comment]
As of `conda` 4.7.11 as of 2019, `conda run` definitely exists. Is there any reason why I shouldn't use it? It seems useful in a Dockerfile.

```
$ conda -V
conda 4.7.11

$ conda | grep run
    run          Run an executable in a conda environment. [Experimental]

$ conda run -h
usage: conda run [-h] [-n ENVIRONMENT | -p PATH] [-v] [--dev]
                 [--debug-wrapper-scripts] [--cwd CWD]
                 ...

Run an executable in a conda environment. [Experimental]

Use '--' (double dash) to separate CLI flags for 'conda run' from CLI flags sent to
the process being launched.

Example usage:

    $ conda create -y -n my-python-2-env python=2
    $ conda run -n my-python-2-env python --version

Options:

positional arguments:
  executable_call       Executable name, with additional arguments to be
                        passed to the executable on invocation.

optional arguments:
  -h, --help            Show this help message and exit.
  -v, --verbose         Use once for info, twice for debug, three times for
                        trace.
  --dev                 Sets `CONDA_EXE` to `python -m conda`, assuming the
                        CWD containsthe root of conda development sources.
                        This is mainly for useduring tests where we test new
                        conda source against old Pythonversions.
  --debug-wrapper-scripts
                        When this is set, where implemented, the shell wrapper
                        scriptswill echo to stderr a lot of debugging
                        information.
  --cwd CWD             Current working directory for command to run in.
                        Defaults to cwd

Target Environment Specification:
  -n ENVIRONMENT, --name ENVIRONMENT
                        Name of environment.
  -p PATH, --prefix PATH
                        Full path to environment location (i.e. prefix).
```

**Comment by mingwandroid** [comment]
Use it if it works for you and it is useful.

It's far from finished though. From my perspective:

1. An IO loop to service stdio for the child (so as things stand the child could not, for example request any input from the user).
2. It uses execve instead of spawn and some people think it should be the other way around and others think that should be an option.

**Comment by karrtikr** [comment]
Can anyone explain what does `"Use '--' (double dash) to separate CLI flags for 'conda run' from CLI flags sent to
the process being launched."` mean in the documentation?

I am not able use double dashes like `conda run -n envname -- python arg1 arg2`

**Comment by karrtikr** [comment]
I can't use double dashes anymore
```
conda run -n test -- python --version
```
I have to run it like
```
conda run -n test python --version
```

Was the support for them removed?

**Comment by impredicative** [comment]
`conda run` is currently [utterly broken](https://github.com/conda/conda/issues/9599), and unless you like silent failures in production, it shouldn't be used. Moreover, the author who broke it and those who're tasked with maintaining it are refusing to fix it.
