### ISSUE TITLE
conda activate and deactivate need to add and remove entries from PATH

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#2914]
Reference: https://github.com/matplotlib/matplotlib/pull/6520

When an environment is first activated, `CONDA_PATH_BACKUP` is set to the current value of `PATH`, and when it is deactivated `PATH` is restored to that value.

Unfortunately, this means that modifications to `PATH` between these times are lost. In particular the `PATH` modifications done by `vcvars.bat` are lost meaning `conda-build` can't currently build things that need Visual Studio.

I propose a slight modification to how this is being handled. Instead we need to add and remove entries during `activate` and `deactivate` respectively. A `deactivate` followed by an immediate `activate` needs special handling so that it inserts the `conda` paths at the *same place*, perhaps by being told that this is happening and inserting a special token we can replace later (here I've called it `CONDA_PATHS_HERE`).

```
PATH=C:\msysGit\bin;C:\somefolder;C:\miniconda\bin;C:\miniconda\Library\bin;C:\someotherfolder
$ deactivate(newenv=_build) =>
PATH=C:\msysGit\bin;C:\somefolder;CONDA_PATHS_HERE;C:\someotherfolder
$ deactivate(newenv=None) =>
PATH=C:\msysGit\bin;C:\somepath;C:\someotherpath
$ activate(env=_build,PATH=C:\msysGit\bin;C:\somepath;CONDA_PATHS_HERE;C:\someotherpath) =>
PATH=C:\msysGit\bin;C:\somepath;C:\miniconda\envs\_build\bin;C:\miniconda\envs\_build\Library\bin;C:\someotherpath
$ activate(env=_build,PATH=C:\msysGit\bin;C:\somepath;C:\someotherpath) =>
PATH=C:\miniconda\envs\_build\bin;C:\miniconda\envs\_build\Library\bin;C:\msysGit\bin;C:\somepath;C:\someotherpath
```

**Comment by mingwandroid** [comment]
@kalefranz, @csoja, @msarahan this is a critical blocker.

**Comment by msarahan** [comment]
@kalefranz I'm happy to fix this on Windows.  Do you think you could do something similar for the bash scripts?  I think it's important that we maintain similar behavior as much as possible.

**Comment by kalefranz** [comment]
I need to get `4.1.5` out today with some other critical fixes.  I'll do the bash stuff that @msarahan asked for and get a `4.1.6` out asap, probably tomorrow.  It'll also include another patch from mcg1969.

**Comment by msarahan** [comment]
Should we leave this open until bash equivalents exist?
