### ISSUE TITLE
error installin r-essentials with conda

### ISSUE THREAD

**Issue by Fercho120** [conda/conda#2919]
Right after using conda install -c r r-essentials a list of packages are displayed and the system ask if it proceed, once it's confirmed the following error appears:

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_fun
c
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in e
xecute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in insta
ll
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRA
CT_CMD
    extract(arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 236, in exp_backo
ff_fn
    result = fn(*args)
WindowsError: [Error 5] Access is denied

(C:\Anaconda2) C:\Windows\system32>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

PD: This is a new attempt, the fist one allows multiple packages installed until the same error shows up; if I type the update command it returns that r packages aren´t installed.

**Comment by Fercho120** [comment]
Suddenly after retrying this appeared:

Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
'mingw-w64\bin\p11-kit.exe' is not recognized as an internal or external command
,
operable program or batch file.
'mingw-w64\bin\p11-kit.exe' is not recognized as an internal or external command
,
operable program or batch file.
'mingw-w64\bin\p11-kit.exe' is not recognized as an internal or external command
,
operable program or batch file.
'mingw-w64\bin\p11-kit.exe' is not recognized as an internal or external command
,
operable program or batch file.
'mingw-w64\bin\p11-kit.exe' is not recognized as an internal or external command
,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[      COMPLETE      ]|##################################################| 100%

What's going on? Is all r-essentials package already installed? If I run the update command it say that all packages are already installed

**Comment by AbhilashAwasthi01** [comment]
I received the same error when trying to install r-essentials in conda in windows environemnt. Did you get the solution?

**Comment by Fercho120** [comment]
I have no idea what was causing the error, I only retried after going for a coffee, then it works; I think it must be someting about processes interfiring the installation, but to be sincere it's merely an especulation

**Comment by AbhilashAwasthi01** [comment]
Yeah now second time I tried, it is installed properly & I am able to create a notebook with R kernel & use R packages in it. Thanks BTW!!

**Comment by mingwandroid** [comment]
The `p11-kit` stuff is, I think, harmless, I'll fix it when I get a chance. The other problems seem to be virus scanner related. We've added some code to `conda` recently to work around this.

If you want the very latest of R, you can use:

`conda install -c rdonnellyr r-essentials`

**Comment by toasteez** [comment]
I received the error today, but when I try to reinstall it states all requested packages already installed?

Has this been fixed?  Will this cause me any issues other that my packaging for installation?

Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Program Files\Anaconda3\.condarc
           offline mode : False


Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Program Files\Anaconda3\.condarc
           offline mode : False

**Comment by mingwandroid** [comment]
@toasteez : which error did you receive?
