### ISSUE TITLE
Making conda the ultimate package manager

### ISSUE THREAD

**Issue by srossross** [conda/conda#292]
I have been challenged a number of times on why I don't use conda for everything I do. 

The following may be a bit long winded, but I think that this pretty short given my goal.
### Problem statement

Sometimes if all I need to do is pip install something especially when provisioning new servers, then I won't use conda because it is _superfluous_. 
#### Example

When my install command is just `pip install -r requirements.txt` If I wanted to use conda I would have to:

1) Download and install conda
2) Split out packages in requirements.txt that are in PyPI and not in a conda channel. OR create conda packages for each PyPI package.
3) Add a new command `conda install` 

I could do this, it is not _unreasonable_. But why would I do the extra work, what advantage does this give me? What advantage does conda give users over pip for packages that are easy to install?
### End Goal

_Make conda the ultimate package manager_ Install all packages with `conda`. no one should ever need anything else. All package should be treated as equals.
#### Example

`conda install package1 package2` should install package1 and package2 the same if they are pip or conda (In the future yum, nodejs, etc too)
### One Solution

Revisit the ideas behind `conda pip` (not the command itself) now that `binstar` exists.

I know that it is less than ideal to have to support multiple package types. but If we want to take over the world, we have to start here. Once people are using conda - even tho they may be installing pip packages - we will make it easy for them to upload new **conda** packages. and thus fulfilling our goal of world domination.
#### Binstar background

Binstar is a package hosting tool that supports arbitrary package types and package metadata. binstar packages are name-spaced behind a user account allowing multiple users to upload the same packages if they like.

Binstar packages contain `distribution`s that are of a package type (conda or pypi, etc.) and contains metadata formatted in a binstar common metadata format:

The binstar structure looks like this:

```
+ sean 
        + ipython
              + ipython-0.13.1-py26_1.tar.bz2
                    + binstar metadata for conda package
              + ipython-0.13.1.tar.gz
                    + binstar metadata for pypi package
```

To work natively with package managers, binstar provides filters and translators in the form of sister sites (e.g. pypi.binstar.org and conda.binstar.org) Theses sister sites transform the package metadata into something the package manager expects:

So to install Ipython with `pip` I could do:

`pip install ipython --index-url https://pypi.binstar.org/sean`

OR, to install it with `conda` I could do:

`conda install ipython --channel https://conda.binstar.org/sean`

There is also another sister site `api.binstar.org` which provides the highest degree of control over all of these packages.

**Note:** There is also another level of package access control. The above example assumes that IPython is a publicly accessible package. binstar also has private packages. The procedure to install a private package is:

``` bash
TOKEN=$(binstar auth --create -n 'my conda deployment token' --resource 'conda:**')
conda install ipython --channel https://$TOKEN@conda.binstar.org/sean
```
#### Implementation: Refactoring Conda to take advantage of binstar:

I would propose that conda be divided in to the following 4 composable modules, just like compiler commands are composed of multiple commands. If these commands are _composable_ then we can do a refactor first without changing anything and then modifying the components to suit our needs:
1. Fetch package metadata and package dependency tree
2. Compute actions
3. Fetch packages into cache
4. Apply actions
##### Fetch package metadata and package dependency tree

This one is pretty simple, but for binstar, the dependency tree may be different if a 
user is logged in or not. For binstar, this includes all 'types' of packages like pypi or conda.
##### Compute actions

This module would take the metadata combined with metadata of currently installed packages and output a manifest describing (step by step) exactly what needs to be done on this environment.

For example a manifest may look something like:

```
CONDA: uninstall $CACHE/sean/ipython-0.13.1-py26_1.tar.bz2
CONDA: install   $CACHE/sean/ipython-1.0.1-py26_1.tar.bz2
PYPI:  install   $CACHE/ilan/flask-0.9.0.tar.gz
```

This would specify the actual paths of the files to be installed and would ignore all dependancies. (the execution order matters)
##### Fetch packages into cache

Because some of the packages may be private, the installers should not have to fetch the packages into the cache. this should be done first 
##### Apply actions

Apply each command in the manifest in order. choosing the correct installer and running that command
(Let me know if this is clear)

cc @teoliphant @ilanschnell @ijstokes @joelhullcio

**Comment by mforbes** [comment]
Could someone in the know suggest current best practices to deal with Sean's original problem?  It is very challenging for new users to figure out what the best strategy is.  My guess:

1. First, add some extra channels and see if that helps:

   ```bash
conda config --append channels condo-forge
conda config --append channels pipy               # Is this trustworthy/safe?
```
2.  If that fails, consider adding your missing project to [conda-forge](https://conda-forge.github.io).
3. If it is not worth it, then fall back to `pip` until this issue is resolve.

**Comment by mcg1969** [comment]
@kalefranz should this issue remain open? I don't think we really intend to meet the ambitious goals Sean has laid out here, and I'm wonder if the conda ecosystem has evolved to the point where it is less necessary. Perhaps a targeted pip fallback capability would be worth considering.

**Comment by ilanschnell** [comment]
IMHO, this should definitely be closed.  Conda is conda and pip is pip.  Conda cannot (and should not) be the package manager for everything.  Conda's success is because conda is simple and focused.

**Comment by mforbes** [comment]
If closing, please consider providing a suggestion or link to a description of the best practice/strategy for dealing with the original issue.

**Comment by kalefranz** [comment]
Now that conda-build is producing wheels, I've proposed https://github.com/conda/conda/issues/5202.  To the best of my knowledge, the conversion between wheels and conda packages is some simple metadata translation and directory translation.

I think it's safe to close this issue in lieu of #5202.
