### ISSUE TITLE
conda should prefer the latest version from the request channel

### ISSUE THREAD

**Issue by brendancol** [conda/conda#2921]
Scenario:

hypothetical package call `pyconstants`.

`bcollins` channel has pyconstants 0.0.2 and 0.0.1
`dmertz` channel has pyconstants 0.0.1

`dmertz` installs `conda install -c bcollins pyconstants` and gets 0.0.2
`dmertz` decides he doesn't trust `bcollins` and runs `conda install -c dmertz pyconstants`

right now this says "pyconstants" already installed, instead of automatically using the latest version from `dmertz` which is `0.0.1`

**Comment by mcg1969** [comment]
What version of conda are you running? We actually do this in conda 4.1.x.

**Comment by brendancol** [comment]
ah ok cool, `4.0.9`
