### ISSUE TITLE
clone error in 4.1.x

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2925]
This is being detected right now if 4.1.x.  I've finally figured out it's a real issue.

Ilan must have removed `linux-64/python-3.5.1-1` from defaults, because there is now only `linux-64/python-3.5.1-5`.  It happened in the last few days, and it's now exposing this bug.

Before Ilan changed that package, both defaults and conda-forge were at build 1.  Now defaults is `python-3.5.1-5` while conda-forge is still `python-3.5.1-1`.

    =================================== FAILURES ===================================
    _____________ IntegrationTests.test_dash_c_usage_replacing_python ______________
    Traceback (most recent call last):
      File "/home/travis/build/conda/conda/tests/test_create.py", line 357, in test_dash_c_usage_replacing_python
        with make_temp_env("--clone", prefix) as clone_prefix:
      File "/home/travis/miniconda/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/travis/build/conda/conda/tests/test_create.py", line 131, in make_temp_env
        run_command(Commands.CREATE, prefix, *packages)
      File "/home/travis/build/conda/conda/tests/test_create.py", line 115, in run_command
        args.func(args, p)
      File "/home/travis/build/conda/conda/conda/cli/main_create.py", line 57, in execute
        install(args, parser, 'create')
      File "/home/travis/build/conda/conda/conda/cli/install.py", line 218, in install
        'unknown': args.unknown})
      File "/home/travis/build/conda/conda/conda/cli/install.py", line 87, in clone
        fetch_args=fetch_args)
      File "/home/travis/build/conda/conda/conda/misc.py", line 306, in clone_env
        raise RuntimeError(msg)
    RuntimeError: Package  missing in current linux-64 channels: - python-3.5.1-1.tar.bz2
    ----------------------------- Captured stdout call -----------------------------

**Comment by mcg1969** [comment]
Why is this a bug exactly? Cloning doesn't substitute across channels...

**Comment by kalefranz** [comment]
Aha! You're right!  And the test (again) is wrong!  (But that's ok too :))

line 357 was

    with make_temp_env("--clone", prefix) as clone_prefix:

but needs to be

    with make_temp_env("--clone", prefix, "-c conda-forge") as clone_prefix:

I guess we should also fully exercise the offline part of clone too, at some point. Except I don't think we can do that until we stop clobbering things in the package cache.

**Comment by kalefranz** [comment]
Actually, I'm wrong.  We need to discard `build_number` from the second part of the test.  Except I'm wondering what might blow up when we do.

**Comment by kalefranz** [comment]
line 350

    for field in ('url', 'channel', 'schannel', 'build_number'):

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/2926

**Comment by mcg1969** [comment]
Whoa, we shouldn't be discarding build number there. Why are you saying it's necessary?

**Comment by mcg1969** [comment]
OK, I've finally figured out what's going on. I think that adding `-c conda-forge` to the final clone should have fixed it. The reason it is not, I think, is that the cloning code isn't seeing the additional channels supplied on the command line---it is only considering the channels listed in `.condarc`. Adding `conda-forge` to my `.condarc` fixed the problem. So this is a bug, but not quite what we thought it was.

**Comment by kalefranz** [comment]
closed with #2937
