### ISSUE TITLE
Help building XGBoost package for Python 3.5

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2935]
Hi team, I have tried to build the XGBoost package using a recipe I snagged from @aterrel on Anaconda Cloud.  But I have failed.  Attached are the build script and the meta.yaml. I have a commercial request for this package.  I imagine it is in the build script, but this is out of my depth to solve.

[xgboost_conda_recipe.zip](https://github.com/conda/conda/files/341772/xgboost_conda_recipe.zip)

**Comment by aterrel** [comment]
yeah xgboost changed the way they install over the last release. I had an updated version, the script installs fine from bash but doesn't from `conda build`. I can try to dig it up and post.

**Comment by ijstokes** [comment]
OK, GCC version issue.  I've managed to build it using gcc 4.8.2 on CentOS 6.7 by installing it using the technique described here:

http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos

I'm wondering/worried about whether this is going to lead to compatibility issues with the Conda package if it is deployed on a CentOS 6.7 system.  GLIBC errors?  I don't know about these things, but if someone is able to provide some advice I'd appreciate it. TIA!

**Comment by ijstokes** [comment]
@aterrel I pulled the build script from your latest Conda package here:

https://anaconda.org/aterrel/xgboost/files

If you have something newer than that, it would be great, but once I upgraded GCC from 4.4 to 4.8 it built OK for me.  The one piece I added to your `build.sh` (no idea if this was necessary) was:

    git submodule update --init --recursive

right at the top.

**Comment by aterrel** [comment]
That looks like the files I have. I remember it worked for me on linux fine.

**Comment by mingwandroid** [comment]
Hi @ijstokes, we have our own GCC 4.8.5 packages that have been built on CentOS 5.11.

If you add `gcc` as a build requirement and `libgcc` as a run requirement then your packages should be binary compatible with everything we support.

**Comment by ijstokes** [comment]
@mingwandroid thanks for the tip.  I have re-built my XGBoost packages with those additions to my `meta.yaml` Conda recipe.

https://anaconda.org/ijstokes/xgboost
