### ISSUE TITLE
conda update --all bottleneck issue

### ISSUE THREAD

**Issue by thecpshah** [conda/conda#2948]
Hello All,

The information about current `conda` installation is as below:

             platform : osx-64
        conda version : 4.1.5
    conda-env version : 2.5.1
    conda-build version : 0+unknown
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /Users/chintanshah/anaconda  (writable)
    default environment : /Users/chintanshah/anaconda
     envs directories : /Users/chintanshah/anaconda/envs
        package cache : /Users/chintanshah/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

When I try `conda update --all` I get the following message:

    Fetching package metadata .......
    Solving package specifications: ....

    The following specifications were found to be in conflict:
    - bottleneck -> numpy 1.10*|1.11*|1.9*
    - bottleneck -> python 3.4*|3.5*
    - sockjs-tornado
    Use "conda info <package>" to see the dependencies for each package.

It seems I need to reinstall Anaconda but I do not want to mess it up. Also, I am currently using `ZSH` instead of `bash`.

What would be the best to resolve this?

Yesterday, I installed the following:

    pip install Plotly
    pip install keras
    conda install opencv
    pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

**Comment by mcg1969** [comment]
Can you provide a full output of `conda list`? It looks like there may be some Python 3 package mixed up in your Python 2 environment.

**Comment by thecpshah** [comment]
Thank you for the reply. Here is the output of `conda list`

`#packages in environment at /Users/chintanshah/anaconda:
#
abstract-rendering        0.5.1               np110py27_0
alabaster                 0.7.7                    py27_0
anaconda                  4.0.0               np110py27_0
anaconda-client           1.4.0                    py27_0
anaconda-navigator        1.1.0                    py27_0
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               1.0.0                    py27_1
astropy                   1.1.2               np110py27_0
babel                     2.2.0                    py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bitarray                  0.8.1                    py27_0
blaze                     0.9.1                    py27_0
blaze-core                0.9.0                    py27_0
bokeh                     0.11.1                   py27_0
boto                      2.39.0                   py27_0
bottleneck                1.0.0               np110py27_0
cdecimal                  2.3                      py27_0
cffi                      1.5.2                    py27_0
chest                     0.2.3                    py27_0
cloudpickle               0.1.1                    py27_0
clyent                    1.2.1                    py27_0
colorama                  0.3.7                    py27_0
conda                     4.1.5                    py27_0
conda-build               1.20.0                   py27_0
conda-env                 2.5.1                    py27_0
conda-manager             0.3.1                    py27_0
configobj                 5.0.6                    py27_0
coursera                  0.5.2                     <pip>
cryptography              1.3                      py27_0
curl                      7.45.0                        0
cycler                    0.10.0                   py27_0
cython                    0.23.4                   py27_1
cytoolz                   0.7.5                    py27_0
dask                      0.8.1                    py27_0
datashape                 0.5.1                    py27_0
decorator                 4.0.9                    py27_0
dill                      0.2.4                    py27_0
docutils                  0.12                     py27_0
dynd-python               0.7.2                    py27_0
enum34                    1.1.2                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
flask-cors                2.1.2                    py27_0
freetype                  2.5.5                         0
funcsigs                  0.4                      py27_0
futures                   3.0.3                    py27_0
gevent                    1.1.0                    py27_0
gevent-websocket          0.9.5                    py27_1
greenlet                  0.4.9                    py27_0
grin                      1.2.1                    py27_1
h5py                      2.5.0               np110py27_4
hdf5                      1.8.15.1                      2
heapdict                  1.0.0                    py27_0
html5lib                  1.0b8                     <pip>
idna                      2.0                      py27_0
ipaddress                 1.0.14                   py27_0
ipdb                      0.9.0                     <pip>
ipykernel                 4.3.1                    py27_0
ipython                   4.1.2                    py27_1
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.2                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
joblib                    0.9.4                     <pip>
jpeg                      8d                            1
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_2
jupyter_client            4.2.2                    py27_0
jupyter_console           4.1.1                    py27_0
jupyter_core              4.1.0                    py27_0
Keras                     1.0.5                     <pip>
keyring                   9.0                       <pip>
launcher                  1.0.0                         3
libdynd                   0.7.2                         0
libpng                    1.6.17                        0
libtiff                   4.0.6                         1
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvmlite                  0.9.0                    py27_0
locket                    0.2.0                    py27_0
lxml                      3.6.0                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.5.1               np110py27_0
mistune                   0.7.2                    py27_1
mkl                       11.3.1                        0
mkl-service               1.1.2                    py27_0
mpmath                    0.19                     py27_0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.1.0                    py27_0
nbformat                  4.0.1                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2                      py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_0
notebook                  4.1.0                    py27_2
numba                     0.24.0              np110py27_0
numexpr                   2.5                 np110py27_0
numpy                     1.10.4                   py27_0
numpy                     1.11.1                    <pip>
odo                       0.4.2                    py27_0
opencv                    2.4.8                np17py27_2
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2g                        0
pandas                    0.18.0              np110py27_0
pandas                    0.18.1                    <pip>
partd                     0.3.2                    py27_1
path.py                   8.1.2                    py27_1
patsy                     0.4.0               np110py27_0
pep8                      1.7.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.5                      py27_0
pillow                    3.1.1                    py27_0
pip                       8.1.1                    py27_1
pip                       8.1.2                     <pip>
plotly                    1.12.2                    <pip>
ply                       3.8                      py27_0
progressbar               2.3                       <pip>
psutil                    4.1.0                    py27_1
ptyprocess                0.5                      py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.3                 py27_0
pyflakes                  1.1.0                    py27_0
pygments                  2.1.1                    py27_0
pyopenssl                 0.15.1                   py27_2
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_1
pytables                  3.2.2               np110py27_1
pytest                    2.8.5                    py27_0
python                    2.7.11                        0
python-dateutil           2.5.1                    py27_0
python-dateutil           2.5.3                     <pip>
python.app                1.2                      py27_4
pytz                      2016.2                   py27_0
pytz                      2016.4                    <pip>
pyyaml                    3.11                     py27_1
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                         1
qtawesome                 0.3.2                    py27_0
qtconsole                 4.2.0                    py27_0
qtpy                      1.0                      py27_0
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.9.1                    py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.7                   py27_0
scikit-image              0.12.3              np110py27_0
scikit-learn              0.17.1              np110py27_0
scipy                     0.17.0              np110py27_0
scipy                     0.17.1                    <pip>
seaborn                   0.6.0                     <pip>
setuptools                20.3                     py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.5                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    2.3.8                    py27_1
spyder-app                2.3.8                    py27_0
sqlalchemy                1.0.12                   py27_0
sqlite                    3.9.2                         0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1               np110py27_0
sympy                     1.0                      py27_0
terminado                 0.5                      py27_1
Theano                    0.9.0.dev1                <pip>
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.2.1                    py27_0
ujson                     1.35                     py27_0
unicodecsv                0.14.1                   py27_0
urllib3                   1.16                      <pip>
werkzeug                  0.11.4                   py27_0
wheel                     0.29.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.8.4                    py27_0
xlwings                   0.7.0                    py27_0
xlwt                      1.0.0                    py27_0
xz                        5.0.5                         1
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         0`

**Comment by mcg1969** [comment]
I see a lot of duplicated packages there, one from Conda and one from Pip. I don't think that's necessarily the specific problem here, but I cannot help but think that is going to cause you issues down the road.

**Comment by thecpshah** [comment]
Thank you for your reply. Here is the output of `conda list`
    #packages in environment at /Users/chintanshah/anaconda:
    #
    abstract-rendering        0.5.1               np110py27_0
    alabaster                 0.7.7                    py27_0
    anaconda                  4.0.0               np110py27_0
    anaconda-client           1.4.0                    py27_0
    anaconda-navigator        1.1.0                    py27_0
    appnope                   0.1.0                    py27_0
    appscript                 1.0.1                    py27_0
    argcomplete               1.0.0                    py27_1
    astropy                   1.1.2               np110py27_0
    babel                     2.2.0                    py27_0
    backports_abc             0.4                      py27_0
    beautifulsoup4            4.4.1                    py27_0
    bitarray                  0.8.1                    py27_0
    blaze                     0.9.1                    py27_0
    blaze-core                0.9.0                    py27_0
    bokeh                     0.11.1                   py27_0
    boto                      2.39.0                   py27_0
    bottleneck                1.0.0               np110py27_0
    cdecimal                  2.3                      py27_0
    cffi                      1.5.2                    py27_0
    chest                     0.2.3                    py27_0
    cloudpickle               0.1.1                    py27_0
    clyent                    1.2.1                    py27_0
    colorama                  0.3.7                    py27_0
    conda                     4.1.5                    py27_0
    conda-build               1.20.0                   py27_0
    conda-env                 2.5.1                    py27_0
    conda-manager             0.3.1                    py27_0
    configobj                 5.0.6                    py27_0
    coursera                  0.5.2                     <pip>
    cryptography              1.3                      py27_0
    curl                      7.45.0                        0
    cycler                    0.10.0                   py27_0
    cython                    0.23.4                   py27_1
    cytoolz                   0.7.5                    py27_0
    dask                      0.8.1                    py27_0
    datashape                 0.5.1                    py27_0
    decorator                 4.0.9                    py27_0
    dill                      0.2.4                    py27_0
    docutils                  0.12                     py27_0
    dynd-python               0.7.2                    py27_0
    enum34                    1.1.2                    py27_0
    et_xmlfile                1.0.1                    py27_0
    fastcache                 1.0.2                    py27_0
    flask                     0.10.1                   py27_1
    flask-cors                2.1.2                    py27_0
    freetype                  2.5.5                         0
    funcsigs                  0.4                      py27_0
    futures                   3.0.3                    py27_0
    gevent                    1.1.0                    py27_0
    gevent-websocket          0.9.5                    py27_1
    greenlet                  0.4.9                    py27_0
    grin                      1.2.1                    py27_1
    h5py                      2.5.0               np110py27_4
    hdf5                      1.8.15.1                      2
    heapdict                  1.0.0                    py27_0
    html5lib                  1.0b8                     <pip>
    idna                      2.0                      py27_0
    ipaddress                 1.0.14                   py27_0
    ipdb                      0.9.0                     <pip>
    ipykernel                 4.3.1                    py27_0
    ipython                   4.1.2                    py27_1
    ipython-notebook          4.0.4                    py27_0
    ipython-qtconsole         4.0.1                    py27_0
    ipython_genutils          0.1.0                    py27_0
    ipywidgets                4.1.1                    py27_0
    itsdangerous              0.24                     py27_0
    jbig                      2.1                           0
    jdcal                     1.2                      py27_0
    jedi                      0.9.0                    py27_0
    jinja2                    2.8                      py27_0
    joblib                    0.9.4                     <pip>
    jpeg                      8d                            1
    jsonschema                2.4.0                    py27_0
    jupyter                   1.0.0                    py27_2
    jupyter_client            4.2.2                    py27_0
    jupyter_console           4.1.1                    py27_0
    jupyter_core              4.1.0                    py27_0
    Keras                     1.0.5                     <pip>
    keyring                   9.0                       <pip>
    launcher                  1.0.0                         3
    libdynd                   0.7.2                         0
    libpng                    1.6.17                        0
    libtiff                   4.0.6                         1
    libxml2                   2.9.2                         0
    libxslt                   1.1.28                        2
    llvmlite                  0.9.0                    py27_0
    locket                    0.2.0                    py27_0
    lxml                      3.6.0                    py27_0
    markupsafe                0.23                     py27_0
    matplotlib                1.5.1               np110py27_0
    mistune                   0.7.2                    py27_1
    mkl                       11.3.1                        0
    mkl-service               1.1.2                    py27_0
    mpmath                    0.19                     py27_0
    multipledispatch          0.4.8                    py27_0
    nbconvert                 4.1.0                    py27_0
    nbformat                  4.0.1                    py27_0
    networkx                  1.11                     py27_0
    nltk                      3.2                      py27_0
    node-webkit               0.10.1                        0
    nose                      1.3.7                    py27_0
    notebook                  4.1.0                    py27_2
    numba                     0.24.0              np110py27_0
    numexpr                   2.5                 np110py27_0
    numpy                     1.10.4                   py27_0
    numpy                     1.11.1                    <pip>
    odo                       0.4.2                    py27_0
    opencv                    2.4.8                np17py27_2
    openpyxl                  2.3.2                    py27_0
    openssl                   1.0.2g                        0
    pandas                    0.18.0              np110py27_0
    pandas                    0.18.1                    <pip>
    partd                     0.3.2                    py27_1
    path.py                   8.1.2                    py27_1
    patsy                     0.4.0               np110py27_0
    pep8                      1.7.0                    py27_0
    pexpect                   4.0.1                    py27_0
    pickleshare               0.5                      py27_0
    pillow                    3.1.1                    py27_0
    pip                       8.1.1                    py27_1
    pip                       8.1.2                     <pip>
    plotly                    1.12.2                    <pip>
    ply                       3.8                      py27_0
    progressbar               2.3                       <pip>
    psutil                    4.1.0                    py27_1
    ptyprocess                0.5                      py27_0
    py                        1.4.31                   py27_0
    pyasn1                    0.1.9                    py27_0
    pyaudio                   0.2.7                    py27_0
    pycosat                   0.6.1                    py27_0
    pycparser                 2.14                     py27_0
    pycrypto                  2.6.1                    py27_0
    pycurl                    7.19.5.3                 py27_0
    pyflakes                  1.1.0                    py27_0
    pygments                  2.1.1                    py27_0
    pyopenssl                 0.15.1                   py27_2
    pyparsing                 2.0.3                    py27_0
    pyqt                      4.11.4                   py27_1
    pytables                  3.2.2               np110py27_1
    pytest                    2.8.5                    py27_0
    python                    2.7.11                        0
    python-dateutil           2.5.1                    py27_0
    python-dateutil           2.5.3                     <pip>
    python.app                1.2                      py27_4
    pytz                      2016.2                   py27_0
    pytz                      2016.4                    <pip>
    pyyaml                    3.11                     py27_1
    pyzmq                     15.2.0                   py27_0
    qt                        4.8.7                         1
    qtawesome                 0.3.2                    py27_0
    qtconsole                 4.2.0                    py27_0
    qtpy                      1.0                      py27_0
    readline                  6.2                           2
    redis                     2.6.9                         0
    redis-py                  2.10.3                   py27_0
    requests                  2.9.1                    py27_0
    rope                      0.9.4                    py27_1
    ruamel_yaml               0.11.7                   py27_0
    scikit-image              0.12.3              np110py27_0
    scikit-learn              0.17.1              np110py27_0
    scipy                     0.17.0              np110py27_0
	scipy                     0.17.1                    <pip>
	seaborn                   0.6.0                     <pip>
	setuptools                20.3                     py27_0
	simplegeneric             0.8.1                    py27_0
	singledispatch            3.4.0.3                  py27_0
	sip                       4.16.9                   py27_0
	six                       1.10.0                   py27_0
	snowballstemmer           1.2.1                    py27_0
	sockjs-tornado            1.0.1                    py27_0
	sphinx                    1.3.5                    py27_0
	sphinx_rtd_theme          0.1.9                    py27_0
	spyder                    2.3.8                    py27_1
	spyder-app                2.3.8                    py27_0
	sqlalchemy                1.0.12                   py27_0
	sqlite                    3.9.2                         0
	ssl_match_hostname        3.4.0.2                  py27_0
	statsmodels               0.6.1               np110py27_0
	sympy                     1.0                      py27_0
	terminado                 0.5                      py27_1
	Theano                    0.9.0.dev1                <pip>
	tk                        8.5.18                        0
	toolz                     0.7.4                    py27_0
	tornado                   4.3                      py27_0
	traitlets                 4.2.1                    py27_0
	ujson                     1.35                     py27_0
	unicodecsv                0.14.1                   py27_0
	urllib3                   1.16                      <pip>
	werkzeug                  0.11.4                   py27_0
	wheel                     0.29.0                   py27_0
	xlrd                      0.9.4                    py27_0
	xlsxwriter                0.8.4                    py27_0
	xlwings                   0.7.0                    py27_0
	xlwt                      1.0.0                    py27_0
	xz                        5.0.5                         1
	yaml                      0.1.6                         0
	zeromq                    4.1.3                         0
	zlib                      1.2.8                         0

**Comment by thecpshah** [comment]
#packages in environment at /Users/chintanshah/anaconda:
    #
    abstract-rendering        0.5.1               np110py27_0
    alabaster                 0.7.7                    py27_0
    anaconda                  4.0.0               np110py27_0
    anaconda-client           1.4.0                    py27_0
    anaconda-navigator        1.1.0                    py27_0
    appnope                   0.1.0                    py27_0
    appscript                 1.0.1                    py27_0
    argcomplete               1.0.0                    py27_1
    astropy                   1.1.2               np110py27_0
    babel                     2.2.0                    py27_0
    backports_abc             0.4                      py27_0
    beautifulsoup4            4.4.1                    py27_0
    bitarray                  0.8.1                    py27_0
    blaze                     0.9.1                    py27_0
    blaze-core                0.9.0                    py27_0
    bokeh                     0.11.1                   py27_0
    boto                      2.39.0                   py27_0
    bottleneck                1.0.0               np110py27_0
    cdecimal                  2.3                      py27_0
    cffi                      1.5.2                    py27_0
    chest                     0.2.3                    py27_0
    cloudpickle               0.1.1                    py27_0
    clyent                    1.2.1                    py27_0
    colorama                  0.3.7                    py27_0
    conda                     4.1.5                    py27_0
    conda-build               1.20.0                   py27_0
    conda-env                 2.5.1                    py27_0
    conda-manager             0.3.1                    py27_0
    configobj                 5.0.6                    py27_0
    coursera                  0.5.2                     <pip>
    cryptography              1.3                      py27_0
    curl                      7.45.0                        0
    cycler                    0.10.0                   py27_0
    cython                    0.23.4                   py27_1
    cytoolz                   0.7.5                    py27_0
    dask                      0.8.1                    py27_0
    datashape                 0.5.1                    py27_0
    decorator                 4.0.9                    py27_0
    dill                      0.2.4                    py27_0
    docutils                  0.12                     py27_0
    dynd-python               0.7.2                    py27_0
    enum34                    1.1.2                    py27_0
    et_xmlfile                1.0.1                    py27_0
    fastcache                 1.0.2                    py27_0
    flask                     0.10.1                   py27_1
    flask-cors                2.1.2                    py27_0
    freetype                  2.5.5                         0
    funcsigs                  0.4                      py27_0
    futures                   3.0.3                    py27_0
    gevent                    1.1.0                    py27_0
    gevent-websocket          0.9.5                    py27_1
    greenlet                  0.4.9                    py27_0
    grin                      1.2.1                    py27_1
    h5py                      2.5.0               np110py27_4
    hdf5                      1.8.15.1                      2
    heapdict                  1.0.0                    py27_0
    html5lib                  1.0b8                     <pip>
    idna                      2.0                      py27_0
    ipaddress                 1.0.14                   py27_0
    ipdb                      0.9.0                     <pip>
    ipykernel                 4.3.1                    py27_0
    ipython                   4.1.2                    py27_1
    ipython-notebook          4.0.4                    py27_0
    ipython-qtconsole         4.0.1                    py27_0
    ipython_genutils          0.1.0                    py27_0
    ipywidgets                4.1.1                    py27_0
    itsdangerous              0.24                     py27_0
    jbig                      2.1                           0
    jdcal                     1.2                      py27_0
    jedi                      0.9.0                    py27_0
    jinja2                    2.8                      py27_0
    joblib                    0.9.4                     <pip>
    jpeg                      8d                            1
    jsonschema                2.4.0                    py27_0
    jupyter                   1.0.0                    py27_2
    jupyter_client            4.2.2                    py27_0
    jupyter_console           4.1.1                    py27_0
    jupyter_core              4.1.0                    py27_0
    Keras                     1.0.5                     <pip>
    keyring                   9.0                       <pip>
    launcher                  1.0.0                         3
    libdynd                   0.7.2                         0
    libpng                    1.6.17                        0
    libtiff                   4.0.6                         1
    libxml2                   2.9.2                         0
    libxslt                   1.1.28                        2
    llvmlite                  0.9.0                    py27_0
    locket                    0.2.0                    py27_0
    lxml                      3.6.0                    py27_0
    markupsafe                0.23                     py27_0
    matplotlib                1.5.1               np110py27_0
    mistune                   0.7.2                    py27_1
    mkl                       11.3.1                        0
    mkl-service               1.1.2                    py27_0
    mpmath                    0.19                     py27_0
    multipledispatch          0.4.8                    py27_0
    nbconvert                 4.1.0                    py27_0
    nbformat                  4.0.1                    py27_0
    networkx                  1.11                     py27_0
    nltk                      3.2                      py27_0
    node-webkit               0.10.1                        0
    nose                      1.3.7                    py27_0
    notebook                  4.1.0                    py27_2
    numba                     0.24.0              np110py27_0
    numexpr                   2.5                 np110py27_0
    numpy                     1.10.4                   py27_0
    numpy                     1.11.1                    <pip>
    odo                       0.4.2                    py27_0
    opencv                    2.4.8                np17py27_2
    openpyxl                  2.3.2                    py27_0
    openssl                   1.0.2g                        0
    pandas                    0.18.0              np110py27_0
    pandas                    0.18.1                    <pip>
    partd                     0.3.2                    py27_1
    path.py                   8.1.2                    py27_1
    patsy                     0.4.0               np110py27_0
    pep8                      1.7.0                    py27_0
    pexpect                   4.0.1                    py27_0
    pickleshare               0.5                      py27_0
    pillow                    3.1.1                    py27_0
    pip                       8.1.1                    py27_1
    pip                       8.1.2                     <pip>
    plotly                    1.12.2                    <pip>
    ply                       3.8                      py27_0
    progressbar               2.3                       <pip>
    psutil                    4.1.0                    py27_1
    ptyprocess                0.5                      py27_0
    py                        1.4.31                   py27_0
    pyasn1                    0.1.9                    py27_0
    pyaudio                   0.2.7                    py27_0
    pycosat                   0.6.1                    py27_0
    pycparser                 2.14                     py27_0
    pycrypto                  2.6.1                    py27_0
    pycurl                    7.19.5.3                 py27_0
    pyflakes                  1.1.0                    py27_0
    pygments                  2.1.1                    py27_0
    pyopenssl                 0.15.1                   py27_2
    pyparsing                 2.0.3                    py27_0
    pyqt                      4.11.4                   py27_1
    pytables                  3.2.2               np110py27_1
    pytest                    2.8.5                    py27_0
    python                    2.7.11                        0
    python-dateutil           2.5.1                    py27_0
    python-dateutil           2.5.3                     <pip>
    python.app                1.2                      py27_4
    pytz                      2016.2                   py27_0
    pytz                      2016.4                    <pip>
    pyyaml                    3.11                     py27_1
    pyzmq                     15.2.0                   py27_0
    qt                        4.8.7                         1
    qtawesome                 0.3.2                    py27_0
    qtconsole                 4.2.0                    py27_0
    qtpy                      1.0                      py27_0
    readline                  6.2                           2
    redis                     2.6.9                         0
    redis-py                  2.10.3                   py27_0
    requests                  2.9.1                    py27_0
    rope                      0.9.4                    py27_1
    ruamel_yaml               0.11.7                   py27_0
    scikit-image              0.12.3              np110py27_0
    scikit-learn              0.17.1              np110py27_0
    scipy                     0.17.0              np110py27_0
	scipy                     0.17.1                    <pip>
	seaborn                   0.6.0                     <pip>
	setuptools                20.3                     py27_0
	simplegeneric             0.8.1                    py27_0
	singledispatch            3.4.0.3                  py27_0
	sip                       4.16.9                   py27_0
	six                       1.10.0                   py27_0
	snowballstemmer           1.2.1                    py27_0
	sockjs-tornado            1.0.1                    py27_0
	sphinx                    1.3.5                    py27_0
	sphinx_rtd_theme          0.1.9                    py27_0
	spyder                    2.3.8                    py27_1
	spyder-app                2.3.8                    py27_0
	sqlalchemy                1.0.12                   py27_0
	sqlite                    3.9.2                         0
	ssl_match_hostname        3.4.0.2                  py27_0
	statsmodels               0.6.1               np110py27_0
	sympy                     1.0                      py27_0
	terminado                 0.5                      py27_1
	Theano                    0.9.0.dev1                <pip>
	tk                        8.5.18                        0
	toolz                     0.7.4                    py27_0
	tornado                   4.3                      py27_0
	traitlets                 4.2.1                    py27_0
	ujson                     1.35                     py27_0
	unicodecsv                0.14.1                   py27_0
	urllib3                   1.16                      <pip>
	werkzeug                  0.11.4                   py27_0
	wheel                     0.29.0                   py27_0
	xlrd                      0.9.4                    py27_0
	xlsxwriter                0.8.4                    py27_0
	xlwings                   0.7.0                    py27_0
	xlwt                      1.0.0                    py27_0
	xz                        5.0.5                         1
	yaml                      0.1.6                         0
	zeromq                    4.1.3                         0
	zlib                      1.2.8                         0

**Comment by thecpshah** [comment]
OK, but then why does not `conda update --all` does not work? Should I reinstall? And what would be the best way to do it?

**Comment by mcg1969** [comment]
I honestly do not know the source of the conflict in `conda update --all`, I'm afraid. Reinstalling should certainly help, with any `conda` upgrades completed _before_ you start installing packages with pip. Furthermore, I would _not_ use pip to install packages that are already in the environment; if you need to do that, `conda remove` them first.

**Comment by thecpshah** [comment]
Ok. So in order to remove Anaconda, 

1. I just need to delete the directory and reinstall. 
2. Then do `conda update --all`
3. then install required packages (if they are not already installed)

Is this correct?

**Comment by mcg1969** [comment]
Is there a specific reason why you are determined to do `conda update --all`? I know it may seem intuitive to do so. But in fact, one of the points of the Anaconda distribution is that it provides a collection of packages that have been tested together. Think of it like a "stable" distribution versus the "bleeding edge" that you get with `conda update --all`.

Don't get me wrong---I'm not saying you _can't_ do it. And conda is supposed to work if you do. I just want you to question your assumption that you _should_ do it.

Another alternative is to do `conda update anaconda`. This gives you the latest collection of Anaconda packages. It will look a lot like `conda update --all`, but again, it remains a set of packages tested together.

Finally: when installing additional packages, I would encourage you to use `conda` instead of `pip` whenever possible. Even if we don't have the package in our `default` channel, it's possible that other Anaconda Cloud users have built conda packages for the very packages you are interested in. You can use the command 

`anaconda search -t conda `_\<package\>_

to look for these. I think you'll find options for just about all of the packages you're interested in. If you consider them suitable, you can 

`conda install -c `_\<user\>_` `_\<package\>_

to install them, where _\<user\>_ is the name of the account where the package was found.

Otherwise, yes, the order of operations is good.

**Comment by mcg1969** [comment]
I'm glad I could help! I'm sorry for the trouble you've been having. If it's OK with you I'm going to close this issue. Feel free to open a new one if you experience problems with the new environment.
