### ISSUE TITLE
source activate gives Error: did not expect more than one argument

### ISSUE THREAD

**Issue by benrifkind** [conda/conda#2965]
Running `source activate environment` gives - Error: did not expect more than one argument.

The issues seems to be with the activate (https://github.com/conda/conda/blob/master/bin/activate) script. Specifically with the `$SHELL$EXT`
If I change line 53

```
 "$_CONDA_DIR/conda" ..checkenv $SHELL$EXT "$args" 
 "$_CONDA_DIR/conda" ..checkenv "$args"
```

and line 61

```
_NEW_PART=$("$_CONDA_DIR/conda" ..activate $SHELL$EXT "$args")
_NEW_PART=$("$_CONDA_DIR/conda" ..activate "$args") 
```

then everything (seems) to run OK. The $SHELL$EXT variable returns "bash" inside the script.

This is on a macbook pro running bash.

**Comment by biologyguy** [comment]
I confirm this behaviour on a Mac Pro, OS X 10.11.5

**Comment by duckontheweb** [comment]
I am also seeing the same behavior on a Macbook Pro, OSX 10.11.6

**Comment by kalefranz** [comment]
What versions of conda?  `conda info`?

Latest conda version is 4.3.17.

**Comment by stevekm** [comment]
I am getting this behavior on CentOS 7 with `Miniconda3-4.5.4-Linux-x86_64.sh` installation

**Comment by tovrstra** [comment]
@kalefranz : can you re-open this issue? Thanks.

This is still a relevant issue with today's miniconda, on some machines. When the login shell is started with command-line arguments, the error `Error: did not expect more than one argument.` will appear and activate will fail.

If you encounter this issue, you can check the following. Open a new terminal and enter:

```
echo $@
```

If this returns a non-empty result, you can solve your problem by removing the `$@` from `miniconda3/bin/activate`. After than `source miniconda/bin/activate` will work. It may cause other problems, so use at your own risk.

**Comment by marcelotrevisani** [comment]
> I am getting this behavior on RHEL 7 with `Miniconda3-4.5.4-Linux-x86_64.sh` installation:
> 
> ```
> $ source conda/bin/activate
> activate does not accept more than one argument:
> ('gpfs', 'home', 'USR', '7.163G', '100G', '110G', '648M', 'none', '|', '163197', '40000', '3600000', '92', '88', 'days', 'hpc-pr2.ib')
> ```

Just for future reference
Instead of doing 
```
source conda/bin/activate
```
you can do
```
source conda/bin/activate base
```

and it will avoid those problems

**Comment by stevekm** [comment]
Yes it turned out that on the HPC system I was using, the admins had configured it to stash a bunch of items in `$@` variables for the login splash screen. I updated my `.bashrc` to unset `$1`, `$2`, etc, and that fixed it
