### ISSUE TITLE
Update docs for new keys on meta.yaml (about section)

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#2967]
There are some new keys available on the about section of the meta.yaml that do not appear on the [conda docs](http://conda.pydata.org/docs/building/meta-yaml.html#about-section)

`description`: Summary is a one liner, where as description is a longer (multiline) description.
`doc_url`: Documentation url (readthedocs etc....)
`dev_url`: Development url (github, bitbucket etc)

**Comment by kalefranz** [comment]
File under conda-build or conda-docs, if it's not already done 😜
