### ISSUE TITLE
Cannot Clone Env

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [conda/conda#2968]
I got the following output when tryting to clone an env:

cloning like this: `conda create --name coursera_ml_clustering_and_retrieval --clone coursera_ml_classification`

	Using Anaconda Cloud api site https://api.anaconda.org
	Fetching package metadata: ......
	src_prefix: '/home/xiaolong/development/anaconda3/envs/coursera_ml_classification'
	dst_prefix: '/home/xiaolong/development/anaconda3/envs/coursera_ml_clustering_and_retrieval'
	Packages: 86
	Files: 19419
	An unexpected error has occurred, please consider sending the
	following traceback to the conda GitHub issue tracker at:

		https://github.com/conda/conda/issues

	Include the output of the command 'conda info' in your report.

	Traceback (most recent call last):
	  File "/home/xiaolong/development/anaconda3/bin/conda", line 6, in <module>
		sys.exit(main())
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
		args_func(args, p)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
		args.func(args, p)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
		install.install(args, parser, 'create')
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 247, in install
		clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
		quiet=quiet, index=index)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 246, in clone_env
		sorted_dists = r.dependency_sort(dists)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 729, in dependency_sort
		depends = lookup(value)
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 724, in lookup
		return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
	  File "/home/xiaolong/development/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 573, in ms_depends
		deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
	KeyError: 'glib-2.43.0-2.tar.bz2'

And here is the `conda info` output:

	Using Anaconda Cloud api site https://api.anaconda.org
	Current conda install:

				 platform : linux-64
			conda version : 4.0.5
	  conda-build version : 1.20.1
		   python version : 3.5.1.final.0
		 requests version : 2.9.1
		 root environment : /home/xiaolong/development/anaconda3  (writable)
	  default environment : /home/xiaolong/development/anaconda3
		 envs directories : /home/xiaolong/development/anaconda3/envs
			package cache : /home/xiaolong/development/anaconda3/pkgs
			 channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
							https://repo.continuum.io/pkgs/free/noarch/
							https://repo.continuum.io/pkgs/pro/linux-64/
							https://repo.continuum.io/pkgs/pro/noarch/
							https://conda.anaconda.org/t/<TOKEN>/Zelphir/linux-64/
							https://conda.anaconda.org/t/<TOKEN>/Zelphir/noarch/
			  config file : /home/xiaolong/.condarc
		is foreign system : False

Other info:

* OS: Fedora 22

**Comment by mcg1969** [comment]
Can you please do `conda update conda` and try again?

**Comment by ZelphirKaltstahl** [comment]
I did that already and now again just to be sure and here is the output:

    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata .........
    # All requested packages already installed.
    # packages in environment at /home/xiaolong/development/anaconda3:
    #
    conda                     4.1.6                    py35_0    defaults

**Comment by mcg1969** [comment]
OK, but surely the output was different the second time. Your clone output from above was from 4.0.5, not 4.1.6. Can you share what happened the second time around?

**Comment by mcg1969** [comment]
Also, you do need to make sure that `conda` can find a conda package for `glib-2.43.0-2.tar.bz2`. That may mean adding some old channels back into your `.condarc`.

**Comment by ZelphirKaltstahl** [comment]
Hm now it worked. Maybe I had another environment activated at the time I tried without noticing? Could be. I guess we can close this now.

**Comment by mcg1969** [comment]
That's great. We've been working on the cloning capability in 4.1, so I was hopeful the latest update fixed it. Don't hesitate to open a new ticket if necessary.
