### ISSUE TITLE
Failure to deactivate environment from non-ascii local user install (Windows)

### ISSUE THREAD

**Issue by kmostachov** [conda/conda#2971]
4.1.6 version of Conda fails to deactivate environment under following sircumstances:

1) Win 10
2) Default local folder for environments is used, e.g.: C:\Users\Щзавря\Miniconda3\envs\
3) Username has non-ascii (in my case cyrillic) characters

See attached traceback screenshot

![image](https://cloud.githubusercontent.com/assets/20268475/16546302/daa7f024-414e-11e6-9bcf-6c28af8591cb.png)

**Comment by kmostachov** [comment]
Version 4.0.5 worked fine.
Global Conda install under ASCII path on D: worked fine even in 4.1.6

**Comment by mcg1969** [comment]
Thank you very much for the detail in your report! That will certainly help track it down.

**Comment by kalefranz** [comment]
Could you also provide the output of `conda info`?

**Comment by kmostachov** [comment]
Here is the output of 'conda info':
A lot of time has passed, but fortunately I haven't used conda much since then:

Current conda install:

               platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : D:\Soft\Conda  (writable)
  default environment : D:\Soft\Conda
     envs directories : D:\Soft\Conda\envs
        package cache : D:\Soft\Conda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
`conda update conda` please :)
