### ISSUE TITLE
Allow system-wide installation

### ISSUE THREAD

**Issue by cryzed** [conda/conda#2972]
Until recently it was possible to install Conda system-wide with a few tricks, at least on [Arch Linux](https://aur.archlinux.org/packages/anaconda/). Recent updates to the locking mechanism made this seemingly impossible -- when running the system-wide installed conda executable as a regular user, lock files were attempted to be created in a directory that the regular user didn't have write-access to.

After fixing this issue by using the latest version of [lock.py](https://github.com/conda/conda/blob/master/conda/lock.py#L69) which just fails silently, conda manages to create a new environment -- however when activating it, the first index in `sys.path` is empty and I assume a few others missing, because none point to the actual location of the created environment.

I am aware that this is technically not a bug, it's more of a feature-request -- since installing Conda locally, as intended, works. Would it be possible to make a few tweaks to Conda to allow such system-wide installations more easily or at all?

**Comment by bkreider** [comment]
I think this is a bug.  It's been reported in other issues i believe and is being worked on.

**Comment by cryzed** [comment]
Great to hear that :)!

**Comment by kalefranz** [comment]
Multi-user installs are fully supported as of conda 4.3.
