### ISSUE TITLE
Crash downloading packages Windows: Illegal filename created

### ISSUE THREAD

**Issue by thorsant** [conda/conda#2973]
Got this error while trying to download pyodbc:

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_fun
c
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in e
xecute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in insta
ll
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in FETCH
_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 369, in download
    with Locked(dst_dir):
  File "C:\Anaconda2\lib\site-packages\conda\lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax i
s incorrect: u'C:\Anaconda2\pkgs\http:'

Output from conda info:
Current conda install:

```
         platform : win-64
    conda version : 4.1.4
conda-env version : 2.5.1
```

  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\212550823.condarc
         offline mode : False
    is foreign system : False

**Comment by mcg1969** [comment]
I am unable to reproduce this. Does this occur consistently? If so, can you do the following things for us, please?

1. Give us the precise command you use to get this error
2. Run the same command with the `--debug` option right after `conda` (e.g., `conda --debug install`), and copy and paste that output here into a reply.
3. Try updating to `conda 4.1.6` and try again.

Thanks!

**Comment by thorsant** [comment]
1. conda install pyodbc

2:
DEBUG:conda.fetch:channel_urls=OrderedDict([('https://repo.continuum.io/pkgs/free/win-64/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/free/noarch/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/pro/win-64/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/pro/noarch/', ('defaults', 1))])
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO:stderrlog:SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO:stderrlog:SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO:stderrlog:SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

DEBUG:conda.fetch:SSL Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

INFO:stderrlog:SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

DEBUG:conda.fetch:SSL Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

DEBUG:conda.fetch:SSL Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

DEBUG:conda.fetch:SSL Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

..DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x000000000500E9E8>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000004FB9860>}
DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x000000000500E208>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000004FB94E0>}

INFO:stdoutlog:

DEBUG:conda.plan:H0 specs=['pyodbc']
DEBUG:conda.plan:H2 python True
DEBUG:conda.plan:H3 python
DEBUG:conda.plan:H2 lua False
DEBUG:conda.plan:H2A lua
DEBUG:conda.plan:HF specs=['pyodbc', u'python 2.7* (target=python-2.7.11-5.tar.bz2)']
DEBUG:conda.plan:Pinned specs=[]
DEBUG:conda.resolve:Checking satisfiability of current install
DEBUG:conda.resolve:Checking if the current environment is consistent
DEBUG:conda.resolve:Limiting solver to the following packages: wheel, menuinst, pyyaml, conda-env, python, pycosat, vs2008_runtime, conda, setuptools, pip, requests, ruamel_yaml
DEBUG:conda.resolve:Packages to be preserved: beautifulsoup4-4.4.1-py27_0.tar.bz2, enum34-1.1.6-py27_0.tar.bz2, mpmath-0.19-py27_1.tar.bz2, networkx-1.11-py27_0.tar.bz2, pyqt-4.11.4-py27_6.tar.bz2, nbformat-4.0.1-py27_0.tar.bz2, jsonschema-2.5.1-py27_0.tar.bz2, fastcache-1.0.2-py27_1.tar.bz2, multipledispatch-0.4.8-py27_0.tar.bz2, traitlets-4.2.1-py27_0.tar.bz2, et_xmlfile-1.0.1-py27_0.tar.bz2, libpng-1.6.22-vc9_0.tar.bz2, markupsafe-0.23-py27_2.tar.bz2, greenlet-0.4.10-py27_0.tar.bz2, jupyter_core-4.1.0-py27_0.tar.bz2, scikit-image-0.12.3-np111py27_1.tar.bz2, qt-4.8.7-vc9_8.tar.bz2, llvmlite-0.11.0-py27_0.tar.bz2, pyopenssl-0.16.0-py27_0.tar.bz2, ipython-4.2.0-py27_0.tar.bz2, mkl-service-1.1.2-py27_2.tar.bz2, lxml-3.6.0-py27_0.tar.bz2, cloudpickle-0.2.1-py27_0.tar.bz2, docutils-0.12-py27_2.tar.bz2, pyflakes-1.2.3-py27_0.tar.bz2, boto-2.40.0-py27_0.tar.bz2, locket-0.2.0-py27_1.tar.bz2, pycparser-2.14-py27_1.tar.bz2, itsdangerous-0.24-py27_0.tar.bz2, sphinx_rtd_theme-0.1.9-py27_0.tar.bz2, curl-7.49.0-vc9_0.tar.bz2, anaconda-4.1.0-np111py27_0.tar.bz2, jinja2-2.8-py27_1.tar.bz2, _nb_ext_conf-0.2.0-py27_0.tar.bz2, grin-1.2.1-py27_3.tar.bz2, numpy-1.11.0-py27_2.tar.bz2, cython-0.24-py27_0.tar.bz2, libtiff-4.0.6-vc9_2.tar.bz2, pandas-0.18.1-np111py27_0.tar.bz2, contextlib2-0.5.3-py27_0.tar.bz2, statsmodels-0.6.1-np111py27_1.tar.bz2, odo-0.5.0-py27_0.tar.bz2, patsy-0.4.1-py27_0.tar.bz2, numba-0.26.0-np111py27_0.tar.bz2, psutil-4.3.0-py27_0.tar.bz2, matplotlib-1.5.1-np111py27_0.tar.bz2, simplegeneric-0.8.1-py27_1.tar.bz2, xlwt-1.1.2-py27_0.tar.bz2, rope-0.9.4-py27_1.tar.bz2, py-1.4.31-py27_0.tar.bz2, ipywidgets-4.1.1-py27_0.tar.bz2, nbconvert-4.2.0-py27_0.tar.bz2, backports-1.0-py27_0.tar.bz2, partd-0.3.4-py27_0.tar.bz2, anaconda-client-1.4.0-py27_0.tar.bz2, conda-build-1.21.2-py27_0.tar.bz2, tornado-4.3-py27_1.tar.bz2, console_shortcut-0.1.1-py27_1.tar.bz2, ipaddress-1.0.16-py27_0.tar.bz2, comtypes-1.1.2-py27_0.tar.bz2, nb_conda_kernels-1.0.3-py27_0.tar.bz2, bzip2-1.0.6-vc9_3.tar.bz2, jedi-0.9.0-py27_1.tar.bz2, python-dateutil-2.5.3-py27_0.tar.bz2, ipython_genutils-0.1.0-py27_0.tar.bz2, pep8-1.7.0-py27_0.tar.bz2, alabaster-0.7.8-py27_0.tar.bz2, clyent-1.2.2-py27_0.tar.bz2, sympy-1.0-py27_0.tar.bz2, pycurl-7.43.0-py27_0.tar.bz2, zlib-1.2.8-vc9_3.tar.bz2, mistune-0.7.2-py27_0.tar.bz2, path.py-8.2.1-py27_0.tar.bz2, nose-1.3.7-py27_1.tar.bz2, nltk-3.2.1-py27_0.tar.bz2, pygments-2.1.3-py27_0.tar.bz2, cytoolz-0.8.0-py27_0.tar.bz2, jpeg-8d-vc9_0.tar.bz2, dill-0.2.5-py27_0.tar.bz2, bottleneck-1.0.0-np111py27_1.tar.bz2, bokeh-0.11.1-py27_0.tar.bz2, entrypoints-0.2.2-py27_0.tar.bz2, argcomplete-1.0.0-py27_1.tar.bz2, colorama-0.3.7-py27_0.tar.bz2, pytz-2016.4-py27_0.tar.bz2, snowballstemmer-1.2.1-py27_0.tar.bz2, decorator-4.0.10-py27_0.tar.bz2, imagesize-0.7.1-py27_0.tar.bz2, spyder-2.3.9-py27_0.tar.bz2, functools32-3.2.3.2-py27_0.tar.bz2, qtconsole-4.2.1-py27_0.tar.bz2, futures-3.0.5-py27_0.tar.bz2, cycler-0.10.0-py27_0.tar.bz2, configobj-5.0.6-py27_0.tar.bz2, openpyxl-2.3.2-py27_0.tar.bz2, sip-4.16.9-py27_2.tar.bz2, werkzeug-0.11.10-py27_0.tar.bz2, cryptography-1.4-py27_0.tar.bz2, idna-2.1-py27_0.tar.bz2, babel-2.3.3-py27_0.tar.bz2, xlwings-0.7.2-py27_0.tar.bz2, ipykernel-4.3.1-py27_0.tar.bz2, cdecimal-2.3-py27_2.tar.bz2, tk-8.5.18-vc9_0.tar.bz2, jupyter_client-4.3.0-py27_0.tar.bz2, ssl_match_hostname-3.4.0.2-py27_1.tar.bz2, pyparsing-2.1.4-py27_0.tar.bz2, mkl-11.3.3-1.tar.bz2, xlsxwriter-0.9.2-py27_0.tar.bz2, flask-cors-2.1.2-py27_0.tar.bz2, scipy-0.17.1-np111py27_1.tar.bz2, chest-0.2.3-py27_0.tar.bz2, six-1.10.0-py27_0.tar.bz2, funcsigs-1.0.2-py27_0.tar.bz2, pytables-3.2.2-np111py27_4.tar.bz2, pyreadline-2.1-py27_0.tar.bz2, nb_anacondacloud-1.1.0-py27_0.tar.bz2, notebook-4.2.1-py27_0.tar.bz2, hdf5-1.8.15.1-vc9_4.tar.bz2, jupyter-1.0.0-py27_3.tar.bz2, scikit-learn-0.17.1-np111py27_1.tar.bz2, datashape-0.5.2-py27_0.tar.bz2, cffi-1.6.0-py27_0.tar.bz2, sphinx-1.4.1-py27_0.tar.bz2, configparser-3.5.0b2-py27_1.tar.bz2, backports_abc-0.4-py27_0.tar.bz2, flask-0.11.1-py27_0.tar.bz2, astropy-1.2.1-np111py27_0.tar.bz2, openssl-1.0.2h-vc9_0.tar.bz2, xlrd-1.0.0-py27_0.tar.bz2, nbpresent-3.0.2-py27_0.tar.bz2, toolz-0.8.0-py27_0.tar.bz2, pillow-3.2.0-py27_1.tar.bz2, get_terminal_size-1.0.0-py27_0.tar.bz2, unicodecsv-0.14.1-py27_0.tar.bz2, anaconda-navigator-1.2.1-py27_0.tar.bz2, sqlalchemy-1.0.13-py27_0.tar.bz2, qtpy-1.0.2-py27_0.tar.bz2, pyzmq-15.2.0-py27_0.tar.bz2, pathlib2-2.1.0-py27_0.tar.bz2, numexpr-2.6.0-np111py27_0.tar.bz2, click-6.6-py27_0.tar.bz2, nb_conda-1.1.0-py27_0.tar.bz2, freetype-2.5.5-vc9_1.tar.bz2, ply-3.8-py27_0.tar.bz2, dask-0.10.0-py27_0.tar.bz2, gevent-1.1.1-py27_0.tar.bz2, jupyter_console-4.1.1-py27_0.tar.bz2, sockjs-tornado-1.0.3-py27_0.tar.bz2, h5py-2.6.0-np111py27_0.tar.bz2, jdcal-1.2-py27_1.tar.bz2, singledispatch-3.4.0.3-py27_0.tar.bz2, pyasn1-0.1.9-py27_0.tar.bz2, pytest-2.9.2-py27_0.tar.bz2, pycrypto-2.6.1-py27_4.tar.bz2, pickleshare-0.7.2-py27_0.tar.bz2, bitarray-0.8.1-py27_1.tar.bz2, pywin32-220-py27_1.tar.bz2, heapdict-1.0.0-py27_1.tar.bz2
Solving package specifications: INFO:stdoutlog:Solving package specifications: 
.DEBUG:dotupdate:Solving for [MatchSpec('pyodbc'), MatchSpec('python 2.7* (target=python-2.7.11-5.tar.bz2)'), MatchSpec('conda'), MatchSpec('conda-env'), MatchSpec('ruamel_yaml (target=ruamel_yaml-0.11.7-py27_0.tar.bz2)'), MatchSpec('setuptools (target=setuptools-23.0.0-py27_0.tar.bz2)'), MatchSpec('pip (target=pip-8.1.2-py27_0.tar.bz2)'), MatchSpec('menuinst (target=menuinst-1.4.1-py27_0.tar.bz2)'), MatchSpec('vs2008_runtime (target=vs2008_runtime-9.00.30729.1-2.tar.bz2)'), MatchSpec('pycosat (target=pycosat-0.6.1-py27_1.tar.bz2)'), MatchSpec('wheel (target=wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py27_4.tar.bz2)'), MatchSpec('requests (target=requests-2.10.0-py27_0.tar.bz2)')]
DEBUG:conda.resolve:Retrieving packages for: [MatchSpec('pyodbc'), MatchSpec('python 2.7* (target=python-2.7.11-5.tar.bz2)'), MatchSpec('conda'), MatchSpec('conda-env'), MatchSpec('ruamel_yaml (target=ruamel_yaml-0.11.7-py27_0.tar.bz2)'), MatchSpec('setuptools (target=setuptools-23.0.0-py27_0.tar.bz2)'), MatchSpec('pip (target=pip-8.1.2-py27_0.tar.bz2)'), MatchSpec('menuinst (target=menuinst-1.4.1-py27_0.tar.bz2)'), MatchSpec('vs2008_runtime (target=vs2008_runtime-9.00.30729.1-2.tar.bz2)'), MatchSpec('pycosat (target=pycosat-0.6.1-py27_1.tar.bz2)'), MatchSpec('wheel (target=wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py27_4.tar.bz2)'), MatchSpec('requests (target=requests-2.10.0-py27_0.tar.bz2)')]
DEBUG:conda.resolve:python: pruned from 63 -> 28
DEBUG:conda.resolve:pip: pruned from 93 -> 29
DEBUG:conda.resolve:conda: pruned from 287 -> 116
DEBUG:conda.resolve:pyyaml: pruned from 27 -> 8
DEBUG:conda.resolve:conda-env: pruned from 64 -> 21
DEBUG:conda.resolve:ruamel_yaml: pruned from 4 -> 2
DEBUG:conda.resolve:setuptools: pruned from 184 -> 50
DEBUG:conda.resolve:menuinst: pruned from 41 -> 16
DEBUG:conda.resolve:pycosat: pruned from 34 -> 11
DEBUG:conda.resolve:wheel: pruned from 16 -> 5
DEBUG:conda.resolve:requests: pruned from 86 -> 24
DEBUG:conda.resolve:pyodbc: pruned from 13 -> 3
.DEBUG:dotupdate:Checking satisfiability
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package removal metric: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,115)
DEBUG:conda.logic:Bisection attempt: (0,0), (2619+136) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (2755+2) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 1/1 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (2757+1) clauses
DEBUG:conda.logic:Bisection failure, new range=(1,1)
DEBUG:conda.logic:Bisection attempt: (1,1), (2757+1) clauses
DEBUG:conda.logic:Bisection success, new range=(1,1)
DEBUG:conda.logic:Final sum objective: 1
DEBUG:conda.logic:New peak objective: 1
.DEBUG:dotupdate:Track feature count: 1
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package feature count: 1
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,10)
DEBUG:conda.logic:Eliminating 10/10 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (2758+10) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Dependency update count: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (2768+152) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (2920+34) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 3/3 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (2954+3) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Weak dependency count: 0
.DEBUG:dotupdate:Looking for alternate solutions

Warning: 2 possible package resolutions (only showing differing packages):
  - conda-env-2.5.1-py27_0.tar.bz2
  - http://bremen/pkgs/free::conda-env-2.5.1-py27_0.tar.bz2INFO:stdoutlog:
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-env-2.5.1-py27_0.tar.bz2
  - http://bremen/pkgs/free::conda-env-2.5.1-py27_0.tar.bz2

INFO:stdoutlog:


Package plan for installation in environment C:\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyodbc-3.0.10              |           py27_0          43 KB

The following NEW packages will be INSTALLED:

    pyodbc: 3.0.10-py27_0

Proceed ([y]/n)? 
DEBUG:conda.plan:Adding plans for operations: ('RM_FETCHED', 'FETCH', 'RM_EXTRACTED', 'EXTRACT', 'UNLINK', 'LINK', 'SYMLINK_CONDA')
DEBUG:conda.plan:action RM_FETCHED not in actions
DEBUG:conda.plan:appending value http://bremen/pkgs/free::pyodbc-3.0.10-py27_0 for action FETCH
DEBUG:conda.plan:action RM_EXTRACTED not in actions
DEBUG:conda.plan:appending value http://bremen/pkgs/free::pyodbc-3.0.10-py27_0 for action EXTRACT
DEBUG:conda.plan:action UNLINK not in actions
DEBUG:conda.plan:appending value http://bremen/pkgs/free::pyodbc-3.0.10-py27_0 1 False for action LINK
DEBUG:conda.plan:appending value C:\Anaconda2 for action SYMLINK_CONDA
DEBUG:conda.instructions: PREFIX('C:\\Anaconda2')
DEBUG:conda.instructions: PRINT('Fetching packages ...')
INFO:print:Fetching packages ...
DEBUG:conda.instructions: FETCH(u'http://bremen/pkgs/free::pyodbc-3.0.10-py27_0')
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:conda.fetch:url=u'https://repo.continuum.io/pkgs/free/win-64/http://bremen/pkgs/free::pyodbc-3.0.10-py27_0.tar.bz2'
Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 369, in download
    with Locked(dst_dir):
  File "C:\Anaconda2\lib\site-packages\conda\lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'C:\\Anaconda2\\pkgs\\http:'

3. Shall do.

**Comment by thorsant** [comment]
Where do I find conda 4.1.6? I try doing `conda update conda` but it says already at version 4.1.4

**Comment by HugoTian** [comment]
@thorsant  please run "conda update conda", or reinstall anaconda/miniconda to update conda, and the latest version is 4.1.9

I think the errors comes from lock module, since http:// is in file path.  In conda 4.2, before create lock, we will make sure it is a legal path.

I just tried on 4.1.9 and it works fine, please @ me if you still have problems

**Comment by thorsant** [comment]
Ok, thank you! Will try it.
