### ISSUE TITLE
Support pinning of channels for specific packages

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#2978]
As having multiple channels become the norm with the rise of `conda-forge` it would be very useful to be able to specify that you want a given package to _only_  ever be installed from a specific channel (or channels)

**Comment by kalefranz** [comment]
The `pinned_packages` configuration now accepts channel as part of the spec, starting in conda 4.4.0.

**Comment by dhirschfeld** [comment]
Is there any documentation for this feature or any other way I can find out how to pin a package to a particular channel?

**Comment by dhirschfeld** [comment]
The only info I could fine is in https://github.com/conda/conda/pull/4921
...but it doesn't say anything about the syntax for pinning *channels*
