### ISSUE TITLE
conda install --force won't install a package with unsatisfiable specifications

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#2980]
```
$conda install readline=6.3 --force
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................
Solving package specifications: ....

The following specifications were found to be in conflict:
  - readline 6.3*
Use "conda info <package>" to see the dependencies for each package.
```

I would expect `--force` to install the package anyway. This used to work, don't know why this was broken. 

(by the way, the reason I want to do this is that the Continuum `python` depends on readline 6.2, but I want to install readline 6.3 from conda-forge)

**Comment by mcg1969** [comment]
This stopped working as soon as we started including installed packages into the solver specs. And of course, we had to do that for other reason: for instance, so that things like `conda update numpy` wouldn't break all of the packages that depended on a particular NumPy API.

I wonder if this is why Ilan thought that `--force --no-deps` was a new addition: https://github.com/conda/conda/issues/2928

**Comment by mcg1969** [comment]
In this specific case, perhaps we should be relaxing our specifications on `python` from `readline 6.2` to `readline >=6.2,<7`?

**Comment by asmeurer** [comment]
So maybe this actually didn't ever work. I just tested `conda create -n test -c asmeurer/c/test unsat --force` in an old version of conda (3.0.6) and it doesn't work there either. I am now remembering that `--force` has always had to call the solver anyway, to match Python versions.

**Comment by adler-j** [comment]
Is there any known workaround to this? I've been spending at least an hour trying to force numpy to upgrade, but conda simply won't let me do it.

**Comment by Serhiy-Shekhovtsov** [comment]
I have the same problem. Trying to install python 3.5 on root environment, and it gives me UnsatisfiableError with only one package specified at a time. And I have to run it again and again and remove packages in conflict one by one. Nightmare!

**Comment by liorgraf** [comment]
+1

**Comment by kalefranz** [comment]
Going to close this ticket.  Lots of other open issues tagged with solver and solver-messaging that will cover anything outstanding here also.

**Comment by adler-j** [comment]
So, could anyone give links to said "Lots of other open issues tagged with solver and solver-messaging that will cover anything outstanding here also."? It seems my earlier comment is simply acquiring thumbs up and there is not an answer anywhere that I've found.

**Comment by msarahan** [comment]
https://github.com/conda/conda/labels/tag-solver
https://github.com/conda/conda/labels/tag-solver_messaging

**Comment by colinbrislawn** [comment]
This seems like a catch-22:
I need to install conflicting packages to test my patch,
but conda won't let me install conflicting packages

Any recommendations here? How are we _supposed_ to resolve conflicts around software versions?

**Comment by lguangyu** [comment]
Is there a configuration or workaround to override conda's default package dependency specifications?
both --force and --no-deps are useless even conda's documentation says:
```
If you wish to skip dependency checking altogether, use the '--no-deps' option.
```
I think the users _should_ have the freedom to choose what they want or temper the system as long as they know what they are doing.

**Comment by thermokarst** [comment]
Hi @lguangyu, I have _no_ idea if this is an appropriate workaround or not, but here is a rough protocol I have used in the past:

https://github.com/caporaso-lab/pretrained-feature-classifiers/pull/6#issuecomment-586023587

If you have any questions or idea, I am happy to discuss, but maybe it would be best to discuss on the PR linked to above, that way we don't spam this closed issue.

**Comment by lguangyu** [comment]
Hi @thermokarst, I appreciate your reply. The workaround seems working for me.
I was thinking if it is possible to have a feature in future versions that allows passing a json or yaml file to `conda install` with user-specified dependency overrides. I think some (old) packages, especially in python, run out of maintenance to update their compatibility with newer versions of python.

**Comment by TheConfused** [comment]
If somebody is still looking for solution to this problem, you could try the following:

`/path/to/anaconda3/envs/env_name/bin/pip install whatever`

**Comment by epassaro** [comment]
> Is there a configuration or workaround to override conda's default package dependency specifications? both --force and --no-deps are useless even conda's documentation says:
> 
> ```
> If you wish to skip dependency checking altogether, use the '--no-deps' option.
> ```
> 
> I think the users _should_ have the freedom to choose what they want or temper the system as long as they know what they are doing.

I'm in the same situation!
