### ISSUE TITLE
Source of truth: which packages are installed?

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2986]
What is the source of "truth" as to whether or not Conda is installed?  Conda is installed, but it doesn't seem to know about it, consequently I can't `update`.

```
(root) ➜  ~ which conda
/Users/ijstokes/anaconda/bin/conda

(root) ➜  ~ conda update conda
Error: Package 'conda' is not installed in /Users/ijstokes/anaconda

(root) ➜  ~ conda -V
conda 4.1.3

(root) ➜  ~ /Users/ijstokes/anaconda/bin/conda -V
conda 4.1.3

(root) ➜  ~ /Users/ijstokes/anaconda/bin/conda update conda
Error: Package 'conda' is not installed in /Users/ijstokes/anaconda
```

I think what has happened here for me is that some `conda` operation obliterated `conda` from my root environment and I recovered using the technique I described in #2911.  And from the looks of it, there is some missing information so I can no longer `conda update conda`.

FWIW, I can `conda install conda`, which perhaps is the solution for my immediate problem, but I'd like to know how to refine my "rescue" technique.

**Comment by mcg1969** [comment]
The source of truth is the `conda-meta` directory. If there is not a `conda-*` package there, `conda` does not think it is installed. `conda install -f conda` is definitely a good addition to your rescue script.

**Comment by ijstokes** [comment]
@mcg1969 thanks, the answer is the `conda-meta` directory as you said.

**Comment by hashamMunir** [comment]
still conda not found
