### ISSUE TITLE
Channel Alias should add ending slash /

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2990]
Channel Alias: http://conda.pydata.org/docs/install/central.html#channel-alias-channel-alias

Should add a trailing slash if there isn't one in the config file.  Otherwise it concatenates a nonsense string like:    https://conda.anaconda.org for `conda install wget -c bkreider` would become this =>   https://conda.anaconda.orgbkreider.

I don't see how it would ever be useful to not add the trailing slash there.

**Comment by kalefranz** [comment]
Is this a new bug?

**Comment by kalefranz** [comment]
`conda install wget -c bkreider` worked fine for me

**Comment by bkreider** [comment]
I'm not sure.  I debugged this on a customer implementation.  I couldn't figure out why the url had smashed the alias and the default channel together.  I didn't test it with the CLI (-c), but there was a "short name" channel in the channels list.  

I haven't try to recreate it locally.
