### ISSUE TITLE
Better error catching / stronger validation

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2991]
I accidentally had a customer configure the .condarc for Anaconda Cluster to have this (it should not be a list):

```
channel_alias: 
    - https://your.repo/
```

When conda attempted to run the config command, something like `conda config --set blah`,  it blew up because of the bad config file, but it looks like the `conda config` command is what is failing.  The command is fine, but the existing .condarc is wrong.  If you don't know to look at the .condarc, the stack trace makes one think that the config command is somehow wrong.  

I'd even be happy with a blanket:  "Your config is broken" message (but we should be able to say what key/value is wrong).

**Comment by kalefranz** [comment]
This is happening as part of the config overhaul in conda 4.2.
