### ISSUE TITLE
Conda metadata fetch should have name + progress bar

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2996]
@srossross commented on [Wed Jul 06 2016](https://github.com/conda/conda-build/issues/1099)

It would be nice to see a name and progress bar of the current metadata download just like the package section. eg:
```
$ conda install pandas
Fetching metadata ...
sean                2% |##                                                                                                                   | ETA:  
repo.continuum.io   2% |##                                                                                                                   | ETA:  
Fetching packages ...

mkl-11.3.3-0.t   2% |##                                                                                                                   | ETA:  0:02:48 617.28 kB/s
...
```

---

@msarahan commented on [Thu Jul 07 2016](https://github.com/conda/conda-build/issues/1099#issuecomment-231080931)

Moving this over to conda - I don't think this is strictly a build issue, is it?

**Comment by kalefranz** [comment]
@HugoTian Let's think about this in a week or two if we get to refactoring more of `fetch.py` for testing, etc.

**Comment by HugoTian** [comment]
According to fetch.py, fetch_repodata will run in parallel if it can import concurrent.futures. 

If this download run in serial, it is not hard to add progress bar using existing library. However, when run in parallel, we may have to modify progress bar library to support this.

**Comment by HugoTian** [comment]
@srossross , I create a PR, #3112  , for new progress bar use blessing and progressive, and it also support multi-threading and it will do something like below:

[![Tree Progress View](https://raw.githubusercontent.com/hfaran/progressive/master/example.gif)](https://github.com/hfaran/progressive)

Iet's discuss under that PR, and I will close this issue. Feel free to reopen it.
