### ISSUE TITLE
conda update anaconda do not work properly

### ISSUE THREAD

**Issue by shilkazx** [conda/conda#2998]
Environment: Archlinux x64
The current annaconda version is “4.0.0 np110py35_0”. But when I was tring to update anaconda via "conda update anaconda", conda did not give me the update prompt but show me :

Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at *****/anaconda3:
#
anaconda                  4.0.0               np110py35_0  

I actually have another computer also run Archlinux x64 and anaconda, but the update process on that computer works fine--conda recognize new anaconda version properly and then update related packages without any trouble.

**Comment by shilkazx** [comment]
Occasionly, I've found the reason of this problem. It's just because the conflict of new anaconda version and some other packages' requirement. I suggest that conda update function should give more details about the reason of unable to update.

**Comment by HugoTian** [comment]
Agree with you, now conda is not good at telling why. In future, we will add more features to solve it in a better way.

**Comment by shilkazx** [comment]
In anaconda trouble shooting doc, it is suggested that 
> Running "conda update anaconda" or "conda install anaconda=4.2" (replacing “4.2” with the latest version number) will show a list of these conflicting packages.

But when I run conda update anaconda, the program just still prompt 
> All requested packages already installed. 
> packages in environment at ****:
> anaconda                  4.1.1               np111py35_0 

Seems conda update is still malfunctioning on conflict detecting.

**Comment by kalefranz** [comment]
Another issue where https://github.com/ContinuumIO/anaconda-issues/issues/4298 is the solution to the root cause.

**Comment by shilkazx** [comment]
Thanks dude. It seems that conda update perform better than before in
recent days.
