### ISSUE TITLE
Extracting packages ... An unexpected error has occurred

### ISSUE THREAD

**Issue by jvsinco** [conda/conda#3002]
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 854, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 240, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\Anaconda3\\pkgs\\mkl-11.3.3-1.tmp' -> 'C:\\Anaconda3\\pkgs\\mkl-11.
3.3-1'

C:\Users\jvansl>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
What was the package you were trying to install?

**Comment by jvsinco** [comment]
C:\Users\jvansl>conda install numpy
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.3                 |                1       110.0 MB
    numpy-1.11.1               |           py35_0         2.8 MB
    numexpr-2.6.0              |      np111py35_0         130 KB
    scipy-0.17.1               |      np111py35_1        10.6 MB
    scikit-learn-0.17.1        |      np111py35_1         3.5 MB
    ------------------------------------------------------------
                                           Total:       126.9 MB

The following packages will be UPDATED:

    mkl:          11.3.1-0           --> 11.3.3-1
    numexpr:      2.4.6-np110py35_1  --> 2.6.0-np111py35_0
    numpy:        1.10.4-py35_0      --> 1.11.1-py35_0
    scikit-learn: 0.17-np110py35_1   --> 0.17.1-np111py35_1
    scipy:        0.16.0-np110py35_0 --> 0.17.1-np111py35_1

Proceed ([y]/n)? y

Fetching packages ...
mkl-11.3.3-1.t 100% |###############################| Time: 0:02:53 666.21 kB/s
numpy-1.11.1-p 100% |###############################| Time: 0:00:05 521.73 kB/s
numexpr-2.6.0- 100% |###############################| Time: 0:00:00 231.54 kB/s
scipy-0.17.1-n 100% |###############################| Time: 0:00:17 620.52 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:05 696.78 kB/s
Extracting packages ...

**Comment by kalefranz** [comment]
I thought we had fixed this in #2944 and #2955, but maybe we needed to give even more time for the virus scanner to run.  Are you working on a relatively slow or older system?

**Comment by jvsinco** [comment]
It is no super hero!
[cid:image001.png@01D1D85E.DF5C2B20]

jvs

**Comment by jvsinco** [comment]
I re-run the install and this time it worked.
jvs
