### ISSUE TITLE
error on "conda info"

### ISSUE THREAD

**Issue by lainiewright** [conda/conda#3009]
`$ conda info`

Stack trace:

Warning: could not import binstar_client ('args' object has no attribute 'site')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/lainie.wright/anaconda/envs/diutil/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/lainie.wright/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/lainie.wright/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/lainie.wright/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/Users/lainie.wright/anaconda/lib/python2.7/site-packages/conda/config.py", line 243, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by twiecki** [comment]
I had to `conda remove binstar` which fixed it.

**Comment by tim-scharf** [comment]
same issue.  Solution by @twiecki worked for me as well  --

**Comment by kerrydu** [comment]
same issue ...but the solution does not apply to me.
-------------------------------------------------------------------
[Anaconda3] C:\Users\Kerui>conda remove binstar
Fetching package metadata .........
Solving package specifications: ..........
Error: no packages found to remove from environment: d:\Users\Kerui\Anaconda3

**Comment by HugoTian** [comment]
please run "conda update conda", now the version is 4.1.9, and it should solves this problem.

I will close this issue now, and if there is still problem, feel free to reopen it

**Comment by babhishek21** [comment]
Issue resurfaces in 4.1.11. (originally 4.1.10, updated with `conda update conda`).

![image](https://cloud.githubusercontent.com/assets/8472087/17713032/77aa4a4a-6416-11e6-97b3-e3cc8fc12854.png)
