### ISSUE TITLE
Installing PySide on Linux and py33: RPATH not set

### ISSUE THREAD

**Issue by almarklein** [conda/conda#301]
I thought that Conda took responsibility for setting the RPATH of installed libs, but the libs have an empty RPATH. After patching with patchelf things work as expected.

**Comment by goanpeca** [comment]
@kalefranz @csoja since we dont support py33 or pyside, could we close this? (plus 3 years old issue)

However PySide2 will eventually come, but that should be a separate issue anyway...

**Comment by kalefranz** [comment]
Yes, I think this is safe to close.  It was probably a conda-build issue, or maybe it was conda.  Either way the root cause I'm sure has long been resolved.
