### ISSUE TITLE
how about checkout to new env promptly after creating?

### ISSUE THREAD

**Issue by workingenius** [conda/conda#3010]
As far as my situations, env creatings are often followed by operations on the new envs, usually installing packages, or checkout to the new one and start my app.  For many times I forget to checkout and change the last env, even damage it.  So, would this be a good idea?

**Comment by jakirkham** [comment]
Basically that would require `source` in that command, but yeah I like that idea.

**Comment by workingenius** [comment]
@jakirkham, . command in sh is also ok, right?

**Comment by kalefranz** [comment]
We can actually do this now with #5044.
