### ISSUE TITLE
 netCDF4 can't be used on ssl requests

### ISSUE THREAD

**Issue by ReimarBauer** [conda/conda#3013]
netCDF4 1.2.2 needs curl 7.45.0 by one of its dependencies 

Unfortunately this version has not anymore SSLv2_client_method defined.

Is there a newer netCDF4 module which did not try to request those old SSLv2 client method or a newer curl which can be replace this 7.45.0 haveing those symbols

```
[Fri Jul 08 16:42:32.658871 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]     import netCDF4
[Fri Jul 08 16:42:32.658888 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]   File "/home/user/miniconda2/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
[Fri Jul 08 16:42:32.658915 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]     from ._netCDF4 import *
[Fri Jul 08 16:42:32.658955 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ] ImportError: /home/user/miniconda2/lib/python2.7/site-packages/netCDF4/../../.././libcurl.so.4: undefined symbol: SSLv2_client_method
[Fri Jul 08 16:42:32.660183 2016] [ssl:debug] [pid 20343:tid 140526487525120] ssl_engine_io.c(1016): [client] AH02001: Connection closed 
```

Current conda install:

```
              platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.5
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/user/miniconda2  (writable)
  default environment : /home/user/miniconda2
     envs directories : /home/user/miniconda2/envs
        package cache : /home/user/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/user/.condarc
         offline mode : False
    is foreign system : False
```

Is there some workaround?

**Comment by jakirkham** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
@ReimarBauer the conda repository is not really about the packages, but more about `conda` itself. I believe the right place to report this would be https://github.com/ContinuumIO/anaconda-issues or the mailing list.

@msarahan the `conda-forge` package has that symbols BTW:

```
> nm libcurl.so | grep SSLv2_client_method
                 U SSLv2_client_method
```

**Comment by ReimarBauer** [comment]
great :)

As I was trying this I also updated netCDF4
The following packages will be UPDATED:

 ```
   curl:      7.45.0-0          --> 7.49.1-0          conda-forge
    hdf5:      1.8.15.1-2        --> 1.8.17-2          conda-forge
    libnetcdf: 4.3.3.1-3         --> 4.4.0-1           conda-forge
    netcdf4:   1.2.2-np111py27_0 --> 1.2.4-np111py27_2 conda-forge
```

and afterwards I had the netCDF import error. So I was not able to go further.

So I guess I could tell this in the anaconda tracker. :)

**Comment by jakirkham** [comment]
If there was an issue with the conda-forge package, it should be raised at that feedstock ( https://github.com/conda-forge/netcdf4-feedstock ).

**Comment by ReimarBauer** [comment]
I described the ssl issue on anaconda-issue. https://github.com/ContinuumIO/anaconda-issues/issues/908
upgrade default netcdf4 to netcdf4-feedstock works. But with more libraries involved it gets not the latest build of hdf4. Anyway the issue is on the wrong place
 
So I close this one here.
