### ISSUE TITLE
Too many files to create an environment

### ISSUE THREAD

**Issue by srossross** [conda/conda#3017]
# Problem Statement
## Too many files

Conda and anaconda have a growing number of files that can be used for different purposes, but achieve the basic functionality of creating or specifying an environment. 

Some formats add to this core, but they all share the same base. Yet each does this in a different way from the next.

| Command | Instals packages | Channel support | pip support | project support | platform specificity | different requirement syntax |
| --- | --- | --- | --- | --- | --- | --- |
| `command line` | ✅ | ✅ | ✅ | ✅ | ⛔ | - |
| [`requirements.txt`](http://conda.pydata.org/docs/using/envs.html#build-identical-conda-environments) | ✅ | ⛔ | ⛔ | ⛔ | ⛔ | - |
| [`environment.yaml`](http://conda.pydata.org/docs/using/envs.html#use-environment-from-file) | ✅ | ✅ | ✅ | ⛔ | ⛔ | - |
| [`project.yaml | kapsel.yaml`](https://github.com/Anaconda-Platform/anaconda-project/blob/conda-kapsel-staging/kapsel-config.rst) | ✅ | ✅ | ✅ | ✅ | ⛔ | - |
| [`constructor.yaml`](https://github.com/conda/constructor/blob/master/CONSTRUCT.md) | ✅ | ✅ | ⛔ | ⛔ | ⛔ | - |
| [`cas-installer.yaml`](https://docs.continuum.io/anaconda-repository/cli-cas-installer#cas-installer) | ✅ | ✅ | ⛔ | ⛔ | ⛔ | - |
| [`meta.yaml`](http://conda.pydata.org/docs/building/meta-yaml.html) | ✅ | ⛔ | ⛔ | ⛔ | ✅ | 💀 |
### Notes
- [`meta.yaml`](http://conda.pydata.org/docs/building/meta-yaml.html)
  - ✅ can use requirements.txt if found
# Possible Solutions
### Lets standardize.

As we move forward we should think about how adding new file formats and definitions affects the conda ecosystem. Are we going to have an ever growing list of file formats? 
- Should we deprecate a few in a planned and controlled way?
- Should we standardize so that the core functionality is the same across all files? And the files can be written in the same way with the same syntax?
- Should we define a base file `quiz-blag.yaml` that all tools look for to create their environment (just like meta.yaml uses requirements.txt if it exists)?

**Comment by kalefranz** [comment]
I wasn't aware of the constructor and cas-installer files. I plan to deprecate environment.yml in a planned and controlled way. The new file will be condaenv.yml, which will be a strict subset of kapsel.yml. At least those are my thoughts right now.

**Comment by jakirkham** [comment]
What is `kapsel.yml`? 😕
