### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by KanduriC** [conda/conda#3030]
Hello!

One of the programs that I am trying to install on a linux cluster uses conda. The program installation is interrupted because of an issue with conda (shown below). Any suggestions on how I can overcome this? Thanks. 

-bash-4.1$ /cluster/home/skanduri/bcbio/anaconda/bin/conda update -y -c r ncurses 
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /cluster/home/skanduri/bcbio/anaconda:

The following packages will be UPDATED:

```
ncurses: 5.9-0 --> 5.9-4 r (soft-link)
```

Extracting packages ...
An unexpected error has occurred, please consider sending the             |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/cluster/home/skanduri/bcbio/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/install.py", line 852, in extract
    t.extractall(path=temp_path)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2200, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2284, in makelink
    os.link(tarinfo._link_target, targetpath)
OSError: [Errno 1] Operation not permitted

---

-bash-4.1$ /cluster/home/skanduri/bcbio/anaconda/bin/conda info 
Current conda install:

```
         platform : linux-64
    conda version : 4.1.6
conda-env version : 2.5.1
```

  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /cluster/home/skanduri/bcbio/anaconda  (writable)
  default environment : /cluster/home/skanduri/bcbio/anaconda
     envs directories : /cluster/home/skanduri/bcbio/anaconda/envs
        package cache : /cluster/home/skanduri/bcbio/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by jakirkham** [comment]
Yep, that means `ncurses` built with hardlinks, which it likes to do by default. 😒 I also tried to extract that same package on OS X just by downloading the tarball and decompressing it. The package gave me a similar error.

The package from `conda-forge` may work for you in the interim depending on your `glibc` version. Could you please try running `strings /lib64/libc.so.6 | grep GLIBC` on the target machine and please let me know what it says?

**Comment by jakirkham** [comment]
Bringing this one to your attention @mingwandroid, it looks like `ncurses` needs to be rebuilt. The change needed should be giving `configure` the option `--enable-symlinks`.

**Comment by KanduriC** [comment]
Thanks for the quick response. 

-bash-4.1$ strings /lib64/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

**Comment by jakirkham** [comment]
Yep, you should be able to use the `conda-forge` copy fine. Try running `conda install -c conda-forge ncurses` and then proceed. There may be channel priority issues that need to be sorted, but we can cross that bridge when we get there.

**Comment by KanduriC** [comment]
Thanks for the advice; it worked.

**Comment by mingwandroid** [comment]
Thanks @jakirham, I'm on it. I think we should add a check for this to `anaconda-verify`, do you agree @ilanschnell? I'm happy to take a look if you think it'd be ok?

**Comment by mingwandroid** [comment]
The temporary bug closure was github being too clever for its own good!

**Comment by mingwandroid** [comment]
`ncurses` on `defaults` is now updated to `5.9-8` which fixes this. Thanks all.

**Comment by jakirkham** [comment]
> I think we should add a check for this to `anaconda-verify`...

By check do you mean a check for hard-links? That might be tricky.

Though you could just have a check that sees if the package can be decompressed/installed. Surprisingly that catches several big errors hard-links included.

**Comment by mingwandroid** [comment]
We're now using this:

https://docs.python.org/3/library/tarfile.html#tarfile.TarInfo.islnk

.. so we should catch 'em all in future. Like pokemons.
