### ISSUE TITLE
conda clone failed to install python libraries

### ISSUE THREAD

**Issue by maoliveira69** [conda/conda#3033]
Hi,

After cloning our root environment with:

[mao@login-2 ~]> conda create -n mao --clone root
Source:      /apps/anaconda/2.4.1.1
Destination: /home/mao/.conda/envs/mao
The following packages cannot be cloned out of the root environment:
 - conda-4.1.6-py27_0
 - conda-build-1.21.3-py27_0
Packages: 186
Files: 0
Linking packages ...
[      COMPLETE      ]|###########################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate mao
#
# To deactivate this environment, use:
# $ source deactivate
#

we found that several libraries are missing. Notably libpython2.7.so.

(mao) [mao@login-2 ~]> python
python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory.

In fact this library is a dangling link:

(mao) [mao@login-2 ~]> ll ~/.conda/envs/mao/lib/libpython2.7.so
lrwxrwxrwx 1 mao hpc-users 19 Jul 11 17:49 /home/mao/.conda/envs/mao/lib/libpython2.7.so -> libpython2.7.so.1.0
(mao) [mao@login-2 ~]> ll ~/.conda/envs/mao/lib/libpython2.7.so.1.0
ls: cannot access /home/mao/.conda/envs/mao/lib/libpython2.7.so.1.0: No such file or directory

Are we doing something wrong?

Best Regards,

MAO

===============================================================================

(mao) [mao@login-2 ~]> conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /apps/anaconda/2.4.1.1  (read only)
  default environment : /home/mao/.conda/envs/mao
     envs directories : /home/mao/.conda/envs
                        /home/mao/envs
                        /apps/anaconda/2.4.1.1/envs
        package cache : /home/mao/.conda/envs/.pkgs
                        /home/mao/envs/.pkgs
                        /apps/anaconda/2.4.1.1/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by lmcinnes** [comment]
I am having the same issue. None of the libraries in .conda/env/<envname>/lib are linked correctly.

**Comment by HugoTian** [comment]
Let's move the discussion to #3198, and feel free to reopen this one and @ me
