### ISSUE TITLE
Exception attempting to install package file

### ISSUE THREAD

**Issue by havocp** [conda/conda#3035]
I typed `conda install package.tar.bz2` and got this traceback.

```
  File "/home/hp/bin/Anaconda-2.2.0/envs/deptest/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/cli/install.py", line 203, in install
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/conda/config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0
```

**Comment by kalefranz** [comment]
What version of conda?

`conda info`

**Comment by havocp** [comment]
this was 4.1.6 linux64

**Comment by havocp** [comment]
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/hp/bin/Anaconda-2.2.0  (writable)
  default environment : /home/hp/bin/Anaconda-2.2.0/envs/py3
     envs directories : /home/hp/bin/Anaconda-2.2.0/envs
        package cache : /home/hp/bin/Anaconda-2.2.0/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/binstar/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/binstar/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/hp/.condarc
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
Can you try conda 4.1.8?

**Comment by havocp** [comment]
Still fails but different error.

```
(py3) [hp@localhost old.conda-kapsel]$ conda install build/packages/py3.5/linux-64/conda-kapsel-0.3.0-py35_29.tar.bz2 
Using Anaconda Cloud api site https://api.anaconda.org
Fetching packages ...
Error: HTTPError: 404 Client Error: None for url: file:///home/hp/checkout/old.conda-kapsel/build/packages/py3.5/linux-64/conda-kapsel-0.3.0-py35_29.tar.bz2: file:///home/hp/checkout/old.conda-kapsel/build/packages/py3.5/linux-64/conda-kapsel-0.3.0-py35_29.tar.bz2

(py3) [hp@localhost old.conda-kapsel]$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.1
  conda-build version : 1.21.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/hp/bin/Anaconda-2.2.0  (writable)
  default environment : /home/hp/bin/Anaconda-2.2.0/envs/py3
     envs directories : /home/hp/bin/Anaconda-2.2.0/envs
        package cache : /home/hp/bin/Anaconda-2.2.0/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/binstar/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/binstar/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/hp/.condarc
         offline mode : False
    is foreign system : False

```

**Comment by kalefranz** [comment]
ok that's progress

I'm guessing your current working directory is `/home/hp/checkout/old.conda-kapsel`?

Can you try `conda install {{ FULL PATH }}/build/packages/py3.5/linux-64/conda-kapsel-0.3.0-py35_29.tar.bz2` -- installing the tarball with full path?

Not that you shouldn't be able to install with a relative path, but at least will help confirm the issue.

**Comment by havocp** [comment]
Right, that's the cwd. Full path doesn't seem to help, same error.

**Comment by kalefranz** [comment]
The file exists, correct?

    ls -al /home/hp/checkout/old.conda-kapsel/build/packages/py3.5/linux-64/conda-kapsel-0.3.0-py35_29.tar.bz2

**Comment by havocp** [comment]
Doh! No, I rebuilt with a new version so the command in my history was for an old file.

It does appear to successfully install with 4.1.8. Looks good.

**Comment by kalefranz** [comment]
cool!
