### ISSUE TITLE
miniconda 4.1.x not available in https://repo.continuum.io/miniconda/

### ISSUE THREAD

**Issue by gmnash** [conda/conda#3037]
It appears that several versions of conda 4.1.x have been released but there is no associated miniconda installer here: https://repo.continuum.io/miniconda/. When will they be made available?

**Comment by HugoTian** [comment]
We are making the miniconda installer now. It takes time since we want to fully test miniconda installer, and we also want to have a stable version of conda.

Now conda 4.1.10 is relative stable, and the new installer of that will be released soon.

Thanks
