### ISSUE TITLE
conda env remove fails: AttributeError: 'module' object has no attribute 'PREFIX'

### ISSUE THREAD

**Issue by chicagofire** [conda/conda#3039]
`--> conda env remove -n jmmp
Using Anaconda Cloud api site http://anaconda:8080/api
Fetching package metadata ...........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/auto/foopen/CONDA/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/auto/foopen/CONDA/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/auto/foopen/CONDA/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/auto/foopen/CONDA/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'

`--> conda info
Using Anaconda Cloud api site http://anaconda:8080/api
Current conda install:

             platform : linux-64
        conda version : 4.1.3
    conda-env version : 2.5.0
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /auto/foopen/CONDA  (writable)
  default environment : /auto/foopen/CONDA/envs/jmmp2
     envs directories : /auto/foopen/CONDA/envs
        package cache : /auto/foopen/CONDA/pkgs
         channel URLs : http://anaconda:8080/conda/t/<TOKEN>/anaconda/linux-64/
                        http://anaconda:8080/conda/t/<TOKEN>/anaconda/noarch/
                        http://anaconda:8080/conda/t/<TOKEN>/creditit/linux-64/
                        http://anaconda:8080/conda/t/<TOKEN>/creditit/noarch/
                        http://anaconda:8080/conda/t/<TOKEN>/vurazov/linux-64/
                        http://anaconda:8080/conda/t/<TOKEN>/vurazov/noarch/
                        http://anaconda:8080/conda/t/<TOKEN>/michael/linux-64/
                        http://anaconda:8080/conda/t/<TOKEN>/michael/noarch/
          config file : /home/jmayes/.condarc
         offline mode : False
    is foreign system : False

**Comment by HugoTian** [comment]
Could you please update the conda, by running conda update conda .

I did not see line 73 in conda_env/cli/main_remove.py in version 4.1.8
