### ISSUE TITLE
activate: not an identifier bug

### ISSUE THREAD

**Issue by Zibi92** [conda/conda#3042]
Bug with zsh (Version 5.0.2 on CentOS 7) and oh-my-zsh, when activating an environment:

`miniconda3/bin/activate:65: not an identifier: %{$fg[cyan]%}%n%{$reset_color%}:%{$fg[green]%}%c%{$reset_color%}$(git_prompt_info)`

Changing 
`export CONDA_PS1_BACKUP=$PS1`
to
`export CONDA_PS1_BACKUP="$PS1"`

Fixed my issue, but I didn't manage to make a pull request.

**Comment by HugoTian** [comment]
Thanks for you help, and did you make that PR yet ?

Could you refer to this issue when you make the PR, Thanks
