### ISSUE TITLE
Make conda have an option modify the path to the dynamic linker/loader

### ISSUE THREAD

**Issue by Horta** [conda/conda#3058]
Much like
`conda --set-interpreter /path/to/ld-linux.so`

I've encountered a problem while using Red Hat 7.1 with Linuxbrew and Conda. Red Hat 7.1 is an old distribution and Linuxbrew provide a solution for having more up-to-date libraries (in special, glibc, dynamic linker/loader, gcc compiler, stdc++)  for those without root privileges (common case in clusters).

However, Anaconda distribution had all its binaries pointing to the old /lib64/ld-linux-x86-64.so.2, which means that python packages compiled later via the gcc compiler provided by linuxbrew wouldn't work as conda python would load the old glibc but those compiled libraries would request incompatible but newer infrastructure libs (like libstdc++) provided by linuxbrew.

Here is the link to the problem I found and a solution: https://github.com/Linuxbrew/brew/issues/77#issuecomment-232248602

Just a suggestion. Not sure if it makes sense or just complicate things as the problematic python package came from pip, and not from conda repositories. But I suspect people might face very similar problems with many R packages that are not provided in the R channel.

**Comment by mingwandroid** [comment]
IMHO mixing distros is a very bad idea (if the `.so` that was linked at build time isn't the one that is found then symbols will not resolve). I would be strongly against anything that tries to imply that mixing distros is OK and this suggestion fits into that category.

If you need a certain package built, please build it with `conda-build` in a compatible way.
