### ISSUE TITLE
Most recent jupyter crashes notebook

### ISSUE THREAD

**Issue by willgdjones** [conda/conda#3062]
Hi there, the most recent jupyter version 4.1.0 is crashing on startup for me.

Starting from scratch,

`conda create -n test jupyter`

and then,

`source activate test`

followed by

`jupyter notebook`

gives me

Traceback (most recent call last):
  File "/Users/fonz/anaconda2/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 31, in <module>
    from zmq.eventloop import ioloop
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/**init**.py", line 49, in <module>
    from zmq import backend
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/**init**.py", line 41, in <module>
    reraise(*exc_info)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/**init**.py", line 29, in <module>
    _ns = select_backend(first)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/**init**.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Library not loaded: @rpath/libsodium.4.dylib
  Referenced from: /Users/fonz/anaconda2/lib/libzmq.4.dylib
  Reason: image not found

**Comment by willgdjones** [comment]
My installed conda packages are:

#
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               1.0.0                    py27_1
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bwa                       0.7.13                        0    biobuilds
db                        6.1.26                        0    biobuilds
perl-threaded             5.22.0                       10    bioconda
bitarray                  0.8.1                    py27_0
conda                     4.1.8                    py27_0
conda-build               1.21.5                   py27_0
conda-env                 2.5.1                    py27_0
configobj                 5.0.6                    py27_0
configparser              3.5.0b2                  py27_1
decorator                 4.0.10                   py27_0
entrypoints               0.2.2                    py27_0
ghost.py                  0.2.1                    py27_0    equipoise
freetype                  2.5.5                         1
functools32               3.2.3.2                  py27_0
gdbm                      1.11                          0
get_terminal_size         1.0.0                    py27_0
httplib2                  0.9.2                     <pip>
ipykernel                 4.3.1                    py27_0
ipython                   5.0.0                    py27_0
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jinja2                    2.8                      py27_1
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.1.0                    py27_0
launcher                  1.0.0                         3
libsodium                 1.0.3                         0
libxslt                   1.1.28                        2
markupsafe                0.23                     py27_2
mistune                   0.7.2                    py27_1
mkl                       11.3.3                        0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.0.1                    py27_0
node-webkit               0.10.1                        0
notebook                  4.2.1                    py27_0
openssl                   1.0.2h                        1
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.7.2                    py27_0
pip                       8.1.2                     <pip>
pip                       8.1.2                    py27_0
ply                       3.8                      py27_0
prompt_toolkit            1.0.3                    py27_0
ptyprocess                0.5.1                    py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_1
pygments                  2.1.3                    py27_0
pyqt                      4.11.4                   py27_3
python                    2.7.12                        1
python.app                1.2                      py27_4
pyyaml                    3.11                     py27_4
qt                        4.8.7                         3
qtconsole                 4.2.1                    py27_0
jpeg                      8d                            2    r
libgcc                    4.8.5                         1    r
libpng                    1.6.17                        0    r
libxml2                   2.9.2                         1    r
pyzmq                     14.5.0                   py27_1    r
singledispatch            3.4.0.3                  py27_1    r
zeromq                    4.0.5                         1    r
zlib                      1.2.8                         1    r
readline                  6.2                           2
redis                     3.2.0                         0
requests                  2.10.0                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.7                   py27_0
setuptools                23.0.0                   py27_0
simplegeneric             0.8.1                    py27_1
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
sshuttle                  0.78.0                    <pip>
ssl_match_hostname        3.4.0.2                  py27_1
terminado                 0.6                      py27_0
tk                        8.5.18                        0
tornado                   4.3                      py27_1
traitlets                 4.2.1                    py27_0
unicodecsv                0.14.1                   py27_0
wcwidth                   0.1.7                    py27_0
wheel                     0.29.0                   py27_0
xz                        5.2.2                         0
yaml                      0.1.6                         0

**Comment by willgdjones** [comment]
I've gone through everything in this post but still no avail https://github.com/conda/conda/issues/1722.

Would greatly appreciated any help!

Thanks

**Comment by willgdjones** [comment]
Also the error still occurs with a clean install on anaconda https://github.com/jupyter/jupyter/issues/184

**Comment by willgdjones** [comment]
FIXED. My libsodium was out of date. Need to keep my brew packages updated

**Comment by willgdjones** [comment]
Nope still a problem

**Comment by willgdjones** [comment]
UPDATE - this should be an easy fix, as running

`jupyter notebook` OUTSIDE of my test environment completes successfully.

Thanks!

Will

**Comment by Bartcardi** [comment]
Not a sustainable solution, but for me changing libsodium.13.dylib (or whatever version is applicable to you) to libsodium.4.dylib got the notebook started. Not sure about the implications though.

**Comment by willgdjones** [comment]
Hey @Bartcardi so you can reproduce this I'm not going crazy?

Thanks

**Comment by willgdjones** [comment]
This fix works for me too
