### ISSUE TITLE
setuptools hard build dependency

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#3079]
Here: https://github.com/conda/conda/blob/master/setup.py#L8

@kalefranz I thought we had agreed that setuptools is not going to be a hard build dependency anymore.

**Comment by ilanschnell** [comment]
If you don't want to hard code all the packages (because you're vendoring so many things now), you can use this code:
```
import os
from fnmatch import fnmatchcase
from distutils.util import convert_path

def find_packages(where='.', exclude=()):
    out = []
    stack=[(convert_path(where), '')]
    while stack:
        where, prefix = stack.pop(0)
        for name in os.listdir(where):
            fn = os.path.join(where,name)
            if ('.' not in name and os.path.isdir(fn) and
                os.path.isfile(os.path.join(fn, '__init__.py'))
            ):
                out.append(prefix+name)
                stack.append((fn, prefix+name+'.'))
    for pat in list(exclude) + ['ez_setup', 'distribute_setup']:
        out = [item for item in out if not fnmatchcase(item, pat)]
    return out
```

**Comment by kalefranz** [comment]
Actually, I thought you'd think this build dependency was ok.  I'm still using the `setup` function from distutils, not from setuptools.
https://github.com/conda/conda/blob/master/setup.py#L12

**Comment by ilanschnell** [comment]
No, `from distutils.core import setup` doesn't help, because `setuptools` monkeypatches `distutils` somehow.  When I add `setuptools` as a build dependency, I also have to add `pycosat`.  I'm not sure exactly what setuptools does, not it's safest to not depend on it.

**Comment by kalefranz** [comment]
Grrrrrrrrr that sucks.  OK I'll fix it with the function you suggest.

**Comment by ilanschnell** [comment]
Thanks!  Setuptools does crazy stuff, so the best is to avoid it when possible.
