### ISSUE TITLE
activate script should manage LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#308]
The activate script should check to see if LD_LIBRARY_PATH is set.   If it is, then activate should pre-pend the correct /lib directory to LD_LIBRARY_PATH as well as updating PATH

**Comment by nnashok** [comment]
Another valid scenario is when you have a software collection (e.g rh-nodejs4 on RHEL) which require setting the LD_LIBRARY_PATH for its programs to work. Now when I run condo to build a package that depends on this software collection, the LD_LIBRARY_PATH is being unset causing the build to fail. Specifically:
My package requires rh-nodejs4. rh-nodejs4 is installed as a software collection (scl, https://www.softwarecollections.org/). Even after I activate the collection, when I try to build my package, condo is unsetting the LD_LIBRARY_PATH causing the build to fail.

Please correct me if I'm looking in the wrong direction.
