### ISSUE TITLE
got 'PermissionError' when create a new conda environment

### ISSUE THREAD

**Issue by Sushengdai** [conda/conda#3085]
jupyter_consol 100% |###############################| Time: 0:00:00 801.16 kB/s
notebook-4.2.1 100% |###############################| Time: 0:00:02   2.15 MB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:00 750.93 kB/s
ipywidgets-4.1 100% |###############################| Time: 0:00:00 816.22 kB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00 296.89 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\Scripts\conda-env-scri
pt.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a_env\cli\main_create.py", line 99, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a_env\installers\conda.py", line 20, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\install.py", line 245, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\Users\DLN234\AppData\Loc
al\Continuum\Anaconda3\pkgs\mkl-11.3.3-1.tmp' -> 'C:\Users\DLN234\AppData
\Local\Continuum\Anaconda3\pkgs\mkl-11.3.3-1'

**Comment by HugoTian** [comment]
@Sushengdai can you give men your "conda info" output ?

**Comment by Sushengdai** [comment]
I’m reinstalling Anaconda now. I will keep you updated.

**Comment by kalefranz** [comment]
This is on Windows, and there have been several fixes recently for this situation.  Please make sure you're , running conda 4.1.8 with `conda update conda`.  And definitely let us know if that doesn't fix it!

**Comment by Sushengdai** [comment]
The same error occurred after reinstall Anaconda. Let me update conda and try again. Thanks,

honTraining\CapitalOne-Training-2016-07-19>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\DLN234\AppData\Local\Continuum\Anaconda3  (writ
able)
  default environment : C:\Users\DLN234\AppData\Local\Continuum\Anaconda3
     envs directories : C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\envs
        package cache : C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
Actually, I would have expected 4.1.6 to work correctly here.  I don't think there's anything in 4.1.7 or 4.1.8 to address this permissions issue.  But please let us know either way.

**Comment by Sushengdai** [comment]
I still got the same error after update to conda 4.1.8. But after I did “conda install mkl”, the permission error is gone. Unfortunately, I got new error as below.

Collecting bloscpack>=0.8.0 (from castra)
  Downloading bloscpack-0.10.0.tar.gz (90kB)
    100% |################################| 92kB 264kB/s
Collecting blosc (from castra)
  Downloading blosc-1.3.3.tar.gz (269kB)
    100% |################################| 276kB 386kB/s
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2 in
c:\users\dln234\appdata\local\continuum\anaconda3\envs\anaconda_training\lib\sit
e-packages (from pandas->castra)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in c:\user
s\dln234\appdata\local\continuum\anaconda3\envs\anaconda_training\lib\site-packa
ges (from pandas->castra)
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\dln234
\appdata\local\continuum\anaconda3\envs\anaconda_training\lib\site-packages (fro
m bloscpack>=0.8.0->castra)
Building wheels for collected packages: memory-profiler, castra, bloscpack, blos
c
  Running setup.py bdist_wheel for memory-profiler ... done
  Stored in directory: C:\Users\DLN234\AppData\Local\pip\Cache\wheels\18\b1\c5\f
8e94cea18d00a5121918e8e9ff6f0d5b5036c980398a9228f
  Running setup.py bdist_wheel for castra ... done
  Stored in directory: C:\Users\DLN234\AppData\Local\pip\Cache\wheels\54\85\40\5
bd60d9883915fb662038079976f8b53f68efcb632b54323f4
  Running setup.py bdist_wheel for bloscpack ... done
  Stored in directory: C:\Users\DLN234\AppData\Local\pip\Cache\wheels\58\12\d0\8
d5999926a30c363cdb4a8eb7b5d4009bd0f876fbbfea116b3
  Running setup.py bdist_wheel for blosc ... error
  Complete output from command C:\Users\DLN234\AppData\Local\Continuum\Anaconda3
\envs\anaconda_training\python.exe -u -c "import setuptools, tokenize;__file__='
C:\\Users\\DLN234\\AppData\\Local\\Temp\\pip-build-pey52rl1\\blosc\\setup.py';ex
ec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'
), __file__, 'exec'))" bdist_wheel -d C:\Users\DLN234\AppData\Local\Temp\tmpltsb
8np2pip-wheel- --python-tag cp34:
  SSE2 detected
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.4
  creating build\lib.win-amd64-3.4\blosc
  copying blosc\test.py -> build\lib.win-amd64-3.4\blosc
  copying blosc\toplevel.py -> build\lib.win-amd64-3.4\blosc
  copying blosc\version.py -> build\lib.win-amd64-3.4\blosc
  copying blosc\__init__.py -> build\lib.win-amd64-3.4\blosc
  running build_ext
  building 'blosc.blosc_extension' extension
  error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

  ----------------------------------------
  Failed building wheel for blosc
  Running setup.py clean for blosc
Successfully built memory-profiler castra bloscpack
Failed to build blosc
Installing collected packages: memory-profiler, blosc, bloscpack, castra
  Running setup.py install for blosc ... error
    Complete output from command C:\Users\DLN234\AppData\Local\Continuum\Anacond
a3\envs\anaconda_training\python.exe -u -c "import setuptools, tokenize;__file__
='C:\\Users\\DLN234\\AppData\\Local\\Temp\\pip-build-pey52rl1\\blosc\\setup.py';
exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\
n'), __file__, 'exec'))" install --record C:\Users\DLN234\AppData\Local\Temp\pip
-pjzm1tkb-record\install-record.txt --single-version-externally-managed --compil
e:
    SSE2 detected
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\blosc
    copying blosc\test.py -> build\lib.win-amd64-3.4\blosc
    copying blosc\toplevel.py -> build\lib.win-amd64-3.4\blosc
    copying blosc\version.py -> build\lib.win-amd64-3.4\blosc
    copying blosc\__init__.py -> build\lib.win-amd64-3.4\blosc
    running build_ext
    building 'blosc.blosc_extension' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).


    ----------------------------------------
Command "C:\Users\DLN234\AppData\Local\Continuum\Anaconda3\envs\anaconda_trainin
g\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DLN234\\App
Data\\Local\\Temp\\pip-build-pey52rl1\\blosc\\setup.py';exec(compile(getattr(tok
enize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"
install --record C:\Users\DLN234\AppData\Local\Temp\pip-pjzm1tkb-record\install
-record.txt --single-version-externally-managed --compile" failed with error cod
e 1 in C:\Users\DLN234\AppData\Local\Temp\pip-build-pey52rl1\blosc\
Error: pip returned an error.

**Comment by kalefranz** [comment]
So the original issue was actually caused by your virus scanner holding a file system lock on the extracted MKL tarball. We still have work to do to tune our backoff function here and wait for your virus scanner to finish. 

The new error is from pip, no? In that case, you've now got the wrong github repo for the issue :)
