### ISSUE TITLE
documented way to detect which conda environment is active, read conda-meta .json

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3090]
I have been transitioning a build system to work against conda. A feature of the build system is building the link line compiling C++ applications. It would be nice if I could detect if a conda environment is active from my scripts, as well as which one, and then further go into the conda-meta directory and parse the .json files there to read what shared object libraries are associated with different packages - I realize that guessing which of the .so files listed in the .json files is needed to link against the package is not bullet proof, the goal is doing something that gets it right most of the time.

I had been looking at the environment variable (this is in linux) CONDA_ENV_PATH in a previous version of conda, but now I see I need to look at CONDA_PREFIX. Since it has changed, I realize my method of determining which conda environment is active is hacky.

Is it possible to nail down a environment variable that users could rely on to detect which conda environment is active? Can I rely on the subdirectory named 'conda-meta' being present, along with the current structure of the .json files in there?

**Comment by kalefranz** [comment]
`CONDA_ENV_PATH` holds either the environment name, or a path to the environment.  `CONDA_PREFIX` is guaranteed to hold the full path to the active environment. (At least as of conda 4.1.)

>  Can I rely on the subdirectory named 'conda-meta' being present, along with the current structure of the .json files in there?

Yes!  To detect if a directory *is* a conda prefix, you can test of the existence of a `conda-meta/history` file.  As to the structure of the json files in the conda-meta directory, any change other than pure additions will go through a well-documented an lengthy migration plan.  But I really don't foresee any real breaking changes at any point on the horizon.  Only additions to what's already there.

I guess at some point it makes sense to start using a `version` key within those json files, just to be safe.  I'll add that next time we make a change in that area.  Still, the first will be a simple addition to what's already there.
