### ISSUE TITLE
list of conflict sometimes uninformative

### ISSUE THREAD

**Issue by cel4** [conda/conda#3092]
I am trying to update a python-2.7 environment to the latest anaconda version and get following error message:

```
conda install anaconda=4.1.1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda 4.1.1*
Use "conda info <package>" to see the dependencies for each package.
```

This output is confusing - what exactly is it in conflict with?

Produced with conda-4.1.8 on macOS

**Comment by HugoTian** [comment]
Could you please retry this installation now, and I think it will work.

If still have problem, feel free to reopen this and @ me
