### ISSUE TITLE
Conda-specific conflict between python 3.5 and version pandas 0.17.1

### ISSUE THREAD

**Issue by jess010** [conda/conda#3093]
When attempting to set up conda environment to contribute to mesa project, a conflict was reported between pandas 0.17.1 and python 3.5.

Workflow that generated conflict was as follows using an OSX terminal:
1) Created conda environment using: "conda create -n mesa python=3"
2) Added packages from requirements.txt as follows: "conda install pandas=0.17.1 jupyter=1.0.0 coverage=4.1 nose=1.3.7 tornado=4.0.2"
3) Got conflict message: "The following specifications were found to be in conflict:
- pandas 0.17.1*
- python 3.5\* "

Not clear what the source of this issue is, this may be related to #2791. It was suggested by @jackiekazil suggested that I raise an issue for this in this repo to start.

**Comment by jackiekazil** [comment]
To add... I suggested this repo, because pandas 0.17.1 and python 3.5 works with virtualenv, but not conda.

**Comment by kalefranz** [comment]
I'm guessing the pandas package just wasn't built yet, and you're issue has resolved itself by now.  If not, conda 4.3 will give better, if still not perfect, hints.
