### ISSUE TITLE
Error for Python 3 conda env set up

### ISSUE THREAD

**Issue by jess010** [conda/conda#3095]
Got this error using the following on Mac OSX. The conda environment is available, despite the error.

1) conda create -n sample python=3.5

Output message:
Warning: could not import binstar_client ('args' object has no attribute 'token')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "//anaconda/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by HugoTian** [comment]
Hi, I am actually working on this bug. Others have some issue when run 

    conda info

First, please run conda info, if the version is not 4.1.8, please update to latest version using 

    conda update conda

Then, if you run into same error when run "conda info", could you run "conda --debug info" to see whether you get log message like "args has no attribute site". If so, please refer to issue #3070. Otherwise, please show the output

Thanks

**Comment by jess010** [comment]
Thanks for your help. I got an error on running "conda info", see below. I was able to verify the conda version is up to 4.1.8 using conda --version conda. 

Warning: could not import binstar_client ('args' object has no attribute 'token')INFO:stderrlog:Warning: could not import binstar_client ('args' object has no attribute 'token')
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "//anaconda/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

I got the same error when running conda --debug info. After I installed anaconda-client though I was able to run both the conda info and conda --debug info commands. This produces the following output: 


Current conda install:

             platform : osx-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.3.1
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False


Still having issues with the conda env though. Different error message, as follows:


An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 431, in install
    print_activate(args.name if args.name else prefix)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 100, in print_activate
    shell = find_parent_shell(path=False)
  File "//anaconda/lib/python2.7/site-packages/conda/utils.py", line 260, in find_parent_shell
    pname = process.parent().name().lower()
TypeError: 'Process' object is not callable

**Comment by HugoTian** [comment]
1. Based on the warning info," Warning: could not import binstar_client ('args' object has no attribute 'token') ", I think the bug is in binstar_client package. Could you please check  "/anaconda/lib/python2.7/site-packages/binstar_client/utils/____init____.py" file. In this file, there should be a get_binstar function, and in that function, there should be code like following

    token = getattr(args, 'token', None)
    log_level = getattr(args, 'log_level', logging.INFO)
    site = getattr(args, 'site', None)

This code will not give you error, if you find your code is different than this, please try conda update anaconda-client. Hope it will fix the issue

2. The TypeError you get, "Process Object is not callable", I think, is due to the version of psutil module. Could you please try conda update psutil. Hope it will fix the issue.

Thanks again for your information, it really helps to make conda stable.

**Comment by jess010** [comment]
No problem, thank you for your help! From the __init__.py file you referenced, the entire function is as follows, it looks to contain the exact text you specified:

def get_binstar(args=None, cls=None):
    """
    DEPRECATED METHOD,


    use `get_server_api`
    """

    warnings.warn(
      'method get_binstar is deprecated, please use `get_server_api`',
      DeprecationWarning
    )

    token = getattr(args, 'token', None)
    log_level = getattr(args, 'log_level', logging.INFO)
    site = getattr(args, 'site', None)

    aserver_api = get_server_api(token, site, log_level, cls)
    return aserver_api

I did 'conda update psutils', it turned out I was running 1.2.1-py27_0, this got updated to 4.3.0-py27_0. Tried running the 'conda create -n sample3 python=3.5'. Worked just fine. From my perspective, this issue is resolved. 

Really appreciate your assistance with this!
