### ISSUE TITLE
trouble with using conda to install R-essential 

### ISSUE THREAD

**Issue by Luxios** [conda/conda#3098]
I am sorry but I have met problems as following :
 Extracting packages ...
 [ COMPLETE ]|##################################################| 100%
 Unlinking packages ...
 [ COMPLETE ]|##################################################| 100%
 Linking packages ...
 'mingw-w64\bin\p11-kit.exe' Not an internal or external command, neither an exe nor bat.  | 12%
 The system can't find the directory properly

 [ COMPLETE ]|##################################################| 100%

After this I open the jupyter notebook, and build a new R script , it happens to me that
 the kernel is always dead. Even R-gui.exe in the Folder can not be used. But I change to use python ,it works well. How can I solve this problem?

**Comment by mingwandroid** [comment]
No need to be sorry! Did you activate your `conda` environment from the commandline before running `jupyter notebook` from that same command line?

**Comment by Luxios** [comment]
Do you mean to activate the my-r-env environment? What the command is for example? I just followed this article, https://www.continuum.io/blog/developer/jupyter-and-conda-r  .
And when I click on the  R-gui.exe ,it says I lack some .dll files. I downloaded those files but it didn't work.How can I set the path correctly and run it from the correct environment...

**Comment by mingwandroid** [comment]
You are meant to run, from cmd.exe `<conda_install_root>\Scripts\activate.bat` then `jupyter notebook`, or use `Anaconda Navigator`.
