### ISSUE TITLE
Cannot install - pyproj=1.9.4=py27_1 but it is listed on anaconda.org

### ISSUE THREAD

**Issue by cpaulik** [conda/conda#3103]
My `environment.yml` file stopped working recently and I can no longer install
- proj.4 4.9.1 0
- pyproj 1.9.4 py27_1

The strange thing is that both versions are listed on anaconda.org

see for [pyproj](https://anaconda.org/anaconda/pyproj/files?version=1.9.4&page=2)
 and [proj.4](https://anaconda.org/anaconda/proj.4/files?version=4.9.1)

But pyproj is not available under https://repo.continuum.io/pkgs/free/linux-64/ which is the channel url that `conda info` gives me.

see also https://travis-ci.org/TUW-GEO/pynetCF/jobs/145542052

**Comment by lacardonap** [comment]
Hello cpaulik,

Can you resolved this problem? I have the same if you can help me I would appreciate.

Thaks a lot,

Leo Cardona

**Comment by cpaulik** [comment]
We've switched to pyproj 1.9.5 in the meantime. If you really need 1.9.4 you should be able to use the conda-forge builds https://anaconda.org/conda-forge/pyproj/files?version=1.9.4

**Comment by lacardonap** [comment]
I used pyproj=1.9.5.1=py27_0 and It was useful for me.  Thanks you for your help.
