### ISSUE TITLE
conda solver not installing the packages I would expect it to

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#3105]
Here is the history file for an environment:

```
==> 2016-07-17 22:21:26 <==
# cmd: /Users/aaronmeurer/anaconda3/bin/conda create -n test ipython=4.2 pytest python=3.5
appnope-0.1.0-py35_0
asmeurer::zlib-1.2.8-1
backports-1.0-py35_0
decorator-4.0.10-py35_0
get_terminal_size-1.0.0-py35_0
ipython-4.2.0-py35_1
ipython_genutils-0.1.0-py35_0
openssl-1.0.2h-1
path.py-8.2.1-py35_0
pexpect-4.0.1-py35_0
pickleshare-0.7.2-py35_0
pip-8.1.2-py35_0
ptyprocess-0.5.1-py35_0
py-1.4.31-py35_0
pytest-2.9.2-py35_0
python-3.5.2-0
python.app-1.2-py35_4
readline-6.2-2
setuptools-23.0.0-py35_0
simplegeneric-0.8.1-py35_1
sqlite-3.13.0-0
tk-8.5.18-0
traitlets-4.2.1-py35_0
wheel-0.29.0-py35_0
xz-5.2.2-0
# create specs: ['ipython 4.2*', 'pytest', 'python 3.5*']
==> 2016-07-18 13:40:12 <==
# cmd: /Users/aaronmeurer/anaconda3/envs/test/bin/conda install python=2.7
-appnope-0.1.0-py35_0
-backports-1.0-py35_0
-decorator-4.0.10-py35_0
-get_terminal_size-1.0.0-py35_0
-ipython-4.2.0-py35_1
-ipython_genutils-0.1.0-py35_0
-path.py-8.2.1-py35_0
-pexpect-4.0.1-py35_0
-pickleshare-0.7.2-py35_0
-pip-8.1.2-py35_0
-ptyprocess-0.5.1-py35_0
-py-1.4.31-py35_0
-pytest-2.9.2-py35_0
-python-3.5.2-0
-python.app-1.2-py35_4
-setuptools-23.0.0-py35_0
-simplegeneric-0.8.1-py35_1
-traitlets-4.2.1-py35_0
-wheel-0.29.0-py35_0
+appnope-0.1.0-py27_0
+asmeurer::decorator-3.4.0-py27_1
+asmeurer::ipython-1.0.0rc1-py27_0
+asmeurer::path.py-5.2-py27_0
+asmeurer::pexpect-2.4-py27_0
+asmeurer::py-1.4.19-py27_0
+asmeurer::pytest-2.5.1-py27_0
+asmeurer::six-1.3.0-py27_0
+asmeurer::wheel-0.22.0-py27_3
+backports-1.0-py27_0
+get_terminal_size-1.0.0-py27_0
+ipython_genutils-0.1.0-py27_0
+pathlib2-2.1.0-py27_0
+pickleshare-0.7.2-py27_0
+pip-8.1.2-py27_0
+ptyprocess-0.5.1-py27_0
+python-2.7.12-1
+python.app-1.2-py27_4
+setuptools-23.0.0-py27_0
+simplegeneric-0.8.1-py27_1
+traitlets-4.2.1-py27_0
# install specs: ['python 2.7*']
==> 2016-07-18 13:43:59 <==
# cmd: /Users/aaronmeurer/anaconda3/envs/test/bin/conda install ipython=4.2
-asmeurer::ipython-1.0.0rc1-py27_0
+ipython-4.2.0-py27_1
# install specs: ['ipython 4.2*', 'python 2.7* (target=python-2.7.12-1.tar.bz2)']
==> 2016-07-18 13:44:41 <==
# cmd: /Users/aaronmeurer/anaconda3/envs/test/bin/conda install six=1.10
-asmeurer::six-1.3.0-py27_0
+six-1.10.0-py27_0
# install specs: ['six 1.10*', 'python 2.7* (target=python-2.7.12-1.tar.bz2)']
==> 2016-07-18 13:45:53 <==
# cmd: /Users/aaronmeurer/anaconda3/envs/test/bin/conda install python=3.5 ipython=4.2
-appnope-0.1.0-py27_0
-asmeurer::decorator-3.4.0-py27_1
-asmeurer::path.py-5.2-py27_0
-asmeurer::pexpect-2.4-py27_0
-asmeurer::py-1.4.19-py27_0
-asmeurer::pytest-2.5.1-py27_0
-asmeurer::wheel-0.22.0-py27_3
-backports-1.0-py27_0
-get_terminal_size-1.0.0-py27_0
-ipython-4.2.0-py27_1
-ipython_genutils-0.1.0-py27_0
-pathlib2-2.1.0-py27_0
-pickleshare-0.7.2-py27_0
-pip-8.1.2-py27_0
-ptyprocess-0.5.1-py27_0
-python-2.7.12-1
-python.app-1.2-py27_4
-setuptools-23.0.0-py27_0
-simplegeneric-0.8.1-py27_1
-six-1.10.0-py27_0
-traitlets-4.2.1-py27_0
+appnope-0.1.0-py35_0
+backports-1.0-py35_0
+decorator-4.0.10-py35_0
+get_terminal_size-1.0.0-py35_0
+ipython-4.2.0-py35_1
+ipython_genutils-0.1.0-py35_0
+path.py-8.2.1-py35_0
+pathlib2-2.1.0-py35_0
+pexpect-4.0.1-py35_0
+pickleshare-0.7.2-py35_0
+pip-8.1.2-py35_0
+ptyprocess-0.5.1-py35_0
+py-1.4.31-py35_0
+pytest-2.9.2-py35_0
+python-3.5.2-0
+python.app-1.2-py35_4
+setuptools-23.0.0-py35_0
+simplegeneric-0.8.1-py35_1
+six-1.10.0-py35_0
+traitlets-4.2.1-py35_0
+wheel-0.29.0-py35_0
# install specs: ['python 3.5*', 'ipython 4.2*']
```

Let's decompose what happened here:
1. I created an environment with IPython 4.2 and Python 3.5. You can't see it here, but the reason I included Python 3.5 was that `conda create -n test ipython=4.2 pytest` defaulted to Python 2.7 (even though my conda is itself in Python 3.5).
2. I converted the environment to Python 2.7 with `conda install python=2.7`. This chose IPython 1.0 (!) from my channel. 
3. I fixed this by installing `ipython=4.2` manually.
4. `ipython` was then broken, because of a too old version of six, 1.3. At this point _both_ `conda install six` and `conda update six` did nothing. I had to manually conda install six=1.10 to update it. 

The final command reverted back to Python 3.5, which seems to have worked correctly. 

So there are a few bugs here:
- conda didn't pick the latest version of Python when I created the environment. I know that this sort of thing is technically possible in the solver because newer versions of one package require older versions of another, but there are so many versions of Python that this seems unlikely. Is it possible the way the solver picks the best solution changed? It should be picking latest versions, then fewest packages to break ties. 
- Downgrading Python picked very old versions of some dependencies, for now apparent reason.
- Updating IPython didn't update its dependencies. There's a reason the [update_dependencies](http://conda.pydata.org/docs/config.html#disable-updating-of-dependencies-update-dependencies) option was set to default to true. 
- Both `conda install six` and `conda update six` didn't update six. I would expect at least one, if not both to do it. I believe it used to work that install always installed it, and update would skip it if the package was already the latest version (the difference being if a dependency might also be updated otherwise). 

Everything was done with 

```
Current conda install:

             platform : osx-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : /Users/aaronmeurer/anaconda3  (writable)
  default environment : /Users/aaronmeurer/anaconda3/envs/test
     envs directories : /Users/aaronmeurer/anaconda3/envs
        package cache : /Users/aaronmeurer/anaconda3/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/asmeurer/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/asmeurer/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/pyne/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/pyne/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/jjhelmus/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/jjhelmus/noarch/
          config file : /Users/aaronmeurer/.condarc
         offline mode : False
    is foreign system : False
```

CC @mcg1969

**Comment by mcg1969** [comment]
> the reason I included Python 3.5 was that conda create -n test ipython=4.2 pytest defaulted to Python 2.7 (even though my conda is itself in Python 3.5).

Not sure why that be, but I'm going to set that aside for the moment because that's a separate issue from the solver itself (it's an `add_defaults_to_specs` issue, most likely).

> I converted the environment to Python 2.7 with conda install python=2.7. This chose IPython 1.0 (!) from my channel.

Yes. That's because it's preferring _any_ version of iPython in your channel over _any_ version in the lower-priority `defaults` channel. Forcing `ipython=4.2` made it drop down to `defaults` to pick a compatible one.

This would be a good argument for changing the channel priority behavior to _ignore_ packages from a lower-priority channel. But this must also coincide with the ability to explicitly specify the channel you want to pull a package from. We're working on that.

Moral of this story, for now: don't keep packages in your personal channel that you don't intend to use.

> Updating IPython didn't update its dependencies. There's a reason the update_dependencies option was set to default to true.

Well, we might disagree on what `update_dependencies` should do. As we have it now, it's primary function is to _prevent_ dependencies from being updated when set to `False`, for users who don't want to change any other packages in their environment. 

When it is `True`, we are *not* giving Conda carte blanche to update everything. Instead, `conda` updates dependences *on an as-needed basis*. When a dependency *does* need to be updated, it is updated as much as possible; but if the current dependency is sufficient to handle the requested package, it is not touched. And according to `conda info ipython=4.2.0=py27_1`, all of the dependencies currently in your environment at this point were satisfactory.

We went back and forth on this when the new solver was being demonstrated. People were quite concerned that the more aggressive dependency resolution was effectively going to force far too many updates.

So conda is behaving as expected here. I'd argue this is a bug in `ipython`'s conda recipe.

> Both conda install six and conda update six didn't update six. I would expect at least one, if not both to do it.

That's because it's the latest version of `six` in your channel. Again, it behaved as expected here.

It looks like you'd be a good candidate for `channel_priority: False`. This way, you'll get the latest versions of the packages, whether or not they come from your channel. With that setting, the sort order is version, then channel, then build (because build numbers are not comparable across channels).

**Comment by asmeurer** [comment]
Oooh, so the priority changes that happened were channel priority. I had heard some rumblings about that at SciPy, but I didn't know exactly what it was. 

So I need to move my channel down in priority (I don't build stuff any more). I think a good order for me would be 

```
- conda-force
- defaults
- asmeurer
# Everything else
```

**Comment by asmeurer** [comment]
> When it is True, we are not giving Conda carte blanche to update everything. Instead, conda updates dependences on an as-needed basis. When a dependency does need to be updated, it is updated as much as possible; but if the current dependency is sufficient to handle the requested package, it is not touched. And according to conda info ipython=4.2.0=py27_1, all of the dependencies currently in your environment at this point were satisfactory.

That's what the `false` value is supposed to do. What does setting it to false actually do? Create inconsistent solutions?

> We went back and forth on this when the new solver was being demonstrated. People were quite concerned that the more aggressive dependency resolution was effectively going to force far too many updates.

I get that you don't want to just install something, and have every conda install basically be `conda update --all`. But I would argue that the dependencies for any package that you request should be updated, and it should only be conservative for the other packages that are installed. 

From what I recall, there's three different "strings" of versions for any given package

- The currently installed version
- All versions newer than the currently installed version (in order)
- All versions older than that version

`update_dependencies: true` orders versions basically ignoring the current version. `update_dependencies: false` orders them as `current version > reversed(newer versions) > older versions` (if I remember correctly; please correct me if I am wrong)

Probably a different order is needed, even for `update_dependencies: true` for the tertiary packages that aren't requested or dependencies of what is requested. (and I know that "dependencies of what is requested" is a shaky term)

I get that people are concerned about conda updating more than they want, but the default options to be to keep stuff updated. That option was added for people who want to have more conservative setups.

> So conda is behaving as expected here. I'd argue this is a bug in ipython's conda recipe.

But in reality, almost no recipe specifies a minimum version. This just work because it picks the latest versions. 

I suspect that biggest issue here is not really this, but the channel priority stuff. That sounds like a real mess. Are you changing what `conda config --add channels` does here as well?

**Comment by asmeurer** [comment]
In particular, prepending channels is the wrong thing, given this new logic. TBH, I'm not sold on the new logic. I get that there are issues with the old logic, but I don't see this is a better solution. I'm not the only one who will have outdated stuff in their channel. And as far as the default behavior, most people are just adding channels to get some package, not because they want to use that channel *instead of* `defaults`. I would suggest keeping `channel_priority: false` as the default, and leaving it to be set to `true` for the folks who are curating their channel lists and really do want this behavior.

**Comment by mcg1969** [comment]
> That's what the false value is supposed to do. What does setting it to false actually do? Create inconsistent solutions?

`False` permits _no_ dependency updates. That makes it more likely that the latest version of the requested package cannot be installed, if it requires newer versions of the dependencies than are currently installed.
