### ISSUE TITLE
conda should install python3 automatically if needed

### ISSUE THREAD

**Issue by bgruening** [conda/conda#3106]
The tool hivtrace is a py3k only tool (bioconda channel). If we are in a python2 env, let's say miniconda2 `conda install hivtrace` will fail because conda is trying to get a package for python2. This results in a version conflict.
The correct way to install this package is `conda install hivtrace python==3.5.1` to tell conda that you actually want to have python3. I think this should be done automatically. If there is no python2 version, python3 should be a dependency and it should not fail at first hand.

**Comment by msarahan** [comment]
This is OK for creating a new environment, maybe, but absolutely not for installing into an existing environment.  Changing python version in an environment is very dangerous, and should never be implicit, IMHO.

**Comment by bgruening** [comment]
@msarahan that's true. I was actually talking about creating environments. Sorry for so unprecise.

**Comment by ericenns** [comment]
This issue also occurs for tools that only work on py27 and not py3k.

**Comment by kalefranz** [comment]
As a business rule, we don't switch an environment beyond minor versions without a user explicitly asking for it.  See https://github.com/conda/conda/blob/4.4.11/conda/core/solve.py#L272-L280
