### ISSUE TITLE
clean and minimal Conda environments

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3107]
I might be mistaken, but presently I believe it is necessary that all Conda environments have Python installed (I think to support basic `conda` commands).  It would be nice if a Conda environment could truly be "minimal" and only contain the pieces necessary for that environment to function "stand alone".  E.g. so someone could zip it up and **just** have the pieces necessary for that Conda environment to run (modulo problems of shebang lines).

One possibility for this might be to have `conda` run from its own minimal "locked-down" environment that is distinct from the root environment.  This minimal environment would always be on the path, as well as "one other" environment, defaulting to "root".  This idea has been discussed in the past, some of which is captured in #1022

**Comment by kalefranz** [comment]
See the changelog for 4.2.0.
https://github.com/conda/conda/releases/tag/4.2.0
