### ISSUE TITLE
user config and multiple miniconda/anaconda installations 

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3109]
If one were to centrally administer several conda installs, and users were then to create their own environments, I think there may be issues. I'm thinking of something along the lines of a production miniconda install, and a development miniconda install. I'd prefer just one miniconda install where I maintain separate environments for production vs. development, but there are some packages which can only live in the root environment - namely conda, conda-env and I think conda-build? I'm concerned about issues like https://github.com/conda/conda/issues/3104 where updating conda can leave conda inoperable. I'm thinking the production install will not have conda-build in it. 

As I look at the .condarc and .conda directory that get created for a user of the central install, I can see someone creating an environment based on the production miniconda, which would include links to packages in the production miniconda, but then they may activate this environment from the development miniconda, with unforseen side effects.

I suspect this is an unusual use case, low priority issue, but thought it would be worth noting. I imagine the same issue would arise for a user that is playing two miniconda installs, or a miniconda and a anaconda install.

**Comment by kalefranz** [comment]
The spirit of this ticket goes under the "multiuser-support" category.  We're doing a deep-dive here in either 4.3, 4.4, or 4.5.  Still working out the details one which feature set goes in which sprint.

**Comment by davidslac** [comment]
Great! Looking forward to it. I mentioned this on a separate issue - but somewhere along the line, the .condarc for my central install is no longer being read - may be something to think about for multi-user, how do users mess that up, debug it.

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by kalefranz** [comment]
That condarc file no longer being read should actually be fixed with the 4.2 feature release.  Has a totally new configuration engine.  Docs coming soon.

**Comment by davidslac** [comment]
Thanks! I'll use conda 4.2 from the canary channel - the new features in the github readme sound interesting, docs would be great. 

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by kalefranz** [comment]
Multi-user support should be completely fixed with conda 4.3.  Closing this ticket now.
