### ISSUE TITLE
activate/deactivate as conda commands

### ISSUE THREAD

**Issue by joonro** [conda/conda#3111]
Hi,

I use conda environment a lot, and I wish `activate`/`deactivate` are actual conda subcommands, not separate scripts. At least to me, after creating an environment with `conda create`, switching to another environment with `conda activate` and `conda deactivate` would be very intuitive.

Thanks a lot for the great utility!

**Comment by HugoTian** [comment]
I like the idea, and I think the simple solution is ,

    conda activate  A = source deactivate (if any) + source activate A

I will discuss this with @kalefranz , to see whether we should have this in future version

**Comment by joonro** [comment]
That was exactly what I was thinking - thank you very much for your quick response!

**Comment by kalefranz** [comment]
This is definitely on the roadmap. To do this, `conda` actually needs to become a shell function in addition to an executable on `PATH`.  Here's one example https://github.com/conda/conda/pull/2080

It will definitely happen at some point.

**Comment by kalefranz** [comment]
Resolved with #5044.
