### ISSUE TITLE
`conda update --all` slows down conda afterward

### ISSUE THREAD

**Issue by rlee287** [conda/conda#3122]
After running this in the root environment on Windows, python takes several seconds to start up, and conda is very slow. This occured even after a fresh reinstall of Miniconda.

I just reinstalled Miniconda again. Before I rerun `conda --debug update --all` to produce logs, is there any command that I can use to direct all of the output into a log file? When I tried this earlier, there was so much output that most of it was pushed out of the command window buffer.

**Comment by HugoTian** [comment]
For direct stdout to log file on windows, please refer to this link

https://www.quora.com/In-the-Windows-command-line-how-do-you-redirect-terminal-output-into-a-txt-file

Moreover, after reinstall, is the command run faster ?

**Comment by rlee287** [comment]
Thanks for the reply. After the reinstall, it runs faster, but this is because the miniconda installer at http://conda.pydata.org/miniconda.html does not have the latest package versions. When I update with `conda update --all`, it slows down again.

I will post the update logs once I have a chance.

**Comment by rlee287** [comment]
1. Before update
    1. Ran `conda info --all` and piped to `conda_info_before.txt`.
    2. Ran `tree -a` (from Cygwin) in Miniconda directory and piped to `conda_tree_before.txt`.
2. Updated with `conda --yes --debug update --all` and piped to `conda_update.txt`.
(Weirdly, the debug output is not captured).
3. Repeated step 1, but named the files `conda_info_after.txt` and `conda_tree_after.txt`.

[conda_info_after.txt](https://github.com/conda/conda/files/377498/conda_info_after.txt)
[conda_info_before.txt](https://github.com/conda/conda/files/377501/conda_info_before.txt)
[conda_tree_after.txt](https://github.com/conda/conda/files/377499/conda_tree_after.txt)
[conda_tree_before.txt](https://github.com/conda/conda/files/377500/conda_tree_before.txt)
[conda_update.txt](https://github.com/conda/conda/files/377502/conda_update.txt)

As to the debug output, I noticed a lot of permission errors like the following:
```
WARNING:conda.install:Cannot remove, not empty: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpz6nnwy42
WARNING:conda.install:Cannot remove, permission denied: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpzb3012qw\DLLs\_ssl.pyd
WARNING:conda.install:Cannot remove, not empty: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpzb3012qw\DLLs
WARNING:conda.install:Cannot remove, not empty: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpzb3012qw
WARNING:conda.install:Cannot remove, permission denied: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpzcy9e52f\python35.dll
WARNING:conda.install:Cannot remove, not empty: C:\Users\Ryan\Miniconda3\pkgs\.trash\tmpzcy9e52f
WARNING:conda.install:Cannot remove, not empty: C:\Users\Ryan\Miniconda3\pkgs\.trash
```

I also got ```Warning: somethings is wrong with binstar_client (No module named 'binstar_client')``` when running `conda info --all` after the update.

**Comment by HugoTian** [comment]
First, binstar_client is not necessary for conda functionality. "conda install anaconda-client" will give you the binstar_client library.

Then permission is a priority issue for next conda release, and the conda team is working on this now. In next release, 4.2, we may handle the permission better.

From the log, I cannot tell the reason for the slow-down. Could you please give me more detail ?

when run conda install packages, it has 4 part that may take long, "Solving package specifications",
"Fetching packages", "Extracting packages", "linking packages", can you tell me which part takes long ?

If all of them takes long, and python takes seconds to start up, then I have no idea what's going on and it is hard to reproduce the case. My recommendation will be waiting for next conda release, and next miniconda installer release, which will be much better

**Comment by rlee287** [comment]
The `conda update` command runs normally at normal speed, except for all those permission errors. After the update command, however, conda and python both take seconds to start up.
I guess I will just revert back to a clean installation and wait for 4.2 to come out.

**Comment by rlee287** [comment]
@HugoTian 
In the meantime, I tried reverting with `conda install -r 0`. Even after the revert, conda and python continued to take seconds to start up.

I will reinstall Miniconda and wait for release 4.2, but I will post the logs from the revert in case they may help the developers.

[conda_info_revert.txt](https://github.com/conda/conda/files/379382/conda_info_revert.txt)
[conda_revert.txt](https://github.com/conda/conda/files/379383/conda_revert.txt)
[conda_tree_revert.txt](https://github.com/conda/conda/files/379384/conda_tree_revert.txt)

**Comment by kalefranz** [comment]
For problems with specific packages, please file issues at https://github.com/ContinuumIO/anaconda-issues.
