### ISSUE TITLE
conda info --use-local <package>

### ISSUE THREAD

**Issue by forman** [conda/conda#3123]
After I've built a package (named `dedop`) on Windows 10 with `conda build <recipe>` and tested it using `conda install --use-local dedop` I got an error saying:

```
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - dedop
Use "conda info <package>" to see the dependencies for each package.
```

I have no clue what the conflict between a single specification may be. However, `conda info dedop` doesn't help because of course I get

```
Fetching package metadata .........
Error: Package missing in current win-64 channels:
  - dedop
```

I wish I could call `conda info --use-local dedop` which would tell me more about the possible cause of the conflict.

The not-very-special recipe is here: https://github.com/DeDop/dedop-conda/tree/master/dedop. Note that the package builds & installs well on Ubuntu.

**Comment by forman** [comment]
In fact, I've used the build with a channel: `conda build -c IOOS <recipe>` because this was required for my `basemap` dependency. If I remove `basemap` and build without channel everything works fine! 

Anyway, my initial feature wish remains.

**Comment by kalefranz** [comment]
In this case, `--use-local` and `--channel local` will end up being equivalent.  We'll track this feature request via #1390
