### ISSUE TITLE
Selectively installing development versions

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3125]
A discussion we have had at conda-forge is how to install development releases. See this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/147 ). There are some great benefits of being able to do something like this. The biggest ones are speeding up the release process and increased community engagement. We have tried this in one case. In particular, we have tried this with `matplotlib`. See this [comment](https://github.com/conda-forge/matplotlib-feedstock/pull/24#issuecomment-221496870) for a brief walkthrough of how it worked.

The biggest challenge we face ATM is that enabling the development channel results in getting development releases of everything. As can be imagined, this is suboptimal. Most people would want to enable one type of dev release selectively so they can try that one package. One solution would be to name the dev channels distinctly, but having so many dev channels would quickly be a management nightmare for the end user. It would be great if we can start a larger discussion about how `conda` can facilitate this. Also it would be helpful if we think about some concrete changes in conda that would make this possible.

I have cc'd everyone part of this discussion at conda-forge in hopes that we can work with Continuum to find a healthy solution to this important problem.

cc @pelson @ocefpaf @astrofrog @Cadair @jjhelmus @rgommers @ChrisBarker-NOAA @patricksnape @janschulz @SylvainCorlay @tacaswell @msarahan @mcg1969 @kalefranz

**Comment by mcg1969** [comment]
We need the ability to pin a package to a particular channel. That way, you never need to add the full development channel to your channel list (whether by `-c` or `.condarc`). We talk about this in the namespace gist, and of course it has benefits well beyond this particular use case.

**Comment by ChrisBarker-NOAA** [comment]
I think we need to bake the concept of "dev" releases into the versioning scheme. something like:

x.x.y-dev

marks a version as a development version.

then you need to explicitly tell conda you want dev versions, either with a flag to the install command (allowing any dev version) or adding the -dev to the version for a particular package.

So conda forge would likely end up with something like:

my_package 1.2.3
my_package 1.2.4
my_package 1.2.5
my_package 1.3.0-dev

at some point, and no one would get the dev version unless they asked for it.

then, later on, when released:
my_package 1.2.3
my_package 1.2.4
my_package 1.2.5
my_package 1.3.0-dev
my_package 1.3.0

(the -dev version could be removed later on)

of course, there could be multiple dev versions -- but I kind of like the idea of there only being one -- when a new build gets put up, it replaces the old one. not at all reproducible, but as long as teh package itself has a checksum or git tag, or something to identify it, then that's OK.

Alternatively, we could add VCS label on the end:

my_package 1.3.0-dev-62ac5ccb32c0361e9

though I can't think at the moment how conda could know _which_ -dev version is the latest.

maybe use a tag, rather than a hash, so it's sort-able? that would require putting a tag in when a dev release was done, but that makes sense anyway.

-CHB

**Comment by ChrisBarker-NOAA** [comment]
> We need the ability to pin a package to a particular channel.

you can already do:

conda install -c conda-forge-dev a_package

what else do we need?

or does that mean that that channel will be used for all of a_package's dependencies, too?

-CHB

**Comment by mcg1969** [comment]
@ChrisBarker-NOAA That is not the same. The `-c` package temporarily adds the entire conda-forge-dev channel to your channel list, putting every single one of the packages in that channel into Conda's view. What we want is to get _exactly one_ package from that channel.

More specifically, I'm thinking that a `channel/package` syntax would put the channel at the _bottom_ of your priority list, with an exception for `package` itself. That way if there are dependencies that can't be pulled from elsewhere, they can be pulled from the new channel.

**Comment by jakirkham** [comment]
The problem is the versioning scheme in `conda` is a bit complex as it tries to handle several different languages' versioning schemes. I'd be a little hesitant to try to add one more thing or add some new constraint. If we were to try and detect dev versioning in packages, namespacing would actually help. In which case, it seems better to go with @mcg1969's proposal IMHO to start with and add some automation for this case afterwards.

**Comment by jakirkham** [comment]
Also to clarify something, we are currently using a label `rc` for the RC release of `matplotlib`. So when you say `channel/package` @mcg1969, are you factoring this into `channel` then?

**Comment by mcg1969** [comment]
Well, I'm not factoring anything into it yet :-) But yes I think we need to make sure that labels are properly handled in any sort of channel pinning syntax.

**Comment by jakirkham** [comment]
> But yes I think we need to make sure that labels are properly handled in any sort of channel pinning syntax.

As long as we are thinking about it. 😉

**Comment by pelson** [comment]
Just as another datapoint, pip has the ``--pre`` flag which turns on pre-release installations (https://pip.pypa.io/en/stable/reference/pip_wheel/?highlight=pre#cmdoption--pre):

```
--pre
Include pre-release and development versions. By default, pip only finds stable versions.
```

**Comment by patricksnape** [comment]
I think from the end user perspective, doing something like `conda install -c conda-forge/channels/rc matplotlib` isn't so bad. However, from a package maintainer perspective it is currently very difficult to create a recipe that relies on a particular channel. I personally feel like recipes might benefit from the ability to specify which channel to look for a dependency on.

**Comment by dopplershift** [comment]
The install using `-c conda-forge/labels/rc` isn't the problem--the problem is that following it up with `conda update --all` then will try to "upgrade" matplotlib to the regular conda-forge version.

**Comment by jakirkham** [comment]
Does the channel match spec functionality in `conda` 4.4 include labels as well? If so, think that would qualify as a solution (IMHO the solution) to this problem.

**Comment by mbargull** [comment]
Sure, `conda` doesn't actually care/know about those labels.
IIUC, a "channel" is either
1. just an URL,
2. a partial URL like `conda-forge` or `conda-forge/label/main`, `conda-forge/label/rc`, etc.,
   (which get `channel_alias`, i.e., `https://conda.anaconda.org`, prepended),
3. a "custom multichannel" like `defaults`, `local`
   (see `conda config --describe custom_multichannels`),
4. a "custom channel"
   (see `conda config --describe custom_channels`) \[TBH: no idea why this exists...\]

Thus, 2. is what you want and what you can specify with `conda >=4.4` in, e.g.,
```
conda install conda-forge/label/rc::matplotlib
```

**Comment by jakirkham** [comment]
From my perspective, MatchSpec solves this problem. Though if there are other concerns that people have with that approach, it would be great to raise them to correctly scope this issue. If there are no other concerns, would move to close this issue in let's say 1 week from today.
