### ISSUE TITLE
load saved environment variables in order

### ISSUE THREAD

**Issue by shahin** [conda/conda#3127]
Right now, scripts in `activate.d` are sourced [in whatever order `find` returns them](https://github.com/conda/conda/blob/3c73a234158280e75a44da5705fd3d00f07ac9bc/bin/activate#L95). This order is filesystem-specific and isn't guaranteed stable. This means that packages can't rely on environment variables saved by their requirements.

For example: if package Y requires package X, then environment variables saved by package X may or may not exist when package Y's `activate.d` scripts are sourced. This is surprising because package Y _can_ rely on other assets included in package X.

Reliable order is desirable when a package needs to inspect a dependency's configuration in order to configure itself.

Options might include:
1. Order `activate.d` scripts by the dependency tree. I'm no expert, but this looks difficult given `activate.d`'s current implementation.
2. Order `activate.d` scripts alphabetically (this is [how ipython solves a similar problem](https://ipython.org/ipython-doc/1/config/overview.html#startup-files)). This seems simple to implement.

Either way, this would need a fix for #2767 first.

**Comment by kalefranz** [comment]
I wasn't aware this was the case.  The expected behavior should be #2.

**Comment by kalefranz** [comment]
This is resolved with #5044 and will be included in conda 4.4.
