### ISSUE TITLE
fresh install gives `binstar_client` error

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#3141]
I just did a complete reinstall of my conda setup and am seeing this error for standard installs:
```zsh
└─❱❱❱ conda install -n py2 -y --file ~/Dropbox/standard_py3_conda_packages.txt              +4643 23:04 ❰─┘
Fetching package metadata .......
Solving package specifications: ..........
Warning: somethings is wrong with binstar_client (No module named 'binstar_client')
[...]
```
I figured out that conda actually means anaconda_client (I guess?) but I wouldn't know why it actually requires it for default channel package installs?
This was on OSX 10.10.5.

**Comment by aldanor** [comment]
Getting same error, Linux, conda 4.1.9.

**Comment by HugoTian** [comment]
I believe binstar_client can be installed by "conda install anaconda-client", and we are working on those binstar_client stuff on conda. It is legacy code, and we are trying to understand it and make it stable. Maybe in new lease, conda4.2, we will fix this binstar_client issue.

**Comment by HugoTian** [comment]
Moreover, this binstar issue will be refactored in conda 4.2, a much stable version

**Comment by HugoTian** [comment]
I will close this issue, and I think in conda 4.1.11, there will only be debug info, instead of warning when you do not have binstar_client.

Feel free to reopen it, and thanks for your info.
