### ISSUE TITLE
Removal of args_func in conda breaks conda-env

### ISSUE THREAD

**Issue by groutr** [conda/conda#3146]
See https://github.com/conda/conda-env/issues/265
cc: @kalefranz

**Comment by HugoTian** [comment]
I think in conda 4.1.x , there is still args_func. However in master branch, which is conda4.2, there is no args_func

**Comment by HugoTian** [comment]
I am about to close this PR, and please refer to #3148.

If you find more problem with import issue, please mention that in above PR.

Feel free to reopen this PR , thanks
