### ISSUE TITLE
conda info gives:   AttributeError: 'NoneType' object has no attribute 'domain'

### ISSUE THREAD

**Issue by capybaralet** [conda/conda#3147]
Davids-MacBook-Air-3:CS188.1x-Project3 david$ conda info
Warning: could not import binstar_client ('args' object has no attribute 'site')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/david/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/config.py", line 246, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by HugoTian** [comment]
please update conda, run

    conda update conda

The new version 4.1.10 will solve this problem

Thanks

**Comment by capybaralet** [comment]
I already have version 4.10:

Davids-MacBook-Air-3:CS188.1x-Project3 david$ conda update conda

Fetching package metadata .......

# All requested packages already installed.

# packages in environment at /Users/david/anaconda:

#

conda                     4.1.10                   py27_0

**Comment by HugoTian** [comment]
@capybaralet , thanks for your information.

Actually conda 4.1.9 fix this issue, and when we releasing 4.1.10, we forget to update the issue.

Sorry about this, please run

    conda install conda=4.1.9 

This version fix this issue, however it may  run into bugs when you clone environments. We are fixing this issue now, and a new conda 4.1.10 will release later

Thanks

**Comment by capybaralet** [comment]
that fixed it, thanks!
