### ISSUE TITLE
conda locking rudimentary and fragile

### ISSUE THREAD

**Issue by pitrou** [conda/conda#3161]
The conda lock is currently implemented using a two-step `glob()` / `open()` sequence. This has several issues:
* there is an inherent race condition: two processes could satisfy the `glob()` condition and take the lock at the same time
* the lock isn't cleaned up when a process terminates abruptly (which can happen when e.g. a CI job gets killed)

There are various ways to do robust file-based locking. Cross-platform Python libraries exist for this, e.g. [locket](https://pypi.python.org/pypi/locket/) or [py-filelock](https://filelock.readthedocs.io/en/latest/).

**Comment by HugoTian** [comment]
@pitrou I completely agree with you.

For the first one, I think, it may seldom happen in real world application, and we will certainly consider using the library you provided.

For the second one, I think it is high priority for conda 4.2, and we can simply add a final block to clean all the lock in exception handler. I will try to give a PR for this one.

I will go deep into the library you provided and discuss with other conda member, and thanks for your advice

**Comment by pitrou** [comment]
> For the second one, I think it is high priority for conda 4.2, and we can simply add a final block to clean all the lock in exception handler.

This won't work if the process is killed from the outside.

**Comment by kalefranz** [comment]
It will if we catch SIGINT here as we should be. You're on your own to run conda clean if you SIGKILL.

**Comment by kalefranz** [comment]
merged for 4.2

**Comment by pitrou** [comment]
Is it ok to have closed this issue? The PR doesn't even seem to add a signal handler (let alone address the hypothetical race condition).

**Comment by HugoTian** [comment]
We will revert that PR soon, and need discussion for the lock.

Now I prefer use the py-filelock that @pitrou  mentioned above, and modify that a little bit to raise CondaLockError.

Or we can carefully handle lock clean when there is exception or outside signal

**Comment by msarahan** [comment]
Thanks for the suggestion of libraries, @pitrou.  Be careful, @HugoTian - filelock seems to only support Python 3, but we need to support Python 2 for some time to come.

**Comment by pitrou** [comment]
I took a quick look at their source code, and both libraries are wrappers around `fcntl.flock` on Linux, and `msvcrt.locking` on Windows. Both seem easily vendorable (single-file module). There is some additional internal complexity to make their APIs thread-safe in addition to process-safe (that complexity may not be required by Conda).

**Comment by HugoTian** [comment]
@msarahan , Thanks for your information, and  I will pay special attention to python2 stuff.

 However, @pitrou , sometimes, conda need to lock a directory, see [here](https://github.com/conda/conda/blob/master/conda/install.py#L1051) and filelock will run into OSError when it tries to open a directory.

**Comment by pitrou** [comment]
The directory itself isn't locked. You are just putting a marker there (a file) indicating that the directory is locked, so both file lock libraries should be apt.

**Comment by HugoTian** [comment]
I see and I will create a PR based on py-filelock.

Thanks

**Comment by HugoTian** [comment]
I already create a PR #3197  for this new lock based on  [py-filelock](https://filelock.readthedocs.io/en/latest/).

Let's move discussion to that PR
