### ISSUE TITLE
Activate script should disable user site-packages directory

### ISSUE THREAD

**Issue by pitrou** [conda/conda#3162]
The current `activate` scripts are error-prone in that they allow Python to see non-environment-installed packages. They should really set `PYTHONNOUSERSITE`.

**Comment by Zaharid** [comment]
See also https://github.com/conda/conda/issues/2590

**Comment by pitrou** [comment]
@kalefranz, @msarahan, can we get this soon? I got bitten once again just today...

**Comment by kalefranz** [comment]
Actually, if we were going to be setting `PYTHONNOUSERSITE`, it should probably be done within `activate.d`/`deactivate.d` scripts for the python package.  That would be the correct place to do it.

**Comment by kalefranz** [comment]
Similar to comment https://github.com/conda/conda/issues/1497#issuecomment-300432084 and comments in #2590, we shouldn't be managing language-specific environment variables with hard-coding in conda.

I'm going to close this issue, given the solution. Feel free to open a new issue at https://github.com/ContinuumIO/anaconda-issues for adjustment to the python package if you feel strongly about it.
