### ISSUE TITLE
Jupyter's R-kernel standard error output has line breaks after every character

### ISSUE THREAD

**Issue by jolespin** [conda/conda#3172]
Sometimes an error window pops up but most of the time it just pops up in the stdout as each character separated by linebreaks
![screen shot 2016-07-27 at 9 32 12 am](https://cloud.githubusercontent.com/assets/9061708/17183591/0f4215e4-53dd-11e6-950f-2e54a8d87220.png)

Here's my conda info

```
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 0+unknown
       python version : 3.5.2.final.0
     requests version : 2.9.1
     root environment : /Users/jespinoz/anaconda  (writable)
  default environment : /Users/jespinoz/anaconda
     envs directories : /Users/jespinoz/anaconda/envs
        package cache : /Users/jespinoz/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/osx-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/jespinoz/.condarc
         offline mode : False
    is foreign system : False
```

Here's my R info:

```
$ which R
/Users/jespinoz/anaconda/bin/R
```

w/ that R ^^^

```
> version
               _                           
platform       x86_64-apple-darwin11.0.0   
arch           x86_64                      
os             darwin11.0.0                
system         x86_64, darwin11.0.0        
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair            
> 
```

**Comment by HugoTian** [comment]
could you please give me the code in your notebook that leads to this error ?

I will try to reproduce it and forward to notebook group to fix it.

Thanks

**Comment by jolespin** [comment]
Yea, try just a simple error like: `print "a"`

![screen shot 2016-07-27 at 3 34 23 pm](https://cloud.githubusercontent.com/assets/9061708/17194921/a4ef36b2-540f-11e6-9652-c1dcda1da576.png)

**Comment by mingwandroid** [comment]
@csoja can you assign this to the best person to look into it? If it's something I've done wrong then I'd be glad to be advised where to begin investigating.

**Comment by csoja** [comment]
@mingwandroid I'm not sure who is the best person.  Are you able to reproduce the error?

**Comment by mingwandroid** [comment]
Yeah, I've seen it, it's annoying rather than very serious which is why I've not spent time investigating it.

**Comment by jolespin** [comment]
Unfortunately, I'm not going to be able to help w/ the troubleshooting b/c my R Kernel is broken in Jupyter :( https://github.com/conda/conda/issues/3316#issuecomment-241246755 . Luckily, I've found a way to use my version of `R` installed through `conda` to work on `RStudio` (details in my answer here http://stackoverflow.com/questions/38534383/how-to-set-up-conda-installed-r-for-use-with-rstudio)

**Comment by mingwandroid** [comment]
This is fixed now. I'm not entirely sure who or what fixed it though.
