### ISSUE TITLE
csh version of activate

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3176]
Old habits die hard, and for others, they just don't have a choice in the matter: tcsh is their shell and there is no changing it.  It would be nice to have a CSH version of the BASH `activate` script, even if it didn't have all the features.  This may be a variation on some of the ideas here: https://github.com/conda/conda/issues/747.  This was requested by a client.

**Comment by njalerikson** [comment]
see #3175

**Comment by kalefranz** [comment]
#3175 will be in 4.3 :) @njalerikson has done an awesome job unifying activate/deactivate support for all the Bourne shell derivatives and C shell derivatives.

**Comment by StevenCHowell** [comment]
I'm still having an issue, even though I am on anaconda version 4.3.1 (full version: 4.3.1-np111py36-0).  I posted a comment in the pr #3175 thread.  Am I missing something?

**Comment by ijstokes** [comment]
@mingwandroid has just informed me that PR #3175 had to be backed out after merging because it introduced a bunch of problems.  So this remains an open issue (which may or may not ever be addressed!)

**Comment by njalerikson** [comment]
@ijstokes this is correct

I have been briefed by @kalefranz and a new idea for csh is in the works that follows #5044 #5141 

This new solution is cleaner and technically solves many more problems than #3175 was able to solve

**Comment by kalefranz** [comment]
Done in conda 4.4.
