### ISSUE TITLE
error when conda --debug

### ISSUE THREAD

**Issue by sbacelar** [conda/conda#3180]
When I do `conda --debug`

 I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda3\Scripts\conda-
script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda3\lib\site-packa
ges\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda3\lib\site-packa
ges\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
AttributeError: 'Namespace' object has no attribute 'func'
```

This is the output of command `conda info`

        ```
     platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda
3  (writable)
  default environment : C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda
3
     envs directories : C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda
3\envs
        package cache : C:\Users\sergio.bacelar\AppData\Local\Continuum\Anaconda
3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by HugoTian** [comment]
Generally conda 4.1.x is not good at catching exceptions. In main function, there is a line

     args = p.parse_args()

If the command is "conda --debug", this line will raise a warning and a SystemExit baseException, and below is the warning message

usage: conda [-h] [-V] [--debug] command ...
conda: error: the following arguments are required: command

I think in conda4.2 , we will better handle exception and baseException.

Thanks

**Comment by HugoTian** [comment]
In conda repo, the master branch is 4.2 and it does not catch baseException. However, the "main" function is wrapped by a try block.

As a result, in conda 4.2 , if you try "conda --debug" , it will say

usage: conda [-h] [-V] [--debug] command ...
conda: error: the following arguments are required: command

Moreover. I change the code, and let conda catch baseException, and I got following error message


usage: conda [-h] [-V] [--debug] command ...
conda: error: the following arguments are required: command
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues


Current conda install:

               platform : osx-64
          conda version : 4.1.11.dev894+bdbe3dc
       conda is private : False
      conda-env version : 2.5.1
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /Users/tester/anaconda3  (writable)
    default environment : /Users/tester/anaconda3
       envs directories : /Users/tester/anaconda3/envs
          package cache : /Users/tester/anaconda3/pkgs
           channel URLs : defaults
            config file : None
           offline mode : False


`$ /Users/tester/anaconda3/bin/conda --debug`


    Traceback (most recent call last):
      File "/Users/tester/Desktop/conda/conda/exceptions.py", line 402, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/tester/Desktop/conda/conda/cli/main.py", line 122, in _main
        args = p.parse_args()
      File "/Users/tester/Desktop/conda/conda/cli/conda_argparse.py", line 172, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "/Users/tester/anaconda3/lib/python3.5/argparse.py", line 1726, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/Users/tester/anaconda3/lib/python3.5/argparse.py", line 1758, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/Users/tester/anaconda3/lib/python3.5/argparse.py", line 1993, in _parse_known_args
        ', '.join(required_actions))
      File "/Users/tester/Desktop/conda/conda/cli/conda_argparse.py", line 157, in error
        super(ArgumentParser, self).error(message)
      File "/Users/tester/anaconda3/lib/python3.5/argparse.py", line 2385, in error
        self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
      File "/Users/tester/anaconda3/lib/python3.5/argparse.py", line 2372, in exit
        _sys.exit(status)
    SystemExit: 2

Hope it help

**Comment by HugoTian** [comment]
I think I will close this issue, and I you have questions, please reopen it and @ me
