### ISSUE TITLE
conda install shouldn't silently skip failed linking

### ISSUE THREAD

**Issue by aldanor** [conda/conda#3182]
When linking fails, conda install doesn't produce an error and finishes silently:

```sh
$ conda --debug install -f somepackage.tar.bz2

...

DEBUG:conda.install:pkgs_dir='.../anaconda3/pkgs', prefix='.../envs/py35', dist='file://.../dist::somepackage-0.3.0-py35_0', linktype=1
ERROR:conda.install:failed to link (src='.../anaconda3/pkgs/somepackage-0.3.0-py35_0/lib/python3.5/site-packages/somepackage/__init__.py', dst='.../envs/py35/lib/python3.5/site-packages/somepackage/__init__.py', type=1, error=OSError(18, 'Invalid cross-device link'))

...

[      COMPLETE      ]|#####################################| 100%
INFO:progress.stop:None

```

**Comment by aldanor** [comment]
It's interesting that it even attempts a cross-device link, why wouldn't it just copy? (I have `allow_softlinks: false` in `~/.condarc`)

**Comment by HugoTian** [comment]
Agree ! 

And in conda4.2 , we will fix this, and below is the code


            try:
                _link(src, dst, lt)
            except OSError as e:
                raise CondaOSError('failed to link (src=%r, dst=%r, type=%r, error=%r)' %
                                   (src, dst, lt, e))

And the whole "main" function is wrapped by a exception handler, which will give proper error message

Thanks

**Comment by HugoTian** [comment]
I will close this issue, and if you have questions , feel free to reopen it and @ me

**Comment by aldanor** [comment]
@HugoTian So what is the preferred way to force copy link mode if using `conda.misc.install_local_packages`? (I believe in 4.2 it's now `conda.explicit`)

**Comment by aldanor** [comment]
From [`conda.instructions`](https://github.com/conda/conda/blob/master/conda/instructions.py#L70):

```python
def split_linkarg(arg):
    "Return tuple(dist, linktype)"
    parts = arg.split()
    return (parts[0], int(LINK_HARD if len(parts) < 2 else parts[1]))
```

The `arg` will be just a `file://...`, so this will be forced to `LINK_HARD` completely ignoring any config/context settings?

**Comment by HugoTian** [comment]
I see, but in link function , code here https://github.com/conda/conda/blob/master/conda/install.py#L999,

It will change to soft-link in some cases.

However, I think we should have better way to handle config/context setting for soft-link

I will look deep into the code to see this

Thanks

**Comment by HugoTian** [comment]
also  I just found

    --copy                Install all packages using copies instead of hard- or soft-linking.

Please check this and see whether it's what you want ?

**Comment by HugoTian** [comment]
Also please check https://github.com/conda/conda/blob/master/conda/plan.py#L357

It will check the context.always_copy, and --copy setting on command line, and this is happened before split_linkarg you just mentioned

**Comment by aldanor** [comment]
No, it is ignored for local installs (which is the point of this issue), even if you call it from the CLI:

```sh
$ conda --debug install --force --copy somepackage-py35_0.tar.bz2 
...
DEBUG:conda.install:pkgs_dir='.../anaconda3/pkgs', prefix='.../env', 
    dist='file://.../dist::somepackage-py35_0', linktype=1
...
```

Link type is wrong here.

Both the CLI and the `misc.explicit` should *not* have LINK_HARD hard-coded for explicit local installs.

**Comment by HugoTian** [comment]
Sorry, I did not see that it is installed from tar.bz2, and I agree with you , and there should be a check in this explicit function. 

I will creata a PR for this one, and thanks for your information

**Comment by HugoTian** [comment]
@aldanor  please help to review this PR, and thanks a lot for pointing out this bug
