### ISSUE TITLE
could not start R kernel

### ISSUE THREAD

**Issue by DanqingZ** [conda/conda#3188]
I have followed this [official blog](https://www.continuum.io/blog/developer/jupyter-and-conda-r) from conda..but could not start the R kernel, below are the errors

[W 01:37:32.034 NotebookApp] Timeout waiting for kernel_info reply from 1759c888-1086-4c60-8a77-f63d48acd976
[I 01:37:34.036 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 1759c888-1086-4c60-8a77-f63d48acd976 restarted
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/danqing0703/anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Users/danqing0703/anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.dylib
  Referenced from: /Users/danqing0703/anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted

**Comment by mingwandroid** [comment]
Please show the output of `conda info` and `conda list --export`

**Comment by DanqingZ** [comment]
I solved this by "conda install -c r r-irkernel zeromq"[from a comment of this stackoverflow question](http://stackoverflow.com/questions/38387027/unable-to-load-irkernel-in-jupyter-notebook)
