### ISSUE TITLE
Improve handling of local packages

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#3190]
Currently locally built packages take precedence over remote ones for things like conda build. This is usually what you want, but it can happen that a locally built package is broken somehow (it was probably built for testing!). 

I see no way of cleaning these packages short of manually removing the files in the conda directory, both in the pkgs directory and in conda-bld.

Perhaps something like `conda clean --local` would help.

**Comment by kalefranz** [comment]
@msarahan Do you have any recommendations here?  Do you already have a way of cleaning up the conda-bld directory?  I don't at all mind implementing something under the `conda clean` command.  Don't want to duplicate something you already have though.

**Comment by nehaljwani** [comment]
I think maybe `conda build purge-all` is relevant here? https://github.com/conda/conda-build/issues/1965

**Comment by kalefranz** [comment]
Oh I see how it's implemented. Yup that'll do it.
