### ISSUE TITLE
jupyter failed to load the kernel

### ISSUE THREAD

**Issue by liyun831229** [conda/conda#3194]
When I started a jupter notebook from anaconda. It works very well. I can change between kernels. However, if I started jupter notebook from Windows cmd. It only load the root kernel, there is no option to change between root kernel and other kernels.
Another two problems of mine is:
1. activate env_name do not actually works in windows cmd. It just stick on the root environment.

**Comment by bollwyvl** [comment]
Sounds like you might need to ensure that `conda` is on the `PATH` environment variable when you start your command prompt. Depending on how you installed Anaconda, you had the option to do just that:

![anacondainstallwindows](https://cloud.githubusercontent.com/assets/45380/17301117/6db414b0-57e3-11e6-8378-71d21a1bdd5e.png)

As it says, if you didn't check that box, you'll have to use the `Anaconda Command Prompt` to get the right `PATH` when you start up. The other way is to actually _find_ the `activate.bat` for your environment and run that, but that all depends on where you installed it!

Related to this, we've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! 

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

No promises for your issue, but it might help!

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166
