### ISSUE TITLE
Automatically switch environments on .python-version

### ISSUE THREAD

**Issue by mcandre** [conda/conda#3195]
Could conda support automatically switching environments on per-project .python-files, like pyenv? That would significantly speed up my development workflow.

**Comment by shahin** [comment]
Looks like [autoenv provides exactly this functionality](https://github.com/kennethreitz/autoenv). @mcandre , does that work in your use case?

**Comment by mcandre** [comment]
Thanks, but I'm looking for a version manager with Windows support as well. I could just use pyenv if I all my hosts were Unix.

**Comment by kalefranz** [comment]
The windows cmd.exe shell is incapable of supporting this feature.  I'm guessing powershell can though.
