### ISSUE TITLE
conda create --clone creates broken env when crossing filesystems

### ISSUE THREAD

**Issue by jgullingsrud** [conda/conda#3198]
The conda create subcommand attempts to create hard links from source (non-symlink) files in the cloned env to the destination env.  However, when source and destination directories are on different filesystems, most commonly in an NFS environment, creation of those hard links fails.  The resulting environment has many broken links to shared libraries, as the actual shared library contents never get copied.

Creation of the hard links is attempted in conda.install._link when link type is LINK_HARD.  The underlying call to os.link throws an exception, but the exception is caught by the install.link() function and logged somewhere.  No error message gets written to the console.

The use of the --copy option in conda create does not change the behavior: hard links are still attempted, but silently fail.

I suggest either (1) detecting cross-filesysystem clones and copy files in that case instead of trying to hard link them; or (2) make --copy change the behavior of conda.install._link to use LINK_COPY.

In addition, the catching of the OSError exception in conda.install.link seems misguided.  Failure to create a link means the created env is in all likelihood broken.  The install should just quit and report the error on the console, and ensure that the script exits nonzero.

**Comment by jgullingsrud** [comment]
Note: Issue#3033 appears to be caused by this same problem.

**Comment by kalefranz** [comment]
FYI @HugoTian

**Comment by HugoTian** [comment]
Someone already mentioned a similar problem #3182 , and I already get a PR to fix this, #3184.

**Comment by HugoTian** [comment]
Generally, when we clone env or install from tar , we call explicit function in conda/misc.py instead of ensure_linked_actions in conda/plan.py. Link action are carefully handled in plan module, but not in misc module.

Moreover, in conda4.2, we will get a better exception handler, and it will raise error with proper message when there is link failure

**Comment by HugoTian** [comment]
PR #3184 now pass all the test cases, and I think it will fix the issue in explicit function in conda/misc.py

I will close this issue and let's discuss under that PR

Feel free to reopen it and @ me
