### ISSUE TITLE
conda build -- build dependencies

### ISSUE THREAD

**Issue by bkreider** [conda/conda#320]
It tough to build packages that have build dependencies provided via Binstar without editing the .bashrc.  

I don't know the best way of solving this:
- Deps could be fully specified to point to a binstar channel - +1
- Defining binstar channels on the command-line when building - with access tokens
- Allowing one to pre-install packages into an environment with all of the dependencies.

**Comment by asmeurer** [comment]
The -c flag was added https://github.com/conda/conda-build/pull/334

**Comment by goanpeca** [comment]
@bkreider can we close this?

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1996
