### ISSUE TITLE
activate breaks on unbound vars in some bash shells

### ISSUE THREAD

**Issue by shahin** [conda/conda#3200]
The deactivate script [attempts to access $CONDA_PATH_BACKUP](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/deactivate#L55) even when it isn't bound (for example, [when `activate` sources `deactivate`](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/activate#L59)). This makes `deactivate` exit with an error message when sourced from a bash shell with [the `nounset` option](http://tldp.org/LDP/abs/html/options.html) set. Eventually `activate` breaks when the `errexit` option is also set:

```
$ /bin/bash -c 'source activate testenv; echo $CONDA_DEFAULT_ENV'
testenv
$ /bin/bash -eu -c 'source activate testenv; echo $CONDA_DEFAULT_ENV'
/home/jenkins-ci/miniconda3/bin/deactivate: line 55: CONDA_PATH_BACKUP: unbound variable
$ 
```

When sourced in a non-interactive session, `activate` does the same thing all by itself (even with `changeps1: False`):

```
$ /bin/bash -eu -c 'CONDA_PATH_BACKUP=""; source activate testenv; echo $CONDA_DEFAULT_ENV'
/home/jenkins-ci/miniconda3/bin/activate: line 65: PS1: unbound variable
$
```

It's not crazy to activate a conda env in such a shell. `nounset` and `errexit` are helpful and fairly common when debugging, and they help avoid silent failures in production. 

Some options are:
1. Ask users to activate conda environments in shells without `nounset` and `errexit` options set,
2. Bind these variables at the beginning of each script if they're unbound, or
3. Fix these two tests to [check for unbound variables](http://stackoverflow.com/a/13864829).

Option (3) seems least disruptive to me. If there are no objections, I'll open a PR soon.

**Comment by kalefranz** [comment]
Awesome report.  Thanks!

Option 3 sounds completely reasonable, and I'd definitely welcome a PR.  When you create your working branch, please branch off of the `4.1.x` branch, and set `4.1.x` as the target of the PR.

**Comment by cread** [comment]
I'm getting this problem in `4.2.7`

**Comment by gmnash** [comment]
I do as well.

**Comment by rspreafico** [comment]
Same here with `4.3.13`

**Comment by jzwinck** [comment]
@shahin Are you still planning to file a PR for this or should someone else do it?

**Comment by shahin** [comment]
@jzwinck I'm not planning to file a PR for this.

**Comment by cjfields** [comment]
I see this when attempting to activate an environment in a batch script using SLURM via the nextflow workflow system.  The fixes @shahin linked to worked for `deactivate` (for `$CONDA_PATH_BACKUP`, [L55](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/deactivate#L55)) and `activate` (for `$PS1` in three locations, [L65](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/activate#L65), [L87](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/activate#L87), [L88](https://github.com/conda/conda/blob/402ace6f77775f2d7965128a0f7f42243142f32c/shell/activate#L88)).

**Comment by sebastian-luna-valero** [comment]
Getting the same problem here with `GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
`

Can be reproduced with:
```
#!/usr/bin/env bash

# References
# http://kvz.io/blog/2013/11/21/bash-best-practices/
# http://jvns.ca/blog/2017/03/26/bash-quirks/

# exit when a command fails
set -o errexit

# exit if any pipe commands fail
set -o pipefail

# exit when your script tries to use undeclared variables
set -o nounset

# trace what gets executed
set -o xtrace

wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh -b -p $PWD/conda

$PWD/conda/bin/conda create -n env -c bioconda pysam --yes

source $PWD/conda/bin/activate env
```

Error:
```
line 55: CONDA_PATH_BACKUP: unbound variable
```
