### ISSUE TITLE
conda does not read central install .condarc if local one is present

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3213]
I have been getting help with a issue on conda-build, but I think it is a conda issue, but what I figured out was the above title, details are here:

https://github.com/conda/conda-build/issues/1120

**Comment by kalefranz** [comment]
Using conda 4.2 should fix your problem out of the box.  Here's the 4.2 changlog: https://github.com/conda/conda/releases/tag/4.2.0

With the 4.2 feature release we're starting a new "conda canary" program.  Feature releases will be held in canary for one month, and then the latest patch release will be transitioned to defaults.  So the general availability of the conda 4.2 feature release will be Aug 28.

However, please *do* participate in the canary program (I'm writing a full blog post about it today).

    conda config --add channels conda-canary
    conda update conda
