### ISSUE TITLE
Conda failing to remove and env

### ISSUE THREAD

**Issue by sarath-ps** [conda/conda#3215]
$ conda env remove --name py27
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/sar/anaconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/sar/anaconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/sar/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/sar/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: module 'conda.plan' has no attribute 'PREFIX'

----
12:18 $ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/sar/anaconda3  (writable)
  default environment : /Users/sar/anaconda3
     envs directories : /Users/sar/anaconda3/envs
        package cache : /Users/sar/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by HugoTian** [comment]
I will look into this issue, and please try conda remove --name py27, instead of conda env remove, and see whether it will remove a env successfully

Thanks

**Comment by kalefranz** [comment]
Try

    conda remove --all --name ENVIRONMENT_NAME

**Comment by HugoTian** [comment]
I double checked " conda remove --all --name ENVIRONMENT_NAME" command, and it works fine.

Generally, try to use "conda" command more instead of "conda env".

I will close this issue, and if you have questions, feel free to reopen this and @ me

**Comment by sarath-ps** [comment]
On Wed, Aug 3, 2016 at 9:09 PM, Tian Zhang <notifications@github.com> wrote:

> conda remove --name py27 --all


It did work :)

thanks, please consider adding this to help. Sorry if I missed this out in
the manual :(

thanks you very much



-- 
-Sarath
