### ISSUE TITLE
blosc package seems to be empty

### ISSUE THREAD

**Issue by FrancescAlted** [conda/conda#3216]
Apparently the latest versions for the `blosc` package are broken:

```
francesc@francesc:~$ conda install blosc
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/francesc/miniconda3:

The following NEW packages will be INSTALLED:

    blosc: 1.2.3-0

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|##########################################################################| 100%
francesc@francesc:~$ python -c "import blosc; blosc.compress(b'a'*10)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'blosc'
```

This in on a Ubuntu Linux 16.04 platform and conda 4.1.11.

**Comment by kalefranz** [comment]
What is the output of `which -a conda` and `which -a python`?

**Comment by ilanschnell** [comment]
Hi Francesc, the package `blosc-1.2.3-0` (on Linux) includes the C library only.  The content of the package is:
```
include/blosc.h
include/blosclz.h
include/shuffle.h
lib/blosc.so
```

**Comment by FrancescAlted** [comment]
Hi Ian.  That's good to know.  I have been trying to know the way to browse the contents of a package (the equivalent of `dpkg -L` in Debian) in conda, but never managed to find the way to do that.  So, apparently there is not a `python-blosc` package in conda.

**Comment by FrancescAlted** [comment]
Just a suggestion: it would be good to change the name of the `blosc` package in conda to `c-blosc` in order to differentiate from an eventual `python-blosc` in the future.

**Comment by kalefranz** [comment]
We're working on a different way of resolving these ecosystem namespace problems.
Here's a rough spec: https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1

**Comment by FrancescAlted** [comment]
Ok, sounds good.  At any rate, I'd like to let you know that the C Blosc library became officially [C-Blosc](https://github.com/Blosc/c-blosc) quite long time ago.  But I am +1 on language namespaces too.

**Comment by kalefranz** [comment]
Oh, if that's an official name change, then I agree we should transition the name to c-blosc. Something for @ilanschnell to be aware of.

**Comment by ilanschnell** [comment]
Yes, we should always keep the original package name.

**Comment by kalefranz** [comment]
But if the name has officially changed, I'd think it would be reasonable to transition the package to the new name, using a metapackage for the old name to smooth the transition.
