### ISSUE TITLE
issues after updating to conda conda 4.1.11

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [conda/conda#3229]
I just updated to conda 4.1.11 and tried to update my ananconda as well but I get the following error.

$conda update anaconda
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda
  - enaml -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.

conda info gives me the following output
Warning: could not import binstar_client ('args' object has no attribute 'site')Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.1
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.9.1
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/osx-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ben/.condarc
         offline mode : False
    is foreign system : False
 
And reversing conda doesn't work out either
conda install --revision 17
Fetching package metadata .........
.
Package plan for installation in environment //anaconda:

The following packages will be downloaded:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "//anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 394, in install
    display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "//anaconda/lib/python3.5/site-packages/conda/plan.py", line 73, in display_actions
    info = index[dist + '.tar.bz2']
KeyError: 'r-htmlwidgets-0.5-r3.2.1_0.tar.bz2'

Any suggestions?

**Comment by HugoTian** [comment]
Based on my understand, you have 2 problem.

1. conda update anaconda gets conflict, and I am not quite sure with this. Maybe enaml depends on python2.7 and your environment is python3.5. Please try "conda remove enaml", and then conda update anaconda.


2. conda cannot revert back to old state, and this error is caused by the update of index. Index comes from the online repo-data and your local info. Seems you already delete or uninstall r-htmowidggets, so the index has no info of that package, then you cannot revert back. Moreover, we already has better error message for this kind of error in conda 4.2, please refer to PR #3181

**Comment by BenjaminSchwessinger** [comment]
Thanks I went the brude force way and did a fresh reinstall. Looking good now.
