### ISSUE TITLE
Sphinx installation fails

### ISSUE THREAD

**Issue by Tryph** [conda/conda#3231]
`conda install sphinx` fails:

```
Traceback (most recent call last):
  File "C:\dev\sw\miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\install.py", line 1076, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\install.py", line 436, in update_prefix
    os.chmod(path, stat.S_IMODE(st.st_mode))
WindowsError: [Error 2] Le fichier spÚcifiÚ est introuvable: 'C:\\dev\\sw\\miniconda2\\Scripts\\rst2latex.py'
```
```
>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.19.0
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : C:\dev\sw\miniconda2  (writable)
  default environment : C:\dev\sw\miniconda2
     envs directories : C:\dev\sw\miniconda2\envs
        package cache : C:\dev\sw\miniconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by HugoTian** [comment]
I cannot understand the error message on last line, but I guess that means file not found for variable path. below is the source code for that part

     with exp_backoff_fn(open, path, 'wb') as fo:
        fo.write(data)
    os.chmod(path, stat.S_IMODE(st.st_mode)) 

Generally, exp_backoff_fn will open(path, 'wb') and seems it fails to create that file.

Could you please show the output of conda --debug install sphinx

**Comment by Tryph** [comment]
You are right the last line means "file ot found".

Actually, after this error, i tried to install a previous version of sphinx (1.3.5 instead of current 1.4.1) and it worked fine.
So I juste removed sphinx in order to be able to execute  "conda --debug install sphinx", and this time the install worked...

anyway, below is the output of the conda --debug install sphinx but i do not think it will help you a lot:
`>conda --debug install sphinx
DEBUG:conda.fetch:channel_urls=OrderedDict([('https://repo.continuum.io/pkgs/free/win-64/', ('defaults', 1)), ('http
s://repo.continuum.io/pkgs/free/noarch/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/pro/win-64/', ('default
s', 1)), ('https://repo.continuum.io/pkgs/pro/noarch/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/msys2/win
-64/', ('defaults', 1)), ('https://repo.continuum.io/pkgs/msys2/noarch/', ('defaults', 1))])
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, red
irect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/win-64/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/win-64/',) kwargs {'session': <conda.
connection.CondaSession object at 0x0000000003244358>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'session': <conda.
connection.CondaSession object at 0x0000000003244358>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/win-64/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/win-64/',) kwargs {'session': <conda.c
onnection.CondaSession object at 0x0000000003244358>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'session': <conda.c
onnection.CondaSession object at 0x0000000003244358>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/msys2/win-64/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/msys2/win-64/',) kwargs {'session': <conda
.connection.CondaSession object at 0x0000000003244358>, 'use_cache': False}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/msys2/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/msys2/noarch/',) kwargs {'session': <conda
.connection.CondaSession object at 0x0000000003244358>, 'use_cache': False}

INFO:stdoutlog:

DEBUG:conda.plan:H0 specs=['sphinx']
DEBUG:conda.plan:H2 python True
DEBUG:conda.plan:H3 python
DEBUG:conda.plan:H2 lua False
DEBUG:conda.plan:H2A lua
DEBUG:conda.plan:HF specs=['sphinx', u'python 2.7* (target=python-2.7.12-0.tar.bz2)']
DEBUG:conda.plan:Pinned specs=[]
DEBUG:conda.resolve:Checking satisfiability of current install
DEBUG:conda.resolve:Checking if the current environment is consistent
Solving package specifications: INFO:stdoutlog:Solving package specifications:
.DEBUG:dotupdate:Solving for [MatchSpec('sphinx'), MatchSpec('python 2.7* (target=python-2.7.12-0.tar.bz2)'), MatchS
pec('conda >=4.1.11'), MatchSpec('conda-env'), MatchSpec('six (target=six-1.10.0-py27_0.tar.bz2)'), MatchSpec('pygme
nts (target=pygments-2.1.3-py27_0.tar.bz2)'), MatchSpec('enum34 (target=enum34-1.1.6-py27_0.tar.bz2)'), MatchSpec('w
heel (target=wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('pip (target=pip-8.1.2-py27_0.tar.bz2)'), MatchSpec('pep8 (ta
rget=pep8-1.7.0-py27_0.tar.bz2)'), MatchSpec('anaconda-client (target=anaconda-client-1.2.2-py27_0.tar.bz2)'), Match
Spec('sphinx_rtd_theme (target=sphinx_rtd_theme-0.1.9-py27_0.tar.bz2)'), MatchSpec('lazy-object-proxy (target=lazy-o
bject-proxy-1.2.1-py27_0.tar.bz2)'), MatchSpec('py (target=py-1.4.31-py27_0.tar.bz2)'), MatchSpec('pycosat (target=p
ycosat-0.6.1-py27_1.tar.bz2)'), MatchSpec('colorama (target=colorama-0.3.7-py27_0.tar.bz2)'), MatchSpec('snowballste
mmer (target=snowballstemmer-1.2.1-py27_0.tar.bz2)'), MatchSpec('msvc_runtime (target=msvc_runtime-1.0.1-vc9_0.tar.b
z2)'), MatchSpec('astroid (target=astroid-1.4.4-py27_0.tar.bz2)'), MatchSpec('pytz (target=pytz-2015.7-py27_0.tar.bz
2)'), MatchSpec('menuinst (target=menuinst-1.4.1-py27_0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py27_4.tar
.bz2)'), MatchSpec('coverage (target=coverage-4.1-py27_0.tar.bz2)'), MatchSpec('psutil (target=psutil-3.4.2-py27_0.t
ar.bz2)'), MatchSpec('docutils (target=docutils-0.12-py27_2.tar.bz2)'), MatchSpec('vs2008_runtime (target=vs2008_run
time-9.00.30729.1-2.tar.bz2)'), MatchSpec('wrapt (target=wrapt-1.10.6-py27_0.tar.bz2)'), MatchSpec('ruamel_yaml (tar
get=ruamel_yaml-0.11.7-py27_0.tar.bz2)'), MatchSpec('babel (target=babel-2.3.3-py27_0.tar.bz2)'), MatchSpec('patch (
target=patch-2.5.9-1.tar.bz2)'), MatchSpec('logilab-common (target=logilab-common-1.0.2-py27_0.tar.bz2)'), MatchSpec
('requests (target=requests-2.10.0-py27_0.tar.bz2)'), MatchSpec('conda-build (target=conda-build-1.19.0-py27_0.tar.b
z2)'), MatchSpec('alabaster (target=alabaster-0.7.8-py27_0.tar.bz2)'), MatchSpec('python-dateutil (target=python-dat
eutil-2.4.2-py27_0.tar.bz2)'), MatchSpec('setuptools (target=setuptools-23.0.0-py27_0.tar.bz2)'), MatchSpec('singled
ispatch (target=singledispatch-3.4.0.3-py27_0.tar.bz2)'), MatchSpec('pytest (target=pytest-2.9.2-py27_0.tar.bz2)'),
MatchSpec('jinja2 (target=jinja2-2.8-py27_0.tar.bz2)'), MatchSpec('markupsafe (target=markupsafe-0.23-py27_0.tar.bz2
)'), MatchSpec('nose (target=nose-1.3.7-py27_1.tar.bz2)'), MatchSpec('pylint (target=pylint-1.5.4-py27_0.tar.bz2)'),
 MatchSpec('pycrypto (target=pycrypto-2.6.1-py27_3.tar.bz2)'), MatchSpec('clyent (target=clyent-1.2.0-py27_0.tar.bz2
)')]
DEBUG:conda.resolve:Retrieving packages for: [MatchSpec('sphinx'), MatchSpec('python 2.7* (target=python-2.7.12-0.ta
r.bz2)'), MatchSpec('conda >=4.1.11'), MatchSpec('conda-env'), MatchSpec('six (target=six-1.10.0-py27_0.tar.bz2)'),
MatchSpec('pygments (target=pygments-2.1.3-py27_0.tar.bz2)'), MatchSpec('enum34 (target=enum34-1.1.6-py27_0.tar.bz2)
'), MatchSpec('wheel (target=wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('pip (target=pip-8.1.2-py27_0.tar.bz2)'), Mat
chSpec('pep8 (target=pep8-1.7.0-py27_0.tar.bz2)'), MatchSpec('anaconda-client (target=anaconda-client-1.2.2-py27_0.t
ar.bz2)'), MatchSpec('sphinx_rtd_theme (target=sphinx_rtd_theme-0.1.9-py27_0.tar.bz2)'), MatchSpec('lazy-object-prox
y (target=lazy-object-proxy-1.2.1-py27_0.tar.bz2)'), MatchSpec('py (target=py-1.4.31-py27_0.tar.bz2)'), MatchSpec('p
ycosat (target=pycosat-0.6.1-py27_1.tar.bz2)'), MatchSpec('colorama (target=colorama-0.3.7-py27_0.tar.bz2)'), MatchS
pec('snowballstemmer (target=snowballstemmer-1.2.1-py27_0.tar.bz2)'), MatchSpec('msvc_runtime (target=msvc_runtime-1
.0.1-vc9_0.tar.bz2)'), MatchSpec('astroid (target=astroid-1.4.4-py27_0.tar.bz2)'), MatchSpec('pytz (target=pytz-2015
.7-py27_0.tar.bz2)'), MatchSpec('menuinst (target=menuinst-1.4.1-py27_0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml
-3.11-py27_4.tar.bz2)'), MatchSpec('coverage (target=coverage-4.1-py27_0.tar.bz2)'), MatchSpec('psutil (target=psuti
l-3.4.2-py27_0.tar.bz2)'), MatchSpec('docutils (target=docutils-0.12-py27_2.tar.bz2)'), MatchSpec('vs2008_runtime (t
arget=vs2008_runtime-9.00.30729.1-2.tar.bz2)'), MatchSpec('wrapt (target=wrapt-1.10.6-py27_0.tar.bz2)'), MatchSpec('
ruamel_yaml (target=ruamel_yaml-0.11.7-py27_0.tar.bz2)'), MatchSpec('babel (target=babel-2.3.3-py27_0.tar.bz2)'), Ma
tchSpec('patch (target=patch-2.5.9-1.tar.bz2)'), MatchSpec('logilab-common (target=logilab-common-1.0.2-py27_0.tar.b
z2)'), MatchSpec('requests (target=requests-2.10.0-py27_0.tar.bz2)'), MatchSpec('conda-build (target=conda-build-1.1
9.0-py27_0.tar.bz2)'), MatchSpec('alabaster (target=alabaster-0.7.8-py27_0.tar.bz2)'), MatchSpec('python-dateutil (t
arget=python-dateutil-2.4.2-py27_0.tar.bz2)'), MatchSpec('setuptools (target=setuptools-23.0.0-py27_0.tar.bz2)'), Ma
tchSpec('singledispatch (target=singledispatch-3.4.0.3-py27_0.tar.bz2)'), MatchSpec('pytest (target=pytest-2.9.2-py2
7_0.tar.bz2)'), MatchSpec('jinja2 (target=jinja2-2.8-py27_0.tar.bz2)'), MatchSpec('markupsafe (target=markupsafe-0.2
3-py27_0.tar.bz2)'), MatchSpec('nose (target=nose-1.3.7-py27_1.tar.bz2)'), MatchSpec('pylint (target=pylint-1.5.4-py
27_0.tar.bz2)'), MatchSpec('pycrypto (target=pycrypto-2.6.1-py27_3.tar.bz2)'), MatchSpec('clyent (target=clyent-1.2.
0-py27_0.tar.bz2)')]
DEBUG:conda.resolve:python: pruned from 68 -> 29
DEBUG:conda.resolve:pip: pruned from 92 -> 28
DEBUG:conda.resolve:conda: pruned from 310 -> 1
DEBUG:conda.resolve:menuinst: pruned from 40 -> 15
DEBUG:conda.resolve:pyyaml: pruned from 26 -> 7
DEBUG:conda.resolve:conda-env: pruned from 66 -> 2
DEBUG:conda.resolve:pycosat: pruned from 33 -> 10
DEBUG:conda.resolve:requests: pruned from 85 -> 23
DEBUG:conda.resolve:ruamel_yaml: pruned from 6 -> 2
DEBUG:conda.resolve:six: pruned from 37 -> 10
DEBUG:conda.resolve:pygments: pruned from 25 -> 7
DEBUG:conda.resolve:enum34: pruned from 11 -> 7
DEBUG:conda.resolve:wheel: pruned from 15 -> 4
DEBUG:conda.resolve:pep8: pruned from 28 -> 8
DEBUG:conda.resolve:anaconda-client: pruned from 34 -> 10
DEBUG:conda.resolve:clyent: pruned from 31 -> 9
DEBUG:conda.resolve:pytz: pruned from 63 -> 18
DEBUG:conda.resolve:setuptools: pruned from 183 -> 49
DEBUG:conda.resolve:python-dateutil: pruned from 21 -> 6
DEBUG:conda.resolve:sphinx_rtd_theme: pruned from 8 -> 2
DEBUG:conda.resolve:lazy-object-proxy: pruned from 3 -> 1
DEBUG:conda.resolve:py: pruned from 45 -> 13
DEBUG:conda.resolve:colorama: pruned from 19 -> 5
DEBUG:conda.resolve:snowballstemmer: pruned from 8 -> 2
DEBUG:conda.resolve:msvc_runtime: pruned from 6 -> 2
DEBUG:conda.resolve:astroid: pruned from 33 -> 9
DEBUG:conda.resolve:coverage: pruned from 13 -> 4
DEBUG:conda.resolve:psutil: pruned from 72 -> 21
DEBUG:conda.resolve:docutils: pruned from 21 -> 7
DEBUG:conda.resolve:wrapt: pruned from 3 -> 1
DEBUG:conda.resolve:babel: pruned from 18 -> 5
DEBUG:conda.resolve:logilab-common: pruned from 18 -> 5
DEBUG:conda.resolve:conda-build: pruned from 156 -> 52
DEBUG:conda.resolve:alabaster: pruned from 13 -> 4
DEBUG:conda.resolve:singledispatch: pruned from 3 -> 1
DEBUG:conda.resolve:pytest: pruned from 63 -> 20
DEBUG:conda.resolve:jinja2: pruned from 33 -> 9
DEBUG:conda.resolve:markupsafe: pruned from 18 -> 5
DEBUG:conda.resolve:nose: pruned from 38 -> 11
DEBUG:conda.resolve:pylint: pruned from 29 -> 8
DEBUG:conda.resolve:astroid: pruned from 9 -> 7
DEBUG:conda.resolve:pycrypto: pruned from 22 -> 6
DEBUG:conda.resolve:sphinx: pruned from 44 -> 14
.DEBUG:dotupdate:Checking satisfiability
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package removal metric: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,7)
DEBUG:conda.logic:Bisection attempt: (0,0), (3551+14) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (3565+6) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 1/1 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (3571+1) clauses
DEBUG:conda.logic:Bisection failure, new range=(1,1)
DEBUG:conda.logic:Bisection attempt: (1,1), (3571+1) clauses
DEBUG:conda.logic:Bisection success, new range=(1,1)
DEBUG:conda.logic:Final sum objective: 1
DEBUG:conda.logic:New peak objective: 1
.DEBUG:dotupdate:Track feature count: 1
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Eliminating 7/7 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (3572+7) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Package feature count: 7
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,37)
DEBUG:conda.logic:Eliminating 41/41 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (3579+41) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Dependency update count: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Bisection attempt: (0,0), (3620+367) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (3987+58) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 9/9 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (4045+9) clauses
DEBUG:conda.logic:Bisection failure, new range=(1,1)
DEBUG:conda.logic:Bisection attempt: (1,1), (4045+39) clauses
DEBUG:conda.logic:Bisection success, new range=(1,1)
DEBUG:conda.logic:Final sum objective: 1
DEBUG:conda.logic:New peak objective: 1
.DEBUG:dotupdate:Weak dependency count: 1
.DEBUG:dotupdate:Looking for alternate solutions

INFO:stdoutlog:

Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment C:\dev\sw\miniconda2:

The following NEW packages will be INSTALLED:

    imagesize: 0.7.1-py27_0
    sphinx:    1.4.1-py27_0

Proceed ([y]/n)?

DEBUG:conda.plan:Adding plans for operations: ('RM_FETCHED', 'FETCH', 'RM_EXTRACTED', 'EXTRACT', 'UNLINK', 'LINK', '
SYMLINK_CONDA')
DEBUG:conda.plan:action RM_FETCHED not in actions
DEBUG:conda.plan:action FETCH not in actions
DEBUG:conda.plan:action RM_EXTRACTED not in actions
DEBUG:conda.plan:action EXTRACT not in actions
DEBUG:conda.plan:action UNLINK not in actions
DEBUG:conda.plan:appending value imagesize-0.7.1-py27_0 1 for action LINK
DEBUG:conda.plan:appending value sphinx-1.4.1-py27_0 1 for action LINK
DEBUG:conda.plan:appending value C:\dev\sw\miniconda2 for action SYMLINK_CONDA
DEBUG:conda.instructions: PREFIX('C:\\dev\\sw\\miniconda2')
DEBUG:conda.instructions: PRINT('Linking packages ...')
Linking packages ...
INFO:print:Linking packages ...
DEBUG:conda.instructions: PROGRESS('2')
INFO:progress.start:2]|                                                  |   0%
DEBUG:conda.instructions: LINK(u'imagesize-0.7.1-py27_0 1')
INFO:progress.update:('imagesize', 0)                                    |   0%
DEBUG:conda.install:pkgs_dir='C:\\dev\\sw\\miniconda2\\pkgs', prefix='C:\\dev\\sw\\miniconda2', dist=u'imagesize-0.7
.1-py27_0', linktype=1
DEBUG:conda.instructions: LINK(u'sphinx-1.4.1-py27_0 1')
INFO:progress.update:('sphinx', 1)##############                         |  50%
DEBUG:conda.install:pkgs_dir='C:\\dev\\sw\\miniconda2\\pkgs', prefix='C:\\dev\\sw\\miniconda2', dist=u'sphinx-1.4.1-
py27_0', linktype=1
[      COMPLETE      ]|##################################################| 100%
INFO:progress.stop:None
DEBUG:conda.instructions: SYMLINK_CONDA('C:\\dev\\sw\\miniconda2')

c:\dev\workspace\collaboar\doc\sphinx\collaboar>conda list
# packages in environment at C:\dev\sw\miniconda2:
#
alabaster                 0.7.8                    py27_0
anaconda-client           1.2.2                    py27_0
astroid                   1.4.4                    py27_0
babel                     2.3.3                    py27_0
backports.shutil-get-terminal-size 1.0.0                     <pip>
clyent                    1.2.0                    py27_0
colorama                  0.3.7                    py27_0
conda                     4.1.11                   py27_0
conda-build               1.19.0                   py27_0
conda-env                 2.5.2                    py27_0
coverage                  4.1                      py27_0
decorator                 4.0.10                    <pip>
docutils                  0.12                     py27_2
enum34                    1.1.6                    py27_0
imagesize                 0.7.1                    py27_0
ipython                   4.2.1                     <pip>
ipython-genutils          0.1.0                     <pip>
jinja2                    2.8                      py27_0
lazy-object-proxy         1.2.1                    py27_0
logilab-common            1.0.2                    py27_0
markupsafe                0.23                     py27_0
menuinst                  1.4.1                    py27_0
msvc_runtime              1.0.1                     vc9_0  [vc9]
nose                      1.3.7                    py27_1
nose2                     0.6.5                     <pip>
patch                     2.5.9                         1
pathlib2                  2.1.0                     <pip>
pep8                      1.7.0                    py27_0
pickleshare               0.7.2                     <pip>
pip                       8.1.2                    py27_0
psutil                    3.4.2                    py27_0
py                        1.4.31                   py27_0
pycosat                   0.6.1                    py27_1
pycrypto                  2.6.1                    py27_3
pygments                  2.1.3                    py27_0
pylint                    1.5.4                    py27_0
pytest                    2.9.2                    py27_0
python                    2.7.12                        0
python-dateutil           2.4.2                    py27_0
pytz                      2015.7                   py27_0
pyyaml                    3.11                     py27_4
requests                  2.10.0                   py27_0
ruamel_yaml               0.11.7                   py27_0
setuptools                23.0.0                   py27_0
simplegeneric             0.8.1                     <pip>
singledispatch            3.4.0.3                  py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sphinx                    1.4.1                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
traitlets                 4.2.2                     <pip>
unittest-xml-reporting    2.1.0                     <pip>
vs2008_runtime            9.00.30729.1                  2
wheel                     0.29.0                   py27_0
wrapt                     1.10.6                   py27_0`

**Comment by HugoTian** [comment]
Since it works for your now, I am about to close this issue, and we will have better solution or better error message when such error occurs in conda4.2
