### ISSUE TITLE
Latest conda version fails during install

### ISSUE THREAD

**Issue by rohitjamuar** [conda/conda#3246]
With conda-**4.1.3**, I could conda install our distribution using -
**<path_to_distribution>/pkgs/python-2.7.11/bin/python2 -E <path_to_distribution>/pkgs/conda-4.1.3-py27_0/lib/python2.7/site-packages/conda/install.py --prefix=<prefix>** 

After updating conda to **4.1.11**, running the same command gives this trace:

```
Traceback (most recent call last):
  File "pkgs/conda-4.1.11-py27_0/lib/python2.7/site-packages/conda/install.py", line 1252, in <module>
    main()
  File "pkgs/conda-4.1.11-py27_0/lib/python2.7/site-packages/conda/install.py", line 1238, in main
    link(prefix, dist, linktype)
  File "pkgs/conda-4.1.11-py27_0/lib/python2.7/site-packages/conda/install.py", line 1089, in link
    if config.shortcuts:
NameError: global name 'config' is not defined
```

How could this be resolved?

**Comment by HugoTian** [comment]
Previously , conda/install.py can be a stand alone module, any import failure will be well-handled.

However, we decided not let conda/install.py be a stand alone module anymore.  Therefore, new added code may leads to import error. 

You can try to use "conda install" , hope it works fine with your distribution

**Comment by HugoTian** [comment]
If it fails, please roll back to conda 4.1.3. Moreover, could you please share the reason why you want to use this stand alone install.py instead of "conda install". We may bring this feature back in future

**Comment by tomashek** [comment]
Hugo, we are creating a conda-compatible installation, and this method was how we were told to do an installation.

Basically, we have a "pkgs" directory with a set of conda packages. Then we execute the conda install script by running "pkgs/python.../bin/python pkgs/conda-4.1.11-py27_0/lib/python2.7/site-packages/conda/install.py" as you see above. In the past, this then linked all the packages in the "pkgs" dir to the directory that contained pkgs.

Is there another supported way to do this installation now?

@mcg1969  can you help here?

**Comment by mcg1969** [comment]
I've been away from conda development for awhile here. I'm not sure what the specific changes have been that lead to this. @kalefranz, do you know? Rolling back all the way to 4.1.3 is not a good solution, because of the many other fixes that are included in the intervening versions. 

I'm going to guess that this is related to @ilanschnell's creation of `libconda` and therefore the relaxation of the requirement that `conda.install` run in standalone mode. If that's the case, then Todd et. al. need precise instructions on the replacement for this idiom.

**Comment by tomashek** [comment]
Unfortunately, we need them pretty quickly too.

The basic use case is: we have a set of conda packages in a directory, including conda itself and python, and we need to install all of them to setup a root environment.

**Comment by mcg1969** [comment]
My quick and dirty suggestions: 1) fall back to conda 4.1.3, or to the version immediately prior to the breakage of standalone capability (hopefully @kalefranz can identify that version soon); or 2) pull `install.py` from 4.1.3, and include that in the installer, separate from whatever conda version you package up.

**Comment by mcg1969** [comment]
I'd recommend the `constructor` package, but I know that you're wrapping a custom installer around this, so I don't think that will work for you.

**Comment by mcg1969** [comment]
It looks like this is the commit where `config.shortcuts` was introduced:

https://github.com/conda/conda/commit/9c248f8687e9b71a0439a680bd651c53b3584901

@msarahan, this looks like something you needed for conda-build. Any advice for Todd here? Todd @tomashek it looks like this was introduced in conda 4.1.8.

**Comment by tomashek** [comment]
I just implemented a quick patch that defines "config" in the existing import exception block and modifies line 1089 to: "if config and config.shortcuts:".  Works so far, and I can't think of how it could break the logic.

**Comment by tomashek** [comment]
So I think we're okay for now, but I would like to know the recommended way we should be bootstrapping a root installation now that install.py is not standalone.

**Comment by msarahan** [comment]
This seems like I could have handled it better with not assuming config should be available.  I can put up a patch later.  It sounds like your patch would be fine if you want to put that in instead, though.

I think that it would also be very worthwhile to add a test for assumptions like these (if we still need install.py to be standalone) - more so than just a code comment.

**Comment by kalefranz** [comment]
`install.py` *should* be standalone through the 4.1.x release series.  I'm happy to accept patches to 4.1.x to ensure that's the case.  As of 4.2.x, it won't be.  At some point, we might go back and make a separate standalone package.  For now, the 4.1.x install.py can be used, or @ilanschnell's libconda.

**Comment by tomashek** [comment]
@kalefranz , how do we bootstrap an installation with 4.2.x if install.py will no longer run standalone? We will need a solution for this before our next full product release or we will not be able to include 4.2.x.

**Comment by tomashek** [comment]
@kalefranz , is there a supported standalone "install" that can be used to bootstrap a root environment installation now?

**Comment by tomashek** [comment]
@kalefranz @msarahan , is there a supported standalone "install" that can be used to bootstrap a root environment installation now?

**Comment by kalefranz** [comment]
Yes, with https://github.com/conda/constructor :)
