### ISSUE TITLE
Progressbar creates newline on each refresh

### ISSUE THREAD

**Issue by brendancol** [conda/conda#3249]
Could be only my problem, but the progress bar is on a different line for each refresh

<img width="709" alt="screen shot 2016-08-08 at 3 07 01 pm" src="https://cloud.githubusercontent.com/assets/433221/17494379/0ea212d2-5d7a-11e6-8a19-43779f7fae3d.png">

**Comment by HugoTian** [comment]
Can you show me the output of conda info ?

In some version of conda and conda-build, there are lots of noisy output("like INFO..."), which leads to this unclean progress bar.  I think there is already a fix for this one, and please try to update conda and conda-build

Thanks

**Comment by brendancol** [comment]
I updated `conda-build` and all looks good. thanks.

```
(elm-env) ➜  ~ conda-build --version
conda-build 1.21.11+0.g5b44ab3.dirty
```
