### ISSUE TITLE
spyder wont start...new install fails

### ISSUE THREAD

**Issue by brettwujek** [conda/conda#3250]
Recently for some reason my spyder application just wont start anymore - it flashes and then fails.  I found on a message board to just try to run the installer again ("conda install spyder")...it fails with:

Z:\>conda install spyder
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Program Files\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |            vc9_0         175 KB
    openssl-1.0.2h             |            vc9_0         4.4 MB
    vs2008_runtime-9.00.30729.1|                2         1.0 MB
    zlib-1.2.8                 |            vc9_3         108 KB
    alabaster-0.7.8            |           py27_0          18 KB
    backports-1.0              |           py27_0           1 KB
    backports_abc-0.4          |           py27_0           5 KB
    colorama-0.3.7             |           py27_0          19 KB
    conda-env-2.5.2            |           py27_0          67 KB
    decorator-4.0.10           |           py27_0          12 KB
    docutils-0.12              |           py27_2         640 KB
    functools32-3.2.3.2        |           py27_0          15 KB
    imagesize-0.7.1            |           py27_0           3 KB
    ipython_genutils-0.1.0     |           py27_0          32 KB
    jedi-0.9.0                 |           py27_1         191 KB
    libpng-1.6.22              |            vc9_0         524 KB
    libtiff-4.0.6              |            vc9_2         466 KB
    markupsafe-0.23            |           py27_2          25 KB
    menuinst-1.4.1             |           py27_0         105 KB
    mistune-0.7.2              |           py27_0         125 KB
    path.py-8.2.1              |           py27_0          45 KB
    pep8-1.7.0                 |           py27_0          88 KB
    pyflakes-1.2.3             |           py27_0         112 KB
    pygments-2.1.3             |           py27_0         1.2 MB
    pytz-2016.6.1              |           py27_0         171 KB
    pyyaml-3.11                |           py27_4         169 KB
    pyzmq-15.3.0               |           py27_0         485 KB
    requests-2.10.0            |           py27_0         615 KB
    ruamel_yaml-0.11.14        |           py27_0         212 KB
    setuptools-25.1.6          |           py27_0         707 KB
    simplegeneric-0.8.1        |           py27_1           6 KB
    sip-4.18                   |           py27_0         260 KB
    six-1.10.0                 |           py27_0          16 KB
    snowballstemmer-1.2.1      |           py27_0          73 KB
    sphinx_rtd_theme-0.1.9     |           py27_0         629 KB
    wcwidth-0.1.7              |           py27_0          21 KB
    wheel-0.29.0               |           py27_0         121 KB
    win_unicode_console-0.5    |           py27_0          27 KB
    babel-2.3.3                |           py27_0         5.0 MB
    conda-4.1.11               |           py27_0         245 KB
    configparser-3.5.0         |           py27_0          31 KB
    get_terminal_size-1.0.0    |           py27_0           4 KB
    jinja2-2.8                 |           py27_1         265 KB
    jsonschema-2.5.1           |           py27_0          96 KB
    pathlib2-2.1.0             |           py27_0          26 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    prompt_toolkit-1.0.3       |           py27_0         296 KB
    qt-4.8.7                   |            vc9_9        50.3 MB
    singledispatch-3.4.0.3     |           py27_0          12 KB
    ssl_match_hostname-3.4.0.2 |           py27_1           6 KB
    traitlets-4.2.2            |           py27_0         108 KB
    entrypoints-0.2.2          |           py27_0           6 KB
    jupyter_core-4.1.0         |           py27_0         100 KB
    pickleshare-0.7.3          |           py27_0           8 KB
    pyqt-4.11.4                |           py27_7         3.7 MB
    sphinx-1.4.1               |           py27_0         1.3 MB
    tornado-4.4.1              |           py27_0         551 KB
    ipython-5.0.0              |           py27_0         987 KB
    jupyter_client-4.3.0       |           py27_0         138 KB
    nbformat-4.0.1             |           py27_0         155 KB
    ipykernel-4.3.1            |           py27_0         117 KB
    nbconvert-4.2.0            |           py27_0         354 KB
    qtconsole-4.2.1            |           py27_0         203 KB
    spyder-2.3.9               |           py27_0         2.1 MB
    ------------------------------------------------------------
                                           Total:        80.2 MB

The following NEW packages will be INSTALLED:

    alabaster:           0.7.8-py27_0
    babel:               2.3.3-py27_0
    backports:           1.0-py27_0
    backports_abc:       0.4-py27_0
    configparser:        3.5.0-py27_0
    entrypoints:         0.2.2-py27_0
    functools32:         3.2.3.2-py27_0
    get_terminal_size:   1.0.0-py27_0
    imagesize:           0.7.1-py27_0
    ipykernel:           4.3.1-py27_0
    ipython_genutils:    0.1.0-py27_0
    jpeg:                8d-vc9_0        [vc9]
    jupyter_client:      4.3.0-py27_0
    jupyter_core:        4.1.0-py27_0
    libpng:              1.6.22-vc9_0    [vc9]
    libtiff:             4.0.6-vc9_2     [vc9]
    nbconvert:           4.2.0-py27_0
    nbformat:            4.0.1-py27_0
    openssl:             1.0.2h-vc9_0    [vc9]
    path.py:             8.2.1-py27_0
    pathlib2:            2.1.0-py27_0
    pickleshare:         0.7.3-py27_0
    prompt_toolkit:      1.0.3-py27_0
    qt:                  4.8.7-vc9_9     [vc9]
    qtconsole:           4.2.1-py27_0
    ruamel_yaml:         0.11.14-py27_0
    simplegeneric:       0.8.1-py27_1
    singledispatch:      3.4.0.3-py27_0
    sip:                 4.18-py27_0
    snowballstemmer:     1.2.1-py27_0
    sphinx_rtd_theme:    0.1.9-py27_0
    traitlets:           4.2.2-py27_0
    vs2008_runtime:      9.00.30729.1-2
    wcwidth:             0.1.7-py27_0
    wheel:               0.29.0-py27_0
    win_unicode_console: 0.5-py27_0
    zlib:                1.2.8-vc9_3     [vc9]

The following packages will be UPDATED:

    colorama:            0.3.3-py27_0   --> 0.3.7-py27_0
    conda:               3.10.0-py27_0  --> 4.1.11-py27_0
    conda-env:           2.1.3-py27_0   --> 2.5.2-py27_0
    decorator:           3.4.0-py27_0   --> 4.0.10-py27_0
    docutils:            0.12-py27_1    --> 0.12-py27_2
    ipython:             3.0.0-py27_1   --> 5.0.0-py27_0
    jedi:                0.8.1-py27_0   --> 0.9.0-py27_1
    jinja2:              2.7.3-py27_2   --> 2.8-py27_1
    jsonschema:          2.4.0-py27_0   --> 2.5.1-py27_0
    markupsafe:          0.23-py27_0    --> 0.23-py27_2
    menuinst:            1.0.4-py27_0   --> 1.4.1-py27_0
    mistune:             0.5.1-py27_0   --> 0.7.2-py27_0
    pep8:                1.6.2-py27_0   --> 1.7.0-py27_0
    pip:                 6.0.8-py27_0   --> 8.1.2-py27_0
    pyflakes:            0.8.1-py27_0   --> 1.2.3-py27_0
    pygments:            2.0.2-py27_0   --> 2.1.3-py27_0
    pyqt:                4.10.4-py27_1  --> 4.11.4-py27_7
    pytz:                2015.2-py27_0  --> 2016.6.1-py27_0
    pyyaml:              3.11-py27_0    --> 3.11-py27_4
    pyzmq:               14.5.0-py27_0  --> 15.3.0-py27_0
    requests:            2.6.0-py27_0   --> 2.10.0-py27_0
    setuptools:          14.3-py27_0    --> 25.1.6-py27_0
    six:                 1.9.0-py27_0   --> 1.10.0-py27_0
    sphinx:              1.2.3-py27_0   --> 1.4.1-py27_0
    spyder:              2.3.4-py27_1   --> 2.3.9-py27_0
    ssl_match_hostname:  3.4.0.2-py27_0 --> 3.4.0.2-py27_1
    tornado:             4.1-py27_0     --> 4.4.1-py27_0

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Program Files\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 202
, in main
    args_func(args, p)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 207
, in args_func
    args.func(args, p)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main_install.py",
line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line
404, in install
    if not pscheck.main(args):
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\pscheck.py", line
66, in main
    while not check_processes():
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\pscheck.py", line
33, in check_processes
    for n in psutil.get_pid_list():
AttributeError: 'module' object has no attribute 'get_pid_list'

Z:\>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : C:\Program Files\Anaconda  (writable)
  default environment : C:\Program Files\Anaconda
     envs directories : C:\Program Files\Anaconda\envs
        package cache : C:\Program Files\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ccordoba12** [comment]
Is there any message printed in the terminal if you

    spyder --show-console

there?

**Comment by HugoTian** [comment]
Please refer to [here](https://github.com/conda/conda-build/issues/527), psutil.get_pid_list is no long used in latest conda, and I believe we will not use psutil in future. Please try to update conda, and psutil(optional) using conda command, and hope it will fix it

Thanks

**Comment by brettwujek** [comment]
Z:\>spyder --show-console
C:\Program Files\Python-2.7.8.10\Lib\site-packages\IPython\qt.py:13:
ShimWarning
: The `IPython.qt` package has been deprecated. You should import from
qtconsole
 instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "C:\Program Files\Anaconda\lib\site-packages\spyderlib\spyder.py",
line 2
367, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Program Files\Anaconda\lib\site-packages\spyderlib\spyder.py",
line 2
255, in run_spyder
    main.setup()
  File "C:\Program Files\Anaconda\lib\site-packages\spyderlib\spyder.py",
line 8
01, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Program
Files\Anaconda\lib\site-packages\spyderlib\plugins\inspector.
py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "C:\Program
Files\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py
", line 27, in <module>
    pygments_patch.apply()
  File "C:\Program
Files\Anaconda\lib\site-packages\spyderlib\pygments_patch.py"
, line 27, in apply
    from IPython.frontend.qt.console.pygments_highlighter import RegexLexer
ImportError: No module named pygments_highlighter

**Comment by ccordoba12** [comment]
This line in your error report

    C:\Program Files\Python-2.7.8.10\Lib\site-packages\IPython\qt.py:13

shows that you have another Python version installed in your system. Please remove that version and try again. I'm almost sure your problems will be solved after that :-)
