### ISSUE TITLE
Anaconda installs into my system root on OS X

### ISSUE THREAD

**Issue by alper** [conda/conda#3254]
I went through the Anaconda installer and I think because the user interface is unclear it has installed itself into my system root. This is non-standard behaviour.

When installers on OS X ask for a destination, picking your main Hard Drive is considered to be the choice of disk where to install something, not the literal path intended.

After installation `which python` returns `//anaconda/bin/python` which is also an incorrect path for OS X.

**Comment by HugoTian** [comment]
We do have that question during testing, please uninstall (delete folder) and reinstall using bash installer. Generally, it will install under home directory on OS X

**Comment by alper** [comment]
Thanks, I did that and reinstalled it. There is a lot of documentation that explains this process but that is of course overlooked when clicking through a default installer.
