### ISSUE TITLE
Unlinking packages ... An unexpected error has occurred

### ISSUE THREAD

**Issue by purexa** [conda/conda#3263]
The following NEW packages will be INSTALLED:

    _nb_ext_conf:       0.2.0-py27_0
    backports:          1.0-py27_0
    click:              6.6-py27_0
    configparser:       3.5.0b2-py27_1
    contextlib2:        0.5.3-py27_0
    entrypoints:        0.2.2-py27_0
    functools32:        3.2.3.2-py27_0
    get_terminal_size:  1.0.0-py27_0
    imagesize:          0.7.1-py27_0
    nb_anacondacloud:   1.1.0-py27_0
    nb_conda:           1.1.0-py27_0
    nb_conda_kernels:   1.0.3-py27_0
    nbpresent:          3.0.2-py27_0
    pathlib2:           2.1.0-py27_0
    pycurl:             7.43.0-py27_0
    ruamel_yaml:        0.11.7-py27_0

The following packages will be UPDATED:

    alabaster:          0.7.7-py27_0       --> 0.7.8-py27_0
    anaconda:           4.0.0-np110py27_0  --> 4.1.1-np111py27_0
    anaconda-navigator: 1.1.0-py27_0       --> 1.2.1-py27_0
    astropy:            1.1.2-np110py27_0  --> 1.2.1-np111py27_0
    babel:              2.2.0-py27_0       --> 2.3.3-py27_0
    blaze:              0.9.1-py27_0       --> 0.10.1-py27_0
    bokeh:              0.11.1-py27_0      --> 0.12.0-py27_0
    boto:               2.39.0-py27_0      --> 2.40.0-py27_0
    bottleneck:         1.0.0-np110py27_0  --> 1.1.0-np111py27_0
    bzip2:              1.0.6-vc9_2        [vc9] --> 1.0.6-vc9_3        [vc9]
    cdecimal:           2.3-py27_1         --> 2.3-py27_2
    cffi:               1.5.2-py27_0       --> 1.6.0-py27_0
    cloudpickle:        0.1.1-py27_0       --> 0.2.1-py27_0
    clyent:             1.2.1-py27_0       --> 1.2.2-py27_0
    conda:              4.0.5-py27_0       --> 4.1.11-py27_0
    conda-env:          2.4.5-py27_0       --> 2.5.1-py27_0
    cryptography:       1.3-py27_0         --> 1.4-py27_0
    curl:               7.45.0-vc9_1       [vc9] --> 7.49.0-vc9_0       [vc9]
    cython:             0.23.4-py27_0      --> 0.24-py27_0
    cytoolz:            0.7.5-py27_0       --> 0.8.0-py27_0
    dask:               0.8.1-py27_0       --> 0.10.0-py27_0
    datashape:          0.5.1-py27_0       --> 0.5.2-py27_0
    decorator:          4.0.9-py27_0       --> 4.0.10-py27_0
    dill:               0.2.4-py27_0       --> 0.2.5-py27_0
    docutils:           0.12-py27_1        --> 0.12-py27_2
    enum34:             1.1.2-py27_0       --> 1.1.6-py27_0
    fastcache:          1.0.2-py27_0       --> 1.0.2-py27_1
    flask:              0.10.1-py27_1      --> 0.11.1-py27_0
    freetype:           2.5.5-vc9_0        [vc9] --> 2.5.5-vc9_1        [vc9]
    funcsigs:           0.4-py27_0         --> 1.0.2-py27_0
    futures:            3.0.3-py27_0       --> 3.0.5-py27_0
    gevent:             1.1.0-py27_0       --> 1.1.1-py27_0
    greenlet:           0.4.9-py27_0       --> 0.4.10-py27_0
    grin:               1.2.1-py27_2       --> 1.2.1-py27_3
    h5py:               2.5.0-np110py27_4  --> 2.6.0-np111py27_0
    heapdict:           1.0.0-py27_0       --> 1.0.0-py27_1
    idna:               2.0-py27_0         --> 2.1-py27_0
    ipaddress:          1.0.14-py27_0      --> 1.0.16-py27_0
    ipython:            4.1.2-py27_1       --> 4.2.0-py27_0
    jdcal:              1.2-py27_0         --> 1.2-py27_1
    jedi:               0.9.0-py27_0       --> 0.9.0-py27_1
    jinja2:             2.8-py27_0         --> 2.8-py27_1
    jsonschema:         2.4.0-py27_0       --> 2.5.1-py27_0
    jupyter:            1.0.0-py27_2       --> 1.0.0-py27_3
    jupyter_client:     4.2.2-py27_0       --> 4.3.0-py27_0
    libpng:             1.6.17-vc9_1       [vc9] --> 1.6.22-vc9_0       [vc9]
    libtiff:            4.0.6-vc9_1        [vc9] --> 4.0.6-vc9_2        [vc9]
    llvmlite:           0.9.0-py27_0       --> 0.11.0-py27_0
    locket:             0.2.0-py27_0       --> 0.2.0-py27_1
    markupsafe:         0.23-py27_1        --> 0.23-py27_2
    matplotlib:         1.5.1-np110py27_0  --> 1.5.1-np111py27_0
    menuinst:           1.3.2-py27_0       --> 1.4.1-py27_0
    mkl:                11.3.1-0           --> 11.3.3-1
    mkl-service:        1.1.2-py27_0       --> 1.1.2-py27_2
    mpmath:             0.19-py27_0        --> 0.19-py27_1
    nbconvert:          4.1.0-py27_0       --> 4.2.0-py27_0
    nltk:               3.2-py27_0         --> 3.2.1-py27_0
    nose:               1.3.7-py27_0       --> 1.3.7-py27_1
    notebook:           4.1.0-py27_2       --> 4.2.1-py27_0
    numba:              0.24.0-np110py27_0 --> 0.26.0-np111py27_0
    numexpr:            2.5-np110py27_0    --> 2.6.0-np111py27_0
    numpy:              1.10.4-py27_0      --> 1.11.1-py27_0
    odo:                0.4.2-py27_0       --> 0.5.0-py27_1
    openssl:            1.0.2g-vc9_0       [vc9] --> 1.0.2h-vc9_0       [vc9]
    pandas:             0.18.0-np110py27_0 --> 0.18.1-np111py27_0
    partd:              0.3.2-py27_1       --> 0.3.4-py27_0
    path.py:            8.1.2-py27_1       --> 8.2.1-py27_0
    patsy:              0.4.0-np110py27_0  --> 0.4.1-py27_0
    pickleshare:        0.5-py27_0         --> 0.7.2-py27_0
    pillow:             3.1.1-py27_0       --> 3.2.0-py27_1
    pip:                8.1.1-py27_1       --> 8.1.2-py27_0
    psutil:             4.1.0-py27_0       --> 4.3.0-py27_0
    pycosat:            0.6.1-py27_0       --> 0.6.1-py27_1
    pycparser:          2.14-py27_0        --> 2.14-py27_1
    pycrypto:           2.6.1-py27_3       --> 2.6.1-py27_4
    pyflakes:           1.1.0-py27_0       --> 1.2.3-py27_0
    pygments:           2.1.1-py27_0       --> 2.1.3-py27_0
    pyopenssl:          0.15.1-py27_2      --> 0.16.0-py27_0
    pyparsing:          2.0.3-py27_0       --> 2.1.4-py27_0
    pyqt:               4.11.4-py27_5      --> 4.11.4-py27_6
    pytables:           3.2.2-np110py27_2  --> 3.2.2-np111py27_4
    pytest:             2.8.5-py27_0       --> 2.9.2-py27_0
    python:             2.7.11-4           --> 2.7.12-0
    python-dateutil:    2.5.1-py27_0       --> 2.5.3-py27_0
    pytz:               2016.2-py27_0      --> 2016.4-py27_0
    pyyaml:             3.11-py27_3        --> 3.11-py27_4
    qt:                 4.8.7-vc9_7        [vc9] --> 4.8.7-vc9_8        [vc9]
    qtconsole:          4.2.0-py27_1       --> 4.2.1-py27_0
    qtpy:               1.0-py27_0         --> 1.0.2-py27_0
    requests:           2.9.1-py27_0       --> 2.10.0-py27_0
    scikit-image:       0.12.3-np110py27_0 --> 0.12.3-np111py27_1
    scikit-learn:       0.17.1-np110py27_0 --> 0.17.1-np111py27_1
    scipy:              0.17.0-np110py27_0 --> 0.17.1-np111py27_1
    setuptools:         20.3-py27_0        --> 23.0.0-py27_0
    simplegeneric:      0.8.1-py27_0       --> 0.8.1-py27_1
    sockjs-tornado:     1.0.1-py27_0       --> 1.0.3-py27_0
    sphinx:             1.3.5-py27_0       --> 1.4.1-py27_0
    spyder:             2.3.8-py27_1       --> 2.3.9-py27_0
    sqlalchemy:         1.0.12-py27_0      --> 1.0.13-py27_0
    ssl_match_hostname: 3.4.0.2-py27_0     --> 3.4.0.2-py27_1
    statsmodels:        0.6.1-np110py27_0  --> 0.6.1-np111py27_1
    toolz:              0.7.4-py27_0       --> 0.8.0-py27_0
    tornado:            4.3-py27_0         --> 4.3-py27_1
    vs2008_runtime:     9.00.30729.1-0     --> 9.00.30729.1-2
    werkzeug:           0.11.4-py27_0      --> 0.11.10-py27_0
    xlrd:               0.9.4-py27_0       --> 1.0.0-py27_0
    xlsxwriter:         0.8.4-py27_0       --> 0.9.2-py27_0
    xlwings:            0.7.0-py27_0       --> 0.7.2-py27_0
    xlwt:               1.0.0-py27_0       --> 1.1.2-py27_0
    zlib:               1.2.8-vc9_2        [vc9] --> 1.2.8-vc9_3        [vc9]

Proceed ([y]/n)? y

menuinst-1.4.1 100% |###############################| Time: 0:00:00 117.81 kB/s
Fetching packages ...
mkl-11.3.3-1.t 100% |###############################| Time: 0:11:43 164.08 kB/s
vs2008_runtime 100% |###############################| Time: 0:00:08 127.76 kB/s
bzip2-1.0.6-vc 100% |###############################| Time: 0:00:01  83.98 kB/s
openssl-1.0.2h 100% |###############################| Time: 0:00:14 311.96 kB/s
python-2.7.12- 100% |###############################| Time: 0:02:02 201.44 kB/s
zlib-1.2.8-vc9 100% |###############################| Time: 0:00:01  88.63 kB/s
alabaster-0.7. 100% |###############################| Time: 0:00:00  67.42 kB/s
backports-1.0- 100% |###############################| Time: 0:00:00 533.98 kB/s
boto-2.40.0-py 100% |###############################| Time: 0:00:06 232.46 kB/s
cdecimal-2.3-p 100% |###############################| Time: 0:00:01  72.48 kB/s
click-6.6-py27 100% |###############################| Time: 0:00:00 103.45 kB/s
cloudpickle-0. 100% |###############################| Time: 0:00:00  65.21 kB/s
conda-env-2.5. 100% |###############################| Time: 0:00:00  76.06 kB/s
contextlib2-0. 100% |###############################| Time: 0:00:00  42.68 kB/s
curl-7.49.0-vc 100% |###############################| Time: 0:00:03  84.96 kB/s
cython-0.24-py 100% |###############################| Time: 0:00:11 190.54 kB/s
decorator-4.0. 100% |###############################| Time: 0:00:00  32.05 kB/s
dill-0.2.5-py2 100% |###############################| Time: 0:00:01  62.41 kB/s
docutils-0.12- 100% |###############################| Time: 0:00:04 141.59 kB/s
enum34-1.1.6-p 100% |###############################| Time: 0:00:01  54.21 kB/s
fastcache-1.0. 100% |###############################| Time: 0:00:00  72.38 kB/s
funcsigs-1.0.2 100% |###############################| Time: 0:00:00  82.56 kB/s
functools32-3. 100% |###############################| Time: 0:00:00  47.50 kB/s
futures-3.0.5- 100% |###############################| Time: 0:00:00  82.90 kB/s
greenlet-0.4.1 100% |###############################| Time: 0:00:00  46.08 kB/s
grin-1.2.1-py2 100% |###############################| Time: 0:00:00  74.23 kB/s
heapdict-1.0.0 100% |###############################| Time: 0:00:00   2.70 MB/s
idna-2.1-py27_ 100% |###############################| Time: 0:00:01  79.14 kB/s
imagesize-0.7. 100% |###############################| Time: 0:00:00 263.46 kB/s
ipaddress-1.0. 100% |###############################| Time: 0:00:00  58.38 kB/s
jdcal-1.2-py27 100% |###############################| Time: 0:00:00   4.40 MB/s
jedi-0.9.0-py2 100% |###############################| Time: 0:00:02  86.42 kB/s
libpng-1.6.22- 100% |###############################| Time: 0:00:04 115.35 kB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:06  68.92 kB/s
locket-0.2.0-p 100% |###############################| Time: 0:00:00   2.01 MB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00  47.39 kB/s
mkl-service-1. 100% |###############################| Time: 0:00:00   2.63 MB/s
mpmath-0.19-py 100% |###############################| Time: 0:00:07 121.10 kB/s
nltk-3.2.1-py2 100% |###############################| Time: 0:00:08 205.03 kB/s
nose-1.3.7-py2 100% |###############################| Time: 0:00:01 139.57 kB/s
numpy-1.11.1-p 100% |###############################| Time: 0:00:18 172.04 kB/s
path.py-8.2.1- 100% |###############################| Time: 0:00:00  85.69 kB/s
psutil-4.3.0-p 100% |###############################| Time: 0:00:02 112.97 kB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00  84.99 kB/s
pycparser-2.14 100% |###############################| Time: 0:00:01  92.40 kB/s
pycrypto-2.6.1 100% |###############################| Time: 0:00:05  86.59 kB/s
pyflakes-1.2.3 100% |###############################| Time: 0:00:03  34.82 kB/s
pygments-2.1.3 100% |###############################| Time: 0:00:05 231.99 kB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00  73.66 kB/s
pytz-2016.4-py 100% |###############################| Time: 0:00:01  89.37 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:02  84.28 kB/s
qtpy-1.0.2-py2 100% |###############################| Time: 0:00:00  53.18 kB/s
requests-2.10. 100% |###############################| Time: 0:00:04 138.77 kB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:02  74.44 kB/s
setuptools-23. 100% |###############################| Time: 0:00:05 120.18 kB/s
simplegeneric- 100% |###############################| Time: 0:00:00   1.33 MB/s
sqlalchemy-1.0 100% |###############################| Time: 0:00:09 136.94 kB/s
toolz-0.8.0-py 100% |###############################| Time: 0:00:01  53.17 kB/s
werkzeug-0.11. 100% |###############################| Time: 0:00:01 220.47 kB/s
xlrd-1.0.0-py2 100% |###############################| Time: 0:00:02  65.64 kB/s
xlsxwriter-0.9 100% |###############################| Time: 0:00:01 102.02 kB/s
xlwt-1.1.2-py2 100% |###############################| Time: 0:00:02  65.49 kB/s
astropy-1.2.1- 100% |###############################| Time: 0:00:30 202.75 kB/s
babel-2.3.3-py 100% |###############################| Time: 0:00:42 123.00 kB/s
bottleneck-1.1 100% |###############################| Time: 0:00:01 121.05 kB/s
cffi-1.6.0-py2 100% |###############################| Time: 0:00:01 105.74 kB/s
clyent-1.2.2-p 100% |###############################| Time: 0:00:00  68.15 kB/s
conda-4.1.11-p 100% |###############################| Time: 0:00:02  94.56 kB/s
configparser-3 100% |###############################| Time: 0:00:00  48.55 kB/s
cytoolz-0.8.0- 100% |###############################| Time: 0:00:03  75.77 kB/s
freetype-2.5.5 100% |###############################| Time: 0:00:08  78.88 kB/s
get_terminal_s 100% |###############################| Time: 0:00:00   2.22 MB/s
gevent-1.1.1-p 100% |###############################| Time: 0:00:02 179.98 kB/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:08  70.86 kB/s
jinja2-2.8-py2 100% |###############################| Time: 0:00:02  95.77 kB/s
jsonschema-2.5 100% |###############################| Time: 0:00:02  46.60 kB/s
llvmlite-0.11. 100% |###############################| Time: 0:00:39 151.35 kB/s
numexpr-2.6.0- 100% |###############################| Time: 0:00:01 122.62 kB/s
partd-0.3.4-py 100% |###############################| Time: 0:00:00  88.08 kB/s
pathlib2-2.1.0 100% |###############################| Time: 0:00:00  42.77 kB/s
patsy-0.4.1-py 100% |###############################| Time: 0:00:01 182.56 kB/s
pip-8.1.2-py27 100% |###############################| Time: 0:00:16  97.08 kB/s
pycurl-7.43.0- 100% |###############################| Time: 0:00:01  68.29 kB/s
pytest-2.9.2-p 100% |###############################| Time: 0:00:02 119.77 kB/s
python-dateuti 100% |###############################| Time: 0:00:03  61.75 kB/s
qt-4.8.7-vc9_8 100% |###############################| Time: 0:06:01 149.04 kB/s
scipy-0.17.1-n 100% |###############################| Time: 0:00:57 208.55 kB/s
ssl_match_host 100% |###############################| Time: 0:00:00 318.35 kB/s
xlwings-0.7.2- 100% |###############################| Time: 0:00:03 192.58 kB/s
cryptography-1 100% |###############################| Time: 0:00:02 131.37 kB/s
datashape-0.5. 100% |###############################| Time: 0:00:00 102.93 kB/s
entrypoints-0. 100% |###############################| Time: 0:00:00   1.99 MB/s
flask-0.11.1-p 100% |###############################| Time: 0:00:01 111.50 kB/s
numba-0.26.0-n 100% |###############################| Time: 0:00:11 160.19 kB/s
pandas-0.18.1- 100% |###############################| Time: 0:00:45 160.24 kB/s
pickleshare-0. 100% |###############################| Time: 0:00:00   4.45 MB/s
pillow-3.2.0-p 100% |###############################| Time: 0:00:06 157.17 kB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:25 156.79 kB/s
pytables-3.2.2 100% |###############################| Time: 0:00:08 178.62 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:14 254.20 kB/s
sphinx-1.4.1-p 100% |###############################| Time: 0:00:09 136.84 kB/s
tornado-4.3-py 100% |###############################| Time: 0:00:04 116.86 kB/s
anaconda-navig 100% |###############################| Time: 0:00:10 129.45 kB/s
bokeh-0.12.0-p 100% |###############################| Time: 0:00:15 223.89 kB/s
ipython-4.2.0- 100% |###############################| Time: 0:00:08 116.71 kB/s
jupyter_client 100% |###############################| Time: 0:00:01  98.08 kB/s
matplotlib-1.5 100% |###############################| Time: 0:00:36 174.70 kB/s
odo-0.5.0-py27 100% |###############################| Time: 0:00:03  55.22 kB/s
pyopenssl-0.16 100% |###############################| Time: 0:00:00  95.79 kB/s
sockjs-tornado 100% |###############################| Time: 0:00:00  59.64 kB/s
statsmodels-0. 100% |###############################| Time: 0:00:35 134.79 kB/s
dask-0.10.0-py 100% |###############################| Time: 0:00:03 161.70 kB/s
nbconvert-4.2. 100% |###############################| Time: 0:00:05  61.64 kB/s
scikit-image-0 100% |###############################| Time: 0:01:46 173.79 kB/s
blaze-0.10.1-p 100% |###############################| Time: 0:00:06 103.49 kB/s
notebook-4.2.1 100% |###############################| Time: 0:00:34 155.48 kB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:01 108.09 kB/s
spyder-2.3.9-p 100% |###############################| Time: 0:00:24  88.64 kB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00   2.67 MB/s
nb_anacondaclo 100% |###############################| Time: 0:00:00  70.60 kB/s
nb_conda_kerne 100% |###############################| Time: 0:00:00  67.42 kB/s
nb_conda-1.1.0 100% |###############################| Time: 0:00:00 102.70 kB/s
_nb_ext_conf-0 100% |###############################| Time: 0:00:00 455.98 kB/s
nbpresent-3.0. 100% |###############################| Time: 0:00:03 151.80 kB/s
anaconda-4.1.1 100% |###############################| Time: 0:00:00  52.42 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  45%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\kolesov\Anaconda2\Scripts\conda-script.py", line 5, in <module>
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 64, in execute
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\instructions.py", line 96, in UNLINK_CMD
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\install.py", line 723, in unlink
  File "C:\Users\kolesov\Anaconda2\lib\site-packages\conda\install.py", line 596, in move_path_to_trash
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 11: ordinal not in range(128)

[Anaconda2] C:\Users\kolesov>conda info

Current conda install:

             platform : win-64
conda command version : 1.8.2
       root directory : C:\Anaconda
       default prefix : C:\Users\kolesov\Anaconda2
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None

**Comment by kalefranz** [comment]
Conda is at version 4.1.11 now. Please update if you can :)
