### ISSUE TITLE
conda clone fails when repo url changes

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#3267]
Conda has new strict channel urls for each installed package but this functionality breaks when running your own Anaconda Repo and then migrating to a new hostname/server.  All of the old packages have explicit urls to a hostname that no longer exists and it fails to perform the clone operation even though all of those packages exist in the new server at its new hostname.

We need to handle this better and if we cannot connect to the old url, then check again using the channels configured in `.condarc` for the same package.  Currently it just fails and will not allow you to clone old environments.

```
conda create --name newenv --clone oldenv
Source: /user/anaconda/envs/oldenv
Destination: /user/anaconda/envs/newenv
Packages: 175
Files: 2278
Fetching package metadata ...Could not connect to http://oldhostname:port/pkgs/linux-64/
.Could not connect to http://oldhostname:port/pkgs/noarch/
.Could not connect to http://oldhostname:port/conda/t/$TOKEN/channame/linux-64/
.Could not connect to http://oldhostname:port/conda/t/$TOKEN/channame/noarch/

```

**Comment by HugoTian** [comment]
May I get your "conda info" output ?

Thanks

**Comment by JeremyEnns** [comment]
Also current workaround is to downgrade back to conda 4.0.9 

```
> conda info
Current conda install:
platform : linux-64
conda version : 4.1.11
conda-env version : 2.5.0
conda-build version : 1.21.7
python version : 2.7.12.final.0
requests version : 2.9.1
root environment : /user/anaconda/ (writable)
default environment : /user/anaconda/envs/default
envs directories : /user/anaconda/envs
package cache : /user/anaconda/pkgs
channel URLs : http://anaconda:8080/conda/anaconda/linux-64/
http://anaconda:8080/conda/anaconda/noarch/
http://anaconda:8080/conda/channame/linux-64/
http://anaconda:8080/conda/channame/noarch/
http://anaconda:8080/conda/conda-forge/linux-64/
http://anaconda:8080/conda/conda-forge/noarch/
config file : /home/username/.condarc
offline mode : False
is foreign system : False
```
(modified the usernames/channel names to protect the innocent)

**Comment by kalefranz** [comment]
@HugoTian we should be able to start by writing an integration test for this. Basically duplicate one of the tests for clone, but then switch out one of the channel urls. 

There are at least two mapping we could probably use here. 
* conda.anaconda.org/anaconda is a mirror of repo.continuum.io/pkgs/free
* the channel `conda-forge` should be identical to the channel `conda-forge/label/main`

**Comment by kalefranz** [comment]
There are also at least two different configuration parameters in play here. `channel_alias` and `default_urls` (I think that's it, on my phone right now) could both affect this.

**Comment by kalefranz** [comment]
@HugoTian it'll likely be easier to fix this in 4.2 with the Channel model object. I think we could skip the fix in 4.1 given the complexity.

**Comment by JeremyEnns** [comment]
In the above scenario both servers were identical mirrors, but the host name changed due to moving to new hardware.  They migrated the Anaconda Repo from serverA to serverB now everything is broken when it tries to connect to serverA and it no longer exists.  Ideally in this situation, it should just try the explicit historical url for the package, if it fails to connect or gets a timeout then try the channels configured in the `.condarc` and continue and update the url.

This situation may also come into play when a developer has projects using packages from an internal repo and are trying to work from home.  They would be unable to make any changes to their environments if they can't connect to the internal hostname from their office.

**Comment by kalefranz** [comment]
The two configuration parameters we need to test and play with are `default_channels` and `channel_alias`.
