### ISSUE TITLE
error creating new environment through conda package manager

### ISSUE THREAD

**Issue by anujshah1003** [conda/conda#3276]
I am unable to create a new environment or install any package through conda package through anaconda prompt. i have attached a picture of one error
![conda-error](https://cloud.githubusercontent.com/assets/20814689/17579441/347872fe-5fb3-11e6-87cc-4881aa3e7cf3.PNG)

**Comment by HugoTian** [comment]
Please show me the output of conda info ?

From the output, it seems that there are 2 problem.

1. Cannot connect to repo.continuum.io.
Please retry, I will double check to make sure the server is working correctly

2. When you do the rename, access is denied.
Please refer to #3271 . If you have virus scanner running, please disable that and retry. 
This seems to be a common problem on Win, we will come up with better solution in future

**Comment by anujshah1003** [comment]
The output of conda info
![conda_info](https://cloud.githubusercontent.com/assets/20814689/17612384/e2e7e58e-606e-11e6-864d-31b7ed3f29f0.PNG)

**Comment by anujshah1003** [comment]
The Output of conda info is attached

**Comment by HugoTian** [comment]
Please retry If sill not working, please disable virus scanner and retry.

Feel free to reopen this issue and @ me 

Thanks
