### ISSUE TITLE
Conda always tries to change MKL from our build to the defaults channel

### ISSUE THREAD

**Issue by tomashek** [conda/conda#3279]
We're having what looks like incorrect conda updating behavior. Conda seems to always want to change the mkl package from our version to the package in defaults when trying to install or update any _other_ package. But issuing "conda update mkl" or including mkl in the command line with the desired package (such as "conda install pycparser mkl" instead of "conda install pycparser") leaves our mkl package alone. Our package lives on anaconda.org in our "test" label, which is listed first in our channels, and thus should be a higher priority than the 'defaults' channel version.

MKL is not listed as a dependency of pycparser (pycparser only lists python 3.5\* as a dependency).

Our setup (many packages removed from package list for brevity):

```
(root) ipyprod27pc26$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /localdisk/work/tmtomash/ipyprod27pc26  (writable)
  default environment : /localdisk/work/tmtomash/ipyprod27pc26
     envs directories : /localdisk/work/tmtomash/ipyprod27pc26/envs
        package cache : /localdisk/work/tmtomash/ipyprod27pc26/pkgs
         channel URLs : https://conda.anaconda.org/intel/label/test/linux-64/
                        https://conda.anaconda.org/intel/label/test/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /nfs/site/home/tmtomash/.condarc
         offline mode : False
    is foreign system : False

(root) ipyprod27pc26$ conda list
# packages in environment at /localdisk/work/tmtomash/ipyprod27pc26:
#
....
conda                     4.1.11                   py27_0    intel/label/test
conda-env                 2.5.2              py27_intel_0  [intel]  intel/label/test
....
mistune                   0.7.2              py27_intel_3  [intel]  intel/label/test
mkl                       2017.0.0                intel_3  [intel]  intel/label/test
mpi4py                    2.0.0              py27_intel_3  [intel]  intel/label/test
....
python                    2.7.12                  intel_3  [intel]  intel/label/test
....
zeromq                    4.1.4                   intel_3  [intel]  intel/label/test
zlib                      1.2.8                   intel_3  [intel]  intel/label/test
(root) ipyprod27pc26$ conda install pycparser
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /localdisk/work/tmtomash/ipyprod27pc26:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.3                 |                0       122.1 MB  defaults
    pycparser-2.14             |           py27_1         148 KB  defaults
    ------------------------------------------------------------
                                           Total:       122.2 MB

The following NEW packages will be INSTALLED:

    pycparser: 2.14-py27_1      defaults        

The following packages will be DOWNGRADED due to dependency conflicts:

    mkl:       2017.0.0-intel_3 intel/label/test [intel] --> 11.3.3-0 defaults

Proceed ([y]/n)? n

(root) ipyprod27pc26$ conda install pycparser mkl
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /localdisk/work/tmtomash/ipyprod27pc26:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pycparser-2.14             |           py27_1         148 KB  defaults

The following NEW packages will be INSTALLED:

    pycparser: 2.14-py27_1 defaults

Proceed ([y]/n)? n
```

**Comment by mcg1969** [comment]
I wonder if it has to do with the fact that the version numbering schemes are different. I'll be honest---if that's the issue, I don't see an easy way to fix it. Is there a reason you've chosen to deviate from the versioning scheme used by `defaults`?

**Comment by tomashek** [comment]
That's the version number the MKL team is moving to for MKL itself. We need to use what they give us for the version.

**Comment by mcg1969** [comment]
@kalefranz @ilanschnell @csoja just want to point out Todd's last comment here. If Intel is changing MKL's version numbering scheme that poses an interesting problem beyond this issue alone.

Shall we close this issue, though, @tomashek, given that we've found the cause offline?

**Comment by tomashek** [comment]
@mcg1969 , I lost track of this for a few days. I think the prioritization algorithm is still worth examining. We found that the presence of the additional "feature" in our mkl package is what caused it to be preempted by the version in the "defaults" channel. But is that what is supposed to happen? For this case, we were able to remove the new "feature" because it was not needed, but that may not always be the case. I would **not** think that minimizing features should take precedence over channel priority, but it appeared to here.

**Comment by tomashek** [comment]
@mcg1969 any further findings here?

**Comment by mcg1969** [comment]
No, I haven't done any further investigation here. As you indicated, removing the extra feature appeared to solve the problem in this case. Do you have another instance where you're seeing incorrect behavior?

To be clear we need to distinguish between "incorrect" and "undesirable" here. I'm going to be working on the solver again soon but to prioritize the incorrect behaviors first (foremost among them: providing better hints when there are specification conflicts.)

**Comment by jakirkham** [comment]
> I would **not** think that minimizing features should take precedence over channel priority, but it appeared to here.

Completely agree. Have been encountering the exact same behavior recently with conda-forge's `blas` package of late.

Should add I don't recall this always being the behavior of the solver. Would have to go searching to dredge up version numbers, but I do remember that our `blas` and `numpy` use to get higher priority based on channel priority; even though, they used features. In any event, this would make this behavior not only incorrect, but a regression.
