### ISSUE TITLE
Error: HTTPError: 404 Client Error: NOT FOUND for url

### ISSUE THREAD

**Issue by Gabriel-p** [conda/conda#3285]
I'm getting the error:

````
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2
````

when attempting to install the `astroML` package via:

````
$ conda install -c astropy astroml=0.3
````

In the page https://anaconda.org/astropy/astroml the .tar.bz file is located in

    https://anaconda.org/astropy/astroml/0.3/download/linux-64/astroml-0.3-py27_0.tar.bz2

and the command is looking for

    https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2

**Comment by HugoTian** [comment]
Here is output for show astropy/astroml

    Using Anaconda Cloud api site https://api.anaconda.org
    Name:    astroml
    Summary: tools for machine learning and data mining in Astronomy
    Access:  public
    Package Types:  conda
    Versions:
     + 0.2
     + 0.3

    To install this package with conda run:
          conda install --channel https://conda.anaconda.org/astropy astroml

Please try this command, and see whether it works

    conda install --channel https://conda.anaconda.org/astropy astroml

**Comment by Gabriel-p** [comment]
This is what I get with that command:

````
$ conda install --channel https://conda.anaconda.org/astropy astroml
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/gabriel/miniconda2/envs/asteca:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astroml-0.3                |           py27_0         135 KB  astropy

The following NEW packages will be INSTALLED:

    astroml: 0.3-py27_0 astropy

Proceed ([y]/n)? y

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2
````

**Comment by HugoTian** [comment]
Here is the index json of astroml: 0.3-py27_0 astropy

{u'subdir': u'osx-64', u'build_number': 0, u'name': u'astroml', u'license': u'BSD License', u'fn': u'astroml-0.3-py27_0.tar.bz2', u'schannel': u'astropy', u'requires': [], **u'url': u'https://conda.anaconda.org/astropy/osx-64/astroml-0.3-py27_0.tar.bz**2', u'machine': u'x86_64', u'platform': u'osx', u'depends': [u'astropy >=0.2.5', u'matplotlib >=0.99', u'numpy >=1.4', u'python 2.7*', u'python >=2.6|>=3.3', u'scikit-learn >=0.10', u'scipy >=0.7'], u'version': u'0.3', u'build': u'py27_0', u'channel': u'https://conda.anaconda.org/astropy/osx-64', u'binstar': {u'package_id': u'556baebe3273af617f50408e', u'channel': u'main', u'owner_id': u'54ecd3d95e768324e956b7e9'}, u'priority': 0, u'size': 138028, u'arch': u'x86_64', u'operatingsystem': u'darwin', u'target-triplet': u'x86_64-any-darwin', u'md5': u'3c336272dd8d55a5d47d5c59f133bcd8'}

As you can see, the url is https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2.
The index is broken, and I have no idea how to fix this index.

However, you can download the tar ball (from the url), and run "conda install --file your_tar_ball"

**Comment by HugoTian** [comment]
If the tar ball is not working, here is the result of anaconda search -t conda astroml

anaconda search -t conda astroml
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     OpenAstronomy/astroml     |      0.3 | conda           | linux-64, win-32, win-64, osx-64
                                          : tools for machine learning and data mining in Astronomy
     astropy/astroml           |      0.3 | conda           | linux-64, win-32, win-64, osx-64
                                          : tools for machine learning and data mining in Astronomy
     auto/astroml              |      0.2 | conda           | linux-32, osx-64
                                          : tools for machine learning and data mining in Astronomy
     jakevdp/astroML           |      0.1 | conda           | osx-64         
                                          : Machine learning for Astronomy
     srwalker101/astroml       |      0.3 | conda           | linux-64, osx-64
                                          : tools for machine learning and data mining in Astronomy
Found 5 packages

You can download from srwalker101, and see whether it works

**Comment by Gabriel-p** [comment]
Attempting to install from `srwalker101/astroml` needs to downgrade a lot of packages.

You mentioned above that the index is broken. Is this the proper place to report that issue? Because that would seem to be the actual fix here.

**Comment by Gabriel-p** [comment]
I just opened a new issue here: https://github.com/Anaconda-Platform/support/issues/56

I believe that repo is more relevant than this one?

**Comment by csoja** [comment]
Yes - I would agree that is the right place in this case.  Thank you for opening the new issue.  I will close this issue.
