### ISSUE TITLE
Better conflict output

### ISSUE THREAD

**Issue by srossross** [conda/conda#3290]
```
Solving package specifications: .
Error:  Dependency missing in current linux-64 channels: 
  - binstar-server 2.19.4 535 -> jupyter_core 4.1.1 py27_0
```

It would be great if conda errors out to have enough information here to full debug the issue.

Some possible suggestions:
1. Complete path from `binstar-server` to `jupyter_core`
   It would be great if the error results could look somthing like `npm ls`:
   
   ```
   anaconda-server@1.0.0 /Users/sean/Documents/workspace/anaconda.org
   ├─┬ browserify@11.2.0 invalid
   │ ├── assert@1.3.0
   │ ├─┬ browser-pack@5.0.1
   │ │ ├─┬ combine-source-map@0.6.1
   │ │ │ ├── convert-source-map@1.1.3
   │ │ │ ├── inline-source-map@0.5.0
   ```
2. The channels that the packages were pulled from

cc @kalefranz

**Comment by kalefranz** [comment]
To add to @srossross's report, in this case, `jupyter_core` is not a direct dependency of `binstar-server`, but rather a dependency or a dependency (or maybe even more nested).  Sean is specifically asking that the full dependency chain between the two be communicated rather than masking the in-betweens.

**Comment by srossross** [comment]
Here is what I came up with in [Anaconda-Platform/kapsel-install](https://github.com/Anaconda-Platform/kapsel-install) (see the readme)

```
conda-install2 conflict1
+ @sean/conflict1-v0.bz2 (conda)
  ├─ conflict2>=1
  └─ conflict3
+ @sean/conflict3-v0.bz2 (conda)
  └─ conflict4<=1
+ @sean/conflict2-v1.bz2 (conda)
  └─ conflict4>=2
[error] Could not find any suitable version of the package 'conflict4'
(<=1 required by 'conflict3' and >=2 required by 'conflict2')

```

**Comment by kalefranz** [comment]
resolved with https://github.com/conda/conda/pull/3597
