### ISSUE TITLE
per-environment condarc

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3294]
I've just realized that I think it would be helpful to have the option of per-environment `.condarc`.  At least the piece I think would be really helpful: the ability to attach certain package sources (channels) on a per-environment basis, so when I do:

```
source activate foo
conda install bar
```

then environment `foo` can have some specific channels `ping`, `pong`, and `zap` that are automatically searched without need to add `-c ping -c pong -c zap` to each command nor modify my personal `~/.condarc` to include these channels universally (for all `conda` commands).

I think this is somewhat like `git`'s behavior: there are global (per-user) "defaults" while also allowing per-repo custom configurations.

**Comment by kalefranz** [comment]
You apparently haven't been using 4.2. It's already done!

**Comment by ijstokes** [comment]
@fperez there you go, already done!

**Comment by ijstokes** [comment]
@kalefranz OK, I have 4.2 installed by doing `conda install -c conda-canary conda` but `conda -h` and `conda config -h` don't tell me how to use this feature.  Any tips/pointers?

**Comment by kalefranz** [comment]
`conda config -h` will show three new flags. `--show`, `--show-sources`, and `--validate`

Put a `.condarc` file in the root directory of your activated env. `--show-sources` will show its being picked up, and the values within should affect the compiled configuration given by `--show`

**Comment by fperez** [comment]
Glad to see this, thanks @ijstokes for the ping!! But I'd suggest that, given this feature now exists, it might be worth documenting it :) I see no mention of the word "channel" at all in the [current docs on managing envs](http://conda.pydata.org/docs/using/envs.html), and the [config docs](http://conda.pydata.org/docs/config.html?highlight=channel#the-conda-configuration-file-condarc), as best I can tell, don't explain this either (they only talk of a master condarc file for the root env).

In any case, thanks, this is great to have!!

**Comment by BrenBarn** [comment]
This feature is indeed very useful, but it still seems it's not mentioned in the main docs at all.
