### ISSUE TITLE
conda install -c draikes scapy=2.3.2   on  python 3.5

### ISSUE THREAD

**Issue by netqwe** [conda/conda#3295]
conda install -c draikes scapy=2.3.2
Lead to :
The following specification were found to be in conflict:
 -python3.5*
 -scapy 2.3.2*

What can be done about that ?

Thanks in advance

**Comment by HugoTian** [comment]
Can you show me the output of conda info ?

**Comment by HugoTian** [comment]
Here is some info about metadata of scapy 2.3.2 

    scapy-2.3.2-py27_0.tar.bz2:
    "machine":"x86_64","platform":"win","depends":["python 2.7*"],"
     version":"2.3.2","build":"py27_0","
     md5":"3b470dee37f6a5cb461aab89a3967c50"

It seems scapy depends on python2.7 and your python version is 3.5. There is a solution using conda environment, try 

    conda create -n "env_name" python=2.7

to create a python 2.7 environment, and install scapy in that environment.

**Comment by netqwe** [comment]
Thanks , i installed it via the conda environment but scapy cannot be imported :
ImportError: No module named 'scapy'

**Comment by HugoTian** [comment]
Do you activate the environment , and then install in that environment ?

**Comment by netqwe** [comment]
Yes, the installation was properly
But scapy does not appear on conda list

**Comment by HugoTian** [comment]
That's wired. please give me the output of "conda list -n your_env_name" ?

Thanks

**Comment by netqwe** [comment]
Scapy appearing at:
conda list -n env_name

Do you mean that the module can be used only on the 2.7 environment ?
Is no any possibility to install it on the 3.5 environment ?

**Comment by HugoTian** [comment]
Yes, it can be used only in python 2.7 environment.

That package depends on python2.7 according to its index, and I do not think it works with py35

**Comment by netqwe** [comment]
Ok , last thing , how the switch between the environments can be done in the 'Spyder' (Editor and Console) ?

**Comment by HugoTian** [comment]
I just test on my machine. 

First, activate the python2.7 environment. Then start spyder using command line , and the spyder will connect to python2.7

**Comment by netqwe** [comment]
I tried :
activate env_name
and then :
spyder

but I still get the 3.5 Spyder

**Comment by netqwe** [comment]
Ok , spyder installation should be done before :
conda install -n env_name spyder

Thanks for the answers
