### ISSUE TITLE
Conda env won't create when pip-only dependencies listed

### ISSUE THREAD

**Issue by gallamine** [conda/conda#3300]
Running `conda 4.1.11`
Created new directory and added `environment.yml` file containing:

```
name: conda-test
dependencies:
- pip:
    - urllib3
```

From command line run `conda env create` and get the following error:

```
Error: too few arguments, must supply command line package specs or --file
```

I get the same error when i do `conda env create --file environment.yml`.

To fix the problem I change the `environment.yml` file to be:

```
name: conda-test
dependencies:
- pip
- pip:
    - urllib3
```

`conda env create` now works and I can create and activate the environment.

Is this expected behavior?

**Comment by HugoTian** [comment]
Agree, this should be fixed.

Simply removing this [line](https://github.com/conda/conda-env/blob/develop/conda_env/installers/conda.py#L9) will be fine.

In conda 4.2, with the empty-environment feature, we no long check empty specification,

**Comment by HugoTian** [comment]
Please refer to PR #3288 . Already merged in master branch, and will be fixed in new conda release.

Feel free to reopen this and @ me
