### ISSUE TITLE
Import env with packages from non-default channels

### ISSUE THREAD

**Issue by KonstV** [conda/conda#3305]
Actually I doesn't sure this is bug, but I couldn't find explanation in docs. I created an environment with package from non-default channel (see attachment). And when I trying to import this env on another machine with
```
conda env create -f simple.yml
```
I got following error:
```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - menpo::opencv 2.4.11 nppy27_0
```
`conda info` output
```
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.6
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/konstantin/frameworks/anaconda2  (writable)
  default environment : /home/konstantin/frameworks/anaconda2
     envs directories : /home/konstantin/frameworks/anaconda2/envs
        package cache : /home/konstantin/frameworks/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```
[simple.yml.zip](https://github.com/conda/conda/files/420961/simple.yml.zip)

**Comment by HugoTian** [comment]
We will have a tmp fix in 4.2, please refer to PR #3286 , and the changes in conda_env/installers/conda.py

Generally, we need to parse the dependencies into channel and package, and then give all the info to conda to install correctly

**Comment by KonstV** [comment]
Got it, thank you for reply!

**Comment by HugoTian** [comment]
But it is just a tmp fix. It cannot solve the channel issue. 

For example, if a package is available on 2 channels, A and B. Both A and B are in config file, and your .yml file show A::package, and conda may end up install B::package.

We will have better solution later
