### ISSUE TITLE
How can I install libsvm on windows-64 ?

### ISSUE THREAD

**Issue by netqwe** [conda/conda#3309]
pip install libsvm
Lead to:
'Could not find a version that satisfies the requirement libsvm'

Also , only linux-64 and osx-64 installation packages in the anaconda cloud.

Thanks in advance

**Comment by netqwe** [comment]
Ok , I managed to find and install
conda install -c conda-forge libsvm=3.21 
From:
https://anaconda.org/search

But libsvm cannot be imported

**Comment by HugoTian** [comment]
The simple answer is, libsvm is not a python package, and you cannot import it directly from python. But you can use ctypes to import it into python 

Here is the info about this package:

    Library/bin/svm-predict.exe
    Library/bin/svm-scale.exe
    Library/bin/svm-toy.exe
    Library/bin/svm-train.exe
    Library/include/svm.h
    Library/lib/libsvm.dll

As can be seen, there is a dll library created in Library/lib, then you can use ctypes to call function in that dll library. For more details, please see [here ]
 (http://stackoverflow.com/questions/5253854/python-import-dll)

Or you can build it from github source, and please refer to [here](https://github.com/cjlin1/libsvm/tree/master/python) 

Moreover, conda libsvm package let you run something like svm-train, svm-scale from command line according to those .exe files
