### ISSUE TITLE
vlfeat cannot be imported 

### ISSUE THREAD

**Issue by netqwe** [conda/conda#3311]
vlfeat cannot be imported by spider editor/console ,
although installed properly via:
conda install -c menpo vlfeat=0.9.20

import vlfeat 
Lead to:
'ImportError: No module named vlfeat'

Is it related to vc9_1 build instead py27_0/py27_1/py27_2 ?

![12345](https://cloud.githubusercontent.com/assets/21021700/17737859/aa051642-6497-11e6-9c33-ff2e492ccc63.png)

Thanks in advance

**Comment by HugoTian** [comment]
Basically, the answer is that vlfeat installed by conda is not a python package, please refer to answer on issue #3309.

There is a Library/bin/vl.dll file in your anaconda home, and you can import function from dll using ctypes

**Comment by alexscluk** [comment]
try it 

https://stackoverflow.com/questions/34964090/vlfeat-for-ipython

**Comment by alexscluk** [comment]
actually i still don't understand how to do it. here is the link i tried to follow: https://stackoverflow.com/questions/5253854/python-import-dll

Anyone can give me some hints?
