### ISSUE TITLE
can't create python 3 environment with >= specification

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3312]
I thought this would be a good idea to create the latest python 3 environment 

conda create -n py3 python>=3

but it seems to hang. If I am more specific, python=3.5* then it gets going. This is with conda canary conda 4.2.3

**Comment by HugoTian** [comment]
I think the terminal think the > as a redirect sign, and it will create a " =3 " file.

I will double check the performance, and seems conda 4.0, 4.1 both cannot handle this case

**Comment by HugoTian** [comment]
I just checked,  conda create -n py35 python\>=3 will work

Thanks

**Comment by davidslac** [comment]
Ah! Now I know why I was deleting these funny files name =1 and =2 that were lying around, thanks!

best,

David Schneider
SLAC/LCLS
________________________________________
