### ISSUE TITLE
multiuser install - "text file is busy" when activating environment

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3315]
Today, from a user account, I did

```
$ source activate anarel-1.0.0
```

and got

```
-bash: /central-install/miniconda2/bin/conda: /central-install/miniconda2/bin/python: bad interpreter: No such file or directory
```

I did it a second time and it worked.

we see this kind of thing on our filesystem when we do thinks like modify then install a file and immediately run the file from the new location, sleeping a second in between those steps fixes it. I think it is a problem with our nfs filesystem, but I was surprised to see it when I activate an environment. I know you guys are looking at multi-user conda, so wanted to raise the issue - to make conda robust on different filesystems, keep things like source activate as lightweight as possible? (Or tell us to fix our filesystem :)

**Comment by davidslac** [comment]
I am trying to activate an environment but it hangs. That is just doing

source activate envir

where envir is provided in the central install, hangs. I would think that activate could just be a simple script to change the path and run other scripts, instead it is clearly some heavy weight thing.

**Comment by kalefranz** [comment]
Multi-user installs should be good to go as of conda 4.3, and especially 4.3.13.

**Comment by kalefranz** [comment]
Oh and the activate race condition should be solved also.  Even for conda 4.2 I think.
