### ISSUE TITLE
Don't fail conda install when Windows menu items fail to install

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#3317]
In the case when a user is installing conda packages on Windows and the packages attempt to create Window menu items but the user does not have sufficient privileges to create the item, do not fail the install but instead only fail to install the menu items.

Currently when menu item creation fails due to insufficient privileges the entire conda package install will fail.  This is often not necessary or desirable.  A warning is sufficient.  By continuing the install instead of failing to install the packages the user can still install and use the packages from notebooks and the command line even if the menu items are not present.

A good example, create a new environment with ipython in it.  The user will be prompted for credentials to create the menu items, press Cancel and the entire env creation will fail.  It would be better to create the env without the menu items.

**Comment by kalefranz** [comment]
Fixed in conda 4.3.
