### ISSUE TITLE
Error switching `openssl` installs

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3319]
We have observed a strange error when trying to switch from the `defaults` package of `openssl` to the `conda-forge` package of `openssl`. More details along with reproducing cases and logs can be see in issue ( https://github.com/conda-forge/openssl-feedstock/issues/3 ). It seems like maybe(?) it is using the cache incorrectly and misattributing it to a package from a different channel. It is unclear whether the latter is part of the problem that results in the installation failure or another related problem.

cc @msarahan @asmeurer @pelson

**Comment by asmeurer** [comment]
If I create a test environment with the conda-forge openssl and then manually copy and run the post link script from `defaults`, I get the error (with a different garbled string):

```
$ conda create -n test openssl
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .................
Solving package specifications: ..........

Package plan for installation in environment /Users/aaronmeurer/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.2-3 conda-forge
    openssl:         1.0.2h-2   conda-forge

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
$ conda create -n teest2 -c defaults --override-channels openssl
Fetching package metadata .......
Solving package specifications: ..........
Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment /Users/aaronmeurer/anaconda3/envs/teest2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2h             |                2         3.0 MB  defaults

The following NEW packages will be INSTALLED:

    openssl: 1.0.2h-2 defaults

Pruning fetched packages from the cache ...
Fetching packages ...
openssl-1.0.2h 100% |##############################################################################################################| Time: 0:00:06 501.66 kB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate teest2
#
# To deactivate this environment, use:
# $ source deactivate
#
$ cp ~/anaconda/pkgs/openssl-1.0.2h-2/bin/.openssl-libcrypto-fix ~/anaconda/envs/test/bin/
$ ~/anaconda/envs/test/bin/.openssl-libcrypto-fix /Users/aaronmeurer/anaconda/envs/test/
Error: old string incorrect `H�OH��t	H�I�	]�I�'
```

The conda-forge package doesn't have a post-link script. So I'm pretty confident that this is what is happening, that the defaults post-link script is being run against the conda-forge package.

**Comment by kalefranz** [comment]
Guessing this is a pretty fundamental bug. Something going on with package cache, clobbering installs, no uninstall instruction when switching channels, etc

also CC @mcg1969

**Comment by pelson** [comment]
Amazed that this hasn't come up before. I guess as soon as we introduced channel priority this became more of a thing, but I assume it has always been there...

```
$ ls *            
a:
meta.yaml

a_prime:
meta.yaml
```

```
$ cat a/meta.yaml 
package:
  name: a
  version: 1

build:
  script: echo "solitary a" > $PREFIX/contents.txt

test:
  commands:
    - cat $PREFIX/contents.txt
```

```
$ cat a_prime/meta.yaml 
package:
  name: a
  version: 1

build:
  script: echo "a prime" > $PREFIX/contents.txt

test:
  commands:
    - cat $PREFIX/contents.txt
```


```
$ conda build a
BUILD START: a-1-0
...
+ echo 'solitary a'
number of files: 1
Fixing permissions
Fixing permissions
BUILD END: a-1-0
TEST START: a-1-0
...
Solving package specifications: ..........

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    a-1                        |                0          743 B  local

The following NEW packages will be INSTALLED:

    a: 1-0 local
...
+ cat /data/local/itpe/miniconda/envs/_test/contents.txt
solitary a
TEST END: a-1-0
```

```
$ conda build a_prime 
Removing old build environment
BUILD START: a-1-0
...
+ echo 'a prime'
number of files: 1
Fixing permissions
Fixing permissions
BUILD END: a-1-0
TEST START: a-1-0
...
The following NEW packages will be INSTALLED:

    a: 1-0 local

Linking packages ...
...
+ cat $PREFIX/contents.txt
solitary a    ***************** SHOULD READ " a prime " *********************
TEST END: a-1-0
```

Clearly the problem is that we aren't storing *where* a package in the cache has come from, although giving conda the ability to do so shouldn't be too hard if it inspects the available metadata rather than assuming the package cache has a particular naming convention.

**Comment by asmeurer** [comment]
conda ought to invalidate the cache if the tarball md5 isn't the same. I seem to remember it doing this before (back when I worked on conda). I could be wrong, though (it wouldn't be the first time I've misremembered some conda behavior).

**Comment by kalefranz** [comment]
CC @mcg1969 FYI

**Comment by mcg1969** [comment]
I don't think md5 checking is always invoked. However, if the package cache is supposed to be keeping track of which channel the cached tarball came from, so that if a different package from a different channel comes in, it knows to re-fetch and overwrite.

**Comment by asmeurer** [comment]
Given how easy it is to re-upload a package with the same name, wouldn't it be better to just use the hash as an invalidation check?

**Comment by frol** [comment]
Upgrading Conda from 4.2.9 to 4.2.11 solved the issue for me.
