### ISSUE TITLE
install error: specifications in conflict

### ISSUE THREAD

**Issue by fdongyu** [conda/conda#3324]
I was using conda to install a package called stomel (conda install stomel). I did add the correct channel to .condarc.
The error showed that The following specifications were found to be in conflict:
   -stomel
I know this kind of error would be normal when using conda to install package. But should there be two or more packages that are in conflict? Besides, I never install stomel before. All I need to find is which one is in conflict with the stomel package.
I would really appreciate any answers. Thank you in advance. Attached is the error message.
![error](https://cloud.githubusercontent.com/assets/10620053/17814730/d0776e1e-65f6-11e6-8f58-32d5f5c41373.png)

**Comment by HugoTian** [comment]
Can you show me the output of conda info stomel ?

**Comment by fdongyu** [comment]
Sure! And here is the channel info you may need: https://conda.binstar.org/rustychris

stomel 0.1.1 np18py27_2
-----------------------
file name   : https://conda.binstar.org/rustychris::stomel-0.1.1-np18py27_2.tar.bz2
name        : stomel
version     : 0.1.1
build number: 2
build string: np18py27_2
channel     : https://conda.binstar.org/rustychris/linux-64
size        : 364 KB
arch        : x86_64
binstar     : {u'package_id': u'5384e8b3e1dad12e7a62a14b', u'channel': u'main', u'owner_id': u'53349002e1dad16b4af78f66'}
fn          : stomel-0.1.1-np18py27_2.tar.bz2
license     : GPLv2
machine     : x86_64
md5         : 08298e13f414e98d0fd52b56ed522fb6
operatingsystem: linux
platform    : linux
priority    : 2
schannel    : https://conda.binstar.org/rustychris
target-triplet: x86_64-any-linux
url         : https://conda.binstar.org/rustychris/linux-64/stomel-0.1.1-np18py27_2.tar.bz2
dependencies:
    gdal
    matplotlib
    numpy 1.8*
    python 2.7*
    python-cgal-bindings
    rtree
    scipy
    shapely

**Comment by HugoTian** [comment]
Basically, conda is not good at telling how to fix a conflict.

My suggestion will be creating a new pthon2.7 environment, and install stomel in that environment

Something like:

     conda create -n stomel_env python=2
     source activate stomel_env
     conda install stomel

**Comment by fdongyu** [comment]
Thanks a lot! This solves my problem perfectly. 

Does that mean I create a new environment and install everything in that environment including Python? And this new environment will not affect everything in my computer if I do "source deactivate"?
I am just curious about this. My issue is well resolved. Thank you!

**Comment by HugoTian** [comment]
Yes, you have a new environment that is different and independent from your root environment(The default environment). Doing source deactivate will not affect your root environment.

**Comment by damcas** [comment]
Hi, I had the same problem installing Python 3.6. I created a new environment and installed python on that one and it worked. If I want to use the Spyder version I got when I installed the Anaconda with the 2.7 python but now with the new Python 3.5, do I have to change something else, activate the new environment or does it upgrade on Spyder automatically?

Thanks a lot!
