### ISSUE TITLE
Resolve for newest package version when multiple channels are provided

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda#3331]
User request:

When specifying more than one repo channel for a package conda does not grab the latest version. Conda does not concatenate the repodata.json between repos before it finds the package and will resolve to the highest version of the package it first encounters.

Example:
repo1 has ipython 3.2.1
repo2 has ipython 5.1.0

```
conda install --override-channels -c http://repo1url -c http://repo2url ipython
```

If there is a need for a user to get packages from 2 repos it will not get the latest as it resolves ipython on repo1. Is it possible to add a feature where conda can combine the repodata.json to resolve which version is highest and grab the package from that repo?

**Comment by kalefranz** [comment]
`conda config --set channel_priority false` should get you part of the way.  We also have finer-grained control of associating packages with channels on the conda roadmap.  Do those two things cover this issue?
