### ISSUE TITLE
URLs with :: are OK and should not raise assertion errors

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3332]
For conda-build's perl skeleton generator, we can end up with URLs like:

http://api.metacpan.org/v0/module/Test::More

Unfortunately, conda prevents us from actually using those URLs:

```
  File "/Users/msarahan/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 354, in download
    assert "::" not in str(url), url
AssertionError: http://api.metacpan.org/v0/module/Test::More
```

Please partially revert https://github.com/conda/conda/commit/39605e01ccd05b5af5ebeceeacaafe652f4b32e4

**Comment by HugoTian** [comment]
I believe I add this assertion, and I think it is fine to revert back or change it in a new PR.
