### ISSUE TITLE
features using wrong datatype: scalar string instead of list?

### ISSUE THREAD

**Issue by tomashek** [conda/conda#3341]
I have not had the chance to see if this is an actual bug, but it looks very suspicious so I wanted to report it.

Features are represented as a list in meta.yaml:

```
build:
    features:
        - intel
        - vc9
```

..but they end up in the index.json metadata file as a scalar string. Dependencies are retained as a list in the json:

```
"depends": [
    "intelpython",
    "vc"
  ],
  "features": "intel vc9",
```

I haven't dug into the code that uses "features" to see if this is a real problem, but if they are to be treated as a list, I would think they would simply be kept as a list.

**Comment by kalefranz** [comment]
Completely agree that this was an unfortunate design decision.  Really too late now to change it though.
