### ISSUE TITLE
Cannot remove env

### ISSUE THREAD

**Issue by galleon** [conda/conda#3344]
toggy:envs tog$ conda env remove -n for-ora-connect
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/tog/miniconda2/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/tog/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/tog/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/tog/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'
toggy:envs tog$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.1
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/tog/miniconda2  (writable)
  default environment : /Users/tog/miniconda2
     envs directories : /Users/tog/miniconda2/envs
        package cache : /Users/tog/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by HugoTian** [comment]
Conda env is broken for 4.1, you can use following command to remove a environment

    conda remove -n env_name --all

or download new version of conda and conda-env using 

    conda install -c conda-canary conda=4.2.3

**Comment by galleon** [comment]
Thanks. It worked.
