### ISSUE TITLE
conda.api.get_index not using the platform kwarg

### ISSUE THREAD

**Issue by pelson** [conda/conda#3348]
In tracking down a particularly fiddly bug with conda-smithy (https://github.com/conda-forge/conda-smithy/pull/274) I noticed that `conda.api.get_index` is no longer using the platform kwarg - it is now exclusively coming from `conda.config.subdir`. That is fine, but I just wanted to highlight the issue, and raise awareness of the value of being able to get an index for any platform (in testing, and in resolving how an environment should look).

**Comment by jakirkham** [comment]
Is this still the case in newer `conda`'s?

**Comment by kalefranz** [comment]
I'm not sure, but I'm finding out now.

**Comment by kalefranz** [comment]
If not, it would be nice to fix along with https://github.com/conda/conda/pull/4094 and get into 4.3.1 that I'm shipping tomorrow in canary.

**Comment by kalefranz** [comment]
Speaking of conda-smithy, you should be aware of the 4.3.0 feature release change log.
https://github.com/conda/conda/blob/4.3.0/CHANGELOG.md

Specifically

> * **Python API Module**: An oft requested feature is the ability to use conda as a python library,
  obviating the need to "shell out" to another python process. Conda 4.3 includes a
  `conda.cli.python_api` module that facilitates this use case. While we maintain the user-facing
  command-line interface, conda commands can be executed in-process. There is also a
  `conda.exports` module to facilitate longer-term usage of conda as a library across conda
  conda releases.  However, conda's python code *is* considered internal and private, subject
  to change at any time across releases. At the moment, conda will not install itself into
  environments other than its original install environment. (#4028)

**Comment by jakirkham** [comment]
Setting the `platform` argument does seem to work FWICT. However, it seems like the `Context` doesn't provide us any way to override the `platform`/`subdir` any more.

xref: https://github.com/conda/conda/blob/4.2.13/conda/base/context.py#L163-L173
xref: https://github.com/conda/conda/blob/4.3.0/conda/base/context.py#L206-L216

**Comment by kalefranz** [comment]
I'm not happy right now with the split between `subdir` (https://github.com/conda/conda/blob/4.2.13/conda/base/constants.py#L73-L80) and `Platform` + `Arch` (https://github.com/conda/conda/blob/4.2.13/conda/base/constants.py#L18-L45) right now.  Yes also relevant is https://github.com/conda/conda/blob/4.2.13/conda/base/context.py#L155-L173.

But that context object is incredibly configurable.  If your using conda programmatically, either in-process or shelling out to it, I think the easiest way is to use environment variables.  Any of the growing list of config parameters (https://github.com/conda/conda/blob/4.2.13/conda/base/context.py#L155-L173) can be set with an environment variable prepending `CONDA_` and then the rest of the parameter in all caps with underscores.

Several config parameters have aliases.  The `context.always_yes` parameter is a good example.  It is aliased to `yes`.  So setting `CONDA_ALWAYS_YES` and `CONDA_YES` with have the equivalent result.

Configuration is also merged from quite a few sources.  We first scan `[SEARCH_PATH](https://github.com/conda/conda/blob/4.2.13/conda/base/context.py#L91)` for files that look like condarc, .yml, and .yaml.  Then we look at environment variables.  Then we look at CLI flags from argparse.  Parameters set later in that chain override parameters set earlier.  At least for the "primitive" parameter type.

Sequence parameter types, like `channel`, are a little trickier.  The lists are merged.  It's definitely caused some confusion.  I'm way behind on updating the docs.  But if it causes you problems let me know and I'll help with solutions.

**Comment by kalefranz** [comment]
Also, if there are things for conda-smithy that you'd like me to add to `conda/exports.py`, please let me know.

**Comment by jakirkham** [comment]
As far as the `subdir`/`platform` split goes, am ok with having to specify the platform with an argument if that is the way we are going. The big thing with `conda-smithy` is it has to masquerade as an OS different from the one that `conda` is installed on (e.g. pretending we are on Linux when we are on Windows and so forth). So as long as we settle on one well-defined way to do this, I think we should be golden.

Probably be able to give you a better idea of what we need after playing with it. FWICT most things that we would want are in `conda/exports.py`.

Though one thing that would be nice is a way to get `defaults` channel spec for different platforms. Near term just having `DEFAULT_CHANNELS_UNIX` and `DEFAULT_CHANNELS_WIN` included in `conda/exports.py` should be sufficient. Long term maybe a `get_defaults` function and/or have `get_index` properly expand `defaults` based on the specified `platform`.

**Comment by kalefranz** [comment]
Should be long-ago fixed.
