### ISSUE TITLE
Cygwin activate works incorrectly

### ISSUE THREAD

**Issue by SnookEE** [conda/conda#3352]
The activate for the Cygwin environment still works incorrectly. There are a few changes needed to make it work properly. 

I used the bash replace to modify to the proper Cygwin prefix. This seemed to work from both Cywin and MSYS2.

There also seemed to be a newline in the return of conda for the changeps1 variable.

The hexdump was 

0000000 0d31 000a
0000003

To my mind that indicated a local configuration issue, but I don't seem to have anything different than the base 4.1 conda install locally. The content of the condarc file is

```
changeps1: true

```

``` bash
diff --git a/Scripts/activate b/Scripts/activate
index a1d5a77..5ad8d2b 100644
--- a/Scripts/activate
+++ b/Scripts/activate
@@ -59,6 +59,15 @@ fi
 source "$_CONDA_DIR/deactivate"

 _NEW_PART=$("$_CONDA_DIR/conda" ..activate $_SHELL$EXT "$args")
+case "$(uname -s)" in
+    CYGWIN*)
+        #BUG IN conda, wants to append /C, not /cygdrive/c
+        _NEW_PART=${_NEW_PART//\/C/\/cygdrive/c}
+        ;;
+    *)
+        ;;
+esac
+
 if (( $? == 0 )); then
     export CONDA_PATH_BACKUP="$PATH"
     # export this to restore it upon deactivation
@@ -81,11 +90,12 @@ if (( $? == 0 )); then
     #    Last date of change: 2016-06-21
     firstpath=${PATH%%:*}
     export CONDA_PREFIX="$(echo ${firstpath} | sed "s|/bin$||")" &>/dev/null
-
+
+    changeps1="$(echo -e "$("$_CONDA_DIR/conda" ..changeps1)" | tr -d '[[:space:]]')"
     # if CONDA_DEFAULT_ENV not in PS1, prepend it with parentheses
-    if [ $("$_CONDA_DIR/conda" ..changeps1) = "1" ]; then
+    if [ "$changeps1" == "1" ]; then
         if ! $(grep -q CONDA_DEFAULT_ENV <<<$PS1); then
-            export PS1="(${CONDA_DEFAULT_ENV}) $PS1"
+            export PS1="\[\e[94m\](${CONDA_DEFAULT_ENV}) $PS1"
         fi
     fi
```

**Comment by mingwandroid** [comment]
IMHO, we should fix the source of the problem rather than patching over it ..

Arguably `conda` should be giving us _NEW_PART in a shell-appropriate form, which would involve using `cygpath -u` internally, something like: https://github.com/conda/conda-build/commit/e1e905#diff-c4cfa32f287679b20f86b99df93b3188R460, this would then work for both `MSYS2` and `Cygwin` and also it would respect `/etc/fstab`.

**Comment by SnookEE** [comment]
I agree. Obviously outputting the extra new line was an oversight.

I would add hooks to pass in the correct path type requested, i.e. cygwin, msys2, or unix.

The os.path module can return a absolute normalized path, from the there I find some regular expressions are considerably less ass pain than any other option. You are being helped greatly by the drive naming rules on windows. 

```python
import os
import re
from enum import Enum

class PathType(Enum):
    CYGWIN = 0,
    MSYS2  = 1

class PathConversion:
    drive_regex = re.compile('(?P<drive_letter>[A-Z]):\\\\(?P<path>.*)')
    msys2_drive = '/{drive_letter}/{path}'
    cygwin_drive = '/cygdrive/{drive_letter}/{path}'
    @classmethod
    def normpath(self,x,pt=PathType.MSYS2):
        m = self.drive_regex.match(os.path.abspath(x))
        if m:
            dr_letter = m.group('drive_letter')
            path = m.group('path').replace('\\','/')
            if pt==PathType.MSYS2:
                path = self.msys2_drive.format(drive_letter=dr_letter.upper(), path=path)
            else:
                path = self.cygwin_drive.format(drive_letter=dr_letter.lower(),path=path)

            return path

if __name__ == "__main__":
    x = 'C:/home/workspace_cdt'
    pt = PathType.CYGWIN

    p = PathConversion.normpath(x,pt)

    print(p)
```

Network paths will need a different approach

**Comment by mingwandroid** [comment]
Conda already has code similar to this, it just needs some attention. You can see it in this file:

https://github.com/conda/conda/blob/master/conda/utils.py#L111

> The os.path module can return a absolute normalized path, from the there I find some regular expressions are considerably less ass pain than any other option. You are being helped greatly by the drive naming rules on windows.

Even less of a pain (and more correct) is to use `cygpath -u` like in the code from `conda-build` that I linked to earlier. Anything else won't respect the internal path conversions of Cygwin/MSYS2, for example parsing `/etc/fstab`.

**Comment by SnookEE** [comment]
I bet you'll run into path trouble trying to ensure you always have cygpath available when you get called from weird places. How do you get called back out to MSYS2 from that python script? What happens when the pwd you called from what you think is MSYS2 hits the cygwin pwd and your -w hook fails.

Its not always the cygwin terminal, sometimes other programs use the cygwin in path and you get called without the path setup as you expect. Perhaps all that has been thought through, but to me it sounds like trouble, especially when you are the one who is generating the paths and the conversion over is regular.

**Comment by mingwandroid** [comment]
If bash.exe is on your path then cgypath.exe is too (unless you deleted it). Your examples of Cygwin / MSYS2 mix-up seem contrived.  If someone has both on their path whichever appears first will mask the other, besides that's a case of PEBCAK.

We are not discussing other programs here,  we are talking about using conda from a Cygwin and / or MSYS2 shell are we not?

**Comment by SnookEE** [comment]
> We are not discussing other programs here, we are talking about using conda from a Cygwin and / or MSYS2 shell are we not?

Maybe, until you try and include python into your build flow, and then suddenly its getting called from lots of different places. Whether that matters for something like activate I'm not sure, but it is commonly where corner case things get lit up in my experience. 

And I think I agree on the point about bash and cygpath, as well as msys2 bash and pwd. You explicitly know where bash.exe is, and assuming co-location i guess is acceptable. 

Perhaps that is the key, have the environment aspects that are necessary be explicitly provided as part of the interface to any path operation from the conda software.

**Comment by mingwandroid** [comment]
Indeed, there are many gotchas when dealing with `POSIX` emulation and `GCC` on Windows. In general people take bits from here, there and everywhere ending up with a hodge-podge solution that works only in some cases.

This is one of the reasons that `MSYS2` was started. It aims to be a cohesive `POSIX` emulation layer (light fork of `Cygwin`) which does all that it can facilitate interoperation between that layer and native Windows. As such, it has a large suite of packages (end-user software, developer tools and libraries) for both `POSIX` and native Windows `GCC` (`mingw-w64`).

You can install and use many `MSYS2` packages from `conda` too - these were added mainly to allow building `conda` packages that require a `POSIX` build system or `GCC` to be built in a repeatable way. The POSIX packages are prefixed with `m2-` and the native `GCC` (`mingw-w64`) ones are prefixed with `m2w64-`.

It's not perfect, but `POSIX` on Windows probably never will be.

**Comment by DancingQuanta** [comment]
Any progress on this?

**Comment by kalefranz** [comment]
Cygwin should be supported as of conda 4.4.  There is currently a known bug however, tracked in https://github.com/conda/conda/issues/6896.
