### ISSUE TITLE
Conda-install clobbers bin scripts of the same name from different packages

### ISSUE THREAD

**Issue by gbrener** [conda/conda#3353]
Two different conda packages each contain separate scripts which get installed into a fresh conda environment's `bin` location. Since these separate scripts happen to share the same filename, `conda install` silently overwrites the script from the first package with the script from the second package.

This is a problem because users have no way of knowing which of their packages got overwritten after the fact, and it can cause unexpected breakage.

The same problem exists for `conda update`.

**Comment by kalefranz** [comment]
conda config --set path_conflict prevent

This was built into conda 4.3.  The other settings for `path_conflict` are `warn` and `clobber`.  The default in conda 4.3 was intended to be `prevent`, but there are just too many conflicts right now and it would be been visibly painful to users to roll out without cleaning up our repositories first.

In future conda feature releases we're going to try to transition the default setting to `warn` and then finally to `prevent`.
