### ISSUE TITLE
`conda search --platform osx-64` shows linux packages (on Linux)

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#3357]
I ran:

`conda search --platform osx-64 -c r-assertthat`

.. and got the linux packages.

adding `--debug` I see:

`DEBUG conda.models.channel:__init__(115): making channel object for url: https://conda.anaconda.org/r/linux-64`

**Comment by kalefranz** [comment]
Pretty sure we fixed this a while ago.  Closing.  But feel free to re-open if I'm wrong.
