### ISSUE TITLE
R Cairo library font problem

### ISSUE THREAD

**Issue by RussianImperialScott** [conda/conda#3359]
Hi -

I installed both R-3.3.1 and Microsoft R Open 3.2.3 using the conda package manager and cannot get fonts to render properly in plots for which the Cairo library backend is used (`CairoPDF`, `CairoPNG`, etc.). For example:

```
library(ggplot2)
library(Cairo)

# Set up the plot
pl = qplot(data = mtcars, x = cyl, y = mpg)

# Export using default pdf function
pdf(file = 'test_plot_default.pdf', height = 6, width = 6)
print(pl)
dev.off()

# Export using Cairo pdf function
CairoPDF(file = 'test_plot_Cairo.pdf', height = 6, width = 6)
print(pl)
dev.off()
```

I have confirmed this issue on both Ubuntu 14.04 and 16.04, as well as similarly bad results when using the `CairoPNG` function instead of `png`. The results below were generated on Ubuntu 14.04 using R-3.3.1.

[test_plot_Cairo.pdf](https://github.com/conda/conda/files/445879/test_plot_Cairo.pdf)
[test_plot_default.pdf](https://github.com/conda/conda/files/445878/test_plot_default.pdf)

**Comment by mingwandroid** [comment]
Can you try this again with R-3.3.2?
