### ISSUE TITLE
activate.bat broken on conda-canary??

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#3361]
My activate.bat/deactivate.bat appear to have been nuked and replaced with

```
@echo off
call "C:\Minonda\Scripts\activate" %*
```

```
@echo off
call "C:\Minonda\Scripts\deactivate" %*
```

???

Copy-pasting from the latest on github doesn't work because [L6](https://github.com/conda/conda/blob/master/shell/deactivate.bat#L6)

```
@SET "CONDA_EXE=%~dp0\..\Scripts\conda.exe"
```

results in

```
CALL "C:\Python\Scripts\\..\Scripts\conda.exe" ..checkenv "cmd.exe" "py35-32"

IF errorlevel 1 exit /b 1
The system cannot find the path specified.
```

This issue I think is the extra `\`.

Replacing L6 with `SET "CONDA_EXE=%~dp0conda.exe"` and substititing `s/~dp0\/~dp0` in both activate and deactivate appears to fix it.

**Comment by kalefranz** [comment]
I'm guessing we got this cleaned up before that version of conda left canary?

**Comment by dhirschfeld** [comment]
Yeah, this seems to have not made it out of canary so I'll close.
