### ISSUE TITLE
System python PATH set to python3 

### ISSUE THREAD

**Issue by spraharsh** [conda/conda#3367]
I tried to install multiple packages using conda , after installing it with pip,  when I tried to `$python`
I end up getting python3. I believe this is causing issues to my system. the error is described here

http://askubuntu.com/questions/819476/errors-occurring-when-trying-to-install-python-command-not-found

It would also be nice if somebody could help me set my system python path to 2 again too

**Comment by kalefranz** [comment]
Use the miniconda installer to install conda, not pip.  As you've found out, all kinds of bad things can happen.
