### ISSUE TITLE
Environment Removal Error

### ISSUE THREAD

**Issue by serg2014** [conda/conda#3368]
When try to delete environments error occurs

`C:\Anaconda2\python.exe C:\Anaconda2\Scripts\conda-script.py remove --json --yes --name first_env --all: {"maxval": 173, "finished": false, "progress": 0} 
{"maxval": 173, "finished": false, "name": "anaconda-navigator", "progress": 0}
{"error": "An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
 https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
 File \"C:\\Anaconda2\\lib\\site-packages\\conda\\cli\\main.py\", line 130, in args_func
 exit_code = args.func(args, p)
 File \"C:\\Anaconda2\\lib\\site-packages\\conda\\cli\\main_remove.py\", line 193, in execute
 plan.execute_actions(actions, index, verbose=not args.quiet)
 File \"C\\Anaconda2\\lib\\site-packages\\conda\\plan.py\", line 599, in execute_actions
 inst.execute_instructions(plan, index, verbose)
 File \"C:\\Anaconda2\\lib\\site-packages\\conda\\instructions.py\", line 135, in execute_instructions
 cmd(state, arg)
 File \"C:\\Anaconda2\\lib\\site-packages\\conda\\instructions.py\", line 82, in UNLINK_CMD
 unlink(state['prefix'], arg)\n File \"C\\Anaconda2\\lib\\site-packages\\conda\\install.py\", line 1127, in unlink
 rm_rf(dst)\n File \"C:\\Anaconda2\\lib\\site-packages\\conda\\install.py\", line 274, in rm_rf
 if trash and move_path_to_trash(path):
 File \"C:\\Anaconda2\\lib\\site-packages\\conda\\install.py\", line 1023, in move_path_to_trash
log.debug(\"Could not move %s to %s (%s)\" % (path, trash_file, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 11: ordinal not in range(128)\n", 
"error_type": "UnexpectedError" 
}`

conda info output
Current conda install:
             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 2.0.0
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
Closing as outdated.
