### ISSUE TITLE
Conda env update fails with mysterious message about adding None and a list

### ISSUE THREAD

**Issue by gnhernandez** [conda/conda#3376]
Hi, 

I was running conda env update and got this traceback where it seems an isntall command was trying to add a None with a list:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main_update.py", line 112, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
  File "C:\Anaconda\lib\site-packages\conda_env\installers\pip.py", line 9, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
As per the output of conda info, here it is:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c:\DCM\dcm-intuition>conda info
Warning: could not import binstar_client ('args' object has no attribute 'site')Current conda install:

```
         platform : win-64
    conda version : 4.1.11
conda-env version : 2.5.2
```

  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\Napoleon.condarc
         offline mode : False
    is foreign system : False

**Comment by HugoTian** [comment]
can you show me the detail of your environment ? like the output of "conda list -n your_env" ?
