### ISSUE TITLE
conda-canary ignores CONDA_FORCE_32BIT environment variable

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#3378]
Repro:
```
set CONDA_FORCE_32BIT=1
conda create -n test-win32 python=3.5 pywin32
```
The above command will install a 64bit Python and pywin32 despite `CONDA_FORCE_32BIT` being set to 1.

Curiously I can install a 32bit python on  its own, but if I then try to install `pywin32` into the same environment it installs the 64bit version which fails (`import win32ui`) with a DLL no a valid win32 application error.

***Aside:*** It would be nice if the architecture info was shown in the install phase so  you would know beforehand that it was attempting to install the wrong architecture version

**Comment by kalefranz** [comment]
fixed in #3391
