### ISSUE TITLE
Windows 10 - SSL Error only solved when installing python from python.org

### ISSUE THREAD

**Issue by errorreplicator** [conda/conda#3381]
Guys,
My set up: Win10 + miniconda with python 3.5.2 + PyCharm 2016.2.2
I have had strange issue when I was trying to use quandl package. The error was 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

code triggering this issue was : 
import Quandl as qd
ds = qd.get("FMAC/HPI_PA", authtoken="MyAuthTockenHere")
strange thing was that the same code was working on my old laptop on the same Windows 10 + miniconda and PyCharm installation. I've tried everything from Windows settings to miniconda and pycharm reinstallation along with all necessary packages update. Nothing worked only until I realised that on my old laptop I had Python 3.5.2 from python.org installed first before I moved to miniconda. So I installed Python 3.5 from Python.org and all started working immediately. 
Note that I have not even changed default project interpreter in PyCharm from miniconda python.exe to python.org python.exe it was just the fact I've installed it and this solved my issue.
Should this be working like this ? Does miniconda requires python installation from python.org or this is a bug ?
Regards
E

**Comment by kalefranz** [comment]
> Does miniconda requires python installation from python.org

No.  You probably had an outdated pyopenssl package.  `conda update pyopenssl` usually clears this up.
