### ISSUE TITLE
Virtual env creation with python3 produces "TypeError: 'Process' object is not callable"

### ISSUE THREAD

**Issue by aaronpolhamus** [conda/conda#3389]
When creating a virtual environment using python3 as the `python` default I am getting a strange error message that seems to be non-fatal, but recommends that I refer it to this issues thread. Interested in (1) Where this comes from, (2) Whether it's affecting anything in my virtual env, and (3) how to fix it.

After running `conda update conda` to update my conda verion on OSX I run the following command to create a virtual environment with the most current python3 version as the `python` default: 

`conda create --name credijusto python=3`

This seems to work fine until the very end, when I run into the following error output: 

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/aaronpolhamus/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 431, in install
    print_activate(args.name if args.name else prefix)
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 100, in print_activate
    shell = find_parent_shell(path=False)
  File "/Users/aaronpolhamus/anaconda/lib/python2.7/site-packages/conda/utils.py", line 260, in find_parent_shell
    pname = process.parent().name().lower()
TypeError: 'Process' object is not callable
```

I thought this meant that the virtual env creation had failed, so to reproduce the error I re-ran `conda create --name credijusto python=3`, which returned: 

`Error: prefix already exists: /Users/aaronpolhamus/anaconda/envs/credijusto`

Running `source activate /Users/aaronpolhamus/anaconda/envs/credijusto` takes me into a virtual environment, which seems to work normally. Because the virtual env appears to function normally, it's unclear to me what this error is referring to. To re-cap, I'd like to know: 
(1) Where this comes from, 
(2) Whether it's affecting anything in my virtual env, and 
(3) how to fix it.

Here's the output of `conda info`:

```
             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.3.1
       python version : 2.7.12.final.0
     requests version : 2.8.1
     root environment : /Users/aaronpolhamus/anaconda  (writable)
  default environment : /Users/aaronpolhamus/anaconda/envs/credijusto
     envs directories : /Users/aaronpolhamus/anaconda/envs
        package cache : /Users/aaronpolhamus/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/aaronpolhamus/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by kalefranz** [comment]
Outdated ticket.  `find_parent_shell` code path no longer exists.  Shouldn't be any related issues with either 4.2 or 4.3 release series.
