### ISSUE TITLE
"No such file or directory" during multiple parallel activations

### ISSUE THREAD

**Issue by ksbeattie** [conda/conda#3411]
Nearly identically to #2837, I am also working in a clustered environment where multiple parallel processes are activating the same env simultaneously and I am getting "No such file or directory" regularly.

In fact running the following script, in 3 different terminals at once, will reproduce the problem within a few seconds:

```
#!/bin/bash
# Look for race condition in activating an anaconda env
# Run this in multiple windows at once and wait for one of them to crash.

ret=0
while [ "$ret" == "0" ]; do
    echo -n .
    source activate myenv
    ret=$?
done
```

The immediate solution (as #2837 did) would appear to be to add another exception to the exception [in install.py in symlink_conda_hlp at ~line 616](https://github.com/kalefranz/conda/blob/8b5bc4ec76075f2896d5a53d1b5e41a0194a9c11/conda/install.py#L616).  This time adding errno.ENOENT to the list.

So many exceptions to exceptions raises the question in my mind if re-symlinking is the right thing to do during activation.   If the symlinks can't be entirely removed, could this be replaced with just a check if the symlinks are there and a warning if somehow they've gone missing?  Keeping it read-only will avoid these race conditions.  (In fact, the above suggestion probably doesn't remove all the possible race conditions here.)  An arg to activate to force re-symlinking could be added to override the default of not re-symlinking.  Just some thoughts...

CC'ing NERSC admins who have helped me debug this: @rcthomas

**Comment by ksbeattie** [comment]
Update:
Adding `errno.ENOENT` at the line suggested above won't fix this issue as it is in the `if lexists` block.

There is another race condition here which my above script above reveals:
```
/path/to/conda/envs/myenv/bin/activate: line 86: /path/to/conda/envs/myenv/bin/conda: No such file or directory
/path/to/conda/envs/myenv/bin/activate: line 86: [: =: unary operator expected`
```
Unfortunately, I don't believe this can be fixed without some kind of db or file-system level semaphore - since this looks like a race between 2 instances where one is in python and the other is in bash.

I found that since the parallel jobs in my clustered env only want to run python and not any conda commands, simply prepending PATH is sufficient for my needs.

So, it seems that activating an environment is simply not a re-entrant operation at the moment *but* just setting PATH is enough for "activating" execution-only environments.  This seems something well worth documenting.

**Comment by kalefranz** [comment]
This would be solved when implementing https://github.com/conda/conda/issues/2502, which I'm hoping to include in conda 4.3.

**Comment by chicagofire** [comment]
We run into this issue quite frequently in nearly an identical fashion as @ksbeattie. I've had to hack install.py to make it functional as it was impacting our production processes.

```python
def symlink_conda_hlp(prefix, root_dir, where, symlink_fn):
    scripts = ["conda", "activate", "deactivate"]
    prefix_where = join(prefix, where)
    if not isdir(prefix_where):
        os.makedirs(prefix_where)
    for f in scripts:
        root_file = join(root_dir, where, f)
        prefix_file = join(prefix_where, f)
        if realpath(root_file) != realpath(prefix_file):
            try:
                # try to kill stale links if they exist
                if os.path.lexists(prefix_file):
                    rm_rf(prefix_file)
                # if they're in use, they won't be killed.  Skip making new symlink.
                if not os.path.lexists(prefix_file):
                    symlink_fn(root_file, prefix_file)
            except (IOError, OSError) as e:
                if (os.path.lexists(prefix_file) and
                        (e.errno in (errno.EPERM, errno.EACCES, errno.EROFS, errno.EEXIST))):
                    log.debug("Cannot symlink {0} to {1}. Ignoring since link already exists."
                            .format(root_file, prefix_file))
                else:
                    raise
```

The key is the line:
```python
  if realpath(root_file) != realpath(prefix_file):
```

This way, the symlinks are redone ONLY if they're not correct.

**Comment by Aethylred** [comment]
> The key is the line:
> 
>  `if realpath(root_file) != realpath(prefix_file):`
> This way, the symlinks are redone ONLY if they're not correct.

Ah, this will update the symlinks during a batch process, so all jobs before being redone will be expecting the old symlink and after will have the new symlink. There's potential that the runtime environment might change part way through a batch of parallel processes leading to inconsistent results.

Would a semaphore be a better method, increment the semaphore each time the environment is activated, and decremented each time it is deactivated. The links are only removed when the semaphore gets to zero, and created when it becomes non-zero.

**Comment by Aethylred** [comment]
We use a work-around in the mean time which prevents further errors by not calling

```python
 conda ..checkenv bash hsf2nc
```
At line 53 of (version 4.2.9) the activate script. Which prevents it from deleting and then recreating each of the conda, activate and deactivate scripts.

**Comment by kalefranz** [comment]
This has been fixed in 4.3. (I'm not sure if the fix was backported to 4.2 or not.)

**Comment by ksbeattie** [comment]
FWIW, I'm still seeing this problem in 4.3.21

**Comment by quanvuong** [comment]
I'm still seeing this problem in 4.3.22

**Comment by kalefranz** [comment]
For all you folks working on clusters, I'll be especially interested in your feedback on conda 4.4. The "symlink conda" behavior that is at the heart of this issue has been dropped, in favor of another strategy. The new strategy is largely related to work in #5044 and follow-on PRs. 

There's a conda 4.4.0beta2 release available now if you want to start playing with it. It's in the canary channel, but under a special label. To get it, do something like

    conda config --add channels conda-canary/label/beta
    conda update conda

I've re-opened this issue to keep the conversation going. As is, I don't think there will be any further progress for a solution in conda 4.3. But there's a lot of opportunity to get it right in conda 4.4.

**Comment by kalefranz** [comment]
Conda 4.4 dumped the symlinking conda stuff.  So this issue should be completely resolved now.

**Comment by ksbeattie** [comment]
Thanks so much @kalefranz!

A quick test of my above "condabomb.sh" script running on 6 different nodes didn't show any failures to active.

@rcthomas This was on cori, twice.  Once using the python/3.6-anaconda-4.4 module and again using python/2.7-anaconda-4.4
