### ISSUE TITLE
Addition on new R library in conda r essentials 

### ISSUE THREAD

**Issue by mahi80** [conda/conda#3414]
how can we add  R library which are not available in r essentials like library(bsts) and its depandent library such BH,Boom ,BoomSpikeLab

**Comment by mingwandroid** [comment]
You can do it with `devtools` easily (*) enough. If on Windows:

`conda install m2w64-toolchain m2-make r-devtools r-essentials`

.. otherwise you'll need system compilers installed and:

`conda install r-devtools r-essentials`

Then in R:

```
library(devtools)
# Probably only necessary for Windows:
options(download.file.method = "wget")
# For non-github things (this isn't using devtools):
install.packages('bsts')
# For github things (this is using devtools):
install_github('hadley/readxl')
```
