### ISSUE TITLE
can't open text editor while conda environment activate

### ISSUE THREAD

**Issue by BMJHayward** [conda/conda#3415]
Vim will work in bash when an environment is activated, but vifm won't open vim to edit files in the same environment.
This doesn't occur in other environment managers, e.g. venv, virtualenv, or when no environment is active.

The screen blinks and refreshes, but won't open the editor.

conda 4.1.6
ubuntu 16
vim 7.4.1689
vifm 0.7.8
tmux 2.1
python 2.7/3.5

Please advise if this issue needs to edited or moved elsewhere.
Thanks.

**Comment by kalefranz** [comment]
vifm is probably making stupid assumptions about PATH that it shouldn't be making.  Nothing really conda can do here.  Best bet would be to head over to conda-forge and package vim and vifm and then conda-install them.  Or file a ticket upstream with vifm.
