### ISSUE TITLE
how to use conda  install environment.yml package?

### ISSUE THREAD

**Issue by rfyiamcool** [conda/conda#3417]
I know conda install flask,  then how to install pacakge with environment.yml file ?

I don't find usage in conda document.

**Comment by csoja** [comment]
Does this http://conda.pydata.org/docs/using/envs.html help?

**Comment by HugoTian** [comment]
conda env create -f environment.yml

**Comment by ducva** [comment]
conda env update

**Comment by pauloabelha** [comment]
> 
> 
> Does this http://conda.pydata.org/docs/using/envs.html help?

No. This helps:
https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by anosharshad** [comment]
I downloaded a file environment.yml but it always saves as environment.yml.txt thats why this command conda env create -f environment.yml is not reading the file. Any solution ?

**Comment by resthomas** [comment]
> I downloaded a file environment.yml but it always saves as environment.yml.txt thats why this command conda env create -f environment.yml is not reading the file. Any solution ?

Have you tried renaming it to environment.yml?

**Comment by pythonns** [comment]
> I downloaded a file environment.yml but it always saves as environment.yml.txt thats why this command conda env create -f environment.yml is not reading the file. Any solution ?

could you try>  conda env create -f environment-dev.yml

> > I downloaded a file environment.yml but it always saves as environment.yml.txt thats why this command conda env create -f environment.yml is not reading the file. Any solution ?
> 
> Have you tried renaming it to environment.yml?

I've tried this, and it work.

**Comment by erfannariman** [comment]
If your anaconda env is already activate, use:

```
conda env update --file environment.yml
```

Or update a specific environment without activating it:
```
conda env update --name envname--file environment.yml
```

**Comment by mattip** [comment]
It would be nice if instead of the error `CondaValueError: could not parse 'name: xxx' in: environment.yml` when mistyping `conda install --file environment.yml`, conda would give a more helpful error message like `conda install cannot use this environment.yml file. Did you mean conda env update --file environment.yml`?
