### ISSUE TITLE
Can't make python 2 debug environment

### ISSUE THREAD

**Issue by vladfi1** [conda/conda#3421]
I'm trying to create an environment to use python 2 built with debug symbols:

    $ conda create -n debug2 python=2.7.11=d0
    Fetching package metadata: ..
    Solving package specifications: ..
    Error: Unsatisfiable package specifications.
    Generating hint:

The hint generation terminates, but it doesn't output anything. The same happens with `2.7.10-d0`, `2.7.9-d2` and `2.7.10-d1`. Note that these packages are all valid - they show up in `conda search python` and the `create` commands don't complain about not finding them.

**Comment by kalefranz** [comment]
Try

    conda create -n debug2 python=2.7.11=d0 debug

`debug` is the package that provides the debug feature, so you also need to install it.

**Comment by tadeu** [comment]
Just a note, there seems to be no `2.7.11 d0` package in Anaconda :(

```
Using Anaconda API: https://api.anaconda.org      
Fetching package metadata ...........             
Solving package specifications: .                 
Error: Package missing in current win-64 channels:
  - python 2.7.11 d0                              
                                                  
You can search for packages on anaconda.org with  
                                                  
    anaconda search -t conda python
```
