### ISSUE TITLE
Ipython 5.1 broken with conda

### ISSUE THREAD

**Issue by d10genes** [conda/conda#3423]
If I install the following conda env file

````
name: bug
dependencies:
- python=3.5
- jupyter
````

I get `ImportError: cannot import name 'pexpect'`
Trace and conda list [here](https://gist.github.com/d10genes/3fd2adbb0ed856264466987d678543ab).

**Comment by kalefranz** [comment]
`from IPython.external import pexpect`

That definitely looks like an IPython issue to me.  Suggest filing a report with those folks if you're still stuck.
