### ISSUE TITLE
linking errors

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#3426]
I can reproduce this very weird linking error from my script to quickly reinstall a whole enviroment.
Version: conda 4.1.11

Steps to reproduce:

1. `conda create -n TEST python=3`
2. `source activate TEST`
3. `conda install -y --file standard_py3_conda_packages.txt`

This repeatably fails for me at linking the `ipyparallel` package.
Note, that this has worked fine several conda versions until recently, not sure when it failed.
Attached the package list file.

[standard_py3_conda_packages.txt](https://github.com/conda/conda/files/473564/standard_py3_conda_packages.txt)

**Comment by michaelaye** [comment]
Note, I have conda-forge as channel in condarc and this issue is weirdly fixable by:

4.: `conda install notebook` (or any other of still missing packages that were blocked because of above fail)
5. execute again `conda install -y --file standard_py3_conda_packages.txt`

**Comment by kalefranz** [comment]
I think this might be the same thing as what happened here
https://github.com/conda/conda/issues/3431#issuecomment-247220888

Looks like there's already an issue for it here: https://github.com/conda-forge/ipyparallel-feedstock/issues/8
