### ISSUE TITLE
Error creating env on Windows

### ISSUE THREAD

**Issue by friend0** [conda/conda#3430]
Previously working, but looks like I can no longer create working envs without this error?
Looks like the path in [Error 3] did not get joined properly?

---

Traceback (most recent call last):
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\Scripts\conda-sc
ript.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\lib\site-package
s\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\lib\site-package
s\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\lib\site-package
s\conda\cli\main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\lib\site-package
s\conda\cli\install.py", line 428, in install
    append_env(prefix)
  File "C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\lib\site-package
s\conda\misc.py", line 248, in append_env
    os.mkdir(dir_path)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\Usersrya
rodriguez\.conda'

C:>conda info
Current conda install:

```
         platform : win-64
    conda version : 4.1.6
conda-env version : 2.5.1
```

  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2
 (writable)
  default environment : C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2
     envs directories : C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\
envs
        package cache : C:\Users\ryarodriguez\AppData\Local\Continuum\Anaconda2\
pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
Could you run `conda update conda` to get conda version 4.2.6 or later, and then try again?
