### ISSUE TITLE
Install of older python (revert) from newer yields error

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3433]
Build log at https://travis-ci.org/conda/conda-build/jobs/160031372

2.7 and 3.5 builds complete just fine - but they start with (approximately) the python version that they are using for the testing.

Gist of the situation is that we start with a 3.5 installation, and then want to go back to a 3.4 installation for testing purposes.  With conda 4.1.11, this works.  For 4.2.6, it does not.  I have not dug in further, but would be happy to do so.

**Comment by kalefranz** [comment]
Just verified that I'm able to reproduce locally on OSX.

**Comment by kalefranz** [comment]
I'm thinking this is something where we just swallowed the error previously.  It's a real problem though.  Somehow the file path isn't getting unlinked from the 3.5 install before it gets linked from the 3.4 install.

**Comment by mangerij** [comment]
I just want to point out that this still doesn't fix the problem that arises in #3437 . I just did a fresh install of conda on Ubuntu 16.04 and then _only_ `conda install --channel https://conda.anaconda.org/conda-forge fenics` which produces the `CondaOSError: OS error: failed to link` issue.

**Comment by mangerij** [comment]
Ok, perhaps I was a bit ahead of myself.

If you don't update conda to 4.2.13  before running `conda install --channel https://conda.anaconda.org/conda-forge fenics` then you will get the CondaOSError. 

I apologize for commenting on an old issue but perhaps if someone runs into the same issue, this will fix it. Cheers.
