### ISSUE TITLE
unexpected error when trying to update python

### ISSUE THREAD

**Issue by mr-fuller** [conda/conda#3439]
From the ArcGIS Pro environment, I typed "conda update python" which triggered an unexpected error.
Screenshots of the traceback and conda install info are attached.
![condaerror](https://cloud.githubusercontent.com/assets/20356962/18560499/dc808f5c-7b49-11e6-97f3-833d00ac7b05.JPG)
![condainfo](https://cloud.githubusercontent.com/assets/20356962/18560500/dc83ff0c-7b49-11e6-8241-29433e3ca544.JPG)

**Comment by kalefranz** [comment]
Could you start with updating conda and then try again?

    conda update conda

Should get you `4.2.6` or greater (we're about to release 4.2.7).

**Comment by mr-fuller** [comment]
Do I need to navigate to the root environment first?

**Comment by kalefranz** [comment]
shouldn't matter

**Comment by mr-fuller** [comment]
`conda update conda` gave an error message saying the package 'conda' is not installed in [name/location of environment]
then I tried `conda install conda`, which yielded an error saying 'conda' can only be installed into the root environment, which is why I asked.

I tried `conda install python` and that removed python 3.4.4, and then I typed conda install python again, and it said 3.4.5 was installed, but when I typed python, I got a message saying python is not recognized as an internal or external command

**Comment by kalefranz** [comment]
I guess maybe you do then need to be in the root environment.  I'm not sure how arcgis configures things.  Or maybe try running `deactivate` and then `conda update conda`.

**Comment by mr-fuller** [comment]
That worked! Thanks! I'm still having other issues with the ArcGIS Pro conda environment, but I will close this issue.
