### ISSUE TITLE
How to deactivate an environment using Windows?

### ISSUE THREAD

**Issue by raderaj** [conda/conda#344]
I'm working on a windows PC machine. It is easy to create a new environment using a command such as:
conda create -n test python pip

Then the prompt accurately indicates one should activate this environment using 
activate test 
(note this is not source activate test).

However I can't seem to deactivate or change to other environments without closing out the command console/powershell.
Typing 
deactivate test 
produces this error:
'deactiveate' is not recognized as an internal or external command, opererable program or batch file.

Any suggestions on how to deactivate this environment or change to another one?

**Comment by u2berggeist** [comment]
I'm running into these issues right now as well. No idea what on earth is going on. See [my StackExchange question](https://stackoverflow.com/q/50993497/7564988)  for more details.

Bottom line, I my computer "find" `activate`, `deactivate`, or `conda` despite fully knowing where they are via a `where` function. Even if I `cd` to the location of the files, it still claims that it can't find them.

**Comment by gitDawn** [comment]
> On Windows, due to the lack of the deactivate command, you type:
> 
> ```
> > activate root
> ```
> Note that `root` is a special reserved name for the root environment.

That doesn't work.
'activate' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ecardenas1123** [comment]
Hi everyone, I'm a beginner with programming languages and I'm running into this issue right now, could someone solve it?
thanks a lot.

> (env) λ deactivate
> 'deactivate' is not recognized as an internal or external command,
> operable program or batch file.
