### ISSUE TITLE
Could not connect to https://repo.continnum.io/pkgs/free/win64

### ISSUE THREAD

**Issue by MAK546003** [conda/conda#3446]
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs
/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.6
       conda is private : False
      conda-env version : 4.2.6
    conda-build version : 2.0.1
         python version : 2.7.11.final.0
       requests version : 2.11.1
       root environment : C:\Users\Mukesh Bhadane\Anaconda3  (writable)
    default environment : C:\Users\Mukesh Bhadane\Anaconda3
       envs directories : C:\Users\Mukesh Bhadane\Anaconda3\envs
          package cache : C:\Users\Mukesh Bhadane\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\Mukesh Bhadane\Anaconda3\Scripts\conda-script.py install mingw libpy
thon`

    Traceback (most recent call last):
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\exceptions
.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\cli\main.p
y", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\cli\main_i
nstall.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\cli\instal
l.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\api.py", l
ine 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\fetch.py",
 line 282, in fetch_index
        for url in urls]
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\fetch.py",
 line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\Mukesh Bhadane\Anaconda3\lib\site-packages\conda\fetch.py",
 line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host
='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-6
4/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.
continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.
continuum.io/pkgs/free/win-64/

**Comment by kalefranz** [comment]
Please just try the request again.  If the problem persists, please file a new ticket.
