### ISSUE TITLE
conda update mkl fail, RuntimeError

### ISSUE THREAD

**Issue by stevechoris** [conda/conda#3449]
I use `conda update mkl` to update the package but got the following error message:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.6
       conda is private : False
      conda-env version : 4.2.6
    conda-build version : 1.20.0
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /home/guanwanxian/anaconda2  (writable)
    default environment : /home/guanwanxian/anaconda2/envs/gpu2
       envs directories : /home/guanwanxian/anaconda2/envs
          package cache : /home/guanwanxian/anaconda2/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/guanwanxian/.condarc
           offline mode : False

`$ /home/guanwanxian/anaconda2/envs/gpu2/bin/conda update mkl`

Traceback (most recent call last):
      File "/home/guanwanxian/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", l
ine 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/guanwanxian/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "/home/guanwanxian/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.p
y", line 65, in execute
        install(args, parser, 'update')
      File "/home/guanwanxian/anaconda2/lib/python2.7/site-packages/conda/cli/install.py",
line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/g
uanwanxian/anaconda2/pkgs/mkl-11.3.3-0.tar.bz2.part' for writing (HTTPSConnectionPool(host=
'mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out.).

I have tryed many times and still get the errors, where is the problem?

**Comment by kalefranz** [comment]
It appears you have a connection problem with your server mirrors.tuna.tsinghua.edu.cn
