### ISSUE TITLE
Conda environment using default global packages instead of throwing an error is unexpected behaviour

### ISSUE THREAD

**Issue by kdheepak** [conda/conda#3452]
Hi all, I've been using conda environment for a while, but the recent version seems to have caused some new changes that can cause confusion. I've illustrated this below with an example.

Let's say I create an environment with Python2 called testing-env

```
> conda create -n testing-env python=2
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/$USER/anaconda/envs/testing-env:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-2
    pip:        8.1.2-py27_0
    python:     2.7.12-1
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################################################################################################################################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate testing-env
#
# To deactivate this environment, use:
# > source deactivate testing-env
#
```

I can activate this environment by the following.

```
> source activate testing-env
```

The python executable exists in the environment. This is good and expected.

```
(testing-env) > which python
/Users/$USER/anaconda/envs/testing-env/bin/python
```

But when I run the following command, I get the global jupyter executable. This is not expected. 

```
(testing-env) > which jupyter
/Users/$USER/anaconda/bin/jupyter
```

My first explanation of this was that jupyter was somehow preloaded with anaconda. But the same thing happens with nosetests and py.test!

```
(testing-env) > which nosetests
/Users/$USER/anaconda/bin/nosetests

(testing-env) > which py.test
/Users/$USER/anaconda/bin/py.test
```

It also finds packages I've installed like the one below!

```
(testing-env) > which fono
/Users/$USER/anaconda/bin/fono
```

Inside a new environment, I can now run jupyter notebook, import fono and everything would work completely fine. A user could be completely oblivious to which version of the package they are using.

Let's say I want to use a different version of jupyter, I can install jupyter inside the environment. 

```

(testing-env) > conda install jupyter -y
...

```

But on installing the environment, jupyter is still linked to the global environment.

```
(testing-env) > which jupyter
/Users/$USER/anaconda/bin/jupyter
```

If I deactivate and activate the environment, I now can access my installation within the environment.

```

(testing-env) > source deactivate

> source activate testing-env

(testing-env) > which jupyter
/Users/$USER/anaconda/envs/testing-env/bin/jupyter

```

This is planned behaviour for conda env? I find this unintuitive. I propose raising an `ImportError` if a user is in an environment.

**Comment by kalefranz** [comment]
I'm not aware of a change we've made to this behavior yet, but something might have slipped through.  I'm guessing that your root environment is on your `PATH` multiple times.

However, what you describe is actually a planned change to be made in the near future.

> But when I run the following command, I get the global jupyter executable. This is not expected.

It actually should be expected. This is how `PATH` resolution works.  Search for the requested executable in the first location, if not found there search in the next location, on through the chain. For example, you can `conda install git` in the root env or in an activated env, and it will shadow the git on path for your system.

It's actually no different with conda's python version.  Your python at `/Users/$USER/anaconda/bin/python` shadows the system python at `/usr/bin/python`.

In general, you might find the `-a` flag helpful when using `which`.

    which -a python

will show you all locations of python currently on `PATH`.

> But on installing the environment, jupyter is still linked to the global environment.

This is where we potentially have a legitimate bug.  However, the locations of executables on `PATH` are often cached by the shell.  Before we declare this a bug, try to reproduce, but after installing jupyter in your activated env, but before trying `which jupyter` run `hash -r` (if your shell is bash) or `rehash` (if your shell is zsh).  So the sequence is

```
conda create -n testing-env python=2
source activate testing-env
which -a jupyter
conda install jupyter -y
hash -r
which -a jupyter
```

> If I deactivate and activate the environment, I now can access my installation within the environment.

That's because the activate script does the `hash -r` for you :)

**Comment by kdheepak** [comment]
Great answer! I tested the sequence, and `which -a jupyter` returns one instance of jupyter (global) before running `conda install jupyter -y` and two instances (inside the environment and global) after. 

However, I still think that if the package does not exist in an environment it should raise an ImportError. For instance, previously I could guarantee a package would work in a another person's computer if I created a fresh environment and installed it in there. Regardless of what my global packages are, I would be able to replicate a user installing a package I'm developing. With the current setup (or the planned change for the future) creating a fresh environment will no longer ensure this. 

The way I've been looking at it is that the purpose of a virtual environment is to isolate ties to the global environment. Thoughts? Do you have an alternative for the above use case?

**Comment by kdheepak** [comment]
PS - My PATH variable does not contain more an one instance of anaconda

```
> echo $PATH
/Users/$USER/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin
```

This is my `$PATH` variable inside the environment

```
/Users/$USER/anaconda/envs/testing-env/bin:/Users/$USER/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin
```

Alternatively, would it be possible to add a flag in the virtual environment creation process such that it replaced the existing anaconda-PATH instead of appending to it?

**Comment by kdheepak** [comment]
Are there any updates on this? It is becoming increasing difficult to isolate Python3 and Python2 workflows on a single machine. If I create a fresh Python3 environment and run ipython in it, I get an iPython kernel with Python 2.7.12

```
$ conda create env -n python3-env -y

$ source activate python3

(python-3) $ ipython

Python 2.7.12 |Anaconda 2.5.0 (x86_64)| (default, Jul  2 2016, 17:43:17)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by kalefranz** [comment]
Why wouldn't you make your create command

    conda create env -n python3-env -y python=3 ipython

?

**Comment by h2oworker** [comment]
My issue / question [https://github.com/ContinuumIO/anaconda-issues/issues/1429#issuecomment-330588673](https://github.com/ContinuumIO/anaconda-issues/issues/1429#issuecomment-330588673) seems to be similar to the issue being discussed here.

**Comment by kalefranz** [comment]
@h2oworker Not really. These discussions are all related to bash or other Bourne-like shells.  W.R.T. your comment in anaconda-issues, you need to make sure you're using the Anaconda Prompt instead of cmd.exe, or activating environments accordingly after opening cmd.exe.

**Comment by Mottotime** [comment]
I've experienced similar issues, too. It should throw an error instead of using global packages secretely.

**Comment by fredRos** [comment]
The hint with `hash -r` saved my day. I didn't know about it. I had just installed `pytest` in a python3 conda env but when I ran `py.test`, it would take the system's `py.test` (python 2.7) so I was testing the prebuilt python2 version of my code that hadn't changed in a long time instead of my in-development python3 version. Very annoying
