### ISSUE TITLE
BUG: DryRunExit raised with `conda create --dry-run`

### ISSUE THREAD

**Issue by binarysubstrate** [conda/conda#3455]
# Steps to Reproduce 
Exception raised with conda versions 4.2.6 and 4.2.7 using various combinations of `conda create --dry-run`:

- `conda create --dry-run  --no-default-packages -n dashboard python=3.5`
- `conda create --dry-run  --no-default-packages -n dashboard python=3`
- `conda create --dry-run  -n dashboard python=3.5`
- `conda create --dry-run  -name dashboard`

# Error Output
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : linux-64
>           conda version : 4.2.6
>        conda is private : False
>       conda-env version : 4.2.6
>     conda-build version : 1.20.0
>          python version : 3.5.2.final.0
>        requests version : 2.9.1
>        root environment : /home/michelle/anaconda3  (writable)
>     default environment : /home/michelle/anaconda3
>        envs directories : /home/michelle/anaconda3/envs
>           package cache : /home/michelle/anaconda3/pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
>                           https://repo.continuum.io/pkgs/free/noarch/
>                           https://repo.continuum.io/pkgs/pro/linux-64/
>                           https://repo.continuum.io/pkgs/pro/noarch/
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ /home/michelle/anaconda3/bin/conda create --dry-run --no-default-packages -n dashboard python=3.5`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/home/michelle/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/home/michelle/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
>         exit_code = args.func(args, p)
>       File "/home/michelle/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
>         install(args, parser, 'create')
>       File "/home/michelle/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 398, in install
>         common.confirm_yn(args)
>       File "/home/michelle/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 433, in confirm_yn
>         raise DryRunExit
>     TypeError: __init__() missing 1 required positional argument: 'message'

**Comment by kalefranz** [comment]
resolved with #3457
