### ISSUE TITLE
conda 4.2.7 error

### ISSUE THREAD

**Issue by joonpark72** [conda/conda#3458]
(root) C:\Users\Joonho>conda clean -a --dry-run
Cache location:
There are no tarballs to remove
Cache location:
There are no unused packages to remove
svn cache (C:\Users\Joonho\Anaconda3\conda-bld\svn_cache)
Size:                                           0 B

git cache (C:\Users\Joonho\Anaconda3\conda-bld\git_cache)
Size:                                           0 B

hg cache (C:\Users\Joonho\Anaconda3\conda-bld\hg_cache)
Size:                                           0 B

source cache (C:\Users\Joonho\Anaconda3\conda-bld\src_cache)
Size:                                           0 B

Total:                                          0 B
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : C:\Users\Joonho\Anaconda3  (writable)
    default environment : C:\Users\Joonho\Anaconda3
       envs directories : C:\Users\Joonho\Anaconda3\envs
          package cache : C:\Users\Joonho\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
                          https://conda.anaconda.org/conda-forge/win-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://conda.binstar.org/menpo/win-64/
                          https://conda.binstar.org/menpo/noarch/
            config file : C:\Users\Joonho\.condarc
           offline mode : False

`$ C:\Users\Joonho\Anaconda3\Scripts\conda-script.py clean -a --dry-run`

    Traceback (most recent call last):
      File "C:\Users\Joonho\Anaconda3\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Joonho\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Joonho\Anaconda3\lib\site-packages\conda\cli\main_clean.py", line 459, in execute
        rm_source_cache(args, **json_result['source_cache'])
      File "C:\Users\Joonho\Anaconda3\lib\site-packages\conda\cli\main_clean.py", line 405, in rm_source_cache
        confirm_yn(args)
      File "C:\Users\Joonho\Anaconda3\lib\site-packages\conda\cli\common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'

**Comment by kalefranz** [comment]
This issue has been resolved.  Thanks for the report.
