### ISSUE TITLE
Custom channel with HTTP auth broken in conda 4.2

### ISSUE THREAD

**Issue by lschr** [conda/conda#3459]
Previously, it was possible to have a custom channel with basic HTTP auth using the `https://<user>:<pass>@<path>` syntax. With conda 4.2, this is not the case anymore. Instead, when such a channel is present in `condarc`, one gets 401 errors whenever trying to install or update something. I identified two reasons:
- Since `urllib3`'s `parse_url` is used instead of `urllib.parse.urlparse` (in common/url.py), the username and password are stripped from the `netloc` attribute and the information is therefore lost.
- Even if username and password are retained as part of the URL (e. g. by using `urllib.parse.urlparse` as I did for testing purposes), authentification is not successful, because (in connection.py) the `CondaSession` class sets `self.auth = BinstarAuth()`, apparently overriding the credentials given as part of the URL. If I remove the line, the HTTP auth works again.

Apart from that, #2804 is still true for conda 4.2.

**Comment by Zaharid** [comment]
In addition, it is not possible to use basic_auth with a `.netrc` file, which was possible in 4.1.

**Comment by kalefranz** [comment]
addressed in #3550

**Comment by kalefranz** [comment]
@lschr, @elehcim, @Zaharid 

Conda 4.2.10 is available on the `conda-canary` channel, and it should have a fix for this issue.  If you have time, please help test it.

    conda config --prepend channels conda-canary
    conda update conda

We'll likely be releasing this build to the general availability defaults channel on Friday.

**Comment by Zaharid** [comment]
Seems to work for me, both with the explicit url and the `.netrc` file. Can I assume that basic auth is officially supported?

**Comment by lschr** [comment]
:+1: Looks like it is working for me as well (with `https://username:password@path` in `.condarc`). Thank you very much @kalefranz @elehcim for your work!

**Comment by elehcim** [comment]
Ok, I tested it and it seems okay for my use case. Thank you
