### ISSUE TITLE
CIO_TEST not working correctly

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#3463]
In conda 4.2.7, `CIO_TEST` is prepending the URL's (which are read from the `cio_test.py` module) to the list of channel URL's.  This is changing the old behavior, which is that only the cio_test URL's are used.  The reason for this behavior is to ensure that when testing any other channel are ignored.

**Comment by kalefranz** [comment]
I see.  In the `cio_test` module, if we change the environment variable to set `CONDA_DEFAULT_CHANNELS` instead of `CONDA_CHANNELS`, and no other channels are set, then I think that might be the original behavior.

**Comment by ilanschnell** [comment]
Yes, this works, but only if no other channels are set.  It should not matter if other channels are set.  Is there a way to restore the old behavior?
