### ISSUE TITLE
activate environment messing up path?

### ISSUE THREAD

**Issue by TidyData** [conda/conda#3464]
for some reason on my machine the command 
`pip install django-compressor`
works but 
`activate [environment name]`
then 
`pip install django-compressor` does not work
I have updated conda to the latest version 4.2.7 and it still errors out

I believe it has to do with the ordering in the path.  I tried to reorder the path though and it still occurred.
`
c:\anaconda3\envs[environment name]\include\pyconfig.h(243): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory

error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
`
I wish I could just conda install everything but I still do not know how to build conda packages and cannot find some conda packages.  Conda is Amazing though!

note: if testing this out, might need to install rcssmin with
`pip install rcssmin==1.0.6 --install-option="--without-c-extensions"`

windows 7 - 64 bit

**Comment by kalefranz** [comment]
Make sure `where python` and `where pip` match locations. Otherwise `conda install pip`:)
