### ISSUE TITLE
Unable to update --all after conda update to 4.2.7 on linux64

### ISSUE THREAD

**Issue by remygithub** [conda/conda#3472]
I am encountering the following error when trying to **`conda update --all`**:
<code bash>
An unexpected error has occurred.
Please consider posting the following information to the conda GitHub issue tracker at:     https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/Anaconda/anaconda3  (writable)
    default environment : /opt/Anaconda/anaconda3
       envs directories : /opt/Anaconda/anaconda3/envs
          package cache : /opt/Anaconda/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/remy/.condarc
           offline mode : False

`$ /opt/Anaconda/anaconda3/bin/conda update --dry-run --all`

    Traceback (most recent call last):
      File "/opt/Anaconda/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/Anaconda/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/opt/Anaconda/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/opt/Anaconda/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 398, in install
        common.confirm_yn(args)
      File "/opt/Anaconda/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'

</code>

I get the same error even after a fresh reinstall of **`conda 4.1.1`** and subsequently updating it to 4.2.7.

**Additional info:**
The **` --dry-run`** shows the following list of updates/downgrades:
<code bash>
remy@hercules2:/opt/Anaconda/anaconda3$ conda update --dry-run --all

Package plan for installation in environment /opt/Anaconda/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    expat-2.1.0                |                0         365 KB
    icu-54.1                   |                0        11.3 MB
    libgcc-5.2.0               |                0         1.1 MB
    libxcb-1.12                |                0         1.5 MB
    dbus-1.10.10               |                0         2.4 MB
    alabaster-0.7.9            |           py35_0          11 KB
    boto-2.42.0                |           py35_0         1.4 MB
    gstreamer-1.8.0            |                0         2.6 MB
    mistune-0.7.3              |           py35_0         653 KB
    pyyaml-3.12                |           py35_0         341 KB
    setuptools-27.2.0          |           py35_0         526 KB
    xlsxwriter-0.9.3           |           py35_0         193 KB
    babel-2.3.4                |           py35_0         4.8 MB
    gst-plugins-base-1.8.0     |                0         3.1 MB
    pickleshare-0.7.4          |           py35_0           9 KB
    traitlets-4.3.0            |           py35_0         124 KB
    jupyter_core-4.2.0         |           py35_0          52 KB
    qt-5.6.0                   |                0        43.9 MB
    pyqt-5.6.0                 |           py35_0         5.4 MB
    matplotlib-1.5.3           |      np111py35_0         8.4 MB
    notebook-4.2.3             |           py35_0         5.0 MB
    ------------------------------------------------------------
                                           Total:        93.0 MB

The following NEW packages will be INSTALLED:

    dbus:             1.10.10-0
    expat:            2.1.0-0
    gst-plugins-base: 1.8.0-0
    gstreamer:        1.8.0-0
    icu:              54.1-0
    libgcc:           5.2.0-0
    libxcb:           1.12-0

The following packages will be UPDATED:

    alabaster:        0.7.8-py35_0      --> 0.7.9-py35_0
    babel:            2.3.3-py35_0      --> 2.3.4-py35_0
    boto:             2.40.0-py35_0     --> 2.42.0-py35_0
    jupyter_core:     4.1.1-py35_0      --> 4.2.0-py35_0
    matplotlib:       1.5.1-np111py35_0 --> 1.5.3-np111py35_0
    mistune:          0.7.2-py35_0      --> 0.7.3-py35_0
    notebook:         4.2.2-py35_0      --> 4.2.3-py35_0
    pickleshare:      0.7.3-py35_0      --> 0.7.4-py35_0
    pyqt:             4.11.4-py35_4     --> 5.6.0-py35_0
    pyyaml:           3.11-py35_4       --> 3.12-py35_0
    qt:               4.8.7-4           --> 5.6.0-0
    setuptools:       26.1.1-py35_0     --> 27.2.0-py35_0
    traitlets:        4.2.2-py35_0      --> 4.3.0-py35_0
    xlsxwriter:       0.9.2-py35_0      --> 0.9.3-py35_0

The following packages will be DOWNGRADED due to dependency conflicts:

    spyder:           2.3.9-py35_1      --> 2.3.9-py35_0

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:    https://github.com/conda/conda/issues
</code>
**The previously listed error follows the above listing.**

**Comment by kalefranz** [comment]
resolved with #3457
