### ISSUE TITLE
Windows hard linking error

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#3477]
Hey folks, this issue came to me on a back channel. Looks like under certain circumstances Windows hard linking fails. Perhaps the inclusion of a forward slash in the path is a culprit, who knows. Attached is the output.  I had to clean out some private information here, and the user has since deleted and reinstalled, so I'm afraid there's nothing else we can offer to debug this.

```
$ conda update conda
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at c:\Users\ZZZ\AppData\Local\Continuum\Anaconda2:
#
conda                     4.2.7                    py27_0

$ conda install anaconda
    Fetching package metadata .........
    Solving package specifications: ..........

    Package plan for installation in environment c:\Users\ZZZ\AppData\Local\Continuum\Anaconda2:

    The following NEW packages will be INSTALLED:

        anaconda:           4.0.0-np110py27_0
        anaconda-navigator: 1.1.0-py27_0
        blaze:              0.9.1-py27_0
        bokeh:              0.11.1-py27_0
        conda-manager:      0.3.1-py27_0
        dask:               0.8.1-py27_0
        ipykernel:          4.3.1-py27_0
        jupyter:            1.0.0-py27_2
        jupyter_client:     4.2.2-py27_0
        jupyter_console:    4.1.1-py27_0
        matplotlib:         1.5.1-np110py27_0
        notebook:           4.1.0-py27_2
        odo:                0.4.2-py27_0
        partd:              0.3.2-py27_1
        pyopenssl:          0.15.1-py27_2
        qtconsole:          4.2.0-py27_1
        scikit-image:       0.12.3-np110py27_0
        sockjs-tornado:     1.0.1-py27_0
        spyder:             2.3.8-py27_1

    Proceed ([y]/n)?
    Linking packages ...
CondaOSError: OS error: failed to link (src=u'c:\\Users\\ZZZ\\AppData\\Local\\Continuum\\Anacond
a2\\pkgs\\bokeh-0.11.1-py27_0\\Scripts/bokeh-script.py-server', dst='c:\\Users\\ZZZ\\AppData\\Lo
cal\\Continuum\\Anaconda2\\Scripts/bokeh-script.py-server', type=1, error=CondaOSError: OS error: w
in32 hard link failed
)
```

**Comment by wulmer** [comment]
I am experiencing the same problem. I think I can remember a related discussion/issue about an invalid filename where the `-script.py` for the command line entry point was not added correctly. 

Here, it also looks like the filename should actually be `bokeh-server-script.py` instead of `bokeh-script.py-server`. Might be a `conda-build` issue?

**Comment by wulmer** [comment]
I tried downgrading conda from 4.2.9 --> 4.1.12. This at least doesn't make conda crash, but prints an error log message and then continues. The problem with the non-existing hard link however still exists.

**Comment by wulmer** [comment]
I found the source of this problem: If you have a look into the `bokeh-0.11.1-py27_0.tar.bz2` file (or into the unzipped folder with the same name) under `info/files`, you will find a list of files that should be contained in this package. 

However the `info/files` entry for `is **invalid** !! It ends with:

    Scripts/bokeh-script.py
    Scripts/bokeh-script.py-server
    Scripts/bokeh-server.bat
    Scripts/bokeh.bat

You can clearly see here that the third last line is invalid. The correct filename would be `Scripts/bokeh-server-script.py`.

**Comment by wulmer** [comment]
I think this is more an Anaconda issue than a conda problem. Any admin here to move/address this in Anaconda-issues? Or should I cross-post this to Anaconda issues?

**Comment by gary-dalton** [comment]
I just ran into a Windows hardlink error that killed my Anaconda. I was able to recover using:

`conda list --revisions`
`conda install --revision 3`

Right now, I am running my revision 3 and am able to reproduce the error. Here is the error message:

 CondaOSError: OS error: failed to link (src='C:\\Users\\Gary\\Anaconda3\\pkgs\\bokeh-0.11.1-py35_0\\Scripts/bokeh-script
.py-server', dst='C:\\Users\\Gary\\Anaconda3\\Scripts/bokeh-script.py-server', type=1, error=CondaOSError: OS error: win
32 hard link failed
)

**Comment by nmgzjf** [comment]
Just as wulmer said that the info/files entry for the bokeh-server script is invalid. 
Modify the entry Scripts/bokeh-script.py-server to Scripts/bokeh-server-script.py. Then rerun the install command, the packages will be successfully installed.

**Comment by gary-dalton** [comment]
Sorry nmgzjf and wulmer. My unmodified info/files entry  for Scripts is:
Scripts/bokeh-script.py
Scripts/bokeh-server-script.py
Scripts/bokeh-server.exe
Scripts/bokeh.exe

Still get error:

    conda install bokeh=0.11.1
    Fetching package metadata .........
    Solving package specifications: ..........
    
    Package plan for installation in environment C:\Users\Gary\Anaconda3:
    
    The following packages will be UPDATED:
    
       bokeh: 0.11.0-py35_0 --> 0.11.1-py35_0
    
    Unlinking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Linking packages ...
    [bokeh               ]|                                                  |   0%
    
    CondaOSError: OS error: failed to link (src='C:\\Users\\Gary\\Anaconda3\\pkgs\\bokeh-0.11.1-py35_0\\Scripts/bokeh-script.py-server', dst='C:\\Users\\Gary\\Anaconda3\\Scripts/bokeh-script.py-server', type=1, error=CondaOSError: OS error: win32 hard link failed)

**Comment by gary-dalton** [comment]
The above does work. I was looking at the incorrect file (for version 0.11.0). After correcting the above file, running `conda install bokeh=0.11.1` and then `conda update anaconda` successfully complete.

**Comment by debapratimsaha** [comment]
I did what @wulmer pointed and @gary-dalton told above. However, I still get the same hard link error (even showing the changes to the filename that I made to the `info/file`)

**Comment by kalefranz** [comment]
Also, conda 4.3 will tell you when a package is corrupt like this.

**Comment by nagasai-iitr** [comment]
excuse me People I'm new to coding... can I know  how @nmgzjf  modified the entry scripts
