### ISSUE TITLE
conda info displays wrong version for conda-env

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3479]
It is displaying the package version for conda in both conda and conda-env.

**Comment by kalefranz** [comment]
That's intentional.  As of conda 4.2, `conda_env` now rides along with `conda`, and they're versioned together.  The conda-env 2.6.0 package is actually just an empty package to help with the migration.

**Comment by mcg1969** [comment]
Maybe we should change the version number of the empty package to 4.2.0 ;-) maybe we should take the version number of the empty package
