### ISSUE TITLE
Issues with conda behind proxy (without username/password)

### ISSUE THREAD

**Issue by AbdealiJK** [conda/conda#3481]
I am using Windows 64bit computer with:

```
>conda --version
conda 4.1.4
>python --version
Python 3.5.1 :: Anaconda 4.1.0 (64-bit)
```
#### With .condarc proxy

I have set my conda proxy at `.condarc`:

```
proxy_servers:
    http: http://proxy.example.com:8888
    https: https://proxy.example.com:8888
```

I then try to update a package in conda:

```
>conda update nb_conda_kernels
Fetching package metadata ...
https proxy username: <press enter as I don't have a username>

https proxy username: Password: <press enter as I don't have a password>

https proxy username: Password: <just keep pressing enter a few times>
```
#### Trying to manually download package

I even tried to copy the archive of the package into my `pkgs`  folder from http://repo.continuum.io/pkgs/free/win-64/ and ran with `--unknown` as I saw in another issue. And it gives:

```
>conda update nb_conda_kernels --unknown
Fetching package metadata ...
https proxy username: <press enter as I don't have a username>

https proxy username: Password:<press enter as I don't have a password>

https proxy username: Password: <just keep pressing enter a few times>
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
..
```

Also, after I enter the username/password twice, it just hangs. Doesnt respond to Ctrl+C, ctrl+z, etc. and to stop it I have to close the cmd prompt.
#### With HTTP_PROXY env variables.

I also have HTTP_PROXY and HTTPS_PROXY set up in the environment variables. When I remove those lines in .condarc and try it, it says:

```
>conda update nb_conda_kernels
Fetching package metadata ...Could not find a proxy for 'https'. See
http://conda.pydata.org/docs/html#configure-conda-for-use-behind-a-proxy-server
for more information on how to configure proxies.
```
#### Issues
1. I am not sure why it asks me for the password to begin with. Git, pip, etc do not ask me for the password and works fine.
2. I am not sure why it is not using HTTP_PROXY and HTTPS_PROXY as environment variables.
3. I am not sure why I can't kill the stuck conda operation with Ctrl-C.

**Comment by cossio** [comment]
Is there a way to tell conda that my proxy _does not have a password or username_.

**Comment by kalefranz** [comment]
Proxy issues and resolution will be tracked with https://github.com/conda/conda/issues/3481
