### ISSUE TITLE
issue with disabling ssl_verify

### ISSUE THREAD

**Issue by pilgrim6588** [conda/conda#3482]
P:\\ is our corporate net drive for userdata

SSL_VERIFY needs to be disabled probably because of issues with our authenticated firewall
(which also does not work with pip, regardless of seeting system variables etc.) :

Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:590): https://repo.continuum.io/pkgs/free/win-64/mingw-4.7-1.tar.bz2

-->here:
D:\Downloads\Programmieren\Python>conda config --set ssl_verify false
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\Apps\Programmieren\Anaconda2\Scripts\conda-script.py", line 5, in <mo
dule>
    sys.exit(main())
  File "D:\Apps\Programmieren\Anaconda2\lib\site-packages\conda\cli\main.py", li
ne 120, in main
    exit_code = args_func(args, p)
  File "D:\Apps\Programmieren\Anaconda2\lib\site-packages\conda\cli\main.py", li
ne 130, in args_func
    exit_code = args.func(args, p)
  File "D:\Apps\Programmieren\Anaconda2\lib\site-packages\conda\cli\main_config.
py", line 212, in execute
    execute_config(args, parser)
  File "D:\Apps\Programmieren\Anaconda2\lib\site-packages\conda\cli\main_config.
py", line 338, in execute_config
    with open(rc_path, 'w') as rc:
IOError: [Errno 2] No such file or directory: 'P:\\.condarc'

D:\Downloads\Programmieren\Python>

**Comment by kalefranz** [comment]
I've observed this error when an antivirus program (in my case Kaspersky) was inserting it's own CA bundle.  Output from a verbose `curl` actually showed what was going on.  Once I disabled that "feature" of the antivirus, the problem went away.
