### ISSUE TITLE
update Anaconda when there is no internet

### ISSUE THREAD

**Issue by fluency03** [conda/conda#3483]
I would like to update Anaconda on a Linux server when there is not internet but only the newest Anaconda package.

I know that when there is internet, I can do:

```
conda update conda
conda update anaconda
```

Now, I do not have internet but only the newest Anaconda package. Can I simply remove all the Anaconda by:

```
rm -rf ~/anaconda2
```

and install it again by: 

```
bash /path/to/Anaconda2-4.1.1-Linux-x86_64.sh
```

???

Thanks!

**Comment by kalefranz** [comment]
yes
