### ISSUE TITLE
Conda search will list packages for other python versions

### ISSUE THREAD

**Issue by zhangyi-hu** [conda/conda#3484]
When I use conda search to show information a particular package, it will dump packages for all python versions, while I'm only interested in one version--the version of my currently python.

For instance, this is what I got for pyqt

pyqt                      4.10.4                   py26_0  defaults
                             4.10.4                   py27_0  defaults
                             4.10.4                   py33_0  defaults
                             4.10.4                   py34_0  defaults
                             4.10.4                   py26_1  defaults
                             4.10.4                   py27_1  defaults
                             4.10.4                   py33_1  defaults
                             4.10.4                   py34_1  defaults
                             4.11.4                   py27_0  defaults
                             4.11.4                   py35_0  defaults
                             4.11.4                   py27_2  defaults
                             4.11.4                   py34_2  defaults
                             4.11.4                   py35_2  defaults
                             4.11.4                   py27_3  defaults
                             4.11.4                   py34_3  defaults
                             4.11.4                   py35_3  defaults
                             4.11.4                   py27_4  defaults
                             4.11.4                   py34_4  defaults
                             4.11.4                   py35_4  defaults
                             4.11.4                   py27_5  defaults
                             4.11.4                   py34_5  defaults
                             4.11.4                   py35_5  defaults
                          \*  4.11.4                   py27_6  defaults
                             4.11.4                   py34_6  defaults
                             4.11.4                   py35_6  defaults
                             4.11.4                   py27_7  defaults
                             4.11.4                   py34_7  defaults
                             4.11.4                   py35_7  defaults
                          .  5.6.0                    py27_0  defaults
                             5.6.0                    py34_0  defaults
                             5.6.0                    py35_0  defaults

I don't think I need information for python3, since I'm using python 2. 
This problem currently prevents me from searching for a package with many other packages containing the same keyword. My screen will be flooded with so much irrelevant lines that makes it hard to spot what I really need.

**Comment by hzzyyy** [comment]
Also, I believe the user won't be interested in the version older than the currently used one. I think it would be more user friendly to hide those by default, and display them if the use requested explicitly.
