### ISSUE TITLE
Cannot install tensor flow

### ISSUE THREAD

**Issue by billchenxi** [conda/conda#3486]
Can you help me to install tensor flow?

`Xis-MacBook-Pro:~ bill$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
Xis-MacBook-Pro:~ bill$ conda search tensorflow --channel conda-forge
WARNING conda.connection:get_binstar_token(106): Warning: could not capture token from anaconda-client (RecursionError('maximum recursion depth exceeded while calling a Python object',))
WARNING conda.connection:get_binstar_token(106): Warning: could not capture token from anaconda-client (RecursionError('maximum recursion depth exceeded while calling a Python object',))
tensorflow                   0.7.1                    py27_0  conda-forge  
                             0.7.1                    py35_0  conda-forge  
                             0.8.0                    py27_0  conda-forge  
                             0.8.0                    py34_0  conda-forge  
                             0.8.0                    py35_0  conda-forge  
                             0.9.0                    py27_0  conda-forge  
                             0.9.0                    py34_0  conda-forge  
                             0.9.0                    py35_0  conda-forge  
                             0.10.0                   py27_0  conda-forge  
                             0.10.0                   py34_0  conda-forge  
                             0.10.0                   py35_0  conda-forge  
Xis-MacBook-Pro:~ bill$ conda install tensorflow
WARNING conda.connection:get_binstar_token(106): Warning: could not capture token from anaconda-client (RecursionError('maximum recursion depth exceeded while calling a Python object',))
WARNING conda.connection:get_binstar_token(106): Warning: could not capture token from anaconda-client (RecursionError('maximum recursion depth exceeded while calling a Python object',))

Package plan for installation in environment /Users/bill/miniconda3:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-env-2.5.2 | py35_0          27 KB  conda-forge |
| conda-4.1.11 | py35_1         390 KB  conda-forge |
| protobuf-3.0.0b2 | py35_0         172 KB  conda-forge |
| pbr-1.10.0 | py35_0          99 KB  conda-forge |
| mock-2.0.0 | py35_0         101 KB  conda-forge |
| tensorflow-0.10.0 | py35_0        26.6 MB  conda-forge |

```
------------------------------------------------------------
                                       Total:        27.4 MB
```

The following NEW packages will be INSTALLED:

```
mock:       2.0.0-py35_0   conda-forge
pbr:        1.10.0-py35_0  conda-forge
protobuf:   3.0.0b2-py35_0 conda-forge
tensorflow: 0.10.0-py35_0  conda-forge
```

The following packages will be SUPERCEDED by a higher-priority channel:

```
conda:      4.2.7-py35_0               --> 4.1.11-py35_1 conda-forge
conda-env:  2.6.0-0                    --> 2.5.2-py35_0  conda-forge
```

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : osx-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : not installed
     python version : 3.5.2.final.0
   requests version : 2.10.0
   root environment : /Users/bill/miniconda3  (writable)
default environment : /Users/bill/miniconda3
   envs directories : /Users/bill/miniconda3/envs
      package cache : /Users/bill/miniconda3/pkgs
       channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                      https://conda.anaconda.org/conda-forge/noarch/
                      https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /Users/bill/.condarc
       offline mode : False
```

`$ /Users/bill/miniconda3/bin/conda install tensorflow`

```
Traceback (most recent call last):
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 378, in download
    resp.raise_for_status()
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/conda-env-2.5.2-py35_0.tar.bz2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 387, in download
    raise CondaRuntimeError(msg)
conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/conda-env-2.5.2-py35_0.tar.bz2: https://conda.anaconda.org/conda-forge/osx-64/conda-env-2.5.2-py35_0.tar.bz2


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
    raise CondaSystemExit('Exiting', e)
  File "/Users/bill/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
    yield
  File "/Users/bill/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/conda-env-2.5.2-py35_0.tar.bz2: https://conda.anaconda.org/conda-forge/osx-64/conda-env-2.5.2-py35_0.tar.bz2`
```

**Comment by jakirkham** [comment]
xref: https://github.com/conda/conda/issues/3399 ?

**Comment by tyler-thetyrant** [comment]
`conda update -c defaults conda`
`conda install -c conda-forge tensorflow`
