### ISSUE TITLE
Conda config file usage does not match documentation

### ISSUE THREAD

**Issue by tomashek** [conda/conda#3487]
There are inconsistent behaviors in how the condarc file settings are applied.

FIRST issue:
Documentation [here](http://conda.pydata.org/docs/config.html#the-conda-configuration-file-condarc) says this:
"A .condarc file may also be located in the root environment, in which case it overrides any in the home directory."

I found that not to be the case:
~/.condarc contents:

```
offline: True
channels:
  - intel
  - defaults
```

root condarc contents:
`offline: False`

conda info:

```
Current conda install:
               platform : linux-64
          conda version : 4.2.6
       conda is private : False
      conda-env version : 4.2.6
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.9.1
       root environment : /localdisk/work/tmtomash/miniconda3  (writable)
    default environment : /localdisk/work/tmtomash/miniconda3
       envs directories : /localdisk/work/tmtomash/miniconda3/envs
          package cache : /localdisk/work/tmtomash/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/intel/linux-64/  (offline)
                          https://conda.anaconda.org/intel/noarch/  (offline)
                          https://repo.continuum.io/pkgs/free/linux-64/  (offline)
                          https://repo.continuum.io/pkgs/free/noarch/  (offline)
                          https://repo.continuum.io/pkgs/pro/linux-64/  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch/  (offline)
            config file : /nfs/site/home/tmtomash/.condarc
           offline mode : True
```

As can be seen, the user-level condarc settings for "offline" and "channels" are both in effect, and the root environment condarc is being ignored.

SECOND issue:
Perhaps this is a feature, but it is unexpected. When specifying a configuration file by using the environment variable CONDARC, conda appears to merge the settings in the listed config file with those in the user's config file, rather than using only the contents of the specified file.

Config file at /localdisk/work/tmtomash/miniconda3/envs/ipytest2/.condarc
`offline: False`

User config file is same as above.

```
Current conda install:
               platform : linux-64
          conda version : 4.2.6
       conda is private : False
      conda-env version : 4.2.6
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.9.1
       root environment : /localdisk/work/tmtomash/miniconda3  (writable)
    default environment : /localdisk/work/tmtomash/miniconda3
       envs directories : /localdisk/work/tmtomash/miniconda3/envs
          package cache : /localdisk/work/tmtomash/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/intel/linux-64/
                          https://conda.anaconda.org/intel/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /localdisk/work/tmtomash/miniconda3/envs/ipytest2/.condarc
           offline mode : False
```

As you can see, the config file is listed as the file specified in CONDARC, and offline=False as that config file states, but the "intel" channel is still being pulled from the user configuration file.

Ultimately, I would like the ability to have environment-specific condarc files so that someone can create a single environment with the "intel" channel without that meaning ALL their environments now prefer intel packages. One potential implementation was to set CONDARC=<env_root>/.condarc, perhaps when "activate"ing the environment. I'm not certain I can rely on any of the current config resolution mechanics, though.

**Comment by Lobotomik** [comment]
I want to install a dedicated miniconda installation in my users' computers to run certain packages, and would like this installation not to interfere at all with the user's own anaconda installation if existing. The dedicated, out-of-view installation would have a different set of channels including conda-forge and a channel to an in-house server hosting my packages.

If the .condarc in the root directory was read, I could do so easily. As it is, I am adding conda-forge and my package channel also to my users' main anaconda installation (if it exists).

Is there a workaround to make this work?
Is this going to be fixed anytime soon?
What does the "ent" lable mean? And "cio"?

Thanks for your help

**Comment by kalefranz** [comment]
If the docs haven't been updated following https://www.continuum.io/blog/developer-blog/conda-configuration-engine-power-users, they will be soon.
