### ISSUE TITLE
Add ability to exit non-zero if conda update PACKAGE doesn't solve to latest version

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3488]
Add as a configuration parameter that can optionally be enabled.

CC @mcg1969 @csoja

**Comment by srossross** [comment]
I think in previous discussions, we had discussed adding a `latest` version keyword e.g:
```
conda install anaconda-server=latest
```

**Comment by dsludwig** [comment]
Previous discussion in: https://github.com/conda/conda/issues/2505
