### ISSUE TITLE
conda remove --all behavior changed in 4.2.7

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#3489]
`conda remove --all` used to remove an environment if it existed, and quietly succeed if it was already gone. Now this command fails when the environment does not exist. This makes something formerly easy to do in an automated way now difficult especially in a cross-platform way on Windows.

```
C:\>conda remove --all -n nonenv
CondaEnvironmentNotFoundError: Could not find environment: nonenv .
You can list all discoverable environments with `conda info --envs`.



C:\>echo %ERRORLEVEL%
1
```

Just suppressing the error is not appealing, because there are many error modes different from the environment not existing that should trigger a failure.

**Comment by kalefranz** [comment]
Still exists in conda 4.3.x

```
kfranz@0283:~/continuum/conda *4.3.x ❯ python -m conda remove --all -n flub

CondaEnvironmentNotFoundError: Could not find environment: flub .
You can list all discoverable environments with `conda info --envs`.

```

I hate that we didn't get to this sooner.  At this point, I don't know if we should change it in the 4.3.x branch.  I'm happy to revert the behavior in 4.4 though.

**Comment by kalefranz** [comment]
Fixing in conda 4.4.0 with PR #5231
