### ISSUE TITLE
Unable to install pandas

### ISSUE THREAD

**Issue by DougMHu** [conda/conda#3495]
I apologize for the segmented screenshot of console output.
![capture1](https://cloud.githubusercontent.com/assets/10804722/18759722/a0b235a2-80b2-11e6-8916-15e2151779c6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10804722/18759724/a7285060-80b2-11e6-9fba-853fe2a78f6d.PNG)

**Comment by kalefranz** [comment]
Most permissions errors were fixed in conda 4.3.  If you're still experiencing this issue in conda 4.3.17 or later, please file a new issue with the updated stack trace.
