### ISSUE TITLE
Local `file://` channels for `conda-build` added?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3496]
When adding other channels to my `.condarc`, I'm find that `conda` is adding `file://` channels for `conda-build` to the `.condarc`. This is problematic as these directories don't exist yet. As a result, `conda` is unable to work afterwards. Here's an [example log](https://circleci.com/gh/nanshe-org/docker_nanshe/6?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) showing this failure.

**Comment by kalefranz** [comment]
@jakirkham Are you still seeing this?  I'm not sure exactly how to reproduce if you are...
