### ISSUE TITLE
Not putting sudo in front of conda update borked shebang line of conda

### ISSUE THREAD

**Issue by Lahaela** [conda/conda#3498]
This was already an issue that was closed: #242 https://github.com/conda/conda/issues/242

It happened to me again today, I forgot to put sudo in front of 'conda update conda' and something terrible happened. I'm not actually sure what specific line I messed up, but when I tried using conda or source activate I got the following error:

![image](https://cloud.githubusercontent.com/assets/5668998/18779966/2c9a50ea-8130-11e6-8ddf-eb4062bd5033.png)

I then updated the shebang line, which as stated in Issue 242 had been corrupted to some nonsense.

Then I tried doing 'conda update openssl' without sudo and what do you know,
![image](https://cloud.githubusercontent.com/assets/5668998/18780009/5bdb08a4-8130-11e6-9222-33580da93d43.png)

everything is broken. So I'm working on fixing stuff now, but figured should let you guys know this is still potentially a problem.

**Comment by Lahaela** [comment]
Update: I solved things by following the instructions [here](http://conda.pydata.org/docs/troubleshooting.html#conda-claims-installed)

This might not have been the best method, but it worked and I really needed to get from point A to point B by a tomorrow deadline. I assumed the packages were corrupted so I force installed (re-installed) both openssl and conda, and then when I normal updated other stuff it worked so I'm praying the only packages affected were openssl and conda.

That being said, the old issue of "I didn't use sudo and updated conda somehow and the shebang line was totally screwy" remains.

**Comment by mobeets** [comment]
Yep, this just happened to me as well...

**Comment by kalefranz** [comment]
Is this still an issue in recent versions of conda?  Latest is conda 4.3.17.
