### ISSUE TITLE
python.exe crashes while using QComboBox in pyQt GUI from a Miniconda install

### ISSUE THREAD

**Issue by PertuyF** [conda/conda#3501]
I am using `miniconda3 4.1.11` (reinstalled with `python 3.4`) to deploy a python software to windows users.

When I launch the GUI from the miniconda install everything works except that triggering a `QComboBox` will crash `python.exe`.

I tried several install options including the fully portable one (NoRegistry=1, InstallationType=JustMe, AddToPath=0, RegisterPython=0) and it produces the same result.

By contrast, when I use a `WinPython 64-bit python 3.4.4.3` expurgated from all unnecessary packages (basically I reduced it to the same list as my miniconda install) I do not get this bug.
The GUI works perfectly well with my main anaconda install (`python 3.4` too).

Any clue on what's the cause?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1683
