### ISSUE TITLE
package is installed but "missing"

### ISSUE THREAD

**Issue by jterning** [conda/conda#3503]
the package sfepy for osx-64 is installed:

particle:sfepy terning$ conda list
# packages in environment at /Users/terning/Projects/miniconda2:
# 

anaconda                  custom                   py27_0  
anaconda-client           1.5.1                    py27_0  
clyent                    1.2.2                    py27_0  
conda                     4.2.7                    py27_0  
conda-env                 2.6.0                         0  
enum34                    1.1.6                    py27_0  
openssl                   1.0.2h                        1  
pip                       8.1.2                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
pyparsing                 2.1.4                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.11                     py27_4  
readline                  6.2                           2  
requests                  2.10.0                   py27_0  
ruamel_yaml               0.11.14                  py27_0  
setuptools                23.0.0                   py27_0  
sfepy                     2016.1                   py27_1    fredhohman
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  

but when trying to create an environment it is missing

particle:sfepy terning$ conda create --name fe python=2.7 sfepy
Fetching package metadata .......
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
- sfepy

particle:sfepy terning$ conda info
Current conda install:

```
           platform : osx-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : not installed
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /Users/terning/Projects/miniconda2  (writable)
default environment : /Users/terning/Projects/miniconda2
   envs directories : /Users/terning/Projects/miniconda2/envs
      package cache : /Users/terning/Projects/miniconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

**Comment by soapy1** [comment]
Heya @jterning, what is the contents of your `.condarc` 
you probably want to have fredhohman in there if you don't already. So it should look something like:

```
channels:
    - fredhohman
    - defaults
```
