### ISSUE TITLE
conda Python 3.5 install freezes in PowerShell ISE

### ISSUE THREAD

**Issue by illuzioner** [conda/conda#3506]
I have Anaconda with Python 2.7 installed and I was trying to get an additional, parallel installation of Python 3.5.  I used the instructions here:
[Create a Python 3.5 environment](http://conda.pydata.org/docs/py2or3.html)

In Win7, I open a PowerShell ISE with admin privileges, and run:
`$ conda create -n python35 python=3.5 anaconda
`It prints the message "The following NEW packages will be INSTALLED", listed a bunch of packages, and then did nothing for 9 hours. No description of what was executing or stalling or anything.

I tried again several times to no avail.  I tried again with the --debug option, and yet there's still no printouts after the list of packages.

I tried running the same thing in regular PowerShell, and to my surprise it worked.  So, it looks like conda doesn't play well with PowerShell ISE.

**Comment by arvindch** [comment]
Experiencing the same issue, for quite some time.
Apparently, it's being worked on - https://github.com/conda/conda/issues/3511

**Comment by kalefranz** [comment]
We'll use #626 to track PowerShells support.
