### ISSUE TITLE
conda env export, upload not working properly

### ISSUE THREAD

**Issue by dbaugher** [conda/conda#3507]
conda env export -n NOx
name: NOx
channels: !!python/tuple
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- anaconda-client=1.5.1=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bryanwweber::cantera=2.2.1=np111py27_4
- bryanwweber::sundials=2.6.2=3
- cairo=1.12.18=6
- cloog=0.18.0=0
- clyent=1.2.2=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- functools32=3.2.3.2=py27_0
- gcc=4.8.5=6
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- gmp=5.1.2=2
- harfbuzz=0.9.39=1
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_0
- isl=0.12.2=0
- jinja2=2.8=py27_1
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.0=py27_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mistune=0.7.3=py27_0
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- mpmath=0.19=py27_1
- nb_anacondacloud=1.2.0=py27_0
- nb_conda=2.0.0=py27_0
- nb_conda_kernels=2.0.0=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- nbpresent=3.0.2=py27_0
- notebook=4.2.3=py27_0
- numpy=1.11.1=py27_0
- openssl=1.0.2i=0
- pandas=0.18.1=np111py27_0
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pyyaml=3.12=py27_0
- pyzmq=15.4.0=py27_0
- qt=4.8.7=4
- qtconsole=4.2.1=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- scipy=0.18.1=np111py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- sympy=1.0=py27_0
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.1=py27_0
- traitlets=4.3.0=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- yaml=0.1.6=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3
prefix: /home/drew/anaconda3/envs/NOx

drew@drew-ThinkPad-T460:~$ conda env upload NOx
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /home/drew/anaconda3  (writable)
    default environment : /home/drew/anaconda3
       envs directories : /home/drew/anaconda3/envs
          package cache : /home/drew/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/drew/anaconda3/bin/conda-env upload NOx`

    Traceback (most recent call last):
      File "/home/drew/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_upload.py", line 70, in execute
        env = from_file(args.file)
      File "/home/drew/anaconda3/lib/python3.5/site-packages/conda_env/env.py", line 82, in from_file
        raise exceptions.EnvironmentFileNotFound(filename)
    conda_env.exceptions.EnvironmentFileNotFound: Conda Env Exception: environment.yml file not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/drew/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/drew/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_upload.py", line 78, in execute
        raise exceptions.CondaEnvRuntimeError(msg)
    conda_env.exceptions.CondaEnvRuntimeError: Runtime error: Unable to locate environment file: environment.yml
    
    Please verify that the above file is present and that you have
    permission read the file's contents.  Note, you can specify the file
    to use by explictly adding --file=/path/to/file when calling conda env
    create.

**Comment by soapy1** [comment]
I think you need to create an `environment.yml` file to upload. So, can run
```
$ conda env export -n NOx > environment.yml
$ less environment.yml

name: NOx
channels: !!python/tuple
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- anaconda-client=1.5.1=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
...

$ conda env upload NOx
```
