### ISSUE TITLE
IRAF-tcsh/csh

### ISSUE THREAD

**Issue by dafh** [conda/conda#3509]
Hi community: I have been struggling with iraf and tcsh (it worked properly in bash) via astroconda. Does anyone have tried to use IRAF with C-shell? [Note: you need support for csh/tcsh via https://github.com/conda/conda/pull/3175]

**Comment by njalerikson** [comment]
Since IRAF is a highly specific package for astronomical work it may be more useful to ask this question on the AstroConda page (https://github.com/astroconda/astroconda). I see that there has been past discussions of IRAF there.
