### ISSUE TITLE
Fail to install conda from pip

### ISSUE THREAD

**Issue by kawing-chiu** [conda/conda#3512]
Hi. I'm using Arch linux and want to install conda (as a normal user) by pip. But the pypi conda package seems to be broken:

```
$ pip install --user -U --no-cache-dir conda
Collecting conda
  Downloading conda-4.2.7.tar.gz (235kB)
    100% |████████████████████████████████| 235kB 31kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-438oi6wu/conda/setup.py", line 32, in <module>
        from conda._vendor.auxlib import packaging  # NOQA
    ImportError: No module named 'auxlib'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-438oi6wu/conda/
```

Also, the [pypi page](https://pypi.python.org/pypi/conda) shows a conda version of `0.0.0`, which is suspicious, too.

**Comment by soapy1** [comment]
Have you tried following the instructions here: http://conda.pydata.org/docs/install/quick.html#linux-miniconda-install

**Comment by kawing-chiu** [comment]
@soapy1 Hi. I am aware of the miniconda install script. But I want to know whether I have the choice to install conda from pip and let it use my system's python compiler instead of using the magical miniconda bash install script.

**Comment by mbmilligan** [comment]
Just dropping in to note, right now http://conda.pydata.org/docs/ (source from https://github.com/conda/conda-docs/blob/master/docs/source/index.rst) advertises "pip install conda" as a supported way of installing conda, right alongside the Anaconda and Miniconda downloads. If this isn't true the docs should be changed.

**Comment by tyler-thetyrant** [comment]
It is highly recommended to follow the official conda install instruction. 
We cannot guarantee the full functionality of pip-installed conda.
