### ISSUE TITLE
When a file already exists, include package name in warning

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#3520]
I sometimes get warnings such as:

```
WARNING:conda.install:file already exists: 'C:\\conda\\envs\\test\\Lib/__pycache__/tempfile.cpython-35.pyc
```

To debug these kinds of errors, it would be helpful to include the package name in the warning.

**Comment by kalefranz** [comment]
I don't see this code in 4.2.x any more.  What version of conda are you running?
