### ISSUE TITLE
mayavi fails with pyqt5

### ISSUE THREAD

**Issue by max3-2** [conda/conda#3553]
Hi,

using the new Anaconda installer on Windows installs PyQt5 / Spyder3. 
Mayavi (e.g. conda install -c menpo mayavi=4.5.1) wont start without PyQt4.
Downgrading (conda install pyqt=4.11) breaks spyder and creates strange custom env

**Comment by kalefranz** [comment]
If you're still having the problem you report, please file a new issue at https://github.com/ContinuumIO/anaconda-issues.
