### ISSUE TITLE
Conda doesn't warn about updating to python 3.5 in Windows XP (it breaks)

### ISSUE THREAD

**Issue by rubennj** [conda/conda#3555]
I tried to update _python_ from 3.4 to 3.5 with _conda_ and I got it even though is not supported.
_Conda_ should warn that is not compatible **before** achieving!

Now _python_ says that "_Python is not a valid win32 application_" and _conda_ "_failed to create process_".

**Comment by rubennj** [comment]
Also fails in Windows server 2003.

**Comment by kalefranz** [comment]
Widows XP is no longer supported.  Behavior is undefined.  Closing.
