### ISSUE TITLE
conda update failed, error in .condarc file

### ISSUE THREAD

**Issue by GregorHerten** [conda/conda#3556]
I newly installed Anaconda and tried as a first command 
conda update conda
I got an error:
Fetching package metadata ......Could not connect to http://conda.binstar.org/myname/osx-64/
I tracked the error to the configuration file ~/.condarc
The default configuration file has
- http://conda.binstar.org/myname
  Changing it to 
  - https://conda.binstar.org/myname
    solved the problem. 
    That error in .condarc should be fixed.

**Comment by 13mshorter** [comment]
where do you go to find your config file ? sorry brand new to coding :D

**Comment by GregorHerten** [comment]
I am using a Mac and the config file is, like for most other programs in the home directory: ~/.condarc Remember that this is a hidden file, which does not appear in Finder.  
You can see them in terminal. For viewing in Finder open a terminal window and type:
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

**Comment by 13mshorter** [comment]
ok I'm on windows would anything be different?

**Comment by 13mshorter** [comment]
actually I believe our situations are different I'm going to post a picture I took of my problem maybe you could help

**Comment by 13mshorter** [comment]
![img_7173](https://cloud.githubusercontent.com/assets/22554323/19012558/86fdd63a-8787-11e6-9eeb-9ff2998d5e3b.JPG)

**Comment by 13mshorter** [comment]
sorry for it not being a screenshot and it being flipped lol
