### ISSUE TITLE
conda build fails running patchelf on a static binary

### ISSUE THREAD

**Issue by mj-harvey** [conda/conda#3557]
Hi,

We build a conda package including statically linked executables.
Recently, the conda build process has started failing because patchelf errors when called against a static binary:

$ patchelf --version
patchelf 0.9
$ file a.out
a.out: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5409b9978f2e5a5155090e1ac3d656f282848ad1, not stripped
$ patchelf --print-rpath a.out
cannot find section .dynamic
$ echo $?
1

See the travis build log at https://s3.amazonaws.com/archive.travis-ci.org/jobs/163653211/log.txt for an example

This seems to be a regression in conda-build, (it was working until a few days ago) but I haven't had opportunity yet to track down the change.

**Comment by kalefranz** [comment]
Probably best to move this issue to the conda/conda-build repo :)

**Comment by mj-harvey** [comment]
dona, apologies.
