### ISSUE TITLE
CondaRuntimeError

### ISSUE THREAD

**Issue by garima123456** [conda/conda#3558]
Current conda install:

```
           platform : win-32
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : not installed
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : C:\Users\admin\Miniconda2  (writable)
default environment : C:\Users\admin\Miniconda2
   envs directories : C:\Users\admin\Miniconda2\envs
      package cache : C:\Users\admin\Miniconda2\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-32/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-32/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : None
       offline mode : False
```

`$ C:\Users\admin\Miniconda2\Scripts\conda-script.py install mkl`

```
Traceback (most recent call last):
  File "C:\Users\admin\Miniconda2\lib\site-packages\conda\exceptions.py", li
```

ne 473, in conda_exception_handler
        return_value = func(_args, *_kwargs)
      File "C:\Users\admin\Miniconda2\lib\site-packages\conda\cli\main.py", line
 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\admin\Miniconda2\lib\site-packages\conda\cli\main_install.p
y", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\admin\Miniconda2\lib\site-packages\conda\cli\install.py", l
ine 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not ope
n u'C:\Users\admin\Miniconda2\pkgs\mkl-11.3.3-1.tar.bz2.part' for writing (
HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by garima123456** [comment]
Please help

**Comment by ABadCandy** [comment]
Maybe you can try to turn off Windows Defender protection first

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
