### ISSUE TITLE
ImportError: No module named 'ruamel_yaml'

### ISSUE THREAD

**Issue by DBaryudin** [conda/conda#3561]
I created a environment.yml file for a conda environment created on a Windows 7 64-bit and tried creating a new environment on a windows server 2009 64-bit by running the command: 
`conda env create -f environment.yml`

I get a resulting error (broken up as env_error1.png and env_error2.png).

![env_error1](https://cloud.githubusercontent.com/assets/7144543/18993695/7c73dc36-86f2-11e6-8c2c-3859f3f87450.PNG)
![env_error2](https://cloud.githubusercontent.com/assets/7144543/18993696/7c800812-86f2-11e6-8078-379254739e7f.PNG)

**Comment by kalefranz** [comment]
Can you give me the output of `conda info` and `conda list -n root`?

**Comment by DBaryudin** [comment]
![conda_info2](https://cloud.githubusercontent.com/assets/7144543/18994541/50e53cdc-86f6-11e6-8a03-a476caa00f08.PNG)
![conda_info1](https://cloud.githubusercontent.com/assets/7144543/18994542/50e60022-86f6-11e6-838b-e9520f4df9d1.PNG)
![conda_info3](https://cloud.githubusercontent.com/assets/7144543/18994543/50ea8958-86f6-11e6-8973-0ca76a3d1e62.PNG)

**Comment by kalefranz** [comment]
I think you just need `conda update conda`.

**Comment by DBaryudin** [comment]
Yes, that worked. Thank you.
