### ISSUE TITLE
cannot install tensorflow -read timed out

### ISSUE THREAD

**Issue by jiranranyaojianchi** [conda/conda#3565]
Current conda install:

```
           platform : osx-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 1.21.3
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /Users/Ariya/anaconda  (writable)
default environment : /Users/Ariya/anaconda
   envs directories : /Users/Ariya/anaconda/envs
      package cache : /Users/Ariya/anaconda/pkgs
```

`$ /Users/Ariya/anaconda/bin/conda install -c https://conda.anaconda.org/jjhelmus tensorflow`

```
Traceback (most recent call last):
  File "/Users/Ariya/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/Ariya/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/Ariya/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/Ariya/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/Ariya/anaconda/pkgs/tensorflow-0.10.0rc0-py27_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by subir0071** [comment]
start your terminal as an administrator (sudo). It does not seems to have permission on the files.

**Comment by MQCodingFarmer** [comment]
maybe your network is unstable. i had the same question today. I just try  the command like` sudo conda install -c conda-forge tensorflow` again and it solved

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.

**Comment by drv01** [comment]
issue coming again and again  even if cmd is run as administrator 
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023D4C99E828>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
