### ISSUE TITLE
"conda search" produces junk output

### ISSUE THREAD

**Issue by janssen** [conda/conda#3566]
It seems there's no way to turn off the "Fetching package metadata ....." message from conda search.  This makes it hard to use for tests, like this:

```
has_matplotlib=`conda search matplotlib --names-only`
```

And it's essentially useless output.  At the very least, a "-q" switch to suppress it would be useful.

While we're at it, "conda search" could exit with non-zero status to indicate no packages found.

**Comment by kalefranz** [comment]
If you're using it for tests, highly recommend the `--json` flag, and collecting only `stdout`.  It'll take care of the "Fetching package metadata..." issue, plus the content is structured so you can use it programatically.
