### ISSUE TITLE
Failed attempt to install libraries & packages on upgrading Anaconda 4.1 to 4.2

### ISSUE THREAD

**Issue by davidlovelace** [conda/conda#3567]
cmd.exe > conda update anaconda
Traceback attached
[Traceback_of_installation_errors_updateAnaconda41to42_1stOctober2016.txt](https://github.com/conda/conda/files/504674/Traceback_of_installation_errors_updateAnaconda41to42_1stOctober2016.txt)

**Comment by kalefranz** [comment]
Most permissions issues have been cleared up with more recent versions of conda 4.3.  Latest is conda 4.3.17.  If you're still having similar problems, please open a new ticket with the new stack trace.
