### ISSUE TITLE
Not able to update or install anything on conda

### ISSUE THREAD

**Issue by kirtanp** [conda/conda#3569]
[condaList.txt](https://github.com/conda/conda/files/504996/condaList.txt)
Hi,

The current info on `conda` is as follows:

```
               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/kirtan/anaconda  (writable)
    default environment : /home/kirtan/anaconda
       envs directories : /home/kirtan/anaconda/envs
          package cache : /home/kirtan/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False
```
I am getting
`UnsatisfiableError: The following specifications were found to be in conflict:` when I try to `conda update` or `conda install` any package. 

I saw some threads which suggested `conda update --all`. This is what I got for `conda update --all`:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - ruamel_yaml
Use "conda info <package>" to see the dependencies for each package.
```
One thread suggested force removing anaconda and then doing `conda update --all` but that also did not help. I've been having this problem since a while. Output of `conda list` is attached. Thanks.

**Comment by kirtanp** [comment]
Nothing was working so I deleted conda and  reinstalled it. Everything works now.

**Comment by ijstokes** [comment]
@kirtanp you shouldn't need to do that to get Conda working again, and if you do then there is a bug we need to find and resolve.  I'm going to create a new issue and reference this one, since I've just run into this myself.
