### ISSUE TITLE
conda command failed to create process

### ISSUE THREAD

**Issue by prakritidev** [conda/conda#3575]
conda command is not working on windows. 
all other commands working properly. 

Screenshots Windows cmd Administrator:

![conda](https://cloud.githubusercontent.com/assets/7278807/19064928/1debd080-8a2e-11e6-8b51-eea9a6c9a27a.PNG)
![conda1](https://cloud.githubusercontent.com/assets/7278807/19064934/2507f83a-8a2e-11e6-8454-cca86c8c034d.PNG)

**Comment by kalefranz** [comment]
Fixed long ago.
