### ISSUE TITLE
find_new_location() returns non-writable directories

### ISSUE THREAD

**Issue by alexhsamuel** [conda/conda#3581]
In some cases, `conda.install.find_new_location()` returns the path that is not writable to the current process. This occurs for me as follows:
1. Install conda.
2. Switch to another user, who has read but not write permission to the conda installation.
3. Configure a channel other than repo.continuum.io/pkgs/free that contains some of the same packages, _e.g._ a local mirror.
4. Try create a new environment.

I think what happens is that the `urls.txt` entries for the existing packages show `repo.continuum.io` URLs, which don't match the current channel URLs, so conda tries to download and unpack the packages again.  This confuses `find_new_location()`, which finds the package in the `package_cache`, but the directory is not writable.

I think one or two `try_write()` checks in `find_new_location()` work around this.

More broadly, if I understand correctly, `urls.txt` uses the URL to identify packages, which isn't really right if the same package might be available from more than one place.  Using the package m5sum or something similar might be better?

**Comment by kalefranz** [comment]
No longer relevant with conda 4.3.
