### ISSUE TITLE
Anaconda launcher disappeared after windows 10 anniversary update

### ISSUE THREAD

**Issue by alpha36turn** [conda/conda#3582]
Hi,

I lost the launcher and icons for Jupyter and other apps in Anaconda after the update.  I've tried Mohit's solution: 
"C:\Anaconda3\pythonw.exe" "C:\Anaconda3\Lib_nsis.py" mkmenus 
https://github.com/conda/conda/issues/1558

but got the following error:

C:\Users\alpha\Anaconda3\Lib>_nsis.py
Traceback (most recent call last):
  File "C:\Users\alpha\Anaconda3\Lib_nsis.py", line 117, in <module>
    main()
  File "C:\Users\alpha\Anaconda3\Lib_nsis.py", line 101, in main
    cmd = sys.argv[1].strip()
IndexError: list index out of range

Has anyone found a workaround to this?

Thanks!

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1682
