### ISSUE TITLE
`install --force` clobbers installed packages

### ISSUE THREAD

**Issue by soapy1** [conda/conda#3587]
Currently `conda install --force <pkg>` will clobber the package if it already exists. This seems a bit unsafe. I think that at least the package that is being forced installed should be unlinked.

This is also affecting the ability to validate the state before lilnking (pr: https://github.com/conda/conda/pull/3571). For now, we can just ignore the check if `--force` is being used.

cc/ @ilanschnell @mcg1969

**Comment by mcg1969** [comment]
Whoa, is that the case? I thought we did unlink. I consider it a bug if we do not.
