### ISSUE TITLE
conda info -e output is wrong

### ISSUE THREAD

**Issue by Scoodood** [conda/conda#3591]
I have installed both Python 3.5, and Python2.7 in my OSX with the following default setting

```
>> conda info -e
# conda environments:
#
python2                  /Users/JJ/anaconda/envs/python2
root                  *  /Users/JJ/anaconda

>> cat .bash_profile
...
export PATH="/Users/JJ/anaconda:$PATH"
```

The Python3.5 is the root environment, and is activated by default when I launch a new terminal. In order to set Python2 as a default environment I followed this [guideline](https://www.continuum.io/blog/developer-blog/python-packages-and-environments-conda) (under section "Creating and Using Environments") and change the bash PATH to 

```
export PATH="/Users/JJ/anaconda/envs/python2/bin:$PATH"
```

Now Python2.7 is default environment when I launch a new terminal but the output of `conda info -e` still show **Python3 (root) is the default environment, which is wrong.

```
>> conda info -e
# conda environments:
#
python2                  /Users/JJ/anaconda/envs/python2
root                  *  /Users/JJ/anaconda
```

What is the proper way to set default environment in conda?

**Comment by kalefranz** [comment]
> What is the proper way to set default environment in conda?

By using `source activate` on most shells (or `activate` for cmd.exe).
