### ISSUE TITLE
conda update error using Jupyter

### ISSUE THREAD

**Issue by dgibbs2016** [conda/conda#3594]
An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at: https://github.com/conda/conda/issues Include the output of the command 'conda info' in your report. Traceback (most recent call last): File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func exit_code = args.func(args, p) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 64, in execute install(args, parser, 'update') File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install execute_actions(actions, index, verbose=not args.quiet) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\plan.py", line 600, in execute_actions inst.execute_instructions(plan, index, verbose) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in execute_instructions cmd(state, arg) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD extract(arg) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\install.py", line 854, in extract exp_backoff_fn(os.rename, temp_path, path) File "C:\Users\biomass\Anaconda3\lib\site-packages\conda\install.py", line 240, in exp_backoff_fn result = fn(*args) PermissionError: [WinError 5] Access is denied: 'C:\Users\biomass\Anaconda3\pkgs\pyqt-5.6.0-py35_0.tmp' -> 'C:\Users\biomass\Anaconda3\pkgs\pyqt-5.6.0-py35_0'

**Comment by soapy1** [comment]
@dgibbs2016 could you confirm that your user has "modify" permissions on `pkgs` and `C:\Users\biomass\Anaconda3\pkgs\pyqt-5.6.0-py35_0.tmp`

This should be somewhat addressed in pr: https://github.com/conda/conda/pull/3571

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
