### ISSUE TITLE
conda update icu (54.1-0 --> 56.1-4 conda-forge)

### ISSUE THREAD

**Issue by rickedanielson** [conda/conda#3600]
In a new installation, it appears that going from icu 54 to 56 will fail unless the following is done (at least on linux):

bash Anaconda2-4.2.0-Linux-x86_64.sh
conda remove icu
rm -r $HOME/anaconda2/lib/icu
conda install -c conda-forge icu=56.1

In other words, using the first and fourth lines alone fails with:

CondaOSError: OS error: failed to link (src=u'/home/anaconda2/pkgs/icu-56.1-4/lib/icu/current', dst='/home/anaconda2/lib/icu/current', type=3, error=OSError(17, 'File exists'))

**Comment by soapy1** [comment]
@rickedanielson could you share the output from `conda info` and the full stack trace for the case when you get the error?

**Comment by rickedanielson** [comment]
> conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : $HOME/anaconda2  (writable)
    default environment : $HOME/anaconda2
       envs directories : $HOME/anaconda2/envs
          package cache : $HOME/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : $HOME/.condarc
           offline mode : False

> conda install -c conda-forge icu=56.1
Fetching package metadata .........
Solving package specifications: ..........
Package plan for installation in environment $HOME/anaconda2:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    icu-56.1                   |                4        21.9 MB  conda-forge
    conda-env-2.5.2            |           py27_0          26 KB  conda-forge
    conda-4.1.11               |           py27_1         204 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        22.1 MB
The following NEW packages will be INSTALLED:
    conda-env: 2.5.2-py27_0 conda-forge
The following packages will be UPDATED:
    icu:       54.1-0                   --> 56.1-4        conda-forge
The following packages will be SUPERCEDED by a higher-priority channel:
    conda:     4.2.9-py27_0             --> 4.1.11-py27_1 conda-forge
Proceed ([y]/n)? 
Fetching packages ...
icu-56.1-4.tar 100% |#############################################################################################################################################| Time: 0:00:39 583.39 kB/s
conda-env-2.5. 100% |#############################################################################################################################################| Time: 0:00:00 164.50 kB/s
conda-4.1.11-p 100% |#############################################################################################################################################| Time: 0:00:00 303.18 kB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|################################################################################################################################################################| 100%
Linking packages ...
CondaOSError: OS error: failed to link (src=u'$HOME/anaconda2/pkgs/icu-56.1-4/lib/icu/current', dst='$HOME/anaconda2/lib/icu/current', type=3, error=OSError(17, 'File exists'))

> ls -al $HOME/anaconda2/pkgs/icu-56.1-4/lib/icu/current $HOME/anaconda2/lib/icu/current
lrwxrwxrwx 1 here now 4 okt.  10 22:14 $HOME/anaconda2/lib/icu/current -> 54.1
lrwxrwxrwx 1 here now 4 okt.  10 22:16 $HOME/anaconda2/pkgs/icu-56.1-4/lib/icu/current -> 56.1

> cat $HOME/.condarc
channels:
  - conda-forge
  - defaults

**Comment by soapy1** [comment]
I was able to reproduce the issue and dig around a bit. It looks like there was some problem unlinking symlinks. I submitted a pr to get this fixed and will also add some tests 💃

**Comment by rickedanielson** [comment]
Thanks; closing I suppose, in favour of #3605
