### ISSUE TITLE
Could not connect to https://repo.continuum.io/pkgs/pro/                                                                                       noarch/

### ISSUE THREAD

**Issue by quintin-sally** [conda/conda#3601]
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/                                                                                       noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.

**Comment by kalefranz** [comment]
Conda has no network connection.  You have a system-level networking issue :)
