### ISSUE TITLE
activate should do a check to verify env hasn't been relocated

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#361]
Most users won't know the details of how `conda activate foo` works, and could reasonably assume that `~/anaconda/envs/foo` could be safely relocated to `~/anaconda/envs/bar` using `mv`.  This will not work, and attempts to `source activate bar` will result in error messages and an obliterated `PATH` (see bug #354).

**Comment by kalefranz** [comment]
I'm going to reopen this issue.  At the very least, `conda activate` could fail with a warning/error if the environment has been relocated.  And thus requiring a `conda activate --force` i.e. "at your own risk."
