### ISSUE TITLE
conda environments should set PIP_CONFIG_FILE to /dev/null

### ISSUE THREAD

**Issue by anntzer** [conda/conda#3611]
My `~/.config/pip/pip.conf` contains the lines

```
[install]
user = true
```

so that when working with the system python, `pip install foo` does a `--user` install (I never want to do a system-wide install, my linux package manager is there for that).  (See https://pip.pypa.io/en/stable/user_guide/#config-file.)

But when in a conda env, this doesn't make much sense -- you just want to install into the environment.  Two ways to do this would be either to set `PIP_CONFIG_FILE` to `/dev/null` or possibly provide a `pip.conf` which undoes such changes in the environment itself as the environment config file is read last (this seems harder to do -- you'd probably want to undo all possible customizations, which seems awkward).

**Comment by kalefranz** [comment]
This should actually be done as part of the activate and deactivate scripts in the pip package, not hard-coded in conda itself.  I'll move this ticket to anaconda-issues where your request can be further discussed.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1709
