### ISSUE TITLE
Conda command info failed:

### ISSUE THREAD

**Issue by fsouder** [conda/conda#3612]
I'm not very technical, but I received this error today. Have no idea how to fix it.

![image](https://cloud.githubusercontent.com/assets/6238703/19323587/8e2d22f0-908b-11e6-869f-fd20f93514ab.png)

 Don't know whether image posted. Error occurred when using Graphlab Create Launcher. Says the following:
A JavaScript error occurred in the main process
Uncaught exception:
Error: Conda command "info" failed:
command: conda info, --json
output: An unexpected error has occurred

**Comment by The-Gupta** [comment]
Uninstall and reinstall Anaconda. 
Now, try to install GraphLab Create.
