### ISSUE TITLE
conda reports missing dependencies incorrectly

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3622]
@daler commented on [Wed Oct 12 2016](https://github.com/conda/conda-build/issues/1454)

I think `conda-build` is reporting the wrong thing when it hits a certain kind of dependency conflict. This gets kind of complicated so I'll first describe it in general terms and then show a reproducible example.
## The general problem
- A depends on B and C
- B depends on C
- A is to be built for `CONDA_R=3.3.1`
- B only exists in channels for `CONDA_R=3.2`. So `conda-build` should report a dependency conflict when building A
- C exists in channels for `CONDA_R=3.3.1` and `CONDA_R=3.2`

When I try building A, I expect to get a dependency conflict error saying that B doesn't exist for `R=3.3.1`. But instead I get a dependency conflict error saying that C doesn't exist for `R=3.3.1` (when in fact it does).
### `conda info` on relevant packages

This package `bioconductor-annotationdbi` (package "C" in the example above), is built for both R3.2 and R3.3:

```
bioconductor-annotationdbi 1.32.3 0
-----------------------------------
file name   : bioconda::bioconductor-annotationdbi-1.32.3-0.tar.bz2
dependencies:
    bioconductor-biobase >=1.17.0
    bioconductor-biocgenerics >=0.15.10
    bioconductor-iranges
    bioconductor-s4vectors
    r >=2.7.0
    r-dbi
    r-rsqlite


bioconductor-annotationdbi 1.34.4 r3.3.1_1
------------------------------------------
file name   : bioconda::bioconductor-annotationdbi-1.34.4-r3.3.1_1.tar.bz2
dependencies:
    bioconductor-biobase >=1.17.0
    bioconductor-biocgenerics >=0.15.10
    bioconductor-iranges
    bioconductor-s4vectors >=0.9.25
    r 3.3.1*
    r-dbi
    r-rsqlite
```

This package `bioconductor-genomicfeatures` ("B" in the example above) is not yet built for R3.3.1. Note that it has a dependency for `bioconductor-annotationdbi`:

```
bioconductor-genomicfeatures 1.22.13 r3.2.2_0
---------------------------------------------
file name   : bioconda::bioconductor-genomicfeatures-1.22.13-r3.2.2_0.tar.bz2
dependencies:
    bioconductor-annotationdbi >=1.27.9
    bioconductor-biobase >=2.15.1
    bioconductor-biocgenerics >=0.1.0
    bioconductor-biomart >=2.17.1
    bioconductor-biostrings >=2.23.3
    bioconductor-genomeinfodb >=1.5.16
    bioconductor-genomicranges >=1.21.32
    bioconductor-iranges >=2.3.21
    bioconductor-rtracklayer >=1.29.24
    bioconductor-s4vectors >=0.7.17
    bioconductor-xvector
    r 3.2.2*
    r-dbi
    r-rcurl
    r-rsqlite
```
### the problematic `meta.yaml`

This `meta.yaml` (package "A" in the example) illustrates the problem.

``` yaml
package:
  name: demo
  version: 0.1
requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-genomicfeatures
    - r
```

When I try building it, it says that `bioconductor-annotationdbi` conflicts:

```
$ conda build . --channel r --channel bioconda
BUILD START: demo-0.1-0
updating index in: /miniconda3/conda-bld/linux-64
updating index in: /miniconda3/conda-bld/noarch
Using Anaconda Cloud api site https://api.anaconda.org
...INFO:stderrlog:...
Can't build /bioconda-recipes/tmp due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - bioconductor-annotationdbi
  - r 3.3.1*
Use "conda info <package>" to see the dependencies for each package.
```

I interpreted this to mean that `bioconductor-annotationdbi` does not exist for R3.3.1. But in fact it does -- and it's even found by `conda info`.

Curiously, if I comment out the line for `bioconductor-genomicfeatures`, it works. Note that I'm commenting out the package _not_ listed as a dependency conflict:

``` yaml
package:
  name: demo
  version: 0.1
requirements:
  build:
    - bioconductor-annotationdbi
    # - bioconductor-genomicfeatures
    - r
```

```
$ conda build . --channel r --channel bioconda
...
# Automatic uploading is disabled
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /miniconda3/conda-bld/linux-64/demo-0.1-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

```
### Finally:

So when `conda-build` reported the conflict:

```
The following specifications were found to be in conflict:
  - bioconductor-annotationdbi
  - r 3.3.1*
```

shouldn't it instead be reporting that `bioconductor-genomicfeatures` is the conflicting package?

---

@daler commented on [Wed Oct 12 2016](https://github.com/conda/conda-build/issues/1454#issuecomment-253324069)
### automatically discovered dependency is also not found after it's built

I would also like to add that if I put the `bioconductor-annotationdbi` recipe in an adjacent folder to the example recipe above, `conda-build` sees it and tries to build it. But even after building it successfully, it is not successfully identified as a dependency:

```
BUILD START: demo-0.1-0
updating index in: /miniconda3/conda-bld/linux-64
updating index in: /miniconda3/conda-bld/noarch
Using Anaconda Cloud api site https://api.anaconda.org
...INFO:stderrlog:...
The following specifications were found to be in conflict:
  - bioconductor-annotationdbi
  - r 3.3.1*
Use "conda info <package>" to see the dependencies for each package.
Missing dependency bioconductor-annotationdbi, but found recipe directory, so building bioconductor-annotationdbi first


... (bioconductor-annotationdbi builds successfully here)

TEST END: bioconductor-annotationdbi-1.34.4-r3.3.1_1
INFO:/miniconda3/lib/python3.5/site-packages/conda_build/config.py:--keep-old-work flag not specified.  Removing source and build files.

# Automatic uploading is disabled
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /miniconda3/conda-bld/linux-64/bioconductor-annotationdbi-1.34.4-r3.3.1_1.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes


... but then:


BUILD START: demo-0.1-0
updating index in: /miniconda3/conda-bld/linux-64
updating index in: /miniconda3/conda-bld/noarch
...INFO:stderrlog:...
Can't build /bioconda-recipes/tmp due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - bioconductor-annotationdbi
  - r 3.3.1*
```

---

@msarahan commented on [Thu Oct 13 2016](https://github.com/conda/conda-build/issues/1454#issuecomment-253517732)

Thanks for reporting.  Any complaint with conda's hints should be posted to the conda issue tracker, though.  Conda-build is just using conda, and has no control over this behavior.

I'm moving this issue to the conda issue tracker.

**Comment by kalefranz** [comment]
CC @mcg1969

**Comment by mcg1969** [comment]
This should be tested with the latest hint fixes. It is known that conda's hints are currently broken.

**Comment by kurtwheeler** [comment]
@mcg1969 I was running into this issue, however I upgraded conda to version 4.3.18 and conda-build to version 2.1.15 and then I got more meaningful output.

**Comment by msarahan** [comment]
I think this is fixed in recent versions of conda.  Closing.
