### ISSUE TITLE
Help with RPATH on OS X with cmake

### ISSUE THREAD

**Issue by wesm** [conda/conda#3624]
See the OS X (Travis CI) failure here: https://github.com/conda-forge/staged-recipes/pull/1732

For some reason, the `@loader_path` rpath set when the libraries are being linked is not being respected after the conda build -- the C++ shared library in question, `libpyarrow.dylib`, is in the same directory as the Cython modules. CMake is linking the transitive dependencies of `libpyarrow` so that might be a problem -- I can experiment if specifying `LINK_PRIVATE` in the `target_link_libraries` helps. If any CMake experts know the right incantation that would be most helpful.

**Comment by msarahan** [comment]
I have found it helpful to disable CMake's RPATH replacement in some cases.  It can mess up conda's efforts for relocatability.

From https://cmake.org/Wiki/CMake_RPATH_handling:

No RPATH at all
There is a builtin CMake option CMAKE_SKIP_RPATH, if it is enabled all other RPATH related options are ignored, no RPATH is built into anything.

**Comment by msarahan** [comment]
PS: this kind of question probably is better asked on the conda-build issue tracker.

**Comment by wesm** [comment]
It appears my trouble were isolated to XCode 6.1, which is what's being currently used in conda-forge. XCode 6.4 and 8.0 don't have issues with `@loader_path`. Thanks!
