### ISSUE TITLE
Miniconda failing on AppVeyor with Python 2.7

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#3630]
At conda-forge, we are seeing all jobs that use Miniconda on Python 2.7 fail with the following error:

https://ci.appveyor.com/project/conda-forge/pep257-feedstock/build/job/c632u6l67evx0be2

Is this a conda/miniconda bug - is anyone seeing this for other projects?

**Comment by astrofrog** [comment]
Opening this issue was premature, sorry! I'm not seeing issues with other projects, so will close this for now.

**Comment by jakirkham** [comment]
This is reasonable to raise. However, the actual issues is fixed in a later version of `conda`. Have asked for a new Miniconda release in issue ( https://github.com/ContinuumIO/anaconda-issues/issues/1161 ) and copied you on it. That should actually fix the problem that we were encountering.
