### ISSUE TITLE
CondaOSError while creating a new environnement

### ISSUE THREAD

**Issue by jmague** [conda/conda#3631]
Hi,

I have anaconda python 3.5 installed and I'm trying to create a new environment with python 2.7. The creation of the environment fails with a CondaOSError while trying to link packages:

$ conda create --name py27 python=2 --verbose
Fetching package metadata ...INFO requests.packages.urllib3.connectionpool:_new_conn(805): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(805): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(805): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(805): Starting new HTTPS connection (1): repo.continuum.io
....
Solving package specifications: ..........

Package plan for installation in environment /home/jmague/anaconda3/envs/py27:

The following NEW packages will be INSTALLED:

```
openssl:    1.0.2j-0
pip:        8.1.2-py27_0
python:     2.7.12-1
readline:   6.2-2
setuptools: 27.2.0-py27_0
sqlite:     3.13.0-0
tk:         8.5.18-0
wheel:      0.29.0-py27_0
zlib:       1.2.8-3
```

Proceed ([y]/n)?

Linking packages ...
An unexpected error has occurred.                                                                                                                                              |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

INFO conda.common.io:captured(27): overtaking stderr and stdout
INFO conda.common.io:captured(33): stderr and stdout yielded back
Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 3.5.2.final.0
   requests version : 2.11.1
   root environment : /home/jmague/anaconda3  (writable)
default environment : /home/jmague/anaconda3
   envs directories : /home/jmague/anaconda3/envs
      package cache : /home/jmague/anaconda3/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /home/jmague/anaconda3/bin/conda create --name py27 python=2 --verbose`

```
Traceback (most recent call last):
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/install.py", line 966, in link
    _link(src, dst, lt)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/install.py", line 171, in _link
    shutil.copy2(src, dst)
  File "/home/jmague/anaconda3/lib/python3.5/shutil.py", line 252, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/home/jmague/anaconda3/lib/python3.5/shutil.py", line 219, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/home/jmague/anaconda3/lib/python3.5/shutil.py", line 159, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/home/jmague/anaconda3/envs/py27/bin/c_rehash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/home/jmague/anaconda3/lib/python3.5/site-packages/conda/install.py", line 969, in link
    (src, dst, lt, e))
conda.exceptions.CondaOSError: OS error: failed to link (src='/home/jmague/anaconda3/pkgs/openssl-1.0.2j-0/bin/c_rehash', dst='/home/jmague/anaconda3/envs/py27/bin/c_rehash', type=3, error=OSError(5, 'Input/output error'))
```

The weird thing is that the link seems to have been created anyway:

$ ls /home/jmague/anaconda3/envs/py27/bin/c_rehash
/home/jmague/anaconda3/envs/py27/bin/c_rehash

Thanks,

Jean-Philippe

**Comment by vangalamaheshh** [comment]
Any follow up fix for this?
It seems I am having the same issue.
Any helpful tip is much appreciated.

Thanks,
Mahesh

**Comment by vangalamaheshh** [comment]
OK, apparently, using 

`conda clean --lock --index-cache`

did the trick!

- Mahesh

**Comment by kalefranz** [comment]
Failed to link because it already existed probably. Conda 4.3 here does much better in some of these situations than conda 4.2 or earlier.
