### ISSUE TITLE
conda install pyPDF2 broke pandas

### ISSUE THREAD

**Issue by tmcewen** [conda/conda#3637]
I'm using Microsoft Windows version 6.1.7601 which I believe is Windows 7...
I installed pypdf2 using the command below:
`conda install -c conda-forge pypdf2=1.26.0 `
Everything installed correctly (I remeber it updated conda or anaconda) and I closed the command prompt.  I ran my program that I'm working on and got the following error
![error_1](https://cloud.githubusercontent.com/assets/925723/19406098/cd06a172-9234-11e6-8c61-09e4dfeb8e1c.PNG)
I tried to use the last answer on [this page](http://stackoverflow.com/questions/34145861/valueerror-failed-to-parse-cpython-sys-version-after-using-conda-command) and point the PYTHONPATH to the anaconda Python directory, but no dice.
I'm at a loss.  I can't even uninstall pandas.  I use pandas for everything and now it's broken.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1160
