### ISSUE TITLE
Attempting to install from channel with ssl_verify: corp.crt results in SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jarom-nelson** [conda/conda#3638]
My company has a Web Security Appliance, and I followed the instructions [here](http://conda.pydata.org/docs/install/central.html?highlight=ssl_verify#ssl-verification-ssl-verify) to specify the certificate to use for https. I was able to `conda update/install` from the default channel fine (numpy, jupyter, etc.) fine.

My environment is Windows 10, Cygwin64
i.e. added the following line to my C:\Users\username\.condarc,  (used when in cmd.exe)
 and C:\cygwin64\home\username\.condarc  (used when in Cygwin)
ssl_verify: C:\Users\username\corp.crt   

However, when I attempted to do the following,
`conda install -c r r-essentials`

I get errors related to SSL: CERTIFICATE_VERIFY_FAILED

It appears that the ssl_verify setting from my .condarc is not getting applied when attempting to install from the "r" channel.

The same behavior is seen whether in Cygwin or cmd.exe

[cert_errors.txt](https://github.com/conda/conda/files/530649/cert_errors.txt)

**Comment by kalefranz** [comment]
There have been a few of these issues lately. I'd like to get to the bottom of yours, but it might take some back-and-forth.

First, can you give me the output of `conda info`?  Then run `conda update conda`. If you get an error, give me that output. Otherwise give me the ouput of `conda info` again.

**Comment by jarom-nelson** [comment]
Thanks for your help.

I've attached output from `conda info `and `conda update conda` for both Cygwin and cmd.exe. (no errors in either)

[cmd_conda_info.txt](https://github.com/conda/conda/files/533801/cmd_conda_info.txt)
[cmd_conda_update_conda.txt](https://github.com/conda/conda/files/533800/cmd_conda_update_conda.txt)
[cygwin_conda_info.txt](https://github.com/conda/conda/files/533802/cygwin_conda_info.txt)
[cygwin_conda_update_conda.txt](https://github.com/conda/conda/files/533803/cygwin_conda_update_conda.txt)

**Comment by kalefranz** [comment]
Are you using virus scanning software? If so, which one?

**Comment by jarom-nelson** [comment]
Symantec Endpoint Protection, Windows Defender

**Comment by kalefranz** [comment]
I'm guessing one or both are injecting their own root cert bundles into your networking stack.  You're on windows, so I can't help you quite as much.  Unless you install `curl`.  `conda install m2-curl` should probably get it for you actually.

Then run

    curl -v https://repo.continuum.io/pkgs/free/noarch/repodata.json

You should see something like

```
*   Trying 54.225.212.75...
* Connected to repo.continuum.io (127.0.0.1) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: repo.continuum.io
* Server certificate: thawte SSL CA - G2
* Server certificate: thawte Primary Root CA
...
```

The "Server certificate" lines are what is most important here.

**Comment by jarom-nelson** [comment]
New information:
This also happens on Linux. Added the ssl_verify line  to ~/.conda for a linux server I'm using.  `conda info` and `conda update conda` both have normal output, but `conda install -c r r-essentials` gives "SSL: CERTIFICATE_VERIFY_FAILED" errors.

[conda_cert_errors.txt](https://github.com/conda/conda/files/534320/conda_cert_errors.txt)


I tried the curl commands you noted on Cygwin: The only "Server certificate" indicated is the certificate from my company, and it verifies OK. I don't see any other certificates injected. This may have happened because I've attempted to install my company's certificate in the Cygwin environment as well.

In cmd.exe:  I get certificate errors.
[curl_cert_errors.txt](https://github.com/conda/conda/files/534347/curl_cert_errors.txt)

In Linux: several errors
[curl_output.txt](https://github.com/conda/conda/files/534352/curl_output.txt)

**Comment by kalefranz** [comment]
For an immediate fix, you can always do `conda config --set sal_verify false` while we try to figure out where this is coming from.

**Comment by bkreider** [comment]
This looks like a problem:

> SSL certificate problem: self signed certificate in certificate chain

Can you post the output of this command? `openssl s_client -connect repo.continuum.io:443 -CAfile /usr/workspace/wsb/nelson99/cots/anaconda3/ssl/cacert.pem`

Hit ctrl-c to exit.  You should see output like this:
```
CONNECTED(00000003)
depth=3 C = ZA, ST = Western Cape, L = Cape Town, O = Thawte Consulting cc, OU = Certification Services Division, CN = Thawte Premium Server CA, emailAddress = premium-server@thawte.com
verify return:1
depth=2 C = US, O = "thawte, Inc.", OU = Certification Services Division, OU = "(c) 2006 thawte, Inc. - For authorized use only", CN = thawte Primary Root CA
verify return:1
depth=1 C = US, O = "thawte, Inc.", CN = thawte SSL CA - G2
verify return:1
depth=0 C = US, ST = Texas, L = Austin, O = Continuum Analytics Inc, OU = Information Technology, CN = repo.continuum.io
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Texas/L=Austin/O=Continuum Analytics Inc/OU=Information Technology/CN=repo.continuum.io
   i:/C=US/O=thawte, Inc./CN=thawte SSL CA - G2         <======= Issuer - matches the next "s"
 1 s:/C=US/O=thawte, Inc./CN=thawte SSL CA - G2
   i:/C=US/O=thawte, Inc./OU=Certification Services Division/OU=(c) 2006 thawte, Inc. - For authorized use only/CN=thawte Primary Root CA                      <=======  Issuer - matches the "s" of 2
 2 s:/C=US/O=thawte, Inc./OU=Certification Services Division/OU=(c) 2006 thawte, Inc. - For authorized use only/CN=thawte Primary Root CA
   i:/C=ZA/ST=Western Cape/L=Cape Town/O=Thawte Consulting cc/OU=Certification Services Division/CN=Thawte Premium Server CA/emailAddress=premium-server@thawte.com
---
```

That makes a SSL connection and dumps the SSL certificate chain.  In the example above, my SSL connection validates because Cert 0 is signed by Cert 1 which is signed by Cert 2 and Cert 2 is trusted by fiat because of my root CA store cacert.pem.  If your company is injecting a different cert chain, then the highest numbered cert needs to be in your cacert.pem file.

**Comment by jarom-nelson** [comment]
Here's the output from `openssl s_client -connect repo.continuum.io:443` using the CAfile from Anaconda:
[openssl_cert_dump.txt](https://github.com/conda/conda/files/548280/openssl_cert_dump.txt)

Here's the output from `openssl s_client -connect repo.continuum.io:443` using my company's CA file:
[openssl_local_cert_dump.txt](https://github.com/conda/conda/files/548281/openssl_local_cert_dump.txt)

Should I modify Anaconda's cacert.pem to add in my company's certificate? Isn't that essentially what the `ssl_verify: corp.crt`  should be doing for me, but fails to do when connecting to a non-default channel?

**Comment by bkreider** [comment]
Thanks for running those tests.  You can see that it doesn't trust the Root of the certificate chain in the first one.  (the 2nd line)
```
verify error:num=19:self signed certificate in certificate chain
```
But the second one (2nd and 4th lines) is able to be verified, because you trust the issuing cert:
```
verify return:1
```

@kalefranz is that enough information for you?  It seems like the PEM file isn't be used with channel short names (-c r).  The root cert file looks good from the openssl commands. 

Jarom-nelson, if you fully specify the channel name as ` https://conda.anaconda.org/r`, do that obey the *ssl_verify* setting?

**Comment by kalefranz** [comment]
Also make sure you're testing this against 4.2.11 (which was actually just released today).

**Comment by jarom-nelson** [comment]
On Cygwin:
`conda create --name cert_test -c https://conda.anaconda.org/r r-essentials |& tee conda_full_channel_url_cygwin.txt`
[conda_full_channel_url_cygwin.txt](https://github.com/conda/conda/files/549124/conda_full_channel_url_cygwin.txt)

It looks like it worked fine, HOWEVER, I did this first with `ssl_verify: false` (unintentionally), and, of course, it worked fine. I tried again after reverting to `ssl_verify: C:\Users\username\corp.crt`, and it still worked (strange), output is above. So I did the following, which also worked fine (without certificate errors) though I would expect it to fail based on previous tests:

`conda create --name cert_test2 -c r r-essentials |& tee conda_channel_cygwin.txt`
[conda_channel_cygwin.txt]
(https://github.com/conda/conda/files/549130/conda_channel_cygwin.txt)


On Linux I still get certificate errors with full channel URL (note: `ssl_verify:` was unchanged here from previous tests):
`conda create --name cert_test -c https://conda.anaconda.org/r r-essentials |& tee conda_full_channel_url_linux.txt`
[conda_full_channel_url_linux.txt](https://github.com/conda/conda/files/549136/conda_full_channel_url_linux.txt)


All of these were done after `conda update conda`

**Comment by jarom-nelson** [comment]
I had was suspicious about the success of the Cygwin with the "r" channel above, thinking perhaps something was caching the certificate chain in some way to cause it to pass.  So I tried a different channel:
` conda create --name mro_test -c https://conda.anaconda.org/mro r-uuid |& tee conda_mro_channel_url_cygwin.txt`
[conda_mro_channel_url_cygwin.txt](https://github.com/conda/conda/files/549188/conda_mro_channel_url_cygwin.txt)

As I suspected, the install failed with certificate errors (as it did on Linux without the `ssl_verify` mixup).

**Comment by jarom-nelson** [comment]
It appears that I have a similar certificate error with the following:
`anaconda search -t conda pypi`
[search_cert_error.txt](https://github.com/conda/conda/files/569256/search_cert_error.txt)

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
