### ISSUE TITLE
when i run "conda env create -f conda_env.yml"there be trouble

### ISSUE THREAD

**Issue by 9596805** [conda/conda#3642]
![111](https://cloud.githubusercontent.com/assets/22849236/19416001/bdffa3da-93b6-11e6-8823-024683ecfa31.png)
![2222](https://cloud.githubusercontent.com/assets/22849236/19416002/be9ece88-93b6-11e6-8f1c-bd39699d1066.png)

i am WIN10  64bit   can i run gprMax?  i had try to run gprMax 2.0 but its useless
i try to install gprMax  with https://github.com/gprMax/gprMax  useless,either.
i  want to know where is mistake?please help me

**Comment by kalefranz** [comment]
intermittent HTTP issue
