### ISSUE TITLE
Extracting packages Opencv for installation in environment Anaconda

### ISSUE THREAD

**Issue by fgsalas** [conda/conda#3645]
I cannot install Open cv in Anaconda Environment! I need to use it for implementing vision routines in python. Thanks for your help!!
Extracting packages ...
An unexpected error has ocurred, 

Traceback (most recent call last)
File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module> sys.exit(main())
File"C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main exit_code = args_func(args,p)
File"C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func exit_code = args.funs(args,p)
File"C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute install(args, parser, 'install')
File"C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install execute_actions(actions, index, verbose=not args.quiet)
File"C:\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_actions inst.execute_instructions(plan, index, verbose)
File"C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions cmd(state, arg)
 File"C:\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD extract(arg)
File"C:\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract exp_backoff_fn(os.rename, temp_path, path)
File"C:\Anaconda2\lib\site-packages\conda\install.py", line 236, in exp_backoff_fn result = fn(*args)
WindowsError: [Error 5] Acceso denegado

Output of conda info
platform : win-64
conda version : 4.1.4
conda-env version: 2.5.1
conda-build version : 1.21.2
python version : 2.7.11.final.0
requests version : 2.10.0
root environment : C:\Anaconda2 (writable)
default environment : C:\Anaconda2
envs directories : C:\Anaconda2\envs
package cache : C:\Anaconda2\pkgs
channel URLs: https://repo.continuum.io/pkgs/free/win-64/
                       https://repo.continuum.io/pkgs/free/noarch/
                       https://repo.continuum.io/pkgs/pro/win-64/
                       https://repo.continuum.io/pkgs/pro/noarch/
config file : None
offline mode : False
is foreign system : False

**Comment by kalefranz** [comment]
This issue is filed for conda version 4.1.4.  The latest releases are 4.1.12 and 4.2.11.
