### ISSUE TITLE
Installing ompython-2.0.7

### ISSUE THREAD

**Issue by paulrusu8** [conda/conda#3646]
Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Library/Frameworks/Python.framework/Versions/2.7  (writable)
    default environment : /Library/Frameworks/Python.framework/Versions/2.7
       envs directories : /Library/Frameworks/Python.framework/Versions/2.7/envs
          package cache : /Library/Frameworks/Python.framework/Versions/2.7/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Library/Frameworks/Python.framework/Versions/2.7/bin/conda install -c mutirri ompython=2.0.7`

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x10846b110>

**Comment by skibaa** [comment]
Same here when trying to go through 30-minute tutorial:

```

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.7.0
       root environment : /home/andrews/miniconda2  (writable)
    default environment : /home/andrews/miniconda2
       envs directories : /home/andrews/miniconda2/envs
          package cache : /home/andrews/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /home/andrews/miniconda2/bin/conda create --name snowflakes biopython`




    Traceback (most recent call last):
      File "/home/andrews/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/andrews/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/andrews/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/andrews/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7f6d7d6deb10>

```

**Comment by paulrusu8** [comment]
Try installing it through pip. I only tried it through conda because the pip install leads to a problem with omcidl stubs version on Mac OS X. 
Let me know if that works on Linux.

**Comment by skibaa** [comment]
I just went the second time through the tutorial and did not update conda with 'conda update conda'. This time it works. Probably some recent regression.

**Comment by paulrusu8** [comment]
But does it work? Do you get an error message omniidl stubs version incompatibility (version 4.2 installed, version 3.0 supported)?

**Comment by skibaa** [comment]
I did not use omniidl, notice that my command is different - it is one from http://conda.pydata.org/docs/test-drive.html

**Comment by paulrusu8** [comment]
I don’t mean the conda part, I mean when you eventually run it in a python program and put “omc=OMCSession()”? Does it work?
On 19 Oct 2016, at 9:05 PM, Andrew Skiba <notifications@github.com<mailto:notifications@github.com>> wrote:


I did not use omniidl, notice that my command is different - it is one from http://conda.pydata.org/docs/test-drive.html

**Comment by skibaa** [comment]
I don't use ompython either. So far I progress through the tutorial I referred in the previous message, works as expected with conda 3.1.11.
