### ISSUE TITLE
Getting index for platforms other than the one you're on

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3648]
There used to be a way to do this: https://github.com/conda/conda/blob/4.1.x/conda/api.py#L21-L23

but that seems to be gone in 4.2: https://github.com/conda/conda/blob/4.2.x/conda/api.py#L10 - the platform argument is still there, but it does not do anything.

Is there an equivalent way with the new config?  I looked for both of the two functions (```normalize_urls``` and ```get_channel_urls```) but neither of them seem to exist.  Where are you appending the platform to the URL, and can we make the platform changeable?

This is essential for the new build system, which examines dependencies and computes the necessary builds for all platforms from one central platform, so I'm marking it as blocking.

**Comment by kalefranz** [comment]
I think we got that covered here, no?
https://github.com/conda/conda/pull/3629

Already merged into the pending 4.2.10...

**Comment by msarahan** [comment]
Yes, looks fixed.  Thanks.
