### ISSUE TITLE
Removal of handle_proxy_407 breaks conda-build

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3651]
Elevating as issue from https://github.com/conda/conda/commit/b993816b39a48d807e7a9659246266f6035c3dcd#commitcomment-19452072 so that it does not get lost.

Removal of handle_proxy_407 breaks conda-build (it is used in pypi skeleton code for some reason.) Is there an alternative that I can use instead?  Please provide example code.

**Comment by kalefranz** [comment]
CondaSession should now handle, as part of CondaAuth or whatever that class is called. 

The eventual solution is to just remove handle_proxy_407 from conda-build. In the meantime, I tried to make it a no-op. I guess I got the function signature wrong though?

**Comment by kalefranz** [comment]
https://github.com/conda/conda/blob/master/conda/exports.py#L36

**Comment by msarahan** [comment]
Thanks.  Please backport that to 4.2.
