### ISSUE TITLE
# $ conda create -n my_root --clone=C:\Program Files\Anaconda3 Fails?

### ISSUE THREAD

**Issue by toasteez** [conda/conda#3652]
We are evaluating Anaconda and as such for the corporate requirement have a fresh install of latest Anaconda3 on Windows 7.  I attempted to update conda and received the following:

(C:\Program Files\Anaconda3) C:\Users\xxxxxxxx>conda update conda
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files\Anaconda3:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-env-2.6.0 | 0          498 B  defaults |

The following NEW packages will be INSTALLED:

```
conda-env: 2.6.0-0 defaults (copy)
```

CondaIOError: IO error: Missing write permissions in: C:\Program Files\Anaconda3

```
# You don't appear to have the necessary permissions to update packages
# into the install area 'C:\Program Files\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone=C:\Program Files\Anaconda3
```

(C:\Program Files\Anaconda3) C:\Users\xxxxxxxx>conda create -n C:\Users\xxxxxxxx
\myAnaconda3 --clone="C:\Program Files\Anaconda3"
Source:      C:\Program Files\Anaconda3
Destination: C:\Users\xxxxxxxx\myAnaconda3
The following packages cannot be cloned out of the root environment:
- conda-4.2.9-py35_0
- conda-build-2.0.2-py35_0
  Packages: 173
  Files: 44
  WARNING conda.lock:touch(53): Failed to create lock, do not run conda in paralle
  l processes [errno 13]
  An unexpected error has occurred.
  Please consider posting the following information to the
  conda GitHub issue tracker at:
  
  https://github.com/conda/conda/issues

Current conda install:

```
           platform : win-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 3.5.2.final.0
   requests version : 2.11.1
   root environment : C:\Program Files\Anaconda3  (read only)
default environment : C:\Program Files\Anaconda3
   envs directories : C:\Users\xxxxxxxx\.conda\envs
                      C:\Program Files\Anaconda3\envs
      package cache : C:\Users\xxxxxxxx\.conda\envs\.pkgs
                      C:\Program Files\Anaconda3\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : C:\Program Files\Anaconda3\.condarc
       offline mode : False
```

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -n C:\Users\xxxxxxxx\myAnaconda3 --clone=C:\Program Files\Anaconda3`

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", l
```

ine 473, in conda_exception_handler
        return_value = func(_args, *_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.p
y", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 228, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_
args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 90, in clone
        index_args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\misc.py", line 38
7, in clone_env
        force_extract=False, index_args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\misc.py", line 18
7, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 64
3, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\install.py", line
 801, in extract
        t.extractall(path=temp_path)
      File "C:\Program Files\Anaconda3\lib\tarfile.py", line 1996, in extractall

```
    numeric_owner=numeric_owner)
  File "C:\Program Files\Anaconda3\lib\tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "C:\Program Files\Anaconda3\lib\tarfile.py", line 2100, in _extract_m
```

ember
        os.makedirs(upperdirs)
      File "C:\Program Files\Anaconda3\lib\os.py", line 231, in makedirs
        makedirs(head, mode, exist_ok)
      File "C:\Program Files\Anaconda3\lib\os.py", line 231, in makedirs
        makedirs(head, mode, exist_ok)
      File "C:\Program Files\Anaconda3\lib\os.py", line 241, in makedirs
        mkdir(name, mode)
    PermissionError: [WinError 5] Access is denied: 'C:\Program Files\Anaconda
3\pkgs\menuinst-1.4.1-py35_0.tmp'

(C:\Program Files\Anaconda3) C:\Users\xxxxxxxx>

**Comment by sidthedesigner** [comment]
How did you solve this issue, Sir?

**Comment by sidthedesigner** [comment]
Anybody facing this issue, simply run the cmd/prompt file as administrator and you will not face this issue.
Eg:
1. Go to Start
2. Search for "Anaconda Prompt"
3. Right click on the icon
4. Click Run as Administrator
5. Then type in " conda install -c conda-forge scipy ".

It will solve the issue.
Thanks

**Comment by j213j213** [comment]
While installation you may have selected All Users , now before installing or updating anything you will have to open the Anaconda with Admin privileges - it can be done by right click ---> Run as admin.

Or you can try re-installing the software and select "Just for Me" option in place of "All the users" selection.

**Comment by yanfri** [comment]
Thank you guys for the solutions. However, this is still not working for me.
I have an Admin account on my PC (I am its only user :)) but it does not let me install Anaconda packages even when I run the command line or Anaconda prompt as an admin...
But it is true that I installed my Anaconda version for all users. Probably a bad idea...

**Comment by silkyprogrammer** [comment]
We can resolve this by running "Anaconda Navigator" as Admin and then when we run updates this problem will not appear.

**Comment by cardinal10** [comment]
had the same problem but was resolved by going to the ProgramData\Anaconda folder properties and setting the permissions of User to Full Control and Modify (followed the other thread's solution).

**Comment by dmast3r** [comment]
I had the same problem while installing packages(I was installing scikit-learn) from Anaconda but using admin privileges as mentioned by others did not help either. So, I uninstalled and re-installed Anaconda in a directory with no spaces and during installation I chose "Only me". It worked successfully than.

**Comment by bhaskarbhuyan** [comment]
Simple Method: Just go to the path 'C:\ProgramData\Anaconda3' , right-click > properties> secutrity and edit the permissions to allow them for the users. Come back to the console and install anything

**Comment by mohapatras** [comment]
The reason this is happening is Administrator privileges.
Here's how to solve it.
Right click -> Run as administrator ->  _Execute your syntaxes_

**Comment by Phone2017** [comment]
@sidthedesigner Yes, Tks for your answer. I have solved this problem easily by your method. Tks. @sidthedesigner

**Comment by narenltk** [comment]
we can run anaconda prompt as admin to install everything we need....

**Comment by drashya17** [comment]
my problem solved after change anaconda's privilage to all and run anaconda prompt as 'run as adminstrator'  mode. And i also create a virtual environment for installing all packages, this is a safest method .

**Comment by Glxblt76** [comment]
@sidthedesigner Your answer FIXED my problem! It seems to work not only for scipy but for other libraries. I landed on this page looking for a solution regarding Bigfloat library, and I could install it thanks to your fix.

All the best!
