### ISSUE TITLE
Add option to pin or unpin a package from conda CLI

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#3658]
conda pin <package names ...>
conda unpin <package names ...>

**Comment by kalefranz** [comment]
Done in (I think) 4.3.16.

**Comment by joelhullcio** [comment]
I just checked conda 4.3.16 on OS X.  I don't see a pin/unpin option?

**Comment by kalefranz** [comment]
conda config --env --add pinned_packages python=2.7

Enabled in #4921, #4964
