### ISSUE TITLE
verbose output for dependency resolution with conda install

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#3663]
Hello,

When installing a self-built meta-package, `conda` hangs at the dependency resolution step:
```
Fetching package metadata ...............
Solving package specifications: .......
```

but I do not know how to troubleshoot this problem. Would it be possible to add a `verbose` option to see what's going on with the dependency resolution algorithm?

As far as I can see, that's not available:
http://conda.pydata.org/docs/commands/conda-install.html

Best regards,
Sebastian.

**Comment by kalefranz** [comment]
Use `-v` or `-vv` to add verbosity as long as your version of conda is up-to-date.  Older versions, you'll have to use `--debug`.

**Comment by contactlp** [comment]
conda's `-vv` does not allow to see when pip installing very large package using env.yml. It feels like conda is stuck.

 Is there way to see what pip is doing when you install through `conda env create -n py35 -f env2.yml -vv`

**Comment by peterroelants** [comment]
@lav-patel I ran into the same issue with conda not verbosing `pip install` logs. I filed another issue at: https://github.com/conda/conda/issues/10556
