### ISSUE TITLE
conda appears to be stuck during update/install: Access Denied Error on Windows

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda#3664]
Hi,

At work we have on occasion noticed that some of our build workers were taking unusually long during some `conda update` and `conda install` operations.

After enabling debugging with `-vv` and `-debug`, we identified that Conda was having trouble removing the `pkgs/.trash` folder. Here's the output we were seeing:

```
10:49:00 INFO conda.common.disk:delete_trash(235): Could not delete path in trash dir W:\Miniconda\pkgs\.trash\b095ce24-6c5c-4df1-aeb1-b726106d1f2b
10:49:00 WindowsError(5, 'Access is denied')
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 0.147886 sec
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 0.252876 sec
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 0.43156 sec
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:00 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 0.834403 sec
10:49:01 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:01 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 1.69182 sec
10:49:03 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:03 DEBUG conda.common.disk:exp_backoff_fn(163): retrying disk.py/59 <lambda>() in 3.20222 sec
10:49:06 DEBUG conda.common.disk:exp_backoff_fn(154): WindowsError(5, 'Access is denied')
10:49:06 INFO conda.common.disk:delete_trash(235): Could not delete path in trash dir W:\Miniconda\pkgs\.trash\b1e43e9c-d723-4323-8ceb-3b834d67e4e4
10:49:06 WindowsError(5, 'Access is denied')
```

This could go on for dozens of minutes. 

Looking at this worker we noticed a few things:

* `conda` was the only Python process running at the time;
* Looking at code we noticed the docs for `exp_backoff_fn`:

  ```python
  """Mostly for retrying file operations that fail on Windows due to virus scanners"""
  ```

  Some issues (#2947, #2983) also mention virus scanners, so we disabled the virus scanner we have ("ESET Endpoint Antivirus") but the problem persisted. 

Here's the output of `conda info`:

```
Current conda install:

               platform : win-64
          conda version : 4.2.9+1
       conda is private : False
      conda-env version : 4.2.9+1
    conda-build version : 1.20.0+1
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : W:\Miniconda  (writable)
    default environment : W:\Miniconda
       envs directories : W:\Miniconda\envs
          package cache : W:\Miniconda\pkgs
           channel URLs : https://eden.esss.com.br/conda-channel/esss/win-64/
                          https://eden.esss.com.br/conda-channel/esss/noarch/
                          https://eden.esss.com.br/conda-channel/mirror/win-64/
                          https://eden.esss.com.br/conda-channel/mirror/noarch/
                          https://eden.esss.com.br/conda-channel/mirror-conda-forge/win-64/
                          https://eden.esss.com.br/conda-channel/mirror-conda-forge/noarch/
            config file : W:\Miniconda\.condarc
           offline mode : False

```

Our current workaround was to remove the `pkgs/.trash` folder just before calling `conda update` or `conda install`.

Any ideas on how to debug this perhaps? Any help is greatly appreciated.

**Comment by kalefranz** [comment]
First, thanks for the awesome, detailed report.  I wish every issue filed was this descriptive :)

As you can tell from our code, we've been battling permissions issues like this on windows for a while now.

Question 1: What are the details of your file system/mount for your `W:\` drive?  Local? Network? NTFS? Other?

Question 2: 

> Our current workaround was to remove the pkgs/.trash folder just before calling conda update or conda install.

Are you doing this with the same automated script that is calling `conda update` or `conda install`?  What is the actual command you're using?

**Comment by nicoddemus** [comment]
> First, thanks for the awesome, detailed report. I wish every issue filed was this descriptive :)

Thanks, it's the least I can do. 😁 

> Question 1: What are the details of your file system/mount for your W:\ drive? Local? Network? NTFS? Other?

That is a normal, local partition. In almost all of our slaves that's a separate hard-drive than the one where the system is installed.

A detail that perhaps it wasn't very clear is that we checked the permissions of the `.trash` folder and the files on it and they were fine. We can delete the files normally when logging in with the same user which runs our CI job once we kill the python/conda process.

> Are you doing this with the same automated script that is calling conda update or conda install? 
> What is the actual command you're using?

Yes, we are doing that in two scripts at the moment:

1. A powershell script which is run daily to provision the workers (ensure that conda is installed, update some choco packages, cleanup some workspaces, etc). That script is now running this command right before attempting to execute `conda install`:

  ```ps
  $cir = conda info --root
  $trash_dir = "$($cir)\pkgs\.trash"
  if (Test-Path $trash_dir){
      Remove-Item -Recurse -Force $trash_dir
  }
  conda --debug update --all --yes --quiet 
  ```

2. A "setup worker" BAT file which executed at the start of each job, and calls `conda env update` to create a conda-environment:

  ```bat
  for /F %%i in ('conda info --root') do set CONDA_ROOT=%%i
  set CONDA_TRASH=%CONDA_ROOT%\pkgs\.trash
  if exist %CONDA_TRASH% (
      echo Removing %CONDA_TRASH%
      rd /s /q %CONDA_TRASH%
  )
  @REM update conda and conda-env to the versions specified on this branch
  call conda install -n root --file "%WORKSPACE%\eden\conda_version.txt" || goto ERROR
  ```

The `conda install/update` calls above are the points where we were observing that conda was getting stuck.

We have a separate `W:` drive because we can easily quick format it and run the provisioning script to "wipe" a slave. The `W:` drive contains Miniconda, all packages and environments, as well as the jobs' workspaces.

**Comment by kalefranz** [comment]
Helpful comment from @ChrisBarker-NOAA on the conda message board.
https://groups.google.com/a/continuum.io/forum/#!msg/conda/9dPHBsAGqoQ/CrKdGLyfBgAJ

> Windows file locking in a pain in the %#^%
> 
> We have had problems that we have never been able to resolve. On my workstation, I ended up installing "unlocker"
> 
> http://www.iobit.com/en/iobit-unlocker.php
> 
> which is very nice for interactive GUI use -- but not helpful for conda. But I wll say that I end up using it a LOT!
> 
> Anyway, aside from virus scanners, backup software can be a really pain this way:
> 
> it detects a change in some files.
> it locks them while updating the backup
> now you can't delete them until it is done.
> 
> The proper solution here is configure your backup software to not back up stuff it shouldn't, but conda has no control over that.
> 
> However, it looks like at least in this case it's a .trash folder that's causing the problem ,so it seems conda should just give up (quickly)  if it can't delete that -- it's not fatal, is it?
> 
> Also -- maybe there is a way to make a system call to unlock files? woudl conda have the permission to do that?

**Comment by kalefranz** [comment]
Should be resolved, or at least much better, with #3698.

**Comment by nicoddemus** [comment]
This does look like it will fix the issue. Thanks for the quick turnaround. 👍

**Comment by mparry** [comment]
I don't think this is fixed in 4.2.11 unfortunately. I think the problem is that the revised backoff_rmdir() implementation doesn't propagate the max_tries value to backoff_unlink().

**Comment by mparry** [comment]
I should probably also add: I think the reason this can end up being so slow is that the exponential back-off is, AFAICS, applied for each individual file / directory. That is, you end up sleeping for ~6.5s * num locked items. If instead it remembered all of the problem items and only applied the exponential back-off between retrying the entire list of them, you would sleep for ~6.5s in total. 

I certainly seem to have run into cases (builds with nested Python instances) where there are >100 locked files in .trash and this clean-up has ended up retrying for >15 minutes.

**Comment by kalefranz** [comment]
Yes, it's trying every file.  I haven't written code to hold state or do any of this more intelligently.  Happy to accept PRs though 😁

At least now (hopefully) it only tries once, with no delay.  Note the variable name is `max_tries`, not `max_retries`.

**Comment by mparry** [comment]
As of 4.2.12 this is fine for 'conda install' and '... update' but can still be very slow for other cases; the default number of attempts in conda.common.disk is still 7 and various code paths - eg. 'conda env remove', which I've been tending to hit quite a bit locally in recent work - don't end up overriding it. I'm therefore still having to hack MAX_TRIES to 1 in my local install to get it to behave reasonably. Would you like me to open a fresh ticket about this?

(I expect I'm missing something but it's not immediately obvious to me why it's desirable to retry here at all by default. The files in question can just be cleaned up next time conda runs. Isn't this the point of the .trash directory? It seems like a bit of edge case where the amount of content that's pending deletion is so large that the latency would be a problem.)

**Comment by mparry** [comment]
Actually, thinking about it a bit more, the problem here may be specifically that the deletion retries (invoked by `UNLINK_CMD`) are always failing for various files in the 'python' package and so it spends a while backing off, then inevitably moves them to .trash anyway. Certainly that's the point that the progress bar is always stuck on for me. I believe that it's the case under Windows that if one hard link is locked, no other hard links for that file can be deleted. For example:

In shell 1:
```
echo foo > file.txt
mklink /H link.txt file.txt
mklink /H link2.txt file.txt
ipython
import win32file
h = win32file.CreateFile("link.txt", win32file.GENERIC_READ, 0,
        None, win32file.OPEN_EXISTING, 0, None)
```

In shell 2:
```
del link2.txt
> The process cannot access the file because it is being used by another process.
```
