### ISSUE TITLE
"Anaconda Navigator quit unexpectedly"

### ISSUE THREAD

**Issue by TWellman** [conda/conda#3668]
Greetings, 
After updating anaconda, python, and some misc. packages via conda install at the command line,  Anaconda Navigator will not launch properly in clicking the icon. I get the following error, below. Help appreciated.

Process:               python2.7 [3391]
Path:                  /Users/USER/*/python
Identifier:            com.continuum.io
Version:               1.3.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [3390]
Responsible:           python2.7 [3391]
User ID:               51310

Date/Time:             2016-10-18 15:44:27.237 -0600
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        1B3417CE-EC8A-CAA4-FD69-D1DDCB85BE36

Time Awake Since Boot: 4400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff88573f06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff88e2f4ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9ab336df abort + 129
3   libQt5Core.5.6.0.dylib        	0x00000001030171f9 qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&) + 9
4   libQt5Core.5.6.0.dylib        	0x0000000103018bc0 QMessageLogger::fatal(char const*, ...) const + 224
5   QtCore.so                     	0x0000000101312e02 pyqt5_err_print() + 786
6   QtCore.so                     	0x00000001013186ac PyQtSlotProxy::unislot(void**) + 124
7   QtCore.so                     	0x0000000101318615 PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 85
8   libQt5Core.5.6.0.dylib        	0x0000000103215273 QObject::event(QEvent*) + 739
9   libQt5Widgets.5.6.0.dylib     	0x000000010689a616 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294
10  libQt5Widgets.5.6.0.dylib     	0x000000010689d904 QApplication::notify(QObject*, QEvent*) + 7956
11  QtWidgets.so                  	0x00000001062f786f sipQApplication::notify(QObject*, QEvent*) + 127
12  libQt5Core.5.6.0.dylib        	0x00000001031e87a7 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
13  libQt5Core.5.6.0.dylib        	0x00000001031e940b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 587
14  libqcocoa.dylib               	0x0000000114935b9e QCocoaEventDispatcherPrivate::processPostedEvents() + 190
15  libqcocoa.dylib               	0x00000001149364a1 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
16  com.apple.CoreFoundation      	0x00007fff8a7b5881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
17  com.apple.CoreFoundation      	0x00007fff8a794fbc __CFRunLoopDoSources0 + 556
18  com.apple.CoreFoundation      	0x00007fff8a7944df __CFRunLoopRun + 927
19  com.apple.CoreFoundation      	0x00007fff8a793ed8 CFRunLoopRunSpecific + 296
20  com.apple.HIToolbox           	0x00007fff8668b935 RunCurrentEventLoopInMode + 235
21  com.apple.HIToolbox           	0x00007fff8668b76f ReceiveNextEventCommon + 432
22  com.apple.HIToolbox           	0x00007fff8668b5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
23  com.apple.AppKit              	0x00007fff8b872df6 _DPSNextEvent + 1067
24  com.apple.AppKit              	0x00007fff8b872226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
25  com.apple.AppKit              	0x00007fff8b866d80 -[NSApplication run] + 682
26  libqcocoa.dylib               	0x00000001149352fd QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2189
27  libQt5Core.5.6.0.dylib        	0x00000001031e4b51 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
28  libQt5Core.5.6.0.dylib        	0x00000001031e8e8a QCoreApplication::exec() + 346
29  QtWidgets.so                  	0x00000001062f8380 meth_QApplication_exec_(_object*, _object*) + 80
30  libpython2.7.dylib            	0x00000001000b51ae PyEval_EvalFrameEx + 30574
31  libpython2.7.dylib            	0x00000001000b9f52 fast_function + 274
32  libpython2.7.dylib            	0x00000001000b4da4 PyEval_EvalFrameEx + 29540
33  libpython2.7.dylib            	0x00000001000ad732 PyEval_EvalCodeEx + 1538
34  libpython2.7.dylib            	0x00000001000ad126 PyEval_EvalCode + 54
35  libpython2.7.dylib            	0x00000001000dbf04 PyRun_FileExFlags + 164
36  libpython2.7.dylib            	0x00000001000dba81 PyRun_SimpleFileExFlags + 769
37  libpython2.7.dylib            	0x00000001000f15c8 Py_Main + 3096
38  python                        	0x0000000100001f24 start + 52

etc .....

**Comment by kalefranz** [comment]
Please see [this link](https://docs.continuum.io/anaconda/navigator#support) to get help with Anaconda Navigator.  This issue tracker is for conda :)
