### ISSUE TITLE
Error in installing Graphlab

### ISSUE THREAD

**Issue by chatterjeesidd** [conda/conda#3670]
The installation procedure for anaconda freezes at 70% for sometime and then completes with error. Installation log attached.

[launcher-install-log.txt](https://github.com/conda/conda/files/539995/launcher-install-log.txt)

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1174

**Comment by chatterjeesidd** [comment]
Hi kalefranz, would you be able to suggest what I need to do to complete the installation. I am very new to using python and graphlab

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1178
