### ISSUE TITLE
CDT metadata discussion

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3679]
Prototype (not to be followed) for CI system is at:

https://github.com/msarahan/ci_test

Pay special attention to:
- build_platforms.d
- test_platforms.d
- versions.yml

These don't implement everything we need.  In particular, they don't really directly capture things like glibc version.  versions.yml is currently limited solely to the few packages that conda-build has hard-coded.  It really should support arbitrary packages.  This ties into https://github.com/conda/conda-build/issues/1142

**Comment by kalefranz** [comment]
I believe we can close this now.

**Comment by msarahan** [comment]
Could you please document a working example? I think you've implemented this, but I haven't seen working examples yet.

I'm reopening​ until it's documented.
