### ISSUE TITLE
Can't read ENVI header

### ISSUE THREAD

**Issue by muratetm** [conda/conda#3681]
import spectral.io.envi as envi
lib = envi.open('/home/mmuratet/Downloads/EO1H0280342016290110K7/EO1H0280342016290110K7.hdr')

IOError                                   Traceback (most recent call last)
<ipython-input-29-2c7626f16cfd> in <module>()
      1 import spectral.io.envi as envi
----> 2 lib = envi.open('/home/mmuratet/Downloads/EO1H0280342016290110K7/EO1H0280342016290110K7.hdr')

/home/mmuratet/anaconda/lib/python2.7/site-packages/spectral/io/envi.pyc in open(file, image)
    314                     break
    315         if not image:
--> 316             raise IOError('Unable to determine image file name.')
    317     else:
    318         image = find_file_path(image)

IOError: Unable to determine image file name.

I understand from the documentation that it should read ENVI headers, but it seems to want an image file, too.

Thanks

Mike
​

**Comment by kalefranz** [comment]
There's nothing here that changing conda's source code can affect.
