### ISSUE TITLE
Conda reports wrong package conflicts

### ISSUE THREAD

**Issue by mick-d** [conda/conda#3687]
_Context_: 

Installing a list of packages with `conda` when one package is in conflict with the environment python version

_Issue_: 

No matter where in the list the conflicting package is, `conda` systematically reports the first package in the list to be the culprit, even when it is not

_Example when `vtk` is the culprit in a python 3.5 environment_:

`conda install xlrd matplotlib` works, but:
`conda install xlrd matplotlib vtk` blames xlrd

```
Fetching package metadata .......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - matplotlib
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

`conda install matplotlib xlrd vtk` blames matplotlib

```
Fetching package metadata .......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - matplotlib
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

When actually it is `vtk` to blame:
`conda install vtk` **does not work**

```
Fetching package metadata .......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 3.5*
  - vtk
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by kalefranz** [comment]
@mcg1969 is working on a fix for the next feature release.

**Comment by MaharishiCanada** [comment]
Is this related? I do 
```
$ conda install vtk=7.1.0
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/dominic/app_download/anaconda3:
#
vtk                       7.1.0                    py35_2    conda-forge
```
Note that vtk 7.1.0 uses python 3.5. Next, I check the info for vtk:

```
$ conda info vtk
Fetching package metadata .........

vtk 5.10.1 py27_0
-----------------
file name   : vtk-5.10.1-py27_0.tar.bz2
name        : vtk
version     : 5.10.1
build string: py27_0
build number: 0
channel     : defaults
size        : 92.2 MB
arch        : x86_64
date        : 2013-07-30
license     : BSD
md5         : da1fcbaa9e8e0d0b01864bb96c3c3fbf
platform    : linux
requires    : ()
url         : https://repo.continuum.io/pkgs/free/linux-64/vtk-5.10.1-py27_0.tar.bz2
dependencies:
    python 2.7*

```
Note that it says vtk 5.10 using python 2.7.  I am a newby on conda and python. Is this part of the bug? Maybe this has nothing to do with the bug and is expected and I am misunderstanding something.

**Comment by kalefranz** [comment]
Outdated. Closing.
