### ISSUE TITLE
conda and csh interaction problems

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3688]
Reported today on the Conda ML, possibly by @mhagerty.  Not my issue, but seems like something to look into:

---

Something weird is indeed going on here.  I am not a bash user, I am a csh user.  So I "activate" with `source ~/anaconda/bin/activate.csh myenv`.  This changes my prompt to reflect the environment change but as we'll see below, it apparently doesn't properly set things up for conda to work.   As you noted, it seems that conda isn't recognizing the activated environment even after it changes my prompt!

Furthermore, if I switch to bash, and do `source activate myenv` and then run `conda install 'pyqt<5'`: rather than saying it's already installed, it installs pyqt4 again!

```
(myenv) bash-3.2$ conda install 'pyqt<5'
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/myusername/anaconda/envs/myenv:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freetype-2.7               |                0         791 KB  conda-forge
    qt-4.8.7                   |                4        37.1 MB
    ------------------------------------------------------------
                                           Total:        37.9 MB

The following NEW packages will be INSTALLED:

    freetype: 2.7-0         conda-forge
    libpng:   1.6.24-0      conda-forge
    pyqt:     4.11.4-py27_0 conda-forge
    qt:       4.8.7-4                 
    sip:      4.18-py27_0   conda-forge

Proceed ([y]/n)?

Fetching packages ...
freetype-2.7-0 100% |###################################################################| Time: 0:00:00   2.32 MB/s
qt-4.8.7-4.tar 100% |###################################################################| Time: 0:00:13   2.86 MB/s
Extracting packages ...
[      COMPLETE      ]|######################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
```

...and NOW when I try to import PyQt4, it simply works:

```
>>> import PyQt4
>>>
```

_furthermore_, if I leave bash and go into csh, and activate my anaconda environment again, THEN it also works:

```
>>> import PyQt4
>>>
```

So the lesson here is that conda is only partially compatible with csh, despite there being a script for it.  I will remember: _"always run bash when using conda"_.

Thank you, you have gotten me through this and I can now get back to what I was originally trying to do a few hours ago when PyQt4 turned up missing!

Someone should have a look at the interaction of the `activate.csh` script and/or conda...  I never have trouble when I use `pip`, but apparently there's an issue with "conda".

**Comment by njalerikson** [comment]
None of the current Conda branches supports CSH (it is being worked on here #3175).

So additional details will need to be collected to properly understand this issue.

**Comment by njalerikson** [comment]
#3175 was merged today. I would assume that this ticket can be closed until it has been properly tested with the new code where CSH/TCSH is supported.

**Comment by kalefranz** [comment]
agreed
