### ISSUE TITLE
Basic authentication broken: login:password components from channel urls lost by prioritize_channels()

### ISSUE THREAD

**Issue by afeblot** [conda/conda#3690]
With conda 4.2.9,
running `conda search xxx`, or `conda install xxx` on a channel (`https://user:password@server/channels`) protected by basic authentication fails `with HTTPError: 401 Client Error: Unauthorized for url: https://server/channels/osx-64/repodata.json: https://server/channels/osx-64/`

For what I understand, `user:password` components are lost by 
```
def prioritize_channels(channels):
    # ('https://conda.anaconda.org/conda-forge/osx-64/', ('conda-forge', 1))
    result = odict()
    for q, chn in enumerate(channels):
        channel = Channel(chn)
        for url in channel.urls:
            if url in result:
                continue
            result[url] = channel.canonical_name, q
    return result
```
where
```
channel._raw_value = https://user:password@server/channels
result = OrderedDict([(u'https://server/channels/osx-64/', (u'https://server/channels', 0)), (u'https://server/channels/noarch/', (u'https://server/channels', 0))])
```

**Comment by kalefranz** [comment]
This should be fixed, in a release coming Monday.  If you want to preview to confirm,

    conda config --prepend channels conda-canary
    conda update conda

That should give you conda 4.2.10.  4.2.11 will be released to defaults Monday.

**Comment by afeblot** [comment]
Hi,
indeed, works fine, thanks. Sorry for having overlooked #3459
