### ISSUE TITLE
To add to a new 3.x release

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3692]
- [ ] Upgrade notice for noarch packages
- [ ] Parsing of `info/files` for hashes

**Comment by soapy1** [comment]
Expanding more on this:

**Upgrade notice for noarch packages**
Possible values for noarch when using 3.X, 4.[0-2]:
```
noarch: generic  # regular conda package that lives in noarch
noarch: True       # noarch package
noarch: False      # regular conda package
```
If the `noarch` value is anything else return message telling user to "installing this package requires a minimum conda version of 4.3".

**Parsing of info/files for hashes**
more info: https://github.com/conda/conda/pull/3702
Same things as above except for `info/files`. e.g. for older versions of conda `info/files` should exist for versions 3.x, 4.[0-2], for versions greater than 4.3, it should not. 

**Prelink scripts**
Figure out where prelink gets run, and return warning for 3.x, 4.[0-2] (NOTE: still install package). Message should be "Package <pkg name> uses a pre-link script. Pre-link scripts are potentially dangerous and highly discouraged. Future versions of conda may deprecate and ignore pre-link scripts. Consider using a different package."

e.g. use user warning (opposed to deprecation warning)
