### ISSUE TITLE
Setting LIBRARY_PATH etc. on "source activate"

### ISSUE THREAD

**Issue by bjodah** [conda/conda#3694]
Currently `$PATH` is modified upon `source activate myenv`.
Could we also modify `$LIBRARY_PATH`, `$C_INCLUDE_PATH` and `$CPLUS_INCLUDE_PATH` accoringly? (if not by default, at least enable a way to do this by setting e.g. `export CONDA_MODIFY_LIBRARY_PATH=1`

Edit: In case you're wondering about the motivation behind this you can look at the first cell in this notebook:
http://mybinder.org/repo/bjodah/example-conda-environment

**Comment by kalefranz** [comment]
Might be best to hear from @ilanschnell to start.

**Comment by ilanschnell** [comment]
When environment variables are required, I think it is important the set these environment variables explicitly, and not let `source activate` set then for you.  There have been suggestions to add setting other environment variables, such as `LD_LIBRARY_PATH`, which I am even more strongly opposed of.  Personally, I think that `source activate` should only set (or better modify) `PATH`, and things internal to conda (such as `CONDA_DEFAULT_ENV`).

**Comment by bjodah** [comment]
I see, is it safe to rely on `$CONDA_PREFIX` to always point to the current environment path?
A pragmatic approach would then be for me to look if that environment variable is set, if it is I can just append `$CONDA_PREFIX/lib` and `$CONDA_PREFIX/include` to `$LIBRARY_PATH` and `$C_INCLUDE_PATH`/`$CPLUS_INCLUDE_PATH`.

**Comment by kalefranz** [comment]
> $CONDA_PREFIX to always point to the current environment path?

For any conda version after conda 4.1.0, yes.

**Comment by mingwandroid** [comment]
This is an old issue. If you use our compilers we set done variables, not that one though as it's very non standard.

**Comment by TMiguelT** [comment]
What do you mean? `LIBRARY_PATH`, `LD_LIBRARY_PATH` etc are all standard Linux variables. They're used everywhere for things like this

**Comment by mingwandroid** [comment]
We disable the effect of `LD_LIBRARY_PATH` and all bills systems on Linux use LDFLAG which we set.

**Comment by TMiguelT** [comment]
Right, `LDFLAGS` would also be fine, except that it doesn't export this variable as part of the environment, so non conda tools can't see it (for instance if I `pip install` a package, or if I `make` compile something manually)

**Comment by mingwandroid** [comment]
If you install our compilers those variables are set.

**Comment by mingwandroid** [comment]
If you don't install our compilers you are free to use your open and create packages that set whatever variables you want.

This is entirely customizable and in your hands.

I recommend using our compilers though.

**Comment by TMiguelT** [comment]
I disagree, because that's forcing users to install another package they don't need (they probably have a working toolchain already). But at least we've found some workarounds:
* Using the conda compilers instead of system compilers (`conda install gcc`)
* Exporting variables, e.g. `export C_INCLUDE_PATH=$CONDA_PREFIX/include LD_LIBRARY_PATH=$CONDA_PREFIX/lib` etc)

**Comment by mingwandroid** [comment]
Don't use conda install gcc, it's deprecated. Use gcc_linux-64 instead.

We take the approach that we prefer not to do anything beyond setting PATH and a few conda specific env vars. Forced changing any commonly used variable will upset someone therefore we make it explicit by doing it in packages.

**Comment by mingwandroid** [comment]
Again, we don't use LD_LIBRARY_PATH so it makes no difference to our programs. You open compiled ones may care but you should avoid DT_RUNPATH by not setting the linker option --user-new-dtags.
