### ISSUE TITLE
Error installing python 2.7 with conda due to document saving permissions in windows

### ISSUE THREAD

**Issue by usryokousha** [conda/conda#3713]
Due to the corporate security software installed on my computer, document files such as *.doc or *.pdf files cannot be saved.  

Using an .exe installation package of anaconda I was able to install python 3.4, however when I created a new environment and attempted to install python 2.7 I ran into trouble.  Is it possible to create my own conda package for the python 2.7 installation, which doesn't install specific *.doc or *.pdf files?  Basically I would just take the install tarball and extract the files into a folder and then edit the install scripts to avoid installation of the document files.  Is there anyone familiar with what install scripts I would have to change and where I could find references to files such as "~/lib/mdb.doc"?

Thank you!

**Comment by kalefranz** [comment]
CC @ilanschnell

**Comment by kalefranz** [comment]
@usryokousha Where did you get your .exe installer of Anaconda?  Can you give us the download link?

**Comment by kalefranz** [comment]
The `~/lib/mdb.doc` looks highly suspicious.  I doubt it's coming from an Anaconda installer, but if it is, we need to know.

**Comment by kalefranz** [comment]
Also, can you get me *THE EXACT* .exe file you're trying to install?  You could try to email it to me, but I think it'll probably be too big.  I'd really like to get my hands on that exact file though.

**Comment by usryokousha** [comment]
Believe it or not I just got it from https://repo.continuum.io/archive and the file was Anaconda3-2.3.0-Windows-x86_64.exe for my Anaconda 3.4 install.  Once this was setup I used conda packages to install the other items necessary for the project I'm doing.  While working on my project it turned out I needed to install Python 2.7 to check an issue with backcompatibility.  When I tried installing Python 2.7 in a new conda env (I tried literally 5 different version) all packages contained .doc files and failed to extract.  When I took the .doc files out of the package and recompressed them, they failed to link correctly because the .doc files were obviously referenced in the setup file(s).

**Comment by kalefranz** [comment]
@usryokousha I really need to make sure we have the *exact* same file.  Your issue raises some security implications, and I want to address this properly.

Thanks for providing the `Anaconda3-2.3.0-Windows-x86_64.exe` file reference.

When I asked for the .exe file, I guess that's not what I'm after.  You say you tried multiple different versions of python 2.7.  THOSE (or even one of those) are the .tar.bz2 files I want to examine.  The python 2.7 windows files all seem to be less than 25MB, which means I think you can email one to me.

Please use kfranz@continuum.io

I want the *exact* .tar.bz2 file that's on your machine that extracted to have this .doc file in it.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1198
