### ISSUE TITLE
Test for virtualenv fails for conda env

### ISSUE THREAD

**Issue by cswarth** [conda/conda#3716]
Can someone help me understand how conda envs differ from those created by `virtualenv`? 

I ran across [this code](https://github.com/BD2KGenomics/toil/blob/master/Makefile#L185) that checks for an active virtualenv,

```
check_venv:
        @$(python) -c 'import sys; sys.exit( int( not hasattr(sys, "real_prefix") ) )' \
                || ( printf "$(red)A virtualenv must be active.$(normal)" ; false )
```

I have no idea why this requirement is enforced but this check fails if using conda to manage python environments.

I would like to modify this test to work with conda env as well.

**Comment by kalefranz** [comment]
Regarding the issue title, there's a lot of information linked here: https://github.com/conda-forge/staged-recipes/issues/1139
