### ISSUE TITLE
regression bug: https://github.com/conda/conda/issues/3235 appears to have resurrected itself in another place

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#3717]
The bug was that conda handled the channel "http://conda-01" incorrectly. Here's the stack trace in conda 4.2.11:

```
    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 479, in c
onda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 145, in _ma
in
        exit_code = args.func(args, p)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 65,
in execute
        install(args, parser, 'update')
      File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 308, in
install
        update_deps=context.update_dependencies)
      File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 526, in install
_actions
        force=force, always_copy=always_copy)
      File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 308, in ensure_
linked_actions
        fetched_in = is_fetched(dist)
      File "C:\Miniconda3\lib\site-packages\conda\install.py", line 727, in is_f
etched
        for fn in package_cache().get(dist, {}).get('files', ()):
      File "C:\Miniconda3\lib\site-packages\conda\install.py", line 675, in pack
age_cache
        add_cached_package(pdir, url)
      File "C:\Miniconda3\lib\site-packages\conda\install.py", line 633, in add_
cached_package
        schannel = Channel(url).canonical_name
      File "C:\Miniconda3\lib\site-packages\conda\models\channel.py", line 161,
in __call__
        c = Channel.from_value(value)
      File "C:\Miniconda3\lib\site-packages\conda\models\channel.py", line 211,
in from_value
        return Channel.from_url(value)
      File "C:\Miniconda3\lib\site-packages\conda\models\channel.py", line 196,
in from_url
        return parse_conda_channel_url(url)
      File "C:\Miniconda3\lib\site-packages\conda\models\channel.py", line 132,
in parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path
)
      File "C:\Miniconda3\lib\site-packages\conda\models\channel.py", line 122,
in _read_channel_configuration
        return (Url(host=host, port=port).url.rstrip('/'), path.strip('/') or No
ne,
    AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by mwiebe** [comment]
Adding some print statements gives the following specific variable values in the innermost calls:

```
url=http://conda-01/win-64/qt5-5.6.1.1-msvc2015rel_2.tar.bz2
host=conda-01
port=None
path=None
query=None
scheme=http
```

**Comment by kalefranz** [comment]
Yeah I know where the bug is.  4.2.11 introduced the requirement that every channel have a "name."  At least one directory level beyond the host and port.  I guess I didn't remember #3235, and was hoping everyone had at least one directory layer.

We need this to allow channels to have locations.  That is, we need to uniquely identify channels, but they also need to be able to move locations.  Each channel needs a deterministic name.  4.2.11 does that, but it assumes at least one directory level beyond the network location.

**Comment by mwiebe** [comment]
Cool, I guess the fix is to allow an empty string as the unique name, replacing None?

**Comment by kalefranz** [comment]
Maybe. I'm not sure just yet.  Thinking...

**Comment by kalefranz** [comment]
Need to chat with @mcg1969 about this. But I'm out of the office today.

**Comment by kalefranz** [comment]
@mwiebe How invasive would it be to your infrastructure to add one directory level?  Even if I hack a fix here, I think you're going to want to do this in the future.

We're progressively moving toward making "channel" a first-class-citizen in a package specification.  You'll be able to specify channel along with package on the command line.  Likely something similar to

    conda install channel_name/package_name

Note there I have `channel_name`, because channels fundamentally need to move locations with proper configuration.  The no-channel-name/empty-channel-name case just really doesn't work here.

I'm still thinking on solutions though...

**Comment by kalefranz** [comment]
Either way this is definitely a bug.  Whether we ultimately find a way to handle no-name channels cleanly, or just need to alert that the specified channel is invalid.

**Comment by mwiebe** [comment]
It's definitely something we can do, just in a phased way. This bug basically trickled down to the "reinstall miniconda" fix.

In the system you're moving towards, how is a channel on anaconda.org distinguished from a channel on someone's local server? If we make http://conda-01/stable the location where we put packages once we're happy with them for development environments, how should that interact with the wholly separate anaconda/"defaults" set of channels?

**Comment by kalefranz** [comment]
There's very robust configuration for all of that.  New in 4.2.  The docs are behind; still working on those.

But, to answer your exact question, all you would do is add

    custom_channels:
      stable: http://conda-01

in your condarc file.  (There are now multiple places for condarc configs, including in activated env directories.)

**Comment by gnarlie** [comment]
I'm seeing this also. I reference a channel of the form 'http://conda.ourserver.com' that I don't have control over right now. Any work around?

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.18.2
         python version : 2.7.11.final.0
       requests version : 2.11.1

**Comment by mwiebe** [comment]
Best workaround I've come up with is to wipe out all the contents of the `<anaconda>/pkgs` directory, then downgrade to 4.2.9.
