### ISSUE TITLE
Don't show outdated packages that can't be updated

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#372]
If a package has a newer version, but isn't built for the Python or NumPy version of the environment in question, it still shows up with `conda search --outdated`. This happens all the time for me because for whatever reason Python 3 packages aren't always built, leading to the all-too-often, "ooh, an update's available...aww, it isn't built for Python 3".

**Comment by mcg1969** [comment]
In this long strange trip through the older issues, I've just learned of a conda feature I didn't know existed.

**Comment by kalefranz** [comment]
Yeah same thing happened to me.

**Comment by asmeurer** [comment]
It itself is an "outdated" feature, from before update --all existed. These days you can run conda update --all --dry-run to see the "true" list of outdated packages.
