### ISSUE TITLE
Spyder not opening due to incomplete installation of anaconda

### ISSUE THREAD

**Issue by AshaSusan** [conda/conda#3723]
I had installed Anaconda suucessfully and could execute programs using spyder. One day I could not so I unsinstalled and reinstalled. But it didnt work
 Installed anaconda3-4.2.0 Windows 64 bit. Three error messages were shown hence used the following commands which worked
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" addpath
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkdirs
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkmenus

* Spyder is not opening

* Error shown:
![image](https://cloud.githubusercontent.com/assets/23001679/19621162/7e118138-98a9-11e6-84fa-4f5233723ffb.png)

* .ipython directory is not present in my folder.
I tried the following commands on command prompt. C://Users/Asha
conda install -f qt
conda install -f pyqt
got the following output
![image](https://cloud.githubusercontent.com/assets/23001679/19681656/e9868128-9ac7-11e6-912c-59d40944b2ec.png)

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1195
