### ISSUE TITLE
`conda skeleton pypi` doesn't respect --version option

### ISSUE THREAD

**Issue by mickeydonkey** [conda/conda#3724]
my environment:
win-64
conda=4.2.11-py35_0
just try `conda skeleton pypi logbook --version 0.12.5` it gives you build recipe for  version 1.0.0

**Comment by mickeydonkey** [comment]
this is mentioned by this SO question[http://stackoverflow.com/questions/39869535/how-to-specify-package-version-with-conda-skeleton-pypi-command], and I checked logbook 0.12.5 realse on pypi supports py35.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1487
