### ISSUE TITLE
Update $PATH in .zshrc to find conda 

### ISSUE THREAD

**Issue by akleiner2** [conda/conda#3728]
I'm using [zsh](github.com/robbyrussell/oh-my-zsh), and just ran the Miniconda install script according to [this guide](http://conda.pydata.org/docs/install/quick.html) to install conda. While it updates the `$PATH` variable in my `.bash_profile` to look for the conda binary, I have to copy and paste over the `export PATH=...` declaration in my `.zshrc`. This is obviously not a huge deal, but it would be great if the install script could do this automatically!

**Comment by kalefranz** [comment]
This issue was moved to conda/constructor#80
