### ISSUE TITLE
Conda no longer not respects anaconda config

### ISSUE THREAD

**Issue by srossross** [conda/conda#3735]
```
(sean@samson ~ •‿•) anaconda whoami
Using Anaconda API: http://api.beta.anaconda.org
Username: sean
```

You can see here that conda is using anaconda.org not beta.anaconda.org 

```

(sean@samson ~ •‿•) conda --debug create --debug --override  -c anaconda flask -n beta-2016-10-26-5
DEBUG conda.common.url:path_to_url(36): /Users/sean/anaconda/conda-bld converted to file:///Users/sean/anaconda/conda-bld
DEBUG conda.fetch:fetch_index(288): channel_urls=OrderedDict([('https://conda.anaconda.org/anaconda/osx-64', ('anaconda', 0)), ('https://conda.anaconda.org/anaconda/noarch', ('anaconda', 0))])
```

cc @csoja @dsludwig @kalefranz

**Comment by dsludwig** [comment]
This is probably a result of https://github.com/Anaconda-Platform/anaconda-client/pull/369.

**Comment by kalefranz** [comment]
ACK. 4.2 milestone added

**Comment by kalefranz** [comment]
@srossross Please `conda config --set channel_alias http://api.beta.anaconda.org`.  If you're logged in, you should find that the token is used as you'd expect.

**Comment by kalefranz** [comment]
As @bkreider suggested in https://github.com/Anaconda-Platform/anaconda-client/pull/369#issuecomment-255421530, importing `binstar_client` isn't quite an optimal experience.

I've isolated the anaconda client code here: https://github.com/conda/conda/blob/master/conda/gateways/anaconda_client.py

In a previous version of conda code, there was some fairly robust use of the anaconda server API: https://github.com/conda/conda/blob/8ec8dd45b84c72ffd6a2ad48d5e68db8c94b9ea0/conda/gateways/anaconda_client.py

I pulled it because it was too slow.

At this point we're duplicating anaconda-client logic to read tokens from the appdirs directory.  This component is all fully covered and verified by conda's own test code.

**Comment by srossross** [comment]
@kalefranz this sounds ok, but we will have to update the docs. 

I have a few remaining questions. with the command above I get:

```
conda config --set channel_alias http://api.beta.anaconda.org
conda create  --override  -c anaconda flask -n beta-2016-10-26-6
Fetching package metadata ....

CondaHTTPError: HTTP 404 NOT FOUND
for url <https://api.beta.anaconda.org/t/se-6eb9e5a0-55f4-4e7d-81b6-5479561f5553/anaconda/osx-64/repodata.json>

```

It seems like you need to set this to `http://conda.beta.anaconda.org` if that is the case then there are now two places you need to set the url one for the `api.*` using anaconda-client and one for `conda.*`. 

Also does `anaconda login` no longer work?  Do we now need to set the token manually?

**Comment by kalefranz** [comment]
Oh! Try 

    conda config --set channel_alias http://conda.beta.anaconda.org

Sorry that was my mistake before.  It should pick the token up for api.beta.anaconda.org.

**Comment by kalefranz** [comment]
The one feature that I don't think is quite duplicated right now is the use of anaconda-client's `-s` flag.  I'm open to thinking through what adding an `anaconda_site` config parameter would look like.  Where it would fall in precedence for choosing conda's `channel_alias` parameter, and how that would all work.  What are the error conditions if specified but not found.  etc etc

**Comment by kalefranz** [comment]
BTW, with conda 4.2.11, appending `/api` or `/conda` to an ip address SHOULD also work seamlessly.  Maybe @dsludwig could check that?

**Comment by kalefranz** [comment]
Some of the test cases for anaconda server related stuff are [here](https://github.com/conda/conda/blob/5bc0ae645301018574d44991aed062228b599a29/tests/models/test_channel.py#L91-L197).

**Comment by kalefranz** [comment]
@srossross This issue is waiting on your input here: https://github.com/conda/conda/pull/3758
