### ISSUE TITLE
Consider a Conda Plugin Framework

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3737]
I'd like to open a discussion on adding a plugin framework to conda.  What library should we use--or what patterns should we follow?  What have been others' experience with plugin frameworks?  What are best practices?

For libraries, I'm aware of [PluginBase](http://pluginbase.pocoo.org/) and [Yapsy](http://yapsy.sourceforge.net/).  I'd also consider setuptools entry_points a form of library.  I could also envision ways of implementing plugins just by using conda packages and subclassing.

Also, in what areas of conda's workflow should we consider adding shims to customize behavior?  How would the community envision using this feature, and what sorts of plugins would you want to (be able to) write?

**Comment by ManishGuptaBKBCE** [comment]
I want to create GUI using anaconda environment. Earlier I was using Tkinter and it was quite successful from python command prompt. Kindly suggest any plugins for anaconda and if yes, share the steps.
Thanks
