### ISSUE TITLE
conda env create giving ImportError for yaml package

### ISSUE THREAD

**Issue by leouieda** [conda/conda#3738]
`conda env create` suddenly started giving `"ImportError: No module named 'yaml'"` with latest miniconda on my TravisCI builbs: https://travis-ci.org/leouieda/website/builds/170917743

I changed nothing significant in my code. Tried rebuilding previous passing builds and started getting the same error. 

Is this something from a recent release?

**Comment by kalefranz** [comment]
Wow.  Thanks for the report.  I thought we had patched conda_env to use `ruamel_yaml`.  I guess not.

**Comment by kalefranz** [comment]
If you want to fix your build until we get this patched, you can add `conda install pyyaml`.

**Comment by leouieda** [comment]
@kalefranz installing pyyaml works, thanks! Please let me know when the patch lands in miniconda.
Thanks for the quick reply!

**Comment by kalefranz** [comment]
We'll probably be releasing the next conda patch release on Monday.  I'm not sure we'll release another Miniconda (maybe).  But once you have miniconda, just `conda update conda`.

**Comment by leouieda** [comment]
OK, perfect! That's always included in the CI scripts.
