### ISSUE TITLE
Using environment from file error

### ISSUE THREAD

**Issue by stevans** [conda/conda#3750]
Command that prompted error, output, and suggested text to post here is quoted below. The file inspection_plot_env.yml is attached at the bottom as a txt file.

> c221-103.maverick(14)$ conda env create -f inspection_plot_env.yml
> Fetching package metadata .........Could not connect to https://repo.continuum.io/pkgs/free/linux-64
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
> ```
> https://github.com/conda/conda/issues
> ```
> 
> Current conda install:
> 
> ```
>            platform : linux-64
>       conda version : 4.2.11
>    conda is private : False
>   conda-env version : 4.2.11
> conda-build version : not installed
>      python version : 2.7.12.final.0
>    requests version : 2.11.1
>    root environment : /work/03897/sbs2623/maverick/softwave/miniconda2  (writable)
> default environment : /work/03897/sbs2623/maverick/softwave/miniconda2
>    envs directories : /work/03897/sbs2623/maverick/softwave/miniconda2/envs
>       package cache : /work/03897/sbs2623/maverick/softwave/miniconda2/pkgs
>        channel URLs : https://repo.continuum.io/pkgs/free/linux-64
>                       https://repo.continuum.io/pkgs/free/noarch
>                       https://repo.continuum.io/pkgs/pro/linux-64
>                       https://repo.continuum.io/pkgs/pro/noarch
>         config file : None
>        offline mode : False
> ```
> 
> `$ /work/03897/sbs2623/maverick/softwave/miniconda2/bin/conda-env create -f inspection_plot_env.yml`
> 
> ```
> Traceback (most recent call last):
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
>     return_value = func(*args, **kwargs)
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
>     installer.install(prefix, pkg_specs, args, env)
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda_env/installers/conda.py", line 28, in install
>     prefix=prefix)
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
>     index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
>     for url in urls]
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
>     res = f(*args, **kwargs)
>   File "/work/03897/sbs2623/maverick/softwave/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
>     raise CondaRuntimeError(msg)
> CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b5c21dc4f90>: Failed to establish a new connection: [Errno -2] Name or service not known',)): https://repo.continuum.io/pkgs/free/linux-64
> ```

[inspection_plot_env.txt](https://github.com/conda/conda/files/557563/inspection_plot_env.txt)

**Comment by stevans** [comment]
In my browser I can access:

> https://repo.continuum.io/pkgs/free/linux-64/

but not:

> https://repo.continuum.io/pkgs/free/linux-64

which is the url listed in error message.

**Comment by stevans** [comment]
I solved the problem by defining the channel URLs in a .condarc file to be the default channels with trailing forward-slashes. Why does miniconda for linux (which I just installed minutes before getting this error) have default channel URLs that don't work?

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
