### ISSUE TITLE
Error when installing 'conda install mingw libpython'

### ISSUE THREAD

**Issue by anhduc1210** [conda/conda#3752]
I encountered this error when using the command `conda install mingw libpython` on cmd

> Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/noarch
> Could not connect to https://repo.continuum.io/pkgs/free/noarch
> Could not connect to https://repo.continuum.io/pkgs/pro/win-64
> Could not connect to https://repo.continuum.io/pkgs/free/win-64
> Could not connect to https://repo.continuum.io/pkgs/msys2/win-64
> Could not connect to https://repo.continuum.io/pkgs/msys2/noarch
> Could not connect to https://repo.continuum.io/pkgs/free/win-64
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-64
>           conda version : 4.2.11
>        conda is private : False
>       conda-env version : 4.2.11
>     conda-build version : 2.0.2
>          python version : 2.7.12.final.0
>        requests version : 2.11.1
>        root environment : C:\Program Files\Anaconda2  (read only)
>     default environment : C:\Program Files\Anaconda2
>        envs directories : C:\Users\****\.conda\envs
>                           C:\Program Files\Anaconda2\envs
>           package cache : C:\Users\****\.conda\envs\.pkgs
>                           C:\Program Files\Anaconda2\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ C:\Program Files\Anaconda2\Scripts\conda-script.py install mingw libpython`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in install
>         prefix=prefix)
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
>         index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\fetch.py", line 316, in fetch_index
>         for url in urls]
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\fetch.py", line 74, in func
>         res = f(*args, **kwargs)
>       File "C:\Program Files\Anaconda2\lib\site-packages\conda\fetch.py", line 234, in fetch_repodata
>         raise CondaRuntimeError(msg)
>     CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000050714E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)): https://repo.continuum.io/pkgs/free/win-64

Does anyone have the same problem? Any help is much appreciated.

**Comment by mmngreco** [comment]
+1

**Comment by anhduc1210** [comment]
I found the solution here http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers
@mmngreco 
I will close the topic.

**Comment by mingwandroid** [comment]
@anhduc1210 : `conda install mingw libpython`

.. where did you read to install this? I need to try to remove any such documentation or provide updates to it. `mingw` is deprecated now to the extent that I'd expect it not to work (and it never worked for 64-bit software). Instead you should install and use `m2w64-toolchain`.

**Comment by mingwandroid** [comment]
@ayimechan thanks, I will ask them to update their documentation.
