### ISSUE TITLE
ImportError on yaml when creating environment in freshly installed miniconda2 on windows

### ISSUE THREAD

**Issue by cstbgansanay** [conda/conda#3756]
Hello,

I am trying to install miniconda and a set of packages using a powershell script:

```
Write-Output "`nInstalling Miniconda for Windows ..."
$exe = "$wd\downloads\Miniconda2-latest-Windows-x86_64.exe"
&$exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /S /D=$wd\Miniconda2 | Out-Null
if(Test-Path "$wd\Miniconda2\Scripts") {
    $conda = "$wd\Miniconda2\Scripts\conda.exe"
    echo 'Listing environments...'
    &$conda info --envs
    echo 'Creating environment my_env...'
    Start-Process $conda "env create -f my_env.yml -y" -NoNewWindow -Wait
````

I get:

```
Installing Miniconda for Windows ...
Listing environments...
# conda environments:
#
root                     D:\my_software\Miniconda2

Creating environment my_env...
Traceback (most recent call last):
  File "D:\my_software\Miniconda2\Scripts\conda-env-script.py", line 3, in <module>
    import conda_env.cli.main
  File "D:\my_software\Miniconda2\lib\site-packages\conda_env\cli\main.py", line 35, in <module>
    from . import main_attach
  File "D:\my_software\Miniconda2\lib\site-packages\conda_env\cli\main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "D:\my_software\Miniconda2\lib\site-packages\conda_env\env.py", line 17, in <module>
    from . import yaml
  File "D:\my_software\Miniconda2\lib\site-packages\conda_env\yaml.py", line 8, in <module>
    import yaml
ImportError: No module named yaml
```

Even if I do a `conda install yaml` before creating the environment, this ImportError still shows up.

I can create an empty my_env, but then when I try to populate it through `conda install --name my_env --file spec-file-win.txt -y`, it fails with the error ` ' in: spec-file-win.txtrror: could not parse ' @ E X P L I C I T`

What can I do? Why does conda_env try to import yaml when it's not there?

Regards,
Guillaume

**Comment by cstbgansanay** [comment]
Ok, it seems to be fixed in 4.2.12. Waiting for the release.

**Comment by pellagic-puffbomb** [comment]
Hi, I get this error as well after using this Miniconda installer script released on Oct 24th:

```
Miniconda2-latest-Linux-x86_64.sh
```

We're also using the public continuum/miniconda3 base docker image (which hasn't been updated for a few weeks, so it still builds), so I wanted to check and see if the fix mentioned above would cover all the installers for different OSes and also that the problem wouldn't make it into the docker image (not sure how those are released?).

**Comment by alanhdu** [comment]
Just wanted to add that we're seeing this with the `Miniconda2-latest-Linux-x86_64.sh` installer right now too. (See https://travis-ci.org/ADI-Labs/density/builds/171564198).

**Comment by kalefranz** [comment]
We have a fix for this coming tomorrow.  https://github.com/conda/conda/pull/3740  Will update the miniconda installer too.

In the meantime you can just `conda install pyyaml`.
