### ISSUE TITLE
conda doesn't detect a failed download (v. 4.1.6)

### ISSUE THREAD

**Issue by bkreider** [conda/conda#3776]
This was a wild goose chase.  Note the download % jumps from 21% to 100% here.

<img width="817" alt="screen shot 2016-10-31 at 10 43 02 pm" src="https://cloud.githubusercontent.com/assets/1699478/19872693/7191aadc-9fbb-11e6-8a4c-dd67f8a54e0d.png">

The error message is then:  
```
Error: MD5 sums mismatch for download .....
```

We spent a lot of time trying to re-mirror this package a few times before noticing that the download was finishing at exactly 30 seconds which is the gunicorn timeout on the webserver serving the file.  Why is conda ignoring the truncated error condition?  In a perfect world, it would restart the download using ranges to request the rest of the file.

**Comment by kalefranz** [comment]
We use requests. Happy to accept a pull request if you can get to it before I do.

**Comment by kalefranz** [comment]
This logic was reworked in conda 4.3 to detect failed downloads.
