### ISSUE TITLE
Channel conda/anaconda gets extra conda

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3778]
I don't know what is going on here.  Also, it is very weird that he had to turn on "subdomains" in his Repo install, to avoid channel_alias from adding "conda" twice to his path, when he clones:

but since the channel_alias is set to https://anaconda..../conda/, the conda tool thinks the channel is "conda/anaconda". That becomes an issue because it now wants to download from https://.../conda/conda/anaconda/linux-64/ .. which is too many condas.

CC @bkreider @csoja @JeremyEnns

**Comment by kalefranz** [comment]
Does anybody CC'ed on this ticket remember what the issue referred to?  Is it still an issue?

**Comment by bkreider** [comment]
This was a desk support issue.  You can close it for now and i'll reopen it if we run into it again.

**Comment by kalefranz** [comment]
Cool. Thanks Brad.
