### ISSUE TITLE
Conda env spontaneously removed :confused:

### ISSUE THREAD

**Issue by robinandeer** [conda/conda#3782]
Hi,

we are running conda 4.2.11 on a Scientific Linux cluster

Recently we've experienced some strange issues where an entire conda environment suddenly disappears, leaving a bin folder with only some links; `activate`, `deactivate`, and `conda` left in it.

What we've observed is that it seems to do with many `source activate [env]` commands being executed at the same time.

Please let me know if I can provide any other information to aid in debugging the issue

**Comment by kalefranz** [comment]
related to https://github.com/conda/conda/issues/2502

**Comment by kalefranz** [comment]
Are you still seeing this in recent versions of conda?  Latest is conda 4.3.17.

**Comment by robinandeer** [comment]
Nope we haven't seen this happen again. However, we moved to using the default root environment to avoid excessively sourcing environments 🙂

**Comment by kalefranz** [comment]
I'm guessing conda 4.3 fixed the root cause of the problem here.
