### ISSUE TITLE
conda install env error

### ISSUE THREAD

**Issue by xyl576807077** [conda/conda#3786]
I try to install Python3.4 Anaconda env
`conda create -n py34 python=3.4 anaconda`

then

'
Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.19.0
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : D:\Anaconda  (writable)
    default environment : D:\Anaconda
       envs directories : D:\Anaconda\envs
          package cache : D:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ D:\Anaconda\Scripts\conda-script.py create -n lala python=3.4 anaconda`

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in con
da_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main

        exit_code = args.func(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 68, in
 execute
        install(args, parser, 'create')
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in in
stall
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection er
ror: ('_ssl.c:574: The handshake operation timed out',): https://repo.continuum.
io/pkgs/free/win-64/fastcache-1.0.2-py34_1.tar.bz2
'

**Comment by kalefranz** [comment]
This is just a timeout error.  Please try again.
