### ISSUE TITLE
Error while installing Tensorflow

### ISSUE THREAD

**Issue by prasants** [conda/conda#3790]
Got this error message while installing Tensorflow with a virtualenv:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.18.1
         python version : 2.7.10.final.0
       requests version : 2.7.0
       root environment : /Users/prasant/anaconda  (writable)
    default environment : /Users/prasant/anaconda/envs/tensorflow
       envs directories : /Users/prasant/anaconda/envs
          package cache : /Users/prasant/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/prasant/anaconda/envs/tensorflow/bin/conda install jupyter`

    Traceback (most recent call last):
      File "/Users/prasant/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/prasant/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/prasant/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/prasant/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/prasant/anaconda/pkgs/nbformat-4.1.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

Edit: Adding a little more detail. I am trying to create a virtualenv to run Tensorflow. After creating the env, the error is caused by "conda install anaconda", or even "conda install jupyter".

**Comment by mingwandroid** [comment]
It looks like you have installed anaconda into your home directory, @prasants in that case do not use `sudo`.

**Comment by arpita8** [comment]
<img width="180" alt="screen shot 2017-03-09 at 2 06 07 pm" src="https://cloud.githubusercontent.com/assets/22601715/23766205/d98aa438-04d1-11e7-80e6-49388b87c2bc.png">
Why am i getting this error?? What am i doing wrong?

**Comment by arpita8** [comment]
<img width="648" alt="screen shot 2017-03-09 at 2 14 07 pm" src="https://cloud.githubusercontent.com/assets/22601715/23766433/c3f3428c-04d2-11e7-894f-cf764e99f2a8.png">
 i am getting this error using  sudo conda install -c conda-forge tensorflow

**Comment by arpita8** [comment]
<img width="866" alt="screen shot 2017-03-09 at 2 18 42 pm" src="https://cloud.githubusercontent.com/assets/22601715/23766568/5c517a08-04d3-11e7-8c05-9acfe6f33ec7.png">

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
