### ISSUE TITLE
Using a local conda environment requires --prefix to always be specified

### ISSUE THREAD

**Issue by bheklilr** [conda/conda#3791]
I recently learned that conda allows you to create and use environments local to a project by using the `--prefix` argument to `conda create` instead of `--name`:

    cd path/to/project
    conda create --prefix=env
    activate env

This seems to be very attractive since I have a number of environments and it can be difficult remembering exactly which one I should use with which project.  Instead of having all of my environments in one place in AppData, I can create an environment locally and always know which one to use with each project.  The biggest downside is that instead of triggering off of the `CONDA_PREFIX` environment variable, it seems that `conda install` and friends trigger off of `CONDA_DEFAULT_ENV` and look for it in the conda installation folder.  This can be easily mitigated by specifying the prefix again:

    conda install -p env numpy

but if I change directories this becomes cumbersome to specify.  Without I get the error `environment does not exist: C:\path\to\Miniconda\envs\env ... Use 'conda create' to create an environment before installing packages into it`

Would it be possible to get any environment to be treated as a first class citizen regardless of where it's located on disk?

**Comment by kalefranz** [comment]
Everything requested here is being incorporated into conda 4.4.
