### ISSUE TITLE
version inference seems to assume .0 (zero) instead of .* (anything)

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3795]
I cannot definitively tell if this is the case or not, but it appears that when I do something like:

```
conda install bokeh==0.12
```

And don't specify a patch version that Conda automatically assumes `.0`, IOW the statement above is equivalent to:

```
conda install bokeh==0.12.0
```

I would suggest that this is surprising to the end user who I would think, if they haven't specified a patch version, is expecting the latest patch version in the 0.12 release series.  IOW they are expecting that the first statement is equivalent instead to:

```
conda install bokeh==0.12.*
```

But perhaps there is another way to think about this that I am not aware of.

It is an aside, but I should say that I think the "wildcard" syntax that I see of `==0.12*` rather surprising.  Normal regex rules would suggest that such an expression would equivalently match `==0.129`, which surely Conda wouldn't do, but on the surface it makes one worry that it might.

**Comment by kalefranz** [comment]
I never get this right either.  I *think* `==` is an "exact" match, whereas `=` is a fuzzy match.

I also hate seeing `=0.12*`.  I never know if I can trust it.

**Comment by ijstokes** [comment]
@kalefranz  I'm not sure I believe this.  I put in my environment.yml file

    - anaconda =4.3

And just expected it to pick up 4.3.1.  It didn't.  It picked up 4.3.0.  Yes, there was other stuff in there.  But when I put in 4.3.1 explicitly it still worked.  I'd buy your argument if my experience just now was that `=4.3.1` meant that some other part of my environment.yml file couldn't be satisfied, so 4.3.0 was needed.  But given that didn't happen I think there is a problem.

OR, are you saying that I needed to have

    - anaconda =4.3.*

Or is it

    - anaconda =4.3*

That latter syntax is sucky, if you ask me.  Because RE rules would suggest this matches 4.30 and 4.31, which is not at all what I mean.  Thanks for clarifying.  I'm not reopening, since I'm guessing it is a weird conda syntax issue that I just don't get yet, but I'd still say we should consider conda might not be doing the right thing here.
