### ISSUE TITLE
updating conda through pip breaks it

### ISSUE THREAD

**Issue by znaiman** [conda/conda#3799]
A recent upgrade of conda broke my installation. When running any conda command, I get an error including:
  
File "/usr/lib/python2.7/site-packages/conda/models/channel.py", line 131, in <module>
    TOKEN_RE = re.compile(r'(/t/[a-z0-9A-Z-]+)?(\S*)?')

I find that if I change the line of that file to the following, everything is happy again:
 TOKEN_RE = re.compile(r'(/t/[a-z0-9A-Z-]+)?(\S.*)?')

(notice the . before the * toward the end)

**Comment by kalefranz** [comment]
Conda cannot be installed or updated with pip.  Not much different than not being able to `pip install python3`.
