### ISSUE TITLE
compile_missing_pyc needs an option to skip some files

### ISSUE THREAD

**Issue by dan-blanchard** [conda/conda#380]
The function `compile_missing_pyc` currently tries to compile every single `.py` file it encounters on Python 2.x, and this can prevent packages that include syntactically invalid `.py` files for testing from functioning properly. 

For example, I created a `pylint` recipe (ContinuumIO/conda-recipes#32) and it works for Python 3 (because conda only uses `compile_missing_pyc` for Python 2), but it fails with Python 2 because the forced compilation of some invalid Python files. For code analysis tools like `pylint` it is important to have the ability to include test files that have invalid syntax.

Fixing this issue will likely require adding something to the `meta.yaml` file format that specifies the files that should be skipped, but I wasn't exactly sure how you would want to approach that (which is why this an issue and not a PR).

**Comment by jakirkham** [comment]
This discussion seems to be better addressed here ( https://github.com/conda/conda-build/issues/686 ) at this point. Given the command has been removed from `conda` this should be closed IMHO.
