### ISSUE TITLE
What does package name ending with '@' mean?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#3805]
I see several places where packages ending with '@' are being referred to, in conda code:

conda/models/dist.py
```python
 72     def is_feature_package(self):
 73         return self.dist_name.endswith('@')
```

conda/cli/main_search.py
```python
185         if '@' in name:
186             continue
```

tests/test_resolve.py
```python
221     def test_anaconda_mkl_2(self):
222         # to test "with_features_depends"
223         dists = r.install(['anaconda 1.5.0', 'python 2.7*', 'numpy 1.7*', 'mkl@'])
```

I don't see any of '@' or 'with_features_depends' anywhere in conda docs. Am I looking at the wrong place?

* http://conda.pydata.org/docs/spec.html#package-match-specifications (for '@')
* http://conda.pydata.org/docs/search.html?q=with_features_depends&check_keywords=yes&area=default (for 'with_features_depends')

Can we please have this documented somewhere? Even after going through http://conda.pydata.org/docs/building/bpp.html I couldn't figure out a scenario using conda-build and conda index to create repodata.json with `with_feature_depends`

**Comment by kalefranz** [comment]
CC @mcg1969 

It's an *internal-only* symbol that @mcg1969 added for housekeeping when the `Dist` object was just a string we were constantly parsing.  The `@` symbol kludge could possibly go away in the future.

**Comment by nehaljwani** [comment]
@kalefranz What about `with_feature_depends`? Is it also internal only? I see it being used at https://repo.continuum.io/pkgs/free/linux-64/repodata.json 

I tried the following:

In a new environment, install the feature mkl, from the [pro](https://repo.continuum.io/pkgs/pro/linux-64) repo.
```bash
conda install -c https://repo.continuum.io/pkgs/pro/linux-64 mkl
```

Then install `anaconda-2.4.1-np110py27_0` which has `with_feature_depends` in repodata.json:
```bash
conda install anaconda=2.4.1=np110py27_0
```

However, this tells me, that it will replace the scipy[mkl] package with the non-mkl version:
```bash
scipy:              0.16.1-np110py35_p0 [mkl] --> 0.16.0-np110py27_1
```

Now, if I cancel the previous command, and replace it with:
```bash
conda install anaconda=2.4.1=np110py27_0 mkl@
```

It wants to keep the mkl package, rather, pin it to the required version (which is expected):
```bash
scipy:              0.16.1-np110py35_p0 [mkl] --> 0.16.0-np110py27_p1 [mkl]
```

Now, what I don't understand is, two things:
* Why do I need to pass mkl@ ?
* Why does the mkl package at https://repo.continuum.io/pkgs/free/linux-64 not track the mkl feature?

**Comment by kalefranz** [comment]
RE `with_feature_depends` https://github.com/conda/conda/pull/5191

**Comment by kalefranz** [comment]
Honestly, I *still* don't understand all of this feature stuff.  Yeah, I'm serious.  I still get confused about the different between `features` and `track_features` in index.json.  I'm never quite sure if I'm supposed to append or prepend an `@` sign, or when and why.  Features is still all a big mess as far as I'm concerned.
