### ISSUE TITLE
Conda error while attempting to install h5py from conda-forge on macOS 10.12.1

### ISSUE THREAD

**Issue by JimBiardCics** [conda/conda#3809]
Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/jbiard/miniconda3  (writable)
    default environment : /Users/jbiard/miniconda3/envs/SERDP
       envs directories : /Users/jbiard/miniconda3/envs
          package cache : /Users/jbiard/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.binstar.org/pelson/osx-64
                          https://conda.binstar.org/pelson/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jbiard/.condarc
           offline mode : False

`$ /Users/jbiard/miniconda3/envs/SERDP/bin/conda install h5py`

    Traceback (most recent call last):
      File "/Users/jbiard/miniconda3/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jbiard/miniconda3/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/jbiard/miniconda3/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/jbiard/miniconda3/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/h5py-2.6.0-np111py27_6.tar.bz2: https://conda.anaconda.org/conda-forge/osx-64/h5py-2.6.0-np111py27_6.tar.bz2

**Comment by soapy1** [comment]
Looks like this is a server error opposed to a client error. When I ran `conda install h5py` I could not reproduce the error. Have you tried running install again?

**Comment by JimBiardCics** [comment]
I did, and it worked fine. The message from conda asked me to post it as an issue, so I did. You can likely close this.

**Comment by soapy1** [comment]
Awesome 🍌 , thanks!
