### ISSUE TITLE
conda env update : does not support --prefix

### ISSUE THREAD

**Issue by joewalnes** [conda/conda#3810]
The `conda env update` does not support the `--prefix` / `-p` argument.

```
$ conda info | grep version
          conda version : 4.2.12
      conda-env version : 4.2.12
    conda-build version : 1.20.3
         python version : 2.7.11.final.0
       requests version : 2.10.0

$ conda env update -p ./conda-env
usage: conda-env [-h] {attach,create,export,list,remove,upload,update} ...
conda-env: error: unrecognized arguments: -p
```

**Comment by soapy1** [comment]
I don't know if I've interpreted your issue correctly, but I think all you need to do is drop the `env` so your command becomes `conda update -p ./conda-env`

**Comment by joewalnes** [comment]
Here's what I'm trying to achieve:

I have a bootstrap script that always gets run when a project gets checked out or updated. This is to make it easy for users who are not conda-savvy, and for continuous build machines, etc.

I'd like to have a cmd I can run that can create the environment (from environment.yml) the first time it's run, and then update on subsequent runs.

* `conda env update` works really well for this, but doesn't allow custom prefixes. 
* `conda env create --prefix foo` will respect the prefix, but it fails if the env has already been created (I'm working around this at the moment with `--force`, but it's slow as it rebuilds the complete env every time).
* `conda update -prefix foo` does not read environment.yml, so doesn't work for me.

**Comment by soapy1** [comment]
I see, I think the right way to do this is `conda env update -n foo`. This will use the environment.yml file to update an env named foo.

**Comment by joewalnes** [comment]
But that doesnt work with --prefix. I always use local prefix based envs to ensure projects are isolated from each other.

**Comment by jzwinck** [comment]
I have this issue too.  I would really like `conda env update --prefix` to be supported so I can update an environment which is not in the canonical location.

**Comment by Rudd-O** [comment]
How is this still an issue?  I need this too.

**Comment by JDFagan** [comment]
I have this issue too as we like to use the conda env update command for CI/CD and sometimes the env might not exist yet and we want env to be created but may not want the prefix defined in yml file as that is typically the developer's prefix and not one we use for rollout in official production envs.
