### ISSUE TITLE
"conda env remove" will delete a directory named like the environment

### ISSUE THREAD

**Issue by sdvillal** [conda/conda#3814]
This is, I think, a very unfortunate bug of conda-env:
```sh
mkdir -p test/i-do-not-want-to-delete-this-dir
cd test
conda env remove -n i-do-not-want-to-delete-this-dir
```
conda goes wild and deletes the ```i-do-not-want-to-delete-this-dir``` directory.

I'm on these versions of conda/conda-env:
```
conda                     4.1.12                   py27_0    conda-forge
conda-env                 2.5.2                    py27_0    conda-forge
```

**Comment by sdvillal** [comment]
Note that this happens only if the environment does not exist. Extended example:

```sh
mkdir -p test/i-do-not-want-to-delete-this-dir
conda create -n i-do-not-want-to-delete-this-dir python
cd test
# run this, the environment gets removed and the directory is not touched
conda env remove -n i-do-not-want-to-delete-this-dir  
# run it again, the directory is removed
conda env remove -n i-do-not-want-to-delete-this-dir
```

**Comment by dsm054** [comment]
I just got burned by this.  One of my team speculated that it might be a consequence of some legacy local-folder-environment support, but whether that's true or not it seems needlessly dangerous in practice.
