### ISSUE TITLE
Strange formatting of message when package not found

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3816]
I'm trying to install `rpy2` while offline.  It is available in `~/anaconda/pkgs` so I had hoped that would be sufficient to be able to install it.  But Conda can't find it and reports this message:

Strangely worded and formatted error message when package is not found:

```
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - rpy2
```

What does the empty single quoted string indicate (after *Package not found:*)?

Why do we put the Python exception name in the text we display to the end user so we effectively duplicate the message "PackageNotFoundError: Package not found:"?

If being offline is the  problem (which it might be), why don't we indicate something in a nice way instead of with a stack trace?

What does Conda need to be able to install the package from the local version?

**Comment by kalefranz** [comment]
Fixed.  At least in 4.3 it is.  I guess this report had to be for 4.2.  Feeling like 4.3 should be our LTS version though.  Conda-forge is hopefully moving there soon.
