### ISSUE TITLE
`conda env export` fail

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3819]
`conda env -h` help (the first output block below) suggests that I should be able to do a simple `export` to output (presumably) my current Conda environment, however when I attempt it (second output block) I get a message suggesting I can't do this and an alternative is proposed, which I then attempt (third output block), and that reports an error and doesn't output anything.

```
➜  notebooks git:(master) ✗ conda env export -h
usage: conda-env export [-h] [-c CHANNEL] [--override-channels] [-n NAME]
                        [-f FILE] [--no-builds] [--ignore-channels]

Export a given environment

Options:

optional arguments:
  -h, --help            Show this help message and exit.
  -c CHANNEL, --channel CHANNEL
                        Additional channel to include in the export
  --override-channels   Do not include .condarc channels
  -n NAME, --name NAME  name of environment (in /Users/ijstokes/anaconda/envs)
  -f FILE, --file FILE
  --no-builds           Remove build specification from dependencies
  --ignore-channels     Do not include channel names with package names.

examples:
    conda env export
    conda env export --file SOME_FILE
```

```
➜  notebooks git:(master) ✗ conda env export --file root.yml


CondaEnvException: Conda Env Exception: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.
```

```
➜  notebooks git:(master) ✗ conda env export -n root --file root.yml
DEPRECATION: The default format will switch to columns in the future. You can use --format=legacy (or define a list_format in your pip.conf) to disable this warning.


CondaValueError: Value error: invalid package specification: None:///<unknown>::appscript=1.0.1=py27_0
```

I tried again after doing a `source activate root` and got the same result.  I then switched to a different environment and it worked perfectly (no deprecation warnings or anything).

I think trying to snapshot the root environment might be a common sort of operation for someone to perform, but perhaps not.  I don't understand why I sometimes had the `DEPRECATION` warning and sometimes not.

**Comment by gdraps** [comment]
As a fix, try running `conda update --all` (which removed `None:///<unknown>` from all package versions for me), and try `conda env export -n root` again.

**Comment by kalefranz** [comment]
The `None:///<unknown>` package versions were fixed in conda a while back.
