### ISSUE TITLE
Fail to install pythonocc offline

### ISSUE THREAD

**Issue by sodynamic** [conda/conda#3822]
I have downloaded the pythonocc tar, but meet some problem when i try to conda install. Here is the info:

(C:\Users\LiuMeng-YF\Anaconda3) H:\python exercise>conda install win-64-pythonocc-core-0.17-py35_vc14_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.7
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\LiuMeng-YF\Anaconda3  (writable)
    default environment : C:\Users\LiuMeng-YF\Anaconda3
       envs directories : C:\Users\LiuMeng-YF\Anaconda3\envs
          package cache : C:\Users\LiuMeng-YF\Anaconda3\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\LiuMeng-YF\.condarc
           offline mode : False

`$ C:\Users\LiuMeng-YF\Anaconda3\Scripts\conda-script.py install win-64-pythonocc-core-0.17-py35_vc14_0.tar.bz2`

    Traceback (most recent call last):
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\cli\install.py", line 209, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\misc.py", line 66, in explicit
        if not is_url(url_p):
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\common\url.py", line 72, in is_url
        p = urlparse(url)
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "C:\Users\LiuMeng-YF\Anaconda3\lib\site-packages\conda\common\url.py", line 55, in urlparse
        if on_win and url.startswith('file:'):
    AttributeError: 'NoneType' object has no attribute 'startswith'

I hope this info may help to solve the problem.
Thanks.

**Comment by sodynamic** [comment]
Well, it seems to be a small problem, because when i finally connect my computer to the internet, I successfully install pythonocc with
conda install -c https://conda.anaconda.org/dlr-sc pythonocc-core=0.17

The problem may be something about dependency. Because there are other packages are installed during pythonocc installation. Here is the package info

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freeimageplus-3.17.0       |           vc14_0         2.0 MB
    gl2ps-1.3.8                |           vc14_3          98 KB
    tbb-4.3.6                  |           vc14_1         720 KB
    conda-4.2.12               |           py35_0         446 KB
    oce-0.17.2                 |           vc14_4        27.9 MB
    pythonocc-core-0.17        |      py35_vc14_0        38.8 MB
    ------------------------------------------------------------
                                           Total:        70.0 MB

The following NEW packages will be INSTALLED:

    freeimageplus:  3.17.0-vc14_0    [vc14]
    gl2ps:          1.3.8-vc14_3     [vc14]
    oce:            0.17.2-vc14_4    [vc14]
    pythonocc-core: 0.17-py35_vc14_0 [vc14]
    tbb:            4.3.6-vc14_1     [vc14]

The following packages will be UPDATED:

    conda:          4.2.11-py35_0    --> 4.2.12-py35_0

Anyway, thanks a lot.

**Comment by drewkett** [comment]
I ran into the same error for a different package. If you call conda install with a more complete path it seems to work. As in

`conda install ./win-64-pythonocc-core-0.17-py35_vc14_0.tar.bz2`

instead of 

`conda install win-64-pythonocc-core-0.17-py35_vc14_0.tar.bz2`

**Comment by kalefranz** [comment]
Installing from tarballs has been fixed in recent versions of conda.  Latest is conda 4.3.17.
