### ISSUE TITLE
version of sphinx

### ISSUE THREAD

**Issue by sodynamic** [conda/conda#3823]
I have installed sphinx 1.4.8
but when i run
sphinx-build --version
it says the version of sphinx is 1.3.1

I have tried remove the sphinx and re-install it, this problem remains.

**Comment by soapy1** [comment]
I can't seem to reproduce the problem. When I install sphinx with `conda install sphinx` I get
```
$ sphinx-build --version
Sphinx (sphinx-build) 1.4.8
```

what is the output of `conda list | grep sphinx` ?

**Comment by nehaljwani** [comment]
@sodynamic What's the output for `where sphinx-build`

**Comment by sodynamic** [comment]
This is the output,
(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>where sphinx-build
C:\Users\LiuMeng-YF\Anaconda3\Scripts\sphinx-build.exe

**Comment by nehaljwani** [comment]
I was able to reproduce it like this (in Windows and Linux):
```bash
$ source /tmp/scratchconda/bin/activate 
$ pip install sphinx==1.3.1
$ conda install sphinx
$ sphinx-build --version
```
Note that the pip package's name is '**S**phinx' and that provided by conda is '**s**phinx'.

@sodynamic What's the output of `pip freeze`

**Comment by sodynamic** [comment]
Here is the output of pip freeze:

(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>pip freeze
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.3
anaconda-navigator==1.3.2
appdirs==1.4.0
argcomplete==1.0.0
astroid==1.4.7
astropy==1.2.1
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.3
boto==2.43.0
Bottleneck==1.1.0
cffi==1.8.3
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
comtypes==1.1.2
conda==4.2.12
conda-build==2.0.7
configobj==5.0.6
contextlib2==0.5.3
cryptography==1.5.2
cycler==0.10.0
Cython==0.25.1
cytoolz==0.8.0
dask==0.11.1
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd===c328ab7
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
future==0.15.2
gevent==1.1.2
greenlet==0.4.10
h5py==2.6.0
HeapDict==1.0.0
iapws==1.1.2
idna==2.1
imagesize==0.7.1
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
lazy-object-proxy==1.2.1
llvmlite==0.14.0
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==1.5.3
menuinst==1.4.2
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.9
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.29.0
numexpr==2.6.1
numpy==1.11.2
odo==0.5.0
openpyxl==2.4.0
pandas==0.19.0
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pefile==2016.3.28
pep8==1.7.0
pickleshare==0.7.4
Pillow==3.4.2
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.8
psutil==4.4.2
py==1.4.31
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.16
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.1.3
PyInstaller==3.2
pylint==1.5.4
pyOpenSSL==16.0.0
pyparsing==2.1.4
pyreadline==2.1
pytest==3.0.3
python-dateutil==2.5.3
pytz==2016.7
pywin32==220
PyYAML==3.12
pyzmq==16.0.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
requests==2.11.1
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.18
scipy==0.18.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.3.1
sphinx-rtd-theme==0.1.9
spyder==3.0.1
SQLAlchemy==1.1.3
statsmodels==0.6.1
sympy==1.0
tables==3.2.2
toolz==0.8.0
tornado==4.4.2
traitlets==4.3.1
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.11
widgetsnbextension==1.2.6
win-unicode-console==0.5
wrapt==1.10.8
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2

**Comment by soapy1** [comment]
```
Sphinx==1.3.1
```
Looks like that may be a problem.... could you try `pip uninstall Sphinx` and then reinstall with conda

**Comment by sodynamic** [comment]
well, this time it works. Thanks!


(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>pip uninstall Sphinx
Uninstalling Sphinx-1.3.1:
  c:\users\liumeng-yf\anaconda3\lib\site-packages\sphinx
  c:\users\liumeng-yf\anaconda3\lib\site-packages\sphinx-1.3.1-py3.5.egg-info
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-apidoc-script.py
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-apidoc.exe
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-autogen-script.py
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-autogen.exe
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-build-script.py
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-build.exe
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-quickstart-script.py
  c:\users\liumeng-yf\anaconda3\scripts\sphinx-quickstart.exe
Proceed (y/n)? y
  Successfully uninstalled Sphinx-1.3.1

(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>conda install sphinx
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Users\LiuMeng-YF\Anaconda3:
#
sphinx                    1.4.8                    py35_0

(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>conda uninstall sphinx
Fetching package metadata .........
Solving package specifications: ..........

Package plan for package removal in environment C:\Users\LiuMeng-YF\Anaconda3:

The following packages will be REMOVED:

    sphinx: 1.4.8-py35_0
    spyder: 3.0.1-py35_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%

(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>conda install sphinx -y
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/msys2/win-64
Could not connect to https://repo.continuum.io/pkgs/pro/noarch
Could not connect to https://repo.continuum.io/pkgs/pro/win-64
Could not connect to https://repo.continuum.io/pkgs/free/noarch
Could not connect to https://repo.continuum.io/pkgs/free/win-64
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch
......
Solving package specifications: ..........

Package plan for installation in environment C:\Users\LiuMeng-YF\Anaconda3:

The following NEW packages will be INSTALLED:

    sphinx: 1.4.8-py35_0

Linking packages ...
[      COMPLETE      ]|##################################################| 100%

(C:\Users\LiuMeng-YF\Anaconda3) C:\Users\LiuMeng-YF>sphinx-build --version
Sphinx (sphinx-build) 1.4.8

**Comment by soapy1** [comment]
Awesome! Thanks @sodynamic and @nehaljwani !
