### ISSUE TITLE
Trying to setup Jupyter and conda for R

### ISSUE THREAD

**Issue by kirankunapuli** [conda/conda#3825]
I'm trying to setup Jupyter and conda for R. 
When I enter `conda install -c r r-essentials` the following error occurs.

> I tried the solution mentioned in #3271 but it didn't work for me!

> I guess changing the R url will solve this issue, as the latest version released right now is R 3.3.2

Fetching packages ...
Could not connect to https://conda.anaconda.org/r/win-64/r-base-3.3.1-0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\kk\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\kk\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\kk\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py install -c r r-essentials`

    Traceback (most recent call last):
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\kk00\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 215

**Comment by mingwandroid** [comment]
The latest R on conda is 3.3.1, not 3.3.2.

Can you enter the following into the `Anaconda Prompt`:

`conda config --add channels r`

.. and try again please?

**Comment by kirankunapuli** [comment]
Hi, 

I tried your suggestion, but it didn't work. I'm still getting the exact same error.

**Comment by mingwandroid** [comment]
Can you show the output from `conda info` after you added the r channel please?

**Comment by mingwandroid** [comment]
.. and also try this:

`conda config --add channels https://repo.continuum.io/pkgs/r`

**Comment by kirankunapuli** [comment]
**Output of `conda info` is**

Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\kk\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\kk\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\kk\.condarc
           offline mode : False


**Error after typing `conda config --add channels https://repo.continuum.io/pkgs/r` and trying `conda install -c r r-essentials` is**

Fetching packages ...
Could not connect to https://conda.anaconda.org/r/win-64/r-base-3.3.1-0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\kk\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\kk\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\kk\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\kk\.condarc
           offline mode : False



`$ C:\Users\kk\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py install -c r r-essentials`




    Traceback (most recent call last):
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "C:\Users\kk\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'D' (0x44) at index 236

**Comment by mingwandroid** [comment]
Since you added `r` to your channels, can you now try without `-c r`?

**Comment by kirankunapuli** [comment]
**It worked.** 

So the solution is, 
1. `conda config --add channels https://repo.continuum.io/pkgs/r`
2. `conda install r-essentials`

Then `jupyter notebook`. Now I can create R Notebooks.

Thank you for your help.
