### ISSUE TITLE
Was trying to update Spyder to 3.01 now seems that conda is very broken?

### ISSUE THREAD

**Issue by dartdog** [conda/conda#3827]
Linux 16.04
Would sure like to preserve as much as possible as I have a custom Tensorflow build in one of the environments..
I had run a prior update command the broke conda and I did a new install of miniconda as suggested here: https://github.com/conda/conda/issues/3437 (See bottom)
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 2.6.0
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/tom/anaconda3  (writable)
    default environment : /home/tom/anaconda3
       envs directories : /home/tom/anaconda3/envs
          package cache : /home/tom/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/tom/.condarc
           offline mode : False
`$ /home/tom/anaconda3/bin/conda install -c anaconda spyder=3.0.1`
    Traceback (most recent call last):
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/install.py", line 977, in link
      File "/home/tom/anaconda3/lib/python3.5/site-packages/conda/install.py", line 369, in update_prefix
    FileNotFoundError: [Errno 2] No such file or directory: '/home/tom/anaconda3/lib/icu/54.1/Makefile.inc'

**Comment by dartdog** [comment]
and It broke the Conda link tom@tomServal:~$ conda list
bash: /home/tom/anaconda3/bin/conda: No such file or directory

**Comment by dartdog** [comment]
So I reinstalled using:
     bash ~/Downloads/Miniconda3-latest-Linux-x86_64.sh -bfp ~/anaconda3
and all goes well except the force file option?
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
mkdir: cannot create directory ‘/home/tom/anaconda3/envs’: File exists
Python 3.5.2 :: Continuum Analytics, Inc.
creating default environment...
using -f (force) option
installation finished.

But I have no spyder if I run:
 conda install -c anaconda spyder=3.0.1
 it just breaks again
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[icu                 ]|####                                               |   8%

CondaOSError: OS error: failed to link (src='/home/tom/anaconda3/pkgs/icu-54.1-0/lib/icu/pkgdata.inc', dst='/home/tom/anaconda3/lib/icu/pkgdata.inc', type=3, error=FileExistsError(17, 'File exists'))

**Comment by kalefranz** [comment]
This issue was fixed with transactions in conda 4.3.  Conda no longer "uninstalls" itself during a failed update.
