### ISSUE TITLE
conda 4.2.9 does not read CONDA_ENVS_PATH or CONDA_ENVS_DIR, Linux64

### ISSUE THREAD

**Issue by parkerjon** [conda/conda#3829]
Using the latest Anaconda distribution version, my conda env path variables are ignored.  Steps:

`export PATH=/usr/local/anaconda2/bin:$PATH`

`export CONDA_ENVS_DIR=/tmp/envs`
`export CONDA_ENVS_PATH=/tmp/envs`

`mkdir /tmp/envs`

`conda create -p /tmp/envs/test python`
Create is successful.

`source activate test`
CondaEnvironmentNotFoundError: Could not find environment: test .
 You can list all discoverable environments with `conda info --envs`.

`source activate /tmp/envs/test`

`conda info`
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /usr/local/anaconda2  (read only)
    default environment : /usr/local/anaconda2
       envs directories : /home/jparker/.conda/envs
                          /usr/local/anaconda2/envs
          package cache : /home/jparker/.conda/envs/.pkgs
                          /usr/local/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

**Comment by kalefranz** [comment]
This was fixed in 4.2.11.
