### ISSUE TITLE
'conda update pip' could not connect to Could not connect to https://repo.continuum.io/pkgs/free/osx-64/conda-env-2.6.0-0.tar.bz2

### ISSUE THREAD

**Issue by lewis1286** [conda/conda#3840]
Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/lewisguignard/anaconda2  (writable)
    default environment : /Users/lewisguignard/anaconda2
       envs directories : /Users/lewisguignard/anaconda2/envs
          package cache : /Users/lewisguignard/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/lewisguignard/anaconda2/bin/conda update pip`

    Traceback (most recent call last):
      File "/Users/lewisguignard/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/lewisguignard/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/lewisguignard/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/lewisguignard/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: EOF occurred in violation of protocol (_ssl.c:590): https://repo.continuum.io/pkgs/free/osx-64/conda-env-2.6.0-0.tar.bz2

**Comment by kalefranz** [comment]
Intermittent HTTP error.
