### ISSUE TITLE
CondaRuntimeError

### ISSUE THREAD

**Issue by Smp58** [conda/conda#3842]
Hi,
When i was trying to RMG and the RMG-database binaries via the command prompt as explained in the following website http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUserWindows.html, I encountered an unexpected error while installation. I'm copying the error massage.

Fetching packages ...
eigen-3.2.2-0. 100% |###############################| Time: 0:00:00   1.28 MB/s
ffmpeg-2.7.0-0 100% |###############################| Time: 0:00:55 771.84 kB/s
graphviz-2.38. 100% |###############################| Time: 0:01:21 484.64 kB/s
mopac-2016-1.t 100% |###############################| Time: 0:00:06 894.65 kB/s
symmetry-1.0.1 100% |###############################| Time: 0:00:00 467.76 kB/s
vs2015_runtime 100% |###############################| Time: 0:00:00   4.85 MB/s
libxml2-2.9.3- 100% |###############################| Time: 0:00:04 771.48 kB/s
boost-1.56.0-p 100% |###############################| Time: 0:00:22 389.12 kB/s
coverage-4.2-p 100% |###############################| Time: 0:00:00   2.46 MB/s
cython-0.21-py 100% |###############################| Time: 0:00:00   5.56 MB/s
gprof2dot-2015 100% |###############################| Time: 0:00:00 655.22 kB/s
guppy-0.1.10-p 100% |###############################| Time: 0:00:00   1.41 MB/s
numpy-1.11.2-p 100% |###############################| Time: 0:00:00   4.26 MB/s
An unexpected error has occurred.                   | Time: 0:00:39 770.43 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda2  (writable)
    default environment : C:\Program Files\Anaconda2
       envs directories : C:\Program Files\Anaconda2\envs
          package cache : C:\Program Files\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda2\Scripts\conda-script.py create -c rmg --name rmg_env rmg rmgdatabase`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'C:\\Program Files\\Anaconda2\\pkgs\\openbabel-2.3.2-py27_4.tar.bz2.part' for writing (("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))).

I'm not sure how to fix this error. would appreciate some help.

**Comment by kalefranz** [comment]
Intermittent HTTP error.  `conda update conda` will help.
