### ISSUE TITLE
Piping explicit conda list

### ISSUE THREAD

**Issue by nalexandre** [conda/conda#3851]
I need to pipe some conda commands: 

    $ conda list --export | head -n 3
    # This file may be used to create an environment using:
    # $ conda create --name <env> --file <this file>
    # platform: linux-64

This works fine. However piping the explicit list fails:

    $ conda list --explicit | head -n 3
    # This file may be used to create an environment using:
    # $ conda create --name <env> --file <this file>
    # platform: linux-64
    An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:
    
        https://github.com/conda/conda/issues
    
        
    
    Current conda install:
    
                   platform : linux-64
              conda version : 4.2.12
           conda is private : False
          conda-env version : 4.2.12
        conda-build version : not installed
             python version : 2.7.12.final.0
           requests version : 2.11.1
           root environment : /home/me/miniconda3  (writable)
        default environment : /home/me/miniconda3
           envs directories : /home/me/miniconda3/envs
              package cache : /home/me/miniconda3/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/pro/linux-64
                              https://repo.continuum.io/pkgs/pro/noarch
                config file : None
               offline mode : False
    
    
    
    `$ /home/me/miniconda3/bin/conda list --explicit`
    
    
   
The traceback is (sorry, it wont allow me to put it inside code tags...):

 Traceback (most recent call last):

File "/home/me/miniconda3/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler

return_value = func(*args, **kwargs)

File "/home/me/miniconda3/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
  exit_code = args.func(args, p)

File "/home/me/miniconda3/lib/python2.7/site-packages/conda/cli/main_list.py", line 213, in execute
  print_explicit(prefix, args.md5)

File "/home/me/miniconda3/lib/python2.7/site-packages/conda/cli/main_list.py", line 190, in print_explicit
  print(url + ('#%s' % md5 if add_md5 and md5 else ''))

IOError: [Errno 32] Broken pipe

That's probably a bug right? Without piping it works fine.

**Comment by kalefranz** [comment]
Are you still experiencing this issue with recent versions of conda? Latest is conda 4.3.17.

**Comment by kalefranz** [comment]
```
$ /conda/bin/conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 2.1.10+6.g99aaa148
         python version : 2.7.12.final.0
       requests version : 2.12.0
       root environment : /conda  (writable)
    default environment : /conda
       envs directories : /conda/envs
                          /Users/kfranz/.conda/envs
          package cache : /conda/pkgs
                          /Users/kfranz/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/kfranz/.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.0 CPython/2.7.12 Darwin/16.5.0 OSX/10.12.4
                UID:GID : 502:20

$ /conda/bin/conda list --explicit | head -n 6
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/osx-64/_license-1.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/abstract-rendering-0.5.1-np110py27_0.tar.bz2

```

**Comment by kalefranz** [comment]
Cannot reproduce.

**Comment by nalexandre** [comment]
Hey thanks for the reply, I haven't tried the new version of conda yet. However the strange thing is, with the (now old) version 4.3.17, the command throws the error for the linux version, but works fine on Mac osx. Can yo reproduce it on the new version for both Linux and mac osx?

**Comment by kalefranz** [comment]
Oh I only tried for osx.  But now trying on CentOS 6, with all sorts of different versions of conda--including 4.2.12.  I still don't seem to be able to reproduce it at all.  Strange.

What's the non-piped output?  Does it look normal?
