### ISSUE TITLE
Unexpected error occured Travis CI

### ISSUE THREAD

**Issue by jarifibrahim** [conda/conda#3853]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/travis/miniconda  (writable)
    default environment : /home/travis/miniconda
       envs directories : /home/travis/miniconda/envs
          package cache : /home/travis/miniconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/travis/.condarc
           offline mode : False

`$ /home/travis/miniconda/bin/conda create -q -n test-environment nose python=2.7 --file deps_py2.txt`

    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: a float is required

The command "conda create -q -n test-environment nose python=$TRAVIS_PYTHON_VERSION --file $DEPS" failed and exited with 1 during .

Your build has been stopped.

**Comment by nehaljwani** [comment]
@jarifibrahim Could you please share the contents of the file `deps_py2.txt` ?

**Comment by jarifibrahim** [comment]
@nehaljwani Here you go https://github.com/apache/climate/blob/master/deps_py2.txt

Btw I believe it was some random network issue. Travis was unable to download some files in the beginning and so the build failed. I tried a fresh build and it worked fine.

Closing this as the issue does not exist.
