### ISSUE TITLE
Error from `conda env create --name test`

### ISSUE THREAD

**Issue by christianbrodbeck** [conda/conda#3859]
Getting the following when simply trying to create a new env. I feel like I remember this working before.

```
~$ conda env create --name test 
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 0+unknown
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/christian/anaconda  (writable)
    default environment : /Users/christian/anaconda
       envs directories : /Users/christian/anaconda/envs
          package cache : /Users/christian/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/christian/anaconda/bin/conda-env create --name test`




    Traceback (most recent call last):
      File "/Users/christian/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/christian/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/Users/christian/anaconda/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Invalid name, try the format: user/package
    test does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt
```

**Comment by soapy1** [comment]
You don't need the `env`. You should be able to just run `conda create --name test`

**Comment by christianbrodbeck** [comment]
That works, thanks! Should have looked at ``conda --help``, sorry...

**Comment by sbliven** [comment]
It's confusing that `conda env create` seems to be a valid command (redirecting to the conda-env binary), but requiring different parameters.

**Comment by sebma** [comment]
Hi,

Both `conda-env create -h` and `conda env create -h` say : 

```
  -n ENVIRONMENT, --name ENVIRONMENT
                        Name of environment (in /usr/local/miniconda2/envs:/Us
                        ers/mansfeld/.conda/envs).
...
    conda env create -n name
...
```
If this command `conda-env create -n name` or this one : `conda env create -n name` is not callable this way, can you please update the `conda-env create -h` and `conda env create -h` ouputs ?

**Comment by rgommers** [comment]
Can this please be reopened? The documentation for `conda env create` still says that `conda env create -n someenvname` should work, but it doesn't. If that's no longer a valid command, the docs need changing.

**Comment by Renton2017** [comment]
Hi I am trying the following:
> conda env create -n pandas_dev -f environment-dev.yaml
_It does not work. I am getting the following:_
> `SpecNotFound: Invalid name, try the format: user/package``
_Meanwhile I have tried:_
>  conda create -n pandas_dev -f environment-dev.yaml

And the the fetching has started.
But then am getting an http error like:
```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Read timed out. (read timeout=9.15)",))',),)
```

I do not know how to sort this out.
Andrea

**Comment by john-shine** [comment]
Why not fix? it`s a design bug.

**Comment by charlie0389** [comment]
Yes, the documentation is incorrect, but the change should be to make the command work, to maintain symmetry with the command

``conda env remove -n env_name``

**Comment by abalter** [comment]
What is up with this issue? Certainly this needs to be fixed, right? @kalefranz?

**Comment by erccarls** [comment]
Same.  Documentation mismatch and senseless to not fix....

**Comment by mica5** [comment]
+1 for making some kind of fix (either the documentation, or making the command work as advertised) for this instead of keeping it marked as "Closed".

I wonder how many times I have to rediscover this page from a Google search before either it's fixed or I manage re-wire my neurons, but I fantasize that it could be fixed to save the hundreds or thousands of other people who encounter this issue from the heartache of rediscovering this issue multiple times before they also manage to re-wire their neurons.

**Comment by pythonns** [comment]
please see the

> Hi I am trying the following:
> 
> > conda env create -n pandas_dev -f environment-dev.yaml
> > _It does not work. I am getting the following:_
> > `SpecNotFound: Invalid name, try the format: user/package``
> > _Meanwhile I have tried:_
> > conda create -n pandas_dev -f environment-dev.yaml
> 
> And the the fetching has started.
> But then am getting an http error like:
> 
> ```
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Read timed out. (read timeout=9.15)",))',),)
> ```
> I do not know how to sort this out.
> Andrea

try this: 
https://towardsdatascience.com/getting-started-with-python-environments-using-conda-32e9f2779307

**Comment by maxwellmckinnon** [comment]
+1, please update the confusing outdated --help docs

**Comment by GalvinGao** [comment]
+1. Docs were confused and I even wonder if that's a issue for PyCharm though LOL.

**Comment by barendlinders** [comment]
Just fell for this one again...

**Comment by forskamse** [comment]
Please update the docs or just enable the redirection of conda-env. It's confusing when using conda-env commands.

**Comment by volcan01010** [comment]
+1 for a change in the documentation from me. Running command as specified by `conda env -h` gives `SpecNotFound` error on Conda 4.7.11 on Ubuntu 19.10.

```bash
conda env create -n name
```

**Comment by TejasAvinashShetty** [comment]
Till the docs are fixed 
> conda env create -f environment.yml

**Comment by gitjonez** [comment]
> Just fell for this one again...

Me too! AGAIN! >:|

**Comment by samuell** [comment]
Can confirm that this still gives an error on Conda 4.7.12, on Windows 10, when run in the Anaconda prompt:

```cmd
conda env create -n test

SpecNotFound: Invalid name, try the format: user/package
```

**Comment by shan224** [comment]
Yup bit me as well. Any consensus on this? 
Change the command or change the doc?

**Comment by emeti** [comment]
Design flaw. +1 to reopen and fix. 
Users sensibly expect  `conda env remove` and `conda env create` to be the opposite actions 
... and `conda env create -f` works but without specifying the env yaml file does not ? 
The command does not need to be changed, it only needs to be enhanced so that `conda env create` action be synonymous with what currently `conda create` does. It would improve user experience tremendously and such "shortcuts" happen in other CLIs often (eg. in docker, `images` = `image ls`).

**Comment by jfaccioni** [comment]
2020 update - still same issue:

    $ conda env create -n test
    SpecNotFound: Invalid name, try the format: user/package

Documentation says:
    
    $ conda env create --help
    . . .
    examples:
        conda env create
        conda env create -n name
    . . .

Which is confusing to say the least.

**Comment by tgsmith61591** [comment]
Do the contribs even bother responding to issues anymore? 🤔

**Comment by mzjp2** [comment]
Ran into this again, why isn't it fixed?

**Comment by hessproject** [comment]
+1 to reopen and update documentation, just ran into this issue again 4 years after this ticket was created

**Comment by sebma** [comment]
> +1 to reopen and update documentation, just ran into this issue again 4 years after this ticket was created

Yes, darn right :) 

Please, please, do update the CLI of `conda`.

God bless you for this great tool !

**Comment by polarctis** [comment]
Yes, it's 2020 and still this managed to fool me.

**Comment by AmitSharma1127** [comment]
`conda create environment`
results in
`CondaValueError: The target prefix is the base prefix. Aborting.`

`conda env create -n environment`
results in
`SpecNotFound: Invalid name, try the format: user/package `

`conda env create -f environment`
results in
`EnvironmentFileNotFound: 'C:\Users\Amit\environment' file not found`

`conda env create -f environment.yml`
also results in 
`EnvironmentFileNotFound: 'C:\Users\Amit\environment.yml' file not found`

-----------------------------------------
Date: 2nd July, 2020
Conda Version: 4.8.3 (latest till date)

**Comment by Alexander-Serov** [comment]
Hello!
Why has not this issue been re-opened yet?

**Comment by edgBR** [comment]
Hi,

Same issue here. Extremely messy to create new environments

BR
/E

**Comment by stromal** [comment]
Adding more RAM helps I switched from 0.5 GB to 8GB RAM

**Comment by freshsun** [comment]
And now 2021 comes

**Comment by gitjonez** [comment]
I was looking into this and `conda env create` (or `conda-env create`) reports via --help:

```
usage: conda-env create [-h] [-f FILE] [-n ENVIRONMENT | -p PATH] [-C] [-k] [--offline] [--force]
                        [--json] [-v] [-q]
                        [remote_definition]

Create an environment based on an environment file
...
```

While yes, the behavior is different than `conda create -n new_env [packages]`,
It ***doesn't mean*** the example help of:
`conda env create -n name` is ***incorrect***, since this sub-command states correctly, it's job is:
  - Create an environment ***based on an environment file***

Notes:
  - `conda-env` (not installed in my `homebrew` miniconda install)
    - conda 4.9.2
    - macos 10.15.7
  - To create a new default env or a new env based on specs: (
    e.g. specs: `python=3.8 pandas numpy ipython jupyter`): 
    ```
    prompt> conda create -n new38env -c conda-forge python=3.8 jupyter ipython
    ```

**Comment by memeplex** [comment]
`conda-env` overlaps a lot with `conda` in a very confusing way, it's not included in the reference documentation, trivial issues like this one are ignored for years, etc. I guess the only reason it has not yet been dropped is because it's the only tool that manages environment.yml definitions. Given its state of abandonment I expect it to be deprecated in the future. I learned not to worry and only use it for the corner cases not covered by `conda`.

**Comment by ChariseWalraven** [comment]
This command works for me: `conda create -n tcpserver python=3.8`. Obviously, adjust the python version to whatever you need, and add other packages if necessary. 

I agree that the documentation should be updated, this is confusing for users.

**Comment by jbteves** [comment]
This is needlessly confusing, still hitting this problem in 2022.

**Comment by DanielHongYi** [comment]
Wow, the problem is still here.  May, 2022

**Comment by agricolab** [comment]
Still there in August 2022

**Comment by GF-Huang** [comment]
Issue still.

![image](https://user-images.githubusercontent.com/4510984/220221883-7c405ec7-b143-4d2f-bcb4-3b50937a0258.png)

**Comment by taehyunzzz** [comment]
`conda create $envname` seems to work?

**Comment by Sandy4321** [comment]
> You don't need the `env`. You should be able to just run `conda create --name test`

no , it is not working
it gives no error
but environment is not fully created - can not be lunched

**Comment by kenodegard** [comment]
@Sandy4321 you are experiencing a different problem, for your conda environment to show up as a Jupyter Notebook Kernel you need to install `ipykernel`:

```
conda create --name apr17_sander python=3.9 ipykernel
```

If you continue to encounter problems please open a new issue.

---

In an effort to redirect the conversation to the more appropriate thread and keep it on topic we will be locking this thread. Please raise further questions or concerns in the epic (https://github.com/conda/conda/issues/11633) tracking the effort to resolve the long running confusion between `conda` and `conda env`.
