### ISSUE TITLE
CondaOSError: OS error: failed to link

### ISSUE THREAD

**Issue by orchestor** [conda/conda#3865]
conda update anaconda

I got this, any pointer to solve this?

CondaOSError: OS error: failed to link (src=u'/Users/grant/anaconda2/pkgs/alabaster-0.7.9-py27_0/lib/python2.7/site-packages/alabaster-0.7.9-py2.7.egg-info/PKG-INFO', dst='/Users/grant/anaconda2/lib/python2.7/site-packages/alabaster-0.7.9-py2.7.egg-info/PKG-INFO', type=1, error=OSError(17, 'File exists'))

**Comment by ll-portes** [comment]
Same issue here after:
>> conda update conda
>> conda update --all

My "solution" was:
1. download Miniconda and install it (http://conda.pydata.org/docs/install/quick.html) 
2. execute conda install anaconda

After that, I didn't tried conda update --all yet, but I can work again!

**Comment by kalefranz** [comment]
Root cause should be fixed with recent versions of conda.  Latest is conda 4.3.17.
