### ISSUE TITLE
Terminal throws error message everytime I cd to a git repository

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3866]
@simmimourya1 commented on [Sat Nov 12 2016](https://github.com/conda/conda-build/issues/1529)

I used anaconda2 for a project. I don't remember the first time when it threw this error because at that point it didn't affect the work flow and everything was working fine. I tried to fix it but couldn't find any work around. It still doesn't affect anything but this message  pops up every time I `cd` to a local git repository:
`Error: too few arguments, must supply command line package specs or --file`

![screenshot from 2016-11-13 07 03 32](https://cloud.githubusercontent.com/assets/8150326/20243125/86e7fa7c-a96f-11e6-8928-64faee826845.png)

And it is bugging me. 

No error is thrown if I am not inside a git repository. 

![screenshot from 2016-11-13 07 03 52](https://cloud.githubusercontent.com/assets/8150326/20243127/921228dc-a96f-11e6-9533-86b6d8f0e544.png)

Any clue?
 Thanks a lot for reading this!

---

@msarahan commented on [Sat Nov 12 2016](https://github.com/conda/conda-build/issues/1529#issuecomment-260160988)

Sorry, I don't see how this is related to conda-build.  I'm moving this issue to conda.  I think it probably has something to do with your zsh customization, which is trying to run conda to figure out when environment you're in somehow.  I don't think this is anything standard, so unfortunately, you're probably going to need to figure this out yourself.

**Comment by kalefranz** [comment]
Are you using fish shell @simmimourya1?

**Comment by simmimourya1** [comment]
@kalefranz, I am using zsh.

**Comment by kalefranz** [comment]
At the top of your `~/.zshrc` file add `set -x`.  Then `source ~/.zshrc`.  You should be able to identify the command that's triggering the error output.  Then we can take it from there.

**Comment by njalerikson** [comment]
This would suggest that you are not using a pure `cd` command. What do you get if you run:

```
which cd
```

and

```
alias cd
```

**Comment by kalefranz** [comment]
type -a cd

**Comment by simmimourya1** [comment]
Yep. It helped. 
I had an alias set up named `test` which ran `conda install --name _test`. It was overriding shell built-in `test`.

**Comment by simmimourya1** [comment]
Issue can be closed now. Thanks everyone!
