### ISSUE TITLE
conda update conda failed!

### ISSUE THREAD

**Issue by xi2008wang** [conda/conda#3869]
➜  ~ conda update conda
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/chriswan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.2.12               |           py27_0         376 KB

The following packages will be UPDATED:

    conda: 4.2.11-py27_0 --> 4.2.12-py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-4.2.12-p 100% |#####################################################################################################################################| Time: 0:00:13  28.52 kB/s
Extracting packages ...
[      COMPLETE      ]|########################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|########################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /Users/chriswan/anaconda  (writable)
    default environment : /Users/chriswan/anaconda
       envs directories : /Users/chriswan/anaconda/envs
          package cache : /Users/chriswan/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/chriswan/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/chriswan/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/chriswan/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/chriswan/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/chriswan/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x10a1ec610>

**Comment by xi2008wang** [comment]
now:
➜  ~ conda list conda
# packages in environment at /Users/chriswan/anaconda:
#
anaconda                  2.3.0                np19py27_0    None:///<unknown>
conda                     4.2.12                    <pip>
conda-build               1.14.1                   py27_0    None:///<unknown>
conda-env                 2.6.0                         0
➜  ~ conda update conda


PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in /Users/chriswan/anaconda


➜  ~ conda list conda
# packages in environment at /Users/chriswan/anaconda:
#
anaconda                  2.3.0                np19py27_0    None:///<unknown>
conda                     4.2.12                    <pip>
conda-build               1.14.1                   py27_0    None:///<unknown>
conda-env                 2.6.0                         0

➜  conda ls
__init__.py      api.pyc          config.py        core             exports.pyc      install.py       logic.py         plan.pyc         toposort.pyc
__init__.pyc     base             config.pyc       egg_info.py      fetch.py         install.pyc      logic.pyc        resolve.py       utils.py
__main__.py      cli              connection.py    egg_info.pyc     fetch.pyc        instructions.py  misc.py          resolve.pyc      utils.pyc
__main__.pyc     common           connection.pyc   exceptions.py    gateways         instructions.pyc misc.pyc         signature.py     version.py
_vendor          compat.py        console.py       exceptions.pyc   history.py       lock.py          models           signature.pyc    version.pyc
api.py           compat.pyc       console.pyc      exports.py       history.pyc      lock.pyc         plan.py          toposort.py
➜  conda pwd
/Users/chriswan/anaconda/lib/python2.7/site-packages/conda

**Comment by kalefranz** [comment]
I'm sorry you ran into this :(  Unfortunately I don't know exactly what happened or what went wrong.  I can't tell from the code.

The easiest way to immediately get out of this mess is to download a miniconda installer from http://conda.pydata.org/miniconda.html, and then run

    bash PATH_TO_MINICONDA_DOWNLOAD -bfp /Users/chriswan/anaconda

**Comment by stevenmanton** [comment]
I'm having a similar issue -- conda stuck in an intermediate state and `conda update conda` fails:

```
➜ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.11.1
       root environment : /work/analytics2/analytics/python  (writable)
    default environment : /work/analytics2/analytics/python
       envs directories : /work/analytics2/analytics/python/envs
          package cache : /work/analytics2/analytics/python/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False


➜ conda update conda
PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in /work/analytics2/analytics/python
```

When I try the solution you propose above, it fails when it tries to install the wheel package:

```
➜  tools bash Miniconda2-latest-Linux-x86_64.sh -bfp /work/analytics2/analytics/python/
PREFIX=/work/analytics2/analytics/python
installing: python-2.7.12-1 ...
installing: conda-env-2.6.0-0 ...
installing: enum34-1.1.6-py27_0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py27_0 ...
installing: pycrypto-2.6.1-py27_4 ...
installing: pip-8.1.2-py27_0 ...
installing: wheel-0.29.0-py27_0 ...
tar: bin/wheel: Cannot open: File exists
tar: info/LICENSE.txt: Cannot open: File exists
tar: info/files: Cannot open: File exists
tar: info/has_prefix: Cannot open: File exists
tar: info/index.json: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/PKG-INFO: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/SOURCES.txt: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/dependency_links.txt: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/entry_points.txt: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/not-zip-safe: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/requires.txt: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel-0.29.0-py2.7.egg-info/top_level.txt: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel/__init__.py: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel/__init__.pyc: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel/__main__.py: Cannot open: File exists
tar: lib/python2.7/site-packages/wheel/__main__.pyc: Cannot open: File exists
...
```

**Comment by kalefranz** [comment]
@stevenmanton you ran into a problem that's completely solved with conda 4.3.  Again, you'll probably have to use a new miniconda installer to recover.

**Comment by mikehagerty** [comment]
This issue is *not* resolved.  I just got the same error both on macos and Linux.
e.g., I just installed conda from Anaconda3-5.1.0-Linux-x86_64.sh
and when I try to do: conda update conda I get:
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /some/path/anaconda3/envs/obspy
  package name: conda

(obspy)>conda -V
conda 4.4.10

Clearly, conda update conda looks in the environment package list (.../anaconda3/envs/...) and it is not there.  

I tried doing:
>conda install conda

This simply adds the latest conda as a pkg in the environment, it does not update the "root" conda located in ../env/bin/conda.  Somehow it needs to bootstrap this and it is not doing it.

**Comment by kalefranz** [comment]
@mikehagerty conda now advises using

    conda update -n base conda

**Comment by sulsj** [comment]
Hi,

Have you guys seen the below issue?

$ conda update -n base conda
Solving environment: done

## Package Plan ##

  environment location: /global/projectb/sandbox/rqc/qc_user/miniconda/miniconda2

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.1                |           py27_0         630 KB  conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.1.18-0      conda-forge --> 2018.4.16-0      conda-forge
    certifi:         2018.1.18-py27_0 conda-forge --> 2018.4.16-py27_0 conda-forge
    conda:           4.4.10-py27_0    anaconda    --> 4.5.1-py27_0     conda-forge
    openssl:         1.0.2n-0         conda-forge --> 1.0.2o-0         conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda 4.5.1: ########################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'None'.
IOError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

IOError(13, 'Permission denied')


Thanks,
Seung
