### ISSUE TITLE
Miniconda macOS bash installer writes in .bash_profile instead of .profile

### ISSUE THREAD

**Issue by DerekDomino** [conda/conda#3871]
I've just installed miniconda on macOS Sierra and the installer **created** a `~/.bash_profile` file.

It is annoying as bash won't source anymore `~/.profile` when it finds `~/.bash_profile` !

For example, `brew` and `nvm` add their contents in `~/.profile`.

Instead of writing contents to `~/.bash_profile`, the installer should append its modifications to `~/.profile`.
Another option would be that miniconda installer adds a source command in `~/.bash_profile` when it creates it:
````bash
    [[ -r ~/.profile ]] && . ~/.profile
    [[ -r ~/.bashrc ]] && . ~/.bashrc
````

**Comment by kalefranz** [comment]
I'm going to move this issue to ContinuumIO/anaconda-issues so @ilanschnell sees it.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1233
