### ISSUE TITLE
list of used dependency versions for each build..

### ISSUE THREAD

**Issue by martin-mann** [conda/conda#3872]
Hi,

we just discussed for bioconda the problem of updated runtime dependencies that break existing downstream packages (eg for perl etc..).

eg. think about the following situation: given a (perl) package A and a dependent package B, which only provides a minimal required version for A. Now A is updated and rebuild to a new version which drops the interface used by B. So the build of A is successful, but as soon as B is installed, the recent A is installed too and B fails on runtime.

Is is planned/possible/useful to add to each package also the *full list* of packages including version number used for the build?

This would very much ease 
- debugging for the described scenario and 
- enable the identification of outdated packages to be rebuild.

Thanks for feedback on that,
Martin

**Comment by kalefranz** [comment]
This might already be done, or it might be planned.  I'm not sure.  I'm going to move the issue to conda-build for you so it gets more attention by the people who would know best :)

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1534
