### ISSUE TITLE
conda libraries clobber logging configuration

### ISSUE THREAD

**Issue by alexhsamuel** [conda/conda#3873]
```py
>>> import logging
>>> logging.basicConfig(level=logging.INFO)
>>> print(logging.getLogger().level)
20
>>> import conda.base.context
>>> print(logging.getLogger().level)
40
```

I tracked this down to `conda.common.io.attach_stderr_handler`.  

Could this kind of forcible logging configuration be moved to `conda.cli` or somewhere else that is not imported when conda is used as a library?

BTW all I was trying to do was get the path to conda's build directory programatically.

**Comment by kalefranz** [comment]
We're evolving logging and getting it all straightened out right now. At the moment it's in a few places, depending on the logger. 

Safest place for now to get the conda build direct I think is `conda_build.config.croot` or something like that. Look in the conda-build project source to track it down specifically.

**Comment by alexhsamuel** [comment]
@kalefranz, alas, `import conda_build.config` also reconfigures logging.
