### ISSUE TITLE
why are some packages also listed as pip installs

### ISSUE THREAD

**Issue by jreback** [conda/conda#3874]
a slightly older conda
```
λ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 2.0.7
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\bmc3
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
```

fresh env
```
λ conda create -n foo3 python=3.5
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda\envs\foo3:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_0
    python:         3.5.2-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate foo3
#
# To deactivate this environment, use:
# > deactivate
#

C:\dev\jellyfish (master)
λ activate foo3
```

```
(foo3) C:\dev\jellyfish (master)
λ conda install jellyfish -c conda-forge --override-channels
Fetching package metadata .....
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda\envs\foo3:

The following NEW packages will be INSTALLED:

    jellyfish: 0.5.1-py35_0 conda-forge

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%

(foo3) C:\dev\jellyfish (master)
λ conda env export
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
name: foo3
channels:
- file://\\bcna.corp\dfs\shared\production\conda\channels
- defaults
- conda-forge
dependencies:
- conda-forge::jellyfish=0.5.1=py35_0
- pip=9.0.1=py35_0
- python=3.5.2=0
- setuptools=27.2.0=py35_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - jellyfish==0.5.1
prefix: C:\Anaconda\envs\foo3


(foo3) C:\dev\jellyfish (master)
```

so what is curious is that *some* packages have a pip listed as well as a conda line. why is that?

**Comment by kalefranz** [comment]
Likely because they were first installed with conda, but then installed again with pip.  Conda inspects the installed packages in an environment via the contents of the environment's `conda-meta` directory.  Other package managers (like pip, gem, npm, etc) can clobber an environment in several ways.

We look for pip installed packages by inspecting the environment's python `site-packages` directory and looking for `.egg-info` and `.dist-info` directories to pull metadata out of (maybe a few more sources also).  Those are the python packages that have been installed NOT as conda packages.  This should include btw installing via `python setup.py install`.

 Someday in the future we'll probably add a `conda doctor` or `conda integrity-check` or something for an environment.  That would be able to report on files that have been added to the environment or altered without conda knowing about it.  We're actually right now adding the information to conda-build packages to be able to do that (https://github.com/conda/conda-build/pull/1501).  But the actual implementation of that feature within conda is lower priority than many other features and fixes right now.

**Comment by kalefranz** [comment]
Did that answer your question @jreback?

**Comment by jreback** [comment]
@kalefranz I think so. 

we were bit because this particular library has c-extensions, which work when installed from conda, but it doesn't have pip wheels.

Further the pip version is > the conda version.

Its kind of a perverse situation, but ideally conda would not try to double install things (by generating the .yml this way).

**Comment by kalefranz** [comment]
Ahh that's a conda-env issue then I think, which there hasn't been bandwidth to give much attention in 2016.  I'm hoping that 2017 will see a lot of evolution and improvement for conda-env.

**Comment by hrichardlee** [comment]
@kalefranz Are you saying that if a package puts a `.egg-info` folder into `Lib/site-packages` pip will assume that it is a pip package?

A few observations:
- It looks like the jellyfish conda package includes a `.egg-info` folder (https://anaconda.org/conda-forge/jellyfish/0.5.6/download/win-64/jellyfish-0.5.6-py34_0.tar.bz2 contains a folder called `Lib/site-packages/jellyfish-0.5.6-py3.4.egg-info`).
- The pandas conda package also contains a `.egg-info` folder, but it doesn't behave like this (https://anaconda.org/conda-forge/pandas/0.19.1/download/win-64/pandas-0.19.1-np111py35_0.tar.bz2 contains a folder called `Lib/site-packages/pandas-0.19.1-py3.5.egg-info`):

```
> conda create -n test python=3
> activate test
> conda install pandas
> conda env export
name: test
channels:
- file://\\bcna.corp\dfs\shared\production\conda\channels
- defaults
- conda-forge
dependencies:
- mkl=11.3.3=1
- numpy=1.11.2=py35_0
- pandas=0.19.1=np111py35_0
- pip=9.0.1=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.7=py35_0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
prefix: C:\bin\Miniconda\envs\test
```

Is there an explanation for why jellyfish and pandas behave differently? I find it hard to believe that just running `conda install jellyfish` really installs the conda package and the pip package. There's nothing in the console output that indicates that a pip package is being installed and there's nothing in the jellyfish conda package that suggests that would happen. The presence of the `.egg-info` folder is explained by the fact that it exists in the conda package.

It seems that most conda packages are well-behaved, but there are many conda packages that behave like jellyfish (they show up as both conda and pip packages in `conda env export`). Here are just a few examples we've run across:
https://anaconda.org/conda-forge/cartopy/0.14.3/download/win-64/cartopy-0.14.3-np111py35_3.tar.bz2
https://anaconda.org/conda-forge/distributed/1.14.3/download/win-64/distributed-1.14.3-py35_0.tar.bz2
https://anaconda.org/conda-forge/feather-format/0.3.1/download/win-64/feather-format-0.3.1-py35_1.tar.bz2
https://anaconda.org/conda-forge/multiprocess/0.70.4/download/win-64/multiprocess-0.70.4-py35_0.tar.bz2
https://anaconda.org/conda-forge/s3fs/0.0.7/download/win-64/s3fs-0.0.7-py35_0.tar.bz2

**Comment by kalefranz** [comment]
> pip will assume that it is a pip package?

I have no idea what assumptions pip makes.  This is the conda issue tracker :)

The code I discussed above that implements this is pretty simple.  https://github.com/conda/conda/blob/ab8ec3c83bd6c1eed96e23d03daa05b829f82321/conda/egg_info.py

**Comment by jreback** [comment]
@kalefranz I think the issue is that ``conda env export`` exports BOTH a conda and a pip package reference (but not for all packages).

**Comment by hrichardlee** [comment]
Sorry, I mis-typed. I will edit my comment so that it makes sense (replacing "pip will assume" to "`conda env export` will assume")

**Comment by hrichardlee** [comment]
I think I found the issue, and this has been fixed in https://github.com/conda/conda/commit/0b9814f9fdfcf3a26da26c0b770e4da98ecb3c57 which is in conda 4.2.12.

Apologies for the superfluous issue!
