### ISSUE TITLE
package not relocatable after conda --clone?

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3878]
I have built my own version of openmpi to be relocatable. When I create a new conda environment with my openmpi package, it works. However if I clone the environment, something like mpirun -h doesn't work, I get
```
(ana-1.0.5-dev) psanaphi108: ~ $ mpirun -h
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/openmpi-1.10.3-prod_1474170458941/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
```

**Comment by kalefranz** [comment]
You might have to manually flag `share/openmpi/help-opal-runtime.txt` or other files referencing it in your conda meta.yaml recipe..  The documentation around http://conda.pydata.org/docs/building/meta-yaml.html#relocation might help.  Using either `binary_has_prefix_files` and/or `has_prefix_files` (yes those parameter names are horrible, I know).

**Comment by kalefranz** [comment]
Also, you should be able to add a section to your recipe

```
test:
  commands:
    - mpirun -h
```

So you know immediately if something is broken.

**Comment by kalefranz** [comment]
Oh I see you're problem is just with cloning?  Can you attach the conda package you built to this issue so I can look at it?  Should be able to just drag and drop.

**Comment by davidslac** [comment]
Hi Kale, I have the recipe in github, here is the meta.yaml

https://github.com/slaclab/anarel-manage/blob/master/recipes/system/openmpi-1.10.3-prod/meta.yaml

I do have a bunch of tests, but I wasn't testing mpirun -h, and right, 
mpirun -h works in the environment I created from the ground up, just 
not in the cloned environment -

If I need to explicitly list other files for conda-bld to re-write for 
relocation, it will be tricky, all the help-*.txt files in share/openmpi 
don't have a hard coded path in them, but I do see a lot of %s, which 
suggests the path is in some code somewhere.

best,

David

**Comment by davidslac** [comment]
I tried to clone again last night and mpirun worked. Not sure what changed, I'll close this for now.
