### ISSUE TITLE
Possible to suppress "to activate this environment..." message on env update?

### ISSUE THREAD

**Issue by paul99se** [conda/conda#3879]
I don't see a switch that would allow me to turn this message off:

`#
# To activate this environment, use:
# > activate soq1
#
# To deactivate this environment, use:
# > deactivate soq1
#
# * for power-users using bash, you must source
#`

**Comment by kalefranz** [comment]
Seems reasonable.

**Comment by paul99se** [comment]
Suppressing the message when --quiet would work well for my case.

**Comment by kalefranz** [comment]
Oh that's trivial to implement.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/3886

With the new config engine in 4.2, you can activate this by adding `quiet: true` to any of the many conda config file locations, setting a `CONDA_QUIET=true` environment variable, or using the `--quiet` flag on commands that accept it.

On unix (I don't know if it's true for Windows), if a command doesn't accept the `--quiet` flag, you can pass environment variables just by prepending them.  Something like

    CONDA_QUIET=yes source activate my_env

**Comment by wulmer** [comment]
On Windows, the command should be (untested)

    set CONDA_QUIET=yes& activate my_env
