### ISSUE TITLE
graphviz package confusing

### ISSUE THREAD

**Issue by amueller** [conda/conda#3889]
I find it a bit confusing that the graphviz package in conda is not the graphviz package in pip. To use the python package graphviz in a conda environment, I have to ``conda install graphviz``, which installs the C library, and ``pip install graphviz`` which installs the python library. I don't think the python ``graphviz`` library is part of conda.
Is there a way to make this less confusing?
Thanks!

**Comment by kalefranz** [comment]
Yes, we have a proposal to fix this.  https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1

It need not be named "Conda Hackery" at this point.  We think it will actually work well.

CC @mcg1969

**Comment by amueller** [comment]
wow that's a pretty cool idea. It sounds like relatively long-term undertaking though...

**Comment by kalefranz** [comment]
Should happen first quarter or half of 2017 probably.

**Comment by amueller** [comment]
Feel free to close this, depending on how the renaming will work.

**Comment by asmeurer** [comment]
I haven't read the proposal in depth, but I had always imagined this working by conda giving a helpful "which one do you want?" message (with configurable and/or smart defaults) for `conda install package` whenever both `package` and `language-package` exist (and also possibly automatically using `language-package` for `conda install package` when there is no ambiguity). This sort of "in the face of ambiguity, refuse the temptation to guess" can probably be applied to the namespace idea as well (it's mostly a UI thing).

**Comment by jakirkham** [comment]
At least for `graphviz` specifically @amueller, one can do `conda install -c conda-forge python-graphviz` and get both in one step. Though I do agree these conflicting names are a mess. @mcg1969's proposal is the most reasonable thing to solve this FWICT.

**Comment by kalefranz** [comment]
We're tracking ecosystem namespaces as a feature addition through https://github.com/conda/conda/issues/6939
