### ISSUE TITLE
Creating activate.d and deactivate.d directories messes up $PATH in OSX

### ISSUE THREAD

**Issue by jvarada** [conda/conda#3890]
I created a new environment,
`conda create --name testenv python=3 -y`

and I wanted to set environment variables in the ./etc/conda/activate.d (and unset in the deactivate.d) directories as specified in the tutorial. However when activating the environment, I got some errors that the env_vars.sh file could not be found (and the file path looked all messed up).

Doing `echo $PATH` reveals my path looks like this now:

> /Us rs/vdj/a aco da/  vs/t st  v/bi :/Us rs/vdj/a aco da/bi :/Applicatio s/fr  surf r/bi :/Applicatio s/fr  surf r/fsfast/bi :/Applicatio s/fr  surf r/tktools:/usr/local/fsl/bi :/Applicatio s/fr  surf r/m i/bi :/Us rs/vdj/a aco da/bi :/usr/local/fsl/bi :/usr/local/opt/php55/bi :/Us rs/vdj/phab/arca ist/bi :/usr/local/bi :/usr/local/sbi :/usr/local/bi :/usr/bi :/bi :/usr/sbi :/sbi :/opt/X11/bi :/Library/T X/t xbi :/Us rs/vdj/d v/dcm2 iix/bi :/Us rs/vdj/abi :/Us rs/vdj/a tsbi /bi :/Us rs/vdj/Spark/bi

As far as I can tell, it's removing the `n`'s and the `e`'s from the path names. This behavior goes away if I delete the ./etc/conda/activate (or deactivate) .d directories.

I am running on OS X 10.11.6, 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15),
conda 4.2.9,
Python 3.5.2 :: Continuum Analytics, Inc.

**Comment by njalerikson** [comment]
Just to confirm your `activate.d`/`deactivate.d` directories are nested in the environment directory:

```
~/anaconda/envs/[ENVIRONMENT]/etc/conda/{activate.d,deactivate.d}
```

Otherwise you should dump the contents of your `env_vars.sh` file here.

**Comment by jvarada** [comment]
Yes, they are. Eg,

`/Users/vdj/anaconda/envs/testenv/etc/conda/activate.d`

The contents of the `env_vars.sh` file are:

activate.d/env_vars.sh:
```
#!/bin/sh

export DJANGO_KEY='abc123'
``` 

deactivate.d/env_vars.sh:
```
#!/bin/sh

unset DJANGO_KEY
```

Incidentally, the behavior happens even if there are no files under the activate.d/deactivate.d directories. Removing the `~/anaconda/envs/[ENV]/etc` directory and subdirectories returns the behavior to normal (after restarting the shell).
