### ISSUE TITLE
conda install matplotlib error;can anyone tell me why?

### ISSUE THREAD

**Issue by sangyongjia** [conda/conda#3894]
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /data1/yongjia/myTask/personality/devEnvironment/miniconda2  (writable)
    default environment : /data1/yongjia/myTask/personality/devEnvironment/miniconda2
       envs directories : /data1/yongjia/myTask/personality/devEnvironment/miniconda2/envs
          package cache : /data1/yongjia/myTask/personality/devEnvironment/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /data1/yongjia/myTask/personality/devEnvironment/miniconda2/bin/conda install matplotlib`

    Traceback (most recent call last):
      File "/data1/yongjia/myTask/personality/devEnvironment/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/data1/yongjia/myTask/personality/devEnvironment/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/data1/yongjia/myTask/personality/devEnvironment/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/data1/yongjia/myTask/personality/devEnvironment/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/data1/yongjia/myTask/personality/devEnvironment/miniconda2/pkgs/qt-5.6.0-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by sangyongjia** [comment]
waiting online tonight.

**Comment by kalefranz** [comment]
It's just an HTTP timeout error.  We've extended the timeouts in `4.2.13`.  Run `conda update conda` and then try again.
