### ISSUE TITLE
C++ linking issue on ubuntu when building scikit-learn

### ISSUE THREAD

**Issue by amueller** [conda/conda#3897]
I've trouble building scikit-learn inside a conda environment on a fresh machine running Ubuntu 16.10.
I get the following linking issue:

scikit-learn/sklearn/svm/libsvm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __cxa_throw_bad_array_new_length

I suspect that this is caused by some version mismatch between shared libraries. I'm using gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005.

Using the system python I can run scikit-learn without issues.

Here are the linked libraries:
```
> ldd /home/andy/checkout/scikit-learn/sklearn/svm/libsvm.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc1c5ce000)
	libpython3.5m.so.1.0 => /home/andy/anaconda3/lib/libpython3.5m.so.1.0 (0x00007fb4cf2c4000)
	libstdc++.so.6 => /home/andy/anaconda3/lib/libstdc++.so.6 (0x00007fb4cefae000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb4cec88000)
	libgcc_s.so.1 => /home/andy/anaconda3/lib/libgcc_s.so.1 (0x00007fb4cea72000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb4ce854000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb4ce48b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb4ce287000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb4ce084000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb4cde7c000)
	/lib64/ld-linux-x86-64.so.2 (0x00005638e7a82000)
```

**Comment by amueller** [comment]
Any help would be much appreciated.

**Comment by amueller** [comment]
and then it magically worked. Can't reproduce any more.

**Comment by amueller** [comment]
Actually, I can still reproduce. I was in a different conda env than I thought. Here is the anaconda package list on which it doesn't compile and the minimal conda env on which it does....
[root_new.txt](https://github.com/scikit-learn/scikit-learn/files/595969/root_new.txt)
[python35.txt](https://github.com/scikit-learn/scikit-learn/files/595970/python35.txt)

**Comment by chrisormandy** [comment]
can you build with 2.7 - I haven't tried building on 3.5, but can do it on 2.7. 

I will setup a new v env with 3.5 and give it a go.

**Comment by amueller** [comment]
I can build on a venv with 35 with the list in python35.txt above. I can not build on the default anaconda. Basically some of the additional packages in anaconda make it break!

**Comment by amueller** [comment]
(I'm suspecting glib, but I think that just turned out to be wrong, next suspect is mkl-services)

**Comment by amueller** [comment]
In the working environment I get
```
> ldd /home/andy/checkout/scikit-learn/sklearn/svm/libsvm.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc49944000)
	libpython3.5m.so.1.0 => /home/andy/anaconda3/envs/python35/lib/libpython3.5m.so.1.0 (0x00007ff01f04c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff01eca7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff01e99e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff01e787000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff01e569000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff01e1a0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff01df9c000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff01dd99000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff01db91000)
	/lib64/ld-linux-x86-64.so.2 (0x00005562eb092000)
(python35) 
```

**Comment by chrisormandy** [comment]
[packagelist2.7.txt](https://github.com/conda/conda/files/595995/packagelist2.7.txt)

I can build on 2.7 with this setup

**Comment by amueller** [comment]
They use different libstdc++ and libgcc. The working env uses my system one, while the non-working env uses the anaconda one.

**Comment by chrisormandy** [comment]
~/python/scikit-learn/build/lib.linux-x86_64-3.5/sklearn/svm$ ldd libsvm.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffdab59a000)
	libpython3.5m.so.1.0 => /home/chris/anaconda2/envs/pthree/lib/libpython3.5m.so.1.0 (0x00007fd865b41000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd8657a5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd86549b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd865285000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd865068000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd864c9e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd864a9a000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd864897000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd86468e000)
	/lib64/ld-linux-x86-64.so.2 (0x00005585cbb21000)

**Comment by chrisormandy** [comment]
builds no issues with this package setup:

# packages in environment at /home/chris/anaconda2/envs/pthree:
#
libgfortran               3.0.0                         1  
mkl                       11.3.3                        0  
numpy                     1.11.2                   py35_0  
openssl                   1.0.2j                        0  
pip                       9.0.1                    py35_0  
python                    3.5.2                         0  
readline                  6.2                           2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
zlib                      1.2.8                         3

**Comment by amueller** [comment]
I think it's more an issue of "root env" vs "separate env". In my root env the link is against the anaconda libgcc and libstdc++, which doesn't seem to work. In a separately created conda env it works.

**Comment by kalefranz** [comment]
@ilanschnell @msarahan @mingwandroid Any ideas on what's going on here?

**Comment by chrisormandy** [comment]
just for completness, I can build on root env, with latest g++ and gcc installed. Not sure what would cause the mismatch in linking between mine and your tbh.

**Comment by amueller** [comment]
"interesting"
Any ideas how to debug?

**Comment by msarahan** [comment]
Just educated guessing here. 

The libgcc package is present when things don't work, and absent when they do. The libgcc package is a very old version (4.8.5). You probably need a libgcc that is closer to the compiler you're using. Ideally the same or newer version. 

Long term, we are updating our toolchain. Short term, there is a newer libgcc that might work - should be version 5.2.

By building with such a new gcc, though, you are imposing very rigid constraints on where your package will run. Even though your package works on your system, if you send it to someone with an older system libstdc++, it will not work. This is the idea behind the manylinux docker image and the conda_builder_linux docker image that never really caught on. I strongly recommend that you take steps to ensure wider compatibility.

**Comment by amueller** [comment]
Well this is just for my personal use. We have anylinux wheels...

**Comment by msarahan** [comment]
Cool, that's easier. 

Just make sure libgcc is not installed. If anything really needs it, you'll need to rebuild the thing that needs it,  or as a terrible hack, perhaps just delete the files from libgcc without actually removing the package.

**Comment by amueller** [comment]
jupyter depends on libgcc... hm I could also downgrade my gcc ... but I think this is solved (pending my build running through). Thanks for the help!

**Comment by msarahan** [comment]
By rebuild, I mean hack the recipe to remove the libgcc dependency. You don't technically need to rebuild. You can get away with hacking info/index.json, but that's kind of fragile.

**Comment by amueller** [comment]
Runs! Wouldn't it be somewhat more consistent if you ship your own gcc if you ship libgcc?

**Comment by msarahan** [comment]
Yes, and that's absolutely where we're headed. Only so much time in a day,
though.

The bottleneck has been building packages, but we will have an automated
system up soon. Progress at https://github.com/conda/conda-concourse-ci
