### ISSUE TITLE
Confusing message about dependency conflicts

### ISSUE THREAD

**Issue by jbednar** [conda/conda#3901]
If I explicitly downgrade a package, the messages are very confusing.  It *says* that the package will be "downgraded due to dependency conflicts", which may be true in some narrow sense, but to me it's being downgraded because I explicitly told it to!  Any chance the message could avoid claiming a reason it's being downgraded, if it's too complicated to convey the actual reason?

```
$ conda install dask=0.11.0
Fetching package metadata .......
Solving package specifications: ..........
Package plan for installation in environment .../anaconda:
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dask-0.11.0                |           py27_0         591 KB

The following packages will be DOWNGRADED due to dependency conflicts:

    dask: 0.12.0-py27_0 --> 0.11.0-py27_0

Proceed ([y]/n)? y
```

**Comment by kalefranz** [comment]
Good point.  CC @mcg1969 

Something to try to fix when we're working within that code next time.

**Comment by jbednar** [comment]
I guess it could say "to meet the constraints", which is presumably always true...

**Comment by mcg1969** [comment]
It seems the simple thing to do here is note that an explicit constraint requirement was given for that package; and in that case, drop the downgrade reason altogether.

**Comment by mcg1969** [comment]
For the record @kalefranz this is not solver related. Not to disclaim responsibility, just that it does not require getting into the weeds of the solver to fix it. The logic here is contained entirely within the display_actions method.

**Comment by kalefranz** [comment]
Sometime when a few higher-level priorities are smacked down I'm going to go through display_actions myself and see what I can contribute to improvement there.

Part of it will be turning the output first into a `Message`-type object so we can abstract out the actual information from the various display methods (cli, json, etc).

**Comment by jbednar** [comment]
As far as I can tell, this problem no longer applies to current conda. Running a similar test just now with conda 4.10.1 yielded a message "The following packages will be DOWNGRADED:", not mentioning dependency conflicts, which seems fine now.
