### ISSUE TITLE
Using conda config set writes strings on the config file

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#3903]
`conda config --set ssl-verify True`

Results in a yaml file that looks like

```yaml
ssl_verify: 'False'
```

instead of

```yaml
ssl_verify: False
```

(**Notice the extra quotes!**)

This does not seem to affect functionality but it looks funny.

This is related to Navigator which sets some options via the GUI (and calls the conda config command)

Maybe this [line](https://github.com/conda/conda/blob/master/conda/cli/main_config.py#L403) is the culprit?

**Comment by kalefranz** [comment]
@soapy1 This one if fair game for you.

**Comment by kalefranz** [comment]
I think this is completely fixed in 4.3. @goanpeca please re-open if not.
