### ISSUE TITLE
Could not connect to https://repo.continuum.io/pkgs/free/noarch/ while fetching package

### ISSUE THREAD

**Issue by cecileclem** [conda/conda#3914]
Hello,
I have recently installed anaconda without difficulties. I need several packages/libraries which are not installed by default: xarray, netCDF4 and mpl_toolkits.basemap. Unfortunatly I can't install them with conda, I got the following error:

*********************************************************************************************************
$ conda install xarray
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /cea/home/b4/clementc/anaconda2  (writable)
    default environment : /cea/home/b4/clementc/anaconda2
       envs directories : /cea/home/b4/clementc/anaconda2/envs
          package cache : /cea/home/b4/clementc/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /cea/home/b4/clementc/anaconda2/bin/conda install xarray`

    Traceback (most recent call last):
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/cea/home/b4/clementc/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b80c37eccd0>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')): https://repo.continuum.io/pkgs/free/linux-64/

******************************************************************************************************

Then I tried to install the package xarray through jupyter, in the tab "Conda". In the list "Available packages" on the left, there is no suggestion at all (I waited for several minutes).

My version of python is  2.7.12.final.0, but it is written in the issue message that the requests version is 2.11.1. Do you think this is why it is not working?

Thank you
Cecile

**Comment by cecileclem** [comment]
I have exactly the same issue when I try:
conda update conda 
Maybe someting went wrong during the installation...

**Comment by cecileclem** [comment]
It is working, it was because of the proxy :
http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers
Sorry for annoying you!

**Comment by jmarriaga** [comment]
Hi cecileclem, I'm having the same issue but do not understand how to fix it with those instructions. Is there a way you could help me out? Thanks

**Comment by cecileclem** [comment]
Hi jmarriaga. Do you have a proxy with your connection ?

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
