### ISSUE TITLE
installing conda-forge tensorflow

### ISSUE THREAD

**Issue by Estifo** [conda/conda#3920]
Could not connect to https://conda.anaconda.org/conda-forge/linux-64/
Could not connect to https://conda.anaconda.org/conda-forge/noarch/
Could not connect to https://conda.anaconda.org/conda-forge/linux-64/
An unexpected error has occurred.
 how can i fix this ???

**Comment by soapy1** [comment]
Does this happen consistently e.g. did you try to install again a little bit later?
Also, could you provided the output to `conda info`

**Comment by kalefranz** [comment]
This issue was moved to Anaconda-Platform/support#87
