### ISSUE TITLE
Error in conda insatall scikit-learn

### ISSUE THREAD

**Issue by praveenvaddimgunta** [conda/conda#3921]
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/linux-64
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/praveen/miniconda2  (writable)
    default environment : /home/praveen/miniconda2
       envs directories : /home/praveen/miniconda2/envs
          package cache : /home/praveen/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/praveen/miniconda2/bin/conda install scikit-learn`

    Traceback (most recent call last):
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/praveen/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b6aaf8d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)): https://repo.continuum.io/pkgs/free/linux-64

**Comment by nehaljwani** [comment]
`'Temporary failure in name resolution'`
Doesn't seem like a bug to me.

**Comment by kalefranz** [comment]
If you don't mind, can you give me what ipinfo.io/json says for you?  Also can you `conda update conda` to `4.2.13`?  If that succeeds, can you give me the output of `/home/praveen/miniconda2/bin/conda install scikit-learn -vv`?

**Comment by rajendrabharti** [comment]
try chaning nameserver  in /etc/resolv.conf file to nameserver 8.8.8.8 and then try again it might help cause it helped me

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
