### ISSUE TITLE
Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/

### ISSUE THREAD

**Issue by Fenix0817** [conda/conda#3925]
Hi, 

Since one week I have this Error. When I try to install some package using "conda install -c", the command line in ubuntu 14.04 show me always the message:

Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/

Please, somebody can help me?

**Comment by kalefranz** [comment]
Please provide the output of `conda info` and the full command that is failing along with the stack trace.

**Comment by rth** [comment]
@kalefranz We are encountering the same issue on Travis CI using Python 2.7 (cf. https://github.com/PyAbel/PyAbel/issues/190). This seems to be quite similar to issue #3323.

It can be reproduced running Travis CI on [`PyAbel/rth:travis-fix`](https://github.com/rth/PyAbel/tree/travis-fix) branch, and the output can be found at,
                     https://travis-ci.org/rth/PyAbel/jobs/191950137  Only Py2.7 setup is affected, PY3.4 and  3.5 work fine.

I have added a `conda info -a` and `curl -I https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2` debug commands as suggested in the other issue for debugging.

Reruning the build several times does not solve this either. cc @DanHickstein

**Comment by arita37** [comment]
Same issue here, but CURL works: 


```
C:\Windows\system32>curl -I https://repo.continuum.io/pkgs/pro/win-64/repodata.json.bz2
HTTP/1.1 200 OK
Date: Wed, 15 Feb 2017 09:58:51 GMT
Content-Type: application/json
Content-Length: 18534
Connection: keep-alive
Set-Cookie: __cfduid=d9d8a58f3a61d2dc6834e47d49c02d9371487152731; expires=Thu, 15-Feb-18 09:58:51 GMT; path=/; domain=.continuum.io; HttpOnly
x-amz-id-2: 3VRhA5/TPpynG3vWIoo9PJ/x83RBe9oTe0yRiN5cuRhMkrbpOarOAeKHCOlE2m231NlqsBfd+Pw=
x-amz-request-id: 85644638A37DF46D
Last-Modified: Wed, 15 Feb 2017 01:53:24 GMT
x-amz-version-id: 0sUyF7.4xgSIEeUJwldFKmVHyoqXZMVo
ETag: "dc3a4dd4c0e972e2caa9c9df7d3158a1"
CF-Cache-Status: HIT
Expires: Wed, 15 Feb 2017 09:59:21 GMT
Cache-Control: public, max-age=30
Server: cloudflare-nginx
CF-RAY: 3317e759b9d50b44-NRT

```

**Comment by kalefranz** [comment]
The problem from the travis-ci output is an old version of conda--conda 3.4.3.  
https://travis-ci.org/rth/PyAbel/jobs/191950137#L273

The problem is this line here:
https://travis-ci.org/rth/PyAbel/jobs/191950137#L247

```
$ conda install --yes -c conda conda-env
Fetching package metadata ...........
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda2:
The following NEW packages will be INSTALLED:
    pyyaml:    3.12-py27_0 
The following packages will be SUPERCEDED by a higher-priority channel:
    conda-env: 2.6.0-0      --> 1.4.1-py27_0_gd8a6659 conda
The following packages will be DOWNGRADED due to dependency conflicts:
    conda:     4.3.4-py27_0 --> 3.4.3-py27_0   
```

I recommend removing that line.  As of conda 4.2, conda-env comes along with conda.  You don't need to install it separately.

**Comment by DanHickstein** [comment]
Thanks! We'll try that.

**Comment by nishankmahore** [comment]
Install MiniConda
sh Miniconda2-latest-Linux-x86_64.sh -f
In the same folder of previous  conda
It will solve all conad related problem

Works for me as charm
