### ISSUE TITLE
Relaxing channel platform requirements

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3933]
Conda should not require `/<PLATFORM>/repodata.json`. Particularly as some platforms may not have any packages at all. If it requires anything at all, it should require `/noarch/repodata.json` to make sure the channel is a real channel. This was the [suggestion]( https://github.com/Anaconda-Platform/support/issues/76#issuecomment-254618687 ) @kalefranz put forward in issue ( https://github.com/Anaconda-Platform/support/issues/76 ) and it seems quite sensible.

**Comment by kalefranz** [comment]
Here's the PR: https://github.com/conda/conda/pull/3739

It could easily be merged (with a couple test fixes).  There's been a lot of opposition to it so far though.

**Comment by kalefranz** [comment]
Going to close this ticket.  The requirement was indeed relaxed, although it's probably more accurate to consider this in limbo state.  Oh well.
