### ISSUE TITLE
Conda upgrade fails on macOS Yosemite 

### ISSUE THREAD

**Issue by tunguz** [conda/conda#3934]
Here is the error that I get:

Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /Users/tunguz/anaconda  (writable)
    default environment : /Users/tunguz/anaconda
       envs directories : /Users/tunguz/anaconda/envs
          package cache : /Users/tunguz/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/tunguz/anaconda/bin/conda upgrade conda`

    Traceback (most recent call last):
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by azotova** [comment]
I had a very similar issue and was able to fix it following these instructions http://stackoverflow.com/questions/40748838/problems-with-updating-anaconda-and-installing-new-packages  (issue #3929)

**Comment by kalefranz** [comment]
Duplicate of #3929 and #3935.  Honestly not sure where this came from all the sudden.  We definitely need to limit dependencies somewhere.

In general `pyopenssl` and `cryptography` are out of sync.

    CONDA_VERIFY_SSL=false conda update pyopenssl

should fix your problem

**Comment by tunguz** [comment]
Sorry, but that did not solve the issue. Please re-open this issue. Here is the error message that I got:

`$ /Users/tunguz/anaconda/bin/conda update pyopenssl`




    Traceback (most recent call last):
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/tunguz/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by kalefranz** [comment]
@tunguz What do you have for `conda list`?

**Comment by tunguz** [comment]
Here is the output:

# packages in environment at /Users/tunguz/anaconda:
#
_license                  1.1                      py27_0    None://None/<unknown>
abstract-rendering        0.5.1                np19py27_0    None://None/<unknown>
accelerate                1.13.0              np19py27_p0  
alabaster                 0.7.3                    py27_0    None://None/<unknown>
anaconda                  2.3.0                np19py27_0    None://None/<unknown>
appnope                   0.1.0                     <pip>
appscript                 1.0.1                    py27_0    None://None/<unknown>
argcomplete               0.8.9                    py27_0    None://None/<unknown>
astropy                   1.0.3                np19py27_0    None://None/<unknown>
babel                     1.3                      py27_0    None://None/<unknown>
bayesian-optimization     0.1.0                     <pip>
bcolz                     0.9.0                np19py27_0    None://None/<unknown>
beautiful-soup            4.3.2                    py27_0    None://None/<unknown>
binstar                   0.11.0                   py27_0    None://None/<unknown>
bitarray                  0.8.1                    py27_0    None://None/<unknown>
blaze-core                0.8.0                np19py27_0    None://None/<unknown>
blz                       0.6.2                np19py27_1    None://None/<unknown>
bokeh                     0.9.0                np19py27_0    None://None/<unknown>
boto                      2.38.0                   py27_0    None://None/<unknown>
bottleneck                1.0.0                np19py27_0    None://None/<unknown>
brew                      0.1.3                     <pip>
cdecimal                  2.3                      py27_0    None://None/<unknown>
certifi                   14.05.14                 py27_0    None://None/<unknown>
cffi                      1.1.0                    py27_0    None://None/<unknown>
clyent                    0.3.4                    py27_0    None://None/<unknown>
colorama                  0.3.3                    py27_0    None://None/<unknown>
conda                     4.2.11                   py27_0  
conda-build               1.14.1                   py27_0    None://None/<unknown>
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0    None://None/<unknown>
cryptography              0.9.1                    py27_0    None://None/<unknown>
cssselect                 0.9.1                     <pip>
cudatoolkit               7.0                           1  
curl                      7.43.0                        0    None://None/<unknown>
cv2                       1.0                       <pip>
cython                    0.22.1                   py27_0    None://None/<unknown>
cytoolz                   0.7.3                    py27_0    None://None/<unknown>
datashape                 0.4.5                np19py27_0    None://None/<unknown>
decorator                 3.4.2                    py27_0    None://None/<unknown>
Django                    1.9                       <pip>
django                    1.8.4                    py27_0  
docutils                  0.12                     py27_0    None://None/<unknown>
dynd-python               0.6.5                np19py27_0    None://None/<unknown>
enum34                    1.0.4                    py27_0    None://None/<unknown>
fastcache                 1.0.2                    py27_0    None://None/<unknown>
feedfinder2               0.0.1                     <pip>
feedparser                5.1.3                     <pip>
flask                     0.10.1                   py27_1    None://None/<unknown>
freetype                  2.5.5                         0  
funcsigs                  1.0.2                     <pip>
funcsigs                  0.4                      py27_0    None://None/<unknown>
future                    0.15.2                    <pip>
geograpy                  0.3.7                     <pip>
gevent                    1.0.1                    py27_0    None://None/<unknown>
gevent-websocket          0.9.3                    py27_0    None://None/<unknown>
gnureadline               6.3.3                     <pip>
google-api-python-client  1.5.3                     <pip>
greenlet                  0.4.7                    py27_0    None://None/<unknown>
grin                      1.2.1                    py27_1    None://None/<unknown>
h2o                       3.8.3.2                   <pip>
h5py                      2.5.0                np19py27_3    None://None/<unknown>
hdf5                      1.8.15.1                      1    None://None/<unknown>
hep-ml                    0.3.0                     <pip>
httplib2                  0.9.2                     <pip>
idna                      2.0                      py27_0    None://None/<unknown>
image                     1.4.3                     <pip>
imageio                   1.6                       <pip>
ipaddress                 1.0.7                    py27_0    None://None/<unknown>
ipykernel                 4.3.1                     <pip>
ipython                   4.1.2                     <pip>
ipython                   3.2.0                    py27_0    None://None/<unknown>
ipython-genutils          0.1.0                     <pip>
ipython-notebook          3.2.0                    py27_0    None://None/<unknown>
ipython-qtconsole         3.2.0                    py27_0    None://None/<unknown>
ipywidgets                4.1.1                     <pip>
itsdangerous              0.24                     py27_0    None://None/<unknown>
jbig                      2.1                           0  
jdcal                     1.0                      py27_0    None://None/<unknown>
jedi                      0.8.1                    py27_0    None://None/<unknown>
jellyfish                 0.5.6                     <pip>
jieba                     0.35                      <pip>
jinja2                    2.7.3                    py27_1    None://None/<unknown>
jpeg                      8d                            1    None://None/<unknown>
jsonschema                2.4.0                    py27_0    None://None/<unknown>
jupyter                   1.0.0                     <pip>
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
Keras                     1.0.7                     <pip>
launcher                  1.0.0                         3    None://None/<unknown>
libdynd                   0.6.5                         0    None://None/<unknown>
libpng                    1.6.17                        0    None://None/<unknown>
libsodium                 0.4.5                         0    None://None/<unknown>
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0    None://None/<unknown>
libxslt                   1.1.28                        2    None://None/<unknown>
llvmlite                  0.6.0                    py27_0  
lxml                      3.3.5                     <pip>
lxml                      3.4.4                    py27_0    None://None/<unknown>
markupsafe                0.23                     py27_0    None://None/<unknown>
matplotlib                1.4.3                np19py27_2    None://None/<unknown>
mistune                   0.5.1                    py27_1    None://None/<unknown>
mkl                       11.3.1                        0  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p1  
mklfft                    2.0                 np19py27_p0  
ml-metrics                0.1.4                     <pip>
mock                      2.0.0                     <pip>
mock                      1.0.1                    py27_0    None://None/<unknown>
moviepy                   0.2.2.11                  <pip>
multipledispatch          0.4.7                    py27_0    None://None/<unknown>
mysql-connector-python    2.0.3                    py27_0  
MySQL-python              1.2.5                     <pip>
nbconvert                 4.1.0                     <pip>
nbformat                  4.0.1                     <pip>
networkx                  1.9.1                    py27_0    None://None/<unknown>
newspaper                 0.0.9.8                   <pip>
nltk                      2.0.5                     <pip>
nltk                      3.0.3                np19py27_0    None://None/<unknown>
node-webkit               0.10.1                        0    None://None/<unknown>
nose                      1.3.7                    py27_0    None://None/<unknown>
notebook                  4.1.0                     <pip>
numba                     0.20.0               np19py27_0  
numbapro                  0.20.0              np19py27_p1  
numbapro_cudalib          0.2                           0  
numpy                     1.11.1                    <pip>
numpy                     1.11.2                    <pip>
numpy                     1.10.4                   py27_0  
oauth2client              3.0.0                     <pip>
oauthlib                  1.0.3                     <pip>
odo                       0.3.2                np19py27_0    None://None/<unknown>
opencv                    2.4.8                np17py27_2  
openpyxl                  1.8.5                    py27_0    None://None/<unknown>
openssl                   1.0.2g                        0  
pandas                    0.18.0                    <pip>
pandas                    0.18.0              np110py27_0  
path.py                   8.1.2                     <pip>
patsy                     0.3.0                np19py27_0    None://None/<unknown>
pbr                       1.10.0                    <pip>
pep8                      1.6.2                    py27_0    None://None/<unknown>
pexpect                   4.0.1                     <pip>
pickleshare               0.6                       <pip>
pillow                    3.0.0                    py27_1  
Pillow                    2.5.1                     <pip>
pip                       8.1.1                    py27_0  
ply                       3.6                      py27_0    None://None/<unknown>
protobuf                  3.0.0                     <pip>
psutil                    2.2.1                    py27_0    None://None/<unknown>
ptyprocess                0.5.1                     <pip>
ptyprocess                0.4                      py27_0    None://None/<unknown>
py                        1.4.27                   py27_0    None://None/<unknown>
pyasn1                    0.1.9                     <pip>
pyasn1                    0.1.7                    py27_0    None://None/<unknown>
pyasn1-modules            0.0.8                     <pip>
pyaudio                   0.2.7                    py27_0    None://None/<unknown>
pycosat                   0.6.1                    py27_0    None://None/<unknown>
pycountry                 1.20                      <pip>
pycparser                 2.14                     py27_0    None://None/<unknown>
pycrypto                  2.6.1                    py27_0    None://None/<unknown>
pycurl                    7.19.5.1                 py27_2    None://None/<unknown>
pyflakes                  0.9.2                    py27_0    None://None/<unknown>
pygments                  2.0.2                    py27_0    None://None/<unknown>
pyopenssl                 0.15.1                   py27_1    None://None/<unknown>
pyparsing                 2.0.3                    py27_0    None://None/<unknown>
pyqt                      4.11.3                   py27_0    None://None/<unknown>
pytables                  3.2.0                np19py27_0    None://None/<unknown>
pytest                    2.7.1                    py27_0    None://None/<unknown>
python                    2.7.12                        1  
python-dateutil           2.4.0                     <pip>
python-dateutil           2.4.2                    py27_0    None://None/<unknown>
python.app                1.2                      py27_4    None://None/<unknown>
pytz                      2015.4                   py27_0    None://None/<unknown>
pytz                      2016.2                    <pip>
pyyaml                    3.11                     py27_1    None://None/<unknown>
pyzmq                     14.7.0                   py27_0    None://None/<unknown>
qt                        4.8.6                         3    None://None/<unknown>
qtconsole                 4.2.0                     <pip>
readline                  6.2                           2    None://None/<unknown>
redis                     2.6.9                         0    None://None/<unknown>
redis-py                  2.10.3                   py27_0    None://None/<unknown>
requests                  2.12.1                    <pip>
requests                  2.9.1                    py27_0  
requests-oauthlib         0.6.0                     <pip>
rope                      0.9.4                    py27_1    None://None/<unknown>
rsa                       3.4.2                     <pip>
ruamel_yaml               0.11.14                  py27_0  
runipy                    0.1.3                    py27_0    None://None/<unknown>
scikit-image              0.11.3               np19py27_0    None://None/<unknown>
scikit-learn              0.17.1              np110py27_0  
scipy                     0.18.0                    <pip>
scipy                     0.17.0              np110py27_0  
seaborn                   0.7.1                     <pip>
setuptools                28.8.0                    <pip>
setuptools                20.3                     py27_0  
simplegeneric             0.8.1                     <pip>
simplejson                3.8.2                     <pip>
sip                       4.16.5                   py27_0    None://None/<unknown>
six                       1.9.0                    py27_0    None://None/<unknown>
six                       1.10.0                    <pip>
sklearn                   0.0                       <pip>
snowballstemmer           1.2.0                    py27_0    None://None/<unknown>
sockjs-tornado            1.0.1                    py27_0    None://None/<unknown>
sphinx                    1.3.1                    py27_0    None://None/<unknown>
sphinx_rtd_theme          0.1.7                    py27_0    None://None/<unknown>
spyder                    2.3.5.2                  py27_0    None://None/<unknown>
spyder-app                2.3.5.2                  py27_0    None://None/<unknown>
sqlalchemy                1.0.5                    py27_0    None://None/<unknown>
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_0    None://None/<unknown>
statsmodels               0.6.1                np19py27_0    None://None/<unknown>
sympy                     0.7.6                    py27_0    None://None/<unknown>
tabulate                  0.7.5                     <pip>
tensorflow                0.11.0                    <pip>
terminado                 0.5                      py27_0    None://None/<unknown>
Theano                    0.8.2                     <pip>
tk                        8.5.18                        0    None://None/<unknown>
tldextract                1.5.1                     <pip>
toolz                     0.7.2                    py27_0    None://None/<unknown>
tornado                   4.2                      py27_0    None://None/<unknown>
tqdm                      4.9.0                     <pip>
traitlets                 4.2.1                     <pip>
tweepy                    3.5.0                     <pip>
twython                   3.4.0                     <pip>
ujson                     1.33                     py27_0    None://None/<unknown>
unicodecsv                0.9.4                    py27_0    None://None/<unknown>
uritemplate               0.6                       <pip>
werkzeug                  0.10.4                   py27_0    None://None/<unknown>
wheel                     0.29.0                   py27_0  
wikipedia                 1.4.0                     <pip>
xgboost                   0.4a13                    <pip>
xlrd                      0.9.3                    py27_0    None://None/<unknown>
xlsxwriter                0.7.3                    py27_0    None://None/<unknown>
xlwings                   0.3.5                    py27_0    None://None/<unknown>
xlwt                      1.0.0                    py27_0    None://None/<unknown>
xz                        5.0.5                         0  
yaml                      0.1.6                         0    None://None/<unknown>
zeromq                    4.0.5                         0    None://None/<unknown>
zlib                      1.2.8                         0    None://None/<unknown>

**Comment by kalefranz** [comment]
Honestly not sure what that None://None/ thing is about. It's a bug (I guess?), but I've never seen it before at all. What are the contents of whatever your `conda info` says is your condarc file?

Also, you've got a ton of overlap between pip and conda installs going on. Maybe the most I've ever seen. To get conda working again, maybe try 

    pip install -U requests==2.11.1 pyopenssl cryptograpy

**Comment by tunguz** [comment]
All right, that seems to have fixed it! Thanks a lot, and thanks for all your attention and effort. BTW, the content of my 'conda info' has been mentioned at the very start of this issue thread. 

Yes, I've been vaguely aware of some conflicts with pip/conda from before. Unfortunately, there are a lot of packages that for whatever reason I am only able to install/upgrade using either pip or conda, and hence I've been going back and forth with the two.
