### ISSUE TITLE
I met a trouble in running conda test

### ISSUE THREAD

**Issue by NWAFU-daniel** [conda/conda#3946]
Fetching package metadata .....Could not connect to https://repo.continuum.io/pkgs/free/linux-64
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/daniel/miniconda2  (writable)
    default environment : /home/daniel/miniconda2
       envs directories : /home/daniel/miniconda2/envs
          package cache : /home/daniel/miniconda2/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/daniel/.condarc
           offline mode : False

`$ /home/daniel/miniconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/daniel/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/linux-64

thanks for your kind help.

**Comment by kalefranz** [comment]
This is a HTTP timeout issue.  I've been seeing a lot of these lately, especially for users located in China.  My best advice right now: keep trying `conda update conda` over and over. Maybe at different times of the day.  It will hopefully at some point succeed.  If it DOES succeed, then there should be a little bit of relief for you in the update conda `4.2.13`.  There we increased the HTTP handshake timeout from `3.05` seconds to `6.1` seconds.  In conda `4.3`, we'll be making these timeout values configurable.

**Comment by NWAFU-daniel** [comment]
i tried many times as instructed, and it finally works. Now my conda version is 4.2.13, thanks  again. @kalefranz
