### ISSUE TITLE
help message update-dependencies/no-update-dependencies contradiction

### ISSUE THREAD

**Issue by akubiak** [conda/conda#3951]
The help message output appears to be self-contradictory. While I believe dependencies are suggested to be updated by default, the help message output for the optional flags `--update-deps` and `--no-update-deps` appear to contradict each other.

    $ conda --version
    conda 4.2.13
    $ conda install --help
    ...
    --update-dependencies, --update-deps
                          Don't update dependencies (default: True).
    --no-update-dependencies, --no-update-deps
                          Don't update dependencies (default: False).

**Comment by kalefranz** [comment]
Fixed.
