### ISSUE TITLE
Cannot install packages after fresh install

### ISSUE THREAD

**Issue by matthpich** [conda/conda#3962]
Hi there,
I keep getting this error message, whenever I try to install any package after a fresh miniconda install.
Any help would be very much appreciated.
Thanks in advance!

--

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/pichama3/miniconda3  (writable)
    default environment : /home/pichama3/miniconda3
       envs directories : /home/pichama3/miniconda3/envs
          package cache : /home/pichama3/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/pichama3/miniconda3/bin/conda install snakemake`

    Traceback (most recent call last):
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
        conn = self._new_conn()
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 66, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment]
Probably an issue with requests, fixed with a requests update.

**Comment by kalefranz** [comment]
Reopened this ticket, because it's the first report of several duplicate issues.

**Comment by kalefranz** [comment]
From https://github.com/conda/conda/issues/4724#issuecomment-282239443:

> My bad. I'd managed to remove one of the forward slashes of the proxy in the .condarc file. (https:/ instead of https://)

**Comment by kalefranz** [comment]
For anyone having this issue, please investigate your proxy configuration.  Also if you find an error, report back on the details of where you configured in an error, so that we can help give conda better error messages in the future.

**Comment by foxl-studio** [comment]
@kalefranz 
I tried print the proxies used at runtime, and got this:
**OrderedDict([('http', 'http://'), ('https', 'https://'), ('ftp', 'ftp://')])**
That proxies are from requests.adapters:get_connection function's parameter. Then the **select_proxy**  will select ('https', 'https://') as proxy, that's why no host in following steps.
I don't have any VPN enabled, so there's no proxy in Windows system when executing conda.

For now, I just add one statement in **HTTPSConnectionPool._new_conn** function to hide proxy, and it works: 

![image](https://user-images.githubusercontent.com/8531280/31279416-978988c8-aadb-11e7-877b-4e6206298ddc.png)

I think the proxies passed to requests.adapters may have some problems, but I don't have more time on debugging it. The no-proxy solution works fine for now, but it won't be final solution.

**Comment by foxl-studio** [comment]
Following are my debug info, hope can do something useful

DEBUG conda.core.index:fetch_index(114): channel_urls=OrderedDict([('https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64', ('https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free', 0)), ('https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch', ('https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free', 0)), ('https://repo.continuum.io/pkgs/main/win-64', ('defaults', 1)), ('https://repo.continuum.io/pkgs/main/noarch', ('defaults', 1)), ('https://repo.continuum.io/pkgs/free/win-64', ('defaults', 2)), ('https://repo.continuum.io/pkgs/free/noarch', ('defaults', 2)), ('https://repo.continuum.io/pkgs/r/win-64', ('defaults', 3)), ('https://repo.continuum.io/pkgs/r/noarch', ('defaults', 3)), ('https://repo.continuum.io/pkgs/pro/win-64', ('defaults', 4)), ('https://repo.continuum.io/pkgs/pro/noarch', ('defaults', 4)), ('https://repo.continuum.io/pkgs/msys2/win-64', ('defaults', 5)), ('https://repo.continuum.io/pkgs/msys2/noarch', ('defaults', 5))])
Fetching package metadata ...DEBUG urllib3.util.retry:from_int(200): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG conda.core.repodata:fetch_repodata(458): Locally invalidating cached repodata for https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64 at C:\Users\Fox\Anaconda3\pkgs\cache\a2eb941d.json
DEBUG requests.utils:select_proxy(707):
        FOXADDED urlparts.hostname:mirrors.tuna.tsinghua.edu.cn
DEBUG requests.adapters:get_connection(302):
        FOXADDED url:https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/repodata.json proxy.host : https:// proxies:OrderedDict([('http', 'http://'), ('https', 'https://'), ('ftp', 'ftp://')])
DEBUG urllib3.poolmanager:connection_from_url(279):
        FOXADDED url->https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/repodata.json    host->mirrors.tuna.tsinghua.edu.cn    scheme->https
DEBUG urllib3.poolmanager:connection_from_host(217):
        FOXADDED host->mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connectionpool:__init__(184):
        FOXADDED proxy.host : None
DEBUG requests.adapters:get_connection(313):
        FOXADDED conn.host->mirrors.tuna.tsinghua.edu.cn
DEBUG requests.utils:select_proxy(707):
        FOXADDED urlparts.hostname:mirrors.tuna.tsinghua.edu.cn
DEBUG requests.adapters:send(413):
        FOXADDED url->/anaconda/pkgs/free/win-64/repodata.json
DEBUG requests.adapters:send(414):
        FOXADDED conn.proxy->https://:443 conn.host->mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connectionpool:_new_conn(827): Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connection:__init__(222):
        FOXADDED --> 6  host: mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connection:__init__(107):
        FOXADDED -->1
DEBUG urllib3.connection:set_cert(276):
        FOXADDED -->8  assert_hostname: None
DEBUG urllib3.connectionpool:urlopen(594):
        FOXADDED conn.host->mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connection:connect(292):
        FOXADDED -->9 self.host: mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connection:_new_conn(134):
        FOXADDED -->2  self.host: mirrors.tuna.tsinghua.edu.cn
DEBUG urllib3.connection:_match_hostname(366):
        FOXADDED -->10

**Comment by kalefranz** [comment]
* https://stackoverflow.com/questions/46260169/python-locationvalueerror-no-host-specified
* https://stackoverflow.com/questions/46053826/pip-exception-attributeerror-nonetype-object-has-no-attribute-startswith

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/pull/6205 and https://github.com/requests/requests/issues/4353

**Comment by saraneem** [comment]
After installing Anaconda 5.1, Python 3.6, getting the following error:

```conda info pyodbc

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
return func(*args, **kwargs)
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
exit_code = do_call(args, p)
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
exit_code = getattr(module, func_name)(args, parser)
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\cli\main_info.py", line 299, in execute
print_package_info(args.packages)
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\cli\main_info.py", line 95, in print_package_info
results[package] = tuple(SubdirData.query_all(context.channels, context.subdirs, spec))
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\core\repodata.py", line 86, in query_all
return tuple(concat(future.result() for future in as_completed(futures)))
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\core\repodata.py", line 90, in query
self.load()
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\core\repodata.py", line 134, in load
_internal_state = self._load()
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\core\repodata.py", line 202, in _load
mod_etag_headers.get('_mod'))
File "C:\Users\pl02346\anaconda3\lib\site-packages\conda\core\repodata.py", line 402, in fetch_repodata_remote_request
timeout=timeout)
File "C:\Users\pl02346\anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
return self.request('GET', url, **kwargs)
File "C:\Users\pl02346\anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\pl02346\anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "C:\Users\pl02346\anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
timeout=timeout
File "C:\Users\pl02346\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
self._prepare_proxy(conn)
File "C:\Users\pl02346\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
conn.connect()
File "C:\Users\pl02346\anaconda3\lib\site-packages\urllib3\connection.py", line 284, in connect
conn = self._new_conn()
File "C:\Users\pl02346\anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "C:\Users\pl02346\anaconda3\lib\site-packages\urllib3\util\connection.py", line 51, in create_connection
if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'

`$ C:\Users\pl02346\anaconda3\Scripts\conda info pyodbc`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```
```
conda info -a

active environment : base
active env location : C:\Users\pl02346\anaconda3
shell level : 1
user config file : C:\Users\pl02346\.condarc
populated config files : C:\Users\pl02346\.condarc
conda version : 4.4.10
conda-build version : 3.4.1
python version : 3.6.4.final.0
base environment : C:\Users\pl02346\anaconda3 (writable)
channel URLs : https://repo.continuum.io/pkgs/main/win-64
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/win-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/win-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/win-64
https://repo.continuum.io/pkgs/pro/noarch
https://repo.continuum.io/pkgs/msys2/win-64
https://repo.continuum.io/pkgs/msys2/noarch
package cache : C:\Users\pl02346\anaconda3\pkgs
C:\Users\pl02346\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\pl02346\anaconda3\envs
C:\Users\pl02346\AppData\Local\conda\conda\envs
C:\Users\pl02346\.conda\envs
platform : win-64
user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/7 Windows/6.1.7601
administrator : False
netrc file : None
offline mode : False

# conda environments:
#
base * C:\Users\pl02346\anaconda3

sys.version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 ...
sys.prefix: C:\Users\pl02346\anaconda3
sys.executable: C:\Users\pl02346\anaconda3\python.exe
conda location: C:\Users\pl02346\anaconda3\lib\site-packages\conda
conda-build: C:\Users\pl02346\anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\pl02346\anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\pl02346\anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\pl02346\anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\pl02346\anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\pl02346\anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\pl02346\anaconda3\Scripts\conda-metapackage.exe
conda-render: C:\Users\pl02346\anaconda3\Scripts\conda-render.exe
conda-server: C:\Users\pl02346\anaconda3\Scripts\conda-server.exe
conda-skeleton: C:\Users\pl02346\anaconda3\Scripts\conda-skeleton.exe
conda-verify: C:\Users\pl02346\anaconda3\Scripts\conda-verify.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: base
CONDA_PREFIX: C:\Users\pl02346\anaconda3
CONDA_PROMPT_MODIFIER: (base)
CONDA_PYTHON_EXE: C:\Users\pl02346\anaconda3\python.exe
CONDA_ROOT: C:\Users\pl02346\anaconda3
CONDA_SHLVL: 1
HOMEPATH: \
HTTPS_PROXY: <set>
HTTP_PROXY: <set>
PATH: C:\Users\pl02346\anaconda3;C:\Users\pl02346\anaconda3\Library\mingw-w64\bin;C:\Users\pl02346\anaconda3\Library\usr\bin;C:\Users\pl02346\ana
conda3\Library\bin;C:\Users\pl02346\anaconda3\Scripts;C:\Users\pl02346\anaconda3\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\W
INDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\
1E\NomadBranch\;C:\Program Files (x86)\BlueZone\7.1\;c:\Program Files\VanDyke Software\Clients\;C:\Program Files\IDM Computer Solutions\UltraComp
are
PSMODULEPATH: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\Microsoft Application Virtualization\Client\;C:\Program Files
(x86)\Microsoft Azure Information Protection\Powershell
PYTHONIOENCODING: 1252
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>


WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```
```
conda config show
usage: conda config [-h] [--json] [--debug] [--verbose]
[--system | --env | --file FILE]
(--show [SHOW [SHOW ...]] | --show-sources | --validate | --describe [DESCRIBE [DESCRIBE ...]] | --write-default | --get [KEY
[KEY ...]] | --append KEY VALUE | --prepend KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY | --stdin)
conda config: error: one of the arguments --show --show-sources --validate --describe --write-default --get --append --prepend/--add --set --remo
ve --remove-key --stdin is required

(base) C:\Users\pl02346>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
- ca-certificates
- certifi
- openssl
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
- defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
pkgs/main: https://repo.continuum.io
pkgs/free: https://repo.continuum.io
pkgs/r: https://repo.continuum.io
pkgs/pro: https://repo.continuum.io
pkgs/msys2: https://repo.continuum.io
custom_multichannels:
defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.cont
inuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/msys2"]
local: []
default_channels:
- https://repo.continuum.io/pkgs/main
- https://repo.continuum.io/pkgs/free
- https://repo.continuum.io/pkgs/r
- https://repo.continuum.io/pkgs/pro
- https://repo.continuum.io/pkgs/msys2
disallow: []
download_only: False
envs_dirs:
- C:\Users\pl02346\anaconda3\envs
- C:\Users\pl02346\AppData\Local\conda\conda\envs
- C:\Users\pl02346\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
- C:\Users\pl02346\anaconda3\pkgs
- C:\Users\pl02346\AppData\Local\conda\conda\pkgs
proxy_servers:
http: http://pl02346:xxxxxx@xxxxxx:8080
https: https://pl02346:xxxxx@xxxxxx:8080
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: False
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```

**Comment by kalefranz** [comment]
@saraneem I promise this is an error in proxy configuration. It also has nothing to do with conda, but is an error in requests/urllib3. @nehaljwani has gotten a fix into upstream requests, but after months they still haven’t had a release with the change. 

The information you’ve provided show that both `HTTP_PROXY` and `HTTPS_PROXY` environment variables are set. Triple check the contents of those environment variables. As I recall, the most common cause of this error is missing a `/` in the proxy url. For example, having `http:/proxy.server` instead of `http://proxy.server`. 

Also, requests picks proxy configuration out of the windows registry. We don’t report that in `confa info` right now, but we should.

**Comment by saraneem** [comment]
The issue was resolved, proxy config had a typo.
@kalefranz Thank you for your quick response.

**Comment by SackeyDavid** [comment]
For me, after countless twists and turns, conda started working (that is installing packages) after an unintended PC reboot.
