### ISSUE TITLE
updating/installing nb_conda, nb_conda_kernels, nb_anacondacloud does not always make python3 kernels available in python2 envs

### ISSUE THREAD

**Issue by mpacer** [conda/conda#3963]
I was trying to get a python3 kernel working inside a python2 environment (testing the compatibility of building the jupyter notebook documentation which includes notebooks that use python3 kernels). 

Following http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-python-2-and-3 did not solve the problem & though it apparently installed a python3 kernel according to the kernelspec list. 

I arrived at http://stackoverflow.com/questions/38257138/jupyter-no-such-kernel-named-python3 (specifically http://stackoverflow.com/a/38705741/1816995) but this also did not work. 

Additionally, I have a (pip based) editable install of the notebook, and when installing/updating `nb_conda`, `nb_conda_kernels`, and `nb_anacondacloud` it did not recognise this, but instead created a hard dependency on notebook 4.2.3. This doesn't seem to shadow my editable install when I open a python or IPython interpreter, but I could see that that may be part of what is causing the problem.

If it *had* shadowed my install, attempting to `conda uninstall notebook` also uninstalls `nb_conda`, `nb_conda_kernels`, and `nb_anacondacloud` meaning that the SO solution wouldn't have worked.

NB: Eventually I was able to get this to work after manually deleting & recreating the kernelspec file, but I figured that this was enough of a pain that you should be made aware (especially if it was at all related to the shadowing).

**Comment by kalefranz** [comment]
I'm not sure if anaconda-issues is the right tracker for this, but this one definitely isn't.  I'm moving it to anaconda-issues.  @csoja might want to move it again.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1692
