### ISSUE TITLE
Conda gives "Malformed version string" for versions with wildcard after underscore in 4.2.0

### ISSUE THREAD

**Issue by jehturner** [conda/conda#3964]
In Anaconda 4.1, I could specify package dependency versions in meta.yaml as:
`- package.name sometag_*`

In 4.2.0, I get an error like this from the `VersionSpec` class when running conda-build:
`conda.exceptions.CondaValueError: Value error: Malformed version string 'sometag_': empty version component.`

The same thing happens with `conda install package.name=sometag_*`. In both cases, `sometag_*` has to be changed to `sometag*`, which seems like a bug (why should the expression fail to match only when the wildcard appears after a certain character in the full version string?).

This is no big deal for me, since I can just omit the underscore, but in principle doing so could lead to ambiguity without that delimiter, where one tag is a substring of another, which would be a more serious problem. I would also like to be able to give internal users instructions including the underscore.

No urgency, mainly just FYI. Thanks!

James.

**Comment by kalefranz** [comment]
There's a lot of discussion about version parsing in https://github.com/conda/conda/issues/2071
