### ISSUE TITLE
Track requested packages

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3968]
Some time back @mcg1969 , @mingwandroid and I had a discussion about tracking requested packages vs. unrequested dependencies needed to satisfy the requested ones. We agreed it would be valuable for `conda` to track requested packages as explained in this [comment]( https://github.com/conda/conda/issues/2651#issuecomment-225313705 ).

One example of a case needing to track requested packages is upgrading a Python 2 to Python 3 environment where compatibility packages (e.g. `backports.*`) are installed. We are ok with the backports that are explicitly installed being removed to accomplish an upgrade to Python 3. However, we can't currently explain this to `conda` without `conda` learning about which packages we care about being installed.

Another example I was thinking of this lately is solver priority. For instance, if I install package `A` and it pulls in `B` and `C`, when I run upgrade a downgrade for `A` could be preferred if it will result in an upgrade to `B` and `C`. However, this seems counterintuitive as `A` is the package I care about having installed. So I would want the latest version of `A` always even if that means `B` and `C` get downgraded.

xref: https://github.com/conda/conda/issues/2651

**Comment by mcg1969** [comment]
Definitely good ideas here. Much of the machinery needed to determine the requested package list is already in conda. The key is telling the solver that the non-requested packages are optional... and that their upgrade behavior should be subservient to the requested ones. Will have to give this some thought but I am certain it's doable.

**Comment by kalefranz** [comment]
For the non-solver-related use-cases, it's actually already done.

------

#### A digression

I'm going to have people arguing my ear off for this probably, but you'll soon be able to pip install conda.  With two **big** ✳️ asterisks.

✳️  The pip-installed version posted on PyPI will be useful for a python library only.  It will not create entry points.  It will not be useable as most people would normally use conda--as an application.

We will hopefully soon have other methods for installing/bootstrapping conda, including rpm and deb packages.  Maybe even a homebrew recipe.  But pip with all python tooling including wheels in their current form is not capable of installing conda as an application.

✳️ Use conda as a python library at your own risk.  Explicitly pin dependencies for your application, and upgrade diligently but deliberately.  All of conda's internal code *is not* a public API, even though it's written in python, and python doesn't support "private" code.

The single long-term supported API is the command line API.  I'm soon going to add some code that let's you easily use that command line API in process, without having to shell out.  The other "LTS"-ish supported interface is `conda/exports.py`, which conda-build is using.

Digression over.

---------

For the user-requested items you're looking for, try this

```
from pprint import pprint
from conda.history import History

prefix="/some/conda/path/prefix"

history = History(prefix)
with History(prefix) as h:
    pprint(h.get_user_requests())
```

**Comment by jakirkham** [comment]
In response to the digression, we had planned to make an installer for the conda-forge stack before. This may help those concerned about having a completely open installer. Largely I think people are in favor of the idea. Though one of our concerns was `constructor` has no way to disambiguate channels included by default from `defaults` as we know it canonically. We don't too much like the idea of the `conda-forge` channel being called `defaults` as it would make things very confusing for everyone. Especially as we still need the `defaults` channel for some things. If we have a way to name preincluded channels in the installer like in this proposal ( https://github.com/conda/constructor/issues/42 ), that would be very helpful.

In response to the history, that is very interesting. I did not know that. Seems this gives one some sort of JSON that is already quite amenable to solving this problem. Appears `specs` has the packages added in from each step. Though it seems to include `conda` and `conda-env` in some of the `specs`. What is happening there?

**Comment by electronwill** [comment]
Another benefit in tracking which packages were user requested: I've heard a few users say they'd like to be able to export the user requested packages of an environment but not the unrequested dependencies.

**Comment by mingwandroid** [comment]
Exporting the dependencies exposes possibly platform specific implementation details (whether to use thrift vs thrify-py for example) and makes the exported list non-portable.

**Comment by jakirkham** [comment]
Ran into another a real world problem recently over at Dask that I expect would be fixed by this depending on how it is implement. Please see this [comment]( https://github.com/dask/dask/issues/2191#issuecomment-292797498 ) for a more detailed explanation and the OP for an example of the problem.

**Comment by kalefranz** [comment]
Conda does this even better as part of conda 4.4.  Closing this ticket.

**Comment by jakirkham** [comment]
Could you please elaborate @kalefranz? I'm not seeing a PR; so, am having trouble understanding in what ways this issue has been addressed.

**Comment by kalefranz** [comment]
Conda 4.4 records the specs users used on the command line for each operation. They’re recorded in the `conda-meta/history` file.

**Comment by ankostis** [comment]
Wouldn't be nice to have a command-line option like `conda env export --user-requested`,
based, for instance, on the [sample code of @zertrin](https://github.com/conda/conda/issues/4545#issuecomment-469984684)?
