### ISSUE TITLE
explicit() doesn't remove existing package first => try_hard_link() fails => symlinks are used => relative RPATHs in executables do not work.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#3974]
I was looking into why symlinks were being used everywhere as it was preventing me from testing packages installed with a full path.

It seems that `explicit()` (or something in that callstack) doesn't remove the existing package first.

This means that `try_hard_link()` will fail because `dst` exists and `assert not isfile(dst), dst` will fire. This gets caught in `explicit()` which (I guess) makes the assumption that hardlinks are not possible.

Conda then goes off and symlinks everything which causes `RPATH` to fail in executables as symlinks are followed before the RPATH is canonicalized/normalized.

I'm not sure if there's a reason not to unlink first? But this bug also gives us the opportunity to mark executables as such and *never* symlink them.

**Comment by mingwandroid** [comment]
Some more info. Perhaps the old version does get removed. I added a print in `try_hard_link()` and it tells me:

```
try_hard_link src=/home/ray/mc-x64-3.5/pkgs/r-base-3.3.1-6/info/index.json, dst=local::/.tmp-r-base-3.3.1-6 isfile(src)=True not isfile(dst)=True
```

`dst=local::/.tmp-r-base-3.3.1-6` looks pretty wrong.

**Comment by kalefranz** [comment]
I'm touching this explicit beast now for another problem I'm having. I'll poke around at this too.

**Comment by mingwandroid** [comment]
Cool. The title is likely incorrect though, but it's probably work checking if it does indeed unlink first. My 3975 pr fixes the bug anyway so merging that would work for me.
