### ISSUE TITLE
Cleaning up after creating env from specfile removes libpython

### ISSUE THREAD

**Issue by y0ast** [conda/conda#3977]
We use conda to create an environment from a specfile. This specfile includes python 3.5.2:

`conda create -n devenv --file /spec-file.txt python=3.5.2 -y`

Afterwards we run:

`conda clean --all`

This removes libpython:

```
$ python
python: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

libpython is symlinked to a non existing directory (which was removed by clean):
```
/home/user/conda/envs/python3_5_2/lib/libpython3.5m.so.1.0 -> /home/user/conda/pkgs/python-3.5.2-0/lib/libpython3.5m.so.1.0
```

The minimal specfile:
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/python-3.5.2-0.tar.bz2
```

Platform: CentOS 6.8
Miniconda version: 4.2.12 AND 4.2.13

Note this used to NOT be a problem on Miniconda version 4.1.11. In that version the libpython is not symlinked, but actually at the expected place in: `/home/user/conda/envs/python3_5_2/lib/libpython3.5m.so.1.0 `.

**Comment by kalefranz** [comment]
Can you verify that this is still a problem with conda 4.3?  Latest is 4.3.17.

**Comment by y0ast** [comment]
It's fixed! Thanks
