### ISSUE TITLE
activate and powerline don't play nice together

### ISSUE THREAD

**Issue by cstich** [conda/conda#3982]
I am using [powerline](https://github.com/powerline/powerline) to display the current anaconda environment in my shell. However, when I use  `source active MY_ENV ` it doesn't realize that I am already using `powerline` to display the anaconda environment and it appends the current anaconda environment before my `PS1` variable. Effectively it now displays my environment twice in my shell.

One trivial workaround for this is to check whether `PS1` is modified by `powerline` before appending the current environment to it. I am happy to file a pull request, but I wanted to check how people feel about this and also if anybody else has any better ideas of how to deal with this.

**Comment by njalerikson** [comment]
Just be aware that #3175 happened so the activate/deactivate scripts have been completely refactored.

I do not know enough about powerline (I just learned about it) to quickly offer a solution however I suggest adding the check for powerline to the `conda ..changeps1` function and that way make no changes to any of the activate/deactivate scripts.
