### ISSUE TITLE
Error when installing R essentials

### ISSUE THREAD

**Issue by lucasverra** [conda/conda#3993]
r-base-3.3.1-0  92% |#################An unexpected error has occurred.##################################################################################################             | Time: 0:02:35 294.26 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.3
         python version : 2.7.10.final.0
       requests version : 2.11.1
       root environment : /Users/lucas/anaconda  (writable)
    default environment : /Users/lucas/anaconda/envs/py2
       envs directories : /Users/lucas/anaconda/envs
          package cache : /Users/lucas/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/lucas/anaconda/envs/py2/bin/conda install -c r r-essentials`

    Traceback (most recent call last):
      File "/Users/lucas/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/lucas/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/lucas/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/lucas/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/lucas/anaconda/pkgs/r-base-3.3.1-0.tar.bz2.part' for writing (("Connection broken: error(60, 'Operation timed out')", error(60, 'Operation timed out'))).

**Comment by mingwandroid** [comment]
This is just a network timeout. I believe newer conda may have increased the timeout time:

`conda update conda`

.. then try again.
