### ISSUE TITLE
Error trying to install python 3.5 from anaconda2

### ISSUE THREAD

**Issue by azharbasit** [conda/conda#3998]
Hello,  I tried to install python 3.5 by using anaconda by using the following command:

    conda create -n python3 python=3.5 anaconda`

and I got the following error:

astroid-1.4.7- 100% |################################| Time: 0:00:06  37.66 kB/s
astAn unexpected error has occurred.############     | Time: 0:03:12  41.79 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/azhar/anaconda2  (writable)
    default environment : /home/azhar/anaconda2
       envs directories : /home/azhar/anaconda2/envs
          package cache : /home/azhar/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/azhar/anaconda2/bin/conda create -n python3 python=3.5 anaconda`

    Traceback (most recent call last):
      File "/home/azhar/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/azhar/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/azhar/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/azhar/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/azhar/anaconda2/pkgs/astropy-1.2.1-np111py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by dhirschfeld** [comment]
The error message says your web connection timed out. Are you on a dodgy connection? If so I'd just try again and jope you get further - unless you know of a specific reason your connection woild be timing out...

**Comment by azharbasit** [comment]
This is also happening over a fast connection.  

Another question, if I try to run the command again I understandably get the error:

CondaValueError: Value error: prefix already exists: /home/azhar/anaconda2/envs/python3 

I am completely new to python and anaconda.  How can I install again without having to download everything again from scratch? 

thanks

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
