### ISSUE TITLE
build environment shebang too long for Linux: "bad interpreter"

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3999]
@janssen commented on [Wed Oct 12 2016](https://github.com/conda/conda-build/issues/1453)

I've got a build.sh which installs a tool, then calls it to install a couple of other things.  But the tool invocation fails:

```
/local/miniconda2/conda-bld/jkivy_1476297899236/work/conda_build.sh: /local/miniconda2/conda-bld/jkivy_1476297899236/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/garden: /local/miniconda2/conda-bld/jkivy_1476297899236/_b_env_placehold_placehold_pl: bad interpreter: No such file or directory
Command failed: /bin/bash -x -e /local/miniconda2/conda-bld/jkivy_1476297899236/work/conda_build.sh
```

If you look at the top of bin/garden, you'll find this shebang:

```
#!/local/miniconda2/conda-bld/jkivy_1476297899236/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
```

Now, that Python exists, and is executable.  And we know that the "bad interpreter" error refers to the shebang being too long.  It's about twice as long as the typical Linux max shebang length of 127.

---

@msarahan commented on [Thu Oct 13 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-253517289)

conda takes care of this on package install by setting up a shortcut of sorts.  If you're installing that script yourself in build.sh, you'll need to do something similar.

https://github.com/conda/conda/blob/master/conda/install.py#L281-L289

---

@janssen commented on [Thu Oct 13 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-253559603)

So the shebangs in the built packages are still bad?  Still seems like kind of a bug; shouldn't something like "#!/usr/bin/env python" be preferable?  I presume the whole chain of _placehold frobs are there to make enough space in DLLs to properly relocate the RPATH, but that line of reasoning doesn't really apply to shebangs.

---

@msarahan commented on [Thu Oct 13 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-253564950)

Shebangs in built packages are bad until conda installs them and applies the function I linked above.

The placehold stuff is indeed there to make enough space in executables and shared libraries.

Are you proposing that conda-build apply some kind of shebang fixing before packaging?  If so, when exactly?  Conda-build cedes control to the user during bld.bat/build.sh execution, and then immediately bundles up files.  Is there a place where some intermediate shebang fix would help?

---

@janssen commented on [Tue Oct 18 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-254662883)

Fair enough.

---

@jjhelmus commented on [Sat Dec 03 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-264679973)

I've run into this issue while trying to rebuild some `conda-forge` packages with long prefixes.  Packages installed by conda-build into the build environment contain long shebang lines which cannot be executed in the environment.  Is there a work around for this?  Should conda-build be setting up shortcuts for these shebang lines?  

Specifically the example I've been debugging is building [`pkg-config`](https://github.com/conda-forge/pkg-config-feedstock).  This recipe installs the `autoconf` package in the build environment which includes the autom4te script.  This is a perl script with a shebang line in the environment of:

```
#! /home/jjhelmus/anaconda/conda-bld/pkg-config-feedstock_1480817967516/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/perl -w
```

When this script is executed via the execution of `aclocal` in by the `build.sh` script it fails due to the long shebang line.

---

@msarahan commented on [Sat Dec 03 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-264682025)

As long as the scripts being run are actually parts of some other package, this should not be happening - things should get fixed by conda when that other package is installed into the build environment.

I think what is going wrong for you, @jjhelmus, is that the shebang line contains an unusual space separator on the left.  I don't think it's syntactically wrong, but it might throw off conda's machinery for shortening the hashbang.

---

@jjhelmus commented on [Sat Dec 03 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-264682952)

I worked out what is happening to shebang lines but I'm not sure if the fault issue is with `conda` or `conda-build`.  

The issue lies in shebang lines which contain a shace between the `!` and the path to the interpreter.  For example:  `#! /usr/bin/perl`. These type of shebang lines are only correctly updated to a "shortcut" prefix if the executable contains the text `python`.  

This is best shown with the following pair of recipes which creates three shebang scripts (foo) and print out the contents of these files in the build environment (bar).

## foo recipe:

meta.yaml
```
package:
  name: foo
  version: 1.0
```

build.sh
```
#!/bin/sh

echo "#! ${PREFIX}/bin/python" > say_hi.py
echo "print('Hello')" >> say_hi.py
cat say_hi.py
cp say_hi.py $PREFIX/bin/

echo "#! ${PREFIX}/bin/perl" > say_hi.pl
echo "print('Hello')" >> say_hi.pl
cat say_hi.pl
cp say_hi.pl $PREFIX/bin/

echo "#! ${PREFIX}/bin/lala" > say_hi.la
echo "print('Hello')" >> say_hi.la
cat say_hi.la
cp say_hi.la $PREFIX/bin/
```

## bar recipe

meta.yaml
```
package:
  name: bar
  version: 1.0

requirements:
  build:
    - foo
  run:
    - foo
```

build.sh

```
#!/bin/sh

ls $PREFIX/bin

cat ${PREFIX}/bin/say_hi.py
cat ${PREFIX}/bin/say_hi.pl
cat ${PREFIX}/bin/say_hi.la

exit 1
```

With conda `4.2.13` and conda-build `2.0.11` building the foo package adds three files to the ./bin/ directory.  Examining the contents of these files shows that there is no space in the shebang line of the file with `python` in the executable path, due to the logic in the `fix_prefix` function in the `post.py` module of conda-build.  The other scripts retain the space in the shebang line.

```
~/.../test/foo$ tar xf ~/anaconda/conda-bld/linux-64/foo-1.0-0.tar.bz2 bin/say_hi.py -O
#!/opt/anaconda1anaconda2anaconda3/bin/python
print('Hello')
~/.../test/foo$ tar xf ~/anaconda/conda-bld/linux-64/foo-1.0-0.tar.bz2 bin/say_hi.pl -O
#! /opt/anaconda1anaconda2anaconda3/bin/perl
print('Hello')
~/.../test/foo$ tar xf ~/anaconda/conda-bld/linux-64/foo-1.0-0.tar.bz2 bin/say_hi.la -O
#! /opt/anaconda1anaconda2anaconda3/bin/lala
print('Hello')
```

Now when these scripts are install into a conda environment with a long prefix as if done in conda build only the shebang line of the python script is rewritten as a shortcut `usr/bin/env` due to the SHEBANG_REGEX in the `install.py` module of `conda.

```
$ conda build .
BUILD START: bar-1.0-0
updating index in: /home/jjhelmus/anaconda/conda-bld/linux-64
updating index in: /home/jjhelmus/anaconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    foo-1.0                    |                0           2 KB  local

The following NEW packages will be INSTALLED:

    foo: 1.0-0 local

Package: bar-1.0-0
source tree in: /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/work
+ source /home/jjhelmus/anaconda/bin/activate /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_eh
+ ls /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placeholn
activate  conda  deactivate  say_hi.la	say_hi.pl  say_hi.py
+ cat /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placehoy
#!/usr/bin/env python
print('Hello')
+ cat /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placehol
#! /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placehold_l
print('Hello')
+ cat /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placehoa
#! /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/_b_env_placehold_placehold_placehold_placehold_a
print('Hello')
+ exit 1
Command failed: /bin/bash -x -e /home/jjhelmus/anaconda/conda-bld/bar_1480823450512/work/conda_build.sh
~/.../test/bar$ 
```

I can see logic in having `conda-build` always rewrite shebang lines without a space and a placeholder or having `conda` rewrite shebang lines which contain a space.  Both could also be implemented. Personally I would prefer the later is that (with a space) is how I write my shebang lines and is how they were [first written by Dennis Ritchie](https://en.wikipedia.org/wiki/Shebang_(Unix)#History) 

Happy to open new issue(s) in either repository on this topic.

---

@jjhelmus commented on [Sat Dec 03 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-264683083)

> I think what is going wrong for you, @jjhelmus, is that the shebang line contains an unusual space separator on the left. I don't think it's syntactically wrong, but it might throw off conda's machinery for shortening the hashbang.

Yes, that is what I found too, and these types of hashbang lines [are allowed](http://unix.stackexchange.com/questions/276751/is-space-allowed-between-and-bin-bash-in-shebang).  The question is should these be allowed in conda package or removed by `conda-build`.

---

@msarahan commented on [Sat Dec 03 2016](https://github.com/conda/conda-build/issues/1453#issuecomment-264683203)

I think all the code related to this is in Conda.  I'm transferring the issue over there.  Please ping me as necessary.

**Comment by jjhelmus** [comment]
I think the current regex for detecting a shebang line:

 ``` Python
SHEBANG_REGEX = re.compile(br'^(#!((?:\\ |[^ \n\r])+)(.*))')
```

Can be updated as follows to match shebang lines with or without whitespace between`#!` and the executable:

``` Python
SHEBANG_REGEX = re.compile(br'^(#!\s*((?:\\ |[^ \n\r])+)(.*))')
```

**Comment by kalefranz** [comment]
I've been reading the history on this.  I'm not sure `\s*` is correct because it includes all white space characters, not just space.  It includes new lines under certain modes.  I also don't know the full history of this regex.

If I was writing it from scratch, I think it would probably be multi-line mode

    ^(#!(?:[ ]*[^\n\r\t]*))$

**Comment by jjhelmus** [comment]
I think allowing for tabs `[ \t]` might also be prudent although my use case would be met if just spaces were supported.  Thanks!

**Comment by kalefranz** [comment]
If you can track down some documentation arguing tabs are valid, I'm all for it. It seems to me right now that they shouldn't be though.

**Comment by jjhelmus** [comment]
[The #! magic](http://www.in-ulm.de/~mascheck/various/shebang/#details)page only mentions spaces not tabs so I'm fine with just spaces.

**Comment by kalefranz** [comment]
BTW, I figured out what the 'backslash backslash space' was.  Ends up, I wrote it.  Imagine that.  Now it's actually both commented and tested.  https://github.com/conda/conda/pull/4008/files#diff-827c3c3f848db24eacfc18b94aead92aR21

**Comment by jjhelmus** [comment]
Thanks for the quick fix @kalefranz!
