### ISSUE TITLE
HELP!! Cannot install pip

### ISSUE THREAD

**Issue by biggyd** [conda/conda#4000]
I was trying to 
conda install pip on my terminal. I use Mac OS X.

At the beginning, everything looks fine:
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/zdong/anaconda:

The following NEW packages will be INSTALLED:

    pip: 9.0.1-py27_0

Proceed ([y]/n)? y

When linking packages, I got
`CondaOSError: OS error: failed to link (src=u'/Users/zdong/anaconda/pkgs/pip-9.0.1-py27_0/lib/python2.7/site-packages/pip/__init__.py', dst='/Users/zdong/anaconda/lib/python2.7/site-packages/pip/__init__.py', type=1, error=OSError(17, 'File exists'))`

Please help me on me the devastated beginner. Super confused.

**Comment by mingwandroid** [comment]
Strange that the file already exists. You can probably add `--force` to your command line to work around this.

**Comment by biggyd** [comment]
@mingwandroid Thanks so much.  I used `conda install pip --force` and got exactly the same error message.

**Comment by mingwandroid** [comment]
Please show output from:

`conda info` and `conda list --show-channel-urls`

**Comment by biggyd** [comment]
Output from `conda info`
`Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 0+unknown
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /Users/zdong/anaconda  (writable)
    default environment : /Users/zdong/anaconda
       envs directories : /Users/zdong/anaconda/envs
          package cache : /Users/zdong/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False`
output from `conda list --show-channel-urls`

> # packages in environment at /Users/zdong/anaconda:
#
_license                  1.1                      py27_1    defaults
_nb_ext_conf              0.2.0                    py27_0    defaults
alabaster                 0.7.8                    py27_0    defaults
anaconda                  custom                   py27_0    defaults
anaconda-client           1.4.0                    py27_0    defaults
anaconda-navigator        1.3.2                    py27_0    defaults
appnope                   0.1.0                    py27_0    defaults
appscript                 1.0.1                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.7                    py27_0    defaults
astropy                   1.2.1               np111py27_0    defaults
attrs                     15.2.0                   py27_0    defaults
babel                     2.3.3                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.4.1                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.0                   py27_0    defaults
boto                      2.40.0                   py27_0    defaults
bottleneck                1.1.0               np111py27_0    defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.6.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.6                      py27_0    defaults
cloudpickle               0.2.1                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.2.13                   py27_0    defaults
conda-build               1.20.0                   py27_0    defaults
conda-env                 2.6.0                         0    defaults
conda-manager             0.3.1                    py27_0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0b2                  py27_1    defaults
constantly                15.1.0                   py27_0    defaults
contextlib2               0.5.3                    py27_0    defaults
cryptography              1.4                      py27_0    defaults
cssselect                 1.0.0                     <pip>
cssselect                 1.0.0                    py27_0    defaults
curl                      7.49.0                        0    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.24                     py27_0    defaults
cytoolz                   0.8.0                    py27_0    defaults
dask                      0.10.0                   py27_0    defaults
datashape                 0.5.2                    py27_0    defaults
decorator                 4.0.10                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docutils                  0.12                     py27_2    defaults
dynd-python               0.7.2                    py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_1    defaults
flask                     0.11.1                   py27_0    defaults
flask-cors                2.1.2                    py27_0    defaults
freetype                  2.5.5                         1    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.1.1                    py27_0    defaults
greenlet                  0.4.10                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
h5py                      2.6.0               np111py27_1    defaults
hdf5                      1.8.16                        0    defaults
heapdict                  1.0.0                    py27_1    defaults
icu                       54.1                          0    defaults
idna                      2.1                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
incremental               16.10.1                  py27_0    defaults
ipaddress                 1.0.16                   py27_0    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.2.0                    py27_1    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py27_1    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.8                      py27_1    defaults
jpeg                      8d                            1    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            4.3.0                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
lazy-object-proxy         1.2.1                    py27_0    defaults
libdynd                   0.7.2                         0    defaults
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.11.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.6.0                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                1.5.3               np111py27_1    defaults
mistune                   0.7.2                    py27_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py27_2    defaults
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.8                    py27_0    defaults
nb_anacondacloud          1.1.0                    py27_0    defaults
nb_conda                  1.1.0                    py27_0    defaults
nb_conda_kernels          1.0.3                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
nbpresent                 3.0.2                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.1                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.2.1                    py27_0    defaults
numba                     0.26.0              np111py27_0    defaults
numexpr                   2.6.0               np111py27_0    defaults
numpy                     1.11.2                   py27_0    defaults
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2h                        1    defaults
pandas                    0.19.1              np111py27_0    defaults
pandoc                    1.15.2                        0    defaults
parsel                    1.0.3                    py27_0    defaults
partd                     0.3.4                    py27_0    defaults
path.py                   8.2.1                    py27_0    defaults
pathlib2                  2.1.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.7.2                    py27_0    defaults
pillow                    3.2.0                    py27_1    defaults
pip                       9.0.1                     <pip>
ply                       3.8                      py27_0    defaults
psutil                    4.3.0                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pyasn1-modules            0.0.8                    py27_0    defaults
pyaudio                   0.2.7                    py27_0    defaults
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.14                     py27_1    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_0    defaults
pydispatcher              2.0.5                    py27_0    defaults
pyflakes                  1.2.3                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pylint                    1.5.4                    py27_1    defaults
pymongo                   3.3.0                    py27_0    defaults
pyopenssl                 0.16.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_0    defaults
pyquery                   1.2.17                    <pip>
pytables                  3.2.2               np111py27_4    defaults
pytest                    2.9.2                    py27_0    defaults
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytz                      2016.4                   py27_0    defaults
pyyaml                    3.11                     py27_4    defaults
pyzmq                     15.2.0                   py27_1    defaults
qt                        5.6.0                         0    defaults
qtawesome                 0.3.2                    py27_0    defaults
qtconsole                 4.2.1                    py27_1    defaults
qtpy                      1.1.2                    py27_0    defaults
queuelib                  1.4.2                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.12.1                   py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.18.1              np111py27_0    defaults
scipy                     0.18.1              np111py27_0    defaults
scrapy                    1.1.1                    py27_0    defaults
service_identity          16.0.0                   py27_0    defaults
setuptools                23.0.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.4.1                    py27_0    defaults
sphinx_rtd_theme          0.1.9                    py27_0    defaults
spyder                    3.0.2                    py27_0    defaults
sqlalchemy                1.0.13                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
sympy                     1.0                      py27_0    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py27_0    defaults
tornado                   4.3                      py27_1    defaults
traitlets                 4.2.1                    py27_0    defaults
twisted                   16.6.0                   py27_0    defaults
ujson                     1.35                     py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
w3lib                     1.16.0                   py27_0    defaults
werkzeug                  0.11.10                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
wrapt                     1.10.8                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.2                    py27_0    defaults
xlwings                   0.7.2                    py27_0    defaults
xlwt                      1.1.2                    py27_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         3    defaults
zope                      1.0                      py27_0    defaults
zope.interface            4.3.2                    py27_0    defaults

**Comment by mingwandroid** [comment]
Somehow it seems pip is already installed, but not from conda. The following line not containing `defaults` indicates this:

`pip 9.0.1`

Did you try to install pip through some other means first?

**Comment by biggyd** [comment]
@mingwandroid I think I installed it through homebrew before...

**Comment by mingwandroid** [comment]
`homebrew` should not write files inside the Anaconda prefix. You can probably get by with just removing `/Users/zdong/anaconda/lib/python2.7/site-packages/pip` via:
`rm -rf /Users/zdong/anaconda/lib/python2.7/site-packages/pip` then re-installing pip via:
`conda install pip`.

**Comment by biggyd** [comment]
@mingwandroid Thanks for being so patient with me...
I tried the rm -rf code but got something like
`rm: /Users/zdong/anaconda/lib/python2.7/site-packages/pip/vcs: Permission denied
rm: /Users/zdong/anaconda/lib/python2.7/site-packages/pip/wheel.py: Permission denied
rm: /Users/zdong/anaconda/lib/python2.7/site-packages/pip/wheel.pyc: Permission denied
rm: /Users/zdong/anaconda/lib/python2.7/site-packages/pip: Directory not empty
`
Before the line 1, I got a lot of other 'Permission denied' ... Just not pasted there to make it complicated... I was trying to search for some solutions, but these didn't work... Sorry if my question looks silly...

**Comment by mingwandroid** [comment]
I think somehow it seems you installed pip as the root user. Try:

`sudo rm -rf /Users/zdong/anaconda/lib/python2.7/site-packages/pip`

**Comment by biggyd** [comment]
@mingwandroid Solved!!! Yay yay yay!!!
Thanks a tribillion!!!!!!! 💯

**Comment by mingwandroid** [comment]
No problem.
