### ISSUE TITLE
Can't install alyvix

### ISSUE THREAD

**Issue by ahmedbhram** [conda/conda#4001]
I wanted to install alyvix, according to the guidelines provided on their site, I installed anaconda, and typed the following in cmd (Admin):
conda install -c https://conda.anaconda.org/alyvix alyvix

I got the following:
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    alyvix-2.3.0               |           py27_1        42.2 MB  alyvix
    conda-4.2.13               |           py27_0         455 KB
    ------------------------------------------------------------
                                           Total:        42.7 MB

The following NEW packages will be INSTALLED:

    alyvix:    2.3.0-py27_1 alyvix
    conda-env: 2.6.0-0

The following packages will be UPDATED:

    conda:     4.2.9-py27_0        --> 4.2.13-py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    pillow:    3.3.1-py27_0        --> 2.7.0-py27_0
    pyqt:      5.6.0-py27_0        --> 4.10.4-py27_1

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.                   | ETA:  0:12:35  48.92 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda2  (writable)
    default environment : C:\Program Files\Anaconda2
       envs directories : C:\Program Files\Anaconda2\envs
          package cache : C:\Program Files\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda2\Scripts\conda-script.py install -c https://conda.a
naconda.org/alyvix alyvix`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", l
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_install.
py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py",
line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not ope
n u'C:\\Program Files\\Anaconda2\\pkgs\\alyvix-2.3.0-py27_1.tar.bz2.part' for wr
iting (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', po
rt=443): Read timed out.).

**Comment by tyler-thetyrant** [comment]
This is a very old version of conda. `conda update conda` will update your conda to version 4.3.16
Please try with the newest version of conda!
