### ISSUE TITLE
Miniconda ImportError: No module named Scipy (Windows)

### ISSUE THREAD

**Issue by santfloyd** [conda/conda#4002]
Im using miniconda to create an environment with Numpy, Scipy, Matplotlib and Pandas libraries, but when i run my code it prompts an importerror: no module scipy but when i check with the conda list command it shows me that the module is installed. 
I dont know why it´s happening. With the conda info -a command it says conda_envs_path: not set, so i proceeded to set it, and CONDA_ENVS_PATH was set to C:\Users\username\Miniconda2\envs, but still when a try to run the code it prompts the following traceback:

from sklearn.decomposition import PCA
file "C:\Python27\python\Lib\site-packages\sklearn/__init__.py", line 57, in <module>
from .base import clone
file "C:\Python27\python\Lib\site-packages\sklearn/base.py, line 10, in <module>
from scipy import sparse
ImportError: No module named scipy

What else i can do? and i don´t know if that has something to do with the path variable. 
PYTHONPATH is not set

**Comment by dhirschfeld** [comment]
The traceback shows paths pointing to your root environment - i.e. the python interpreter your trying to run your code in isn't the one from the environment you created. Did you [`activate`](http://conda.pydata.org/docs/using/envs.html#id3) the newly created environment before running python?

**Comment by santfloyd** [comment]
Yes of course i did. Actually i deleted the first env and created a new one but same result. Why would that happen? A misleading path variable?  How do i know how to edit the path correctly pointing to the created env?
i already set CONDA_ENVS_PATH to C:\Users\username\Miniconda2\envs  but apparently it doesn´t changed anything. the PYTHONPATH is not set, may be the issue is in the path variable...

**Comment by dhirschfeld** [comment]
> Yes of course i did. 

You should paste every single command you entered and the complete output of all of those commands to avoid wasting time - just copy the entire contents of your terminal into the issue and it'll save a lot of  unnecessary back-and-forth.

The answer to your question is likely in what you have omitted above. It's not `CONDA_ENVS_PATH` - in normal usage you should never need to set that and the same goes for the `PYTHONPATH` - don't touch it unless you know what you're doing.

What you *have* posted above states explicitly that you have not activated the environment even if you think you have therefore you're making a mistake in activating the environment or there is a bug in the activation of the environment. 

You've left out the command you used to activate the environment and the result of that command so it's hard to say what went wrong. The moral of the story is paste *all* information whether you think its relevant or not - don't abbreviate or summarise any steps because if you knew what information was relevant or not you would likely have debugged the issue yourself.

**Comment by dhirschfeld** [comment]
One issue on Windows is that conda doesn't support powershell so if you're trying to activate an environment from powershell it will do nothing.

I suspect that's not your problem though - the python interpreter you started was the one in `C:\Python27\python` but it appears your Miniconda install is located in `C:\Users\username\Miniconda2`. If you've previously installed Python and it's on your path before Miniconda it will be chosen in preference to your Miniconda Python. Since the other Python appears to be an All Users install and Miniconda seems to be installed Just for Me then it's likely that is the case. My recommendation would be to uninstall the other Python, alternatively you could manually edit your path to remove the other Python from it.

**Comment by santfloyd** [comment]
You are right. If i want to be helped i must give the most accurate info of my problem. here are the commands and outputs

C:\Users\username>activate snow

(snow) C:\Users\username>cd Documents

(snow) C:\Users\username\Documents>cd fundamentos c++ y python

(snow) C:\Users\username\Documents\fundamentos c++ y python>cd DAT210x-master

(snow) C:\Users\username\Documents\fundamentos c++ y python\DAT210x-master>cd Module4

(snow) C:\Users\username\Documents\fundamentos c++ y python\DAT210x-master\Module4>assigment1week4datascience.py
Traceback (most recent call last):
  File "C:\Users\username\Documents\fundamentos c++ y python\DAT210x-master\Module4\assigment1week4datascience.py", line 5, in <module>
    from sklearn.decomposition import PCA
  File "C:\Python27\python\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\Python27\python\lib\site-packages\sklearn\base.py", line 10, in <module>
    from scipy import sparse
ImportError: No module named scipy

(snow) C:\Users\username\Documents\fundamentos c++ y python\DAT210x-master\Module4>conda info -a
Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\username\Miniconda2  (writable)
    default environment : C:\Users\username\Miniconda2\envs\snow
       envs directories : C:\Users\username\Miniconda2\envs
          package cache : C:\Users\username\Miniconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

# conda environments:
#
snow                  *  C:\Users\username\Miniconda2\envs\snow
snow1                    C:\Users\username\Miniconda2\envs\snow1
snowflakes               C:\Users\username\Miniconda2\envs\snowflakes
work                     C:\Users\username\Miniconda2\envs\work
root                     C:\Users\username\Miniconda2

sys.version: 2.7.12 |Continuum Analytics, Inc.| (defa...
sys.prefix: C:\Users\username\Miniconda2
sys.executable: C:\Users\username\Miniconda2\python.exe
conda location: C:\Users\username\Miniconda2\lib\site-packages\conda
conda-build: None
conda-env: C:\Users\username\Miniconda2\Scripts\conda-env.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: snow
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\username\Miniconda2\Library\bin;C:\Users\username\Miniconda2\envs\snow;C:\Users\username\Miniconda2\envs\snow\Library\mingw-w64\bin;C:\Users\username\Miniconda2\envs\snow\Library\usr\bin;C:\Users\username\Miniconda2\envs\snow\Library\bin;C:\Users\username\Miniconda2\envs\snow\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Python27\python;C:\Python27\python\Scripts;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files\Anaconda2;C:\Program Files\Anaconda2\Scripts;C:\Program Files\Anaconda2\Library\bin;C:\Users\username\Miniconda2\envs;C:\Users\username\Miniconda2\Library\bin;C:\Users\username\Miniconda2\envs;C:\Users\username\Miniconda2\Scripts;C:\Users\username\Miniconda2\Library\bin;C:\Users\username\AppData\Local\Microsoft\WindowsApps
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

(snow) C:\Users\username\Documents\fundamentos c++ y python\DAT210x-master\Module4>conda list -n snowflakes scipy
# packages in environment at C:\Users\username\Miniconda2\envs\snowflakes:
#
scipy                     0.18.1              np111py27_0

**Comment by dhirschfeld** [comment]
As mentioned above you've got multiple Pythons installed and you're using the wrong one.

You're excunting the Python script by just typing its name:
> (snow) ~/DAT210x-master/Module4> assigment1week4datascience.py

When you do that it will use whatever Python you have associated with .py files in you registry. Instead try executing it by passing the script name to the `python.exe` executable - e.g.
```
(snow) ~/DAT210x-master/Module4> python.exe assigment1week4datascience.py
```

That *may* work. If not, I would recommend you uninstall the other Python on your system - having multiple Pythons' installed is a recipe for disaster. If you can't for some reason then try the below:
```
(snow) ~/DAT210x-master/Module4> C:\Users\username\Miniconda2\envs\snow\python.exe assigment1week4datascience.py
```

**Comment by santfloyd** [comment]
I uninstalled the python27 in order to avoid future problems and erased the python27 from the path in advance system options. What i need to do the program executable now? it seems system cant execute the specified program

**Comment by dhirschfeld** [comment]
> it seems system cant execute the specified program

How did you deduce this??

Did you try either of my suggestions above? What was the result of those attempts? (again, copy full input/output from the terminal session)
