### ISSUE TITLE
Current conda install

### ISSUE THREAD

**Issue by EchoLu2016** [conda/conda#4004]
Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda  (writable)
    default environment : C:\Program Files\Anaconda
       envs directories : C:\Program Files\Anaconda\envs
          package cache : C:\Program Files\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda\Scripts\conda-script.py upgrade pandas`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", li
ne 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line
 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main_update.py
", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", l
ine 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not ope
n u'C:\\Program Files\\Anaconda\\pkgs\\pandas-0.19.1-np111py27_0.tar.bz2.part' f
or writing (('Connection broken: error("(10054, \'WSAECONNRESET\')",)', error("(
10054, 'WSAECONNRESET')",))).

**Comment by kalefranz** [comment]
That's a windows socket error.  Are you still having this problem?
