### ISSUE TITLE
conda breaks after using conda

### ISSUE THREAD

**Issue by nosamrer** [conda/conda#4014]
This has happened twice now. I get a fresh install of conda. Things like conda list work, then I use a command from the cloud site to get a netcdf4 package, **conda install -c conda-forge netcdf4=1.2.5**, and right after it is done, conda is no longer recognized as a command. Conda list, conda install, nothing works any more. It seems as if the activate.bat file just disappears (I looked and its not there) after I run that install command, so then I can no longer use an anaconda prompt.

**Comment by kalefranz** [comment]
This was fixed entirely with conda 4.3.  No more conda uninstalling itself!
