### ISSUE TITLE
`dyld: Library not loaded`

### ISSUE THREAD

**Issue by jolespin** [conda/conda#4016]
My ultimate goal is to have an ecosystem of `Bioconductor`, `Anaconda`, and `Beaker-Notebook`.  I primarily use `Python 3` but there are certain packages in `R` that are just way too good to ignore.  

I installed `R 3.3.1` via `conda` in a virtual environment (i.e. `r-conda`).  Before doing this I broke my `R` and then to fix it I completely wiped my computer clean of all the binaries and libraries.  Here is my environment: 

The framework is very sensitive.  I had `R` working through `conda` just moments ago.  Either of these commands just broke it. 

```
$ conda install -c conda-forge cairo=1.12.18 --yes
$ conda install -c r rpy2
```

Now I can't even run `R` in the terminal :(
```
(r-conda) jespinozlt-osx:~ jespinoz$ R
dyld: Library not loaded: @rpath/libicuuc.54.dylib
  Referenced from: /Users/jespinoz/anaconda/envs/r-conda/lib/R/lib/libR.dylib
  Reason: image not found
Trace/BPT trap: 5
```

I've already wiped `R` clean from my computer ~3x but I really want to have it working perfectly through anaconda so I can export the environment and not have to do this again. 

Please help

I have a `Python 2` environment.  I checked where `libicuuc.54.1.dylib` was in my system and it's in: 
`/Users/jespinoz/anaconda/envs/python2/lib` so I deleted my `Python 2` environment and now it's in `/Users/jespinoz/anaconda/pkgs/icu-54.1-0/lib`

**Comment by mingwandroid** [comment]
Unfortunately `conda defaults` and `conda-forge` are not binary compatible so you cannot mix software from each like this. Do you need `cairo` from `conda-forge`?

**Comment by jolespin** [comment]
Thanks for getting back to me!  That's good to know.  No, I have no idea what Cairo does but when I try to use beaker w/ my conda installed R.  I got an error saying something about not finding cairo.  I deleted my entire conda directory and I am reinstalling everything right now.

**Comment by mingwandroid** [comment]
I am working on R/Cairo on macOS at present, so will hopefully have something useable soon.

**Comment by mingwandroid** [comment]
If you use:

`conda install -c rdonnellyr r-base`

.. you should end up with a cairo-enabled version of R 3.3.2.

**Comment by mingwandroid** [comment]
.. if you run into solver issues then I'll figure something out tomorrow.

**Comment by jolespin** [comment]
Should I use `conda install -c rdonnellyr r-base` rather than the default channel?

**Comment by mingwandroid** [comment]
Try to install r-essentials from the r channel as before then install the updated r-base from rdonnellyr, yes.
