### ISSUE TITLE
conda libtcl8.5.so conflicts with system libtcl8.5.so

### ISSUE THREAD

**Issue by gawbul** [conda/conda#4023]
We use environment modules on our HPC to manage package installations. When I have a miniconda environment installed, however, it breaks the modules command, e.g.:

```
$ module avail
init.c(556):ERROR:161: Cannot initialize TCL
warn UNKNOWN command:  test 0 = 1
```

When I look at the linked library information I get the following:

```
ldd /apps/Modules/default/bin/modulecmd.wrapped
	linux-vdso.so.1 =>  (0x00007fffb0bdd000)
	libtcl8.5.so => /home/gawbul/miniconda2/lib/libtcl8.5.so (0x00007fba595fb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000383f800000)
	libm.so.6 => /lib64/libm.so.6 (0x000000383f400000)
	libc.so.6 => /lib64/libc.so.6 (0x000000383f000000)
	/lib64/ld-linux-x86-64.so.2 (0x000000383ec00000)
```

However, when I aren't in the conda environment I get this:
```
ldd /apps/Modules/default/bin/modulecmd.wrapped
	linux-vdso.so.1 =>  (0x00007ffc9d9e8000)
	libtcl8.5.so => /usr/lib64/libtcl8.5.so (0x0000003840400000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000383f800000)
	libm.so.6 => /lib64/libm.so.6 (0x000000383f400000)
	libc.so.6 => /lib64/libc.so.6 (0x000000383f000000)
	/lib64/ld-linux-x86-64.so.2 (0x000000383ec00000)
```

If I do `LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH ldd /apps/Modules/default/bin/modulecmd.wrapped` it fixes it, but I don't know what impact this will have on any of the conda applications currently.

Obviously `libtcl8.5.so` is conflicting.

**Comment by gawbul** [comment]
Would symlinking `/home/gawbul/miniconda2/lib/libtcl8.5.so` to `/usr/lib64/libtcl8.5.so` cause any major issues?

**Comment by mingwandroid** [comment]
> Would symlinking /home/gawbul/miniconda2/lib/libtcl8.5.so to /usr/lib64/libtcl8.5.so cause any major issues?

Probably, but maybe not.

Can you show the output of `echo $LD_LIBRARY_PATH` in each case? Also the output from:

`readelf -d apps/Modules/default/bin/modulecmd.wrapped`
