### ISSUE TITLE
allow_other_channels False in the system .condarc doesn't stop install

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#4026]
conda version 4.2.13
I added allow_other_channels: False to my system .condarc then I added a new channel in my ~/.condarc file and I could successfully install a package from the channel in my ~/.condarc.

The channel in my ~/.condarc is also used when doing conda search but it probably shouldn't be.

The feature to control the channels from the system .condarc file is a critical feature for enterprises to control conda use.

Please fix this ASAP!

**Comment by nehaljwani** [comment]
Seems like this feature was removed from conda in https://github.com/conda/conda/commit/12a042d627ca110d5d3395395d9ec9574619b353
@kalefranz Could you please share the reason behind this removal?

**Comment by kalefranz** [comment]
Tracking via #5158.

**Comment by qris** [comment]
This issue is closed, but the `allow_other_channels` feature still doesn't work? #5158 addressed `override_channels`, not this bug. Please could we reopen this?
