### ISSUE TITLE
Discrepancy in conda Sphinx version and reported Sphinx version

### ISSUE THREAD

**Issue by rlee287** [conda/conda#4035]
The output of `conda list` contains the following line:

```
sphinx                    1.5                      py35_0  
```

However, 

```
> sphinx-build --version
Sphinx (sphinx-build) 1.3.1
```

The output of `conda info --all` and the complete output of `conda list` is attached below:
[packages.txt](https://github.com/conda/conda/files/645298/packages.txt)
[conda info.txt](https://github.com/conda/conda/files/645299/conda.info.txt)

**Comment by kalefranz** [comment]
You probably have multiple versions of sphinx installed on your system, and the first on PATH isn't the same as your activate conda environment.

    which -a sphinx-build

might help.  If not, check the python site-packages directory.  You could have a situation where conda and pip are fighting over what's installed.
