### ISSUE TITLE
conda install jupyter

### ISSUE THREAD

**Issue by csempesz** [conda/conda#4037]
Started my Python bootcamp training on Udemy and installed Anaconda for Windows 7 (64 bit) successfully. But when I (following the training material) try to install jupyter via: conda install jupyter I receive errors: Below I copied the content of the screen. 

C:\Tutorials\Python>conda install jupyter
Fetching package metadata ...SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
..SSL verification error: [Errno 2] No such file or directory
.SSL verification error: [Errno 2] No such file or directory
...
Solving package specifications: ..........

Package plan for installation in environment C:\Users\ccsenter\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

Proceed ([y]/n)? y

Fetching packages ...
**Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2**
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\ccsenter\Anaconda3  (writable)
    default environment : C:\Users\ccsenter\Anaconda3
       envs directories : C:\Users\ccsenter\Anaconda3\envs
          package cache : C:\Users\ccsenter\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\ccsenter\Anaconda3\Scripts\conda-script.py install jupyter`

    Traceback (most recent call last):
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
    FileNotFoundError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Users\ccsenter\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 297, in ssl_wrap_socket
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

**Comment by csempesz** [comment]
Same thing happens if I use update instead of install...

**Comment by kalefranz** [comment]
You have a problem with requests and your certificate bundle somewhere.  Sometimes the easiest solution is to reinstall miniconda when certain files get corrupted like this.
