### ISSUE TITLE
Conda is pulling the wrong `vc` when a package is unavailable in a preferred channel

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda#4040]
@msarahan maybe you can help us here. As you can see from this log:

https://ci.appveyor.com/project/astrofrog/debug-conda-forge-appveyor/build/1.0.17#L82

even though that project is Python 2.7 and should be using `vc 9` conda is pulling a `qt` compiled with `vc 10`. Note that the project has `conda-forge` and `defaults` channels in that order and `conda-forge` does not have a `qt vc 9` version for that Arch. So conda should be pulling a `qt vc 9` from `defaults` instead.

If the channel order is resversed the right stack is downloaded.

IMO channel preference should not swicht `vc`s. I've seen a smiliar behavior when channel preference broke a package pinning in order to satisfy the channel order. Maybe `pinning`, like the `vc`s there, should preceed the channel order in the resolution in order to ensure a stable mix of packages.

cc @astrofrog

**Comment by kalefranz** [comment]
I think we've gotten all the vc stuff worked out now.
