### ISSUE TITLE
 CondaRuntimeError: Runtime error: RuntimeError: Runtime error:

### ISSUE THREAD

**Issue by 201528014227051** [conda/conda#4048]
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/user3/anaconda2  (writable)
    default environment : /home/user3/anaconda2/envs/tensorflow
       envs directories : /home/user3/anaconda2/envs
          package cache : /home/user3/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/user3/.condarc
           offline mode : False

`$ /home/user3/anaconda2/envs/tensorflow/bin/conda install tensorflow`

    Traceback (most recent call last):
      File "/home/user3/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/user3/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/user3/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/user3/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/user3/anaconda2/pkgs/tensorflow-0.11.0-py27_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by wzm2256** [comment]
I have the same issue.

**Comment by rachelmsi** [comment]
I have the same problem, someone know how to resolve this?

**Comment by TiagoSousaNeves** [comment]
Me too!

**Comment by kalefranz** [comment]
This is an intermittent HTTP timeout error.  Just retry.  `conda update conda` will also help
