### ISSUE TITLE
GDAL needs to have GDAL_DATA environment variable set

### ISSUE THREAD

**Issue by mwtoews** [conda/conda#4050]
I'm not sure if it is the responsibility for an Anaconda package to set up environment variables, or not, but here is an issue that I'm able to replicated on Windows and Linux (here with gdal 2.1.0-py27_0). GDAL needs to have a [`GDAL_DATA` environment variable](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DATA) to point to `share/gdal` (installed by Anaconda) to load spatial projection data, used by C++ and Python components of GDAL. Without it, things don't work as expected, i.e. from a shell:
```bash
$ echo $GDAL_DATA

$ epsg_tr.py 4326
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
Unable to lookup 2193, either not a valid EPSG
code, or it the EPSG CSV files are not accessible.
$ gdalsrsinfo EPSG:4326
ERROR 1: ERROR - failed to load SRS definition from EPSG:4326
```

The environment variable can be set by the user to make the above tests work:
```bash
export GDAL_DATA=/path/to/anaconda/share/gdal
```
Is there a fix that can come from Anaconda, or should this be documented to the user somehow?

**Comment by groutr** [comment]
When you activate an environment with GDAL installed, GDLA_DATA should get set by the activate.sh script
https://github.com/conda/conda-recipes/blob/master/gdal/posix/activate.sh

When deactivating the environment, it gets removed.

**Comment by mwtoews** [comment]
I'm not sure how to activate this environment, and I don't see that script under the `andaconda` install (I only see `./pkgs/conda-4.2.9-py27_0/bin/activate` and `./bin/activate`).

**Comment by groutr** [comment]
@mwtoews http://conda.pydata.org/docs/using/envs.html#change-environments-activate-deactivate

**Comment by mwtoews** [comment]
@groutr thanks, this method seems to work. For example:
```
# create environment once
conda create --name snowflakes gdal

# use it
source activate snowflakes
# do work, e.g.:
epsg_tr.py 4326
source deactivate snowflakes
```
and I can see that `$GDAL_DATA` is properly set/unset in the process. I'm not sure if there is a better way to document this, but it seems to work as expected. Thanks!

**Comment by kmu2000** [comment]
C:\Users\kriti>if not defined GDAL_DATA (
set GDAL_DATA="C:\ProgramData\Anaconda2\etc\conda\activate.d\\..\..\..\Library\share\gdal"
 set _CONDA_SET_GDAL_DATA=1
)

I am getting a message like this when I am opening an Anaconda prompt. what is the meaning of this? Any suggestion/help would be highly appreciated

**Comment by msarahan** [comment]
You are seeing output from conda setting environment variables for you.  It is safe to ignore.  Setting those variables is critical to GDAL working properly.
