### ISSUE TITLE
Can't install `pyqt` with conda install

### ISSUE THREAD

**Issue by Elizaveta239** [conda/conda#4052]
Hello! After the latest update of pyqt5.6.0 package (updated 2016-12-12) I can't install it with `conda install` command on Windows. I always get the error with the following message:

ERROR: placeholder 'C:/Users/ray/qtb-2.7-64/_b_env' too short in: qt-5.6.2-vc9_0

Could you please help me to resolve the issue?

**Comment by mingwandroid** [comment]
This was a bug in conda.

`conda update conda` should see you right.

**Comment by Elizaveta239** [comment]
@mingwandroid Thank you for the answer! But I'm using the latest version of Miniconda. Should I report this problem to them?

**Comment by mingwandroid** [comment]
This is one of the places to report problems regarding `Miniconda`. The terms are confusing here, by `conda` I do not mean `The Miniconda Distribution`, I mean the `conda package manager`.

Please issue `conda update conda` and try again.

**Comment by Elizaveta239** [comment]
It helped, thank you!

**Comment by groutr** [comment]
@mingwandroid what was the bug exactly?

**Comment by mingwandroid** [comment]
There was a bug in conda. It reported that error about binary replacement prefix length when they do not happen on Windows anyway.
