### ISSUE TITLE
[ENH] conda info to report LD_LIBRARY_PATH or DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4055]
We need to try and help people help themselves and to head off common causes of Anaconda/Conda failure, such as LD_LIBRARY_PATH and DYLD_LIBRARY_PATH.  Longer term a `conda debug` command might be useful (similarly a GUI version in Navigator), but in the short term it would probably go a long way to helping us if we reported `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` with the output of `conda info`.

**Comment by mingwandroid** [comment]
FYI `DYLD_*` does nothing in most scenarios since SIP, just a warning .. we cannot and must use it in our recipes.

**Comment by kalefranz** [comment]
This is included in `conda info -a`.
