### ISSUE TITLE
Cyclic dependencies not reported as a warning and things get installed in the wrong order.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#4067]
The following exception gets raised but I guess it's not getting caught, or at least it's not getting reported ..

```
    if len(data) != 0:
        msg = 'Cyclic dependencies exist among these items: {}'
        raise CondaValueError(msg.format(' -> '.join(repr(x) for x in data.keys())))
```

This is a very important warning that identifies that the package(s) need to be fixed.

**Comment by kalefranz** [comment]
Is this in 4.3?  Or 4.2 that carried into 4.3 probably?

**Comment by mingwandroid** [comment]
I saw it in 4.2, not sure if it carried over.

**Comment by kalefranz** [comment]
resolved with https://github.com/conda/conda/pull/4109

**Comment by kalefranz** [comment]
#4109 might not be the right fix according to the test failures.

> The following exception gets raised but I guess it's not getting caught, or at least it's not getting reported

In what context are you referring?  Which commands?  The error *is* being raised, but then it must be swallowed somewhere too.  Only way I can trace it is to know which commands you're experiencing this with.

**Comment by mingwandroid** [comment]
Any `conda install pkg-leading-to-cycles` will cause it.

**Comment by kalefranz** [comment]
Do you know of a specific example that I can test manually?  I've looked through the call stack for `conda install` and I couldn't find any place we were swallowing `ValueError` exceptions.  It wouldn't be hard to miss though.

**Comment by mingwandroid** [comment]
On Windows, the old MSYS2 packages would exhibit this.

`conda install m2w64-ca-certificates`

I've since fixed them, so I would just make 2 mutually dependent recipes.

**Comment by kalefranz** [comment]
Closing, following in-person discussion.
