### ISSUE TITLE
create fail

### ISSUE THREAD

**Issue by dugloon** [conda/conda#4068]
C:\Aptina>conda env create -f quarryEnv.yml
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: Fetching packages ...
python-3.4.5-0 100% |###############################| Time: 0:00:20   1.16 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:10   1.30 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda_env\cli\main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Anaconda2\lib\site-packages\conda_env\installers\pip.py", line 8, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

-----------
name: efftrack
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- python=3.4.5=0
- pywin32=220=py34_1
- pip:
  - aiodns==1.1.1
  - aiohttp==1.1.1
  - aiohttp-jinja2==0.12.0
  - aiopg==0.13.0
  - async-timeout==1.1.0
  - cchardet==1.1.1
  - chardet==2.3.0
  - jinja2==2.8
  - markupsafe==0.23
  - multidict==2.1.2
  - psycopg2==2.6.2
  - py2exe==0.9.2.0
  - pycares==2.1.1
  - pyyaml==3.12
  - yarl==0.5.3

**Comment by kalefranz** [comment]
outdated.
