### ISSUE TITLE
Conda left in inoperable state after failed install on Windows

### ISSUE THREAD

**Issue by synapticarbors** [conda/conda#407]
I was attempting to install some software via conda on a machine that I did not realize that I was lacking admin privileges for. After conda failed with a permission issue, it appears to have left itself in an inoperable state, where the conda app is gone:

```
XXX>conda search -h
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

conda.bat and conda-script.py are both missing from C:\Anaconda\Scripts. 

When I look in C:\Anaconda\pkgs, I can see that the package I was trying to install (setuptools) and conda are both in some intermediate state in the install:

```
 Directory of C:\Anaconda\pkgs

11/25/2013  09:52 AM    <DIR>          ..
11/25/2013  09:52 AM    <DIR>          .
11/25/2013  09:52 AM    <DIR>          setuptools-1.4-py27_0
11/25/2013  09:52 AM    <DIR>          conda-2.2.1-py27_0
10/21/2013  11:57 PM    <DIR>          ipython-1.1.0-py27_0
10/21/2013  11:57 PM    <DIR>          conda-2.0.0-py27_0
10/21/2013  11:57 PM    <DIR>          cache
11/25/2013  09:52 AM           848,473 setuptools-1.4-py27_0.tar.bz2
11/25/2013  09:52 AM           131,679 conda-2.2.1-py27_0.tar.bz2
```

It doesn't seem like I should be able to wreck the conda install like this as a user without admin privileges, and that conda, when encountering a situation where I didn't have sufficient write permissions to complete the install, should have rolled back things to the state pre `conda install setuptools`. When I ran this command I was prompted whether I wanted to upgrade conda as well as part of the install, which is why conda was touched in the first place. 

I'm using Windows Server 2008 with Anaconda 1.7 (with whatever Conda version was associated with the distro). 

This issue was originally reported on the Conda mailing list: 
https://groups.google.com/a/continuum.io/forum/#!topic/conda/YN3eoiJM4es

**Comment by kalefranz** [comment]
fixed with transactions in conda 4.3
