### ISSUE TITLE
Specifications in conflict after creating frozen (exported) environment from file

### ISSUE THREAD

**Issue by olegsinyavskiy** [conda/conda#4078]
Hello,

`pip freeze` command creates a requirements file specifying all versions of all packages that can be used later with `pip install -r`. This usually works for years on my test servers without any intervention.

I thought the similar is expected from conda with its `export` and `conda create --file` workflow. 

However, recently I got `The following specifications were found to be in conflict` error after few months of successful creations of environment on a test server.

I assume that conda export and create haven't specified everything or there must be some kind of untracked changes inside packages that happened without bumping versions. I would expect this might happen with some custom not-well-maintained packages, but in my case the error happened with quite well known packages:

```
The following specifications were found to be in conflict:
  - boost 1.60.0 py27_0
  - pyqt 4.11.4 py27_4 -> qt >=4.8.6,<5.0
  - qt 4.8.7 4
```

How can I fix this but mainly how can I avoid such issues in the future?

**Comment by olegsinyavskiy** [comment]
Here is the output of conda info for those conflicting packages. I'm not really sure how to deduce what is exactly in conflict..

``` 
conda info pyqt=4.11.4=py27_4 0s  
Fetching package metadata: ....

pyqt 4.11.4 py27_4
------------------
file name   : pyqt-4.11.4-py27_4.tar.bz2
name        : pyqt
version     : 4.11.4
build number: 4
build string: py27_4
channel     : defaults
size        : 3.3 MB
date        : 2016-07-14
license     : Commercial, GPLv2, GPLv3
license_family: GPL3
md5         : 89862eae10583bb2951f7531180de2de
installed environments:
dependencies:
    python 2.7*
    qt >=4.8.6,<5.0
    sip 4.18

  conda info qt=4.8.7=4 0s  
Fetching package metadata: ....

qt 4.8.7 4
----------
file name   : qt-4.8.7-4.tar.bz2
name        : qt
version     : 4.8.7
build number: 4
build string: 4
channel     : defaults
size        : 32.7 MB
date        : 2016-07-12
license     : LGPLv3
license_family: LGPL
md5         : f598c18cd6457ce2fcf552021f7126a1
installed environments:
dependencies:
    fontconfig >=2.11.1
    freetype >=2.5.2
    libpng 1.6*
    openssl 1.0.2*
    pango
    zlib 1.2.*

  conda info boost=1.60.0=py27_0 0s  
Fetching package metadata: ....

boost 1.60.0 py27_0
-------------------
file name   : boost-1.60.0-py27_0.tar.bz2
name        : boost
version     : 1.60.0
build number: 0
build string: py27_0
channel     : defaults
size        : 10.1 MB
date        : 2016-03-08
license     : Boost license
license_family: Other
md5         : abef931943c9161a1296a2d31a2e030c
installed environments:
dependencies:
    icu
    python 2.7*
    zlib
```

**Comment by kalefranz** [comment]
Were you trying to install the requirements file in a fresh, clean environment?  Or one that was already populated with packages?  If the latter, then it's easy to get conflicts like these.

**Comment by olegsinyavskiy** [comment]
Its a travis test node which is spawned fresh every time.

**Comment by kalefranz** [comment]
Were you able to resolve your issue?

**Comment by olegsinyavskiy** [comment]
@kalefranz , yes, I stopped using conda:) I had to switch back to pip, apt and other stable tools because I couldn't afford spontaneous crashes in the production code, that was stable for months.
