### ISSUE TITLE
Unexpected Error occurs during update process (Build 1.14.1)

### ISSUE THREAD

**Issue by BlueTower** [conda/conda#4082]
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 3.4.4.final.0
       requests version : 2.9.1
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

```
Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 120, in main
    from conda.cli.find_commands import find_commands
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 130, in args_func
    
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 64, in execute
    def execute(args, parser):
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 407, in install
    try:
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 599, in execute_actions
    to_link.append(subst[:-8])
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 1060, in link
    for path in sorted(dst_dirs2, key=len, reverse=True):
  File "//anaconda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '//anaconda/lib/python3.4/site-packages/pip/_vendor/_markerlib'
```

# Full log up to this point (warning, lots of text)

$ conda update --prefix //anaconda anaconda
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment //anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blz-removed                |                0          356 B
    conda-env-2.6.0            |                0          601 B
    dynd-python-removed        |                0          297 B
    mkl-11.3.1                 |                0        99.1 MB
    openssl-1.0.2g             |                0         3.0 MB
    sqlite-3.9.2               |                0         1.2 MB
    xz-5.0.5                   |                1         173 KB
    zeromq-4.1.3               |                0         577 KB
    zlib-1.2.8                 |                0          83 KB
    curl-7.45.0                |                0         371 KB
    freetype-2.5.5             |                0         732 KB
    hdf5-1.8.15.1              |                2         1.6 MB
    libtiff-4.0.6              |                1         736 KB
    python-3.4.4               |                0        11.4 MB
    alabaster-0.7.7            |           py34_0          15 KB
    appnope-0.1.0              |           py34_0           4 KB
    backports_abc-0.4          |           py34_0           5 KB
    beautifulsoup4-4.4.1       |           py34_0         122 KB
    boto-2.39.0                |           py34_0         1.4 MB
    cloudpickle-0.1.1          |           py34_0          16 KB
    colorama-0.3.7             |           py34_0          20 KB
    cython-0.23.4              |           py34_1         2.2 MB
    cytoolz-0.7.5              |           py34_0         244 KB
    decorator-4.0.9            |           py34_0           7 KB
    dill-0.2.4                 |           py34_0          73 KB
    et_xmlfile-1.0.1           |           py34_0          15 KB
    greenlet-0.4.9             |           py34_0          13 KB
    heapdict-1.0.0             |           py34_0           4 KB
    jdcal-1.2                  |           py34_0           7 KB
    jedi-0.9.0                 |           py34_0         196 KB
    llvmlite-0.9.0             |           py34_0         5.9 MB
    locket-0.2.0               |           py34_0           5 KB
    mistune-0.7.2              |           py34_1         155 KB
    mkl-service-1.1.2          |           py34_0           6 KB
    mpmath-0.19                |           py34_0         901 KB
    multipledispatch-0.4.8     |           py34_0          12 KB
    nltk-3.2                   |           py34_0         1.9 MB
    numpy-1.10.4               |           py34_0         2.6 MB
    path.py-8.1.2              |           py34_1          46 KB
    pep8-1.7.0                 |           py34_0          27 KB
    pillow-3.1.1               |           py34_0         491 KB
    ply-3.8                    |           py34_0          72 KB
    psutil-4.1.0               |           py34_1         208 KB
    ptyprocess-0.5             |           py34_0          19 KB
    py-1.4.31                  |           py34_0         127 KB
    pyasn1-0.1.9               |           py34_0          57 KB
    pycosat-0.6.1              |           py34_0          53 KB
    pycurl-7.19.5.3            |           py34_0          43 KB
    pyflakes-1.1.0             |           py34_0          69 KB
    pygments-2.1.1             |           py34_0         1.2 MB
    pytz-2016.2                |           py34_0         175 KB
    pyyaml-3.11                |           py34_1         144 KB
    pyzmq-15.2.0               |           py34_0         658 KB
    qt-4.8.7                   |                1        39.0 MB
    qtpy-1.0                   |           py34_0          17 KB
    requests-2.9.1             |           py34_0         648 KB
    setuptools-20.3            |           py34_0         459 KB
    simplegeneric-0.8.1        |           py34_0           6 KB
    sip-4.16.9                 |           py34_0         210 KB
    six-1.10.0                 |           py34_0          17 KB
    snowballstemmer-1.2.1      |           py34_0          79 KB
    sphinx_rtd_theme-0.1.9     |           py34_0         628 KB
    sqlalchemy-1.0.12          |           py34_0         1.4 MB
    toolz-0.7.4                |           py34_0          53 KB
    unicodecsv-0.14.1          |           py34_0          21 KB
    werkzeug-0.11.4            |           py34_0         422 KB
    xlrd-0.9.4                 |           py34_0         182 KB
    xlsxwriter-0.8.4           |           py34_0         189 KB
    abstract-rendering-0.5.1   |      np110py34_0          43 KB
    argcomplete-1.0.0          |           py34_1          33 KB
    astropy-1.1.2              |      np110py34_0         6.1 MB
    babel-2.2.0                |           py34_0         4.3 MB
    bcolz-1.0.0                |           py34_0         382 KB
    bottleneck-1.0.0           |      np110py34_0         153 KB
    cffi-1.5.2                 |           py34_0         191 KB
    chest-0.2.3                |           py34_0          10 KB
    clyent-1.2.1               |           py34_0          13 KB
    conda-4.2.13               |           py34_0         389 KB
    cycler-0.10.0              |           py34_0          11 KB
    gevent-1.1.0               |           py34_0         470 KB
    h5py-2.5.0                 |      np110py34_4         685 KB
    jinja2-2.8                 |           py34_0         301 KB
    lxml-3.6.0                 |           py34_0         845 KB
    networkx-1.11              |           py34_0         1.1 MB
    numba-0.24.0               |      np110py34_0         1.6 MB
    numexpr-2.5                |      np110py34_0         111 KB
    openpyxl-2.3.2             |           py34_0         254 KB
    patsy-0.4.0                |      np110py34_0         368 KB
    pexpect-4.0.1              |           py34_0          66 KB
    pickleshare-0.5            |           py34_0           8 KB
    pip-8.1.1                  |           py34_1         1.6 MB
    pyqt-4.11.4                |           py34_1         4.0 MB
    pytest-2.8.5               |           py34_0         226 KB
    python-dateutil-2.5.1      |           py34_0         237 KB
    qtawesome-0.3.2            |           py34_0         153 KB
    scipy-0.17.0               |      np110py34_0        11.8 MB
    singledispatch-3.4.0.3     |           py34_0          13 KB
    sympy-1.0                  |           py34_0         5.9 MB
    tornado-4.3                |           py34_0         578 KB
    traitlets-4.2.1            |           py34_0         113 KB
    xlwings-0.7.0              |           py34_0         383 KB
    anaconda-client-1.4.0      |           py34_0         102 KB
    bokeh-0.11.1               |           py34_0         3.2 MB
    cryptography-1.3           |           py34_0         406 KB
    datashape-0.5.1            |           py34_0          92 KB
    flask-0.10.1               |           py34_1         135 KB
    ipython-4.1.2              |           py34_1         991 KB
    jupyter_core-4.1.0         |           py34_0          51 KB
    matplotlib-1.5.1           |      np110py34_0         6.1 MB
    pandas-0.18.0              |      np110py34_0         5.8 MB
    pytables-3.2.2             |      np110py34_1         1.6 MB
    scikit-learn-0.17.1        |      np110py34_0         3.6 MB
    sockjs-tornado-1.0.1       |           py34_0          32 KB
    sphinx-1.3.5               |           py34_0         1.2 MB
    terminado-0.5              |           py34_1          18 KB
    conda-manager-0.3.1        |           py34_0         136 KB
    flask-cors-2.1.2           |           py34_0          16 KB
    jupyter_client-4.2.2       |           py34_0          99 KB
    odo-0.4.2                  |           py34_0         176 KB
    partd-0.3.2                |           py34_1          24 KB
    pyopenssl-0.15.1           |           py34_2         161 KB
    scikit-image-0.12.3        |      np110py34_0        17.8 MB
    statsmodels-0.6.1          |      np110py34_0         4.8 MB
    blaze-core-0.9.0           |           py34_0         542 KB
    dask-0.8.1                 |           py34_0         296 KB
    ipykernel-4.3.1            |           py34_0         120 KB
    nbconvert-4.1.0            |           py34_0         275 KB
    blaze-0.9.1                |           py34_0         542 KB
    jupyter_console-4.1.1      |           py34_0          25 KB
    notebook-4.1.0             |           py34_2         4.4 MB
    qtconsole-4.2.0            |           py34_0         163 KB
    ipython-notebook-4.0.4     |           py34_0           5 KB
    ipython-qtconsole-4.0.1    |           py34_0           4 KB
    spyder-2.3.8               |           py34_1         2.0 MB
    jupyter-1.0.0              |           py34_2           2 KB
    spyder-app-2.3.8           |           py34_0           7 KB
    anaconda-4.0.0             |      np110py34_0           5 KB
    ------------------------------------------------------------
                                           Total:       278.5 MB

The following NEW packages will be INSTALLED:

    anaconda-client:    1.4.0-py34_0               
    appnope:            0.1.0-py34_0               
    backports_abc:      0.4-py34_0                 
    beautifulsoup4:     4.4.1-py34_0               
    blaze:              0.9.1-py34_0               
    chest:              0.2.3-py34_0               
    cloudpickle:        0.1.1-py34_0               
    conda-manager:      0.3.1-py34_0               
    cycler:             0.10.0-py34_0              
    dask:               0.8.1-py34_0               
    dill:               0.2.4-py34_0               
    et_xmlfile:         1.0.1-py34_0               
    flask-cors:         2.1.2-py34_0               
    gevent:             1.1.0-py34_0               
    heapdict:           1.0.0-py34_0               
    jbig:               2.1-0                      
    locket:             0.2.0-py34_0               
    mkl:                11.3.1-0                   
    mkl-service:        1.1.2-py34_0               
    mpmath:             0.19-py34_0                
    partd:              0.3.2-py34_1               
    path.py:            8.1.2-py34_1               
    pexpect:            4.0.1-py34_0               
    pickleshare:        0.5-py34_0                 
    qtawesome:          0.3.2-py34_0               
    qtpy:               1.0-py34_0                 
    simplegeneric:      0.8.1-py34_0               
    singledispatch:     3.4.0.3-py34_0             
    unicodecsv:         0.14.1-py34_0              

The following packages will be UPDATED:

    alabaster:          0.7.3-py34_0      <unknown> --> 0.7.7-py34_0      
    anaconda:           custom-py34_0               --> 4.0.0-np110py34_0 
    argcomplete:        0.8.9-py34_0      <unknown> --> 1.0.0-py34_1      
    astropy:            1.0.3-np19py34_0  <unknown> --> 1.1.2-np110py34_0 
    babel:              1.3-py34_0        <unknown> --> 2.2.0-py34_0      
    bcolz:              0.9.0-np19py34_0  <unknown> --> 1.0.0-py34_0      
    blaze-core:         0.8.0-np19py34_0  <unknown> --> 0.9.0-py34_0      
    bokeh:              0.9.0-np19py34_0  <unknown> --> 0.11.1-py34_0     
    boto:               2.38.0-py34_0     <unknown> --> 2.39.0-py34_0     
    cffi:               1.1.0-py34_0      <unknown> --> 1.5.2-py34_0      
    clyent:             0.3.4-py34_0      <unknown> --> 1.2.1-py34_0      
    colorama:           0.3.3-py34_0      <unknown> --> 0.3.7-py34_0      
    conda:              4.1.11-py34_0               --> 4.2.13-py34_0     
    conda-env:          2.5.2-py34_0                --> 2.6.0-0           
    cryptography:       0.9.1-py34_0      <unknown> --> 1.3-py34_0        
    curl:               7.43.0-0          <unknown> --> 7.45.0-0          
    cython:             0.22.1-py34_0     <unknown> --> 0.23.4-py34_1     
    cytoolz:            0.7.3-py34_0      <unknown> --> 0.7.5-py34_0      
    datashape:          0.4.5-np19py34_0  <unknown> --> 0.5.1-py34_0      
    decorator:          3.4.2-py34_0      <unknown> --> 4.0.9-py34_0      
    freetype:           2.5.2-2           <unknown> --> 2.5.5-0           
    greenlet:           0.4.7-py34_0      <unknown> --> 0.4.9-py34_0      
    h5py:               2.5.0-np19py34_3  <unknown> --> 2.5.0-np110py34_4 
    hdf5:               1.8.15.1-1        <unknown> --> 1.8.15.1-2        
    ipykernel:          4.0.3-py34_0                --> 4.3.1-py34_0      
    ipython:            3.2.0-py34_0      <unknown> --> 4.1.2-py34_1      
    ipython-notebook:   3.2.0-py34_0      <unknown> --> 4.0.4-py34_0      
    ipython-qtconsole:  3.2.0-py34_0      <unknown> --> 4.0.1-py34_0      
    jdcal:              1.0-py34_0        <unknown> --> 1.2-py34_0        
    jedi:               0.8.1-py34_0      <unknown> --> 0.9.0-py34_0      
    libtiff:            4.0.2-1           <unknown> --> 4.0.6-1           
    llvmlite:           0.5.0-py34_0      <unknown> --> 0.9.0-py34_0      
    lxml:               3.4.4-py34_0      <unknown> --> 3.6.0-py34_0      
    matplotlib:         1.4.3-np19py34_2  <unknown> --> 1.5.1-np110py34_0 
    mistune:            0.5.1-py34_1      <unknown> --> 0.7.2-py34_1      
    multipledispatch:   0.4.7-py34_0      <unknown> --> 0.4.8-py34_0      
    networkx:           1.9.1-py34_0      <unknown> --> 1.11-py34_0       
    nltk:               3.0.3-np19py34_0  <unknown> --> 3.2-py34_0        
    numba:              0.19.1-np19py34_0 <unknown> --> 0.24.0-np110py34_0
    numexpr:            2.4.3-np19py34_0  <unknown> --> 2.5-np110py34_0   
    numpy:              1.9.2-py34_0      <unknown> --> 1.10.4-py34_0     
    odo:                0.3.2-np19py34_0  <unknown> --> 0.4.2-py34_0      
    openpyxl:           1.8.5-py34_0      <unknown> --> 2.3.2-py34_0      
    pandas:             0.16.2-np19py34_0 <unknown> --> 0.18.0-np110py34_0
    patsy:              0.3.0-np19py34_0  <unknown> --> 0.4.0-np110py34_0 
    pep8:               1.6.2-py34_0      <unknown> --> 1.7.0-py34_0      
    pillow:             2.8.2-py34_0      <unknown> --> 3.1.1-py34_0      
    ply:                3.6-py34_0        <unknown> --> 3.8-py34_0        
    psutil:             2.2.1-py34_0      <unknown> --> 4.1.0-py34_1      
    ptyprocess:         0.4-py34_0        <unknown> --> 0.5-py34_0        
    py:                 1.4.27-py34_0     <unknown> --> 1.4.31-py34_0     
    pyasn1:             0.1.7-py34_0      <unknown> --> 0.1.9-py34_0      
    pycurl:             7.19.5.1-py34_2   <unknown> --> 7.19.5.3-py34_0   
    pyflakes:           0.9.2-py34_0      <unknown> --> 1.1.0-py34_0      
    pygments:           2.0.2-py34_0      <unknown> --> 2.1.1-py34_0      
    pyopenssl:          0.15.1-py34_1     <unknown> --> 0.15.1-py34_2     
    pyqt:               4.11.3-py34_0     <unknown> --> 4.11.4-py34_1     
    pytables:           3.2.0-np19py34_0  <unknown> --> 3.2.2-np110py34_1 
    pytest:             2.7.1-py34_0      <unknown> --> 2.8.5-py34_0      
    python-dateutil:    2.4.2-py34_0      <unknown> --> 2.5.1-py34_0      
    pytz:               2015.4-py34_0     <unknown> --> 2016.2-py34_0     
    pyzmq:              14.7.0-py34_0     <unknown> --> 15.2.0-py34_0     
    qt:                 4.8.6-3           <unknown> --> 4.8.7-1           
    qtconsole:          4.0.1-py34_0                --> 4.2.0-py34_0      
    scikit-image:       0.11.3-np19py34_0 <unknown> --> 0.12.3-np110py34_0
    scikit-learn:       0.16.1-np19py34_0 <unknown> --> 0.17.1-np110py34_0
    scipy:              0.15.1-np19py34_0 <unknown> --> 0.17.0-np110py34_0
    sip:                4.16.5-py34_0     <unknown> --> 4.16.9-py34_0     
    six:                1.9.0-py34_0      <unknown> --> 1.10.0-py34_0     
    snowballstemmer:    1.2.0-py34_0      <unknown> --> 1.2.1-py34_0      
    sphinx:             1.3.1-py34_0      <unknown> --> 1.3.5-py34_0      
    sphinx_rtd_theme:   0.1.7-py34_0      <unknown> --> 0.1.9-py34_0      
    spyder:             2.3.5.2-py34_0    <unknown> --> 2.3.8-py34_1      
    spyder-app:         2.3.5.2-py34_0    <unknown> --> 2.3.8-py34_0      
    sqlalchemy:         1.0.5-py34_0      <unknown> --> 1.0.12-py34_0     
    sympy:              0.7.6-py34_0      <unknown> --> 1.0-py34_0        
    toolz:              0.7.2-py34_0      <unknown> --> 0.7.4-py34_0      
    tornado:            4.2-py34_0        <unknown> --> 4.3-py34_0        
    werkzeug:           0.10.4-py34_0     <unknown> --> 0.11.4-py34_0     
    xlrd:               0.9.3-py34_0      <unknown> --> 0.9.4-py34_0      
    xlsxwriter:         0.7.3-py34_0      <unknown> --> 0.8.4-py34_0      
    xlwings:            0.3.5-py34_0      <unknown> --> 0.7.0-py34_0      
    zeromq:             4.0.5-0           <unknown> --> 4.1.3-0           

The following packages will be SUPERCEDED by a higher-priority channel:

    abstract-rendering: 0.5.1-np19py34_0  <unknown> --> 0.5.1-np110py34_0 
    blz:                0.6.2-np19py34_1  <unknown> --> removed-0         
    bottleneck:         1.0.0-np19py34_0  <unknown> --> 1.0.0-np110py34_0 
    dynd-python:        0.6.5-np19py34_0  <unknown> --> removed-0         
    flask:              0.10.1-py34_1     <unknown> --> 0.10.1-py34_1     
    libxslt:            1.1.28-2          <unknown> --> 1.1.28-2          
    sockjs-tornado:     1.0.1-py34_0      <unknown> --> 1.0.1-py34_0      
    statsmodels:        0.6.1-np19py34_0  <unknown> --> 0.6.1-np110py34_0 

The following packages will be DOWNGRADED due to dependency conflicts:

    jinja2:             2.8-py34_1                  --> 2.8-py34_0        
    jupyter:            1.0.0-py34_3                --> 1.0.0-py34_2      
    jupyter_client:     4.3.0-py34_0                --> 4.2.2-py34_0      
    jupyter_console:    5.0.0-py34_0                --> 4.1.1-py34_0      
    jupyter_core:       4.1.1-py34_0                --> 4.1.0-py34_0      
    nbconvert:          4.2.0-py34_0                --> 4.1.0-py34_0      
    notebook:           4.2.2-py34_0                --> 4.1.0-py34_2      
    openssl:            1.0.2h-2                    --> 1.0.2g-0          
    pip:                8.1.2-py34_0                --> 8.1.1-py34_1      
    pycosat:            0.6.1-py34_1                --> 0.6.1-py34_0      
    python:             3.4.5-0                     --> 3.4.4-0           
    pyyaml:             3.11-py34_4                 --> 3.11-py34_1       
    requests:           2.10.0-py34_0               --> 2.9.1-py34_0      
    setuptools:         25.1.6-py34_0               --> 20.3-py34_0       
    sqlite:             3.13.0-0                    --> 3.9.2-0           
    terminado:          0.6-py34_0                  --> 0.5-py34_1        
    traitlets:          4.2.2-py34_0                --> 4.2.1-py34_0      
    xz:                 5.2.2-0                     --> 5.0.5-1           
    zlib:               1.2.8-3                     --> 1.2.8-0           

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
```
blz-removed-0. 100% |################################| Time: 0:00:00 266.31 kB/s
conda-env-2.6. 100% |################################| Time: 0:00:00 650.36 kB/s
dynd-python-re 100% |################################| Time: 0:00:00 256.27 kB/s
mkl-11.3.1-0.t 100% |################################| Time: 0:03:11 543.03 kB/s
openssl-1.0.2g 100% |################################| Time: 0:00:07 429.82 kB/s
sqlite-3.9.2-0 100% |################################| Time: 0:00:02 541.58 kB/s
xz-5.0.5-1.tar 100% |################################| Time: 0:00:00 537.58 kB/s
zeromq-4.1.3-0 100% |################################| Time: 0:00:01 451.42 kB/s
zlib-1.2.8-0.t 100% |################################| Time: 0:00:00 525.02 kB/s
curl-7.45.0-0. 100% |################################| Time: 0:00:00 462.36 kB/s
freetype-2.5.5 100% |################################| Time: 0:00:01 514.60 kB/s
hdf5-1.8.15.1- 100% |################################| Time: 0:00:03 459.81 kB/s
libtiff-4.0.6- 100% |################################| Time: 0:00:02 291.41 kB/s
python-3.4.4-0 100% |################################| Time: 0:00:21 553.70 kB/s
alabaster-0.7. 100% |################################| Time: 0:00:00 602.13 kB/s
appnope-0.1.0- 100% |################################| Time: 0:00:00   1.25 MB/s
backports_abc- 100% |################################| Time: 0:00:00   3.74 MB/s
beautifulsoup4 100% |################################| Time: 0:00:00 578.13 kB/s
boto-2.39.0-py 100% |################################| Time: 0:00:02 566.21 kB/s
cloudpickle-0. 100% |################################| Time: 0:00:00 552.39 kB/s
colorama-0.3.7 100% |################################| Time: 0:00:00 405.77 kB/s
cython-0.23.4- 100% |################################| Time: 0:00:04 545.22 kB/s
cytoolz-0.7.5- 100% |################################| Time: 0:00:00 701.61 kB/s
decorator-4.0. 100% |################################| Time: 0:00:00   5.52 MB/s
dill-0.2.4-py3 100% |################################| Time: 0:00:00 414.61 kB/s
et_xmlfile-1.0 100% |################################| Time: 0:00:00 567.48 kB/s
greenlet-0.4.9 100% |################################| Time: 0:00:00 522.12 kB/s
heapdict-1.0.0 100% |################################| Time: 0:00:00   3.18 MB/s
jdcal-1.2-py34 100% |################################| Time: 0:00:00   5.48 MB/s
jedi-0.9.0-py3 100% |################################| Time: 0:00:00 417.44 kB/s
llvmlite-0.9.0 100% |################################| Time: 0:00:10 621.07 kB/s
locket-0.2.0-p 100% |################################| Time: 0:00:00   1.75 MB/s
mistune-0.7.2- 100% |################################| Time: 0:00:00 716.70 kB/s
mkl-service-1. 100% |################################| Time: 0:00:00   5.15 MB/s
mpmath-0.19-py 100% |################################| Time: 0:00:02 434.36 kB/s
multipledispat 100% |################################| Time: 0:00:00   3.65 MB/s
nltk-3.2-py34_ 100% |################################| Time: 0:00:03 561.37 kB/s
numpy-1.10.4-p 100% |################################| Time: 0:00:04 623.02 kB/s
path.py-8.1.2- 100% |################################| Time: 0:00:00 742.51 kB/s
pep8-1.7.0-py3 100% |################################| Time: 0:00:00 299.89 kB/s
pillow-3.1.1-p 100% |################################| Time: 0:00:01 353.17 kB/s
ply-3.8-py34_0 100% |################################| Time: 0:00:00 433.71 kB/s
psutil-4.1.0-p 100% |################################| Time: 0:00:00 581.64 kB/s
ptyprocess-0.5 100% |################################| Time: 0:00:00 571.35 kB/s
py-1.4.31-py34 100% |################################| Time: 0:00:00 710.41 kB/s
pyasn1-0.1.9-p 100% |################################| Time: 0:00:00 550.98 kB/s
pycosat-0.6.1- 100% |################################| Time: 0:00:00 759.93 kB/s
pycurl-7.19.5. 100% |################################| Time: 0:00:00 497.65 kB/s
pyflakes-1.1.0 100% |################################| Time: 0:00:00 506.48 kB/s
pygments-2.1.1 100% |################################| Time: 0:00:02 606.67 kB/s
pytz-2016.2-py 100% |################################| Time: 0:00:00 724.18 kB/s
pyyaml-3.11-py 100% |################################| Time: 0:00:00 716.32 kB/s
pyzmq-15.2.0-p 100% |################################| Time: 0:00:00 725.71 kB/s
qt-4.8.7-1.tar 100% |################################| Time: 0:01:03 645.85 kB/s
qtpy-1.0-py34_ 100% |################################| Time: 0:00:00 502.10 kB/s
requests-2.9.1 100% |################################| Time: 0:00:00 715.20 kB/s
setuptools-20. 100% |################################| Time: 0:00:00 727.30 kB/s
simplegeneric- 100% |################################| Time: 0:00:00   4.67 MB/s
sip-4.16.9-py3 100% |################################| Time: 0:00:00 584.92 kB/s
six-1.10.0-py3 100% |################################| Time: 0:00:00 513.06 kB/s
snowballstemme 100% |################################| Time: 0:00:00 418.32 kB/s
sphinx_rtd_the 100% |################################| Time: 0:00:01 631.91 kB/s
sqlalchemy-1.0 100% |################################| Time: 0:00:02 722.18 kB/s
toolz-0.7.4-py 100% |################################| Time: 0:00:00 428.30 kB/s
unicodecsv-0.1 100% |################################| Time: 0:00:00 508.81 kB/s
werkzeug-0.11. 100% |################################| Time: 0:00:00 580.19 kB/s
xlrd-0.9.4-py3 100% |################################| Time: 0:00:00 735.39 kB/s
xlsxwriter-0.8 100% |################################| Time: 0:00:00 694.02 kB/s
abstract-rende 100% |################################| Time: 0:00:00 506.21 kB/s
argcomplete-1. 100% |################################| Time: 0:00:00 494.78 kB/s
astropy-1.1.2- 100% |################################| Time: 0:00:09 652.46 kB/s
babel-2.2.0-py 100% |################################| Time: 0:00:07 643.00 kB/s
bcolz-1.0.0-py 100% |################################| Time: 0:00:01 316.56 kB/s
bottleneck-1.0 100% |################################| Time: 0:00:00 649.81 kB/s
cffi-1.5.2-py3 100% |################################| Time: 0:00:00 680.82 kB/s
chest-0.2.3-py 100% |################################| Time: 0:00:00   4.20 MB/s
clyent-1.2.1-p 100% |################################| Time: 0:00:00 473.81 kB/s
conda-4.2.13-p 100% |################################| Time: 0:00:00 540.72 kB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00   8.20 MB/s
gevent-1.1.0-p 100% |################################| Time: 0:00:00 603.56 kB/s
h5py-2.5.0-np1 100% |################################| Time: 0:00:01 639.65 kB/s
jinja2-2.8-py3 100% |################################| Time: 0:00:00 698.49 kB/s
lxml-3.6.0-py3 100% |################################| Time: 0:00:01 713.52 kB/s
networkx-1.11- 100% |################################| Time: 0:00:01 720.86 kB/s
numba-0.24.0-n 100% |################################| Time: 0:00:02 707.63 kB/s
numexpr-2.5-np 100% |################################| Time: 0:00:00 730.10 kB/s
openpyxl-2.3.2 100% |################################| Time: 0:00:00 703.52 kB/s
patsy-0.4.0-np 100% |################################| Time: 0:00:00 654.52 kB/s
pexpect-4.0.1- 100% |################################| Time: 0:00:00 593.57 kB/s
pickleshare-0. 100% |################################| Time: 0:00:00 453.02 kB/s
pip-8.1.1-py34 100% |################################| Time: 0:00:02 650.61 kB/s
pyqt-4.11.4-py 100% |################################| Time: 0:00:06 685.73 kB/s
pytest-2.8.5-p 100% |################################| Time: 0:00:00 619.04 kB/s
python-dateuti 100% |################################| Time: 0:00:00 535.09 kB/s
qtawesome-0.3. 100% |################################| Time: 0:00:00 710.42 kB/s
scipy-0.17.0-n 100% |################################| Time: 0:00:18 669.29 kB/s
singledispatch 100% |################################| Time: 0:00:00   6.63 MB/s
sympy-1.0-py34 100% |################################| Time: 0:00:08 708.01 kB/s
tornado-4.3-py 100% |################################| Time: 0:00:01 506.17 kB/s
traitlets-4.2. 100% |################################| Time: 0:00:00 542.32 kB/s
xlwings-0.7.0- 100% |################################| Time: 0:00:00 701.00 kB/s
anaconda-clien 100% |################################| Time: 0:00:00 714.78 kB/s
bokeh-0.11.1-p 100% |################################| Time: 0:00:04 705.70 kB/s
cryptography-1 100% |################################| Time: 0:00:01 309.82 kB/s
datashape-0.5. 100% |################################| Time: 0:00:00 413.99 kB/s
flask-0.10.1-p 100% |################################| Time: 0:00:00 304.96 kB/s
ipython-4.1.2- 100% |################################| Time: 0:00:01 707.54 kB/s
jupyter_core-4 100% |################################| Time: 0:00:00 618.18 kB/s
matplotlib-1.5 100% |################################| Time: 0:00:09 676.27 kB/s
pandas-0.18.0- 100% |################################| Time: 0:00:08 698.22 kB/s
pytables-3.2.2 100% |################################| Time: 0:00:02 689.15 kB/s
scikit-learn-0 100% |################################| Time: 0:00:05 656.57 kB/s
sockjs-tornado 100% |################################| Time: 0:00:00 341.15 kB/s
sphinx-1.3.5-p 100% |################################| Time: 0:00:01 653.73 kB/s
terminado-0.5- 100% |################################| Time: 0:00:00 383.10 kB/s
conda-manager- 100% |################################| Time: 0:00:00 679.79 kB/s
flask-cors-2.1 100% |################################| Time: 0:00:00 544.76 kB/s
jupyter_client 100% |################################| Time: 0:00:00 433.56 kB/s
odo-0.4.2-py34 100% |################################| Time: 0:00:00 426.88 kB/s
partd-0.3.2-py 100% |################################| Time: 0:00:00 372.51 kB/s
pyopenssl-0.15 100% |################################| Time: 0:00:00 718.71 kB/s
scikit-image-0 100% |################################| Time: 0:00:26 706.77 kB/s
statsmodels-0. 100% |################################| Time: 0:00:07 709.70 kB/s
blaze-core-0.9 100% |################################| Time: 0:00:00 713.23 kB/s
dask-0.8.1-py3 100% |################################| Time: 0:00:00 714.22 kB/s
ipykernel-4.3. 100% |################################| Time: 0:00:00 518.08 kB/s
nbconvert-4.1. 100% |################################| Time: 0:00:00 717.81 kB/s
blaze-0.9.1-py 100% |################################| Time: 0:00:00 713.92 kB/s
jupyter_consol 100% |################################| Time: 0:00:00 593.20 kB/s
notebook-4.1.0 100% |################################| Time: 0:00:06 686.84 kB/s
qtconsole-4.2. 100% |################################| Time: 0:00:00 733.62 kB/s
ipython-notebo 100% |################################| Time: 0:00:00   3.65 MB/s
ipython-qtcons 100% |################################| Time: 0:00:00   3.24 MB/s
spyder-2.3.8-p 100% |################################| Time: 0:00:03 696.35 kB/s
jupyter-1.0.0- 100% |################################| Time: 0:00:00   3.30 MB/s
spyder-app-2.3 100% |################################| Time: 0:00:00   5.98 MB/s
anaconda-4.0.0 100% |################################| Time: 0:00:00   4.28 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...       |  66%

An unexpected error has occurred.
```

**Comment by kalefranz** [comment]
To my knowledge, permissions errors have been completely resolved in conda 4.3.  Update to conda 4.3, and file a new issue if you continue to have problems.
