### ISSUE TITLE
Linking error from conda-forge package

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#4086]
When trying to install the notebook extensions from conda-forge via:

    conda install jupyter_contrib_nbextensions

I get a failure when linking the dependency `jupyter_highlight_selected_word`. Here is the error. 

```
Linking packages ...
LinkError: Link error: Error: post-link failed for: conda-forge::jupyter_highlight_selected_word-0.0.5-py35_0 
```

Running conda 4.2.9 on macOS 10.12.

**Comment by kalefranz** [comment]
`post-link failed` means there's a problem with the package.  Best to file an issue with conda-forge for that feedstock.
