### ISSUE TITLE
PaddingError: Placeholder of length '80' too short in package ...

### ISSUE THREAD

**Issue by tedtoal** [conda/conda#4088]
Sorry if I'm posting this in the wrong place...

I get a "PaddingError" error with 'conda install' using conda version 4.2.12, and after spending considerable time searching and reading the many web pages discussing this error occuring in one context or another, I'm no closer to understanding how I might resolve it.

Since lots of people get this error, and have been getting it, for over a year now, wouldn't it be wise to somewhere have guidelines on how to diagnose and fix this problem?  Or maybe there are such guidelines?

**Comment by mingwandroid** [comment]
Please show the full output. Which package was it?

**Comment by tedtoal** [comment]
At first it seemed to be centered around openssl.  I was trying to install R 3.3.1.  When the error occurred, I installed an older openssl with no problems, then tried re-installing R with --no-update-dependencies, but then the error occurred with 'fontconfig'.

I have a fairly long conda environment path, which I really don't want to change.

**Comment by tedtoal** [comment]
Full output:

    twtoal@carcinos> conda install --no-update-dependencies -c r r=3.3.1
    Fetching package metadata ...............
    Solving package specifications: ..........
    
    Package plan for installation in environment /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/variants_pipeline:
    
    The following NEW packages will be INSTALLED:
    
        cairo:         1.12.18-intel_6     intel       [intel]
        curl:          7.49.1-2            conda-forge
        fontconfig:    2.11.1-intel_7      intel       [intel]
        freetype:      2.5.5-intel_9       intel       [intel]
        glib:          2.51.0-2            conda-forge
        harfbuzz:      0.9.39-1                       
        libpng:        1.6.22-intel_9      intel       [intel]
        libtiff:       4.0.6-7             conda-forge
        libxml2:       2.9.3-intel_10      intel       [intel]
        pango:         1.39.0-0                       
        pip:           8.1.2-py27_intel_4  intel       [intel]
        pixman:        0.32.6-intel_6      intel       [intel]
        python:        2.7.12-intel_18     intel       [intel]
        r:             3.3.1-r3.3.1_0      r          
        r-base:        3.3.1-3             r          
        r-boot:        1.3_18-r3.3.1_0     r          
        r-class:       7.3_14-r3.3.1_0     r          
        r-cluster:     2.0.4-r3.3.1_0      r          
        r-codetools:   0.2_14-r3.3.1_0     r          
        r-foreign:     0.8_66-r3.3.1_0     r          
        r-kernsmooth:  2.23_15-r3.3.1_0    r          
        r-lattice:     0.20_33-r3.3.1_0    r          
        r-mass:        7.3_45-r3.3.1_0     r          
        r-matrix:      1.2_6-r3.3.1_0      r          
        r-mgcv:        1.8_12-r3.3.1_0     r          
        r-nlme:        3.1_128-r3.3.1_0    r          
        r-nnet:        7.3_12-r3.3.1_0     r          
        r-recommended: 3.3.1-r3.3.1_0      r          
        r-rpart:       4.1_10-r3.3.1_0     r          
        r-spatial:     7.3_11-r3.3.1_0     r          
        r-survival:    2.39_4-r3.3.1_0     r          
        readline:      6.3-1               conda-forge
        setuptools:    23.0.0-py27_intel_4 intel       [intel]
        sqlite:        3.13.0-intel_13     intel       [intel]
        tcl:           8.6.4-intel_15      intel       [intel]
        tk:            8.6.4-intel_15      intel       [intel]
        wheel:         0.29.0-py27_intel_4 intel       [intel]
        xz:            5.2.2-intel_14      intel       [intel]
        zlib:          1.2.8-intel_9       intel       [intel]
    
    Proceed ([y]/n)? y
    
    Linking packages ...
    [fontconfig          ]|#########################################                                                             |  41%
    
    PaddingError: Placeholder of length '80' too short in package intel::fontconfig-2.11.1-intel_7.
    The package must be rebuilt with conda-build > 2.0.

**Comment by mingwandroid** [comment]
Your installation is rooted at a depth of 66 characters:

```
echo /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/ | wc -c
66
```

If you try to install a package built with an 80 character padded prefix (such as Intel's fontconfig) that leaves only 12 characters for the files themselves. Most packages will contain paths consisting of more characters than that.

Do you need to install to such a long prefix? If you were able to use a shorter installation prefix for your root folder then that would prevent this from happening. The shorter the better here.

The best fix for this is that Intel needs to rebuild their `fontconfig` package with `conda-build >=2` and in doing so, ensure that it ends up with a 255 character prefix.
