### ISSUE TITLE
--file seems to have surprising behavior for update vs install

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4096]
I have a simplistic view of `conda update` vs `conda install`.

For `update` I assume I don't specify a version number, and Conda will figure it out for me, giving me the latest version of a package that will work with everything else I have installed.

For `install`, if it is a new package, I assume I'll get the latest available version of a package that results in the minimum set of changes to existing packages.

For `install`, if it is an existing package, I assume that I need to provide a specific version number and otherwise Conda will say *"already installed!"*.  If I provide a version number then Conda will do everything in its power to give me that version of that package, and change whatever else it needs to in my Conda environment to make that happen (upgrades and downgrades).

If any of those assumptions are broadly off base then what I have to say next can be ignored.  But if they are reasonable assumptions then the behavior of the `--file` option confuses me.

As per this ML response I just wrote: https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/Q50Yl1V2q9g/yNdqhll4CQAJ

I have now created a version-free list of Conda packages that are found in Anaconda 4.2:

https://gist.github.com/ijstokes/3688030a04639288539aa0e251c526dd#file-anaconda42_pkgs_noversions-txt

One possible way I could imagine using those would be to do:

```bash
for pkg in `cat anaconda42_pkgs_noversions.txt`; do
    conda update -y $pkg
done
```

But since I've got the `--file` option available I can imagine saving myself some bash scripting and just invoke:

```
conda update --file anaconda42_pkgs_noversions.txt
```

But this does not work!  Nothing happens, and I'm told all the packages are already installed.  I **know** they are installed, but I want to `update` them.

Instead it seems I need to do:

```
conda install --file anaconda42_pkgs_noversions.txt
```

This is a surprise!

**Comment by kalefranz** [comment]
Might be a bug instead of a feature.  Idk.  But I'm labelling a lot of tickets with that 'environment-spec' tag, because sometime soon I'd like to revisit this whole thing.  And resolve all the discrepancies between conda and conda-env.  And bring conda here in line and consistent as much as possible with what Havoc is doing with Anaconda Project.  So it looks like a *team* actually built all of our stuff together.
