### ISSUE TITLE
Could not connect to https://conda.anaconda.org/r/win-64/r-mass-7.3_45-r3.3.1_0.tar.bz2 An unexpected error has occurred.

### ISSUE THREAD

**Issue by krnvamsi** [conda/conda#4114]

**Comment by mingwandroid** [comment]
Can you show the rest of the output?

This is likely either a transient connectivity issue or a firewall at your location.

I was able to download that file fine just now.

**Comment by kalefranz** [comment]
Intermittent HTTP error.
