### ISSUE TITLE
Could not connect to https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64 An unexpected error has occurred

### ISSUE THREAD

**Issue by WarSmoke** [conda/conda#4121]
Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/kcui/miniconda2  (writable)
    default environment : /Users/kcui/miniconda2
       envs directories : /Users/kcui/miniconda2/envs
          package cache : /Users/kcui/miniconda2/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/kcui/.condarc
           offline mode : False

`$ /Users/kcui/miniconda2/bin/conda create -n py34 python=3.4`

    Traceback (most recent call last):
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/kcui/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/free/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103ee5a90>, u'Connection to corp.com timed out. (connect timeout=3.05)')): https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64

I want to install box2d, but I cant fix this connection error.
when I $conda install numpy , this same error occurs.
whien I vim .condarc and change to  https://repo.continuum.io/pkgs/free/osx-64, this same error occurs.

here is .condarc
  1 channels:
  2   - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  3 #  - https://repo.continuum.io/pkgs/free/osx-64
  4   - defaults
  5 show_channel_urls: true
  6 
  7 
  8 proxy_servers:
  9     http: http://user:pass@corp.com:8080
 10     https: https://user:pass@corp.com:8080

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
