### ISSUE TITLE
Problem: Downloading source fails for some packages

### ISSUE THREAD

**Issue by gabm** [conda/conda#4134]
I get a Download error on downloading a certain package (patchelf). Its strange, because others work. I'm on latest master 4.3.2+34

  ```
[..] python3.5/site-packages/conda/gateways/download.py", line 99, in download
    downloaded_bytes=streamed_bytes)
conda.CondaError: Downloaded bytes did not match Content-Length
  url: http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
  target_path: /[..]/conda-bld/src_cache/patchelf-0.9.tar.gz
  Content-Length: 191502
  downloaded bytes: 768000
```

The downloaded file in the src_cache is ok, md5sums match. Running conda build a second time works because it takes it from the src_cache. So I guess its a problem in the downloader. I could reproduce this error with this file only by now. Changing tar.gz to tar.bz2 (which is also offered by this vendor) makes it work. Other packages with tar.bz2 and tar.gz work fine though.

The number looks strange, its too perfect.. maybe an overflow or smthg?

In any case: Maybe its useful to clean up the src_cache after error (guess thats a conda-build issue then), because if the download would be corrupted for real, then we'd end up with a corrupted file that gets picked up next time...

**Comment by kalefranz** [comment]
We at least attempted a fix somewhere, I think in 4.2 that got merged up into later releases of 4.3.  Are you still seeing this in later versions of 4.3?

**Comment by gabm** [comment]
@kalefranz I'm sorry, but the issue still persists with conda 4.3.21 on all systems... I used the recipe from patchelf from conda-forge: https://raw.githubusercontent.com/conda-forge/patchelf-feedstock/master/recipe/meta.yaml

the output is more or less the same on all systems: Windows, Linux-Intel64 and Aarch64... Please see the output here:

```shell
conda build . --debug
BUILD START: patchelf-0.9-1
    (actual version deferred until further download or env creation)
Source cache directory is: /home/gabm/miniconda3/conda-bld/src_cache
Downloading source to cache: patchelf-0.9.tar.gz
Downloading http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
INFO:fetch.start:('patchelf-0.9.t', 191502)                    <<<!!!----- here is a wrong filename!
INFO:fetch.update:16384
INFO:fetch.update:32768
INFO:fetch.update:49152
INFO:fetch.update:65536
INFO:fetch.update:81920
INFO:fetch.update:98304
INFO:fetch.update:114688
INFO:fetch.update:131072
INFO:fetch.update:147456
INFO:fetch.update:163840
INFO:fetch.update:180224
INFO:fetch.update:191502
INFO:fetch.stop:None
Success
MD5 mismatch: '34b74b76333f72e29ec44384e09856ac' != '3c265508526760f233620f35d79c79fc'
```

Please note as above, that the filename in fetch.start seems to be wrong...

**Comment by remram44** [comment]
I am experiencing this for local files (file://) as well (wtf?)

**Comment by gabm** [comment]
@msarahan is this in conda-build instead?

**Comment by remram44** [comment]
Also my whole build fails because now conda-build outputs more stuff on stdout than the package name ("Attempting to finalize metadata for ..."). Seems like as usual, building conda packages means I have to spend a half hour hunting down a working version of conda.

**Comment by msarahan** [comment]
Sorry @remram44 - the extra info is reported at https://github.com/conda/conda-build/issues/2173

I believe this download issue is due to requests transparently decompressing files.  @kalefranz has said that this is primarily due to misconfigured servers, but these more recent reports - especially the one for file:// urls seems to point to something else.  I will try to reproduce with patchelf.  @remram44 if you have any reproducible steps I can take for the file:// url, I'd be happy to take a look there too.

**Comment by remram44** [comment]
```
conda.CondaError: Downloaded bytes did not match Content-Length
  url: file:///tmp/rr_conda_p1qpE3IB/reprounzip.tar.gz
  target_path: /opt/conda/conda-bld/src_cache/reprounzip.tar.gz
  Content-Length: 47
  downloaded bytes: 50889
```
I'm using a normal tar.gz file built with `setup.py sdist`.

If your suspicion were true, the 47 bytes would mean something -- here they don't match the filesize (50889) and certainly not the decompressed size.

**Comment by msarahan** [comment]
@remram44 Yes, that's something completely different.  Have you looked at the 47 byte file?  It seems like it might be some short error message that may tell us something more.

**Comment by kalefranz** [comment]
I haven't seen any other reports of this issue. Does that mean, whatever the underlying cause was, that it's now resolved?

**Comment by gabm** [comment]
its not really resolved.. it seems that downloading the file with wget gives you another file than what conda downloads into the source cache... the file downloaded through conda gives:

```
$ md5sum src_cache/patchelf-0.9_b0a9699738.tar.gz 
34b74b76333f72e29ec44384e09856ac  src_cache/patchelf-0.9_b0a9699738.tar.gz
$ sha256sum src_cache/patchelf-0.9_b0a9699738.tar.gz 
b0a96997382ec3597aee1376a9f6dfed04053c83f2b3d1062cc7b7cec4c6c95b  src_cache/patchelf-0.9_b0a9699738.tar.gz
```

through wget:
```
$ md5sum patchelf-0.9.tar.gz 
3c265508526760f233620f35d79c79fc  patchelf-0.9.tar.gz
$ sha256sum patchelf-0.9.tar.gz 
f2aa40a6148cb3b0ca807a1bf836b081793e55ec9e5540a5356d800132be7e0a  patchelf-0.9.tar.gz
```

**Comment by kalefranz** [comment]
I can confirm I get the same results for hashes.

```
$ curl -sSL http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz | shasum -a 256
f2aa40a6148cb3b0ca807a1bf836b081793e55ec9e5540a5356d800132be7e0a
```

Also,

```
curl -IL http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
HTTP/1.1 301 Moved Permanently
Date: Fri, 02 Mar 2018 11:32:35 GMT
Server: Apache/2.4.29 (Unix) OpenSSL/1.0.2n
Location: https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Fri, 02 Mar 2018 11:32:35 GMT
Server: Apache/2.4.29 (Unix) OpenSSL/1.0.2n
Strict-Transport-Security: max-age=15552000
Last-Modified: Mon, 29 Feb 2016 10:27:53 GMT
ETag: "2ec0e-52ce619f2dc40"
Accept-Ranges: bytes
Content-Length: 191502
Content-Type: application/x-tar
Content-Encoding: x-gzip
```

**Comment by bsolomon1124** [comment]
Saw this error out of nowhere with `click==7.*` and the byte sizes differed by a pretty massive factor (3x).

```
CondaError: Downloaded bytes did not match Content-Length
  url: https://repo.anaconda.com/pkgs/main/noarch/click-7.1.2-py_0.conda
  target_path: /opt/conda/pkgs/click-7.1.2-py_0.conda
  Content-Length: 72569
  downloaded bytes: 23818
```

However, it seemed to be a one-off error, as re-running installed with no issues.

**Comment by mhiyer** [comment]
Is there a solution for this problem? I am encountering this too.
