### ISSUE TITLE
ENH: Mirroring/caching support

### ISSUE THREAD

**Issue by westurner** [conda/conda#414]
For managing offline installations (e.g. computer labs) which don't need to re-download every package from the internet, it would be great if there was some sort of caching/mirroring support.

I'm not very clear on how conda soft/hardlinks on a local machine; there may already be a machine-level cache (like how pip has `-d / --download-cache / pip.conf:download-cache`)

This particular use case has more to do with running a LAN-local cache / mirror of [one or more] binstar package sets.

I would imagine that something out-of-band (like squid or nginx `proxy_cache_path` https://gist.github.com/dctrwatson/5785638) would work, but the extra SSL overhead could be eliminated by some sort of conda-package-aware caching / mirroring. Collective.eggproxy and z3c.pypimirror come to mind.

**Comment by Endle** [comment]
Is it possible to make a full mirror of <http://repo.continuum.io/>?
If my college set up such a mirror, users in my college can save up a lot of bandwidth and time

**Comment by MattThornell** [comment]
The short answer is yes, you can mirror the repo without violating any terms. We do not recommend or support it though, and can't promise that any future changes we make to our repo site will keep your mirror from breaking. We do have a supported option though via our Anaconda Server product (www.continuum.io/anaconda-server), and we even have a specific tool that privately mirrors our repo for your group. Let me know if you would like more information on this, and I'd be happy to help. My email is matt.thornell@continuum.io, or sales@continuum.io

Thanks.

**Comment by kalefranz** [comment]
Just to clarify the comment by @MattThornell 

Anaconda and Miniconda are trademarks of Continuum Analytics. Public mirrors of repo.continuum.io are not allowed without express permission from Continuum Analytics. For private mirrors and technical support, we encourage you to look at Anaconda Enterprise and Anaconda Support.
