### ISSUE TITLE
exception unablle to open C:\\Anaconda\\pkgs\\qtawesome-0.3.3-py35_0.tar.bz2

### ISSUE THREAD

**Issue by DMcKatHome** [conda/conda#4140]
alabaster-0.7. 100% |###############################| Time: 0:00:00 351.09 kB/s
anaconda-clean 100% |###############################| Time: 0:00:00   1.04 MB/s
backports-1.0- 100% |###############################| Time: 0:00:00  13.00 kB/s
beautifulsoup4 100% |###############################| Time: 0:00:00   1.84 MB/s
bitarray-0.8.1 100% |###############################| Time: 0:00:00 241.50 kB/s
boto-2.42.0-py 100% |###############################| Time: 0:00:00   4.26 MB/s
click-6.6-py35 100% |###############################| Time: 0:00:00   1.90 MB/s
cloudpickle-0. 100% |###############################| Time: 0:00:00 632.11 kB/s
colorama-0.3.7 100% |###############################| Time: 0:00:00 603.58 kB/s
comtypes-1.1.2 100% |###############################| Time: 0:00:00   1.45 MB/s
console_shortc 100% |###############################| Time: 0:00:00 943.23 kB/s
contextlib2-0. 100% |###############################| Time: 0:00:00 212.37 kB/s
curl-7.49.0-vc 100% |###############################| Time: 0:00:00   3.05 MB/s
cython-0.24.1- 100% |###############################| Time: 0:00:00   7.66 MB/s
decorator-4.0. 100% |###############################| Time: 0:00:00 525.65 kB/s
dill-0.2.5-py3 100% |###############################| Time: 0:00:00   1.40 MB/s
docutils-0.12- 100% |###############################| Time: 0:00:00   4.86 MB/s
entrypoints-0. 100% |###############################| Time: 0:00:00 243.52 kB/s
fastcache-1.0. 100% |###############################| Time: 0:00:00 353.33 kB/s
filelock-2.0.6 100% |###############################| Time: 0:00:00 364.68 kB/s
greenlet-0.4.1 100% |###############################| Time: 0:00:00 566.67 kB/s
hdf5-1.8.15.1- 100% |###############################| Time: 0:00:00   6.70 MB/s
heapdict-1.0.0 100% |###############################| Time: 0:00:00 252.50 kB/s
idna-2.1-py35_ 100% |###############################| Time: 0:00:00 592.37 kB/s
imagesize-0.7. 100% |###############################| Time: 0:00:00 116.63 kB/s
itsdangerous-0 100% |###############################| Time: 0:00:00 365.30 kB/s
jdcal-1.2-py35 100% |###############################| Time: 0:00:00 400.14 kB/s
jedi-0.9.0-py3 100% |###############################| Time: 0:00:00   1.99 MB/s
jsonschema-2.5 100% |###############################| Time: 0:00:00   1.94 MB/s
lazy-object-pr 100% |###############################| Time: 0:00:00 827.94 kB/s
libpng-1.6.22- 100% |###############################| Time: 0:00:00   3.68 MB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00   2.95 MB/s
llvmlite-0.13. 100% |###############################| Time: 0:00:00   6.84 MB/s
locket-0.2.0-p 100% |###############################| Time: 0:00:00 307.80 kB/s
lxml-3.6.4-py3 100% |###############################| Time: 0:00:00   6.07 MB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00 824.53 kB/s
mistune-0.7.3- 100% |###############################| Time: 0:00:00   1.61 MB/s
mkl-service-1. 100% |###############################| Time: 0:00:00 436.69 kB/s
mpmath-0.19-py 100% |###############################| Time: 0:00:00   3.81 MB/s
multipledispat 100% |###############################| Time: 0:00:00 241.29 kB/s
nltk-3.2.1-py3 100% |###############################| Time: 0:00:00   7.65 MB/s
nose-1.3.7-py3 100% |###############################| Time: 0:00:00   2.57 MB/s
numpy-1.11.1-p 100% |###############################| Time: 0:00:00   6.78 MB/s
path.py-8.2.1- 100% |###############################| Time: 0:00:00   1.04 MB/s
pep8-1.7.0-py3 100% |###############################| Time: 0:00:00   1.24 MB/s
pkginfo-1.3.2- 100% |###############################| Time: 0:00:00   1.43 MB/s
ply-3.9-py35_0 100% |###############################| Time: 0:00:00   1.35 MB/s
psutil-4.3.1-p 100% |###############################| Time: 0:00:00   2.47 MB/s
py-1.4.31-py35 100% |###############################| Time: 0:00:00   1.49 MB/s
pyasn1-0.1.9-p 100% |###############################| Time: 0:00:00 567.49 kB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00   1.28 MB/s
pycparser-2.14 100% |###############################| Time: 0:00:00   2.25 MB/s
pycrypto-2.6.1 100% |###############################| Time: 0:00:00   2.11 MB/s
pyflakes-1.3.0 100% |###############################| Time: 0:00:00   1.98 MB/s
pygments-2.1.3 100% |###############################| Time: 0:00:00   6.51 MB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00   1.28 MB/s
pytz-2016.6.1- 100% |###############################| Time: 0:00:00   2.69 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:01   6.04 MB/s
pyyaml-3.12-py 100% |###############################| Time: 0:00:00   1.63 MB/s
pyzmq-15.4.0-p 100% |###############################| Time: 0:00:00   3.95 MB/s
qtpy-1.1.2-py3 100% |###############################| Time: 0:00:00 349.72 kB/s
requests-2.11. 100% |###############################| Time: 0:00:00   4.76 MB/s
rope-0.9.4-py3 100% |###############################| Time: 0:00:00   1.92 MB/s
simplegeneric- 100% |###############################| Time: 0:00:00 280.21 kB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:00   2.09 MB/s
snowballstemme 100% |###############################| Time: 0:00:00 937.06 kB/s
sqlalchemy-1.0 100% |###############################| Time: 0:00:00   5.68 MB/s
toolz-0.8.0-py 100% |###############################| Time: 0:00:00   1.48 MB/s
tornado-4.4.1- 100% |###############################| Time: 0:00:00   4.61 MB/s
unicodecsv-0.1 100% |###############################| Time: 0:00:00 637.09 kB/s
wcwidth-0.1.7- 100% |###############################| Time: 0:00:00 700.55 kB/s
werkzeug-0.11. 100% |###############################| Time: 0:00:00   3.23 MB/s
win_unicode_co 100% |###############################| Time: 0:00:00 540.81 kB/s
wrapt-1.10.6-p 100% |###############################| Time: 0:00:00   1.04 MB/s
xlrd-1.0.0-py3 100% |###############################| Time: 0:00:00   2.64 MB/s
xlsxwriter-0.9 100% |###############################| Time: 0:00:00   2.81 MB/s
xlwt-1.1.2-py3 100% |###############################| Time: 0:00:00   2.60 MB/s
argcomplete-1. 100% |###############################| Time: 0:00:00   1.73 MB/s
astroid-1.4.7- 100% |###############################| Time: 0:00:00   3.07 MB/s
astropy-1.2.1- 100% |###############################| Time: 0:00:00   7.46 MB/s
babel-2.3.4-py 100% |###############################| Time: 0:00:00  10.21 MB/s
bottleneck-1.1 100% |###############################| Time: 0:00:00   2.33 MB/s
cffi-1.7.0-py3 100% |###############################| Time: 0:00:00   2.56 MB/s
chest-0.2.3-py 100% |###############################| Time: 0:00:00 601.66 kB/s
clyent-1.2.2-p 100% |###############################| Time: 0:00:00 728.91 kB/s
configobj-5.0. 100% |###############################| Time: 0:00:00   1.17 MB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.23 MB/s
cytoolz-0.8.0- 100% |###############################| Time: 0:00:35   5.94 kB/s
dynd-python-0. 100% |###############################| Time: 0:00:00   4.45 MB/s
freetype-2.5.5 100% |###############################| Time: 0:00:00   5.14 MB/s
get_terminal_s 100% |###############################| Time: 0:00:00 449.30 kB/s
gevent-1.1.2-p 100% |###############################| Time: 0:00:00   4.72 MB/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:00   4.75 MB/s
jinja2-2.8-py3 100% |###############################| Time: 0:00:00   3.70 MB/s
networkx-1.11- 100% |###############################| Time: 0:00:00   7.92 MB/s
numba-0.28.1-n 100% |###############################| Time: 0:00:00   5.08 MB/s
numexpr-2.6.1- 100% |###############################| Time: 0:00:00   2.50 MB/s
partd-0.3.6-py 100% |###############################| Time: 0:00:00   1.09 MB/s
pathlib2-2.1.0 100% |###############################| Time: 0:00:00 408.67 kB/s
patsy-0.4.1-py 100% |###############################| Time: 0:00:00   4.50 MB/s
pickleshare-0. 100% |###############################| Time: 0:00:00 974.99 kB/s
pip-8.1.2-py35 100% |###############################| Time: 0:00:00   6.98 MB/s
prompt_toolkit 100% |###############################| Time: 0:00:00   3.50 MB/s
pycurl-7.43.0- 100% |###############################| Time: 0:00:00   1.83 MB/s
pytest-2.9.2-p 100% |###############################| Time: 0:00:00   3.56 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   3.00 MB/s
qt-5.6.0-vc14_ 100% |###############################| Time: 0:00:04  10.58 MB/s
An unexpected error has occurred.                   | Time: 0:00:13   3.56 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.11.0
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
          package cache : C:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Anaconda\Scripts\conda-script.py create -n py35 python=3.5 anaconda`

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'C:\\Anaconda\\pkgs\\qtawesome-0.3.3-py35_0.tar.bz2.
part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

C:\Users\danny>

**Comment by kalefranz** [comment]
Either an intermittent http error, or a permissions issue.  `conda clean --packages --tarballs` might help.  If it's just an HTTP timeout, then your issue has probably already resolved itself.
