### ISSUE TITLE
Could not connect to https://repo.continuum.io/pkgs/free/win-64, An unexpected error occurred

### ISSUE THREAD

**Issue by SoumiC** [conda/conda#4142]
Dear Sir/Madam,
I was trying to access Keras library using Theano background on a Windows 64 bit system.
I got this warning:
Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`

From anaconda prompt, I run the command "conda install m2w64-toolchain" and got the error:
**Could not connect to https://repo.continuum.io/pkgs/free/win-64, An unexpected error occurred**
I am unable to solve the warning, I additionally tried to install minGW for 32 bit as well as 64 bit. The issue is not getting resolved. Please suggest me my next action.

Thank you,

Regards,
Soumi Chaki

![image](https://cloud.githubusercontent.com/assets/17950143/21500462/1cf1cd3c-cc65-11e6-812a-4a889f7c7f57.png)

**Comment by kalefranz** [comment]
Intermittent HTTP error.
