### ISSUE TITLE
conda update --all and conda list fails

### ISSUE THREAD

**Issue by plzombie** [conda/conda#4146]
"conda update --all" returns

> conda update --all
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-32
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : not installed
>          python version : 3.4.5.final.0
>        requests version : 2.12.3
>        root environment : C:\Miniconda3  (writable)
>     default environment : C:\Miniconda3
>        envs directories : C:\Miniconda3\envs
>           package cache : C:\Miniconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-32
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-32
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-32
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ C:\Miniconda3\Scripts\conda-script.py update --all`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
>         install(args, parser, 'update')
>       File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 157, in install
>         linked = install_linked(prefix)
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 923, in linked
>         return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 915, in linked_data
>         load_linked_data(prefix, fn[:-5], ignore_channels=ignore_channels)
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 839, in load_linked_data
>         rec = json.load(fi)
>       File "C:\Miniconda3\lib\json\__init__.py", line 268, in load
>         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>       File "C:\Miniconda3\lib\json\__init__.py", line 318, in loads
>         return _default_decoder.decode(s)
>       File "C:\Miniconda3\lib\json\decoder.py", line 343, in decode
>         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>       File "C:\Miniconda3\lib\json\decoder.py", line 359, in raw_decode
>         obj, end = self.scan_once(s, idx)
>     ValueError: Expecting ',' delimiter: line 883 column 1 (char 68749)

"conda list" returns same error message

> conda list
> # packages in environment at C:\Miniconda3:
> #
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-32
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : not installed
>          python version : 3.4.5.final.0
>        requests version : 2.12.3
>        root environment : C:\Miniconda3  (writable)
>     default environment : C:\Miniconda3
>        envs directories : C:\Miniconda3\envs
>           package cache : C:\Miniconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-32
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-32
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-32
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ C:\Miniconda3\Scripts\conda-script.py list`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 227, in execute
>         show_channel_urls=context.show_channel_urls)
>       File "C:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 163, in print_packages
>         installed = linked(prefix)
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 923, in linked
>         return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 915, in linked_data
>         load_linked_data(prefix, fn[:-5], ignore_channels=ignore_channels)
>       File "C:\Miniconda3\lib\site-packages\conda\install.py", line 839, in load_linked_data
>         rec = json.load(fi)
>       File "C:\Miniconda3\lib\json\__init__.py", line 268, in load
>         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>       File "C:\Miniconda3\lib\json\__init__.py", line 318, in loads
>         return _default_decoder.decode(s)
>       File "C:\Miniconda3\lib\json\decoder.py", line 343, in decode
>         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>       File "C:\Miniconda3\lib\json\decoder.py", line 359, in raw_decode
>         obj, end = self.scan_once(s, idx)
>     ValueError: Expecting ',' delimiter: line 883 column 1 (char 68749)

**Comment by kalefranz** [comment]
Unfortunately it looks like your environment is corrupted.  Fixing the root cause of this issue was a major feature of conda 4.3.  Not much more we can do here but advise a re-install and promise this particular issue will never happen again.
