### ISSUE TITLE
conda update --all killed a Win7 64bit installation of anaconda that worked previously

### ISSUE THREAD

**Issue by TheMitchWorksPro** [conda/conda#4160]
It appears that when a poster comments on an issue - the issue closes automatically - that was an accident.  Please see additional comments posted by me.  Issue still open.  Thanks

Background: 
* I had installed Anaconda months ago with a default of Python 3.5 and additional environment of Python 2.7.  This was done on a Windows 7 64 bit laptop w/ 1.4 Ghz processor, 16 Gigs of Ram and ample HD space
* Spyder stopped working for no reason.  only known change between then and now:  Windows updates.
* in attempting to debug this, ran across something that suggested maybe I needed to update my Python 3.5 environment in which it was originally deployed

What happened
* ran "conda update --all" on my 3.5 Python environment
* now that environment is missing from my Jupyter notebook menus 
  ** original environment before uddate blew it away:  
       *** two 3.5 menu items for root 3.5 env:  Python [default] and Python [root]
       *** following normal default install created these menu items for same single environment
       *** after update messed it up, only my Python [Py27] env that I added in post install remained
* and all icons relating to the default 3.5 environment are gone
* and the activate.bat and activate script and missing from the Anaconda3 default env folder
* and anaconda command prompt does not work now (error says the batch file is missing)
* it appears I now cannot use my Anaconda3 env - only the secondary Python 27 env is working

What I would like from you
* Please look into what caused this error.  It is a bad user experience when you take a step that should ensure your environment is up to date and instead it kills your environment

* additional symptoms and notes:
  ** as is documented below, "conda update --all" when ran, produced these error lines at the end of update after updating all or most of my packages:
------------------
Linking packages ...
PaddingError: Placeholder of length '30' too short in package qt-5.6.2-vc14_0.%
The package must be rebuilt with conda-build > 2.0.
-------------------
  ** in addition to all symptoms mentioned above, it seems that when this went bad, it took out my right-click hot menu associations for Git bash (I had git installed on my computer as well).

In the interim:
* problems with Spyder, this bad experience with 3.5, and an upcoming class that will be taught in 2.7 have convinced me to re-install my whole environment this time as a 2.7 distribution with an extra 3.x environment.  I may try 3.6 that I think is out instead of 3.5 - but this behavior is worrisome as it indicates the update command can kill a working distribution.

Here are all the messages from running of "conda update --all" on my environment showing what it did up until the problems occurred:

(C:\ProgramFilesCoders\Anaconda3) C:\Users\Mitch>conda update --all

Package plan for installation in environment C:\ProgramFilesCoders\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2j             |           vc14_0         5.1 MB
    _license-1.1               |           py35_1          56 KB
    boto-2.45.0                |           py35_0         1.6 MB
    contextlib2-0.5.4          |           py35_0          13 KB
    cython-0.25.2              |           py35_0         2.3 MB
    decorator-4.0.10           |           py35_1          14 KB
    filelock-2.0.7             |           py35_0           9 KB
    greenlet-0.4.11            |           py35_0          18 KB
    jdcal-1.3                  |           py35_0           8 KB
    lazy-object-proxy-1.2.1    |           py35_0          27 KB
    llvmlite-0.15.0            |           py35_0         6.2 MB
    lxml-3.7.0                 |           py35_0         1.6 MB
    multipledispatch-0.4.9     |           py35_0          13 KB
    numpy-1.11.2               |           py35_0         3.3 MB
    path.py-9.0.1              |           py35_0          50 KB
    pkginfo-1.4.1              |           py35_0          75 KB
    psutil-5.0.1               |           py35_0         248 KB
    pycparser-2.17             |           py35_0         157 KB
    pytz-2016.10               |           py35_0         174 KB
    pyzmq-16.0.2               |           py35_0         528 KB
    qtpy-1.1.2                 |           py35_0          22 KB
    requests-2.12.4            |           py35_0         791 KB
    setuptools-27.2.0          |           py35_1         761 KB
    sqlalchemy-1.1.4           |           py35_0         1.5 MB
    toolz-0.8.2                |           py35_0          88 KB
    tornado-4.4.2              |           py35_0         593 KB
    werkzeug-0.11.13           |           py35_0         433 KB
    wrapt-1.10.8               |           py35_0          39 KB
    xlsxwriter-0.9.6           |           py35_0         198 KB
    astroid-1.4.7              |           py35_0         258 KB
    astropy-1.3                |      np111py35_0         6.5 MB
    cffi-1.9.1                 |           py35_0         131 KB
    conda-verify-2.0.0         |           py35_0          58 KB
    cytoolz-0.8.2              |           py35_0         275 KB
    gevent-1.2.0               |           py35_0         595 KB
    h5py-2.6.0                 |      np111py35_2         656 KB
    menuinst-1.4.2             |           py35_1         108 KB
    numba-0.30.0               |      np111py35_0         2.0 MB
    numexpr-2.6.1              |      np111py35_1         120 KB
    openpyxl-2.4.0             |           py35_0         274 KB
    pip-9.0.1                  |           py35_1         1.7 MB
    prompt_toolkit-1.0.9       |           py35_0         325 KB
    pytest-3.0.5               |           py35_0         305 KB
    python-dateutil-2.6.0      |           py35_0         234 KB
    qt-5.6.2                   |           vc14_0        56.5 MB
    qtawesome-0.3.3            |           py35_0         153 KB
    scipy-0.18.1               |      np111py35_0        11.7 MB
    traitlets-4.3.1            |           py35_0         124 KB
    xlwings-0.10.1             |           py35_0         742 KB
    anaconda-client-1.6.0      |           py35_0         171 KB
    bokeh-0.12.3               |           py35_1         3.6 MB
    conda-4.2.13               |           py35_0         449 KB
    cryptography-1.7.1         |           py35_0         353 KB
    datashape-0.5.4            |           py35_0         100 KB
    flask-0.12                 |           py35_0         146 KB
    jupyter_core-4.2.1         |           py35_0         106 KB
    pandas-0.19.2              |      np111py35_0         7.3 MB
    pillow-3.4.2               |           py35_0         999 KB
    pylint-1.5.4               |           py35_1         347 KB
    pyqt-5.6.0                 |           py35_1         4.5 MB
    scikit-learn-0.18.1        |      np111py35_0         4.4 MB
    sphinx-1.5.1               |           py35_0         1.4 MB
    anaconda-navigator-1.3.2   |           py35_0         3.1 MB
    conda-build-2.0.12         |           py35_0         355 KB
    dask-0.12.0                |           py35_0         685 KB
    matplotlib-1.5.3           |      np111py35_1         6.2 MB
    nbformat-4.2.0             |           py35_0         125 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    ipykernel-4.5.2            |           py35_0         129 KB
    notebook-4.3.0             |           py35_0         5.3 MB
    qtconsole-4.2.1            |           py35_2         201 KB
    spyder-3.0.2               |           py35_0         3.0 MB
    ------------------------------------------------------------
                                           Total:       151.5 MB

The following NEW packages will be INSTALLED:

    _license:           1.1-py35_1
    astroid:            1.4.7-py35_0
    conda-verify:       2.0.0-py35_0
    lazy-object-proxy:  1.2.1-py35_0
    pkginfo:            1.4.1-py35_0
    pylint:             1.5.4-py35_1
    qtawesome:          0.3.3-py35_0
    wrapt:              1.10.8-py35_0

The following packages will be UPDATED:

    anaconda-client:    1.5.1-py35_0       --> 1.6.0-py35_0
    anaconda-navigator: 1.2.3-py35_0       --> 1.3.2-py35_0
    astropy:            1.2.1-np111py35_0  --> 1.3-np111py35_0
    bokeh:              0.12.2-py35_0      --> 0.12.3-py35_1
    boto:               2.42.0-py35_0      --> 2.45.0-py35_0
    cffi:               1.7.0-py35_0       --> 1.9.1-py35_0
    conda:              4.2.7-py35_0       --> 4.2.13-py35_0
    conda-build:        2.0.1-py35_0       --> 2.0.12-py35_0
    contextlib2:        0.5.3-py35_0       --> 0.5.4-py35_0
    cryptography:       1.5-py35_0         --> 1.7.1-py35_0
    cython:             0.24.1-py35_0      --> 0.25.2-py35_0
    cytoolz:            0.8.0-py35_0       --> 0.8.2-py35_0
    dask:               0.11.0-py35_0      --> 0.12.0-py35_0
    datashape:          0.5.2-py35_0       --> 0.5.4-py35_0
    decorator:          4.0.10-py35_0      --> 4.0.10-py35_1
    filelock:           2.0.6-py35_0       --> 2.0.7-py35_0
    flask:              0.11.1-py35_0      --> 0.12-py35_0
    gevent:             1.1.2-py35_0       --> 1.2.0-py35_0
    greenlet:           0.4.10-py35_0      --> 0.4.11-py35_0
    h5py:               2.6.0-np111py35_0  --> 2.6.0-np111py35_2
    ipykernel:          4.5.0-py35_0       --> 4.5.2-py35_0
    jdcal:              1.2-py35_1         --> 1.3-py35_0
    jupyter_core:       4.2.0-py35_0       --> 4.2.1-py35_0
    llvmlite:           0.13.0-py35_0      --> 0.15.0-py35_0
    lxml:               3.6.4-py35_0       --> 3.7.0-py35_0
    matplotlib:         1.5.3-np111py35_0  --> 1.5.3-np111py35_1
    menuinst:           1.4.1-py35_0       --> 1.4.2-py35_1
    multipledispatch:   0.4.8-py35_0       --> 0.4.9-py35_0
    nbformat:           4.1.0-py35_0       --> 4.2.0-py35_0
    notebook:           4.2.3-py35_0       --> 4.3.0-py35_0
    numba:              0.28.1-np111py35_0 --> 0.30.0-np111py35_0
    numexpr:            2.6.1-np111py35_0  --> 2.6.1-np111py35_1
    numpy:              1.11.1-py35_1      --> 1.11.2-py35_0
    openpyxl:           2.3.2-py35_0       --> 2.4.0-py35_0
    openssl:            1.0.2h-vc14_0      [vc14] --> 1.0.2j-vc14_0      [vc14]
    pandas:             0.18.1-np111py35_0 --> 0.19.2-np111py35_0
    path.py:            8.2.1-py35_0       --> 9.0.1-py35_0
    pillow:             3.3.1-py35_0       --> 3.4.2-py35_0
    pip:                8.1.2-py35_0       --> 9.0.1-py35_1
    prompt_toolkit:     1.0.3-py35_0       --> 1.0.9-py35_0
    psutil:             4.3.1-py35_0       --> 5.0.1-py35_0
    pycparser:          2.14-py35_1        --> 2.17-py35_0
    pyopenssl:          16.0.0-py35_0      --> 16.2.0-py35_0
    pyqt:               5.6.0-py35_0       --> 5.6.0-py35_1
    pytest:             2.9.2-py35_0       --> 3.0.5-py35_0
    python-dateutil:    2.5.3-py35_0       --> 2.6.0-py35_0
    pytz:               2016.6.1-py35_0    --> 2016.10-py35_0
    pyzmq:              15.4.0-py35_0      --> 16.0.2-py35_0
    qt:                 5.6.0-vc14_0       [vc14] --> 5.6.2-vc14_0       [vc14]
    qtconsole:          4.2.1-py35_0       --> 4.2.1-py35_2
    qtpy:               1.0.2-py35_0       --> 1.1.2-py35_0
    requests:           2.11.1-py35_0      --> 2.12.4-py35_0
    scikit-learn:       0.17.1-np111py35_1 --> 0.18.1-np111py35_0
    scipy:              0.18.0-np111py35_0 --> 0.18.1-np111py35_0
    setuptools:         27.2.0-py35_0      --> 27.2.0-py35_1
    sphinx:             1.4.1-py35_0       --> 1.5.1-py35_0
    spyder:             2.3.9-py35_0       --> 3.0.2-py35_0
    sqlalchemy:         1.0.13-py35_0      --> 1.1.4-py35_0
    toolz:              0.8.0-py35_0       --> 0.8.2-py35_0
    tornado:            4.4.1-py35_0       --> 4.4.2-py35_0
    traitlets:          4.3.0-py35_0       --> 4.3.1-py35_0
    werkzeug:           0.11.11-py35_0     --> 0.11.13-py35_0
    xlsxwriter:         0.9.3-py35_0       --> 0.9.6-py35_0
    xlwings:            0.9.3-py35_0       --> 0.10.1-py35_0

Proceed ([y]/n)? y

menuinst-1.4.2 100% |###############################| Time: 0:00:00   3.80 MB/s
Fetching packages ...
openssl-1.0.2j 100% |###############################| Time: 0:00:00   8.63 MB/s
_license-1.1-p 100% |###############################| Time: 0:00:00   2.50 MB/s
boto-2.45.0-py 100% |###############################| Time: 0:00:00   8.10 MB/s
contextlib2-0. 100% |###############################| Time: 0:00:00   1.49 MB/s
cython-0.25.2- 100% |###############################| Time: 0:00:00   7.70 MB/s
decorator-4.0. 100% |###############################| Time: 0:00:00   1.55 MB/s
filelock-2.0.7 100% |###############################| Time: 0:00:00   1.80 MB/s
greenlet-0.4.1 100% |###############################| Time: 0:00:00   1.57 MB/s
jdcal-1.3-py35 100% |###############################| Time: 0:00:00   2.10 MB/s
lazy-object-pr 100% |###############################| Time: 0:00:00   1.87 MB/s
llvmlite-0.15. 100% |###############################| Time: 0:00:01   3.80 MB/s
lxml-3.7.0-py3 100% |###############################| Time: 0:00:00   3.54 MB/s
multipledispat 100% |###############################| Time: 0:00:00   1.32 MB/s
numpy-1.11.2-p 100% |###############################| Time: 0:00:00   4.97 MB/s
path.py-9.0.1- 100% |###############################| Time: 0:00:00   2.12 MB/s
pkginfo-1.4.1- 100% |###############################| Time: 0:00:00   2.95 MB/s
psutil-5.0.1-p 100% |###############################| Time: 0:00:00   4.70 MB/s
pycparser-2.17 100% |###############################| Time: 0:00:00   3.82 MB/s
pytz-2016.10-p 100% |###############################| Time: 0:00:00   3.71 MB/s
pyzmq-16.0.2-p 100% |###############################| Time: 0:00:00   6.28 MB/s
qtpy-1.1.2-py3 100% |###############################| Time: 0:00:00   1.90 MB/s
requests-2.12. 100% |###############################| Time: 0:00:00   6.43 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   5.60 MB/s
sqlalchemy-1.1 100% |###############################| Time: 0:00:00   3.74 MB/s
toolz-0.8.2-py 100% |###############################| Time: 0:00:00   2.92 MB/s
tornado-4.4.2- 100% |###############################| Time: 0:00:00   5.78 MB/s
werkzeug-0.11. 100% |###############################| Time: 0:00:00   4.39 MB/s
wrapt-1.10.8-p 100% |###############################| Time: 0:00:00   2.12 MB/s
xlsxwriter-0.9 100% |###############################| Time: 0:00:00   3.98 MB/s
astroid-1.4.7- 100% |###############################| Time: 0:00:00   3.39 MB/s
astropy-1.3-np 100% |###############################| Time: 0:00:00   8.45 MB/s
cffi-1.9.1-py3 100% |###############################| Time: 0:00:00   3.82 MB/s
conda-verify-2 100% |###############################| Time: 0:00:00   2.30 MB/s
cytoolz-0.8.2- 100% |###############################| Time: 0:00:00   4.09 MB/s
gevent-1.2.0-p 100% |###############################| Time: 0:00:00   1.49 MB/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:00   4.76 MB/s
numba-0.30.0-n 100% |###############################| Time: 0:00:00   3.99 MB/s
numexpr-2.6.1- 100% |###############################| Time: 0:00:00   3.14 MB/s
openpyxl-2.4.0 100% |###############################| Time: 0:00:01 215.99 kB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00   7.33 MB/s
prompt_toolkit 100% |###############################| Time: 0:00:00   5.28 MB/s
pytest-3.0.5-p 100% |###############################| Time: 0:00:00   1.55 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   4.28 MB/s
qt-5.6.2-vc14_ 100% |###############################| Time: 0:00:07   7.73 MB/s
qtawesome-0.3. 100% |###############################| Time: 0:00:00 942.15 kB/s
scipy-0.18.1-n 100% |###############################| Time: 0:00:01   8.03 MB/s
traitlets-4.3. 100% |###############################| Time: 0:00:00   2.89 MB/s
xlwings-0.10.1 100% |###############################| Time: 0:00:00   6.13 MB/s
anaconda-clien 100% |###############################| Time: 0:00:00   1.39 MB/s
bokeh-0.12.3-p 100% |###############################| Time: 0:00:00   8.28 MB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:00   5.97 MB/s
cryptography-1 100% |###############################| Time: 0:00:00   5.08 MB/s
datashape-0.5. 100% |###############################| Time: 0:00:00   2.92 MB/s
flask-0.12-py3 100% |###############################| Time: 0:00:00   3.31 MB/s
jupyter_core-4 100% |###############################| Time: 0:00:00   3.01 MB/s
pandas-0.19.2- 100% |###############################| Time: 0:00:01   6.14 MB/s
pillow-3.4.2-p 100% |###############################| Time: 0:00:00   7.05 MB/s
pylint-1.5.4-p 100% |###############################| Time: 0:00:00   4.93 MB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:00   8.76 MB/s
scikit-learn-0 100% |###############################| Time: 0:00:00   8.31 MB/s
sphinx-1.5.1-p 100% |###############################| Time: 0:00:00   2.20 MB/s
anaconda-navig 100% |###############################| Time: 0:00:00   7.53 MB/s
conda-build-2. 100% |###############################| Time: 0:00:00   5.20 MB/s
dask-0.12.0-py 100% |###############################| Time: 0:00:00   5.01 MB/s
matplotlib-1.5 100% |###############################| Time: 0:00:00   6.55 MB/s
nbformat-4.2.0 100% |###############################| Time: 0:00:00   3.56 MB/s
pyopenssl-16.2 100% |###############################| Time: 0:00:00 986.18 kB/s
ipykernel-4.5. 100% |###############################| Time: 0:00:00   1.33 MB/s
notebook-4.3.0 100% |###############################| Time: 0:00:00   8.19 MB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:00   3.38 MB/s
spyder-3.0.2-p 100% |###############################| Time: 0:00:00   4.18 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
PaddingError: Placeholder of length '30' too short in package qt-5.6.2-vc14_0.%
The package must be rebuilt with conda-build > 2.0.

**Comment by ccordoba12** [comment]
@mingwandroid, here it is this error again. Did you compile Qt 5.6.2 with an old conda-build version?

**Comment by mingwandroid** [comment]
No I didn't. The big here is that Windows conda should not be doing binary prefix relocation.

That big had since been fixed but you need to do `conda update conda` first to get the fixed version.

**Comment by TheMitchWorksPro** [comment]
This problem has now occurred in an Anaconda 4.2 installation using Python 27 as the default.
I added some packages for data science, and got this same error I think because of a dependency
Then the whole environment I had spent hours building got destroyed and I have to start again.
This is very frustrating.  Here is a dump of what I was doing when the problem occurred.  Then ... not shown below ... I tried "conda update conda" (read your post after this problem occurred) ... looked like I got successful results, but then the next command I tried came back as "failed to create process" and now my anaconda prompt won't load and I have to de-install everything and try again ... maybe i needed to try the command immediately after installation before adding any packages of doing conda update --all.  very frustrating

![image](https://cloud.githubusercontent.com/assets/23440318/21592664/44379030-d0dd-11e6-97da-f8ed1d046b68.png)

**Comment by TheMitchWorksPro** [comment]
The recommendation to use conda update conda ahead of the changes that may have fried my system appears that it might be right. I am finding other issues the need more urgent attention filed separately, so closing this one.  Thanks for the help and input so far.
