### ISSUE TITLE
Trash clean up still very slow for various operations

### ISSUE THREAD

**Issue by mparry** [conda/conda#4164]
In either conda 4.2.13 or 4.3.1, various operations tend to hang for a long time after they've completed. This appears to still be because of the exponential back-off for retries in the trash clean up code, and every now and then during this hang (under 4.3.1) it will spit out a series of errors like this:

`WARNING conda.gateways.disk:exp_backoff_fn(45): Uncaught backoff with errno 41`

(41 is `ENOTEMPTY` of course.)

I wrote about this in my last couple of comments on #3664 and I'll just summarise that here:

1. I still find it necessary to hack `MAX_TRIES` (now in gateways.disk.\_\_init\_\_.py) to 1 to get all operations to perform reasonably.
2. I think in some cases the retries will never succeed (under Windows).
3. It's not clear to me why retries are desirable at all, and there's no way of suppressing them other than by hacking at the code. 

Let me know if you need any further info.

**Comment by dhirschfeld** [comment]
Have just updated to 4.3.5 (on win64) and am seeing lots of warnings printed and long delays before conda exits.

From my point of view I want conda to be fast and I don't much care if it leaves trash lying about. It would be nice if it didn't but I don't want to sit about waiting whilst it futilely reattempts the same operation multiple times.

Windows likes to hang on to references to files so trying to delete them can often fail. In my experience when that happens you can try and track down the program holding a reference and kill it, use a file unlocker tool or reboot your computer and reattempt the operation. The point is that if the operation failed it will continue to do so unless you actually do something to fix the underlying issue. Simply waiting increasing long periods of time will never work so applying that concept to deleting files on windows won't get you anything except long delays. Where it does make sense is in something like web requests / network communication where you can get intermittent interruptions but have some hope that they will be resolved and future attempts may be successful.

Concrete suggestions:
  1. Set the default max retries for all delete operations to 0 (at least on windows)
  2. On any conda operation try to clean up trash left previously but fail *fast* (no retries)
  3. Add an explicit `conda clean --trash` command to allow cleaning of leftover trash to be run on demand
  4. Allow max retries to be configurable a the command line

http://www.howtogeek.com/128680/how-to-delete-move-or-rename-locked-files-in-windows/

**Comment by kalefranz** [comment]
Has this improved in later patch releases of conda 4.3?  We're at 4.3.17 now...

**Comment by dhirschfeld** [comment]
TBF I haven't been noticing the long delays recently so maybe it has been fixed?
