### ISSUE TITLE
error due to proxy server

### ISSUE THREAD

**Issue by trileycac** [conda/conda#4170]
I am brand new to python, and am the first person in my company to try and use it behind our firewall/proxy server and am running into issues after installing anaconda.

when i run a simple, "conda update conda" this is what i'm getting (see attached) 

any help would be greatly appreciated. Thanks

Attachment:
![conda](https://cloud.githubusercontent.com/assets/24901462/21621486/3ec24b6e-d1c7-11e6-807c-c92a33aef815.png)

**Comment by kalefranz** [comment]
Future resolution of proxy interaction bugs will be tracked via #5220
