### ISSUE TITLE
Creating environments in Anaconda 4.2 duplicates icons to all applications

### ISSUE THREAD

**Issue by TheMitchWorksPro** [conda/conda#4171]
Machine:  Windows 7 w/ 16 Gigs RAM
Anaconda Version:  saw this in 4.1, but it is more pervasive in 4.2

What happens:  

Use anaconda commands to either create new environments or add notebook kernels to your Jupyter menus (through command line or through GUI for environment creation) and it creates either a full set of Anaconda icons for each environment or duplicates only some of the Anaconda application icons.  However, only root environment is hooked to these applications, so these are just ghosts icons.  Some of the icons crash when you load them (icons generated in connection with R environments).  Others are just renamed versions of what you already have (but named for each environment).

Add environment with the GUI and this happens every time.  This is true both with the online Jupyter GUI and the new Anaconda Navigator GUI.  Further, more duplicates get created when you use "conda update --all" (or update packages that trigger this - not sure exactly which ones yet).

From command line, it usually happens when you add a Notebook Kernel menu for an environment but sometimes happens during creation as well.

I was running tests on a broken environment trying to shake some stuff out before I will blow it away and re-install fresh to get it right.  These screenshots show this symptom:

![image](https://cloud.githubusercontent.com/assets/23440318/21624582/b498981c-d1d5-11e6-859d-7a1559d4a456.png)

(root) C:\Users\Mitch>conda info --envs
# conda environments:
#
BioPy                    C:\ProgramFilesCoders\Anaconda2\envs\BioPy
Py27tst                  C:\ProgramFilesCoders\Anaconda2\envs\Py27tst
Py2tst2                  C:\ProgramFilesCoders\Anaconda2\envs\Py2tst2
Py3tst                   C:\ProgramFilesCoders\Anaconda2\envs\Py3tst
Python3                  C:\ProgramFilesCoders\Anaconda2\envs\Python3
root                  *  C:\ProgramFilesCoders\Anaconda2

(root) C:\Users\Mitch>python -m ipykernel install --user --name Py2tst2 --displa
y-name "Python (Py2tst2)"
Installed kernelspec Py2tst2 in C:\Users\Mitch\AppData\Roaming\jupyter\kernels\p
y2tst2

(root) C:\Users\Mitch>python -m ipykernel install --user --name Py3tst --display
-name "Python (Py3tst)"

Installed kernelspec Py3tst in C:\Users\Mitch\AppData\Roaming\jupyter\kernels\py
3tst

More Notes on this behavior:

Blew away above environment because of an unrelated problem.  Rebuilt Anaconda fresh with a new set of environments.  In the screenshots that follow, after icons were created, I moved them into a folder to make it easier to see my main ones from all the ones Anaconda built.  Due to all the scenarios under which it builds these icons (create env / add menu item / update environment packages) - you can see the list of icons getting quite large.  of interest - to solve another problem, just built an environment with Python 3.5 and R from Anaconda Navigator - you can see it only added 2 icons for that one though it added all or just one or two for some of the others. 

Icons:

![image](https://cloud.githubusercontent.com/assets/23440318/21755967/ee76a7e2-d5e8-11e6-8cb7-339ed676ec40.png)

![image](https://cloud.githubusercontent.com/assets/23440318/21755974/1c926d0a-d5e9-11e6-9e47-85a688cd4517.png)

Environments on Anaconda Navigator:

![image](https://cloud.githubusercontent.com/assets/23440318/21755990/55310856-d5e9-11e6-8282-bb63ca8b5438.png)

**Comment by ijstokes** [comment]
Also reported in https://github.com/ContinuumIO/anaconda/issues/803 (private repo issue) -- @csoja or @msarahan is this resolved in 4.4?

**Comment by jaircastruita** [comment]
Is there any way to make environments without creating this icons automatically?

**Comment by kalefranz** [comment]
conda config --set shortcuts false
