### ISSUE TITLE
pinning still results in reinstall from another channel

### ISSUE THREAD

**Issue by bkreider** [conda/conda#4181]
Even though conda is pinned, because I'm pulling from conda-forge, it tries to reinstall the same pinned version from conda-forge.  I REALLY don't want conda from conda-forge.  This makes it extremely difficult for me to use conda-forge without ending up in package hell.  I only want the package i'm asking for from supplemental channels.  

```
conda install protobuf=3.0 -c conda-forge
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /opt/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.2.13               |           py27_0         375 KB  conda-forge
    protobuf-3.0.0             |           py27_0         6.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.0 MB

The following packages will be UPDATED:

    protobuf: 2.6.1-py27_1  defaults --> 3.0.0-py27_0  conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:    4.2.13-py27_0 defaults --> 4.2.13-py27_0 conda-forge

Proceed ([y]/n)? n
```

**Comment by kalefranz** [comment]
Turns out this is probably the behavior we actually want going forward.  You'll be able to specify a channel to pin to if you want, when you specify the rest of the pin (I know you can't right now, soon).

To keep conda for switching out,

    conda config --set auto_update_conda false
