### ISSUE TITLE
when I use the  "conda create -n tensorflow python=3.5", I met the following errors .Can someone help me fix it?Your kind heart will be appreciated.

### ISSUE THREAD

**Issue by yingning** [conda/conda#4203]
(F:\Anaconda\anaconda3) C:\Windows\system32>conda create -n tensorflow python=3.5
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment F:\Anaconda\anaconda3\envs\tensorflow:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2015_runtime-14.0.25123  |                0         1.9 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python-3.5.2               |                0        30.3 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    setuptools-27.2.0          |           py35_1         761 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    wheel-0.29.0               |           py35_0         123 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pip-9.0.1                  |           py35_1         1.7 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    ------------------------------------------------------------
                                           Total:        34.8 MB

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python:         3.5.2-0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    setuptools:     27.2.0-py35_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    vs2015_runtime: 14.0.25123-0  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    wheel:          0.29.0-py35_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)?

Pruning fetched packages from the cache ...
Fetching packages ...
vs2015_runtime 100% |###############################| Time: 0:00:00   2.22 MB/s
python-3.5.2-0 100% |###############################| Time: 0:01:13 430.31 kB/s
setuptools-27. 100% |###############################| Time: 0:00:01 707.33 kB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00 767.74 kB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:04 387.53 kB/s
Extracting packages ...
An unexpected error has occurred.                                        |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : F:\Anaconda\anaconda3  (writable)
    default environment : F:\Anaconda\anaconda3
       envs directories : F:\Anaconda\anaconda3\envs
          package cache : F:\Anaconda\anaconda3\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\pengyong\.condarc
           offline mode : False

`$ F:\Anaconda\anaconda3\Scripts\conda-script.py create -n tensorflow python=3.5`

    Traceback (most recent call last):
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "F:\Anaconda\anaconda3\lib\site-packages\conda\install.py", line 801, in extract
        t.extractall(path=temp_path)
      File "F:\Anaconda\anaconda3\lib\tarfile.py", line 1996, in extractall
        numeric_owner=numeric_owner)
      File "F:\Anaconda\anaconda3\lib\tarfile.py", line 2038, in extract
        numeric_owner=numeric_owner)
      File "F:\Anaconda\anaconda3\lib\tarfile.py", line 2108, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "F:\Anaconda\anaconda3\lib\tarfile.py", line 2148, in makefile
        with bltn_open(targetpath, "wb") as target:
    PermissionError: [Errno 13] Permission denied: 'F:\\Anaconda\\anaconda3\\pkgs\\vs2015_runtime-14.0.25123-0.tmp\\Library\\bin\\ucrtbase.dll'

**Comment by yingning** [comment]
I input the instructions in anaconda prompt without using administrator permission. What problem is it?

**Comment by kalefranz** [comment]
Conda 4.3 has solved multi-user permissions problems.  Please update to conda 4.3.  And if you continue to have problems, please file a new issue with the new stack trace.
