### ISSUE TITLE
Anaconda Navigator -> Install RStudio --> Does not work

### ISSUE THREAD

**Issue by TheMitchWorksPro** [conda/conda#4204]
Environment:  I installed Anaconda 4.2 (most current download) with default environment that is Python 2.7, and additional environments including Python 3.6 and R.  My laptop is Windows 7 64 bit.

Problem:  From Anaconda Navigator, I attempted to click the R Studio Install button and it did not work. Screen shots and conda command output is provided to help with debugging.  But I came to realize that having rebuilt this environment 3 times already due to other issues, I don't want to risk breaking it again with trial and error experiments and I don't know enough about how to proceed.    

related questions:
Is the icon smart enough to install to my R environment and not my Python root?  If it installs to root, does that mean it puts R in the root along with Python?  How will the Notebook kernel react to that?  My root environment has VS2008_runtime.  Should this be replaced with "VS2015_runtime" ?  (see conda package info provided later in this post.  In short - how do I fix this?

![image](https://cloud.githubusercontent.com/assets/23440318/21707657/34d46ba8-d39f-11e6-9bf1-ccb18b566dc6.png)

Tried running package info on rstudio:

(C:\ProgramFilesCoders\Anaconda2) C:\Users\Mitch>conda info rstudio
Fetching package metadata ...........

rstudio 1.0.44 vc14_1
---------------------
file name   : r::rstudio-1.0.44-vc14_1.tar.bz2
name        : rstudio
version     : 1.0.44
build number: 1
build string: vc14_1
channel     : r
size        : 67.4 MB
app_entry   : ${PREFIX}/Library/bin/rstudio.exe
app_type    : desk
arch        : x86_64
binstar     : {u'package_id': u'58335c5dda6c9911120d1fb1', u'channel': u'main',
u'owner_id': u'52c5dc11f53f2a0b1a9de428'}
features    : vc14
fn          : rstudio-1.0.44-vc14_1.tar.bz2
has_prefix  : True
icon        : c839dc03e5d17d3cd61dbf23ae3ca88b.png
license     : Commercial or AGPLv3
license_family: GPL
machine     : x86_64
md5         : 0fafc9ba23a5ad2e70efa47eb5ebdcca

operatingsystem: win32
platform    : win
priority    : 0
schannel    : r
subdir      : win-64
summary     : A set of integrated tools designed to help you be more productive
with R
target-triplet: x86_64-any-win32
type        : app
url         : https://conda.anaconda.org/r/win-64/rstudio-1.0.44-vc14_1.tar.bz2
dependencies:
    m2-openssh
    m2w64-diffutils
    m2w64-grep
    qt >=5.6
    r-essentials
    vs2015_runtime

**Comment by mingwandroid** [comment]
You cannot use RStudio for Windows in a Python 2 environment, you must use it in a Python 3 one instead. This is because of how the visual studio runtime versions differ between the three packages.

Please create a Python 3 environment and install RStudio into that instead.

**Comment by mingwandroid** [comment]
As for whether RStudio is installed into your R environment, I am not sure, but if it were, then I do not think you would have run into this issue. I think the forthcoming `Anaconda Navigator` release may contain some changes around this behaviour though? @goanpeca will know better.

**Comment by TheMitchWorksPro** [comment]
Just saw these comments and thanks for checking in.  If you use the RStudio icon - how do you tell it which environment to use?  I already have a Python 3.6 environment, but clicking the icon triggers the error.  Alternatively, I am trying to find guidance on the web for how to install RStudio myself (not use Anaconda Navigator) and point it to my Anaconda R environment, but so far, I only found an incomplete topic written for a Mac and as stated in this write-up, my system is Windows 7 64 bit.  If there is a way to get Anaconda Navigator icon to do this great.  If not - is there a way install RStudio from RStudio website and tell it to use an environment of Anaconda that is not my root environment?  Adding further confusion to this ... RStudio obvisouly needs the R language.  When I first created R environments on Anaconda using Navigator, I then went to test them on Jupyter Notebooks and they only partially recognized code and threw errors for other lines from a sample I got off the web.  I then ran "conda update --all" in the R environment and then my notebook of R code (from the web) worked.  But when I listed the environment, i noticed it added a whole bunch of Python 2.7 packages to it (probably because that is the default installation in my root).  If R needs a 3.x environment for RStudio install - how do I create the combined environment of R/Python3.6 on an Anaconda2 installation (default env of PYthon 2.7) ?  stuck on how to proceed here other than to ignore Anaconda altogether and just do a fresh install of R and RStudio in another directory assuming that doesn't create some kind of environment variable conflict.

**Comment by TheMitchWorksPro** [comment]
In case it helps with debugging this issue, including a list of all packages across all my environments.  If anyone has ideas about how to get past this so RStudio will install to correct environment and/or what I need to do to update one of these to proper to specs for it it would be appreciated.  I know this is issue reporting, but until the icon on Anaconda Navigator is fixed, these instructions may also need to be added to documentation for Anaconda 4.2.  Thanks in advance for any help.

[anaconda_envs_list.txt](https://github.com/conda/conda/files/690132/anaconda_envs_list.txt)

**Comment by goanpeca** [comment]
@TheMitchWorksPro you can create a new environment on the environments tab. Once this environment is installed you can go back to Home and select from the combobox the new environment and then install for RStudio. This will install the application on that specific environment instead of root.

----

@mingwandroid I was not aware of the Py2 limitation for R, I think we will need to handle this specific case in a better way. (Provide some info on this...)

Could you please open an issue on the Navigator repo with any additional comment you want to add?

**Comment by TheMitchWorksPro** [comment]
re:  minwandroid's comments:  

Sorry but I am new to all of this - could you give me a link to the navigator rep?  
I tried looking here but do not see a navigator repo:
https://github.com/conda/ 

Get me that and I will then close this issue and open one there as I think you are suggesting.  Regarding earlier comments:  After two installations went bad on me for different reasons, I discovered Navigator and I do think it's a great application - just needs a few fixes.  When you build an environment:  you're only choices are Python 2, Python 3 and R -- where highest versions allowed are Python 2.7 and Python 3.5.  To create a Python 3.6 environment, I was able to do this by using Jupyter --> conda tab where it does not tell you what version is is building (just says Python 3) but then builds an environment in Python 3.6.  I was then able to clone this environment on Navigator as a backup.  Oddly though - running "conda update --all" to ensure all packages were up to date added some Python 27 packages to my R environments.

**Comment by goanpeca** [comment]
Hi @TheMitchWorksPro the comment for the issue was aimed for @mingwandroid  :-).

The navigator repo is private so for all anaconda distribution related issues the correct repo is https://github.com/ContinuumIO/anaconda-issues/issues

Now regarding:

> To create a Python 3.6 environment, I was able to do this by using Jupyter --> conda tab where it does not tell you what version is is building (just says Python 3) but then builds an environment in Python 3.6. I was then able to clone this environment on Navigator as a backup. Oddly though - running "conda update --all" to ensure all packages were up to date added some Python 27 packages to my R environments.

Python3.6 is available but some packages have not yet been packaged for py36. The new version of Navigator will include support for 2.7 3.5 and 3.6 and drop official support for 3.4.

**Comment by TheMitchWorksPro** [comment]
Will move this there shortly.  One more question --> to re-try RStudio button:  are you saying I should build an R environment and it will then know to install there (it does not ask what environmet user wants to use when you click it)?  

Do I have to blow away my existing ones as described earlier due to their current state (see notes in my earlier comment).  What is my step by step?  There is also an option to build an environment with R and Python in it and select the version of Python but I did not try that (on env tab).  

Earlier comment has output of all environments that exist on in my installation with lists of what packages they contain.  It shows that before I ever hit the RStudio button I had 2 R environments already as described.

Can you give me a step-by-step on what you intend for me to try?  If I can help us both by getting you results of the effort and myself since this gets closer to how do we make RStudio button work so much the better.

**Comment by goanpeca** [comment]
You can install applications in specific environments by selecting the environment on the combobox of the home screen.

**Comment by TheMitchWorksPro** [comment]
Thanks for above!  Did not realize the UI worked that way (was expecting selection to be made after clicking the button not before).  Still need a few more answers before I can move forward with testing the work-around but closing this issue and moving to here as suggested:

https://github.com/ContinuumIO/anaconda-issues/issues/1337

**Comment by xlong2** [comment]
I hope this can be a more pronounced notification in anaconda installation page. I wasted 2 days trying to find ways to work around and finally abandon my attempt to use anaconda installed R with Rstudio. I simply can't have the plot to function in Rstudio.

**Comment by mingwandroid** [comment]
Please give specifics for what happened. I believe this should all be handled for you by Navigator.

**Comment by TheMitchWorksPro** [comment]
@xlong2 - it may be advisable to open a new issue with full details of what went wrong with your installation. Though I also gave up and installed RStudio outside of Anaconda, my issues are now a year old and new releases have come out since then. I believe this issue thread was also closed a year ago.
