### ISSUE TITLE
Proposal: environment.lock.yml files

### ISSUE THREAD

**Issue by tcwalther** [conda/conda#4205]
It would be great if the `conda` tool gained support for `environment.lock.yml` files. These files should be the auto-generated equivalent to the `environment.yml` file, just like the `Gemfile.lock` file is the auto-generated equivalent to the `Gemfile` in Ruby-land.

The `environment.lock.yml` file would fix version numbers of all packages used in this project. I believe that the output of `conda env export` is mostly sufficient for this, except that the `prefix:` entry should be omitted.

I would propose to [copy the behaviour from bundler](http://bundler.io/v1.3/man/bundle-install.1.html#DESCRIPTION) regarding what to do if a lock file exists or doesn't, and what to do if the lock file and the regular environment file are out of sync. I also believe that bundler's [conservative updating](http://bundler.io/v1.3/man/bundle-install.1.html#CONSERVATIVE-UPDATING) is an approach that `conda` should mimic.

I propose that this functionality is incorporated into `conda env create`. This means that you can re-run `conda env create` even when an environment with the same name already exists. This would be a departure of current behaviour - currently, `conda env create` aborts with an error if an environment with the same name already exists.

I would further propose that `conda env update` updates all dependencies based on `environment.yml` (like it currently does), and also updates the `environment.lock.yml` accordingly, just like `bundle update`. This should not introduce any breaking changes.

The discussion around [Pipfile](https://github.com/pypa/pipfile) shows that this problem is still a concern in Python land. It would be great if Anaconda gained such functionality.

**Comment by mivade** [comment]
It would also be useful to have a way to create a conda environment file from a `Pipfile`. This should be rather trivial, though I'm not sure how it would be best implemented (perhaps adding a `conda env import` command?).

**Comment by kalefranz** [comment]
Definitely something on our list.  Check out all issues tagged with https://github.com/conda/conda/labels/tag%3Aenvironment-spec.  We know we have work to do here.
