### ISSUE TITLE
cannot install scikit-learn

### ISSUE THREAD

**Issue by jerryfanjiahao** [conda/conda#4213]
Firstly,I am ready to update scikit-learn,but failed.So I removed the existed scikit-learn package and installed the latest version of scikit-learn using the command "conda install scikit-learn". But failed. The details are as follows.

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : D:\Anaconda2  (writable)
    default environment : D:\Anaconda2
       envs directories : D:\Anaconda2\envs
          package cache : D:\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ D:\Anaconda2\Scripts\conda-script.py install scikit-learn`

    Traceback (most recent call last):
      File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _mai
n
        exit_code = args.func(args, p)
      File "D:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80,
in execute
        install(args, parser, 'install')
      File "D:\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in i
nstall
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not ope
n u'D:\\Anaconda2\\pkgs\\scikit-learn-0.18.1-np111py27_0.tar.bz2.part' for writi
ng (("Connection broken: error(10054, '')", error(10054, ''))).

**Comment by kalefranz** [comment]
Intermittent HTTP error.
