### ISSUE TITLE
new install issue

### ISSUE THREAD

**Issue by macmanes** [conda/conda#4214]
any help appreciated..

Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/macmanes/.linuxbrew/Cellar/python/2.7.12_3  (writable)
    default environment : /home/macmanes/.linuxbrew/Cellar/python/2.7.12_3
       envs directories : /home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/envs
          package cache : /home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/macmanes/.linuxbrew/bin//conda install --file /proc/self/fd/11`

    Traceback (most recent call last):
      File "/home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/macmanes/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7fa6eb5963d0>

**Comment by rth** [comment]
@macmanes On my system `/proc/self/fd/11` symlinks to a file within `/dev/pts/` i.e. a pseudo terminal, which is not a requirement file as it's expected by conda. Unless I missed something?

**Comment by kalefranz** [comment]
Are you still having this issue with recent versions of conda?  Latest is 4.3.17.  I believe we fixed this a while ago.

**Comment by kalefranz** [comment]
I believe this issue has been fixed.
