### ISSUE TITLE
conda build causes different compiler flags being used

### ISSUE THREAD

**Issue by twiecki** [conda/conda#423]
I try to compile pymc on OSX. If I just run `python setup.py` build it works fine, but `conda build` of the same package produces an error. The `build.sh` does nothing more: https://github.com/fonnesbeck/conda-recipes/blob/master/pymc/build.sh

I tracked it down to different compile flags being set, manually calling `setup.py` produces gfortran being called with these flags, among others:

`/usr/bin/gfortran -Wall -m64 -Wall -undefined dynamic_lookup -bundle`

While conda build which also just calls setup.py omits some necessary flags:
`/usr/bin/gfortran -Wall -arch x86_64`

Why would the flags be different between these two?

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1997
