### ISSUE TITLE
Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/

### ISSUE THREAD

**Issue by omshinde** [conda/conda#4232]
Hello! 
I am trying to install geojson in my anaconda. But, the following error persists:
`Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/`

conda info:
Current conda install:
```
platform : win-64
        conda version : 3.2.0a1
       python version : 2.7.12.final.0
     root environment : C:\Users\pc\Anaconda2  (writable)
     default environment : C:\Users\pc\Anaconda2
     envs directories : C:\Users\pc\Anaconda2\envs
        package cache : C:\Users\pc\Anaconda2\pkgs
         channel URLs : https://conda.binstar.org/conda-canary/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\pc\.condarc
    is foreign system : False
```
This may be a very small error but I am unable to find a solution. Please help.
Thanks
Rajat

**Comment by kalefranz** [comment]
You're using `conda version : 3.2.0a1`.  The current conda version is `4.2.14`.  Please update conda.

    conda update conda

Would be the easiest, but with a conda version that old, you may just need to download a new miniconda and install on top of your current installation.

**Comment by omshinde** [comment]
Thank you for your help @kalefranz .
