### ISSUE TITLE
non json output on root clone

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#4235]
I understand that cloning root env is probably a not very good idea... but even then with the json flag, we get this non json output

```
$ conda create -n rootclone --clone root --json`
The following packages cannot be cloned out of the root environment:
 - conda-build-2.0.2-py35_0
 - conda-4.2.13-py35_0
... (valid Json output)
```

Possible fixes according to @kalefranz 

- Send that output to stderr
- Just eat that output
- Please fill in with your suggestion ...

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/4241
