### ISSUE TITLE
cannot import conda.fetch.cache_fn_url

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#4247]
I'm using conda 4.3.2, and the function `conda.fetch.cache_fn_url` does not exist anymore.  What to do?

**Comment by kalefranz** [comment]
`conda.core.index.cache_fn_url`

**Comment by ilanschnell** [comment]
Thanks.  Nevertheless, this is yet another example of something I've been relying on for years is suddenly changing underneath me, and which is also I mostly rely on the "never to be changed" `libconda` package :-)

**Comment by mcg1969** [comment]
None of us is exempt from the admonition against relying on conda's private APIs.

**Comment by ilanschnell** [comment]
That's true @mcg1969.  I have actually been the person always saying not to use conda as a library, but I did it myself for convenience because I was very familiar with what I wrote.

**Comment by ilanschnell** [comment]
I'm not complaining, this change is not hard for me to make, but there are other people (in particular the maintainers of `conda-build` and `anaconda-navigator`), which rely intensely on the private API, for historical reasons.

**Comment by ilanschnell** [comment]
The location changed again.  In 4.3.13 it is `conda.core.repodata.cache_fn_url()`.  Why do these things get moved around?

**Comment by kalefranz** [comment]
@ilanschnell I've added it to `conda/exports.py` in #4729.  For all of your code that does `import conda`, try to confine the imports to `import conda.exports`.  That module is far more stable than the rest of the code base.  All of conda-build's imports are going through that module.  

conda-build is also isolating all of it's conda imports to a single location: https://github.com/conda/conda-build/blob/master/conda_build/conda_interface.py

And then the rest of the conda-build code imports everything through there.  That pattern has dramatically improved conda + conda-build inter-stability.

**Comment by ilanschnell** [comment]
Thanks for the prompt response.  Not a big deal.
