### ISSUE TITLE
_'s in versions are not accepted by conda 4.3

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#4263]
I think this needs to be considered a blocker for 4.3 as it means that environments which were previously considered OK are now not OK.

When `conda skeleton cran` fetches r-packages from CRAN it replaces any `-` in the version with `_` (and helpfully puts a comment to that effect in the recipe), e.g.:

```
package:
  name: r-bit
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1_12"
```

and also in the dependencies we also see such versions:

```
requirements:
  build:
    - r-base
    - r-bit >=1.1_12
```

Now, when conda is asked to install such dependencies I am getting:
```
failed to parse packages from exception: Value error: invalid package specification: r-bit=>=1.1_12
```

**Comment by mcg1969** [comment]
Agreed, this is a problem. It's possible I broke it in my attempt to normalize on the use of `arg2spec`.

**Comment by mcg1969** [comment]
I'm having trouble reproducing this. Specifically, I'm finding that `conda install r-bit=>=1.1_12` is failing with 4.1, 4.2, and 4.3. And frankly, it should, because that's not a well-formed version spec.

So the challenge here is trying to figure out who and what is _producing_ this faulty MatchSpec. For that I need a bit more help reproducing this. Can you offer me the exact `conda` command that you're trying to use that runs into this error on 4.3, but _not_ on earlier versions?

**Comment by mingwandroid** [comment]
Yeah, don't copy the text of the error message, make a recipe:

```
requirements:
  build:
    - r-base
    - r-bit >=1.1_12
```

I'll knock one up now.

**Comment by mingwandroid** [comment]
```
package:
  name: test-pkg

requirements:
  build:
    - r-base
    - r-bit >=1.1_12
```

```
conda-build .
updating index in: /Users/rdonnelly/mc-x64-3.5/conda-bld/noarch
updating index in: /Users/rdonnelly/mc-x64-3.5/conda-bld/osx-64
failed to parse packages from exception: Value error: invalid package specification: r-bit=>=1.1_12
```

**Comment by mingwandroid** [comment]
Adding `--debug` to the command-line I get:

```
DEBUG conda.cli.main:_main(95): conda.cli.main called with ('create', '--debug', '-yp', '/Users/rdonnelly/mc-x64-3.5/conda-bld/test-pkg_1484091709359/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho', 'r-base=3.3.1*', 'r-bit=>=1.1.12')
```

so it looks to be a conda-build bug, sorry about the noise!

**Comment by mingwandroid** [comment]
Re-opening until I have more certainty.

**Comment by mingwandroid** [comment]
Changing from `>=1.1_12` to `>=1.1.12` doesn't make this issue go away, so `_` is a red-herring.

**Comment by mingwandroid** [comment]
@msarahan says it's known and in conda-build so closing.
