### ISSUE TITLE
Problem trying to install netcdf4 from conda-forge

### ISSUE THREAD

**Issue by gcreager** [conda/conda#4272]
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.7
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /scratch/software/anaconda  (writable)
    default environment : /scratch/software/anaconda
       envs directories : /scratch/software/anaconda/envs
          package cache : /scratch/software/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /scratch/software/anaconda/bin/conda install -c conda-forge netcdf4`

    Traceback (most recent call last):
      File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7f7805dd3ad0>

**Comment by jakirkham** [comment]
Maybe worth raising at the feedstock as well (or only).

ref: https://github.com/conda-forge/netcdf4-feedstock

**Comment by kalefranz** [comment]
Can you reproduce the error in python 3 environment? Python 2 doesn't chain stack traces, so we're actually notseei g the root cause of the error.

**Comment by kalefranz** [comment]
Regardless, this logic has been completely reworked in conda 4.3. The code in this area in particular is dramatically different now.
