### ISSUE TITLE
Permission Errors in create_link

### ISSUE THREAD

**Issue by groutr** [conda/conda#4273]
This might be a bug in conda, but definitely a bug in packaging.  But it complicates the multi-user feature of conda-4.3.  The latest anaconda 4.2.0 release is not compatible with the multi-user cache features.

The packaging bug is summarized here.
https://github.com/ContinuumIO/anaconda-issues/issues/1301

On the conda side: create_link doesn't seem to account for permissions errors (or, maybe that handling happens at a different level).  Should there be some error handling here to account for the situation described in https://github.com/ContinuumIO/anaconda-issues/issues/1301? Conda could even check during the extraction phase that all files are world readable, and if not inform the user and change the permissions to world-readable.

Or, as the poster in 1301 suggests, maybe such info should be given to the packager at the conda-build level, ensuring that all files in a package are world-readable and warning the packager that the resulting package may not be usable in multi-user environments.

**Comment by kalefranz** [comment]
I don't think this is a problem conda can or should solve at install time.  It's possible that a package builder might want non-world-readable permissions, and I don't think conda should override that.  Seems easy enough to solve at the package level.  Thanks for the report though.
