### ISSUE TITLE
ENH: add --force option to conda env create

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#4274]
Both conda env create and conda create need a --force option that will overwrite the environment if it already exists.

conda could warn the user and prompt for confirmation but must also allow for --yes option to not prompt so conda can be used effectively in automation scripts that won't have human interaction.

**Comment by kalefranz** [comment]
FWIW, the `--mkdir` flag on `conda install` creates a new environment if it doesn't already exists.  Depending on your use case, it might be a close alternative that will work just as well.

**Comment by honnibal** [comment]
+1 on this. In general I've been having a really hard time using conda with automation.

* You can't install it via package manager
* There are tonnes of prompts you have to -y through (plus the non-obvious `-b` in the install script)
* Ubuntu has dash shell by default, which breaks environment activation
* No idempotent way to create environments

It seems like provisioning servers should be an important use-case, but using the tool it feels like not much thought has gone into this?
