### ISSUE TITLE
BUG: cannot source deactivate env with conda installed in it

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#4275]
Create an env with a name that begins with an underscore (i.e. _myenv) and install conda in the env.
source activate the env
try to source deactivate the env and conda won't deactivate back to the root env.

It appears that since conda is installed in the env conda thinks the env is the root env when it isn't.
They is no way to source deactivate back to the real root env.

condo version 4.2.13

**Comment by kevinzzz007** [comment]
@joelhullcio I have a similar problem, I created an env with a name that does not start with an underscore, first I can successfully activate this env, but when I type `source deactivate` when inside the env, I get an error as the following `/Users/MyName/anaconda3/envs/EnvName/bin/deactivate:81: no such file or directory: /Users/MyName/anaconda3/envs/EnvName/bin/python`, I looked at the `/Users/MyName/anaconda3/envs/EnvName/bin` directory and there is no python file in this directory, and after I typed the `source deactivate` command, my command prompt seems to be back to normal, but then the command prompt can't recognize simple commands like `ls`...

my conda version is 4.3.4

**Comment by kalefranz** [comment]
If not already fixed, definitely resolved with #5044 for conda 4.4.
