### ISSUE TITLE
conda crashes in cryptography package with: "AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'"

### ISSUE THREAD

**Issue by capybaralet** [conda/conda#4280]
(cross posted on [the conda user group](https://groups.google.com/a/continuum.io/forum/#!topic/conda/dhG4J7h4Iz0))

conda doesn't seem to work at all anymore, and crashes whenever I try to use it.

I updated conda in one shell while I had an environment active in another shell.
Afterwards, I did 

    source deactivate

in the shell where the environment was active.  That lead to an error like this (not sure it's exactly the same as what I saw, because I rebooted and lost the trace):

davids-air-3:david david$ conda --help
Traceback (most recent call last):
  File "/Users/david/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 165, in main
    return conda_exception_handler(_main, *args)
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 426, in print_unexpected_error_message
    from conda.base.context import context
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.disk import try_write, conda_bld_ensure_dir
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/common/disk.py", line 16, in <module>
    from ..utils import on_win
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/utils.py", line 11, in <module>
    from .common.url import path_to_url
  File "/Users/david/anaconda/lib/python2.7/site-packages/conda/common/url.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import LocationParseError
  File "/Users/david/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/david/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/david/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'

**Comment by kalefranz** [comment]
Do you mind sharing the output of `conda list`?
I'm looking for versions of conda, requests, pyopenssl, and all dependencies.

**Comment by kalefranz** [comment]
Going to close this issue.  In touch via email.  I'll have that miniconda installer for you soon.

**Comment by robclewley** [comment]
@kalefranz I have the same problem -- I can no longer run conda at all. I suspect things got messed up attempting to install the google cloud api in my anaconda 4 / py 2.7 pyenv.

I see a suggested solution involving miniconda [here](http://conda.continuum.narkive.com/lwYGsuAu/conda-crashes-in-cryptography-package-with-attributeerror-module-object-has-no-attribute-init-cffi) but I don't know how specific that suggestion was to the results of the ls output for that user, so I didn't want to blindly try it. 

Here's my contents of my pyenv's conda-meta:

```
alabaster-0.7.7-py27_0.json
anaconda-client-1.4.0-py27_0.json
anaconda-custom-py27_0.json
anaconda-navigator-1.1.0-py27_0.json
appnope-0.1.0-py27_0.json
appscript-1.0.1-py27_0.json
argcomplete-1.0.0-py27_1.json
astropy-1.2.1-np111py27_0.json
babel-2.2.0-py27_0.json
backports-1.0-py27_0.json
backports_abc-0.4-py27_0.json
beautifulsoup4-4.4.1-py27_0.json
bitarray-0.8.1-py27_0.json
blaze-0.10.1-py27_0.json
bokeh-0.11.1-py27_0.json
boto-2.39.0-py27_0.json
bottleneck-1.1.0-np111py27_0.json
cdecimal-2.3-py27_0.json
cffi-1.5.2-py27_0.json
chest-0.2.3-py27_0.json
cloudpickle-0.1.1-py27_0.json
clyent-1.2.1-py27_0.json
colorama-0.3.7-py27_0.json
conda-4.3.22-py27_0.json
conda-build-1.20.0-py27_0.json
conda-env-2.6.0-0.json
conda-manager-0.3.1-py27_0.json
configobj-5.0.6-py27_0.json
configparser-3.5.0b2-py27_1.json
contextlib2-0.5.3-py27_0.json
cryptography-1.7.1-py27_0.json
curl-7.49.0-0.json
cycler-0.10.0-py27_0.json
cymem-1.31.0-py27_0.json
cython-0.23.4-py27_1.json
cytoolz-0.8.2-py27_0.json
dask-0.8.1-py27_0.json
datashape-0.5.1-py27_0.json
decorator-4.0.9-py27_0.json
dill-0.2.5-py27_0.json
docutils-0.12-py27_0.json
dynd-python-0.7.2-py27_0.json
entrypoints-0.2.2-py27_0.json
enum34-1.1.2-py27_0.json
et_xmlfile-1.0.1-py27_0.json
fastcache-1.0.2-py27_0.json
flask-0.10.1-py27_1.json
flask-cors-2.1.2-py27_0.json
freetype-2.5.5-0.json
ftfy-4.4.3-py27_0.json
funcsigs-0.4-py27_0.json
futures-3.0.3-py27_0.json
geos-3.4.2-0.json
gevent-1.1.0-py27_0.json
greenlet-0.4.9-py27_0.json
grin-1.2.1-py27_1.json
h5py-2.6.0-np111py27_1.json
hdf5-1.8.16-0.json
heapdict-1.0.0-py27_0.json
history
html5lib-0.999-py27_0.json
idna-2.0-py27_0.json
ipaddress-1.0.14-py27_0.json
ipykernel-4.3.1-py27_0.json
ipython-4.1.2-py27_1.json
ipython_genutils-0.1.0-py27_0.json
ipywidgets-4.1.1-py27_0.json
itsdangerous-0.24-py27_0.json
jbig-2.1-0.json
jdcal-1.2-py27_0.json
jedi-0.9.0-py27_0.json
jinja2-2.8-py27_0.json
jpeg-8d-1.json
jsonschema-2.4.0-py27_0.json
jupyter-1.0.0-py27_2.json
jupyter_client-4.2.2-py27_0.json
jupyter_console-4.1.1-py27_0.json
jupyter_core-4.1.0-py27_0.json
libdynd-0.7.2-0.json
libgcc-4.8.5-1.json
libpng-1.6.17-0.json
libtiff-4.0.6-1.json
libxml2-2.9.2-0.json
libxslt-1.1.28-2.json
llvmlite-0.12.1-py27_0.json
locket-0.2.0-py27_0.json
lxml-3.6.0-py27_0.json
markdown-2.6.6-py27_0.json
markupsafe-0.23-py27_0.json
matplotlib-1.5.1-np111py27_0.json
mistune-0.7.2-py27_1.json
mkl-11.3.3-0.json
mkl-service-1.1.2-py27_2.json
mpld3-0.2-py27_0.json
mpmath-0.19-py27_0.json
multipledispatch-0.4.8-py27_0.json
murmurhash-0.26.1-py27_0.json
nbconvert-4.2.0-py27_0.json
nbformat-4.0.1-py27_0.json
ncurses-5.9-1.json
networkx-1.11-py27_0.json
nltk-3.2.1-py27_0.json
nose-1.3.7-py27_0.json
notebook-4.1.0-py27_2.json
numba-0.27.0-np111py27_0.json
numexpr-2.6.1-np111py27_0.json
numpy-1.11.1-py27_0.json
odo-0.4.2-py27_0.json
openpyxl-2.3.2-py27_0.json
openssl-1.0.2g-0.json
pandas-0.18.1-np111py27_0.json
partd-0.3.2-py27_1.json
path.py-8.1.2-py27_1.json
pathlib-1.0.1-py27_0.json
patsy-0.4.1-py27_0.json
pcre-8.31-0.json
pep8-1.7.0-py27_0.json
pexpect-4.0.1-py27_0.json
pickleshare-0.5-py27_0.json
pillow-3.1.1-py27_0.json
pip-8.1.1-py27_1.json
plac-0.9.6-py27_0.json
ply-3.8-py27_0.json
preshed-1.0.0-py27_0.json
psutil-4.1.0-py27_1.json
psycopg2-2.6.1-py27_1.json
ptyprocess-0.5-py27_0.json
py-1.4.31-py27_0.json
pyasn1-0.1.9-py27_0.json
pyaudio-0.2.7-py27_0.json
pycosat-0.6.1-py27_0.json
pycparser-2.14-py27_0.json
pycrypto-2.6.1-py27_0.json
pycurl-7.43.0-py27_0.json
pyflakes-1.1.0-py27_0.json
pygments-2.1.1-py27_0.json
pyopenssl-17.0.0-py27_0.json
pyparsing-2.0.3-py27_0.json
pyqt-4.11.4-py27_1.json
pytables-3.2.2-np111py27_4.json
pytest-2.8.5-py27_0.json
python-2.7.11-0.json
python-dateutil-2.5.1-py27_0.json
python.app-1.2-py27_4.json
pytz-2016.2-py27_0.json
pyyaml-3.11-py27_1.json
pyzmq-15.2.0-py27_0.json
qt-4.8.7-1.json
qtawesome-0.3.2-py27_0.json
qtconsole-4.2.0-py27_0.json
qtpy-1.0-py27_0.json
r-3.2.2-0.json
r-base-3.2.2-0.json
r-boot-1.3_17-r3.2.2_0a.json
r-class-7.3_14-r3.2.2_0a.json
r-cluster-2.0.3-r3.2.2_0a.json
r-codetools-0.2_14-r3.2.2_0a.json
r-foreign-0.8_66-r3.2.2_0a.json
r-kernsmooth-2.23_15-r3.2.2_0a.json
r-lattice-0.20_33-r3.2.2_0a.json
r-mass-7.3_45-r3.2.2_0a.json
r-matrix-1.2_2-r3.2.2_0a.json
r-mgcv-1.8_9-r3.2.2_0a.json
r-nlme-3.1_122-r3.2.2_0a.json
r-nnet-7.3_11-r3.2.2_0a.json
r-recommended-3.2.2-r3.2.2_0.json
r-rpart-4.1_10-r3.2.2_0a.json
r-spatial-7.3_11-r3.2.2_0a.json
r-survival-2.38_3-r3.2.2_0a.json
readline-6.2-2.json
redis-2.6.9-0.json
redis-py-2.10.3-py27_0.json
regex-2017.4.5-py27_0.json
requests-2.14.2-py27_0.json
rope-0.9.4-py27_1.json
rpy2-2.7.0-py27r3.2.2_0.json
ruamel_yaml-0.11.14-py27_1.json
scikit-image-0.12.3-np111py27_1.json
scikit-learn-0.17.1-np111py27_2.json
scipy-0.17.1-np111py27_1.json
seaborn-0.7.0-py27_0.json
semver-2.4.2-py27_0.json
setuptools-20.3-py27_0.json
shapely-1.5.13-py27_0.json
simplegeneric-0.8.1-py27_0.json
singledispatch-3.4.0.3-py27_0.json
sip-4.16.9-py27_0.json
six-1.10.0-py27_0.json
snowballstemmer-1.2.1-py27_0.json
sockjs-tornado-1.0.1-py27_0.json
spacy-1.8.2-py27_0.json
sphinx-1.3.5-py27_0.json
sphinx_rtd_theme-0.1.9-py27_0.json
sputnik-0.9.3-py27_0.json
spyder-2.3.8-py27_1.json
sqlalchemy-1.0.13-py27_0.json
sqlite-3.9.2-0.json
ssl_match_hostname-3.4.0.2-py27_0.json
statsmodels-0.6.1-np111py27_1.json
sympy-1.0-py27_0.json
tabulate-0.7.5-py27_0.json
termcolor-1.1.0-py27_0.json
terminado-0.5-py27_1.json
thinc-6.5.2-py27_0.json
tk-8.5.18-0.json
toolz-0.8.2-py27_0.json
tornado-4.3-py27_1.json
tqdm-4.14.0-py27_0.json
traitlets-4.2.1-py27_0.json
twisted-16.2.0-py27_0.json
ujson-1.35-py27_0.json
unicodecsv-0.14.1-py27_0.json
unidecode-0.04.19-py27_0.json
wcwidth-0.1.7-py27_0.json
werkzeug-0.11.4-py27_0.json
wheel-0.29.0-py27_0.json
wrapt-1.10.10-py27_0.json
xlrd-0.9.4-py27_0.json
xlsxwriter-0.8.4-py27_0.json
xlwings-0.7.0-py27_0.json
xlwt-1.0.0-py27_0.json
xz-5.0.5-1.json
yaml-0.1.6-0.json
zeromq-4.1.3-0.json
zlib-1.2.8-0.json      
zope.interface-4.2.0-py27_0.json
```
