### ISSUE TITLE
environment export error

### ISSUE THREAD

**Issue by johandebraak** [conda/conda#4294]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.1
       conda is private : False
      conda-env version : 4.3.1
    conda-build version : 2.0.8
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Miniconda3  (writable)
    default environment : C:\Miniconda3\envs\myenv
       envs directories : C:\Miniconda3\envs
          package cache : C:\Miniconda3\pkgs
           channel URLs : 
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Johan\.condarc
           offline mode : False
             user-agent : conda/4.3.1 requests/2.11.1 CPython/3.5.2 Windows/10 Windows/10.0.10586

`$ C:\Miniconda3\Scripts\conda-env-script.py export`

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 515, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda_env\cli\main_export.py", line 94, in execute
        ignore_channels=args.ignore_channels)
      File "C:\Miniconda3\lib\site-packages\conda_env\env.py", line 62, in from_environment
        if dist.channel not in channels:
    AttributeError: 'str' object has no attribute 'channel'

**Comment by kalefranz** [comment]
Appears to be fixed.

```
$ python -m conda_env export

CondaEnvException: Conda Env Exception: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

```

**Comment by kalefranz** [comment]
tested with conda version 4.3.18
