### ISSUE TITLE
Conda 4.3.4 seems to be broken 

### ISSUE THREAD

**Issue by bgruening** [conda/conda#4299]
```
bag@bag ~ % conda --version      
conda 4.3.4
bag@bag ~ % conda install -y --file https://raw.githubusercontent.com/bioconda/bioconda-utils/master/bioconda_utils/bioconda_utils-requirements.txt


CondaError: Downloaded bytes did not match Content-Length
  url: https://raw.githubusercontent.com/bioconda/bioconda-utils/master/bioconda_utils/bioconda_utils-requirements.txt
  target_path: /tmp/tmpUp36pQ/bioconda_utils-requirements.txt
  Content-Length: 195
  downloaded bytes: 310



bag@bag ~ % 

```

**Comment by nehaljwani** [comment]
Seems like https://github.com/conda/conda/commit/24ad4709#diff-e524c3264718c66b34ea0dadbfc2559fR88 introduced the bug. 

The request header sent by `requests.session` in this case has:
```bash
'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*'
```
AFAIK, the `Content-Length` header holds the raw length of the HTTP body. So, in this case, it will show 195 bytes, which is the size of the compressed 310 bytes.

If you do: `print(len(resp.raw.data))` you will see 195.

**Comment by nehaljwani** [comment]
Sort of relevant discussion at: https://github.com/kennethreitz/requests/issues/2155
