### ISSUE TITLE
Conda update seems to violate channel priority

### ISSUE THREAD

**Issue by christianbrodbeck** [conda/conda#4300]
See below. When I run `$ conda update` it tries to replace the `traitsui` package with one from `conda-forge`, which has lower priority than `defaults`, even though `traitsui` is on `defaults` too. 

It also fails to updated dependencies properly, so maybe there is more amiss? (the `traitsui` update requires a `traits` update, and the `mayavi` update requires a `vtk` update)

```
$ conda --version
conda 4.3.4
$ $ conda config --get channels
--add channels 'conda-forge'   # lowest priority
--add channels 'defaults'
--add channels 'christianbrodbeck'   # highest priority
$ cat ~/.condarc 
channels:
  - christianbrodbeck
  - defaults
  - conda-forge
$ conda create -n test mayavi=4.4
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment //anaconda/envs/test:

The following NEW packages will be INSTALLED:

    apptools:   4.2.1-py27_0    
    configobj:  5.0.6-py27_0    
    envisage:   4.4.0-py27_1    
    freetype:   2.5.5-1         
    libpng:     1.6.27-0        
    mayavi:     4.4.0-np19py27_0
    mkl:        11.3.3-0        
    numpy:      1.9.3-py27_3    
    openssl:    1.0.2j-0        
    pip:        9.0.1-py27_1    
    pyface:     4.4.0-py27_0    
    pyqt:       4.11.4-py27_4   
    python:     2.7.13-0        
    python.app: 1.2-py27_4      
    qt:         4.8.7-4         
    readline:   6.2-2           
    setuptools: 27.2.0-py27_0   
    sip:        4.18-py27_0     
    six:        1.10.0-py27_0   
    sqlite:     3.13.0-0        
    tk:         8.5.18-0        
    traits:     4.4.0-py27_0    
    traitsui:   4.4.0-py27_0    
    vtk:        5.10.1-py27_0   
    wheel:      0.29.0-py27_0   
    zlib:       1.2.8-3         

Proceed ([y]/n)? y

openssl-1.0.2j 100% |##############################################################| Time: 0:00:01   2.80 MB/s
sqlite-3.13.0- 100% |##############################################################| Time: 0:00:00   2.68 MB/s
tk-8.5.18-0.ta 100% |##############################################################| Time: 0:00:00   2.15 MB/s
freetype-2.5.5 100% |##############################################################| Time: 0:00:00   2.73 MB/s
python.app-1.2 100% |##############################################################| Time: 0:00:00   8.55 MB/s
sip-4.18-py27_ 100% |##############################################################| Time: 0:00:00   4.68 MB/s
vtk-5.10.1-py2 100% |##############################################################| Time: 0:00:11   2.52 MB/s
apptools-4.2.1 100% |##############################################################| Time: 0:00:00 817.01 kB/s
envisage-4.4.0 100% |##############################################################| Time: 0:00:00 900.27 kB/s
mayavi-4.4.0-n 100% |##############################################################| Time: 0:00:04   2.49 MB/s
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

$ source activate test
(test) $ conda update mayavi
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment //anaconda/envs/test:

The following packages will be UPDATED:

    apptools: 4.2.1-py27_0     --> 4.4.0-py27_0            
    envisage: 4.4.0-py27_1     --> 4.5.1-py27_0            
    mayavi:   4.4.0-np19py27_0 --> 4.5.0-py27_0            
    traitsui: 4.4.0-py27_0     --> 5.1.0-py27_0 conda-forge

Proceed ([y]/n)? 
```

**Comment by kalefranz** [comment]
@christianbrodbeck Thanks for the report.  I can confirm being able to reproduce your issue.  But I can also reproduce it in conda 4.2 (using 4.2.15).  Just trying to narrow down where the problem started.

@mcg1969 I'm going to write a regression test using this as a test case targeted to 4.2.x.  The test will be that the `update` command respects channel priority.

**Comment by mcg1969** [comment]
Are we sure there isn't a dependency requirement for a newer version of traitsui than is supplied in defaults? If none of the packages in `defaults` satisfy the requirements, then it is expected that conda will reach down to a lower priority channel.

**Comment by mcg1969** [comment]
If what we want is for `conda` to completely _disregard_ all packages in lower-priority channels, we can do that, but that has never been the designed behavior, and that is not what is documented, either.

**Comment by mcg1969** [comment]
One way to test this: remove `conda-forge` from the channel list, and then try the same command. If a lesser version of `mayavi` is installed, then we can be sure that there's a dependency limitation. Remember, conda's _first_ priority in any situation is to maximize the versions of the packages specified on the command line.

**Comment by mcg1969** [comment]
I can't look at `conda-forge` metadata right now, but in `defaults`, `traitsui-5.1` does _not_ depend on `traits` at all, so it would not force an update for `traits`.

**Comment by mcg1969** [comment]
Our metadata for the `mayavi` package does show a dependency on `vtk`, but it is unversioned. Thus it would _not_ cause an update to `vtk`.

**Comment by kalefranz** [comment]
I think the question to answer is why is traitsui being pulled from the conda-forge channel on the update command?

**Comment by mcg1969** [comment]
I understand that's the primary question, but I'm just dispatching the other concerns since they were easy to verify. Again, try dropping conda-forge altogether and re-running the install. That will give us a hint if perhaps there is a deep dependency conflict forcing conda to bypass the traitsui package in defaults.

**Comment by mcg1969** [comment]
I know why---it's because the `defaults` version of `traitsui` would force an upgrade to `pyface 4.6.0` or later, while the `conda-forge` version does not.

So by reaching down to `conda-forge`, it has reduced the _number_ of packages that it has to update by one. That is a higher priority objective, so that's the choice it makes.

I'm afraid this is just a corner case that we're not going to be able to fix. My bigger concern, in fact, is that conda-forge's recipe for `traitsui` seems to have no version constraints at all on its packages; and that our `traitsui` package doesn't even _have_ a `traits` dependency, which it would seem it obviously ought to.

**Comment by mcg1969** [comment]
The only way we can categorically avoid corner cases like this is if we implement a _strict_ channel priority mode, which means that `conda` is _never_ allowed to reach down to a lower-priority channel for _any_ reason.

**Comment by kalefranz** [comment]
Don't ever bet against the solver. Ever. Ever ever.

@christianbrodbeck I think we've resolved this problem.  It's not a bug in conda.  The error is with the package definitions.

**Comment by kalefranz** [comment]
I guess I can't even use this as a regression test case.  Moving on :)

**Comment by kalefranz** [comment]
Thanks @mcg1969

**Comment by mcg1969** [comment]
I love the fact that the SAT solver has become this reliable. But it is fascinating to see these really weird behaviors, and @christianbrodbeck, I am grateful that you brought this one to our attention. I do think the real problem here is that conda-forge and defaults don't agree on what the metadata should say; and I thnk there are some objective problems with both channels' choices in the `traitsui` case.

**Comment by christianbrodbeck** [comment]
Thanks for the help! What is the proper way to report a problem with the dependency specifications in the `defaults` channel?

**Comment by kalefranz** [comment]
https://github.com/ContinuumIO/anaconda-issues

**Comment by christianbrodbeck** [comment]
thanks!
