### ISSUE TITLE
Current conda install:

### ISSUE THREAD

**Issue by qq303067814** [conda/conda#4305]
platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : E:\Anaconda2  (writable)
    default environment : E:\Anaconda2
       envs directories : E:\Anaconda2\envs
          package cache : E:\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ E:\Anaconda2\Scripts\conda-script.py install --yes numpy scipy matplotlib sci
kit-image pip`

    Traceback (most recent call last):
      File "E:\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "E:\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _mai
n
        exit_code = args.func(args, p)
      File "E:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80,
in execute
        install(args, parser, 'install')
      File "E:\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in i
nstall
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not ope
n u'E:\\Anaconda2\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnecti
onPool(host='repo.continuum.io', port=443): Read timed out.).

plz how can I solve it?

**Comment by qq303067814** [comment]
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  99.60 kB/s
An unexpected error has occurred.                   | Time: 0:01:49  66.96 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

**Comment by kalefranz** [comment]
Intermittent HTTP timeout.  Just retry.  Also, `conda update conda` will help.
