### ISSUE TITLE
Another NoneType issue

### ISSUE THREAD

**Issue by bioruffo** [conda/conda#4306]
Related to:  
https://github.com/Anaconda-Platform/anaconda-client/issues/380

This time, the script that returns an error is `history.py`:  

    >conda install --revision spyder 2.3.9
    Fetching package metadata ...........
    An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:
    
        https://github.com/conda/conda/issues
    
    
    
    Current conda install:
    
                   platform : win-64
              conda version : 4.3.4
           conda is private : False
          conda-env version : 4.3.4
        conda-build version : 1.21.3
             python version : 3.5.2.final.0
           requests version : 2.12.4
           root environment : C:\Users\Roberto\Anaconda3  (writable)
        default environment : C:\Users\Roberto\Anaconda3
           envs directories : C:\Users\Roberto\Anaconda3\envs
              package cache : C:\Users\Roberto\Anaconda3\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/win-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/win-64
                              https://repo.continuum.io/pkgs/pro/noarch
                              https://repo.continuum.io/pkgs/msys2/win-64
                              https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.4 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14986
    
    
    
    `$ C:\Users\Roberto\Anaconda3\Scripts\conda-script.py install --revision spyder 2.3.9`
    
    
    
    
        Traceback (most recent call last):
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\cli\main.py", line 158, in _main
            exit_code = args.func(args, p)
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
            install(args, parser, 'install')
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\cli\install.py", line 232, in install
            action_set = [revert_actions(prefix, get_revision(args.revision), index)]
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\plan.py", line 807, in revert_actions
            state = h.get_state(revision)
          File "C:\Users\Roberto\Anaconda3\lib\site-packages\conda\history.py", line 195, in get_state
            return pkgs[rev]
        TypeError: tuple indices must be integers or slices, not NoneType

**Comment by kalefranz** [comment]
I believe this should be resolved with https://github.com/conda/conda/pull/4290.  We'll be released `4.3.5` tomorrow probably, and I'll circle back around to check and see if that's fixed your issue.

**Comment by kalefranz** [comment]
Should be fixed with #4290 in conda `4.3.5`.  If you'd like to test,

    conda config --add channels conda-canary
    conda update conda
