### ISSUE TITLE
Problems installing 3rd party packages via Conda install

### ISSUE THREAD

**Issue by itorres1994** [conda/conda#4310]
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\Ian Torres\Anaconda2  (writable)
    default environment : C:\Users\Ian Torres\Anaconda2
       envs directories : C:\Users\Ian Torres\Anaconda2\envs
          package cache : C:\Users\Ian Torres\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Ian Torres\.condarc
           offline mode : False

`$ C:\Users\Ian Torres\Anaconda2\Scripts\conda-script.py update requests openssl`

    Traceback (most recent call last):
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2

Fetching packages ...

**Comment by itorres1994** [comment]
Also of note I am using Git Bash Terminal to run this install.

**Comment by kalefranz** [comment]
I'm not sure what's going on here, but try running `conda update conda` or `conda install conda=4.2.15` (if you want to stay on conda 4.2) and see if you still have the error.

**Comment by itorres1994** [comment]
The problem even persists running both commands. Here is the output of running `conda update conda`:
$ conda update conda
Fetching package metadata ...SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.....
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Ian Torres\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

Proceed ([y]/n)? y

Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\Ian Torres\Anaconda2  (writable)
    default environment : C:\Users\Ian Torres\Anaconda2
       envs directories : C:\Users\Ian Torres\Anaconda2\envs
          package cache : C:\Users\Ian Torres\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Ian Torres\.condarc
           offline mode : False



`$ C:\Users\Ian Torres\Anaconda2\Scripts\conda-script.py update conda`




    Traceback (most recent call last):
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2


Fetching packages ...

**Comment by kalefranz** [comment]
Oh, right.  Try this

1. Run `conda config --set ssl_verify false`.
2. Run either of the two commands from before.
3. Run `conda config --remove-key ssl_verify`.

**Comment by itorres1994** [comment]
It failed on step 2. The problem seems to be that the update script cannot connect to the conda web domain. Here is the failure output. However, I think this is the only line that seems to be of note:
**Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2**

Ian Torres@IanTorres-PC MINGW64 ~
$ conda config --set ssl_verify false

Ian Torres@IanTorres-PC MINGW64 ~
$ conda update conda
Fetching package metadata ...SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
..SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
...
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Ian Torres\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

Proceed ([y]/n)? y

Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\Ian Torres\Anaconda2  (writable)
    default environment : C:\Users\Ian Torres\Anaconda2
       envs directories : C:\Users\Ian Torres\Anaconda2\envs
          package cache : C:\Users\Ian Torres\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Ian Torres\.condarc
           offline mode : False



`$ C:\Users\Ian Torres\Anaconda2\Scripts\conda-script.py update conda`




    Traceback (most recent call last):
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Ian Torres\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2


Fetching packages ...

**Comment by kalefranz** [comment]
After `conda config --set ssl_verify false`, what is the output of `conda config --show` and `conda config --show-sources`?

**Comment by itorres1994** [comment]
Here is the output from running both commands in git bash:

Ian Torres@IanTorres-PC MINGW64 ~
$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_softlinks: True
always_copy: False
always_yes: False
auto_update_conda: True
binstar_upload: None
changeps1: True
channel_alias: https://conda.anaconda.org/
channel_priority: True
channels:
  - defaults
client_cert:
client_cert_key:
create_default_packages: []
debug: False
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
json: False
offline: False
proxy_servers: {}
quiet: False
shortcuts: True
show_channel_urls: None
ssl_verify: False
track_features: []
update_dependencies: True
use_pip: True
verbosity: 0

Ian Torres@IanTorres-PC MINGW64 ~
$ conda config --show-sources
==> C:\Users\Ian Torres\.condarc <==
ssl_verify: False

**Comment by kalefranz** [comment]
Ok I honestly have no idea where this cert error is coming from.  And it's on Windows, meaning I'd need to be on the machine to get to the root cause.

Next step: Download the latest miniconda installer for your system (https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe) and run it overtop your `C:\Users\Ian Torres\Anaconda2` directory.

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
