### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by mfhmoham** [conda/conda#4314]
(C:\Program Files\Anaconda3) C:\Windows\system32>conda create -n my_root -clone
C:\Program Files\Anaconda3
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Users\Fazrul.Hazuwan\.conda\envs
                          C:\Program Files\Anaconda3\envs
          package cache : C:\Users\Fazrul.Hazuwan\.conda\envs\.pkgs
                          C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -n my_root -clone=
:\Program Files\Anaconda3`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py",
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", li
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.
y", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 238, in install
        prefix=prefix)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\api.py", line 23
 in get_index
        channel_urls = prioritize_channels(channel_urls)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\models\channel.p
", line 198, in prioritize_channels
        channel = Channel(chn)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\models\channel.p
", line 46, in __call__
        elif has_scheme(value):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\models\channel.p
", line 28, in has_scheme
        return bool(urlparse(value).scheme in RECOGNIZED_URL_SCHEMES)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\common\url.py",
ine 51, in urlparse
        return parse_url(url)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urll
b3\util\url.py", line 189, in parse_url
        raise LocationParseError(url)
    requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: l
ne=C:\Program

**Comment by kalefranz** [comment]
In this situation, the space in the file path in your command is a problem for Windows command-line tokenization.  I think using quotation marks should fix your issue.

    conda create -n my_root --clone "C:\Program Files\Anaconda3"

**Comment by kalefranz** [comment]
Also, conda 4.2.9 is old and has bugs.  You should update to 4.2.16 or 4.3.8.

    conda update conda
