### ISSUE TITLE
deactivate bug

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#4316]
@kevinzzz007 your issue reported in #4275 is different than what #4275 is reporting.  I've created a new issue here.

> I have a similar problem, I created an env with a name that does not start with an underscore, first I can successfully activate this env, but when I type source deactivate when inside the env, I get an error as the following /Users/MyName/anaconda3/envs/EnvName/bin/deactivate:81: no such file or directory: /Users/MyName/anaconda3/envs/EnvName/bin/python, I looked at the /Users/MyName/anaconda3/envs/EnvName/bin directory and there is no python file in this directory, and after I typed the source deactivate command, my command prompt seems to be back to normal, but then the command prompt can't recognize simple commands like ls...

> my conda version is 4.3.4

**Comment by kalefranz** [comment]
This logic has changed recently, and it's also in the latest release of 4.2.  I'll try to fix this tomorrow.

**Comment by kevinzzz007** [comment]
@kalefranz thank you so much!

**Comment by kalefranz** [comment]
Should be fixed with #4329 in conda `4.3.5`.  If you'd like to test,

    conda config --add channels conda-canary
    conda update conda

**Comment by kevinzzz007** [comment]
@kalefranz tested and now it works! Just out of curiosity, what does `conda config --add channels conda-canary` do?
