### ISSUE TITLE
Problems install local package error

### ISSUE THREAD

**Issue by xmljr** [conda/conda#4321]
Hi! I am new here. I want to install some new packages from D drive. The error just pops out. Can anyone help me? Thanks.

The info is posted below:

 (snakes) C:\Users\Jiarui Li>conda install --file D:\pynx-2.3.4.tar.bz2 pynx
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\Jiarui Li\Anaconda3  (writable)
    default environment : C:\Users\Jiarui Li\Anaconda3\envs\snakes
       envs directories : C:\Users\Jiarui Li\Anaconda3\envs
          package cache : C:\Users\Jiarui Li\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/3.5.2 Windows/7 Windows/6.1.7601

`$ C:\Users\Jiarui Li\Anaconda3\Scripts\conda-script.py install --file D:\pynx-2.3.4.tar.bz2 pynx`

    Traceback (most recent call last):
      File "C:\Users\Jiarui Li\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_
exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Jiarui Li\Anaconda3\lib\site-packages\conda\cli\main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Jiarui Li\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in e
xecute
        install(args, parser, 'install')
      File "C:\Users\Jiarui Li\Anaconda3\lib\site-packages\conda\cli\install.py", line 168, in insta
ll
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "C:\Users\Jiarui Li\Anaconda3\lib\site-packages\conda\cli\common.py", line 538, in specs_
from_url
        for line in open(path):
      File "C:\Users\Jiarui Li\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 13: character maps to <un
defined>

(snakes) C:\Users\Jiarui Li>

**Comment by kalefranz** [comment]
Try without the `--file` flag.  Without being completely sure what you want to do, probably something like

    conda install D:\pynx-2.3.4.tar.bz2
