### ISSUE TITLE
Channels in centrally installed .condarc file are being ignored in conda 4.3.4

### ISSUE THREAD

**Issue by wulmer** [conda/conda#4323]
Hi, I am testing a centrally installed Anaconda setup with Anaconda installed under `C:\Program Files\Anaconda3`. I have a condarc file under `C:\Program Files\Anaconda3\.condarc`.

When I run `conda info` it tells me that my config file is under the correct location.

    config file : C:\Program Files\Anaconda3\.condarc

I have configured a few custom channels in this `.condarc` file, e.g.:

    channels:
      - http://some.internal/url

I can also use `conda config --system --add channels http://some.internal/url` to set this value and conda tells me that channels already contains this value.

But when I run `conda config --system --show`, the list of channels is always set to:

    channels:
      - defaults

It seems that the list of channels in the central `.condarc` file is completely ignored and always replaced by `defaults`. I have also tried to set the list of `default_channels` in the central `.condarc` file but without success.

Using conda 4.3.4 on win-64.

**Comment by kalefranz** [comment]
Definitely a problem.  Thanks for the report.  I'll investigate.

**Comment by kalefranz** [comment]
Should be fixed with #4327 in conda `4.3.5`.  If you'd like to test,

    conda config --add channels conda-canary
    conda update conda

**Comment by wulmer** [comment]
@kalefranz Works! Thank you very much for this quick fix.
