### ISSUE TITLE
Install environment from .yaml file

### ISSUE THREAD

**Issue by DravinTitep** [conda/conda#4328]
I cannot manage to create a new environment from .yaml file. Maybe the .yaml file is in the wrong directory ? 
Does anyone know where I should put it ? 
I've tried 
/anaconda/bin
/anaconda/envs

Tks !

************
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ //anaconda/bin/conda-env create -f dand-env-mac.yaml`

    Traceback (most recent call last):
      File "//anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "//anaconda/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: dand-env-mac.yaml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment]
Try passing the absolute path of the file `dand-env-mac.yaml` to `conda create --file`

**Comment by DravinTitep** [comment]
it worked. Thanks :)

**Comment by phani99** [comment]
how to pass absolute path of file to conda create --file

**Comment by nehaljwani** [comment]
@phani99 By absolute path, I mean the complete path of the environment yaml file from '/', for example, let's say the environment file named `dand-env-mac.yaml` is kept inside the folder: `/path/to/my/projects/folder/`, then you would type:

```
$ /path/to/conda/bin/conda-env create -f /path/to/my/projects/folder/dand-env-mac.yaml
```

**Comment by phani99** [comment]
still i am getting this error

  Traceback (most recent call last):
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda\exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: /C:/Users/aind-environment-windows.yml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment]
@phani99 In Windows, the directory structure is different. Try typing:
```
conda create -f C:\Users\aind-environment-windows.yml
```
Also, your username contains a space. Please don't install anaconda into a directory which contains spaces. Reinstall anaconda to a directory with no spaces in it, otherwise you might face surprises.

**Comment by elhamiii** [comment]
Thanks so much nehaljwani it worked.

**Comment by kalefranz** [comment]
Duplicate of https://github.com/conda/conda/issues/3689

**Comment by cecilialee** [comment]
I encountered the same problem.
I solved this by first changing directories to the folder where the yml file locates.

- Open terminal, type `cd` followed by a space.
- Then open finder, drag and drop the folder to the terminal window. (Drop the folder where the file - locates, not the file itself.)
- You should be able to see terminal showing code like this `cd /Users/username/path/to/my/projects/folder/`, press enter.
- You'll now locates at the folder where your yml file locates.
- Type the conda command again `conda env create -f environment.yml` (Replace enviornment.yml with the name of your yml file.)
- Viola!

**Comment by DravinTitep** [comment]
Thanks @cecilialee

**Comment by luishernandezIMT** [comment]
Looking for this, thanks @cecilialee

**Comment by abinjoabraham** [comment]
> Try passing the absolute path of the file `dand-env-mac.yaml` to `conda create --file`

It worked . Thanks for the quick fix :).
