### ISSUE TITLE
conda 4.3* breaks package cache & dependency resolution

### ISSUE THREAD

**Issue by Korijn** [conda/conda#4338]
Since conda 4.3* has been released we have (once again) been forced to pin conda to an older version (4.2*). Various problems arise:

* Dependency resolution has changed; conda 4.3* prefers older package than 4.2*; couldn't trace this problem to its cause as the dependency resolution codebase is hard to understand and therefore to debug
* Package cache is broken; `CondaError: No package '***' found in cache directories.` is an error that pops up across the board on all our projects that are under CI for various different packages.

Whereas I normally could reproduce problems quite easily, I find that these errors are almost random.

We also frequently see `WARNING conda.gateways.disk:exp_backoff_fn(47): Uncaught backoff with errno 41` popping up on systems that aren't doing anything else, with completely clean & fresh conda installs.

IMHO the changes in conda 4.3* are a violation of semver as they appear to have involved many big changes (e.g., removal of locks) that affect the entire conda codebase. Behaviour has changed very significantly, and thus should have been tested more rigorously before being released. Have you considered working with specific groups of users to beta-test conda's bleeding edge in the field?

**Comment by kalefranz** [comment]
@Korijn Each feature release series spends several weeks in canary.  It's the `conda-canary` channel on anaconda.org.  4.3.0, 4.3.1, 4.3.2, and 4.3.3 were never released to defaults.

Even for patch versions, releases are always uploaded to the canary channel first so that various stakeholders have an opportunity to test them.  It'd be awesome if you participated! :)

I think I've fixed "Uncaught backoff with errno 41" recently with https://github.com/conda/conda/pull/4277/commits/fb2a783d9b9371559b5ea82aaf8ae631c2ce0450.  I guess there could be further places to ignore it.

> Package cache is broken

#4297 might fix this for you as well.  If not, please help with more details and I'll get whatever is broken fixed asap.

> Dependency resolution has changed

This should absolutely not be happening.  Are you seeing this when using conda alone, or only in conjunction with conda-build?

**Comment by Korijn** [comment]
> 4.3.0, 4.3.1, 4.3.2, and 4.3.3 were never released to defaults.

That's a surprise:

```
C:\Users\korij_000>conda info                                               
Current conda install:                                                      
                                                                            
               platform : win-64                                            
          conda version : 4.2.15                                            
       conda is private : False                                             
      conda-env version : 4.2.15                                            
    conda-build version : 2.0.12                                            
         python version : 3.5.2.final.0                                     
       requests version : 2.12.4                                            
       root environment : C:\Users\korij_000\Miniconda3  (writable)         
    default environment : C:\Users\korij_000\Miniconda3                     
       envs directories : C:\Users\korij_000\Miniconda3\envs                
          package cache : C:\Users\korij_000\Miniconda3\pkgs                
           channel URLs : https://conda.anaconda.org/clinicalgraphics/win-64
                          https://conda.anaconda.org/clinicalgraphics/noarch
                          https://repo.continuum.io/pkgs/free/win-64        
                          https://repo.continuum.io/pkgs/free/noarch        
                          https://repo.continuum.io/pkgs/pro/win-64         
                          https://repo.continuum.io/pkgs/pro/noarch         
                          https://repo.continuum.io/pkgs/msys2/win-64       
                          https://repo.continuum.io/pkgs/msys2/noarch       
            config file : C:\Users\korij_000\.condarc                       
           offline mode : False                                             
                                                                            
                                                                            
C:\Users\korij_000>conda config --get                                       
--add channels 'defaults'   # lowest priority                               
--add channels 'clinicalgraphics'   # highest priority                      
                                                                            
C:\Users\korij_000>conda update conda                                       
Fetching package metadata ...........                                       
Solving package specifications: ..........                                  
                                                                            
Package plan for installation in environment C:\Users\korij_000\Miniconda3: 
                                                                            
The following packages will be downloaded:                                  
                                                                            
    package                    |            build                           
    ---------------------------|-----------------                           
    conda-4.3.4                |           py35_0         534 KB            
                                                                            
The following packages will be UPDATED:                                     
                                                                            
    conda: 4.2.15-py35_0 --> 4.3.4-py35_0                                   
                                                                            
Proceed ([y]/n)?                                                            
```

This happens on CI (e.g. AppVeyor) as well, where a clean install of conda is done everytime. So it seems like a public release to me?

> Even for patch versions, releases are always uploaded to the canary channel first so that various stakeholders have an opportunity to test them. It'd be awesome if you participated! :)

I was not aware of that. We definitely will!

> I think I've fixed "Uncaught backoff with errno 41" recently with fb2a783. I guess there could be further places to ignore it.
> #4297 might fix this for you as well. If not, please help with more details and I'll get whatever is broken fixed asap.

Awesome. I'll check it out.

> This should absolutely not be happening. Are you seeing this when using conda alone, or only in conjunction with conda-build?

When calling `conda env create`. Particularly for `noarch` packages, we see a new error during the install phase that says something along the lines of `%prefix%\...\pkg-foo\python.exe does not exist`, which seems like it might be related.

**Comment by kalefranz** [comment]
> That's a surprise

4.3.4 was the first 4.3.x release to defaults.  I think that's consistent with what you're seeing.

You'll see 4.3.5 pop up in the conda-canary channel within an hour or two hopefully.  Since it's a patch release, I'd like to get it to defaults this evening or tomorrow.

I'm rushed for time now, but I'll circle back later and try to address anything I haven't covered yet.

**Comment by kalefranz** [comment]
@Korijn 4.3.5 is in the `conda-canary` channel.  Why don't you try it and see how far it gets you.  What got fixed (hopefully several things), and what's still remaining...

**Comment by Korijn** [comment]
I will try it tomorrow! The GMT+1 workday has ended. :)

**Comment by Korijn** [comment]
It looks like 4.3.5 fixes all aforementioned problems.

Interesting to note that we now see a different failure further on CI when building our package with `conda-build:     2.1.0beta1-py35_0 conda-canary`

```
Traceback (most recent call last):
  File "C:\Miniconda35-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 312, in main
    execute(sys.argv[1:])
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 304, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\api.py", line 86, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 1422, in build_tree
    config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 947, in build
    config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\render.py", line 90, in parse_or_try_download
    metadata.parse_again(config=config, permit_undefined_jinja=False)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\metadata.py", line 431, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja, config=config),
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\metadata.py", line 770, in _get_contents
    permit_undefined_jinja=permit_undefined_jinja))
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\jinja_context.py", line 213, in context_processor
    ctx = get_environ(config=config, m=initial_metadata)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\environ.py", line 217, in get_dict
    d.update(python_vars(config))
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\environ.py", line 254, in python_vars
    'PYTHON': config.build_python,
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\config.py", line 289, in build_python
    return self._get_python(self.build_prefix)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\config.py", line 202, in _get_python
    if 'debug' in packages_names:
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\config.py", line 201, in <genexpr>
    packages_names = (pkg.split('-')[0] for pkg in packages)
  File "C:\Miniconda35-x64\lib\site-packages\conda\models\dist.py", line 254, in split
    assert sep == '::'
AssertionError
```

**Comment by kalefranz** [comment]
CC @msarahan.  I guess we haven't been keeping up with conda-build on the canary channel.

I just added a different label to the conda-build package on conda-canary, so that most recently problem should clear up.

conda-build is now in version something like 2.1.1.  It should get pulled in for you now.

**Comment by kalefranz** [comment]
I'm going to close this issue.  Feel free to open a new one if something else pops up!
