### ISSUE TITLE
Re: message after "conda update --all

### ISSUE THREAD

**Issue by drfredkin** [conda/conda#4341]
Here is the log you requested:

[err.txt](https://github.com/conda/conda/files/711732/err.txt)

I suspect there is a permissions issue. If I execute the conda update command as root there are no error messages.

**Comment by kalefranz** [comment]
Thanks!  Will dig in soon.

**Comment by kalefranz** [comment]
This issue should now be fixed with https://github.com/conda/conda/pull/4366, and it will be released with conda 4.3.6 in the next 24 to 48 hours.
