### ISSUE TITLE
Package cache locations during installs

### ISSUE THREAD

**Issue by groutr** [conda/conda#4343]
Given the new multi-user cache support in conda, it would be really useful to see which caches conda is interacting with during a fetch/link.  Or another idea is to show the cache location for a package if its not from the main/global cache.

**Comment by kalefranz** [comment]
Yeah I can probably bubble that information up for you.

**Comment by kalefranz** [comment]
If you're curious, experiment with `-v, `-vv`, and `-vvv`.

**Comment by groutr** [comment]
I have experimented with the verbose flags.  -v doesn't give enough info, and -vv and -vvv give way too much.

Something like
```
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /sarc/spa/users/r.grout/.conda/envs/testenv:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0      defaults    /home/root/conda/pkgs/openssl
    pip:        9.0.1-py36_1  defaults    /home/root/conda/pkgs/pip
    python:     3.6.0-0       defaults    /home/user/.conda/.pkgs/python
    readline:   6.2-2         defaults    /home/root/conda/pkgs/readline

Proceed ([y]/n)?
```

**Comment by kalefranz** [comment]
Honestly, I don't want to overwhelm people with information.  While we *could* do it, I'm not sure we should.  Since this issue really hasn't had upvotes or additional community input, I'm going to close it for now.  If interest here picks up, we can always re-open it.

**Comment by groutr** [comment]
The reason why this is an important issue is because simply displaying the channel information is misleading.  If the package already exists in the package cache from a different channel, that cached package will be used instead of the package from the channel that was displayed to the user.

**Comment by kalefranz** [comment]
That hasn't been true for a long time.  For a package to be pulled from the package cache without it being invalidated and re-downloaded, the channel name, package name, version, and build have to match exactly.
