### ISSUE TITLE
Can't redirect error messages when starting conda

### ISSUE THREAD

**Issue by amkellett** [conda/conda#4344]
I preparation for posting another issue, I have been trying to redirect the errors I get when I start conda.  Here's what I enter:
conda > issue.txt

A file called issue.txt is produced, but it contains nothing.

What can I do to redirect the several pages of traceback I get?  

Here are the first few lines (hand-typed):
------start output-------------------

An unexpected error has occurred.
Please consider posting the following information to the 
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback(most recent call last):
  ...(a couple pages)
---------end output------------------

I hope this is posed correctly. Apologies if I'm doing this wrong - this is my first issue.

**Comment by kalefranz** [comment]
Error messages are usually written to stderr, not stdout.  To dump both to a file, you'll want to add `2>&1` onto your command.  So as you put it

    conda > issue.txt 2>&1

Also check out the `tee` command (http://stackoverflow.com/questions/637827/redirect-stderr-and-stdout-in-a-bash-script) if you want to write to a file *and* see the output on the terminal.

**Comment by amkellett** [comment]
Thanks much.
