### ISSUE TITLE
Installing R packages within Conda 

### ISSUE THREAD

**Issue by toasteez** [conda/conda#4355]
I am trying to use conda to install an r package [ycinterextra ](https://CRAN.R-project.org/package=ycinterextra )and possibly other CRAN packages.

How would I do this, the following did not work?

    conda install r-ycinterextra 

launching R from the command line and using install.packages("ycinterextra") works fine but does this install to anaconda path for use in Jupyter?  

What is the preferred way?

Note that I have looked here: https://docs.continuum.io/anaconda/r_language

**Comment by groutr** [comment]
@toasteez the `-c r` is important.  The R packages live in their own channel.  The `-c r` tells conda to look for packages in the R channel.

**Comment by mingwandroid** [comment]
We don't have the `ycinterextra` package unfortunately.

Your approach *should* still work with and in Jupyter, did you try it?

**Comment by toasteez** [comment]
@mingwandroid Yes that works in Jupyter:

    %R install.packages("ycinterextra")

**Comment by DivM** [comment]
I tried installing `bit64` from within the Jupyter notebook. It gave the following output:

```
also installing the dependency ‘bit’

Warning message in install.packages("bit64"):
“installation of package ‘bit’ had non-zero exit status”Warning message in install.packages("bit64"):
“installation of package ‘bit64’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```
But, when I am trying to include the package using `library(bit64)`, it's throwing error:

`Error in library(bit64): there is no package called ‘bit64’`

What is it that I am missing?

**Comment by mingwandroid** [comment]
> What is it that I am missing?

.. using conda to install your software when we provide it already:

`conda's install r-bit64`

**Comment by DivM** [comment]
`bit64` was just a token package I took for example. There are other packages which aren't on Anaconda Repo, and need to be installed directly from CRAN. 

Could you answer the above question for those packages, then?

**Comment by mingwandroid** [comment]
> Could you answer the above question for those packages, then?

Yeah sure.

```
conda install conda-build
conda skeleton cran <something_on_cran>
conda build r-<something_on_cran_lowercased>
conda install -c local r-<something_on_cran_lowercased>
```

**Comment by DivM** [comment]
It worked. Thanks!

Also, is there any option to include all dependencies automatically as well in the above commands as you have to manually run `conda skeleton` for each one before building the local package?

**Comment by mingwandroid** [comment]
There's a `--recursive` option. Try `conda skeleton cran --help`.

You can then pass multiple packages on the `conda-build` commandline, but you will want to build them in dependency order.

**Comment by DivM** [comment]
Got it. Thanks!

**Comment by setegonz** [comment]
I have installed FSA and all its dependencies via:

```
conda skeleton cran FSA
conda build r-fsa

```
When trying to run withins jupyter lab I get:
```
Error in library("FSA"): there is no package called ‘FSA’
```

I also tried 

`install.packages("FSA", "/users/setegonz/anaconda3/lib/R/library")`

Same result


Looking for the package folder this is the path that I found:
`/Users/setegonz/anaconda3/pkgs/r-fsa-0.8.22-r351h6115d3f_0`



Why Jupyter is not able to use this package?
Any suggestions?
