### ISSUE TITLE
Broke conda (removed executables) when upgrading nb_conda_kernels

### ISSUE THREAD

**Issue by pocin** [conda/conda#4365]
Hi, 
today I ran `$ conda upgrade nb_conda_kernels` and it seems it removed `conda` and `activate` executables from /opt/conda/bin (this is where I installed it)

Here is the output:
<img width="667" alt="conda_err_1" src="https://cloud.githubusercontent.com/assets/8642344/22079869/a03b8fd4-ddbd-11e6-87a1-76f27178727e.png">
<img width="1275" alt="conda_err_2" src="https://cloud.githubusercontent.com/assets/8642344/22079870/a03cd8b2-ddbd-11e6-8e1d-c61b5db0be8c.png">

I think this is the command that broke it, but I am not really sure. Is there anything I can provide to help diagnose the issue?

**Comment by nehaljwani** [comment]
Out of curiosity, is `/opt/conda` a network file system?

**Comment by kalefranz** [comment]
There was a path collision somewhere, and then because conda was updating itself in the process, it likely "uninstalled itself."  I would be thrilled if this was the last report of that ever happening.

The easiest way to heal the conda installation from here is to download the correct miniconda from [here](http://conda.pydata.org/miniconda.html), something like

    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh
    bash ~/miniconda.sh -bfp /opt/conda

**Comment by kalefranz** [comment]
See [this](https://www.continuum.io/blog/developer-blog/announcing-general-availability-conda-4-3) for what I was talking about with conda uninstalling itself.

**Comment by pocin** [comment]
@nehaljwani It is a ubuntu server running in LXC, 
```bash
nemeth@jupyterhub:~$ df -l
Filesystem                           Size Avail Use%      Mounted on
lxc/containers/jupyterhub   250G.....                /
...
```
From that I conclude it is not network filesystem, but I am not 100% sure.

@kalefranz 
```bash
nemeth@jupyterhub:~$ bash ./miniconda.sh -bfp /opt/conda
PREFIX=/opt/conda
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
tar: info/about.json: Cannot open: File exists
tar: info/files: Cannot open: File exists
tar: info/index.json: Cannot open: File exists
tar: info/platform: Cannot open: File exists
tar: Exiting with failure status due to previous errors
```

**Comment by kalefranz** [comment]
I've never seen that from the miniconda installer before. Are you sure you have permissions to those files?

**Comment by pocin** [comment]
Silly me, of course those were permission issues. Thanks for help!
