### ISSUE TITLE
Conda not running from command prompt

### ISSUE THREAD

**Issue by maherl** [conda/conda#4368]
C:\Users\Lydia> conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\Lydia\Anaconda3  (writable)
    default environment : C:\Users\Lydia\Anaconda3
       envs directories : C:\Users\Lydia\Anaconda3\envs
          package cache : C:\Users\Lydia\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Lydia\Anaconda3\Scripts\conda-script.py`

    Traceback (most recent call last):
      File "C:\Users\Lydia\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Lydia\Anaconda3\lib\site-packages\conda\cli\main.py", line 90, in _main
        args.append('-h')
    AttributeError: 'tuple' object has no attribute 'append'

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda/pull/4367
