### ISSUE TITLE
Conda 4.3.5 missing ~/miniconda/bin/activate

### ISSUE THREAD

**Issue by gmnash** [conda/conda#4371]
```
$ conda install -y conda
...
$ conda --version
conda 4.3.5

$ source activate {env_name_00}
bash: activate: No such file or directory

$ find ~/miniconda -name activate
~/miniconda/envs/{env_name_00}/bin/activate
~/miniconda/envs/{env_name_01}/bin/activate
~/miniconda/pkgs/conda-4.3.5-py27_0/bin/activate
~/miniconda/pkgs/conda-env-2.4.5-py27_0/bin/activate
```

**Comment by kalefranz** [comment]
What OS?

**Comment by gmnash** [comment]
Xubuntu 14.04

**Comment by ccordoba12** [comment]
@kalefranz, I think this is what's causing the Spyder tests to fail (and it only happens with Python 2.7; 3.5 is fine):

https://travis-ci.org/spyder-ide/spyder/jobs/193126633

**Comment by kalefranz** [comment]
Package looks fine: https://repo.continuum.io/pkgs/free/linux-64/conda-4.3.5-py27_0.tar.bz2

Still looking though...

**Comment by kalefranz** [comment]
If either of you figure this out before I do, please speak up.  I haven't found a smoking gun yet...

**Comment by kalefranz** [comment]
@ccordoba12 looks like something happened to your `conda` executable.  Looking at that too.

**Comment by ccordoba12** [comment]
What do you mean?

**Comment by kalefranz** [comment]
No more `conda` command somewhere between https://github.com/spyder-ide/spyder/blob/master/continuous_integration/travis/install.sh#L56 and https://github.com/spyder-ide/spyder/blob/master/continuous_integration/travis/build_test.sh#L18.

The output here in particular: https://travis-ci.org/spyder-ide/spyder/jobs/193126633#L368

**Comment by ccordoba12** [comment]
But that happens after activation. Please notice that before we run

    source activate test-environment

we use conda 4.3.5 to install a couple of packages.

**Comment by kalefranz** [comment]
Yeah, I just saw that at https://github.com/spyder-ide/spyder/blob/master/.travis.yml#L41

**Comment by gmnash** [comment]
The problem appears to be caused by installing conda-build.  This script reproduces it.  The problem is not exhibited when conda-build is not installed.

```
#!/bin/bash
set -e

CONDA_INSTALL_SCRIPT=Miniconda-latest-Linux-x86_64.sh
rm -rf $HOME/miniconda
rm -rf $CONDA_INSTALL_SCRIPT

wget https://repo.continuum.io/miniconda/$CONDA_INSTALL_SCRIPT
chmod +x ./$CONDA_INSTALL_SCRIPT
./$CONDA_INSTALL_SCRIPT -b -p $HOME/miniconda

conda install -y conda
conda create -y python=2.7 -n new_env

find $HOME/miniconda -name activate

# problem is here
conda install conda-build -y

find $HOME/miniconda -name activate

**Comment by kalefranz** [comment]
Thanks.  That helped.  I know what the problem is now.

**Comment by kalefranz** [comment]
The `conda-env >=2.6.0` dependency got removed.  I wasn't told that happened.  It's still required.

For now, something like

    conda install -y conda conda-env=2.6

will fix your problem until we get conda the next version of conda released tomorrow with the correct dependency back in.

**Comment by kalefranz** [comment]
Ilan is adding that back for us now.  Sorry for the trouble.

**Comment by kalefranz** [comment]
@ccordoba12 I think this is related to your problem too.  When you update conda right after miniconda, just make sure you update conda-env all the way too.

**Comment by ccordoba12** [comment]
@kalefranzm thanks, I'll try it and let you know if that works for us too.

**Comment by gmnash** [comment]
Thanks for the quick turnaround!
