### ISSUE TITLE
Command prompt told me to post

### ISSUE THREAD

**Issue by watthell234** [conda/conda#4375]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\Gonza\Anaconda3  (writable)
    default environment : C:\Users\Gonza\Anaconda3
       envs directories : C:\Users\Gonza\Anaconda3\envs
          package cache : C:\Users\Gonza\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Gonza\Anaconda3\Scripts\conda-script.py`

    Traceback (most recent call last):
      File "C:\Users\Gonza\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Gonza\Anaconda3\lib\site-packages\conda\cli\main.py", line 90, in _main
        args.append('-h')
    AttributeError: 'tuple' object has no attribute 'append'

**Comment by watthell234** [comment]
Please help! :D

**Comment by nehaljwani** [comment]
This has been fixed by commit https://github.com/conda/conda/commit/59376c5b545ad99ad20b64997ebdf39ad35393a5

**Comment by kalefranz** [comment]
Thanks for helping with the update @nehaljwani :)

**Comment by watthell234** [comment]
Thank you guys for the amazing turnaround on this! As a noob I appreciate this immensely.
