### ISSUE TITLE
installation error help

### ISSUE THREAD

**Issue by wqpeng** [conda/conda#4376]
I have created a new environment with the code "conda create -c rmg --name rmg_env rmg rmgdatabase", and then I choose "y" to download the package. But it occurs the error in the picture.
![_20170119145242](https://cloud.githubusercontent.com/assets/25217440/22096539/22e2e7e0-de57-11e6-9efc-2413f2d51d5f.png)
And what can I should do ?

**Comment by wqpeng** [comment]
help me

**Comment by kalefranz** [comment]
This is an HTTP timeout due to a not-so-great internet connection.  Updating to a more recent version of conda will help.

    conda update conda

Otherwise, just keep retrying :)

**Comment by wqpeng** [comment]
font{
        line-height: 1.5;
    }


    How can I solve this CondaError after I have update my conda :D

    
        On 01/19/2017 14:54，
                
                        Kale Franz
                        <notifications@github.com>
                    wrote：
                
        
    


This is an HTTP timeout due to a not-so-great internet connection.  Updating to a more recent version of conda will help.
conda update conda

Otherwise, just keep retrying :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  






        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }

**Comment by wqpeng** [comment]
font{
        line-height: 1.5;
    }


    Why can I always occur the CondaHTTPError？ Just because do I come from China?


    
        On 01/19/2017 15:27，
                
                        wangqianpeng
                        <wangqianpeng@buaa.edu.cn>
                    wrote：
                
        
    




    font{
        line-height: 1.5;
    }


    How can I solve this CondaError after I have update my conda :D

    
        On 01/19/2017 14:54，
                
                        Kale Franz
                        <notifications@github.com>
                    wrote：
                
        
    


This is an HTTP timeout due to a not-so-great internet connection.  Updating to a more recent version of conda will help.
conda update conda

Otherwise, just keep retrying :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  






        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
