### ISSUE TITLE
Conda completely broken after conda update --all

### ISSUE THREAD

**Issue by buergi** [conda/conda#4377]
A conda update --all failed with
```
PaddingError: Placeholder of length '30' too short in package qt-5.6.2-vc14_3.%
The package must be rebuilt with conda-build > 2.0.
```
leaving conda completely unusable, the conda command is not even found any longer.
I found the executable below the pkg folder, however I could't find a way to use it.

[Here](https://github.com/conda/conda/files/716544/condalog.txt) is the whole log of the update progress (I removed the download progress from the log)

I'm using Windows 10 and installed Anaconda without Admin permissions for my local user.
Besides installing some packages using conda I didn't change anything on the conda installation.
It should not be possible that a failure in a single package leaves the whole conda system unusable.
I'm just installing Anaconda from scratch as I have no idea how to fix the system.

**Comment by mingwandroid** [comment]
You ran into an old bug with `conda` (the `Placeholder of length` thing) I am afraid, then likely some incompatibility between the `conda` you ran with and the `conda` that the update installed.

@kalefranz, would it be possible to make any updates that involve `conda` instead *only* update `conda`, and ask the user to update again afterwards, I know it's not the optimal user experience, but it beats what @buergi has just experienced.

**Comment by kalefranz** [comment]
The transactional rollback in 4.3 will prevent the worst part of this experience completely. Once we get users on 4.3, we'll be in much better shape.

**Comment by kalefranz** [comment]
> then likely some incompatibility between the conda you ran with and the conda that the update installed

I'm not so sure. The code that had the problem was probably the in-memory old version. And then conda "uninstalled itself." That's the part that 4.3 fixes.

**Comment by mingwandroid** [comment]
Are you sure that's how it works? What happens for a module that hasn't yet been imported? Presumably the new code gets loaded.

Also, what about my suggestion that conda update should first update itself and exit before updating anything else?

**Comment by kalefranz** [comment]
> What happens for a module that hasn't yet been imported? Presumably the new code gets loaded.

Yes, the new code would get loaded.  But it's unlikely (or maybe impossible) that, by the time you've uninstalled and reinstalled something, that there is any new code to load.

> Also, what about my suggestion that conda update should first update itself and exit before updating anything else?

I'm thinking through it and what it would look like :)

**Comment by mingwandroid** [comment]
It might be easier once conda is a shell script ...

**Comment by mcg1969** [comment]
I'd say the effort is better spent moving people towards an isolated environment for conda itself.

**Comment by xuxgeo** [comment]
I'm having the same problem on Windows 10. The conda update --all failed with [this](https://github.com/conda/conda/issues/1786) error. After that the conda script is missing.

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda2  (writable)
    default environment : C:\Program Files\Anaconda2
       envs directories : C:\Program Files\Anaconda2\envs
          package cache : C:\Program Files\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

**Comment by kalefranz** [comment]
@xuxgeo you'll have to download miniconda again and re-install it overtop of `C:\Program Files\Anaconda2`.  conda 4.3 shouldn't ever leave you in this state again.
