### ISSUE TITLE
Invalid requirement while trying to use pip options

### ISSUE THREAD

**Issue by eyadsibai** [conda/conda#4378]
Hi!

I have in my pip section inside envrionment.yaml file this line
```- rep --install-option='--no-deps'```

while I am trying to update my environment I am getting this error

```Invalid requirement: 'rep --install-option='--no-deps''```

if I do pip -r requirements.txt and I have that line as it is in requirements.txt it works.

**Comment by sdvillal** [comment]
Give a look to #3969. The short answer is that this is not possible until something like the changes proposed there is added to conda-env.
