### ISSUE TITLE
Inadvertent downgrade to python=2.7; now cannot install python=3.4

### ISSUE THREAD

**Issue by AMacInnes** [conda/conda#4390]
Inadvertent downgrade to python=2.7; now cannot install python=3.4
I am using a Mac and tried conda install python=2.7 
unfortunately i whizzed by the notice that python3.4 would be downgraded
Now conda remove python=2.7 does not allow files to be removed nor does conda install python=3.4

Any help would be appreciated.

Error msg
UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34 -> python 2.7*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.

**Comment by kalefranz** [comment]
conda uninstall enum34

**Comment by AMacInnes** [comment]
[cid:C550C2D2-DA08-4243-B164-D5C21F4A985B]

Still not able to install python=3.4 after uninstall enum34

Thanks for your help.
