### ISSUE TITLE
conda fails to enable jupyter

### ISSUE THREAD

**Issue by nitinvaish** [conda/conda#4395]
hi, 

i'm creating a conda environment that is provisioned with the libraries i need for a project. it however doesn't enable jupyter and gives segmentation fault (attached). any ideas how to resolve this? 

thanks!
![screen shot 2017-01-21 at 4 16 44 pm](https://cloud.githubusercontent.com/assets/25273228/22178756/1557a652-dff5-11e6-8b0d-26b42bba9929.png)

**Comment by kalefranz** [comment]
We'll have 4.3.7 out in the next 24-48 hours. It may fix this. If it doesn't, then there's something else going on that's related to the way packages are built rather than how conda is installing them.

**Comment by kalefranz** [comment]
conda 4.3.7 is available now.  Please update this ticket if it fails to resolve the issue.

**Comment by mingwandroid** [comment]
@kalefranz, I suspect this might be on macOS (neé OSX) < 10.9. Can we get the output from `uname -r` included in `conda-info`? I think that will be important as many recently build packages will fail like this on < 10.9.

**Comment by nitinvaish** [comment]
yes, i'm on OS 10.7.5 - is this the issue then? how do i resolve it? thanks!

**Comment by kalefranz** [comment]
> how do i resolve it?

update your operating system to OSX >= 10.9

10.7 is many years beyond end-of-life and is no longer getting security updates from Apple.  Using repo.continuum.io with OSX 10.7 or 10.8 is likely to result in unspecified behavior.

**Comment by mingwandroid** [comment]
We can be fairly specific and say it will result in segfaults. Can you add the `uname -r` info please Kale? It will save us time in future I reckon.

**Comment by kalefranz** [comment]
If the report had contained the full `conda info`, the user-agent string would have been included.  Here's mine currently

     user-agent : conda/4.3.8.post11+35dff973a requests/2.10.0 CPython/2.7.12 Darwin/16.3.0 OSX/10.12.2

The `uname -r` info is right there :)
