### ISSUE TITLE
Installing R in a folder with spaces in name generates errors

### ISSUE THREAD

**Issue by lasimon** [conda/conda#4403]
conda install -c r r-essentials
on Windows 10 to install into C:\Users\Larry Simon (note space in name) generated the following:
echo **** post_link.bat for m2w64-p11-kit ****
**** post_link.bat for m2w64-p11-kit ****
p11-kit: 'Simon/Anaconda2/Library/mingw-w64/bin/trust' is not a valid command. See 'Larry --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Simon/Anaconda2/Library/mingw-w64/bin/trust' is not a valid command. See 'Larry --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Simon/Anaconda2/Library/mingw-w64/bin/trust' is not a valid command. See 'Larry --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Simon/Anaconda2/Library/mingw-w64/bin/trust' is not a valid command. See 'Larry --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Simon/Anaconda2/Library/mingw-w64/bin/trust' is not a valid command. See 'Larry --help'
p11-kit: couldn't run trust tool: No error
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by mingwandroid** [comment]
In this instance, those warnings are benign and R should still work, however we strongly discourage installing Anaconda or Miniconda to a path containing spaces.
