### ISSUE TITLE
Unsatisfiability hint code can take too long

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#441]
The way the "Hint: the following combinations of packages create a conflict with the
remaining packages" code works is that it tries to remove one at a time, then two at a time, and so on, until it finds the largest subset that is satisfiable. But this can be combinatorially too large if there are many packages. There should be a sanity limit on it. We need to play with it to see what's reasonable.

**Comment by kalefranz** [comment]
Closing.  Outdated.
