### ISSUE TITLE
Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0- 0.tar.bz2 An unexpected error has occurred.

### ISSUE THREAD

**Issue by ghost** [conda/conda#4412]
while updating conda using command 'conda update conda ' i am getting following error

Fetching package metadata ...SSL verification error: [SSL: CERTIFICATE_VERIFY_FA
ILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:590)
.....
Solving package specifications: ..........

Package plan for installation in environment D:\gegdc\VD475768\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-
0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : D:\gegdc\VD475768\Anaconda  (writable)
    default environment : D:\gegdc\VD475768\Anaconda
       envs directories : D:\gegdc\VD475768\Anaconda\envs
          package cache : D:\gegdc\VD475768\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ D:\gegdc\VD475768\Anaconda\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "D:\gegdc\VD475768\Anaconda\lib\site-packages\conda\exceptions.py", l
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\gegdc\VD475768\Anaconda\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "D:\gegdc\VD475768\Anaconda\lib\site-packages\conda\cli\main_update.p
y", line 65, in execute
        install(args, parser, 'update')
      File "D:\gegdc\VD475768\Anaconda\lib\site-packages\conda\cli\install.py",
line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection er
ror: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): ht
tps://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2

**Comment by kalefranz** [comment]
The easiest fix to this right now is

    conda config --set ssl_verify false
    conda update conda
    conda config --remove-key ssl_verify

Please let me know if that doesn't fix the problem for you.
