### ISSUE TITLE
No docs about "licence"

### ISSUE THREAD

**Issue by guettli** [conda/conda#4420]
I think this search should return a result:

https://github.com/conda/conda/search?q=licence

**Comment by groutr** [comment]
This search returns 41 results.  Is it the result you're looking for?
https://github.com/conda/conda/search?q=license

**Comment by kalefranz** [comment]
License is also displayed right at the top of the project

![image](https://cloud.githubusercontent.com/assets/1418419/22257386/838e9240-e223-11e6-980d-6dc0e7ab1769.png)

Any advice on actually making your search work as you want @guettli?  GitHub documentation anywhere?

**Comment by guettli** [comment]
I am very sorry. It was a typo: licence vs license. Yes, all information is there. I was blind.
