### ISSUE TITLE
CondaOSError: OS error failed to link - Cannot update anything with fresh install

### ISSUE THREAD

**Issue by jstaf** [conda/conda#4422]
I just did a fresh install of Anaconda3-4.2.0 on CentOS 7.3, no other commands have been run. Attempting to run `conda update conda`, `conda update --all` or even `conda update conda -c conda-canary` results in conda breaking itself:

```
$ ./conda update conda -c conda-canary

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 210.43 kB/s
requests-2.12. 100% |################################| Time: 0:00:00  13.47 MB/s
pyopenssl-16.2 100% |################################| Time: 0:00:00   5.33 MB/s
conda-4.3.8-py 100% |################################| Time: 0:00:00   1.78 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
CondaOSError: OS error: failed to link (src='/global/software/python/anaconda3/pkgs/conda-4.3.8-py35_0/bin/conda', dst='/global/software/python/anaconda3/bin/conda', type=3, error=PermissionError(13, 'Permission denied'))

]$ ./conda --help
-bash: ./conda: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory
```

Strange, considering anaconda isn't even installed in /opt. Even more strangely, Anaconda2 works just fine.

**Comment by kalefranz** [comment]
Conda 4.3 won't have this problem of uninstalling itself or corrupting itself.  The cause of the issue here is

    CondaOSError: OS error: failed to link (src='/global/software/python/anaconda3/pkgs/conda-4.3.8-py35_0/bin/conda', dst='/global/software/python/anaconda3/bin/conda', type=3, error=PermissionError(13, 'Permission denied'))

With the same user as your ran the `conda update conda -c conda-canary`, you should also get a permissions error with

    cp /global/software/python/anaconda3/pkgs/conda-4.3.8-py35_0/bin/conda /global/software/python/anaconda3/bin/conda

So this is just a permissions issue it looks like for the path

    /global/software/python/anaconda3/bin/conda

**Comment by jstaf** [comment]
Hmmm... running `conda update` as root indeed fixes things. 

Very odd though, conda was installed under a non-root user, and should not require any special permissions to update (and the same upgrade process worked for the Python2 version of Anaconda without incident).
