### ISSUE TITLE
Cannot upgrade pandas or other packages

### ISSUE THREAD

**Issue by xfsm1912** [conda/conda#4425]
My anaconda suddenly cannot upgrade pandas or other packages. As I type "conda upgrade pandas", it will return:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/Jianhua/anaconda  (writable)
    default environment : /Users/Jianhua/anaconda
       envs directories : /Users/Jianhua/anaconda/envs
          package cache : /Users/Jianhua/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`$ /Users/Jianhua/anaconda/bin/conda upgrade pandas`

    Traceback (most recent call last):
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 136, in install
        linked_dists = install_linked(prefix)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 121, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 34, in load_linked_data
        rec = json.load(fi)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/Jianhua/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

Can someone tell me what is going on?

Thank you so much!

**Comment by kalefranz** [comment]
Open python, then run this:

```
from glob import glob
from json import loads
for path in glob('/Users/Jianhua/anaconda/conda-meta/*.json'):
    try:
        with open(path) as fh:
            data = loads(fh.read())
    except:
        print(path)
        print(data)
        raise
```

What output does that give?

**Comment by xfsm1912** [comment]
Hi, Kalefranz

Thank you for your response first. By your code, I got the output:
/Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json

**Comment by kalefranz** [comment]
Well that's sure interesting. CC @msarahan. I wonder if this is related to some other recent issues... I can't see exactly how just yet though...

**Comment by kalefranz** [comment]
This blank conda-meta file... it's possible I have an off-by-one index error somewhere in the rollback code that could lead to this maybe...

**Comment by kalefranz** [comment]
@xfsm1912 Let's try this... 

    rm /Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json

Then run that python code again.  Make sure it comes back without printing anything.  I mean, make sure nothing happens when you run that code snippet now.  Then

    conda install --no-deps mkl=2017

Let me know how that goes...

**Comment by xfsm1912** [comment]
after delete the mkl-2017.0.1-0.json, nothing is output as running the previous code. But running install code, I got:

[Jianhua@d-172-26-7-254~]$ conda install --no-deps mkl=2017
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/Jianhua/anaconda:

The following packages will be UPDATED:

    mkl: 11.3.3-0 --> 2017.0.1-0

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'defaults::mkl-2017.0.1-0'.
LookupError('unknown encoding: ',)
Attempting to roll back.



LookupError('unknown encoding: ',)

**Comment by kalefranz** [comment]
Now I'm even more confused.  But I think we're making progress...

How about

    conda install --no-deps mkl=2017 -v -v -v

?  It might be a LOT of output.  That's ok.  Too much is better than not enough.

**Comment by xfsm1912** [comment]
[Jianhua@d-172-26-7-254~]$ conda install --no-deps mkl=2017 -v -v -v
DEBUG conda.cli.main:_main(135): verbosity set to 3
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/Jianhua/anaconda  (writable)
    default environment : /Users/Jianhua/anaconda
       envs directories : /Users/Jianhua/anaconda/envs
          package cache : /Users/Jianhua/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20



`$ /Users/Jianhua/anaconda/bin/conda install --no-deps mkl=2017 -v -v -v`




    Traceback (most recent call last):
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 136, in install
        linked_dists = install_linked(prefix)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 121, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 34, in load_linked_data
        rec = json.load(fi)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/Users/Jianhua/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/Jianhua/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

No JSON again

**Comment by kalefranz** [comment]
Oh even better!  One more time

    rm /Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json

and then now 

    conda install --no-deps mkl=2017 -v -v -v

**Comment by xfsm1912** [comment]
As I type conda install --no-deps mkl=2017 -v -v -v, output is a lot, but finally:
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/Jianhua/anaconda  (writable)
    default environment : /Users/Jianhua/anaconda
       envs directories : /Users/Jianhua/anaconda/envs
          package cache : /Users/Jianhua/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20



`$ /Users/Jianhua/anaconda/bin/conda install --no-deps mkl=2017 -v -v -v`




    Traceback (most recent call last):
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 277, in execute
        rollback_excs,
    CondaMultiError: unknown encoding:

**Comment by kalefranz** [comment]
Unfortunately that doesn't quite help.  I actually need the full output.  You can email it to me in a file if you'd like.  kale@franz.io

**Comment by kalefranz** [comment]
As emailed to me, the important pieces of the full debug output are

```
INFO conda.core.link:_execute_actions(300): ===> LINKING PACKAGE: defaults::mkl-2017.0.1-0 <===
  prefix=/Users/Jianhua/anaconda
  source=/Users/Jianhua/anaconda/pkgs/mkl-2017.0.1-0

TRACE conda.core.path_actions:execute(517): creating linked package record /Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json
DEBUG conda.core.link:_execute_actions(311): Error in action #0 for pkg_idx #1 CreateLinkedPackageRecordAction(linked_package_record=IndexRecord(_IndexRecord__initd=True, arch=u'x86_64', build=u'0', build_number=0, date=u'2017-01-10', depends=(), license=u'proprietary - Intel', license_family=u'Proprietary', md5=u'435fd00978b584ac45619b6123b0ba9b', name=u'mkl', platform=u'darwin', requires=(), size=116187988, subdir=u'osx-64', version=u'2017.0.1', fn=u'mkl-2017.0.1-0.tar.bz2', schannel=u'defaults', channel=u'https://repo.continuum.io/pkgs/free/osx-64', priority=0, url=u'https://repo.continuum.io/pkgs/free/osx-64/mkl-2017.0.1-0.tar.bz2', auth=None, files=('lib/libiomp5.dylib', 'lib/libmkl_avx.dylib', 'lib/libmkl_avx2.dylib', 'lib/libmkl_avx512.dylib', 'lib/libmkl_core.dylib', 'lib/libmkl_intel.dylib', 'lib/libmkl_intel_ilp64.dylib', 'lib/libmkl_intel_lp64.dylib', 'lib/libmkl_intel_thread.dylib', 'lib/libmkl_mc.dylib', 'lib/libmkl_mc3.dylib', 'lib/libmkl_rt.dylib', 'lib/libmkl_sequential.dylib', 'lib/libmkl_tbb_thread.dylib', 'lib/libmkl_vml_avx.dylib', 'lib/libmkl_vml_avx2.dylib', 'lib/libmkl_vml_avx512.dylib', 'lib/libmkl_vml_mc.dylib', 'lib/libmkl_vml_mc2.dylib', 'lib/libmkl_vml_mc3.dylib'), link=Link(_Link__initd=True, source=u'/Users/Jianhua/anaconda/pkgs/mkl-2017.0.1-0', type=1), with_features_depends=frozendict(), preferred_env=None), _record_written_to_disk=False, _verified=True, target_short_path=u'conda-meta/mkl-2017.0.1-0.json', target_prefix=u'/Users/Jianhua/anaconda', _linked_data_loaded=False, source_prefix=None, source_short_path=None)
DEBUG conda.core.link:_execute_actions(312): Traceback (most recent call last):
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 307, in _execute_actions
    action.execute()
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/core/path_actions.py", line 519, in execute
    write_linked_package_record(self.target_prefix, self.linked_package_record)
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/gateways/disk/create.py", line 116, in write_linked_package_record
    with open(conda_meta_full_path, 'w') as fo:
LookupError: unknown encoding:

ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'defaults::mkl-2017.0.1-0'.
LookupError('unknown encoding: ',)
Attempting to roll back.

INFO conda.core.link:_reverse_actions(342): ===> REVERSING PACKAGE LINK: defaults::mkl-2017.0.1-0 <===
  prefix=/Users/Jianhua/anaconda

DEBUG conda.core.link:_reverse_actions(343): reversing pkg_idx #1 from axn_idx #0
TRACE conda.core.path_actions:reverse(527): reversing linked package record creation /Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json
TRACE conda.core.path_actions:reverse(534): record was not created /Users/Jianhua/anaconda/conda-meta/mkl-2017.0.1-0.json
```

**Comment by kalefranz** [comment]
I'm not sure if #4433 fixes this, but we're sure going to try it.  This error is really weird, and google isn't helping me...

The line throwing the error is

    with open(conda_meta_full_path, 'w') as fo:

The `open` function we're using is actually `io.open`, and you're experiencing this with python 2.7.  The exception message is

    LookupError: unknown encoding:

`io.open` optionally takes an encoding argument.  So it's sort of an "empty string" unknown encoding.  

Given all of this, I'm hopeful that #4433 fixes the issue, but I can't myself reproduce it so I can't be sure.

**Comment by xfsm1912** [comment]
OK, sound the problem is weird. How about I reinstall the anaconda again in Python 2.7? That may fix the problem.

**Comment by kalefranz** [comment]
It's possible.  If you don't mind, an alternate solution.  Try installing anaconda in python 3.  I understand you may have need for python 2.7 in certain projects, and you can always roll back.  Or you can just use separate conda environments for your python 2.7 work :)

But I'm actually curious if on your specific system you hit the same problem when conda is running under python3 rather than python2.
