### ISSUE TITLE
Error while installing Jupyter in anaconda

### ISSUE THREAD

**Issue by supercool276** [conda/conda#4434]
Installing collected packages: scandir, pathlib2, pickleshare, packaging, appdirs, setuptools, ipython, ipykernel, functools32, jsonschema, nbformat, mistune, html5lib, bleach, pandocfilters, configparser, entrypoints, testpath, nbconvert, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-console, jupyter
  Running setup.py install for scandir ... error
    Complete output from command c:\users\rishabh\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\rishabh\\appdata\\local\\temp\\pip-build-i9uf1e\\scandir\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\rishabh\appdata\local\temp\pip-cjmbwu-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying scandir.py -> build\lib.win32-2.7
    running build_ext
    building '_scandir' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    C:\Users\RISHABH\Anaconda\Scripts\gcc.bat -mdll -O -Wall -Ic:\users\rishabh\anaconda\include -Ic:\users\rishabh\anaconda\PC -c _scandir.c -o build\temp.win32-2.7\Release\_scandir.o
    In file included from _scandir.c:21:0:
    winreparse.h:45:0: warning: "MAXIMUM_REPARSE_DATA_BUFFER_SIZE" redefined [enabled by default]
    In file included from c:\users\rishabh\anaconda\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/windef.h:137:0,
                     from c:\users\rishabh\anaconda\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/windows.h:59,
                     from _scandir.c:20:
    c:\users\rishabh\anaconda\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/winnt.h:3863:0: note: this is the location of the previous definition
    _scandir.c: In function 'get_target_path':
    _scandir.c:194:5: warning: implicit declaration of function 'GetFinalPathNameByHandleW' [-Wimplicit-function-declaration]
    _scandir.c:195:42: error: 'VOLUME_NAME_DOS' undeclared (first use in this function)
    _scandir.c:195:42: note: each undeclared identifier is reported only once for each function it appears in
    _scandir.c: In function 'path_converter':
    _scandir.c:799:13: warning: too many arguments for format [-Wformat-extra-args]
    error: command 'C:\\Users\\RISHABH\\Anaconda\\Scripts\\gcc.bat' failed with exit status 1

**Comment by kalefranz** [comment]
There is literally nothing here that is related directly or indirectly to the conda command I don't think.  I'm not sure what you're trying to do, but I'm pretty sure you've filed your issue in the wrong spot.  Sorry I can't help more.
