### ISSUE TITLE
Anaconda Navigator

### ISSUE THREAD

**Issue by Chimsom** [conda/conda#4435]
Anaconda Navigator is not launching!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After I update packages on the navigator, it stops launching
I have uninstall and install and the problem is still not fixed...
Here is what it says when I tried using
![image](https://cloud.githubusercontent.com/assets/25299235/22333925/2120c4ec-e3e1-11e6-8189-68481b0c9a38.png)

Please help!
Thank you

**Comment by kalefranz** [comment]
I think just run `conda install _license`.
