### ISSUE TITLE
'NoPackagesFoundError' object has no attribute 'packages'

### ISSUE THREAD

**Issue by danfischetti** [conda/conda#4437]
I'm running conda 4.3.8 with conda-build 2.1.2. and I get this error when I try to build a package with unsatisfiable dependencies. conda-build/build.py:1521 tries to access the 'packages' attribute of the NoPackagesFoundError but in https://github.com/conda/conda/blob/master/conda/exceptions.py the class is defined with the attribute 'pkgs'

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1708
