### ISSUE TITLE
Problems installing phyluce through conda

### ISSUE THREAD

**Issue by TiagoSousaNeves** [conda/conda#4446]
conda install phyluce`

Fetching package metadata ...Could not connect to https://conda.binstar.org/faircloth-lab/noarch/
Could not connect to https://conda.binstar.org/faircloth-lab/linux-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://conda.binstar.org/faircloth-lab/linux-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /illumina/tiago/Software/anaconda2  (writable)
    default environment : /illumina/tiago/Software/anaconda2
       envs directories : /illumina/tiago/Software/anaconda2/envs
          package cache : /illumina/tiago/Software/anaconda2/pkgs
           channel URLs : https://conda.binstar.org/faircloth-lab/linux-64/
                          https://conda.binstar.org/faircloth-lab/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /illumina/tiago/.condarc
           offline mode : False

`$ /illumina/tiago/Software/anaconda2/bin/conda install phyluce`

    Traceback (most recent call last):
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.binstar.org', port=443): Max retries exceeded with url: /faircloth-lab/linux-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f54ce62cc50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)): https://conda.binstar.org/faircloth-lab/linux-64/ 

Can you help me please?

**Comment by kalefranz** [comment]
In your file `/illumina/tiago/.condarc` remove `https://conda.binstar.org/faircloth-lab`.  If you want to add it back, just add it as `faircloth-lab`.  Then `conda update conda`.

**Comment by TiagoSousaNeves** [comment]
I did it! Now I got this:

[tiago@illuminaserver ~]$ conda update conda
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /illumina/tiago/Software/anaconda2  (writable)
    default environment : /illumina/tiago/Software/anaconda2
       envs directories : /illumina/tiago/Software/anaconda2/envs
          package cache : /illumina/tiago/Software/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /illumina/tiago/.condarc
           offline mode : False



`$ /illumina/tiago/Software/anaconda2/bin/conda update conda`




    Traceback (most recent call last):
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/illumina/tiago/Software/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe24af2d7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)): https://repo.continuum.io/pkgs/free/linux-64/

**Comment by kalefranz** [comment]
What do you get for

    dig repo.continuum.io

?

**Comment by TiagoSousaNeves** [comment]
; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.23.rc1.el6_5.1 <<>> repo.continuum.io
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by kalefranz** [comment]
Yeah you have a network configuration issue on your machine.  I'm guessing this like `curl -L www.google.com` also don't work?  I can't really help you beyond this point.

**Comment by TiagoSousaNeves** [comment]
Yes, you guess right! it doesn't work!
I will contact the cluster manager to see what is going on!
Thanks

TSN
