### ISSUE TITLE
Document breaking changes in --json in command line, better python API doc

### ISSUE THREAD

**Issue by davidslac** [conda/conda#4448]
I'm working on updating conda from 4.2.13 to 4.3.8, I have been using 
```conda list --json```
to get the packages in a environment, that used to parse as a list of strings, but now it is a list of dicts, looks great! But would be nice if the change migrated to the changelog, (which I found at http://conda.pydata.org/docs/changelog.html). 

Side issue, better documentation on using the Python API for conda, the changelog mentions new things
```
conda.cli and conda.exports
```
I do the conda management from an environment other than root, so I need to know how to get those there, I once found a blog post about installing a conda xface package, https://github.com/conda/conda-api  but maybe if this made its way into the mainstream conda docs, would be helpful, and maybe that package is out of date?

Anyways, excited by all the new features in conda 4.3.8! Multi-user, etc. conda is getting more traction here, people like it.

**Comment by kalefranz** [comment]
I'm spending a lot more time on documentation over the coming months.  I'm committing to writing one blog post a week, which will ultimately be turned into documentation as well.

For all of our "communication" outside of conda, I'm working toward turning everything we print, whether it's an error or just a general message, into an object.  Then we can deserialize or present it based on the context.  It's a WIP, but it'll continue to get better.
