### ISSUE TITLE
`conda config --add channels` is not what it says it is

### ISSUE THREAD

**Issue by basnijholt** [conda/conda#4452]
adding multiple channels doesn't work, so the name should be:
`conda config --add channel`

**Comment by bsipocz** [comment]
@basnijholt - in my reading in the configuration there is a key ``channels``, so it should be indeed used as ``channels`` in the command above. It's unfortunate that currently it's not possible to add multiple values for a given key. 
However it's a useful feature request I think.

**Comment by kalefranz** [comment]
> It's unfortunate that currently it's not possible to add multiple values for a given key.

Implementing that capability would be a good first issue for a new contributor.

**Comment by marcelotrevisani** [comment]
Today after work I will try to add that

**Comment by jdhalimi** [comment]
Hello, I tried an implementation [here](https://github.com/jdhalimi/conda/commit/10ee2c9c5bc557c3545a61f85f579a444c01bb3f) and it seems to support both

``conda config --add channels conda-canary``
``conda config --add channel conda-canary``

**Comment by mbargull** [comment]
Thanks for taking a look at this @jdhalimi. To retain the one-to-one mapping of configuration parameters from `conda config` and `.condarc`, I think we don't necessarily want to enable/translate `conda config --add channel conda-canary`. Rather, we should just allow the currently supported
```
conda config --add channels defaults --add channels conda-canary
```
to be optionally be given as
```
conda config --add channels conda-canary defaults
```
. This likely just requires `nargs=2` to be changed to `nargs='+'` at
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/conda_argparse.py#L446
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/conda_argparse.py#L454
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/conda_argparse.py#L470
and loop over the those multiple values accordingly at
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/main_config.py#L281
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/main_config.py#L317
.

**Comment by mbargull** [comment]
Note that for `--add` (which is an alias for `--prepend`)
```
conda config --add channels defaults --add channels conda-canary
```
translates to
```
conda config --add channels defaults
conda config --add channels conda-canary
```
and thus to
```yaml
channels:
  - conda-canary
  - defaults
```
. When supporting `nargs='+'`, the reverse order, i.e.,
```
conda config --add channels conda-canary defaults
```
would be more natural. Hence, you'd need to take care of this change of order when expanding the loop at
https://github.com/conda/conda/blob/4.6.0a2/conda/cli/main_config.py#L281
.

**Comment by jdhalimi** [comment]
hello @mbargull,

thank you for having a look at this change, I was training my github skills with  a "good first issue"
I didn't expect you would spend time on it as I didn't post a pull request.

I strongly agree that changing ``conda config`` is not a big improvement and will involve regressions for users that uses it already.

I read your suggestions for handling multiple channels in one call. I also prefer this approach (even if it is almost equivalent to multiple calls to --add channels).

I will try to submit an implementation in my repo as soon as I have a piece of time.

Thanks again,
Jean-David.

**Comment by kalefranz** [comment]
In my comment above, I think what I had in mind was

    conda config --add channels conda-canary --add channels defaults --set path_conflict warn
