### ISSUE TITLE
Conda update - An unexpected error has occurred - now Conda can't be found

### ISSUE THREAD

**Issue by bluemonk482** [conda/conda#4458]
I have not used my macbook for work for a while now so I needed to update a few python packages and this happened..

> MacBook-Pro:~ bowang$ conda update scipy
> Fetching package metadata .........
> Solving package specifications: ..........
> 
> Package plan for installation in environment /Users/bowang/anaconda:
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     mkl-2017.0.1               |                0       110.8 MB
>     numpy-1.11.3               |           py27_0         3.2 MB
>     requests-2.12.4            |           py27_0         752 KB
>     scipy-0.18.1               |      np111py27_1        13.7 MB
>     cryptography-1.7.1         |           py27_0         468 KB
>     pyopenssl-16.2.0           |           py27_0          68 KB
>     conda-4.3.8                |           py27_0         467 KB
>     ------------------------------------------------------------
>                                            Total:       129.4 MB
> 
> The following packages will be UPDATED:
> 
>     conda:        4.2.13-py27_0      --> 4.3.8-py27_0      
>     cryptography: 1.3.1-py27_0       --> 1.7.1-py27_0      
>     mkl:          11.3.3-0           --> 2017.0.1-0        
>     numpy:        1.11.2-py27_0      --> 1.11.3-py27_0     
>     pyopenssl:    0.15.1-py27_2      --> 16.2.0-py27_0     
>     requests:     2.9.1-py27_0       --> 2.12.4-py27_0     
>     scipy:        0.18.1-np111py27_0 --> 0.18.1-np111py27_1
> 
> Proceed ([y]/n)? y
> 
> Fetching packages ...
> mkl-2017.0.1-0 100% |##############################################################################| Time: 0:01:01   1.88 MB/s
> numpy-1.11.3-p 100% |##############################################################################| Time: 0:00:02   1.35 MB/s
> requests-2.12. 100% |##############################################################################| Time: 0:00:00   1.43 MB/s
> scipy-0.18.1-n 100% |##############################################################################| Time: 0:00:07   1.80 MB/s
> cryptography-1 100% |##############################################################################| Time: 0:00:00 994.33 kB/s
> pyopenssl-16.2 100% |##############################################################################| Time: 0:00:00 542.20 kB/s
> conda-4.3.8-py 100% |##############################################################################| Time: 0:00:00 801.59 kB/s
> Extracting packages ...
> [      COMPLETE      ]|#################################################################################################| 100%
> Unlinking packages ...
> [      COMPLETE      ]|#################################################################################################| 100%
> Linking packages ...
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : osx-64
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : 0+unknown
>          python version : 2.7.12.final.0
>        requests version : 2.12.4
>        root environment : /Users/bowang/anaconda  (writable)
>     default environment : /Users/bowang/anaconda
>        envs directories : /Users/bowang/anaconda/envs
>           package cache : /Users/bowang/anaconda/pkgs
>            channel URLs : https://conda.anaconda.org/spacy/osx-64
>                           https://conda.anaconda.org/spacy/noarch
>                           https://repo.continuum.io/pkgs/free/osx-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/osx-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : /Users/bowang/.condarc
>            offline mode : False
> 
> 
> 
> `$ /Users/bowang/anaconda/bin/conda update scipy`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
>         install(args, parser, 'update')
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 405, in install
>         execute_actions(actions, index, verbose=not context.quiet)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
>         inst.execute_instructions(plan, index, verbose)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
>         cmd(state, arg)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
>         link(state['prefix'], dist, lt, index=state['index'])
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/install.py", line 986, in link
>         _link(src, dst, lt)
>       File "/Users/bowang/anaconda/lib/python2.7/site-packages/conda/install.py", line 171, in _link
>         shutil.copy2(src, dst)
>       File "/Users/bowang/anaconda/lib/python2.7/shutil.py", line 130, in copy2
>         copyfile(src, dst)
>       File "/Users/bowang/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
>         with open(dst, 'wb') as fdst:
>     IOError: [Errno 13] Permission denied: '/Users/bowang/anaconda/lib/python2.7/site-packages/numpy/__config__.py'

Now Conda can't be found:

> MacBook-Pro:~ bowang$ conda update scipy
> -bash: /Users/bowang/anaconda/bin/conda: No such file or directory

**Comment by kalefranz** [comment]
Unfortunately you're going to have to install miniconda back over your current install to heal the problem.  If you look at `/Users/bowang/anaconda/lib/python2.7/site-packages/numpy/__config__.py`, it probably has different permissions than the what the current user running conda did.  Anaconda 4.3 is coming out soon, which comes with conda 4.3, which won't ever let you get into this situation to begin with.
