### ISSUE TITLE
Does Conda have too big of a window where it captures SIGTERM?

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4466]
Conda should definitely capture `SIGTERM` when it is performing critical sections like environment updates and creation.  But other times it shouldn't hold `SIGTERM`, in my opinion.  Just now I had Conda apparently stuck in the "Solving package specification" stage.  This has no state-changing effect on my system and therefore, I believe, it should be safe to `CTRL-C` that step.  But no dice.  I had to find the PID and `kill -9` (`SIGKILL`) the process.  That felt unnecessary to me.

```
$ conda create -n rcore -c r -c bioconda anaconda python=3.5 \
>                            r-essentials r-devtools r-viridis r-nycflights13
Fetching package metadata ...............
Solving package specifications: .^C^C^C^C




Killed: 9
```

**Comment by kalefranz** [comment]
Yeah at some point in the 4.3.x release series I rolled back the signal handler usage to only wrap the unlink-link transaction.  We attach and then detach the handlers in a `with` context isolated to that transaction now.
