### ISSUE TITLE
Default channel documentation

### ISSUE THREAD

**Issue by samerafach** [conda/conda#4469]
I've been digging for 2 days to find information on how to add my package to the default channel so that a `conda install mypackage` will work without having to add my personal channel locally.

Is there any documentation that explains how PyQt, h5py and other similar libraries get a place in the default channel, and what requirements have to be there for other organizations/people to get it?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1675
