### ISSUE TITLE
Crash and can't open - python 3.6 update (macOS)

### ISSUE THREAD

**Issue by Ansolix** [conda/conda#4471]
On macOS Sierra,
When trying to update python module from 3.5 to 3.6, Anaconda crashes without any error message and does not open anymore even after restarting the app and even the computer, so I have to uninstall Anaconda and re-install it

**Comment by kalefranz** [comment]
@goanpeca where's the public issue tracker for Navi?

**Comment by kalefranz** [comment]
@Ansolix If you're still having your issue, please file a ticket at https://github.com/ContinuumIO/anaconda-issues
