### ISSUE TITLE
Anaconda 4.2.0, python3.5 version on mac, is this normal?

### ISSUE THREAD

**Issue by cidj** [conda/conda#4475]
The installation succeeded. (The path is /Applications/anaconda3/). And I opened the Anaconda-Navigator, and lauched jupyter note book (4.2.3). And a terminal automatically appeared and shows some errors here (below). Is it normal?

------------------------------------------------------------------------
Last login: Sun Jan 29 16:43:36 on ttys000
/Applications/anaconda3/anaconda/bin/jupyter_mac.command ; exit;
➜  ~ /Applications/anaconda3/anaconda/bin/jupyter_mac.command ; exit;
[E 16:48:55.754 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[I 16:48:55.755 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 16:48:56.295 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 16:48:56.296 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 16:48:56.331 NotebookApp] [nb_anacondacloud] enabled
[I 16:48:56.334 NotebookApp] [nb_conda] enabled
[I 16:48:56.338 NotebookApp] Serving notebooks from local directory: /Users/tao
[I 16:48:56.338 NotebookApp] 0 active kernels 
[I 16:48:56.338 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 16:48:56.338 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 16:48:58.209 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/nb_conda/handlers.py", line 51, in get
        self.finish(json.dumps(self.env_manager.list_envs()))
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/nb_conda/envmanager.py", line 58, in list_envs
        info = self.clean_conda_json(self._execute('conda info --json'))
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/nb_conda/envmanager.py", line 44, in _execute
        output = check_output(cmdline)
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda'
[E 16:48:58.211 NotebookApp] {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree",
      "Host": "localhost:8888",
      "Accept-Language": "en-us",
      "X-Requested-With": "XMLHttpRequest",
      "Accept": "application/json, text/javascript, */*; q=0.01"
    }
[E 16:48:58.211 NotebookApp] 500 GET /conda/environments?_=1485726537114 (::1) 6.20ms referer=http://localhost:8888/tree
[E 16:48:58.217 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/nb_conda/handlers.py", line 229, in get
        data = searcher.list_available(self)
      File "/Applications/anaconda3/anaconda/lib/python3.5/site-packages/nb_conda/handlers.py", line 213, in list_available
        bufsize=4096)
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/Applications/anaconda3/anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda'
[E 16:48:58.218 NotebookApp] {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree",
      "Host": "localhost:8888",
      "Accept-Language": "en-us",
      "X-Requested-With": "XMLHttpRequest",
      "Accept": "application/json, text/javascript, */*; q=0.01"
    }
[E 16:48:58.218 NotebookApp] 500 GET /conda/packages/available?_=1485726537115 (::1) 5.68ms referer=http://localhost:8888/tree

**Comment by cidj** [comment]
~ /Applications/anaconda3/anaconda/bin/conda info     
Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Applications/anaconda3/anaconda  (writable)
    default environment : /Applications/anaconda3/anaconda
       envs directories : /Applications/anaconda3/anaconda/envs
          package cache : /Applications/anaconda3/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

**Comment by cidj** [comment]
In jupyter, python3 runs normally. However, when I click the label "conda", it shows:

" An error occurred while listing Conda environments.
Internal Server Error"

**Comment by cidj** [comment]
Could you help me figure this out? If you need any further test, I'll do it and paste the results here. Thanks!

**Comment by nehaljwani** [comment]
@cidj Did you try the same thing after activating the environment and then running jupyter? If you don't want to do that, try adding /Applications/anaconda3/anaconda/bin/ to your PATH env variable.

**Comment by cidj** [comment]
@nehaljwani 
Sorry for my late reply. It works! Thank you very much!
By the way, I found Anaconda for Python 2.7 doesn't have this issue. It works quite well.
