### ISSUE TITLE
Additional architectures cannot be added without code modification

### ISSUE THREAD

**Issue by gabm** [conda/conda#4479]
We are using additional architectures with conda to ship our binaries. Currently we are adding those addtional architectures through a patch directly to the hard-coded array inside conda. We ship these changes in a custom binary version of conda for these custom architectures.

However, this raises two problems: 1) more maintaining efforts on our side and 2) other platforms still don't know about these additional architectures. That is currently blocking our CI processes, as we want to skip packages for certain platforms.

I'd suggest to add a possibility to extend or override known architectures through a config key. This way, additional architectures could be added by anyone on his own responsibility. That would release our blocker and would not break existing API.

@kalefranz What do you think? How does this interfere with #3708 ?

**Comment by kalefranz** [comment]
The `CONDA_SUBDIR` and `subdir` condarc parameter can now be specified.  Also undocumented, you can specify `CONDA_SUBDIRS` as a string-delimited list and `subdirs` as a list in condarc.  These remain undocumented and experimental for now.  We have plans to expand the power of what we use subdirs for.  Any specific custom implementation might not be completely compatible with what is eventually settled on.  Thus the reason these remain experimental and undocumented.  Some related PRs are https://github.com/conda/conda/pull/4178 and https://github.com/conda/conda/pull/5030.

Actually this doesn't interfere with https://github.com/conda/conda/issues/3708 at all.  In fact https://github.com/conda/conda/issues/3708 is intended to make room exactly for this.  Unfortunately the team is still not in full agreement on ultimate implementation.  See discussion in https://github.com/conda/conda/pull/3739 and https://github.com/conda/conda/pull/4238.

**Comment by kalefranz** [comment]
CC @mingwandroid.  Not sure if he has any input beyond what I've already said though.  It's still WIP
