### ISSUE TITLE
rename info/package_metadata.json

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#4481]
The file `info/package_metadata.json` should be renamed to something more meaningful.  The current name is not useful, because all content of `info/` is "package metadata".  Moreover the name is extra log.  Calling the file `info/foo.json` would at least be shorted, although it wouldn't mean anything either.  Filenames like this one, are part of the external API on conda, and choosing meaningful names reflects on the project as a whole.

CC @kalefranz, @msarahan, @csoja

**Comment by kalefranz** [comment]
Ilan, do you have a proposal? (I'm assuming your proposal wasn't in fact we rename it to `info/foo.json`, but correct me if I'm wrong.)

**Comment by kalefranz** [comment]
Relevant history is here: https://github.com/conda/conda-build/pull/1539

The purpose of the file is to contain information needed by conda at install time after the package is unpacked, but not necessary for the solver and therefore not needed for inclusion in index.json.

**Comment by ilanschnell** [comment]
Indeed, naming the file `info/foo.json` wasn't my proposal.

So if the file is used to contain information about install (or rather linking) the package, why don't we call it `info/link.json`.  This seems to clearly indicate what the purpose of this file is, and will avoid other "things" unrelated to linkage from being added to the file in the future.

**Comment by kalefranz** [comment]
I like link.json. Along those lines maybe install.json is also an option.

**Comment by ilanschnell** [comment]
In "conda" term, we separate between "download", "extract" and "link", whereas "install" is too brought I would say.

**Comment by ilanschnell** [comment]
Looking at one of these files, I see:
```
{
  "noarch": {
    "type": "True"
  },
  "package_metadata_version": 1
}
```
In cases like this one, where nothing special is done, I would say that the json file should not exist at all.

**Comment by kalefranz** [comment]
Renamed to `info/link.json`.
