### ISSUE TITLE
Unexpected error while installing R-essentials

### ISSUE THREAD

**Issue by nvasilius** [conda/conda#4483]
I was attempting to install r-essentials to use in Jupyter Notebook. I received the following error.

-----------------------------Dump from Command Line-----------------------------

The following packages will be UPDATED:

    conda:                   4.2.9-py35_0           --> 4.3.8-py35_0
    pyopenssl:               16.0.0-py35_0          --> 16.2.0-py35_0
    requests:                2.11.1-py35_0          --> 2.12.4-py35_0

Proceed ([y]/n)? y

Fetching packages ...
r-httpuv-1.3.3 100% |###############################| Time: 0:00:00 365.82 kB/s
r-httr-1.2.1-r 100% |###############################| Time: 0:00:11  25.35 kB/s
r-irdisplay-0. 100% |###############################| Time: 0:00:00 151.09 kB/s
r-markdown-0.7 100% |###############################| Time: 0:00:00 297.71 kB/s
r-matrix-1.2_7 100% |###############################| Time: 0:00:10 245.91 kB/s
r-minqa-1.2.4- 100% |###############################| Time: 0:00:00 293.72 kB/s
r-modelmetrics 100% |###############################| Time: 0:00:00 293.05 kB/s
r-munsell-0.4. 100% |###############################| Time: 0:00:00 301.14 kB/s
r-nlme-3.1_128 100% |###############################| Time: 0:00:01   1.87 MB/s
r-pbdzmq-0.2_4 100% |###############################| Time: 0:00:01   1.48 MB/s
r-plyr-1.8.4-r 100% |###############################| Time: 0:00:01 561.64 kB/s
r-psych-1.6.9- 100% |###############################| Time: 0:00:01   2.38 MB/s
r-readxl-0.1.1 100% |###############################| Time: 0:00:00 433.11 kB/s
r-rprojroot-1. 100% |###############################| Time: 0:00:00 253.23 kB/s
r-stringr-1.1. 100% |###############################| Time: 0:00:00 275.53 kB/s
r-tibble-1.2-r 100% |###############################| Time: 0:00:00 344.43 kB/s
r-xml2-1.0.0-r 100% |###############################| Time: 0:00:01   1.38 MB/s
r-zoo-1.7_13-r 100% |###############################| Time: 0:00:00   1.00 MB/s
r-dplyr-0.5.0- 100% |###############################| Time: 0:00:01   1.39 MB/s
r-evaluate-0.1 100% |###############################| Time: 0:00:00 282.67 kB/s
r-forcats-0.1. 100% |###############################| Time: 0:00:00 337.89 kB/s
r-glmnet-2.0_5 100% |###############################| Time: 0:00:01   1.67 MB/s
r-htmlwidgets- 100% |###############################| Time: 0:00:00 893.55 kB/s
r-lubridate-1. 100% |###############################| Time: 0:00:00 717.68 kB/s
r-matrixmodels 100% |###############################| Time: 0:00:00 472.80 kB/s
r-mgcv-1.8_16- 100% |###############################| Time: 0:00:01   1.93 MB/s
r-pryr-0.1.2-r 100% |###############################| Time: 0:00:00 347.92 kB/s
r-rcppeigen-0. 100% |###############################| Time: 0:00:01   1.19 MB/s
r-readr-1.0.0- 100% |###############################| Time: 0:00:00 642.52 kB/s
r-reshape2-1.4 100% |###############################| Time: 0:00:00 287.81 kB/s
r-scales-0.4.1 100% |###############################| Time: 0:00:00 384.35 kB/s
r-selectr-0.3_ 100% |###############################| Time: 0:00:00 336.05 kB/s
r-shiny-0.14.2 100% |###############################| Time: 0:00:01   1.63 MB/s
r-survival-2.4 100% |###############################| Time: 0:00:01   2.67 MB/s
r-xts-0.9_7-r3 100% |###############################| Time: 0:00:00 676.96 kB/s
r-ggplot2-2.2. 100% |###############################| Time: 0:00:01   1.99 MB/s
r-haven-1.0.0- 100% |###############################| Time: 0:00:00 429.67 kB/s
r-irkernel-0.7 100% |###############################| Time: 0:00:00 302.92 kB/s
r-knitr-1.15.1 100% |###############################| Time: 0:00:00   1.03 MB/s
r-lme4-1.1_12- 100% |###############################| Time: 0:00:01   2.58 MB/s
r-purrr-0.2.2- 100% |###############################| Time: 0:00:00 448.21 kB/s
r-quantreg-5.2 100% |###############################| Time: 0:00:01   1.73 MB/s
r-recommended- 100% |###############################| Time: 0:00:00 504.76 kB/s
An unexpected error has occurred.                   | Time: 0:00:06  25.33 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py install -c r r-essentials`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", lin
e 232, in _error_catcher
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", lin
e 314, in read
        data = self._fp.read(amt)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", lin
e 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", lin
e 324, in read
        flush_decoder = True
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", lin
e 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-pac
kages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amaz
onaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install

        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_action
s
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execut
e_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_C
MD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\
\pkgs\\r-rvest-0.3.2-r3.3.2_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packa
ges-prod.s3.amazonaws.com', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_ex
ception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in exe
cute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install

        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_pro
gress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install

        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '
C:\\Program Files\\Anaconda3\\pkgs\\r-rvest-0.3.2-r3.3.2_0.tar.bz2.part' for writing (HTTPSConnectio
nPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by mingwandroid** [comment]
This looks like a network connectivity issue, hopefully transient in nature.

Can you try again.

Also, I would recommend you not to install Anaconda into a path containing spaces.

**Comment by nvasilius** [comment]
I actually updated conda and it fixed the issue. There was one more error during install, but on the second try it worked. I'm now able to use R in Jupyter Notebooks!

**Comment by mingwandroid** [comment]
Great!
