### ISSUE TITLE
CondaHTTPError - Proxy authentication needed    

### ISSUE THREAD

**Issue by RedDevil91** [conda/conda#4486]
Hi

I have upgraded miniconda version from 4.0.5 to 4.2.12 and now I have an issue with proxy authentication. If we (at work) want to install packages with conda then I get the following error:

```
Fetching package metadata ...

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 authenticationrequired',)))",),)
```

In the .condarc file the proxy address and port number is properly set without username:password. So currently my .condarc look like the following:

```
proxy_servers:

      http: http://address:port

      https: https://address:port

```

The username and the password is missing because we are using the conda from work and the IT doesn't allow to store the password and username in a file without encryption.

Is this because the newer version of conda doesn't support the proxy settings authentication from command line? Because the old version asked for username and password if conda couldn't find them in the .condarc file.

Thanks

**Comment by RedDevil91** [comment]
I have checked the conda [config documentation ](https://conda.io/docs/config.html#id5)and this note states that this feature should work but it throws error for me in case of authentication fails:

> Note: If you do not include the username and password, of if authentication fails, conda will prompt for a username and password.

**Comment by kalefranz** [comment]
Bugs with conda's interaction with proxy servers are now being tracked in https://github.com/conda/conda/issues/5220
