### ISSUE TITLE
SSH + source activate

### ISSUE THREAD

**Issue by ajmendez** [conda/conda#4487]
SSH through a gateway machine using ssh's ProxyCommand fails after activating a conda environment.    I am not sure what would be the root cause, however deactivating the env does not clean whatever has changed which causes this issue. Opening a new terminal allows it to work again.

Here is a cleaned up version of the output:

me@laptop:~$ ssh SERVER
Last login: Tue Jan 31 20:37:59 2017 from xxx.xxx.xxx.xxx
remote@server:~$ logout
Connection to SERVER closed.
Killed by signal 1.

me@laptop:~$ source activate py27

(py27) me@laptop:~/tmp/arubasc$ ssh SERVER
bash: No such file or directory
ssh_exchange_identification: Connection closed by remote host

(py27) me@laptop:~$ source deactivate
me@laptop:~$ ssh SERVER
bash: No such file or directory
ssh_exchange_identification: Connection closed by remote host

Current conda install:

             platform : osx-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/me/.local/anaconda3  (writable)
  default environment : /Users/me/.local/anaconda3
     envs directories : /Users/me/.local/anaconda3/envs
        package cache : /Users/me/.local/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

.ssh/config

Host SERVER
    User        remote
    HostName     xxx.xxx.xxx.xxx
    ProxyCommand    ssh user@gateway nc %h %p

**Comment by bkreider** [comment]
Maybe you can try running ssh in debug mode and maybe all inline instead of using the config?

`ssh -v -o ProxyCommand="user@gateway nc %h %p" remote@xxx.xxx.xxx.xx`

**Comment by kalefranz** [comment]
There have been many bug fixes to activate since conda 4.1.6.  Can you reproduce your problem with more recent versions of conda? (latest is 4.3.17)
