### ISSUE TITLE
Errno2 on running "conda update --all" on windows 

### ISSUE THREAD

**Issue by may-s** [conda/conda#4504]
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py update --all`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Anaconda3\\pkgs\\anaconda-navigator-1.4.3-py35_0\\info\\index.json'

**Comment by General-Sax** [comment]
I had an analogous/identical issue. Here's as much context as one could ask for:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\[user]>conda update --all
> Fetching package metadata ...........
> Solving package specifications: .
> 
> Package plan for installation in environment C:\Anaconda3:
> 
> The following NEW packages will be INSTALLED:
> 
>     chardet:            2.3.0-py35_0
>     conda-verify:       2.0.0-py35_0
>     filelock:           2.0.7-py35_0
>     pkginfo:            1.4.1-py35_0
>     widgetsnbextension: 1.2.6-py35_0
> 
> The following packages will be UPDATED:
> 
>     alabaster:          0.7.7-py35_0       --> 0.7.9-py35_0
>     anaconda-client:    1.4.0-py35_0       --> 1.6.1-py35_0
>     anaconda-navigator: 1.1.0-py35_0       --> 1.2.3-py35_0
>     astropy:            1.1.2-np110py35_0  --> 1.3-np111py35_0
>     babel:              2.2.0-py35_0       --> 2.3.4-py35_0
>     beautifulsoup4:     4.4.1-py35_0       --> 4.5.3-py35_0
>     bokeh:              0.11.1-py35_0      --> 0.12.4-py35_0
>     boto:               2.39.0-py35_0      --> 2.45.0-py35_0
>     bottleneck:         1.0.0-np110py35_0  --> 1.2.0-np111py35_0
>     bzip2:              1.0.6-vc14_2       [vc14] --> 1.0.6-vc14_3       [vc14]
>     cffi:               1.5.2-py35_0       --> 1.9.1-py35_0
>     click:              6.6-py35_0         --> 6.7-py35_0
>     cloudpickle:        0.1.1-py35_0       --> 0.2.2-py35_0
>     clyent:             1.2.1-py35_0       --> 1.2.2-py35_0
>     conda-build:        1.21.6-py35_0      --> 2.1.3-py35_0
>     conda-manager:      0.3.1-py35_0       --> 0.4.0-py35_0
>     curl:               7.45.0-vc14_1      [vc14] --> 7.52.1-vc14_0      [vc14]
>     cython:             0.23.4-py35_0      --> 0.25.2-py35_0
>     cytoolz:            0.7.5-py35_0       --> 0.8.2-py35_0
>     dask:               0.8.1-py35_0       --> 0.13.0-py35_0
>     datashape:          0.5.1-py35_0       --> 0.5.4-py35_0
>     decorator:          4.0.9-py35_0       --> 4.0.11-py35_0
>     dill:               0.2.4-py35_0       --> 0.2.5-py35_0
>     docutils:           0.12-py35_1        --> 0.13.1-py35_0
>     fastcache:          1.0.2-py35_0       --> 1.0.2-py35_1
>     flask-cors:         2.1.2-py35_0       --> 3.0.2-py35_0
>     freetype:           2.5.5-vc14_0       [vc14] --> 2.5.5-vc14_2       [vc14]
>     gevent:             1.1.0-py35_0       --> 1.2.1-py35_0
>     greenlet:           0.4.9-py35_0       --> 0.4.11-py35_0
>     h5py:               2.5.0-np110py35_4  --> 2.6.0-np111py35_2
>     heapdict:           1.0.0-py35_0       --> 1.0.0-py35_1
>     idna:               2.0-py35_0         --> 2.2-py35_0
>     ipykernel:          4.3.1-py35_0       --> 4.5.2-py35_0
>     ipython:            4.1.2-py35_1       --> 5.1.0-py35_0
>     ipywidgets:         4.1.1-py35_0       --> 5.2.2-py35_1
>     jdcal:              1.2-py35_0         --> 1.3-py35_0
>     jedi:               0.9.0-py35_0       --> 0.9.0-py35_1
>     jinja2:             2.8-py35_0         --> 2.9.4-py35_0
>     jpeg:               8d-vc14_0          [vc14] --> 8d-vc14_2          [vc14]
>     jsonschema:         2.4.0-py35_0       --> 2.5.1-py35_0
>     jupyter_client:     4.2.2-py35_0       --> 4.4.0-py35_0
>     jupyter_console:    4.1.1-py35_0       --> 5.0.0-py35_0
>     jupyter_core:       4.1.0-py35_0       --> 4.2.1-py35_0
>     libpng:             1.6.17-vc14_1      [vc14] --> 1.6.27-vc14_0      [vc14]
>     libtiff:            4.0.6-vc14_1       [vc14] --> 4.0.6-vc14_2       [vc14]
>     llvmlite:           0.9.0-py35_0       --> 0.15.0-py35_0
>     locket:             0.2.0-py35_0       --> 0.2.0-py35_1
>     lxml:               3.6.0-py35_0       --> 3.7.2-py35_0
>     markupsafe:         0.23-py35_1        --> 0.23-py35_2
>     matplotlib:         1.5.1-np110py35_0  --> 1.5.1-np111py35_0
>     menuinst:           1.3.2-py35_0       --> 1.4.4-py35_0
>     mistune:            0.7.2-py35_0       --> 0.7.3-py35_0
>     mkl:                11.3.1-0           --> 2017.0.1-0
>     mkl-service:        1.1.2-py35_0       --> 1.1.2-py35_3
>     mpmath:             0.19-py35_0        --> 0.19-py35_1
>     multipledispatch:   0.4.8-py35_0       --> 0.4.9-py35_0
>     nbconvert:          4.1.0-py35_0       --> 4.2.0-py35_0
>     nbformat:           4.0.1-py35_0       --> 4.2.0-py35_0
>     nltk:               3.2-py35_0         --> 3.2.2-py35_0
>     nose:               1.3.7-py35_0       --> 1.3.7-py35_1
>     notebook:           4.1.0-py35_2       --> 4.3.1-py35_1
>     numba:              0.24.0-np110py35_0 --> 0.30.1-np111py35_0
>     numexpr:            2.5-np110py35_0    --> 2.6.1-np111py35_2
>     numpy:              1.10.4-py35_0      --> 1.11.3-py35_0
>     odo:                0.4.2-py35_0       --> 0.5.0-py35_1
>     openpyxl:           2.3.2-py35_0       --> 2.4.1-py35_0
>     openssl:            1.0.2g-vc14_0      [vc14] --> 1.0.2k-vc14_0      [vc14]
>     pandas:             0.18.0-np110py35_0 --> 0.19.2-np111py35_1
>     partd:              0.3.2-py35_1       --> 0.3.7-py35_0
>     path.py:            8.1.2-py35_1       --> 10.0-py35_0
>     patsy:              0.4.0-np110py35_0  --> 0.4.1-py35_0
>     pickleshare:        0.5-py35_0         --> 0.7.4-py35_0
>     pillow:             3.1.1-py35_0       --> 3.4.2-py35_0
>     pip:                8.1.1-py35_1       --> 9.0.1-py35_1
>     ply:                3.8-py35_0         --> 3.10-py35_0
>     prompt_toolkit:     1.0.3-py35_0       --> 1.0.9-py35_0
>     psutil:             4.1.0-py35_0       --> 5.0.1-py35_0
>     pycosat:            0.6.1-py35_0       --> 0.6.1-py35_1
>     pycparser:          2.14-py35_0        --> 2.17-py35_0
>     pycrypto:           2.6.1-py35_3       --> 2.6.1-py35_5
>     pyflakes:           1.1.0-py35_0       --> 1.5.0-py35_0
>     pygments:           2.1.1-py35_0       --> 2.1.3-py35_0
>     pyparsing:          2.0.3-py35_0       --> 2.1.4-py35_0
>     pyqt:               4.11.4-py35_5      --> 4.11.4-py35_7
>     pytables:           3.2.2-np110py35_2  --> 3.2.2-np111py35_4
>     pytest:             2.8.5-py35_0       --> 3.0.5-py35_0
>     python:             3.5.1-4            --> 3.5.2-0
>     python-dateutil:    2.5.1-py35_0       --> 2.6.0-py35_0
>     pytz:               2016.2-py35_0      --> 2016.10-py35_0
>     pywin32:            220-py35_1         --> 220-py35_2
>     pyyaml:             3.11-py35_3        --> 3.12-py35_0
>     pyzmq:              15.2.0-py35_0      --> 16.0.2-py35_0
>     qtawesome:          0.3.2-py35_0       --> 0.4.3-py35_0
>     qtconsole:          4.2.0-py35_1       --> 4.2.1-py35_0
>     qtpy:               1.0-py35_0         --> 1.2.1-py35_0
>     ruamel_yaml:        0.11.14-py35_0     --> 0.11.14-py35_1
>     scikit-image:       0.12.3-np110py35_0 --> 0.12.3-np111py35_1
>     scikit-learn:       0.17.1-np110py35_0 --> 0.18.1-np111py35_1
>     scipy:              0.17.0-np110py35_0 --> 0.18.1-np111py35_1
>     setuptools:         20.3-py35_0        --> 27.2.0-py35_1
>     simplegeneric:      0.8.1-py35_0       --> 0.8.1-py35_1
>     sip:                4.16.9-py35_2      --> 4.18-py35_0
>     sockjs-tornado:     1.0.1-py35_0       --> 1.0.3-py35_0
>     sqlalchemy:         1.0.12-py35_0      --> 1.1.5-py35_0
>     statsmodels:        0.6.1-np110py35_0  --> 0.6.1-np111py35_1
>     toolz:              0.7.4-py35_0       --> 0.8.2-py35_0
>     tornado:            4.3-py35_0         --> 4.4.2-py35_0
>     traitlets:          4.2.1-py35_0       --> 4.3.1-py35_0
>     vs2015_runtime:     14.00.23026.0-0    --> 14.0.25123-0
>     werkzeug:           0.11.4-py35_0      --> 0.11.15-py35_0
>     xlrd:               0.9.4-py35_0       --> 1.0.0-py35_0
>     xlsxwriter:         0.8.4-py35_0       --> 0.9.6-py35_0
>     xlwings:            0.7.0-py35_0       --> 0.10.2-py35_0
>     xlwt:               1.0.0-py35_0       --> 1.2.0-py35_0
>     zlib:               1.2.8-vc14_2       [vc14] --> 1.2.8-vc14_3       [vc14]
> 
> Proceed ([y]/n)? y
> 
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-64
>           conda version : 4.3.8
>        conda is private : False
>       conda-env version : 4.3.8
>     conda-build version : 1.21.6
>          python version : 3.5.1.final.0
>        requests version : 2.12.4
>        root environment : C:\Anaconda3  (writable)
>     default environment : C:\Anaconda3
>        envs directories : C:\Anaconda3\envs
>           package cache : C:\Anaconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/win-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
>              user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.1 Windows/10 Windows/10.0.14393
> 
> 
> 
> `$ C:\Anaconda3\Scripts\conda-script.py update --all`
> 
>     Traceback (most recent call last):
>       File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
>         exit_code = args.func(args, p)
>       File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
>         install(args, parser, 'update')
>       File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
>         execute_actions(actions, index, verbose=not context.quiet)
>       File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
>         execute_instructions(plan, index, verbose)
>       File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
>         cmd(state, arg)
>       File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
>         txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
>       File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
>         for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
>       File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
>         for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
>       File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
>         index_json_record = read_index_json(extracted_package_directory)
>       File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
>         with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
>     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Anaconda3\\pkgs\\jdcal-1.3-py35_0\\info\\index.json'

**Comment by may-s** [comment]
@General-Sax were you able to resolve the issue?

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
