### ISSUE TITLE
Problem when updating Anaconda

### ISSUE THREAD

**Issue by hlignin** [conda/conda#4507]
![conda1](https://cloud.githubusercontent.com/assets/7775813/22564262/e70c88b0-e951-11e6-98d2-4eaa2b26b184.JPG)
![conda2](https://cloud.githubusercontent.com/assets/7775813/22564298/04006e32-e952-11e6-88c2-5fcf32e535cc.JPG)

Please see the error message in the attached pictures. Now my python doesn't work at all...

**Comment by kalefranz** [comment]
Solution is `conda clean --packages` and then `conda update conda`.
