### ISSUE TITLE
install opencv3 on python3.6 error

### ISSUE THREAD

**Issue by alexxucui** [conda/conda#4511]
I try to use conda install to install opencv3 on anaconda python 3.6

And here is the error,

C:\Users\Alex Cui>conda install -c menpo opencv3=3.1.0
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv3 3.1.0* -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by m-rossi** [comment]
Something similar here for `conda install nb_conda` and various other packages on a Windows 7 machine with Anaconda 4.3 installed.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1674
