### ISSUE TITLE
conda subcommands should reliably return with nonzero exit status on error 

### ISSUE THREAD

**Issue by kernc** [conda/conda#4512]
Problem:
```bash
$ conda build nonexistent  # silently passes with noop and exit status == 0
$
```

```bash
$ conda install /tmp/something.tar.bz2  # silently passes with noop and exit status == 0
$
```

Solution:
> Errors should never pass silently.

**Comment by kalefranz** [comment]
What version of conda were you using?  I think all of the code within the conda repo does pretty well with this at this point, following the exception handler rolled out with conda 4.2.

Right now for example,

```
kfranz@0283:~/continuum/conda *4.3.x ❯ python -m conda install /tmp/something.tar.bz2

CondaError: dist_name is not a valid conda package: file:///tmp/something.tar.bz2

(1)kfranz@0283:~/continuum/conda *4.3.x ❯ echo $?
1
kfranz@0283:~/continuum/conda *4.3.x ❯
```

If you find other examples, please report them in a new ticket and we'll get them fixed up.
