### ISSUE TITLE
Conda overriding or circumventing ACL permissions in linux.

### ISSUE THREAD

**Issue by abalter** [conda/conda#4521]
This references #1329 on conda for group installations.

We've been doing some experimentation with using ACLs on a group conda installation and they are not working. Somehow, when conda installs things, it is able to apply permissions that are overriding or circumventing the ACLs.

We created a sandbox directory `permstest`. 
```
balter@exalab3:.../permstest$ getfacl .
# file: .
# owner: burchard
# group: BioCoders
# flags: -st
user::rwx
group::rwx
other::---
default:user::rwx
default:group::rwx
default:group:BioCoders:rwx
default:mask::rwx
default:other::---
balter@exalab3:.../permstest$ getfacl miniconda3
# file: miniconda3
# owner: balter
# group: BioCoders
# flags: -s-
user::rwx
group::rwx
group:BioCoders:rwx
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:BioCoders:rwx
default:mask::rwx
default:other::---
```
When I or anyone else creates files or directories in that directory, everything "works":

```
balter@exalab3:.../permstest$ echo "main (){}" > test.c
balter@exalab3:.../permstest$ gcc test.c
balter@exalab3:.../permstest$ touch touchtest
balter@exalab3:.../permstest$ mkdir dirtest
balter@exalab3:.../permstest$ ./miniconda3/bin/python -c "f=open('filecreatedbypy','w'); f.write('test'); f.close()"
balter@exalab3:.../permstest$ ./miniconda3/bin/python -c "import os; os.mkdir('dirbypy')"
balter@exalab3:.../permstest$ ls -lrt
total 19875
-rw-rw----+  1 balter   BioCoders 33905474 Feb  2 23:05 Miniconda3-latest-Linux-x86_64.sh
drwxrws---+ 12 balter   BioCoders     4096 Feb  3 09:05 miniconda3
-rw-rw----+  1 balter   BioCoders       10 Feb  3 12:07 test.c
-rwxrwx--x+  1 balter   BioCoders     6262 Feb  3 12:08 a.out
-rw-rw----+  1 balter   BioCoders        0 Feb  3 12:09 touchtest
drwxrws---+  2 balter   BioCoders     4096 Feb  3 12:09 dirtest
-rw-rw----+  1 balter   BioCoders        4 Feb  3 12:09 filecreatedbypy
drwxrws---+  2 balter   BioCoders     4096 Feb  3 12:09 dirbypy
```

When I installed miniconda, the permissions went in as 770 as hoped for. However, when I or anyone else installs, they are going in as 755. This means that only the installer will be able to remove, update, etc.

Conda is simply a python program, and it invokes other compilers and installers. So based on the experiments above, it seems like anything done with a python program or system compiler should result in the expected permissions.

But, clearly conda is able to do something we don't understand regarding how it is able to override permissions.

Any clarity that can be shed on this would be greatly appreciated!

**Comment by abalter** [comment]
Something to add:

Could it partially be what happens with permissions when a file is moved? Here are some tests:

```
balter@exalab3:.../OurGroup$ touch filetomove
balter@exalab3:.../OurGroup$ ls -l filetomove
-rw-rw-r-- 1 balter OurGroup 0 Feb  3 12:55 filetomove
balter@exalab3:.../OurGroup$ chmod 646 filetomove
balter@exalab3:.../OurGroup$ ls -l filetomove
-rw-r--rw- 1 balter OurGroup 0 Feb  3 12:55 filetomove
balter@exalab3:.../OurGroup$ getfacle filetomove
-bash: getfacle: command not found
balter@exalab3:.../OurGroup$ getfacl filetomove
# file: filetomove
# owner: balter
# group: OurGroup
user::rw-
group::r--
other::rw-

balter@exalab3:.../OurGroup$ mv filetomove permstest/
balter@exalab3:.../OurGroup$ cd permstest/
balter@exalab3:.../OurGroup/permstest$ ls -l filetomove
-rw-r--rw- 1 balter OurGroup 0 Feb  3 12:55 filetomove
balter@exalab3:.../OurGroup/permstest$ getfacl filetomove
# file: filetomove
# owner: balter
# group: OurGroup
user::rw-
group::r--
other::rw-

balter@exalab3:.../OurGroup/permstest$ cd
balter@exalab3:~$ touch filetomove
balter@exalab3:~$ ls -l filetomove
-rw-rw-r-- 1 balter HPCUsers 0 Feb  3 12:57 filetomove
balter@exalab3:~$ chmod 646 filetomove
balter@exalab3:~$ ls -l filetomove
-rw-r--rw- 1 balter HPCUsers 0 Feb  3 12:57 filetomove
balter@exalab3:~$ getfacl filetomove
# file: filetomove
# owner: balter
# group: HPCUsers
user::rw-
group::r--
other::rw-

balter@exalab3:~$ mv filetomove .../OurGroup/permstest/
balter@exalab3:~$ cd !$
cd .../OurGroup/permstest/
balter@exalab3:.../OurGroup/permstest$ ls -l filetomove
-rw-r--rw- 1 balter HPCUsers 0 Feb  3 12:57 filetomove
balter@exalab3:.../OurGroup/permstest$ getfacl filetomove
# file: filetomove
# owner: balter
# group: HPCUsers
user::rw-
group::r--
other::rw-
```

**Comment by bkreider** [comment]
This seems to indicate a similar thing: http://serverfault.com/questions/183800/why-does-cp-not-respect-acls

Your earlier examples were around creating a new file.  It looks like cp preserves the file permission bits.  One thing you could try to do though is to not use a default:group, but add default users.  I think cp only preserves the mask and effective bits.  

For each user:   `setfacl -Rdm user:my_user_name:rwX .`

**Comment by abalter** [comment]
Based on the (excellent) explanations in that post, it sounds like it is by design that cp and mv preserve perms. In 99.999% of cases that is probably exactly what you want.

I wonder what it would take to have conda always change perms to the destination ACLs?

**Comment by kalefranz** [comment]
> I wonder what it would take to have conda always change perms to the destination ACLs?

A solid spec that has lots of eyeballs reviewing it with most people agreeing on what conda *should* be doing (if it's not doing it already).

**Comment by kalefranz** [comment]
@nehaljwani If you haven't come across this issue yet, guessing you might be interested.

**Comment by mcg1969** [comment]
Actually, could the issue here be something as simple as the hard link vs. copy question? That is to say: by default, conda installs files into environments by hard linking them from a package cache. If it copied them instead, it might naturally respect ACL permissions when doing so.

**Comment by mcg1969** [comment]
comment deleted, because I misread things ;-) Still interested in this thread regardless.

**Comment by nehaljwani** [comment]
Relevant links:
https://serverfault.com/questions/183800/why-does-cp-not-respect-acls https://serverfault.com/questions/451698/default-permission-for-newly-created-files-folders-using-acls-not-respected-by-c

**Comment by ijstokes** [comment]
IIRC there are complexities due to file linking as well.  I haven't read any of the SO posts.  I agree this is something conda should address: the package cache should have consistent ownership.  Things get weird fast when different people have different degrees of access/visibility to different packages in the cache.  And to be clear: it is perfectly OK and expected for different people to have different degrees of access/visibility to *all* packages in the cache.

I've just written up a new issue in #6046 for an idea I've been mulling over for years that I think would address this and many other issues related to challenges in using conda in multiuser environments.
