### ISSUE TITLE
anaconda upgrade failed

### ISSUE THREAD

**Issue by sheacoding** [conda/conda#4525]
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/shea/anaconda2  (writable)
    default environment : /home/shea/anaconda2
       envs directories : /home/shea/anaconda2/envs
          package cache : /home/shea/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/shea/anaconda2/bin/conda update --prefix /home/shea/anaconda2 anaconda`

    Traceback (most recent call last):
      File "/home/shea/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/shea/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/shea/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/shea/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/shea/anaconda2/pkgs/libiconv-1.14-0.tar.bz2.part' for writing (("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))).

**Comment by kalefranz** [comment]
Intermittent HTTP error.
