### ISSUE TITLE
conda instsall error

### ISSUE THREAD

**Issue by ganjingcun** [conda/conda#4527]
Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/joe/anaconda2/anaconda  (writable)
    default environment : /Users/joe/anaconda2/anaconda/envs/style-transfer
       envs directories : /Users/joe/anaconda2/anaconda/envs
          package cache : /Users/joe/anaconda2/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/joe/anaconda2/anaconda/envs/style-transfer/bin/conda install -c conda-forge tensorflow=0.11.0`

    Traceback (most recent call last):
      File "/Users/joe/anaconda2/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/joe/anaconda2/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/joe/anaconda2/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/joe/anaconda2/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/joe/anaconda2/anaconda/pkgs/mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by Krishnkant-Swarnkar** [comment]
Same issue with me too...

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
