### ISSUE TITLE
Errno 13: conda install doesn't work.

### ISSUE THREAD

**Issue by yzhu38** [conda/conda#4534]
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -c r r-essentials`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'

**Comment by yzhu38** [comment]
issue resolved by reinstalling anaconda, changing from "for all users" to "for myself"

**Comment by yelingusa** [comment]
Thanks for the post! It solved my problem as well.

**Comment by kalefranz** [comment]
This should also be fixed if you are running conda >= 4.3.13.

**Comment by asimay** [comment]
hi, I think it is still issue existing:
my setup:
Current conda install:

               platform : win-32
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : D:\ProgramDatar\anaconda3  (writable)
    default environment : D:\ProgramDatar\anaconda3\envs\tensorflow
       envs directories : D:\ProgramDatar\anaconda3\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : D:\ProgramDatar\anaconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

when conda install:

(tensorflow) C:\Users\Administrator>conda install python=3.5.3
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment D:\ProgramDatar\anaconda3\envs\tensorflow:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1
    python:         3.5.3-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)?



CondaError: PermissionError(13, 'Permission denied')

CondaError: PermissionError(13, 'Permission denied')

CondaError: PermissionError(13, 'Permission denied')

**Comment by asimay** [comment]
and I changed the directory permission to write and read , but is not effect.

**Comment by tylermanning** [comment]
Are there any solutions to this yet?

**Comment by ooigy** [comment]
i tried `conda clean --all`

worked fine after

**Comment by iranmatlab** [comment]
Hello Friends
I have solved the problem.

This error cause because of different version of python in anaconda and installed python on your system.

when you upgrade anaconda to new version, It has been written in newest version on pyhton (3.6 for me) but i have installed lower version (3.5 for me) of python in my system, so it cause fail in run.

so download newest version of python and install it, then 
**rename** folder of last python to a different name such as "pythoonn"

then conda command will works.

**Comment by dev-ramesh** [comment]
Another way is to go Anaconda Prompt in administrative mode and install required package using command line. 
It worked for me.

**Comment by shaikfaizahamed** [comment]
There seems to be another way of resolving this issue open your anaconda prompt as "run as adminstrator".It worked for me.

**Comment by suishunli** [comment]
Thanks for the post! It solved my problem as well.

**Comment by mesandipdatta** [comment]
For windows machine , there are workarounds to avoid Permission issues . 
Go to - 
> C:\Windows\System32
> Right click on "cmd" and choose "Run in Elevated mode"
> Opens "cmd" prompt in elevated mode.
> Type in conda commands - e.g conda install anything_you_want

Worked for me

**Comment by tobinwang** [comment]
chmod -R 777 your conda file location

**Comment by naga-pakalapati** [comment]
> Another way is to go Anaconda Prompt in administrative mode and install required package using command line.
> It worked for me.

This worked for me too. Thanks!!

**Comment by mdhamid160** [comment]
conda install qt
does not work still getting same permission Error 13. even in admin cmd

**Comment by smerlingcustodio** [comment]
right click on the anaconda prompt, and run as administrator. it fixed it for me.

**Comment by Elgadighizlane** [comment]
> conda install qt
> does not work still getting same permission Error 13. even in admin cmd

did you find a solution I have the same issue even if I run anaconda prompt as admin

**Comment by zllion** [comment]
I had the same issue, and it took me half a day and solved it.
Initially, I installed anaconda under a path with a space in it, which causing the conda cannot boot. So I uninstall anaconda and install it right under C:\
However, this give me Permission deny errors, when creating new env. No matter how I reinstall or use the administrator run, it's still got Permission.
Finally, I found that conda will create hardlink. In windows, to create hardlink you need **ownership**, not admistrator permission of target file.
Follow this article, https://www.laptopmag.com/articles/take-ownership-folder-windows-10-using-file-explorer, change the ownership of Anaconda3 folder, and it's done.
