### ISSUE TITLE
Need nb_conda for Python 3.6

### ISSUE THREAD

**Issue by DavidMertz** [conda/conda#4539]
There currently does not seem to be support for `nb_conda` that is compatible with Python 3.6.  This makes it cumbersome to work with Py36 environments that use Jupyter.  Or in Jupyter when you need to choose an environment (whichever way you want to look at it).

```bash
532-Downloads % conda create -n nb36 python=3.6 jupyter nb_conda
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by kalefranz** [comment]
Hey David, appreciate the issue report, but this isn't really going to get the eyes to actually solve the problem. If it's something that belongs as part of repo.continuum.io, the best place to file an issue is ContinuumIO/anaconda-issues

**Comment by DavidMertz** [comment]
OK. I'll file it there. It seemed like it wasn't merely a conda package, but a package whose purpose is supporting conda. Still, is not the conda codebase as such, of course.

**Comment by PaoloTCS** [comment]
I have the same error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7*
  - python 3.6*

**Comment by sh1895** [comment]
I have the same error too:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```
```
python --version
Python 3.6.0 :: Anaconda 4.3.0 (64-bit)

```

**Comment by damianavila** [comment]
This is tracked here: https://github.com/ContinuumIO/anaconda-issues/issues/1423, and in other places. @kalefranz please close this one to avoid duplication. Thanks.

**Comment by Rich2020** [comment]
:face_with_head_bandage:

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1706
