### ISSUE TITLE
Check satisfiability of existing packages when installing

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#454]
This has been discussed a few times in various places. Conda needs a way to check the satisfiability of existing packages when installing or removing packages.  I've opened this issue to start the discussion for it, as there are several difficulties surrounding this. 

The one issue I can think of so far is with the anaconda metapackage, it would be impossible to remove any package that comes with anaconda, because there would be an inconsistency with anaconda being installed. If versions are included, then it would be impossible to upgrade any package past its anaconda version.

**Comment by kalefranz** [comment]
Done with `4.0` solver.

**Comment by cjw296** [comment]
@kalefranz - what is solver? Where can I find out about version 4.0 of it and when that will take effect in conda environments?

**Comment by mcg1969** [comment]
The "solver" is that portion of the `conda` code that checks to make sure dependencies are satisfied, and ensures that the best set of packages is selected for installation. It has been revamped considerably in version 4.0. You're almost certainly running conda 4.x already, but if for some reason you're not, `conda update conda` should make sure you are.
