### ISSUE TITLE
error trying to use jupyter notebook in a environment I created

### ISSUE THREAD

**Issue by jinluyang** [conda/conda#4542]
I created an conda environment "tensorflow",tried to use jupyter notebook with these codes:

source activate tensorflow
jupyter notebook

But in the notebook,I can only find the root environment,no tensorflow.So I tried to import tensorflow in the notebook 
![image](https://cloud.githubusercontent.com/assets/15670327/22639088/37433bca-ec87-11e6-9a87-e7ac8c283667.png)
After a while the error occured:

> An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at: https://github.com/conda/conda/issues Include the output of the command 'conda info' in your report. Traceback (most recent call last): File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func exit_code = args.func(args, p) File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute install(args, parser, 'install') File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install execute_actions(actions, index, verbose=not args.quiet) File "/root/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions inst.execute_instructions(plan, index, verbose) File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions cmd(state, arg) File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 48, in FETCH_CMD fetch_pkg(state['index'][arg + '.tar.bz2']) File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 336, in fetch_pkg download(url, path, session=session, md5=info['md5'], urlstxt=True) File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 419, in download chunk = resp.raw.read(2**14) File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 320, in read flush_decoder = True File "/root/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__ self.gen.throw(type, value, traceback) File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 246, in _error_catcher raise ProtocolError('Connection broken: %r' % e, e) ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer')) 

The output of conda info is:

> Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /root/anaconda2  (writable)
  default environment : /root/anaconda2/envs/tensorflow
     envs directories : /root/anaconda2/envs
        package cache : /root/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
         offline mode : False
    is foreign system : False

After I activated the environment ,I can import tensorflow using "python" command,but can't import it in ipython or jupyter notebook. I just want to run some notebooks using tensorflow.

**Comment by kalefranz** [comment]
Intermittent HTTP error.  Timeouts are longer and configurable in conda 4.3.
