### ISSUE TITLE
conda installation breaks existing `virtualenv` and `virtualenvwrapper`

### ISSUE THREAD

**Issue by barseghyanartur** [conda/conda#4543]
If I'm already in an env (myenv1) and then try to work on another env (myenv2):

```sh

 workon myenv2
```

I get an error:

```text

Error: deactivate must be sourced. Run 'source deactivate' instead of 'deactivate'.
```

I would expect it to use own commands that do not duplicate existing (very popular) ones.

**Comment by kalefranz** [comment]
In conda 4.4, we are transitioning to `conda activate` and `conda deactivate`.  The `activate` and `deactivate` scripts for conda may then be deprecated at some point in the future.  There's a long run way to make that happen though.

In general I agree that the initial decision to trample this namespace was obtuse.
