### ISSUE TITLE
Tracking explicitly installed packages separately from dependencies would enable portable Conda environments

### ISSUE THREAD

**Issue by mrduane** [conda/conda#4545]
If I create a Conda env on one platform, it's likely that platform-specific dependencies will be included, making that Conda env unsuitable for another platform. It would be useful to be able to track/export an env spec that contains *just* the packages the user explicitly installed, and not the dependencies.

Workaround: Track explicitly installed packages by hand.

**Comment by groutr** [comment]
Explicitly installed specs are available in conda's environment history file.  Explicitly installed packages can be calculated using an approach similar to https://github.com/groutr/conda-tools/blob/master/conda_tools/environment_utils.py#L54-L80

It would be nice though, if this information could be derived directly from environment metadata (the *.json files in conda-meta).

**Comment by kalefranz** [comment]
There's a lot of plumbing in conda 4.4 built in that will help a lot with this.  Maybe in 4.5 we can surface it toward the spirit of this feature request.

**Comment by nanoant** [comment]
I would also really appreciate this feature, especially that many e.g. `apt`, `pacman` (most?) Linux package managers have concept of "explicit" and "dependencies".
Now it is really hard to tell what was that I installed, and was a side-effect, and later to keep living environment nice & clean, e.g. by removing dependencies that are no longer needed by other packages.

**Comment by tkelman** [comment]
x-ref related discussion in https://github.com/continuumio/anaconda-issues/issues/232

**Comment by kalefranz** [comment]
This issue is still open because we have exposed these capabilities to `conda env` yet.

**Comment by jakirkham** [comment]
FYI tracking requested packages only is under issue ( https://github.com/conda/conda/issues/3968 ), which has been closed.

**Comment by zertrin** [comment]
Inspired by hints taken from issue #3968, there is at least a way to get the list of explicitly installed packages programmatically:

```python
from conda.history import History
prefix = '/path/to/a/conda/prefix' # for example '/home/user1/anaconda3/envs/myenv'
history = History(prefix)
history.get_requested_specs_map()
```

Which gives something like:

```
{'nbstripout': MatchSpec(name=LowerStrMatch('nbstripout')),
 'seaborn': MatchSpec(name=LowerStrMatch('seaborn')),
 'python': MatchSpec(name=LowerStrMatch('python'), version=VersionSpec('3.6.*')),
 'pandas': MatchSpec(name=LowerStrMatch('pandas')),
 'scipy': MatchSpec(name=LowerStrMatch('scipy')),
 'psycopg2': MatchSpec(name=LowerStrMatch('psycopg2')),
 'numpy': MatchSpec(name=LowerStrMatch('numpy')),
 'jupyter': MatchSpec(name=LowerStrMatch('jupyter')),
 'flake8': MatchSpec(name=LowerStrMatch('flake8')),
 'ipython': MatchSpec(name=LowerStrMatch('ipython')),
 'line_profiler': MatchSpec(name=LowerStrMatch('line_profiler')),
 'python-slugify': MatchSpec(name=LowerStrMatch('python-slugify')),
 'openpyxl': MatchSpec(name=LowerStrMatch('openpyxl')),
 'geopandas': MatchSpec(name=LowerStrMatch('geopandas')),
 'natsort': MatchSpec(name=LowerStrMatch('natsort')),
 'requests': MatchSpec(name=LowerStrMatch('requests')),
 'jupyter_contrib_nbextensions': MatchSpec(name=LowerStrMatch('jupyter_contrib_nbextensions')),
 'pendulum': MatchSpec(name=LowerStrMatch('pendulum'))}
```

that you can further process.

Hope this can help while waiting for an user facing conda command to export this directly.

**Comment by technic** [comment]
In addition to @zertrin  comment, you should also put
```python
import conda.gateways.logging
```
in the beginning to fix logger related conda error.

**Comment by leeping** [comment]
I just wanted to chime in and say that this would be an incredibly helpful feature.  

Multiple times I've wanted to rebuild a months-old environment that has become very slow when installing new packages because "Solving environment" takes a long time - but I did not have a record of all the packages I requested.  @zertrin 's comment with @technic 's revision really does the trick.

**Comment by SeanGriffith** [comment]
After searching around for the same problem I found the `--from-history` option [here](https://stackoverflow.com/questions/58009732/managing-conda-env-in-cross-platform-environment) which was recently added to conda (Conda 4.7.12 or later). 

This should do exactly what is explained as needed here: write an environment.yaml file that contains the explicitly installed packages.

Usage:
`conda env export --from-history > environment.yaml`

**Comment by gamesbook** [comment]
This only gives the packages in the (base) environment, not in the extended one, so works for (base) and not (my_env) ...
```
(my_env) (base) user@machine:
```

**Comment by gamesbook** [comment]
The -n flag does appear to do anything.

**Comment by leeping** [comment]
This definitely works for me (conda 4.8.3).

```$ conda activate main2
(main2) $ conda env export --from-history
name: main2
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python
  - openmm
  - mdtraj
  - matplotlib
  - lxml
  - networkx
  - mpi4py
  - libgfortran
  - mercurial
  - pandas
  - pymbar
  - swig
  - scipy
  - numpy
  - future
  - cython
  - ipython
prefix: /home/leeping/opt/miniconda3/envs/main2

(main2) $ conda activate base
(base) $ conda env export --from-history
name: base
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - swig
  - conda
prefix: /home/leeping/opt/miniconda3
```

**Comment by dsyzling** [comment]
I'm not sure this solves the explicit use case discussed above - in my case this list doesn't contain the current versions of these packages. If I create a conda environment under Windows and let's say it's a piece of research that I want to package within a docker container. I want to make sure that the versions of packages that I have selected and exist in my current environment can be explicitly selected to build the container - i.e. I can capture the environment and repackage this at any time without upgrading to a more recent version of any packages. 

However the following commands list dependencies which can be architecture specific, so they will include Windows specific components which will not work when creating a linux docker container.
conda list --explicit
conda env export 
conda env export -n <name>   - also lists architecture specific references

Personally if I write an environment.yml file declaring my dependencies (potentially without versions), I'd like to export/snapshot the versions of these explicit components I've requested. I can then use this exported environment to build a new environment under a Linux docker container and if this works use this in future to recreate the research environment.

**Comment by zhangyi-hu** [comment]
```
#!/usr/bin/env bash

# grep the part before 'dependencies:'
conda env export -n $1 --no-build | sed '/dependencies/q' > /var/tmp/temp

# prepare the pattern for packages installed explicitly ('conda=|python=|pytest=|scipy=|pandas=', for instance)
pattern=`conda env export -n $1 --from-history | sed -n '/dependencies/,/prefix/p' | sed '1d; $d' | cut -d' ' -f 4- | cut -d'=' -f 1 | sed 's/$/=/' | paste -sd '|'`
#echo $pattern

# filter the output with --no-build using the pattern prepared
conda env export -n $1 --no-build | grep -E $pattern >> /var/tmp/temp

# grep the part after 'prefix:'
conda env export -n $1 --from-history | sed -ne '/prefix/,$p' >> /var/tmp/temp

# show the result
cat /var/tmp/temp 

# remove the temp file
rm /var/tmp/temp

```
And the output looks like this:

```
name: base
channels:
  - defaults
dependencies:
  - conda=4.8.4
  - pandas=1.1.0
  - pytest=6.0.1
  - python=3.7.7
  - scipy=1.5.0
prefix: /opt/conda
```
