### ISSUE TITLE
``conda clean --all`` leaves some stuff in ``/path/to/conda/lib/``

### ISSUE THREAD

**Issue by jfbu** [conda/conda#4556]
I needed to reclaim some disk space and issued ``conda clean --all`` after having ``conda remove -n envname --all`` on various conda environments, thus leaving only the root environment which has python3.5 installed and a py27 environment.

But when I visit my `/path/to/conda/lib/` I see a `python3.4` repertory which contains obsolete stuff:

```console
$ du -hc -d1 /path/to/conda/lib/python3.4/site-packages
 84K	/path/to/conda/lib/python3.4/site-packages/__pycache__
 24K	/path/to/conda/lib/python3.4/site-packages/imagesize
 28K	/path/to/conda/lib/python3.4/site-packages/imagesize-0.7.0.dist-info
148K	/path/to/conda/lib/python3.4/site-packages/PyQt4
 20K	/path/to/conda/lib/python3.4/site-packages/sphinx
 20K	/path/to/conda/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg
 20K	/path/to/conda/lib/python3.4/site-packages/Sphinx-1.3.5-py3.4.egg
344K	/path/to/conda/lib/python3.4/site-packages
344K	total
```
not much but still. I guess I can delete that ?

**Comment by kalefranz** [comment]
You know I'd just use `rm -rf`.  Annoying I agree.  Labelling this a tech debt.

**Comment by jfbu** [comment]
I had done boldly ;-) the ``rm -rf`` shortly after posting, thanks for confirmation anyway!

**Comment by jakirkham** [comment]
So was this solved in `conda` or is this still an open issue on that regard?

**Comment by kalefranz** [comment]
I think this has all been solved, so long as you don’t use pip and install stuff in the environment that conda isn’t managing. Am I wrong?
