### ISSUE TITLE
Conda Uninstall certain package(2packages have the same name)

### ISSUE THREAD

**Issue by vladimircape** [conda/conda#4557]
I got 2 package
spacy                     0.101.0                  py27_0  
spacy                     1.6.0                     <pip>

and i want to remove just
spacy                     0.101.0                  py27_0  

how to do these?

**Comment by kalefranz** [comment]
Conda should have never installed the two packages in the same environment to begin with.

To get out of the current state, I would uninstall both packages, and then install the spacy that you want.
