### ISSUE TITLE
conda create -n opsim python : Fetching package metadata ...An unexpected error has occurred. : Please consider posting the following information to the conda GitHub issue tracker

### ISSUE THREAD

**Issue by KenMighell** [conda/conda#4559]
[dhcp-116-175:~] mighell% conda create -n opsim python
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : http://lsst-web.ncsa.illinois.edu/~mareuter/conda/dev/osx-64
                          http://lsst-web.ncsa.illinois.edu/~mareuter/conda/dev/noarch
                          http://eupsforge.net/conda/dev/osx-64
                          http://eupsforge.net/conda/dev/noarch
                          http://conda.lsst.codes/sims/osx-64
                          http://conda.lsst.codes/sims/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mighell/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Darwin/15.5.0 OSX/10.11.5
                UID:GID : 502:20

`$ /anaconda/bin/conda create -n opsim python`

    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 143, in func
        res = f(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'

[dhcp-116-175:~] mighell%

**Comment by pavoljuhas** [comment]
I get a very similar crash and traceback from

```sh
mkdir mychannel
conda build -c mychannel path/to/recipe
```
The `conda-build` command works fine when started from a path that has no "mychannel" subdirectory.  Perhaps you are getting a similar problem - check if there is any path conflict with channels defined in your `.condarc`.

PS: This seems related to #4513 and fixup #4518.  I am not sure if these address the `conda build` crash as well.  Perhaps the `--channel` handling needs to be changed to look at local directories after `-c ./mychannel`, `-c /path/to/mychannel`, but use the cloud for `-c mychannel` or `-c mychannel/channel/somelabel`.

**Comment by kalefranz** [comment]
This bug wasn't in the wild for long.  Fixed probably in 4.3.10.
