### ISSUE TITLE
conda develop command is missing from 4.3.9

### ISSUE THREAD

**Issue by garywu** [conda/conda#4560]
Using https://hub.docker.com/r/continuumio/anaconda3/

command is documented [here](https://conda.io/docs/commands/build/conda-develop.html)

```bash
$docker pull continuumio/anaconda3
$docker run -i -t continuumio/anaconda3 /bin/bash
root@32934096c5a7:/code# conda update conda
root@32934096c5a7:/code# conda --version
conda 4.3.9
root@32934096c5a7:/code# conda develop .
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/opt/conda/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```

**Comment by garywu** [comment]
This stackoverflow thread is asking the same question: http://stackoverflow.com/questions/42012409/why-did-the-anaconda-installer-not-install-conda-develop

It's kind of strange that seems nobody is using conda to install from source, I'm basically looking for equivalent of the following functionally:
virtualenv add .
pip install .
pip install -e .
python setup.py develop

**Comment by msarahan** [comment]
Conda develop is part of the conda-build package.  You can obtain it with:

``conda install conda-build``

**Comment by XEasonChan** [comment]
> Conda develop is part of the conda-build package. You can obtain it with:
> 
> `conda install conda-build`
This can't fix my problem, I got the latest conda-build 
`conda-build               3.17.8                   py27_1    conda-forge
`
and the problem just occur again and again once I try to activate an env
```
xeason@xeUbuntu:~$ source activate densepose/
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/xeason/anaconda2/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```
even when I'm trying to `source .bashrc` in the Home dir, it just occur 
```
xeason@xeUbuntu:~$ source .bashrc
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/xeason/anaconda2/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```
and it could be encounted in even more scenario than I just mentioned aboved.
