### ISSUE TITLE
Miniconda-latest-* (without python version) have been removed

### ISSUE THREAD

**Issue by bsipocz** [conda/conda#4562]
The installer seems to be disappeared not long ago (I see failing builds for one of the projects on appveyor for a week now, but some other projects are still fine, presumably due to caching) and now only the Miniconda2-* and Miniconda3-* files are available for windows. https://github.com/astropy/ci-helpers/issues/159
According to the footnote at https://repo.continuum.io/miniconda/ they should be still around.

I'm updating our ci-helpers to use Miniconda3* from now, but having an issue might be useful to save others from running into the same thing.

**Comment by bsipocz** [comment]
Recently realized that the Miniconda-* aliases also disappeared for OSX.

**Comment by kalefranz** [comment]
Yes, I think just yesterday @ilanschnell removed them.  We're preparing to do something different with Miniconda-* installers.  They'll install neither python2 nor python3 in the root environment the way the Miniconda2-* and Miniconda3-* installers do.

@ilanschnell Can you update the footnote at https://repo.continuum.io/miniconda/?

**Comment by ilanschnell** [comment]
I only remove `Miniconda-latest-Linux-x86_64.sh`, the other ones have been removed a long time ago.  I'll add something to the footnote.

**Comment by bsipocz** [comment]
Updating the footnote is a great solution for this issue. Thanks. 

Also it would be great to get some more docs out when things gets diverge e.g. different handling of the env variables e.g. #4579

**Comment by bsipocz** [comment]
Also I think there may be default delay/caching on CIs, as e.g. the disappearance of the windows version of Miniconda-latest* affected a few repos while others were still working.

**Comment by ilanschnell** [comment]
I removed the incorrect footnote.
