### ISSUE TITLE
could not use conda to install any package

### ISSUE THREAD

**Issue by StarsMyDestination** [conda/conda#4564]
sepp@bmwft:~$ conda install jupyter notebook
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/linux-64
An unexpected error has occurred.

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/sepp/miniconda2  (writable)
    default environment : /home/sepp/miniconda2
       envs directories : /home/sepp/miniconda2/envs
          package cache : /home/sepp/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

I can open this link: https://repo.continuum.io/pkgs/free/linux-64 in my browser.

**Comment by kalefranz** [comment]
You haven't provided the stack trace that conda gave you.  There's not much I can do.

**Comment by kalefranz** [comment]
Best advice, update to conda 4.3, and then file a new issue if you still have problems.  `conda update conda`.  Just include the stack trace next time.
