### ISSUE TITLE
.sh extension required for environment variable scripts on *nix

### ISSUE THREAD

**Issue by fperez** [conda/conda#4566]
The [docs on how to customize environment variables](https://conda.io/docs/using/envs.html#saved-environment-variables) state that "Scripts can be given any name", but through trial and error I found that at least on OSX, they *must* have a `.sh` extension, else they don't get executed.

Either the docs should specify this (for all OSes) or, even better, the restriction on a specific extension should be lifted (and then the docs would be correct).

**Comment by kalefranz** [comment]
@electronwill If we haven't fixed this, we absolutely need to.  And actually, it's `.sh` only for bourne-type shells.  It's `.fish` for fish and `.csh` for csh and tcsh.  Etc etc

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-docs#432
