### ISSUE TITLE
Error while installing Matplotlib

### ISSUE THREAD

**Issue by YogeshSumant** [conda/conda#4568]
Getting below error while I am running the command "conda install matplotlib"
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs
/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-32/
Could not connect to https://repo.continuum.io/pkgs/pro/win-32/
Could not connect to https://repo.continuum.io/pkgs/free/win-32/
Could not connect to https://repo.continuum.io/pkgs/free/win-32/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:
               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1

**Comment by kalefranz** [comment]
You have a networking issue on your machine.  Nothing that conda code can really address.
