### ISSUE TITLE
 An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free::qt-5.6.2-vc9_3'.

### ISSUE THREAD

**Issue by itrowa** [conda/conda#4569]
(sci) C:\Users\rikka>conda install scikit-image
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\rikka\Anaconda3\envs\sci:

The following NEW packages will be INSTALLED:

    matplotlib:   2.0.0-np111py27_0  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pillow:       4.0.0-py27_0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pyqt:         5.6.0-py27_2       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    qt:           5.6.2-vc9_3        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    scikit-image: 0.12.3-np111py27_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    scipy:        0.18.1-np111py27_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)? y

scipy-0.18.1-n 100% |###############################| Time: 0:00:11   1.06 MB/s
ERROR conda.core.link:_execute_actions(319): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free::qt-5.6.2-vc9_3'.
UnicodeDecodeError('utf-8', b'\xd2\xd1\xb8\xb4\xd6\xc6         1 \xb8\xf6\xce\xc4\xbc\xfe\xa1\xa3\r\n', 0, 1, 'invalid continuation byte')
Attempting to roll back.

UnicodeDecodeError('utf-8', b'\xd2\xd1\xb8\xb4\xd6\xc6         1 \xb8\xf6\xce\xc4\xbc\xfe\xa1\xa3\r\n', 0, 1, 'invalid continuation byte')

I'm using Windows 10 x64 with anaconda py2.

**Comment by joelkim** [comment]
Maybe duplicated with #4567

**Comment by kalefranz** [comment]
`conda info`?
