### ISSUE TITLE
ERROR conda.core.link:_execute_actions: conda install does not allow interactive (via post-link) anymore?

### ISSUE THREAD

**Issue by hainm** [conda/conda#4573]
Hi all,

We've been using `post-link.sh` during conda-build to ask for some of informations from user (e.g Name, organziation, ...) so we can keep track of who's using conda to install our package.
(To justify the existence of distributing binary package).

Things worked pretty well with old conda version but I got stuck with conda `conda 4.3.9` (further info will be shown).

```bash
ERROR conda.core.link:_execute_actions(319): An error occurred while installing package 'ambermd::ambertools-16.21.1-py35_1'.
LinkError: post-link script failed for package ambermd::ambertools-16.21.1-py35_1
running your command again with `-v` will provide additional information
location of failed script: /Users/haichit/miniconda3/bin/.ambertools-post-link.sh
==> script messages <==
<None>
```

Full log: 
[log.conda.txt](https://github.com/conda/conda/files/761592/log.conda.txt)

System info:
```bash
               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.1.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/haichit/miniconda3  (writable)
    default environment : /Users/haichit/miniconda3
       envs directories : /Users/haichit/miniconda3/envs
          package cache : /Users/haichit/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/ambermd/osx-64
                          https://conda.anaconda.org/ambermd/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
            config file : /Users/haichit/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20
```
thanks.

cc @dacase

**Comment by hainm** [comment]
command

`conda install ambertools=16 -c ambermd`

**Comment by kalefranz** [comment]
So I've dug in, and I'm a little stuck at the moment.

https://conda.io/docs/building/build-scripts.html#pre-post-link-unlink-scripts

These hooks were never designed for interactive IO.  That it worked before I guess was a leaked capability.  Still, I hate breaking something that worked for you before, even if it wasn't ever meant to work.  Still thinking on how we can resolve this...

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/4629 fixes the path issue that was showing up, but it still doesn't fix the IO issue...

**Comment by hainm** [comment]
>Still, I hate breaking something that worked for you before, even if it wasn't ever meant to work. Still thinking on how we can resolve this...

thanks. That would be awesome.

Hai
