### ISSUE TITLE
CONDA_CHANNELS env variable is not consistent for different Minicondas

### ISSUE THREAD

**Issue by bsipocz** [conda/conda#4579]
The https://github.com/astropy/ci-helpers repo provides a toolkit for a large number of packages to set up the conda environment for their travis and appveyor runs. We have a few environment variables including ``CONDA_CHANNELS`` that we process in our install scripts.

Until yesterday we downloaded the ``Miniconda-latest*`` version of Miniconda to start the install, but due to #4562, I had to change it to be ``Miniconda3-*`` (or ``Miniconda2-*``).

Now I'm running into the very annoying bug that this variable also seems to be a conda variable (though we haven't noticed it to be documented at the time we introduced it, nor can I find it documented now).
 
We use whitespace as separator when multiple channels are given, while you seem to prefer a coma separated string. This discrepancy make the install fail quite badly with a ``CondaHTTPError: The remote server could not find the channel you requested.``

There is also a discrepancy between the behaviour of the install scripts in this matter, as both Miniconda2- and Miniconda3- knows about this env variable, while Miniconda- doesn't.

I wonder whether it is possible to choose whitespace as a separator, and if not then make it a separator, too. 

Failure with Miniconda3-: https://travis-ci.org/astropy/ci-helpers/jobs/199371961
Failure with Miniconda2-: https://travis-ci.org/astropy/ci-helpers/jobs/199439273
All green with Miniconda-: https://travis-ci.org/astropy/ci-helpers/jobs/199575722

**Comment by kalefranz** [comment]
I'm not sure if the documentation has been updated yet following https://www.continuum.io/blog/developer-blog/conda-configuration-engine-power-users, but if not it will be soon.  CC @electronwill

**Comment by kalefranz** [comment]
In conda 4.3.16 or later, check out `conda config --describe`.
