### ISSUE TITLE
Issues while updating conda

### ISSUE THREAD

**Issue by Arnab035** [conda/conda#4580]
Hi ,

I am facing a strange error while I run the below command -

conda update conda

Basically I needed to run this to resolve the SSL_CERTIFICATE_VERIFY_FAILED errors . Anyway, I receive the below errors while running the command -

CondaFileIOError: IO Error: Couldn't read or write to file. 'C:\Users\Arnab\Miniconda3\conda-meta\history. Can't write the history file [Errno 22]. Invalid argument.

**Comment by kalefranz** [comment]
What is the output of `conda info`?
