### ISSUE TITLE
ERROR conda.core.link:_execute_actions(319): An error occurred while installing package 'defaults::qt-5.6.2-vc9_3'.

### ISSUE THREAD

**Issue by LiamLiuhit** [conda/conda#4582]
The following NEW packages will be INSTALLED:

    cycler:       0.10.0-py27_0
    icu:          57.1-vc9_0        [vc9]
    jpeg:         9b-vc9_0          [vc9]
    libpng:       1.6.27-vc9_0      [vc9]
    matplotlib:   2.0.0-np111py27_0
    openssl:      1.0.2k-vc9_0      [vc9]
    pyparsing:    2.1.4-py27_0
    pyqt:         5.6.0-py27_2
    qt:           5.6.2-vc9_3       [vc9]
    sip:          4.18-py27_0
    subprocess32: 3.2.7-py27_0
    tk:           8.5.18-vc9_0      [vc9]
    zlib:         1.2.8-vc9_3       [vc9]

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(319): An error occurred while installing
package 'defaults::qt-5.6.2-vc9_3'.
UnicodeDecodeError('utf-8', b'\xd2\xd1\xb8\xb4\xd6\xc6         1 \xb8\xf6\xce\xc
4\xbc\xfe\xa1\xa3\r\n', 0, 1, 'invalid continuation byte')
Attempting to roll back.

UnicodeDecodeError('utf-8', b'\xd2\xd1\xb8\xb4\xd6\xc6         1 \xb8\xf6\xce\xc
4\xbc\xfe\xa1\xa3\r\n', 0, 1, 'invalid continuation byte')

**Comment by LiamLiuhit** [comment]
What's strange is that matplotlib can be install in root environment but failed in user defined environment.

**Comment by joelkim** [comment]
This is a duplicated issue.
I found the reason, but not fixed. check https://github.com/conda/conda/issues/4567 .

**Comment by kalefranz** [comment]
resolved with #4585.  Release coming in the next few days...

**Comment by kalefranz** [comment]
Conda 4.3.12 that includes a patch for this issue has been released to conda canary.  Feel free to test.

    conda config --add channels conda-canary
    conda update conda
