### ISSUE TITLE
Errno 13 , Permission denied, when creating environment

### ISSUE THREAD

**Issue by kiranhari** [conda/conda#4584]
I am having the issue as permission denied while creating the environment
The conda info is
(C:\ProgramData\Anaconda3) C:\Users\BANUCABLE>conda info
Current conda install:

           platform : win-64
      conda version : 4.3.8
   conda is private : False
  conda-env version : 4.3.8
conda-build version : not installed
     python version : 3.6.0.final.0
   requests version : 2.12.4
   root environment : C:\ProgramData\Anaconda3  (writable)
default environment : C:\ProgramData\Anaconda3
   envs directories : C:\ProgramData\Anaconda3\envs
      package cache : C:\ProgramData\Anaconda3\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/win-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/win-64
                      https://repo.continuum.io/pkgs/pro/noarch
                      https://repo.continuum.io/pkgs/msys2/win-64
                      https://repo.continuum.io/pkgs/msys2/noarch
        config file : C:\Users\BANUCABLE\.condarc
       offline mode : False
         user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

and the stacktrace is below

(C:\ProgramData\Anaconda3) C:\Users\BANUCABLE>conda create -n siraj-regression python=2
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\siraj-regression:

The following NEW packages will be INSTALLED:

pip:            9.0.1-py27_1
python:         2.7.13-0
setuptools:     27.2.0-py27_1
vs2008_runtime: 9.00.30729.5054-0
wheel:          0.29.0-py27_0
Proceed ([y]/n)? y

vs2008_runtime 100% |###############################| Time: 0:00:09 114.73 kB/s
vs2008_runtime 100% |###############################| Time: 0:00:08 118.36 kB/s
vs2008_runtime 100% |###############################| Time: 0:00:09 114.31 kB/s

CondaError: PermissionError(13, 'Permission denied')

CondaError: PermissionError(13, 'Permission denied')

CondaError: PermissionError(13, 'Permission denied')

**Comment by kalefranz** [comment]
Thanks for the report.  What do you get for the output of

    conda create -n siraj-regression python=2 -vv

?
