### ISSUE TITLE
unable to install pandas packages

### ISSUE THREAD

**Issue by dipanarya** [conda/conda#4589]
Hi Team,

Please find below logs and command for your reference.I tried to install pandas package on Anaconda after creating the Project called "dlnd".

please help with steps if i missed any steps.

######################################################################
(dlnd) C:\Users\Dipan Arya\Desktop\uda\dlnd-your-first-network\DLND-your-first-n
etwork>conda install pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\dlnd:

The following NEW packages will be INSTALLED:

    mkl:             2017.0.1-0
    numpy:           1.11.3-py36_0
    pandas:          0.19.2-np111py36_1
    python-dateutil: 2.6.0-py36_0
    pytz:            2016.10-py36_0
    six:             1.10.0-py36_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3\envs\dlnd
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Dipan Arya\AppData\Local\conda\conda\envs
                          C:\Users\Dipan Arya\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Dipan Arya\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install pandas`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 825,
 in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 258, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dist
s, link_dists)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line
 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line
 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.
py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.
py", line 104, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi
:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\An
aconda3\\pkgs\\pandas-0.19.2-np111py36_1\\info\\index.json'

(dlnd) C:\Users\Dipan Arya\Desktop\uda\dlnd-your-first-network\DLND-your-first-n
etwork>
######################################################################

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
