### ISSUE TITLE
Make CTRL-C in the middle of conda update operations robust

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#459]
I did a CTRL-C while conda was updating itself at just the wrong time. The result was the removal of conda.  I can't find an especially good way to get it back.  In the end I had to reinstall Anaconda from scratch.  I only after realized that a pip install _may_ have worked.  Maybe putting a signal handler to catch CTRL-C would be a good idea so conda installs don't leave things in an inconsistent state.

**Comment by ijstokes** [comment]
@kalefranz here is another one that maybe we are already handling.  I can't tell when the "long-term" label was put on it, but this is old enough the problem may have been solved.  It seems to me there is a very small but very high value piece of work that could be done to add a SIGTERM signal handler around critical parts of conda updates (and maybe installs).

**Comment by kalefranz** [comment]
Done with conda 4.3.  We're still having problems with the signal handlers for other reasons, but at least this isn't one of them.
