### ISSUE TITLE
Fetching package metadata ... An unexpected error has occured.

### ISSUE THREAD

**Issue by ChrisGChicago** [conda/conda#4590]
I'm very new to this so here it goes...

I was trying to run Anaconda Prompt: "conda update conda" and got the following error and I'm unsure if that is an error or not. the error message suggested I post here. Any help/education would be greatly appreciated. Thanks!:

![image](https://cloud.githubusercontent.com/assets/9057330/22816006/d3891636-ef24-11e6-94b7-84977762a675.png)
![image](https://cloud.githubusercontent.com/assets/9057330/22816070/491ac8b8-ef25-11e6-8b6f-da19a370fb2a.png)

**Comment by kalefranz** [comment]
Right click on the Anaconda Prompt, choose "Run as administrator", and `conda update conda`.
