### ISSUE TITLE
unable to import Metaplotlib.pyplot

### ISSUE THREAD

**Issue by dipanarya** [conda/conda#4595]
I am unable to import Mataplotlib on anaconda environment.please find below code snippet.

C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>conda create --name
 dlnd1  matplotlib python=3 ipython=3 numpy pandas jupyter notebook pyzmq
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\dlnd1
:

The following NEW packages will be INSTALLED:

    cycler:           0.10.0-py35_0
    decorator:        4.0.11-py35_0
    entrypoints:      0.2.2-py35_0
    icu:              57.1-vc14_0        [vc14]
    ipykernel:        4.1.1-py35_0
    ipython:          3.2.3-py35_0
    ipython_genutils: 0.1.0-py35_0
    ipywidgets:       4.1.1-py35_0
    jinja2:           2.9.4-py35_0
    jpeg:             9b-vc14_0          [vc14]
    jsonschema:       2.5.1-py35_0
    jupyter:          1.0.0-py35_3
    jupyter_client:   4.4.0-py35_0
    jupyter_console:  5.0.0-py35_0
    jupyter_core:     4.2.1-py35_0
    libpng:           1.6.27-vc14_0      [vc14]
    markupsafe:       0.23-py35_2
    matplotlib:       2.0.0-np111py35_0
    mistune:          0.7.3-py35_0
    mkl:              2017.0.1-0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.2.0-py35_0
    notebook:         4.3.1-py35_1
    numpy:            1.11.3-py35_0
    openssl:          1.0.2k-vc14_0      [vc14]
    pandas:           0.19.2-np111py35_1
    pip:              9.0.1-py35_1
    prompt_toolkit:   1.0.9-py35_0
    pygments:         2.1.3-py35_0
    pyparsing:        2.1.4-py35_0
    pyqt:             5.6.0-py35_2
    pyreadline:       2.1-py35_0
    python:           3.5.2-0
    python-dateutil:  2.6.0-py35_0
    pytz:             2016.10-py35_0
    pyzmq:            16.0.2-py35_0
    qt:               5.6.2-vc14_3       [vc14]
    qtconsole:        4.2.1-py35_2
    setuptools:       27.2.0-py35_1
    sip:              4.18-py35_0
    six:              1.10.0-py35_0
    tk:               8.5.18-vc14_0      [vc14]
    tornado:          4.4.2-py35_0
    traitlets:        4.3.1-py35_0
    vs2015_runtime:   14.0.25123-0
    wcwidth:          0.1.7-py35_0
    wheel:            0.29.0-py35_0
    zlib:             1.2.8-vc14_3       [vc14]

Proceed ([y]/n)? y

python-3.5.2-0 100% |###############################| Time: 0:00:49 614.58 kB/s
decorator-4.0. 100% |###############################| Time: 0:00:00 659.01 kB/s
entrypoints-0. 100% |###############################| Time: 0:00:00   1.52 MB/s
ipython_genuti 100% |###############################| Time: 0:00:00 540.08 kB/s
jsonschema-2.5 100% |###############################| Time: 0:00:00 739.20 kB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00 849.47 kB/s
mistune-0.7.3- 100% |###############################| Time: 0:00:01  95.48 kB/s
numpy-1.11.3-p 100% |###############################| Time: 0:00:05 635.87 kB/s
pygments-2.1.3 100% |###############################| Time: 0:00:02 491.18 kB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00 536.00 kB/s
pyreadline-2.1 100% |###############################| Time: 0:00:01  36.19 kB/s
pytz-2016.10-p 100% |###############################| Time: 0:00:00 690.74 kB/s
pyzmq-16.0.2-p 100% |###############################| Time: 0:00:00 685.00 kB/s
setuptools-27. 100% |###############################| Time: 0:00:01 661.07 kB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:01 144.80 kB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   2.04 MB/s
tornado-4.4.2- 100% |###############################| Time: 0:00:00 692.38 kB/s
wcwidth-0.1.7- 100% |###############################| Time: 0:00:00  89.00 kB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00 694.12 kB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.23 MB/s
ipython-3.2.3- 100% |###############################| Time: 0:00:07 521.42 kB/s
jinja2-2.9.4-p 100% |###############################| Time: 0:00:00 670.60 kB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:02 635.96 kB/s
prompt_toolkit 100% |###############################| Time: 0:00:00 671.95 kB/s
python-dateuti 100% |###############################| Time: 0:00:00 748.59 kB/s
traitlets-4.3. 100% |###############################| Time: 0:00:00 760.60 kB/s
jupyter_core-4 100% |###############################| Time: 0:00:00 861.70 kB/s
pandas-0.19.2- 100% |###############################| Time: 0:00:11 618.11 kB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:05 630.67 kB/s
jupyter_client 100% |###############################| Time: 0:00:01 118.21 kB/s
matplotlib-2.0 100% |###############################| Time: 0:00:15 592.41 kB/s
nbformat-4.2.0 100% |###############################| Time: 0:00:00 719.97 kB/s
ipykernel-4.1. 100% |###############################| Time: 0:00:00  62.16 kB/s
nbconvert-4.2. 100% |###############################| Time: 0:00:01 197.22 kB/s
jupyter_consol 100% |###############################| Time: 0:00:00   1.05 MB/s
notebook-4.3.1 100% |###############################| Time: 0:00:09 580.39 kB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:01 121.63 kB/s
ipywidgets-4.1 100% |###############################| Time: 0:00:01  88.30 kB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00 889.99 kB/s
#
# To activate this environment, use:
# > activate dlnd1
#
# To deactivate this environment, use:
# > deactivate dlnd1
#
# * for power-users using bash, you must source
#

C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>activate dlnd1

(dlnd1) C:\Users\Dipan Arya\Desktop\uda\dnd\DLND-your-first-network>ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v
.1900 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 3.2.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\pyplot.py in <m
odule>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\colorbar.py in
<module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\contour.py in <
module>()
     21 import matplotlib.collections as mcoll
     22 import matplotlib.font_manager as font_manager
---> 23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook
     25 import matplotlib.mlab as mlab

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\text.py in <mod
ule>()
     31 from matplotlib.artist import allow_rasterization
     32
---> 33 from matplotlib.backend_bases import RendererBase
     34 from matplotlib.textpath import TextPath
     35

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\backend_bases.p
y in <module>()
     61
     62 import matplotlib.tight_bbox as tight_bbox
---> 63 import matplotlib.textpath as textpath
     64 from matplotlib.path import Path
     65 from matplotlib.cbook import mplDeprecation, warn_deprecated

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\textpath.py in
<module>()
     18 from matplotlib.ft2font import KERNING_DEFAULT, LOAD_NO_HINTING
     19 from matplotlib.ft2font import LOAD_TARGET_LIGHT
---> 20 from matplotlib.mathtext import MathTextParser
     21 import matplotlib.dviread as dviread
     22 from matplotlib.font_manager import FontProperties, get_font

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\mathtext.py in
<module>()
     60
     61 import matplotlib.colors as mcolors
---> 62 import matplotlib._png as _png
     63
     64 ####################

ImportError: DLL load failed: The specified procedure could not be found.

In [2]: import matplotlib

In [3]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\pyplot.py in <m
odule>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\colorbar.py in
<module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\contour.py in <
module>()
     21 import matplotlib.collections as mcoll
     22 import matplotlib.font_manager as font_manager
---> 23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook
     25 import matplotlib.mlab as mlab

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\text.py in <mod
ule>()
     31 from matplotlib.artist import allow_rasterization
     32
---> 33 from matplotlib.backend_bases import RendererBase
     34 from matplotlib.textpath import TextPath
     35

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\backend_bases.p
y in <module>()
     61
     62 import matplotlib.tight_bbox as tight_bbox
---> 63 import matplotlib.textpath as textpath
     64 from matplotlib.path import Path
     65 from matplotlib.cbook import mplDeprecation, warn_deprecated

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\textpath.py in
<module>()
     18 from matplotlib.ft2font import KERNING_DEFAULT, LOAD_NO_HINTING
     19 from matplotlib.ft2font import LOAD_TARGET_LIGHT
---> 20 from matplotlib.mathtext import MathTextParser
     21 import matplotlib.dviread as dviread
     22 from matplotlib.font_manager import FontProperties, get_font

C:\ProgramData\Anaconda3\envs\dlnd1\lib\site-packages\matplotlib\mathtext.py in
<module>()
     60
     61 import matplotlib.colors as mcolors
---> 62 import matplotlib._png as _png
     63
     64 ####################

ImportError: DLL load failed: The specified procedure could not be found.

In [4]:

**Comment by dipanarya** [comment]
@msarahan  can you please help on the above issue.i checked the other related issues but didn't work.
Please provide your valuable inputs.

i reset environment variable also.please find details below:
"C:\ProgramData\Anaconda3\Library\bin"

**Comment by abalter** [comment]
Question: are you working on a remote machine? Some Matplotlib packages will cause a poorly reported error if there is no X connection. 

http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

http://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1672
