### ISSUE TITLE
conda env export deprecated?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#4596]
Got a rather strange warning earlier that seemed to imply `conda env export` is going to stop working. I hope I'm just misreading this and/or this warning is talking about something else.

FWIW I have found `conda env export` really useful so as to export an environment file to `stdout` that I can then include in issues. This way people can reproduce the issue I'm running into.

```bash
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.2
         python version : 3.5.3.final.0
       requests version : 2.12.5
       root environment : /opt/conda  (writable)
    default environment : /opt/conda/envs/test
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False

$ conda env export
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
...
```

**Comment by groutr** [comment]
It looks like a warning from pip, not from conda.

**Comment by mcg1969** [comment]
Just a quick reply---yes, that's a pip warning. We'll have to make sure we handle that properly moving forward, but conda env behavior will not be changing because of it.

**Comment by jakirkham** [comment]
Phew! 😌 Thanks for clarifying.

**Comment by rolweber** [comment]
This gets rid of the warning:

    PIP_FORMAT=legacy conda env export

**Comment by kalefranz** [comment]
Not yet it isn't!

**Comment by rolweber** [comment]
It would still be a good idea to explicitly specify the export format when calling pip. That will get rid of the warning, and you'll never have to worry about the changing default in the future.

**Comment by kalefranz** [comment]
Oh, I get it.  To be added to conda-env.

**Comment by kalefranz** [comment]
xref https://github.com/conda/conda/issues/5212

**Comment by ciniro** [comment]
You must to do the follow steps (if you are in Windows like me):

1. Acess the folder C:\Users\
2. If dont exists, create in C:\Users a new folder called "pip"
3. After, enter in folder pip created and create a new file with name "pip.ini".
4. In this file add the follow lines:
[list]
format=columns

5. Open the terminal (cmd, cygwin or anaconda prompt) and try again typing:
(name_of_your_env) C:\your_path>conda env export > name_of_file.yaml

6. Acess the C:\your_path cited in the step 5 and notice that file exported called name_of_file.yaml was be created.

I hope I have helped! Bye!

**Comment by ohmyskyhigh** [comment]
Hi, I followed your step but it does not help, I tried both create pip.ini in my conda env site-package\pip folder and C:\Users\pip folder.

And in both folder I created pip.ini with following text
`[list]
 format=columns`

**Comment by ohmyskyhigh** [comment]
*[list]
 format=columns

**Comment by rolweber** [comment]
@ohmyskyhigh: You have to specify format 'legacy', not 'columns'. Or upgrade conda.
