### ISSUE TITLE
undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

### ISSUE THREAD

**Issue by vladimircape** [conda/conda#4597]
Maybe you can help?

python -m spacy.en.download
/home/vshebuniayeu/anaconda2/bin/python: /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages/spacy/serialize/huffman.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

**Comment by vladimircape** [comment]
The problem was fixed, set the same version for g++ and gcc and install conda additional packages

**Comment by gbonnard** [comment]
Hi vladimircape,

I have the exact similar issue. what conda additional packages did you install?

Thanks a lot.

Gaël
