### ISSUE TITLE
UnsatisfiableError conda install libsbml

### ISSUE THREAD

**Issue by Edahi** [conda/conda#4598]
Recenlty I installed Anaconda on my windows 10 because I will work in some network analysis.
I tried to install libsbml using the next command in shell:
`conda --debug install -c sbmlteam python-libsbml=5.14.1`
And I am getting the following prompt:

> Fetching package metadata .............
> Solving package specifications: .
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - python 3.6*
>   - python-libsbml 5.14.1* -> python 2.7*
> Use "conda info <package>" to see the dependencies for each package.

Have anyone got this before? I have all of my pip/conda commands up to date.

Thank you very much

Conda info:

> 
>                platform : win-64
>           conda version : 4.3.8
>        conda is private : False
>       conda-env version : 4.3.8
>     conda-build version : not installed
>          python version : 3.6.0.final.0
>        requests version : 2.12.4
>        root environment : C:\Users\Edahi\Anaconda  (writable)
>     default environment : C:\Users\Edahi\Anaconda
>        envs directories : C:\Users\Edahi\Anaconda\envs
>           package cache : C:\Users\Edahi\Anaconda\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/win-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
>              user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

**Comment by kalefranz** [comment]
The package `python-libsbm` isn't available for python3 apparently, so you'll need to create a conda environment and specify python 2.

    conda create -n sml-env -c sbmlteam python-libsbml=5.14.1 python=2
    activate sml-env
