### ISSUE TITLE
error msg instructions: "Please consider posting the following information to the conda GitHub issue tracker at:"     https://github.com/conda/conda/issues

### ISSUE THREAD

**Issue by iurisegtovich** [conda/conda#4608]
# brief description

* error when running `conda install -c r r-essentials` at `Could not connect to https://repo.continuum.io/pkgs/free/linux-64/pango-1.40.3-1.tar.bz2`

# solution

* actually worked after just trying again

# final considerations

* the error message instructed me to post here, therefore I believe the system was unable to self-diagnose, so maybe this report will be useful so developers can prevent greater issues that this undiagnosed cause might eventually bring up

# complete terminal log
		
		segtovichisv@segtovichisv-lubuntu1604-vb-scicomp:~$ conda install -c r r-essentials
		Fetching package metadata .........
		Solving package specifications: ..........
		
		Package plan for installation in environment /home/segtovichisv/anaconda3:
		
		The following packages will be downloaded:
		
		    package                    |            build
		    ---------------------------|-----------------
		    bzip2-1.0.6                |                3          83 KB
		    conda-env-2.6.0            |                0          502 B
		    libiconv-1.14              |                0         2.0 MB
		    ncurses-5.9                |               10         904 KB
		    pixman-0.34.0              |                0         3.8 MB
		    gsl-2.2.1                  |                0         7.7 MB
		    libpng-1.6.27              |                0         219 KB
		    pcre-8.39                  |                1         656 KB
		    glib-2.50.2                |                1         5.6 MB
		    requests-2.12.4            |           py35_0         800 KB
		    fontconfig-2.12.1          |                3         429 KB
		    cairo-1.14.8               |                0         609 KB
		    pyopenssl-16.2.0           |           py35_0          70 KB
		    qt-5.6.2                   |                2        44.2 MB
		    conda-4.3.11               |           py35_0         497 KB
		    pango-1.40.3               |                1         938 KB
		    pyqt-5.6.0                 |           py35_2         5.4 MB
		    r-base-3.3.2               |                0        21.7 MB  r
		    r-assertthat-0.1           |         r3.3.2_4          47 KB  r
		    r-backports-1.0.4          |         r3.3.2_0          27 KB  r
		    r-base64enc-0.1_3          |         r3.3.2_0          27 KB  r
		    r-bh-1.62.0_1              |         r3.3.2_0         8.9 MB  r
		    r-bitops-1.0_6             |         r3.3.2_2          25 KB  r
		    r-boot-1.3_18              |         r3.3.2_0         583 KB  r
		    r-cluster-2.0.5            |         r3.3.2_0         481 KB  r
		    r-codetools-0.2_15         |         r3.3.2_0          48 KB  r
		    r-colorspace-1.3_1         |         r3.3.2_0         412 KB  r
		    r-crayon-1.3.2             |         r3.3.2_0         699 KB  r
		    r-curl-2.3                 |         r3.3.2_0         400 KB  r
		    r-data.table-1.10.0        |         r3.3.2_0         1.1 MB  r
		    r-dbi-0.5_1                |         r3.3.2_0         364 KB  r
		    r-dichromat-2.0_0          |         r3.3.2_2         149 KB  r
		    r-digest-0.6.10            |         r3.3.2_0         115 KB  r
		    r-foreign-0.8_67           |         r3.3.2_0         224 KB  r
		    r-formatr-1.4              |         r3.3.2_0          48 KB  r
		    r-gtable-0.2.0             |         r3.3.2_0          60 KB  r
		    r-highr-0.6                |         r3.3.2_0          33 KB  r
		    r-hms-0.3                  |         r3.3.2_0          23 KB  r
		    r-iterators-1.0.8          |         r3.3.2_0         308 KB  r
		    r-jsonlite-1.1             |         r3.3.2_0         1.0 MB  r
		    r-kernsmooth-2.23_15       |         r3.3.2_0          87 KB  r
		    r-labeling-0.3             |         r3.3.2_2          43 KB  r
		    r-lattice-0.20_34          |         r3.3.2_0         705 KB  r
		    r-lazyeval-0.2.0           |         r3.3.2_0         120 KB  r
		    r-magrittr-1.5             |         r3.3.2_2         159 KB  r
		    r-maps-3.1.1               |         r3.3.2_0         3.4 MB  r
		    r-mass-7.3_45              |         r3.3.2_0         1.0 MB  r
		    r-mime-0.5                 |         r3.3.2_0          29 KB  r
		    r-mnormt-1.5_5             |         r3.3.2_0          67 KB  r
		    r-nloptr-1.0.4             |         r3.3.2_2         961 KB  r
		    r-nnet-7.3_12              |         r3.3.2_0         102 KB  r
		    r-openssl-0.9.5            |         r3.3.2_0         1.2 MB  r
		    r-r6-2.2.0                 |         r3.3.2_0         138 KB  r
		    r-randomforest-4.6_12      |         r3.3.2_0         144 KB  r
		    r-rcolorbrewer-1.1_2       |         r3.3.2_3          28 KB  r
		    r-rcpp-0.12.8              |         r3.3.2_0         2.3 MB  r
		    r-repr-0.10                |         r3.3.2_0          62 KB  r
		    r-rpart-4.1_10             |         r3.3.2_0         868 KB  r
		    r-sourcetools-0.1.5        |         r3.3.2_0          66 KB  r
		    r-sparsem-1.74             |         r3.3.2_0         874 KB  r
		    r-spatial-7.3_11           |         r3.3.2_0         128 KB  r
		    r-stringi-1.1.2            |         r3.3.2_0         699 KB  r
		    r-uuid-0.1_2               |         r3.3.2_0          20 KB  r
		    r-xtable-1.8_2             |         r3.3.2_0         692 KB  r
		    r-yaml-2.1.14              |         r3.3.2_0          84 KB  r
		    r-catools-1.17.1           |         r3.3.2_2         161 KB  r
		    r-class-7.3_14             |         r3.3.2_0          85 KB  r
		    r-foreach-1.4.3            |         r3.3.2_0         372 KB  r
		    r-hexbin-1.27.1            |         r3.3.2_0         739 KB  r
		    r-htmltools-0.3.5          |         r3.3.2_0         133 KB  r
		    r-httpuv-1.3.3             |         r3.3.2_0         337 KB  r
		    r-httr-1.2.1               |         r3.3.2_0         270 KB  r
		    r-irdisplay-0.4.4          |         r3.3.2_0          26 KB  r
		    r-markdown-0.7.7           |         r3.3.2_2         109 KB  r
		    r-matrix-1.2_7.1           |         r3.3.2_0         2.3 MB  r
		    r-minqa-1.2.4              |         r3.3.2_2         108 KB  r
		    r-modelmetrics-1.1.0       |         r3.3.2_0         103 KB  r
		    r-munsell-0.4.3            |         r3.3.2_0         133 KB  r
		    r-nlme-3.1_128             |         r3.3.2_0         2.0 MB  r
		    r-pbdzmq-0.2_4             |         r3.3.2_0         357 KB  r
		    r-plyr-1.8.4               |         r3.3.2_0         752 KB  r
		    r-psych-1.6.9              |         r3.3.2_0         3.3 MB  r
		    r-readxl-0.1.1             |         r3.3.2_0         266 KB  r
		    r-rprojroot-1.1            |         r3.3.2_0          48 KB  r
		    r-stringr-1.1.0            |         r3.3.2_0         117 KB  r
		    r-tibble-1.2               |         r3.3.2_0         155 KB  r
		    r-xml2-1.0.0               |         r3.3.2_0         238 KB  r
		    r-zoo-1.7_13               |         r3.3.2_0         867 KB  r
		    r-dplyr-0.5.0              |         r3.3.2_0         1.7 MB  r
		    r-evaluate-0.10            |         r3.3.2_0          49 KB  r
		    r-forcats-0.1.1            |         r3.3.2_0         155 KB  r
		    r-glmnet-2.0_5             |         r3.3.2_0         1.6 MB  r
		    r-htmlwidgets-0.8          |         r3.3.2_0         731 KB  r
		    r-lubridate-1.6.0          |         r3.3.2_0         657 KB  r
		    r-matrixmodels-0.4_1       |         r3.3.2_0         215 KB  r
		    r-mgcv-1.8_16              |         r3.3.2_0         2.0 MB  r
		    r-pryr-0.1.2               |         r3.3.2_0         200 KB  r
		    r-rcppeigen-0.3.2.9.0      |         r3.3.2_0         1.6 MB  r
		    r-readr-1.0.0              |         r3.3.2_0         568 KB  r
		    r-reshape2-1.4.2           |         r3.3.2_0         107 KB  r
		    r-scales-0.4.1             |         r3.3.2_0         218 KB  r
		    r-selectr-0.3_0            |         r3.3.2_0         163 KB  r
		    r-shiny-0.14.2             |         r3.3.2_0         2.4 MB  r
		    r-survival-2.40_1          |         r3.3.2_0         4.8 MB  r
		    r-xts-0.9_7                |         r3.3.2_2         611 KB  r
		    r-ggplot2-2.2.0            |         r3.3.2_0         2.7 MB  r
		    r-haven-1.0.0              |         r3.3.2_0         255 KB  r
		    r-irkernel-0.7.1           |         r3.3.2_0         112 KB  r
		    r-knitr-1.15.1             |         r3.3.2_0         835 KB  r
		    r-lme4-1.1_12              |         r3.3.2_0         4.4 MB  r
		    r-purrr-0.2.2              |         r3.3.2_0         364 KB  r
		    r-quantreg-5.29            |         r3.3.2_0         1.8 MB  r
		    r-recommended-3.3.2        |         r3.3.2_0           2 KB  r
		    r-rvest-0.3.2              |         r3.3.2_0         837 KB  r
		    r-tidyr-0.6.0              |         r3.3.2_0         370 KB  r
		    r-ttr-0.23_1               |         r3.3.2_0         419 KB  r
		    r-broom-0.4.1              |         r3.3.2_0         1.6 MB  r
		    r-pbkrtest-0.4_6           |         r3.3.2_0         215 KB  r
		    r-quantmod-0.4_7           |         r3.3.2_0         483 KB  r
		    r-rmarkdown-1.2            |         r3.3.2_0         1.8 MB  r
		    r-car-2.1_4                |         r3.3.2_0         1.4 MB  r
		    r-gistr-0.3.6              |         r3.3.2_0         1.8 MB  r
		    r-modelr-0.1.0             |         r3.3.2_0         132 KB  r
		    r-caret-6.0_73             |         r3.3.2_0         4.7 MB  r
		    r-rbokeh-0.5.0             |         r3.3.2_0         1.2 MB  r
		    r-tidyverse-1.0.0          |         r3.3.2_0          23 KB  r
		    r-essentials-1.5.1         |                0           2 KB  r
		    ------------------------------------------------------------
		                                           Total:       180.1 MB
		
		The following NEW packages will be INSTALLED:
		
		    bzip2:          1.0.6-3                    
		    gsl:            2.2.1-0                    
		    libiconv:       1.14-0                     
		    ncurses:        5.9-10                     
		    pango:          1.40.3-1                   
		    pcre:           8.39-1                     
		    r-assertthat:   0.1-r3.3.2_4       r       
		    r-backports:    1.0.4-r3.3.2_0     r       
		    r-base:         3.3.2-0            r       
		    r-base64enc:    0.1_3-r3.3.2_0     r       
		    r-bh:           1.62.0_1-r3.3.2_0  r       
		    r-bitops:       1.0_6-r3.3.2_2     r       
		    r-boot:         1.3_18-r3.3.2_0    r       
		    r-broom:        0.4.1-r3.3.2_0     r       
		    r-car:          2.1_4-r3.3.2_0     r       
		    r-caret:        6.0_73-r3.3.2_0    r       
		    r-catools:      1.17.1-r3.3.2_2    r       
		    r-class:        7.3_14-r3.3.2_0    r       
		    r-cluster:      2.0.5-r3.3.2_0     r       
		    r-codetools:    0.2_15-r3.3.2_0    r       
		    r-colorspace:   1.3_1-r3.3.2_0     r       
		    r-crayon:       1.3.2-r3.3.2_0     r       
		    r-curl:         2.3-r3.3.2_0       r       
		    r-data.table:   1.10.0-r3.3.2_0    r       
		    r-dbi:          0.5_1-r3.3.2_0     r       
		    r-dichromat:    2.0_0-r3.3.2_2     r       
		    r-digest:       0.6.10-r3.3.2_0    r       
		    r-dplyr:        0.5.0-r3.3.2_0     r       
		    r-essentials:   1.5.1-0            r       
		    r-evaluate:     0.10-r3.3.2_0      r       
		    r-forcats:      0.1.1-r3.3.2_0     r       
		    r-foreach:      1.4.3-r3.3.2_0     r       
		    r-foreign:      0.8_67-r3.3.2_0    r       
		    r-formatr:      1.4-r3.3.2_0       r       
		    r-ggplot2:      2.2.0-r3.3.2_0     r       
		    r-gistr:        0.3.6-r3.3.2_0     r       
		    r-glmnet:       2.0_5-r3.3.2_0     r       
		    r-gtable:       0.2.0-r3.3.2_0     r       
		    r-haven:        1.0.0-r3.3.2_0     r       
		    r-hexbin:       1.27.1-r3.3.2_0    r       
		    r-highr:        0.6-r3.3.2_0       r       
		    r-hms:          0.3-r3.3.2_0       r       
		    r-htmltools:    0.3.5-r3.3.2_0     r       
		    r-htmlwidgets:  0.8-r3.3.2_0       r       
		    r-httpuv:       1.3.3-r3.3.2_0     r       
		    r-httr:         1.2.1-r3.3.2_0     r       
		    r-irdisplay:    0.4.4-r3.3.2_0     r       
		    r-irkernel:     0.7.1-r3.3.2_0     r       
		    r-iterators:    1.0.8-r3.3.2_0     r       
		    r-jsonlite:     1.1-r3.3.2_0       r       
		    r-kernsmooth:   2.23_15-r3.3.2_0   r       
		    r-knitr:        1.15.1-r3.3.2_0    r       
		    r-labeling:     0.3-r3.3.2_2       r       
		    r-lattice:      0.20_34-r3.3.2_0   r       
		    r-lazyeval:     0.2.0-r3.3.2_0     r       
		    r-lme4:         1.1_12-r3.3.2_0    r       
		    r-lubridate:    1.6.0-r3.3.2_0     r       
		    r-magrittr:     1.5-r3.3.2_2       r       
		    r-maps:         3.1.1-r3.3.2_0     r       
		    r-markdown:     0.7.7-r3.3.2_2     r       
		    r-mass:         7.3_45-r3.3.2_0    r       
		    r-matrix:       1.2_7.1-r3.3.2_0   r       
		    r-matrixmodels: 0.4_1-r3.3.2_0     r       
		    r-mgcv:         1.8_16-r3.3.2_0    r       
		    r-mime:         0.5-r3.3.2_0       r       
		    r-minqa:        1.2.4-r3.3.2_2     r       
		    r-mnormt:       1.5_5-r3.3.2_0     r       
		    r-modelmetrics: 1.1.0-r3.3.2_0     r       
		    r-modelr:       0.1.0-r3.3.2_0     r       
		    r-munsell:      0.4.3-r3.3.2_0     r       
		    r-nlme:         3.1_128-r3.3.2_0   r       
		    r-nloptr:       1.0.4-r3.3.2_2     r       
		    r-nnet:         7.3_12-r3.3.2_0    r       
		    r-openssl:      0.9.5-r3.3.2_0     r       
		    r-pbdzmq:       0.2_4-r3.3.2_0     r       
		    r-pbkrtest:     0.4_6-r3.3.2_0     r       
		    r-plyr:         1.8.4-r3.3.2_0     r       
		    r-pryr:         0.1.2-r3.3.2_0     r       
		    r-psych:        1.6.9-r3.3.2_0     r       
		    r-purrr:        0.2.2-r3.3.2_0     r       
		    r-quantmod:     0.4_7-r3.3.2_0     r       
		    r-quantreg:     5.29-r3.3.2_0      r       
		    r-r6:           2.2.0-r3.3.2_0     r       
		    r-randomforest: 4.6_12-r3.3.2_0    r       
		    r-rbokeh:       0.5.0-r3.3.2_0     r       
		    r-rcolorbrewer: 1.1_2-r3.3.2_3     r       
		    r-rcpp:         0.12.8-r3.3.2_0    r       
		    r-rcppeigen:    0.3.2.9.0-r3.3.2_0 r       
		    r-readr:        1.0.0-r3.3.2_0     r       
		    r-readxl:       0.1.1-r3.3.2_0     r       
		    r-recommended:  3.3.2-r3.3.2_0     r       
		    r-repr:         0.10-r3.3.2_0      r       
		    r-reshape2:     1.4.2-r3.3.2_0     r       
		    r-rmarkdown:    1.2-r3.3.2_0       r       
		    r-rpart:        4.1_10-r3.3.2_0    r       
		    r-rprojroot:    1.1-r3.3.2_0       r       
		    r-rvest:        0.3.2-r3.3.2_0     r       
		    r-scales:       0.4.1-r3.3.2_0     r       
		    r-selectr:      0.3_0-r3.3.2_0     r       
		    r-shiny:        0.14.2-r3.3.2_0    r       
		    r-sourcetools:  0.1.5-r3.3.2_0     r       
		    r-sparsem:      1.74-r3.3.2_0      r       
		    r-spatial:      7.3_11-r3.3.2_0    r       
		    r-stringi:      1.1.2-r3.3.2_0     r       
		    r-stringr:      1.1.0-r3.3.2_0     r       
		    r-survival:     2.40_1-r3.3.2_0    r       
		    r-tibble:       1.2-r3.3.2_0       r       
		    r-tidyr:        0.6.0-r3.3.2_0     r       
		    r-tidyverse:    1.0.0-r3.3.2_0     r       
		    r-ttr:          0.23_1-r3.3.2_0    r       
		    r-uuid:         0.1_2-r3.3.2_0     r       
		    r-xml2:         1.0.0-r3.3.2_0     r       
		    r-xtable:       1.8_2-r3.3.2_0     r       
		    r-xts:          0.9_7-r3.3.2_2     r       
		    r-yaml:         2.1.14-r3.3.2_0    r       
		    r-zoo:          1.7_13-r3.3.2_0    r       
		
		The following packages will be UPDATED:
		
		    cairo:          1.12.18-6                   --> 1.14.8-0     
		    conda:          4.2.12-py35_0      anaconda --> 4.3.11-py35_0
		    fontconfig:     2.11.1-6                    --> 2.12.1-3     
		    glib:           2.43.0-1                    --> 2.50.2-1     
		    libpng:         1.6.22-0                    --> 1.6.27-0     
		    pixman:         0.32.6-0                    --> 0.34.0-0     
		    pyopenssl:      16.0.0-py35_0               --> 16.2.0-py35_0
		    pyqt:           5.6.0-py35_0                --> 5.6.0-py35_2 
		    qt:             5.6.0-0                     --> 5.6.2-2      
		    requests:       2.11.1-py35_0               --> 2.12.4-py35_0
		
		The following packages will be SUPERCEDED by a higher-priority channel:
		
		    conda-env:      2.6.0-0            anaconda --> 2.6.0-0      
		
		Proceed ([y]/n)? y
		
		Pruning fetched packages from the cache ...
		Fetching packages ...
		bzip2-1.0.6-3. 100% |################################| Time: 0:00:00 402.22 kB/s
		conda-env-2.6. 100% |################################| Time: 0:00:00 357.66 kB/s
		libiconv-1.14- 100% |################################| Time: 0:00:05 405.53 kB/s
		ncurses-5.9-10 100% |################################| Time: 0:00:02 324.94 kB/s
		pixman-0.34.0- 100% |################################| Time: 0:00:13 305.75 kB/s
		gsl-2.2.1-0.ta 100% |################################| Time: 0:00:25 322.50 kB/s
		libpng-1.6.27- 100% |################################| Time: 0:00:01 205.81 kB/s
		pcre-8.39-1.ta 100% |################################| Time: 0:00:02 246.67 kB/s
		glib-2.50.2-1. 100% |################################| Time: 0:00:17 333.89 kB/s
		requests-2.12. 100% |################################| Time: 0:00:01 636.73 kB/s
		fontconfig-2.1 100% |################################| Time: 0:00:00   1.26 MB/s
		cairo-1.14.8-0 100% |################################| Time: 0:00:00 751.88 kB/s
		pyopenssl-16.2 100% |################################| Time: 0:00:00 852.96 kB/s
		qt-5.6.2-2.tar 100% |################################| Time: 0:02:31 307.16 kB/s
		conda-4.3.11-p 100% |################################| Time: 0:00:06  73.85 kB/s
		Could not connect to https://repo.continuum.io/pkgs/free/linux-64/pango-1.40.3-1.tar.bz2
		An unexpected error has occurred.
		Please consider posting the following information to the
		conda GitHub issue tracker at:
		
		    https://github.com/conda/conda/issues
		
		
		
		Current conda install:
		
		               platform : linux-64
		          conda version : 4.2.12
		       conda is private : False
		      conda-env version : 4.2.12
		    conda-build version : 2.0.2
		         python version : 3.5.2.final.0
		       requests version : 2.11.1
		       root environment : /home/segtovichisv/anaconda3  (writable)
		    default environment : /home/segtovichisv/anaconda3
		       envs directories : /home/segtovichisv/anaconda3/envs
		          package cache : /home/segtovichisv/anaconda3/pkgs
		           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
		                          https://repo.continuum.io/pkgs/free/noarch
		                          https://repo.continuum.io/pkgs/pro/linux-64
		                          https://repo.continuum.io/pkgs/pro/noarch
		            config file : None
		           offline mode : False
		
		
		
		`$ /home/segtovichisv/anaconda3/bin/conda install -c r r-essentials`
		
		
		
		
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
		        self._validate_conn(conn)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
		        conn.connect()
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
		        ssl_version=resolved_ssl_version)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
		        return context.wrap_socket(sock, server_hostname=server_hostname)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/ssl.py", line 377, in wrap_socket
		        _context=self)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/ssl.py", line 752, in __init__
		        self.do_handshake()
		      File "/home/segtovichisv/anaconda3/lib/python3.5/ssl.py", line 988, in do_handshake
		        self._sslobj.do_handshake()
		      File "/home/segtovichisv/anaconda3/lib/python3.5/ssl.py", line 633, in do_handshake
		        self._sslobj.do_handshake()
		    socket.timeout: _ssl.c:629: The handshake operation timed out
		    
		    During handling of the above exception, another exception occurred:
		    
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
		        chunked=chunked)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
		        self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
		        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
		    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)
		    
		    During handling of the above exception, another exception occurred:
		    
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
		        timeout=timeout
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
		        release_conn=release_conn, **response_kw)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
		        release_conn=release_conn, **response_kw)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
		        release_conn=release_conn, **response_kw)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
		        _stacktrace=sys.exc_info()[2])
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
		        raise MaxRetryError(_pool, url, error or ResponseError(cause))
		    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/pango-1.40.3-1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))
		    
		    During handling of the above exception, another exception occurred:
		    
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 404, in download
		        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
		        return self.request('GET', url, **kwargs)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
		        resp = self.send(prep, **send_kwargs)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
		        r = adapter.send(request, **kwargs)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
		        raise ConnectionError(e, request=request)
		    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/pango-1.40.3-1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))
		    
		    During handling of the above exception, another exception occurred:
		    
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
		        execute_actions(actions, index, verbose=not context.quiet)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
		        inst.execute_instructions(plan, index, verbose)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
		        cmd(state, arg)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
		        fetch_pkg(state['index'][arg + '.tar.bz2'])
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 363, in fetch_pkg
		        download(url, path, session=session, md5=info['md5'], urlstxt=True)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 415, in download
		        raise CondaRuntimeError(msg)
		    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/pango-1.40.3-1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/linux-64/pango-1.40.3-1.tar.bz2
		    
		    
		    During handling of the above exception, another exception occurred:
		    
		    Traceback (most recent call last):
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
		        return_value = func(*args, **kwargs)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
		        exit_code = args.func(args, p)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
		        install(args, parser, 'install')
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
		        raise CondaSystemExit('Exiting', e)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
		        self.gen.throw(type, value, traceback)
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
		        yield
		      File "/home/segtovichisv/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
		        raise CondaRuntimeError('RuntimeError: %s' % e)
		    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/pango-1.40.3-1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/linux-64/pango-1.40.3-1.tar.bz2
		    
		
		segtovichisv@segtovichisv-lubuntu1604-vb-scicomp:~$

**Comment by kalefranz** [comment]
Thanks for the report.  I think we do a lot better job with HTTP errors in conda 4.3 (`conda update conda`).  I've reviewed all of the code though and made a small adjustment.  See #4627

**Comment by kalefranz** [comment]
Conda 4.3.12 that includes this patch has been released to conda canary.  Feel free to test.

    conda config --add channels conda-canary
    conda update conda
