### ISSUE TITLE
Error while installing geopandas

### ISSUE THREAD

**Issue by karanchhabra99** [conda/conda#4614]
When I start installing Geopandas library into my computer, this error showed up.

> Current conda install:
> 
>                platform : win-64
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : 2.0.2
>          python version : 3.5.2.final.0
>        requests version : 2.12.4
>        root environment : C:\Program Files\Anaconda3  (writable)
>     default environment : C:\Program Files\Anaconda3
>        envs directories : C:\Program Files\Anaconda3\envs
>           package cache : C:\Program Files\Anaconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ C:\Program Files\Anaconda3\Scripts\conda-script.py install -c conda-forge geopandas`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 256, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 298, in _error_catcher
>         yield
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 380, in read
>         data = self._fp.read(amt)
>       File "C:\Program Files\Anaconda3\lib\http\client.py", line 448, in read
>         n = self.readinto(b)
>       File "C:\Program Files\Anaconda3\lib\http\client.py", line 488, in readinto
>         n = self.fp.readinto(b)
>       File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
>         return self._sock.recv_into(b)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 273, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 271, in recv_into
>         raise timeout('The read operation timed out')
>     socket.timeout: The read operation timed out
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 703, in generate
>         for chunk in self.raw.stream(chunk_size, decode_content=True):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 432, in stream
>         data = self.read(amt=amt, decode_content=decode_content)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 397, in read
>         raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>       File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 303, in _error_catcher
>         raise ReadTimeoutError(self._pool, None, 'Read timed out.')
>     requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 421, in download
>         for chunk in resp.iter_content(2**14):
>       File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 710, in generate
>         raise ConnectionError(e)
>     requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
>         execute_actions(actions, index, verbose=not context.quiet)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
>         inst.execute_instructions(plan, index, verbose)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
>         cmd(state, arg)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
>         fetch_pkg(state['index'][arg + '.tar.bz2'])
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
>         download(url, path, session=session, md5=info['md5'], urlstxt=True)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 440, in download
>         raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
>     conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\gdal-2.1.3-np111py35_vc14_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
>         raise CondaSystemExit('Exiting', e)
>       File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
>         yield
>       File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
>         raise CondaRuntimeError('RuntimeError: %s' % e)
>     conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\gdal-2.1.3-np111py35_vc14_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
>

**Comment by ehbaker** [comment]
Were you able to fix this issue? If so, please post your solution!! Thanks.

**Comment by karanchhabra99** [comment]
I was not being able to install it in python 3.
But when I try to install it in python 2.7, it work out just fine.

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
