### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by EvertS3** [conda/conda#4618]
Hi, 

I was trying to update my conda environment by using the following command: 

`conda env update -n `MY_ENV_NAME`

However, I got the following output in my terminal console. Can someone help? 

`Fetching package metadata .........
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/EvertTrollip/miniconda3  (writable)
    default environment : /Users/EvertTrollip/miniconda3
       envs directories : /Users/EvertTrollip/miniconda3/envs
          package cache : /Users/EvertTrollip/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Darwin/16.1.0 OSX/10.12.1
                UID:GID : 501:20

`$ /Users/EvertTrollip/miniconda3/bin/conda-env update -n fsm_backend`

    Traceback (most recent call last):
      File "/Users/EvertTrollip/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/EvertTrollip/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_update.py", line 113, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/Users/EvertTrollip/miniconda3/lib/python3.5/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
`

**Comment by kalefranz** [comment]
Fixed in later versions of conda 4.3.  `conda update conda`
