### ISSUE TITLE
Possible regression when setting `envs_dirs`

### ISSUE THREAD

**Issue by timothymillar** [conda/conda#4622]
From the conda [docs](https://conda.io/docs/install/central.html) for `envs_dir` option in a condarc file:
> Specify directories in which environments are located. If this key is set, the root prefix envs_dir is not used unless explicitly included. This key also determines where the package caches will be located.

In conda 4.0.5 and 4.1.11 this works as expected and, when the `envs_dirs` optionis specified, conda only uses the specified location for environments/cacheing packages.

In conda 4.2.12 through 4.3.9 the root env-dir/package-cache is still available (listed second) which means conda will try to link packages cahced in the the root environment.

In conda 4.3.11 the package cache is missing from the configured `envs_dir` and it look like conda will default to the users home folder.

I'm aware that conda is moving towards multi-user support and I'm not sure if these changes are bugs or part of the new intended behaviour.
If this is an intended change, will there be an option to strictly configure which package cache(s) are used (i.e. avoid the use of some caches)?

Possibly related to:
https://github.com/conda/conda/issues/1329
https://github.com/conda/conda/issues/3885

**Details:**

Tested in Ubuntu 16.04 and equivalent results found in a centralised installation on CentOS 7.

condarc file:

```
envs_dirs:
  -  /home/tim/Environments
```

conda 4.0.5 and 4.1.11:

```
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : /home/tim/miniconda2  (writable)
  default environment : /home/tim/miniconda2
     envs directories : /home/tim/Environments
        package cache : /home/tim/Environments/.pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/tim/.condarc
         offline mode : False
    is foreign system : False
```

conda 4.2.12 -> 4.3.9:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/tim/miniconda2  (writable)
    default environment : /home/tim/miniconda2
       envs directories : /home/tim/Environments
                          /home/tim/miniconda2/envs
          package cache : /home/tim/Environments/.pkgs
                          /home/tim/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/tim/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-59-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
```

conda 4.3.11:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/tim/miniconda2  (writable)
    default environment : /home/tim/miniconda2
       envs directories : /home/tim/Environments
                          /home/tim/miniconda2/envs
                          /home/tim/.conda/envs
          package cache : /home/tim/miniconda2/pkgs
                          /home/tim/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/tim/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-59-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
```

**Comment by kalefranz** [comment]
It was intentional.  Having the package cache directories coupled to the envs_dirs variable was sloppy.  You can now set `pkgs_dirs` configuration or `CONDA_PKGS_DIRS` environment variable directly, and it will behave as `envs_dirs` did before by completely overriding the default `pkgs_dirs` value.  However, at least one of the package cache directories must be writable, or conda will complain.

**Comment by timothymillar** [comment]
Just tested with conda 4.3.4-11 and it's working as you describe. 
This is a very useful option!
@kalefranz Thanks for the quick response and for the work towards multi-user support!
