### ISSUE TITLE
Unexpected behavior with build features

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#4624]
I have been attempting use build features for the packaging of the cling c++ interpreter. Indeed `cling` depends on a patched version of `clang` and `llvm`.

Before I get into build features, the Dependency schema is

```
LLVM [cling]  <------ Clang [cling] <--------- Cling
```

Also, at runtime, Cling depends on `libcxx`, the clang c runtime.

**First approach with features**

Following the approach with the `Debug` empty package in the documentation, I created an empty conda package called `cling-patches` which tracks the `cling`  feature.

```
package:
  name: cling-patches
  version: 1

build:
  number: 0
  track_features:
    - cling
```

Then, I built two variants of Clang, one of which declares a `cling` features and depends on `cling-patches` while the other variant does not. 

My initial understanding was that installing `LLVM`, `Clang` and `cling-patches` together would result in have the cling variants of everything, while it did not.

In fact, the even while depending on `cling-patches`, the default variant of the LLVM package is always chosen! Looking into how others used build features, I came across the statement

https://github.com/conda-forge/blas-feedstock/blob/master/recipe/meta.yaml#L19

```
    # The "blas" package must always track a feature, else it will be
    # prioritised over all others.
```

I ended up having rely on this behavior to create the first dependency chain.

** The new approach **

The current approach is that llvm and clang both track features (`llvmcling` for `llvm` and `clangcling` for `clang`).  Besides, `clang` has `features: llvmcling`. This seemed to work, and to make cling-patches unnecessary.

Now, I am building a recipe (`cling`) that depends on `clang [cling]` and `llvm [cling]`. The build of cling randomly switches between the `cling` and `default` variants of llvm and clang...

Now I am observing he the following behavior: subsequent builds of the same conda recipe results in clang 3.9.1 with both default and cling variants.

**Comment by mcg1969** [comment]
@SylvainCorlay, I'm glad you posted an issue, but I was hoping you could help me by offering a simple way to reproduce the "ping-pong" problem you're experiencing. Forgive me if I'm being dense but I'd just like an easy way to reproduce the behavior in `conda` (not conda-build, BTW).

**Comment by SylvainCorlay** [comment]
Sure. I will try to come up with an example that I will push on my channel.

**Comment by mcg1969** [comment]
I've got a simple fix for #2384, but I'm not sure it addresses the problem you're facing. If you get that test case working for me, let me know. Thank you!

**Comment by mcg1969** [comment]
@SylvainCorlay, I just posted over on #2384. It looks like your packages aren't built the way you think they are.

Once the package builds are fixed, you're probably going to need to delete all of the broken builds from conda-forge. There's no telling what conda would do with a mixture of broken and correct packages.

**Comment by kalefranz** [comment]
@SylvainCorlay have we gotten all of the details worked out here for this ticket?

**Comment by SylvainCorlay** [comment]
I think that we can close! Thanks for checking.
