### ISSUE TITLE
netCDF4 not installed properly - DLL load failed

### ISSUE THREAD

**Issue by pablo-esteban** [conda/conda#4631]
I created an anaconda environment with python 3.6 then `conda install netCDF4` which installed 
- libnetcdf: 4.3.3.1-3
- netcdf4:   1.2.4-np111py36_0

I then try to import the package and get this error:

    (py36) C:\Users\pablo\dev>python
    Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import netCDF4
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\pablo\AppData\Local\Continuum\Anaconda\envs\py36\lib\site-packages\netCDF4\__init__.py", line 3, in <module>
        from ._netCDF4 import *
    ImportError: DLL load failed: The specified module could not be found.

Am I missing something or should conda have installed everything to use netcdf4?

Here is the output of `conda info`:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : C:\Users\pablo\AppData\Local\Continuum\Anaconda  (writable)
    default environment : C:\Users\pablo\AppData\Local\Continuum\Anaconda\envs\py36
       envs directories : C:\Users\pablo\AppData\Local\Continuum\Anaconda\envs
          package cache : C:\Users\pablo\AppData\Local\Continuum\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

**Comment by pbreach** [comment]
I'm also having the same issue on the same platform with same installation except Python 3.6 if that helps? Used to work a couple of years ago but seems that something is broken.

**Comment by ikbenali** [comment]
I also had the same problem but with Python 3.6, removing the package with:
`conda remove netcdf4`
and installing it with `pip install netcdf4` to fix it for me.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1671
