### ISSUE TITLE
Install without tk

### ISSUE THREAD

**Issue by anderson-dan-w** [conda/conda#4632]
I want to be able to create a conda environment, specifically a python environment, without tk - that's a dependency I don't need (and is unnecessary when my code will eventually run on a headless server). However, if I try `conda remove tk` it also removes `pip, python, setuptools, wheel`. And if I then try to re-install, say, `pip`, it forces me to reinstall `tk` again. I don't need or want GUI support.

Any way around this?

Thanks

**Comment by kalefranz** [comment]
I just talked with @ilanschnell about this.  We're working through how to just completely drop `tk` as a dependency from conda's python packages...  You're not the first person who has wanted a solution here.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1670
