### ISSUE TITLE
md5 mismatch for xz

### ISSUE THREAD

**Issue by pvanderlinden** [conda/conda#4642]
I'm trying to make a conda environment, but all I get is:
CondaError: MD5MismatchError: MD5MismatchError: MD5 sums mismatch for download: https://conda.anaconda.org/anaconda/noarch/xz-5.2.2-1.tar.bz2 (6352a951a56d7e96a49cbcb3abdda7ed != c8d5d3f406b5309e575c6848091f2fd2)

**Comment by pvanderlinden** [comment]
It seems like the xz package 5.2.2-1 is corrupted

**Comment by pvanderlinden** [comment]
Somehow, instead of downloading the linux-64 version, it downloads the osx-64 version from the noarch channel

**Comment by pvanderlinden** [comment]
Conda info
```
               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 2.0.4
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda3  (writable)
    default environment : /opt/anaconda3/envs/sportr-dataset-api
       envs directories : /opt/anaconda3/envs
                          /home/paul/.conda/envs
          package cache : /opt/anaconda3/pkgs
                          /home/paul/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/paul/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.5.2 Linux/4.4.0-62-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
```

**Comment by pvanderlinden** [comment]
Similair error, this time for pywin32 (not sure why anaconda tries to install it, while installing on a linux system either:
CondaError: MD5MismatchError: MD5MismatchError: MD5 sums mismatch for download: https://conda.anaconda.org/anaconda/noarch/pywin32-220-py35_2.tar.bz2 (484b246cfa329fdd2c1026bd0590641c != 3f51ab31b87ea16e0ba5c5edefb1047a)

**Comment by ilanschnell** [comment]
Thanks for reporting this issue.  The problem is that the 'anaconda' channel on anaconda.org (https://conda.anaconda.org/anaconda) is currently broken.  We are working on a solution.  Since this is merely a mirror of https://repo.continuum.io/pkgs/free it would be best just use the default channel instead.

CC @csoja

**Comment by pvanderlinden** [comment]
@ilanschnell to make sure I don' t use the anaconda channel I can replace all places where I use `anaconda::` in a environment file with `free::`?

**Comment by ilanschnell** [comment]
In the file `/home/paul/.condarc`, you have to remove:
```
channels:
  - anaconda
```

**Comment by pvanderlinden** [comment]
I have never added `anaconda`. The anaconda must be in the default, the error also occured yesterday in a completely clean docker image (continuumio/miniconda3). My condarc:
```
channels:
  - http://<interal-repo>/pkgs
  - defaults
```

**Comment by pvanderlinden** [comment]
As you can also see in my conda info: the anaconda channel isn't even in there.

**Comment by pvanderlinden** [comment]
I think this is related to a bug I forgot to report:
For example, when you have an environment.yml file, and create/update a conda environment with it:
```
name: test
dependencies:
- menpo::opencv3
- redis-py
- python=3.5
```
you will actually install redis from the menpo channel instead of the default. That is why I had to change it into:
```
name: test
dependencies:
- menpo::opencv3
- anaconda::redis-py
- anaconda::redis
- python=3.5
```
Basicly if you specify a package from a channel, it will also try to install all other packages from that repo, even if it is available in the default channels.

**Comment by kalefranz** [comment]
This issue has been resolved.
