### ISSUE TITLE
"An unexpected error has occurred." while installing FEniCS for python3

### ISSUE THREAD

**Issue by chuymtz** [conda/conda#4646]
I succesfully install FEniCS for a python2 environment I created but im not able to use matplotlib.pyplot there. 

So I've tried to install fenics for my default python 3 installation but I get an error when entering 
`conda install -c conda-forge fenics`

The msg I get is

`Linking packages ...`
`An unexpected error has occurred.                                                                  |   0%`
`Please consider posting the following information to the`
`conda GitHub issue tracker at:`

`    https://github.com/conda/conda/issues`

`Current conda install:`

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 0+unknown
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/chuypotter/anaconda  (writable)
    default environment : /Users/chuypotter/anaconda
       envs directories : /Users/chuypotter/anaconda/envs
          package cache : /Users/chuypotter/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`

**Comment by kalefranz** [comment]
Where's the stack trace?

**Comment by chuymtz** [comment]
Hello,

I was able to resolve the issue. Thanks!
