### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by HarshD07** [conda/conda#4648]
Extracting packages ...
[                    ]|                                           [vs2015_runtime      ]|                                           WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.after successfully creating virtual environment i am unable to proceeed further by giving python command
![screenshot 12](https://cloud.githubusercontent.com/assets/25800372/22987079/a57d9e1e-f37b-11e6-9272-48e82ba3e253.png)

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
