### ISSUE TITLE
Unexpected error while installing sciikit-image, pip, six

### ISSUE THREAD

**Issue by avijoyChakma** [conda/conda#4650]
![conda installation error](https://cloud.githubusercontent.com/assets/8032929/22990704/aaabe63a-f37f-11e6-82eb-48eadc336118.png)

TIA for any kind of help.

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
