### ISSUE TITLE
[ENH] I miss the download size details conda previously provided

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4657]
I mentioned this to @kalefranz when I saw in a canary release that download-sizes had disappeared. I thought I was going to be able to live with it, but now I'm finding I'm frustrated by not having some idea of how long a conda environment creation is going to take.  When it takes long enough for me to notice/care (or potentially abort) it is always because of the number/size of files that need to get downloaded (this is especially true if I'm on a slow wifi connection in a coffee shop, plane, or pay-per-MB tethered on my phone).  I don't get that information any more and it makes me sad.

**Comment by mcg1969** [comment]
I agree with this.

**Comment by kalefranz** [comment]
Restored in conda 4.4!  With any luck conda 4.4.0 will drop into the canary channel in the next couple weeks.
