### ISSUE TITLE
An unexpected error occurred during downloading the package #proxy

### ISSUE THREAD

**Issue by RAHULVAMUSANI** [conda/conda#4658]
C:\Users>conda install azure
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
            config file : C:\Users\hp\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py install azure`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Anaconda2\\pkgs\\cache\\2116b818.json'

I am working on a university proxy network 
this is my .condarc file:
channels:
    - defaults
    - r

show_channel_urls: True
allow_other_channels: True

proxy_servers:
    http: http://0024:password@192.168.23.31:3128
    https: http://0024:password@192.168.23.31:3128

ssl_verify: False

How do i resolve this problem 
Pls,anyone help me in resolving the issue 

Thanks in advance for those who help me in fixing the issue

`

**Comment by devesh23** [comment]
Did you solve the issue?

**Comment by kalefranz** [comment]
Yes.  `conda update conda` to version 4.3.13 or greater.  On Windows, you'll need to open the Anaconda command prompt by right-clicking on the icon and selecting "Run as administrator".

**Comment by devesh23** [comment]
Thank You :)

**Comment by RAHULVAMUSANI** [comment]
Nope,The same issue did not solved
I am on a campus proxy network
How can i solve

Thanks in advance

**Comment by kalefranz** [comment]
Your PermissionDenied error has nothing to do with proxy configuration.  It's a permissions issue.  You'll need to run `conda update conda` with Administrator privileges, just as you installed it (i.e. in multi-user mode).
