### ISSUE TITLE
Conda install 'file' does not respect dependencies

### ISSUE THREAD

**Issue by srossross** [conda/conda#466]
This does not install dependencies:

```
conda install ./package.tar.bz2
```

It would be nice for interactive testing before I upload to binstar

**Comment by amcpherson** [comment]
An important use case for this is distribution of licensed software.  A tar.bz2 hidden behind a license agreement on a webpage could be downloaded and conda installed, and publicly available dependencies installed with it from anaconda.org or other repositories.

**Comment by hmaarrfk** [comment]
I'm commenting here in case anybody else finds this issue.

My solution has been to distribute a `.tar.bz` and ask the user to install it using the full path.

Subsequently, one can issue the command
```
conda update <PACKAGE NAME>
```
for conda to fetch the dependencies. A little annoying, but at least it gives a systematic procedure for distributing software.

Alternatively, if you supply a few different packages, it might be easier to provide the command
```
conda update --all
```

**Comment by LeslieGerman** [comment]
I also encountered this issue and found that the conda doc now explicitly states:
> conda can also be called with a list of explicit conda package filenames (e.g. ./lxml-3.2.0-py27_0.tar.bz2). Using conda in this mode implies the --no-deps option

See https://docs.conda.io/projects/conda/en/latest/commands/install.html
