### ISSUE TITLE
Error when attempting "conda install enable" from newly created environment.

### ISSUE THREAD

**Issue by capn-freako** [conda/conda#4665]
$ conda install enable
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\envs\pybert_64:

The following NEW packages will be INSTALLED:

    enable:             4.5.1-np110py27_0
    pyface:             4.5.2-py27_0
    traits:             4.5.0-py27_0
    traitsui:           4.5.1-py27_0

The following packages will be UPDATED:

    anaconda:           4.3.0-np111py27_0  --> custom-py27_0
    scikit-image:       0.12.3-np111py27_1 --> 0.12.3-np110py27_1
    statsmodels:        0.6.1-np111py27_1  --> 0.6.1-np110py27_1

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.4.3-py27_0       --> 1.2.3-py27_0
    astropy:            1.3-np111py27_0    --> 1.1.2-np110py27_0
    bottleneck:         1.2.0-np111py27_0  --> 1.0.0-np110py27_1
    h5py:               2.6.0-np111py27_2  --> 2.6.0-np110py27_0
    llvmlite:           0.15.0-py27_0      --> 0.11.0-py27_0
    matplotlib:         2.0.0-np111py27_0  --> 1.5.1-np110py27_0
    numba:              0.30.1-np111py27_0 --> 0.26.0-np110py27_0
    numexpr:            2.6.1-np111py27_2  --> 2.4.6-np110py27_0
    numpy:              1.11.3-py27_0      --> 1.10.1-py27_0
    pandas:             0.19.2-np111py27_1 --> 0.18.1-np110py27_0
    pyqt:               5.6.0-py27_2       --> 4.10.4-py27_1
    pytables:           3.2.2-np111py27_4  --> 3.2.2-np110py27_1
    qtconsole:          4.2.1-py27_2       --> 4.2.1-py27_0
    scikit-learn:       0.18.1-np111py27_1 --> 0.17-np110py27_1
    scipy:              0.18.1-np111py27_1 --> 0.16.0-np110py27_0

Proceed ([y]/n)?

anaconda-custo 100% |###############################| Time: 0:00:00   6.90 MB/s
numpy-1.10.1-p 100% |###############################| Time: 0:00:02  11.56 MB/s
pyqt-4.10.4-py 100% |###############################| Time: 0:00:02  11.14 MB/s
traits-4.5.0-p 100% |###############################| Time: 0:00:00  12.31 MB/s
astropy-1.1.2- 100% |###############################| Time: 0:00:00  11.66 MB/s
bottleneck-1.0 100% |###############################| Time: 0:00:00  12.33 MB/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:00  12.11 MB/s
llvmlite-0.11. 100% |###############################| Time: 0:00:00  11.75 MB/s
numexpr-2.4.6- 100% |###############################| Time: 0:00:00  12.34 MB/s
pyface-4.5.2-p 100% |###############################| Time: 0:00:00  11.97 MB/s
scipy-0.16.0-n 100% |###############################| Time: 0:00:07  11.71 MB/s
matplotlib-1.5 100% |###############################| Time: 0:00:00  11.63 MB/s
numba-0.26.0-n 100% |###############################| Time: 0:00:00  11.87 MB/s
pandas-0.18.1- 100% |###############################| Time: 0:00:00  11.79 MB/s
pytables-3.2.2 100% |###############################| Time: 0:00:00  11.88 MB/s
scikit-learn-0 100% |###############################| Time: 0:00:00  11.44 MB/s
traitsui-4.5.1 100% |###############################| Time: 0:00:00  11.46 MB/s
anaconda-navig 100% |###############################| Time: 0:00:00  11.17 MB/s
enable-4.5.1-n 100% |###############################| Time: 0:00:00  11.06 MB/s
scikit-image-0 100% |###############################| Time: 0:00:01  11.21 MB/s
statsmodels-0.  98% |############################## | Time: An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\dbanas\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\envs\pybert_64
       envs directories : C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\envs
                          C:\Users\dbanas\AppData\Local\conda\conda\envs
                          H:\.conda\envs
          package cache : C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\pkgs
                          C:\Users\dbanas\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Windows/7 Windows/6.1.7601

`$ C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py install enable`

    Traceback (most recent call last):
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 106, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\dbanas\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
    IOError: [Errno 13] Permission denied: u'C:\\Users\\dbanas\\AppData\\Local\\Continuum\\Anaconda2\\envs\\pybert_64\\Scripts\\conda'

statsmodels-0. 100% |###############################| Time: 0:00:00  11.74 MB/s
qtconsole-4.2. 100% |###############################| Time: 0:00:00  13.00 MB/s
(pybert_64)
dbanas@hq-dbanas-lt MINGW64 /c/Users/dbanas/Documents/eASIC/Projects/Rambus/IBIS_AMI_Validation/Thunderbolt_16G_IBIS_AMI_Models_20170209
$ conda install traitsui
bash: /C/Users/dbanas/AppData/Local/Continuum/Anaconda2/envs/pybert_64/Scripts/conda: No such file or directory

**Comment by capn-freako** [comment]
I think I may have causing this, by not prefixing my "conda install ..." command with "winpty".
When I do that, things seem to work just fine.

(I'm using the MINGW64 Bash shell installed, as part of the _Git for Windows_ application.)

**Comment by zwn** [comment]
I am experiencing the same issue with bash on windows.

@capn-freako thanks for the workaround using `winpty` - it works for me too :+1:
