### ISSUE TITLE
Allow user to specify tarball's properties

### ISSUE THREAD

**Issue by nnashok** [conda/conda#4666]
When I use 'conda build...' to create a package, the tarball generated has some default properties, specifically the user/group is set to match the process owner's user/group. However, this results in creating packages that when untarred end up with user/group set to the process owner who created the package. I would like to make sure that the packages have user/group set to root/root for security. Current interface to conda build does not allow me to do that. It would be useful to have some way to set the properties of the files/directories created in the 'conda build...' process.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1983
