### ISSUE TITLE
CondaHTTPError with  conda version 4.2.13

### ISSUE THREAD

**Issue by kcnwogu** [conda/conda#4674]
I encountered the error below when I run `conda update conda`. My .condarc contains http and https proxy server addresses and port. 

`C:\>conda update conda
Fetching package metadata ...

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))",),)`

**Comment by agilevic** [comment]
This caused quite a bit of friction at a major account.

**Comment by kalefranz** [comment]
If anybody knows of some public proxy server infrastructure we can write automated integration tests against, that would be awesome.

**Comment by kalefranz** [comment]
Bugs with conda's interaction with proxy servers are now being tracked in #5220
