### ISSUE TITLE
Error Installing a Package from GitHub

### ISSUE THREAD

**Issue by ArthurZ** [conda/conda#4675]
Trying to install [ipyvolume](https://github.com/maartenbreddels/ipyvolume) getting error:

`CondaError: An error occurred when loading cached repodata.  Executing
`conda clean --index-cache` will remove cached repodata files
so they can be downloaded again`

Happens on the step when executed `conda install -c conda-forge ipyvolume`

**Comment by groutr** [comment]
Did you try the `conda clean --index-cache` command?
