### ISSUE TITLE
Can't update to Python 3 from 2.7

### ISSUE THREAD

**Issue by IamEchelon** [conda/conda#4681]
I've run ```conda update --all``` I've attempted to install every version of python 3 and each one lists a different ```UnsatisfiableError```

**Comment by kalefranz** [comment]
Not always easy to update environments from python 2 to python 3.  There are python 2 packages and just can't be installed alongside python 3.  For example, `enum34` will prevent an environment from being upgraded to anything beyond python 3.3.  Easiest advice when switching python versions is to create a new environment.
