### ISSUE TITLE
Error Creating conda environment for python 3

### ISSUE THREAD

**Issue by dattasainathd** [conda/conda#4685]
Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Users\ddatt\Anaconda3  (writable)
    default environment : C:\Users\ddatt\Anaconda3
       envs directories : C:\Users\ddatt\Anaconda3\envs
                          C:\Users\ddatt\AppData\Local\conda\conda\envs
                          C:\Users\ddatt\.conda\envs
          package cache : C:\Users\ddatt\Anaconda3\pkgs
                          C:\Users\ddatt\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.13.0 CPython/3.6.0 Windows/10 Windows/10.0.14393

**Comment by groutr** [comment]
@dattasainathd What command did you run to create a python 3 environment?  What error did conda give you?

**Comment by kalefranz** [comment]
What is the error??  Is there a stack trace?  Also, conda 4.3.13 is released that has a few bug fixes.  Perhaps it fixes your issue.  `conda update conda`

**Comment by dattasainathd** [comment]
I was trying to create an environment variable.
I have downloaded the file aind-environment-windows.yml
I tried using the command: conda env create -f aind-environment-windows.yml
But, could not get the desired result:
