### ISSUE TITLE
feature request: set environment variables from meta.yaml

### ISSUE THREAD

**Issue by croth1** [conda/conda#4686]
It would be nice to have a way to declare environment variables for the test environment directly in meta.yaml.

like 
```
   env:
       - KERAS_BACKEND=theano
```

xref: https://github.com/conda-forge/keras-feedstock/pull/6

**Comment by patricksnape** [comment]
I imagine this would be a request for conda-build? Otherwise I can't imagine conda setting environment variables automatically for specific packages (how would you handle clashes?)

**Comment by croth1** [comment]
@patricksnape, yes now that you mention, this indeed only seems to make sense as a conda-build feature.
