### ISSUE TITLE
denied permission to install envirnment

### ISSUE THREAD

**Issue by ajaypanekkad** [conda/conda#4689]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\ajaypanekkad>condo list
'condo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ajaypanekkad>conda list
# packages in environment at C:\ProgramData\Miniconda3:
#
cffi                      1.9.1                    py36_0
conda                     4.3.11                   py36_0
conda-env                 2.6.0                         0
console_shortcut          0.1.1                    py36_1
cryptography              1.7.1                    py36_0
idna                      2.2                      py36_0
menuinst                  1.4.4                    py36_0
openssl                   1.0.2k                   vc14_0  [vc14]
pip                       9.0.1                    py36_1
pyasn1                    0.1.9                    py36_0
pycosat                   0.6.1                    py36_1
pycparser                 2.17                     py36_0
pyopenssl                 16.2.0                   py36_0
python                    3.6.0                         0
pywin32                   220                      py36_2
requests                  2.12.4                   py36_0
ruamel_yaml               0.11.14                  py36_1
setuptools                27.2.0                   py36_1
six                       1.10.0                   py36_0
vs2015_runtime            14.0.25123                    0
wheel                     0.29.0                   py36_0

C:\Users\ajaypanekkad>cd CarND-Term1-Starter-Kit
The system cannot find the path specified.

C:\Users\ajaypanekkad>cd CarND-Term1-Starter-Kit-master

C:\Users\ajaypanekkad\CarND-Term1-Starter-Kit-master>conda env create -f environment.yml
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\ajaypanekkad\AppData\Local\conda\conda\envs
                          C:\Users\ajaypanekkad\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\ajaypanekkad\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Miniconda3\Scripts\conda-env-script.py create -f environment.yml`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\installers\conda.py", line 29, in install
        prefix=prefix)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 144, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Miniconda3\\pkgs\\cache\\2116b818.json'

C:\Users\ajaypanekkad\CarND-Term1-Starter-Kit-master>conda infor --envs
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: argument command: invalid choice: 'C:\\ProgramData\\Miniconda3\\Scripts\\conda-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

C:\Users\ajaypanekkad\CarND-Term1-Starter-Kit-master>conda env create -f environment.yml
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\ajaypanekkad\AppData\Local\conda\conda\envs
                          C:\Users\ajaypanekkad\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\ajaypanekkad\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Miniconda3\Scripts\conda-env-script.py create -f environment.yml`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\installers\conda.py", line 29, in install
        prefix=prefix)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 144, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Miniconda3\\pkgs\\cache\\2116b818.json'

C:\Users\ajaypanekkad\CarND-Term1-Starter-Kit-master>

C:\Users\ajaypanekkad\CarND-Term1-Starter-Kit-master>

**Comment by ozak** [comment]
I have a similar problem when trying to create a new environment for my user on a Linux cluster (which may be related to #4731). I am replicating my info here

I am trying to use a ``YAML`` file that I use to install my working environment in other computers, which has worked fine in other computers where I have administrative rights. Strangely, in the cluster it fails, even though I am not trying to install or update anything in the root account but in mine. Here's the command and the error message I get:

    conda-env create -p ~/.conda/envs/ -f ~/CondaInstall/Myenv.yml

    Traceback (most recent call last):
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
         return_value = func(*args, **kwargs)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 112, in execute
         installer.install(prefix, pkg_specs, args, env)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 29, in install
         prefix=prefix)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 125, in get_index
         index = fetch_index(channel_priority_map, use_cache=use_cache)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 552, in fetch_index
         repodatas = _collect_repodatas(use_cache, tasks)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 541, in _collect_repodatas
         repodatas = _collect_repodatas_serial(use_cache, tasks)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
         for url, schan, pri in tasks]
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in <listcomp>
         for url, schan, pri in tasks]
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 144, in func
         res = f(*args, **kwargs)
       File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 500, in fetch_repodata
         with open(cache_path, 'w') as fo:
     PermissionError: [Errno 13] Permission denied: '/grid/software/anaconda/4.3.0/anaconda3/pkgs/cache/497deca9.json'

The output of the ``conda info`` command is

                   platform : linux-64
              conda version : 4.3.11
           conda is private : False
          conda-env version : 4.3.11
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.13.0
           root environment : /grid/software/anaconda/4.3.0/anaconda3  (read only)
        default environment : /grid/software/anaconda/4.3.0/anaconda3
           envs directories : /grid/software/anaconda/4.3.0/anaconda3/envs
                              /users/ozak/.conda/envs
              package cache : /grid/software/anaconda/4.3.0/anaconda3/pkgs
                              /users/ozak/.conda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/linux-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/linux-64
                              https://repo.continuum.io/pkgs/pro/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.11 requests/2.13.0 CPython/3.6.0 Linux/2.6.32-642.6.2.el6.x86_64 Scientific Linux/6.5 glibc/2.12
                    UID:GID : 6032:1013

**Comment by kalefranz** [comment]
This is fixed as of conda 4.3.13.  On windows, right-click on the Anaconda Prompt, choose "Run as administrator", and `conda update conda`.

On linux/osx, `sudo /grid/software/anaconda/4.3.0/anaconda3/bin/conda update conda` for THIS SPECIFIC permissions issue.

Once you have 4.3.13, this multi-user permissions error shouldn't occur anymore.

**Comment by PyAntony** [comment]
Hello. I have same issue. I am running Anaconda Prompt as administrator and I can't use any conda command:

example with "conda info":

(C:\USERS\AGD10\ANACONDA3) C:\WINDOWS\system32>conda info
usage: CONDA-script.py [-h] [-V] command ...
CONDA-script.py: error: argument command: invalid choice: 'C:\\USERS\\AGD10\\ANACONDA3\\SCRIPTS\\CONDA-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

I have unistalled and installed 3 times already, following all recommendations (“Just Me”, not adding Anaconda to the PATH, etc.), and nothing seems to work. Any idea?
