### ISSUE TITLE
A basemap installing issue with Anaconda3 on my win7

### ISSUE THREAD

**Issue by TFbg** [conda/conda#4690]
I run with administrator rights "Anaconda Prompt" and in "Anaconda Prompt" run following command:
`conda install -c conda-forge basemap-data-hires=1.0.8.dev0`
but I met the issue:
requests.exceptions.ConnectionError: HTTPSConnectionPool(hosts='binstar-cio-packages-prod.s3.amazonaws.com', prot=443): Read timed out.
Is the proxy is wrong? Please help me.

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
