### ISSUE TITLE
conda attempts to "upgrade" packages with same version from higher priority channel

### ISSUE THREAD

**Issue by kynan** [conda/conda#4700]
This is using the [`jupyterhub/jupyterhub:latest` docker image](https://hub.docker.com/r/jupyterhub/jupyterhub). Contrived MFE (this actually happens when trying to install *any* package):
```
# conda install -y conda-env
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env: 2.6.0-0 conda-forge --> 2.6.0-0 (copy)

Pruning fetched packages from the cache ...
WARNING conda.install:rm_fetched(755): Directory not removed during RM_FETCHED instruction: /opt/conda/pkgs/conda-env-2.6.0-0
Fetching packages ...
conda-env-2.6. 100% |#####################################################| Time: 0:00:00 506.50 kB/s
Extracting packages ...
An unexpected error has occurred.                                                              |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /opt/conda/bin/conda install -y conda-env`




    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/opt/conda/lib/python3.5/site-packages/conda/install.py", line 812, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "/opt/conda/lib/python3.5/site-packages/conda/common/disk.py", line 158, in exp_backoff_fn
        return fn(*args, **kwargs)
    OSError: [Errno 39] Directory not empty: '/opt/conda/pkgs/conda-env-2.6.0-0.tmp' -> '/opt/conda/pkgs/conda-env-2.6.0-0'
```
cc @minrk @willingc

**Comment by kynan** [comment]
Bizzarely this cannot even be worked around by `conda install --no-update-dependencies` iow `conda` *always* attempts to upgrade `conda` and `conda-env`. What's the point of this flag then?

**Comment by kynan** [comment]
This is incredibly frustrating! I can't even force `conda` to not consider the `conda-forge` channel! The following will *still* attempt to upgrade `conda` and `conda-env` from the `conda-forge` channel and fail:

    conda install --yes --no-update-deps -c defaults --override-channels <any package>

**Comment by willingc** [comment]
Hi @kynan,

The Dockerfile can be found in the jupyterhub repo:
https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile

You may edit [this line](https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile) in the Dockerfile to remove `-c conda-forge` and replace with your desired channel.

**Comment by kynan** [comment]
@willingc I know I could do that, but I think I shouldn't need to, right? I'd rather not maintain my own version of the Docker image if I can help it.

**Comment by kalefranz** [comment]
If you don't disable conda's auto-update, use

    conda config --set auto_update_conda false

or

    export CONDA_AUTO_UPDATE_CONDA=false

**Comment by kalefranz** [comment]
Also, you've pretty clearly got a permissions error in your output

    WARNING conda.install:rm_fetched(755): Directory not removed during RM_FETCHED instruction: /opt/conda/pkgs/conda-env-2.6.0-0

I'm guessing that you ran conda with `sudo` in front of it at some point.  That of course will permanently bork permissions for non-root users.  You'll have to `sudo chown -R` to back your way out of it probably.

**Comment by kynan** [comment]
> I'm guessing that you ran conda with `sudo` in front of it at some point. That of course will permanently bork permissions for non-root users. You'll have to `sudo chown -R` to back your way out of it probably.

No, this is running as root in a container. This seems to be a `conda` bug: I think conda tries replacing a package *with the same version* and falls over. See this line in the output listing above:

    conda-env: 2.6.0-0 conda-forge --> 2.6.0-0 (copy)

**Comment by kalefranz** [comment]
Can you give me the Dockerfile contents that can reproduce the error you're seeing?

**Comment by kynan** [comment]
Sorry, I think it really is a permissions issue: I can not reproduce it on a different machine building *the same* derived Docker container. Apologies for the noise!

**Comment by willingc** [comment]
No problem @kynan. Thanks @kalefranz for finding the root cause :cookie:

**Comment by kynan** [comment]
@kalefranz @willingc got to the bottom of this: the issue is caused by [RHEL 7 / CentOS 7 not supporting the Docker `overlay` storage driver](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html), which is the new Docker default. See also docker/docker#27358.
