### ISSUE TITLE
Conda install doesn't recognize dependency when installed with pip

### ISSUE THREAD

**Issue by bsipocz** [conda/conda#4701]
In our CI environments I run into the issue that astropy 1.3 is not yet available with the latest and greatest numpy and python versions. Thus I fall back on installing it with pip.
However when other packages are also needed to be installed, conda install doesn't recognize that their astropy dependency is already available in the environment.

Is there a way to work around this issue? On example build is e.g. this:
https://travis-ci.org/bsipocz/ci-helpers/jobs/203928062

**Comment by kalefranz** [comment]
At the moment, conda's solver doesn't have access to packages that have been pip, gem, npm, yum, etc installed into a conda environment.  This could potentially be a future enhancement, but it would probably require quite a bit of discussion.

**Comment by bsipocz** [comment]
Is there a way for a manual hack? Editing registry files would still be a cleaner solution for our usage than sticking with pip for all the rest of the installs.

**Comment by kalefranz** [comment]
To "trick" conda, you would need to correctly create the file `$PREFIX/conda-meta/astropy-1.3-np111py36_0.json`, or whatever the "correct" file name would be for the astropy you're installing.  For what the format would look like, I'd start with looking for that `conda-meta/astropy-*.json` file in another installation where the version isn't quite correct for you, but close.  Most all the information contained in the `conda-meta/*.json` files comes out of the `info/` directory within the package tarballs, with a few exceptions like `channel`, `schannel`, `url`, and `link`.

**Comment by kalefranz** [comment]
Honestly, the easiest way is to just file a request to update the repo.continuum.io at github.com/ContinuumIO/anaconda-issues

**Comment by bsipocz** [comment]
@kalefranz - Good points, thanks :)

**Comment by bsipocz** [comment]
(Still it's good to have a fallback workaround, as we may run into the similar issue with the next release...)
