### ISSUE TITLE
Error installing ipython

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#4703]
When trying to `conda install anaconda` on a Windows NanoServer container I continually get the below error when it tries to install ipython:
```
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::ipython-5.1.0-py36_0'.
PathNotFoundException()
Attempting to roll back.

PathNotFoundException()
```
This error causes the build of the container to fail (anaconda doesn't get installed). Is there anyway to debug the problem? 

`conda                     4.3.13                   py36_0`

**Comment by mingwandroid** [comment]
add `-v -v -v` to your commandline.

**Comment by kalefranz** [comment]
Yeah I'm not seeing `PathNotFoundException` anywhere in conda code.  `-vvv` should help

**Comment by dhirschfeld** [comment]
Sorry, should have thought of that myself - I just wanted to pose the exception in case it rang a bell.

The output from trying to install ipython is available at: https://gist.github.com/dhirschfeld/b50c2a3640ae4b3fd10511acbaecf8eb

**Comment by dhirschfeld** [comment]
NB: I've seen menuinst errors before with ipython. Usually to do with not being admin, but I think the docker build runs as the container admin - will have to check. Either way the error seems to prevent the install from happening :/

**Comment by mingwandroid** [comment]
Ah NanoServer doesn't have these folders I don't think. Does it even have a Start Menu?

**Comment by dhirschfeld** [comment]
@mingwandroid - that's right, NanoServer doesn't have any GUI or desktop so wouldn't have a Start Menu. This means you can't remote desktop into it as you usually would on Windows but instead manage it via powershell.

I guess that explains the error. I'm wondering how to work around it short of rebuilding the ipython package without the menuinst component?

**Comment by kalefranz** [comment]
Easy fix.  Should just move on if shortcuts can't be created OR if menuinst has any issues.

**Comment by dhirschfeld** [comment]
@kalefranz - could I be cheeky and request a `conda-canary` build including PR #4709 so that I can test it on NanoServer? 

I've tried to manually patch the version on my NanoServer container but it's not working. I suspect that I'm just doing something wrong (learning about docker build caching was a fun waste of a few hours) but to confirm that and hopefully close this issue it would be good to be able to test a properly built and installed package.

There's no big rush - I would like to get to the bottom of the problem though and it seems that will be the best way to definitively rule out any issue on the conda side.

TIA,
Dave

**Comment by kalefranz** [comment]
Yeah I'll make sure we get a canary release cut at least sometime next week.

**Comment by dhirschfeld** [comment]
Thx! :)

**Comment by dhirschfeld** [comment]
I went ahead and built the package myself to test on nanoserver and it seems to be working fine so will close this issue. Thanks for your help sorting it out!
