### ISSUE TITLE
`Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/` during `conda update conda`

### ISSUE THREAD

**Issue by pjacob2** [conda/conda#4704]
I have noticed that conda suddenly no longer updates on one of my machines. If running `conda update conda` I get an error message saying `Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/linux-64/`. I have tried `conda config --add channels conda-canary` fllowed by `conda config --remove channels defaults` as suggested in [another post](https://github.com/conda/conda/issues/3323) but that only produces new error messages. The output of `conda info -a` is as follows:

```
Current conda install:

             platform : linux-64
        conda version : 2.2.5
     root environment : /home/pmj27/anaconda  (writable)
  default environment : /home/pmj27/anaconda
     envs directories : /home/pmj27/anaconda/envs
        package cache : /home/pmj27/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

# conda environments:
#
root                  *  /home/pmj27/anaconda

sys.version: 2.7.11 |Anaconda 2.1.0 (64-bit)| (defaul...
sys.prefix: /home/pmj27/anaconda
sys.executable: /home/pmj27/anaconda/bin/python
conda location: /home/pmj27/anaconda/lib/python2.7/site-packages/conda

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /home/pmj27/software/boost_1.61/lib
PATH: /home/pmj27/anaconda/bin:/home/pmj27/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PYTHONPATH: <not set>

License directories:
    /home/pmj27/.continuum
    /home/pmj27/anaconda/licenses
License files (license*.txt):
Package/feature end dates:
```
What is this issue caused by and how might I resolve it?

**Comment by kalefranz** [comment]
You are running on conda version 2.2.5. The current version is 4.3.13. Usually conda update conda is fine, but you may have to download the latest miniconda and install it overtop your current install.

**Comment by pjacob2** [comment]
That seems to create a new installation though. How do I force it to upgrade the old conda? (I have some packages compiled from source code against my current anaconda and don't want to break that.)

**Comment by kalefranz** [comment]
Install miniconda *overtop* your current root environment. Alternately install miniconda in another location, then use it to manage your old root environment.

**Comment by pjacob2** [comment]
I understand that, I just don't know how to do that in Ubuntu.

**Comment by kalefranz** [comment]
First I would make a backup, even if it's temporary, just in case something goes wrong.

    cp -R /home/pmj27/anaconda /home/pmj27/anaconda2

Then

    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda.sh
    bash ~/miniconda.sh -bfp /home/pmj27/anaconda

**Comment by pjacob2** [comment]
Thank you very much for that!

**Comment by nishankmahore** [comment]
Install MiniConda
sh Miniconda2-latest-Linux-x86_64.sh -f
In the same folder of previous  conda
It will solve all conad related problem

Works for me as charm

**Comment by ramik7** [comment]
it has been working for me as well, Thanks!
