### ISSUE TITLE
Error during clone of an environment

### ISSUE THREAD

**Issue by CodeReclaimers** [conda/conda#4705]
I attempted to clone an existing environment with `conda create --name kaggle --clone neat-3.5`, and this was the result:

> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata: ....
> src_prefix: '/home/alan/anaconda2/envs/neat-3.5'
> dst_prefix: '/home/alan/anaconda2/envs/kaggle'
> Packages: 59
> Files: 36487
> An unexpected error has occurred, please consider sending the
> following traceback to the conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> Include the output of the command 'conda info' in your report.
> 
> 
> Traceback (most recent call last):
>   File "/home/alan/anaconda2/envs/neat-3.5/bin/conda", line 6, in <module>
>     sys.exit(main())
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
>     args_func(args, p)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
>     args.func(args, p)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
>     install.install(args, parser, 'create')
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
>     clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
>     quiet=quiet, index=index)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
>     sorted_dists = r.dependency_sort(dists)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
>     depends = lookup(value)
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
>     return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
>   File "/home/alan/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
>     deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
> KeyError: 'graphviz-2.38.0-1.tar.bz2'

As requested I've attached the output of `conda info`.  I'll leave the created environment on my machine as-is for now, just in case there is some useful info there.

[conda-info.txt](https://github.com/conda/conda/files/794548/conda-info.txt)

For what it's worth: the environment I was cloning has been around for a while, and I've manually installed/uninstalled some packages I had under development many times, so I wouldn't be terribly surprised if there is some unexpected cruft in it as a result.

**Comment by CodeReclaimers** [comment]
Additional info: if I export the environment I wanted to clone into a .yml file, change the name inside the .yml file, and then create a new environment from that, I get this:

> Using Anaconda Cloud api site https://api.anaconda.org
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata: ....
> .Solving package specifications: .
> Error:  Package missing in current linux-64 channels: 
>   - graphviz 2.38.0 1

**Comment by kalefranz** [comment]
There are several known and fixed bugs regarding clone in conda 4.0.5.  `conda update conda` should give you version 4.3.13 and fix your problem.

**Comment by CodeReclaimers** [comment]
Thank you for the quick response--I didn't know I was that far behind!  Apologies for the noise. :)
