### ISSUE TITLE
conda 4.3 missing resources folder - noarch packages broken

### ISSUE THREAD

**Issue by msarahan** [conda/conda#4715]
Observed with 4.3.11 and 4.3.13.

The resources folder just isn't there at all.  What are you doing to try to package it?  I didn't see any reference to it in setup.py or meta.yaml/bld.bat

**Comment by msarahan** [comment]
To clarify: what this folder has in it are the cli-32.exe and cli-64.exe files, which are critical for creating entry point scripts on windows.  Without them, noarch package installation is broken with errors like:

```
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'file:///C:/test_folder/test_noarch_python_with_tests0::noarch_python_test_package-1.0-pyh9d385c3_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda2\lib\site-packages\conda\resources\cli-64.exe
```

**Comment by kalefranz** [comment]
They're listed in MANIFEST.in to my recollection, but I guess that only works for setuptools... I'll track it down.

**Comment by kalefranz** [comment]
Turns out MANIFEST.in actually is a distutils thing, not a setuptools thing, so it should be fine.  The problem is that it only works for *creating* sdists, and our recipes just install directly from setup.py.
