### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by JurijsNazarovs** [conda/conda#4722]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /u/n/a/nazarovs/software/miniconda3  (writable)
    default environment : /u/n/a/nazarovs/software/miniconda3
       envs directories : /u/n/a/nazarovs/software/miniconda3/envs
                          /u/n/a/nazarovs/.conda/envs
          package cache : /u/n/a/nazarovs/software/miniconda3/pkgs
                          /u/n/a/nazarovs/.conda/pkgs
           channel URLs : https://conda.anaconda.org/daler/linux-64
                          https://conda.anaconda.org/daler/noarch
                          https://conda.anaconda.org/asmeurer/linux-64
                          https://conda.anaconda.org/asmeurer/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-45-generic debian/stretch/sid glibc/2.23
                UID:GID : 16603:16603

**Comment by kalefranz** [comment]
Please include the full output of your session.  There is no context to help without additional information.  At a minimum we need the stack trace and the command being executed when the stack trace happened.

**Comment by JurijsNazarovs** [comment]
Here is the whole output of my session. I tried to instal dependencies for some genomic software "atac_dnase_pipelines". The GitHub is following: "https://github.com/kundajelab/atac_dnase_pipelines". I executed the .sh script "instal_dependencies.sh".


./install_dependencies.sh 
Fetching package metadata ...................
Solving package specifications: .

Package plan for installation in environment /u/n/a/nazarovs/software/miniconda3/envs/bds_atac:

The following NEW packages will be INSTALLED:

    argcomplete:                1.0.0-py27_1               
    argh:                       0.26.2-py27_0      bioconda
    bcftools:                   1.3.1-1            bioconda
    bedtools:                   2.26.0-0           bioconda
    bioconductor-biocgenerics:  0.18.0-r3.2.2_0    bioconda
    bioconductor-biocparallel:  1.4.3-r3.2.2_0     bioconda
    bioconductor-biostrings:    2.38.4-0           bioconda
    bioconductor-genomeinfodb:  1.6.3-0            bioconda
    bioconductor-genomicranges: 1.22.4-0           bioconda
    bioconductor-iranges:       2.4.8-0            bioconda
    bioconductor-rsamtools:     1.22.0-r3.2.2_1    bioconda
    bioconductor-s4vectors:     0.8.11-0           bioconda
    bioconductor-xvector:       0.10.0-1           bioconda
    bioconductor-zlibbioc:      1.16.0-r3.2.2_1    bioconda
    biopython:                  1.67-np110py27_0           
    boost:                      1.57.0-4                   
    bowtie:                     1.1.2-py27_2       bioconda
    bowtie2:                    2.2.6-py27_0       bioconda
    bx-python:                  0.7.3-np110py27_1  bioconda
    cairo:                      1.14.8-0                   
    curl:                       7.52.1-0                   
    cutadapt:                   1.9.1-py27_0       bioconda
    cycler:                     0.10.0-py27_0              
    cython:                     0.25.2-py27_0              
    expat:                      2.1.0-0                    
    fastqc:                     0.11.5-1           bioconda
    fisher:                     0.1.4-py27_0       bioconda
    fontconfig:                 2.12.1-3                   
    freetype:                   2.5.5-2                    
    gffutils:                   0.8.7.1-py27_1     bioconda
    ghostscript:                9.16-0             asmeurer
    glib:                       2.43.0-2           asmeurer
    gnuplot:                    4.6.0-1            bioconda
    graphviz:                   2.38.0-4                   
    gsl:                        1.16-1             asmeurer
    harfbuzz:                   0.9.35-6           asmeurer
    htslib:                     1.3.2-0            bioconda
    icu:                        54.1-0                     
    java-jdk:                   8.0.92-1           bioconda
    jbig:                       2.1-0                      
    jinja2:                     2.9.5-py27_0               
    jpeg:                       9b-0                       
    libffi:                     3.0.13-3           asmeurer
    libgcc:                     4.8.5-1            asmeurer
    libgfortran:                3.0.0-1                    
    libiconv:                   1.14-0                     
    libpng:                     1.6.27-0                   
    libtiff:                    4.0.6-3                    
    libtool:                    2.4.2-0            asmeurer
    libxml2:                    2.9.4-0                    
    macs2:                      2.1.0-0            bioconda
    markupsafe:                 0.23-py27_2                
    matplotlib:                 1.5.1-np110py27_0          
    metaseq:                    0.5.6-py27_0       bioconda
    mkl:                        11.3.3-0                   
    mysql:                      5.5.24-0                   
    ncurses:                    5.9-5              asmeurer
    nose:                       1.3.7-py27_1               
    numpy:                      1.10.2-py27_0              
    openblas:                   0.2.14-4                   
    openssl:                    1.0.2k-0                   
    pandas:                     0.18.0-np110py27_0         
    pango:                      1.36.8-3           asmeurer
    pcre:                       8.39-1                     
    perl-threaded:              5.22.0-10          bioconda
    picard:                     1.126-4            bioconda
    pigz:                       2.3-0                      
    pip:                        9.0.1-py27_1               
    pixman:                     0.34.0-0                   
    preseq:                     2.0.2-gsl1.16_0    bioconda
    pybedtools:                 0.6.9-py27_0       bcbio   
    pycairo:                    1.10.0-py27_0              
    pyfaidx:                    0.4.8.1-py27_0     bioconda
    pyparsing:                  2.1.4-py27_0               
    pyqt:                       4.10.4-py27_0      asmeurer
    pysam:                      0.8.2.1-py27_0     bcbio   
    python:                     2.7.13-0                   
    python-dateutil:            2.2-py27_0         asmeurer
    python-levenshtein:         0.12.0-py27_1      bioconda
    pytz:                       2016.10-py27_0             
    pyyaml:                     3.12-py27_0                
    qt:                         4.8.5-0            asmeurer
    r:                          3.2.2-0            asmeurer
    r-base:                     3.2.2-0            asmeurer
    r-bitops:                   1.0_6-r3.2.2_1     asmeurer
    r-boot:                     1.3_17-r3.2.2_0    asmeurer
    r-catools:                  1.17.1-r3.2.2_2    asmeurer
    r-class:                    7.3_14-r3.2.2_0    asmeurer
    r-cluster:                  2.0.3-r3.2.2_0     asmeurer
    r-codetools:                0.2_14-r3.2.2_0    asmeurer
    r-foreign:                  0.8_66-r3.2.2_0    asmeurer
    r-futile.logger:            1.4.1-r3.2.2_0     bioconda
    r-futile.options:           1.0.0-r3.2.2_0     bioconda
    r-kernsmooth:               2.23_15-r3.2.2_0   asmeurer
    r-lambda.r:                 1.1.7-r3.2.2_0     bioconda
    r-lattice:                  0.20_33-r3.2.2_0   asmeurer
    r-mass:                     7.3_44-r3.2.2_0    asmeurer
    r-matrix:                   1.2_2-r3.2.2_0     asmeurer
    r-mgcv:                     1.8_7-r3.2.2_0     asmeurer
    r-nlme:                     3.1_122-r3.2.2_0   asmeurer
    r-nnet:                     7.3_11-r3.2.2_0    asmeurer
    r-recommended:              3.2.2-r3.2.2_0     asmeurer
    r-rpart:                    4.1_10-r3.2.2_0    asmeurer
    r-snow:                     0.4_1-r3.2.2_0     bioconda
    r-snowfall:                 1.84_6.1-r3.2.2_0  bioconda
    r-spatial:                  7.3_11-r3.2.2_0    asmeurer
    r-spp:                      1.13-r3.2.2_0      bioconda
    r-survival:                 2.38_3-r3.2.2_0    asmeurer
    readline:                   6.2-2                      
    sambamba:                   0.6.5-0            bioconda
    samtools:                   1.2-2              bioconda
    scikit-learn:               0.17.1-np110py27_2         
    scipy:                      0.17.0-np110py27_4         
    setuptools:                 27.2.0-py27_0              
    simplejson:                 3.10.0-py27_0              
    sip:                        4.15.5-py27_0      asmeurer
    six:                        1.10.0-py27_0              
    sqlite:                     3.13.0-0                   
    system:                     5.8-2                      
    tk:                         8.5.18-0                   
    trim-galore:                0.4.1-0            bioconda
    ucsc-bedclip:               332-0              bioconda
    ucsc-bedgraphtobigwig:      323-0              daler   
    ucsc-bedtobigbed:           323-0              daler   
    ucsc-bigwigaverageoverbed:  332-0              bioconda
    ucsc-bigwiginfo:            332-0              bioconda
    ucsc-fetchchromsizes:       323-0              daler   
    ucsc-wigtobigwig:           323-0              daler   
    wheel:                      0.29.0-py27_0              
    xz:                         5.2.2-1                    
    yaml:                       0.1.6-0                    
    zlib:                       1.2.8-3                    

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /u/n/a/nazarovs/software/miniconda3  (writable)
    default environment : /u/n/a/nazarovs/software/miniconda3
       envs directories : /u/n/a/nazarovs/software/miniconda3/envs
                          /u/n/a/nazarovs/.conda/envs
          package cache : /u/n/a/nazarovs/software/miniconda3/pkgs
                          /u/n/a/nazarovs/.conda/pkgs
           channel URLs : https://conda.anaconda.org/daler/linux-64
                          https://conda.anaconda.org/daler/noarch
                          https://conda.anaconda.org/asmeurer/linux-64
                          https://conda.anaconda.org/asmeurer/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/bcbio/linux-64
                          https://conda.anaconda.org/bcbio/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-45-generic debian/stretch/sid glibc/2.23
                UID:GID : 16603:16603



`$ /u/n/a/nazarovs/software/miniconda3/bin/conda create -n bds_atac --file requirements.txt -y -c daler -c asmeurer -c defaults -c bioconda -c bcbio -c r`




    Traceback (most recent call last):
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/u/n/a/nazarovs/software/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: '/u/n/a/nazarovs/software/miniconda3/pkgs/qt-4.8.5-0/info/index.json'

**Comment by JurijsNazarovs** [comment]
If I am glad to provide other information about the current run, if I have it.

**Comment by kalefranz** [comment]
`conda clean --packages` will fix the stack trace ending with `FileNotFound`
