### ISSUE TITLE
Anacoda Navigator unable to install or upgrade packages

### ISSUE THREAD

**Issue by gabrif7** [conda/conda#4725]
Hello everyone,

When I try to Install packages or to upgrade already installed packages, after some processes and elaboration, nothing happened and the libraries result not installed or upgraded.

I am using Anaconda Navigator 1.4.3 and the software is installed in C:\ProgramData\Anaconda3.
Python version 3.6
Unfortunately I haven't found similar issues online.

Gabriele

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1707
