### ISSUE TITLE
documentation: CONDA_DEFAULT_ENV influences conda commands

### ISSUE THREAD

**Issue by bkreider** [conda/conda#473]
`conda install` without -n or -p will install outside of the root environment if `CONDA_DEFAULT_ENV` is set to something else.  There is confusion over whether activate influences this as well.  I didn't see any documentation here:  
http://docs.continuum.io/conda/commands/install.html

It should probably be added to all of the commands that it influences and be cross-referenced.

**Comment by kalefranz** [comment]
Outdated. Closing.
