### ISSUE TITLE
conda update --all problem

### ISSUE THREAD

**Issue by m00nd00r** [conda/conda#4736]
I ran this command and in the process of updating and installing, it hung up at ipywidgets... saying it was at 100%, but then 15 minutes later there was no change in the terminal window. So I closed it, restarted, and tried again. To this I got the following error, telling me to post it here:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : C:\Users\Johnnysporto\Anaconda2  (writable)
    default environment : C:\Users\Johnnysporto\Anaconda2
       envs directories : C:\Users\Johnnysporto\Anaconda2\envs
                          C:\Users\Johnnysporto\AppData\Local\conda\conda\envs
                          C:\Users\Johnnysporto\.conda\envs
          package cache : C:\Users\Johnnysporto\Anaconda2\pkgs
                          C:\Users\Johnnysporto\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.12 Windows/10 Windows/10.0.14393

`$ C:\Users\Johnnysporto\Anaconda2\Scripts\conda-script.py update --all`

    Traceback (most recent call last):
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\Johnnysporto\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\Johnnysporto\\Anaconda2\\pkgs\\notebook-4.3.1-py27_1\\info\\index.json'

**Comment by robbuckley** [comment]
hi, i got very similar issue, except mine is hung up in a different file. It happened after i updated conda from 4.2.13 to 4.3.13 in my root environment.

Then I switched to another environment (called python3) and ran

`conda update --all `

I got a hang similar to the one @m00nd00r describes and had to close the command window. After this i get an IOerror when trying to update --all or the python package. 

Interestingly i also get the same error when trying to clone the broken environment:

```
Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.10
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : C:\Users\Rob Buckley\Anaconda2  (writable)
    default environment : C:\Users\Rob Buckley\Anaconda2
       envs directories : C:\Users\Rob Buckley\Anaconda2\envs
                          C:\Users\Rob Buckley\AppData\Local\conda\conda\envs
                          C:\Users\Rob Buckley\.conda\envs
          package cache : C:\Users\Rob Buckley\Anaconda2\pkgs
                          C:\Users\Rob Buckley\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : C:\Users\Rob Buckley\.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.12 Windows/10 Windows/10.0.14393



`$ C:\Users\
```Rob Buckley\Anaconda2\Scripts\conda-script.py create --name py3_broken --clone python3`




    Traceback (most recent call last):
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\cli\install.py", line 212, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\cli\install.py", line 69, in clone
        index_args=index_args)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\misc.py", line 312, in clone_env
        force_extract=False, index_args=index_args)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\misc.py", line 94, in explicit
        _supplement_index_with_cache(index, ())
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\core\index.py", line 65, in _supplement_index_with_cache
        index_json_record = read_index_json(pkg_dir)
      File "C:\Users\Rob Buckley\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\Rob Buckley\\Anaconda2\\pkgs\\python-3.5.3-0\\info\\index.json'

**Comment by robbuckley** [comment]
issue #4687 looks similar also

**Comment by mingwandroid** [comment]
Would it be possible to try to install into a folder *without* spaces in it and post your results?

**Comment by kalefranz** [comment]
@m00nd00r 

    conda clean --packages

should fix your issue

**Comment by kalefranz** [comment]
@robbuckley 

I'm guessing `conda clean --packages` fixes that stack trace for you also.

**Comment by robbuckley** [comment]
@kalefranz yes that seems to have done the trick. I went thru a sequence

```
conda clean --packages
conda update --all
```

first in the affected environment - at this point i got the same error. I repeated that sequence in the root environment, which took forever as i rarely use it so it was horribly out of date. Then again in the affected environment, when it all seemed to work OK

thanks!

**Comment by m00nd00r** [comment]
so i ran an update on ipywidgets separately and then conda update --all hung up on the package notebook.

after a few more dead ends, i deleted the notebook package and reinstalled it. i restarted and reran conda update --all and everything worked fine.

thanks @kalefranz for the clean command. i'll try it next time something like this happens.
