### ISSUE TITLE
CondaError: MD5MismatchError qt-5.6.2-vc14_3.tar.bz2 [Windows 64]

### ISSUE THREAD

**Issue by cdelaserna** [conda/conda#4739]
I am getting this error whenever I run `conda update anaconda` or creating a new environment. 

```
CondaError: MD5MismatchError: MD5MismatchError: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2 (ebda0633bf4e02893f2969565feb3db1 != 546100cb1c07d6b88f39eae6029e374b)
```

```
C:\WINDOWS\system32>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Christian\AppData\Local\conda\conda\envs
                          C:\Users\Christian\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Christian\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Christian\.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393
```

my .condarc file only contains `{}`

**Comment by mingwandroid** [comment]
I believe this is a connectivity error at your side. Can you try opening that URL in a browser?

**Comment by cdelaserna** [comment]
Yes, no problem opening `https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2` and downloading it through  my browser. Manually checked MD5 `EBDA0633BF4E02893F2969565FEB3DB1`.

**Comment by mingwandroid** [comment]
That is very strange, for me:

```
md5 qt-5.6.2-vc14_3.tar.bz2 
MD5 (qt-5.6.2-vc14_3.tar.bz2) = 546100cb1c07d6b88f39eae6029e374b
```

How big is the file?

**Comment by cdelaserna** [comment]
Here are my file details.

![dllhost_2017-02-27_06-17-43](https://cloud.githubusercontent.com/assets/4268756/23344277/8212e690-fcb4-11e6-966a-882a8a394045.png)

**Comment by mingwandroid** [comment]
For me:
```
ls -l qt-5.6.2-vc14_3.tar.bz2 
-rw-r--r--  1 rdonnelly  staff  58116806  7 Feb 23:05 qt-5.6.2-vc14_3.tar.bz2
```

@kalefranz, any clues about this?

**Comment by mingwandroid** [comment]
@cdelaserna can you upload the file somewhere? I need to inspect it.

**Comment by cdelaserna** [comment]
https://www.dropbox.com/s/zfehnbgf81h8dwq/qt-5.6.2-vc14_3.tar.bz2?dl=0

**Comment by mingwandroid** [comment]
Thanks, investigating now.

**Comment by mingwandroid** [comment]
OK, this is odd. I'm glad my first thought was incorrect. It seems yours is a previous version of the file which would point to something up with our CDNs replication of that file. I'll assign it to one of my colleagues who knows about that side of things.

**Comment by guolinke** [comment]
got the same error in the travis: https://travis-ci.org/Microsoft/LightGBM/jobs/206527335

**Comment by mingwandroid** [comment]
@kalefranz, this was a repackaging by @ilanschnell (why was it repackaged Ilan? I don't see the need since we don't do binary replacement on Windows and that's all that was changed).

Some edge nodes (or something) now have stale versions. I'm fairly surprised the edge nodes and the master do not resync with each other every few hours, how slow can sending a bunch of sha1s be? Can we script something to check for this situation and fix it?

**Comment by ilanschnell** [comment]
Yes, it was repackaged to remove the binary placeholder.  Out of the about 60k packages in the default repo, I repackages around 11k over the past two weeks (in order to remove the hotfixes of the metadata).  There are only about 4k packages which still need to be done.

**Comment by mingwandroid** [comment]
Thanks @ilanschnell. Looking at the diffs, you *added* the following 2 binary prefix replacement records to `info/has_prefix`, I'm not sure why though as Windows should not attempt to ever do this anyway, and if it were to we'd end up with broken Qt. Can you detail why this was necessary? Is it working around a bug elsewhere?

```
"C:/Users/ray/qtb-3.5-64/_b_env" binary "Library/bin/Qt5Core.dll"
"C:/Users/ray/qtb-3.5-64/_b_env" binary "Library/bin/qmake.exe"
```

Good work on the hot-fix freezing btw. Cheers!

**Comment by ilanschnell** [comment]
@mingwandroid looking at `win-64/qt-5.6.2-vc14_3.tar.bz2` (which has MD5: `546100cb1c07d6b88f39eae6029e374b`), I don't see any binary placeholders.  The content of `info/has_prefix` is:
```
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5AxBase.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5AxContainer.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5AxServer.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5Bootstrap.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5LabsControls.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5OpenGLExtensions.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5PlatformSupport.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5QmlDevTools.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/Qt5UiTools.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/qtfreetype.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/lib/qtmain.prl"
"C:/Users/ray/qtb-3.5-64/_b_env" text "Library/mkspecs/qmodule.pri"
```

**Comment by mingwandroid** [comment]
Yup, you removed them, but I'd like to know why this was necessary since Windows should not attempt to use them anyway.

**Comment by ilanschnell** [comment]
It wasn't strictly necessary, but I wanted to avoid confusion.  Since I've been repackaging thousands of other packages, I though repackaging a few more wouldn't do any harm.

**Comment by mingwandroid** [comment]
Ah OK thanks. So we just need to hear from @kalefranz if there's anything we can automate to prevent this edge node de-sync from happening.

**Comment by kalefranz** [comment]
What I'm currently seeing is the md5 matching for repodata and the downloaded file.

```
kfranz@0283:~ ❯ curl -sS https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2 | md5
546100cb1c07d6b88f39eae6029e374b
kfranz@0283:~ ❯ curl -sS https://repo.continuum.io/pkgs/free/win-64/repodata.json | jq .packages | jq '.["qt-5.6.2-vc14_3.tar.bz2"].md5'
"546100cb1c07d6b88f39eae6029e374b"
```

If this is actually a case of an edge node not properly invalidating, while other edge nodes are (i.e. different edge nodes being out of sync), this would be the first time I'm seeing that.

@cdelaserna Before I go clear the edge caches for that one file, can you give me the output of

    curl -I https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2

If you don't have curl, you can install it with `conda install m2-curl`.

**Comment by kalefranz** [comment]
P.S. @mingwandroid I don't see an `m2-md5` or `m2-md5sum` with `conda search`.  Any chance you can throw that in at some point when you're in that package neighborhood?
