### ISSUE TITLE
kaspersky - Internet Security is blaocking Ipython console to be running in Spyder

### ISSUE THREAD

**Issue by kjoth** [conda/conda#4753]
Hi,

Windows 10
Anaconda 3 - 64bit
Ipython console is not starting and kernel keeps dying. 
When I disable the kaspersky the Ipython Console is working in Anaconda Spyder.  When kaspersky is turned on its not letting Spyder to start.

Windows 8.1
Anaconda 3 - 64bit
Here also I'm using the same version of kaspersky and using but here ipthon console in anaconda spyder is working fine.

Could some one help on this. 

Note: I've reinstalled so many times, with Anaconda 2.7 and 3 version, still problem occurs.

**Comment by mingwandroid** [comment]
Can you report this with Kaspersky please?

**Comment by kjoth** [comment]
@mingwandroid: Yeah Sure I will raise with them and update here the solutions they provide.
