### ISSUE TITLE
conda  HTTPError in windows

### ISSUE THREAD

**Issue by godofyoga** [conda/conda#4754]
Hello ,
Please help me to solve this problem
C:\Users\yogesh>conda update anaconda
Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/

Thank you,
yogesh

**Comment by kjoth** [comment]
Could you kindly check weather you could open the link in your browser.

**Comment by godofyoga** [comment]
yes i am accessing internet in browser.
C:\Users\yogesh>ping google.com

Pinging google.com [216.58.220.46] with 32 bytes of data:
Reply from 216.58.220.46: bytes=32 time=23ms TTL=53
Reply from 216.58.220.46: bytes=32 time=23ms TTL=53
Reply from 216.58.220.46: bytes=32 time=23ms TTL=53
Reply from 216.58.220.46: bytes=32 time=24ms TTL=53

Ping statistics for 216.58.220.46:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 23ms, Maximum = 24ms, Average = 23ms

**Comment by kjoth** [comment]
Could you open this url http://repo.continuum.io/pkgs/pro/win-64/ in your browser?

**Comment by godofyoga** [comment]
yes i can able to open following link in my browser http://repo.continuum.io/pkgs/pro/win-64/

**Comment by godofyoga** [comment]
How can i use files from this link to solve problem

**Comment by kalefranz** [comment]
That happens for very old versions of conda.  Please `conda update conda`.

**Comment by kalefranz** [comment]
For more background, it happens because old versions use an http handler that doesn't follow redirects.  You can also change the configuration to use all https:// urls.

**Comment by godofyoga** [comment]
conda update conda is not working
How can i change http://  to https://  in url path?
