### ISSUE TITLE
An unexpected error has occurred while installing >conda install seaborn on windows 10

### ISSUE THREAD

**Issue by upavan** [conda/conda#4758]
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'

Note : Operating system - Windows 10

**Comment by kalefranz** [comment]
This is fixed as of conda 4.3.13.  `conda update conda`.  You'll need to run `conda update conda` as an Administrator.  Right click on the Anaconda Prompt and choose "Run as administrator".
