### ISSUE TITLE
please help resolving this issue

### ISSUE THREAD

**Issue by chaitanya6761** [conda/conda#4770]
Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\chaitanya\Anaconda3  (writable)
    default environment : C:\Users\chaitanya\Anaconda3
       envs directories : C:\Users\chaitanya\Anaconda3\envs
                          C:\Users\chaitanya\AppData\Local\conda\conda\envs
                          C:\Users\chaitanya\.conda\envs
          package cache : C:\Users\chaitanya\Anaconda3\pkgs
                          C:\Users\chaitanya\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.5.2 Windows/7 W
indows/6.1.7601

`$ C:\Users\chaitanya\Anaconda3\Scripts\conda-script.py update numpy`

    Traceback (most recent call last):
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\exceptions.py",
 line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\cli\main.py", l
ine 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\cli\main_update
.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\cli\install.py"
, line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\plan.py", line
823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\instructions.py
", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\instructions.py
", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dist
s, link_dists)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\core\link.py",
line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\core\link.py",
line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\gateways\disk\r
ead.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\chaitanya\Anaconda3\lib\site-packages\conda\gateways\disk\r
ead.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi
:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\chaitany
a\\Anaconda3\\pkgs\\scikit-learn-0.18.1-np111py35_1\\info\\index.json'

C:\Users\chaitanya>

**Comment by kalefranz** [comment]
`conda clean --packages` should fix your problem

**Comment by kalefranz** [comment]
Please let me know if you still have problems.  Closing this issue now.  Will improve handling of this specific stack trace in a future PR.
