### ISSUE TITLE
conda spending much time looking through files in package cache (conda 4.3.13)

### ISSUE THREAD

**Issue by wresch** [conda/conda#4777]
Hi - 
this is kind of hard to look for in the issues so I apologize in advance if this has already been brought up.  Recently, any conda operation has been extremely slow. For example, a simple conda search takes 5 minutes:

```
$ time conda search pysam
[...snip...]
real    4m58.644s
user    3m3.074s
sys     0m46.633s
```
This was with 3 channels active. Nearly the same time with just the defaults channel. As a quick and dirty way to try and figure out what is happening I did an strace with time stamps
```
strace -fro conda_search_strace conda search pysam
```
That ran for 272s
```
$ awk '{t+=$2}END{print t}' conda_search_strace
272.496
```

Most of that time (2/3) is spent stat-ing files in the package cache:
```
$ grep 'stat' conda_search_strace | grep '/usr/local/Anaconda/pkgs' | awk '{t+=$2}END{print t}'
178.849
```

Our package cache is large (68GiB - it's a central install used by admins and users to create many environments so it's hard to clean up) and located on a more-or-less busy NFS mounted file system.  Indeed at less busy times this operation runs faster, though still 2 minutes, which is still somewhat painful.

So my questions are (1) did something change in conda that would explain this slowdown? (2) is there anything we can do? Or conversely - are we doing something to cause this? (3) could whatever conda does that requires touching everything in the package cache be optimized? caching? database?

Anyway - please forgive me if i missed something obvious.

```
$ conda info

Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /usr/local/Anaconda  (writable)   <--- on NFS
    default environment : /usr/local/Anaconda
       envs directories : /usr/local/Anaconda/envs
                          /home/$USER/.conda/envs
          package cache : /usr/local/Anaconda/pkgs   <-- this is large
                          /home/$USER/.conda/pkgs    <-- nothing here
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          file:///usr/local/Anaconda/conda-bld/linux-64
                          file:///usr/local/Anaconda/conda-bld/noarch
            config file : /home/$USER/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.12 Linux/2.6.32-642.13.1.el6.x86_64 Red Hat Enterprise Linux Server/6.8 glibc/2.12
                UID:GID : XXXXX:XXXXX
```

**Comment by kalefranz** [comment]
> (1) did something change in conda that would explain this slowdown?

yes

> (2) is there anything we can do?

There must be.  This is the first report, but I'll look into ways of making the package cache scanning more lazy.

> (3) could whatever conda does that requires touching everything in the package cache be optimized? caching? database?

Going to look into this now, and leave this issue open to track it.  You haven't missed anything obvious, and thanks for your report and the debug work you did to narrow down the problem!

**Comment by kalefranz** [comment]
Quick question, about how many top-level directories and also how many tarballs in `/usr/local/Anaconda/pkgs`?  `ls /usr/local/Anaconda/pkgs/*.tar.bz2 | wc -l` for example.

**Comment by wresch** [comment]
It's rather large:
```
$ find /usr/local/Anaconda/pkgs -maxdepth 1 -mindepth 1 -type d | wc -l
4125
$ ls /usr/local/Anaconda/pkgs/*.tar.bz2 | wc -l
4020
```
I didn't check this before, but the tar balls show up in the strace output more than the directories:
```
$ grep '/usr/local/Anaconda/pkgs' conda_search_strace | grep '.bz2' | wc -l
10780
$ grep '/usr/local/Anaconda/pkgs' conda_search_strace | grep -v '.bz2' | wc -l
5854
```

I had mad a wrong assumption about spending more time looking into the directories than the tar balls.  Would cleaning the tar balls (`conda clean --tarballs`) be a mostly non-disruptive way to shave a significant amount of time off?  As I hinted before I don't think I can do a `conda clean -p` b/c there are environments outside the root that are symlinked.

**Comment by kalefranz** [comment]
Don't blow away any of your cache with `conda clean --tarballs` or `--packages` just yet, if you can help it.  Give me 24 hours to dig in and see what I can come up with for lazy access to the data we need.

**Comment by wresch** [comment]
OK. Thanks. Let me know if I can help with anything.

**Comment by kalefranz** [comment]
@wresch I've started working on #4778 to try to figure out what's going on here.  When you said most of the time was spent with tarballs, I was worried that we were needlessly calculating md5 sums for each one.  I don't think that's the case though.  At least not for `conda search`.

In #4778 I've made the package cache initialization a little more lazy, but I don't think I've affected anything that much.  Feels like I haven't found a smoking gun yet.  Still working though.

**Comment by kalefranz** [comment]
> Would cleaning the tar balls (conda clean --tarballs) be a mostly non-disruptive way to shave a significant amount of time off?

Just as a test, would you mind moving those tarballs to a different directory, then running your `conda search` test case again?  See what kind of result you get?  That might help point to something I'm overlooking right now.

**Comment by wresch** [comment]
I created a profiled version of conda and ran the same conda search before
moving any tarballs:

```
$ cat bin/_condap
#!/usr/local/Anaconda/bin/python
if __name__ == '__main__':
    import sys
    import conda.cli
    import cProfile
    pr = cProfile.Profile()
    pr.enable()
    rt = conda.cli.main()
    pr.disable()
    pr.dump_stats("conda.profile")
    sys.exit(rt)

$ _condap search pysam
Fetching package metadata .............
pysam                        0.7.7                    py27_0  local
                             0.8.2.1                  py27_0  local
[...snip...]

$ ls -lh conda.profile
-rw-rw-r-- 1 user user 1.5M Mar  1 21:28 conda.profile
```

Let's look at the profile:
```
$ python
>>> import pstats
>>> p = pstats.Stats('conda.profile')
>>> p.sort_stats('cumulative').print_stats(30)
Wed Mar  1 21:28:18 2017    conda.profile

         101000008 function calls (97112032 primitive calls) in 259.595 seconds

   Ordered by: cumulative time
   List reduced from 3901 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002  259.735  259.735 /usr/local/Anaconda/lib/python2.7/site-packages/conda/cli/main.py:139(main)
        1    0.000    0.000  259.541  259.541 /usr/local/Anaconda/lib/python2.7/site-packages/conda/exceptions.py:589(conda_exception_handler)
        1    0.003    0.003  259.541  259.541 /usr/local/Anaconda/lib/python2.7/site-packages/conda/cli/main.py:83(_main)
        1    0.218    0.218  258.323  258.323 /usr/local/Anaconda/lib/python2.7/site-packages/conda/cli/main_search.py:122(execute)
        1    0.008    0.008  258.105  258.105 /usr/local/Anaconda/lib/python2.7/site-packages/conda/cli/main_search.py:128(execute_search)
        1    0.002    0.002  152.039  152.039 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:191(get_all_extracted_entries)
      281    0.001    0.000  151.283    0.538 {map}
       22    0.000    0.000  151.258    6.875 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:133(__call__)
        3    0.000    0.000  151.258   50.419 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:193(<genexpr>)
        2    0.000    0.000  151.258   75.629 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:151(__init__)
        2    0.083    0.041  151.250   75.625 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:254(_init_dir)
     4138    0.067    0.000  148.854    0.036 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:273(_add_entry)
     4467    0.008    0.000  147.352    0.033 {next}
     4139    0.040    0.000  147.208    0.036 /usr/local/Anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py:58(first)
     8157    5.802    0.001  147.147    0.018 /usr/local/Anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py:88(<genexpr>)
  9343473    7.474    0.000  138.901    0.000 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/package_cache.py:274(<lambda>)
  9343473   13.837    0.000  131.427    0.000 /usr/local/Anaconda/lib/python2.7/site-packages/conda/common/path.py:246(safe_basename)
  9370558    9.792    0.000  104.984    0.000 /usr/local/Anaconda/lib/python2.7/re.py:143(search)
        1    0.001    0.001  103.355  103.355 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/index.py:75(get_index)
        1    0.000    0.000  103.350  103.350 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/index.py:103(fetch_index)
        1    0.006    0.006  103.342  103.342 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/repodata.py:56(collect_all_repodata)
        1    0.000    0.000  103.336  103.336 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/repodata.py:453(_collect_repodatas_serial)
       10    0.002    0.000  103.334   10.333 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/repodata.py:103(func)
       10    0.124    0.012  103.329   10.333 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/repodata.py:400(fetch_repodata)
  9374488   82.540    0.000   82.540    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
       10    0.001    0.000   66.595    6.660 /usr/local/Anaconda/lib/python2.7/site-packages/conda/core/repodata.py:111(fetch_repodata_remote_request)
       10    0.000    0.000   65.227    6.523 /usr/local/Anaconda/lib/python2.7/site-packages/requests/sessions.py:492(get)
       10    0.000    0.000   65.227    6.523 /usr/local/Anaconda/lib/python2.7/site-packages/requests/sessions.py:411(request)
       10    0.001    0.000   65.175    6.518 /usr/local/Anaconda/lib/python2.7/site-packages/requests/sessions.py:569(send)
        8    0.000    0.000   65.050    8.131 /usr/local/Anaconda/lib/python2.7/site-packages/requests/adapters.py:375(send)
```

So almost half the time seems to be spent on regular expression searches. I did a separate,
more hacky experiment where I traced all function calls and that seems to back up this
conclusions (most calls are to re.compile and re.search). It looks to me like the main
culprit may be conda/core/package_cache.py:191(get_all_extracted_entries).

Here are the same top 30 functions with callee information. I got this by calling

```
pstats.Stats('conda.profile').sort_stats('cumulative').print_callees(30)
```

and then editing the output to remove any calls that cost little or no time and
shortening paths. That give a bit of a better picture for the code path. About
half the time is spent in intex.py(get_index), the other in package_cache.py(get_all_extracted_entries).

Within get_all_extracted_patterns about 2/3 of the time seems to go to
regular expression searches - 10 million of them in fact - plus some time
in safe_basename.

Within get_index, 2/3 of the time seem to go towards the url requests and
the rest to processing and writing pickled data.


```
   Ordered by: cumulative time
   List reduced from 3901 to 30 due to restriction <30>

Function                                                                                                    called...
                                                                                            ncalls  tottime  cumtime
site-packages/conda/cli/main.py:139(main)                                 ->       1    0.000  259.541  site-packages/conda/exceptions.py:589(conda_exception_handler)
site-packages/conda/exceptions.py:589(conda_exception_handler)            ->       1    0.003  259.541  site-packages/conda/cli/main.py:83(_main)
site-packages/conda/cli/main.py:83(_main)                                 ->       1    0.218  258.323  site-packages/conda/cli/main_search.py:122(execute)
site-packages/conda/cli/main_search.py:122(execute)                       ->       1    0.008  258.105  site-packages/conda/cli/main_search.py:128(execute_search)
site-packages/conda/cli/main_search.py:128(execute_search)                ->       1    0.001  103.355  site-packages/conda/core/index.py:75(get_index)
                                                                                   1    0.002  152.039  site-packages/conda/core/package_cache.py:191(get_all_extracted_entries)
#-------------------------

site-packages/conda/core/package_cache.py:191(get_all_extracted_entries)  ->       1    0.000  151.258  {map}
{map}                                                                     ->       3    0.000  151.258  site-packages/conda/core/package_cache.py:193(<genexpr>)
site-packages/conda/core/package_cache.py:193(<genexpr>)                  ->       2    0.000  151.258  site-packages/conda/core/package_cache.py:133(__call__)
site-packages/conda/core/package_cache.py:133(__call__)                   ->       2    0.000  151.258  site-packages/conda/core/package_cache.py:151(__init__)
site-packages/conda/core/package_cache.py:151(__init__)                   ->       2    0.083  151.250  site-packages/conda/core/package_cache.py:254(_init_dir)
site-packages/conda/core/package_cache.py:254(_init_dir)                  ->    4138    0.067  148.854  site-packages/conda/core/package_cache.py:273(_add_entry)
site-packages/conda/core/package_cache.py:273(_add_entry)                 ->    4138    0.040  147.208  site-packages/conda/_vendor/auxlib/collection.py:58(first)
site-packages/conda/_vendor/auxlib/collection.py:58(first)                ->    4139    0.007  147.151  {next}
{next}                                                                    ->    4139    5.799  147.144  site-packages/conda/_vendor/auxlib/collection.py:88(<genexpr>)
site-packages/conda/_vendor/auxlib/collection.py:88(<genexpr>)            -> 9343473    7.474  138.901  site-packages/conda/core/package_cache.py:274(<lambda>)
site-packages/conda/core/package_cache.py:274(<lambda>)                   -> 9343473   13.837  131.427  site-packages/conda/common/path.py:246(safe_basename)
site-packages/conda/common/path.py:246(safe_basename)                     -> 9343473    9.742  104.652  re.py:143(search)
re.py:143(search)                                                         -> 9370558   12.653   12.659  re.py:230(_compile)
                                                                             9370558   82.533   82.533  {method 'search' of '_sre.SRE_Pattern' objects}
#-------------------------

site-packages/conda/core/index.py:75(get_index)                           ->       1    0.000  103.350  site-packages/conda/core/index.py:103(fetch_index)
site-packages/conda/core/index.py:103(fetch_index)                        ->       1    0.006  103.342  site-packages/conda/core/repodata.py:56(collect_all_repodata)
site-packages/conda/core/repodata.py:56(collect_all_repodata)             ->       1    0.000  103.336  site-packages/conda/core/repodata.py:453(_collect_repodatas_serial)
site-packages/conda/core/repodata.py:453(_collect_repodatas_serial)       ->      10    0.002  103.334  site-packages/conda/core/repodata.py:103(func)
site-packages/conda/core/repodata.py:103(func)                            ->      10    0.124  103.329  site-packages/conda/core/repodata.py:400(fetch_repodata)
site-packages/conda/core/repodata.py:400(fetch_repodata)                  ->      10    0.001   66.595  site-packages/conda/core/repodata.py:111(fetch_repodata_remote_request)
                                                                                   6    0.034   15.960  site-packages/conda/core/repodata.py:302(write_pickled_repodata)
                                                                                   6    0.487   14.215  site-packages/conda/core/repodata.py:371(process_repodata)
{method 'search' of '_sre.SRE_Pattern' objects}                           ->
site-packages/conda/core/repodata.py:111(fetch_repodata_remote_request)   ->      10    0.000   65.227  site-packages/requests/sessions.py:492(get)
site-packages/requests/sessions.py:492(get)                               ->      10    0.000   65.227  site-packages/requests/sessions.py:411(request)
site-packages/requests/sessions.py:411(request)                           ->      10    0.001   65.175  site-packages/requests/sessions.py:569(send)
site-packages/requests/sessions.py:569(send)                              ->       8    0.000   65.050  site-packages/requests/adapters.py:375(send)
site-packages/requests/adapters.py:375(send)                              ->       8    0.000    0.002  site-packages/requests/adapters.py:198(cert_verify)
                                                                                   8    0.001   65.035  site-packages/requests/packages/urllib3/connectionpool.py:449(urlopen)
```

I can do some experiments tomorrow with moving the tar balls. Since the profiles are a little hard to look at with the narrow-ish window i also attached a text file with just the two profile summaries
[profiles.txt](https://github.com/conda/conda/files/812687/profiles.txt)

**Comment by kalefranz** [comment]
This is awesome information!  I don't have a big package cache to run against, and I didn't feel like faking one out, so really appreciate this profiling work.  Let me chew on it a bit...

FYI if you want to watch debug output, use two `-v` flags.  Three `-v` flags and you get "trace" level output, which is *extremely* verbose, especially during install/uninstall operations.

For the get_index part of the time, that concerns downloading and local caching repodata.json.  If there isn't a local cached copy, then you should see HTTP 200 responses, repodata downloads, and pickle writing output in debug logs.  That scenario eats up a bit of time.  However those repodata files don't change that often, at least for repo.continuum.io--maybe a few times a day.  So for successive runs, get_index should become pretty speedy, with seeing either no HTTP calls at all (going off the mtime of the local cached file) or HTTP calls with 304 responses, and then only reading pickled data structures into memory.  This part is as optimized as it's going to get in the near-term.  In the longer term, we're looking at alternate ways of storing and accessing this information (e.g. a sqlite db) so that it can be more efficiently queried and we don't have to load the whole universe of information into memory for each and every operation.

All the regex time is a surprise though, and seems like something we should be able to improve dramatically.

**Comment by kalefranz** [comment]
For the record, I was of the understanding that you actually didn't need to pre-compile regexs in python anymore because they the compiled version are efficiently cached by the all the various regex functions. Perhaps that's misguided. Or perhaps that's only true for python 3.

**Comment by groutr** [comment]
@kalefranz What does safe_basename offer over the standard library (pathlib and os.path)?

**Comment by kalefranz** [comment]
@groutr `ntpath.basename` doesn't properly handle escaped spaces in paths and `posixpath.basename` doesn't work with backslashes.  `pathlib` is python >= 3.4 only.

**Comment by wresch** [comment]
Do you still want me to experiment with moving the tarballs out of the cache?

**Comment by kalefranz** [comment]
> Do you still want me to experiment with moving the tarballs out of the cache?

At the moment now, I don't think that's going to tell us anything.  I think the hot spot we're running into would get triggered either way.

**Comment by groutr** [comment]
@kalefranz enum is also only for Python >=3.4. There is a backport for pathlib called pathlib2 (https://pypi.python.org/pypi/pathlib2)

**Comment by wresch** [comment]
Thanks @kalefranz . So this is targeted for a 4.4 release (if i understand the pull request discussion ocrrectly)?
