### ISSUE TITLE
conda uncontrollably spawning python processes when creating/removing envs

### ISSUE THREAD

**Issue by cwreid18** [conda/conda#4782]
On Windows 7, with Anaconda installed for all users in C:\Anaconda3. No problem creating and removing envs with admin rights. However, when running as user without admin rights, I get the following problem when creating environments: packages are downloaded ok, but then it hangs (usually at the linking or unlinking packages step) and I can see pythonw.exe processes being launched in task manager at a rate of several per second. Only way to stop this is to shut down the machine. The problem is intermittent and seems to occur more frequently when creating envs with all the anaconda packages (e.g. conda create -n test anaconda=4.1.1) rather than environments that only contain a few packages. Happens occasionally when trying to remove envs. I have tried reinstalling with multiple versions of anaconda (inc. the latest, 4.3.0) but the problem keeps occurring.

**Comment by kalefranz** [comment]
What version of conda?  Can you provide `conda info`?  If you're not on 4.3.13, go ahead an upgrade and see if the problem is still there.

**Comment by cwreid18** [comment]
4.3.8 was the most recent version I used previously. The admin isn't around but I was able to update conda to 4.3.13 on my user. I then tried `conda create -n test anaconda=4.1.1` and got the error described above.

**Comment by cwreid18** [comment]
![conda_info](https://cloud.githubusercontent.com/assets/26145704/23520477/160068ee-ff73-11e6-86c4-693815543296.png)

**Comment by wulmer** [comment]
I am having the same issue with conda 4.3.13. This problem currently blocks our Jenkins builds on Windows... :-(
It seems that if there is a problem while creating an environment, conda retries again and again. (Each of the failed processes spawns a new subprocess which also fails and which also starts a new subprocess and so on...)

I was able to get the command line of the spawned Python processes. It always reads the same:

    "C:\Program Files\Anaconda3\pythonw.exe" "-c" "import menuinst; menuinst.install('c:\\Jenkins\\WORKSP~1\\XQ_MUL~1\\FED2B2~1\\virtual-env2\\Menu\\spyder_shortcut.json', False, 'c:\\Jenkins\\WORKSP~1\\XQ_MUL~1\\FED2B2~1\\virtual-env2')"

As I don't run with admin rights (and AFAIK creating start menu shortcuts with conda shows a UAC prompt) I assume that my background Jenkins process tries to get a UAC approval but can't as it is running in the background. So somehow conda tries it again over and over...

I will try to change my env setup commands to skip menu shortcut creation... hope this avoids the issue...

My conda install is:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.5
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3

**Comment by kalefranz** [comment]
To my knowledge there is no "retry" in conda (there is in conda-build).  And it's possible that menuinst is the problem.  An easy test would just be `conda uninstall menuinst`, which shouldn't cripple conda at all.

**Comment by asishm** [comment]
@wulmer Could you tell how you were able to get the command line of the spawned Python processes?

**Comment by wulmer** [comment]
@asishm I use ProcessHacker (http://processhacker.sf.net) which not only shows process dependencies but also much more interesting and helpful information (for debugging), e.g. it can show command lines, working directories or environment variables of processes. Has saved me lots of time...

**Comment by asishm** [comment]
Thanks,

I verified and I have the same issue. The `menuinst` keeps spawning multiple child processes. Since I don't have admin access, I can't run `conda uninstall menuinst` until I can get the sysadmin process it, which takes a very long time due to company procedures.

I'm trying to create conda envs with the default anaconda packages  with `conda create -n full_env python=3.5 anaconda` and since `menuinst` is a default package, it shows up. Is there any way to exclude that?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/menuinst#42
