### ISSUE TITLE
Conda Update Issue:  conda update CondaHTTPError: HTTP None

### ISSUE THREAD

**Issue by josephcamire** [conda/conda#4793]
Midway through running Conda Update --all, the update stalled. Multiple packages had been updated. Now, when I run "conda update --all" or "conda update conda", I get this response:

```
(C:\Users\*****\AppData\Local\Continuum\Anaconda3) C:\Users\*****>conda update conda
Fetching package metadata ...

CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
```
I've repeated "conda update conda" over multiple days, with no change in results. I can see there is no HTTP, however "conda info --a" shows channel URLs

```
(C:\Users\*****\AppData\Local\Continuum\Anaconda3) C:\Users\*****>conda info -a
Current conda install:

           platform : win-64
      conda version : 4.3.13
   conda is private : False
  conda-env version : 4.3.13
conda-build version : 2.1.5
     python version : 3.5.3.final.0
   requests version : 2.13.0
   root environment : C:\Users\*****\AppData\Local\Continuum\Anaconda3  (writable)
default environment : C:\Users\*****\AppData\Local\Continuum\Anaconda3
   envs directories : C:\Users\*****\AppData\Local\Continuum\Anaconda3\envs
                      C:\Users\*****\AppData\Local\conda\conda\envs
                      C:\Users\*****\.conda\envs
      package cache : C:\Users\*****\AppData\Local\Continuum\Anaconda3\pkgs
                      C:\Users\*****\AppData\Local\conda\conda\pkgs
       channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                      https://conda.anaconda.org/anaconda-fusion/noarch
                      https://repo.continuum.io/pkgs/free/win-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/win-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/win-64
                      https://repo.continuum.io/pkgs/pro/noarch
                      https://repo.continuum.io/pkgs/msys2/win-64
                      https://repo.continuum.io/pkgs/msys2/noarch
        config file : C:\Users\*****\.condarc
       offline mode : False
         user-agent : conda/4.3.13 requests/2.13.0 CPython/3.5.3 Windows/7 Windows/6.1.7601
```

How do I get "conda update" to call a correct HTTP address?

**Comment by cobrin** [comment]
Hi,
I hit the same problem, on CentOS 7. It seems to be related to curl issues especially when behind a company proxy (ours was ZScaler), as the certificate from the the remote site is signed by your companies certificate which is not known by curl. I resolved this issue, by explicitly telling curl to use the correct certificate, so in my case that was

`export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`

as I'd already imported the ZScaler certificate with `update-ca-trust`

should be the default anyway, but it worked and "`conda update conda`" worked afterwards

**Comment by SpinoPi** [comment]
@cobrin Hi cobrin, I also hit the same problem. Our proxy service is provided from Cisco. Do you know how to solve this problem in a Window7 system? Thank you very very much.

**Comment by kalefranz** [comment]
You need to get your certificate authority bundle in order.  It's been corrupted somehow.  Unfortunately, there's no single path by which this can happen, and it's pretty hard to diagnose in an issue like this.

You're on windows.  This could potentially help, but by doing this you are disabling part of TLS security

    SET CONDA_SSL_VERIFY=false
    conda update conda requests pyopenssl cryptography
    SET CONDA_SSL_VERIFY=

**Comment by ashukrishna100** [comment]
I recently got this issue resolved. Use this command to see proxy_servers
`conda config --show`

If any proxy server is present in the configuration. Kindly use
`conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
Enter
`conda clean --source-cache`
Now your http error is gone.
Give it a try and let me know in case of any difficulty.

**Comment by noahwalugembe** [comment]
> I recently got this issue resolved. Use this command to see proxy_servers
> `conda config --show`
> 
> If any proxy server is present in the configuration. Kindly use
> `conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
> Enter
> `conda clean --source-cache`
> Now your http error is gone.
> Give it a try and let me know in case of any difficulty.

It is not working for me

**Comment by bisheng602** [comment]
My system is also win10, when I change the system setting about "controls the language used to display text in programs that do not support Unicode " to UTF-8 , this problem occurs and what's worse ,some error happen when I started anaconda prompt and can not activate my python environments.

But it's easy to solve this problem , just change the  system setting back , then conda prompt become normal and you can update your conda

**Comment by bisheng602** [comment]
My system is also win10, when I change the system setting about "controls the language used to display text in programs that do not support Unicode " to UTF-8 , this problem occurs and what's worse ,some error happen when I started anaconda prompt and can not activate my python environments.

But it's easy to solve this problem , just change the  system setting back , then conda prompt become normal and you can update your conda
