### ISSUE TITLE
Win10 64b, error when trying to create tf environment: conda env create -f environment_win.yml

### ISSUE THREAD

**Issue by neovaldivia** [conda/conda#4812]
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Users\neova\Anaconda3  (writable)
    default environment : C:\Users\neova\Anaconda3
       envs directories : C:\Users\neova\Anaconda3\envs
          package cache : C:\Users\neova\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\neova\Anaconda3\Scripts\conda-env-script.py create -f environment_win.yml`

    Traceback (most recent call last):
      File "C:\Users\neova\Anaconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\neova\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 82, in execute
        directory=os.getcwd())
      File "C:\Users\neova\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: environment_win.yml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment]
Did you try replacing `-f environment_win.yml` with `-f /absolute/path/to/environment_win.yml` ? If that doesn't work, please share the contents of `environment_win.yml`

**Comment by neovaldivia** [comment]
hi, yes I tried that and worked...thanks!
