### ISSUE TITLE
Conda says it will update but it actually downgrades matplotlib

### ISSUE THREAD

**Issue by Gabriel-p** [conda/conda#4817]
Just installed `astropy` in a Python 3 environment. Conda says it has to "update" `matplotlib`, but the version numbers show it is actually downgrading due to also downgrading `numpy`.

```
$ conda install astropy   
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/gabriel/anaconda3/envs/cat-match:

The following NEW packages will be INSTALLED:

    astropy:    1.3-np111py36_0  

The following packages will be UPDATED:

    matplotlib: 2.0.0-np112py36_0 --> 2.0.0-np111py36_0

The following packages will be DOWNGRADED due to dependency conflicts:

    numpy:      1.12.0-py36_0     --> 1.11.3-py36_0   
```

**Comment by nehaljwani** [comment]
AFAIK, conda compares the version numbers and then the build numbers. It doesn't care what the entire build string is, as is evident from: https://github.com/conda/conda/blob/4.3.14/conda/plan.py#L152-L246

**Comment by kalefranz** [comment]
I guess here, you should read UPDATED as meaning, "updating the package in the prefix so it's compatible with the rest of the environment."  It's subtle.  But I think trying to clarify it further could end up causing even more confusion.

**Comment by Gabriel-p** [comment]
@kalefranz but right below that the package `numpy` is correctly marked as being *downgraded*. Why this difference?

**Comment by kalefranz** [comment]
What would you suggest as a better word in this situation?

**Comment by Gabriel-p** [comment]
I would suggest *downgrade*, since that is what is actually happening. Is it not?

**Comment by kalefranz** [comment]
No, it's not.  The matplotlib package is exactly the same version: 2.0.0.  Conda just switched to the matplotlib 2.0.0 package that's compatible with numpy 1.11 instead of numpy 1.12.  It's the same version of matplotlib code, just compiled against a different numpy.  It's most definitely NOT a downgrade.

**Comment by Gabriel-p** [comment]
Got it, thank you.
