### ISSUE TITLE
Windows 10 Bash Ubuntu conda install perl failure

### ISSUE THREAD

**Issue by greggjm** [conda/conda#4827]
I'm trying to work out a few errors installing packages for sequence alignment software and a persistent issue I've been experiencing is perl failing to extract whenever it installs. I'm using the [linux bash shell](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) on windows 10, hopefully others with similar problems find this thread too.

I've found [this useful thread](https://github.com/Microsoft/BashOnWindows/issues/186#issuecomment-240591395) discussing some issues with perl on bash ubuntu but changing the Config.pm folder didn't solve the problem.

Here is the actual error I've been experiencing:

`# conda install -c bioconda perl-lwp-protocol-https
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /root/unix/bin/miniconda3:

The following NEW packages will be INSTALLED:

    perl:                    5.22.0.1-0         conda-forge
    perl-encode-locale:      1.05-pl5.22.0_4    bioconda
    perl-lwp-protocol-https: 6.06-2             bioconda
    perl-lwp-simple:         6.15-3             bioconda
    perl-threaded:           5.22.0-pl5.22.0_12 bioconda

Proceed ([y]/n)?
Extracting packages ...
An unexpected error has occurred.                                                                              |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /root/unix/bin/miniconda3  (writable)
    default environment : /root/unix/bin/miniconda3
       envs directories : /root/unix/bin/miniconda3/envs
          package cache : /root/unix/bin/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False

`$ /root/unix/bin/miniconda3/bin/conda install -c bioconda perl-lwp-protocol-https`

    Traceback (most recent call last):
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/root/unix/bin/miniconda3/lib/python3.6/site-packages/conda/install.py", line 810, in extract
        t.extractall(path=temp_path)
      File "/root/unix/bin/miniconda3/lib/python3.6/tarfile.py", line 2003, in extractall
        numeric_owner=numeric_owner)
      File "/root/unix/bin/miniconda3/lib/python3.6/tarfile.py", line 2045, in extract
        numeric_owner=numeric_owner)
      File "/root/unix/bin/miniconda3/lib/python3.6/tarfile.py", line 2115, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/root/unix/bin/miniconda3/lib/python3.6/tarfile.py", line 2156, in makefile
        with bltn_open(targetpath, "wb") as target:
    OSError: [Errno 22] Invalid argument: '/root/unix/bin/miniconda3/pkgs/perl-5.22.0.1-0.tmp/man/man3/Encode::Config.3'`

It begins to extract perl, but fails before actually making any progress. If you've experienced this error or know how to work around it to install conda packages dependent on this package please let me know.

I need to use packages that would be installed with this such as perl-threaded for other programs like hisat2 and tophat.

Advice anyone?

**Comment by nehaljwani** [comment]
Related: https://github.com/Microsoft/BashOnWindows/issues/1514

**Comment by greggjm** [comment]
The problem was caused because I extracted miniconda to a symbolically linked folder (/mnt/c/User/Desktop/) which was outside of the linux subsystem in the appdata folder. I uninstalled miniconda and reinstalled it to my home directory instead of the symbolically linked folder. That fixed the problem.
