### ISSUE TITLE
ImportError: No module named 'conda.cli.pip_warning'

### ISSUE THREAD

**Issue by hate5six** [conda/conda#4829]
I was having problems with conda earlier so I proceeded with a fresh install after wiping the /anaconda3 directory. The reinstall process had no issues but now when I try to create or activate an environment I get:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/conda", line 7, in <module>
    from conda.cli.pip_warning import main
ImportError: No module named 'conda.cli.pip_warning'
```
Any ideas?

**Comment by kalefranz** [comment]
Did you use pip to install or update conda ever?

**Comment by hate5six** [comment]
I used pip to install packages some packages here and there but not to update conda.

**Comment by kalefranz** [comment]
The contents of `/home/ubuntu/anaconda3/bin/conda` should point to `conda.cli.main()`.  I'm pretty sure the only way to get `conda.cli.pip_warning` is to `pip install conda`.  If that's not the case, and you can give me exact steps to reproduce, please let me know and I'll get it fixed.
