### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:   - opencv 2.4.11* -> numpy 1.9* -> python 2.6* -> openssl 1.0.1*   - python 3.6*

### ISSUE THREAD

**Issue by connect2robiul** [conda/conda#4832]
conda install -c menpo opencv=2.4.11

Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv 2.4.11* -> numpy 1.9* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

in ipython console 
<img width="382" alt="screenshot 2017-03-09 13 45 38" src="https://cloud.githubusercontent.com/assets/1263093/23740661/cf7c2ec4-04ce-11e7-9cb3-3cb0d3732cd1.png">

**Comment by azzurolilc** [comment]
I was just trying to get opencv working and I was having the exact same issue, 
resolved using python3.5 and opencv3 instead
==>
`conda install python=3.5`
then
`conda install -c menpo opencv3`

**Comment by vivekpatani** [comment]
Hi guys, I've posted the same answer in another issue that references this problem. @azzurolilc @irobiul. Consider closing down the issue if you think https://github.com/conda/conda/issues/2448 and your issues are the same.

Thanks!

**Comment by albertaleksieiev** [comment]
@azzurolilc Thank you! It's work great!

**Comment by Sidney2408** [comment]
![screenshot 27](https://user-images.githubusercontent.com/19767514/34327936-e1b2af14-e90c-11e7-9c91-64ef73404260.png)

Other files that are missing are:
THS.DLL
TH.DLL
SHM.DLL
python35.dll (It can be found in \Anaconda3\envs\tensorflow\python35.dll)

If the issue lies in setting the PATH variable please provide examples.

**Comment by kesjien** [comment]
conda install -c menpo opencv3 
also works with python 3.6

**Comment by ionox0** [comment]
does `opencv 2.4.11* -> numpy 1.9* -> python 2.6* -> openssl 1.0.1*` mean `opencv` requires a different version of`numpy` or `numpy` requires a different version of `opencv`?
