### ISSUE TITLE
PackageNotFoundError: Package not found: Conda could not find '

### ISSUE THREAD

**Issue by pjacob2** [conda/conda#4836]
Having updated my `conda` to version 4.3.14 I get a `PackageNotFoundError` stating that `Conda could not find '` whenever I am trying to install a new package. If I downgrade to version 4.3.13 using `conda install conda=4.3.13` the error disappears until eventually some package being installed causes conda to revert back to version 4.3.14. What is this being caused by?

**Comment by hack-r** [comment]
I have this problem to. Seems to happen no matter what package I'm trying to install. I don't want to downgrade...

**Comment by pjacob2** [comment]
This issues appears to still persist for me. Does anybody have any thoughts on this?

**Comment by goanpeca** [comment]
@pjacob2 and @hack-r could you please update to the latest version of conda?

`conda update conda`
