### ISSUE TITLE
conda install with --use-local --override-channels ignore --yes

### ISSUE THREAD

**Issue by MatthieuDartiailh** [conda/conda#4837]
Observed here https://travis-ci.org/Ecpy/ecpy_hqc_legacy/jobs/209356357 (and some other build too). Setting the always_yes option using conda config however works.

Conda is updated using conda update conda before running this command.

**Comment by kalefranz** [comment]
You're running on an old version of conda.
https://travis-ci.org/Ecpy/ecpy_hqc_legacy/jobs/209356357#L123

I think we've even removed those links to Miniconda without a python version number.
