### ISSUE TITLE
Permission denied when installing packages to environment as non-root user

### ISSUE THREAD

**Issue by wl2776** [conda/conda#4838]
$ conda install -v  -n MBA scikit-image

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /opt/miniconda2  (read only)
    default environment : /home/eremeev/.conda/envs/MBA
       envs directories : /opt/miniconda2/envs
                          /home/eremeev/.conda/envs
          package cache : /opt/miniconda2/pkgs
                          /home/eremeev/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/eremeev/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.13 Linux/4.4.0-66-generic debian/stretch/sid glibc/2.23
                UID:GID : 1002:1002

`$ /home/eremeev/.conda/envs/MBA/bin/conda install -v -n MBA scikit-image`

    Traceback (most recent call last):
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 800, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 295, in execute
        rollback_excs,
    CondaMultiError: post-link script failed for package defaults::dbus-1.10.10-0
    running your command again with `-v` will provide additional information
    location of failed script: /home/eremeev/.conda/envs/MBA/bin/.dbus-post-link.sh
    ==> script messages <==
    <None>

**Comment by wl2776** [comment]
Have found that some files in `/opt/miniconda2/bin` are not readable by users, for example .dbus-post-link.sh

Changed their attributes - the installation went fine.

**Comment by kadrlica** [comment]
I've run into similar issues. I'm linking this to #1329 as requested by @kalefranz when he closed that issue.

**Comment by DaanVanHauwermeiren** [comment]
Thanks @wl2776 ! changing all the permissions solved my issue in #3661

**Comment by kalefranz** [comment]
@DaanVanHauwermeiren if you remember what the incorrect permissions were, and for which files, please share.  It seems like it could be a packaging problem, but if conda did something wrong, it's probably an easy fix.

**Comment by DaanVanHauwermeiren** [comment]
@kalefranz sorry I don't remember exactly. If I'm not mistaken, before it was: the files and folders are owned by root, other users have read access. I changed it with following commands:

```
chmod a+r /path/to/conda/pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
chmod a+w /path/to/conda/conda-meta/ -R
chmod a+r /path/to/conda/pkgs/ -R
chmod a+r /path/to/conda/bin -R
```
see #3661
