### ISSUE TITLE
\urllib3\connection.py", line 142, in _new_conn    connection error

### ISSUE THREAD

**Issue by osbe45** [conda/conda#4841]
At this moment I can't install anything through pip.  I am getting connections errors.  I have tried to upgrade the pip, to upgrade the urllib3 and install the html5lib but has been unsuccessful.

By the way, I am new to python.  Please, I need help

Here an example when trying to install html5lib using the conda  (I am using Anaconda3 interpreter 3.5.2).   After that an example when tryin to upgrade urllib3

conda install -c anaconda html5lib=0.999

Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://conda.anaconda.org/anaconda/noarch/
Could not connect to https://conda.anaconda.org/anaconda/win-64/
Could not connect to https://conda.anaconda.org/anaconda/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\...\AppData\Local\Continuum\Anaconda3
(writable)
    default environment : C:\Users\...\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\...\AppData\Local\Continuum\Anaconda3\e
nvs
          package cache : C:\Users\...\AppData\Local\Continuum\Anaconda3\p
kgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\...\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py
install -c anaconda html5lib=0.999`

    Traceback (most recent call last):
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\util\connection.py", line 75, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\socket.py",
 line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 11004] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\...\AppData\Local\Continuum\Anaconda3\lib\site-packag
es\requests\packages\urllib3\connection.py", line 254, in connect
......

#### Trying to upgrade urllib3

C:\Users\...>pip install --upgrade urllib3
Collecting urllib3
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x00000000053A52E8>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)': /simple/urllib3/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connec
tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x00000000053A5C50>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)': /simple/urllib3/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connec
tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x00000000053A5048>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)': /simple/urllib3/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connec
tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x00000000053A5E10>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)': /simple/urllib3/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connec
tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x00000000053A5A90>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)': /simple/urllib3/
  Could not find a version that satisfies the requirement urllib3 (from versions
: )
No matching distribution found for urllib3

**Comment by kalefranz** [comment]
Neither pip nor conda can connect to the internet.  You have a networking issue on your system.  Look deeper into your networking stack.  Or get help from your sysadmin.
