### ISSUE TITLE
--no-builds broken

### ISSUE THREAD

**Issue by alchenist** [conda/conda#4844]
The `--no-builds` flag in the CLI no longer removes build specifications from exported .ymls; looks like https://github.com/conda/conda/commit/d7d77b0cc43cf5b0b10eb1a4b54103699408d91f#diff-989997a4af9fec0d3b58db8232c62182R53 added the build specification back into conda package lines.

**Comment by drkjam** [comment]
+1

**Comment by StudioEtrange** [comment]
Yes. This is really a problem.
+10

**Comment by bkreider** [comment]
Is this still a problem?

**Comment by mhearne-usgs** [comment]
@bkreider 
It is for me...

conda 4.3.29
OSX 10.12.6 (16G1114)
Python 3.5.4

I just ran conda env export --no-builds and got a file with dependency lines that look like this:

- gdal=2.1.4=py35_1

I'm just learning about build numbers but I assume that's what py35_1 is...

**Comment by kalefranz** [comment]
`conda env export --no-builds` is fixed in recent versions of conda 4.3.

    conda update conda
