### ISSUE TITLE
conda search --outdated broken

### ISSUE THREAD

**Issue by nicolavianello** [conda/conda#4845]
Hi
for some reason conda search --oudated is broken in my OSX box. 
This is the trace back

Current conda install:

               platform : osx-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.5
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/vianello/anaconda2  (writable)
    default environment : /Users/vianello/anaconda2
       envs directories : /Users/vianello/anaconda2/envs
                          /Users/vianello/.conda/envs
          package cache : /Users/vianello/anaconda2/pkgs
                          /Users/vianello/.conda/pkgs
           channel URLs : https://conda.anaconda.org/astropy/osx-64
                          https://conda.anaconda.org/astropy/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/sunpy/osx-64
                          https://conda.anaconda.org/sunpy/noarch
            config file : /Users/vianello/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 502:20

`$ /Users/vianello/anaconda2/bin/conda search --outdated`

    Traceback (most recent call last):
      File "/Users/vianello/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/vianello/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/Users/vianello/anaconda2/lib/python2.7/site-packages/conda/cli/main_search.py", line 124, in execute
        execute_search(args, parser)
      File "/Users/vianello/anaconda2/lib/python2.7/site-packages/conda/cli/main_search.py", line 211, in execute_search
        assert len(vers_inst) == 1, name
    AssertionError: conda

Any idea?

**Comment by tyler-thetyrant** [comment]
I think this was fixed in the recent versions of conda. @kalefranz
