### ISSUE TITLE
conda install --yes flag ignored when --use-local set with conda-build 2.1.6

### ISSUE THREAD

**Issue by msarahan** [conda/conda#4848]
@Lnaden commented on [Fri Mar 10 2017](https://github.com/conda/conda-build/issues/1825)

Trying to execute `conda install --yes --use-local {package}` from a package built with `conda-build` ignores the `--yes` flag and waits for user input. This [has](https://travis-ci.org/choderalab/openmmtools/jobs/209789665#L951) put a [halt](https://travis-ci.org/choderalab/pymbar/jobs/209453492#L646) to trying to do automatic builds as they time out, I am only using the 2 links as examples.

I can replicate the problem on my local machine and on downgrading to `conda-build` 2.1.5 the problem goes away, even without re-building the package. 

---

@msarahan commented on [Fri Mar 10 2017](https://github.com/conda/conda-build/issues/1825#issuecomment-285718752)

Sorry, but it looks like a coincidence that conda-build 2.1.5 works but 2.1.6 breaks.  Your build is succeeding (https://travis-ci.org/choderalab/openmmtools/jobs/209789665#L919), but it is only the conda step after that that is broken.  I'm going to move this issue to the conda issue tracker.

Also, this is concerning: https://travis-ci.org/choderalab/openmmtools/jobs/209789665#L925

you should probably add a pin to whichever jpeg you actually want, so that conda does not arbitrarily choose something you don't want.

**Comment by Lnaden** [comment]
> Also, this is concerning 

Yes, that is something new that cropped up but I think unrelated to the issue as we see it in other packages without that problem.

**Comment by pavoljuhas** [comment]
I tracked this problem to the `conda-index` output in the local packages directory.  The index depends on the conda-build version, please see https://github.com/conda/conda-build/issues/1825#issuecomment-285741965.

**Comment by kalefranz** [comment]
Closing after reviewing discussion in https://github.com/conda/conda-build/issues/1825
