### ISSUE TITLE
error when installing graph create launcher

### ISSUE THREAD

**Issue by hollyyuhu** [conda/conda#4854]
I'm taking a coursera class and completely new to python. this is the error message i got when installing graph create launcher. what should i do?

===================
There was a problem updating the conda package.  Restart GraphLab Create Launcher.

Unable to update conda:
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
...SSL verification error: [Errno 2] No such file or directory
.SSL verification error: [Errno 2] No such file or directory
.SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
...
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - conda 4.0.8*

You can search for this package on anaconda.org with

    anaconda search -t conda conda 4.0.8*

  

Process completed with exit code -1

**Comment by kalefranz** [comment]
Please file an issue with GraphLab for help.  You are not using conda directly here.
