### ISSUE TITLE
The lauching of ipython under conda is much slower than the system's ipython.

### ISSUE THREAD

**Issue by wangg12** [conda/conda#4855]
I consistently found that conda's ipython is slower than the system's ipython, more or less. Sometimes it takes seconds to start, while the system's ipython starts almost instantly. I've tested on several ubuntu machines and mac. What may cause the ipython under conda so slow? Confusing...

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1653
