### ISSUE TITLE
Can't use matplotlibs basemap-module in ipython (only in standard python shell)

### ISSUE THREAD

**Issue by jvollme** [conda/conda#4857]
Hi,
I'm trying to use Basemap from the matplotlib_toolkit. I've installed it using: `conda install basemap`.

It seemed to be installed fine (inlcuding dependencies):
    
    The following NEW packages will be INSTALLED:
    
    backports:          1.0-py27_0
    backports_abc:      0.5-py27_0
    basemap:            1.0.7-np112py27_0
    cycler:             0.10.0-py27_0
    functools32:        3.2.3.2-py27_0    bioconda
    geos:               3.5.0-0
    matplotlib:         2.0.0-np112py27_2 conda-forge
    pyparsing:          2.1.4-py27_0
    python-dateutil:    2.6.0-py27_0      bioconda
    pytz:               2016.10-py27_0
    singledispatch:     3.4.0.3-py27_0
    six:                1.10.0-py27_0
    ssl_match_hostname: 3.4.0.2-py27_1
    subprocess32:       3.2.7-py27_0
    tornado:            4.4.2-py27_0
    
    The following packages will be UPDATED:
    
    icu:                56.1-4            conda-forge --> 58.1-1   conda-forge
    libgd:              2.2.4-0           conda-forge --> 2.2.4-1  conda-forge
    libpng:             1.6.27-0                      --> 1.6.28-0 conda-forge
    
    Proceed ([y]/n)? y

However when i try to import basemap within ipython, I get the following error:

    ----> 1 from mpl_toolkits.basemap import Basemap
    
    ImportError: No module named mpl_toolkits.basemap

When I try to do the same from within the standard python shell, however, It seems to work.

While I'm fine with using the module only in the standard python shell, something must be wrong here, mustn't it?

UPDATE:
When I then try to import pyplot (as per basemap tutorial) I get the following error:

    import matplotlib.pyplot as plt
    ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

**Comment by nehaljwani** [comment]
Try:
```bash
conda install -c nehaljwani libicu=56.1
python -c 'import matplotlib.pyplot as plt'
```

**Comment by jvollme** [comment]
Oh, nevermind. It was a different problem caused by a simple mistake on my part: I did not manually install ipython via conda so my previosuly installed ipython was used, which reverted to a different python installation than my conda environment. 
I missed that, because I thought i python was installed together with python when creating a new conda-environment (I thought I had read that someweher, and anyway thought that it would use my current environment python otherwise). But I was wrong.
simply installing ipython via conda solved the problem.
Thanks, though.
