### ISSUE TITLE
Error in Conda error message for conda not-a-valid-command

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#4859]
Conda  version: `4.3.14`

What actually happens:
```
(root) [root@4cd1258efdd1 ~]# conda lsit
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/conda/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```

What is expected:
```
(root) [root@4cd1258efdd1 ~]# conda lsit
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: 'lsit' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```

Question: Why is the `and` condition at https://github.com/conda/conda/blob/4.3.14/conda/cli/main.py#L113 necessary?

**Comment by AchilesGomes** [comment]
Hello, the command: conda **list**

Ready more in: https://conda.io/docs/using/pkgs.html#list-all-packages

**Comment by nehaljwani** [comment]
@AchilesGomes That is not what this GH issue is about. The main issue is that It should say:
`invalid choice: 'lsit`
instead of:
`invalid choice: '/conda/bin/conda'`

**Comment by AchilesGomes** [comment]
I take that =D

**Comment by kalefranz** [comment]
As of latest 4.4

```
$ conda lsit

CommandNotFoundError: No command 'conda lsit'.
Did you mean 'conda list'?
```

**Comment by massich** [comment]
I see something similar (in `conda 4.3.34`):

```sh
$ conda install nose
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/sik/miniconda3/envs/mne:
#
nose                      1.3.7            py36hcdf7029_2  
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/sik/miniconda3/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```

**Comment by thebeancounter** [comment]
having the same issue 
I found the solution should [be](https://github.com/ContinuumIO/anaconda-issues/issues/6171) 

$conda update anaconda-navigator
$ conda update navigator-updater

but I am getting the same error when trying to use the solution...

**Comment by XEasonChan** [comment]
I met a similar question, no matter what Command I gave it just come up with this error:
```
xeason@xeUbuntu:~$ source activate densepose/
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/xeason/anaconda2/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```

and it could even occur after I uninstall and reinstall my anaconda. How can I solve this?

**Comment by danmoser** [comment]
Same error here... `conda 4.3.16`.

> usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/path/to/miniconda2x64/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')

However, `conda list` works! The output is here:

> packages in environment at /path/to/miniconda2x64:
asn1crypto                0.24.0                   py27_0    https://repo.anaconda.com/pkgs/main
ca-certificates           2019.1.23                     0    https://repo.anaconda.com/pkgs/main
certifi                   2019.3.9                 py27_0    https://repo.anaconda.com/pkgs/main
cffi                      1.12.2           py27h2e261b9_1    https://repo.anaconda.com/pkgs/main
chardet                   3.0.4                    py27_1    https://repo.anaconda.com/pkgs/main
conda                     4.6.14                   py27_0    https://repo.anaconda.com/pkgs/main
cryptography              2.6.1            py27h1ba5d50_0    https://repo.anaconda.com/pkgs/main
enum34                    1.1.6                    py27_1    https://repo.anaconda.com/pkgs/main
futures                   3.2.0                    py27_0    https://repo.anaconda.com/pkgs/main
idna                      2.8                      py27_0    https://repo.anaconda.com/pkgs/main
ipaddress                 1.0.22                   py27_0    https://repo.anaconda.com/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    https://repo.anaconda.com/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://repo.anaconda.com/pkgs/main
libgcc-ng                 8.2.0                hdf63c60_1    https://repo.anaconda.com/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    https://repo.anaconda.com/pkgs/main
ncurses                   6.1                  he6710b0_1    https://repo.anaconda.com/pkgs/main
openssl                   1.1.1b               h7b6447c_1    https://repo.anaconda.com/pkgs/main
pip                       19.0.3                   py27_0    https://repo.anaconda.com/pkgs/main
pycosat                   0.6.3            py27h14c3975_0    https://repo.anaconda.com/pkgs/main
pycparser                 2.19                     py27_0    https://repo.anaconda.com/pkgs/main
pyopenssl                 19.0.0                   py27_0    https://repo.anaconda.com/pkgs/main
pysocks                   1.6.8                    py27_0    https://repo.anaconda.com/pkgs/main
python                    2.7.16               h9bab390_0    https://repo.anaconda.com/pkgs/main
readline                  7.0                  h7b6447c_5    https://repo.anaconda.com/pkgs/main
requests                  2.21.0                   py27_0    https://repo.anaconda.com/pkgs/main
ruamel_yaml               0.15.46          py27h14c3975_0    https://repo.anaconda.com/pkgs/main
setuptools                41.0.0                   py27_0    https://repo.anaconda.com/pkgs/main
six                       1.12.0                   py27_0    https://repo.anaconda.com/pkgs/main
sqlite                    3.27.2               h7b6447c_0    https://repo.anaconda.com/pkgs/main
tk                        8.6.8                hbc83047_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.24.1                   py27_0    https://repo.anaconda.com/pkgs/main
wheel                     0.33.1                   py27_0    https://repo.anaconda.com/pkgs/main
yaml                      0.1.7                had09818_2    https://repo.anaconda.com/pkgs/main
zlib                      1.2.11               h7b6447c_3    https://repo.anaconda.com/pkgs/main

**Comment by xiaohk** [comment]
Same error here

**Comment by killalarm** [comment]
Same error here
