### ISSUE TITLE
Error in PackageNotFoundError

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#4860]
Commit https://github.com/conda/conda/commit/bb3e54d8a8be3a51de0601206faf20d82b3f0dbb broke PackageNotFoundError for v4.3.14

Expected:

```bash
(root) [root@4cd1258efdd1 ~]$ conda install perl
Fetching package metadata .........


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - perl

Close matches found; did you mean one of these?

    perl: petl

You can search for packages on anaconda.org with

    anaconda search -t conda perl

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```
What actually happens:
```bash
(root) [root@4cd1258efdd1 ~]$ conda update conda -y
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /conda:

The following packages will be UPDATED:

    conda: 4.3.11-py27_0 --> 4.3.14-py27_0

conda-4.3.14-p 100% |###################################################################################################################################################################| Time: 0:00:00   6.61 MB/s
(root) [root@4cd1258efdd1 ~]$ conda install perl
Fetching package metadata .........


PackageNotFoundError: Package not found: Conda could not find '

```

**Comment by dsdaveh** [comment]
I ran into this same error when trying to create an environment with:
https://github.com/kjam/data-wrangling-video/blob/master/py3_requirements.txt

**Comment by roverallover** [comment]
I'm having the same issue trying to install gsshapy from a local repo. I am also using conda version 4.3.14...
I installed the gsshapy package once from conda-forge, downloaded all the dependency packages listed and put them in a local directory ($HOME/conda_bz2/linux-64) ran conda index on the folder and looked at the repodata.json file ... here's what is in it:
"gsshapy-2.1.1-py27_2.tar.bz2": {
      "build": "py27_2",
      "build_number": 2,
      "depends": [
        "mapkit",
        "psycopg2",
        "pygrib",
        "python 2.7*",
        "rapidpy",
        "timezonefinder"
      ],
      "license": "BSD-3-Clause",
      "license_family": "BSD",
      "md5": "a8bde98757f4baf33ffe049ae8c91d17",
      "name": "gsshapy",
      "sig": null,
      "size": 155917,
      "subdir": "linux-64",
      "version": "2.1.1"
    },
I changed my .condarc file to only have the local channel, activated my environment (which was created from the local repo just fine) to install the gsshapy in, and ran:
$ conda install gsshapy
and this what I got (too):
Fetching package metadata .....
Solving package specifications:

PackageNotFoundError: Package not found: Conda could not find '

I also tried:
conda install gsshapy --offline --override-channels --channel file:///home/gssha-user/conda_bz2/linux-64
and got the same results....
I have the package "nose" in the same repo and that installed just fine... Does anyone know what's up?
Thanks!

**Comment by clipo** [comment]
I am also getting this error (I just reinstalled from scratch the latest anaconda using the command line install (Mac os X). I get this error for any package...

$ conda install pyparty
Fetching package metadata .........
PackageNotFoundError: Package not found: Conda could not find '

platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4

**Comment by ShadSBCB** [comment]
Dear all,

Has this issue been solved?

I have just recently reinstalled Anaconda and am getting the same error as above:

PackageNotFoundError: Package not found: Conda could not find '

I get the error when trying to install anything (though conda update --all works).

Please find some details below and let me know if you need more.

Thank you!

Some details:

Current conda install:

platform : linux-64
conda version : 4.3.14
conda is private : False
conda-env version : 4.3.14
conda-build version : not installed
python version : 2.7.13.final.0
requests version : 2.12.4
root environment : /biggin/b15/shil4362/scripts/anaconda2  (writable)
default environment : /biggin/b15/shil4362/scripts/anaconda2
envs directories : /biggin/b15/shil4362/scripts/anaconda2/envs
                            /biggin/b15/shil4362/.conda/envs
package cache : /biggin/b15/shil4362/scripts/anaconda2/pkgs
                           /biggin/b15/shil4362/.conda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
config file : None
offline mode : False
user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Linux/3.13.0-113-generic debian/jessie/sid glibc/2.19
UID:GID : 13074:171

**Comment by goanpeca** [comment]
We are working on it!

**Comment by ShadSBCB** [comment]
@goanpeca Thank you for the reply and thank you for the support!

**Comment by bounlu** [comment]
I get the same error:
```

csioan:Desktop omeran$ conda install sra-tools
Fetching package metadata .........


PackageNotFoundError: Package not found: Conda could not find '


csioan:Desktop omeran$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.0.2
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /Users/omeran/anaconda2  (writable)
    default environment : /Users/omeran/anaconda2
       envs directories : /Users/omeran/anaconda2/envs
                          /Users/omeran/.conda/envs
          package cache : /Users/omeran/anaconda2/pkgs
                          /Users/omeran/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20
```

**Comment by nehaljwani** [comment]
@bounlu Try:

`conda install -c bioconda sra-tools`

**Comment by bounlu** [comment]
@nehaljwani 
it works for sra-tools but does not work for `meme` for example:

`conda install -c bioconda meme`

**Comment by ShadSBCB** [comment]
Dear all,

A quick update.

I was trying to install PyMOL via conda using

`conda install -c psi4 pymol=1.7.5`

This was giving me an error. I found a different channel (samoturk), and that installation worked. I am now not sure whether this is an issue with specific channels or not.

I also ran

`conda config --add channels conda-forge`

prior to installing the necessary supplementary packages.

**Comment by ferintphilipose** [comment]
was trying to install tensorflow with 
conda install -c https://conda.anaconda.org/jjhelmus tensorflow
and got the following error:

PackageNotFoundError: Package not found: Conda could not find '

**Comment by ijstokes** [comment]
@ferintphilipose I think the best place to get tensorflow today is from the `conda-forge` channel:

```
conda install -c conda-forge tensorflow
```

It is available there for multiple platforms and python versions:

https://anaconda.org/conda-forge/tensorflow/files

**Comment by ferintphilipose** [comment]
@ijstokes Thanks , but when I tried to run the suggested command, I received the following error.
""UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tensorflow -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.""

Would you be able to help me out with this if possible?

**Comment by goanpeca** [comment]
@ferintphilipose it seems that there are no packages available for win64 and python 3.6

https://anaconda.org/conda-forge/tensorflow/files?sort=basename&sort_order=desc

<img width="986" alt="screen shot 2017-03-24 at 10 38 43 pm" src="https://cloud.githubusercontent.com/assets/3627835/24319198/add39e90-10e2-11e7-8a22-fe4d09e08a34.png">

**Comment by ferintphilipose** [comment]
@goanpeca Thanks for clarifying it. Would you be able to suggest me an alternative way to set up the tensorflow framework ?

**Comment by ijstokes** [comment]
@ferintphilipose you should create a conda environment for tensorflow.  I would suggest doing the following:

Download the `anaconda_core.txt` file from this gist:

https://gist.github.com/ijstokes/d258375ca6ba10782aebd3ecc32a4cb6

Then from the command line (using the Anaconda Command Prompt in Windows) do:

```
conda create -n tf35 -c conda-forge python=3.5
activate tf35                               # for non-Windows users this would be "source activate tf35"
conda install -c conda-forge --file anaconda_core.txt
conda install -c conda-forge tensorflow
```

I don't have a Windows system to test on, but the basic sequence there works for me on a Mac.  Should get you Tensorflow 1.0 for Windows with Python 3.5.  Let us know if it doesn't

**Comment by jabalv** [comment]
Fail with environment creation: conda create -name environment001, same error:
PackageNotFoundError: Package not found: Conda could not find '

**Comment by goanpeca** [comment]
This is fixed and will be available shortly with the new conda version

**Comment by edwardlsanders** [comment]
I am having the same issue for conda 4.3.15

PackageNotFoundError: Package not found: Conda could not find '

**Comment by nehaljwani** [comment]
@edwardlsanders The [release](https://github.com/conda/conda/releases/tag/4.3.15) 4.3.15 was made before the [fix](https://github.com/conda/conda/pull/4935).

**Comment by TEMadsen** [comment]
I'm not sure if this is the same issue you're having, but I had success with this route to install tensorflow:

conda create -n tensorflow -y
activate tensorflow
conda install python=3.5 -y
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

That last line was from https://www.tensorflow.org/install/install_windows 
So of course, edit if you're on a different OS.

Hope that helps,
T

**Comment by nehaljwani** [comment]
This issue has been resolved in the release [v4.3.16](https://github.com/conda/conda/releases/tag/4.3.16) by https://github.com/conda/conda/pull/4935

**Comment by cbeddow** [comment]
Problem I'm having:

* I updated to v4.3.16
* Trying to do `conda create --name streets osmnx`
* Package not found
* `conda install -c conda-forge osmnx
* says it v4.3.16 will be superceded by v4.2.13-py27_0
* If I do this, then it goes back to v4.2.13 and the package is not found again, like this issue reports

Vicious circle?

**Comment by mingwandroid** [comment]
> Vicious circle?

A side-effect of a cautious update policy around `conda`. You can work around this by preventing `conda` from updating itself. Please read more here: https://conda.io/docs/config.html?highlight=auto_update_conda#update-conda-automatically-auto-update-conda

**Comment by cbeddow** [comment]
@mingwandroid well, if I don't update it, then the old version can't find the package. I need the updated version so that it doesn't return a can't find package error with a blank for the name, but in order to use the package, it says I need to old version. Am I missing something still?

**Comment by mingwandroid** [comment]
Maybe my explanation wasn't clear enough. You need to update `conda` to `4.3.16`, then disable updating `conda` further then install your package from `conda-forge`.

**Comment by nilamnini** [comment]
Hi, please help me. I still got an error eventhough I already successfully install the package. Thank you.
=====================================
# All requested packages already installed.
# packages in environment at C:\Users\Acer-PC\Anaconda3:
#
scikit-learn              0.19.0              np113py36_0

(C:\Users\Acer-PC\Anaconda3) C:\>import sklearn
'import' is not recognized as an internal or external command,
operable program or batch file.

(C:\Users\Acer-PC\Anaconda3) C:\>conda create --name Machinelearning scikit learn
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:

  - scikit

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by ijstokes** [comment]
@nilamnini please post your question to the conda community mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/conda

Thanks!

**Comment by maaqib1** [comment]
hellow every one , i m trying to install imutils but is not found by conda 
my conda info is 
platform : osx-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/mohammadaaqib/miniconda3  (writable)
    default environment : /Users/mohammadaaqib/miniconda3/envs/nnseries
       envs directories : /Users/mohammadaaqib/miniconda3/envs
                          /Users/mohammadaaqib/.conda/envs
          package cache : /Users/mohammadaaqib/miniconda3/pkgs
                          /Users/mohammadaaqib/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mohammadaaqib/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Darwin/17.5.0 OSX/10.13.4    
                UID:GID : 501:20
