### ISSUE TITLE
Consider allowing additional package formats for conda packages

### ISSUE THREAD

**Issue by aburgm** [conda/conda#4861]
I did some research about using package formats other than `.tar.bz2` for conda packages. The upshot is there seems to be potential to improve the fetch+extract phase of installing conda packages by ~30% when using algorithms that yield a higher compression ratio and/or faster decompression than bzip2. Here is a notebook summarizing these findings:

https://github.com/aburgm/conda-compression-cmp/blob/master/Analysis.ipynb

My personal favorite is `.tar.xz` since the tooling around it as fairly good, it has been adopted in other open source projects such as the Linux kernel or GNOME for their source code tarballs, and is supported by Python since 3.3. Google's brotli algorithm also seems very competitive.

Happy to hear the community's ideas and thoughts about this. If there is consensus that this is a good idea then I think the first step would be to handle additional package formats in case conda encounters them in an index (`repodata.json`) file. I'd be happy to start contributing in that direction.

@kalefranz This is the promised follow-up from the discussion we had at AnacondaCON.

**Comment by mingwandroid** [comment]
Interesting work. Thank you for taking the time.

The decompression memory requirements are actually a concern for us as we'd like to be able to target embedded systems with very low amounts of RAM, but non-9 xz *may* still be ok in that scenario.

**Comment by kalefranz** [comment]
I thought the blogpost [here](http://gregoryszorc.com/blog/2017/03/07/better-compression-with-zstandard/) about compression algorithms was particularly well done.  (Except it left off some critical information for bzip2 -- argh.)

What I was personally particularly looking for there was decompression speed, of course coupled with compression ratio.  bzip2 got left out of many of the decompression speed charts.

And as @mingwandroid correctly points out, we also need an axis that shows memory usage as well. 

Thanks for starting the discussion @aburgm.  Looking forward to digging into your notebook later today.

**Comment by aburgm** [comment]
@mingwandroid Thanks for that insight! It might be worth looking at `xz` options below `-6` (which is the default), I wouldn't be surprised if there's something with equal or less memory requirements than bzip2 that still outperforms it.

@kalefranz Thanks for the pointer to that blogpost, I'll go through it more thoroughly later and cross-check with my own findings!

**Comment by kalefranz** [comment]
Want to add one more note to make clear what my goals are here, in case it wasn't before.  The three things I think we need to optimize for, in order, are:

1. decompression speed
2. memory footprint during decompression (preferably tunable, e.g. at compression time)
3. compressed artifact size

I'm willing to give up a LOT of compression speed for the benefit of the other three.

I think ideally we'd be able to balance priorities 1 & 2 depending on platform target.

At this point I don't have enough information to have a favorite algorithm.  I'm not partial to any at this point.  I'm also not scared of the newer algorithms with less exposure and battle testing, if they bring with them compelling improvements.  We already have bzip2 for the traditionalists.

**Comment by kalefranz** [comment]
![image](https://user-images.githubusercontent.com/1418419/29035395-0a7b18ec-7b61-11e7-99d6-8ccfcccd3456.png)

Interesting benchmark image from https://gregoryszorc.com/blog/2017/03/07/better-compression-with-zstandard/ that includes bz2 for reference.

**Comment by kalefranz** [comment]
Additional useful references:

* https://quixdb.github.io/squash-benchmark/unstable/
* https://github.com/ebiggers/libdeflate
* http://www.nongnu.org/lzip/xz_inadequate.html
* https://cran.r-project.org/web/packages/brotli/vignettes/brotli-2015-09-22.pdf

**Comment by kalefranz** [comment]
Also very interesting:

* https://github.com/inikep/lizard
