### ISSUE TITLE
conda install --use-local ignores channels as of conda 4.3

### ISSUE THREAD

**Issue by dragly** [conda/conda#4863]
Earlier, we could install locally built packages with --use-local even though they had dependencies in other channels. If the package was not built locally, it would install it from one of the channels if it existed there.

With conda 4.3.13, we get the cryptic error message about a missing blank package when attempting to install with --use-local, no matter if the package is built locally or not:

```
$ conda install pyxona -c defaults -c conda-forge -c cinpla --use-local
Fetching package metadata .............


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - pyxona

You can search for packages on anaconda.org with

    anaconda search -t conda pyxona

```

However, the package installs just fine in conda 4.2.16:

```
$ conda install pyxona -c defaults -c conda-forge -c cinpla --use-local
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /home/username/anaconda3/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.12.0               |           py36_0         7.0 MB
    wheel-0.29.0               |           py36_0          88 KB
    scipy-0.18.1               |      np112py36_1        31.2 MB
    ------------------------------------------------------------
                                           Total:        38.3 MB

The following NEW packages will be INSTALLED:

    libgfortran: 3.0.0-1
    mkl:         2017.0.1-0
    numpy:       1.12.0-py36_0
    openssl:     1.0.2k-1
    pip:         9.0.1-py36_1
    python:      3.6.0-0
    pyxona:      0.1_13_gd3ace21-py_0 cinpla
    quantities:  0.11.1-py36_0        conda-forge
    readline:    6.2-2
    scipy:       0.18.1-np112py36_1
    setuptools:  27.2.0-py36_0
    sqlite:      3.13.0-0
    tk:          8.5.18-0
    wheel:       0.29.0-py36_0
    xz:          5.2.2-1
    zlib:        1.2.8-3

Proceed ([y]/n)?
```

It could also be that some version of the 4.3.* series doesn't have this issue. 

It appears as if channels are completely ignored when the --use-local flag is present.

**Comment by kalefranz** [comment]
@dragly 

Do you get the same results with

    conda install pyxona --use-local -c defaults -c conda-forge -c cinpla

as you do with

    conda install pyxona -c local -c defaults -c conda-forge -c cinpla

?

**Comment by dragly** [comment]
As of conda version 4.3.16 both commands work as expected. They do not produce the same result, but that is expected. I will close the bug since it seems a recent update has fixed the issue.
