### ISSUE TITLE
Runtime error: C libraries

### ISSUE THREAD

**Issue by karoush** [conda/conda#4883]
Everytime I try to open Anaconda Navigator, I get the error below. I have re-installed both Anaconda and Microsoft's C++ distribution. How do I resolve this issue?
![image](https://cloud.githubusercontent.com/assets/13799010/23970614/c24f3d1e-09a0-11e7-9704-dc75d89bbb5d.png)

**Comment by karoush** [comment]
I did try it. Of note, I am running windows 7- though I'm not sure if it makes a difference

**Comment by karoush** [comment]
I also have the same issue with miniconda. Running a version check pulls the following issue:
![image](https://cloud.githubusercontent.com/assets/13799010/23972491/601c8b26-09a8-11e7-97a8-31e60636a103.png)
![image](https://cloud.githubusercontent.com/assets/13799010/23972502/6b8ed9d2-09a8-11e7-8e5e-99883043a153.png)

**Comment by mingwandroid** [comment]
From the `Anaconda Prompt`, please show the output from:

```
echo %PATH%
where python
python --version
```

**Comment by karoush** [comment]
Here is the output:
![image](https://cloud.githubusercontent.com/assets/13799010/23973646/69b62e94-09ad-11e7-81e3-eadae4d749f1.png)

**Comment by mingwandroid** [comment]
This is a mismatch between Anaconda and your system Python.

Please use the Anaconda Prompt to launch your command shell and repeat these commands. Also try launching Anaconda Navigator from that.

**Comment by karoush** [comment]
When I open Anaconda Prompt, I get the runtime error message. Clicking ok eventually allows me to input commands producing the image in my last post.
![image](https://cloud.githubusercontent.com/assets/13799010/23974792/825d526e-09b3-11e7-9254-a0c6671dde71.png)
Attempting to launch navigator from prompt produces the same error.

**Comment by karoush** [comment]
After repeatedly hitting ok after the initial navigator launch attempt, this is what is outputted
![image](https://cloud.githubusercontent.com/assets/13799010/23974851/ea6dbdbc-09b3-11e7-8407-01019971e873.png)

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1679

**Comment by karoush** [comment]
Note: attempting the solutions at https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/windows-10-settings-window-link-errors-in-some/af24a3dd-3634-4a67-96e4-a3054f2c5736

did not resolve the problem.

I have been using python's IDE, but would prefer to have anaconda working
