### ISSUE TITLE
Dependencies not found on -c listed channels, error message should be more useful

### ISSUE THREAD

**Issue by durack1** [conda/conda#4884]
I have just tried to install a package using specific labels:
```
> conda create -n UVCDATNightly -c conda-forge -c uvcdat/label/nightly uvcdat
```
And it fails giving me:
```
> conda create -n labelTest -c uvcdat/label/nightly uvcdat
Fetching package metadata ...........
PackageNotFoundError: Package not found: Conda could not find '
```
What I'm missing here is also adding the **non-nightly** channel (as some of the package dependencies are not included in **nightly**), so:
```
> conda create -n labelTest -c uvcdat/label/nightly -c uvcdat uvcdat
```
Works..

It would be great to augment the error message beyond the existing `PackageNotFoundError: Package not found: Conda could not find '` I wasted a fair bit of time trying to figure out what was happening

@doutriaux1 @zshaheen

**Comment by kalefranz** [comment]
This bogus error message has been fixed.
