### ISSUE TITLE
issue while installing numpy package

### ISSUE THREAD

**Issue by aravindsasidharan** [conda/conda#4890]
Fetching packages ...
llvmlite-0.16. 100% |###############################| Time: 0:00:56 120.95 kB/s
numexpr-2.6.2- 100% |###############################| Time: 0:00:02  63.13 kB/s
scipy-0.19.0-n 100% |###############################| Time: 0:02:01 108.99 kB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:05  83.83 kB/s
numba-0.31.0-n 100% |###############################| Time: 0:00:14 137.31 kB/s
pandas-0.19.2- 100% |###############################| Time: 0:01:07 114.31 kB/s
pytables-3.2.2 100% |###############################| Time: 0:00:20  76.51 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:36 129.02 kB/s
matplotlib-2.0 100% |###############################| Time: 0:01:10 126.94 kB/s
statsmodels-0. 100% |###############################| Time: 0:00:48 128.94 kB/s
An unexpected error has occurred.######             | Time: 0:02:20  80.54 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\DELL\Anaconda2  (writable)
    default environment : C:\Users\DELL\Anaconda2
       envs directories : C:\Users\DELL\Anaconda2\envs
          package cache : C:\Users\DELL\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\DELL\Anaconda2\Scripts\conda-script.py install -c anaconda numpy=1.12.0`

    Traceback (most recent call last):
      File "C:\Users\DELL\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\DELL\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\DELL\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\DELL\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'C:\\Users\\DELL\\Anaconda2\\pkgs\\scikit-image-0.12.3-np112py27_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by tyler-thetyrant** [comment]
`conda update conda` will bring you to the most recent conda, conda 4.3.16. 
Can you try again with the newest version of conda?

**Comment by kalefranz** [comment]
Just an intermittent HTTP issue due to flakey network connection.  Conda 4.3 should help with longer timeouts.
