### ISSUE TITLE
R-Studio Basic Install leaves source window not working

### ISSUE THREAD

**Issue by Pelonza** [conda/conda#4894]
I installed the latest download of Anaconda today, then used it to install the standard version of Rstudio.

Rstudio opens, and I can update packages, run basic code etc. However, the source window does not show any code/text, no matter what kind of file I open. 

I tried to install R-Studio separately and run off of Anaconda's installation of R, but that ran into other issues that I believe the conda team already knows about.... (it couldn't auto-find the R install, and when I navigated to anaconda's R install, it's missing lots of library files)

I tried to find some hint of what might be going wrong in lots of other places...but couldn't seem to find anything. Since I imagine this is a basic requirement for R-Studio, obviously others aren't having this issue...

**Comment by mingwandroid** [comment]
Can you try running rstudio from the `Anaconda Prompt`?

Please share, from the `Anaconda Prompt` your outputs from:
`conda info`
`conda list --show-channel-urls`
`echo %PATH%`

**Comment by Pelonza** [comment]
Ran R-Studio from the prompt, problem still exists.

Outputs from prompt:

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\kschmit1\AppData\Local\conda\conda\envs
                          C:\Users\kschmit1\.conda\envs
          package cache : C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\kschmit1\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\kschmit1\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.10586

# packages in environment at C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.9                    py36_0    defaults
anaconda                  4.3.1               np111py36_0    defaults
anaconda-client           1.6.0                    py36_0    defaults
anaconda-navigator        1.5.0                    py36_0    defaults
anaconda-project          0.4.1                    py36_0    defaults
anyqt                     0.0.8                    py36_1    conda-forge
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3                 np111py36_0    defaults
babel                     2.3.4                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.5.3                    py36_0    defaults
bitarray                  0.8.1                    py36_1    defaults
blaze                     0.10.1                   py36_0    defaults
bokeh                     0.12.4                   py36_0    defaults
boto                      2.45.0                   py36_0    defaults
bottleneck                1.2.0               np111py36_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.9.1                    py36_0    defaults
chardet                   2.3.0                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.7                    py36_0    defaults
comtypes                  1.1.2                    py36_0    defaults
conda                     4.3.14                   py36_1    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py36_0    defaults
console_shortcut          0.1.1                    py36_1    defaults
contextlib2               0.5.4                    py36_0    defaults
cryptography              1.7.1                    py36_0    defaults
curl                      7.52.1                   vc14_0  [vc14]  defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.13.0                   py36_0    defaults
datashape                 0.5.4                    py36_0    defaults
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.5                    py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_0    defaults
et_xmlfile                1.0.1                    py36_0    defaults
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12                     py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
font-ttf-dejavu-sans-mono 2.37                          0    defaults
font-ttf-inconsolata      2.000                         0    defaults
font-ttf-source-code-pro  2.030                         0    defaults
font-ttf-ubuntu           0.83                          0    defaults
fonts-continuum           1                             0    defaults
freetype                  2.5.5                    vc14_2  [vc14]  defaults
get_terminal_size         1.0.0                    py36_0    defaults
gevent                    1.2.1                    py36_0    defaults
greenlet                  0.4.11                   py36_0    defaults
h5py                      2.6.0               np111py36_2    defaults
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py36_1    defaults
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.2                      py36_0    defaults
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.5.2                    py36_0    defaults
ipython                   5.1.0                    py36_0    defaults
ipython_genutils          0.1.0                    py36_0    defaults
ipywidgets                5.2.2                    py36_1    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.9.0                    py36_1    defaults
jinja2                    2.9.4                    py36_0    defaults
joblib                    0.9.4                    py36_0    defaults
jpeg                      9b                       vc14_0  [vc14]  defaults
jsonschema                2.5.1                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            4.4.0                    py36_0    defaults
jupyter_console           5.0.0                    py36_0    defaults
jupyter_core              4.2.1                    py36_0    defaults
keyring                   9.3.1                    py36_0    defaults
keyrings.alt              1.2                      py36_0    conda-forge
lazy-object-proxy         1.2.2                    py36_0    defaults
libpng                    1.6.27                   vc14_0  [vc14]  defaults
libtiff                   4.0.6                    vc14_3  [vc14]  defaults
llvmlite                  0.15.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.2                    py36_0    defaults
m2-bash                   4.3.042                       5    defaults
m2-gcc-libs               5.3.0                         4    defaults
m2-heimdal                1.5.3                        10    defaults
m2-heimdal-libs           1.5.3                        10    defaults
m2-icu                    56.1                          2    defaults
m2-libcrypt               1.3                           2    defaults
m2-libdb                  5.3.28                        3    defaults
m2-libedit                3.1                    20150326    defaults
m2-libopenssl             1.0.2.g                       2    defaults
m2-libreadline            6.3.008                       8    defaults
m2-libsqlite              3.10.0.0                      2    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-ncurses                6.0.20160220                  2    defaults
m2-openssh                7.1p2                         2    defaults
m2-openssl                1.0.2.g                       2    defaults
m2-zlib                   1.2.8                         4    defaults
m2w64-bwidget             1.9.10                        2    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-c-ares              1.11.0                        2    defaults
m2w64-ca-certificates     20150426                    103    defaults
m2w64-curl                7.48.0                        2    defaults
m2w64-diffutils           3.3.2                         2    defaults
m2w64-expat               2.1.1                         2    defaults
m2w64-fftw                3.3.4                         6    defaults
m2w64-flac                1.3.1                         3    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-gnutls              3.4.11                        2    defaults
m2w64-grep                2.24                          2    defaults
m2w64-gsl                 2.1                           2    defaults
m2w64-jansson             2.7                           3    defaults
m2w64-libffi              3.2.1                         4    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libidn              1.32                          4    defaults
m2w64-libjpeg-turbo       1.4.2                         3    defaults
m2w64-libmetalink         0.1.3                         2    defaults
m2w64-libogg              1.3.2                         3    defaults
m2w64-libpng              1.6.21                        2    defaults
m2w64-libsndfile          1.0.26                        2    defaults
m2w64-libssh2             1.7.0                         2    defaults
m2w64-libsystre           1.0.1                         3    defaults
m2w64-libtasn1            4.7                           2    defaults
m2w64-libtiff             4.0.6                         2    defaults
m2w64-libtre-git          122.c2f5d13                   5    defaults
m2w64-libvorbis           1.3.5                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-libxml2             2.9.3                         3    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-nettle              3.1.1                         4    defaults
m2w64-nghttp2             1.9.2                         2    defaults
m2w64-nlopt               2.4.2                         3    defaults
m2w64-openssl             1.0.2.g                       2    defaults
m2w64-p11-kit             0.23.2                        2    defaults
m2w64-pcre                8.38                          2    defaults
m2w64-rtmpdump-git        499.a107cef                   4    defaults
m2w64-speex               1.2rc2                        3    defaults
m2w64-speexdsp            1.2rc3                        3    defaults
m2w64-tcl                 8.6.5                         3    defaults
m2w64-tk                  8.6.5                         3    defaults
m2w64-tktable             2.10                          5    defaults
m2w64-wineditline         2.101                         5    defaults
m2w64-xz                  5.2.2                         2    defaults
m2w64-zlib                1.2.8                        10    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.0.0               np111py36_0    defaults
menuinst                  1.4.4                    py36_0    defaults
mistune                   0.7.3                    py36_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mpmath                    0.19                     py36_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.4.9                    py36_0    defaults
nbconvert                 4.2.0                    py36_0    defaults
nbformat                  4.2.0                    py36_0    defaults
networkx                  1.11                     py36_0    defaults
nltk                      3.2.2                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  4.3.1                    py36_2    defaults
numba                     0.30.1              np111py36_0    defaults
numexpr                   2.6.1               np111py36_2    defaults
numpy                     1.11.3                   py36_0    defaults
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
openpyxl                  2.4.1                    py36_0    defaults
openssl                   1.0.2k                   vc14_0  [vc14]  defaults
orange3                   3.4.1               np111py36_0    conda-forge
pandas                    0.19.2              np111py36_1    defaults
pandoc                    1.19.2.1                      1    defaults
partd                     0.3.7                    py36_0    defaults
path.py                   10.0                     py36_0    defaults
pathlib2                  2.2.0                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pep8                      1.7.0                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    4.0.0                    py36_0    defaults
pip                       9.0.1                    py36_1    defaults
ply                       3.9                      py36_0    defaults
prompt_toolkit            1.0.9                    py36_0    defaults
psutil                    5.0.1                    py36_0    defaults
py                        1.4.32                   py36_0    defaults
pyasn1                    0.1.9                    py36_0    defaults
pycosat                   0.6.1                    py36_1    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_5    defaults
pycurl                    7.43.0                   py36_2    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.1.3                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyopenssl                 16.2.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pyqtgraph                 0.10.0                   py36_2    conda-forge
pytables                  3.2.2               np111py36_4    defaults
pytest                    3.0.5                    py36_0    defaults
python                    3.6.0                         0    defaults
python-dateutil           2.6.0                    py36_0    defaults
pytz                      2016.10                  py36_0    defaults
pywin32                   220                      py36_2    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                    vc14_3  [vc14]  defaults
qtawesome                 0.4.3                    py36_0    defaults
qtconsole                 4.2.1                    py36_2    defaults
qtpy                      1.2.1                    py36_0    defaults
r                         3.3.2                  r3.3.2_0    r
r-assertthat              0.1                    r3.3.2_4    defaults
r-backports               1.0.4                  r3.3.2_0    defaults
r-base                    3.3.2                         0    defaults
r-base64enc               0.1_3                  r3.3.2_0    defaults
r-bh                      1.62.0_1               r3.3.2_0    defaults
r-bitops                  1.0_6                  r3.3.2_2    defaults
r-boot                    1.3_18                 r3.3.2_0    defaults
r-broom                   0.4.1                  r3.3.2_0    defaults
r-car                     2.1_4                  r3.3.2_0    defaults
r-caret                   6.0_73                 r3.3.2_0    defaults
r-catools                 1.17.1                 r3.3.2_2    defaults
r-class                   7.3_14                 r3.3.2_0    defaults
r-cluster                 2.0.5                  r3.3.2_0    defaults
r-codetools               0.2_15                 r3.3.2_0    defaults
r-colorspace              1.3_1                  r3.3.2_0    defaults
r-crayon                  1.3.2                  r3.3.2_0    defaults
r-curl                    2.3                    r3.3.2_0    defaults
r-data.table              1.10.0                 r3.3.2_0    defaults
r-dbi                     0.5_1                  r3.3.2_0    defaults
r-dichromat               2.0_0                  r3.3.2_2    defaults
r-digest                  0.6.10                 r3.3.2_0    defaults
r-dplyr                   0.5.0                  r3.3.2_0    defaults
r-essentials              1.5.2                  r3.3.2_0    defaults
r-evaluate                0.10                   r3.3.2_0    defaults
r-forcats                 0.1.1                  r3.3.2_0    defaults
r-foreach                 1.4.3                  r3.3.2_0    defaults
r-foreign                 0.8_67                 r3.3.2_0    defaults
r-formatr                 1.4                    r3.3.2_0    defaults
r-ggplot2                 2.2.0                  r3.3.2_0    defaults
r-gistr                   0.3.6                  r3.3.2_0    defaults
r-glmnet                  2.0_5                  r3.3.2_0    defaults
r-gtable                  0.2.0                  r3.3.2_0    defaults
r-haven                   1.0.0                  r3.3.2_0    defaults
r-hexbin                  1.27.1                 r3.3.2_0    defaults
r-highr                   0.6                    r3.3.2_0    defaults
r-hms                     0.3                    r3.3.2_0    defaults
r-htmltools               0.3.5                  r3.3.2_0    defaults
r-htmlwidgets             0.8                    r3.3.2_0    defaults
r-httpuv                  1.3.3                  r3.3.2_0    defaults
r-httr                    1.2.1                  r3.3.2_0    defaults
r-irdisplay               0.4.4                  r3.3.2_0    defaults
r-irkernel                0.7.1                  r3.3.2_0    defaults
r-iterators               1.0.8                  r3.3.2_0    defaults
r-jsonlite                1.1                    r3.3.2_0    defaults
r-kernsmooth              2.23_15                r3.3.2_0    defaults
r-knitr                   1.15.1                 r3.3.2_0    defaults
r-labeling                0.3                    r3.3.2_2    defaults
r-lattice                 0.20_34                r3.3.2_0    defaults
r-lazyeval                0.2.0                  r3.3.2_0    defaults
r-lme4                    1.1_12                 r3.3.2_0    defaults
r-lubridate               1.6.0                  r3.3.2_0    defaults
r-magrittr                1.5                    r3.3.2_2    defaults
r-maps                    3.1.1                  r3.3.2_0    defaults
r-markdown                0.7.7                  r3.3.2_2    defaults
r-mass                    7.3_45                 r3.3.2_0    defaults
r-matrix                  1.2_7.1                r3.3.2_0    defaults
r-matrixmodels            0.4_1                  r3.3.2_0    defaults
r-mgcv                    1.8_16                 r3.3.2_0    defaults
r-mime                    0.5                    r3.3.2_0    defaults
r-minqa                   1.2.4                  r3.3.2_2    defaults
r-mnormt                  1.5_5                  r3.3.2_0    defaults
r-modelmetrics            1.1.0                  r3.3.2_0    defaults
r-modelr                  0.1.0                  r3.3.2_0    defaults
r-munsell                 0.4.3                  r3.3.2_0    defaults
r-nlme                    3.1_128                r3.3.2_0    defaults
r-nloptr                  1.0.4                  r3.3.2_2    defaults
r-nnet                    7.3_12                 r3.3.2_0    defaults
r-openssl                 0.9.5                  r3.3.2_0    defaults
r-packrat                 0.4.8_1                r3.3.2_0    defaults
r-pbdzmq                  0.2_4                  r3.3.2_0    defaults
r-pbkrtest                0.4_6                  r3.3.2_0    defaults
r-pki                     0.1_3                  r3.3.2_0    defaults
r-plyr                    1.8.4                  r3.3.2_0    defaults
r-pryr                    0.1.2                  r3.3.2_0    defaults
r-psych                   1.6.9                  r3.3.2_0    defaults
r-purrr                   0.2.2                  r3.3.2_0    defaults
r-quantmod                0.4_7                  r3.3.2_0    defaults
r-quantreg                5.29                   r3.3.2_0    defaults
r-r6                      2.2.0                  r3.3.2_0    defaults
r-randomforest            4.6_12                 r3.3.2_0    defaults
r-rbokeh                  0.5.0                  r3.3.2_0    defaults
r-rcolorbrewer            1.1_2                  r3.3.2_3    defaults
r-rcpp                    0.12.8                 r3.3.2_0    defaults
r-rcppeigen               0.3.2.9.0              r3.3.2_0    defaults
r-rcurl                   1.95_4.8               r3.3.2_0    defaults
r-readr                   1.0.0                  r3.3.2_0    defaults
r-readxl                  0.1.1                  r3.3.2_0    defaults
r-recommended             3.3.2                  r3.3.2_0    defaults
r-repr                    0.10                   r3.3.2_0    defaults
r-reshape2                1.4.2                  r3.3.2_0    defaults
r-rjsonio                 1.3_0                  r3.3.2_2    defaults
r-rmarkdown               1.3                    r3.3.2_0    defaults
r-rpart                   4.1_10                 r3.3.2_0    defaults
r-rprojroot               1.1                    r3.3.2_0    defaults
r-rsconnect               0.7                    r3.3.2_0    defaults
r-rstudioapi              0.6                    r3.3.2_0    defaults
r-rvest                   0.3.2                  r3.3.2_0    defaults
r-scales                  0.4.1                  r3.3.2_0    defaults
r-selectr                 0.3_0                  r3.3.2_0    defaults
r-shiny                   0.14.2                 r3.3.2_0    defaults
r-sourcetools             0.1.5                  r3.3.2_0    defaults
r-sparsem                 1.74                   r3.3.2_0    defaults
r-spatial                 7.3_11                 r3.3.2_0    defaults
r-stringi                 1.1.2                  r3.3.2_0    defaults
r-stringr                 1.1.0                  r3.3.2_0    defaults
r-survival                2.40_1                 r3.3.2_0    defaults
r-tibble                  1.2                    r3.3.2_0    defaults
r-tidyr                   0.6.0                  r3.3.2_0    defaults
r-tidyverse               1.0.0                  r3.3.2_0    defaults
r-ttr                     0.23_1                 r3.3.2_0    defaults
r-uuid                    0.1_2                  r3.3.2_0    defaults
r-xml2                    1.0.0                  r3.3.2_0    defaults
r-xtable                  1.8_2                  r3.3.2_0    defaults
r-xts                     0.9_7                  r3.3.2_2    defaults
r-yaml                    2.1.14                 r3.3.2_0    defaults
r-zoo                     1.7_13                 r3.3.2_0    defaults
requests                  2.12.4                   py36_0    defaults
rope                      0.9.4                    py36_1    defaults
rstudio                   1.0.136                  vc14_1  [vc14]  defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.12.3              np111py36_1    defaults
scikit-learn              0.18.1              np111py36_1    defaults
scipy                     0.18.1              np111py36_1    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sphinx                    1.5.1                    py36_0    defaults
spyder                    3.1.2                    py36_0    defaults
sqlalchemy                1.1.5                    py36_0    defaults
statsmodels               0.6.1               np111py36_1    defaults
sympy                     1.0                      py36_0    defaults
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.4.2                    py36_0    defaults
traitlets                 4.3.1                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.11.15                  py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        1.2.6                    py36_0    defaults
win_unicode_console       0.5                      py36_0    defaults
wrapt                     1.10.8                   py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwings                   0.10.2                   py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

Path:
C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Library\mingw-w64\bin;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Library\usr\bin;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Library\bin;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Scripts;C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3\Library\bin

**Comment by mingwandroid** [comment]
Can you attach a screenshot or two to illustrate this please?

**Comment by Pelonza** [comment]
![image](https://cloud.githubusercontent.com/assets/12863059/24076027/b074aaaa-0bf5-11e7-8386-0358fd25b895.png)
![screenshot 2017-03-18 16 12 58](https://cloud.githubusercontent.com/assets/12863059/24076039/e9192002-0bf5-11e7-86e3-43ddd7f6b114.png)

**Comment by Pelonza** [comment]
Shots above show the R-studio editor window blank, side-by-side with the same file opened in note-pad. 

I tried to do the same with a *.R file, but I think in the process of messing with them, the file I was looking at got wiped also.

**Comment by Pelonza** [comment]
So I installed another version of R on the computer, and was able to get code to show up....

But it's definitely an issue with the install that comes with the Anaconda install of R. 

Now that I've installed a different version of R, and am using the "default system R" ... instead of the Anaconda install the code panel works fine... 

So...my personal issue is resolved, but still a bit concerning that the simple install process for it didn't work on a fresh computer...

**Comment by mingwandroid** [comment]
When you say "a fresh computer", how fresh do you mean?

Does your computer run OpenGL OK? Can you use e.g. WebGL demos such as the ones here: http://webglsamples.org/

**Comment by Pelonza** [comment]
By "fresh" I meant mostly I meant, I hadn't installed R-Studio or Anaconda at all on the computer before. There's definitely stuff installed (I've had it about a year now maybe)...but I've tried to keep it fairly clean since it's a work provided laptop. 

However, the OpenGL stuff runs just fine....

**Comment by Pelonza** [comment]
And... something is still weird/broken with it, because it started doing it again. 
For some more context, I'm trying to run Microsoft's "IDEAR" package...which has it's own slew of dependencies that it installs... so there might be something wonky in there too...

But again, I had no problem running that on my Win-7 Machine...

**Comment by mingwandroid** [comment]
> something is still weird/broken with it, because it started doing it again
To clarify, do you mean:
1. The "default system R"/RStudio worked for a while then stopped or
2. The Anaconda R/RStudio worked for a while then stopped?

**Comment by Pelonza** [comment]
I mean the anaconda launched version still had issues. It might be that I tried launching it with not the Anaconda-R install (using "Ctrl-launch") when it was working...

**Comment by kalefranz** [comment]
I'm going to close this issue, because I don't see anything here that changing conda's own code can help with.  Feel free to keep discussing though.
