### ISSUE TITLE
Conda ImportError: cannot import name 'get_auth_from_url'

### ISSUE THREAD

**Issue by sidhiartha** [conda/conda#4897]
Every time I type conda and then press enter, whatever the following code, it always give me these Error: **ImportError: cannot import name 'get_auth_from_url'**

I have try to install another Anaconda, fresh download from the site, in another folder and try to access it directly with full URL, but it still give me the same error.

My System:
OS: macOS Sierra
Anaconda: v. 3.6

How can I fix this issue?

If there are some additional information needed, please state it and I will try to provide it as fast as possible.

Thanks for the help
Sidhi Artha

**Comment by kalefranz** [comment]
Please provide the full stack trace and the output of `conda info`.
