### ISSUE TITLE
conda packages dependencies: lack of update, problems after update

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda#4900]
Hi,

We have a channel where we distribute our packages (https://anaconda.org/acellera). We find conda a great platform to distribute our software, but we find the updates rather troublesome much of the times, specially related with dependencies.

**Issue number 1:** When doing `conda update htmd -c acellera`, our main package, we notice many times that the dependencies are not updated. We know there is a flag, `--update-dependencies`, specifically related with this, but we trust the default to be working. Is this not the case? In this end, we sometimes recommend people to use the `conda update --all`, which I've read somewhere that it should be used carefully. We currently also implemented a way of having specific versions associated with the package instead of keeping it to the latest, but it doesn't seem like it has improved the behaviour much. 

**Issue number 2:** Alternatively to the behaviour in Issue 1, the package is updated, as shown by `conda list`, but the Python module still behaves like the old one, suggesting that there may be a conflict between the older installation and the new one.

**Issue number 3:** Sometimes, we change our package, and create a new dependency for it. For new installations, everything works fine, but for installations that are updated to a new version using `conda update`, for some people and more often than we wished for, the package cannot de imported, like it was missing. Despite that, the command `conda list` reports it.

Many times, we are left clueless about these issues, and all we can suggest to our users is to reinstall conda, which normally fixes the issues. Do all these issues mean that `conda update` cannot be trusted? Asking our users to always be installing conda is very annoying.

We appreciate any feedback that could improve this issues.

João

**Comment by j3mdamas** [comment]
I have an idea. Could it be possible that the `--update-dependencies` does not use the channel I am passing, and hence the dependencies do not "see" the updated packages that exist in that channel?

**Comment by kalefranz** [comment]
> We know there is a flag, --update-dependencies, specifically related with this, but we trust the default to be working. Is this not the case?

We've gone through several iterations of behavior here, and it turns out the "least surprise" is to not change the version of a package if it is installed and still consistent with the rest of the environment.  That `--update-dependencies` flag is indeed there to override that behavior.

> but the Python module still behaves like the old one

I really have no context to help here.  I'd probably start with

    python -c "import htmd; print(htdm.__version__)"

> Issue number 3

This is the first I can recall I've heard of behavior like this.  Not that it's not happening.  But it might be possible there's a quirk here that's unique to you or how you're building packages.  I'm guessing there's no deterministic set of steps I could follow to reproduce this behavior?

**Comment by kalefranz** [comment]
I recently wrote some tests that showed the `--update-dependencies` flag actually isn't working as it should.  https://github.com/conda/conda/issues/5263

Hoping that @mcg1969 can help out with getting to the root cause of #5263.

**Comment by j3mdamas** [comment]
Hi @kalefranz,

Thanks for the feedback. 

But the `--update-dependencies` is said to be `default: True` on the help, so it should be the default behaviour rather than the flag to override, like you said. Or is this covered in the erroneous behaviour you mention in the other issue?

For issue 2, it was not about the package itself, but about the dependencies. I don't have an example right now, and if you don't hear back from me, never mind this issue. If I remember correctly, if a dependency used to put a file in the conda/bin at a given version, and in a subsequent version, it did not have that file in conda/bin anymore, the update would not "clean" the file from conda/bin. Is this clear?

Issue 3 is actually an issue that I don't remember. I deeply apologize for not having reproducible examples :( We were doing many changes in our package and dependencies, and I could not take the time to create them.

If issue 1 could be solved, it would already be great!

**Comment by j3mdamas** [comment]
We've circumvented conda update by having our own updating manager. I'm closing this issue.
