### ISSUE TITLE
conda install --revision N can remove conda itself

### ISSUE THREAD

**Issue by arnold-jr** [conda/conda#4909]
Trying to rollback to a previous version of conda, I inadvertently removed conda without replacing it. Perhaps there should be a warning for this, since I'm stuck trying to figure out how to piece my root environment back together.

**Comment by kalefranz** [comment]
What versions of conda were you switching between?  And did the rollback operation fail?

**Comment by arnold-jr** [comment]
If memory serves, the revision was 
```
2017-03-21 21:00:40  (rev 2)
     conda  {4.3.14  -> 4.3.8 }
```
It didn't fail; there was simply no `conda` command left to me. Sorry I didn't document it better. Feel free to close this ticket.
