### ISSUE TITLE
Issue to create an environment 

### ISSUE THREAD

**Issue by MariaSkr** [conda/conda#4910]
![issue](https://cloud.githubusercontent.com/assets/12560275/24173312/db481d3c-0e8b-11e7-8cbd-02d25be54474.jpg)

**Comment by MariaSkr** [comment]
The initial command was conda env create -f environment.yml

**Comment by MariaSkr** [comment]
![image](https://cloud.githubusercontent.com/assets/12560275/24173557/cb26a634-0e8c-11e7-9b90-c304895cb6ea.png)

**Comment by nehaljwani** [comment]
Does `conda env create -f full\path\to\environment.yml` work for you?

**Comment by MariaSkr** [comment]
Unfortunately it doesn't 
![image](https://cloud.githubusercontent.com/assets/12560275/24213797/febc0a78-0f33-11e7-8072-e9b1a871aa9c.png)

**Comment by nehaljwani** [comment]
Do you see the same error with only this command or any other conda command like `conda search something`?

**Comment by kalefranz** [comment]
SSL handshake error.
