### ISSUE TITLE
Can't create Python 2.7.x env inside a VirtualEnv

### ISSUE THREAD

**Issue by gonzalodiaz** [conda/conda#4915]
I have the use case that I need `conda` installed inside a `VirtualEnv`. This schema was working until yesterday that I tried to rebuild the environment.

After hours of headbanging against the keyword, I could reduce the case to this: 

1. Download and Install Conda 2.7 or 3.6 from https://conda.io/miniconda.html
2. Then open a new terminal and:
```
$ conda update conda
$ conda -V
conda 4.3.14
$ virtualenv --version
15.0.1
$ python --version
Python 2.7.13 : Continuum Analytics. Inc.
```

3. Now, try to reproduce:
```
$ mkdir test_dir; cd test_dir
$ virtualenv venv 
$ conda install --yes --prefix ./venv python=2.7.11=0

ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::python-2.7.11-0'.
IOError(13, 'Permission denied')
Attempting to roll back.

# Sometimes I get this error too:
ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::python-2.7.13-0'.
FileExistsError(17, 'File exists')
Attempting to roll back.
```

Any version of python 2.7 is causing this issue. Every python 3.5 versions work.
I've tried using conda 2.7 and conda 3.5. Same result.
I've tested this in Mac OX El Capitan and also inside a fresh Vagrant VM with Ubuntu 14.04.

Using Pure Conda environments, everything works as expected. The virtual env factor seems to be causing issues now.

A more verbose output (just the important part):
```
INFO conda.core.link:_execute_actions(317): ===> LINKING PACKAGE: defaults::python-2.7.11-0 <===
  prefix=/home/vagrant/test_dir/venv
  source=/home/vagrant/miniconda3/pkgs/python-2.7.11-0

INFO conda.gateways.disk.create:create_link(223): file exists, but clobbering: '/home/vagrant/test_dir/venv/bin/python'
INFO conda.gateways.disk.create:create_link(223): file exists, but clobbering: '/home/vagrant/test_dir/venv/bin/python2'
INFO conda.gateways.disk.create:create_link(223): file exists, but clobbering: '/home/vagrant/test_dir/venv/bin/python2.7'
INFO conda.gateways.disk.create:create_link(223): file exists, but clobbering: '/home/vagrant/test_dir/venv/include/python2.7/Python-ast.h'
DEBUG conda.gateways.disk.permissions:make_writable(36): tried make writable but failed: /home/vagrant/test_dir/venv/include/python2.7/Python-ast.h
PermissionError(1, 'Operation not permitted')
DEBUG conda.gateways.disk.delete:rm_rf(50): PermissionError(13, 'Permission denied') errno 13
Cannot unlink /home/vagrant/test_dir/venv/include/python2.7/Python-ast.h.
INFO conda.gateways.disk.delete:rm_rf(55): Failed to remove /home/vagrant/test_dir/venv/include/python2.7/Python-ast.h.
INFO conda.gateways.disk.delete:rm_rf(62): rm_rf failed for /home/vagrant/test_dir/venv/include/python2.7/Python-ast.h
DEBUG conda.core.link:_execute_actions(328): Error in action #44 for pkg_idx #5 LinkPathAction(target_prefix='/home/vagrant/test_dir/venv', target_short_path='include/python2.7/Python-ast.h', source_prefix='/home/vagrant/miniconda3/pkgs/python-2.7.11-0', source_short_path='include/python2.7/Python-ast.h', link_type=<LinkType.hardlink: 1>, _execute_successful=False, _verified=True)
DEBUG conda.core.link:_execute_actions(329): Traceback (most recent call last):
  File "/home/vagrant/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 324, in _execute_actions
    action.execute()
  File "/home/vagrant/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 225, in execute
    force=context.force)
  File "/home/vagrant/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 229, in create_link
    link(src, dst)
FileExistsError: [Errno 17] File exists: '/home/vagrant/miniconda3/pkgs/python-2.7.11-0/include/python2.7/Python-ast.h' -> '/home/vagrant/test_dir/venv/include/python2.7/Python-ast.h'

ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::python-2.7.11-0'.
FileExistsError(17, 'File exists')
Attempting to roll back.

INFO conda.core.link:_reverse_actions(359): ===> REVERSING PACKAGE LINK: defaults::python-2.7.11-0 <===
  prefix=/home/vagrant/test_dir/venv
```

**Comment by mingwandroid** [comment]
Where did you get your `virtualenv` package from?

**Comment by gonzalodiaz** [comment]
@mingwandroid from `pip` by doing `pip install virtualenv`.

**Comment by mingwandroid** [comment]
Correct me if I'm off-base here, but why do you expect `conda` to be able to co-exist inside a `virtualenv` here? If `conda` ever overwrites a system file (from its perspective, a pre-existing `virtualenv` looks just like that), would you not hope that it would undo that?

**Comment by gonzalodiaz** [comment]
@mingwandroid in this particular project we are using `virtualenv --relocatable` and then we apply some obscure scripts to be able to have the environment "relocatable", by altering the path of the environment. Doing so, we build the environment once, and then we can deploy it in N nodes in the cluster. Scaling the instances up and down without issues.

Being that said, I know our DevOps team now is working with `conda` "relocatable" environments. Perhaps a new feature in `conda`. 
But the project with this particular issue has an old base code. It is in production and we don't want to change much right now as it is very critical. Especially, how we build it.

**Comment by mingwandroid** [comment]
From what I've read: https://virtualenv.pypa.io/en/latest/userguide/#making-environments-relocatable you want to move away from this feature anyway.

I know this isn't the use pattern you have at present, but you can now use `virtualenvs` within `conda` if you use our fixed `virtualenv` package, so perhaps that is an option.

But really, I'd encourage just using `conda` envs. AFAIK, `conda` envs have always been relocatable; it's something we rely upon across the entire eco-system.

**Comment by nehaljwani** [comment]
@mingwandroid I feel a little apprehensive about stating that conda envs have always been relocatable. IIUC, the term 'relocatable' also implies that the environment can me _moved around_ in the same computer to a different location, which AFAIK, will not always work with Conda, for example, when one of the packages has a config file or a binary with a C String in it which should always be pointing to `$PREFIX/some/thing` and is patched every time that package is installed in a new environment. 

Related thread: https://github.com/conda/conda/issues/1845

**Comment by kalefranz** [comment]
You're right, you can't use `mv` to move/relocate environments, but that's a pretty limited definition. Instead we have `conda create --clone`.
