### ISSUE TITLE
conda activate/deactivate ruins PS1 in 4.3.14

### ISSUE THREAD

**Issue by debashissaha** [conda/conda#4916]
In 4.3.1, source activate calls "deactivate for previous envs... line 62:

```
 60 # Ensure we deactivate any scripts from the old env
 61 _CONDA_HOLD=true
 62 source "$_CONDA_DIR/deactivate"
 63 unset _CONDA_HOLD
```

But if this is no previous environment ($CONDA_PS1_BACKUP is unset), PS1 is set to null and therefore a subsequent deactivate cannot retrieve the original PS1
[The logic around _CONDA_HOLD is broken in deactivate]

```
foobar:~ ds$ echo $PS1
\h:\W \u\$
foobar:~ ds$ echo $CONDA_PS1_BACKUP

foobar:~ ds$ source activate magenta
(magenta) echo $PS1
(magenta)
(magenta) echo $CONDA_PS1_BACKUP

(magenta) source deactivate

date
Wed Mar 22 08:03:17 PDT 2017
```
--> Lost prompt

**Comment by ijstokes** [comment]
I think I'm suffering from a variation of this, where `source activate` obliterates the previous `$PS1` so there is no visible prompt.  Also `source activate` creates a prompt which is **just** `(env_name)` and nothing else.

**Comment by ijstokes** [comment]
Using conda 4.3.16 on OS X with bash.

**Comment by AlbertDeFusco** [comment]
I'm also having the same problem. It seems like it started with some conda update in the last few months.

I've solved it(1) by adding `export CONDA_PS1_BACKUP` in `~/.bash_profile`

```bash
#completion and PS1
if [ -e /opt/local/etc/bash_completion ]; then
  . /opt/local/etc/bash_completion
fi
if [ -f /opt/local/share/git/contrib/completion/git-completion.bash ]; then
  source /opt/local/share/git/contrib/completion/git-completion.bash
  source /opt/local/share/git/contrib/completion/git-prompt.sh
  GIT_PS1_SHOWDIRTYSTATE=true
  export PS1="\u@\h:\W\$(__git_ps1)>"
else
  export PS1="\u@\h:\W>"
fi

export CONDA_PS1_BACKUP=$PS1 # fix source activate

export PATH=$HOME/Applications/anaconda3/4.4/bin:$PATH
```

(1) however,  `source activate` replaces my original `export PATH` above. I don't think this happened in previous versions. That means that `source deactivate` completely removes the path to `conda` from my `$PATH`. Is this expected behavior?

```bash
adefusco@0235-adefusco:~>conda --version
econda 4.3.27
adefusco@0235-adefusco:~>echo $PATH
/Users/adefusco/bin:/Users/adefusco/Applications/anaconda3/4.4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

adefusco@0235-adefusco:~>source activate new_env

(new_env) adefusco@0235-adefusco:~>echo $PATH
/Users/adefusco/Applications/anaconda3/4.4/envs/new_env/bin:/Users/adefusco/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

(new_env) adefusco@0235-adefusco:~>source deactivate

adefusco@0235-adefusco:~>echo $PATH
/Users/adefusco/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

**Comment by kalefranz** [comment]
`activate` was reworked for conda 4.4.  If you continue to have a problem, please file a new issue.
