### ISSUE TITLE
Better shebang detection for other languages

### ISSUE THREAD

**Issue by bkreider** [conda/conda#492]
It would be really helpful for bundling nodejs packages, if there was support for turning "#!/usr/bin/env node" to "#!${PREFIX}/bin/node".  All of the node packages created using "npm install" will create a shebang line like that.

I tried to add a build step to modify the binaries to have "#!/opt/anaconda1anaconda2/anaconda3/bin/node", but it looks like the installer.py module looks for "bin/python" as a trigger to expand the install.prefix_placeholder.  I which it looked in the first line of the binary for install.prefix_placeholder, so we could at least patch support for other languages into our generated binaries.

**Comment by jakirkham** [comment]
Could this patching be done as part of the build step with `$PREFIX` expanded? I think then `conda-build` should pick this up. Or was this already tried and/or I'm just missing it?

**Comment by bkreider** [comment]
@jakirkham I haven't tried doing it the right way in 2 years, but i think part of the problem is that nodejs programs (I'm not a nodejs developer) have the canonical form of `#!/usr/bin/env node` instead of `#!$PREFIX/node`.  I think conda-build only fixes this automatically if it sees $PREFIX.

**Comment by jakirkham** [comment]
So, I use the form `#!/usr/bin/env python` with my Python scripts and `conda-build` picks this up and fixes them. It might be worthwhile trying to pick up a sample `node` recipe and see if this is still a problem. Are there some floating in conda-recipes or anaconda-recipes that we could look at, @bkreider?

**Comment by bkreider** [comment]
I think the recipes in wakari-recipes repo.  aen-gateway is a pure javascript app as well.

**Comment by jakirkham** [comment]
Ah, I'm guessing those are not open sourced, right? That or I'm just not looking in the right place.

If they are still closed source, is there one (ideally) pure javascript recipe that is simple enough that it wouldn't cause issues being open sourced?

**Comment by bkreider** [comment]
Sorry, you are right.  I posted the coffee-script conda recipe above.  Here it is.  I haven't built this in a very long time though, so i hope it still works:

meta.yaml
```
package:
  name: coffee-script
  version: 1.7.1

build:
  number: {{environ.get('binstar_build', 1)}}

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - coffee --version

about:
  home: http://coffeescript.org/
```


build.sh:
```
#!/bin/bash

npm --loglevel warn install -g coffee-script@$PKG_VERSION

# Make env safe - fix shbang lines
pushd $PREFIX
binary="lib/node_modules/coffee-script/bin/coffee"
mv $binary $binary.old
echo "#!${PREFIX}/bin/node" >  $binary
tail -n +2 $binary.old >> $binary
rm $binary.old
chmod +x $binary

binary="lib/node_modules/coffee-script/bin/cake"
mv $binary $binary.old
echo "#!${PREFIX}/bin/node" >  $binary
tail -n +2 $binary.old >> $binary
rm $binary.old
chmod +x $binary
popd
```

You can find nodejs on my channel `bkreider` or in the default channels.
