### ISSUE TITLE
HTTP 404 error when attempting to update Conda

### ISSUE THREAD

**Issue by Natathon** [conda/conda#4926]
Hey all, I'm very new to this. I keep getting a HTTP 404 error when attempting to update conda. I've included a picture in this post. I'm trying to use Geoff Boeings OSMNX: http://geoffboeing.com/2017/02/python-getting-started/

![img_3402](https://cloud.githubusercontent.com/assets/25332533/24259243/55c77f0c-0fbe-11e7-98be-46498dede896.JPG)

Let me know if you have any advice!

**Comment by goanpeca** [comment]
@Natathon could you type `conda info` and paste the result here?

**Comment by Natathon** [comment]
Hey @goanpeca, I just got back from work! 

Juanpablos-MacBook-Pro:~ juanpabloramirez$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/juanpabloramirez/anaconda  (writable)
    default environment : /Users/juanpabloramirez/anaconda
       envs directories : /Users/juanpabloramirez/anaconda/envs
          package cache : /Users/juanpabloramirez/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/cc/osx-64
                          https://conda.anaconda.org/cc/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forg/osx-64
                          https://conda.anaconda.org/conda-forg/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/juanpabloramirez/.condarc
           offline mode : False

Juanpablos-MacBook-Pro:~ juanpabloramirez$

**Comment by goanpeca** [comment]
@natathon you a typo. you have a channel named conda-forg. Just remove that from thw config.

**Comment by akuardit** [comment]
happen to me to, but its ssl ... 

[akuardit.atn-zenbook] ➤ conda update conda
Fetching package metadata ...

CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)


[akuardit.atn-zenbook] ➤ conda info
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : D:\dev\Anaconda3  (writable)
    default environment : D:\dev\Anaconda3
       envs directories : D:\dev\Anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\DOCUME~1\MOBAXT~1\home\.conda\envs
          package cache : D:\dev\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
            config file : C:\Users\user\DOCUME~1\MOBAXT~1\home\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

**Comment by goanpeca** [comment]
@akuardit its a different error

**Comment by akuardit** [comment]
@goanpeca any help about my-case? or should i make a new issue? cause its happen even when i used miniconda, does it happen cause i use windows 10?

**Comment by goanpeca** [comment]
@akuardit yes please open a new issue :-)

**Comment by Natathon** [comment]
@goanpeca thank you so much! It worked!

**Comment by prachiichandak** [comment]
I had similar problem while updating conda.
![image](https://user-images.githubusercontent.com/30116022/28116289-241e36fc-6726-11e7-9ed5-79afd6bc7799.png)

**Comment by akuardit** [comment]
Its solved, please check this... https://github.com/conda/conda/issues/4930
