### ISSUE TITLE
Prevent package installs in the root environment

### ISSUE THREAD

**Issue by nelson-liu** [conda/conda#4929]
Hi,
When I used to use `virtualenv` I was a big fan of using the `PIP_REQUIRE_VIRTUALENV` flag, which stipulates that any `pip install` commands _must_ be run in a virtualenv in order to work. The rationale for this was to avoid polluting the global package space.

Too often, I find myself absentmindedly forgetting to activate my conda environment and `{pip|conda} install`ing something. It'd be great to have a similar flag in conda to prevent this from happening, and block me from installing packages in the root environment.

Alternatively, it'd be great to know of a way to reset the root environment to the default state (I couldn't find anything solving this when i looked online), to quickly clean up the global package space without `{pip|conda} uninstall`ing every single package.

Thanks! Conda has been great for me, but this is a big feature (to me) that I sorely miss from my old virtualenv/pip setup

**Comment by kalefranz** [comment]
I appreciate this feature request.  I think it's a great idea.  We'll keep it in mind..

**Comment by H0R5E** [comment]
I think this is a great idea, particularly because I have noticed that environments used on Windows seem to be able to pick up packages in the root environment sometimes. This has caused me a lot of confusion when I have inadvertently installed something to the root environment which I did not intend to.

Could it be extended to prevent setuptools installs as well?

**Comment by kalefranz** [comment]
possibly related: https://github.com/conda/conda/issues/4943

**Comment by scottdraves** [comment]
totally wish for this feature.

**Comment by msarahan** [comment]
You might be interested in the standalone executables: https://repo.anaconda.com/pkgs/misc/conda-execs/

**Comment by scottdraves** [comment]
please re-open, still valid afaik

**Comment by jaimergp** [comment]
See https://github.com/conda/conda/issues/4943#issuecomment-3035649173
