### ISSUE TITLE
Validate channel when adding to config

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#4934]
Adding a validation step before actually adding a channel in the config (or even validating channels as a first step of reading the config in case it was updated manually) would avoid simple errors like https://github.com/conda/conda/issues/4926

I would like to work on this @kalefranz

**Comment by kalefranz** [comment]
Implementation of this PR would require within the `# prepend, append, add` section of `cli/main_config.py` that, if the key is `channels`, do something like

```python
channel = Channel(item)
session = CondaSession()
response = session.head(join_url(channel.base_url, 'noarch', 'repodata.json'))
response.raise_for_status()
```

we would need to make sure

1. proxy servers, including proxy servers requiring auth, are properly handled
2. remote servers requiring various types of auth that conda general supports (e.g. HTTP Basic Auth) are properly supported
3. If `context.offline == True` and `channel.scheme != 'file'`, we also skip validation.

I think we need more community discussion before we add an http request to `--set`, `--add`, `--append`, or `--prepend` commands on `conda config`.

In the meantime, I think there are two more immediate steps we can take.

First, we can add the above logic to `conda config --validate`.  For now though, I'd want to confine any addition here to `cli/main_config.py`.  We can refactor to different parts of the code later.

In this case, the logic would be something like

```python
session = CondaSession()
for chn in context.channels:
    channel = Channel(chn)
    response = session.head(join_url(channel.base_url, 'noarch', 'repodata.json'))
    response.raise_for_status()
```

Second, we can discuss changing the default value of `context.allow_non_channel_urls` from `True` to `False`.  The area of code affected by this config is [here](https://github.com/conda/conda/blob/4.3.15/conda/core/repodata.py#L164-L242).  It is related to #3739 and #4238.

**Comment by goanpeca** [comment]
Thanks for all the info @kalefranz I was not aware of all the implications, but happy to help :-)
