### ISSUE TITLE
An unexpected error has occurred when tried to "conda - conda update"

### ISSUE THREAD

**Issue by Fomyther** [conda/conda#4937]
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 1.19.0
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : /Users/CQ/anaconda  (writable)
    default environment : /Users/CQ/anaconda
       envs directories : /Users/CQ/anaconda/envs
                          /Users/CQ/.conda/envs
          package cache : /Users/CQ/anaconda/pkgs
                          /Users/CQ/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.12 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`$ /Users/CQ/anaconda/bin/conda - conda update`

    Traceback (most recent call last):
      File "/Users/CQ/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/CQ/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 119, in _main
        args = p.parse_args(args)
      File "/Users/CQ/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "/Users/CQ/anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/Users/CQ/anaconda/lib/python2.7/argparse.py", line 1740, in parse_known_args
        self.error(str(err))
      File "/Users/CQ/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by tku95309** [comment]
I have the same problem......
![default](https://cloud.githubusercontent.com/assets/26673830/24323087/6eadcaa0-11ab-11e7-99f6-6c9e1768595a.JPG)

**Comment by kalefranz** [comment]
Already fixed.  `conda update conda`
