### ISSUE TITLE
Can't track down source of dependency with -vvv

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4942]
I have a set of packages I'm installing.  One of my goals is to NOT install QT.  I have tried to remove every package I can think of that has a QT dependency, however when I go and do

```
conda create -n core --file anaconda_core.txt
```

QT is still pulled in.  I've tried adding `-vvv` debug options but these provide no insights as to where the QT dependency is coming from.

I logging this as a bug because I feel like that information should be visible in the debug output.

Here is the file I use for the `--file` option, in case it is useful.

[anaconda_core.txt](https://github.com/conda/conda/files/870017/anaconda_core.txt)

**Comment by ijstokes** [comment]
FWIW, I figured this out myself through the somewhat laborious process of doing:

`grep qt ~/anaconda/pkgs/*/info/index.json`

where I discovered that `jupyter` (I should have guessed) is the meta-package that includes `qtconsole` as a dependency and (because we don't yet have optional deps) `matplotlib` includes `pyqt`

But it would have been nice to get this information as part of the output of `conda` with the `-vvv` debug options.  The form I'd love this to take would be something like:

    REQUIRED -> BECAUSE -> A, B, C

**Comment by goanpeca** [comment]
@kalefranz I am bumping all enhancements/features to 4.4.0 milestone but maybe 4.5 or even 5.x make more sense.

**Comment by kalefranz** [comment]
For the conda 4.4 code, there's now

    /path/to/condas/bin/python -m conda.models.dag /path/to/environment/you/want/to/visualize

It makes a graphviz graph of your environment, and opens it in a browser for you.  The code isn't ready for prime-time yet, but it's a start.
