### ISSUE TITLE
conda update --all creates update loop

### ISSUE THREAD

**Issue by fredcascarini** [conda/conda#4949]
Starting from a fresh install of anaconda 4.3.1 using python 2.7,  `conda update --all` results in an upgrade of a list of packages, coupled with an upgrade to anaconda custom-py27_0
After this update is run `conda update --all` then suggests an update of anaconda custom-py27_0 back to 4.3.1-np111py27_0, along with a downgrade of all the upgraded packages. This loop appears to continue if the downgrade is run.

Is there a fix for this loop?

Other information:

OS: 
Windows 7 Enterprise SP1

conda info:
`platform : win-64`
`conda version : 4.3.14`
`conda is private : False`
`conda-env version : 4.3.14`
`conda-build version : not installed`
`python version : 2.7.13.final.0`
`requests version : 2.13.0`
`root environment : c:\ProgramData\Anaconda2  (read only)`
`default environment : c:\ProgramData\Anaconda2`
`envs directories : c:\ProgramData\Anaconda2\envs`
`                          C:\Users\[username]\AppData\Local\conda\conda\envs`
`                          C:\MinGW\msys\1.0\home\[username]\.conda\envs`
`package cache : c:\ProgramData\Anaconda2\pkgs`
`                          C:\Users\[username]\AppData\Local\conda\conda\pkgs`
`channel URLs : https://repo.continuum.io/pkgs/free/win-64`
`                          https://repo.continuum.io/pkgs/free/noarch`
`                          https://repo.continuum.io/pkgs/r/win-64`
`                          https://repo.continuum.io/pkgs/r/noarch`
`                          https://repo.continuum.io/pkgs/pro/win-64`
`                          https://repo.continuum.io/pkgs/pro/noarch`
`                          https://repo.continuum.io/pkgs/msys2/win-64`
`                          https://repo.continuum.io/pkgs/msys2/noarch`
`config file : C:\MinGW\msys\1.0\home\[username]\.condarc`
`offline mode : False`
`user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.13 Windows/7 Windows/6.1.7601`

**Comment by mingzihan** [comment]
I have the same question as you, have you solved it?

**Comment by kalefranz** [comment]
Can this be reproduced in recent versions of conda?  Latest release is conda 4.4.11.
