### ISSUE TITLE
conda update conda failed ;  [Errno 13] Permission denied

### ISSUE THREAD

**Issue by paulyuatgithub** [conda/conda#4950]
When updating conda on Mac 10.10.5, and y for update all, the update failed.
Now, the conda command cannot be found.

Kindly let me know how to fix it.
Thanks a lot.
Paul

PaultekiMacBook-Pro:~ paulyu$ conda -V
conda 3.19.1
PaultekiMacBook-Pro:~ paulyu$ conda update conda
Fetching package metadata: ....
Solving package specifications: ....................
Package plan for installation in environment /Users/paulyu/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    openssl-1.0.2k             |                1         3.0 MB
    sqlite-3.13.0              |                0         1.4 MB
    xz-5.2.2                   |                1         212 KB
    zlib-1.2.8                 |                3          89 KB
    python-3.4.5               |                0        11.0 MB
    idna-2.2                   |           py34_0         124 KB
    pyasn1-0.2.3               |           py34_0          79 KB
    pycosat-0.6.2              |           py34_0          97 KB
    pycparser-2.17             |           py34_0         157 KB
    requests-2.13.0            |           py34_0         814 KB
    ruamel_yaml-0.11.14        |           py34_1         198 KB
    setuptools-27.2.0          |           py34_0         528 KB
    six-1.10.0                 |           py34_0          17 KB
    cffi-1.9.1                 |           py34_0         197 KB
    pip-9.0.1                  |           py34_1         1.7 MB
    cryptography-1.7.1         |           py34_0         480 KB
    pyopenssl-16.2.0           |           py34_0          70 KB
    conda-4.3.14               |           py34_0         508 KB
    ------------------------------------------------------------
                                           Total:        20.5 MB

The following NEW packages will be INSTALLED:

    ruamel_yaml:  0.11.14-py34_1

The following packages will be UPDATED:

    cffi:         1.1.0-py34_0  --> 1.9.1-py34_0  
    conda:        3.19.1-py34_0 --> 4.3.14-py34_0 
    conda-env:    2.4.5-py34_0  --> 2.6.0-0       
    cryptography: 0.9.1-py34_0  --> 1.7.1-py34_0  
    idna:         2.0-py34_0    --> 2.2-py34_0    
    openssl:      1.0.2f-0      --> 1.0.2k-1      
    pip:          8.0.2-py34_0  --> 9.0.1-py34_1  
    pyasn1:       0.1.7-py34_0  --> 0.2.3-py34_0  
    pycosat:      0.6.1-py34_0  --> 0.6.2-py34_0  
    pycparser:    2.14-py34_0   --> 2.17-py34_0   
    pyopenssl:    0.15.1-py34_1 --> 16.2.0-py34_0 
    python:       3.4.4-0       --> 3.4.5-0       
    requests:     2.9.1-py34_0  --> 2.13.0-py34_0 
    setuptools:   19.6.2-py34_0 --> 27.2.0-py34_0 
    six:          1.9.0-py34_0  --> 1.10.0-py34_0 
    sqlite:       3.9.2-0       --> 3.13.0-0      
    xz:           5.0.5-1       --> 5.2.2-1       
    zlib:         1.2.8-0       --> 1.2.8-3       

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 534.29 kB/s
openssl-1.0.2k 100% |################################| Time: 0:00:01   1.80 MB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:00   9.23 MB/s
xz-5.2.2-1.tar 100% |################################| Time: 0:00:00   4.66 MB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00   3.90 MB/s
python-3.4.5-0 100% |################################| Time: 0:02:53  66.19 kB/s
idna-2.2-py34_ 100% |################################| Time: 0:00:00 160.57 kB/s
pyasn1-0.2.3-p 100% |################################| Time: 0:00:01  66.18 kB/s
pycosat-0.6.2- 100% |################################| Time: 0:00:00 241.92 kB/s
pycparser-2.17 100% |################################| Time: 0:00:00   5.28 MB/s
requests-2.13. 100% |################################| Time: 0:00:01 538.79 kB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:01 179.79 kB/s
setuptools-27. 100% |################################| Time: 0:00:01 482.48 kB/s
six-1.10.0-py3 100% |################################| Time: 0:00:00   3.25 MB/s
cffi-1.9.1-py3 100% |################################| Time: 0:00:04  46.76 kB/s
pip-9.0.1-py34 100% |################################| Time: 0:00:00   6.56 MB/s
cryptography-1 100% |################################| Time: 0:00:00   5.27 MB/s
pyopenssl-16.2 100% |################################| Time: 0:00:00 312.19 kB/s
conda-4.3.14-p 100% |################################| Time: 0:00:03 136.28 kB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  36%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/paulyu/anaconda/bin/conda", line 5, in <module>
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 173, in main
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 180, in args_func
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 48, in execute
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 423, in install
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/plan.py", line 538, in execute_actions
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 91, in LINK_CMD
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 87, in link
  File "/Users/paulyu/anaconda/lib/python3.4/site-packages/conda/install.py", line 616, in link
  File "/Users/paulyu/anaconda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/paulyu/anaconda/lib/python3.4/site-packages/pyasn1/codec/native'
PaultekiMacBook-Pro:~ paulyu$ conda update conda
-bash: /Users/paulyu/anaconda/bin/conda: No such file or directory

**Comment by kalefranz** [comment]
Permissions error in 3.19.1.  Fixed in conda 4.3.  To recover, you might have to run a new miniconda installer over your current installation.
