### ISSUE TITLE
miniconda/anaconda installers for tcsh and sh (bourne shell)

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda#4951]
There are still people who use `tsch` or `sh` as login, and many times they are not even aware.

It would be nice if the default installers, for example Miniconda ones (https://conda.io/miniconda.html), would detect the shell environment and suggest the appropriate login profile. For example, in bourne shell it's `~/.profile` and tsch it's `~/.tcshrc`.

I could modify that part of the code myself and do a pull request, but I can't find the source of the installers anywhere in here. Are they available here or somewhere else? Google did not help me much either.

Thanks,
João

**Comment by goanpeca** [comment]
@j3mdamas maybe https://github.com/ContinuumIO/anaconda-issues/issues is the right repo for this.

**Comment by j3mdamas** [comment]
Thanks!
