### ISSUE TITLE
error conda install numpy

### ISSUE THREAD

**Issue by adri8112** [conda/conda#4953]
The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.9.1                 |           py34_0   hard-link
    conda-4.3.14               |           py34_1   hard-link
    conda-env-2.6.0            |                0   hard-link
    cryptography-1.7.1         |           py34_0   hard-link
    idna-2.2                   |           py34_0   hard-link
    mkl-2017.0.1               |                0   hard-link
    numpy-1.11.3               |           py34_0   hard-link
    openssl-1.0.2k             |           vc10_0   hard-link
    pyasn1-0.2.3               |           py34_0   hard-link
    pycparser-2.17             |           py34_0   hard-link
    pyopenssl-16.2.0           |           py34_0   hard-link
    pywin32-220                |           py34_2   hard-link
    requests-2.13.0            |           py34_0   hard-link
    ruamel_yaml-0.11.14        |           py34_1   hard-link
    setuptools-27.2.0          |           py34_1   hard-link
    six-1.10.0                 |           py34_0   hard-link
    vs2010_runtime-10.00.40219.1|                2   hard-link

WARNING: the process C:\pyzo2014a\pyzo.exe (11348) is running
WARNING: Continuing installation while the above processes are running is
not recommended.  Please, close all Anaconda programs before installing or
updating things with conda.

Continue (yes/no/force) (y/[n]/f)? f

Fetching packages ...

download 

Extracting packages ...
 |                                                                       |   0%
[cffi                ] |##                                               |   5%
[conda               ] |#####                                            |  11%
[conda-env           ] |########                                         |  17%
[cryptography        ] |###########                                      |  23%
[idna                ] |##############                                   |  29%
[mkl                 ] |#################                                |  35%
[numpy               ] |####################                             |  41%
[openssl             ] |#######################                          |  47%
[pyasn1              ] |#########################                        |  52%
[pycparser           ] |############################                     |  58%
[pyopenssl           ] |###############################                  |  64%
[pywin32             ] |##################################               |  70%
[requests            ] |#####################################            |  76%
[ruamel_yaml         ] |########################################         |  82%
[setuptools          ] |###########################################      |  88%
[six                 ] |##############################################   |  94%
[vs2010_runtime      ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |                                                 |   0%
[conda               ] |#########                                        |  20%
[numpy               ] |###################                              |  40%
[requests            ] |#############################                    |  60%
[setuptools          ] |#######################################          |  80%
[six                 ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |                                                 |   0%
[cffi                ] |##                                               |   5%
[conda               ] |#####                                            |  11%
[conda-env           ] |########                                         |  17%
[cryptography        ] |###########                                      |  23%
[idna                ] |##############                                   |  29%
[mkl                 ] |#################                                |  35%
[numpy               ] |####################                             |  41%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Error in conda command:
[Errno 22] Invalid argument: 'C:\\pyzo2014a\\"Lib\\site-packages\\numpy\\__config__.py"'

In [1]: conda info
Current conda install:

             platform : win-64
        conda version : 3.5.5
       python version : 3.4.1.final.0
     root environment : C:\pyzo2014a  (writable)
  default environment : C:\pyzo2014a
     envs directories : C:\pyzo2014a\envs
        package cache : C:\pyzo2014a\pkgs
         channel URLs : http://conda.binstar.org/pyzo/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\pyzo2014a\.condarc
    is foreign system : False

**Comment by goanpeca** [comment]
Please update to the latest version of conda:

On the Anaconda prompt type:

`conda update conda`

**Comment by goanpeca** [comment]
Closing for lack of response
