### ISSUE TITLE
Inconsistent dependency resolution

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#4955]
Hello,

If you do:
```
conda create --dry-run -n pysam pysam
```

you get `htslib-1.3.2-0` which is expected as requested in the `pysam` recipe:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pysam/meta.yaml#L21

However, if you install `cgat-scripts-devel` which has `pysam` as dependency:
```
conda create --dry-run -n cgat cgat-scripts-devel 
```

you get `htslib-1.4-0` which contradicts the requirements of `pysam`.

Can you please explain why?

Here is the `.condarc`:
```
allow_softlinks: false

channels:
  - bioconda
  - r
  - defaults
  - conda-forge
```

Here is `conda info`:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : /sebastian/conda/conda3-install/i6  (writable)
    default environment : /sebastian/conda/conda3-install/i6
       envs directories : /sebastian/conda/conda3-install/i6/envs
                          /ifs/home/sebastian/.conda/envs
          package cache : /sebastian/conda/conda3-install/i6/pkgs
                          /ifs/home/sebastian/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /ifs/home/sebastian/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.13.0 CPython/3.6.1 Linux/2.6.32-642.15.1.el6.x86_64 Scientific Linux/6.8 glibc/2.12
                UID:GID : 1362:1000
```

**Comment by sebastian-luna-valero** [comment]
For my own reference.

Travis:
https://travis-ci.org/CGATOxford/cgat/builds/216298600

GitHub:
https://github.com/CGATOxford/cgat/pull/322

**Comment by sebastian-luna-valero** [comment]
And forgot to say, many thanks for looking into the issue!

**Comment by ma-ba** [comment]
`pysam`'s recipe on bioconda has only recently been updated to include the version restriction for `htslib`, see https://github.com/bioconda/bioconda-recipes/pull/4235/files. Thus a previous build (`pysam-0.10.0-py35_2`) without the restriction is still available and gets picked up when installing `cgat-scripts-devel`.
Notice the different build numbers (`_2` vs `_3`):
```bash
$ conda create -n env -c bioconda --dry-run --json cgat-scripts-devel | grep pysam-
          "dist_name": "pysam-0.10.0-py35_2",
```
```bash
$ conda create -n env -c bioconda --dry-run --json pysam | grep pysam-
          "dist_name": "pysam-0.10.0-py35_3",
```

**Comment by sebastian-luna-valero** [comment]
Thanks @ma-ba !

Having into account that `cgat-scripts-devel` requires the latest version of `pysam`:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cgat-scripts-devel/meta.yaml#L43

Why do I get `_2` instead of `_3` when doing:
```
$ conda create -n env -c bioconda --dry-run --json cgat-scripts-devel | grep pysam-
```

**Comment by sebastian-luna-valero** [comment]
Hello,

Could you please let me know if you have any progress on this?

Best regards,
Sebastian

**Comment by ma-ba** [comment]
Over at #4956 there was some (as I see it, not yet conclusive) discussion on the issue of previous builds being picked up. Maybe @mcg1969 could tell you why exactly you got different builds or at least which workaround is currently advised.

**Comment by mcg1969** [comment]
It's not clear to me this is a bug. @mbargull is right, conda considers all of the packages made available to it, including possibly older builds. conda is producing an environment that is consistent. The older `pysam` builds either need to be pulled or corrected.

**Comment by sebastian-luna-valero** [comment]
Thanks for getting back to me. I have just rerun my commands above with and it's working now so I will close the issue. Not sure why it did happen in the first instance. Below is the output for future reference.
```
$ conda-install/bin/conda create -n env -c bioconda --dry-run --json cgat-scripts-devel | grep pysam-
          "dist_name": "pysam-0.11.2.1-py35_0",

$ conda-install/bin/conda create -n env -c bioconda --dry-run --json pysam | grep pysam-             
          "dist_name": "pysam-0.11.2.1-py36_0",

$ conda-install/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /tmp/conda/conda-install  (writable)
    default environment : /tmp/conda/conda-install
       envs directories : /tmp/conda/conda-install/envs
                          /ifs/home/sebastian/.conda/envs
          package cache : /tmp/conda/conda-install/pkgs
                          /ifs/home/sebastian/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /ifs/home/sebastian/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Linux/2.6.32-696.1.1.el6.x86_64 Scientific Linux/6.9 glibc/2.12
                UID:GID : 1362:1000

```

**Comment by mbargull** [comment]
It's working this time because `pysam` now has a higher version number and thus possibly gets more prioritized by the solver.
The issue still stands that older faulty build need to be ignored (the `conda` issue) or pulled from the repository (which makes it a `bioconda` issue).
Re: the `conda` issue: Currently there is no functionality on the repository side to mark builds as defunct or superseded which only leaves the resolution given by @mcg1969: those builds need to be removed from the repository. For more details on that, see #4956 and @mcg1969's Gist at https://gist.github.com/mcg1969/38589eeefb046c417720f1027f97085b.

To still reproduce the issue, see:
```bash
$ conda create -n env -c bioconda --dry-run htslib 'pysam<0.11'
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/maba/miniconda3/envs/env:

The following NEW packages will be INSTALLED:

    bcftools:   1.4.1-0       bioconda
    bzip2:      1.0.6-3               
    curl:       7.52.1-0              
    htslib:     1.4.1-0       bioconda
    libgcc:     5.2.0-0               
    openssl:    1.0.2k-2              
    pip:        9.0.1-py35_1          
    pysam:      0.10.0-py35_2 bioconda
    python:     3.5.3-1               
    readline:   6.2-2                 
    samtools:   1.4.1-0       bioconda
    setuptools: 27.2.0-py35_0         
    sqlite:     3.13.0-0              
    tk:         8.5.18-0              
    wheel:      0.29.0-py35_0         
    xz:         5.2.2-1               
    zlib:       1.2.8-3               
```
If `htslib` is one of the explicitly requested packages, `conda` tries to maximize its version and thus picks up `htslib-1.4.1-0` but also `pysam-0.10.0-py35_2`. This `pysam` build is faulty in that it should require `htslib >=1.3,<1.4` but only requires `htslib >=1.3`. Outcome: The above command will install a non-functional `pysam` package.
```bash
$ conda create -n env -c bioconda --dry-run 'pysam<0.11'
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/maba/miniconda3/envs/env:

The following NEW packages will be INSTALLED:

    bcftools:   1.3.1-1       bioconda
    curl:       7.52.1-0              
    htslib:     1.3.2-0       bioconda
    libgcc:     5.2.0-0               
    openssl:    1.0.2k-2              
    pip:        9.0.1-py36_1          
    pysam:      0.10.0-py36_3 bioconda
    python:     3.6.1-2               
    readline:   6.2-2                 
    samtools:   1.3.1-5       bioconda
    setuptools: 27.2.0-py36_0         
    sqlite:     3.13.0-0              
    tk:         8.5.18-0              
    wheel:      0.29.0-py36_0         
    xz:         5.2.2-1               
    zlib:       1.2.8-3               
```
It `htslib` is not explicitly requested, only `pysam`'s version (including its build number) gets maximized so that `pysam-0.10.0-py36_3` can be used.

I am going to file an accompanying issue @bioconda.

**Comment by sebastian-luna-valero** [comment]
Many thanks @mbargull

**Comment by mcg1969** [comment]
> The older fauly build should be ignored.

I'm afraid it's not that simple. Any package that conda "sees" is considered. So either the faulty build should be pulled from the channel or its metadata must be correctead.

**Comment by mcg1969** [comment]
Believe me, I'm well aware that this causes undesirable behavior in situations like this---if you search the GitHub issues for "metadata hotfix" you'll see we go through some serious gymnastics to work through this.

**Comment by mbargull** [comment]
Of course, I understand the underlying issue (that's why I linked the other issue and your Gist) and feel your pain 😉.
