### ISSUE TITLE
Win 10 and Anaconda 4.3.1 issue - does not run

### ISSUE THREAD

**Issue by tolyla25** [conda/conda#4959]
I have installed the latest 64-bit version of Anaconda 4.3.1 on my Win 10 laptop. I installed it running as an Admin

The installation was successful. However, when I tried to launch Notebook from the dashboard of the navigator NOTHING happened. Nothing got launched. No error.

I went back to 64-bit 4.0.0 version. I did get started (launched) but quickly generated a system error

Can you help to get 4.3.1 running on Win 10?

I have 12Gb of RAM and plenty of HDD space. Antivirus was disabled

**Comment by goanpeca** [comment]
@tolyla25 I advice you to install as the current user and not for all users.

**Comment by tolyla25** [comment]
I installed it for 1 user only

**Comment by goanpeca** [comment]
`I have installed the latest 64-bit version of Anaconda 4.3.1 on my Win 10 laptop. I installed it running as an Admin`

You dont need to do that if you had installed for the current user

**Comment by tolyla25** [comment]
I still have the same issue

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1678
