### ISSUE TITLE
PEP440 and local version identifiers

### ISSUE THREAD

**Issue by tonigi** [conda/conda#4962]
I've got packages with local version identifiers, but the conda install command may not handle version precedence according to PEP440. In particular

    >>> from packaging.version import Version, parse
    >>> parse("2.3.0+htmd4") > parse("2.3.0")
    True  # This follows PEP440

while conda install prefers version 2.3.0 to 2.3.0+htmd4.

**Comment by kalefranz** [comment]
Conda is close to PEP440, but not exact.  These are all explicit design decisions, with I think the most time spent by @ukoethe thinking through all these issues and corner cases.  For conda and the behavior you're looking for, use `.post` from PEP440 instead of `+`.
