### ISSUE TITLE
Python yt installation

### ISSUE THREAD

**Issue by schned** [conda/conda#4967]
I am trying to learn to do scientific visualizations in Python and I am attempting to install the yt package, but I've run into issues when I use "conda install yt". I have Miniconda installed which I have already used to install astropy. Every time I try to install yt using conda, I get this error:
"C:\Users\Miniconda3\Library\bin>conda install yt
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - yt -> numpy 1.8* -> python 2.6*
Use "conda info <package>" to see the dependencies for each package."

I have look around and tried to figure out what's going on. On the yt project website, they say that using Miniconda should work and I can't figure out why it won't install. I have a windows 64x system, running windows 10. Can someone help me or point me toward an answer that will help me?

**Comment by kalefranz** [comment]
yt is not built for python 3.6

    conda create -n my-yt-env python=2.7 yt
    activate my-yt-env
