### ISSUE TITLE
Error in DirectoryNotFoundError

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#4969]
Commit 1f430607 has broken the class DirectoryNotFoundError. Example to trigger the code path calling DirectoryNotFoundError():

    (root) [root@833f44c1b4d6 ~]# conda create -n starlord --clone /path/to/vanishing/point

Current conda install:

               platform : linux-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /conda  (writable)
    default environment : /conda
       envs directories : /conda/envs
                          /root/.conda/envs
          package cache : /conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.15 requests/2.12.4 CPython/3.6.0 Linux/4.8.6-300.fc25.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 0:0

`$ /conda/bin/conda create -n starlord --clone /path/to/vanishing/point`

    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/conda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/conda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/conda/lib/python3.6/site-packages/conda/cli/install.py", line 212, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/conda/lib/python3.6/site-packages/conda/cli/install.py", line 57, in clone
        raise DirectoryNotFoundError(src_arg, 'no such directory: %s' % src_arg, json)
    TypeError: __init__() takes 2 positional arguments but 4 were given

**Comment by kalefranz** [comment]
Thanks Nehal.

**Comment by kalefranz** [comment]
@tyler-thetyrant Can you take this one?

**Comment by tyler-thetyrant** [comment]
@kalefranz Yup. Looking into it.
