### ISSUE TITLE
Error in conda install java-jdk8.0.92-1 

### ISSUE THREAD

**Issue by learnyoung1990** [conda/conda#4970]
I instal miniconda and add channels bioconda. I want to use conda install  software fastqc ,it depend on java-jdk, but I can't install the java-jdk. the conda show this below:

[tzhangqihao@cluster ~]$ conda install fastqc
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /public/users/tzhangqihao/miniconda2:

The following NEW packages will be INSTALLED:

    fastqc:   0.11.5-1 bioconda
    java-jdk: 8.0.92-1 bioconda

Proceed ([y]/n)? y

yjava-jdk-8.0.9   0% |                                                                                                                          | ETA:  --:--:--   0.00  B/java-jdk-8.0.9 100% |###########################################################################################################################| Time: 0:02:59 715.39 kB/s
java-jdk-8.0.9 100% |###########################################################################################################################| Time: 0:01:39   1.29 MB/s

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/bioconda/linux-64/java-jdk-8.0.92-1.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/bioconda/linux-64/java-jdk-8.0.92-1.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/bioconda/linux-64/java-jdk-8.0.92-1.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by kalefranz** [comment]
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
