### ISSUE TITLE
conda remove does not check for breaking dependencies of other pkgs

### ISSUE THREAD

**Issue by marscher** [conda/conda#4972]
eg. conda remove numpy (ok, this is a stupid example), would break all packages depending on numpy in this environment. I just wonder, if there is some check preventing this.

conda version 4.3.15:

```
$ conda list|grep np112 |wc -l
10
#####
$ conda remove numpy 
Fetching package metadata .............
Solving package specifications: .

Package plan for package removal in environment /home/marscher/anaconda:

The following packages will be REMOVED:

    numpy: 1.12.0-py27_blas_openblas_200 conda-forge [blas_openblas]

Proceed ([y]/n)? n

Exiting
```

I think this would also be the key to solve #62.

**Comment by marscher** [comment]
I can only reproduce this in the root environment, but not in a separate env.

**Comment by marscher** [comment]
[root_env.txt](https://github.com/conda/conda/files/883491/root_env.txt)

**Comment by kalefranz** [comment]
Can you provide the output of `conda list` and `conda info`, and then attach the full output of

    conda remove numpy -vvv

For that last one, just go up to the confirmation step (where you choose 'no').

**Comment by marscher** [comment]
will do, I can only reproduce this on this particular system, which I 
don't have access to right now. So this is probably just one very 
strange (and rare) side condition.
