### ISSUE TITLE
Anybody have a better strategy to manage your R packages using conda-build?

### ISSUE THREAD

**Issue by alfredzj** [conda/conda#4973]
I figure out a way to manage python and r packages, and I am wondering whether there is a better way to do that?

This is what I concluded.
https://github.com/alfredzj/Documentations/blob/master/anaconda-set-up.md

And I am wondering why the packages that I install using ```conda-build``` does not show in the screen when I type ```conda list```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1991
