### ISSUE TITLE
can't activate environment

### ISSUE THREAD

**Issue by kaare-mikkelsen** [conda/conda#4977]
In win 10, after having added graphviz\bin to the path:

> activate py35_custom
\graphviz\bin"" was unexpected at this time.

I then get a very long print of what looks like the entire path. 
The problem disappears when I remove graphviz\bin from the path again. I tried cleaning up the path a bit, removing some other directories that weren't needed, but re-adding graphviz made the problem reappear.

My anaconda version:

> conda -V
conda 4.3.14

**Comment by wulmer** [comment]
Might it be that you have multiple quotes in your `%PATH%` variable? Make sure that you don't have any quotes in the variable, as they aren't necessary even if some paths contain whitespaces.

**Comment by kaare-mikkelsen** [comment]
the path was edited by using the windows gui (control panel -> edit system variables -> environment variables), so it seems unlikely to be done incorrectly. how would you suggest checking that?

**Comment by wulmer** [comment]
Open a command shell and enter `echo %PATH%`. This shows you the effective PATH environment variable (containing system and user paths). There shouldn't be any quotes in this output!

**Comment by kaare-mikkelsen** [comment]
the problem has changed to being intermittent now (it disappeared, but after removing and adding graphviz a bunch of times, the problem seems to reappear occasionally). it seems that the gui does in fact add some quotes occasionally. it's possible that it has something to do with how much the gui is closed. 

anyway, problem seems to be solved, was not related to conda.
