### ISSUE TITLE
Anaconda3 not launching

### ISSUE THREAD

**Issue by JBCoded** [conda/conda#4980]
So I downloaded Anaconda 3.6 (newest version on Continuum site), and installed it. However, when I try to launch Navigator (or anything other that Anaconda Prompt), nothing happens. I tried to uninstall and reinstall to see if that would fix the issue, but didn't. So I looked up in google to find a solution and found many suggesting that it's a problem with qt. I found my conda run, but even that won't stay open, so I used Anaconda Prompt and used the conda install command to install qt, but this came back with an error stating line 5 column0 YMAL. I've even downloaded qt4 folders and put them into the include folder for Anaconda3 and the Library, and still nothing. Any help would be appreciated. Oh and I should note that while I'm not computer illiterate, I'm not 100% great at knowing everything on command prompt and all

**Comment by goanpeca** [comment]
@JBCoded could you open an issue over https://github.com/ContinuumIO/anaconda-issues/issues, and add over there the output of running on the anaconda-prompt the following commands:

`conda info`

and 

`conda list`
