### ISSUE TITLE
Installing anaconda to Ubuntu 16.04.2 64-bit

### ISSUE THREAD

**Issue by JediGex** [conda/conda#4983]
In the middle of the anaconda installation I receive the following error:

creating default environment...
/anaconda3/bin/.openssl-libcrypto-fix: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
Error: post-link failed for: openssl-1.0.2k-1

Any thoughts on this issue?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1576
