### ISSUE TITLE
--yes not functioning for "Clean"

### ISSUE THREAD

**Issue by jrking123** [conda/conda#4986]
Hi, either `conda clean -y --all` or `conda clean --yes --all` still prompt for a confirmation. 

conda 4.2.13
macOS 10.12.4

**Comment by goanpeca** [comment]
@kalefranz should this be fixed for 4.1 onwards or?

**Comment by cfobel** [comment]
Confirmed here as well.

`conda==4.2.13`  
`Windows 32-bit`

**Comment by kalefranz** [comment]
Probably at least 4.2 onward.

**Comment by kalefranz** [comment]
resolved with #5311 targeting 4.3.x
