### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by kiralyb** [conda/conda#4999]
(phy) c:\Users\Balint\Desktop\phy-data-master>conda env create -n phy
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Miniconda  (writable)
    default environment : C:\Miniconda\envs\phy
       envs directories : C:\Miniconda\envs
                          C:\Users\Balint\AppData\Local\conda\conda\envs
                          C:\Users\Balint\.conda\envs
          package cache : C:\Miniconda\pkgs
                          C:\Users\Balint\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\Miniconda\Scripts\conda-env-script.py create -n phy`

    Traceback (most recent call last):
      File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda\lib\site-packages\conda_env\cli\main_create.py", line 82, in execute
        directory=os.getcwd())
      File "C:\Miniconda\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Invalid name, try the format: user/package
    Please install nbformat:
        conda install nbformat
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by goanpeca** [comment]
@kiralyb you can either create an environment with

`conda create -n phy <some_package> <another_package>`

or 

`conda create environment.yml`

Where `environment.yml` should contain something like

```
name: stats
channels:
  - javascript
dependencies:
  - python=3.4   # or 2.7 if you are feeling nostalgic
  - bokeh=0.9.2
  - numpy=1.9.*
  - nodejs=0.10.*
  - flask
  - pip:
    - Flask-Testing
```
