### ISSUE TITLE
Is there a up-to-date miniconda installer for Linux x86_64?

### ISSUE THREAD

**Issue by hartzell** [conda/conda#5000]
The newest installer [in the repo](https://repo.continuum.io/miniconda/) seems to be for 4.3.11, but I see releases on github up to 4.3.14.

Is there a schedule for an installer?  I can't use the "install 4.3.11 and use conda to update itself" route.

**Thanks!**

**Comment by hartzell** [comment]
**ping?**

**Comment by mingwandroid** [comment]
We do not build a new `Miniconda` (the minimal set of packages needed to run `conda`) for each release on `conda`. Usually we plan to only release on `Miniconda` per release of `Anaconda Distribution` but sometimes issues force us to release `Miniconda` more frequently.

`conda update conda` will get you the latest `conda`.

**Comment by hartzell** [comment]
> We do not build a new Miniconda (the minimal set of packages needed to run conda) for each release on conda.

Is there a technical reason (a place that I could contribute instead of whining) or is it Policy?

> conda update conda will get you the latest conda

Sadly, that's a total non-starter for folks downstream who are trying to package your tools.

I wouldn't care, except that you seem to have fixed a number of problems with running in a multi-user environment between .11 and .14, our users keep tripping over them and complaining.

Shrugging isn't a very satisfying response.

**Comment by mingwandroid** [comment]
> Is there a technical reason (a place that I could contribute instead of whining) or is it Policy?

`Anaconda` and `Miniconda` are rolling software distributions with fixed checkpointed releases (roughly 4 times a year). Those releases take a *significant* amount of time and time to test, time that would otherwise be spent fixing and improving our packages or adding new ones.

> Sadly, that's a total non-starter for folks downstream who are trying to package your tools.

You can package your own installers as and when you wish. We have an open source tool called `constructor` that you can install via `conda install constructor`. You can read the documentation here: https://github.com/conda/constructor

**Comment by mingwandroid** [comment]
I do have sympathy for your use case around multi user issues by the way. We're not far off the next release though, and that one should have all of those issues put to bed. Pinging @csoja too so that your concern is further noted.

**Comment by hartzell** [comment]
**Thanks!**

My intuition was that most of the effort invested in ensuring that installing release X and then doing `conda update conda` works reliably overlaps with what you'd do to ensure that an updated installer works.

I'll hold my horses and keep pointing the users at my FAQ about it.

**Comment by csoja** [comment]
We are planning to release a Miniconda v4.3.14.  We plan to at a minimum release a version of Miniconda with the same version of conda as is found in Anaconda installer releases.  There is quite a bit of extra work required for a Miniconda release - both building the installers and the testing required on all platforms - and as conda patch releases often come out quite frequently, we cannot release Miniconda as often as conda.  However, you have a good argument for increasing the frequency of our Miniconda releases.  Will a Miniconda with conda v4.3.14 version work for you?

**Comment by hartzell** [comment]
I appreciate (particularly now that I understand it better!) the work you put into the releases.

It's hard for me to discern the release pattern when I look back through the repository, perhaps a useful thing would be to describe the release schedule/policy some where on [the miniconda page](https://conda.io/miniconda.html).  Then everyone's working from the same plan.

> Will a Miniconda with conda v4.3.14 version work for you?

I've done the `conda update conda` process by hand and *believe* that it fixes the issues that I've seen with writability of the shared env/package dirs and interpolation of variables in ~/.condarc files and etc....

I'd be happy to test drive a release candidate if it would be helpful.

**Comment by csoja** [comment]
Thank you for the offer to help test.  I'll plan to send you a link to it when it is available for testing.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1663
