### ISSUE TITLE
When lacking permissions to write, clone message should quote prefix.

### ISSUE THREAD

**Issue by scw** [conda/conda#5006]
When trying to install a new package into a location that the user lacks write permissions (read-only root), conda helpfully suggests cloning the environment into a new location:

```
CondaIOError: IO error: Missing write permissions in: C:\Program Files\Anaconda
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\Program Files\Anaconda'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_deathstar --clone=C:\Program Files\Anaconda\envs\deathstar
```
As shown in the example above, this clone path may include spaces. This will be particularly common on Windows, where a global install will result in files written to Program Files, which a non-administrator user will not be able to write to, and contains spaces. Because the command presents a prefix, it should be quoted to guard against this case.

**Comment by Ahtesham519** [comment]
i got the solution of this problem :
windows 10 64-bit

press shift and right click on the bottom left windows button ,a list log will appear . Run the command prompt(Admin) .there enter the install/update command all works fine .  
enjoy
