### ISSUE TITLE
conda install conda

### ISSUE THREAD

**Issue by iamasifali** [conda/conda#5014]
I am new in python.I have installed anaconda 1.4 version 32 bit.But when i am trying to update the conda by using conda update conda it gives me the following error--
C:\Users\Dell>conda install m2w64 libpython
conda: error: failed to fetch repodata from 'http://repo.continuum.io/pkgs/pro/win-32/'
I can't understan how to get rid from this problem.When i am tring to use "conda install mingw libpython"
it shows me the same error.Please anyone help me to solve this problem...

**Comment by kalefranz** [comment]
The latest version of Anaconda is 4.3.1.  You are about 4 years out of date.  Please use a more recent installer.
