### ISSUE TITLE
Conda upgrade notebook to 5.0 failing

### ISSUE THREAD

**Issue by omarkb93** [conda/conda#5016]
Hello, I'm trying to upgrade to Jupyter notebook 5.0. I receive the following warnings and errors. I'm running windows 10, let me know if any other info would be useful... can anyone help me? I'm not super savy with code at this level.

PS C:\> conda upgrade notebook
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\ProgramData\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    anaconda-custom            |           py36_0          13 KB
    conda-4.3.16               |           py36_0         546 KB
    notebook-5.0.0             |           py36_0         5.4 MB
    ------------------------------------------------------------
                                           Total:         5.9 MB

The following packages will be UPDATED:

    anaconda:  4.3.1-np111py36_0             --> custom-py36_0
    conda:     4.2.13-py36_0     conda-forge --> 4.3.16-py36_0
    notebook:  4.3.1-py36_2                  --> 5.0.0-py36_0

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env: 2.6.0-0           conda-forge --> 2.6.0-0       (copy)

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
WARNING conda.install:rm_fetched(750): File not removed during RM_FETCHED instruction: C:\ProgramData\Anaconda3\pkgs\con
da-env-2.6.0-0.tar.bz2
WARNING conda.install:rm_fetched(755): Directory not removed during RM_FETCHED instruction: C:\ProgramData\Anaconda3\pkg
s\conda-env-2.6.0-0
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00   0.00  B/s
WARNING conda.common.disk:exp_backoff_fn(182): Uncaught backoff with errno 17
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py upgrade notebook`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 456, in download
        exp_backoff_fn(os.rename, pp, dst_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\disk.py", line 165, in exp_backoff_fn
        result = fn(*args, **kwargs)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\ProgramData\\Anaconda3\\pkg
s\\conda-env-2.6.0-0.tar.bz2.part' -> 'C:\\ProgramData\\Anaconda3\\pkgs\\conda-env-2.6.0-0.tar.bz2'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 459, in download
        (pp, dst_path, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not rename 'C:\\ProgramData\\Anaconda3\\pkgs\\conda-env-2.6
.0-0.tar.bz2.part' to 'C:\\ProgramData\\Anaconda3\\pkgs\\conda-env-2.6.0-0.tar.bz2': FileExistsError(17, 'Cannot create
a file when that file already exists')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not rename 'C:\\ProgramData\\A
naconda3\\pkgs\\conda-env-2.6.0-0.tar.bz2.part' to 'C:\\ProgramData\\Anaconda3\\pkgs\\conda-env-2.6.0-0.tar.bz2': FileEx
istsError(17, 'Cannot create a file when that file already exists')

**Comment by kalefranz** [comment]
Can you update to the latest conda and see if the problem is still there?  Latest it 4.3.16.

    conda update conda

**Comment by omarkb93** [comment]
Hmm `conda update conda` is hanging on "unlinking packages"... should I open a separate issue for that?

**Comment by kalefranz** [comment]
Sure.  But if you do, include output of what's happening with the `--debug` flag enabled.

**Comment by drcrook1** [comment]
Where did the conda update conda issue get posted to?
