### ISSUE TITLE
Conda install fails for awsebcli

### ISSUE THREAD

**Issue by robnewman** [conda/conda#5019]
**Environment:** Windows 10 x64
**Python:** 2.7 default, 3.4 in my-env
**CLI:** GitBash

$ conda install -c contango awsebcli
Fetching package metadata .............
Solving package specifications: .
Package plan for installation in environment C:\Anaconda2\envs\<my-env>:
The following NEW packages will be INSTALLED:

    awsebcli:         3.7.7-py34_0  contango
    botocore:         1.4.90-py34_0
    cement:           2.8.2-py34_0  contango
    colorama:         0.3.7-py34_0
    docker-py:        1.7.2-py34_0  contango
    dockerpty:        0.4.1-py34_0  contango
    docopt:           0.6.2-py34_0
    docutils:         0.13.1-py34_0
    jmespath:         0.9.0-py34_0
    pathspec:         0.3.4-py34_0  contango
    python-dateutil:  2.2-py34_0    contango
    pyyaml:           3.12-py34_0
    requests:         2.10.0-py34_0
    semantic_version: 2.5.0-py34_0
    six:              1.10.0-py34_0
    texttable:        0.8.4-py34_0  contango
    websocket-client: 0.37.0-py34_0 contango

Proceed ([y]/n)? y

    colorama-0.3.7 100% |###############################| Time: 0:00:00 587.47 kB/s
    docopt-0.6.2-p 100% |###############################| Time: 0:00:00 831.70 kB/s
    docutils-0.13. 100% |###############################| Time: 0:00:00   1.30 MB/s
    jmespath-0.9.0 100% |###############################| Time: 0:00:00   1.45 MB/s
    pathspec-0.3.4 100% |###############################| Time: 0:00:00 285.77 kB/s
    pyyaml-3.12-py 100% |###############################| Time: 0:00:00 723.05 kB/s
    requests-2.10. 100% |###############################| Time: 0:00:00   1.28 MB/s
    semantic_versi 100% |###############################| Time: 0:00:00   1.04 MB/s
    six-1.10.0-py3 100% |###############################| Time: 0:00:00   1.02 MB/s
    texttable-0.8. 100% |###############################| Time: 0:00:00 671.73 kB/s
    cement-2.8.2-p 100% |###############################| Time: 0:00:00 339.13 kB/s
    dockerpty-0.4. 100% |###############################| Time: 0:00:00 244.54 kB/s
    python-dateuti 100% |###############################| Time: 0:00:00 512.74 kB/s
    websocket-clie 100% |###############################| Time: 0:00:00 681.97 kB/s
   boAn unexpected error has occurred.##############   | Time: 0:00:01   1.48 MB/s`

Please consider posting the following information to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 1.18.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2\envs\<my-env>
       envs directories : C:\Anaconda2\envs
                          C:\Users\<user>\AppData\Local\conda\conda\envs
                          C:\Users\<user>\.conda\envs
          package cache : C:\Anaconda2\pkgs
                          C:\Users\<user>\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/contango/win-64
                          https://conda.anaconda.org/contango/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.12 Windows/10 Windows/10.0.14393`

`$ C:\Anaconda2\Scripts\conda-script.py install -c contango awsebcli`

    Traceback (most recent call last):
      File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
    IOError: [Errno 13] Permission denied: u'C:\\Anaconda2\\envs\\<my-env>\\Scripts\\conda'

    botocore-1.4.9 100% |###############################| Time: 0:00:01   1.49 MB/s
    docker-py-1.7. 100% |###############################| Time: 0:00:00 261.34 kB/s
    awsebcli-3.7.7 100% |###############################| Time: 0:00:00 523.56 kB/s

**Comment by kalefranz** [comment]
Wow that's a surprising stack trace.  I didn't know that code path existed.  Definitely have seen a stack trace like this before.

At a minimum this will resolve itself in conda 4.4.
