### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by cleberrocco** [conda/conda#5031]
Fetching packages ...
An unexpected error has occurred.                   | ETA:  0:15:49   2.39 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda2  (writable)
    default environment : C:\Program Files\Anaconda2
       envs directories : C:\Program Files\Anaconda2\envs
          package cache : C:\Program Files\Anaconda2\pkgs
           channel URLs : http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Cleber Rocco\.condarc
           offline mode : False

`$ C:\Program Files\Anaconda2\Scripts\conda-script.py install -c conda-forge glpk=4.61`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'C:\\Program Files\\Anaconda2\\pkgs\\glpk-4.61-py27_vc9_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.).

C:\>

**Comment by kalefranz** [comment]
Probably an intermittent HTTP error.  Specifically a HTTP timeout.  Much better configuration, support, and error messages in conda 4.3.
