### ISSUE TITLE
Create new env fails

### ISSUE THREAD

**Issue by tilusnet** [conda/conda#5037]
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.19.0
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /home/tilushq/opt/anaconda3  (writable)
    default environment : /home/tilushq/opt/anaconda3
       envs directories : /home/tilushq/opt/anaconda3/envs
                          /home/tilushq/.conda/envs
          package cache : /home/tilushq/opt/anaconda3/pkgs
                          /home/tilushq/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.12.4 CPython/3.5.2 Linux/4.8.6-040806-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/tilushq/opt/anaconda3/bin/conda-env create -n tmp1`

    Traceback (most recent call last):
      File "/home/tilushq/opt/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/tilushq/opt/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/home/tilushq/opt/anaconda3/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Invalid name, try the format: user/package
    tmp1 does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by mingwandroid** [comment]
You cannot create an environment with no packages specified. Try, for example adding `python=3.5.2`.

**Comment by tilusnet** [comment]
If that's the case, the `help` is incorrect:
`$ conda env create --help`
with
```
examples:
    conda env create
    conda env create -n name
    conda env create vader/deathstar
    conda env create -f=/path/to/environment.yml
    conda env create -f=/path/to/requirements.txt -n deathstar
    conda env create -f=/path/to/requirements.txt -p /home/user/software/deathstar
```
My command is the 2nd example which obviously doesn't work.

In my opinion the python package should be included by default, and it should be the version pointed at by `which python`.

**Comment by mingwandroid** [comment]
Ah oops, you are using `conda env` here, I didn't spot that. In this case, the 

I think you want `conda create -n tmp1` instead of `conda-env create -n tmp1`.

`conda-env --help` states:

> create              Create an environment based on an environment file

.. and `conda-env create --help` states:

>  -f FILE, --file FILE  environment definition file (default: environment.yml)

.. so I don't think the help is incorrect here.

> In my opinion the python package should be included by default, and it should be the version pointed at by which python

My guess is you are probably saying that as someone who believes conda is all about Python? What about people who don't want Python in a new environment for example people only interested in R? Forcing *anything* into an environment constrains the solver solution space a lot so there needs to be a way to not install Python.

Personally, I would love to re-write `conda` and `conda-build` as purely static binaries written in something fast and safe like Rust and not force Python on anyone but that's just me!

**Comment by tilusnet** [comment]
Ah, you are right, I got the command wrong.
And thank you for pointing out that `conda` is not a Python only package manager ─ I thought that was the case. Good to know, cheers.
I just cloned an environment with `conda create` with success, sorry for the misleading comments!

**Comment by mingwandroid** [comment]
No problem, glad to help, and I was wrong when I said that an environment cannot be empty so it was useful for me too!
