### ISSUE TITLE
conda install python=3.5

### ISSUE THREAD

**Issue by SilvanaNobre** [conda/conda#5038]
I was trying to change my Python version from 3.6 to 3.5
So I used this command: conda install python=3.5
I got an error, and Anaconda suggested me to post it here.
[CondaError.docx](https://github.com/conda/conda/files/914427/CondaError.docx)
Please, help me.
What should I do?

Silvana.

**Comment by mingwandroid** [comment]
Please paste the error as plain text.

**Comment by SilvanaNobre** [comment]
Now I cannot any more. I have already closed the anaconda window.

**Comment by mingwandroid** [comment]
I assume you are on Windows, if so, run the `Anaconda Prompt` to open a new prompt then try again.

**Comment by SilvanaNobre** [comment]
OK!, I'll do it!
Silvana

**Comment by SilvanaNobre** [comment]
Done! It has worked. Thank you!
Silvana

**Comment by mingwandroid** [comment]
OK, great. You should stick to using the `Anaconda Prompt` instead of the normal `cmd.exe` Window.

**Comment by dangwt** [comment]
I use the Anacoda Prompt, but still: An unexpected error has occured.
How can I do?


(C:\ProgramData\Anaconda3) C:\Users\dang>python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z


(C:\ProgramData\Anaconda3) C:\Users\dang>conda install python=3.5
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dang\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Wi
ndows/6.1.7601



`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install python=3.5`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\
pkgs\\cache\\2116b818.json'


(C:\ProgramData\Anaconda3) C:\Users\dang>conda install python=3.5
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

              platform : win-64
              conda version : 4.3.8
              conda is private : False
              conda-env version : 4.3.8
              conda-build version : not installed
              python version : 3.6.0.final.0
              requests version : 2.12.4
              root environment : C:\ProgramData\Anaconda3  (writable)
              default environment : C:\ProgramData\Anaconda3
              envs directories : C:\ProgramData\Anaconda3\envs
              package cache : C:\ProgramData\Anaconda3\pkgs
              channel URLs : 
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dang\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Wi
ndows/6.1.7601

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install python=3.5`

Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", lin
e 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\
pkgs\\cache\\2116b818.json'

**Comment by mingwandroid** [comment]
Conda 4.3.8 is quite buggy.

Please try `conda update conda` first.

**Comment by dangwt** [comment]
@mingwandroid, Thanks, but conda update conda has the same error.

**Comment by mingwandroid** [comment]
Did you install for `All Users`?

**Comment by mingwandroid** [comment]
You probably want to install for `Just Me` and also do not allow the installer to add to `PATH`.

To get a newer conda, you could install the latest Minconda instead, then if you want all of Anaconda you can use `conda install anaconda`.

**Comment by dangwt** [comment]
I reinstalled it for Just Me and solved the problem, 
Thank you!
