### ISSUE TITLE
Two local locations for environments

### ISSUE THREAD

**Issue by FMeines** [conda/conda#5040]
I have recently install anaconda and I have encountered two local folders for the environments. One is located in program files folder and the other one is in user folder. My OS is windows 7 64b. So, I have two root environments too. And when I use conda through command line switches between both. When I return to root environment using conda, it goes to root in program files. Even when I was in an enviroment of user folder. This behavior is normal?

Sorry, but i posted this issue here and in the anaconda issues channel because I don't know which one is related to. Please, you can close that are not related.

**Comment by kalefranz** [comment]
Yes, conda by default has two locations for both package caches and named environments.  Those associated with the root environment are the default when they are writable by the current user.  When they're not writable, conda opts for locations associated with the users home directory or writable workspace.
