### ISSUE TITLE
Anaconda http error occuring when installing conda-env 

### ISSUE THREAD

**Issue by mudkip727** [conda/conda#5042]
![image](https://cloud.githubusercontent.com/assets/27350736/24956738/fc4d9f90-1fc3-11e7-9520-b158d11f81de.png)
I was downloading librosa for python using anaconda, when a http error(as shown in the image above) occured. I'm a noob when it comes to using anaconda, so I would appreciate any help.

**Comment by kalefranz** [comment]
This was probably just an intermittent HTTP error.  The error messages have been dramatically improved in conda 4.3.
