### ISSUE TITLE
Package missing in current linux-32 channels

### ISSUE THREAD

**Issue by mohseniaref** [conda/conda#5045]
Hi,

I wonder how can I solve this issue

conda install mpl_toolkits
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-32 channels: 
  - mpl_toolkits

Close matches found; did you mean one of these?

    mpl_toolkits: prompt_toolkit

**Comment by nehaljwani** [comment]
`mpl_toolkits` is not a separate conda package. This [module](http://matplotlib.org/2.0.0/mpl_toolkits/index.html) is provided by the matplotlib package.

```bash
(root) nwani@linux-uuay:~> arch
i686
(root) nwani@linux-uuay:~> conda create -yn i5045 matplotlib
(root) nwani@linux-uuay:~> source activate i5045
(i5045) nwani@linux-uuay:~> python -c 'import mpl_toolkits; print mpl_toolkits.__path__'
['/home/nwani/miniconda2/envs/env5045/lib/python2.7/site-packages/mpl_toolkits']

```
