### ISSUE TITLE
Change conda platform in cygwin from win-64 to linux-64

### ISSUE THREAD

**Issue by stbei** [conda/conda#5046]
I am working in Cygwin and I want to install Qiime1 with conda for wich I need to work on the linux-64 platform. Anyone knows how to change the conda platform?

$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by mingwandroid** [comment]
I am not really sure what you mean here. Linux software will not run on Cygwin. If you are using Windows 10, you might be able to use the `Windows Subsystem for Linux`. The latest Windows 10 Creators Update [1] has a lot of good fixes and it appears that a good amount of console-based Linux software runs fairly well (though I have not verified this myself). You could try to run [2] in a `bash` prompt on Windows. Once you have installed and activated Miniconda, you should be able to install `qiime` via `conda install -c bioconda qiime`

[1] https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/
[2] https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

**Comment by kalefranz** [comment]
Also, you're on a very old version of conda. `conda update conda` should get you to the latest 4.3.16.
