### ISSUE TITLE
anaconda tensorflow intsllation  error

### ISSUE THREAD

**Issue by riya1202** [conda/conda#5048]
i was installing tenssorflow using

conda install -c conda-forge tensorflow

and i am getting the following error.how to remove it?

UnsatisfiableError:the following specifications were found to be in conflict :
-python 2.7*
-tensorflow->protobuf ==3.1.0 ->python 3.4*

**Comment by ilanschnell** [comment]
The problem appears to be that you are still using Python 3.4, which we no longer support.  We currently only support Python 2.7, 3.5 and 3.6.
