### ISSUE TITLE
Why does conda update --all wants to update to same version from  different mirror

### ISSUE THREAD

**Issue by xgdgsc** [conda/conda#5053]
When I run `conda update --all` , it wants to update to same version from different mirror:

![image](https://cloud.githubusercontent.com/assets/1189869/25036650/8b0f201e-2127-11e7-9030-31f37065bd60.png)

which is beyond my expectation. Is it a bug or feature? I' m using latest anaconda 3 on windows 10.

**Comment by tyler-thetyrant** [comment]
Try `conda update -c deafults --all`

**Comment by xgdgsc** [comment]
This way it doesn' t use the mirror, right?

**Comment by tyler-thetyrant** [comment]
Yup! It'll update packages from our default Conda channel.

**Comment by xgdgsc** [comment]
But I want to check and download new version from the mirror , without re-downloading everything.
