### ISSUE TITLE
Unable to install package from anaconda.org

### ISSUE THREAD

**Issue by smontanaro** [conda/conda#5055]
Despite successfully logging in, I am unable to install a package from anaconda.org. Why do I need to be "authorized" to install from a public repo?

Here's a session:

> (anaconda) src% conda install -c pydanny cookiecutter
> Fetching package metadata ...
> 
> CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/pydanny/linux-64/repodata.json>
> Elapsed: 00:00.186933
> CF-RAY: 34f70e302ebd099a-ORD
> 
> The remote server has indicated you are using invalid credentials for this channel.
> 
> If the remote site is anaconda.org or follows the Anaconda Server API, you
> will need to
>   (a) login to the site with `anaconda login`, or
>   (b) provide conda with a valid token directly.
> 
> Further configuration help can be found at <https://conda.io/docs/config.html>.
> 
> 
> 
> (anaconda) src% anaconda login
> Using Anaconda API: https://api.anaconda.org
> Username: smontanaro	
> smontanaro's Password: 
> login successful
> (anaconda) src% conda install -c pydanny cookiecutter
> Fetching package metadata ...
> 
> CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/sm-1bb26830-27a7-4652-a4df-f47d9426aaf1/pydanny/linux-64/repodata.json>
> Elapsed: 00:00.189228
> CF-RAY: 34f7135bfaa52597-ORD
> 
> The remote server has indicated you are using invalid credentials for this channel.
> 
> If the remote site is anaconda.org or follows the Anaconda Server API, you
> will need to
>   (a) login to the site with `anaconda login`, or
>   (b) provide conda with a valid token directly.
> 
> Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by smontanaro** [comment]
Here's some verbose output.

> (anaconda) src% conda install --verbose -c pydanny cookiecutter
> Fetching package metadata ...An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> overtaking stderr and stdout
> 
> stderr and stdout yielding back
> 
> Current conda install:
> 
>                platform : linux-64
>           conda version : 4.3.13
>        conda is private : False
>       conda-env version : 4.3.13
>     conda-build version : 2.1.5
>          python version : 3.6.0.final.0
>        requests version : 2.12.4
>        root environment : /home/skip/anaconda3  (writable)
>     default environment : /home/skip/anaconda3/envs/anaconda
>        envs directories : /home/skip/anaconda3/envs
>                           /home/skip/.conda/envs
>           package cache : /home/skip/anaconda3/pkgs
>                           /home/skip/.conda/pkgs
>            channel URLs : https://conda.anaconda.org/pydanny/linux-64
>                           https://conda.anaconda.org/pydanny/noarch
>                           https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : None
>            offline mode : False
>              user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Linux/4.8.0-46-generic debian/stretch/sid glibc/2.24
>                 UID:GID : 1001:1001
> 
> 
> 
> `$ /home/skip/anaconda3/envs/anaconda/bin/conda install --verbose -c pydanny cookiecutter`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 137, in fetch_repodata_remote_request
>         resp.raise_for_status()
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
>         raise HTTPError(http_error_msg, response=self)
>     requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/pydanny/linux-64/repodata.json
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
>         exit_code = args.func(args, p)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 222, in install
>         unknown=index_args['unknown'], prefix=prefix)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 92, in get_index
>         index = fetch_index(channel_priority_map, use_cache=use_cache)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 111, in fetch_index
>         repodatas = collect_all_repodata(use_cache, tasks)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 70, in collect_all_repodata
>         repodatas = _collect_repodatas_serial(use_cache, tasks)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 459, in _collect_repodatas_serial
>         for url, schan, pri in tasks]
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 459, in <listcomp>
>         for url, schan, pri in tasks]
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 105, in func
>         res = f(*args, **kwargs)
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 436, in fetch_repodata
>         mod_etag_headers.get('_mod'))
>       File "/home/skip/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 299, in fetch_repodata_remote_request
>         e.response)
>     conda.exceptions.CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/<TOKEN>/pydanny/linux-64/repodata.json>
>     Elapsed: 00:00.216415
>     CF-RAY: 34f7600708092525-ORD
>     
>     The remote server has indicated you are using invalid credentials for this channel.
>     
>     If the remote site is anaconda.org or follows the Anaconda Server API, you
>     will need to
>       (a) login to the site with `anaconda login`, or
>       (b) provide conda with a valid token directly.
>     
>     Further configuration help can be found at <https://conda.io/docs/config.html>.
>

**Comment by smontanaro** [comment]
Fails when trying to install from conda-forge as well. I specifically listed public packages for linux-64:

> https://anaconda.org/search?q=access%3Apublic+platform%3Alinux-64+cookiecutter

but it still demands some authorization which I can't provide.

> (anaconda) ~% conda install -c conda-forge cookiecutter
> Fetching package metadata ...
> 
> CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/sm-1bb26830-27a7-4652-a4df-f47d9426aaf1/conda-forge/linux-64/repodata.json>
> Elapsed: 00:00.205895
> CF-RAY: 34f76f284a710994-ORD
> 
> The remote server has indicated you are using invalid credentials for this channel.
> 
> If the remote site is anaconda.org or follows the Anaconda Server API, you
> will need to
>   (a) login to the site with `anaconda login`, or
>   (b) provide conda with a valid token directly.
> 
> Further configuration help can be found at <https://conda.io/docs/config.html>.
>

**Comment by smontanaro** [comment]
I just discovered this issue: https://github.com/conda/conda/issues/3399 Previous searching hadn't found it. (This ticket can likely be merged with that.)

Nothing which was suggested there worked for me. In fact, after executing

> (anaconda) ~% conda config --add channels conda-forge

even conda search commands failed. I had to --remove it before basic searches would work. Specifying any "non-standard" channel seems to fail.

**Comment by kalefranz** [comment]
If you have an expired token, anaconda.org will always return a 401.  `anaconda logout` is the quick fix to get rid of the expired token.  I guess we could add this extra information to that error message.

**Comment by smontanaro** [comment]
I've done the logout/login dance many times. It never solves the problem. I always get the 401. I don't think a stale/expired token is the problem.

**Comment by kalefranz** [comment]
Ok try this...

    ls -al /home/skip/.config/binstar
    rm -rf /home/skip/.config/binstar/*.token

Conda is clearly picking up a bad token from somewhere...

> CondaHTTPError: HTTP 401 UNAUTHORIZED for url https://conda.anaconda.org/t/sm-1bb26830-27a7-4652-a4df-f47d9426aaf1/conda-forge/linux-64/repodata.json

Get the same result with 

    curl -I https://conda.anaconda.org/t/sm-1bb26830-27a7-4652-a4df-f47d9426aaf1/conda-forge/linux-64/repodata.json

**Comment by smontanaro** [comment]
```
% ls -al ~/.config/binstar
ls: cannot access '/home/skip/.config/binstar': No such file or directory
```

**Comment by smontanaro** [comment]
@kalefranz - any thoughts?

**Comment by kalefranz** [comment]
Try

    CONDA_ADD_ANACONDA_TOKEN=false conda install -c conda-forge cookiecutter

**Comment by kalefranz** [comment]
Also could we get the output from

    /home/skip/anaconda3/bin/python -m conda.gateways.anaconda_client

**Comment by smontanaro** [comment]
On Mon, May 1, 2017 at 6:33 PM, Kale Franz <notifications@github.com> wrote:

> Also could we get the output from
>
> /home/skip/anaconda3/bin/python -m conda.gateways.anaconda_client
>
>
% /home/skip/anaconda3/bin/python -m conda.gateways.anaconda_client
{}

**Comment by smontanaro** [comment]
>
> Try
>
> CONDA_ADD_ANACONDA_TOKEN=false conda install -c conda-forge cookiecutter
>
>
% CONDA_ADD_ANACONDA_TOKEN=false conda install -c conda-forge cookiecutter
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <
https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 00:00.237573
CF-RAY: 358acdae8bc05516-ORD

The remote server has indicated you are using invalid credentials for this
channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <
https://conda.io/docs/config.html>.

**Comment by smontanaro** [comment]
@kalefranz 

This continues to be a thorn in my side. I'm going to have to start resorting to using pip to install some packages...

(python2) ~% conda search python-avro
Fetching package metadata .........
(python2) ~% conda search -c conda-forge python-avro
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 00:00.478339
CF-RAY: 359e3818bbd15619-ORD

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

The only environment variable I can find which matches "CONDA_[A-Z_]+_TOKEN" is "ANACONDA_API_TOKEN".

I tried installing anaconda-client. That didn't help either...

**Comment by smontanaro** [comment]
Is there more I can do to figure out where it's falling down? Unless the failing code is in a shared object, I should have write access to everything necessary. I'm happy to sprinkle print statements in the code to see what's going on.

**Comment by kalefranz** [comment]
First let's update to the latest 4.3.17 so I can give you exact code line number references.

    conda install -c defaults conda=4.3.17

Poke around with print statements in 

    /home/skip/anaconda3/lib/python3.6/site-packages/conda/connection.py

in the `add_binstar_token()` around line 140.

Let's assume for this exercise that discovery of *any* anaconda token is bad.  So on line 141 a

    print("token >>", token)

Should always yield `None`.  How bout this...

```python
@staticmethod
def add_binstar_token(url):
    clean_url, token = split_anaconda_token(url)
    print(">> token for url '%s' is '%s'" % (clean_url, token))
    if not token and context.add_anaconda_token:
        for binstar_url, token in iteritems(read_binstar_tokens()):
            if clean_url.startswith(binstar_url):
                print("This line should never trigger, but is has for url '%s'" % binstar_url)
                log.debug("Adding anaconda token for url <%s>", clean_url)
                from .models.channel import Channel
                channel = Channel(clean_url)
                channel.token = token
                return channel.url(with_credentials=True)
    return url
```

For the second print statement I added, we've already verified that it shouldn't ever be triggered with `python -m conda.gateways.anaconda_client`.

I just don't know where this token is coming from, so these print statements will at least help I think.

I know there are a lot of other reports of people having problems with these 401 errors, but in all other cases `anaconda logout` has resolved the issue and cleared the expired token.  This bug you're seeing is different.  I know you're frustrated, and I'm frustrated for you!

**Comment by smontanaro** [comment]
Not looking quite right:

>> token for url 'https://conda.anaconda.org/conda-forge/linux-64/repodata.
json' is 'None'
This line should never trigger, but is has for url '
https://conda.anaconda.org'

I added another print into read_binar_tokens, and got this output:

> token files: ['/home/skip/.config/binstar/https%3A%2F%2Fapi.anaconda.
org.token']

The date on that file is very recent:

~% ls -l ~/.config/binstar/
total 4
-rw------- 1 skip skip 39 May  4 15:48 https%3A%2F%2Fapi.anaconda.org.token

(It wasn't there last time I looked a few days ago.) I removed that file
and tried again. Now read_binstar_tokens() returns an empty list, but the
install still fails (extra print in front of return):

>> token for url '
https://conda.anaconda.org/conda-forge/linux-64/repodata.json' is 'None'
> token files: []
>> add_binstar_token returns:
https://conda.anaconda.org/conda-forge/linux-64/repodata.json

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <
https://conda.anaconda.org/conda-forge/linux-64/repodata.json> ...

I won't try to go any further than that for the time being, but will poke
around in the code a bit more. If there's anything else you want me to
poke, let me know.

Skip

**Comment by kalefranz** [comment]
The `read_binstar_tokens()` file is in `conda/gateways/anaconda_client.py`.  Figure out why that function is returning anything other than `None`.  Then we'll have our answer.

**Comment by kalefranz** [comment]
Anything new here?

**Comment by smontanaro** [comment]
Nothing new for me. I've reported what I can.

**Comment by ijstokes** [comment]
FWIW, I just had exactly this problem but doing an `anaconda login` fixed things for me.
