### ISSUE TITLE
WARNING: The remote server could not find the noarch directory for the requested channel with url: https://conda.anaconda.org/conda-default

### ISSUE THREAD

**Issue by atDoyle** [conda/conda#5057]
Forgive me because I am still new to this, but I can't create new conda environments and do not know why.  I am running Python 2.7 in anaconda and am trying to run python 3.5 so I can run Tensorflow, according to these instructions: https://conda.io/docs/py2or3.html

However when I enter conda create -n py35 python=3.5 anaconda, I get the following:

Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-default

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
...

PackageNotFoundError: Package missing in current win-64 channels:
  - python 3.5*

I have been searching for hours and have no idea what is causing this.

**Comment by nehaljwani** [comment]
Please share the output for `conda info`

**Comment by kalefranz** [comment]
`conda-default` isn't a valid channel. If there are docs indicating users should add a "conda-default" channel, they definitely need fixed.

**Comment by atDoyle** [comment]
Hi, thank you for the responses.  It looks like I was able to solve the issue by uninstalling Anaconda completely, deleting the .conda folder in C\Users\[User] (along with the other folders associated with Anaconda, like .spyder, etc.) and then reinstalling Anaconda.  I must have messed up the environments somehow but I'm not entirely sure what I did.

**Comment by Assassintears** [comment]
I encountered this problem too.
![image](https://user-images.githubusercontent.com/18465107/33713891-ead0eb98-db87-11e7-8ab2-368163dcae6d.png)
How to address this problem, not reinstall anaconda
