### ISSUE TITLE
Error when conda install -c menpo opencv

### ISSUE THREAD

**Issue by LeiChenML** [conda/conda#5061]
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/lei/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    opencv-2.4.11              |         nppy27_0         8.2 MB  menpo

The following NEW packages will be INSTALLED:

    opencv:    2.4.11-nppy27_0 menpo

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env: 2.6.0-0               --> 2.6.0-0 conda-forge

Proceed ([y]/n)? y

Fetching packages ...
opencv-2.4.11-  7An unexpected error has occurred.   | ETA:  0:00:05 483.79 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/lei/anaconda2  (writable)
    default environment : /home/lei/anaconda2
       envs directories : /home/lei/anaconda2/envs
          package cache : /home/lei/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/lei/.condarc
           offline mode : False

`$ /home/lei/anaconda2/bin/conda install -c menpo opencv`

    Traceback (most recent call last):
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/lei/anaconda2/pkgs/opencv-2.4.11-nppy27_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.).

**Comment by kalefranz** [comment]
I think this was the HTTP timeout error in conda 4.2.  The error message has been improved in conda 4.3.  There are also configuration parameters to extend the timeouts in conda 4.3.
