### ISSUE TITLE
Something wrong in communication with anaconda sever

### ISSUE THREAD

**Issue by SiriusYou** [conda/conda#5064]
That is what happened in my terminal:

yuukas-MacBook-Pro:~ youjia$ conda --version
conda 4.3.13
yuukas-MacBook-Pro:~ youjia$ conda update conda
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/Si-f9899432-584d-4512-82e7-91d612ed38b1/anaconda-fusion/osx-64/repodata.json>
Elapsed: 00:01.117847
CF-RAY: 351484083cac77ae-LAX

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

yuukas-MacBook-Pro:~ youjia$ 

I can't figure out what's the problem.
Could anyone offer help?
Thanks a lot!

**Comment by kalefranz** [comment]
Your anaconda.org token has probably expired.  Use `anaconda logout`.  If you need access to private packages on anaconda.org, you can use `anaconda login` to log back in again.
