### ISSUE TITLE
CondaHTTPError

### ISSUE THREAD

**Issue by azamla** [conda/conda#5065]
I try to insatll packages and even update current packages. However, there is a problem about Python anaconda
(C:\ProgramData\Anaconda2) C:\Users\Administrator>conda update conda
Fetching package metadata .........

CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Read timed out. (read timeout=9.15)",))',),)

(C:\ProgramData\Anaconda2) C:\Users\Administrator>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (read only)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Administrator\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

**Comment by Sklavit** [comment]
Same for
```
               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.17.0
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : D:\Anaconda  (writable)
    default environment : D:\Anaconda
       envs directories : D:\Anaconda\envs
          package cache : D:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\s.nechuiviter\.condarc
           offline mode : False
```

**Comment by kalefranz** [comment]
This is an HTTP timeout, probably from a flakey connection.  As the error message says, just retry a few times.  You can also try something like

    conda config --set remote_connect_timeout_secs 60

**Comment by kalefranz** [comment]
But I guess `remote_connect_timeout_secs` configuration was added in conda 4.3, so won't work in conda 4.2.
