### ISSUE TITLE
complex dependencies

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5069]
@epruesse commented on [Tue Apr 18 2017](https://github.com/conda/conda-build/issues/1935)

Conda currently (AFAIK) only implements simple dependencies where a package requires a series of packages with an optional range of permissible versions.

There are, however, often more complex requirements:
 - alternative dependencies, e.g. `libxml2 2.1.2 | libxml3* | libxml-ng`
 - exclusions: `pysam >0.8 !0.9.1`
 - other package connections, such as `conflicts`, `breaks`, `suggests`, `recommends`, `provides` or `enhances` (examples taken from dpkg).

Are there any plans to extend conda in this direction?

---

@msarahan commented on [Tue Apr 18 2017](https://github.com/conda/conda-build/issues/1935#issuecomment-294974603)

As merely a consumer of conda's capabilities in this area, I don't think conda-build is the right place to file this issue.  Do you want me to move it to the conda repository?

---

@epruesse commented on [Tue Apr 18 2017](https://github.com/conda/conda-build/issues/1935#issuecomment-294986607)

Yes, I guess conda/conda is the better place. I had looked at #1590 here which somewhat similar. 

---

@msarahan commented on [Tue Apr 18 2017](https://github.com/conda/conda-build/issues/1935#issuecomment-294989052)

Yeah, #1590 is related.  Ultimately, conda-build is bound by what conda can do.  It is absolutely not right at all for conda-build to implement its own parsing scheme beyond conda's, unless that scheme is completely specific to building or testing packages (like the jinja2 scheme mentioned in that issue.)

**Comment by epruesse** [comment]
(Thx for moving. Zenhub should really have rewritten #1590 into conda/conda-build#1590 though.)

**Comment by kalefranz** [comment]
In 4.4 we're implementing `constrains`--what some people call optional or conditional. See https://github.com/conda/conda/pull/4982

After that, the next feature we'll implement along these lines is to indicate when one package name replaces or supersedes or is able to take the place of another package name.

Once we clear those, we'll see what else makes sense.

**Comment by hanslovsky** [comment]
Would it be possible to install an optional dependency by default but not fail if the user chooses not to install that dependency (which would reqiured an additional switch). That would be desirable in my use case, something like this (very simplified):
```
jdk
package A with jdk depends on jdk
package A without jdk does not depend on jdk
```
instead I would like to have something like
```
jdk
package A optional dependence on jdk (but installs jdk by default)
```

This could probably also be achieved in a similar way by what @kalefranz suggests, so I am curious to learn what the timeline would be for that:
> After that, the next feature we'll implement along these lines is to indicate when one package name replaces or supersedes or is able to take the place of another package name.
