### ISSUE TITLE
Rstudio Desktop installed via Anaconda can't open the .R(R Scripts) or .RMD(R markdown) files.

### ISSUE THREAD

**Issue by sniperhgy** [conda/conda#5072]
OS : Windows 7 64 bit
Anaconda : 4.3.1 64 bit Python 3.6.0

After installed Anaconda, I installed R language via command line : conda install r-essentials, then the RStudio Desktop version via command line : conda install rstudio.

The installation are both successful. The open the RStudio Desktop, it will associate the R.exe automatically. I can write R codes in it and run. But I found that, if I try to open an existing R script file or R markdown file, the editor in RStudio Desktop will return a empty windows.(The are a lot of codes in that file, but RStudio Desktop doesn't display them.)

For finding out what's going on, I downloaded RStudio from its Official Website and installed it, all the R script and R markdown files can be opened successfully. So I can make sure the issue only occurred in RStudio Desktop (installed via Anaconda).

Dear developers, could you please help to check it out?

Thank you very much.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1615
