### ISSUE TITLE
Anaconda spyder install crash

### ISSUE THREAD

**Issue by chba7628** [conda/conda#5074]
Trying to update my spyder to the newest version, but crashing during package installation. See below:

![image](https://cloud.githubusercontent.com/assets/26173737/25179458/4d6120fa-250a-11e7-96e9-2e93ca9da8b3.png)

![image](https://cloud.githubusercontent.com/assets/26173737/25179474/5d57f77c-250a-11e7-99cc-aad44b41f2d8.png)

**Comment by tyler-thetyrant** [comment]
You are not using most up to date version of Conda. 
Try `conda update conda` to get the most recent version of Conda, which is 4.3.16
