### ISSUE TITLE
Received error attempting to update conda

### ISSUE THREAD

**Issue by sastephe** [conda/conda#5075]
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Sam> conda update conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2k             |            vc9_0         4.4 MB
    vs2008_runtime-9.00.30729.5054|                0        1016 KB
    idna-2.2                   |           py27_0         122 KB
    ipaddress-1.0.18           |           py27_0          31 KB
    pyasn1-0.2.3               |           py27_0          76 KB
    pycparser-2.17             |           py27_0         154 KB
    pywin32-220                |           py27_2        15.1 MB
    requests-2.13.0            |           py27_0         776 KB
    ruamel_yaml-0.11.14        |           py27_1         222 KB
    cffi-1.9.1                 |           py27_0         191 KB
    menuinst-1.4.4             |           py27_0         109 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    cryptography-1.7.1         |           py27_0         335 KB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.16               |           py27_0         541 KB
    ------------------------------------------------------------
                                           Total:        24.6 MB

The following NEW packages will be INSTALLED:

    idna:           2.2-py27_0
    ipaddress:      1.0.18-py27_0
    openssl:        1.0.2k-vc9_0      [vc9]
    ruamel_yaml:    0.11.14-py27_1
    vs2008_runtime: 9.00.30729.5054-0
    wheel:          0.29.0-py27_0

The following packages will be UPDATED:

    cffi:           0.9.2-py27_0  --> 1.9.1-py27_0
    conda:          3.11.0-py27_0 --> 4.3.16-py27_0
    conda-env:      2.1.4-py27_0  --> 2.6.0-0
    cryptography:   0.8-py27_1    --> 1.7.1-py27_0
    enum34:         1.0.4-py27_0  --> 1.1.6-py27_0
    menuinst:       1.4.2-py27_1  --> 1.4.4-py27_0
    pip:            6.1.1-py27_0  --> 9.0.1-py27_1
    pyasn1:         0.1.7-py27_0  --> 0.2.3-py27_0
    pycparser:      2.10-py27_0   --> 2.17-py27_0
    pyopenssl:      0.14-py27_0   --> 16.2.0-py27_0
    pywin32:        219-py27_0    --> 220-py27_2
    requests:       2.7.0-py27_0  --> 2.13.0-py27_0
    setuptools:     15.2-py27_0   --> 27.2.0-py27_1
    six:            1.9.0-py27_0  --> 1.10.0-py27_0

Proceed ([y]/n)? y

menuinst-1.4.4 100% |###############################| Time: 0:00:00   1.47 MB/s
Fetching packages ...
openssl-1.0.2k 100% |###############################| Time: 0:00:02   1.77 MB/s
vs2008_runtime 100% |###############################| Time: 0:00:00   1.57 MB/s
idna-2.2-py27_ 100% |###############################| Time: 0:00:00   1.02 MB/s
ipaddress-1.0. 100% |###############################| Time: 0:00:00   1.03 MB/s
pyasn1-0.2.3-p 100% |###############################| Time: 0:00:00   1.36 MB/s
pycparser-2.17 100% |###############################| Time: 0:00:00   1.61 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:08   1.78 MB/s
requests-2.13. 100% |###############################| Time: 0:00:00   1.85 MB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00   1.62 MB/s
cffi-1.9.1-py2 100% |###############################| Time: 0:00:00   1.23 MB/s
pip-9.0.1-py27 100% |###############################| Time: 0:00:01   1.68 MB/s
cryptography-1 100% |###############################| Time: 0:00:00   1.53 MB/s
pyopenssl-16.2 100% |###############################| Time: 0:00:00   1.01 MB/s
conda-4.3.16-p 100% |###############################| Time: 0:00:00   1.53 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'
PS C:\Users\Sam>

**Comment by kalefranz** [comment]
You're updating from conda 3.11.0, which is very very old.  And that's the code that's actually being ran for the update.  You might just have to start with a new environment.

**Comment by kalefranz** [comment]
I'm sure this was a bug, but it has long ago been fixed.

Actually, yes, from the changelog:

> 2015-05-05 3.12.0:
> ----------
>  * correctly allow conda to update itself

So not a lot we can do at this point.
