### ISSUE TITLE
Setuptools downloading is disabled in conda build

### ISSUE THREAD

**Issue by srossross** [conda/conda#508]
I was working on a conda build when I got this error:

```
Processing dependencies for Test-Package==1.1.0
Searching for werkzeug
Traceback (most recent call last):
....
RuntimeError: Setuptools downloading is disabled in conda build  url=https://pypi.python.org/simple/werkzeug/r
Command failed: /bin/bash -x -e /Users/sean/Documents/workspace/conda/example_packages/setuptools/build.sh
```

I added the options `--single-version-externally-managed --record=record.txt` to the `python setup.py install` command and it seemed to work ok.

Is this the expected way of dealing with this error?

**Comment by zonksoft** [comment]
Yes, it would definitely help if the RuntimeError message would contain more information.

**Comment by kerrywatson1** [comment]
@asmeurer can this be closed? This isn't really docs.

**Comment by asmeurer** [comment]
This isn't the docs issue tracker.  As far as I know, the message could still be improved.

**Comment by kerrywatson1** [comment]
@asmeurer is this a good error message, then? 

"setuptools is trying to download a (non-conda) dependency 'pathlib' during conda-build, which is not allowed. 'pathlib' is not declared in your meta.yaml as a conda dependency - consider adding it."

**Comment by asmeurer** [comment]
Yeah, something like that. Maybe also link to a docs page with more information so that we can update more information there without having to rebuild setuptools.

**Comment by yoavram** [comment]
I'm having an issue where a package is declared in the meta.yaml file, 
there is a conda package in my channel, I'm using my channel, and I'm still getting this error message.

**Comment by rolando** [comment]
Just for the record, I had a similar issue while building a package for `service_identity`.

Even though the requirement `pyasn1-modules` was buildable because conda have `pyasn1` up to `0.1.9`, it turns out that when building `service_identity` the "requirement chain" resulted in installing `pyasn1 0.1.7`, which I believe it's due to either `cryptography` or `pyopenssl` (I haven't dig further into this), causing the build to fail with the `Setuptools downloading is disabled ...` because `pyasn1-modules` had as requirement `pyasn1 >= 0.1.8`.

So, the simple solution was to build `pyasn1-modules 0.0.5` rather than the latest version.

**Comment by berislavlopac** [comment]
I'm just having a similar problem as @rolando above -- when installing `sqlalchemy-continuum` it's trying to download `phonenumbers 5.6b1r` from GitHub, even though `7.0.9` is already installed.

**Comment by groutr** [comment]
@berislavlopac, that is because sqlalchemy-utils has a problem with it's setup.py.

**Comment by berislavlopac** [comment]
I figured that might be the culprit. Any suggestions how to resolve it, or at least work around it?

**Comment by groutr** [comment]
When I build a similar package, I just patched setup.py.  I can open a PR for the project with my changes.

**Comment by phumke** [comment]
I ran into a similar problem when building airflow:

`RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/flask-cache/r
Command failed: /bin/bash -x -e /home/humkepm/mountedSharedDrives/dropbox/Projects/anaconda/conda-recipes/airflow/1.6.2/build.sh
`

I built flask-cache earlier, so I have the meta.yaml files for both.  I was able to work around the issue using `--single-version-externally-managed --record=record.txt`, but that felt hacky to me.

Here's the flask-cache meta.yaml:
https://github.com/phumke/conda-recipes/blob/master/flask-cache/0.13.1/meta.yaml

And the airflow meta.yaml:
https://github.com/phumke/conda-recipes/blob/master/airflow/1.6.2/meta.yaml

**Comment by nguyenviettien13** [comment]
> I was working on a conda build when I got this error:
> 
> ```
> Processing dependencies for Test-Package==1.1.0
> Searching for werkzeug
> Traceback (most recent call last):
> ....
> RuntimeError: Setuptools downloading is disabled in conda build  url=https://pypi.python.org/simple/werkzeug/r
> Command failed: /bin/bash -x -e /Users/sean/Documents/workspace/conda/example_packages/setuptools/build.sh
> ```
> I added the options `--single-version-externally-managed --record=record.txt` to the `python setup.py install` command and it seemed to work ok.
> 
> Is this the expected way of dealing with this error?

can you show me? how to add the options `--single-version-externally-managed --record=record.txt` to the `python setup.py install`
i don't know where "python setup.py install"
