### ISSUE TITLE
Make pinned packages optional/constrained dependencies

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5081]
In the conda 4.3 feature branch, make the `get_pinned_specs()` function in `conda/plan.py` return `MatchSpec` objects with the `optional=True` flag.

Make sure (by writing extra unit tests) that the `conda.cli.common.spec_from_line()` function is both working correctly and being used correctly.

Package pinning configuration was recently implemented within condarc files via https://github.com/conda/conda/pull/4921/files.  Reviewing that PR would be a good place to start.

**Comment by stefanseefeld** [comment]
While working on the test I notice something isn't working quite right, I suspect the solver:

```
run_command(Commands.INSTALL, prefix, "openssl")
assert not package_is_installed(prefix, "python")
run_command(Commands.INSTALL, prefix, "flask")
assert package_is_installed(prefix, "python-3.6.1-2")
```
works fine, while
```
run_command(Commands.CONFIG, prefix,
                        "--add pinned_packages", "python=3.6.1-2")
run_command(Commands.INSTALL, prefix, "openssl")
assert not package_is_installed(prefix, "python")
run_command(Commands.INSTALL, prefix, "flask")
assert package_is_installed(prefix, "python-3.6.1-2")
```
yields the error
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - flask
  - python 3.6.1-2 (optional)
```

**Comment by stefanseefeld** [comment]
@mcg1969 , do you have any idea why this may be happening, and where I should follow up (file a separate bug report, etc.) ?

**Comment by mcg1969** [comment]
Interesting. Normally I tell people _never doubt the solver_ but this is certainly sufficiently new functionality that we should check. I'll see what I can find.

**Comment by mcg1969** [comment]
ha ha! _never doubt the solver_.

`python=3.6.1-2` is not the correct spec. It's either `python=3.6.1=2` or `python 3.6.1 2`, depending on how you've implemented it. `python=3.6.1-2` means `Python version 3.6.1-2`, not `Python version 3.6.1 build 2`.

**Comment by stefanseefeld** [comment]
Thanks ! (Just a shot in the dark: the solver itself only treats a bunch of numbers (roughly speaking :-) ), which we generate from all the various inputs (match-spec, index content, etc.). I could imagine that our encoding of the request from those inputs into numbers might be wrong somehow, i.e. the query we submit to the solver proper may not be what we intended.)

**Comment by stefanseefeld** [comment]
Oh ! Now that isn't very intuitive, is it ? Is that documented somewhere ?
Anyhow, thanks for the quick find, I'll adjust my test logic and see whether it works.

**Comment by mcg1969** [comment]
Well, `python=3.6.1=2` is the proper command-line syntax, and that's documented. `python 3.6.1 2` is the proper MatchSpec syntax, which is also documented, but perhaps internally.

**Comment by stefanseefeld** [comment]
OK, fair enough. Thanks for your assistance !

**Comment by stefanseefeld** [comment]
```
run_command(Commands.CONFIG, prefix,
            "--add pinned_packages", "python=3.6.1=2")
run_command(Commands.INSTALL, prefix, "openssl")
assert not package_is_installed(prefix, "python")
```
is failing, i.e. python is being installed even though openssl doesn't depend on it. The MatchSpec objects look good, though.

**Comment by kalefranz** [comment]
@stefanseefeld 

> is failing, i.e. python is being installed even though openssl doesn't depend on it

Are you working in 4.3.x or 4.4.x?

**Comment by stefanseefeld** [comment]
Right, I understand.
This is on 4.4.x.

**Comment by kalefranz** [comment]
I guess that means then that the `optional=True` flag sent to the MatchSpec object isn't working correctly within resolve?

**Comment by mcg1969** [comment]
Is this on windows? If so, features are to blame, and we're discussing that in another issue.

**Comment by stefanseefeld** [comment]
This is GNU/Linux.

**Comment by mcg1969** [comment]
Ah, I'll bet I know why. You're passing an optional MatchSpec right to `Resolve.solve`, I'll bet.

That's not going to work, I don't think. The reason why is that I've been using the optional specification for a long time to effect package _removals_. When you do a `conda remove xxx`, the solver gets a set of specs that exclude `xxx`, and which make _all other packages optional_. That way, if it has to remove other packages because they have a dependency relationship with `xxx`, it is given permission to do so.

But of course, we don't _want_ to remove all the packages in the environment; indeed, we want to keep as many of them as possible. So the solver has a specific pass that _maximizes the number of optional specs it keeps around_.

**Comment by mcg1969** [comment]
I was frankly unaware that y'all were trying to do this. It makes sense, don't get me wrong, but optional specs fed directly to `Resolve.solve` have had a specific meaning for quite some time. It's not entirely clear to me how this is going to be fixed.

**Comment by mcg1969** [comment]
So it sounds like we need two kinds of optional dependencies: 1) optional, but try hard to include it; and 2) optional, but try hard _not_ to include it.

It's important to note that pinned dependencies are _not_ always optional. In Stefan's example above, for instance, `python=3.6.1=2` starts out as "optional but try hard not to include it". But as soon as it _does_ get included in the environment, it is _no longer optional at all_.

**Comment by stefanseefeld** [comment]
Yeah, from a user's perspective I find the terminology confusing. It's the "pinned" that is the operational term here. Optional merely means that the pinning should have no bearing on whether or not the package gets installed.
So perhaps we can just find a better term to express the concept, to be less confusing to ourselves.

**Comment by mcg1969** [comment]
Well, we're trying to _implement_ pinning using conda's internal optional dependency mechanism. We don't necessarily need to use the term "optional" in public facing documentation, that's for sure.

But I realized over lunch how we can get this to work. We can create a "virtual package" that is installed in each environment. That package would include as optional dependencies every pinned package. This would ensure that conda behaves properly no matter what the operations are.

**Comment by stefanseefeld** [comment]
That sounds good. (And yes, please let's make sure the user-facing information deploys a less ambiguous term to flag this). I'm getting confused each time I try to parse the title of this very issue. ;-)

**Comment by kalefranz** [comment]
@stefanseefeld I just found an error that will/should be affecting your tests here...

https://github.com/conda/conda/blob/4.4.x/conda/models/index_record.py#L126

Should be `optional=True`, not `option=True`.

**Comment by stefanseefeld** [comment]
Good catch ! Unfortunately, the test still fails with that fixed. I'll keep looking...

**Comment by mcg1969** [comment]
The tests _should_ fail unless the metapackage idea is implemented. If you supply an "optional=True" directly to the `conda.resolve.Resolve.solve` spec list, it's going to try to install it---it just won't complain if it can't.

**Comment by stefanseefeld** [comment]
OK, so it sounds like we need a plan for how to attack this. I'd like to help, but don't think I have enough knowledge about the solver internals to even understand what needs to be done.

**Comment by kalefranz** [comment]
done with #5414
