### ISSUE TITLE
Add a prefix state file

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5082]
Add a new json-formatted file to the `conda-meta` directory in a prefix to hold state information. 
 Possible names for the file could be `state.json` or `prefix_state.json`.

Implementation should be through a new `PathAction` that gets added to the 'register' `ActionGroup` in `UnlinkLinkTransaction._prepare()`.

The only contents of the new file right now should be the dependency sort order or all the packages installed in the prefix (i.e. the result of `Resolve().dependency_sort()`.

**Comment by kalefranz** [comment]
Also don't forget: add configuration to lock an environment against mutation operations #6231

**Comment by kalefranz** [comment]
Also related:

  * https://github.com/conda/conda/issues/4929
  * https://github.com/conda/conda/issues/4943

**Comment by kalefranz** [comment]
With this work, may also want to move certain configuration parameters (like `channels`) out of the current configuration context, and into this new state file.  Under this scenario, the `channels` configuration would only be used when first creating environments.  Once environments are created, channels are only pulled from the configuration for that individual environment.

**Comment by kalefranz** [comment]
Configuration parameters that make sense to move to the state file when the environment is first created include:

- channels
- pinned_packages
- default_channels
- aggressive_update_packages ?
- auto_update_conda
- channel_priority
- track_features
- subdirs

**Comment by kalefranz** [comment]
@jjhelmus The `subdirs` component above should handle keeping a "force_win32" env as `win-32`.

**Comment by aryarm** [comment]
Have there been any updates on this issue? I think this would be really helpful to have. I'm hoping it would also help with https://github.com/conda/conda/pull/8776
