### ISSUE TITLE
Error triggered with .yaml

### ISSUE THREAD

**Issue by gdudhat** [conda/conda#5084]
(my_env) C:\Users\L G Dudhat>conda env create -f environment.yaml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : C:\anaconda  (writable)
    default environment : C:\anaconda\envs\my_env
       envs directories : C:\anaconda\envs
                          C:\Users\L G Dudhat\AppData\Local\conda\conda\envs
                          C:\Users\L G Dudhat\.conda\envs
          package cache : C:\anaconda\pkgs
                          C:\Users\L G Dudhat\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\L G Dudhat\.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\anaconda\Scripts\conda-env-script.py create -f environment.yaml`

**Comment by nehaljwani** [comment]
The trace back is missing in the output shared by you. 

Also, please don't create conda environments in directories which have space(s) in their path.
