### ISSUE TITLE
Conda Pylint not working 

### ISSUE THREAD

**Issue by klimanek** [conda/conda#5105]
Been having this issue for a while: 

`$ pylint --version`
`Problem importing module variables.py: No module named functools_lru_cache`
`Problem importing module variables.pyc: No module named functools_lru_cache`
`No config file found, using default configuration`
`pylint 1.6.4, `
`astroid 1.4.9`
`Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) `
`[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]`

And so...

`PackageNotFoundError: Package missing in current osx-64 channels: 
      - functools_lru_cache`

The same issue was reported [here](https://github.com/PyCQA/pylint/issues/1296).

**Comment by kalefranz** [comment]
As referenced in your linked issue, this is not an issue that changing conda code can fix.  It has to do with the package itself.  A ticket has been created in https://github.com/ContinuumIO/anaconda-recipes/issues/79, but it might not get visibility there.  The correct place for this issue where it'll get noticed is https://github.com/ContinuumIO/anaconda-issues.  I'll move it.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1623
