### ISSUE TITLE
Conda won't uninstall packages that were installed via pip

### ISSUE THREAD

**Issue by lexual** [conda/conda#512]
If you attempt to install a package, and there isn't a conda package for it, then the system falls back to installing it via pip.

But if you then attempt to uninstall one of these packages, conda fails.

```
Error: no packages found to remove from environment
```

The expected behaviour should be the same for installation: first attempt to remove package via conda, and fallback to pip if it's not a conda package.

Steps to reproduce:

1) conda install django # or any non-conda package.
2) conda remove django
3) see confusing error message.

**Comment by ionFreeman** [comment]
So, how do I handle old Python 2 pip installs?
```

☺ conda list --prefix ~/anaconda | grep -F '<pip>'
awscli                    1.6.2                     <pip>
```
I want to get rid of that awscli, but both conda and pip deny ownership.
