### ISSUE TITLE
Incorrectly detected arch on aarch64

### ISSUE THREAD

**Issue by H-Plus-Time** [conda/conda#5125]
As per the title, conda currently only knows about the usual x86, x86_64 and armv7l architectures. Since aarch64 systems are compatible with armhf binaries, conda just needs to alias 'aarch64' to 'armv7l'.

The only hitch involved in approaching the problem via such an alias is that the armhf linker (ld-linux-armhf) may not be installed - its a rare situation currently, since most ARM systems opt for a 64bit kernel/32 bit userspace due to the rarity of 64 bit ARM binaries. The user (with sudo privileges) would need to install the linker in such a situation.

See [PR 4809](https://github.com/conda/conda/pull/4809) for implementation.

**Comment by vielmetti** [comment]
> Since aarch64 systems are compatible with armhf binaries

This is not in general true; there are aarch64 systems in the field based on the Cavium ThunderX hardware which do not run 32-bit ARM binaries, and these systems are available from Packet ("Type 2A" 96 core) and Scaleway (virtualized 2, 4, or 8 core) in existing configurations.
