### ISSUE TITLE
Feature Request: conda install --file meta.yaml should just work

### ISSUE THREAD

**Issue by winni-genp** [conda/conda#5126]
In our projects we create meta.yaml files which have requirements sections for `build` and `run`.  In development we install all requirements listed in the `requirements:run` section of the meta.yaml.  We currently have a bespoke script that parses the meta.yaml and drops the dependencies on the command line.  However, this seems like something conda install should do.

**Comment by mingwandroid** [comment]
Are you not using `conda-build` here?

**Comment by winni-genp** [comment]
We use `conda-build` for building conda packages from `meta.yaml` files.  However, this is impractical for development work, so we instead run `python setup.py develop` when developing.  All we need is a tool for installing the dependencies of a package into the current environment without installing the package itself.

On further reflection, this works, but it seems a bit overkill for something this simple:
```
conda build my_tool
conda install my_tool -c "file://$(readlink -f conda-env/conda-bld)"
conda uninstall my_tool
```

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/3500

**Comment by kalefranz** [comment]
conda itself won't be parsing meta.yaml files.  With all the jinja2 templating, it's just too hazardous.  Conda 4.4 does include the #3500 feature request.
