### ISSUE TITLE
Issues installing KlustaViewa

### ISSUE THREAD

**Issue by bs10reh** [conda/conda#5127]
I am trying to install KlustaViewa. When I type in the following I get the package not found error below. Please can you help with this problem. Thank you

C:\Users\Rachel\Miniconda3>conda create -n klusta -f C:\Users\Rachel\MiniConda3\environment.yml
Fetching package metadata ...........

PackageNotFoundError: Package missing in current win-64 channels:
  - c:\users\rachel\miniconda3\environment.yml

**Comment by nehaljwani** [comment]
If you are using the environment file: https://raw.githubusercontent.com/klusta-team/klustaviewa/master/installer/environment-win.yml , it doesn't work for me either.  The environment file which works for me is: [env.yml](https://github.com/conda/conda/files/953902/env.yml.txt)
