### ISSUE TITLE
improve fault tolerance when channel connection fails

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5149]
Right now conda fails hard on the first channel that it can't connect to.  So an inaccessible or down repository will prevent conda from working at all.  This seems undesirable.  I think a warning should be issued and conda should continue with the next channel.  Some option like `--strict` could be used to indicate that any channel failure aborts conda.  But in the general case the current behavior can make conda hard to use when remote systems out of the user's control are not accessible from the local system.

**Comment by kalefranz** [comment]
`--strict` should always be the default. If you have a misbehaving channel and want to bypass it, remove it from your channels list. The alternative is that conda ends up guessing, and user's get VERY unexpected and undefined behavior. The non-strict alternative and the full set of behaviors that option encompasses is from an overall user experience far inferior to conda complaining when a channel isn't available. Fail fast, and let the user know what's wrong (and how to correct if they want). These corrections though necessarily need to be explicit actions by users and not conda trying to guess.

**Comment by kalefranz** [comment]
Principle of least surprise is, at least for me, one of the most important cpncepts in UX. If we relaxed this constraint, the universe of possibilities for non-obvious behavior is extensive.

**Comment by ijstokes** [comment]
What happens when I don't have control over the `.condarc` files that conda is picking up?  That is my scenario right now.  I have no way of suppressing certain channels, so far as I can tell.

**Comment by goanpeca** [comment]
@ijstokes how about channel override?

**Comment by kalefranz** [comment]
I've created https://github.com/conda/conda/issues/5158 that should cover this use case.  I agree that we need to work something out here.

**Comment by ijstokes** [comment]
@kalefranz so after you had convinced me (and you did convince me) that conda should hard-fail when a channel doesn't work, and the fact that it does this now is a good thing, I then discovered that it isn't always true!  I had a bad channel in a config file: `http://repo.demo.continuum.io/`.  It caused a non-fatal warning:

```
$ conda create -n octave -c conda-forge octave_kernel
Fetching package metadata ................
WARNING: The remote server could not find the noarch directory for the
requested channel with url: http://repo.demo.continuum.io

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.
Solving package specifications: .

Package plan for installation in environment /Users/ijstokes/anaconda/envs/octave:
```

Is that consistent behavior or a surprise to you?

**Comment by kalefranz** [comment]
Yeah, I don't like it.  There's history on that at https://github.com/conda/conda/pull/3739 and https://github.com/conda/conda/pull/4238.  I think in the interim since that discussion, the situation may have hopefully gelled a bit.

**Comment by kalefranz** [comment]
Just added an additional comment https://github.com/conda/conda/pull/3739#issuecomment-297881591
