### ISSUE TITLE
Anaconda Python + pyodbc does not work

### ISSUE THREAD

**Issue by meet-bhagdev** [conda/conda#5150]
Anaconda Python is not able to run a python script successfully that works with system python. 

To repro:
```
$pip install pyodbc
$sudo su 
$curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
$curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
$exit
$sudo apt-get update
$sudo ACCEPT_EULA=Y apt-get install msodbcsql=13.1.6.0-1 mssql-tools=14.0.3.0-1 unixodbc-dev
$pip install pyodbc
$vim test.py
```
Paste the following in test.py
```
import pyodbc
server = 'localhost'
database = 'SampleDB'
username = 'sa'
password = 'your_password'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
print ('Reading data from table')
tsql = "SELECT @@VERSION;"
with cursor.execute(tsql):
    row = cursor.fetchone()
    while row:
        print (str(row[0]))
        row = cursor.fetchone()
```

```$ python test.py```
-- Works! 

```
$cd /usr/bin/anaconda/bin/
$./pip install pyodbc
$./python test.py
```
This gives an error:
`pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.6.0' : file not found (0) (SQLDriverConnect)")`
 
I think it is something about permissions (anaconda python not being able to read from certain folders)

Some other issues on StackOverflow:
http://stackoverflow.com/questions/42301519/pyodbc-cannot-find-unixodbc-library-when-using-anaconda-python

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1639
