### ISSUE TITLE
noarch package with menuinst menu

### ISSUE THREAD

**Issue by mbargull** [conda/conda#5153]
Apart from conda itself, this also concerns menuinst (ping @ilanschnell ).
Do you think it will be possible/worthwhile to provide a way to include `menuinst`-menus inside a `noarch`-package?
A use case would be an cross-platform application which could be perfectly packaged with `noarch: ...` -- but also happens to have a GUI for which Windows users would benefit from having a start menu entry/desktop link. Currently one needs to build platform-dependent packages for this or supply some additional helper package which provides those menus.
I see it is problematic since the `.json` (+`.ico`, ...) files are platform-dependent which kinda goes against `noarch`. If one wants to include them regardless, either conda or conda and menuinst need to be changed to support this. That is, in effect the copying step during package building (e.g., [console_shortcut/bld.bat](https://github.com/ContinuumIO/anaconda-recipes/blob/master/console_shortcut/bld.bat)) would most likely be postponed until the user installation (post-link step?) and the package could contain platform sub folders like `Menu/win` etc.

**Comment by kalefranz** [comment]
Right now noarch really universal.  If you have platform-specific or arch-specific anything, it's not a noarch package.  So if in a meta.yaml file you're using selectors, that's a pretty good hint that your package can't be noarch.

Expanding noarch to have certain platform- and arch-specific capabilities would definitely be useful, but it's a pretty big feature request that needs to be prioritized in the context of other features on the wish list.

**Comment by ma-ba** [comment]
Indeed. Though a menuinst-specific solution ("hack") might be possible, I agree and welcome more general concepts for platform specific alterations. Coming up with those concepts takes time, hence "a pretty big feature request" is an understandable classification. Thanks for taking your time to answer my question!
