### ISSUE TITLE
Error after conda install scikit-learn

### ISSUE THREAD

**Issue by GeoffNN** [conda/conda#5156]
After creating a new conda environment, with `conda create -n name python=3.5`, doing `conda install scikit-learn` and then importing sklearn results in the following error:
`"ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory"`

**Comment by kalefranz** [comment]
Can you please provide `conda info` and `conda list --show-channel-urls`?  Also, did you remember to `source activate name` after your `conda create`?

**Comment by GeoffNN** [comment]
I did `source activate name`. The installation worked with `pip` but not with `conda`. Here are the outputs you asked for (after the installation with pip on the env).

Here's the output of `conda info`: 
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /home/geoff/anaconda3  (writable)
    default environment : /home/geoff/anaconda3/envs/umkl
       envs directories : /home/geoff/anaconda3/envs
                          /home/geoff/.conda/envs
          package cache : /home/geoff/anaconda3/pkgs
                          /home/geoff/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.2 Linux/4.4.0-75-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

And of `conda list --show-channels-urls`:
# packages in environment at /home/geoff/anaconda3/envs/umkl:
#
bleach                    2.0.0                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.11                    <pip>
entrypoints               0.2.2                     <pip>
html5lib                  0.999999999               <pip>
ipykernel                 4.6.1                     <pip>
ipython                   6.0.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                6.0.0                     <pip>
jedi                      0.10.2                    <pip>
Jinja2                    2.9.6                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.0.1                     <pip>
jupyter-console           5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.0.0                     <pip>
mistune                   0.7.4                     <pip>
nbconvert                 5.1.1                     <pip>
nbformat                  4.3.0                     <pip>
notebook                  5.0.0                     <pip>
numpy                     1.12.1                    <pip>
openssl                   1.0.2k                        1    defaults
pandas                    0.19.2                    <pip>
pandocfilters             1.4.1                     <pip>
pexpect                   4.2.1                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py35_1    defaults
prompt-toolkit            1.0.14                    <pip>
ptyprocess                0.5.1                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.5.3                         1    defaults
python-dateutil           2.6.0                     <pip>
pytz                      2017.2                    <pip>
pyzmq                     16.0.2                    <pip>
qtconsole                 4.3.0                     <pip>
readline                  6.2                           2    defaults
scikit-learn              0.18.1                    <pip>
scipy                     0.19.0                    <pip>
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>
sklearn                   0.0                       <pip>
sqlite                    3.13.0                        0    defaults
terminado                 0.6                       <pip>
testpath                  0.3                       <pip>
tk                        8.5.18                        0    defaults
tornado                   4.5.1                     <pip>
traitlets                 4.3.2                     <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        2.0.0                     <pip>
xz                        5.2.2                         1    defaults
zlib                      1.2.8                         3    defaults

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1645
