### ISSUE TITLE
re-implement --override-channels

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5158]
Work out a way for `--override-channels` to start working again, without violating the security model.

Will probably need to add an `#!exclude` flag for sequence config parameters as part of this task.

**Comment by kalefranz** [comment]
Also `allow_other_channels` per #4026.

**Comment by mbrbus** [comment]
Any news on this bug ?

**Comment by jjhelmus** [comment]
A workaround for this issue is to temporarily add the lines 

```
default_channels: [] 
channels: []
```

to the `.condarc` file.  This seems to disable all channels except those specified on the command line.

**Comment by kalefranz** [comment]
Turns out, this is already done in 4.4.  I think it has been for a while.  There's PR #6467, but it's only a one-line change.  `--override-channels` should be functioning correctly in the latest 4.4.0rc, and if not, then we should create a new issue.
