### ISSUE TITLE
default path prefix on Windows for new env seems to have extra "conda"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5164]
Using virgin Anaconda 4.3.1 on Windows 10 (Python 3.6), I do:

```
> conda create -n py36 python=3.6
```

And the installation directory is:

```
C:\Users\builder\AppData\Local\conda\conda\envs\py36
```

To my eye there is an extra `conda` in the env install path prefix.

**Comment by kalefranz** [comment]
Nope.  This is standard `appdirs` I think.  https://github.com/ActiveState/appdirs  Conda is the org and the app here.  Just like github.com/conda/conda
