### ISSUE TITLE
Canonical way to backup all environments

### ISSUE THREAD

**Issue by DavidMertz** [conda/conda#5165]
From time to time, I update to the newest Anaconda distribution and/or move my work onto another machine.  An unfortunate side effect of this is that my conda environments are destroyed (or simply absent) in the process.

`conda env export` provides the basic capability for snapshotting a reproducible environment, but by default it is a manual process, subject to errors, to export a collection of environments.  As a hack on my own system, I use a small script `export-conda-envs` to meet my needs.  A corresponding `restore-conda-envs` is not shown, but is similarly crude.

It would be much nicer if there was an official command to perform this action of exporting all environments.

```bash
#!/bin/bash

NOW=$(date "+%Y-%m-%d")
mkdir $HOME/tmp/envs-$NOW
ENVS=$(conda env list | grep '^\w' | cut -d' ' -f1)
for env in $ENVS; do
    source activate $env
    conda env export > $HOME/tmp/envs-$NOW/$env.yml
    echo "Exporting $env"
done
```

**Comment by mmiladi** [comment]
This would be a very useful feature. I am backing up my homefolder with rsync. Entire ~/.miniconda folder is huge and unnecessary to be backedup and on the other hand I don't want to miss conda settings in case of system restore.

**Comment by DavidMertz** [comment]
Looking through old issues... was this added as a conda command of some sort (or something covering the same need?)

**Comment by holdenweb** [comment]
Glad to see this is still on the radar. I too have an "export all environments into a newly-created directory" script to create the necessary yaml files.

**Comment by rgiannico** [comment]
+1 For this feature. I'd love to have it!

**Comment by holdenweb** [comment]
@DavidMertz - would `conda-pack` fit your needs? If so I will undertake (when nagged, no doubt) to submit an addendum tot he documentation. Ref: https://github.com/conda/conda/issues/7779

**Comment by rgiannico** [comment]
> @DavidMertz - would `conda-pack` fit your needs? If so I will undertake (when nagged, no doubt) to submit an addendum to the documentation. Ref: #7779

I don't think it would. 
If I understand the documentation, `conda-pack` creates a .tar.gz from a single conda environment. 
It doesn't save ALL the environments, plus I believe the .yml format created by `conda env export` is the current "trusted and suggested" way to backup environments (as long as you accept "backup" means saving info to reproduce the env). 
My problem is (as the issue title) to backup ALL the environments together.
I like the idea to save them in different .yml files (as suggested by the issue opener trick) but I'd like to see it tested, formalized and wrapped into a trusted new "canonical way" command line (like `conda env export-all` for example).

**Comment by holdenweb** [comment]
OK, I'll look out my script and see if it would meet with your approval: in
summary, it iterates over `$(conda env list)` and creates a yaml file for
each one. Would that be any kind of a start?

Kind regards,
Steve

**Comment by holdenweb** [comment]
I suppose one option might be to choose between a yaml file and a complete
environment dump, since the latter (assuming the presence of conda-pack) is
just a different command in the same iteration ....

Kind regards,
Steve

**Comment by DavidMertz** [comment]
@holdenweb The script I started this issue with a few years ago does just what you describe, iterate over `conda env list`.  It's not a terrible approach or anything, but some sort of option in conda itself would definitely be better.

**Comment by holdenweb** [comment]
SO much easier to discuss it, though, isn't it? ;-)

Kind regards,
Steve

**Comment by rgiannico** [comment]
@DavidMertz  I totally agree. 
I like your script. I believe it's a nice solution and theoretically it should guarantee a full restore, but I'm not completely sure without in-deep testing. 

Do you think using your script in production to backup all conda envs is advisable ? Are you using it for this purpose? Have you ever successfully restored a functioning set of conda envs using this trick?

**Comment by johntiger1** [comment]
I think this is a great idea, and had the exact same thoughts. But without the _most important_ part, restoring and backup, it is difficult for me to adopt this. Has anyone tried this script and can report if it works for restoring environments, say a year later?

**Comment by raygozajk** [comment]
The problem I see with this way of doing it is that it has an expiration date depending on the availability of package versions in servers. I can see this failing once a cleanup of the servers for (very) old versions no longer present.

**Comment by holdenweb** [comment]
If the deprecation policies are clear for all components then a backed-up environment could have a predictable lifetime. Also, the deprecated software could be placed on an archival channel for such cases if there were sufficient demand.

**Comment by hanhanhan** [comment]
This is a tweak of @DavidMertz 's script for the switch to using `conda` instead of `source` and that it's a shell function, so [another step to call from a script](https://github.com/conda/conda/issues/7980/). 

```
NOW=$(date "+%Y-%m-%d")
CONDA_BASE=$(conda info --base)
CONDA_FUNCTION="etc/profile.d/conda.sh"
CONDA="$CONDA_BASE/$CONDA_FUNCTION"
source $CONDA

mkdir ./condaenvs-$NOW

ENVS=$(conda env list | grep '^\w' | cut -d' ' -f1)
for env in $ENVS; do
    conda activate $env
    conda env export > ./condaenvs-$NOW/$env.yml
    echo "Exporting $env"
done
```

**Comment by bgriffen** [comment]
Here is a python version...

```python
import subprocess as sub
import pandas as pd

# create list of current environments

sub.check_call(" ".join(['conda','env','list','>','envs.txt']),shell=True)

# load and parse environment names

envs = pd.read_csv("envs.txt",header=1)
env_names = envs['#'].str.split(expand=True)[0]

# write environment packages out

for env in env_names:
    print("Backing up...",env)
    cmd = "conda env export --name %s > %s.yml" % (env,env)
    sub.check_call(cmd,shell=True)
```

**Comment by mijoda** [comment]
> Here is a python version...

This is terrific, thanks!

Still, it would great if there was a single conda command that worked on all platforms...

**Comment by uldry** [comment]
I got sick of typing the conda command. (I have quite a few of them now) so I created a small script that can be turned into an executable with py2exe and put in your path.
It either exports the active env or all of them at once.

[SaveCondaEnvs](https://github.com/uldry/SmallButUseful/tree/main/SaveCondaEnvs)

**Comment by ghbrown** [comment]
Here's a Python version that doesn't rely on Pandas. Credit goes to **bgriffen**, my only real changes were in the parsing and the deletion of the `conda env list` dump file.

Also, `+1` for requesting a way to do this through conda itself.

```python
import subprocess as sub

envs_file='envs.txt'
# get current environments in file
sub.check_call(" ".join(['conda','env','list','>',envs_file]),shell=True)

# load and parse environment names
with open(envs_file,'r') as f:
    lines = f.readlines()
env_lines = lines[2:-1] #first two lines and last line contain no env info
env_names = [line.split()[0] for line in env_lines] #column 0 for env name

# write environment packages out
for env in env_names:
    print("Backing up...",env)
    cmd = "conda env export --name %s > %s.yml" % (env,env)
    sub.check_call(cmd,shell=True)

#delete envs_file
sub.check_call('rm -f '+envs_file,shell=True)
```

**Comment by pasquale90** [comment]
Bash script for importing multiple conda envs from yml files:
```restore-conda-envs.sh
#!/bin/bash

#define the path where the yml files are stored
envdir=$1
#provide some checks
if [[ -d "${envdir}" ]]
then
	echo "$envdir exists on your filesystem."
	if [[ "$envdir" != */ ]]
	then
		envdir=${envdir}/
	fi
else
	echo "No relative path ${newdir} found. Maybe try with an absolute path?"
fi


#list all yml files using their relative path
filepaths=$(ls -t ${envdir}*.yml)

#env will have the name of the file without the extension .yml
ext=".yml"
for filepath in $filepaths;do
	file=${filepath#$envdir}
	env=${file%$ext}
	echo "from file=${file} in filepath=${filepath}, a new environment is being created named ${env}"
	conda env update -n ${env} --file ${filepath}
done
```
for running : 
```
#Place script into a root_folder and the ymlfiles into root_folder/subdir
$ cd $root_folder
$ bash restore_conda_envs.sh <subdir where envs are included>
```

**Comment by joel-kelly** [comment]
Here is a slight tweak in this [gist](https://gist.github.com/joel-kelly/8ba25be161f5406a80de220adc1c6704) to the python solution posted by @bgriffen, I found it didn't work when the conda environment is installed outside of the default env directory.

**Comment by psychonaute** [comment]
I had to write the same snippet for PowerShell, I figured other might be interested:
```powershell
# build export path
$root = "D:\backups\py_envs"
$machine = $(hostname).ToLower()
$dateStr = Get-Date -Format "yyyy-MM-dd_HHmmss"
$path = [IO.Path]::Combine($root, $machine, 'windows', $dateStr)
md $path | Out-Null
echo "Creating directory: '$path'"

# get environement name list
$CmdOutput = @(conda env list)
$envs = foreach ($env in $CmdOutput.Where({ $_ -ne "" })){
    if ($env -notmatch "^#") {
        $env.split(" ")[0]
    }
}


foreach ($env in $envs){
    $filePath = [IO.Path]::Combine($path, "$env.yml")
    # echo $filePath
    $cmd = @(
        "conda"
        "env"
        "export"
        "--name",
        $env,
        ">",
        $filePath
    )
    $cmdStr = $cmd -join(" ")
    echo $cmdStr
    Invoke-Expression $cmdStr
}
```

PS: Probably not the most elegant way of doing it, but i'm no PS expert
