### ISSUE TITLE
Unsatisfiable package hints in conda build aren't very helpful

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#517]
If you conda build a package that has unsatisfiable runtime dependencies (like you build it for Python 3 but one of the runtime dependencies does not have a Python 3 version), then you just get `RuntimeError: Unsatisfiable package specifications
Hint: <the package you just built> has a conflict with the remaining packages`

Aside from the fact that you get a traceback, the hint is not very helpful, because it doesn't tell you what you really want to know, which is what the problem with your runtime dependencies is.

**Comment by kalefranz** [comment]
Plenty of tickets tracking `tag:solver-messaging`.
