### ISSUE TITLE
Conda HTTP Error hostname doesn't match

### ISSUE THREAD

**Issue by hal98x** [conda/conda#5170]
I have been getting the following error with conda whenever I try to update or install a package.
IT first occured after I did a conda update all. Any help would be greatly appreciated. This is on linux.

michael@michael-Bonobo-Professional:~$ conda update conda
Fetching package metadata .../home/michael/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/home/michael/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
ERROR requests.packages.urllib3.connection:_match_hostname(353): Certificate did not match expected hostname: conda.anaconda.org. Certificate: {'subjectAltName': [], 'subject': ((('commonName', u'ssl383846.cloudflaressl.com'),),)}
ERROR requests.packages.urllib3.connection:_match_hostname(353): Certificate did not match expected hostname: conda.anaconda.org. Certificate: {'subjectAltName': [], 'subject': ((('commonName', u'ssl383846.cloudflaressl.com'),),)}

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
SSLError(SSLError(CertificateError("hostname 'conda.anaconda.org' doesn't match u'ssl383846.cloudflaressl.com'",),),)

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by hal98x** [comment]
michael@michael-Bonobo-Professional:~$ conda info --envs
# conda environments:
#
fatiando                 /home/michael/anaconda/envs/fatiando
geophysics               /home/michael/anaconda/envs/geophysics
jptest                   /home/michael/anaconda/envs/jptest
steno                    /home/michael/anaconda/envs/steno
testgeo                  /home/michael/anaconda/envs/testgeo
root                  *  /home/michael/anaconda

michael@michael-Bonobo-Professional:~$ ^C
michael@michael-Bonobo-Professional:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/michael/anaconda  (writable)
    default environment : /home/michael/anaconda
       envs directories : /home/michael/anaconda/envs
          package cache : /home/michael/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/michael/.condarc
           offline mode : False

**Comment by kalefranz** [comment]
I'm not sure what's going on exactly.  The subject alt name is there.

```
kfranz@0283:~/continuum/conda *fish-ps1-starter ❯ openssl s_client -servername conda.anaconda.org -connect conda.anaconda.org:443 2>/dev/null | openssl x509 -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a1:43:db:7c:4a:8e:29:8f:b5:13:13:cb:99:c9:03:f4
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO RSA Domain Validation Secure Server CA 2
        Validity
            Not Before: Apr  8 00:00:00 2017 GMT
            Not After : Oct 15 23:59:59 2017 GMT
        Subject: OU=Domain Control Validated, OU=PositiveSSL Multi-Domain, CN=ssl383845.cloudflaressl.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:ab:f2:f6:a4:fb:85:5b:71:ed:50:5b:bc:6b:81:
                    7d:8f:d3:25:4a:56:07:e2:8a:b0:37:b2:05:c4:fa:
                    95:6d:5b:b3:5b:a1:7a:c5:19:71:93:2d:60:0b:65:
                    49:9d:2c:ce:b7:c9:26:cd:78:97:75:28:64:2d:e7:
                    4b:c5:b5:9b:cf:44:7d:b1:6c:f8:79:8d:1c:fb:94:
                    18:35:d3:9c:34:28:a9:7a:91:17:f7:0a:fa:5a:11:
                    b7:b3:f6:c1:74:1f:de:f1:eb:d6:21:c4:50:76:da:
                    e7:17:41:f7:e9:da:b2:09:59:2e:19:09:0e:f8:60:
                    c5:5e:80:37:36:8b:b4:e8:3f:16:d5:83:d7:0f:e0:
                    b4:cd:22:20:fb:3e:99:7e:74:54:9d:92:52:52:42:
                    6c:7d:ee:e4:6c:b3:58:14:ae:f0:92:b2:17:63:30:
                    b7:b4:a5:8b:fc:f4:1d:6a:6a:d9:c2:5a:e8:d0:4d:
                    23:06:7c:c0:ba:c5:e1:5c:16:f2:d2:7f:75:ee:1d:
                    2f:6a:c1:ec:a7:55:11:4a:84:0e:21:37:e5:6f:70:
                    5f:32:cc:22:d6:48:49:5a:1d:ae:77:5f:f2:69:5f:
                    aa:38:da:ae:5b:fb:76:e7:d2:9e:60:c3:72:b7:ab:
                    5e:1b:6f:77:5a:a0:c5:42:4a:7e:ab:d7:87:53:06:
                    7a:1b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier:
                keyid:D4:B0:F4:FD:4F:9C:42:A4:6C:DC:3D:2E:EE:5B:41:18:C9:AD:03:F6

            X509v3 Subject Key Identifier:
                54:4C:E7:29:D0:1B:77:4F:A7:E0:6A:89:3A:79:EE:3B:E4:5F:D1:5D
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Certificate Policies:
                Policy: 1.3.6.1.4.1.6449.1.2.2.7
                  CPS: https://secure.comodo.com/CPS
                Policy: 2.23.140.1.2.1

            X509v3 CRL Distribution Points:
                URI:http://crl.comodoca4.com/COMODORSADomainValidationSecureServerCA2.crl

            Authority Information Access:
                CA Issuers - URI:http://crt.comodoca4.com/COMODORSADomainValidationSecureServerCA2.crt
                OCSP - URI:http://ocsp.comodoca4.com

            X509v3 Subject Alternative Name:
                DNS:ssl383845.cloudflaressl.com, DNS:*.anaconda.org, DNS:anaconda.org
    Signature Algorithm: sha256WithRSAEncryption
        38:7c:a8:fb:43:0b:77:24:ed:c8:2f:51:03:53:fc:ac:47:78:
        07:5e:5e:90:dd:51:30:17:8e:7d:36:71:2f:06:ca:ef:3e:11:
        10:c2:6a:51:fe:ed:0d:c2:d2:e1:7e:fa:62:3c:9b:de:62:22:
        83:73:f1:b6:a6:44:5d:e8:dd:c3:3d:b8:0f:c6:98:a7:db:d6:
        b0:2d:6b:20:fb:93:1c:80:a9:a8:01:03:d1:ba:a6:40:91:49:
        f3:66:49:71:9b:0b:cb:db:d5:a9:b6:94:76:b0:f0:5c:72:df:
        9f:6f:d2:05:25:98:7a:61:9a:ef:d4:13:4f:7b:91:0e:a6:80:
        1f:a3:85:99:6b:cc:07:2a:2c:4e:82:50:b5:45:b5:71:c2:c5:
        61:c0:ee:2f:f2:a2:41:6f:a8:0f:6c:cb:5e:c6:46:b5:d6:c7:
        40:92:5a:a9:24:69:71:d2:69:48:49:d6:57:df:d3:ac:df:c9:
        5b:a3:07:8d:68:fb:5b:4c:14:7c:6a:7c:18:d7:55:70:b8:b7:
        ad:0d:21:bc:77:91:b7:57:f3:64:ac:45:84:e0:fd:18:04:89:
        c9:6b:dc:65:8c:b8:36:7d:d5:39:81:60:b3:de:06:af:f7:f7:
        45:08:d3:45:cf:f5:8c:cc:6b:0d:ca:46:a6:ec:80:5e:3c:eb:
        67:77:40:e4
-----BEGIN CERTIFICATE-----
MIIFhzCCBG+gAwIBAgIRAKFD23xKjimPtRMTy5nJA/QwDQYJKoZIhvcNAQELBQAw
gZIxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTgwNgYD
VQQDEy9DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EgMjAeFw0xNzA0MDgwMDAwMDBaFw0xNzEwMTUyMzU5NTlaMGwxITAfBgNVBAsT
GERvbWFpbiBDb250cm9sIFZhbGlkYXRlZDEhMB8GA1UECxMYUG9zaXRpdmVTU0wg
TXVsdGktRG9tYWluMSQwIgYDVQQDExtzc2wzODM4NDUuY2xvdWRmbGFyZXNzbC5j
b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCr8vak+4Vbce1QW7xr
gX2P0yVKVgfiirA3sgXE+pVtW7NboXrFGXGTLWALZUmdLM63ySbNeJd1KGQt50vF
tZvPRH2xbPh5jRz7lBg105w0KKl6kRf3CvpaEbez9sF0H97x69YhxFB22ucXQffp
2rIJWS4ZCQ74YMVegDc2i7ToPxbVg9cP4LTNIiD7Ppl+dFSdklJSQmx97uRss1gU
rvCSshdjMLe0pYv89B1qatnCWujQTSMGfMC6xeFcFvLSf3XuHS9qweynVRFKhA4h
N+VvcF8yzCLWSElaHa53X/JpX6o42q5b+3bn0p5gw3K3q14bb3daoMVCSn6r14dT
BnobAgMBAAGjggH7MIIB9zAfBgNVHSMEGDAWgBTUsPT9T5xCpGzcPS7uW0EYya0D
9jAdBgNVHQ4EFgQUVEznKdAbd0+n4GqJOnnuO+Rf0V0wDgYDVR0PAQH/BAQDAgWg
MAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCME8G
A1UdIARIMEYwOgYLKwYBBAGyMQECAgcwKzApBggrBgEFBQcCARYdaHR0cHM6Ly9z
ZWN1cmUuY29tb2RvLmNvbS9DUFMwCAYGZ4EMAQIBMFYGA1UdHwRPME0wS6BJoEeG
RWh0dHA6Ly9jcmwuY29tb2RvY2E0LmNvbS9DT01PRE9SU0FEb21haW5WYWxpZGF0
aW9uU2VjdXJlU2VydmVyQ0EyLmNybDCBiAYIKwYBBQUHAQEEfDB6MFEGCCsGAQUF
BzAChkVodHRwOi8vY3J0LmNvbW9kb2NhNC5jb20vQ09NT0RPUlNBRG9tYWluVmFs
aWRhdGlvblNlY3VyZVNlcnZlckNBMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9v
Y3NwLmNvbW9kb2NhNC5jb20wRAYDVR0RBD0wO4Ibc3NsMzgzODQ1LmNsb3VkZmxh
cmVzc2wuY29tgg4qLmFuYWNvbmRhLm9yZ4IMYW5hY29uZGEub3JnMA0GCSqGSIb3
DQEBCwUAA4IBAQA4fKj7Qwt3JO3IL1EDU/ysR3gHXl6Q3VEwF459NnEvBsrvPhEQ
wmpR/u0NwtLhfvpiPJveYiKDc/G2pkRd6N3DPbgPxpin29awLWsg+5McgKmoAQPR
uqZAkUnzZklxmwvL29WptpR2sPBcct+fb9IFJZh6YZrv1BNPe5EOpoAfo4WZa8wH
KixOglC1RbVxwsVhwO4v8qJBb6gPbMtexka11sdAklqpJGlx0mlISdZX39Os38lb
oweNaPtbTBR8anwY11VwuLetDSG8d5G3V/NkrEWE4P0YBInJa9xljLg2fdU5gWCz
3gav9/dFCNNFz/WMzGsNykam7IBePOtnd0Dk
-----END CERTIFICATE-----
```

**Comment by kalefranz** [comment]
If you want, you can try

    CONDA_SSL_VERIFY=false conda update conda requests pyopenssl cryptography

Remove the conda-forge channel when you do.

**Comment by hal98x** [comment]
Awesome thank you for the shortcut to turn off ssl verification. The command helped to clear out whatever conda error there was and conda is now running just fine.

**Comment by ScarabMonkey** [comment]
Just a note to say this solution assumes you are using bash. Here is the equivalent for tcsh:
% setenv CONDA_SSL_VERIFY false
% conda update conda requests pyopenssl cryptography

**Comment by swails** [comment]
I know this is an old thread, but I see it referenced when this error pops up with a suggestion to do the following:

> If you want, you can try
> 
> ```
> CONDA_SSL_VERIFY=false conda update conda requests pyopenssl cryptography
> ```
> 
> Remove the conda-forge channel when you do.

Since this doesn't come with a caveat or warning about what this actually does, I wanted to add it to the thread so people that come here at least see the warning.

Disabling TLS host verification eliminates the principle protection that TLS provides in this instance -- namely ensuring you trust the source you're fetching the packages from (sure, it still encrypts the content that's sent, but it's just sending open-source Python packages).

When you set this environment variable, you are ignoring both the benign warnings (like in this case) and the malicious warnings if someone tries to spoof conda to get you to install malicious packages in your machine.

My advice is don't get in the habit of sidestepping TLS issues (listen to your browser when it says avoid going to a website due to certificate issues and *don't* skip TLS verification like this).
