### ISSUE TITLE
Trying to run <conda env update>

### ISSUE THREAD

**Issue by Streich676** [conda/conda#5173]
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /Users/christopherstreich/anaconda2  (writable)
    default environment : /Users/christopherstreich/anaconda2
       envs directories : /Users/christopherstreich/anaconda2/envs
          package cache : /Users/christopherstreich/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/christopherstreich/anaconda2/bin/conda-env update`

    Traceback (most recent call last):
      File "/Users/christopherstreich/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/christopherstreich/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 77, in execute
        directory=os.getcwd())
      File "/Users/christopherstreich/anaconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by tyler-thetyrant** [comment]
You are using very outdate version of conda! `conda update conda` will bring you to 4.3.16.
Can you try again with the most recent conda?
