### ISSUE TITLE
conda build purge-all not documented

### ISSUE THREAD

**Issue by rmancy-smg** [conda/conda#5174]
Hi,

My specific situation was this. I am building and installing conda packages locally. I decided to update the meta.yaml to include new dependencies. I then ran the following:
>$ conda build purge
>$ conda build --build-only
>$ conda install --use-local my-package

However it did not pick up the new dependency. From looking at the source code, it seems that purge only cleans the build, and because the build string would have stayed the same as before (I was still testing so I hadn't rev'ed the build or version) I guess it was picking up the old tarball, which has the meta.yaml including deps??

Anyway, I noticed in the source there was a 'purge-all' which removed the tarballs as well. This solved my problem. I can't find any docs or reference to this command, not even in the argparse output.

**Comment by msarahan** [comment]
Issue moved to [conda/conda-build #1965](https://github.com/conda/conda-build/issues/1965) via [**ZenHub**](https://www.zenhub.com/)
