### ISSUE TITLE
conda install --use-local not working after conda-build --build-only

### ISSUE THREAD

**Issue by rmancy-smg** [conda/conda#5175]
Hi,

Running `conda build --build-only my_package` does not put any tarballs into the `conda-bld` directory. I would have expected a build system to create a tarball as part of the output.

When `conda install --use-local my_package` runs, it looks in the `conda-bld` directory, but can't find the tarball and so fails. Of course, this problem doesn't come about if you just run `conda build my_package`. I suspect this is because it needs to install the package into a test environment, and thus the tarball would have to be created in the process.

I'm not sure if this behaviour is by design, or if I'm doing something else wrong, but I certainly didn't expect it.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1966
