### ISSUE TITLE
Autoactivate a conda environment when entering a directory.

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [conda/conda#5179]
Is there a way to automatically activate a Conda environment when entering a folder ? 

I know Pyenv has this option, but I did not find anything on Stackoverflow or Github.

I found this [file](<script src="https://gist.github.com/sotte/8fb92dff17264c7a2a85.js"></script>),

but I am wondering what is the official way of doing this ?

**Comment by kalefranz** [comment]
Right now, no.  Nice feature request though.

**Comment by janschulz** [comment]
If you want to do it in the commandline (bash/zsh) there are easy options:
* https://github.com/kennethreitz/autoenv (bash, etc)
* https://github.com/Tarrasch/zsh-autoenv (zsh)

**Comment by janosh** [comment]
I recently wrote a [blog post about this](https://janosh.io/blog/conda-auto-env).

**Comment by guicho271828** [comment]
alternatively, you can add this to .bashrc:

```
if [ -f $PWD/.bashrc ]
then
    source $PWD/.bashrc
fi
```

then add your local .bashrc in your repository:
```
conda activate <your env>
```

**Comment by daniellepintz** [comment]
@guicho271828 do you mean put the first commands in `$HOME/.bashrc` and the second command `conda activate <your env>` in the directory's `.bashrc`? That is what I tried and I am getting a bunch of errors like this:
```
-bash: /usr/local/bin/date: Argument list too long
-bash: /bin/id: Argument list too long
``` 
when I run `source $HOME/.bashrc`

**Comment by guicho271828** [comment]
@daniellepintz 
I don't know what is your error, it should be some unrelated error in your script.
btw I modifed the comment to avoid infinite recursion

**Comment by guicho271828** [comment]
> do you mean put the first commands in $HOME/.bashrc and the second command conda activate <your env> in the directory's .bashrc


yes, that is what I meant

**Comment by daniellepintz** [comment]
thanks @guicho271828! I was able to get it to work by putting this into my `$HOME/.bashrc`
```
cd() { builtin cd "$@" &&
if [ "$1" == "pytorch-lightning/" ]; then
   conda activate pl
fi
if [ "$1" == "" ]; then
   conda deactivate
fi     }
```

**Comment by patrickjwright** [comment]
Why was this closed? This would be a great feature for conda to have, and it seems like it has not yet been implemented.

**Comment by vallops99** [comment]
Hello everyone, I wrote a little script to be added in the shell profile file [conda-autoactivate-env](https://github.com/vallops99/Conda-autoactivate-env).

It basically extends the CD command in order to search for a `.conda_config` file that will contain the env name to be activated.
This means that, by following the pyenv road, you need to create a `.conda_config` file to specify which env to activate inside the directory you want the env to be activated.

I'll copy/paste the script there to let the research be easier without switching through another tab.

```sh
export CONDACONFIGDIR=""
cd() { builtin cd "$@" && 
if [ -f $PWD/.conda_config ]; then
    export CONDACONFIGDIR=$PWD
    conda activate $(cat .conda_config)
elif [ "$CONDACONFIGDIR" ]; then
    if [[ $PWD != *"$CONDACONFIGDIR"* ]]; then
	export CONDACONFIGDIR=""
	conda deactivate
    fi
fi }
```

Bear in mind that this is a workaround.

**Comment by wise-east** [comment]
I've used @vallops99  and it works great!

**Comment by togume** [comment]
It would be great to have a firs-class citizen feature for this. Using many other environment tools (NVM, ASDF, etc), when you enter a directory there's a config, rc-file, or similar, which auto-enables what's needed to run the project.
