### ISSUE TITLE
conda update --all failing with "Access is denied" error

### ISSUE THREAD

**Issue by surajitsen** [conda/conda#5180]
Post installation anaconda version 4.0.5 on Windows 10 (64 bit) environment, when I'm trying to update conda with command "conda update --all", its throwing "WindowsError: [Error 5] Access is denied" error.

**Detail Error Message:** 
[Conda-Update-Error.txt](https://github.com/conda/conda/files/964057/Conda-Update-Error.txt)

**Here is the output of conda info:**
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://conda.anaconda.org/spacy/win-64/
                        https://conda.anaconda.org/spacy/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\surajie\.condarc
    is foreign system : False

Kindly help me to overcome this issue.

**Comment by kalefranz** [comment]
Multi-user problem fixed in conda 4.3.  Probably conda >= 4.3.13.

**Comment by surajitsen** [comment]
As per your advise, I installed conda version 4.3.17, but getting same "Access denied" error.

C:\Users\surajie>conda --version
**conda 4.3.17**

**Detail Error Message:**
C:\Users\surajie>conda update --all
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2:

The following NEW packages will be INSTALLED:

    notebook: 4.3.1-py27_2

Proceed ([y]/n)? y

CondaError: WindowsError(5, 'Access is denied')
CondaError: WindowsError(5, 'Access is denied')
CondaError: WindowsError(5, 'Access is denied')

**Output of conda info:**
    Current conda install:

                   platform : win-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : not installed
             python version : 2.7.13.final.0
           requests version : 2.12.4
           root environment : C:\Anaconda2  (writable)
        default environment : C:\Anaconda2
           envs directories : C:\Anaconda2\envs
                          C:\Users\surajie\AppData\Local\conda\conda\envs
                          C:\Users\surajie\.conda\envs
              package cache : C:\Anaconda2\pkgs
                          C:\Users\surajie\AppData\Local\conda\conda\pkgs
               channel URLs : https://conda.anaconda.org/spacy/win-64
                          https://conda.anaconda.org/spacy/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                config file : C:\Users\surajie\.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

Kindly help to resolve the issue. I got badly stuck. I had to reinstall OS due to some technical issues, and now unable to get my anaconda python development environment back.
