### ISSUE TITLE
Tracking for original generic shell support work

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5183]
Original PR: https://github.com/conda/conda/pull/3175

Follow-on PRs:
  * https://github.com/conda/conda/pull/3959
  * https://github.com/conda/conda/pull/3960
  * https://github.com/conda/conda/pull/3987
  * https://github.com/conda/conda/pull/4018

Related open issues:
  * https://github.com/conda/conda/issues/3176
  * https://github.com/conda/conda/issues/2747
  * https://github.com/conda/conda/issues/3808
  * https://github.com/conda/conda/issues/3511
  * https://github.com/conda/conda/issues/626
  * https://github.com/conda/conda/issues/3128

**Comment by kalefranz** [comment]
@njalerikson I'm going to go ahead and close these follow-on PRs.  *So* much of this work I want to bring in.  The tests, especially, are awesome.  The new framework lets us be a little more strategic with tests.  With that I mean the logic only has to be tested once, with python unit tests, and not with full integration tests fanned out to all supported shells.

Making this ticket in particular so we have a handle on all of this and none of it gets lost.

**Comment by DarthSpock** [comment]
Pinging for attention since powershell is being stupid on Win 7 (I did upgrade to latest PS).

**Comment by kalefranz** [comment]
Powershell support is in conda 4.6. This is an old issue and can be closed.
