### ISSUE TITLE
conda command not found

### ISSUE THREAD

**Issue by SiriusYou** [conda/conda#5194]
Dear,

I have a problem with my terminal:

Last login: Thu Apr 27 22:49:56 on ttys000
youjia ~ $ conda env --help
-bash: conda: command not found
youjia ~ $ conda --verson
-bash: conda: command not found
youjia ~ $ pwd
/Users/youjia
youjia ~ $ cd /Users/youjia/anaconda
youjia anaconda $ conda --version
-bash: conda: command not found
youjia anaconda $ conda update conda
-bash: conda: command not found
youjia anaconda $ 

I cannot figure out what's wrong with my terminal?

**Comment by tyler-thetyrant** [comment]
This isn't a conda problem
Seems like Conda isn't added to your path. Did you install conda properly? 
[Here](https://conda.io/docs/install/quick.html) is an official installation instruction.
