### ISSUE TITLE
Kernel dies using AWS EC2 ubuntu16.04

### ISSUE THREAD

**Issue by camilogavo** [conda/conda#5197]
Hi, I was trying to run Python and R in a new instance created in AWS-EC2. But after open a new notebook, kernel Restart and after that it dies with no specific message that may refer me.

Do you guys have any idea how to deal with issue?

The OS is ubuntu 16.04

Conda info

ubuntu@ip-172-31-68-109:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : /home/ubuntu/anaconda3  (writable)
    default environment : /home/ubuntu/anaconda3
       envs directories : /home/ubuntu/anaconda3/envs
                          /home/ubuntu/.conda/envs
          package cache : /home/ubuntu/anaconda3/pkgs
                          /home/ubuntu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.0 Linux/4.4.0-1013-aws debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

Conda list 

ubuntu@ip-172-31-68-109:~$ conda list
# packages in environment at /home/ubuntu/anaconda3:
#
_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.5.2                    py36_0  
anaconda-project          0.4.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3.2               np111py36_0  
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_0  
boto                      2.46.1                   py36_0  
bottleneck                1.2.0               np111py36_0  
bzip2                     1.0.6                         3  
cairo                     1.14.8                        0  
cffi                      1.9.1                    py36_0  
chardet                   3.0.2                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.16                   py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.1                   py36_0  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.6                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_1  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12.1                   py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
gmp                       6.1.0                         0  
greenlet                  0.4.12                   py36_0  
gsl                       2.2.1                         0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np111py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.6.1                    py36_0  
ipython                   5.1.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.17.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
ncurses                   5.9                          10  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numba                     0.32.0              np111py36_0  
numexpr                   2.6.2               np111py36_0  
numpy                     1.11.3                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py36_1  
pandoc                    1.15.0.6                      0  
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
partd                     0.3.7                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.1.0                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
ply                       3.10                     py36_0  
prompt_toolkit            1.0.14                   py36_0  
psutil                    5.2.2                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.2.3                    py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np111py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
r-assertthat              0.1                    r3.3.2_4  
r-backports               1.0.4                  r3.3.2_0  
r-base                    3.3.2                         1    r
r-base64enc               0.1_3                  r3.3.2_0  
r-bh                      1.62.0_1               r3.3.2_0  
r-bitops                  1.0_6                  r3.3.2_2  
r-boot                    1.3_18                 r3.3.2_0  
r-broom                   0.4.1                  r3.3.2_0  
r-car                     2.1_4                  r3.3.2_0  
r-caret                   6.0_73                 r3.3.2_0  
r-catools                 1.17.1                 r3.3.2_2  
r-class                   7.3_14                 r3.3.2_0  
r-cluster                 2.0.5                  r3.3.2_0  
r-codetools               0.2_15                 r3.3.2_0  
r-colorspace              1.3_1                  r3.3.2_0  
r-crayon                  1.3.2                  r3.3.2_0  
r-curl                    2.3                    r3.3.2_0  
r-data.table              1.10.0                 r3.3.2_0  
r-dbi                     0.5_1                  r3.3.2_0  
r-dichromat               2.0_0                  r3.3.2_2  
r-digest                  0.6.10                 r3.3.2_0  
r-dplyr                   0.5.0                  r3.3.2_0  
r-essentials              1.5.2                  r3.3.2_0  
r-evaluate                0.10                   r3.3.2_0  
r-forcats                 0.1.1                  r3.3.2_0  
r-foreach                 1.4.3                  r3.3.2_0  
r-forecast                7.3                    r3.3.2_0  
r-foreign                 0.8_67                 r3.3.2_0  
r-formatr                 1.4                    r3.3.2_0  
r-fracdiff                1.4_2                  r3.3.2_2  
r-ggplot2                 2.2.0                  r3.3.2_0  
r-gistr                   0.3.6                  r3.3.2_0  
r-glmnet                  2.0_5                  r3.3.2_0  
r-gtable                  0.2.0                  r3.3.2_0  
r-haven                   1.0.0                  r3.3.2_0  
r-hexbin                  1.27.1                 r3.3.2_0  
r-highr                   0.6                    r3.3.2_0  
r-hms                     0.3                    r3.3.2_0  
r-htmltools               0.3.5                  r3.3.2_0  
r-htmlwidgets             0.8                    r3.3.2_0  
r-httpuv                  1.3.3                  r3.3.2_0  
r-httr                    1.2.1                  r3.3.2_0  
r-irdisplay               0.4.4                  r3.3.2_0  
r-irkernel                0.7.1                  r3.3.2_0  
r-iterators               1.0.8                  r3.3.2_0  
r-jsonlite                1.1                    r3.3.2_0  
r-kernsmooth              2.23_15                r3.3.2_0  
r-knitr                   1.15.1                 r3.3.2_0  
r-labeling                0.3                    r3.3.2_2  
r-lattice                 0.20_34                r3.3.2_0  
r-lazyeval                0.2.0                  r3.3.2_0  
r-lme4                    1.1_12                 r3.3.2_0  
r-lubridate               1.6.0                  r3.3.2_0  
r-magrittr                1.5                    r3.3.2_2  
r-maps                    3.1.1                  r3.3.2_0  
r-markdown                0.7.7                  r3.3.2_2  
r-mass                    7.3_45                 r3.3.2_0  
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0  
r-mgcv                    1.8_16                 r3.3.2_0  
r-mime                    0.5                    r3.3.2_0  
r-minqa                   1.2.4                  r3.3.2_2  
r-mnormt                  1.5_5                  r3.3.2_0  
r-modelmetrics            1.1.0                  r3.3.2_0  
r-modelr                  0.1.0                  r3.3.2_0  
r-munsell                 0.4.3                  r3.3.2_0  
r-nlme                    3.1_128                r3.3.2_0  
r-nloptr                  1.0.4                  r3.3.2_2  
r-nnet                    7.3_12                 r3.3.2_0  
r-openssl                 0.9.5                  r3.3.2_0  
r-pbdzmq                  0.2_4                  r3.3.2_0  
r-pbkrtest                0.4_6                  r3.3.2_0  
r-plyr                    1.8.4                  r3.3.2_0  
r-pryr                    0.1.2                  r3.3.2_0  
r-psych                   1.6.9                  r3.3.2_0  
r-purrr                   0.2.2                  r3.3.2_0  
r-quadprog                1.5_5                  r3.3.2_2  
r-quantmod                0.4_7                  r3.3.2_0  
r-quantreg                5.29                   r3.3.2_0  
r-r6                      2.2.0                  r3.3.2_0  
r-randomforest            4.6_12                 r3.3.2_0  
r-rbokeh                  0.5.0                  r3.3.2_0  
r-rcolorbrewer            1.1_2                  r3.3.2_3  
r-rcpp                    0.12.8                 r3.3.2_0  
r-rcpparmadillo           0.7.500.0.0            r3.3.2_0  
r-rcppeigen               0.3.2.9.0              r3.3.2_0  
r-readr                   1.0.0                  r3.3.2_0  
r-readxl                  0.1.1                  r3.3.2_0  
r-recommended             3.3.2                  r3.3.2_0  
r-repr                    0.10                   r3.3.2_0  
r-reshape2                1.4.2                  r3.3.2_0  
r-rmarkdown               1.3                    r3.3.2_0  
r-rpart                   4.1_10                 r3.3.2_0  
r-rprojroot               1.1                    r3.3.2_0  
r-rvest                   0.3.2                  r3.3.2_0  
r-scales                  0.4.1                  r3.3.2_0  
r-selectr                 0.3_0                  r3.3.2_0  
r-shiny                   0.14.2                 r3.3.2_0  
r-sourcetools             0.1.5                  r3.3.2_0  
r-sparsem                 1.74                   r3.3.2_0  
r-spatial                 7.3_11                 r3.3.2_0  
r-stringi                 1.1.2                  r3.3.2_0  
r-stringr                 1.1.0                  r3.3.2_0  
r-survival                2.40_1                 r3.3.2_0  
r-tibble                  1.2                    r3.3.2_0  
r-tidyr                   0.6.0                  r3.3.2_0  
r-tidyverse               1.0.0                  r3.3.2_0  
r-timedate                3012.100               r3.3.2_2  
r-tseries                 0.10_35                r3.3.2_0  
r-ttr                     0.23_1                 r3.3.2_0  
r-uuid                    0.1_2                  r3.3.2_0  
r-xml2                    1.0.0                  r3.3.2_0  
r-xtable                  1.8_2                  r3.3.2_0  
r-xts                     0.9_7                  r3.3.2_2  
r-yaml                    2.1.14                 r3.3.2_0  
r-zoo                     1.7_13                 r3.3.2_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.13.0                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np111py36_0  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.19.0              np111py36_0  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.4                    py36_0  
spyder                    3.1.3                    py36_0  
sqlalchemy                1.1.9                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np111py36_0  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.12.1                   py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.10                  py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  

Conda list --show-channel-urls

ubuntu@ip-172-31-68-109:~$ conda list --show-channel-urls
# packages in environment at /home/ubuntu/anaconda3:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.10                   py36_0    defaults
anaconda                  custom                   py36_0    defaults
anaconda-client           1.6.3                    py36_0    defaults
anaconda-navigator        1.5.2                    py36_0    defaults
anaconda-project          0.4.1                    py36_0    defaults
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3.2               np111py36_0    defaults
babel                     2.4.0                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.5.3                    py36_0    defaults
bitarray                  0.8.1                    py36_0    defaults
blaze                     0.10.1                   py36_0    defaults
bleach                    1.5.0                    py36_0    defaults
bokeh                     0.12.5                   py36_0    defaults
boto                      2.46.1                   py36_0    defaults
bottleneck                1.2.0               np111py36_0    defaults
bzip2                     1.0.6                         3    defaults
cairo                     1.14.8                        0    defaults
cffi                      1.9.1                    py36_0    defaults
chardet                   3.0.2                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.7                    py36_0    defaults
conda                     4.3.16                   py36_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py36_0    defaults
contextlib2               0.5.4                    py36_0    defaults
cryptography              1.7.1                    py36_0    defaults
curl                      7.52.1                        0    defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.14.1                   py36_0    defaults
datashape                 0.5.4                    py36_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.6                    py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_1    defaults
et_xmlfile                1.0.1                    py36_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12.1                   py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
get_terminal_size         1.0.0                    py36_0    defaults
gevent                    1.2.1                    py36_0    defaults
glib                      2.50.2                        1    defaults
gmp                       6.1.0                         0    defaults
greenlet                  0.4.12                   py36_0    defaults
gsl                       2.2.1                         0    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.7.0               np111py36_0    defaults
harfbuzz                  0.9.39                        2    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py36_1    defaults
html5lib                  0.999                    py36_0    defaults
icu                       54.1                          0    defaults
idna                      2.2                      py36_0    defaults
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.6.1                    py36_0    defaults
ipython                   5.1.0                    py36_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                6.0.0                    py36_0    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.9.0                    py36_1    defaults
jinja2                    2.9.6                    py36_0    defaults
jpeg                      9b                            0    defaults
jsonschema                2.6.0                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            5.0.1                    py36_0    defaults
jupyter_console           5.1.0                    py36_0    defaults
jupyter_core              4.3.0                    py36_0    defaults
lazy-object-proxy         1.2.2                    py36_0    defaults
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.27                        0    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         3    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.17.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.3                    py36_0    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.0.0               np111py36_0    defaults
mistune                   0.7.4                    py36_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mpmath                    0.19                     py36_1    defaults
multipledispatch          0.4.9                    py36_0    defaults
nbconvert                 5.1.1                    py36_0    defaults
nbformat                  4.3.0                    py36_0    defaults
ncurses                   5.9                          10    defaults
networkx                  1.11                     py36_0    defaults
nltk                      3.2.2                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  5.0.0                    py36_0    defaults
numba                     0.32.0              np111py36_0    defaults
numexpr                   2.6.2               np111py36_0    defaults
numpy                     1.11.3                   py36_0    defaults
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
olefile                   0.44                     py36_0    defaults
openpyxl                  2.4.1                    py36_0    defaults
openssl                   1.0.2k                        1    defaults
pandas                    0.19.2              np111py36_1    defaults
pandoc                    1.15.0.6                      0    defaults
pandocfilters             1.4.1                    py36_0    defaults
pango                     1.40.3                        1    defaults
partd                     0.3.7                    py36_0    defaults
path.py                   10.3.1                   py36_0    defaults
pathlib2                  2.2.1                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pcre                      8.39                          1    defaults
pep8                      1.7.0                    py36_0    defaults
pexpect                   4.2.1                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    4.1.0                    py36_0    defaults
pip                       9.0.1                    py36_1    defaults
pixman                    0.34.0                        0    defaults
ply                       3.10                     py36_0    defaults
prompt_toolkit            1.0.14                   py36_0    defaults
psutil                    5.2.2                    py36_0    defaults
ptyprocess                0.5.1                    py36_0    defaults
py                        1.4.32                   py36_0    defaults
pyasn1                    0.2.3                    py36_0    defaults
pycosat                   0.6.2                    py36_0    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_4    defaults
pycurl                    7.43.0                   py36_2    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.2.0                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyopenssl                 16.2.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pytables                  3.3.0               np111py36_0    defaults
pytest                    3.0.7                    py36_0    defaults
python                    3.6.0                         0    defaults
python-dateutil           2.6.0                    py36_0    defaults
pytz                      2017.2                   py36_0    defaults
pywavelets                0.5.2               np111py36_0    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                         3    defaults
qtawesome                 0.4.4                    py36_0    defaults
qtconsole                 4.3.0                    py36_0    defaults
qtpy                      1.2.1                    py36_0    defaults
r-assertthat              0.1                    r3.3.2_4    defaults
r-backports               1.0.4                  r3.3.2_0    defaults
r-base                    3.3.2                         1    r
r-base64enc               0.1_3                  r3.3.2_0    defaults
r-bh                      1.62.0_1               r3.3.2_0    defaults
r-bitops                  1.0_6                  r3.3.2_2    defaults
r-boot                    1.3_18                 r3.3.2_0    defaults
r-broom                   0.4.1                  r3.3.2_0    defaults
r-car                     2.1_4                  r3.3.2_0    defaults
r-caret                   6.0_73                 r3.3.2_0    defaults
r-catools                 1.17.1                 r3.3.2_2    defaults
r-class                   7.3_14                 r3.3.2_0    defaults
r-cluster                 2.0.5                  r3.3.2_0    defaults
r-codetools               0.2_15                 r3.3.2_0    defaults
r-colorspace              1.3_1                  r3.3.2_0    defaults
r-crayon                  1.3.2                  r3.3.2_0    defaults
r-curl                    2.3                    r3.3.2_0    defaults
r-data.table              1.10.0                 r3.3.2_0    defaults
r-dbi                     0.5_1                  r3.3.2_0    defaults
r-dichromat               2.0_0                  r3.3.2_2    defaults
r-digest                  0.6.10                 r3.3.2_0    defaults
r-dplyr                   0.5.0                  r3.3.2_0    defaults
r-essentials              1.5.2                  r3.3.2_0    defaults
r-evaluate                0.10                   r3.3.2_0    defaults
r-forcats                 0.1.1                  r3.3.2_0    defaults
r-foreach                 1.4.3                  r3.3.2_0    defaults
r-forecast                7.3                    r3.3.2_0    defaults
r-foreign                 0.8_67                 r3.3.2_0    defaults
r-formatr                 1.4                    r3.3.2_0    defaults
r-fracdiff                1.4_2                  r3.3.2_2    defaults
r-ggplot2                 2.2.0                  r3.3.2_0    defaults
r-gistr                   0.3.6                  r3.3.2_0    defaults
r-glmnet                  2.0_5                  r3.3.2_0    defaults
r-gtable                  0.2.0                  r3.3.2_0    defaults
r-haven                   1.0.0                  r3.3.2_0    defaults
r-hexbin                  1.27.1                 r3.3.2_0    defaults
r-highr                   0.6                    r3.3.2_0    defaults
r-hms                     0.3                    r3.3.2_0    defaults
r-htmltools               0.3.5                  r3.3.2_0    defaults
r-htmlwidgets             0.8                    r3.3.2_0    defaults
r-httpuv                  1.3.3                  r3.3.2_0    defaults
r-httr                    1.2.1                  r3.3.2_0    defaults
r-irdisplay               0.4.4                  r3.3.2_0    defaults
r-irkernel                0.7.1                  r3.3.2_0    defaults
r-iterators               1.0.8                  r3.3.2_0    defaults
r-jsonlite                1.1                    r3.3.2_0    defaults
r-kernsmooth              2.23_15                r3.3.2_0    defaults
r-knitr                   1.15.1                 r3.3.2_0    defaults
r-labeling                0.3                    r3.3.2_2    defaults
r-lattice                 0.20_34                r3.3.2_0    defaults
r-lazyeval                0.2.0                  r3.3.2_0    defaults
r-lme4                    1.1_12                 r3.3.2_0    defaults
r-lubridate               1.6.0                  r3.3.2_0    defaults
r-magrittr                1.5                    r3.3.2_2    defaults
r-maps                    3.1.1                  r3.3.2_0    defaults
r-markdown                0.7.7                  r3.3.2_2    defaults
r-mass                    7.3_45                 r3.3.2_0    defaults
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    defaults
r-mgcv                    1.8_16                 r3.3.2_0    defaults
r-mime                    0.5                    r3.3.2_0    defaults
r-minqa                   1.2.4                  r3.3.2_2    defaults
r-mnormt                  1.5_5                  r3.3.2_0    defaults
r-modelmetrics            1.1.0                  r3.3.2_0    defaults
r-modelr                  0.1.0                  r3.3.2_0    defaults
r-munsell                 0.4.3                  r3.3.2_0    defaults
r-nlme                    3.1_128                r3.3.2_0    defaults
r-nloptr                  1.0.4                  r3.3.2_2    defaults
r-nnet                    7.3_12                 r3.3.2_0    defaults
r-openssl                 0.9.5                  r3.3.2_0    defaults
r-pbdzmq                  0.2_4                  r3.3.2_0    defaults
r-pbkrtest                0.4_6                  r3.3.2_0    defaults
r-plyr                    1.8.4                  r3.3.2_0    defaults
r-pryr                    0.1.2                  r3.3.2_0    defaults
r-psych                   1.6.9                  r3.3.2_0    defaults
r-purrr                   0.2.2                  r3.3.2_0    defaults
r-quadprog                1.5_5                  r3.3.2_2    defaults
r-quantmod                0.4_7                  r3.3.2_0    defaults
r-quantreg                5.29                   r3.3.2_0    defaults
r-r6                      2.2.0                  r3.3.2_0    defaults
r-randomforest            4.6_12                 r3.3.2_0    defaults
r-rbokeh                  0.5.0                  r3.3.2_0    defaults
r-rcolorbrewer            1.1_2                  r3.3.2_3    defaults
r-rcpp                    0.12.8                 r3.3.2_0    defaults
r-rcpparmadillo           0.7.500.0.0            r3.3.2_0    defaults
r-rcppeigen               0.3.2.9.0              r3.3.2_0    defaults
r-readr                   1.0.0                  r3.3.2_0    defaults
r-readxl                  0.1.1                  r3.3.2_0    defaults
r-recommended             3.3.2                  r3.3.2_0    defaults
r-repr                    0.10                   r3.3.2_0    defaults
r-reshape2                1.4.2                  r3.3.2_0    defaults
r-rmarkdown               1.3                    r3.3.2_0    defaults
r-rpart                   4.1_10                 r3.3.2_0    defaults
r-rprojroot               1.1                    r3.3.2_0    defaults
r-rvest                   0.3.2                  r3.3.2_0    defaults
r-scales                  0.4.1                  r3.3.2_0    defaults
r-selectr                 0.3_0                  r3.3.2_0    defaults
r-shiny                   0.14.2                 r3.3.2_0    defaults
r-sourcetools             0.1.5                  r3.3.2_0    defaults
r-sparsem                 1.74                   r3.3.2_0    defaults
r-spatial                 7.3_11                 r3.3.2_0    defaults
r-stringi                 1.1.2                  r3.3.2_0    defaults
r-stringr                 1.1.0                  r3.3.2_0    defaults
r-survival                2.40_1                 r3.3.2_0    defaults
r-tibble                  1.2                    r3.3.2_0    defaults
r-tidyr                   0.6.0                  r3.3.2_0    defaults
r-tidyverse               1.0.0                  r3.3.2_0    defaults
r-timedate                3012.100               r3.3.2_2    defaults
r-tseries                 0.10_35                r3.3.2_0    defaults
r-ttr                     0.23_1                 r3.3.2_0    defaults
r-uuid                    0.1_2                  r3.3.2_0    defaults
r-xml2                    1.0.0                  r3.3.2_0    defaults
r-xtable                  1.8_2                  r3.3.2_0    defaults
r-xts                     0.9_7                  r3.3.2_2    defaults
r-yaml                    2.1.14                 r3.3.2_0    defaults
r-zoo                     1.7_13                 r3.3.2_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py36_0    defaults
requests                  2.13.0                   py36_0    defaults
rope                      0.9.4                    py36_1    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.13.0              np111py36_0    defaults
scikit-learn              0.18.1              np111py36_1    defaults
scipy                     0.19.0              np111py36_0    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sphinx                    1.5.4                    py36_0    defaults
spyder                    3.1.3                    py36_0    defaults
sqlalchemy                1.1.9                    py36_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.8.0               np111py36_0    defaults
sympy                     1.0                      py36_0    defaults
terminado                 0.6                      py36_0    defaults
testpath                  0.3                      py36_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.4.2                    py36_0    defaults
traitlets                 4.3.2                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.12.1                   py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        2.0.0                    py36_0    defaults
wrapt                     1.10.10                  py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.5                         0    defaults
zlib                      1.2.8                         3    defaults

**Comment by kalefranz** [comment]
> Do you guys have any idea how to deal with issue?

No clue, especially with the information given.  I do know this is the wrong issue tracker to get help.  There's nothing that changing conda code can help with here.
