### ISSUE TITLE
Cannot update anaconda or other packages

### ISSUE THREAD

**Issue by jcfuhrmann** [conda/conda#5199]
Installed for one user (joel). Had installed for all users earlier, but removed installation before starting this one. All files in c:\ProgramData\Anaconda3 were removed, and program group removed from administrator's start menu, so I think I had a clean machine when I started this.

conda update conda was run immeidiately prior to this and ran successfully.

====================================================
C:\Users\joel>conda update anaconda
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\joel\Anaconda3:

The following packages will be UPDATED:

    conda: 4.3.14-py36_1 --> 4.3.16-py36_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\joel\Anaconda3  (writable)
    default environment : C:\Users\joel\Anaconda3
       envs directories : C:\Users\joel\Anaconda3\envs
                          C:\Users\joel\AppData\Local\conda\conda\envs
                          C:\Users\joel\.conda\envs
          package cache : C:\Users\joel\Anaconda3\pkgs
                          C:\Users\joel\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\joel\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ C:\Users\joel\Anaconda3\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\exceptions.py", line
 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\cli\main.py", line 1
34, in _main
        exit_code = args.func(args, p)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\cli\main_update.py",
 line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\cli\install.py", lin
e 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\plan.py", line 798,
in execute_actions
        plan = plan_from_actions(actions, index)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\plan.py", line 338,
in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\plan.py", line 302,
in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 464, in prepare
        for dist in self.link_dists)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 464, in <genexpr>
        for dist in self.link_dists)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 387, in make_actions_for_dist
        key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(
md5)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\_vendor\auxlib\colle
ction.py", line 88, in first
        return next((apply(x) for x in seq if key(x)), default() if callable(def
ault) else default)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\_vendor\auxlib\colle
ction.py", line 88, in <genexpr>
        return next((apply(x) for x in seq if key(x)), default() if callable(def
ault) else default)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 386, in <genexpr>
        (PackageCache(pkgs_dir).get(dist) for pkgs_dir in context.pkgs_dirs),
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 346, in get
        return self._packages_map.get(dist, default)
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 251, in _packages_map
        return self.__packages_map or self._init_packages_map()
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 286, in _init_packages_map
        pkgs_dir_contents = dedupe_pkgs_dir_contents(listdir(pkgs_dir))
      File "C:\Users\joel\Anaconda3\lib\site-packages\conda\core\package_cache.p
y", line 282, in dedupe_pkgs_dir_contents
        last = reduce(_process, sorted(pkgs_dir_contents))
    TypeError: reduce() of empty sequence with no initial value

**Comment by kalefranz** [comment]
This was fixed in conda 4.3.15 with #4843.

    conda update conda

This bug happened when a package cache directory contained no files I think.  To update past 4.3.14, try this

    set CONDA_PKGS_DIRS=C:\Users\joel\Anaconda3\pkgs
    conda update conda
    set CONDA_PKGS_DIRS=

**Comment by jcfuhrmann** [comment]
Fixed it, thank you!

Joel Fuhrmann
