### ISSUE TITLE
Installing a tar bundle

### ISSUE THREAD

**Issue by martinfiers** [conda/conda#5211]
Hello,

According to: 

https://docs.continuum.io/anaconda/faq#how-do-i-install-packages-on-a-non-networked-machine

You can install a bundle of packages by first creating a tar, and then simply using ``conda install``. The bundle would just install them without doing any checking - which is indeed the desired behavior if you're assuming you created a consistent bundle.

I found out that this works nicely on conda 4.2.12, but not anymore on 4.3.17 (I didn't test versions in between).

Is there a reason this behavior has changed (and, certainly, the doc is out of sync with the latest behavior). 

What would be the preferred way to make a 'bundle' of packages? My use case is that we have a proper environment already set up, and I want to deploy additional packages in that environment (which have been tested to work and do not create dependency problems).

Thanks for looking into this and advising!

**Comment by kalefranz** [comment]
This should work on 4.3.17 as well. If it doesn't, it's a bug. Please provide more context. Is there a stack trace? What steps should I take to reproduce what you're seeing?

**Comment by kalefranz** [comment]
There used to be an experimental `conda bundle` command, but it was deprecated and then removed because *creating* packages/tarballs is squarely the job of conda-build. You can probably use tweak a standard conda-build recipe to do what you want. Or consider filing an issue in the conda-build repo for a feature request.

**Comment by martinfiers** [comment]
Hello,

Thank you for your reply. To reproduce: as an example, I'm attaching test_bundle.zip (apparently only zip is allowed for upload). It contains test_bundle.tar, which contains two conda packages (isort-4.2.5 and jedi-0.9.0).

[test_bundle.zip](https://github.com/conda/conda/files/973763/test_bundle.zip)

So when I did ``conda install test_bundle.tar`` in conda 4.2, it used to work, but now it starts doing the typical install procedure: fetching package metadata, .. and then ends with an error:

    PackageNotFoundError: Package not found: Conda could not find '

I hope this is providing sufficient detail. Indeed, alternatively, I was thinking of creating a conda recipe that does what I want but I could not immediately see how. Probably I could make a package in which the build.bat/bld.sh just installs the packages I want. (but then juist building a tar seemed like a more elegant, quick solution).

**Comment by nehaljwani** [comment]
This commit removed this feature: d61e73a86003a036a3fbba24ad3f246fa5c532f7

**Comment by martinfiers** [comment]
Oh, good to know. 

So I guess this removal still needs to be updated in the FAW as well:
https://docs.continuum.io/anaconda/faq#how-do-i-install-packages-on-a-non-networked-machine

The nice thing about the tar was that it's an easy way to get several packages installed, and having perfect control on what will get installed (because it doesn't search for dependencies). In our case that was what we needed. But I understand you want to remove non-frequently used features to keep the codebase clean.

Another remark (not fully related to this issue, but I might as well ask here): when you do ``conda install`` on a tar.bz2 file, you need to specify the full path, i.e., ``conda install c:\path\to\my_package.tar.bz2``. it will fail in 2 cases:

* ``conda install my_package.tar.bz2``
* ``conda install c:\path\to with spaces\my_package.tar.bz2``.

Note that with the tar file, I didn't need to specify the full path. That made it easier for non-python experts to get something installed. In fact, we get quite some support calls about this, where we instruct users to install a package but it fails because of the above mentioned reasons.

**Comment by martinfiers** [comment]
Small update: apparently, the behavior of not being able to install a tar.bz2 package as shown above didn't work on 4.2.12, but it works on the latest conda (4.3.17).

**Comment by martinfiers** [comment]
After some more investigation I'm still puzzled. I understand creating tarballs is the job of conda build. The only way I see this work is that I create a new conda recipe that has a build script that looks like this:

bld.bat:

    conda install package1
    conda install package2

And then build this. The resulting tarball will include package1 and package2. But then I'm not sure if this approach is recommended? Remember, I don't care that much about dependency resolving, but I do expect package1 / package2 to be installed properly. And I'm not sure if I install the resulting package, that package1/package2 will be installed properly. Still I feel something's missing. 

Any recommendations?

**Comment by martinfiers** [comment]
Upon your recommendations I'm repeating the issue here: https://github.com/conda/conda-build/issues/2061. So I'll close the issue here.
