### ISSUE TITLE
openblas not built with full processor support

### ISSUE THREAD

**Issue by susilehtola** [conda/conda#5215]
The openblas library appears to have been built only for the Nehalem processor. However, openblas has runtime cpu detection, and so it should be built with support for all processors.

Also, it's not clear which version of the library you are shipping - is it the sequential library, a pthreads library, or an OpenMP library? It would be good to have all three.

You can have a look at how it's supposed to be built at the Fedora spec file
 https://src.fedoraproject.org/cgit/rpms/openblas.git/tree/openblas.spec

For the dynamic architecture support, the flags you need are e.g.
TARGET=CORE2 DYNAMIC_ARCH=1

**Comment by mingwandroid** [comment]
> The openblas library appears to have been built only for the Nehalem processor

Thanks we should fix that.

> .. is it the sequential library, a pthreads library, or an OpenMP library?

We have a build matrix dimension for the blas implementation (either MKL or OpenBLAS). Unfortunately that is done by the old 'features' feature. This only allows for two options (feature on or feature off) so we cannot, as things stand, support 3 variants of OpenBLAS (though conda-build 3 - which is not quite ready yet - does have support for non-binary feature).

I am interested in why you want sequential, pthreads and OpenMP though. Can you detail your use-case? I get that sequential can be faster on single core processors, but hardly anyone uses those now, and to my mind, OpenMP vs pthreads is an implementation detail that should be hidden from the user. For packaging, we should pick whichever is the fastest on each platform.

> You can have a look at how it's supposed to be built at the Fedora spec file

That is just one project's version of how it is supposed to be built, they have very different constraints and requirements than those of the Anaconda Distribution (I have not seen a Fedora for macOS or Windows for example). Here's another project's version of the same: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=openblas

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1661
