### ISSUE TITLE
`cli.python_api` captures `stdout` from `cli.common.confirm_yn`

### ISSUE THREAD

**Issue by mbargull** [conda/conda#5217]
`cli.python_api.run_command` captures any output to `stdout`/`stderr` via `common.io.captured`. This causes the user confirmation messages from `cli.common.confirm_yn`, i.e.,
```bash
Proceed ([y]/n)? 
```
to also be captured, i.e., not being output/accessible until the command finishes (which might be never if the user does not interact). The examples in the doc string are
```python
    Examples:
        >>  run_command(Commands.CREATE, "-n newenv python=3 flask", use_exception_handler=True)
        >>  run_command(Commands.CREATE, "-n newenv", "python=3", "flask")
        >>  run_command(Commands.CREATE, ["-n newenv", "python=3", "flask"], search_path=())
```
and show exactly such use cases.

Due to this, `run_command` is only generally usable if any of `--json`, `--yes` or `--dry-run` is supplied.
There could be two solutions to this:
  1. Force the user to include at least one of those arguments.
  2. Instead of only capturing the output, it could be recorded but also forwarded to `stdout`/`stderr`. This could/should be made optional via some `kwarg` for `run_command`.

Possibility 1. is of course much simpler and could at least serve as a temporary solution.

**Comment by kalefranz** [comment]
Definitely prefer option 1 if anybody wants to swing by and submit an easy PR.

**Comment by mbargull** [comment]
What would be the preferred way to handle the enforcement?

How to detect:
 0. do nothing
 1. inspect `args = p.parse_args(split_command_line)` for `.yes`(`.dry_run`, `.json`) attributes
 2. test every known affected command explicitly (à la `if command in {Commands.CREATE, ...}:`)
 3. have some state information which gets passed down to `confirm_yn` to indicate usage of `python_api` (e.g., an additional attribute to `base.context.context`)
Option 0 is sufficient for now. Option 1 is simple and less "hard-coded" compared to 2. Option 3 is a little overkill (IMHO) for this issue.

How to handle:
 1. raise some exception (`ArgumentError`)
 2. set `args.yes = True` if the detection above succeeded
 3. set `args.yes = True` unconditionally

I opted for always, unconditionally setting `args.yes = True` in #5399.

**Comment by mbargull** [comment]
If you think #5394 could be accepted, this would only be needed if `stdout` is captured as a string (i.e., if the new argument from #5394, `stdout`, is absent or `STRING`) since otherwise the user can handle it themselves (having access to `sys.stdout` or their own supplied file-like object).
If one would want to allow user interaction, instead of #5399, something like this could be done:
```python
def run_command(command, *arguments, **kwargs):
...
    always_yes = kwargs.get('always_yes', True)
...
    args = p.parse_args(split_command_line)
    context.__init__(
        search_path=configuration_search_path,
        app_name=APP_NAME,
        argparse_args=args,
    )
    if (not always_yes) and stdout == STRING:
        if ("yes" in args) and not any((context.always_yes, context.dry_run, context.json)):
            raise ArgumentError("must use one of --yes, --dry-run, --json when stdout is captured in user-confirmable command")
    context.always_yes = True
```
