### ISSUE TITLE
Conda stuck at "Solving package specifications"

### ISSUE THREAD

**Issue by simonvh** [conda/conda#5219]
I recently updated a conda package in the bioconda channel: [gimmemotifs](https://bioconda.github.io/recipes/gimmemotifs/README.html). However, using a simple install/create command will now fail, with conda (version 4.3.17) being stuck at the "Solving package specifications" stage. 

```
$ conda create -n gimmemotifs python=2 gimmemotifs
Fetching package metadata ...............
Solving package specifications: .
```
When I specify the exact version, the installation works flawlessly:

```
$ conda create -n gimmemotifs python=2 gimmemotifs=0.10.0=py27_0
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/simon/anaconda3/envs/gimmemotifs:

The following NEW packages will be INSTALLED:
[...]
```

Has anyone seen this before? Any clues on how to solve it?

**Comment by kalefranz** [comment]
Can you provide output for

    conda info
    conda create -n gimmemotifs python=2 gimmemotifs -vv

**Comment by simonvh** [comment]
```
$ conda info
    Current conda install:

                   platform : linux-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.0.7
             python version : 3.5.2.final.0
           requests version : 2.13.0
           root environment : /home/simon/anaconda3  (writable)
        default environment : /home/simon/anaconda3
           envs directories : /home/simon/anaconda3/envs
                          /home/simon/.conda/envs
              package cache : /home/simon/anaconda3/pkgs
                          /home/simon/.conda/pkgs
               channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                config file : /home/simon/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.13.0 CPython/3.5.2 Linux/4.4.0-66-generic debian/stretch/sid glibc/2.23    
                    UID:GID : 1001:1001
    
```
Output from conda create: [conda.out.txt](https://github.com/conda/conda/files/978439/conda.out.txt)
This is where its seems to get stuck.

**Comment by kalefranz** [comment]
@mcg1969 Another "solver got stuck" issue you might want to browse through.  There's a file attached with debug output.

**Comment by mcg1969** [comment]
I'm not sure we're going to be able to reproduce this. In particular, I'm getting a pretty quick solution now for the same install recipe, but with 0.10.0b1 instead of 0.10.0. And that's why we're likely not to be able to reproduce it: the environment that the solver is living in is always changing.

That said, when I look at the debug output, I'm finding that it's not able to prune back the package list very well. The more "old" packages it has to consider the higher the likelihood that this kind of solver stall happens. Thankfully it is a lot less likely than it used to be.

We will certainly keep pushing this though. I'm not keen to have random solver stalls like this.

**Comment by xjdeng** [comment]
I had this problem until I upgraded conda in my root environment:

`conda upgrade conda`

**Comment by mavelli** [comment]
had the same, after upgrading conda-forge it didnt stick any more

`conda:` 4.3.22-py35_0 conda-forge --> 4.3.29-py35_0 conda-forge`

**Comment by EzzEddin** [comment]
Thanks @xjdeng 
I just upgraded Anaconda from the Navigator GUI.

**Comment by Cadene** [comment]
Use no-update-deps flag:

```
conda install ncurses --no-update-deps
```

**Comment by searain** [comment]
I had the Anaconda Navigator open, command line update stuck in
Solving package specifications: .

But after I close Anaconda, the process is going on.

**Comment by Sarnath** [comment]
I installed Anaconda for first time today. Win64 edition. 
I tried to install Tensorflow and it gets stuck in "Solving package specification"...
No further progress.
Just the first attempt to install..... has gone awry.. :(

**Comment by cmosguy** [comment]
I am getting the same issue wit trying to install `ipython-sql`.  Is there something going on with the servers?

**Comment by pompomon** [comment]
I had the similar problem with Anaconda Navigator x64 on Windows 10. It stuck on "solving package specifications" for base environment, but when I created another virtual environment, everything worked. Thank you @zgrkpnr !

**Comment by simonvh** [comment]
@zgrkpnr I haven't had this issue for a while now, it seems to be solved for me

**Comment by alik604** [comment]
I currently have it. trying posted solution right now. The cause must still be present

**Comment by bishab** [comment]
Aren't there any other ways to solve it, cause none of em worked in mine

**Comment by alistairone** [comment]
I am having this issue when trying to install the gdal package into my base environment. Is there any fix for this?

**Comment by marcoxa** [comment]
Let me join the club here...

I tried to uninstall anaconda and reinstalling but no joy.  Windows 10 64bits.  No Python installed before.

Getting stuck.

**Comment by jinlukang1** [comment]
Don't use IDE, use Cmd. This works for me.

**Comment by sakshamg94** [comment]
> 
> 
> I had this problem until I upgraded conda in my root environment:
> 
> `conda upgrade conda`

sorry this did not work for me,  but @pompomon 's , @zgrkpnr 's solution worked!!

**Comment by aliakbarrn** [comment]
update conda and create new environment works for me

**Comment by krishnapm642** [comment]
I also have the same issue while installing tensor flow.My anaconda python version is 3.8
After i changed the version to 3.7 , then it is worked for me.

**Comment by skintigh** [comment]
I just updated and now I have the same problem.

**Comment by Ganymede23** [comment]
This happened to me when trying to create an environment with Python 3.6. I tried `conda upgrade conda` but it didn't work.
Switched to Python 3.9 and it's working just fine now.
Not an ideal solution if you really need a specific version, but still.

**Comment by skintigh** [comment]
I think I uninstalled and installed a new version and that didn't help, so I uninstalled, manually deleted all the directories, reinstalled, and then it worked. So apparently something was messed up on my end.

**Comment by RichardSchulz52** [comment]
I just solved the problem by setting the channel priority to false. It was on strict before and i couldn't solve under any circumstances.

**Comment by coldReactive** [comment]
> I just solved the problem by setting the channel priority to false. It was on strict before and i couldn't solve under any circumstances.

I don't know how to do this using the GUI version of anaconda3. I use Python 3.11, the latest python, and Anaconda gets stuck at solving packages on the Anaconda Navigator for opencv 4.6.0

**Comment by Strikoder** [comment]
Updating conda didn't work for me.

**Comment by RichardSchulz52** [comment]
I already commented here, but I switched to mamba since then. It does the same thinks but faster and doesn't get stuck. It turned out one config I was trying wasn't possible but conda kept searching for a solution. Mamba just told me no way and I tried other configurations till I was happy.

**Comment by jezdez** [comment]
Just in case you'd like to use the part of mamba that makes it fast (its "solver"), but with conda directly, feel free to try out [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/), an optional package that bridges between the two projects (plus additional compatibility layer for conda's behavior).

We plan to make that solver the default in the future and would really appreciate you trying it out. There is a [getting started guide](https://conda.github.io/conda-libmamba-solver/getting-started/) to.. get you started whenever you're ready. Thank you for your continued interest in this ticket!
