### ISSUE TITLE
activate borks PS1 when done with abspath in .bash_profile

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5223]
Based on conversations with @mingwandroid I've come to understand that the `activate` script is the right way for me to get Anaconda setup and available in a terminal session.

As such I've put the following as the last entry in my `.bash_profile`:

```
source /Users/ijstokes/anaconda/bin/activate root
```

However it borks my `PS1`, and ALL I get is the conda piece, so my prompt for executing `ls` looks like:

``` bash
(root) ls
```

(yuck!)

I think this may be related to #4494 and #4916

**Comment by kalefranz** [comment]
On your system, what is `echo $PS1` before you do anything with conda? I'll try to track this down...

Will note that in conda 4.4, this is all reworked again. This time I think the strategy is solid. See #4055 and follow-on PRs as listed in the CHANGELOG.

**Comment by ijstokes** [comment]
I don't know what's changed!  This is working for me now, after a kernel-panic-induced reboot (I had rebooted before and still been stuck with this weird behavior).  Anyway, if the issue returns I'll add an `echo $PS1` just before the `source /path/to/activate root` statement in my `.bash_profiile`.
