### ISSUE TITLE
conda links in qt5 files even when they have no place being there

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5224]
I used this conda env file to create a conda environment:

[ana43noverserver.txt](https://github.com/conda/conda/files/977313/ana43noverserver.txt)

It does not include `qt` nor is it an implied dependency.  Once the environment has been created `conda list` agrees: the `qt` package is not listed in any way shape or form.

However it has been linked into that environment and is the biggest single file in my `/path/to/env/lib` directory:

```
-rwxrwxr-x    2 ijstokes  staff    62M Nov 17 11:33 libQt5WebEngineCore.5.6.2.dylib*
```

What's going on?

Here is my FD version of the question.

I have a mystery that requires some help to sleuth out the answer. 

```
 $ grep libQt5WebEngineCore.5.6.2.dylib ~/anaconda/pkgs/*/info/files
/Users/ijstokes/anaconda/pkgs/qt-5.6.2-0/info/files:lib/libQt5WebEngineCore.5.6.2.dylib
/Users/ijstokes/anaconda/pkgs/qt-5.6.2-1/info/files:lib/libQt5WebEngineCore.5.6.2.dylib
```
which suggests to me that `libQt5WebEngineCore.5.6.2.dylib` is only available in the `qt` package

But then the environment I just created:

```
 $ ls -Fla libQt5WebEngineCore.5.6.2.dylib 
-rwxrwxr-x  2 ijstokes  staff  64927480 Nov 17 11:33 libQt5WebEngineCore.5.6.2.dylib*

 $ pwd
/Users/ijstokes/anaconda/envs/ana43noverserver/lib
```

So I have the file (it is big, and I’m trying to reduce the size of this conda environment), however I don’t have the `qt` package installed:

```
 $ conda list -e ana43noverserver | grep -i qt
```

returns nothing.

So why would the file be in my conda environment?

**Comment by ijstokes** [comment]
Something wacky happened there (probably PEBCAK).  I started from scratch and this time the `qt` package is listed by `conda list`.  Closing.

For anyone who cares, MKL was pulling in QT5.

**Comment by mingwandroid** [comment]
`matplotlib` surely? `MKL` has no such requirement.

**Comment by ijstokes** [comment]
@mingwandroid you are, of course, correct.  I am mis-reading the `about.json` file for MKL that lists qt for some reason.  I assumed that was because it was a dependency.  This is tied a bit to https://github.com/conda/conda/issues/4942, since I can't back-trace where the Qt dep was coming from I resorted to `grep` on `anaconda/pkgs/*/info/about.json` -- if there is a better way, please let me know.
