### ISSUE TITLE
graphviz package doesn't add executable to PATH on windows

### ISSUE THREAD

**Issue by amueller** [conda/conda#5227]
The graphviz dot executable is installed to ``<anaconda>/Library/bin/graphviz/`` (I think, don't have a machine here to double check - but there's definitely a graphviz sub-folder).
But this folder is not added to the executable search path. That means that it can not be used basically, and using the python graphviz package fails.
I just manually fixed this issue at around 10 laptops in my workshop :-/
doing ``!set PATH=PATH;C:\path\to\anaconda\Library\bin\graphviz\`` fixed it.

**Comment by kalefranz** [comment]
`activate` on windows should absolutely be adding `Library\bin` to `PATH`.

https://github.com/conda/conda/blob/4.2.16/conda/cli/activate.py#L73

How are you accessing a command line on windows? In what terminal?  How is the initialization of the terminal being configured?

If you're using the Anaconda Prompt that's a cmd.exe shell, then `activate root` should be called automatically for you.  If you're just using plain `cmd.exe`, then you might have to call it yourself.  I don't know what all the Anaconda installer adds to PATH by default, but I know there's a push to add even less.

CC @mingwandroid

**Comment by amueller** [comment]
The executable is not in ``bin``, though, it's in a ``graphviz`` subfolder.

**Comment by mingwandroid** [comment]
If you can move this to Anaconda-issues and assign it to me please do @kfranz.

Also, do you think it would be possible to setup an issues template so that people are forced to think about whether the bug they are reporting concerns conda or whether it concerns AD (or navigator or Spyder or constructor etc)? I think it could save quite a bit of your time if so.

**Comment by kalefranz** [comment]
> The executable is not in bin, though, it's in a graphviz subfolder.

Oh I totally missed that.  My mistake.

> do you think it would be possible to setup an issues template

I've been considering that for quite a long time.  I'm not a fan of the github implementation, but I think it might just be time.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1666

**Comment by amueller** [comment]
Not sure if a template is the best solution; I really don't like those. I thought anaconda-issues relates to the anaconda distribution, but I guess now it also relates to the whole conda repository?

**Comment by kalefranz** [comment]
Creating a new issue has the

> Before you submit an issue, please review [the guidelines](https://github.com/conda/conda/blob/master/.github/CONTRIBUTING.md) for this repository.

box.  The information is there.  The box is easy to miss though.

**Comment by amueller** [comment]
I take all blame, should have read that. Should be enough? I'm just also very lazy.

**Comment by kalefranz** [comment]
Yeah anaconda-issues is for all packages in repo.continuum.io.  One of the things Continuum is really good at is confusing people with what we name stuff.

**Comment by amueller** [comment]
unrelated and then I'm gonna be quite:
```
:+1::tada: First off, thanks for taking the time to conda! :tada::+1:
```
Is "conda" the verb in this sentence on purpose, or did you just miss the "contribute"?

**Comment by kalefranz** [comment]
Intentional.  At the time I wrote it, it made me laugh ¯\\\_(ツ)\_/¯
