### ISSUE TITLE
conda not installing packages into activated environment?

### ISSUE THREAD

**Issue by ericmjl** [conda/conda#5238]
Hi!

I've noticed a quirky bug yesterday with conda 4.2.13. The tl;dr version is **cannot find package in environment even after `conda install`**.

I had an environment setup and activated, named `bayes`, and forgot to install PyMC3. I thus decided to install it after-the-fact. With `bayes` activated:

```bash
$ source activate bayes
```

I installed PyMC3.
```bash
$ conda install pymc3
```

It was installed from `conda-forge`. I did this all with a Jupyter notebook running in the same activated environment.

Previous behaviour was such that I could immediately go back into the Jupyter notebook and without restarting the kernel, find the PyMC3 package installed and immediately start using it.

Yesterday's behaviour was markedly different: PyMC3 could not be found.

It took doing `conda env update -f environment.yml`, where PyMC3 was added as a required package there, to get it installed.

Any ideas why this is happening? Has the default behaviour of conda changed? Is this related to [this comment](https://github.com/Anaconda-Platform/nb_conda/issues/54#issuecomment-299450344)?

Thanks in advance!

**Comment by kalefranz** [comment]
I think this is a question for a different issue tracker.  It seems from your description that conda installed the package properly.  It's just that the notebook environment didn't notice and pick up the change.  So there's nothing that changing conda's own code can affect here.

**Comment by ericmjl** [comment]
Thanks, @kalefranz, I'll post this over at the Jupyter Notebook repo and see what the response is there.

**Comment by kalefranz** [comment]
Feel free to kick it back as a conda issue if there's something we're actually doing wrong in our code base here.  I'm not seeing it right now though.
