### ISSUE TITLE
Conda env update: SpecNotFound: Runtime error: Can't process without a name

### ISSUE THREAD

**Issue by sergcourt** [conda/conda#5244]
Current conda install:

               platform : osx-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.18.2
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/abcabc/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/abcabc/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/abcabc/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.13 Darwin/16.5.0 OSX/10.12.4
                UID:GID : 501:0

`$ //anaconda/bin/conda-env update`

    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 77, in execute
        directory=os.getcwd())
      File "//anaconda/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by kalefranz** [comment]
Help for `conda env update` says

    Update the current environment based on environment file

You didn't provide a `--file` flag, and no `environment.yml` file can be found in the current directory.
