### ISSUE TITLE
Conda removes its own interpreter

### ISSUE THREAD

**Issue by LucoLab** [conda/conda#5245]
I have broken my conda installation. I removed one package and conda delete also python interpreter

```
> conda uninstall deeptools 
Fetching package metadata ............. Solving package specifications: Package plan for package removal in environment /home/name/bin/anaconda3:

The following packages will be REMOVED:

    deeptools: 2.5.0-py35_0 bioconda
    python:    3.5.2-0              

Proceed ([y]/n)? y
So now :

>conda install python
-bash: /home/name/: /home/name/bin/anaconda3/bin/python: bad interpreter: No such file or directory

```

**Comment by rmldj** [comment]
I have a similar problem - due to a flawed contributed package I think. How did you solve it? I also noticed that a similar question was deleted on StackOverflow..

**Comment by Dana-Farber** [comment]
Same issue here after installing and uninstalling pysam. Ideas?

**Comment by walterreade** [comment]
Same issue, after I did a conda rollback. Completely removed python. So very annoying.

**Comment by rmldj** [comment]
Perhaps it would be worthwhile to open a new issue? Since this issue has been closed, the developers may not be following it. I could not resolve the problem and reinstalled anaconda from scratch. But it has been a while and I do not remember the exact setup (package versions etc.) that I had..
