### ISSUE TITLE
How to update anaconda and all packages for a offline computer. 

### ISSUE THREAD

**Issue by pcmagic** [conda/conda#5246]
For some security issue, one of computers I'm using is offline, which means that it can NOT connect the Internet directly; and I can only download, and copy packages from a laptop to that computer using FTP. 

I have installed anaconda and some packages at the offline computer, however, they are out of date. Is there some elegant (easy) way to update anaconda and all the packages. 

THX.

**Comment by ijstokes** [comment]
Anaconda Enterprise is the official answer!

https://www.continuum.io/anaconda-enterprise-features

This scenario is what we've developed our commercial products to support: anything beyond single user, single system, interactive, Internet-connected usage.  There are hacky ways you can do what you want by downloading packages into your local package cache and then using the `--offline` option, but they aren't really supported, and we've recently updated our repository AUP to make it clear that people aren't meant to setup mirrors of it.

If I were in your situation here's what I'd try to do:

1. Decide if Anaconda provides high value.  If it does, contact the Anaconda sales team (sales@continuum.io) and give them 15-20 minutes to discuss your usage scenario and see if we can come up with a business case for why it is worth your organization's time and $$$ to purchase our commercial product (support! indemnification! cool-enterprise-features!).

2. If you decide it isn't worth the $$$ but you still need an answer then you could `rsync` the `internet.connected.computer:/path/to/anaconda/pkgs` directory from an equivalent system which is Internet connected and where you've installed the packages you need.  Drop those into the firewalled/offline machine: `firewalled.computer:/path/to/anaconda/pkgs`.  Now do stuff with the `--offline` flag on `firewalled.computer`.
