### ISSUE TITLE
i want install zipline 

### ISSUE THREAD

**Issue by hmz123** [conda/conda#5247]
# **1. UnsatisfiableError: The following specifications were found to be in conflict:
2.   - python 3.6*
3.   - zipline -> alembic >=0.7.7 -> python 3.4*
4. Use "conda info <package>" to see the dependencies for each package.**

**Comment by kalefranz** [comment]
Assuming you're using the quantopian channel, zipline is only available for python 2.7 and python 3.4. 

    conda create -n zipline-env -c quantopian zipline python=3.4

Then activate the zipline-env environment.
