### ISSUE TITLE
confusing messages at downgrading

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#5248]
When I willfully downgrade a package, confusing dialogs are given related to dependency conflicts, possibly because the same dialog/logging is used when an automatic downgrade requirement was being determined:

```bash
(stable) └─❱❱❱ conda install pandas=0.19                                        +6295 8:05 ❰─┘
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/stable:

The following packages will be DOWNGRADED due to dependency conflicts:

    pandas: 0.20.1-np112py36_0 conda-forge --> 0.19.2-np112py36_1 conda-forge

Proceed ([y]/n)?
```

I think it would be preferable, that in the deliberate downgrade the messages should not say `due to dependency conflicts` and that this part is only added to the dialog when a dependency conflict was automatically found.

version: 4.2.13 on macOS

**Comment by mcg1969** [comment]
Seems to me the simplest thing for us to do here is to drop the "due to dependency conflicts." It's not clear to me we can reliably say that anyway.
