### ISSUE TITLE
What does it mean when when conda refuses to install and doesn't offer a resolution?

### ISSUE THREAD

**Issue by abalter** [conda/conda#5255]
Most of the time when `conda` runs into a conflict it will show you a resolution and ask how you want to proceed. This is how I would expect a package manager to act. That is what `apt` does. But sometimes I get something like: 

    balter@BICB260:~$ conda install r-venndiagram
    Fetching package metadata ...................
    Solving package specifications: .
    
    
    UnsatisfiableError: The following specifications were found to be in conflict:
      - r-backports
      - r-venndiagram -> r 3.2.2* -> r-base 3.2.2
    Use "conda info <package>" to see the dependencies for each package.

It would be nice if `conda` would offer some possible resolutions.

**Comment by kalefranz** [comment]
I agree.  There are tons of open issues that look very similar to this one.  Definitely high priority on the list of improvements, if nothing else to cut down on the number if issues being filed :)

I'm guessing here `r-venndiagram` needs `r` version `3.2.2*`, but `r-backports` is already installed, and it's incompatible with that version of `r`.  So what you probably need to do is uninstall `r-backports`, and then let conda upgrade your version of `r`.
