### ISSUE TITLE
Deprecated R version

### ISSUE THREAD

**Issue by danvilar** [conda/conda#5262]
Hi guys. As you know, many people who work with R will eventually use Bioconductor. As of today, this is what you can read from their install page:

> "The current release of Bioconductor is version 3.5; it works with R version 3.4.0. Users of older R and Bioconductor users must update their installation to take advantage of new features and to access packages that have been added to Bioconductor since the last release."

Do you have plans on providing newer R versions?
Thanks

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1712
