### ISSUE TITLE
conda install local package

### ISSUE THREAD

**Issue by juvion** [conda/conda#5266]
I have installed Anaconda 4.3.1 (64-bit) on my remote Linux server (Red Hat 4.4.7-1). Since I don't have sudo permission, the admin created `/usr/local2 ` folder and granted me with full permission on it.  After the installation, the python runs fine.
```
$ which python
/usr/local2/anaconda2/bin/python
```
The problem is installation of packages locally via `conda install`.
Now that the Linux server has internet connection restriction, and I have to use `conda install` to build from local package file. Take `pyodbc` for example...
```
$ conda install  pyodbc-3.0.10-py27_1.tar.bz2
```
No error message.

When I run python, and try to load the `pyodbc` library, it complains importError

```
$ python
Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local2/anaconda2/lib/python2.7/site-packages/pyodbc.so: cannot open shared object file: No such file or directory
``` 
The problem is the `pyodbc.so` file actually is in the path, and `conda list` shows the package.

```
$ conda list
pygments                  2.1.3                    py27_0
pylint                    1.6.4                    py27_1
pyodbc                    3.0.10                   py27_1    file:///home/user80/Downloads
pyopenssl                 16.2.0                   py27_0
pyparsing                 2.1.4                    py27_0
```

I have read it might be related to LD_LIBRARY_PATH issue, but how do I set it given my case?

Thanks a lot.

**Comment by kalefranz** [comment]
When you install tarballs directly, you bypass the conda solver.  There are thus no dependencies installed.  Your best option is probably to create your own local channel off of a `file://` url using `conda index`.

**Comment by juvion** [comment]
Thanks for the instruction. I followed Anaconda's documentation: https://docs.continuum.io/anaconda/faq#id6 . Did I misunderstand it then?
