### ISSUE TITLE
Issue while trying to create new environment

### ISSUE THREAD

**Issue by sohan1990** [conda/conda#5268]
https://github.com/conda/conda/issues

    Current conda install:

                   platform : osx-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.14.1
           root environment : /Applications/anaconda  (writable)
        default environment : /Applications/anaconda
           envs directories : /Applications/anaconda/envs
                          /Users/sohansamanta/.conda/envs
              package cache : /Applications/anaconda/pkgs
                          /Users/sohansamanta/.conda/pkgs
               channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                config file : /Users/sohansamanta/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.14.1 CPython/3.6.0 Darwin/16.5.0 OSX/10.12.4    
                    UID:GID : 501:20
    

`$ /Applications/anaconda/bin/conda create -n environ_2.7`

    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in <listcomp>
        for url, schan, pri in tasks]
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/Applications/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 452, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/Applications/anaconda/pkgs/cache/6dd50e2e.json'

**Comment by kalefranz** [comment]
I'm curious how you got in this situation.  Did you ever use `sudo` in front of `conda`?

**Comment by kalefranz** [comment]
Actually, can you give me the output of

    ls -al /Applications/anaconda/pkgs
    id

**Comment by sohan1990** [comment]
total 10840
drwxr-xr-x  191 sohansamanta  staff     6494 May  9 16:55 .
drwxr-xr-x   23 sohansamanta  staff      782 May  9 16:55 ..
-rw-r--r--    1 sohansamanta  staff     2097 Mar  6 15:42 .cio-config.py
-rw-r--r--    1 sohansamanta  staff    51116 Mar  6 15:42 .install.py
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 _license-1.1-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 alabaster-0.7.9-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 anaconda-4.3.1-np111py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 anaconda-client-1.6.0-py36_0
drwxr-xr-x    4 root          staff      136 May  9 16:55 anaconda-custom-py36_0
-rw-r--r--    1 root          staff     2847 May  9 16:55 anaconda-custom-py36_0.tar.bz2
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:42 anaconda-navigator-1.5.0-py36_0
drwxr-xr-x    6 root          staff      204 May  9 16:55 anaconda-navigator-1.5.2-py36_0
-rw-r--r--    1 root          staff  4931506 May  9 16:55 anaconda-navigator-1.5.2-py36_0.tar.bz2
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 anaconda-project-0.4.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 appnope-0.1.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 appscript-1.0.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 astroid-1.4.9-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 astropy-1.3-np111py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 babel-2.3.4-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 backports-1.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 beautifulsoup4-4.5.3-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 bitarray-0.8.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 blaze-0.10.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 bokeh-0.12.4-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 boto-2.45.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 bottleneck-1.2.0-np111py36_0
drwxr-xr-x   18 sohansamanta  staff      612 May  9 16:55 cache
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 cffi-1.9.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 chardet-2.3.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 chest-0.2.3-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 click-6.7-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 cloudpickle-0.2.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 clyent-1.2.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 colorama-0.3.7-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:47 conda-4.3.14-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 May  7 02:28 conda-4.3.17-py36_0
-rw-r--r--    1 sohansamanta  staff   518404 May  7 02:28 conda-4.3.17-py36_0.tar.bz2
drwxr-xr-x    3 sohansamanta  staff      102 Mar  6 15:47 conda-env-2.6.0-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 configobj-5.0.6-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 contextlib2-0.5.4-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 cryptography-1.7.1-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:42 curl-7.52.1-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 cycler-0.10.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 cython-0.25.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 cytoolz-0.8.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 dask-0.13.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 datashape-0.5.4-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 decorator-4.0.11-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 dill-0.2.5-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 docutils-0.13.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 entrypoints-0.2.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 et_xmlfile-1.0.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 fastcache-1.0.2-py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 flask-0.12-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 flask-cors-3.0.2-py36_0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:42 freetype-2.5.5-2
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 get_terminal_size-1.0.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 gevent-1.2.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:42 greenlet-0.4.11-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 h5py-2.6.0-np111py36_2
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:42 hdf5-1.8.17-1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:42 heapdict-1.0.0-py36_1
drwxr-xr-x    8 sohansamanta  staff      272 Mar  6 15:43 icu-54.1-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 idna-2.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 imagesize-0.7.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 ipykernel-4.5.2-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 ipython-5.1.0-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 ipython_genutils-0.1.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 ipywidgets-5.2.2-py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 isort-4.2.5-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 itsdangerous-0.24-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 jbig-2.1-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 jdcal-1.3-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 jedi-0.9.0-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 jinja2-2.9.4-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:43 jpeg-9b-0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 jsonschema-2.5.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 jupyter-1.0.0-py36_3
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 jupyter_client-4.4.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 jupyter_console-5.0.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:43 jupyter_core-4.2.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 lazy-object-proxy-1.2.2-py36_0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:43 libiconv-1.14-0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:43 libpng-1.6.27-0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:43 libtiff-4.0.6-3
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:43 libxml2-2.9.4-0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:43 libxslt-1.1.29-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 llvmlite-0.15.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 locket-0.2.0-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 lxml-3.7.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 markupsafe-0.23-py36_2
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 matplotlib-2.0.0-np111py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 mistune-0.7.3-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:43 mkl-2017.0.1-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 mkl-service-1.1.2-py36_3
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 mpmath-0.19-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 multipledispatch-0.4.9-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 nbconvert-4.2.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 nbformat-4.2.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 networkx-1.11-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 nltk-3.2.2-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 nose-1.3.7-py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 notebook-4.3.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 numba-0.30.1-np111py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 numexpr-2.6.1-np111py36_2
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 numpy-1.11.3-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 numpydoc-0.6.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 odo-0.5.0-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 openpyxl-2.4.1-py36_0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:45 openssl-1.0.2k-1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pandas-0.19.2-np111py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 partd-0.3.7-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 path.py-10.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pathlib2-2.2.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 patsy-0.4.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pep8-1.7.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pexpect-4.2.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pickleshare-0.7.4-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pillow-4.0.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pip-9.0.1-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 ply-3.9-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 prompt_toolkit-1.0.9-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 psutil-5.0.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 ptyprocess-0.5.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 py-1.4.32-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pyasn1-0.1.9-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pycosat-0.6.1-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pycparser-2.17-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pycrypto-2.6.1-py36_4
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pycurl-7.43.0-py36_2
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pyflakes-1.5.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pygments-2.1.3-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pylint-1.6.4-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pyopenssl-16.2.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pyparsing-2.1.4-py36_0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:45 pyqt-5.6.0-py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pytables-3.3.0-np111py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 pytest-3.0.5-py36_0
drwxr-xr-x    7 sohansamanta  staff      238 Mar  6 15:42 python-3.6.0-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 python-dateutil-2.6.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:45 python.app-1.2-py36_4
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pytz-2016.10-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pyyaml-3.12-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:45 pyzmq-16.0.2-py36_0
drwxr-xr-x   14 sohansamanta  staff      476 Mar  6 15:46 qt-5.6.2-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 qtawesome-0.4.3-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:46 qtconsole-4.2.1-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 qtpy-1.2.1-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:46 readline-6.2-2
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 redis-3.2.0-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 redis-py-2.10.5-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 requests-2.12.4-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 rope-0.9.4-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:46 ruamel_yaml-0.11.14-py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:46 scikit-image-0.12.3-np111py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 scikit-learn-0.18.1-np111py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 scipy-0.18.1-np111py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 seaborn-0.7.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 setuptools-27.2.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 simplegeneric-0.8.1-py36_1
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 singledispatch-3.4.0.3-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:47 sip-4.18-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 six-1.10.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 snowballstemmer-1.2.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 sockjs-tornado-1.0.3-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 sphinx-1.5.1-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 spyder-3.1.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 sqlalchemy-1.1.5-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:47 sqlite-3.13.0-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 statsmodels-0.6.1-np111py36_1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 sympy-1.0-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 terminado-0.6-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:47 tk-8.5.18-0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 toolz-0.8.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 tornado-4.4.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 traitlets-4.3.1-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 unicodecsv-0.14.1-py36_0
-rw-r--r--    1 sohansamanta  staff    18766 Mar  6 15:42 urls
-rw-r--r--    1 sohansamanta  staff    13120 May  9 16:55 urls.txt
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 wcwidth-0.1.7-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 werkzeug-0.11.15-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 wheel-0.29.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 widgetsnbextension-1.2.6-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 wrapt-1.10.8-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 xlrd-1.0.0-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 xlsxwriter-0.9.6-py36_0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 xlwings-0.10.2-py36_0
drwxr-xr-x    4 sohansamanta  staff      136 Mar  6 15:47 xlwt-1.2.0-py36_0
drwxr-xr-x    6 sohansamanta  staff      204 Mar  6 15:47 xz-5.2.2-1
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 yaml-0.1.6-0
drwxr-xr-x    5 sohansamanta  staff      170 Mar  6 15:47 zlib-1.2.8-3

**Comment by sohan1990** [comment]
uid=501(sohansamanta) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),701(com.apple.sharepoint.group.1)

**Comment by sohan1990** [comment]
I actually did use sudo in front of coda. After installing anaconda, the navigator was not running. It would start and then immediately crash. In the terminal I saw it was showing some ownership issues, for which I tried running it with sudo.

**Comment by kalefranz** [comment]
Oh that explains it then. 

    sudo chown -R sohansamanta:staff /Applications/anaconda
