### ISSUE TITLE
conda is not installing, updating packages or creating any environment

### ISSUE THREAD

**Issue by vyas1** [conda/conda#5277]
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda
3  (writable)
    default environment : C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda
3
       envs directories : C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda
3\envs
                          C:\Users\vyas.rastogi\AppData\Local\conda\conda\envs
                          C:\Users\vyas.rastogi\.conda\envs
          package cache : C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda
3\pkgs
                          C:\Users\vyas.rastogi\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
            config file : C:\Users\vyas.rastogi\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.
py - proxy_servers: {}`

    Traceback (most recent call last):
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1762, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1971, in _parse_known_args
        stop_index = consume_positionals(start_index)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1927, in consume_positionals
        take_action(action, args)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1820, in take_action
        argument_values = self._get_values(action, argument_strings)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 2271, in _get_values
        self._check_value(action, value[0])
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 2314, in _check_value
        raise ArgumentError(action, msg % args)
    argparse.ArgumentError: argument command: invalid choice: '-' (choose from '
info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remo
ve', 'uninstall', 'config', 'clean', 'package')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\site-pac
kages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\site-pac
kages\conda\cli\main.py", line 119, in _main
        args = p.parse_args(args)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\site-pac
kages\conda\cli\conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1730, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\argparse
.py", line 1769, in parse_known_args
        self.error(str(err))
      File "C:\Users\vyas.rastogi\AppData\Local\Continuum\Anaconda3\lib\site-pac
kages\conda\cli\conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by kalefranz** [comment]
Installing, updating packages, and creating environments are three different conda commands. The only command I see being executed here is 

    conda -proxy_servers: {}

which isn't a conda command. 

Please provide more context.

**Comment by kalefranz** [comment]
Oh, this is just `CommandNotFoundError(cmd, message)` having invalid init, which has been fixed already.
