### ISSUE TITLE
dyld: Library not loaded: @rpath/./libgfortran.3.dylib for install.packages("maps") for R 3.3.2

### ISSUE THREAD

**Issue by Shuolongbj** [conda/conda#5279]
1、(gcc) Ru@bogon:~$ conda info
    Current conda install:

                   platform : osx-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.1.9
             python version : 3.6.1.final.0
           requests version : 2.12.4
           root environment : /Users/Ru/anaconda  (writable)
        default environment : /Users/Ru/anaconda/envs/gcc
           envs directories : /Users/Ru/anaconda/envs
                          /Users/Ru/.conda/envs
              package cache : /Users/Ru/anaconda/pkgs
                          /Users/Ru/.conda/pkgs
               channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                config file : /Users/Ru/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/3.6.1 Darwin/16.5.0 OSX/10.12.4
                    UID:GID : 501:20

2、(gcc) Ru@bogon:~$ conda list --show-channel-urls
#packages in environment at /Users/Ru/anaconda/envs/gcc:
#
cairo                     1.14.8                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cloog                     0.18.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
curl                      7.52.1                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fontconfig                2.12.1                        3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gcc                       4.8.5                         8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gettext                   0.19.8                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
glib                      2.50.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gmp                       6.1.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gsl                       2.2.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
harfbuzz                  0.9.39                        2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icu                       54.1                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
isl                       0.12.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc                    4.8.5                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.27                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxml2                   2.9.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpc                       1.0.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mpfr                      3.1.5                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ncurses                   5.9                          10    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openjdk                   8.0.121                       0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2k                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pango                     1.40.3                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pcre                      8.39                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pixman                    0.34.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    3.6.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
r                         3.3.2                  r3.3.2_0    conda-forge
r-base                    3.3.2                         1    defaults
r-boot                    1.3_18                 r3.3.2_0    conda-forge
r-class                   7.3_14                 r3.3.2_0    conda-forge
r-cluster                 2.0.6                  r3.3.2_0    conda-forge
r-codetools               0.2_15                 r3.3.2_0    conda-forge
r-foreign                 0.8_67                 r3.3.2_0    conda-forge
r-kernsmooth              2.23_15                r3.3.2_0    conda-forge
r-lattice                 0.20_34                r3.3.2_0    conda-forge
r-mass                    7.3_45                 r3.3.2_0    conda-forge
r-matrix                  1.2_7.1                r3.3.2_0    conda-forge
r-mgcv                    1.8_17                 r3.3.2_0    conda-forge
r-nlme                    3.1_131                r3.3.2_0    conda-forge
r-nnet                    7.3_12                 r3.3.2_0    conda-forge
r-recommended             3.3.2                  r3.3.2_0    conda-forge
r-rpart                   4.1_10                 r3.3.2_0    conda-forge
r-spatial                 7.3_11                 r3.3.2_0    conda-forge
r-survival                2.40_1                 r3.3.2_0    conda-forge
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                27.2.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.2                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.8                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

3、(gcc) Ru@bogon:~$ r

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin11.4.2 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> .libPaths()
[1] "/Users/Ru/anaconda/envs/gcc/lib/R/library"
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin11.4.2 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

> install.packages("maps")
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/maps_3.1.1.tar.gz'
Content type 'application/octet-stream' length 2338492 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

* installing *source* package ‘maps’ ...
** package ‘maps’ successfully unpacked and MD5 sums checked
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
configure: creating ./config.status
config.status: creating src/Makefile
** libs
** arch -
clang -I/Users/Ru/anaconda/envs/gcc/include  -I/Users/Ru/anaconda/envs/gcc/include -arch x86_64 -L/Users/Ru/anaconda/envs/gcc/lib -lgfortran -L/Users/Ru/anaconda/envs/gcc  Gmake.c   -o Gmake
clang -I/Users/Ru/anaconda/envs/gcc/include  -I/Users/Ru/anaconda/envs/gcc/include -arch x86_64 -L/Users/Ru/anaconda/envs/gcc/lib -lgfortran -L/Users/Ru/anaconda/envs/gcc  Lmake.c   -o Lmake
Converting world to world2
awk -f convert.awk < world.line > world2.line
Creating legacy world2 database
awk -f legacy_convert.awk < legacy_world.line > legacy_world2.line
make county.L state.L usa.L nz.L world.L world2.L italy.L france.L state.vbm.L state.carto.L legacy_world.L legacy_world2.L lakes.L
./Lmake 0 s b county.line county.linestats ../inst/mapdata/county.L
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /private/var/folders/l8/vgdsznqs12l6yxf4tdljm04h0000gn/T/Rtmp56FR4e/R.INSTALL2593136a3842/maps/src/./Lmake
  Reason: image not found
make[1]: *** [county.L] Abort trap: 6
make: *** [ldata] Error 2
ERROR: compilation failed for package ‘maps’
* removing ‘/Users/Ru/anaconda/envs/gcc/lib/R/library/maps’

The downloaded source packages are in
  ‘/private/var/folders/l8/vgdsznqs12l6yxf4tdljm04h0000gn/T/RtmpxnRFVd/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("maps") :
  installation of package ‘maps’ had non-zero exit status

4、~/.bash_profile
#added by Anaconda3 4.3.1 installer
export PATH="/Users/Ru/anaconda/bin:$PATH"
#DYLD 
export DYLD_FALLBACK_LIBRARY_PATH=/Users/Ru/anaconda/lib:/usr/local/lib:/usr/lib:$DYLD_FALLBACK_LIBRARY_PATH

5、(gcc) Ru@bogon:~$ otool -L ~/anaconda/envs/gcc/lib/libgfortran.3.dylib
/Users/Ru/anaconda/envs/gcc/lib/libgfortran.3.dylib:
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

Read a lot of issues, but still did not solve, look forward to your help.
  
@kalefranz Can you help diagnose it?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1715

**Comment by bhomass** [comment]
I see a lot of posting and re-posting, but what is the final answer for solving this problem?

**Comment by mingwandroid** [comment]
`conda install r-maps` is the final answer.

**Comment by radlinsky** [comment]
I'm having the same problem.. I can't start R!


(cd4_thelper_project) Calebs-MacBook-Pro:~ calebradens$ R
dyld: Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/calebradens/miniconda3/envs/cd4_thelper_project/lib/R/lib/libRblas.dylib
  Reason: image not found
Abort trap: 6


conda info:

     active environment : cd4_thelper_project
    active env location : /Users/calebradens/miniconda3/envs/cd4_thelper_project
            shell level : 1
       user config file : /Users/calebradens/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /Users/calebradens/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/calebradens/miniconda3/pkgs
                          /Users/calebradens/.conda/pkgs
       envs directories : /Users/calebradens/miniconda3/envs
                          /Users/calebradens/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
