### ISSUE TITLE
allow automatic download of packages in non-default channels

### ISSUE THREAD

**Issue by lukereding** [conda/conda#5283]
Feature request

In my `conda` usage, I'm usually interested in downloading a package but I don't care what channel it's from. 

In the current state of `conda`, my workflow usually looks something like:

```bash
root@f6300fad4623: conda install tensorflow=1.0.0
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - tensorflow 1.0.0*

```

I then have to go [anaconda cloud](https://anaconda.org/), search for the package, note the correct channel, then 

```bash
root@f6300fad4623: conda install -c conda-forge tensorflow=1.0.0
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    funcsigs:   1.0.2-py27_0  conda-forge
    mkl:        2017.0.1-0               
    mock:       2.0.0-py27_0  conda-forge
    numpy:      1.12.1-py27_0            
    pbr:        3.0.0-py27_0  conda-forge
    protobuf:   3.3.0-py27_0  conda-forge
    tensorflow: 1.0.0-py27_0  conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:      4.3.17-py27_0             --> 4.2.13-py27_0 conda-forge
    conda-env:  2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? 
```

I often have to repeat this several times when installing packages for a given project.

It would be ideal if there was an option that would allow 'automatic download of packages outside of default channels'. I am aware that I can [edit my `.condarc` config file](https://conda.io/docs/config.html#channel-locations-channels) to allow `conda` to search for packages in other channels, but given the number of channels it is difficult to anticipate in advance that I will need a package in a given channel. Is it possible for `conda` to automatically find the channels with the package I'm looking for?

The code above was run using [this](https://hub.docker.com/r/continuumio/miniconda/) docker image.

**Comment by kalefranz** [comment]
> Is it possible for conda to automatically find the channels with the package I'm looking for?

That sounds like a lot of "magic" that could have some pretty severe unintended consequences.

Actually, it's similar to an experiment where conda would automatically fall back to `pip install` for a package if the conda package didn't exist.  That ended up being a complete disaster.

**Comment by kalefranz** [comment]
Also, conda has no knowledge the the Anaconda API.  There's a strict design separation there.  You can use the anaconda client and `anaconda search`.
