### ISSUE TITLE
Conda confirmation prompt doesn't accept no

### ISSUE THREAD

**Issue by aburgm** [conda/conda#5288]
When running `conda create` or another command and then choosing "no" at the prompt where it asks you to proceed, conda still goes ahead and performs the operation.

Looks like this might have been introduced by #5203.

**Comment by kalefranz** [comment]
Oh th

**Comment by kalefranz** [comment]
Oh that's bad. A PR that's only meant to add additional test coverage, and we break things. Thanks for the report.

**Comment by kalefranz** [comment]
Can't release any 4.4 without this fixed.

**Comment by kalefranz** [comment]
merged to 4.4.x with #5291
