### ISSUE TITLE
Updating PyQt4 to PyQt5 leaves an empty PyQt4 directory in site-packages

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda/conda#5290]
For some reason, I ended up with an empty 'PyQt4' directory (next to a correct install of PyQt5) in the site-packages directory of an env. 
The reason I noticed this is because it broke the import of pandas (and also of matplotlib): pandas does a `import PyQt4` import to check whether it is installed (which works with an empty directory), and if so, later on imports actual functionality from PyQt4 (which then fails). Somebody else just reported the same problem: https://github.com/pandas-dev/pandas/issues/16322

I have conda 4.3.17, on Ubuntu 16.04, python 3.5. But, I can't really give more details as I don't remember anymore what I exactly did before this happened. I suppose it was after updating some stuff (eg matplotlib). But, I can not reproduce it in a clean env (first installing pyqt4 and then updating works just fine). 
For @dibgerge the same happend when he updated pandas from 0.19.2 to 0.20.1 (which might also update the matplotlib version, and so pyqt4 version, as pyqt is not a direct dependency of pandas). Maybe he can give more details on what he exactly did.

Sorry for the vague description, but as I was apparently not the only one with this issue, I thought I could report it.

**Comment by kalefranz** [comment]
> which works with an empty directory

Really?

```
$ mkdir /conda/lib/python2.7/site-packages/PyQt44
$ /conda/bin/python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import PyQt44
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named PyQt44
```

**Comment by jorisvandenbossche** [comment]
Hmm, you are of course completely correct that it does not work without an init file in it. I forgot for a moment my common sense when I encountered the issue, didn't know the reason but saw the empty dir . :-) 
But apart from that, I had at a certain moment an conda python environment, where I could both import PyQt4 and PyQt5, but without an actual working PyQt4 install (`import PyQt4` worked, `from PyQt4 import something` not), and I saw that empty directory. But then there should be something else causing it .. 

As I said, I cannot reproduce it, so this is probably not very helpful, and so feel free to close. It is just a bit strange that someone else encounters exactly the same.

**Comment by jorisvandenbossche** [comment]
Just checked my Trash, the directory was still there, and I was actually not fully correct. It was not empty, but did still have a `__pycache__` directory (and inside one file `__init__.cpython-3.5.pyc`).
Can that be the reason that the import still worked? 

And maybe the reason could be an update from PyQt4 to 5 when there was a console active where the package was loaded?

**Comment by kalefranz** [comment]
Yeah now that's interesting.

Are you working on Windows or a unix?

**Comment by kalefranz** [comment]
> Can that be the reason that the import still worked?

Yes, that is the reason the import still worked.  So now we should figure out how that file stuck around...

**Comment by jorisvandenbossche** [comment]
Unix -> Ubuntu 16.04, conda 4.3.17

**Comment by kalefranz** [comment]
Are you using packages from `defaults` or from `conda-forge`? Or both?

**Comment by kalefranz** [comment]
And python 3.5? Have you switched back and forth between different python versions?

**Comment by jorisvandenbossche** [comment]
OK, I can reproduce this now. For now, I tried to reproduce with Python 3.5 and using defaults (normally I use conda-forge).

Steps to reproduce:

- `conda create -n test_qt python=3.5 pandas matplotlib qt=4 -c defaults`
- `source activate test_qt`
- run python and import pandas or matplotlib (after that `'PyQt4' in sys.modules` gives True, as it is imported by pandas or matplotlib)
- leave the existing session open, and open a new terminal. 
- in the new terminal, activate the environment, and update eg matplotlib `conda update matplotlib -c defaults` (which will update the qt version)
- run python and try to import pandas or matplotlib -> import error

**Comment by kalefranz** [comment]
So I guess there's a step there where conda removes that file, and then the python interpreter adds it back, correct?  Can you isolate exactly where that happens?

**Comment by jorisvandenbossche** [comment]
How can I do that? Just from naively watching the directory, it seems it never was fully removed

**Comment by nehaljwani** [comment]
I was able to reproduce this in the same prompt:

```
(root) barry@condaexpts:~$ conda create -yn test_qt python=3.5 pyqt=4 -c defaults
(root) barry@condaexpts:~$ source activate test_qt
(test_qt) barry@condaexpts:~$ ls $CONDA_PREFIX/lib/python3.5/site-packages/PyQt4/__pycache__
ls: cannot access /home/barry/condaexpts/m3/envs/test_qt/lib/python3.5/site-packages/PyQt4/__pycache__: No such file or directory
(test_qt) barry@condaexpts:~$ python -c "import PyQt4"
(test_qt) barry@condaexpts:~$ ls $CONDA_PREFIX/lib/python3.5/site-packages/PyQt4/__pycache__
__init__.cpython-35.pyc
(test_qt) barry@condaexpts:~$ conda update qt
(test_qt) barry@condaexpts:~$ conda list | grep qt
# packages in environment at /home/ubuntu/condaexpts/m3/envs/test_qt:
pyqt                      5.6.0                    py35_2  
qt                        5.6.2                         3  
(test_qt) barry@condaexpts:~$ ls $CONDA_PREFIX/lib/python3.5/site-packages/PyQt4/__pycache__
__init__.cpython-35.pyc
(test_qt) barry@condaexpts:~$ python -c "import PyQt4; print(PyQt4.__path__)"
_NamespacePath(['/home/barry/condaexpts/m3/envs/test_qt/lib/python3.5/site-packages/PyQt4'])
```
By the way, the pyqt package in the menpo channel tracks the `__pycache__` files in `info/files` and the one in the defaults channel doesn't.

**Comment by kalefranz** [comment]
> By the way, the pyqt package in the menpo channel tracks the __pycache__ files in info/files and the one in the defaults channel doesn't.

Oh! Then this might just be a bad package.

**Comment by kalefranz** [comment]
I've verified myself exactly what @nehaljwani discovered.  Looking at https://repo.continuum.io/pkgs/free/osx-64/pyqt-4.11.4-py35_4.tar.bz2

So this indeed is something we'd ascribe to a packaging problem, and not a conda problem.

If we are to fix this, the correct fix is to rebuild these packages and this time include the pyc files.  However, @ilanschnell's current opinion is that these packages are old enough that we shouldn't worry about it.

If you disagree, or this issue becomes more than just a minor annoyance, feel free to file an issue at https://github.com/ContinuumIO/anaconda-issues regarding an update for these packages.

**Comment by jorisvandenbossche** [comment]
The problems is also for people who already have the package installed, so updating the package will not help for those. So sounds certainly reasonable to not update the package.

**Comment by Nikhilkumar8143** [comment]
AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)

Can you help me out in this? 
I dont understand what to do? 
Please help me through this
