### ISSUE TITLE
Activate the environment again if the current environment is updated

### ISSUE THREAD

**Issue by isuruf** [conda/conda#5292]
This is needed if a package is installed to the current environment and it needs activating.

**Comment by nehaljwani** [comment]
@isuruf  Could you please share a _package name_ as example which needs 'activating' ?

**Comment by isuruf** [comment]
`sage` package from `conda-forge` channel

**Comment by nehaljwani** [comment]
If you are referring to https://github.com/conda-forge/sage-feedstock/ , then it seems to be a meta-package. I wonder why you need to re-activate a conda environment after installing sage into it.

**Comment by isuruf** [comment]
Sorry, I meant `sagelib` feedstock

**Comment by isuruf** [comment]
https://github.com/conda-forge/sagelib-feedstock/blob/master/recipe/activate/activate.sh

**Comment by kalefranz** [comment]
This is fixed with #5044 which will be in conda 4.4.

**Comment by isuruf** [comment]
Thanks
