### ISSUE TITLE
Minidconda \\ Upon deactivating an env, conda command stops working. 

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5323]
_From @haftab27 on May 15, 2017 8:59_

Pre-Reqs: 

- User has installed minidconda3 4.3.14 as Install for 'All User'. 
- In Advance installation options, Anaconda is not added in System Environment Path variable. 
![screenshot_2](https://cloud.githubusercontent.com/assets/24476512/26049742/7b359d2e-3975-11e7-9526-01d885e6ff35.png)

Steps to reproduce 

- Open the “Anaconda Prompt” by clicking on it from the Start Menu
- Run `conda create -y -n test-env python=3`
- Run `activate test-env`
- Run `deactivate`
- Run `conda info -e`

Actual: 

- Conda command is not running, as prompt is showing that conda is not recognized as internal or external command. 
![screenshot_3](https://cloud.githubusercontent.com/assets/24476512/26050064/ba951174-3976-11e7-9021-3529f09514b4.png)

  

_Copied from original issue: ContinuumIO/anaconda#814_

**Comment by kalefranz** [comment]
Right now this is expected behavior. You can deactivate your way out of conda being on PATH. There are pros and cons to changing this behavior.

**Comment by kalefranz** [comment]
Resolved with conda 4.4.

**Comment by Usama23** [comment]
@kalefranz 

Miniconda 4.5.4
conda 4.5.4

By deactivating base environment, conda commands are not working.

![screenshot_1054](https://user-images.githubusercontent.com/21064099/41290384-2c01ef06-6e66-11e8-9ed0-173b015cc826.png)

**Comment by mingwandroid** [comment]
Not a bug.
