### ISSUE TITLE
Ambiguous package resolution for X.Y and X.Y.0

### ISSUE THREAD

**Issue by ebolyen** [conda/conda#5330]
Hello everyone,

I'm not sure if this is a duplicate, but I ran across something pretty unintuitive. It involves packages that have a version of `X.Y` and `X.Y.0` available. Specifically, there is a package on the `bioconda` channel that has both a `1.4.0` version and a `1.4` version. I'd like to install `1.4.0`, however conda reports that there are 2 package resolution options and will randomly switch which choice it makes. 

I'm not sure why `1.4` would be chosen as I requested the more specific `1.4.0` (I could see how the opposite would be ambiguous however). I suppose this has to do with PEP440's implicit `.0` versions, but I'm still not sure how to disambiguate these cases. Are these versions incorrectly unique in filename, but semantically (according to PEP440) identical?

```

(q2-dev) 13:23:09 § conda install -c bioconda "bioconductor-dada2=1.4.0"
Fetching package metadata ...........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - bioconda::bioconductor-dada2-1.4.0-r3.3.1_0
  - bioconda::bioconductor-dada2-1.4-r3.3.1_0

Package plan for installation in environment /home/evan/.conda/envs/q2-dev:

The following packages will be UPDATED:

    bioconductor-dada2: 1.2-r3.3.1_0 bioconda --> 1.4.0-r3.3.1_0 bioconda

Proceed ([y]/n)? n

Exiting
```
```
(q2-dev) 13:23:52 § conda install -c bioconda "bioconductor-dada2=1.4.0"
Fetching package metadata ...........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - bioconda::bioconductor-dada2-1.4-r3.3.1_0
  - bioconda::bioconductor-dada2-1.4.0-r3.3.1_0

Package plan for installation in environment /home/evan/.conda/envs/q2-dev:

The following packages will be UPDATED:

    bioconductor-dada2: 1.2-r3.3.1_0 bioconda --> 1.4-r3.3.1_0 bioconda

Proceed ([y]/n)? n

Exiting
```

**Comment by kalefranz** [comment]
Can you see if

    conda install -c bioconda "bioconductor-dada2==1.4.0"

with two equal signs will consistently give you what you want?  Not that we don't have something here to clean up.  But just to see if it makes a difference...

**Comment by ebolyen** [comment]
I'm getting the same behavior with `==`. Additionally, since I was upgrading in the above example, I thought I would try installing fresh (without the existing `1.2` version), but I'm getting the same stochastic resolution as before (with either version delimiter).

I also realized I didn't give you any information about my conda install (sorry!):

<details>
<summary>original conda info</summary>

```
18:48:17 ~ § conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 2.1.8
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /opt/miniconda3  (read only)
    default environment : /opt/miniconda3
       envs directories : /home/evan/.conda/envs
                          /opt/miniconda3/envs
          package cache : /opt/miniconda3/pkgs
                          /home/evan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Linux/3.13.0-110-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000
```
</details>
&nbsp;

I seem to have been using a version that was two patches old, I've just updated conda to `4.3.18`, but the results are identical.

<details>
<summary>updated conda info</summary>

```
18:57:10 ~ § conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 2.1.8
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /opt/miniconda3  (read only)
    default environment : /opt/miniconda3
       envs directories : /home/evan/.conda/envs
                          /opt/miniconda3/envs
          package cache : /opt/miniconda3/pkgs
                          /home/evan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.18 requests/2.13.0 CPython/3.5.3 Linux/3.13.0-110-generic debian/jessie/sid glibc/2.19    
                UID:GID : 1000:1000
```
</details>

**Comment by ebolyen** [comment]
It looks like if I provide a build-id/number I no longer get the ambiguous package resolution:
```
(q2-dev) 19:03:43 ~ § conda install -c bioconda "bioconductor-dada2=1.4.0=r3.3.1_0"
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/evan/.conda/envs/q2-dev:

The following packages will be UPDATED:

    bioconductor-dada2: 1.2-r3.3.1_0 bioconda --> 1.4.0-r3.3.1_0 bioconda

Proceed ([y]/n)? n

Exiting
```

This seems a little weird because both versions have the same build-id/number, but maybe just providing that makes conda generate the filepath it expects from anaconda.org instead of searching?

This solves my immediate problem, but let me know if I can be of further assistance!

**Comment by kalefranz** [comment]
This is definitely a bug.  Thanks for the report.

**Comment by mcg1969** [comment]
Actually, PEP440 calls for 1.4.0 and 1.4 to be evaluated as equal. `conda` is working exactly as designed in this regard.

**Comment by mcg1969** [comment]
As for adding the build number, that's also expected behavior---if you supply both a version and build match it assumes an exact string-based match, instead of a numeric version match.

I'm afraid the real problem here is with `bioconda`. It should not have 1.4 and 1.4.0 present in the same channel.

**Comment by kalefranz** [comment]
> I'm afraid the real problem here is with bioconda. It should not have 1.4 and 1.4.0 present in the same channel.

Ah.  Yup.

**Comment by ebolyen** [comment]
That makes sense, thanks all. I know this isn't `conda`'s problem specifically but should `anaconda.org` be normalizing package names for `conda` file types?

**Comment by kalefranz** [comment]
What do you mean?

**Comment by ebolyen** [comment]
Well since `1.4` and `1.4.0` are the same version, shouldn't that be disallowed on anaconda.org? 

My understanding was a build number was the correct way to manage multiple files having the same "version". It seems like permitting both `X.Y` and `X.Y.0` files to exist breaks some assumptions and so normalizing the package name to PEP440 would at least prevent the same version from existing twice without different build numbers (e.g. you'd have to either use `--force` or increment the build number in order to upload). There's also a great many ways that PEP440 can normalize things, so it is probably very easy to accidentally duplicate packages where the versions are "identical". 

But I can totally see how "just don't upload non-normalized versions" is a pretty simple solution and avoids a million other technical problems.

**Comment by kalefranz** [comment]
Oh, I see what you mean now.  anaconda.org probably only de-dupes by file name, and not by version here.  And those two would have different file names.

If you want to file a feature request, you can do so at https://github.com/Anaconda-Platform/support/issues.  I'm not sure they'll want to implement it though.  Something like this is really up to the package maintainer I think.
