### ISSUE TITLE
CondaMultiError: 'ascii' codec can't decode byte 0xb9 in position 811: ordin al not in range(128)

### ISSUE THREAD

**Issue by yiranxijie** [conda/conda#5336]
===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::ca-certificates-2017.1.23-0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\ca-certificates-2017.1.23-0

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::jpeg-9b-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\jpeg-9b-vc9_0

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::openssl-1.0.2h-vc9_3 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\openssl-1.0.2h-vc9_3

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::vc-9-0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\vc-9-0

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::zlib-1.2.11-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\zlib-1.2.11-vc9_0

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::icu-58.1-vc9_1 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\icu-58.1-vc9_1

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::libpng-1.6.28-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\libpng-1.6.28-vc9_0

===> LINKING PACKAGE: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-
forge::qt-5.6.2-vc9_1 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes
  source=C:\Users\Administrator\Miniconda2\pkgs\qt-5.6.2-vc9_1

An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn
/anaconda/cloud/conda-forge::qt-5.6.2-vc9_1'.
UnicodeDecodeError('ascii', 'C:\\Users\\Administrator\\Miniconda2\\Library\\bin;
C:\\Users\\Administrator\\Miniconda2\\envs\\snakes;C:\\Users\\Administrator\\Min
iconda2\\envs\\snakes\\Library\\mingw-w64\\bin;C:\\Users\\Administrator\\Minicon
da2\\envs\\snakes\\Library\\usr\\bin;C:\\Users\\Administrator\\Miniconda2\\envs\
\snakes\\Library\\bin;C:\\Users\\Administrator\\Miniconda2\\envs\\snakes\\Script
s;E:\\Python27\\Lib\\site-packages\\PyQt4;C:\\ProgramData\\Oracle\\Java\\javapat
h;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\Sys
tem32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Java\\jdk1.8.0_102\\bin;C:\\
Program Files\\Java\\jdk1.8.0_102\\jre\\bin;C:\\Program Files\\Git\\cmd;C:\\Prog
ram Files\\nodejs\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\B
inn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Fi
les\\Microsoft SQL Server\\100\\DTS\\Binn\\;D:\\tao\\\xb9\xa4\xbe\xdf\\Strings;D
:\\tao\\\xb9\xa4\xbe\xdf\\upx393w;D:\\tao\\\xb5\xda\xd2\xbb\xd0\xd0\xb4\xfa\xc2\
xeb\xd1\xa7\xcf\xb0\\android-sdk_r24.4.1-windows\\sdk\\tools;D:\\tao\\\xb5\xda\x
d2\xbb\xd0\xd0\xb4\xfa\xc2\xeb\xd1\xa7\xcf\xb0\\android-sdk_r24.4.1-windows\\sdk
\\platform-tools;E:\\Python27;D:\\tao\\Android_The_First_Line_Code\\android-sdk_
r24.4.1-windows\\sdk\\tools;D:\\tao\\Android_The_First_Line_Code\\android-sdk_r2
4.4.1-windows\\sdk\\platform-tools;C:\\Users\\Administrator\\Miniconda2;C:\\User
s\\Administrator\\Miniconda2\\Scripts;C:\\Users\\Administrator\\Miniconda2\\Libr
ary\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\npm;D:\\android-ndk-r8;', 8
11, 812, 'ordinal not in range(128)')
Attempting to roll back.

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::qt-5.6.2-vc9_1 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::libpng-1.6.28-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::icu-58.1-vc9_1 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::zlib-1.2.11-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::vc-9-0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::openssl-1.0.2h-vc9_3 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::jpeg-9b-vc9_0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

===> REVERSING PACKAGE LINK: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
/conda-forge::ca-certificates-2017.1.23-0 <===
  prefix=C:\Users\Administrator\Miniconda2\envs\snakes

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\Administrator\Miniconda2  (writable)
    default environment : C:\Users\Administrator\Miniconda2\envs\snakes
       envs directories : C:\Users\Administrator\Miniconda2\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\Users\Administrator\Miniconda2\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/co
nda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/co
nda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Administrator\.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.4 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : unknown

`$ C:\Users\Administrator\Miniconda2\Scripts\conda-script.py install qt -v`

    Traceback (most recent call last):
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\exceptions
.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\cli\main.p
y", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\cli\main_i
nstall.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\cli\instal
l.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\plan.py",
line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\instructio
ns.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\instructio
ns.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Users\Administrator\Miniconda2\lib\site-packages\conda\core\link.
py", line 297, in execute
        rollback_excs,
    CondaMultiError: 'ascii' codec can't decode byte 0xb9 in position 811: ordin
al not in range(128)

**Comment by kalefranz** [comment]
If you're going to be using non-ascii unicode characters, I highly recommend making your root environment python3, and then using individual conda environments for anything needing python 2.  Unicode paths on Windows when conda is running under python 2 is not supported.
