### ISSUE TITLE
Discussion: Conda packages metadata

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#5340]
## Description

This issue should serve as a discussion for the metadata content  for both repo.continuum.io and anaconda.org, pinging several people to gather some thoughts.

## Goals

- **What** needs to go into the (global) metadata of a given channel/repo?
- **How** should we package and generate this information (conda-build)
- **How** should we serve it in a way that is consistent with conda, repo.continuum.io and anaconda.org.

## Present status
Repo.continuum.io provides: https://repo.continuum.io/pkgs/free/metadata.json 

```json
"package-name": {
    "description": "The Affine package is used to produce the affine transformation.", 
    "dev_url": "https://github.com/ContinuumIO/anaconda/tree/master/packages/affine", 
    "doc_url": "https://anaconda.org/anaconda/affine", 
    "home": "https://github.com/sgillies/affine", 
    "license": "BSD", 
    "source_git_url": "https://github.com/sgillies/affine.git", 
    "summary": "Matrices describing affine transformation of the plane.", 
    "version": "2.0.0" 
    "source_git_tag": "2.0.0",
    "platforms": "linux-64 win-32 win-64 linux-32 osx-64",
}
```

This is currently being used by Anaconda Navigator to provide descriptions for packages.

This metadata is a global metadata that gets updated when newer versions are "uploaded", so even though these fields (license, icon, version, summary, etc...) might change from version to version, we just care about the most recent (as in latest version) value.

#### Nitpicks

We could do much better with a list, instead of a space separated string :-)

```json
...
    "platforms": "linux-64 win-32 win-64 linux-32 osx-64",
...
```

## URL for metadata
Some options suggested by @kalefranz include:
- https://conda.anaconda.org/anaconda/assets/repodata.json
- https://conda.anaconda.org/anaconda/metadata/repodata.json

So that the directory structure for a given channel is preserved. 

## Navigator needs

For navigator we need a way to gather this information in a way that s consistent between repo and anaconda.org, and we also need to have access to the icon of applications that define one.

So an extra entry like:

```json
...
"icon_url":  ./assets/9779607c273dc0786bd972b4cb308b58.png
...
```
Where the hash is what conda-build currently generates.

### Conda-build
@msarahan 

Conda build needs to be able to generate this information via the `index` command. We could support more formats, or advice on the image dimensions for instance (squarish works better for instance).

Store the icon in the package AND in the index (some duplication??).
- Is the `<hash>.png` a good naming scheme? I think a `package-name-<hash>.<ext>` could work nicely.
- How to handle duplicates when regenerating the index?

### Conda
@kalefranz

Conda could also use this metadata to display extra information when running the info, search, list commands. It would also be nice if conda coulda handle downloading and caching these files just like it currently does with the repodata.json of other channels.

## Anaconda client / Anaconda.org
@dsludwig, @abarto

The anaconda client needs to be updated in order to include this information and upload. There is some logic that already upload b64 images for notebooks thumbnails.

## Other comments / Questions?
- We need to have a bz2 version as well
- What other metadata needs would fit here (I heard @teoliphant talk about tags at some point for instance)

**Comment by stefanseefeld** [comment]
This relates a lot to what we have been working on lately in the context of a new conda API.

**Comment by goanpeca** [comment]
@stefanseefeld, I just finished the description, don't know if it is what you had in mind

**Comment by stefanseefeld** [comment]
Yes, it's definitely related. (In the API project we are now trying to encapsulate the metadata such that we are in a good position to change a) its storage (might use SQLite in the future, for example), and b) what we want to store. So yes, this is very much related.
