### ISSUE TITLE
Anaconda update doesn't clean automatically older packages

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5347]
_From @SMH17 on March 10, 2017 20:11_

I usually update packages with 

`conda update --all`

I have see that in `Anaconda3\pkgs `there are accumulated all older versions of updated packages that aren't needed anymore. That isn't good. Update task should clean older packages after the upgrade, not only download newer versions updating dependencies, deleting manually all older packages is very annoying. 

OS: Windows 10 x64

_Copied from original issue: ContinuumIO/anaconda-issues#1515_

**Comment by kalefranz** [comment]
For this we have the `conda clean --packages` command.  Effectively adding a callback to `conda clean --packages` after a `conda update` command would be a major change in behavior at this point.  Many conda users rely on the package cache being populated for (1) usage with the `--offline` flag and (2) the ability to roll back to previous installs with `conda list --revisions` and `conda install --rev REV_NUM`.

If there is more interest in the future by more users, we can continue to discuss.  For now, I'm going to close this feature request as "won't fix" given the above explanation.

**Comment by Adrien79** [comment]
At the very least, I think that there should be a message displayed to the user after `conda update`, like this: "do not forget to apply `conda clean -p` if you want to clear the package cache".
I've just discovered that I had 3 GB of unused packages lying around on my hard disk from previous updates, and I found this quite annoying.

**Comment by michaelaye** [comment]
just discovered 18 GB of older packages! Would be nice if we could schedule a monthly cleaning or something like that.

**Comment by Adrien79** [comment]
See also #1003 open since 2014.

**Comment by faceduck** [comment]
same here. I just cleaned up 2 GB worth of updates from just 3 months. Please autosuggest conda  clean -p :)

**Comment by kalefranz** [comment]
> we can continue to discuss

Actually, rather than discussing here, please comment in #1003 or open a new issue if #1003 isn't close to what you want.
