### ISSUE TITLE
Anaconda update unexpected error

### ISSUE THREAD

**Issue by truesebastian** [conda/conda#5349]
I get the following message when trying to update anaconda with "conda update anaconda":
Current conda install:

               platform : win-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 1.8.2
         python version : 2.7.8.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
                          C:\Users\User\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.18 requests/2.14.2 CPython/2.7.8 Windows/8 Windows/6.2.9200
          administrator : unknown

`$ C:\Anaconda\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "C:\Anaconda\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_package.py", line 27, in <module>
        from ..install import PREFIX_PLACEHOLDER
    ImportError: cannot import name PREFIX_PLACEHOLDER

**Comment by truesebastian** [comment]
Another problem: spyder does not start when trying to start it.

**Comment by kalefranz** [comment]
I've double-checked, and nothing has changed in 4.3.18 with that import.  The code is there; it should work.  Which means the python files for conda's code have been borked somehow.  Easiest solution is to download a new miniconda2 installer, then run it overtop `C:\Anaconda`.

**Comment by truesebastian** [comment]
Thank you. How do I install overtop C:\Anaconda  ? The miniconda installer doesn't let me choose this directory as it is not empty.
