### ISSUE TITLE
Conda HTTPError with anaconda-fusion channel

### ISSUE THREAD

**Issue by rwhitt2049** [conda/conda#5352]
I'm getting the following error when trying to do `conda install`

Fetching package metadata ...

CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusi
on/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(SSLError(SSLError("bad handshake: SysCallError(10053, 'WSAECONNABORTED'
)",),),)

I have tried all of the standard advice that I've seen in the issues list for similar issues, but to no avail. I've also done an uninstall and re-install.

(This didn't work for me)
set CONDA_SSL_VERIFY=false
conda update -c defaults conda cryptography pyopenssl requests
set CONDA_SSL_VERIFY=

I eventually just removed anaconda-fusion from my channels and that fixed my immediate issue. (I've seen this issue on two other of my colleague's computers. None of us have changed our .condarc file from whatever the default is and none of us have added it from the command line as a channel either)

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\Users\whittr1\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\___\AppData\Local\conda\conda\envs
                          C:\Users\___\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\___\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\___\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

**Comment by kalefranz** [comment]
After you removed the anaconda-fusion channel and then successfully did 

    conda update -c defaults conda cryptography pyopenssl requests

can you add the anaconda-fusion channel back and have conda work again?

**Comment by rwhitt2049** [comment]
This didn't seem to help me. I ended up pip installing requests==2.11.2 and that seemed to fix the issue, but caused some other minor annoyances such as ignoring my CONDA_ENVS_PATH environment variable. I finally just punted and reinstalled miniconda and made sure to leave my root env alone (lesson learned).

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```

**Comment by rwhitt2049** [comment]
@tpowellcio that did it. Thanks!
