### ISSUE TITLE
Miniconda installation fails to have write rigths and cannot install/udpate

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5354]
_From @rubennj on December 17, 2016 21:31_

Conda says it cannot write and therefore it doesn't install/update anything.
This happens when Miniconda is installed for all users, however it works when is installed only for the current user.

Version: Miniconda3-4.2.12-Windows-x86_64.exe

_Copied from original issue: ContinuumIO/anaconda-issues#1302_

**Comment by kalefranz** [comment]
Fixed as of conda 4.3.13.  Use a newer miniconda installer.
