### ISSUE TITLE
Can't Install tensorflow- caused by conflict

### ISSUE THREAD

**Issue by Deepankar-Sedai** [conda/conda#5355]
I was trying to install tensorflow in ubuntu but i ended up with this problem:

acer@acer-MS-7592:~$ conda install -c jjhelmus tensorflow=0.12.0rc0
Fetching package metadata ...........
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tensorflow 0.12.0rc0*
Use "conda info <package>" to see the dependencies for each package.

please suggest a solution for this problem.

**Comment by kalefranz** [comment]
That package hasn't been compiled for python 3.6, which is your default python according to your root environment.

    conda install -c jjhelmus tensorflow=0.12.0rc0 python=3.5

will fix your problem.

**Comment by kalefranz** [comment]
related to the add_defaults_to_specs function behavior

**Comment by Deepankar-Sedai** [comment]
thanks dude,it worked
