### ISSUE TITLE
Support package variants

### ISSUE THREAD

**Issue by stefanseefeld** [conda/conda#5360]
Packages, notably ones containing C extension modules, can be optimized for different hardware (including GPUs).
Allow conda to track multiple variants of such packages, such that `conda install` could then fetch and install the appropriate variant, depending on a) user requests, or b) based on the specific hardware available.
As a point in case, The TensorFlow package now emits warnings of the form
```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
```
letting users wonder how to obtain a variant that has SSE4.1 support, etc.

**Comment by kalefranz** [comment]
The general direction I think we want to go here is to extend the feature concept to be multi-value, not just the binary True/False.

**Comment by electronwill** [comment]
Suppose someone installs such a package, and then upgrades their CPU without changing the motherboard, disk, or the rest of the system, and then they try to use the package again. Do they get any errors? If so, what errors, and how are they produced?

**Comment by stefanseefeld** [comment]
I'm not exactly sure what you mean by "upgrades their CPU", but if it's a CPU which is no longer compatible with the instruction set used in the installed binaries, he will most likely get SIGILL errors.
Likewise, the removal of a GPU may cause other runtime errors that may or may not be handled gracefully by the software.
I don't think we should worry about this use case. It should however be possible to upgrade / downgrade packages to replace them by other variants that support the locally available hardware. (i.e. fall back to generic versions without any platform-specific optimizations.)

**Comment by electronwill** [comment]
The possibility I had in mind was someone switching the CPU for one with the same socket that supports new instruction set extensions such as SSE4.1 and getting the warning above. However, as I dig a little deeper it appears that instruction set extensions are exactly the same for all the CPUs that fit any given socket, even if marketing terms such as "Core i7" include CPUs with different sockets and different instruction set extensions. More generally, I agree that people changing a CPU, motherboard, or GPU will expect that they need to reinstall everything or at least take some extra steps to fall back to generic versions, so as you say, no need to worry about this.

**Comment by kalefranz** [comment]
Now tracking via https://github.com/conda/conda/issues/6950
