### ISSUE TITLE
[ENH] make activate work if old env doesn't exist any more

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5361]
I have spent a long time convincing myself that I am a rare, if not unique, case in the way I keep getting myself into this mixed up situation of having an "activated" conda environment that I've deleted.  But I've done it so many times in the past week that I'm thinking other people must do it at least occasionally.  This is what it looks like:

```bash
(envs/default) $ rm -Rf envs/default                  # delete a bad env, but OOPS, it is still activated

(envs/default) $ anaconda-project run                 # dang, that's not going to work.
-bash: anaconda-project: command not found

(envs/default) $ source activate root                 # try to switch to root, but activate is not on the path
-bash: activate: No such file or directory

(envs/default) $ source ~/anaconda/bin/activate root  # well, I know where it lives, so I'll do that

CondaValueError: Value error: Could not find environment: /Users/ijstokes/teaching/python/pycon2017-anaconda-project-data-science-apps/mnist_digit_recognition/envs/default

-bash: sed: command not found
-bash: grep: command not found
-bash: grep: command not found
-bash: grep: command not found
-bash: sed: command not found
```

Oh dear, now my shell is pooched.  Close and re-open.

So maybe if conda were in its own env that was always on the path, and the activate script came from that location instead of from the "active" env, then this problem would go away.

But if that is a long way off, or if the isolated-conda-env idea doesn't solve this problem, then perhaps doing `source /path/to/another/env/bin/activate foo` could either be made to work as expected or to fail gently instead of catastrophically.

**Comment by kalefranz** [comment]
This is resolved with `conda activate` in conda 4.4, since `conda activate` is now a shell function rather than a script that needs to be sourced.
