### ISSUE TITLE
envs_dirs not being respected by conda create

### ISSUE THREAD

**Issue by gddcunh** [conda/conda#5366]
I've seen some other issues with envs_dirs mentioned but they seem to address something slightly different. 

My setup: running anaconda3/4.3.1 with conda/4.3.14. This is installed to a central readable but not writable directory. I want to enable a shared environment folder.

I created a .condarc in that directory and included 

```
envs_dirs:
 - /data/conda

```
When I run conda info, it confirms that both that the .condarc is being used and /data/conda is the first "envs directories" entry.  So far, so good.

However, when I do a conda create (e.g. conda create -n test python=3.5) it tries to install it in ~/.conda/envs/test. 

I've confirmed the /data/conda is writeable and I can create an environment there using "conda create -p /data/conda/test python=3.5". However, I don't see why it would not try to create the environment there by default. When I use the -vvv option, it doesn't ever seem to be checking for /data/conda.

**Comment by kalefranz** [comment]
If you're using conda 4.3.1, that's your problem.  Latest conda version is 4.3.18.

**Comment by gddgithub** [comment]
That was a typo. Should have been 4.3.14. I'll upgrade to 4.3.18 and see if that helps but didn't see anything in the changelog about it.

**Comment by kalefranz** [comment]
Please include the output of `conda info` and `conda config --show`.
