### ISSUE TITLE
Simple Install Issue PLEASE HELP A BEGINNER!

### ISSUE THREAD

**Issue by orbitalhybridization** [conda/conda#5369]
Hi Coders,

This one should be easy for ya.

I'm here trying to use this 64-bit installer to install Anaconda 4.3.1 on my 64-bit Windows computer. I'm going through the prompts that they give me but am unable to pass a certain point without an error message popping up, and have been stuck here for quite a little while.

It happens when I try to choose an install location. As soon as I try to put the program in the recommended folder (C:\Users\Me\Anaconda3), the following error message shows up:

**The installation directory has 1 space. This can cause problems with several Conda packages. Please consider removing the space.**

Now I've tried putting it in my Program Files folder, and also my Program Files (x86). I've tried creating new folders in different locations and it's still not budging smoothly. Instead, this message shows up:

**Directory 'C:\Program Files' is not empty, please choose a different location.**

 I don't wanna shoehorn this, as that would likely cause some annoying problems in the future. Any advice for someone just trying to take a class?

Thanks!

**Comment by kalefranz** [comment]
So you get the message 

> The installation directory has 1 space. This can cause problems with several Conda packages. Please consider removing the space.

for the directory 

    C:\Users\Me\Anaconda3

when that path clearly has no space?

**Comment by mingwandroid** [comment]
> The installation directory has 1 space. This can cause problems with several Conda packages. Please consider removing the space.

.. is only a warning, you can just ignore it, esp. if it's reporting it incorrectly (though I've never seen that).
