### ISSUE TITLE
Try to update all components via command line would hang frequently

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5375]
_From @kevin-coder on July 10, 2016 4:46_

When I tried to update all the components via command line, it will hang frequently.
Reproduce steps:
1. Open cmd.exe
2. Type: conda update --all
Wait sometime, and it would hang somewhere during downloading components.

_Copied from original issue: ContinuumIO/anaconda-issues#894_

**Comment by kalefranz** [comment]
This is basically a feature request to bring back some of the progress output that got dropped in conda 4.3.  On the way!

**Comment by kalefranz** [comment]
resolved with #5546
