### ISSUE TITLE
conda handling of invalid auth tokens

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5381]
Using v4.3.18 `conda update conda` fails due to borked auth token that, on first inspection, doesn't even appear to exist to a user (i.e. it looks like they are logged out).  conda DOES tell me what to do to solve the problem (which is good) -- execute `anaconda logout` --  but I feel like the problem shouldn't have happened in the first place.

When I try to do simple operations `conda` fails with an HTTP 401 error message about invalid auth token for accessing the `anaconda-fusion` channel, even though the channel is public/world-readable (I thought there was an issue out for that already, but I can't find it), and worse when I go and do `anaconda whoami` it appears that I am logged out as it reports `Anonymous User`.  Because of the other conda bug of having excessive DEBUG and INFO output appearing (even when I haven't asked for it) I can now see that `anaconda-client` has noticed the expired/borked auth token, but that is only mentioned in the DEBUG output.

Expected behavior:

1. `anaconda whoami` reports `Anonymous User` and should only do so if there is no auth token.
2. `conda` needs to notice if it has a borked auth token and not feed garbage to the repository.
3. Anaconda Repository should not care about auth tokens for read-operations if the channel is world-readable

```bash
0097-ijstokes:~ ijstokes$ conda update conda
Fetching package metadata ...
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/anaconda-fusion/osx-64/repodata.json>
Elapsed: 00:00.427186
CF-RAY: 36180786de692a91-SEA

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) remove the invalid token from your system with `anaconda logout`, optionally
      followed by collecting a new token with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.


0097-ijstokes:~ ijstokes$ anaconda whoami
Using Anaconda API: https://api.anaconda.org
DEBUG binstar:load_token(162): Found login token: /Users/ijstokes/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
DEBUG binstar.whoami:main(18): ('Authorization token is no longer valid', 401)
Anonymous User
INFO binstar.whoami:main(19): Anonymous User

0097-ijstokes:~ ijstokes$ anaconda logout
Using Anaconda API: https://api.anaconda.org
DEBUG binstar:load_token(162): Found login token: /Users/ijstokes/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
DEBUG binstar.logout:main(22): The token that you are trying to remove may not be valid('Authorization token is no longer valid', 401)
logout successful
INFO binstar.logout:main(25): logout successful

0097-ijstokes:~ ijstokes$ conda update conda
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/ijstokes/anaconda:
#
conda                     4.3.18                   py36_0  

0097-ijstokes:~ ijstokes$ anaconda whoami
Using Anaconda API: https://api.anaconda.org
DEBUG binstar.whoami:main(18): ('Authorization header was not given', 401)
Anonymous User
INFO binstar.whoami:main(19): Anonymous User
```

**Comment by kalefranz** [comment]
@ijstokes From my current understanding, conda is behaving exactly as expected here.  The only conda-related part of your request here is

> 2. conda needs to notice if it has a borked auth token and not feed garbage to the repository.

which is, I think, technically impossible.  I think what you really want out of all of this is

> 3. Anaconda Repository should not care about auth tokens for read-operations if the channel is world-readable

Since this is a feature request for Anaconda Repository, moving the ticket to https://github.com/Anaconda-Platform/support/issues.

**Comment by kalefranz** [comment]
This issue was moved to Anaconda-Platform/support#111

**Comment by kalefranz** [comment]
FWIW, https://github.com/conda/conda/pull/3758 was open for quite a while, requesting help from the anaconda-client team on any improvements needed for conda.  There was never any feedback though, so I closed it, assuming we were pretty much ok.

If we can get some input from someone on the anaconda-client team, I'm happy to work that back in.

**Comment by goanpeca** [comment]
@abarto @j0hn
