### ISSUE TITLE
Better error message if dependencies are incompatible

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5387]
_From @bilderbuchi on November 24, 2015 10:9_

Recently, I tried to install pylint (#543), and I got this error message:

```
Z:\>conda install pylint
Fetching package metadata: ....
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - pylint
  - python 3.5*

Use 'conda info pylint' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
```

Pylint conflicts with python 3.5? Interesting, because running `conda info pylint` as the error message suggested yields (among a load of others) one section involving py35:

```
pylint 1.4.2 py35_0
-------------------
file name   : pylint-1.4.2-py35_0.tar.bz2
name        : pylint
version     : 1.4.2
build number: 0
build string: py35_0
channel     : defaults
size        : 246 KB
date        : 2015-10-31
license     : GPL
license_family: GPL2
md5         : 39b28ee413f6960a1dc1d89c12e48638
installed environments:
dependencies:
    astroid 1.3.4
    python 3.5*
```

so, it seems pylint conflicts with its own dependency (while at the same time offering a version for py35)?!?

Some helpful hints reveal that it's a _dependency_  of pylint that fails here (in this case: logilab-common did not have a py35 version out yet), but the error message does not in any way imply that that could be the cause - the user has to manually climb down the dependency tree to find out (easy with pylint, as it was only 2 steps, but this could be pretty involved, especially with a branching dependency tree). 

It would be great if the error message would be more expressive about the fact that a dependency is incompatible, not the package-to-install itself.

_Copied from original issue: ContinuumIO/anaconda-issues#556_

**Comment by shoemakerdr** [comment]
Want to throw a +1 on this one. Dealing with some pretty bad conflicts from local conda-build packages. It would help if there was more info from conda about which dependencies from which packages are in conflict. From the looks of `conda search` output, I can't tell where the actual conflict is. If the output is too large, maybe have conda pipe more verbose conflict information into a file (maybe `<cmd>.conflict`?).

**Comment by bilderbuchi** [comment]
Hi @github-actions. Why do you want us to reproduce using "Conda 2" - the current version is conda 4, already. ;-)

**Comment by bilderbuchi** [comment]
In any case, I think this has improved in the meantime. I can't quickly locate a conflict in a transitive dependency, but at least for direct conflicts, the output is much more useful nowadays:
```
conda create -n foo pylint=2.9.6 astroid=2.5
...
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package astroid conflicts for:
astroid=2.5
pylint=2.9.6 -> astroid[version='>=2.6.5,<2.7']
```
so I think this can be closed.
