### ISSUE TITLE
Purpose of .continuum directory

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5389]
I'm trying to understand the purpose of the `.continuum` directory. Is this something that is still needed for some purpose? If so, what is it? Also, assuming it is needed, is there a way to relocate this out of the home directory to somewhere else (perhaps `conda`'s install location)? Thanks.

**Comment by kalefranz** [comment]
Conda does not use a `.continuum` directory at all.  To my knowledge, it never has.  Other Continuum-developed software does.  Asking on the anaconda-client tracker might be the next place to go for you...

https://github.com/Anaconda-Platform/support/issues

**Comment by jakirkham** [comment]
This issue was moved to Anaconda-Platform/support#113
