### ISSUE TITLE
zsh support

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5395]
_From @briantrice on July 9, 2014 17:16_

One trivial change would be to support ~/.zprofile in addition to ~/.bash_profile with the same environment change to the PATH.

A more interesting change would be an autocomplete plugin (see also: a pony).

_Copied from original issue: ContinuumIO/anaconda-issues#142_

**Comment by nehaljwani** [comment]
_From @asmeurer on July 28, 2014 17:0_

Re autocomplete, if [argcomplete](https://github.com/kislyuk/argcomplete) works with zsh, conda already uses that. If not, I would bug them to add zsh support.

**Comment by kalefranz** [comment]
Conda 4.4 supports zsh. And all other posix-compliant shells.
