### ISSUE TITLE
Environment Deactivation - Misleading Message?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5400]
When I try to create an environment, I get the following message:

```bash
(root) [xyz@unknown ~]$ conda create -yn anacondacon
Fetching package metadata .........
Solving package specifications:
Package plan for installation in environment /conda/envs/anacondacon:

#
# To activate this environment, use:
# > source activate anacondacon
#
# To deactivate this environment, use:
# > source deactivate anacondacon
#
```
The command displayed to deactivate the environment suggests that the name of the environment is an argument to deactivate. But, is it really? I only have to do `source deactivate`, right?

**Comment by kalefranz** [comment]
BTW this message gets to change to `conda activate` and `conda deactivate` in conda 4.4.  But at least it's fixed in conda 4.3 now.
