### ISSUE TITLE
[Help] <pip> to py2.7

### ISSUE THREAD

**Issue by biggyd** [conda/conda#5401]
**Conda Version: 4.3.1**
**Python Version: 2.7.11**
I used PyCharm 2017.1 version. Now I want to use a non-conda package called `keras`.
I used `pip install keras` to install the package and it was installed successfully. However, when I use `conda list` Its third column is somehow different from the other packages.
For example,
`cycler                    0.10.0                   py27_0  
`
is for most of the packages I have, while for `keras`, I had
`Keras                     2.0.4                     <pip>
`
Any package with the third column as `<pip>` cannot pass to my interpreter in PyCharm, and not useable. For example, the `keras` package won't show up in the package list for the conda environment I use.

What do I need to do so I can change the `Keras` show up in my IDE? Thank you so, so, so much for your help!!

**Comment by tyler-thetyrant** [comment]
I think you should uninstall pip-installed keras, and run
`conda install -c conda-forge keras`, which I believe will give you conda-compatible keras. 

Also, you should update your conda version! You can do this by running `conda update conda` command.
