### ISSUE TITLE
Untracked files on windows

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#541]
When I conda installed nose into conda, a lot (all?) of the files show up as untracked. 

![screen shot 2014-01-29 at 2 32 25 pm](https://f.cloud.github.com/assets/71486/2033993/9aeebc4a-8924-11e3-9cdd-0faa3b806d81.png)

The list goes on, and note that it also includes things from https://github.com/ContinuumIO/anaconda-issues/issues/76.

**Comment by kalefranz** [comment]
Fixed.
