### ISSUE TITLE
Feature request: ability to expose system installed files as installable conda packages

### ISSUE THREAD

**Issue by tomashek** [conda/conda#5410]
We would like the ability to be able to "install" system files into a conda-based python environment.

Specifically, Parallel Studio has large sets of libraries that can be used with python (MKL, DAAL, TBB, etc.). We would like the ability to expose these to a conda-based python environment so a user could "conda install" the libraries *without copying them*. Because they are, combined, hundreds of MB, the solution must avoid creating copies (where possible).

Requirements:
- The local library packages look like regular conda packages so they can satisfy requirements of other conda packages (such as numpy requiring MKL) and behave in a consistent manner when "install", "update" and "remove" commands are given
- The local libraries should be able to maintain their own availability. In other words, when the system installation changes, it should be able to update its availability for python users
- The local library package must be able to enforce version consistency with the software version it references

Proactive discovery of local resources by the python installation is not a requirement for our use case.

**Comment by tomashek** [comment]
Options previously discussed:

On Unix, this request can be achieved by allowing Conda packages that include absolute-path symlinks. A local package of symlinks to the system installation can be created and made available in a local file conda channel. I don't believe this solution is possible on Windows.

On Windows and Unix, allowing conda to hard-link files from system locations instead of only the cache would appear to meet the requirements.

Another proposed option was using metapackages that would setup the environment to use specific system files without copying/linking them into the python environment. The setup would occur at environment activation.

**Comment by tomashek** [comment]
Comments welcome!

A strawman proposal: 
Each line in the info/files metadata file can be a scalar as it is now or a (src,dest) tuple. If a tuple, conda links src to dest. Soft links are preferred on unix to avoid having copies when across filesystems.

Pros: fully backward-compatible, straightforward to implement, allows mix of system files with packaged files (maybe not a pro because I have no use-case for it and don't know if it is even wise)
Cons: versioning checking is probably needed (do the files found at the location given actually match the metadata?)  Can we use cksum to check that the files referenced have not been changed from expectations?

Open questions:
How would conda-build create such a package?
- Conda-build could take command-line metadata to create the package and post it to a local channel. It could be similar to the conda metapackage command, but a file with (src,dest) also included along with a local directory in which to create (or update) the local channel. Or, there could be a new "source" key in meta.yaml that has a list of tuples that are the files. Something like:
source:
    - system:
        - src, dest
        - src2, dest2
src is a full path while dest is relative to the python env root.

**Comment by stefanseefeld** [comment]
This is an interesting proposal ! However, I think it's important to capture the desired semantics prior to thinking about possible implementations. We are trying to get away from a direct exposure of the data structures used to represent an environment (i.e., json files, dictionaries, etc.), so we can more easily change them if we have to.

**Comment by kalefranz** [comment]
info/files is maintained for backward compatibility, but deprecated for new features. Conda 4.3 uses info/paths.json if it exists. There's a conda-build issues somewhere that outlines the v1 spec for that file.

**Comment by kalefranz** [comment]
https://github.com/conda/conda-build/issues/1486

**Comment by kalefranz** [comment]
Generic absolute symlinks within conda packages might be a tough sell. It really seems to violate one of conda's code portability principals. Shadow packages however, are something we've needed for a while. Not only could they work for stuff conda will never install, but also for packages other installers (like pip) install into an environment.

**Comment by tomashek** [comment]
@kalefranz, what is your definition of a "shadow package"? Does it not include linking files into the python environment?

**Comment by tomashek** [comment]
@stefanseefeld , having clear semantics first would be great. The strawman is to help draw those out. Other than the use case and "requirements" I described, do you have other desirables? Comments on the use case I presented?

**Comment by tomashek** [comment]
@kalefranz, @stefanseefeld, I would appreciate continued work on getting this specification. We are planning new features for our 2019 Parallel Studio release over the next 6 weeks and I would really like to see a conda-enabled python with conda-build as a new component of Parallel Studio. It will not happen, though, if we can't solve the library duplication problem. So we need a plan for this in the next few weeks.
