### ISSUE TITLE
CEP-1:-Replacing-root-environment-with-default-environment

### ISSUE THREAD

**Issue by gwdgithubnom** [conda/conda#5416]
I had followed this [wiki - Replacing-root-environment-with-default-environment]( https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment), but it did not work for windows 10.

command1: conda config --set core.default_env=anaconda3

After input the command1, I just got a error about this: CondaValueError: Value error: Key 'core.default_env' is not a known primitive parameter.

**Comment by kalefranz** [comment]
The link you gave was just a proposal that was never implemented.  `conda config --set core.default_env=anaconda3` is not expected to work, and the error message shows conda is behaving as designed.
