### ISSUE TITLE
Respecting topological sorting for environment removal

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5417]
Not sure if this is implemented in newer versions of `conda`, but it would be nice if environment removal performed a topological sort and uninstalled packages based on this sorting. Namely only removing packages that are not required for anything else first. For the most part this doesn't matter, but when `pre-unlink` scripts are involved it does.

**Comment by jakirkham** [comment]
Also ran into a similar issue when doing `conda update --all` recently.

**Comment by kalefranz** [comment]
I *think* this should be done in 4.4.  I'm adding the milestone so I can confirm later.  If it's not done yet, it might get bumped past 4.4.0.  Hopefully it's already done.

**Comment by jakirkham** [comment]
That's great news! Thanks @kalefranz. 😄
