### ISSUE TITLE
What is the reason of ERROR conda.core.link:_execute_actions(337)?

### ISSUE THREAD

**Issue by gundamkeroro** [conda/conda#5432]
When I trying to import a evn to my conda, I got this:

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::openssl-1.0.2k-1'.
UnicodeDecodeError('ascii', '/Users/fengxinlin/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/usr/local/Cellar/mongodb/2.4.9/bin:/Users/fengxinlin/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/opt/ImageMagick/bin}\xc2\xa0', 236, 237, 'ordinal not in range(128)')
Attempting to roll back.

It look like a decode issue, but I have no idea how to handle it.

**Comment by rbavery** [comment]
I get the same error when attempting to conda install basemap:

`ERROR conda.core.link:_execute_actions(337): An error occurred while installing                                                                           package 'defaults::qt-5.6.2-vc9_4'.
UnicodeDecodeError('ascii', 'C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Mini                                                                          conda2\\Library\\bin;C:\\Users\\rbavery\\bin;C:\\Program Files\\Git\\mingw64\\bi                                                                          n;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\P                                                                          rogram Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Fil                                                                          es\\Git\\usr\\bin;C:\\Users\\rbavery\\bin;C:\\ProgramData\\Oracle\\Java\\javapat                                                                          h;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Fi                                                                          les (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\windows\\system32;C:                                                                          \\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\                                                                          v1.0;C:\\Program Files (x86)\\ActivIdentity\\ActivClient;C:\\Program Files\\Acti                                                                          vIdentity\\ActivClient;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program                                                                           Files\\Git\\cmd;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance                                                                           Toolkit;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda3;C:\\Users\\rba                                                                          very\\AppData\\Local\\Continuum\\Anaconda3\\Scripts;C:\\Users\\rbavery\\AppData\                                                                          \Local\\Continuum\\Anaconda3\\Library\\bin;C:\\Users\\rbavery\\AppData\\Local\\C                                                                          ontinuum\\Anaconda2;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda2\\Sc                                                                          ripts;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda2\\Library\\bin;\x9                                                                          3C;C:\\Program Files\\Git\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files                                                                          \\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common F                                                                          iles\\Microsoft Shared\\Windows Live;C:\\windows\\system32;C:\\windows;C:\\windo                                                                          ws\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Fi                                                                          les (x86)\\ActivIdentity\\ActivClient;C:\\Program Files\\ActivIdentity\\ActivCli                                                                          ent;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files\\Git\\cmd;C:                                                                          \\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit;C:\\Progra                                                                          m Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl'                                                                          , 1129, 1130, 'ordinal not in range(128)')
Attempting to roll back.


UnicodeDecodeError('ascii', 'C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Miniconda2\\Library\\bin;C:\\Users\\rbavery\\bin;C:\\Program Fil              es\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program               Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\rbavery\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\              \Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\windows\\system32;C:              \\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\ActivIdentity\\ActivClient;C:\              \Program Files\\ActivIdentity\\ActivClient;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)              \\Windows Kits\\8.1\\Windows Performance Toolkit;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda3;C:\\Users\\rbavery\\AppData\\Local              \\Continuum\\Anaconda3\\Scripts;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda3\\Library\\bin;C:\\Users\\rbavery\\AppData\\Local\\C              ontinuum\\Anaconda2;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anaconda2\\Scripts;C:\\Users\\rbavery\\AppData\\Local\\Continuum\\Anacond              a2\\Library\\bin;\x93C;C:\\Program Files\\Git\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Common Files\\Microsoft Shared\\Window              s Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C              :\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\ActivIdentity\\ActivClient;C:\\Program Files\\ActivIdentity\\ActivCli              ent;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performanc              e Toolkit;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl', 1129, 1130, 'ordinal not in range(128)              ')
`
This is how my conda is setup. I need to use python 2 32 bit:
`Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\rbavery\AppData\Local\Continuum\Miniconda2  (writable)
    default environment : C:\Users\rbavery\AppData\Local\Continuum\Miniconda2
       envs directories : C:\Users\rbavery\AppData\Local\Continuum\Miniconda2\envs
                          C:\Users\rbavery\AppData\Local\conda\conda\envs
                          C:\Users\rbavery\.conda\envs
          package cache : C:\Users\rbavery\AppData\Local\Continuum\Miniconda2\pkgs
                          C:\Users\rbavery\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : False
`

**Comment by gundamkeroro** [comment]
I guess I solved this problem somehow. I use anaconda2 yesterday and I got this issue, but when I completely removed anaconda2 and downloaded anaconda3, then re-import env file, I never got this error anymore.

**Comment by kalefranz** [comment]
@rbavery you have non-ascii characters in your PATH environment variable.  Python2 on windows just doesn't work well with non-ascii characters.

**Comment by adu013** [comment]
> `ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::qt-5.6.2-vc9_4'.

I've found the error while working with Python 3.6. I found that the python and anaconda were incompatible. Python was 32bit while anaconda was 64bit.
