### ISSUE TITLE
Trying to install Pymatlab throws an error

### ISSUE THREAD

**Issue by awa5114** [conda/conda#5434]
I am trying to install pymatlab via Anaconda prompt but getting errors

![image](https://cloud.githubusercontent.com/assets/24267968/26483193/0e4fdad8-41ec-11e7-8e92-d1400a038ca6.png)

I would like to know why this is happening and how I can fix it ? Thanks

**Comment by kalefranz** [comment]
They pymatlab package at https://anaconda.org/jmargeta/pymatlab/files is only available for python 2.7.  

    conda create -n pymatlab -c jarmeta pymatlab=0.2.3 python=2
    activate pymatlab
