### ISSUE TITLE
an unexpected error as occured while run the command "conda update conda

### ISSUE THREAD

**Issue by logamohan** [conda/conda#5437]
(root) C:\Users\mlogana1>conda update .condarc
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : c:\Anaconda3  (writable)
    default environment : c:\Anaconda3
       envs directories : c:\Anaconda3\envs
                          C:\Users\mlogana1\AppData\Local\conda\conda\envs
                          C:\Users\mlogana1\.conda\envs
          package cache : c:\Anaconda3\pkgs
                          C:\Users\mlogana1\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\mlogana1\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ c:\Anaconda3\Scripts\conda-script.py update .condarc`

    Traceback (most recent call last):
      File "c:\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "c:\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _mai
n
        exit_code = args.func(args, p)
      File "c:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, i
n execute
        install(args, parser, 'update')
      File "c:\Anaconda3\lib\site-packages\conda\cli\install.py", line 130, in i
nstall
        context.validate_configuration()
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
838, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
836, in <genexpr>
        for name in self.parameter_names)
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
829, in _collect_validation_error
        func(*args, **kwargs)
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
447, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self
.default,
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
664, in _merge
        for match in relevant_matches)
      File "c:\Anaconda3\lib\site-packages\conda\common\configuration.py", line
664, in <genexpr>
        for match in relevant_matches)
      File "c:\Anaconda3\lib\site-packages\conda\common\compat.py", line 71, in
iteritems
        return iter(d.items(**kw))
    AttributeError: 'str' object has no attribute 'items'

**Comment by kalefranz** [comment]
You have an error in your condarc file `C:\Users\mlogana1\.condarc`.  Just remove whatever is causing conda to choke in that file.

**Comment by kalefranz** [comment]
Then you also want `conda update conda`, not `conda update .condarc`.
