### ISSUE TITLE
Package pyside issues

### ISSUE THREAD

**Issue by Lobotomik** [conda/conda#5438]
My application is based on numpy+traitsui and requires pyside, enable, chaco.

For library pyside, versions 1.1.1 and 1.1.2 are available.

* Version 1.1.1 dates back to 2012-09-13. 
* Only requirements are python 2.7
* Does not work because it contains library version 1.1.1.1 but it tries to load 1.1.1 which should be there but is missing.

    import PySide.QtCore  # @UnresolvedImport
    ImportError: dlopen(/Applications/anaconda/lib/python2.7/site-packages/PySide/QtCore.so, 2): 
    Library not loaded: @loader_path/../../../libpyside-python2.7.1.1.dylib
    Referenced from: /Applications/anaconda/lib/python2.7/site-packages/PySide/QtCore.so
    Reason: image not found

* Version 1.1.2 dates back to 2013-05-04
* Dependencies include qt 4.7.4 _exactly_ which is too low for pyqt which is required by enable which is required by chaco.

I see no way to install pyside+enable+chaco. With 1.1.1 it would mesh (albeit with oldish packages), though it does not work due to the missing 1.1.1 library. With 1.1.2 the 4.7.4 requirement would need to be relaxed to better than 4.7.4.

I have made it work by duplicating the library file and editing the name to remove the extra '.1',  but to distribute the application it needs to work with the standard packages.

What can I do?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1776
