### ISSUE TITLE
update_dependencies flag applies to non-dependencies

### ISSUE THREAD

**Issue by akale2408** [conda/conda#5440]
I'm facing a problem with the update_dependencies option.

On the one hand, when running "conda install ..." I've noticed that conda tries to upgrade packages that I didn't ask it to upgrade (explicitly or implicitly). This is problematic because I don't necessarily want every installed package upgraded to the latest version every time I run "install", because my code may not be compatible w/ that version yet. The only solution for this that I know of is to set **update_dependencies = False**.

On the other hand, suppose I have version 2 of package B installed, and then I run "conda install A==10" where version 10 of package A depends on version **3** of package B. I would expect that B is at that point upgraded, and it is upgraded as long as **update_dependencies = True**.

So, it seems like I have to choose between one desired behavior or the other. 

Ideally, conda would first crawl the dependency tree for what I'm asking it to install. If a package lies outside of that tree, conda would try to keep it on the same version. If a package lies inside of that tree, conda would either keep that package on the same version (update_dependencies = False) or remove the current version from the spec (update_dependencies = True). I think the problem with the existing code is that it incorrectly assumes all installed packages to be in the dependency tree.

Here's the relevant section of code https://github.com/conda/conda/blob/master/conda/resolve.py#L682

**Comment by kalefranz** [comment]
Can you provide a couple examples that reproduce the behavior you're seeing?  Start with `conda create -n test-env` and then whatever `conda install -n test-env` commands/packages reproduce what you're seeing...

**Comment by mcg1969** [comment]
I'm not quite sure I understand what you're describing. But in fact, nominally, `conda` attempts to minimize the total number of packages that need to be upgraded in order to accomplish a given install command. Once the _number_ of updates is minimized, then conda is aggressive about updating those packages as much as possible. But if it's possible to complete your requested installation without any other upgrades, it will do so.

**Comment by akale2408** [comment]
I'm able to reproduce the problem on conda 4.2.12, but it's a complex case. I'm currently working on narrowing it down to a small test case as @kalefranz suggested.

**Comment by akale2408** [comment]
I confirmed that the issue exists on a later version of conda (4.3.21). Still trying to narrow down a test case.

**Comment by kalefranz** [comment]
Any update on a reproducible test case?  Or have we solve the problem with conda 4.4?
