### ISSUE TITLE
Miniconda python 3.6 64-bit installer not working

### ISSUE THREAD

**Issue by traugertyson** [conda/conda#5441]
It gives "ERROR: size of $THIS_FILE should be  34694134 byte".  However, when I check the file size through ls -l  (or wc -c "PATH") it gives the correct size (34694134). I am running Ubuntu 16.04.

**Comment by ilanschnell** [comment]
Which is the exact filename of the Miniconda installing you are using?  Thanks

**Comment by traugertyson** [comment]
Miniconda3-latest-Linux-x86_64.sh. On https://conda.io/miniconda.html, its the Linux 64-bit (bash installer) download.

**Comment by ilanschnell** [comment]
I don't know why you're getting the error.  I just tried this installer, and it works for me.

**Comment by ilanschnell** [comment]
The MD5 sum is `fc6fc37479e3e3fcf3f9ba52cae98991`.  How do you execute the installer?  Maybe you are using a wrong shell.  Try:
```
bash Miniconda3-latest-Linux-x86_64.sh
```
