### ISSUE TITLE
Not able to install Udacity car Simulator

### ISSUE THREAD

**Issue by heeramani** [conda/conda#5444]
(C:\Users\Heeramani\Anaconda2) C:\Users\Heeramani>conda env create -f environments.yml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\Heeramani\Anaconda2  (writable)
    default environment : C:\Users\Heeramani\Anaconda2
       envs directories : C:\Users\Heeramani\Anaconda2\envs
                          C:\Users\Heeramani\AppData\Local\conda\conda\envs
                          C:\Users\Heeramani\.conda\envs
          package cache : C:\Users\Heeramani\Anaconda2\pkgs
                          C:\Users\Heeramani\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\Users\Heeramani\Anaconda2\Scripts\conda-env-script.py create -f environments.yml`

    Traceback (most recent call last):
      File "C:\Users\Heeramani\Anaconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Heeramani\Anaconda2\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\Heeramani\Anaconda2\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: environments.yml file not found
    There is no requirements.txt

**Comment by kalefranz** [comment]
I'm guessing you meant `environment.yml` instead of `environments.yml`.  Regardless, I've created #5475 which should add even more safety here.
