### ISSUE TITLE
Zipline update: specifications were found to be in conflict - blaze and cannot find register.py or extensions.py

### ISSUE THREAD

**Issue by ikfdarba** [conda/conda#5450]
Hello,
I am not an expert of anaconda by any means and running into trouble in updating zipline and finding the extensions.py file 

I am trying to write my own data bundle loader and have been using an example from online. 

First I am using Zipline 1.0.2 but am having some issues updating to 1.1.0 through conda:

When running: `conda install -y -c quantopian zipline=1.1.0` i am getting the following message:

UnsatisfiableError: The following specifications were found to be in conflict:
- blaze
- zipline1.1.0* -> cython>=0.22.1

however i have:
blaze 0.10.1
cython 0.25.2

im not sure what to do here...

Second in the zipline 1.0.2 i cannot seem to register the ingest function i coded because 

1) there is no extension.py (or extensions.py not sure which one it should be) file in the zipline directory which i am supposed to register the ingest function in. 
2) There is moreover no register.py function either (nowhere, neither in data/bundles/ nor in data nor in root)

So i would not even know how to run the 'yahoo-equities' example given in the zipline.io
Ingesting quandl and quantopian-quandl both seem to work however. 

I alos tried to check in the tar file i downloaded from online zipline-1.1.0.tar, and here i also cannot find the extension.py file...

Thank you for your help,

**Comment by kalefranz** [comment]
Looks like it's only available for python 2.7 and 3.4.  https://anaconda.org/Quantopian/zipline/files?channel=main  so that might be part of your problem.

Just use a conda environment.

    conda create -y -c quantopian zipline=1.1.0 python=3.4 -n zipline-env
    source activate zipline-env

or

    activate zipline-env

if you're on Windows.

For the second problem, this issue tracker can't really help you.  You'll have to ask elsewhere for getting more into the specifics of any application or library code.  Conda just installs it for you.

**Comment by ikfdarba** [comment]
Hello,

thanks for the answer, however I am already using a python 3.4 environment.
