### ISSUE TITLE
conda clean --json error

### ISSUE THREAD

**Issue by wsfax** [conda/conda#5451]
`conda clean -t --json --dry-run
{
  "error": "Traceback (most recent call last):\n  File \"C:\\Anaconda27\\lib\\site-packages\\conda\\exceptions.py\", line 632, in conda_exception_handler\n    return_value = func(*args, **kwargs)\n  File \"C:\\Anaconda27\\lib\\site-packages\\conda\\cli\\main.py\", line 137, in _main\n    exit_code = args.func(args, p)\n  File \"C:\\Anaconda27\\lib\\site-packages\\conda\\cli\\main_clean.py\", line 306, in execute\n    rm_tarballs(args, pkgs_dirs, totalsize, verbose=not context.json)\n  File \"C:\\Anaconda27\\lib\\site-packages\\conda\\cli\\main_clean.py\", line 123, in rm_tarballs\n    if not context.json or not context.yes:\nAttributeError: 'Context' object has no attribute 'yes'\n"
}

conda info --all
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.1.15
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda27  (writable)
    default environment : C:\Anaconda27
       envs directories : C:\Anaconda27\envs
                          C:\Users\Oammous\AppData\Local\conda\conda\envs
                          C:\Users\Oammous\.conda\envs
          package cache : C:\Anaconda27\pkgs
                          C:\Users\Oammous\AppData\Local\conda\conda\pkgs
           channel URLs : http://conda/prod/win-64
                          http://conda/prod/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : C:\Users\Oammous\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.10586
          administrator : False
# conda environments:
#
_test                    C:\Anaconda27\envs\_test
gulbis                   C:\Anaconda27\envs\gulbis
py3                      C:\Anaconda27\envs\py3
root                  *  C:\Anaconda27

sys.version: 2.7.13 |Anaconda custom (64-bit)| (defau...
sys.prefix: C:\Anaconda27
sys.executable: C:\Anaconda27\python.exe
conda location: C:\Anaconda27\lib\site-packages\conda
conda-build: C:\Anaconda27\Scripts\conda-build.exe
conda-convert: C:\Anaconda27\Scripts\conda-convert.exe
conda-develop: C:\Anaconda27\Scripts\conda-develop.exe
conda-env: C:\Anaconda27\Scripts\conda-env.exe
conda-index: C:\Anaconda27\Scripts\conda-index.exe
conda-inspect: C:\Anaconda27\Scripts\conda-inspect.exe
conda-metapackage: C:\Anaconda27\Scripts\conda-metapackage.exe
conda-render: C:\Anaconda27\Scripts\conda-render.exe
conda-server: C:\Anaconda27\Scripts\conda-server.exe
conda-sign: C:\Anaconda27\Scripts\conda-sign.exe
conda-skeleton: C:\Anaconda27\Scripts\conda-skeleton.exe
conda-verify: C:\Anaconda27\Scripts\conda-verify.exe
`

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda/pull/5452
