### ISSUE TITLE
crash on conda --info envs

### ISSUE THREAD

**Issue by daemon515** [conda/conda#5458]
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\local_name\AppData\Local\Continuum\Anaconda3  (wri
table)
    default environment : C:\Users\local_name\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\local_name\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\local_name\AppData\Local\conda\conda\envs
                          C:\Users\local_name\.conda\envs
          package cache : C:\Users\local_name\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\local_name\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ C:\Users\local_name\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py --in
fo envs`

    Traceback (most recent call last):
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1762, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1971, in _parse_known_args
        stop_index = consume_positionals(start_index)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1927, in consume_positionals
        take_action(action, args)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1820, in take_action
        argument_values = self._get_values(action, argument_strings)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 2271, in _get_values
        self._check_value(action, value[0])
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 2314, in _check_value
        raise ArgumentError(action, msg % args)
    argparse.ArgumentError: argument command: invalid choice: 'envs' (choose fro
m 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'r
emove', 'uninstall', 'config', 'clean', 'package')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\main.py", line 119, in _main
        args = p.parse_args(args)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1730, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\argparse.py", l
ine 1769, in parse_known_args
        self.error(str(err))
      File "C:\Users\local_name\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by daemon515** [comment]
Initally tried to create a new environment using:
conda create --name env_name python=2.7 numpy pandas matplotlib
This command did not complete and had to terminate using ctrl+c. This is the log at time of conda create

The following NEW packages will be INSTALLED:

    cycler:          0.10.0-py27_0
    functools32:     3.2.3.2-py27_0
    icu:             57.1-vc9_0         [vc9]
    jpeg:            9b-vc9_0           [vc9]
    libpng:          1.6.27-vc9_0       [vc9]
    matplotlib:      2.0.2-np112py27_0
    mkl:             2017.0.1-0
    numpy:           1.12.1-py27_0
    openssl:         1.0.2l-vc9_0       [vc9]
    pandas:          0.20.1-np112py27_0
    pip:             9.0.1-py27_1
    pyparsing:       2.1.4-py27_0
    pyqt:            5.6.0-py27_2
    python:          2.7.13-1
    python-dateutil: 2.6.0-py27_0
    pytz:            2017.2-py27_0
    qt:              5.6.2-vc9_4        [vc9]
    setuptools:      27.2.0-py27_1
    sip:             4.18-py27_0
    six:             1.10.0-py27_0
    subprocess32:    3.2.7-py27_0
    tk:              8.5.18-vc9_0       [vc9]
    vs2008_runtime:  9.00.30729.5054-0
    wheel:           0.29.0-py27_0
    zlib:            1.2.8-vc9_3        [vc9]

Proceed ([y]/n)? y

mkl-2017.0.1-0 100% |###############################| Time: 0:00:18   7.25 MB/s
vs2008_runtime 100% |###############################| Time: 0:00:00   3.81 MB/s
icu-57.1-vc9_0 100% |###############################| Time: 0:00:05   6.26 MB/s
jpeg-9b-vc9_0. 100% |###############################| Time: 0:00:00   5.34 MB/s
openssl-1.0.2l 100% |###############################| Time: 0:00:00   6.38 MB/s
python-2.7.13- 100% |###############################| Time: 0:00:04   5.75 MB/s
tk-8.5.18-vc9_ 100% |###############################| Time: 0:00:00   5.21 MB/s
zlib-1.2.8-vc9 100% |###############################| Time: 0:00:00   5.05 MB/s
functools32-3. 100% |###############################| Time: 0:00:00   1.18 MB/s
libpng-1.6.27- 100% |###############################| Time: 0:00:00   5.90 MB/s
numpy-1.12.1-p 100% |###############################| Time: 0:00:00   6.60 MB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00   2.31 MB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00   6.64 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   7.23 MB/s
sip-4.18-py27_ 100% |###############################| Time: 0:00:00   6.81 MB/s
six-1.10.0-py2 100% |###############################| Time: 0:00:00   1.20 MB/s
subprocess32-3 100% |###############################| Time: 0:00:00   1.35 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   3.89 MB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00 826.12 kB/s
pip-9.0.1-py27 100% |###############################| Time: 0:00:00   5.60 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   5.53 MB/s
qt-5.6.2-vc9_4 100% |###############################| Time: 0:00:08   6.54 MB/s
pandas-0.20.1- 100% |###############################| Time: 0:00:01   8.02 MB/s
pyqt-5.6.0-py2 100% |###############################| Time: 0:00:00   7.21 MB/s
matplotlib-2.0 100% |###############################| Time: 0:00:01   6.95 MB/s
--> ctrl+c here as it was taking too long
ERROR conda.core.link:_execute_actions(335): An error occurred while installing
package 'defaults::qt-5.6.2-vc9_4'.
CondaSignalInterrupt: Signal interrupt SIGINT

Attempting to roll back.



CondaSignalInterrupt: Signal interrupt SIGINT

**Comment by kalefranz** [comment]
Already fixed in a more recent version of conda.  Latest is 4.3.21.  `conda update conda`.
