### ISSUE TITLE
custom subdir installation not working

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5459]
I have a package that sets subdir to osx_1012-x86_64 - https://anaconda.org/msarahan/clang_osx-1012-x86_64

If I try to create a dummy environment with this package, I end up with PackageNotFound:

```
CONDA_SUBDIR=osx-1012-x84_64 conda create -n weee clang_osx-1012-x86_64 -c msarahan
Fetching package metadata .............
Solving package specifications:

PackageNotFoundError: Package missing in current osx-1012-x84_64 channels:
  - clang_osx-1012-x86_64
```

I think I'm setting subdir correctly here, but please correct me if I'm not.  Tested on current 4.3.x branch and 4.4.x branch.

cc @mandeep

**Comment by kalefranz** [comment]
I think it might be a bug with anaconda.org?  The packages should be listed in https://conda.anaconda.org/msarahan/osx-1012-x84_64/repodata.json, but there's nothing there.

**Comment by kalefranz** [comment]
I don't see any problem with the command as you've given

    CONDA_SUBDIR=osx-1012-x84_64 conda create -n weee clang_osx-1012-x86_64 -c msarahan

You could also do

    CONDA_SUBDIR=osx-1012-x84_64 conda info

to verify the subdir in the channel urls.

I'm guessing that CONDA_SUBDIR works just fine when using from a local channel?

**Comment by msarahan** [comment]
no, CONDA_SUBDIR fails in the same way with the local channel - it was just easier for me to give you a reproducer from anaconda.org.  Interesting observation about repodata.json.  That does seem like an anaconda.org bug.

Locally, though, conda index gives me this:

```
{
  "info": {},
  "packages": {
    "clangxx_osx-1012-x86_64-10.12-h0bb54af_0.tar.bz2": {
      "build": "h0bb54af_0",
      "build_number": 0,
      "depends": [],
      "md5": "998fa5470c17bf567cdf1559cb362013",
      "name": "clangxx_osx-1012-x86_64",
      "sha256": "633cf9f01771df7860d00e3107fa6534a43779d0f53ef4294196c0137aea8235",
      "sig": null,
      "size": 2383,
      "subdir": "osx-1012-x86_64",
      "timestamp": 1496261580770,
      "version": "10.12"
    }
  }
}
```

for index.json contents:

```
{
  "arch": "1012-x86_64",
  "build": "h0bb54af_0",
  "build_number": 0,
  "depends": [],
  "name": "clangxx_osx-1012-x86_64",
  "platform": "osx",
  "subdir": "osx-1012-x86_64",
  "timestamp": 1496261580770,
  "version": "10.12"
}
```

that all seems sane, aside from the arch.  Platform really should be osx-1012, and arch should be x86_64.

**Comment by kalefranz** [comment]
Ok I believe you now that it's a bug.  I'll use that package, make a local channel, then try to figure out what's going on.  My guess is that it has something to do with channel parsing.

A test I'm thinking of to demonstrate what's going on...

```python
with env_var('CONDA_SUBDIR', 'osx-1012-x86_64'):
    channel = Channel('https://conda.anaconda.org/msarahan/osx-1012-x84_64/clangxx_osx-1012-x86_64-10.12-h0bb54af_0.tar.bz2')
    assert channel.base_url == 'https://conda.anaconda.org/msarahan/osx-1012-x84_64'
    assert channel.package_filename == 'clangxx_osx-1012-x86_64-10.12-h0bb54af_0.tar.bz2'
    assert channel.platform == 'osx-1012-x84_64'  # the platform attribute is misnamed here in conda 4.3; conda 4.4 code can correctly use the channel.subdir attribute
```

**Comment by msarahan** [comment]
That might work.  Not sure if it helps, but I also found that in conda-build the package is found by the Resolve object, but seemingly can't be found when getting install actions - maybe get_reduced_index is reducing too much?

```
Traceback (most recent call last):
  File "/Users/msarahan/code/conda-build/conda_build/environ.py", line 667, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/Users/msarahan/code/conda/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/Users/msarahan/code/conda/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/Users/msarahan/code/conda/conda/resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/Users/msarahan/code/conda/conda/resolve.py", line 850, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/Users/msarahan/code/conda/conda/resolve.py", line 376, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/Users/msarahan/code/conda/conda/resolve.py", line 302, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Packages missing in current osx-1012-x86_64 channels:
  - clang_osx-1012-x86_64
  - clangxx_osx-1012-x86_64
  - pkg-config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/msarahan/miniconda3/bin/conda-build", line 11, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "/Users/msarahan/code/conda-build/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/Users/msarahan/code/conda-build/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/Users/msarahan/code/conda-build/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/msarahan/code/conda-build/conda_build/build.py", line 1499, in build_tree
    built_packages=built_packages,
  File "/Users/msarahan/code/conda-build/conda_build/build.py", line 891, in build
    timestamp=index_timestamp)
  File "/Users/msarahan/code/conda-build/conda_build/environ.py", line 673, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Packages missing in current osx-1012-x86_64 channels:
  - clang_osx-1012-x86_64
  - clangxx_osx-1012-x86_64
  - pkg-config
```

**Comment by kalefranz** [comment]
Worked with @mandeep to figure out what's going on.  While #5478 is a good bug fix, the cause of the problem here is in conda-build.  CB calls conda's `get_index()` twice (should only need to call it once), the first time specifying the correct subdir (`osx-1012-x84_64`), the second time specifying an incorrect subdir (`osx-x84_64`) that appears to be related to platform-arch string parsing of `-` and then reconstruction to subdir.

It possible that it's conda's `context.arch_name` and `context.platform` that are parsing these incorrectly and then passing them through to conda-build.  However, it's not clear what the general rule should be for parsing subdir with multiple dashes, and we kill any parts of the code that are actually relying on that parsing.  Subdir should just be subdir.

**Comment by msarahan** [comment]
Thanks.  Good find.  I agree with you on parsing subdir being fragile, but what would the alternative here be?

```
CONDA_PLATFORM=osx-1012 CONDA_ARCH=x86_64 conda build ...
```

That's easy enough, I just want to make sure that both conda-build and conda will work that way.  I think conda *should* right now, but I have less faith in conda-build.

**Comment by kalefranz** [comment]
In most cases where the logic matters, I think conda treats subdir as its own, independent thing at this point.  Not relying on translation back and forth between platform+arch <=> subdir.  That might not be possible for conda-build, but I don't think there's any reason conda has to dig any deeper into subdir and try to infer something that might not always be safe.

**Comment by kalefranz** [comment]
xref https://github.com/conda/conda-build/pull/2066

**Comment by kalefranz** [comment]
If it ever is needed, I'm fine with the rule

    platform, arch = subdir.rsplit('-', 1)
