### ISSUE TITLE
Support proxy_servers in conda config

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#546]
proxy_servers is not support in conda config because it's a dictionary, but it currently only supports list or boolean keys.

**Comment by jasongrout** [comment]
@asmeurer - it seems like this works now, right?

**Comment by jasongrout** [comment]
Oh, never mind.  I see what you're saying.  You can't set proxy servers from the `conda config` command line script.

**Comment by kalefranz** [comment]
Duplicate of #4302
