### ISSUE TITLE
Resolution fails for packages with hyphens that share a prefix

### ISSUE THREAD

**Issue by gatesn** [conda/conda#5462]
For example (though I cannot find any public packages that hit this case):

`conda create -n testenv package-other package` will only install `package-other`.

**Comment by kalefranz** [comment]
That seems pretty odd, and the first I've heard of an error like this.  Apparently this is for private packages you're building yourself?  Perhaps there's something wrong with the packages?

If you could reproduce this with something that's available in `defaults` or on anaconda.org, then we can write a regression test and get the issue resolved.

**Comment by gatesn** [comment]
Yes I've been struggling to reproduce this. Will dig into the packages and see what's going on.

Feel free to close this out for now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mbargull** [comment]
@gatesn did you use a conda version lower than 4.3.17? The issue sound similar to #4849 and #5161 which are fixed in 4.3.17 (and sometimes couldn't be reproduced reliably in prior versions).
