### ISSUE TITLE
conda cannot remove readline from the root environment

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5479]
https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/conda/Xfr3Ev1Q6b8/YwAhJDN5CgAJ

> I just noticed that I can't pull readline from a conda distribution by the usual means.   I now get:
> 
> ./miniconda/bin/conda remove readline
> Fetching package metadata: ....
> Solving package specifications: .........
> Error: this 'remove' command cannot be executed because it
> would require removing 'conda' dependencies.
> gmake: *** [all] Error 1
> 
> Since the readline library is GPL'd - it's a non-starter for commercial applications.   Conda really has to gracefully support cutting it away.

**Comment by kalefranz** [comment]
I've just confirmed that using the `--force` flag works as expected to remove readline.

```
$ /conda/bin/python -m conda remove --dry-run readline --force
Fetching package metadata .........

Package plan for package removal in environment /conda:

The following packages will be REMOVED:

    readline: 6.2-2
```

So conda is working as expected right now.

**Comment by mingwandroid** [comment]
I wonder if we need to do better here though, from a Distribution perspective? Doing that will result in an inability to `import readline`.

**Comment by kalefranz** [comment]
Oh I definitely agree that we need to do better.  The issue is closed as far as conda not being able to remove readline--it can.  @teoliphant in particular is still considering options on what should be our longer-term strategy w.r.t. readline.
