### ISSUE TITLE
add ability to run pre-link script

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#548]
A script named `.<name>-pre-link.sh` would need to be run from the extracted location in the `pkgs` directory, because it is not linked yet, and an error should stop conda.

**Comment by kalefranz** [comment]
@ilanschnell Can you give me the history of why this issue was created and implemented?

**Comment by ilanschnell** [comment]
Yes, the idea was that a conda package could perform some checks in order to see if installing the package is even useful.  If the check fails, conda would fail.  No packages (which I ever made, i.e. in `repo.continuum.io`) use this feature, but a colleague working for one of our customers (in New York) requested this feature.  I have no idea if the feature is still being used.
