### ISSUE TITLE
centso6.5  yum install error

### ISSUE THREAD

**Issue by huty323** [conda/conda#5481]
[root@master ~]# yum groupinstall "X Window System"
Loaded plugins: fastestmirror, security
Determining fastest mirrors
Could not retrieve mirrorlist http://apt.sw.be/redhat/el6/en/mirrors-rpmforge error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'apt.sw.be'"
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. </html>/
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
base                                                                               | 3.7 kB     00:00     
http://mirrors.aliyun.com/centos/6/os/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for base: Damaged repomd.xml file
Trying other mirror.
http://mirrors.aliyuncs.com/centos/6/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.aliyuncs.com/centos/6/os/x86_64/repodata/repomd.xml: (28, 'connect() timed out!')
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again

**Comment by nehaljwani** [comment]
Closing, as this issue doesn't seem to be related to conda.
