### ISSUE TITLE
CondaHTTPError when attempting to install packages from any and all channels

### ISSUE THREAD

**Issue by IndyMark** [conda/conda#5497]
Normal conda installs without the -c work fine.  However, whenever I attempt to specify ANY channel, I get this error:

conda install -c rdkit rdkit=2017.03.2
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/rdkit/linux-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /rdkit/linux-64/repodata.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Read timed out. (read timeout=9.15)",))',),)

**Comment by IndyMark** [comment]
conda info output:

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.14.2
       root environment : /share/apps/CentOS_6.4/anaconda/r-2.3.0  (writable)
    default environment : /share/apps/CentOS_6.4/anaconda/r-2.3.0
       envs directories : /share/apps/CentOS_6.4/anaconda/r-2.3.0/envs
                          /root/.conda/envs
          package cache : /share/apps/CentOS_6.4/anaconda/r-2.3.0/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.11 Linux/2.6.32-696.1.1.el6.x86_64 CentOS/6.9 glibc/2.12
                UID:GID : 0:0

**Comment by IndyMark** [comment]
Digging into this is little more and I suspect an SSL certificate error of some sort.  Just last week we did a yum update on this server and updated to CentOS 6.9, and I wonder if that could be related somehow.  

Totally outside of anaconda, I attempted to connect to the following sites:
http://www.google.com = OK
https://www.google.com = OK
https://www.anaconda.org = Unable to retrieve https://www.anaconda.org/:  SSL error

**Comment by kalefranz** [comment]
The cert on www.anaconda.org looks good to me:
   https://www.ssllabs.com/ssltest/analyze.html?d=www.anaconda.org&s=52.201.88.26&latest

Although I'm seeing there that the only supported protocol is TLS 1.2.  Maybe that's what's causing problems?

Conda itself never connects to www.anaconda.org, but instead conda.anaconda.org.  The cert there is issued by Cloudflare.
   https://www.ssllabs.com/ssltest/analyze.html?d=conda.anaconda.org&s=104.16.5.213&latest

Can you confirm that you're able to connect to repo.continuum.io?  That is to say, if you don't include the `-c rdkit` flag, but just try say, `conda update conda`, do you have  problems in that case?

**Comment by IndyMark** [comment]
I can access https://repo.continuum.io without issues and conda update conda does indeed work.  In fact, that's the first thing I tried while troubleshooting this issue.

Attempting to connect to conda.anaconda.org looks like it redirects to anaconda.org, and I get the same SSL error.

**Comment by IndyMark** [comment]
More Googling had me try openssl commands like these:

[root@harvest03 ~]# openssl s_client -connect google.com:443
This command spits back a ton of certificate info like you'd suspect

[root@harvest03 ~]# openssl s_client -connect conda.anaconda.org:443
CONNECTED(00000003)

This command spits out the CONNECTED line and then hangs indefinitely.

**Comment by kalefranz** [comment]
I have more practice looking at curl than I do with openssl.  What do you get for `curl -vI https://conda.anaconda.org`

```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.3.213...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.3.213) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: ssl383846.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 302 FOUND
HTTP/1.1 302 FOUND
< Date: Tue, 06 Jun 2017 19:59:28 GMT
Date: Tue, 06 Jun 2017 19:59:28 GMT
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=dd6a81f474bba0b787633c1c031c507331496779168; expires=Wed, 06-Jun-18 19:59:28 GMT; path=/; domain=.anaconda.org; HttpOnly
Set-Cookie: __cfduid=dd6a81f474bba0b787633c1c031c507331496779168; expires=Wed, 06-Jun-18 19:59:28 GMT; path=/; domain=.anaconda.org; HttpOnly
< Location: https://anaconda.org/
Location: https://anaconda.org/
< Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000
< Server: cloudflare-nginx
Server: cloudflare-nginx
< CF-RAY: 36adf3cbfd10582b-DFW
CF-RAY: 36adf3cbfd10582b-DFW

<
* Curl_http_done: called premature == 0
* Connection #0 to host conda.anaconda.org left intact
```

**Comment by IndyMark** [comment]
[root@harvest03 ~]# curl -Iv https://conda.anaconda.org
* About to connect() to conda.anaconda.org port 443 (#0)
*   Trying 104.16.1.213... Timeout
*   Trying 104.16.3.213... Timeout
*   Trying 104.16.2.213... Timeout
*   Trying 104.16.5.213... ^C
[root@harvest03 ~]#

Of course it works fine for https://repo.continuum.io

[root@harvest03 ~]# curl -Iv https://repo.continuum.io
* About to connect() to repo.continuum.io port 443 (#0)
*   Trying 104.16.19.10... connected
* Connected to repo.continuum.io (104.16.19.10) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=repo.continuum.io,OU=Information Technology,O=Continuum Analytics Inc,L=Austin,ST=Texas,C=US
*       start date: Mar 04 00:00:00 2015 GMT
*       expire date: Mar 03 23:59:59 2018 GMT
*       common name: repo.continuum.io
*       issuer: CN=thawte SSL CA - G2,O="thawte, Inc.",C=US
> HEAD / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: repo.continuum.io
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Tue, 06 Jun 2017 20:09:23 GMT
Date: Tue, 06 Jun 2017 20:09:23 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 871
Content-Length: 871
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=de3670107c7a32b8bb0b30203f1a0837d1496779763; expires=Wed, 06-Jun-18 20:09:23 GMT; path=/; domain=.continuum.io; HttpOnly
Set-Cookie: __cfduid=de3670107c7a32b8bb0b30203f1a0837d1496779763; expires=Wed, 06-Jun-18 20:09:23 GMT; path=/; domain=.continuum.io; HttpOnly
< x-amz-id-2: PAP2o8/EFVdjv9id+/OVjcGemD8mTmlEqbyvAhFZe9ExSySYQezTQqkYjMYj6+qILpZt+sk6lcs=
x-amz-id-2: PAP2o8/EFVdjv9id+/OVjcGemD8mTmlEqbyvAhFZe9ExSySYQezTQqkYjMYj6+qILpZt+sk6lcs=
< x-amz-request-id: 2A77FD52C964F75F
x-amz-request-id: 2A77FD52C964F75F
< Last-Modified: Thu, 23 Mar 2017 17:49:33 GMT
Last-Modified: Thu, 23 Mar 2017 17:49:33 GMT
< x-amz-version-id: QHfyEynachFPeKAMq1h6ojgJWBTr5yB_
x-amz-version-id: QHfyEynachFPeKAMq1h6ojgJWBTr5yB_
< ETag: "82b8c3e1a1354ee46b91d898c39e6c93"
ETag: "82b8c3e1a1354ee46b91d898c39e6c93"
< CF-Cache-Status: HIT
CF-Cache-Status: HIT
< Expires: Tue, 06 Jun 2017 20:09:53 GMT
Expires: Tue, 06 Jun 2017 20:09:53 GMT
< Cache-Control: public, max-age=30
Cache-Control: public, max-age=30
< Server: cloudflare-nginx
Server: cloudflare-nginx
< CF-RAY: 36ae02515c8756e7-IAD
CF-RAY: 36ae02515c8756e7-IAD

<
* Connection #0 to host repo.continuum.io left intact
* Closing connection #0
[root@harvest03 ~]#

**Comment by IndyMark** [comment]
Tried the curl command again this morning and it got a little farther but it's still hanging:

[u365412@harvest03 ~]$ curl -Iv https://conda.anaconda.org
* About to connect() to conda.anaconda.org port 443 (#0)
*   Trying 104.16.2.213... connected
* Connected to conda.anaconda.org (104.16.2.213) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
[hangs here]

BTW, I tried this on a fully updated CentOS 7 box in my office and the same curl command to https://conda.anaconda works from there.  I have at least verified that I can use that as a workaround for the time being since our Anaconda environment is on an NFS mount.

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```

**Comment by IndyMark** [comment]
Success!  That fixed it.  Thanks so much!

**Comment by noahwalugembe** [comment]
> Success! That fixed it. Thanks so much!

Iam trying to install 
conda install -c conda-forge pyarrow but iam geting this error 

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by stiv-yakovenko** [comment]
Right now it fails for me like this:
```
Collecting package metadata: failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
```

**Comment by msarahan** [comment]
https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors
