### ISSUE TITLE
scikit-image enexpected installation error

### ISSUE THREAD

**Issue by Tejeshwarabm** [conda/conda#5504]
scikit-image-0   8% |##########                                                                                 An unexpected error has occurred.ime: 0:03:00  15.17 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/admin1/anaconda2  (writable)
    default environment : /home/admin1/anaconda2
       envs directories : /home/admin1/anaconda2/envs
          package cache : /home/admin1/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /xx/xx/xx/anaconda2/bin/conda install -c anaconda scikit-image=0.13.0`

**Comment by tyler-thetyrant** [comment]
I've tested with a clean docker image, and the command works perfectly fine with the most recent version of conda, 4.3.21. Either `conda update conda` or reinstalling up-to-date miniconda will resolve your issue.

**Comment by Tejeshwarabm** [comment]
$ conda install -c menpo dlib=19.4
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/admin1/anaconda2:
#
dlib                      19.4                     py27_0    menpo



But the problem is "dlib" is not importing in spyder IDE...

import dlib
Traceback (most recent call last):

  File "<ipython-input-6-82a137582d6f>", line 1, in <module>
    import dlib

ImportError: No module named dlib

**Comment by tyler-thetyrant** [comment]
```
