### ISSUE TITLE
Conda install: UnsatisfiableError

### ISSUE THREAD

**Issue by nheugel** [conda/conda#5509]
I am trying to install python and MNE for work I am doing.  I was following the instructions on this page http://martinos.org/mne/stable/install_mne_python.html#install-the-mne-module

I installed anaconda 2.7 like it instructed.  When I run the test commands below, they spit back what the instructions told me I should see
`:~$ conda --version
conda 4.3.21

:~$ which python
/home/nheugel/anaconda2/bin/python

:~$ python --version
Python 2.7.13 :: Continuum Analytics, Inc.`

The issue arises when I try and run the next step
`conda install scipy matplotlib scikit-learn mayavi ipython-notebook`

I get the following error, and I do not know what it means and haven't been able to resolve it.
`UnsatisfiableError: The following specifications were found to be in conflict:
  - mayavi
  - navigator-updater -> pyqt >=5.6
  - seaborn -> matplotlib -> freetype 2.4*
  - seaborn -> matplotlib -> pyqt 5.*
  - seaborn -> matplotlib -> pyside 1.1.2 -> qt 4.7.4
Use "conda info <package>" to see the dependencies for each package`

So far I have deleted and reinstalled conda, 
run  `conda update --all`
as well as  
`conda remove anaconda --force
conda update --all`

So since I don't really know what the error is saying, and the only things I could find somewhat related to the error didn't fix it I thought I would see if anyone with more insight could help me out.  Thanks for your time.

**Comment by tyler-thetyrant** [comment]
Hmm interesting. 

I was able to reproduce this error in a clean Anaconda2/CentOS7 Docker container but was not able to reproduce this in Miniconda2/CentOS7 container. 

@nheugel I would uninstall anaconda2, and install miniconda2 ([from here](https://conda.io/miniconda.html)) then run the command. 

@mcg1969 @kalefranz  Any idea why?

**Comment by nehaljwani** [comment]
Setting up Miniconda2 is not really necessary. OP can just do the following:

```bash
conda create -yn py27 scipy matplotlib scikit-learn mayavi ipython-notebook
source activate py27
```
