### ISSUE TITLE
Package cache stomped over when using CONDA_SUBDIR

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#5510]
Based on the comments by Kale here:

https://github.com/conda/conda/issues/2014#issuecomment-300604221

You should be able to use the CONDA_SUBDIR environment variable to create 32-bit conda environments inside a 64-bit install. This seems to work, but has the problem that it pollutes the package cache with 32-bit packages! I tried alternating between creating 32-bit and 64-bit environments, and conda seems to be smart enough to avoid using the incorrect packages from the package cache, but since the package names don't specify bitness they get overwritten and conda has to redownload packages rather than pulling them from the cache.

CONDA_FORCE_32BIT seems to handle this better, by creating a "pkgs32" folder to cache the 32-bit packages separately. Although it sounds like that might be deprecated/removed soon. I could set CONDA_SUBDIR *and* CONDA_PKGS_DIRS when creating 32-bit environments, and unset them when creating 64-bit environments, but that seems prone to error. Are there plans to support subdir as more of a first class citizen for building packages and creating environments - e.g. allowing you to specify via the command line or in the meta.yaml/env.yaml, and keep the environments and packages separated by subdir? Or I am I better off using separate 32-bit and 64-bit coda installs?

**Comment by kalefranz** [comment]
Should be cleanly solved with https://github.com/conda/conda/pull/5937 and https://github.com/conda/conda/issues/5933
