### ISSUE TITLE
Conda doesn't seem to install all from "The following NEW packages will be INSTALLED:"

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [conda/conda#5511]
I've noticed this sequence in a couple recent projects: 

1. I create a new conda environment
2. I conda install a few packages
3. conda shows me a list of "The following NEW packages will be INSTALLED...Proceed ([y]/n)? 
4. I enter `y`
5. conda displays a very small subset of packages it installs 

(see attached screenshot for example).

Is this expected behavior? These are packages I have installed in other environments on this machine, including my default python, so perhaps it only installs new packages if it can't find them elsewhere? 

(My system info is Linux Mint 18 Sarah, 64-bit & conda version : 4.3.18, 64-bit)

![conda install packages screenshot](https://user-images.githubusercontent.com/18562882/26991164-63a2bed8-4d27-11e7-876d-645a45c18c68.png)

**Comment by kalefranz** [comment]
All the packages are being installed.  What's being shown in the screenshot is a progress bar for downloading a package that's not already in your package cache.  We've improved the UI here in conda 4.4.
