### ISSUE TITLE
ProxyError with Kerberos

### ISSUE THREAD

**Issue by jamesthurgood34** [conda/conda#5513]
## The problem

When trying to install a package with conda I get the following message.

C:\Anaconda2>conda install -c conda-forge hdbscan=0.8.10
Fetching package metadata ...

CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>

Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exce
eded with url: /conda-forge/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', e
rror('Tunnel connection failed: 407 authenticationrequired',)))",),)

## My attempt to fix it
I have created a .condarc file which includes:

- The proxy settings for both http and https
- ssl_verfiy: False

I am currently sitting behind a company firewall and do have a CA bundle but I am unsure how to tell conda that I have this.

I believe the underlying issue here is the requests package. I can not get that to work either for any site. I have managed to get pycurl to communicate with the outside world.

**Comment by vmuriart** [comment]
Have you tried creating *environment variables* on your machine?

I just checked the configuration on my machine (also behind a corp firewall), `http_proxy` and `https_proxy` *environment variables* are both set to my proxy url.

On my `.condarc` file, the only settings I see is `ssl_verify: true` though I don't remember ever changing this.

**Comment by nehaljwani** [comment]
@jamesthurgood34 Have you gone through https://conda.io/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers ? Could you try specifying the proxy credentials in the configuration too?

**Comment by samuelharmer** [comment]
@jamesthurgood34 If you have the bundle as a concatenated bundle of PEM encoded certs then you just need to run `conda config --set ssl_verify C:\path\to\cert.crt`
