### ISSUE TITLE
Unexpected error when launching anaconda prompt after windows 32bit installation

### ISSUE THREAD

**Issue by kflaw** [conda/conda#5516]
![image](https://user-images.githubusercontent.com/9289048/27048803-0d62cbc0-4f62-11e7-9532-58b5683c0620.png)

I am running python 2.7.11. Do I need to upgrade to 2.7.13?

**Comment by nehaljwani** [comment]
In the output you see `C:\Python27\...` , which indicates that you are having another installation of Python in your system. Either remove that, or remove it's location from your `PATH` and/or `PYTHONPATH` environment variables.
