### ISSUE TITLE
Start Menus disappear after first launch on Windows 10

### ISSUE THREAD

**Issue by imperialex19** [conda/conda#5519]
Installed Anaconda3-4.4.0-Windows-x86_64.exe on Win10: OK
- Launched Anaconda Navigator from Windows 10 startup menu - 1st time: OK
- Try to launch Spyder from there: NOK - silent crash of Anaconda Navigator
- Start Menus do not appear any langer.
- Tried to launch anaconda-navigator.exe - Does not start.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6792
