### ISSUE TITLE
Miniconda3 on Windows conda-forge update removes activate.bat

### ISSUE THREAD

**Issue by j08lue** [conda/conda#5522]
I installed Miniconda 3.6 on Windows 10 (64 bit) and right after ran the two commands

```
conda config --add channels conda-forge
conda update conda
```

This removed the `activate` and `deactivate` scripts from the `Miniconda3/Scripts` folder, such that the Anaconda Prompt was broken.

An interim solution was to make backups of the `activate` and `deactivate` scripts after the initial installation and copying them back into the `Scripts` folder after running updating to `conda-forge`.

But the question remains: Why do those scripts get lost?

**Comment by kalefranz** [comment]
This is a pretty old issue, with pretty old versions of conda.  I think the root cause has probably been resolved by now.
