### ISSUE TITLE
Error while using install_tensorflow (), in RStudio Windows. 

### ISSUE THREAD

**Issue by rwanjohi** [conda/conda#5527]
Traceback (most recent call last):
  File "C:\ANACON~1\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\ANACON~1\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\ANACON~1\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\ANACON~1\lib\site-packages\conda\cli\main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "C:\ANACON~1\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\ANACON~1\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\ANACON~1\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\ANACON~1\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\ANACON~1\lib\site-packages\conda\install.py", line 850, in extract
    t.extractall(path=temp_path)
  File "C:\ANACON~1\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\ANACON~1\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\ANACON~1\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\ANACON~1\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 22] invalid mode ('wb') or filename: 'C:\\ANACON~1\\pkgs\\python-3.5.3-3.tmp\\DLLs\\_testcapi.pyd'
Error: Error 1 occurred creating conda environment r-tensorflow
In addition: Warning message:
running command '"C:\ANACON~1\Scripts\conda.exe" "create" "--yes" "--name" "r-tensorflow" "python=3.5"' had status 1 
>

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by rwanjohi** [comment]
(C:\Anaconda2) C:\Users\Richard>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 1.21.2
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
                          C:\Users\Richard\AppData\Local\conda\conda\envs
                          C:\Users\Richard\.conda\envs
          package cache : C:\Anaconda2\pkgs
                          C:\Users\Richard\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False

**Comment by rwanjohi** [comment]
My original goal was/is to install Keras and Tensorflow as instructed here https://rstudio.github.io/keras/
After my first error, I did: conda update conda AND conda update anaconda. Now, in RStudio, when I run the commands
library(keras)
install_tensorflow()
I am getting the following::

Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Error in system2(python, "--version", stdout = TRUE, stderr = TRUE) : 
  '"C:\ANACON~1\envs\r-tensorflow\python.exe"' not found
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\ANACON~1\envs\r-tensorflow/python.exe": The system cannot find the file specified

**Comment by rwanjohi** [comment]
Solved my problem. I updated my RStudio packages. I uninstalled Anaconda2 and installed Anaconda3. Tensorflow support Python 3.5+
