### ISSUE TITLE
Add automatic error report uploads

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5530]
Rather than asking users to report unexpected errors on the github issue tracker, offer to post the error to a private resource accessible by the conda core team.  The posted content should be anonymous.  It should only include the error stack trace and the contents of `conda info`.

**Comment by pzwang** [comment]
Let's make sure to do a quick review of the error aggregation service we use.  It would be nice if we could ensure that we can use the same one across a variety of Continuum-affiliated and non-affiliated OSS projects.  I have spoken with other maintainers in Scipy/PyData land, and I know they have wanted usage and crash data for a long time.  It would be great if our choice here could inform potential discussions at Scipy this summer about this topic.

**Comment by goanpeca** [comment]
We are trying out https://www.sumologic.com/ (on navi internally) this month to see how it could work.

**Comment by kalefranz** [comment]
I don't have a strong opinion, other than Sumo is the aggregator that's widely accepted to be the most secure.  Papertrail, Loggly, and Splunk are the other options that immediately come to mind.

Rolling out the #5531 PR is independent of which provider we ultimately choose.  The upload URL is on the conda.io domain, which we have managed by Cloudflare, and so are easily able to redirect.  The upload is also tolerant of failures.  We're not going to puke out a big stack trace if the upload URL we point to spits back a 500 error, for example.  In that case we just `log.debug()`, but otherwise fail silently.

**Comment by kalefranz** [comment]
I don't see these error reports as something we need to archive long-term. 30-60 days of history would be just fine for me.  If any unexpected stack traces aren't handled within 60 days, we have bigger problems than figuring out which of the half dozen possibilities of log aggregators is the ultimate best solution for us.

If someone makes a decision, we're going with option X, I'm happy to play along and move forward in that direction.
