### ISSUE TITLE
conda arguments not accepted

### ISSUE THREAD

**Issue by MartinPri** [conda/conda#5534]
Hi, 

I'm working with conda/anaconda since about 2 years. An easy update of packages does not work anymore.

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

                   platform : win-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.1.10
             python version : 2.7.13.final.0
           requests version : 2.0.1
           root environment : C:\Users\Martin\Anaconda2  (writable)
        default environment : C:\Users\Martin\Anaconda2
           envs directories : C:\Users\Martin\Anaconda2\envs
                          C:\Users\Martin\AppData\Local\conda\conda\envs
                          C:\Users\Martin\.conda\envs
              package cache : C:\Users\Martin\Anaconda2\pkgs
                          C:\Users\Martin\AppData\Local\conda\conda\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.0.1 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\Users\Martin\Anaconda2\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\cli\main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "C:\Users\Martin\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\cli\main_search.py", line 13, in <module>
        from ..api import get_index
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\api.py", line 1, in <module>
        from .core.index import get_index
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .repodata import collect_all_repodata
      File "C:\Users\Martin\Anaconda2\lib\site-packages\conda\core\repodata.py", line 21, in <module>
        from requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: cannot import name InsecureRequestWarning

**Comment by kalefranz** [comment]
Do you know how you managed to get that very old version of requests?  That's what's causing the problem here.
