### ISSUE TITLE
`conda activate c:\foo` activates non-existing environment

### ISSUE THREAD

**Issue by vmuriart** [conda/conda#5538]
Somewhere between conda `4.0.5` and `4.3.21` the behavior of `conda activate` changed.

## Steps to reproduce issue:

- Create a dummy empty folder `c:\foo`
- Execute `conda activate c:\foo`

On conda `4.0.5` this would error out with `No environment named "c:\foo" exists in C:\Anaconda2\envs, or is not a valid conda installation directory.`. 
But on `4.3.21` it activates with no exception and creates a `Scripts` directory. 

I haven't tested on other versions of conda other than the two mentioned above.

**Comment by kalefranz** [comment]
Should no longer be the case with conda 4.4.
