### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by petermchale** [conda/conda#5542]
I am trying to install a Python package called `graphlab` using a GUI launcher that the [vendor](https://turi.com/) supplies. The launcher fails, producing this output (excerpted from a log file):

```
There was a problem updating the conda package.  Restart GraphLab Create Launcher.

Unable to update conda:
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda 4.0.8* -> conda-env <2.5 -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

I'd be very grateful if someone could provide some guidance.

**Comment by petermchale** [comment]
I was able to install the `GraphLab` Python package by following the steps outline in Option 1 at this [webpage](https://turi.com/download/install-graphlab-create-command-line.html)

**Comment by Blair-Waldorf97** [comment]
Same question......Have you solved it ???

**Comment by petermchale** [comment]
The solution I describe above (Option 1 [here](https://turi.com/download/install-graphlab-create-command-line.html)) worked for me.

**Comment by Blair-Waldorf97** [comment]
Thank you !
But I did as it said .But when I want to Install my  licensed copy of GraphLab Create
it said:
Could not find a version that satisfies the requirement graphlab-create>=2.1 (from GraphLab-Create-License==2.1) (from versions: )
No matching distribution found for graphlab-create>=2.1 (from GraphLab-Create-License==2.1) 
Have you met it ? Anyway,thanks!

**Comment by petermchale** [comment]
Sorry, I haven't encountered this problem.
