### ISSUE TITLE
Conda source activate has ^M (potentially carriage return) in Cygwin $PATH

### ISSUE THREAD

**Issue by phizaz** [conda/conda#5544]
I use anaconda3 (with conda version `4.3.21`) on the Cygwin system on Windows 10 

When I `echo $PATH`, I saw:

```
/C/tools/Anaconda3/envs/<env>:/C/tools/Anaconda3/envs/<env>/Library/mingw-w64/bin:/C/tools/Anaconda3/envs/<env>/Library/usr/bin:/C/tools/Anaconda3/envs/<env>/Library/bin:/C/tools/Anaconda3/envs/<env>/Scripts^M:$MYOLDPATH
```

You can see there is a `^M` in my `$PATH` which makes me cannot run any executables from `<env>/Scripts`.

I wonder where does this come from ? 

Update: I have a good idea now, that I can avoid this problem once and for all if I can just ignore any carriage return in the shell. But, that is not the case for `zsh` which I'm using. The `bash` has its own way to achieve that. I think I will have just to use `bash` for the mean time.

**Comment by kalefranz** [comment]
Cygwin was never completely supported before conda 4.4.  Should be fine now though.
