### ISSUE TITLE
can't access conda-canary on OSX El Capitan

### ISSUE THREAD

**Issue by TheQuickBrownFoxJumpsTheLazyBitch** [conda/conda#5545]
Hi, I have a most annoying issue in conda: conda can't seem to be able to access the conda-canary repository. conda could not access the previous directory either. It bothers me cuz I removed my scikit-learn and I can't reinstall it.

I'm running
conda update anaconda

I get the error:
  File "/Users/monmac/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: conda-canary/osx-64/repodata.json.bz2

My conda config is:
$ conda config --get
--add channels 'conda-canary'

$ more .condarc 

channels:
  - conda-canary

My system is:
$ uname -a
Darwin MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1421

**Comment by nehaljwani** [comment]
Could you please share the complete trace back and the output for: `conda --version` and `conda info`?

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
Dear Nehal,
Many thanks for your mail. Please find below the request information:
Kind regards,Alexandre

$ conda --versionconda 2.0.4
$ conda infoCurrent conda install:
             platform : osx-64        conda version : 2.0.4     root environment : /Users/monmac/anaconda  (writable)  default environment : /Users/monmac/anaconda     envs directories : /Users/monmac/anaconda/envs        package cache : /Users/monmac/anaconda/pkgs         channel URLs : conda-canary/osx-64/          config file : /Users/monmac/.condarc
$ more .condarc
channels:  - conda-canary

      De : Nehal J Wani <notifications@github.com>
 À : conda/conda <conda@noreply.github.com> 
Cc : TheQuickBrownFoxJumpsTheLazyBitch <useridfr@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Dimanche 18 juin 2017 15h03
 Objet : Re: [conda/conda] can't access conda-canary on OSX El Capitan (#5545)
   
Could you please share the complete trace back and the output for: conda --version and conda info?—

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
Dear Nehal,

Please find below.

Kind regards,
Alexandre

$ conda --version
conda 2.0.4

$ conda info
Current conda install:

             platform : osx-64
        conda version : 2.0.4
     root environment : /Users/monmac/anaconda  (writable)
  default environment : /Users/monmac/anaconda
     envs directories : /Users/monmac/anaconda/envs
        package cache : /Users/monmac/anaconda/pkgs
         channel URLs : conda-canary/osx-64/
          config file : /Users/monmac/.condarc

**Comment by nehaljwani** [comment]
Wow, that's a very old version. You should consider upgrading to conda `4.3.x`

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
Hi Nehal,

Many thanks for your mail. I have tried updating anaconda to the newest version. And conda gives the same "ValueError: unknown url type: conda-canary/osx-64/repodata.json.bz2" message (trace below).

What do you advise I do next?
Kind regards,
Alexandre

$ conda update anaconda
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/monmac/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 75, in execute
    prepend=not args.override_channels)
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/api.py", line 33, in get_index
    return fetch_index(tuple(channel_urls))
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/utils.py", line 61, in __call__
    value = self.func(*args)
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 105, in fetch_index
    repodata = fetch_repodata(url)
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 72, in fetch_repodata
    u = connectionhandled_urlopen(request)
  File "/Users/monmac/anaconda/lib/python2.7/site-packages/conda/connection.py", line 83, in connectionhandled_urlopen
    return urllib2.urlopen(request)
  File "/Users/monmac/anaconda/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/monmac/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/Users/monmac/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: conda-canary/osx-64/repodata.json.bz2
$

**Comment by nehaljwani** [comment]
The channel URL is wrong (as evident from the output if `conda info`). Could you please share the contents of your `.condarc` file?

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
$ more .condarc

channels:
  - conda-canary

**Comment by nehaljwani** [comment]
I am not sure how this is happening, but if that's the only content in your condarc file, please delete it, and then type:
```
conda info
conda config --prepend channels conda-canary`
conda info
```

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
I have an error when I type conda config --prepend channels conda-canary. Trace below

$ rm .condarc 
MacBook-Pro:~ monmac$ conda info
Current conda install:

             platform : osx-64
        conda version : 2.0.4
     root environment : /Users/monmac/anaconda  (writable)
  default environment : /Users/monmac/anaconda
     envs directories : /Users/monmac/anaconda/envs
        package cache : /Users/monmac/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None

MacBook-Pro:~ monmac$ 
$ conda config --prepend channels conda-canary
usage: conda config [-h] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY BOOL_VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required

**Comment by nehaljwani** [comment]
You are using a very old version of conda (2.0.4). As I told you before, please install the latest one.

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
And I can't do this from my conda install? So how do I deinstall what I have and reinstall the new one then? Feels a bit like the Microsoft of old, donnit?

**Comment by TheQuickBrownFoxJumpsTheLazyBitch** [comment]
OK. I've removed my previous version and installed the latest one. All the packages are there and it seems to work. Thanks for your help
Kind regards,
Alexandre
