### ISSUE TITLE
IO Error installing on Mac OSX 10.6.8

### ISSUE THREAD

**Issue by eschwager** [conda/conda#555]
![screen shot 2014-02-12 at 8 52 25 am](https://f.cloud.github.com/assets/6545126/2148901/f1a747b4-93ec-11e3-96c0-1779edc02221.png)
I tried installing using the bash installer but got the error above.  Other packages install (e.g., flask), the bzip2 module works in python and the bzip2 command line tool works.  Any insight would be greatly appreciated.

**Comment by ilanschnell** [comment]
We only support Mac OS X 10.7 and higher (at least now we do).  Sorry
