### ISSUE TITLE
Need to change where anaconda default creates environments and caches packages

### ISSUE THREAD

**Issue by JDeBo** [conda/conda#5551]
I need to get anaconda to install packages not in the home/user directory because it doesn't have enough space to hold all the packages.

Solutions I've tried.
	- Create environment using the --prefix specifier
		○ conda create -p /opt/anaconda/.conda py3 python=3
			*Saves environment to /opt/anaconda/.conda, but still saves packages to /home/user/
	- Create Symlinks that connect /home/user/.conda to /opt/anaconda/.conda
		○ Works for 30 mins, then says the environment directories don't exist
                         	"CondaError: No writable package cache directories found in
	                         ('/opt/anaconda/3-4.3.1/pkgs', '/home/user/.conda/pkgs')"
			*Can still access the environments, just can't use conda create or conda install
		○ Tried editing .condarc to allow the use of softlinks.
		○ Tried using both absolute and relative symlinks
	- Edit .condarc file to specify /opt/anaconda/.conda/envs as the environment directory
		○ envs_dirs:
		  - /opt/anaconda/.conda/envs
			*Still saved packages to home directory

First question is whether there is a list key that can be added to .condarc to specify package cache location? I've checked https://conda.io/docs/config.html but there didn't seem to be an option discussed there. 

Second question is why the symlinking wouldn't be working? I looked at https://github.com/conda/conda/issues/691 but that didn't seem to be the same issue.

**Comment by JDeBo** [comment]
Nevermind, found solution using pkgs_dirs in .condarc file. not sure if it's the best practice, but seems to do the job. https://github.com/conda/conda/issues/4636

**Comment by member123456** [comment]
Could you explain your solutions clearly.

**Comment by diallobakary4** [comment]
@JDeBo is it possible to move the directory ~/.conda ?
