### ISSUE TITLE
activate env_name is not working

### ISSUE THREAD

**Issue by shivam001joshi** [conda/conda#5559]
Here is the cmd code
  C:\Users\DELL>conda info --env
  # conda environments:
  #
  tensorflow               D:\codes\anaconda\envs\tensorflow
  root                  *  D:\codes\anaconda

Activate command is giving the error as:
  C:\Users\DELL>activate tensorflow
  '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY' is not 
   recognized as
   an internal or external command,
   operable program or batch file.

The Same error is occurring for the root env. as:
  C:\Users\DELL>activate
  '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY' is not 
  recognized as an internal or external command,
  operable program or batch file.

The PATH var is set as:
  C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
  owsPowerShell\v1.0\;C:\Program Files (x86)\Java\jdk1.6.0_13\bin;C
  :\Python;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;D:\codes\anaconda;D:\codes\ana
  conda\Scripts;D:\codes\anaconda\Library\bin;C:\Program 
 Files\Git\cmd;D:\codes\anaconda\envs\tensorflow;D:\codes\anaconda\envs\tensorflow\Library\bin;D:\co
  des\anaconda\envs\tensorflow\Scripts;

**Comment by wulmer** [comment]
Seems like you have an invalid environment variable. Can you check your environment (run `set`) to see if there are variables with whitespace and/or quotes in them? Another option would be to modify `activate.bat` (find it with `where activate.bat`) and remove all leading `@` characters or `echo off` commands to make it print all commands. This should help you identify the script line that causes this error.
