### ISSUE TITLE
Unable to install Seaborn in Anaconda

### ISSUE THREAD

**Issue by gateway2dhawal** [conda/conda#5560]
I am very new to python and anaconda and I am using Windows 7 and trying to install Seaborn but in vain as I am getting errors. I tried lot of entries but almost same error response. As of now neither 'pip install seaborn' nor 'conda install seaborn' is working for me. Please Help!

C:\Users\mw422e>conda install seaborn
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs
/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\mw422e\AppData\Local\Continuum\Anaconda2  (wr
itable)
    default environment : C:\Users\mw422e\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\envs

          package cache : C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\pkgs

           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\mw422e\.condarc
           offline mode : False

`$ C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py ins
tall seaborn`

    Traceback (most recent call last):
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\mw422e\AppData\Local\Continuum\Anaconda2\lib\site-packages\
conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host
='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-6
4/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.co
nnection.VerifiedHTTPSConnection object at 0x0000000008EF9400>: Failed to establ
ish a new connection: [Errno 11004] getaddrinfo failed',)): https://repo.continu
um.io/pkgs/free/win-64/

**Comment by tyler-thetyrant** [comment]
`conda udpate conda` will get you the most recent version of conda, 4.3.22.
Can you try again with the newest conda?

**Comment by gateway2dhawal** [comment]
Thanks Tyler, but I have got this fixed. Its the firewall issue which I resolved.
