### ISSUE TITLE
conda env create --url https://raw.githubusercontent.com/.../environment.yml

### ISSUE THREAD

**Issue by jbednar** [conda/conda#5562]
I'm the maintainer for the datashader package, and I'm trying to streamline the process by which our users can set up an environment containing a bunch of libraries so that they can run our example scripts and notebooks.  These libraries aren't dependencies of the main library, and so they aren't installed with the main `datashader` conda install, but we do want people to be able to get them all easily.  For that reason, we provide an [environment file](https://raw.githubusercontent.com/bokeh/datashader/master/examples/environment.yml), but telling people to use that is complicated -- we either have to tell them to install datashader, then find the environment file wherever it ended up on their platform, or to go to the URL and download it using some platform-specific command or procedure, name it appropriately, then call it from the commandline.  

It would be vastly simpler for us our users if they could simply do the same command on all platforms to get the current environment:

```
conda env create --url https://raw.githubusercontent.com/bokeh/datashader/master/examples/environment.yml
```
 
Would that be feasible?

**Comment by mrocklin** [comment]
I needed this and so put up a PR here: https://github.com/conda/conda/pull/9835
