### ISSUE TITLE
Conda `activate` adds not only conda-env Path but also special Char to system PATH

### ISSUE THREAD

**Issue by schlichtanders** [conda/conda#5565]
Dear conda team,

I installed conda with python 3.6, my conda version is 4.3.21 and added a `py27` environment using by executing `$ conda create -n py27 python=2.7`. I am using Windows 10, 64 bit.

However if I now run ``activate py27``, ``python --version`` still outputs python 3.6. The problem is the PATH: ``echo %PATH%`` outputs something similar to the following
```
�C:\tools\Anaconda3\envs\py27;C:\tools\Anaconda3\envs\py27\Library\mingw-w64\bin;C:\tools\Anaconda3\envs\py27\Library\usr\bin;C:\tools\Anaconda3\envs\py27\Library\bin;C:\tools\Anaconda3\envs\py27\Scripts;...
```
[Actually if I just copy and paste from my commandline output, the � is simply ignored, so I added this char manually afterwards.]

An ad-hoc fix is to run ``SET PATH=%PATH:*C=C%`` which just deletes everything before the initial ``C`` character. After this ``python --version`` reports 2.7.

Concluding, somehow a special unicode character (uncopyable to github) is added to the front.
Do you know this issue? Does someone have an idea how to fix this?
Any help is highly appriciated!

**Comment by gauravssnl** [comment]
Even,i am facing the same problem on Windows .i have installed Anaconda on Windows and created environment py27 of Python 2.7.13 .but,even after activating py27 environment ,when i run python command,that run Python 3.6.1 which is default env.So,what is solution to that ???  @schlichtanders

**Comment by kalefranz** [comment]
Do you still have this problem with conda 4.4?
