### ISSUE TITLE
conda env upload fails

### ISSUE THREAD

**Issue by mhweber** [conda/conda#5567]
I recently reinstalled Anaconda and I'm currently unable to upload an environment to Anaconda cloud account using the following with error:

`F:\Continuum\Anaconda2) C:\Users\mweber>conda env upload --file=c:\users\mweber\temp\StreamCat.yml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:`

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.1.15
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : F:\Continuum\Anaconda2  (writable)
    default environment : F:\Continuum\Anaconda2
       envs directories : F:\Continuum\Anaconda2\envs
                          C:\Users\mweber\AppData\Local\conda\conda\envs
                          C:\Users\mweber\.conda\envs
          package cache : F:\Continuum\Anaconda2\pkgs
                          C:\Users\mweber\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\mweber\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : False

`$ F:\Continuum\Anaconda2\Scripts\conda-env-script.py upload --file=c:\users\mweber\temp\StreamCat.yml`

    Traceback (most recent call last):
      File "f:\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "f:\Continuum\Anaconda2\lib\site-packages\conda_env\cli\main_upload.py", line 101, in execute
        info = uploader.upload()
      File "f:\Continuum\Anaconda2\lib\site-packages\conda_env\utils\uploader.py", line 81, in upload
        if self.is_ready():
      File "f:\Continuum\Anaconda2\lib\site-packages\conda_env\utils\uploader.py", line 94, in is_ready
        return self.ensure_package_namespace() and self.ensure_distribution()
      File "f:\Continuum\Anaconda2\lib\site-packages\conda_env\utils\uploader.py", line 109, in ensure_package_namespace
        self.binstar.add_release(self.username, self.packagename, self.version, {}, '', '')
      File "f:\Continuum\Anaconda2\lib\site-packages\binstar_client\__init__.py", line 417, in add_release
        self._check_response(res)
      File "f:\Continuum\Anaconda2\lib\site-packages\binstar_client\__init__.py", line 216, in _check_response
        raise ErrCls(msg, res.status_code)
    BinstarError: (u'Bad Request: Bad request syntax or unsupported method ([POST] https://api.anaconda.org/release/mweber36/StreamCat/2017.06.21.1612 -> 400)', 400)`

**Comment by kalefranz** [comment]
Try using `anaconda upload` instead

**Comment by mhweber** [comment]
Works like a charm - thanks!
