### ISSUE TITLE
Error during update Conda

### ISSUE THREAD

**Issue by MrSerGV** [conda/conda#5569]
Does anyone know what need to fix?
![snap 2017-06-20 at 17 16 59](https://user-images.githubusercontent.com/29592454/27372991-378f5332-566f-11e7-9b43-9b7ec5718b7a.png)

**Comment by tyler-thetyrant** [comment]
You are using a very old version of conda, which it probably break when it tries to update itself. 
I would uninstall and reinstall miniconda or anaconda completely, which will give you the most up to date version, 4.3.22

**Comment by MrSerGV** [comment]
Thank you for answer.
