### ISSUE TITLE
Error setting up custom channel

### ISSUE THREAD

**Issue by PeterKucirek** [conda/conda#5576]
I'm trying to setup a local custom channel, and have been following along with the [documentation](https://conda.io/docs/custom-channels.html). I have setup my channel exactly as described, containing the following structure:

* /my-channel
  - /noarch
    + repodata.json.bz2
    + repodata.json
    + .index.json
  - /wind-64
    + my-package-0.0.1.tar.bz2
    + repodata.json.bz2
    + repodata.json
    + .index.json

However, when i call `conda search my-package -c file://my-channel --override-channels` I get the following error:

```
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: file://my-channel

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
```

I have no idea how to resolve this error. I've made sure to update my  version using `conda update conda` but it's had no effect. The only thing that I can think that might be a little unusual is that I have a few different Miniconda installations on my machine, some Python27 and some Python35. 

Here are the results of `conda info`:

```
Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 1.11.0
         python version : 2.7.11.final.0
       requests version : 2.18.1
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\pjk\AppData\Local\conda\conda\envs
                          C:\Users\pjk\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\pjk\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\pjk\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.18.1 CPython/2.7.11 Windows/7
Windows/6.1.7601
          administrator : True
```

**Comment by kalefranz** [comment]
The problem your facing here is with file:// urls on windows. I have to look up the details every time I attempt to use them. Is it two slashes or three? Include drive letter or not? Include colon after drive letter or not? I never remember. 

Hopefully conda knows how to do it right at this point though. I would try just using `-c c:\my-channel`

**Comment by PeterKucirek** [comment]
Thanks @kalefranz, I tried using `file:///` followed by the **absolute path including the drive letter**, and I was able to get it working.

It would helpful if this was mentioned in the documentation.
