### ISSUE TITLE
Windows: Running 'conda' on partially quoted path fails

### ISSUE THREAD

**Issue by cmeyer** [conda/conda#5589]
If I set an environment variable on Windows:

set MCC="C:\Miniconda43"

then try to run conda:

%MCC%\Scripts\conda

it fails on 4.3.22; succeeds on 4.3.9.

Example below.

```
C:\Users\Chris>%MCC%\Scripts\Conda --version
conda 4.3.9

C:\Users\Chris>%MCC%\Scripts\Conda update conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Users\Chris\Anaconda3:

The following packages will be UPDATED:

    conda: 4.3.9-py36_0 --> 4.3.22-py36_0

Proceed ([y]/n)? y

conda-4.3.22-p 100% |###############################| Time: 0:00:00   3.78 MB/s

C:\Users\Chris>%MCC%\Scripts\Conda --version
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: argument command: invalid choice: 'C:\\Users\\Chris\\Anaconda3\\Scripts\\conda-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

C:\Users\Chris>set MCC
MCC="C:\Users\Chris\Anaconda3"

```

**Comment by mingwandroid** [comment]
Please remove the quotes. There is no need for them.

**Comment by cmeyer** [comment]
There are plenty of workarounds -- but the quotes are perfectly valid and there _is_ a need for them if the path to Conda has spaces in it.

Please re-open?

**Comment by mingwandroid** [comment]
There is never a need for an environment variable on Windows to contain double-quotes. Whereas on Unix, double quotes are used to prevent the delimiting of such env vars at spaces and do not make it into the content of the env. var, on Windows things are different and the env. var includes those quotes.

To see this:

```
set TEST="Hello World"
echo %TEST%
"Hello World"
```

Versus:

```
set TEST=Hello World
echo %TEST%
Hello World
```

Alternatively, you can do:

```
set "TEST=Hello World" if you want things to seem a bit more Unix-like, and in this case Windows will just discard them for you.

**Comment by mingwandroid** [comment]
I should clarify that any attempt to 'handle' double quotes by programs inevitably breaks the ability to pass double quotes to those programs when that is the intention.

**Comment by cmeyer** [comment]
To run a program without quotes (rename the Anaconda installation directory temporarily) you need to quote the entire expression.

```
set MCC=C:\Users\Chris\A n a c o n d a 3
REM next line fails
%MCC%\Scripts\Conda.exe
REM next line works
"%MCC%\Scripts\Conda.exe"
```

However, there IS a need to quote strings.

If you have a script that calls another script, the only way to pass the path into the second script is to quote it on the command line.

Script1.bat:

```
set MCC %1
REM this must be UNQUOTED to handle quotes properly
%MCC%\Scripts\Conda.exe
```

Script2.bat

```
REM this MUST be quoted to pass it as argument #1
call Script1.bat "C:\Users\Chris\A n a c o n d a 3"
```

I maintain that the 'conda' program is what's broken, not my use of double-quotes.

Also, I'm not proposing to pass quoted arguments to conda -- the problem, instead, is the path to 'conda' itself (the %0 argument). It looks like 'conda' is mismanaging it's conversion of the %0 argument when processing the arguments to 'conda-script'.

**Comment by cmeyer** [comment]
One other comment... this doesn't really have to do with environment variables.

```
REM next line runs
"C:\Users\Chris\A n a c o n d a 3\Scripts\conda.exe"
REM next line doesn't run
"C:\Users\Chris\A n a c o n d a 3"\Scripts\conda.exe
```

It seems to have to do with how the new 'conda' / 'conda-script' combination processes argument 0.

**Comment by mingwandroid** [comment]
I've explained why it is reasonable to consider your use of double-quotes when using `set` to be broken, but you do have a point with your new example, reopening.

**Comment by cmeyer** [comment]
The point is that this writing this on a command line is a valid way to run a program and it fails when running conda (conda runs, btw, it's conda-script that doesn't run). And it used to work fine (4.3.9 worked, 4.3.22 doesn't).

```
"C:\Users\Chris\A n a c o n d a 3"\Scripts\conda
```

**Comment by mingwandroid** [comment]
I've assigned it to myself, but I think you'll have to use a workaround for now. There are two as I see it:

1. Use quotes around the *full* path and avoid adding broken quotes in env. vars.
2. Run activate.bat and then run `conda.exe` without specifying the full path (this is the supported way to use conda).

**Comment by mingwandroid** [comment]
For my own reference when I cycle back to this: https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

**Comment by cmeyer** [comment]
Thanks for keeping this open. As another workaround I think I can `cd` to the directory and run `conda` relative to the current directory.

**Comment by mingwandroid** [comment]
activate.bat is the correct way. Conda needs to set many path entries and some other vars and packages can run bespoke activation and deactivation logic and that only happens when you use activate.bat and deactivate.bat

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#7020
