### ISSUE TITLE
python-socketio and conda-env not found

### ISSUE THREAD

**Issue by brianray** [conda/conda#5590]
C:\Users\brray\AppData\Local\Continuum\Anaconda3\Scripts>conda install --verbose -y -c conda-forge python-socketio
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\brray\AppData\Local\Continuum\Anaconda3:

The following NEW packages will be INSTALLED:

    python-engineio: 1.5.2-py36_0  conda-forge
    python-socketio: 1.7.4-py36_0  conda-forge

The following packages will be UPDATED:

    conda:           4.3.21-py36_0             --> 4.3.22-py36_0 conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env:       2.6.0-0                   --> 2.6.0-0       conda-forge

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\brray\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\brray\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\brray\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\brray\AppData\Local\conda\conda\envs
                          C:\Users\brray\.conda\envs
          package cache : C:\Users\brray\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\brray\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.10586
          administrator : False

`$ C:\Users\brray\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install --verbose -y -c conda-forge python-socketio`

    Traceback (most recent call last):
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 494, in execute
        self._execute_action(action)
      File "C:\Users\brray\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 516, in _execute_action
        raise CondaMultiError(exceptions)
    conda.CondaMultiError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/conda-env-2.6.0-0.tar.bz2>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.

    CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/conda-env-2.6.0-0.tar.bz2>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.

    CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/conda-env-2.6.0-0.tar.bz2>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by kalefranz** [comment]
Was this an intermittent HTTP issue you were able to solve by retrying?
