### ISSUE TITLE
Failed to initialize anaconda directory etc.

### ISSUE THREAD

**Issue by oathofoblivion** [conda/conda#5593]
So, I've been trying to install anaconda for python3  for the past few months and I've been having no success at all. I always encounter exactly three error messages saying it can't initialize Anaconda directory etc. But, somehow yesterday when I used the same installer executable that I've been using for the past few months, it seems to run perfectly and didn't give the error messages that I've been seeing these past few months. As for what changed, the only thing that I did was I completely cleared any traces of Python3 that was installed on my PC (The directories of vanilla python3 and all its content, the python launcher, previous failed installation of anaconda, and cleaned my registry of any possible problems). Hope this helps with solving the problem that seems to be a common issue for Anaconda users.

**Comment by kalefranz** [comment]
I'm sure this is just a dll hell issue.  But I'll move it to ContinuumIO/anaconda-issues so it can be closed from there.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6589
