### ISSUE TITLE
HTTP error occured while downloading the packages

### ISSUE THREAD

**Issue by Prabhat-IIT** [conda/conda#5594]
CondaError: CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/linux-64/notebook-5.0.0-py27_0.tar.bz2> Elapsed: None

**Comment by Prabhat-IIT** [comment]
When I tried to install the same packages again it showed:
CondaValueError: prefix already exists: /home/prabhat/miniconda2/envs/mypython

**Comment by kalefranz** [comment]
You had some type of download error. Not enough details for me to help you with more information.  It was probably just intermittent, unless you had a proxy server misconfiguration.

For the second, just

    rm -rf /home/prabhat/miniconda2/envs/mypython
