### ISSUE TITLE
what's wrong with my spyder?

### ISSUE THREAD

**Issue by aky15** [conda/conda#5595]
aky15@aky15-Lenovo-Y40-70:~$ spyder
xkbcommon: ERROR: failed to add default include path /home/aky15/anaconda3/lib
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file

**Comment by kalefranz** [comment]
No idea.  This is the conda issue tracker, not the spyder issue tracker.  Closing.
