### ISSUE TITLE
Broken file in 

### ISSUE THREAD

**Issue by vicpara** [conda/conda#5599]
Hi, 
While I'm installing an environment using conda for python 3 I'm reaching a binary I cannot download from S3. It looks like the bucket or the file is corrupted:

`curl -O -L --insecure https://conda.anaconda.org/conda-forge/linux-64/gdal-1.11.5-np112py35_5.tar.bz2`
fails to download the file.

**Comment by tyler-thetyrant** [comment]
```

**Comment by tyler-thetyrant** [comment]
root@6924d1722f0f:/# curl -O -L --insecure https://conda.anaconda.org/conda-forge/linux-64/gdal-1.11.5-np112py35_5.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2781    0  2781    0     0   5435      0 --:--:-- --:--:-- --:--:--  6558
100 61.2M  100 61.2M    0     0  3146k      0  0:00:19  0:00:19 --:--:-- 3912k
