### ISSUE TITLE
Anaconda/3-4.4.0 Permission Issue for Creating Virtual Environment in Multi-User Environment

### ISSUE THREAD

**Issue by yangliu2009** [conda/conda#5601]
Just installed Anaconda/3-4.4.0 in a shared directory on our cluster. The conda version is 4.3.21. When I run the command 'conda create -p /scratch/user/abc/Test/test-conda-4.3-env python=3.6 anaconda' to create a virtual environment in a user's directory, the command failed with error:
anaconda-4.4.0 100% |###################################################################################################################################################################| Time: 0:00:00   5.54 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::expat-2.1.0-0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

PermissionError(13, 'Permission denied')

What could be wrong? How can this error be fixed?

**Comment by nehaljwani** [comment]
Does passing an additional `--copy` argument to `conda create` fix this for you?

**Comment by yangliu2009** [comment]
Tried "conda create --copy -p /scratch/user/abc/Test/conda-virtual-local anaconda". Still recieved the same error:
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::expat-2.1.0-0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.


PermissionError(13, 'Permission denied')


Yang

**Comment by nehaljwani** [comment]
Could you please share the output of the same command with additional argument `-vvv` ?

**Comment by yangliu2009** [comment]
Below is the output from the command with '-vvv' option.

INFO conda.core.link:_execute_actions(319): ===> LINKING PACKAGE: defaults::expat-2.1.0-0 <===
  prefix=/scratch/user/yangliu/Test/conda-virtual-local
  source=/software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0

TRACE conda.core.path_actions:execute(539): creating linked package record /scratch/user/yangliu/Test/conda-virtual-local/conda-meta/expat-2.1.0-0.json
TRACE conda.gateways.disk.create:write_as_json_to_file(55): writing json to file /scratch/user/yangliu/Test/conda-virtual-local/conda-meta/expat-2.1.0-0.json
TRACE conda.core.path_actions:execute(243): linking None => /scratch/user/yangliu/Test/conda-virtual-local/bin
TRACE conda.gateways.disk.create:mkdir_p(158): making directory /scratch/user/yangliu/Test/conda-virtual-local/bin
TRACE conda.core.path_actions:execute(243): linking None => /scratch/user/yangliu/Test/conda-virtual-local/include
TRACE conda.gateways.disk.create:mkdir_p(158): making directory /scratch/user/yangliu/Test/conda-virtual-local/include
TRACE conda.core.path_actions:execute(243): linking None => /scratch/user/yangliu/Test/conda-virtual-local/lib/pkgconfig
TRACE conda.gateways.disk.create:mkdir_p(158): making directory /scratch/user/yangliu/Test/conda-virtual-local/lib/pkgconfig
TRACE conda.core.path_actions:execute(243): linking None => /scratch/user/yangliu/Test/conda-virtual-local/share/man/man1
TRACE conda.gateways.disk.create:mkdir_p(158): making directory /scratch/user/yangliu/Test/conda-virtual-local/share/man/man1
TRACE conda.core.path_actions:execute(243): linking /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/bin/xmlwf => /scratch/user/yangliu/Test/conda-virtual-local/bin/xmlwf
TRACE conda.gateways.disk.create:_do_copy(220): copying /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/bin/xmlwf => /scratch/user/yangliu/Test/conda-virtual-local/bin/xmlwf
TRACE conda.core.path_actions:execute(243): linking /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/include/expat.h => /scratch/user/yangliu/Test/conda-virtual-local/include/expat.h
TRACE conda.gateways.disk.create:_do_copy(220): copying /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/include/expat.h => /scratch/user/yangliu/Test/conda-virtual-local/include/expat.h
TRACE conda.core.path_actions:execute(243): linking /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/include/expat_external.h => /scratch/user/yangliu/Test/conda-virtual-local/include/expat_external.h
TRACE conda.gateways.disk.create:_do_copy(220): copying /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/include/expat_external.h => /scratch/user/yangliu/Test/conda-virtual-local/include/expat_external.h
TRACE conda.core.path_actions:execute(243): linking /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/lib/libexpat.a => /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.a
TRACE conda.gateways.disk.create:_do_copy(220): copying /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/lib/libexpat.a => /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.a
TRACE conda.core.path_actions:execute(243): linking /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/lib/libexpat.la => /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la
TRACE conda.gateways.disk.create:_do_copy(220): copying /software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0/lib/libexpat.la => /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la
TRACE conda.core.path_actions:execute(297): rewriting prefixes in /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la
DEBUG conda.core.link:_execute_actions(330): Error in action #9 for pkg_idx #0 PrefixReplaceLinkAction(target_prefix='/scratch/user/yangliu/Test/conda-virtual-local', target_short_path='lib/libexpat.la', source_prefix='/software/hprc/Anaconda/3-4.4.0/pkgs/expat-2.1.0-0', source_short_path='lib/libexpat.la', link_type=<LinkType.copy: 3>, _execute_successful=True, prefix_placeholder='/opt/anaconda1anaconda2anaconda3', file_mode=<FileMode.text: 'text'>, _verified=True)
DEBUG conda.core.link:_execute_actions(331): Traceback (most recent call last):
  File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/link.py", line 326, in _execute_actions
    action.execute()
  File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/path_actions.py", line 299, in execute
    self.file_mode)
  File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/portability.py", line 57, in update_prefix
    update_file_in_place_as_binary(realpath(path), _update_prefix)
  File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 28, in update_file_in_place_as_binary
    fh = exp_backoff_fn(open, file_full_path, 'rb+')
  File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 21, in exp_backoff_fn
    return fn(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: '/scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la'

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::expat-2.1.0-0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

INFO conda.core.link:_reverse_actions(361): ===> REVERSING PACKAGE LINK: defaults::expat-2.1.0-0 <===
  prefix=/scratch/user/yangliu/Test/conda-virtual-local

DEBUG conda.core.link:_reverse_actions(362): reversing pkg_idx #0 from axn_idx #9
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.a
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/include/expat_external.h
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/include/expat.h
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/bin/xmlwf
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:try_rmdir_all_empty(164): Attempting to remove directory /scratch/user/yangliu/Test/conda-virtual-local/share/man/man1
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:try_rmdir_all_empty(164): Attempting to remove directory /scratch/user/yangliu/Test/conda-virtual-local/lib/pkgconfig
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:try_rmdir_all_empty(164): Attempting to remove directory /scratch/user/yangliu/Test/conda-virtual-local/include
TRACE conda.core.path_actions:reverse(250): reversing link creation /scratch/user/yangliu/Test/conda-virtual-local
TRACE conda.gateways.disk.delete:try_rmdir_all_empty(164): Attempting to remove directory /scratch/user/yangliu/Test/conda-virtual-local/bin
TRACE conda.core.path_actions:reverse(546): reversing linked package record creation /scratch/user/yangliu/Test/conda-virtual-local/conda-meta/expat-2.1.0-0.json
TRACE conda.gateways.disk.delete:rm_rf(31): rm_rf /scratch/user/yangliu/Test/conda-virtual-local/conda-meta/expat-2.1.0-0.json
DEBUG conda.common.signals:signal_handler(49): de-registering handler for SIGBREAK
DEBUG conda.common.signals:signal_handler(49): de-registering handler for SIGBREAK
DEBUG conda.common.signals:signal_handler(49): de-registering handler for SIGBREAK
DEBUG conda.common.signals:signal_handler(49): de-registering handler for SIGBREAK
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/software/hprc/Anaconda/3-4.4.0' using path '/software/hprc/Anaconda/3-4.4.0/conda-meta/history'
TRACE conda.gateways.disk.test:file_path_is_writable(23): checking path is writable /software/hprc/Anaconda/3-4.4.0/conda-meta/history
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: '/software/hprc/Anaconda/3-4.4.0/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/software/hprc/Anaconda/3-4.4.0' using path '/software/hprc/Anaconda/3-4.4.0/conda-meta/history'
TRACE conda.gateways.disk.test:file_path_is_writable(23): checking path is writable /software/hprc/Anaconda/3-4.4.0/conda-meta/history
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: '/software/hprc/Anaconda/3-4.4.0/conda-meta/history'
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /software/hprc/Anaconda/3-4.4.0  (read only)
    default environment : /software/hprc/Anaconda/3-4.4.0
       envs directories : /home/yangliu/.conda/envs
                          /software/hprc/Anaconda/3-4.4.0/envs
          package cache : /software/hprc/Anaconda/3-4.4.0/pkgs
                          /home/yangliu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/yangliu/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/2.6.32-696.3.2.el6.x86_64 CentOS/6.9 glibc/2.12    
                UID:GID : 15547:15547

`$ /software/tamusc/Anaconda/3-4.4.0/bin/conda create -vvv --copy -p /scratch/user/yangliu/Test/conda-virtual-local anaconda`


    Traceback (most recent call last):
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/link.py", line 326, in _execute_actions
        action.execute()
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/path_actions.py", line 299, in execute
        self.file_mode)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/portability.py", line 57, in update_prefix
        update_file_in_place_as_binary(realpath(path), _update_prefix)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 28, in update_file_in_place_as_binary
        fh = exp_backoff_fn(open, file_full_path, 'rb+')
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 21, in exp_backoff_fn
        return fn(*args, **kwargs)
    PermissionError: [Errno 13] Permission denied: '/scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la'
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/software/hprc/Anaconda/3-4.4.0/lib/python3.6/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la'

**Comment by kalefranz** [comment]
Output of 

    ls -al /scratch/user/yangliu/Test/conda-virtual-local/lib/libexpat.la

?

**Comment by yangliu2009** [comment]
Sorry that the files/directory were deleted. However, it works now after 'write' permission was added to the owner of the directory where Anaconda/3-4.4.0 was installed. The 'write' permission  was removed to avoid installation of packages by accident.
