### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by linglingtingfei** [conda/conda#5603]
When I update conda , it outputted the error shown on screenshots. Even I update anaconda, it showed the same error. I don't know why?
![qq 20170627092618](https://user-images.githubusercontent.com/20789616/27566933-ffe52d7a-5b1a-11e7-9591-30eb390b4668.jpg)
![qq 20170627092601](https://user-images.githubusercontent.com/20789616/27566934-ffecd25a-5b1a-11e7-91e8-d1eb084defae.jpg)

**Comment by kalefranz** [comment]
Probably a fluke one-off system error. I haven't seen any other similar reports.  Go ahead and file a new issue if the problem persists.
