### ISSUE TITLE
python 3.6 socket module is missing CAN bus symbols

### ISSUE THREAD

**Issue by thom-nic** [conda/conda#5604]
My issue is with the *python build* installed via miniconda, I hope this is the right place to report it.  I am new to miniconda but not sure why parts of the python3 `socket` module would be absent:
```
$ uname -a
Linux test-host 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ which python
/home/test/miniconda3/bin/python
$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.AF_CAN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'socket' has no attribute 'AF_CAN'
>>> socket.PF_CAN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'socket' has no attribute 'PF_CAN'
>>> socket.AF_BLUETOOTH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```
Stock python3:
```
$ /usr/bin/python3 --version
Python 3.5.2
$ /usr/bin/python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.AF_CAN
<AddressFamily.AF_CAN: 29>
>>> socket.PF_CAN
29
>>> socket.AF_BLUETOOTH
<AddressFamily.AF_BLUETOOTH: 31>
```

Ref: https://docs.python.org/3/library/socket.html#socket.AF_CAN
I did a quick manual search through conda.io/docs/ and did not see anything that might indicate parts of python's stdlib were omitted - sorry if I missed something.  Thanks!

**Comment by mingwandroid** [comment]
The reason these symbols are missing is because we support Centos5 level OSes which come with the Linux kernel version 2.6.18.4 (heavily patched by Redhat).

From: https://en.m.wikipedia.org/wiki/SocketCAN

> Patches about CAN were added in the 2.6.25 Linux kernel.

**Comment by thom-nic** [comment]
Bummer.  Ok well thanks for the explanation!  I understand that not too many people will be using SocketCAN 😂
