### ISSUE TITLE
Add PrefixData, SubdirData, and PackageCacheData to conda/api.py

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5610]
https://github.com/conda/conda/commit/69f1b7af939adb783ee284fa952174e8fa447569#diff-aa516f421733d7851d878e08d4bf7464R408

This is used in conda-build at https://github.com/conda/conda-build/blob/master/conda_build/render.py#L210

Please provide an interface (ideally in conda's exports) that I can use to ask Conda to download packages for me.

**Comment by kalefranz** [comment]
Conda 4.4 provides the `Solver` class in `conda/api.py`. In turn, that provides an instance of `UnlinkLinkTransaction` via the `solve_for_transaction()` method, which in turn provides an instance of `ProgressiveFetchExtract` via the `get_pfe()` method.

Perhaps that's progress.  I don't think it's enough though.

In conda 4.5 we should target adding the `PrefixData`, `SubdirData` (representing repodata), and `PackageCacheData` classes to `conda/api.py`.

I'm still not sure that's enough.

I'd like to spend some time auditing all of conda-build's interactions with conda--with a lot of help from @msarahan--to see which pieces of conda-build could be dramatically simplified by preferring these interfaces over all of the legacy interfaces that are still being supported in conda.

**Comment by kalefranz** [comment]
I'm going to bump the milestone here to 4.5.  I don't think it should block the 4.4.0 release.
