### ISSUE TITLE
Anaconda fusion seems to be popping up in the conda cache even if fusion is private?

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#5612]

**Comment by chdoig** [comment]
![image](https://user-images.githubusercontent.com/4940549/27704361-0d5b1774-5cd0-11e7-9a20-aef6dd38dc32.png)

This is what I see. Maybe the package is locally cached, but tries to pull it from Anaconda Cloud?

I'm not sure if this is a conda issue or a Navigator issue

**Comment by kalefranz** [comment]
The only thing it would be on the conda side is cached repodata.  So `conda clean -i`.
