### ISSUE TITLE
conda install --offline fails with "Package missing in current win-64 channels"

### ISSUE THREAD

**Issue by haraldsinger** [conda/conda#5613]
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\Anaconda2' using path 'C:\Anaconda2\conda
-meta\history'
TRACE conda.gateways.disk.test:file_path_is_writable(23): checking path is writable C:\Anaconda2\conda-meta\history
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\Anaconda2' using path 'C:\Anaconda2\conda
-meta\history'
TRACE conda.gateways.disk.test:file_path_is_writable(23): checking path is writable C:\Anaconda2\conda-meta\history
Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
                          C:\Users\hsinger\AppData\Local\conda\conda\envs
                          C:\cygwin64\home\hsinger\.conda\envs
          package cache : C:\Anaconda2\pkgs
                          C:\Users\hsinger\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/win-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/win-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-64  (offline)
                          https://repo.continuum.io/pkgs/msys2/noarch  (offline)
            config file : None
             netrc file : None
           offline mode : True
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Anaconda2\Scripts\conda-script.py install -v -v -v --offline anaconda_packages.tar`

   Traceback (most recent call last):
     File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
       return_value = func(*args, **kwargs)
     File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
       exit_code = args.func(args, p)
     File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
       install(args, parser, 'install')
     File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 312, in install
       raise PackageNotFoundError(error_message)
   PackageNotFoundError: Package missing in current win-64 channels:
     - anaconda_packages.tar

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda/pull/6371 in conda 4.4.0
