### ISSUE TITLE
rm_rf not removing envs on Windows

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5614]
This is an update to work done in https://github.com/conda/conda/commit/4c9421270d16cb58e58c5dc4ee045a5673714e28

I have a build that uses conda 4.3.22.  What should be happening in between each env creation is complete removal of the build prefix (here's the loop that we're in: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1078-L1144).  The build log indicates that the prefix is not being removed.

https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/build/1.0.2206/job/k2dhbhrflwmwe4vb#L1483

Note that conda-build does its own removal (https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L974-L990), but still depends on conda's rm_rf function to clean up any cached environment data.

I have debugged this locally and isolated it down to the install_actions function:

https://gist.github.com/msarahan/3a4ff8b6550ca7b0510e8f3f9aa78e78

Take a look at those specs, and then what comes out as the install actions - the install actions include lots of m2 packages, but nothing in the specs is tied to those.

```
ipdb> specs
(MatchSpec('vs2015_runtime 14.0.25420.*'), MatchSpec('wheel 0.29.0.*'), MatchSpec('pip 9.0.1.*'), MatchSpec('lib1intradependencies 1.0.*'), MatchSpec('setuptools 27.2.0.*'), MatchSpec('python 3.6.0.*'))

> z:\msarahan\code\conda-build\conda_build\environ.py(728)get_install_actions()
    727                         raise
--> 728         if disable_pip:
    729             actions['LINK'] = [spec for spec in actions['LINK']

ipdb> actions
defaultdict(<type 'list'>, {u'op_order': ('CHECK_FETCH', 'RM_FETCHED', 'FETCH', 'CHECK_EXTRACT', 'RM_EXTRACTED', 'EXTRACT', 'UNLINK', 'LINK', 'SYMLINK_CONDA'), 'SYMLINK_CONDA': ['C:\\Users\\builder\\Miniconda2'], 'PREFIX': u'c:\\users\\builder\\appdata\\local\\temp\\pytest-of-msarahan\\pytest-200\\test_intradependencies0\\intradependencies_1498762929098\\_h_env', 'LINK': [Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'msys2-conda-epoch-20160418-1', name=u'msys2-conda-epoch', version=u'20160418', build_string=u'1', build_number=1, with_features_depends=None, base_url=None, platform=None)
```

Here's repodata for the 2 preceding subpackages, which have no dependencies (to make sure that conda isn't picking up msys2 from the lib1intradependencies spec):

```
{
  "info": {},
  "packages": {
    "lib1intradependencies-1.0-h974edbf_0.tar.bz2": {
      "build": "h974edbf_0",
      "build_number": 0,
      "depends": [],
      "md5": "24212df23ea19f2d93f73628eb64cf1f",
      "name": "lib1intradependencies",
      "sha256": "24d5f0e51d46befe879452cc4806bc9d9fc169c828ef1883a09e28122506eae4",
      "sig": null,
      "size": 3283,
      "subdir": "win-64",
      "timestamp": 1498762962457,
      "version": "1.0"
    },
    "lib2intradependencies-1.0-hb0d1d5b_0.tar.bz2": {
      "build": "hb0d1d5b_0",
      "build_number": 0,
      "depends": [],
      "md5": "e80aa69fbaa0940b2fdf09e146e4fb07",
      "name": "lib2intradependencies",
      "sha256": "dc2bd292815b155bd3d28688676c12d0380b38c1c0067b998913f129904a578c",
      "sig": null,
      "size": 3277,
      "subdir": "win-64",
      "timestamp": 1498762966598,
      "version": "1.0"
    }
  }
}
```

**Comment by kalefranz** [comment]
I highly suspect the root cause here is https://github.com/conda/conda/issues/5154

**Comment by kalefranz** [comment]
I believe we solved this already.  Please reopen if you disagree.
