### ISSUE TITLE
Creating Conda Env using .yml on Win 7

### ISSUE THREAD

**Issue by RyanAshbaugh** [conda/conda#5619]
I am trying to create a conda env using a .yml file. Below is the output as well as the command which causes it. The environment.yml file is in the current working directory of the Anaconda Prompt

> conda env create -f environment.yml --debug

Error:
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for
prefix 'C:\Users\Owner\Anaconda3' using path 'C:\Users\Owner\Anaconda3\conda-met
a\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for
prefix 'C:\Users\Owner\Anaconda3' using path 'C:\Users\Owner\Anaconda3\conda-met
a\history'
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\Owner\Anaconda3  (writable)
    default environment : C:\Users\Owner\Anaconda3
       envs directories : C:\Users\Owner\Anaconda3\envs
                          C:\Users\Owner\AppData\Local\conda\conda\envs
                          C:\Users\Owner\AppData\Roaming\SPB_16.6\.conda\envs
          package cache : C:\Users\Owner\Anaconda3\pkgs
                          C:\Users\Owner\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Owner\AppData\Roaming\SPB_16.6\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : True

`$ C:\Users\Owner\Anaconda3\Scripts\conda-env-script.py create -f environment.ym
l --debug`

    Traceback (most recent call last):
      File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Owner\Anaconda3\lib\site-packages\conda_env\cli\main_create
.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\Owner\Anaconda3\lib\site-packages\conda_env\specs\__init__.
py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Can't process without a name

Also the contents of environment.yml are shown below:

name: car-behavioral-cloning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - pip:
        - moviepy
        - tensorflow==1.1
        - keras==1.2

**Comment by nehaljwani** [comment]
@RyanAshbaugh Are you sure that the `environment.yml` file is in the same directory in which you are trying to invoke the `conda env create` command?

**Comment by RyanAshbaugh** [comment]
Yes, even when I supply the full path name to the environment.yml I get the same error.
