### ISSUE TITLE
conda info –envs & conda remove --name xxxx –all

### ISSUE THREAD

**Issue by AdamMajdi** [conda/conda#5623]
Last login: Sun Jul  2 16:13:40 2017 from 146.151.108.26
[user@server9 ~]$ conda info –envs
Fetching package metadata .........
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ /home/user/anaconda2/bin/conda info â€“envs`

    Traceback (most recent call last):
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 313, in execute
        print_package_info(args.packages)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 153, in print_package_info
        for dist in r.get_dists_for_spec(arg2spec(package)):
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 509, in arg2spec
        return str(spec)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 0: ordinal not in range(128)

**Comment by nehaljwani** [comment]
Try `conda info --envs` instead of `conda info –envs`
The difference is between two double dashes instead of single long one.

**Comment by AdamMajdi** [comment]
Thanks, nehaljwani! It works, but still have a problem with deleting an environment. I tried:
`conda remove --name flowers –all`

But it gave me the same error listed above. Any idea?

**Comment by AdamMajdi** [comment]
This works:
`conda remove -n bunnies --all`

**Comment by nehaljwani** [comment]
Even in the case of environment removal:
Try `conda remove --name flowers --all`  instead of `conda remove --name flowers –all`
The difference is between two double dashes instead of single long one.

It seems to me as if you are copying these command from some webpage on the internet where `--` is being rendered as `–` . If that is the case, I would suggest you to contact the author of that page and ask them to rectify that.

**Comment by nehaljwani** [comment]
Closing, as this doesn't seem to be a bug in conda.
