### ISSUE TITLE
Problems installing matplotlib into anaconda

### ISSUE THREAD

**Issue by matplotlibproblem** [conda/conda#5626]
EDIT: I think I MIGHT have just fixed this by fiddling with PIP to get that to do the install instead of letting conda try to do it.

I am trying to use matplotlib in python to run some existing pieces of python code needed for a research project. The windows system I've been working on is unusually set up so I've had to work from a directory inside my downloads folder rather than from the usual C:\ drive locations.

Initially I had problems with matplotlib not at the point in my code where the module tried to import (line 1, import matplotlib.pyplot as plt ) but at the fist time I tried to call it (a later line to the form of, plt.plot([1, 2, 3, 4], [1, 4, 9, 16]) ). So I found advice online suggesting I try using conda to uninstall matplotlib and pyqt and a few other packages, then reinstall them all. Now it seems that I cannot get matplotlib to reinstall, and any attempts o run python code which wants to import matplotlib fail as soon as the import is supposed to happen. Please suggest how I can fix this, thanks.

The error log is below and has been posted here as advised in the error message.

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\ana
condaPython  (writable)
    default environment : \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\ana
condaPython
       envs directories : \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\ana
condaPython\envs
                          C:\Users\[name hidden]\AppData\Local\conda\conda\envs
                          C:\Users\[name hidden]\.conda\envs
          package cache : \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\ana
condaPython\pkgs
                          C:\Users\[name hidden]\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : False

`$ \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\Scripts\con
da-script.py install -c conda-forge matplotlib=2.0.0`

    Traceback (most recent call last):
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\cli\install.py", line 363, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\core\link.py", line 263, in execute
        self.verify()
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\core\link.py", line 242, in verify
        self.prepare()
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\core\link.py", line 149, in prepare
        for pkg_info in self.packages_info_to_link)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\core\link.py", line 149, in <genexpr>
        for pkg_info in self.packages_info_to_link)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\core\link.py", line 54, in determine_link_type
        if hardlink_supported(source_test_file, target_prefix):
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\_vendor\auxlib\decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "\\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaPython\li
b\site-packages\conda\gateways\disk\test.py", line 84, in hardlink_supported
        assert not lexists(test_file), test_file
    AssertionError: \\uol.le.ac.uk\root\student\home\r\[name hidden]\Downloads\anacondaP
ython\.tmp.index.json

**Comment by kalefranz** [comment]
Fixed in a recent version of conda.
