### ISSUE TITLE
Please help with this error

### ISSUE THREAD

**Issue by dineshgit** [conda/conda#5627]
Any code that I attempt to execute on Anaconda Prompt would result in a similar error below:
This includes simple commands like "conda list", "conda update conda" and etc. 

Could someone please help ?

(C:\Toolkits\Anaconda3-4.2.0) C:\Users\dines>conda list
packages in environment at C:\Toolkits\Anaconda3-4.2.0:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.0.2
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : C:\Toolkits\Anaconda3-4.2.0  (writable)
    default environment : C:\Toolkits\Anaconda3-4.2.0
       envs directories : C:\Toolkits\Anaconda3-4.2.0\envs
                          C:\Users\dines\AppData\Local\conda\conda\envs
                          C:\Users\dines\.conda\envs
          package cache : C:\Toolkits\Anaconda3-4.2.0\pkgs
                          C:\Users\dines\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dines\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.5.3 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Toolkits\Anaconda3-4.2.0\Scripts\conda-script.py list`

    Traceback (most recent call last):
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main_list.py", line 242, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\cli\main_list.py", line 172, in print_packages
        installed = linked(prefix)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Toolkits\Anaconda3-4.2.0\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nehaljwani** [comment]
Does the following help?:
```
conda clean -i
```

**Comment by dineshgit** [comment]
Hi,

The command doesn't work. I still get the similar error as earlier.

Thanks

**Comment by kalefranz** [comment]
What happened here is that conda was forcibly stopped via SIGKILL or other means during an unlink-link transaction.  Because you were operating on your root environment, unfortunately, the easiest solution is to just reinstall.

**Comment by 77philosophia** [comment]
> Does the following help?:
> 
> ```
> conda clean -i
> ```

It works for me,thanks
