### ISSUE TITLE
How to install a more recent version of pyaudio package

### ISSUE THREAD

**Issue by billtubbs** [conda/conda#5629]
I'm trying out speech recognition using the SpeechRecognition package but when I execute the code it says:

```AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.7)```

I note from the [documentation](https://anaconda.org/anaconda/pyaudio) that Anaconda only includes `pyaudio` version 0.2.7.

Is it possible to upgrade conda to include the latest package or if not, how do I bypass conda and install the latest version just for the purposes of this current project.  (virtual environment maybe?).

Sorry I'm still a newbie when it comes to package/environment management.

**Comment by HLasse** [comment]
I'm in the exact same situation as you. Did you find a solution?

**Comment by billtubbs** [comment]
No.  I gave up!

**Comment by tomaso909** [comment]
You can install the latest version with pip:

`source activate -your environment name- `
`pip install pyaudio`

You may run into the following error when installing from pip:

` 
src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory  
    #include "portaudio.h" 
               ^  
   compilation terminated.  
   error: command 'gcc' failed with exit status 1 
 `

That is because you don't have the PortAudio development package installed. Install it with:

`sudo apt-get install portaudio19-dev`

**Comment by billtubbs** [comment]
I'm on a Mac so I did the following and it worked:

```
brew install portaudio 
pip install pyaudio
```

All installed and working! Thanks @tomaso909

**Comment by kalefranz** [comment]
Not really a conda issue. Somebody here should head over to conda-forge though and fix this :)

**Comment by rahul6612** [comment]
i am using windows 10 and when i am running the commang - git push heroku master getting this erro please solve my problem from 4 days i am searching the solution but didn't get
 Running setup.py install for PyAudio: started
remote:            Running setup.py install for PyAudio: finished with status 'error'
remote:            Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qx34haso/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mydedmjn-record/install-record.txt --single-version-externally-managed --compile:
remote:            running install
remote:            running build
remote:            running build_py
remote:            creating build
remote:            creating build/lib.linux-x86_64-3.6
remote:            copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
remote:            running build_ext
remote:            building '_portaudio' extension
remote:            creating build/temp.linux-x86_64-3.6
remote:            creating build/temp.linux-x86_64-3.6/src
remote:            gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
remote:            src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory
remote:            compilation terminated.
remote:            error: command 'gcc' failed with exit status 1
remote:
remote:            ----------------------------------------
remote:        Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qx34haso/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mydedmjn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qx34haso/PyAudio/
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to shoppingwave.
remote:
To https://git.heroku.com/shoppingwave.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shoppingwave.git'

**Comment by bronz3beard** [comment]
1. sudo apt purge python3-pyaudio
2. sudo apt install portaudio19-dev python-all-dev
3. sudo pip3 install pyaudio==0.2.11 --upgrade

**Comment by kalefranz** [comment]
If you have to use `sudo` in front of `pip`, you’re probably doing it wrong.

**Comment by techbhaskar** [comment]
> I'm on a Mac so I did the following and it worked:
> 
> ```
> source activate -my environment name-
> brew install portaudio 
> pip install pyaudio
> ```
> All installed and working! Thanks @tomaso909

How we can do it Windows 7
