### ISSUE TITLE
conda update anaconda failed

### ISSUE THREAD

**Issue by letsop** [conda/conda#5630]
I tried the command 
conda update anaconda
it failed with the following error messages and now "conda" has disapeared

pc42:~ postel$ conda update anaconda
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /Volumes/USER/postel/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sqlite-3.13.0              |                0         1.4 MB
    conda-env-2.6.0            |                0          601 B
    zlib-1.2.8                 |                3          89 KB
    openssl-1.0.2l             |                0         3.0 MB
    yaml-0.1.6                 |                0          79 KB
    tk-8.5.18                  |                0         1.9 MB
    python-2.7.13              |                0         9.1 MB
    enum34-1.1.6               |           py27_0          54 KB
    idna-2.5                   |           py27_0         121 KB
    pycosat-0.6.2              |           py27_0          97 KB
    six-1.10.0                 |           py27_0          16 KB
    pycparser-2.17             |           py27_0         153 KB
    setuptools-27.2.0          |           py27_0         522 KB
    anaconda-custom            |           py27_0           3 KB
    pyparsing-2.1.4            |           py27_0          70 KB
    ipaddress-1.0.18           |           py27_0          30 KB
    requests-2.14.2            |           py27_0         701 KB
    asn1crypto-0.22.0          |           py27_0         145 KB
    ruamel_yaml-0.11.14        |           py27_1         197 KB
    packaging-16.8             |           py27_0          29 KB
    cffi-1.10.0                |           py27_0         195 KB
    cryptography-1.8.1         |           py27_0         468 KB
    pyopenssl-17.0.0           |           py27_0          73 KB
    conda-4.3.22               |           py27_0         494 KB
    ------------------------------------------------------------
                                           Total:        18.9 MB

The following NEW packages will be INSTALLED:

    asn1crypto:   0.22.0-py27_0 
    conda-env:    2.6.0-0       
    enum34:       1.1.6-py27_0  
    idna:         2.5-py27_0    
    ipaddress:    1.0.18-py27_0 
    packaging:    16.8-py27_0   
    ruamel_yaml:  0.11.14-py27_1

The following packages will be UPDATED:

    anaconda:     2.1.0-np19py27_0 --> custom-py27_0 
    cffi:         0.8.6-py27_0     --> 1.10.0-py27_0 
    conda:        3.7.4-py27_0     --> 4.3.22-py27_0 
    cryptography: 0.5.4-py27_0     --> 1.8.1-py27_0  
    openssl:      1.0.1k-0         --> 1.0.2l-0      
    pycosat:      0.6.1-py27_0     --> 0.6.2-py27_0  
    pycparser:    2.10-py27_0      --> 2.17-py27_0   
    pyopenssl:    0.14-py27_0      --> 17.0.0-py27_0 
    pyparsing:    2.0.1-py27_0     --> 2.1.4-py27_0  
    python:       2.7.9-1          --> 2.7.13-0      
    requests:     2.5.1-py27_0     --> 2.14.2-py27_0 
    setuptools:   5.8-py27_0       --> 27.2.0-py27_0 
    six:          1.8.0-py27_0     --> 1.10.0-py27_0 
    sqlite:       3.8.4.1-0        --> 3.13.0-0      
    tk:           8.5.15-0         --> 8.5.18-0      
    yaml:         0.1.4-1          --> 0.1.6-0       
    zlib:         1.2.8-0          --> 1.2.8-3       

Proceed ([y]/n)? y

Fetching packages ...
sqlite-3.13.0- 100% |################################| Time: 0:00:00   1.93 MB/s
conda-env-2.6. 100% |################################| Time: 0:00:00   1.20 MB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00   1.49 MB/s
openssl-1.0.2l 100% |################################| Time: 0:00:01   1.99 MB/s
yaml-0.1.6-0.t 100% |################################| Time: 0:00:00 568.83 kB/s
tk-8.5.18-0.ta 100% |################################| Time: 0:00:01   1.73 MB/s
python-2.7.13- 100% |################################| Time: 0:00:05   1.75 MB/s
enum34-1.1.6-p 100% |################################| Time: 0:00:00 568.07 kB/s
idna-2.5-py27_ 100% |################################| Time: 0:00:00   1.66 MB/s
pycosat-0.6.2- 100% |################################| Time: 0:00:00   1.54 MB/s
six-1.10.0-py2 100% |################################| Time: 0:00:00 759.03 kB/s
pycparser-2.17 100% |################################| Time: 0:00:00 839.26 kB/s
setuptools-27. 100% |################################| Time: 0:00:00   1.96 MB/s
anaconda-custo 100% |################################| Time: 0:00:00   3.20 MB/s
pyparsing-2.1. 100% |################################| Time: 0:00:00   1.35 MB/s
ipaddress-1.0. 100% |################################| Time: 0:00:00 987.68 kB/s
requests-2.14. 100% |################################| Time: 0:00:00   1.82 MB/s
asn1crypto-0.2 100% |################################| Time: 0:00:00   1.67 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   1.59 MB/s
packaging-16.8 100% |################################| Time: 0:00:00   1.04 MB/s
cffi-1.10.0-py 100% |################################| Time: 0:00:00   1.51 MB/s
cryptography-1 100% |################################| Time: 0:00:00   1.73 MB/s
pyopenssl-17.0 100% |################################| Time: 0:00:00   1.24 MB/s
conda-4.3.22-p 100% |################################| Time: 0:00:00   1.71 MB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Volumes/USER/postel/anaconda/bin/conda", line 5, in <module>
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/plan.py", line 589, in execute_actions
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in link
  File "/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/conda/install.py", line 509, in link
  File "/Volumes/USER/postel/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Volumes/USER/postel/anaconda/lib/python2.7/site-packages/enum/doc'

**Comment by nehaljwani** [comment]
Does this fix the problem for you:

`sudo chown -R postel  /Volumes/USER/postel/anaconda`
