### ISSUE TITLE
trying to create env in anaconda 4.4 , tensorflow

### ISSUE THREAD

**Issue by kurt247** [conda/conda#5634]
I followed the instructions on the tensorflow site to install tensorflow in conda env , via Visual Studios .Following error report came up ;
![screenshot 2017-07-03 23 16 31](https://user-images.githubusercontent.com/29505206/27817565-c2608700-6089-11e7-9f6f-b0fc4779aab0.png)

**Comment by nehaljwani** [comment]
It seems like the conda package somehow got corrupt? Does this help:
```cmd
conda install -y conda=4.3.21
conda clean --all -y
conda install conda=4.3.22
```
