### ISSUE TITLE
conda install --revision removed pretty much everything from my conda installation

### ISSUE THREAD

**Issue by drhay53** [conda/conda#5646]
Hello, 

I updated a bunch of packages and wanted to rollback to a previous state. So I looked at my revisions like this:

conda list --revisions

I then located the revision from just before I started doing updates, and tried to revert to that revision...

conda install --revision 15

Which basically removed everything from my anaconda installation, including anaconda itself!

conda list
# packages in environment at /Users/castor/anaconda/envs/zipline:
#
alembic                   0.7.7                    py27_0    Quantopian
cachetools                1.1.6                    py27_0    Quantopian
cyordereddict             0.2.2                    py27_0    Quantopian
intervaltree              2.1.0                    py27_0    Quantopian
logbook                   0.12.5                   py27_0    Quantopian
sortedcontainers          1.4.4                    py27_0    Quantopian

What the heck do I do?

**Comment by kalefranz** [comment]
`conda info` ?

**Comment by kalefranz** [comment]
Fixed in recent versions of conda 4.3 and conda 4.4.
