### ISSUE TITLE
Versioned docs for conda.io

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#5650]
Conda doesn't use ReatTheDoc which is fine - I assume there are good reasons for it, however the conda docs seem to be missing some features as compared to RTD.

Specifically the docs don't seem to be tied to any particular version of `conda`. I assume that [https://conda.io/docs/](https://conda.io/docs/) always just points to the latest stable release, but sometimes you want to read up on new features in unreleased versions, or to actually find the docs for the specific version you're currently running which may not always be the latest stable.

RTD allows you to view the docs for any past version and for the upcoming, unreleased version which is a *very* useful feature. It would be good if the conda docs allowed you to do the same. The most important aspect for me is to be able to (easily) read up about the new features which have been developed but not yet released.

Is that actually correct that those docs aren't published or have I just missed them somewhere?

**Comment by tyler-thetyrant** [comment]
You can view our conda change log [here](https://github.com/conda/conda/blob/master/CHANGELOG.md), which shows new features and other unleased improvements.

**Comment by dhirschfeld** [comment]
A change log and PRs *aren't* the same as prose documentation.

I think this is still a valid request and should be re-opened.
