### ISSUE TITLE
activate()/deactivate() functions should adjust MANPATH

### ISSUE THREAD

**Issue by smontanaro** [conda/conda#5654]
I suspect my request is essentially equivalent to this long ago closed issue: https://github.com/conda/conda/issues/845

Briefly, if the activate and deactivate functions/scripts are going to mess with PATH, they darn well ought to mess with MANPATH in a similar fashion for at least two reasons:

1. If a package installed via "conda install ..." didn't previously exist on the computer, there will be no other place to find suitable man pages.

2. If a package installed via "conda install ..." is newer than whatever the system provided (e.g., you install Python 3.x via Conda on a system where /usr/bin/python is 2.x), the outdated man page will give you misleading information.

This seems like it should be marked "easy," since the logic for manipulating MANPATH should be similar (I think) to the logic for manipulating PATH, but I've been wrong about this sort of thing before.

**Comment by asmeurer** [comment]
As pointed out at https://github.com/conda/conda/issues/845#issuecomment-313822591, one gotcha is that setting MANPATH overrides the default search path, so you'd have to make sure to add that in manually (from the output of `man --path`).

**Comment by smontanaro** [comment]
Well, sure but you override PATH as well, and somehow manage to make that
work. Just prepend the appropriate directory to MANPATH in a manner similar
to PATH. Besides a little breakage (bendage?) wouldn't be nearly as tragic
in this case as muffing PATH.
