### ISSUE TITLE
Trying to follow snakemake tutorial

### ISSUE THREAD

**Issue by michellemli** [conda/conda#5656]
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/michellemli/anaconda3  (writable)
    default environment : /Users/michellemli/anaconda3
       envs directories : /Users/michellemli/anaconda3/envs
                          /Users/michellemli/.conda/envs
          package cache : /Users/michellemli/anaconda3/pkgs
                          /Users/michellemli/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ /Users/michellemli/anaconda3/bin/conda-env create --name snakemake-tutorial --file environment.yaml`

    Traceback (most recent call last):
      File "/Users/michellemli/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/michellemli/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/Users/michellemli/anaconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Invalid name, try the format: user/package
    snakemake-tutorial does not exist or can't be accessed
    Conda Env Exception: environment.yaml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment]
Is `environment.yaml` in the same directory from which you are trying to invoke `conda env create`?
