### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 146: ordinal not

### ISSUE THREAD

**Issue by vcalderon2009** [conda/conda#5657]
When I try to deactivate a virtual environment (Python 3.6), I get the following message.
And then, I need to source /etc/profile to have access to normal commands like `ls`, `cd`, etc.

I get similar messages when I try to update anaconda with 

    conda update conda
    conda update anaconda

Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/victor2/anaconda  (writable)
    default environment : /Users/victor2/anaconda/envs/py3
       envs directories : /Users/victor2/anaconda/envs
                          /Users/victor2/.conda/envs
          package cache : /Users/victor2/anaconda/pkgs
                          /Users/victor2/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/rwest/osx-64
                          https://conda.anaconda.org/rwest/noarch
                          https://conda.anaconda.org/vgauthier/osx-64
                          https://conda.anaconda.org/vgauthier/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/victor2/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Darwin/16.6.0 OSX/10.12.5
                UID:GID : 501:20

`$ ~/anaconda/envs/py3/bin/conda ..deactivate.path bash ~/anaconda/envs/py3`

    Traceback (most recent call last):
      File "/Users/victor2/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 168, in main
        activate.main()
      File "/Users/victor2/anaconda/lib/python2.7/site-packages/conda/cli/activate.py", line 150, in main
        os.environ[str('PATH')], 1)
      File "/Users/victor2/anaconda/lib/python2.7/re.py", line 155, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 146: ordinal not

**Comment by nbara** [comment]
Hey have you solved this since you filed the issue? I'm having the same problem with the latest conda on OSX using `zsh` (works fine with bash)

**Comment by kalefranz** [comment]
At present, the best solution for unicode errors is to use python 3 in the base (i.e. root) environment, or there environment where conda lives, and then to use `conda create` to make python 2 environments.

**Comment by stevelaskaridis** [comment]
I have had the same problem due to non-unicode characters in my prompt (PS1) on zsh. I removed them and works as expected on zsh.

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/6650
