### ISSUE TITLE
windows 7:  ImportError: No module named conda.cli

### ISSUE THREAD

**Issue by xMrAli** [conda/conda#5658]
I just install Anaconda for the first time

Python 2.7 is ok

```
Python 2.7.13 |Continuum Analytics, Inc.| (default, May 11 2017, 13:17:26) 
[MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>
```
my PC is 64 .

But conda in the command line will not work

```
$ conda
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda\Scripts\conda-script.py", line 3, in <module>
    import conda.cli
ImportError: No module named conda.cli
```

**Comment by xMrAli** [comment]
Some wired thing in the system Path:

![2017-07-07 10_03_58-rapid environment editor 9 1 build 936 x64](https://user-images.githubusercontent.com/24437888/27947237-b72a46f2-62fd-11e7-9e26-7332522171fe.jpg)

**Comment by xMrAli** [comment]
Some wired thing in the system Path:

![2017-07-07 10_03_58-rapid environment editor 9 1 build 936 x64](https://user-images.githubusercontent.com/24437888/27947237-b72a46f2-62fd-11e7-9e26-7332522171fe.jpg)

**Comment by nehaljwani** [comment]
Please remove all references to `C:\Python27` from `PATH` and `PYTHONPATH` environment variables.

**Comment by xMrAli** [comment]
any way i install pip and forget about conda.  🚶
