### ISSUE TITLE
conda build spec error

### ISSUE THREAD

**Issue by joachimwolff** [conda/conda#5659]
In a conda meta.yaml file it makes a difference if a dependency in `requirements` is written 

`numpy >= 0.1` or  `numpy >=0.1`. 

The first one fails if executed with `conda build`: `conda.exceptions.InvalidSpecError: Invalid spec: >=`. 

I think one more space or not should not make a difference. 

Can this behaviour be changed?

At the same time, if you define a `requirements.txt` file like 

```
numpy >= 0.1
scipy >= 0.1
```

and you use it with `conda install --file requirements.txt` the one more space is fine.

**Comment by msarahan** [comment]
Issue moved to [conda/conda-build #2162](https://github.com/conda/conda-build/issues/2162) via [**ZenHub**](https://www.zenhub.com/)
