### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:

### ISSUE THREAD

**Issue by webMing** [conda/conda#5662]
when I install  vtk  at command line get this error
UnsatisfiableError: The following specifications were found to be in conflict:
 - python 3.6*
  - vtk -> python 2.7* -> openssl 1.0.1*
Use "conda info <package>" to see the dependencies for each package.

anyone know how to solve ,thank advance

**Comment by nehaljwani** [comment]
AFAIK, there is not python 3.6 build of vtk. Try creating a separate environment with python2 and vtk:
```
conda create -yn vtkenv python=2 vtk
```
Then activate the `vtkenv` environment.

**Comment by webMing** [comment]
this work for me  and I have a question: when i  deactivate env, i found i can`t  import vtk module.

**Comment by nehaljwani** [comment]
Well that's expected, since vtk was installed for that environment only.

**Comment by webMing** [comment]
I have a doubt that when i use  Anaconda IDE   could i  import vtk and it will work well ?
