### ISSUE TITLE
Cannot install to non-root env with pip

### ISSUE THREAD

**Issue by dkirkby** [conda/conda#5666]
Running "pip install <pkg>" is consistently installing <pkg> into the root env, instead of my active env. I have reproduced this from a clean (py3.6) install of anaconda:
```
bash Anaconda3-4.4.0-MacOSX-x86_64.sh
```
Next, from a new shell:
```
conda create -n test
source activate test
pip install speclite
```
These commands appear to work, however the package is not listed when I run:
```
conda list -n test speclite
```
but is listed by:
```
conda list -n root speclite
```
I find the same behavior with every package I have tried so far.

I am hoping this is just user error since I am new to conda envs, but this is not the behavior I expected.

**Comment by dkirkby** [comment]
A further sanity check:
```
~% which python pip
/Users/david/anaconda3/bin/python
/Users/david/anaconda3/bin/pip
```

**Comment by mingwandroid** [comment]
You didn't install pip into your test env.
