### ISSUE TITLE
Rasterio import fails for environments created with rasterio

### ISSUE THREAD

**Issue by hsparra** [conda/conda#5671]
On CentOS 6, creating an environment for rasterio fails:
```
conda create -n rasterio rasterio
source activate rasterio
python -c "import rasterio" 
```
This results in
```
ImportError: libjpeg.so.8: cannot open shared object file: No such file or direct
```
A similar error occurs on OS X, `Library not loaded: @rpath/libmfhdf.0.dylib`

**Comment by hsparra** [comment]
Any updates on this?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6752
