### ISSUE TITLE
Local Conda installation failing due to permissions on shared hosting

### ISSUE THREAD

**Issue by abalter** [conda/conda#5676]
I can't seem to get any help with this on  [stackoverflow](https://stackoverflow.com/questions/45018272/local-conda-installation-failing-due-to-permissions-on-shared-hosting) or the [google group](https://groups.google.com/a/continuum.io/forum/#!topic/conda/IJg6etdzM3c).

I had thought I could create an isolated, local installation. But it turns out you seem to need links to system packages belonging to root. I think this is the essence of [this question](https://stackoverflow.com/questions/41640056/do-conda-environments-have-access-to-root-environment-system-packages), which remains unanswered.

I've been using conda quite a bit with non-root installs on servers. Right now, I'm trying to install it on a Bluehost shared server. They have recently changed the ssh shell to a jailshell that does not allow linking to system packages. I did not realize this would be an obstacle. However...

    [/home7/arielbal/miniconda3] >>> /home7/arielbal/test/conda
    PREFIX=/home7/arielbal/test/conda
    installing: python-3.6.1-2 ...
    tar: bin/2to3: Cannot create symlink to `2to3-3.6': Permission denied
    tar: bin/idle3: Cannot create symlink to `idle3.6': Permission denied
    tar: bin/pydoc: Cannot create symlink to `pydoc3.6': Permission denied
    tar: bin/pydoc3: Cannot create symlink to `pydoc3.6': Permission denied
    tar: bin/python: Cannot create symlink to `python3.6': Permission denied
    tar: bin/python3: Cannot create symlink to `python3.6': Permission denied
    tar: bin/python3-config: Cannot create symlink to `python3.6m-config': Permission denied
    tar: bin/python3.6-config: Cannot create symlink to `python3.6m-config': Permission denied
    tar: bin/pyvenv: Cannot create symlink to `pyvenv-3.6': Permission denied
    tar: lib/libpython3.6m.so: Cannot create symlink to `libpython3.6m.so.1.0': Permission denied
    tar: share/man/man1/python3.1: Cannot create symlink to `python3.6.1': Permission denied
    tar: Exiting with failure status due to previous errors

Bluehost does allow compiling (unlike greengeeks.com), so I actually went through the trouble of compiling the dependencies to get the initial miniconda install. I was eventually able to get that to work. But when I tried to install further packages, I again ran into permissions/linking issues.

Is there a way to create a local install conda in a completely portable way that will handle all dependencies not currently linkable on the system?

**Comment by kalefranz** [comment]
I don't see how evidence that 

>  it turns out you seem to need links to system packages belonging to root.

from the above output.  What it looks like to me is that you're not allowed to create symlinks at all on the system.  Most linux conda packages contain symlinks to other paths within themselves.

It looks like your line

    [/home7/arielbal/miniconda3] >>> /home7/arielbal/test/conda

is meant to be invoking the miniconda installer, but the output that follows.  However I don't understand how.

Have you resolved your issue by now?  If not, we're going to need more information.
