### ISSUE TITLE
Incremental modification of repodata/index

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5678]
@stefanseefeld asked me to submit this issue.  We have discussed this before at length.  Conda-build needs to completely rebuild its index after any package is built, so that that package is then installable for the test phase.  It would be a large optimization to conda-build if conda were able to modify the existing index to add the new package, rather than re-generate the entire index.

Some more info (possibly outdated) here:

This happens in two parts.  The first adds the package to the on-disk repodata.json file: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L755
MichaelS
The second re-reads the on-disk repodata.json into the memory object: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1239
MichaelS
It would be ideal to replace the second part with a small modification to the in-memory index during the first part.

**Comment by stefanseefeld** [comment]
Note to self: the way to implement the above is to fill in the `RepoData.add` method (https://github.com/conda/conda/blob/master/conda/core/repodata.py#L139).

**Comment by kalefranz** [comment]
I think with conda 4.4 (and tracking down that one issue right before we released 4.4 to defaults), repodata handling is pretty performant now.  If anything, we should someday walk through our API user stories again, and see where conda-build starts to use newer APIs that are becoming pretty solid now.
