### ISSUE TITLE
support for package containers (eg. wheel)

### ISSUE THREAD

**Issue by marscher** [conda/conda#5679]
If one installs conda to a network filesystem, imports take a long time, because the installation method of conda enforces unpacking everything. This problem has already been solved by the wheel and egg zip file formats, which avoid the overhead of reading thousands of individual files. The Java world has jars for this purpose. So I got some questions.
* Is there any good reason to enforce unpacking wheels in the first place?
* Is wheel interfering with the meta-data concept of conda in any way? Duplicating the info wouldn't be a problem, would it?
* Do you think it would be hard to implement? (eg. just omit the unzip step and just copy the archive file to site-packages)

Thanks in advance for your feedback on this. I hope it is not a duplicate (githubs search feature is kinda limited, sorry).

**Comment by kalefranz** [comment]
Right, java has jars.  Python has (err, had) eggs.  These are technologies of the language ecosystem.  Conda is just responsible for installing what the interpreter/runtime wants.  So you're poking at the wrong level of the software stack with your request on this one...
