### ISSUE TITLE
conda env create gives confusing message if environment file does not exist

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5681]
Try executing `conda env create -f does_not_exist.txt`.  The output I get is:

```
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name
```

That is not super useful or meaningful.  I'd suggest it should say something obvious, like:

```
File not found: does_not_exist.txt
```

**Comment by nehaljwani** [comment]
Related: https://github.com/conda/conda/issues/5621

**Comment by kalefranz** [comment]
From https://github.com/conda/conda/issues/5621#issue-240019026

> IIUC, the function [build_message()](https://github.com/conda/conda/blob/master/conda_env/specs/__init__.py#L26-L31) gives precedence to binstar spec and over others, which is why this happens.
