### ISSUE TITLE
conda update --all only wants to downgrade

### ISSUE THREAD

**Issue by ethankruse** [conda/conda#5683]
I'm not really sure what's going on here, but when I run `conda update --all`, I get this:
```
The following packages will be UPDATED:

    basemap:      1.0.7-np113py27_0   --> 1.0.7-np111py27_0  
    h5py:         2.7.0-np113py27_0   --> 2.7.0-np111py27_0  
    numexpr:      2.6.2-np113py27_0   --> 2.6.2-np111py27_0  
    pyopengl:     3.1.1a1-np113py27_0 --> 3.1.1a1-np111py27_0
    pytables:     3.3.0-np113py27_0   --> 3.3.0-np111py27_0  
    pywavelets:   0.5.2-np113py27_0   --> 0.5.2-np111py27_0  
    scikit-image: 0.13.0-np113py27_0  --> 0.13.0-np111py27_0 
    scikit-learn: 0.18.1-np113py27_1  --> 0.18.1-np111py27_1 
    scipy:        0.19.0-np113py27_0  --> 0.19.0-np111py27_0 
    statsmodels:  0.8.0-np113py27_0   --> 0.8.0-np111py27_0  

The following packages will be DOWNGRADED:

    astropy:      2.0-np113py27_0     --> 1.3.3-np111py27_0  
    geos:         3.5.0-0             --> 3.4.2-0            
    matplotlib:   2.0.2-np113py27_0   --> 1.5.1-np111py27_0  
    numpy:        1.13.1-py27_0       --> 1.11.3-py27_0      
    pandas:       0.20.2-np113py27_0  --> 0.20.1-np111py27_0 
    pyqt:         5.6.0-py27_2        --> 4.11.4-py27_4      
    qt:           5.6.2-4             --> 4.8.7-4            
    qtconsole:    4.3.0-py27_0        --> 4.2.1-py27_0   
```
So basically it just wants to downgrade lots of packages and revert to numpy 1.11, which for whatever reason is treated as an 'upgrade' to its dependent packages.

I've been searching everywhere, but is there some way to check if something is wrong in my environment? Looking at the verbose output, there's a line that says
`DEBUG conda.resolve:bad_installed(740): Checking if the current environment is consistent`, followed by 2 lines that aren't there in an environment that is consistent:
```
DEBUG conda.logic:minimize(557): Final sum objective: 3
DEBUG conda.logic:minimize(569): New peak objective: 1
```

Maybe I have some inconsistencies somewhere?

Any tips would be appreciated, and I'm sorry if this is the wrong place for this.

**Comment by tyler-thetyrant** [comment]
That is conda's solver at work. To satisfy all packages' dependency requirements, it is inevitable to downgrade some packages so that your environment/packages don't break.
