### ISSUE TITLE
python messy code in conda 

### ISSUE THREAD

**Issue by ningzhilin** [conda/conda#5685]
When I use directionkeys  in python interactive interface in conda, there shows a messy code like this:

-bash-4.1$ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> ^[[A^[[A^[[A^[[B^[[B

I think maybe I should install some packages?
How should I do?

Thank you very much!!~~

**Comment by kalefranz** [comment]
You probably need readline, but this isn't the appropriate issue tracker to get such help.
