### ISSUE TITLE
MD5Sum Error

### ISSUE THREAD

**Issue by smeagan** [conda/conda#5686]
Whenever I try to update Anaconda, I get this error with respect to numpy and the entire update stops. Currently have numpy 1.12.0. I can force update numpy to 1.13, but if/when I try to update other packages/anaconda, it wants to downgrade numpy to 1.12.1 and the result is always as follows.

CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.continuum.io/pkgs/free/win-64/numpy-1.12.1-py35_0.tar.bz2'.
  download saved to: C:\Anaconda3\pkgs\numpy-1.12.1-py35_0.tar.bz2
  expected md5 sum: e3ce359a591360ca8b6f9622a4abca9f
  actual md5 sum: 6c4e21a0bb26d9c99576fec3cc92fa71

**Comment by kalefranz** [comment]
Appears good now

```
$ curl -sS https://repo.continuum.io/pkgs/free/win-64/numpy-1.12.1-py35_0.tar.bz2 | md5
e3ce359a591360ca8b6f9622a4abca9f
```

Use `conda clean --tarballs` if you still have the error.
