### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by terrence5** [conda/conda#5689]
**# I am trying to install Fenics on Anaconda. Using "./conda create -n fenicsproject -c conda-forge fenics" like the website instructs but I get this error message:**

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /scratch/home/terrence/.conda/envs/fenicsproject/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /scratch/home/terrence/.conda/envs/fenicsproject/bin/.gcc-post-link.sh
==> script messages <==
<None>

****When I run with '-v' it gives me this info:**

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /scratch/software/anaconda  (read only)
    default environment : /scratch/software/anaconda
       envs directories : /scratch/home/terrence/.conda/envs
                          /scratch/software/anaconda/envs
          package cache : /scratch/software/anaconda/pkgs
                          /scratch/home/terrence/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/2.6.32-431.11.2.el6.x86_64 CentOS/6.5 glibc/2.12
                UID:GID : 1053:100

`$ ./conda create -n fenicsproject -c conda-forge fenics -v`

    Traceback (most recent call last):
      File "/scratch/software/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/scratch/software/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/scratch/software/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/scratch/software/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 136, in install
        check_prefix(prefix, json=context.json)
      File "/scratch/software/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 48, in check_prefix
        raise CondaValueError(error, json)
    conda.exceptions.CondaValueError: prefix already exists: /scratch/home/terrence/.conda/envs/fenicsproject

**Any ideas or any help would be greatly appreciated**

**Comment by Racial** [comment]
I have met the same question. I want to ask if you have dealt with it? Thank you

**Comment by kalefranz** [comment]
You have two different issues here.  The first appears to be a packaging problem with the post-link script in a gcc package.  If the issue persists, file a new issue at github.com/ContinuumIO/anaconda-issues.  The second problem you have is that an environment named `fenicsproject` already exists, and so you need to you `conda install` instead of `conda create` to install into that existing environment.
