### ISSUE TITLE
An unexpected error has occured (while creating a env on Ubuntu)

### ISSUE THREAD

**Issue by Vivbhav** [conda/conda#5690]
I downloaded the latest version of Anaconda today 4.3.22. I was creating an environment from a .yaml file when I got this error. 

nb_conda-2.0.0 100% |################################################################################| Time: 0:00:00 805.29 kB/s
_nb_ext_conf-0 100% |################################################################################| Time: 0:00:00   1.93 MB/s
nbpresent-3.0. 100% |################################################################################| Time: 0:00:01 321.82 kB/s
**An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:**

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/vivek/Documents/self/anaconda3  (writable)
    default environment : /home/vivek/Documents/self/anaconda3
       envs directories : /home/vivek/Documents/self/anaconda3/envs
                          /home/vivek/.conda/envs
          package cache : /home/vivek/Documents/self/anaconda3/pkgs
                          /home/vivek/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-83-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/vivek/Documents/self/anaconda3/bin/conda-env create -f udacity.yaml`

    Traceback (most recent call last):
      File "/home/vivek/Documents/self/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/vivek/Documents/self/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/vivek/Documents/self/anaconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: can only concatenate list (not "NoneType") to list

**Comment by tyler-thetyrant** [comment]
can you just try with `canda create` instead of `conda-env create` ?

**Comment by solomonsunder** [comment]
I think the issue #6208 that I created is a duplicate of this. This issue still persists.

conda-env create this command is not the one I am using. It just appears on the error message. A bit new to conda, so you can tell the entire new command that I am supposed to try.
canda create or conda create also don't work.

conda env create -f dand-env-linux.yaml

The above command is the one I used.
