### ISSUE TITLE
Feature request: Specify channel in yaml file?

### ISSUE THREAD

**Issue by hainm** [conda/conda#5693]
Hi,

Is it a good idea to add that? Example

```python
name: IOOS3
dependencies:
  - python=3.6
  - bagit
  - beautifulsoup4 # -c conda-forge
```

PS: I know we can set that via
```python
channels:
  - conda-forge
  - XYZ
``` 
but this is not really great if I want package "A" from channel "XYZ" rather "conda-channel".

**Comment by hainm** [comment]
Related topic: https://groups.google.com/a/continuum.io/forum/#!topic/conda/AH1AzpJMAsc

**Comment by adam-urbanczyk** [comment]
Any updates on the topic? This feature would be indeed very nice from the point of view of environment reproducibility.

**Comment by kalefranz** [comment]
The `environment.yml` file now supports the `::` syntax for specifying channels.  For example

```
dependencies:
  - python=3.6
  - bagit
  - conda-forge::beautifulsoup4
```

**Comment by hainm** [comment]
Beautiful, thanks.

**Comment by sigvaldm** [comment]
Quick question: from which version is this supported?

**Comment by cjw296** [comment]
@kalefranz - where is this documented?
