### ISSUE TITLE
Problem while installing OpenCV 3.2.0

### ISSUE THREAD

**Issue by jroberayalas** [conda/conda#5695]
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.19.0
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/JRAS/.condarc
           offline mode : False

`$ /Applications/anaconda/bin/conda install -c conda-forge opencv=3.2.0`

    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 217

**Comment by tyler-thetyrant** [comment]
We are currently at conda version 4.3.22. 
Can you try with the most recent version of conda?

**Comment by tyler-thetyrant** [comment]
Closing since the lack of response and that I wasn't able to reproduce the issue with the most recent version of conda on osx-64 platform.

**Comment by jroberayalas** [comment]
Sorry for the delay. The most recent version of conda solved the problem. Many thanks!
