### ISSUE TITLE
Conda plugins and argparse

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5696]
I had posted [this query](https://groups.google.com/a/continuum.io/forum/#!topic/conda/wsf_L_MtwOw) on the mailing list a while ago, and was asked by @msarahan to start a discussion here.

As of conda v4.4.0beta1:
```
(root) [root@a14d37a9b31f ~]# conda-<lets_hit_tab>
conda-build        conda-develop      conda-index        conda-metapackage  conda-skeleton     
conda-convert      conda-env          conda-inspect      conda-render       conda-verify       
```
Now, IIUC, typing `conda<space>{any_subcommand_from_above}` will execute that file and the code path for this is at [conda/cli/conda_argparse.py](https://github.com/conda/conda/blob/4.4.0beta1/conda/cli/conda_argparse.py#L46-L71), inside the function: `ArgumentParser.error`

So, is it safe to assume that if I create an executable by the name conda-$something and make sure that it is present in `/path/to/conda/activated/env/bin/`, this functionality will be supported in the future, thereby enabling me to type:
```
(root) [root@a14d37a9b31f ~]# conda<space>$something
```
If this functionality is guaranteed to exist in the future, this makes creating custom sub-commands (plugins?) for conda very easy. One will just have to create a conda package and make sure it is installed in the activated environment.

**Comment by kalefranz** [comment]
> So, is it safe to assume that if I create an executable by the name conda-$something and make sure that it is present in /path/to/conda/activated/env/bin/, this functionality will be supported in the future

Yes.
