### ISSUE TITLE
pre/post script failures appear to be fatal but only produce WARNING

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5700]
While looking into #5417 I have discovered that the `pre-unlink.sh` script's failure is actually causing the entire update to bork out, but I am not given any indication that this has happened.

Here is the fragment showing the `WARNING` followed by (effective) failure:

```
Proceed ([y]/n)? y

pysocks-1.6.6- 100% |#############################################################| Time: 0:00:00   1.73 MB/s
urllib3-1.21.1 100% |#############################################################| Time: 0:00:00   4.76 MB/s
widgetsnbexten 100% |#############################################################| Time: 0:00:00   3.63 MB/s
WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py36_0
consider notifying the package maintainer
(root) twitter $
```

And also strangely it appears that either the unlink phase and package downloads are concurrent or unlinks are done one-at-a-time with each download, because on my first invocation of the update command 3 packages were downloaded before the pre-unlink script failure caused the process to abort, but when I immediately re-issued it more downloads occurred and the command completed successfully.  I would have expected all the downloads to complete before conda started running `pre-unlink.sh` scripts.  If that is a reasonable expectation then perhaps there is another issue that should also be reported.

Attached is the trace of executing exactly the same command (`conda update -n spark --all`) 3 times in succession:

[warning_trace.txt](https://github.com/conda/conda/files/1159906/warning_trace.txt)

First time: downloads 3 packages and then fails on `pre-unlink.sh` with a WARNING.  Unclear that the update failed.

Second time: many more packages downloaded, appears to complete successfully.

Third time: confirms that the second invocation worked: no new packages to install/update.

**Comment by kalefranz** [comment]
I've looked at the current code, and this no longer looks like a hard failure, but indeed just a warning.
