### ISSUE TITLE
jupyter notebook not getting installed

### ISSUE THREAD

**Issue by DebasishSR** [conda/conda#5702]
I am installing Anaconda3-4.4.0 in windows 10 machine. Entire suite is getting installed except Jupyter notebook and rstudio. Hence from command prompt, when I type jupyter notebook, it is unable to find it.

I opened Anaconda navigator & from there separately tried to install jupyter notebook. Installation started & at right end down corner blue coloured scroll bar started shoing some progress. But after sometime, it seem that it got stuck there as it effectively show no progress & endlessly went on. I force-closed the Anaconda navigator window & re-started it & again tried to install but again it kept trying for endless period & finally no result.

Any clue ?

I tried now --> 'conda install jupyter' command in Anaconda command prompt. Got the below error test -
Fetching package metadata ...
CondaHTTPError: HTTP None None for url https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F09B0D8208>, 'Connection to repo.continuum.io timed out. (connect timeout=9.15)'))",),)

**Comment by kalefranz** [comment]
This is an http timeout, likely due to a slow or flakey internet connection.  You can extend the timeouts via configuration options.

```
# remote_connect_timeout_secs (float)
#   The number seconds conda will wait for your client to establish a
#   connection to a remote url resource.
#
# remote_connect_timeout_secs: 9.15

# remote_read_timeout_secs (float)
#   Once conda has connected to a remote resource and sent an HTTP
#   request, the read timeout is the number of seconds conda will wait for
#   the server to send a response.
#
# remote_read_timeout_secs: 60.0
```
