### ISSUE TITLE
feature request: "conda download package" 

### ISSUE THREAD

**Issue by hainm** [conda/conda#5704]
What do you think? 
This should be similar to `pip download package`

PS: I searched ""conda download" in issues but getting > 280 restuls, not sure if this post is duplicated.

**Comment by kalefranz** [comment]
Implemented via #5988 in conda 4.4 with a `--download-only` flag.  Duplicate of #5983.

**Comment by hainm** [comment]
thanks. 

> Duplicate of #5983.

actually this issue is opened before that issue.
