### ISSUE TITLE
conda install package on RHEL 5.5 but not strings /lib64/libc.so.6 

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [conda/conda#5707]
Dear all
I install conda with bwa and I have this error:
```
 bwa
bwa: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by bwa)
```

It was able to install python 3.5 and other software. why not glibc?

**Comment by nehaljwani** [comment]
What's the name of this package? From which conda channel did you install this package?

**Comment by bioinfo-dirty-jobs** [comment]
Thanks so. Much.. The package are installed it is bwa from bioconda

Il 22/Lug/2017 07:13, "Nehal J Wani" <notifications@github.com> ha scritto:

**Comment by nehaljwani** [comment]
IIRC, bioconda folks compile all their packages on CenOS6 so this can happen. RHEL5 is EoL, so I would recommend you to move forward. If you still want to use this package, you can try compiling it from the recipe itself, which is available at https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bwa

In any case, this is not an issue with conda itself or the packages provided on the defaults channel. Also, you have already raised an issue at https://github.com/bioconda/bioconda-recipes/issues/5308 . So I am going to close this.
