### ISSUE TITLE
conda-build 2.1.13 bug in conda_build/utils.py:231

### ISSUE THREAD

**Issue by hsparra** [conda/conda#5710]
Steps to reproduce:
- Install miniconda+conda-build in path /opt/proj1@tmp/miniconda
- Create a conda-project in /opt/proj1
- attempt to conda build /opt/proj1

**Comment by msarahan** [comment]
is conda-project an Anaconda Project?  I don't know what conda-build should do with that.

You are also out-of-date on your conda-build issue.  I can't support old versions.  If you update to 2.1.17 or 3.0.8 and still have issues, I'm happy to help.

This is the wrong tracker for this issue, also.  Moving to conda-build.

**Comment by msarahan** [comment]
Issue moved to [conda/conda-build #2228](https://github.com/conda/conda-build/issues/2228) via [**ZenHub**](https://www.zenhub.com/)

**Comment by hsparra** [comment]
It is actually just a directory containing an environment.yml.
