### ISSUE TITLE
conda search doesn't respect --override-channels

### ISSUE THREAD

**Issue by gabm** [conda/conda#5717]
When i run `conda search -c defaults --override-channels <package-name>`  it finds packages from my private repos as well.. is conda-search supposed to ignore these parameters @kalefranz ?

**Comment by tyler-thetyrant** [comment]
`--override-channels` flag does not search default sor .condarc channels. It also requires  `-c` or `--channel` flag to set a different channel that conda will search through.

**Comment by gabm** [comment]
this is my understanding... it should not search the .condarc channels - but that is what in fact happens

**Comment by tyler-thetyrant** [comment]
ooh I see what you meant originally. Once #5597 gets merged, I'll make another pr to address this in 4.4.x

**Comment by bgruening** [comment]
@tyler-thetyrant did you had time to fix this in 4.4?

**Comment by kalefranz** [comment]
I've just tested this in conda 4.4, and `--override-channels` looks to be working correctly with `conda search`.
