### ISSUE TITLE
Conda Installation Issue

### ISSUE THREAD

**Issue by kranthisai** [conda/conda#5725]
I installed miniconda following the docs. However when I type conda --version in the terminal, I will not get any output. Also no output for conda list .

 I can see the following appended in the .bashrc 

# added by Miniconda2 4.3.21 installer 
export PATH="/home/kranthi/miniconda2/bin:$PATH"

**Comment by tyler-thetyrant** [comment]
Have you tried restarting your terminal?

**Comment by kranthisai** [comment]
yes.

**Comment by kranthisai** [comment]
moved to docker. closing the issue
