### ISSUE TITLE
parameters in outputs script section causes error

### ISSUE THREAD

**Issue by tomashek** [conda/conda#5734]
When attempting to use a script with parameters in the "outputs" section, an error is raised:

meta.yaml relevant section:
```
outputs:
  - name: mkl-include
    script: setup.py --fileset mkl-include
```

FileNotFoundError: [Errno 2] No such file or directory: '/localdisk/work/buildstack/mkl-recipe/setup.py --fileset mkl-include'

It appears that parameters are not allowed for scripts in this section. Allowing parameters will make certain configurations simpler, so please add this feature.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2240
