### ISSUE TITLE
`conda ---version` fails

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#5742]
```
conda ---version
usage: conda [-h] [-V] command ...
conda: error: the following arguments are required: command
```

**Comment by tyler-thetyrant** [comment]
`conda --version` works fine in both 4.3 and 4.4
```

**Comment by tyler-thetyrant** [comment]
conda 4.3. and 4.4 gives the identical error with `---version`

**Comment by kalefranz** [comment]
This is what argparse does I guess.  I don't think there's anything we want to do here.
