### ISSUE TITLE
installing numpy

### ISSUE THREAD

**Issue by skimura04** [conda/conda#5746]
I get the following output when I attempted to install numpy by "conda install -c conda-forge numpy".
Could anyone give me a hint on what I have been doing wrong?

Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.16
       conda is private : False
      conda-env version : 4.2.16
    conda-build version : 1.3.5
         python version : 2.7.12.final.0
       requests version : 2.14.2
       root environment : /Users/skimura/mysoftware/anaconda  (writable)
    default environment : /Users/skimura/mysoftware/anaconda
       envs directories : /Users/skimura/mysoftware/anaconda/envs
          package cache : /Users/skimura/mysoftware/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/skimura/mysoftware/anaconda/bin/conda install -c conda-forge numpy`

    Traceback (most recent call last):
      File "/Users/skimura/mysoftware/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 485, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/skimura/mysoftware/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/Users/skimura/mysoftware/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/skimura/mysoftware/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/skimura/mysoftware/anaconda/pkgs/openblas-0.2.20-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by tyler-thetyrant** [comment]
You are using a very outdated version of conda. Please update to your conda by using`conda update conda` or reinstall miniconda to the latest version. I believe there will be no problem installing numpy with conda 4.3.x
