### ISSUE TITLE
can't install using conda

### ISSUE THREAD

**Issue by nir997** [conda/conda#5755]
i can't install some packages  through this code 
       conda install numpy pyyaml mkl setuptools cmake gcc cffi 
this is what i get when i tried to install it using the above command.
how to solve this ?
  thanks in advance :)

Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/anaconda3:

The following NEW packages will be INSTALLED:

    bzip2:        1.0.6-3           
    cloog:        0.18.0-0          
    cmake:        3.6.3-0           
    gcc:          4.8.5-7           
    gmp:          6.1.0-0           
    isl:          0.12.2-0          
    mpc:          1.0.3-0           
    mpfr:         3.1.5-0           
    ncurses:      5.9-10            

The following packages will be UPDATED:

    anaconda:     4.4.0-np112py36_0  --> custom-py36_0     
    astropy:      1.3.2-np112py36_0  --> 2.0-np113py36_0   
    bottleneck:   1.2.1-np112py36_0  --> 1.2.1-np113py36_0 
    h5py:         2.7.0-np112py36_0  --> 2.7.0-np113py36_0 
    llvmlite:     0.18.0-py36_0      --> 0.19.0-py36_0     
    matplotlib:   2.0.2-np112py36_0  --> 2.0.2-np113py36_0 
    mkl:          2017.0.1-0         --> 2017.0.3-0        
    numba:        0.33.0-np112py36_0 --> 0.34.0-np113py36_0
    numexpr:      2.6.2-np112py36_0  --> 2.6.2-np113py36_0 
    numpy:        1.12.1-py36_0      --> 1.13.1-py36_0     
    pandas:       0.20.1-np112py36_0 --> 0.20.3-py36_0     
    pytables:     3.3.0-np112py36_0  --> 3.3.0-np113py36_0 
    pywavelets:   0.5.2-np112py36_0  --> 0.5.2-np113py36_0 
    scikit-image: 0.13.0-np112py36_0 --> 0.13.0-np113py36_0
    scikit-learn: 0.18.1-np112py36_1 --> 0.18.2-np113py36_0
    scipy:        0.19.0-np112py36_0 --> 0.19.1-np113py36_0
    statsmodels:  0.8.0-np112py36_0  --> 0.8.0-np113py36_0 

Proceed ([y]/n)? y

()

===> UNLINKING PACKAGE: defaults::anaconda-4.4.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::astropy-1.3.2-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::bottleneck-1.2.1-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::h5py-2.7.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::llvmlite-0.18.0-py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::matplotlib-2.0.2-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::mkl-2017.0.1-0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::numba-0.33.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::numexpr-2.6.2-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::numpy-1.12.1-py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::pandas-0.20.1-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::pytables-3.3.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::pywavelets-0.5.2-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::scikit-image-0.13.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::scikit-learn-0.18.1-np112py36_1 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::scipy-0.19.0-np112py36_0 <===
  prefix=/home/anaconda3

===> UNLINKING PACKAGE: defaults::statsmodels-0.8.0-np112py36_0 <===
  prefix=/home/anaconda3

===> LINKING PACKAGE: defaults::bzip2-1.0.6-3 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/bzip2-1.0.6-3

===> LINKING PACKAGE: defaults::gmp-6.1.0-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/gmp-6.1.0-0

===> LINKING PACKAGE: defaults::mkl-2017.0.3-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/mkl-2017.0.3-0

===> LINKING PACKAGE: defaults::ncurses-5.9-10 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/ncurses-5.9-10

===> LINKING PACKAGE: defaults::isl-0.12.2-0 <===
  prefix=/home//anaconda3
  source=/home/anaconda3/pkgs/isl-0.12.2-0

===> LINKING PACKAGE: defaults::mpfr-3.1.5-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/mpfr-3.1.5-0

===> LINKING PACKAGE: defaults::anaconda-custom-py36_0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/anaconda-custom-py36_0

===> LINKING PACKAGE: defaults::cloog-0.18.0-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/cloog-0.18.0-0

===> LINKING PACKAGE: defaults::cmake-3.6.3-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/cmake-3.6.3-0

===> LINKING PACKAGE: defaults::llvmlite-0.19.0-py36_0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/llvmlite-0.19.0-py36_0

===> LINKING PACKAGE: defaults::mpc-1.0.3-0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/mpc-1.0.3-0

===> LINKING PACKAGE: defaults::numpy-1.13.1-py36_0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/numpy-1.13.1-py36_0

===> LINKING PACKAGE: defaults::bottleneck-1.2.1-np113py36_0 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/bottleneck-1.2.1-np113py36_0

===> LINKING PACKAGE: defaults::gcc-4.8.5-7 <===
  prefix=/home/anaconda3
  source=/home/anaconda3/pkgs/gcc-4.8.5-7

$ /bin/bash -x /home/anaconda3/bin/.gcc-post-link.sh
==> cwd: /home/anaconda3/bin <==
==> exit code: 1 <==
==> stdout <==
b"gcc install OS matches gcc build OS: Skipping post-link portability fixes.\nInstallation failed: gcc is not able to compile a simple 'Hello, World' program.\n"
==> stderr <==
b'++ uname\n/home/anaconda3/bin/.gcc-post-link.sh: line 3: uname: command not found\n+ \'[\' \'\' == Darwin \']\'\n+ build_os_md5=($(md5sum "${PREFIX}/share/conda-gcc-build-machine-os-details"))\n++ md5sum /home/anaconda3/share/conda-gcc-build-machine-os-details\n/home/anaconda3/bin/.gcc-post-link.sh: line 9: md5sum: command not found\n+ target_os_md5=($(lsb_release -a | md5sum))\n++ lsb_release -a\n/home/anaconda3/bin/.gcc-post-link.sh: line 10: lsb_release: command not found\n++ md5sum\n/home/anaconda3/bin/.gcc-post-link.sh: line 10: md5sum: command not found\n+ [[ \'\' == \'\' ]]\n+ echo \'gcc install OS matches gcc build OS: Skipping post-link portability fixes.\'\n++ mktemp -d XXXXXXXXXX\n/home/anaconda3/bin/.gcc-post-link.sh: line 124: mktemp: command not found\n+ workdir=\n+ cat\n/home/anaconda3/bin/.gcc-post-link.sh: line 127: cat: command not found\n+ cat\n/home/anaconda3/bin/.gcc-post-link.sh: line 136: cat: command not found\n+ set +e\n+ set -e\n+ /home//anaconda3/bin/gcc -o hello_c.out hello.c\ngcc: error trying to exec \'as\': execvp: Not a directory\n+ SUCCESS=1\n+ \'[\' 1 -ne 0 \']\'\n+ echo \'Installation failed: gcc is not able to compile a simple \'\\\'\'Hello, World\'\\\'\' program.\'\n+ cd ..\n+ rm -r \'\'\n/home//anaconda3/bin/.gcc-post-link.sh: line 156: rm: command not found\n+ exit 1\n'

An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/anaconda3/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

===> REVERSING PACKAGE LINK: defaults::gcc-4.8.5-7 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::bottleneck-1.2.1-np113py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::numpy-1.13.1-py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::mpc-1.0.3-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::llvmlite-0.19.0-py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::cmake-3.6.3-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::cloog-0.18.0-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::anaconda-custom-py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::mpfr-3.1.5-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::isl-0.12.2-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::ncurses-5.9-10 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::mkl-2017.0.3-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::gmp-6.1.0-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE LINK: defaults::bzip2-1.0.6-3 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::statsmodels-0.8.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::scipy-0.19.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::scikit-learn-0.18.1-np112py36_1 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::scikit-image-0.13.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::pywavelets-0.5.2-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::pytables-3.3.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::pandas-0.20.1-np112py36_0 <===
  prefix=/home//anaconda3

===> REVERSING PACKAGE UNLINK: defaults::numpy-1.12.1-py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::numexpr-2.6.2-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::numba-0.33.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::mkl-2017.0.1-0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::matplotlib-2.0.2-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::llvmlite-0.18.0-py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::h5py-2.7.0-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::bottleneck-1.2.1-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::astropy-1.3.2-np112py36_0 <===
  prefix=/home/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::anaconda-4.4.0-np112py36_0 <===
  prefix=/home/anaconda3
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/anaconda3  (writable)
    default environment : /home/anaconda3
       envs directories : /home/anaconda3/envs
                          /home/conda/envs
          package cache : /home/anaconda3/pkgs
                          /home/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.14.2 CPython/3.6.1 Linux/4.8.0-36-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/anaconda3/bin/conda install numpy pyyaml mkl setuptools cmake gcc cffi `

    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/home/anaconda3/lib/python3.6/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/home/anaconda3/bin/.gcc-post-link.sh']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/homeanaconda3/lib/python3.6/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/home/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::gcc-4.8.5-7
    running your command again with `-v` will provide additional information
    location of failed script: /home/anaconda3/bin/.gcc-post-link.sh
    ==> script messages <==
    <None>
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::gcc-4.8.5-7
    running your command again with `-v` will provide additional information
    location of failed script: /home/anaconda3/bin/.gcc-post-link.sh
    ==> script messages <==
    <None>
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 323, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/home/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondamMultiError: post-link script failed for package defaults::gcc-4.8.5-7
    running your command again with `-v` will provide additional information
    location of failed script: /home/anaconda3/bin/.gcc-post-link.sh
    ==> script messages <==
    <None>

**Comment by nehaljwani** [comment]
Try installing gcc using the linux distro package manager (apt or yum/dnf or any other) and then try the above conda install command. See if that helps?

**Comment by kalefranz** [comment]
post-link error for the gcc package, which means this is a packaging issue.
