### ISSUE TITLE
conda install does not resolve pinned transitive dependencies

### ISSUE THREAD

**Issue by kynan** [conda/conda#5757]
Consider the following scenario: my conda env already has package `A` at version `x`. I `conda install D`, which depends on `C`, which depends on `B`, which depends on `A` pinned at version `y > x`. There is no conflict of `A` version `y` with any other package.

`conda install D` does *not* upgrade `A`, leaving `D` in a broken state.

My concrete example involves packages on conda-forge (which I believe should not make a difference) and the packages in question are: `magics` dependens on `python-eccodes` depends on `jasper` depends on `jpeg 9.*`. The Azure notebooks root env provides `jpeg 8d`. `conda install -y -c conda-forge magics` does *not* upgrade `jpeg`.

This is using `conda` 4.3.22 on python 2.7. Azure notebooks currently provides the Anaconda 4.10 package set with some Azure specific extras.

**Comment by kynan** [comment]
[Here's a notebook demonstrating the issue](https://notebooks.azure.com/frathgeber/libraries/conda-5757)

**Comment by kalefranz** [comment]
Probably of interest to @mcg1969

**Comment by mcg1969** [comment]
The version of `jasper` that is being pulled in is `jasper-1.900.1-1`. This version does _not_ specify a version of `jpeg`. [See here](https://anaconda.org/conda-forge/jasper/files/modal/info/57113eb15351d85fcbece617). Conda is doing the right thing here.

Now, the latest build of `jasper`, `jasper-1.900-4`, does indeed specify a version of `jpeg`. [See here](https://anaconda.org/conda-forge/jasper/files/modal/info/589782229aba451118d45607).

This is, I'm afraid, a hotfixing issue. Conda-forge needs to remove or hotfix older builds of 1900.1

**Comment by kalefranz** [comment]
> This is, I'm afraid, a hotfixing issue. Conda-forge needs to remove or hotfix older builds of 1900.1
