### ISSUE TITLE
Is sudo apt-get install works for all envs

### ISSUE THREAD

**Issue by MrWanter** [conda/conda#5760]
My question is simple, maybe silly, I just want to know that if I use `sudo apt-get install` to install some pkgs in the root env, then in conda's newly created env, are those pkgs accessible to me still? Thanks !

**Comment by MrWanter** [comment]
I'm using `Anaconda` with `python 3.6`, and I created a new `env` with `python 2.7`, previously I have installed `protobuf` with `sudo apt-get install libprotobuf-dev protobuf-compiler`, and I can find them with `dpkg -l | grep protobuf`, which gives:

```
(py2) cc@cc-Lenovo-Rescuer-14ISK:~/Downloads/caffe$ dpkg -l | grep protobuf
ii  libprotobuf-dev:amd64                                 2.5.0-9ubuntu1                                      amd64        protocol buffers C++ library (development files)
ii  libprotobuf-lite8:amd64                               2.5.0-9ubuntu1                                      amd64        protocol buffers C++ library (lite version)
ii  libprotobuf8:amd64                                    2.5.0-9ubuntu1                                      amd64        protocol buffers C++ library
ii  protobuf-compiler                                     2.5.0-9ubuntu1                                      amd64        compiler for protocol buffer definition files

```

but in my new `env`, after I installed caffe and try `import caffe`, it gives 
```
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal
```
so it seems that it cannot find `protobuf`, what's the problem? What's I'm mainly confused of is that, if I installed some pkgs with `sudo apt-get install` command, would it be installed in a system-wide location and I can access the pkgs in my new conda env?

**Comment by nehaljwani** [comment]
To use protobuf inside conda environment, type:
```
conda install protobuf
```
To use the protobuf outside of conda environment (system level), type:
```
apt-get install python-protobuf
```

**Comment by kalefranz** [comment]
Or `conda install protobuf --prefix /usr/local`.  Good luck.
