### ISSUE TITLE
Cannot install microscopes-common due to conflict

### ISSUE THREAD

**Issue by robmorr** [conda/conda#5765]
I am attempting to install microscopes-common from the channel datamicroscopes but have discovered a conflict between bottleneck and microscopes-common based on different dependencies on numpy.  While attempting the installation, I receive the following message:

$ conda install microscopes-common

UnsatisfiableError: The following specifications were found to be in conflict:
  - bottleneck
  - microscopes-common
Use "conda info <package>" to see the dependencies for each package.

Attached are the conda list and dependencies for bottleneck and microscopes-common.

[conda_list.txt](https://github.com/conda/conda/files/1192370/conda_list.txt)
[bottleneck_info.txt](https://github.com/conda/conda/files/1192371/bottleneck_info.txt)
[microscopes-common.txt](https://github.com/conda/conda/files/1192373/microscopes-common.txt)

My installation of anaconda2 on Linux 64-bit was downloaded from: https://www.continuum.io/downloads

It seems that the microscopes-common package depends on numpy 1.8.2, but there does not seem to be a bottleneck build that depends on numpy 1.8.2.

Is there anyway to work around this problem?

**Comment by kalefranz** [comment]
Head over to conda-forge and build for yourself what you need :)
