### ISSUE TITLE
activate -> deactivate -> activate fails on Windows

### ISSUE THREAD

**Issue by htInEdin** [conda/conda#5768]
To reproduce, clean install of Miniconda 3, launch the Anaconda prompt from the Start Menu, create an empty new environment and then
```
(C:\Miniconda3) C:\Users\ht>activate myenv1

(myenv1) C:\Users\ht>deactivate

C:\Users\ht>activate myenv1
'activate' is not recognized as an internal or external command,
operable program or batch file.
```
I thought that was supposed to work?

```
C:\Users\ht>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Miniconda3  (writable)
    default environment : C:\Miniconda3
       envs directories : C:\Miniconda3\envs
                          C:\Users\ht\AppData\Local\conda\conda\envs
                          C:\Users\ht\.conda\envs
          package cache : C:\Miniconda3\pkgs
                          C:\Users\ht\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : False
```

**Comment by kalefranz** [comment]
Because of this issue, for the cmd.exe shell, I still think it might be a good idea to have a directory that *only* contains the conda executable (or actually `conda.bat`) so that we can always have `conda` on PATH.

**Comment by wulmer** [comment]
Sounds great to me! As the current Anaconda versions require the user to manually activate the base environment (e.g. to fix the [QT platform plugin issue](https://github.com/ContinuumIO/anaconda-issues/issues/7766#issuecomment-351888968)), it would be great if at least `conda` was on the PATH. As I understood, the current (command line) approach involves calling the `activate.bat` script of the base environment with its full path. So being able to call `activate` or `conda` without having to activate the base environment first with its full path would be great!

**Comment by mbargull** [comment]
Yes, maybe it's not a bad idea to have that `cmd.exe`-only.
@mingwandroid, what are your thoughts on this? I agree with you on https://github.com/conda/conda/issues/6810#issuecomment-364963993, but for `cmd.exe` we don't have a `. etc/profile.d/conda.sh` and shell function equivalent. Thus, making something like
```bat
set "PATH=DIR_ONLY_CONTAINING_CONDA_BAT;%PATH%"
```
the
```bash
. etc/profile.d/conda.sh
```
equivalent is currently the only possibility I see. Any alternative suggestions?

**Comment by mingwandroid** [comment]
Do you mean adding this path in the installer all of the time or something?

I'm not thrilled about it and would really prefer we specify that people need to use the full path to conda when activating instead.

Can Powershell do better? Is there any .profile stuff and she'll functions there that we can use to get us closer to Unix behaviour?

**Comment by mbargull** [comment]
> Can Powershell do better? Is there any .profile stuff and she'll functions there that we can use to get us closer to Unix behaviour?

I don't know if they have `.profile` equivalents. But I'm pretty sure that dot-sourcing and functions are available. (TBH, I know next to nothing about Powershell, though..)

> I'm not thrilled about it and would really prefer we specify that people need to use the full path to conda when activating instead.

But with `conda 4.4` we make use of shell functions and thus can remove everything from the (`base`) environment from `PATH` with a `deactivate`. That works very fine -- apart from with `cmd.exe`. Since we have no shell function there, but still remove everything from `PATH`, we should get the same issue as this one, i.e., after `conda deactivate` (at `CONDA_SHLVL=1`) a subsequent `conda activate` won't find `conda`.

**Comment by mbargull** [comment]
I guess, since the "Anaconda Prompt" user won't necessarily know the full path to `conda.bat`, you'd at least have to output something like
```
Deactivated the last Conda environment. To activate again, call
full\path\to\conda.bat activate
```
when we drop that location from `PATH`.
