### ISSUE TITLE
Setting up the KNIME Python extension. Revisited for Python 3.0 and 2.0

### ISSUE THREAD

**Issue by ouyangluman** [conda/conda#5769]
Hi

I have a question when I Set up the KNIME Python extension. Revisited for Python 3.0 and 2.0 (https://www.knime.org/blog/setting-up-the-knime-python-extension-revisited-for-python-30-and-20). Below is the information:
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\CTF\AppData\Local\OptimusAnaconda  (writable)
    default environment : C:\Users\CTF\AppData\Local\OptimusAnaconda
       envs directories : C:\Users\CTF\AppData\Local\OptimusAnaconda\envs
          package cache : C:\Users\CTF\AppData\Local\OptimusAnaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\CTF\AppData\Local\OptimusAnaconda\Scripts\conda-script.py create -y -n py35_knime python=2.7 pandas jedi`

    Traceback (most recent call last):
      File "C:\Users\CTF\AppData\Local\OptimusAnaconda\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\CTF\AppData\Local\OptimusAnaconda\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\CTF\AppData\Local\OptimusAnaconda\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\CTF\AppData\Local\OptimusAnaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'C:\\Users\\CTF\\AppData\\Local\\OptimusAnaconda\\pkgs\\mkl-2017.0.3-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

  Can you tell me how to deal with these issue? Thanks and thanks for your work on KNIME

   Bestwishes!
   Olivia

**Comment by tyler-thetyrant** [comment]
Can you try with the most recent version of conda (4.3.23)?
 I wasn't able to reproduce the error with it. You can either reinstall miniconda or run `conda update conda` command.

**Comment by kalefranz** [comment]
Intermittent HTTP error.  Also, `conda update conda`.
