### ISSUE TITLE
Major bug :   conda install --revision x deletes conda ......

### ISSUE THREAD

**Issue by arita37** [conda/conda#5775]
Serious BUG in conda:

conda install --revision x   deletes the packages updated or installed.

Deletion also includes conda.

So, after conda disappeards and nothing can be done.

1) How to solve it without re-installing the whole anaconda ?

2) Can you solve this major bug ?
  Especially, put a limitation on fundamental packages which cannot be deleted.... or altered (or keep in backup).

**Comment by jacksdu** [comment]
Same issue..

**Comment by kalefranz** [comment]
Solved in pending releases of conda 4.3 and conda 4.4.
