### ISSUE TITLE
Offline .tar install broken

### ISSUE THREAD

**Issue by patrick984** [conda/conda#5777]
I am attempting to install a tarball of packages on an air-gapped machine.

Using the command `conda install packages.tar` as indicated [here](https://docs.continuum.io/anaconda/user-guide/tasks/install-packages#installing-packages-on-a-non-networked-machine).

This produces the following error:

```
>conda install packages.tar
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:

  - packages.tar

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
```

Have also tried absolute path and adding --offline option, both also fail.

Conda version: 4.3.23
OS: Windows 10

**Comment by patrick984** [comment]
Have just tested downgrading to conda 4.2 and offline installation works as expected.

**Comment by willsALMANJ** [comment]
This feature was removed intentionally: https://github.com/conda/conda/pull/3641. The documentation should be updated, but I'm not sure where to file the bug for that.
