### ISSUE TITLE
After installing "debug" package, conda breaks

### ISSUE THREAD

**Issue by mcgibbon** [conda/conda#5780]
With a working Python 2.7 install, I ran "conda install debug" to be able to debug a Cython extension. I ran into some other issues as a result, but can't fix them because of one main issue - now "conda" does nothing. 

```
[mcgibbon@***.edu workspace]$ conda remove debug
[204525 refs]
[mcgibbon@***.edu workspace]$ conda list
[204525 refs]
[mcgibbon@***.edu workspace]$ conda
[204525 refs]
```

As a temporary work-around, how can I manually remove debug and go back to my previous Python installation? I am using Linux with a home directory install.

In the longer term, conda probably shouldn't break when installing packages in the anaconda channel.

**Comment by mcgibbon** [comment]
I manually downloaded a Python package from the conda website and extracted it to my anaconda folder, after which conda worked again, so I did a "conda remove debug" and "conda install python".

Anyone know what to do about this?

**Comment by kalefranz** [comment]
I guess you got debug versions of python, right?  I know the debug packages are REALLY old, and we don't actively test against them (nor do we have the resources to right now).  Best advice is to only use debug packages inside of a non-root active conda environment.

**Comment by mcgibbon** [comment]
Eventually I was able to restore my anaconda by manually replacing the python executable, and then conda installing the non-debug Python.
