### ISSUE TITLE
Env not shown in list

### ISSUE THREAD

**Issue by robmarkcole** [conda/conda#5785]
conda 4.3.23 on Mac

I follow the instructions on the cheat sheet and create an env:

`conda create --prefix ~/hass-dev-london-air python=3.5.3`

But when I list my envs, it does not appear:

```
conda info -e
# conda environments:
#
hass_dev_35              /Users/robincole/anaconda3/envs/hass_dev_35
root                  *  /Users/robincole/anaconda3
```

However I am able to activate the env with `source activate`.

If I follow the instructions in [the docs](https://conda.io/docs/using/envs.html) I create then env with:

`conda create --name hass-dev-london-air python=3.5.3`

The env DOES appear with `conda info -e`. 
I have probably misunderstood the usage of `prefix` and `name` but at the leas this could be clarified between the cheat sheet and online docs

**Comment by kalefranz** [comment]
Fixed in conda 4.4
