### ISSUE TITLE
Give package hints based on rules, not packages

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#579]
I was reading [this presentation](http://files.opensuse.org/opensuse/en/b/b9/Fosdem2008-solver.pdf) about zypper, the OpenSuse package mangaer, which also uses a SAT solver. It mentions that when packages are unsatisfiable, to report to the user what rules are the cause.

This is a good idea. Conda currently reports what packages can be removed to make the rest satisfiable, but you have to deduce what the issue is from that. And [sometimes](https://github.com/conda/conda/issues/567) it's not very helpful. Instead of reporting "removing package X would make things work", we should report, "the rule(s) X is the issue here", where it could be something like "X depends on Y and Y conflicts with Z" (the most common occurrence of unsatisfiable packages is a package not being built for a particular version of Python) or "X and Y cannot be installed together".

**Comment by mcg1969** [comment]
I would argue that this is at least what we're _trying_ to do right now. We find the minimal unsatisfiable subset, and then search for an underlying dependency conflict that causes it. It's not perfect, as I'm sure you know, and as [other issues suggest](https://github.com/conda/conda/labels/tag%3Asolver-messaging) ---but the point is the goal is as you describe.
