### ISSUE TITLE
conda upload - TypeError: 'NoneType'

### ISSUE THREAD

**Issue by Joko013** [conda/conda#5793]
I am trying to upload environment to start working on my python project via anaconda cloud but every time run (after exporting the `test` environment with `conda env export --name test > environment.yml`)

`C:\Users\admin>conda env upload test`

I get this error:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

 https://github.com/conda/conda/issues

Current conda install:
               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\admin\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\admin\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\admin\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\admin\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : False

$ C:\ProgramData\Anaconda3\Scripts\conda-env-script.py upload --name test

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_upload.py", line 70, in execute
        env = from_file(args.file)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 71, in from_yaml
        data[key] = value
    TypeError: 'NoneType' object does not support item assignment

Does anyone see what I am doing wrong?

**Comment by kalefranz** [comment]
Use `anaconda upload` instead.
