### ISSUE TITLE
chcp and cmd is not an internal order

### ISSUE THREAD

**Issue by fighterzzzh** [conda/conda#5796]
After i created the environment,i can not use‘ activate’ to use  the environment and cmd suggested that  chcp and cmd is not an internal order。I am using win10.

**Comment by mingwandroid** [comment]
Can you use the `Anaconda Prompt`? That will activate your root environment for you.

**Comment by fighterzzzh** [comment]
I can use it.But if i use the 'activate ',it had the same problem.

**Comment by mingwandroid** [comment]
Please show the exact command you try to run and the exact output. If you can copy and paste these as text instead of as pictures that would be better.

Also, please show the output, in the `Anaconda Prompt` again, of `where activate`.

**Comment by fighterzzzh** [comment]
Okay, but the computer is not around. I will do it when i go back。

**Comment by kalefranz** [comment]
Hopefully fixed with conda 4.4.  If not, please file a new issue.
