### ISSUE TITLE
activating conda environment broken with git bash in Windows 10

### ISSUE THREAD

**Issue by dashesy** [conda/conda#5799]
Similar to issue #2810 but using source also has no effect:

    $ source activate py35
    $ python --version
    Python 3.6.1 :: Anaconda custom (64-bit)

---
Edit: I edited `activate` (just added and echo) and now it is working! No idea what happens.

**Comment by warren-oneill** [comment]
@dashesy could you expand a bit more on your solution?

**Comment by dashesy** [comment]
@warren-oneill I edited `activate` module (just added some comments) and then it started working! I removed the comments and it continued working. I guess it might have been some `.pyc` file being used.
Since it is working now, I will close this issue. I wish I could figure out what exactly caused the transient issue.
