### ISSUE TITLE
conda --file installation fails with opencv3

### ISSUE THREAD

**Issue by juhaemil** [conda/conda#5807]
Already downgraded to conda 4.2 from 4.3 but to no avail.
--------

(myenv) jj-MacBook-Air:conda jj$ conda install --file ~/miniconda3/conda-bld/src_cache/opencv-3.1.0.tar.gz
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.17
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/jj/miniconda3  (writable)
    default environment : /Users/jj/miniconda3/envs/myenv
       envs directories : /Users/jj/miniconda3/envs
          package cache : /Users/jj/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/menpo/osx-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jj/.condarc
           offline mode : False

`$ /Users/jj/miniconda3/envs/myenv/bin/conda install --file /Users/jj/miniconda3/conda-bld/src_cache/opencv-3.1.0.tar.gz`

    Traceback (most recent call last):
      File "/Users/jj/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jj/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/jj/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/jj/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 189, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "/Users/jj/miniconda3/lib/python3.6/site-packages/conda/cli/common.py", line 520, in specs_from_url
        for line in open(path):
      File "/Users/jj/miniconda3/lib/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by kalefranz** [comment]
Don't know where you saw downgrading to conda 4.2 would help. It's no longer supported. The `--file` flag is for a list of requirements, not for a path to a conda package tarball. Just leave it out of your command. And `conda update conda` back to 4.3.

**Comment by juhaemil** [comment]
How can I force conda to use a file on the hard drive? It tries to look online and fails.

jj-MacBook-Air:conda jj$ conda install ~/miniconda3/conda-bld/src_cache/opencv-3.1.0.tar.gz
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - /users/jj/miniconda3/conda-bld/src_cache/opencv-3.1.0.tar.gz

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/menpo/osx-64
  - https://conda.anaconda.org/menpo/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by kalefranz** [comment]
Oh. You're using a .tar.gz file. It's probably not even a conda package. All conda packages are currently .tar.bz2. But just because a file is .tar.bz2, it doesn't mean it's a conda package.

**Comment by juhaemil** [comment]
Hmm...I'm pretty sure it's a conda package, as it appeared when I followed these instructions:

https://github.com/menpo/conda-opencv3

Any thoughts?

**Comment by kalefranz** [comment]
I think that documentation is wrong.  It might just be a typo.  But a .tar.gz file is by definition not a conda package.
