### ISSUE TITLE
why does conda downloads python again, when i have anaconda already

### ISSUE THREAD

**Issue by vimalk78** [conda/conda#5812]
i am using anaconda python

```
$ python --version
Python 2.7.13 :: Anaconda 4.4.0 (64-bit)


$ which python
/home/vimal/anaconda2/bin/python

$ conda create -n myjunkproject python=2
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/vimal/anaconda2/envs/siraj-regression:

The following NEW packages will be INSTALLED:

openssl:    1.0.2l-0     
pip:        9.0.1-py27_1 
python:     2.7.13-0     
readline:   6.2-2        
setuptools: 27.2.0-py27_0
sqlite:     3.13.0-0     
tk:         8.5.18-0     
wheel:      0.29.0-py27_0
zlib:       1.2.8-3      

Proceed ([y]/n)? n
```

why install python 2.7.13 again?????? isnt it already there? same about pip.

everytime i create a new project, it MANDATORILY downloads every dependency. even without user specifying any versions. the same dependdencies are already in use by another project, but it still downloads newly. why it cannot cache and reuse the same?

**Comment by kalefranz** [comment]
The issue was actually with the installer, not conda.  It's been taken care of in recent versions of the Anaconda installer.
