### ISSUE TITLE
Conda-tensorflow installation problem

### ISSUE THREAD

**Issue by nberat5** [conda/conda#5819]
Hi guys, 

Whatever I tried recently is not working at all. I'm using win 7, trying to install opencv3, tensorflow and other packages with Anaconda. I tried their 32 bit version and after some effort I got opencv work but at that time tensorflow is not working. 

What should I do? 

If you would be as much as clear and give me advice to apply step by step, I'll be really appreciated. 
Thanks in advance.

**Comment by kalefranz** [comment]
The conda issue tracker really isn't a user support forum.  It's used more for tracking real bugs and the addition of new features to the conda source code.  You might have better luck with the conda user forum.  https://groups.google.com/a/continuum.io/forum/#!forum/conda
