### ISSUE TITLE
Old error message when running `activate` on Unix-like systems

### ISSUE THREAD

**Issue by DavidMertz** [conda/conda#5828]
```bash
521-~ % activate py36
Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.
522-~ % conda activate py36
(py36) 523-~ % conda --version
conda 4.4.0rc0
(py36) 524-~ % uname -a
Darwin 0196-dmertz.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

Given the improved `conda activate` usage, the error message should reflect this.  Perhaps:

> Error: activate is a subcommand of conda. Run 'conda activate envname' instead of 'activate envname'.

**Comment by mbargull** [comment]
Resolved with https://github.com/conda/conda/pull/6669. `activate`/`deactivate` are just not executable anymore.
