### ISSUE TITLE
Unable to pin anaconda version

### ISSUE THREAD

**Issue by basnijholt** [conda/conda#5832]
This does work:
```
conda create  --name test anaconda mshr
```
but this not:
```
conda create  --name test anaconda=4.4 mshr
```
which gives the following error:
```
Fetching package metadata ...........
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda 4.4*
Use "conda info <package>" to see the dependencies for each package.
```
It is pulling `mshr` from the `conda-forge` channel.

We would really like to version control anaconda in our [`Dockerimage env file`](https://github.com/quantum-tinkerer/research-docker/blob/c3fa2e4b5405166d1074c26fb4838ccfdf420bc3/python3.yml#L14) for our Jupyerhub to ensure reproducibility, but right now it is impossible.

**Comment by kalefranz** [comment]
I'm guessing mshr declares a dependency that's incompatible with the explicitly-pinned packages in the ananconda 4.4 metapackage?  I do agree that we need much better messaging here.
