### ISSUE TITLE
AttributeError: 'module' object has no attribute 'add_metaclass'

### ISSUE THREAD

**Issue by swaroopgrs** [conda/conda#5840]
Installed it only for user. Getting this while opening anaconda prompt
```

Traceback (most recent call last):
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\Scripts\conda-script
.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\co
nda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\co
nda\exceptions.py", line 628, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\co
nda\exceptions.py", line 590, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\co
nda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\co
nda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\re
quests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\re
quests\packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\Op
enSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\Op
enSSL\crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "C:\Users\sgadiyar\AppData\Local\Continuum\Anaconda2\lib\site-packages\cr
yptography\hazmat\primitives\asymmetric\__init__.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
```

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by kalefranz** [comment]
Or is that the command you were trying to execute?

You've got a version mismatch between `requests` and `cryptography`.  Have you been using pip to install packages?

**Comment by kalefranz** [comment]
Can you give me the output of `python -c "import conda; print(conda.__version__)"`?

**Comment by swaroopgrs** [comment]
I do not have conda in the PATH. So, I am trying to use Anaconda Prompt. When I launch Anaconda Prompt, I am getting the error above. I cannot run the commands you said in a normal command window since conda is not recognized, as it is not in the path.

**Comment by swaroopgrs** [comment]
I have python, h5py, pyodbc, python support libraries (by Microsoft) installed with admin privileges (separate from conda).

**Comment by swaroopgrs** [comment]
`conda info` is giving a blank output.  `python -c "import conda; print(conda.__version__)"` is saying `No module named conda`

**Comment by compie** [comment]
I have the same issue (after a fresh install of Anaconda3-5.0.1-Windows-x86_64.exe

**Workaround**:

1. Open a normal command prompt (cmd.exe)
2. Execute commands:
`set PYTHONPATH=`
`set PATH=%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem`
3. Execute the 'Anaconda Prompt' command directly:
`C:\Users\<username>\AppData\Local\Continuum\anaconda3\Scripts\activate.bat C:\Users\<username>\AppData\Local\Continuum\anaconda3`

**Comment by kalefranz** [comment]
Manually setting the `PYTHONPATH` can lead to all sorts of problems.

**Comment by ykzhou** [comment]
I had almost identical  errors when trying to do pip install.

Then I noticed there was an old dir ~/.local/lib/python2.7/,  which was generated by another  python2.7 in ubuntu.

removing this old dir solved my problem.

**Comment by RadCopperman** [comment]
I use Google Colab and for 
%load_ext zipline 
I got this error:
****ImportError: cannot import name 'add_metaclas**s'**
