### ISSUE TITLE
Problem: conda-build doesn't clean up temporary files

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5847]
@gabm commented on [Thu Aug 17 2017](https://github.com/conda/conda-build/issues/2289)

It seems conda-build doesn't clean up temporary files located under `/tmp/tmpxxxxxx` or `User/../AppData/Local/tmpxxxxxx` on windows. After the build these folders contain the decompressed packages that I suppose have been installed as dependencies during the build. Maybe its also a conda problem?!

Anyway, on our Windows build machine we accumulated 25Gb within some weeks .... 

---

@gabm commented on [Thu Aug 17 2017](https://github.com/conda/conda-build/issues/2289#issuecomment-323134590)

.. the same files are located again in `miniconda3/pkgs`... 

---

@msarahan commented on [Thu Aug 17 2017](https://github.com/conda/conda-build/issues/2289#issuecomment-323158750)

Conda-build uses this functionality in conda for temporary folders: https://github.com/conda/conda/blob/dbe99de1d45206c5d6f2e19017a9e2466f81dc6d/conda/compat.py#L23-L67

When we get files from packages, we do so with the package_has_file function: https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L714-L730

package_has_file does not ever extract the whole package.  This seems like a conda issue.  Sorry, I don't currently have time to investigate this more.  I can move this issue to the conda repo if you'd like.

---

@gabm commented on [Thu Aug 17 2017](https://github.com/conda/conda-build/issues/2289#issuecomment-323170508)

ok, then please move it there... If I find time, I'll have a further look. I realised some strange folders `/tmp/tmpxxxxxxx` some weeks ago, so could be easy to reproduce...

**Comment by kalefranz** [comment]
That `TemporaryDirectory` class is *only* used by conda-build.  The only reason it hasn't been removed from conda is to support conda-build.  Perhaps we should be moving it there.

**Comment by kalefranz** [comment]
This is probably generally related to https://github.com/conda/conda/issues/6631

**Comment by aktzbn** [comment]
So, does it really related to #6631? Is it fixed?

**Comment by heineike02** [comment]
When I run jupyter on conda on windows 10 computers I always get a few thousand of these empty tmpxxxxxx files .  I thought it might be something specific to my computer and the security settings on my work computer, but I have now seen it on 4 computers with windows 10 and most recently installed Anaconda on a new computer yesterday (July 14 2020).  Every few months I check issue #6631 to see if there has been any progress, but it seems like that issue has not been worked on for a few years.  

Right now my protocol is to open up the \AppData\Local\Temp folder and delete them all every few days, but I feel like there must be a better way.  I can't imagine I am the only one running Jupyter from Anaconda on Windows 10.  Is there any news on this issue?
