### ISSUE TITLE
Conda update can result in binary incompatible packages when using multiple channels

### ISSUE THREAD

**Issue by jni** [conda/conda#5855]
Under instruction from @fbender in #1967, I'm upgrading this from a comment to its own issue. The TL;DR is that "conda update" can result in numpy from conda-forge with dependent packages from defaults, or vice versa, resulting in a binary incompatibility that only shows up at runtime.

Longer version:

Like many conda users, I more or less interchangeably install from defaults and conda-forge as the mood strikes me. My default channel from condarc, confusingly, is conda-forge, but some environments are based on defaults (for the MKL mostly). Now, conda-update in these environments does weird things. **My conda version was 4.3.11**.

Here I am trying to update all, specifying defaults as the channel. As you can see, it seems to work, except NumPy gets updated to conda-forge, thereby breaking everything. I type `y` while making a mental note to reinstall defaults numpy.

```console
 $ conda update --all -c defaults
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/nuneziglesiasj/anaconda/envs/36:

The following packages will be UPDATED:

    hdf5:    1.8.17-1                  --> 1.8.17-2                                 
    ipython: 5.3.0-py36_0  conda-forge --> 6.1.0-py36_0                             
    numpy:   1.12.1-py36_0             --> 1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas]
    pillow:  4.1.1-py36_0              --> 4.2.0-py36_0                             
    s3fs:    0.1.0-py36_0              --> 0.1.1-py36_0                             

Proceed ([y]/n)? 

hdf5-1.8.17-2. 100% |############################################################| Time: 0:00:00  40.60 MB/s
pillow-4.2.0-p 100% |############################################################| Time: 0:00:00  53.43 MB/s
ipython-6.1.0- 100% |############################################################| Time: 0:00:00  23.39 MB/s
s3fs-0.1.1-py3 100% |############################################################| Time: 0:00:00  22.87 MB/s
```

Now to re-update numpy:

```console
 $ conda update -c defaults numpy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/nuneziglesiasj/anaconda/envs/36:

The following packages will be UPDATED:

    scikit-learn: 0.18.2-np112py36_0                        --> 0.18.2-np112py36_blas_openblas_200 conda-forge [blas_openblas]
    scipy:        0.19.1-np112py36_0                        --> 0.19.1-np112py36_blas_openblas_200 conda-forge [blas_openblas]

The following packages will be SUPERCEDED by a higher-priority channel:

    numpy:        1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.12.1-py36_0                                 

Proceed ([y]/n)? n
```

Right... Ok scrap that, what happens if I try to specify all those packages manually?

```console
 $ conda update -c defaults numpy scipy scikit-learn scikit-image pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/nuneziglesiasj/anaconda/envs/36:

The following packages will be SUPERCEDED by a higher-priority channel:

    numpy: 1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.12.1-py36_0

Proceed ([y]/n)? y
```

Whew!

My `.condarc`:

```yaml
channels:
  - conda-forge
  - defaults
```

Needless to say, a crisis was averted only because I know just enough about these things to be suspicious. A user described by @janschulz [here](https://github.com/conda/conda/issues/1967#issuecomment-180327850), really not very far removed from myself, would have been totally screwed:

> someone who has not a lot of ideas about requirements and such stuff and wants to have certain python packages to "just work".

So it seems `conda update` is still not there with @seibert's [Three Laws](https://github.com/conda/conda/issues/1967#issuecomment-172917291)...

> 1. `conda update` will not make the environment inconsistent or, through inaction, allow an environment to become inconsistent.
> 2. `conda update` will install the packages explicitly requested by the user on the command line, except when it conflicts with the First Law.
> 3. `conda update` will preserve the package state of environment, except when it conflicts with the First or Second Law.

What's the recommended way to deal with this...?

**Comment by jkroes** [comment]
Couldn't you prevent any other channels from being searched, and thereby numpy upgrading to a conda-forge version, by using` conda update --all -c defaults  --override-channels`? Without the latter option, the manual indicates that any default channels (i.e. conda-forge) will be searched after the channel specified by `-c`.  Let me know if I'm missing something here. I'm still learning conda as I go :)

**Comment by mingwandroid** [comment]
> Like many conda users, I more or less interchangeably install from defaults and conda-forge as the mood strikes me.

> What's the recommended way to deal with this...?

The *only* way to deal with this (until conda `defaults` and `conda-forge` reach a condition of binary compatibility and a mutually agreed rule to maintain that as an *explicit* goal) is to keep conda `defaults` and `conda-forge` software isolated from each other in different conda `environments`.

An essential precondition to @seibert's [Three Laws](https://github.com/conda/conda/issues/1967#issuecomment-172917291) is that you are not mixing incompatible package families in the same conda `environment`.

**Comment by jni** [comment]
@mingwandroid @jkroes I have no doubt that there is a user-based solution to this problem. The issue is that it should *not* be up to the user to figure out what "incompatible package families" are. Users are going to be reading instructions to "conda install X" and "conda install -c conda-forge Y" and they are not going to have any idea that mixing these two commands can break things.

I *don't* think conda-forge and defaults can ever aim to be binary compatible, because defaults tries to maximise performance even at the cost of using proprietary libraries, while conda-forge aims to use a fully open and free stack.

imho, the aim here should be for conda to keep track of the channel that each package comes from, and disallow dependencies to come from a different channel *unless* the package is pure-Python. I'm sure there are many edge cases that break my rule but I hope it's a good starting point for discussion.

**Comment by mingwandroid** [comment]
The messaging is difficult, IMHO `conda` cannot forcibly prevent mixing things because some other channels do work properly with either `defaults` or `conda-forge` (as that is their - possibly unstated - intention). It's also not really possible to determine BC from inspection (it is to a limited extent, syntactically if you will, but not semantically. We don't have the tooling in place for syntactic BC determination yet). For sure, `conda create -n cf_y_env -c conda-forge Y` is much better advice than naive mixing software from each in the same env at present.

However `defaults` and `conda-forge` have very similar goals and are moving closer to each other. Some of us are very interested in figuring out how to 'fix' binary compatibility. I do not think the proprietary vs open distinction precludes making things *largely* work just fine. It is possible to define ABIs and write tooling to make it easier to stick to them and/or implement fully dynamic loading. It does need a deliberate effort though.

**Comment by jni** [comment]
@mingwandroid Sorry for my long silence.

I understand the difficulties, I think, but I think there is still stuff to be done to minimize the risk of these incompatibilities. For example, in my original message, this line:

```python
    numpy:   1.12.1-py36_0             --> 1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas]
```

makes no sense to me. Is NumPy getting updated because `1.12.1-py36_b` is greater than `1.12.1-py36_0`? Ah, seeing the other updates, that's indeed what happened. That probably requires some fixing in the conda-forge recipe, or conda's version resolution scheme, or both. As you mentioned, you can't control user repos, but you can try to fix the most common use case, which is users installing defaults and conda-forge packages depending on availability.

**Comment by jni** [comment]
@jkroes incidentally, it doesn't look like `--override-channels` prevents this behavior:

```
 $ conda install -c defaults --override-channels scikit-image=0.12
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/nuneziglesiasj/anaconda/envs/skim12:

The following packages will be UPDATED:

    numpy:        1.12.1-py36_0      --> 1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas]
    scikit-learn: 0.18.2-np112py36_0 --> 0.19.0-py36_blas_openblas_201 conda-forge [blas_openblas]
    scipy:        0.19.1-np112py36_0 --> 0.19.1-py36_blas_openblas_202 conda-forge [blas_openblas]

The following packages will be DOWNGRADED:

    scikit-image: 0.13.0-np112py36_0 --> 0.12.3-np112py36_1
```

I think an easy* early fix would be that `-c [channel-name] --override-channels` means "Don't look at anything on any channel other than `[channel-name]`!!!" If there are backward compatibility concerns, we could add a new arg, `--really-override-channels-dammit`.

Incidentally, my instinct is that `-c` would imply `--override-channels`.

If anyone (a) welcomes that change, and (b) can point me in the right direction, I'd be happy to submit a PR to this effect.

- *: Haha
