### ISSUE TITLE
[0x7FFD0BD6A4C0] ANOMALY: meaningless REX prefix used

### ISSUE THREAD

**Issue by josephzjw** [conda/conda#5858]
when I use the `conda activate tensorflow` to activate the environment tensorflow, but it shows `[0x7FFD0BD6A4C0] ANOMALY: meaningless REX prefix used`.

My operation system is win 10 and I have tried both 32 bit and 64 bit Anaconda, and it shows the same problem.

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by josephzjw** [comment]
Now it's okay, I don't know why last time it shows differently. Thanks!
