### ISSUE TITLE
Broken Pipe when installing miniconda for Python 2.7

### ISSUE THREAD

**Issue by Arrashg** [conda/conda#5860]
When I download miniconda for python 2.7 I get this warning. Can't seem to find a similar issue anywhere else.

<img width="945" alt="screen shot 2017-08-20 at 5 17 06 pm" src="https://user-images.githubusercontent.com/20796673/29499685-ea031234-85cb-11e7-859f-cb6b8226a305.png">

**Comment by kalefranz** [comment]
You need to mark that file as executable, or else invoke it with bash.

    chmod +x Miniconda2-latest-MacOSX-x86_64.sh
    ./Miniconda2-latest-MacOSX-x86_64.sh

or

    bash Miniconda2-latest-MacOSX-x86_64.sh
