### ISSUE TITLE
`pip install -e` does not recognise a conda environment as a virtualenv

### ISSUE THREAD

**Issue by ksze** [conda/conda#5861]
I believe most people would agree that, for all intents and purposes, a conda environment should be treated like a proper Python virtualenv.

However, `pip install -e <git url>` (which installs a python package in "editable" mode) does not recognise a conda environment as such.

According to the documentation of pip, `pip install -e <git url>` would place the editable package under `<virtualenv name>/src` if pip detects a virtualenv; otherwise it places the editable package under the *current working directory*.

I first discovered the issue using berryconda (https://github.com/jjhelmus/berryconda/issues/12), which is a conda-based Python distribution for Raspberry Pi. This is what happens if I try to install a package in editable mode using berryconda:
```
$ cd
$ ls -ld ./src/django
ls: cannot access ./src/django: No such file or directory
```

This shows that we start off without a `~/src/django` directory.

Now let's create a conda environment and install django in editable mode:
```
$ conda create -n django-dev pip
Fetching package metadata .....
Solving package specifications: .

Package plan for installation in environment /home/pi/berryconda3/envs/django-dev:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.7.27.1-0
    certifi:         2017.7.27.1-py36_0
    ncurses:         5.9-0
    openssl:         1.0.2l-0
    pip:             9.0.1-py36_0
    python:          3.6.2-0
    readline:        6.3-0
    setuptools:      36.2.7-py36_0
    sqlite:          3.15.0-0
    tk:              8.6.6-0
    wheel:           0.29.0-py36_0
    xz:              5.2.2-0
    zlib:            1.2.11-0

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate django-dev
#
# To deactivate an active environment, use:
# > source deactivate
#

$ source activate django-dev
$ pip install -e git+https://github.com/django/django.git#egg=django-dev
Obtaining django from git+https://github.com/django/django.git#egg=django-dev
  Cloning https://github.com/django/django.git to ./src/django
Collecting pytz (from django)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: pytz, django
  Running setup.py develop for django
Successfully installed django pytz-2017.2
$ ls -ld ./src/django
drwxr-xr-x 11 pi pi 4096 Aug 22 00:04 ./src/django
```

Oops.

Ok, so is there anything under `~/berryconda3/envs/django-dev/src`, where I expect pip to have installed the editable package?
```
$ ls -ld ~/berryconda3/envs/django-dev/src
ls: cannot access /home/pi/berryconda3/envs/django-dev/src: No such file or directory
```

Crap.

I initially raised an issue at the berryconda repo (https://github.com/jjhelmus/berryconda/issues/12). However, @jjhelmus suggests that this is a problem upstream in conda or pip, so I'm raising a new issue here.

Here is the corresponding issue in the pip project: https://github.com/pypa/pip/issues/4688

**Comment by kalefranz** [comment]
One solution to this issue would be to patch pip in 

https://github.com/pypa/pip/blob/4fc6978/src/pip/_internal/locations.py#L39-L49

Such that it also considers itself operating inside a python virtualenv if the `CONDA_PREFIX` environment variable is set and matches `sys.prefix`.

@nehaljwani Do you have any thoughts?

**Comment by kalefranz** [comment]
Also related is https://github.com/conda/conda/issues/7707

**Comment by asiron** [comment]
Correct me if I am wrong, but this seems to me like a very fundamental issue and there has been no traction on it for 2+ years now. 

I am currently handling python dependencies using `conda` (as is majority of DS/ML community). Some tools like `mlflow`, `azureml` are kind of enforcing `conda` on you. I would've preferred to use `pipenv`, but `conda` is supported out of the box in these tools

One work around for specifying editable packages would be to directly pass `--src <path>` to the `environment.yml` file as following:

```
name: test
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
    - "--editable git+git@ssh.dev.azure.com:v3/path/to/python/pkg@master#egg=my_pkg --src /path/to/conda/env/src"
```
but that doesn't work, because `conda` internally runs `pip install -r`, which doesn't support the `--src` flag as pointed out by https://stackoverflow.com/a/53364395. So the only option is to pass `PIP_SRC` as environment flag as such: `PIP_SRC=/path/to/src conda env create -f environment.yml`

**Comment by mfickett** [comment]
Thanks @asiron for noting the `PIP_SRC` workaround. I'm doing this:

```
local CONDA_BASE="$(dirname $(dirname "${CONDA_EXE}"))"
export PIP_SRC="${CONDA_BASE}/envs/${ENV_NAME}/pipsrc"
conda env create --name ${ENV_NAME} --file environment.yml
```

I agree the issue leads to surprising behavior, for example when deleting pip `src/` directories outside of a conda directory tree breaks the conda environment.

**Comment by kalefranz** [comment]
Related discussion at https://github.com/conda/conda/issues/7173

**Comment by benjamin9555** [comment]
I'm having the same problem and trying to bring more awareness to it.

Easy portability of conda envs is crucial and this issue hinders it, as automatically generating an `environment.yml` file with `conda env export > environment.yml` is obviously also missing all packages that have been installed with `pip install -e`.

**Comment by mfickett** [comment]
One mitigation is that `-e git+git@github.com:MyOrg/myrepo` style [is deprecated](https://github.com/pypa/pip/issues/7554) in favor of `git+ssh://git@github.com/MyOrg/myrepo` which doesn't require `-e`. So for my usage (where I don't actually care about [editable](https://pip.pypa.io/en/stable/reference/pip_install/#install-editable), I just want to clone from GitHub) switching to `git+ssh://` avoids the issue I believe.

**Comment by benjamin9555** [comment]
Good idea, but unfortunately you will need to pip install in editable mode to have the VCS reference included in `pip freeze` or `conda env export`, as far as I understand.

**Comment by janosh** [comment]
Based on @pfmoore's [comment](https://github.com/pypa/pip/issues/4688#issuecomment-513449192) in [pip#4688](https://github.com/pypa/pip/issues/4688#issuecomment-513449192), it sounds like this could be fixed on `conda`'s end by modifying `sys.base_executable`.

**Comment by sbidoul** [comment]
> you will need to pip install in editable mode to have the VCS reference included in pip freeze

@benjamin9555 if this can help, pip 20.1 implements PEP 610 and therefore pip freeze works with non editable VCS references too

**Comment by benjamin9555** [comment]
@sbidoul thanks for the hint. I just created a new conda environment with pip 20.2.2, but unfortunately the issue remains the same as @ksze pointed out in the beginning, `pip install -e <git url>` does not recognise the current conda environment.

**Comment by sbidoul** [comment]
@benjamin9555 I don't think anything changed on that front indeed. I just meant to answer to your May 1 comment by mentioning there is a new pip feature that `-e` is not necessary anymore for pip freeze to work, so if you don't specially care about *editable* installs this may alleviate the issue.

**Comment by SumNeuron** [comment]
So is there a `pip install -e` alternate for `conda`?
