### ISSUE TITLE
resinstall corrupted conda

### ISSUE THREAD

**Issue by arita37** [conda/conda#5866]
In Win 64bits, Python 2.7.1,

Conda has been corrupted :  
    cannot use command line, but the packages are available in python interpreter.

Message says current "conda installation is by pip,cannot update conda."

How to recover the conda without reinstalling the whole and without destryoing the env ?

**Comment by kalefranz** [comment]
Don't use pip to install conda.  Use a miniconda or anaconda installer instead.

**Comment by arita37** [comment]
Conda often broke and is not stable at all
due to external dependencies....



On 11 Oct 2017, at 22:25, Kale Franz <notifications@github.com> wrote:

Closed #5866.

―
