### ISSUE TITLE
'conda env remove -n name' deletes local folder 'name' if environment does not exist.

### ISSUE THREAD

**Issue by dharhas** [conda/conda#5867]
Running `conda env remove -n name` deletes local folder named `name` if no conda environment called `name` exists. 

To reproduce:

```
$ mkdir testdir
$ ls
testdir
$ conda env remove -n testdir

Remove all packages in environment /Users/rditldp9/tmp/testdir:

Proceed ([y]/n)? y
$ ls

$ conda --v
conda 4.3.23
$ uname -a
Darwin ITLDP9-MD-Q3134 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```

Found this while debugging an install script, our python package and our environment name were the same which is a pretty common thing to do: https://github.com/ContinuumIO/EarthSim/issues/80

This seems pretty dangerous to me.

**Comment by kalefranz** [comment]
Should be fixed in conda 4.4.  We ensure target environments *are* actually conda environments via the existence of `conda-meta/history`.
