### ISSUE TITLE
Seaborn Installation Issue - Unexpected Error

### ISSUE THREAD

**Issue by NithinKumarRN** [conda/conda#5868]
(D:\AnacondaInstallation) C:\Users\nr00353842>conda install seaborn
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs
/free/win-32/
Could not connect to https://repo.continuum.io/pkgs/pro/win-32/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
...
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - http://bremen/pkgs/free::conda-env-2.5.1-py35_0.tar.bz2
  - conda-env-2.5.1-py35_0.tar.bz2

Package plan for installation in environment D:\AnacondaInstallation:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.1            |           py35_0          64 KB
    seaborn-0.7.0              |           py35_0         274 KB
    ------------------------------------------------------------
                                           Total:         338 KB

The following NEW packages will be INSTALLED:

    seaborn:   0.7.0-py35_0

The following packages will be UPDATED:

    conda-env: 2.5.1-py35_0 --> 2.5.1-py35_0

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\AnacondaInstallation\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "D:\AnacondaInstallation\lib\site-packages\conda\cli\main.py", line 120,
in main
    exit_code = args_func(args, p)
  File "D:\AnacondaInstallation\lib\site-packages\conda\cli\main.py", line 130,
in args_func
    exit_code = args.func(args, p)
  File "D:\AnacondaInstallation\lib\site-packages\conda\cli\main_install.py", li
ne 69, in execute
    install(args, parser, 'install')
  File "D:\AnacondaInstallation\lib\site-packages\conda\cli\install.py", line 40
7, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "D:\AnacondaInstallation\lib\site-packages\conda\plan.py", line 595, in e
xecute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\AnacondaInstallation\lib\site-packages\conda\instructions.py", line 1
36, in execute_instructions
    cmd(state, arg)
  File "D:\AnacondaInstallation\lib\site-packages\conda\instructions.py", line 4
8, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "D:\AnacondaInstallation\lib\site-packages\conda\fetch.py", line 336, in
fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "D:\AnacondaInstallation\lib\site-packages\conda\fetch.py", line 369, in
download
    with Locked(dst_dir):
  File "D:\AnacondaInstallation\lib\site-packages\conda\lock.py", line 60, in __
enter__
    os.makedirs(self.lock_path)
  File "D:\AnacondaInstallation\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "D:\AnacondaInstallation\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "D:\AnacondaInstallation\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "D:\AnacondaInstallation\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: 'D:\\AnacondaInstallation\\pkgs\\http:'

(D:\AnacondaInstallation) C:\Users\nr00353842>conda info
Current conda install:

             platform : win-32
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : D:\AnacondaInstallation  (writable)
  default environment : D:\AnacondaInstallation
     envs directories : D:\AnacondaInstallation\envs
        package cache : D:\AnacondaInstallation\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\nr00353842\.condarc
         offline mode : False
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
You are using a very old version of conda! You should either reinstall miniconda or try `conda update conda`. 
We are currently on 4.3.24 :^)

**Comment by NithinKumarRN** [comment]
Thanks a lot for the confirmation. I've installed the latest conda version
which has Seaborn pre installed in it and got a way to work around the
problem.
