### ISSUE TITLE
Some questions about features (that should be documented when they are answered)

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#587]
I have some questions about features:

- Looking at the index.json for mkl numpy, I see

```json
{
  "arch": "x86_64",
  "build": "py27_p0",
  "build_channel": "p",
  "build_number": 0,
  "depends": [
    "mkl-rt 11.1",
    "python 2.7*"
  ],
  "features": "mkl",
  "license": "BSD",
  "name": "numpy",
  "platform": "osx",
  "pub_date": "2014-01-30",
  "requires": [
    "mkl-rt 11.1",
    "python 2.7"
  ],
  "version": "1.8.0"
}
```

Is the "features" key always a string? How does a package have multiple features?

- In the repo metadata, Anaconda has the `with_features_depends` key. For example

```json
"with_features_depends": {
        "mkl": [
          "mkl-rt 11.1 p0",
          "numexpr 2.3.1 np18py27_p0",
          "numpy 1.8.0 py27_p0",
          "scikit-learn 0.14.1 np18py27_p1",
          "scipy 0.13.3 np18py27_p0"
        ]
      }
```

- Why does only Anaconda have this? 
- The `conda index` command doesn't seem to handle this at all (meaning likely binstar won't either). 
- In general, what should be the correct transformation from the package metadata to the repo metadata regarding features?

http://conda.pydata.org/docs/spec.html does not talk about features at all. It also does not talk about the repo metadata spec, but it really should.

**Comment by kerrywatson1** [comment]
@asmeurer can you give us an update on this item? You should be the expert by now. :)

**Comment by asmeurer** [comment]
Features are pretty well documented by now.
