### ISSUE TITLE
Navigator error occoured when tried to open anaconda-navigator in ubuntu

### ISSUE THREAD

**Issue by Devanya** [conda/conda#5874]
![screenshot from 2017-08-24 04-43-19](https://user-images.githubusercontent.com/29503559/29642537-1d37bb92-8887-11e7-8739-bc74ac2fcff6.png)

**Comment by Devanya** [comment]
![screenshot from 2017-08-24 04-54-49](https://user-images.githubusercontent.com/29503559/29642780-78ee9d7e-8888-11e7-9487-fa0a632ed7e0.png)
![screenshot from 2017-08-24 04-55-17](https://user-images.githubusercontent.com/29503559/29642795-8221801e-8888-11e7-8400-b2b610178aa8.png)

**Comment by Devanya** [comment]
Some please look into this

**Comment by goanpeca** [comment]
@devanya, if you do 

```
$ source activate root
$ anaconda-navigator
```

?

**Comment by goanpeca** [comment]
Also the right repository to report this is https://github.com/ContinuumIO/anaconda-issues

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6560
