### ISSUE TITLE
Installing Plotly and Scikit packages in corporate networks 

### ISSUE THREAD

**Issue by NithinKumarRN** [conda/conda#5875]
Hi Team,

I'm unable to install plotly,cufflinks or scikit packages in my corporate enviroment.
Is there a way to work around this issue? I've the latest Anaconda distribution but the packages are not installed in it. 

(D:\Anaconda4.4InstallationFiles) C:\Users\nr00353842>conda install scikit-learn

Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-
32/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port
=443): Max retries exceeded with url: /pkgs/free/win-32/repodata.json.bz2 (Cause
d by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConn
ection object at 0x035B4170>, 'Connection to repo.continuum.io timed out. (conne
ct timeout=9.15)'))",),)

(D:\Anaconda4.4InstallationFiles) C:\Users\nr00353842>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : D:\Anaconda4.4InstallationFiles  (writable)
    default environment : D:\Anaconda4.4InstallationFiles
       envs directories : D:\Anaconda4.4InstallationFiles\envs
                          C:\Users\nr00353842\AppData\Local\conda\conda\envs
                          C:\Users\nr00353842\.conda\envs
          package cache : D:\Anaconda4.4InstallationFiles\pkgs
                          C:\Users\nr00353842\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\nr00353842\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7
indows/6.1.7601
          administrator : False

(D:\Anaconda4.4InstallationFiles) C:\Users\nr00353842>

**Comment by petebachant** [comment]
Have you set the proxy addresses in `~/.condarc`?

Something like:

```yaml
proxy_servers:
  http: http://corp.com:8080
  https: https://corp.com:8080
```
