### ISSUE TITLE
Optional dependencies and features as ways to segment examples, source, data, tests, docs

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5876]
It feels like many conda packages could be decomposed into a subset of components that come from these groups:

* binaries (pre-compiled)
* docs
* examples
* tests
* data
* source

In many cases it may be desirable to have just one of these (e.g. docs, or binaries, or examples), whereas in others some collection of those may be appropriate.

It would be nice to consider what the preferred patterns are to create this kind of decomposition, leveraging either (or both) optional dependencies and features.  I do not immediately have a suggestion for this, but as I watch the output of `--debug` and see lots of package contents being written to disk that I have no interest in it is making me think of ways to address this.

**Comment by kalefranz** [comment]
A package type for associated build logs is also on my list here.  Other than that, our lists mostly agree.  Except, I'm not yet convinced about the merits of an examples package type being different from a docs package type.

Also, there is currently discussion of docs package types being "fat," that is, having both html-format docs as generated via sphinx for something like read-the-docs to host, in addition to docs compatible with `man`.

**Comment by kalefranz** [comment]
Related issues to docs packages:

* https://github.com/conda/conda/issues/642
* https://github.com/conda/conda/issues/845
* https://github.com/conda/conda/issues/5654
