### ISSUE TITLE
Uninstallable dependencies lead to wild good chase

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5881]
I've built new mkl packages.  They're repacks of Intel's packages.  Here's some relevant repodata.json for these packages.  I have sorted them by timestamp.

```
"mkl-devel-2018.0.0-ha6e2b1a_4.tar.bz2":{"build_number":4,"name":"mkl-devel","has_prefix":false,"md5":"110617c65eda627f6d33800cbe258dca","requires":[],"machine":"x86_64","platform":"osx",
"depends":["mkl 2018.0.0 hb1dadce_4","mkl-include 2018.0.0 h6765ad9_0"],
"version":"2018.0.0","build":"ha6e2b1a_4","timestamp":1503590192833,
"binstar":{"package_id":"599f5578c7d29212d5bf7bd3","channel":"main","owner_id":"55fac6e4d3234d09d295156c"},"size":2596,"arch":"x86_64","operatingsystem":"darwin","target-triplet":"x86_64-any-darwin","subdir":"osx-64"}
```

```
"mkl-devel-2018.0.0-hf544b58_4.tar.bz2":{"build_number":4,"name":"mkl-devel","has_prefix":false,"md5":"6ff5f9b505a60fed19fbdaf43234bcf5","requires":[],"machine":"x86_64","platform":"osx",
"depends":["mkl 2018.0.0 h47df402_4","mkl-include 2018.0.0 h28e9f76_4"],
"version":"2018.0.0","build":"hf544b58_4","timestamp":1503606103311,
"binstar":{"package_id":"599f5578c7d29212d5bf7bd3","channel":"main","owner_id":"55fac6e4d3234d09d295156c"},"size":2521,"arch":"x86_64","operatingsystem":"darwin","target-triplet":"x86_64-any-darwin","subdir":"osx-64"}
```

```
"mkl-devel-2018.0.0-hbd05119_4.tar.bz2":{"build_number":4,"name":"mkl-devel","has_prefix":false,"md5":"abe970ed5cf4b757443b656a255f0deb","requires":[],"machine":"x86_64","platform":"osx",
"depends":["mkl 2018.0.0 h47df402_4","mkl-include 2018.0.0 h28e9f76_4"],
"version":"2018.0.0","build":"hbd05119_4","timestamp":1503606627998,
"binstar":{"package_id":"599f5578c7d29212d5bf7bd3","channel":"main","owner_id":"55fac6e4d3234d09d295156c"},"size":2566,"arch":"x86_64","operatingsystem":"darwin","target-triplet":"x86_64-any-darwin","subdir":"osx-64"}
```

The traceback I get if I create an env with mkl-devel (with 4.3.x or 4.4.x) is:

```
conda create -n mkltest -c msarahan mkl-devel
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl-devel
  - mkl==2018.0.0=hb1dadce_4
  - icc_openmp
```

This hash is the mkl specified by the earlier timestamp.  Both the mkl and mkl-include packages specified by any of these are fine, you can find them on my channel.  Here was the missing part:
mkl specified a dependency on ``intel_openmp``, but the package I made for that was ``intel-openmp``.

If at all possible, could we please have some diagnostic output for when solutions are tossed due to unsatisfiable dependencies?  Ending up with that earliest one really led me down the wrong trail.  Perhaps especially from some special set of channels (like ones that conda-build manually specifies?)  I'm sorry if this is an unfeasible request - I don't know if the solver is amenable to this kind of thing.

**Comment by kalefranz** [comment]
@msarahan I'm tracking this general topic with the [solver-message](https://github.com/conda/conda/labels/tag%3Asolver-messaging) tag.  There are 21 open issues and 12 closed issues on this thing.  It's definitely a big topic, and one @mcg1969 and I frequently discuss.
