### ISSUE TITLE
ssl_verify functionality doesn't match description

### ISSUE THREAD

**Issue by samuelharmer** [conda/conda#5884]
Was experimenting to see if I could use a cert directory on Windows 7:
```
> conda config --set ssl_verify C:\Users\HarmerS\certs
```

However it seems like the description of `ssl_verify` doesn't agree with the implementation.
```
> conda config --describe
[...]
ssl_verify (basestring, bool)
  default: true
  aliases: insecure, verify_ssl
  Conda verifies SSL certificates for HTTPS requests, just like a web
  browser. By default, SSL verification is enabled, and conda operations
  will fail if a required url's certificate cannot be verified. Setting
  ssl_verify to False disables certification verificaiton. The value for
  ssl_verify can also be (1) a path to a CA bundle file, or (2) a path
  to a directory containing certificates of trusted CA.
[...]

> conda install -c conda-forge pydicom

CustomValidationError: Parameter ssl_verify = 'C:\\Users\\HarmerS\\certs' declared in <<merged>> is invalid.
ssl_verify value 'C:\Users\HarmerS\certs' must be a boolean or a path to a certificate bundle.
```

```
> conda --version
conda 4.3.25
```
Via Miniconda 4.3.21 [installer](https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe) Python 2.7 32-bit + `conda update conda` on Windows 7 64-bit.

I would prefer to have the feature of using a cert directory (much easier to manage) so I raised the issue here rather than under conda-docs.

**Comment by kalefranz** [comment]
Conda just uses requests under the hood.  Is what you're proposing compatible with http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification ? If so, we can absolutely update all associated docs.

For reference, the documentation shown by `conda config --describe` is at https://github.com/conda/conda/blob/4.3.x/conda/base/context.py#L686
