### ISSUE TITLE
re-organize package cache

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5889]
Further to comments from @mcg1969 regarding sym-linking, `urls` and `urls.txt`, and reliability of packges in the the package cache I have been inspired (again) to think that our package cache really should be creating a full mirror of repo.continuum.io, and in fact at even one level up in the case of multiple repositories.  I would like to propose that we re-organize the package cache to look like:

```
/path/to/anaconda/cache/reposite/channel/platform/bitwidth/pkg-ver
```

I don't have a suggestion for how labels should be handled.

And in this way a simple `rsync` + `conda index` would allow someone (individual user, or IT administrator) to re-create a durable package cache that looks like a repository instance, and then conda could look there for symlinking or hard linking files and have a much lower chance of files being overwritten by conda in the `install` and `update` process.

**Comment by mcg1969** [comment]
Oh my, no. We can't do a full mirror. That's way too much data. But @kalefranz has already been noodling on a package cache redesign that he has said is effectively a _sparse_ mirror of the relevant channels: e.g., the full repodata.json for the channel, plus whatever packages have been specifically requested.

**Comment by mcg1969** [comment]
Ah, but indeed, @kalefranz's idea could be adapted to support what you're hoping to see, actually, e.g. cache preloading.

**Comment by ijstokes** [comment]
@mcg1969 what I meant was a sparse cache: that is filled as packages are installed, and in such a way that a local package cache has the same structure (at least logically) of a "full feature" conda package repository.

I got thinking more about this after reading your comments on the problem of cache contents being overwritten by same-named copies of packages from other channels that may not be the same, and the impact that would have on sym-links.

Also note: my file path example above was missing a critical piece: `channel`, which I've now added in.

**Comment by ijstokes** [comment]
I see where I was unclear, in writing:

> our package cache really should be creating a full mirror of repo.continuum.io

What I meant was that it should **incrementally** be creating a full/equivalent mirror of repo.continuum.io.

**Comment by mcg1969** [comment]
Great, it sounds like you and Kale are in very near agreement. The only issue here then is timeline. I do support the idea of reworking the cache!

**Comment by ijstokes** [comment]
Another thing this package cache reorganization may address is something I've been running into repeatedly: conda downloading packages again that I know I already have on my system.  Some example issues: #4611 #5953 

Assuming that there is some connection between conda re-downloading packages and conda not knowing exactly where a particular package on disk came from, a particularly vexing aspect of the current situation is that the #5953 situation borks out after 370 packages have been downloaded (a separate issue related to #5750), and trying to resolve that problem currently means repeatedly re-downloading all 370 packages.

**Comment by ijstokes** [comment]
@kalefranz I think you've picked up this topic in #5933, so I'll close this.

**Comment by kalefranz** [comment]
For the record, the extra downloading issue is a limitation of constructor + conda, and how we build installers. We need to figure out how to teach constructor about the uniqueness metadata for tarballs and extracted tarballs that conda relies upon.
