### ISSUE TITLE
Install lrutils package from local file

### ISSUE THREAD

**Issue by Isaacsh** [conda/conda#5892]
I am getting errors while trying to install a package locally (Windows 7 x64 machine):

`conda install --offline --file C:\Users\Isaac\Downloads\LandRegistry-lr-utils-alpha-0-g0999439.tar.gz`

Here is the output:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : C:\Users\Isaac\Anaconda3  (writable)
    default environment : C:\Users\Isaac\Anaconda3
       envs directories : C:\Users\Isaac\Anaconda3\envs
                          C:\Users\Isaac\AppData\Local\conda\conda\envs
                          C:\Users\Isaac\.conda\envs
          package cache : C:\Users\Isaac\Anaconda3\pkgs
                          C:\Users\Isaac\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64  (offline)
                          https://conda.anaconda.org/anaconda-fusion/noarch  (offline)
                          https://repo.continuum.io/pkgs/free/win-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/win-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/win-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-64  (offline)
                          https://repo.continuum.io/pkgs/msys2/noarch  (offline)

            config file : C:\Users\Isaac\.condarc
             netrc file : None
           offline mode : True
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.2 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\Isaac\Anaconda3\Scripts\conda-script.py install --offline --file C:\
Users\Isaac\Downloads\LandRegistry-lr-utils-alpha-0-g0999439.tar.gz`

    Traceback (most recent call last):
      File "C:\Users\Isaac\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Isaac\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Isaac\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Isaac\Anaconda3\lib\site-packages\conda\cli\install.py", line 190, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "C:\Users\Isaac\Anaconda3\lib\site-packages\conda\cli\common.py", line 551, in specs_from_url
        for line in open(path):
      File "C:\Users\Isaac\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 59: character maps to <undefined>

**Comment by thomasd57** [comment]
I am getting the same error, except 'in position 58:' 
Anaconda Navigator 1.6.2
lrutils-0.1.4.tar.gz from https://pypi.python.org/pypi/lrutils/0.1.4

**Comment by thomasd57** [comment]
Sorry, forgot my environment:
```
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : True
```

**Comment by kalefranz** [comment]
`LandRegistry-lr-utils-alpha-0-g0999439.tar.gz` is not a conda package.  Conda doesn't know how to handle `.tar.gz` files.
