### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by jkroes** [conda/conda#5898]
Fetching package metadata .........

# All requested packages already installed.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.13
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/justinkroes/anaconda  (writable)
    default environment : /Users/justinkroes/anaconda/envs/sphinx
       envs directories : /Users/justinkroes/anaconda/envs
                          /Users/justinkroes/.conda/envs
          package cache : /Users/justinkroes/anaconda/pkgs
                          /Users/justinkroes/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/justinkroes/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20

`$ /Users/justinkroes/anaconda/envs/sphinx/bin/conda install --revision=2`

    Traceback (most recent call last):
      File "/Users/justinkroes/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/justinkroes/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/justinkroes/anaconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/justinkroes/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 290, in install
        print_packages(action["PREFIX"], spec_regex)
    KeyError: 'PREFIX'

**Comment by kalefranz** [comment]
fixed with #6719 in 4.3.33
