### ISSUE TITLE
Python 3 conda environment defaulting to pip for Python 2

### ISSUE THREAD

**Issue by ryanriopelle** [conda/conda#5909]
I am trying to install the jupyterhub package using pip with a python 3 conda environment.  After creating the python 3 conda environment activate the environment via "source activate py3".  Within the python 3 environment pip continues to default to python 2, preventing me from installing jupyterhub. 

I have tried installing pip3 and re-installing pip doesn't work. 

(py36)[root@10-119-101-70 root]# source activate py36
discarding /tmp/riopery/miniconda3/envs/py36/bin from PATH
prepending /tmp/riopery/miniconda3/envs/py36/bin to PATH
(py36)[root@10-119-101-70 root]# pip install jupyterhub
Collecting jupyterhub
  Downloading jupyterhub-0.7.2.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 468kB/s
    Complete output from command python setup.py egg_info:
    ERROR: JupyterHub requires Python version 3.3 or above.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-26Xc4P/jupyterhub/

exit()
(py36)[root@10-119-101-70 root]# pip install -U --force-reinstall pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 416kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-9.0.1
(py36)[root@10-119-101-70 root]# pip install jupyterhub
Collecting jupyterhub
  Downloading jupyterhub-0.7.2.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 605kB/s
    Complete output from command python setup.py egg_info:
    ERROR: JupyterHub requires Python version 3.3 or above.

**Comment by kalefranz** [comment]
Can you prove to me it's actually a python3 environment?

    which -a python
    python --version
    which -a pip
