### ISSUE TITLE
update --all shouldn't list all installed packages

### ISSUE THREAD

**Issue by jrking123** [conda/conda#5911]
Hi, could the `conda update --all` command be changed to only show packages that are being updated instead of the entire list?

**Comment by kalefranz** [comment]
You mean it's showing packages that are *not* being updated?

**Comment by jrking123** [comment]
Yup - if there are no updates it lists all installed packages.

**Comment by kalefranz** [comment]
I see.  Yeah that does seem kind of weird.

**Comment by jrking123** [comment]
@kalefranz is there a switch I'm missing?

**Comment by kalefranz** [comment]
Not that I'm aware of, but there could be.  I haven't had time to investigate yet.

What is your use case here?  Are you trying to parse the output for some follow-on operation programmatically?  If so, the `--json` flag would be helpful, and the output could possibly be different in that case.

**Comment by jrking123** [comment]
It's just a script I run to keep my macOS updated (and know what has been changed). `Homebrew`, `pip` and so forth default to saying nothing - or something like "`No updates made`" nice and easy to read. I have several environments, so to see what changed, if anything, I've got to wade through multiple lists of stuff I already know is installed. :-)   Thanks

**Comment by kalefranz** [comment]
We should definitely improve this workflow.  Keeping this ticket open as a feature request.
