### ISSUE TITLE
Conda confused about version ordering?

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#5916]
When trying to update my env conda states that it's downgrading numba:
```
The following packages will be DOWNGRADED:

    numba:    0.35.0.dev-np113py36_207    numba  --> 0.35.0rc1-np113py36_15      numba
```

Whereas my reading of [PEP440](https://www.python.org/dev/peps/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering) would be that the LHS is 207 commits after the last release which came *before* `0.35.0` (i.e. `0.34.0.post207`) whereas the RHS is 15 commits after the release of `0.35.0rc1` and hence is a *newer* version.

This mattered because this made conda choose a bad install plan which I had to "fix" by pinning packages until numba was the package chosen to "downgrade"

**Comment by kalefranz** [comment]
Conda doesn't strictly follow PEP440 for various reasons.  See #2071 and https://github.com/conda/conda/blob/4.4.8/conda/models/version.py#L33-L141.
