### ISSUE TITLE
Conda commands don't show anything

### ISSUE THREAD

**Issue by shuklam20** [conda/conda#5927]
I installed Anaconda-4.4.0-Linux-x86_64 and it installed fine - I even edited my .bashrc file the way it needs to be. However, when I enter "conda" commands in my terminal, it doesn't display anything (Like in the image). I am using Ubuntu 14.04.

![screenshot from 2017-09-05 21 31 49](https://user-images.githubusercontent.com/18172899/30123932-98708fee-9301-11e7-97e4-13bb88f3ae4b.png)

**Comment by kalefranz** [comment]
What is the output of

    which -a conda
    cat $(which conda)
    which -a python

**Comment by kalefranz** [comment]
Probably same thing going on here as in https://github.com/conda/conda/issues/6314.  Please `unset PYTHONPATH`.
