### ISSUE TITLE
use kerberos for private channel

### ISSUE THREAD

**Issue by ptulpen** [conda/conda#5930]
Hello,
we use internal mirrors provided by an httpd (Works fine so far)
But now we want to make a internal channel where not everyone is able to access.
So I used Kerberos protected (used in other services as well) and with a browser this looks correct

But with conda I get 
CondaHTTPError: HTTP 401 UNAUTHORIZED for url [...]
and no user shown in httpd, so conda does not seem to be able to use kerberos

Is there a way to enable this?
Best regards, Peter

**Comment by kalefranz** [comment]
Conda does not currently support Kerberos auth. If we had a motivated contributor willing to go through a couple rounds of iteration in PR code review, that would be awesome. Otherwise adding in Kerberos support would probably be something driven by an enterprise or corporate sponsor.

**Comment by ptulpen** [comment]
Ah OK, thanks a lot for the quick answer

What other opportunities are there to protect ?
(the first which comes to my mind is basic auth like http://myuser:mypw@mymirror/foor/bar) but this is not an oportinuty for us, since the config will be public)

**Comment by mguillau** [comment]
Of course, whether it is a proper solution for you or not really depends on your context, but a possible way is to use AWS S3 to host your channel (conda channels hosted on s3 are already supported and specified using the "s3://" URL scheme).

Only users with access to your S3 bucket would be able to search and install packages stored there. Conda relies on the boto library for S3 operations so your users would have to install boto (outside of any conda environment) and configure it appropriately:
http://docs.pythonboto.org/en/latest/getting_started.html#configuring-boto-credentials

**Comment by ptulpen** [comment]
Hello,
well we solved it now by using a samba share, which is much easier to give ACLs to
