### ISSUE TITLE
fish shell requires adding ~/miniconda3/bin/ to $PATH in conda 4.4.0rc1 (unlike bash-shell-derivatives)

### ISSUE THREAD

**Issue by justlurking** [conda/conda#5935]
Edit:

Adding the following lines to my config.fish file fixed the problem on 4.3.25, and per @jaimergp this should also work on 4.4.0rc1:

```
# Conda startup script
source ~/miniconda3/etc/fish/conf.d/conda.fish

# Path to system Python3
set fish_user_paths $fish_user_paths /Library/Frameworks/Python.framework/Versions/3.6/bin/

# For Conda < 4.4.0 prepend Conda path to fish path (should be removable in Conda 4.4.0+)
set fish_user_paths $fish_user_paths ~/miniconda3/bin/
```
**However**, fish shell users don't yet have a shell script which allows for the removal of ~/miniconda3/bin/ from the system path (unlike bash shell).

### Edited the subject line to clarify the issue.
-------
Original issue text:

I've done a lot of digging into this and can't seem to figure it out. I see that conda previously had fish support (e.g. https://github.com/conda/conda/pull/545, #2611, #2680, #5182, etc.) but I'm not having any luck getting it to work on 4.40rc1 (Python 3.6 version for OS X).

`> source ~/miniconda3/etc/fish/conf.d/conda.fish` completes silently, without error.

Subsequently, running 'conda' from a fish shell results in the following:

```
> conda
fish: Unknown command 'conda'
conda.fish (line 2): 
        command conda
                ^
in function 'conda'
	called on standard input
```

I'm running macOS Sierra (10.12.6).

/cc some fish conda users to see whether any of you have tried 4.4.0 and are experiencing similar issues:
@jaimergp @zzag @soxofaan @rsully @alexbw @abhigenie92 @msarahan @kalefranz

**Comment by jaimergp** [comment]
I haven't tested v4.4 yet, but is it `~/miniconda3'` in `$PATH`?

**Comment by jaimergp** [comment]
Ok, I have downloaded v4.4 and it is working for me (very snappy!). Here are the steps I followed:

1 - Create a separate Miniconda3 installation and enable it in your `~/.config/fish/config.fish` with these lines:

     set -gx PATH ~/miniconda3/bin $PATH
     source ~/miniconda3/etc/fish/conf.d/conda.fish

2 - `git clone https://github.com/conda/conda.git && cd conda/ && git checkout 4.4.x`

3 - `conda install conda-build`

4 - `conda build conda.recipe`

5 - `conda install ~/miniconda3/conda-bld/linux-64/conda-4.3.25-py36h491242c_0.tar.bz2` (the actual name might change; check the build output). While the filename states that it's version 4.3.25, it's actually v4.4.

6 - `conda --version` just to make sure! In my case:

     > conda --version                                                                     
     conda 4.4.0rc1.post5+b500ffb7

**Comment by justlurking** [comment]
@jaimergp Thanks for weighing in. I guess there aren't too many brave fish users who have tried 4.4.0 yet. :worried:

I'm new to conda, but as I understand it based on @kalefranz's [Google Groups post](https://groups.google.com/a/continuum.io/d/msg/conda/VC32lgaTMpw/aCfOY0cvCQAJ) (and specifically the section of that post called "Conda Activate"), one of the benefits of 4.4.0 is no longer needing to manually fuss with setting / updating $PATH.

In fairness, he specifically calls out support for Bourne-derivative shells, so perhaps this is a known problem for fish shell users. Would be nice to see confirmation if that's the case. (Even better, a fix in the next 4.4.0 release!)

I ended up removing 4.4.0rc2 and installing 4.3.25. At first I had issues because I prepended the /miniconda3/bin/ path to $PATH (causing some issues when I wanted to access the system Python), but since I modified to appending that path, everything seems to be working well.

Addendum:
As I was the typing the above, I saw you were able to successfully install 4.4.0. Congrats! I take it you did not attempt to follow the exact instructions in Kale's post regarding no longer setting ~/miniconda3/bin/ in $PATH.

**Comment by jaimergp** [comment]
Hi! Yes, the `conda-canary` method is the same and easier. I just didn't know about it ^^'.

I have reviewed the included `conda.fish` script and it's nowhere similar to `profile.d/conda.sh`, so I guess that we `fish` users still need to prepend `$CONDA_PATH` to `$PATH` and use the old-style activation process. Maybe @kalefranz has something to say :)

**Comment by RustyRaptor** [comment]
HI I am using fish as well and I had this issue. Thanks for the fix.

**Comment by anton-matosov** [comment]
I am using fish (v2.5.0) and now starting with conda (4.3.30) and I had to add
```
set -gx PATH $HOME/anaconda3/bin $PATH
source $HOME/anaconda3/etc/fish/conf.d/conda.fish
```
to config.fish to make conda work in fish nicely

**Comment by kalefranz** [comment]
Hey fish folks, finally able to get a fish wrapper that takes into account all the improvements in 4.4.

https://github.com/conda/conda/pull/6475

I'm inclined to merge that PR where it stands at this point, and then let you folks continue to iterate on it.  I'm sure it's far from perfect.  It at least seems functional to me though.

We'll probably be releasing 4.4.0 into defaults soon.

Happy to have input on #6475 though, or follow-on PRs.
