### ISSUE TITLE
Installation problem at "conda create"

### ISSUE THREAD

**Issue by kalessinlord** [conda/conda#5946]
I have proglem by 
conda create -n obspy python=2.7
Following message can be seen and obspy is not installed. The environment is the latest windows OS

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\kales\.condarc
           offline mode : False

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py create -n obspy python=2.7`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not rename u'C:\\ProgramData\\Anaconda2\\pkgs\\wheel-0.29.0-py27_0.tar.bz2.part' to u'C:\\ProgramData\\Anaconda2\\pkgs\\wheel-0.29.0-py27_0.tar.bz2': WindowsError(183, '\x8a\xf9\x82\xc9\x91\xb6\x8d\xdd\x82\xb7\x82\xe9\x83t\x83@\x83C\x83\x8b\x82\xf0\x8d\xec\x90\xac\x82\xb7\x82\xe9\x82\xb1\x82\xc6\x82\xcd\x82\xc5\x82\xab\x82\xdc\x82\xb9\x82\xf1\x81B')

**Comment by kalefranz** [comment]
Conda 4.2 is no longer supported.  Please `conda update conda`.  If you continue to have a problem, please file a new issue.
