### ISSUE TITLE
Basemap installs but is not seen by Python

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#5952]
Creating a conda env with `basemap` named as one of the packages installs cleanly, but results in the following when basemap is imported:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-db00e19d8b31> in <module>()
----> 1 import basemap

ModuleNotFoundError: No module named 'basemap'
```

I've added `conda-forge` and `anaconda` to the channels list, and have confirmed that basemap is in the `share` subdir in the env.

Conda reports that the package is installed:

```
$ conda install -c conda-forge basemap
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/fonnescj/anaconda3/envs/bios8366:
#
basemap                   1.1.0                    py36_2    conda-forge
```

Running Python 3.6 on macOS 10.12.

**Comment by kalefranz** [comment]
This issue was moved to conda-forge/basemap-feedstock#22

**Comment by ocefpaf** [comment]
There is no modulo to import as `basemap`. It is `import mpl_toolkits.basemap `, more info in the docs: https://matplotlib.org/basemap/
