### ISSUE TITLE
CondaHTTPError and SSLError

### ISSUE THREAD

**Issue by melanus** [conda/conda#5956]
Anytime I try to update, install, or create an environment in conda, it always comes up with this error:

> Fetching package metadata ...
> CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
> Elapsed: None

> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> SSLError(SSLError("Can't connect to HTTPS URL because the SSL module is not available.",),) 

I have tried setting the ssl_verify to false, but that provides no solution.

**Comment by kalefranz** [comment]
> SSL module is not available

It seems you've managed to delete `openssl` or `pyopenssl` somehow.  You haven't provided any additional information (like `conda info`), so I can't give you specific instructions, but the easiest solution will likely be to just reinstall the correct version of miniconda overtop your current install.

**Comment by StinkyLord123** [comment]
thanx, i installed fresh anaconda, but i had this issue, now that i installed miniconda on top, it solved the issue.
