### ISSUE TITLE
Cannot modify .condarc from terminal

### ISSUE THREAD

**Issue by Isaacsh** [conda/conda#5961]
I wanted to set proxy_servers configs in .condarc from terminal by

`conda config --set proxy_servers http: http://[user]:[pass]@naproxy.[something].com:80/`

but it says

`bash: !@naproxy.[something].com: event not found`

I can confirm it's not set by

`conda config --show`

which gives me

`proxy_servers: {}`

How can I set configs from within terminal?

Thanks

**Comment by kalefranz** [comment]
Yeah, because your shell is doing expansion there.  Easiest is just to edit your `~/.condarc` file with a text editor for this case.  Also, `conda config` hasn't been enabled for map-type parameters like `proxy_servers`.

**Comment by Isaacsh** [comment]
What if you do not access to .condarc file directly? How can one edit that file through shell?
