### ISSUE TITLE
Strange representation of OrderedDict in iPython

### ISSUE THREAD

**Issue by fatalispm** [conda/conda#5962]
I am not even sure if this is an issue, though I found this behaviour misleading and it actually differs from other environments I have used. I am using: **Python 3.6.1 |Anaconda 4.4.0 (x86_64)** and **IPython 5.3.0**. 
```
from collections import Counter, OrderedDict 

class F(Counter, OrderedDict):
   pass
words = ['hello', 'my', 'hello', 'world', 'absd']

F(words) # result F({'absd': 1, 'hello': 2, 'my': 1, 'world': 1})

```
While both **repr(F)** and **str(F)** return correct representation: **"F({'hello': 2, 'my': 1, 'world': 1, 'absd': 1})"**

I think the correct behaviour is that it should use **__repr__**, otherwise it's quite misleading.

**Comment by jakirkham** [comment]
This doesn't feel like a `conda` issue. Were you meaning to raise this with IPython maybe? 😕

**Comment by fatalispm** [comment]
Actually, it worked this way only in conda. On other Python implementations it works as expected.

**Comment by jakirkham** [comment]
In which case it may be a packaging issue and should be raised at the [anaconda-recipes repo]( https://github.com/ContinuumIO/anaconda-recipes ) instead.

**Comment by fatalispm** [comment]
@jakirkham Great, thanks, I was struggling to find appropriate repository for this.
