### ISSUE TITLE
conda clean -p should remove duplicate pacakge when there is multiple cache

### ISSUE THREAD

**Issue by nouiz** [conda/conda#5967]
We have an environment where we have a local installation of anaconda shared by many user on each computer. If user create an env and the shared installation do not contain the most up to date version of the packages, they will download new packages in there home. When we update later the shared conda installation, we end up with some packages duplicated in the home under "~/.conda/pkgs" and the in shared installation.

"conda clean -p" should update existing user env to point to the shared installation and delete from there home the duplicate packages.

This would remove much disk access to the home directory that is remote.

I don't know a good/easy enough manual way of doing this. Having this would help in the meantime.

I think the manual way to do this cleanly is:
- Find ourself which packages they have duplicate (very hard, each user create env at different time)
- ask user to uninstall the duplicate packages from all there env
- then do "conda clean -a"
- then reinstall the duplicate packages.

Do you think of a better way of doing this?

**Comment by kalefranz** [comment]
The `conda clean` command will not be mutating existing environments.  Sorry, but pretty much a non-starter for a feature request.
