### ISSUE TITLE
Support OpenBSD

### ISSUE THREAD

**Issue by plavcik** [conda/conda#5968]
maintainer note: Repurposing this issue as a general tracking ticket for OpenBSD support in conda.

---

on OpenBSD 6.1 these things are blocking installation from  Miniconda3-latest-Linux-x86_64.sh

- URL to bash is hardcoded
- licence count with OpenSSL, but LibreSSL is used on OpenBSD
- md5sum is expected, but md5 is available

FYI MD5 is not safe anymore, please switch to sha256

Is there other way, how to install miniconda ? thank you

**Comment by kalefranz** [comment]
I don't know what the libc details are on FreeBSD and OpenBSD, but I'm guessing the linux build outs of most repositories, including `defaults` (i.e. repo.continuum.io), are not compatible with the BSDs.

Would be lovely to have it.  On the wish list.

**Comment by kalefranz** [comment]
By the time we have compatible packages, the installer issues you enumerated will have long been resolved.  Specifically,

> URL to bash is hardcoded

The installer has already been converted to posix-compliant shell.

> licence count with OpenSSL, but LibreSSL is used on OpenBSD

Irrelevant.  Most conda environments link against their own ssl flavor.

> md5sum is expected, but md5 is available. FYI MD5 is not safe anymore, please switch to sha256

In conda, md5 is only used as a check of download integrity.  The use of md5 is NOT meant to be a security feature.  For the full flow of package delivery, sha256 is only marginally more "secure," if you're using that hash as a security feature.

It's my emphatic hope that we'll be implementing TUF package signing in the near future.

**Comment by justlurking** [comment]
> It's my emphatic hope that we'll be implementing TUF package signing in the near future.

This would be amazing. Would it cover all anaconda-hosted packages, just Anaconda / conda itself, or something in-between?

**Comment by kalefranz** [comment]
Package signing is going to be opt-in for package builders.  Of course, I'm sure most/all of repo.continuum.io will have signatures once we roll it out.  conda-forge and anaconda.org in general might be different / take longer.  We're going to have to build out tools for package builders to manage their key infrastructure I'm guessing.  Or at least provide a solid best-practices document.  The code powering anaconda.org will also probably have to be augmented in some ways.

I think it's all coming.  It's a process though.

**Comment by kalefranz** [comment]
P.S. This really isn't the ticket we should be discussing TUF on, even though it kind of touched on it.  For more TUF discussion, including 👍 votes, go to https://github.com/conda/conda/issues/5282
