### ISSUE TITLE
Uninstalling Anaconda: AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by chenggong03** [conda/conda#5970]
Hi! I want to uninstall Anaconda on Mac (to cleanup some space): I heard I need to remove config first `conda install anaconda-clean` `anaconda-clean --yes`, then remove the folder. So when I try to`conda install anaconda-clean`, I got the following. My Python version is Python 3.4.5 :: Anaconda 2.3.0 (x86_64). What should I do?

> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
> https://github.com/conda/conda/issues
> 
> Traceback (most recent call last):
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
>     return_value = func(*args, **kwargs)
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 85, in _main
>     from ..base.context import context
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/base/context.py", line 20, in <module>
>     from ..common.disk import try_write, conda_bld_ensure_dir
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/common/disk.py", line 16, in <module>
>     from ..utils import on_win
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/utils.py", line 11, in <module>
>     from .common.url import path_to_url
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/common/url.py", line 21, in <module>
>     from requests.packages.urllib3.exceptions import LocationParseError
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/__init__.py", line 52, in <module>
>     from .packages.urllib3.contrib import pyopenssl
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
>     import OpenSSL.SSL
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import rand, crypto, SSL
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/SSL.py", line 124, in <module>
>     SSL_ST_INIT = _lib.SSL_ST_INIT
> AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/gongcheng/anaconda/bin/conda", line 6, in <module>
>     sys.exit(conda.cli.main())
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 165, in main
>     return conda_exception_handler(_main, *args)
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
>     print_unexpected_error_message(e)
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
>     info_stdout, info_stderr = get_info()
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 413, in get_info
>     args.func(args, p)
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/cli/main_info.py", line 156, in execute
>     from conda.api import get_index
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/api.py", line 7, in <module>
>     from .fetch import fetch_index
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 12, in <module>
>     import requests
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/__init__.py", line 52, in <module>
>     from .packages.urllib3.contrib import pyopenssl
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
>     import OpenSSL.SSL
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import rand, crypto, SSL
>   File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/SSL.py", line 124, in <module>
>     SSL_ST_INIT = _lib.SSL_ST_INIT
> AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by kalefranz** [comment]
`conda info` ?

**Comment by chenggong03** [comment]
conda info: (thank you for reviewing my problem!)

> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> `$ /Users/gongcheng/anaconda/bin/conda info`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 85, in _main
>         from ..base.context import context
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/base/context.py", line 20, in <module>
>         from ..common.disk import try_write, conda_bld_ensure_dir
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/common/disk.py", line 16, in <module>
>         from ..utils import on_win
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/utils.py", line 11, in <module>
>         from .common.url import path_to_url
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/conda/common/url.py", line 21, in <module>
>         from requests.packages.urllib3.exceptions import LocationParseError
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/__init__.py", line 52, in <module>
>         from .packages.urllib3.contrib import pyopenssl
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
>         import OpenSSL.SSL
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
>         from OpenSSL import rand, crypto, SSL
>       File "/Users/gongcheng/anaconda/lib/python3.4/site-packages/OpenSSL/SSL.py", line 124, in <module>
>         SSL_ST_INIT = _lib.SSL_ST_INIT
>     AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
>

**Comment by kalefranz** [comment]
I have no idea what's going on here, but you're using some pretty old packages I think.  Might be easiest just to start over with a new Miniconda or Anaconda installer.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
