### ISSUE TITLE
noarch for Python 2 or 3 only

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5971]
Would be great if it were possible to have `noarch` packages that are Python 2 only or Python 3 only. Some Google Python libraries will likely remain Python 2 only and it would be nice to still have a `noarch` option for them. Also some of the core SciPy stack is moving to Python 3 only and it would be nice to still have a `noarch` option for them as well.

**Comment by jakirkham** [comment]
cc @msarahan

**Comment by jakirkham** [comment]
Also @takluyver may find this one interesting.

**Comment by takluyver** [comment]
Do `noarch: python` packages specify a dependency on Python itself?

**Comment by jakirkham** [comment]
Yes, but IIUC they can't constraint the version. Though would be happy to hear I'm incorrect.

**Comment by mbargull** [comment]
@jakirkham 
> Yes, but IIUC they can't constraint the version. Though would be happy to hear I'm incorrect.

Feel free to be happy ;). For `noarch: python` packages I had no trouble with `- python >=3.4` or the like. With `conda-build 2.x` there were some issues for non-`noarch: python` packages. Last time I checked (then with `conda-build 3.0.0beta1`) there were no issues whatsoever, no matter if `noarch` or not.
For me, combining `noarch: python` with version constrains on `python` has been fine for `conda-build` `2.x` and `3.x`, see https://github.com/conda/conda-build/issues/1962#issuecomment-297663035.

**Comment by kalefranz** [comment]
I think the core contributors generally agree that we need to introduce some limited selector-type ability into the noarch package concept.  It's on the TODO list.

**Comment by kalefranz** [comment]
At this point, the only thing that might be needed here is some help from conda-build with the build_string.  E.g. if the python version is constrained to `>=3,<4`, the build_string should probably be `py3_0` instead of `py_0`.

**Comment by mbargull** [comment]
This works fine in `conda` for a long time now, hence this is the wrong issue to necrobump :wink:.
I understand the need and desire for this feature, but the comments you referenced still hold true.
The only thing I can add, is that it's possible to add Python 3-only `noarch: python` packages to conda-forge **if they are not affected by https://github.com/conda/conda-build/pull/2672**, see https://github.com/conda-forge/pyscaffold-feedstock/blob/02b91712d911c593f0b9933fcd27a37aa7b0d9d2/recipe/meta.yaml for an example. Otherwise, anything else should be directed towards conda-forge.

**Comment by leycec** [comment]
> This works fine in `conda` for a long time now, hence this is the wrong issue to necrobump :wink: .

`</sigh>`

You're right, of course. Why are project maintainers always right?

> The only thing I can add, is that it's possible to add Python 3-only `noarch:` python packages to conda-forge if they are not affected by conda/conda-build#2672...

**O.K.,** that's super helpful. If I read your pull request right,<sup>i probably didn't</sup> then conda-forge already implicitly supports *all* Python 3-only `noarch:` python packages *except* those "...that include scripts in `bin` (`Scripts`)." Forgive my profoundly obvious ignorance, but which `meta.yaml` settings does that exception apply to? Specifically, would that be recipes with a:

* `build/entry_points` key in `meta.yaml`? I suspect "Nope.", as the [example recipe](https://github.com/conda-forge/pyscaffold-feedstock/blob/02b91712d911c593f0b9933fcd27a37aa7b0d9d2/recipe/meta.yaml) you kindly reference defines this key. Which would be awesome, as we define entry points too.
* `outputs` list item defining the `name`, `script`, and `script_interpreter` keys in `meta.yaml`?
* `bld.bat` or `build.sh` scripts?
* None of the above? I couldn't find reference to `bin` or `Scripts` elsewhere, but... I'm fairly new to the (Ana|Mini)conda ecosystem. In other words, no one should listen to me.

Thanks again, @mbargull. And, yes: I'll stop necro-ing this issue now. That does it for me! (*Phew.*)

**Comment by mbargull** [comment]
> Why are project maintainers always right?

No maintainer, just a happy contributor :wink:.

> but which `meta.yaml` settings does that exception apply to?

None, it's the `scripts` argument for `distutils.core.setup`/`setuptools.setup` in `setup.py`.

> I'll stop necro-ing this issue now.

:+1: :wink:
