### ISSUE TITLE
Error while creating tensor environment in Condas

### ISSUE THREAD

**Issue by psoham25** [conda/conda#5972]
I am trying to use Tensor Via Anacondas to run machine learning Algos in C++ language. While attempting to create a tenfor enviornment in Condas as per the following link : 

https://www.tensorflow.org/install/install_windows

M getting the following error.
Error: ModuleNotFoundError : 'condas.gateways.disk.test'

Can you debug this error for me?

**Comment by kalefranz** [comment]
Without substantially more information, it's impossible to help.  Perhaps try asking for help in a conda support forum somewhere.  Although I'd recommend giving people the full set of instructions on how to reproduce your error.
