### ISSUE TITLE
noarch for pure R packages

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5974]
Would be nice if there was a `noarch: r` option to allow R packages to be built for all platforms and (if possible) without a specific dependence on R version.

**Comment by mingwandroid** [comment]
It is worth investigating for sure.

**Comment by jakirkham** [comment]
For others following along, some work on making the layout of R on different platforms match is occurring in PR ( https://github.com/conda-forge/r-base-feedstock/pull/43 ).
