### ISSUE TITLE
Building conda packages with conda skeleton

### ISSUE THREAD

**Issue by cprogrammer1994** [conda/conda#5977]
Hello,

I run into a problem with _Building conda packages with conda skeleton_.

According to the [documentation](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html) the following snippet should work:

```
conda skeleton pypi pyinstrument
```

however i get the following error:

```bash
>d:\Anaconda3\Scripts\conda.exe skeleton pypi pyinstrument
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: argument command: invalid choice: 'd:\\Anaconda3\\Scripts\\conda-script.py' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```

Please note that my conda install is not on the `PATH` but I call the conda.exe directly. What should I do to get this work?

Am I calling the wrong executable or what folder do I need to be on the PATH?

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2388
