### ISSUE TITLE
conda install --download-only feature

### ISSUE THREAD

**Issue by mahmoud** [conda/conda#5983]
Right now we have `--dry-run`, but is there a way to actually download the `.tar.bz2` files into `pkgs` without installing them? If not, can there be? 

`--download-only` is one design with precedent, but also maybe as a separate subcommand, like `pip download`. The overarching goal is to get `pkgs` populated with all the dependencies necessary for an application and freezing it out into something akin to [a wheelhouse](https://pip.pypa.io/en/stable/reference/pip_wheel/#examples) for reproducible installs ([a la](https://www.paypal-engineering.com/2016/09/22/python-by-the-c-side/)). 

Thanks in advance!

**Comment by kalefranz** [comment]
Yeah we need this. It's been on the roadmap for the API for a while. Actually is trivial to implement at this point. I'll make sure it gets into 4.4.
