### ISSUE TITLE
Issue installing mayavi in fresh install of Anaconda

### ISSUE THREAD

**Issue by tjiagoM** [conda/conda#5985]
I am using Ubuntu 16.04, 64-bit. 

I have just installed Anaconda (Anaconda2-4.4.0). The first thing I tried to do was running the following command:
`$ conda install mayavi`

And I got the following output:
```
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - mayavi
  - navigator-updater
  - pywavelets
Use "conda info <package>" to see the dependencies for each package.
```

As you can see, the error doesn't really explain anything. I had to do this to actually install mayavi:
```bash
$conda create --name mymayavi python=2
$source activate mymayavi
$conda install mayavi
```

Why can't I install mayavi with a simple `conda install` when I have a completely fresh anaconda installation? 

Does the error mean that I cannot have `navigator-updater` and `pywavelets` installed to install mayavi? If that's the case, or other case, please make this output more readable.

**Comment by pieroguerrero** [comment]
I have the same issue but mine says:

UnsatisfiableError: The following specifications were found to be in conflict:
  - bottleneck
  - mayavi
  - navigator-updater
Use "conda info <package>" to see the dependencies for each package.

Don't know how to proceed

**Comment by tjiagoM** [comment]
@robgics Note that by running

`conda install pyqt=4`

you will be downgrading pyqt to the one needed by mayavi, thus kinda overriding the conflicts.

**Comment by robgics** [comment]
(my_test) 1 r262@r262:~$ conda install pyqt=4
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - navigator-updater -> pyqt >=5.6 -> qt 5.6.* -> icu 54.*
  - pyqt 4* -> qt >=4.8.6,<5.0
  - pyqt 4* -> sip >=4.16.4,<4.18
Use "conda info <package>" to see the dependencies for each package.


Hmm...Conda isn't easily fooled.

**Comment by robgics** [comment]
Humorously, I just did "pip install mayavi", and after it barfed because vtk wasn't there ("conda install vtk"), then it installed just fine and imports into python.  That seems the easiest way around it, but I don't know that it's the best.

**Comment by tjiagoM** [comment]
Ok, that's curious, because I did that and it worked. I don't remember well, but I might have done that with a fresh virtual environment anyway, and maybe for python3. Sorry about that, I confused the actual situation where I used that command. My issue is still pertinent, then.

**Comment by tjiagoM** [comment]
Oh, I think that the easiest thing is what I did when describing the issue: just do the `conda create --name mymayavi python=2` to have a new environment. It worked with me.

**Comment by muvic08** [comment]
I am having the same issue:

> $ conda install -c anaconda mayavi
> UnsatisfiableError: The following specifications were found to be in conflict:
>      - mayavi
>      - navigator-updater
>      - pywavelets
> Use "conda info <package>" to see the dependencies for each package.

**Comment by kalefranz** [comment]
Unlink pip, conda won't let you install packages into the same environment that it knows to be incompatible.  Pip will go ahead and install things for you, only for you to find a couple days or weeks later that your environment is incredibly broken, and by that time, there's no real way to connect the problem back to the root cause.

For problems with satisfiability, by far the easiest way is to create a new environment that specific to the individual task.

**Comment by tjiagoM** [comment]
@kalefranz That is true. Still, I created this issue because I think there is space for improvement. The error doesn't explain a lot and could be better rather than just showing to go into the `conda info` kind of instructions.

**Comment by kalefranz** [comment]
Check out all the issues labeled https://github.com/conda/conda/labels/tag%3Asolver-messaging

They're all getting at exactly this :)

**Comment by fosterseth** [comment]
Ok what worked for me
conda uninstall pyqt

warning -- it will seemingly uninstall any package that depends on pyqt, so this might be a good solution if you have a lot of packages to reinstall

then conda install mayavi=4.5.0

on centos7, python 2.7

**Comment by ibadurrahmanJKT** [comment]
I've tried many ways to clear this issue. 

In the end, I install mayavi via this command and it worked without using a new environment nor uninstalling any packages.

`conda install -c menpo mayavi `

**Comment by jagomd** [comment]
After trying and failing several times to fix this issue. I removed Anaconda altogether then with a freshly installed Miniconda `$ conda install mayavi` went smoothly. 

Specss: Miniconda 2.7 for Windows 8 64-bit
