### ISSUE TITLE
ImportError: No module named packages.urllib3.util

### ISSUE THREAD

**Issue by ericsmoll** [conda/conda#5987]
Hello, 

I am installing a program called "ambertools" which builds miniconda. The install has failed with the suggestion that I report the error at "https://github.com/conda/conda/issues". Can anyone help me resolve this problem? 

Best,
Eric

```
Deleting existing miniconda at ./miniconda
Installing Miniconda Python.
PREFIX=/home/ericsmoll/programs/amber/ambertools/amber16/miniconda
installing: python-2.7.13-0 ...
installing: cffi-1.9.1-py27_0 ...
installing: conda-env-2.6.0-0 ...
installing: cryptography-1.7.1-py27_0 ...
installing: enum34-1.1.6-py27_0 ...
installing: idna-2.2-py27_0 ...
installing: ipaddress-1.0.18-py27_0 ...
installing: libffi-3.2.1-1 ...
installing: openssl-1.0.2k-0 ...
installing: pyasn1-0.1.9-py27_0 ...
installing: pycosat-0.6.1-py27_1 ...
installing: pycparser-2.17-py27_0 ...
installing: pyopenssl-16.2.0-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.12.4-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_1 ...
installing: setuptools-27.2.0-py27_0 ...
installing: six-1.10.0-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.3.11-py27_0 ...
installing: pip-9.0.1-py27_1 ...
installing: wheel-0.29.0-py27_0 ...
Python 2.7.13 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Updating and installing required and optional packages...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "./miniconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 559, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 518, in get_info
    from conda.cli import conda_argparse
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 14, in <module>
    from .read import get_json_content
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 22, in <module>
    from ...models.channel import Channel
  File "/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
ImportError: No module named packages.urllib3.util
```

**Comment by kalefranz** [comment]
`conda info` ?

**Comment by kalefranz** [comment]
Also, `python -c "import requests; print(requests.__version__)"`

**Comment by kalefranz** [comment]
Technically, this isn't an issue with conda.  `requests` is either the wrong version or not there.  I guess it's the installer that messed up.  Not sure what ambertools is or if it's using constructor or something else.

Still, I know this particular import stack trace has been completely avoided in later versions of conda 4.3, because we're vendoring urllib3.

**Comment by ericsmoll** [comment]
[ amber16 ] PRECISION $ conda info
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ /home/ericsmoll/programs/amber/ambertools/amber16/miniconda/bin/conda
info`




    Traceback (most recent call last):
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/exceptions.py",
line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/main.py",
line 92, in _main
        p, sub_parsers = generate_parser()
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/main.py",
line 51, in generate_parser
        from ..cli import conda_argparse
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py",
line 15, in <module>
        from .common import add_parser_help
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/cli/common.py",
line 19, in <module>
        from ..core.linked_data import linked_data
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/core/linked_data.py",
line 11, in <module>
        from ..gateways.disk.delete import rm_rf
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/gateways/disk/delete.py",
line 14, in <module>
        from .read import get_json_content
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/gateways/disk/read.py",
line 22, in <module>
        from ...models.channel import Channel
      File
"/home/ericsmoll/programs/amber/ambertools/amber16/miniconda/lib/python2.7/site-packages/conda/models/channel.py",
line 6, in <module>
        from requests.packages.urllib3.util import Url
    ImportError: No module named packages.urllib3.util

**Comment by ericsmoll** [comment]
[ amber16 ] PRECISION $ python -c "import requests;
print(requests.__version__)"
2.2.1

**Comment by kalefranz** [comment]
I was expecting a requests version > 3.  Instead it's a really old version of 2.  According to your output above though,

    installing: requests-2.12.4-py27_0 ...

I don't think this is something a change to conda code can help with at this point.  Maybe try the ambertools issue tracker?

**Comment by karinlah** [comment]
I had the same issue, on Ubuntu machine and the problem was that the Ubuntu OS is using urilib3 as well, so it didn't recognize the package installed through pip.
The solution was to remove the ubunto urllib3 package and install it again with pip:
```
apt-get remove python-urllib3 
sudo pip install urllib3 
```
