### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict

### ISSUE THREAD

**Issue by yuhangpan** [conda/conda#5989]
when i tried to install netCDF4 in a new environment, this happened

UnsatisfiableError: The following specifications were found to be in conflict:
  - hdfeos5 -> hdf5 1.8.18|1.8.18.*
  - netcdf4 -> hdf5 1.8.9
This environment was built for using pyNGL and pyNIO 
Anyone know how to solve? 
Thanks

**Comment by kalefranz** [comment]
Please provide all details, step-by-step, on how to reproduce your problem.
