### ISSUE TITLE
Updating packages in main environment fails.

### ISSUE THREAD

**Issue by bozso11** [conda/conda#5990]
Have a standard Anaconda install, tried to update all  packages.

c:\Users\212572626>  conda-env update --name=root -vv
DEBUG conda.cli.main:init_loggers(98): verbosity set to 2
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\Users\212572626\AppData\Local\Continuum\Anaconda3' using path 'C:\Users\212572626\AppData\Local\Continuum\Anaconda3\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\Users\212572626\AppData\Local\Continuum\Anaconda3' using path 'C:\Users\212572626\AppData\Local\Continuum\Anaconda3\conda-meta\history'
Current conda install:

               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\212572626\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\212572626\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\212572626\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\212572626\AppData\Local\conda\conda\envs
                          C:\Users\212572~1\BOXSYN~1\_NOTSH~1\Programs\MOBAXT~1.4\.conda\envs
          package cache : C:\Users\212572626\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\212572626\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\212572626\AppData\Local\Continuum\Anaconda3\Scripts\conda-env-script.py update --name=root -vv`

    Traceback (most recent call last):
      File "C:\Users\212572626\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\212572626\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\cli\main_update.py", line 70, in execute
        directory=os.getcwd())
      File "C:\Users\212572626\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Invalid name, try the format: user/package

**Comment by kalefranz** [comment]
Could you also supply the contents of your `environment.yml` file?

**Comment by bozso11** [comment]
Here it is.

Thanks for looking into this!

**Comment by kalefranz** [comment]
I don't see the requested information?

**Comment by bozso11** [comment]
Apologies, this fell out of my radar. I've zipped it & attached.
[environment_root.zip](https://github.com/conda/conda/files/1393729/environment_root.zip)
