### ISSUE TITLE
conda install pymol failed

### ISSUE THREAD

**Issue by footballboy1986** [conda/conda#5993]
Hi, 
when I tried to use conda install pymol, I got this information.
Does anyone have answers for it? Many thanks!
--------------------------------------------------------------
conda install pymol-v1.8.6.0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/yaojun/anaconda  (writable)
    default environment : /Users/yaojun/anaconda
       envs directories : /Users/yaojun/anaconda/envs
                          /Users/yaojun/.conda/envs
          package cache : /Users/yaojun/anaconda/pkgs
                          /Users/yaojun/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/yaojun/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 502:20

`$ /Users/yaojun/anaconda/bin/conda install pymol-v1.8.6.0.tar.bz2`

    Traceback (most recent call last):
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 210, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/misc.py", line 100, in explicit
        link_names = {index[d]['name'] for d in link_dists}
      File "/Users/yaojun/anaconda/lib/python3.6/site-packages/conda/misc.py", line 100, in <setcomp>
        link_names = {index[d]['name'] for d in link_dists}
    KeyError: Dist(_Dist__initd=True, channel='<unknown>', dist_name='pymol-v1.8.6.0', name='pymol', version='v1.8.6.0', build_string='', build_number=0, with_features_depends=None, base_url='file:///Users/yaojun/Downloads', platform=None)

**Comment by kalefranz** [comment]
The file `pymol-v1.8.6.0.tar.bz2` does not exist in your current working directory.

**Comment by kalefranz** [comment]
You may have just meant `conda install pymol` or `conda install pymol=1.8.6`

**Comment by footballboy1986** [comment]
I found the problem is that pymol need python27 environment, while my conda is Python3. After activation Python27 environment, pymol was successfully installed.

From mobile device, please excuse my typos



On Mon, Oct 2, 2017 at 11:48 PM +0200, "Kale Franz" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #5993<https://github.com/conda/conda/issues/5993>.
