### ISSUE TITLE
Release notes on docs page outdated

### ISSUE THREAD

**Issue by cdeil** [conda/conda#5996]
At https://conda.io/docs/release-notes.html the latest release shown is 2017-07-21 4.3.23

But at https://github.com/conda/conda/blob/master/CHANGELOG.md#4325-2017-08-16 it says that 4.3.25 (2017-08-16) was released a month ago.

Is there an issue with the update of the release notes in the docs?

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-docs#490
