### ISSUE TITLE
conda env create error

### ISSUE THREAD

**Issue by vanine6** [conda/conda#5998]
I am trying to create an environment with the command
"conda env create -f requirenents/aind-dog-mac.yml 
and got the following error message:
"ResolvePacka"geNotFound
rise 4.0.0b1 py35_0"
I tried to instal rise, but it is not found.
Thanks,
Vanine

**Comment by kalefranz** [comment]
Please provide the output of `conda info` and the contents of your file `requirenents/aind-dog-mac.yml`
