### ISSUE TITLE
Conda command is very slow

### ISSUE THREAD

**Issue by nbren12** [conda/conda#6000]
I would like to use some `conda info` commands in my bashrc, but each invocation of conda takes over .5 seconds on my system. Is there any way to speed this up?

**Comment by kalefranz** [comment]
This should be substantially improved already in conda 4.4

**Comment by nbren12** [comment]
Okay.  I guess I will just wait until v 4.4 shows up on anaconda.org.

**Comment by kalefranz** [comment]
4.4.0rc1 is available in the `conda-canary` channel.  There are a few known bugs.  The most serious is if you are currently using or in the past have used private channels (that include tokens) on anaconda.org.

**Comment by kalefranz** [comment]
I'm not sure `conda info` is every going to be fast enough to use in your bashrc, unfortunately.  What types of information are you wanting to pull out?  Maybe we can help in other ways...

**Comment by nbren12** [comment]
I was thinking about using  `conda info --root` in my bashrc. But there are many trivial ways to get that info.

**Comment by kalefranz** [comment]
Yeah for that `python -c "import sys; print(sys.prefix)"` is probably easiest.  I frankly didn't even know `--root` was a flag on `conda info`.  So many rando and untested flags that *still* keep popping up 😳

**Comment by nbren12** [comment]
yup. i saw it some random place on the interwebs, and thought ...hey I'll
put that in my bashrc (actually config.fish) file.

**Comment by justlurking** [comment]
> 4.4.0rc1 is available in the conda-canary channel. There are a few known bugs.

@kalefranz Is rc2 dropping any time soon? Had some issues with rc1 and reverted back to 4.3. Sorry for the off-topic comment - not sure if there's a better place to ask.

**Comment by kalefranz** [comment]
Hopefully, yes.  The expired token issue is especially frustrating, I know.  We've all been heads down getting Anaconda 5.0 out, and conda 4.4 got put on hold until that happened.  I'm at least part-time back on conda now.

**Comment by jaimergp** [comment]
> Yeah for that python -c "import sys; print(sys.prefix)" is probably easiest. I frankly didn't even know --root was a flag on conda info. So many rando and untested flags that still keep popping up :flushed:

Oh shit, and all this time I thought my fish installation was _simply_ slow. It was `conda info --root` slowing that down! I replaced that with your proposal and god, what a difference. Thanks!

**Comment by kalefranz** [comment]
Closing this issue.  I think we've done all we can to improve startup time and be conservative with imports until needed in conda 4.4.
