### ISSUE TITLE
Miniconda Python 2.7 | 64-bit Install Error on Windows 10

### ISSUE THREAD

**Issue by jason061938** [conda/conda#6003]
Hi,

I went here: https://conda.io/miniconda.html and downloaded the Miniconda Python 2.7 | 64-bit (exe installer) for Windows (Miniconda2-latest-Windows-x86_64.exe). However, attempting to run the installer results in the following error:

NSIS Error
Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy.

I'm on Windows 10 Home (64 bit). Help resolving this issue would be greatly appreciated. Thank you.

**Comment by kalefranz** [comment]
Did you try downloading the package a couple more times?  Do the checksums match?  Correct checksums given at https://repo.continuum.io/miniconda/

**Comment by jason061938** [comment]
Thank you. I have tried downloading the package a couple more times now. The checksums do not match actually. Verified using CertUtil utility.

**Comment by kalefranz** [comment]
Please provide detailed step-by-step instructions on how to reproduce your issue.

**Comment by jason061938** [comment]
I've since downloaded Anaconda. and am using that. Thank you for your time.
