### ISSUE TITLE
How to fix the Warning: Calling fails_with :llvm is deprecated!

### ISSUE THREAD

**Issue by neilwang0913** [conda/conda#6006]
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb:59:in `<class:Gcc>'
Please report this to the homebrew/core tap!

**Comment by kalefranz** [comment]
Wrong issue tracker
