### ISSUE TITLE
`conda info` does not show information of activated environment

### ISSUE THREAD

**Issue by aphearin** [conda/conda#6010]
My default conda environment uses python 2. I have created a conda environment that uses python 3, but after activating this environment, when I use the `conda info` command to display my system information, the command still displays that my installation is python 2. 

Here is the result of `conda info` from my default environment:

Current conda install:

               platform : osx-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : 2.1.17
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /Users/aphearin/anaconda  (writable)
    default environment : /Users/aphearin/anaconda
       envs directories : /Users/aphearin/anaconda/envs
                          /Users/aphearin/.conda/envs
          package cache : /Users/aphearin/anaconda/pkgs
                          /Users/aphearin/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/aphearin/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.18.4 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

I created a new environment as follows:
`conda create -n py3_basic python=3.6 ipython matplotlib numpy scipy cython astropy`

I activate this environment as follows:
`source activate py3_basic`

I confirm that this environment actually is using python 3 from an interpreter with this environment activated:

```
import sys
print(sys.version)

3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 23:01:38) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

Here is the result of `conda info` from my new `py3_basic` environment:

Current conda install:

               platform : osx-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : 2.1.17
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /Users/aphearin/anaconda  (writable)
    default environment : /Users/aphearin/anaconda/envs/py3_basic
       envs directories : /Users/aphearin/anaconda/envs
                          /Users/aphearin/.conda/envs
          package cache : /Users/aphearin/anaconda/pkgs
                          /Users/aphearin/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/aphearin/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.18.4 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

**Comment by goanpeca** [comment]
@aphearin `$ conda info` normally displays/works like that.

Maybe you are looking for `$ conda config --show`  ?

**Comment by aphearin** [comment]
The nice thing about `$conda info` is that it displays basically the perfect information for bug reports of python packages. `$conda config --show` does not display much information that is relevant for that.

**Comment by aphearin** [comment]
If this is really the intended behavior of `conda info` ,then maybe I should phrase this as a question instead. If I create a custom environment dedicated to the use of some (external) package, and I want to submit a bug report to the developers of that package, what is the best way that I can get `conda` to display the system information relevant to the custom environment?

**Comment by kalefranz** [comment]
Actually, it does in conda 4.4.  There's an rc1 of conda 4.4.0 available (with several known bugs).  To get it

    conda config --add channels conda-canary
    conda update conda
