### ISSUE TITLE
Unsatisfiable error: The following specification found to be conflict 

### ISSUE THREAD

**Issue by jhasuman** [conda/conda#6011]
I am using the latest version of Cinda and in that Python 3 but while installing basemap I  am getting this error. 
Unsatisfiable error: The following specification found to be conflict: 
-basemap -> Numpy 1.10* -> Python 2.7*
- Python 3.6*
Operating system: Windows 
Thanks!!

**Comment by tyler-thetyrant** [comment]
This is conda's solver at work. It solves packages' dependency trees to avoid breaking interdependencies of multiple packages. 
With the latest miniconda3, I did not run into any problems running `conda install basemap`

**Comment by kalefranz** [comment]
It appears there is no python 3.6 version of basemap available for win-64.  I recommend using a conda environment to isolate your dependencies here, or file an issue with conda-forge.
