### ISSUE TITLE
Purging the ".trash" folder.

### ISSUE THREAD

**Issue by tokejepsen** [conda/conda#6012]
OS: Windows.

When updating an environment, a snapshot of the environment get stored in the ```[miniconda]\pkgs\.trash```

Is there a way to clean up this trash directory with a ```conda``` command?

**Comment by timleslie** [comment]
I also have this problem and would be interested in a solution. My reading of the code is that a call to `delete_trash()` needs to be added somewhere, but I'm not sufficiently familiar with the code to know the best way to do this.

**Comment by tokejepsen** [comment]
Further to this, if you try to manually delete the environment snapshots, you'll get a "Access denied" error if the environment is in use.

**Comment by kalefranz** [comment]
The `.trash` directory is what we've resorted to for dealing with windows file locking.  This is really a Windows OS issue.  Windows aggressively locks files on a per-process basis, which means if a process is "using" a file, conda won't be able to delete it.  We can rename it however, and move it to the .trash directory.

The `delete_trash()` function is called at the end of `create`, `install`, `update`, and `remove` operations.  See:

* https://github.com/conda/conda/blob/4.3.x/conda/cli/main_create.py#L69
* https://github.com/conda/conda/blob/4.3.x/conda/cli/main_install.py#L81
* https://github.com/conda/conda/blob/4.3.x/conda/cli/main_update.py#L66
* https://github.com/conda/conda/blob/4.3.x/conda/cli/main_remove.py#L172

**Comment by tokejepsen** [comment]
Maybe we could get a ```delete_trash()``` when dealing with environments?

https://github.com/conda/conda/blob/4.3.x/conda_env/cli/main_create.py

**Comment by kalefranz** [comment]
Yeah good idea.

**Comment by garu57** [comment]
The delete_trash logic is missing also in clean.
`conda clean -p` deletes packages from `pkgs` moving them to `.trash` but then they are left there.

Can you reopen this or do you need another pr?

**Comment by kalefranz** [comment]
It’s one or two lines of code. Feel free to submit a PR.
