### ISSUE TITLE
##help##

### ISSUE THREAD

**Issue by nagendraversatile** [conda/conda#6015]
Hi,

(C:\Users\nuthalap\AppData\Local\Continuum\Anaconda3) C:\Users\nuthalap>conda create -n tensorflow python=3.5 anaconda
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert access denied')],)",),),)

getting this error, please help

**Comment by kalefranz** [comment]
Intermittent http error.

**Comment by nagendraversatile** [comment]
I tried several time, same issue is getting repeated
