### ISSUE TITLE
`sys.path` contains --local installed python paths for a conda env

### ISSUE THREAD

**Issue by tylerjereddy** [conda/conda#6018]
Two scipy core developers (Pauli and I) can reproduce this potential issue where creating a Python 3.6 conda environment results in a python executable in the environment that picks up python paths for `--local` installed packages.

His sample output:
```
$ conda create -n foo python=3.6
 ... 
$ source activate foo 
$ python 
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information. 
>> import sys 
>> sys.path 
['', '/home/pauli/.local/lib/conda/envs/foo/lib/python36.zip',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/lib-dynload',
 '/home/pauli/.local/lib/python3.6/site-packages',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/site-packages'] 
# 
# Note that /home/pauli/.local/lib/python3.6/site-packages 
# appears in sys.path. This seems to only occur on Python 3.6. 
#
```

My sample output also contains stuff from a `--local` install
```
$ conda create -n foo python=3.6
...
$ source activate foo
$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/tyler/miniconda3/envs/foo/lib/python36.zip', '/home/tyler/miniconda3/envs/foo/lib/python3.6', '/home/tyler/miniconda3/envs/foo/lib/python3.6/lib-dynload', '/home/tyler/.local/lib/python3.6/site-packages', '/home/tyler/.local/lib/python3.6/site-packages/MDAnalysis-0.17.0.dev0-py3.6-linux-x86_64.egg', '/home/tyler/.local/lib/python3.6/site-packages/joblib-0.11-py3.6.egg', '/home/tyler/.local/lib/python3.6/site-packages/mmtf_python-1.0.9-py3.6.egg', '/home/tyler/.local/lib/python3.6/site-packages/GridDataFormats-0.3.3-py3.6.egg', '/home/tyler/.local/lib/python3.6/site-packages/networkx-2.0-py3.6.egg', '/home/tyler/.local/lib/python3.6/site-packages/biopython-1.70-py3.6-linux-x86_64.egg', '/home/tyler/.local/lib/python3.6/site-packages/msgpack_python-0.4.8-py3.6-linux-x86_64.egg', '/home/tyler/.local/lib/python3.6/site-packages/decorator-4.1.2-py3.6.egg', '/home/tyler/miniconda3/envs/foo/lib/python3.6/site-packages']
```

I also confirmed that the issue seems to be Python 3.6-specific. Following the same procedure with Python 2.7 & 3.5 environments yielded sensible `sys.path` values that were isolated to the conda env.

The original discussion arose from our [development work](https://github.com/spacetelescope/asv/pull/539) on `asv`, where I noticed a path problem on Windows, but apparently this is reproducible on linux as well.

**Comment by tylerjereddy** [comment]
If this is indeed a bug, I am open to being guided to produce a patch to help resolve it, if one is not already underway.

**Comment by kalefranz** [comment]
This wouldn't be anything that conda itself is doing. Could relate to how our python package is compiled and built though. 

Checkout github.com/AnacondaRecipes/python-feedstock to see if you can spot anything. 

Does the conda-forge python behave differently?

**Comment by tylerjereddy** [comment]
Identical behavior using conda-forge as the source channel, including the specificity of the issue to Python version 3.6. I'll take a look at the feedstock repo you linked.

**Comment by kalefranz** [comment]
Are you sure this isn't just expected python behavior?  https://www.python.org/dev/peps/pep-0370/

**Comment by tylerjereddy** [comment]
Ah, you are correct. This has [previously generated confusion for users](https://github.com/conda/conda/issues/448), and the conclusion there seems to be that the conda team is not interested in excluding site directories entirely (for understandable reasons -- this changes the default behavior of Python).

I'm closing this because there are various ways to achieve what we need for our project -- i.e.,
`export PYTHONNOUSERSITE=True` will apparently give us the kind of environment isolation (no site packages whatsoever in a conda env) that is desired, as suggested by one of my colleagues in the above linked issue.

**Comment by pv** [comment]
If it's expected Python behavior, why does it occur only on Python 3.6?

**Comment by tylerjereddy** [comment]
@pv Yeah, pretty sure we have to suppress the default Python behavior of adding the local site packages to sys.path if we want the conda env isolation to be more similar to the level of isolation achieved with i.e., virtualenv.

**Comment by kalefranz** [comment]
Cross reference to previous discussion, in case it wasn't clear from above: https://github.com/conda/conda/issues/448

**Comment by yanbussieres** [comment]
As mentioned #448 : 

`export PYTHONNOUSERSITE=True`

is the best workaround for now. 

Still having the issue with python 3.6. 
Current setup : conda 4.5.8, ubuntu 18.04. I was also able to reproduce with Ubuntu 16.

**Comment by nehaljwani** [comment]
xref: https://github.com/conda/conda/issues/7173

**Comment by rachidbch** [comment]
Hello @yanbussieres,
Thanks fo the ```export PYTHONNOUSERSITE=True```` workaround.

However I would be glad to have access to user site  but with priority to conda env site packages over system user site packages.
To put it clearly i would like to have (with your example above):
```
>> sys.path 
['', '/home/pauli/.local/lib/conda/envs/foo/lib/python36.zip',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/lib-dynload',
 '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/site-packages'],
 '/home/pauli/.local/lib/python3.6/site-packages',
```
that way i can have access to user site packages but i can also overshadow them by installing packages in the conda env.

I suspect I've something wrong here otherwise it would have already picked up in the conversation.

So what's the trick here ?

**Comment by anugrahandi** [comment]
For those Windows user like me who confused by `export PYTHONNOUSERSITE=True`, this is system environment setting. 

To set, hit Start, search for "Edit the system environment variables", select first entry shown. 'System Properties' window appear, click 'Environment Variables' button. New window appear, click "New" on User Variables (top dialog) and add:
> Variable name = PYTHONNOUSERSITE
> Variable value = True

Then restart computer if necessary.

Sorry maybe it is trivial for expert users here, but I couldn't find solution on google on windows how to put 'export' command.

I encountered import when have second installation of Python 3.7 in my system. Apparently, Anaconda also include 'site-packages in AppData' as its source of package (checked by print `sys.path`) which will have conflict on my another python 3.7 installation.

**Comment by zhong-yy** [comment]
I have the same issue with conda 4.10.1 on ubuntu 20.04. It seems that _$HOME/.local/lib/python3.7/site-packages_ has a higher priority than my own environment.

```python
In [1]: import sys
   ...: sys.path
Out[1]: 
['/home/yyzhong/anaconda3/envs/myenv/bin',
 '/opt/intel/oneapi/advisor/2021.1.1/pythonapi',
 '/home/yyzhong/anaconda3/envs/myenv/lib/python37.zip',
 '/home/yyzhong/anaconda3/envs/myenv/lib/python3.7',
 '/home/yyzhong/anaconda3/envs/myenv/lib/python3.7/lib-dynload',
 '',
 '/home/yyzhong/.local/lib/python3.7/site-packages',
 '/home/yyzhong/anaconda3/envs/myenv/lib/python3.7/site-packages',
 '/home/yyzhong/anaconda3/envs/myenv/lib/python3.7/site-packages/IPython/extensions',
 '/home/yyzhong/.ipython']

```

**Comment by Ceciliogq** [comment]
> Hello @yanbussieres,
> Thanks fo the `export PYTHONNOUSERSITE=True` workaround.
> 
> However I would be glad to have access to user site but with priority to conda env site packages over system user site packages.
> To put it clearly i would like to have (with your example above):
> 
> ```
> >> sys.path 
> ['', '/home/pauli/.local/lib/conda/envs/foo/lib/python36.zip',
>  '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6',
>  '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/lib-dynload',
>  '/home/pauli/.local/lib/conda/envs/foo/lib/python3.6/site-packages'],
>  '/home/pauli/.local/lib/python3.6/site-packages',
> ```
> 
> that way i can have access to user site packages but i can also overshadow them by installing packages in the conda env.
> 
> I suspect I've something wrong here otherwise it would have already picked up in the conversation.
> 
> So what's the trick here ?

I also think this is a more desirable behaviour. Has anyone figured out how to achieve this?
