### ISSUE TITLE
caching server for conda

### ISSUE THREAD

**Issue by ptulpen** [conda/conda#6025]
Hello,
we have an internal mirror for conda packages and we have locations with a bad internet connection to us.
In this locations docker images are build, so quite often a conda install is done.(where the client cache dies not help)
Since they only use a few packages and their dependencies, I dont want to set up a complete mirror

So my idea is now: is it possible to have a location cache for packages and metadata? (I think this takes the most time)
I thought about something like this: https://www.unix-ag.uni-kl.de/~bloch/acng/
But I did find nothing like this for conda

**Comment by Zaharid** [comment]
You can have your own channel and set it with higher priority than the default one. All you need is to organize the packges in the correct directory structure and call `conda index` on it.

You may find this useful:

https://conda.io/docs/user-guide/tasks/create-custom-channels.html
