### ISSUE TITLE
How to install packages in non-Conda envs

### ISSUE THREAD

**Issue by ofek** [conda/conda#6027]
@kalefranz @goanpeca Say I create an env with `virtualenv ~/test` and then wish to use Conda to install numpy in it.

If I do `conda install -p ~/test numpy==1.13.1` I get:
```
The following NEW packages will be INSTALLED:     
                                                  
    certifi:        2017.7.27.1-py36_0 conda-forge
    mkl:            2017.0.3-0                    
    numpy:          1.13.1-py36_0                 
    pip:            9.0.1-py36_0       conda-forge
    python:         3.6.2-0            conda-forge
    setuptools:     36.3.0-py36_0      conda-forge
    vs2015_runtime: 14.0.25420-0       conda-forge
    wheel:          0.30.0-py_1        conda-forge
    wincertstore:   0.2-py36_0         conda-forge
```

How can I have Conda use the already created python/pip and only install what is needed?

**Comment by goanpeca** [comment]
@ofek it does not work like that, you cannot install a conda package inside a virtualenv. The idea is to use conda environments. If you want to use virtualenv inside conda, you can but you will have to use pip to install packages on that virtualenv.

**Comment by ofek** [comment]
@goanpeca Is there any way to do this, at all?

**Comment by goanpeca** [comment]
No
