### ISSUE TITLE
Slow when source conda.fish

### ISSUE THREAD

**Issue by neowulf33** [conda/conda#6029]
```
source (conda info --root)/etc/fish/conf.d/conda.fish
```

in my `~/.config/fish/config.fish` takes anywhere from 1 to 5 seconds. Sometimes even more.

Fish version is 2.6.0
Conda version is 4.3.21
Mac OS 10.12.6

**Comment by Zaharid** [comment]
A workaround is to remove the `(conda info --root)` and write the actual path instead. That's probably what should be done by default.
