### ISSUE TITLE
"conda help X" fails on clean install

### ISSUE THREAD

**Issue by arthurward** [conda/conda#6031]
"conda help X" gives me the following error for any argument:

`C:\ProgramData\Anaconda3\python.exe: can't open file 'C:\ProgramData\Anaconda3\Scripts\conda': [Errno 2] No such file or directory`

I expected it to give the help content for command X. For example, `conda help help` should be equivalent to `conda help --help` according to `conda help --help`.

This happens with both Anaconda 4.4.0, installed on a new Windows 10 computer, and with Anaconda 5.0.0 (after uninstalling, discovering the new release, and installing 5.0.0 instead). The error message is true; "conda" does not exist, but "conda.exe" does.

`conda info` says:

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\X\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\X\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\X\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\X\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.14393
          administrator : False

**Comment by kalefranz** [comment]
We don't have tests for the `conda help` command.  The more common pattern is to append `--help` to the command you're looking to get help on.  For example, `conda install --help`.

**Comment by kalefranz** [comment]
`conda help` is being deprecated.  Instead, use the `--help` cli flag.
