### ISSUE TITLE
Windows 10 miniconda installer tries to create a weird path

### ISSUE THREAD

**Issue by nlehtinen** [conda/conda#6032]
See this image:

<img width="241" alt="untitled" src="https://user-images.githubusercontent.com/32343386/30936644-3374e56c-a3dd-11e7-90c4-33a0dcf9498e.png">

It literally creates tries to create this path, with intermediate directory names containing a semicolon. E.g., there is a "bin;C" subfolder in the folder C:\ProgramData\Miniconda3\Library, and more subfolders inside.

```
C:\ProgramData\Miniconda3>dir Library
 Volume in drive C is OS
 Volume Serial Number is 8E32-5CC0

 Directory of C:\ProgramData\Miniconda3\Library

09/27/2017  11:34 PM    <DIR>          .
09/27/2017  11:34 PM    <DIR>          ..
09/27/2017  11:34 PM    <DIR>          bin;C

```
I checked the installer versions:
Miniconda3-4.3.11-Windows-x86_64.exe
Miniconda3-4.3.14-Windows-x86_64.exe
Miniconda3-4.3.21-Windows-x86_64.exe
Miniconda3-4.3.27-Windows-x86_64.exe
Miniconda2-4.3.27-Windows-x86_64.exe

All of them (since February!) have this error.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6226
