### ISSUE TITLE
Conda create --clone failing on missing phantom pyc files

### ISSUE THREAD

**Issue by tomashek** [conda/conda#6033]
While attempting to clone a root environment, it fails with reports of unlinkable .pyc files:

> conda create -m -p /localdisk/projects/newroot2 --clone /localdisk/intelpython2

Source:      /localdisk/projects/intelpython2
Destination: /localdisk/projects/newroot2
The following packages cannot be cloned out of the root environment:
 - conda-4.3.27-py27hff99c7a_0
 - conda-env-2.6.0-0
Packages: 139
Files: 10575
zlib-1.2.11-in 100% |###############################| Time: 0:00:00 204.32 kB/s

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'intel::python-2.7.13-intel_2'.
CondaError: Cannot link a source that does not exist. /localdisk/projects/intelpython2/pkgs/python-2.7.13-intel_2/lib/python2.7/lib2to3/__init__.pyc
Attempting to roll back.

CondaError: Cannot link a source that does not exist. /localdisk/projects/intelpython2/pkgs/python-2.7.13-intel_2/lib/python2.7/lib2to3/__init__.pyc

--------------------------------

There are similar failures in a python 3 environment for __pycache__/*.pyc files missing.

The .pyc files that it is complaining about are not in the package, nor are they in the "info/files" metadata file, so I don't know why conda --clone thinks it should find them.

If I manually compile the .pyc files it complained about initially, it eventually runs into other .py files without a .pyc and fails on those.

I see other issues relating to "clone" failing when targeting a root environment, but none with this .pyc error.

**Comment by kalefranz** [comment]
Can you give me step-by-step instructions on how to reproduce this?  Starting with "fire up operating system X of version Y"?

**Comment by tomashek** [comment]
I have a simpler reproducer.

Linux ubuntu 16.04.
Start with miniconda:
```
$ conda list
# packages in environment at /localdisk/work/miniconda3:
#
asn1crypto                0.22.0                   py36_0  
cffi                      1.10.0                   py36_0  
conda                     4.3.16                   py36_0  
conda-env                 2.6.0                         0  
cryptography              1.8.1                    py36_0  
idna                      2.6                      py36_0  
libffi                    3.2.1                         1  
openssl                   1.0.2g                        0  
packaging                 16.8                     py36_0  
pip                       9.0.1                    py36_1  
pycosat                   0.6.1                    py36_1  
pycparser                 2.18                     py36_0  
pycrypto                  2.6.1                    py36_4  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.2.0                    py36_0  
python                    3.6.2                         0  
pyyaml                    3.12                     py36_0  
readline                  6.2                           2  
requests                  2.12.4                   py36_0  
ruamel_yaml               0.11.14                  py36_1  
setuptools                27.2.0                   py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         0 
```

Then create an environment using the package python-3.6.2-nopyc_intel_4.tar.bz2 from the intel/label/test channel:

conda create -c intel/label/test -c intel -n mypython1 python=3.6.2=nopyc_intel_4

```
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /localdisk/work/miniconda3/envs/mypython1:

The following NEW packages will be INSTALLED:

    intelpython: 2018.0.0-3          intel           
    openssl:     1.0.2k-intel_3      intel            [intel]
    pip:         9.0.1-py36_intel_0  intel            [intel]
    python:      3.6.2-nopyc_intel_4 intel/label/test [intel]
    setuptools:  27.2.0-py36_intel_0 intel            [intel]
    sqlite:      3.13.0-intel_15     intel            [intel]
    tcl:         8.6.4-intel_17      intel            [intel]
    tk:          8.6.4-intel_26      intel            [intel]
    wheel:       0.29.0-py36_intel_5 intel            [intel]
    xz:          5.2.2-intel_16      intel            [intel]
    zlib:        1.2.11-intel_3      intel            [intel]

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'intel/label/test::python-3.6.2-nopyc_intel_4'.
CondaError: Cannot link a source that does not exist. /localdisk/work/miniconda3/pkgs/python-3.6.2-nopyc_intel_4/lib/python3.6/lib2to3/__pycache__/__init__.cpython-36.pyc
Attempting to roll back.


CondaError: Cannot link a source that does not exist. /localdisk/work/miniconda3/pkgs/python-3.6.2-nopyc_intel_4/lib/python3.6/lib2to3/__pycache__/__init__.cpython-36.pyc
```

The curious part is there are NO pyc files in the "info/files" manifest, so I don't know why conda thinks it should try to link them.

**Comment by tomashek** [comment]
I updated to conda=4.3.27-py36h2866c0b_0  and the problem remains

**Comment by tomashek** [comment]
I found the problem. The pyc files are referenced in "paths.json". You can close this
