### ISSUE TITLE
Cannot install jupyter_core: 4.3.0-py27_0 in a new environment with conda.

### ISSUE THREAD

**Issue by xandervx** [conda/conda#6035]
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::jupyter_core-4.3.0-py27_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

PermissionError(13, 'Permission denied')

Has been fighting with it since yesterday. Help

**Comment by kalefranz** [comment]
You have to provide us with a lot more information before we can have any foundation or context to help you.  Start with `conda info`.

If you've ever used `sudo` on the environment, you have to use it in perpetuity, or fix your permissions with `chown`.  Unless you're on Windows, which has a different set of solutions.  `conda info` would have given us that information up front.
