### ISSUE TITLE
"Dubious" registry access blocked by antivirus

### ISSUE THREAD

**Issue by MSeifert04** [conda/conda#6039]
I updated some packages yesterday and everytime there is something trying to access the registry and my antivirus program is blocking it. It started with the latest conda update.

Unfortunately I haven't copied the details but when it happens again I'll update the post.

System: Windows 10, conda 4.3.27

**Comment by kalefranz** [comment]
Am very interested to find out what this is.  If you can isolate what's going on and provide more information, would be very much appreciated.

If you think it's a real security issue, feel free to email me privately and directly.  kfranz@anaconda.com

**Comment by msarahan** [comment]
We set some registry keys to comply with PEP 514: https://www.python.org/dev/peps/pep-0514/

**Comment by MSeifert04** [comment]
Thank you for the fast replies! 👍 

Seems like I cannot reproduce it. Maybe it was just a temporary hickup of the antivirus program. If I encounter it again I'll reopen it with a more detailed description.
