### ISSUE TITLE
hi, I am new to pyhton and i coudnt figure out what the issue is after installing miniconda

### ISSUE THREAD

**Issue by DHAVALdesai13** [conda/conda#6040]
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : C:\miniconda  (writable)
    default environment : C:\miniconda
       envs directories : C:\miniconda\envs
                          C:\Users\Dhaval Desai\AppData\Local\conda\conda\envs
                          C:\Users\Dhaval Desai\.conda\envs
          package cache : C:\miniconda\pkgs
                          C:\Users\Dhaval Desai\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Windows/10 Windows/10.0.14393
          administrator : False

`$ C:\miniconda\Scripts\conda-env create -f C:\miniconda`

    Traceback (most recent call last):
      File "C:\miniconda\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\miniconda\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\miniconda\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
        if spec.can_handle():
      File "C:\miniconda\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\miniconda\lib\site-packages\conda_env\env.py", line 78, in from_file
        with open(filename, 'r') as fp:
    IOError: [Errno 13] Permission denied: 'C:\\miniconda'

**Comment by pzwang** [comment]
Did you install as administrator?
