### ISSUE TITLE
GLIBC >= 2.6 required for building C extension package

### ISSUE THREAD

**Issue by merraksh** [conda/conda#6041]
I get the following error on a conda build for a C extension package. This didn't happen before:

+ /anaconda/conda-bld/mypkg_1506699210499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python setup.py install
/anaconda/conda-bld/mypkg_1506699210499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /anaconda/conda-bld/mypkg_1506699210499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python)

The message repeats with just a different version of glibc that's not found: GLIBC_2.9 and GLIBC_2.6.

I have a Linux server with glibc 2.5 (necessary for the purposes of the server), and Conda 4.3.27. Updating to Anaconda 5.0 anticipates that error:

/anaconda/bin/python: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /anaconda/bin/python)

Should I downgrade Anaconda or some conda package in order to restore functionality?

Thanks

[EDIT] The last error message also repeats for 2.9 and 2.6:
/anaconda/bin/python: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /anaconda/bin/python)
/anaconda/bin/python: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by /anaconda/bin/python)

[EDIT 2] This happens for multiple versions of Python: 3.5, 3.6, 2.7

**Comment by msarahan** [comment]
Anaconda 5 no longer supports CentOS 5 / glibc 2.5 as the baseline.  It has moved to CentOS 6 / glibc 2.12.  You'll need to stick with conda < 4.3.27, which will keep you on the old "defaults" channel.  The new defaults channel includes https://repo.continuum.io/pkgs/main, and this is where all software will be compatible with glibc 2.12 and up.

**Comment by msarahan** [comment]
to prevent conda from updating itself, you can do:

```conda config --set auto_update_conda false```

at the terminal

**Comment by mingwandroid** [comment]
We actually dropped official support for glibc 2.5 during the Anaconda 4 series, though at 5 we made a very clean break from the old stuff.

**Comment by merraksh** [comment]
Thanks @msarahan , I'll downgrade the installation.
