### ISSUE TITLE
conda 4.4 + zsh: conda:shift:1: shift count must be <= $#

### ISSUE THREAD

**Issue by anntzer** [conda/conda#6045]
With conda 4.4.0rc1 and zsh, calling the new conda shell function with no arguments results in
```
$ conda
conda:shift:1: shift count must be <= $#
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '' (choose from 'clean', 'config', 'create', 'help', 'info', 'install', 'list', 'package', 'remove', 'uninstall', 'search', 'update', 'upgrade')
```
It's mostly an esthetic point but it would be nice if the shell error message (shift count) was not shown.

**Comment by kalefranz** [comment]
Thanks for the report!

**Comment by anntzer** [comment]
Some related issues:
1. `conda nonexistentcommand` exits with status 1 but does not print any error message.
2. The changelog recommends putting conda.sh in a profile folder but this usually won't work if the user's terminals are not login shells (as is the default on Linux): nonlogin shells do not read the profile folder and do not inherit *functions* (even though the *environment* is inherited.  I just sourced conda.sh in my .zshrc (rather than my .zprofile).
