### ISSUE TITLE
Create conda service to support multiuser operations

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#6046]
conda in a multiuser environment continues to be problematic.

My best (high-level) idea for how to address this is is to have conda in a multi-user setting implemented not as a pure file system-based transactional service but rather as a persistent API-based service where users authenticate to the service, make a request for a conda operation from the conda daemon service, and that daemon service then performs the operations according to some policy but all (in memory and on disk) as a particular account.  Permissions for any given user to perform any particular conda operation becomes part of some conda-specific security policy and access to conda-installed software becomes a matter of IT configuration of POSIX users and groups.  At that stage if there are any nuances with POSIX.1e ACLs it can be added as a stage in the "conda service" to fix ACLs after any write operations -- if necessary.

Doing this would involve creating a conda server and a conda client, with the server wrapping the vanilla (single-user) file-system based conda.

**Comment by kalefranz** [comment]
Glad we finally have a ticket to track this. There are quite a few other uses for an agent process. Things like a general locking service, global environment registry, environment update service, environment reporting service, etc.

Once we have the foundational client-server code written and working, the addition of each new feature has a relatively low cost. There’s a pretty high entry barrier though to getting this client-server foundation designed, written, and tested, across all OSes. 

Given all its uses, and the high entry barrier / low feature cost situation, it’s possible that Anaconda, Inc. decided to create this not as something within conda, but as an enterprise feature, value-add, or add-on.

**Comment by jamie-arcc** [comment]
I just want to bump this because conda's support for multi-user environments is abysmal.  It just broke for me again.
