### ISSUE TITLE
CondaError: Cannot link a source that does not exist. C:\Users\...\Anaconda3\Scripts\conda.exe

### ISSUE THREAD

**Issue by AVSuni** [conda/conda#6057]
I get this error when trying to conda install tqdm. Pip install works fine. However, when trying conda install spacy, I still get the same error because the conda installation for spacy attempts to conda install tqdm.

**Comment by kalefranz** [comment]
Do you still get the error after running `conda clean --all`?

**Comment by kalefranz** [comment]
If you need additional help, please include more details.  At a minimum, `conda info`, the command that gave the error, and the full stack trace.  Whatever details are necessary to independently reproduce the issue you're seeing.

**Comment by AVSuni** [comment]
Thanks @kalefranz. I had tried `Conda clean --all`. The error went away when I updated everything with `conda update anaconda `

**Comment by jochem4207** [comment]
Had the same error and @AVSuni thank you so much! Also thanks to @kalefranz  (it occured when installing spacy)

**Comment by minrk** [comment]
We've run into this with nbconvert as well. I setup [a repo](https://github.com/minrk/debug-conda-appveyor) to do some testing:

On AppVeyor, installing nbconvert from conda-forge has started failing with:

```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::nbconvert-5.3.1-py_1'.
CondaError: Cannot link a source that does not exist. C:\Miniconda-x64\Scripts\conda.exe
Attempting to roll back.
CondaError: Cannot link a source that does not exist. C:\Miniconda-x64\Scripts\conda.exe
```

Possibly relevant bits of info:

- `conda clean --all` does not help
- Failure only occurs on [Windows + Python 2](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.9)
- It only occurs when conda is upgraded or downgraded during the same install. Disabling auto_update_conda [fixes the issue](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.10)
- Appears to be a regression between conda [4.3.8](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.21) and [4.3.9](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.22)
- nbconvert has `noarch: python` and an entry-point, as does tqdm
- installing last nbconvert release prior to noarch [has no issue](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.11)
- installing other, lighter packages with noarch + entrypoint (geojsonio) [doesn't reproduce the issue](https://ci.appveyor.com/project/minrk/debug-conda-appveyor/build/1.0.6) so there might be something else special about nbconvert+tqdm, or it could just be the ordering of packages causing the correct sequence of events to occur that `conda.exe` is removed while it's attempted to be linked.

**Comment by dhirschfeld** [comment]
I'm seeing this in damianavila/RISE#315 on win64 / py36 / conda 4.3.22

**Comment by mccolem19** [comment]
Hi all, I've run into this issue while trying to install the "tweepy" package. [conda 4.3.30 / Python 3.6.3]

Command: `conda install -c conda-forge tweepy`

Error:
`oauthlib-2.0.6 100% |###############################| Time: 0:00:00   0.00  B/s
conda-4.3.29-p 100% |###############################| Time: 0:00:00   3.20 MB/s
requests-oauth 100% |###############################| Time: 0:00:00   0.00  B/s
tweepy-3.5.0-p 100% |###############################| Time: 0:00:00   3.37 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::pyjwt-1.5.3-py_0'.
CondaError: Cannot link a source that does not exist. C:\Users\Maurice\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.


CondaError: Cannot link a source that does not exist. C:\Users\Maurice\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.`

I tried the above steps of `conda clean --all --yes` and `conda update anaconda` but I didn't have any success. 
Any recommendations on what else I could try? Thanks.

**Comment by kalefranz** [comment]
> or it could just be the ordering of packages causing the correct sequence of events to occur that conda.exe is removed while it's attempted to be linked.

That's exactly what's happening.

```
DEBUG conda.core.link:create_from_dists(119): instantiating UnlinkLinkTransaction with
  target_prefix: C:\Users\builder\Miniconda3
  unlink_dists:
    defaults::conda-4.3.24-py36_0
    defaults::conda-env-2.6.0-0
    defaults::openssl-1.0.2l-vc14_0
  link_dists:
    conda-forge::ca-certificates-2017.7.27.1-0
    conda-forge::conda-env-2.6.0-0
    conda-forge::openssl-1.0.2l-vc14_0
    conda-forge::vc-14-0
    conda-forge::pyjwt-1.5.3-py_0
    conda-forge::conda-4.3.29-py36_0
```

Sometime around 4.3.8, we removed the embedded `cli-64.exe` / `cli-32.exe` files like what's in conda-build (https://github.com/conda/conda-build/tree/master/conda_build), realizing we already had the identical python entry point binary already available with conda.exe.

As you can see in the above operation plan, conda is unlinked, but then installed last, after pyjwt, which is what needs the entry point binary to hard link.

**Comment by cspipaon** [comment]
Hi I'm kind of new to Python, completely new to Github and I have the same problem as @mccolem19. Was it possible to resolve the problem? Could someone give me a n00b-proof guideline?
Thanks

**Comment by jbrant** [comment]
Are there any work-arounds for this?

**Comment by dhirschfeld** [comment]
You could try:
```
conda install conda=4.2.16
```
...until conda is released with the bugfix.

**Comment by fauskanger** [comment]
I did: 

    conda clean --all --yes

then 
    
    conda install conda=4.2.16

and then

    conda update --all

but now when I try to do `conda info` I get the message that: `'conda' is not recognized as an internal or external command, operable program or batch file.`

I also tried to do `conda update anaconda` but then it got stuck at `solving package specifications` (ref [this](https://github.com/conda/conda/issues/5219))

I have recently re-installed a clean install of Windows 10 (deleting all user files) in case any of my user files or previous hacks interfered with the Anaconda installation.

So: If I uninstall and remove all of Anaconda, what is the recommended way to use Anaconda until a bugfix is released? Should I downgrade to conda=4.2.16 right away? (I noticed during `conda update --all` that the `attrs` library complained that it needed conda>=4.3.)

**Comment by henklaak** [comment]
I found that it helps to do a 
` conda update conda` 
before doing any other upgrade/install operations

**Comment by wesleytao** [comment]
I solved this problem by doing a 
`conda update conda` 
as @henklaak suggested. Thanks!

**Comment by deaningithub** [comment]
I use #conda update anaconda 
and success!

**Comment by ajmerlob** [comment]
I also found the following to work for me @deaningithub :

`conda update anaconda` 

Please note this is different from `conda update conda`

**Comment by bahaabeih** [comment]
conda update anaconda solved it in my case

**Comment by Mallikarjunayya** [comment]
Thanks lot  @kalefranz 

Below commend is working fine for me
conda config --add pinned_packages defaults::conda

**Comment by HenryFBP** [comment]
Fails under `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1 automat`

I've done `conda update anaconda` and `conda config --add pinned_packages defaults::conda`.

The `automat` package seems responsible:

```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge/label/g
cc7::automat-0.7.0-py_1'.
```

Will update if I succeed.

**Comment by jsantanders** [comment]
Thanks, @HenryFBP your solution work for me.

**Comment by muhammediqbal** [comment]
> Fails under `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1 automat` on Windows 7, conda 4.5.11
> 
> I've done `conda update anaconda` and `conda config --add pinned_packages defaults::conda`.
> 
> The `automat` package seems responsible:
> 
> ```
> ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge/label/g
> cc7::automat-0.7.0-py_1'.
> ```
> EDIT: Succeeds under `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce automat==0.6.0 pythonocc-core==0.18.1`!
> 
> Seems to be an issue with automat's most recent version, 0.7.0, not being released for Windows.

How can i amend your install command for scrapy as i am also having an issue with installing automats recent version ?

**Comment by HenryFBP** [comment]
> > Fails under `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1 automat` on Windows 7, conda 4.5.11
> > I've done `conda update anaconda` and `conda config --add pinned_packages defaults::conda`.
> > The `automat` package seems responsible:
> > ```
> > ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge/label/g
> > cc7::automat-0.7.0-py_1'.
> > ```
> > EDIT: Succeeds under `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce automat==0.6.0 pythonocc-core==0.18.1`!
> > Seems to be an issue with automat's most recent version, 0.7.0, not being released for Windows.
> 
> How can i amend your install command for scrapy as i am also having an issue with installing automats recent version ?

That I'm not sure of...I don't use `scrapy`.

Try `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce automat==0.6.0`?

That command shouldn't install `pythonocc-core`, which is some CAD Python library.

**Comment by mfansler** [comment]
I find it strange that you are all Windows users, but it seems that Conda is showing preference to install from the `noarch` platform channel, even though in the `nbconvert` and `automat` cases there is clearly a **win-64** build of the latest version.  When I `--dry-run` install these on OSX, Conda resolves to the **osx-64** builds.

I wonder, **would directly installing from the platform-specific tarball make a difference**?  For the Automat example (@HenryFBP), assuming Python 3.6:

    conda install https://anaconda.org/conda-forge/automat/0.7.0/download/win-64/automat-0.7.0-py36_0.tar.bz2
    conda upgrade automat

Note, the `upgrade` step is because normally dependencies would get upgraded, but pulling directly from the tarball won't trigger this on its own.

**Comment by nanqiaobei** [comment]
Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe  
sorry  i don"t know to slove this problem ,i try to conda clean --all then conda update anaconda  but don't work,can you help me     thank

**Comment by HenryFBP** [comment]
> Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe
> sorry i don"t know to slove this problem ,i try to conda clean --all then conda update anaconda but don't work,can you help me thank

Does `conda install -c conda-forge -c dlr-sc -c pythonocc -c oce automat==0.6.0` work for you?

**Comment by FergusonShuai** [comment]
Tried to run `conda update conda` but still get error message:
`menuinst-1.4.1 100% |###############################| Time: 0:00:00   6.03 MB/s
openssl-1.0.2p 100% |###############################| Time: 0:00:00  18.05 MB/s
freetds-1.00.9 100% |###############################| Time: 0:00:00  14.18 MB/s
libxml2-2.9.8- 100% |###############################| Time: 0:00:00  10.65 MB/s
pymssql-2.1.4- 100% |###############################| Time: 0:00:00  12.23 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing
package 'defaults::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\ProgramData\Anaconda3\S
cripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.


CondaError: Cannot link a source that does not exist. C:\ProgramData\Anaconda3\S
cripts\conda.exe
Running `conda clean --packages` may resolve your problem.`

**Comment by shubing13** [comment]
> Do you still get the error after running `conda clean --all --yes`?
And here's my conda info:
after running the 'conda clean --all --y' the problem still remains
 active environment : base
    active env location : D:\Anaconda3
            shell level : 1
       user config file : C:\Users\shubi\.condarc
 populated config files : C:\Users\shubi\.condarc
          conda version : 4.6.14
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\shubi\.conda\pkgs
                          C:\Users\shubi\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\shubi\.conda\envs
                          C:\Users\shubi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

**Comment by jason-s** [comment]
I have more or less the same issue. I'm on Windows 10 using 64-bit python. I need to install Anaconda 5.0 to setup a conda environment with a particular fixed set of package versions for my application. The more recent version (2019.1? 2017.1? I forget) is somehow not compatible and I cannot install that set of versions for some reason, so I had to go back to install the Anaconda 5.0.

But then when I go to do "conda install markdown" it fails with this issue.

```
>conda install markdown
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment c:\app\python\anaconda\2:

The following NEW packages will be INSTALLED:

    conda-package-handling: 1.3.11-py27_0
    libarchive:             3.3.3-h96cdc4e_5
    lz4-c:                  1.8.1.2-h3cc03e0_0
    markdown:               3.1.1-py27_0
    python-libarchive-c:    2.8-py27_13
    tqdm:                   4.32.1-py_0
    xz:                     5.2.4-h3cc03e0_4
    zstd:                   1.3.7-h1b0e4d7_0

The following packages will be UPDATED:

    bzip2:                  1.0.6-vc9h563fc2e_1   --> 1.0.8-h0c8e037_0
    conda:                  4.3.30-py27he817781_0 --> 4.7.11-py27_0
    conda-env:              2.6.0-h36134e3_1      --> 2.6.0-1
    libxml2:                2.9.4-vc9h17753f3_5   --> 2.9.9-h325896a_0
    menuinst:               1.4.10-py27hf5e3df7_0 --> 1.4.16-py27h0c8e037_0
    openssl:                1.0.2l-vc9h02d068b_2  --> 1.0.2s-h0c8e037_0
    pycosat:                0.6.2-py27h96ae2ec_1  --> 0.6.3-py27h0c8e037_0

Proceed ([y]/n)? y

menuinst-1.4.1 100% |###############################| Time: 0:00:00  20.90 MB/s
conda-env-2.6. 100% |###############################| Time: 0:00:00   2.82 MB/s
lz4-c-1.8.1.2- 100% |###############################| Time: 0:00:00  23.91 MB/s
openssl-1.0.2s 100% |###############################| Time: 0:00:00  35.50 MB/s
xz-5.2.4-h3cc0 100% |###############################| Time: 0:00:00  27.68 MB/s
libxml2-2.9.9- 100% |###############################| Time: 0:00:00  45.09 MB/s
pycosat-0.6.3- 100% |###############################| Time: 0:00:00  20.61 MB/s
tqdm-4.32.1-py 100% |###############################| Time: 0:00:00  16.33 MB/s
markdown-3.1.1 100% |###############################| Time: 0:00:00  26.68 MB/s
python-libarch 100% |###############################| Time: 0:00:00   7.97 MB/s
conda-package- 100% |###############################| Time: 0:00:00  20.48 MB/s
conda-4.7.11-p 100% |###############################| Time: 0:00:00  31.15 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. c:\app\python\anaconda\2\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.


CondaError: Cannot link a source that does not exist. c:\app\python\anaconda\2\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
```

**Comment by JeanReneN** [comment]
Thanks. It works.

**Comment by QtRoS** [comment]
`conda update conda` finally did the trick.

**Comment by sdk2116** [comment]
for those of you who are still stuck on this issue: 
**ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\..........\conda.exe
Running `conda clean --packages` may resolve your problem.**


running `conda install tqdm -f` before running `conda update conda` solved the issue for me

**Comment by ojoayokunnumi** [comment]
reverting to 4.2.16 worked for me 
conda install conda=4.2.16 markdown -c anaconda

**Comment by 15703396763** [comment]
I am trying to install "conda install -c plotly plotly-orca==1.2.1 psutil requests" in anaconda prompt but its not working properly it showed the following problem.

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.46.0-py_0'. CondaError: Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe Attempting to roll back.

CondaError: Cannot link a source that does not exist. D:\Anaconda3\Scripts\conda.exe

(D:\Anaconda3) C:\Users\Dell\Documents>

**Comment by jimtalksdata** [comment]
> for those of you who are still stuck on this issue:
> **ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'. CondaError: Cannot link a source that does not exist. C:..........\conda.exe Running `conda clean --packages` may resolve your problem.**
> 
> running `conda install tqdm -f` before running `conda update conda` solved the issue for me

This worked for me.

**Comment by baileywellen** [comment]
> I have more or less the same issue. I'm on Windows 10 using 64-bit python. I need to install Anaconda 5.0 to setup a conda environment with a particular fixed set of package versions for my application. The more recent version (2019.1? 2017.1? I forget) is somehow not compatible and I cannot install that set of versions for some reason, so I had to go back to install the Anaconda 5.0.
> 
> But then when I go to do "conda install markdown" it fails with this issue.
> 
> ```
> >conda install markdown
> Fetching package metadata .............
> Solving package specifications: .
> 
> Package plan for installation in environment c:\app\python\anaconda\2:
> 
> The following NEW packages will be INSTALLED:
> 
>     conda-package-handling: 1.3.11-py27_0
>     libarchive:             3.3.3-h96cdc4e_5
>     lz4-c:                  1.8.1.2-h3cc03e0_0
>     markdown:               3.1.1-py27_0
>     python-libarchive-c:    2.8-py27_13
>     tqdm:                   4.32.1-py_0
>     xz:                     5.2.4-h3cc03e0_4
>     zstd:                   1.3.7-h1b0e4d7_0
> 
> The following packages will be UPDATED:
> 
>     bzip2:                  1.0.6-vc9h563fc2e_1   --> 1.0.8-h0c8e037_0
>     conda:                  4.3.30-py27he817781_0 --> 4.7.11-py27_0
>     conda-env:              2.6.0-h36134e3_1      --> 2.6.0-1
>     libxml2:                2.9.4-vc9h17753f3_5   --> 2.9.9-h325896a_0
>     menuinst:               1.4.10-py27hf5e3df7_0 --> 1.4.16-py27h0c8e037_0
>     openssl:                1.0.2l-vc9h02d068b_2  --> 1.0.2s-h0c8e037_0
>     pycosat:                0.6.2-py27h96ae2ec_1  --> 0.6.3-py27h0c8e037_0
> 
> Proceed ([y]/n)? y
> 
> menuinst-1.4.1 100% |###############################| Time: 0:00:00  20.90 MB/s
> conda-env-2.6. 100% |###############################| Time: 0:00:00   2.82 MB/s
> lz4-c-1.8.1.2- 100% |###############################| Time: 0:00:00  23.91 MB/s
> openssl-1.0.2s 100% |###############################| Time: 0:00:00  35.50 MB/s
> xz-5.2.4-h3cc0 100% |###############################| Time: 0:00:00  27.68 MB/s
> libxml2-2.9.9- 100% |###############################| Time: 0:00:00  45.09 MB/s
> pycosat-0.6.3- 100% |###############################| Time: 0:00:00  20.61 MB/s
> tqdm-4.32.1-py 100% |###############################| Time: 0:00:00  16.33 MB/s
> markdown-3.1.1 100% |###############################| Time: 0:00:00  26.68 MB/s
> python-libarch 100% |###############################| Time: 0:00:00   7.97 MB/s
> conda-package- 100% |###############################| Time: 0:00:00  20.48 MB/s
> conda-4.7.11-p 100% |###############################| Time: 0:00:00  31.15 MB/s
> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.
> CondaError: Cannot link a source that does not exist. c:\app\python\anaconda\2\Scripts\conda.exe
> Running `conda clean --packages` may resolve your problem.
> Attempting to roll back.
> 
> 
> CondaError: Cannot link a source that does not exist. c:\app\python\anaconda\2\Scripts\conda.exe
> Running `conda clean --packages` may resolve your problem.
> ```
> 
> for reference:
> 
> ```
> >conda list conda
> # packages in environment at c:\app\python\anaconda\2:
> #
> anaconda                  5.0.1            py27hdb50712_1
> anaconda-client           1.6.5            py27h9642776_0
> anaconda-navigator        1.6.9            py27hd588ecf_0
> anaconda-project          0.8.0            py27h56b7296_0
> conda                     4.3.30           py27he817781_0
> conda-build               3.0.27           py27hdc961ca_0
> conda-env                 2.6.0                h36134e3_1
> conda-verify              2.0.0            py27h5217224_0
> ```
> 
> It looks like the conda=4.2.16 does the trick and removes these bizarre dependencies and errors:
> 
> ```
> >conda install conda=4.2.16 markdown -c anaconda
> Fetching package metadata ...........
> Solving package specifications: ..........
> 
> Package plan for installation in environment c:\app\python\anaconda\2:
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     markdown-3.1.1             |           py27_0         130 KB  anaconda
>     conda-4.2.16               |           py27_0         468 KB  anaconda
>     ------------------------------------------------------------
>                                            Total:         599 KB
> 
> The following NEW packages will be INSTALLED:
> 
>     markdown: 3.1.1-py27_0  anaconda
> 
> The following packages will be SUPERCEDED by a higher-priority channel:
> 
>     conda:    4.2.16-py27_0          --> 4.2.16-py27_0 anaconda
> 
> Proceed ([y]/n)? y
> ```
> 
> It doesn't quite work the same without `-c anaconda` (uninstall step skipped here) --- I get an older version of markdown.
> 
> ```
> >conda install conda=4.2.16 markdown
> Fetching package metadata .........
> Solving package specifications: ..........
> 
> Package plan for installation in environment c:\app\python\anaconda\2:
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     conda-4.2.16               |           py27_0         468 KB
> 
> The following NEW packages will be INSTALLED:
> 
>     markdown: 2.6.9-py27_0
> 
> The following packages will be SUPERCEDED by a higher-priority channel:
> 
>     conda:    4.2.16-py27_0 anaconda --> 4.2.16-py27_0
> 
> Proceed ([y]/n)? y
> 
> Pruning fetched packages from the cache ...
> Fetching packages ...
> conda-4.2.16-p 100% |###############################| Time: 0:00:00  29.97 MB/s
> Extracting packages ...
> [      COMPLETE      ]|##################################################| 100%
> Unlinking packages ...
> [      COMPLETE      ]|##################################################| 100%
> Linking packages ...
> [      COMPLETE      ]|##################################################| 100%
> ```

this worked for me, thanks

**Comment by mountain-shui** [comment]
> for those of you who are still stuck on this issue:
> **ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'. CondaError: Cannot link a source that does not exist. C:..........\conda.exe Running `conda clean --packages` may resolve your problem.**
> 
> running `conda install tqdm -f` before running `conda update conda` solved the issue for me

thanks,this worked for me!

**Comment by BAkrseddik** [comment]
i can't install jupyter or numpy and always give me this msg
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.59.0-pyhd3eb1b0_1'.
CondaError: Cannot link a source that does not exist. C:\Users\20100\Anaconda3\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\20100\Anaconda3  (writable)
    default environment : C:\Users\20100\Anaconda3
       envs directories : C:\Users\20100\Anaconda3\envs
                          C:\Users\20100\AppData\Local\conda\conda\envs
                          C:\Users\20100\.conda\envs
          package cache : C:\Users\20100\Anaconda3\pkgs
                          C:\Users\20100\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.18362
          administrator : False
