### ISSUE TITLE
Conda Config --add channels "some big path with spaces" adding two lines into .CONDARC and corrupting file

### ISSUE THREAD

**Issue by seahawks8** [conda/conda#6068]
I am running the following command 
`conda config --add channels "some big path with spaces and lots of spaces"`

however it writes to the .CONDARC file but creates a new line and makes the file unreadable
here is what the result .CONDARC file looks like

```
channels:
  - some big path with spaces and lots of spaces with additional spaces that
	i have no control over
  - conda-forge
  - defaults
```

**Comment by seahawks8** [comment]
should of added, but I get the following error
`Load Error: in some_path\.condarc on line 3, column 2. Invalid YAML`

**Comment by kalefranz** [comment]
What channel has spaces?  Also you forgot the closing quote, even if there were a valid channel containing spaces.

**Comment by seahawks8** [comment]
I did have the closing space when running in CMD, just did not paste over correctly into thread

I want to add a shared IT network drive as a custom conda channel, but the drive has spaces :( that is out of my control to replace with proper text.

**Comment by kalefranz** [comment]
Channels need to be urls.  So use `file://` urls and url-escaping for spaces.

    conda config --add channels "some big path with spaces and lots of spaces"

Does not reproduce your bad yaml issue using conda 4.3.27.

**Comment by seahawks8** [comment]
Yup, I am running 4.3.27 as well, that worked, by adding the url and url-espacing for spaces (in my case used %20)

Thanks!
