### ISSUE TITLE
BUG: astropy 2.0.2 uninstallable on linux-64

### ISSUE THREAD

**Issue by bsipocz** [conda/conda#6069]
The latest version of astropy from the default channel is currently uninstallable using the astropy standard ci setups due to a ``PackageNotFoundError``:

https://travis-ci.org/astropy/astroquery/jobs/282622662#L780

```
Package plan for installation in environment /home/travis/miniconda/envs/test:

The following NEW packages will be INSTALLED:

    mkl:   2017.0.3-0   

    numpy: 1.13.1-py36_0

Fetching package metadata .............

Solving package specifications: 

PackageNotFoundError: Dependency missing in current linux-64 channels: 

  - astropy 2.0.2* -> libgcc-ng >=7.2.0

Close matches found; did you mean one of these?

    libgcc-ng: libgcc
```
Installing it from ``conda-forge`` works however. 

ping @msarahan

**Comment by msarahan** [comment]
You might need to update conda.  I also probably need to rebuild the package.  With the Anaconda 5 release, we're using new tools.

```CONDA_SUBDIR=linux-64 conda search libgcc-ng
Fetching package metadata ...............
libgcc-ng                    7.2.0                hcbc56d2_1  defaults
```

That package does exist on defaults, but it's in the new "main" channel.  This channel is added automatically by conda 4.3.27 or higher.

So, I've built the current package on old defaults with the new tools, and it added a dependency that requires the new channel.  I should also provide new builds that use the old tool in the old defaults.

**Comment by bsipocz** [comment]
Oh, gotcha. At some point we've decided to pin the conda version in ``ci-helpers`` as new releases kept breaking some parts of the infrastructure, so now we've updating it when we know we'll have time to sort out possible issues. 

Is the an announcement channel for conda releases? Just to realize when a major release is coming out?

**Comment by msarahan** [comment]
The big anaconda 5 release was very rushed and we haven't had a big announcement yet.  Your approach is very sane, given history.

This wasn't a new major conda version - it was a very small conda release with enormous implications in other ways.  Sort of hard to say what the right versioning should be!

**Comment by bsipocz** [comment]
Thanks for the info. I'll try it out with a few packages, and will update the version if there is an overall travis happiness...

**Comment by kalefranz** [comment]
> Is the an announcement channel for conda releases? Just to realize when a major release is coming out?

There's an RSS feed listed at https://repo.continuum.io/pkgs/ .  Right now it's a little out of date; we have to hook it into the new pkgs/main.  There's also an announcement list that gets used especially for major conda updates.  https://conda.io/docs/help-support.html#conda-announcements-list

**Comment by kalefranz** [comment]
Looks like this issue can now be closed?

**Comment by msarahan** [comment]
I believe I still need to build astropy 2.0.2 on the free channel with old tools.  We can at least move this issue to anaconda-issues if you'd like.

**Comment by bsipocz** [comment]
Yes, we've updated the conda version in ci-helpers, so the 2.0.2 version is picked up.

However, somewhat unrelated, that we saw weird probably related issues with mpl. Using the same version number of packages installed with pip, everything passes, just as when the conda version is limited to 4.3.21. We haven't fully investigated the issue, but please ping us if you're reported something similar.

Just rerun it again with our latest master: https://travis-ci.org/bsipocz/astropy/jobs/287155667
