### ISSUE TITLE
Specifying the priority of pip installed packages.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6070]
Hi,

Recently if I have packages installed with 'pip install' and they are provided in a channel, then conda install overrides them. For example
```
conda list mpi4py

# packages in environment at /home/yfeng1/anaconda3/install:
#
mpi4py                    2.0.0                    <pip>

conda install mpi4py
....
...
following will be installed ....
mpi4py2.0.0.py35_2
...
[y/N]
```
Is there a way to override this?

The documentation does not seem to say a way of specifying the priority of pip managed packages against conda managed ones. It would be nice to give pip managed packages a higher priority than conda ones by default -- because it usually suggests the packages must be recompiled on the local site. (for example x86_64 super computers all have different MPI libraries)

**Comment by kalefranz** [comment]
We have plans to implement something as you describe with a concept we are calling shadow packages.  That work will be tracked elsewhere.

**Comment by rainwoodman** [comment]
Thanks. Is there a reference link?
