### ISSUE TITLE
conda env create -f env.yml

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#6072]
Hello,

After having read the help for `conda env create`:
https://conda.io/docs/commands/env/conda-env-create.html

and some testing, I have a question.

When you run:
```
conda env create -f env.yml
```

with `env.yml` being:
```
name: env

channels:
- chn1
- chn2
- chn3

dependencies:
- dep1
- dep2
- dep3
```
I was expecting the packakges `dep1`, `dep2`, and `dep3` to be installed just by using channels `chn1`, `chn2`, and `chn3` only. However, if also uses the channels in `~/.condarc`

However, for a environment file to be fully portable, `conda env create -f env.yml` should only use the channels listed in `env.yml`, am I wrong or missing something?

Best regards,
Sebastian

**Comment by noahp** [comment]
You can exclude the default system channels by adding "nodefaults" to the channel list in an environment file: https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually

So I think your proposal is to change the default channels to opt-in if any channels are specified in the yml, eg:
```yml
channels:
- chn1
- defaults  # include default channels as well
```
I think I agree that it's a little more intuitive that way.
