### ISSUE TITLE
`conda env create --file` errors one package at a time

### ISSUE THREAD

**Issue by mivade** [conda/conda#6073]
When trying to create a new environment from a environment YAML file that was created on one operating system, I get errors such as the following when running on another OS:

```
ResolvePackageNotFound: 
  - pango 1.39.0 1
```

The problem is that as soon as I comment the offending package out (since it is likely not a hard requirement, but rather just something that happened to be installed by whomever created the environment file), I just get another similar error for another package.

Considering it can take 10s of seconds before getting this error, it would be especially helpful to be presented with a list of all packages that can't be found instead of having to hunt them one at a time.

**Comment by MichaelJendryke** [comment]
+1

**Comment by matthiasroder** [comment]
I run into the same issue.

`conda env create -f environment.yml -v`

gives me:

`Traceback (most recent call last):
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 475, in install_actions_list
        dists_for_envs = determine_all_envs(r, specs, channel_priority_map=channel_priority_map)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 540, in determine_all_envs
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 540, in <genexpr>
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in <genexpr>
        best_pkgs = (r.index[r.get_dists_for_spec(s, emptyok=False)[-1]] for s in specs)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 563, in get_dists_for_spec
        raise ResolvePackageNotFound([(ms,)])
    ResolvePackageNotFound:
      - backports 1.0 py27h6492d98_1`

I suspect that this has something to do with "channels" and how conda sorts dependencies. I therefore wanted to see whether the situation would be solved by using the old "sorting algorithm":

`conda config --set channel_priority false`

and then again:

`conda env create -f environment.yml -v`

to no avail.

**Comment by colllin** [comment]
Is anyone looking into this?  I am experiencing the same problem after exporting a conda environment on macOS and then trying to reproduce the environment on Ubuntu 16.04.  Actually this is literally the only thing I did.  

- I started on macOS,
- installed some dependencies,
- realized the data was too big, 
- exported the environment, 
- spun up an Ubuntu instance on EC2,
- cloned the repo,
- tried to re-create the conda environment.

I exported using `conda env export > environment.yml`, and tried to re-create using `conda env create --name my-project --file environment.yml`. I receive the same error as reported by OP:

```
ResolvePackageNotFound: 
  - ca-certificates 2017.08.26 ha1e5d58_0
```

I also tried to first create a conda environment without the file, then install from the file, with a different error:

```
$ conda create --name my-project `grep -o 'python=[0-9.]\+' environment.yml`
$ conda install --file environment.yml
CondaValueError: could not parse 'name: my-project' in: environment.yml
```

This is the same error I receive if I try to create the environment from the file *using `conda create` rather than `conda env create`*.

**Comment by kalefranz** [comment]
Oftentimes build numbers don't match across platforms.  Use the `--no-builds` flag with `conda env export`.

    conda env export --no-builds > environment.yml

**Comment by mivade** [comment]
What I have generally been doing to work around this is to hand craft environment files rather than using `conda env export` and only including packages that I'm explicitly depending on. This is not always ideal (especially for things that might have a lot of dependencies), but it has been working well enough so far.

**Comment by colllin** [comment]
Thanks for the `--no-builds` tip, @kalefranz.  That seemed promising.  I believe this changes the problem, but I still have similar looking errors, albeit a much smaller list of failed packages:

```
ResolvePackageNotFound: 
  - appnope=0.1.0
  - libcxx=4.0.1
  - libgfortran=3.0.1
  - libcxxabi=4.0.1
```

Note: I also ran `conda update conda`, which updated me to 4.4.7 (miniconda and anaconda don't ship with latest conda?).

Is there a simple explanation here?  The linux channels are not in-sync with the macOS channels?  Or... I'm fairly new to python...  Can package dependencies vary depending on the destination platform?

@mivade, good idea...  Glad to hear it's a working path forward.  It kind of defeats the purpose of using an environment manager, though — even if I am open to it, it would be ridiculous to try to get my team on-board, and expect them to learn how to do it and get it right, with complexities such as channels, etc.  But I'm not sure what other option I have right now!

I believe `npm install` (with `--save`) and `yarn add` behave similarly to what @mivade describes.  When you install/add a package, it only writes *that package* to your manifest, but will also install any dependencies.  The dependencies don't need to be written, because they are just that — dependencies — and can be determined dynamically at install-time.  I believe this is a better pattern than what is currently followed by `conda env export`, which appears to be more equivalent to a lock-file, which works great in node-land, but apparently doesn't work so well in python-land.

I have already wasted too much time on these issues to dig any further on my own.  If you have other ideas, I will definitely give them a shot.

**Comment by kalefranz** [comment]
The reason this issue is tagged as a feature request and with the “environment-spec” tag is because we know there’s quite a bit of work we need to do here to improve the user experience. 

Indeed `conda env export` should only include, or have a mode that only includes, “user-provided” specs, and not the equivalent of a lock file that lists every package in the environment.

**Comment by maxwellmckinnon** [comment]
I also am blocked by the libcxx issue

`Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............

ResolvePackageNotFound:
  - libcxx 4.0.1*`

Like the original poster said, very aggravating that it takes 10s to see the failure, then fixing it just brings on more.

Can't there be a switch to just install everything possible from the environment, then alert which ones failed afterward? This defeats the #1 promise of anaconda being a solution to the "runs on my computer" problem. The biggest/only thing I want from anaconda is the export reqs and import reqs to work flawlessly.

Is there another workflow I'm missing that is the intended path of deploying code to another computer? I thought it was supposed to be `conda env export > env.yml` on one, `conda create env -f env.yml` on the other.

**Comment by gabegm** [comment]
Have the same problem, had to manually remove the dependencies causing the error from the env file.
ResolvePackageNotFound:
  - libcxxabi=4.0.1
  - libcxx=4.0.1
Exported the env from macOS and tried to import on Linux

**Comment by pattersongp** [comment]
+1

**Comment by leemengtaiwan** [comment]
Exactly same problem like @gabegm even if I used 
```
conda env export --no-builds > environment.yaml
```
Had to manually remote the dependencies

```
libcxxabi=4.0.1
libcxx=4.0.1
```

which should be handle more gracefully by conda.

**Comment by ryanrunchey** [comment]
Same problem

conda env create --force -f=/Users/ryanrunchey/Downloads/gcloud_ryanrunchey_starling_conda_env_base_2018-07-25/environment.yml -n gcloud_starling_base

Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............

ResolvePackageNotFound: 
  - gensim 3.5.0 py36_0

**Comment by howie** [comment]
Same problem on ubuntu 

conda.exceptions.ResolvePackageNotFound:
  - libcxxabi=4.0.1
  - libgfortran=3.0.1
  - libcxx=4.0.1

**Comment by mingwandroid** [comment]
@howie, you cannot share env files between OSes, your env file has come from macOS here.

**Comment by mingwandroid** [comment]
My suggestion is that you generate an env file on each OS and then update your tooling to use the appropriate one given the current OS.

**Comment by howie** [comment]
@mingwandroid thanks for your information 😂

**Comment by aakashns** [comment]
> My suggestion is that you generate an env file on each OS and then update your tooling to use the appropriate one given the current OS.

@mingwandroid Is there a way to get `conda` to ignore the unresolved packages, and proceed with the installation?

**Comment by Arslan-Zaidi** [comment]
Same problem here.

ResolvePackageNotFound: 
  - appnope 0.1.0
  - libcxxabi 4.0.1
  - libgfortran 3.0.1

Things I've tried:
1. --no-builds
2. added all channels that were present on macOS (where the env was created)
3. manually removed the above mentioned packages from the .yml file

These steps seemed to do it, but I think it was only no. 3 that fixed the issue as I tried the first two individually to no avail.

**Comment by aakashns** [comment]
> manually removed the above mentioned packages from the .yml file
It appears this is what most people (including me) end up doing most of the time. `conda` should probably add a `--ignore-missing` flag to do this automatically

**Comment by sheegl** [comment]
I came across this issue when trying to export my `environment.yml` and run on other systems. I was mainly interested in getting version numbers for my dependencies. So I wrote a quick dirty script that exports the environment, picks the version numbers and adds them to the `environment.yml`. This doesn't add any unexpected dependencies that cause inconsistencies on other systems.

```python
#!/usr/bin/env python

import subprocess
import re
import sys

env_filepath = sys.argv[1]

with open(env_filepath, 'r') as f:
    env_yml = f.read()

env_name = re.search('^name: (.+)', env_yml, flags=re.MULTILINE).group(1)
env_export = subprocess.check_output(
    'conda env export --name ' + env_name + ' --no-builds', shell=True
).strip().decode('utf-8')

for line in env_yml.split('\n'):
    if line:
        m = re.search(line.strip() + '(==?.+)', env_export, flags=re.MULTILINE)
        if m:
            print(line + m.group(1))
        else:
            print(line)
    else:
        print()
```

**Comment by johnprakashgithub** [comment]
Getting same error while creating conda environment


ResolvePackageNotFound:
  - libcxx
  - libcxxabi

**Comment by yiannis-kt** [comment]
```
conda env export --no-builds | grep -v "^prefix: " > environment.yml
```

produces

```
name: falcon-app
channels:
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.22.0
  - atomicwrites=1.3.0
  - attrs=15.2.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2016.2.28
  - cffi=1.10.0
  - cryptography=1.8.1
  - cryptography-vectors=2.6.1
  - cython=0.26
  - decorator=4.1.2
  - docopt=0.6.2
  - falcon=1.4.1
  - idna=2.6
  - intel-openmp=2019.1
  - ipython=6.1.0
  - ipython_genutils=0.1.0
  - jedi=0.10.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libiconv=1.14
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.2
  - libstdcxx-ng=8.2.0
  - mkl=2017.0.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=3.2.0
  - ncurses=6.1
  - nomkl=1.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openblas=0.3.5
  - openblas-devel=0.3.2
  - openssl=1.0.2l
  - packaging=16.8
  - pandas=0.24.2
  - parso=0.3.4
  - pastedeploy=1.5.2
  - pep8=1.7.0
  - pexpect=4.2.1
  - pickleshare=0.7.5
  - pip=9.0.1
  - pluggy=0.9.0
  - prompt_toolkit=1.0.14
  - ptyprocess=0.5.2
  - py=1.4.34
  - pyasn1=0.2.3
  - pycparser=2.18
  - pygments=2.1.3
  - pyodbc=4.0.17
  - pyopenssl=17.0.0
  - pyparsing=2.2.0
  - pytest=3.2.1
  - python=3.6.2
  - python-dateutil=2.6.1
  - python-mimeparse=1.6.0
  - pytz=2017.2
  - readline=6.2
  - setuptools=36.4.0
  - simplegeneric=0.8.1
  - six=1.10.0
  - sqlite=3.13.0
  - tk=8.5.18
  - traitlets=4.3.1
  - ujson=1.35
  - unixodbc=2.3.4
  - wcwidth=0.1.7
  - websocket-client=0.55.0
  - wheel=0.29.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - gunicorn==19.1.0
    - pyexasol==0.3.31
    - rsa==3.4.2
```

then,

```
╰─➤  conda env create -n deleteme -f environment.yml        
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound: 
  - mkl=2017.0.3
  - docopt=0.6.2 -> python
  - idna=2.6 -> python
  - pyparsing=2.2.0 -> python
  - libiconv=1.14
  - python-dateutil=2.6.1
  - pytz=2017.2
  - asn1crypto=0.22.0
  - pep8=1.7.0
  - pygments=2.1.3
  - zlib=1.2.11
  - intel-openmp=2019.1
  - pluggy=0.9.0 -> python
  - readline=6.2
  - atomicwrites=1.3.0 -> python
  - cython=0.26
  - libopenblas=0.3.2
  - ujson=1.35
  - websocket-client=0.55.0
  - pip=9.0.1
  - pycparser=2.18 -> python
  - liblapack=3.8.0
  - blas=1.0
  - ncurses=6.1
  - libstdcxx-ng=8.2.0
  - wheel=0.29.0
  - cffi=1.10.0
  - mkl_random=1.0.2
  - python=3.6.2
  - liblapacke=3.8.0
  - packaging=16.8
  - libffi=3.2.1
  - jedi=0.10.2
  - libcblas=3.8.0
  - openblas-devel=0.3.2
  - pickleshare=0.7.5
  - pandas=0.24.2
  - decorator=4.1.2
  - certifi=2016.2.28
  - wcwidth=0.1.7 -> python
  - attrs=15.2.0
  - openblas=0.3.5
  - cryptography-vectors=2.6.1 -> python
  - ipython_genutils=0.1.0
  - python-mimeparse=1.6.0 -> python
  - libgfortran-ng=7.3.0
  - numpy=1.16.2
  - tk=8.5.18
  - pastedeploy=1.5.2 -> python
  - pastedeploy=1.5.2 -> setuptools
  - pexpect=4.2.1
  - sqlite=3.13.0
  - ipython=6.1.0
  - py=1.4.34
  - simplegeneric=0.8.1 -> python
  - mkl_fft=1.0.10
  - nomkl=1.0
  - pytest=3.2.1
  - libgcc-ng=8.2.0
  - ca-certificates=2019.1.23
  - traitlets=4.3.1
  - backcall=0.1.0 -> python
  - more-itertools=3.2.0
  - falcon=1.4.1
  - parso=0.3.4 -> python
  - libedit=3.1.20181209
  - libblas=3.8.0
  - ptyprocess=0.5.2
  - pyasn1=0.2.3
  - cryptography=1.8.1
  - pyopenssl=17.0.0
  - setuptools=36.4.0
  - xz=5.2.3
  - openssl=1.0.2l
  - six=1.10.0
  - libgfortran=3.0.0
  - numpy-base=1.16.2
  - pyodbc=4.0.17
  - prompt_toolkit=1.0.14
  - unixodbc=2.3.4
```

how is that even possible? :(

**Comment by cognitiaclaeves** [comment]
+1 on the --ignore-missing suggestion. Please implement this. I can manually drop the incorrect libraries out of generated file, but this doesn't protect me from changes that can happen in future packaging in conda and conda-forge.

**Comment by alexvicegrab** [comment]
Still relevant. Would be fantastic if we could export conda environments with an option to minimally specify user-installed packages, as an extra flag.

**Comment by payneio** [comment]
Same problem. Export in macos import in ubuntu. `libcxx` and `libcxxabi`

**Comment by joe0750** [comment]
Same problem.  libssh2

**Comment by PowerToThePeople111** [comment]
I would also be interested in a solution that allows to properly move envs around by just creating a yml.

For me it is:
```
ResolvePackageNotFound:
  - libcxxabi=4.0.1
  - libcxx=4.0.1
  - libgfortran=3.0.1
  - appnope=0.1.0
```

**Comment by danielmiskell** [comment]
Same problem had to manually remove the packages causing errors.

**Comment by joleroi** [comment]
I had the same problem with ``libcxx`` and ``libcxxabi``. I am also running MacOS and want to use the environement file on a linux machine.

I circumvented it by starting a docker image that runs linux 

```
docker run -it ubuntu bash
``` 

create my conda env there from scratch and exported it

```
conda env export --no-builds > environment_linux.yml
```

and copied the file to my MacOS machine for further use

**Comment by xuyangkang** [comment]
Same problem.

```
Getting same error while creating conda environment

ResolvePackageNotFound:

libcxx
libcxxabi
```

I'm using macos for development and linux for production. I exported conda env on mac, tried to create the same env in linux, and shows these error.

The reason is libcxx and libcxxabi are macos only packages. They are not in linux channel. I think we should think a solution to deal with platform specific packages.

**Comment by jooddang** [comment]
It's been years that folks want this issued to be solved and I'm one of them. While being a fan of miniconda, I see other package managers (like poetry?) deal with cross platform problem well.

**Comment by marcelm** [comment]
A Conda running on Linux can be forced to use macOS packages when resolving environments. I use this to create proper `environment.linux.lock.yml` *and* `environment.osx.lock.yml` files from a single script, without access to a Mac.

The trick is to temporarily add this to `~./condarc`:
```
subdir: osx-64
subdirs:
  - osx-64
  - noarch
```
With this, Conda will happily create macOS environments even on Linux. These will not be functional, of course, but can then be `conda env export`ed to create an environment file that works on macOS. Using `--no-builds` isn’t necessary in this step.

I believe this works also in the other direction, that is, creating Linux environments on macOS.

Here’s a cleaned-up version of the script I’m using:
https://gist.github.com/marcelm/32dc00cb5e4018670294d2508883402d

This is slightly hackish of course, but may be helpful until we get a proper solution.

**Comment by NonMundaneDev** [comment]
> I came across this issue when trying to export my `environment.yml` and run on other systems. I was mainly interested in getting version numbers for my dependencies. So I wrote a quick dirty script that exports the environment, picks the version numbers and adds them to the `environment.yml`. This doesn't add any unexpected dependencies that cause inconsistencies on other systems.
> 
> ```python
> #!/usr/bin/env python
> 
> import subprocess
> import re
> import sys
> 
> env_filepath = sys.argv[1]
> 
> with open(env_filepath, 'r') as f:
>     env_yml = f.read()
> 
> env_name = re.search('^name: (.+)', env_yml, flags=re.MULTILINE).group(1)
> env_export = subprocess.check_output(
>     'conda env export --name ' + env_name + ' --no-builds', shell=True
> ).strip().decode('utf-8')
> 
> for line in env_yml.split('\n'):
>     if line:
>         m = re.search(line.strip() + '(==?.+)', env_export, flags=re.MULTILINE)
>         if m:
>             print(line + m.group(1))
>         else:
>             print(line)
>     else:
>         print()
> ```
> 
> Just pass your `environment.yml` path to the script. Hope this helps someone.

Hello. Thank you for this script. Please how do I use it as in your last statement " Just pass your `environment.yml` path to the script".?

**Comment by AdrienWehrle** [comment]
> > I came across this issue when trying to export my `environment.yml` and run on other systems. I was mainly interested in getting version numbers for my dependencies. So I wrote a quick dirty script that exports the environment, picks the version numbers and adds them to the `environment.yml`. This doesn't add any unexpected dependencies that cause inconsistencies on other systems.
> > ```python
> > #!/usr/bin/env python
> > 
> > import subprocess
> > import re
> > import sys
> > 
> > env_filepath = sys.argv[1]
> > 
> > with open(env_filepath, 'r') as f:
> >     env_yml = f.read()
> > 
> > env_name = re.search('^name: (.+)', env_yml, flags=re.MULTILINE).group(1)
> > env_export = subprocess.check_output(
> >     'conda env export --name ' + env_name + ' --no-builds', shell=True
> > ).strip().decode('utf-8')
> > 
> > for line in env_yml.split('\n'):
> >     if line:
> >         m = re.search(line.strip() + '(==?.+)', env_export, flags=re.MULTILINE)
> >         if m:
> >             print(line + m.group(1))
> >         else:
> >             print(line)
> >     else:
> >         print()
> > ```
> > 
> > 
> > Just pass your `environment.yml` path to the script. Hope this helps someone.
> 
> Hello. Thank you for this script. Please how do I use it as in your last statement " Just pass your `environment.yml` path to the script".?

Hi!
=python your_code.py your_file.yml= with =your_code.py= the name you gave to this code, =your_file.yml=  is transparent. =sys.argv[1]= points to the second entry of your command. You could also just replace =sys.argv[1]= with your .yml file in a string and run the code.

**Comment by HarshaSuranjith** [comment]
> Same problem on ubuntu
> 
> conda.exceptions.ResolvePackageNotFound:
> 
> * libcxxabi=4.0.1
> * libgfortran=3.0.1
> * libcxx=4.0.1

Any woraround for this ??

**Comment by Vampirebat** [comment]
> I came across this issue when trying to export my `environment.yml` and run on other systems. I was mainly interested in getting version numbers for my dependencies. So I wrote a quick dirty script that exports the environment, picks the version numbers and adds them to the `environment.yml`. This doesn't add any unexpected dependencies that cause inconsistencies on other systems.
> 
> ```python
> #!/usr/bin/env python
> 
> import subprocess
> import re
> import sys
> 
> env_filepath = sys.argv[1]
> 
> with open(env_filepath, 'r') as f:
>     env_yml = f.read()
> 
> env_name = re.search('^name: (.+)', env_yml, flags=re.MULTILINE).group(1)
> env_export = subprocess.check_output(
>     'conda env export --name ' + env_name + ' --no-builds', shell=True
> ).strip().decode('utf-8')
> 
> for line in env_yml.split('\n'):
>     if line:
>         m = re.search(line.strip() + '(==?.+)', env_export, flags=re.MULTILINE)
>         if m:
>             print(line + m.group(1))
>         else:
>             print(line)
>     else:
>         print()
> ```
> 
> Just pass your `environment.yml` path to the script. Hope this helps someone.

i thought anaconda was specifically doing this... i thought that the whole point of a yml file was to download EXACTLY what a program needs for its dependencies.

**Comment by leihuayi** [comment]
@PowerToThePeople111 @howie @Arslan-Zaidi @leemengtaiwan it seems that some precise versions of packages only exist for osx:
  - libcxx=4.0.1 (see [here](https://anaconda.org/search?q=libcxx))
  - libgfortran=3.0.1 (see here)(https://anaconda.org/search?q=libcxx)
that is why it probably fails when you try to install it on linux. It would be nice if Anaconda Cloud informed which versions are equivalent on other platforms.

**Comment by thesofakillers** [comment]
is there really no solution to this? We just have to manually remove these packages?

**Comment by ProspectDataIntern** [comment]
I have the same issue, beginning to think the `environment.yml` is nothing more than a myth to give you the illusion of having more portability.

**Comment by mivade** [comment]
Yeah I've never been a fan of bots that close issues just because there haven't been any comments in a while. AFAIK this is still an issue. I only ever craft `environment.yml` files by hand these days which only lists explicit dependencies. This is an OK approach but doesn't really allow for true reproducibility.

**Comment by zhengxu001** [comment]
> is there really no solution to this? We just have to manually remove these packages?

No need to remove these packages entirely. I manually moved these packages from the dependencies section to the pip section and problem solved!
