### ISSUE TITLE
missing rpath for libmkl_intel_thread?

### ISSUE THREAD

**Issue by stevengj** [conda/conda#6074]
In Julia, which loads `libpython` as a shared library (installed via conda by default), we are suddenly (with a recent conda upgrade) getting MKL failures on MacOS because it can't find `libmkl_intel_thread.dylib`.     Manually setting `LD_LIBRARY_PATH` to Conda's `usr/lib` directory (where that library is found) fixes the problem, but that didn't used to be required, and isn't required if I run the `python` executable directly.

My guess is that there is a missing shared-library dependency somewhere — something in numpy should have explicitly linked `-lmkl_intel_thread` but didn't do so?  Or maybe a missing `-rpath` linker argument?

For example, we get this when plotting via matplotlib (JuliaPy/PyPlot.jl#315), but also when calling any numpy linear-algebra function:
```
julia> using PyCall

julia> pyimport("numpy.linalg")["inv"](rand(100,100))
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
```
(This just calls `numpy.linalg.inv` on a random 100x100 numpy matrix.  Under the hood, it is calling `PyImport_ImportModule("numpy.linalg")` in `libpython`, etcetera, using Python's standard C embedding API.)

**Comment by stevengj** [comment]
`otool -L usr/pkgs/numpy-1.11.1-py27_0/lib/python2.7/site-packages/numpy/linalg/_umath_linalg.so` gives
```
	@rpath/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_intel_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
```
so it looks like `libmkl_intel_thread.dylib` is explicitly linked.

If I run `otool -l` on either the `python` executable or on `libpython2.7.dylib`, I get two `LC_RPATH` commands to [add paths to the library search path](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/dyld.1.html):
```
Load command 15
          cmd LC_RPATH
      cmdsize 272
         path /Users/stevenj/.julia/v0.6/Conda/deps/usr/lib (offset 12)
Load command 18
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../lib/ (offset 12)
```
Notice that it has both the absolute path of my conda `/usr/lib` directory and also a path relative to `@loader_path`.   Both of these seem correct.

Clearly, there's something I don't understand about how MacOS resolves shared-library search paths.   Something is not getting set correctly when we open `libpython` dynamically via `dlopen`. 

But what has changed recently in Conda's NumPy package that would cause this to suddenly appear?  Are you linking differently than you used to?

**Comment by stevengj** [comment]
It seems like the problem is specific to `libmkl_intel_thread`, since if I manually `dlopen` that library (and the `libompi5` OpenMP library it requires), then NumPy works fine even without setting `LD_LIBRARY_PATH`:
```jl
julia> Libdl.dlopen("/Users/stevenj/.julia/v0.6/Conda//deps/usr/lib/libiomp5.dylib")
          Libdl.dlopen("/Users/stevenj/.julia/v0.6/Conda//deps/usr/lib/libmkl_intel_thread.dylib")

julia> .... call numpy.linalg.inv, it works ....
```

**Comment by stevengj** [comment]
cc @asmeurer, who has worked on `rpath` issues in the past (conda/conda-build#312).  (Should I have reported this in conda/conda-build instead?  Sorry!)

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6423

**Comment by montyvesselinov** [comment]
This bug impacts also the pyplot performance:

https://travis-ci.org/madsjulia/Mads.jl/jobs/281775921
