### ISSUE TITLE
Error message when creating a new environment from a yml file

### ISSUE THREAD

**Issue by vhriebes** [conda/conda#6077]
I'm trying to create a new environment from a yml file. However, I am getting an error message when trying to do this. I don't have a lot of programming experience and followed this website's instructions: https://conda.io/docs/user-guide/tasks/manage-environments.html

This is the error message I got:

C:\Users\User\Desktop>conda env create -f python2.7-environment.yml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Users\Valentin\AppData\Local\conda\conda\envs
                          C:\Program Files\Anaconda3\envs
                          C:\Users\Valentin\.conda\envs
          package cache : C:\Program Files\Anaconda3\pkgs
                          C:\Users\Valentin\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Program Files\Anaconda3\Scripts\conda-env-script.py create -f python2.7-environment.yml`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Program Files\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
        if spec.can_handle():
      File "C:\Program Files\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda_env\env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda_env\env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 75, in load
        return loader.get_single_data()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 53, in get_single_node
        document = self.compose_document()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 76, in compose_document
        self.get_event()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 136, in get_event
        self.current_event = self.state()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 215, in parse_document_end
        token = self.peek_token()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 239, in fetch_more_tokens
        return self.fetch_value()
      File "C:\Program Files\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 598, in fetch_value
        self.get_mark())
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 327, column 24:
          <!-- blob contrib key: blob_contributors:v21:6a96baf8 ...
                               ^

Thank you for the help!

**Comment by kalefranz** [comment]
Can you provide the output of `conda list` ?

**Comment by vhriebes** [comment]
C:\Users\Valentin\Desktop>conda list
# packages in environment at C:\Program Files\Anaconda3:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  4.2.0               np111py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
catalyst                  0.1.post1                 <pip>
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.27                   py35_0    conda-forge
conda-build               2.0.2                    py35_0
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.3                    py35_0
mkl                       2017.0.3                      0
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.4                    py35_0    conda-forge
numpy                     1.13.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.3.1                    py35_0
pip                       9.0.1                     <pip>
pip                       8.1.2                    py35_0
pkginfo                   1.3.2                    py35_0
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pylint                    1.5.4                    py35_1
pyopenssl                 16.2.0                   py35_0    conda-forge
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
requests                  2.13.0                   py35_0    conda-forge
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.19.0              np113py35_0
scipy                     0.19.1              np113py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by kalefranz** [comment]
Can you provide the contents of `python2.7-environment.yml`?

**Comment by vhriebes** [comment]
The can be downloaded under Installation Process, Step 3 here: 
https://github.com/enigmampc/catalyst-docs/wiki/Catalyst-Installation-Instructions-for-Windows-10-Users
This is what comes up when I open it as a txt:
name: catalyst
channels:
- statiskit
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- coverage=4.4.1=py27_0
- nose=1.3.7=py27_1
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pip=9.0.1=py27_1
- python=2.7.13=0
- pyyaml=3.12=py27_0
- readline=6.2=2
- setuptools=36.4.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.11=0
- libdev=1.0.0=py27_0
- python-dev=1.0.0=py27_0
- python-scons=3.0.0=py27_0
- pip:
  - alembic==0.9.5
  - backports.shutil-get-terminal-size==1.0.0
  - bcolz==0.12.1
  - bottleneck==1.2.1
  - chardet==3.0.4
  - click==6.7
  - contextlib2==0.5.5
  - cycler==0.10.0
  - cyordereddict==1.0.0
  - cython==0.26.1
  - decorator==4.1.2
  - empyrical==0.2.1
  - enigma-catalyst>=0.2.dev2
  - enum34==1.1.6
  - functools32==3.2.3.post2
  - idna==2.6
  - intervaltree==2.1.0
  - ipdb==0.10.3
  - ipdbplugin==1.4.5
  - ipython==5.5.0
  - ipython-genutils==0.2.0
  - logbook==1.1.0
  - lru-dict==1.1.6
  - mako==1.0.7
  - markupsafe==1.0
  - matplotlib==2.0.2
  - multipledispatch==0.4.9
  - networkx==1.11
  - numexpr==2.6.4
  - numpy==1.13.1
  - pandas==0.19.2
  - pandas-datareader==0.5.0
  - pathlib2==2.3.0
  - patsy==0.4.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - pytz==2017.2
  - requests==2.18.4
  - requests-file==1.4.2
  - requests-ftp==0.3.1
  - scandir==1.5
  - scipy==0.19.1
  - scons==3.0.0a20170821
  - simplegeneric==0.8.1
  - sortedcontainers==1.5.7
  - sqlalchemy==1.1.14
  - statsmodels==0.8.0
  - subprocess32==3.2.7
  - tables==3.4.2
  - toolz==0.8.2
  - traitlets==4.3.2
  - urllib3==1.22
  - wcwidth==0.1.7

**Comment by kalefranz** [comment]
The stack trace is indicating a yaml parse error in your file `python2.7-environment.yml`. Probably best to go to https://raw.githubusercontent.com/enigmampc/catalyst/master/etc/python2.7-environment.yml, and then copy and paste that content using something like notepad.
