### ISSUE TITLE
conda upgrade failed - ERROR conda.core.link:_execute_actions

### ISSUE THREAD

**Issue by varoudis** [conda/conda#6078]
Hi,

conda upgrade --all with conda-forge added in the list fails on windows 64bit (both 2.7 and 3.6 py tested)

On Mac everything is ok on exaclty same install scenario.

Any ideas?
Thanks

> DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
>  prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
> 'system'
> DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
>  prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
> 'system'
> DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
>  prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
> 'system'
> ERROR conda.core.link:_execute_actions(337): An error occurred while installing
> package 'conda-forge::wheel-0.30.0-py_1'.
> CondaError: Cannot link a source that does not exist. C:\ProgramData\Anaconda3\S
> cripts\conda.exe
> Attempting to roll back.
> 
> DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
>  prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
> 'system'

**Comment by kalefranz** [comment]
Try `conda clean --all` and see if you keep having the issue...

**Comment by varoudis** [comment]
same error. no change at all.

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by varoudis** [comment]
(C:\ProgramData\Anaconda3) C:\Users\varoudis\Documents>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\varoudis\AppData\Local\conda\conda\envs
                          C:\Users\varoudis\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\varoudis\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\varoudis\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/7 W
indows/6.1.7601
          administrator : True

(C:\ProgramData\Anaconda3) C:\Users\varoudis\Documents>

**Comment by kalefranz** [comment]
Probably need to just manually delete `C:\ProgramData\Anaconda3\pkgs` and `C:\Users\varoudis\AppData\Local\conda\conda\pkgs`.

**Comment by varoudis** [comment]
same error. nothing new. :(

**Comment by AlexM9200** [comment]
I'm getting this same error on Windows 10. Any help would be appreciated.

**Comment by ErinKenna** [comment]
I had the same issue on Windows 10 with miniconda (win-64, conda 4.3.27, python 3.6.3.final.0).
This worked for me using an admin prompt (install was not as admin).
`conda clean --all`
`conda update conda`
`conda update --all`

**Comment by varoudis** [comment]
even though I got some of the same errors, I didnt get the critical wheel error! 
I think this did it.
thanks @ErinKenna 

jupyter-1.0.0- 100% |###############################| Time: 0:00:00 586.33 kB/s
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
 prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
 prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
 prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
 prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'

(C:\ProgramData\Anaconda3) C:\Users\varoudis\Documents>

**Comment by hieyong** [comment]
When I use the prompt commander as an administrator, it seems that this terrible problem is solved.

**Comment by anjalinagel12** [comment]
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::nltk-3.2.5-py36h1190bce_0'.

Getting this error. Anyone knows how to solve it?

**Comment by marvinntale** [comment]
this worked for me 
conda clean --all
conda update conda
conda update --all

**Comment by MadhushreeB** [comment]
this worked for me
conda clean --all
conda update conda
conda update --all

**Comment by cuixing158** [comment]
this worked for me
conda clean --all
conda update conda
conda update --all
