### ISSUE TITLE
pip operation in cloned env alters root env

### ISSUE THREAD

**Issue by msarahan** [conda/conda#6079]
From ionutdam@gmail.com, via anaconda mailing list.  I have reproduced locally.

1. Clean install 5.0.0.0 only for current user in d:\anaconda

2. Clone root environment into "tf-gpu" environment

3. Activated tf-gpu

4. Installed tensorflow 1.3.0 with "pip install --ignore-installed --upgrade tensorflow-gpu" 

5. activated root env

6. see below ...

```
(tf-gpu) C:\Users\Andrei\Documents>activate root

(root) C:\Users\Andrei\Documents>pip
Traceback (most recent call last):
  File "d:\anaconda\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "d:\anaconda\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "d:\anaconda\lib\site-packages\pip\vcs\subversion.py", line 9, in <module>
    from pip.index import Link
  File "d:\anaconda\lib\site-packages\pip\index.py", line 33, in <module>
    from pip._vendor import html5lib, requests, six
ImportError: cannot import name 'html5lib'

(root) C:\Users\Andrei\Documents>
```

Note that tensorflow-gpu installs wheel, bleach, werkzeug, markdown, and html5lib as dependencies, in spite of the --ignore-installed argument.  I suspect that installing html5lib is causing the issue here.

**Comment by kalefranz** [comment]
It would sure be nice to start marking inodes read-only.  Tried it already, and ran into a few issues.
See https://github.com/conda/conda/pull/5296 and #681.

**Comment by andreidi** [comment]
Also - probably obvious - any newly created envs will be broken...

**Comment by kalefranz** [comment]
So everyone is working with the same common understanding, what's happening here is that when pip clobbers a file that exists in the environment, it does so without breaking the inode reference (i.e. removing it first), and rather just opens that inode in-place, thereby changing it's contents in the package cache and all environments that are linking that package.

**Comment by andreidi** [comment]
Any news regarding this issue ?

**Comment by kalefranz** [comment]
Tracking a fix via https://github.com/conda/conda/issues/6079

**Comment by kbrose** [comment]
@kalefranz "Tracking a fix via ..." did you mean to link to this same issue?
