### ISSUE TITLE
Unsatisfiable error: The following error found to be conflicted 

### ISSUE THREAD

**Issue by jhasuman** [conda/conda#6080]
Getting this error!! Please tell me how to fix that!! 

![error](https://user-images.githubusercontent.com/17616710/31237373-6d3702a2-aa14-11e7-8577-df8693a78da6.png)

**Comment by kalefranz** [comment]
That message indicates that either mss or basemap don't have any available packages built for python 3.6.

**Comment by kalefranz** [comment]
Perfect situation to use a conda environment.
