### ISSUE TITLE
conda build can't seem to download CRAN packages despite proxy settings

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6081]
_From @mcg1969 on August 30, 2017 14:5_

Submitted on behalf of another user, but note that I have reproduced this myself on their system.

We're running conda-build 2.1.15 with requests 2.12.4 here. Steps to reproduce:
```
conda skeleton cran ldavis
conda build r-ldavis
```
During the build process, the CRAN package cannot be downloaded:
```
Source cache directory is: /opt/wakari/anaconda/conda-bld/src_cache
Downloading source to cache: LDAvis_0.3.2.tar.gz
Downloading https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Downloading https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download LDAvis_0.3.2.tar.gz
```
Using `wget` to download the package from the same URL works just fine, giving evidence that the proxy settings are correct.

The user reports that it worked before. He was running 2.1.7 at the time, but upgrading to 2.1.15 did not help. It's not clear then what could have changed from when it worked for him and when it did not, so it's possible the issue is environment-specific. Nevertheless, if wget is successfully able to navigate the proxy, it stands to reason that conda-build should be able to as well.

_Copied from original issue: conda/conda-build#2336_

**Comment by kalefranz** [comment]
_From @mcg1969 on August 30, 2017 14:42_

cc: @kalefranz 

@msarahan and I have determined that the failure is occurring inside the `conda.gateways.download.download()` method, which conda-build uses to fetch the package. A little printf debugging reveals that `session.proxies` is empty.

**Comment by kalefranz** [comment]
_From @stephenakearns on October 3, 2017 3:8_

Hi @msarahan and @csoja - any chance of looking at this now that we're thru the release of AD5? The associated #GSK support ticket has been open for a month now and I'm wondering if this is an easy fix.

**Comment by kalefranz** [comment]
I've set up a testbed for proxy servers and conda.  Before I did that, I had zero confidence in the state of conda with proxy servers.  I've been working with it all day though, and conda's use of proxy servers looks to be in decent shape.

That doesn't mean we still don't have problems.  There are N^M different ways to configure proxy servers.  I've spoken with @mcg1969, and it probably makes sense now for me to speak directly with clients represented by @stephenakearns to help debug this issue.

**Comment by kalefranz** [comment]
Let's try running 

    python -c "import requests; r=requests.head('https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz'); print(r)"

and see what shakes out

**Comment by mcg1969** [comment]
ok, will do

**Comment by kalefranz** [comment]
Also, I'll be curious to know the output of

    env | sort | grep _PROXY

and if there is any `~/.netrc` file

**Comment by mcg1969** [comment]
```
[mg796775@us1salxhpe0008 ~]$ python -c "import requests; r=requests.head('https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz'); print(r)"
<Response [200]>
```

**Comment by mcg1969** [comment]
```
$ env | sort | grep _PROXY
HTTP_PROXY=http://****:****@****:800
HTTPS_PROXY=http://****:****@****:800
NO_PROXY=localhost,127.0.0.1
```
No `~/.netrc`

**Comment by kalefranz** [comment]
Can we run

    conda skeleton cran ldavis
    conda build r-ldavis --debug

again just to make sure we're in the same state?  If we actually get a more informative stack trace, let me know and I'll come look at it.

**Comment by mcg1969** [comment]
will do

**Comment by mcg1969** [comment]
Nothing useful, I'm afraid:
```
Source cache directory is: /home/mg796775/conda-bld/src_cache
Downloading source to cache: LDAvis_0.3.2.tar.gz
Downloading https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz
BUILD START: r-ldavis-0.3.2-r3.3.2_0
    (actual version deferred until further download or env creation)
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Downloading https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download LDAvis_0.3.2.tar.gz
```

**Comment by kalefranz** [comment]
```
kfranz@0283:~/continuum/conda *4.3.x ❯ curl -I https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz
HTTP/1.1 200 OK
Date: Mon, 16 Oct 2017 21:03:06 GMT
Server: Apache/2.4.10 (Debian)
Last-Modified: Sat, 24 Oct 2015 06:21:20 GMT
ETag: "c161d-522d3bc883de1"
Accept-Ranges: bytes
Content-Length: 792093
Content-Type: application/x-gzip

kfranz@0283:~/continuum/conda *4.3.x ❯ curl -I https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz
HTTP/1.1 404 Not Found
Date: Mon, 16 Oct 2017 21:03:18 GMT
Server: Apache/2.4.10 (Debian)
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Content-Type: text/html; charset=utf-8
Content-Language: en
```

**Comment by kalefranz** [comment]
Why two different URLs?

**Comment by mcg1969** [comment]
Inserting debug prints in `conda.gateways.download.download` shows that the environment variables are still active when that function is called

**Comment by mcg1969** [comment]
Oh, that's very interesting

**Comment by mcg1969** [comment]
The recipe generated by `conda skeleton` has both:
```
source:
  fn: LDAvis_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/LDAvis_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_{{ version }}.tar.gz
```

**Comment by mcg1969** [comment]
But note that conda-build cannot find either one.

**Comment by kalefranz** [comment]
I believe we've long ago resolved this issue.
