### ISSUE TITLE
Openssl missing / incomplete in conda on WSL Ubuntu

### ISSUE THREAD

**Issue by theobarnhart-USGS** [conda/conda#6086]
Hi,

I was rebuilding my computing environment and found an issue in the latest miniconda distribution for linux. Here is the system I'm on. 

    Windows:
    Edition - Windows 10 Enterprise
    Version - 1607
    OS Build - 14393.1715

    Ubuntu on Windows:
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.5 LTS
    Release:        14.04
    Codename:       trusty

And the error I get when I try and use conda:

    $ conda create -n py36
    Fetching package metadata ...
    CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
    Elapsed: -
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /conda-forge/linux-64/repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",))',),)

When I revert to https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh this issue does not occur.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6435
