### ISSUE TITLE
Are packages supposed to have some kind of hash after the version number now?

### ISSUE THREAD

**Issue by ethankruse** [conda/conda#6087]
I've searched documentation and issues and I can't seem to find anything about this change. I've been hesitant to go through with my conda update --all because it seems to want to just replace all my packages with the same version number but with a hash at the end, e.g. 

    jupyter:                  1.0.0-py36_3          --> 1.0.0-py36h9896ce5_0      
    jupyter_client:           5.1.0-py36_0          --> 5.1.0-py36h614e9ea_0      
    jupyter_core:             4.3.0-py36_0          --> 4.3.0-py36h357a921_0 

It's somewhat intimidating to all of a sudden have conda wanting to update and replace every single package without any sort of warning or apparent documentation of a big change in how package labeling works. And no big new version number of for conda itself? Even though they all claim to be coming from the 'defaults' channel, it just looks untrustworthy.

Is this an intended change and if it is, is there some documentation explaining why or what it means?

**Comment by kalefranz** [comment]
CC @msarahan

**Comment by kalefranz** [comment]
> no big new version number of for conda itself

There haven't been any changes to conda that warrant a new version number beyond a patch release.  The big changes have really been to conda-build.

We have blog posts coming out soon.  CC @csoja

**Comment by msarahan** [comment]
explanation at https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/

**Comment by ethankruse** [comment]
Ah excellent, thank you. That explains it well.
