### ISSUE TITLE
ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::llvmlite-0.20.0-py36_0'. OSError(5, 'Input/output error')

### ISSUE THREAD

**Issue by ZheFrench** [conda/conda#6091]
Hey,

I'm on .
> Linux lakitu 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

Current conda install:

>                platform : linux-64
>           conda version : 4.3.14
>        conda is private : False
>       conda-env version : 4.3.14
>     conda-build version : not installed
>          python version : 3.6.0.final.0
>        requests version : 2.12.4
>        root environment : /home/luco/localLib/anaconda3  (writable)
>     default environment : /home/luco/localLib/anaconda3
>        envs directories : /home/luco/localLib/anaconda3/envs
>                           /home/luco/.conda/envs
>           package cache : /home/luco/localLib/anaconda3/pkgs
>                           /home/luco/.conda/pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : None
>            offline mode : False
>              user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Linux/3.16.0-4-amd64 debian/8.9 glibc/2.19
>                 UID:GID : 1009:1005
> 
> # conda environments:
> #
> root                  *  /home/luco/localLib/anaconda3
> 
> sys.version: 3.6.0 |Anaconda 4.3.1 (64-bit)| (default...
> sys.prefix: /home/luco/localLib/anaconda3
> sys.executable: /home/luco/localLib/anaconda3/bin/python
> conda location: /home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda
> conda-build: None
> conda-env: /home/luco/localLib/anaconda3/bin/conda-env
> conda-server: /home/luco/localLib/anaconda3/bin/conda-server
> user site dirs: 
> 
> CIO_TEST: <not set>
> CONDA_DEFAULT_ENV: <not set>
> CONDA_ENVS_PATH: <not set>
> LD_LIBRARY_PATH: <not set>
> PATH: /home/luco/soft/rMATS.3.2.5:/home/luco/localLib/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/bin/tophat-2.1.1.Linux_x86_64:/usr/src/RSEM:/usr/bin/ucsc_tools/:/usr/bin/BEDOPS:/usr/bin/sratoolkit.2.8.2/:/usr/bin/peakzilla/:/usr/bin/SICER/:/usr/bin/bwa/
> PYTHONHOME: <not set>
> PYTHONPATH: <not set>
> 
> License directories:
>     /home/luco/.continuum
>     /home/luco/localLib/anaconda3/licenses
> License files (license*.txt):
> Package/feature end dates:
> 

Trying to install numpy , I GET : 

> ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::llvmlite-0.20.0-py36_0'.
> OSError(5, 'Input/output error')
> Attempting to roll back.
> 
> 
> 
> OSError(5, 'Input/output error')

What is going on ? Can't install any package.

**Comment by ZheFrenchKitchen** [comment]
any idea ?

**Comment by kalefranz** [comment]
Is your disk full?  What is the command you're actually trying to run?

**Comment by kalefranz** [comment]
Please provide the output of that command, plus `-vv`

**Comment by ZheFrenchKitchen** [comment]
I did conda install numpy.


> INFO conda.core.link:_execute_actions(317): ===> LINKING PACKAGE: defaults::llvmlite-0.20.0-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
>   source=/home/luco/localLib/anaconda3/pkgs/llvmlite-0.20.0-py36_0
> 
> DEBUG conda.core.link:_execute_actions(328): Error in action #39 for pkg_idx #17 PrefixReplaceLinkAction(target_prefix='/home/luco/localLib/anaconda3', target_short_path='lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so', source_prefix='/home/luco/localLib/anaconda3/pkgs/llvmlite-0.20.0-py36_0', source_short_path='lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so', link_type=<LinkType.copy: 3>, _execute_successful=False, prefix_placeholder='/opt/miniconda/conda-bld/llvmlite_1504714633240/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_', file_mode=<FileMode.binary: 'binary'>, _verified=True)
> DEBUG conda.core.link:_execute_actions(329): Traceback (most recent call last):
>   File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 324, in _execute_actions
>   File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 270, in execute
>   File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 225, in execute
>   File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 233, in create_link
>   File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 207, in _do_copy
>   File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 252, in copy2
>     copystat(src, dst, follow_symlinks=follow_symlinks)
>   File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 219, in copystat
>     _copyxattr(src, dst, follow_symlinks=follow)
>   File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 159, in _copyxattr
>     os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
> OSError: [Errno 5] Input/output error: '/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so'
> 
> ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::llvmlite-0.20.0-py36_0'.
> OSError(5, 'Input/output error')
> Attempting to roll back.
> 
> INFO conda.core.link:_reverse_actions(359): ===> REVERSING PACKAGE LINK: defaults::llvmlite-0.20.0-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #17 from axn_idx #39
> INFO conda.core.link:_reverse_actions(359): ===> REVERSING PACKAGE LINK: defaults::anaconda-custom-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #16 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::statsmodels-0.6.1-np111py36_1 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #15 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::scipy-0.18.1-np111py36_1 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #14 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::scikit-learn-0.18.1-np111py36_1 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #13 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::scikit-image-0.12.3-np111py36_1 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #12 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::pytables-3.3.0-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #11 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::pandas-0.19.2-np111py36_1 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #10 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::numpy-1.11.3-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #9 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::numexpr-2.6.1-np111py36_2 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #8 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::numba-0.30.1-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #7 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::matplotlib-2.0.0-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #6 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::llvmlite-0.15.0-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #5 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::h5py-2.6.0-np111py36_2 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #4 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::conda-4.3.14-py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #3 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::bottleneck-1.2.0-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #2 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::astropy-1.3-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #1 from axn_idx #-1
> INFO conda.core.link:_reverse_actions(354): ===> REVERSING PACKAGE UNLINK: defaults::anaconda-4.3.1-np111py36_0 <===
>   prefix=/home/luco/localLib/anaconda3
> 
> DEBUG conda.core.link:_reverse_actions(360): reversing pkg_idx #0 from axn_idx #-1
> DEBUG conda.common.signals:signal_handler(47): de-registering handler for SIGBREAK
> DEBUG conda.common.signals:signal_handler(47): de-registering handler for SIGBREAK
> DEBUG conda.common.signals:signal_handler(47): de-registering handler for SIGBREAK
> DEBUG conda.common.signals:signal_handler(47): de-registering handler for SIGBREAK
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> INFO conda.common.io:captured(59): overtaking stderr and stdout
> DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/luco/localLib/anaconda3' using path '/home/luco/localLib/anaconda3/conda-meta/history'
> DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/luco/localLib/anaconda3' using path '/home/luco/localLib/anaconda3/conda-meta/history'
> INFO conda.common.io:captured(65): stderr and stdout yielding back
> Current conda install:
> 
>                platform : linux-64
>           conda version : 4.3.14
>        conda is private : False
>       conda-env version : 4.3.14
>     conda-build version : not installed
>          python version : 3.6.0.final.0
>        requests version : 2.12.4
>        root environment : /home/luco/localLib/anaconda3  (writable)
>     default environment : /home/luco/localLib/anaconda3
>        envs directories : /home/luco/localLib/anaconda3/envs
>                           /home/luco/.conda/envs
>           package cache : /home/luco/localLib/anaconda3/pkgs
>                           /home/luco/.conda/pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : None
>            offline mode : False
>              user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Linux/3.16.0-4-amd64 debian/8.9 glibc/2.19
>                 UID:GID : 1009:1005
> 
> 
> 
> `$ /home/luco/localLib/anaconda3/bin/conda install -vv numpy`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 324, in _execute_actions
>         action.execute()
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 270, in execute
>         super(PrefixReplaceLinkAction, self).execute()
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 225, in execute
>         force=context.force)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 233, in create_link
>         _do_copy(src, dst)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 207, in _do_copy
>         shutil.copy2(src, dst)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 252, in copy2
>         copystat(src, dst, follow_symlinks=follow_symlinks)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 219, in copystat
>         _copyxattr(src, dst, follow_symlinks=follow)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/shutil.py", line 159, in _copyxattr
>         os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
>     OSError: [Errno 5] Input/output error: '/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 279, in execute
>         pkg_data, actions)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 342, in _execute_actions
>         reverse_excs,
>     conda.CondaMultiError: [Errno 5] Input/output error: '/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so'
>     
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
>         exit_code = args.func(args, p)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
>         execute_actions(actions, index, verbose=not context.quiet)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 800, in execute_actions
>         execute_instructions(plan, index, verbose)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
>         cmd(state, arg)
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
>         txn.execute()
>       File "/home/luco/localLib/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 295, in execute
>         rollback_excs,
>     conda.CondaMultiError: [Errno 5] Input/output error: '/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so'
>     
> 
>

**Comment by kalefranz** [comment]
You have some type of file system permissions error for the path `/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so`.  I'm guessing that path already exists?  

Specifically, what's failing is `os.setxattr()` within python's `shutil.copy2()` function.

Does the following throw any type of error?

    python -c "open('/home/luco/localLib/anaconda3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so', 'a').close()"

**Comment by ZheFrenchKitchen** [comment]
No errors are returned .
I'm not root on this server. I tried a local install of anaconda in my home directory.
I have just done a fresh install of Anaconda3-4.3.1-Linux-x86_64.sh.
I created localib dir to install anaconda. The install was ok.
Then trying to install numpy, I got into troubles.

**Comment by ZheFrenchKitchen** [comment]
The dir should be ok for my user access.
drwxr-xr-x 20 luco bioinfo   21 Oct 11 16:49 anaconda3
