### ISSUE TITLE
Anaconda3 5.0.0 Installation fail

### ISSUE THREAD

**Issue by KirkLab** [conda/conda#6093]
When trying to install Anaconda3 5.0.0, the files all download, but the installation fails. An error pops up at the very end saying “Failed to create menus: abort retry ignore”. clicking retry does nothing. Since there are no menus, python cannot be opened. Even trying to open python or spyder from CMD, it appears as though anaconda doesnt officially install; computer does not recognize it.

**Comment by KirkLab** [comment]
![capture](https://user-images.githubusercontent.com/20971364/31337038-8f323114-acc7-11e7-91bb-8021b485d552.PNG)

**Comment by stahlous** [comment]
I have the same issue. I ran the Anaconda uninstaller to remove the old version, restarted my computer, and attempted twice now to installed 5.0.0 with the same result as @KirkLab. This is a Windows 10 machine with the 64-bit version.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8276
