### ISSUE TITLE
Installation failed - now cannot run conda commands

### ISSUE THREAD

**Issue by jordanlui** [conda/conda#6094]
Hello,
My conda installation failed (command prompted got crashed) and left several key files with changed filenames such as "python.exe.c~"

Now I cannot run conda commands or activate a secondary environment. I am renaming files one by one to see if I can my installation working again.
Is there any repair or roll-back script I can run? I'd prefer to not re-install Anaconda because I have OpenCV working in this environment - something that was difficult to initially configure. Any help is appreciated!

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/6418 and related issues.
