### ISSUE TITLE
Installation of python 3.3 and 3.4 fail due to pysocks dependency

### ISSUE THREAD

**Issue by bwohlberg** [conda/conda#6098]
Recent changes (this was working a few days ago) appear to have broken python 3.3 and 3.4:

```
$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
$ bash miniconda.sh -b -p $HOME/miniconda
$ export PATH="$HOME/miniconda/bin:$PATH"
$ conda update --yes -q conda
$ conda install --yes python=3.4
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pysocks -> python 3.6*
  - python 3.4*
```

Doing `conda info pysocks` indicates that there are no versions of the package available for python 3.3 and 3.4. It's not clear whether this issue is due to removal of these packages, or the introduction of a spurious dependency.

**Comment by kalefranz** [comment]
Output of `conda info`?

**Comment by kalefranz** [comment]
Oh nevermind. You're on linux.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6615
