### ISSUE TITLE
conda uninstall r-essential does not remove r-essential

### ISSUE THREAD

**Issue by jmbertoncelli** [conda/conda#6100]
when running R from within my virtual environment after using conda remove or uninstall  r-essential from my virtual environment  it is still R that has been installed within the virtual environment that is executed!

I did reboot just in case but still the same.

when I run R from outside the virtual environment this is what I get: /usr/lib64/bin/R for R_HOME
when I run R from within the virtual environment this is what I get: /root/miniconda/envs/lib/R/bin/R for R_HOME?????

Thanks in advance for your support.

JM

**Comment by kalefranz** [comment]
Can you provide the output of `conda info` and `conda list`?

**Comment by mingwandroid** [comment]
This is because r-essentials is a meta package. This is expected behaviour

**Comment by jji13** [comment]
you can try `conda uninstall r-base` . It will remove R and most of the R library in this Env.
