### ISSUE TITLE
Feature Request: relocated conda environments

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6104]
I propose adding an argument `--dest-dir` to `conda create`.

The argument specifies an alternative location of the environment other than the intended `prefix`.

Here is an example:
```
conda create -n env -p /opt/my-python-application --dest-dir=$TMP/buildroot/opt/my-python-applicatoin python=3.6
```
This will write the the conda environment to $TMP/buildroot/my-python-application, but when these files are copied to `/opt/my-python-application` it will run as is.

One potential use-case is to create linux distribution packages (e.g. RPM) of entire conda environments; can simplify for example to create Rolls of certain computing environments for RocksClusters.

The package builders usually require the installation script to have such a feature like autotools' `DESTDIR`, because the assumption is that the builder does not otherwise have access to the intended target directory of installation. For example, rpmbuild prefixes make install with DESTDIR to allow non-root building and automatic packaging of files from the install-root. (see https://fedoraproject.org/wiki/How_to_create_an_RPM_package#.25install_section )

In addition, we have another use case for deployment of conda environments on HPC systems, but it may be too specialized to be mentioned here.

I suppose this is a trivial change -- if hopefully it doesn't get into the way of the path-fixers.

**Comment by rainwoodman** [comment]
I am poking with a proposed patch.

**Comment by kalefranz** [comment]
I’m not opposed to this, at least at the moment, but I’m also not sure it’ll be a trivial change. I guess we’ll find out!

**Comment by kalefranz** [comment]
To give you some initial guidance, if it’s not already the case in the master branch, all prefix determination on what the target environment is for any run of conda should be coming from `context.target_prefix`. This is what we have to deconvolve, probably into a new property `context.dest_dir`. Under most cases they would be the same value, except when using a `—dest-dir` CLI flag. 

Then we have to find every place that `context.target_prefix is used, and also every place that value gets passed through to subordinate function/method calls, and make sure we don’t have to change the value to be the new `context.dest_dir`.

**Comment by rainwoodman** [comment]
Thanks. I've put up some demonstration of idea in #6162 along these lines. My initial audit is that all but in the function for updating prefix shall be changed to dest_dir. We shall probably move the discussion over there and close this issue.

**Comment by rainwoodman** [comment]
closing since the feature is already in.
