### ISSUE TITLE
I can't install conda forge netcdf4

### ISSUE THREAD

**Issue by nick96432** [conda/conda#6115]
`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'D:\Anaconda' using path 'D:\Anaconda\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'D:\Anaconda' using path 'D:\Anaconda\conda-meta\history'`
`Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : D:\Anaconda  (writable)
    default environment : D:\Anaconda
       envs directories : D:\Anaconda\envs
                          C:\Users\龍品瑞\AppData\Local\conda\conda\envs
                          C:\Users\龍品瑞\.conda\envs
          package cache : D:\Anaconda\pkgs
                          C:\Users\龍品瑞\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.14393
          administrator : False` 
`Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_remove.py", line 121, in execute
        raise CondaValueError('no package names supplied,\n'
    conda.exceptions.CondaValueError: no package names supplied`

**Comment by kalefranz** [comment]
What is the command you're actually trying to run?
