### ISSUE TITLE
Incompatible shell

### ISSUE THREAD

**Issue by ofek** [conda/conda#6137]
@kalefranz Also @scopatz @gforsyth @astronouth7303 might know

On Windows when using https://github.com/xonsh/xonsh (a shell written in Python), if you create a new env via e.g. `conda create --yes -p ./test python=3.6` and then try to delete that new env, Windows will error with:

![capture](https://user-images.githubusercontent.com/9677399/31367708-1ca8461c-ad47-11e7-9d0d-d7e6b40ecd15.PNG)

Here are the files that seem to be (though I think they aren't) in use:

```
Ofek@Ofek-PC ~\test $ fd                 
api-ms-win-core-file-l1-2-0.dll          
api-ms-win-core-file-l2-1-0.dll          
api-ms-win-core-localization-l1-2-0.dll  
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-synch-l1-2-0.dll         
api-ms-win-core-timezone-l1-1-0.dll      
api-ms-win-crt-conio-l1-1-0.dll          
api-ms-win-crt-convert-l1-1-0.dll        
api-ms-win-crt-environment-l1-1-0.dll    
api-ms-win-crt-filesystem-l1-1-0.dll     
api-ms-win-crt-heap-l1-1-0.dll           
api-ms-win-crt-locale-l1-1-0.dll         
api-ms-win-crt-math-l1-1-0.dll           
api-ms-win-crt-process-l1-1-0.dll        
api-ms-win-crt-runtime-l1-1-0.dll        
api-ms-win-crt-stdio-l1-1-0.dll          
api-ms-win-crt-string-l1-1-0.dll         
api-ms-win-crt-time-l1-1-0.dll           
ucrtbase.dll                             
vcruntime140.dll                         
```

**Comment by gforsyth** [comment]
Hey @ofek -- if you quit `xonsh` after env creation does the file lock still remain?

**Comment by ofek** [comment]
@gforsyth Nope, they can be deleted at that point.

**Comment by ofek** [comment]
Does anyone have an idea what is causing this?

**Comment by msarahan** [comment]
My guess would be hard linking.  Does it also fail if the python version is a totally different MSVC version?  For example, you have VC 14 here.  What if your env is py27, which is vc9?

Either way, conda should be able to delete environments no matter what, and this is a bug you're observing.

**Comment by ofek** [comment]
It's probably evident, but just to clarify `xonsh` is installed in the root Miniconda3 (Python 3.6). I don't know if that is useful information.

Ok so doing `conda create --yes -n test python=X.Y` then `conda remove --yes -n test --all` works fine for 2.7, 3.3, and 3.4. However the remove command hangs (file lock happens) for 3.5+.

@msarahan Does that give you more insight?
