### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Queue' while Fetching package Metadata

### ISSUE THREAD

**Issue by alonecoder1337** [conda/conda#6138]
Here is the traceback

> 
> Traceback (most recent call last):
>   File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
>     sys.exit(main())
>   File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
>     exit_code = args_func(args, p)
>   File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_fun
> c
>     exit_code = args.func(args, p)
>   File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in e
> xecute
>     install(args, parser, 'install')
>   File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in insta
> ll
>     index = common.get_index_trap(**index_args)
>   File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 622, in get_in
> dex_trap
>     return get_index(*args, **kwargs)
>   File "C:\Anaconda3\lib\site-packages\conda\api.py", line 26, in get_index
>     index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
>   File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 281, in fetch_index
> 
>     executor = concurrent.futures.ThreadPoolExecutor(10)
>   File "C:\Anaconda3\lib\site-packages\futures-3.0.5-py3.5.egg\concurrent\future
> s\thread.py", line 93, in __init__
>     self._work_queue = queue.Queue()
> AttributeError: 'function' object has no attribute 'Queue'

**Comment by kalefranz** [comment]
You're using a very old version of conda.  `conda update conda`
