### ISSUE TITLE
Version discrepancy

### ISSUE THREAD

**Issue by HenrikEckermann** [conda/conda#6139]
I wonder why anaconda uses such an old version of Rstudio. I noticed that this version was not even ready for the use with Retina display on the MacBook Pro. So I had to make an extra installation of Rstudio. 

Now about 4 months later and updating to new OS I thought that hopefully a newer version of Rstudio is implemented. But it is still version 1.0153.

I wonder: Am I doing something wrong and it is in fact possible to install the newest version form Anaconda Navigator? And if not, why is Rstudio not updated?

**Comment by mingwandroid** [comment]
Purely down to workload. We've had to rebuild the entire AD from scratch in the last 4 months and the R infrastructure is next on the list. I have been working on RStudio today actually.

**Comment by HenrikEckermann** [comment]
Thank you for working on this mingwandroid and letting me know!!!
