### ISSUE TITLE
Conda search cannot find noarch/repodata.json in channel

### ISSUE THREAD

**Issue by madarez** [conda/conda#6143]
Hi,

I intend to install the intel's distribution of python (intelpython3_full). But it seems that my conda cannot recognize the package in intel's channel. My search (conda search -c intel intelpython3_full) and install (conda install -c intel intelpython3_full) commands come up with the following error:

> `conda search -c intel intelpython3_full`
> Fetching package metadata ....
> WARNING: The remote server could not find the noarch directory for the
> requested channel with url: https://conda.anaconda.org/intel
> 
> It is possible you have given conda an invalid channel. Please double-check
> your conda configuration using `conda config --show`.
> 
> If the requested url is in fact a valid conda channel, please request that the
> channel administrator create `noarch/repodata.json` and associated
> `noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
> $ mkdir noarch
> $ echo '{}' > noarch/repodata.json
> $ bzip2 -k noarch/repodata.json
> .........
> 
> PackageNotFoundError: Packages missing in current channels:
>             
>   - intelpython3_full
> 
> We have searched for the packages in the following channels:
>             
>   - https://conda.anaconda.org/intel/osx-64
>   - https://conda.anaconda.org/intel/noarch
>   - https://repo.continuum.io/pkgs/main/osx-64
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/osx-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/osx-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/osx-64
>   - https://repo.continuum.io/pkgs/pro/noarch

I visited https://conda.anaconda.org/intel/osx-64, and I could see all of noarch/repodata.json, noarch/repodata.json.bz2 and intelpython3_full are there.

I'm running a Mac OS-X, with the most updated conda which is conda 4.3.29.

**Comment by kalefranz** [comment]
This is pretty strange. Is this error reproducible, or did it only happen once?

**Comment by madarez** [comment]
Oh, yeah. I tried it in different times and places. I get the same thing from both my home network and my university network. By the way, I have access and can download other regular packages like graphviz for example. The problem must be about channel commands. Because, I'm in the same boat as [this post's issue](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fconda%2Fconda%2Fissues%2F5717&sa=D&sntz=1&usg=AFQjCNFnkxVS2qsCSTvxzmJXsdyxexxAKg) too.

**Comment by kalefranz** [comment]
#5717 relates to the `--override-channels` flag specifically.  I don't see that in what you're doing here.

Have you ever configured any type of proxy servers on your machine?

**Comment by madarez** [comment]
Yeah, it was a side note implying that I got problems with other commands related to channels; hence there must be something about them.
I went under my wifi advanced network settings on my mac, the proxy tab has no protocol checked:
<img width="670" alt="screen shot 2017-10-12 at 9 33 56 am" src="https://user-images.githubusercontent.com/31979020/31498648-8cfd1f92-af30-11e7-902e-c7cbf8770bb6.png">
Would that answer your question?

**Comment by kalefranz** [comment]
I guess there's nothing there.  Do you have a `~/.netrc` file or any `*_PROXY` environment variables set (`env | sort`)?

**Comment by kalefranz** [comment]
Also, is this anything for anaconda.org, or just the `intel` channel?  What happens for `conda search -c conda-forge python` ?

**Comment by madarez** [comment]
I searched my PC now. No `.netrc` and no `*_PROXY` besides the following:

> ./usr/share/zsh/5.3/functions/**tcp_proxy**
> ~/anaconda3/pkgs/lazy-object-proxy-1.3.1-py36h2fbbe47_0/lib/python3.6/site-packages/**lazy_object_proxy**
> ~/anaconda3/pkgs/lazy-object-proxy-1.2.2-py36_0/lib/python3.6/site-packages/**lazy_object_proxy**
> ~/anaconda3/lib/python3.6/site-packages/**lazy_object_proxy**

As for your last question, the command `conda search -c conda-forge python`, actually returns a handful of results. The only problem I have is with when I add the channel intel. Despite that, [the intel channel](https://conda.anaconda.org/intel/osx-64) that is listed also in the error message looks fine, because it both has the json file and the package that I'm calling.

**Comment by kalefranz** [comment]
Definitely still stumped.  Can you provide the output of

    conda search -c intel intelpython3_full -vvv

**Comment by madarez** [comment]
As it shows a long block of text, I just put the output in three files for you as follows:
[stdout.txt](https://github.com/conda/conda/files/1380386/stdout.txt)
[stderr.txt](https://github.com/conda/conda/files/1380385/stderr.txt)
[stdout+stderr.txt](https://github.com/conda/conda/files/1380387/stdout.stderr.txt)

**Comment by kalefranz** [comment]
Try this

    CONDA_ADD_ANACONDA_TOKEN=no conda search -c intel intelpython3_full

I think we're seeing some new behavior from anaconda.org

**Comment by madarez** [comment]
That actually shows some results:
`CONDA_ADD_ANACONDA_TOKEN=no conda search -c intel intelpython3_full`
<img width="558" alt="screen shot 2017-10-12 at 5 00 38 pm" src="https://user-images.githubusercontent.com/31979020/31519001-f06c5852-af6e-11e7-92de-e6445c087bd5.png">
So, do you know what happened? And how I can use this channel?

**Comment by kalefranz** [comment]
Yeah, `anaconda whoami` should show that you're logged in to anaconda.org.  That is, you have a token stored on your system.  Conda recognizes this too, and adds the token for you when accessing anything on anaconda.org.  Your token isn't being accepted any longer, probably because it expired.  `anaconda logout` then `anaconda login` will probably fix the problem immediately for you.

Just recently, apparently, that anaconda.org API must have changed.  There now appears to be different behavior for expired tokens than there used to be.  I'm filing a ticket with the anaconda.org folks.

**Comment by madarez** [comment]
Thanks, you were right. It worked. Now it shows everything.

What is the default value of CONDA_ADD_ANACONDA_TOKEN? Is it yes or true?

**Comment by kalefranz** [comment]
`yes` and `true` are all equivalent in yaml, which is sort of the standard we use here.  All get cast to python `True`.

**Comment by kalefranz** [comment]
For more on conda configuration, a good blog post: https://www.anaconda.com/blog/developer-blog/conda-configuration-engine-power-users/
