### ISSUE TITLE
conda not working anymore

### ISSUE THREAD

**Issue by fhag** [conda/conda#6148]
Hi
I get the following error when I try running conda.
Python seems to work ok (see attachment).

[condaerror.txt](https://github.com/conda/conda/files/1376410/condaerror.txt)

As recommended I upload the message.
This happens after I did : pip install --upgrade google-api-python-client
I do not know if the error is related to this pip install.
Best regards
Gérard

**Comment by kalefranz** [comment]
In this case, pip has manipulated your environment to incompatible `requests` and `cryptography` versions.  `pip install -U requests[security]` may allow pip to fix it for you.
