### ISSUE TITLE
Problem with solution given in  #6096

### ISSUE THREAD

**Issue by ghoetker** [conda/conda#6150]
Attempting to apply solution given in  #6096 on MacOS unsuccessfully

The command given was

```
# in the command below, set PATH_TO_ENVIRONMENT yourself
sed -i '' -E 's|("timestamp": [0-9]+)\.|\1|' /PATH_TO_ENVIRONMENT/conda-meta/*.json
```

`conda info --envs` answers

```
# conda environments:
#
root                  *  /Users/ghoetker/anaconda
```

Substituting that for PATH_TO_ENVIRONMENT yielded command
```
gsed -i '' -E 's|("timestamp": [0-9]+)\.|\1|' /Users/ghoetker/anaconda/conda-meta/*.json
```
which gave the error

`gsed: can't read s|("timestamp": [0-9]+)\.|\1|: No such file or directory`

I'm guessing the problem is in the path I provided, but my `envs` directory is empty, so I don't know what else it would be.

Thank you.

**Comment by kalefranz** [comment]
The solution given for mac used `sed`, not `gsed`.  So

    sed -i '' -E 's|("timestamp": [0-9]+)\.|\1|' /Users/ghoetker/anaconda/conda-meta/*.json

If you're using gnu sed, use the solution given for Linux.

**Comment by ghoetker** [comment]
Thank you and apologies for that error. Things worked fine when I actually, you know, followed the directions...
