### ISSUE TITLE
Anaconda 2 do not openning

### ISSUE THREAD

**Issue by marcossecca** [conda/conda#6151]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : D:\Users\mppse\AppData\Local\Continuum\anaconda2  (wri
table)
    default environment : D:\Users\mppse\AppData\Local\Continuum\anaconda2
       envs directories : D:\Users\mppse\AppData\Local\Continuum\anaconda2\envs
                          D:\Users\mppse\AppData\Local\conda\conda\envs
                          D:\Users\mppse\.conda\envs
          package cache : D:\Users\mppse\AppData\Local\Continuum\anaconda2\pkgs
                          D:\Users\mppse\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : D:\Users\mppse\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False

`$ D:\Users\mppse\AppData\Local\Continuum\anaconda2\Scripts\conda ..checkenv cmd
.exe D:\Users\mppse\AppData\Local\Continuum\anaconda2`

    Traceback (most recent call last):
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\cli\main.py", line 171, in main
        activate.main()
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\cli\activate.py", line 181, in main
        from ..install import symlink_conda
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\install.py", line 37, in <module>
        from .core.package_cache import rm_fetched  # NOQA
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\core\package_cache.py", line 9, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\core\path_actions.py", line 33, in <module>
        from ..gateways.download import download
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
onda\gateways\download.py", line 10, in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchem
a, SSLError
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\r
equests\__init__.py", line 84, in <module>
        from urllib3.contrib import pyopenssl
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\u
rllib3\contrib\pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\O
penSSL\__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\O
penSSL\crypto.py", line 12, in <module>
        from cryptography import x509
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
ryptography\x509\__init__.py", line 9, in <module>
        from cryptography.x509.base import (
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
ryptography\x509\base.py", line 16, in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\c
ryptography\x509\extensions.py", line 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\a
sn1crypto\keys.py", line 22, in <module>
        from ._elliptic_curve import (
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\a
sn1crypto\_elliptic_curve.py", line 51, in <module>
        from ._int import inverse_mod
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\a
sn1crypto\_int.py", line 56, in <module>
        from ._perf._big_num_ctypes import libcrypto
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\site-packages\a
sn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\ctypes\util.py"
, line 53, in find_library
        fname = os.path.join(directory, name)
      File "D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\ntpath.py", lin
e 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 17: ord
inal not in range(128)

**Comment by yunliangc** [comment]
Problem of setting environment variables

**Comment by marcossecca** [comment]
How can I set these environment variables?

**Comment by mingwandroid** [comment]
You need to remove any non-ASCII from `PATH`. https://www.java.com/en/download/help/path.xml

**Comment by yunliangc** [comment]
![environment variables](https://user-images.githubusercontent.com/32910797/31775067-1f1e5302-b51a-11e7-99b9-5b17088b5faf.png)
the Path of System variable  maybe set too long or wrong， try too check it

**Comment by yunliangc** [comment]
the Path of System variable too long maybe the reason of UnicodeDecodeError

**Comment by yunliangc** [comment]
I came up with the same problem and solved it, and that's the solution

**Comment by yunliangc** [comment]
Maybe your installation path is too long 
D:\Users\mppse\AppData\Local\Continuum\anaconda2\lib\ntpath.py
