### ISSUE TITLE
Interesting RPATH of gcc libraries.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6161]
Hi,

It appears that with a fresh mini-conda installer after installing libgcc_ng we see these:

```
objdump: /home/yfeng1/anaconda3/mini/lib/libgcc_s.so: File format not recognized
/home/yfeng1/anaconda3/mini/lib/libgcc_s.so.1
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libgomp.so
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libgomp.so.1
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libgomp.so.1.0.0
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libitm.so
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libitm.so.1
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
/home/yfeng1/anaconda3/mini/lib/libitm.so.1.0.0
  RPATH                /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib
```

Are these supposed not to be changed.

**Comment by mingwandroid** [comment]
No, they aren't. Not an issue.

**Comment by mingwandroid** [comment]
To explain, the libraries that are `DT_NEEDED` by all of these compiler runtime libraries are system libraries, meant to be resolved from `/usr/lib` (or `/usr/lib64`) so we do not want any library in `${PREFIX}/lib` getting used.

We could I guess, remove these entries, but relocating them is not the right thing to do (and it is costly, it prevents hardlinks from working).

**Comment by rainwoodman** [comment]
Sorry I am still puzzled:

- You mean by setting a non-existing RPATH these libraries are not used by ld.so at runtime? I thought the RPATH entry only affects where to look for dependency shared objects.

- If they are not even supposed to be used, then why are they installed with the libgcc_ng package? Do you perhaps mean the libgcc_ng package is not supposed to be installed (ng == no good?)

**Comment by mingwandroid** [comment]
No I do not mean that. These libraries are good and used. The libraries they need (DT_NEEDED) are system libraries and we deliberately do not provide system libraries).

ng comes from the fact they are built by crosstool-ng and is added to allow people to run applications linked against our old libgcc packages in the same env as ones linking to these new ones.

**Comment by rainwoodman** [comment]
Thanks. Now I see how this works. It sounds like this may actually break the installation on msarahan's computer? 

Perhaps use a more meaningful path than msarahan's home directory to avoid the confusion; but that may need some infrastructure change in conda to support.
