### ISSUE TITLE
Can not create python virtual environment using venv module

### ISSUE THREAD

**Issue by krysros** [conda/conda#6171]
Can not create python virtual environment using venv module.

    (C:\Users\kryst\Miniconda3) C:\Users\kryst\Documents\NewProject>python --version
    Python 3.6.3 :: Anaconda, Inc.
    
    (C:\Users\kryst\Miniconda3) C:\Users\kryst\Documents\NewProject>python -m venv env
    Error: Command '['C:\\Users\\kryst\\Documents\\NewProject\\env\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
    
    (C:\Users\kryst\Miniconda3) C:\Users\kryst\Documents\NewProject>

**Comment by fortran-favors-the-old** [comment]
Hi @krysros ,

Since this problem appears to be with the Anaconda distribution itself and not `conda`, I opened ContinuumIO/anaconda-issues#6917 .  Hopefully this issue gets more attention there.

**Comment by msarahan** [comment]
Yes, anaconda-issues is a better place.
