### ISSUE TITLE
Error message saying that openssl is missing

### ISSUE THREAD

**Issue by vhriebes** [conda/conda#6177]
I'm trying to create a new python 2.7 environment with this command:
conda env create -f python27env.yml
This is the error message I am getting:

ResolvePackageNotFound:

openssl 1.0.2l 0
Then I tried installing openssl with this command:
conda install openssl

But the same error message is still showing. How can I fix this? Thank you for your help!

**Comment by kalefranz** [comment]
Please include the output of `conda info` and the contents of `python27env.yml`

**Comment by vhriebes** [comment]
Contents of python27env.yml:

name: catalyst
channels:
- statiskit
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- coverage=4.4.1=py27_0
- nose=1.3.7=py27_1
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pip=9.0.1=py27_1
- python=2.7.13=0
- pyyaml=3.12=py27_0
- readline=6.2=2
- setuptools=36.4.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.11=0
- libdev=1.0.0=py27_0
- python-dev=1.0.0=py27_0
- python-scons=3.0.0=py27_0
- pip:
  - alembic==0.9.5
  - backports.shutil-get-terminal-size==1.0.0
  - bcolz==0.12.1
  - bottleneck==1.2.1
  - chardet==3.0.4
  - click==6.7
  - contextlib2==0.5.5
  - cycler==0.10.0
  - cyordereddict==1.0.0
  - cython==0.26.1
  - decorator==4.1.2
  - empyrical==0.2.1
  - enigma-catalyst>=0.2.dev2
  - enum34==1.1.6
  - functools32==3.2.3.post2
  - idna==2.6
  - intervaltree==2.1.0
  - ipdb==0.10.3
  - ipdbplugin==1.4.5
  - ipython==5.5.0
  - ipython-genutils==0.2.0
  - logbook==1.1.0
  - lru-dict==1.1.6
  - mako==1.0.7
  - markupsafe==1.0
  - matplotlib==2.0.2
  - multipledispatch==0.4.9
  - networkx==1.11
  - numexpr==2.6.4
  - numpy==1.13.1
  - pandas==0.19.2
  - pandas-datareader==0.5.0
  - pathlib2==2.3.0
  - patsy==0.4.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - pytz==2017.2
  - requests==2.18.4
  - requests-file==1.4.2
  - requests-ftp==0.3.1
  - scandir==1.5
  - scipy==0.19.1
  - scons==3.0.0a20170821
  - simplegeneric==0.8.1
  - sortedcontainers==1.5.7
  - sqlalchemy==1.1.14
  - statsmodels==0.8.0
  - subprocess32==3.2.7
  - tables==3.4.2
  - toolz==0.8.2
  - traitlets==4.3.2
  - urllib3==1.22
  - wcwidth==0.1.7

Output from conda info:
C:\Users\Valentin\Desktop>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 2.0.2
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : C:\Users\Valentin\Anaconda3  (writable)
    default environment : C:\Users\Valentin\Anaconda3
       envs directories : C:\Users\Valentin\Anaconda3\envs
                          C:\Users\Valentin\AppData\Local\conda\conda\envs
                          C:\Users\Valentin\.conda\envs
          package cache : C:\Users\Valentin\Anaconda3\pkgs
                          C:\Users\Valentin\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.5.3 Windows/10 Windows/10.0.14393
          administrator : False

**Comment by kalefranz** [comment]
It's possible that yml file wasn't created for windows.  Try

```
name: catalyst
channels:
- statiskit
- defaults
dependencies:
- certifi=2016.2.28
- coverage=4.4.1
- nose=1.3.7
- openssl=1.0.2l
- path.py=10.3.1
- pip=9.0.1
- python=2.7.13
- pyyaml=3.12
- readline=6.2
- setuptools=36.4.0
- six=1.10.0
- sqlite=3.13.0
- tk=8.5.18
- wheel=0.29.0
- yaml=0.1.6
- zlib=1.2.11
- libdev=1.0.0
- python-dev=1.0.0
- python-scons=3.0.0
- pip:
  - alembic==0.9.5
  - backports.shutil-get-terminal-size==1.0.0
  - bcolz==0.12.1
  - bottleneck==1.2.1
  - chardet==3.0.4
  - click==6.7
  - contextlib2==0.5.5
  - cycler==0.10.0
  - cyordereddict==1.0.0
  - cython==0.26.1
  - decorator==4.1.2
  - empyrical==0.2.1
  - enigma-catalyst>=0.2.dev2
  - enum34==1.1.6
  - functools32==3.2.3.post2
  - idna==2.6
  - intervaltree==2.1.0
  - ipdb==0.10.3
  - ipdbplugin==1.4.5
  - ipython==5.5.0
  - ipython-genutils==0.2.0
  - logbook==1.1.0
  - lru-dict==1.1.6
  - mako==1.0.7
  - markupsafe==1.0
  - matplotlib==2.0.2
  - multipledispatch==0.4.9
  - networkx==1.11
  - numexpr==2.6.4
  - numpy==1.13.1
  - pandas==0.19.2
  - pandas-datareader==0.5.0
  - pathlib2==2.3.0
  - patsy==0.4.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - pytz==2017.2
  - requests==2.18.4
  - requests-file==1.4.2
  - requests-ftp==0.3.1
  - scandir==1.5
  - scipy==0.19.1
  - scons==3.0.0a20170821
  - simplegeneric==0.8.1
  - sortedcontainers==1.5.7
  - sqlalchemy==1.1.14
  - statsmodels==0.8.0
  - subprocess32==3.2.7
  - tables==3.4.2
  - toolz==0.8.2
  - traitlets==4.3.2
  - urllib3==1.22
  - wcwidth==0.1.7
```

**Comment by vhriebes** [comment]
I created a new yml file with that and got this error message:

C:\Users\Valentin\Desktop>conda env create -f python2.7env.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...............

ResolvePackageNotFound:
  - readline 6.2*

**Comment by kalefranz** [comment]
So remove `readline` from the list and tray again...
