### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by mayerbar** [conda/conda#6178]
I am pasting the error output as given in the command prompt

C:\Windows\system32>conda install --file "C:\Users\****\Downloads\opencv\build\python\2.7\x64\cv2.pyd"
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\****\AppData\Local\conda\conda\envs
                          C:\Users\****\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\****\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\****\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : True

`$ C:\ProgramData\Anaconda3\Scripts\conda install --file C:\Users\****\Downloads\opencv\build\python\2.7\x64\cv2.pyd`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 190, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\common.py", line 551, in specs_from_url
        for line in open(path):
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>

**Comment by mingwandroid** [comment]
Does `****` contain any non-ASCII characters?

**Comment by mayerbar** [comment]
@mingwandroid Thanks for your reply
No, it doesn't. It's just a plain four-capital-letter-in-the-English-alphabet name

**Comment by kalefranz** [comment]
As I understand the information here, you're trying to execute

    C:\ProgramData\Anaconda3\Scripts\conda install --file C:\Users\****\Downloads\opencv\build\python\2.7\x64\cv2.pyd

That's not what the `--file` flag is designed to be used for.  Conda has no support for "installing" an individual pyd file like that.
