### ISSUE TITLE
Problem on installation on reproducibility of the package in the same machine

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [conda/conda#6187]
I create two environment where I try to use the same package with thee same version..
The second version dosen't work.
```
(rna_test2) [riva@ilmn-qm ~]$ conda list |grep multiqc
multiqc                   0.9a                     py35_0    bioconda
(rna_test2) [riva@ilmn-qm ~]$ multiqc --version
multiqc, version 0.9.dev0
(rna_test2) [riva@ilmn-qm ~]$ 


Here not works. The version are the same:

```
(trial_py) [riva@ilmn-qm rna_test2]$ conda list|grep multiqc
multiqc                   0.9a                     py35_0    bioconda
(trial_py) [riva@ilmn-qm rna_test2]$ 
home/riva/miniconda2/envs/trial_py/bin/python: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by /home/riva/miniconda2/envs/trial_py/bin/../lib/libpython3.5m.so.1.0)
(trial_py) [riva@ilmn-qm rna_test2]$ 

```

What is wrong in this.?

```
(rna_test2) [riva@ilmn-qm ~]$ cat rna.conda.txt 
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/riva/miniconda2  (writable)
    default environment : /home/riva/miniconda2/envs/rna_test2
       envs directories : /home/riva/miniconda2/envs
                          /home/riva/.conda/envs
          package cache : /home/riva/miniconda2/pkgs
                          /home/riva/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/riva/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/2.7.13 Linux/2.6.18-308.1.1.el5 Red Hat Enterprise Linux Server/5.5 glibc/2.5    
                UID:GID : 1003:1004
```

It is the same info list of conda..

**Comment by kalefranz** [comment]
The package you're having problems with was built for something newer than RHEL 5.  The community has moved on from RHEL / CentOS 5, given that end of security support was March 31, 2017.

**Comment by bioinfo-dirty-jobs** [comment]
@kalefranz 
There is no a problem of RHEl 5.5 because it works on that system. I ask help because it is not repoducible this. I suppose the command need to be reproducibile..

**Comment by ewels** [comment]
Hi @kalefranz,

Are you asking about the fact that the version outputs from conda and multiqc are different? That's not a big problem - they're set in separate places (and often by separate people). Also, v0.9 is quite old so I'd recommend updating to v1.2 (or v1.3 which will be out in a few days).

For future problems, I'd recommend asking at https://github.com/bioconda/bioconda-recipes where this is packaged. Alternatively, at https://github.com/ewels/MultiQC

Phil

**Comment by mingwandroid** [comment]
Kale wasn't asking anything here, he was stating that `conda` and the `Anaconda Distribution` are no long compatible with RHEL5. We target RHEL6/CentOS6 as the baseline Linux distro now-a-days.
