### ISSUE TITLE
conda install files should support `-r FILE` for includes

### ISSUE THREAD

**Issue by singingwolfboy** [conda/conda#619]
`pip` supports using the `-r` argument to read from a requirements file. Within a requirements file, you can also use `-r FILE` to recursively include the contents of the FILE you've listed. `conda` already supports `--file` to read from a requirements file, but for compatibility with `pip`, these requirements files should allow recursive includes with the same syntax that `pip` expects.

For example, if you have `file1.txt` with the content

```
-r file2.txt
pkg1==1.2.3
```

and you have `file2.txt` with the content

```
pkg2==3.2.1
```

Then I would expect running `conda install --file file1.txt` to result in conda installing both `pkg1` and `pkg2` at the appropriate versions. Instead, I get the error message `Error: Invalid character ' ' in package name: '-r file2.txt'`

**Comment by jfinkels** [comment]
This remains an issue in conda version 4.0.8:

> Error: could not parse '-r requirements.txt' in: requirements-test.txt

This is important because in my project I would like to be able to support Travis builds using both pip and conda. Having separate requirements files for each is silly and unmaintainable.

**Comment by jfinkels** [comment]
A start to fixing this would be to add some code in the main loop of the `specs_from_url()` function in https://github.com/conda/conda/blob/master/conda/cli/common.py that checks whether a line starts with `-r`, and if so, call the function recursively.
