### ISSUE TITLE
How can I get parmap for python 36 and Anaconda3?

### ISSUE THREAD

**Issue by arash-mham** [conda/conda#6190]
want to install parmap in anaconda3 for windows 64. If I try conda install -c marufr parmap, I receive an error reporting a conflict between python 2.7 and python 3.6 which is the current python version of my anaconda3. Is there any way to solve this issue? This is the error that I am receiving:

UnsatisfiableError: The following specifications were found to be in conflict:

-parmap->python 2.7*
-python 3.6*

**Comment by kalefranz** [comment]
Search on anaconda.org.  Otherwise, you can contribute yourself via conda-forge.
