### ISSUE TITLE
BUGs in samtools tview installed with bioconda

### ISSUE THREAD

**Issue by shexuan** [conda/conda#6191]
Samtools installed with conda cannot correctly show the mapping results and its subcommand in samtools are completely changed,  reinstalled with source code solved this problem.

**Comment by dpryan79** [comment]
Stated properly, `samtools tview` isn't using curses.

**Comment by kalefranz** [comment]
Closing, per https://github.com/samtools/samtools/issues/728#issuecomment-337833046.  Thanks @dpryan79
