### ISSUE TITLE
deprecate 'conda help' in favor of --help CLI flag

### ISSUE THREAD

**Issue by jurekK** [conda/conda#6192]
With the install on Windows 10:

  _platform : win-64   conda version : 4.3.30
  conda is private : False   conda-env version : 4.3.30
  conda-build version : 3.0.22   python version : 3.6.3.final.0
  requests version : 2.18.4     root environment : C:\Anaconda3  (writable)_

the command:  `conda help install`  (or other similar, say, conda help create, etc.) produces the message

`C:\Anaconda3\python.exe: can't open file 'C:\Anaconda3\Scripts\conda': [Errno 2] No such file or directory`

This syntax works under Linux (Ubuntu), but of course, there is no just "conda" file in Windows Anaconda Scripts.

**Comment by oarodriguez** [comment]
I also noticed this issue today. It is very annoying, hope it gets solved soon.

**Comment by kalefranz** [comment]
Cannot reproduce in conda 4.4.

**Comment by kalefranz** [comment]
I don't see much reason to have `conda help` as a command.  Help is extensively supported through the `--help` CLI flag.
