### ISSUE TITLE
conda only updates itself in the root environment

### ISSUE THREAD

**Issue by jbednar** [conda/conda#6194]
I was listening to a presentation about conda a couple of days ago where it was mentioned that conda aggressively auto-updates itself. Aggressive auto-updates can be problematic, because they can result in the quick spread of a buggy release that is no longer able to update itself, which has happened to me and co-workers in the past.  But in general they are a good thing, because they can help make sure that the installed user base is (a) not using outdated versions where problems were fixed long ago, and (b) are using a similar set of versions so that we don't have to reason about the effects of all possible version combinations.  

However, the main benefits of aggressively auto-updating only accrue if all or nearly all installations auto-update, which does not appear to be the case.  Right now, it looks to me like auto-updates happen only when people regularly use the root environment.  In my own workflows, I haven't installed anything in the root environment in many months; I always work on one of a number of more specialized environments instead.  I didn't even realize this until recently, when I ran into a bug fixed several months ago in conda, and which I expected not to apply to me.  I eventually fixed it by switching to the root environment and running ``conda update conda``, which was fine, but it was not at all clear that this would be needed.  I imagine other users who don't use the root environment may encounter similar issues.  I don't think conda is installed in any environment other than root, but maybe the other environments could warn on a ``conda install`` command if conda itself is more than a month or so out of date?

**Comment by jbednar** [comment]
This problem just reared its head in practice:  as of conda 4.3.27, new packages are going into ``https://repo.continuum.io/pkgs/main/``, and so when I tried to install packages in any environment, I was getting out of date packages.  After ``conda update conda`` to upgrade 4.3.25, it works fine, but I only knew to do that (given that my conda version wasn't even very old) because of an in-person suggestion from Michael Grant.  This seems like something that will cause lots of confusion for any users who habitually use sub-environments.

**Comment by kalefranz** [comment]
Related issue: https://github.com/conda/conda/issues/6232
