### ISSUE TITLE
Removal of orphan dependencies

### ISSUE THREAD

**Issue by trentoliphant** [conda/conda#62]
The Conda UI (Launcher) will keep track of which packages were selected by the user to be installed to a specific environment - versus which are installed because they are a dependency.  It would be nice to have a command that allows some way to remove the dependencies of a package when a package is removed - provided they aren't needed by other packages.

I can see one of two ways of accomplishing this. 

1) An arg (--remove-dependencies or something) that is passed in when a package is removed to have it also remove any dependencies (that aren't also dependencies of other packages).

2) A separate command that removes everything except for packages (and their dependencies) that are sent into the command.

**Comment by ajmazurie** [comment]
I second this; I was looking right this morning at cleaning up my conda environment and could not figure out how to remove 'orphan' dependencies.

**Comment by kalefranz** [comment]
Conda 4.4 will include a `--prune` flag.

**Comment by kirk86** [comment]
Why is this closed. I don't see it as resolved issue. I have conda 4.5.10 and still there's no `--prune` or anything similar to be found.

I had mpi4py installed and mpich2. After uninstalling both of those packages here's what's left:

```
/miniconda3/envs/rl/lib/libmpich.a
/miniconda3/envs/rl/lib/libmpich.so
/miniconda3/envs/rl/lib/libmpich.so.3.3
/miniconda3/envs/rl/lib/libmpichcxx.a
miniconda3/envs/rl/lib/libmpichcxx.so
/miniconda3/envs/rl/lib/libmpichcxx.so.3
/miniconda3/envs/rl/lib/libmpichcxx.so.3.3
miniconda3/envs/rl/lib/libmpichf90.a
/miniconda3/envs/rl/lib/libmpichf90.so
miniconda3/envs/rl/lib/libmpichf90.so.3
/miniconda3/envs/rl/lib/libmpichf90.so.3.3
miniconda3/envs/rl/lib/python3.6/site-packages/mpmath/libmp/libmpi.py
/miniconda3/envs/rl/lib/python3.6/site-packages/mpmath/libmp/__pycache__/libmpi.cpython-36.pyc
miniconda3/pkgs/mpi4py-2.0.0-py36_2/lib/python3.6/site-packages/mpi4py/libmpi.pxd
/miniconda3/pkgs/mpi4py-2.0.0-py36_2/lib/python3.6/site-packages/mpi4py/include/mpi4py/libmpi.pxd
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpich.a
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpich.so
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpich.so.3
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpich.so.3.3
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichcxx.a
miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichcxx.so
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichcxx.so.3
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichcxx.so.3.3
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichf90.a
miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichf90.so
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichf90.so.3
/miniconda3/pkgs/mpich2-1.4.1p1-0/lib/libmpichf90.so.3.3
/miniconda3/pkgs/mpmath-1.0.0-py36_2/lib/python3.6/site-packages/mpmath/libmp/libmpi.py
/miniconda3/pkgs/mpmath-1.0.0-py36_2/lib/python3.6/site-packages/mpmath/libmp/__pycache__/libmpi.cpython-36.pyc
/miniconda3/pkgs/mpmath-1.0.0-py36hfeacd6b_2/lib/python3.6/site-packages/mpmath/libmp/libmpi.py
miniconda3/pkgs/mpmath-1.0.0-py36hfeacd6b_2/lib/python3.6/site-packages/mpmath/libmp/__pycache__/libmpi.cpython-36.pyc
```

**Comment by piw** [comment]
> Why is this closed. I don't see it as resolved issue. I have conda 4.5.10 and still there's no `--prune` or anything similar to be found.
> 

(using conda 4.6 here) The `--prune` option is part of the `update` command. This will find all the packages to be removed:
```
conda update --prune --all
```
