### ISSUE TITLE
Ipython with Python.app distributed with conda will not parse sys_version correctly.

### ISSUE THREAD

**Issue by dangom** [conda/conda#6209]
Steps to reproduce:

1. Install conda3
2. `conda install python.app ipython`
3. `pythonw -m IPython`

Will raise a ValueError (from _anaconda3/lib/python3.6/platform.py_) saying it failed to parse Cpython sys.version.
Here's the offending code:

```
    else:
        # CPython
        match = _sys_version_parser.match(sys_version)
        if match is None:
            raise ValueError(
                'failed to parse CPython sys.version: %s' %
                repr(sys_version))
```
That's because `pythonw`'s sys.version is:

> "'3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) \\n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'"

My workaround was to modify the match copying the sys_version of python3, as in:
```
    else:
        # CPython
        match = _sys_version_parser.match(sys_version) or _sys_version_parser.match('3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 19:18:17) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]')
        if match is None:
            raise ValueError(
                'failed to parse CPython sys.version: %s' %
                repr(sys_version))
```

Don't know what is the correct place to report this, but I figured here.
Thanks!

**Comment by mingwandroid** [comment]
conda-forge needs to package pythonw (or python.app) here. This should be reported at conda-forge.
