### ISSUE TITLE
tkinter fonts

### ISSUE THREAD

**Issue by marcogullieuszik** [conda/conda#6213]
I have a simple Tk GUI (using ttk) that looks really bad when I use the conda python.
the fonts are really bad.
On the same computer, it looks ok if I use the system python.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6833

**Comment by mingwandroid** [comment]
Which computer are you using? `conda info` and `conda list --show-channel-urls` please.

Two representative screenshots would also be useful here.

**Comment by marcogullieuszik** [comment]
![tkk](https://user-images.githubusercontent.com/2780500/31942805-dbbeea9e-b8c6-11e7-85f1-33858838b458.png)

In the upper window there is the output of python conda, in the lower one the system python

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/marco/miniconda3  (writable)
    default environment : /home/marco/miniconda3
       envs directories : /home/marco/miniconda3/envs
                          /home/marco/.conda/envs
          package cache : /home/marco/miniconda3/pkgs
                          /home/marco/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.8.0-58-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

#############
#
asn1crypto                0.22.0           py36h265ca7c_1    defaults
astropy                   2.0.2            py36ha51211e_4    defaults
astroquery                0.3.5                    py36_2    astropy
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
bleach                    2.0.0            py36h688b259_0    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.7.27.1      py36h8b7b77e_0    defaults
cffi                      1.10.0           py36had8d393_1    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
conda                     4.3.30           py36h5d9f9f4_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.0.3            py36ha225213_1    defaults
cycler                    0.10.0           py36h93f1223_0    defaults
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.1.2            py36hd076ac8_0    defaults
entrypoints               0.2.3            py36h1aec115_2    defaults
expat                     2.2.4                hc00ebd1_1    defaults
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  h52ed37b_0    defaults
glib                      2.53.6               hc861d11_1    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
html5lib                  0.999999999      py36h2cfc398_0    defaults
icu                       58.2                 h211956c_0    defaults
idna                      2.6              py36h82fb2a8_1    defaults
intel-openmp              2018.0.0             h15fc484_7    defaults
ipykernel                 4.6.1            py36hbf841aa_0    defaults
ipython                   6.1.0            py36hc72a948_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.0.0            py36h7b55c3a_0    defaults
jedi                      0.10.2           py36h552def0_0    defaults
jinja2                    2.9.6            py36h489bce4_1    defaults
jpeg                      9b                   habf39ab_1    defaults
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0            py36h9896ce5_0    defaults
jupyter_client            5.1.0            py36h614e9ea_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.3.0            py36h357a921_0    defaults
keyring                   10.4.0           py36h4fce1c9_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran               3.0.0                         1    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libiconv                  1.15                 h63c8f33_5    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libxcb                    1.12                 h84ff03f_3    defaults
libxml2                   2.9.4                h6b072ca_5    defaults
libxslt                   1.1.29               hcf9102b_5    defaults
lxml                      4.1.0            py36h5b66e50_0    defaults
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                2.1.0            py36hba5de38_0    defaults
mistune                   0.7.4            py36hbab8784_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
ncurses                   6.0                  h06874d7_1    defaults
notebook                  5.0.0            py36h0b20546_2    defaults
numpy                     1.13.3           py36ha12f23b_0    defaults
openssl                   1.0.2l               h077ae2c_5    defaults
packaging                 16.8             py36ha668100_1    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
path.py                   10.3.1           py36he0c6f6d_0    defaults
pcre                      8.41                 hc71a17e_0    defaults
pexpect                   4.2.1            py36h3b9d41b_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pip                       9.0.1            py36h8ec8b28_3    defaults
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.4.34           py36h0712aa3_1    defaults
pycosat                   0.6.2            py36h1a0ea17_1    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pygments                  2.2.0            py36h0d3125c_0    defaults
pyopenssl                 17.2.0           py36h5cc804b_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pyqt                      5.6.0            py36h0386399_5    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytest                    3.2.1            py36h11ad3bb_1    defaults
python                    3.6.3                hc9025b9_1    defaults
python-dateutil           2.6.1            py36h88d3b88_1    defaults
pytz                      2017.2           py36hc2ccc2a_1    defaults
pyzmq                     16.0.2           py36h3b0cf96_2    defaults
qt                        5.6.2               h974d657_12    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
scipy                     0.19.1           py36h9976243_3    defaults
setuptools                36.5.0           py36he42e2e1_0    defaults
simplegeneric             0.8.1            py36h2cb9092_0    defaults
simplejson                3.11.1                   py36_0    defaults
sip                       4.18.1           py36h51ed4ed_2    defaults
six                       1.11.0           py36h372c433_1    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
terminado                 0.6              py36ha25a19f_0    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
tk                        8.6.7                h5979e9b_1    defaults
tornado                   4.5.2            py36h1283b2a_0    defaults
traitlets                 4.3.2            py36h674d592_0    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
wheel                     0.29.0           py36he7f4e38_1    defaults
widgetsnbextension        3.0.2            py36hd01bb71_1    defaults
wxPython                  4.0.0b1                   <pip>
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zeromq                    4.2.2                hb0b69da_1    defaults
zlib                      1.2.11               hfbfcf68_1    defaults
