### ISSUE TITLE
Issue in Installing a different version of Python

### ISSUE THREAD

**Issue by SINOJ** [conda/conda#6215]
(C:\Users\90001433\AppData\Local\Continuum\Anaconda2) C:\Users\90001433>conda create -n py36 python=3.6.3 anaconda
Fetching package metadata ...An unexpected error has occurred.

for Version 3.6 getting like below:

CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

**Comment by kalefranz** [comment]
This is an ssl handshake error.  Sometimes they are intermittent and you should just retry.  Other times you need to update your CA certificates file or check your proxy configuration.
