### ISSUE TITLE
Certain packages produce incorrect pip dependencies

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#6216]
To start with, set "add_pip_as_python_dependency" to false. This is not necessary to reproduce the bug, but will help illustrate the issue more clearly.

Now, run the following commands:

conda create -n TestEnv1 pyreadline pip python=3.5
conda env export -n TestEnv1

The resulting set of dependencies is as follows:

dependencies:
- asn1crypto=0.22.0=py35he3634b9_1
- ca-certificates=2017.08.26=h94faf87_0
- cachecontrol=0.12.3=py35h3f82863_0
- certifi=2017.7.27.1=py35hbab57cd_0
- cffi=1.10.0=py35h4132a7f_1
- chardet=3.0.4=py35h177e1b7_1
- colorama=0.3.9=py35h32a752f_0
- cryptography=2.0.3=py35h67a4558_1
- distlib=0.2.5=py35h12c42d7_0
- html5lib=0.999999999=py35h79d4e7f_0
- idna=2.6=py35h8dcb9ae_1
- lockfile=0.12.2=py35h667c6d9_0
- msgpack-python=0.4.8=py35hdef45cb_0
- openssl=1.0.2l=vc14hcac20b0_2
- packaging=16.8=py35h5fb721f_1
- pip=9.0.1=py35h69293b5_3
- progress=1.3=py35ha84af61_0
- pycparser=2.18=py35h15a15da_1
- pyopenssl=17.2.0=py35hea705d1_0
- pyparsing=2.2.0=py35hcabcaab_1
- pyreadline=2.1=py35_0
- pysocks=1.6.7=py35hb30ac0d_1
- python=3.5.4=hdec4e59_20
- requests=2.18.4=py35h54a615f_1
- setuptools=36.5.0=py35h21a22e4_0
- six=1.11.0=py35hc1da2df_1
- urllib3=1.22=py35h8cc84eb_0
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0
- webencodings=0.5.1=py35h5d527fb_1
- wheel=0.29.0=py35hdbcb6e6_1
- win_inet_pton=1.0.1=py35hbef1270_1
- wincertstore=0.2=py35hfebbdb8_0
- pip:
  - sphinx==1.3.1
  - win-inet-pton==1.0.1

This is wrong. In particular, I believe sphinx==1.3.1 under the pip section should either not be there, or should include additional pip packages. If you take the output of this command and try to share the environment with someone else, what *they* end up installed with is as follows:

dependencies:
- asn1crypto=0.22.0=py35he3634b9_1
- ca-certificates=2017.08.26=h94faf87_0
- cachecontrol=0.12.3=py35h3f82863_0
- certifi=2017.7.27.1=py35hbab57cd_0
- cffi=1.10.0=py35h4132a7f_1
- chardet=3.0.4=py35h177e1b7_1
- colorama=0.3.9=py35h32a752f_0
- cryptography=2.0.3=py35h67a4558_1
- distlib=0.2.5=py35h12c42d7_0
- html5lib=0.999999999=py35h79d4e7f_0
- idna=2.6=py35h8dcb9ae_1
- lockfile=0.12.2=py35h667c6d9_0
- msgpack-python=0.4.8=py35hdef45cb_0
- openssl=1.0.2l=vc14hcac20b0_2
- packaging=16.8=py35h5fb721f_1
- pip=9.0.1=py35h69293b5_3
- progress=1.3=py35ha84af61_0
- pycparser=2.18=py35h15a15da_1
- pyopenssl=17.2.0=py35hea705d1_0
- pyparsing=2.2.0=py35hcabcaab_1
- pyreadline=2.1=py35_0
- pysocks=1.6.7=py35hb30ac0d_1
- python=3.5.4=hdec4e59_20
- requests=2.18.4=py35h54a615f_1
- setuptools=36.5.0=py35h21a22e4_0
- six=1.11.0=py35hc1da2df_1
- urllib3=1.22=py35h8cc84eb_0
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0
- webencodings=0.5.1=py35h5d527fb_1
- wheel=0.29.0=py35hdbcb6e6_1
- win_inet_pton=1.0.1=py35hbef1270_1
- wincertstore=0.2=py35hfebbdb8_0
- pip:
  - alabaster==0.7.10
  - babel==2.5.1
  - docutils==0.14
  - jinja2==2.9.6
  - markupsafe==1.0
  - pygments==2.2.0
  - pytz==2017.2
  - snowballstemmer==1.2.1
  - sphinx==1.3.1
  - sphinx-rtd-theme==0.1.9
  - win-inet-pton==1.0.1

Note the extra pip packages. This is because when one does "pip install sphinx==1.3.1", it pulls in several other pip dependencies. One of the fundamental assumptions we have is that for any environment, you can run "conda env export" to get an environment file, then run "conda env create" on that environment file, and it will produce an identical environment. For the overwhelming majority of environments this is true, but unfortunately this issue breaks that assumption.

One interesting thing to note is that this issue only happens if "pyreadline" and "pip" are installed in conjunction. For example, the following commands:

conda create -n TestEnv2 pyreadline python=3.5
conda env export -n TestEnv2

yield these dependencies:

dependencies:
- pyreadline=2.1=py35_0
- python=3.5.4=hdec4e59_20
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0

and the following commands:

conda create -n TestEnv3 pip python=3.5
conda env export -n TestEnv3

yield these dependencies:

dependencies:
- asn1crypto=0.22.0=py35he3634b9_1
- ca-certificates=2017.08.26=h94faf87_0
- cachecontrol=0.12.3=py35h3f82863_0
- certifi=2017.7.27.1=py35hbab57cd_0
- cffi=1.10.0=py35h4132a7f_1
- chardet=3.0.4=py35h177e1b7_1
- colorama=0.3.9=py35h32a752f_0
- cryptography=2.0.3=py35h67a4558_1
- distlib=0.2.5=py35h12c42d7_0
- html5lib=0.999999999=py35h79d4e7f_0
- idna=2.6=py35h8dcb9ae_1
- lockfile=0.12.2=py35h667c6d9_0
- msgpack-python=0.4.8=py35hdef45cb_0
- openssl=1.0.2l=vc14hcac20b0_2
- packaging=16.8=py35h5fb721f_1
- pip=9.0.1=py35h69293b5_3
- progress=1.3=py35ha84af61_0
- pycparser=2.18=py35h15a15da_1
- pyopenssl=17.2.0=py35hea705d1_0
- pyparsing=2.2.0=py35hcabcaab_1
- pysocks=1.6.7=py35hb30ac0d_1
- python=3.5.4=hdec4e59_20
- requests=2.18.4=py35h54a615f_1
- setuptools=36.5.0=py35h21a22e4_0
- six=1.11.0=py35hc1da2df_1
- urllib3=1.22=py35h8cc84eb_0
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0
- webencodings=0.5.1=py35h5d527fb_1
- wheel=0.29.0=py35hdbcb6e6_1
- win_inet_pton=1.0.1=py35hbef1270_1
- wincertstore=0.2=py35hfebbdb8_0
- pip:
  - win-inet-pton==1.0.1

So it is curious where sphinx==1.3.1 is coming from, since it is apparently neither a dependency of pip=9.0.1=py35h69293b5_3 nor pyreadline=2.1=py35_0 separately, but is when they're together.

Another curious note is that this only happens with python=3.5. If I use python=3.6, the resulting environment does not have sphinx. It can be seen here (with both pip and pyreadline):

dependencies:
- asn1crypto=0.22.0=py36h8e79faa_1
- ca-certificates=2017.08.26=h94faf87_0
- cachecontrol=0.12.3=py36hfe50d7b_0
- certifi=2017.7.27.1=py36h043bc9e_0
- cffi=1.10.0=py36hae3d1b5_1
- chardet=3.0.4=py36h420ce6e_1
- colorama=0.3.9=py36h029ae33_0
- cryptography=2.0.3=py36h123decb_1
- distlib=0.2.5=py36h51371be_0
- html5lib=0.999999999=py36ha09b1f3_0
- idna=2.6=py36h148d497_1
- lockfile=0.12.2=py36h0468280_0
- msgpack-python=0.4.8=py36h58b1e9d_0
- openssl=1.0.2l=vc14hcac20b0_2
- packaging=16.8=py36ha0986f6_1
- pip=9.0.1=py36hadba87b_3
- progress=1.3=py36hbeca8d3_0
- pycparser=2.18=py36hd053e01_1
- pyopenssl=17.2.0=py36h15ca2fc_0
- pyparsing=2.2.0=py36h785a196_1
- pyreadline=2.1=py36_0
- pysocks=1.6.7=py36h698d350_1
- python=3.6.3=h9e2ca53_1
- requests=2.18.4=py36h4371aae_1
- setuptools=36.5.0=py36h65f9e6e_0
- six=1.11.0=py36h4db2310_1
- urllib3=1.22=py36h276f60a_0
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0
- webencodings=0.5.1=py36h67c50ae_1
- wheel=0.29.0=py36h6ce6cde_1
- win_inet_pton=1.0.1=py36he67d7fd_1
- wincertstore=0.2=py36h7fe50ca_0
- pip:
  - win-inet-pton==1.0.1

The fact that it doesn't happen with python 3.6 packages but does with python 3.5 packages would make me think this is a bug in one of the packages, but the fact that pyreadline or pip installed individually do not cause this issue, while installed together they do (I tried pip then pyreadline and pyreadline then pip, order does not matter), makes me think this is a conda bug. Any insight into this would be greatly appreciated.

**Comment by Bezier89** [comment]
PS: I'm currently using the latest versions of conda (4.3.30) and conda-build (3.0.27)

**Comment by Bezier89** [comment]
After more investigation, I have determined that the pyreadline=2.1=py35_0 package on the default channel is bad. There is no other version of pyreadline on the default channels built for Python 3.5, but conda-forge has their own version of pyreadline=2.1=py35_0 that works fine.

You can confirm the package on the default channel is bad by looking at pyreadline-2.1-py35_0.json in the conda-meta folder of the environment. When installed from conda-forge, it is 119 lines and looks as expected. When instead from the default channels, it is 618 lines long and you'll notice by looking at the "files" section that it pollutes site-packages with hundreds of sphinx-related files.

**Comment by Bezier89** [comment]
And specifically, it's only the win-64, Python 3.5 version of pyreadline that's bad/corrupted. You can also tell because it's the only one of the pyreadlines over 1MB, the rest are ~100KB ;)

https://anaconda.org/anaconda/pyreadline/2.1/download/win-64/pyreadline-2.1-py35_0.tar.bz2

**Comment by nehaljwani** [comment]
@Bezier89 There is a new build of the pyreadline package available. Could you try that out? https://repo.continuum.io/pkgs/main/win-64/pyreadline-2.1-py35h9d47d9c_1.tar.bz2

**Comment by Bezier89** [comment]
Thanks @nehaljwani, new package looks good.

**Comment by nehaljwani** [comment]
@Bezier89 Did you figure out where `win-inet-pton` was coming from?

**Comment by Bezier89** [comment]
@nehaljwani urllib3 pulls in pysocks, and pysocks pulls in win-inet-pton. However, I have no idea why win-inet-pton is considered to be both "conda installed" and "pip installed".
