### ISSUE TITLE
LinkError openssl conda env python 2.7 ubuntu linux 32 bit 

### ISSUE THREAD

**Issue by tomasvanoyen** [conda/conda#6217]
Dear, 

I am attempting to make a new conda env (OS: ubuntu 14.04) with the requirement of using python 2.7, 32 bit. 

To force conda to use 32 bit, I've set the following environment: 
`
export CONDA_FORCE_32BIT=1 
`
which, it appears works: 
`
tomas@PowerEdge-T130:~$ conda info | grep platform                
`
`platform : linux-32
`

Unfortunately, then making a new environment fails: 
`
tomas@PowerEdge-T130:~$ conda create -n myenv python=2.7
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/tomas/miniconda3/envs/myenv:

The following NEW packages will be INSTALLED:

    certifi:    2016.2.28-py27_0
    openssl:    1.0.2l-0
    pip:        9.0.1-py27_1
    python:     2.7.13-0
    readline:   6.2-2
    setuptools: 36.4.0-py27_1
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.11-0

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::openssl-1.0.2l-0'.
LinkError: post-link failed for: defaults::openssl-1.0.2l-0
Attempting to roll back.

LinkError: post-link failed for: defaults::openssl-1.0.2l-0
`

Many posts with similar errors report that the path should not have any 'bang' characters, however, this does not seem to be the case here. Any help on this issue is warmly welcomed. 

Thanks in advance!

**Comment by kalefranz** [comment]
Can you give us the output of

    conda create -n myenv python=2.7 -vv

That will show more details about the error being encountered in the post-link script.

**Comment by tomasvanoyen** [comment]
Hi, 

I uploaded the output as file as it is quite lengthy.
 
[output_conda.txt](https://github.com/conda/conda/files/1413619/output_conda.txt)

I hope it helps. 

Thanks, 

Tomas

**Comment by kalefranz** [comment]
Relevant from log:

```
INFO conda.core.link:_execute_actions(319): ===> LINKING PACKAGE: defaults::openssl-1.0.2l-0 <===
  prefix=/home/tomas/miniconda3/envs/myenv
  source=/home/tomas/miniconda3/pkgs32/openssl-1.0.2l-0

DEBUG conda.core.link:run_script(499): for defaults::openssl-1.0.2l-0 at /home/tomas/miniconda3/envs/myenv, executing script: $ /bin/bash -x /home/tomas/miniconda3/envs/myenv/bin/.openssl-post-link.sh
DEBUG conda.gateways.subprocess:subprocess_call(46): executing>> /bin/bash -x /home/tomas/miniconda3/envs/myenv/bin/.openssl-post-link.sh
INFO conda.gateways.subprocess:subprocess_call(54): $ /bin/bash -x /home/tomas/miniconda3/envs/myenv/bin/.openssl-post-link.sh
==> cwd: /home/tomas/miniconda3/envs/myenv/bin <==
==> exit code: 127 <==
==> stdout <==
b''
==> stderr <==
b'
+ cp /home/tomas/miniconda3/envs/myenv/lib/libcrypto.so.1.0.0 /home/tomas/miniconda3/envs/myenv/lib/libcrypto.so.1.0.0-tmp
+ mv /home/tomas/miniconda3/envs/myenv/lib/libcrypto.so.1.0.0-tmp /home/tomas/miniconda3/envs/myenv/lib/libcrypto.so.1.0.0
+ /home/tomas/miniconda3/envs/myenv/bin/.openssl-libcrypto-fix /home/tomas/miniconda3/envs/myenv
/home/tomas/miniconda3/envs/myenv/bin/.openssl-post-link.sh: line 7: /home/tomas/miniconda3/envs/myenv/bin/.openssl-libcrypto-fix: No such file or directory
'

DEBUG conda.core.link:_execute_actions(330): Error in action #115 for pkg_idx #0 LinkPathAction(target_prefix='/home/tomas/miniconda3/envs/myenv', target_short_path='ssl/openssl.cnf', source_prefix='/home/tomas/miniconda3/pkgs32/openssl-1.0.2l-0', source_short_path='ssl/openssl.cnf', link_type=<LinkType.hardlink: 1>, _execute_successful=True, _verified=True)

```

**Comment by kalefranz** [comment]
Also

```
               platform : linux-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/tomas/miniconda3  (writable)
    default environment : /home/tomas/miniconda3
       envs directories : /home/tomas/miniconda3/envs
                          /home/tomas/.conda/envs
          package cache : /home/tomas/miniconda3/pkgs32
                          /home/tomas/.conda/pkgs32
           channel URLs : https://repo.continuum.io/pkgs/free/linux-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-32
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1001:1001
```

**Comment by kalefranz** [comment]
I still don't understand what's happening.  Could be a packaging issue.  Could you just try `conda update conda` and go from there?

**Comment by mingwandroid** [comment]
This is using the old pre-5.0 stuff. Can you reinstall Anaconda Distribution 5.0.1 instead? We have removed the post-link scripts from openssl now.

**Comment by kalefranz** [comment]
`conda update conda` will get you there as well.  It'll bring in the new `pkgs/main` channel at a higher priority :)

**Comment by tomasvanoyen** [comment]
Thanks, 
conda update conda allowed to install a python2.7, 32bit environment. 
Thanks
