### ISSUE TITLE
Broken compatibility with GLIBC in CentOS6 after "conda update --all"

### ISSUE THREAD

**Issue by edu159** [conda/conda#6218]
After updating all packages in Conda in CentOS6 I found that the minimum version required of glibc library is now 2.7 when it used to be <2.4! 

If I try any conda command I get the infamous error:
/home/cpl/miniconda2/bin/python: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/cpl/miniconda2/bin/../lib/libpython2.7.so.1.0)

On my machine:
>ldconfig --version
ldd (GNU libc) 2.5

I checked libpython2.7.so.1.0:
>objdump -T ~/miniconda2/lib/libpython2.7.so.1.0 | grep GLIBC_2.7
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.7   __fread_chk

So it seems that symbol is breaking the compatibility. Any idea if that is a bug or an intended upgrade? Where is that symbol coming from and why is it using 2.7 libc interface?

**Comment by mingwandroid** [comment]
CentOS5 uses glibc 2.5, not CentOS6 uses glibc 2.12:

```
cat /etc/redhat-release 
CentOS release 6.9 (Final)
```

```
cat /etc/redhat-release | head -n1
CentOS release 6.9 (Final)
```

We no longer support CentOS5 as it was causing increasingly bigger problems in terms of the modernity and functionality of the software we were providing.

If you have a pressing business need to run on CentOS5-level operating systems, you could get in touch with sales@anaconda.com

**Comment by edu159** [comment]
Ah thanks! My bad, it is actually CentOS 5.11. Thanks for the info.
