### ISSUE TITLE
Miniconda force overwrite does not overwrite

### ISSUE THREAD

**Issue by tonigi** [conda/conda#6219]
Running this 

    Miniconda3-4.3.27.1-Linux-x86_64.sh  -b -f  -p /tmp/ana

works the first time, but fails the second time around (while -f should force overwrite). 

    PREFIX=/tmp/ana
    installing: python-3.6.2-hdfe5801_15 ...
    mkdir: cannot create directory ‘/tmp/ana/pkgs/python-3.6.2-hdfe5801_15’: File exists

**Comment by kalefranz** [comment]
This issue was moved to conda/constructor#123
