### ISSUE TITLE
Got "An unexpected error has occurred." on running command "conda install -c conda-forge line_profiler | pip install geopy memory_profiler"

### ISSUE THREAD

**Issue by neerajshirname** [conda/conda#6226]
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\Public\Anaconda3  (writable)
    default environment : C:\Users\Public\Anaconda3
       envs directories : C:\Users\Public\Anaconda3\envs
                          C:\Users\Neeraj Shirname\AppData\Local\conda\conda\envs
                          C:\Users\Neeraj Shirname\.conda\envs
          package cache : C:\Users\Public\Anaconda3\pkgs
                          C:\Users\Neeraj Shirname\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Neeraj Shirname\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\Public\Anaconda3\Scripts\conda-script.py install -c conda-forge line_profiler`

    Traceback (most recent call last):
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\cli\install.py", line 302, in install
        common.confirm_yn(args)
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\cli\common.py", line 458, in confirm_yn
        default=default)
      File "C:\Users\Public\Anaconda3\lib\site-packages\conda\cli\common.py", line 440, in confirm
        sys.stdout.flush()
    OSError: [Errno 22] Invalid argument

**Comment by kalefranz** [comment]
You can't pipe the output of a conda command to pip.  If someone on the internet told you to do that, they're wrong.
