### ISSUE TITLE
installing a Conda package offline (windows)

### ISSUE THREAD

**Issue by VanitarNordic** [conda/conda#6234]
Hello,

I have downloaded a package, named `cudatoolkit-8.0-3.tar.bz2`

I try to install it by `conda install cudatoolkit-8.0-3.tar.bz2`, but I get these errors:

```
CondaError: ReadError('file could not be opened successfully',)
CondaError: ReadError('file could not be opened successfully',)
CondaError: ReadError('file could not be opened successfully',)
```

The file path is correct. what is wrong then?

**Comment by VanitarNordic** [comment]
That was my bad, I had downloaded the Linux package instead of Windows :-(

**Comment by VanitarNordic** [comment]
There is another problem. it seems `-` in `cudatoolkit-8.0-3.tar.bz2` causes problem in Windows. I mean `-` before `3`

**Comment by kalefranz** [comment]
What version of conda? `conda info`?  Also, please provide the url that was the source for your `cudatoolkit-8.0-3.tar.bz2` file.

**Comment by VanitarNordic** [comment]
conda version is 4.3.27

I fixed the problem, but I don't know why removing that `-` solved my problem. 

link: https://anaconda.org/anaconda/cudatoolkit/8.0/download/win-64/cudatoolkit-8.0-3.tar.bz2

**Comment by VanitarNordic** [comment]
I appreciate if you update the tensorflow-gpu for windows also. in the pip channel now it is 1.3 but in anaconda is 1.1

**Comment by kalefranz** [comment]
For the package update request, go ahead and file an issue at github.com/ContinnumIO/anaconda-issues.

**Comment by kalefranz** [comment]
> I fixed the problem, but I don't know why removing that - solved my problem.

The dash shouldn't have mattered.  Perhaps you were getting encoding errors? No way to know without more details of the error you were seeing.
