### ISSUE TITLE
Noarch directory error for conda_forge

### ISSUE THREAD

**Issue by abalter** [conda/conda#6246]
I'm getting a noarch directory error for conda_forge.

This error is the same as #5761, but their solution had to do with a particular third party package.

I got this error from a totally clean conda install. This is the first command I issued after installation.

```
(uiserver):u89924123:~$ conda update --all
Fetching package metadata ..........
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda_forge

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
```

This is my `.condarc`

```
(uiserver):u89924123:~$ cat .condarc
channels:
  - anaconda
  - bioconda
  - r
  - conda_forge
  - defaults
```

I've attached `conda config --show`.

[conda_config_show.txt](https://github.com/conda/conda/files/1434740/conda_config_show.txt)

**Comment by kalefranz** [comment]
> It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

`conda_forge` is not a channel.  The channel is `conda-forge`, with a dash instead of an underscore.
