### ISSUE TITLE
Additional install modifier behavior for 4.4

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6247]
Add additional install modifier flag to cover the use case

> A --force a-like option that just means "I don't care what you think is installed, please re-install everything including deps and do not bother me if any files exist on the FS already"

**Comment by kalefranz** [comment]
CC @mingwandroid

**Comment by mingwandroid** [comment]
I should add a caveat to the:

>  don't care what you think is installed

.. part, here, I do expect `conda` to take those things into consideration for solving, but when it comes to writing stuff, I want to forcibly rewrite every file in every package in the dependency tree of the package(s) I asked it to forcibly re-install.

**Comment by kalefranz** [comment]
Current install modifiers are

https://github.com/conda/conda/blob/0ec17c5a6891aadc0fed8e66ae6d301166e7908e/conda/core/solve.py#L36-L43

The addition here should be something like

```python
REINSTALL_ALL = 'reinstall_all'
```

If you're in a situation where you want to combine it with one of the other modifiers, from a UI and code complexity situation I think it's best to leave this as two separate operations for the user.  What I'm saying here is that we shouldn't build out a matrix of options like we did with `UPDATE_DEPS_ONLY_DEPS`.

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/3149
