### ISSUE TITLE
Tclsh results in missing "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib"

### ISSUE THREAD

**Issue by gamdow** [conda/conda#6248]
I'm trying to build some software (OOMMF) which is written in C++, and my build fails using the Conda installed tclsh, giving the error:

```
xiar: executing 'ar'
/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib linux-x86_64/libvf.a
<3373> pimake 1.2.1.0  error:
couldn't execute "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib": no such file or directory
```
Somehow I'm picking up this error only through the Conda installed tclsh - if I explicitly call the system tclsh via the absolute path, the software builds fine.

Similar to https://github.com/conda/conda/issues/6030?

**Comment by mingwandroid** [comment]
Yes, and a similar resolution is best: `conda install gcc_linux-64`

**Comment by gamdow** [comment]
Deleting the conda version of tclsh did the trick for me. But I'm guessing that not defaulting to the system binaries is unintended? Hence the bug report.

**Comment by mingwandroid** [comment]
No, it is intended. I do not know what system binaries you run with and I do not know if they are modern enough to link to our libraries therefore you should use our compilers with our libraries to avoid problems.

**Comment by mingwandroid** [comment]
Defaulting to system tools is going to become a continuing source of github issues. I'd rather just not do it at all.

**Comment by gamdow** [comment]
I'm not familiar with tcl, or much of conda, so apologies if this doesn't follow; Does the current version of tclsh distributed with conda imply a dependency which isn't being met by default (so need to conda install gcc_linux-64)? Or is whatever script tclsh is calling that has the dependencies (in my case?)?

**Comment by mingwandroid** [comment]
If you are building any software that links to any libraries (or Python) from the `Anaconda Distribution` then the best plan of action is to use our toolchains and not involve your system tools (if you're on a *very* modern Linux distro it'll probably be OK, but it's less guaranteed).

**Comment by gamdow** [comment]
Understood, but my intention was not to build OOMMF using the conda toolchains, but simply to install both OOMMF and conda on my system. Can I limit conda's superposition, maybe by taking opt/conda/bin off the path and adding back conda/python/pip/etc explicitly?

**Comment by mingwandroid** [comment]
If you are trying to build `OOMMF` outside of conda and not using python from the `Anaconda Distribution` you should deactivate your conda env before proceeding.

**Comment by gamdow** [comment]
But I only have the root environment, and I can't deactivate that? right? I'm clearly missing something and maybe this isn't a good place to discuss it? :worried:

**Comment by mingwandroid** [comment]
Yes you can deactivate it:

`. deactivate`

**Comment by gamdow** [comment]
:) ty

**Comment by mingwandroid** [comment]
Also, I encourage people not to add `Anaconda` to their `PATH` and instead use the `activate` script when they need to use `Anaconda` software.
