### ISSUE TITLE
Proposal - Change output message of 'conda activate' 

### ISSUE THREAD

**Issue by joshy** [conda/conda#6249]
Whenever I want to change to a different conda environment I can't remember the command to list all environments. However I know I can activate it with `conda activate <env name>` once I know the name. 
When running just `conda activate` it tells me: `You need to specify a conda environment.` This is correct but also not very helpful. My suggestion would be to change the message to something like:
`You need to specify a conda environment. To list environments use "conda env list"`. Even better would be of course to just print out directly the installed environments. This would probably needs some work and would be doing too much.

**Comment by mbargull** [comment]
This hasn't improved, yet. Rather, it has regressed:
```
(base) $ conda --version
conda 4.4.11
(base) $ conda activate --help
help requested for activate
```
`help requested for activate` is even less helpful than `You need to specify a conda environment.`

**Comment by mbargull** [comment]
As is, `conda activate` without an additional argument will now default to activating `base`.
I'm not sure that is the best choice. Having `conda activate` output the proposed `You need to specify a conda environment. To list environments use "conda env list"` sounds better to me.
