### ISSUE TITLE
Permission Error when installing `r-essentials`

### ISSUE THREAD

**Issue by galen211** [conda/conda#6250]
I get the below error when running `conda install r-essentials`:

DEBUG conda.gateways.disk.test:prefix_is_writable(63): testing write access for prefix 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3' using path 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(63): testing write access for prefix 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3' using path 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(63): testing write access for prefix 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3' using path 'C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\conda-meta\history'
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\gasimmons\AppData\Local\Continuum\anaconda3  (writable)
    default environment : C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\envs\r-env
       envs directories : C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\gasimmons\AppData\Local\conda\conda\envs
                          C:\Users\gasimmons\.conda\envs
          package cache : C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\gasimmons\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\gasimmons\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\Scripts\conda install --debug r-essentials`

    Traceback (most recent call last):
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache.py", line 492, in execute
        self._execute_action(action)
      File "C:\Users\gasimmons\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache.py", line 513, in _execute_action
        raise CondaMultiError(exceptions)
    conda.CondaMultiError: PermissionError(13, 'Permission denied')
    PermissionError(13, 'Permission denied')
    PermissionError(13, 'Permission denied')

**Comment by kalefranz** [comment]
Did you create your `r-env` environment under a terminal with Administrator privileges?  That's the only way I know of to get into a situation like this.

**Comment by galen211** [comment]
I'm not able to create environments with R using Navigator.  I also get the same message when trying to install into the default environment

**Comment by mingwandroid** [comment]
I cannot reproduce this. Did you install for `All Users` or `Just Me`? Are you running a virus scanner? Can you try to disable it temporarily?

**Comment by galen211** [comment]
I am using a virus scanner - trying to get admin to disable it, since I checked the logs and this appears to be the problem

**Comment by mingwandroid** [comment]
OK, thanks for the feedback. Which virus scanner are you using?

**Comment by galen211** [comment]
McAfee
