### ISSUE TITLE
Defaults channel has incorrect repodata

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#6255]
Take a look at https://repo.continuum.io/pkgs/main/win-64/repodata.json

As an example, let's look at python-2.7.13-1.tar.bz2

In this channel, this package has the following repodata:

"python-2.7.13-1.tar.bz2": {
      "build": "1",
      "build_number": 1,
      "date": "2017-05-11",
      "depends": [
        "vc 9.*",
        "vs2008_runtime"
      ],
      "license": "PSF",
      "md5": "fd115c17839a0aad86f63f4143577d07",
      "name": "python",
      "size": 24990162,
      "space_anchor": true,
      "version": "2.7.13"
    },

However, if you download the package and use "conda index" (even with latest conda: 4.3.30) on a local channel, the resulting repodata is as follows:

"python-2.7.13-1.tar.bz2": {
      "build": "1",
      "build_number": 1,
      "depends": [
        "vs2008_runtime"
      ],
      "license": "PSF",
      "md5": "fd115c17839a0aad86f63f4143577d07",
      "name": "python",
      "sha256": "d841a927a934f9394ff133c94e9fbc59fb77b3b11dc859ef1220f999202963c6",
      "sig": null,
      "size": 24990162,
      "subdir": "win-64",
      "timestamp": 1509559249,
      "track_features": "vc9",
      "version": "2.7.13"
    },

This dependency mismatch breaks the fundamental assumption that if you use a particular version of a package from a particular channel, it will pull in a known, non-changing set of dependencies. If this is a bug fix, it should only affect new packages going forward. The repodata and dependencies of old packages should never change.

**Comment by kalefranz** [comment]
We'll soon have a solution for this, following https://github.com/conda/conda-build/issues/2407.  After we get that implemented, we'll also be writing a blog post to clear up a lot of this confusion.

**Comment by kalefranz** [comment]
Fundamental issue here is that we have to be able to update metadata over time, most commonly to put upper bounds on the versions of dependencies, but there are also times we need to make other patches.

We intend to implement something similar to https://gist.github.com/jjhelmus/bf9489e3847d8e1737afca7d04b2f66d within `conda index`.  Best place to track that is https://github.com/conda/conda-build/issues/2407.
