### ISSUE TITLE
Updating r and rstudio. RStudio does not start

### ISSUE THREAD

**Issue by FranekW** [conda/conda#6259]
I have been having Anaconda for about a year. I recently tried to update r from version 3.4.1 to 3.4.2 and RStudio upto version 1.1.383. On both systems OS X el capitan and Centos 7 the update was successful but RStudio failed to run! ON OS X it did show empty warning window whereas on Centos 7 it was asking for an object file!
I could not find anything in internet on this issue and decided to reinstall anaconda completely, now having version 5.0.1. I created a new environment and run `conda install r --channel r` and `conda install rstudio --channel r`. This is when RStudio begun to work again.

**Comment by goanpeca** [comment]
@FranekW I think you need to update conda first.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update rstudio
```

**Comment by FranekW** [comment]
I do update conda frequently and this time it did not work. I had to reinstall anaconda

**Comment by mingwandroid** [comment]
It's hard to diagnose this after the fact.

`conda list --show-channel-urls` would've been useful as would `conda info`.
