### ISSUE TITLE
Error in updating conda

### ISSUE THREAD

**Issue by Akshat4112** [conda/conda#6262]
Output of conda report :  
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\andaconda  (writable)
  default environment : C:\andaconda
     envs directories : C:\andaconda\envs
        package cache : C:\andaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
There's no error or stack trace here to take action on.  Sorry.  If you can report more information, feel free to file a new report with complete details on how to reproduce your problem.
