### ISSUE TITLE
Add self-check mode to the Miniconda installer

### ISSUE THREAD

**Issue by mithro** [conda/conda#6264]
The miniconda installer already has code for checking that the binary is the right size and has the correct hash. This is useful to make sure that the download is correct.

However, you can not easily to tell that the Miniconda file downloaded is corrupt or the install failed. It would be good if Miniconda had a "self test" mode which you could run to check that the download worked.

Maybe a `./Miniconda3-latest-Linux-x86_64.sh --verify` or `./Miniconda3-latest-Linux-x86_64.sh --check`.

**Comment by kalefranz** [comment]
This issue was moved to conda/constructor#131
