### ISSUE TITLE
Miniconda3 stopped working suddenly on Windows 10

### ISSUE THREAD

**Issue by vikasmalik22** [conda/conda#6267]
I have a Miniconda3 Windows 64-bit version installed on my Windows 10 PC. The miniconda was working fine but after I restarted my PC it doesn’t run anymore.

When I am trying to start from Windows -> Miniconda3 -> Anaconda Prompt…I am getting this error Access is Denied. Windows just prompts and say This app can’t run on your PC whereas it was running perfectly fine before restarting the PC.I tried searching online to find the solution, I tried turning off the smartscreen detection on windows but that also didn’t help.

I tried restarting several times. I tried to even start as Administrator but doesn’t run. I have it installed on my PC in D:\Miniconda3.

I have the Miniconda3 in my environment path variables as well.

![miniconda3_error](https://user-images.githubusercontent.com/6457663/32448046-caed8a90-c348-11e7-832d-5be3cd5a9afa.PNG)

**Comment by kalefranz** [comment]
Have you been able to resolve your issue?
