### ISSUE TITLE
cannot open c:\anaconda\scripts\conda-script.py

### ISSUE THREAD

**Issue by dyank** [conda/conda#6270]
I can't run anaconda. Each time I type a command I get the error above. I can't find conda-script.py in the scripts folder. How can I locate and download this file? I've tried to uninstall anaconda using control panel and that doesn't work. I've tried running conda install anaconda-clean but I get the error above.

**Comment by kalefranz** [comment]
Probably the easiest thing to do is delete `c:\anaconda` and download a new installer from https://www.anaconda.com/download
