### ISSUE TITLE
Timestamp prioritization results in undesirable race-condition

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#6271]
As discussed on gitter when the time-of-build is taken into account it can result in unnecessary or undesirable upgrades/downgrades of packages.

**Comment by dhirschfeld** [comment]
The example which brought this to light for me is the `pytables=3.4.2` package which has been built (in the default channel) with the same build number but different hashes:
  * `py36h71138e3_2`
  * `py36h71138e3_2` 

Unfortunately, the package which was built most recently was built against an older version of `hdf5` so, simply because of the time the package was built an *update* will try to downgrade `hdf5`:
```
pytables 3.4.2 py36h5b51ad3_2
-----------------------------
channel     : defaults
timestamp   : 1506561470266
dependencies:
    bzip2 >=1.0.6,<2.0a0
    hdf5 >=1.8.18,<1.8.19.0a0
    lzo >=2.10,<3.0a0
    numexpr
    numpy >=1.11.3,<2.0a0
    python >=3.6,<3.7.0a0
    six
    vc 14.*
    zlib >=1.2.11,<1.3.0a0
```
```
pytables 3.4.2 py36h71138e3_2
-----------------------------
channel     : defaults
timestamp   : 1506561439158
dependencies:
    bzip2 >=1.0.6,<2.0a0
    hdf5 >=1.10.1,<1.10.2.0a0
    lzo >=2.10,<3.0a0
    numexpr
    numpy >=1.11.3,<2.0a0
    python >=3.6,<3.7.0a0
    six
    vc 14.*
    zlib >=1.2.11,<1.3.0a0
```

**Comment by kalefranz** [comment]
Thanks for creating the issue @dhirschfeld.  We discussed last week in an internal conda meeting.  I believe @jjhelmus or @nehaljwani will be working with @mcg1969 to fix it.

**Comment by mcg1969** [comment]
I believe that #6279 will knock this out.

**Comment by kalefranz** [comment]
Closing, per #6279.
