### ISSUE TITLE
Multiple package resolutions - how to resolve?

### ISSUE THREAD

**Issue by lifescholar** [conda/conda#6273]
I'm receiving the following warning on issuing the 'conda update --all' command:

`Warning: 2 possible package resolutions (only showing differing packages):`
`  - defaults::quandl-3.2.0-py36h30f7a5e_0, defaults::requests-2.14.2-py36_0`
`  - defaults::quandl-3.1.0-py36_0, defaults::requests-2.18.4-py36h4371aae_1`

Is this as a result of a bug, or is there a way to resolve it?

**Comment by kalefranz** [comment]
Can you provide the output of `conda info`?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#7173
