### ISSUE TITLE
Conda wants to update and downgrade completely unrelated packages

### ISSUE THREAD

**Issue by Khris777** [conda/conda#6281]
I'm at a point where Conda always wants to push a bunch of updates and downgrades on me claiming it were dependencies, regardless of which package I try to update.

It started affecting only a few packages, but now it's at a point where it happens with EVERY package, even with packages that explicitely have no dependencies on any third-party packages.

It's always the same batch of packages, and the majority is downgrades, most notably a downgrade of matplotlib from 2.1.0 to 2.0.2.

This is what happens when I'm trying to only update `pep8`, a small package with no third-party dependencies at all. Note how it wants to even install a new package with kerberos bindings that have NOTHING to do with the pop8 package.

```
The following NEW packages will be INSTALLED:

    krb5:       1.14.2-vc14_0         conda-forge [vc14]

The following packages will be UPDATED:

    bzip2:      1.0.6-vc14hdec8e7a_1              --> 1.0.6-vc14_1      conda-forge [vc14]
    hdf5:       1.10.1-vc14hb361328_0             --> 1.10.1-vc14_1     conda-forge [vc14]
    jpeg:       9b-vc14h4d7706e_1                 --> 9b-vc14_2         conda-forge [vc14]
    libssh2:    1.8.0-vc14hcf584a9_2              --> 1.8.0-vc14_2      conda-forge [vc14]
    libxslt:    1.1.29-vc14hf85b8d4_5             --> 1.1.29-vc14_5     conda-forge [vc14]
    pillow:     4.2.1-py36hdb25ab2_0              --> 4.3.0-py36_1      conda-forge

The following packages will be DOWNGRADED:

    curl:       7.55.1-vc14hdaba4a4_3             --> 7.55.1-vc14_0     conda-forge [vc14]
    freetype:   2.8-vc14h17c9bdf_0                --> 2.7-vc14_2        conda-forge [vc14]
    icu:        58.2-vc14hc45fdbb_0               --> 58.1-vc14_1       conda-forge [vc14]
    libiconv:   1.15-vc14h29686d3_5               --> 1.14-vc14_4       conda-forge [vc14]
    libpng:     1.6.32-vc14hce43e6c_2             --> 1.6.28-vc14_2     conda-forge [vc14]
    libtiff:    4.0.8-vc14h04e2a1e_10             --> 4.0.7-vc14_1      conda-forge [vc14]
    matplotlib: 2.1.0-py36h11b4b9c_0              --> 2.0.2-np113py36_0
    openssl:    1.0.2l-vc14hcac20b0_2             --> 1.0.2l-vc14_0     conda-forge [vc14]
    qt:         5.6.2-vc14h6f8c307_12             --> 5.6.2-vc14_1      conda-forge [vc14]
    sqlite:     3.20.1-vc14h7ce8c62_1             --> 3.19.3-vc14_1     conda-forge [vc14]
    tk:         8.6.7-vc14hb68737d_1              --> 8.5.19-vc14_1     conda-forge [vc14]
    yaml:       0.1.7-vc14hb31d195_1              --> 0.1.6-vc14_0      conda-forge [vc14]
    zlib:       1.2.11-vc14h1cdd9ab_1             --> 1.2.11-vc14_0     conda-forge [vc14]
```

Unless I want to downgrade a bunch of stuff I can't update ANYTHING right now.

I'm using three update channels:

```
defaults
conda-forge
anaconda-fusion
```

Using Windows 10, Anaconda 5, Python 3, Conda 4.3.30

**Comment by jorisvandenbossche** [comment]
This seems very similar to what I reported here https://github.com/conda/conda/issues/6283#issuecomment-343232939 (and we also experience this problem on the geopandas CI: https://github.com/geopandas/geopandas/issues/616)

**Comment by kalefranz** [comment]
@Khris777  Did you ever get more insight here?  If you're still having the problem, I need the output of `conda info` and `conda config --show-sources`.

**Comment by Khris777** [comment]
At one point I simply went through with the whole weird update, since then everything has been normal and I can keep everything up to date just fine.
