### ISSUE TITLE
Deactivate error

### ISSUE THREAD

**Issue by lewis-jeffery** [conda/conda#6285]
Got the following message:

> Lewiss-MacBook-Air:~ lewis$ source activate python3
(python3) Lewiss-MacBook-Air:~ lewis$ source deactivate
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/lewis/anaconda2  (writable)
    default environment : /Users/lewis/anaconda2/envs/python3
       envs directories : /Users/lewis/anaconda2/envs
                          /Users/lewis/.conda/envs
          package cache : /Users/lewis/anaconda2/pkgs
                          /Users/lewis/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/lewis/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/2.7.13 Darwin/17.2.0 OSX/10.13.1    
                UID:GID : 501:20

`$ /Users/lewis/anaconda2/envs/python3/bin/conda ..deactivate.path bash /Users/lewis/anaconda2/envs/python3`

    Traceback (most recent call last):
      File "/Users/lewis/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 171, in main
        activate.main()
      File "/Users/lewis/anaconda2/lib/python2.7/site-packages/conda/cli/activate.py", line 156, in main
        os.environ[str('PATH')], 1)
      File "/Users/lewis/anaconda2/lib/python2.7/re.py", line 155, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)

**Comment by mingwandroid** [comment]
I believe this is caused by having non-ASCII in your PATH.

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/6650
