### ISSUE TITLE
Unexpected error while installing ipykernel

### ISSUE THREAD

**Issue by Serenitas** [conda/conda#6286]
$ C:\Windows\system32\cmd.exe /d /c D:\Program Files\Anaconda\Scripts\.ipykernel-post-link.bat
==> cwd: D:\Program Files\Anaconda\Scripts <==
==> exit code: 1 <==
==> stdout <==

==> stderr <==

An error occurred while installing package 'defaults::ipykernel-4.6.1-py27h30cef79_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
running your command again with `-v` will provide additional information
location of failed script: D:\Program Files\Anaconda\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.14.1
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : D:\Program Files\Anaconda  (writable)
    default environment : D:\Program Files\Anaconda
       envs directories : D:\Program Files\Anaconda\envs
                          C:\Users\Svetlana\AppData\Local\conda\conda\envs
                          C:\Users\Svetlana\.conda\envs
          package cache : D:\Program Files\Anaconda\pkgs
                          C:\Users\Svetlana\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : True

`$ D:\Program Files\Anaconda\Scripts\conda install ipykernel -v`

    Traceback (most recent call last):
      File "D:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "D:\Program Files\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\Program Files\Anaconda\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "D:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "D:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "D:\Program Files\Anaconda\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    CondaMultiError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
    running your command again with `-v` will provide additional information
    location of failed script: D:\Program Files\Anaconda\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

IPython Notebook's kernel is dead, cannot be restarted.

**Comment by mingwandroid** [comment]
As a test, to get more information, can you edit `D:\Program Files\Anaconda\Scripts\.ipykernel-post-link.bat` and change it from:
```
"%PREFIX%"\Python.exe -m ipykernel install --sys-prefix > NUL 2>&1 && if errorlevel 1 exit 1
```

to:

```
"%PREFIX%"\Python.exe -m ipykernel install --sys-prefix && if errorlevel 1 exit 1
```

.. then try again?

**Comment by Serenitas** [comment]
There is no such .bat file in Scripts folder, but I found it in pkgs folder and changed. This is traceback you probably wanted to see:

`$ C:\Windows\system32\cmd.exe /d /c D:\Program Files\Anaconda\Scripts\.ipykernel-post-link.bat
==> cwd: D:\Program Files\Anaconda\Scripts <==
==> exit code: 1 <==
==> stdout <==

==> stderr <==
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "D:\Program Files\Anaconda\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "D:\Program Files\Anaconda\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "D:\Program Files\Anaconda\lib\site-packages\ipykernel\connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths`

**Comment by mingwandroid** [comment]
If you do not have that file in `Scripts` it means your installation did not complete successfully. The only reason I've seen so far for that to happen is due to virus scanners getting in the way. Can you try to disable any you have running and try again?

**Comment by lin-aaron** [comment]
I also have the same issue, and disabling my virus scanners didn't work for me. I'm not sure if it happened for Svetlana, but Anaconda's installer wouldn't work for me, and I had to use Miniconda instead. However when running "conda install anaconda" it fails when trying to install ipykernel with the same error message.

**Comment by mingwandroid** [comment]
I believe I have fixed the missing `activate.bat`/`conda.exe` problem. It is a race-condition around virus scanners (but also Windows itself). If anyone here is still suffering from it, can you please try one of the Windows `Miniconda` installers in https://repo.continuum.io/pkgs/misc/preview/ and let me know if it works for you?

To go from `Miniconda` to the latest `Anaconda` you can run the `Anaconda Prompt` then do `conda install anaconda`

**Comment by mingwandroid** [comment]
Just to note since this is closed, the Minicondas to which I was referring have been moved out of the preview directory now as we are happy they are good enough for general consumption. You can find them here now: https://repo.continuum.io/miniconda/

**Comment by cookierolls** [comment]
I have the same issue too,and finally solve the problem by uninstalled my virus scanners.

**Comment by MuqadderIqbal** [comment]
Running in to this same error (but for Anaconda 5.0.1 For Windows 64 bit ). I'm on a company provided workstation and I can't uninstall antivirus software to make things work. There has to be a better way of fixing this issue but I haven't seen any solutions here on this thread that doesn't involve uninstalling stuff.

**Comment by andrewimcclement** [comment]
I have exactly the same issue as @MuqadderIqbal .

**Comment by hvpandya** [comment]
Installed Miniconda and tried upgrading to full Anaconda, getting the same error as others

```
ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::ipykernel-4.8.0-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\harsh\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\harsh\Miniconda3\Scripts\.ipykernel-post-link.bat
```

**Comment by mingwandroid** [comment]
Please follow https://github.com/conda/conda/issues/6286#issuecomment-343447441

Though you shouldn't need this via-Miniconda workaround anymore since the problem was fixed in Anaconda 5.1 already.

**Comment by andrewimcclement** [comment]
It seems for me the batch file is in the wrong place (similarly to @Serenitas ). Editing the batch file led to SHA mismatch. Will try uninstalling Anaconda and reinstalling. Thanks for your help @mingwandroid .

**Comment by MuqadderIqbal** [comment]
I was able to resolve this issue by following a set of simple steps I came across on another similar thread on Github. Here are the steps that worked for me:-

1. Open anaconda prompt window (preferably launched as Administrator)
2. Run this command
       **conda update conda**
3. then run,
        **conda update ipykernel**
4 and finally :
**conda update --all**

Original post: https://github.com/ContinuumIO/anaconda-issues/issues/8087#issuecomment-365397764

**Comment by MuqadderIqbal** [comment]
@mingwandroid  can you expand on that a bit more? What kind of permissions issues might we run into when upgrading Anaconda as an administrator? Most of the online documentation I have come across in fact says running the update commands in an elevated/admin mode is preferable. Moreover, I have personally run into problems upgrading Anaconda on my corporate workstation when running the anaconda prompt as a non-admin. The only way I was able to do that was to run the anaconda prompt as an admin, even though Anaconda was not installed as Administrator.

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/6610

**Comment by mingwandroid** [comment]
> Most of the online documentation I have come across in fact says running the update commands in an elevated/admin mode is preferable

Where is this documentation? The opposite is generally true (to be exact, if you install as an admin/super-user you should update as admin/super-user and if not then you should not, and we recommend non-admin installation in general).

> Moreover, I have personally run into problems updating Anaconda on my corporate workstation when running the anaconda prompt as a non-admin. The only way I was able to do that was to run the anaconda prompt as an admin, even though Anaconda was not installed as Administrator.

Please file a bug. It sounds like you have messed up permissions on the folder you installed in here. Swapping from admin to non-admin will do that though.

**Comment by MuqadderIqbal** [comment]
Like I mentioned earlier, first Anaconda install was done as a non-admin, to the Anaconda default folder at the install time. I am not sure what you mean by "messed up permissions". There is no other program that'd have changed the permissions on that folder, nor have I tried to fiddle with the folder level permissions myself. Moreover, there has been no admin to non-admin swap. It's the other way around: I had to ask my IT team to grant me local admin permissions (which I didn't have when I originally installed Anaconda) so I could update it.

**Comment by moulla** [comment]
Same experience here.  ipykernel-4.8.2 on a fresh (non-admin) anaconda install fails.  both without and with elevated privilege.

LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0

**Comment by thatlittleboy** [comment]
This is still an issue for me as well, same error with ipykernel-4.8.2-py36_0.

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package '<unknown>::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package <unknown>::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package <unknown>::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
```

`conda info` gives the following:
```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.0
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\user\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

I can't use the solution [by MuqadderIqbal above](https://github.com/conda/conda/issues/6286#issuecomment-367154918) because `ipykernel` is not even installed in my system/anaconda distribution.

`conda update ipykernel` gives an error:
```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\ProgramData\Anaconda3
  package name: ipykernel
```
as expected.

But `conda install ipykernel` keeps giving the error above. Any tips here?

**Comment by mingwandroid** [comment]
Try conda update jedi first.

On Mar 23, 2018 1:07 AM, "thatlittleboy" <notifications@github.com> wrote:

This is still an issue for me as well, same error with
ipykernel-4.8.2-py36_0.

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while
installing package '<unknown>::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package <unknown>::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script:
C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package <unknown>::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script:
C:\ProgramData\Anaconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

conda info gives the following:

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.0
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\user\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4
Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

I can't use the solution by MuqadderIqbal above
<https://github.com/conda/conda/issues/6286#issuecomment-367154918> because
ipykernel is not even installed in my system/anaconda distribution.

conda update ipykernel gives an error:

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\ProgramData\Anaconda3
  package name: ipykernel

as expected.

But conda install ipykernel keeps giving the error above. Any tips here?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/conda/conda/issues/6286#issuecomment-375506836>, or mute
the thread

**Comment by thatlittleboy** [comment]
@mingwandroid I did `conda update jedi`, which was successful, then `conda install ipykernel`, and it installed ipykernel 4.8.2 successfully as well. Then had to use `conda update --all` instead of `conda update anaconda` because the latter would attempt to downgrade ipykernel back to 4.8.0. 

It all works fine now, thanks.

**Comment by bbiney1** [comment]
I'm using Miniconda, windows 10. I didn't have jedi before so I performed `conda install jedi` then `conda update jedi`. Then I tried `conda install ipykernel` and I"m still getting the LinkError

`Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\biney\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==`

**Comment by Grkmus** [comment]
@bbiney1 exactly same situation.

**Comment by julianhemde** [comment]
@bbiney1 @Grkmus  i have the same issue, have you found any solution?

**Comment by washcycle** [comment]
<company>\<username> ran PYTHON.EXE, which tried to access C:\USERS\MLANDO1\APPDATA\LOCAL\TEMP\1\PIP-INSTALL-5ICYUXNT\TENSORFLOW-GPU\TENSORFLOW_GPU-1.12.0.DATA\PURELIB\TENSORFLOW, violating the rule "Writing to files commonly targeted by ransomware-class malware", and was blocked. For information about how to respond to this event, see KB85494.

**Comment by parkershamblin** [comment]
I hope this can help someone. This is how I solved.

My situtation:
Creating a new python 2.7 conda environemnt and when I ran conda install jupyter notebook, I was met with the following error:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::ipykernel-4.10.0-py27_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py27_0
location of failed script: C:\Users\parker\Anaconda3\envs\py27\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr:
return code: 1

()
```

I solved by simply using the command:
```
pip install jupyter notebook
```
instead of the previous command I was using:
```
conda install jupyter notebook
```

**Comment by iValentinTee** [comment]
I was facing same error when trying to install spyder with conda 4.8.3. What i did was 

1. Update conda to 4.8.4
`conda update -n base -c defaults conda`

2. Install ipykernel. After this completed successfully, .ipykernel-post-link appeared in my script folder.
`conda install ipykernel`

3. Install spyder
`conda install spyder`

**Comment by Jens1985** [comment]
Its old, but maybe ist helps:

`set PYTHONIOENCODING=UTF-8`

did it for me
