### ISSUE TITLE
conda install --revision N REMOVED CONDA

### ISSUE THREAD

**Issue by nreitman** [conda/conda#6290]
Hello, 

Today I discovered that conda can remove itself, which seems like it shouldn't be possible. Here's what happened:

Conda was updated from 4.3.29 to 4.3.30 when I installed a package (spyder-ide) that was supposed to let me get a bash terminal in my Spyder GUI. However, the package didn't work, so I decided to remove it. I did so by reverting back to the previous revision rather than uninstalling it and its dependencies. BAD MISTAKE! As you can see from my revision history below, conda install --revision 36 _removed_ conda entirely instead of downgrading it. Now I don't have conda. 

Is there a fix besides reinstalling Anaconda?

Thanks.

2017-11-12 15:26:47  (rev 36)
     conda  {4.3.29 -> 4.3.30}
    +coloredlogs-7.1
    +humanfriendly-4.4
    +spyder-terminal-0.2.2 (spyder-ide)

2017-11-12 15:29:16  (rev 37)
    -coloredlogs-7.1
    -conda-4.3.30
    -humanfriendly-4.4
    -spyder-terminal-0.2.2 (spyder-ide)

**Comment by kalefranz** [comment]
Wow, that's bad.

If you're on unix, easiest solution is to download the miniconda .sh installer, then use

    bash miniconda.sh -bfp /path/to/Anaconda/directory

**Comment by Jking-GIS** [comment]
Is there a quick fix to this for a Windows installation too?
