### ISSUE TITLE
Conda doesn´t run

### ISSUE THREAD

**Issue by Joaquinjoaquin** [conda/conda#6297]
Hello,

I´m starting with programming. I installed anaconda (windows) and tried to run conda. I set manually the PATH to Anaconda3 and scripts. The problem is that conda doesn´t run. I think it´s because conda.exe isn´t in scripts, so i put it myself. Then i get this problem:

Traceback (most recent call last):
  File "C:\Users\joaqu\Anaconda3\Scripts\conda-script.py", line 6, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

Im using the latest version of Anaconda
Please help

**Comment by kalefranz** [comment]
Please use the "Anaconda Prompt" application and icon to start the shell after installing Anaconda.

**Comment by Joaquinjoaquin** [comment]
Thanks for answering so quickly. I did. The problem is happening with the anaconda prompt.

El 14 nov. 2017 11:09 AM, Kale Franz <notifications@github.com> escribió:

Closed #6297<https://github.com/conda/conda/issues/6297>.

**Comment by Joaquinjoaquin** [comment]
Thanks for the quick answer. I used the anaconda prompt.


El 14 nov. 2017 11:09 AM, Kale Franz <notifications@github.com> escribió:

Please use the "Anaconda Prompt" application and icon to start the shell after installing Anaconda.
