### ISSUE TITLE
Miniconda3 4.3.30 "python" and "conda" versions inconsistency

### ISSUE THREAD

**Issue by FeodorFitsner** [conda/conda#6306]
Installing Miniconda3 4.3.30 on Windows (both [x64](https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Windows-x86_64.exe) and [x86](https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Windows-x86.exe)) and running `conda --version` yields wrong version information:

    conda 4.3.27

Shouldn't it be `conda 4.3.30`?

Also, target python version is also different in x64 and x86 packages.

x64: `Python 3.6.3 :: Anaconda, Inc.`
x86: `Python 3.6.2 :: Anaconda, Inc.`

Presumably both should target 3.6.3, right?

Could you please clarify?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#7323
