### ISSUE TITLE
After running conda update --all, 'ruamel_yaml' is missing

### ISSUE THREAD

**Issue by TMorville** [conda/conda#6311]
Summary: Ran conda update -all, now ruamel.yaml is missing. When pip installing it, it shows up as already installed. Can't run _any_ conda commands. 

Ran

    conda update --all

which completed. Afterwards, when doing anything in conda it throws an error

    ImportError: No module named 'ruamel_yaml'

Output of `echo $PATH`

`/Users/*username*/anaconda/bin:/usr/local/fsl/bin:/opt/spark/bin:/usr/local/bin:/usr/bin:/bin:/usr/sin:/sbin:/opt/X11/bin:/Library/TeX/texbin`

and `which conda` outputs 

    /Users/*username*/anaconda/bin/conda
If I do `pip install ruamel.yaml` i get

    Requirement already satisfied: ruamel.yaml in /usr/local/lib/python2.7/site-packages
    Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/local/lib/python2.7/site-packages (from ruamel.yaml)

[Stack copy](https://stackoverflow.com/questions/47307346/importerror-no-module-named-ruamel-yaml-after-conda-update-all).

**Comment by kalefranz** [comment]
Try `pip install -U ruamel.yaml`.  Can't help much beyond that, without the output that was given with the `conda update --all` command.

**Comment by Harmeet2504** [comment]
Hi, I ran into the same error. Could you resolve this?

**Comment by Ntkrell** [comment]
@Harmeet2504 did you solve the problem? I have the same issue.

**Comment by Ntkrell** [comment]
Per @Harmeet2504's advice, uninstalling and reinstalling conda fixed this issue.
