### ISSUE TITLE
pip writes into a cache that is not environment specific leading to problems when attempting to rebuild.

### ISSUE THREAD

**Issue by james-lawrence** [conda/conda#6312]
to reproduce have an environment that uses a pip package that depends on a shared library.
```
conda env create -f environment.yml
conda env remove -n {env}
mv lib{foo.so.5.0.0,foo.so.5.0.1}
ln -s libfoo.so libfoo.so.5.0.1
conda env create -f environment.yml 
```

this will fail due to the pip cache in the user's home directory referencing the old shared library.
conda clean --all doesn't fix this because it doesn't touch the pip cache.
conda needs to move the pip cache into the environment directory when installing pip packages so that a clean, or remove will properly remove said references.

**Comment by kalefranz** [comment]
Yeah this is very much a known issue.  We have tons of both open and closed issues related to it.  There's nothing conda can do.  It'll take patching pip to fix this.

**Comment by kalefranz** [comment]
The patched pip has now been released.  See https://github.com/conda/conda/issues/6861
