### ISSUE TITLE
Conda command produces no response

### ISSUE THREAD

**Issue by msaharia** [conda/conda#6314]
I have been using `Anaconda` for quite some time. I had reinstall recently.

Distro: Ubuntu
I selected a different folder than default for conda installation. 

And added `export PATH="/d1/m/anaconda3/bin:$PATH"`

When I call `python`, the conda environment is called correctly.

However, outside, `conda` command produces no response. No error message. It simply runs and drops off.

Please let me know what the problem is.

**Comment by kalefranz** [comment]
What's the output of `conda info`?

**Comment by fxia22** [comment]
Same issue. `conda info` also produces nothing.

**Comment by msaharia** [comment]
`conda info` produces nothing for me. But calling python opens the  conda shell

**Comment by mbargull** [comment]
What does
```
type conda
(set -x && conda info)
```
show?

**Comment by kalefranz** [comment]
What is the output of `conda --version`?

**Comment by msaharia** [comment]
1. conda is hashed (/d1/msaharia/anaconda3/bin/conda)
+ conda info

2. conda --version produces no response

**Comment by kalefranz** [comment]
How about `"$(which conda)" --version`?

**Comment by msaharia** [comment]
No response, unfortunately. But conda command line python works perfectly.

**Comment by msaharia** [comment]
Reinstalling didn't help.

**Comment by fxia22** [comment]
same.

**Comment by kalefranz** [comment]
How about

    cat "$(which conda)"

**Comment by msaharia** [comment]
Here
```
#!/d1/msaharia/anaconda3/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from conda.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by kalefranz** [comment]
Ok, how about

    python
    import conda
    print(conda.__version__)

**Comment by msaharia** [comment]
>>> print(conda.__version__)
4.3.30

**Comment by kalefranz** [comment]
How about

```
python
from conda.cli.python_api import *
run_command(Commands.INFO)
```

**Comment by msaharia** [comment]
```
>>> from conda.cli.python_api import *
>>> run_command(Commands.INFO)
('Current conda install:\n\n               platform : linux-64\n          conda version : 4.3.30\n       conda is private : False\n      conda-env version : 4.3.30\n    conda-build version : 3.0.27\n         python version : 3.6.3.final.0\n       requests version : 2.4.3\n       root environment : /d1/msaharia/anaconda3  (writable)\n    default environment : /d1/msaharia/anaconda3\n       envs directories : /d1/msaharia/anaconda3/envs\n                          /home/manab/.conda/envs\n          package cache : /d1/msaharia/anaconda3/pkgs\n                          /home/manab/.conda/pkgs\n           channel URLs : https://repo.continuum.io/pkgs/main/linux-64\n                          https://repo.continuum.io/pkgs/main/noarch\n                          https://repo.continuum.io/pkgs/free/linux-64\n                          https://repo.continuum.io/pkgs/free/noarch\n                          https://repo.continuum.io/pkgs/r/linux-64\n                          https://repo.continuum.io/pkgs/r/noarch\n                          https://repo.continuum.io/pkgs/pro/linux-64\n                          https://repo.continuum.io/pkgs/pro/noarch\n            config file : None\n             netrc file : None\n           offline mode : False\n             user-agent : conda/4.3.30 requests/2.4.3 CPython/3.6.3 Linux/3.16.0-5-amd64 debian/8.10 glibc/2.19    \n                UID:GID : 29693:1500\n', '', None)
```

**Comment by kalefranz** [comment]
So I guess there's something going on with the entry point.  I have no idea what it could be though.  I'm not seeing anything.

**Comment by kalefranz** [comment]
Oh, one more...

    python -m conda info

**Comment by msaharia** [comment]
Yeah, I am not sure how to debug it.

`python -m conda info` produces no response.

**Comment by kalefranz** [comment]
How about this...

    conda create -p ./test-env --yes
    ls -al

See if an empty environment actually gets created in the current directory.

**Comment by msaharia** [comment]
This is what I get.

@ $ ls -al
total 8
drwxr-sr-x 2 manab rap1 4096 Feb 21 18:56 .
drwxr-sr-x 8 manab rap1 4096 Feb 21 18:56 ..

**Comment by kalefranz** [comment]
Ok well I had a theory that conda was actually running and it was some issue with stdout and stderr.  So I guess we're back to something going on with the entry point.

**Comment by mbargull** [comment]
What does
```
which python
```
say?

**Comment by msaharia** [comment]
`/d1/msaharia/anaconda3/bin/python`

**Comment by mbargull** [comment]
And
```
python -c 'from conda.cli.main import main; main("conda", "info")'
```
as well as
```
python -c 'import sys; sys.argv[0] = "conda"; from conda.cli.main import main; main()' info
```
?

**Comment by msaharia** [comment]
Neither produces any response.

**Comment by mbargull** [comment]
That very interesting/puzzling..
```
python -c 'print("test")'
python -m pip
python -c 'import conda; print(conda.__version__)'
python -c 'from conda.cli.python_api import *; print(*run_command(Commands.INFO))'
```
?

**Comment by kalefranz** [comment]
🤨

**Comment by msaharia** [comment]
manab @ /d3/msaharia/ffreq/forcinggeneration/test
# @ $ python -c 'print("test")'
test
manab @ /d3/msaharia/ffreq/forcinggeneration/test

# @ $ python -m pip
Traceback (most recent call last):
  File "/d1/msaharia/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/d1/msaharia/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/d1/msaharia/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/d1/msaharia/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2091, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/dist-packages/mpl_toolkits/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1520, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
manab @ /d3/msaharia/ffreq/forcinggeneration/test

# @ $ python -c 'import conda; print(conda.__version__)'
4.3.30
manab @ /d3/msaharia/ffreq/forcinggeneration/test
# @ $ python -c 'from conda.cli.python_api import *; print(*run_command(Commands.INFO))'
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.4.3
       root environment : /d1/msaharia/anaconda3  (writable)
    default environment : /d1/msaharia/anaconda3
       envs directories : /d1/msaharia/anaconda3/envs
                          /home/manab/.conda/envs
          package cache : /d1/msaharia/anaconda3/pkgs
                          /home/manab/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.4.3 CPython/3.6.3 Linux/3.16.0-5-amd64 debian/8.10 glibc/2.19
                UID:GID : 29693:1500
  None

**Comment by mbargull** [comment]
```
 (echo $PYTHONPATH ; unset PYTHONPATH ; HOME=/tmp PATH=/d1/msaharia/anaconda3/bin conda info)
```
?

**Comment by msaharia** [comment]
@ $ (echo $PYTHONPATH ; unset PYTHONPATH ; HOME=/tmp PATH=/d1/msaharia/anaconda3/bin conda info)
:/opt/lib/python2.7/site-packages/
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /d1/msaharia/anaconda3  (writable)
    default environment : /d1/msaharia/anaconda3
       envs directories : /d1/msaharia/anaconda3/envs
                          /tmp/.conda/envs
          package cache : /d1/msaharia/anaconda3/pkgs
                          /tmp/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/3.16.0-5-amd64 debian/8.10 glibc/2.19
                UID:GID : 29693:1500

**Comment by mbargull** [comment]
Aha! `/opt/lib/python2.7/site-packages/`
Does this work:
```
PYTHONPATH= conda info
```
?

**Comment by msaharia** [comment]
@ $ PYTHONPATH= conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /d1/msaharia/anaconda3  (writable)
    default environment : /d1/msaharia/anaconda3
       envs directories : /d1/msaharia/anaconda3/envs
                          /home/manab/.conda/envs
          package cache : /d1/msaharia/anaconda3/pkgs
                          /home/manab/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/3.16.0-5-amd64 debian/8.10 glibc/2.19
                UID:GID : 29693:1500

**Comment by mbargull** [comment]
So, basically you make Python look in `/opt/lib/python2.7/site-packages/` for packages via the `PYTHONPATH` environment variable. Since the Miniconda installation has a completely different Python installation which has to look at `/d1/msaharia/anaconda3/lib/python3.6/site-packages/`, it doesn't find its packages.
You'll just have to not set that variable (in your `.bashrc` or other files) and be good to go!
(If you can't figure out where that variable is defined in you setup, you can always run `unset PYTHONPATH` to get rid of it.)

**Comment by msaharia** [comment]
I had these in my bashrc

export PATH="/d1/msaharia/anaconda3/bin:$PATH"

export LD_LIBRARY_PATH=/opt/netcdf4-intel/lib:/opt/hdf5/lib:/opt/szip-2.1:/opt/zlib-1.2.8:$LD_LIBRARY_PATH

**Comment by msaharia** [comment]
But unset PYTHONPATH worked. Thank you so much!  👍
