### ISSUE TITLE
[Linux] Keyboard keys not working on URxvt - readline related?

### ISSUE THREAD

**Issue by mhham** [conda/conda#6322]
I have just installed conda 4.4.30 on linux, and use python 3.6.3 from URxvt terminal.

The backspace and arrow keys are not working on the interpreter on URxvt terminal, while they are working on other terminals (xterm). More precisely they are detected as characters / espace characters instead.

There was a similar issue [here](https://groups.google.com/a/continuum.io/d/searchin/anaconda/readline/anaconda/N5J8k12Wg9U/5lmc9R4kAgAJ)

My version of readline is : `readline                  7.0                  ha6073c6_4`

**Comment by mhham** [comment]
Just found [this solution](https://github.com/ContinuumIO/anaconda-issues/issues/6758), but it is a temporary fix since it downgrades the whole distribution.

A `conda update --all` would make the problem appear again.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8271
