### ISSUE TITLE
Error in PackageNotFoundError

### ISSUE THREAD

**Issue by byyang007** [conda/conda#6325]
I found there's a bug when we execute `conda list -e > environment.txt`. The output file contains statements like `nb-conda==2.2.1`, which will cause a unexpected termination when execute installation command. 

This issues has been reported a lot, and it should be simple to resolve. Just change the dash "-" to underscore "_".

Current conda install:
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       //... ...
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-38-generic debian/stretch/sid glibc/2.23
                UID:GID : 1001:1002

**Comment by kalefranz** [comment]
I can't reproduce this issue with the latest conda 4.4.
