### ISSUE TITLE
noarch package producing invalid python code for entry point

### ISSUE THREAD

**Issue by msarahan** [conda/conda#6332]
@dougalsutherland commented on [Tue Sep 12 2017](https://github.com/conda/conda-build/issues/2362)

Example failure: [nbformat-feedstock](https://github.com/conda-forge/nbformat-feedstock) has a recipe with 
```yaml
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
```
which I just tried to change (https://github.com/conda-forge/nbformat-feedstock/pull/9) to be `noarch: python`. This produced a file with a line like
```python
from nbformat.sign import TrustNotebookApp.launch_instance
``` 
which of course caused a syntax error.

Doesn't happen without `noarch: python`.

(This is using conda-build 2.)

---

@jakirkham commented on [Wed Sep 13 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-329212360)

Just out of curiosity, does this happen with `conda-build` 3 as well? If not, we might be able to backport a fix.

---

@dougalsutherland commented on [Wed Sep 13 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-329219615)

Yep, same output for current master (d246171198a8a29224cd7fe82af90344ce6a21dd).

---

@jakirkham commented on [Wed Sep 13 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-329221872)

Thanks for confirming.

---

@pelson commented on [Wed Nov 15 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-344603157)

Just had a similar (perhaps not identical though) issue for the [conda-gitenv feedstock](https://github.com/conda-forge/conda-gitenv-feedstock/pull/5).

In my local build directory, the entrypoint script appears to not be executable:

```
+ source /Users/pelson/miniconda/bin/activate /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/_t_env
+ /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/_t_env/bin/python -s /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/test_tmp/run_test.py
import: 'conda_gitenv'
+ /bin/bash -x -e /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/test_tmp/run_test.sh
+ conda gitenv --help
TESTS FAILED: conda-gitenv-0.3.1-py_0
```

```
pelson@~/dev/conda-forge/feedstocks/conda-gitenv-feedstock> ll /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/_t_env/bin/conda-gitenv
-rw-rw-r--  1 pelson  staff  469 15 Nov 13:52 /Users/pelson/miniconda/conda-bld/conda-gitenv_1510753845438/_t_env/bin/conda-gitenv
```

Explicitly adding the entrypoint to the meta.yaml solved the issue for me. I was running (a pretty ancient) ``conda-build 2.1.10``. Updating to ``2.1.17`` didn't solve the issue.

---

@isuruf commented on [Mon Nov 20 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-345905095)

This commit, https://github.com/conda/conda/commit/dbacd91780ab0538a8975ceba7bba27f5de2de10 fixes it for conda 4.4.x, but not for conda 4.3.x

---

@msarahan commented on [Tue Nov 21 2017](https://github.com/conda/conda-build/issues/2362#issuecomment-346123350)

I'm moving this issue to the conda tracker, since @isuruf isolated its fix to something in conda.  Thanks @isuruf

**Comment by kalefranz** [comment]
@isuruf Do you still consider this a high priority? Honestly, I'd rather spend time getting conda 4.4 into conda-forge.  The biggest blocker there is https://github.com/conda-tools/conda-build-all/pull/96, where there's one remaining test failure I haven't had time to figure out how to address.

**Comment by isuruf** [comment]
I think we'd want to support both 4.3 and 4.4 a bit more. `conda-build-all` will not be used in conda-forge infrastructure once we move to conda-build=3
