### ISSUE TITLE
conda installing packages in the wrong folder, then it cannot be found

### ISSUE THREAD

**Issue by luk-f-a** [conda/conda#6333]
Hello,

I created a fresh new environment. I install (via conda) numpy, xarray, matplotlit, spyder. When trying to run spyder, it complains about "no module named 'jupyter_core".
conda install jupyter_core reports: "All requested packages already installed."
conda env export   reports:  "- conda-forge::jupyter_core=4.4.0=py_0"
Running python's console and attempting "import jupyter_core" returns the same "no module named 'jupyter_core".
Looking at [..]/lib/python3.6/site-packages/ I see there's no jupyter core folder, which there is in another environment that works fine. If I copy that folder into this environment I am able to import jupyter_core.
I tried to reinstall using --force, I tried deleting environment and starting fresh.
I think the problem starts when I create the environment with "conda create -n myenv spyder". It reports installing jupyter_core, but it does not actually do it.
I have an identical problem with pytz.
I am working on Mint 18.2 KDE 64bits, conda 4.2.9

I really don't know what do do, I cannot use any new environment.

**Comment by luk-f-a** [comment]
After further investigation, I can see that every package I have a problem with is being installed in [env name]/site-packages/
python is not able to find them there. In other environment I have, those same packages (pytz, jupyter-core) have been installed in [env name]/lib/python3.6/site-packages/
Not every package is being stored in [env name]/site-packages/, most are in lib/python3.6/site-packages/ but a few of them are in that location: dask, jupyter_core, nbconvert, pytz, tlz, toolz, wheel, zict.

**Comment by kalefranz** [comment]
Conda 4.2 is no longer supported.  Please update to the latest patch version of conda 4.3 or 4.4.

**Comment by kalefranz** [comment]
`conda update conda`
