### ISSUE TITLE
conda install --rev REV_NUM doesn't work when trying to revert back to a later revision

### ISSUE THREAD

**Issue by jmsy00** [conda/conda#6334]
**conda version 4.3.30**

was debugging a separate issue and tried going to a rev without a specific package installed...

**works as advertised:**
`)) conda install --rev earlier_revnum `
...
**should this work? Attempting to return to a rev with the package installed**
```
)) conda install --rev later_revnum
"All requested packages are already installed."

)) conda --list
... package not here ...
```

**Comment by kalefranz** [comment]
This will be fixed with https://github.com/conda/conda/pull/6719
