### ISSUE TITLE
OSError : Invalid Data Stream when trying to create a virtual environment

### ISSUE THREAD

**Issue by Black-Swan-ICL** [conda/conda#6336]
Hi,

I have installed the most recent version of Anaconda on a Windows machine that I am using at the
moment. I am trying to create a virtual environment using conda by running the following command
in an Anaconda prompt : 
**conda create -n MyEnvName python=3.6.3**
When running this command, I get an **OSError**.

I am enclosing the full error message. I am also enclosing the output I get when running **conda info**.

Every time I try to run the _conda create_ command, I run the _conda config --set ssl_verify false_ command beforehand.

![condacreateerrorstack](https://user-images.githubusercontent.com/17177996/33212663-10e18d5e-d11c-11e7-95bf-c1a808d54954.png)
![condainfo](https://user-images.githubusercontent.com/17177996/33212664-111642ba-d11c-11e7-88c3-b1c04537eedc.png)

**Comment by nehaljwani** [comment]
Does `conda clean --all -y` help?

**Comment by Black-Swan-ICL** [comment]
Hi @nehaljwani,

thanks for your answer !

I am afraid that unfortunately, it does not solve the problem. I still
have the exact same issue

**Comment by kalefranz** [comment]
This is happening during repodata downloading.  I think it's just a flakey network connection.
