### ISSUE TITLE
activate.d scripts is likely not ran in order.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6338]
scripts in  /etc/conda/activate.d are likely not ran in order:

```
   if [[ -d "$_CONDA_D" ]]; then
        eval $(find "$_CONDA_D" -iname "*.sh" -exec echo source \'{}\'';' \;)
    fi

```

See here:
https://serverfault.com/questions/181787/find-command-default-sorting-order

If there are interdependency between scripts this will be very badly messed up. -- I am looking into if we can make the new cross-compilation enabled mpich package to fall back to use CXX and CC when the cross-toolchain is not installed (the result should still work on the local system since it is ABI compatable). For this to work, however, it depends on the cross compilation activate.d scripts to run before the mpich one.

**Comment by mingwandroid** [comment]
A PR to conda would be welcome here. We're all probably too busy. You'd need to perform a topological sort. You wouldn't need to do this upon every activation, just when things get installed or removed form an env, caching the result in a script to be run.

**Comment by rainwoodman** [comment]
I am not sure if I understand your proposal...

I was thinking more along the lines of init.d scripts style -- ordering by file names, then run forward in activate and backward in deactivate. This is sufficiently deterministic to implement some depencency. 

However the Linux init.d scripts then eventually it was replaced/superseded with real 'dependency rules' with system.d which is the right thing to do, but too much of an effort. So I don't actually know which route to take.

**Comment by mingwandroid** [comment]
My proposal is to respect the dependencies and run the activation scripts in that order.

**Comment by rainwoodman** [comment]
Your proposal will require conda to be able to tell the owner package of individual files. I don't think it can do this.

I can file a PR to run the files in alphabetical order if you'd like -- not quite there but it will at least make sure the order is deterministic.

**Comment by mingwandroid** [comment]
Conda absolutely can tell the owner for each file except in the case of ambiguity in which case just talking the first is fine.  Search for which_package in conda-build (look like my fork for a much faster version).

**Comment by mingwandroid** [comment]
Please look through the conda source code instead of asking me to do the same.

**Comment by mingwandroid** [comment]
@kalefranz, making sure you are aware of this discussion incase you have any objections to this idea or can provide and assistance to @rainwoodman

**Comment by rainwoodman** [comment]
I will. I was asking just in case if anyone already knew where to look. It's a pretty big code base already.

**Comment by mingwandroid** [comment]
Sure. I rarely hack on `conda` itself as there's too much work for me to do on the `Anaconda Distribution` side of things.

**Comment by rainwoodman** [comment]
The hook shall be around LinkUnLinkActions. Perhaps added as an Action.

However an alternative way of assembling activate-order is to use post-link action scripts in the packages that provides activate.d scripts. I feel this is a cleaner design because the behaviour of conda does not `depend` on the content of the package beyond meta.yaml.

when post-link occurs the package is already listed in conda-list. So if we ship a shell script with conda that rebuilds activate-order, then those that provides activate.d scripts can call the script in post-link and pre-link.

**Comment by rainwoodman** [comment]
Another quirk of the activate scripts. If a compiler package is not immediately enabled after it is installed. The environment must be reactivated. There is no way to get this working as expected.

**Comment by mingwandroid** [comment]
Conda 4.4 addresses this as best it can AFAIK or at least it is now able to do something about it. For this `conda` had been changed into a shell function.

**Comment by kalefranz** [comment]
Just now catching up on some of these issues and seeing this.

For activate and deactivate, we have to be particularly careful about operations that will start to take a lot of time.  If we expect users to use activate consistently, it needs to be *fast*.

In 4.4, one of the things I wanted to do, but didn't get done, was add a json file in `conda-meta` that held various information about the environment's current state.  One thing for sure was going to be the topo sort order of all packages installed in that environment.  That field would be actively managed anytime there was a change to the environment.

If packages used the convention that their scripts in the `activate.d` and `deactivate.d` directories were named the same as the package, then it would be pretty straight forward to execute in the correct order based on just the topo-sorted list of packages.

We could go a step further in complexity and start recording in that file the exact order of all scripts to run for activate and deactivate.

I also mentioned somewhere else today that we're going to fairly soon run into issues with only having `.sh` and `.bat` scripts for activate and deactivate.  We're having more and more users of csh variants, fish, and Powershell.  Or people who want to use those shells at least.  Not to mention xonsh, which in 4.4 already has a supported wrapper within conda.

I think it's going to force us to work out a DSL or something similar that lets us manage environment variables in a more shell-agnostic way.

**Comment by rainwoodman** [comment]
For example, a python script that can be called and returns the new
environment as a dictionary, and defines its dependency via subclassing?

```

from conda.runtenv import forpackage, getenv

@forpackage('gcc-linux-64')
class env(getenv('binutils-linux-64')):
   def activate(...):
        return dict(....)

   def dectivate(...):
        return dict(....)

```

I bet there can be better names for the decorators.

**Comment by kalefranz** [comment]
Pretty much exactly what you propose with a convention for python function names would be the natural choice. However, there could come a time in the not-so-distant future where we start to transition conda to a compiled language. So in that case we don’t necessarily have the assumption that a python interpreter is available.

I’m still struggling here to think through what’s best both mid- and long-term.

**Comment by rainwoodman** [comment]
I initially thought about but then vetoed the convention for python function names because package names is not a subset of the names of a python classes. e.g if a package name starts with a [0-9]? 

In any case the compiled conda shall come with a Python API anyways, so it is probably not too bad to have activation scripts that depend on python -- bash is not for this sort of things, and coding up a new DSL, while fun, is redoing real work that's already been done.

**Comment by jakirkham** [comment]
Echoing what others have said about using topo sort. Also agree `conda-meta` is the right place to record this info. Like the idea of diffing changes as packages move.

Think the simplest optimization is not to reactivate if users only changed packages without activation scripts. Another optimization along these lines might be to reset the environment somehow instead of running deactivate scripts and then run activate scripts. There might be other tricks like this.

Taking a step back, historically we have discouraged activation scripts (particularly in c-f) and preferred options like patching hard coded paths for c-b to pick up. So there aren't lots of packages using activation (at least in c-f). So performance may be less of an issue than we think and the tricks mentioned above may already go a long ways.

>  I also mentioned somewhere else today that we're going to fairly soon run into issues with only having .sh and .bat scripts for activate and deactivate. We're having more and more users of csh variants, fish, and Powershell. Or people who want to use those shells at least. Not to mention xonsh, which in 4.4 already has a supported wrapper within conda.
>
> I think it's going to force us to work out a DSL or something similar that lets us manage environment variables in a more shell-agnostic way.

Interesting! Though this basically deserves it's own issue, right? Does it have one?

**Comment by mingwandroid** [comment]
We also discourage activation (and post-link and pre-unlink) but sometimes they are the best way to do things (or maybe the best given time constraints to patch around the need for them).

**Comment by kalefranz** [comment]
@jakirkham the issue you’re looking for is https://github.com/conda/conda/issues/6820

**Comment by kalefranz** [comment]
Also related is https://github.com/conda/conda/issues/5082
