### ISSUE TITLE
problem install gmaps on python/jupyter notebook with conda or with pip

### ISSUE THREAD

**Issue by naamahoresh** [conda/conda#6342]
i am trying to install the package but get an error while using the next commend:
conda install -c conda-forge gmaps 

I got an error and than run the commend with -v:
conda install -c conda-forge gmaps -v

and got the following report:

$ /bin/bash -x /home/naamah/anaconda3/bin/.gmaps-post-link.sh
==> cwd: /home/naamah/anaconda3/bin <==
==> exit code: 1 <==
==> stdout <==
b''
==> stderr <==
b'+ /home/naamah/anaconda3/bin/jupyter-nbextension enable gmaps --py --sys-prefix\nTraceback (most recent call last):\n  File "/home/naamah/anaconda3/bin/jupyter-nbextension", line 11, in <module>\n    sys.exit(main())\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance\n    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance\n    app.start()\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 988, in start\n    super(NBExtensionApp, self).start()\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start\n    self.subapp.start()\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 896, in start\n    self.toggle_nbextension_python(self.extra_args[0])\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python\n    logger=self.log)\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python\n    logger=logger)\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python\n    m, nbexts = _get_nbextension_metadata(module)\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata\n    m = import_item(module)\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item\n    return __import__(parts[0])\n  File "/home/naamah/anaconda3/lib/python3.5/site-packages/gmaps/__init__.py", line 6, in <module>\n    from gmaps.geocoding import Geocoding\nImportError: No module named \'gmaps.geocoding\'\n'

An error occurred while installing package 'conda-forge::gmaps-0.7.0-py35_0'.
LinkError: post-link script failed for package conda-forge::gmaps-0.7.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: /home/naamah/anaconda3/bin/.gmaps-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

===> REVERSING PACKAGE LINK: conda-forge::gmaps-0.7.0-py35_0 <===
  prefix=/home/naamah/anaconda3

===> REVERSING PACKAGE LINK: conda-forge::conda-4.3.29-py35_0 <===
  prefix=/home/naamah/anaconda3

===> REVERSING PACKAGE LINK: conda-forge::conda-env-2.6.0-0 <===
  prefix=/home/naamah/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::conda-env-2.6.0-h36134e3_1 <===
  prefix=/home/naamah/anaconda3

===> REVERSING PACKAGE UNLINK: defaults::conda-4.3.30-py35hf9359ed_0 <===
  prefix=/home/naamah/anaconda3

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.30
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : /home/naamah/anaconda3  (writable)
    default environment : /home/naamah/anaconda3
       envs directories : /home/naamah/anaconda3/envs
                          /home/naamah/.conda/envs
          package cache : /home/naamah/anaconda3/pkgs
                          /home/naamah/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.5.4 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1001:1001

`$ /home/naamah/anaconda3/bin/conda install -c conda-forge gmaps -v`
    Traceback (most recent call last):
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/home/naamah/anaconda3/bin/.gmaps-post-link.sh']' returned non-zero exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package conda-forge::gmaps-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /home/naamah/anaconda3/bin/.gmaps-post-link.sh
    ==> script messages <==
    <None>
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::gmaps-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /home/naamah/anaconda3/bin/.gmaps-post-link.sh
    ==> script messages <==
    <None>
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/home/naamah/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::gmaps-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /home/naamah/anaconda3/bin/.gmaps-post-link.sh
    ==> script messages <==
    <None>

**Comment by kalefranz** [comment]
This is a problem with the post-link script for the gmaps package, which you are getting from conda-forge.  Can't help you here on this issue tracker.  Go ahead an file an issue with conda-forge if you want.
