### ISSUE TITLE
Module installed but gives error on importing in Spyder

### ISSUE THREAD

**Issue by chahatupreti** [conda/conda#6349]
I recently installed [pybedtools](https://daler.github.io/pybedtools/main.html#quick-install-via-conda) in my Conda environment, using the command they mentioned - 

`conda install -c bioconda pybedtools`

But then when I activated spyder in this environment, and tried to run `import pybedtools` it gave me the error-

 `Modulenotfounderror: no module named 'pybedtools'`

I went back and tried to install using the module using `pip` too (`pip install pybedtools`) but it said that I already had it - 

`Requirement already satisfied: pybedtools in /anaconda3/envs/env1/lib/python3.5/site-packages
Requirement already satisfied: six in ./anaconda3/envs/env1/lib/python3.5/site-packages (from pybedtools)
`

So, I am unable to understand how it is that the module is installed but Spyder does not allow me to import it. I have never faced this issue with Anaconda before. Any help would be great!

**Comment by kalefranz** [comment]
I think you're using spyder wrong.  Unfortunately this is the conda issue tracker, not the spyder support forum.
