### ISSUE TITLE
`conda --help` does not show `conda activate` and `conda deactivate` info

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6353]
### What is the problem?

Currently, the main help page does not show `activate` or `deactivate`. 

### Why does this happen?

This happens because conda itself is not like most commands in that it must be installed into your shell profile for it to be used. When you call conda at the command line, you are actually invoking a shell function that finds and executes the write scripts. In these shell functions, `activate` and `deactivate` are treated differently than the other commands.

### How do we fix it?

To address this, we could potentially create some mock entries for "activate" and "deactivate" that would show up on the help page. Because these commands are intercepted and parsed first by shell functions, we do not have to worry about them being invoked instead of the real `activate` and `deactivate` commands (which are really just shell functions).

**Comment by kalefranz** [comment]
> Is the `source` style supposed to be deprecated at some point? If so when?

Yes.  

1. I'd like to get the `conda init` PR well behind us first.  
2. Then get the Anaconda and Miniconda installers doing whatever the right thing is at that point (i.e. *not* `export PATH`).  
3. Then put formal deprecation notices in `activate` / `deactivate` / `activate.bat` / `deactivate.bat` with all the officially correct and forevermore settled shell setup instructions.

And, if we get all of that landed prior to conda 5.0, then that's probably when we'll actually remove those four files.

**Comment by kalefranz** [comment]
Honestly, should we show both? Idk. We're in a little bit of limbo right now.  We really need this `conda init` stuff finalized.

If you're looking to beef up some help docs though, `conda activate --help` needs some... help

https://github.com/conda/conda/blob/b2915b97abea4cec509c6737eb4ddf30f05769ac/conda/activate.py#L175-L179

**Comment by derrickoswald** [comment]
+1
It is deceitful to not mention two of the main commands (activate & deactivate) in the help screen - especially for new users who rely on what documentation there is.

**Comment by dmd** [comment]
I just ran into this as well. I had a brain-fart and couldn't remember the literally most common thing I type, and then was stunned when the help mentions all sorts of commands I *never* use, but not the thing used most often.

**Comment by travishathaway** [comment]
@dmd, this is annoying and also related to how the command parsing for the application works. I updated the description of this issue today to provide more background on why this happens and a potentially way to fix it.
