### ISSUE TITLE
Unable to activate root environments from bash

### ISSUE THREAD

**Issue by edwardreed81** [conda/conda#6354]
#2869 seems to be this same issue, but it is claimed to be fixed and that issue is closed.

If I create a conda environment as the root user to share with all users on the system like `# conda create --name test --clone root`, I cannot activate that environment as a regular user from the bash shell.
    
    $ source activate test
    CondaEnvironmentError: Cannot activate environment bash.
    User does not have write access for conda symlinks.

It does work using the fish shell (`conda activate test`).

Fresh install of Anaconda3_5.0.1 in Ubuntu 16.04.

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.30
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /opt/anaconda3  (read only)
    default environment : /opt/anaconda3
       envs directories : /home/ereed/.conda/envs
                          /opt/anaconda3/envs
          package cache : /opt/anaconda3/pkgs
                          /home/ereed/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /opt/anaconda3/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-101-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1002:1002

EDIT: I did `chmod 777 /opt/anaconda3/bin/activate` and it fixed this. Then I changed it back to 775 and it remained fixed. I honestly have no idea what to say about that.

**Comment by kalefranz** [comment]
Activate has been completely reworked in conda 4.4.  It should solve this problem for you.  If not, let's re-open the issue.
