### ISSUE TITLE
Creating empty environment can trick user

### ISSUE THREAD

**Issue by sindrerb** [conda/conda#6359]
When creating an empty environment, as suggested by the documentation, a real gotcha is that installing by pip will install into the root environment. I suggest that the documentation be updated to warn the user. 

To clarify - when a user creates a new **empty** environment, pip is not installed into this environment, but is still linked from root. I can foresee new users installing conda, creating a new environment, and then installing their favourite package via pip, and consequently running into issues when the package cannot be found.

Previously, this was not an issue, since environments were created by `conda create --name myenv PACKAGE`, which wasn't very intuitive, but prevented an empty environment from being created.

**Comment by kalefranz** [comment]
I agree that we need a good tutorial about `type -a` and `which -a` on unix-like systems, and `where` on windows.  Mind suggesting that in https://github.com/conda/conda-docs ?
