### ISSUE TITLE
Support for environment activation/deactivation on Cygwin

### ISSUE THREAD

**Issue by rivokl** [conda/conda#6361]
On Cygwin, a `source activate` followed by a `source deactivate` breaks bash and zsh, the PATH is lost, even `ls` is a command not found. Upon issuing the deactivation command, a CondaValueError is reported 

> CondaValueError: Could not find environment: /cygdrived:\Miniconda3

A possible solution from Richard Pelvin can be found on this [thread](https://stackoverflow.com/questions/45095500/conda-activate-deactivate-environment-breaking-path/47043344#47043344). I think the bugs should be easy to fix based on his work (See snippets [here](https://bitbucket.org/snippets/plevin/xon8rb/activatecygwin-anaconda-activate-script) and [there](https://bitbucket.org/snippets/plevin/BprGro/deactivatecygwin-anaconda-deactivate))

By the way, I don't know where in the ~~hell~~ code base one can apply those fixes. Where are these two files located?

**Comment by kalefranz** [comment]
Should be fixed in conda 4.4.
