### ISSUE TITLE
Installing numpy and scikit-learn together "downgrades" to python 2.7

### ISSUE THREAD

**Issue by eric-wu** [conda/conda#6372]
This is for conda version 4.3.30 x86_64 running on a Debian box.

After conda is installed, the python binary points at `~/miniconda3/bin/python`. The python version is 3.6.3.

I can create an environment without specifying the python version, e.g. `conda create --name my-env`.  Once the environment is created,  activate my-env. Within my-env, the python binary still points at `~/miniconda3/bin/python` and it is python 3.6.3.

Now, in this empty environment, if I install numpy and scikit-learn together like so `conda install numpy scikit-learn`, it will install python 2.7 into the environment.  However, installing the same two packages separately does not "downgrade" python.

This behavior does not seem to be consistent with the conda documentation.

**Comment by tyler-thetyrant** [comment]
Yup, I was able to reproduce on Debian and centos7, but not on OSX.

This results in import error for numpy and scikit as the python3 is set as the default python within the environment. 

However, a quick solution would be installing them as you create the environment. You can run `conda create -n my-env python=3 numpy scikit-learn` 

```
root@119277c8e8a9:/# source activate test
(test) root@119277c8e8a9:/# python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 27 2017, 19:41:01)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(test) root@119277c8e8a9:/# conda install numpy scikit-learn
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /usr/local/envs/test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2017.11.5-py27h71e7faf_0
    intel-openmp:    2018.0.0-hc7b2577_8
    libedit:         3.1-heed3624_0
    libffi:          3.2.1-hd88cf55_4
    libgcc-ng:       7.2.0-h7cc24e2_2
    libgfortran-ng:  7.2.0-h9f7466a_2
    libstdcxx-ng:    7.2.0-h7a57d05_2
    mkl:             2018.0.1-h19d6760_4
    ncurses:         6.0-h9df7e31_2
    numpy:           1.13.3-py27hbcc08e0_0
    openssl:         1.0.2m-h26d622b_1
    pip:             9.0.1-py27ha730c48_4
    python:          2.7.14-hdd48546_24
    readline:        7.0-ha6073c6_4
    scikit-learn:    0.19.1-py27h445a80a_0
    scipy:           1.0.0-py27hf5f0f52_0
    setuptools:      36.5.0-py27h68b189e_0
    sqlite:          3.20.1-hb898158_2
    tk:              8.6.7-hc745277_3
    wheel:           0.30.0-py27h2bc6bb2_1
    zlib:            1.2.11-ha838bed_2

Proceed ([y]/n)? y

**Comment by eric-wu** [comment]
You are right. The workaround I ended up using is to create the env **specifying the python version explicitly**, `create -n my-env python=3.6`. Note the difference here is that it installs python 3 and a bunch of other python packages into the environment. Whereas `create -n my-env` creates an empty environment with no packages in it.

**Comment by kalefranz** [comment]
Guessing this was a temporary packaging metadata issue?  Sure have it fixed by now, no?
