### ISSUE TITLE
#An unexpected error @ Current conda install:

### ISSUE THREAD

**Issue by Gili12** [conda/conda#6375]
platform : win-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (read only)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\Users\Gili\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda2\envs
                          C:\Users\Gili\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Gili\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Gili\.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.16299
          administrator : unknown

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py create -n py36 python=3.6 anaconda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 374, in install
        print(print_activate(args.name if args.name else prefix))
    IOError: [Errno 2] No such file or directory

**Comment by kalefranz** [comment]
Please `conda update conda`.  If you still have similar problems, go ahead and file a new issue.
