### ISSUE TITLE
Calling python in test-env defaults to /usr/python

### ISSUE THREAD

**Issue by jonoave** [conda/conda#6376]
Hello, 

Firstly excuse me for the noob-like question. 
The default python call on my system brings out python 3.4.6.
I want to run something in a test_env with python 2.7.6

So I tried the following:
    conda create -n test_env python=2.7.6
    conda activate test_env
    (test_env) user@molev-32-56:~$ which python
    /home/user/anaconda3/envs/test_env/bin/python

Which looks fine, but if I try to call python:
    (test_env) user@molev-32-56:~$ python --version 
    Python 3.4.6
    (test_env) junhoe@molev-32-56:~$ python
    Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] on linux
   
the python in /home/user/anaconda3/envs/test_env/bin/ is correctly installed as 2.7.6. I thought the purpose of creating an environment is that I can call python that defaults to the test environment? Or is there something wrong with the paths in my bashrc file?

Thanks.

**Comment by kalefranz** [comment]
Try `hash -r` after `conda activate`.  You shouldn't need it, but maybe you have an old shell?
