### ISSUE TITLE
Conda does not tolerate spaces in path

### ISSUE THREAD

**Issue by ARF1** [conda/conda#638]
Conda does not seem to tolerate spaces in paths. See the message"The filename, directory name, or volume label syntax is incorrect." in the log below:
# 

Microsoft Windows [Version 5.2.3790](C) Copyright 1985-2003 Microsoft Corp.

C:\Documents and Settings\A F>conda info
Current conda install:

```
         platform : win-32
    conda version : 3.0.6
   python version : 2.7.6.final.0
 root environment : C:\Documents and Settings\A F\Anaconda  (writable
```

)
  default environment : C:\Documents and Settings\A F\Anaconda
     envs directories : C:\Documents and Settings\A F\Anaconda\envs
        package cache : C:\Documents and Settings\A F\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/pro/win-32/
          config file : None
    is foreign system : False

C:\Documents and Settings\A F>conda update conda

Package plan for installation in environment C:\Documents and Settings\A F\Anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| conda-3.4.0 | py27_0         123 KB |

The following packages will be UN-linked:

| package | build |
| --- | --- |
| conda-3.0.6 | py27_0 |

The following packages will be linked:

| package | build |
| --- | --- |
| conda-3.4.0 | py27_0   hard-link |

Proceed ([y]/n)? y

Fetching packages ...
conda-3.4.0-py27_0.tar.bz2 100% |###################| Time: 0:00:00 131.44 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
The filename, directory name, or volume label syntax is incorrect.

C:\Documents and Settings\A F>

**Comment by mmcdermott** [comment]
I've seen a similar issue when trying to create an environment whose name has spaces on linux: 
```
...:~$ conda create --name ML\ Sandbox\ 3.5 --clone tensorflow3.5
Source:      /home/.../miniconda3/envs/tensorflow3.5
Destination: /home/.../miniconda3/envs/ML Sandbox 3.5
Packages: 53
Files: 79
cp: target '3.5/lib/libcrypto.so.1.0.0-tmp' is not a directory
mv: target '3.5/lib/libcrypto.so.1.0.0' is not a directory
/home/.../miniconda3/envs/ML Sandbox 3.5/bin/.openssl-post-link.sh: line 7: /home/.../miniconda3/envs/ML: No such file or directory
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'defaults::openssl-1.0.2j-0'.
LinkError: Link error: Error: post-link failed for: defaults::openssl-1.0.2j-0 

Attempting to roll back.


LinkError: Link error: Error: post-link failed for: defaults::openssl-1.0.2j-0 
```

The error text seems to indicate there is a string escaping issue within conda directly; it accepts an environment name with spaces during creation, but then does not escape those spaces in future reference, which ends up muddling directory and file names. In my case, the desired environment name was `ML Sandbox 3.5` and conda reported an error `/home/.../miniconda3/envs/ML: No such file or directory` and `3.5/lib/libcrypto.so.1.0.0-tmp`

**Comment by kalefranz** [comment]
That particular error happened from a bash post-link script.

    LinkError: Link error: Error: post-link failed for: defaults::openssl-1.0.2j-0 

Conda really doesn't have any control of the code that goes in there.  It's all just arbitrary bash code.  If the script fails, the only thing conda can do is tell you about it.

**Comment by kalefranz** [comment]
Conda is now tested with spaces in paths.  From conda's perspective, spaces should be fine as of conda 4.4, if not earlier.

**Comment by ijstokes** [comment]
How about `conda build`? @bradbur has seen problems with this on a Mac where his home directory has a space in it.  He could provide a (redacted) trace.

**Comment by mcallaway** [comment]
I still see this bug happening on conda 4.9.2:

    > file ./python3-config
    ./python3-config: a /Users/mcallawa/PyCharm Projects/First Project/env/bin/python3.8 script text executable, ASCII text
    
    > ./python3-config
    bash: ./python3-config: /Users/mcallawa/PyCharm: bad interpreter: Permission denied

Destroying the ./env and remaking it without spaces in the directory structure makes it work.

This is on Mac OSX 10.15.7 with a new `brew install --cask miniconda` setup.
