### ISSUE TITLE
install geopandas fail!

### ISSUE THREAD

**Issue by yanhzz** [conda/conda#6387]
HUANGYANdeMacBook-Pro:~ huangyan$ pip install geopandas;
Requirement already satisfied: geopandas in /anaconda/lib/python2.7/site-packages
Requirement already satisfied: pandas in /anaconda/lib/python2.7/site-packages (from geopandas)
Requirement already satisfied: shapely in /anaconda/lib/python2.7/site-packages (from geopandas)
Requirement already satisfied: fiona in /anaconda/lib/python2.7/site-packages (from geopandas)
Requirement already satisfied: descartes in /anaconda/lib/python2.7/site-packages (from geopandas)
Requirement already satisfied: pyproj in /anaconda/lib/python2.7/site-packages (from geopandas)
Requirement already satisfied: python-dateutil in /anaconda/lib/python2.7/site-packages (from pandas->geopandas)
Requirement already satisfied: pytz>=2011k in /anaconda/lib/python2.7/site-packages (from pandas->geopandas)
Requirement already satisfied: numpy>=1.7.0 in /anaconda/lib/python2.7/site-packages (from pandas->geopandas)
Requirement already satisfied: cligj in /anaconda/lib/python2.7/site-packages (from fiona->geopandas)
Requirement already satisfied: click-plugins in /anaconda/lib/python2.7/site-packages (from fiona->geopandas)
Requirement already satisfied: enum34 in /anaconda/lib/python2.7/site-packages (from fiona->geopandas)
Requirement already satisfied: munch in /anaconda/lib/python2.7/site-packages (from fiona->geopandas)
Requirement already satisfied: six in /anaconda/lib/python2.7/site-packages (from fiona->geopandas)
Requirement already satisfied: matplotlib in /anaconda/lib/python2.7/site-packages (from descartes->geopandas)
Requirement already satisfied: click>=4.0 in /anaconda/lib/python2.7/site-packages (from cligj->fiona->geopandas)
Requirement already satisfied: functools32 in /anaconda/lib/python2.7/site-packages (from matplotlib->descartes->geopandas)
Requirement already satisfied: subprocess32 in /anaconda/lib/python2.7/site-packages (from matplotlib->descartes->geopandas)
Requirement already satisfied: cycler>=0.10 in /anaconda/lib/python2.7/site-packages (from matplotlib->descartes->geopandas)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /anaconda/lib/python2.7/site-packages (from matplotlib->descartes->geopandas)
HUANGYANdeMacBook-Pro:~ huangyan$ conda install -c conda-forge geopandas
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /anaconda  (writable)
    default environment : /anaconda
       envs directories : /anaconda/envs
                          /Users/huangyan/.conda/envs
          package cache : /anaconda/pkgs
                          /Users/huangyan/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/huangyan/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

**Comment by kalefranz** [comment]
You didn't include the stack trace.  There's nothing I can do here without additional information.  If you still have a problem, please file a new issue.
