### ISSUE TITLE
Conda installation issue creating an environment based yml file

### ISSUE THREAD

**Issue by NormaH** [conda/conda#6388]
I am submitting this as suggested by Conda/Anaconda3.  Very strange, appreciate any guide on this. 
It appears the environment  gets installed in Windows 32 bit but I would expect the packaging within should run in 64 bit.  I have installed Spyder 3.2.4 but the package wants to run in 3.2.3 (backward?).

Anaconda 3 was installed in the computer less than 2 weeks ago.  

![conda -installation issue-12-2-17](https://user-images.githubusercontent.com/9207196/33528588-bb6d2298-d828-11e7-9efd-18b922f01a9c.jpg)

**Comment by NormaH** [comment]
I would like to add the following image showing that Conda is only searching in Window  32 bit channel, It is not offering options to install  OpenCV3 in Window 64 bit;
![capture-conda-search only 32 bit](https://user-images.githubusercontent.com/9207196/33572997-2dfd4564-d8fa-11e7-8b66-89d90063c636.GIF)

Please let me know how I can get the OpenCV3 to install; according to Anaconda 3  the environment set for its use has OpenCV3 already installed within, but when I import it from Spyder 3.2.3 IDE  (environment created by a yml file)  or  even in Spyder 3.2.4, the below  error is reported:  
 
  File "<ipython-input-1-4618487bd3ff>", line 1, in <module>
    import opencv3

ImportError: No module named 'opencv3'

**Comment by NormaH** [comment]
HI 
I  was able to have the CV2  module in Spyder/Python  after  
install -c conda-forge opencv  import CV2 

It was installed after doing a   conda update conda    (it reported the  updates as shown below):
  
![conda update no updating 12-6-17](https://user-images.githubusercontent.com/9207196/33801616-fb869c22-dd25-11e7-9608-d7a4b9b8c97f.png)

It appears Conda  may not hold the updated libraries/packages even when Anaconda Navigator shows the specific packages are installed for an specific environment.   Thanks

**Comment by kalefranz** [comment]
Great.  Sounds like you resolved your issue!
