### ISSUE TITLE
Be more descriptive about what's pinned

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#6399]
Just read the blog post and a lot of the improvements sound great! One thing I'm a little concerned about is the behaviour described below:
> *For example, executing `conda install conda-forge::scikit-learn` will confine all future changes to the scikit-learn package in the environment to the conda-forge channel, until the spec is changed again*

This isn't what I would want to happen by default when I choose to install from a particular channel. It seems to me to be conflating two separate concerns - installing from a particular channel and pinning a package to a particular channel. I don't think the latter should happen (by default) just because you want to do the former. 

I think channel pinning should be opt-in - e.g. `conda install conda-forge::scikit-learn --pin-channel` rather than implicit.

I suppose that it's not a big deal if there's an easy way to unpin the channel after installing from a particular channel. Does such a method exist? Also, xref #2978 - is there any documentation of this?

**Comment by kalefranz** [comment]
It's the whole user-requested spec that's recorded, not just channel.  Another example is something like `conda install python=2.7`.  The user-requested history for that spec is now preserved, and for the python package, we'll respect that spec until it's overridden by a subsequent request.

All part of the consistent theme of recognizing the difference between packages explicitly requested by users (and the specs through which those packages were brought in), and packages that are part of an environment only to satisfy dependencies.

There are plenty of ways to *not* pin channels.  The way you'd get scikit-learn from conda-forge in conda 4.3 is

    conda install -c conda-forge scikit-learn

which hasn't changed in conda 4.4, and that of course won't pin the channel.  So what most users would consider the "default" behavior, the parts in conda 4.4 that aren't additive beyond 4.3, all work the same.

> This isn't what I would want to happen by default when I choose to install from a particular channel. It seems to me to be conflating two separate concerns - installing from a particular channel and pinning a package to a particular channel.

In the above, would it still be true for you if you replaced the word "channel" with "version"? How about "subdir"?

**Comment by kalefranz** [comment]
> I suppose that it's not a big deal if there's an easy way to unpin the channel after installing from a particular channel.

If you run `conda install conda-forge::scikit-learn`, any update to the spec for that package name will override the previous recorded spec.  So `conda update -all`, `conda update scikit-learn`, and `conda install scikit-learn` will all drop the previous spec.

Documentation definitely needs to be updated for conda 4.4.  The problem with our documentation right now is that it's not versioned, so until we actually release conda 4.4, we'd have an issue where the documentation tells people about a capability that doesn't exist if they're running conda 4.3.  It's a problem for sure.  Something we'd really like to get fixed.

**Comment by dhirschfeld** [comment]
Because I have `channel_priority: false` 
```
conda install -c conda-forge scikit-learn
```
won't necessarily install from `conda-forge` - the above will only add `conda-forge` as a channel to search for the latest version and the latest version from whatever channel will be installed. To install from a specific channel I'd have to also add `--override-channels`

> *Would it still be true for you if you replaced the word "channel" with "version"?*

Absolutely! When I choose to install a particular version of a package I don't want that to automatically pin the package to that version. To me installing is separate from pinning whether that's installing a particular version / pinning a package to a particular version or installing from a particular channel / pinning a package to a particular channel. In each case I don't want the install operation to be conflated with the pinning operation.

Python is a good counter-example - if I install a particular python version I probably really do want it pinned at least to the minor version. I can't think of another package though where I'd want automatic pinning.

**Comment by dhirschfeld** [comment]
I guess I'm not understanding what *"the spec"* of a package refers to.

> *So `conda update -all`, `conda update scikit-learn`, and `conda install scikit-learn` will all drop the previous spec.*

...seems to directly contradict:

> *For example, executing `conda install conda-forge::scikit-learn` will confine all future changes to the scikit-learn package in the environment to the conda-forge channel, until the spec is changed again*

modulo the caveat about "the spec".  

Your statement at the top suggests that `conda install conda-forge::scikit-learn` followed by `conda update scikit-learn` would update `scikit-learn` from *any* channel because the latter update command dropped the spec? Is that correct? If so, what *"future changes"* are then confined to the `conda-forge` channel? :confused:

**Comment by dhirschfeld** [comment]
Yeah, I've previously brought up the documentation versioning issue - https://github.com/conda/conda/issues/5650

IMHO It would be very useful to have versioned docs.

**Comment by dhirschfeld** [comment]
Despite this issue I've upgraded to `4.4.6` as it fixes several other issues I'm running into.

To be able to manage my environment properly what I'd like now is a command `conda list pinned` which listed all packages which were either pinned to a particular version or a particular channel.

When I do an update all conda says I'm up-to-date:
```
λ conda update --all
Solving environment: done

# All requested packages already installed.
```
...but if conda has surreptitiously pinned some packages to a particular channel that may not actually be the case so I'd like a command to be able to check that, and then have an unpin command in case conda had decided to implicitly pin any channels.

**Comment by kalefranz** [comment]
Perhaps in the output of `conda list`, we should show the spec associated with a package, if there is one (i.e. if it was user requested, pinned, etc).

**Comment by dhirschfeld** [comment]
Sounds good. Extra info could be hidden behind a --verbose flag or some such. 

A (humsn-readable) timestamp would be a good candidate to be included too!
