### ISSUE TITLE
Can't install conda development version

### ISSUE THREAD

**Issue by nouiz** [conda/conda#6403]
I want to modify conda to better suite our need. For this I followed the instruction at:

https://github.com/conda/conda#contributing

But this give me this error:

"""
Traceback (most recent call last):
  File "/home/bastienf/miniconda2/bin/conda", line 11, in <module>
    load_entry_point('conda', 'console_scripts', 'conda')() 
  File "/home/bastienf/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point 
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/bastienf/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2750, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'conda') not found
"""

Are those instruction up to date? I did this on an installation of miniconda2 version 4.3.30

**Comment by sdvillal** [comment]
I'm also curious regarding what is best practice to have a conda development environment. I personally looked at several examples in the conda repo, and ended up using *utils/functions.sh* to get me there (```install_conda_dev``` is most useful).

**Comment by sdvillal** [comment]
Just found also this: https://github.com/conda/conda/issues/6160.

**Comment by nouiz** [comment]
Thanks for pointing to the other issue. Using "python -m conda ..." allow me to use my cloned version of conda.
