### ISSUE TITLE
conda 4.4 hangs after "solving environment"

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#6406]
I followed instructions from here https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/
to get conda 4.4

My conda history: Was using exclusively conda-forge (well, i had conda-forge on top of my channels, and the defaults below.

Executed commands to get conda 4.4:

```bash
$ conda config --add channels conda-canary
$ conda update conda
$ conda config --system --add pinned_packages conda-canary::conda
```

then put this in my .zprofile:

```bash
. /Users/klay6683/miniconda3/etc/profile.d/conda.sh
```
withOUT the recommended "conda activate base" because I like to have my default environment to be NOT root/base. Is that a problem? I thought it was frowned upon doing everday work in root/base? At least I corrupted more than one miniconda install doing so.

I have my iTerm2 profiles set up that each new terminal now executes "conda activate stable" and confirmed that it works correctly, e.g. paths are set correctly.

Then I executed a "conda update --all" in my main environment called "stable" (guess that's that? ;) 
and then I got feedback:
```bash
Solving environment: done (after a minuter or so)
[]
```
and then it's stuck at above box symbol.

How to debug?

**Comment by michaelaye** [comment]
This seems to be caused by my anti-virus program checking (Avira). Deactivating it created an appropriate response time after solving the environment (order of 5 s for approx 290 packages).

**Comment by matiasandina** [comment]
Deactivating Windows Defender also fix issue :)

**Comment by jayspeidell** [comment]
Can confirm that Windows Defender blocks conda. Had same issue, deactivating Windows Defender fixed it.

**Comment by HangsunKim** [comment]
Hi. I tried deactivating the Windows Defender and my other anti-virus program, but still I'm unable to do conda update.

**Comment by aspiringguru** [comment]
Found this thread with same problem.
Have Win 10 home version 1709, gpedit.msc not enabled in windows home. (really? mistake purchase, hating ms right now)

this page provided a batch file to enable gpedit.msc
gpedit.msc now accessible

tried these instructions to disable windows defender.
https://www.windowscentral.com/how-permanently-disable-windows-defender-windows-10
Computer Configuration > Administrative Templates > Windows Components > Windows Defender > double-click Turn off Windows Defender.

exit powershell, new instance of powershell. (not sure if this is required but good practice to open new shell)

conda update conda 

seems to run now, is slow, sat on 'solving environment : done' for several minutes, then displayed package plan, listed packages to be downloaded, packages to be installed, packages to be updated.  took 5-10 minutes on i7 laptop.

running conda update conda again gives message 'all requested packages  already installed'

re-enable windows defender before closing gpedit.msc

**Comment by kalefranz** [comment]
Please always provide output of `conda info` :)

**Comment by joseph-valles** [comment]
I'm getting the same problem on Ubuntu 16.04 headless. No antivirus installed to my knowledge. It just hangs after it solves the environment. It was working fine just a few minutes before. I checked my internet connection and the problem isn't with my internet.

`(base) paperspace@pshxsdi1t:~$ conda info

     active environment : base
    active env location : /home/paperspace/anaconda3
            shell level : 1
       user config file : /home/paperspace/.condarc
 populated config files : 
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/paperspace/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/paperspace/anaconda3/pkgs
                          /home/paperspace/.conda/pkgs
       envs directories : /home/paperspace/anaconda3/envs
                          /home/paperspace/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-83-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False`

**Comment by mmcdermott** [comment]
I have the same problem as @joseph-valles.

**Comment by kangqiwang** [comment]
Deactivating Windows Defender also fix issue :)
Cheers my friends

**Comment by mpschr** [comment]
Is there a workaround for Windows Machine where the user has no privileges to deactivate the defender?

**Comment by georgechen1** [comment]
I tried disabling windows defender but had the same problem still.
Any recs anyone?

**Comment by sephib** [comment]
Hi,
Having the same problem as @joseph-valles running on OpenSUSE

> (base) ds@linux-vnlc:~> conda info
> 
>      active environment : base
>     active env location : /home/ds/anaconda3
>             shell level : 1
>        user config file : /home/ds/.condarc
>       populated config files : /home/ds/.condarc
>           conda version : 4.5.11
>     conda-build version : 3.4.1
>          python version : 3.6.4.final.0
>        base environment : /home/ds/anaconda3  (writable)
>            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://conda.anaconda.org/ioos/linux-64
>                           https://conda.anaconda.org/ioos/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/linux-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>           package cache : /home/ds/anaconda3/pkgs
>                           /home/ds/.conda/pkgs
>        envs directories : /home/ds/anaconda3/envs
>                           /home/ds/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Linux/4.4.159-73-default opensuse/42.3 glibc/2.22
>                 UID:GID : 1000:100
>              netrc file : None
>            offline mode : False
>

**Comment by amjltc295** [comment]
I have the same problem as @joseph-valles. I think I did use ctrl+c to stop the installation process at some point.

**Comment by we10710aa** [comment]
Hi, I have the same problem, probably because of windows defender.
Installing  another antivirus solve problem for me

**Comment by dileepdail** [comment]
I tried with command "conda update conda" and it solved the issue.
