### ISSUE TITLE
Improve workflow for conda developers

### ISSUE THREAD

**Issue by danielballan** [conda/conda#6407]
In an effort to beta-test 4.4.0rc2, I followed these steps, inspired by [the conda-build Travis-CI configuration](https://github.com/conda/conda-build/blob/master/.travis.yml#L48-L57):

```
 wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
 rm -rf ~/miniconda3
 bash miniconda.sh -b -p $HOME/miniconda3
 export PATH="$HOME/miniconda3/bin:$PATH"
 hash -r
 conda config --set always_yes yes
 conda config --set auto_update_conda False
 conda update -q --all
 rm -rf $HOME/miniconda3/lib/python/site-packages/conda;
 rm -rf $HOME/miniconda3/lib/python/site-packages/conda*.egg-info;
 git clone --single-branch --depth 1000 https://github.com/conda/conda.git;
 pushd conda;
 $HOME/miniconda3/bin/python utils/setup-testing.py install;
 popd;
 hash -r;
 conda info;
```

It seems to have worked:

```
$ conda --version
conda 4.4.0rc2.post35+c72c237
$ which conda
/Users/dallan/miniconda3/bin/conda
```

Now, following [the instructions in this blog post](https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/) I went looking for `~/miniconda3/etc/profile.d/conda.sh` but only found a fish shell script:

```
$ ls ~/miniconda3/etc/
fish
```

Where should I expect to find `conda.sh`?

**Comment by nehaljwani** [comment]
Why not just `conda install -c conda-canary conda=4.4.0rc2`

**Comment by kalefranz** [comment]
The reason we can't have people `pip install conda` is because setup.py doesn't let us put files everywhere they need to be.  Use @nehaljwani's solution and you'll be set.

**Comment by danielballan** [comment]
Indeed, the instructions in the blog post, echoed by @nehaljwani, work as advertised. But I'm still not sure why ` $HOME/miniconda3/bin/python utils/setup-testing.py install` generated `conda.fish` but no `conda.sh`. It would be nice to have working dev-install instructions.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/6518 will substantially help with our dev workflow
