### ISSUE TITLE
quiet flag is too quiet and verbose flag is too verbose

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#6424]
I'm doing a `conda env update -f environment.yml` and logging the output. In the logs I don't want to see a  new line for each iteration of the progress bar but specifying `--quiet` means *no* output gets displayed.

It would be good to have some option in-between so I can see that something is actually happening without any useful information getting lost in progress-bar updates.

Maybe a `--no-progress` argument which just didn't display the progress bar would fit the purpose?

**Comment by kalefranz** [comment]
If using conda 4.4, try using a single `-v` instead of `--quiet`...  One `-v` is INFO level, two is DEBUG, and three is TRACE.  All three disable progress bar updates.  I'm guessing output at only the INFO level is at least forward progress for you...

**Comment by dhirschfeld** [comment]
Thanks, will close this since it sounds like it's addressed in the latest...

**Comment by dhirschfeld** [comment]
Without any flags every `#` in the spinner prints a new line which makes the logs far to verbose and makes finding any problems in the logs very difficult.

Specifying `-v` gets rid of the spinner but is also very verbose hence I'm reopening this issue to request an option to *only* disable the spinner but not print any extra information. All I want are the package names printed as they're installed and also any stderr output so I can both monitor the install as it's happening and easily identify any problems if they occurred.

**Comment by dhirschfeld** [comment]
Although, with `-v` it seems no information at all is printed about downloading the packages?

I'd also like to see the list of names of packages as they're downloaded so that I know something is actually happening.
