### ISSUE TITLE
conda 4.4.0rc: 'Not a conda environment' plus environments that shouldn't be there

### ISSUE THREAD

**Issue by wresch** [conda/conda#6445]
I have a python 3.6 root environment with conda 4.4.0rc2 installed in /usr/local/Anaconda/conda_root/3.6.  I sourced $CONDA_ROOT/etc/profile.d/conda.sh.

```shell
$ conda --version
conda 4.4.0rc2
$ conda info

     active environment : base
    active env location : /usr/local/Anaconda/conda_root/3.6
            shell level : 1
       user config file : /home/helixapp/.condarc
 populated config files : /usr/local/Anaconda/conda_root/3.6/.condarc
          conda version : 4.4.0rc2
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /usr/local/Anaconda/conda_root/3.6  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /usr/local/Anaconda/conda_root/3.6/pkgs
                          /home/$USER/.conda/pkgs
       envs directories : /usr/local/Anaconda/conda_root/3.6/envs
                          /home/$USER/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.0rc2 requests/2.14.2 CPython/3.6.2 Linux/3.10.0-693.2.2.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 31672:57823
             netrc file : None
           offline mode : False
```

### Issue 1
 `conda info --envs` and `conda env list` see environments outside of the envs directories
```shell
$ conda info --envs
# conda environments:
#
0.2.2                    /spin1/sys2/usrlocal/Anaconda/envs_app/crossmap/0.2.2
1.0.0                    /spin1/sys2/usrlocal/Anaconda/envs_app/iva/1.0.0
1.0.2                    /spin1/sys2/usrlocal/Anaconda/envs_app/iva/1.0.2
base                  *  /usr/local/Anaconda/conda_root/3.6
test                     /usr/local/Anaconda/conda_root/3.6/envs/test
R3.4                     /usr/local/Anaconda/envs/R3.4
py2.7                    /usr/local/Anaconda/envs/py2.7
py3.5                    /usr/local/Anaconda/envs/py3.5
```
`conda env list` returns the same result

We have many more environments which aren't seen. But it seems to me the only ones listed should be `base` and `test`.

### Issue 2
 `conda activate test` fails due to the existence of the directory `/home/$USER/test`

```shell
$ conda activate test
Not a conda environment: /home/$USER/test
$ ls -lhd /home/$USER/test
drwxr-xr-x 3 $USER group 4.0K Nov 23 10:56 /home/$USER/test
```
`conda activate /usr/local/Anaconda/conda_root/3.6/envs/test` works. 

This works fine for `/usr/local/Anaconda/conda_root/3.6/envs/c44testing`, because the name is unique:
```shell
$ conda activate c44testing
(c44testing)$ 
```

Why is `conda activate` looking in `$HOME` for names matching the environment name? `$HOME` is not in the list of environment directories (`$HOME`/.conda/envs is)

**Comment by kalefranz** [comment]
> `conda info --envs` and `conda env list` see environments outside of the envs directories

This is intentional and as-designed, so long as those paths are indeed conda environments.

Issue 2 needs a solution for sure though.

**Comment by wresch** [comment]
Thanks for looking at it Kale.

One question  about Issue 1:  we have several dozen environments under `/spin1/sys2/usrlocal/Anaconda`, our old anaconda tree. Why is it not finding them? Conversely, what are the limits of searching for environments? Will it look anywhere it has permissions? We have huge file systems and i'd like to prevent it from looking outside the envs directories in the configuration.

**Comment by kalefranz** [comment]
Are the environments all located in `/spin1/sys2/usrlocal/Anaconda/envs`, and is `/spin1/sys2/usrlocal/Anaconda/envs` listed as an envs directory with `conda info`?

**Comment by kalefranz** [comment]
On unix, if the process is running under UID 0, it'll scan all home directories for the `.conda/environments.txt` file.  Otherwise, just the current user's `~/.conda/environments.txt` file.  That, in addition to looking at whats configured for `envs_dirs`.

**Comment by kalefranz** [comment]
We figured that if you're root, you probably want to know of *all* conda environments that are on your system.  In case, for example, you wanted to see if openssl is out of date in any of them.

I supposed we could add a configuration parameter or flag or something like that if it becomes a problem.

**Comment by kalefranz** [comment]
#6447 closes this issue

**Comment by wresch** [comment]
Oh yeah - I'm an idiot. I forgot about ~/.conda/environments.txt.  That makes sense now. Thanks

**Comment by wresch** [comment]
I'm going to ping this one more time - with an empty `~/.conda/environments`, it now does not list environments in `envs_dirs` which is different behaviour from 4.3:

```shell
### ~/.conda/environments.txt is empty
(base) [Anaconda]$ vim ~/.conda/environments.txt

### conda info --envs only lists the base environment
(base) [Anaconda]$ conda info --envs
# conda environments:
#
base                 *    /usr/local/Anaconda/conda_root/3.6

### even though in the root's envs dir there exists a conda environment 
### named c44testing to which the user has full read/write access
(base) [Anaconda]$ conda config --show envs_dirs
envs_dirs:
  - /usr/local/Anaconda/conda_root/3.6/envs
  - /home/$USER/.conda/envs
(base) [Anaconda]$ ls -lh /usr/local/Anaconda/conda_root/3.6/envs
total 4.0K
drwxr-x--- 10 $USER $GROUP 4.0K Dec 13 12:48 c44testing

### and that environment can be activated by name only
(base) [Anaconda]$ conda activate c44testing
(c44testing) [Anaconda]$
```

**Comment by kalefranz** [comment]
Yeah I fixed that already in another of the PRs that’s hovering around about this topic. Will be in the next release.
