### ISSUE TITLE
Missing paraview binary in the Conda paraview package

### ISSUE THREAD

**Issue by bokertov** [conda/conda#6452]
I installed paraview in Miniconda on my linux desktop:
https://anaconda.org/conda-forge/paraview

However, there is only paraview-config under ~/miniconda3/bin/, and no binary "paraview".

Is this a bug?

**Comment by kalefranz** [comment]
You’ll have to file an issue with conda-forge for that. Best place would be under the issue tracker for that packafe’s feedstock.
