### ISSUE TITLE
Package is incompatible with itself?

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda#6453]
I got the following error
```python
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - bluesky 1.0.0 py35_0
Use "conda info <package>" to see the dependencies for each package.
```
This is during a build of the bluesky package. It seems that it didn't output the other packages were conflicting (@synapticarbors found some packages missing from conda-forge which were at fault). It would be nice if this was a bit more verbose about the exact problem.

**Comment by jakirkham** [comment]
Might want to link the log and state of the recipe (e.g. commit) just to help with reproducibility a bit.

**Comment by CJ-Wright** [comment]
Thats a good idea
build: https://circleci.com/gh/conda-forge/staged-recipes/22152?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
repo state: https://github.com/CJ-Wright/staged-recipes/blob/5264328211bb28e3db544a80a491df92589c1d18/recipes/bluesky/meta.yaml
