### ISSUE TITLE
Conda update conda error

### ISSUE THREAD

**Issue by partha1968** [conda/conda#6455]
I am using Anaconda 5.0.1 on windows 7 (32 bit).
I am getting the following error:
(C:\Users\Quant\Anaconda3) C:\Users\Quant>conda update conda
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pk
gs/main/win-32/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', por
t=443): Max retries exceeded with url: /pkgs/main/win-32/repodata.json.bz2 (Caus
ed by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at
0x0378C550>: Failed to establish a new connection: [Errno 11004] getaddrinfo fai
led',))",),)

(C:\Users\Quant\Anaconda3) C:\Users\Quant>conda list
# packages in environment at C:\Users\Quant\Anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36ha9200a3_0
alabaster                 0.7.10           py36hedafc74_0
anaconda                  5.0.1            py36h2419598_2
anaconda-client           1.6.5            py36hb3b9584_0
anaconda-navigator        1.6.9            py36hfabed4d_0
anaconda-project          0.8.0            py36h88395f3_0
asn1crypto                0.22.0           py36hee29ec9_1
astroid                   1.5.3            py36h3217d1f_0
astropy                   2.0.2            py36h5dd925f_4
babel                     2.5.0            py36h9773feb_0
backports                 1.0              py36hf8a4c8f_1
backports.shutil_get_terminal_size 1.0.0            py36h567543b_2
beautifulsoup4            4.6.0            py36h4361f19_1
bitarray                  0.8.1            py36hc06d7bf_0
bkcharts                  0.2              py36h41dda5e_0
blaze                     0.11.3           py36h70bead1_0
bleach                    2.0.0            py36h2453164_0
bokeh                     0.12.10          py36h6669f50_0
boto                      2.48.0           py36h2dece20_1
bottleneck                1.2.1            py36hd155fb5_0
bzip2                     1.0.6            vc14h31cfb99_1  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py36h922bf65_0
certifi                   2017.7.27.1      py36h8287e07_0
cffi                      1.10.0           py36h935798a_1
chardet                   3.0.4            py36hf2a9688_1
click                     6.7              py36hfb6b3c4_0
cloudpickle               0.4.0            py36h859eb6c_0
clyent                    1.2.2            py36h4dd741a_1
colorama                  0.3.9            py36he9a059a_0
comtypes                  1.1.2            py36h9d81d3a_0
conda                     4.3.30           py36h404fb56_0
conda-build               3.0.27           py36h3212714_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h5d0fd5b_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36h19a5d9b_0
cryptography              2.0.3            py36h011be45_1
curl                      7.55.1           vc14h8488bd0_3  [vc14]
cycler                    0.10.0           py36hd299a41_0
cython                    0.26.1           py36h9e8b7db_0
cytoolz                   0.8.2            py36hdaace5b_0
dask                      0.15.3           py36h5f84f4a_0
dask-core                 0.15.3           py36hea13c7f_0
datashape                 0.5.4            py36h801e743_0
decorator                 4.1.2            py36hac4cfca_0
distlib                   0.2.5            py36hada7309_0
distributed               1.19.1           py36hd80bbde_0
docutils                  0.14             py36h4cf9f97_0
entrypoints               0.2.3            py36hd26a89c_2
et_xmlfile                1.0.1            py36ha14dd7c_0
fastcache                 1.0.2            py36h41c7961_0
filelock                  2.0.12           py36h38d8215_0
flask                     0.12.2           py36h7a02084_0
flask-cors                3.0.3            py36h499a37b_0
freetype                  2.8              vc14hfa46bb4_0  [vc14]
get_terminal_size         1.0.0                h4b36c58_0
gevent                    1.2.2            py36h35b58af_0
glob2                     0.5              py36h850fbe3_1
greenlet                  0.4.12           py36hdfd23a0_0
h5py                      2.7.0            py36h2a75726_1
hdf5                      1.10.1           vc14h7c25517_0  [vc14]
heapdict                  1.0.0            py36hbd458ba_0
html5lib                  0.999999999      py36h3e19504_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hbe8e9fa_0  [vc14]
idna                      2.6              py36h787667b_1
imageio                   2.2.0            py36h74fbb4f_0
imagesize                 0.7.1            py36h8cc6c1c_0
intel-openmp              2018.0.0             hda8db3e_7
ipykernel                 4.6.1            py36h9617649_0
ipython                   6.1.0            py36h25a49e7_1
ipython_genutils          0.2.0            py36h011d6f9_0
ipywidgets                7.0.0            py36he7427df_0
isort                     4.2.15           py36h9892446_0
itsdangerous              0.24             py36h0eb04fb_1
jdcal                     1.3              py36hdee49d3_0
jedi                      0.10.2           py36he9c8e28_0
jinja2                    2.9.6            py36hcda7f41_1
jpeg                      9b               vc14h39a59fb_1  [vc14]
jsonschema                2.6.0            py36hc586ae5_0
jupyter                   1.0.0            py36h16e480c_2
jupyter_client            5.1.0            py36h1f9acbd_0
jupyter_console           5.2.0            py36hb66b1b8_1
jupyter_core              4.3.0            py36h576004c_0
jupyterlab                0.27.0           py36h65ec9ff_2
jupyterlab_launcher       0.4.0            py36h4890406_0
lazy-object-proxy         1.3.1            py36hfebf436_0
libiconv                  1.15             vc14h61b1384_5  [vc14]
libpng                    1.6.32           vc14hf267d31_3  [vc14]
libssh2                   1.8.0            vc14h91c0462_2  [vc14]
libtiff                   4.0.8           vc14h38eb8c7_10  [vc14]
libxml2                   2.9.4            vc14h3c340fd_5  [vc14]
libxslt                   1.1.29           vc14h4217bde_5  [vc14]
llvmlite                  0.20.0                   py36_0
locket                    0.2.0            py36h3eabf40_1
lockfile                  0.12.2           py36hbbd9834_0
lxml                      4.1.0            py36h1ef3e42_0
lzo                       2.10             vc14he4ef3e4_1  [vc14]
markupsafe                1.0              py36h3b07c4d_1
matplotlib                2.1.0            py36he33e573_0
mccabe                    0.6.1            py36ha34857b_1
menuinst                  1.4.10           py36h07c0980_0
mistune                   0.7.4            py36hd7f275d_0
mkl                       2018.0.0             hd024497_4
mkl-service               1.1.2            py36h10c1010_4
mpmath                    0.19             py36h16eb394_2
msgpack-python            0.4.8            py36h1581075_0
multipledispatch          0.4.9            py36hd8bd89d_0
navigator-updater         0.1.0            py36he13d301_0
nbconvert                 5.3.1            py36h5066f46_0
nbformat                  4.4.0            py36hfe36a2e_0
networkx                  2.0              py36h4a3a701_0
nltk                      3.2.4            py36h4f806ae_0
nose                      1.3.7            py36h732162c_2
notebook                  5.0.0            py36h95a442a_2
numba                     0.35.0             np113py36_10
numexpr                   2.6.2            py36h686ca0e_1
numpy                     1.13.3           py36h38e73f1_0
numpydoc                  0.7.0            py36he021ee4_0
odo                       0.5.1            py36h3d61389_0
olefile                   0.44             py36hb56be0d_0
openpyxl                  2.4.8            py36hc89560d_1
openssl                   1.0.2l           vc14h7709ba0_2  [vc14]
packaging                 16.8             py36h7c26a67_1
pandas                    0.20.3           py36h93e7217_2
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36hbaae778_1
partd                     0.3.8            py36h9032c1e_0
path.py                   10.3.1           py36hecbadf8_0
pathlib2                  2.3.0            py36hebc6caf_0
patsy                     0.4.1            py36h8a8f1ce_0
pep8                      1.7.0            py36h68eb8c5_0
pickleshare               0.7.4            py36he181f7f_0
pillow                    4.2.1            py36hc1b3d4a_0
pip                       9.0.1            py36h09019dc_3
pkginfo                   1.4.1            py36h6186838_1
ply                       3.10             py36h9282218_0
progress                  1.3              py36h646ed32_0
prompt_toolkit            1.0.15           py36ha226939_0
psutil                    5.4.0            py36h7b2e820_0
py                        1.4.34           py36h5d7abe8_1
pycodestyle               2.3.1            py36h265b76b_0
pycosat                   0.6.2            py36h06ed0df_1
pycparser                 2.18             py36h315bf61_1
pycrypto                  2.6.1            py36h08e4588_1
pycurl                    7.43.0           py36he5719a0_3
pyflakes                  1.6.0            py36h66794c8_0
pygments                  2.2.0            py36h1a04f08_0
pylint                    1.7.4            py36heac34a7_0
pyodbc                    4.0.17           py36h458d450_0
pyopenssl                 17.2.0           py36h2105193_0
pyparsing                 2.2.0            py36h9ef7486_1
pyqt                      5.6.0            py36h13ac1a8_5
pysocks                   1.6.7            py36hbb234f4_1
pytables                  3.4.2            py36h4b11fb6_2
pytest                    3.2.1            py36h842b08d_1
python                    3.6.3                h28e8c7f_1
python-dateutil           2.6.1            py36h507c767_1
pytz                      2017.2           py36h6ca8096_1
pywavelets                0.5.2            py36hf262123_0
pywin32                   221              py36heebab90_0
pyyaml                    3.12             py36h624d9f2_1
pyzmq                     16.0.2           py36h450087d_2
qt                        5.6.2           vc14h6f76a7e_12  [vc14]
qtawesome                 0.4.4            py36h6b33ce7_0
qtconsole                 4.3.1            py36h86495bc_0
qtpy                      1.3.1            py36hc5ff042_0
requests                  2.18.4           py36h964142b_1
rope                      0.10.5           py36h3c8b003_0
ruamel_yaml               0.11.14          py36h1a6402c_2
scikit-image              0.13.0           py36h32d7ed4_1
scikit-learn              0.19.1           py36hb0057d7_0
scipy                     0.19.1           py36hfc7e94f_3
seaborn                   0.8.0            py36h5f15cc2_0
setuptools                36.5.0           py36h7f22f53_0
simplegeneric             0.8.1            py36h295c9ac_0
singledispatch            3.4.0.3          py36h2687f66_0
sip                       4.18.1           py36h0e39f04_2
six                       1.11.0           py36h7f2c006_1
snowballstemmer           1.2.1            py36h5e2b779_0
sortedcollections         0.5.3            py36hd1c3950_0
sortedcontainers          1.5.7            py36h4eaf07f_0
sphinx                    1.6.3            py36h9a8bd83_0
sphinxcontrib             1.0              py36h3cc09c9_1
sphinxcontrib-websupport  1.0.1            py36h10e879d_1
spyder                    3.2.4            py36h4570d2d_0
sqlalchemy                1.1.13           py36h5c218a5_0
sqlite                    3.20.1           vc14hf772eac_1  [vc14]
statsmodels               0.8.0            py36h2172a75_0
sympy                     1.1.1            py36hba5725f_0
tblib                     1.3.2            py36h96aaa60_0
testpath                  0.3.1            py36ha9283f1_0
tk                        8.6.7            vc14h051b162_1  [vc14]
toolz                     0.8.2            py36he12a8a7_0
tornado                   4.5.2            py36hfd51417_0
traitlets                 4.3.2            py36h0dbcc04_0
typing                    3.6.2            py36h9649c0b_0
unicodecsv                0.14.1           py36h238903e_0
urllib3                   1.22             py36hf0c4117_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123           hd4c4e62_2
wcwidth                   0.1.7            py36hc8ec93f_0
webencodings              0.5.1            py36hf0a7dc3_1
werkzeug                  0.12.2           py36h5b09e35_0
wheel                     0.29.0           py36h442dda1_1
widgetsnbextension        3.0.2            py36h98546b4_1
win_inet_pton             1.0.1            py36h6b5aef5_1
win_unicode_console       0.5              py36ha08cfaa_0
wincertstore              0.2              py36hcdd9a18_0
wrapt                     1.10.11          py36h084cbfa_0
xlrd                      1.1.0            py36he7b893d_1
xlsxwriter                1.0.2            py36hde92fec_0
xlwings                   0.11.4           py36h89f095e_0
xlwt                      1.3.0            py36hb79324b_0
yaml                      0.1.7            vc14h188b4a1_1  [vc14]
zict                      0.1.3            py36hf291af1_0
zlib                      1.2.11           vc14h902601c_1  [vc14]

please help

**Comment by kalefranz** [comment]
Flakey network connection.
