### ISSUE TITLE
Issue installing Spyder in python 2.7 (32 bit) virtual environment 

### ISSUE THREAD

**Issue by sayboltm** [conda/conda#6461]
Created a virtual environment for Python 2.7 and 32 bit using set CONDA_FORCE_32BIT=1

Usually for errors like this I think needs admin rights, but nothing I am doing should need admin rights and following least level of privilege as possible, I do not want to do that unless it is really needed. If so, please describe why and which executable needs it.

-----------------------------------------

DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\CZ3QFP\miniconda2\envs\spyderDev_27_32', env_name: 'spyderDev_27_32', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\CZ3QFP\miniconda2\pythonw.exe, args are [u'C:\\Users\\CZ3QFP\\miniconda2\\cwp.py', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32\\pythonw.exe', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\CZ3QFP\miniconda2\python.exe, args are [u'C:\\Users\\CZ3QFP\\miniconda2\\cwp.py', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32\\python.exe', u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32\\Scripts\\spyder-script.py', u'--reset']
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\Users\CZ3QFP\miniconda2  (writable)
    default environment : C:\Users\CZ3QFP\miniconda2\envs\spyderDev_27_32
       envs directories : C:\Users\CZ3QFP\miniconda2\envs
                          C:\Users\CZ3QFP\AppData\Local\conda\conda\envs
                          C:\Users\CZ3QFP\.conda\envs
          package cache : C:\Users\CZ3QFP\miniconda2\pkgs
                          C:\Users\CZ3QFP\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\CZ3QFP\miniconda2\Scripts\conda install spyder`

    Traceback (most recent call last):
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\instructions.py", line 95, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
      File "C:\Users\CZ3QFP\miniconda2\lib\site-packages\conda\common\compat.py", line 118, in open
        closefd=closefd)
    IOError: [Errno 13] Permission denied: u'C:\\Users\\CZ3QFP\\miniconda2\\envs\\spyderDev_27_32\\Scripts\\conda'

**Comment by kalefranz** [comment]
If you've used admin privileges with conda once, you'll oftentimes need to do it in the future.  Easiest solution is to install conda as single-user so those permissions don't get crossed.  Conda does support multi-user, but there's not enough information here to really be helpful.
