### ISSUE TITLE
"--no-channel-priority" has no effect on build number

### ISSUE THREAD

**Issue by sscherfke** [conda/conda#6464]
The `--no-channel-priority` cmd line flag (and the `channel_priority: false` setting) only affect the version numbers, but not the build numbers, which is IMHO unexpected and should be fixed.

Suppose you have two channels *A* and *B* with the following packages:

## Channels

**A**
- spam-1.0-py36_0
- eggs-1.0-py36_0

**B**
- spam-1.1-py36_0
- eggs-1.0-p36_1

## Installation with channel priority

`conda install spam eggs --channel=A --channel=B` will install both packages from *A*

## Installation without channel priority

`conda install spam eggs --channel=A --channel=B --no-channel-priority` will install *spam* from *B* because it is newer, but *eggs* from *A* although it has a higher build number and is thus newer than the version in *A*

## `conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /data/ssd/stefan/ems-training-3-staging  (writable)
    default environment : /data/ssd/stefan/ems-training-3-staging
       envs directories : /data/ssd/stefan/ems-training-3-staging/envs
                          /localhome/stefan/.conda/envs
          package cache : /data/ssd/stefan/ems-training-3-staging/pkgs
                          /localhome/stefan/.conda/pkgs
           channel URLs : http://***/conda/staging/linux-64
                          http://***/conda/staging/noarch
                          http://***/conda/stable/linux-64
                          http://***/conda/stable/noarch
            config file : /data/ssd/stefan/ems-training-3-staging/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.18.4 CPython/3.6.3 Linux/4.13.13-200.fc26.x86_64 Fedora/26 glibc/2.25    
                UID:GID : 1119:1119
```

**Comment by mingwandroid** [comment]
> but eggs from A although it has a higher build number and is thus newer than the version in A

This doesn't make any sense, can you fix it?

Also you are not using the latest version of conda, please try after having done `conda update conda`.

**Comment by mbargull** [comment]
Build number are not supposed to be comparable across channels.
Suppose `A::eggs-1.0-py36_0` just works fine and dandy, but in channel `B` someone messed up a couple of times to until they get some build `B::eggs-1.0-py36_9001` working that is equivalent to `A::eggs-1.0-py36_0` -- builds from different channels just happen independently is all.

**Comment by mbargull** [comment]
Also add another channel `C` which again starts at build number `0` but actually does so a year after packages from `A` and `B` are built: `C` has the "newer" build, although a potentially smaller build number...

**Comment by mingwandroid** [comment]
Ah yes, this is true @mbargull, thanks for the input. I'm going to close this as a non-issue.

**Comment by mingwandroid** [comment]
One final point, you should be able to use `conda` `meta-channels` to allow comparison across channels. Please correct me if I am wrong about that though @mbargull and @kalefranz.

**Comment by mbargull** [comment]
I would assume that even inside a multi-channel the single channels get priorities. For Anaconda's `defaults` that would be to prioritize the new `main` over `free` for example. I haven't tried that out and don't know all of the associated code, though. But given the test case at https://github.com/conda/conda/tree/c11f30f1e1ed060515887c300f3e59aae1fa0cfe/tests/models/test_channel.py#L925, I believe my assumption could be correct.
