### ISSUE TITLE
Identifying CONDA v. PIP Installed Libraries

### ISSUE THREAD

**Issue by Erstwild** [conda/conda#6474]
I am trying to find the best starting point for identifying conda v. pip installed libraries.  I have project I am working on that requires a virtualenv to be defined currently.  I would like to give users the option to use conda virtual environments, but I have found it to be difficult to consistently identify what packages have been installed via pip v. conda to include in my packaging routines.  Is there a good recommended starting point for figuring this out?

**Comment by jjhelmus** [comment]
`conda list` will identify the packages installed via conda or pip in a conda environment.  Were you looking at something more details than that?
