### ISSUE TITLE
Problem in launching of anaconda-navigator in Anaconda3-5.0.1-Linux-x86_64.sh

### ISSUE THREAD

**Issue by bansalmk18jan** [conda/conda#6484]
Hello,
I have installed Anaconda3-5.0.1-Linux-x86_64.sh on Ubuntu 17.10.
Installation was successful, and I did not see any error/warning during installation.
But, as I run the anaconda-navigator, I am able to see the Anaconda Navigator, but also seeing the following messages on linux terminal -
we6aisol@we6aisol-H170-Gaming-3:~$ 2017-12-17 21:11:44,876 - ERROR download_api._download:192
Invalid URL '': No schema supplied. Perhaps you meant http://?

2017-12-17 21:11:44,877 - ERROR download_api._download:197
Invalid url

Is there any issue with Anaconda installation?

Thanks & Regards
Manoj Bansal

**Comment by goanpeca** [comment]
@bansalmk18jan closing this as it is duplicate in the anaconda-issues tracker (where it belongs :-)  )
