### ISSUE TITLE
Make stacked environments configurable

### ISSUE THREAD

**Issue by dmitry-kabanov** [conda/conda#6488]
When conda is activated, the `bin` directory of the `root` environment is in the `PATH`.
When another environment is activated, its `bin` directory is prepended to the `PATH`, however, the root's `bin` is still in the `PATH` as the second item.
It leads to the situations like the following.

I have `root` environment where `ipython` is installed, for example.
Then I create a new environment, say, `test` and install some package there, which is not installed in my root environment, for example, `clawpack`. However, I forget to install `ipython` in the `test` environment.

Then I activate my `test` environment, execute `ipython` and type `import clawpack`.
What I get is an import error, because `ipython` that I use comes from the `root` environment, not from the `test` environment.

A similar situation occurs when I install into the `test` environment a different version of a package.

It seems to me that the `bin` of the `root` environment should be removed from `PATH` when another environment is activated. Then, during deactivation, `root` environment should be pushed back to the `PATH`.

**Comment by kalefranz** [comment]
This will be default behavior in conda 4.6.  For users still wanting to literally stack environments on PATH, we are providing a `--stack` flag for `conda activate`.  See #7194.
