### ISSUE TITLE
Conda damages its DB

### ISSUE THREAD

**Issue by KOLANICH** [conda/conda#6490]
1 when I try to update anaconda conda often hangs. I me no CPU activity, no disk io, just waits for something. I usually ctrl-c in these cases.
2 But after that I cannot restart the installation (even with -f - it stops too fast doing nothing, for example no shortcuts are created) - conda thinks that it has installed everything. Even though it hasn't. I think that in the db (or what it uses to keep trac) packages must be marked as installed only after thwy are really installed.

**Comment by kalefranz** [comment]
Sending SIGKILL during an unlink-link transaction WILL corrupt your installation.  This is a known issue, and one we consider technical debt.  The solution is being tracked in #6418
