### ISSUE TITLE
ImportError: cannot import name 'multiarray' when i use conda env in apache

### ISSUE THREAD

**Issue by suparek** [conda/conda#6496]
my environment:
ubuntu server 16.04
apache2
django 1.11
python 3.6 (use conda env)

when i use shell，i write:
`import numpy`
`import numpy.core.multiarray`

it is all right

but when i use it in my django code。come error like this:
`Traceback (most recent call last):`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941]   File "/home/yangtao/miniconda3/envs/compoengine/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <modu$`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941]     from . import multiarray`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941] ImportError: cannot import name 'multiarray'`

why ? i use it in my conda env,

my apache conf:
`
<VirtualHost *:7080>

        ServerName localhost:7080
        ServerAdmin sdfsa@163.com

        WSGIDaemonProcess comengine python-path=/home/yangtao/miniconda3/envs/compoengine/lib/python3.6/site-packages

        WSGIProcessGroup comengine

        WSGIScriptAlias / /home/serverend/comengine/comengine/wsgi.py

        <Directory /home/serverend/comengine/comengine>
        <Files wsgi.py>
                Require all granted
        </Files>
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error-comengine.log
        CustomLog ${APACHE_LOG_DIR}/access-comengine.log combined

</VirtualHost>
`

**Comment by kalefranz** [comment]
This has nothing to do with conda. Sorry.
