### ISSUE TITLE
window 10 conda4.2.9  python3.5 pip install tensorflow 

### ISSUE THREAD

**Issue by 2015E8016061044** [conda/conda#6498]
Collecting tensorflow
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000020FC2115B70>, 'Connection to pypi
.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000020FC219BC88>, 'Connection to pypi
.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000020FC219B710>, 'Connection to pypi
.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000020FC219BBA8>, 'Connection to pypi
.python.org timed out. (connect timeout=15)')': /simple/tensorflow/

**Comment by 2015E8016061044** [comment]
.condarc:
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://nanomirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
ssl_verify: true
show_channel_urls: true

**Comment by kalefranz** [comment]
Flakey internet connection.  Intermittent HTTP error.  Also conda 4.2 is no longer supported.  

    conda update conda

**Comment by VanitarNordic** [comment]
if you use Anaconda, you can use  `conda install -c hesi_m tensorflow ` to install tensorflow 1.9.0 for CPU 

if you specifically use Keras also, you can use  `conda install -c hesi_m keras` which installs Keras 2.2.0 in accompany with everything including tensorflow 1.9.0

It is better to make a fresh anaconda environment for your experiments
