### ISSUE TITLE
more targeted conda locking

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#650]
I have one terminal window that is busy creating a conda environment (`conda create -n foo ...`.  This takes 10-15 minutes.  In another terminal window I want to build a conda package (`conda build conda.recipe`).  Perhaps in another terminal window I want to build a different conda package.  Right now I can't do the first two due to the way conda does locking.  I'd like to be able to at least do the first two concurrently, and ideally be able to concurrently build multiple conda packages (which I believe is also not possible right now).

**Comment by asmeurer** [comment]
If you still find the locking to not be targeted enough, please comment here. As for building multiple at once, see https://github.com/conda/conda-build/issues/96.
