### ISSUE TITLE
Add control over which packages to export from an environment

### ISSUE THREAD

**Issue by petebachant** [conda/conda#6501]
This seems to be related to but not a duplicate of #5155.

I like to keep only dependencies that are imported directly in my `environment.yml` file to keep it cross-platform, i.e., let conda find the dependencies of the top-level dependencies automatically. It would be great if I could only export the versions of the dependencies listed there when calling `conda env export`.

Usage example:

```
conda env export -n myenv --from-file environment.yml > environment.yml
```

Conda would read packages listed in `environment.yml`, and use these to filter what's exported.

Another usage example:

```
conda env export -n myenv --packages python matplotlib pandas
```

This command would only export those packages (whether installed by pip or conda).

**Comment by DrDanRyan** [comment]
I just discovered the `--from-history` flag. Doesn't this do exactly what you want?
`conda env export -n myenv --from-history > environment.yml`

**Comment by petebachant** [comment]
Not quite, but that seems useful.
