### ISSUE TITLE
User does not have write access for conda symlinks error.

### ISSUE THREAD

**Issue by as7a5** [conda/conda#6503]
This error happens as one wants to activate a particular version of an environment. Other version loads up properly. Miniconda is installed on a cluster (CentOS6.8, Bright cluster management, conda 4.3.27) and this error happens on compute nodes if it is run as a user. As a root it is all good.
The full error:
CondaEnvironmentError: Cannot activate environment bash.
User does not have write access for conda symlinks.
I appreciate your help

**Comment by kalefranz** [comment]
Conda 4.4 no longer mutates environments on activation by creating those symlinks.
