### ISSUE TITLE
conda 4.4 and GNU screen doesn't find "conda" function

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#6505]
When trying to use the new "conda activate" command inside a screen terminal, I get this:

```bash
└─( 2 ) ❱❱❱ conda activate                                                +8766 23:53 ❰─┘

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /Users/klay6683/miniconda3/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s /Users/klay6683/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="/Users/klay6683/miniconda3/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^
```
The `source activate <env_name>` still works, so I'm not bothered much, apart from the inconsistency, trying to solely use `conda activate <env_name>`.

I tried to follow the instructions from above error message, but to no avail.

Running this on macOS 10.12.6 on an iMac. conda 4.4 via canary.

**Comment by kalefranz** [comment]
That message displays as expected.

**Comment by michaelaye** [comment]
How is the impossibility of using "conda activate" expected? Did I miss something in the docs?

**Comment by michaelaye** [comment]
I'm stumped..
With the exact same path, I get a different answer for `which conda` in the `screen` session:

Standard login zsh:
```bash
(stable) └─❱❱❱ echo $PATH                                                           +8993 18:15 ❰─┘
/Users/klay6683/miniconda3/envs/stable/bin:/Users/klay6683/.jenv/shims:/usr/local/bin:/usr/local/sbin:/Users/klay6683/bin:/Users/klay6683/Dropbox/src/SpiceyPy/cspice/exe:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(stable) └─❱❱❱ which conda                                                          +8997 18:15 ❰─┘
conda () {
	if [ "$#" -ge 1 ]
	then
		local cmd="$1"
		shift
	else
		local cmd=""
	fi
	case "$cmd" in
		(activate) _conda_activate "$@" ;;
		(deactivate) _conda_deactivate "$@" ;;
		(install | update | uninstall | remove) $_CONDA_EXE "$cmd" "$@"
			_conda_reactivate ;;
		(*) $_CONDA_EXE "$cmd" "$@" ;;
	esac
}
```

Screen session:
```bash
┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
└─( 2 ) ❱❱❱ echo $PATH                                                              +8995 18:15 ❰─┘
/Users/klay6683/miniconda3/envs/stable/bin:/Users/klay6683/.jenv/shims:/usr/local/bin:/usr/local/sbin:/Users/klay6683/bin:/Users/klay6683/Dropbox/src/SpiceyPy/cspice/exe:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
└─( 2 ) ❱❱❱ which conda                                                             +8996 18:15 ❰─┘
/Users/klay6683/miniconda3/envs/stable/bin/conda
┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
└─( 2 ) ❱❱❱ ls -la `which conda`                                                    +9005 18:20 ❰─┘
lrwxr-xr-x  1 klay6683  staff    36B Jan 22 14:15 /Users/klay6683/miniconda3/envs/stable/bin/conda -> /Users/klay6683/miniconda3/bin/conda

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
└─( 2 ) ❱❱❱ file /Users/klay6683/miniconda3/bin/conda                               +9006 18:20 ❰─┘
/Users/klay6683/miniconda3/bin/conda: Python script text executable, ASCII text
```

Should there actually be still a Python script at `~/miniconda3/bin/conda` after updating to 4.4.7?

**Comment by michaelaye** [comment]
And if somebody needs .zprofile to be loaded by screen, put this into ~/.screenrc, to  forge a `login` shell to be opened by `screen`:

```
shell -zsh
```

**Comment by mbargull** [comment]
Oh, the advice to put it into `.bash_profile` isn't a good one, I think!
For `bash` it's `.bashrc` that should be altered. (Well, unless you're a Mac user where things are stupid and `.bash_profile` is used; IMO, it's best to include `[[ -f ~/.bashrc ]] && . ~/.bashrc` in `.bash_profile` and make all other changes in `.bashrc`).
`.bash_profile` is usually only executed for login shells and other interactive one use `.bashrc`.
As for `zsh`, you got it right, `.zshrc` should be used, I believe.

**Comment by Bl41r** [comment]
[dsmith7@ip- ~]$ conda activate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /opt/anaconda/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /opt/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/opt/anaconda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^


[dsmith7@ip- ~]$ sudo ln -s /opt/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
[sudo] password for dsmith7:
[dsmith7@ip- ~]$ conda activate
.....

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with
........

(using conda 4.4.8)
Curious why the command did not work?

**Comment by michaelaye** [comment]
Have you sourced the new shell script? If not, logging out and in again does that for you.

**Comment by the-vampiire** [comment]
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /Users/YOU/anaconda3/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s /Users/YOU/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="/Users/YOU/anaconda3/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^
```

## If you had this issue and are using ZSH on Mac / OSX do the following:
- remove `export PATH=~/anaconda3/bin:$PATH` from your `.zshrc` file
- add this line `. /Users/ROOT_USER_HERE/anaconda3/etc/profile.d/conda.sh` to your `.zshrc` file

alternatively take the error message they gave you and change the target to `.zshrc`
- **change this**: `$ echo ". /Users/YOU/anaconda3/etc/profile.d/conda.sh" >> ~/.bash_profile`
- **to this**: `$ echo ". /Users/YOU/anaconda3/etc/profile.d/conda.sh" >> ~/.zshrc`

## NOTE
- from now on you can no longer use `source activate X` and `source deactivate`
- you must use `conda activate X` and `conda deactivate`

### embarassing note
- i have no idea why this works but it does.
- would love to know why this change was necessary (been fucking around with this for longer than i'd like to admit)
- also what adding `. /Users/ROOT_USER_HERE/anaconda3/etc/profile.d/conda.sh` does. `export PATH` makes some sense. never seen this `. ...` syntax before.

**Comment by jbrant** [comment]
I'm having the same issue as the OP on Windows.

**Comment by svnp10** [comment]
Have same issue on Mac - 10.13

**Comment by ews92** [comment]
I have the same problem on Mac. Started this week and will not go away no matter what sequence of commands I enter in Terminal.

**Comment by zie-1** [comment]
I have also the same problem on Windows 10 :( . I am hopeless trying get rid of these error :(
All the commands seems dont  work for me.

**Comment by rpanai** [comment]
I've the same problem on GCP.

**Comment by ews92** [comment]
@zie-1 I ended up solving this by installing a new user profile on my machine and bringing my old data over. I spoke to someone who explained that as a beginner, diagnosing and solving the problem was going to take longer than doing it this way. Thankfully, I have frequent backups and Macs make it very easy to port data from one user to another.

**Comment by YCmove** [comment]
OS: Ubuntu 18.04
conda version: 4.5.5

I can only enable conda with
`$ echo ". /home/USERNAME/anaconda2/etc/profile.d/conda.sh" >> ~/.bashrc`

And this line didn't work.
`$ sudo ln -s /home/USERNAME/anaconda2/etc/profile.d/conda.sh /etc/profile.d/conda.sh`

**Comment by PseudoFlame** [comment]
To comment on the curiosity between execute `conda activate` and `source activate` as mentioned before:

`conda activate` does work for me in a terminal (using bash), **but not in a script**!
Consider the following python script:
```python
#! /usr/bin/env python

import subprocess

if __name__ == "__main__":
    cmd = 'bash'
    proc = subprocess.Popen(cmd,
                            shell=True,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE,
                            stdin=subprocess.PIPE,
                        )
    cmd_fails = '~/miniconda2/bin/conda activate'
    cmd_works = 'echo `which python`; source ~/miniconda2/bin/activate ~/miniconda2/; echo `which python`'
    stdout, stderr = proc.communicate(cmd_works)
    print stdout, stderr
```
If I use `cmd_fails` I obtain the `CommandNotFoundError` as posted above by many other users as well. However, entering `conda activate` in any terminal (running bash) works fine.
If I use the `cmd_works` I successfully changed the environment in the script:
```
> python shell_swap_env.py
/usr/bin/python
~/miniconda2/bin/python
```

What is the difference between using `conda activate` and `source activate`?

**Comment by kalefranz** [comment]
[`source`](https://en.wikipedia.org/wiki/Source_(command)) is a bash built-in. You must "source" rather than subprocess when you want the script to affect the context of the current process.  To make `conda activate` work, `conda` actually needs to become a shell function rather than an executable.  The `conda` command is loaded as a shell function in conda 4.4 and 4.5 when you execute something like

    source /home/USERNAME/anaconda2/etc/profile.d/conda.sh

from above.  Compare the output of `type -a conda` before and after issuing that command.  This is all complicated by how shells initialize themselves differently in "interactive" vs "non-interactive" mode.

We're trying to clean this up one step further in conda 4.6.  The recommended way to initialize conda in a bash shell where `~/.bashrc` or `~/.bash_profile` is not sourced at shell startup will be

    eval "$(/home/USERNAME/anaconda2/bin/conda shell.bash hook)"

which largely follows the same pattern established by the excellent [`direnv`](https://direnv.net/) project.

**Comment by danielrvoigt** [comment]
The changelog explains the solution well:
https://github.com/conda/conda/blob/master/CHANGELOG.md#440-2017-12-20

I'm on mac and did the following:

1. `sudo vim ~/.bash_profile`

2. insert:

`. /anaconda3/etc/profile.d/conda.sh
conda activate base`

(replace `/anaconda3`, with your path for Anaconda)

3. restart terminal session to see changes
