### ISSUE TITLE
create an "initialize" command for conda

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6507]
With the new shell capabilities in conda 4.4, shell configuration has gotten a lot more nuanced.  This is a tracking ticket for creating a `conda initialize` command.

Capabilities:

1. Help ensure users have properly configured shells.
2. Enable `pip install conda`, in a way that will actually work.
3. For conda developers and contributors, facilitate a more stream-lined dev mode.

Somewhat related to #107.

**Comment by kalefranz** [comment]
Below is the current draft for the help string.  Definitely interested in getting feedback on the examples, and the capabilities they are demonstrating.

```
Key parts of conda's functionality require that it interact directly with the shell 
within which conda is being invoked. The `conda activate` and `conda deactivate` commands 
specifically are shell-level commands. That is, they affect the state (e.g. environment 
variables) of the shell context being interacted with. Other core commands, like 
`conda create` and `conda install`, also necessarily interact with the shell environment. 
They're therefore implemented in ways specific to each shell. Each shell must be configured 
to make use of them.

Examples:
    
    # Make the conda command available in all detected shells for the *current user*.
    # For example, if the bash shell is among those detected on your system, this command
    # will modify your user's `~/.bashrc` file (`~/.bash_profile` on macOS). In addition to,
    # the 'conda' command being made available, the 'base' conda environment is automatically
    # activated (i.e. environment variables set and all executables put on PATH).
    
        $ conda init
    
    # Make the conda command available to every user on the system. For example, if the bash 
    # shell is among those detected on your system, a file `/etc/profile.d/conda.sh` will be
    # created, which will be sourced when your shell is initialized.
    
        $ conda init --system
    
    # Initialize conda in all detected shells for the current user. Additionally, make *only*
    # the 'conda' command available to the shell, and *do not* automatically activate the 
    # base environment. Executables in the base environment, like python, will not be 
    # available on PATH until running 'conda activate base'.
    
        $ conda init --no-auto-activate
    
    # When executed from a bash shell, ensure that conda is properly installed in the prefix 
    # for the first python on PATH (e.g. following a `python -m pip install conda`). Make the 
    # 'conda' command available to the current shell process, and activate the 'base' 
    # environment. Does not modify `~/.bashrc` for example, so has no effect on future shell
    # sessions.
    
        $ eval `python -m conda init --install-only bash`


IMPORTANT: After running `conda init`, most shells will need to be closed and restarted
           for changes to take effect.
```

In addition to these examples, there will be one more not included here, but included in developer documentation somewhere (those dev docs really don't yet exist).  That example might look like the following

```
# An example for creating an environment to develop on conda's own code. Clone the 
# conda repo and install a dedicated miniconda within it. Remove all remnants of 
# conda source files in the `site-packages` directory associated with 
# `~/conda/devenv/bin/python`. Write a `conda.pth` file in that `site-packages` 
# directory pointing to source code in `~/conda`, the current working directory.
# Write commands to stdout, suitable for bash `eval`, that sets up the current
# shell as a dev environment. 
    
    $ git clone git@github.com:conda/conda ~/conda
    $ curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/Miniconda3-latest-Linux-x86_64.sh
    $ bash ~/Miniconda3-latest-Linux-x86_64.sh -bfp ~/conda/devenv
    $ cd ~/conda
    $ eval `./devenv/bin/python -m conda init --dev bash`

```

**Comment by kalefranz** [comment]
reference: https://github.com/direnv/direnv

**Comment by kalefranz** [comment]
The description above was an example, and the help information as implemented is substantially paired back.

**Comment by abalter** [comment]
I'm curious what the `initialize` command is for?

**Comment by kalefranz** [comment]
The command is actually now `conda init`.  The primary purpose is to properly configure all the various shells so that `conda activate` works correctly.

It gives us one command--that's the same everywhere--we can use ourselves with the Miniconda and Anaconda installers or give to users who might have gotten conda onto their systems in another way to make sure conda has been hooked into their system correctly.

On unix systems, the command is intelligently (idempotently, with comments/annotations) making modifications to `.bashrc`, `.zshrc`, `/etc/profile.d`, etc.  On Windows, the command also makes some targeted registry modifications.

**Comment by scw** [comment]
@kalefranz could you speak to how these will work in contexts where there are multiple conda installs on the same machine? With Anaconda being distributed via Visual Studio, standalone Anaconda and Miniconda installations and Applications which ship with embedded conda in the mix, will this preserve the features that provide isolation across environments? I know this is a tricky one to get right, just hoping to never return to the unpleasant place of managing  overlapping Python installs in the registry (for Windows at least).
