### ISSUE TITLE
4.4+conda-build not prioritizing local channel correctly

### ISSUE THREAD

**Issue by msarahan** [conda/conda#6516]
I have a package, bzip2, build number 4, locally.  I'm expecting it to be used as a dependency.  Conda 4.3.31 finds it ok:

```
conda build libnetcdf-feedstock/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/dev/code/aggregate/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/dev/code/aggregate/conda_build_config.yaml
Attempting to finalize metadata for libnetcdf
INFO:conda_build.metadata:Attempting to finalize metadata for libnetcdf
BUILD START: ['libnetcdf-4.5.0-h569e9f1_6.tar.bz2']

The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h9a117a8_4      local
    ca-certificates: 2017.08.26-h1d4fec5_0 defaults
    curl:            7.55.1-h78862de_4     defaults
    hdf4:            4.2.13-h3ca952b_2     defaults
    hdf5:            1.8.18-h6792536_1     defaults
    jpeg:            9b-h024ee3a_2         defaults
    libgcc-ng:       7.2.0-h7cc24e2_2      defaults
    libgfortran-ng:  7.2.0-h9f7466a_2      defaults
    libssh2:         1.8.0-h2d05a93_3      defaults
    libstdcxx-ng:    7.2.0-h7a57d05_2      defaults
    openssl:         1.0.2n-hb7f436b_0     defaults
    zlib:            1.2.11-ha838bed_2     defaults
```

Conda 4.4.0 does not:

```
[root@69189185e23f aggregate]# conda build libnetcdf-feedstock/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/dev/code/aggregate/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/dev/code/aggregate/conda_build_config.yaml
Attempting to finalize metadata for libnetcdf
INFO:conda_build.metadata:Attempting to finalize metadata for libnetcdf
Solving environment: done
Solving environment: done
Solving environment: done
BUILD START: ['libnetcdf-4.5.0-h569e9f1_6.tar.bz2']
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/conda-bld/libnetcdf_1513891848918/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-3               defaults
    ca-certificates: 2017.08.26-h1d4fec5_0 defaults
    curl:            7.55.1-h78862de_4     defaults
    hdf4:            4.2.13-h3ca952b_2     defaults
    hdf5:            1.8.18-h6792536_1     defaults
    jpeg:            9b-h024ee3a_2         defaults
    libgcc-ng:       7.2.0-h7cc24e2_2      defaults
    libgfortran-ng:  7.2.0-h9f7466a_2      defaults
    libssh2:         1.8.0-h2d05a93_3      defaults
    libstdcxx-ng:    7.2.0-h7a57d05_2      defaults
    openssl:         1.0.2n-hb7f436b_0     defaults
    zlib:            1.2.11-ha838bed_2     defaults
```

This is conda-build 3.2.0, if that helps.

**Comment by kalefranz** [comment]
I've identified the issue.  Might take some discussion to figure out how to fix it.  Here's the issue...

The `install_actions()` function in conda takes a `channel_priority_map` parameter:
https://github.com/conda/conda/blob/4.4.1/conda/plan.py#L515

I guess in conda 4.4 that took on more/different importance.

That parameter currently isn't being passed by conda-build:
https://github.com/conda/conda-build/blob/3.2.0/conda_build/environ.py#L691

So conda is falling back to whatever is configured for `context.channels`.

**Comment by mcg1969** [comment]
Does this mean there is an unintentional change to the exported behavior conda build uses? I think we should prioritize restoring that behavior.

But 4.3.x has the `channel_priority_map` input as well, so I don't understand why it would behave differently in 4.4.

**Comment by kalefranz** [comment]
In 4.3, we set channel priority on each individual record every time we build the index.  In 4.4, we hand channel priority over to Resolve, and let Resolve handle all the dynamic parts of priority.

Stuffing that level of mutability inside of an index record was always problematic.  We have the same issue of `add_pip_as_python_dependency`.  

Conda-build probably wasn't using that parameter on `install_actions()` because it wasn't important before now, for the flows that conda-build uses (i.e. calling conda's get_index, and then handing that index back to the solver).

I can probably hack something together in conda to make this work again, but I'm pretty sure there will be a performance hit for all the translation.

Maybe it's worthwhile for us to do a code review of the much cleaner APIs that conda 4.4 has for the Solver, and the three individual information sources (i.e. package cache, prefix, and repodata).  The Solver API is already locked down in `conda/api.py`, and we can easily do the same thing for the three lower-level APIs too.  Then start thinking about how conda-build can make use of them.

**Comment by mcg1969** [comment]
OK, so I get that this is an unintentional change, but I think we have to go with the perfomance hit here and revert. Perhaps there's a way to mitigate the performance hit.

**Comment by mcg1969** [comment]
An alternative is if we can come up with an easy way on the conda-build side to do the right thing, but it would have to work with conda 4.3 and 4.4...

**Comment by msarahan** [comment]
Can I pass a reasonable channel map somehow?

**Comment by kalefranz** [comment]
I believe #6517 fixes this for conda-build without a real performance penalty.

**Comment by msarahan** [comment]
I'll try this in the docker container where I observed the problem.

**Comment by jjhelmus** [comment]
Ran into this as well.  What is odd is that the package being installed does not match the version spec.  During a build of Boost, after libboost is built, the environment to build py-boost is created:

```
Packaging py-boost
INFO:conda_build.build:Packaging py-boost
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/libboost_multiple_outputs_1513906514392/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-3               defaults
    ca-certificates: 2017.08.26-h1d4fec5_0 defaults
    icu:             58.2-h9c2bf20_1       defaults
    intel-openmp:    2018.0.0-hc7b2577_8   defaults
    libboost:        1.65.1-h4055789_3     defaults
    libedit:         3.1-heed3624_0        defaults
    libffi:          3.2.1-hd88cf55_4      defaults
    libgcc-ng:       7.2.0-h7cc24e2_2      defaults
    libgfortran-ng:  7.2.0-h9f7466a_2      defaults
    libstdcxx-ng:    7.2.0-h7a57d05_2      defaults
    mkl:             2018.0.1-h19d6760_4   defaults
    ncurses:         6.0-h9df7e31_2        defaults
    numpy:           1.9.3-py27h7e35acb_3  defaults
    openssl:         1.0.2n-hb7f436b_0     defaults
    python:          2.7.14-h1571d57_29    defaults
    readline:        7.0-ha6073c6_4        defaults
    sqlite:          3.20.1-hb898158_2     defaults
    tk:              8.6.7-hc745277_3      defaults
    zlib:            1.2.11-ha838bed_2     defaults
```

Not only is the local `libboost` package not being installed by the pinning to the exact build string is not being respected.

**Comment by kalefranz** [comment]
I'm probably going to be cutting another release tonight, for other things that have clear and simple solutions. Anybody have any input on me including #6517 in 4.4.2?

**Comment by msarahan** [comment]
I have been building python 3.6.4 and haven't had time to look at this.  I'm not likely to get to this before I go on holiday.  If you try to build libnetcdf as we previously discussed, pay special attention to the bzip2 package that gets installed.  Without your fix, it's an old package that comes from the free channel.  If your fix works correctly, it'll be one from main instead.

If you'd like a further test, use c3i to build both bzip2-feedstock and libnetcdf-feedstock.  They will be build in order, and the libnetcdf build should use the package that was built by the earlier bzip2 build.

**Comment by kalefranz** [comment]
For testing #6517, I built bzip2 locally first, and then started the build for libnetcdf.  According to that test, #6517 indeed fixes the problem.

<details><summary>Without #6517</summary>
kfranz@0283:~/AnacondaRecipes/libnetcdf-feedstock/recipe *master ❯ /conda3/bin/conda build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/kfranz/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/kfranz/conda_build_config.yaml
Attempting to finalize metadata for libnetcdf
INFO:conda_build.metadata:Attempting to finalize metadata for libnetcdf
Solving environment: done
Solving environment: done

Downloading and Extracting Packages
hdf5 1.8.18: ################################################################################################################################################## | 100%
Solving environment: done
BUILD START: ['libnetcdf-4.5.0-h5a68d8a_6.tar.bz2']
Solving environment: done

## Package Plan ##

  environment location: /conda3/conda-bld/libnetcdf_1513893960557/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-3
    ca-certificates: 2017.08.26-ha1e5d58_0
    curl:            7.55.1-h2e228d0_4
    hdf4:            4.2.13-h39711bb_2
    hdf5:            1.8.18-h017327d_1
    jpeg:            9b-he5867d9_2
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libgfortran:     3.0.1-h93005f0_2
    libssh2:         1.8.0-h9feafcd_3
    openssl:         1.0.2n-hdbc3d79_0
    zlib:            1.2.11-hf3cbc9b_2


Downloading and Extracting Packages
libssh2 1.8.0: ################################################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done
Solving environment: done

## Package Plan ##

  environment location: /conda3/conda-bld/libnetcdf_1513893960557/_build_env


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-3
    ca-certificates: 2017.08.26-ha1e5d58_0
    cctools:         895-h7512d6f_0
    clang:           4.0.1-h662ec87_0
    clang_osx-64:    4.0.1-h1ce6c1d_5
    cmake:           3.9.4-h30c3106_0
    compiler-rt:     4.0.1-h5487866_0
    curl:            7.55.1-h2e228d0_4
    expat:           2.2.5-hb8e80ba_0
    ld64:            274.2-h7c2db76_0
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libssh2:         1.8.0-h9feafcd_3
    libuv:           1.14.0-h740c2a5_0
    llvm:            4.0.1-hc748206_0
    llvm-lto-tapi:   4.0.1-h6701bc3_0
    make:            4.2.1-h0cf4ea2_0
    ncurses:         6.0-hd04f020_2
    openssl:         1.0.2n-hdbc3d79_0
    pkg-config:      0.29.2-h29070b1_6
    rhash:           1.3.5-h3aa0507_1
    xz:              5.2.3-h0278029_2
    zlib:            1.2.11-hf3cbc9b_2
</details>


<details><summary>With #6517</summary>
kfranz@0283:~/AnacondaRecipes/libnetcdf-feedstock/recipe *master ❯ /conda3/bin/conda build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/kfranz/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/kfranz/conda_build_config.yaml
Attempting to finalize metadata for libnetcdf
INFO:conda_build.metadata:Attempting to finalize metadata for libnetcdf
BUILD START: ['libnetcdf-4.5.0-h5a68d8a_6.tar.bz2']

The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h1de35cc_2      local
    ca-certificates: 2017.08.26-ha1e5d58_0
    curl:            7.55.1-h2e228d0_4
    hdf4:            4.2.13-h39711bb_2
    hdf5:            1.8.18-h017327d_1
    jpeg:            9b-he5867d9_2
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libgfortran:     3.0.1-h93005f0_2
    libssh2:         1.8.0-h9feafcd_3
    openssl:         1.0.2n-hdbc3d79_0
    zlib:            1.2.11-hf3cbc9b_2


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h1de35cc_2      local
    ca-certificates: 2017.08.26-ha1e5d58_0
    cctools:         895-h7512d6f_0
    clang:           4.0.1-h662ec87_0
    clang_osx-64:    4.0.1-h1ce6c1d_5
    cmake:           3.9.4-h30c3106_0
    compiler-rt:     4.0.1-h5487866_0
    curl:            7.55.1-h2e228d0_4
    expat:           2.2.5-hb8e80ba_0
    ld64:            274.2-h7c2db76_0
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libssh2:         1.8.0-h9feafcd_3
    libuv:           1.14.0-h740c2a5_0
    llvm:            4.0.1-hc748206_0
    llvm-lto-tapi:   4.0.1-h6701bc3_0
    make:            4.2.1-h0cf4ea2_0
    ncurses:         6.0-hd04f020_2
    openssl:         1.0.2n-hdbc3d79_0
    pkg-config:      0.29.2-h29070b1_6
    rhash:           1.3.5-h3aa0507_1
    xz:              5.2.3-h0278029_2
    zlib:            1.2.11-hf3cbc9b_2
</details>

**Comment by jjhelmus** [comment]
If you want anther test case [PR 2 from the boost-cpp feedstock](https://github.com/AnacondaRecipes/boost-cpp-feedstock/pull/2) builds correctly with conda 4.3.31 but fails with 4.4.0 and 4.4.1 on linux-64.  The Windows builds still need some work.

**Comment by kalefranz** [comment]
And yet, clearing my local `conda-bld` build cache, even with #6517, it appears I'm getting the pkgs/free bzip2.  hmmphh

**Comment by kalefranz** [comment]
Ok I think #6517 so far might be part of the fix.  But I also think 4.4 might not be prioritizing the defaults multi-channel correctly, among all the subchannels.  Looking into that now.

**Comment by kalefranz** [comment]
Ok so #6517 has two patches now.  One for holding over conda-build's channel priority state between `get_index()` and `install_actions()` calls, and then the other for channel priority within multi-channels.
