### ISSUE TITLE
--use-local flag not working in 4.4.0

### ISSUE THREAD

**Issue by martinholmer** [conda/conda#6520]
For some time I've been doing this:
```
conda build --old-build-string --python 2.7
conda install taxcalc=0.0.0 --use-local --yes
```
But that `conda install` command now fails under conda 4.4.0 and 4.4.1.

I have been able to work around this problem by doing this:
```
conda build --old-build-string --python 2.7
conda install --offline ~/anaconda/conda-bld/osx-64/taxcalc-0.0.0-py27_0.tar.bz2
```
Why does my old code fail under conda 4.4.0 and conda 4.4.1?

The failure is that it says it cannot find the package, but it is where it has always been built:
`~/anaconda/conda-bld/osx-64/taxcalc-0.0.0-py27_0.tar.bz2`

**Comment by kalefranz** [comment]
Does this work:

    conda install -c local taxcalc=0.0.0

**Comment by kalefranz** [comment]
Does this work?

    conda install -c local taxcalc=0.0.0

**Comment by martinholmer** [comment]
@kalefranz asked:
> Does this work?
>
> `conda install -c local taxcalc=0.0.0`

Thanks for the suggestion.  I'm going to try it now.

**Comment by kalefranz** [comment]
It's still a bug either way.  If that works for you though, it'll at least help narrow down the problem.

**Comment by martinholmer** [comment]
After doing `conda build`, I tried the `conda install` command suggested by @kalefranz and that worked although the "solving environment" step took quite a while.  Also, to put this command in a bash script it seems as if you need to quiet the progress "spinner".   Here is what happened in my test:
```
iMac:conda.recipe$ date ; conda install -c local taxcalc=0.0.0 --quiet --yes ; date
Thu Dec 21 22:44:21 EST 2017
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/mrh/anaconda

  added / updated specs: 
    - taxcalc=0.0.0


The following NEW packages will be INSTALLED:

    taxcalc: 0.0.0-py27_0 local

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Thu Dec 21 22:44:57 EST 2017

iMac:conda.recipe$ conda list taxcalc
# packages in environment at /Users/mrh/anaconda:
#
taxcalc                   0.0.0                    py27_0    local
iMac2:conda.recipe mrh$ 
```
Thanks for the quick advice @kalefranz.

**Comment by kalefranz** [comment]
There's still probably some tuning to be done on the solver behavior, making sure it's not slower than 4.3.

What was the behavior you saw that forced use of the `--quiet` flag in your script?  Just curious if there's something that can be done there...

**Comment by martinholmer** [comment]
@kalefranz asked:
> What was the behavior you saw that forced use of the --quiet flag in your script? Just curious if there's something that can be done there...

Oh, now that I think about it maybe I just forgot the `--yes` option.
I'll test again without the `--quiet` option.

**Comment by martinholmer** [comment]
@kalefranz, Sorry about the misinformation about needing the `--quiet` option; everything works fine as long as I remember to use the `--yes` option.
```
iMac2:conda.recipe mrh$  ./install_local_taxcalc_package.sh
STARTING : Thu Dec 21 22:59:38 EST 2017
BUILD-PREP...
==> Uninstalling existing taxcalc package
==> Continuing to build new taxcalc package
BUILD START: [u'taxcalc-0.0.0-py27_0.tar.bz2']
TEST START: /Users/mrh/anaconda/conda-bld/osx-64/taxcalc-0.0.0-py27_0.tar.bz2
TEST END: /Users/mrh/anaconda/conda-bld/osx-64/taxcalc-0.0.0-py27_0.tar.bz2
INSTALLATION...
CLEAN-UP...
Execute 'conda uninstall taxcalc --yes' after using taxcalc package
FINISHED : Thu Dec 21 23:03:51 EST 2017
iMac:conda.recipe$ conda list taxcalc
# packages in environment at /Users/mrh/anaconda:
#
taxcalc                   0.0.0                    py27_0    local
```
The script used this `conda install` command:
```
conda install -c local taxcalc=0.0.0 --yes 2>&1 > /dev/null
```
So, thanks so much for the late-night advice @kalefranz.  Your work-around is much better than my first try.
