### ISSUE TITLE
update --all removes packages after clean installer and remove anaconda

### ISSUE THREAD

**Issue by o12johns** [conda/conda#6521]
After a new install of anaconda, do 

conda remove anaconda
conda upgrade --all

conda 4.4.0 will ask to remove all installed packages.

After revert to conda 4.3.31, conda upgrade --all acts correctly 
(except of course wishing to upgrade conda to 4.4.0)

System is Mac OSX Sierra on 2017 iMac.

**Comment by kalefranz** [comment]
The solution to this is https://github.com/conda/constructor/issues/138

**Comment by kalefranz** [comment]
fixed with #6523
