### ISSUE TITLE
'conda update --all' causes "'python' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by enihcam** [conda/conda#6523]
repro steps:
1. fresh install of latest version of miniconda
2. `conda update --all` and yes to all questions
3. restart 'Anaconda Prompt'

and you will see
```
'python' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by enihcam** [comment]
And i ran 'conda update --all' again and yes to all questions, shortcut 'Anaconda Prompt' is then removed. I'm totally confused.

**Comment by kalefranz** [comment]
Also #6521.  It's technically not a bug with conda, but instead with constructor.  Either way, we'll have a patch out tonight to stop this behavior.
