### ISSUE TITLE
The batch file cannot be found with conda=4.4

### ISSUE THREAD

**Issue by isuruf** [conda/conda#6527]
See

https://ci.appveyor.com/project/isuruf/flang/build/1.0.386
https://ci.appveyor.com/project/conda-forge/r-base-feedstock/build/1.0.73/job/td3eh8eyg8t046l1

changing `conda update --yes --quiet conda` to `conda install --yes --quiet conda=4.3` fixes this

**Comment by kalefranz** [comment]
The issue here is reproduced, on windows, when flipping back and forth between conda 4.4 from defaults and conda 4.3 from conda-forge.

Don't yet know the root cause.

In the interim, until we have a solution, immediately after the command in your CI setup

    conda update --yes --quiet conda

add the line

    conda config --system --add pinned_packages defaults::conda

**Comment by jdblischak** [comment]
I tried implementing this temporary fix in https://github.com/conda-forge/r-base-feedstock/pull/28/commits/07c46f4b7168e9036236d12254896903a6eb4c3a.

But now `conda-build` is not installed:

https://ci.appveyor.com/project/conda-forge/r-base-feedstock/build/1.0.75/job/360gsx25j0si0mv4#L75

**Comment by kalefranz** [comment]
Oh wow I didn't know conda-forge was going to need compatibility with conda 4.4 out-of-the-box.  I thought conda-forge's internals always used conda-forge's conda.

That said, the no conda-build thing confuses me.

I'm looking here at an appveyor build in the same project from a few hours before we released 4.4 to defaults:
https://ci.appveyor.com/project/conda-forge/r-base-feedstock/build/1.0.69/job/d7g1lbvakk1jfsnf#L47

There too, I don't see anywhere in the setup and conda's output that conda has actually installed the `conda-build` package.  Maybe it's being brought in through through the `conda-forge-build-setup` package?

**Comment by kalefranz** [comment]
I see what's going on in the `conda-forge-build-setup` package now.  I wasn't familiar with that package before.
https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_win.bat#L14

It's possible that `conda install -n root PACKAGE_NAME` is broken in 4.4.  I'll investigate.

**Comment by kalefranz** [comment]
I thought `conda install -n root` was possibly broken in conda 4.4 because, for visual purposes, we renamed the `root` environment to the `base` environment.  Still, the intent was always to keep `root` as an alias to `base`.  And in testing, it appears that everything is fine there.

**Comment by kalefranz** [comment]
BTW, does this mean all of conda-forge is broken right now??? Or just this one recipe?  Because if all of conda-forge is broken, this becomes a MUCH bigger deal, obviously.

**Comment by isuruf** [comment]
All of conda-forge windows builds are broken right now

**Comment by kalefranz** [comment]
I'm also concerned that `CommandNotFoundError` apparently exited `0` in https://ci.appveyor.com/project/conda-forge/r-base-feedstock/build/1.0.75/job/360gsx25j0si0mv4#L75

**Comment by isuruf** [comment]
It seems `run_conda_forge_build_setup` is not run anymore (which install conda-build among other things). I've no idea why

**Comment by kalefranz** [comment]
To get the Windows builds back, until we figure out what's going on, I'd just add for the first `conda config` command before doing *anything* else after conda is initially installed

    conda config --system --set auto_update_conda false

Probably best to keep that as an interim solution.  A stopgap to get Windows builds up and running again until we figure out everything that's going on here.

**Comment by kalefranz** [comment]
@isuruf I'm sorry I'm just coming back to this.  When I first read the issue, I didn't understand that the implication was that *all conda-forge Windows builds* were down.

**Comment by kalefranz** [comment]
I'm not sure where to take this just yet.  I think the most immediate priority should be getting the windows builds back online.  Setting `auto_update_conda` to `false` should hopefully do that.  Please update here if it does or does not, either way.

**Comment by isuruf** [comment]
My current solution was to do `conda install conda=4.3` so that conda=4.4 is not installed at all. I'm not sure whether conda 4.4 breaks our upload scripts, so I think this is the safest way.

**Comment by kalefranz** [comment]
Ok as long as there's an interim solution, I feel a lot better.

**Comment by isuruf** [comment]
This is related to https://github.com/conda/conda/issues/6553
conda is a batch file now and downgrading to conda=4.3 deletes that batch file resulting in this error. (Earlier it was an executable and therefore loaded into memory, so this problem was not there before)

**Comment by kalefranz** [comment]
And also, I think the https://github.com/conda/conda/issues/6527#issuecomment-353707859 comment above is related to #6556

**Comment by kalefranz** [comment]
I think this issue can be closed now, in lieu of the others that have been opened branching from here.

**Comment by isuruf** [comment]
In case, people from conda-forge see this issue, conda-smithy 2.4.5 has a workaround for this. Just rerender.
