### ISSUE TITLE
centralized control over .condarc

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#654]
For Anaconda Server and centralized installations of Anaconda, or for "centralized" installations of conda, without any Python specific pieces, it seems to me that the condarc should either enable loading of other condarc configs, or have a different look up order, e.g.

CLI option (if you really want to override it)
$CONDARC (another way to override)
/etc/condarc (centralized)
sys.prefix + "condarc" (no dot) (deployment specific)
$HOME/.condarc (user specific)
./.condarc (current directory -- possibly risky)

This is motivated by the situation with Wakari where we really need users to keep our default packages and special channels in their condarc.  If they don't, then they will get "standard" packages for things that we've had to patch (in particular, ipython), and new envs won't work with Wakari.  I could imagine this would be a common situation.

**Comment by ilanschnell** [comment]
There is also an environment variable `CONDARC` which can point explicitly to a condarc file.

**Comment by kalefranz** [comment]
This will/should ultimately be addressed by #2537.
