### ISSUE TITLE
source activate <env> does not work from command line in a folder containing io.py

### ISSUE THREAD

**Issue by nicain** [conda/conda#6549]
I just noticed (after quite a bit of head scratching) that I cannot activate a python environment using source activate from a folder containing a file called io.py:

```
lsb_release -a    
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

To reproduce w/ conda 4.4.0:

```
mkdir tmp
cd tmp
echo raise > io.py
source activate <my_env_name_here>
```

Result:

```
[nicholasc@nicholasc-ubuntu]~/$mkdir tmp
[nicholasc@nicholasc-ubuntu]~/$cd tmp
[nicholasc@nicholasc-ubuntu]~/tmp$echo raise > io.py
[nicholasc@nicholasc-ubuntu]~/tmp$source activate mtrain
Traceback (most recent call last):
  File "/home/nicholasc/anaconda2/bin/conda", line 7, in <module>
    from conda.cli import main
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 10, in <module>
    from .common.compat import iteritems, text_type
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 108, in <module>
    from io import open as io_open  # NOQA
  File "/home/nicholasc/tmp/io.py", line 1, in <module>
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

Similarly, conda --version (called from inside ~/tmp, after the echo above) results in:

```
[nicholasc@nicholasc-ubuntu]~/tmp/$conda --version
Traceback (most recent call last):
  File "/home/nicholasc/anaconda2/bin/conda", line 7, in <module>
    from conda.cli import main
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 10, in <module>
    from .common.compat import iteritems, text_type
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 108, in <module>
    from io import open as io_open  # NOQA
  File "/home/nicholasc/tmp/io.py", line 1, in <module>
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

Same behavior on on macOS (10.12.6), conda version 4.3.30

**Comment by kalefranz** [comment]
This is really interesting.  And I have no idea how to fix it yet 🤔.

Side effect of the current working directory being first on python's `sys.path`.

**Comment by kalefranz** [comment]
Ok #6552 should resolve the issue.  Now, the only files in your current working directory that will be a problem (I think the only ones) will be `os.py` or `sys.py`.  Although I guess it's possible there are a whole host of others.  But at that point, there won't be much else conda can do.

**Comment by kalefranz** [comment]
Reference for `sys.path`: https://stackoverflow.com/a/38403654

**Comment by mingwandroid** [comment]
@nicain, your thoughts would be welcome over at https://github.com/conda/conda/pull/6552

This is just the way Python works IMHO (and it's not very secure).

**Comment by erlkonig** [comment]
I noticed the comment in the ...bin/conda of:

` # The standard first entry in sys.path is an empty string,`

FYI - having a PATH starting with `.:` or just `:` either of which prepends the current directory to the search path is a terrible security hole discouraged since the 1980s.  It's anything BUT standard.

Typically what used to happen on multi-user systems is that folks would drop a script named `ls` or something into `/tmp`, and it would then create set-user-id programs to compromise the unwitting calling user who'd `cd`ed there, then run the normal system `ls`.  Thirty years ago.

**Comment by msarahan** [comment]
You might not like it, but it is the standard behavior for python: https://docs.python.org/3.7/library/sys.html#sys.path

Is it a nasty wart?  Yes.  Take it up with python.org.  It is not appropriate for us to capriciously change behavior that is established and documented upstream.
