### ISSUE TITLE
conda should make downgrading explicitly given packages less likely

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#656]
conda currently tries to pick the latest versions of things possible in a very equal sense (each lower version or build is a penalty, and it tries to minimize the penalty). But maybe it should give packages that are given explicitly at the command line a higher penalty.

**Comment by teoliphant** [comment]
+1

**Comment by kalefranz** [comment]
Conda 4.4 will start associating user-requested packages to channels on first install, and then keeping those channels "sticky" until a user changes the channel.
