### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by Ronggui** [conda/conda#6566]
$ conda update --all
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - anaconda[version='>1']

Current channels:

  - https://conda.anaconda.org/anaconda-fusion/osx-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

$ python --version
Python 3.6.4 :: Anaconda custom (64-bit)

**Comment by kalefranz** [comment]
conda update conda
