### ISSUE TITLE
Cannot Update Conda packages

### ISSUE THREAD

**Issue by chaoticfractal** [conda/conda#6575]
I am currently running into problems when trying to update conda via the terminal. It prints out this message: 

PackagesNotFoundError: The following packages are not available from current channels:

  - anaconda[version='>1']

  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

Don't know how this could have happened but any help will be appreciated. Thanks in advance.

**Comment by kalefranz** [comment]
conda update -n base conda

**Comment by chaoticfractal** [comment]
Thank you
