### ISSUE TITLE
Error installing Python Package 

### ISSUE THREAD

**Issue by sharma-ji** [conda/conda#6578]
I'm getting the following error while installing `pip install rasa-nlu` 

` C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -IC:\Users\Dell\AppData\Local\conda\conda\envs\nlu\include -IC:\Users\Dell\AppData\Local\conda\conda\envs\nlu\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcsrc/twisted/test/raiser.c /Fobuild\temp.win-amd64-3.6\Release\src/twisted/test/raiser.obj
    raiser.c
    c:\users\dell\appdata\local\conda\conda\envs\nlu\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

Note: I have `C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe'` in my environment path

**Comment by kalefranz** [comment]
This has nothing to do with conda. Pip is invoking a compiler, and can’t find a needed header file. Sorry we can’t help more
