### ISSUE TITLE
Win 10: Update to conda 4.4.4 breaks python path

### ISSUE THREAD

**Issue by rnelsonchem** [conda/conda#6579]
I updated to conda 4.4.4 recently, and now when I open a new "Anaconda Prompt" the first thing that is displayed is:
`'python' is not recognized as an internal or external command,
operable program or batch file.`
At this point, I can start Python just fine. However, if I activate and then deactivate another environment, I can't use Python from the command prompt anymore. I get the same error message as above. I've tried rolling back the conda update with revisions, but that broke my installation. (The package pycosat does not get uninstalled properly, which seemed to break my conda install.)

Not sure if this matters, but the text in parentheses before the path has changed. Before the update, It would read as the path to my Anaconda installation. In conda 4.4.4, it reads as `(base)`. This may be intended for this update, but I just thought I would share.

**Comment by kalefranz** [comment]
Do you know what version of conda you had before you updated?

**Comment by rnelsonchem** [comment]
I started with a fresh Anacoda distribution. (Py3.6, Win64)
