### ISSUE TITLE
activate script breaks prompt on 4.4.0-4.4.4

### ISSUE THREAD

**Issue by pitrou** [conda/conda#6580]
I have the following bash prompt:
```
$ echo $PS1
\u@\h:\w$(chg prompt '[\[\e[0;32m\]{\[\e[0;31m\]{status|modified}}{branch}\[\e[0m\]{{update}}] ' 2>/dev/null)$(__git_ps1)$
```
Up to version 4.3.27, conda works fine with that. Starting from 4.4.0, it breaks the prompt when I source the `activate` script:
```
$ echo $PS1
(dask36) \u@\h:\w$(chg prompt [[e[0
```

**Comment by kalefranz** [comment]
Hey Antoine.  Thanks for the report.  Looking into it right now, and hopefully have a patch in 4.4.5 out soon.

Could you do me a favor in helping me debug?  Give me an additional data point...  See if you get the same behavior with conda 4.4.0rc2 from the canary channel

    conda install -c conda-canary conda=4.4.0rc2

**Comment by pitrou** [comment]
@kalefranz thank you! 4.4.0rc2 works fine here.

**Comment by kalefranz** [comment]
Thanks.  That's helpful.

**Comment by kalefranz** [comment]
Out of curiosity, just for myself, are there any public repos for your `chg` and `__git_ps1`  commands/functions?

**Comment by pitrou** [comment]
`chg` is the C command client for Mercurial (basically a version of `hg` with better startup times). I believed it's bundle by default with Mercurial. As for `__git_ps1`, it simply seems to be provided by the official Ubuntu package for git.

**Comment by kalefranz** [comment]
I think #6585 should resolve this issue.

**Comment by kalefranz** [comment]
conda 4.4.5 is in the canary channel, if you'd like to test.

    conda config --add channels conda-canary
    conda update -n root conda

**Comment by pitrou** [comment]
4.4.5 seems to work here. Thank you!
