### ISSUE TITLE
Conda 4.4.4 breaks activation from Git Bash on Windows

### ISSUE THREAD

**Issue by petebachant** [conda/conda#6581]
Running 

    source ~/Anaconda3/Scripts/activate

gives

    bash: /c/ci/conda_1514155543394/_h_env/etc/profile.d/conda.sh: No such file or directory

**Comment by petebachant** [comment]
It looks like the `activate` script has some lines appended to the top:

```bash
#!/bin/sh
_CONDA_ROOT="/c/ci/conda_1514155543394/_h_env"
#!/bin/sh
```

**Comment by petebachant** [comment]
These lines also made it into `conda.sh`:

```bash
_CONDA_EXE="/c/ci/conda_1513805551152/_h_env/Scripts/conda.exe"
_CONDA_ROOT="/c/ci/conda_1513805551152/_h_env"
```

**Comment by kalefranz** [comment]
conda 4.4.5 is in the canary channel, if you'd like to test.

    conda config --add channels conda-canary
    conda update -n root conda

**Comment by petebachant** [comment]
Just tried this out and it doesn't seem to have fixed it. My `activate` script now has this at the top:

```sh
#!/bin/sh
_CONDA_ROOT="$(cygpath '')"
#!/bin/sh
```

which results in

```
cygpath: can't convert empty path
bash: /etc/profile.d/conda.sh: No such file or directory
```

**Comment by petebachant** [comment]
I'm guessing it's because `$win_prefix` isn't defined.

**Comment by kalefranz** [comment]
Yeah I see it. Trying again...

**Comment by kalefranz** [comment]
Having the recipe in two different places. Forgot to update the second place. Doh. 

Also see another problem though too.

**Comment by petebachant** [comment]
Also looks like `$BIN_DIR` wasn't substituted in `conda.sh`:

```sh
_CONDA_EXE="$(cygpath '$BIN_DIR\conda.exe')"
```

**Comment by kalefranz** [comment]
@petebachant We left conda 4.4.5 in canary because of this and a couple of other issues.  Conda 4.4.6 is now in the `conda-canary` channel, and all looks good to me now.  I'll probably push it to `defaults` later today.  Feel free to test and report back though.

**Comment by petebachant** [comment]
Looks good. Nice work. Much appreciated!
