### ISSUE TITLE
Newer versions of conda (4.4.0+) sometimes ignore --no-deps option

### ISSUE THREAD

**Issue by mhearne-usgs** [conda/conda#6590]
My environment:
Scientific Linux release 7.4 (Nitrogen)

I tried to make a simple example of this problem with just one conda dependency, but could not get recent versions of conda to fail in the same way.

See attached env.txt (really a YAML) file.

Take the following steps:
`conda install conda=4.4.0`
`conda env create -f env.txt --force`
`source activate test`
`conda install -y --no-deps -c conda-forge openquake.engine`

For me, this fails with the following error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - openquake.engine -> scipy[version='>=0.13,<0.18']
  - scipy==1.0.0=py35_blas_openblas_201

Repeating these steps (appropriately deleting test env as necessary) with conda 4.4.4 yields the same results. Downgrading conda to 4.3.31 yields what I consider to be the expected results - namely, conda ignores dependencies and installs openquake.engine.

My workaround for now will be to install the older version 
[env.txt](https://github.com/conda/conda/files/1589995/env.txt)

**Comment by reggied** [comment]
I'm experiencing something similar: even thought I specify `--no-deps`, conda is complaining about dependencies that it can't find in the repositories. Any plans for a fix for this? Any workarounds other than using the older version of conda?
