### ISSUE TITLE
"conda update -n base conda" is not updating conda

### ISSUE THREAD

**Issue by MattJEM** [conda/conda#6591]
I appear to be unable to update from conda 4.4.3 to 4.4.4. 4.4.3 installation verified by `conda info`. 

If I run `$ conda update -n base conda`, I receive the following output:

```
Solving environment: done
==> WARNING: A newer version of conda exists. <==
current version: 4.4.3
latest version: 4.4.4
Please update conda by running
$ conda update -n base conda
# All requested packages already installed.
```

`conda update --all` works just fine, and I can update packages individually with no problem as well. I've also tried running `conda update conda`, that doesn't work either.

**Comment by kalefranz** [comment]
What’s the output of `conda info`?

If you’ve got an activated environment, it’s posdible that you got conda installedinto that environment. So basically, twice. Early versions of 4.4 had a problem where “conda update conda” in a non-base environment installed conda into that active environment.

**Comment by MattJEM** [comment]
Thank you for the quick reply! Here's the output of `conda info`

```
     active environment : None
       user config file : /home/mainacct/.condarc
 populated config files : /home/mainacct/anaconda2/.condarc
                          /home/mainacct/.condarc
          conda version : 4.4.3
    conda-build version : 3.2.0
         python version : 2.7.14.final.0
       base environment : /home/mainacct/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/schrodinger/linux-64
                          https://conda.anaconda.org/schrodinger/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /home/mainacct/anaconda2/pkgs
                          /home/mainacct/.conda/pkgs
       envs directories : /home/mainacct/anaconda2/envs
                          /home/mainacct/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.3 requests/2.18.4 CPython/2.7.14 Linux/4.10.0-42-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by kalefranz** [comment]
Looks like you have conda-forge ahead of defaults in your channels list. How about

    conda update -n base conda -c defaults

**Comment by MattJEM** [comment]
Unfortunately, that didn't work.

After that, I tried moving defaults to the top of the channels list, and neither `conda update -n base conda` nor `conda update -n base conda -c defaults` worked.

I then removed all of the channels except for defaults, and _still_ neither command worked.

**Comment by kalefranz** [comment]
Can you give me output for `conda config --show-sources` ?

**Comment by MattJEM** [comment]
Huh, so I fixed it. This is what I did:

First--with defaults as the only channel, tried `conda update -n base conda` and `conda update -n base conda -c defaults` again, neither worked.

Then saw your post, and ran `conda config --show-sources:`
```
==> /home/mainacct/anaconda2/.condarc <==
pinned_packages:
  - bioconda::weblogo
  - schrodinger::pymol-psico
  - schrodinger::pymol
  - anaconda::anaconda
  - anaconda::conda

==> /home/mainacct/.condarc <==
ssl_verify: True
channels:
  - defaults
channel_priority: False
```
This reminded me I had conda pinned to the anaconda channel (whoops) and this appears to have worked:

`conda update -n base conda -c anaconda`:

```
Solving environment: done

## Package Plan ##

  environment location: /home/mainacct/anaconda2

  added / updated specs: 
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2017.11.5          |   py27h71e7faf_0         196 KB  anaconda
    conda-4.4.4                |           py27_0         621 KB  anaconda
    openssl-1.0.2n             |       hb7f436b_0         3.4 MB  anaconda
    ------------------------------------------------------------
                                           Total:         4.2 MB

The following packages will be UPDATED:

    certifi: 2017.11.5-py27h71e7faf_0          --> 2017.11.5-py27h71e7faf_0 anaconda
    conda:   4.4.3-py27_0             anaconda --> 4.4.4-py27_0             anaconda
    openssl: 1.0.2n-hb7f436b_0                 --> 1.0.2n-hb7f436b_0        anaconda

Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi 2017.11.5: ############################################################################################################ | 100% 
conda 4.4.4: ################################################################################################################## | 100% 
openssl 1.0.2n: ############################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

After that, `conda info` to check installation:

```
     active environment : None
       user config file : /home/mainacct/.condarc
 populated config files : /home/mainacct/anaconda2/.condarc
                          /home/mainacct/.condarc
          conda version : 4.4.4
    conda-build version : 3.2.0
         python version : 2.7.14.final.0
       base environment : /home/mainacct/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/mainacct/anaconda2/pkgs
                          /home/mainacct/.conda/pkgs
       envs directories : /home/mainacct/anaconda2/envs
                          /home/mainacct/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.4 requests/2.18.4 CPython/2.7.14 Linux/4.10.0-42-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

This might be irrelevant to you at this point, but for the hell of it I ran `conda update -n base conda` (i.e. without specifying anaconda channel) and got this:

```
Solving environment: done

## Package Plan ##

  environment location: /home/mainacct/anaconda2

  added / updated specs: 
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2017.11.5          |   py27h71e7faf_0         196 KB
    openssl-1.0.2n             |       hb7f436b_0         3.4 MB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following packages will be UPDATED:

    certifi: 2017.11.5-py27h71e7faf_0 anaconda --> 2017.11.5-py27h71e7faf_0
    openssl: 1.0.2n-hb7f436b_0        anaconda --> 1.0.2n-hb7f436b_0       

Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi 2017.11.5: ############################################################################################################ | 100% 
openssl 1.0.2n: ############################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

I'm guessing the `anaconda::conda` pin was the problem, huh?


If you have time, now I have a few questions (can also ask them somewhere else since this is off-topic from the issues):

- Is there are reason to _not_ have the pins `anaconda::conda` and `anaconda::anaconda`, aside from me forgetting they existed? I did so because before I pinned them I tended to get mixed installations of conda (even before conda-forge was at a higher priority than defaults) and the package lists at [anaconda.org](https://anaconda.org) seemed to indicate the anaconda channel had the highest version of conda for 2.7.
- Would it be safer to install conda/anaconda from defaults?
- How does the defaults channel work, and how is it different from the anaconda channel in terms of how it gets packages, which ones go into it, and the stability of said packages?
- I read the best practices is to install packages to a new environment rather than the base. I guess I assumed that most packages outside "special" channels (like bioconda/schrodinger/r) would be needed across all environments. Am I confused?

Thanks for your help!

**Comment by kalefranz** [comment]
> I'm guessing the anaconda::conda pin was the problem, huh?

Yeah, it was.  The `anaconda` channel is really just a bad mirror of `defaults`.  It's always going to be behind.  There's really never any good reason to use it.

It definitely makes sense to pin conda and anaconda, but pin them as `defaults::conda`.

The `defaults` channel is, by default, hard-coded as a "multichannel".  If you were going to configure it yourself, you'd have something in your condarc like

```
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/r
```

So that's what `defaults` is.  Also, as of conda 4.3.27 or so, the channels within multi-channels are prioritized, so packages out of the newer `pkgs/main` will be favored.  repo.continuum.io is edge-cached with Cloudflare, and download performance will be a lot better, compared to pulling stuff from anaconda.org, which is just pulling out of a single s3 bucket (might only matter, depending on location).  Something the anaconda.org team needs to improve in the future; it's on the todo list.

The bigger issue is that the anaconda channel is an amalgamation of `https://repo.continuum.io/pkgs/main`, `https://repo.continuum.io/pkgs/free`, and `https://repo.continuum.io/pkgs/pro`, all dumped together, so priority doesn't work like it's supposed to.  It'll also be usually about 24 hours behind, unless the mirroring fails for some reason, at which point it could be even farther behind.

> I read the best practices is to install packages to a new environment rather than the base. I guess I assumed that most packages outside "special" channels (like bioconda/schrodinger/r) would be needed across all environments. Am I confused?

I might be a little confused by your question...

> I read the best practices is to install packages to a new environment rather than the base.

Yes, that's true.  It's better to use specialized environments that are built for particular tasks, rather than to have a single environment that you try to make work for all tasks.  In the latter, at some point, environments can get big enough and unwieldy enough that finding satisfiable solutions isn't possible.  Simple example: you can't have both python2 and python3 installed in the same environment, even though some projects may require one, and some projects the other.

> I guess I assumed that most packages outside "special" channels (like bioconda/schrodinger/r) would be needed across all environments.

Each environment is completely independent.  Channels aren't necessarily complete though.  Some channels may require the presence of other channels.  `conda-forge`, and I think `bioconda` are fairly complete channels that probably don't lean on `defaults` much.  Let's take the `pytorch` channel though, which has packages released by the `pytorch` maintainer directly.  That channel doesn't have `python` in it, so you'd still need either `defaults`, `conda-forge`, or another channel that has a suitable `python` package to be able to use the `pytorch` channel.

Did I cover most of your questions?

**Comment by MattJEM** [comment]
That was very helpful! I didn't realize that about anaconda.

Just one more question: with regard to installing packages in the base environment--do you recommend installing no packages at all? Or perhaps just defaults or conda-forge?

**Comment by kalefranz** [comment]
Well right now conda is in the base environment.  We have plans to move conda off to its own private environment in the future, but that's not done yet.  The recommendation I guess is just to keep your base environment as minimal or generic as possible, and than have specialized environments for particular tasks.

**Comment by Sedna137** [comment]
A very similar case, and I wonder what went wrong.

No packages can be installed via conda install, it requires conda to be updated.
When I try to update conda the followings were the output.

**case 1:**
`conda update -n base conda -c anaconda` gave me an output

```
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda
```

**case 2:**
`conda update -n base -c defaults conda` had an output 
```
Collecting package metadata (current_repodata.json): done
Solving environment: done
```

___________________________
Here are the conda info and config.
OS: Windows 10


```
conda info:


active environment : base
    active env location : C:\ProgramData\Anaconda2
            shell level : 1
       user config file : C:\Users\arijs\.condarc
 populated config files : C:\Users\arijs\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 2.7.16.final.0
       virtual packages : __cuda=9.0
       base environment : C:\ProgramData\Anaconda2  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\arijs\.conda\pkgs
                          C:\Users\arijs\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\arijs\.conda\envs
                          C:\ProgramData\Anaconda2\envs
                          C:\Users\arijs\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
and

```
conda config --show-sources:

==> C:\Users\arijs\.condarc <==
ssl_verify: True
channels:
  - defaults
restore_free_channel: True

```
