### ISSUE TITLE
conda 4.4.0 breaks activate.bat on windows, seems related to spaces in path?

### ISSUE THREAD

**Issue by robbuckley** [conda/conda#6593]
hi
on upgrading from 4.3.30 > 4.4.0, 

`activate xxx 
`

fails with 

```
'C:/Users/Rob' is not recognized as an internal or external command,
operable program or batch file.
```

Downgrading to 4.3.30 again seemed to fix it

**Comment by robbuckley** [comment]
my home dir is 'C:/Users/Rob Buckley', so perhaps this is due to the space

**Comment by kalefranz** [comment]
Thanks for the report. Duplicate of #6579, and we have a fix in the works.
