### ISSUE TITLE
Anaconda Prompt Error

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6599]
_From @armstrang on December 24, 2017 6:29_

![untitlgged](https://user-images.githubusercontent.com/32195239/34324700-b5360572-e8b6-11e7-9fe6-32007c8cda40.png)

i can't use The anaconda Prompt

_Copied from original issue: ContinuumIO/anaconda-issues#7904_

**Comment by kalefranz** [comment]
_From @nehaljwani on December 24, 2017 14:55_

Could you share the output for:
```
"C:\Users\Sultan Jorgi\Aanconda3\Scripts\conda.exe" info -a
```

In the meantime, see if this helps you to activate the Anaconda3 install:
```
"C:\Users\Sultan Jorgi\Aanconda3\Scripts\activate"
```

**Comment by kalefranz** [comment]
_From @armstrang on December 25, 2017 11:32_


![2](https://user-images.githubusercontent.com/32195239/34339024-5f1586dc-e9aa-11e7-92b9-336e25b754ef.png)
@nehaljwani 
![1](https://user-images.githubusercontent.com/32195239/34339022-5b7bf61e-e9aa-11e7-9eeb-d331edf52c57.png)

**Comment by kalefranz** [comment]
_From @mingwandroid on December 25, 2017 12:15_

@kalefranz, it seems conda 4.4 has regressed wrt spaces in the install location.

**Comment by kalefranz** [comment]
@armstrang In your first, original screen shot, had you just opened the Anaconda prompt window?

**Comment by kalefranz** [comment]
I'm not yet convinced this is a space in path issue, unless I'm missing something.  The user ran

    C:\Users\Sultan Jorgi\Aanconda3\Scripts\activate

rather than

    "C:\Users\Sultan Jorgi\Aanconda3\Scripts\activate"

which is the source of the space-related error that I'm seeing in the screenshots.

**Comment by mbargull** [comment]
In the first screen shot you can see that in, e.g., https://github.com/conda/conda/blob/4.4.4/conda/shell/Library/bin/conda.bat#L37, `%_CONDA_EXE%` was expanded and contained spaces. Replacing every unquoted `%_CONDA_EXE%` with `"%_CONDA_EXE%"` might fix it.

**Comment by kalefranz** [comment]
Here's the block of code in question, from `conda.bat`:

```
@IF "%CONDA_PROMPT_MODIFIER%" == "" GOTO skip_prompt_set_activate
    @CALL SET "PROMPT=%%PROMPT:%CONDA_PROMPT_MODIFIER%=%_empty_not_set_%%%"
:skip_prompt_set_activate
@CALL "%_TEMP_SCRIPT_PATH%"
```

Any ideas?

**Comment by mbargull** [comment]
I think the problem occurred two lines above that in the line I linked to:
https://github.com/conda/conda/blob/4.4.4/conda/shell/Library/bin/conda.bat#L37
```bat
@FOR /F "delims=" %%i IN ('@CALL %_CONDA_EXE% shell.cmd.exe activate %*') DO @SET "_TEMP_SCRIPT_PATH=%%i"
```
which should be
```bat
@FOR /F "delims=" %%i IN ('@CALL "%_CONDA_EXE%" shell.cmd.exe activate %*') DO @SET "_TEMP_SCRIPT_PATH=%%i"
```
I think. The other calls, for de- and re-activate would need the same `"%_CONDA_EXE%"` quoting.

**Comment by mbargull** [comment]
nvm, I think I read something wrong, hold on a sec.

**Comment by kalefranz** [comment]
Yeah I finally saw it.  Guess I'm not awake yet.

**Comment by mbargull** [comment]
The `%_CONDA_EXE%` doesn't need to be quoted as I said before since that is already done in
https://github.com/conda/conda/blob/4.4.4/conda/shell/Library/bin/conda.bat#L5-L7.
I currently wonder how `CMD` interprets
```bat
"_CONDA_EXE="%CONDA_PYTHON_EXE%" "%~dp0..\..\bin\conda""
```
guess I'll just try it out in a VM in a minute..

**Comment by mbargull** [comment]
Maybe the problem is in https://github.com/conda/conda/blob/4.4.4/utils/functions.sh#L195:
```bash
echo "@SET \"_CONDA_EXE=$win_conda_exe\"" > "$prefix/Library/bin/conda.bat"
```
would
```bash
echo "@SET \"_CONDA_EXE=\"$win_conda_exe\"\"" > "$prefix/Library/bin/conda.bat"
```
work? I'm not sure whether `$win_conda_exe` from
```bash
local win_conda_exe="$(cygpath --windows "$conda_exe")"
```
include quotes..

**Comment by kalefranz** [comment]
The `$win_conda_exe` stuff has changed in https://github.com/conda/conda/pull/6587.  Go ahead and look through that, looking for the same thing...

**Comment by kalefranz** [comment]
Actually, this one I've been through before.  I *know* we've settled on

    SET "ENV_VAR=some value with spaces"

as the correct way to quote for `cmd.exe` syntax.

**Comment by kalefranz** [comment]
conda 4.4.5 is in the canary channel, if you'd like to test.

    conda config --add channels conda-canary
    conda update -n root conda
