### ISSUE TITLE
Conda activate broken for Linux compilers

### ISSUE THREAD

**Issue by ehsantn** [conda/conda#6600]
The new compiler packages (gcc_linux-64 7.2.0 24) don't activate in Linux.

```
ERROR: This cross-compiler package contains no program /home/travis/miniconda3/envs/travisci/bin/x86_64-conda_cos6-linux-gnu-cc
ERROR: activate-gcc_linux-64.sh failed, see above for details
ERROR: This cross-compiler package contains no program /home/travis/miniconda3/envs/travisci/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+HOST=x86_64-conda_cos6-linux-gnu
ERROR: This cross-compiler package contains no program /home/travis/miniconda3/envs/travisci/bin/x86_64-conda_cos6-linux-gnu-c++
ERROR: activate-gxx_linux-64.sh failed, see above for details
```

**Comment by mingwandroid** [comment]
Fix is being uploaded now, sorry about the breakage.

**Comment by ehsantn** [comment]
Thanks.

**Comment by bellenger-l** [comment]
Hello, I have the same issue, how can I fix it ? 
```
ERROR: This cross-compiler package contains no program /home/lea/miniconda3/envs/R-pathifier/bin/x86_64-conda_cos6-linux-gnu-c++
ERROR: deactivate-gxx_linux-64.sh failed, see above for details
ERROR: This cross-compiler package contains no program /home/lea/miniconda3/envs/R-pathifier/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: deactivate-gfortran_linux-64.sh made the following environmental changes:
-HOST=x86_64-conda_cos6-linux-gnu
ERROR: This cross-compiler package contains no program /home/lea/miniconda3/envs/R-pathifier/bin/x86_64-conda_cos6-linux-gnu-cc
ERROR: deactivate-gcc_linux-64.sh failed, see above for details
```

Thanks, Lea

**Comment by qizhengyang2017** [comment]
Hello, my conda version is 4.6.7. When I login the terminal, I get the issue, how can I fix it?

> Connection established.
> To escape to local shell, press Ctrl+Alt+].
> 
> Last login: Thu Feb 28 12:07:49 2019 from 122.205.65.80
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-addr2line
> ERROR: activate-binutils_linux-64.sh failed, see above for details
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-cc
> ERROR: activate-gcc_linux-64.sh failed, see above for details
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-cc
> ERROR: deactivate-gcc_linux-64.sh failed, see above for details
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-addr2line
> ERROR: deactivate-binutils_linux-64.sh failed, see above for details
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-addr2line
> ERROR: activate-binutils_linux-64.sh failed, see above for details
> ERROR: This cross-compiler package contains no program /home/qi/miniconda3/envs/py3.6/bin/x86_64-conda_cos6-linux-gnu-cc
> ERROR: activate-gcc_linux-64.sh failed, see above for details
>

**Comment by qizhengyang2017** [comment]
I got a solution at https://stackoverrun.com/cn/q/13088304
`conda remove gcc_linux-64 gcc_impl_linux-64 binutils_linux-64 binutils_impl_linux-64 `

**Comment by peterthorpe5** [comment]
(conda remove gcc_linux-64 gcc_impl_linux-64 binutils_linux-64 binutils_impl_linux-64)

This didn't work for me: conda version 4.8.2,   Redhat   7.7. 

**ERROR: This cross-compiler package contains no program ../x86_64-conda_cos6-linux-gnu-gfortran**

Has anyone got a fix for this? I get it trying to install trinity, braker2 ... (conda create -n trinity_env trinity,  conda create -n braker_env braker2 ....)

thanks Pete

**Comment by seb-mueller** [comment]
It worked for me after reinstalling the above (note first run the `remove` line above):

```
conda install gcc_linux-64 gcc_impl_linux-64 binutils_linux-64 binutils_impl_linux-64
```

**Comment by peterthorpe5** [comment]
Solution that worked for me: This seems to be a bit random but some programs when installed via conda are not executable. So find where they are and chmod a+x  the programs. This has also happened to python and R for me. when you do this it works. (for me anyway).

**Comment by Zachary-Wu** [comment]
I have the same issue.
`ERROR: This cross-compiler package contains no program ... /miniconda3/envs/busco4_env/bin/x86_64-conda_cos6-linux-gnu-gfortran`
and the Solution(chmod -R u+x  .../miniconda3/envs/busco4_env/bin) worked for me. lol
