### ISSUE TITLE
Minconda install error

### ISSUE THREAD

**Issue by veddermatic** [conda/conda#6603]
Obtained and ran installer with these commands on Ubuntu 16.04:

```
wget -nv  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod a+x Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p /vagrant/miniconda
```

Installer runs and aborts with this error:

```
PREFIX=/vagrant/miniconda
installing: python-3.6.3-h6c0c0dc_5 ...
Python 3.6.3 :: Anaconda, Inc.
installing: ca-certificates-2017.08.26-h1d4fec5_0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-h7cc24e2_2 ...
installing: libstdcxx-ng-7.2.0-h7a57d05_2 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.0-h9df7e31_2 ...
Traceback (most recent call last):
  File "/vagrant/miniconda/pkgs/.install.py", line 618, in <module>
    main2()
  File "/vagrant/miniconda/pkgs/.install.py", line 599, in main2
    link_dist(opts.link_dist)
  File "/vagrant/miniconda/pkgs/.install.py", line 454, in link_dist
    link(prefix, dist, linktype)
  File "/vagrant/miniconda/pkgs/.install.py", line 343, in link
    raise Exception("dst exists: %r" % dst)
Exception: dst exists: '/vagrant/miniconda/share/terminfo/e/eterm'
```

I've googled my heart out and can't figure out what to do to resolve this.  I've installed miniconda using this exact method on several machines (virtual or otherwise) and it's installed and run wonderfully.

**Comment by kalefranz** [comment]
I'm stumped.  Ran fine for me in a docker container.  CC @mingwandroid @nehaljwani

**Comment by veddermatic** [comment]
Yeah, that's what is odd; I've run it without issues many times / many places.

**Comment by mingwandroid** [comment]
You are using a case-insensitive file system here I guess? You shouldn't.

To workaround this (with possible adverse side-effects), add the `-f` argument to force file clobbering.

**Comment by mingwandroid** [comment]
FWIW, to run Linux conda on docker on macOS (I assume that's what you are doing here?), I created a case-sensitive volume mounted at `/opt` into which I install all my `conda` Linux aoftware. With APFS this was easy. You should also create an entry in `/etc/fstab` such as:

```
UUID=<FILE_SYSTEM_UUID> /opt apfs rw 0 2
```

**Comment by kalefranz** [comment]
> You are using a case-insensitive file system here I guess? You shouldn't.

Oh that makes sense now.

**Comment by hrpereira** [comment]
Hi there! 
Did you solve your problem?
I have the same problem, but with Anaconda2. I am trying to install it with a user that is not the root. Is this the problem?
Can you help me? Thanks in advance

**Comment by TiemenSch** [comment]
Got this today again on WSL (Ubuntu 18.04 on Windows) with the latest Miniconda3.

It installs fine in my WSL home directory, but fails on some path like /mnt/c/miniconda-linux

**Comment by migunasekera** [comment]
@TiemenSch I am running into the same issue with WSL (Ubuntu 18.04 on Windows) with the latest Miniconda3.

`wget -nv  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod a+x Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh`

And I chose to have mine mounted on my c: directory


`PREFIX=/mnt/c/miniconda3
installing: python-3.7.1-h0371630_7 ...
Python 3.7.1
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libgcc-ng-8.2.0-hdf63c60_1 ...
installing: libstdcxx-ng-8.2.0-hdf63c60_1 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-he6710b0_1 ...
Traceback (most recent call last):
  File "/mnt/c/miniconda3/pkgs/.install.py", line 616, in <module>
    main2()
  File "/mnt/c/miniconda3/pkgs/.install.py", line 597, in main2
    link_dist(opts.link_dist)
  File "/mnt/c/miniconda3/pkgs/.install.py", line 452, in link_dist
    link(prefix, dist, linktype)
  File "/mnt/c/miniconda3/pkgs/.install.py", line 341, in link
    raise Exception("dst exists: %r" % dst)
Exception: dst exists: '/mnt/c/miniconda3/share/terminfo/e/eterm'`

**Comment by msarahan** [comment]
I expect that folder is a case-insensitive filesystem.  As @mingwandroid mentioned above, that's not going to work.  For the linux installers, they MUST be installed to a case-sensitive filesystem.  WSL creates that for your home folder, but /mnt/c doesn't fit that description.  Windows has a case insensitive filesystem by default.

**Comment by migunasekera** [comment]
I see. I have installed conda onto my home directory successfully. Next step is to find out how I can create a path for Windows and LInux without having to specify it in both.

**Comment by FrancescAlted** [comment]
I have just had the same problem.  I fixed it by creating the home directory with the case sensitivity flag active (Windows 10's April 2018 update and on); see a recipe for this at: https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

**Comment by Khalilsqu** [comment]
@FrancescAlted thanks, helped
