### ISSUE TITLE
conda env giving strange non-blocking behavior on Windows

### ISSUE THREAD

**Issue by petebachant** [conda/conda#6607]
Using conda 4.4.4, this is happening in both the Anaconda prompt and Git Bash. To reproduce, simply run `conda env -h`. The prompt will return and it seems like conda is run in the background, producing output a few seconds later. Strangely enough, this doesn't happen when running `conda-env -h`.

**Comment by kalefranz** [comment]
I noticed that too.  Is it new in 4.4, and not that way in 4.3?  I guess it's coming from using `os.execv()`, which apparently behaves differently on Windows than I'm used to on unix systems?

**Comment by kalefranz** [comment]
To clarify, I noticed it yesterday with `conda build`.

**Comment by petebachant** [comment]
I never noticed this sort of thing with any older versions.

**Comment by kalefranz** [comment]
Oh, and I was working in `cmd.exe`, not git bash.  So it's I guess a problem universal to Windows.

**Comment by mingwandroid** [comment]
Urgh, `git bash` is like nails on a blackboard to me. It is `msys2/bash`.

**Comment by petebachant** [comment]
@mingwandroid I'm sorry you feel that way. I feel like it would be less informative to say `msys2/bash`, since this was installed with Git for Windows. Certainly there could be differences if I used the MSYS2 installer.

**Comment by mingwandroid** [comment]
It's just that the package (and hard work) is directly by the `MSYS2` team but because of `Git for Windows` bad naming practices they take all of the credit.

**Comment by kalefranz** [comment]
Yeah that's a little shady.  I agree.

However... Yesterday I downloaded and installed it on a VM so that I could do some debugging stuff.  Seemed like their installer was a lot better than ours.  Was thinking about tracking down what they use...

**Comment by kalefranz** [comment]
Actually, there were also a couple of ideas in their installer flow that I was thinking about ripping off for conda et al.

**Comment by mingwandroid** [comment]
Hah, actually they didn't take the `MSYS2` installer unfortunately. I say that because they picked one that's not cross-platform while the `Qt Installer Framework` is.

**Comment by kalefranz** [comment]
What's something that uses the Qt Installer Framework?  I want to interact with it and try it out...

**Comment by mingwandroid** [comment]
The `Qt SDK` is the best example.

**Comment by mingwandroid** [comment]
Oh, one point about the Qt Installer, I believe it can fetch packages on-demand and can also bake out new installers so you can make your own off-line installers with your own package selection. That's quite nifty.

**Comment by kalefranz** [comment]
conda 4.4.5 is in the canary channel, if you'd like to test.

    conda config --add channels conda-canary
    conda update -n root conda

**Comment by petebachant** [comment]
Looks like it's working as expected, thanks!
