### ISSUE TITLE
Conda env not activated in windows power shell

### ISSUE THREAD

**Issue by quasiben** [conda/conda#661]
In windows power shell conda does not seem to correctly activate an environment:

``` bash
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Users\builder> conda create -n myenv python=2.7
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment C:\Users\builder\Anaconda\envs\myenv:

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.6               |                0   hard-link

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |#################################################| 100%
#
# To activate this environment, use:
# > activate myenv
#
PS C:\Users\builder> activate myenv
Activating environment "myenv"...
PS C:\Users\builder>
```

Notice how the path is not appropriately prepended.  If you print `sys.path` from python you will see that `myenv` is not in the path:

``` bash
PS C:\Users\builder> activate myenv
Activating environment "myenv"...
PS C:\Users\builder> python
Python 2.7.6 |Anaconda 1.9.1 (64-bit)| (default, Nov 11 2013, 10:49:15) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', 'C:\\Users\\builder\\Anaconda\\python27.zip', 'C:\\Users\\builder\\Anaconda\\DLLs', 'C:\\Users\\builder\\Anaconda\
lib', 'C:\\Users\\builder\\Anaconda\\lib\\plat-win', 'C:\\Users\\builder\\Anaconda\\lib\\lib-tk', 'C:\\Users\\builder\\
naconda', 'C:\\Users\\builder\\Anaconda\\lib\\site-packages', 'C:\\Users\\builder\\Anaconda\\lib\\site-packages\\PIL',
C:\\Users\\builder\\Anaconda\\lib\\site-packages\\win32', 'C:\\Users\\builder\\Anaconda\\lib\\site-packages\\win32\\lib
, 'C:\\Users\\builder\\Anaconda\\lib\\site-packages\\Pythonwin', 'C:\\Users\\builder\\Anaconda\\lib\\site-packages\\set
ptools-2.2-py2.7.egg']
>>>
```

This **does** work with windows `cmd.exe`

**Comment by ddofer** [comment]
Issue is also in Windows 8.1   .

**Comment by mlgiter** [comment]
Issue is also present in Windows 8.1 + far 3.0.2785 x86. 
Activation works in cmd.exe.

**Comment by hrzafer** [comment]
Issue is also in Windows 10

**Comment by hydrosquall** [comment]
Issue is also in windows 7

**Comment by MFry** [comment]
Windows 10 with `conda 4.3.16` still has this issue even when system path has `..\Anaconda3\envs`

**Comment by aagostini-tada** [comment]
Perhaps this issue should be reopened? It appears several folks are still having this issue (including me)

**Comment by aelsibaie** [comment]
Having this issue as well. Maybe reopen?

**Comment by FrancisBase** [comment]
Also virtualenvs has the same behaviour of conda.

**Comment by kalefranz** [comment]
Conda does not yet have an officially-supported powershell wrapper.  See https://github.com/conda/conda/issues/626.  Pull requests welcome though.  They should use the framework as established for other shell wrappers in 4.4.

**Comment by napsternxg** [comment]
The issue is still there in Windows 10.

**Comment by zeushera140** [comment]
The issue is still there in Windows 7.

**Comment by LastAncientOne** [comment]
Works on CMD but now it does not work on window powershell. Weird it was working on window powershell about a month ago.

**Comment by avidalfinsa** [comment]
This issue is still open: I could only activate environments in cmd and not in powershell.

**Comment by gamontoya** [comment]
I did everything perfectly fine on Windows 10 using the Anaconda prompt.

**Comment by kalefranz** [comment]
This issue is a duplicate of https://github.com/conda/conda/issues/626. That’s why it is closed.

**Comment by kalefranz** [comment]
Also, a pull request that follows the same patterns as the five other shell wrappers would be very welcome.
