### ISSUE TITLE
Workflow problem that causes permissions errors

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6610]
1. Install miniconda as unprivileged user to `~/miniconda`
2. `sudo su - root`
3. Perform conda operation using the above miniconda install, where package download/extract is required

Result is that `~/miniconda/pkgs` gets populated with files that the unprivileged user doesn't have write access to.

In this particular flow, I think what needs to happen is that, in the process of step 3, the `~/miniconda/pkgs` package cache directory is flipped to read-only for the unprivileged user.

So we're going to be doing *something* with the package cache magic file `~/miniconda/pkgs/urls.txt`, but what exactly?  It's probably going to be something like `chown UID:GID ~/miniconda/pkgs/urls.txt` every time you *write* to that package cache.  And the UID part is simple.  How do we know what the best GID is though?  Do we just use the primary of the current user?  Seems like that would cause problems in certain workflows too.

**Comment by kalefranz** [comment]
Maybe we should check to see if the setgid bit is set on the `~/miniconda/pkgs` directory, in the above example, and do something different if it is?

**Comment by kalefranz** [comment]
And then, how do we handle all of this on Windows? 🤮

**Comment by mingwandroid** [comment]
Could you not detect the destruction about to be wreaked in 3. and say "are you really really sure?"

IMHO this pattern would be followed most often by mistake. Sure you need to figure out what's best when it happens, but I think we need to assist our users here.

**Comment by kalefranz** [comment]
Yeah that's a good point.  If (on unix) the UID of that magic file doesn't match the current user's UID, we could add in an extra confirmation prompt.

Speaking of, we should probably be creating all `pkgs` directories with the setgid bit set.  So, by default, conda should be doing

    mkdir pkgs
    chmod 02775 pkgs

**Comment by kalefranz** [comment]
For people reading this unfamiliar with that setgid bit

https://en.wikipedia.org/wiki/Setuid

> Setting the `setgid` permission on a directory ("`chmod g+s`") 
>
> 1. causes new files and subdirectories created within it to inherit its group ID, rather than the primary group ID of the user who created the file (the owner ID is never affected, only the group ID).
> 2. Newly created subdirectories inherit the `setgid` bit. Thus, this enables a shared workspace for a group without the inconvenience of requiring group members to explicitly change their current group before creating new files or directories.
> 3. only affects the group ID of new files and subdirectories created after the `setgid` bit is set, and is not applied to existing entities.
> 4. does not affect group ID of the files that are created elsewhere and moved to the directory in question. The file will continue to carry the group ID that was effected when and where it was created.
