### ISSUE TITLE
PATH manipulation problems with conda.bat activate on Windows

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#6612]
With conda 4.4.5:

```
C:\Users\builder>echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\PuTTY\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Users\builder\AppData\Local\Microsoft\WindowsApps;

c:/Users/builder/m64/Library/bin/conda.bat activate
'chcp' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\builder>(base) C:\Users\builder>echo %PATH%
c:\Users\builder\m64;c:\Users\builder\m64\Library\mingw-w64\bin;c:\Users\builder\m64\Library\usr\bin;c:\Users\builder\m64\Library\bin;c:\Users\builder\m64\Scripts;c:\Users\builder\m64\bin;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\PuTTY\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Users\builder\AppData\Local\Microsoft\WindowsApps;
```

Notice that `C:\WINDOWS\system32` got dropped which is why `chcp` isn't found (this folder contains lots of important programs too).

**Comment by kalefranz** [comment]
Is this with 4.4.5 in canary?

**Comment by mingwandroid** [comment]
Yes and 4.4.4 too

**Comment by mingwandroid** [comment]
OK, I know what's going on and it's kind of my fault (but I want to make a PR to conda to avoid this anyway).

While investigating https://github.com/ContinuumIO/anaconda/issues/1158 to check whether [this horrible hack](https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch) was to blame I removed it.

This then tripped up [this code](https://github.com/conda/conda/blob/master/conda/activate.py#L368-L374):

```
    def _get_starting_path_list(self):
        path = os.environ['PATH']
        if on_win:
            # on Windows, the python interpreter prepends sys.prefix\Library\bin on startup WTF
            return path.split(os.pathsep)[1:]
        else:
            return path.split(os.pathsep)
```

I will make a PR that will only elide the first element when the interpreter has actually done this (by testing it to see if the value of the first entry is indeed `sys.prefix\Library\bin`.

This will remove a dependency between future conda releasses and this hack in our Python interpreter and will also allow conda to work correctly on other builds of Python on Windows.
