### ISSUE TITLE
4.4.6 causing hanging on getting packages

### ISSUE THREAD

**Issue by jreback** [conda/conda#6634]
in pandas, experiencing timeouts on builds with 4.4.6. everything looks good on 4.4.4 and have pinned.

4.4.4: https://travis-ci.org/pandas-dev/pandas/builds/323574151
4.4.6: https://travis-ci.org/pandas-dev/pandas/builds/323632057 (and multiple restarting of jobs on travis).
4.4.4 (pinned): https://travis-ci.org/pandas-dev/pandas/builds/323780089

xref: https://github.com/pandas-dev/pandas/pull/19025

**Comment by kalefranz** [comment]
Looking now...

**Comment by gfyoung** [comment]
@jreback : FWIW, I remember working around this issue by emptying the `pkgs` directory.  Somehow some of the packages had become corrupted (missing some necessary JSON files)...

**Comment by kalefranz** [comment]
@jreback Gotta be honest, I'm really confused here.  I've spent time trying to reproduce this.  I've gone through each line of the diff (`git diff 4.4.4..4.4.6`).  I don't see any smoking gun at all.

Could you push a PR once more that lets the conda version float again?  Basically revert the commit in https://github.com/pandas-dev/pandas/pull/19025 and see what your CI does with it...  Really confused here right now.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/19062 in CI

**Comment by jreback** [comment]
hmm, actually its looking ok now. maybe was a travis problem.

**Comment by gfyoung** [comment]
> hmm, actually its looking ok now. maybe was a travis problem.

Of course, that would happen. :smile:
