### ISSUE TITLE
Conda 4.4 breaks the Anaconda eco system

### ISSUE THREAD

**Issue by jroberts32** [conda/conda#6635]
To install new packages in Anaconda, it forces you to upgrade to conda 4.4.  Then ENVs and NB_Conda breaks and so on.  This then breaks the NB_Conda package.  In the tab you cannot create new environments. If you do accept the update to 4.4, then Anaconda changes to a "custom" version.

**Comment by jroberts32** [comment]
This seems to be related to #6633.

**Comment by kalefranz** [comment]
Can you file an issue at https://github.com/Anaconda-Platform/nb_conda for the nb_conda stack trace (or whatever other indication you have that it's "broken")?

Anaconda switching to version "custom" is expected behavior.
