### ISSUE TITLE
System wide installation of conda using sudo: best practices?

### ISSUE THREAD

**Issue by kingaj12** [conda/conda#6638]
Can you tell me the best practices for installing conda for multiple users using sudo on a single machine? 

Under sudo the files install with default owner "root".  I have run into all kinds of permissions problems for non-root users.  There doesn't seem to be a simple chmod -R fix, as the Anaconda files are sprinkled all over.

Or does this type of multi-user installation require a license as in [https://docs.anaconda.com/anaconda-scale/](https://docs.anaconda.com/anaconda-scale/)?

**Comment by kalefranz** [comment]
Can you provide the exact sequence of commands you’re using?

**Comment by kingaj12** [comment]
sudo bash Anaconda3-5.0.1-Linux-x86_64.sh     # with all defaults...

Then

    ls -ld anaconda3   
    # returns:      drwxr-x--- 22 root root 4096 Jan  2 12:57 anaconda3

**Comment by kingaj12** [comment]
Looks like it is a Ubuntu issue.  The previous comment reported on an Ubuntu 16.04 installation.

If I do the same thing on Ubuntu 14.04 I get

    ls -ld anaconda_sudo_test
    #returns drwxr-xr-x 22 root root 4096 Jan  3 05:48 anaconda_sudo_test

It's still owned by root, but the permissions allow world read access.

**Comment by kingaj12** [comment]
This was an Ubuntu sudo issue.  See [https://askubuntu.com/questions/991843/permission-problems-installing-with-sudo-between-14-04-and-16-04](https://askubuntu.com/questions/991843/permission-problems-installing-with-sudo-between-14-04-and-16-04).

**Comment by kalefranz** [comment]
Using *just* `sudo` alone, without fully switching users, will often get you into trouble with conda.  We're working to clean that up, but it's not a trivial problem.  Right now, best practice is to *fully* switch users, not just invoke sudo to get another user's permissions.  So, something like

    sudo su root -c "bash Anaconda3-5.0.1-Linux-x86_64.sh -bfp /anaconda"
