### ISSUE TITLE
Conda env: PackagesNotFoundError: The following packages are not available from current channels:    - pkgs

### ISSUE THREAD

**Issue by AlexBThomsen** [conda/conda#6640]
Hi,
I'm using macOS with conda 4.4.6.
 
I'm trying to create my first conda env and want to use an earlier version of python (3.5), so I wrote in the terminal:

input:

         conda create -n backtestingenv python 3.5

output:

         Solving environment: failed

         PackagesNotFoundError: The following packages are not available from current channels:

         - 3.5

        Current channels:
 
         - https://repo.continuum.io/pkgs/main/osx-64
         - https://repo.continuum.io/pkgs/main/noarch
         - https://repo.continuum.io/pkgs/free/osx-64
         - https://repo.continuum.io/pkgs/free/noarch
         - https://repo.continuum.io/pkgs/r/osx-64
         - https://repo.continuum.io/pkgs/r/noarch

Been looking around but not sure what to do. 

Thanks for the help!

**Comment by mbargull** [comment]
Use `conda create -n backtestingenv python=3.5` instead.

**Comment by AlexBThomsen** [comment]
no way thought I tried that! thanks, feeling dumb....

**Comment by 1026tree** [comment]
I have encountered the same problem. How did you solve it?

**Comment by AlexBThomsen** [comment]
I originally wrote "conda create -n backtestingenv python 3.5", but should have written 
"conda create -n backtestingenv python=3.5". Hope this helps.

**Comment by 1026tree** [comment]
Thank you!
