### ISSUE TITLE
The --quiet flag seems to have changed with conda 4.4 and conda-build

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6642]

**Comment by msarahan** [comment]
Originally filed at https://github.com/conda/conda-build/issues/2604

**Comment by kalefranz** [comment]
One solution here I think is that, after https://github.com/conda/conda/pull/6616 gets merged, we should look at detecting if the 'conda' logger is set to level ERROR, and if so, make spinner and ProgressBar disabled/quiet.
