### ISSUE TITLE
Incorrect path installing anaconda-navigator

### ISSUE THREAD

**Issue by scubamut** [conda/conda#6644]
how can I fix the windows path problem?
------------------------------------------------
C:\Users\scuba>conda install -c anaconda anaconda-navigator
Solving environment: done

## Package Plan ##

  environment location: E:\Miniconda3

  added / updated specs:
    - anaconda-navigator

The following NEW packages will be INSTALLED:

    anaconda-client:    1.6.6-py36ha174c20_0     anaconda
    anaconda-navigator: 1.6.11-py36h25c516c_0    anaconda
    anaconda-project:   0.8.2-py36hfad2e28_0     anaconda
    clyent:             1.2.2-py36hb10d595_1     anaconda
    decorator:          4.1.2-py36he63a57b_0     anaconda
    freetype:           2.8-vc14h17c9bdf_0       anaconda [vc14]
    icu:                58.2-vc14hc45fdbb_0      anaconda [vc14]
    ipython_genutils:   0.2.0-py36h3c5d0ee_0     anaconda
    jpeg:               9b-vc14h4d7706e_1        anaconda [vc14]
    jsonschema:         2.6.0-py36h7636477_0     anaconda
    jupyter_core:       4.4.0-py36h56e9d50_0     anaconda
    libpng:             1.6.32-vc14h5163883_3    anaconda [vc14]
    libtiff:            4.0.8-vc14h04e2a1e_10    anaconda [vc14]
    nbformat:           4.4.0-py36h3a5bc1b_0     anaconda
    olefile:            0.44-py36h0a7bdd2_0      anaconda
    pillow:             4.2.1-py36hdb25ab2_0     anaconda
    psutil:             5.4.1-py36h257d382_0     anaconda
    pyqt:               5.6.0-py36hb5ed885_5     anaconda
    python-dateutil:    2.6.1-py36h509ddcb_1     anaconda
    pytz:               2017.3-py36h1d3fa6b_0    anaconda
    pyyaml:             3.12-py36h1d1928f_1      anaconda
    qt:                 5.6.2-vc14h6f8c307_12    anaconda [vc14]
    qtpy:               1.3.1-py36hb8717c5_0     anaconda
    sip:                4.18.1-py36h9c25514_2    anaconda
    sqlite:             3.20.1-vc14h7ce8c62_1    anaconda [vc14]
    tornado:            4.5.2-py36h57f6048_0     anaconda
    traitlets:          4.3.2-py36h096827d_0     anaconda
    zlib:               1.2.11-vc14h1cdd9ab_1    anaconda [vc14]

The following packages will be UPDATED:

    ca-certificates:    2017.08.26-h94faf87_0             --> 2017.08.26-h94faf87_0    anaconda
    certifi:            2017.11.5-py36hb8ac631_0          --> 2017.11.5-py36hb8ac631_0 anaconda
    conda:              4.4.6-py36_0                      --> 4.4.6-py36_0             anaconda
    openssl:            1.0.2n-h74b6da3_0                 --> 1.0.2n-h74b6da3_0        anaconda

The following packages will be DOWNGRADED:

    yaml:               0.1.7-hc54c509_2                  --> 0.1.7-vc14hb31d195_1     anaconda [vc14]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path.
  **path: C:\Users\scuba\C:\Users\scuba\.conda\environments.txt**

_______________________________________________________________________
obviously path above is wrong , but how do I solve this?

**Comment by kalefranz** [comment]
What is the output of `conda info`?

**Comment by kalefranz** [comment]
Also the output of `conda config --show` and `conda config --show-sources`.

**Comment by kalefranz** [comment]
Is there documentation somewhere that told you to use `-c anaconda`?  I think there's some floating around, but we need to get it cleaned up.  In general people shouldn't be using that.  It's just a jumbled of mix of 

  * https://repo.continuum.io/pkgs/main
  * https://repo.continuum.io/pkgs/free
  * https://repo.continuum.io/pkgs/pro

and it also doesn't even go through a good CDN.  Almost always want to use `-c defaults` instead of `-c anaconda`.

**Comment by scubamut** [comment]
(base) C:\Users\scuba>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/msys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
download_only: False
envs_dirs:
  - E:\Miniconda3\envs
  - C:\Users\scuba\AppData\Local\conda\conda\envs
  - C:\Users\scuba\%USERPROFILE%\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - E:\Miniconda3\pkgs
  - C:\Users\scuba\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []

(base) C:\Users\scuba>conda config --show-sources
==> C:\Users\scuba\%USERPROFILE%\.condarc <==
ssl_verify: True
channels:
  - defaults

**Comment by scubamut** [comment]
I am finding anaconda/conda documentation regarding configuration confusing (possibly just me :)), especially regarding:
1) .continuum, .anaconda,  .conda, .jupyter, .ipython
2) %USERPROFILE% (windows, obviously), several users
3) using .condarc - when should I use it and where do I find the json file to edit?
4) how best to configure miniconda3 and to avoid all the above stuff competing
5) I'd like to use anaconda-navigator, but the confusion grows
6) added to this, updating anaconda/minicona/conda, if I get any of the above wrong, fixing the config can be very trying

**Comment by scubamut** [comment]
>" Is there documentation somewhere that told you to use -c anaconda?"

[]https://anaconda.org/anaconda/anaconda

Installers
conda install 
 linux-ppc64le  v5.0.0
 linux-64  v5.0.1
 win-32  v5.0.1
 osx-64  v5.0.1
 linux-32  v5.0.1
 win-64  v5.0.1

To install this package with conda run:
**conda install -c anaconda anaconda**

**Comment by scubamut** [comment]
I'm sure it must be easy to work aroud this?

![image](https://user-images.githubusercontent.com/1937564/34640400-a68421b4-f2fa-11e7-8c49-cdf2b9aa72c3.png)

Need your assistance please.

**Comment by mbargull** [comment]
I'm guessing your environment variables could be set to wrong values.
Can you show the output of
```cmd
set
```
or just
```cmd
echo HOME=%HOME%
echo USERPROFILE=%USERPROFILE%
echo HOMEDRIVE=%HOMEDRIVE%
echo HOMEPATH=%HOMEPATH%
```
? (to compare with correct default values, see https://en.wikipedia.org/wiki/Environment_variable#Default_values)

**Comment by scubamut** [comment]
(root) E:\Miniconda3\Scripts>echo HOME=%HOME%
HOME=%USERPROFILE%

(root) E:\Miniconda3\Scripts>echo USERPROFILE=%USERPROFILE%
USERPROFILE=C:\Users\scuba

(root) E:\Miniconda3\Scripts>echo HOMEDRIVE=%HOMEDRIVE%
HOMEDRIVE=C:

(root) E:\Miniconda3\Scripts>echo HOMEPATH=%HOMEPATH%
HOMEPATH=\Users\scuba

**Comment by mbargull** [comment]
Hi @scubamut, sorry for coming back to this only now. I'm surprised, as I had assumed those environment variables were set to some erroneous values. But those look fine to me. Do you still see the same error if you use `conda` `4.4.8` or `4.4.9`? If yes, can you show the output for
```bat
echo HOME=%HOME%
conda config --show envs_dirs
set "HOME=%USERPROFILE%"
echo HOME=%HOME%
conda config --show envs_dirs
```
?
