### ISSUE TITLE
Conda Deactivate Fails in MacOS after Pycharm Use

### ISSUE THREAD

**Issue by MR-T77** [conda/conda#6648]
Have a conda environment that was working perfectly until I created a project in Pycharm that used this env interpreter.

In source activate <environment> I get lot's of verbose (that i didn't get up until recently):
```
$ source activate bss
INFO: activate_clang_osx-64.sh made the following environmental changes:
+AR=/Users/mactobe/anaconda/envs/bss/bin/x86_64-apple-darwin13.4.0-ar
+AS=/Users/mactobe/anaconda/envs/bss/bin/x86_64-apple-darwin13.4.0-as
+CC=x86_64-apple-darwin13.4.0-clang
+CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
+CHECKSYMS=/Users/mactobe/anaconda/envs/bss/bin/x86_64-apple-darwin13.4.0-checksyms
...
```
In source deactivate I get an error:
```
Failed to import the site module
Traceback (most recent call last):
  File "/Users/mactobe/anaconda/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/Users/mactobe/anaconda/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/mactobe/anaconda/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/mactobe/anaconda/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/mactobe/anaconda/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/mactobe/anaconda/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/Users/mactobe/anaconda/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/mactobe/anaconda/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0
```
Does anyone have a hint on this?
Thx in advance.

**Comment by kalefranz** [comment]
Ping @mingwandroid.  Probably the best to help out here.

**Comment by nehaljwani** [comment]
Try updating python in the base environment?

**Comment by MR-T77** [comment]
@nehaljwani How updating root env python may help me in a different env. Conda root environment is working fine.

**Comment by mingwandroid** [comment]
@nehaljwani is correct. To deactivate from this newer env that contains our new compilers to an older one (i.e. your root one) you must update the python in your root env.

**Comment by MR-T77** [comment]
Ok, thanks. To prevent future issues, could you please just clear this doubt: this issue may happen when I have some CondaEnv with a newer Python than the root env? Ie, does the root environment has to have the newest Python version?
On the other hand, is this problem only connected with Python version or is it related to other pieces of software?
Thanks again.

**Comment by MR-T77** [comment]
Just a further question: Do you advice on a safe way to update python in my root environment? (according to [this thread](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/7bceY_GQOUk), there are several latent problems when upgrading root environment).
Thanks.

**Comment by mingwandroid** [comment]
This was a one off thing that's fixed now provided your root Python is greater than a certain build number. There's no general 'root Python must be newer' dependency here.

**Comment by MR-T77** [comment]
Thanks @mingwandroid. I've updated root python and problems disappeared (although I get lot's of verbose when activating our deactivating that particular "bss" condaenv. Any idea why?)

**Comment by mingwandroid** [comment]
Yes, I am detailing exactly what env. vars got changed by activating and deactivate our new compilers so that people are not surprised and do not spend ages wondering why `x86_64-conda_cos6-linux-gnu-gcc` got used in some software build instead of `gcc`.

But your question just reinforces that sometimes people do not read or care for the information that is presented to them :-(

**Comment by MR-T77** [comment]
I'm sorry. I understand your point, but the interpretation is not correct: the right interpretation is not everyone has the same technical knowledge (thus there is info that is "unreadable"). That is my case, and I'm sure there are lot's of Conda users with the same (lack of) abilities. It is not lack of interest.
Thanks.

**Comment by mingwandroid** [comment]
Yeah, there's not much I can do here, if they don't mean much to you then just ignore them. That they don't say "WARNING" nor "ERROR" but do say "INFO" indicates that you probably do not need to worry.

**Comment by MR-T77** [comment]
Don't get me wrong, I'm appreciated for your informed help (i was just explaining I'm not able to follow your reasoning as I would like). If you re-read the above lines, you can figure that I'm trying to learn (I saw a new behaviour, and was trying to figure why). I believe I have learnt something.
Thanks.

**Comment by mingwandroid** [comment]
OK no problem, sorry if I can across as rude, it wasn't my intention.

**Comment by smcinerney** [comment]
> This was a one off thing that's fixed now provided your root Python is greater than a certain build number. There's no general 'root Python must be newer' dependency here.

I just hit this same issue (and with conda 4.5.11; python 3.7.1 h46c1a51_0). So it doesn't seem to be a one-off:

(base) $ pip upgrade kaggle
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 17, in <module>
    from pip._internal.locations import USER_CACHE_DIR, src_prefix
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/locations.py", line 83, in <module>
    site_packages = sysconfig.get_path("purelib")
  File "/opt/anaconda3/lib/python3.7/sysconfig.py", line 514, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/opt/anaconda3/lib/python3.7/sysconfig.py", line 504, in get_paths
    return _expand_vars(scheme, vars)
  File "/opt/anaconda3/lib/python3.7/sysconfig.py", line 165, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/opt/anaconda3/lib/python3.7/sysconfig.py", line 552, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/opt/anaconda3/lib/python3.7/sysconfig.py", line 423, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0'

**Comment by nehaljwani** [comment]
@smcinerney Type: `/opt/anaconda3/bin/conda update -y python`
