### ISSUE TITLE
Conflict between conda and anaconda-navigator

### ISSUE THREAD

**Issue by o12johns** [conda/conda#6658]
conda clean --all deletes a configuration directory that anaconda-navigator uses to populate its home page.

To see that anaconda-navigator uses ~/anaconda3/pkgs/cache to store the
contents of its home page:

Zeus:~ ojohns$ navigator-updater #Dismiss the panel that appears
Zeus:~ ojohns$ cd anaconda3/pkgs/
Zeus:pkgs ojohns$ ls cache
0cdb2265.json	0cdb2265.q	9cd9d6b5.json	9cd9d6b5.q	abae4451.json	abae4451.q	d85a531e.json	d85a531e.q
Zeus:pkgs ojohns$ anaconda-navigator #See correct home page.  Then close window.
Zeus:pkgs ojohns$ mv cache acache
cache -> acache
Zeus:pkgs ojohns$ anaconda-navigator  #See empty home page.  Then close window.
Zeus:pkgs ojohns$ mv acache/ cache
acache/ -> cache
Zeus:pkgs ojohns$ anaconda-navigator #See correct home page once again

To see that conda clean —all deletes the folder ~/anaconda3/pkgs/cache:

Zeus:pkgs ojohns$ navigator-updater #Dismiss the panel that appears.
Zeus:pkgs ojohns$ cd ~/anaconda3/pkgs
Zeus:pkgs ojohns$ ls cache
0cdb2265.json	0cdb2265.q	9cd9d6b5.json	9cd9d6b5.q	abae4451.json	abae4451.q	d85a531e.json	d85a531e.q
Zeus:pkgs ojohns$ conda clean --all -y
Cache location: 
There are no tarballs to remove
Cache location: 
There are no unused packages to remove
source cache (/Users/ojohns/anaconda3/conda-bld/src_cache)
Size:                                           0 B

git cache (/Users/ojohns/anaconda3/conda-bld/git_cache)
Size:                                           0 B

hg cache (/Users/ojohns/anaconda3/conda-bld/hg_cache)
Size:                                           0 B

svn cache (/Users/ojohns/anaconda3/conda-bld/svn_cache)
Size:                                           0 B

Total:                                          0 B
Removing /Users/ojohns/anaconda3/conda-bld/src_cache
Removing /Users/ojohns/anaconda3/conda-bld/git_cache
Removing /Users/ojohns/anaconda3/conda-bld/hg_cache
Removing /Users/ojohns/anaconda3/conda-bld/svn_cache
Zeus:pkgs ojohns$ ls cache
ls: cache: No such file or directory
Zeus:pkgs ojohns$

**Comment by o12johns** [comment]
note:  This bug is with conda 4.4.6 and anaconda-navigator 1.6.11

**Comment by kalefranz** [comment]
@goanpeca What do you think we should do here?

**Comment by o12johns** [comment]
This is hard because it is not actually a bug in either package.  Or, rather it is a bug in both packages.  Two solutions:
(1) anaconda-navigator should NOT label a config file with the name "cache".  And what is it doing in ~/anaconda3/pkgs anyway?  So rename it or move it.
(2) conda should not zap directories without acknowledging that it is zapping them.  Zapping ~/anaconda3/pkgs/cache is a mistake
So, I guess the developers of both packages should decide who fixes it.  Or maybe both should fix it.

**Comment by goanpeca** [comment]
I don't understand, as soon as the index is updated, things should go back to "normal", no ?

**Comment by kalefranz** [comment]
It's probably wrong to call the cache directory a configuration directory.  But I think I understand the issue.  Navi *does* use stuff in that directory.  @goanpeca is investigating behavior in Navi after you `rm -rf` it.  Navi should be smart enough to ask conda to refresh it on its own.  If not, I guess we're about to see what happens.

**Comment by o12johns** [comment]
Reply to "I don't understand".  Do the following to see the problem in action.  Things do not go back to normal.  The anaconda-navigator home page has no apps after conda clean --all is run.  You can always get them back (bug work-around) by running navigator-updater.  Then all is OK again.

Zeus:~ ojohns$ navigator-updater #Dismiss the panel that appears
Zeus:~ ojohns$ anaconda-navigator #See correct home page with apps on it. Then close it.
Zeus:~ ojohns$ conda clean --all -y
Cache location: 
There are no tarballs to remove
Cache location: 
There are no unused packages to remove
source cache (/Users/ojohns/anaconda3/conda-bld/src_cache)
Size:                                           0 B

git cache (/Users/ojohns/anaconda3/conda-bld/git_cache)
Size:                                           0 B

hg cache (/Users/ojohns/anaconda3/conda-bld/hg_cache)
Size:                                           0 B

svn cache (/Users/ojohns/anaconda3/conda-bld/svn_cache)
Size:                                           0 B

Total:                                          0 B
Removing /Users/ojohns/anaconda3/conda-bld/src_cache
Removing /Users/ojohns/anaconda3/conda-bld/git_cache
Removing /Users/ojohns/anaconda3/conda-bld/hg_cache
Removing /Users/ojohns/anaconda3/conda-bld/svn_cache
Zeus:~ ojohns$ anaconda-navigator #Now see an empty home page
Zeus:~ ojohns$

**Comment by goanpeca** [comment]
@o12johns and @kalefranz the thing is that Anaconda Navigator does not require an internet connection on startup and by default does not induce conda to make a package cache update (which is triggered by any conda operation requestion repodata) so:

>conda clean --all deletes a configuration directory that anaconda-navigator uses to populate its home page.

Is an incorrect assessment as that is not a config directory. The bug here is that Navigator should display any installed apps, and upon request for index update (The button  on the environment tabs) it should repopulate and "fix the home" so I can make the `Update Index button be available on the Home page and make sure installed apps are showing (that is the bug in this case)

---

@kalefranz I don't want to force an internet request via conda to update the index on Navigator on startup in case the cache is empty.  Thoughts?

**Comment by o12johns** [comment]
So, OK, ~/anaconda3/pkgs/cache is not a configuration file.  Still, it is an error for conda clean --all to zap it.  Why/how is conda clean doing that?  Rather than making navigator jump through hoops to recover when conda clean --all zaps one of its files, why not just stop conda clean --all from doing that.  It now seems to me to be a conda bug and not a navigator bug.

**Comment by goanpeca** [comment]
>So, OK, ~/anaconda3/pkgs/cache is not a configuration file. Still, it is an error for conda clean --all to zap it

Well because that is the point of that command, I dont think is a conda bug per se, and there are workarrounds on the navigator  side :-), in the meantime as I suggested you could just run the `Update Index` button on the environments tab.

**Comment by goanpeca** [comment]
@o12johns will close this one and track on https://github.com/ContinuumIO/anaconda-issues/issues/8066 as it is a change to Navigator
