### ISSUE TITLE
Conda error regarding libopenblasp

### ISSUE THREAD

**Issue by kirk86** [conda/conda#6675]
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory

Everything was working fine. After update of packages and conda environment I keep getting this error.

**Comment by kalefranz** [comment]
You're going to have to give more details.  Exact step-by-step details necessary to reproduce the problem you're seeing, and any other relevant information you can think of.  Also output of `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls`.

**Comment by kirk86** [comment]
I think this might have to do with corrupted mkl but I am not 100% sure. The thing is that I've done a recent reinstall of the conda environment (couldn't wait) so even if I wanted I can't provide more details. Thus, I am closing this.
