### ISSUE TITLE
Python  cant run despite have its path defined

### ISSUE THREAD

**Issue by OwiyeD** [conda/conda#6677]
Hello, I have a problem with running a python that I just installed on windows7. C:\Python34\Scripts this is the path in environment variable. Kindly help.

**Comment by kalefranz** [comment]
Please give step-by-step instructions and all details necessary to reproduce the problem you're seeing.

**Comment by LeeGeong** [comment]
I creat a new envirment , but can't activated , error 
C:\Users\Administrator>EFIX=C:\ProgramData\Anaconda3\envs\python27"
'EFIX' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>OMPT_MODIFIER=(python27) "
'OMPT_MODIFIER' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>THON_EXE=C:\ProgramData\Anaconda3\python.exe"
'THON_EXE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>LVL=1"
'LVL' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by kalefranz** [comment]
There is not sufficient information here to help.  If you continue to have problems and can isolate a particular bug, please file a new issue.
