### ISSUE TITLE
Installing pymssql to use Orange3

### ISSUE THREAD

**Issue by L0GQ** [conda/conda#6687]
Hi, 

I am new to Python. I would like to install MSSQL connector to Orange3, however when I do that I got an error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pymssql
  - zict
Use "conda info <package>" to see the dependencies for each package.

Not sure what to do, anyone can help me?

**Comment by wuzhenda** [comment]
these links may help you:
https://github.com/pymssql/pymssql/issues/473
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql

**Comment by L0GQ** [comment]
Thanks.
