### ISSUE TITLE
Add quiet option to condarc

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#669]
As per @srossross's request.

**Comment by kerrywatson1** [comment]
@asmeurer don't we have a silent mode now?

**Comment by asmeurer** [comment]
I don't think a condarc option was ever added.

**Comment by kerrywatson1** [comment]
@asmeurer thanks, then we need to add this before we document it. Can you remove documentation label?

**Comment by kalefranz** [comment]
Done.
