### ISSUE TITLE
Add package data to json info on conda-meta folder

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#6692]
Currently there is no way to know if a given package is an application by looking at the files located at conda-meta. I think it would be benefitial (for some things on Navigator) to have this information available, at the very least, the app_entry

**Comment by kalefranz** [comment]
Right way to do this is just to add

    app_entry = StringField(required=False, default=None, default_in_dump=False)

to `conda.models.index_record.IndexJsonRecord`.  Add a comment explaining what it is and what it's for.
