### ISSUE TITLE
Outdated conda notification does not respect `-q` arg

### ISSUE THREAD

**Issue by ihleonard-c3** [conda/conda#6695]
The notify_outdated_conda warning checks only `if context.notify_outdated_conda`, but I think it should check `if context.notify_outdated_conda and not context.quiet`. If I specify the `-q` flag, I don't want to see this warning.

**Comment by kalefranz** [comment]
Seems reasonable to me.

**Comment by ShubhGupta2125** [comment]
I am a beginner and would like to work on this issue. Can i take it up and be guided along?

**Comment by kalefranz** [comment]
Yup. Go for it.  Just change

    if context.notify_outdated_conda:

to

    if context.notify_outdated_conda and not context.quiet:

and submit a PR
