### ISSUE TITLE
`conda activate` on 4.4.7 doesn't complete unless I press enter twice

### ISSUE THREAD

**Issue by boulund** [conda/conda#6701]
I'm experiencing a strange issue. I was running conda `4.4.3`, and was experiencing issues with extreme slowness to activate the base environment. The time to run `conda activate` was really long, we're talking several minutes. I've had this issue ever since I upgraded to conda `4.4.3` from `4.3.<something>`. 
I updated to version `4.4.7` just now and after some trial and error I realized that running `conda activate` doesn't complete until I press Enter a few times.
First I thought it was a random fluke, but some more testing showed that it activates without problems in under a second if I just press Enter twice after calling `conda activate`. 

My conda installation is fairly old and has been in use since about a year ago (original install date was beginning of February 2017, I think). I'm running Scientific Linux 7.4 (i.e. CentOS).

What can I do to troubleshoot this, to find what's causing this issue?

**Comment by kalefranz** [comment]
Are you running bash as your terminal shell?  If so, execute

    set -x

which is sorta like "debug mode" for bash.  It'll spit out a ton of stuff that's happening behind the scenes.  Then run the slow `conda activate` and share here with more detail.

**Comment by boulund** [comment]
Of course! Thanks. Off to a good start!  :)

```
[fredrik.boulund@ctmr-nas ~]$ set -x
++ printf '\033]0;%s@%s:%s\007' fredrik.boulund ctmr-nas '~'
[fredrik.boulund@ctmr-nas ~]$ conda activate
+ conda activate
+ '[' 1 -ge 1 ']'
+ local cmd=activate
+ shift
+ case "$cmd" in
+ _conda_activate
+ '[' -n '' ']'
+ local ask_conda
++ PS1='[\u@\h \W]\$ '
++ /home/ctmr/anaconda3/bin/conda shell.posix activate
+ ask_conda='PS1='\''(base) [\u@\h \W]\$ '\''
export CONDA_DEFAULT_ENV='\''base'\''
export CONDA_PREFIX='\''/home/ctmr/anaconda3'\''
export CONDA_PROMPT_MODIFIER='\''(base) '\''
export CONDA_PYTHON_EXE='\''/home/ctmr/anaconda3/bin/python'\''
export CONDA_SHLVL='\''1'\''
export PATH='\''/home/ctmr/anaconda3/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin'\''
. "/home/ctmr/anaconda3/etc/conda/activate.d/java_home.sh"
. "/home/ctmr/anaconda3/etc/conda/activate.d/set_blastmat_env_variable.sh"
. "/home/ctmr/anaconda3/etc/conda/activate.d/activate-r-base.sh"'
+ eval 'PS1='\''(base) [\u@\h \W]\$ '\''
export CONDA_DEFAULT_ENV='\''base'\''
export CONDA_PREFIX='\''/home/ctmr/anaconda3'\''
export CONDA_PROMPT_MODIFIER='\''(base) '\''
export CONDA_PYTHON_EXE='\''/home/ctmr/anaconda3/bin/python'\''
export CONDA_SHLVL='\''1'\''
export PATH='\''/home/ctmr/anaconda3/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin'\''
. "/home/ctmr/anaconda3/etc/conda/activate.d/java_home.sh"
. "/home/ctmr/anaconda3/etc/conda/activate.d/set_blastmat_env_variable.sh"
. "/home/ctmr/anaconda3/etc/conda/activate.d/activate-r-base.sh"'
++ PS1='(base) [\u@\h \W]\$ '
++ export CONDA_DEFAULT_ENV=base
++ CONDA_DEFAULT_ENV=base
++ export CONDA_PREFIX=/home/ctmr/anaconda3
++ CONDA_PREFIX=/home/ctmr/anaconda3
++ export 'CONDA_PROMPT_MODIFIER=(base) '
++ CONDA_PROMPT_MODIFIER='(base) '
++ export CONDA_PYTHON_EXE=/home/ctmr/anaconda3/bin/python
++ CONDA_PYTHON_EXE=/home/ctmr/anaconda3/bin/python
++ export CONDA_SHLVL=1
++ CONDA_SHLVL=1
++ export PATH=/home/ctmr/anaconda3/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin
++ PATH=/home/ctmr/anaconda3/bin:/home/fredrik.boulund/code/scripts:/home/fredrik.boulund/bin:/home/ctmr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin
++ . /home/ctmr/anaconda3/etc/conda/activate.d/java_home.sh
+++ export JAVA_HOME_CONDA_BACKUP=
+++ JAVA_HOME_CONDA_BACKUP=
+++ export JAVA_HOME=/home/ctmr/anaconda3
+++ JAVA_HOME=/home/ctmr/anaconda3
++ . /home/ctmr/anaconda3/etc/conda/activate.d/set_blastmat_env_variable.sh
+++ export BLASTMAT=/home/ctmr/anaconda3/data/
+++ BLASTMAT=/home/ctmr/anaconda3/data/
++ . /home/ctmr/anaconda3/etc/conda/activate.d/activate-r-base.sh
+++ R CMD javareconf


+ _conda_hashr
+ case "$_CONDA_SHELL_FLAVOR" in
+ hash -r
++ printf '\033]0;%s@%s:%s\007' fredrik.boulund ctmr-nas '~'
```
You can probably easily spot the two line breaks towards the end, after `R CMD javareconf` that seems to stall until I press enter twice....

Manually running `R CMD javareconf` gets me this:

```
 (base) [fredrik.boulund@ctmr-nas ~]$ R CMD javareconf
+ R CMD javareconf
Java interpreter : /home/ctmr/anaconda3/jre/bin/java
Java version     : 1.8.0_121
Java home path   : /home/ctmr/anaconda3
Java compiler    : /home/ctmr/anaconda3/bin/javac
Java headers gen.: /home/ctmr/anaconda3/bin/javah
Java archive tool: /home/ctmr/anaconda3/bin/jar

trying to compile and link a JNI program
detected JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
detected JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
gcc -std=gnu99 -I/home/ctmr/anaconda3/lib/R/include -DNDEBUG -I/home/ctmr/anaconda3/include -I/home/ctmr/anaconda3/include/linux  -I/home/ctmr/anaconda3/include   -fpic  -I/home/ctmr/anaconda3/include  -c conftest.c -o conftest.o
gcc -std=gnu99 -shared -L/home/ctmr/anaconda3/lib/R/lib -L/home/ctmr/anaconda3/lib -lgfortran -o conftest.so conftest.o -L/home/ctmr/anaconda3/jre/lib/amd64/server -ljvm -L/home/ctmr/anaconda3/lib/R/lib -lR


JAVA_HOME        : /home/ctmr/anaconda3
Java library path: $(JAVA_HOME)/jre/lib/amd64/server
JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
Updating Java configuration in /home/ctmr/anaconda3/lib/R
mv: replace '/home/ctmr/anaconda3/lib/R/etc/Makeconf', overriding mode 0644 (rw-r--r--)?
mv: replace '/home/ctmr/anaconda3/lib/R/etc/ldpaths', overriding mode 0644 (rw-r--r--)?
Done.

++ printf '\033]0;%s@%s:%s\007' fredrik.boulund ctmr-nas '~'
```
Here you see the two mv commands that require interactive confirmation to overwrite `anaconda3/lib/R/etc/Makeconf` and `anaconda3/lib/R/etc/ldpaths`. This is probably not what's supposed to happen, right?

**Comment by boulund** [comment]
We are running our conda installation in a shared folder, and it seems these two files were created by another user with a different umask set, leading to incorrect group permissions set on those two files. 
Fixed it with a `sudo chmod g+w /anaconda3/lib/R/etc/{Makeconf,ldpaths}`! 

Thanks for the help @kalefranz !

**Comment by kalefranz** [comment]
You're welcome!  `set +x` gets you out of the annoying debug mode if you need.  Guessing you've already just restarted your terminal though :)

**Comment by kalefranz** [comment]
BTW, here's a case where conda really needs to start creating new directories (especially root directories of new prefixes and `pkgs` directories), with `chmod 02775` or `chmod g+s`.

**Comment by boulund** [comment]
@kalefranz we have our shared conda folder in a shared folder with `g+s` permissions set, but if users don't have a umask of `0002` they don't set the same group permissions when new files and folders are created with conda.

**Comment by boulund** [comment]
Apparently just changing the permissions wasn't enough. It seems the `javareconf` that is being run during conda initalization (like so: `R CMD javareconf`, in `anaconda3/etc/conda/activate.d/activate-r-base.sh`) fails to move the new `Makeconf` and `ldpath` files that are create due to differing permissions (see Errors below), as we need to have `rw-rw-r--` permissions in our shared anaconda3 folder. 

Now I solved it temporarily by making a very small change to `anaconda3/lib/R/bin/javareconf`, on line 414:

```
- mv -fv "${file}.new" "${file}"
+ mv "${file}.new" "${file}"
```
so it justs overwrite the old files with the new without prompting, but writing a line about it into the log output. 

Errors:
``` 
mv: replace '/home/ctmr/anaconda3/lib/R/etc/Makeconf', overriding mode 0644 (rw-r--r--)? 
mv: replace '/home/ctmr/anaconda3/lib/R/etc/ldpaths', overriding mode 0644 (rw-r--r--)? 
```

**Comment by boulund** [comment]
Totally forgot about this and recently update R in my base conda environment and got stuck with the same thing again. Performed the same fix as previously; change the `mv` statement on line 414 in `anaconda3/lib/R/bin/javareconf`.

**Comment by boulund** [comment]
This just happened again, after an accidental change to the installed version of R in the base environment.

**Comment by mingwandroid** [comment]
> This is probably not what's supposed to happen, right?

It is meant to happen, why are your permissions incorrect?

> and it seems these two files were created by another user with a different umask set

This is your bug then. Do not do this.

**Comment by mingwandroid** [comment]
> mv -fv

Why do you want this to be verbose?

**Comment by mingwandroid** [comment]
I have made changes to attempt to fix this, but I am worried they could cause issues. Really, incorrect permissions *is* a user error. If you randomly change the permissions of our files then you should expect breakage. You need to unify your umask settings here if you intend to share things or configure your share to ignore your problematic permissions.

**Comment by boulund** [comment]
I appreciate the time you've spent looking into this, but of course you shouldn't implement the fix if there's a risk it will cause issues for other users.

I wanted `mv -fv` to be verbose to remind me of my change when if I ever skim through the log. It was not my intention that it should be verbose for all conda users. 

I'm happy without any changes from your side, as I realize this is due to a misconfiguration on our end :). This issue was closed because the issue was solved, and I commented here today mostly to potentially help others experiencing the same issue.

**Comment by nick-youngblut** [comment]
My research group was struggling with this problem for some time (even with the latest versions of conda). Thanks @boulund for the fix! I just want to make a general comment for others experiencing issues like this one: 

There seems to be a general assumption with the conda development that it will be used in a particular way (admin installs for all users, or users have their own private installs). We have a situation where our admin will not install conda (he thinks it's a big security risk after he assessing the code), and having private conda installs for each person generates too many files on our file system (eg., 1x minconda install with 5-10 envs can be 100's of 1000's of files; multiply that times >25 people, and that's too many files on our file system). So, we have one miniconda install for all users, but the install is not managed by the admin. It works, except when we run into permissions issues like this one with javareconf, but there really isn't any support for this type of setup.

**Comment by kalefranz** [comment]
> he thinks it's a big security risk after he assessing the code

Would very much appreciate additional detail. Can you elaborate?
