### ISSUE TITLE
Request: --user flag on install

### ISSUE THREAD

**Issue by consideRatio** [conda/conda#6702]
`pip install --user` installs packages inside the home directory of the user. It's great if you have mounted your home directory inside a docker container and want to have some additional packages persistent in between container restarts.

It would be great if that was available for the conda package manager as well!

**Comment by kalefranz** [comment]
Can you share a set of `docker` commands, Dockerfiles, etc that demonstrate the workflow here with pip?

**Comment by consideRatio** [comment]
**A more general response to "Why have a --user flag?"** 
https://stackoverflow.com/a/42989020/2220152
>pip defaults to installing Python packages to a system directory (such as /usr/local/lib/python3.4). This requires root access.
--user makes pip install packages in your home directory instead [within `~.local/`], which doesn't require any special privileges.

**My specific situation:**

I'm a user living only inside a docker container, and an administrator is providing me with access to it will always mount one single directory that will allow my work to persist in between container restarts: `/home/erik`.

To simulate this, you (as administrator) can run...
```bash
docker run -it --rm -v <choose_some_dir_on_host>:/home/erik  jupyter/minimal-notebook /bin/bash
```

Then, you as a user inside the container could run...
```bash
pip install scrapy
```

Do some work depending on scrapy, quit, and later come back, needing to do `pip install scrapy` again. But thanks to the `--user` flag provided by pip, I would get my `scrapy` package installed inside my home directory `/home/erik` and be able to avoid installing my package on an ephemeral location.

**Comment by kalefranz** [comment]
How is this different from running

    conda create -p /home/erik/my-work-env

outside the container, and then inside the container (with `-v /erik:/home/erik`) run

    conda install -p /erik/my-work-env numpy

?  Is there a permissions issue?  If so, how is the permissions problem not an issue with the pip workflow, but it is with the conda workflow?

**Comment by consideRatio** [comment]
Wieee!

Okay so `pip install --user <package>` corresponded to `conda install -p ~/.local <package>` as far as I can tell, both solutions made me able to access the package straight away without configuring PATH additionally which is awesome!

Thank you for your time guiding me to understanding the pre-existing potential of conda @kalefranz.

**Comment by kalefranz** [comment]
The example I gave above was probably bad.  Pure-python files inside of a `site-packages`-like directory (or using `PYTHONPATH` to point at one) will work fine in that case.  In general though, many binaries and executables will probably be broken inside the container, for the same reason you can't just use `mv` to change the location of a conda environment (you have you use `conda create --clone` instead).

The better example is keeping the path the same inside and outside the container.  So

1. create environment outside container with `conda create -p /home/erik/my-work-env`
2. start container with volume `-v /home/erik:/home/erik`
3. install packages with `conda install -p /home/erik/my-work-env numpy`

**Comment by jakirkham** [comment]
Have at times had a weird need for this feature. Our use case is also related to containers that are non-writable. Though sometimes we need to add just one more package to the environment for testing, debugging, or just something we are uncomfortable shipping in the container for whatever reason.

Expect that having some sort of stacked, partial environment would solve the issue. Stacking has been discussed in various issues, but to recap is the option to activate multiple environments in some order where all of them are used together. Partial in the sense that this environment would be incomplete. IOW it would rely on the environment it is stacked on top of to satisfy dependencies. Think these two features would be enough to scratch this itch (though I could be wrong).

**Comment by consideRatio** [comment]
Sorry for not returning to this issue until now, I lost track of it. The guidance I got by @kalefranz did the trick for me. I'm thinking I'll close this, and let someone reopen it if that seems good to them.

**Comment by rragundez** [comment]
This:
"Okay so pip install --user <package> corresponded to conda install -p ~/.local <package>" doesn't work. As .local is not a conda environment: 

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: /home/username/.local

So how can I have a systemwide conda environment available to all users which they cannot modify for other users, but at the same time they can install new package or update nre packages by installing them in their own home folder or so (where they have permissions)?

This is possible with pip.

**Comment by jakirkham** [comment]
Would recommend creating a new issue @rragundez . This one is quite old at this point 🙂
