### ISSUE TITLE
Deactivate error in fish shell under conda 4.4

### ISSUE THREAD

**Issue by stagrovin** [conda/conda#6703]
It complains about an array out of bounds.

Seems like line 72 in conda.fish should read:

eval (eval $_CONDA_EXE shell.fish deactivate)

 instead of

eval (eval $_CONDA_EXE shell.fish deactivate $argv[2..-1])

as this command has no parameters.

Changing this seems to make it work.

**Comment by ShubhGupta2125** [comment]
I am a beginner and would like to work on this issue. Can i make the change specified by you above?

**Comment by kalefranz** [comment]
Yes, go for it.  Just submit a PR.

**Comment by civilx64** [comment]
Thanks @stagrovin! Can confirm this worked for me as well. I will leave the PR for @ShubhGupta2125.
