### ISSUE TITLE
Error in in conda command while installing numpy

### ISSUE THREAD

**Issue by bthornton191** [conda/conda#6714]
Error in conda command:
("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

>>> conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : c:\anaconda3  (writable)
  default environment : c:\anaconda3
     envs directories : c:\anaconda3\envs
        package cache : c:\anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
That's just an intermittent HTTP error.  Also you're using a very old version of conda.  Please update before requesting help in the future.
