### ISSUE TITLE
add pkgs/mro in list of default channels

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6715]

**Comment by mingwandroid** [comment]
Hi @kalefranz, we need to be careful here. MRO does not work on macOS < 10.9 and it is not available for any 32-bit OSes.

**Comment by kalefranz** [comment]
Right now pkgs/mro is an empty channel, so this change has no effect at the moment.

I assume no availability for 32-bit OSes just means we won’t be adding packages to linux-32 or win-32, correct? If that’s the case, this change should have no impact there.

We haven’t been supporting OSX <10.9 in pkgs/main, correct? So really this change isn’t unlike adding pkgs/main to defaults and how it affects CentOS 5 (i.e. people still using CentOS 5 need to set the ‘default_channels’ config parameter on their own).

**Comment by kalefranz** [comment]
> MRO does not work on macOS < 10.9

@mingwandroid Can you clarify 10.9 or 10.11?

**Comment by mingwandroid** [comment]
10.11.

> I assume no availability for 32-bit OSes just means we won’t be adding packages to linux-32 or win-32, correct? 

I'm now making R packages that don't require compilation noarch: generic so those could get selected from mro and I'd rather they didn't.

**Comment by kalefranz** [comment]
FYI total packages downloads for November and December for osx/macOS were 4.8% for 10.10 and 0.9% for 10.9.  Still working on percentages for R packages.
