### ISSUE TITLE
Error 'Destination Folder' contains the following invalid character

### ISSUE THREAD

**Issue by ravisank** [conda/conda#6717]
I am trying to install Anaconda and get the following message - Error 'Destination Folder' contains the following invalid characterC:\Users\iyw752\AppData\Local\Continuum\anaconda3

![anaconda error](https://user-images.githubusercontent.com/22347836/34845993-c836eb6e-f6e4-11e7-9422-5ce126fb7b10.JPG)

I tried changing the destination but that doesnt work either. I do want to mention that I tried installing Anaconda once but my computer crashed (not because of the download). I am now trying to reinstall the software and now I keep getting this error. Will really appreciate any help you guys can provide in resolving the issue.

Thanks
Ravi

**Comment by kalefranz** [comment]
@nehaljwani @mingwandroid Any thoughts?

**Comment by kalefranz** [comment]
The error you encountered is not with conda.  If you continue to have problems, please file a new issue at github.com/ContinuumIO/anaconda-issues.
