### ISSUE TITLE
Do a better job with packages that include the same files

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#672]
Right now, if two packages include the same files, conda just overwrites one with the other. This has to be done better. 

For instance, you remove a package, it can end up breaking your installation because a file that should have still been there from another package will be removed.

**Comment by janschulz** [comment]
For a problem with this see: https://github.com/conda-forge/staged-recipes/pull/674#issuecomment-221869388

Just to put it into perspective: debian does not allow two packages have the same file, these have to conflict with each other and if a file changes "ownership" a certain "dance" with conflicts and replaces has to be added to the package metadata.

**Comment by kalefranz** [comment]
Conda 4.3 implements a `path_conflict` configuration parameter.  The parameter can be set to

* `clobber`
* `warn`
* `prevent`

The intention was for the default value to be `prevent` in conda 4.3, but our repositories actually have a lot of problems, and we would have created a *lot* of very visible pain for users.  In 4.3 (and probably 4.4) the default value is `clobber`, which preserves the previous behavior before this feature was implemented.  In the future, we'll hopefully be able to transition the default value to `warn` and eventually `prevent`.

**Comment by asmeurer** [comment]
In how many instances are the files actually identical? From what I remember, that's usually the case. When that happens, there isn't really an issue.

**Comment by kalefranz** [comment]
> When that happens, there isn't really an issue.

When files are identical, the biggest issue is when two packages sharing the same path are installed, and then one package is uninstalled, effectively wiping out the files for both packages.

Good example is `dateutil` and `python-dateutil`, which was recently discussed on the mailing list.
https://groups.google.com/a/continuum.io/forum/#!msg/conda/ZKbbc40xMSc/M4_aa9vOAgAJ

**Comment by asmeurer** [comment]
Ah yes, it should definitely avoid doing that. What I mean is the packages need not conflict. I remember there being a lot of minor instances of this for metadata files.

**Comment by kalefranz** [comment]
> packages need not conflict

Exactly.  Sometimes they do still.  `virtualenv`'s `activate` conflicting with conda's for example.

@stefanseefeld is working on a tool to scan the full repo and figure out where we have conflicts that we need to address.  After we get our repo in shape (and share the tool with conda-forge *et al.* for them to do the same), then we'll be able to start ratcheting up the `path_conflict` default behavior.
