### ISSUE TITLE
Installing a package via .tar.bz2 file prefers cache over the actual .tar.bz2 file

### ISSUE THREAD

**Issue by kuepe-sl** [conda/conda#6721]
When installing a conda package via
```
conda install /tmp/builds/linux-64/mytestpkg-x-1-gcc540_0.tar.bz2
```
conda always uses the data from the package cache. This can be very confusing when rebuilding and testing packages locally, because the changes of the rebuilt package will not end up in the installed conda environment.

The expected behaviour for installing packages via .tar.bz2 files would be, that the package cache is cleared and the new .tar.bz2 file is installed.

**Comment by kalefranz** [comment]
Do you know if this is isolated to conda 4.4, or if it's also present in 4.3?

**Comment by kuepe-sl** [comment]
It is present in 4.3.
The first time I noticed this I was using Conda 4.3.25, but I forgot to make an issue back then.

I think this is a general issue with the cache. It's not a new bug.
