### ISSUE TITLE
Bring locking back for writable package caches and environments

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6742]
Needed to support concurrent conda operations.

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/5997

**Comment by kalefranz** [comment]
Reference: https://pypi.python.org/pypi/flufl.lock/2.4.1

**Comment by kalefranz** [comment]
Besides package cache and target environment locking, also don't overlook locking for other files we interact with, like `~/.conda/environments.txt`.

**Comment by goanpeca** [comment]
Ref: 

https://filelock.readthedocs.io/en/latest/
https://flufllock.readthedocs.io/en/latest/

**Comment by epruesse** [comment]
Still an issue

**Comment by ChaotX** [comment]
I have a machine that runs multiple CI agents in docker containers.
If I could share the same package cache as volume for all these containers I would save lots of ssd storage.

**Comment by bernt-matthias** [comment]
xref https://github.com/conda/conda/issues/12138

**Comment by jacobwilliams** [comment]
This would have been a very useful feature. (especially for CI usage)

**Comment by jezdez** [comment]
@dholth is this identical to the locking topic we discussed?
