### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:   - pytorch-cpu Use "conda info <package>" to see the dependencies for each package.

### ISSUE THREAD

**Issue by iamyashasvi** [conda/conda#6743]
Hi, i found this error on my ubuntu when im installing PyTorch,
this is command after this i encountered error  "conda install pytorch-cpu torchvision -c pytorch"
 Anyone known how do i solve this error. Thanks in advance :)

**Comment by kalefranz** [comment]
Use conda environments.

    conda create -n pytorch pytorch-cpu torchvision -c pytorch
    conda activate pytorch
