### ISSUE TITLE
source activate sometimes does not empty hash cache in zsh

### ISSUE THREAD

**Issue by jasongrout** [conda/conda#6744]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

I have conda 4.3.30.

Sometimes I've noticed when activating an environment that executable locations are not updated to refer to the current environment's bin directory. For example, I just created a new environment and installed the notebook package. `which jupyter-notebook` still gave me a system notebook. I had to empty the zsh hash cache with `hash -r` for zsh to recognize that the conda environment had a `jupyter-notebook` that took precedence over the system one.

My understanding is that resetting the PATH *should* empty the cache, but apparently something didn't work here. I wonder if conda should do `hash -r` when starting a new environment to make sure the cache is empty.

I talked with @fperez once about how conda activates new environments, and he mentioned he had a system where he *always* started a subshell with the new environment. That seems to be a simple solution to cleanly starting and exiting environments.

**Comment by kalefranz** [comment]
Conda 4.4 uses `hash -r` for zsh and `rehash` for other posix shells.
https://github.com/conda/conda/blob/4.4.7/conda/shell/etc/profile.d/conda.sh

**Comment by jasongrout** [comment]
Or maybe this is a bug in zsh? I'm running `zsh 5.2 (x86_64-apple-darwin16.0)` on OS X.

**Comment by jasongrout** [comment]
Great, good to know it's fixed! Thanks!

**Comment by kalefranz** [comment]
BTW

> always started a subshell with the new environment

I've thought about implementing something like that.  Haven't landed on a use case just yet that's compellingly urgent.

Seems that the `conda activate` in 4.4 is reasonably solid at this point, I think.

**Comment by kalefranz** [comment]
Actually, `zsh` uses `rehash` and everything else uses `hash -r`.  We've been doing that since at least conda 4.1 I think.

https://github.com/conda/conda/blob/4.3.30/shell/activate#L118-L125

**Comment by jasongrout** [comment]
I could be wrong about using `hash -r` on zsh - I just found out about the hash function a few minutes ago when trying to figure out why I wasn't seeing the executable in the conda env.

**Comment by kalefranz** [comment]
I think we probably used advice from https://superuser.com/a/490984 or something like that.  But I'm also seeing that `hash -r` is valid for zsh.  http://zsh.sourceforge.net/Guide/zshguide03.html

I wonder if there's an old version of zsh we'd like to support that only has `rehash` and not `hash -r`?

**Comment by fperez** [comment]
@jasongrout, I've called my little tool [`copip`](https://github.com/fperez/copip). It's awfully raw, basically personal-use-grade code only, but has been working great for me.

**Comment by mbargull** [comment]
To get a new subshell with an activated environment, you can, e.g., with `bash` use
```bash
 bash --rcfile <(echo '. ~/.bashrc ; . /path/to/conda/bin/activate')
```
(or, of course, put `. ~/.bashrc ; . /path/to/conda/bin/activate` in a persistent `file` and use `bash --rcfile file`.)

**Comment by kalefranz** [comment]
There's definitely an argument that `conda activate` should either as an option, or by default, subprocess to a new shell.  In a lot of ways there would be way less accounting for environment variable handling, and `ctrl-D` would work to get you out of the current active shell.

I rather like the idea, and I guess you can tell I've thought some about it.  I still have a lot of unanswered questions in my own mind about implementation details though.  Details on workflows that impact a generic conda user, not just "conda user with zsh."

**Comment by mbargull** [comment]
IMHO, `conda activate` should never subprocess to a new shell. It should just `activate` an environment.
But an additional `conda start` command is certainly possible. Since this would always create a new subprocess, it can be (nearly) completely implemented in Python.
But that requires some research as how to launch each shell in a `bash --rcfile <(echo '. ~/.bashrc ; . /path/to/conda/bin/activate')`-like fashion and how to handle those specialities (`zsh` for example requires a whole directory instead of a since `.*rc` file).
