### ISSUE TITLE
Install MongoDB and pymongo

### ISSUE THREAD

**Issue by Fulvioo** [conda/conda#6749]
Hello

Anaconda Navigator 1.6.2 (2 envs: Anaconda3 and TensorFlow)
Python 3.6.1
Windows 10

Not solving package specifications thus it doesn't install Mongo at all
I've waited more than 1hr and also tried restarting the laptop a couple of times.

Shall I install by '`conda install -c anaconda mongodb`' ? 
Any contraindications?

![navigator](https://user-images.githubusercontent.com/30832709/35107013-205c9d30-fc70-11e7-8c4a-6ced7c4b0350.png)

**Comment by kalefranz** [comment]
Try using application-specific conda environments.

**Comment by Fulvioo** [comment]
Thanks, solved by using the shell command 'conda etc.'
Anyway, I think that the issue on Anaconda Navigator persists.
