### ISSUE TITLE
[Errno 2] No such file or directory: '/opt/conda/pkgs/entrypoints-0.2.3-py35_0.tar.bz2'

### ISSUE THREAD

**Issue by hungple** [conda/conda#6758]
Hi,

Have you seen this error?

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64/
                          https://conda.anaconda.org/r/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
            config file : /root/.condarc
           offline mode : False

`$ /opt/conda/bin/conda clean -y --tarballs`

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_clean.py", line 427, in execute
        pkgs_dirs, totalsize = find_tarballs()
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_clean.py", line 210, in find_tarballs
        size = getsize(join(pkgs_dir, fn))
      File "/opt/conda/lib/python3.5/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/pkgs/entrypoints-0.2.3-py35_0.tar.bz2'

**Comment by kalefranz** [comment]
Conda 4.2 is no longer supported.  `conda update conda`
