### ISSUE TITLE
An unexpected error has occurred while execute "conda upgrade --all -v"

### ISSUE THREAD

**Issue by nanhu** [conda/conda#6761]
Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\ProgramData\Anaconda3',
 env_name: 'None', mode: 'None', used_mode: 'system'

Shortcut cmd is D:\ProgramData\Anaconda3\pythonw.exe, args are ['D:\\ProgramData
\\Anaconda3\\cwp.py', 'D:\\ProgramData\\Anaconda3', 'D:\\ProgramData\\Anaconda3\
\pythonw.exe', 'D:\\ProgramData\\Anaconda3\\Scripts\\anaconda-navigator-script.p
y']

===> REVERSING PACKAGE UNLINK: defaults::anaconda-client-1.6.5-py36hd36550c_0 <=
==
  prefix=D:\ProgramData\Anaconda3

===> REVERSING PACKAGE UNLINK: defaults::anaconda-5.0.1-py36h8316230_2 <===
  prefix=D:\ProgramData\Anaconda3

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : D:\ProgramData\Anaconda3  (writable)
    default environment : D:\ProgramData\Anaconda3
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/7 W
indows/6.1.7601
          administrator : True

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/menuinst#59
