### ISSUE TITLE
SSL error while trying to update Anaconda

### ISSUE THREAD

**Issue by saurabh-23** [conda/conda#6763]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
We’re looking to use Conda as a way to update and manage the Python, and R packages. While updating and running the command "conda update anaconda" we ran into this error which is a SSL error as shown below. I have already looked all over and tried multiple things like updating the navigator version, using proxy to access, and disabling the SSL.
Any leads on this shall be highly appreciated.
Ps- We’re focusing on using conda from the command line – not from Navigator so $ conda update anaconda-navigator does not work.

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),),)
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
This is something going on with your OS's network stack.  There's nothing really conda is doing (or not doing) here.

Maybe some thing with this google query can be helpful? 
https://www.google.com/search?q=WSAECONNRESET&oq=WSAECONNRESET
