### ISSUE TITLE
custom private channel no arch directory not found

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6771]
_From @fvisconti on January 23, 2018 10:39_

Hi,

I have a custom channel on a private server, added in `.condarc` as 
`http:USER:PASSWD@server.url`.

It has been working for a long time, but now it says:

`WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/http:USER:PASSWD@server.url`.

Of course the `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files are there, as have always been.

I feel it is strange the `conda` url is prepended to my custom url, what's going on?

It's a WARNING, so everything runs fine unless I need a package from my channel.

```
conda --version
conda 4.4.7
```

_Copied from original issue: conda/conda-docs#531_

**Comment by kalefranz** [comment]
@fvisconti Can you share with me the output of

    conda config --show-sources

?

**Comment by fvisconti** [comment]
I had a bad url, shame on me.
Now I have unauthorized access (HTTP 401), but I think I have problems with the login.

You can close the issue, sorry.
