### ISSUE TITLE
conda 4.4 not sourcing 'activate.d' / 'deactivate.d' scripts

### ISSUE THREAD

**Issue by jrevans** [conda/conda#6785]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

I have been using conda 4.4 since it was RC1, now using conda-4.4.7 for the 'conda activate <foo>' mechanism.

At one point a '.../etc/profile.d/conda.csh' script was added, which I was happy to see because I no longer needed to use my own.

It does not properly run the 'activate.d' or 'deactivate.d' scripts.  Attached is a"fixed" version.  Additionally when testing out the bash version, it no longer sources either.

[conda.csh.txt](https://github.com/conda/conda/files/1662046/conda.csh.txt)

### Steps to Reproduce

```
```
for any given env place a 'foo.csh' and 'foo.sh' script into the env '.../etc/activate.d/' and '.../etc/deactivate.d' directories, then activate that environment and the 'foo.*sh' scripts will not be sourced.

## Expected Behavior

activating an environment should source the appropriate *sh scripts located in '.../etc/activate.d/'

deactivating an environment should source the appropriate *sh scripts located in '.../etc/deactivate.d'

**Comment by kalefranz** [comment]
> Additionally when testing out the bash version, it no longer sources either.

Can you give me something more concrete to reproduce that?

**Comment by kalefranz** [comment]
Attached conda.csh.txt script contents, for reference

```
setenv _CONDA_EXE "/group/mdnav/conda/bin/conda"
setenv _CONDA_ROOT "/group/mdnav/conda"
# Recommended way to make the conda command available in csh is
#   $ sudo ln -s <CONDA_ROOT>/etc/profile.d/conda.csh /etc/profile.d/conda.csh
# or in ~/.cshrc add the line
#   source <CONDA_ROOT>/etc/profile.d/conda.csh

# This block should only be for dev work. Under normal installs, _CONDA_EXE will be templated
# in at the top of this file.
if (! $?_CONDA_EXE) then
  set _CONDA_EXE="${PWD}/conda/shell/bin/conda"
else
  if ("$_CONDA_EXE" == "") then
      set _CONDA_EXE="${PWD}/conda/shell/bin/conda"
  endif
endif

if (`alias conda` == "") then
    if ($?_CONDA_ROOT) then
        alias conda source $_CONDA_ROOT/etc/profile.d/conda.csh
    else
        alias conda source $PWD/conda/shell/etc/profile.d/conda.csh
    endif
    setenv CONDA_SHLVL 0
    if (! $?prompt) then
        set prompt=""
    endif
else
    switch ( $1 )
        case "activate":
            set noglob
            eval `$_CONDA_EXE shell.csh activate "$2" $argv[3-]`
            unset noglob
            rehash
            if ( -e "$CONDA_PREFIX/etc/activate.d" ) then
                set nonomatch=1
                set conda_autoexec_scripts = ( $CONDA_PREFIX/etc/activate.d/*.csh )
                if ( -e $conda_autoexec_scripts[1] ) then
                    foreach script ( $conda_autoexec_scripts )
                        source "$script"
                    end
                endif
                unset conda_autoexec_scripts
                unset nonomatch
            endif
            breaksw
        case "deactivate":
            set noglob
            eval `$_CONDA_EXE shell.csh deactivate "$2" $argv[3-]`
            unset noglob
            rehash
            if ( -e "$CONDA_PREFIX/etc/deactivate.d" ) then
                set nonomatch=1
                set conda_autoexec_scripts = ( $CONDA_PREFIX/etc/deactivate.d/*.csh )
                if ( -e $conda_autoexec_scripts[1] ) then
                    foreach script ( $conda_autoexec_scripts )
                        source "$script"
                    end
                endif
                unset conda_autoexec_scripts
                unset nonomatch
            endif
            breaksw
        case "install" | "update" | "uninstall" | "remove":
            set noglob
            $_CONDA_EXE $argv[1-]
            eval `$_CONDA_EXE shell.csh reactivate`
            unset noglob
            rehash
            breaksw
        default:
            set noglob
            $_CONDA_EXE $argv[1-]
            unset noglob
            breaksw
    endsw
endif
```

**Comment by kalefranz** [comment]
The whole blocks like

```
            if ( -e "$CONDA_PREFIX/etc/activate.d" ) then
                set nonomatch=1
                set conda_autoexec_scripts = ( $CONDA_PREFIX/etc/activate.d/*.csh )
                if ( -e $conda_autoexec_scripts[1] ) then
                    foreach script ( $conda_autoexec_scripts )
                        source "$script"
                    end
                endif
                unset conda_autoexec_scripts
                unset nonomatch
            endif
```

should no longer be necessary.  Look at the output of

    conda shell.csh activate /path/to/prefix

for a prefix that has `.csh` files in the `activate.d` directory.  The output of that command is what should be eval'd by the shell.

**Comment by jrevans** [comment]
Create a dummy test environment 'bug_6785'
`conda create --name bug_6785`

Make sure there is an activate directory
`mkdir -p ~/miniconda3/envs/bug_6785/etc/activate.d`

create a couple of dummy activate scripts

    cat > ~/miniconda3/envs/bug_6785/etc/activate.d/foo.csh << EOF
    echo "Running 'foo.csh' activate script..."
    EOF

    cat > ~/miniconda3/envs/bug_6785/etc/activate.d/foo.sh << EOF
    echo "Running 'foo.sh' activate script..."
    EOF

See what gets eval'd when activating:
`conda shell.csh activate bug_6785`

    set prompt='(bug_6785) ';
    setenv CONDA_DEFAULT_ENV "bug_6785";
    setenv CONDA_PREFIX "/home/jrevans/miniconda3/envs/bug_6785";
    setenv CONDA_PROMPT_MODIFIER "(bug_6785) ";
    setenv CONDA_PYTHON_EXE "/home/jrevans/miniconda3/bin/python";
    setenv CONDA_SHLVL "1";
    setenv PATH "/home/jrevans/miniconda3/envs/bug_6785/bin:.:/home/jrevans/miniconda3/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin";

no mention of 'foo.csh'.  Try it for bash.
`conda shell.posix activate bug_6785`

    PS1='(bug_6785) '
    export CONDA_DEFAULT_ENV='bug_6785'
    export CONDA_PREFIX='/home/jrevans/miniconda3/envs/bug_6785'
    export CONDA_PROMPT_MODIFIER='(bug_6785) '
    export CONDA_PYTHON_EXE='/home/jrevans/miniconda3/bin/python'
    export CONDA_SHLVL='1'
    export PATH='/home/jrevans/miniconda3/envs/bug_6785/bin:.:/home/jrevans/miniconda3/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin'```

No mention of 'foo.sh'.  Lets actually try it, from within a c-shell:
`conda activate bug_6785`
the echo statement is nowhere to be seen.

Try from within a bash shell:
`conda activate bug_6785`
Still no echo happening.

perhaps the true fix is that whatever generates the output that gets eval'd needs to be fixed, but delving into that takes more time than I have, so currently we have been using the above submitted file for our miniconda installations, and another similar one for the few bash users that we have.

**Comment by mbargull** [comment]
You need to use
```bash
"${CONDA_PREFIX}/etc/conda/activate.d/"
```
instead of
```bash
"${CONDA_PREFIX}/etc/activate.d/"
```

**Comment by jrevans** [comment]
*facepalm*

yes, that would do it.  Apparently I have been consistently making that error all over the place, since before the 'csh' support was fully implemented, so my temporary work-around had always worked.

Thanks for the help.

One thing of note...  you will still need to add the 'set noglob' and 'unset noglob' lines to the 'conda.csh' script, otherwise 'csh' will attempt to expand and '*' used and this would make things like `conda search '*qt*'` fail.

**Comment by kalefranz** [comment]
@jrevans do you have any advice on how we should handle non-zero exit codes from conda here for csh? We do fine in conda.sh, but I don’t have a lot of experience with csh. I’m sure there’s still plenty to improve.

**Comment by jrevans** [comment]
in my original 'conda.csh' (from conda < 4.4) if I only was calling one thing (like `${_CONDA_EXE} $argv[1-]`, then I would follow it up with `exit $status`

for running several commands where you want to check after each one, then you would have to check the status code after each command.
