### ISSUE TITLE
Provide a conda command to install dependencies from package metadata?

### ISSUE THREAD

**Issue by ceball** [conda/conda#6788]
Imagine I'm developing 3 pure python packages. In the python world, I might run `pip install -e .` on each of the 3 git checkouts, which would install the 3 packages in 'develop'/'editable' mode, and would also install the dependencies of all 3 into my current environment.

Often, I would prefer to use conda instead of pip - particularly for installing the dependencies of the python packages I'm developing. The python packages I'm developing always have a meta.yaml file in the repository (for building a conda package to release), so I hoped I would be able to use that somehow via `conda develop`. However, `conda develop` does not seem to do what I want, and is currently not recommended (e.g. https://github.com/conda/conda-build/issues/2633#issuecomment-359572215, https://github.com/conda/conda-build/issues/1990#issuecomment-305549938, https://github.com/conda/conda-build/issues/1992).

A suggestion that seems to have come up several times for `conda develop` is that it should create an environment from the meta.yaml file (e.g. https://github.com/conda/conda-build/issues/1677), in addition to installing the package in 'develop' mode. However, I would prefer a new environment not to be created (or for it to be optional), because I want to be able to install multiple packages' sets of dependencies into the same, existing environment. I would also have no problem running `pip install --no-deps -e` myself, after having installed the dependencies using conda, because I am only ever working on pure python packages<sup>1</sup>.

I think what I want has been asked before (#5126), but the resolution there is not what I'm looking for. Unless I'm misunderstanding, I think that issue leads to a command to do something like `conda install --dependencies-only pkg`, where pkg is an existing (built) conda package. I don't want to have to build the conda package and then install dependencies from it because that's a time consuming process - particularly if I am currently editing the dependencies - and the package could anyway fail to be created (e.g. my package tests might fail). And I don't want to use an existing version of pkg from elsewhere because the dependencies may be out of date.

Currently, projects I see tend to have developer instructions like one of the following:

  * `conda install pkg && conda remove --force pkg && pip install --no-deps -e .` (which gets a developer the released package's dependencies, not those specified in the repo's current meta.yaml file), or

  * `conda install dep1 dep2 ... depN && pip install --no-deps -e .` where dep1, dep2, ..., depN are somehow never quite the same as what's in meta.yaml (accidentally, not just because dependencies have moved on since last time), and are different from what developers actually install, and vary again on travis and appveyor too (accidentally, not just because there are genuine platform differences).

A `conda "install dependencies from" meta.yaml` command could cut down the times dependencies are specified in a project, greatly improving the chance that developers and CI systems are all using the same dependencies, which will be the same ones as in the conda package when it's released, helping users get a reliable package.

I guess I'm hoping that by asking for only an "install dependencies from meta.yaml" command rather than to fix/upgrade `conda develop`, there might somehow be less work involved. It naively looks to me like I could put together some kind of command to get the dependencies from meta.yaml using `conda_build.api.render()` and then reading `'requirements/run'` etc, but there are probably subtleties I'm not considering! 

-----

1. I don't know if `conda develop` is supposed to be python only, or if it's expected to do any more of what's specified in a package's meta.yaml/associated build scripts. I haven't thought about that because I'm biased to developing only python packages.

**Comment by mbargull** [comment]
I suppose this would be mostly a `conda-build` work as that `meta.yaml` parsing isn't part of `conda` but `conda-build`.
I could imagine either a `conda-build` command that outputs a list that `conda install` could consume, e.g.
```
conda install --file <(conda show-run-requirements /path/to/recipe/)
```
or a `conda-build` command that directly invokes `conda install`, e.g.,
```
conda install-run-requirements /path/to/recipe/
```
(as with `conda render`, those would be actually part of `conda-build` but could be run via `conda`).

----

> It naively looks to me like I could put together some kind of command to get the dependencies from meta.yaml using `conda_build.api.render()` and then reading `'requirements/run'` etc,

If you have a very simple recipe, you could do something like
```bash
conda install --file <( conda render /path/to/recipe/ | python -c 'import sys; import ruamel_yaml as yaml; print(*yaml.load(sys.stdin)["requirements"]["run"], sep="\n")' )
```
Or, you could do it the other way around and use a separate file with the list of requirements and include that in `meta.yaml`. This isn't currently directly supported in `conda-build`, though, but can be achieved in a rather hacky way, e.g.:
<details open><summary><code>
/path/to/recipe/conda-requirements-run.txt
</code></summary><p>

```
python
numba >=0.36.0
```
</p></details>
<details open><summary><code>
/path/to/recipe/meta.yaml
</code></summary><p>

```
{% set run_requirements = load_file_regex(
    load_file='conda-requirements-run.txt',
    regex_pattern='.+',
    from_recipe_dir=True).string.strip().split("\n")
%}

package:
...
requirements:
  run:
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}

```
</p></details>

That `conda-requirements-run.txt` could be then directly used with `conda install --file conda-requirements-run.txt`.

----

> but there are probably subtleties I'm not considering!

Yeah, overall it's actually not that trivial in general as, e.g., a single recipe/`meta.yaml` can create multiple output packages. So you'd at least need some kind of `--output` parameter to be able to specify which package's dependencies you want. Then again, you can provide build matrices to `conda-build` to create multiple build with different dependencies. So you might also need a way to specify for which of those builds you want to install the dependencies. And I'm sure there are other things to be considered, too...

**Comment by ceball** [comment]
> or a conda-build command that directly invokes conda install, e.g., `conda install-run-requirements /path/to/recipe/`

Developers would probably also want to install the test requirements. (And presumably for some packages it would be necessary to install the build dependencies too.) So maybe it could be `conda install-requirements recipe` with options to control which sections are used? (And some sensible combination by default, if possible.)

> If you have a very simple recipe, you could do something like `conda install --file <( conda render /path/to/recipe/ | python -c 'import sys; import ruamel_yaml as yaml; print(*yaml.load(sys.stdin)["requirements"]["run"], sep="\n")' )`

It would be great to have a "conda supported" command, because then I could persuade others to use it :)

> Or, you could do it the other way around and use a separate file with the list of requirements and include that in meta.yaml. [...] That conda-requirements-run.txt could be then directly used with conda install --file conda-requirements-run.txt.

I could almost live with this because it would cut down duplication of dependency specifications within projects. However, I prefer authoring the meta.yaml file and for it to be the source, because it already lets me express things like "these are run dependencies", "these are test dependencies", "this one applies only on windows", etc.

**Comment by mbargull** [comment]
> It would be great to have a "conda supported" command

Of course!

> "this one applies only on windows"

Yeah, having selectors is something that wouldn't be possible in a simple text file that can be used with `conda install --file`. Both of my suggestions are merely some bad workarounds you could apply now but they have with *very limited* capabilities.

@msarahan: What do you think about @ceball's feature request? Should this be moved to https://github.com/conda/conda-build/issues/?

**Comment by jlstevens** [comment]
I think this is a great idea. 

I often run into trouble when trying to use ``pip install -e .`` (or worse ``python setup.py develop``) in my conda environments which often causes problems. If ``conda develop`` worked in the way @ceball describes, I think I would use it more frequently to avoid using ``pip`` for this purpose altogether.

**Comment by cpbotha** [comment]
We're feeling exactly this pain at the moment.

Our main application has a conda `environment.yml`. A number of its git submodules are Python packages we are developing in parallel, each with its own `setup.py` and `environment.yml`.

With vanilla pip, this is straight-forward: `pip install -e .` in any submodule, and it will pull in that sub-package's dependencies also. However, our sub-packages depend heavily on conda packages themselves.

With conda, there is no straight-forward way to do this, or am I missing something that could do the trick for us?

**Comment by DTasev** [comment]
>  I don't want to have to build the conda package and then install dependencies from it because that's a time consuming process - particularly if I am currently editing the dependencies

This. The issue actually described into #5126 is not solved at all by `conda-build --only-deps`, and the only actual solution is build the package locally, and then install with `--only-deps`, but this can takes ages for big packages

**Comment by msarahan** [comment]
This might be helpful: https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/debugging.html

You still need a conda recipe, but at least you don't have to build a package.

**Comment by aparnapr121** [comment]
We are facing a similar issue. We have several only python projects built using conda. When we want to work on them locall, we use the following command to set up the environment.
conda create -n env_name packagae_name --only-deps
But this doesnt install any test dependencies. As testing is crucial before we check in the code, we have to install all the missing testing dependencies one by one. This is a cumbersome approach. Are there any ways to add the test dependencies while installing a package?
I went through the conda-debug page https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/debugging.html to see if it would solve this problem. But the documentation there is not so helpful. As conda-debug is mentioned as a sub command of conda-build, I was looking for some instructions with runnable commands on using conda-debug. I did a search in the git repo for conda-build as well, but didn't hit any results. Are there any examples on how to run a conda-debug command.?

**Comment by bretttully** [comment]
For what it is worth, we used the conda CLI to parse the recipe. I'm sure it misses a bunch of edge cases, but this project that was a C++ lib with python bindings it worked very well: https://bitbucket.org/cmriprocan/toffee/src/dev/.dev-environment/create_dev_conda_environment_helper.py
