### ISSUE TITLE
add 'conda search --envs'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6791]
As root, running

    conda search --envs 'openssl<1.0.2n'

would list the location of every known environment containing an outdated version of openssl.

**Comment by mbargull** [comment]
What would that do?
Given that `conda search --help` => `[...] Search for packages and display associated information. [...]`, I'm not sure how the environments fit in..

(Also, PS: Want to you check your Gitter?)

**Comment by kalefranz** [comment]
Updated the issue with a description :)  Opened the issue on my phone, while I was getting a haircut :-p  Just wanted it as a reminder; couldn't really type in the details.
