### ISSUE TITLE
conda env update --prune reports conflicts for removed packages (4.4)

### ISSUE THREAD

**Issue by ShannonGreen** [conda/conda#6809]
[environments.zip](https://github.com/conda/conda/files/1671754/environments.zip)
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

We have a Python 2 and Python 3 branch for our codebase while we're transitioning, with a corresponding env.yaml file for each. For a variety of reasons, some packages are not in both environments. Obviously all common packages have a different version due to requiring a different version of Python.

When using `conda env update -n environment --prune --file env.yaml` command to sync an environment from our Python 2 branch to our Python 3 branch, conda reports a package conflict. This error is new since upgrading from 4.3 to 4.4.7. 

### Steps to Reproduce

I've attached a minimal working example for both .yaml files.
```
$ conda env update --file bug_env.yaml --prune -n test
<creates the environment OK, snip>
$ conda env update --file bug_env2.yaml --prune -n test
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - singledispatch==3.4.0.3=py36_0
  - win_inet_pton==1.0.1=py27_0
Use "conda info <package>" to see the dependencies for each package.
```

## Expected Behavior

Packages that have been removed from env.yaml (like win_inet_pton in this case) should be removed from the environment when run with --prune, and should not conflict. This was the behaviour in conda 4.3. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : None
       user config file : C:\Users\sgreen\.condarc
 populated config files : C:\Users\sgreen\.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : C:\ProgramData\Miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/win-32
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda2\pkgs
                          C:\Users\sgreen\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda2\envs
                          C:\Users\sgreen\AppData\Local\conda\conda\envs
                          C:\Users\sgreen\.conda\envs
               platform : win-32
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> C:\Users\sgreen\.condarc <==
channels:
  - conda-canary
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls                                          
# packages in environment at C:\ProgramData\Miniconda2:                   
#                                                                         
asn1crypto                0.22.0           py27h717bdfe_1    defaults     
ca-certificates           2017.08.26           h94faf87_0    defaults     
certifi                   2017.7.27.1      py27h6309188_0    defaults     
cffi                      1.10.0           py27he2ca222_1    defaults     
chardet                   3.0.4            py27h400594b_1    defaults     
conda                     4.4.7                    py27_0    conda-canary 
conda-env                 2.6.0                h36134e3_1    defaults     
console_shortcut          0.1.1                h6bb2dd7_3    defaults     
cryptography              2.0.3            py27hd885b15_1    defaults     
enum34                    1.1.6            py27h62011c5_1    defaults     
futures                   3.2.0            py27h47d355e_0    defaults     
idna                      2.6              py27hc92a076_1    defaults     
ipaddress                 1.0.18           py27hdb5ba36_0    defaults     
menuinst                  1.4.10           py27hffda999_0    defaults     
openssl                   1.0.2m               h05bc326_1    defaults     
pip                       9.0.1            py27hfe60e39_4    defaults     
pycosat                   0.6.3            py27hd462980_0    defaults     
pycparser                 2.18             py27h9852578_1    defaults     
pyopenssl                 17.2.0           py27h9ddb344_0    defaults     
pysocks                   1.6.7            py27h3e65130_1    defaults     
python                    2.7.14              hca1081f_23    defaults     
pywin32                   221              py27hd388f4c_0    defaults     
requests                  2.18.4           py27h038ddc7_1    defaults     
ruamel_yaml               0.11.14          py27h6ffe8f8_2    defaults     
setuptools                36.5.0           py27h474e7f7_0    defaults     
six                       1.11.0           py27hcc62b61_1    defaults     
urllib3                   1.22             py27h0db6be9_0    defaults     
vc                        9                    h7299396_1    defaults     
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults     
wheel                     0.29.0           py27hefd7827_1    defaults     
win_inet_pton             1.0.1            py27h4f1e666_1    defaults     
wincertstore              0.2              py27h87a2792_0    defaults     
yaml                      0.1.7                h00170ee_2    defaults     
```
</p></details>

**Comment by kalefranz** [comment]
I believe that the problem here isn't with `--prune` necessarily, but with how environments are created with an environment.yml file using conda 4.4.  With conda 4.4, we make the distinction between user-requested specs and specs in an environment that are there to fulfill dependencies of user-requested specs.  By recreating an environment from a typical environment.yml file, you're telling conda that *every* package is a user-requested spec.

The solution going forward is to provide a flag for `conda env export` that allows users to export only user-requested dependencies.

**Comment by kalefranz** [comment]
Or also maybe not: https://github.com/conda/conda/blob/4.4.8/conda_env/installers/conda.py#L35

**Comment by ShannonGreen** [comment]
Oh, so is it now the case that --prune will only remove specs that were brought in to fulfil dependencies, and will not remove user-requested specs, even if they are not in environment.yml?

conda/core/solve.py describes 'prune' as:
```
            prune (bool):
                If ``True``, the solution will not contain packages that were
                previously brought into the environment as dependencies but are no longer
                required as dependencies and are not user-requested.
```

This is different to the behaviour described by conda env update --help.

What's the best workaround for this? Just `conda remove --all` and recreate the environment?

**Comment by ShannonGreen** [comment]
If I'm not mistaken, the change in behaviour is mainly due to this line: https://github.com/conda/conda/blob/master/conda/core/solve.py#L169

I see now why conda behaves the way it does. It's not a conda bug necessarily - but maybe a documentation bug. To update an environment to be exactly like an environment.yaml file, I need to either 

- ignore the history of user-requested specs (maybe an option like --ignore-history or --prune-hard)
- delete history file completely (an easy workaround, but I'm unsure of the wider consequences)
- remove and create the environment (I think this is significantly slower)

Since our use case for conda is mainly to enforce a particular environment for reproducibility, I'm looking seriously at the second option. Any chance there's a benefit to exposing this functionality in the CLI?

**Comment by nicoddemus** [comment]
Hi everyone,

I contributed `--prune` (IIRC), and the behavior described in the docs is what we at @esss intended at the time: to remove any packages that should no longer be in the environment because they are not listed in the `environmnent.yml` file. We depend on that behavior for the same reasons stated by @ShannonGreen: we reuse conda environments in CI to avoid the cost of recreating them for each build. 

We are also considering deleting the history file as a workaround, but would be perfectly fine with a `--prune-hard` flag (or similar).

It might be worth mentioning https://github.com/esss/conda-devenv, which is a wrapper around `conda env` to fit exactly the needs described above, while also adding Jinja, and environment variable support, and ability to include other environment files for intra-project dependencies.

xref: https://github.com/ESSS/conda-devenv/issues/59

**Comment by nicoddemus** [comment]
In the end we followed @ShannonGreen's workaround and are truncating the `history` file (https://github.com/ESSS/conda-devenv/issues/60), we will report back if this does not work well for us.

**Comment by nicoddemus** [comment]
Truncating the `history` file no longer works (https://github.com/conda/conda/issues/7279#issuecomment-510975223), so it seems the best course of action is indeed to make conda-env do not deal with the original specs at all (https://github.com/conda/conda/issues/7279#issuecomment-516417564).

**Comment by nicoddemus** [comment]
Also worth noting that https://github.com/conda/conda/pull/9614 fixes this. We also depend on `--prune` working, so we build conda internally with #9614 applied.
