### ISSUE TITLE
Windows uninstall is slow

### ISSUE THREAD

**Issue by lovettchris** [conda/conda#6815]
I'm submitting a bug report for the Anaconda Windows installer, I don't know if this is the right place.  But first I'd like to thank the team for providing such great windows support for Anaconda.  Awesome job.

The bug I think is that the uninstaller tries to print too much stuff to the screen, causing it to be very slow at deleting files.  So this UI takes for ever:

![image](https://user-images.githubusercontent.com/18707114/35555347-b5be5e04-0553-11e8-9546-9cf2c7ac637e.png)

## Current Behavior

The files are flashing by quickly but there are so many of them that the UI DrawText routine is taking all the time.  If one tries "rd /s /q" the folder can be deleted much more quickly than the Installer leads one to believe...

## Steps to Reproduce
Create 5 environments, each with lots of packages (100 or so), then uninstall Anaconda (conda install Jupyter is a good way to get lots of packages).

## Expected Behavior
The uninstaller UI could "self-throttle" the output by drawing on a separate rending thread at 30 fps whatever file name is currently being deleted, this will decouple the UI performance from the File system delete operation, and make the delete much faster.

**Comment by Arkarbo** [comment]
Good job

**Comment by Arkarbo** [comment]
Rise to version

**Comment by kalefranz** [comment]
This issue was moved to conda/constructor#168

**Comment by kartikpodugu** [comment]
I am also facing this issue. Anaconda 3 uninstaller takes too much time to uninstall. It just stops similar to the image above.

**Comment by msarahan** [comment]
As @kalefranz mentions, the correct place to comment on this issue is https://github.com/conda/constructor/issues/168

Locking here.
