### ISSUE TITLE
conda base env not set when entering tmux (conda 4.4)

### ISSUE THREAD

**Issue by paulthebaker** [conda/conda#6826]
**I'm submitting a...**
  - bug report

This is related to #6796, but the fix from the last comment therein does not work for me.

## Current Behavior

When I open a new terminal, the conda `base` env loads correctly.  In `.bashrc` which is simlinked to `.profile` the following activation runs.
```
. /Users/ptb/anaconda/etc/profile.d/conda.sh
conda activate base
```

When I run `tmux` the conda base env does not load, and anaconda is buried at the end of my `PATH`.

### Steps to Reproduce

upon opening a new terminal
```
(base) $ which python
/Users/ptb/anaconda/bin/python
(base) $ echo $PATH
/Users/ptb/anaconda/bin:/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
(base) $ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N4srnzhlXF/Render
CONDA_DEFAULT_ENV=base
CONDA_PREFIX=/Users/ptb/anaconda
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=/Users/ptb/anaconda/bin/python
CONDA_SHLVL=1
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.GefrjjZC0u/unix_domain_listener
DISPLAY=/private/tmp/com.apple.launchd.Zq5dhUoRDy/org.macosforge.xquartz:0
GLOBUS_LOCATION=/opt/ldg
GLOBUS_PATH=/opt/ldg
HOME=/Users/ptb
LANG=en_US.UTF-8
LOGNAME=ptb
PATH=/Users/ptb/anaconda/bin:/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/ptb
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pqZRzlSd7P/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=26677BC9-43A4-44BC-9E8C-AE7731828EB6
TMPDIR=/var/folders/yd/200nmm0d6c9592mgyxkz619c0000gn/T/
USER=ptb
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
```
run tmux
```
(base) $ tmux
```

In `tmux` (base) is no longer prepended to my prompt, anaconda is buried in my path, but the `CONDA_*` variables are still set
```
$ which python
/usr/bin/python
$ echo $PATH
/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/ptb/anaconda/bin:/opt/local/bin:/opt/local/sbin
$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N4srnzhlXF/Render
CONDA_DEFAULT_ENV=base
CONDA_PREFIX=/Users/ptb/anaconda
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=/Users/ptb/anaconda/bin/python
CONDA_SHLVL=1
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.GefrjjZC0u/unix_domain_listener
DISPLAY=/private/tmp/com.apple.launchd.Zq5dhUoRDy/org.macosforge.xquartz:0
GLOBUS_LOCATION=/opt/ldg
GLOBUS_PATH=/opt/ldg
HOME=/Users/ptb
LANG=en_US.UTF-8
LOGNAME=ptb
PATH=/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/ptb/anaconda/bin:/opt/local/bin:/opt/local/sbin
PWD=/Users/ptb
SHELL=/bin/bash
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pqZRzlSd7P/Listeners
TERM=screen-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=E427F5F6-D0AB-4977-89E3-D2AAD0AD4E13
TMPDIR=/var/folders/yd/200nmm0d6c9592mgyxkz619c0000gn/T/
TMUX=/private/tmp/tmux-501/default,11501,14
TMUX_PANE=%19
USER=ptb
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
```
I can try to activate `base` inside of `tmux`, but nothing happens... there's not even an error:
```
$ conda activate base
$ which python
/usr/bin/python
```

I can activate a user defined conda env inside of tmux, but weirdness ensues.
```
$ conda activate pss
(pss) $ which python
/Users/ptb/anaconda/envs/pss/bin/python
(pss) $ echo $PATH
/Users/ptb/anaconda/envs/pss/bin:/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/ptb/anaconda/bin:/opt/local/bin:/opt/local/sbin
(pss) $ conda deactivate
(base) $ echo $PATH
/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/ptb/anaconda/bin:/opt/local/bin:/opt/local/sbin
(base) $ which python
/usr/bin/python
```

## Expected Behavior

Upon running `tmux` anaconda sits at the top of my `PATH`, and the base env loads.

### fresh terminal
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/ptb/anaconda
            shell level : 1
       user config file : /Users/ptb/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       base environment : /Users/ptb/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/ptb/anaconda/pkgs
                          /Users/ptb/.conda/pkgs
       envs directories : /Users/ptb/anaconda/envs
                          /Users/ptb/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.7 requests/2.13.0 CPython/2.7.12 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

### inside tmux
(This is the same as in a fresh terminal)
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/ptb/anaconda
            shell level : 1
       user config file : /Users/ptb/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       base environment : /Users/ptb/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/ptb/anaconda/pkgs
                          /Users/ptb/.conda/pkgs
       envs directories : /Users/ptb/anaconda/envs
                          /Users/ptb/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.7 requests/2.13.0 CPython/2.7.12 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

## Fix from #6796 
I tried to deactivate, if I enter `tmux`, by adding the following to the top of my `.bashrc`.
```
if [ -n "$TMUX" ]; then
    conda deactivate
fi
... other commands ...
. /Users/ptb/anaconda/etc/profile.d/conda.sh
conda activate base
```

This causes an error to be thrown when entering `tmux` from a fresh terminal.
```
(base) $ tmux
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /Users/ptb/anaconda/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s /Users/ptb/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="/Users/ptb/anaconda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^


 $
```

**Comment by paulthebaker** [comment]
Updated to conda 4.4.8.  Same behavior.

**Comment by kalefranz** [comment]
How does your issue compare to https://github.com/conda/conda/issues/6796?

**Comment by paulthebaker** [comment]
It's the same general idea, if I understood correctly.  The conda environmental variables are carried over, but the actual python executable of my env is not on top of the path in tmux.

**Comment by paulthebaker** [comment]
Looking at that issue again, I can reproduce another behavior seen there.  When I launch `tmux` from an clean terminal (after running `conda deactivate`) the conda variables show up in my env, but anaconda is nowhere in my `PATH`.

```
(base) $ conda deactivate

$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N4srnzhlXF/Render
CONDA_SHLVL=0
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.GefrjjZC0u/unix_domain_listener
DISPLAY=/private/tmp/com.apple.launchd.Zq5dhUoRDy/org.macosforge.xquartz:0
GLOBUS_LOCATION=/opt/ldg
GLOBUS_PATH=/opt/ldg
HOME=/Users/ptb
LANG=en_US.UTF-8
LOGNAME=ptb
PATH=/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/ptb
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pqZRzlSd7P/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=1CB14EAD-166D-4F4E-82FE-5E9FCEE61588
TMPDIR=/var/folders/yd/200nmm0d6c9592mgyxkz619c0000gn/T/
USER=ptb
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0

$ tmux

$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N4srnzhlXF/Render
CONDA_DEFAULT_ENV=base
CONDA_PREFIX=/Users/ptb/anaconda
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=/Users/ptb/anaconda/bin/python
CONDA_SHLVL=1
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.GefrjjZC0u/unix_domain_listener
DISPLAY=/private/tmp/com.apple.launchd.Zq5dhUoRDy/org.macosforge.xquartz:0
GLOBUS_LOCATION=/opt/ldg
GLOBUS_PATH=/opt/ldg
HOME=/Users/ptb
LANG=en_US.UTF-8
LOGNAME=ptb
PATH=/opt/ldg/bin:/opt/ldg/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin
PWD=/Users/ptb
SHELL=/bin/bash
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pqZRzlSd7P/Listeners
TERM=screen-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=E427F5F6-D0AB-4977-89E3-D2AAD0AD4E13
TMPDIR=/var/folders/yd/200nmm0d6c9592mgyxkz619c0000gn/T/
TMUX=/private/tmp/tmux-501/default,11501,20
TMUX_PANE=%25
USER=ptb
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
```

**Comment by kalefranz** [comment]
I guess there’s something going on with the transition in and out of tmux. If you can identify some specific fixes, would definitely entertain an attempt to implement them.

**Comment by paulthebaker** [comment]
I'm not familiar enough with the inner workings of conda to know where to start.

**Comment by paulthebaker** [comment]
It's possible the way tmux is sourcing `.bashrc` / `.profile` / `/etc/profile` is the issue.

**Comment by mbargull** [comment]
I have a simple fix for #6796. Will open a PR in the next few hours.

**Comment by mbargull** [comment]
PR is #6828.

**Comment by mbargull** [comment]
@paulthebaker, in the OP you said you'd except the behavior to be
> Upon running tmux anaconda sits at the top of my PATH, and the base env loads.

. I don't think this is something `conda` can or should do on its own. But, given the fix proposed in #6828 gets through, you could simply test for `CONDA_PREFIX` in your `.bashrc` and do a `conda activate "${CONDA_PREFIX}"` if it's set. This would then just reactivate the current environment.

**Comment by kalefranz** [comment]
> Upon running tmux anaconda sits at the top of my PATH, and the base env loads.

I don't understand why it isn't.  How is tmux moving across *some* environment variables into the subprocess, but not *all* environment variables?  It seems to me like tmux is maybe a bit disrespectful or arrogant with setting `PATH` to something that's hard-coded without inheritance.  Something like

    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

rather than

    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

Conda, and I'm sure a lot of other software for that matter, uses coupled state among environment variables.  tmux is totally breaking that it seems.

Sorry for the rant.  I'm probably as frustrated with it as you are here.

**Comment by kalefranz** [comment]
Note that if tmux was doing that second example, conda wouldn't have a problem.  Our activate and deactivate work fine with other software adding stuff to PATH, as long as the parts of PATH that conda has contributed remain intact.

**Comment by mbargull** [comment]
It's *not really* `tmux` that is resetting `PATH`/`PROMPT_COMMAND`. The thing is that `tmux` runs login shells on default and thus `/etc/profile`, `/etc/profile.d/*`, ... get sourced, which then set those variables but (usually) won't touch other ones like `CONDA_*`.
So, basically compare the following outputs:
```bash
[maba@mb830 ~]$ PS1='>>>BASE SHELL $ '
>>>BASE SHELL $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
>>>BASE SHELL $ export PATH=/tmp/bin:$PATH
>>>BASE SHELL $ echo $PATH
/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
>>>BASE SHELL $ bash
[maba@mb830 ~]$ echo $PATH
/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[maba@mb830 ~]$ exit
exit
>>>BASE SHELL $ bash --login
[maba@mb830 ~]$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[maba@mb830 ~]$ exit
logout
>>>BASE SHELL $ echo $PATH
/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
You can of course make `tmux` run another command instead of launching a login shell with things like `tmux new shell-command`, e.g., `tmux new bash`, which would then preserve `PATH`.

**Comment by paulthebaker** [comment]
@mbargull having anaconda at the top of `PATH` is not globally necessary.  I guess the point is that the `PATH` is preserved when moving into `tmux`.  If `PATH=/anaconda/bin:/usr/bin` in my base shell, then it better stay that way in tmux.  So my **desired behavior** was too specific to my case.

`tmux new bash` preserves the `PATH`, but resets `PS1`.  It looks like PR #6828 will result in tmux entering the `base` env correctly, which is good enough.

**Comment by mbargull** [comment]
`conda 4.4.9` released on `conda-canary` --> issue resolved  🎉

**Comment by kalefranz** [comment]
If you want to test...

    conda config --add channels conda-canary
    conda update conda

**Comment by jjpr-mit** [comment]
In 4.4.9, after starting tmux, I still get the `CommandNotFoundError` message when I try to run `conda activate`.  

Is this because the new `conda` command is implemented as a shell function?  When starting tmux, environment variables are preserved, but aliases and functions are not.

**Comment by mbargull** [comment]
@jjpr-mit, can you post a reproducer?

**Comment by mbargull** [comment]
> Is this because the new conda command is implemented as a shell function?

Yes, but if you have `tmux`/`bash` configured to `. YOUR_CONDA_INSTALL_PREFIX/etc/profile.d/conda.sh`, then that shell function should be available.

**Comment by mbargull** [comment]
Note that for `conda >=4.4` it is recommended (correct me if I'm wrong @kalefranz) to source that `conda.sh` file **instead of** putting Conda's base prefix on `PATH` in your, e.g., `.bashrc`.

**Comment by kalefranz** [comment]
> Is this because the new conda command is implemented as a shell function?

Yes. `conda activate` is only available, and only makes sense, as a shell function.  Unless we allow `conda activate` to fork a new subprocess, which we haven't implemented yet, and go back-and-forth on whether we want to or not.

**Comment by mbargull** [comment]
>  Unless we allow `conda activate` to fork a new subprocess, which we haven't implemented yet, and go back-and-forth on whether we want to or not.

Please never change that behavior -- IMO, `conda activate` should only every `activate` like it does now. If we want to launch a subshell, that should be with a distinct other command, e.g., `conda start` or the like.

**Comment by jjpr-mit** [comment]
My mistake, I had made the change to my .bashrc as recommended, but I must have had ~/anaconda3 still in my PATH from before the change.  

The actual error I'm getting is:  
```
~$ conda activate
conda: command not found
```
which is probably because my .profile no longer sources my .bashrc.  Not sure how that happened, perhaps a result of installing iTerm2 integration.  

Still tangentially involves tmux, since I'm using tmux/iTerm2 integration, but separate from this issue.  I'll open a new issue if I can't sort it out.

**Comment by mbargull** [comment]
Note that `tmux` launches login shells on default. Hence it should source `.profile`. I think the easiest thing to do is to have
```bash
[[ -f $HOME/.bashrc ]] && . ~/.bashrc
```
in `.profile` (and I also think iTerm does something odd like not reading `.bashrc` on default; can't exactly remember). I don't think there is anything more `conda` could or should do. Just make sure you source `conda.sh` when launching your shell.

**Comment by tommasolaurenzi** [comment]
I have 
```
source /opt/anaconda3/etc/profile.d/conda.sh 
[[ -z $TMUX ]] || conda deactivate; conda activate base
```
in my .zshrc. This seems to solve it for me

what tmux does to path when starting up remains a mystery to me. I had a terminfo compiled with /opt/local/bin/tic but tmux badly wanted to use /usr/bin/infocmp regardless of my $PATH being correctly set up to ignore /usr/bin homologs. Or will `[[ -f $HOME/.zshrc ]] && . ~/.zshrc` in .zprofile do the trick?

**Comment by mathandy** [comment]
For me this was caused by ~/.profile being sourced a when by `tmux` -- and the following `PATH` augmentation I keep in ~/.profile.  The last line in the below code block fixed the issue.

```
# make default python2 also an anaconda environment
# note 1: a symlink was also added `ln -s pip pip2` in this bin
# note 2: the second line here is neccessary, otherwise if 
# ~/.profile is sourced a second time (e.g. by tmux), then
# base2 will end up being the default and cause lots of 
# confusion
export PATH="/home/andy/anaconda3/envs/base2/bin:$PATH"
export PATH="/home/andy/anaconda3/bin:$PATH"
```

**Comment by standage** [comment]
I just lost 90 minutes troubleshooting this. Luckily the suggestion from @rebelot did the trick.

```
[[ -z $TMUX ]] || conda deactivate; conda activate base
```

Uggh, this is why we can't have nice things!

Thanks for all your work on this!

**Comment by harritaylor** [comment]
Just passing by. Had this issue. Can confirm's @rebelot's fix worked perfectly. Thanks!

**Comment by ehknight** [comment]
If anybody's still having this problem, [this](https://stackoverflow.com/a/24980688) worked for me.

**Comment by istinspring** [comment]
problem still there!

**Comment by erietz** [comment]
> I just lost 90 minutes troubleshooting this. Luckily the suggestion from @rebelot did the trick.
> 
> ```
> [[ -z $TMUX ]] || conda deactivate; conda activate base
> ```
> 
> Uggh, this is why we can't have nice things!
> 
> Thanks for all your work on this!

I just lost 89 minutes on this until I found this reply. Putting this line in `.zshrc` solved my problem!

**Comment by aiporre** [comment]
FYI. In Mac OS. [#6826(comment)](https://github.com/conda/conda/issues/6826#issuecomment-718853246) of @erietz add ing to the .bash_profile fixed
