### ISSUE TITLE
Way to show the dependency tree

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#683]

**Comment by rhattersley** [comment]
:+1: Some unknown change in Nth-order dependencies has resulted in the "Solving package specifications" phase of `conda create ...` taking 5 minutes. When it finally finishes a bunch of new packages are listed. It'd be very helpful to understand why these new packages are there.

**Comment by kenwarner** [comment]
any way to do this emerged since last post?

**Comment by omad** [comment]
Here're links to a couple of solutions other people have developed:

 - https://gist.github.com/ericdill/9942ac55c2c9f6a550973dd2dc3653a4
 - https://github.com/rvalieris/conda-tree

**Comment by teake** [comment]
Bit late to the party, but here's my solution: https://github.com/omegacen/conda-depgraph.
