### ISSUE TITLE
dnf fails with `No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'` after gcc_linux-64 is installed

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6836]
After gcc_linux-64 is installed, the variable `_PYTHON_SYSCONFIGDATA_NAME` is set to override the sysconfig. 

dnf from Fedora uses the system python 3.6 installation, which fails if `_PYTHON_SYSCONFIG_DATA_NAME` is set, because the file is not in its python home.

Sequence to reproduce:
```
conda activate base
conda install gcc_linux-64
dnf
```

The workaround is to deactivate the conda environment before calling dnf.

The alternative would be asserting that the cross compilation no longer rely on environment variables to override the current Python's compiler setting -- which means switching to shipping a completely different python binary -- a lot of work with marginal gain.

**Comment by kalefranz** [comment]
@rainwoodman Are you using the latest build of python?  Can you be sure?  I think we discussed changing this recently.

**Comment by kalefranz** [comment]
This is ultimately a packaging issue.  Going to move it to the packages issue tracker.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8437
