### ISSUE TITLE
Feature Request: channel which proxies binary location

### ISSUE THREAD

**Issue by pelson** [conda/conda#6843]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Expected Behavior

It would be super useful to be able to manually construct proxy channel indexes. By that, I mean, conda should follow the existing rules for fetching ``repodata.json[.bz2]``, but the repodata may optionally choose to reference some other location for the binaries themselves.

For example, today we have:

```
 - my_super_channel
    - linux-64
       - repodata.json[.bz2]
       - my_super_package-*.tar.bz2
    - noarch
       - repodata.json[.bz2]
```

with repodata.json looking something like:

```
{
  "info": {},
  "packages": {
    "my_super_package-*.tar.bz2": {
      "build_number": 0,
      "depends": [
      ],
      "md5": "...",
      "name": "my_super_package",
      "size": 15846,
      "subdir": "linux-64",
      "version": "..."
    }
}
```

-----

The proposal is that a proxy channel might look something like:

```
 - my_super_channel
    - linux-64
       - repodata.json[.bz2]
    - noarch
       - repodata.json[.bz2]
 - my_secondary_location
       - my_super_package-*.tar.bz2
```

with repodata.json looking something like:

```
{
  "info": {},
  "packages": {
    "my_super_package-*.tar.bz2": {
      "build_number": 0,
      "depends": [
      ],
      "md5": "...",
      "name": "my_super_package",
      "size": 15846,
      "subdir": "linux-64",
      "location": "../../my_secondary_location/my_super_package-*.tar.bz2",
      "version": "..."
    }
}
```

In practice, I'd like to also support non-relative paths such as:

```
"location": "https://my_super_website.com/my_super_package-*.tar.bz2",
```

One application of this is to allow us to create "meta" channels which bring together multiple channels into a curated form without the need to copy the actual binaries.

**Comment by mbargull** [comment]
This is what `mulitchannels` are for:
```bash
$ conda config --describe custom_multichannels
# custom_multichannels (map: list)
#   A multichannel is a metachannel composed of multiple channels. The two
#   reserved multichannels are 'defaults' and 'local'. The 'defaults'
#   multichannel is customized using the 'default_channels' parameter. The
#   'local' multichannel is a list of file:// channel locations where
#   conda-build stashes successfully-built packages.  Other multichannels
#   can be defined with custom_multichannels, where the key is the
#   multichannel name and the value is a list of channel names and/or
#   channel urls.
# 
# custom_multichannels: {}
```
As and example (apart from the default ones in the help text above), you can add
```yaml
custom_multichannels:
  bio-forge:
    - bioconda
    - conda-forge
```
to your `.condarc` which you can then use with
```bash
$ conda create -nsome-env -c bio-forge bwa
```

**Comment by pelson** [comment]
That's useful to know @mbargull. The problem that I see with that approach is that it is user defined, and not a central channel index that multiple people can access. ``defaults`` might actually be a pretty good candidate for this kind of channel proxy (assuming user customisation is not a thing that is desired in defaults, but that might not be the case I suppose).

In terms of implementing this, I don't imagine it will be a significant code-change, but there will be a few technical implications such as security and debugging which will need to be considered.

**Comment by kalefranz** [comment]
related comment: https://github.com/conda/conda/pull/2376#issuecomment-213472958

**Comment by pelson** [comment]
I'm still an advocate of this feature request. It would be a powerful way for channel curators to reference existing builds, without having to resort to reverse proxies (as was done in conda-metachannel https://github.com/regro/conda-metachannel - cc @mariusvniekerk as I can imagine him being interested in this).
