### ISSUE TITLE
Feature request: fast conda env update for satisfied dependencies

### ISSUE THREAD

**Issue by minrk** [conda/conda#6845]
I would love a mode for `conda env update -f environment.yml` that functions a bit more like `pip install -r requirements.txt` in terms of dong less unneeded work. In particular, I would like it to avoid updating packages that don't need updating, and ideally avoid talking to the index at all if the environment.yml is already satisfied.

I think `update_dependencies: False` does *part* of this, but it doesn't apply to explicitly listed dependencies. In general, there appears to be no available operation to say "Given this environment.yml, make the fewest possible changes to satisfy its specification." My particular goals:

1. `conda env update` with an already satisfied environment.yml should install no packages, make no network requests, and in general complete as fast as possible.
2. if spec is partially satisfied, do not update packages that already satisfy their requirement, unless it is required to satisfy the packages that will be installed

I would like this behavior for `conda install` as well, such that I could call `conda install notebook` and it would only perform any actions if notebook is not up to date.

Are there existing combinations of flags that accomplish some or all of this?

**Comment by kalefranz** [comment]
Additional use case: https://github.com/rtfd/readthedocs.org/issues/3829#issuecomment-375024281

**Comment by kalefranz** [comment]
The solve modes right now are currently

https://github.com/conda/conda/blob/27157ddcec0fefbccd168b6b5be7258f03115b05/conda/core/solve.py#L42-L49

We need something like `PRESERVE_SATISFIED`.  Maybe there's something better to call it.

**Comment by kalefranz** [comment]
Or.. maybe we just don't have the correct implementation for `FREEZE_INSTALLED`?

**Comment by jakirkham** [comment]
> I would like this behavior for `conda install` as well, such that I could call `conda install notebook` and it would only perform any actions if notebook is not up to date.

Actually would add that IMHO `conda install notebook` should do nothing if `notebook` is there already. Updating `notebook` fits under the role of `conda update notebook` IMHO. FWIW without this constraint would not expect issues like ( https://github.com/rtfd/readthedocs.org/issues/3829 ) to be solved.

**Comment by kalefranz** [comment]
> Actually would add that IMHO conda install notebook should do nothing if notebook is there already

I agree in principle, but that seems like a *major* behavior change.  Feels like something I'd get in trouble for, even incorporating into a feature release.

**Comment by kalefranz** [comment]
BTW there's another issue floating around that discusses this exact topic.  That `conda install` should have the `pip` behavior and *not* update an already-satisfied spec.

**Comment by jakirkham** [comment]
Yeah, that makes sense. Maybe there could be a new option to opt-in to this behavior? Possibly moving towards the default behavior in conda 5 depending on how receptive people are to it.

**Comment by wildraid** [comment]
I agree with this issue. I came here while "googling" the right way to do faster update.

**Comment by jakirkham** [comment]
Thanks Kale. Looking forward to it :)

**Comment by minrk** [comment]
This is awesome, thank you! It solves the case where *all* dependencies are already satisfied very well.

Perhaps what was more important to me was the case where *some* dependencies were already satisfied, e.g.

```bash
conda create -n test zeromq=4.2.3 # latest is 4.2.5
conda install -n test -S zeromq # doesn't upgrade, yay!
conda install -n test -S zeromq zlib # upgrades zeromq to 4.2.5
```

But this is still a big improvement. Thanks!

I'll migrate over to https://github.com/conda/conda/issues/5027 which seems to be a description of the remaining missing piece.

**Comment by rrmistry** [comment]
This works well for `conda update <package>`

but is there any advise on how to speed up `conda env update --file 'environment.yml'` ?

**Comment by jakirkham** [comment]
@rrmistry , would suggest opening a new issue for other problems 😉
