### ISSUE TITLE
Running into ConnectTimeoutError

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#6858]
Seem to be running into a `ConnectTimeoutError` basically any way I try to run `conda install`. Any ideas? Is there some sort of outage going on?

**Comment by kalefranz** [comment]
Whoa we are too.

**Comment by jakirkham** [comment]
Ok. So it's not something local to our network then?

**Comment by kalefranz** [comment]
https://www.cloudflarestatus.com/

**Comment by kalefranz** [comment]
I think we're getting hit by that

**Comment by jakirkham** [comment]
Good find. Sounds likely.

FWIW Amazon's S3 looked ok.

**Comment by kalefranz** [comment]
Actually, that's not it.  I think we've isolated this to something going on with Level 3's backbone.

**Comment by kalefranz** [comment]
@jakirkham Looks like we have stuff coming back up... How are things for you?

**Comment by jakirkham** [comment]
Yeah looks like it is coming back for me too. Did you change something internally as a workaround or is Cloudflare recovering?

**Comment by kalefranz** [comment]
Neither.  It wasn't an issue with Cloudflare I don't think.  What they're saying is a problem for them is unrelated.  Level (3) is a backbone connectivity provider, and one we use for one of our lines out.  We're thinking it was something going on with them.

**Comment by kalefranz** [comment]
Ok I think the internet healed itself.  Whatever it was.  Going to close this issue now.

**Comment by jakirkham** [comment]
Thanks @kalefranz.
