### ISSUE TITLE
Conda create gives many sha256-mismatch error messages

### ISSUE THREAD

**Issue by xoffey** [conda/conda#6859]
**I'm submitting a...**
  - [x ] bug report
  - [ ] feature request

## Current Behavior

conda create gives numerous error messages "The package for wheel located at ... appears to be corrupted... has a sha256 mismatch."

These errors seem to apply to setuptools and many others. It happens on more than one machine.
SafetyError: The package for wheel located at /opt/anaconda/miniconda3/pkgs/wheel-0.30.0-py35hd3883cf_1
appears to be corrupted. The path 'lib/python3.5/site-packages/wheel/__pycache__/__init__.cpython-35.pyc'
has a sha256 mismatch.
  reported sha256: c44a94bf1b089749a267419527242ac3909fd802ad0b86e9737c0708bbb60b70
  actual sha256: 2ffece4ac40285bd48a28a7df87f4614752463ee5cc8ae5f43b111c50581aa20

SafetyError: The package for wheel located at /opt/anaconda/miniconda3/pkgs/wheel-0.30.0-py35hd3883cf_1
appears to be corrupted. The path 'lib/python3.5/site-packages/wheel/__pycache__/__main__.cpython-35.pyc'
has a sha256 mismatch.
  reported sha256: d0233ab26a33707e0ca5fe2952d7e328def59b82a07789a05e3196321b4f10a0
  actual sha256: 8fa56b47a339bf8726885efc0c093c96d3b9f3b5127641dae6f1732de88775ff

SafetyError: The package for wheel located at /opt/anaconda/miniconda3/pkgs/wheel-0.30.0-py35hd3883cf_1
appears to be corrupted. The path 'lib/python3.5/site-packages/wheel/__pycache__/archive.cpython-35.pyc'
has a sha256 mismatch.
  reported sha256: fa9ddf881c91e92e61b04e4f2539abad2508bd220116c1261a354aaf4d688876
  actual sha256: d7f1df3d2b1690f69dd57c409dd29e7cd42a2f108d61d76e4585164ff65b8ec4
... and many more

### Steps to Reproduce

```
conda create -n xxx python=3.5
```

## Expected Behavior

Should create the environment with python 3.5 and no warnings.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/abc/.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /opt/anaconda/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /opt/anaconda/miniconda3/pkgs
                          /home/abc/.conda/pkgs
       envs directories : /opt/anaconda/miniconda3/envs
                          /home/abc/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-98-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(no output)
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/anaconda/miniconda3:
#
asn1crypto                0.23.0           py36h4639342_0    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.11.5        py36hf29ccca_0    defaults
cffi                      1.11.2           py36h2825082_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
conda                     4.4.7                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.1.4            py36hd09be54_0    defaults
docopt                    0.6.2                     <pip>
hdfs                      2.1.0                     <pip>
idna                      2.6              py36h82fb2a8_1    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
ncurses                   6.0                  h9df7e31_2    defaults
openssl                   1.0.2n               hb7f436b_0    defaults
pip                       9.0.1            py36h6c6f9ce_4    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
python                    3.6.3                h6c0c0dc_5    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
setuptools                36.5.0           py36he42e2e1_0    defaults
six                       1.11.0           py36h372c433_1    defaults
sqlite                    3.20.1               hb898158_2    defaults
tk                        8.6.7                hc745277_3    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wheel                     0.30.0           py36hfd4bba0_1    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults

```
</p></details>

**Comment by kalefranz** [comment]
Have you verified that the sha sums are indeed correct or incorrect?

**Comment by xoffey** [comment]
Sorry, I have not had the time to do that. Either way, it's a bug, though, right?

**Comment by kalefranz** [comment]
I very much doubt this is a bug.  That's a warning that the packages in the package cache aren't in the state you think they are.  And if conda was to go ahead an install them, bad things would come up and bite you down the road.

**Comment by kalefranz** [comment]
You need to investigate the integrity of the packages.  I haven't seen other reports for these packages, so I don't think it's a problem with the package server-side.  It's very possible that we release incorrectly built packages, but I don't think that's the case here, given the lack of other reports.

**Comment by kalefranz** [comment]
`reported sha256` might be a bad description.  Perhaps it should be `expected sha256`.

**Comment by kalefranz** [comment]
Are you using conda and pip together? There are situations that certain pip misbehavior can cause something like this.

**Comment by xoffey** [comment]
Thank you so much for the thoughtful replies! It seems that it is sometimes necessary to use conda and pip together. For example, recent versions of Tensorflow are available via pip but not via conda, as far as I know.

Anyway, I tried using `conda clean -a` to remedy my situation, but it did not help. I thought that would clear the package caches you mentioned.

How would I go about investigating the integrity of my packages?

**Comment by kalefranz** [comment]
This has definitely been an ongoing issue for us.  I know I've written about the explanation before, but I have no idea where it is.  So I created a new issue with an explanation (and a way for us to track when we're going to help with a patch to pip).

https://github.com/conda/conda/issues/6861

After you read the explanation, you can understand how `conda clean -a` isn't a solution... `conda clean --packages` will *not* remove packages that currently being linked into an environment (i.e. having paths that share their inode with at least one other path).

**Comment by xoffey** [comment]
I see, I may be more-or-less hosed by something that pip did while installing tensorflow. I never liked using `--ignore-installed --upgrade` the way they tell us to.

I can prevent getting the warning messages just by making the following 2 deletions, even though there were dozens of warnings.
rm -r /opt/anaconda/miniconda3/pkgs/setuptools-38.4.0-py35_0
rm -r /opt/anaconda/miniconda3/pkgs/wheel-0.30.0-py35hd3883cf_1

After doing that, I can do `conda create -n xxx python=3.5` without errors or warnings. Of course, that doesn't mean everything will work. But at least my original question is answered.

**Comment by kalefranz** [comment]
That’s interesting. Didn’t know that was their advice. They’re recommendations are based on working around deficiencies in pip, and making sure tensorflow works at all costs, without regard to anything else you’ve got in your environment. And here I mean virtualenv, not a conda environment. Pip just doesn’t have the capability right now to keep environments consistent among all requirements across operations. 

So on one hand I guess I don’t blame them. On the other, they’re really creating difficult-to-diagnose situations for users who are working with anything other than tensorflow.

**Comment by kalefranz** [comment]
There were so many SafetyErrors for you, because we generate one exceptionper path, then gather those up and report each at the same time. I agree that we could do better in aggregating errors like that.

**Comment by kalefranz** [comment]
I'm going to go ahead and close this issue.  I think we understand the root-cause dynamics here.  I've added the `important-discussion` label because I'm sure I'll be referring back to it in the future.

**Comment by rainwoodman** [comment]
Does `-f` ignore these safety-check errors are are they already ignored anyways?

**Comment by zhuhongyue** [comment]
thank you for your advice!

**Comment by JoyceYa** [comment]
> I see, I may be more-or-less hosed by something that pip did while installing tensorflow. I never liked using `--ignore-installed --upgrade` the way they tell us to.
> 
> I can prevent getting the warning messages just by making the following 2 deletions, even though there were dozens of warnings.
> rm -r /opt/anaconda/miniconda3/pkgs/setuptools-38.4.0-py35_0
> rm -r /opt/anaconda/miniconda3/pkgs/wheel-0.30.0-py35hd3883cf_1
> 
> After doing that, I can do `conda create -n xxx python=3.5` without errors or warnings. Of course, that doesn't mean everything will work. But at least my original question is answered.

Same problem here, i did the first deletion, removed the environment, and recreate the environment, no errors.

`rm -r /opt/anaconda/miniconda3/pkgs/setuptools-36.4.0-py35_1`
`conda create -n xxx python=3.5`
