### ISSUE TITLE
pip breaks conda environments by changing content of existing inodes

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6861]
Under the most common mode of operation, conda makes extensive use of hard links to optimize speed and disk space efficiency.  Rather than make a copy of every file being installed into every environment, we extract a package into a writable package cache, and then use hard links to install most all paths into a conda environment.  That is, each path for a package will be hard-linked into an environment, and we have only one inode for two paths on the file system.

Any further use of the same package in other conda environments will also result in hard links from the package cache.  Thus if you have three environments all using the same package (plus the existence of the extracted package in the package cache), for each file in the package, you have four paths sharing the same inode, and you are only using 1/4 the disk space you normally would if you created full copies of each file.

When pip installs a package into a conda environment, it will blissfully clobber paths that conda has already installed files to.  Worse than the clobbering though, pip does not sever the path/inode connection before clobbering, and thus replaces content in the existing inode (rather than creating a new one).  When that happens, pip modifies not only the current environment, but *all* environments on the system that have that package installed into it.

**Comment by xoffey** [comment]
Is there a way to use conda whereby it would not use hard links in such a way? On all my machines, there are only a few conda envs, so it would not be a big deal if there were copies of each package for each environment. In fact, the main reason I use mutliple envs is because I mistakenly thought it would prevent one environment from stepping on others in this way.

I love conda, Anaconda, and Continuum, but I feel like I may be driven away if it can't be made more compatible with pip.

**Comment by kalefranz** [comment]
> Is there a way to use conda whereby it would not use hard links in such a way?

Yes.  Either use the `--copy` CLI flag with `create`, `install`, and `update` operations, or do

    conda config --set always_copy true

or

    conda config --system --set always_copy true

> but I feel like I may be driven away if it can't be made more compatible with pip.

Technically, it's if pip can't be made more compatible with conda.  It really is pip that's the bad actor in this situation.  It's on our list to patch pip to behave better with conda, and apply that patch to the pip you get as the conda package (and the one we always install).  We'll also be submitting that patch upstream.

**Comment by kalefranz** [comment]
Need to audit pip for clobber behavior before all uses of

* `copyfile`
* `copy2`
* `copyfileobj`
* `move`
* `copytree`
* `open` with mode `w`
* `open` with mode `a`

**Comment by goanpeca** [comment]
if os.path.lexists(): os.unlink()

**Comment by xoffey** [comment]
Your approach seems reasonable. However, I haven't seen any documentation on the conda config always_copy option.

**Comment by kalefranz** [comment]
Look at output of `conda config --describe`.

**Comment by nehaljwani** [comment]
An example on how to reproduce this issue.

Install latest Miniconda and activate the base env
```
$ source m3/bin/activate 
```
Note down the sha256sum of a particular file
```
(base) $ sha256sum $CONDA_PREFIX/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
a829793afc6a95a9203150d53659df99cc87878a51357a2ea30c87a138be90df  /tmp/wani.1519541064/m3/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
```
Note down the inode number as well
```
(base) $ ls -i $CONDA_PREFIX/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
82004548 /tmp/wani.1519541064/m3/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
```
Now lets delete the dist-info directory so that pip doesn't know that setuptools is installed.
```
(base) $ rm -fr $CONDA_PREFIX/lib/python3.6/site-packages/setuptools-38.4.0-py3.6.egg-info
```
Let's ask pip to install setuptools
```
(base) $ pip install setuptools
Collecting setuptools
  Downloading setuptools-38.5.1-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 1.2MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-38.5.1
```
Let's look at the inode number for that file in the package cache. It is still the same
```
(base) $ ls -i $CONDA_PREFIX/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
82004548 /tmp/wani.1519541064/m3/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
```
Let's look at the sha256sum of the file. It has changed! :scream_cat: 
```
(base) $ sha256sum $CONDA_PREFIX/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
23450ea85ad2f54edf9a1d2e5b9ec8477ee478c2927aa5e9eb3eb53b3d671280  /tmp/wani.1519541064/m3/pkgs/setuptools-38.4.0-py36_0/lib/python3.6/site-packages/setuptools/command/easy_install.py
```

**Comment by 183amir** [comment]
FYI, this was also discussed in #6079

**Comment by kalefranz** [comment]
Closing this issue following https://github.com/AnacondaRecipes/pip-feedstock/pull/1

**Comment by kiwi0fruit** [comment]
@kalefranz I've just encountered behaviour that indicates that this issue id not over:

When having conda cython v0.28.2 and installing a package that depend on higher version of cython: `"cython>=0.28.3"` (or pip installing higher version cython itself) pip uninstalls conda's cython and installs.

I tested on conda's main repo pip v10.0.1 and on conda-forge pip v0.9.3

**Comment by mingwandroid** [comment]
conda-forge don't have these fixes yet.

**Comment by kiwi0fruit** [comment]
But they should and I'm almost sure that they have - because of the
version=9.0.3 I installed. See this:
https://github.com/conda-forge/pip-feedstock/pull/9

**Comment by mingwandroid** [comment]
Ah ok. Odd then, I cannot explain it.

**Comment by kiwi0fruit** [comment]
I guess such small fix is not enough for pip to be gentle all the time :) I
actually've seen some cases where this fix prevents pip from uninstalling.
But for some reason it depends on situation.​

**Comment by kalefranz** [comment]
@kiwi0fruit What you describe [here](https://github.com/conda/conda/issues/6861#issuecomment-393858350) and [here](https://github.com/ContinuumIO/anaconda-issues/issues/1660#issuecomment-393791410) and [here](https://github.com/AnacondaRecipes/pip-feedstock/pull/1#issuecomment-393785370) sounds like a different issue than what we're addressing with the patch to pip.

The patch to pip is so that, when pip *does* replace a package in an environment, it doesn't end up "reading in" to *other* conda environments and changing the contents of those environments too.  Pip retains the full ability to replace the version of one package with another, even if conda originally installed that package.

**Comment by kiwi0fruit** [comment]
Thank you for clearing it!

>

**Comment by kiwi0fruit** [comment]
@kalefranz By the way. Was it fixed in conda's main repo pip v10.0.1 too?

**Comment by kalefranz** [comment]
Yes it appears https://github.com/AnacondaRecipes/pip-feedstock/tree/master/recipe has been updated for 10.0.1, and still includes the clobber patch.

**Comment by kalefranz** [comment]
Although it's possible that with the 10.0.1 release, there's now new code that we need to patch.

**Comment by pelson** [comment]
To update this issue: The patch was no longer needed after pip was upgraded itself in https://github.com/pypa/pip/pull/5405. The patch was dropped in https://github.com/conda-forge/pip-feedstock/issues/17 (on conda-forge).
