### ISSUE TITLE
pip-github dependencies are not updated

### ISSUE THREAD

**Issue by mschrimpf** [conda/conda#6863]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

conda does not update github repositories specified through pip

### Steps to Reproduce

Create an environment from a `environment.yml` file such as the following:
```
name: example
dependencies:
  - pip:
    - git+https://github.com/someuser/somerepo
```
After creating the environment with `conda env create -f environment.yml && conda activate example`, the repository is successfully installed.
When trying to update with `conda update --all` however, the repository is not updated.

## Expected Behavior

If new commits have been made since the installation of the repository / the last update, conda should re-install the repository.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
            shell level : 1
 populated config files :
          conda version : 4.4.9
    conda-build version : not installed
         python version : 3.6.4.final.0
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
               platform : linux-64
             user-agent : conda/4.4.9 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-43-Microsoft ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False                                                   
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
`conda update --all` does not interact with pip-installed packages.

**Comment by mschrimpf** [comment]
I guess alternatively it would be great if you could specify git urls directly within the conda dependencies instead of the pip workaround
