### ISSUE TITLE
Feature request: packages list configuration export for sharing and backup.

### ISSUE THREAD

**Issue by duytrung** [conda/conda#6864]
Hi there,
I haven't touched Anaconda for a few months due to other works and commitments. 

Is there any way to export a list of all install package and configuration for importation at another machine?

This is useful when working in a classroom where people use different versions of python, provided that we can use the older packages, it should be available for education purpose. 

Regards

**Comment by kalefranz** [comment]
At the moment, I think your best option is probably `conda env export --no-builds`.

      --no-builds           Remove build specification from dependencies
