### ISSUE TITLE
I am facing this issue while installing pcl package using anaconda

### ISSUE THREAD

**Issue by niranjanreddy891** [conda/conda#6869]
```
(E:\Anaconda) C:\Users\*****>conda install -c ccordoba12 pcl
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pcl -> boost       <1.56.0 -> python     <3
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.  
(E:\Anaconda) C:\Users\*****>
```

This is what the error I am facing.I followed this to install [pcl command](https://anaconda.org/ccordoba12/pcl)

**Comment by mbargull** [comment]
Use a separate environment, e.g., called `pcl`:
```
conda install -c ccordoba12 --name pcl pcl
```

**Comment by niranjanreddy891** [comment]
Thanks for the response. Can you help me with this error in Pycharm? I am trying to install PCL package, but it is not there in the library. Instead of PCL, there is a package called PyPCL. Please go through the screen shot attached.

![error while installing PCL](https://user-images.githubusercontent.com/33854825/36112036-44313526-104e-11e8-870c-f877740d5fc6.png)

**Comment by kalefranz** [comment]
In conda 4.4 we made a decision to give less UnsatisfiableErrors, for the tradeoff of having to change around more packages to make the current request satisfiable.  `conda update conda` would probably resolve the issue as originally filed.

For the second one, your issue is with pycharm and pip, so this is the wrong place for assistance there.

**Comment by deepgi** [comment]
Hi, I am having the same problem. I tries updating conda...but it still gives the same error. PFA the cmd image...
![conda](https://user-images.githubusercontent.com/28789110/36735764-3726d6b2-1bd7-11e8-8490-32f738f04bad.PNG)

My main requirement is to visualize and modify point clouds in python.

**Comment by jjhelmus** [comment]
@deepgi Did you try the recommendation from @mbargull to create a new environment for pcl using `conda create -c ccordoba12 --name pcl pcl`?

**Comment by deepgi** [comment]
I did, it actually created a new environment in Anaconda. There was also an instruction to start with "activate pcl" in cmd. But I am very new to python. I only use jupyter notebook for coding. So even when I open the jupyter notebook after "activate pcl", I cant seem to import pcl. Please help. Maybe I dont really understand what a new environment means/

**Comment by mbargull** [comment]
> Maybe I dont really understand what a new environment means/

"Environments" are one of the main features of Conda. I recommend to read up on that in the user guide: https://conda.io/docs/user-guide/concepts.html#conda-environments

If you take a look at https://anaconda.org/ccordoba12/repo, you can see that there is not only `pcl` but also `python-pcl` -- I guess you want
```bat
conda install -c ccordoba12 --name pcl python-pcl
```
(note that Conda is not a pure Python package manager, but a more generic one; hence sometimes (to avoid collisions) Python packages may have slightly different names as those you know from PyPI.)

**Comment by niranjanreddy891** [comment]
I have figured out the issue. Now everything is working fine. Thanks @kalefranz, @mbargull @jjhelmus

**Comment by deepgi** [comment]
The problem was actually with Python 3.6. I downgraded to Python 2.7 and all the packages work fine. I guess a lot of these packages are not optimized for Conda Python 3.6.
