### ISSUE TITLE
Install right version of Anaconda

### ISSUE THREAD

**Issue by PierBJX** [conda/conda#6876]
Hi !

I use a HPC and I don't have the right to install module therefore I tried Anaconda3 (already installed on the HPC).
I installed Anaconda3 locally with this command:
`conda create --name myenv --clone=/apps/software/Anaconda3/4.2.0`

But the problem is that the version is not good. So I tried to update it:

```
(myenv) -bash-4.2$ conda update conda
PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in /mnt/gpfs0/home/s280987/.conda/envs/myenv
```

And if I try to install it:
```

(myenv) -bash-4.2$ conda install conda
Fetching package metadata ...........
InstallError: Install error: Error: 'conda' can only be installed into the root environment
```

The problem is that if I do it in the root environment I don't have the right

**Comment by kalefranz** [comment]
You'll need to ask your sysadmin to update the root conda.  There's really not anything I can do to help here.  Sorry I couldn't help more.
