### ISSUE TITLE
Moving a package to it's own conda install adds additional dependencies.

### ISSUE THREAD

**Issue by mpechner** [conda/conda#6878]
Part of my conda environment setup uses this line:

    conda install -y libiconv=1.14=0 libxml2=2.9.4=0 libxslt=1.1.28=3 lxml=3.4.0=py27_0 numpy=1.8.2 openssl=1.0.2j=0 py=1.4.31=py27_0 pytest=2.9.2=py27_0 pytz=2016.10=py27_0 readline=6.2=2 scikit-learn=0.14.1=np18py27_1 setuptools=27.2.0=py27_0 sqlite=3.13.0=0 tk=8.5.18=0 wheel=0.29.0=py27_0 zlib=1.2.8=3  python-snappy=0.5.1

Has been in place for over a month.  Chef runs 2-3 times  a day and this line is run each time. In experimenting, I moved `python-snappy=0.5.1` to it's own conda install line. It added dependencies.  here is the history from conda:

```
==> 2018-01-26 16:03:00 <==
# cmd: /opt/anaconda/envs/lattice/bin/conda install -y libiconv=1.14=0 libxml2=2.9.4=0 libxslt=1.1.28=3 lxml=3.4.0=py27_0 numpy=1.8.2 openssl=1.0.2j=0 py=1.4.31=py27_0 pytest=2.9.2=py27_0 pytz=2016.10=py27_0 readline=6.2=2 scikit-learn=0.14.1=np18py27_1 setuptools=27.2.0=py27_0 sqlite=3.13.0=0 tk=8.5.18=0 wheel=0.29.0=py27_0 zlib=1.2.8=3 python-snappy=0.5.1
+conda-forge::python-snappy-0.5.1-py27_2
+conda-forge::snappy-1.1.7-1
# install specs: libiconv 1.14 0,libxml2 2.9.4 0,libxslt 1.1.28 3,lxml 3.4.0 py27_0,numpy 1.8.2*,openssl 1.0.2j 0,py 1.4.31 py27_0,pytest 2.9.2 py27_0,pytz 2016.10 py27_0,readline 6.2 2,scikit-learn 0.14.1 np18py27_1,setuptools 27.2.0 py27_0,sqlite 3.13.0 0,tk 8.5.18 0,wheel 0.29.0 py27_0,zlib 1.2.8 3,python-snappy 0.5.1*
==> 2018-02-13 00:07:28 <==
# cmd: /opt/anaconda/envs/lattice/bin/conda install -y python-snappy=0.5.1
-conda-forge::numpy-1.8.2-py27_blas_openblas_201
-defaults::pandas-0.13.1-np18py27_0
-defaults::scikit-learn-0.14.1-np18py27_1
-defaults::scipy-0.14.0-np18py27_0
+conda-forge::numpy-1.14.0-py27_blas_openblas_200
+conda-forge::pandas-0.22.0-py27_0
+conda-forge::python-dateutil-2.6.1-py27_0
+conda-forge::scikit-learn-0.19.1-py27_blas_openblas_201
+conda-forge::scipy-1.0.0-py27_blas_openblas_201
# install specs: python-snappy 0.5.1*
```

You can see that there is a change dependencies.  You can see on Jan 26, it was installed.  Why when I moved the package to a seperate line did it change the installed packages.

This can from an investigation around this general issue.  Took my environment script and as you can see I nail all the versions of the packages.  One example I was chasing down. Where as older systems had libgfortran 0.1, my testing this week, scripy requires libgfortran 0.3 and fails because it cannot find libgfortran 0.1.

**Comment by kalefranz** [comment]
Output of `conda info` please?

**Comment by kalefranz** [comment]
Also the output of `conda config --show-sources`, as requested in the issue template.

**Comment by kalefranz** [comment]
And also the full `conda-meta/history` file.
