### ISSUE TITLE
carriage return errors on conda 4.4 in cygwin

### ISSUE THREAD

**Issue by yoda-vid** [conda/conda#6896]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I recently updated conda to 4.4 following the instructions outlined in [your blog post](https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/?utm_source=hashnode.com). When I open a new bash terminal, I receive this error:

```
sh: /etc/profile.d/conda.sh: line 2: syntax error near unexpected token `$'{\r''
'h: /etc/profile.d/conda.sh: line 2: `_conda_set_vars() {
sh: /cygdrive/d/Programs/Miniconda2/etc/profile.d/conda.sh: line 2: syntax error near unexpected token `$'{\r''
'h: /cygdrive/d/Programs/Miniconda2/etc/profile.d/conda.sh: line 2: `_conda_set_vars() {

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
```

My workaround was to convert line endings with dos2unix (fixed typo -- thanks @mingwandroid ):

```
dos2unix Miniconda2/etc/conda/profile.d/conda.sh
```

### Steps to Reproduce

Open a Cygwin bash terminal after updating to conda 4.4 as above. After applying dos2unix as above, open a new terminal, which shows no errors. ``conda activate [env]`` now works as well.

## Expected Behavior

No errors when starting Cygwin bash terminal

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

After applying dos2unix (paths scrubbed below):

```
conda info
     active environment : D:\Programs\Miniconda2
    active env location : D:\Programs\Miniconda2
            shell level : 1
       user config file : D:\Programs\cygwin64\[user_dir]\.condarc
 populated config files : D:\Programs\Miniconda2\.condarc
                          D:\Programs\cygwin64\[user_dir]\.condarc
          conda version : 4.4.10
    conda-build version : not installed
         python version : 2.7.13.final.0
       base environment : D:\Programs\Miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : D:\Programs\Miniconda2\pkgs
                          C:\[win_user_dir]\AppData\Local\conda\conda\pkgs
       envs directories : D:\Programs\Miniconda2\envs
                          C:\[win_user_dir]\AppData\Local\conda\conda\envs
                          D:\Programs\cygwin64\[user_dir]\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.13.0 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
conda config --show-sources                             
==> D:\Programs\Miniconda2\.condarc <==                 
pinned_packages:                                        
  - conda-canary::conda                                 
                                                        
==> D:\Programs\cygwin64\home\hello\.condarc <==        
channels:                                               
  - conda-canary                                        
  - defaults                                            
                                                        
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
conda list --show-channel-urls                                                  
                                                                                
EnvironmentLocationNotFound: Not a conda environment: D:\Programs\Miniconda2    
                                                                                
```
</p></details>

**Comment by mingwandroid** [comment]
You used `dos2unix` not `unix2dos`!

While we should make sure these scripts have unix line endings, I would recommend you to use `MSYS2` instead of `Cygwin` when you want to run any `Windows`-native software.

**Comment by the4thchild** [comment]
Ah yes, I meant dos2unix in the text too (I'll fix that -- thanks!). Thanks for pointing out MSYS2 as an alternative to Cygwin too. Does MSYS2 typically work better with Anaconda on Windows?

**Comment by kalefranz** [comment]
We haven’t added in activation tests for all the posix shell variants on windows yet, but we need to.

@mingwandoid Of all the environments pre-installed on appveyor (https://www.appveyor.com/docs/build-environment/), which do you recommend hitting explicitly?

**Comment by mingwandroid** [comment]
MSYS2. It's been on AppVeyor for a good while now.

**Comment by kalefranz** [comment]
Well if that’s the default bash.exe on PATH then we’re already good.

**Comment by mingwandroid** [comment]
It does not say "Default in PATH" on that page, so I guess it isn't.

**Comment by the4thchild** [comment]
Thanks, been trying out MSYS2 and works great with Anaconda.

**Comment by mingwandroid** [comment]
No problem, glad to hear it, I think we should keep this open though until we fix our `CRLF`s

**Comment by grant-humphries** [comment]
Hi @kalefranz @mingwandroid, I don't mean to be a pain, but this seems like fairly low hanging fruit, any chance you'd have time to fix this?  Changing the line endings for my local install is no big deal, but the problem is those files are overwritten and CRLFs are restored anytime I update conda.
