### ISSUE TITLE
Conda update working differently

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#6914]
If a user installs the latest Anaconda 5.1 and then they try to update anaconda-client:

```
conda install anaconda=5.1.0
conda update anaconda-client 
```

Conda will say everything is up to date and will not attempt to update to 1.6.11 from 1.6.9.

This issue seems to be another manifestation of it:
- https://github.com/ContinuumIO/anaconda-issues/issues/8603
- https://github.com/ContinuumIO/navigator/issues/1437

Seems to be related with the Anaconda metapackage and how its handling changed from  4.3.x?

**Comment by mbargull** [comment]
duplicate of #6691.
