### ISSUE TITLE
csh prompt handling & deactivate broken

### ISSUE THREAD

**Issue by jrevans** [conda/conda#6919]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

In a csh shell, after sourcing the '~/miniconda3/etc/profile.d/conda.csh'

When activating the environment the original prompt is not a part of the new prompt.

Neither is it reverted to the original prompt when deactivating.

Additionally, when deactivating the 'CONDA' specific env vars are not removed from the environment.

### Steps to Reproduce

```
$> echo "'$prompt'"
'$> '
$> conda activate test_env
(test_env) echo "'$prompt'"
'(test_env) '
(test_env) conda deactivate
env | grep CONDA
_CONDA_EXE=/home/jrevans/miniconda3/bin/conda
_CONDA_ROOT=/home/jrevans/miniconda3
CONDA_SHLVL=0
CONDA_DEFAULT_ENV=test_env
CONDA_PREFIX=/home/jrevans/miniconda3/envs/test_env
CONDA_PROMPT_MODIFIER=(test_env) 
CONDA_PYTHON_EXE=/home/jrevans/miniconda3/bin/python

```

## Expected Behavior

The prompt needs to be preserved throughout and the conda env vars need to be removed from the environment.

I have attached a version of the '.../etc/profile.d/conda.csh' script that fixes the prompt problem.

The env var problem can be fixed by changing the results of 'conda shell.csh deactivate' to use 'unsetenv' instead of 'unset'

[conda.csh.txt](https://github.com/conda/conda/files/1748844/conda.csh.txt)

**Comment by njalerikson** [comment]
Resolved with #7041
