### ISSUE TITLE
Conda command not found in Environments created

### ISSUE THREAD

**Issue by sampathweb** [conda/conda#6938]
Has Conda changed in 4.4?  After I create a new environment - 
`conda create -y --name py36 python=3.6`, the conda command is not copied to the new environment.  Was this a change in 4.4?

**Comment by kalefranz** [comment]
Yes. There's quite a bit of discussion in https://github.com/conda/conda/issues/6810.  Conda 4.5.0 is pending release once the few remaining PRs are merged (https://github.com/conda/conda/milestone/6), and it includes the solution discussed.
