### ISSUE TITLE
Requested Python version (2) is not installed

### ISSUE THREAD

**Issue by jienkles** [conda/conda#6949]
Hi there i recently changed laptops and reinstalled all my software onto new machine.
I created a python 2 environment but it doesnt seem to read this. my python 2.7 files are located c:/python27 while my python 3 path is C:\Users\Dj\AppData\Local\Continuum\anaconda3.

the trouble is that in command and anaconda prompt i cannot change environment even when i specified conda create -n py27 python=2.7 anaconda within my location where i needed to install it.

i get the above error when trying to run this. My intended package only works with python 2, hence the py2 environment.

thank you for your assistance.

**Comment by jienkles** [comment]
<img width="960" alt="py27" src="https://user-images.githubusercontent.com/35368083/36728724-add1fea4-1bb9-11e8-9e55-24d624f97e29.png">
this shows my files after i have specified python 2

**Comment by kalefranz** [comment]
I don't understand your error. Can you provide step-by-step details and expected outputs so that we can reproduce your issue independently?
