### ISSUE TITLE
Permission denied when trying to use pkgs in multi-user environment

### ISSUE THREAD

**Issue by cinaljess** [conda/conda#6953]
- [ ] bug report

I create a new conda environment successfully "conda create --name bigscape". When trying to specify packages for this new environment I get the error.

```
$ conda install -n bigscape numpy scipy scikit-learn
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda



NotWritableError: The current user does not have write permissions to a required path.
  path: /home/user/software/anaconda2/pkgs/mkl-2017.0.3-0/info/repodata_record.json
  uid: 15461
  gid: 1015

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 15461:1015 /home/user/software/anaconda2/pkgs/mkl-2017.0.3-0/info/repodata_record.json

In general, it's not advisable to use 'sudo conda'.
```

The directory mkl-2017.0.3-0 is indeed owned by another user. The perms are 775 for mkl-2017.0.3-0 and mkl-2017.0.3-0/info are 755. 

Following the suggested "conda update -n base conda" I get the same exact error about the mkl library repodata_record.json. We do not have the option of running any Sudo commands.

What is a solution here for having these permissions issues not occur again?

```

$ conda info
     active environment : None
       user config file : /home/unix/acristo/.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.0.8
         python version : 2.7.11.final.0
       base environment : /home/user/software/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/user/software/anaconda2/pkgs
                          /home/unix/acristo/.conda/pkgs
       envs directories : /home/user/software/anaconda2/envs
                          /home/unix/acristo/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.11.1 CPython/2.7.11 Linux/2.6.32-696.20.1.el6.x86_64 rhel/6.9 glibc/2.12
                UID:GID : 15461:1015
             netrc file : None
           offline mode : False
```

**Comment by kalefranz** [comment]
This is probably a bug that needs fixed.  If we can't write that `repodata_record.json` file because of permissions issues, I think we should swallow that error.

**Comment by kalefranz** [comment]
In the meantime, if you don't need to have access to the read-only package cache at `/home/user/software/anaconda2/pkgs`, you can use

    CONDA_PKGS_DIRS=/home/unix/acristo/.conda/pkgs conda install -n bigscape numpy scipy scikit-learn

or

    conda config --add pkgs_dirs /home/unix/acristo/.conda/pkgs

**Comment by cinaljess** [comment]
This was a workable solution, but just in my case our home directory has limited space and this env took >10GB (not a conda problem) so I could not take that route. Fortunately my colleague with the mkl directory is right nearby so I asked him to do a chmod -R g+wr on the pkgs/ dir. Hopefully this avoids any more problems until the bug is patched.

**Comment by aaronpenne** [comment]
This error is caused by permissions like the error message states, but running the suggested command does not work because `repodata_record.json` does not exist yet. The fix for me was to run chown on the conda related directories. Try running the below commands, replacing <YOUR_USER_NAME>

```
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/miniconda3
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/.conda/
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/.condarc/
```

**Comment by argideritzalpea** [comment]
I ran:
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/anaconda
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/.conda/

I don't have a .condarc/ or miniconda3 install. The above, however, did not work for me. I am getting: ```NotWritableError: The current user does not have write permissions to a required path.
  path: //anaconda/pkgs/conda-4.5.2-py27_0/info/repodata_record.json
  uid: 502
  gid: 20```
whenever I try to update or install a package now.

**Comment by nilsonsales** [comment]
I think you need to configure **conda** to use a local path first, using the command:

`conda config --add pkgs_dirs /home/<YOUR_USER_NAME>/.conda/pkgs`

And then you try to install anaconda and the other packages you want:

`conda install anaconda`

It worked here.

---

Thanks for the tips, @kalefranz

**Comment by aschuerch** [comment]
We also use conda in a multi-user environment without sudo rights, with home directories with limited space, and experienced the same problems. My attempted solution was to revert to an earlier revision before we updated conda. But, predictably, I get the same error:

```
$ conda install --revision 23

NotWritableError: The current user does not have write permissions to a required path.
  path: /hpc/local/CentOS7/dla_mm/tools/miniconda2/pkgs/bitarray-0.8.1-py35_0/info/repodata_record.json
  uid: 11039
  gid: 10595

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 11039:10595 /hpc/local/CentOS7/dla_mm/tools/miniconda2/pkgs/bitarray-0.8.1-py35_0/info/repodata_record.json

In general, it's not advisable to use 'sudo conda'.
```

**Comment by aschuerch** [comment]
I (hopefully) made a work-around for now by re-installing an earlier conda version and dis-allowing updating conda by adjusting the `.condarc` file as described in the [User guide - automatically updating conda](https://conda.io/docs/user-guide/configuration/use-condarc.html#update-conda-automatically-auto-update-conda) and [User guide - disallowing installation of specific packages](https://conda.io/docs/user-guide/configuration/use-condarc.html#disallow-installation-of-specific-packages-disallow)

**Comment by dllahr-foghorntx** [comment]
FWIW I don't have a problem with this on our redhat/centos system, but did have a problem with it on a debian system.

**Comment by daveuu** [comment]
See [here](https://github.com/conda/conda/issues/7227#issuecomment-518289063) for a solution that should work for any version of conda.
