### ISSUE TITLE
Conda install error for py2exe

### ISSUE THREAD

**Issue by spchundu** [conda/conda#6959]
Hello,

I am receiving below error when trying to install py2exe 

> "(base) C:\Users\newuser>conda install -c kieranharding py2exe
> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - nltk
>   - py2exe
> Use "conda info <package>" to see the dependencies for each package."

**Environment details:**
platform : win-64
conda version : 4.4.10
conda-build version : 3.4.1
python version : 2.7.14.final.0
user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.14393

**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
This is what environments are for.

    conda create -n py2exe -c kieranharding py2exe
    conda activate py2exe

**Comment by mbargull** [comment]
We need some kind of message that reflects that
https://github.com/conda/conda/blob/113de7eb4e30312c5b8bb7994e01701e18e6d59b/conda/core/solve.py#L273-L281
came into play.

**Comment by kalefranz** [comment]
For the record, I'm not a fan of this special case "business rule." I *despise* special case hacks like this, actually.
