### ISSUE TITLE
Ubuntu14 no longer support it？

### ISSUE THREAD

**Issue by forbxy** [conda/conda#6963]
python3.5.0 python3.6.0 are the last version?
thank u

**Comment by kalefranz** [comment]
Can you please be more specific? Provide more details? Your question makes no sense :(

**Comment by forbxy** [comment]
on ubuntu14.04,
`bxy@bxy-vm:~$ conda create --name jupyter python==3.6.4
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - python ==3.6.4
`
 on ubuntu16,this command  running successed

**Comment by kalefranz** [comment]
Please provide the output of `conda info`

**Comment by forbxy** [comment]
`               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/bxy/software/anaconda3  (writable)
    default environment : /home/bxy/software/anaconda3
       envs directories : /home/bxy/software/anaconda3/envs
                          /home/bxy/.conda/envs
          package cache : /home/bxy/software/anaconda3/pkgs
                          /home/bxy/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-101-generic debian/jessie/sid glibc/2.19    
                UID:GID : 1000:1000
`

**Comment by kalefranz** [comment]
conda update conda
