### ISSUE TITLE
Problem: packages with build features are not updateable by conda update --all

### ISSUE THREAD

**Issue by argltuc** [conda/conda#6966]
We currently facing the situation, that packages which are built with features like `gcc540` or `vc15` can not updated with a general `conda update --all` but only directly by `conda update package`

To check this behaviour, we create a minimal test package which is built by `conda build --croot builds/ src/`as v1 and later as v2.
Second we create a local conda channel, which was configured in `.condarc` with
```
channels:
  - file:///path/to/conda-test-chan/
```
with `conda install testpkg` version 1 was correctly installed. after this we built v2, put it into our test channel and create a new index. Now we expected that `conda update --all` will deliver the new version of our test package. But nothing happens. Only `conda update testpkg` will deliver version 2

I attach all related stuff:
- test package with conda recipe
- our test conda channel
- the used condarc (you have to edit the path to the channel)

[testpkg.zip](https://github.com/conda/conda/files/1771132/testpkg.zip)
[conda_test_channel.zip](https://github.com/conda/conda/files/1771136/conda_test_channel.zip)
[condarc.txt](https://github.com/conda/conda/files/1771147/condarc.txt)

**Comment by mbargull** [comment]
You need to install the packages that "track" (i.e., provide via `track_features`) those features. Otherwise `conda` will avoid updating your `testpkg` to the newer feature-dependent version, unless explicitly requested.

**Comment by argltuc** [comment]
Well, I know. As you can see in condarc.txt track features are used.

**Comment by kalefranz** [comment]
What version of conda are you testing with? Please give us the output of `conda info`, like the issue template asks for.

**Comment by mbargull** [comment]
@argltuc, yeah, sorry, didn't download those files before, my bad.
Thanks for the nice reproducer!
@kalefranz: Just tried it out: This works fine with `4.3.x` but doesn't with `4.4.x` or `master`.

**Comment by argltuc** [comment]
Ah sorry, forgot it. Can't give you the conda info print right now. But this issue was tested on Conda 4.4.11 / Conda Build 3.5.1
With Conda 4.4.1 we had the same issue.

**Comment by argltuc** [comment]
well, the missing conda info:

```
conda info

     active environment : None
       user config file : /home/argl/.condarc
 populated config files : /home/argl/.condarc
          conda version : 4.4.11
    conda-build version : 3.5.1
         python version : 3.5.4.final.0
       base environment : /home/argl/miniconda3  (writable)
           channel URLs : file:///home/argl/dev/conda-test-chan/linux-64
                          file:///home/argl/dev/conda-test-chan/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/argl/miniconda3/pkgs
                          /home/argl/.conda/pkgs
       envs directories : /home/argl/miniconda3/envs
                          /home/argl/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.5.4 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by argltuc** [comment]
Are there any updates to this issue? @kalefranz What can we do to help debugging?
Would be great to solve this issue since our users of our framework are heavily affected by this problem.

**Comment by kuepe-sl** [comment]
I already wondered why `conda update` won't update half of the packages I have installed.

It would be great to see this fixed.

**Comment by argltuc** [comment]
Are there any news for this update? @kalefranz Can we help in some way?

**Comment by mbargull** [comment]
This fails when `conda.resolve.Resolve.bad_installed` is called at https://github.com/conda/conda/blob/4.5.3/conda/core/solve.py#L219. `context.track_features` is first considered only later on at https://github.com/conda/conda/blob/4.5.3/conda/core/solve.py#L301.
Since `bad_installed` sees that the installed `testpkg` has `features=gcc540` but there is no accompanying `track_features=gcc540` package installed and `context.track_features` isn't yet factored in, `testpkg=1=gcc540_0` is considered as "inconsistent":
```
DEBUG conda.resolve:bad_installed(759): Limiting solver to the following packages: 
DEBUG conda.resolve:bad_installed(761): Packages to be preserved: [Dist(channel='file:///path/to/conda-test-chan', dist_name='testpkg-1-gcc540_0', name='testpkg', version='1', build_string='gcc540_0', build_number=0, base_url=None, platform=None)]
DEBUG conda.core.solve:solve_final_state(236): inconsistent dists: 
  - file:///path/to/conda-test-chan::testpkg-1-gcc540_0
```
Thus, it is "preserved", i.e., excluded from the subsequent steps.

@argltuc: Until this is fixed, you could create a package with `track_features` and install that as a substitute for the configuration parameter.
