### ISSUE TITLE
can't launch parallel shells (screen / tmux) while in virtualenv

### ISSUE THREAD

**Issue by sbyrnes321** [conda/conda#6967]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Issue

Sorta related to #6800 and #2837, but this is still an issue in conda 4.4.11. If I am in a virtualenv X on linux, and then I run `screen` or `tmux` to create parallel shells, the spawned shells can claim to be in the same virtualenv X (i.e. it says "(X)" before the prompt) but actually aren't (based on which version of python opens and which packages are available). And there is no error message.

## Workaround

The obvious workaround -- deactivating the conda environment before starting `screen` or `tmux` -- does indeed work for me. So maybe this is a low-priority bug, but I'm reporting it anyway.

**Comment by kalefranz** [comment]
Can you provide output from an example workflow that demonstrates the behavior you’re seeing?

**Comment by sbyrnes321** [comment]
Sorry, here it is on RHEL 7:

* Create a conda virtualenv called `myenv`.
* Open bash, type `source activate myenv`
* Then type `screen` to run the GNU screen multitasking utility and enter a new screen
* Type `source activate myenv` in this new screen.
* This runs without error and makes it look like I'm now in `myenv` (i.e. the prompt starts with `(myenv)`), but I'm actually not! I know this because if I then type `python`, it opens the wrong version of Python, and the myenv packages are not available.

**Comment by kalefranz** [comment]
I see.  So this appears to be related to, or similar to, https://github.com/conda/conda/issues/6796 and #6826, which we thought we had resolved in conda 4.4.9.  Can you review those issues and identify what's different with screen that we didn't cover when we marked those issues as closed?

**Comment by mbargull** [comment]
I assume this is related to some `screen`, shell, login, etc., related configuration.
Can you show the complete output for the command you ran, but with `set -x` executed at the very start and also right when you enter the `screen` session?

**Comment by sbyrnes321** [comment]
@mbargull -- see https://gist.github.com/sbyrnes321/4d6f095f6a47648434abe1a141ea3bb4

By the way, I tried on a different computer (ubuntu) and could NOT reproduce. It only happens on this RHEL7 one.

**Comment by mbargull** [comment]
I'm pretty sure you have
```bash
export PATH="/home/sjb1472/miniconda3/bin:$PATH"
```
somewhere in your `.bashrc` or some another related file. Please remove that line or replace it by
```bash
\. /home/sjb1472/miniconda3/etc/profile.d/conda.sh
```

**Comment by sbyrnes321** [comment]
Confirmed! Thanks so much for your time.
