### ISSUE TITLE
I am facing this error while installing pcl-1.8.1

### ISSUE THREAD

**Issue by niranjanreddy891** [conda/conda#6974]
Hi,
I am facing this issue while installing pcl package through conda. I followed this command from this website [https://anaconda.org/sirokujira/pcl]
I attached the error which I am facing. Please go through it.
![error I am facing](https://user-images.githubusercontent.com/33854825/36890210-184e7292-1e23-11e8-9ed1-220148e787d8.png)

**Comment by niranjanreddy891** [comment]
@sirokujira. Please help me in this issue

**Comment by kalefranz** [comment]
conda create -n pcl -c sirokujira pcl
    activate pcl

**Comment by niranjanreddy891** [comment]
Thanks for the response @kalefranz. I am getting the same error even after specifying the command which you mentioned. Please help me in solving this issue

**Comment by jjhelmus** [comment]
Try `conda create -n pcl -c sirokujira -c conda-forge pcl`

**Comment by niranjanreddy891** [comment]
I tried the command you mentioned. But same error @jjhelmus 
![error](https://user-images.githubusercontent.com/33854825/36930505-1e3b9716-1ec8-11e8-93a1-60265cd6c1ed.png)

**Comment by niranjanreddy891** [comment]
I figured out the issue myself. Now everything works fine. Thanks @kalefranz and @jjhelmus
