### ISSUE TITLE
I tried installing pcl-1.8.1 with this command conda create -n pcl -c sirokujira pcl activate pcl

### ISSUE THREAD

**Issue by niranjanreddy891** [conda/conda#6975]
[https://github.com/conda/conda/issues/6974](https://github.com/conda/conda/issues/6974)
I am facing the same error as before @kalefranz. Please solve the issue [https://github.com/conda/conda/issues/6974](https://github.com/conda/conda/issues/6974)

**Comment by kalefranz** [comment]
Please fill out a proper error report using the issue template with all requested information.

**Comment by kalefranz** [comment]
We can't help you otherwise.  For reference, here's dependency info for the package you're trying to get

```
$ conda search sirokujira::pcl --info
Loading channels: done
pcl 1.8.1 0
-----------
file name   : pcl-1.8.1-0.tar.bz2
name        : pcl
version     : 1.8.1
build string: 0
build number: 0
size        : 16.4 MB
arch        : x86_64
constrains  : ()
platform    : Platform.osx
license     : BSD
subdir      : osx-64
url         : https://conda.anaconda.org/sirokujira/osx-64/pcl-1.8.1-0.tar.bz2
md5         : 91948095af59221b4aabaf14b037c31f
dependencies:
  - boost 1.64.0
  - eigen3
  - flann
  - libpng
  - libpng >=1.6.32,<1.7.0a0
  - qhull
  - zlib
  - zlib >=1.2.11,<1.3.0a0
```

**Comment by niranjanreddy891** [comment]
@kalefranz, I tried the command you mentioned. But it didn't work. Please solve this issue
![error](https://user-images.githubusercontent.com/33854825/36930520-743094b4-1ec8-11e8-8219-2fe295251564.png)

**Comment by niranjanreddy891** [comment]
@kalefranz, I want to install pcl-1.8.1 in my windows-7 64bit version. But I can't install it. Please help me in this issue.

**Comment by niranjanreddy891** [comment]
Can anyone guide me how to install pcl-1.8.1. I am trying to install it from here [https://anaconda.org/sirokujira/pcl](url). Also I tried using the command which @kalefranz mentioned in the above commands. But it didn't work

**Comment by niranjanreddy891** [comment]
I figured out the problem myself. Thanks @kalefranz
