### ISSUE TITLE
remove dist from resolve.py

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6979]
Dist is no longer needed, and it's time to remove it from the code base.  The first step is to remove all `dist` references from `resolve.py`, in a way that `py.test tests/test_resolve.py` passes.  Once that's done, we can extract `dist` from the remainder of the code base.

CC @mcg1969

**Comment by kalefranz** [comment]
We'll ultimately end up with a performance improvement here.  See e.g. #6976

**Comment by groutr** [comment]
Could you please give some more details on why dist is technical debt and how conda will represent the information in Dist objects in the future?

**Comment by kalefranz** [comment]
Pretty simple. Dist is derived from the filename for a package: name-version-build. But that’s all duplicate information, and we want a single source of truth. The source of truth we’ve chosen is what’s actually inside the package, the info/index.json file. That gets exposed as the package record, and that’s what we want to be using in all cases.

**Comment by kalefranz** [comment]
@mcg1969 has agreed to take a first crack at this

**Comment by kalefranz** [comment]
resolved via https://github.com/conda/conda/pull/7216
