### ISSUE TITLE
Error cleaning packages

### ISSUE THREAD

**Issue by bgatessucks** [conda/conda#698]
C:\Users\blabla>C:\Continuum\Anaconda\Scripts\conda info
Current conda install:

             platform : win-64
        conda version : 3.4.2
       python version : 2.7.6.final.0
     root environment : C:\Continuum\Anaconda  (writable)
  default environment : C:\Continuum\Anaconda
     envs directories : C:\Continuum\Anaconda\envs
        package cache : C:\Continuum\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

C:\Users\blabla>C:\Continuum\Anaconda\Scripts\conda clean --packages
Cache location: C:\Continuum\Anaconda\pkgs
Will remove the following packages:

anaconda-1.9.1-np18py27_0                     60 KB
atom-0.3.7-py27_0                            380 KB
blaze-0.4.2-np18py27_0                       1.0 MB
bokeh-0.4.1-np18py27_0                      20.7 MB
boto-2.25.0-py27_0                           7.2 MB
conda-3.0.5-py27_0                           450 KB
conda-3.0.6-py27_0                           451 KB
conda-3.1.1-py27_0                           456 KB
conda-3.2.0-py27_0                           494 KB
conda-3.2.1-py27_0                           495 KB
conda-3.3.0-py27_0                           513 KB
conda-3.3.1-py27_0                           519 KB
conda-3.3.2-py27_0                           519 KB
conda-3.4.0-py27_0                           539 KB
conda-3.4.1-py27_0                           538 KB
conda-3.4.2-py27_0                           620 KB
conda-build-1.2.1-py27_0                     199 KB
conda-build-1.3.1-py27_0                     306 KB
cython-0.20.1-py27_0                         6.8 MB
datashape-0.1.1-np18py27_0                   358 KB
dynd-python-0.6.1-np18py27_0                 2.3 MB
enaml-0.9.1-py27_0                           6.7 MB
gmt_risk_tools-0.2.1-py27_0                  856 KB
gmt_risk_tools-0.2.4-py27_0                  1.3 MB
ipython-1.2.1-py27_0                        13.2 MB
ipython-2.0.0-py27_0                        12.4 MB
ipython-notebook-2.0.0-py27_0                  1 KB
llvmpy-0.12.3-py27_0                        18.2 MB
lxml-3.3.1-py27_0                            4.0 MB
numba-0.12.1-np18py27_0                      1.5 MB
numexpr-2.3.1-np18py27_0                     529 KB
numpy-1.7.1-py27_3                          50.9 MB
openpyxl-1.8.2-py27_1                        676 KB
pandas-0.13.1-np18py27_0                    15.8 MB
pykit-0.2.0-np18py27_0                       1.7 MB
python-2.7.6-0                              48.5 MB
pywin32-218.4-py27_0                        26.1 MB
pyyaml-3.11-py27_0                           736 KB
pyzmq-14.1.0-py27_0                          1.5 MB
py_package-0.1.0-np17py27_0                    5 KB
setuptools-2.2-py27_0                        757 KB
setuptools-3.1-py27_0                        758 KB
sphinx-1.2.2-py27_0                          4.1 MB
wxpython-3.0-py27_0                         74.4 MB
xlsxwriter-0.5.2-py27_0                      965 KB
-----------------------------------------
Total:                                     330.1 MB

Proceed ([y]/n)? y

removing anaconda-1.9.1-np18py27_0
removing atom-0.3.7-py27_0
removing blaze-0.4.2-np18py27_0
removing bokeh-0.4.1-np18py27_0
removing boto-2.25.0-py27_0
removing conda-3.0.5-py27_0
removing conda-3.0.6-py27_0
removing conda-3.1.1-py27_0
removing conda-3.2.0-py27_0
removing conda-3.2.1-py27_0
removing conda-3.3.0-py27_0
removing conda-3.3.1-py27_0
removing conda-3.3.2-py27_0
removing conda-3.4.0-py27_0
removing conda-3.4.1-py27_0
removing conda-3.4.2-py27_0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Continuum\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in
 main
    args.func(args, p)
  File "C:\Continuum\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 2
00, in execute
    rm_pkgs(args)
  File "C:\Continuum\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 1
80, in rm_pkgs
    rm_rf(join(pkgs_dir, pkg))
  File "C:\Continuum\Anaconda\lib\site-packages\conda\install.py", line 144, in
rm_rf
    shutil.rmtree(path)
  File "C:\Continuum\Anaconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Continuum\Anaconda\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Continuum\Anaconda\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'C:\\Continuum\\Anaconda\\pkgs\\conda-
3.4.2-py27_0\\Scripts\\conda.exe'

**Comment by soapy1** [comment]
This should be fixed in the newest version of conda. Closing this issue
