### ISSUE TITLE
Install pcl-1.8.1 on win-7 64bit platform

### ISSUE THREAD

**Issue by niranjanreddy891** [conda/conda#6980]
Hi, I want to install pcl-1.8.1, but I couldn't do it. Previously, I mentioned my problem in these issues. But those answers are not helpful. [https://github.com/conda/conda/issues/6974](url) and [https://github.com/conda/conda/issues/6975](url)
Please solve this issue

**Comment by mbargull** [comment]
1. `conda update conda`
2. Fill out the issue template
3. Don't open duplicate issues.
4. Please do *all* of the above.

**Comment by mbargull** [comment]
(5. Copy the text from terminal output and paste it here instead of taking screenshots.)

**Comment by kalefranz** [comment]
The reason those answers are not helpful is because you have failed to provide information to us. When you open a new issue, there is a guided issue template with sections for you to fill out.  We need that information.  WE CANNOT HELP YOU WITHOUT THAT INFORMATION.

**Comment by niranjanreddy891** [comment]
Thanks for the response. This is the error I am getting while installing pcl-1.8.1 through anaconda command prompt
`(C:\ProgramData\Anaconda2) C:\Windows\system32>conda search sirokujira/win-64::p
cl --info
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: --info`

I am using win-7 64 bit.

**Comment by niranjanreddy891** [comment]
I have figured out the issue. I solved it myself. Now everything is working fine. Thanks @kalefranz and @mbargull
