### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by DemosfenArsen** [conda/conda#6982]
C:\Users\Demosfen>set "KERAS_BACKEND=theano"

(base) C:\Users\Demosfen>conda install -c conda-forge dlib
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - blaze
  - dlib
Use "conda info <package>" to see the dependencies for each package.

(base) C:\Users\Demosfen>set KERAS_BACKEND=

(base) C:\Users\Demosfen>set "KERAS_BACKEND=theano"

**Comment by kalefranz** [comment]
conda create -n dlib -c conda-forge dlib
    conda activate dlib
