### ISSUE TITLE
`conda.fish` does not respect `changeps1` config setting

### ISSUE THREAD

**Issue by teake** [conda/conda#6996]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

The `conda.fish` file does not respect the `changeps1` [config setting](https://conda.io/docs/user-guide/configuration/use-condarc.html?highlight=changeps1#change-command-prompt-changeps1). In particular his function:

https://github.com/conda/conda/blob/a88a7b065ff4c00712286e099e4cebd199ebf6b6/conda/shell/etc/fish/conf.d/conda.fish#L34

seems a bit too happy about always displaying the environment.

This is annoying when your shell theme also display the environment (see e.g. oh-my-fish/theme-agnoster#28).

I'm also a bit puzzle by the lack of prompt changing in the corresponding Bash source file. (Though perhaps that is handled somewhere else?)

## Environment Information
<details open><summary><code>`conda info`</code>(excerpt)</summary><p>

```
     active environment : None
            shell level : 0
          conda version : 4.4.11
    conda-build version : 3.7.0
         python version : 3.6.4.final.0
       base environment : /usr/local/var/pyenv/versions/miniconda3-latest  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by supacyan** [comment]
I just add below into top line of function [__conda_add_prompt](https://github.com/conda/conda/blob/a88a7b065ff4c00712286e099e4cebd199ebf6b6/conda/shell/etc/fish/conf.d/conda.fish#L34)  to remove the green (base), quick and dirty. @teake 
``` 
  set -l fish_conda_changeps1 (conda config --show changeps1 | awk '{print $2}')
  [ $fish_conda_changeps1 = 'False' ]; and return
```

**Comment by sdaitzman** [comment]
Additional not-ideal but functional workaround: add this to your `~/.config/fish/config.fish`, after the modifications by conda:

```fish
# kill the right prompt __conda_add_prompt 😠
function __conda_add_prompt; end
```

It overwrites the function Conda uses to print the right prompt. This has the benefit of persisting across runs of `$ conda init` and is persistent when conda is updated, moved or reinstalled.
