### ISSUE TITLE
Use conda and python version instead of "latest" in Miniconda installer package, e.g. Miniconda3-4.4.10-py36-Windows-x86_64.exe

### ISSUE THREAD

**Issue by nanoant** [conda/conda#6997]
When downloading Miniconda from https://conda.io/miniconda.html the installers are called simply `Miniconda3-latest-Windows-x86_64.exe` or `Miniconda3-latest-MacOSX-x86_64.sh`.

The problem is that with `latest`, once downloaded, there is absolutely no indication what `conda` version it is and what Python version it is.

I would suggest you replace `latest` with `<conda-version>-py<python-version>` e.g.:
~~~
Miniconda3-4.4.10-py36-Windows-x86_64.exe
~~~

This would greatly help with installing proper (intended) version and keep track on Conda installers.

**Comment by mingwandroid** [comment]
The files with the names (or close to anyway) you are asking for already exist [here](https://repo.continuum.io/miniconda/)

**Comment by nanoant** [comment]
@mingwandroid Thanks for the instant response. I will then try to use the link you've provided. However, still I believe it would be better to make `latest` an redirection (symbolic link?) instead a file itself.
