### ISSUE TITLE
Document how to use miniconda for travis-ci builds

### ISSUE THREAD

**Issue by cdeil** [conda/conda#700]
@teoliphant proposed `conda` for continuous integration in this [scipy-dev mailing list post](http://mail.scipy.org/pipermail/scipy-dev/2014-April/019853.html). Like many others scientific Python devs I'm using https://travis-ci.org/ for continuous integration and probably should use `miniconda` to get fast tests.

I've seen a few people trying to do this, but would it be possible to write up documentation how to use `miniconda` on `travis-ci` ... if you can get it accepted preferable [in the official travis-ci Python docs](http://docs.travis-ci.com/user/languages/python/) and advertise this option?

**Comment by robertsawko** [comment]
Hi,

Can I ask you to review this document, @asmeurer ? I just copied and modified the travis setup and I cannot get it to work. [This](https://github.com/robertsawko/pyfd/blob/fix_travis/.travis.yml] is the branch I am working on. It trips over on the last line `python setup.py install` by saying `python: can't open file 'setup.py': [Errno 2] No such file or directory`. Have I missed something in the config?
