### ISSUE TITLE
"source activate" has no effect sometimes

### ISSUE THREAD

**Issue by yaroslavvb** [conda/conda#7007]
Sometimes I do `source activate pytorch_p36` on newly started shell and it has no effect. IE, the command succeeds with status 0, nothing is printed and no visible environment changes took place. In that case `source deactivate` followed by `source activate pytorch_p36` will do what's expected. Sorry for vague report, any suggestions how to debug, collect more info?

conda 4.4.7, AWS [DLAMI v5](https://aws.amazon.com/marketplace/pp/B077GCH38C)

**Comment by mbargull** [comment]
You might want to update to the latest release, currently `conda 4.4.11`, and use `conda activate pytorch_p36` instead.
If you then still have that issue, try
```bash
set -x ; conda activate pytorch_p36 ; set -x
```
and post its output for the failing case here.

**Comment by kalefranz** [comment]
I think @mbargull meant

    set -x ; conda activate pytorch_p36 ; set +x

Also, I'd modify to

    env | sort
    set -x ; conda activate pytorch_p36 ; set -x
    env | sort
