### ISSUE TITLE
conda install pyqt=5.6.0

### ISSUE THREAD

**Issue by LEpessoa** [conda/conda#7009]
I'm currently getting this warning:

(virtual_platform) luado@Jagha:~$ conda install pyqt=5.6.0
Solving environment: \ 
Warning: 4 possible package resolutions (only showing differing packages):
  - conda-forge::openssl-1.0.2l-0, conda-forge::pyqt-5.6.0-py35_2
  - conda-forge::openssl-1.0.2l-0, defaults::pyqt-5.6.0-py35_2
  - conda-forge::pyqt-5.6.0-py35_2, defaults::openssl-1.0.2l-0
  - defaults::openssl-1.0.2l-0, defaults::pyqt-5.6.0-py35done

**Comment by kalefranz** [comment]
There’s a reason we ask for `conda info` and `conda config --show-sources` in the issue template. You’re getting free help here... Please respect everyone’s nights and weekends and least provide the baseline information requested in the issue template.
