### ISSUE TITLE
Conda file getting corrupted on installing <package>

### ISSUE THREAD

**Issue by jeffin143** [conda/conda#7017]
Whenever install package imutils using conda it is messing up conda dir environment

Link i took for package installation
https://anaconda.org/mlgill/imutils

command 
conda install -c mlgill imutils 

After execution and installing of package
If you re run the command it will throw up this error
I tried finding out the remedial measure but couldn't get one

 conda install -c mlgill imutils 
Traceback (most recent call last):
  File "/home/jeffin/anaconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named 'conda'

Not only conda install
any command regarding conda is not working

**Comment by kalefranz** [comment]
You realize there’s no actionable report here, right?

**Comment by jeffin143** [comment]
sry It was for the first time i was opening an issue and hence sorry for the inconvenience caused

The error is
Whenver i am trying to install package imutils it is messing up with conda directory file and error is
 conda list
Traceback (most recent call last):
  File "/home/jeffin/anaconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named 'conda


path is set in bash file and i have reproduced this error 3 time starting from clean installation
