### ISSUE TITLE
after install, no longer using my .profile

### ISSUE THREAD

**Issue by formvoltron** [conda/conda#7019]
Well maybe it's because I'm old and decrepit.  I use a .profile file on a Mac to specify my own PATH & aliases, etc.

After installing miniconda, my PATH has now changed.  I haven't figure out yet where the miniconda version of my startup variables are being set.  Maybe a .bash_profile or something like that?

Yes that's it... You all added a .bash_profile, when I don't use .bash_profile.  I use .profile.  And so my settings temporarily disappeared.  Never a good feeling.  

I'd say the solution would be to first check if there is no .bash_profile, but there is a .profile, then append to the .profile file instead of dumping into .profile?  These things are so messy huh?

**Comment by njalerikson** [comment]
See proposed initialize idea: #6507

**Comment by kalefranz** [comment]
> These things are so messy huh?

Yes, they are. Incredibly messy.  And *you're* only working with a single shell...
