### ISSUE TITLE
Error running conda install on Chinese system

### ISSUE THREAD

**Issue by st80rules** [conda/conda#7023]
Our installation program (written with NSIS) performs pip and conda updates, and I'm having unknown errors on a Chinese system.

The error goes like this:

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.18.1
       root environment : C:\Program Files\Dragonfly\Anaconda3\  (writable)
    default environment : C:\Program Files\Dragonfly\Anaconda3\
       envs directories : C:\Program Files\Dragonfly\Anaconda3\envs
                          C:\Users\wanghuan\AppData\Local\conda\conda\envs
                          C:\Users\wanghuan\.conda\envs
          package cache : C:\Program Files\Dragonfly\Anaconda3\pkgs
                          C:\Users\wanghuan\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.18.1 CPython/3.6.1 Windows/10 Windows/10.0.14393    
          administrator : True

`$ C:\Program Files\Dragonfly\Anaconda3\Scripts\conda-script.py install --file C:\Program Files\Dragonfly\pyth_ext\vtk\libpng-1.6.34-vc14_0.tar.bz2`

    Traceback (most recent call last):
      File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\conda\cli\install.py", line 179, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\conda\cli\common.py", line 551, in specs_from_url
        for line in open(path):
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 16: illegal multibyte sequence

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

**Comment by kalefranz** [comment]
Pull requests that resolve issues like this are especially welcome.

**Comment by kalefranz** [comment]
This is for conda 4.3. Please update and file an new ticket if the issue persists.
