### ISSUE TITLE
'conda install --use-local' does not find a local package that is found by 'conda search'

### ISSUE THREAD

**Issue by pjh5** [conda/conda#7024]
**I'm submitting a...**
  - [ x ] bug report
  - [ ] feature request

## Current Behavior

`conda install --use-local` can't find a package that was previously built with `conda build`. This occurs in the root env and in a brand new env called 'testenv'.

### Steps to Reproduce

```
# A call to conda-build finished with
updating: caffe2-0.8.dev-py27h5b96e0f_0.tar.bz2
Updating index at /opt/conda/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /opt/conda/conda-bld/linux-64 to make package installable with dependencies
Updating index at /opt/conda/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /opt/conda/conda-bld/noarch to make package installable with dependencies
Nothing to test for: /opt/conda/conda-bld/linux-64/caffe2-0.8.dev-py27h5b96e0f_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /opt/conda/conda-bld/linux-64/caffe2-0.8.dev-py27h5b96e0f_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []

# Then
root@3bc896e43bc2:~/caffe2# conda search caffe2 -c local
Fetching package metadata .............
caffe2                       0.8.dev          py27h5b96e0f_0  local
root@3bc896e43bc2:~/caffe2# conda install caffe2 -c local
Fetching package metadata .............
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - caffe2

We have searched for the packages in the following channels:

  - file:///opt/conda/conda-bld/linux-64
  - file:///opt/conda/conda-bld/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
# conda install caffe2 --use-local gives the same output
```

## Expected Behavior

The package should be found and installed along with its dependencies.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
root@3bc896e43bc2:~/caffe2# conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda/envs/testenv
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Linux/4.9.60-linuxkit-aufs debian/stretch/sid glibc/2.23
                UID:GID : 0:0
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
This command doesn't output anything
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
conda list --show-channel-urls
# packages in environment at /opt/conda/envs/testenv:
#
```
</p></details>

**Comment by mbargull** [comment]
Do you get the same error after you `conda update conda` to the latest version?

**Comment by pjh5** [comment]
Sorry for the late reply. I haven't actually been able to reproduce this. It didn't seem like consistent behavior. Feel free to close for now. I will add more info if I ever encounter it again.

I was calling conda build on an Ubuntu 16.04 docker image with Anaconda 2.5.1 installed (installed with https://github.com/caffe2/caffe2/blob/master/docker/jenkins/common/install_anaconda.sh ). The script used to call `conda build` was https://github.com/caffe2/caffe2/blob/master/scripts/build_anaconda.sh . I was making changes to what packages I was including in the meta.yaml, and sometimes this error would appear, but I can't find the combination of packages that caused it.

**Comment by kalefranz** [comment]
Could be an issue with conda-build here too.  `conda update conda-build`

**Comment by krinsman** [comment]
If it's any consolation, I've had weird behavior when using conda in Docker containers too. They seemed honestly more like a problem with Docker (or the Bourne shell) than with conda.

**Comment by certik** [comment]
The same problem here with the latest conda and conda-build. The command
```
$ conda install my_package --use-local
```
fails, but this works:
```
$ conda install -c file:///home/certik/ext/miniconda3/envs/my-env/conda-bld/ my_package
```
I used the `my-env` environment to call `conda-build` to build the package.

**Comment by egpbos** [comment]
I have the same problem and the solution by @certik works for me. Conda-build version 3.17.3, Conda 4.5.12.

Could the issue be related to having set only conda-forge and defaults as channels in ~/.condarc?

**Comment by egpbos** [comment]
Indeed, when I remove the `channels` list from `~/.condarc`, and install my local package with

```
conda install my_package -c conda-forge -c local
```

it works fine again.

**Comment by tovrstra** [comment]
Same problem here with:

```
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
```

This is a showstopper when one relies on `conda build` to find local dependencies built previously. It cannot, for the same reason.

**Comment by tacaswell** [comment]
I am still seeing this problem with:

```
amilyn@11:37  ➤  conda list | grep ^conda
conda                     4.6.14                   py37_0  
conda-build               3.17.8                   py37_0  
```

@stas00 solution got it working.

**Comment by tacaswell** [comment]
and contra @egpbos removing the channels section from my condarc did not help, nor did adding `locals` to that section.

**Comment by jjhelmus** [comment]
@tacaswell Can you provide more information on how this is not working?  Using conda 4.6.14, I am able to install local packages fine using either `conda install --use-local pkg_name` or `conda install -c local pkg_name`.  Note that the package being installed needs to be compatible with those already installed in the environment and `-c local` needs to be the first channel if multiple channel are passed via the command line.

**Comment by tacaswell** [comment]
Ah, something is inconsistent:

```
amilyn@10:33  ➤  conda list conda
# packages in environment at /home/tcaswell/.conda/envs/dd37:
#
# Name                    Version                   Build  Channel
conda                     4.6.14                   py37_0    defaults
conda-build               3.17.8                   py37_0    defaults
conda-package-handling    1.3.0                    py37_0    defaults
conda-verify              3.3.0                    py37_0    defaults
(dd37) ✔  ~/src/bnl/ophyd [doc_release_notes {tacaswell/doc_release_notes}|⚑ 3]
amilyn@10:34  ➤  conda --version
conda 4.4.10
(dd37) ✔  ~/src/bnl/ophyd [doc_release_notes {tacaswell/doc_release_notes}|⚑ 3]
amilyn@10:34  ➤  which conda
~/.conda/envs/dd37/bin/conda
```

I think the issues is that I am sourcing the `conda.sh` from a root installation so despite my env listing a newer version of conda, I am actually using an older version.  

Having fixed that I get:
```
(dd37) ✔  ~/src/bnl/ophyd [doc_release_notes {tacaswell/doc_release_notes}|⚑ 3]
amilyn@10:48  ➤  conda --version
conda 4.7.5

```

If I completely nuke my .condarc I get:

```
dd37) ✔  ~/src/bnl/ophyd [doc_release_notes {tacaswell/doc_release_notes}|⚑ 3]
amilyn@10:49  ➤  conda install -c local pyepics
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyepics

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



```

```
dd37) ✔  ~/src/bnl/ophyd [doc_release_notes {tacaswell/doc_release_notes}|⚑ 3]
amilyn@10:44  ➤  conda install -c ${CONDA_PREFIX}/conda-bld/ pyepics
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/tcaswell/.conda/envs/dd37

  added / updated specs:
    - pyepics


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    epics-base-3.15.6          |       hf484d3e_0        16.0 MB  file:///home/tcaswell/.conda/envs/dd37/conda-bld
    pyepics-3.4.0              |   py37h39e3cac_1         179 KB  file:///home/tcaswell/.conda/envs/dd37/conda-bld
    ------------------------------------------------------------
                                           Total:        16.1 MB

The following NEW packages will be INSTALLED:

  epics-base         conda-bld/linux-64::epics-base-3.15.6-hf484d3e_0
  pyepics            conda-bld/linux-64::pyepics-3.4.0-py37h39e3cac_1


Proceed ([y]/n)? n


CondaSystemExit: Exiting.

```

If I leave my condarc (which points at internal channels) then it hits those instead of 'local'.

**Comment by ReimarBauer** [comment]
We had run into his too.

our solution was to use the rules of the local builded packagename, which is different to any uploaded package.

For example:
`conda create -n mssenv mss=alpha --use-local`

Another option instead of changing the version string is to use an incremented build number and address this by an argument too.


It looks like it is implemented use first match of [repository, local] and `--use-local` only adds the second item.
My expection would be if I set `--use-local` there is nothing from a repository needed, because I have builded everything locally.

**Comment by blackbox-tech** [comment]
I had the same issue using a Microsoft Azure Ubuntu18.04 Data Science image (microsoft-dsvm:ubuntu-1804) , I have to do:
```
conda install -c file://${CONDA_PREFIX}/conda-bld/ my_local_pkg
```
While on Amazon's AWS Ubuntu18.04 Machine Learning image (ami-05f287799f4865acb) I can simply do:
```
conda install --use-local my_local_pkg
```
Its kind of annoying that Microsoft conda installation is setup differently, to the point that basic commands don't work as expected.
