### ISSUE TITLE
Problems Installing OPENCV on a Mac Pro (desktop) running Python 3.6.x under the Anaconda Distribution

### ISSUE THREAD

**Issue by OrbitalMechanic** [conda/conda#7025]
**I'm submitting a...**
  - [ X] bug report
  - [ ] feature request

## Current Behavior

[demo.py_output.txt](https://github.com/conda/conda/files/1805068/demo.py_output.txt)

### Steps to Reproduce

```
python demo.py 
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
import cv2
 
print("OpenCV version:")
print(cv2.__version__)
 
img = cv2.imread("clouds.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
cv2.imshow("Over the Clouds", img)
cv2.imshow("Over the Clouds - gray", gray)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

```
</p></details>

**Comment by jjhelmus** [comment]
Please submit the output from `conda list show-channel-urls` and the other commands in the report template.  Without this it is impossible to debug this issue.
