### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by sleeplessme** [conda/conda#7027]
Hi, im installing anaconda3, trying to open my anaconda prompt and this is what look like
![image](https://user-images.githubusercontent.com/18633984/37355759-15ac863a-2717-11e8-967e-6126f3d60857.png)
if i see other people, it will shows directory not env. is it normal? and if i see my env it shows that only root env, do i must change to default env?
then my i can't launch python from my cmd, how to fix this?
thank you

**Comment by goanpeca** [comment]
@sleeplessme yes it is normal. `base` is now the default environment, which was previously called `root` they are one and the same, but moving forward only `base` will be supported
