### ISSUE TITLE
Problem With Conda Command

### ISSUE THREAD

**Issue by ark00** [conda/conda#7032]
Hi,
I have installed Anaconda 5.1 For Windows Python 3.6 version on my laptop (windows 10).
I was trying to update Anaconda Command Prompt by uning the commands below:
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
But I can not update it.
First error:

`$ C:\Users\Ark\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Ark\Anaconda3
                 HOMEPATH=\Users\Ark
                     PATH=C:\Users\Ark\Anaconda3\Library\bin;C:\Program Files (x86)\Lenovo\Fus
                          ionEngine;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\W
                          indows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common
                          Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C
                          :\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
                          em32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32\config\systemprofile\
                          .dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program
                          Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows
                          Kits\10\Windows Performance Toolkit\;C:\Program Files
                          (x86)\Skype\Phone\;C:\Program Files (x86)\OpenVPN\bin;C:\root_v5.34.36
                          \\bin;C:\Users\Ark\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
               PYTHONPATH=C:\root_v5.34.36\bin\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Ark\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\Ark\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Ark\Anaconda3\pkgs
                          C:\Users\Ark\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Ark\Anaconda3\envs
                          C:\Users\Ark\AppData\Local\conda\conda\envs
                          C:\Users\Ark\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

How can I solve this issue.
Regards,
AK

**Comment by goanpeca** [comment]
Hi @ark00 when you created a new issue there was a template with a lot of information we expect users to fill in before providing any meaningful assistance.

Please complete that information

**Comment by ark00** [comment]
updated the error report

**Comment by ark00** [comment]
Hi, The problem is solved. It looks like the problem was with .condarc file. Therefore, after deleting the file it works.
Thanks,
AK
