### ISSUE TITLE
conda 'fix_shebang' function is improperly 'fixing'

### ISSUE THREAD

**Issue by jrevans** [conda/conda#7039]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

The pattern matching in 'conda/cli/main_package.py:fix_shebang' is called by 'conda build' and will "fix" any shebang line that contains the text 'python' and cause it to be replaces with '
#!/opt/anaconda1anaconda2anaconda3/bin/python'

This means that when I make a conda package where the shebang line is any of the following, then it will be replaced with an incorrect shebang line.

```#!/path/to/conda-bld/prefix/bin/my_fancy_python_wrapper```
```#!/path/to/conda-bld/prefix/bin/ipython```
```#!/path/to/conda/python/install/area/conda-bld/prefix/bin/my_script```

All three of the above lines will cause the 'fix_shebang' function to replace with a simple call to python, simply because it checks for the presence of 'python' in the shebang line.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
          conda version : 4.4.11
    conda-build version : 3.7.1
         python version : 3.6.4.final.0
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-514.2.2.el7.x86_64 rhel/7.0 glibc/2.17
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by mbargull** [comment]
`conda-build` doesn't use `fix_shebang` from `conda.cli.main_package`, though, that code looks equally broken in `conda.cli.main_package` as well as `conda_build.post`.
`conda.cli.main_package` isn't very much used, I assume, but can you open an additional issue over at https://github.com/conda/conda-build/issues?

**Comment by kalefranz** [comment]
`conda package` is labelled `EXPERIMENTAL` and hasn't been touched in a *long* time.  It was actually at one time nearly removed, along with `conda bundle` and `conda run`.  At this time and until further notice I would consider low-priority and unsupported code.

**Comment by mbargull** [comment]
And just the other day I was thinking that it'd be nice to have a functionality to display the package a file belongs to -- and then found `conda package -w` :wink:. But overall I think that subcommand has very limited use, though that `-w` functionality came in handy.

**Comment by kalefranz** [comment]
The `-w` is why the command is even still there probably :)

Someday we should probably bring them all back in.  They need to be fully tested though.  And also we might want to rethink the CLI structure a bit.  Or, in the case of `conda run`, change fundamentally how it works.  TMI probably

**Comment by jrevans** [comment]
I incorrectly thought this was the source of the problem I was having, but it is in fact coming from 'conda_build.post.py' as mentioned above.  I have opened a ticket with 'conda-build'.  Thanks!
