### ISSUE TITLE
conda activate can not activate opencv

### ISSUE THREAD

**Issue by waschbaer00** [conda/conda#7045]
Hi,

after conda activate myenv, myenv is activated and the name is showed at the beginning of the line.

which python3, tells me it is using myenv-python3, but, opencv is still using the version from system environment. 

If I have to add the myenv/PATH/lib/python3.5/ in bashrc, I didn't see any reason to use virtual environment at all.

How could I activate myenv-opencv ?

**Comment by shubhvachher** [comment]
Please give the output of `conda list` and then activate your environment and give the output of `conda list`

**Comment by kalefranz** [comment]
Oops! Please use the issue template. The information requested in the template is very important to be able to solve your problem. We can’t help you without it!
