### ISSUE TITLE
Allow conda search to search build strings

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#705]
This way we it is easy to filter out packages that depend on a particular version of Python.

**Comment by kalefranz** [comment]
Done in conda 4.4.

**Comment by kalefranz** [comment]
The API for `conda search` changes in 4.4.  The argument is now by default MatchSpec, making `search` consistent with `create`, `install`, `update`, and `remove`.  The MatchSpec query language allows specification of both `build` and `build_number`.
