### ISSUE TITLE
Conda status information

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#7055]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request ?

## Current Behavior

Conda 4.4 changed the way it conveyed information about the status of activity 

from `.........` to a spinner `\|/-`. 

### Steps to Reproduce
Run any conda command on 4.4

## Suggestions

The problem when moving to this new way of conveying information is that it does not give any information about "how much time" (even if qualitatively) has elapsed so far. This has 2 effects
- Psychologically it gives the impression of things taking longer, that on top of conda 4.4 being actually slower, further increases this perception of slowness
- It dos not convey information on how much time has passed

Is there any way to provide some actual time information to commands, additional to the spinner?

**Comment by kalefranz** [comment]
The reason I moved to spinner here is because I *do* hope to parallelize a lot of this stuff at some point.  In fact we already have parallelized the repodata downloads.  UI progress indication with parallelized operations in python is... difficult.  Especially if you're limited to python2.

**Comment by goanpeca** [comment]
The thing is that for whatever you do it just sits there with:

`Solving environment: |` which aside the motion of the spinner  it really just gives the impression of being stucked. We should be providing a bit more steps, at least that gives some ides of what conda is doing. Conda is updating the repodata, maybe the environment solving has a couple of subparts. We should provide more information, I do not think the current UX is enough.
