### ISSUE TITLE
Supported ways to use conda as a python library

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7059]
As of conda 4.4, conda can be installed in any environment, not just environments with names starting with `_` (underscore).  That change was made, in part, so that conda can be used as a python library.

There are three supported public modules.  We support

1. `import conda.cli.python_api`.
2. `import conda.api`
3. `import conda.exports`

The first two should have relatively long-term stability.  The third is guaranteed to be stable throughout the lifetime of a feature release series--i.e. minor version number.

Currently, as of conda 4.5, we do not support `pip install conda`. However, we are considering that as a supported bootstrap method in the future.

**Comment by kalefranz** [comment]
Given https://github.com/pypa/pip/issues/5081, probably good to have this here, and then move to official documentation.

**Comment by kalefranz** [comment]
See, e.g.:

https://github.com/conda/conda/blob/3b86094690b0da16eff3c44c7cbd361953dd73b0/conda/cli/python_api.py#L36-L66

https://github.com/conda/conda/blob/3b86094690b0da16eff3c44c7cbd361953dd73b0/conda/api.py#L15-L26

https://github.com/conda/conda/blob/3b86094690b0da16eff3c44c7cbd361953dd73b0/conda/api.py#L147-L152

https://github.com/conda/conda/blob/3b86094690b0da16eff3c44c7cbd361953dd73b0/conda/api.py#L237-L242

https://github.com/conda/conda/blob/3b86094690b0da16eff3c44c7cbd361953dd73b0/conda/api.py#L365-L370

**Comment by kalefranz** [comment]
Also relevant...  Conda *does* follow semantic versioning--when viewed from the perspective of conda as an *application*.  When thinking of conda as a *library*, the minor version should be considered the major version.  Minor version bumps signify major feature releases for conda.  The semver definition for micro version bumps applies in both cases of conda as an application and conda as a library.

**Comment by kalefranz** [comment]
@electronwill @kerrywatson1 @csoja Can we add this content to the conda docs?

**Comment by rrigdon** [comment]
This content lives here: 
https://docs.conda.io/projects/conda/en/latest/api/index.html
