### ISSUE TITLE
Conda installs dependencies from the wrong channel

### ISSUE THREAD

**Issue by vvug** [conda/conda#7071]
I'm using conda 4.5.0 with two channels, like this (`~/.condarc`):
```
channels:
  - defaults
  - conda-forge
```
so I expect packages to be pulled from `defaults`, if available, or from `conda-forge` otherwise. I explicitly installed a package from `conda-forge`, like this:
```
conda install gmt -c conda-forge/label/dev
```
I don't think this package is getting updated automatically with `conda update --all` (as newers versions are not in the `defaults` channel), so I manually gave the install command once again, to force an update:
```
conda install gmt -c conda-forge/label/dev
```
Turns out that no new version is available, but conda still tries to install two packages, replacing the currently installed version (from `defaults`) with versions from `conda-forge`:
```
Solving environment: done

## Package Plan ##

  environment location: /home/[...]

  added / updated specs:
    - gmt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.14.0rc1            |py36_blas_openblas_200         9.0 MB  conda-forge/label/dev
    scipy-1.0.0                |py36_blas_openblas_201        40.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        49.3 MB

The following packages will be UPDATED:

    scipy: 1.0.0-py36hbf646e7_0  --> 1.0.0-py36_blas_openblas_201     conda-forge           [blas_openblas]

The following packages will be DOWNGRADED:

    numpy: 1.14.2-py36hdbf6ddf_0 --> 1.14.0rc1-py36_blas_openblas_200 conda-forge/label/dev [blas_openblas]

Proceed ([y]/n)?
```
A `conda update --all` does not try to install those packages.
I think this is a bug.

**Comment by kalefranz** [comment]
Your issue has been closed because you are reporting what you perceive to be a bug, and you did not use the issue template.  To understand what's going on, we need information that's requested in the issue template.
