### ISSUE TITLE
get this error using openpyxl when trying to save an excel worksheetPermissionError: [Errno 13] Permission denied:. tried every soulutin mentioned in the web, still fails

### ISSUE THREAD

**Issue by ssibecas** [conda/conda#7081]
**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by mingwandroid** [comment]
Closing. Please provide the information asked for when you file bug reports.

**Comment by ssibecas** [comment]
Figure out how to get around it
