### ISSUE TITLE
Conda update fails when custom channel is offline

### ISSUE THREAD

**Issue by cbcoutinho** [conda/conda#7085]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I have a custom channel at work that is located on a network drive. When I'm not at work/connected to the internal network, the network drive is not visible. I was hoping that a simple `conda update --all` would at least find the channels that are visible (in my case, the only other one is `defaults`), and forget about the packages I installed via our internal network.

Currently `conda` fails because it can't find my channel

```
$ conda update conda
Solving environment: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ C:\Development\anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Development\anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Development\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Development\anaconda3\python.exe
               CONDA_ROOT=C:\Development\anaconda3
              CONDA_SHLVL=1
                 GEM_PATH=C:\Users\ccoutinho\scoop\apps\ruby\current\gems
                 HOMEPATH=\Users\ccoutinho
                     PATH=C:\Development\anaconda3;C:\Development\anaconda3\Library\mingw-w64\bi
                          n;C:\Development\anaconda3\Library\usr\bin;C:\Development\anaconda3\Li
                          brary\bin;C:\Development\anaconda3\Scripts;C:\Development\anaconda3\bi
                          n;C:\Program Files\Microsoft HPC Pack 2012\Bin\;C:\ProgramData\Oracle\
                          Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;
                          C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\MATLAB\R2017b\bin;C:\Program Files\MATLAB\R2016b\bin;C:\Program
                          Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program
                          Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\Client
                          SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\Binn\ManagementStudio\;C:\Program Files
                          (x86)\Silverfrost\FTN95;C:\Program Files\PuTTY\;C:\WINDOWS\system32\co
                          nfig\systemprofile\.dnx\bin;C:\Program Files\Microsoft
                          DNX\Dnvm\;C:\Program Files\nodejs\;C:\Development\Git\cmd;C:\Program
                          Files (x86)\Gpg4win\..\GnuPG\bin;C:\Users\ccoutinho\scoop\apps\msys2\c
                          urrent;C:\Users\ccoutinho\scoop\apps\ruby\current\gems\bin;C:\Users\cc
                          outinho\scoop\apps\ruby\current\bin;C:\Users\ccoutinho\AppData\Local\P
                          rograms\Python\Launcher\;C:\Users\ccoutinho\scoop\shims;C:\Development
                          \Go\bin;C:\Users\ccoutinho\go\bin;C:\Users\ccoutinho\.lein\bin;C:\User
                          s\ccoutinho\.cargo\bin;C:\Program Files\CMake\bin;C:\Users\ccoutinho\A
                          ppData\Local\atom\bin;C:\Development\mingw-w64\x86_64-7.1.0-posix-seh-
                          rt_v5-rev0\mingw64\bin;C:\Development\mingw-w64\x86_64-7.1.0-posix-
                          seh-rt_v5-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\7.1.0;C:\Development
                          \OpenBLAS\install\bin;C:\Development\lapack\install\bin;C:\Development
                          \mingw-w64\i686-7.1.0-posix-dwarf-rt_v5-rev0\mingw32\lib\gcc\i686-w64-
                          mingw32\7.1.0;C:\Development\mingw-w64\i686-7.1.0-posix-dwarf-rt_v5-re
                          v0\mingw32\bin;C:\Development\lapack\install-32\bin;C:\Development\Git
                          \cmd;C:\Development\Git\mingw64\bin;C:\Development\Git\usr\bin;C:\texl
                          ive\2016\bin\win32;C:\Development\gmsh-2.16.0;C:\Development\ffmpeg\ff
                          mpeg-20170321-db7a05d-win64-static\ffmpeg-20170321-db7a05d-win64-stati
                          c\bin;C:\Program Files (x86)\Microsoft Visual
                          Studio\Shared\14.0\VC\bin;C:\Program Files (x86)\Microsoft Visual Stud
                          io\2017\Community\SDK\ScopeCppSDK\SDK\include\ucrt;C:\Users\ccoutinho\
                          AppData\Roaming\npm;C:\Users\ccoutinho\AppData\Local\Pandoc\;C:\Users\
                          ccoutinho\AppData\Local\Microsoft\WindowsApps;C:\Development\cmder;C:\
                          Program Files\Microsoft VS Code\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Development\anaconda3
            shell level : 1
       user config file : C:\Users\ccoutinho\.condarc
 populated config files : C:\Users\ccoutinho\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.4.final.0
       base environment : C:\Development\anaconda3  (writable)
           channel URLs : file:///R:/Conda_channel/win-64
                          file:///R:/Conda_channel/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Development\anaconda3\pkgs
                          C:\Users\ccoutinho\AppData\Local\conda\conda\pkgs
       envs directories : C:\Development\anaconda3\envs
                          C:\Users\ccoutinho\AppData\Local\conda\conda\envs
                          C:\Users\ccoutinho\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 404 CONNECTION FAILED for url <file:///R:/Software/redstack_channel/noarch/repodata.json>
Elapsed: 00:00.000110

The remote server could not find the noarch directory for the
requested channel with url: file:///R:/Software/redstack_channel

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

A reportable application error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

```

### Steps to Reproduce

Connect to an internal network and add the channel to your conda config:

```
conda config --add channels file://R:/Conda_channel
conda install my_custom_package

*** log off network ***

conda update --all
FAIL
```

## Expected Behavior
I would expect `conda` to just ignore the nonexistent channel and update all other packages it can.

## Environment Information

```
$ conda info
     active environment : base
    active env location : C:\Development\anaconda3
            shell level : 1
       user config file : C:\Users\ccoutinho\.condarc
 populated config files : C:\Users\ccoutinho\.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.4.final.0
       base environment : C:\Development\anaconda3  (writable)
           channel URLs : file:///R:/Conda_channel/win-64
                          file:///R:/Conda_channel/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Development\anaconda3\pkgs
                          C:\Users\ccoutinho\AppData\Local\conda\conda\pkgs
       envs directories : C:\Development\anaconda3\envs
                          C:\Users\ccoutinho\AppData\Local\conda\conda\envs
                          C:\Users\ccoutinho\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```

**Comment by cbcoutinho** [comment]
Oops, looks like I should have looked a bit further. This is actually expected behavior: https://github.com/conda/conda/issues/5149

**Comment by preeti-n** [comment]
Traceback (most recent call last):
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\Users\91798\anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\Users\91798\anaconda3\Scripts\conda-script.py install -c conda-forge/label/cf201901 opencv`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\91798\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\91798\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\91798\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\91798\anaconda3\python.exe
               CONDA_ROOT=C:\Users\91798\anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\91798
                     PATH=C:\Users\91798\anaconda3;C:\Users\91798\anaconda3\Library\mingw-w64\bi
                          n;C:\Users\91798\anaconda3\Library\usr\bin;C:\Users\91798\anaconda3\Li
                          brary\bin;C:\Users\91798\anaconda3\Scripts;C:\Users\91798\anaconda3\bi
                          n;C:\Users\91798\anaconda3;C:\Users\91798\anaconda3\Library\mingw-w64\
                          bin;C:\Users\91798\anaconda3\Library\usr\bin;C:\Users\91798\anaconda3\
                          Library\bin;C:\Users\91798\anaconda3\Scripts;C:\Users\91798\anaconda3\
                          bin;C:\Users\91798\anaconda3\condabin;C:\windows\system32;C:\windows;C
                          :\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\
                          windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Users\91798\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\91798\anaconda3
            shell level : 1
       user config file : C:\Users\91798\.condarc
 populated config files : C:\Users\91798\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.0
       base environment : C:\Users\91798\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/label/cf201901/win-64
                          https://conda.anaconda.org/conda-forge/label/cf201901/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\91798\anaconda3\pkgs
                          C:\Users\91798\.conda\pkgs
                          C:\Users\91798\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\91798\anaconda3\envs
                          C:\Users\91798\.conda\envs
                          C:\Users\91798\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

pls resolve the issue
