### ISSUE TITLE
Incorrect command to activate the environment, if there is space in environment name.

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7092]
_From @RidaZubair on March 27, 2018 11:51_

**OS: Linux
Anaconda Navigator**

**Steps to Reproduce:**

- Install Anaconda.
- Create an environment with space.
- Check the command to activate the environment

**Actual Result:**
inverted commas are missing in command to activate the environment if there are spaces in name.
![image](https://user-images.githubusercontent.com/27444898/37964518-3fcfe6ea-31db-11e8-8720-8a8da9242a6f.png)

_Copied from original issue: ContinuumIO/anaconda#1367_

**Comment by kalefranz** [comment]
_From @csoja on March 27, 2018 14:3_

@kalefranz I didn't think we supported spaces in environment names?  Is that documented?

**Comment by kalefranz** [comment]
You have to quote the name. Standard command line parsing.

**Comment by kalefranz** [comment]
_From @sriaz2 on March 27, 2018 14:58_

@kalefranz "You have to quote the name. Standard command line parsing."
That is what the issue is reporting, the command presented by conda in the terminal to activate environment should contain quotes if there is a space in the environment name. 
<img width="715" alt="screen shot 2018-03-27 at 7 58 14 pm" src="https://user-images.githubusercontent.com/20394675/37975652-39817b0a-31f9-11e8-977c-6d634f73959e.png">

**Comment by kalefranz** [comment]
The correct fix here is to detect spaces in the environment name, and then if detected, show the red box as

    source activate "test space enviroooooonment"

**Comment by mingwandroid** [comment]
Or just don't support this pointless misfeature :-)

**Comment by kalefranz** [comment]
Right.  We could also raise an error on `conda create -n "environment name"` that spaces are not allowed in environment names.

**Comment by kalefranz** [comment]
> inverted commas are missing in command

???????

**Comment by kalefranz** [comment]
Oh, quotation marks.  I've never heard them called inverted commas haha

**Comment by goanpeca** [comment]
This has been fixed on #7168. Closing
