### ISSUE TITLE
When will the release go to installer archive?

### ISSUE THREAD

**Issue by hsiaoyi0504** [conda/conda#7093]
Hi all,

I am curious about when will the release of this repo appear on the installer archive.

I saw that we have version `4.5.0` in this repo, but it seems that the latest version of installer archive listed in https://repo.continuum.io/miniconda/index.html is still `4.4.10`.

Personally, I have a repo based on docker and want to install miniconda version higher than `4.4.10` inside the doccker to avoid the issue #6811.

**Comment by kalefranz** [comment]
We don't make Miniconda installers for every conda version.  It's really not necessary.  Just run `conda update conda` after executing the latest miniconda installer.  Check out Dockerfiles at https://github.com/conda/conda-docker/tree/master/miniconda3 for how we do it all in one step to make the most optimum use of Docker's layered filesystem.

**Comment by hsiaoyi0504** [comment]
Thanks for the information, so what's the rule  or condition that one of the version will be put into archive?

**Comment by kalefranz** [comment]
Miniconda installers are made for every version of conda that is put into an Anaconda installer.  And we occasionally make others.
