### ISSUE TITLE
CondaHTTPError

### ISSUE THREAD

**Issue by ktavabi** [conda/conda#7095]
**I'm submitting a...**
  - [x] bug report

## Current Behavior
`conda update conda` or `conda env create -n newenv -f PATH/TO/ENV.YML` both fail for conda `version 4.5.0` 

### Steps to Reproduce
```
conda update conda
```

> Solving environment: failed
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
> `$ /home/.../miniconda3/bin/conda update conda`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>                CONDA_ROOT=/home/.../miniconda3
>             DEFAULTS_PATH=/usr/share/gconf/mate.default.path
>           LD_LIBRARY_PATH=/usr/local/MNE/MNE-2.7.4-3505-Linux-x86_64/lib
>            MANDATORY_PATH=/usr/share/gconf/mate.mandatory.path
>              MNE_BIN_PATH=/usr/local/MNE/MNE-2.7.4-3505-Linux-x86_64/bin
>              MNE_LIB_PATH=/usr/local/MNE/MNE-2.7.4-3505-Linux-x86_64/lib
>              MNI_DATAPATH=/usr/local/freesurfer/v6-BETA/freesurfer/mni/data
>                      PATH=/home/.../miniconda3/bin:/usr/local/MNE/MNE-2.7.4-3505-Linux-x86_6
>                           4/bin:/usr/local/freesurfer/v6-BETA/freesurfer/bin:/usr/local/freesurf
>                           er/v6-BETA/freesurfer/fsfast/bin:/usr/local/freesurfer/v6-BETA/freesur
>                           fer/tktools:/usr/local/fsl/bin:/usr/local/freesurfer/v6-BETA/freesurfe
>                           r/mni/bin:/home/.../bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/
>                           usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
>             XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
>          XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
>       XUSERFILESEARCHPATH=/usr/local/MNE/MNE-2.7.4-3505-Linux-x86_64/share/app-defaults/%N
> 
>      active environment : None
>        user config file : /home/.../.condarc
>  populated config files : /home/.../.condarc
>           conda version : 4.5.0
>     conda-build version : not installed
>          python version : 3.6.1.final.0
>        base environment : /home/.../miniconda3  (writable)
>            channel URLs : https://pypi.python.org/pypi/linux-64
>                           https://pypi.python.org/pypi/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/linux-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>           package cache : /home/ktavabi/miniconda3/pkgs
>                           /home/ktavabi/.conda/pkgs
>        envs directories : /home/ktavabi/miniconda3/envs
>                           /home/ktavabi/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.5.0 requests/2.5.3 CPython/3.6.1 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : False
> 
> 
> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> 
> CondaHTTPError: HTTP 404 NOT FOUND for url <https://pypi.python.org/pypi/noarch/repodata.json>
> Elapsed: 00:00.205198
> 
> The remote server could not find the noarch directory for the
> requested channel with url: https://pypi.python.org/pypi
> 
> As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
> associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
> empty. please request that the channel administrator create
> `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
> $ mkdir noarch
> $ echo '{}' > noarch/repodata.json
> $ bzip2 -k noarch/repodata.json
> 
> You will need to adjust your conda configuration to proceed.
> Use `conda config --show channels` to view your configuration's current state.
> Further configuration help can be found at <https://conda.io/docs/config.html>.
> 
> A reportable application error has occurred. Conda has prepared the above report.
> Upload successful.

## Expected Behavior
Either update conda or create new environment as per `environment.yml`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : None
       user config file : /home/ktavabi/.condarc
 populated config files : /home/ktavabi/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.1.final.0
       base environment : /home/ktavabi/miniconda3  (writable)
           channel URLs : https://pypi.python.org/pypi/linux-64
                          https://pypi.python.org/pypi/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ktavabi/miniconda3/pkgs
                          /home/ktavabi/.conda/pkgs
       envs directories : /home/ktavabi/miniconda3/envs
                          /home/ktavabi/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.5.3 CPython/3.6.1 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/.../.condarc <==
channels:
  - https://pypi.python.org/pypi
  - defaults
report_errors: True


```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
==> /home/.../.condarc <==
channels:
  - https://pypi.python.org/pypi
  - defaults
report_errors: True

ktavabi@Nara:~$ conda list --show-channel-urls
# packages in environment at /home/ktavabi/miniconda3:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                     <pip>
arrow                     0.10.0                    <pip>
asn1crypto                0.22.0                   py36_0    defaults
attrs                     17.4.0                    <pip>
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.10.0                   py36_0    defaults
conda                     4.5.0                    py36_0    defaults
conda-env                 2.6.0                         0    defaults
cryptography              1.8.1                    py36_0    defaults
decorator                 4.2.1                     <pip>
idna                      2.5                      py36_0    defaults
libffi                    3.2.1                         1    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
niprov                    0.5                       <pip>
numpy                     1.14.1                    <pip>
olefile                   0.44                      <pip>
openssl                   1.0.2o               h20670df_0    defaults
packaging                 16.8                     py36_0    defaults
Pillow                    4.3.0                     <pip>
pip                       9.0.1                    py36_1    defaults
pluggy                    0.6.0                     <pip>
pocket                    0.3.6                     <pip>
py                        1.5.2                     <pip>
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.17                     py36_0    defaults
pycuda                    2017.1.1                  <pip>
pyfiglet                  0.7.5                     <pip>
pyopenssl                 17.0.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
PySocks                   1.6.7                     <pip>
pytest                    3.4.1                     <pip>
python                    3.6.1                         2    defaults
python-dateutil           2.6.1                     <pip>
pytools                   2017.6                    <pip>
rainbowstream             1.3.7                     <pip>
readline                  6.2                           2    defaults
requests                  2.5.3                     <pip>
requests                  2.14.2                   py36_0    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-cuda               0.5.2                     <pip>
seaborn                   0.8.1                     <pip>
setuptools                36.5.0           py36he42e2e1_0    defaults
six                       1.10.0                   py36_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
twitter                   1.17.1                    <pip>
wheel                     0.29.0                   py36_0    defaults
xlrd                      1.1.0                     <pip>
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults

```
</p></details>

**Comment by kalefranz** [comment]
`https://pypi.python.org/pypi` is not a conda channel.

    conda config --remove channels https://pypi.python.org/pypi

**Comment by ktavabi** [comment]
Thanks @kalefranz by chance any idea are there circumstances `.condarc` could be edited without user knowledge? IIRC I've never edited `.condarc`

**Comment by kalefranz** [comment]
via `conda config` commands

**Comment by UMSAJAD** [comment]
i got this error 
can any one tell me what to do

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: face_recognition
  channel url: https://conda.anaconda.org/face_recognition
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations
