### ISSUE TITLE
ERROR conda.core.link:_execute(481): An error occurred while uninstalling package 'defaults

### ISSUE THREAD

**Issue by 1rdsk1** [conda/conda#7100]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by 1rdsk1** [comment]
Hi

On m Windows10 conda just installed, I was surprised to be told to upgrade Navigator from 1.7.0 to 1.8.2  since I'd only just installed it.  As packages werent installing on Navigator I tried to upgrade with command below as the navigator upgrade just kept running for too long (over 30mins).

conda update anaconda-navigator

which give error:
ERROR conda.core.link:_execute(481): An error occurred while uninstalling package 'defaults::freetype-2.8-h51f8f2c_1'.
PermissionError(13, 'Access is denied')

Full output below.  I am also unable to install packages with in Navigator or at command prompt.  I tried  to install knitr and nbstripout but both failed

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - anaconda-navigator


The following packages will be UPDATED:

    certifi:  2018.1.18-py36_0  --> 2018.1.18-py36_0 conda-forge
    freetype: 2.8-h51f8f2c_1    --> 2.8.1-vc14_0     conda-forge [vc14]
    jpeg:     9b-hb83a4c4_2     --> 9b-vc14_2        conda-forge [vc14]
    libxml2:  2.9.7-h79bbb47_0  --> 2.9.8-vc14_0     conda-forge [vc14]
    sqlite:   3.22.0-h9d3ae62_0 --> 3.22.0-vc14_0    conda-forge [vc14]

The following packages will be DOWNGRADED:

    yaml:     0.1.7-hc54c509_2  --> 0.1.7-vc14_0     conda-forge [vc14]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while uninstalling package 'defaults::freetype-2.8-h51f8f2c_1'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

**Comment by saidatta21** [comment]
open command prompt as administrator and then try to update

**Comment by zoexili** [comment]
@saidatta21  Thank you!

**Comment by dkumawat1** [comment]
how???please tell?

**Comment by gerryharp** [comment]
For me on Windows7. Right click on 
Windows Button: All Programs: Anaconda3 (64 bit): Anaconda prompt

choose Run as administrator
On windows 10, you can search for Anaconda and probably find the prompt link that way.

**Comment by fredrikaverpil** [comment]
I was hoping to be able to install Miniconda3 in Windows 10 once (multiuser install dir) and then be able to initiate a conda update from within Python:

Install Miniconda3 in Windows 10, multiuser with default path. I've also ticked the checkbox "Add to PATH".

Run the following (Python 3.6):
```
import subprocess
import shutil


cmd = [shutil.which('conda'), 'update', '--yes', '-n', 'base', 'conda']

proc = subprocess.Popen(
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)

output, err = proc.communicate()
print(err)
```

This yields the following for me in Windows 10 with mulituser Miniconda3 install:

```
b"ERROR conda.core.link:_execute(481): An error occurred while uninstalling package 'defaults::conda-4.4.10-py36_0'.\r\nPermissionError(13, 'Access is denied')\r\nAttempting to roll back.\r\n\r\n\r\nPermissionError(13, 'Access is denied')\r\n\r\n\r\n"
```

It seems that a multiuser install on macOS does not have this kind of issue.

What I'm wondering is; can I somehow work around this at all, or am I forced to install Miniconda3 for each user under Windows 10?
I need to be able to trigger a conda update from within Python running without elevated privileges.

**Comment by kalefranz** [comment]
> can I somehow work around this at all

You'll need to elevate privileges to Administrator for that python process.  There's no way around that if you install conda in multi-user mode.  Multi-user mode means the base environment is Administrator-owned, and therefore modifying the base environment can only be accomplished with administrator privileges.  However, you can create, activate, and modify new, non-base environment when the base environment is read-only.  *That* is what multi-user mode is all about.

> I need to be able to trigger a conda update from within Python running without elevated privileges.

Then you'll have to install conda/miniconda for your current user, so that your current user has write permissions for the environment.

> It seems that a multiuser install on macOS does not have this kind of issue.

Not true.  Same situation.  On macOS you'd also need to elevate privileges to update the base environment when the base environment is read-only to the current user.
