### ISSUE TITLE
Python multiprocessing with POWER8 throws up error

### ISSUE THREAD

**Issue by DiableJambe** [conda/conda#7102]
I installed [miniconda for POWER8 ](https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-ppc64le.sh). When I use python multiprocessing, I get the following error:

"Error: processor architecture is not supported in cpuinfo"

Eventhough some threads still run, about half the threads remain inactive. Please help addressing this.

**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
   active environment : None
       user config file : /root/.condarc
 populated config files :
          conda version : 4.4.9
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-ppc64le
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-ppc64le
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-ppc64le
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-ppc64le
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-ppc64le
             user-agent : conda/4.4.9 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

<details><summary><code>`python --version`</code></summary><p>

```
Python 3.6.4 :: Anaconda, Inc.
```
</p></details>

<details><summary><code>`nvidia-docker --version`</code></summary><p>

```
Docker version 17.09.0-ce-rc1, build ae21824
```
</p></details>

**Comment by jjhelmus** [comment]
Can you provide some addition context of the environment where you are seeing the error?  Python version, the code that produces the error and the full traceback/error message would all be helpful.

**Comment by kalefranz** [comment]
Nothing going on with conda here.  Maybe an issue with a particular package (python or something else).  Moving to anaconda-issues.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#9026
