### ISSUE TITLE
Cannot Update tbl2asn through Conda

### ISSUE THREAD

**Issue by oseias-r-junior** [conda/conda#7103]
I'm having a problem with trying to update the current version of tbl2asn through conda. <I'm not sure if I'm having this issue any how regarding on my 32bit cpu labtop, but anyway>...

-$ conda install tbl2asn
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tbl2asn

Current channels:

  - https://repo.continuum.io/pkgs/main/linux-32
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-32
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-32
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-32
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by kalefranz** [comment]
The package is not available in your configured channels.
