### ISSUE TITLE
conda raises bogus NotWritableError exception for a bogus attempt to chown to root

### ISSUE THREAD

**Issue by whitequark** [conda/conda#7109]
I am attempting to upgrade an existing installation of conda by running `conda update conda anaconda-client` (though the specific command does not appear to be important, anything that results in changes to `~/.conda`, i.e. practically any command, has the same problem). This results in the following error:

```
NotWritableError: The current user does not have write permissions to a required path.
  path: /var/lib/buildbot/.conda/environments.txt
  uid: 104
  gid: 111

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 104:111 /var/lib/buildbot/.conda/environments.txt

In general, it's not advisable to use 'sudo conda'.
```

Running the same command with `strace -eopen,chown -f` prepended shows the following relevant syscalls:

```
[pid  4612] open("/var/lib/buildbot/.conda/environments.txt", O_WRONLY|O_CREAT|O_APPEND, 0666) = 8
[pid  4612] chown("/var/lib/buildbot/.conda/environments.txt", 0, 0) = -1 EPERM (Operation not permitted)
```

Two things are wrong here.
  1. The error message is completely wrong. The file *is* writable by the current user, and the permissions are set correctly.
  2. Conda is trying to change the owner of a file when it is not root.

The reason Conda is trying to do this is because of the environment variables `SUDO_UID` and `SUDO_GID` that are both set to `0`. This happens because I logged in, elevated to `root`, and then used `sudo -u buildbot -s -H` to perform maintenance tasks under a different user account.

## Expected Behavior
Conda should stop messing with filesystem permissions and lying to me.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /var/lib/buildbot/.condarc
 populated config files : /var/lib/buildbot/.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.5.2.final.0
       base environment : /var/lib/buildbot/slaves/conda-lin64/miniconda  (writable)
           channel URLs : http://conda.anaconda.org/m-labs/channel/dev/linux-64
                          http://conda.anaconda.org/m-labs/channel/dev/noarch
                          http://conda.anaconda.org/m-labs/channel/main/linux-64
                          http://conda.anaconda.org/m-labs/channel/main/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /var/lib/buildbot/slaves/conda-lin64/miniconda/pkgs
                          /var/lib/buildbot/.conda/pkgs
       envs directories : /var/lib/buildbot/slaves/conda-lin64/miniconda/envs
                          /var/lib/buildbot/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.13.0 CPython/3.5.2 Linux/3.13.0-137-generic ubuntu/14.04 glibc/2.19
                UID:GID : 104:111
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/6569
xref: https://github.com/conda/conda/issues/6576

**Comment by kalefranz** [comment]
A fix for this is in the master branch, which is currently the release branch for 4.6.0.  A 4.6.0a1 build exists that you can test in the `conda-canary` channel.

**Comment by mickeyperlstein** [comment]
$conda --version
conda 4.5.12 
$lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:   xenial
$ conda search "^python$"
Loading channels: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /home/mickey/anaconda3/pkgs/cache/98cb6fa3.json
  uid: 1000
  gid: 1000

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1000:1000 /home/mickey/anaconda3/pkgs/cache/98cb6fa3.json

In general, it's not advisable to use 'sudo conda'.
