### ISSUE TITLE
toposort algorithm has corner cases where cycles are broken in obviously incorrect ways

### ISSUE THREAD

**Issue by scottdraves** [conda/conda#7115]
bug report

See https://github.com/twosigma/beakerx/issues/7095, which has a Dockerfile and env.yml file that reproduces the problem.

The problem is beakerx post-link.sh script is being run before pandas is installed, even though pandas is declared as a dependency of beakerx.

**Comment by kalefranz** [comment]
This is because conda-forge has cycles in their dependency graph.

```
DEBUG conda.common.toposort:_safe_toposort(80): Cyclic dependencies exist among these items: 'beakerx' -> 'mkl_fft' -> 'mkl_random' -> 'pandas' -> 'numpy'
DEBUG conda.common.toposort:_safe_toposort(80): Cyclic dependencies exist among these items: 'mkl_fft' -> 'mkl_random' -> 'pandas' -> 'numpy'
DEBUG conda.common.toposort:_safe_toposort(80): Cyclic dependencies exist among these items: 'mkl_random' -> 'pandas' -> 'numpy'
```

If instead you put `defaults` ahead of `conda-forge` in your channel priority list, there's no cycle.

    conda create -n beakerx beakerx -c defaults -c conda-forge

**Comment by mingwandroid** [comment]
Conda could still do better here. Once it discovers a cycle it just installs things in random order AFAIR.

Thing is, the cycle might not involve any packages with install scripts.

**Comment by kalefranz** [comment]
I take it back. There's still the same cycle, but the cycle is getting broken differently somehow.

**Comment by scottdraves** [comment]
Thank you, will try that out.

That's super interesting can you provide more info about the cycle and what package should be fixed to break it?

Is the cycle like:

'mkl_fft' -> 'mkl_random' -> 'pandas' -> 'numpy' -> 'mkl' -> ... ? -> 'mkl_fft'

**Comment by kalefranz** [comment]
Here's the code that conda uses to break cycles:

https://github.com/conda/conda/blob/31130cd80d868b4d5f52db7f89fc53a274e678bf/conda/models/prefix_graph.py#L265-L279

While that's conda 4.5 code, the same algorithm has been used for many years.

https://github.com/conda/conda/blob/31130cd80d868b4d5f52db7f89fc53a274e678bf/conda/common/toposort.py#L46-L59

**Comment by kalefranz** [comment]
Here's the issue.  Probably not with conda-forge, given that I don't think conda-forge distributes mkl.

```
numpy 1.14.2 py36ha9ae307_1
---------------------------
file name   : numpy-1.14.2-py36ha9ae307_1.tar.bz2
name        : numpy
version     : 1.14.2
build string: py36ha9ae307_1
build number: 1
size        : 4.0 MB
constrains  : ()
license     : BSD 3-Clause
subdir      : osx-64
url         : https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.14.2-py36ha9ae307_1.tar.bz2
md5         : aad7a39434d427467512c56962406940
dependencies:
  - libgfortran >=3.0.1
  - mkl >=2018.0.2
  - mkl_fft
  - mkl_random
  - python >=3.6,<3.7.0a0

mkl_random 1.0.1 py36h78cc56f_0
-------------------------------
file name   : mkl_random-1.0.1-py36h78cc56f_0.tar.bz2
name        : mkl_random
version     : 1.0.1
build string: py36h78cc56f_0
build number: 0
size        : 346 KB
constrains  : ()
license     : BSD 3-Clause
subdir      : osx-64
url         : https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.0.1-py36h78cc56f_0.tar.bz2
md5         : c491b70aa88beb9be234b502bb93169f
dependencies:
  - libcxx >=4.0.1
  - mkl
  - numpy >=1.11.3,<2.0a0
  - python >=3.6,<3.7.0a0
```

`numpy` depends on `mkl_random` and `mkl_random` depends on `numpy`

So why is `beakerx` getting caught in this cycle?

```
beakerx 0.14.0 py36_1
---------------------
file name   : beakerx-0.14.0-py36_1.tar.bz2
name        : beakerx
version     : 0.14.0
build string: py36_1
build number: 1
size        : 103.4 MB
arch        : x86_64
constrains  : ()
platform    : Platform.osx
license     : Apache-2.0
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/beakerx-0.14.0-py36_1.tar.bz2
md5         : 63303c7284604798b1f96587a359d483
dependencies:
  - ipywidgets >=7.0
  - maven
  - notebook >=4.4.0
  - openjdk
  - pandas
  - pytest
  - python 3.6*
  - widgetsnbextension
```

Maybe only because there *is* a cycle, and the algorithm to break the cycle is doing just what the comment says, which is definitely suboptimal in this case.

**Comment by kalefranz** [comment]
Ok, I agree with @mingwandroid that conda can do better here.  This is a good test case.

**Comment by kalefranz** [comment]
Setting a breakpoint above `yield pop_key(data)` in

https://github.com/conda/conda/blob/31130cd80d868b4d5f52db7f89fc53a274e678bf/conda/common/toposort.py#L79-L85

The contents of `data` is

    {'beakerx': {'pandas'}, 'mkl_fft': {'numpy'}, 'mkl_random': {'numpy'}, 'pandas': {'numpy'}, 'numpy': {'mkl_fft', 'mkl_random'}}

regardless of the priority order of `defaults` and `conda-forge`.

**Comment by kalefranz** [comment]
So probably the most immediate problem here is that `beakerx` and `pandas` aren't at all involved in the cycle, but they're getting roped in by the algorithm anyway.  The cycle is really just

    {'mkl_fft': {'numpy'}, 'mkl_random': {'numpy'}, 'numpy': {'mkl_fft', 'mkl_random'}}

**Comment by scottdraves** [comment]
Cool thanks.

Maybe also a good idea to print a warning that a cycle has been detected.

**Comment by mcg1969** [comment]
I'm afraid I can't—will need to find another resource. I can offer assistance.
