### ISSUE TITLE
With conda being a shell function in 4.4+, what's the suggested way to use conda via scripts when an environment isn't explicitly activated by the user beforehand?

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7126]
From gitter starting https://gitter.im/conda/conda?at=5ac4e56dc574b1aa3e67a0d8

@natefoo:

> With conda being a shell function in 4.4+, what's the suggested way to use conda via scripts when an environment isn't explicitly activated by the user beforehand?

@mbargull:

> You'd have to explicitly activate the environment beforehand for this to work. I.e., run
>
>     . /path/to/etc/profile.d/conda.sh
>     conda activate base
> If you run that outside of your script, then this would put the conda executable on PATH. If you run it inside of the script, then the script can use the shell function. There are some features, e.g., automatic environment reactivation, that the shell function provides. So if you install/remove packages with (de)activation script into the currently activated environment, you'd want to use the shell function, i.e., source conda.sh inside your script.

@natefoo:

> The issue here is that it's potentially really confusing for users. If I'm delivering a script that is supposed to create an env and install all our dependencies in to it, until 4.4 they didn't need to do anything other than the required conda set up (putting the base env's `bin` on `$PATH`). Now they have to activate the base env before they run the script.
> I can't do it in the script because I don't know where conda is installed if they don't activate the base env. But that wasn't the case before.
> If nothing else, an exported env var for the path to conda.sh would be sufficient.
> Because the function stuff is pretty transparent to users, so it's not going to be readily apparent why they can run conda on the command line but if they call my script in the same shell, it can't run conda.

@mbargull:

> For reference `CONDA_EXE` was introduced in conda/conda#6923.

@natefoo:

> `$CONDA_EXE` only gets you part of the way there, too, since you need the shell functions for `activate` to work, and if you don't have the path to `conda.sh`, you don't have the shell functions. I can use `$(dirname $CONDA_EXE)/../etc/profile.d/conda.sh` to get the path, but that's pretty hacky.
> 
> I guess source `$(dirname $CONDA_EXE)/activate <env>` would also work as long as `activate` and `deactivate` stick around, but it's a hack too.
> 
> The shell check in activate explicitly precludes `. $(dirname $CONDA_EXE)/activate ...` from working under dash. =(

**Comment by kalefranz** [comment]
As of right now, with #6923, `$CONDA_EXE` only works after the first `conda activate`.  What *does* work right now is `$_CONDA_EXE`.  We'll be transitioning `$_CONDA_EXE` to `$CONDA_EXE` in all the shell wrappers to avoid this problem (and will keep `$_CONDA_EXE` around for a while to help with migration for people who already figured that out).

**Comment by kalefranz** [comment]
To transition to conda 4.4, you can probably use something like

    "$([ -n "$_CONDA_EXE" ] && echo "$_CONDA_EXE" || which conda)" info

in shell scripts.

**Comment by kalefranz** [comment]
Marking with the 4.6 milestone to make sure we get `$CONDA_EXE` set properly in all the shell wrappers.

**Comment by mbargull** [comment]
SGTM

**Comment by natefoo** [comment]
@kalefranz `$_CONDA_EXE` isn't exported, so it's not visible to scripts.

**Comment by kalefranz** [comment]
Doh. Right. That was intentional at the time.

**Comment by deejml** [comment]
I am not sure what to do with "-bash: conda: command not found" error. i could not install any new packages. can you please guide the solution/fix if we have any.
i upgraded my conda to latest recently, from then i am getting this error. I am on MacOS.
