### ISSUE TITLE
Can't install gcc_linux-32 nor gcc_impl_linux-32

### ISSUE THREAD

**Issue by giovannirescia** [conda/conda#7129]
Hi all!

I am trying to install two packages `gcc_linux-32` and `gcc_impl_linux-32`, the output I get when I run `anaconda show anaconda/gcc_linux-32` is:

```
Using Anaconda API: https://api.anaconda.org
Name:    gcc_linux-32
Summary: GNU C Compiler
Access:  public
Package Types:  conda
Versions:
   + 7.2.0

To install this package with conda run:
     conda install --channel https://conda.anaconda.org/anaconda gcc_linux-32
```

But when I run `conda install --channel https://conda.anaconda.org/anaconda gcc_linux-32`, I get:

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - gcc_linux-32

Current channels:

  - https://conda.anaconda.org/anaconda/linux-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

And I have the same problem with the other package. I also tried running ` conda install -c anaconda gcc_linux-32 ` which I took from [here](https://anaconda.org/anaconda/gcc_linux-32), but I got the same error.

My conda version is 4.5.0

Thank you!

**Comment by mingwandroid** [comment]
You need to set CONDA_SUBDIR to linux-32 for this to work.

**Comment by giovannirescia** [comment]
Well, what am trying to do is to create an environment with a 32-bit Python version. I followed (this)[https://stackoverflow.com/questions/33709391/using-multiple-python-engines-32bit-64bit-and-2-7-3-5] tutorial and worked on my machine. But I can't get it to work in the server; even after installing the libraries I listed here, the environment is created with a 64-bit Python version. Any idea why that might be?

**Comment by mingwandroid** [comment]
I do not have access to your machine and you have not provided any details as to precisely what goes wrong so I have no idea.

I can state that we do run 32-bit envs on 64-bit computers so it does work given the right environment.

You could remove some variables by running everything as 32-bit (so installing Miniconda x86 instead of x86_64) but that's not strictly necessary.

**Comment by giovannirescia** [comment]
Yes, am running a 32-bit env on my 64-bit desktop computer. The problem is that I can't get to do the same on the server nor other desktop computer, maybe is there some package I should install and am missing? Or, what are the steps to install a 32-bit env on a 64-bit machine other than [this](https://stackoverflow.com/questions/33709391/using-multiple-python-engines-32bit-64bit-and-2-7-3-5) ones that didn't help?
