### ISSUE TITLE
Cannot use command conda

### ISSUE THREAD

**Issue by LuZhangstat** [conda/conda#7130]
**Hi all!**

**I installed anaconda on my mac this afternoon. Then I ran `conda  update -all` in my terminal and got the following error message:**

 Traceback (most recent call last):
  File "/Users/luzhang/anaconda3/lib/python3.6/site-packages/conda/common/path.py", line 18, in <module>
    from urllib.request import url2pathname
  File "/Users/luzhang/anaconda3/lib/python3.6/urllib/request.py", line 2585, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: dlopen(/Users/luzhang/anaconda3/lib/python3.6/lib-dynload/_scproxy.cpython-36m-darwin.so, 2): Symbol not found: _appleblas_i16gemm
  Referenced from: /usr/local/lib/libBNNS.dylib
  Expected in: /usr/local/lib/libBLAS.dylib
 in /usr/local/lib/libBNNS.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/luzhang/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/luzhang/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 125, in main
    from ..exceptions import conda_exception_handler
  File "/Users/luzhang/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/Users/luzhang/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 24, in <module>
    from .path import expand
  File "/Users/luzhang/anaconda3/lib/python3.6/site-packages/conda/common/path.py", line 21, in <module>
    from urllib import unquote, url2pathname  # NOQA
ImportError: cannot import name 'unquote'

**Then I tried `conda info` and got the same error message. Does anyone have any suggestion for me? My system is macOS High Sierra Version 10.13.4.** 

**Thank you very much!**

**Best,**

**Comment by mingwandroid** [comment]
This looks like homebrew is getting in the way. Do you use homebrew? Can
you list the homebrew packages you have installed?

**Comment by LuZhangstat** [comment]
> This looks like homebrew is getting in the way. Do you use homebrew? Can
you list the homebrew packages you have installed?

**Yes, I do use homebrew. Here are the homebrew packages, the list is a little bit long:**

arpack-julia
atk
atkmm
autoconf
automake
bdw-gc
boost
boost-build
cairo
cairomm
clang-omp
cloog
cloog018
cmake
fftw
fontconfig
freetype
gcc
gcc49
gd
gdbm
gdk-pixbuf
gettext
ghostscript
glib
glib-networking
glibmm
gmp
gmp4
gmp@4
gnutls
gobject-introspection
graphite2
graphviz
gsettings-desktop-schemas
gsl
gtk+
gtkmm
harfbuzz
hicolor-icon-theme
icu4c
intltool
isl
isl011
isl@0.11
jpeg
libffi
libgit2
libiomp
libmpc
libmpc08
libmpc@0.8
libpng
libsigc++
libsoup
libssh2
libtasn1
libtiff
libtool
libunistring
little-cms
little-cms2
llvm37-julia
makedepend
mbedtls
mpfr
mpfr2
mpfr@2
nettle
openblas
openblas-julia
openjpeg
openssl
openssl@1.1
p11-kit
pango
pangomm
pcre
pcre2
pixman
pkg-config
poppler
popt
potrace
r
readline
sqlite
suite-sparse-julia
texinfo
vala
webp
wget
xz

**Thank you very much!**

**Comment by kalefranz** [comment]
@mingwandroid anything to do here except for proper base environment activation? Is there something to be fixed with packaging?

**Comment by mingwandroid** [comment]
Don't use homebrew? I expect `DYLD_FALLBACK_LIBRARY_PATH` is in play though.

I will not install homebrew as it's a complete trainwreck (specifically because it puts stuff in `/usr/local` to make their own lives easier).

**Comment by kalefranz** [comment]
@LuZhangstat  Please show us the output of `conda info --all`.

**Comment by LuZhangstat** [comment]
@kalefranz  I got the same error message as I posted in this issue. Here is a screenshot of my terminal:


<img width="1024" alt="screen shot 2018-04-09 at 2 16 18 pm" src="https://user-images.githubusercontent.com/23649581/38523581-d4dba92a-3c00-11e8-8325-3e9a89b440a5.png">

Thanks a lot.

**Comment by LuZhangstat** [comment]
Alright, I rename **/usr/local/lib/libBNNS.dylib**  into  **/usr/local/lib/libBNNScody.dylib**. Now I can use **conda**. Thank you for all your helps.

**Comment by ChiranjeeviBhagavan** [comment]
how to solve this in windows machine !?
