### ISSUE TITLE
using conda with automation

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7132]
From @honnibal  in https://github.com/conda/conda/issues/4274#issuecomment-340230117

> In general I've been having a really hard time using conda with automation.
> 
> * You can't install it via package manager
> * There are tonnes of prompts you have to -y through (plus the non-obvious `-b` in the install script)
> * Ubuntu has dash shell by default, which breaks environment activation
> * Hard to make it work with Fabric
> * No idempotent way to create environments
> 
> It seems like provisioning servers should be an important workflow, but using the tool it feels like not much thought has gone into this?

**Comment by mingwandroid** [comment]
> plus the non-obvious -b in the install script

I have no idea what this means. You can pass --help to see the options.
What more do you suggest?

```
bash ~/Downloads/Miniconda3-4.3.31-MacOSX-x86_64.sh --help

usage: /Users/rdonnelly/Downloads/Miniconda3-4.3.31-MacOSX-x86_64.sh
[options]

Installs Miniconda3 4.3.31

-b           run install in batch mode (without manual intervention),
```

> Ubuntu has dash shell by default, which breaks environment activation

You need to specify exactly which scripts fail and we need to fix them for
posix compliance or explicitly call bash in the shebang.

**Comment by kalefranz** [comment]
@mingwandroid This was about a 6-month-old comment or so. I know it predates the new activate work that’s fully posix she’ll compliant. And it’s possible it predates the constructor work also.

**Comment by mingwandroid** [comment]
Yeah I spotted that but the reporter could be referring to activation
scripts in packages too.
