### ISSUE TITLE
Working across multiple conda environments

### ISSUE THREAD

**Issue by tesujimath** [conda/conda#7154]
**I'm submitting a...**
  - [X] feature request (discussion)

Currently it seems onerous to me to be a consumer of software across multiple conda environments.  Scripts need to activate and deactivate environments.  This is a bother, and worse, ties such scripts to a particular site (and its particular conda environments), when they should be able to run on any site having the required program installed, somewhere.  My basic principle:  don't embed conda environment activation into scripts, as it makes them fragile.

A partial solution has been discussed in #2379.  I find [exec-wrappers](https://github.com/gqmelo/exec-wrappers) to be very useful in this regard.  However, there is still something missing: having easy access to the public (in some sense) programs in a conda environment, without being exposed to all the dependency cruft that gets pulled in.

This is different from stacking multiple environments, #5159, because we don't want users to see the dependencies, just the public programs.

To set the context, I am interested in bioinformatics software, as provided primarily by the [BioConda ](https://bioconda.github.io/) channel.  Commonly, a single application install may pull in many dependencies, at fixed versions.  Different applications may require different versions of these dependencies (dependency hell), which we solve by installing them into separate conda environments.  So far so good.

Ideally a user wants immediate access to all the top-level applications.  Immediate access means, they are on the path.  Exec-wrappers can do this.  However, we need to know exactly which programs should be wrapped into public bin directories.

I have solved this problem with [public-wrappers](https://github.com/tesujimath/public-wrappers), which uses a configuration file to define which programs in which environments are to be wrapped, and uses exec-wrappers to do the wrapping.  See the [example public-wrappers configuration file](https://github.com/tesujimath/public-wrappers/blob/master/doc/example-config.toml), and the [example profile.sh](https://github.com/tesujimath/public-wrappers/blob/master/doc/example-profile.sh) that makes it work nicely.

This functionality seems sufficiently useful to be addressed by the conda project itself.

What do you think?

**Comment by kalefranz** [comment]
related issues:
  * https://github.com/conda/conda/issues/3912
  * https://github.com/conda/conda/issues/7066

**Comment by jakirkham** [comment]
As you mentioned scripts, you may want to look at [`conda-execute`]( https://github.com/conda-tools/conda-execute ). That gives one the option to list dependencies in the script and use transient environments to run the script. Here's a [quick example]( https://github.com/conda-tools/conda-execute#running-a-conda-execute-script-from-the-command-line-without-the-conda-execute-prefix ).
