### ISSUE TITLE
Conda create fails due to wrong package order

### ISSUE THREAD

**Issue by epruesse** [conda/conda#7167]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

`conda create` fails to install file from `conda list --explicit`

In a nutshell, it is trying to compile python code if the python interpreter is not already installed.

### Steps to Reproduce

The effect can be easily reproduced with just two packages, one the python interpreter and the other a python package. Neither may be installed yet, I believe.

```
conda list -n test_env --explicit > specs.txt
# make sure the python interpreter comes after the first python package - this does 
# happen...
conda env remove test_env
conda clean --yes --all
conda create -n test_env --file specs.txt
```

fails with

```
ERROR conda.core.link:_execute(502): An error occurred while installing package[...]
[...]
FileNotFoundError(2, "No such file or directory: $CONDA/envs/test_env/bin/$PYTHON")
[...]
```

What's happening in there is that it is trying to compile a `.pyc`, uses the python interpreter path for the newly installed environment, and then can't find it because it's not yet installed.

## Expected Behavior

The `specs.txt` should be installable without failure or manual editing. I was assuming that the files are listed in order of installation, but that does not appear to be the case. So I suppose something should re-order that list so that the python interpreter (and whatever else is needed before the package can be linked) is installed prior to other packages.

This might actually mean that there is another list of deps... the install deps...

## Envionment

Tested with conda-4.5.0 and conda-4.5.1 and cases using py3 or py2.

**Comment by kalefranz** [comment]
Can you share the actual output of running

    conda list --explicit

?  Basically, is this an issue with the sort order for the output of `conda list --explicit`, or is doing `conda install --file` losing the sort order?

**Comment by epruesse** [comment]
`conda create --file` works off of the exact order, but the order provided by `conda list --explicit` is not correct. `create` does fail if dependencies are missing, so there is some checking going on. But it doesn't order the `python` interpreter package to the top, and fails when it's trying to pre-compile the python code.

**Comment by epruesse** [comment]
I'm having a bit of a hard time reproducing the wrong order in `conda list --explicit` minimally. However, I've got a set of environments, many of which exhibit the issue listing `python` after `python-dateutil`:  [epruesse/ymp_environments](https://github.com/epruesse/ymp_environments/tree/master)

**Comment by kalefranz** [comment]
> many of which

Can you be more precise?
