### ISSUE TITLE
Default repositories are unsafe to install from

### ISSUE THREAD

**Issue by dstufft** [conda/conda#717]
Now that #400 is in the next problem is that conda is by default still unsafe to use to install things from. The default repositories need to be hosted over HTTPS (ideally with good configuration, see https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/) and then conda should default to installing from the HTTPS versions of the repositories.

**Comment by kalefranz** [comment]
Closing.  repo.continuum.io switched to https last November.  Actually https is forced.
