### ISSUE TITLE
[bug report] Cannot update root environment from Python 2 to Python 3

### ISSUE THREAD

**Issue by daravi** [conda/conda#7184]
I am submitting a bug report. [IMO] 

### Steps to Reproduce

Trying to update the current conda root environment from Python 2 to Python 3 results in the following error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34
  - pysocks
  - python=3
```

Trying to remove pysocks or enum34 results in the following error:
```
Preparing transaction: done
Verifying transaction: failed

RemoveError: This operation will remove conda without replacing it with
another version of conda.
```
## Expected Behavior

This means that there is no standard method for me to update from Python 2 to Python 3. Correct behaviour would be to allow for the upgrade by offering the option to remove the conflicting packages.

## Environment Information
<details><summary><code>`conda info`</code></summary><p>

| Variable | Value | 
| --------------- | --------:|
|     active environment | None                                                                 |
|       user config file | /Users/puya/.condarc                                                 |
| populated config files |                                                                      |
|          conda version | 4.5.1                                                                |
|    conda-build version | not installed                                                        |
|         python version | 2.7.14.final.0                                                       |
|       base environment | /usr/local/miniconda3  (writable)                                    |
|           channel URLs | https://repo.anaconda.com/pkgs/main/osx-64<br/>https://repo.anaconda.com/pkgs/main/noarch<br/>https://repo.anaconda.com/pkgs/free/osx-64<br/>https://repo.anaconda.com/pkgs/free/noarch<br/>https://repo.anaconda.com/pkgs/r/osx-64<br/>https://repo.anaconda.com/pkgs/r/noarch<br/>https://repo.anaconda.com/pkgs/pro/osx-64<br/>https://repo.anaconda.com/pkgs/pro/noarch |
|          package cache | /usr/local/miniconda3/pkgs<br/>/Users/puya/.conda/pkgs |
|       envs directories | /usr/local/miniconda3/envs<br/>/Users/puya/.conda/envs |
|               platform | osx-64                                                               |
|             user-agent | conda/4.5.1 requests/2.18.4 CPython/2.7.14 Darwin/17.5.0 OSX/10.13.4 |
|                UID:GID | 501:20                                                               |
|             netrc file | None                                                                 |
|           offline mode | False                                                                |
</p></details>

<details><summary><code>`conda config --show-sources`</code></summary><p>

```
$
```
</p></details>

<details><summary><code>`conda list --show-channel-url`</code></summary><p>

| Name            | Version     | Build         | Channel  |
| --------------- |:----------:| :-------------:| --------:|
| asn1crypto      | 0.24.0     |         py27_0 | defaults |
| ca-certificates | 2018.03.07 |              0 | defaults |
| certifi         | 2018.1.18  |         py27_0 | defaults |
| cffi            | 1.11.5     | py27h342bebf_0 | defaults |
| chardet         | 3.0.4      | py27h2842e91_1 | defaults |
| conda           | 4.5.1      |         py27_0 | defaults |
| conda-env       | 2.6.0      |     h36134e3_0 | defaults |
| cryptography    | 2.2.2      | py27h1de35cc_0 | defaults |
| enum34          | 1.1.6      | py27hf475452_1 | defaults |
| futures         | 3.2.0      | py27h1b80678_0 | defaults |
| idna            | 2.6        | py27hedea723_1 | defaults |
| ipaddress       | 1.0.22     |         py27_0 | defaults |
| libcxx          | 4.0.1      |     h579ed51_0 | defaults |
| libcxxabi       | 4.0.1      |     hebd6815_0 | defaults |
| libedit         | 3.1        |     hb4e282d_0 | defaults |
| libffi          | 3.2.1      |     h475c297_4 | defaults |
| ncurses         | 6.0        |     hd04f020_2 | defaults |
| openssl         | 1.0.2o     |     h26aff7b_0 | defaults |
| pip             | 9.0.3      |         py27_0 | defaults |
| pycosat         | 0.6.3      | py27h6c51c7e_0 | defaults |
| pycparser       | 2.18       | py27h0d28d88_1 | defaults |
| pyopenssl       | 17.5.0     | py27hfda213f_0 | defaults |
| pysocks         | 1.6.8      |         py27_0 | defaults |
| python          | 2.7.14     |    h138c1fe_31 | defaults |
| python.app      | 2          | py27hf2d5e94_7 | defaults |
| readline        | 7.0        |     hc1231fa_4 | defaults |
| requests        | 2.18.4     | py27h9b2b37c_1 | defaults |
| ruamel_yaml     | 0.15.35    | py27h1de35cc_1 | defaults |
| setuptools      | 39.0.1     |         py27_0 | defaults |
| six             | 1.11.0     | py27h7252ba3_1 | defaults |
| sqlite          | 3.22.0     |     h3efe00b_0 | defaults |
| tk              | 8.6.7      |     h35a86e2_3 | defaults |
| urllib3         | 1.22       | py27hc3787e9_0 | defaults |
| virtualenv      | 15.2.0     |         py27_0 | defaults |
| wheel           | 0.31.0     |         py27_0 | defaults |
| xz              | 5.2.3      |     h0278029_2 | defaults |
| yaml            | 0.1.7      |     hc338f04_2 | defaults |
| zlib            | 1.2.11     |     hf3cbc9b_2 | defaults |
</p></details>

**Comment by kalefranz** [comment]
I am able to reproduce, and I also consider this a bug.

```
$ docker run --rm -it continuumio/miniconda2 conda install python=3
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34
  - pysocks
  - python=3
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by kalefranz** [comment]
@trianta2 

> However I don't want to install 2 versions of Python - the root Python version and the exact version of Python I need in another environment.

The way I understand your statement, what you want to achieve is technically impossible.  You want two different versions of python in your container, but you don't want to install two different versions of python?

**Comment by trianta2** [comment]
@kalefranz No, that is not correct. I want the root version of Python to be the exact version of Python I need.

For example, let's say I wanted Anaconda and Python 3.4.3 for a particular application that I wanted to build a Docker image for. Just now I installed a new Miniconda distribution, which gave me Python 3.6.5. I tried to change the root Python version:

```
$ conda env list
# conda environments:
#
base                  *  <basedir>/mini

$ which python
<basedir>/mini/bin/python

$ python --version
Python 3.6.5 :: Anaconda, Inc.

$ conda install python=3.4.3
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.4.3
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> readline=7
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> tk=8.6
Use "conda info <package>" to see the dependencies for each package.
```

Since this is not possible, the alternative solution is to create _another_ Python environment with `python=3.4.3`. This leaves me with 2 versions of Python, one that I don't want (3.6.5) and one that I do want (3.4.3), which is a waste of space.

**Comment by kalefranz** [comment]
Ok, then yes, I think the problems are related.  In your case conda isn't scheduling packages for removal to facilitate the requests rebundling of dependencies you get when downgrading to requests built for python 3.4.

**Comment by kalefranz** [comment]
The block of code that's supposed to be taking care of this here is 

https://github.com/conda/conda/blob/9f3072cbf74aad89a37abc262359763981e2726a/conda/core/solve.py#L346-L360

It's apparently insufficient in this case.
