### ISSUE TITLE
Progress bar changes/issues

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7189]
In `conda` 4.3+ the progress bar looks something like this...

```
pycrypto-2.6.1 100% |################################| Time: 0:00:00   6.79 MB/s
pytz-2018.4-py 100% |################################| Time: 0:00:00   9.22 MB/s
```

...it has a nice tabular view and separates out package name, percentage, time, and download speed. 

In `conda` 4.5+, the progress bar looks like this...

```
ndg-httpsclient 0.4.4################################################### | 100% 
libffi 3.2.1############################################################ | 100%
```

Here the progress bar starts right near where the version ends. Making it a little hard to read. Also this start point varies depending on package name and the like, which is a bit distracting.

Now I'm not sure if this is an intentional change or if I'm running into a bug. Would be great to know either way. If it is an intentional change, would encourage reconsidering.

**Comment by kalefranz** [comment]
I agree that the UI here could be improved.

**Comment by jakirkham** [comment]
Do you know what caused the shift?

**Comment by kalefranz** [comment]
Updating to tqdm, with a different call API.

**Comment by kalefranz** [comment]
Should be good to go with #7191.
