### ISSUE TITLE
-bash: /home/che_pragadeesh/miniconda3/bin/conda: No such file or directory

### ISSUE THREAD

**Issue by biosainik** [conda/conda#7197]
I uninstalled miniconda by removing folder and I removed bashrc hidden files also.

While running conda command, I get the following.
"-bash: /home/che_pragadeesh/miniconda3/bin/conda: No such file or directory"

Please help!

Also, I want to install Anaconda and link conda command to that. Even I tried installing Anaconda. But Conda command roots to miniconda.

BTW, I am a beginner.

**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by surya-narayanan** [comment]
HI! How did you solve this?
