### ISSUE TITLE
Conda HTTP error 

### ISSUE THREAD

**Issue by suraty** [conda/conda#7199]
Hello,
My OS is ubuntu14.04 64-bit and Anaconda is installed on it.
When I try the command:

>  conda update -n base conda

There are some errors:
<i>CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/my_channel/noarch/repodata.json>
Elapsed: 00:00.539858
CF-RAY: 40ef65d0fbc36505-FRA

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/my_channel

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
</i>
When I enter the command:

> conda config --show channels

The output is:
<i>
channels:
  - my_channel
  - conda-canary
  - defaults
</i>
Now, How can I solve this problem? I am a beginner, how should I make the norch directory?
Thank you so much

**Comment by kalefranz** [comment]
`my_channel` is not a valid conda channel.  Remove it from your channels list.
