### ISSUE TITLE
mistake install seaborn

### ISSUE THREAD

**Issue by alexponom** [conda/conda#7201]
An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at: https://github.com/conda/conda/issues Include the output of the command 'conda info' in your report. Traceback (most recent call last): File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\main.py", line 130, in args_func File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\main_install.py", line 69, in execute File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\install.py", line 407, in install File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\plan.py", line 600, in execute_actions File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\instructions.py", line 136, in execute_instructions File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\instructions.py", line 79, in LINK_CMD File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\install.py", line 1087, in link File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\install.py", line 545, in run_script File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\subprocess.py", line 576, in check_call retcode = call(*popenargs, **kwargs) File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\subprocess.py", line 557, in call with Popen(*popenargs, **kwargs) as p: File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\subprocess.py", line 947, in __init__ restore_signals, start_new_session) File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\subprocess.py", line 1224, in _execute_child startupinfo) FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by kalefranz** [comment]
Issue template not used.
