### ISSUE TITLE
lxml does not build inside a conda environment

### ISSUE THREAD

**Issue by srossross** [conda/conda#721]
```
gcc -bundle -undefined dynamic_lookup -L/Users/sean/anaconda/envs/binstar/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -L/Users/sean/anaconda/lib -L/Users/sean/anaconda/envs/binstar/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.5-x86_64-2.7/lxml/etree.so

ld: mach-o string pool extends beyond end of file in /Users/sean/anaconda/lib/libxslt.dylib file '/Users/sean/anaconda/lib/libxslt.dylib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/sean/anaconda/envs/binstar/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip_build_sean/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip-monM6u-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip_build_sean/lxml

```

See also: https://github.com/astropy/astroquery/issues/278

**Comment by baisk** [comment]
I failed too. I ues virtualenv in a clean environment and do pip install lxml.

cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Users/gaowei/anaconda/include -I/Users/gaowei/anaconda/include/libxml2 -I/Users/gaowei/Dreamer/scrapy/.venv/build/lxml/src/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.9-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace

cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.9-intel-2.7/src/lxml/lxml.etree.o -L/Users/gaowei/anaconda/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.9-intel-2.7/lxml/etree.so

ld: mach-o string pool extends beyond end of file in /Users/gaowei/anaconda/lib/libxslt.dylib file '/Users/gaowei/anaconda/lib/libxslt.dylib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'cc' failed with exit status 1

**Comment by toasteez** [comment]
When installing pandasdmx it trys to install lxml and regardless of whether it is there the following error happend.   I have latest conda and anaconda.

----- Installing 'pandasdmx' -----
Collecting pandasdmx
  Using cached pandaSDMX-0.2.2-py2.py3-none-any.whl
Collecting lxml (from pandasdmx)
  Downloading lxml-3.4.4-cp27-none-win_amd64.whl (3.3MB)
Requirement already up-to-date: pandas in c:\anaconda\lib\site-packages (from pandasdmx)
Requirement already up-to-date: requests in c:\anaconda\lib\site-packages (from pandasdmx)
Requirement already up-to-date: python-dateutil in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: pytz>=2011k in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: numpy>=1.7.0 in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil->pandas->pandasdmx)
Installing collected packages: lxml, pandasdmx
Exception:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Anaconda\lib\site-packages\pip\commands\install.py", line 299, in run
    root=options.root_path,
  File "C:\Anaconda\lib\site-packages\pip\req\req_set.py", line 646, in install
    **kwargs
  File "C:\Anaconda\lib\site-packages\pip\req\req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Anaconda\lib\site-packages\pip\req\req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "C:\Anaconda\lib\site-packages\pip\wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Anaconda\lib\site-packages\pip\wheel.py", line 299, in clobber
    assert not info_dir, 'Multiple .dist-info directories'
AssertionError: Multiple .dist-info directories
----- Failed to install 'pandasdmx' -----

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1998
