### ISSUE TITLE
conda installation outside home

### ISSUE THREAD

**Issue by khawar85** [conda/conda#7214]
Dear Support. 

Good Morning. I am in serious trouble. As I am in institute and I have home only 5GB. I have to install anaconda outside home. 

when I try this. and give path like 
command is here below
[/khawar/anaconda_installed]$> ./Anaconda3-5.1.0-Linux-x86_64.sh -u /khawar/anaconda_installed

and after it reads terms and conditions.. it says like this.

[/khawar/anaconda_installed/] >>> 
mkdir: cannot create directory ‘/h’: Permission denied
ERROR: Could not create directory: '/khawar/anaconda_installed/'
ahmedk@lts002hpc [5] [/khawar/anaconda_installed]

/hive is the entering point of scratch. /h/./././khawar/anadonda_installed/
here not given full path
while in this folder, I have permission to create write and delete everything. It is scratch space for me like disk space. 

Please if you can help me and provide solution. 

I am struggling since a month almost. 

Looking forward

Regards

Khawar

**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by khawar85** [comment]
Resolved .. lets see if something happens again I will ask request. Thank you .. !! Great team,//

**Comment by mingwandroid** [comment]
> As I am in institute and I have home only 5GB

You might want to use Miniconda instead. It's much smaller but you can still install exactly what you need using it.

**Comment by khawar85** [comment]
Dear Sir, 

I tried miniconda as well. I am facing same trouble. 
As I cannot handle in user. Please help me to install in some other spacel.  like /scratch/any_hard/any_folder/

Please 

Greetings

**Comment by kalefranz** [comment]
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -bfp /scratch/any_hard/any_folder/

**Comment by khawar85** [comment]
Thank you so much. Still there is error like 
bash Miniconda3-latest-Linux-x86_64.sh -bfp /scratch/any_hard/any_folder/
installing: python-3.6.4-hc3d631a_1 ...
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.6.4 :: Anaconda, Inc.

and at the end.. it cannot handle that to install completely.

**Comment by kalefranz** [comment]
Are you on a Linux x86-64 system?  What is the kernel version?
