### ISSUE TITLE
Package details of an Anaconda Release

### ISSUE THREAD

**Issue by The-Gupta** [conda/conda#7215]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by The-Gupta** [comment]
Is there a way to know python version or that of any other library in an Anaconda release (at https://repo.continuum.io/archive/) before installing it?

**Comment by The-Gupta** [comment]
Found release notes - https://docs.anaconda.com/anaconda/release-notes
They are fairly good. 
But, not for all releases, Python versions are specified. It's like 2.7.13-14.
Can I get more specific documentation?

**Comment by mbargull** [comment]
The Anaconda Installer mostly consists of the `anaconda` package for which you can show information with `conda search --info anaconda`.
Regardless, this is the issue tracker for the `conda` package manager, i.e., the program itself. If you have questions regarding Anaconda, please file them at https://github.com/ContinuumIO/anaconda-issues.
