### ISSUE TITLE
`create` should have opposite command `destroy`

### ISSUE THREAD

**Issue by srossross** [conda/conda#723]
For automated tasks conda should be able to destroy an environment

**Comment by jpellman** [comment]
What about `conda constrict` or `conda digest`?

**Comment by FvD** [comment]
Given the combination of "environment" and member of the boidae (anaconda) I have set my aliases to move around "habitats" (places the where these snakes live)

I list the habitats where I could go and move into with:

    $ habitats
      my-env

I take my (temporary) dwelling in a habitat:

    $ inhabit my-env
    (my-env) $

And I migrate away when the conditions demand:

    (my-env) $ migrate 
     discarding /home/user/anaconda/envs/my-env/bin from PATH
    $

Following on that word play, I suggest a short version to impose "habitat loss" on the available environments: 

    $ lose my-env

**Comment by jlas** [comment]
`conda remove-env <envname>` or `delete-env` seems like the most straightforward command, this would probably just be an alias for `conda remove --all -n <envname>`

**Comment by hale** [comment]
The existing command is `condo remove --all -n envname` - an alias of `conda remove envname` therefore seems the least objectionable.  Who's decision is this? It would be nice to have something easier to remember.

**Comment by bkreider** [comment]
+1 for destroy.  It's a nice antonym to create and it matches Anaconda Cluster's create/destroy nicely.

**Comment by maphew** [comment]
There could also be `conda envs` or `conda list --envs` or ...

Here instead of a separate issue because to my mind this all (create, list, destroy) comes under the single heading "Env Management"

**Comment by ihnorton** [comment]
`conda create xyz` can do this =on its own when you run it inside an active environment. Yes, there is a warning prompt, but still the behavior seems ... undesirable, to say the least. (`conda 4.6.11`)

**Comment by ptoche** [comment]
Sorry to be a bore, but `conda lose <env>` is not strong enough, as lost things can sometimes be found again. While there is the possibly appropriate `conda serpenticide <env>`, I agree with many here that `conda destroy <env>` is the best, as it helps the user realize the operation is rather drastic.
