### ISSUE TITLE
Unexpected Error has Occurred: conda install -c conda-forge gdal=2.1.3

### ISSUE THREAD

**Issue by evanburgess** [conda/conda#7232]
I am submitting a an error message and traceback received after trying to install a specific version of gdal: `conda install -c conda-forge gdal=2.1.3`  I have pasted my entire environment to try to replicate it.  This has occurred on Ubuntu 16.04.1.

`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:`

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda2  (read only)
    default environment : /home/ubuntu/.conda/envs/twb2
       envs directories : /home/ubuntu/.conda/envs
                          /opt/anaconda2/envs
          package cache : /home/ubuntu/.conda/envs/.pkgs
                          /opt/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-121-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/ubuntu/.conda/envs/twb2/bin/conda install -c conda-forge gdal=2.1.3`

    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.`

Here is my current environment:
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/affine-2.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/backports-1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/backports_abc-0.5-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bleach-1.5.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bokeh-0.12.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/boto-2.45.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bottleneck-1.2.1-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cairo-1.14.8-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/chest-0.2.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/click-6.7-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/click-plugins-1.0.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cligj-0.4.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cloudpickle-0.2.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/configparser-3.5.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/curl-7.49.0-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cycler-0.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cython-0.26-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/dask-0.14.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/datashader-0.4.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/datashape-0.5.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/dbus-1.10.10-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/decorator-4.0.11-py27_0.tar.bz2
https://conda.anaconda.org/ioos/linux-64/descartes-1.0.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dicttoxml-1.7.4-py27_0.tar.bz2
https://conda.anaconda.org/diffpy/linux-64/diffpy.pdffit2-1.1-py27_0.tar.bz2
https://conda.anaconda.org/diffpy/linux-64/diffpy.pdfgui-1.1.2-py27_2.tar.bz2
https://conda.anaconda.org/diffpy/linux-64/diffpy.structure-1.3.5-py27_0.tar.bz2
https://conda.anaconda.org/diffpy/linux-64/diffpy.utils-1.2.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/entrypoints-0.2.2-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/enum34-1.1.6-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/expat-2.1.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/fiona-1.7.0-py27_0.tar.bz2
https://conda.anaconda.org/ccordoba12/linux-64/flann-1.8.4-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/fontconfig-2.12.1-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/freeglut-2.8.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/freetype-2.5.5-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/funcsigs-1.0.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/functools32-3.2.3.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/futures-3.1.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/gdal-2.1.0-py27_0.tar.bz2
https://conda.anaconda.org/ioos/linux-64/geopandas-0.2.1-py27_0.tar.bz2
https://conda.anaconda.org/ioos/linux-64/geopy-1.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/geos-3.5.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/geotiff-1.4.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/get_terminal_size-1.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/glib-2.50.2-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/gst-plugins-base-1.8.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/gstreamer-1.8.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/h5py-2.6.0-np111py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/harfbuzz-0.9.39-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/hdf4-4.2.12-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/hdf5-1.8.17-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/heapdict-1.0.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/html5lib-0.999-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/icu-54.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipdb-0.10.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipykernel-4.6.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipyparallel-6.0.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython-5.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython_genutils-0.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipywidgets-6.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jbig-2.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jinja2-2.9.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jpeg-8d-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jsonschema-2.6.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter-1.0.0-py27_3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_client-5.0.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_console-5.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_core-4.3.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/kealib-1.4.6-0.tar.bz2
https://conda.anaconda.org/Friend/linux-64/laspy-1.4.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libffi-3.2.1-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgdal-2.1.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libiconv-1.14-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libnetcdf-4.4.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libpng-1.6.27-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libpq-9.5.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libsodium-1.0.10-0.tar.bz2
https://conda.anaconda.org/ioos/linux-64/libspatialindex-1.8.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libtiff-4.0.6-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxcb-1.12-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxml2-2.9.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/llvm-3.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/llvmlite-0.18.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/locket-0.2.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markupsafe-0.23-py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/matplotlib-1.5.1-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mistune-0.7.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-2017.0.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/multipledispatch-0.4.9-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/munch-2.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nbconvert-5.1.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nbformat-4.3.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/networkx-1.11-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/notebook-5.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numba-0.33.0-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numexpr-2.6.2-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numpy-1.11.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/odo-0.5.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2k-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/packaging-16.8-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pandas-0.19.2-np111py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pandocfilters-1.4.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pango-1.40.3-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/partd-0.3.8-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/path.py-10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pathlib2-2.2.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/patsy-0.4.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pcre-8.39-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pexpect-4.2.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pickleshare-0.7.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pillow-3.4.2-py27_0.tar.bz2
https://conda.anaconda.org/unidata/linux-64/pint-0.6-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-9.0.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pixman-0.34.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/proj4-4.9.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/prompt_toolkit-1.0.9-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/psycopg2-2.6.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ptyprocess-0.5.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycairo-1.10.0-py27_0.tar.bz2
https://conda.anaconda.org/diffpy/linux-64/pycifrw-4.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pygments-2.1.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyopengl-3.1.1a1-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyparsing-2.1.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyproj-1.9.5.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyqt-4.11.4-py27_4.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pysal-1.12.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pytables-3.3.0-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-2.7.13-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-dateutil-2.6.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pytz-2016.10-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyyaml-3.12-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyzmq-16.0.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qt-4.8.7-4.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qtconsole-4.2.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/rasterio-0.36.0-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/requests-2.14.2-py27_0.tar.bz2
https://conda.anaconda.org/ioos/linux-64/rtree-0.8.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scandir-1.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scikit-image-0.12.3-np111py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scikit-learn-0.18.1-np111py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scipy-0.18.1-np111py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/seaborn-0.8-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/shapely-1.5.16-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/simplegeneric-0.8.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/singledispatch-3.4.0.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sip-4.18-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/six-1.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/snuggs-1.4.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlalchemy-1.1.5-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ssl_match_hostname-3.4.0.2-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/statsmodels-0.8.0-np111py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/subprocess32-3.2.7-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/system-5.8-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/terminado-0.6-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/testpath-0.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/toolz-0.8.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tornado-4.5.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/traitlets-4.3.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wcwidth-0.1.7-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wheel-0.29.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/widgetsnbextension-2.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wxpython-3.0.0.0-py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xarray-0.8.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xerces-c-3.1.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.2.2-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/yaml-0.1.6-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zeromq-4.1.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-3.tar.bz2`

**Comment by kalefranz** [comment]
conda update conda
