### ISSUE TITLE
conda env create doesn't respect order of channels in environment.yaml

### ISSUE THREAD

**Issue by cjw296** [conda/conda#7238]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

`conda env create --file environment.yaml` does not respect the order of channels in the `channels` section of the `environment.yaml` file.

### Steps to Reproduce

- create an environment that uses a number of channels, make sure they are in the order of precedence you require (there's three in my case).

- `conda env export > environment.yaml`

- deactivate the environment

- `conda env create --force --file environment.yaml`

- `conda env export | grep -A 5 channel` and you'll see the channel order may not be the same as in your source `environment.yaml`.

## Expected Behavior

The channel order should be preserved

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/chris/.condarc
 populated config files : /Users/chris/.condarc
          conda version : 4.5.1
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /Users/chris/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/chris/miniconda3/pkgs
                          /Users/chris/.conda/pkgs
       envs directories : /Users/chris/miniconda3/envs
                          /Users/chris/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.3 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</p></details>

**Comment by cjw296** [comment]
See #6152...

**Comment by cjw296** [comment]
Also #7248 for the "unify all the environment types" problem.

**Comment by analog-cbarber** [comment]
I think that `conda env export` is just groveling channels from the packages, so there is no inherent order. 

Really, `conda env create` should save the channels in the environment's .condarc, which is ordered, at least as an option.

**Comment by dwr-psandhu** [comment]
This is why i recommend not using environment.yml. The alternate that always works is to do something like 
```
conda create -n myenv -c my_channel -c defaults -c conda-forge pkg_x pkg_y
```

**Comment by davidrpugh** [comment]
@dwr-psandhu sounds like the issue is with the `conda env export` command. 

I have been creating Conda environments from environment files that I create by hand for years and never had one fail to respect channel priority. My environment files always use at least 2 and usually 3 or 4 channels.

**Comment by dwr-psandhu** [comment]
@davidrpugh Confirmed. This worked on both windows and linux with channel priorities being respected. I think the issue is with binder-hub switching to mamba. I don't use mamba so cannot confirm.

**Comment by cjw296** [comment]
@davidrpugh - indeed, which is why I think https://github.com/conda/conda/issues/7248 is probably the right place to focus. The "several different ways to do any one thing" problem that conda currently has is a magnet for these kinds of problems.

**Comment by cjw296** [comment]
Related: https://github.com/conda/conda/issues/10684

**Comment by wimglenn** [comment]
https://github.com/conda/conda/blob/4.12.0/conda_env/env.py#L86  :laughing:

**Comment by cjw296** [comment]
> https://github.com/conda/conda/blob/4.12.0/conda_env/env.py#L86 😆

...from 7 years ago 😭

**Comment by chebee7i** [comment]
Any plan to fix this?  We can continue coding up our solutions to this I guess...

**Comment by jabowery** [comment]
> @davidrpugh - indeed, which is why I think #7248 is probably the right place to focus. The "several different ways to do any one thing" problem that conda currently has is a magnet for these kinds of problems.

#7248 is the reverse of the OP issue here in terms of solver functionality.  The "several ways" issue here is really just a "several syntaxes" issue, so there should be one meta-syntax used to specify the syntaxes and then a canonical syntax chosen as the target for delivery to the environment solver. 

As for #7248 -- that's a much more difficult problem to solve correctly as it essentially entails decompilation -- going from solution to the minimum description complexity of the specification of the problem.  It's doable, certainly, and it should be done, certainly, but it is hard.
