### ISSUE TITLE
Use uJSON instead of JSON for conda

### ISSUE THREAD

**Issue by lucventurini** [conda/conda#7272]
**I'm submitting a...**
  - [ ] bug report
  - [X] feature request

## Current Behavior

Conda can be very slow when loading the information for the current environment, or installing new packages.

### Steps to Reproduce

```

```

## Expected Behavior

I would expect Conda to load the required information much more quickly - pip is a good benchmark. UJSON should help Conda make part of this step quicker, by cutting down the times needed to load json serialisation files.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/luca/.condarc
 populated config files : /home/luca/.condarc
          conda version : 4.5.3
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /home/luca/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
          package cache : /home/luca/miniconda3/pkgs
                          /home/luca/.conda/pkgs
       envs directories : /home/luca/miniconda3/envs
                          /home/luca/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.5 Linux/4.10.0-38-generic linuxmint/18.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/luca/.condarc <==
pinned_packages:
  - r-base >=3.4
ssl_verify: True
channels:
  - bioconda
  - conda-forge
  - defaults
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/luca/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
conda                     4.5.3                    py36_0    conda-forge
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.2.2            py36h14c3975_0    defaults
idna                      2.6              py36h82fb2a8_1    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
ncurses                   6.0                  h9df7e31_2    defaults
openssl                   1.0.2o                        0    conda-forge
pip                       9.0.3                    py36_0    defaults
pip                       10.0.1                    <pip>
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.5                hc3d631a_0    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.15.35          py36h14c3975_1    defaults
setuptools                39.0.1                   py36_0    defaults
six                       1.11.0           py36h372c433_1    defaults
sqlite                    3.23.1               he433501_0    defaults
tk                        8.6.7                hc745277_3    defaults
ujson                     1.35                      <pip>
urllib3                   1.22             py36hbe7ace6_0    defaults
wheel                     0.31.0                   py36_0    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults

```
</p></details>

**Comment by lucventurini** [comment]
To be more specific; every time, in Conda python libraries, there is a 
``import python``
substituting it with 
``try:
    import ujson as json
except ImportError:
    import json``

will make the code robust, and will allow to install ujson separately. I would recommend, though, using it as the default solution.

**Comment by mingwandroid** [comment]
`import python`?

**Comment by lucventurini** [comment]
Apologies @mingwandroid , I corrected the code snippet above!

**Comment by kalefranz** [comment]
Probably not a bad idea. Would like to assure ourselves with benchmarks first though.

**Comment by mbargull** [comment]
There are quite some places where `conda` (or `auxlib`) uses custom encoder/decoder classes. So a trivial "replace `json` by `ujson`" won't be possible.
Using those custom encoders/decoders might slow down the parsing/serialization in general in comparison to plain `json.load`/`json.dump` invocations. Assessing that performance impact would require a little more extensive investigation.
We get a far less elaborate/wholesome benchmark if we just look at the biggest JSON file `conda` is likely to process, i.e., `repodata.json` from conda-forge, and disregard the custom entity decoding:
```
$ curl --compressed -sLO https://conda.anaconda.org/conda-forge/linux-64/repodata.json
$ python -c '
> from timeit import repeat
> import json
> import ujson
> import rapidjson
> 
> with open("repodata.json", "rt") as f:
>     data = f.read()
> 
> def load_json(json_module):
>     json_module.loads(data)
> 
> for json_module in (json, ujson, rapidjson):
>     print("{:<10}".format(json_module.__name__), *map("{:5.3f}".format, sorted(repeat(lambda: load_json(json_module), number=1, repeat=20))))
> '
json       0.181 0.181 0.181 0.181 0.182 0.182 0.182 0.182 0.183 0.183 0.184 0.184 0.184 0.185 0.185 0.186 0.186 0.186 0.191 0.196
ujson      0.188 0.189 0.189 0.189 0.189 0.190 0.190 0.190 0.190 0.190 0.190 0.190 0.191 0.191 0.191 0.191 0.192 0.193 0.198 0.198
rapidjson  0.191 0.191 0.191 0.191 0.192 0.192 0.192 0.192 0.192 0.192 0.192 0.192 0.192 0.192 0.192 0.193 0.193 0.194 0.197 0.198
$ python -c '
> from timeit import repeat
> from io import BytesIO
> import json
> import ujson
> import rapidjson
> 
> with open("repodata.json", "rb") as f:
>     data = BytesIO(f.read())
> 
> def load_json(json_module):
>     data.seek(0)
>     json_module.load(data)
> 
> for json_module in (json, ujson, rapidjson):
>     print("{:<10}".format(json_module.__name__), *map("{:5.3f}".format, sorted(repeat(lambda: load_json(json_module), number=1, repeat=20))))
> '
json       0.179 0.179 0.180 0.180 0.180 0.181 0.181 0.183 0.183 0.183 0.183 0.184 0.185 0.185 0.185 0.185 0.189 0.190 0.198 0.204
ujson      0.179 0.179 0.179 0.179 0.180 0.180 0.180 0.181 0.181 0.181 0.181 0.182 0.182 0.182 0.183 0.184 0.185 0.186 0.186 0.196
rapidjson  0.236 0.253 0.254 0.254 0.254 0.255 0.255 0.255 0.256 0.256 0.256 0.256 0.257 0.257 0.257 0.258 0.259 0.259 0.262 0.271
```
¯\\\_(ツ)\_/¯

**Comment by kalefranz** [comment]
Somehow I feel like I've done something like this before and came to the same conclusion 🤔

**Comment by mingwandroid** [comment]
I reckon allocation of python objects will dwarf any potential speedup given our records are all so tiny.

**Comment by mbargull** [comment]
>  given our records are all so tiny.

Oh right, that makes very much sense.

@lucventurini, thanks for the suggestion, but IMHO it's very unlikely we'd see any noticeable speedup by changing the JSON library.
Although, you might be interested in that @kalefranz made some nice improvements for `conda 4.6.x` regarding the package index/records handling. Those caused some *very noticeable* speedups; see, e.g., https://github.com/conda/conda/issues/7239#issuecomment-387632154.

**Comment by lucventurini** [comment]
Dear all, thank you for dedicating attention to my suggestion and for pointing me at @kalefranz new modifications. I am installing them now and I hope that they will help with my usercase!

Looking at the other issue (#7239) I think that my problem is that I make use of bioconda, which in turn requires conda-forge. Solving the conda-forge environment requires a lot of work, and I constantly see times of two to five minutes for a simple conda install.

I will be trying the new master branch and see whether it helps.

Kind regards

**Comment by mbargull** [comment]
>Solving the conda-forge environment requires a lot of work, and I constantly see times of two to five minutes for a simple conda install.
>
>I will be trying the new master branch and see whether it helps.

The repository index parsing is something that only takes at most a few seconds. The "two to five minutes" you are seeing is time spent by the dependency solver. In almost all cases this happens because R packages are involved in dependency resolution. There are many duplicates between the `defaults` and `conda-forge` channels for those packages. Additionally, those packages have many builds (for different R versions). If you constrain the version of the `r-base` package, you might get better results. See https://github.com/conda/conda/issues/5536#issuecomment-386935346 for more information.

**Comment by kalefranz** [comment]
> see times of two to five minutes for a simple conda install

I think where “the line” is on performance is very subjective. But five minutes crosses the line for me.

I’m not sure if a more performant SAT implementation will be sufficient. We might have to come up with more creative ways of reducing the universe if packages that we feed into the SAT algorithm.

**Comment by kalefranz** [comment]
I'm going to go ahead an close this issue for now, pending more evidence that ujson would actually give us a performance improvement.
