### ISSUE TITLE
Installing (Ana/Mini)conda

### ISSUE THREAD

**Issue by tasuki** [conda/conda#7277]
This is gonna be somewhat personal and ranty, consider yourself warned.

I'm going through the fast.ai course, and they use conda for managing dependencies. Yet another dependency manager, hooray. As is pip wasn't good enough. Perhaps it's gonna be really good though?

"Package, dependency and environment management for any language" - well that sounds awesome. How do I get started? Well, first I need to choose whether I want Anaconda or Miniconda. How would I know?

So I look at both Anaconda and Miniconda to compare which one is going to be more pleasant to install under my particular Debian-based Linux distro. Unfortunately, the answer here is: *neither*. "**Download a mysterious shell script and run it**" is the official way to install both Anaconda and Miniconda. I forgive those who don't know any better. But you good people are supposed to be "package, dependency, and environment management" experts. And you want me to install your nice package by running a shell script? Are you out of your mind?

**Comment by mingwandroid** [comment]
What are you prepared to download and run exactly?

**Comment by tasuki** [comment]
In order of my personal preference:
1. Official repositories of my distro (ok, that one is outside of your control)
2. Your custom Debian repository (that's what eg Docker or Steam do iirc)
3. Downloadable `.deb` file
4. Pip or easy install
5. Install through other package managers I have installed already
6. Mysterious downloadable shell script

It seems to me you do not understand why I dislike the "mysterious shell script" installation. So:
1. it's not obvious what gets installed where, which files your installation script is going to touch etc
2. it's not obvious how I'm going to get security updates and whatever other updates
3. it's not obvious how to remove Conda should I not like it

**Comment by tasuki** [comment]
Perhaps I shouldn't have lashed out like this. Attempting to install Conda made me confused and scared.

The things that made me confused and scared:
1. All the stuff mentioned above: Conda - while being a package management tool - does not use package management.
2. How do I choose whether to install Miniconda or Anaconda?
3. Let's say I (randomly) chose Miniconda. Next, should I choose `Python 2.7` or `Python 3.6`? Why should I care? What are the implications of choosing one or the other?
3. "These Miniconda installers contain the conda package manager and Python" - my operating system has already provided me with a perfectly working Python. Several of them, in fact (2.7 and 3.5). Will this interfere with the Pythons I already have installed? If so, how? If not, how should I know that and why do I need your Pythons?

**Comment by msarahan** [comment]
Debian packages for installers are on our roadmap for Q3/Q4 this year.  For the time being, if you'd like to give yourself some peace of mind, I recommend running the "mysterious shell script" in a docker container or VM, observing the changes it makes, and judge for yourself if we're doing anything naughty.  You're also free to manage your packages in any other way that you've mentioned.  If you can't manage that, then I'm sorry, your only option is to use our "mysterious shell script" or find something else to do with your time than this fast.ai course.  Good luck.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/issues/1235#issuecomment-368176789

**Comment by mbargull** [comment]
> Let's say I (randomly) chose Miniconda. Next, should I choose Python 2.7 or Python 3.6? Why should I care? What are the implications of choosing one or the other?

IMO, best practice is to always choose `Miniconda3`, i.e., the Python 3 version, and install any other packages into a separate environment (or, depending on your needs, multiple ones), e.g., instead of `conda install that-package-you-want` run `conda create --name environment-name-of-your-choosing that-package-you-want`.

> "These Miniconda installers contain the conda package manager and Python" - my operating system has already provided me with a perfectly working Python. Several of them, in fact (2.7 and 3.5). Will this interfere with the Pythons I already have installed? If so, how? If not, how should I know that and why do I need your Pythons?

I highly suggest you to read the documentation at https://conda.io/docs/ and/or other resources explaining the intention of and usage of Conda.

**Comment by Skeen** [comment]
Having these shell script installers are fine as a fallback for unknown or non supported systems, but as the only solution, it currently forces a lot of people to manually go through the script and check it.
- I quite frankly don't buy the 'start a container and observe it' argument, how can I be sure the script doesn't just check `/proc/1/cgroup` to see if it's running inside a docker container, or similar?

The only way I can know for sure, is reading the entire shell script before I'm convinced I feel confident in running it on anything remotely critical. I am in no way arguing malicious intent on the side of the project, I'm rather arguing vigilance.
