### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pk gs/r/win-64/repodata.json.bz2>

### ISSUE THREAD

**Issue by rahul-raj** [conda/conda#7283]
I need to install tensorflow and hence I was trying to add up environment first. But I get HTTP Connection Failed error. I'm behind a corporate proxy and already defined them well in .condarc file. Here is the error I'm getting:

`C:\Users\Rahul\Downloads>conda create -n tensorflow python=3.6 anaconda`
`Solving environment: failed`

`CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pk`
`gs/r/win-64/repodata.json.bz2>`
`Elapsed: -`

`An HTTP error occurred when trying to retrieve this URL.`
`HTTP errors are often intermittent, and a simple retry will get you on your way.`

`ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', por`
`t=443): Max retries exceeded with url: /pkgs/r/win-64/repodata.json.bz2 (Caused`
`by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0`
`000001A00393C88>: Failed to establish a new connection: [Errno 11002] getaddrinf`
`o failed',))",),)`

I researched for this issue in other github issue trackers, but no luck with them all.  Here is the existing conda config list, adding here if that helps:

`C:\Users\Rahul\Downloads>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io
  pkgs/free: https://repo.continuum.io
  pkgs/r: https://repo.continuum.io
  pkgs/pro: https://repo.continuum.io
  pkgs/msys2: https://repo.continuum.io
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/p
kgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/p
ro", "https://repo.continuum.io/pkgs/msys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
download_only: False
envs_dirs:
  - C:\Users\Rahul\AppData\Local\Continuum\anaconda3\envs
  - C:\Users\Rahul\AppData\Local\conda\conda\envs
  - C:\Users\Rahul\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - C:\Users\Rahul\AppData\Local\Continuum\anaconda3\pkgs
  - C:\Users\Rahul\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: False
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []`

In most of the issue trackers, solution is referred to as "changing .condarc file". I did that and placed in my home directory. But I'm still getting the issue. I have even tried disabling the ssl config but that didnt help either. As per the github issue trackers, there are lot of people who faces this issue, but no resolution found with proper steps. I'm running Windows 8 System & the URL: [**https://repo.continuum.io/pk gs/r/win-64/repodata.json.bz2**](url) is loading perfectly on browser. 
None of the commands like `conda install` or `conda update` works too, all throwing the same error. I'm confused since my proxy settings are correct, but still getting this issue.  

As per my observation, it is clearly an anaconda issue rather than the corproate proxy I'm connected to.

Appreciate if someone could advice on this.

**Comment by rahul-raj** [comment]
Apparently figured out where exactly going wrong. I will update once the tasks are done.

**Comment by rahul-raj** [comment]
Apparently, the condarc file was updated and rewritten as an empty file while I ran config command. I tried running proxy settings and trusted host through command line, but it doesnt work. But then found that invoking trusted host through command line is discontinued and so I added the same in pip.ini file. After that it worked!

**Comment by stalhaa** [comment]
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/win-64/h5py-2.9.0-py36h5e291fa_0.tar.bz2>
Elapsed:  

I am getting this error while installing tensorflow module from conda prompt
@rahul-raj  plz tell how to resolve this issue??

**Comment by rahul-raj** [comment]
Go through the comments posted above as well as here:
https://stackoverflow.com/questions/50305725/condahttperror-http-000-connection-failed-for-url-https-repo-continuum-io-pk

**Comment by stalhaa** [comment]
i am unable  to find pip.ini file on my windows..

**Comment by rahul-raj** [comment]
That's bit off-topic. You need to do some Google
https://stackoverflow.com/questions/28278207/python-cant-find-pip-ini-or-pip-conf-in-windows
