### ISSUE TITLE
Request for adding support for specifying channel to conda info

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#7285]
**I'm submitting a...**
  - [ ] bug report
  - [X] feature request

Feature request to support specifying channel to `conda info`

**Comment by kalefranz** [comment]
What do you mean?

**Comment by kalefranz** [comment]
Oh, do you mean `conda info package_name`?  We're deprecating that.  Use `conda search`.

    conda search -c conda-forge python --info

or

        conda search conda-forge::python --info

**Comment by nehaljwani** [comment]
Closing, as the recommended was suffices my needs.
