### ISSUE TITLE
Cannot run conda after installing others

### ISSUE THREAD

**Issue by shangruli** [conda/conda#7293]
Hi, all.

I installed Anaconda before and when I opened python in terminal, it was automatically using the one with Anaconda.

Yesterday I was trying to install YouCompleteMe for my vim but failed. I tried many solutions online but none worked. After blindly installing lots of things, I found that I cannot use conda in my terminal. The python path was changed to somewhere else (should be MacVim). 

How can I make it back to Anaconda? I tried to reinstall but it failed because I already have one installed. Here are some codes and .profile.

Thanks

`$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MacVim.app/Contents/bin
`
```
# MacPorts Installer addition on 2018-03-21_at_01:52:10: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# Setting PATH for Python 3.6
# The original version is saved in .profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# Setting PATH for Python 3.6
# The original version is saved in .profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# added by Anaconda3 5.1.0 installer
export PATH="/anaconda3/bin:$PATH"

# Setting PATH for Python 3.6
# The original version is saved in .profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
```

**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by niranjanreddy891** [comment]
@shangruli, please post the same issue in `YouCompleteMe`. This error seems related to it. :)

**Comment by mbargull** [comment]
The last lines of `.profile` show
```sh
# added by Anaconda3 5.1.0 installer
export PATH="/anaconda3/bin:$PATH"

# Setting PATH for Python 3.6
# The original version is saved in .profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
```
which means you prepend `/Library/Frameworks/Python.framework/Versions/3.6/bin` to `PATH` giving it a higher priority than `/anaconda3/bin`. Just remove those last 5 lines.
