### ISSUE TITLE
cant deactivate an env in conda

### ISSUE THREAD

**Issue by aliranjbar1370** [conda/conda#7296]
let leave that i cant access conda in Atom command prompt and i am using conda prompt,i cant deactivate an environment ,i can activate it by saying activate myenv,but when i say deactivate myenv it saying : 
deactivate does not accept arguments 
reminder_args : ('myenv', )
help me

**Comment by PertuyF** [comment]
Because you can only deactivate the active environment, so `conda deactivate` does not need nor accept arguments. The error message is very explicit here.

Just call `conda deactivate`.

**Comment by mbargull** [comment]
Solution is correctly described by @PertuyF, thanks!
