### ISSUE TITLE
Connections to whitelist for Network Security 

### ISSUE THREAD

**Issue by dbirdflyshi** [conda/conda#7300]
Is there a list of websites and connections to get full functionality of anaconda and all it's features i can gather to give to the network security team?

**Comment by kalefranz** [comment]
The Anaconda repositories are served through Cloudflare.  Packages from anaconda.org are served via a combination of Cloudflare and AWS s3.  So you could definitely whitelist Cloudflare and s3, although I'm not sure your sysadmin will like that answer.  The infrastructure isn't designed for the purposes of IT whitelisting.  For options that are more IT-friendly, contact sales@anaconda.com and reference this issue.
