### ISSUE TITLE
CondaHTTPError: HTTP 404 NOT FOUND

### ISSUE THREAD

**Issue by tokeemtareq** [conda/conda#7301]
> I am facing the current dilemma while reinstalling miniconda2,
> Is it a common issue?
> 
> I have been trying for several hours, but all other solves do not seem to work.
> 
> Can anyone answer the solution?

$conda update conda

Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /home/molgen/miniconda2/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
               CONDA_ROOT=/home/molgen/miniconda2
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/molgen/01.NGSTools/02.Advanced/02.Tools/LS-BSR:/home/molgen/mini
                          conda2/bin:/home/molgen/MetaCRAST/bin:/home/molgen/MetaCRAST/bin:/home
                          /molgen/NGSTools/02.Advanced/02.Tools/CONDA_all/miniconda2/bin:/home/m
                          olgen/NGSTools/02.Advanced/02.Tools/skewer-0.2.2/:/home/molgen/NGSTool
                          s/02.Advanced/02.Tools/SPAdes-3.10.1/bin:/usr/bin/miniconda2/bin:/home
                          /molgen/miniconda3/bin:/home/molgen/bin:/home/molgen/.local/bin:/usr/l
                          ocal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr
                          /local/games:/snap/bin:/home/molgen/NGSTools/02.Advanced/02.Tools/DeNo
                          GAP_v1.0/bin/../exe/mcl/bin:/home/molgen/.local/bin:/home/molgen/edire
                          ct
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
       user config file : /home/molgen/.condarc
 populated config files : /home/molgen/.condarc
          conda version : 4.5.1
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/molgen/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/hcc/linux-64
                          https://conda.anaconda.org/hcc/noarch
                          https://conda.anaconda.org/biocore/linux-64
                          https://conda.anaconda.org/biocore/noarch
                          https://conda.anaconda.org/biobin/conda/linux-64
                          https://conda.anaconda.org/biobin/conda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/molgen/miniconda2/pkgs
                          /home/molgen/.conda/pkgs
       envs directories : /home/molgen/miniconda2/envs
                          /home/molgen/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-124-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/biobin/conda/noarch/repodata.json>
Elapsed: 00:01.072223
CF-RAY: 41c39b4d8882aa7a-SIN

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/biobin/conda

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

A reportable application error has occurred. Conda has prepared the above report.
Upload successful.

**Comment by mbargull** [comment]
>The remote server could not find the noarch directory for the
>requested channel with url: https://conda.anaconda.org/biobin/conda
>
>As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
>associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
>empty. please request that the channel administrator create
>`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
>$ mkdir noarch
>$ echo '{}' > noarch/repodata.json
>$ bzip2 -k noarch/repodata.json
>
>You will need to adjust your conda configuration to proceed.
>Use `conda config --show channels` to view your configuration's current state.
>Further configuration help can be found at https://conda.io/docs/config.html.

"https://conda.anaconda.org/biobin/conda" is no Conda channel.
Depending on the output of `conda config --show channels`, run either
* `conda config --remove channels 'biobin/conda'`
* or `conda config --remove channels 'https://conda.anaconda.org/biobin/conda'`

**Comment by tokeemtareq** [comment]
Thanks for the quick reply.
It worked like a charm.

**Comment by udaykeith** [comment]
This worked well for me facing the exact same error message while trying to install gdal using: conda install -c conda-forge gdal 

My question is: How do those channel names show up in our channels list in the first place?
