### ISSUE TITLE
is armv7 support discontinued

### ISSUE THREAD

**Issue by jruizaranguren** [conda/conda#7302]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

Last miniconda supported version for armv7 architecture is 3.16, built in 2015.

## Expected Behavior

Would like to have updated versions of miniconda for armv7.
Any plans to support armv7? That would open miniconda for Raspberry PI users.

**Comment by kalefranz** [comment]
Check out https://github.com/jjhelmus/berryconda
