### ISSUE TITLE
pip flags not included in export 

### ISSUE THREAD

**Issue by dangirsh** [conda/conda#7306]
I can create an `environment.yml` file like 

```
name: env-name
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pip:
    - --extra-index-url=<index-url>
    - --trusted-host=<host>
    - my-local-pkg==1.0
```

I install this environment, then try to export it for sharing. The exported config doesn't include the pip flags, meaning it will fail to install `my-local-pkg`! 

### Steps to Reproduce

```
conda env create -f environment.yml
conda env export -n env-name > exported-env.yml  
```

## Expected Behavior

`exported-env.yml` is currently correct, except for the pip flags. It correctly contains a listing for `my-local-pkg`, but I expected conda to also keep track of the pip flags in the original file.

## Environment Information

<details>
<summary><code>conda info</code></summary>

```
     active environment : None
       user config file : /home/dan/.condarc
 populated config files : /home/dan/.condarc
          conda version : 4.5.2
    conda-build version : 3.9.1
         python version : 3.6.4.final.0
       base environment : /home/dan/miniconda3  (writable)
           channel URLs : ...
                          /home/dan/.conda/pkgs
       envs directories : /home/dan/miniconda3/envs
                          /home/dan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-39-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

</details>

**Comment by kalefranz** [comment]
Happy to make this a feature request, but it's not a bug.  Holding over this state wasn't ever designed into conda env.

**Comment by dangirsh** [comment]
From https://conda.io/docs/user-guide/concepts.html :

"You can also share your environment with someone by giving them a copy of your environment.yaml"

Either this is a bug, or the docs have a bug :)

Is the best workaround to create a local conda index and repackage for that?

**Comment by jaksiprejak** [comment]
It would be great to have this as a feature.

Perhaps having an "update" flag on export command, that modifies an existing yml file's packages only, would be a fast way to enable this functionality?

I.e. export env to file -> make manual edits for whatever pip stuff you want -> export _update_ the file as you go
