### ISSUE TITLE
Suggestion: auto pin python minor version

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#7325]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

Currently, if a version is not offered for 3.6, but for 3.5 from the preferred channel, conda downgrades the whole channel, as has happened in this issue: https://github.com/conda-forge/ipyparallel-feedstock/issues/30#issuecomment-390772128

As my last post suggests, it is of great help to let `conda` tell you which package in a huge list of to be installed packages actually creates the conflict that initiates the downgrade suggestion.
A way to do this is to pin the python minor version like so:

`conda config --env --add pinned_packages "python=3.6"`

I humbly suggest that this is what 99% of the users would like anyway, and therefore conda should auto-pin to the minor version a current env is being installed for.

## Expected Behavior

Installing a package should never suggest/try to downgrade to a different minor version of Python. That's just too much of a change, can break working code.

**Comment by tjd2002** [comment]
Generally agree (and even more strongly if the suggestion would be to pin the major version to avoid user confusion: see for example #8718)

But, I can see some big usability issues with automatically adding a pin. Specifically, how would unpinning/upgrading work?

I think most users would expect ‘conda update python’ to upgrade their python to latest point release, but it wouldn’t do that if python were pinned. 

If instead you do ‘conda install --no-pin python’ you will get the latest version, but it will then revert to the pinned version on subsequent calls to install (according to the docs here: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning )

Maybe there needs to be an ‘--update-pins’ flag to conda install, which can then be applied to certain packages by default? (But it’s not clear what the logic would be here for determining if the pin should be to major, minor, or patch version.

Another solution I can see would be to create metapackages for python major and point releases. ‘python3’, ‘python36’, etc. these packages would only contain a single dependency on the requested python versions, and could be uninstalled when the user wants to upgrade.

**Comment by michaelaye** [comment]
> I think most users would expect ‘conda update python’ to upgrade their python to latest point release, but it wouldn’t do that if python were pinned.

That's fine for upgrades of point releases. But it's definitely not fine for automatic downgrades of point releases, which can render my existing code incompatible and leaves me with a broken system.

**Comment by h-vetinari** [comment]
There's already the functionality to do that with [`conda-meta/pinned`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html?highlight=pinned#preventing-packages-from-updating-pinning). However, AFAICT, there's no API to fill or inspect that file.

**Comment by michaelaye** [comment]
@h-vetinari that's not what this issue is about. I am requested that the minor version of python is **AUTO**-pinned after creating the env. I'm well aware that I can pin it myself, but many users are not and my suggestion is that this could be fatal to the un-initiated user.

**Comment by h-vetinari** [comment]
@michaelaye 
What I meant is that conda is already able to do that *internally*, and now it's only a matter of exposing that to the API, resp. changing the defaults. IOW, I support your suggested change, which has frequently been a nuisance for myself as well.

**Comment by msarahan** [comment]
This is the behavior of conda 4.7.x.  Conda will not allow python to change unless it is an explicit dependency.

**Comment by rgommers** [comment]
Since this is now implemented on 4.7.x, can the issue be closed?

**Comment by michaelaye** [comment]
Yes, Thanks!
