### ISSUE TITLE
New networking filter causing problems with anaconda

### ISSUE THREAD

**Issue by dbirdflyshi** [conda/conda#7330]
The network security team recently set up a https filter thus causing a ton of problems with trying to get anaconda to run the way it's supposed to be. I got them to whitelist some sites which allows me to log into anaconda navigator and install/update packages, but i am still having issues with anaconda navigator opening up as it gets stuck at the 'loading applications' step for 10 minutes at a time. I am also having issues with creating new environments in navigator where the entire program goes into 'not responding' for even longer than 10 minutes. It eventually builds the environment but it's a total hassle every time i open the app and make environments. 

What are the https addresses i need to have network security whitelist in the filter in order to get full functionality back into anaconda navigator?

**Comment by kalefranz** [comment]
Depending on the versions of conda and navigator, either `https://repo.continuum.io` or `https://repo.anaconda.com`.  If you're using anything from anaconda.org (like conda-forge), then also `https://conda.anaconda.org`.

**Comment by dbirdflyshi** [comment]
navigator = 1.8.5
conda = 4.5.4

**Comment by kalefranz** [comment]
In that case you *should* be ok with just the newer `https://repo.anaconda.com`.  However it might be safest to also add `https://repo.continuum.io` just in case, or if you continue to see the behavior you're describing.

**Comment by dbirdflyshi** [comment]
https://repo.anaconda.com
https://www.anaconda.com
https://repo.continuum.io
these have already been unblocked and im still having these issues

**Comment by dbirdflyshi** [comment]
bump

**Comment by kalefranz** [comment]
I guess you'll need to get more verbose logging output from Navigator.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#9430
