### ISSUE TITLE
How to create or transplant an environment without the Internet?

### ISSUE THREAD

**Issue by Harold-Zhang** [conda/conda#7337]
**Does anyone know the way to create or transplant an environment without the Internet?** 
I need to deploy my environment on a machine, but it is not able to connect the Internet. I can deploy my environment on a machine which can connect the Internet, and then I transplant the environment to the machine without the Internet. But I don't know the way to transplant. I have tried to copy the environment from the online machine to the offline machine, but it caused some mistakes. I hope someone can give me a hand.

**Comment by kalefranz** [comment]
Please provide the output of ‘conda info’ for *both* machines.

**Comment by Harold-Zhang** [comment]
**The online machine**
     active environment : intel
    active env location : /root/anaconda2/envs/intel
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : /root/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /root/anaconda2/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda2/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-87-generic ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False

**The offline machine**
Current conda install:

             platform : linux-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : /WORK/app/anaconda/2.1.0  (read only)
  default environment : /HOME/acict_gmtan_1/envs/intel
     envs directories : /HOME/a**t/envs
                        /WORK/app/anaconda/2.1.0/envs
        package cache : /HOME/a**t/envs/.pkgs
                        /WORK/app/anaconda/2.1.0/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

The conda version is different, but I have tried the same version, and it still doesn't work.

**Comment by Harold-Zhang** [comment]
Does anyone know how to solve this problem? It is really a problem to deploy the system environment.

**Comment by groutr** [comment]
One possible way to do it is to setup a local conda channel on the offline machine and populate it with the package archives that you need.  Then when you setup your environment on the offline machine, you can point conda to the local channel to fetch its packages.  

To get the list of packages, you can setup the environment on your machine that has network access and see what packages get installed.  Then simply copy those package archives from your cache into your local channel.  It's a bit hacky, but it should work.

**Comment by brethvoice** [comment]
Using Windows 10 Anaconda Navigator, you can clone any environment (except the base) by navigating to the "Environments" tab, selecting the environment you wish to clone, and selecting "clone" from the options at the bottom of the page.
