### ISSUE TITLE
NotWritableError: The current user does not have write permissions to a required path.

### ISSUE THREAD

**Issue by pragya2411** [conda/conda#7342]
please help me with this whenever i am writing the conda update conda command it is showing this error

(base) C:\Users>conda info

     active environment : base
    active env location : C:\Users\pragya saraswat\Anaconda2
            shell level : 1
       user config file : C:\Users\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : C:\Users\pragya saraswat\Anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\pragya saraswat\Anaconda2\pkgs
                          C:\Users\pragya saraswat\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\pragya saraswat\Anaconda2\envs
                          C:\Users\pragya saraswat\AppData\Local\conda\conda\envs
                          C:\Users\.conda\envs
               platform : win-32
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda

## Package Plan ##

  environment location: C:\Users\pragya saraswat\Anaconda2\envs\myenv

  added / updated specs:
    - python=3.4

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.29.0               |           py34_0         120 KB
    vs2010_runtime-10.00.40219.1|                2         944 KB
    python-3.4.5               |                0        21.7 MB
    setuptools-27.2.0          |           py34_1         759 KB
    vc-10                      |                0          700 B
    pip-9.0.1                  |           py34_1         1.7 MB
    ------------------------------------------------------------
                                           Total:        25.2 MB

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py34_1
    python:         3.4.5-0
    setuptools:     27.2.0-py34_1
    vc:             10-0
    vs2010_runtime: 10.00.40219.1-2
    wheel:          0.29.0-py34_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
wheel 0.29.0: ################################################################################################# | 100%
vs2010_runtime 10.00.40219.1: ################################################################################# | 100%
python 3.4.5: ################################################################################################# | 100%
setuptools 27.2.0: ############################################################################################ | 100%
vc 10: ######################################################################################################## | 100%
pip 9.0.1: #################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: C:\Users\.conda\environments.txt

**Comment by wulmer** [comment]
Hi, your `.condarc` seems to contain an invalid env path: Try to change `C:\Users` to `C:\Users\yourusername\`.

**Comment by diegormzgro** [comment]
I have the same problem and I am in C:\Users\yourusername\ and Still is not working

**Comment by avi-developer** [comment]
run anaconda prompt as an admin, this worked for me.

**Comment by cocamaho** [comment]
Guys, run anaconda prompt as an admin is worked for me. Thank avi-developer!

**Comment by KillianPremel** [comment]
Hi, I have the same issue. The user config file path is wrong, and  one of the env directories also. How do I change the paths ? 

I have that :
envs directories : C:\Anaconda3\envs
                          C:\Users\emac\AppData\Local\conda\conda\envs
                          C:\Users\emac\ \Users\emac\.conda\envs
But I don't understand why there is a \Users\emac twice...

**Comment by vipinrane** [comment]
> run anaconda prompt as an admin, this worked for me.

This Worked for me too :)

**Comment by BarryDeCicco** [comment]
Seconding vipinrane - I played with removing the read-only status of the directory in Windows explorer, but running the Anaconda prompt as an admin worked fine.

**Comment by lumbric** [comment]
If you get this error using Linux when run via sudo, see #7267 and especially [this comment](https://github.com/conda/conda/issues/7267#issuecomment-387329419).

**Comment by vaibhavpathak999** [comment]
> please help me with this whenever i am writing the conda update conda command it is showing this error
> 
> (base) C:\Users>conda info
> 
> ```
>  active environment : base
> active env location : C:\Users\pragya saraswat\Anaconda2
>         shell level : 1
>    user config file : C:\Users\.condarc
> ```
> 
> populated config files :
> conda version : 4.4.10
> conda-build version : 3.4.1
> python version : 2.7.14.final.0
> base environment : C:\Users\pragya saraswat\Anaconda2 (writable)
> channel URLs : https://repo.continuum.io/pkgs/main/win-32
> https://repo.continuum.io/pkgs/main/noarch
> https://repo.continuum.io/pkgs/free/win-32
> https://repo.continuum.io/pkgs/free/noarch
> https://repo.continuum.io/pkgs/r/win-32
> https://repo.continuum.io/pkgs/r/noarch
> https://repo.continuum.io/pkgs/pro/win-32
> https://repo.continuum.io/pkgs/pro/noarch
> https://repo.continuum.io/pkgs/msys2/win-32
> https://repo.continuum.io/pkgs/msys2/noarch
> package cache : C:\Users\pragya saraswat\Anaconda2\pkgs
> C:\Users\pragya saraswat\AppData\Local\conda\conda\pkgs
> envs directories : C:\Users\pragya saraswat\Anaconda2\envs
> C:\Users\pragya saraswat\AppData\Local\conda\conda\envs
> C:\Users.conda\envs
> platform : win-32
> user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
> administrator : False
> netrc file : None
> offline mode : False
> 
> ==> WARNING: A newer version of conda exists. <==
> current version: 4.4.10
> latest version: 4.5.4
> 
> Please update conda by running
> 
> ```
> $ conda update -n base conda
> ```
> 
> ## Package Plan
> environment location: C:\Users\pragya saraswat\Anaconda2\envs\myenv
> 
> added / updated specs:
> - python=3.4
> 
> The following packages will be downloaded:
> 
> ```
> package                    |            build
> ---------------------------|-----------------
> wheel-0.29.0               |           py34_0         120 KB
> vs2010_runtime-10.00.40219.1|                2         944 KB
> python-3.4.5               |                0        21.7 MB
> setuptools-27.2.0          |           py34_1         759 KB
> vc-10                      |                0          700 B
> pip-9.0.1                  |           py34_1         1.7 MB
> ------------------------------------------------------------
>                                        Total:        25.2 MB
> ```
> 
> The following NEW packages will be INSTALLED:
> 
> ```
> pip:            9.0.1-py34_1
> python:         3.4.5-0
> setuptools:     27.2.0-py34_1
> vc:             10-0
> vs2010_runtime: 10.00.40219.1-2
> wheel:          0.29.0-py34_0
> ```
> 
> Proceed ([y]/n)? y
> 
> Downloading and Extracting Packages
> wheel 0.29.0: ################################################################################################# | 100%
> vs2010_runtime 10.00.40219.1: ################################################################################# | 100%
> python 3.4.5: ################################################################################################# | 100%
> setuptools 27.2.0: ############################################################################################ | 100%
> vc 10: ######################################################################################################## | 100%
> pip 9.0.1: #################################################################################################### | 100%
> Preparing transaction: done
> Verifying transaction: failed
> 
> NotWritableError: The current user does not have write permissions to a required path.
> path: C:\Users.conda\environments.txt

There can be two simple issues due to which this issue is generated--
* During installing library your Anaconda program is running. This restricts you to make any changes in environment during working. 

Solution-1 Close Anaconda program then try installing library on command prompt.  
Solution-2 Close Anaconda program then run Anaconda Prompt as Administrator.

I Hope this will work for you.

**Comment by sushmanthnatha** [comment]
Even I had a similar problem, just use pip to install.
I used  ( pip install  pkg-name) in the jupyter notebook itself and it worked

**Comment by BarryDeCicco** [comment]
Thanks!

    On Sunday, May 3, 2020, 11:10:52 AM EDT, sushmanthnatha <notifications@github.com> wrote:  
 
 


Even I had a similar problem, just use pip to install.
I used ( pip install pkg-name) in the jupyter notebook itself and it worked

**Comment by kapdivyang** [comment]
I had the same problem and got solved by just running anaconda as administrator.
[Thanks to stackoverflow](https://stackoverflow.com/questions/55290271/updating-anaconda-fails-environment-not-writable-error)
