### ISSUE TITLE
conda package build  are not avaible the compressed file

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [conda/conda#7350]
I try to build this  package:
https://github.com/bioinfo-dirty-jobs/conda_vcf2maf
All the precess seem works  but I don't have any bz2  file as show in this command..
```
conda build . --output
/home/maurizio/miniconda2/conda-bld/linux-64/vcf2maf-1.6.16-pl5.22.0_1.tar.bz2

```
I just wondering what is the problem?

**Comment by kalefranz** [comment]
The conda-build issue tracker is at github.com/conda/conda-build.
