### ISSUE TITLE
Unexpected instructions for `conda activate` on Windows

### ISSUE THREAD

**Issue by ericdill** [conda/conda#7353]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

When I type `\path\to\install\Scripts\conda activate` in a terminal on Windows **while conda is not on my path** then there are instructions dumped to the screen that tell me how to add conda to my path **for bash shells**, not Windows.

### Steps to Reproduce

```
1. Install miniconda on Windows
2. Do not add it to your path
3. Open cmd
4. \path\to\install\Scripts\conda activate
```

## Expected Behavior

~I should be given instructions on how to put conda on my path in Windows or provided a link to do so~

I should be given correct instructions on how to use conda properly on Windows, not bash

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
C:\Users\builder\Miniconda3\Scripts\conda --version

conda 4.5.4

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

![screen shot 2018-05-30 at 3 37 30 pm](https://user-images.githubusercontent.com/6223243/40748989-79564706-6430-11e8-9e7d-8abeea4c4773.png)

**Comment by mingwandroid** [comment]
I disagree. Windows users should never have to think about PATH.

It should tell you to use the Anaconda prompt instead so that activation takes place.

**Comment by ericdill** [comment]
What is the Anaconda prompt?

> I disagree. Windows users should never have to think about PATH.

That's fine. I defer to you on what the "right" answer here is. This report is concerned that I'm getting fundamentally incorrect bash instructions on a Windows machine. I'll update the original post to reflect that I am not trying to proscribe a solution

**Comment by mingwandroid** [comment]
No problem, the messaging is pretty poor there but this whole area is in flux and I'm not sure where the cards will fall. We need something better than this though.

I'm not actually sure why activate failed at all to be honest.

Have you ever used this installation from the bash prompt? I'm wondering if some shebang got bashified or something?

**Comment by ericdill** [comment]
> Have you ever used this installation from the bash prompt? I'm wondering if some shebang got bashified or something?

These are the exact steps I took:

1. Launch new instance of windows 10 virtual box from IT
2. download miniconda
3. run miniconda installer (it finished successfully), but I did not tick the "add conda to my PATH" option
4. launch cmd
5. type `conda` (this fails)
6. navigate to C:\Users\<username>\Miniconda3\Scripts
7. type `conda` (this works)
8. type `conda activate` (this produces the bash guidance)

**Comment by mingwandroid** [comment]
Ok, thanks; not good then!

**Comment by mbargull** [comment]
> 6. navigate to C:\Users<username>\Miniconda3\Scripts

`Scripts\conda.exe` is the entrypoint for the main program itself.
To be able to modify the shell environment, you'll have to run the appropriate shell script, which is
```bat
call C:\Users<username>\Miniconda3\Library\bin\conda.bat activate
```
for `cmd.exe`.

But @mingwandroid is correct with "this whole area is in flux". If you want to try the alpha version of the next minor release, you could install it with `conda install conda-canary::conda`.
This will give a very different error message if you try to run `conda activate` on the executable itself:
```
(base) $ $(type -P conda) activate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```
(On Windows `cmd.exe` will be part of that `supported shells` list.)

**Comment by ericdill** [comment]
Hi @mbargull, thanks for chiming in.

> This will give a very different error message if you try to run conda activate on the executable itself <snip> (On Windows cmd.exe will be part of that supported shells list.)

That's great!

**Comment by lautjy** [comment]
Still the same behavior on Windows 10, Anaconda 2018.12.
I'm getting Linux bash instructions when using `c:\windows\system32\cmd.exe` .

Conda info:

```
    conda version : 4.5.12
    conda-build version : 3.17.6
    python version : 3.7.1.final.0
```

Anaconda prompt can do `conda activate` fine, no errors. It is just not integrated to my workflows :/

**Comment by Seshirantha** [comment]
On the windows environment use "anaconda prompt" instead of "command prompt".
1. Go to search.
2. Type "anaconda prompt" and open it.
3. Then type "conda activate <env_name>
