### ISSUE TITLE
Outdated error information regarding license package when running conda info

### ISSUE THREAD

**Issue by rltbennett** [conda/conda#7362]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

### Steps to Reproduce

`conda info -a` shows the following at the end:
```
WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

## Expected Behavior

`root` has been renamed to `base` so it should say `conda install -n base _license`.

**Comment by kalefranz** [comment]
We need to remove this `_license` stuff altogether.  It no longer applies after Anaconda 5.0 and the `pkgs/main` channel.
