### ISSUE TITLE
Document new way to install and activate?

### ISSUE THREAD

**Issue by cdeil** [conda/conda#7363]
I see that the new way to set up conda is this:
```
. /opt/conda/etc/profile.d/conda.sh
conda activate base
```
* https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/
* https://github.com/conda/conda/blob/master/CHANGELOG.md#440-2017-12-20

I just now (June 1, 2018) installed Anaconda 5.2 with conda 4.5.4 and by default the installer still adds this to my `~/.bash_profile`, i.e. uses the old way to set things up:
```
# added by Anaconda3 5.2.0 installer
export PATH="/Users/deil/software/anaconda3/bin:$PATH"
```

Same with the docs (https://conda.io/docs/) - as far as I see they don't even mention the new way to set things up yet.

It's been about half a year since the conda 4.4 release. Time to update the docs and Anaconda installer to use the new way?

**Comment by leezu** [comment]
@kalefranz @goanpeca it would be great if you can clarify how you plan to update the conda installer. We are preparing material to be printed and to be used by people without experience with conda. We currently instruct to answer `yes` to the question if the path should be augmented during installation and use `source activate` instructions later. We wan't to make sure that these instructions don't fall out of date quickly after print.

In particular the concerns are:
- If the question changes and the `conda` shell function is defined by default, our `source activate` 
instructions may break.
- We can instruct users to say `no` to the PATH augmentation and manually add the shell function definition, but this adds additional complexity and we are not sure why it is not done by default instead (ie. may there lurk some other issues with this)?

Thanks for the clarification!

CC: @astonzhang
