### ISSUE TITLE
conda on python 2.7.15rc1 (Ubuntu Mate 18.04) fails

### ISSUE THREAD

**Issue by alexxtasi** [conda/conda#7366]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request
(I suppose !!)

## Current Behavior

While trying to install conda (happens with both Anaconda and Miniconda) on Ubuntu Mate 18.04, the installation stops with a message:
```
[/home/ubuntu/miniconda2] >>>
PREFIX=/home/ubuntu/miniconda2
installing: python-2.7.14-h1571d57_31 ...
Downloads/Miniconda2-latest-Linux-x86.sh: line 355:  2794 Illegal instruction     (core dumped) 
 $PREFIX/pkgs/python-2.7.14-h1571d57_31/bin/python" -E -s "$PREFIX"/pkgs/.install.py $INST_OPT --root-prefix="$PREFIX" --link-dist="$1"
```
I have to mention that a fresh Mate 18.04 installation comes with python-2.7.15rc1 preinstalled !!
Maybe there is a problem with python rc version ?

### Steps to Reproduce

```
- install Ubuntu Mate 18.04
- download and install Miniconda2 or Anaconda2 latest versions
```

## Expected Behavior

Expected to proceed and succeed in the installation, as described in the installation documentation.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by alexxtasi** [comment]
oups!
the same error comes when trying to install Miniconda2-latest-Linux-x86 in Ubuntu-Mate-16.04 (python 2.7.12) !!
... so my first assumption (error related with the python version) is not true 

any suggestions ?
regards

**Comment by kalefranz** [comment]
@nehaljwani Do you see anything obvious here with the installer? Or something this user's environment is lacking?

**Comment by alexxtasi** [comment]
I did some tests creating a vm (ubuntu mate 18.04 with python-2.7.15rc1) ... the installation of Miniconda2 ended with no errors!!

The processor of the first machine, where this issue came from is ```Intel Pentium M @2Ghz```
do you think this might be the problem?

- this is not excluded from miniconda's [requirements](https://conda.io/docs/user-guide/install/index.html#system-requirements) though
- also the error does not indicate such a problem

do you think it is relevant ?

regards

**Comment by mingwandroid** [comment]
Most Pentium-M are too old to support Anaconda. We require sse3.
