### ISSUE TITLE
Pin all packages in a conda environment without listing them all

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda#7375]
**I'm submitting a...**
  - [ ] bug report
  - [X] feature request

## Current Behavior

According to the [docs](https://conda.io/docs/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning) it is possible to pin a list of packages in a conda environment by adding a file named `pinned` to the `conda-meta` directory with a list of the packages that you do not want updated.

### Steps to Reproduce

```
N/A
```

## Expected Behavior

Is it possible to pin all packages in a conda environment without explicitly mentioning all of them?  i.e. just use a keyword like `all` in the `pinned` file inside the `conda-meta` directory.

**Comment by kalefranz** [comment]
There's a `--freeze-installed` flag.  It's for sure there in the master branch, and might also be available in the latest 4.5 (I don't remember).  Does that cover your use case?

**Comment by kalefranz** [comment]
If it's not available in conda 4.5, you can get conda 4.6.0a2 from the `conda-canary` channel to try it out.

**Comment by sebastian-luna-valero** [comment]
Is `--freze-installed` equivalent to `--no-update-deps`?
https://github.com/conda/conda/blob/master/conda/cli/conda_argparse.py#L1377

**Comment by sebastian-luna-valero** [comment]
Just to add to my previous comments:
* `--no-update-deps` (and presumably `--freeze-installed`) helps when you are installing new packages into an existing environment. However, you need to use `--no-update-deps` every time that you want to install new packages.
* regarding my use case: once the environment has been created or updated, I would like to have the option of running a command after which all the dependencies are frozen and you don't have to use `--no-update-deps` every time you want to install a new package into that environment. I guess that's what you currently achieve with the `pinned` file inside the `conda-meta` directory. However, that's only suitable when you only want to pin a small number of packages. For environments where you have a large number of packages and you want to pin them all, it is a bit of a problem.

**Comment by kalefranz** [comment]
I just pushed a PR that'll be in 4.6.0a3.

Theoretically, with 4.6.0a2, you should have been able to do `conda config --env --set update_modifier freeze_installed`.  That's undocumented, and might remain that way (or we might expose it someday, idk).  But without #7377 you run into a stack trace with `conda config --set` there.  For 4.6.0a2, you could just do `echo "update_modifier: freeze_installed" > ENV_LOCATION/.condarc`.

**Comment by kalefranz** [comment]
And yeah, `--freeze-installed` and `--no-update-deps` do the same thing.

**Comment by sebastian-luna-valero** [comment]
Many thanks!

It didn't work for me with `4.6.0a2`.

Below are the commands that I run. Please let me know if I am doing something wrong.

If the commands below are fine, I will then re-try them with `4.6.0a3` when https://github.com/conda/conda/pull/7377 is merged

```
# install conda
curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p i-1

# installed 4.6.0a2
source i1/etc/profile.d/conda.sh 
conda activate base
conda update --all -c conda-canary -c defaults

# created test env
conda create -n test-1 numpy=1.12.1 nomkl -c defaults
echo "update_modifier: freeze_installed" > /tmp/tmp.cpe41nMdqO/i-1/envs/test-1/.condarc

# the following test did not work: offered updating numpy to latest version (1.14.3) 
conda update numpy -c defaults

# however, this worked
echo "numpy ==1.12.1" > /tmp/tmp.cpe41nMdqO/i-1/envs/test-1/conda-meta/pinned
```

FYI:
```
     active environment : test-1
    active env location : /tmp/tmp.cpe41nMdqO/i-1/envs/test-1
            shell level : 1
       user config file : /ifs/home/sebastian/.condarc
 populated config files : /ifs/home/sebastian/.condarc
          conda version : 4.6.0a2
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /tmp/tmp.cpe41nMdqO/i-1  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/tmp.cpe41nMdqO/i-1/pkgs
                          /ifs/home/sebastian/.conda/pkgs
       envs directories : /tmp/tmp.cpe41nMdqO/i-1/envs
                          /ifs/home/sebastian/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.0a2 requests/2.18.4 CPython/3.6.5 Linux/2.6.32-696.23.1.el6.x86_64 scientific/6.9 glibc/2.12
                UID:GID : 1362:1000
             netrc file : None
           offline mode : False
```

**Comment by kalefranz** [comment]
>     # the following test did not work: offered updating numpy to latest version (1.14.3) 
>     conda update numpy -c defaults

Yeah that's expected.  Because the `numpy` in the command overrides the "freeze" for `freeze_installed`.  Everything else in the environment is frozen, but when you add `numpy` to the command, that one floats.  There might be some behavior to tweak here, or we might need to introduce one more option in the spectrum of all the update modifiers.

**Comment by sebastian-luna-valero** [comment]
Right. My expected behaviour was that after:
```
echo "update_modifier: freeze_installed" > /tmp/tmp.cpe41nMdqO/i-1/envs/test-1/.condarc
```

All the packages in that environment would be pinned, and they could neither be updated nor downgraded. Would that be of common interest?

**Comment by kalefranz** [comment]
It might, I'm not sure.  I guess pinning isn't exactly the same thing as `freeze_installed`, because the pins are specs, and so depending on how locked down the spec is, there's the possibility of the package floating and changing.

Can you discuss your exact use case a little more?  The larger workflow and problem you're trying to solve for?  Might help me see everything with more context.

**Comment by sebastian-luna-valero** [comment]
Sure. 

I am working with complex conda environments (> 80 direct dependencies). Here is an example:
https://github.com/CGATOxford/CGATPipelines/blob/master/conda/environments/pipelines-devel.yml

I ask users to install the environment, but they normally need to install new conda packages afterwards. `conda install` will by default upgrade installed packages and, in my experience, that is very likely to break the environment by installing incompatible versions of packages.

With this feature request I would like to lock down the entire conda environment after it has been created. Therefore I enforce the user to install new packages into new, separate environments.

Does this make sense?
