### ISSUE TITLE
Add ability to remove multiple environments in a single command

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#7380]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

`conda env remove` doesn't support removing multiple environments in the same invocation of the command.

### Steps to Reproduce

```
$ conda env remove -yn test1 -n test2  #This only removes test2
```

## Expected Behavior

Both conda environments, `test1` and `test2` should be removed.

**Comment by kalefranz** [comment]
I've been thinking about adding a `conda init --uninstall` that would pretty much wipe everything known and possible.  Guess that's not the same, but potentially related.
