### ISSUE TITLE
I installed anaconda 3.6 in windows 64bit .But getting error .Its not opening

### ISSUE THREAD

**Issue by IIITian-Chandan** [conda/conda#7381]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\OpenSource\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\ProgramData\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
             GIT_LFS_PATH=C:\Program Files\Git LFS
                 HOMEPATH=\Users\OpenSource
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.2\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Progr
                          am Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
                          Client\;C:\Program Files (x86)\Java\jre1.8.0_161;C:\Windows\system32;C
                          :\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShe
                          ll\v1.0\;C:\Program Files\PuTTY\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Python27\;C:\Python27\Scripts\;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common
                          Files\Seagate\SnapAPI\;C:\Program Files\Git\cmd;C:\Program Files\Git
                          LFS;C:\Program Files (x86)\Yarn\bin;C:\Program
                          Files\nodejs\;C:\Program Files (x86)\Pandoc\;C:\Go\bin;C:\Program
                          Files (x86)\sbt\bin;C:\Program Files\CMake\bin;%SystemRoot%\system32;%
                          SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPo
                          werShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\spark-2.3.0-bin-hadoo
                          p2.7\bin;C:\wget;C:\cygnus\cygwin-b20\H-i586-cygwin32\bin;C:\Program F
                          iles\Git;C:\Users\OpenSource\AppData\Local\Yarn\bin;C:\Users\OpenSourc
                          e\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\Java\jd
                          k1.8.0_161\bin;C:\Users\OpenSource\AppData\Local\atom\bin;C:\Users\Ope
                          nSource\flutter\bin;C:\scala-2.10.5\bin;C:\Program Files
                          (x86)\sbt\bin;C:\winutils-master\winutils-
                          master\hadoop-2.7.1\bin;C:\winutils-master\winutils-master\hadoop-2.6.
                          0\bin;C:\adb;C:\Users\OpenSource\AppData\Local\Microsoft\WindowsApps;C
                          :\cuda\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\OpenSource\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\OpenSource\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\OpenSource\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\OpenSource\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: conda update conda

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

C:\Users\OpenSource>conda update conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\OpenSource\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
             GIT_LFS_PATH=C:\Program Files\Git LFS
                 HOMEPATH=\Users\OpenSource
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.2\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Progr
                          am Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
                          Client\;C:\Program Files (x86)\Java\jre1.8.0_161;C:\Windows\system32;C
                          :\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShe
                          ll\v1.0\;C:\Program Files\PuTTY\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Python27\;C:\Python27\Scripts\;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common
                          Files\Seagate\SnapAPI\;C:\Program Files\Git\cmd;C:\Program Files\Git
                          LFS;C:\Program Files (x86)\Yarn\bin;C:\Program
                          Files\nodejs\;C:\Program Files (x86)\Pandoc\;C:\Go\bin;C:\Program
                          Files (x86)\sbt\bin;C:\Program Files\CMake\bin;%SystemRoot%\system32;%
                          SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPo
                          werShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\spark-2.3.0-bin-hadoo
                          p2.7\bin;C:\wget;C:\cygnus\cygwin-b20\H-i586-cygwin32\bin;C:\Program F
                          iles\Git;C:\Users\OpenSource\AppData\Local\Yarn\bin;C:\Users\OpenSourc
                          e\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\Java\jd
                          k1.8.0_161\bin;C:\Users\OpenSource\AppData\Local\atom\bin;C:\Users\Ope
                          nSource\flutter\bin;C:\scala-2.10.5\bin;C:\Program Files
                          (x86)\sbt\bin;C:\winutils-master\winutils-
                          master\hadoop-2.7.1\bin;C:\winutils-master\winutils-master\hadoop-2.6.
                          0\bin;C:\adb;C:\Users\OpenSource\AppData\Local\Microsoft\WindowsApps;C
                          :\cuda\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\OpenSource\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\OpenSource\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\OpenSource\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\OpenSource\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

**Comment by niranjanreddy891** [comment]
@IIITian-Chandan, I had the same issue with the anaconda-4.5.4 version. So, I installed anaconda-4.3.0 version which works fine. My suggestion is try to install anaconda-4.3.0. :)

**Comment by mbargull** [comment]
The important part of the error message is
```
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\OpenSource\.condarc", position 0
```
which means your configuration file is corrupted. You can either try to edit the file manually and try to remove those NULL characters from `C:\Users\OpenSource\.condarc` or simply remove that file.

NB: We have seen this error reported a few times already but I still have no idea what caused that corruption, sadly.

**Comment by AFTownsend** [comment]
What worked for me was changing the file encoding to UTF-8. In visual studio code this can be done by selecting the encoding in the bottom right corner 
![image](https://user-images.githubusercontent.com/22835521/57767291-e4922880-7700-11e9-8dcf-17e9c847acad.png)

**Comment by KenanHArik** [comment]
> What worked for me was changing the file encoding to UTF-8. In visual studio code this can be done by selecting the encoding in the bottom right corner
> ![image](https://user-images.githubusercontent.com/22835521/57767291-e4922880-7700-11e9-8dcf-17e9c847acad.png)

Thanks for pointing this out. This worked to resolve my issue as well. I couldn't for the life of me figure out what was going on!

**Comment by qqgg231** [comment]
I think conda should detect it and inform user what should be done 🙂

**Comment by LaurieWilkinson** [comment]
Thanks, changing the environment file's UTF encoding to UTF-8 worked for me too

**Comment by cobey** [comment]
I do not think this should be marked as closed. The command `conda env export --name baseline > envname.yml` created the file with UTF-16 encoding with no user interaction. Simply creating an environment file and immediately trying to use it to create an environment fails due to the encoding issue.

**Comment by wisley94** [comment]
what worked for me was to remove  config.yaml file

**Comment by Arash-AI** [comment]
Simply, I removed the onfig.yaml file and restarted anaconda, it works for me. @wisley94 thanks

**Comment by Josiah0612** [comment]
> what worked for me was to remove config.yaml file

Same here

**Comment by dad69420** [comment]
> The important part of the error message is
> 
> ```
> ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
>   in "C:\Users\OpenSource\.condarc", position 0
> ```
> 
> which means your configuration file is corrupted. You can either try to edit the file manually and try to remove those NULL characters from `C:\Users\OpenSource\.condarc` or simply remove that file.
> 
> NB: We have seen this error reported a few times already but I still have no idea what caused that corruption, sadly.

removing the file worked
thanks
