### ISSUE TITLE
Behavior changes to consider for conda 5.0

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7394]
A running list of behavior changes to consider for the next major version bump of conda.

* #6147
* #12399
* #12401
* #12400
* #12403
* #12402

**Comment by astrojuanlu** [comment]
Was any of the behaviors described in the top comment implemented? Or was this closed because the issue didn't make sense anymore?

**Comment by kenodegard** [comment]
@astrojuanlu These ideas are all still valid but deserve to be their own epics, I'll reopen this for now and work to split them up.

**Comment by kenodegard** [comment]
New issues have been created to track the ideas above, closing this epic
