### ISSUE TITLE
make activate script define CONDA_ROOT env var

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/conda#7399]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

It would be nice if activation script defined `CONDA_ROOT` env var so that when running code in environment we can find out where conda main installation is. For example conda itself defines `CONDA_ROOT` so when creating environments from yaml pip's setup.py can find out where conda's main root. But when we activate and do things we are no longer know where the root is.

That's an issue when during installation you didn't add conda to PATH. I encountered this problem when wrote cross-platform automatic [shortcutter](https://github.com/kiwi0fruit/shortcutter) that creates shortcuts to apps in conda environments (and activated terminals shortcuts too).

**Comment by gilescope** [comment]
`CONDA_PREFIX` I think gives you that doesn't it?

**Comment by kiwi0fruit** [comment]
`CONDA_PREFIX` only gives path to the particular env not the root env.
