### ISSUE TITLE
How to correct update error ? 

### ISSUE THREAD

**Issue by rgoalcast** [conda/conda#7400]
I am trying to conda update --all through mac terminal
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::pip-9.0.1-py36h1555ced_4'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied')

**Comment by BonfaceKilz** [comment]
You should recursively `chown` the directory where you installed anaconda to be owned by you. This will solve the permissions problem. Something like this would suffice:
```
sudo chown -R <username> <path/to/anaconda>
```

**Comment by niranjanreddy891** [comment]
@rgoalcast, did you tried by running as system administrator?
