### ISSUE TITLE
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'conda-forge::numpy-1.13.3-py36_blas_openblas_201'.

### ISSUE THREAD

**Issue by monajalal** [conda/conda#7404]
In CentOS7 I want to install pydot and graphviz for Anaconda Python 3. I get the following error. How should I fix it?

```
$ conda install -c anaconda pydot 
Solving environment: done

## Package Plan ##

  environment location: /scratch/sjn/anaconda

  added / updated specs: 
    - pydot


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2o             |       h20670df_0         3.4 MB  anaconda
    opencv-3.3.1               |   py36h6cbbc71_1        38.9 MB  anaconda
    pydot-1.2.4                |           py36_0          37 KB  anaconda
    certifi-2018.4.16          |           py36_0         142 KB  anaconda
    ffmpeg-3.4                 |       h7264315_0         8.0 MB  anaconda
    mkl_random-1.0.1           |   py36h629b387_0         373 KB  anaconda
    scipy-1.1.0                |   py36hfc37229_0        18.1 MB  anaconda
    conda-4.5.4                |           py36_0         1.0 MB  anaconda
    blas-1.0                   |              mkl           6 KB  anaconda
    ca-certificates-2018.03.07 |                0         124 KB  anaconda
    mkl_fft-1.0.1              |   py36h3010b51_0         140 KB  anaconda
    numpy-1.13.3               |   py36hdbf6ddf_4         3.9 MB  anaconda
    scikit-learn-0.19.1        |   py36h7aa7ec6_0         5.2 MB  anaconda
    ------------------------------------------------------------
                                           Total:        79.4 MB

The following NEW packages will be INSTALLED:

    mkl_fft:         1.0.1-py36h3010b51_0          anaconda   
    mkl_random:      1.0.1-py36h629b387_0          anaconda   
    pydot:           1.2.4-py36_0                  anaconda   

The following packages will be UPDATED:

    ca-certificates: 2018.1.18-0                   conda-forge --> 2018.03.07-0          anaconda
    certifi:         2018.1.18-py36_0              conda-forge --> 2018.4.16-py36_0      anaconda
    conda:           4.5.1-py36_0                  conda-forge --> 4.5.4-py36_0          anaconda
    ffmpeg:          3.2.4-2                       conda-forge --> 3.4-h7264315_0        anaconda
    openssl:         1.0.2n-0                      conda-forge --> 1.0.2o-h20670df_0     anaconda
    scipy:           1.0.1-py36_blas_openblas_200  conda-forge [blas_openblas] --> 1.1.0-py36hfc37229_0  anaconda

The following packages will be DOWNGRADED:

    blas:            1.1-openblas                  conda-forge --> 1.0-mkl               anaconda
    numpy:           1.13.3-py36_blas_openblas_201 conda-forge [blas_openblas] --> 1.13.3-py36hdbf6ddf_4 anaconda
    opencv:          3.4.1-py36_blas_openblas_200  conda-forge [blas_openblas] --> 3.3.1-py36h6cbbc71_1  anaconda
    scikit-learn:    0.19.1-py36_blas_openblas_201 conda-forge [blas_openblas] --> 0.19.1-py36h7aa7ec6_0 anaconda

Proceed ([y]/n)? y


Downloading and Extracting Packages
openssl 1.0.2o############################################################################################################# | 100% 
opencv 3.3.1############################################################################################################### | 100% 
pydot 1.2.4################################################################################################################ | 100% 
certifi 2018.4.16########################################################################################################## | 100% 
ffmpeg 3.4################################################################################################################# | 100% 
mkl_random 1.0.1########################################################################################################### | 100% 
scipy 1.1.0################################################################################################################ | 100% 
conda 4.5.4################################################################################################################ | 100% 
blas 1.0################################################################################################################### | 100% 
ca-certificates 2018.03.07################################################################################################# | 100% 
mkl_fft 1.0.1############################################################################################################## | 100% 
numpy 1.13.3############################################################################################################### | 100% 
scikit-learn 0.19.1######################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'conda-forge::numpy-1.13.3-py36_blas_openblas_201'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied')
```

**Comment by monajalal** [comment]
Solved the problem by the following command:
`$ sudo chown -R jalal /scratch/sjn/anaconda/
`jalal is the username and the path after jalal is the path to username.
and then installing the package.

**Comment by wydadman** [comment]
how about resolving this in windows please?

**Comment by keke2014** [comment]
> how about resolving this in windows please?

right clicked anaconda prompt and run as adminstrator

**Comment by ibobak** [comment]
Unfortunately, on Windows I am getting "permission denied" in Windows. Meanwhile, I've set "Everyone full control" on c:\Anaconda3 folder recursively, so there should be no errors.

Here is the full log:

(tf_cpu) C:\WINDOWS\system32>conda install spyder-kernels
Solving environment: done

## Package Plan ##

  environment location: C:\Anaconda3\envs\tf_cpu

  added / updated specs:
    - spyder-kernels


The following NEW packages will be INSTALLED:

    backcall:         0.1.0-py36_0
    cloudpickle:      0.6.1-py36_0
    colorama:         0.4.1-py36_0
    decorator:        4.3.0-py36_0
    ipykernel:        5.1.0-py36h39e3cac_0
    ipython:          7.2.0-py36h39e3cac_0
    ipython_genutils: 0.2.0-py36h3c5d0ee_0
    jedi:             0.13.2-py36_0
    jupyter_client:   5.2.4-py36_0
    jupyter_core:     4.4.0-py36_0
    libsodium:        1.0.16-h9d3ae62_0
    parso:            0.3.1-py36_0
    pickleshare:      0.7.5-py36_0
    prompt_toolkit:   2.0.7-py36_0
    pygments:         2.3.1-py36_0
    pyzmq:            17.1.2-py36hfa6e2cd_0
    spyder-kernels:   1.0.1-py36_0
    traitlets:        4.3.2-py36h096827d_0
    wcwidth:          0.1.7-py36h3d5aa90_0
    zeromq:           4.2.5-he025d50_1

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'defaults::libsodium-1.0.16-h9d3ae62_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied')

**Comment by vkarumuri-cs** [comment]
Have same issue. Have been every other alternative found in groups.  Nothing worked. Please help me here.

**Comment by Jhsmit** [comment]
For me the issue was resolved by updating to conda v4.6.8 (and administrator prompt but the version was the problem)

**Comment by mkhy19** [comment]
How to solve this problem?
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::conda-4.5.11-py37_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

**Comment by dhinarardhy** [comment]
> How to solve this problem?
> ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::conda-4.5.11-py37_0'.
> PermissionError(13, 'Access is denied')
> Attempting to roll back.

I got the same issue, please help to fix this, I cant install orange text addon. Your solution is very meaningful, thank you very much.

OS Windows 10 64 bit
Anaconda 1.9.7
Orange 3.19

**Comment by SaraLatif99** [comment]
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel-4.10.0-py35_0'
LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\user\Anaconda3\envs\py3-TF2.0\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\user\Anaconda3\envs\py3-TF2.0\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
How can  I resolve this error?
