### ISSUE TITLE
conda not install the latest package

### ISSUE THREAD

**Issue by mingfeima** [conda/conda#7406]
under my anaconda [channel](https://anaconda.org/mingfeima/mkldnn), the available versions for mkldnn is 
```bash
Loading channels: done
# Name                  Version           Build  Channel
mkldnn                   0.12.1               0  mingfeima
mkldnn                   0.13.0               0  mingfeima
mkldnn                   0.14.0               0  mingfeima
``` 
but when i install the library with
```bash
conda install -c mingfeima mkldnn 
```
conda is installing 0.13.0 instead of 0.14.0, like the following.
```bash
Solving environment: done

## Package Plan ##

  environment location: /home/mingfeim/anaconda3

  added / updated specs:
    - mkldnn


The following NEW packages will be INSTALLED:

    mkldnn: 0.13.0-0 mingfeima
```
this is possibly related to [#786](https://github.com/conda/conda/issues/786)

since `mkldnn-v0.13` has dependency on `mkl-v2018.0.1` and `mkldnn-v0.14` has dependency on `mkl-v2018.0.3`, if i have `mkl-v2018.0.1` installed already, it will get `mkldnn-v0.13`.

well, i can install `v0.14` with
```bash
conda install -c mingfeima mkldnn=0.14
```
But i want to make installing `v0.14` the default behavior, if the dependency (mkl) doesn't meet the requirement, i want to have it updated as also. What am i supposed to do here?

**Comment by niranjanreddy891** [comment]
@mingfeima, I guess some dependency package (other package) is the cause for not updating the package you mentioned. It usually happens in order to avoid conflict errors between packages.
