### ISSUE TITLE
anaconda version with 4.4.0+ not forming soft links for shared libraries

### ISSUE THREAD

**Issue by tanishgupta1** [conda/conda#7408]
I am using anaconda version 4.2.0 right now which has by default soft links enabled. When I did a clone from this env then size was around 255 mb. Everything is fine until now.

Then I started working on anaconda 4.4.0. I have marked always_softlink parameter to be true. After this, size of clone is around 1.4 GB which is huge compare to 255 mb. After further debugging, I found out there are many shared libraries and some other files whose symlinks are not getting created even after always_softlink is true. One such example is here :

Clone version of 4.2.9 (which is forming soft symlink)
```
 ls -al  /usr/lib/envss/a-4.2.9.0/lib/python2.7/site-packages/astropy/io/fits/compression.so -> 
lrwxrwxrwx 1 root root  116 Jun 12 08:26 compression.so -> /usr/lib/a-4.2.0-py-2.7.13/pkgs/astropy-1.2.1-np111py27_0/lib/python2.7/site-packages/astropy/io/fits/compression.so
```

Clone version of 4.4.0 (which is not forming soft link)
```
 ls -al /home/ec2-user/envs/soft_clone/lib/python2.7/site-packages/astropy/io/fits/compression.so 
-rwxrwxr-x 1 root root 3781144 Mar 31  2017 /home/ec2-user/envs/soft_clone/lib/python2.7/site-packages/astropy/io/fits/compression.so
```

How can I resolve this symlink issue of shared libraries in new versions of anaconda?

**Comment by mingwandroid** [comment]
It is not possible to symlink shared libraries nor executables due to how ld.so works. Please ignore softlinks altogether. They only exist as a poor backup when hardlinks are not possible. In most installations hardlinks are possible.
