### ISSUE TITLE
pip missing and pyradi could not been installed

### ISSUE THREAD

**Issue by thienvu2vn** [conda/conda#7409]
**I'm submitting a [ ] bug report
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Expected Behavior

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by niranjanreddy891** [comment]
@thienvu2vn, please provide information regarding which o.s, anaconda version and version of pip?
