### ISSUE TITLE
Give better error message when installed package is not in channels

### ISSUE THREAD

**Issue by yelled1** [conda/conda#742]
I prb have bad condarc files or something. I 1st attempted to install ipython, but then I realized that even anaconda was not working.
I originally installed anaconda as root, but used:

> > sudo chown as hyoon:hyoon -R /opt/anaconda

hyoon@BrisBlub:~$ conda update anaconda
Fetching package metadata: .
Error: No packages found matching: anaconda
hyoon@BrisBlub:~$ conda update anaconda
Fetching package metadata: .
Error: No packages found matching: anaconda
hyoon@BrisBlub:~$ conda update ipython
Fetching package metadata: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 196, in install
    assert len(vers_inst) == 1, name
AssertionError: ipython

hyoon@BrisBlub:~$ conda info
Current conda install:
             platform : linux-32
        conda version : 3.4.2
       python version : 2.7.6.final.0
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : http://conda.binstar.org/mutirri/linux-32/
          config file : /home/hyoon/.condarc
    is foreign system : False

**Comment by iamihgam** [comment]
The solution given by asmeurer  really works. 
Mine was  
Fetching package metadata: .
Error: No packages found matching: conda. 
Checked the .condarc file. it was
channels:
-python
then added the two things which later looked as 
channels:
- python
 - mutirri
 - defaults

Now i could use conda update conda. thanks
