### ISSUE TITLE
Writing out environment variable during activate and restoring them during deactivate

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7420]
Would be good if `conda` wrote all of the environment variables to a file before activating, which it would restore after deactivating. This would simplify a lot of things when it comes to writing activation scripts for recipes and may even (largely) eliminate the need for deactivation scripts.

**Comment by msarahan** [comment]
There is no deactivation.  Since the scripts are all done in subprocesses, they are self-contained.

conda_build.sh and its windows equivalent do contain all environment variables already.  I'm not sure what more you want.

**Comment by msarahan** [comment]
ah, sorry.  Got mixed up with conda-build.  My bad.
