### ISSUE TITLE
cygwin mintty PS1 prompt is malformed and conda deactivate throws errors

### ISSUE THREAD

**Issue by kurtu5** [conda/conda#7421]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

When I activate an environment, PS1 is split across two lines and the cursor is at the beginning of the second line, overwriting the prompt.  When trying to deactivate the environment, conda displays errors unless I redefine PS1 to something simple.  It seems that PS1 should be "(condaenv)\r OLDPS1" and not "(condaenv) OLDPS1 \r" and also that deactivate is confused by a complicated prompt.

   I wanted to use cygwin's mintty because its not a windows based shell.  The only thing I did to find the conda instance and set paths appropriately was to source conda.sh at the end of my .bashrc

kurt@BlackRock ~$ tail -n 1 .bashrc
. "C:\Users\kurt\Miniconda3/etc/profile.d/conda.sh"

  If this is too much of an edge case and a detraction from fixing real problems, I'll understand.

### Steps to Reproduce

```
kurt@BlackRock ~$ set | grep ^PS1
PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]$ '

kurt@BlackRock ~$ conda activate nnseries
(nnseries)
CURSOR^CckRock ~$
(nnseries)
set | grep ^PS1~$
PS1=$'(nnseries) \\[\\e]0;\\w\\a\\]\\n\\[\\e[32m\\]\\u@\\h \\[\\e[33m\\]\\w\\[\\e[0m\\]$ \r'
(nnseries)
conda deactivate$
': not a valid identifierULT_ENV
': not a valid identifier
': not a valid identifierIX
': not a valid identifierPT_MODIFIER
': not a valid identifierON_EXE
(nnseries)
PS1="$"ackRock ~$
$conda deactivate
$

```

## Expected Behavior

Not get confused by this greybeard's goofy PS1 prompt format strings.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : nnseries
    active env location : C:\Users\kurt\Miniconda3\envs\nnseries
            shell level : 0
       user config file : E:\cygwin64\home\kurt\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\kurt\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\kurt\Miniconda3\pkgs
                          C:\Users\kurt\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\kurt\Miniconda3\envs
                          C:\Users\kurt\AppData\Local\conda\conda\envs
                          E:\cygwin64\home\kurt\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
no output
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
EnvironmentLocationNotFound: Not a conda environment: C:\Users\kurt\Miniconda3\envs\nnseries

# Not sure about this... perhaps I just need to stick with the Anaconda Prompt rolled out with the Windows 10 install.
```
</p></details>

**Comment by kalefranz** [comment]
I’m not sure where we’ll land for cygwin support in conda for the shell activation stuff. We might get there; we might not. However msys2--and everything that uses it, including Gitbash--is fully supported now.
