### ISSUE TITLE
Can not activate/deactivate conda environment due to cmder lambda character not handled in conda encoder/decoder

### ISSUE THREAD

**Issue by PeterFogh** [conda/conda#7445]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I have updated to conda from version=4.3.29 to version=4.5.4, and I can not activate by conda environment after the update. I'm using cmder bash terminal on windows 10.

When executing the command: `source activate py36_all`, it outputs 
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 98, in main
        return activator_main()
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 584, in main
        print(activator.execute(), end='')
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03bb' in position 130: character maps to <undefined>

`$ C:\Users\FOGH\AppData\Local\Continuum\anaconda3\Scripts\conda shell.posix activate py36_all`

... Followed by the whole environment variables error print out and report submission...
```
Note that cmder have a lambda charater in front of each command. I think it is this lambda charater (i.e. '\u03bb') that is not handled correctly in the encoder/decoder class found in \lib\encodings\cp1252.py.  I have tried to add add the string '\u03bb' to the `decoding_table` tuple list at line 47 in \lib\encodings\cp1252.py, and it results in that the environment can be loaded, but then deactivating the environment with `source deactivate` the error occurs again, with the following error:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 98, in main
        return activator_main()
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 584, in main
        print(activator.execute(), end='')
      File "C:\Users\FOGH\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\x8d' in position 349: character maps to <undefined>

... Again followed by the whole environment variables error print out and report submission...

```
where  '\x8d' is the encode value of the next element in  `decoding_table` after where i have added  '\u03bb'. i.e. 
```
    '\u03bb'   #
    '\ufffe'   #  0x8D -> UNDEFINED
```

Do any one know how to add the lambda charater to the encoder/decoder class, such that i can activate and deactivate the conda environment in my cmder bash terminal?

## Expected Behavior

Well, I should be able to activate and deactivate the conda environment.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\FOGH\.condarc
 populated config files : C:\Users\FOGH\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\FOGH\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\FOGH\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\FOGH\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\FOGH\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\FOGH\AppData\Local\conda\conda\envs
                          C:\Users\FOGH\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\FOGH\.condarc <==
channels:
  - defaults
  - conda-forge
```
</p></details>

**Comment by mingwandroid** [comment]
This sounds like a bug cmder needs to fix!

**Comment by PeterFogh** [comment]
Here is a better fix.

Make the newer versions of conda environments able to be activated in bash terminal as it can not en/decode the cmder lambda character.
Remove the lambda character in `cmder\vendor\git-for-windows\etc\profile.d\git-prompt.sh` at line at line 36.
```
PS1="$PS1"''                 # prompt: always "λ " 
```

**Comment by edmundhighcock** [comment]
Hi @PeterFogh, thanks very much for your post, your suggestion works! 

In response to @mingwandroid, if the lambda is correctly encoded in the cmder prompt, shouldn't conda be able to handle it? Or am I missing somehing?

**Comment by mingwandroid** [comment]
It should handle it, yes. Definitely a bug.

**Comment by m946107011** [comment]
cant anyone help.....
i already tried some solution below ...
but still cant activate my enviroment
thanks ~


(base)
mlsh3@LAPTOP-3KD88OV6 MINGW64 /d/Storage//碩一下/社群
conda activate normal

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Program_Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "D:\Program_Files\Anaconda3\lib\site-packages\conda\activate.py", line 1093, in main
        print(activator.execute(), end='')
    UnicodeEncodeError: 'cp950' codec can't encode character '\xaa' in position 1722: illegal multibyte sequence

`$ D:\Program_Files\Anaconda3\Scripts\conda-script.py shell.posix activate normal`

  environment variables:
             ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program
                          Files\Git\usr\share\aclocal
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:/Program_Files/Anaconda3/Scripts/conda.exe
             CONDA_PREFIX=D:\Program_Files\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:/Program_Files/Anaconda3/python.exe
               CONDA_ROOT=D:\Program_Files\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                  EXEPATH=C:\Program Files\Git
                 HOMEPATH=\Users\mlsh3
                 INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program
                          Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program
                          Files\Git\share\info
                  MANPATH=C:\Program Files\Git\mingw64\local\man;C:\Program
                          Files\Git\mingw64\share\man;C:\Program
                          Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program
                          Files\Git\usr\man;C:\Program Files\Git\share\man
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
            ORIGINAL_PATH=C:\Program Files\Git\mingw64\bin;C:\Program
                          Files\Git\usr\bin;C:\Users\mlsh3\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                          Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windo
                          ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0
                          ;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Windows\syste
                          m32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPow
                          erShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program
                          Files\Intel\WiFi\bin;C:\Program Files\Common
                          Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\cudnn_10_0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUD
                          A\v10.0\bin;D:\Program_Files;C:\Users\mlsh3\AppData\Local\Microsoft\Wi
                          ndowsApps;D:\Storage\▒L▒|▒s\▒Ӥ@▒U\Anaconda3\Library\bin;...\Anaconda3\Scrip
                          ts
                     PATH=D:\Program_Files\Anaconda3;D:\Program_Files\Anaconda3\Library\mingw-w6
                          4\bin;D:\Program_Files\Anaconda3\Library\usr\bin;D:\Program_Files\Anac
                          onda3\Library\bin;D:\Program_Files\Anaconda3\Scripts;D:\Program_Files\
                          Anaconda3\bin;D:\Program_Files\Anaconda3;D:\Program_Files\Anaconda3\Li
                          brary\mingw-w64\bin;D:\Program_Files\Anaconda3\Library\usr\bin;D:\Prog
                          ram_Files\Anaconda3\Library\bin;D:\Program_Files\Anaconda3\Scripts;D:\
                          Program_Files\Anaconda3\bin;D:\Program_Files\Anaconda3\Scripts\condabi
                          n;C:\Users\mlsh3\bin;C:\Program Files\Git\mingw64\bin;C:\Program
                          Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program
                          Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program
                          Files\Git\usr\bin;C:\Users\mlsh3\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                          Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windo
                          ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0
                          ;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Windows\syste
                          m32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPow
                          erShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program
                          Files\Intel\WiFi\bin;C:\Program Files\Common
                          Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\cudnn_10_0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUD
                          A\v10.0\bin;D:\Program_Files;C:\Users\mlsh3\AppData\Local\Microsoft\Wi
                          ndowsApps;D:\Storage\\xaaL\xb6|▒Ps\\xba\u04e4@\xa4U\Anaconda3\Library\bin;...\Anaconda3\
                          Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\
                          usr\bin\core_perl=;D:\Program_Files\Anaconda3\;D:\Program_Files\Anacon
                          da3\Scripts\
          PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program
                          Files\Git\mingw64\share\pkgconfig
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\Program_Files\Anaconda3
            shell level : 1
       user config file : C:\Users\mlsh3\.condarc
 populated config files : C:\Users\mlsh3\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __cuda=11.0
       base environment : D:\Program_Files\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Program_Files\Anaconda3\pkgs
                          C:\Users\mlsh3\.conda\pkgs
                          C:\Users\mlsh3\AppData\Local\conda\conda\pkgs
       envs directories : D:\Program_Files\Anaconda3\envs
                          C:\Users\mlsh3\.conda\envs
                          C:\Users\mlsh3\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

(base)
mlsh3@LAPTOP-3KD88OV6 MINGW64 /d/Storage/ /碩一下/社群

**Comment by agutierad08** [comment]
Setting PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO environment variables to UTF-8 solved my issue. I am using Git bash terminal in windows 10.

**Comment by coding-famer** [comment]
> Setting PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO environment variables to UTF-8 solved my issue. I am using Git bash terminal in windows 10.

@agutierad08 sorry but may I know how can I set PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO to UTF-8?
