### ISSUE TITLE
Failed to upgrade to Python 3.3

### ISSUE THREAD

**Issue by bittware** [conda/conda#745]
As I don't know the user/password of company proxy, I have to download every package that needed by Python 3.3 to local directory, i.e. C:\Anaconda\download\win-64 one by one (73 .bz2 files in total).
I changed channels setting to file:///C:/Anaconda/download/ in .condarc file.
But following things occurred.
C:\Anaconda>conda create -n py33 python=3.3 anaconda
Error: unknown host: file:///C:/Anaconda/download/win-64/
Error: No packages found matching: python 3.3*

My setup is
C:\Anaconda>conda info
Current conda install:

platform : win-64
conda version : 3.0.6
python version : 2.7.6.final.0
root environment : C:\Anaconda  (writable)
default environment : C:\Anaconda
envs directories : C:\Anaconda\envs
package cache : C:\Anaconda\pkgs
channel URLs : file:///C:/Anaconda/download/win-64/
config file : C:\Anaconda\.condarc
is foreign system : False

**Comment by soapy1** [comment]
@bittware has your issue been resolved, can this issues be closed?
