### ISSUE TITLE
Windows 10, can't use activate in git bash

### ISSUE THREAD

**Issue by bbiney1** [conda/conda#7458]
I see that past issues have been made for the same problem, but I can't quite figure out what the solution is in my case.
I installed python 3.6 via miniconda, then I created a conda virtual env called "py2.7 with python-version=2.7. I can run this in the anaconda prompt smoothly.
But I cannot use activate in the git bash prompt. Git bash only returns the same address without the env_name in parentheses, and the python version remains at 3.6 no matter what I do

I've seen other solutions, but nothing that I enter in my command prompt is getting me any results or changes in behavior.

`(base) C:\Users\biney>conda info

     active environment : base
    active env location : C:\Users\biney\Miniconda3
            shell level : 1
       user config file : C:\Users\biney\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\biney\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\biney\Miniconda3\pkgs
                          C:\Users\biney\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\biney\Miniconda3\envs
                          C:\Users\biney\AppData\Local\conda\conda\envs
                          C:\Users\biney\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False`

**Comment by LexSong** [comment]
Are you typing `activate py2.7` or `source activate py2.7`?

**Comment by kalefranz** [comment]
Must use `source activate` or `conda activate`.
