### ISSUE TITLE
make conda work with msysgit terminal or cygwin

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#747]
The bash shell provided with msysgit (http://msysgit.github.io) or with Cygwin are very useful for people on Windows looking for something more useful than cmd.exe or PowerShell.

However, it appears that at least some of the standard conda commands won't work in this environment (probably not surprisingly), e.g. "activate", since .bat file modification of cmd.exe environment is doubtless different from what a bash shell expects.

It would be nice if this worked.  Perhaps just bundling msysgit with Anaconda for Windows would be a good way to provide a "full solution".

**Comment by ijstokes** [comment]
@csoja and @ilanschnell I've had some discussions with @stephenakearns and @mrduane about the importance of strong Windows support in Anaconda.  I think we're on the same page with @teoliphant @pzwang, MattH and MicheleC.  Anaconda (and by implication conda) working wonderfully perfectly in Windows, using Powershell, cygwin, and msysgit (or similar) would really be appreciated.

**Comment by dkoppstein** [comment]
+1

**Comment by nickeubank** [comment]
+1

**Comment by msarahan** [comment]
This functionality should be present in master as it stands now.  We do not have a current release with this yet.  It is slated for conda 4.1.

**Comment by nickeubank** [comment]
@msarahan Oh great, thank! Do you happen to know if there are any guides to building anaconda from source around?

**Comment by nickeubank** [comment]
@msarahan Oh, I see: it's pure python! Ok, I can a python build. Thanks again!

**Comment by ezk84** [comment]
Did this functionality make it into conda 4.1 then? I have 4.3 and `conda activate` inside msysgit screws up my PATH so that none of my normal shell utilities like grep, etc work.

**Comment by nirvana-msu** [comment]
I have exactly same issue as @ezk84. When I try to activate root environment with `source activate root`  it screws up PATH which breaks the shell. I'm using Git Bash/MINGW64 on Windows 7 x64:

```sh
$ source activate root
bash: sed: command not found
bash: grep: command not found
bash: grep: command not found
(root)

$ source activate custom-env
bash: dirname: command not found
bash: uname: command not found
bash: /conda: No such file or directory
(root)
```

**Comment by bitseer** [comment]
+1, I'm having the same problem as @nirvana-msu and I'm using cygwin on Windows 10 x64.

**Comment by mikofski** [comment]
Have different but still weird issues with Anaconda in msys bash inside ConEmu.

* Colors don't work in IPython

* Even after `source deactivate`, my shell's `$PATH` still has Anaconda on it.

Thanks!

**Comment by rygo6** [comment]
+1 Really wish I could use anaconda through git bash terminal.

**Comment by mikofski** [comment]
I added the following scripts to the bin folder of my bash shell:

```bash
#!/usr/bin/bash
source $LOCALAPPDATA/Continuum/Anaconda3/Scripts/activate "$@"
```

save this as `bin/conda-activate`

I also made a path cleaner, saved in `bin/rm-anaconda-paths.py`:

```python
import os, sys
import logging
logging.basicConfig()
LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.DEBUG)
ANACONDA_LIB_PATH = os.path.expandvars(os.path.join('$LOCALAPPDATA', 'Continuum', 'Anaconda3', 'Library', 'bin')).lower()
LOGGER.debug(ANACONDA_LIB_PATH)
try:
        sys.stdout.write(':'.join('/' + p[0].lower() + p[2:] for p in os.environ['PATH'].split(os.pathsep) if not p.lower().endswith(ANACONDA_LIB_PATH[2:])).replace('\\', '/'))
except Exception as err:
        LOGGER.error(err)
        sys.stdout.write('$PATH')
        sys.exit(-1)
else:
    sys.exit(0)
```
which I use instead of deactivate here:

```bash
#!/usr/bin/bash
source $LOCALAPPDATA/Continuum/anaconda3/Scripts/deactivate
export PATH=`$LOCALAPPDATA/Continuum/anaconda3/python.exe ~/bin/rm-anaconda-paths.py`
```
saved as `bin/conda-deactivate`

Never use in a conda-env that has any of the msys channel packages, or path clash hell will ensue. Also, after installing with conda in bash, I have an issue that suddenly bash can't find it anymore and I have to deactivate and re-activate again. 😦

**Comment by kalefranz** [comment]
Conda 4.4 should now be compatible with hot bash. Is anybody actually having problems with recent versions of conda 4.4?

**Comment by mikofski** [comment]
I tried to update, but it broke my anaconda, so I downgraded. I'm using 4.3.31 now:

    anaconda: 5.0.1-py36h8316230_2 --> custom-py36h363777c_0
    conda:    4.3.31-py36_0        --> 4.4.8-py36_0
    pycosat:  0.6.2-py36hf17546d_1 --> 0.6.3-py36h413d8a4_0

see [this comment](https://github.com/conda/conda/issues/6601#issuecomment-354514924)

**Comment by rsheftel** [comment]
I found this thread when trying to get Cygwin working for conda environment (conda v4.5) when I found in the changelog for v4.4 the answer on how to get it to work which solved the problem for me. Oddly the official documentation has not been updated with this:

https://github.com/conda/conda/blob/master/CHANGELOG.md#recommended-change-to-enable-conda-in-your-shell

**Comment by meeotch** [comment]
I can confirm that conda and cygwin still can't play nicely as of the most recent versions of each.  When I attempted, I got the results described here:  https://github.com/conda/conda/issues/7742

The fix referenced by rsheftel above did not fix things for me.

**Comment by mingwandroid** [comment]
Conda well never work very well on Cygwin because Cygwin does not care about interoperation with 'native' Windows software. In fact this is the reason msys was created. I wouldn't recommend using that now-a-days since MSYS2 is available and actually maintained.

If you want basic Cygwin support please submit PRs for this. Conda does support MSYS2 and I will endeavor to make sure this support is maintained as best I can. This MSYS2 support shows what would need to be done to support Cygwin.
