### ISSUE TITLE
Duplicate environments in conda env list

### ISSUE THREAD

**Issue by LexSong** [conda/conda#7493]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

In environment which's paths are not case sensitive, like Windows. Sometimes there may be duplicate environment prefixes in `~/.conda/environments.txt`.

I got a case like this:

    > conda env list
    # conda environments:
    #
    base                  *  C:\Miniconda3
                             c:\Miniconda3
    
    # notice the case differences

I can resolve this with manually fixing the `environments.txt`. However I think it's best to prevent it happening from beginning.

**Comment by kalefranz** [comment]
This is more a feature request than a bug report. Deduping these will incur a performance penalty. I'm not sure it's worth it. Will consider it in the future though.
