### ISSUE TITLE
Errors in History spec parsing with conda 4.5.5

### ISSUE THREAD

**Issue by rmooser** [conda/conda#7494]
Cond 4.5.5 has a problem:

P:\>conda update conda
Solving environment: failed

ERROR REPORT 

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __
call__
        return func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main

        exit_code = do_call(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77
, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 14, i
n execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 235, in i
nstall
        force_reinstall=context.force,
      File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 506, in so
lve_for_transaction
        force_remove, force_reinstall)
      File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 439, in so
lve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned
, force_remove)
      File "C:\Anaconda3\lib\site-packages\conda\core\solve.py", line 148, in so
lve_final_state
        specs_from_history_map = History(self.prefix).get_requested_specs_map()
      File "C:\Anaconda3\lib\site-packages\conda\history.py", line 230, in get_r
equested_specs_map
        for request in self.get_user_requests():
      File "C:\Anaconda3\lib\site-packages\conda\history.py", line 215, in get_u
ser_requests
        comment_items = self._parse_comment_line(line)
      File "C:\Anaconda3\lib\site-packages\conda\history.py", line 191, in _pars
e_comment_line
        specs = History._parse_old_format_specs_string(specs_string)
      File "C:\Anaconda3\lib\site-packages\conda\history.py", line 158, in _pars
e_old_format_specs_string
        specs[-1] = ','.join([specs[-1], spec])
    IndexError: list index out of range

`$ C:\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Anaconda3
                 HOMEPATH=\
                     PATH=C:\Anaconda3\Library\bin;C:\Program Files (x86)\Common                          Files\Oracle\Java\javapath;C:\Program Files\ImageMagic
k-7.0.7-Q16;C:\A
                          naconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anacond
a3\Library\usr\b
                          in;C:\Anaconda3\Library\bin;C:\Anaconda3\Scripts;C:\Pr
ogram
                          Files\ImageMagick-7.0.6-Q16;C:\Program Files
                          (x86)\ImageMagick-7.0.5-Q16;C:\Program Files
                          (x86)\ImageMagick-7.0.4-Q16;C:\Program Files
                          (x86)\ImageMagick-7.0.3-Q16;C:\Program Files (x86)\Ima
geMagick-6.8.6-Q
                          16;C:\Windows\system32;C:\Windows;C:\Windows\System32\
Wbem;C:\Windows\
                          System32\WindowsPowerShell\v1.0\;C:\Program Files (x86
)\QS QualitySoft
                          GmbH\QS-Barcode OCX 4.9;C:\Windows\System32\WindowsPow
erShell\v1.0\;C:
                          \Windows\System32\WindowsPowerShell\v1.0\;C:\Program F
iles\MiKTeX 2.9\
                          miktex\bin\x64\;C:\Windows\System32\WindowsPowerShell\
v1.0\;C:\Program
                          Files (x86)\Common Files\Microsoft Shared\OFFICE15
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:
\Program
                          Files\Microsoft Application Virtualization\Client\
               PYTHONPATH=G:\QPS\11-Software\03-Python\01-QPS
                          FRAMEWORK\03-STRATEGIES;G:\QPS\10-Sandbox\02-Mitarbeit
er\RMoo\01 - QPS
                          FRAMEWORK\11-STRATEGIES;G:\QPS\10-Sandbox\02-Mitarbeit
er\RMoo\01 - QPS
                          FRAMEWORK\01-CORE
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\username\.condarc
 populated config files : C:\Anaconda3\.condarc
                          C:\Users\username\.condarc
          conda version : 4.5.5
    conda-build version : not installed
         python version : 3.6.2.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\rmoo\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\rmoo\AppData\Local\conda\conda\envs
                          C:\Users\rmoo\.conda\envs
               platform : win-64
             user-agent : conda/4.5.5 requests/2.14.2 CPython/3.6.2 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

The problem seems to be the line
specs[-1] = ','.join([specs[-1], spec]) in history.py, which fails if specs = []

**Comment by kalefranz** [comment]
At your command prompt, can you please provide the output of

    type C:\Anaconda3\conda-meta\history

or alternately just attach to this issue the file `C:\Anaconda3\conda-meta\history`

**Comment by kalefranz** [comment]
The PR #7489 by @speleo3 may resolve this issue.  It also may not.  #7500, targeted at 4.5.x, should be the definitive solution.

**Comment by kalefranz** [comment]
Output of ‘conda info’?

**Comment by BEpresent** [comment]
conda info:
```

     active environment : None
       user config file : /home/username/.condarc
 populated config files : /home/username/.condarc
          conda version : 4.5.5
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /home/username/miniconda3  (writable)
           channel URLs : http://conda.anaconda.org/gurobi/linux-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/username/miniconda3/pkgs
                          /home/username/.conda/pkgs
       envs directories : /home/username/miniconda3/envs
                          /home/username/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/3.6.6 Linux/4.14.54-1-MANJARO manjaro/17.1.11 glibc/2.27
                UID:GID : 1000:100
             netrc file : None
           offline mode : False

[
```

Thanks!
