### ISSUE TITLE
Command line option to suppress start menu icon installation in windows

### ISSUE THREAD

**Issue by tonigi** [conda/conda#7507]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

I would like to propose a command line option for the Windows Miniconda installer that avoids the `menuinst` step. This is to enable non-user-visible installations, whose icons otherwise clobber the "main" miniconda start menu shortcut. 

In principle, it would be consistent with the spirit of the existing /NoRegistry . (Actually, in my opinion, not installing the icon should be default in the NoRegistry case).

**Comment by msarahan** [comment]
Conda already had this as a cli flag. For the installer itself, you should move this issue to the github.com/continuumio/anaconda-issues issue tracker.

**Comment by kalefranz** [comment]
I believe the flag is `--no-shortcuts`

**Comment by RoyiAvital** [comment]
@kalefranz, Where are all the flags documented?

**Comment by RoyiAvital** [comment]
I use `--no-shortcuts /NoRegistry=1 /AddToPath=0 /RegisterPython=0` and still gets the installation to register:

![image](https://user-images.githubusercontent.com/7347975/117516361-94719800-afa1-11eb-9f08-6ad51dcd4e32.png)

Any way to prevent this or any registration to the system / registry?
