### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by rsheftel** [conda/conda#7527]
The changelog for v4.4 (https://github.com/conda/conda/blob/master/CHANGELOG.md#recommended-change-to-enable-conda-in-your-shell) recommends using "conda activate" and "conda deactivate" for Cygwin or Linux bash shells.

But the online documentation (https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment) still recommends the old "source activate" and "source deactivate"

**Comment by E3V3A** [comment]
more over the "activate" command is not explained what it does or supposed to do. 
I ran, `./activate` (from cygwin in `../Scripts` directory.) Something ran, but without any output what-so-ever. In fact there should be something mentioning that you also need to add a name to the environment, i guess.
