### ISSUE TITLE
keyerror in the command: conda create --prefix py3.5torch --clone root

### ISSUE THREAD

**Issue by zorrocai** [conda/conda#7530]
I use the command:conda create --prefix py3.5torch --clone root 
then it comes the KeyError:0
the traceback is:
Traceback (most recent call last):
  File "/home/huayue/anaconda2/envs/pytorch/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 87, in clone
    index_args=index_args)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "/home/huayue/anaconda2/lib/python2.7/site-packages/conda/config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0

**Comment by nehaljwani** [comment]
@zorrocai Could you please share the output for:
```
conda list -n root
conda info
```

**Comment by zorrocai** [comment]
the ouput for conda list -n root:
# packages in environment at /home/huayue/anaconda2:
#
_nb_ext_conf              0.2.0                    py27_0  
alabaster                 0.7.8                    py27_0  
anaconda                  4.1.1               np111py27_0  
anaconda-client           1.4.0                    py27_0  
anaconda-navigator        1.2.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astropy                   1.2.1               np111py27_0  
babel                     2.3.3                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.0                   py27_0  
boto                      2.40.0                   py27_0  
bottleneck                1.1.0               np111py27_0  
cairo                     1.12.18                       6  
cdecimal                  2.3                      py27_2  
cffi                      1.6.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.6                      py27_0  
cloudpickle               0.2.1                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.1.6                    py27_0  
conda-build               1.21.3                   py27_0  
conda-env                 2.5.1                    py27_0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0b2                  py27_1  
contextlib2               0.5.3                    py27_0  
cryptography              1.4                      py27_0  
curl                      7.49.0                        0  
cycler                    0.10.0                   py27_0  
cython                    0.24                     py27_0  
cytoolz                   0.8.0                    py27_0  
dask                      0.10.0                   py27_0  
datashape                 0.5.2                    py27_0  
decorator                 4.0.10                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.12                     py27_2  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
flask                     0.11.1                   py27_0  
flask-cors                2.1.2                    py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.1                    py27_0  
greenlet                  0.4.10                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_1  
hdf5                      1.8.16                        0  
heapdict                  1.0.0                    py27_1  
idna                      2.1                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.16                   py27_0  
ipykernel                 4.3.1                    py27_0  
ipython                   4.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_1  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jpeg                      8d                            1  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.3.0                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.11.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.0                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np111py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_2  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.8                    py27_0  
nb_anacondacloud          1.1.0                    py27_0  
nb_conda                  1.1.0                    py27_0  
nb_conda_kernels          1.0.3                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.0.1                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.1                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.2.1                    py27_0  
numba                     0.26.0              np111py27_0  
numexpr                   2.6.0               np111py27_0  
numpy                     1.11.1                   py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py27_0  
partd                     0.3.4                    py27_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.2                    py27_0  
pillow                    3.2.0                    py27_1  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
ply                       3.8                      py27_0  
psutil                    4.3.0                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.14                     py27_1  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_0  
pyflakes                  1.2.3                    py27_0  
pygments                  2.1.3                    py27_0  
pyopenssl                 0.16.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_3  
pytables                  3.2.2               np111py27_4  
pytest                    2.9.2                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.4                   py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     15.2.0                   py27_1  
qt                        4.8.7                         3  
qtconsole                 4.2.1                    py27_0  
qtpy                      1.0.2                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.10.0                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.7                   py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.17.1              np111py27_1  
setuptools                23.0.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.4.1                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_0  
spyder                    2.3.9                    py27_0  
sqlalchemy                1.0.13                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py27_0  
tornado                   4.3                      py27_1  
traitlets                 4.2.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
werkzeug                  0.11.10                  py27_0  
wheel                     0.29.0                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.2                    py27_0  
xlwt                      1.1.2                    py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  

the output for conda info:
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/huayue/anaconda2  (writable)
  default environment : /home/huayue/anaconda2
     envs directories : /home/huayue/anaconda2/envs
        package cache : /home/huayue/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by mbargull** [comment]
You're using a very dated version of `conda`. Please try to run `conda update conda` to get a more recent one.

**Comment by zorrocai** [comment]
Thanks,it works. @mbargull

**Comment by mbargull** [comment]
Great! You're welcome
