### ISSUE TITLE
conda can not get python 3.7,  will not run conda create -n py37 python=3.7 anaconda

### ISSUE THREAD

**Issue by richkatz** [conda/conda#7541]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by richkatz** [comment]
Current behavior:  I have tried to run this command for several weeks.  At first I was told that all  the dependencies were not there.  Is this still the case? 

The last time I tried this it created a virtual env with python 3.6.6 for some reason.

Today I ran the command conda create -n py37 python=3.7 anaconda  again.  I got a large number of conflicts.   A huge list of UnsatisfiableError: The following specifications were found to be in conflict:

I ran conda update --all

And tried again.  Now I have a shorter list. 

C:\Users\richkatz>conda create -n py37 python=3.7 anaconda
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> chardet[version='>=3.0.2,<3.1.0']
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> enum34 -> ordereddict
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> ipaddress
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> urllib3[version='>=1.21.1,<1.23'] -> cryptography[version='>=1.3.4'] -> pyasn1[version='>=0.1.8']
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> urllib3[version='>=1.21.1,<1.23'] -> pyopenssl[version='>=0.14']
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> bokeh -> requests -> urllib3[version='>=1.21.1,<1.23'] -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> win_inet_pton
  - anaconda -> blaze==0.9.1=py27_0 -> odo -> dask[version='>=0.11.1'] -> distributed[version='>=1.20.0'] -> msgpack-python
  - anaconda -> cachecontrol==0.12.3=py35h3f82863_0
  - anaconda -> cffi==1.5.2=py27_0
  - anaconda -> distlib==0.2.5=py35h12c42d7_0
  - anaconda -> distribute==0.6.45=py26_0
  - anaconda -> ipywidgets==4.1.1=py27_0 -> notebook -> nbconvert -> bleach -> html5lib[version='>=0.99999999'] -> webencodings
  - anaconda -> lockfile==0.12.2=py35h667c6d9_0
  - anaconda -> progress==1.3=py35ha84af61_0
  - anaconda -> sockjs-tornado==1.0.1=py27_0 -> python=2.7
  - anaconda -> wheel==0.29.0=py27_0
  - anaconda -> wincertstore==0.2=py35hfebbdb8_0
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.

conda -V
conda 4.5.8


 What do I do?  

Thanks!

Cheers,

Rich Katz

**Comment by mbargull** [comment]
If you want to use the `anaconda` package, you'll have to wait a little bit since not all packages pulled in by `anaconda` have been build for `python 3.7`.
(PS: issues like this one are better fit for https://github.com/continuumio/anaconda-issues/)
