### ISSUE TITLE
Re-creating conda env with custom channels results in HTTP error (perhaps needlessly?)

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [conda/conda#7554]
**I'm submitting a...**
  - [X] bug report
  - [X] feature request

## Current Behavior

I created an environment on one machine and wanted to replicate that environment. On the original machine, I exported the environment details using: `conda env export > my-env.yml`.

On the new machine, running `conda env create -n my-env-copy --file my-env.yml` resulted in at HTTP error (as was the case in #7535):

```shell
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.binstar.org/bashtage/linux-64/repodata.json>
```

### Steps to Reproduce

Create a new environment from an exported yaml file, which includes an http address under the channels sub-section.

## Expected Behavior

The channel should not only be searched for via the given http address in the `env.yml` file, but also perhaps via pure channel name, which I guess can often be parsed from the http address.

In my case, the http was: `- https://conda.binstar.org/bashtage` 
I changed the same line in the yaml file to `bashtage` - which then worked as expected.

Could a fix/patch be as simple as something like:

```python
channel = ''https://conda.binstar.org/bashtage"   # from yaml-reader
try:
    # whatever normally happens:
except CondaHTTPError as e:
    channel_name = channel.split('/')[-1]
    # overwrite the variable that is passed to the usual method in the try-block above
    # ... try again, which would either work or raise the same CondaHTTPError
    # and we don't catch it the second time around!
finally:
    # in case of success using name, and we want to keep users informed...
    warnings.warn('A message alerting user that channel name was used instead of http address')
```

Alternatively, all this could be performed via the export process, while _creating_ the yaml file.
I assume the http address was chosen because it should be static/more robust?

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

This was creating a new environment, so it not specific to any environment.

```
nicholas@mitchell:~$ conda info

     active environment : None
       user config file : /home/nicholas/.condarc
 populated config files : 
          conda version : 4.5.5
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /home/nicholas/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/nicholas/anaconda3/pkgs
                          /home/nicholas/.conda/pkgs
       envs directories : /home/nicholas/anaconda3/envs
                          /home/nicholas/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.18.4 CPython/3.6.3 Linux/4.15.0-24-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

**Comment by HarveySummers** [comment]
Note this appears to be the same as https://github.com/conda/conda/issues/7550

**Comment by nehaljwani** [comment]
IIUC, just using bashtage translates to https://conda.anaconda.org/bashtage . So, try out the following:

Replace https://conda.binstar.org/bashtage with https://conda.anaconda.org/bashtage. And see if you still get the HTTP 000 failure.

If you don't, and everything works, then it means that your are behind an intercept proxy/corporate firewall that has whitelisted conda.anaconda.org or *.anaconda.org, but not *.binstar.org

Also, the certificate for https://conda.binstar.org has expired, so it might be also be the case that whatever is intercepting the connections in between, is trying to contact conda.binstar.org over https, fails and then returns a 000 status to conda.

**Comment by kalefranz** [comment]
I believe we have no resolved the network issues related to conda.binstar.org.
