### ISSUE TITLE
conda env is missing /bin folder

### ISSUE THREAD

**Issue by chanansh** [conda/conda#7555]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
new environment fails to create a /bin folder.

### Steps to Reproduce
```
hanans@Macbook-HananS ~/a/bin> conda create -n my_env
Solving environment: done


  environment location: /Users/hanans/anaconda3/envs/my_env


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate my_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

hanans@Macbook-HananS ~/a/bin> conda activate my_env
set: Warning: $PATH entry "/Users/hanans/anaconda3/envs/my_env/bin" is not valid (No such file or directory)
```

## Expected Behavior
new environment should have a bin folder.

## Environment Information
```
     active environment : kfactor
    active env location : /Users/hanans/anaconda3/envs/my_env
            shell level : 1
       user config file : /Users/hanans/.condarc
 populated config files : /Users/hanans/.condarc
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.6.6.final.0
       base environment : /Users/hanans/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/hanans/anaconda3/pkgs
                          /Users/hanans/.conda/pkgs
       envs directories : /Users/hanans/anaconda3/envs
                          /Users/hanans/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.6 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 235190340:1310284612
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/hanans/.condarc <==
ssl_verify: False
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/hanans/anaconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by nehaljwani** [comment]
Are you using the fish shell? Seems like a duplicate of https://github.com/conda/conda/issues/7271

**Comment by bit-scientist** [comment]
@sometimescasey Hi I did like you suggested, but still there is no bin folder. I should include bin/python folder as an interpreter in pycharm. Do you have any other solution?

**Comment by sometimescasey** [comment]
@bit-scientist can you copy-paste all of your commands and console output? feel free to put in a Github Gist if you don't want to put it here.

**Comment by bit-scientist** [comment]
@sometimescasey I think I resolved it just by referring python.exe in my envs/envname/.  I forgot to come back to this point

**Comment by fatemebfg** [comment]
> @sometimescasey I think I resolved it just by referring to python.exe in my envs/envname/. I forgot to come back to this point

i actually did this but i still get error when running my project,
the error is as below:
  File "C:\Users\Green\Anaconda3\lib\tokenize.py", line 452, in open
    buffer = _builtin_open(filename, 'rb')
PermissionError: [Errno 13] Permission denied: 'F:/arshad/coding/thesi

**Comment by hanan-vian** [comment]
> conda install -n my_env python

this actually does *NOT* create a python bin in my env directory. It still points to the root python.

**Comment by adjanni** [comment]
I am having the same issue as @hanan-vian and @fatemebfg . In fact, I created my conda env as:
`conda create -n my_env python=3.6` but there is no bin file.

**Comment by DamonWz** [comment]
I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8`    2. `conda activate learn`  3.  `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much!

**Comment by subi-ks** [comment]
> `conda create -n my_env` just creates an empty conda environment with nothing in it.
> 
> To have the bin folder in my_env, you have to either do `conda create -n my_env python` to install python to the env when you create it, or do `conda install -n my_env python` to add Python to your already existing environment. This will create your bin folder along with all the other folders and packages.


This didn't work out for me. Still, the bin folder is missing.

**Comment by Sansui-hsy** [comment]
> I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8` 2. `conda activate learn` 3. `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much! Is it related to wsl?

did you solved it？i meet the same question

**Comment by ammar-gilani** [comment]
> > I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8` 2. `conda activate learn` 3. `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much! Is it related to wsl?
> 
> did you solved it？i meet the same question

activate the env, then use conda to install a package for it; worked for me.

**Comment by Sansui-hsy** [comment]
> > I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8` 2. `conda activate learn` 3. `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much! Is it related to wsl?
> 
> did you solved it？i meet the same question

no，but there are a sugguest in following,you can try. used to install many package in my create env ,there is still nothing in bin.finally i only use windows. if you work by using the suggestion, please told me.

**Comment by Sansui-hsy** [comment]
> > > I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8` 2. `conda activate learn` 3. `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much! Is it related to wsl?
> > 
> > 
> > did you solved it？i meet the same question
> 
> activate the env, then use conda to install a package for it; worked for me.

when create env with python=3.8,  there will be packges

**Comment by Two222** [comment]
> I am having the same issue as @hanan-vian and @fatemebfg . In fact, I created my conda env as: `conda create -n my_env python=3.6` but there is no bin file.

did you solve this problem？

**Comment by Two222** [comment]
> > > I have a similar problem. here are my conda commonds: 1. `conda create --name learn python=3.8` 2. `conda activate learn` 3. `which python` -> `/home/damon/miniconda3/envs/learn/bin/python`. Then I want to add a interpreter using the conda environment created above, but the /home/damon/miniconda3/envs/learn/bin folder is empty. Do you have any solution to solve it? Thank you very much! Is it related to wsl?
> > 
> > 
> > did you solved it？i meet the same question
> 
> activate the env, then use conda to install a package for it; worked for me.

it doesnt work for me

**Comment by yola798** [comment]
I was searching this problem for adding interpreters in pycharm. When adding conda environment, I found there was no change to the interpreter blanket. However,I then tried to add system interpreter, and it was added successfully and the environment seems to work well with no bin folder. I am wondering if missing bin folder might not be the problem?
<img width="801" alt="image" src="https://user-images.githubusercontent.com/67108592/216816365-4a071d9d-6ddc-488b-9093-9cd7c0e1b709.png">

**Comment by tgarc** [comment]
Environment so far has worked fine without a bin folder, until I installed rpyc which has the weird behavior of running it's CLI scripts using `/bin/python`. None of the above solutions worked for me to create the bin subfolder in my environment.
