### ISSUE TITLE
Adding package markupsafe in the setup packages that comes with Anaconda.

### ISSUE THREAD

**Issue by guinslym** [conda/conda#7566]
Hi this is a recommendation.

I would like to know if we can add the markupsafe package in the list of packages that comes in the setup of anaconda. Because Anaconda do comes with Flask but when I try to run a code, I get an error.

    python api.py # basic flask app that return a text sentence
    ...
    from markupsafe import Markup, escape, soft_unicode
    ModuleNotFoundError: No module named 'markupsafe' 

Regards,
G,M.

**Comment by kalefranz** [comment]
The `markupsafe` package is already included in the `anaconda` metapackage.  It  looks like you might not be activating your environment correctly.
