### ISSUE TITLE
Reorganize conda to separate API from CLI

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#757]
I would like to be able to do something which seems quite reasonable to me (psuedo-conda-api):

``` python
import conda

conda.api.create(name="test", pkgs='anaconda requests flask'.split())
stdout, stderr = conda.process.run(env='test', cmd='/path/to/cmd', args='a b c'.split())

conda.api.install(name='devel', pkgs='zip zap ping'.split(), dry_run=True) 
```

These seem like reasonable things for someone to want to do.  Certainly I want to do these things right now and have to figure out a way to do it, but, as best I can tell, this is impossible with the current conda implementation that mixes CLI into the API, such that there are operations like `sys.exit()` inside what should just be API calls (that should raise exceptions -- the CLI piece should catch these and then decide to report an error and do `sys.exit()`).

**Comment by ijstokes** [comment]
Some additional comments based on a thread on the internal Anaconda dev mailing list:

all the kinds of things that I want to do as a user, in a particular conda env (not the root env), I also could reasonably want to do in a programmatic way.  Providing nice ways to do this with bash would be great (so as to avoid having to do complicated grep expressions), and the `--json` option and variations on this go a long way on that front for shell-scripting use.  But we're a Python shop, so being able to do those same sorts of environment-internal operations from inside Python seems like an obvious thing to do (and as I say in the issue: is something I've needed to do many times, and right now just need to find work-arounds).  An incomplete list:

    conda update
    conda list
    conda info
    conda remove
    conda install

And as the issue already notes, one distinct piece is to provide an alternative `subprocess` such that I could do:

    from conda.api import subprocess

and then have optional parameters for all the normal `subprocess` classes and functions that would allow me to invoke shell commands from within a particular conda env (and default to the current conda env, of course).

**Comment by kalefranz** [comment]
Heavily underway right now.  Won't be using this ticket to track though.  Closing.
