### ISSUE TITLE
Conda CLA (again)

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7573]
Dear Conda Contributors,

In mid- to late-2016, you signed a Contributor License Agreement for the Conda project. The issue where this was initially tracked is at https://github.com/conda/conda/issues/3438. The agreement you signed is located at https://www.clahub.com/agreements/conda/conda.

Unfortunately, CLAHub has lost all of our data 😱. We reached out to CLAHub to help us recover our data, but unfortunately we haven't been successful (https://github.com/clahub/clahub/issues/158).

You may have already signed the Conda-Build CLA on CLAHub, but that also unfortunately doesn't count.  The good news is that the document we are now asking you to sign covers *all* projects under the Conda Code Organization (i.e. https://github.com/conda).  This includes conda, conda-build, constructor, and all other related projects under https://github.com/conda.

So, we're asking you one more time (🙄) to sign our CLA.  **It's our sincere hope that we get it right this time.**  The CLA is now at:

--> https://conda.io/docs/contributing.html#conda-contributor-license-agreement <--

Once submitted, you will also need to confirm your signature via the Email that Adobe Sign will send to you.

We sincerely appreciate your contributions to conda, and we apologize for the extra trouble.

@arkottke
@blindgaenger
@chrislf
@dan-blanchard
@delicb
@dhirschfeld
@elehcim
@faph
@groutr
@jacoblsmith
@jerowe
@jrovegno
@Korijn
@mheilman
@mikecroucher
@natefoo
@NewbiZ
@rcthomas
@rgommers
@tdhopper
@twiecki

**Comment by megies** [comment]
Done.

**Comment by aldanor** [comment]
Signed.

**Comment by esc** [comment]
Done.

* Kale Franz <notifications@github.com> [2018-07-23]:

**Comment by ukoethe** [comment]
Done.

**Comment by dhirschfeld** [comment]
Done

**Comment by jerowe** [comment]
Done
