### ISSUE TITLE
Please sign the Conda Contributor License Agreement

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7574]
To the honorable, honored group below: your contributions make up conda. Anaconda needs to obtain contributor signatures from all of you, so that we can offer Conda to our customers under different indemnification terms.

Please read and sign at

--> https://conda.io/docs/contributing.html#conda-contributor-license-agreement <--

If you have already signed the CLA for conda-build, it unfortunately doesn't count due to our inability to rely on CLAHub as a trusted source of data (see https://github.com/conda/conda/issues/7573). The good news is that the document we are now asking you to sign covers *all* projects under the Conda Code Organization (i.e. https://github.com/conda).  This includes conda, conda-build, constructor, and all other related projects under https://github.com/conda.

In case you're new to CLAs, this is rather standard procedure for larger projects. [Django](https://www.djangoproject.com/foundation/cla/) and even [Python](https://www.python.org/psf/contrib/contrib-form/) itself both use something similar.

Best regards, and my admiration to all of you for helping to get conda where it is today.

@aburgm
@akanehira
@amelio-vazquez-reina
@anntzer
@ARF1
@AvdN
@bchapman
@Bezier89
@bilderbuchi
@blake-nicholson
@bradsaracik
@brentp
@certik
@daineseh
@ddale
@dfroger
@dmkent
@edwardreed81
@eliteraspberries
@hubmann
@immerrr
@jakirkham
@jameswinegar
@JarnoRFB
@jharriman
@jimm-domingo
@joelkim
@josham
@jrjohansson
@kurtwheeler
@lambdalisue
@loriab
@Maggie-M
@majidaldo
@makbigc
@MaxNoe
@mdeff
@mguillau
@minrk
@mjuric
@NixonK
@oyse
@pelson
@peter1000
@petercable
@ramseydsilva
@rvianello
@sachinbiradar9
@ShannonGreen
@teake

**Comment by kalefranz** [comment]
@tomkinsc 
@tpn 
@Zaharid 
@zzag

**Comment by mdeff** [comment]
done

**Comment by tomkinsc** [comment]
done!

**Comment by joelkim** [comment]
done

**Comment by zzag** [comment]
@kalefranz This new CLA is required for the future contributions, right? If so, I'd like to not sign it because I'm not so active conda contributor.

**Comment by teake** [comment]
Done!

**Comment by kalefranz** [comment]
@zzag This CLA is for prior contributions.  It would be very much appreciated if you could sign.  After another month or so of backfilling signatures, we'll have to go back through and start reviewing individual commits that we don't have a CLA for, and then possibly start reverting those commits :(

**Comment by certik** [comment]
Done. The CLA is not clear on that --- do I keep the copyright of the code I submitted to Conda? So I can, for example, still send my own contribution to Conda to another project under another license.

**Comment by kalefranz** [comment]
@certik Received, and thanks so much.

> do I keep the copyright of the code I submitted to Conda?

I am not a lawyer, and I cannot represent Anaconda in any official, legal capacity with this answer. What I am sharing here is my understanding, but this is also not an official answer. That said, Clause 2 of the CLA states:

> 2. Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby 
grant to Anaconda and to recipients of software distributed by Anaconda a perpetual, worldwide, 
non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare 
derivative works of, publicly display, publicly perform, sublicense, and distribute Your 
Contributions and such derivative works.

My understanding is that the original author of the code always holds the copyright. What the CLA does is grant Anaconda a non-exclusive (no-charge, royalty-free, etc., etc.) license to your contribution(s).  The non-exclusive part is the key here, which means you can take your contributions and use them anywhere else you like, so long as they are not otherwise encumbered in a way that goes against the "perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license" that you've granted to Anaconda.

**Comment by certik** [comment]
@kalefranz thanks, that's what I thought also, but to make it clear, the CLA should explicitly state that the original author keeps the copyright to his contribution. Because, unfortunately it is not true that "the original author of the code always holds the copyright" for all CLAs. An example where the original author does not hold copyright to his code is the FSF CLA.

However, I think things are clarified for Conda, so all is good. Thank you.

**Comment by ShannonGreen** [comment]
Done
