### ISSUE TITLE
Additional information in conda channel's repodata.json; consider messagepack

### ISSUE THREAD

**Issue by mikecormier** [conda/conda#7583]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

The conda channel's repodata.json file includes only some of the meta.yaml information from each package.

### Steps to Reproduce

```
curl -sL https://conda.anaconda.org/<channel>/linux-64/repodata.json
```

## Expected Behavior

Could you include the information from each package's **meta.yaml "extra" key**  in the **repodata.json** file. This json file will be extensively used in our ggd tool for searching and identifying package information from multiple conda channels.

**Comment by kalefranz** [comment]
That would substantially increase the size of the file, and I'm afraid it would have pretty severe performance implications for conda-forge in particular.  In general, we try to keep repodata.json as small as possible, and only include information that is needed by the solver for selecting packages.  Will definitely need more thought and discussion...

**Comment by kalefranz** [comment]
Can you share more information about what your ggd tool is?

**Comment by johanneskoester** [comment]
Apart from GGD, this could be useful for bioconda, because we store DOIs and ontology identifiers in extra. They could be easily queried by registries like https://bio.tools then. Another application (which I believe GGD is aiming at) would be tag-based search (if tags are stored under extra). I agree though that this could lead to some overhead, and one could work around the issue by doing a CI-based parsing of the recipes and providing that information in a separate file hosted on e.g. github pages.

Side question: did you ever consider replacing repodata.json by a messagepack version (or provide that in addition)? This could speed up both download and parsing.

**Comment by kalefranz** [comment]
I think where we might land is creating a new file that might be a “fat” version of repodata.json. It would probably include the contents of both `info/index.json` and `info/about.json`. It would probably also include the fields we use to create [channeldata.json](https://repo.anaconda.com/pkgs/main.channeldata.json), but for every package instance. If the `extra` field doesn’t already land in `info/about.json` it might be worthwhile to open a feature request in the conda-build repo.

**Comment by kalefranz** [comment]
I hadn’t considered MessagePack, but definitely not a bad idea. We’d probably provide the MessagePack file in addition to the json file. I wouldn’t ever want to give up the ability to just open repodata.json in a web browser.

**Comment by johanneskoester** [comment]
Agreed, in particular also for backwards compatibility (who ḱnows what people are already doing with the json).

@mikecormier can you check if extra is in about.json, and if not, create that issue as suggested by @kalefranz?

**Comment by kalefranz** [comment]
I guess GGD == Go Get Data?

Also, are there keys that you’re puttimg in `extra` that maybe we should consider making more formal and not so extra?

**Comment by mikecormier** [comment]
Yes, GGD stands for Go Get Data. 

We utilize the extra key to store information about species, genome build, key words, tags, etc., which fundamentally describe the unique differences between packages. Because GGD is being developed to reach a wide range of fields, beyond the genomic and biology fields, these unique identifiers in the extra key will be propagated with data field unique information. (Physics, pharmaceutical, financial, the -omics fields, etc). This makes it difficult to make this information more formal.

**Comment by mikecormier** [comment]
I have submitted an issue to the conda-build repo for the inclusion of the `extra` key info from the meta.yaml. (https://github.com/conda/conda-build/issues/3046)

**Comment by mikecormier** [comment]
The extra field of the meta.yaml file is now included in the about.json metedata file. (PR: https://github.com/conda/conda-build/pull/3048)

**Comment by mikecormier** [comment]
Hi @kalefranz,

I wanted to follow up with you and see what the status of this feature request is?

**Comment by kalefranz** [comment]
I just looked at https://github.com/conda/conda-build/pull/3048. So now I think I understand that the intent is to have the `extra` field that's being put in `info/about.json` now end up being added to `channeldata.json`, is that correct?  In that case, we'd be adding all `conda-forge` `recipe-maintainers` to the channeldata.json for both `defaults` (via https://github.com/AnacondaRecipes) and `conda-forge` itself. That really doesn't seem appropriate to me.  Would definitely want to get input  from conda-forge before we move forward on that.

FWIW, examples of channeldata are currently at https://conda-static.anaconda.org/conda-forge/channeldata.json and https://conda-static.anaconda.org/main/channeldata.json.

**Comment by mikecormier** [comment]
As discussed above, I think the new intent is to "creating a new file that might be a “fat” version of repodata.json." (https://github.com/conda/conda/issues/7583#issuecomment-408060364) The idea is to create a new metadata file that has more information about channel packages, specifically including the extra field from each packages .yaml file, that can be leveraged for different reasons. 

@johanneskoester any thoughts?

**Comment by johanneskoester** [comment]
@kalefranz I think it would be fine to whitelist top-level keys in extra. E.g., `tags`, and `identifiers` would make us happy already. This way, doi annotations in bioconda and the tags from ggd would become searchable.

**Comment by kalefranz** [comment]
Ah. Ok that makes sense. Sorry I forgot about that.  Are `tags` and `identifiers` the exclusive list of what you want right now?  If not, can you provides the full list?

**Comment by mikecormier** [comment]
`tags` `identifiers` and `keywords` are the three we will be using.

**Comment by mikecormier** [comment]
Looking at the conda-build release, version 3.12.1 contains the extra field in the about.json file. The current version is 3.13.0. https://github.com/conda/conda-build/releases. 

Is there anything else we need in order to create/add this new file?

**Comment by kalefranz** [comment]
@msarahan is working on an update to `conda index` in https://github.com/conda/conda-build/pull/3091, and I'd recommend that these three specific fields, `tags`, `identifiers`, and `keywords`, be added to `channeldata.json` in that PR or as a follow-up.

**Comment by mikecormier** [comment]
@kalefranz, those three fields have been added to the channeldata index file. https://github.com/conda/conda-build/pull/3091/commits/f8e3844cf688b25c4b9b1326314f9916fe8e1530

Will you check to see if this addition complies with what you were thinking?

**Comment by mikecormier** [comment]
@kalefranz, the rewrite of the conda index from @msarahan is complete, has been merged, and adds  `tags`, `identifiers`, and `keywords` to the channeldata.json file.  

I am currently have trouble creating the channeldata.json file for the ggd channel. Could you provide me the steps required in order to create the channeldata.json and RRS feed files? Similar to:
- https://conda-static.anaconda.org/bioconda/
-- https://conda-static.anaconda.org/bioconda/channeldata.json
- https://conda-static.anaconda.org/conda-forge/
-- https://conda-static.anaconda.org/conda-forge/channeldata.json
- https://conda-static.anaconda.org/main/
-- https://conda-static.anaconda.org/main/channeldata.json

**Comment by mikecormier** [comment]
@kalefranz,

Can you provide the steps required to create the channeldata.json file? An example of this file is: https://conda-static.anaconda.org/main/channeldata.json

**Comment by epruesse** [comment]
The `parent_recipe` information would also be very useful to have somewhere.
