### ISSUE TITLE
miniconda permission isssue

### ISSUE THREAD

**Issue by pritesh1110** [conda/conda#7586]
Somebody pleas help me out with this issue.
Thanks in advance!!!
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::conda-4.5.4-py36_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

**Comment by kalefranz** [comment]
You have a permissions error, and you haven't provided information in the issue template, so we have no real way to help.
