### ISSUE TITLE
Guidance on syntax for installs from local channel

### ISSUE THREAD

**Issue by ranjitiyer** [conda/conda#7600]
**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request
  - [x] query

## Current Behavior
I'm wanting some guidance on the correct syntax to install a package from a local channel but allow dependencies to be obtained from the 'default' channel.

I have a locally built sparkmagic package (built with conda build)

1. Index it
```
root@95ac4cdd1e1c:/# conda index /tmp/linux-64/
root@95ac4cdd1e1c:/# ls /tmp/linux-64/
repodata.json  repodata.json.bz2  sparkmagic-0.12.5-py36h39e3cac_0.tar.bz2
```

3. Add local channel
```
conda search --platform linux-64 --offline -c file:///tmp --override-channels
Loading channels: done
# Name                  Version           Build  Channel
sparkmagic               0.12.5  py36h39e3cac_0  tmp
root@95ac4cdd1e1c:/#
```
4. List channels and find 'tmp' has precedence
```
root@95ac4cdd1e1c:/# conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'tmp'   # highest priority
root@95ac4cdd1e1c:/#
```
5. Enforce channel priority
```
conda config --set channel_priority true
```
 
5. Install sparkmagic. I notice that it won't find sparkmagic in the local channel but tries to install it from 'default'

```
conda install --dry-run --channel-priority --show-channel-urls --force --use-local sparkmagic

 Package Plan ##

  environment location: /root/miniconda3

  added / updated specs:
    - sparkmagic


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    constantly-15.1.0          |   py36h28b3542_0          13 KB  defaults
    twisted-18.4.0             |   py36h14c3975_0         4.9 MB  defaults
    widgetsnbextension-3.3.0   |           py36_0         1.7 MB  defaults
          . . . 
   sparkmagic-0.12.5          |           py36_0          65 KB  defaults
    numpy-1.15.0               |   py36h1b885b7_0          35 KB  defaults
    jsonschema-2.6.0           |           py36_0          62 KB  defaults

```
I'm new to this, so guessing there's a missing flag or step. 

My objective is to install sparkmagic alone from ```tmp``` but have its dependencies obtained from ```default```

Thanks :)

**Comment by kalefranz** [comment]
Ah. The `--use-local` flag is equivalent to `-c local`.  There is literally a special channel named `local`, which is actually the conda-build channel, and therefore sort of a confusing name.  Unfortunately, it's historic and difficult to change, so we're stuck with it.

For what you're trying to do, `--channel-priority --show-channel-urls --force` are all overkill.  Channel priority is enabled by default.  I didn't even know `--show-channel-urls` was a valid flag for the `install` command.  The `--force` we're trying to get away from; it means too many different things in too many different contexts.

For what you're trying to do, I'd recommend just

    conda install --dry-run -c file:///tmp sparkmagic

or

    conda install --dry-run file:///tmp::sparkmagic
