### ISSUE TITLE
Updating activate/deactivate syntax in README

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7613]
The README still uses `source activate`/`activate` and `source deactivate`/`deactivate`, which should be updated to `conda activate` and `conda deactivate`.

**Comment by kalefranz** [comment]
Yeah, we'll update those parts of the README when we can include `conda init`, so we can be sure that `conda activate` and `conda deactivate` will work.  Until then, `source activate` / `activate` is still compatible and safest for documentation.

**Comment by akapocsi** [comment]
Bumping this
