### ISSUE TITLE
Docker images from conda environment specs

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7616]
Requirements:
  * Create a fully-compliant [OCI Image](https://github.com/opencontainers/image-spec) from (a) a `conda create` command, (b) a `conda env create` command with an `environment.yml` file, or, more likely, (c) a `create` command based on the https://github.com/conda/conda/issues/7248 environment spec. (**Notice: No `Dockerfile`!**)
  * Once created, the image should be able to be uploaded to a registry of choice.
  * The image should be able to be created with a non-privileged user.
  * Ideally, the image could be created natively on any OS where conda is running (even though the target OS inside the container is obviously Linux). Given obstacles like macOS case insensitivity, we'd probably have to play some tricks here.

**Comment by mingwandroid** [comment]
There's docker for Windows too
