### ISSUE TITLE
Skip iterating through all users on the system

### ISSUE THREAD

**Issue by erictcgs** [conda/conda#7666]
## Current Behavior

Currently conda iterates through all users on the system when list_all_known_prefixes() is called when running as root (e.g. during a docker build).  Normally this may not be problematic, but it is when your system is connected to an ldap with 10k+ users.

https://github.com/conda/conda/blob/3ed26bc6a2fb033f45d6a8e4d5bc8610ec1dc1a1/conda/core/envs_manager.py#L74

### Steps to Reproduce
1. Setup system with LDAP and 10k+ users
2. Run as root (e.g. docker build)
3. `conda env list`
4. Observe a delay of ~60s to list a single environment

## Expected Behavior
`conda env list` should not take 60s.  Unclear why this command would iterate through all users on the system

## Environment Information
```
     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : <internal mirror>
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/4.15.0-20-generic ubuntu/18.04 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by erictcgs** [comment]
Hi @kalefranz - Is there a reason to iterate through all users?  Can that be removed, or at least controlled with a flag?

**Comment by kalefranz** [comment]
We should probably add a flag to control it.  The canonical example is, as root, something like `conda search --envs 'openssl<1.0.2p'` to find all outdated versions of openssl across the entire system.
