### ISSUE TITLE
I cannot Install Anaconda 5.1.0 and 5.0.2. 

### ISSUE THREAD

**Issue by lunaplush** [conda/conda#7669]
Hi!
During installing new Anaconda I have 
![installanacondaproblemprompt2](https://user-images.githubusercontent.com/19995321/44310850-c7386400-a3e5-11e8-90bb-23774e400530.png)
After I use "continue" after this error, I dont have conda.exe, navigator in main menu is epcent etc.

I can install the latest Anaconda only 4.2.0 with python 3.5.
My assumption is that problem with qt-5.6.2 (installation)

I am trying to instal more than 10 times.

**Comment by mingwandroid** [comment]
Please use procmon to find out what non Anaconda Distribution DLLs are
getting loaded and rename them. Probably you have incompatible qt or zlib
DLLs in c:\Windows\system32

**Comment by lunaplush** [comment]
I wil try, but can you explaine a bit better what I have to do.
If I think right?
1 Download Process Monitor programm
2. Start Process Monitor and begin to install Anaconda.
3. In what place can I find information about downloaded DLLs?
4. Should I compare downloaded DLLs names with Dlls in system32.
5. Where I have to rename DLL?

Thank you great for help!

**Comment by mingwandroid** [comment]
You need to filter by process name in procmon and set that to python then
see what DLLs appear. You may also be able to use dependency Walker. It
might be a bit more user friendly.

**Comment by lunaplush** [comment]
Hello! 
I try to install pyton 3.6 one more time from previously version of anaconda 4.5.10 (with python 3.5)
using comand from you site conda create -n py36 python=3.6 anaconda.
After downloading all dll`s and trying to their installation the  ### Error was repeated:
ERROR conda.core.link:_execute(502): An error occurred while installing package
'defaults::### qt-5.9.5-vc14he4a7d60_0'.
FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)

I use Dependensy Walker, but I can undersatend what i have to do exectly. 
Maybe you can tell me what dll connect with qt-5.9.5-vc14he4a7d60_0 and what I have to do!
Or how Dependency Walker can help me, what file I have to open in it?

**Comment by lunaplush** [comment]
With Dependensy Walker I see, that i dont have this ddls

API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
IESHIMS.DLL
But where i can find it and what I have to do?
