### ISSUE TITLE
Ruamel Yaml CommentedSeq Subclasses MutableSequence not List

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda#7672]
## Current Behavior
`conda` checks if something is a list, but since it is loaded by `ruamel_yaml` it is a `CommentedSeq`, which now no longer subclasses from `list` but from `MutableSequence`.

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_config.py", line 30, in execute
    execute_config(args, parser)
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_config.py", line 263, in execute_config
    raise CouldntParseError("key %r should be a list, not %s." % (key, bad))
conda.exceptions.CouldntParseError: key 'channels' should be a list, not CommentedSeq.
```
I think this is the relevant line in master. https://github.com/conda/conda/blob/master/conda/cli/main_config.py#L286

[Commit in `ruamel.yaml` changing inheritance](https://bitbucket.org/ruamel/yaml/commits/9e4de94ee6a88ed86ab5fdc6d49a23cfc6ab5782)

### Steps to Reproduce
Run a build with `ruamel_yaml>0.15.54`.

## Expected Behavior
Not error with `ruamel_yaml>0.15.54`

## Environment Information
Working on it.
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by carlodri** [comment]
currently failing CI in in https://github.com/conda-forge/cherrypy-feedstock/pull/44

**Comment by jakirkham** [comment]
Maybe `conda` should start pinning to a `ruamel_yaml` patch version? There have been a few `ruamel_yaml` releases recently and it seems at least a couple broke `conda`. Not aware of anything else using `ruamel_yaml`. So this seems like a relatively safe thing to do.
