### ISSUE TITLE
CONDA_PKGS_DIRS and multi user environment

### ISSUE THREAD

**Issue by matmel** [conda/conda#7686]
## Context

At my job, we are using conda in a multi user Linux cluster. All volumes mentioned hereafter are NFS volume. Conda is installed globally for all users in:

```
/import/common/conda
```

No user except root has write access in it. Each user of conda is asked to create a minimal `.condarc` to have its own cache and environment directory:

```yaml
envs_dirs:
  - /import/cfd/matthieu/conda

pkgs_dirs:
  - /import/cfd/matthieu/conda/.pkgs
```

Note that `cfd` directory is on another volume as `common` in which conda is installed. We use that volume during development phase of various tools. We rely on conda environments.

Now, when  we finally want to make a release, we use yet again another volume, `/import/poi`, to make a release. Let's call it the release volume. To do that release, we use automated scripts. Those scripts will `export CONDA_PKGS_DIRS=/import/poi/conda/.pkgs`. This directory is the shared conda cache for the release volume.

## Current behavior

Setting `CONDA_PKGS_DIRS`  appends a directory to the cache directory list as shown below in package cache entry:

```bash
export CONDA_PKGS_DIRS=/import/poi/conda/.pkgs

conda info
     active environment : None
       user config file : /import/home/matthieu/.condarc
 populated config files : /import/common/conda/.condarc
                          /import/home/matthieu/.condarc
          conda version : 4.5.8
    conda-build version : 3.12.0
         python version : 2.7.12.final.0
       base environment : /import/common/conda  (read only)
           channel URLs : http://company.com/conda-channels/in-house/linux-64
                          http://company.com/conda-channels/in-house/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /import/poi/conda/.pkgs
                          /import/cfd/Matthieu/conda/.pkgs
       envs directories : /import/cfd/Matthieu/conda
                          /import/home/matthieu/.conda/envs
                          /import/common/conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.14.2 CPython/2.7.12 Linux/2.6.32-696.18.7.el6.x86_64 scientific/6.9 glibc/2.12
                UID:GID : 10029:10002
             netrc file : None
           offline mode : False
```

Without the environment variable set, this `package cache` entry has only `/import/cfd/Matthieu/conda/.pkgs`.

## Expected Behavior

The current behavior is problematic, because during the creation of a new conda environment in the release volume (`/import/poi`), packages that are not in the cache of the release volume already can be in the personal development cache (actually it's very likely). When installing conda will see that in the development cache, the package exists, and it will not bother to re-create it in the release cache. But remember, the development cache, set in `~/.condarc` is in another volume.  The hardlinks for those packages are not created in that situation, but plain copies are used. This is very inefficient in terms of disk space.

We only very recently upgraded to conda 4.5.x. Before that we have used for more than a year conda 4.1.x. In that conda version, the environment directory and the cache directory were set with the same environment variable (`CONDA_ENVS_PATH`). When set, it completly overwrote the `.condarc` value. And thus all packages ended up in the release cache.

I would propose two solutions for this problem:
- The environment variable `CONDA_PKGS_DIRS` overwrite any existing `condarc` configuration
- Or this behavior can be obtained by a specfic `condarc` configuration and / or a flag in `conda create`.

**Comment by kalefranz** [comment]
Thanks for the clear explanation of your issue.  The relevant controlling code here is the block at https://github.com/conda/conda/blob/d244111820ba73df5802f6283b4f4e625ab024bf/conda/core/package_cache_data.py#L457-L547.

I believe the best solution is here a configuration parameter to enforce that every linked package exist in the first writable package cache.
