### ISSUE TITLE
Cannot install Rstudio on root environment from navigator 

### ISSUE THREAD

**Issue by Denhol1** [conda/conda#7691]
Hello,
Brand new install (25/08/18) of Anaconda3 on a windows 10 64 bits machine.
Trying to install rstudio 1.1.456 on the root environment.
And get the following message "rstudio==1.1.456 cannot be installed on this environment. Do you want to install the package in an existing environment or create a new environment?"

Is there any way to have rstudio on the root?

Thanks in advance.

**Comment by mingwandroid** [comment]
Yes use miniconda 3 or anaconda 3 in your base env or use Linux it macOS.

**Comment by mingwandroid** [comment]
That is strange then. Can you try to install it from the Anaconda prompt instead?

**Comment by Mart-97** [comment]
I have the same problem, I tried with Anaconda Prompt, but the problem persisists

**Comment by tm-89** [comment]
Same problem here. Windows 10, current version of Anaconda.

**Comment by wyuill** [comment]
I also can't install rstudio with the same error with the latest Anaconda3. Using Prompt I get the following:
I can install to a different environment but that would be annoying as I'd like to use both python and R in labs and don't want to switch environments.

```
The following packages will be REMOVED:

    anaconda:                  2018.12-py37_0

The following packages will be UPDATED:

    libssh2:                   1.8.0-h7a1dbc1_4                       --> 1.8.0-hd619d38_4
    pycurl:                    7.43.0.2-py37h7a1dbc1_0                --> 7.43.0.2-py37h74b6da3_0

The following packages will be DOWNGRADED:

    conda:                     4.5.12-py37_1000           conda-forge --> 4.5.12-py37_0
    cryptography:              2.4.2-py37h7a1dbc1_0                   --> 2.3.1-py37h74b6da3_0
    krb5:                      1.16.1-hc04afaa_7                      --> 1.16.1-h038dc86_6
    libarchive:                3.3.3-h0643e63_5                       --> 3.3.3-h798a506_0
    matplotlib:                3.0.2-py37hc8f65d3_0                   --> 2.2.2-py37had4c4a9_2
    openssl:                   1.1.1a-he774522_0                      --> 1.0.2p-hfa6e2cd_0
    pyqt:                      5.9.2-py37h6538335_2                   --> 5.6.0-py37ha878b3d_6
    python:                    3.7.1-h8c8aaf0_6                       --> 3.7.1-h33f27b4_4
    qt:                        5.9.7-vc14h73c81de_0                   --> 5.6.2-vc14h6f8c307_12
    sip:                       4.19.8-py37h6538335_0                  --> 4.18.1-py37h6538335_2
```

**Comment by nwestallen** [comment]
I'm having the same problem

**Comment by I-Lauer** [comment]
Same issue here. Anaconda 3 is my only Python installation, Python 3.6, installed at C:/Anaconda3. Cannot install w/ Python Navigator or from Anaconda Prompt

**Comment by mingwandroid** [comment]
Those issue is 5 months old and filed against the wrong project. Can someone having trouble please open an issue at https://github.com/ContinuumIO/anaconda-issues

Please take care to provide all of the details asked for.

**Comment by Denhol1** [comment]
@mingwandroid  => Please explain how this is filed against the "wrong" project? You initially replied to the query 5 months ago and did not flag it as misfiled. No "details" were "asked for" at the time either.

**Comment by OneOfMany07** [comment]
Could be https://github.com/ContinuumIO/anaconda-issues/issues/9906 ?  Already assigned to @mingwandroid since was opened in August 2018 (near when this bug was opened).

**Comment by krone080** [comment]
this helped me https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/

**Comment by msammond9** [comment]
Thank you!

-Matthew Sammond

**Comment by ywwang-notes** [comment]
Installing RStudio from Anaconda Navigator in Windows 10 still failed, but I was able to install it with Anaconda Prompt.  Run `conda update conda ` and then ` conda install -c r rstudio`. After that, Rstudio can be launched from Anaconda Navigator on the root environment.

OS: Windows 10 Pro 10.0.17134 
Anaconda Navigator 1.9.7
Rstudio  1.1.456

**Comment by Alsaxian** [comment]
> this helped me https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/

I HAD this problem after reading and following first this official intro....

**Comment by djlaserman** [comment]
selecting 'r' under the Environments tab on the left fixed my issue.... it would move the progress-bar indefinitely without installing. you can  tell it's installing if in less than 1min30sec it begins to show the progress indicating that it's fetching certain files... so I guess you'd first need to select 'r' it should work

**Comment by OMMANT** [comment]
I finally installed [r-base, r-essentials, rstudio] on the root environment.
I think R seems to be conflicting with some of the installed packages.
On root environment I tried `conda install conda` and then `conda upgrade --all` then you will be able to install R normally.

**Comment by ganeshbabuNN** [comment]
> > this helped me https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/
> 
> I HAD this problem after reading and following first this official intro....

Thanks

**Comment by davidli89** [comment]
Still have this problem. Tried several solutions above. No help.

**Comment by QLutterYin** [comment]
I am facing the same issue, anything new to this topic?

**Comment by LMWafer** [comment]
Had the same problem three times : 

1. I first tried on the (base) environnement with Rstudio on the GUI of anaconda
2. Then I created a new one with : conda create -n renv + conda install r-base + conda install r-essential + conda install rstudio

I tried other small trick (like install packages with Conda Prompt and Rstudio with the GUI)... after 3 hours it still does not work.

**Comment by nishantnayar** [comment]
I am also facing the same issue, any suggestions

**Comment by laxmikants** [comment]
I am also facing the same issue, any suggestions

**Comment by git-hobo** [comment]
This is still an issue at the end of 2022 with Windows 10.

**Comment by slipfall** [comment]
This is still an issue at January 2023 with Windows 10. 
The following error messages may provide some insight.
I believe the problem to be that RStudio cannot be installed in an environment that, in addition to having R installed, also has has Python 3.9 or later in the same environment.
I tried installing RStudio via command line, into an environment that already had R and Python 3.9 installed.
The output was as follows:

(RPy) C:\Users\slipfall>conda install -c r rstudio
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
rstudio -> qt=5.6 -> openssl=1.0
python=3.9 -> openssl[version='>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a']

Package vc conflicts for:
rstudio -> freetype[version='>=2.9.1'] -> vc[version='9.*|>=14.1,<15.0a0']
rstudio -> vc=14

Package vs2015_runtime conflicts for:
rstudio -> freetype[version='>=2.9.1'] -> vs2015_runtime[version='>=14.0.25123,<15.0a0|>=14.0.25420|>=14.15.26706|>=14.16.27012,<15.0a0|>=14.27.29016|>=14.16.27012']
rstudio -> vs2015_runtime

Package zlib conflicts for:
rstudio -> freetype[version='>=2.9.1'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0']
rstudio -> zlib[version='>=1.2']
