### ISSUE TITLE
conda activate command not found

### ISSUE THREAD

**Issue by michaelklachko** [conda/conda#7692]
I'm getting the following error after I did `echo ". /home/michael/miniconda2/etc/profile.d/conda.sh" >> ~/.bashrc`  and commented out `export PATH="/home/michael/miniconda2/bin:$PATH"` in my .bashrc file:
```

michael@Pascal:~$ conda activate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /home/michael/miniconda2/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /home/michael/miniconda2/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/home/michael/miniconda2/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^
```

conda version is 4.5.9

Also, this might help: if I first do `source activate 'myenv_name"` then do `source deactivate`, and then try `conda activate "myenv_name"`, it works fine (the environment is activated).

**Comment by mingwandroid** [comment]
This is not an error. It is a notification about an important change in how conda is activated. You are meant to follow them.

**Comment by mingwandroid** [comment]
In this instance you probably forgot to source your new ~/.bashrc or lunch a new interactive shell.

**Comment by BYSD** [comment]
try $ source ~/.bashrc
