### ISSUE TITLE
Rename egg-info directories for `noarch: python` packages

### ISSUE THREAD

**Issue by mbargull** [conda/conda#7693]
If a package was built with an older `pip <10` and `setuptools`, it can include Python version-specific `egg-info` directories, e.g., `site-packages/overrides-1.9-py2.7.egg-info` in `conda-forge::overrides=1.9=py_0`.
If those packages are `noarch: python` ones, `conda` will install those into the environment's `python`'s site-packages directory but not adjust their names, i.e., the above example will be installed into a `python=3.6` environment as
```
lib/python3.6/site-packages/overrides-1.9-py2.7.egg-info/
```
rather than
```
lib/python3.6/site-packages/overrides-1.9-py3.6.egg-info/
```
This could cause issues when distribution info like entry points are queried.

Surely it makes sense to build packages to rather use `dist-info` instead of `egg-info`. But we could also teach `conda` to rename those directories for `noarch: python` packages.

I'm not aware that a `-py2.7.egg-info` can include Python 2.7-specific things, so I think simply renaming them would be fine. But if anyone as more in-depth knowledge of the contents of `.egg-info`, please feel free to correct or confirm that assumption!

xref: https://github.com/conda/conda-build/issues/3055#issuecomment-409324132

**Comment by kalefranz** [comment]
> If a package was built with an older `pip <10` and `setuptools`

What does "newer" do instead?  Just for reference...

**Comment by mbargull** [comment]
`.dist-info` without `-py?.?` prefixes.

**Comment by mbargull** [comment]
@jjhelmus pointed out (at https://github.com/conda/conda-build/issues/3055#issuecomment-417870099 and https://github.com/conda/conda-build/issues/3094) that from `conda-build 3.12.1` on `PIP_NO_CACHE_DIR` is set at https://github.com/conda/conda-build/pull/3053/files#diff-ac55d744935b1f37a3369258b88e8f1fR1413 which makes `pip` produce `-py?.?.egg-info`s again.
So this isn't restricted to "older" build but also very recent ones.

**Comment by kalefranz** [comment]
I think this is all probably true. We could implement it as part of the special `noarch: python` install translations, but doesn't it also make sense to do on the build side?

**Comment by mbargull** [comment]
> Surely it makes sense to build packages to rather use `dist-info` instead of `egg-info`. But we could also teach `conda` to rename those directories for `noarch: python` packages.

> I think this is all probably true. We could implement it as part of the special `noarch: python` install translations, but doesn't it also make sense to do on the build side?

I think we are in agreement here :wink:.
