### ISSUE TITLE
Solver improvements: 1) use CryptoMiniSat as the default SAT solver

### ISSUE THREAD

**Issue by mbargull** [conda/conda#7694]
ref: https://github.com/conda/conda/pull/7676#issuecomment-415810372
> - **Default to CryptoMiniSat** (requirements: https://github.com/msoos/cryptominisat/issues/513, https://github.com/conda-forge/cryptominisat-feedstock/issues/1, https://github.com/conda-forge/cryptominisat-feedstock/issues/9)

**Comment by wolfv** [comment]
Hi @mbargull I saw your comments on the linked issues. The improved speed of the new SAT solver looks great.

However, I am wondering if other solutions have been considered?

Specifically, the SAT solver coming out of OpenSUSE, which is used by other distros such as Fedora, could be a very interesting alternative: https://github.com/openSUSE/libsolv

I am no expert and there might be downsides. But I could only find libsolv referenced in one comment on some other PR.

**Comment by mbargull** [comment]
Hi @wolfv,

thanks for the suggestion! It's somewhat similar to @domoritz's comment in https://github.com/conda/conda/issues/7239#issuecomment-407127381:
> If the solving algorithm is slow, it might be interesting to look into a powerful constraint solver such as https://potassco.org/aspcud/.

So, my answer in https://github.com/conda/conda/issues/7239#issuecomment-414758739 also applies to your question:
> Thanks for the link. For the long-term I can imagine it could make sense to abstract and factor out all that dependency/constraint resolution. But currently there is some Conda-specific special handling happening in the code which makes this a bit more complicated. So this is nothing we can change any time soon, IMO.

Plus https://github.com/conda/conda/issues/7239#issuecomment-414766963:
> > why you think this can't be expressed as constraints in a general language like [ASP](https://en.wikipedia.org/wiki/Answer_set_programming)? 
> 
> Oh, it's not that I don't think it can be expressed that way. I think it would be a nice thing to do, in fact. My comment was more directed toward that some parts of `conda`'s code are written in a "Conda specific way" (for lack of words..). Meaning, it might take some effort to entangle those bits and I'd be surprised if someone would be willing to take this on any time soon :/. (Plus there is some part, called `features`, that is not very well integrated into the overall dependency resolution process with channel priorities and all -- we have to solve this problem before we do any other substantial changes there, IMO.)
Overall, I don't think it would be tremendous witchcraft to translate the problem with an appropriate DSL, but we'd need someone that has the time and knowledge to do so, I think

**Comment by domoritz** [comment]
https://github.com/potassco/clingo is an amazing solver and it has a conda package (https://github.com/potassco/conda). Clingo forms the basis of potassco.org/aspcud (which you can use to solve package resolution in debian and ubuntu, see https://potassco.org/aspcud/).

**Comment by mbargull** [comment]
@wolfv, @domoritz, I opened gh-7808 such that your suggestions are tracked in an own issue since this one is more for the (hopefully) short-term integration of CMS.
