### ISSUE TITLE
Conda update error: CondaHTTPError: HTTP 404 NOT FOUND

### ISSUE THREAD

**Issue by lec49** [conda/conda#7695]
**I'm submitting a bug report

## Current Behavior

I am trying to update conda and create a new environement (on a server)

I use the command 'conda uodate conda'

Conda attemps to resolve the enviornment but I then reveieve this error:

ubuntu@lyndsay:~/miniconda3$ conda update conda
Solving environment: failed  

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /home/ubuntu/miniconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/ubuntu/miniconda3
              CONDA_SHLVL=0  
                     PATH=/media/lyndsay_1/ls/bin:/home/ubuntu/miniconda3/anaconda3/bin:/home/ub
                          untu/miniconda3/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/media/ly
                          ndsay_1/ls/bin:/home/ubuntu/miniconda3/anaconda3/bin:/home/ubuntu/mini
                          conda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
                          n:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0  
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.2.final.0
       base environment : /home/ubuntu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64

                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda​/linux-64
                          https://conda.anaconda.org/bioconda​/noarch
          package cache : /home/ubuntu/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.2 Linux/4.4.0-109-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/bioconda​/noarch/repodata.json>
Elapsed: 00:00.362745
CF-RAY: 450776fe8d9835cc-LHR

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/bioconda​

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

A reportable application error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

## Expected Behavior

I have conda installed locally on my computer and do not have this issue it is only when I use conda on the server.

I have tried this fix but it didn't work:

conda config --set ssl_verify no

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

    active environment : None
            shell level : 0
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.2.final.0
       base environment : /home/ubuntu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda​/linux-64
                          https://conda.anaconda.org/bioconda​/noarch
          package cache : /home/ubuntu/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.2 Linux/4.4.0-109-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/ubuntu/.condarc <==
ssl_verify: False
channels:
  - conda-forge
  - defaults
  - r
  - bioconda​

```

Conda has previously worked fine for me on the server however I have not used it for about 6 weeks and I am now getting this issue.

I get the same issue if I try and create a new environment.

**Comment by mbargull** [comment]
I have no idea how that happened, but you have a `ZERO WIDTH SPACE` Unicode character at the end of `bioconda` in the URL at
> CondaHTTPError: HTTP 404 NOT FOUND for url https://conda.anaconda.org/bioconda/noarch/repodata.json

which is actually
> > CondaHTTPError: HTTP 404 NOT FOUND for url https://conda.anaconda.org/bioconda%E2%80%8B/noarch/repodata.json

as you can see if you inspect the link.
Maybe this is `\u200B` character is also in your `.condarc`? Can you try to remove it?

**Comment by lec49** [comment]
Thanks for your reply, how would I remove it properly?

**Comment by mbargull** [comment]
Easiest thing is probably to remove the `channels` key and rebuild it via
```sh
conda config --remove-key channels
conda config --append channels conda-forge --append channels bioconda --append channels defaults
```
Also note that I intentionally left out the `r` channel you currently have in your channel list. You don't need to and shouldn't use that channel (since it actually lowers performance of the solver) since the R packages are already part of the `defaults` multichannel as https://repo.anaconda.com/pkgs/r.

**Comment by lec49** [comment]
Thank-you that has worked and the issue is now fixed!

**Comment by Ben-zie** [comment]
Tks a lot ! You saved my day ^^
