### ISSUE TITLE
Inconsistent dependency listing for packages

### ISSUE THREAD

**Issue by derenrich** [conda/conda#7701]
## Current Behavior

Conda package regex=2017.11.09=py36had819a5_0 has incorrect dependencies extracted from the package. I assume this extraction is done by conda and not by the package (and thus this ticket belongs here).

### Steps to Reproduce
Run `conda info regex=2017.11.09=py36had819a5_0`

It lists one package with a dependency on `libgcc-ng >=7.2.0`. 

## Expected Behavior
If you download the package and inspect it it actually takes a dependency on `libgcc-ng 7.2.0.*`. My understanding is these aren't equivalent according to the definitions on your [docs page](https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html).

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.10
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       base environment : /root/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
          package cache : /root/miniconda2/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda2/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.10 requests/2.14.2 CPython/2.7.13 Linux/4.9.93-linuxkit-aufs centos/7 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
ssl_verify: False
channels:
  - https://conda.anaconda.org/anaconda
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment]
This metadata is changed in our index. We sometimes make mistakes when we create packages. This was one of them. There original constraint was far too restrictive. If we change the package, though, the hashsum of the package changes. 

Not an issue, other than if you build your own local collection of packages somehow, you'll only have the original metadata that might be broken or not ideal. There will be a way for local indexes the patch metadata someone soon.

**Comment by mbargull** [comment]
Indeed. For more information you can see these issues https://github.com/conda/conda/issues?q=metadata+hotfixes.

**Comment by derenrich** [comment]
@msarahan what why would you change the package or patch the metadata. re-issue the package with a fixed dependency. right?
