### ISSUE TITLE
Traceback: conda update seaborn -n py360

### ISSUE THREAD

**Issue by yogibearforest** [conda/conda#7721]
Problem:
Executed command:
    conda update seaborn -n py360
Received following traceback
-----------------------
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 333, in insta
ll
    update_deps=args.update_deps)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 411, in install_acti
ons
    update_deps=update_deps):
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 842, in solve2
    sys.exit(self.guess_bad_solve(specs, features))
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 927, in guess_bad
_solve
    hint = minimal_unsatisfiable_subset(specs, sat=sat, log=True)
  File "C:\Anaconda3\lib\site-packages\conda\logic.py", line 735, in minimal_uns
atisfiable_subset
    ret = minimal_unsat(clauses)
  File "C:\Anaconda3\lib\site-packages\conda\logic.py", line 717, in minimal_uns
at
    if not sat(A + include):
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 922, in sat
    self.solve2(specs, features, guess=False, unsat_only=True)
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 819, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 624, in gen_claus
es
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: scipy-1.1.0-py27h2df7626_1.tar.bz2 MatchSpec('numpy >=1.15.1,<2.0a0')

------------------------------
    conda info
---------------------------
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.3.5
       python version : 3.4.1.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://conda.binstar.org/conda-forge/win-64/
                        https://conda.binstar.org/conda-forge/noarch/
                        https://conda.binstar.org/anaconda/win-64/
                        https://conda.binstar.org/anaconda/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Evan\.condarc
    is foreign system : False

-------------------
#    List packages in py360 environment
-------------------

       conda list -n py360

# packages in environment at C:\Anaconda3\envs\py360:
#
Could not extract name and version from: 'Package                  Version'
Could not extract name and version from: '------------------------ ---------'
Could not extract name and version from: 'absl-py                  0.1.9'
Could not extract name and version from: 'alabaster                0.7.10'
Could not extract name and version from: 'asn1crypto               0.22.0'
Could not extract name and version from: 'astropy                  1.3.2'
Could not extract name and version from: 'Babel                    2.4.0'
Could not extract name and version from: 'biopython                1.68'
Could not extract name and version from: 'bleach                   1.5.0'
Could not extract name and version from: 'bokeh                    0.12.5'
Could not extract name and version from: 'certifi                  2018.8.13'
Could not extract name and version from: 'cffi                     1.10.0'
Could not extract name and version from: 'colorama                 0.3.9'
Could not extract name and version from: 'cryptography             1.8.1'
Could not extract name and version from: 'cycler                   0.10.0'
Could not extract name and version from: 'decorator                4.1.2'
Could not extract name and version from: 'docutils                 0.13.1'
Could not extract name and version from: 'entrypoints              0.2.3'
Could not extract name and version from: 'et-xmlfile               1.0.1'
Could not extract name and version from: 'futures                  3.1.1'
Could not extract name and version from: 'h5py                     2.7.0'
Could not extract name and version from: 'html5lib                 0.9999999'
Could not extract name and version from: 'idna                     2.5'
Could not extract name and version from: 'imagesize                0.7.1'
Could not extract name and version from: 'ipykernel                4.6.1'
Could not extract name and version from: 'ipython                  6.1.0'
Could not extract name and version from: 'ipython-genutils         0.2.0'
Could not extract name and version from: 'ipywidgets               6.0.0'
Could not extract name and version from: 'jdcal                    1.3'
Could not extract name and version from: 'jedi                     0.10.2'
Could not extract name and version from: 'Jinja2                   2.9.6'
Could not extract name and version from: 'joblib                   0.11'
Could not extract name and version from: 'jsonschema               2.6.0'
Could not extract name and version from: 'jupyter                  1.0.0'
Could not extract name and version from: 'jupyter-client           5.1.0'
Could not extract name and version from: 'jupyter-console          5.2.0'
Could not extract name and version from: 'jupyter-core             4.3.0'
Could not extract name and version from: 'jupyterlab               0.32.0'
Could not extract name and version from: 'jupyterlab-launcher      0.10.5'
Could not extract name and version from: 'line-profiler            2.1.2'
Could not extract name and version from: 'lxml                     3.7.3'
Could not extract name and version from: 'Markdown                 2.6.11'
Could not extract name and version from: 'MarkupSafe               1.0'
Could not extract name and version from: 'matplotlib               2.0.2'
Could not extract name and version from: 'memory-profiler          0.51.0'
Could not extract name and version from: 'mistune                  0.7.4'
Could not extract name and version from: 'mkl-fft                  1.0.6'
Could not extract name and version from: 'mkl-random               1.0.1'
Could not extract name and version from: 'mpmath                   0.19'
Could not extract name and version from: 'nbconvert                5.2.1'
Could not extract name and version from: 'nbformat                 4.4.0'
Could not extract name and version from: 'networkx                 1.11'
Could not extract name and version from: 'notebook                 5.0.0'
Could not extract name and version from: 'numexpr                  2.6.4'
Could not extract name and version from: 'numpy                    1.15.0'
Could not extract name and version from: 'nxpd                     0.2.0'
Could not extract name and version from: 'olefile                  0.44'
Could not extract name and version from: 'openpyxl                 2.4.7'
Could not extract name and version from: 'packaging                16.8'
Could not extract name and version from: 'pandas                   0.20.3'
Could not extract name and version from: 'pandas-datareader        0.2.1'
Could not extract name and version from: 'pandocfilters            1.4.2'
Could not extract name and version from: 'path.py                  10.3.1'
Could not extract name and version from: 'patsy                    0.4.1'
Could not extract name and version from: 'pickleshare              0.7.4'
Could not extract name and version from: 'Pillow                   4.1.1'
Could not extract name and version from: 'pip                      18.0'
Could not extract name and version from: 'plotly                   1.12.9'
Could not extract name and version from: 'prompt-toolkit           1.0.15'
Could not extract name and version from: 'protobuf                 3.5.1'
Could not extract name and version from: 'psutil                   5.4.3'
Could not extract name and version from: 'pycparser                2.17'
Could not extract name and version from: 'Pygments                 2.2.0'
Could not extract name and version from: 'pygpu                    0.7.6'
Could not extract name and version from: 'pyparsing                2.1.4'
Could not extract name and version from: 'python-dateutil          2.6.1'
Could not extract name and version from: 'pytz                     2017.2'
Could not extract name and version from: 'PyWavelets               0.5.2'
Could not extract name and version from: 'PyYAML                   3.12'
Could not extract name and version from: 'pyzmq                    16.0.2'
Could not extract name and version from: 'qtconsole                4.3.1'
Could not extract name and version from: 'requests                 2.14.2'
Could not extract name and version from: 'requests-file            1.4.1'
Could not extract name and version from: 'scikit-image             0.13.0'
Could not extract name and version from: 'scikit-learn             0.18.1'
Could not extract name and version from: 'scikit-surprise          1.0.5'
Could not extract name and version from: 'scipy                    1.1.0'
Could not extract name and version from: 'seaborn                  0.7.1'
Could not extract name and version from: 'setuptools               40.0.0'
Could not extract name and version from: 'simplegeneric            0.8.1'
Could not extract name and version from: 'six                      1.11.0'
Could not extract name and version from: 'snowballstemmer          1.2.1'
Could not extract name and version from: 'sphinx                   1.6.2'
Could not extract name and version from: 'sphinxcontrib-websupport 1.0.1'
Could not extract name and version from: 'statsmodels              0.8.0'
Could not extract name and version from: 'sympy                    1.0'
Could not extract name and version from: 'tabulate                 0.8.2'
Could not extract name and version from: 'tensorflow               1.5.0'
Could not extract name and version from: 'tensorflow-tensorboard   1.5.0'
Could not extract name and version from: 'testpath                 0.3'
Could not extract name and version from: 'Theano                   1.0.2'
Could not extract name and version from: 'tornado                  4.5.2'
Could not extract name and version from: 'traitlets                4.3.2'
Could not extract name and version from: 'wcwidth                  0.1.7'
Could not extract name and version from: 'Werkzeug                 0.14.1'
Could not extract name and version from: 'wheel                    0.31.1'
Could not extract name and version from: 'widgetsnbextension       3.0.2'
Could not extract name and version from: 'wincertstore             0.2'
Could not extract name and version from: 'xlrd                     1.0.0'
Could not extract name and version from: 'xlwt                     1.2.0'
alabaster                 0.7.10                   py36_0
asn1crypto                0.22.0                   py36_0
astropy                   1.3.2               np112py36_0
babel                     2.4.0                    py36_0
biopython                 1.68                np112py36_0
blas                      1.0                         mkl
bleach                    1.5.0                    py36_0
bokeh                     0.12.5                   py36_1
bzip2                     1.0.6                    vc14_3  [vc14]
certifi                   2018.8.13                py36_0
cffi                      1.10.0                   py36_0
colorama                  0.3.9                    py36_0
cryptography              1.8.1                    py36_0
cycler                    0.10.0                   py36_0
decorator                 4.1.2                    py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.3                    py36_0
et_xmlfile                1.0.1                    py36_0
freetype                  2.5.5                    vc14_2  [vc14]
graphviz                  2.38.0                        4
h5py                      2.7.0               np113py36_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
html5lib                  0.9999999                py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                      py36_0
imagesize                 0.7.1                    py36_0
intel-openmp              2018.0.3                      0
ipykernel                 4.6.1                    py36_0
ipython                   6.1.0                    py36_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                6.0.0                    py36_0
jdcal                     1.3                      py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
joblib                    0.11                     py36_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.1.0                    py36_0
jupyter_console           5.2.0                    py36_0
jupyter_core              4.3.0                    py36_0
libgpuarray               0.7.6                    vc14_0  [vc14]
libpng                    1.6.30                   vc14_1  [vc14]
libpython                 2.0                      py36_0
libtiff                   4.0.6                    vc14_3  [vc14]
mako                      1.0.7                      py_1
markupsafe                1.0              py36h0e26971_1
matplotlib                2.0.2               np112py36_0
mingw                     4.7                           1
mistune                   0.7.4                    py36_0
mkl                       2018.0.3                      1
mkl-service               1.1.2            py36hb217b18_4
mkl_fft                   1.0.6                    py36_0
mkl_random                1.0.1            py36h77b88f5_1
mpmath                    0.19                     py36_1
nbconvert                 5.2.1                    py36_0
nbformat                  4.4.0                    py36_0
networkx                  1.11                     py36_0
notebook                  5.0.0                    py36_0
numpy                     1.15.0           py36h9fa60d3_0
numpy-base                1.15.0           py36h4a99626_0
olefile                   0.44                     py36_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                     py36_0
pandas                    0.20.3                   py36_0
pandas-datareader         0.2.1                    py36_0
pandocfilters             1.4.2                    py36_0
path.py                   10.3.1                   py36_0
patsy                     0.4.1                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.1.1                    py36_0
pip                       18.0                     py36_1
plotly                    1.12.9                   py36_0
prompt_toolkit            1.0.15                   py36_0
pycparser                 2.17                     py36_0
pygments                  2.2.0                    py36_0
pygpu                     0.7.6            py36h452e1ab_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
python                    3.6.6                hea74fb7_0
python-dateutil           2.6.1                    py36_0
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_6  [vc14]
qtconsole                 4.3.1                    py36_0
requests                  2.14.2                   py36_0
requests-file             1.4.1                    py36_0
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scikit-surprise           1.0.5                    py36_0
scipy                     1.1.0            py36h672f292_0
seaborn                   0.7.1                    py36_0
setuptools                40.0.0                   py36_1
simplegeneric             0.8.1                    py36_1
sip                       4.18                     py36_0
six                       1.11.0           py36h4db2310_1
snowballstemmer           1.2.1                    py36_0
sphinx                    1.6.2                    py36_0
sphinxcontrib             1.0                      py36_0
sphinxcontrib-websupport  1.0.1                    py36_0
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
testpath                  0.3.1                    py36_0
theano                    1.0.2                    py36_0
tk                        8.5.18                   vc14_0  [vc14]
tornado                   4.5.2                    py36_0
traitlets                 4.3.2                    py36_0
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wcwidth                   0.1.7                    py36_0
wheel                     0.31.1                   py36_1
widgetsnbextension        3.0.2                    py36_0
wincertstore              0.2                      py36_2
xlrd                      1.0.0                    py36_0
xlwt                      1.2.0                    py36_0
zlib                      1.2.11                   vc14_0  [vc14]

**Comment by kalefranz** [comment]
You cannot use conda-forge with conda 3.18.3.  That version is nearly 3 years old.  You need to remove conda-forge from your channels list, and then `conda update conda`.
