### ISSUE TITLE
Hi I am trying to install packages from local disk to virtual envirement of conda

### ISSUE THREAD

**Issue by Mehdihym** [conda/conda#7727]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by mingwandroid** [comment]
You've not provided us with any of the requested information nor the commands you tried to run. Closing

**Comment by Mehdihym** [comment]
I wanna just use pip inside my virtual environment created by Conda to install some packages
