### ISSUE TITLE
Issue when pinning conda version

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#7734]
Until recently, the following workflow worked:

* Download Miniconda3 latest
* Edit ``~/miniconda3/conda-meta/pinned`` to include ``conda 4.5.10``
* Run `` conda install conda``

However, the last step now causes this error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda==4.5.10
  - conda[version='>=4.5.11']
Use "conda info <package>" to see the dependencies for each package.
```

Note that running ``conda install conda=4.5.10`` however works fine (including with the pinning in place).

**Comment by weaverba137** [comment]
@astrofrog are you certain that you are downloading "latest"? Because in ci-helpers, the miniconda version is hard-coded to 4.5.4, which is not the latest.

**Comment by kalefranz** [comment]
What's the output of `conda config --show-sources`?

**Comment by weaverba137** [comment]
We are specifically seeing this issue with conda in Travis tests.  Here is the output:
```
==> /home/travis/.condarc <==
changeps1: False
always_yes: True
==> envvars <==
channels: []
```

**Comment by weaverba137** [comment]
Also when explicitly using Miniconda3-latest, we actually get this error message from `conda install conda`:
```
PackagesNotFoundError: The following packages are missing from the target environment:
  - conda[version='>=4.5.11']
  - pycosat[version='>=0.6.3']
  - python[version='>=3.7,<3.8.0a0']
  - libffi[version='>=3.2.1,<4.0a0']
  - libstdcxx-ng=7.2.0
  - conda[version='>=4.5.11']
  - pycosat[version='>=0.6.3']
  - python[version='>=3.7,<3.8.0a0']
  - tk[version='>=8.6.7,<8.7.0a0']
  - zlib[version='>=1.2.11,<1.3.0a0']
  - conda[version='>=4.5.11']
  - pyopenssl[version='>=16.2.0']
  - cryptography[version='>=2.2.1']
  - asn1crypto[version='>=0.21.0']
  - conda[version='>=4.5.11']
  - pyopenssl[version='>=16.2.0']
  - cryptography[version='>=2.2.1']
  - cffi[version='>=1.7']
  - pycparser
  - conda[version='>=4.5.11']
  - pyopenssl[version='>=16.2.0']
  - cryptography[version='>=2.2.1']
  - idna[version='>=2.1']
  - conda[version='>=4.5.11']
  - pyopenssl[version='>=16.2.0']
  - cryptography[version='>=2.2.1']
  - six[version='>=1.4.1']
  - conda[version='>=4.5.11']
  - requests[version='>=2.12.4,<3']
  - certifi[version='>=2017.4.17']
  - conda[version='>=4.5.11']
  - requests[version='>=2.12.4,<3']
  - chardet[version='>=3.0.2,<3.1.0']
  - conda[version='>=4.5.11']
  - requests[version='>=2.12.4,<3']
  - urllib3[version='>=1.21.1,<1.24']
  - pysocks[version='>=1.5.6,<2.0,!=1.5.7']
  - conda[version='>=4.5.11']
  - ruamel_yaml[version='>=0.11.14']
  - yaml[version='>=0.1.7,<0.2.0a0']
```

**Comment by weaverba137** [comment]
Oops, ignore previous comment.  That was a version mismatch.

**Comment by weaverba137** [comment]
I double-checked and got that error message with Miniconda3-latest, with `echo 'conda 4.5.11' > miniconda/conda-meta/pinned; conda install conda`.

**Comment by astrofrog** [comment]
@weaverba137 - we hard-coded ci-helpers to 4.5.4 *because* of this issue which happened with the latest release of miniconda.

**Comment by weaverba137** [comment]
OK, fair enough, but now 4.5.4 isn't working either.  I think that's still a bug.

**Comment by weaverba137** [comment]
Here's how 4.5.4 fails:

1. Download Miniconda3-4.5.4.
2. `echo 'conda 4.5.10' > miniconda/conda-meta/pinned`
3. `conda install conda`

Result:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda
  - conda==4.5.10
Use "conda info <package>" to see the dependencies for each package.
```
Note that this error message is slightly different from the original posting.

**Comment by weaverba137** [comment]
More strangeness.  I use Miniconda3-4.5.4, and then pin conda to 4.5.4 (`echo 'conda 4.5.4 > miniconda/conda-meta/pinned`).  `conda install conda` succeeds, because conda is already 4.5.4.  However, then the next step is `conda create -n test python=3.5` and the error is:
```
Solving environment: - failed
PackagesNotFoundError: The following packages are missing from the target environment:
  - python=3.5
```

**Comment by weaverba137** [comment]
OK, it turns out this bug may have been conflated with another bug.  My tests were run in an environment that had `CONDA_CHANNELS` defined, but empty.  You can actually see that in the output of `conda config --show-sources`.
