### ISSUE TITLE
`conda activate` should update PYTHONHOME

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7736]
`conda activate` should update PYTHONHOME environment variable. 
It doesn't currently. 
Sorry if I miss something basic - we're just switching over to `conda`. 
Thanks.

**Comment by kalefranz** [comment]
Can you describe the problem you encountered where `PYTHONHOME` needed to be set?  I think we'd probably create more problems than we solve by setting this automatically.

**Comment by Tagar** [comment]
We have certain applications that rely on correct `PYTHONHOME` variable. 
For example, when we do `conda activate`, we could even switch from Python 2 to 3.. 
and it breaks things until we update all python related variables including `PYTHONHOME`.
Thanks.

**Comment by Tagar** [comment]
Agreed! Thanks so much. That wold be a great idea to unset PYTHONHOME

**Comment by Tagar** [comment]
@kalefranz does it look good to you to unset PYTHONHOME? I can submit a PR 
Thanks!
