### ISSUE TITLE
pip install breaks conda.cli dependency

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7737]
`conda` became broken after I installed a package with pip into that a conda envrionment.

```
$ conda create -n py27_rd python==2.7.13
$ source activate py27_rd 
$ pip install featuretools

(py27_rd) $ conda
Traceback (most recent call last):
  File "/opt/conda/envs/py27_rd/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
```
Any ideas how to fix this? 

One of our data scientists asked to install featuretools pip package ( I didn’t find it in conda).

**Comment by Tagar** [comment]
Check also https://github.com/ContinuumIO/anaconda-issues/issues/10029 
Not sure which repository it should belong to.

**Comment by kalefranz** [comment]
I think what happened was that featuretools declared conda as a dependency in setup.py, and then pip installed a *really* old conda from PyPI in that environment.  It looks like there's now a featuretools package published by the original authors on anaconda.org.  Probably just do something like

    conda create -n py27_rd python==2.7.13 Featuretools::featuretools

**Comment by Tagar** [comment]
thank you @kalefranz
