### ISSUE TITLE
please add featuretools pip package as a conda package

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7738]
Please add featuretools pip package as a conda package.

see https://github.com/ContinuumIO/anaconda-issues/issues/10029 , 
https://github.com/ContinuumIO/anaconda-issues/issues/10030, 
and https://github.com/conda/conda/issues/7737

Thanks.

**Comment by msarahan** [comment]
package requests belong on anaconda-issues.  Closing.

**Comment by kalefranz** [comment]
Feel free to contribute it yourself to conda-forge!

**Comment by Tagar** [comment]
@kalefranz I might try once I know if https://github.com/Featuretools/featuretools/issues/240 is resolvable.
Thanks.
