### ISSUE TITLE
Reduce disk usage of several environments sharing the same packages

### ISSUE THREAD

**Issue by mayito** [conda/conda#7745]
Hi,

Managing environments with conda is a great feature. But it has a cost in terms of disk usage. The same dependencies are duplicated over environments. Is there a way to share resources between environments ? 

Best regards.

**Comment by mingwandroid** [comment]
We use hardlinks when we can (which is the case for most files) so your per-env costs for any shared package is minimal.

**Comment by kalefranz** [comment]
I'd say we *aggressively* use hard links, when we can, so long as you're not overriding configuration parameters that would make conda behave differently than default.  Disk reporting tools usually lie for disk usage of conda environments.

Make sure your package caches are on the same mount as the locations of your environments.  You can't hard-link across disk mounts.
