### ISSUE TITLE
Command to port and environment between platforms/os

### ISSUE THREAD

**Issue by abergeron** [conda/conda#7766]
It would be very useful to be able to port an environment between platforms.  There isn’t any support for doing this currently. It would be useful for us since we have both x86 and power9 machines and I am sure we aren’t the only place that has this kind of setup.

This functionality could also be useful to migrate environments between different sites.

We have developed a sort-of workflow that can help do this, but it still requires manual intervention and knowledge of the intended usage:

On the source machine
```
conda list -e > env.lst
port.py env.lst > env.lst.ported
```

The last step mostly strips the build tags.  The code is below if you want to see it.

On the new machine
```
conda create -n <name> --file env.lst.ported
```

At the last step some manual tweaking is necessary since some packages are not available on all platforms (like MKL) and some platforms have version restrictions that others don't have.  Creating the env like this ensures that the solver runs so that it will not install a bunch of broken packages.

2 actions points to consider:
 - Can such thing can be added to conda (like a new command “conda create --convert” or “conda convert”).
 - This could be greatly improved if conda remembered the packages that were manually installed and we could just extract those to a list to port the environment instead of all those packages and their dependencies.

port.py:
```python
import sys

with open(sys.argv[1]) as f:
    for l in f:
        l = l.strip()
        if l[0] == '#':
            continue

        print('='.join(l.split('=')[:2]))
```

**Comment by jayfurmanek** [comment]
I have access to power9 hardware so may be able to help with this.
@kalefranz What are your thoughts on proceeding with this? Would you accept a PR. I suspect there would be some design aspects that you would like to weigh in on.

My thoughts are you would need a dependency processor - kind of a reverse solver - that would work on the existing package list. The output of the processor could be a list of available packages you could then feed back into the installer/solver to get the package set and correct dependencies.

It would be "best effort" so unavailable packages would just not be listed perhaps.
