### ISSUE TITLE
Request for better error message on conflicting specs

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#7771]
If, due to some reason, two conflicting specs are introduced to the solver, the error message is a bit cryptic to a person who isn't very much familiar with conda's codebase:

```
➜  ~ conda install mkl=2018 mkl=2019
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl[version='2018.*,2019.*']
```

In such cases, conda should say something of the sort: 'Conflicting specs specified' instead of '... packages are not available ...', since, in this case, both versions of the package were available, but couldn't be installed into the same environment.

**Comment by kalefranz** [comment]
I think that might relate to 

https://github.com/conda/conda/blob/21a24f02b2687d0895de04664a4ec23ccc75c33a/conda/resolve.py#L415-L424

**Comment by derenrich** [comment]
really it should tell you the two conflicting packages (as best as it can)
