### ISSUE TITLE
Duplicate package content clobbered and incorrectly removed

### ISSUE THREAD

**Issue by jamienoss** [conda/conda#7775]
## Current Behavior
 
 * conda 4.5.11
 * OSX 10.11.6

Both ``gcc`` and ``libgfortran`` install  ``libgfortran.dylib`` and one will clobber the other. Moreover, removal of ``gcc`` will incorrectly remove this library file (+ others related) yet still list ``libgfortran`` as an installed package. If ``libgfortran`` has been explicitly and independently installed, e.g. as a dependency of ``numpy``, removal of ``gcc`` should not remove these files. It is possible that other stuff is also incorrectly removed, I am only aware of ``libgfortran``.

### Steps to Reproduce

```
me$ conda install libgfortran
Solving environment: done

## Package Plan ##

  environment location: //anaconda

  added / updated specs: 
    - libgfortran


The following NEW packages will be INSTALLED:

    libgfortran: 3.0.1-h93005f0_2

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
```
me$ ls -lt /anaconda/lib/ligfortran.dylib
19 Sep 17 16:00 /anaconda/lib/libgfortran.dylib -> libgfortran.3.dylib
```

```
me$ conda install gcc
Solving environment: done

## Package Plan ##

  environment location: //anaconda

  added / updated specs: 
    - gcc


The following NEW packages will be INSTALLED:

    gcc: 4.8.5-8

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
```
me$ ls /anaconda/lib/ligfortran.dylib
19 Sep 17 16:02 /anaconda/lib/libgfortran.dylib -> libgfortran.3.dylib
```
``libgfortran`` got clobbered.
```
me$ conda remove gcc
Solving environment: done

## Package Plan ##

  environment location: //anaconda

  removed specs: 
    - gcc


The following packages will be REMOVED:

    gcc: 4.8.5-8

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
```
me$ ls /anaconda/lib/libgfortran.dylib
ls: /anaconda/lib/libgfortran.dylib: No such file or directory
```

## Expected Behavior

``libgfortran`` might need to be a dependency of ``gcc`` such that

 1) installing ``gcc`` doesn't clobber that installed by an explicit install of ``libgfortran``
 2) it is not removed when ``gcc`` is removed

The above possible soln. sounds more like a recipe issue, however, the "bug" here, I guess, is the clobbering. The incorrect removal is perhaps just a consequence of this since the clobbering changes ownership (assuming ownership meta exists).
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
 active environment : None
       user config file : /Users/jnoss/.condarc
 populated config files : /Users/jnoss/.condarc
          conda version : 4.5.11
    conda-build version : 3.9.1
         python version : 3.6.4.final.0
       base environment : //anaconda  (writable)
           channel URLs : http://ssb.stsci.edu/astroconda/osx-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : //anaconda/pkgs
                          /Users/jnoss/.conda/pkgs
       envs directories : //anaconda/envs
                          /Users/jnoss/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 1886:1031
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/jnoss/.condarc <==
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at //anaconda:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    defaults
_nb_ext_conf              0.4.0                    py36_1    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-clean            1.1.0                    py36_0    defaults
anaconda-client           1.6.14                   py36_0    defaults
anaconda-navigator        1.8.1                    py36_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
argcomplete               1.9.3                    py36_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.2                    py36_0    defaults
astropy-healpix           0.2.1                     <pip>
asv                       0.2.1                     <pip>
attrs                     17.4.0                   py36_0    defaults
babel                     2.5.3                    py36_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h1de35cc_1    defaults
blas                      1.0                         mkl    defaults
bleach                    2.1.3                    py36_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
ca-certificates           2018.03.07                    0    defaults
cctools                   895                  h7512d6f_0    defaults
certifi                   2018.8.24                py36_1    defaults
cffi                      1.11.5           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
chest                     0.2.3                    py36_0    defaults
clang                     4.0.1                h662ec87_0    anaconda
click                     6.7              py36hec950be_0    defaults
cloog                     0.18.0                        0    defaults
cloudpickle               0.5.2                    py36_1    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
compiler-rt               4.0.1                h5487866_0    defaults
conda                     4.5.11                   py36_0    defaults
conda-build               3.9.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
configobj                 5.0.6                    py36_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.27.3           py36h6ecb376_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_0    defaults
dask-core                 0.17.2                   py36_0    defaults
dbus                      1.12.2               h5243cc1_1    defaults
decorator                 4.2.1                    py36_0    defaults
dill                      0.2.7.1          py36hdf89ffe_0    defaults
distributed               1.21.4                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
dynd-python               removed                       0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
execnet                   1.3.0                    py36_1    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
filelock                  3.0.4                    py36_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.5.5                         1    defaults
gcc                       4.8.5                         8    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               h33f6a65_2    defaults
glob2                     0.6              py36h94c9186_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36hf9c35bd_2    defaults
greenlet                  0.4.13           py36h1de35cc_0    defaults
h5py                      2.7.0               np113py36_0    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
icu                       54.1                          0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imagesize                 1.0.0                    py36_0    defaults
intel-openmp              2018.0.0             h8158457_8    defaults
ipykernel                 4.8.2                    py36_0    defaults
ipython                   6.2.1            py36h3dda519_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.1.2                    py36_0    defaults
isl                       0.12.2                        1    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.11.1                   py36_1    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
jpeg                      8d                            2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
ld64                      274.2                h7c2db76_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libdynd                   0.7.2                         0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.30                        1    defaults
libsodium                 1.0.15               hd9e47c5_0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvm                      4.0.1                hc748206_0    defaults
llvm-lto-tapi             4.0.1                h6701bc3_0    defaults
llvm-openmp               4.0.1                hda82c8b_0    defaults
llvmlite                  0.22.0           py36h35728e8_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      3.7.0                    py36_0    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.0.2               np113py36_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
memory_profiler           0.52.0                   py36_0    defaults
mistune                   0.8.3                    py36_0    defaults
mkl                       2019.0                      117    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mpc                       1.0.3                h7a72875_5    defaults
mpfr                      3.1.5                h711e7fd_2    defaults
mpmath                    1.0.0            py36hf1b8295_2    defaults
msgpack-python            0.5.5            py36h04f5b5a_0    defaults
multipledispatch          0.5.0                    py36_0    defaults
nb_anacondacloud          1.4.0                    py36_0    defaults
nb_conda                  2.2.1            py36h349edbb_0    defaults
nb_conda_kernels          2.1.0                    py36_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
nbpresent                 3.0.2            py36hef4c988_1    defaults
ncurses                   6.0                  hd04f020_2    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h1190bce_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.4.1                    py36_0    defaults
numba                     0.37.0          np113py36h6d7bb6e_0    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
openpyxl                  2.5.1                    py36_0    defaults
openssl                   1.0.2p               h1de35cc_0    defaults
packaging                 17.1                     py36_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parso                     0.1.1            py36hc90e01c_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   11.0                     py36_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
pcre                      8.41                 hfb6ab37_1    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.4.0                    py36_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    3.4.2                    py36_0    defaults
pip                       18.0                      <pip>
pip                       9.0.1                    py36_5    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
pluggy                    0.6.0            py36hb1d0581_0    defaults
ply                       3.11                     py36_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
psutil                    5.4.3            py36h1de35cc_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.5.2            py36ha69170d_0    defaults
pyasn1                    0.4.2            py36h62a34ed_0    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h1de35cc_7    defaults
pycurl                    7.43.0                   py36_0    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.8.3                    py36_0    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.8                    py36_0    defaults
pytest                    3.4.2                    py36_0    defaults
pytest-cache              1.0                      py36_0    defaults
pytest-doctestplus        0.1.2                    py36_0    defaults
pytest-openfiles          0.2.0                    py36_0    defaults
pytest-pep8               1.0.6                    py36_0    defaults
pytest-remotedata         0.2.0                    py36_0    defaults
python                    3.6.4                hc167b69_3    defaults
python-dateutil           2.7.0                    py36_0    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2018.3                   py36_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     17.0.0           py36h1de35cc_0    defaults
qt                        5.6.0                         0    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.4.0                    py36_0    defaults
readline                  7.0                  hc1231fa_4    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.6           py36h7a28c18_0    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.7           py36h68959ac_0    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                38.5.1                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sortedcontainers          1.5.9                    py36_0    defaults
sphinx                    1.7.1                    py36_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.8                    py36_0    defaults
sqlalchemy                1.2.5            py36h1de35cc_0    defaults
sqlite                    3.22.0               h3efe00b_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.0                      py36_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
travis                    0.0.3                     <pip>
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
widgetsnbextension        3.1.4                    py36_0    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.7                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.2.3                h378b8a2_3    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by mingwandroid** [comment]
The GCC package is deprecated and there's no reason to use it.

**Comment by mingwandroid** [comment]
>  It looks like we don't have an alternative for that gcc 4.8.5 osx-64 package that was published.

What do you mean? We use clang on macOS and have no reason to continue to support, recommend or use GCC on macOS.

**Comment by mingwandroid** [comment]
People should use {{ compiler('c') }} in recipes and not worry about it.

**Comment by jamienoss** [comment]
@mingwandroid 
Hi, thanks for the response, however, the clobbering of one package's files by another still sounds like a bug, no? The depreciation of said package(s) should be irrelevant, no?

[Here's the doc](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) explaining the use of the separate compilers but I don't see any mention about the ``gcc`` package being deprecated and/or that it explicitly shouldn't be used.  Is there somewhere of somehow that I (and thus anyone else) should have known that the ``gcc`` package has been deprecated? Should there have been a warning upon my trying to install it?

Is there an issue/pr discussing the rationale for conda deciding not to publish gcc for OSX, that you could kindly point me to, please? 

So what about ``libgcc`` has that too been deprecated?

For fp arithmetic, the order of operation can be important, in which case, consistency in compiler optimizations is also important. Being able to use ``gcc`` (compiler) on OSX helps mitigate these kinds of issues when the target arch/OS for the software is, for example, linux, i.e. scientific calibration pipeline production software running on a linux machine that the consumer (astronomer) may wish to re-use on a Mac.

Of course, there is then the, perhaps more important, concern of using ``libgcc`` vs ``compiler-rt``, but ``clang`` can be directed to use others, [see LLVM doc here](https://clang.llvm.org/docs/Toolchain.html#runtime-libraries).

But, again, the depreciation of ``gcc`` is a separate issue to the bug that I believe this issue covers.

**Comment by mingwandroid** [comment]
Overlapping files in deprecated packages is fine by me, I've see no reason to attempt to fix deprecated things. Conda has no way of informing you of any news unfortunately. gcc was never really a user facing package from my perspective just something to get us out of a hole temporarily until we switched to clang.

I don't know what you mean about macOS and Linux cross. Our gcc package never supported that being a native macOS compiler.

If you want to create and use cross compilers you could look into how we construct gcc compilers these days. It's *very* cross happy being based upon crosstool-ng.

We've blogged about the new compilers and conda-forge are well aware of them. Deprecation of gcc was only implicit in that blog post.

**Comment by mingwandroid** [comment]
The rationale for not providing gcc on macOS is simply that we provide only compilers that we use (for this is the primary purpose of them; to create the Anaconda Distribution) and macOS has moved to clang and for that reason so have we.

The comment about math operation order needs elaboration, can you point to some bug demonstrating the problem?

**Comment by mingwandroid** [comment]
You should not expect exact results between OSes anyway due to libc differences.

**Comment by jamienoss** [comment]
> I've see no reason to attempt to fix deprecated things.

Agreed.

> Overlapping files in deprecated packages is fine by me...

I guess I'm assuming that there's some internal conda mechanism that tracks which files are content belonging to which package and that it this mechanism that is broken, irrespective of the packages in question.  Deprecated or not, the packages demonstrated here are just circumstantial.

Does such a mechanism not exist or is this reliant purely on name mangling to avoid package content collisions?

**Comment by jamienoss** [comment]
@mingwandroid I opened https://github.com/ContinuumIO/anaconda-issues/issues/10081 to cover the ``gcc`` issues discussed here.

**Comment by kalefranz** [comment]
> Hi, thanks for the response, however, the clobbering of one package's files by another still sounds like a bug, no?

You can use `conda config --set path_conflict warn` or `conda config --set path_conflict prevent`.  It's all built in since conda 4.3.

**Comment by mingwandroid** [comment]
> Does such a mechanism not exist or is this reliant purely on name mangling to avoid package content collisions?

No, this is problematic because we support arbitrary user channels so there cannot possibly be a global registry for what file is 'claimed' by what package. We *could* attempt something for `AD` itself though, if time permitted. Even then, what to index for this would be problematic, if we index the pre-AD 5.0 stuff as well as post-AD 5.0 stuff then we'd definitely encounter these overlaps.

**Comment by jamienoss** [comment]
@kalefranz 
>You can use conda config --set path_conflict warn or conda config --set path_conflict prevent. It's all built in since conda 4.3.

Awesome thanks for the tip. Though I have to confess, I'm quite alarmed that the "prevent" option is _not_ the default (or even at least the "warning"). If a user did want to clobber, then they can make that choice and drop this to a warning and march on.

I find the "silent treatment" from a package manager that can obliterate and mangle your already installed packages (installed by the very same manager) _very_ alarming!

Panic aside, what would be the aftermath or blocker for promoting at least one of the above (my pref. being the "prevent" opt.) to the default behavior?

I wonder what overlap, if any, already exists, i.e. has anyone tried installing all of AD using the warning option? Of course, there's every other channel.

**Comment by mingwandroid** [comment]
There is no overlap with AD non-deprecated packages, outside of that people are free to put whatever they want in packages.

**Comment by jamienoss** [comment]
@mingwandroid 
>>Does such a mechanism not exist or is this reliant purely on name mangling to avoid package content collisions?
>
>No, this is problematic because we support arbitrary user channels so there cannot possibly be a global registry for what file is 'claimed' by what package. We could attempt something for AD itself though, if time permitted. Even then, what to index for this would be problematic, if we index the pre-AD 5.0 stuff as well as post-AD 5.0 stuff then we'd definitely encounter these overlaps.

To me, it sounds like your use of  "global" means at the distribution end, i.e. AD, and not the client-side, i.e. indexed by ``conda``. I believe client-side indexing is how ``apt-get`` works (I might be wrong though, I don't really know and just had a quick Google to see).

What might be the best soln. is to have no index at all and instead have the concept of ownership exist as meta at the file level, i.e. each file would contain meta to which package it belonged. When ``conda`` goes to remove files this could be checked.

 * I don't know how, if at all possible, such meta can exist at the file level.
 * I expect ``cond`` doesn't do the actual deleting, the package scripts do and thus I'm not sure how easy if at all, this action could be wrapped and monitored.

The above coupled with the default prevention of file clobbering would (_should_) plug this chasm.

**Comment by mingwandroid** [comment]
I really could care less about this I'm sorry to say. No one ever runs into it unless they use deprecated packages.

**Comment by jamienoss** [comment]
>conda already warns or errors out on this condition though?

Not as default though, right, or have I missed something?

**Comment by mingwandroid** [comment]
Yes not as a default, but changing it to error probably results in a worse user experience than clobbering (which in this case clobbers with the exact same file anyway).

As I said no one has reported any problem with clobbering outside of this issue so it's not a pressing concern for us.
 
```
conda config --show | grep clobber
clobber: False
path_conflict: clobber
```

**Comment by jamienoss** [comment]
> Yes not as a default

Exactly.

> but changing it to error probably results in a worse user experience than clobbering

Sorry, just for the record, I completely fail to understand how this is even remotely true.

BTW: Isn't the ambiguity in having both ``clobber: False`` and ``path_conflict: clobber`` a bug in itself? Unless ``clobber`` relates to something else, eitherway this is still within the realm of being misleading.

> (which in this case clobbers with the exact same file anyway).

Only exact same filename, though right? Conda doesn't compute a checksum to see if the files are actually identical?

> As I said no one has reported any problem with clobbering outside of this issue

What ensures that they'd even know? That's the function of the path-conflict warning/error check, not the user. I only stumbled over this because of the incorrect removal aspect, i.e. a symptom. The more pressing symptom is the silent one where users are using package content that may not be correct. Again, how would they know?

At some level, this is actually a security issue. 

>it's not a pressing concern for us.

If this is a resource issue, I might be able to have a stab at it (or see if someone else can) and open a PR?

**Comment by mingwandroid** [comment]
The removal is definitely an issue, yes, I'm not sure how best to handle it (perhaps we could create a new hardlink somewhere in order to increase the reference count or something), but if you can think of a way and even better, make a PR, that would be great.

**Comment by jamienoss** [comment]
@mingwandroid 
Sorry, I really only meant changing the default behaviour (which I imagine is a trivial change). The bigger fish, might be, well, a bigger fish. 😄

**Comment by kalefranz** [comment]
I think the `main` channel is in pretty good shape.  I think `conda-forge` is probably going to have some pretty major problems.  The starting point is probably to encourage `conda-forge` to flip that config parameter first to `warn` and then to `prevent` in their build system over time.  If we can get `conda-forge` clean, we can probably start to look a transitioning the default value of the config parameter.

**Comment by jamienoss** [comment]
@kalefranz 

Cool, thanks for the intel. Sorry, I'm not really familiar with conda and wasn't aware that this option was an attribute of a channel. In which case, we can at least have ``astroconda`` flip this.

**Comment by jamienoss** [comment]
Well, not an attribute _of_ a channel but that can be set _by_.

**Comment by kalefranz** [comment]
I think you misunderstood.  It's not something that's set by the channel server-side.  It's all just a client-side config and is independent of channel.

What I meant was that it's not feasible to change the hard-coded default value that conda ships with without having the major channels "clean" first.  What I was describing was what the some of the steps might entail to get them to that state.  That is, transition that parameter on the package build side first, during package building.  Then over time, once the majority of users won't see warnings or errors that would be associated with it, we can flip the default value for package users (as opposed to package builders).

**Comment by jamienoss** [comment]
> I think you misunderstood.

Yep, I did. And am still not sure, sorry.

>without having the major channels "clean" first.

I'm interpreting "clean" as having non-overlapping file content and the above statement for them to be clean _only_ with respect to one another. I.e. not in absolution, as this negates the freedom of no-major channel packages to put whatever they want in their packages.

The transition on only the build side doesn't make sense to me. I'm assuming that you're stating the idea is that when a package is built with conda-build and then tested, the test installation will detect the file collisions, which could then be fixed thus cleaning them. However, I thought the test installation would include only those packages listed as "run requirements" and not everything else in the channel that the said package is distributed by, let alone the other "major" channels that it probably doesn't even have semantic understanding of. So how would that work?

Overall, I think you're saying that conda can't change the default because it would/could trigger a cascade of warning/errors upon installation of packages from the major channels. The packages (builders) should be given preferential treatment to having time to fix these first, such that no warnings/errors are created.

I would argue, that the responsibility of a package management system belongs predominantly to the major user base, i.e. the client, i.e. the user installing with it and _not_ the builder.

What about the compromise, bump the path conflict to "warn" on the install side and to "prevent" on the build side, until things are "clean"? At least this way the predominant user of conda is adequately represented, no?
