### ISSUE TITLE
More support for migration from one online machine to another offline machine

### ISSUE THREAD

**Issue by FukoH** [conda/conda#7779]
Upon now we can export conda environment by creating a yaml file and pass it to other people.But the receiver can only replicate the identical environment when they are also online. Is it possible to export the whole environment to some file,say tar.gz , that includes everything needed to facilitate offline migration?

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/5165

**Comment by kalefranz** [comment]
see also https://github.com/conda/conda-pack

**Comment by FukoH** [comment]
> see also https://github.com/conda/conda-pack

This is great and excactly what I needed.Maybe that some reference to `conda-pack`  being added to the document of [conda](https://conda.io/docs/) helps users to save their time finding such a useful feature. @kalefranz
