### ISSUE TITLE
Envs need to be activated before post-link scripts run

### ISSUE THREAD

**Issue by msarahan** [conda/conda#7789]
In Python 3.7, we removed a patch to Python that put Library/bin on PATH.  This was done because putting that on PATH broke the new conda activate stuff somehow.  A side effect of this change is that packages with post-link scripts may fail to run (see https://github.com/ContinuumIO/anaconda-issues/issues/10082 for one example).  At a minimum, we should be activating environments before we run post-link scripts.  We should think about pre-unlink and pre-link, too, I guess.

**Comment by kalefranz** [comment]
Without https://github.com/conda/conda/issues/6820, I'm a little bit nervous about the effect this could have on install times.  I guess we'll see.
