### ISSUE TITLE
Warn before accidentally installing packages in base environment

### ISSUE THREAD

**Issue by drdavella** [conda/conda#7791]
It would be really nice to have a warning prompt from `conda` if I accidentally try to install something in my base environment and `-n base/root` is not explicitly given. I use `conda` a lot, and have messed up my base installation several times this way, and I know I'm not the only one who has suffered this pain.

**Comment by mingwandroid** [comment]
Maybe the ability to lock any given env?

**Comment by mingwandroid** [comment]
`conda lock base` for example, and then conda will flat out refuse to mutate it in any way.

**Comment by drdavella** [comment]
@mingwandroid that's not a bad idea, but it's probably a lot more complicated than what I'm asking for.

**Comment by drdavella** [comment]
Well maybe they deserve to be annoyed! 😉

But seriously, what about some kind of global configuration option in `.condarc`? If you still think the environment lock is best, that would work too.

**Comment by mingwandroid** [comment]
I'd vote for a .conda_locked file in the root dir of each env, then `conda lock` would just create or delete that file and conda would respect it.

**Comment by mingwandroid** [comment]
FWIW, I don't think implementing this lockfile method would be more complicated than special casing a warning for just the base env.

**Comment by kalefranz** [comment]
xref: 
https://github.com/conda/conda/issues/5082

**Comment by kalefranz** [comment]
We also need to teach conda a mode where there is no base / user-default environment. You have to first create an environment and activate it before you can do anything at all. No default fallback.
