### ISSUE TITLE
Installing salmon gives error

### ISSUE THREAD

**Issue by razbarz** [conda/conda#7792]
I am trying to install Salmon. I downloaded miniconda, and installed it using the following line
`bash Miniconda3-latest-MacOSX-x86_64.sh`

I'm using Mac. I tried installing
with
`conda install salmon`
or 
`conda create -n salmon salmon`
and also
`conda install numpy`

Can anyone please help me with this?
I'm getting the following error - 

`Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/deafutlts/noarch/repodata.json>
Elapsed: 00:00.352245
CF-RAY: 45d82483fb412270-LAX

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/deafutlts

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

`

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by mingwandroid** [comment]
We do not have a `salmon` package. Installing `numpy` should work fine though. If you want to figure out why that's not working the please provide the information asked for in the issue template.

**Comment by kalefranz** [comment]
The reason we ask for information in the issue template is so that we don’t spin our wheels helping you with trivial errors. Somehow you’ve fat-fingered `defaults` in your channels list.
