### ISSUE TITLE
UnsatisfiableError creating environment for Python using internal server channels only

### ISSUE THREAD

**Issue by smnemeth** [conda/conda#7796]
## Current Behavior

I'm trying to install Python on systems with only internal internet capability behind firewalls.  I've copied the required packages from the defaults channel onto our local server, and re-indexed the local repo.  Actually this issue extends to a much larger set of packages, however, I've been able to reproduce the issue by trying to simply install Python.

### Steps to Reproduce

With the default channel not listed in .condarc:

```
$ conda create --name=test-python python=2.7.15
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=2.7.15
Use "conda info <package>" to see the dependencies for each package.
```
Then add default channel to .condarc:
```
$ conda create --name=test-python python=2.7.15
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.9
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /fds/miniconda3/envs/test-python

  added / updated specs: 
    - python=2.7.15


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0            http://localServer:8000/anaconda-packages
    certifi:         2018.8.24-py27_1        http://localServer:8000/anaconda-packages
    libedit:         3.1.20170329-h6b74fdf_2 http://localServer:8000/anaconda-packages
    libffi:          3.2.1-hd88cf55_4        defaults                              
    libgcc-ng:       8.2.0-hdf63c60_1        http://localServer:8000/anaconda-packages
    libstdcxx-ng:    8.2.0-hdf63c60_1        http://localServer:8000/anaconda-packages
    ncurses:         6.1-hf484d3e_0          http://localServer:8000/anaconda-packages
    openssl:         1.0.2p-h14c3975_0       http://localServer:8000/anaconda-packages
    pip:             10.0.1-py27_0           http://localServer:8000/anaconda-packages
    python:          2.7.15-h1571d57_0       http://localServer:8000/anaconda-packages
    readline:        7.0-h7b6447c_5          http://localServer:8000/anaconda-packages
    setuptools:      40.2.0-py27_0           http://localServer:8000/anaconda-packages
    sqlite:          3.24.0-h84994c4_0       http://localServer:8000/anaconda-packages
    tk:              8.6.8-hbc83047_0        http://localServer:8000/anaconda-packages
    wheel:           0.31.1-py27_0           http://localServer:8000/anaconda-packages
    zlib:            1.2.11-ha838bed_2       defaults                              

Proceed ([y]/n)? 
```

Proceeding with the install produces an environment where Python 2.7.15 works correctly.

Notice that both libffi and zlib are retrieved from the defaults channel, even though the same exact packages exist in our local server channel:

```
$ conda search libffi=3.2.1=hd88cf55_4
Loading channels: done
# Name                  Version           Build  Channel             
libffi                    3.2.1      hd88cf55_4  pkgs/main           
libffi                    3.2.1      hd88cf55_4  anaconda-packages   

$ conda search zlib=1.2.11=ha838bed_2
Loading channels: done
# Name                  Version           Build  Channel             
zlib                     1.2.11      ha838bed_2  pkgs/main           
zlib                     1.2.11      ha838bed_2  anaconda-packages

```

## Expected Behavior

Conda should create an environment for Python 2.7.15 using packages supplied via our internal local server channel.
Note the .condarc file enables channel priority, for whatever reason I can not get the environment to be created entirely using the local server.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/me/.condarc
 populated config files : /fds/miniconda3/.condarc
          conda version : 4.5.9
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : /fds/miniconda3  (writable)
           channel URLs : http://localServer:8000/anaconda-packages/linux-64
                          http://localServer:8000/anaconda-packages/noarch
                          http://localServer:8000/custom-packages/linux-64
                          http://localServer:8000/custom-packages/noarch
          package cache : /fds/miniconda3/pkgs
                          /home/me/.conda/pkgs
       envs directories : /fds/miniconda3/envs
                          /home/me/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.6.6 Linux/4.10.0-38-generic linuxmint/18.3 glibc/2.23
                UID:GID : 1000:1001
             netrc file : None
           offline mode : False
```
I have repeated this same issue using the latest Conda version, however after reading this [issue](https://github.com/conda/conda/issues/7626), I reverted Conda to 4.5.9 and added this to .condarc:

featureless_minimization_disabled_feature_flag: true

It does not seem to have an effect on the result.

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /fds/miniconda3/.condarc <==
ssl_verify: False
channel_priority: True
channels:
  - http://localServer:8000/anaconda-packages
  - http://localServer:8000/custom-packages
show_channel_urls: True
report_errors: False
featureless_minimization_disabled_feature_flag: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /fds/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.6.3                    py36_0    defaults
ca-certificates           2018.03.07                    0    http://localServer:8000/anaconda-packages
certifi                   2018.8.24                py36_1    defaults
cffi                      1.11.5           py36he75722e_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     6.7                      py36_0    defaults
conda                     4.5.9                    py36_0    defaults
conda-build               3.15.1                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.0                    py36_0    defaults
configobj                 5.0.6                    py36_1    defaults
cryptography              2.3.1            py36hc365091_0    defaults
filelock                  3.0.8                    py36_0    defaults
future                    0.16.0                   py36_0    defaults
glob2                     0.6                      py36_0    defaults
hdf5                      1.10.2               hba1933b_1    defaults
idna                      2.7                      py36_0    defaults
jinja2                    2.10                     py36_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
markupsafe                1.0              py36h14c3975_1    defaults
ncurses                   6.1                  hf484d3e_0    defaults
openssl                   1.0.2p               h14c3975_0    http://localServer:8000/anaconda-packages
patchelf                  0.9                  hf484d3e_2    defaults
pip                       10.0.1                   py36_0    defaults
pkginfo                   1.4.2                    py36_1    defaults
psutil                    5.4.7            py36h14c3975_0    defaults
pycosat                   0.6.3            py36h14c3975_0    defaults
pycparser                 2.18                     py36_1    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pysocks                   1.6.8                    py36_0    defaults
pysvn                     1.9.5                    py36_0    http://localhost/conda-repo
python                    3.6.6                hc3d631a_0    defaults
pytz                      2018.5                   py36_0    defaults
pyyaml                    3.13             py36h14c3975_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.19.1                   py36_0    defaults
ruamel_yaml               0.15.46          py36h14c3975_0    defaults
setuptools                40.2.0                   py36_0    defaults
six                       1.11.0                   py36_1    defaults
sqlite                    3.24.0               h84994c4_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.26.0           py36h28b3542_0    defaults
urllib3                   1.23                     py36_0    defaults
wheel                     0.31.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults
```
</p></details>

## Possible Work-around?
Does anyone know if there is any type of work-around that could allow me to produce an environment without using default channels?

## Other thoughts
Just throwing these thoughts out there after browsing many forums and issues:
- Potential issue with "conda index"
- Bad metadata in default packages
- Dependency solver problems

As I noted above, the larger issue involves many more packages.  I've been able to successfully build and deploy packages using the Anaconda compilers, CDT, X11, OpenGL, and GTK, which is no easy task, and I'm ready to deploy to fire-walled systems.  I never thought copying and using default packages would be an issue.  For reference, here's the [link to the original post](https://groups.google.com/a/continuum.io/forum/#!topic/conda/D0M1sVrl43g)

Really dislike putting this in as a bug, however, it looks like one, and I've tried every work-around I could think of.

Thanks for providing the community with such an awesome tool, and appreciate any help regarding this issue.

**Comment by mingwandroid** [comment]
Can you add -v -v -v to each run of conda and compare the output, particularly when the solver starts pruning packages? Are you indexing with the latest `conda-build`? Pinging @msarahan incase this is hotfix related somehow. I know we have been changing the indexing stuff somewhat recently.

**Comment by smnemeth** [comment]
> > As I noted above, the larger issue involves many more packages. I've been able to successfully build and deploy packages using the Anaconda compilers, CDT, X11, OpenGL, and GTK, which is no easy task
> 
> Do you have modern GTK packages that build from source? Which OSes? Just linux-64? Can you share them? conda-forge may be interested.

Yes, I have gtk2-2.24.31 building from source, along with ogre-1.9.0, along with some other dependencies (ois, and a few X CDT packages).  Unfortunately the in-house software I'm building against uses some of the older packages (gtk2, hdf5, boost), so I can't update to the latest yet.

We only build on Linux-64, so I have no way to do other OSes.

I'm glad to share some of the recipes (some are in-house or licensed code), however, my knowledge for building conda packages is a little dated.  I did a lot of development 4-5 years ago, and much has changed.  I'm sure what I'm doing could be done better with more understanding.  The documentation is great as is the web support, but it's still hard sometimes to connect all the dots on how it works, and Conda has grown considerably :)

I'll work on getting the recipes into my channel this next week.

**Comment by smnemeth** [comment]
> Can you add -v -v -v to each run of conda and compare the output, particularly when the solver starts pruning packages? Are you indexing with the latest `conda-build`? Pinging @msarahan incase this is hotfix related somehow. I know we have been changing the indexing stuff somewhat recently.

Yes, I'm using the latest conda-build-3.15.1.  I've attached the verbose output both with and without using defaults in .condarc.  

[conda_create_python_no_defaults.log](https://github.com/conda/conda/files/2409022/conda_create_python_no_defaults.log)
[conda_create_python_with_defaults.log](https://github.com/conda/conda/files/2409023/conda_create_python_with_defaults.log)

**Comment by mingwandroid** [comment]
I see:
```
 DEBUG conda.resolve:filter_group(277): readline: pruned from 7 -> 5
```

```
 DEBUG conda.resolve:filter_group(277): readline: pruned from 1 -> 0
```

So I think you are missing a readline package somehow? It would be good to know what packages you have.

**Comment by mingwandroid** [comment]
> Yes, I have gtk2-2.24.31

OK, I was hoping for something more recent but starting from your recipes may be useful, then again we need to use meson for more modern gtk I suppose.

**Comment by smnemeth** [comment]
> I see:
> 
> ```
>  DEBUG conda.resolve:filter_group(277): readline: pruned from 7 -> 5
> ```
> 
> vs:
> 
> ```
>  DEBUG conda.resolve:filter_group(277): readline: pruned from 1 -> 0
> ```
> 
> So I think you are missing a readline package somehow? It would be good to know what packages you have.

Here's what conda search shows for readline:
sn5970@DCFDVM-01 ~ $ conda search readline=7.0=h7b6447c_5
Loading channels: done
# Name                  Version           Build  Channel             
readline                    7.0      h7b6447c_5  pkgs/main           
readline                    7.0      h7b6447c_5  anaconda-packages

**Comment by mingwandroid** [comment]
> I've been able to successfully build and deploy packages using the Anaconda compilers, CDT, X11, OpenGL, and GTK, which is no easy task

Can you explain the issues you have/had here?

**Comment by mingwandroid** [comment]
Do you have this readline package in your local package channel?

**Comment by smnemeth** [comment]
> Do you have this readline package in your local package channel?

Yes, the exact same readline package copied from the default repo into the local package channel"

$ conda search readline=7.0=h7b6447c_5
Loading channels: done
Name                  Version                         Build  Channel             
readline                    7.0      h7b6447c_5  pkgs/main           
readline                    7.0      h7b6447c_5  anaconda-packages

**Comment by mbargull** [comment]
The metadata from the `defaults` channel is more up to date than the original one from the package.
This is more of a `conda-build` (since `conda index` is part of `conda-build`) or rather Anaconda repository issue. `conda` itself has no part in generating/updating that metadata.
For more information see https://github.com/conda/conda/issues?q=metadata+hotfixes.
```
$ curl -sL https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2 | tar -xjO info/index.json
{
  "arch": "x86_64",
  "build": "ha838bed_2",
  "build_number": 2,
  "depends": [
    "libgcc-ng 7.2.0.*"
  ],
  "license": "zlib",
  "license_family": "Other",
  "name": "zlib",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1510092253691,
  "version": "1.2.11"
}
$ conda search --info zlib=1.2.11=ha838bed_2 --json                                                                                                                                                                                                             
{
  "zlib": [
    {
      "arch": null,
      "build": "ha838bed_2",
      "build_number": 2,
      "channel": "https://repo.anaconda.com/pkgs/main/linux-64",
      "constrains": [],
      "depends": [
        "libgcc-ng >=7.2.0"
      ],
      "fn": "zlib-1.2.11-ha838bed_2.tar.bz2",
      "license": "zlib",
      "license_family": "Other",
      "md5": "7da835fb21e0c8da332aaef68f9ab80f",
      "name": "zlib",
      "platform": null,
      "size": 103683,
      "subdir": "linux-64",
      "timestamp": 1510092253691,
      "url": "https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2",
      "version": "1.2.11"
    }
  ]
}
```

**Comment by smnemeth** [comment]
> > I've been able to successfully build and deploy packages using the Anaconda compilers, CDT, X11, OpenGL, and GTK, which is no easy task
> 
> Can you explain the issues you have/had here?

**Before reading further, what follows is NOT a part of this issue, and is only supplemental information posted to answer a question, i.e. these issues below are not related to the issue of this thread.**  

Here's a high level run-down of what I recall being the biggest issues developing the following packages:

GTK (GIMP Toolkit)
---------------------
gtk2-2.24.31
pygtk-2.24.0
gdk-pixbuf-2.36.12
pygobject-2.28.7
libglade-2.6.4
atk-2.22.0

OGRE (Object-Oriented Graphics Rendering Engine)
---------------------------------------------------------
ogre-1.9.0
assimp-3.2.0
ois-1.3.0
zziplib-0.13.69

Issues and Challenges
------------------------
1) Understanding of differences between defaults and conda-forge channels.  Conda-forge has a number of xorg-* packages that appeared to be what was needed for building packages that rely upon X11.  Tried using conda-forge packages, but at the end of the day it did not work.  Ended up using the CDT packages from defaults.  There seems to be an architectural difference between the two channnels.  At the end of the day I wanted our software to use Anaconda defaults as much as possible, and then build the few packages we needed to supplement defaults -- so I generally stayed away from using conda-forge (except for mesalib).

2) Understanding how to use the CDT packages.  I think I finally understand how these are intended to be used.  Basically the CDT packages are surrogates used primarily for compiling and build time linking of packages with dependencies to these core OS utilities (like X11).  Then at run-time, the package built with CDT packages does not use the CDT package, but instead uses the host OS packages.  So the CDT packages provide a consistent ABI built into the package to allow for run time execution using the host OS library.  (Please correct this as needed)  I also added in a few CDT packages that were not available 
(libxaw-cos6-x86_64, libxdmcp-cos6-x86_64, libxmu-cos6-x86_64, libxpm-cos6-x86_64 + devel packages of each).  

3) Getting packages to build with the new compiler using a recipe.  Some packages required patches to work with the new compiler.  Some packages needed extra dependencies in the build section of the recipe.  Both cmake and autotool builds would sometimes require input spec tweaks to get them to find packages in the conda build environment.  Also issues getting pkgconfig to pick up packages in the conda build environment.  

4) libuuid and memcpy undefined symbol issues (ABI mismatch?). Can't recall off-hand which packages, but libICE and libSM come to mind too.

5) Picking the best versions of FOSS packages.  There is certainly some threading of the needle going on here.  Some of our in-house software is not forward compatible with the very latest versions, so we had to pick older versions of FOSS packages that are compatible.  Also, we are targeting Centos 7 for deployment so we picked packages that are reasonably close to the version on Centos 7.  This was mainly done to avoid potential issues and use a baseline that is known to work.

I'll share these package recipes soon, and hopefully learn from folks that know more how to build them.

**Comment by smnemeth** [comment]
> The metadata from the `defaults` channel is more up to date than the original one from the package.
> This is more of a `conda-build` (since `conda index` is part of `conda-build`) or rather Anaconda repository issue. `conda` itself has no part in generating/updating that metadata.

This metadata issue was very hard to figure out, and there was very little guidance from the error on how to proceed.  Is there a best practice on how to host an internal repo that mirrors some of the packages in the defaults channel?

**Comment by kalefranz** [comment]
We're in the process of updating `conda index` to be able to apply metadata patch instructions that can also be downloaded for the channel.  It hasn't completely landed yet, but we should make sure the process is documented for creating partial, local conda channels from remote channels by downloading individual packages.

**Comment by smnemeth** [comment]
Note for others with this issue, I was able to work-around the issue by copying the Anaconda channel into a local repo, and then don't modify the repo or attempt to re-index.

Based on kalefranz reply above, it sounds like my issue is understood and will hopefully be resolved in the future.  Thanks for all your help.
