### ISSUE TITLE
CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7800]
## Current Behavior

```
$ docker run --rm -it condaforge/linux-anvil
$ conda create -n cmake cmake
Solving environment: failed

CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 00:00.087525
CF-RAY: 45f68fe61ccd2444-IAD

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```

### Steps to Reproduce

Please see above.

## Expected Behavior

Creation of the environment should proceed.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.5.11
    conda-build version : 3.13.0
         python version : 3.6.6.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/4.9.93-linuxkit-aufs centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /home/conda/.condarc <==
channels:
  - conda-forge
  - defaults
show_channel_urls: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    conda-forge
asn1crypto                0.24.0                   py36_3    conda-forge
beautifulsoup4            4.6.3                    py36_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
clyent                    1.2.2                      py_1    conda-forge
conda                     4.5.11                   py36_0    conda-forge
conda-build               3.13.0                   py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
curl                      7.61.0               h93b3f91_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
filelock                  3.0.4                      py_1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
git                       2.18.0          pl526hbb17d3c_1    conda-forge
glob2                     0.6                        py_0    conda-forge
gosu                      1.10                          0    conda-forge
idna                      2.7                      py36_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_2    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
markupsafe                1.0              py36h470a237_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
patchelf                  0.9                  hfc679d8_2    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
psutil                    5.4.7            py36h470a237_1    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pysocks                   1.6.8                    py36_2    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py36_1    conda-forge
ruamel_yaml               0.15.63          py36h470a237_0    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tini                      0.18.0               h470a237_1    conda-forge
tk                        8.6.8                         0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                     py36_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</p></details>

**Comment by jakirkham** [comment]
Seems to resolved itself. Maybe it was transient. Closing...

**Comment by pkgw** [comment]
I feel like I've been seeing this a lot over the past few days. I don't have links to CI logs since they've been obliterated by me rerunning the relevant builds, but there have been periods where I've been getting 50x errors for what feels like ~50% of the builds I'm attempting to run.

**Comment by ctrueden** [comment]
I'm certainly seeing it now, due to apparent anaconda.org downtime at the moment.

https://twitter.com/tomprimozic/status/1045027628153999361

**Comment by mbargull** [comment]
From https://gitter.im/conda-forge/conda-forge.github.io?at=5bab71328196693171b942fb:
> Anaconda.org is down. We're aware of it and working on it.

**Comment by Carnageous** [comment]
As this issue is currently affecting our team as well, are there any steps on your side to resolve this issue? https://api.anaconda.org/docs is also down for more than two hours now, so it might be somewhat important to investigate, in my opinion.

**Comment by JosjaVanBever** [comment]
Dear, I have the same issue. Error comment below. It prevents me from using a package that I really need at this moment and I currently haven't found a workaround to use that package from another source when running python under the conda environment.


Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/abinit/linux-64/current_repodata.json>
Elapsed: 00:00.579982
CF-RAY: 5c7bcbec8ed1f969-BRU

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.

**Comment by fconstancias** [comment]
same here

**Comment by its-jd** [comment]
same here

> Dear, I have the same issue. Error comment below. It prevents me from using a package that I really need at this moment and I currently haven't found a workaround to use that package from another source when running python under the conda environment.
> 
> Collecting package metadata (current_repodata.json): failed
> 
> CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url https://conda.anaconda.org/abinit/linux-64/current_repodata.json
> Elapsed: 00:00.579982
> CF-RAY: 5c7bcbec8ed1f969-BRU
> 
> A remote server error occurred when trying to retrieve this URL.
> 
> A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
> fulfill a valid request. The problem may be spurious, and will resolve itself if you
> try your request again. If the problem persists, consider notifying the maintainer
> of the remote server.

**Comment by hurtadosanti** [comment]
Same here

**Comment by lobracost** [comment]
Same here

**Comment by Rinak96** [comment]
Same here

**Comment by git31** [comment]
Same here, hope to fix it quickly.

**Comment by LeonardoEmili** [comment]
Same here, did anybody find a workaround to temporarily fix this?

**Comment by MuhammadAsadJaved** [comment]
+1

**Comment by VardanB19** [comment]
The same here, although on Friday was ok.
Hope, it will be solved soon.

**Comment by AlexanderSidorenkov** [comment]
+1

**Comment by hijkzzz** [comment]
+1

**Comment by HandsomeBrotherShuaiLi** [comment]
+1

**Comment by Rania-Sayed-Ahmed** [comment]
Same here!

**Comment by ebbekyhl** [comment]
Glad that I am not the only one...

**Comment by pokbe** [comment]
same here!

**Comment by sebastientourbier** [comment]
Same here!

**Comment by blacmamba69** [comment]
Same here :(

**Comment by llewr0** [comment]
+1

**Comment by xiao-susie-bai** [comment]
+1!

**Comment by cgharo** [comment]
Same here!

**Comment by jaeseo-park** [comment]
+1!

**Comment by ejones18** [comment]
+1!

**Comment by selvakumardreams** [comment]
CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/schrodinger/win-32/repodata.json>

**Comment by linusyukwong** [comment]
I bypassed the issue by using mirror sources, such as the Tsinghua mirror in China.

**Comment by MuhammadAsadJaved** [comment]
@linusyukwong  Tsinghua mirror is not working for me.

**Comment by jileltgen** [comment]
same here ;(

**Comment by emolinaro** [comment]
+1

**Comment by amin-nejad** [comment]
+1

**Comment by a-r-j** [comment]
+1

**Comment by sh1ng** [comment]
+1

**Comment by eliransr** [comment]
same here

**Comment by rajeshg007** [comment]
Same here, Since Last few of Hours.
Any workaround would be appreciated.

**Comment by abij** [comment]
Same here. 
Updating conda to 4.8.4 locally did still work.

**Comment by HandsomeBrotherShuaiLi** [comment]
The Tsinghua mirror did not work, my error is due to `conda update` command.
Details as follows:

> CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/pytorch/linux-64/repodata.json>
Elapsed: 00:10.254952
CF-RAY: 5c7cce8e9f2401a3-SIN A remote server error occurred when trying to retrieve this URL. A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server. ERROR: Service 'worker' failed to build: The command '/bin/sh -c conda update -n base -c defaults conda  && conda env create -n venv -f ./venv.yml  && conda clean -y --all' returned a non-zero code: 1

**Comment by NagabhushanSN95** [comment]
Guys instead of posting +1, please add a like to the first comment. That way we know we are not alone, while not spamming the thread.

**Comment by J-Med** [comment]
+1

**Comment by VardanB19** [comment]
> Same here.
> Updating conda to 4.8.4 locally did still work.

For me as well, thank you.

**Comment by homsrego** [comment]
+1

**Comment by jmuddle** [comment]
It appears to be back up https://conda.anaconda.org

**Comment by ebbekyhl** [comment]
> 
> 
> It appears to be back up https://conda.anaconda.org

Best news of today! Thank you everyone for your contributions. See you soon in some other thread!
