### ISSUE TITLE
Solver improvements: 6) explore more creative and aggressive parameter space reduction

### ISSUE THREAD

**Issue by mbargull** [conda/conda#7809]
xref: From @kalefranz in https://github.com/conda/conda/issues/7700#issue-354111815
> explore more creative and aggressive parameter space reduction (i.e. `get_reduced_index()`)

It would be nice to improve the "pruning step", i.e., `conda.resolve.Resolve.get_reduced_index`, such that the overall number of packages/versions/builds the SAT solver has to consider can be significantly reduced. This could speed up the SAT solver invocations by a great deal, esp. for Conda environments with a large number of packages and packages with a large number of dependencies, e.g., those involving the `anaconda` package.

----
As a subordinate goal, there is also potential to reduce the time taken by `get_reduced_index` itself:

- From @wolfv in https://gitter.im/conda/conda?at=5ba8a2d67dca30650347e160:
  > Now I can at least get a feel for where conda looses a lot of performance
  > The one thing seems to be that it re-fetches the repo json data which takes quite some time
and the other step is "pruning" 

- From @mbargull in https://gitter.im/conda/conda?at=5babe0abfe3778111000c16c:
  > But even without being familiar with that code, I'm pretty sure there is potential for improving it; in terms of speed and also logic/output, resp.!

----
Regarding the "more \[...\] aggressive \[...\] reduction"-part: A strategy that deviates more from the current behavior would be to:
- allow `conda` to "try out" solving an environment with a more rigorously trimmed down index
- by, e.g., completely removing old versions or builds from the search space (since usually newer versions/builds are preferred by the user),
- sucht that the SAT solver can potentially run much faster on that trimmed index and thus more quickly return a solution.

If the index is trimmed so much such that no solution could be retrieved at all, we'd fallback to solving with the less aggressively pruned index.
(Probably a bit tricky to get this right without breaking anything, though :wink:.)

----
Some other refs:

- from @mbargull in personal conversation with @kalefranz:
  > ways to reduce solver search space
  > - introduce some way to mostly (apart from when explicitly required)
  >   disregard old builds (i.e., builds w/o the highest number)
  > - think about adding some default constrains (which may be overridden 
  >   explicitly or implicitly when encountering conflicts) like
  >   - "r >=3.4"
  >   - "r-base >=3.4"
  >   - "python >=3.5" (or "python >=2.7,<3.0a0|>=3.5" because reasons...)

- From @wolfv in https://gitter.im/conda/conda?at=5ba91da433da0f649e48c8f5:
  > just thinking out loud: Couldn't there also be a way to make a wishful hypothesis, which is: take the newest version of everything
  > then run the SAT solver
  > check if it breaks, and where it breaks
  > then add the next "level" of semantic versions (i.e. all versions of the X.Y.**Z** set
  > and then move upwards

- From @wolfv in https://gitter.im/conda/conda?at=5baa2968aedb375b9c43dbc1:
  > I've made this flow chart to put some ideas on how to speed conda up
  > [https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#...](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#R5Vtbc6M2FP4t%2B%2BCZ9iEe7nYeEzdpd6Z7mclDt48yyKBGIBaEL%2F31lYS4CcUhayBpNg8OHIQkfzrfuUle2Jv4%2BHsG0ugTCSBeWEZwXNi%2FLSzLtEyb%2FeOSUynxVmYpCDMUyEaN4AH9C6XQkNICBTDvNKSEYIrSrtAnSQJ92pGBLCOHbrMdwd1RUxDCnuDBB7gv%2FQsFNCqla9do5H9AFEbVyKYhn2yB%2FxhmpEjkeAvL3om%2F8nEMqr5k%2BzwCATm0RPbdwt5khNDyKj5uIObYVrCV790%2F8bSedwYTOuQFq3xhD3ABqxl7mL16uyOsBzZBepKgeN8LUj24ysWS3bAGjpEem4fsKuT%2FbzEDgj39BOItYP8%2FJjkFGAOKSMJuCcPDSOCBfX5lDflqyGHZVMuRy34kSvUkLAqPXB7RGDOByS5zmpFHuCGYZEySkATySSKMFRHAKEzYrc%2BggUx%2Bu4cZRWzNb%2BSDGAUBH%2Bb2ECEKH1Lg8zEPTMOZTKwp5KgZ9bR4B%2FD4JPJmvZ6MJ5DEkGYn1qR6wZYqcOqq%2FqHRt9W1lEVtXatUDUgdD%2Buum3VmF3Kp9cu%2B7uEKA0YAeUsyGpGQJADfNVIFgdYCwCOi37h46cq7v%2BWTfyClJ8luUFDCRE3ffxKSynblbPgUzoPJZkyKzJetXGkYQBZC2WqlhzyDXPP23d4vwc99kjYB2vO%2BpUo1xMBwR%2Fs02ZA4BtxW3LT0X3RRqf%2BP9MqsYsBJh0rScYy2W%2FZ55ZcmMwBXO5I1nNtm6njqLBRl6aqCji4t9RiBK2uFKl6fKzV%2F2lzxRqBK1e%2FYXGEusiGLsVyt5O1XmCE2SW6hxMsMouz0rXqd35QvWO7kBPPGJ5h49SbLwKnVICUooXmr569c0Cy%2F43qd9bc8V1nBssdmPeupDVpir8fmikGSJur6Y8wCEb7OzH2nXOhjUgSzUMFxFC5o%2FIZpabiwHoMLznvwG6u%2BWpvWTI5j1VO1e0j9SBh3LKYuoqGc615GYm6vI8BiXJy%2FNSNsuXMaYbNPUeBH56j5DCAgT8vEYYeOHMRRuGkqEFl9iLypEPJGpWbldCQ3a7czOTlNS8NO93W8jttZTcdQUimlvbc62%2F5iL2XOFLS%2FsbWfK6SvBm%2BZmAeIuY1gZGVchTmtA2lmJXKRyL6ySbbdrsGxnYE22RnB4tjWu9dHTYZpP7Eio%2Bujff1Twruei%2B7PpPAyP4%2BgKGMxwHKKkpBfJnuUkSSGwvaDEPAsu2MjpHX4MCClL0VfEiwcUxA0STsMutEgA5%2Bjh1nnP5y2Dw6O2tUzXsFc%2B9D3e6U29mS7dh13pIKYa3WNmWP3jZmtM2arEYxZrZ%2F%2F68zG1KQ2rbLytIyy3kVyqIXQnsso9dPDMuBoGQUF4qoCEcEjYAiw7522CkhSWteUrBdzP3DhOnB03F9bW9vzRiqGrxTuazInbVVjjEDGeveetkKuo9Rzedpq8JZSf4YH7saaONoAe4Aw2HJo76fX8RE0tk7apca6xkCNdcfQ2FGT%2FYl1z9bo3igJfS8DN61uBu6pW2XlHORbCtwvS8arb9XOFkEMz%2BSGb1GJvS5e8%2BpwPwB%2FKHwf5iza3XB9iRCPew%2BAf34vkP%2F4oYfp3Pm2gpc3tPY%2BRoGviobH9lKrtpvqbDgZHSe1fMl%2BUwDySAx7gd1Y9%2B3GKxUClcTEe6YQqLZ3Rt6uqpA5n7re5DxxLXLhaEX2yK7Z59VVkYYZCODg9JS9RHgnaUbilH%2FPE89I7xPR5%2Fm%2BXpmvqpPWEtadirDuNIR9O2GlXR3NahdwnAspOhje%2FpaQRnfvOtWaSDgTobg%2BSXYY%2BZz3g1T3Lbpv51qJQTXlX9OZqGJiO0Pw%2F1gfQUm757ze%2FJkTFVxPc%2BhEC%2B4YtsOZyNnPW0u5uJir968rRwnD3FW3i%2FHCfHuQq9UYmeGu9T0YInXrc1ZD5PRTsdrIYOI%2F8sNx8LIDdXV%2FleABxSmGQt1xUZ5prRdv%2B5xh%2B5EZ3Ii9AfWMyKaEzjICfsSVh3kBOC3HHHe4uR4F1y80avY3ulgavcYpyXO0RRhRBPNzCzDN5MsliUkGF9pzOw2v%2BTIxW8S3X0LGKLHZ8wtchsuF3DYS0fWJ2d1k0S6KQeovf%2BUzSgKREEMuZFzOAFdoQ7Sh%2FBBMMxjv8jMRB7cLMbGIHIT9ELW1Oqtu1NY4kALz7rflY1KE0fKlwHHQNVS7xIO%2FyhaUp%2BYLuoOmuhM8dZHzIkM2zREe5dzo9MdGHc2%2B7sWZ%2B2AQV5OAaCzX6252tTSM60qgntmdH19nri0q5%2Bl986G%2FGDHXul%2BMPMi9beNjsie%2B%2BKFI26j%2FHD8KuVYP9Kw1gZStM0Avtz%2FstvmdURkbNz%2Fmsu%2F%2BAw%3D%3D)
  > sry for the link size, but would implementing such a workflow make sense or is it changing the behavior?
  > in other words, does install currently update the entire environment?
  > feel free to edit the chart or point me at the conda specs which detail the behaviour of install etc.

- From @mbargull in https://gitter.im/conda/conda?at=5babe0abfe3778111000c16c:
  > I briefly mentioned something in that direction to Kale, some time ago. I think it would be very nice to come up with a scheme of "try a fast solve with a reduced number of versions/builds first; if it fails, do the slow standard stuff", yes! But like with most of this stuff, the tricky thing is to come up with something that works for most cases and also doesn't lead to undesirable result in comparison to what you get without those tweaks -- corner cases everywhere :wink:. If you can work out some nice ideas/strategies for this, that'd be really nice and highly appreciated!

----
And although the following comment is not about reducing the number of packages/builds in `get_reduced_index`, it is still somewhat relevant to this issue since it can trim down the search space in the SAT solver itself:
- From @mcg1969 in https://github.com/conda/conda/issues/6890#issuecomment-366016327:
  > That said, I do have one idea that may help. Right now we do two “version” passes: one for the requested packages and one for everything else. I would suggest that more levels may be warranted; e.g.
  > 
  > 1. Requested packages
  > 2. Any other package that has ever been requested
  > 3. The top level dependencies of any of the packages in 1 & 2
  > 4. Any other dependencies
  > 
  > Layer 4 might even have multiple levels, a sort of breadth-first search in the dependency tree.
  > 
  > The point is that the lower level the dependency is, the less important it’s version maximization ought to be considered. Or put the other way, the higher up the tree we go, the more important its version should be.

**Comment by msarahan** [comment]
Some small work done on this in #8016, but there's more good ideas in this issue to be tried, so I'm leaving this open.
