### ISSUE TITLE
Even i am facing this problem help me out

### ISSUE THREAD

**Issue by Vivekreddyk** [conda/conda#7810]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\VIVEKREDDY\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\VIVEKREDDY\.condarc", position 0

`$ C:\Users\VIVEKREDDY\Anaconda3\Scripts\conda install anaconda-navigator=1.8.5`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\VIVEKREDDY\Anaconda3
                 HOMEPATH=\Users\VIVEKREDDY
                     PATH=C:\Users\VIVEKREDDY\Anaconda3\Library\bin;C:\Windows\System32;C:\Progr
                          am Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\j
                          dk1.8.0_151\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbe
                          m;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\Open
                          SSH\;C:\Users\VIVEKREDDY\AppData\Local\Programs\Python\Python37-32;C:\
                          Users\VIVEKREDDY\AppData\Local\Programs\Python\Python37-32;C:\Users\VI
                          VEKREDDY\Anaconda3;C:\Users\VIVEKREDDY\AppData\Roaming\Microsoft\Windo
                          ws\Start Menu\Programs\Anaconda3
                          (64-bit);C:\Users\VIVEKREDDY\Anaconda3\Scripts;C:\Program Files
                          (x86)\Dev-Cpp\MinGW32\include\GL;C:\Users\VIVEKREDDY\AppData\Local\ato
                          m\bin;C:\Users\VIVEKREDDY\AppData\Local\Programs\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\VIVEKREDDY\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\VIVEKREDDY\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\VIVEKREDDY\Anaconda3\pkgs
                          C:\Users\VIVEKREDDY\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\VIVEKREDDY\Anaconda3\envs
                          C:\Users\VIVEKREDDY\AppData\Local\conda\conda\envs
                          C:\Users\VIVEKREDDY\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

**Comment by jfishe** [comment]
I ran into this problem trying to reproduce from an exported environment.yml. 

Turns out Windows does not use ASCII encoding when redirecting from standard output:

``` powershell
conda env export > bad.yml
conda env create -f .\bad.yml
```

The workaround in PowerShell is:

``` powershell
conda env export | Set-Content -Encoding Ascii -Path .\good.yml
```

I don't know how to accomplish the same thing from cmd.exe Anaconda Prompt.

The two files are attached and look frustratingly similar in a text editor.

[bad.yml.txt](https://github.com/conda/conda/files/2922614/bad.yml.txt)
[good.yml.txt](https://github.com/conda/conda/files/2922615/good.yml.txt)

I added `.txt` on the end so Github would allow the file type.

**Comment by jjhelmus** [comment]
The error message produced here `ReaderError: unacceptable character #x0000: special characters are not allowed` indicates that there are special characters in your `.condarc` file.  These must be removed for conda to function correctly.

**Comment by tamersalama** [comment]
I found out that one of my editors was changing the `environment.yml` file encoding. Changing the file encoding to UTF-8 fixed the issue.

**Comment by phpmaps** [comment]
@jjhelmus I believe @tamersalama is on to something.  After exporting my environment to disk, then using that file to create a new conda environment, I too ran into problems on Windows.

The exception thrown when creating a environment from file was:

```"special characters are not allowed"```

I think when the OS pipes out the file it does not encode it correct, aka not UTF-8.  Once you change the file to UTF-8 (say in NotePad++) create env works from via file.

``` conda env export --from-history >environment.yml ```

This for some reason does not write the file to disk using UTF-8.

https://stackoverflow.com/questions/56298073/cant-create-conda-environment-from-environment-yml
