### ISSUE TITLE
Conda ignores no_proxy if proxies are configured via condarc instead of env vars

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#7818]
Mr. Anderson works for the company: thematrix.com . They have their own team of minions to build conda packages (apparently binary compatible with defaults) and they host their internal packages at: http://conda.thematrix.com . However, they do rely on defaults for the non-in house packages and occasionally conda-forge for testing stuff in throwaway environments.

Everything from within thematrix to the outside world has to go through proxy.thematrix.com:3128

Usually, for proxy-env-var-honoring applications, the following proxy configuration suffices:
```
http_proxy=http://proxy.thematrix.com:3128
HTTP_PROXY=http://proxy.thematrix.com:3128
https_proxy=http://proxy.thematrix.com:3128
HTTPS_PROXY=http://proxy.thematrix.com:3128
no_proxy=thematrix.com
NO_PROXY=thematrix.com
```

For Conda, everyone within thematrix was supposed to use:
```
channels:
  - http://conda.thematrix.com
  - defaults
```

This along with the environment variables worked fine for ages, but then a certain Mr. Neo obtained root access on one of the mainframes within thematrix and placed a configuration file `/etc/conda/condarc.d/proxies.yml` with the following content:
```
proxy_servers: #!final
  http: http://proxy.thematrix.com:3128
  https: http://proxy.thematrix.com:3128
```

And this broke every user. Because, for each conda operation involving the http/https protocol, proxies were ended up being used, even for the http://conda.thematrix.com url, which kept responding 503.

Mr. Anderson asked one of his minions to look into it and that guy simply pointed him to: https://github.com/conda/conda/blob/8d090d4d54686e8f0dd28fec608e46e30b34b7a3/conda/gateways/connection/session.py#L64-L66 ... which means conda always overrides the session's internal settings for proxy, if it is set via configuration file(s) and requests can't seem do anything about it. It's probably :thinking: you want to override my class, and also expect me to look at env vars? Nada!

For the time being, the minion wrote the following patch to satisfy Mr. Anderson (of course, he can't submit it upstream):
```patch
diff --git a/conda/gateways/connection/session.py b/conda/gateways/connection/session.py
index 5e04817..f9b20ac 100644
--- a/conda/gateways/connection/session.py
+++ b/conda/gateways/connection/session.py
@@ -3,6 +3,7 @@ from __future__ import absolute_import, division, print_function, unicode_litera
 
 from logging import getLogger
 from threading import local
+from collections import OrderedDict
 
 from . import (AuthBase, BaseAdapter, HTTPAdapter, Session, _basic_auth_str,
                extract_cookies_to_jar, get_auth_from_url, get_netrc_auth)
@@ -91,6 +92,18 @@ class CondaSession(Session):
         elif context.client_ssl_cert:
             self.cert = context.client_ssl_cert
 
+    def get(self, url, **kwargs):
+        try:
+            from urlparse import urlparse
+        except ImportError:
+            from urllib.parse import urlparse
+        url_parsed = urlparse(url)
+        if 'thematrix.com' in url_parsed.hostname:
+            kwargs['proxies'] = {}
+            self.proxies = {}
+        else:
+            kwargs['proxies'] = context.proxy_servers or {}
+        return Session.get(self, url, **kwargs)
+
 
 class CondaHttpAuth(AuthBase):
     # TODO: make this class thread-safe by adding some of the requests.auth.HTTPDigestAuth() code
-- 
2.7.4
```

**Comment by Nodd** [comment]
I have the same issue with conda 4.14.0. To solve the problem, it should be possible to configure a no_proxy value in condarc, to mirror the NO_PROXY environment variable:
```YAML
proxy_servers:
  http: http://proxy.thematrix.com:3128
  https: http://proxy.thematrix.com:3128
  no_proxy: conda.thematrix.com
```
