### ISSUE TITLE
Add option to "conda create" to override an environment

### ISSUE THREAD

**Issue by certik** [conda/conda#7819]
Currently if the environment already exists, `conda create` will fail with:
```
$ conda create -n tmp python

CondaValueError: prefix already exists: /home/certik/ext/miniconda3/envs/tmp
```
And so when used in scripts, one has to add the following workaround:
```bash
conda env remove -y -n tmp || true
conda create -y -n tmp python
```
It'd be easier if there was an option in `conda create` that would remove the environment if it exists, something like:
```
conda create --override-env -n tmp python
```

**Comment by kalefranz** [comment]
Try the beta in the conda-canary channel :)

**Comment by certik** [comment]
I just tried it, but it still gives the same error:
```
$ conda create -m -n co2 python

CondaValueError: prefix already exists: /home/ondrej/miniconda3/envs/co2
```
and I couldn't find an option that does it in `conda create -h`. Have I missed it?

**Comment by nsarode-joyn** [comment]
The `--force` flag is what you are looking for. It forces creation of environment and will remove previously existing environment of the same name.

**Comment by certik** [comment]
@nsarode-joyn thanks for the suggestion. Unfortunately it does not work for me:
```
$ conda create --force -n test1 python

CondaValueError: prefix already exists: /home/certik/ext/miniconda3/envs/test1
```
If it works for you, can you please post the exact commands that you did?

**Comment by nsarode-joyn** [comment]
You are correct. It is giving me the same error. However, looking back i realized that I often create environments from conda env files (and share them to teams to recreate my environment). Doing it that way doesn't give me any errors when I go for the --force option

**Quick rundown**

```
# Create a test environment (assuming it doesn't already exists, activate if it does)
conda create -n test -q -y python

# activate to export file
source activate test

# export 
conda env export > test.yml

# get out
source deactivate 

# force create using the config file
conda env create -q --file test.yml --force

```

**Complete output**

```
:~$ conda create -n test -q -y python
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/usr/miniconda2/envs/test

  added / updated specs: 
    - python


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h14c3975_1002   conda-forge
    ca-certificates: 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.11.29-py37_1000  conda-forge
    libffi:          3.2.1-hf484d3e_1005   conda-forge
    libgcc-ng:       7.3.0-hdf63c60_0      conda-forge
    libstdcxx-ng:    7.3.0-hdf63c60_0      conda-forge
    ncurses:         6.1-hf484d3e_1002     conda-forge
    openssl:         1.0.2p-h14c3975_1002  conda-forge
    pip:             18.1-py37_1000        conda-forge
    python:          3.7.1-hd21baee_1000   conda-forge
    readline:        7.0-hf8c457e_1001     conda-forge
    setuptools:      40.6.3-py37_0         conda-forge
    sqlite:          3.26.0-h67949de_1000  conda-forge
    tk:              8.6.9-h84994c4_1000   conda-forge
    wheel:           0.32.3-py37_0         conda-forge
    xz:              5.2.4-h14c3975_1001   conda-forge
    zlib:            1.2.11-h14c3975_1004  conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
:~$ source activate test
(test) :~$ conda env export > test.yml
(test):~$ source deactivate
:~$ conda env create -q --file test.yml --force
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

```

**Comment by kalefranz** [comment]
Are you using conda 4.6?

**Comment by nsarode-joyn** [comment]
I am on 4.5.12 still. Didn't realize that 4.6 was out till you asked !

**Comment by msarahan** [comment]
4.6 is in the conda-canary channel. We have some minor issues around activation that need to be fixed. The first release to go into defaults will probably be 4.6.1. given another spin on testing, it'll likely be out early next week. If you are willing and able, please test the package on conda-canary.

**Comment by nsarode-joyn** [comment]
Ok, had a spare ubuntu machine to test on. And --force flag worked just fine with conda 4.6 ! 

Steps:

```
conda config --add channels conda-canary
conda update conda

conda create -n test -q -y python
conda create -n test -q -y python --force

```

**Comment by zdog234** [comment]
Hello! I didn't see anything about `--force` in `--help`. Would adding `--force` be a good candidate for a low-hanging-fruit contribution, or has someone already added it? (You guys are really on top of these issues btw)

**Comment by niderhoff** [comment]
`conda env create --force` worked for me.

**Comment by gbrault** [comment]
--fore doesn't work on 4.7.12

**Comment by kalefranz** [comment]
This ticket represents a feature request to not exit with a hard error when using `conda create` and an environment already exists at the specified location. This feature request is resolved as of conda 4.6.0.

**Comment by manosnoam** [comment]
Fails also on 4.8.3:

conda info

```
     active environment : None
       user config file : /home/jenkins/.condarc
 populated config files : /home/jenkins/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /mnt/nmanos/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/nmanos/miniconda/pkgs
                          /home/jenkins/.conda/pkgs
       envs directories : /mnt/nmanos/miniconda/envs
                          /home/jenkins/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/3.10.0-957.21.2.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 1001390000:0
             netrc file : None
           offline mode : False
```


conda config --add channels conda-forge
conda install -y --update-deps -c conda-forge go-nocgo_linux-64
conda env remove -n conda-env
conda create -y -n conda-env go-nocgo_linux-64 --force

`CondaValueError: prefix already exists: /mnt/nmanos/miniconda/envs/conda-env`

**Comment by shiplu** [comment]
I rely on the exit code of `conda creat`

     conda env create -f env.yml  || conda env update -f env.yml

It checks if the environment already exists. If not it creates it. Otherwise updates the existing environment.
