### ISSUE TITLE
ERROR conda.core.link:_execute(502): An error occurred while installing package [...]

### ISSUE THREAD

**Issue by lstillwe** [conda/conda#7824]
After trying to update nodejs, I attempted to conda update --all and then started to get the error message: 
[...]
Preparing transaction: done
Verifying transaction: done
Executing transaction: | + /opt/anaconda3/bin/jupyter-nbextension disable nb_conda --py --sys-prefix
Disabling notebook extension nb_conda/main...
      - Validating: OK
Disabling tree extension nb_conda/tree...
      - Validating: OK
+ /opt/anaconda3/bin/jupyter-serverextension disable nb_conda --py --sys-prefix
Disabling: nb_conda
- Writing config: /opt/anaconda3/etc/jupyter

| + /opt/anaconda3/bin/jupyter-nbextension disable nbpresent --py --sys-prefix
Disabling notebook extension nbpresent/js/nbpresent.min...
      - Validating: OK
+ /opt/anaconda3/bin/jupyter-serverextension disable nbpresent --py --sys-prefix
Disabling: nbpresent
- Writing config: /opt/anaconda3/etc/jupyter

failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::nodejs-6.11.2-h3db8ef7_0'.
FileNotFoundError(2, 'No such file or directory')
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, 'No such file or directory')

Any clues why this might be happening? How can I find out what file or directory might be missing?

**Comment by kalefranz** [comment]
Execute the command again, adding a ‘-v’ flag. It should show you the full stack traces.

**Comment by lstillwe** [comment]
It says this is the missing file:

conda.CondaMultiError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/node_modules/npm/.github’

I noticed that /opt/anaconda3/lib/node_modules/npm is a link and it appears to be broken. What should this be pointing to?


On Oct 2, 2018, at 7:10 PM, Kale Franz <notifications@github.com<mailto:notifications@github.com>> wrote:

Execute the command again, adding a ‘-v’ flag. It should show you the full stack traces.

**Comment by kalefranz** [comment]
Can you please use the issue template so that we have the preliminary information we need to help you with your issue?
