### ISSUE TITLE
'conda info' with PowerShell

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7828]
@cgranade Already found a bug with the PowerShell wrapper.

```
<devenv> PS /Users/kfranz/continuum/conda> conda info
WARNING: 'conda info package_name' is deprecated.
          Use 'conda search package_name --info'.
```

I think this is related to the line

    $OtherArgs = $Args[1..($Args.Count - 1)];

in `Conda.psm1`.  I *think* when the invoking argument is `conda info`, the line ends up making `$OtherArgs` be `info info`.

**Comment by cgranade** [comment]
Ah, sorry about that, @kalefranz. I'll go on and take a look, then.
