### ISSUE TITLE
Windows: Activate env from path

### ISSUE THREAD

**Issue by dusans** [conda/conda#783]
I created an env with -p. But i can't activate it (using Windows 7 64bit)

```
c:\python\python27anaconda\Scripts>conda create -p c:\temp\tmp_env pywin32
...
#
# To activate this environment, use:
# > activate c:\temp\tmp_env
#

c:\python\python27anaconda\Scripts>activate c:\temp\tmp_env
No environment named "c:\temp\tmp_env" exists in c:\python\python27anaconda\envs

c:\python\python27anaconda\Scripts>conda --version
conda 3.5.5
```

**Comment by wulmer** [comment]
This should work now since https://github.com/conda/conda/pull/1727 has been merged. @dusans: wait for the next conda release (4.0.4) and try again.

**Comment by kalefranz** [comment]
Actually #1727 will be in conda 4.1, which is at least a week or two away yet.

However, you get the bleeding edge master builds by

    conda config --add channels https://conda.anaconda.org/conda/label/dev
