### ISSUE TITLE
Conda --install installs broken packages, default packages in root are also broken

### ISSUE THREAD

**Issue by Ymegithub** [conda/conda#7833]
I am running into a very strange problem, I think it might be a bug. When I use a fresh installation of  Anaconda and set the project interpreter to base/root (Which comes with numpy etc pre-installed), importing numpy, scipy or matplotlib gives me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File"C:\Users\s140041\Anaconda3\envs\testenv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File"C:\Users\s140041\Anaconda3\envs\testenv\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\s140041\Anaconda3\envs\testenv\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File"C:\Users\s140041\Anaconda3\envs\testenv\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File"C:\Users\s140041\Anaconda3\envs\testenv\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)

ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

I have already done troubleshooting: 

- I do not think the issue is path-related, since Anaconda is my only installation of python on this machine, and the problem persists after a fresh installation of windows. I have not added anaconda to Path right now, since I just use the Anaconda prompt for all my conda related commands.

- I do not think it is a problem with the environments, Problem exists on base/root environment of conda as well as on a new conda environment.

- Problem is not system-related, was able to reproduce it on 2 seperate systems with specified versions.

- Problem is not PyCharm related, running python.exe from the root folder also gives the same error.

- Uninstalling / reinstalling the packages through conda does not work.
- Conda does seem to look in the right library for the packages, checked this through print(sys.path) in python.exe, it returns the local library of anaconda where all it's default packages are installed.

Only when I uninstall/reinstall using the pip-command in anaconda prompt it works fine and the packages import without any trouble. 

### Steps to Reproduce
- Install Anaconda 3 - 5.3.0 64-bit on a Windows 10 machine
- Do not add to path
- Try to import for instance numpy v1.15.2, scipy 1.1.0, or matplotlib 3.0.0 on a base/root environment, it will give the specified import error. numpy will give it directly, matplotlib itself can import but it does not import completely. For instance when you try to import pylab (which comes with installing matplotlib), same import error will show: ImportError: DLL load failed: The specified module could not be found. 
- Try to create a new environment and try to install through "conda install numpy. ". Installation will be succesful, however it will generate the same import error as provided in the screenshot. 
- Uninstall, through pip or conda, and use for instance pip install numpy. Import will now work without any problems.  

## Expected Behavior
When I use the base/root environment python should be able to import pre-installed packages without any import-errors. 
When I create a new environment and install packages through "conda install packagename", and try to import through import packagename, while the project interpreter is set to the new environment, it should not give me any import-errors. 

All environment information provided below is on a test environment, with the following packages installed:

- numpy 

- scipy

- matplotlib

All give full / partial import-errors, very similar to the one specified in the screenshot. All contain: DLL load failed: The specified module could not be found.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : Test
    active env location : C:\Users\s140041\Anaconda3\envs\Test
            shell level : 2
       user config file : C:\Users\s140041\.condarc
 populated config files : C:\Users\s140041\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\s140041\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\s140041\Anaconda3\pkgs
                          C:\Users\s140041\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\s140041\Anaconda3\envs
                          C:\Users\s140041\AppData\Local\conda\conda\envs
                          C:\Users\s140041\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False   
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\s140041\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\s140041\Anaconda3\envs\Test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.8.24                py37_1    defaults
cycler                    0.10.0                   py37_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
intel-openmp              2019.0                      118    defaults
jpeg                      9b                   hb83a4c4_2    defaults
kiwisolver                1.0.1            py37h6538335_0    defaults
libpng                    1.6.34               h79bbb47_0    defaults
matplotlib                3.0.0            py37hd159220_0    defaults
mkl                       2019.0                      118    defaults
mkl_fft                   1.0.6            py37hdbbee80_0    defaults
mkl_random                1.0.1            py37h77b88f5_1    defaults
numpy                     1.15.2           py37ha559c80_0    defaults
numpy-base                1.15.2           py37h8128ebf_0    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
pip                       10.0.1                   py37_0    defaults
pyparsing                 2.2.1                    py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
python                    3.7.0                hea74fb7_0    defaults
python-dateutil           2.7.3                    py37_0    defaults
pytz                      2018.5                   py37_0    defaults
qt                        5.9.6            vc14h1e9a669_2    defaults
scipy                     1.1.0            py37h4f6bf74_1    defaults
setuptools                40.4.3                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.25.2               hfa6e2cd_0    defaults
tornado                   5.1.1            py37hfa6e2cd_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.0                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
```
</p></details>

**Comment by dolson14** [comment]
I can verify this issue has been present for quite some time now. _However_, I am able to do the following:
`$ conda create -n testenv
$ activate testenv
(testenv) $ conda install python
(testenv) $ conda install numpy
(testenv) $ python -c "import numpy"`
At this point, numpy loads normally for me in this environment.

Other info that may be pertinent:

In linux, the multiarray library (which is breaking for both of us) is in site-packages/numpy/core/multiarray.cpython-37m-x86_64-linux-gnu.so, and I am able to import this library directly by running import multilib from that directory.

In Windows 10, the multiarray library is in site-packages/numpy/core/multiarray.cp37-win_amd64.pyd, and I am **NOT** able to import this library directly.

It looks like we are both using a local user installation. It might be worth trying to reproduce the error from a system-wide installation of anaconda and see what happens.

**Comment by mingwandroid** [comment]
You need to use procmon to track down the incorrect (probably mkl) DLL
that's getting loaded, probably from C:\Windows\System32.

**Comment by dolson14** [comment]
> You need to use procmon to track down the incorrect (probably mkl) DLL
that's getting loaded, probably from C:\Windows\System32.

I'm really not sure how to use procmon--an initial look didn't seem helpful at all. But, I can say that I have verified that the **only** mkl libraries on my system are in the anaconda directory. Perhaps it's trying to look for them elsewhere, but that doesn't explain why I can get it to work by creating a new environment.

I just tried cloning the base environment, and that alone makes the issue go away within the new environment. Something about the base environment installed in anaconda is broken, and it's not clear exactly what that would be.

**Comment by dolson14** [comment]
Found something:
https://gist.github.com/peterjc123/6b804651288e76db7b5fabe5348e1f03

Based on this, I added %PYTHONROOT%\Library\bin and %PYTHONROOT%\bin to my %PATH%, and now it's able to load numpy normally. I suspect the environments worked for me because activating a new environment automatically handled the path definitions, while the base environment didn't have that particular benefit.

Suggested workaround:
```
$ set "PYTHONROOT=C:\Users\<username>\AppData\Local\Continuum\anaconda3"
$ set "PATH=%PATH%;%PYTHONROOT%;%PYTHONROOT%\Scripts;%PYTHONROOT%\Library\bin;%PYTHONROOT%\bin"
$ python -c "import numpy"
```

Obviously the username depends on your system, and the root path in general depends on how Anaconda is installed. I'm doing this from a terminal (I use cmder, but I've also tried it successfully on plain old cmd), and when I open a Jupyter notebook from the terminal it maintains the path without issue. Others may want to set these directories in the system path within Windows itself to get it to work.

Ymegithub, can you verify if this works for you?

**Comment by mingwandroid** [comment]
Are you activating your base env? Not doing so is unsupported.

**Comment by dolson14** [comment]
mingwandroid, I really don't understand what you mean--I have never had to do anything with the base environment before.

http://docs.anaconda.com/anaconda/install/windows/

There's nothing here that suggests you should have to do anything other than run the gui installer. Running the installer results in exactly the behavior we've described here. Unless you're suggesting that using Anaconda in a command line environment other than the one found by running "Anaconda Prompt" is unsupported... I don't think that's what you're trying to suggest.

Before the most recent version, Anaconda has always "just worked". This version didn't. So either it's a bug, or it was intentionally changed and not documented well, leading at least two of us to find this specific problem.

**Comment by mingwandroid** [comment]
You appear to be launching PyCharm here? Did you launch it from an activated conda environment? You need to, otherwise `PATH` is incorrect.

**Comment by mingwandroid** [comment]
AFAIK, PyCharm doesn't activate conda envs.

**Comment by Ymegithub** [comment]
Dear @mingwandroid , forgive me for I am rather new to Conda and programming in general. 

Problem persists when I first activate base/root env in anaconda prompt, and then try to import numpy from the base/root python.exe (No Pycharm). 

Problem also persists when I first create a new test environment, use
`activate testenv`
 `conda install numpy`
in Anaconda prompt, and then try to import numpy from the environment's python.exe location. Same story. 

That is why I  assumed problem is not Pycharm related.  I type all conda related commands in Anaconda prompt, because during installation I did not click "add to path" during installation. This was a conscious choice since I was taught that adding something to path simply means that it will be easily found by cmd, and I am fine with using Anaconda prompt for my conda related commands. 
Source: https://stackoverflow.com/questions/52664293/why-or-why-not-add-anaconda-to-path 

I agree with @dolson14, and still think there is some kind of bug, or a fault in documentation. All documentation/guides mention nothing about having to activate an environment before being able to use it as "python interpreter".

Of course you have to activate the specified environment first before you have to install new packages to it, when using the anaconda prompt.  This is logical. How else would conda know for which env you want to install packages? But it is mentioned nowhere that environments have to be activated before _using_ them.  All guides simply state: Setup Pycharm such that it points to the right python.exe (In the folder of the env you want to use), and that's that. Even so, as I mentioned above, problem persists when trying to import while using python.exe in root/testenv folder so I do not think it is a problem with Pycharm.

**Comment by mingwandroid** [comment]
To run any software from `The Anaconda Distribution` you must either activate that env or add the values to `PATH` (i.e. let the installer do this) - THIS IS NOT RECOMMENDED.

Activation can involve running 'arbitrary' scripts that can do whatever that package demands such as setting env vars. If people try to use things outside of this then expect failures.

We try to minimise the use of activation scripts though so there are *less* problems for non-activators but you always need `PATH` set properly, somehow (I recommend the Anaconda Prompt as the launching point for anything that will run our Python, including PyCharm).

**Comment by Ymegithub** [comment]
Allright but how can it be then that the problem persists, even when I run the python.exe in the folder of the environment, and the problem persists? That shouldn't happen right?

 What would be the right way to use conda environments then for instance with pycharm? As far as I understand, you simple open Pycharm, point the pycharm interpreter to the python.exe in the environment and that's that.

Also, when you do this, Pycharm shows all the packages installed in the environment you specify, and it also works for interpreting regular python code. So I assumed this was not the problem, since only the import-error persists, and no guides mention the thing you mention. What you are saying is I would always need to add to the path every conda environment I use? This is mentioned nowhere in sources below: 

https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html 
https://medium.com/@GalarnykMichael/setting-up-pycharm-with-anaconda-plus-installing-packages-windows-mac-db2b158bd8c  
https://medium.com/infinity-aka-aseem/how-to-setup-pycharm-with-an-anaconda-virtual-environment-already-created-fb927bacbe61

**Comment by mingwandroid** [comment]
> Allright but how can it be then that the problem persists, even when I run the python.exe in the folder of the environment, and the problem persists? That shouldn't happen right?

Because `conda activate` adds multiple entries to `PATH` and double clicking on an `.exe` in a folder adds nothing to `PATH`?

> Also, when you do this, Pycharm shows all the packages installed in the environment you specify, and it also works for interpreting regular python code

That some software is able to *list* some packages does not mean that those packages will run properly when executed in an unsupported fashion.

We are not responsible for 3rd party documentation.

**Comment by Ymegithub** [comment]
> Because conda activate adds multiple entries to PATH and double clicking on an .exe in a folder adds nothing to PATH?

Allright sir, I must have done something wrong then. Since all guides mention nothing about this and it was such a strange problem, which no-one else on google seemed to experience, I thought I stumbled upon a bug. Please forgive me for my ignorance since I am rather new to all this, and be so kind to help me learn from my mistake.... If I get what you are saying: 

- What I did wrong is trying to use conda environments by only activating them in Anaconda prompt and then trying to use them in for instance python.exe in the folder, or set the new env as project interpreter in Pycharm. This does not make sense because activating an environment only "adds to path" temporarily, untill it is deactivated again, and only in that prompt window?

- What I can do to make sure this never happens again: Either re-install with option "Add to path", So  Pycharm and python.exe can automatically find the packages I install in conda environments **OR** do not add to path during installation, and first activate the env I want to use in Anaconda prompt, and after that boot python.exe or pycharm FROM THAT PROMPT.

> That some software is able to list some packages does not mean that those packages will run properly when executed in an unsupported fashion.

I get that. I am sorry for bothering you with this. Maybe, in the future, you could mention the consequences of adding/not adding to path more clearly on the website (http://docs.anaconda.com/anaconda/install/windows/), for new people like me. I think a lot of new people are "scared" by the warning of not adding something to path, but when they try to integrate your software with an easy IDE like pycharm they will get weird errors. For new users, it might be and easier to "add to path", then to use the anaconda prompt, activate the environment and boot their IDE of choice from there. I think if users would understand what it means to add to path better, bug reports like this (which potentially cost you, developers, a lot of time), could be prevented. Thank you for your time.

**Comment by mingwandroid** [comment]
> What I did wrong is trying to use conda environments by only activating them in Anaconda prompt and then trying to use them in for instance python.exe in the folder, or set the new env as project interpreter in Pycharm. This does not make sense because activating an environment only "adds to path" temporarily, untill it is deactivated again, and only in that prompt window?

You must launch subsequent software from the *activated* Anaconda Prompt for it to behave correctly, yes. Clicking on `python.exe` from Windows Explorer is not sufficient. You can also launch our software from `Anaconda Navigator` and it will take care of activation for you.

> I get that. I am sorry for bothering you with this. Maybe, in the future, you could mention the consequences of adding/not adding to path more clearly on the website (http://docs.anaconda.com/anaconda/install/windows/), for new people like me. I think a lot of new people are "scared" by the warning of not adding something to path, but when they try to integrate your software with an easy-to-use IDE like pycharm they will get weird errors. For new users, it might be and easier to "add to path", then to use the anaconda prompt, activate the environment and boot their IDE of choice from there. I think if users would understand what it means to add to path better, bug reports like this (which potentially costs you, developers, a lot of time), could be prevented. Thank you for your time.

I agree with you here, our docs should make these details clear, I actually had a look for docs on this and there's not much, mostly me answering people on github. We (or you - I'd be happy to assist if you want to learn) could create stub-packages for things like pycharm so that working shortcuts are provided; that would be really nice. The problem would be knowing where pycharm is installed but I guess some registry rummaging would answer that?

**Comment by mingwandroid** [comment]
Note, this won't fix PyCharm's handling of `conda` environments.

**Comment by Ymegithub** [comment]
> You must launch subsequent software from the activated Anaconda Prompt for it to behave correctly, yes. Clicking on python.exe from Windows Explorer is not sufficient. You can also launch our software from Anaconda Navigator and it will take care of activation for you.

Crystal clear. The other option, adding Anaconda to path removes this need (right?) but it might not be a good idea (especially for new people), since messing with path can cause off issues, in the worst case a malfunctioning windows installation. Is that why you disencourage people to add to path in the installation? (BTW: Re-installed Anaconda with option "Add to path" and am now able to setup new environments and work with them in Pycharm flawlessly - importing included)

> I agree with you here, our docs should make these details clear, I actually had a look for docs on this and there's not much, mostly me answering people on github. 

That would be nice very nice indeed! It would help a lot if the documentation would improve. Especially since most Anaconda/Pycharm users are actually data scientists and not hardcore programmers. 

> We (or you - I'd be happy to assist if you want to learn) could create stub-packages for things like pycharm so that working shortcuts are provided; that would be really nice. 

I would love to learn... I must say however that I am not very experienced with stub-packages, I have heard of them and I know it is some kind of way to let programs access a python module, but that is as far as it goes. 

>The problem would be knowing where pycharm is installed but I guess some registry rummaging would answer that? 
Let's assume it will =)

**Comment by mingwandroid** [comment]
> I would love to learn... I must say however that I am not very experienced with stub-packages, I have heard of them and I know it is some kind of way to let programs access a python module, but that is as far as it goes.

I'm not talking about a python stub package here, I mean a conda package that only serves to launch some other program in a correctly setup environment.

`Anaconda Prompt` itself is provided by this package:
https://github.com/AnacondaRecipes/aggregate/tree/master/console_shortcut-feedstock/recipe

.. there's not reason you couldn't change this a bit and have it work for PyCharm.

**Comment by Ymegithub** [comment]
I will try this when i get more familiar with conda in general. Thx for everything!

**Comment by NeoFantom** [comment]
I'm a PyCharm user and installed miniconda. Same problem occurred. So does this mean the only way to make PyCharm work well is to start it from Anaconda Prompt? Is there any way to make PyCharm importing packages normally when just launching it directly?

BTW, I saw in newest version of PyCharm manual, that just setting the python interpreter will work for conda environment, nothing else needed. And I saw someone saying that all `activate` do is just writing a temporary environment variable which means with or without activating, as long as a program can find this environment, it'll be able to use it normally. But I tried setting it in PyCharm, it didn't work for me. Thus I'm confused.

**Comment by mjmaldonado** [comment]
@Ymegithub, thank you for raising this issue and progressing the discussion along; it helped me greatly.  @mingwandroid, thank you for the guidance.  I wasn't able to successfully walk through the demo,  [**Getting Started Tutorial for Python in Visual Studio Code**](https://code.visualstudio.com/docs/python/python-tutorial), until I launched VS Code from Anaconda Prompt.  👊 to you both.
