### ISSUE TITLE
Conda “Verifying transaction” and “Executing transaction” extremely slow

### ISSUE THREAD

**Issue by JustinToribio** [conda/conda#7837]
I opened a new issue because [#7239](https://github.com/conda/conda/issues/7239) seems to focus mainly on the solver and "Solving environment", whereas my issue appears to be specifically with "Verifying transaction" and "Executing transaction".  **IT TAKES 11 MINUTES**  for me to create a new environment where all I install is `jupyter`:

```
time -p conda create -n my_env jupyter  
```  

Here is the output and time:  

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: - DEBUG menuinst_win32:__init__(196): Menu: name: 'Ana  nda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\Joyce\Anaconda3_May_18_2018\envs\my_env', env_name: 'my_env', mode: 'u  r', used_mode: 'user'DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\Joyce\Anaconda3_Ma  18_2018\python.exe, args are ['C:\\Users\\Joyce\\Anaconda3_May_18_2018\\cwp.py', 'C:\\Users\\Joyce\\Anaconda3_May_1  2018\\envs\\my_env', 'C:\\Users\\Joyce\\Anaconda3_May_18_2018\\envs\\my_env\\python.exe', 'C:\\Users\\Joyce\\Anacon  3_May_18_2018\\envs\\my_env\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']
done  

real 661.31
user 0.00
sys 0.01  
```  

As mentioned, the vast majority of that time is taken up by "Verifying transaction" and "Executing transaction".  `Jupyter` and all the associated packages that get installed are already downloaded, extracted and cached on my machine, so no time is spent there.  

I timed it and here's the breakdown:  

Solving environment: 0 min 20 sec  
Preparing transaction: 0 min 10 sec  
**Verifying transaction: 8 min 25 sec!!**  
**Executing transaction: 2 min 18 sec**  

And it has been like this since I started using `conda`.   Here's my `conda info`:  

```
active environment : None
       user config file : C:\Users\Joyce\.condarc
 populated config files : C:\Users\Joyce\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\Joyce\Anaconda3_May_18_2018  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Joyce\Anaconda3_May_18_2018\pkgs
                          C:\Users\Joyce\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Joyce\Anaconda3_May_18_2018\envs
                          C:\Users\Joyce\AppData\Local\conda\conda\envs
                          C:\Users\Joyce\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/7
Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False  
```  

Please help me figure out and solve why my `conda` seems exceptionally slow.  I'm assuming Verifying and Executing transaction shouldn't be taking THAT long.  Please let me know if you need any other info from me.

_Originally posted by @JustinToribio in https://github.com/conda/conda/issues/7239#issuecomment-427617637_

**Comment by blaylockbk** [comment]
Maybe a similar issue: Installing with `conda install` from the conda-forge channel spins on "Solving environments" for hours before I give up.

**Comment by MrEldritch** [comment]
Just chiming in, here - I'm experiencing the same issue, although I had the misfortune to encounter it when trying to install `anaconda`. My machine was stuck on "Verifying Transaction" and "Executing Transaction" for literal hours.

**Comment by 14BewleyM** [comment]
Wanted to also report that I'm having a very similar issue. `conda install`ing packages (especially into environments) seems to take much longer than it used to. ~15 minutes recently to add geopandas to a new environment. In this case, it hung at "Verifying transaction" for maybe 10 minutes, but it doesn't seem to always hang there.

(I also don't have much in the way of useful information, and would be happy to provide some if needed).

**Comment by hemangjoshi37a** [comment]
Have anyone solved the issue yet??

**Comment by msarahan** [comment]
https://github.com/conda/conda/issues/7239#issuecomment-445355045

**Comment by Guptajakala** [comment]
@msarahan 
Why close it? Not resolved.

**Comment by msarahan** [comment]
Are you on a network drive?  Conda's operations involve a ton of very small file operations, which can crawl on network drives.  Virus scanners can also really kill performance, as they try to scan each file as conda is putting it in place.

**Comment by 14BewleyM** [comment]
FWIW I haven't had this issue recently.

**Comment by Guptajakala** [comment]
@msarahan 
I met this issue on a server. Is there any way to get rid of it? When I use pip install I never have this kind of issue.
