### ISSUE TITLE
  base environment : /home/alfredo/miniconda3  (read only) (Problem??)

### ISSUE THREAD

**Issue by alfredo-huerta** [conda/conda#7838]
Hello, this is my terminal

alfredo@alfredo-ThinkPad-E455:~$ conda install statsmodels scipy scikit-learn
Solving environment: done

## Package Plan ##

  environment location: /home/alfredo/miniconda3

  added / updated specs: 
    - scikit-learn
    - scipy
    - statsmodels

The following NEW packages will be INSTALLED:

    blas:            1.0-mkl              
    intel-openmp:    2019.0-118           
    libgfortran-ng:  7.3.0-hdf63c60_0     
    mkl:             2019.0-118           
    mkl_fft:         1.0.6-py37h7dd41cf_0 
    mkl_random:      1.0.1-py37h4414c95_1 
    numpy:           1.15.2-py37h1d66e8a_1
    numpy-base:      1.15.2-py37h81de0dd_1
    pandas:          0.23.4-py37h04863e7_0
    patsy:           0.5.0-py37_0         
    python-dateutil: 2.7.3-py37_0         
    pytz:            2018.5-py37_0        
    scikit-learn:    0.20.0-py37h4989274_1
    scipy:           1.1.0-py37hfa4b5c9_1 
    statsmodels:     0.9.0-py37h035aef0_0 

Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
        unlink_link_transaction.execute()
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 223, in execute
        self.verify()
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
        return f(*args, **kwds)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 200, in verify
        self.prepare()
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 192, in prepare
        stp.remove_specs, stp.update_specs)
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 282, in _prepare
        mkdir_p(transaction_context['temp_dir'])
      File "/home/alfredo/miniconda3/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
        makedirs(path)
      File "/home/alfredo/miniconda3/lib/python3.7/os.py", line 221, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/alfredo/miniconda3/.condatmp'

`$ /home/alfredo/miniconda3/bin/conda install statsmodels scipy scikit-learn`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/alfredo/miniconda3
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/alfredo/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
                          /usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : None
       user config file : /home/alfredo/.condarc
 populated config files : /home/alfredo/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /home/alfredo/miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/alfredo/miniconda3/pkgs
                          /home/alfredo/.conda/pkgs
       envs directories : /home/alfredo/.conda/envs
                          /home/alfredo/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
Upload successful.

Hello, I copied pasted my terminal, I believe the problem is located on this line (according to google)
  **base environment : /home/alfredo/miniconda3  (read only)**

How could I fix that? 
Thanks

**Comment by mingwandroid** [comment]
Did you install with sudo then try to update without sudo?

You shouldn't use sudo.

You may be able to recover this via: `chown -R +w /home/alfredo/miniconda3` though.

**Comment by nehaljwani** [comment]
Conda should now catch PermissionError along with OSError and IOError , so that the 'Submit Report thingy` is not thrown.

**Comment by nd2linh** [comment]
I tried an easy fix and it worked with a very similar issue that you are having.
- Go to miniconda3 root folder (mine is in C:\ProgramData\Anaconda3)
- Right click, choose Properties, and uncheck the read-only box
- Go to "Sharing" Tab, click "Share...", choose "alfredo". Make sure the user has both Read and Write access.
Once you're done, go back to Anaconda, type "conda info", take a look to make sure your environment is "writable"
Hope this will help!

**Comment by santiagodemierre** [comment]
Nailed it! I probably ran sudo conda. Thanks

**Comment by sreddy-ops** [comment]
conda info
base environment : /opt/anaconda2 (Read only)
How to make it writable?
