### ISSUE TITLE
Cannot activate environment in Windows Git Bash

### ISSUE THREAD

**Issue by yissachar** [conda/conda#7841]
## Current Behavior
Cannot activate Conda environment on Windows from within Git Bash

### Steps to Reproduce
```
$ source activate myenv
sh.exe": cygpath: command not found
sh.exe": /etc/profile.d/conda.sh: No such file or directory
```

## Expected Behavior
Should be able to activate environment regardless of terminal.

## Environment Information

```
Windows 10
Conda 4.5.11
```

**Comment by mingwandroid** [comment]
Please use MSYS2 instead.

**Comment by yissachar** [comment]
Thanks, that worked!
