### ISSUE TITLE
conda program not working with ksh

### ISSUE THREAD

**Issue by jpays** [conda/conda#7843]
Hello, 

With the current version of conda, we have issues when using ksh shell, due to the use of the "local" builtin, which seems to be available in bash but not in ksh :

```
$ echo $SHELL
/bin/ksh
$ . /soft/conda/3/etc/profile.d/conda.sh
$ conda activate base
-ksh[84]: local: not found [No such file or directory]
usage: conda [-h] [-V] command ...
```

In bash the same installation works perfectly as expected.
Is ksh actually not supported or should this be considered as a bug ?
Thank you.

Here is the details of my environment :

## Environment Information
<details>
<summary><code>conda info</code></summary>

```
$ conda info

     active environment : base
    active env location : /soft/conda/3
            shell level : 1
       user config file : /projets/lab/home/labusrm21/.condarc
 populated config files : /soft/conda/3/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /soft/conda/3  (read only)
           channel URLs : https://repo-conda.python.intranet.cnp.fr:20443/pkgs/main/linux-64
                          https://repo-conda.python.intranet.cnp.fr:20443/pkgs/main/noarch
                          https://repo-conda.python.intranet.cnp.fr:20443/conda-forge/linux-64
                          https://repo-conda.python.intranet.cnp.fr:20443/conda-forge/noarch
                          https://repo-cnp.python.intranet.cnp.fr:20443/pkgs/public/linux-64
                          https://repo-cnp.python.intranet.cnp.fr:20443/pkgs/public/noarch
          package cache : /soft/conda/3/pkgs
                          /projets/lab/home/labusrm21/.conda/pkgs
       envs directories : /projets/lab/home/labusrm21/.conda/envs
                          /soft/conda/3/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-693.21.1.el7.x86_64 rhel/7.4 glibc/2.17
                UID:GID : 64002:64000
             netrc file : None
           offline mode : False

```

</details>

<details>
<summary><code>conda config --show-sources</code></summary>

```
$ conda config --show-sources
==> /soft/conda/3/.condarc <==
ssl_verify: /etc/ssl/certs/ca-bundle.crt
channel_alias: https://repo-cnp.python.intranet.cnp.fr:20443/pkgs/
channels:
  - https://repo-conda.python.intranet.cnp.fr:20443/pkgs/main
  - https://repo-conda.python.intranet.cnp.fr:20443/conda-forge
  - https://repo-cnp.python.intranet.cnp.fr:20443/pkgs/public
show_channel_urls: True

```

</details>

<details>
<summary><code>conda list --show-channel-urls</code></summary>

```
$ conda list --show-channel-urls
# packages in environment at /soft/conda/3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.8.24                py37_1    defaults
cffi                      1.11.5           py37he75722e_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.3.1            py37hc365091_0    defaults
idna                      2.7                      py37_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  hf484d3e_0    defaults
openssl                   1.0.2p               h14c3975_0    defaults
pip                       10.0.1                   py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.18                     py37_1    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.0                hc3d631a_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.19.1                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                40.2.0                   py37_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.24.0               h84994c4_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.23                     py37_0    defaults
wheel                     0.31.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults

```

</details>

**Comment by Tagar** [comment]
See https://github.com/conda/conda/issues/6820 for ideas how to make source activate shell-agnostic

**Comment by Tagar** [comment]
Also see https://github.com/ContinuumIO/anaconda-issues/issues/10027 - it seems possible to make source activate ksh-compatible by changing local to a similar typeset command.

**Comment by jonathaneichelberger** [comment]
Adding KSH support seems to be pretty simple. In `etc/profile.d/conda.sh`, change all occurrences of `local` to `typeset`, and change `__conda_hashr()` to:
```sh
__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    elif [ -n "${KSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi  
}
```

**Comment by kajukenbo** [comment]
@jonathaneichelberger 

Thank you for this.
It is pretty sad that the progenitor of many of the fancy shell features people take for granted these days STILL doesn't work properly 2 years later.

I had to take your suggestion a step further:

`cd ~/miniconda3/etc/profile.d/`
`vi conda.sh  ## your steps`
`cp -v conda.sh ~/miniconda3/lib/python3.7/site-packages/conda/shell/etc/profile.d`
`cp -v conda.sh ~/miniconda3/pkgs/conda-4.7.12-py37_0/etc/profile.d`
`cp -v conda.sh ~/miniconda3/pkgs/conda-4.7.12-py37_0/lib/python3.7/site-packages/conda/shell/etc/profile.d`
`cp -v conda.sh ~/conda,sh.fixed  ## in case an update breaks something`

I then copied the "init" code from a ~/.bashrc to the end of my ~/.mkshrc

It appears to work in both ksh93 and mksh, for now via conda 4.7.12

**Comment by kalefranz** [comment]
I guess I didn’t realize that ksh (KornShell) was POSIX compliant. So `eval "$(conda shell.sh hook)"` should work for ksh. We should also add a specialized `conda shell.ksh hook` and a `conda init ksh`.

**Comment by kalefranz** [comment]
Does anybody know if `typeset` has compatibility issues with the other POSIX shells?

**Comment by kajukenbo** [comment]
I know there was some problems with typeset & bash in the past, but I think that was due to misuse?
When I get some time I will see if I can do some testing.

https://stackoverflow.com/questions/11084675/equivalent-for-typeset-l-and-typeset-u-in-linux-bash

**Comment by nehaljwani** [comment]
I spent some time on this. One of the best explanations on the history of local/declare/typeset I found: https://unix.stackexchange.com/a/493743/24475 , which claims:

> bash and zsh added typeset aliased to local in 1989 and 1991 respectively.

Then, I went hunting for the source code and found this file (in the oldest commit available):
https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/declare.def?h=devel-base-dist&id=7117c2d221b2aed4ede8600f6a36b7c1454b4f55

It clearly has:
```
$BUILTIN declare
$FUNCTION declare_builtin

$BUILTIN typeset
$FUNCTION declare_builtin

$BUILTIN local
$FUNCTION local_builtin
```

And on code generation, the `local_builtin` function does this:
```C
/* Declare or change variable attributes. */
int
declare_builtin (list)
     register WORD_LIST *list;
{
  return (declare_internal (list, 0));
}

#line 114 "./declare.def"
int
local_builtin (list)
     register WORD_LIST *list;
{
  if (variable_context)
    return (declare_internal (list, 1));
  else
    {
      builtin_error (_("can only be used in a function"));
      return (EXECUTION_FAILURE);
    }
}
```

So it seems to me that all three are exactly same, with the only difference that `local` can be used only inside functions. IMO, it should be safe to replace local with typset for compatibility here.

**Comment by nehaljwani** [comment]
For zsh, `man zshbuiltins` has:

```
       declare
              Same as typeset.

       local [ {+|-}AHUahlprtux ] [ {+|-}EFLRZi [ n ] ] [ name[=value] ... ]
              Same as typeset, except that the options -g, and -f are not permitted.  In this case the -x option does not force the use of -g, i.e. exported variables will be local to functions.
```

**Comment by nehaljwani** [comment]
Another interesting read: https://stackoverflow.com/a/18600920/1005215

Looks like `local` and `typeset` both are not POSIX complaint :)

**Comment by nehaljwani** [comment]
I went hunting a bit further and found that `posixlocal2` is available at http://wooledge.org/~greybot/meta/posixlocal2 which points to http://stchaz.free.fr/locvar.sh (attaching [here](https://github.com/conda/conda/files/4679108/locvar.sh.txt) for convenience) 

Perhaps we could simply adopt that and make every POSIX compliant shell happy? 🤔

**Comment by brenthc** [comment]
Just ran into this. Some vars are being purposefully exported, at least one all-caps var and one lowercase var is set while not local or exported, and several `__XXXXX` functions are declared. I just took the locals out (along with the single line declarations) and it works fine. IMO there are more important things to worry about than if `$cmd` and `$t1` are stomped on and then unused any further. Rename them to something that better matches the other `__conda_cmd` and `__conda_t1` style names and just leave it at that is my suggestion.
