### ISSUE TITLE
Upload build to binstar organisation

### ISSUE THREAD

**Issue by rhattersley** [conda/conda#785]
The auto-upload to binstar after a build is very useful. To make the most of binstar organisations it would be helpful to have another conda option which allowed the specification of an organisation name. (equivalent to `binstar upload -u <org_name> ...`).

For example:

```
conda config --set binstar_upload yes
conda config --set binstar_org <org_name>
conda build ...
```

**Comment by ovz** [comment]
I'm running into similar issue as I script my development process. Would be good to come to a resolution. Ideally I would like to specify my upload settings right inside meta.yaml. At least in my use case the package will always be deployed to the same Organization and Channel. Separate scripts can take from there.

**Comment by dopplershift** [comment]
+1 -- would simplify my life now

**Comment by goanpeca** [comment]
This definitely makes more sense as ~~binstar~~ anaconda.org configuration option as conda itself has no notion of uploading into/to something.

Moving to the Anaconda Client repo
