### ISSUE TITLE
Tuning tools

### ISSUE THREAD

**Issue by abalter** [conda/conda#7851]
For some reason, conda is getting slower and slower. There are numerous issues cropping up on this.

Perhaps there needs to be one or more tools that can help "tune up" conda installs to make them more responsive. The other day I installed `krb5` into an environment and it took hours to complete. This was on a research cluster node with 16 cpus and 24G of RAM.

About 1/2 an hour ago I started a process to remove an environment on a similar compute node. It is still running.

I saved some timings the other day that I thought about posting, but I'm sure you are all pretty aware of the situation.

What the heck. This is on my laptop 16GB RAM, Core i7 8th gen. 50s to create a new environment and another 50s to "update" and realize there is nothing to update.

```
balter@spectre:~$ time conda create -n phyloseq -y
Solving environment: done

## Package Plan ##

  environment location: /home/balter/conda/envs/phyloseq


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate phyloseq
#
# To deactivate an active environment, use
#
#     $ conda deactivate


real    0m50.774s
user    0m32.453s
sys     0m3.969s
balter@spectre:~$ time conda activate phyloseq

real    0m0.503s
user    0m0.172s
sys     0m0.313s
```

**Comment by msarahan** [comment]
There's a lot of work going on to figure out these slow speeds. Adding in large channels like conda forge and bioconda definitely exacerbates it. It will take time, but we will get these times way down.

Please search for other posts like this. There are many. I'm on my phone, so I'll leave linking to someone else.

Tuning isn't really going to help.  There isn't much to tune.  It is much more a problem of reducing the size of problems fed to the solver and using better solvers. We may also be able to skip the solve for some simple tasks.

**Comment by abalter** [comment]
@msarahan -- thanks for the explanation. What can us end users do to help?

Your phone doesn't have conda ;)

**Comment by msarahan** [comment]
Lots of discussion at https://github.com/conda/conda/issues/7239

The best summary of things to do is at https://github.com/conda/conda/issues/7700

Any efforts towards improving benchmarking, profiling, or contributions towards the things that @mbargull mentions in #7700 would be time well spent.
