### ISSUE TITLE
A system for recording the history of conda installations towards robustness and reproducibility.

### ISSUE THREAD

**Issue by abalter** [conda/conda#7852]
Let's face it--we all break our conda installation from time to time. It happens.

I recently noticed that conda keeps a "history" file in `conda/conda-meta` and `conda/env/<env name>/conda-meta` for each environment that records each command that alters the conda installation ( `conda install`, `conda uninstall`, `conda update`, etc.). These can be useful in rebuilding an environment if y.ou don't already have an export. However, you need to process the file to look for packages that were installed and then uninstalled and other such potential issues (of course, you could simply re-run the entire history).

What if after each alteration command conda kept a versioned equivalent to a `conda env export`? That way, when you fubar your conda, you could do something like `conda revert -2` to remove the last two actions, or if necessary `conda rebuild -2` to rebuild the environment from the state information two actions ago.

I sure would love this.

Other methods to repair conda installations would also be welcome.

**Comment by quartox** [comment]
You can use `conda list --revisions` and `conda install --revision 1` to revert to a previous state. I would also like a more automated system for keeping track of environments to allow for it to re-solve an old set of specs. I have some thoughts but they won't be ready to use for a while.

**Comment by rgommers** [comment]
`conda install --revision` seems to be exactly what I need, but it's fragile:
```
$ conda install --revision 12
  
PackagesNotFoundError: The following packages are missing from the target environment:
  - conda-forge::markupsafe==1.1.1=py36h14c3975_0
  - conda-forge::entrypoints==0.3=py36_1000

$ conda install markupsafe=1.1.1
Collecting package metadata: done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
```

Files for the missing packages, e.g. `markupsafe==1.1.1=py36h14c3975_0`, can still be found (https://anaconda.org/conda-forge/markupsafe/files?channel=main&type=conda), but there's no good way to install them anymore and `conda` apparently isn't able to download anything that isn't already in cache.

if I'm missing anything here, please tell me!

**Comment by cartof** [comment]
Same problem.

When installing a previous revision a package is missing from it's original channel (ie conda-forge) but is present with the same compilation in the main channel.

Revision from:
2019-02-02 15:25:40  (rev 1)

```
$ conda install --revision 1

PackagesNotFoundError: The following packages are missing from the target environment:
  - conda-forge::libgfortran-ng==7.2.0=hdf63c60_3

$ conda search libgfortran-ng==7.2.0=hdf63c60_3
Loading channels: done
# Name                       Version           Build  Channel             
libgfortran-ng                 7.2.0      hdf63c60_3  pkgs/main 
```

Is it possible to modify the revision information to change the channel for that package?

**Comment by msarahan** [comment]
You can edit your conda-meta/history file, but otherwise I'd say no.  Conda should absolutely not change the meaning of which package you have by grabbing it from a different channel.  Even if build strings are the same, it does not guarantee that package content is the same.

**Comment by cartof** [comment]
Ok,

I thought they would be the same.

Thanks for the advise

**Comment by msarahan** [comment]
They are the same here, by chance, because conda-forge copied that package from defaults.  However, that is not universally true, and the filename/exact package spec is not sufficient to check.  A file hash is the only thing I'd trust for an exact match.  If you'd like to explore some kind of fallback check with hash verification, a PR would be welcome, but that's not something the conda team can work on right now.
