### ISSUE TITLE
python==2.7.15 anaconda==5.3.0 shows conflicts

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7853]
`conda create --verbose -p /opt/conda-parcel/Anaconda-5.3.0 python==2.7.15 anaconda==5.3.0`

shows there is conflict (doesn't show which one)

> Current conda install:
> 
>                platform : linux-64
>           conda version : 4.3.21
>        conda is private : False
>       conda-env version : 4.3.21
>     conda-build version : not installed
>          python version : 2.7.13.final.0
>        requests version : 2.14.2
>        root environment : /opt/cloudera/parcels/Anaconda  (read only)
>     default environment : /opt/cloudera/parcels/Anaconda
>        envs directories : /vol/devel1/ruslan/conda/envs
>                           /opt/cloudera/parcels/Anaconda/envs
>                           /opt/conda-parcel
>                           /home/rdautkha/.conda/envs
>           package cache : /vol/devel1/ruslan/conda/pkgs
>                           /opt/cloudera/parcels/Anaconda/pkgs
>            channel URLs : https://conda.anaconda.org/anaconda/linux-64
>                           https://conda.anaconda.org/anaconda/noarch
>                           https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>             config file : /home/rdautkha/.condarc
>              netrc file : None
>            offline mode : False
>              user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/3.10.0-862.6.3.el7.x86_64 Red Hat Enterprise Linux Server/7.5 glibc/2.17
>                 UID:GID : 2074918846:30
> 
> `$ /opt/cloudera/parcels/Anaconda/bin/conda create --verbose -p /opt/conda-parcel/Anaconda-5.3.0 python==2.7.15 anaconda==5.3.0`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
>         exit_code = args.func(args, p)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
>         install(args, parser, 'create')
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 251, in install
>         channel_priority_map=_channel_priority_map, is_update=isupdate)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/plan.py", line 489, in install_actions_list
>         for specs_by_prefix in required_solves]
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/plan.py", line 634, in get_actions_for_dists
>         pkgs = r.install(specs, installed, update_deps=update_deps)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 811, in install
>         pkgs = self.solve(specs, returnall=returnall)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 865, in solve
>         self.find_conflicts(specs)
>       File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 371, in find_conflicts
>         raise UnsatisfiableError(bad_deps)
>     UnsatisfiableError: The following specifications were found to be in conflict:
>       - anaconda ==5.3.0
>     Use "conda info <package>" to see the dependencies for each package.
> 
> 

Is anaconda 5.3 still buildable with Python 2.7?
How to narrow down what it conflicts with ?

**Comment by kalefranz** [comment]
conda 4.3.21 doesn't include `pkgs/main` in `default_channels` by default.  Just `conda update conda`.

**Comment by Tagar** [comment]
thank you @kalefranz ! 
yep, I don't have this issue in conda 4.3.30.
