### ISSUE TITLE
conda - short specificator for a channel

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7860]
Please consider adding short specificator for conda channels.

For example 

One way:
`conda install -n prod conda conda-build conda-env conda-verify conda-forge/conda-execute featuretools@featuretools
`
Another way:
`conda install -n prod conda conda-build conda-env conda-verify conda-execute@conda-forge featuretools/featuretools
`
In these examples conda-execute will be taken from conda-forge; and featuretools - from featuretools channel.

Then it will be possible to specify all packages and their different channels in one call to `conda`.

Conda environment resolution takes ("solving environment") takes time so it'll be beneficial to do everything in one pass.

Thank you.

**Comment by kalefranz** [comment]
Use

    conda install conda-forge::conda-execute

in conda 4.4 and up. Also note conda 4.6 (available in the `conda-canary` channel as 4.6.0b0) has a new `conda run` command.

**Comment by Tagar** [comment]
Good to know. Thanks you @kalefranz
