### ISSUE TITLE
WIP: ways that activate/anaconda prompt get messed up on Win

### ISSUE THREAD

**Issue by msarahan** [conda/conda#7881]
We see a lot of issues regarding activation failing.  The causes can be many.  I'm creating this issue to explore and document them, because I've just encountered one that's new to me.

What we're aware of:
1. virus scanners can prevent the installation of the activate.bat files completely.  If the files are not in ``<your-install-location>\Scripts\activate.bat``, this has likely occurred
2. The new conda scripts (4.4 and up) have a more complicated scheme that involved the registry for automatically running the appropriate scripts.  If the uninstallation process does not clean up the registry, or if the user manually just deletes the miniconda/anaconda installation folder without changing the registry, you can end up with "command not found errors."

What we propose as fixes:
1. you may need to uninstall, temporarily disable your virus scanner, and reinstall.  Make sure to re-enable your virus scanner.
2. The registry key lives in one of two places:

* For just-me installs: ``HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun``
* For all users installs: ``HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun``

Use the registry editor to make sure that these registry keys are not pointing to now-removed locations, and either remove them, or change them to point to any new installation you may have.

We at Anaconda will be working to come up with ways to repair these problems more gracefully.

**Comment by nehaljwani** [comment]
While exploring this, I found a small bug in the regex pattern matching at: https://github.com/conda/conda/blob/7a93664267488adc5052efef38614fab537da446/conda/core/initialize.py#L1157-L1166

The regex pattern assumes that I would not have quotes in my already existing value in the registry key. For example, if I have the current value set as...

```
echo "Hello NJW, How's your day today?"
```

... upon `conda init`, it will change the value to:
```
echo "\path\to\installation\condabin\conda_hook.bat"
```

Instead of:
```
echo "Hello NJW, How's your day today?" & "\path\to\installation\condabin\conda_hook.bat"
```

**Comment by nehaljwani** [comment]
An attempt at reset of reg keys on Uninstallation: https://github.com/conda/constructor/pull/235/files

**Comment by nehaljwani** [comment]
This issue also needs https://github.com/conda/conda/issues/7952 to be fixed and https://github.com/conda/conda/issues/7594 (nice to have)

**Comment by msarahan** [comment]
@nehaljwani has done work on several facets to improve this.  I doubt that we've seen the end of all of these problems, but we should close this and reopen more specific issues in the future.  Thanks @nehaljwani
