### ISSUE TITLE
Allow to give channel higher precedence when comparing packages

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#789]
Right now, the package comparison is essentially version, build number, build string, channel. We should allow to move the channel to a higher precedence (probably between version and build number). 

This may require refactoring how conda builds the index with channels. I'll have to think about it, but it could potentially be a bit of work.

**Comment by yannpaul** [comment]
@asmeurer I'd like to take this issue on, but I have some questions about your comments above. I think the crucial part of the current implementation is in resolve.py (https://github.com/conda/conda/blob/master/conda/resolve.py#L190 and subsequent lines). I have an idea of how to make this a bit more flexible, but looking at those lines, I don't see how channel plays into the ordering. Am I missing something about how things work, or is just the version, build number and if available build string are used in the comparison? 

Also, is there a bug on this line: https://github.com/conda/conda/blob/master/conda/resolve.py#L195 Why is `other.build` on this line and not the next (and why does that line have `self.build`)?

**Comment by asmeurer** [comment]
> Also, is there a bug on this line: https://github.com/conda/conda/blob/master/conda/resolve.py#L195 Why is other.build on this line and not the next (and why does that line have self.build)?

That was a workaround. See https://github.com/conda/conda/commit/3cc3ecc662914abe1d98b8d9c4caaa7c932a838e. It shouldn't be needed any more, because conda avoids installing packages with features if they aren't specified (so it will never install the mkl numpy if you don't ask it to).

**Comment by asmeurer** [comment]
My work at https://github.com/conda/conda/pull/1025 may be useful here.

**Comment by asmeurer** [comment]
The channels currently play into the ordering at the level where it fetches the index (the channels are fetched in reverse order and the dictionary is updated https://github.com/conda/conda/blob/271e07986ec95b89c2c2827086b9257ba164f4b7/conda/fetch.py#L263, so duplicate keys prefer the earlier channels).

**Comment by yannpaul** [comment]
> so duplicate keys prefer the earlier channels).

That clears up a major confusion of mine. 

So is the idea to have a per-package comparison method or to have one method for all the packages in the spec?

In other words (ignore the poor ui suggestions), per package:

    conda install --order-ver-build-channel python --order-channel-ver-build numpy

vs. one option for all packages: 

    conda install --order-ver-channel-build python numpy 

I'm not focused on the UI right now, I'm thinking more of how to implement this. I was picturing the second case, where you set the ordering for all packages in the spec list, and if you wanted to mix ordering methods, you would do that with multiple subsequent calls. Am I making sense?

**Comment by asmeurer** [comment]
I think doing it per-package would just make the code complicated (or at least confusing), and probably isn't a big enough use-case. It will be simpler if it is just done globally.

**Comment by kalefranz** [comment]
Conda 4.0 implemented channel priority.
