### ISSUE TITLE
Installing lightgbm for Conda Environment (Python 3.5) CondaError: Cannot link a source that does not exist.

### ISSUE THREAD

**Issue by MPullela29** [conda/conda#7891]
I am facing a similar issue as reported in (https://github.com/conda/conda/issues/7713)
I am trying to install lightgbm packages as instructed in this webpage (https://anaconda.org/conda-forge/lightgbm); seeing the error message below - 

I tried all the different solutions provided for the Issue 7713 
1) conda update -n base conda
2) conda update -c conda-forge conda
3) conda install -c conda-forge lightgbm 

I still see the error 

CondaError: Cannot link a source that does not exist.
4) conda clean --packages did not help either 

I have a Windows 10 64 Machine. 

Any Help will be appreciated. 

**### ERROR MESSAGE** 

c:\anaconda35\Scripts>c:\anaconda35\Scripts\conda install -c conda-forge lightgbm
Solving environment: done

## Package Plan ##

  environment location: c:\anaconda35

  added / updated specs:
    - lightgbm

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.11               |           py36_0         1.0 MB

The following NEW packages will be INSTALLED:

    backports.os:                       0.1.1-py36_1000         conda-forge
    importlib_metadata:                 0.6-py36_0              conda-forge
    jupyterlab_server:                  0.2.0-py_0              conda-forge
    krb5:                               1.14.6-vc14_0           conda-forge [vc14]
    lightgbm:                           2.2.1-py36h6538335_0    conda-forge
    pyhamcrest:                         1.9.0-py_2              conda-forge
    pyreadline:                         2.1-py36_1000           conda-forge
    pywin32-ctypes:                     0.2.0-py36_1000         conda-forge
    typed-ast:                          1.1.0-py36_0            conda-forge

The following packages will be REMOVED:

    anaconda:                           5.3.0-py37_0

The following packages will be UPDATED:

    _ipyw_jlab_nb_ext_conf:             0.1.0-py37_0                        --> 0.1.0-py36_0
    alabaster:                          0.7.11-py37_0                       --> 0.7.12-py_0               conda-forge
    anaconda-navigator:                 1.9.2-py37_0                        --> 1.9.2-py36_0
    anaconda-project:                   0.8.2-py37_0                        --> 0.8.2-py_1                conda-forge
    appdirs:                            1.4.3-py37h28b3542_0                --> 1.4.3-py_1                conda-forge
    asn1crypto:                         0.24.0-py37_0                       --> 0.24.0-py36_1003          conda-forge
    astropy:                            3.0.4-py37hfa6e2cd_0                --> 3.0.5-py36hfa6e2cd_1000   conda-forge
    atomicwrites:                       1.2.1-py37_0                        --> 1.2.1-py_0                conda-forge
    attrs:                              18.2.0-py37h28b3542_0               --> 18.2.0-py_0               conda-forge
    automat:                            0.7.0-py37_0                        --> 0.7.0-py_1                conda-forge
    babel:                              2.6.0-py37_0                        --> 2.6.0-py_1                conda-forge
    backcall:                           0.1.0-py37_0                        --> 0.1.0-py_0                conda-forge
    backports:                          1.0-py37_1                          --> 1.0-py_2                  conda-forge
    backports.shutil_get_terminal_size: 1.0.0-py37_2                        --> 1.0.0-py_3                conda-forge
    beautifulsoup4:                     4.6.3-py37_0                        --> 4.6.3-py36_1000           conda-forge
    bitarray:                           0.8.3-py37hfa6e2cd_0                --> 0.8.3-py36hfa6e2cd_0      conda-forge
    bkcharts:                           0.2-py37_0                          --> 0.2-py36_0                conda-forge
    blaze:                              0.11.3-py37_0                       --> 0.11.3-py36_0             conda-forge
    bleach:                             2.1.4-py37_0                        --> 3.0.2-py_0                conda-forge
    bokeh:                              0.13.0-py37_0                       --> 0.13.0-py36_1000          conda-forge
    boto:                               2.49.0-py37_0                       --> 2.49.0-py36_0
    bottleneck:                         1.2.1-py37h452e1ab_1                --> 1.2.1-py36h452e1ab_1001   conda-forge
    ca-certificates:                    2018.03.07-0                        --> 2018.10.15-ha4d7672_0     conda-forge
    certifi:                            2018.8.24-py37_1                    --> 2018.10.15-py36_1000      conda-forge
    cffi:                               1.11.5-py37h74b6da3_1               --> 1.11.5-py36hfa6e2cd_1001  conda-forge
    chardet:                            3.0.4-py37_1                        --> 3.0.4-py36_1003           conda-forge
    click:                              6.7-py37_0                          --> 7.0-py_0                  conda-forge
    cloudpickle:                        0.5.5-py37_0                        --> 0.6.1-py_0                conda-forge
    clyent:                             1.2.2-py37_1                        --> 1.2.2-py_1                conda-forge
    colorama:                           0.3.9-py37_0                        --> 0.4.0-py_0                conda-forge
    comtypes:                           1.1.7-py37_0                        --> 1.1.7-py36_1000           conda-forge
    conda:                              4.5.11-py37_0                       --> 4.5.11-py36_0
    conda-build:                        3.15.1-py37_0                       --> 3.15.1-py36_0             conda-forge
    constantly:                         15.1.0-py37h28b3542_0               --> 15.1.0-py_0               conda-forge
    contextlib2:                        0.5.5-py37_0                        --> 0.5.5-py_2                conda-forge
    cryptography:                       2.3.1-py37h74b6da3_0                --> 2.3.1-py36h74b6da3_1000   conda-forge
    cycler:                             0.10.0-py37_0                       --> 0.10.0-py_1               conda-forge
    cython:                             0.28.5-py37h6538335_0               --> 0.29-py36h6538335_1000    conda-forge
    cytoolz:                            0.9.0.1-py37hfa6e2cd_1              --> 0.9.0.1-py36hfa6e2cd_1001 conda-forge
    dask:                               0.19.1-py37_0                       --> 0.19.4-py_0               conda-forge
    dask-core:                          0.19.1-py37_0                       --> 0.19.4-py_0               conda-forge
    decorator:                          4.3.0-py37_0                        --> 4.3.0-py_0                conda-forge
    defusedxml:                         0.5.0-py37_1                        --> 0.5.0-py_1                conda-forge
    distributed:                        1.23.1-py37_0                       --> 1.23.3-py36_1000          conda-forge
    docutils:                           0.14-py37_0                         --> 0.14-py36_1001            conda-forge
    entrypoints:                        0.2.3-py37_2                        --> 0.2.3-py36_1002           conda-forge
    et_xmlfile:                         1.0.1-py37_0                        --> 1.0.1-py36_1000           conda-forge
    fastcache:                          1.0.2-py37hfa6e2cd_2                --> 1.0.2-py36hfa6e2cd_1001   conda-forge
    filelock:                           3.0.8-py37_0                        --> 3.0.9-py_0                conda-forge
    flask:                              1.0.2-py37_1                        --> 1.0.2-py_2                conda-forge
    flask-cors:                         3.0.6-py37_0                        --> 3.0.6-py_0                conda-forge
    gevent:                             1.3.6-py37hfa6e2cd_0                --> 1.3.6-py36hfa6e2cd_1000   conda-forge
    glob2:                              0.6-py37_0                          --> 0.6-py_0                  conda-forge
    h5py:                               2.8.0-py37h3bdd7fb_2                --> 2.8.0-py36h54c06b0_1003   conda-forge
    heapdict:                           1.0.0-py37_2                        --> 1.0.0-py36_1000           conda-forge
    html5lib:                           1.0.1-py37_0                        --> 1.0.1-py_0                conda-forge
    idna:                               2.7-py37_0                          --> 2.7-py36_1002             conda-forge
    imagesize:                          1.1.0-py37_0                        --> 1.1.0-py_0                conda-forge
    incremental:                        17.5.0-py37_0                       --> 17.5.0-py_0               conda-forge
    ipykernel:                          4.10.0-py37_0                       --> 5.1.0-pyh24bf2e0_0        conda-forge
    ipython:                            6.5.0-py37_0                        --> 7.0.1-py36h39e3cac_1000   conda-forge
    ipython_genutils:                   0.2.0-py37_0                        --> 0.2.0-py_1                conda-forge
    ipywidgets:                         7.4.1-py37_0                        --> 7.4.2-py_0                conda-forge
    isort:                              4.3.4-py37_0                        --> 4.3.4-py36_1000           conda-forge
    itsdangerous:                       0.24-py37_1                         --> 0.24-py_2                 conda-forge
    jdcal:                              1.4-py37_0                          --> 1.4-py_1                  conda-forge
    jedi:                               0.12.1-py37_0                       --> 0.13.1-py36_1000          conda-forge
    jinja2:                             2.10-py37_0                         --> 2.10-py_1                 conda-forge
    jpeg:                               9b-hb83a4c4_2                       --> 9b-vc14_2                 conda-forge [vc14]
    jsonschema:                         2.6.0-py37_0                        --> 2.6.0-py36_1002           conda-forge
    jupyter_client:                     5.2.3-py37_0                        --> 5.2.3-py_1                conda-forge
    jupyter_console:                    5.2.0-py37_1                        --> 6.0.0-py_0                conda-forge
    jupyter_core:                       4.4.0-py37_0                        --> 4.4.0-py_0                conda-forge
    jupyterlab:                         0.34.9-py37_0                       --> 0.35.2-py36_0             conda-forge
    jupyterlab_launcher:                0.13.1-py37_0                       --> 0.13.1-py_2               conda-forge
    keyring:                            13.2.1-py37_0                       --> 15.1.0-py36_0             conda-forge
    kiwisolver:                         1.0.1-py37h6538335_0                --> 1.0.1-py36he980bc4_1002   conda-forge
    lazy-object-proxy:                  1.3.1-py37hfa6e2cd_2                --> 1.3.1-py36hfa6e2cd_1000   conda-forge
    libpng:                             1.6.34-h79bbb47_0                   --> 1.6.34-vc14_0             conda-forge [vc14]
    libsodium:                          1.0.16-h9d3ae62_0                   --> 1.0.16-vc14_0             conda-forge [vc14]
    libxslt:                            1.1.32-hf6f1972_0                   --> 1.1.32-vc14_0             conda-forge [vc14]
    llvmlite:                           0.24.0-py37h6538335_0               --> 0.24.0-py36_1             conda-forge
    locket:                             0.2.0-py37_1                        --> 0.2.0-py_2                conda-forge
    markupsafe:                         1.0-py37hfa6e2cd_1                  --> 1.0-py36hfa6e2cd_1001     conda-forge
    mccabe:                             0.6.1-py37_1                        --> 0.6.1-py_1                conda-forge
    menuinst:                           1.4.14-py37hfa6e2cd_0               --> 1.4.14-py36_1000          conda-forge
    mistune:                            0.8.3-py37hfa6e2cd_1                --> 0.8.4-py36hfa6e2cd_1000   conda-forge
    mkl-service:                        1.1.2-py37hb217b18_5                --> 1.1.2-py36hb217b18_5
    mkl_fft:                            1.0.4-py37h1e22a9b_1                --> 1.0.6-py36_0              conda-forge
    more-itertools:                     4.3.0-py37_0                        --> 4.3.0-py36_1000           conda-forge
    msgpack-python:                     0.5.6-py37he980bc4_1                --> 0.5.6-py36he980bc4_1003   conda-forge
    multipledispatch:                   0.6.0-py37_0                        --> 0.6.0-py_0                conda-forge
    navigator-updater:                  0.2.1-py37_0                        --> 0.2.1-py36_0
    nbconvert:                          5.4.0-py37_1                        --> 5.4.0-1                   conda-forge
    nbformat:                           4.4.0-py37_0                        --> 4.4.0-py_1                conda-forge
    networkx:                           2.1-py37_0                          --> 2.2-py_1                  conda-forge
    nose:                               1.3.7-py37_2                        --> 1.3.7-py36_1002           conda-forge
    notebook:                           5.6.0-py37_0                        --> 5.7.0-py36_1000           conda-forge
    numba:                              0.39.0-py37h830ac7b_0               --> 0.39.0-py36h830ac7b_0
    numexpr:                            2.6.8-py37h9ef55f4_0                --> 2.6.8-py36h6538335_1000   conda-forge
    numpy:                              1.15.1-py37ha559c80_0               --> 1.15.2-py36ha559c80_0
    numpy-base:                         1.15.1-py37h8128ebf_0               --> 1.15.2-py36h8128ebf_0
    numpydoc:                           0.8.0-py37_0                        --> 0.8.0-py_1                conda-forge
    odo:                                0.5.1-py37_0                        --> 0.5.1-py_1                conda-forge
    olefile:                            0.46-py37_0                         --> 0.46-py_0                 conda-forge
    openpyxl:                           2.5.6-py37_0                        --> 2.5.9-py_0                conda-forge
    openssl:                            1.0.2p-hfa6e2cd_0       conda-forge --> 1.0.2p-hfa6e2cd_1001      conda-forge
    packaging:                          17.1-py37_0                         --> 18.0-py_0                 conda-forge
    pandas:                             0.23.4-py37h830ac7b_0               --> 0.23.4-py36h830ac7b_1000  conda-forge
    pandocfilters:                      1.4.2-py37_1                        --> 1.4.2-py_1                conda-forge
    parso:                              0.3.1-py37_0                        --> 0.3.1-py_0                conda-forge
    partd:                              0.3.8-py37_0                        --> 0.3.9-py_0                conda-forge
    path.py:                            11.1.0-py37_0                       --> 11.5.0-py_0               conda-forge
    pathlib2:                           2.3.2-py37_0                        --> 2.3.2-py36_1000           conda-forge
    patsy:                              0.5.0-py37_0                        --> 0.5.0-py_1                conda-forge
    pep8:                               1.7.1-py37_0                        --> 1.7.1-py_0                conda-forge
    pickleshare:                        0.7.4-py37_0                        --> 0.7.5-py36_1000           conda-forge
    pillow:                             5.2.0-py37h08bbbbd_0                --> 5.2.0-py36_0              conda-forge
    pip:                                10.0.1-py37_0                       --> 18.1-py36_1000            conda-forge
    pkginfo:                            1.4.2-py37_1                        --> 1.4.2-py_1                conda-forge
    pluggy:                             0.7.1-py37h28b3542_0                --> 0.8.0-py_0                conda-forge
    ply:                                3.11-py37_0                         --> 3.11-py_1                 conda-forge
    prometheus_client:                  0.3.1-py37h28b3542_0                --> 0.4.2-py_0                conda-forge
    prompt_toolkit:                     1.0.15-py37_0                       --> 2.0.6-py_0                conda-forge
    psutil:                             5.4.7-py37hfa6e2cd_0                --> 5.4.7-py36hfa6e2cd_1001   conda-forge
    py:                                 1.6.0-py37_0                        --> 1.7.0-py_0                conda-forge
    pyasn1:                             0.4.4-py37h28b3542_0                --> 0.4.4-py_1                conda-forge
    pycodestyle:                        2.4.0-py37_0                        --> 2.4.0-py_1                conda-forge
    pycosat:                            0.6.3-py37hfa6e2cd_0                --> 0.6.3-py36hfa6e2cd_1001   conda-forge
    pycparser:                          2.18-py37_1                         --> 2.19-py_0                 conda-forge
    pycrypto:                           2.6.1-py37hfa6e2cd_9                --> 2.6.1-py36hfa6e2cd_1002   conda-forge
    pycurl:                             7.43.0.2-py37h74b6da3_0             --> 7.43.0.2-py36h74b6da3_0
    pyflakes:                           2.0.0-py37_0                        --> 2.0.0-py_0                conda-forge
    pygments:                           2.2.0-py37_0                        --> 2.2.0-py_1                conda-forge
    pylint:                             2.1.1-py37_0                        --> 2.1.1-py36_0              conda-forge
    pyodbc:                             4.0.24-py37h6538335_0               --> 4.0.24-py36h6538335_1000  conda-forge
    pyopenssl:                          18.0.0-py37_0                       --> 18.0.0-py36_1000          conda-forge
    pyparsing:                          2.2.0-py37_1                        --> 2.2.2-py_0                conda-forge
    pysocks:                            1.6.8-py37_0                        --> 1.6.8-py36_1002           conda-forge
    pytables:                           3.4.4-py37he6f6034_0                --> 3.4.4-py36h7e76658_1      conda-forge
    pytest:                             3.8.0-py37_0                        --> 3.9.1-py36_1000           conda-forge
    pytest-arraydiff:                   0.2-py37h39e3cac_0                  --> 0.2-py_0                  conda-forge
    pytest-astropy:                     0.4.0-py37_0                        --> 0.4.0-py_0                conda-forge
    pytest-doctestplus:                 0.1.3-py37_0                        --> 0.1.3-py_0                conda-forge
    pytest-openfiles:                   0.3.0-py37_0                        --> 0.3.0-py_0                conda-forge
    pytest-remotedata:                  0.3.0-py37_0                        --> 0.3.0-py_0                conda-forge
    python-dateutil:                    2.7.3-py37_0                        --> 2.7.3-py_0                conda-forge
    pytz:                               2018.5-py37_0                       --> 2018.5-py_0               conda-forge
    pywavelets:                         1.0.0-py37h452e1ab_0                --> 1.0.1-py36h452e1ab_1000   conda-forge
    pywin32:                            223-py37hfa6e2cd_1                  --> 224-py36hfa6e2cd_1000     conda-forge
    pywinpty:                           0.5.4-py37_0                        --> 0.5.4-py36_1002           conda-forge
    pyyaml:                             3.13-py37hfa6e2cd_0                 --> 3.13-py36hfa6e2cd_1001    conda-forge
    pyzmq:                              17.1.2-py37hfa6e2cd_0               --> 17.1.2-py36hf576995_1001  conda-forge
    qtawesome:                          0.4.4-py37_0                        --> 0.5.1-pyh8a2030e_1        conda-forge
    qtconsole:                          4.4.1-py37_0                        --> 4.4.2-py_1                conda-forge
    qtpy:                               1.5.0-py37_0                        --> 1.5.2-pyh8a2030e_0        conda-forge
    requests:                           2.19.1-py37_0                       --> 2.20.0-py36_1000          conda-forge
    ruamel_yaml:                        0.15.46-py37hfa6e2cd_0              --> 0.15.71-py36hfa6e2cd_1000 conda-forge
    scikit-image:                       0.14.0-py37h6538335_1               --> 0.14.1-py36h6538335_1000  conda-forge
    scikit-learn:                       0.19.2-py37heebcf9a_0               --> 0.20.0-py36heebcf9a_1
    scipy:                              1.1.0-py37h4f6bf74_1                --> 1.1.0-py36h4f6bf74_1
    seaborn:                            0.9.0-py37_0                        --> 0.9.0-py_0                conda-forge
    send2trash:                         1.5.0-py37_0                        --> 1.5.0-py_0                conda-forge
    service_identity:                   17.0.0-py37h28b3542_0               --> 17.0.0-py_0               conda-forge
    setuptools:                         40.2.0-py37_0                       --> 40.4.3-py36_0             conda-forge
    singledispatch:                     3.4.0.3-py37_0                      --> 3.4.0.3-py36_1000         conda-forge
    six:                                1.11.0-py37_1                       --> 1.11.0-py36_1001          conda-forge
    snowballstemmer:                    1.2.1-py37_0                        --> 1.2.1-py_1                conda-forge
    sortedcollections:                  1.0.1-py37_0                        --> 1.0.1-py_1                conda-forge
    sortedcontainers:                   2.0.5-py37_0                        --> 2.0.5-py_0                conda-forge
    sphinx:                             1.7.9-py37_0                        --> 1.8.1-py36_1000           conda-forge
    sphinxcontrib:                      1.0-py37_1                          --> 1.0-py36_1
    sphinxcontrib-websupport:           1.1.0-py37_1                        --> 1.1.0-py_1                conda-forge
    spyder-kernels:                     0.2.6-py37_0                        --> 1.1.0-py_0                conda-forge
    sqlalchemy:                         1.2.11-py37hfa6e2cd_0               --> 1.2.12-py36hfa6e2cd_1000  conda-forge
    statsmodels:                        0.9.0-py37h452e1ab_0                --> 0.9.0-py36hfa6e2cd_1000   conda-forge
    sympy:                              1.1.1-py37_0                        --> 1.3-py36_1000             conda-forge
    tblib:                              1.3.2-py37_0                        --> 1.3.2-py_1                conda-forge
    terminado:                          0.8.1-py37_1                        --> 0.8.1-py36_1001           conda-forge
    testpath:                           0.3.1-py37_0                        --> 0.4.2-py36_1000           conda-forge
    tk:                                 8.6.8-hfa6e2cd_0                    --> 8.6.8-vc14_0              conda-forge [vc14]
    toolz:                              0.9.0-py37_0                        --> 0.9.0-py_1                conda-forge
    tornado:                            5.1-py37hfa6e2cd_0                  --> 5.1.1-py36hfa6e2cd_1000   conda-forge
    tqdm:                               4.26.0-py37h28b3542_0               --> 4.28.0-py_0               conda-forge
    traitlets:                          4.3.2-py37_0                        --> 4.3.2-py36_1000           conda-forge
    twisted:                            18.7.0-py37hfa6e2cd_1               --> 18.9.0-py36hfa6e2cd_1000  conda-forge
    unicodecsv:                         0.14.1-py37_0                       --> 0.14.1-py_1               conda-forge
    urllib3:                            1.23-py37_0                         --> 1.23-py36_1001            conda-forge
    wcwidth:                            0.1.7-py37_0                        --> 0.1.7-py_1                conda-forge
    webencodings:                       0.5.1-py37_1                        --> 0.5.1-py_1                conda-forge
    werkzeug:                           0.14.1-py37_0                       --> 0.14.1-py_0               conda-forge
    wheel:                              0.31.1-py37_0                       --> 0.32.2-py36_0             conda-forge
    widgetsnbextension:                 3.4.1-py37_0                        --> 3.4.2-py36_1000           conda-forge
    win_inet_pton:                      1.0.1-py37_1                        --> 1.0.1-py36_1002           conda-forge
    win_unicode_console:                0.5-py37_0                          --> 0.5-py36_1000             conda-forge
    wincertstore:                       0.2-py37_0                          --> 0.2-py36_1002             conda-forge
    wrapt:                              1.10.11-py37hfa6e2cd_2              --> 1.10.11-py36hfa6e2cd_1001 conda-forge
    xlrd:                               1.1.0-py37_1                        --> 1.1.0-py_2                conda-forge
    xlsxwriter:                         1.1.0-py37_0                        --> 1.1.1-py_0                conda-forge
    xlwings:                            0.11.8-py37_0                       --> 0.12.1-py36_0             conda-forge
    xlwt:                               1.3.0-py37_0                        --> 1.3.0-py_1                conda-forge
    zeromq:                             4.2.5-he025d50_1                    --> 4.2.5-vc14_2              conda-forge [vc14]
    zict:                               0.1.3-py37_0                        --> 0.1.3-py_0                conda-forge
    zope:                               1.0-py37_1                          --> 1.0-py36_1
    zope.interface:                     4.5.0-py37hfa6e2cd_0                --> 4.5.0-py36hfa6e2cd_1001   conda-forge

The following packages will be DOWNGRADED:

    anaconda-client:                    1.7.2-py37_0                        --> 1.7.1-py_0                conda-forge
    astroid:                            2.0.4-py37_0                        --> 2.0.3-py36_0              conda-forge
    bzip2:                              1.0.6-hfa6e2cd_5                    --> 1.0.6-vc14_1              conda-forge [vc14]
    curl:                               7.61.0-h7602738_0                   --> 7.60.0-vc14_0             conda-forge [vc14]
    datashape:                          0.5.4-py37_1                        --> 0.5.4-py36_0              conda-forge
    freetype:                           2.9.1-ha9979f8_1                    --> 2.8.1-vc14_0              conda-forge [vc14]
    greenlet:                           0.4.15-py37hfa6e2cd_0               --> 0.4.13-py36_0             conda-forge
    hdf5:                               1.10.2-hac2f561_1                   --> 1.10.2-vc14_0             conda-forge [vc14]
    hyperlink:                          18.0.0-py37_0                       --> 17.3.1-py_0               conda-forge
    icu:                                58.2-ha66f8fd_1                     --> 58.2-vc14_0               conda-forge [vc14]
    imageio:                            2.4.1-py37_0                        --> 2.3.0-py_1                conda-forge
    jupyter:                            1.0.0-py37_7                        --> 1.0.0-py_1                conda-forge
    libiconv:                           1.15-h1df5818_7                     --> 1.14-vc14_4               conda-forge [vc14]
    libtiff:                            4.0.9-h36446d0_2                    --> 4.0.9-vc14_0              conda-forge [vc14]
    libxml2:                            2.9.8-hadb2253_1                    --> 2.9.5-vc14_1              conda-forge [vc14]
    lxml:                               4.2.5-py37hef2cd61_0                --> 4.2.3-py36heafd4d3_0      conda-forge
    lzo:                                2.10-h6df0209_2                     --> 2.10-vc14_0               conda-forge [vc14]
    matplotlib:                         2.2.3-py37hd159220_0                --> 2.2.2-py36_1              conda-forge
    mkl_random:                         1.0.1-py37h77b88f5_1                --> 1.0.1-py36_0              conda-forge
    mpmath:                             1.0.0-py37_2                        --> 1.0.0-py_1                conda-forge
    nltk:                               3.3.0-py37_0                        --> 3.2.4-py36_0              conda-forge
    pyasn1-modules:                     0.2.2-py37_0                        --> 0.2.1-py_0                conda-forge
    pyqt:                               5.9.2-py37h6538335_2                --> 5.6.0-py36h764d66f_7      conda-forge
    python:                             3.7.0-hea74fb7_0                    --> 3.6.6-he025d50_0          conda-forge
    qt:                                 5.9.6-vc14h1e9a669_2                --> 5.6.2-vc14_1              conda-forge [vc14]
    rope:                               0.11.0-py37_0                       --> 0.10.7-py_1               conda-forge
    simplegeneric:                      0.8.1-py37_2                        --> 0.8.1-py_1                conda-forge
    sip:                                4.19.8-py37h6538335_0               --> 4.18.1-py36h6538335_0     conda-forge
    snappy:                             1.1.7-h777316e_3                    --> 1.1.7-vc14_1              conda-forge [vc14]
    spyder:                             3.3.1-py37_1                        --> 3.2.8-py36_0              conda-forge
    sqlite:                             3.24.0-h7602738_0                   --> 3.22.0-vc14_0             conda-forge [vc14]
    vc:                                 14.1-h0510ff6_4                     --> 14-0                      conda-forge
    yaml:                               0.1.7-hc54c509_2                    --> 0.1.7-vc14_0              conda-forge [vc14]
    zlib:                               1.2.11-h8395fce_2                   --> 1.2.11-vc14_0             conda-forge [vc14]

Proceed ([y]/n)? y

Downloading and Extracting Packages
conda-4.5.11         | 1.0 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::automat-0.7.0-py_1'.
CondaError: Cannot link a source that does not exist. c:\anaconda35\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

Rolling back transaction: done

CondaError: Cannot link a source that does not exist. c:\anaconda35\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

**Comment by maslovich** [comment]
Has anybody solved the problem? I tried the solutions offered in #7713, they did not help. Maybe I did not tried properly. What worked for you? Is there any 100% solution?

**Comment by MPullela29** [comment]
I tried all the solutions provided in #7713 with no luck. I got around it using conda PIP install instead of conda install .

pip install lightgbm

**Comment by msarahan** [comment]
Because these packages are coming from conda-forge, you should be filing issues on the appropriate conda-forge feedstocks.  For example, https://github.com/conda-forge/lightgbm-feedstock

This is most likely a problem with the packages produced by that recipe.  If the maintainers of that recipe can show that it's a problem with conda (via a reproducible test case), then we'll be happy to take a look.

Using pip is something you should do with extreme caution.  Pip lacks a dependency solver, and it will quite happily clobber things in your environment to make your most recent request satisfied, at the cost of any existing constraints in your environment.  Sometimes things will work by happenstance.  Other times, you'll make a horrible broken mess.

**Comment by msarahan** [comment]
One other observation here: the package that is failing is a noarch package:

```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::automat-0.7.0-py_1'.
```

That saves a lot of build time, but has been a delicate area.  Again, with a simple reproducible test case, we'll be happy to investigate any potential issue in conda.  Please make sure you're using the latest conda version in the meantime - there may be bugs that we have fixed recently.
