### ISSUE TITLE
Take mac deployment target into account in solver

### ISSUE THREAD

**Issue by minrk** [conda/conda#7902]
When a package is compiled for mac, it takes a MACOSX_DEPLOYMENT_TARGET (and sysroot), which determines a base runtime version of macOS the libraries should be compatible with. Currently, most packages build against the oldest environment they can find (mostly 10.9, these days), so that most users can assume that all conda packages work for them. However, some packages (e.g. Qt 5.9 or 5.12) require features not available on older versions, and thus require 10.10, or 10.12 and later, etc. It would be useful and seems sensible to include the host OS version and the package's deployment target in the solver, so that a package that requires 10.12 won't attempt installation on 10.9, for example. Among other things, this should make it easier for packages to safely advance their required mac version without resulting in incompatible packages being installed on older machines with obscure runtime errors.

**Comment by mingwandroid** [comment]
Very good points, and ones we've thought about in the past.

**Comment by kalefranz** [comment]
I think the plan right now is to solve this in a way that's tied in with the markers work (https://github.com/conda/conda/pull/7258). I guess we're still working through the details though.  The marker work is a dependency for some of the higher priority features we want to implement in the near future.  So it's definitely on the radar.
