### ISSUE TITLE
Launching jupyter notebook causes OSError exception, on Windows 7 Pro, 64 Bit

### ISSUE THREAD

**Issue by ReddyKilowatt** [conda/conda#7910]
**NOTE --I've intentionally installed a 32-bit Anaconda installer, because I need to deplpy stand-alone Python executables (built via PyInstaller), so that they run on 32-Bit Windows systems.

If I install the 64-Bit anaconda installer, I can only build 64-bit stand alone Python executables.**

## Current Behavior

(py36dev) C:\>jupyter notebook
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\ProgramData\Anaconda3\envs\py36dev\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

[I 16:51:01.839 NotebookApp] Serving notebooks from local directory: C:\
[I 16:51:01.839 NotebookApp] 0 active kernels
[I 16:51:01.839 NotebookApp] The Jupyter Notebook is running at:
[I 16:51:01.839 NotebookApp] http://localhost:8888/?token=3521a4f2d8ca37e29450e307780e7cceefc39bd0c08ab354
[I 16:51:01.839 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:51:01.855 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=3521a4f2d8ca37e29450e307780e7cceefc39bd0c08ab354
[I 16:51:01.964 NotebookApp] Accepting one-time-token-authenticated connection from ::1

### Steps to Reproduce

```
activate py36dev 
jupyter notebook

```

## Expected Behavior

The notebook should launch in the defautl web browser, without seeing the OSError exceptions in the console.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(py36dev) C:\>conda info

     active environment : py36dev
    active env location : C:\ProgramData\Anaconda3\envs\py36dev
            shell level : 1
       user config file : C:\Users\Z48176ZZ\.condarc
 populated config files : C:\Users\Z48176ZZ\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\z48176zz\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\z48176zz\AppData\Local\conda\conda\envs
                          C:\Users\Z48176ZZ\.conda\envs
               platform : win-32
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(py36dev) C:\>conda config --show-sources
==> C:\Users\Z48176ZZ\.condarc <==
channels:
  - conda-forge
  - defaults
report_errors: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(py36dev) C:\>conda list --show-channel-urls
# packages in environment at C:\ProgramData\Anaconda3\envs\py36dev:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py36h8b40cde_0    defaults
attrs                     18.2.0                     py_0    conda-forge
audioread                 2.1.5                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl    defaults
bleach                    3.0.2                      py_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
colorama                  0.4.0                      py_0    conda-forge
coverage                  4.5.1                    py36_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
ffmpeg                    3.4.2                         0    conda-forge
filelock                  3.0.9                      py_0    conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                     vc14_0  [vc14]  conda-forge
intel-openmp              2019.0                      118    defaults
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py36h39e3cac_0    defaults
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
joblib                    0.12.5                     py_0    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
librosa                   0.6.2                      py_0    conda-forge
libsodium                 1.0.16                   vc14_0  [vc14]  conda-forge
llvmlite                  0.24.0           py36h6538335_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mkl                       2019.0                      118    defaults
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  5.4.1                    py36_0    conda-forge
numba                     0.39.0           py36h830ac7b_0    defaults
numpy                     1.15.2           py36ha559c80_0    defaults
numpy-base                1.15.2           py36h8128ebf_0    defaults
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       10.0.1                   py36_0    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.6                      py_0    conda-forge
py                        1.7.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pytest                    3.5.0                    py36_0    conda-forge
python                    3.6.6                hea74fb7_0    defaults
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywinpty                  0.5.2                    py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtconsole                 4.4.2                      py_1    conda-forge
resampy                   0.2.1                      py_1    conda-forge
scikit-learn              0.20.0           py36heebcf9a_1    defaults
scipy                     1.1.0            py36h4f6bf74_1    defaults
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.0.1                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
tox                       3.5.2                      py_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
vc                        14                            0    conda-forge
virtualenv                15.1.0                   py36_0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
widgetsnbextension        3.2.1                    py36_1    conda-forge
wincertstore              0.2                      py36_0    conda-forge
winpty                    0.4.3                         4    conda-forge
zeromq                    4.2.5                    vc14_2  [vc14]  conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
```
</p></details>

**Comment by msarahan** [comment]
Your packages are coming from conda-forge. You need to post your issue there.

Https://GitHub.com/conda-forge/winpty-feedstock

**Comment by mingwandroid** [comment]
Worse you are mixing defaults and conda-forge. Try one or the other in any given env.

**Comment by ReddyKilowatt** [comment]
>>Worse you are mixing defaults and conda-forge (we are not very compatible yet). Try one or the other in any given env.
How is a user supposed to know this is a problem, if the tool/environment doesn't tell you?

**Comment by ReddyKilowatt** [comment]
>>Https://GitHub.com/conda-forge/
Under which repo at conda-forge do I post the bug report?
