### ISSUE TITLE
Cannot update or uninstall local package in environment

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#7926]
## Current Behavior

When creating python entry points for a local package, conda hardlinks the new entry point to "conda.exe" in the conda installation folder. This behavior is different from non-local packages, which hardlink the entry point to the corresponding executable in the package cache. The latter is expected, but I would argue the former is a bug. Particularly, it is reasonable to want to have a "read-only" conda installation (whereas you certainly wouldn't want a read-only package cache!), and to accomplish this via file permissions. This breaks when something in the environment folder hardlinks to something in the conda installation folder, forcing it to share the same permissions.

### Steps to Reproduce

I've [attached](https://github.com/conda/conda/files/2526954/test.zip)
 a script that builds a test package, creates a new environment with the test package, and then attempts to uninstall the test package to demonstrate this issue. If you set custom file permissions on your conda installation directory before running the "env_failure.bat" script, you will see those permissions on the "test_entry_point.exe" file. If those permissions were read-only, the script will fail when trying to uninstall the test package from the environment.

## Expected Behavior

Script should not fail. Package should be able to be cleanly removed from the environment, regardless of permissions on the conda installation directory.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : [USER DIR]\.condarc
 populated config files : [CONDA ROOT]\.condarc
          conda version : 4.5.11
    conda-build version : 3.16.1
         python version : 3.6.6.final.0
       base environment : [CONDA ROOT]  (read only)
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by osahene** [comment]
Can you give out the step by step procedure on how to resolve the issue?

**Comment by Bezier89** [comment]
@osahene Do you mean steps to _reproduce_ the issue? Here's exact steps on Windows 10:

1. Navigate to "conda.exe" in the the "Scripts" folder of your conda installation folder. Right-click on it and select "Properties".
2. Click on the "Security" tab. Click "Advanced". Click "Change Permissions". Click "Add". 
3. Click "Select a principal" and choose a group that applies to the current user. I used [MACHINE_NAME]\Users
4. Under "Type", select "Deny".
6. Click "Show advanced permissions". Check "Delete". Uncheck all other boxes.
7. Click "OK" to apply permissions. To verify, attempt to delete conda.exe. It should either fail or ask for escalated privileges, which you can cancel out of.
8. If step 7 does delete conda.exe, undo the delete, and ensure that the current user does not have "Full control" on the conda installation folder (Windows permissions are a weird beast...)
8. Download this [test.zip](https://github.com/conda/conda/files/2526954/test.zip) file.
9. Unzip test.zip. Inside it, run the following command: `env_failure.bat path\to\miniconda3\Scripts\conda.exe` (replace path to conda.exe using the file you just set permissions on).
10. Watch conda fail when trying to remove the test package from the environment!
