### ISSUE TITLE
Conda installation problem with scipy on windows - moduletnc.pyd should be moduleTNC.pyd

### ISSUE THREAD

**Issue by slamer59** [conda/conda#7930]
Hello,
I report this issue to scipy. It seems not related to scipy package.
https://github.com/scipy/scipy/issues/9425

If I replace manually moduletnc.pyd to moduleTNC.pyd it works on windows. 
Tarball seems to have moduleTNC.pyd case sensitive. https://anaconda.org/anaconda/scipy/files

I'm on windows 7 wit conda 4.5.11

Feel free to ask for more informations 
Regards,
Thomas

**Comment by mingwandroid** [comment]
Have you enabled case sensitivity on the Windows kernel?

**Comment by slamer59** [comment]
Not sure. 
Like explain here ? 
https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

**Comment by mingwandroid** [comment]
Please do not do that, I was asking whether you'd already do it though.

**Comment by slamer59** [comment]
So, I didn't do this.
