### ISSUE TITLE
conda update -n base conda takes 20+ minutes to solve environment

### ISSUE THREAD

**Issue by jeremymatt** [conda/conda#7938]
## Current Behavior
When I type try to run ```conda update -n base conda```, conda hung for around 20-minutes on 'Solving environment' and then returned a package plan that did not include an updated version of conda.  The package plan that was returned is provided below.  

<details>
  <summary>``` ## Package Plan ##```</summary>

  environment location: C:\Users\jmatt\Anaconda3

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libarchive-3.3.2           |       h1d0d21d_1         4.0 MB
    lz4-c-1.8.2                |           vc14_0         254 KB  conda-forge
    libcurl-7.61.1             |       h7602738_0         249 KB
    ------------------------------------------------------------
                                           Total:         4.5 MB

The following packages will be UPDATED:

    jpeg:       9b-hb83a4c4_2         --> 9b-vc14_2             conda-forge [vc14]
    libcurl:    7.61.1-h2a8f88b_0     --> 7.61.1-h7602738_0
    libsodium:  1.0.16-h9d3ae62_0     --> 1.0.16-vc14_0         conda-forge [vc14]
    libxslt:    1.1.32-hf6f1972_0     --> 1.1.32-vc14_0         conda-forge [vc14]
    lz4-c:      1.8.1.2-h2fa13f4_0    --> 1.8.2-vc14_0          conda-forge [vc14]
    tk:         8.6.8-hfa6e2cd_0      --> 8.6.8-vc14_0          conda-forge [vc14]
    zeromq:     4.2.5-he025d50_1      --> 4.2.5-vc14_2          conda-forge [vc14]

The following packages will be DOWNGRADED:

    astropy:    3.0.5-py36he774522_0  --> 3.0.4-py36hfa6e2cd_0
    bzip2:      1.0.6-hfa6e2cd_5      --> 1.0.6-vc14_1          conda-forge [vc14]
    curl:       7.61.1-h2a8f88b_0     --> 7.60.0-vc14_0         conda-forge [vc14]
    cython:     0.29-py36ha925a31_0   --> 0.28.5-py36h6538335_0
    freetype:   2.9.1-ha9979f8_1      --> 2.8.1-vc14_0          conda-forge [vc14]
    gevent:     1.3.7-py36he774522_1  --> 1.3.6-py36hfa6e2cd_0
    hdf5:       1.10.2-hac2f561_1     --> 1.10.2-vc14_0         conda-forge [vc14]
    icu:        58.2-ha66f8fd_1       --> 58.2-vc14_0           conda-forge [vc14]
    krb5:       1.16.1-h038dc86_6     --> 1.14.6-vc14_0         conda-forge [vc14]
    libarchive: 3.3.3-h798a506_0      --> 3.3.2-h1d0d21d_1
    libiconv:   1.15-h1df5818_7       --> 1.14-vc14_4           conda-forge [vc14]
    libpng:     1.6.35-h2a8f88b_0     --> 1.6.34-vc14_0         conda-forge [vc14]
    libtiff:    4.0.9-h36446d0_2      --> 4.0.9-vc14_0          conda-forge [vc14]
    libxml2:    2.9.8-hadb2253_1      --> 2.9.5-vc14_1          conda-forge [vc14]
    llvmlite:   0.25.0-py36_0         --> 0.24.0-py36h6538335_0
    lxml:       4.2.5-py36hef2cd61_0  --> 4.1.1-py36he0adb16_0
    lzo:        2.10-h6df0209_2       --> 2.10-vc14_0           conda-forge [vc14]
    matplotlib: 3.0.0-py36hd159220_0  --> 2.2.2-py36h153e9ff_0
    mistune:    0.8.4-py36he774522_0  --> 0.8.3-py36hfa6e2cd_1
    numba:      0.40.0-py36hf9181ef_0 --> 0.39.0-py36h830ac7b_0
    pillow:     5.3.0-py36hdc69c19_0  --> 5.1.0-py36h0738816_0
    pyqt:       5.9.2-py36h6538335_2  --> 5.6.0-py36_2
    pywavelets: 1.0.1-py36h8c2d366_0  --> 1.0.0-py36h452e1ab_0
    qt:         5.9.6-vc14h1e9a669_2  --> 5.6.2-vc14_1          conda-forge [vc14]
    snappy:     1.1.7-h777316e_3      --> 1.1.7-vc14_1          conda-forge [vc14]
    sqlalchemy: 1.2.12-py36he774522_0 --> 1.2.11-py36hfa6e2cd_0
    sqlite:     3.25.2-hfa6e2cd_0     --> 3.22.0-vc14_0         conda-forge [vc14]
    twisted:    18.9.0-py36he774522_0 --> 18.7.0-py36hfa6e2cd_1
    vc:         14.1-h0510ff6_4       --> 14-h0510ff6_3
    yaml:       0.1.7-hc54c509_2      --> 0.1.7-vc14_0          conda-forge [vc14]
    zlib:       1.2.11-h8395fce_2     --> 1.2.11-vc14_0         conda-forge [vc14]

Proceed ([y]/n)? n
</details>
    
<br/>

NOTE: the conda version I have installed is 4.5.11 - I'm not sure if this is the most recent version and haven't been able to find a command or resource (other than ```conda update conda```) to check what the most recent version is.  I also had a similar problem when trying to ```conda install websocket-client``` when websocket client was already installed - I wonder if the current version of conda has trouble when the most recent version of a package is already installed.

NOTE 2 (edit 2018-11-06): ```conda update --all``` solved the environment in a reasonable amount of time (~1 min - I didn't time it precisely).

### Steps to Reproduce

```
conda update -n base conda
```

As I mentioned above, ```conda install websocket-client``` also hung at 'Solving environment' - I already had websocket-client version 0.53.0 installed when I tried to run the install command

## Expected Behavior
Conda should either:
1. If the most recent version is installed, conda should promptly inform the user that an update isn't needed.
1. If a newer version is available, I'd expect Conda to solve the environment in a shorter period of time. I think that less than 1-2 minutes would be reasonable - 20+ minutes is too long

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\Users\jmatt\Anaconda3
            shell level : 1
       user config file : C:\Users\jmatt\.condarc
 populated config files : C:\Users\jmatt\.condarc
          conda version : 4.5.11
    conda-build version : 3.16.1
         python version : 3.6.6.final.0
       base environment : C:\Users\jmatt\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\jmatt\Anaconda3\pkgs
                          C:\Users\jmatt\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jmatt\Anaconda3\envs
                          C:\Users\jmatt\AppData\Local\conda\conda\envs
                          C:\Users\jmatt\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
ssl_verify: True
channels:
  - defaults
  - conda-forge
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(base) C:\Users\jmatt>conda list --show-channel-urls
# packages in environment at C:\Users\jmatt\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.2                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
appdirs                   1.4.3            py36h28b3542_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   2.0.4                    py36_0    defaults
astropy                   3.0.5            py36he774522_0    defaults
atomicwrites              1.2.1                    py36_0    defaults
attrs                     18.2.0           py36h28b3542_0    defaults
automat                   0.7.0                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.6.3                    py36_0    defaults
bitarray                  0.8.3            py36hfa6e2cd_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    defaults
bleach                    3.0.2                    py36_0    defaults
blosc                     1.14.4               he51fdeb_0    defaults
bokeh                     0.13.0                   py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h452e1ab_1    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py36_0    defaults
cffi                      1.11.5           py36h74b6da3_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               0.6.1                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.0                    py36_0    defaults
comtypes                  1.1.7                    py36_0    defaults
conda                     4.5.11                   py36_0    defaults
conda-build               3.16.1                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py36_0    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.3.1            py36h74b6da3_0    defaults
curl                      7.61.1               h2a8f88b_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.29             py36ha925a31_0    defaults
cytoolz                   0.9.0.1          py36hfa6e2cd_1    defaults
dask                      0.19.4                   py36_0    defaults
dask-core                 0.19.4                   py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
decorator                 4.3.0                    py36_0    defaults
defusedxml                0.5.0                    py36_1    defaults
distributed               1.23.3                   py36_0    defaults
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3                    py36_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hfa6e2cd_2    defaults
filelock                  3.0.9                    py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.6                    py36_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.16.0                   py36_2    defaults
geographiclib             1.49                       py_0    conda-forge
geopy                     1.17.0                     py_0    conda-forge
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.7            py36he774522_1    defaults
glob2                     0.6                      py36_1    defaults
greenlet                  0.4.15           py36hfa6e2cd_0    defaults
h5py                      2.8.0            py36h3bdd7fb_2    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1                    py36_0    defaults
hyperlink                 18.0.0                   py36_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.7                      py36_0    defaults
imageio                   2.4.1                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.6                      py36_0    defaults
incremental               17.5.0                   py36_0    defaults
intel-openmp              2019.0                      118    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.0.1            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              1.0.0                    py36_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.1                   py36_0    defaults
jinja2                    2.10                     py36_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.2                   py36_0    defaults
jupyterlab_launcher       0.13.1                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
keyring                   15.1.0                   py36_0    defaults
kiwisolver                1.0.1            py36h6538335_0    defaults
krb5                      1.16.1               h038dc86_6    defaults
lazy-object-proxy         1.3.1            py36hfa6e2cd_2    defaults
libarchive                3.3.3                h798a506_0    defaults
libcurl                   7.61.1               h2a8f88b_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.35               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.0                hd619d38_4    defaults
libtiff                   4.0.9                h36446d0_2    defaults
libxml2                   2.9.8                hadb2253_1    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.25.0                   py36_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lxml                      4.2.5            py36hef2cd61_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py36hfa6e2cd_1    defaults
matplotlib                3.0.0            py36hd159220_0    defaults
mccabe                    0.6.1                    py36_1    defaults
menuinst                  1.4.14           py36hfa6e2cd_0    defaults
mistune                   0.8.4            py36he774522_0    defaults
mkl                       2019.0                      118    defaults
mkl-service               1.1.2            py36hb217b18_5    defaults
mkl_fft                   1.0.6            py36hdbbee80_0    defaults
mkl_random                1.0.1            py36h77b88f5_1    defaults
more-itertools            4.3.0                    py36_0    defaults
mpmath                    1.0.0                    py36_2    defaults
msgpack-python            0.5.6            py36he980bc4_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1                    py36_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.2                      py36_1    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.0                    py36_0    defaults
numba                     0.40.0           py36hf9181ef_0    defaults
numexpr                   2.6.8            py36h9ef55f4_0    defaults
numpy                     1.15.3           py36ha559c80_0    defaults
numpy-base                1.15.3           py36h8128ebf_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.46                     py36_0    defaults
openpyxl                  2.5.9                    py36_0    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
packaging                 18.0                     py36_0    defaults
pandas                    0.23.4           py36h830ac7b_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.3.1                    py36_0    defaults
partd                     0.3.9                    py36_0    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.0                    py36_0    defaults
pep8                      1.7.1                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.3.0            py36hdc69c19_0    defaults
pip                       10.0.1                   py36_0    defaults
pkginfo                   1.4.2                    py36_1    defaults
pluggy                    0.8.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.4.2                    py36_0    defaults
prompt_toolkit            2.0.6                    py36_0    defaults
psutil                    5.4.7            py36hfa6e2cd_0    defaults
py                        1.7.0                    py36_0    defaults
pyasn1                    0.4.4            py36h28b3542_0    defaults
pyasn1-modules            0.2.2                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36hfa6e2cd_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36hfa6e2cd_9    defaults
pycurl                    7.43.0.2         py36h74b6da3_0    defaults
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pyhamcrest                1.9.0                    py36_2    defaults
pylint                    2.1.1                    py36_0    defaults
pyodbc                    4.0.24           py36h6538335_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.2.2                    py36_0    defaults
pyqt                      5.9.2            py36h6538335_2    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36he6f6034_0    defaults
pytest                    3.9.1                    py36_0    defaults
pytest-arraydiff          0.2              py36h39e3cac_0    defaults
pytest-astropy            0.4.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.3.0                    py36_0    defaults
python                    3.6.6                hea74fb7_0    defaults
python-dateutil           2.7.3                    py36_0    defaults
python-libarchive-c       2.8                      py36_6    defaults
pytz                      2018.5                   py36_0    defaults
pywavelets                1.0.1            py36h8c2d366_0    defaults
pywin32                   223              py36hfa6e2cd_1    defaults
pywinpty                  0.5.4                    py36_0    defaults
pyyaml                    3.13             py36hfa6e2cd_0    defaults
pyzmq                     17.1.2           py36hfa6e2cd_0    defaults
qt                        5.9.6            vc14h1e9a669_2    defaults
qtawesome                 0.5.1                    py36_1    defaults
qtconsole                 4.4.2                    py36_0    defaults
qtpy                      1.5.2                    py36_0    defaults
requests                  2.19.1                   py36_0    defaults
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36hfa6e2cd_0    defaults
scikit-image              0.14.0           py36h6538335_1    defaults
scikit-learn              0.20.0           py36heebcf9a_1    defaults
scipy                     1.1.0            py36h4f6bf74_1    defaults
seaborn                   0.9.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
service_identity          17.0.0           py36h28b3542_0    defaults
setuptools                40.4.3                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.11.0                   py36_1    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.0.5                    py36_0    defaults
sphinx                    1.8.1                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.1                    py36_1    defaults
spyder-kernels            0.2.6                    py36_0    defaults
sqlalchemy                1.2.12           py36he774522_0    defaults
sqlite                    3.25.2               hfa6e2cd_0    defaults
statsmodels               0.9.0            py36h452e1ab_0    defaults
sympy                     1.3                      py36_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36hfa6e2cd_0    defaults
tqdm                      4.26.0           py36h28b3542_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
twisted                   18.9.0           py36he774522_0    defaults
typed-ast                 1.1.0            py36hfa6e2cd_0    defaults
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.23                     py36_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1                    py36_1    defaults
websocket-client          0.53.0                py36_1000    conda-forge
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.2                   py36_0    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
win_inet_pton             1.0.1                    py36_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36hfa6e2cd_2    defaults
xlrd                      1.1.0                    py36_1    defaults
xlsxwriter                1.1.2                    py36_0    defaults
xlwings                   0.12.1                   py36_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.2.5                he025d50_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.5.0            py36hfa6e2cd_0    defaults

```
</p></details>

**Comment by gwerbin** [comment]
Solving environment is painfully slow (5+ minutes) on Windows for me as well, once an environment gets beyond a certain size. I have an almost-identical environment on Linux where the "solving" step, for almost the same package installation, takes less than 1 minute.

**Comment by mingwandroid** [comment]
Note to self: ensure pycosat is compiled in release mode.

**Comment by gabefair** [comment]
I've noticed that as well, when I run `conda update -all` on my Ubuntu 16.04 machine it will downgrade a bunch of stuff it just finished upgrading. Could it be a bug?

**Comment by msarahan** [comment]
I recommend trying conda 4.6.0, which has an early release available with:

```
conda update -c conda-canary conda
```

It's important to understand that conda will not necessarily return the exact same answer every time.  The nature of the solver is not completely deterministic.  We're working to improve that (see #7700 and #7698).

**Comment by msarahan** [comment]
Using the anaconda channel actually makes this much worse, because it is a bad merge of old packages (the "free" channel) and new ones from defaults (the "main") channel.  It is better to omit ``-c anaconda`` completely and let conda use its default channel configuration, which will have the same packages, but in a better priority listing.

Caching solutions is a pretty hard problem.  https://yihui.name/en/2018/06/cache-invalidation/

You may be able to learn more by using the -vv or -vvv flag to conda.  This will dump a lot more info to help understand exactly which part is going slow.

Generally, extreme slowness is caused by conda bending over backwards to satisfy some overly broad constraint, or because some metadata change or package removal has rendered your environment "inconsistent."  In such cases, conda ends up downgrading things little by little to try to satisfy the environment, and that little-by-little behavior is terribly slow.

The easiest way to get speed back (other than to avoid the ``anaconda`` channel) is probably to create a fresh environment with only what you need, and use that rather than depending on a root env with a ton of old state.  Limiting the size of the problem that conda needs to solve (in terms of both specs to solve, packages already in the env, and size of the repodata) is always the best way to keep it fast.

**Comment by jeremymatt** [comment]
Thanks for the info on what might be going on.

**Comment by PauloCarvalhoRJ** [comment]
If anyone is still interested, mine is running for 40 minutes and counting.

**Comment by PauloCarvalhoRJ** [comment]
Sluguish processess like that should report progress to the user.  Someone taught that to me 30 years algo in an User Interfaces 101 class.

**Comment by bobcolner** [comment]
Whats the status of this issue? Does anaconda even care??

**Comment by PauloCarvalhoRJ** [comment]
Reporting the progress would be fine.  I could decide whether I have time to prepare an expresso or to bake a cake.

**Comment by gsakkis** [comment]
Just use [mamba](https://github.com/mamba-org/mamba) instead; it's orders of magnitude faster.

**Comment by enricovara** [comment]
This this issue being open 4 years on a suggestion to uninstall conda altogether and start fresh with some new version that presumably doesn't have this issue?

**Comment by tlvu** [comment]
@enricovara 

The conda dependency solver is slow with large repo (conda-forge).  That problem is know and is still not solved.  We switched to mamba which is way faster but in return is less precise.  

With mamba, some packages are not at the latest version even thought no constraints for them to be older.   So looks like the mamba dependency solver is less optimized in terms of precision but is more optimized in terms of speed.

So a work-around for us is to pin key packages at latest version with mamba to avoid it being downgraded for no reason.  So we have mamba speed with latest version for the packages that we care about.  For the rest that might be a few versions older, we do not care.

Hope it helps.  Let's make the most out of what is available.

**Comment by enricovara** [comment]
@tlvu Thanks for your reply!

I'm unclear on a couple of things — would you be able to help, please?

1) How slow is slow? My solver has now been running for 18 hours following a ` conda update -n base conda` terminal command on a 2018 MacBook Pro running Big Sur 11.6.8. Is there hope that it will finish at some point in the next few days?

2) If eventually the solver does make it, will it update my conda to a version that uses mamba - did I understand correctly? Or does mamba have nothing to do with the conda version?

3) Is it better if I kill this solver now and try again using mamba? If so, how?

Many thanks,
Enrico

**Comment by tlvu** [comment]
> My understanding:
> 
>  1. mamba can be installed by calling `conda install mamba -n base -c conda-forge`
> 
>  2. `mamba` replaces `conda` in all normal conda commands except `conda activate my_env` and `conda deactivate`, and solves faster
>

Exact
 
> I'm unclear on a couple of things:
> 
>  1. How slow is my current conda solver? It has now been running for 18 hours following a `conda update -n base conda` terminal command on a 2018 MacBook Pro running Big Sur 11.6.8. Is there hope that it will finish at some point in the next few days or is it a lost cause?
> 

It's probably a lost cause.  The `base` env should only contain `conda` and `mamba`, nothing else so updating it is very fast.

You probably installed a lot of other stuff in `base`, that's why it's so slow to update.   Everything else should be in their own env, not in `base`.

You might want to nuke your `base` env and restart installing `conda` from scratch to re-create it clean.  I am not telling you how since I do not know how you installed `conda` initially.  Please search yourself.


>  2. If eventually the solver does make it, will it again take forever to run the command described in point 1?
> 

If `base` env is clean, installing `mamba` into it will be fast.

>   3. Is it better if I kill this solver now and invest solving time to install mamba (as described in point 1) instead?
> 

Already answered.

>  4. Importantly: if I install mamba with the command described in point 1, will I then be able to update conda? Is there any use in updating conda in the first place, once I have mamba?
> 

I am not sure but if my understanding is correct, `mamba` depends on `conda` so it will pull `conda` anyways.  But no harm in installing `conda` first.  Good to have both anyways since a `mamba` is mostly for installing/updating stuff, for all other "administration" commands, it's still `conda`.

**Comment by PauloCarvalhoRJ** [comment]
> 1. How slow is my current conda solver? It has now been running for 18 hours following a `conda update -n base conda` terminal command on a 2018 MacBook Pro running Big Sur 11.6.8. Is there hope that it will finish at some point in the next few days or is it a lost cause?

Mine went on for 4 days in a row until my computer was forced to reboot (Windows Update).

My two cents on mamba:  it works well, but somehow it can't do a `mamba update --all`.  It quits with an error stating unsupported syntax or something like that.  I have to specifiy each package explicitly.  So, mamba is not exactly a solution right now, more like a workaround.
