### ISSUE TITLE
ImportError: No module named conda.cli

### ISSUE THREAD

**Issue by adsherman** [conda/conda#7939]
**I'm submitting a...**
  - [X ] bug report
  - [ ] feature request

## Current Behavior

Calling conda in bash-4.1 causes an ImportError: No module named conda.cli

Everything worked yesterday, and to my knowledge I did not change anything overnight.

```
-bash-4.1$ export PATH=/home/graduate/adsherma/miniconda2/bin
-bash-4.1$ echo $PATH
/home/graduate/adsherma/miniconda2/bin
-bash-4.1$ which python
~/miniconda2/bin/python
-bash-4.1$ which conda
~/miniconda2/bin/conda
-bash-4.1$ conda
Traceback (most recent call last):
  File "/home/graduate/adsherma/miniconda2/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
-bash-4.1$ export PATH=/home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin:$PATH
-bash-4.1$ echo $PATH
/home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin:/home/graduate/adsherma/miniconda2/bin
-bash-4.1$ which python
~/miniconda2/envs/tZqAnalysis/bin/python
-bash-4.1$ which conda
~/miniconda2/envs/tZqAnalysis/bin/conda
-bash-4.1$ conda
Traceback (most recent call last):
  File "/home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
-bash-4.1$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>
```

### Steps to Reproduce

Minimally, just exporting the path to the environment I want to use and trying to open conda won't work. Sourcing activate manually by absolute path does not work either.

```
export PATH=/home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin
conda
```

```
-bash-4.1$ source /home/graduate/adsherma/miniconda2/bin/activate
Traceback (most recent call last):
  File "/home/graduate/adsherma/miniconda2/bin/conda", line 4, in <module>
    import conda.cli
```

```
-bash-4.1$ /home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin/conda
Traceback (most recent call last):
  File "/home/graduate/adsherma/miniconda2/envs/tZqAnalysis/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
```

```
-bash-4.1$ /home/graduate/adsherma/miniconda2/bin/conda
Traceback (most recent call last):
  File "/home/graduate/adsherma/miniconda2/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named conda.cli
```

## Expected Behavior

Conda should probably respond with this 

```
Alexs-MacBook-Pro-2:~ adsherman$ conda
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
...
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

All environment information will show show conda command not found, but here you go:

```
-bash-4.1$ conda info
-bash: conda: command not found
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
-bash-4.1$ conda config --show-sources
-bash: conda: command not found
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
-bash-4.1$ conda list --show-channel-urls
-bash: conda: command not found
```
</p></details>

I tried stripping everything but conda from my PATH and it still did not work. Python worked, and 'which conda' shows the path, but I get this import error. I did not change anything to my knowledge and it broke overnight, everything was fine yesterday. I'm baffled!

**Comment by adsherman** [comment]
Additionally, deleting the miniconda2 directory and installing anaconda2 produces the same problem

**Comment by rargelaguet** [comment]
Same problem here

**Comment by Lya-Batlle-Rafferty-Bose** [comment]
It just happened to me, directly after the installation of an updated version of Scikit-Learn.  Not only do I get this error, but I am not unable to run Jupyter Notebooks as well.

**Comment by Rauschii** [comment]
Me too — any solutions?

**Comment by WenjieZ** [comment]
I have a similar problem.

When I tried to upgrade pandas 0.23 -- py3.7 to pandas 0.24 -- py3.6 via the conda command, I got this error.

**Comment by Lya-Batlle-Rafferty-Bose** [comment]
I ended up having to remove and reinstall anaconda also.

**Comment by pfeffer90** [comment]
I am facing a similar problem after installing sympy, via conda install. 

```
conda activate
Traceback (most recent call last):
  File "/home/pfeiffer/Applications/miniconda2/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

**Comment by bgavran** [comment]
I'm facing the same problem, after running `conda install -c anaconda python=3.7`. 
I can't run any `conda` command on my machine anymore - I'm getting the exact same error:

```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

**Comment by dyukha** [comment]
Same here, after `conda update python`.

**Comment by hbasafa** [comment]
I think reinstalling is the only solution to this problem.
any other solutions appreciated!

**Comment by SongJiaxin95** [comment]
Me too,I have a similar problem.
When I tried to upgrade python verson
use   conda install python=3.5   I got this error.

**Comment by SongJiaxin95** [comment]
Me too,I have a similar problem.
When I tried to upgrade python version
use conda install python=3.5 I got this error.

**Comment by getacat** [comment]
same here, after installing pytourch

**Comment by getacat** [comment]
i solve the problem by reinstalling anaconda
我安装pytorch的时候遇到了相同的问题,重装anaconda解决了这个问题.出现这个报错的原因是,我用conda安装pytorch的时候忘记激活虚拟环境,导致conda的配置被改变.

**Comment by xiangchen2011** [comment]
I got the same error.
Reinstalling seems the only solution here.

**Comment by getacat** [comment]
yes you are right.中国人？

---Original---

**Comment by xiangchen2011** [comment]
对的呀，你咋看出来

**Comment by getacat** [comment]
你的名字不是汉字吗老哥哈哈哈哈哈哈哈笑死我了



---Original---

**Comment by getacat** [comment]
from祥辰2011



---Original---

**Comment by xiangchen2011** [comment]
好吧，被你发现了。。。。尴尬

**Comment by getacat** [comment]
最近学校的网没法翻墙了，不知道是因为高压政策还是因为要装5G，苦逼，git都上不了



---Original---

**Comment by xiangchen2011** [comment]
我好久没弄了，升级了下什么，崩了，气

**Comment by getacat** [comment]
我回答是不是说我是安装pytorch的时候遇到的？哥们什么专业的？



---Original---

**Comment by xiangchen2011** [comment]
Computer Science
getacat <notifications@github.com> 于2019年9月15日周日 下午9:54写道：

**Comment by getacat** [comment]
fine, computer science and technology.这不废话吗(눈_눈)。不聊啦拜拜



---Original---

**Comment by luyuhao98** [comment]
> i solve the problem by reinstalling anaconda
> 我安装pytorch的时候遇到了相同的问题,重装anaconda解决了这个问题.出现这个报错的原因是,我用conda安装pytorch的时候忘记激活虚拟环境,导致conda的配置被改变.

过于真实。遇到同样的情况

**Comment by getacat** [comment]
哈哈



---Original---

**Comment by YancyW** [comment]
Similar, problem.  
But, I guess I know why this happened.  
I install django yesterday.  But I forget to change env, I install it with "conda install django" directly under the default env.
When django was installed, it showed  "python3.7->python3.6",  But my python is 3.7.
As a result, my conda can't open today.  

Thus, this problem is always because python version is changed.
I reinstall the anaconda3 with ./Anaconda3-vxxx.sh -u to the original directory to solve this problem.

But, I wonder even if we use the env, how should we do when some package want to change python version???

**Comment by ucasiggcas** [comment]
from conda.cli import main

No module named conda

**Comment by ucasiggcas** [comment]
any one has solved the problem ?
pls help me ,thx

**Comment by getacat** [comment]
reinstall anaconda



---Original---
