### ISSUE TITLE
Windows activate does not work in a batch file

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#794]
See https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/QMwqUbaVQDc. If you run 

```bat
activate py33
python -V
```

in a batch file, it does not work, but if you run

```bat
activate py33 && python -V
```

it does. I did not verify it yet.

**Comment by davidh-ssec** [comment]
I ran in to this issue myself and I'm really happy I found this report after spending way too long trying to find my own work around. Using `call` seemed to work as I expected. I was able to do stuff like:

    call activate myenv || echo It Failed

This was on a Windows 7 laptop.

**Comment by wulmer** [comment]
@msarahan I think this issue can be closed.

**Comment by msarahan** [comment]
Thanks @wulmer, agreed.  Thanks also @davidh-ssec for the example of how to activate in a script.

**Comment by Mathnerd314** [comment]
It would be nice if this was documented somewhere more obvious, e.g. under https://conda.io/docs/using/envs.html#change-environments-activate-deactivate
