### ISSUE TITLE
cannot run mlflow on Rstudio/databricks

### ISSUE THREAD

**Issue by sorgina13-zz** [conda/conda#7957]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by sorgina13** [comment]
>mlflow::mlflow_install()
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/loarriza@microsoft.com/.conda/envs/r-mlflow:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2l             |                0         3.2 MB
    zlib-1.2.11                |                0         109 KB
    python-2.7.13              |                0        11.5 MB
    certifi-2016.2.28          |           py27_0         211 KB
    setuptools-36.4.0          |           py27_1         557 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    ------------------------------------------------------------
                                           Total:        17.1 MB

The following NEW packages will be INSTALLED:

    certifi:    2016.2.28-py27_0
    openssl:    1.0.2l-0        
    pip:        9.0.1-py27_1    
    python:     2.7.13-0        
    readline:   6.2-2            (soft-link)
    setuptools: 36.4.0-py27_1   
    sqlite:     3.13.0-0         (soft-link)
    tk:         8.5.18-0         (soft-link)
    wheel:      0.29.0-py27_0    (soft-link)
    zlib:       1.2.11-0        

Fetching packages ...
openssl-1.0.2l 100% |###############################| Time: 0:00:00  80.19 MB/s
zlib-1.2.11-0. 100% |###############################| Time: 0:00:00  26.32 MB/s
python-2.7.13- 100% |###############################| Time: 0:00:00  53.99 MB/s
certifi-2016.2 100% |###############################| Time: 0:00:00  44.92 MB/s
setuptools-36. 100% |###############################| Time: 0:00:00  52.44 MB/s
pip-9.0.1-py27 100% |###############################| Time: 0:00:00  57.33 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  10%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/anaconda2/lib/python2.7/site-packages/conda/install.py", line 1042, in link
    with Locked(prefix), Locked(pkgs_dir):
  File "/anaconda2/lib/python2.7/site-packages/conda/lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/anaconda2/pkgs/.conda_lock-28202'
Error: Error 1 occurred creating conda environment r-mlflow
> # Log parameters
> mlflow_log_param("param_int", my_int)
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  processx error: 'No such file or directory' at unix/processx.c:423
> column <- mlflow_log_param("column", 1)
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  processx error: 'No such file or directory' at unix/processx.c:423
