### ISSUE TITLE
conda install [-f] -v python=3.7.1 fails with UnsatisfiableError on R packages(!)

### ISSUE THREAD

**Issue by smcinerney** [conda/conda#7958]
`conda install -f -v python=3.7.1` fails with this error on R packages, which should not be dependencies of Python.

```conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7.1
  - r-rjdbc
  - r-rsconnect
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
    active environment : base
    active env location : /opt/anaconda3
            shell level : 1
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64 [...]
               platform : osx-64
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by smcinerney** [comment]
And yet `conda info python=3.7.1` confirms it does not have any R package dependencies:

```python 3.7.1 haf84260_3
-----------------------
file name   : python-3.7.1-haf84260_3.tar.bz2
name        : python
version     : 3.7.1
build string: haf84260_3
build number: 3
channel     : https://repo.anaconda.com/pkgs/main/osx-64
size        : 21.1 MB
arch        : None
constrains  : ()
license     : PSF
md5         : 65da4664b1c97b498a39503f32ff2021
platform    : None
subdir      : osx-64
timestamp   : 1540322026371
url         : https://repo.anaconda.com/pkgs/main/osx-64/python-3.7.1-haf84260_3.tar.bz2
dependencies:
    libcxx >=4.0.1
    libffi >=3.2.1,<4.0a0
    ncurses >=6.1,<7.0a0
    openssl >=1.1.1,<1.1.2.0a0
    readline >=7.0,<8.0a0
    sqlite >=3.25.2,<4.0a0
    tk >=8.6.8,<8.7.0a0
    xz >=5.2.4,<6.0a0
    zlib >=1.2.11,<1.3.0a0
    pip```

**Comment by smcinerney** [comment]
Worse still, `conda update -v --prefix /opt/anaconda3 anaconda` offers to downgrade from 3.7.0 to 3.6.6 (!)

```
The following packages will be DOWNGRADED:

    pyqt:                               5.9.2-py37h655552a_2    --> 5.9.2-py36h655552a_0   
    python:                             3.7.0-hc167b69_0        --> 3.6.6-hc167b69_0       
    twisted:                            18.7.0-py37h1de35cc_1   --> 17.5.0-py36_0          
    xlwt:                               1.3.0-py37_0            --> 1.2.0-py36h5ad1178_0 
```

**Comment by smcinerney** [comment]
I did find [Troubleshooting: `conda update anaconda command does not install the latest version of Anaconda`](https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#conda-update-anaconda-command-does-not-install-the-latest-version-of-anaconda) but the process recommended is insane, it would be easier to uninstall Anaconda and go to pyenv.

**Comment by smcinerney** [comment]
Looks like [the current Anaconda 5.3 graphical installer for MacOS](https://www.anaconda.com/download/#macos) forces Python 3.7.0 
And when you click the link [How to get Python 3.6 or other Python versions](https://docs.anaconda.com/anaconda/faq#how-do-i-get-the-latest-anaconda-with-python-3-5), you get a 404 (SORRY: This page does not exist yet).

**Comment by smcinerney** [comment]
I'm guessing that's supposed to point to https://docs.anaconda.com/anaconda/user-guide/faq/#anaconda-faq-35 , but that just repeats the same brokenness.

**Comment by mingwandroid** [comment]
I am working on this now. The problem is that Python 3.7.1 pins openssl 1.1 while the R packages that use openssl currently pin to 1.0.2. If all goes well it shouldn't take too long to get this sorted out.

Apologies, I dropped this particular ball.

**Comment by msarahan** [comment]
The error messaging on conda around package conflicts and unsatisfiability is a long-standing issue.  Hopefully we can address it soon.  Sorry for the confusion here.

**Comment by smcinerney** [comment]
@mingwandroid : Ok but:

1.  **Please immediately tell me a workaround**, it's not reasonable for Anaconda to stay broken until the code fix is released.
- Can I unpin those R packages? How exactly do I do that? Assume I don't care if I break/uninstall my R install, it's that critical to me. Must I manually pin them to the 'correct' versions?
- Alternatively, how do I install just conda on osx-64 without any R or Python? (why does your website obfuscate and make this impossible, while [insisting that conda and Anaconda are two distinct things](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/)?) 
- FYI, [searching for "pinned" on the website](https://docs.anaconda.com/search/?q=pinned) and [the FAQ](http://docs.anaconda.com/anaconda/user-guide/faq/) is a waste of time. Can you please have that fixed? (Also the FAQ doesn't tell you how to report missing/broken/out-of-date items on the FAQ)
1. The link [How to get Python 3.6 or other Python versions](https://docs.anaconda.com/anaconda/faq#how-do-i-get-the-latest-anaconda-with-python-3-5) on  [the current Anaconda 5.3 graphical installer for MacOS] page is still broken/404. Could someone please have it fixed.
- Also even after reading your github+documentation for hours I was unable to tell where website breakage should be reported? (email? presumably not github? surely not the free Google group community, which isn't organized.)
- Also to prevent breakage, shouldn't you rename that URL anchor '#how-do-i-get-the-latest-anaconda-with-python-3-x'?
- Ditto the old references to [conda FAQ](http://conda.pydata.org/docs/faq.html) are also broken.
- Can anyone at Anaconda please run a basic link-checking tool on their doc site to detect broken links/anchors?
1. The breakage mentioned in my third comment in this thread (`conda update anaconda` offering to DOWNGRADE Python from 3.7.0 to 3.6.6) should never happen. Can you please confirm you've added a unit-test to make sure that never makes it out into a release build again? In general shouldn't it raise an error for `conda update` to attempt to downgrade something major?

Thanks

**Comment by msarahan** [comment]
Do you have a support contract?  If so, please file a ticket with support.  They can prioritize our time.  Otherwise, you're relying on us as volunteers, and you're making unreasonably high demands of us.  Everything you point out needs to be fixed, but so do 5 million other things, many of which are more fundamental to our ability to stay in business and continue providing our volunteer time now and again.

Ray will provide the R packages when he can.  Without a support contract, we thank you for pointing out ways that we can improve, but we offer no promise of when or if any of your recommendations will be fixed.
