### ISSUE TITLE
Upgrading Conda downgrades Python

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7975]
## Current Behavior

Upgrading Conda seems to downgrade from Python 3.7 to Python 3.6 on [AppVeyor]( https://ci.appveyor.com/project/jakirkham/cybuffer/builds/20409406/job/9esef8y8ulugqlmj#L15 ). This in spite of the fact that Conda itself does not change version in the process.

### Steps to Reproduce

Take stock AppVeyor Python 3.7 Miniconda and run `conda update --yes --quiet conda`.

## Expected Behavior

Honestly not sure exactly, but it seems like the downgrade of Python 3.7 to Python 3.6 should not happen.

## Environment Information

This is just using Miniconda Python 3.7 on AppVeyor. AFAIK they just use a stock Miniconda install. So should be able to get any relevant information by inspecting the stock installer. Some details [here]( https://www.appveyor.com/docs/windows-images-software/#miniconda ). Appears to be Python 3.7.0 with Conda 4.5.11. Was using the 64-bit install.

**Comment by nehaljwani** [comment]
I am taking a guess, but that's probably happening because we don't have a cryptography py37 package compliant with openssl 1.1.1 (on Windows) yet.
