### ISSUE TITLE
I have installed yaafe through conda on mac. But when i try to import in a project console it says "ModuleNotFoundError: No module named 'yaafe'"

### ISSUE THREAD

**Issue by anuj0456** [conda/conda#7977]
## Current Behavior
import yaafe
Traceback (most recent call last):

File "ipython-input-7-6f6d9985a3df", line 1, in 
import yaafe

ModuleNotFoundError: No module named 'yaafe'

### Steps to Reproduce

I have created a vir env in which I have installed yaafe
conda install -c conda-forge yaafe

**Comment by msarahan** [comment]
Please post your issue on the conda-forge issue tracker.

https://github.com/conda-forge/yaafe-feedstock
