### ISSUE TITLE
Running Jupyter Notebook with Python 3.6.5 raises error with Python 2.7.

### ISSUE THREAD

**Issue by b5y** [conda/conda#7982]
Since I installed everything using `conda`, I think it is related to this repository.

## Current Behavior

Raising `ValueError                                Traceback (most recent call last)/usr/lib/python2.7/dist-packages/IPython/kernel/zmq/serialize.pyc in unpack_apply_message(bufs, g, copy)` in the beginning with the path to `python 2.7` and `ValueError: unsupported pickle protocol: 3` in the end. 

Supporting Python version for [ELFI](https://github.com/elfi-dev/elfi) is `Python 3.5+`.

Screenshot:
![ipyparallel](https://user-images.githubusercontent.com/1110987/48916967-2bf3d680-ee8d-11e8-912b-f523eb10fe04.png)

### Steps to Reproduce

Notebook available [here](https://github.com/elfi-dev/notebooks/blob/master/parallelization.ipynb).
Fails on the 10 cell after running pickle (somewhere in the library), i.e.:

```
# Let's start using the ipyparallel client
elfi.set_client('ipyparallel')

rej = elfi.Rejection(model, 'd', batch_size=10000, seed=20170530)
%time result = rej.sample(5000, n_sim=int(5e6))  # 5 million simulations
```

## Expected Behavior

As on the [given](https://github.com/elfi-dev/notebooks/blob/master/parallelization.ipynb) notebook.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
% conda info

     active environment : /l/musaevm1/anaconda3/elfi_test
    active env location : /l/musaevm1/anaconda3/elfi_test
            shell level : 1
       user config file : /u/27/musaevm1/unix/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /work/modules/Ubuntu/14.04/amd64/common/anaconda3/latest  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /work/modules/Ubuntu/14.04/amd64/common/anaconda3/latest/pkgs
                          /u/27/musaevm1/unix/.conda/pkgs
       envs directories : /u/27/musaevm1/unix/.conda/envs
                          /work/modules/Ubuntu/14.04/amd64/common/anaconda3/latest/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.6.6 Linux/4.4.0-138-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1814427:70000
             netrc file : None
           offline mode : False
```

**Comment by nehaljwani** [comment]
The fact that `/usr/lib/python2.7/dist-packages/IPython/kernel/zmq/serialize.pyc` is being seen in the output proves that you are not using the correct ipython. It's picking up from your distro instead of your conda environment. 

Please share output for `env | grep -i python` and also `which ipython`, `which jupyter`

**Comment by b5y** [comment]
Well, it raises only in this notebook and it is first time since I have been using my working computer.

I run `jupyter notebook` after activating `conda env` under `Python 3.6.5`. This is the output in jupyter notebook.

![image](https://user-images.githubusercontent.com/1110987/48980263-546b1300-f0cf-11e8-8646-f50bf6bc7c7c.png)

**Comment by nehaljwani** [comment]
@b5y Please also check the output for: `which ipyparallel`

**Comment by b5y** [comment]
Strange as it may sound, rebooting the system solves this problem.
Thank you for help!
