### ISSUE TITLE
DOCS: Cheatsheet has `source activate` instead of `conda activate`

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#7985]
The official documentation points to this cheatsheet:

https://github.com/conda/conda/blob/master/docs/source/user-guide/conda-cheatsheet.pdf

which still tells the user to use `source activate <env_name>` instead of `conda activate <env_name>`.

I was checking if the old way still works with conda 4.5.11 but that doesn't seem to be the case.

**Comment by michaelaye** [comment]
Correction: The old "source activate" seems to work in zsh and bash, but not with fish.

**Comment by chenghlee** [comment]
Fixed as of the latest version of the cheat sheet (commit a1c7c52f8ace66860629b950240dd689a3c062b0).
