### ISSUE TITLE
Fails to create a new conda environment (e.g. cntk-py35) using Windows command shell

### ISSUE THREAD

**Issue by haricntk** [conda/conda#7987]
HI, 
I am setting CNTK environment manually, conda environment fails to create,

On executing below command i am getting following error:
conda env update --file D:\repos\cntk\scripts\install\windows\conda-windows-cntk-py35-environment.yml --name cntk-py35

D:\local\Anaconda3\Scripts>conda env update --file D:\repos\cntk\scripts\install\windows\conda-windows-cntk-py35-environment.yml --name cntk-py35
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\local\Anaconda3\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "D:\local\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "D:\local\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "D:\local\Anaconda3\lib\site-packages\conda_env\cli\main_update.py", line 112, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
  File "D:\local\Anaconda3\lib\site-packages\conda_env\installers\pip.py", line 9, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

D:\local\Anaconda3\Scripts>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : D:\local\Anaconda3  (writable)
  default environment : D:\local\Anaconda3
     envs directories : D:\local\Anaconda3\envs
        package cache : D:\local\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by nehaljwani** [comment]
Sorry, conda 4.1.x is no longer supported. Please update conda to the latest version.
