### ISSUE TITLE
conda doesn't resume download after network disconnection.

### ISSUE THREAD

**Issue by hargup** [conda/conda#800]
conda doesn't resume download after network disconnection. If the program is interrupted for some reason conda downloads all the downloaded files again. This is particularly problematic in many places in India where the network connections are usually slow and unreliable.

**Comment by CTimmerman** [comment]
Requests does support easy resume, see https://gist.github.com/CTimmerman/ccf884f8c8dcc284588f1811ed99be6c

You might want to use "If-Range" with a "Last-Modified" header in case the resume happens after a server update: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range

**Comment by Husnainakmal5** [comment]
Same problem i tried to download packages manually and extract in pkgs folder but not working
