### ISSUE TITLE
conda env create should copy yml-defined channels  to enabled channels for the new env

### ISSUE THREAD

**Issue by pgunn** [conda/conda#8001]
Right now if you have an alternate set of channels you want to use for a given environment (e.g. environment cftest is to test conda-forge and must have conda-forge enabled and defaults not enabled), conda env create will respect the settings in the yaml for initial build of the environment but doesn't configure the environment to keep those channels going forward.

This feature request is to have the creation preferences carry forward so if someone is working in the env and wants to add a package it doesn't miss out on either custom channels they want or accidentally pull in from channels they don't.

**Comment by pgunn** [comment]
I just noticed that conda will also not respect removing things from a channel's config if the parent config has the channel you don't want to use in it; you'd need to remove it entirely from your condarc. This should probably also be fixed.

**Comment by nehaljwani** [comment]
If you look at the output for `conda config --help`, you will see:
```
  --env                 Write to the active conda environment .condarc file
                        (/tmp/p). If no environment is active, write to the
                        user config file (/Users/nwani/.condarc).
```
Does using the --env flag not solve the use case for you?

**Comment by pgunn** [comment]
This would in theory just fix the second issue, but it doesn't do that; I believe conda merges config items that are list-type with the default environment's version of that list config item, causing it to still possibly install things from channels that are not in scope.
