### ISSUE TITLE
PowerShell Support

### ISSUE THREAD

**Issue by darkn3rd** [conda/conda#8005]
### SUMMARY

Currently, there's only BATCH command shell support for Windows, but these days, PowerShell is gestalt for many tools.  It would be nice to have an `activate.ps1`.  

Workaround is to require people to use command shell (`CMD.EXE`) to setup appropriate env vars, and then launch powershell from that.  

It would also be nice to have the env vars global available for user env vars (Windows has system env vars and user env vars), so that the tool is available all times when a user logs in.

**Use Case**: Looking for easy way to juggle python versions on Windows in PowerShell for use with many tools in that space, like `node-gyp`, which requires python2, where other cases wish to use python3.

### STEPS

Install MiniConda from Powershell and try to use it.

```PowerShell
Set-ExecutionPolicy Bypass -Scope Process -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y miniconda
C:\ProgramData\Miniconda2\Scripts\activate.bat C:\ProgramData\Miniconda2
conda --version
```

Chocolately not required to reproduce this, just put here for convenience, stream-line the steps.

### ACTUAL RESULTS

```
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ conda --version
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### EXPECTED RESULTS

```
conda 4.3.21
```

### WORKAROUND

In order to get access to the tools, you much only launch `CMD.EXE`, and then from there load environment, then run PowerShell.

```
cmd
C:\ProgramData\Miniconda2\Scripts\activate.bat C:\ProgramData\Miniconda2
powershell
conda --version
```

**Comment by letmaik** [comment]
@kalefranz I'm at 4.7.10 and although the Anaconda Powershell Prompt shortcut works, there is still no activate.ps1 that can be used from scripts to use conda when it hasn't been put into the environment before. Or am I missing something?
