### ISSUE TITLE
miniconda error

### ISSUE THREAD

**Issue by shaanvet** [conda/conda#8007]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by neunzehnachtneun** [comment]
This doesnt seem to be a conda error, but the last line indicates, that your drive 'opt' maybe is full. So you should check that first.

**Comment by nehaljwani** [comment]
Closing as this is not a problem with Conda itself.
