### ISSUE TITLE
conda config --add channels should check that the url exists

### ISSUE THREAD

**Issue by srossross** [conda/conda#801]
From: http://code.mumak.net/2014/07/conda-and-binstar-initial-experiences.html

```
conda config --add channels https://binstar.org/auto
```
Should be:
```
conda config --add channels https://conda.binstar.org/auto
```

There are two things we can do to improve this user experience:
 1. conda could check that https://binstar.org/auto is a valid url. 
 1. conda could set its own [User-Agent](http://en.wikipedia.org/wiki/User_agent) header so that binstar can also raise an appropriate error if the url is not a conda repo.

cc @teoliphant @ilanschnell @asmeurer

**Comment by srossross** [comment]
@ilanschnell this is just a reminder about this feature.

**Comment by kalefranz** [comment]
Given discussion above, progress on `User-Agent`, and discussion in #1233, I'm going to close this issue.  I don't want to make http calls for `conda config` commands.  The combination of #3708 and #3710 should resolve everything we need moving forward.
