### ISSUE TITLE
PosixActivator on Windows

### ISSUE THREAD

**Issue by hadim** [conda/conda#8023]
On Windows using conda 4.6 beta:

```bash
 $ conda info

     active environment : base
    active env location : C:\Users\hadim\Miniconda3
            shell level : 1
       user config file : C:\Users\hadim\.condarc
 populated config files : C:\Users\hadim\.condarc
          conda version : 4.6.0b1
    conda-build version : 3.17.1
         python version : 3.7.1.final.0
       base environment : C:\Users\hadim\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\hadim\Miniconda3\pkgs
                          C:\Users\hadim\.conda\pkgs
                          C:\Users\hadim\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\hadim\Miniconda3\envs
                          C:\Users\hadim\.conda\envs
                          C:\Users\hadim\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.0b1 requests/2.20.1 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

I use Git Bash on Windows instead of Anaconda Prompt. WHen I activate an env , the `PATH` variable is correctly set but the activation scripst are not executed. To reproduce the issue on Git Bash, do:

```bash
$ conda create -n java openjdk
$ conda activate java
$ java -version
# Should return the correct java path
$ echo $JAVA_HOME
# Should NOT return the correct JAVA_HOME path
# since the activation script has not been executed.
```

I checked an I confirm `activate.PosixActivator` has been correctly selected, as excepted. The issue is the script extension is set to `.sh` while only `.bat` activation scripts are copied in the env prefix: https://github.com/conda/conda/blob/4.6.0b1/conda/activate.py#L611

The only solution I see is to copy all activation scripts being `.bat` or `.sh` to `PREFIX` during installation. 

Can someone comment?

**Comment by mingwandroid** [comment]
You cannot change bash's environment via cmd.exe so there's no choice but to use the Shell scripts here AFAICT.

Thank you for raising this!

**Comment by hadim** [comment]
Do you think copying all `.sh` and `.bat` scripts during installation could be a solution?

**Comment by mingwandroid** [comment]
Yes, I do. We also need to modify env vars to posix form. PRs very welcome.

**Comment by hadim** [comment]
I didn't realize it was the recipe job to copy activation scripts. So maybe it's just a matter of tweaking the recipe: https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/bld.bat#L26

Then since the env contains `.sh` and `.bat` scripts, the correct ones will be selected during activation? Am I correct or missing something?

**Comment by mingwandroid** [comment]
Try it? Need to make sure that the bash shell never sees Windows style paths in env vars too, I suspect. There may be code in place for that. We have similar concerns in conda-build too when using shell scripts for multiple output recipes so we should try to generalize any such code and have it live in conda.

**Comment by mingwandroid** [comment]
This also ties in with noarch packages I think.

**Comment by msarahan** [comment]
Yep, recipe maintainer responsibility for sure.  Just a question of whether there's anything that can be done to make that simpler.  The powershell approach is really nice because of how it doesn't require additional recipe modification.

**Comment by hadim** [comment]
Ok. Note that I also had to tweak the activation script itself: https://github.com/conda-forge/openjdk-feedstock/pull/49/files#diff-023b12cba01f01093d3c69131ce57aaaR2

I'll let this open then. For the `openjdk` package, I think my workaround is ok for the moment.

**Comment by mingwandroid** [comment]
I need to figure out how cmd.exe changes the bash env.. it should not work from what I know! Weird..

**Comment by mingwandroid** [comment]
> if [[ $(uname -s) == CYGWIN* ]];

`uname -s` doesn't return this for msys2 though?!

**Comment by hadim** [comment]
ahah my bad, I just copied/pasted it from SO. It returns: `MINGW64_NT-10.0` for me.

**Comment by msarahan** [comment]
Yeah, that uname thing is very frustrating on Windows.  There are way too many potential values it can take, from my experience.

**Comment by hadim** [comment]
I have only chosen the most obvious one for me but I am open to alternatives.

**Comment by mingwandroid** [comment]
It depends on whether you launch an msys2 shell or a mingw shell.

Best thing to add is: `or [[ $(uname -s) =~ M* ]]`

I'm confused why this change worked for you though @hadim! Did you test on cygwin?

**Comment by mingwandroid** [comment]
Git for Windows does use a mingw shell though.

**Comment by mingwandroid** [comment]
Definitely good to support all variants here including cygwin.. I recommend:

> 
if [[ $(uname -s) == CYGWIN* ]] || [[ $(uname -s =~ M* ]];

Cheers!

**Comment by hadim** [comment]
The PR should be in good shape now: https://github.com/conda-forge/openjdk-feedstock/pull/49

@mingwandroid I only tested with Git Bash and Java is finally fully working (I have been able to initialize and use pyjnius with it).

**Comment by hadim** [comment]
@mingwandroid you were right, detecting in Bash if we are running Linux, OSX or Windows is too tricky. I decided to use different bash scripts to avoid any failures: https://github.com/conda-forge/openjdk-feedstock/pull/50

**Comment by kalefranz** [comment]
The best / first principles solution, but long-term, here is https://github.com/conda/conda/issues/6820

**Comment by kalefranz** [comment]
Closing this issue now since it was resolved with a packaging change, and is now linked to #6820.
