### ISSUE TITLE
GraphLab Create Launcher Installation Failed

### ISSUE THREAD

**Issue by thekaggler** [conda/conda#8031]
## Current Behavior

I got the error "We encountered an error that prevented us from installing." while installing the "GraphLab Create Launcher"

### Steps to Reproduce

```
I tried to install the 'GraphLab Create Launcher version 3.0.1' after entering my registered email-id and
License key(Valid one: '592E-D824-7322-1017-5186-128E-335E-5435') 
[launcher-install-log.txt](https://github.com/conda/conda/files/2668690/launcher-install-log.txt)

```

## Expected Behavior

Not sure. May be the current installation of python 2.7x has conflicts with my existing python 3.x

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
conda info:
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\NEO\Anaconda2  (writable)
  default environment : C:\Users\NEO\Anaconda2
     envs directories : C:\Users\NEO\Anaconda2\envs
        package cache : C:\Users\NEO\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\NEO\.condarc
    is foreign system : False

# conda environments:
#
root                  *  C:\Users\NEO\Anaconda2

sys.version: 2.7.11 |Anaconda 4.0.0 (64-bit)| (defaul...
sys.prefix: C:\Users\NEO\Anaconda2
sys.executable: C:\Users\NEO\Anaconda2\python.exe
conda location: C:\Users\NEO\Anaconda2\lib\site-packages\conda
conda-build: C:\Users\NEO\Anaconda2\Scripts\conda-build.exe
conda-convert: C:\Users\NEO\Anaconda2\Scripts\conda-convert.exe
conda-develop: C:\Users\NEO\Anaconda2\Scripts\conda-develop.exe
conda-env: C:\Users\NEO\Anaconda2\Scripts\conda-env.exe
conda-index: C:\Users\NEO\Anaconda2\Scripts\conda-index.exe
conda-inspect: C:\Users\NEO\Anaconda2\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\NEO\Anaconda2\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\NEO\Anaconda2\Scripts\conda-pipbuild.exe
conda-server: C:\Users\NEO\Anaconda2\Scripts\conda-server.exe
conda-sign: C:\Users\NEO\Anaconda2\Scripts\conda-sign.exe
conda-skeleton: C:\Users\NEO\Anaconda2\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\NEO\Anaconda2\Library\bin;C:\Users\NEO\Anaconda2;C:\Users\NEO\Anaconda2\Scripts;C:\Program Files\Microsoft MPI\Bin\;C:\cudnn-9.0-windows10-x64-v7\cuda\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\NEO\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;;D:\Program Files (x86);C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Users\NEO\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\NEO\AppData\Local\Programs\Python\Python36-32\;C:\Users\NEO\AppData\Local\Microsoft\WindowsApps;
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

===================
There was a problem updating the conda package.  Restart GraphLab Create Launcher.

Unable to update conda:
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Users\NEO\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vc-9                       |                0          705 B
    python-2.7.13              |                1        23.8 MB
    conda-4.0.8                |           py27_0         229 KB
    ------------------------------------------------------------
                                           Total:        24.1 MB

The following NEW packages will be INSTALLED:

    vc:     9-0         

The following packages will be UPDATED:

    conda:  4.0.5-py27_0 --> 4.0.8-py27_0
    python: 2.7.11-4     --> 2.7.13-1    

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "C:\Users\NEO\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "C:\Users\NEO\Anaconda2\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\NEO\Anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))

  

Process completed with exit code -1
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
conda list:
Error: Error: environment does not exist: C:\Users\NEO\Anaconda2\envs\gl-env
#
# Use 'conda create' to create an environment before listing its packages.

pip version:
pip 8.1.1 from C:\Users\NEO\Anaconda2\lib\site-packages (python 2.7)


pip list:
alabaster (0.7.7)
anaconda-client (1.4.0)
anaconda-navigator (1.1.0)
argcomplete (1.0.0)
astropy (1.1.2)
Babel (2.2.0)
backports-abc (0.4)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.4.1)
bitarray (0.8.1)
blaze (0.9.1)
bokeh (0.11.1)
boto (2.39.0)
Bottleneck (1.0.0)
cdecimal (2.3)
cffi (1.5.2)
chest (0.2.3)
cloudpickle (0.1.1)
clyent (1.2.1)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.0.5)
conda-build (1.20.0)
conda-env (2.4.5)
conda-manager (0.3.1)
configobj (5.0.6)
cryptography (1.3)
cycler (0.10.0)
Cython (0.23.4)
cytoolz (0.7.5)
dask (0.8.1)
datashape (0.5.1)
decorator (4.0.9)
dill (0.2.4)
docutils (0.12)
enum34 (1.1.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.10.1)
Flask-Cors (2.1.2)
funcsigs (0.4)
futures (3.0.3)
gevent (1.1.0)
greenlet (0.4.9)
grin (1.2.1)
h5py (2.5.0)
HeapDict (1.0.0)
idna (2.0)
ipaddress (1.0.14)
ipykernel (4.3.1)
ipython (4.1.2)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
llvmlite (0.9.0)
locket (0.2.0)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
menuinst (1.3.2)
mistune (0.7.2)
mpmath (0.19)
multipledispatch (0.4.8)
nbconvert (4.1.0)
nbformat (4.0.1)
networkx (1.11)
nltk (3.2)
nose (1.3.7)
notebook (4.1.0)
numba (0.24.0)
numexpr (2.5)
numpy (1.10.4)
odo (0.4.2)
openpyxl (2.3.2)
pandas (0.18.0)
partd (0.3.2)
path.py (0.0.0)
patsy (0.4.0)
pep8 (1.7.0)
pickleshare (0.5)
Pillow (3.1.1)
pip (8.1.1)
ply (3.8)
psutil (4.1.0)
py (1.4.31)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflakes (1.1.0)
Pygments (2.1.1)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyreadline (2.1)
pytest (2.8.5)
python-dateutil (2.5.1)
pytz (2016.2)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
QtAwesome (0.3.2)
qtconsole (4.2.0)
QtPy (1.0)
requests (2.9.1)
rope (0.9.4)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.17.0)
setuptools (20.3)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.1)
sphinx (1.3.5)
sphinx-rtd-theme (0.1.9)
spyder (2.3.8)
SQLAlchemy (1.0.12)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.7.4)
tornado (4.3)
traitlets (4.2.1)
unicodecsv (0.14.1)
Werkzeug (0.11.4)
wheel (0.29.0)
xlrd (0.9.4)
XlsxWriter (0.8.4)
xlwings (0.7.0)
xlwt (1.0.0)

```
</p></details>

**Comment by shyamdaraboina** [comment]
Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 63, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\darabois\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Users\\darabois\\AppData\\Local\\Continuum\\Anaconda2\\pkgs\\python-2.7.13-1\\DLLs\\_hashlib.pyd'

**Comment by jjhelmus** [comment]
You are using conda 4.0.5.  That version was released in March 2016 and is no longer supported.  Can you upgrade or install a newer version of conda and try the process again.

**Comment by Naina258** [comment]
Hi,

I am getting the following error while installing GraphLab Creator launcher.

GraphLab Create Launcher, version 3.0.1
Windows_NT (win32) release: 6.1.7601
CPUs: 4 (x64)
Total Memory: 3131228160
Installation process initialized.

=== System State ===

Current time: 2020-05-09T11:15:31.733Z

{
  "PATH": "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\lenovo\\Anaconda2;C:\\Users\\lenovo\\Anaconda2\\Scripts;C:\\Users\\lenovo\\Anaconda2\\Library\\bin;C:\\Users\\lenovo\\Anaconda3;C:\\Users\\lenovo\\Anaconda3\\Scripts;C:\\Users\\lenovo\\Anaconda3\\Library\\bin;C:\\;.;;.;",
  "SHELL": "",
  "HOME": "",
  "USERPROFILE": "C:\\Users\\lenovo",
  "TEMP": "C:\\Users\\lenovo\\AppData\\Local\\Temp",
  "undefined": ""
}

Local settings:
{
  "licenseEmail": "nageswaravallurupalli@gmail.com",
  "licenseKey": "F10A-19F7-CFD6-0BE8-2DA6-4AC1-80A2-95DC",
  "anacondaPath": "C:\\Users\\lenovo\\Anaconda3"
}

isCondaInEnvironment: true
isPipInEnvironment: true
Selected Anaconda path is C:\Users\lenovo\Anaconda3
isCondaAvailable("C:\Users\lenovo\Anaconda3"): true

conda info:
Current conda install:

             platform : win-64
        conda version : 4.0.8
  conda-build version : 2.0.2
       python version : 3.5.6.final.0
     requests version : 2.11.1
     root environment : C:\Users\lenovo\Anaconda3  (writable)
  default environment : C:\Users\lenovo\Anaconda3
     envs directories : C:\Users\lenovo\Anaconda3\envs
        package cache : C:\Users\lenovo\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:
#
py3-TF2.0                C:\Users\lenovo\Anaconda3\envs\py3-TF2.0
py3_TF2.0                C:\Users\lenovo\Anaconda3\envs\py3_TF2.0
root                  *  C:\Users\lenovo\Anaconda3

sys.version: 3.5.6 |Anaconda custom (64-bit)| (defaul...
sys.prefix: C:\Users\lenovo\Anaconda3
sys.executable: C:\Users\lenovo\Anaconda3\python.exe
conda location: C:\Users\lenovo\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\lenovo\Anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\lenovo\Anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\lenovo\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\lenovo\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\lenovo\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\lenovo\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\lenovo\Anaconda3\Scripts\conda-metapackage.exe
conda-render: C:\Users\lenovo\Anaconda3\Scripts\conda-render.exe
conda-server: C:\Users\lenovo\Anaconda3\Scripts\conda-server.exe
conda-sign: C:\Users\lenovo\Anaconda3\Scripts\conda-sign.exe
conda-skeleton: C:\Users\lenovo\Anaconda3\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\lenovo\Anaconda2;C:\Users\lenovo\Anaconda2\Scripts;C:\Users\lenovo\Anaconda2\Library\bin;C:\Users\lenovo\Anaconda3;C:\Users\lenovo\Anaconda3\Scripts;C:\Users\lenovo\Anaconda3\Library\bin;C:\;.;;.;
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\Users\lenovo\.continuum
    C:\Users\lenovo\Anaconda3\licenses
    C:\Users\lenovo\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

===================

Obtained dependency info: {
  "glc": {
    "version": "2.1",
    "url": "https://static.turi.com/products/graphlab-create/2.1/python2.7/windows/GraphLab_Create-2.1-cp27-none-win_amd64.whl",
    "filename": "GraphLab_Create-2.1-cp27-none-win_amd64.whl",
    "md5": "cac379861d465c9bd777e0bbca3f1e5c"
  },
  "anaconda": {
    "version": "4.0.0",
    "filename": "Anaconda2-4.0.0-Windows-x86_64.exe",
    "url": "https://static.turi.com/products/graphlab-create-launcher/resources/anaconda/Anaconda2-4.0.0-Windows-x86_64.exe",
    "md5": "6b2ad997c42fbf58bb1b54baa5619e4f"
  }
}

Anaconda installation detected. Skipping download.

Starting GraphLab Create 2.1 retrieval.

Anaconda installation detected. Skipping installation.

PATH environment variable updated.


Did not find a broken "gl-env" environment.

Creating conda environment "gl-env".
Fetching package metadata: 
Solving package specifications: 
Using Anaconda API: https://api.anaconda.org

Error:  Dependencies missing in current win-64 channels: 
  - anaconda 4.0|4.0.0* -> scipy 0.17.0 np110py35_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> numpy 1.10.4 py27_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> scipy 0.17.0 np110py34_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py27_2 -> numexpr 2.5* -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py35_2 -> numexpr 2.5* -> numpy 1.11* -> blas * mkl
  - anaconda 4.0|4.0.0* -> numexpr 2.5 np110py27_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> scikit-learn 0.17.1 np110py34_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> numpy 1.10.4 py34_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> numexpr 2.5 np110py35_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> numexpr 2.5 np110py34_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> scipy 0.17.0 np110py27_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> numpy 1.10.4 py35_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> scikit-learn 0.17.1 np110py35_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py27_2 -> numexpr 2.5* -> numpy 1.11* -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py34_2 -> numexpr 2.5* -> numpy 1.11* -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py34_2 -> numexpr 2.5* -> blas * mkl
  - anaconda 4.0|4.0.0* -> scikit-learn 0.17.1 np110py27_0 -> blas * mkl
  - anaconda 4.0|4.0.0* -> pytables 3.2.2 np110py35_2 -> numexpr 2.5* -> blas * mkl

You can search for this package on anaconda.org with

    anaconda search -t conda blas * mkl


Capturing final system state:

=== Packages in GraphLab Create Environment ===

conda list:
Error: Error: environment does not exist: C:\Users\lenovo\Anaconda3\envs\gl-env
#
# Use 'conda create' to create an environment before listing its packages.

pip version:
pip 20.1 from c:\users\lenovo\anaconda3\lib\site-packages\pip (python 3.5)


pip list:
Package                            Version
---------------------------------- ------------
absl-py                            0.4.1
alabaster                          0.7.9
anaconda-clean                     1.0
anaconda-client                    1.5.1
anaconda-navigator                 1.3.1
appdirs                            1.4.3
argcomplete                        1.0.0
astor                              0.7.1
astroid                            1.4.7
astropy                            2.0.8
Babel                              2.3.4
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.5.1
bitarray                           0.8.1
blaze                              0.10.1
bokeh                              0.12.2
boto                               2.42.0
Bottleneck                         1.2.1
cffi                               1.7.0
chest                              0.2.3
click                              6.6
cloudpickle                        0.2.1
clyent                             1.2.2
colorama                           0.3.7
comtypes                           1.1.2
conda                              4.0.8
conda-build                        2.0.2
conda-env                          2.4.5
configobj                          5.0.6
contextlib2                        0.5.3
cryptography                       1.5
cycler                             0.10.0
Cython                             0.24.1
cytoolz                            0.8.0
dask                               0.11.0
datashape                          0.5.2
decorator                          4.0.10
dill                               0.2.5
distlib                            0.3.0
docutils                           0.12
dynd                               c328ab7
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           2.0.6
Flask                              0.11.1
Flask-Cors                         2.1.2
gast                               0.3.3
gevent                             1.1.2
greenlet                           0.4.10
grpcio                             1.12.1
h5py                               2.7.0
HeapDict                           1.0.0
idna                               2.1
imageio                            2.8.0
imagesize                          0.7.1
importlib-metadata                 1.6.0
importlib-resources                1.5.0
ipykernel                          4.5.0
ipython                            5.1.0
ipython-genutils                   0.1.0
ipywidgets                         5.2.2
itsdangerous                       0.24
jdcal                              1.2
jedi                               0.9.0
Jinja2                             2.8
joblib                             0.14.1
jsonschema                         2.5.1
jupyter                            1.0.0
jupyter-client                     4.4.0
jupyter-console                    5.0.0
jupyter-core                       4.2.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.2.1
llvmlite                           0.24.0
locket                             0.2.0
lxml                               3.6.4
Markdown                           2.6.11
MarkupSafe                         0.23
matplotlib                         2.2.2
menuinst                           1.4.1
mistune                            0.7.3
mkl-fft                            1.0.6
mkl-random                         1.0.1
mpmath                             0.19
multipledispatch                   0.4.8
nb-anacondacloud                   1.2.0
nb-conda                           2.0.0
nb-conda-kernels                   2.0.0
nbconvert                          4.2.0
nbformat                           4.1.0
nbpresent                          3.0.2
networkx                           1.11
nltk                               3.2.1
nose                               1.3.7
notebook                           4.2.3
numba                              0.39.0
numexpr                            2.6.8
numpy                              1.13.3
odo                                0.5.0
olefile                            0.46
openpyxl                           2.3.2
pandas                             0.23.4
partd                              0.3.6
path.py                            0.0.0
pathlib2                           2.1.0
patsy                              0.4.1
pep8                               1.7.0
pickleshare                        0.7.4
Pillow                             5.2.0
pip                                20.1
pkginfo                            1.3.2
ply                                3.9
prompt-toolkit                     1.0.3
protobuf                           3.6.0
psutil                             4.3.1
py                                 1.4.31
pyasn1                             0.1.9
pycosat                            0.6.3
pycparser                          2.14
pycrypto                           2.6.1
pycurl                             7.43.0.2
pyflakes                           1.3.0
Pygments                           2.1.3
pylint                             1.5.4
pyOpenSSL                          16.2.0
pyparsing                          2.1.4
pytest                             2.9.2
python-dateutil                    2.5.3
pytz                               2016.6.1
PyWavelets                         1.0.0
pywin32                            220
PyYAML                             3.12
pyzmq                              15.4.0
QtAwesome                          0.3.3
qtconsole                          4.2.1
QtPy                               1.1.2
requests                           2.11.1
rope-py3k                          0.9.4.post1
ruamel-yaml                        -VERSION
scikit-image                       0.13.1
scikit-learn                       0.22.2.post1
scipy                              1.1.0
seaborn                            0.8
setuptools                         27.2.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.10.0
snowballstemmer                    1.2.1
sockjs-tornado                     1.0.3
sphinx                             1.4.6
spyder                             3.0.0
SQLAlchemy                         1.0.13
statsmodels                        0.9.0
sympy                              1.0
tables                             3.2.2
tensorboard                        1.10.0
tensorflow                         1.10.0
termcolor                          1.1.0
toolz                              0.8.0
tornado                            4.4.1
traitlets                          4.3.0
unicodecsv                         0.14.1
wcwidth                            0.1.7
Werkzeug                           0.11.11
wheel                              0.29.0
widgetsnbextension                 1.2.6
win-unicode-console                0.5
wrapt                              1.10.6
xlrd                               1.0.0
XlsxWriter                         0.9.3
xlwings                            0.10.0
xlwt                               1.1.2
zipp                               1.2.0

====================================

=== System State ===

Current time: 2020-05-09T11:16:03.042Z

{
  "PATH": "C:\\Users\\lenovo\\Anaconda3;C:\\Users\\lenovo\\Anaconda3\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\lenovo\\Anaconda2;C:\\Users\\lenovo\\Anaconda2\\Scripts;C:\\Users\\lenovo\\Anaconda2\\Library\\bin;C:\\Users\\lenovo\\Anaconda3;C:\\Users\\lenovo\\Anaconda3\\Scripts;C:\\Users\\lenovo\\Anaconda3\\Library\\bin;C:\\;.;;.;",
  "SHELL": "",
  "HOME": "",
  "USERPROFILE": "C:\\Users\\lenovo",
  "TEMP": "C:\\Users\\lenovo\\AppData\\Local\\Temp",
  "undefined": ""
}

Local settings:
{
  "licenseEmail": "nageswaravallurupalli@gmail.com",
  "licenseKey": "F10A-19F7-CFD6-0BE8-2DA6-4AC1-80A2-95DC",
  "anacondaPath": "C:\\Users\\lenovo\\Anaconda3"
}

isCondaInEnvironment: true
isPipInEnvironment: true
Selected Anaconda path is C:\Users\lenovo\Anaconda3
isCondaAvailable("C:\Users\lenovo\Anaconda3"): true

conda info:
Current conda install:

             platform : win-64
        conda version : 4.0.8
  conda-build version : 2.0.2
       python version : 3.5.6.final.0
     requests version : 2.11.1
     root environment : C:\Users\lenovo\Anaconda3  (writable)
  default environment : C:\Users\lenovo\Anaconda3
     envs directories : C:\Users\lenovo\Anaconda3\envs
        package cache : C:\Users\lenovo\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:
#
py3-TF2.0                C:\Users\lenovo\Anaconda3\envs\py3-TF2.0
py3_TF2.0                C:\Users\lenovo\Anaconda3\envs\py3_TF2.0
root                  *  C:\Users\lenovo\Anaconda3

sys.version: 3.5.6 |Anaconda custom (64-bit)| (defaul...
sys.prefix: C:\Users\lenovo\Anaconda3
sys.executable: C:\Users\lenovo\Anaconda3\python.exe
conda location: C:\Users\lenovo\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\lenovo\Anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\lenovo\Anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\lenovo\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\lenovo\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\lenovo\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\lenovo\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\lenovo\Anaconda3\Scripts\conda-metapackage.exe
conda-render: C:\Users\lenovo\Anaconda3\Scripts\conda-render.exe
conda-server: C:\Users\lenovo\Anaconda3\Scripts\conda-server.exe
conda-sign: C:\Users\lenovo\Anaconda3\Scripts\conda-sign.exe
conda-skeleton: C:\Users\lenovo\Anaconda3\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\lenovo\Anaconda3;C:\Users\lenovo\Anaconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\lenovo\Anaconda2;C:\Users\lenovo\Anaconda2\Scripts;C:\Users\lenovo\Anaconda2\Library\bin;C:\Users\lenovo\Anaconda3;C:\Users\lenovo\Anaconda3\Scripts;C:\Users\lenovo\Anaconda3\Library\bin;C:\;.;;.;
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\Users\lenovo\.continuum
    C:\Users\lenovo\Anaconda3\licenses
    C:\Users\lenovo\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

===================
There was a problem creating the "gl-env" conda environment.  Restart GraphLab Create Launcher.

Process completed with exit code -1
