### ISSUE TITLE
Fails to install under NixOS 18.09, despite Python 3.7 being in PATH

### ISSUE THREAD

**Issue by fusion809** [conda/conda#8036]
## Current Behaviour
The Miniconda3 installer script fails at the install stage with the error (I have included a few extra lines for context):

```bash
Do you accept the license terms? [yes|no]
[no] >>> \
Please answer 'yes' or 'no':'
>>> yes

Miniconda3 will now be installed into this location:
/home/fusion809/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/fusion809/miniconda3] >>> 
PREFIX=/home/fusion809/miniconda3
installing: python-3.7.0-hc3d631a_0 ...
./Miniconda3-latest-Linux-x86_64.sh: line 370: /home/fusion809/miniconda3/pkgs/python-3.7.0-hc3d631a_0/bin/python: No such file or directory
```

### Steps to Reproduce
1. Install NixOS 18.09, with this configuration.nix file: https://github.com/fusion809/NixOS-configs/blob/18.09/configuration.nix. 

2. Install Python 3.7.1 with:

```bash
nix-env -f '<nixos-unstable>' -iA python3-3.7.1
```

3. Run Miniconda3 install script, downloaded from:

* https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

4. Agree to license terms and install to ~/miniconda3.

and Voila, you should see the aforementioned error.

## Expected Behaviour
Miniconda3 to install properly. 

## Environment Information

(Can't give you the output of Conda as it failed to install). If it helps here is the output of neofetch:

![screenshot_20181215_191352](https://user-images.githubusercontent.com/4717341/50041248-95868f80-009d-11e9-80b6-59887fadd8f2.png)

**Comment by fusion809** [comment]
If you're unfamiliar with NixOS it places binaries in non-FHS locations, although python3.7 is in PATH.

**Comment by mbargull** [comment]
Hi @fusion809, is this still an issue with newer Miniconda installers?

**Comment by fusion809** [comment]
I don't really use it anymore. So I'll gladly just close this issue.
