### ISSUE TITLE
How to change the path of user config file?

### ISSUE THREAD

**Issue by jhhuang96** [conda/conda#8047]
active environment : base
    active env location : D:\Program Files\Anaconda3
            shell level : 1
       user config file : D:\Cadence\Cadence\SPB_Data\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : D:\Program Files\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Program Files\Anaconda3\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
       envs directories : D:\Program Files\Anaconda3\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
                          D:\Cadence\Cadence\SPB_Data\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
----------------------------------------------------------------------------------------------------------------
I want to change user config file's path. Now it is in ' D:\Cadence\Cadence\SPB_Data\.condarc'. I don't know why it appears in Cadence folder. And I see envs directories also contains 'D:\Cadence\Cadence\SPB_Data\.conda\envs'. I want to change and move these files in Cadence to new file path. Thanks!

**Comment by jhhuang96** [comment]
I change my environment variable in win10. It worked!

**Comment by JaceyPenny** [comment]
@jhhuang96 what environment variable?
