### ISSUE TITLE
from keras.models import Sequential Using TensorFlow backend.  Kernel died, restarting

### ISSUE THREAD

**Issue by manoharsham** [conda/conda#8052]
## Current Behavior

import keras
Using TensorFlow backend.

Kernel died, restarting

### Steps to Reproduce

```

```

## Expected Behavior

No error
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

active environment : base
    active env location : C:\Program Files\Anaconda3
            shell level : 1
       user config file : C:\Users\abc\.condarc
 populated config files : C:\Users\abc\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.5.6.final.0
       base environment : C:\Program Files\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Program Files\Anaconda3\pkgs
                          C:\Users\abc\AppData\Local\conda\conda\pkgs
       envs directories : C:\Program Files\Anaconda3\envs
                          C:\Users\abc\AppData\Local\conda\conda\envs
                          C:\Users\abc\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.5.6 Windows/10 Windows/10.0.15063
          administrator : True
             netrc file : None
           offline mode : False
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

channels:
  - defaults
ssl_verify: True
```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by Coerchan** [comment]
is that any approach can solve this?
