### ISSUE TITLE
Conda installation of scitools failed

### ISSUE THREAD

**Issue by gjayaraman** [conda/conda#806]
$ conda install -c asmeurer scitools

Fetching packages ...
matplotlib-1.3 100% |#############################################################################| Time: 0:06:33  90.96 kB/s
numpy-1.7.1-py 100% |#############################################################################| Time: 0:00:49  60.26 kB/s
pyparsing-1.5. 100% |#############################################################################| Time: 0:00:01  52.64 kB/s
python-2.7.8-0 100% |#############################################################################| Time: 0:05:06  33.68 kB/s
pytz-2014.4-py 100% |#############################################################################| Time: 0:00:05  33.69 kB/s
scitools-0.8-n 100% |#############################################################################| Time: 0:00:11  51.81 kB/s
six-1.7.3-py27 100% |#############################################################################| Time: 0:00:01  14.72 kB/s
Extracting packages ...
[      COMPLETE      ] |###############################################################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the##########################                                |  66%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
 File "/Users/gayathri/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 278, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    execute_plan(plan, index, verbose)
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/plan.py", line 420, in execute_plan
    install.unlink(prefix, arg)
  File "/Users/gayathri/anaconda/lib/python2.7/site-packages/conda/install.py", line 519, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Users/gayathri/anaconda/conda-meta/python-2.7.7-0.json'

OUTPUT of 'condo info'
Current conda install:

             platform : osx-64
        conda version : 3.5.5
       python version : 2.7.8.final.0
     root environment : /Users/gayathri/anaconda  (writable)
  default environment : /Users/gayathri/anaconda
     envs directories : /Users/gayathri/anaconda/envs
        package cache : /Users/gayathri/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False

**Comment by pelson** [comment]
I've just tried this:

```
pelson@~> conda create -n delme -c asmeurer scitools
Fetching package metadata: ........
Solving package specifications: ....................
Package plan for installation in environment /Users/pelson/miniconda/envs/delme:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-1.2.1           |       np17py27_1        29.6 MB  defaults
    scitools-0.8               |       np17py27_0         575 KB  asmeurer
    ------------------------------------------------------------
                                           Total:        30.2 MB

The following NEW packages will be INSTALLED:

    dateutil:   2.4.1-py27_0     defaults
    freetype:   2.4.10-1         defaults
    libpng:     1.5.13-1         defaults
    matplotlib: 1.2.1-np17py27_1 defaults
    ncurses:    5.9-1            asmeurer
    numpy:      1.7.1-py27_2     defaults
    openssl:    1.0.1k-1         defaults
    pip:        7.1.2-py27_0     defaults
    python:     2.7.10-1         defaults
    pytz:       2015.6-py27_0    defaults
    readline:   6.2.5-1          asmeurer
    scitools:   0.8-np17py27_0   asmeurer
    setuptools: 18.4-py27_0      defaults
    six:        1.10.0-py27_0    defaults
    sqlite:     3.8.4.1-1        defaults
    tk:         8.5.18-0         defaults
    wheel:      0.26.0-py27_1    defaults
    zlib:       1.2.8-1          asmeurer

Proceed ([y]/n)? y

Fetching packages ...

matplotlib-1.2 100% |################################| Time: 0:01:01 507.95 kB/s
scitools-0.8-n 100% |################################| Time: 0:00:01 391.43 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################| 100%
#
# To activate this environment, use:
# $ source activate delme
#
# To deactivate this environment, use:
# $ source deactivate
#
pelson@~>
```

I suspect the package got updated, and conda has matured.

This issue can be now closed.

**Comment by soapy1** [comment]
closing the issue as per last comment
