### ISSUE TITLE
set default enviroment for win10

### ISSUE THREAD

**Issue by wjx0912** [conda/conda#8062]
system is win10, i do the 2 command:
```
conda create -n 368  python=3.6.8
conda activate 368
```

after close terminal, and start a new terminal, the activate enviroment already **base**,
i need do the command again:  **conda activate 368**

it  looks like a  simple bug,  maybe have other solution?

**Comment by soapy1** [comment]
By default the base environment will be activated when you open up a new shell. If you want that base environment to have python 3.6.8 you can do a:
`conda install python=3.6.8`

**Comment by wjx0912** [comment]
@soapy1 
it works, thank you.
