### ISSUE TITLE
pip._internal import main VIPER

### ISSUE THREAD

**Issue by prabindm** [conda/conda#8064]
## Current Behavior

I am trying to install VIPER. I encounted this error while tying to run the command below.

### Steps to Reproduce

```
conda env create -f python2_environment.yml -n viper_py2
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Traceback (most recent call last):
      File "/share/pkg/miniconda/2018-02-09/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/share/pkg/miniconda/2018-02-09/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/share/pkg/miniconda/2018-02-09/lib/python2.7/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "/share/pkg/miniconda/2018-02-09/lib/python2.7/site-packages/conda_env/pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/share/pkg/miniconda/2018-02-09/lib/python2.7/subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '[u'/home/pd72a/.conda/envs/viper_py2/bin/python', u'/home/pd72a/.conda/envs/viper_py2/bin/pip', '-V']' returned non-zero exit status 1
```
</p></details>

Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /share/pkg/miniconda/2018-02-09  (read only)
    default environment : /home/pd72a/.conda/envs/my_root
       envs directories : /home/pd72a/.conda/envs
                          /share/pkg/miniconda/2018-02-09/envs
          package cache : /share/pkg/miniconda/2018-02-09/pkgs
                          /home/pd72a/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/2.7.14 Linux/2.6.32-696.28.1.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12    
                UID:GID : 50547:1507 
$ /share/pkg/miniconda/2018-02-09/bin/conda-env create -f python2_environment.yml -n viper_py2

```

```
</p></details>

**Comment by soapy1** [comment]
what is the contents of the python2_environment.yml file
