### ISSUE TITLE
bashrc perhaps not the right place for conda initialization

### ISSUE THREAD

**Issue by pitrou** [conda/conda#8072]
Right now conda will recommend editing `.bashrc` to execute the snippet that sets up `conda activate` (`source activate` is somehow considered deprecated?).

Unfortunately `.bashrc` is only run for interactive shells. Even sourcing it manually won't work, because the file commonly starts with those lines:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
You also cannot source `conda.sh` directly because you don't know its full path beforehand (unless your script is tailored for a particular machine and user).

This makes it more painful to use `conda activate` from non-interactive scripts than it should be. You could try to run those scripts with `bash -i` to force interactive mode. But that has undesirable side effects.

**Comment by msarahan** [comment]
```source activate``` is not something we'll actively encourage using, but we definitely can't deprecate it for quite a while.  It is way too central.  It may never completely die.

I'm not sure how much this is still relevant with ``conda init`` in conda 4.6.  Do you mind trying out the conda 4.6 pre-release?

```conda update -c conda-canary conda```

**Comment by pitrou** [comment]
Just tried, but since it still goes in `.bashrc`, it doesn't solve the issue.
Perhaps if conda created a separate `.bashrc.conda` and added `source $HOME/.bashrc.conda` to the main `.bashrc`, one could could source `.bashrc.conda` programmatically.

**Comment by pitrou** [comment]
That requires that you know exactly where on the filesystem `conda` is installed, or that it's already on `PATH` (but the whole point of `conda activate` is to avoid having `conda` on `PATH`, right?). That's not practical for redistributable scripts.

Example: https://github.com/apache/arrow/pull/3357

**Comment by kalefranz** [comment]
At some point within the shell init process, you have to know exactly what the path to conda is though, right? I guess unless dropping that file in `/etc/profile.d` works out.  Either it's on PATH already (which is why `source activate` works), or you know the exactly path.  Is there something I'm missing?

**Comment by pitrou** [comment]
My point was that if the user has run `conda init` already, then the Conda location is registered somewhere in the user's configuration. But a non-interactive script has no obvious way of getting that information. It would be nice if there was a simple one-liner to do that.

**Comment by kalefranz** [comment]
Yeah I think I understand the issue, and I agree that it would be nice to ha e a solution. However I’m not able to think of a technical solution that will suffice, so long as we’re assuming zero knowledge about the location of conda, and we’re also assuming no conda initialization code has ran (and thus no environment variables to leverage). The only thing I could possibly think to do is maybe start symlinking `bin/conda` to `/usr/local/bin/conda`.

I hope I’m missing something though. Can you see a way to get to what you want to accomplish?

**Comment by kalefranz** [comment]
Oh I missed the details of that above. I rather like that proposal. And then also the modification we make to `~/.bashrc` should also just be sourcing that file.

**Comment by johanneskoester** [comment]
That would be very good for Snakemake too. We currently still rely on `source activate`. But if possible, I would prefer `conda activate`. If that kind of solution is introduced, please make the location of that file available via `conda info --json`.

**Comment by Uiuran** [comment]
I dont seem to find a place to change standard conda env, since it initializes with anaconda/bin (base) env, i want it to initialize with the env i created i gave the name i refer to when working on most of projects (but need other envs to do different versions of python and, for example, to do heavy tasks such deep learning).

I see the call to eval "$(/path/to/bin/conda shell.bash hook)" in .bashrc and that it shabang a python with main() method from the conda module, however cant find where it does setup the standard env.

ps: pretty annoying to change env every time i open the bash terminal

**Comment by Uiuran** [comment]
just think these are related issues

**Comment by Uiuran** [comment]
Ok, just forget what i just said, it suddenly worked. But i think the same of the original poster, .bashrc may not be the best place for conda init.
