### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by lucidBrot** [conda/conda#8078]
## Current Behavior

I created an anaconda env on my Win10 desktop PC using `conda create -n gecobot python=3.6`. Installed some packages, wrote some code, then exported using `conda env export > environment.yml`.

On my raspberry pi, running Jessie, I followed [this guide](https://stackoverflow.com/a/39371773/2550406) to install the latest Miniconda. I allowed the installer to add to the PATH and after the installer finished I ran `source ~/.bashrc`. Then, see Steps to Reproduce

### Steps to Reproduce

```
pi@goodberrypsi:~/punktbot/gecobot $ conda env create -f environment.yml
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 77, in execute
    directory=os.getcwd())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/specs/__init__.py", line 18, in detect
    if spec.can_handle():
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/env.py", line 65, in from_file
    return from_yaml(fp.read(), filename=filename)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/env.py", line 58, in from_yaml
    return Environment(**data)
TypeError: __init__() got an unexpected keyword argument 'prefix'
pi@goodberrypsi:~/punktbot/gecobot $ uname -m
armv7l

```

## Expected Behavior

Miniconda should download the required packages as outlined in the `environment.yml` file. Tbh, I do not understand why the line
```prefix: F:\My\Path\to\Anaconda3\envs\gecobot```
needs to be in the `environment.yml` file and because of my lack of understanding I think miniconda should just ignore that prefix line.
Commenting the line out gets rid of this error. (Now it does not find some packages, but that is a different problem)

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
pi@goodberrypsi:~/punktbot/gecobot $ conda info
Current conda install:

             platform : linux-armv7l
        conda version : 3.16.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/pi/miniconda3  (writable)
  default environment : /home/pi/miniconda3
     envs directories : /home/pi/miniconda3/envs
        package cache : /home/pi/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-armv7l/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-armv7l/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
pi@goodberrypsi:~/punktbot/gecobot $ conda config --show-sources
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
pi@goodberrypsi:~/punktbot/gecobot $ conda list --show-channel-urls
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --show-channel-urls

```
</p></details>

**Comment by msarahan** [comment]
That version of conda in ancient and definitely not supported.  You can get newer versions from the berryconda project, https://github.com/jjhelmus/berryconda

**Comment by lucidBrot** [comment]
Hmm alright, thanks for your assistance.

I installed this version by following [this stackoverflow question](https://stackoverflow.com/a/39371773/2550406) and the link being called "latest" ([ttp://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh](ttp://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh)) made it sound like it would be an up-to-date version.
