### ISSUE TITLE
conda-4.5.12 does not work after downgrading from conda-4.6rc1

### ISSUE THREAD

**Issue by mhlr** [conda/conda#8080]
after

    conda update -c conda-canary conda

and later (because conda-4.6rc1 kept wanting to upgrade to python-3.7)

    conda install conda=4.5 python=3.6

conda-4.5.12 now refuses to work

```
(base) $ conda install -c conda-forge conda=4.6
Solving environment: failed

CondaUpgradeError: This environment has previously been operated on by a conda version that's newer
than the conda currently being used. A newer version of conda is required.
  target environment location: /home/dm/anaconda3
  current conda version: 4.5.12
  minimum conda version: 4.6


(base) $ conda update -c conda-forge conda
Solving environment: failed

CondaUpgradeError: This environment has previously been operated on by a conda version that's newer
than the conda currently being used. A newer version of conda is required.
  target environment location: /home/dm/anaconda3
  current conda version: 4.5.12
  minimum conda version: 4.6
```

**Comment by bryevdv** [comment]
@msarahan in cases like this where there is a concrete action that can be taken I've found it helpful to put it directly in the error message so users can self-serve without having to resort to a GH issue.

**Comment by nehaljwani** [comment]
Looks like https://github.com/conda/conda/commit/973db0c46cf06698828b25e179000c4f45197604 didn't make it to 4.6.0rc1 or 4.5.12 🤔

**Comment by msarahan** [comment]
Hmmm... good catch.  It also doesn't seem to have come into master with the merge of 4.5.x into master.  Stealth commit!  Please pull it back into master directly when you can, since it has already been approved and merged.

**Comment by analog-cbarber** [comment]
Hmm.

```
$ conda config --set allow_conda_downgrades true

CondaValueError: Key 'allow_conda_downgrades' is not a known primitive parameter.

````

**Comment by analog-cbarber** [comment]
Setting the parameter by editing the `.condarc` file directly appears to work:

```
allow_conda_downgrades: true
```

**Comment by msarahan** [comment]
Sorry for the issues here.  This downgrade behavior is highly undesirable.  We'll work to urgently fix it and issue a new release, along with instructions on how to get conda "un-stuck."

**Comment by nwoyecid** [comment]
> Setting the parameter by editing the `.condarc` file directly appears to work:
> 
> ```
> allow_conda_downgrades: true
> ```

Where do you find  `.condarc` file?

**Comment by analog-cbarber** [comment]
In your home directory. Create the file or just use:

```
conda config --set allow_conda_downgrades true
```
