### ISSUE TITLE
Conda install pyttsx

### ISSUE THREAD

**Issue by niteshpandeyofficial** [conda/conda#8085]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request
Feature request

## Current Behavior

at the time of installing pttsx package i got below error
![image](https://user-images.githubusercontent.com/20104212/51070197-73177000-1663-11e9-8b64-0bb89aa1f070.png)

### Steps to Reproduce

```

```

## Expected Behavior

noarch/repodata.json is empty at specified link

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
![image](https://user-images.githubusercontent.com/20104212/51070237-1ec0c000-1664-11e9-9e1c-1eac2ee9fa39.png)

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
![config_show](https://user-images.githubusercontent.com/20104212/51070299-ec639280-1664-11e9-8f18-310a91d6f328.PNG)


```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
https://conda.anaconda.org/pyttsx/noarch
```
</p></details>

**Comment by soapy1** [comment]
It looks like your channel list is kind of messed up. I can't find a pyttsx channel on anaconda.org. So, you'll want to remove that. Then if you look at https://anaconda.org/search?q=pyttsx you can find what pyttsx packages are already available in what channels.
