### ISSUE TITLE
Conda and mayavi

### ISSUE THREAD

**Issue by RamiGASMI** [conda/conda#8086]
Hi every one, 

I have troubles when trying to install mayavi or vtk with anaconda and python 3.7. this is the message i get when installing with --debug command and it gets stck and hanging there 

DEBUG conda.resolve:filter_group(277): apptools: pruned from 26 -> 24
DEBUG conda.resolve:filter_group(277): python: pruned from 245 -> 221
DEBUG conda.resolve:filter_group(277): pip: pruned from 242 -> 164
DEBUG conda.resolve:filter_group(277): traits: pruned from 36 -> 30
DEBUG conda.resolve:filter_group(277): numpy: pruned from 572 -> 480
DEBUG conda.resolve:filter_group(277): python: pruned from 221 -> 93
DEBUG conda.resolve:filter_group(277): pip: pruned from 164 -> 74
DEBUG conda.resolve:filter_group(277): traitsui: pruned from 22 -> 8
DEBUG conda.resolve:filter_group(277): pyface: pruned from 22 -> 8
DEBUG conda.resolve:filter_group(277): traits: pruned from 30 -> 12
DEBUG conda.resolve:filter_group(277): vtk: pruned from 16 -> 6
DEBUG conda.resolve:filter_group(277): _ipyw_jlab_nb_ext_conf: pruned from 14 -> 4
DEBUG conda.resolve:filter_group(277): ipywidgets: pruned from 136 -> 40
DEBUG conda.resolve:filter_group(277): ipykernel: pruned from 126 -> 36
DEBUG conda.resolve:filter_group(277): ipython: pruned from 292 -> 82
DEBUG conda.resolve:filter_group(277): jupyter_client: pruned from 87 -> 27
DEBUG conda.resolve:filter_group(277): jupyter_core: pruned from 74 -> 24
DEBUG conda.resolve:filter_group(277): traitlets: pruned from 54 -> 16
DEBUG conda.resolve:filter_group(277): decorator: pruned from 94 -> 26
DEBUG conda.resolve:filter_group(277): ipython_genutils: pruned from 24 -> 6
DEBUG conda.resolve:filter_group(277): pyzmq: pruned from 198 -> 56
DEBUG conda.resolve:filter_group(277): jupyterlab: pruned from 178 -> 42
DEBUG conda.resolve:filter_group(277): jupyterlab_launcher: pruned from 66 -> 18
DEBUG conda.resolve:filter_group(277): notebook: pruned from 224 -> 72
DEBUG conda.resolve:filter_group(277): jinja2: pruned from 120 -> 32
DEBUG conda.resolve:filter_group(277): nbconvert: pruned from 56 -> 16
DEBUG conda.resolve:filter_group(277): mistune: pruned from 100 -> 28
DEBUG conda.resolve:filter_group(277): nbformat: pruned from 48 -> 14
DEBUG conda.resolve:filter_group(277): jsonschema: pruned from 34 -> 8
DEBUG conda.resolve:filter_group(277): pygments: pruned from 71 -> 19
DEBUG conda.resolve:filter_group(277): tornado: pruned from 198 -> 58
DEBUG conda.resolve:filter_group(277): notebook: pruned from 72 -> 48
DEBUG conda.resolve:filter_group(277): tornado: pruned from 58 -> 40
DEBUG conda.resolve:filter_group(277): widgetsnbextension: pruned from 102 -> 30
DEBUG conda.resolve:filter_group(277): vc: pruned from 22 -> 20
DEBUG conda.resolve:filter_group(277): zlib: pruned from 34 -> 16
DEBUG conda.resolve:filter_group(277): zict: pruned from 48 -> 14
DEBUG conda.resolve:filter_group(277): heapdict: pruned from 32 -> 8
DEBUG conda.resolve:filter_group(277): zeromq: pruned from 36 -> 34
DEBUG conda.resolve:filter_group(277): xlwt: pruned from 52 -> 16
DEBUG conda.resolve:filter_group(277): xlwings: pruned from 235 -> 77
DEBUG conda.resolve:filter_group(277): pywin32: pruned from 70 -> 22
DEBUG conda.resolve:filter_group(277): xlsxwriter: pruned from 262 -> 76
DEBUG conda.resolve:filter_group(277): xlrd: pruned from 69 -> 19
DEBUG conda.resolve:filter_group(277): wrapt: pruned from 40 -> 12
DEBUG conda.resolve:filter_group(277): win_unicode_console: pruned from 16 -> 4
DEBUG conda.resolve:filter_group(277): win_inet_pton: pruned from 20 -> 6
DEBUG conda.resolve:filter_group(277): wincertstore: pruned from 14 -> 4
DEBUG conda.resolve:filter_group(277): wheel: pruned from 82 -> 24
DEBUG conda.resolve:filter_group(277): werkzeug: pruned from 168 -> 50
DEBUG conda.resolve:filter_group(277): webencodings: pruned from 14 -> 4
DEBUG conda.resolve:filter_group(277): wcwidth: pruned from 16 -> 4
DEBUG conda.resolve:filter_group(277): urllib3: pruned from 32 -> 10
DEBUG conda.resolve:filter_group(277): certifi: pruned from 75 -> 21
DEBUG conda.resolve:filter_group(277): cryptography: pruned from 217 -> 37
DEBUG conda.resolve:filter_group(277): cffi: pruned from 142 -> 22
DEBUG conda.resolve:filter_group(277): pycparser: pruned from 90 -> 24
DEBUG conda.resolve:filter_group(277): enum34: pruned from 26 -> 18
DEBUG conda.resolve:filter_group(277): idna: pruned from 65 -> 17
DEBUG conda.resolve:filter_group(277): ipaddress: pruned from 18 -> 16
DEBUG conda.resolve:filter_group(277): openssl: pruned from 110 -> 90
DEBUG conda.resolve:filter_group(277): six: pruned from 101 -> 23
DEBUG conda.resolve:filter_group(277): pyopenssl: pruned from 86 -> 24
DEBUG conda.resolve:filter_group(277): pysocks: pruned from 20 -> 6
DEBUG conda.resolve:filter_group(277): unicodecsv: pruned from 24 -> 8
DEBUG conda.resolve:filter_group(277): tqdm: pruned from 98 -> 30
DEBUG conda.resolve:filter_group(277): toolz: pruned from 72 -> 20
DEBUG conda.resolve:filter_group(277): tk: pruned from 18 -> 16
DEBUG conda.resolve:filter_group(277): testpath: pruned from 36 -> 8
DEBUG conda.resolve:filter_group(277): terminado: pruned from 8 -> 2
DEBUG conda.resolve:filter_group(277): pywinpty: pruned from 39 -> 11
DEBUG conda.resolve:filter_group(277): backports.shutil_which: pruned from 14 -> 4
DEBUG conda.resolve:filter_group(277): backports: pruned from 22 -> 6
DEBUG conda.resolve:filter_group(277): tblib: pruned from 40 -> 12
DEBUG conda.resolve:filter_group(277): sympy: pruned from 82 -> 28
DEBUG conda.resolve:filter_group(277): statsmodels: pruned from 126 -> 40
DEBUG conda.resolve:filter_group(277): numpy: pruned from 480 -> 178
DEBUG conda.resolve:filter_group(277): pandas: pruned from 312 -> 98
DEBUG conda.resolve:filter_group(277): sqlite: pruned from 56 -> 50
DEBUG conda.resolve:filter_group(277): sqlalchemy: pruned from 369 -> 109
DEBUG conda.resolve:filter_group(277): spyder-kernels: pruned from 30 -> 8
DEBUG conda.resolve:filter_group(277): cloudpickle: pruned from 90 -> 26
DEBUG conda.resolve:filter_group(277): spyder: pruned from 232 -> 94
DEBUG conda.resolve:filter_group(277): sphinxcontrib-websupport: pruned from 20 -> 6
DEBUG conda.resolve:filter_group(277): sphinxcontrib: pruned from 20 -> 6
DEBUG conda.resolve:filter_group(277): sphinx: pruned from 232 -> 72
DEBUG conda.resolve:filter_group(277): docutils: pruned from 66 -> 20
DEBUG conda.resolve:filter_group(277): sortedcontainers: pruned from 60 -> 18
DEBUG conda.resolve:filter_group(277): sortedcollections: pruned from 34 -> 10
DEBUG conda.resolve:filter_group(277): snowballstemmer: pruned from 26 -> 6
DEBUG conda.resolve:filter_group(277): sip: pruned from 64 -> 18
DEBUG conda.resolve:filter_group(277): singledispatch: pruned from 16 -> 4
DEBUG conda.resolve:filter_group(277): simplegeneric: pruned from 28 -> 8
DEBUG conda.resolve:filter_group(277): setuptools: pruned from 487 -> 135
DEBUG conda.resolve:filter_group(277): send2trash: pruned from 14 -> 4
DEBUG conda.resolve:filter_group(277): seaborn: pruned from 74 -> 22
DEBUG conda.resolve:filter_group(277): matplotlib: pruned from 256 -> 84
DEBUG conda.resolve:filter_group(277): pytz: pruned from 186 -> 54
DEBUG conda.resolve:filter_group(277): scipy: pruned from 287 -> 89
DEBUG conda.resolve:filter_group(277): scikit-learn: pruned from 328 -> 114
DEBUG conda.resolve:filter_group(277): scikit-image: pruned from 199 -> 63
DEBUG conda.resolve:filter_group(277): ruamel_yaml: pruned from 66 -> 20
DEBUG conda.resolve:filter_group(277): rope: pruned from 48 -> 12
DEBUG conda.resolve:filter_group(277): requests: pruned from 247 -> 69
DEBUG conda.resolve:filter_group(277): qtpy: pruned from 104 -> 32
DEBUG conda.resolve:filter_group(277): qtconsole: pruned from 105 -> 33
DEBUG conda.resolve:filter_group(277): pyqt: pruned from 106 -> 28
DEBUG conda.resolve:filter_group(277): qtawesome: pruned from 66 -> 20
DEBUG conda.resolve:filter_group(277): qt: pruned from 83 -> 61
DEBUG conda.resolve:filter_group(277): jpeg: pruned from 28 -> 22
DEBUG conda.resolve:filter_group(277): libpng: pruned from 54 -> 44
DEBUG conda.resolve:filter_group(277): pyyaml: pruned from 82 -> 22
DEBUG conda.resolve:filter_group(277): pywavelets: pruned from 46 -> 14
DEBUG conda.resolve:filter_group(277): numpy: pruned from 178 -> 98
DEBUG conda.resolve:filter_group(277): python-libarchive-c: pruned from 46 -> 12
DEBUG conda.resolve:filter_group(277): bzip2: pruned from 34 -> 30
DEBUG conda.resolve:filter_group(277): libiconv: pruned from 14 -> 12
DEBUG conda.resolve:filter_group(277): openssl: pruned from 90 -> 22
DEBUG conda.resolve:filter_group(277): python-dateutil: pruned from 90 -> 26
DEBUG conda.resolve:filter_group(277): python: pruned from 93 -> 0

**Comment by soapy1** [comment]
Please include the output of `conda info` and the command(s) you are running in your issue. Currently, I can't reproduce your issue.

**Comment by RamiGASMI** [comment]
Hi thank you for the reply, 

this is the output of conda info:

    active environment : base
    active env location : C:\Users\33624\Anaconda3
            shell level : 1
       user config file : C:\Users\33624\.condarc
 populated config files : C:\Users\33624\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\33624\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\33624\Anaconda3\pkgs
                          C:\Users\33624\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\33624\Anaconda3\envs
                          C:\Users\33624\AppData\Local\conda\conda\envs
                          C:\Users\33624\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

**Comment by larsoner** [comment]
I have seen this on CIs trying to migrate them to 3.7.

On Linux, vanilla `conda` 4.6.1 from Miniconda I can reproduce with:
```Console
$ curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ chmod +x Miniconda3-latest-Linux-x86_64.sh
$ ./Miniconda3-latest-Linux-x86_64.sh  # installed to "testconda3"
$ source /home/larsoner/testconda3/etc/profile.d/conda.sh
$ conda update -n base conda  # 4.5.12 -> 4.6.1
$ conda create -n vtk "python>=3.7 vtk"
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python[version='>=3.7',build=vtk]
```

**Comment by soapy1** [comment]
So, it looks like  there is no mayavi or vtk package for python 3.7

```
$ conda search mayavi
Loading channels: done
# Name                       Version           Build  Channel
mayavi                         4.3.0      np17py27_0  pkgs/free
mayavi                         4.3.0      np17py27_1  pkgs/free
mayavi                         4.3.0      np17py27_2  pkgs/free
mayavi                         4.3.0      np17py27_3  pkgs/free
mayavi                         4.3.0      np17py27_4  pkgs/free
mayavi                         4.3.1      np18py27_0  pkgs/free
mayavi                         4.3.1      np18py27_1  pkgs/free
mayavi                         4.3.1      np19py27_1  pkgs/free
mayavi                         4.4.0      np19py27_0  pkgs/free
mayavi                         4.5.0          py27_0  pkgs/free
```

these are all python 2.7 packages

and
```
$ conda search vtk
Loading channels: done
# Name                       Version           Build  Channel
vtk                           5.10.1          py27_0  pkgs/free
vtk                            6.3.0          py27_0  pkgs/free
vtk                            6.3.0          py27_1  pkgs/free
vtk                            8.1.0 py27h04d9db9_201  pkgs/main
vtk                            8.1.0 py27h87a2a2b_201  pkgs/main
vtk                            8.1.0 py35h04d9db9_201  pkgs/main
vtk                            8.1.0 py35h87a2a2b_201  pkgs/main
vtk                            8.1.0 py36h04d9db9_201  pkgs/main
vtk                            8.1.0 py36h87a2a2b_201  pkgs/main
vtk                            8.1.1 py27ha9eb873_204  pkgs/main
vtk                            8.1.1 py27hce9f6a2_204  pkgs/main
vtk                            8.1.1 py36ha9eb873_204  pkgs/main
vtk                            8.1.1 py36hce9f6a2_204  pkgs/main
```
no python 3.7 packages

you could try building the packages, or search on anaconda.org for versions python 3.7 versions of this package

**Comment by larsoner** [comment]
FWIW my workaround in the meantime has been just to install `vtk` with `pip`.
