### ISSUE TITLE
Conda can no longer install an offline package

### ISSUE THREAD

**Issue by fbriol** [conda/conda#8090]
## Current Behavior

I have a directory containing the local icu (hopefully it is the same library
between the two versions of conda tested) library and associated indexes
created using the ``conda index`` command.

    $ find /tmp/cots_anaconda3-4.4.10/channel -type f
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.about.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/icu-58.2-h9c2bf20_1.tar.bz2
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.recipe.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/index.html
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.index.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.paths.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/stat.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/recipe_log/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/run_exports/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/about/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/paths/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/recipe/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/index/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/.cache/post_install/icu-58.2-h9c2bf20_1.tar.bz2.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/repodata.json
    tmp/cots_anaconda3-4.4.10/channel/linux-64/repodata.json.bz2
    tmp/cots_anaconda3-4.4.10/channel/linux-64/repodata2.json

If I try to install it in "offline" mode with version *4.4.10* it works. This is
impossible since version 4.5.1.

### Steps to Reproduce

If I try with versions *4.5.1* or *4.5.12* it is impossible to install this package offline.

    bash ./Miniconda3-4.5.12-Linux-x86_64.sh -b -p miniconda
    cd miniconda
    ./bin/conda install --use-local --offline -c file://tmp/cots_anaconda3-4.4.10/channel icu
    Solving environment: failed

    PackagesNotFoundError: The following packages are not available from current channels:

    - icu
    - libgcc-ng=7.2.0
    - icu
    - libstdcxx-ng=7.2.0

    Current channels:

    - file://tmp/cots_anaconda3-4.4.10/channel/linux-64
    - file://tmp/cots_anaconda3-4.4.10/channel/noarch
    - https://repo.anaconda.com/pkgs/main/linux-64
    - https://repo.anaconda.com/pkgs/main/noarch
    - https://repo.anaconda.com/pkgs/free/linux-64
    - https://repo.anaconda.com/pkgs/free/noarch
    - https://repo.anaconda.com/pkgs/r/linux-64
    - https://repo.anaconda.com/pkgs/r/noarch
    - https://repo.anaconda.com/pkgs/pro/linux-64
    - https://repo.anaconda.com/pkgs/pro/noarch

    To search for alternate channels that may provide the conda package you're
    looking for, navigate to

        https://anaconda.org

    and use the search bar at the top of the page.

## Expected Behavior

If I try to install it in "offline" mode with version *4.4.10*  it works:

    bash ./Miniconda3-4.4.10-Linux-x86_64.sh -b -p miniconda
    cd miniconda
    ./bin/conda install --use-local --offline -c file://tmp/cots_anaconda3-4.4.10/channel icu
    Solving environment: done

    ## Package Plan ##

    environment location: /tmp/anaconda3-4.4.10/miniconda

    added / updated specs: 
        - icu

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        icu-58.2                   |       h9c2bf20_1        22.5 MB  file://tmp/cots_anaconda3-4.4.10/channel

    The following NEW packages will be INSTALLED:

        icu: 58.2-h9c2bf20_1 file://tmp/cots_anaconda3-4.4.10/channel

## Environment Information
<details open><summary><code>`conda info #4.4.10`</code></summary><p>

        active environment : None
        user config file : /home/fbriol/.condarc
    populated config files : 
            conda version : 4.4.10
        conda-build version : not installed
            python version : 3.6.4.final.0
        base environment : /tmp/anaconda3-4.4.10/miniconda  (writable)
            channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                            https://repo.continuum.io/pkgs/main/noarch
                            https://repo.continuum.io/pkgs/free/linux-64
                            https://repo.continuum.io/pkgs/free/noarch
                            https://repo.continuum.io/pkgs/r/linux-64
                            https://repo.continuum.io/pkgs/r/noarch
                            https://repo.continuum.io/pkgs/pro/linux-64
                            https://repo.continuum.io/pkgs/pro/noarch
            package cache : /tmp/anaconda3-4.4.10/miniconda/pkgs
                            /home/fbriol/.conda/pkgs
        envs directories : /tmp/anaconda3-4.4.10/miniconda/envs
                            /home/fbriol/.conda/envs
                platform : linux-64
                user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.15.0-43-generic ubuntu/18.04 glibc/2.27
                    UID:GID : 1000:1000
                netrc file : None
            offline mode : False

</p></details>

<details open><summary><code>`conda info #4.5.12`</code></summary><p>

        active environment : None
        user config file : /home/fbriol/.condarc
    populated config files : 
            conda version : 4.5.12
        conda-build version : not installed
            python version : 3.7.1.final.0
        base environment : /tmp/anaconda3-4.5.12/miniconda  (writable)
            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                            https://repo.anaconda.com/pkgs/main/noarch
                            https://repo.anaconda.com/pkgs/free/linux-64
                            https://repo.anaconda.com/pkgs/free/noarch
                            https://repo.anaconda.com/pkgs/r/linux-64
                            https://repo.anaconda.com/pkgs/r/noarch
                            https://repo.anaconda.com/pkgs/pro/linux-64
                            https://repo.anaconda.com/pkgs/pro/noarch
            package cache : /tmp/anaconda3-4.5.12/miniconda/pkgs
                            /home/fbriol/.conda/pkgs
        envs directories : /tmp/anaconda3-4.5.12/miniconda/envs
                            /home/fbriol/.conda/envs
                platform : linux-64
                user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-43-generic ubuntu/18.04 glibc/2.27
                    UID:GID : 1000:1000
                netrc file : None
            offline mode : False

</p></details>

<details open><summary><code>`conda config --show-sources #4.4.10`</code></summary><p>

</p></details>

<details open><summary><code>`conda config --show-sources #4.5.12`</code></summary><p>

</p></details>

<details><summary><code>`conda list --show-channel-urls #4.4.10`</code></summary><p>

    # packages in environment at /tmp/anaconda3-4.4.10/miniconda:
    #
    # Name                    Version                   Build  Channel
    asn1crypto                0.24.0                   py36_0    defaults
    ca-certificates           2017.08.26           h1d4fec5_0    defaults
    certifi                   2018.1.18                py36_0    defaults
    cffi                      1.11.4           py36h9745a5d_0    defaults
    chardet                   3.0.4            py36h0f667ec_1    defaults
    conda                     4.4.10                   py36_0    defaults
    conda-env                 2.6.0                h36134e3_1    defaults
    cryptography              2.1.4            py36hd09be54_0    defaults
    idna                      2.6              py36h82fb2a8_1    defaults
    libedit                   3.1                  heed3624_0    defaults
    libffi                    3.2.1                hd88cf55_4    defaults
    libgcc-ng                 7.2.0                h7cc24e2_2    defaults
    libstdcxx-ng              7.2.0                h7a57d05_2    defaults
    ncurses                   6.0                  h9df7e31_2    defaults
    openssl                   1.0.2n               hb7f436b_0    defaults
    pip                       9.0.1            py36h6c6f9ce_4    defaults
    pycosat                   0.6.3            py36h0a5515d_0    defaults
    pycparser                 2.18             py36hf9f622e_1    defaults
    pyopenssl                 17.5.0           py36h20ba746_0    defaults
    pysocks                   1.6.7            py36hd97a5b1_1    defaults
    python                    3.6.4                hc3d631a_1    defaults
    readline                  7.0                  ha6073c6_4    defaults
    requests                  2.18.4           py36he2e5f8d_1    defaults
    ruamel_yaml               0.15.35          py36h14c3975_1    defaults
    setuptools                38.4.0                   py36_0    defaults
    six                       1.11.0           py36h372c433_1    defaults
    sqlite                    3.22.0               h1bed415_0    defaults
    tk                        8.6.7                hc745277_3    defaults
    urllib3                   1.22             py36hbe7ace6_0    defaults
    wheel                     0.30.0           py36hfd4bba0_1    defaults
    xz                        5.2.3                h55aa19d_2    defaults
    yaml                      0.1.7                had09818_2    defaults
    zlib                      1.2.11               ha838bed_2    defaults

</p></details>

<details><summary><code>`conda list --show-channel-urls #4.5.15`</code></summary><p>

    # packages in environment at /tmp/anaconda3-4.5.12/miniconda:
    #
    # Name                    Version                   Build  Channel
    asn1crypto                0.24.0                   py37_0    defaults
    ca-certificates           2018.03.07                    0    defaults
    certifi                   2018.11.29               py37_0    defaults
    cffi                      1.11.5           py37he75722e_1    defaults
    chardet                   3.0.4                    py37_1    defaults
    conda                     4.5.12                   py37_0    defaults
    conda-env                 2.6.0                         1    defaults
    cryptography              2.4.2            py37h1ba5d50_0    defaults
    idna                      2.8                      py37_0    defaults
    libedit                   3.1.20170329         h6b74fdf_2    defaults
    libffi                    3.2.1                hd88cf55_4    defaults
    libgcc-ng                 8.2.0                hdf63c60_1    defaults
    libstdcxx-ng              8.2.0                hdf63c60_1    defaults
    ncurses                   6.1                  he6710b0_1    defaults
    openssl                   1.1.1a               h7b6447c_0    defaults
    pip                       18.1                     py37_0    defaults
    pycosat                   0.6.3            py37h14c3975_0    defaults
    pycparser                 2.19                     py37_0    defaults
    pyopenssl                 18.0.0                   py37_0    defaults
    pysocks                   1.6.8                    py37_0    defaults
    python                    3.7.1                h0371630_7    defaults
    readline                  7.0                  h7b6447c_5    defaults
    requests                  2.21.0                   py37_0    defaults
    ruamel_yaml               0.15.46          py37h14c3975_0    defaults
    setuptools                40.6.3                   py37_0    defaults
    six                       1.12.0                   py37_0    defaults
    sqlite                    3.26.0               h7b6447c_0    defaults
    tk                        8.6.8                hbc83047_0    defaults
    urllib3                   1.24.1                   py37_0    defaults
    wheel                     0.32.3                   py37_0    defaults
    xz                        5.2.4                h14c3975_4    defaults
    yaml                      0.1.7                had09818_2    defaults
    zlib                      1.2.11               h7b6447c_3    defaults
</p></details>

**Comment by soapy1** [comment]
I can't reproduce this issue on my machine. Could you provide the contents of `/tmp/cots_anaconda3-4.4.10/channel/linux-64/repodata.json`

**Comment by kalefranz** [comment]
./bin/conda install --use-local --offline -c file://tmp/cots_anaconda3-4.4.10/channel icu

You're missing a forward slash.  Should be

    -c file:///tmp/cots_anaconda3-4.4.10/channel

**Comment by fbriol** [comment]
Hello,

I wrote a little script to show you what the problem is. You can reproduce the problem on your PC, at least I hope so, using the script contained in this archive: [offline_bug.bash.zip](https://github.com/conda/conda/files/2763368/offline_bug.bash.zip)

The last command of this script will exit in error and display the following lines:

<pre>
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cmake
  - libcurl[version='>=7.61.0,<8.0a0']
  - krb5[version='>=1.16.1,<1.17.0a0']
  - openssl[version='>=1.1.1,<1.1.2.0a0']
  - cmake
  - libcurl[version='>=7.61.0,<8.0a0']
  - libssh2[version='>=1.8.0,<2.0a0']

Current channels:

  - file:///tmp/local/linux-64
  - file:///tmp/local/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
</pre>

If we execute the last command in online mode, we can see that the resolution cannot find the ``krb5`` and ``libssh2`` packages that are present in the downloaded files.

    $BUILD/miniconda/bin/conda install -c file://$PWD/local cmake

<pre>
Solving environment: done

## Package Plan ##

  environment location: /tmp/tmp.EM94D1N6Ls/miniconda

  added / updated specs: 
    - cmake


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.6                |       h14c3975_5         414 KB  file:///tmp/local
    expat-2.2.6                |       he6710b0_0         187 KB  file:///tmp/local
    libcurl-7.63.0             |    h20c2e04_1000         550 KB  file:///tmp/local
    cmake-3.12.2               |       h52cb24c_0        10.0 MB  file:///tmp/local
    krb5-1.16.1                |       h173b8e3_7         1.4 MB
    libssh2-1.8.0              |       h1ba5d50_4         233 KB
    rhash-1.3.7                |       h1ba5d50_0         209 KB  file:///tmp/local
    ------------------------------------------------------------
                                           Total:        13.0 MB

The following NEW packages will be INSTALLED:

    bzip2:   1.0.6-h14c3975_5     file:///tmp/local
    cmake:   3.12.2-h52cb24c_0    file:///tmp/local
    expat:   2.2.6-he6710b0_0     file:///tmp/local
    krb5:    1.16.1-h173b8e3_7                     
    libcurl: 7.63.0-h20c2e04_1000 file:///tmp/local
    libssh2: 1.8.0-h1ba5d50_4                      
    rhash:   1.3.7-h1ba5d50_0     file:///tmp/local

Proceed ([y]/n)? n
</pre>

It is easy here to check that the two packages that the resolution could not find, exist in the local directory.

    ls -l "local/linux-64/krb5-1.16.1-h173b8e3_7.tar.bz2" \
       "local/linux-64/libssh2-1.8.0-h1ba5d50_4.tar.bz2"

<pre>
-rw-r--r-- 1 fbriol fbriol 1460071 janv. 16 09:55 local/linux-64/krb5-1.16.1-h173b8e3_7.tar.bz2
-rw-r--r-- 1 fbriol fbriol  238775 janv. 16 09:55 local/linux-64/libssh2-1.8.0-h1ba5d50_4.tar.bz2
</pre>

**Comment by orodbhen** [comment]
Probably related to this. I created a repo on an air-gap system using `conda index`, and created a `.condarc` file with the channel URLs. This setup was working previously, with conda 4.5.11, but now when trying to run `conda update conda` with conda 4.5.12, I get:

```
PackagesNotFoundError: The following packages are not available from current channels:

- conda[version='>=4.5.12']
...
```

The list of packages is long, and I'm not able to copy and paste it over. Running `conda info conda` shows that conda 4.6.7 is in the repo. 

If I try using an older environment, with conda 4.5.11 installed, I get:

```
Please update conda by running 

    $ conda update -n base conda

# All requested packages already installed
```

Which is a little confusing.

If I do the same thing using the online repos, conda updates without issues. So this seems to be a problem with `conda index`, which was run using 4.5.12. My old base environment hasn't changed, only the index.

**Comment by msarahan** [comment]
These problems are because repodata can be altered from what is in packages.  We publish the hotfixing code for our channels at https://github.com/AnacondaRecipes/repodata-hotfixes

Building an index from packages is not at all guaranteed to get you the same thing that downloading the online repodata gets you.

**Comment by orodbhen** [comment]
@msarahan Thanks for the response. So then I should run run the script to generate a patch, then apply it to my repodata file?

**Comment by msarahan** [comment]
yes.  You can pass an argument to conda-index to run the patch generation stuff.  From ``conda index -h``:

```
-p PATCH_GENERATOR, --patch-generator PATCH_GENERATOR                                                                                                                                                                Path to Python file that outputs metadata patch                                                                                                                                                instructions
``
