### ISSUE TITLE
Activating environments doesn't source scripts!

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8101]
## Current Behaviour

Just kicking the tyres of the 4.6.0 (pre-)release and I'm getting a problem when activating/deactivating environments in powershell
```powershell
(base) C:\Users\dhirschfeld (file:///C:/Users/dhirschfeld )> conda activate py-dev 
remove-item : Cannot find path 'Alias:\git' because it does not exist. 
At C:\Miniconda3\etc\conda\deactivate.d\hub.ps1:1 (file:///C:/Miniconda3/etc/conda/deactivate.d/hub.ps1:1) char:1 
+ remove-item alias:\git 
+ ~~~~~~~~~~~~~~~~~~~~~~ 
    + CategoryInfo          : ObjectNotFound: (Alias:\git:String) [Remove-Item], ItemNotFoundException 
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

This doesn't seem to affect the activation/deactivation but is a bit annoying/alarming.

It might be relevant that I have Posh-Git install and import it in my $PROFILE *before* the `conda init` stuff

**Comment by dhirschfeld** [comment]
Let me know if you need more info to repro the error...

**Comment by dhirschfeld** [comment]
I tried on another box and can't actually repro the problem there so I'll see if I can get more info from the original machine...

**Comment by dhirschfeld** [comment]
Ok, tracked it down - looks like a bad interaction with the [`hub`](https://github.com/conda-forge/hub-feedstock) package

**Comment by dhirschfeld** [comment]
Over in https://github.com/conda-forge/hub-feedstock/issues/15 it was discovered that the reason the `hub.ps1` script fails is because it isn't being *sourced* when the environment is activated.

Is this a bug in conda? *Should* the scripts be being sourced?

**Comment by kalefranz** [comment]
Bug in 4.6.0 pre-release. Closing.
