### ISSUE TITLE
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib

### ISSUE THREAD

**Issue by ssalav** [conda/conda#8103]
Hello,

I installed samtools with anaconda. I tried to run the 'samtools view -bS eg3.sam > eg3.bam' [eg3.sam is output of the Hisat2] and I got this error.

dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /anaconda2/bin/samtools
  Reason: image not found
Trace/BPT trap: 5

I tried to uninstall and install again the samtools but it doesnot work. What should I do now?

**Comment by stephenshank** [comment]
@ssalav I can confirm that I am experiencing the same issue. Moreover, when I create a fresh environment i.e.

```
conda create -n bioinformatics samtools
```

a simple command like `samtools flags 147` works. However, when I `conda install ipython` and rerun the same command, I experience the error you posted.

Did you manage to resolve the issue? Perhaps there is a more appropriate place to post these concerns.

**Comment by tvallet95** [comment]
@ssalav I had the same issue a few days ago. 
Updating postgresql worked for me 

conda install -c conda-forge postgresql

**Comment by stephenshank** [comment]
@ssalav There is a [related issue](https://github.com/conda-forge/conda-forge.github.io/issues/701) on conda-forge.

**Comment by SirSharpest** [comment]
Just want to confirm, this is still an issue!

**Comment by chenghlee** [comment]
Can you please provide the output of `conda list`? It looks like some package in the dependency chain did not correctly constrain its OpenSSL requirement. `samtools` is not a package in the standard Anaconda "defaults" channel, so in all likelihood, you will need to contact some other package maintainer for a fix.

**Comment by lamunge** [comment]
I had the same issue until I ran conda update --all. That caused samtools to update from 1.4.1 to 1.9, openssl remained 1.1.1g. So perhaps this was a known issue that got fixed?

In case it is useful, here is my conda list output before and after updating:
Before:
```
(base) test|⇒ conda list
# packages in environment at /Users/annar/miniconda3:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hc512035_1  
chardet                   3.0.4                 py37_1003  
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.1            py37h1de35cc_0  
cryptography              2.9.2            py37ha12b0ac_0  
curl                      7.71.0               hbdca1c0_0    conda-forge
icu                       67.1                 h4a8c4bd_0    conda-forge
idna                      2.9                        py_1  
krb5                      1.17.1               hddcf347_0  
libcurl                   7.71.0               he6690cf_0    conda-forge
libcxx                    10.0.0                        1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.3                  h0a44026_1  
libiconv                  1.15              h0b31af3_1006    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libssh2                   1.9.0                h39bdce6_2    conda-forge
libxml2                   2.9.10               hc06c4ae_1    conda-forge
ncurses                   6.2                  h0a44026_1  
openssl                   1.1.1g               h0b31af3_0    conda-forge
pip                       20.0.2                   py37_3  
postgresql                12.2                 h62ab893_1    conda-forge
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.20                       py_0  
pyopenssl                 19.1.0                   py37_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.7                hf48f09d_4  
python.app                2                       py37_10  
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  h1de35cc_0  
requests                  2.23.0                   py37_0  
ruamel_yaml               0.15.87          py37h1de35cc_0  
samtools                  1.4.1                         0    bioconda
setuptools                46.4.0                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h5c1f38d_1  
star                      2.7.5a                        0    bioconda
tk                        8.6.8                ha441bb4_0  
tqdm                      4.46.0                     py_0  
tzcode                    2020a                h0b31af3_0    conda-forge
urllib3                   1.25.8                   py37_0  
wget                      1.20.1               h051b688_0    anaconda
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               h1de35cc_3  
```

After:

```
(base) test|⇒ conda list
# packages in environment at /Users/annar/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py37h9bfed18_1000    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.0            py37h9bfed18_2    conda-forge
cryptography              2.9.2            py37he655712_0    conda-forge
curl                      7.71.0               hbdca1c0_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
htslib                    1.9                  h3a161e8_7    bioconda
icu                       67.1                 h4a8c4bd_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               h14dd6a4_1    conda-forge
libcurl                   7.71.0               he6690cf_0    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libdeflate                1.0                  h1de35cc_1    bioconda
libedit                   3.1.20191231         hed1e85f_0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
libidn2                   2.3.0                h0b31af3_0    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libssh2                   1.9.0                h39bdce6_2    conda-forge
libunistring              0.9.10               h1de35cc_0    conda-forge
libxml2                   2.9.10               hc06c4ae_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
postgresql                12.2                 h62ab893_1    conda-forge
pycosat                   0.6.3           py37h9bfed18_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           cpython_h1fd5dd1_6    conda-forge
python.app                1.3              py37h9bfed18_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h9bfed18_1001    conda-forge
samtools                  1.9                 h8aa4d43_12    bioconda
setuptools                47.3.1           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h93121df_0    conda-forge
star                      2.7.5a                        0    bioconda
tk                        8.6.10               hbbe82c9_0    conda-forge
tqdm                      4.47.0             pyh9f0ad1d_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wget                      1.20.1               h33e2efd_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
yaml                      0.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```

**Comment by AlaaALatif** [comment]
Hello, I tried all the solutions provided here but none of them worked. 
However I did find something that finally worked for me here: https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

Assuming you have Homebrew installed, run the following:

brew update
brew install openssl
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/

I hope this helps some people!

**Comment by agnesngsweetie** [comment]
this works for me ! https://github.com/kelaberetiv/TagUI/issues/86

**Comment by ReneKat** [comment]
Hello All-
I am running on a Mac OSX 10.14.6
I tried all of the fixes mentioned above and in the links, but even updating all the packages still gave me samtools 1.4.1
It wasn't until I specified to conda that I wanted samtools 1.9 that it finally corrected the issue.
What worked for me was:
`conda install -c bioconda samtools=1.9`

It looks like there's also a 1.11 release already. Good luck all!

**Comment by shahramsaghaei** [comment]
If you are using a conda env, simply use 

    conda install -c bioconda samtools openssl=1.0

**Comment by Ethanlee20192019** [comment]
hello, i want to know how did you sovle this error, as i have the exact same problem. i also tried all of the solutions mentioned above, but failed. so i want to ask you for help, thank you very much

**Comment by PolyEsterF** [comment]
I have been experiencing this issue too - and lamunge's solution (conda update --all) worked for me!! Thank you :)

**Comment by HebaHamdyHeikal** [comment]
I tried everything in this page and other pages and the only thing worked for me is:

`conda install -c bioconda samtools=1.14`

Hope this helps others

**Comment by stephenshank** [comment]
Two years later and after still experiencing this issue, I've migrated to miniconda/mamba for package management, as opposed to vanilla conda. I am very happy thus far. 

I just tried creating the same environment with both `mamba` and `conda`, and only `conda` uses an out of date `samtools` where this issue is present. It's been fixed for some time, but is not always found by a package manager... especially as more dependencies are added.

**Comment by zengtian2680** [comment]
> 
install samtools 1.14 works for me too. 

other solutions including 
conda install -c bioconda samtools=1.9    and   conda install -c bioconda samtools openssl=1.0 didn't solve my problem on MacOS Monterey.

**Comment by douglas-hoen** [comment]
> Two years later and after still experiencing this issue, I've migrated to miniconda/mamba for package management, as opposed to vanilla conda. I am very happy thus far.
> 
> I just tried creating the same environment with both `mamba` and `conda`, and only `conda` uses an out of date `samtools` where this issue is present. It's been fixed for some time, but is not always found by a package manager... especially as more dependencies are added.

Another 1.5 years later and the issue still persists. I am abandoning anaconda permanently.

**Comment by SquashMeister** [comment]
if using macos install samtools with brew

brew install samtools

this worked for me and I had the same issue.
