### ISSUE TITLE
conda clean --lock

### ISSUE THREAD

**Issue by dpryan79** [conda/conda#8104]
Starting in version 4.6.0 `conda clean --lock` no longer works and instead returns:

    ArgumentError: At least one removal target must be given. See 'conda clean --help'

**Comment by SylvainCorlay** [comment]
(Note: this is called in all conda-forge feedstocks)

**Comment by dpryan79** [comment]
I foresee this getting a `won't fix` label, though the option itself should be removed from the CLI.
