### ISSUE TITLE
conda init messes up .bash_login

### ISSUE THREAD

**Issue by petergacs** [conda/conda#8105]
conda init puts a block of commands into my .bash_login file.  After this, when I start Aquamacs, it reports that it cannot retrieve the environment from my shell.  This block is the only culprit, but since it involves commands by several indirections, I don't know which part of it is responsible.  
Does the block serve any other purpose than putting anaconda3/bin into the path?

__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/gacs/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/gacs/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/gacs/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/gacs/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup

**Comment by zgoda-mobica** [comment]
I got this with 2018.12 on OS X.

**Comment by niderhoff** [comment]
This block puts the conda binary itself in the path first (so it is accessible even when all environments are deactivated) -- which is a fine behaviour, I think. And then it also puts all the binaries from the base env (i.e. anaconda3/bin) inside the path, which is prone to generate errors. Especially on mac where default python is v2.7.10.
