### ISSUE TITLE
Docs links to miniconda installers and cheatsheet dead

### ISSUE THREAD

**Issue by franckalbinet** [conda/conda#8124]
Hi,

The links to:
* miniconda installers `https://conda.io/miniconda.html` in that page for instance `https://docs.conda.io/projects/continuumio-conda/en/latest/user-guide/install/macos.html` and 
* to the conda-cheatsheet  `https://conda.io/docs/_downloads/conda-cheatsheet.pdf`

are now not available anymore.

We can still find them directly from here `https://repo.continuum.io/miniconda/` and `http://know.continuum.io/rs/387-XNW-688/images/conda-cheatsheet.pdf`

Nevertheless, I wanted to check that they have been deleted on purpose?

Thanks a lot!

**Comment by soapy1** [comment]
We are currently restructuring some of the docs. Miniconda should be back up at conda.io/miniconda and the cheatsheet should be moved under the conda project docs at https://conda.io/projects/continuumio-conda/en/latest/user-guide/cheatsheet.html

**Comment by franckalbinet** [comment]
Well noted! 
Thanks a lot for your prompt response/support.
