### ISSUE TITLE
can not update conda itself

### ISSUE THREAD

**Issue by thu1911** [conda/conda#8133]
I have installed anaconda (version 1.6.5) and the version of conda is 4.4.30. I want to update the conda itself to current version so I run:
`conda update conda`
The output is:

> Fetching package metadata .............
>Solving package specifications: .

>\# All requested packages already installed.
>\# packages in environment at /home/user/software/anaconda3:
>\#
>conda                     4.3.30           py36h5d9f9f4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**But the current version of conda is 4.5.12**

Could you please tell me how to solve this problem?

**Comment by soapy1** [comment]
Can you share the output of `conda info` and the contents for `~/.condarc`

**Comment by thu1911** [comment]
> Can you share the output of `conda info` and the contents for `~/.condarc`

Thank you for your help. The info of `conda info` is 

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/user/software/anaconda3  (writable)
    default environment : /home/user/software/anaconda3
       envs directories : /home/user/software/anaconda3/envs
                          /home/user/.conda/envs
          package cache : /home/user/software/anaconda3/pkgs
                          /home/user/.conda/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/user/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/3.10.0-693.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17    
                UID:GID : 1003:1003


The content of `.condarc` is:

channels:
  \- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  \- defaults
