### ISSUE TITLE
"conda install Pypdfocr" not available

### ISSUE THREAD

**Issue by WeiDuan1985** [conda/conda#8138]
Hi, There

I am trying to install pypdfocr lib in conda but I got the below error. I then went to  https://anaconda.org to search for this package but it's available.

Could you please help me out?

![image](https://user-images.githubusercontent.com/42089856/51685370-14001680-1fe6-11e9-8de4-6fef78365e4b.png)

**Comment by soapy1** [comment]
It doesn't look like the package you want is available on anaconda.org but you can give building the package a shot 😃 
https://docs.conda.io/projects/conda-build/en/master/source/recipe.html

![screen shot 2019-01-25 at 10 49 11 am](https://user-images.githubusercontent.com/976973/51759923-f5a22580-208e-11e9-9faa-052043ef8ed1.png)
