### ISSUE TITLE
How to fully specify the details of an environment from a config file

### ISSUE THREAD

**Issue by 3tilley** [conda/conda#8142]
Good afternoon,

To power our cross-platform corporate environment we would like the ability to specify all of the details of a conda environment within a configuration file. These files would then be checked into source control along with their corresponding projects. Currently I don't believe this is possible, but please correct me if I'm wrong. We'd like to be able to build an environment in one short command with a specified:
* Name
* Directory
* Conda and pip packages
* (potentially .condarc details?)

Is there a feature to do this? If this isn't currently possible, we would be able to contribute to the development effort, especially if it results in cleaning up the `conda create` vs `conda env create` situation.

**Comment by soapy1** [comment]
Conda does support this! https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually. You can specify the name of the environment, the prefix/directory to install into, and conda & pip packages. Currently it does not support .condarc details

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/7248

**Comment by kalefranz** [comment]
@soapy1 and the Anaconda team are working on paths forward to address #7248.
