### ISSUE TITLE
WARNING: A newer version of conda exists.

### ISSUE THREAD

**Issue by lundybernard** [conda/conda#8162]
## Current Behavior

`conda update conda` stuck at `A newer version of conda exists` but will not update it

### Steps to Reproduce

```
> conda update -n base -c defaults conda
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

> conda update -n base -c defaults conda
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

```

## Expected Behavior

Following the provided directions to update, should result in conda being updated.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /home/lbernard/miniconda3
            shell level : 1
       user config file : /home/lbernard/.condarc
 populated config files : /home/lbernard/.condarc
          conda version : 4.5.11
    conda-build version : 3.14.0
         python version : 3.5.5.final.0
       base environment : /home/lbernard/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/lbernard/miniconda3/pkgs
                          /home/lbernard/.conda/pkgs
       envs directories : /home/lbernard/miniconda3/envs
                          /home/lbernard/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.5.5 Linux/4.15.0-43-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by lundybernard** [comment]
## Solution:
Update python on the base env

`(base) self@home:~ > conda update python`

Updating python on the base environment updated many packages including:
`conda:                4.5.11-py35_0                      --> 4.6.1-py36_0`

and resolved this issue.


Reported for anyone else who runs into this.

**Comment by StevenCHowell** [comment]
I have this same version of conda, 4.5.11-py35_0, and I am getting the same error from above.  When I try updating python, the process runs with no progress for over 10 minutes.  Nothing had changed by the time I stopped it, around 15 minutes.

**Comment by odelalleau** [comment]
@StevenCHowell it seems it can indeed take a long time if you have many libraries to update, so just let it run for however long it needs.

**Comment by rsignell-usgs** [comment]
Instead of waiting around for your base env to update, you also can just blow it away and start over (in my case I didn't want all the old envs in my ~/miniconda3/envs directory anyway): 
```
if [[ $(uname) == "Darwin" ]]; then
  url=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
elif [[ $(uname) == "Linux" ]]; then
  url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
fi
curl $url -o miniconda.sh
bash miniconda.sh -b
export PATH=$HOME/miniconda3/bin:$PATH
```

**Comment by haoruilee** [comment]
When I try to update python, there still remains "newer version exists"  

Info:

(notebookenv) C:\windows\system32>conda update python
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda
