### ISSUE TITLE
[conda 4.6] activate fails due to unbound PS1 in bash strict mode

### ISSUE THREAD

**Issue by s22chan** [conda/conda#8186]
## Current Behavior

Similar to https://github.com/pypa/virtualenv/issues/1029, the newer version of `conda` (`4.5.x` is fine) doesn't work on `circleci` due to activate accessing `PS1`, which may not be set.

### Steps to Reproduce
```
docker run -it continuumio/miniconda3 /bin/bash -eo pipefail
conda update -y conda
export BASH_ENV=~/env.sh
echo ". /opt/conda/etc/profile.d/conda.sh" >> $BASH_ENV
echo "set -euo pipefail; conda activate" | bash
/opt/conda/etc/profile.d/conda.sh: line 26: PS1: unbound variable
```

## Expected Behavior
conda interpolates PS1 via:
```
${PS1:-}
```

## Environment Information
```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.6.1
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.1 requests/2.21.0 CPython/3.7.1 Linux/4.4.0-93-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by s22chan** [comment]
for whatever reason, https://github.com/conda/conda/blob/8eeb1bba428cceb56c6dae120c51e35b3332b854/conda/shell/etc/profile.d/conda.sh#L64 doesn't work

**Comment by Matt-BF** [comment]
My crude workaround to this problem was to change line 26 of conda.sh to `
${PS1:-}`, and lines 1 and 4 of java_home.sh to `${JAVA_HOME:-}` and `${JAVA_LD_LIBRARY_PATH:-}`

For now it seems to be working ok but I'm not sure if I'm braking it further and it might cause problems in the near future

**Comment by pbordron** [comment]
Hi,

I get the same error with conda 4.6.8 when loading a conda environment with snakemake 5.2.2 (with a `source activate` in the `shell` part instead of using the `conda` field)

The workaround replacing line 26 in `CONDA_ROOT/etc/profile.d/conda.sh` by the following solves the issue:
```
 ask_conda="$(PS1="${PS1:-}" "$CONDA_EXE" shell.posix "$cmd" "$@")" || \return $?
```

**Comment by Matt-BF** [comment]
@pbordron yeah, my issue also arose because of snakemake with source activating the script

**Comment by stolpeo** [comment]
Same here when activating conda from within a shell script with `-u` flag. Is there a bugfix planned? My current fix is inserting `export PS1=` in the shell script that activates conda.

**Comment by yesimon** [comment]
It seems there are more errors beyond `PS1`. My current workaround is `set +eu` before calling `source activate` and `set -eu` afterwards (if desired).

**Comment by GuidoBarzaghi** [comment]
I had the same issue using NextFlow and I'm happy to have quickly solved the problem using @yesimon's solution :)

**Comment by hdetering** [comment]
@yesimon's workaround worked for me as well. Any chance of fixing the underlying problem, though?

**Comment by morales-gregorio** [comment]
Running into the same problem here, also using snakemake to source an environmnet from a bash script. My conda version is `4.10.1` installed with miniconda3.
