### ISSUE TITLE
[4.6.2] Regression with conda env create -n NAME

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8192]
When I try the `conda env create -n NAME -f environment.yml` command with a non-existent yml file (i.e. from the wrong directory) I get an inscrutable `SpecNotFound` error:
```
(base) C:\dev\code> conda env create -n py-dev -f quantdev.yml

SpecNotFound: Invalid name, try the format: user/package

(base) C:\dev\code>
```

It seems this problem has cropped up previously (#5681) and was supposed to have been fixed in #7385 so this appears to be a regression?

**Comment by dhirschfeld** [comment]
```
(base) C:\dev\code> conda info

     active environment : base
    active env location : C:\Miniconda3
            shell level : 1
       user config file : C:\Users\dhirschfeld\.condarc
 populated config files : C:\Users\dhirschfeld\.condarc
          conda version : 4.6.2
    conda-build version : 3.17.7
         python version : 3.7.1.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          http://conda.stanwell.com/conda-forge/win-64
                          http://conda.stanwell.com/conda-forge/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\dhirschfeld\.conda\pkgs
                          C:\Users\dhirschfeld\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\dhirschfeld\.conda\envs
                          C:\Users\dhirschfeld\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.7.1 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by javabrett** [comment]
I've spotted some bugs in https://github.com/conda/conda/blob/master/tests/conda_env/test_cli.py which result in regressions such as this not being picked-up.

**Comment by msarahan** [comment]
Care to detail those bugs?  What tests would be good to add?

**Comment by javabrett** [comment]
The main line of test code I'm concerned about (or at least don't understand) is L90:

https://github.com/conda/conda/blob/2b403a80149b088d234b48b1c77c288c5fb74fa4/tests/conda_env/test_cli.py#L88-L92

... which seems to feed the env name or prefix to `conda env create -f ...` - should that be `-n`?  Fixing that will require some unrelated test fixes.

Then in:

https://github.com/conda/conda/blob/2b403a80149b088d234b48b1c77c288c5fb74fa4/tests/conda_env/test_cli.py#L168-L177

... will that fail if the exception is _not_ thrown?  Seems like it wants a `with pytest.raises`.  Same for `test_conda_env_create_no_file`.

In looking at these - calls to:

https://github.com/conda/conda/blob/2b403a80149b088d234b48b1c77c288c5fb74fa4/conda_env/specs/__init__.py#L15-L17

e.g.

https://github.com/conda/conda/blob/2b403a80149b088d234b48b1c77c288c5fb74fa4/conda_env/cli/main_create.py#L71-L78

- combine env name and `remote_definition`, making them harder to distinguish in the logic for `name`
- pre-default file to `environment.yml`, making it hard to know whether it has been set

Please comment on whether any/all of the above look like valid concerns.

**Comment by javabrett** [comment]
Possible initial fix was incomplete, rather than a regression.  Note issue is specific to `-n NAME` being supplied.

```
$ docker run -it --rm conda/miniconda3 conda --version
conda 4.6.4
$ docker run -it --rm conda/miniconda3 conda env create -f not_a_file.txt

EnvironmentFileNotFound: '/not_a_file.txt' file not found

$ docker run -it --rm conda/miniconda3 conda env create -n named -f not_a_file.txt

SpecNotFound: Invalid name, try the format: user/package
```

So works as expected for invalid `-f`, but not if `-n` also specified.
