### ISSUE TITLE
conda 4.6 seems to give incorrect channel priority

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#8204]
@isuruf mentioned on gitter than conda 4.6.1 is suggesting packages for upgrade from lower priority channels.  An example which exhibits this behavior with conda 4.6.2:

```
conda create -n test100 -c conda-forge -c defaults conda-build conda-smithy conda-forge-pinning
conda activate test100
conda update -c conda-forge -c defaults conda-build conda-smithy conda-forge-pinning
```

The suggested upgrade path installed a number of packages from `defaults` which has lower priority than `conda-forge`:

```
~$ conda update -c conda-forge -c defaults conda-build conda-smithy conda-forge-pinning
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.1
  latest version: 4.6.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jhelmus/anaconda3/envs/test100

  added / updated specs:
    - conda-build
    - conda-forge-pinning
    - conda-smithy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    git-2.19.1                 |  pl526hacde149_0        11.4 MB  defaults
    icu-58.2                   |    hf484d3e_1000        22.6 MB  conda-forge
    krb5-1.14.6                |                0         4.0 MB  conda-forge
    libarchive-3.3.3           |       h5d8350f_2         1.5 MB  defaults
    libssh2-1.8.0              |                1         239 KB  conda-forge
    libxml2-2.9.8              |    h143f9aa_1005         2.0 MB  conda-forge
    lz4-c-1.8.3                |    hf484d3e_1001         187 KB  conda-forge
    lzo-2.10                   |    h14c3975_1000         319 KB  conda-forge
    openssl-1.1.1a             |    h14c3975_1000         4.0 MB  conda-forge
    zstd-1.3.3                 |                1        1023 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        47.2 MB

The following NEW packages will be INSTALLED:

  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-hf484d3e_1001
  lzo                conda-forge/linux-64::lzo-2.10-h14c3975_1000
  zstd               conda-forge/linux-64::zstd-1.3.3-1

The following packages will be UPDATED:

  expat              conda-forge::expat-2.2.5-hf484d3e_1002 --> pkgs/main::expat-2.2.6-he6710b0_0
  openssl                              1.0.2p-h14c3975_1002 --> 1.1.1a-h14c3975_1000
  python             conda-forge::python-3.7.1-hd21baee_10~ --> pkgs/main::python-3.7.2-h0371630_0

The following packages will be SUPERSEDED by a higher-priority channel:

  cryptography       conda-forge::cryptography-2.5-py37hb7~ --> pkgs/main::cryptography-2.4.2-py37h1ba5d50_0
  curl               conda-forge::curl-7.63.0-h646f8bb_1000 --> pkgs/main::curl-7.62.0-hbc83047_0
  git                conda-forge::git-2.20.1-pl526hc122a05~ --> pkgs/main::git-2.19.1-pl526hacde149_0
  libarchive         conda-forge::libarchive-3.3.3-ha149a2~ --> pkgs/main::libarchive-3.3.3-h5d8350f_2
  libcurl            conda-forge::libcurl-7.63.0-h01ee5af_~ --> pkgs/main::libcurl-7.62.0-h20c2e04_0

The following packages will be DOWNGRADED:

  krb5                                 1.16.3-hc83ff2d_1000 --> 1.14.6-0
  libssh2                               1.8.0-h1ad7b7a_1003 --> 1.8.0-1


Proceed ([y]/n)? n
```

**Comment by jjhelmus** [comment]
This is not a new behavior in conda 4.6, conda 4.5.12, 4.5.11 and 4.4.11 all produces the same or similar solutions for the update.

**Comment by jjhelmus** [comment]
The note about `SUPERSEDED by a higher-priority channel` in the Package Plan is an incorrect statement.  That status if shown when a package changes to a lower version and changes channels regardless of which channel has higher priority.  In the example `conda-forge` does have higher priority than `pkgs/main`.

For some reason `ca-certificates`, `certifi` and `openssl` are being included as requested packages in the `conda update ...` command.  When `openssl` is a requested package the solver maximizes the version, even when it requires a package from a lower priority channel.  The maximum version of `openssl` in `defaults` and `conda-forge` is 1.1.1a which only exists in `defaults`.  This causes this package to be selected which in turn pulls in the other packages.

**Comment by msarahan** [comment]
IIRC, there's a hardcoded list of things to always try to update.  This is probably an undesirable side effect.  Openssl needs to behave the same as any other - no bypassing the other rules.

**Comment by msarahan** [comment]
sure, but aggressive updates should still respect channel priority, IMHO.  Do you think otherwise?

**Comment by isuruf** [comment]
FYI, openssl 1.1.1a is coming from conda-build. It's just that none of the other conda-forge packages are using it

**Comment by jjhelmus** [comment]
> sure, but aggressive updates should still respect channel priority, IMHO. Do you think otherwise?
I believe channel priority is being respected in this case.   As @isuruf pointed out openssl 1.1.1a is coming from conda-forge, with "flexible" channel priority conda will select packages from lower priority channels to fulfill a dependency in a higher priority channel.  In this case the solver uses the python, cryptography,  curl, git, libarchive, and libcurl package from `pkgs/main` to meet the openssl 1.1.1a requirement.  

With "strict" channel priority no change is suggested for the environment since the highest priority channel cannot provide packages for openssl 1.1.1a.

**Comment by msarahan** [comment]
Oh, I see.  Indirect vs explicit deps.  That makes sense.  What a crazy "corner" case.  As much of a corner as centrally important packages can be, I guess.

Is there a change we should make here, or just recommend "strict" channel priority?

**Comment by jjhelmus** [comment]
What seems inconsistent to me is that the `conda create ...` does not aggressively select the latest versions of `openssl`, etc where as `conda update ...` does.  This is tricky because until the environment has been solved, it is not known if these packages will be included.

**Comment by jjhelmus** [comment]
> Is there a change we should make here, or just recommend "strict" channel priority?

I think recommending `aggressive_update_packages: []` be used when building packages and for power users is a good idea, similar to `add_pip_as_python_dependency: false`.  Most users want the defaults but those who know more about the ins and outs of conda need more fine grained control.  

I can also see an argument for limiting the aggressive updates of openssl to those within the same release version (1.0.2h will update to 1.0.2p but not 1.1.1a).

**Comment by msarahan** [comment]
> I can also see an argument for limiting the aggressive updates of openssl to those within the same release version (1.0.2h will update to 1.0.2p but not 1.1.1a).

This sounds right to me.  We should special-case openssl right now, but probably should come up with a different more general scheme for packages to indicate this upgrade behavior.  Probably aggregate it at the channeldata.json level.

**Comment by wdirons** [comment]
I am seeing different behavior between conda 4.5.12 and 4.6.2 regarding the SUPERSEDED behavior. Let me know if this should be opened in a new issue.

I first observed this trying to install a custom package that pre-reqs numpy>=1.12.0, however it can be re-created just by installing numpy

Install ananconda3 2018.12 and run the following commands:

```
conda create -n test_env python=3.6 numpy
conda activate test_env
conda install 'numpy>=1.12.0'
conda update -n base -c defaults conda
conda install 'numpy>=1.12.0'
```


**When 4.5.12 was installed, numpy was ok:**
```
(test_env) [builder@f80226b86cbc /]$ conda install 'numpy>=1.12.0'
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.2

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.
```


**Upgrade to 4.6.2**
```
(test_env) [builder@f80226b86cbc /]$ conda update -n base -c defaults conda
Solving environment: done

## Package Plan ##

  environment location: /home/builder/anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.6.2                |           py37_0         1.7 MB

The following packages will be UPDATED:

    conda: 4.5.12-py37_0 --> 4.6.2-py37_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.6.2          | 1.7 MB    | #################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


```
**Retry the same command to install numpy>=1.12.0, and numpy will be downgraded.**
```
(test_env) [builder@f80226b86cbc /]$ conda install 'numpy>=1.12.0'
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/builder/anaconda3/envs/test_env

  added / updated specs:
    - numpy[version='>=1.12.0']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.12.0               |           py36_0        10.3 MB
    ------------------------------------------------------------
                                           Total:        10.3 MB

The following packages will be REMOVED:

  blas-1.0-openblas
  numpy-base-1.15.4-py36h2f8d375_0

The following packages will be SUPERSEDED by a higher-priority channel:

  numpy              pkgs/main::numpy-1.15.4-py36h99e49ec_0 --> pkgs/free::numpy-1.12.0-py36_0


Proceed ([y]/n)?

```

**Comment by jjhelmus** [comment]
@wdirons I believe the issue you are seeing is different than the one here.  I have some ideas but a creating a separate issue with the output from `conda list --show-channel-urls` should help to nail it down.

**Comment by wdirons** [comment]
#8236 was opened for the issue I posted above.

**Comment by Dschoni** [comment]
@jjhelmus could [this issue](https://stackoverflow.com/questions/55825960/updating-conda-leads-to-downgrade-and-superseded-packages) I'm having be related?
