### ISSUE TITLE
Powershell prompt doesn't work with cmder

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8213]

**Comment by dennispg** [comment]
I submitted a pull request for this. Use `conda config --set changeps1 false` and then in cmder or posh-git or whatever else, configure your prompt however you want by reading from `$Env:CONDA_DEFAULT_ENV`.

**Comment by musm** [comment]
Yeah the prompt is not modified when activating environments.

**Comment by dennispg** [comment]
@dhirschfeld I can confirm the change in my pull request work great for cmder with PowerShell, are you also able to confirm?

I think this can be closed now.

**Comment by apwebb** [comment]
Hello, I may be missing something but I am still having these issues with conda/cmder/powershell/pwsh.
Specifically, I cannot properly activate/deactivate environments, although other basic conda commands (eg. install, list, env list) work fine. I just stay in the base environment.  I have run `conda init powershell`. The value of `changeps1` doesn't seem to matter. Further, importing the conda.psm1 module from shell\condabin throws the following error on usage in pwsh/powershell through cmder, but not native pwsh/powershell, where they work fine. The below error is thrown for any command from the module. 

System: Microsoft Windows 10 Pro 10.0.17763
Cmder: 1.3.11
Powershell: 5.1.17763.316
Powershell Core: 6.2.0
Conda: 4.6.14 (miniconda3 installed via scoop)

```
❯ import-module $HOME\scoop\apps\miniconda3\current\shell\condabin\conda.psm1
❯ genv
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
At ~\scoop\apps\miniconda3\current\shell\condabin\conda.psm1:23 char:11
+         & $Env:CONDA_EXE $Env:_CE_M $Env:_CE_CONDA env list | `
+           ~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : BadExpression
```
FWIW, conda-hook.ps1 appears to be set correctly (only CONDA_EXE is set to a non-empty string and it is the correct path), which makes sense if it all works with native pwsh/powershell

**Comment by dennispg** [comment]
Yes, the step you are missing is executing `conda-hook.ps1`. (That, or setting those environment variables one way or another yourself..)

To give a more detailed explanation.. `conda init powershell` inserts a call to `conda-hook.ps1` into your PowerShell profile. Cmder however has it's own notions of profile, and does not load the standard PowerShell profile.

You'll have to research how to customize cmder to do this for you.

Hope that helps!

@msarahan Can this be closed?

**Comment by marckassay** [comment]
Although this issue is related to cmder, similarly with posh-git, along with the 2 comments above by @dennispg one can add this to their powershell profile (Get-Item $PROFILE):
```shell
Import-Module posh-git

$GitPromptSettings.DefaultPromptPrefix.Text = "($Env:CONDA_DEFAULT_ENV) "
```
