### ISSUE TITLE
sparkmagic conda repo is behind pip

### ISSUE THREAD

**Issue by Tagar** [conda/conda#8214]
There was a new release of sparkmagic last week.

pip shows `0.12.7` 
https://pypi.org/project/sparkmagic/ 

conda shows `0.12.6` as latest 
https://anaconda.org/search?q=sparkmagic

How often does conda pull pip packages into conda repos? 
Or it has to happen manually? 
`sparkmagic` package committer isn't sure too - [see comment here](https://github.com/jupyter-incubator/sparkmagic/pull/483#issuecomment-459586349).

**Comment by ericdill** [comment]
Updates to the defaults channel happen as the conda team has time. Updates to the [conda-forge channel](https://github.com/conda-forge/sparkmagic-feedstock) can be done by anyone willing to submit a pull request

**Comment by Tagar** [comment]
thanks @ericdill !
