### ISSUE TITLE
Tab complete environments

### ISSUE THREAD

**Issue by moorepants** [conda/conda#822]
virtualenvwrapper has the really nice `workon` command line command to easily switch environments. `workon` even tab completes environment names so you don't have to remember them. Is there any way that a workon command could be created for conda environments with tab completion?

**Comment by anderson-dan-w** [comment]
@asmeurer did you mean [these lines](https://github.com/asmeurer/dotfiles/blob/8bcba698cde26cf81e765d456dddc20cf0d1865f/.profile#L370-L384)? Seems like you may've changed your `.profile` so they don't seem to point somewhere reasonable

**Comment by asmeurer** [comment]
Yep those are the lines. Forgot to press `y` before I copied the URL I guess.
