### ISSUE TITLE
.\path\to\ba se\prefix\Scripts\activate doesn't work with spaces in .\path\to\ba se\prefix

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#8224]
### Steps to Reproduce

```
(base) C:\Users\Wani>conda create -yp ".\mc 3" conda=4.6.2

:Close prompt, reopen
C:\Users\Wani>cd scratch

C:\Users\Wani\scratch>"mc 3\Scripts\activate"

(base) C:\Users\Wani\scratch>conda
'C:\Users\Wani\scratch\mc' is not recognized as an internal or external command,
operable program or batch file.
```

## Expected Behavior

Conda should work regardless of whether there is a space in base prefix path or not.

**Comment by nehaljwani** [comment]
xref: https://groups.google.com/a/continuum.io/d/msg/anaconda/jHyb8uvIOnc/y7gPbieHGAAJ

**Comment by msarahan** [comment]
I think this is also being worked on in https://github.com/conda/conda/pull/8215
