### ISSUE TITLE
Conda init (at least on Windows) does not allow explicitly activating another base environment

### ISSUE THREAD

**Issue by ronaldsipkema** [conda/conda#8234]
## Current Behavior

After I have initialized my main conda environment using `conda init` it is not possible to activate an environment from a different conda install (e.g., another miniconda install or a custom 'software distribution' installed using an installer created using constructor). I usually activated such an environment by calling `path\to\base\prefix\Scripts\activate.bat path\to\base\prefix`. After initializing my main conda this now results in `conda info` reporting the `base environment`, `package cache', and `envs directories` from my main (initialized) conda install.

## Expected Behavior

I would expect that -- even when there is a 'initialized' conda installation on the system that when activating an environment by explicitly calling the activate script from another base that the conda executable (or batch file) from that installation would be used.

**Comment by kalefranz** [comment]
We’ve had some arguments back and forth about named environments vs referring to environment locations via relative paths. For now, use `activate .\path\to\prefix` for relative paths, or just use full absolute paths. Also prefer ’

**Comment by ronaldsipkema** [comment]
> For now, use `activate .\path\to\prefix` for relative paths, or just use full absolute paths. Also prefer the `conda activate` command to `activate.bat`, which will someday be deprecated.

OK, good to know. But my issue is not necessarily with activating an environment on an absolute path, but how to cope with multiple installs of conda on the same system, where from one of these installs `conda init` was run to make conda available on the command prompt by default (Windows, haven't checked any other OS). What I'm trying to figure out is how in this situation I can activate a conda environment for the conda install that has not been initialized. I would hope / expect that by explicitly calling `some\prefix\condabin\conda.bat activate \path\to\prefix` the relevant environment variables (CONDA_EXE, CONDA_BAT and CONDA_SHLVL as far as I can tell) would be updated to correctly reflect the new base environment. What happens now is that the environment does get updated, but these variables (and CONDA_PYTHON_EXE) refer to the base environment of the other installation.

I guess in short what I'm trying to say is that after calling `conda init` there is no support anymore for different conda installations, even when calling a different conda explicitly.

An example use case would be the possibility to still support a custom install (built using constructor) even if the user has his / her own miniconda installation and has previously called `conda init`. Note that if the support of multiple installs is possible, then this would also mean the 'Anaconda Prompt' shortcut (via wininst) would have to be updated not to use the deprecated `activate.bat` but use a conda command instead.

**Comment by SBYGIS** [comment]
###### Larger issue at hand with conda init.  

Had an issue were my python environment became corrupt and had to uninstall Anaconda3.  Was unable to install or update packages (I believe because openssl was conflicting with certifi and ca-certificates).  With the latests shell hooks now anaconda now binds to cmd.exe and creates hooks to WindowsPowershell\profile.ps.1.  When uninstalling Anaconda those entries remained and caused unintended issues with the Windows PATH.  It took a while to figure out, but while I was without Anaconda any terminal session had an 

```batch
error 'C:\Program' is not recognized as an internal or external command
```

The next issue in trying to reinstall Anaconda3 was that the conda.exe was missing from the installer...  I then resorted to installing Miniconda3.  Used ```conda update conda``` but still to my surprise ```conda init powershell``` still required manual modification to the profile.ps1 file to fully direct to the new miniconda installation by changing Anaconda3 to Miniconda3 in the profile.ps1.

**Comment by msarahan** [comment]
On Windows, we've developed a package that allows you to run conda in powershell without running conda init.  We agree that the global modification makes a mess, and we're working on cleaning it up better (see #8400)

In the meantime, you should be able to ``conda install powershell_shortcut`` to use the alternative way that does not require conda init.  It has not seen much testing, so any feedback you have is welcome and appreciated.

**Comment by SBYGIS** [comment]
@msarahan 
Really appreciate the quick reply.  I'll look into the powershell_shortcut package.  Realistically i've had a bandaid powershell script in my ```anacodna\scripts``` directory that provided a similar result as the deprecated ```activate.bat```.  Just wanted to give you guys a heads up to the need for reverting ```conda init``` behavior upon uninstall.

**Comment by histed** [comment]
> OK, good to know. But my issue is not necessarily with activating an environment on an absolute path, but how to cope with multiple installs of conda on the same system, where from one of these installs `conda init` was run to make conda available on the command prompt by default (Windows, haven't checked any other OS). What I'm trying to figure out is how in this situation I can activate a conda environment for the conda install that has not been initialized. 

> I guess in short what I'm trying to say is that after calling `conda init` there is no support anymore for different conda installations, even when calling a different conda explicitly.

I have this same problem on MacOS X: with two anaconda installations in ~/anaconda36 and ~/anaconda37, only one of them can be activated by conda after ````conda init````.
Workaround: don't use conda init and go back to source ~/anaconda3x/activate env

conda 4.6.14
