### ISSUE TITLE
Request: Python site-packages environment variable

### ISSUE THREAD

**Issue by teake** [conda/conda#8235]
For legacy reasons I have to determine the Python site-packages directory for the current conda environment. I know I can do this as easy as [for example](https://stackoverflow.com/a/43967692/2427624)

```shell
$ python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
```

But does it make sense to expose this as a conda environment variable, e.g. `CONDA_SP_DIR`?
(Conda-build exposes `SP_DIR` during build, but I need it _after_ building a package). I'd be happy to put in a PR for this.

**Comment by kalefranz** [comment]
For me, it’s too much of a special case. Special cases are handled at the package level, not hard-coded within conda itself. We can have the python package set something like that, or you can create your own package that depends on python that sets that variable in an activate.d script. Hard-coding this in conda itself would affect activation times for everybody, whether they use the feature or not and even whether they’re using python or not.

**Comment by teake** [comment]
That's indeed a valid argument not to do this. Closing.

I think I'll roll my own package for this. Btw, how do I keep tabs on whether this will eventually land in the defaults Python package?

**Comment by kalefranz** [comment]
All of the `defaults` recipes are at github.com/AnacondaRecipes. They’re all forks of `conda-forge` now, with `conda-forge` being upstream of `defaults`.

**Comment by teake** [comment]
Thanks for swift reply, I did not know that. Will check it out!
