### ISSUE TITLE
Sign powershell conda module

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#8242]
Starting conda 4.6, conda init uses 3 powershell files for the supporting conda init:
- Profile file written to $PROFILE <--- equivalent of a .rc file (which calls hook script)
- \path\to\installation\dev\shell\condabin\conda-hook.ps1 <--- hook script (which basically imports module)
- \path\to\installation\dev\shell\condabin\Conda.psm1 <---- conda module

Now, after running conda init, the first thing a user sees on spawning powershell is:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

. : File C:\Users\Wani\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\Wani\Documents\WindowsPowerShell\Microsoft.PowerShell_pro ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
Users can choose to ignore this by setting their execution policy to some non restrictive value, or ...

One can overcome this problem by having just one signed file: Conda.psm1 and place it at `%UserProfile%\Documents\WindowsPowerShell\Modules\Conda` or `%ProgramFiles%\WindowsPowerShell\Modules\Conda`, as described [here](https://github.com/conda/conda/pull/6471#issuecomment-380505445). PowerShell (at least on Windows), auto searched this directory and loads it. Also, this file cannot have any string containing the path to the miniconda location, which means, it can't be auto generated (because it needs to be signed). So, one can possibly make it fetch the location of conda installation location from perhaps the windows registry. Something like this:
```diff
@@ -118,6 +114,17 @@ function Exit-CondaEnvironment {
         conda install toolz
 #>
 function Invoke-Conda() {
+    # Check if $CONDA_EXE is already set. If not, get it from registry
+    if (-not (Test-Path Env:CONDA_EXE)) {
+        $Env:CONDA_EXE = CondaFromRegistry;
+    }
+    if (-not (Test-Path Env:CONDA_EXE)) {
+        [Console]::Error.WriteLine(@"
+Unable to locate conda!
+Please run "\path\to\installation\Scripts\conda.exe" init
+"@)
+        return;
+    }
     # Don't use any explicit args here, we'll use $args and tab completion
     # so that we can capture everything, INCLUDING short options (e.g. -n).
     if ($Args.Count -eq 0) {
@@ -244,6 +251,19 @@ function prompt() {
     CondaPromptBackup;
 }

+function CondaFromRegistry() {
+    $_conda_reg_paths = @(
+        "HKCU:\SOFTWARE\Microsoft\Conda",
+        "HKLM:\SOFTWARE\Microsoft\Conda")
+    for ($i = 0; $i -lt $_conda_reg_paths.length; $i++) {
+        If (Test-Path -Path $_conda_reg_paths[$i]) {
+            If (Get-ItemProperty -Path $_conda_reg_paths[$i] -Name exe -ErrorAction SilentlyContinue) {
+                return (Get-ItemProperty -Path $_conda_reg_paths[$i] -Name exe).exe
+            }
+        }
+    }
+}
+
```

I paused at this point. The current implementation of conda init for powershell seems to be quite generic (which I'd hate to break). Also, there doesn't seem to be an easy way to find out the modules directory in a generic fashion. xref: https://github.com/PowerShell/PowerShell/issues/7082#issuecomment-438463574

What should be the path from here? Thoughts? Concerns? Ideas?

**Comment by msarahan** [comment]
IMHO sacrificing some generic behavior here in favor of being able to sign is a worthwhile trade-off.  I think we should continue down the path you're heading, and open an issue for discussion on ideas of how to maintain ability to sign while expanding generic capabilities and ways to support multiple conda installations with just the one powershell script.

One thing I'll say is that setting an env var may keep more flexibility than using the registry.  Since env vars can be local to a given prompt session, they can be used to flip between installations more readily than a single value in the registry.
