### ISSUE TITLE
conda raises bogus NotWritableError exception for a bogus attempt to chown to root

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda#8243]
This isn't a dupe (well it is a dupe of #7109) but the issue still persists.

#7180 fixed the problem in one section of code, but the same problematic snippet is present here:

https://github.com/conda/conda/blob/master/conda/gateways/disk/update.py#L121

**Comment by hhuuggoo** [comment]
This is pretty straightforward, and I'd be happy to fix it, I'd just like some feedback from the conda team first.  Thanks!

**Comment by msarahan** [comment]
Sure, it seems like you have a fix identified, and that's most welcome.  Deduplicating code or otherwise fixing this problem would be very helpful, and we'd appreciate it.
