### ISSUE TITLE
source activate issue with older versions of zsh

### ISSUE THREAD

**Issue by mindriot101** [conda/conda#825]
I'm using zsh version 4.3.6 (my work uses SLES). When trying to create a conda environment and source it, I get the following error:

`${HOME}/anaconda/bin/activate:26: no such file or directory: ./conda`

**Steps to reproduce**

```
conda create -n test numpy
source activate test
${HOME}/anaconda/bin/activate:26: no such file or directory: ./conda
```

I suspect it's to do with this code: [https://github.com/conda/conda/blob/2662b2ee002fc549d01911dacdddbf1229b64110/bin/activate#L10-L19](https://github.com/conda/conda/blob/2662b2ee002fc549d01911dacdddbf1229b64110/bin/activate#L10-L19) where the script directory is computed by `_SCRIPT_LOCATION=${funcstack[1]}` which I suspect is not available in my version of zsh.

**Comment by njalerikson** [comment]
with #3175 zsh has been reworked and is properly unittested, this should not be an issue anymore
