### ISSUE TITLE
add environment aggregate data to conda list

### ISSUE THREAD

**Issue by ARF1** [conda/conda#8275]
## Current Behavior
Conda is supposed to hard link environment contents to already existing packages.

On Windows 8, with a single-user install, hard links are not used. Instead a separate copy for each installation is created leading to massive bloat.

### Steps to Reproduce
```
1. get a clear conda install
2. run: conda create -n test1 python pip pyserial
3. check size of conda env directory with windows explorer. Note "size on disk" value.
4. run conda create -n test2 python pip pyserial
5. check size of conda env directory with windows explorer. Note "size on disk" value. This will have doubled meaning the packages were not hard linked despite being identical.
```

## Expected Behavior
Conda should hard link packages.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : Z:\systemfiles\Miniconda3
            shell level : 1
       user config file : C:\Users\User1\.condarc
 populated config files : C:\Users\User1\.condarc
          conda version : 4.6.3
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : Z:\systemfiles\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : Z:\systemfiles\conda\pkgs
       envs directories : Z:\systemfiles\conda\envs
                          Z:\systemfiles\Miniconda3\envs
                          C:\Users\User1\.conda\envs
                          C:\Users\User1\AppData\Local\conda\conda\envs
               platform : win-32
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.2 Windows/8.1
Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\User1\.condarc <==
envs_dirs:
  - Z:\systemfiles\conda\envs
pkgs_dirs:
  - Z:\systemfiles\conda\pkgs
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at Z:\Systemdateien\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.3                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.5              py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pip                       19.0.1                   py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.2                h8c8aaf0_2    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.7.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                h896c600_2    defaults
```
</p></details>

**Comment by kalefranz** [comment]
I see you have a Z: drive as well as a C: drive. Hard links are only possible when the link is from a package cache that’s on the same drive as the environment. If the package cave and environment are on different drives, conda has to fall back to copying. Is that what you’re running into here?

**Comment by kalefranz** [comment]
Other possibilities:

1. Hard links might not be available at all on a particular network mount or a particular file system type. 
2. Windows File Explorer (and Unix `du`) sort of lie about environment sizes. Or they don’t quite understand. The all total up the disk size of each path. They don’t know how to amortize hard link sizes across multiple links.

**Comment by ARF1** [comment]
@kalefranz Thanks for the advice. Please note though, that:

1. my miniconda installation resides in `Z:\systemfiles`
2. my package directory also resides in `Z:\systemfiles`
3. my environment directory also resides in `Z:\systemfiles`

My drive `Z:` is a NTFS formatted internal HDD which I use for "largish" stuff since my `C:` drive is a fairly small SSD.

Also: Windows file explorer normally does not lie about sizes. It shows a "Size:" property which is the sum of all paths (as you suggested) and a separate "Size on disk:" which explicitly takes into account any hard linked files. The latter will be lower if the checked path contains any hard linked files.

I am convinced that conda is not hard linking. If you are not at this point, can you suggest a way to test this to your satisfaction?

By the way, Windows file explorer used to show the right "size on disk" for previous versions of conda. I last checked a few years back and only stumbled across this issue because anaconda was eating up all my disk space... After multiple reinstalls and experiments, I concluded that the hard linking logic must be broken somehow.

**Comment by kalefranz** [comment]
The best test would be:

1. check total free space on the drive
2. create a new environment that you expect to use hard links from the package cache
3. check total free space on the drive

As a new feature, I think it would be an excellent idea for `conda list` to show some aggregate stats about the environment.

1. path count managed by conda
2. path count not managed by conda
3. conda package count
4. non-conda-package count
5. “apparent” disk usage
6. “effective” disk usage

**Comment by ARF1** [comment]
@kalefranz It seems you are right that Windows file explorer is lying:

With empty package cave:
```
37 739 806 720 Bytes free on Z:
```

After `conda create -n test1 python pip pyserial`:
```
37 541 949 440 Bytes free on Z:
--> Bytes used: 197 857 280

env directory: 112 570 368 Bytes "size on disk" in Windows file explorer
```

After `conda create -n test2 python pip pyserial`:
```
37 519 429 632 Bytes free on Z:
--> Bytes used: 22 519 808

env directory: 225 624 064 Bytes "size on disk" in Windows file explorer
--> 113 053 696 Bytes increase from before
```

So my "size on disk" increased by 113e6 bytes while my free space on disk decreased by only 22e6 bytes. Clearly you are right in claiming Windows file explorer is lying.

I am stumped though, why a few years ago the "size on disk" property of the environment directory used to show "correct" figures but now no longer does...

Second question: 22e6 bytes are however still unaccounted for (at least in terms of hard linking). But I assume, this could be explained if primarily packages get hard linked while the "rest" of the python installation gets copied by design.

**Comment by kalefranz** [comment]
Any files that require paths to be rewritten cannot be hard-linked (because the content of the file needs to be different in each location).  We work hard to minimize those, but sometimes it can't be helped.  So some level of copying is expected.

**Comment by kalefranz** [comment]
I'm going to take over this ticket and turn it into a feature request for some aggregate data on `conda list` as I started to detail in https://github.com/conda/conda/issues/8275#issuecomment-463242405.

**Comment by ARF1** [comment]
@kalefranz Many thanks for your patient help. I really appreciate you taking the time to help me.

Re aggregates: For me personally, the true size of the environment / package directories combined would be the most important aggregate. A way to judge how much space a anaconda installation is really eating would be very useful indeed - since the windows file explorer is evidently completely useless...

I have a "bonus" suggestion for the aggregate features, but I fear the implementation might be unreasonably messy:
It would be great if one could display the "size of unique elements" of a environment. By this I mean, the size of the packages of a environment that are only used in this environment and not in any other environments. - It would be useful for identifying "space eating" environments.

But as I said, the effort required to implement it would probably be far too great compared to the real use of the feature...

**Comment by kalefranz** [comment]
I think you get the same thing with what I was thinking of for "apparent size" and "effective size".  The apparent size would be what `du -ha` or Windows file explorer reports (summing the size of all paths within the environment).  The effective size would take the size of each inode and divide it by the number of paths across the whole system pointing to that inode.  So if you have an apparent size that matches the effective size, you really do have a space hog.  If the effective size is a few percent of the apparent size, then you have a space-efficient environment.

**Comment by kalefranz** [comment]
When we're reporting apparent size vs effective size, we should be sure to distinguish between paths managed by conda and paths not managed by conda (e.g. pip).
