### ISSUE TITLE
miniconda3 for aarch64 (ARM 64-bit)

### ISSUE THREAD

**Issue by junaruga** [conda/conda#8297]
Could you upload `miniconda3-*-Linux-aarch64.sh` (ARM 64-bit)?
https://repo.continuum.io/miniconda/

Or could you tell me how to install miniconda3 to aarch64?

Right now I can see the `miniconda3-*-Linux-armv7l.sh` (ARM 32-bit).
But I want to see the 64-bit version.

If we can not install miniconda3 to aarch64, I like to work and contribute to achieve it for conda.

Thank you.

**Comment by hmaarrfk** [comment]
I don't think Anaconda (the company) officially supports an aarch64 build. It is a work in progress.

A few people at conda-forge (including myself) are working on making conda installable on aarch64.

For now, I think you can grab something from
https://github.com/Archiconda/build-tools/releases

that has the archiconda channel (my own project), c4aarch64 channel, by @jjhelmus and the conda-forge enabled.

There is a small effort to enable the installation of a few packages on aarch64, not the full conda-forge list that you can follow:
https://conda-forge.org/status/

**Comment by junaruga** [comment]
@hmaarrfk Hi Mark, thanks for the info. You are working for that. That's great.
I will see the code.
What is _archiconda_ and _c4aarch64_ channel? You mean Slack or IRC channel on free node server?

Hi Anaconda people

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html-single/8.0_beta_release_notes/index#architectures
> The 64-bit ARM architecture 

I would like to inform you that Red Hat Enterprise Linux 8 started to support ARM 64-bit.
So, it might be a good timing for conda to provide the aarch64 installer.

My personal motivation is that I want to install some bioconda packages to aarch64 environment.
I think adding multi arch environment like aarch64 to your CI development environment is easy with the container image.

Here is the example of Travis CI of my repository.
https://github.com/junaruga/ci-multi-arch-test/blob/master/.travis.yml
https://travis-ci.org/junaruga/ci-multi-arch-test

Thank you.

**Comment by hmaarrfk** [comment]
regarding your questions, they are just other channels on anaconda.org:
https://anaconda.org/c4aarch64/
https://anaconda.org/archiarm/

repos:
https://github.com/jjhelmus/conda4aarch64
https://github.com/archiconda/

**Comment by bwanaaa** [comment]
Would this conda work on an Nvidia tegra (arm v8 64bit)?

**Comment by hmaarrfk** [comment]
Potentially, currently there aren't many packages built. We are kinda stuck on numpy (and generally the larger scientific stack) due to the need to ensure that we aren't introducing bugs by compiling using emulated hardware.

**Comment by casperdcl** [comment]
Regarding limited packages (e.g. `numpy`) I think there are still a lot of packages which are pure python and thus still useful.

Also I don't see why compiling numpy for aarch64 would be impossible... It certainly is installable via `pip`...

**Comment by rgommers** [comment]
> Also I don't see why compiling numpy for aarch64 would be impossible... It certainly is installable via `pip`...

Building on ARM64 is fine, NumPy has had CI for that for over a year now (via Shippable): https://github.com/numpy/numpy/commits/master/shippable.yml. @casperdcl note the comment about "emulated hardware" in @hmaarrfk's last reply. So it's not NumPy, but there needing to be support for hooking up actual hardware, which I assume is a fair amount of work.

**Comment by hmaarrfk** [comment]
FYI, conda-forge has been doing lots of work on this front. 

https://github.com/conda-forge/numpy-feedstock/pull/178

numpy is built, that said, we could use help on gstreamer
https://github.com/conda-forge/gstreamer-feedstock/pull/27

**Comment by junaruga** [comment]
Just for your information. Travis CI started supporting aarch64 environment (and ppc64 and s390x) too.
This makes someone's development in aarch64 easier.
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by junaruga** [comment]
Here is the other reasons why I am looking forward to seeing miniconda3 supports ARM 64-bit.

* Apple announced their transition to the new own CPU Apple silicon (ARM) yesterday at WWDC 2020. [official new release](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/), [article](https://www.theverge.com/2020/6/22/21295475/apple-mac-processors-arm-silicon-chips-wwdc-2020).
* ARM based HPC (super computing). Bioinformatics tools can mainly be used in HPC cases. The current [ranking no 1](https://www.top500.org/) performance (?) HPC [Fugaku](https://en.wikipedia.org/wiki/Fugaku_(supercomputer)) is ARMv8 base.

**Comment by mshamash** [comment]
> Here is the other reasons why I am looking forward to seeing miniconda3 will support ARM 64-bit.
> 
> * Apple announced their transition to the new own CPU Apple silicon (ARM) yesterday at WWDC 2020. [official news release](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/), [article](https://www.theverge.com/2020/6/22/21295475/apple-mac-processors-arm-silicon-chips-wwdc-2020).
> * ARM based HPC (super computing). Bioinformatics tools can mainly be used in HPC use cases. The current [ranking no 1](https://www.top500.org/) performance (?) HPC [Fugaku](https://en.wikipedia.org/wiki/Fugaku_(supercomputer)) is ARMv8 base. [The article yesterday](https://www.top500.org/news/japan-captures-top500-crown-arm-powered-supercomputer/).

I received access to the DTK (dev transition kit) to help upgrade bioinformatics tools we use for the ARM architecture. Would there be interest in me trying to compile or run conda on the platform as well?

**Comment by rgommers** [comment]
@mshamash please try https://github.com/conda-forge/miniforge, which is a conda-forge based installer (miniconda-like) with ARM64 support, and contribute to that instead. If Anaconda decides at some point they'd like to support ARM64 in Miniconda, they can build on the work done by conda-forge.

**Comment by casperdcl** [comment]
@rgommers doesn't seem to work on Debian Jessie aarch64:


```bash
~ (chroot)# wget https://github.com/conda-forge/miniforge/releases/download/4.8.3-4/Miniforge3-Linux-aarch64.sh
...
~ (chroot)# bash Miniforge3-Linux-aarch64.sh
...
PREFIX=/root/miniforge3
Unpacking payload ...
Traceback (most recent call last):
  File "entry_point.py", line 59, in <module>
  File "concurrent/futures/process.py", line 556, in __init__
  File "concurrent/futures/process.py", line 165, in __init__
  File "multiprocessing/queues.py", line 42, in __init__
  File "multiprocessing/context.py", line 67, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 38] Function not implemented
[16016] Failed to execute script entry_point
~ (chroot)# ls miniforge3/
conda.exe          pkgs/              preconda.tar.bz2
LICENSE.txt        postconda.tar.bz2
```

**Comment by rgommers** [comment]
Debian Jessie is past end of life and even out of LTS support, but I don't think that's the problem. A quick search shows that your issue is common on VMs and machines set up without shared memory, e.g. https://github.com/ContinuumIO/anaconda-issues/issues/11163, https://github.com/giampaolo/pyftpdlib/issues/496. The second to last comment on the first issue has a workaround (mounting `/run/shm`, could also be `/dev/shm`) that you can try @casperdcl

**Comment by shantanuo** [comment]
Using AWS linux 2 on 64-bit ARM processor:

```
# /root/miniforge3/condabin/conda install jupyter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.                                                                                                                                        failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

```

**Comment by casperdcl** [comment]
@rgommers would've never thought of creating `tmpfs`/`shm` as a fix for this. Thanks, fixed the os python multiprocessing lib too.

**Comment by rgommers** [comment]
@junaruga please keep in mind that not everything is available yet for `aarch64`. In this case, `jupyter` has no package (probably because it has too many dependencies, one or more of which is problematic - my guess would be Qt). You can see on the feedstock which platforms are supported: https://github.com/conda-forge/jupyter-feedstock

You don't need all of `jupyter` on AWS, what you probably want here is `jupyter_core`, which is packaged for `aarch64`: https://github.com/conda-forge/jupyter_core-feedstock

**Comment by shantanuo** [comment]
@rgommers I am aware that not all packages are available for aarch64. But all I need is jupyter and pandas that is already there. The command that seems to work is this...

`/root/miniforge3/condabin/conda install -c conda-forge notebook pandas`

Thanks a lot for introducing miniforge!

**Comment by alexfromapex** [comment]
Not only will it benefit Apple-based devices but also the Raspberry Pi 3 and 4 are ARM-based

**Comment by junaruga** [comment]
> Not only will it benefit Apple-based devices but also the Raspberry Pi 3 and 4 are ARM-based

Possibly Pinebook too. :-)
https://www.pine64.org/pinebook-pro/

**Comment by mingwandroid** [comment]
That's not really how these things work. The fact two machines are powered by aarch64 doesn't mean it is easy to port software from one to the other.

Far more important is the os. Porting Linux x86 to Linux aarch64 is simple (usually zero work basically) but porting Linux aarch64 to osx-aarch64 will not be nearly so simple.

Regardless you don't need to convince us to support osx-aarch64.

**Comment by junaruga** [comment]
Note Windows is available on ARM.
https://www.zdnet.com/article/microsoft-touts-windows-10-on-arm-advances-including-64-bit-emulation/
https://docs.microsoft.com/en-us/windows/arm/

**Comment by isuruf** [comment]
Miniforge now supports macOS on Apple silicon hardware in addition to Linux on aarch64 hardware. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by Zaryob** [comment]
When anaconda on 64bit linux would be possible. Would you give any time as soon as possible???

**Comment by xguse** [comment]
> When anaconda on 64bit linux would be possible. Would you give any time as soon as possible???

ummm... it has been forever. I am confused

**Comment by bhumikpatel** [comment]
https://www.anaconda.com/blog/anaconda-aws-graviton2

**Comment by junaruga** [comment]
Now we can find the `Miniconda3-*-LInux-aarch64.sh` files created at 2021-03-16 on https://repo.anaconda.com/miniconda/ .

* Miniconda3-latest-Linux-aarch64.sh
* Miniconda3-py37_4.9.2-Linux-aarch64.sh
* Miniconda3-py38_4.9.2-Linux-aarch64.sh
* Miniconda3-py39_4.9.2-Linux-aarch64.sh

Though I expected someone from conda would announce us that here, thanks you so much for that!
So, I would close this ticket.

**Comment by casperdcl** [comment]
I still get symlink errors with aarch64 proot miniconda (same ones which were partially solved by miniforge in  https://github.com/conda-forge/miniforge/issues/107)

**Comment by junaruga** [comment]
Oh did you get errors for the above aarch64 installer? OK. I reopen this ticket for now.

**Comment by junaruga** [comment]
@casperdcl I think your issue is proot environment specific right? I think it's better to open a new issue ticket on this repository. I would close this ticket.
