### ISSUE TITLE
MySQLdb and mysql.connector are incompatible with openssl 1.1.1a

### ISSUE THREAD

**Issue by GoldstHa** [conda/conda#8299]
Packages:
    1. mysql.connector (mysql-connector-python) 8.0.13
    2. openssl 1.1.1a
When attempting to connect to an SSL enabled MySQL server I get:
`InterfaceError: 2026 (HY000): SSL connection error: SSL_CTX_set_tmp_dh failed`

Packages:
    1. MySQLdb (mysqlclient) 1.3.14
    2. openssl 1.1.1a
When attempting to connect to an SSL enabled MySQL server I get:
`OperationalError: (2006, 'SSL connection error: SSL_CTX_set_tmp_dh failed')`

When I downgrade to openssl 1.0.2p both packages are able to connect and I'm able to verify that my connection is encrypted. The conda package manager should be aware of this incompatibility when installing those packages.

**Comment by nehaljwani** [comment]
This issue was moved to ContinuumIO/anaconda-issues#10646

**Comment by pradeeppariyar** [comment]
when I trying to connect with MySQL through python by using different packages like "MySQLdb.connect", sql.connector but every time below error has occurred and I'm not able to connect with Mysql.

error : "SSL connection error: SSL_CTX_set_tmp_dh failed"
MySQLInterfaceError: SSL connection error: SSL_CTX_set_tmp_dh failed.

Anyone have basic solving please comment as a solution it will be helpful for me.
