### ISSUE TITLE
Is there a way to create "copy only" package?

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/conda#8304]
Is there a way to create a "copy only" conda package that always copies it's contents instead of symlinking (regardless of --copy option)?

This is useful for distribution of binaries that have post install scripts that modify installation on user machine.

**Comment by asmeurer** [comment]
Yes. See "no link" on this page https://conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html

**Comment by kiwi0fruit** [comment]
@asmeurer Thanks a lot!
