### ISSUE TITLE
OSError: [Errno 22] Invalid argument: '/opt/conda/envs/envname/bin/python'

### ISSUE THREAD

**Issue by mdscruggs** [conda/conda#8305]
## Current Behavior

`conda env create` fails (specifically in GitLab CI using `continuumio/miniconda3:latest` Docker image). Failure does not occur consistently (sometimes succeeds). 

Cannot reproduce same behavior on my local MacOS development machine (within container using same Docker image and same commands as in CI). I've attempted to isolate the issue to specific libraries, pip versions, etc. and nothing seems to consistently explain or fix the issue. I experience the issue across many different projects / repositories. This is a relatively recent issue (don't think I have encountered it until 2-3 weeks ago as of 2/19/19).

### Steps to Reproduce

NB: I can only trigger this error when running a GitLab CI job (as mentioned above in Current Behavior).

```
conda env create -vv
```

This generates the following error report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
        args, pip_version = pip_args(prefix)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/pip_util.py", line 33, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/opt/conda/lib/python3.7/subprocess.py", line 389, in check_output
        **kwargs).stdout
      File "/opt/conda/lib/python3.7/subprocess.py", line 466, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/opt/conda/lib/python3.7/subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "/opt/conda/lib/python3.7/subprocess.py", line 1516, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    OSError: [Errno 22] Invalid argument: '/opt/conda/envs/myenv/bin/python'

`$ /opt/conda/bin/conda-env create -vv`

  environment variables:
                 CIO_TEST=<not set>
           CI_CONFIG_PATH=.gitlab-ci.yml
          CI_PROJECT_PATH=the/path
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/opt/conda
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.14.48-coreos-r2 debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Expected Behavior

Environment should be created successfully.

## Environment Information

See error report above.

**Comment by rababerladuseladim** [comment]
I have a very similar issue. I also use the continuumio/miniconda3:latest image for our CI and our tests only fail in this environment (opposed to your setting, they fail reproducibly).  Running the same docker image on my local machine executes the tests just fine. We even set up a gitlab runner to narrow down the issue, to our suprise the tests pass in this setting, too.

- the error message we get: 
`/bin/sh: 2: /opt/conda/envs/snakemake-testing/bin/python3.6: Invalid argument`
- [example of a failed CI job](https://gitlab.com/s.fuchs/prophane/-/jobs/169912951)

**Comment by crm416** [comment]
Similar issue here. Non-reproducibility (but often) see:

```
Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/root/anaconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/root/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/root/anaconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
        args, pip_version = pip_args(prefix)
      File "/root/anaconda3/lib/python3.6/site-packages/conda_env/pip_util.py", line 33, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    OSError: [Errno 22] Invalid argument: '/root/anaconda3/envs/myenv/bin/python'
```

I'm not using the miniconda3 image, but restarting Jenkins occasionally fixes the issue.

**Comment by nicolas-b12** [comment]
Bump, same issue here.

**Comment by hartb** [comment]
We've seen this as well with Anaconda in Docker containers recently (conda 4.5.x and 4.6.x with RHEL docker host).

When the problem strikes a message is generated in our system log (dmesg):

```
[6826417.599790] Invalid argument reading file caps for /opt/anaconda/envs/my-pai-env/bin/python
[6826427.604330] Invalid argument reading file caps for /opt/anaconda/envs/my-pai-env/bin/python
[6826456.983638] Invalid argument reading file caps for /opt/anaconda/envs/my-pai-env/bin/python
```

The code that generates that particular message was introduced by:

https://github.com/torvalds/linux/commit/8db6c34f1dbc8e06aa016a9b829b06902c3e1340

And this recent fix may be relevant:

https://github.com/torvalds/linux/commit/355139a8dba446cc11a424cddbf7afebc3041ba1


When one of my container environments got into this state I was able to recover by copying the python executable to another filesystem (/tmp) and back again. Presumably it's some state associated with the inode representing the file, and moving the same file to a new inode resets the condition.

I guess maybe creating another hard-link and then swapping the names might do the same.

We've been using Anaconda python in containers for quite a while now, but have only recently started seeing this with some frequency. I'm not sure what's changed.

**Comment by jhunkeler** [comment]
This isn't a solution but a workaround:

If you mount a docker volume and install [mini|ana]conda into it the `invalid argument` issue goes away. For our automatic Jenkins+Docker jobs we've set the cloud template(s) to mount `/home/jenkins` as a volume, and to automatically remove the volume when its finished. 

From there we install miniconda in the home directory and configure the nodes/stages to use it. Seems pretty stable so far.

We don't use your official images, however the issue doesn't appear to have anything to do with it. The error only presents itself when conda is installed in the _container's filesystem_. I suspect it might be a problem with the `overlay` filesystem not `sync`ing properly, or the kernel itself as @hartb suggested.

**Comment by Peque** [comment]
@mdscruggs Did you find any workaround for Gitlab CI?

**Comment by hartb** [comment]
We're still seeing the issue locally in our environment, a couple workarounds we've used are:

- copy and replace the affected file
- stop and restart the container: `docker stop <container>` / `docker start <container>`

That the latter works for us makes me even more suspicious of the overlay filesystem.

**Comment by Peque** [comment]
@hartb Sadly, in my case, I am unable to reproduce the issue locally. And remotely (Gitlab), I do not have much control over what Docker does.

**Comment by allenpc** [comment]
I ran into this same issue with our Jenkins nodes. Can confirm @hartb's findings that it's a Linux kernel bug. Node was previously using `Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1021-aws x86_64)`, have since upgraded to the latest kernel and problem is resolved.

You can see the fix in the release notes of `4.14.69` and `4.18.7`, presumably fixed in anything newer as well

**Comment by Peque** [comment]
In my case, I am hitting this issue with CentOS 7 and `3.10.0` kernel.

**Comment by hartb** [comment]
And for us a RHEL host w/:
```
$ uname -r
4.14.0-115.6.1.el7a.ppc64le
```

**Comment by juve** [comment]
Also having the same problem with build machines running RHEL 7.6 with 3.10.0-957.21.3.el7.x86_64. I was able to avoid triggering this by using conda 4.4.11, but that is probably not a robust work-around.

**Comment by yhuai** [comment]
@allenpc can you also point out which specific item on the kernel release notes is referring to the fix for this issue? Thank you so much!

**Comment by UrbanSolution** [comment]
Any update on this issue ? 
Still happens using `continuumio/miniconda3:4.7.12` (latest available), and when updating to latest conda in addition within the container.

**Comment by kiwimato** [comment]
@UrbanSolution this appears to be more of a kernel bug, than actual conda problem. What OS are you using?
I have the same problem, and updated to CentOS7 latest kernel `3.10.0-1062.12.1.el7.x86_64` but from the changelog it's not clear enough if they fixed it or not. Unfortunately I don't have access to Bugzilla to check the actual commits.
Since for me the problem is kind of non deterministic, it works in 60% of cases, I just have to see if I get any more failed runs today and report back.

**Comment by hartb** [comment]
FWIW I seem to see this less often than I used to, but still do see it occasionally, including just the other day on a system running RHEL 7.6 ALT kernel:

`4.14.0-115.14.1.el7a.ppc64le`

**Comment by kiwimato** [comment]
Maybe it's too early to say, but after upgrading Centos7 kernel to `5.5.7-1.el7.elrepo.x86_64` using from ElRepo using this [howto](https://www.howtoforge.com/tutorial/how-to-upgrade-kernel-in-centos-7-server/) it seems that it got fixed.

**Comment by thomassajot** [comment]
@kiwimato I do not the rights to change or update the OS. What I found however is that the error seem to appear only when there are packages already installed and pip is installing a different version.

**Comment by SingularBunny** [comment]
`conda update -n base -c defaults conda` helped me.

**Comment by innerNULL** [comment]
so two years later....any solution about this problem..?

**Comment by allenpc** [comment]
@innerNULL there could be other confounding factors, but one of the key root causes was a kernel bug. I think that making sure your linux kernel is updated should resolve this issue in most circumstances, assuming you have control over this. The fix you need is:
https://github.com/torvalds/linux/commit/355139a8dba446cc11a424cddbf7afebc3041ba1

**Comment by Firestick-Xia** [comment]
it works！

> conda activate base
conda install anaconda
conda update --all

**Comment by jezdez** [comment]
Closing as fixed by updating to a newer version of conda and/or Anaconda Distribution.
