### ISSUE TITLE
`source activate` does not work on Windows subsystem for Linux

### ISSUE THREAD

**Issue by hadim** [conda/conda#8313]
Steps to reproduce:

- Use an updated Windows 10 (version 1809).
- Install Ubuntu 18.04 (with Windows subsystem for Linux).
- **On Ubuntu**, install a recent Miniconda version (conda 4.6.4).
- Create a Conda env (called `ws` here).
- Do `conda activate ws`:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

 `conda activate ws` only works if I do `source activate base`first.

Also  `source activate ws` works out-of-the-box.

**Comment by msarahan** [comment]
Did you run conda init like that message is telling you to do?

**Comment by hadim** [comment]
Yes I did (sorry I should have mention it):

```
no change     /home/hadim/local/conda/condabin/conda
no change     /home/hadim/local/conda/bin/conda
no change     /home/hadim/local/conda/bin/conda-env
no change     /home/hadim/local/conda/bin/activate
no change     /home/hadim/local/conda/bin/deactivate
no change     /home/hadim/local/conda/etc/profile.d/conda.sh
no change     /home/hadim/local/conda/etc/fish/conf.d/conda.fish
no change     /home/hadim/local/conda/shell/condabin/Conda.psm1
no change     /home/hadim/local/conda/shell/condabin/conda-hook.ps1
no change     /home/hadim/local/conda/lib/python3.7/site-packages/xonsh/conda.xsh
no change     /home/hadim/local/conda/etc/profile.d/conda.csh
no change     /home/hadim/.bashrc
No action taken.
```

**Comment by msarahan** [comment]
And you also started a new shell or otherwise sourced the appropriate rc file?

**Comment by hadim** [comment]
What do you mean by starting a new shell? I start a new shell each time I do a test for activation yes. Is that what you mean?

**Comment by hadim** [comment]
It works when starting a new bash session after opening a new shell. Is that the intended behavior?

**Comment by msarahan** [comment]
the conda shell function stuff has to be loaded.  Running ``conda init`` writes the changes to the shell startup files, but it can't source them itself.  Restarting the shell is one way to get the shell to load those files.  Depending on which shell you use, you could also source the appropriate file to achieve the same effect.  For example, with bash:

source /home/hadim/.bashrc

https://stackoverflow.com/questions/2518127/how-do-i-reload-bashrc-without-logging-out-and-back-in

**Comment by hadim** [comment]
Ok so on WSL, `.bashrc` is not loaded when a shell is started while `.bash_profile` is. Good to know.

Thanks @msarahan for your time!
