### ISSUE TITLE
Retry after permission error 13

### ISSUE THREAD

**Issue by bwoodsend** [conda/conda#8325]
Often I try to install a package (conda install ...), accept that some of my current packages will be up/downgraded, then leave to do its stuff. Then come back expecting it done only to discover one of those packages was open in a python console, raising a PermissionError(13, file in use by python ...). So I have to close the offending terminal and start from scratch (which given how long the solver can take is quite a lot of time wasted).

Could you put in some kind of 
try:
up/downgrade a package
except PermissionError:
promt user to close whatever is using the package and retry

please???

**Comment by msarahan** [comment]
determining what is using the package is not trivial.  I think this would be a lot of work to add.  Sorry, we'd definitely consider a PR that added this, but I don't think it'll be on our roadmap for the foreseeable future otherwise.
