### ISSUE TITLE
ipykernel's post-link script, conda 4.6, and unicode environment names

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#8330]
## Current Behavior

In a recent AppVeyor build for `nb_conda_kernels`, the `ipykernel` post link script is failing, specifically when installing `ipykernel` into an environment with a Unicode character in the directory name, with this env file:
```
name: "t\u00c6st_env2"
dependencies:
  - ipykernel
  - python=3
```

### Steps to Reproduce

I've actually struggled a bit to reproduce this outside of AppVeyor. The best way to see this is to look at the log for [this build](https://ci.appveyor.com/project/mcg1969/nb-conda-kernels/builds/22600917/job/5kndc78go2n33fn3). However, I can confirm that if I _do not_ update `conda` to 4.6 before running the `conda env` commands, the install proceeds without a problem.

## Expected Behavior

The environment should be installed.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

See the AppVeyor log. If I can reproduce this in a local env I will do so.
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

See the AppVeyor log. If I can reproduce this in a local env I will do so.
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

See the AppVeyor log. If I can reproduce this in a local env I will do so.
</p></details>

**Comment by jjhelmus** [comment]
This is likely causes by #8241 which was fixed in #8289, upgrading to conda 4.6.7 which includes this fix might address this issue.  If not there are still some issues around unicode and encoding that are being discussed in #8341.
