### ISSUE TITLE
python has wrong sys.exec_prefix for conda  user created environments

### ISSUE THREAD

**Issue by mschatzow** [conda/conda#8334]
I am having issues for user created environments for a chef installed anaconda base environment.  Whenever chef runs and updates the anaconda base environment, a user created environment has the wrong site-packages and the wrong sys.exec_prefix.  How is sys.exec_prefix set?  I cannot find the source code anywhere.

Here is an example from below, I changed server name to "server."

`(base) mschatzow@server:➜  ~  conda activate pandas0.16.2
(pandas0.16.2) mschatzow@server:➜  ~  which python
/opt/anaconda/latest/envs/pandas0.16.2/bin/python
(pandas0.16.2) mschatzow@server:➜  ~  which ipython
/opt/anaconda/latest/envs/pandas0.16.2/bin/ipython
(pandas0.16.2) mschatzow@server:➜  ~  ipython
Traceback (most recent call last):
  File "/opt/anaconda/latest/envs/pandas0.16.2/bin/ipython", line 7, in <module>
    from IPython import start_ipython
ImportError: No module named IPython
(pandas0.16.2) mschatzow@server:➜  ~  which python
/opt/anaconda/latest/envs/pandas0.16.2/bin/python
(pandas0.16.2) mschatzow@server:➜  ~  /opt/anaconda/latest/envs/pandas0.16.2/bin/python -m site
sys.path = [
    '/usr/lib64/python27.zip',
    '/usr/lib64/python2.7',
    '/usr/lib64/python2.7/plat-linux2',
    '/usr/lib64/python2.7/lib-tk',
    '/usr/lib64/python2.7/lib-old',
    '/usr/lib64/python2.7/lib-dynload',
    '/usr/lib64/python2.7/site-packages',
    '/usr/lib/python2.7/site-packages',
]
(pandas0.16_2) mschatzow@server:➜ ~ /opt/anaconda/latest/envs/pandas0.16_2/bin/python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
i>>> import sys
>>> sys.exec_prefix
'/usr'
>>>

`

**Comment by nehaljwani** [comment]
@mschatzow Please share the output for:
```
conda list -n pandas0.16.2
```

**Comment by mschatzow** [comment]
`# packages in environment at /opt/anaconda/latest/envs/pandas0.16.2:
#
# Name                    Version                   Build  Channel
altgraph                  0.16.1                   pypi_0    pypi
arctic                    1.73.0                   pypi_0    pypi
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.5                    py27_0    defaults
autopep8                  1.4.3                    py27_0    defaults
backports                 1.0                      py27_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports_abc             0.5                      py27_0    defaults
bcolz                     1.2.1            py27h04863e7_0    defaults
bcrypt                    3.1.5            py27h7b6447c_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.0.2                    py27_0    defaults
blosc                     1.15.0               hd408876_0    defaults
bokeh                     1.0.3                    py27_0    defaults
bzip2                     1.0.6                h14c3975_5    defaults
ca-certificates           2019.1.23                     0    defaults
cached-property           1.5.1                    pypi_0    pypi
certifi                   2018.11.29               py27_0    defaults
cffi                      1.11.5           py27h9745a5d_0    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
click                     7.0                      py27_0    defaults
cloudpickle               0.6.1                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
cryptography              2.4.2            py27h1ba5d50_0    defaults
cvxopt                    1.2.0            py27h9e0dedd_0    defaults
cvxpy                     1.0.12                   pypi_0    pypi
cycler                    0.10.0           py27hc7354d3_0    defaults
cython                    0.29.2           py27he6710b0_0    defaults
cytoolz                   0.9.0.1          py27h14c3975_1    defaults
dask                      1.0.0                    py27_0    defaults
dask-core                 1.0.0                    py27_0    defaults
dbus                      1.13.2               h714fa37_1    defaults
decorator                 4.3.0                    py27_0    defaults
dill                      0.2.8.2                  pypi_0    pypi
dis3                      0.1.3                    pypi_0    pypi
distributed               1.25.2                   py27_0    defaults
docutils                  0.14                     pypi_0    pypi
ecos                      2.0.7.post1              pypi_0    pypi
entrypoints               0.2.3                    py27_2    defaults
enum-compat               0.0.2                    pypi_0    pypi
enum34                    1.1.6            py27h99a27e9_1    defaults
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.0.2            py27h14c3975_2    defaults
flake8                    3.6.0                    pypi_0    pypi
flake8-polyfill           1.0.2                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
frosted                   1.4.1                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
functools32               3.2.3.2                  py27_1    defaults
future                    0.17.1                   pypi_0    pypi
futures                   3.2.0            py27h7b459c0_0    defaults
git-pre-commit-hook       0.0.11                   pypi_0    pypi
git-pre-commit-hook-utils 0.0.5                    pypi_0    pypi
git-pylint-commit-hook    2.5.1                    pypi_0    pypi
glib                      2.56.2               hd408876_0    defaults
glpk                      4.65                 h3ceedfd_2    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
grin                      1.2.1                    py27_4    defaults
gsl                       2.4                  h14c3975_4    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.0                    py27_2    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py27h5722d68_1    defaults
intel-openmp              2019.1                      144    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.10.0                   py27_0    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0            py27h89fb69b_0    defaults
ipywidgets                7.4.2                    py27_0    defaults
isort                     4.3.4                    py27_0    defaults
jinja2                    2.10                     py27_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0            py27h7ed5aa4_0    defaults
jupyter                   1.0.0                    py27_7    defaults
jupyter_client            5.2.4                    py27_0    defaults
jupyter_console           5.2.0                    py27_1    defaults
jupyter_core              4.4.0                    py27_0    defaults
jupyterlab                0.33.11                  py27_0    defaults
jupyterlab_launcher       0.11.2           py27h28b3542_0    defaults
kiwisolver                1.0.1            py27hf484d3e_0    defaults
lazy-object-proxy         1.3.1            py27h14c3975_2    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.36               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.9                he85c1e1_2    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.8                h26e45fe_1    defaults
llvmlite                  0.27.0           py27hd408876_0    defaults
locket                    0.2.0                    py27_1    defaults
lz4                       2.1.6                    pypi_0    pypi
lzo                       2.10                 h49e0be7_2    defaults
macholib                  1.11                     pypi_0    pypi
markupsafe                1.1.0            py27h7b6447c_0    defaults
matplotlib                2.2.3            py27hb69df0a_0    defaults
mccabe                    0.6.1                    py27_1    defaults
metis                     5.1.0                hf484d3e_4    defaults
mistune                   0.8.4            py27h7b6447c_0    defaults
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py27h7dd41cf_0    defaults
mkl_random                1.0.1            py27h4414c95_1    defaults
mock                      2.0.0                    pypi_0    pypi
mockextras                1.0.2                    pypi_0    pypi
msgpack                   0.2.3                    py27_0    defaults
msgpack-python            0.5.6            py27h6bb024c_1    defaults
multiprocess              0.70.6.1                 pypi_0    pypi
nb_conda_kernels          2.2.0                    py27_0    defaults
nbconvert                 5.3.1                    py27_0    defaults
nbformat                  4.4.0            py27hed7f2b2_0    defaults
ncurses                   6.1                  hf484d3e_0    defaults
nodejs                    8.12.0               he6710b0_0    defaults
nose                      1.3.7                    py27_2    defaults
notebook                  5.7.4                    py27_0    defaults
numba                     0.42.0           py27h962f231_0    defaults
numexpr                   2.6.8            py27hd89afb7_0    defaults
numpy                     1.15.4           py27h1d66e8a_0    defaults
numpy-base                1.15.4           py27h81de0dd_0    defaults
olefile                   0.46                     py27_0    defaults
openssl                   1.1.1a               h7b6447c_0    defaults
osqp                      0.5.0                    pypi_0    pypi
packaging                 18.0                     py27_0    defaults
pandas                    0.16.2                   pypi_0    pypi
pandas-old                0.16.2                   pypi_0    pypi
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py27_1    defaults
parameterized             0.6.3                    pypi_0    pypi
paramiko                  2.4.2                    py27_0    defaults
partd                     0.3.9                    py27_0    defaults
pathlib2                  2.3.3                    py27_0    defaults
patsy                     0.5.1                    py27_0    defaults
pbr                       5.1.1                    pypi_0    pypi
pcre                      8.42                 h439df22_0    defaults
pefile                    2018.8.8                 pypi_0    pypi
pep8-naming               0.7.0                    pypi_0    pypi
pexpect                   4.6.0                    py27_0    defaults
pickleshare               0.7.5                    py27_0    defaults
pies                      2.6.7                    pypi_0    pypi
pies2overrides            2.6.7                    pypi_0    pypi
pillow                    5.4.1            py27h34e0f95_0    defaults
pip                       10.0.1                   py27_0    defaults
plotly                    3.4.2            py27h28b3542_0    defaults
prometheus_client         0.5.0                    py27_0    defaults
prompt_toolkit            1.0.15                   py27_0    defaults
psutil                    5.4.8            py27h7b6447c_0    defaults
ptyprocess                0.6.0                    py27_0    defaults
pyasn1                    0.4.4            py27h28b3542_0    defaults
pycodestyle               2.4.0                    pypi_0    pypi
pycosat                   0.6.3            py27ha4109ae_0    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pyflakes                  2.0.0                    pypi_0    pypi
pygments                  2.3.1                    py27_0    defaults
pyinstaller               3.4                      pypi_0    pypi
pylint                    1.9.2                    py27_0    defaults
pymongo                   3.7.2            py27he6710b0_0    defaults
pynacl                    1.3.0            py27h7b6447c_0    defaults
pyopenssl                 18.0.0                   py27_0    defaults
pyparsing                 2.3.0                    py27_0    defaults
pyqt                      5.9.2            py27h05f1152_2    defaults
pysocks                   1.6.8                    py27_0    defaults
pytables                  3.4.4            py27h71ec239_0    defaults
python                    2.7.15               h9bab390_6    defaults
python-blosc              1.7.0            py27h7b6447c_0    defaults
python-dateutil           2.7.5                    py27_0    defaults
pytz                      2018.7                   py27_0    defaults
pyyaml                    3.13             py27h14c3975_0    defaults
pyzmq                     17.1.2           py27h14c3975_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.4.3                    py27_0    defaults
readline                  7.0                  ha6073c6_4    defaults
redis-py                  3.0.1                    py27_0    defaults
requests                  2.18.4           py27hc5b0589_1    defaults
restructuredtext-lint     1.2.2                    pypi_0    pypi
retrying                  1.3.3                    py27_2    defaults
ruamel_yaml               0.15.37          py27h14c3975_2    defaults
scandir                   1.9.0            py27h14c3975_0    defaults
scikit-learn              0.20.1           py27h4989274_0    defaults
scipy                     1.1.0            py27hfa4b5c9_1    defaults
scs                       2.0.2                    pypi_0    pypi
seaborn                   0.9.0                    py27_0    defaults
send2trash                1.5.0                    py27_0    defaults
setuptools                39.2.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.19.8           py27hf484d3e_0    defaults
six                       1.11.0           py27h5f960f1_1    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
sortedcontainers          2.1.0                    py27_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
statsmodels               0.9.0            py27h035aef0_0    defaults
subprocess32              3.5.3            py27h7b6447c_0    defaults
suitesparse               5.2.0                h171a5a3_0    defaults
tbb                       2018.0.5             h6bb024c_0    defaults
tblib                     1.3.2            py27h51fe5ba_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.4.2                    py27_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.1.1            py27h7b6447c_0    defaults
traitlets                 4.3.2            py27hd6ce930_0    defaults
tzlocal                   1.5.1                    pypi_0    pypi
ujson                     1.35             py27h14c3975_0    defaults
unknown                   0.0.0                    pypi_0    pypi
urllib3                   1.22             py27ha55213b_0    defaults
wcwidth                   0.1.7                    py27_0    defaults
webencodings              0.5.1                    py27_1    defaults
wheel                     0.31.1                   py27_0    defaults
widgetsnbextension        3.4.2                    py27_0    defaults
wrapt                     1.10.11          py27h14c3975_2    defaults
xlrd                      1.2.0                    py27_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.5                hf484d3e_1    defaults
zict                      0.1.3                    py27_0    defaults
zlib                      1.2.11               ha838bed_2    defaults`

**Comment by nehaljwani** [comment]
From your previous output:
```
/opt/anaconda/latest/envs/pandas0.16_2/bin/python
Python 2.7.5 (default, Aug 4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2 <------- This is not Anaconda's python at all!
Type "help", "copyright", "credits" or "license" for more information.
```

This is how it should look:
```
$ python 
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Try: `conda install --force-reinstall python=2 -yp 
/opt/anaconda/latest/envs/pandas0.16.2`

**Comment by mschatzow** [comment]
I think the chef code is causing the  wrong python to be picked up
