### ISSUE TITLE
Conda create not using base python version

### ISSUE THREAD

**Issue by rbutleriii** [conda/conda#8338]
## Current Behavior

`conda create` does not default to the base python version, but instead the system version.

### Steps to Reproduce

```
(base) rbutler@Robs-Mac-Pro:~$ python --version
Python 3.7.1
(base) rbutler@Robs-Mac-Pro:~$ conda create -y -n clinotator
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/rbutler/miniconda3/envs/clinotator



Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate clinotator
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) rbutler@Robs-Mac-Pro:~$ conda activate clinotator
(clinotator) rbutler@Robs-Mac-Pro:~$ python --version
Python 2.7.10
```

## Expected Behavior

Should create environment with the conda base python version

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
    active environment : base
    active env location : /Users/rbutler/miniconda3
            shell level : 1
       user config file : /Users/rbutler/.condarc
 populated config files : /Users/rbutler/.condarc
          conda version : 4.6.7
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /Users/rbutler/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/rbutler/miniconda3/pkgs
                          /Users/rbutler/.conda/pkgs
       envs directories : /Users/rbutler/miniconda3/envs
                          /Users/rbutler/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/rbutler/.condarc <==
channels:
  - bioconda
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/rbutler/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h6174b99_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.7                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-pack                0.3.1                    pypi_0    pypi
cryptography              2.4.2            py37ha12b0ac_0    defaults
idna                      2.8                      py37_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
pip                       18.1                     py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                haf84260_7    defaults
python.app                2                        py37_9    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               h1de35cc_3    defaults

```
</p></details>

**Comment by mingwandroid** [comment]
> conda create does not default to the base python version, but instead the system version

Conda create didn't install any python interpreter unless you ask it to. The anaconda distribution is about more than python.

> conda create -y -n clinotator

You have not listed any software to be installed here at all, so no python gets installed so when you type python it finds one in PATH and it finds you system interpreter.

**Comment by rbutleriii** [comment]
>The anaconda distribution is about more than python.

Regardless of the ethos about 'what conda is,' the conda documentation section, [Creating an environment with commands](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id1), does explicitly cover a default python version in step 2. conda ships with a python version in its base, in this case `python version : 3.7.1.final.0`. My understanding with previous anaconda and miniconda versions was that it then uses the base version of python installed with conda as the default for `create`, assuming it is correctly sourced in `.bashrc`. I followed the standard installation instructions in a standard location, and selected yes to modifying the `.bashrc`. You can see that the base environment is active above. Thus:

>python it finds one in PATH and it finds you system interpreter. 

It should find the base version of python that comes with miniconda3. The first thing in my path is `/Users/rbutler/miniconda3/bin`.  `which python` returns `/Users/rbutler/miniconda3/bin/python`. Unless conda explicitly ignores its own python version in the `$PATH` and uses the system version, something is not working right. 

If that is the desired behavior, the conda documentation should probably reflect that. It would also be somewhat useless bloat to ship miniconda3 with a default python version that is not used by default.

**Comment by msarahan** [comment]
When you activate your environment, the root environment is removed from PATH.  That's by design.  Unless you "stack" environments, only one should be active at a time.  As Ray mentioned, you have no python at all in your created env.  It doesn't matter what's in the root env, it only matters what's in your active env.  Since there is no python there, it looks elsewhere, and apparently finds the one on your system.

if instead you run:
```conda activate```

to return to the base env, you should see 
```
(base) rbutler@Robs-Mac-Pro:~$ python --version
Python 3.7.1
```

again.
