### ISSUE TITLE
LookupError: unknown encoding: 65001 caused by pull/8289

### ISSUE THREAD

**Issue by blackgear** [conda/conda#8341]
## Current Behavior

![image](https://user-images.githubusercontent.com/4780199/53404057-d250fa00-39ef-11e9-9b54-57a880fc09e7.png)

### Steps to Reproduce

```
chcp 65001 
conda update --all
```

## Expected Behavior

No Exception should be throw

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\xxxxx\.condarc
 populated config files : C:\Users\xxxxx\.condarc
          conda version : 4.6.7
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : D:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Miniconda3\pkgs
                          C:\Users\xxxxx\.conda\pkgs
                          C:\Users\xxxxx\AppData\Local\conda\conda\pkgs
       envs directories : D:\Miniconda3\envs
                          C:\Users\xxxxx\.conda\envs
                          C:\Users\xxxxx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\xxxxx\.condarc <==
ssl_verify: True
channels:
  - defaults
report_errors: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at D:\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
bleach                    3.1.0                    py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.6.7                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.5              py37h7a1dbc1_0    defaults
decorator                 4.3.2                    py37_0    defaults
entrypoints               0.3                      py37_0    defaults
idna                      2.8                      py37_0    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.3.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.13.2                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.0            py37he774522_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.3.1                    py37_0    defaults
nbformat                  4.4.0                    py37_0    defaults
notebook                  5.7.4                    py37_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.2                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.0.1                   py37_0    defaults
prometheus_client         0.5.0                    py37_0    defaults
prompt_toolkit            2.0.8                      py_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.2               h8c8aaf0_10    defaults
python-dateutil           2.7.5                    py37_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyzmq                     17.1.2           py37ha925a31_2    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.8.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tornado                   5.1.1            py37hfa6e2cd_0    defaults
traitlets                 4.3.2                    py37_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.32.3                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
```
</p></details>

**Comment by blackgear** [comment]
https://github.com/conda/conda/pull/8289 caused this problem by introduce:

https://github.com/jjhelmus/conda/blob/6a7b3e2c09e46fe4c4027477e1372ebd0fdb7101/conda/activate.py#L539

cdll.kernel32.GetACP() returns codepage number, which should not be use as encode format without 'cp' prefix.

instead:
```
                encoding = 'cp' + str(cdll.kernel32.GetACP())
```

**Comment by blackgear** [comment]
```
                "PYTHONIOENCODING": ctypes.cdll.kernel32.GetACP(),
```
https://github.com/conda/conda/blob/master/conda/activate.py#L739

here should be another problem, 'cp' prefix should be included

**Comment by blackgear** [comment]
```
>>> 'aa'.encode('cp1252')
b'aa'
>>> 'aa'.encode('1252')
b'aa'
>>> 'aa'.encode('cp65001')
b'aa'
>>> 'aa'.encode('65001')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: 65001
```

Seems the 65001 is the only encoding that cause this problem...

**Comment by mingwandroid** [comment]
Well, your change seems like it will work in both cases?

`65001` isn't a codepage many [people](https://dev.to/mattn/please-stop-hack-chcp-65001-27db) [recommend](https://bugs.python.org/issue1602), not even [Microsoft](https://mail.python.org/pipermail/python-ideas/2016-August/041539.html). Messing about with `chcp` is also something we'd rather not be doing at all, but unfortunately we must.

AFAIK, there is some [new](https://www.reddit.com/r/Windows10/comments/8r8wa0/new_utf8_support_setting_in_windows10_1803/) UTF-8 support in the latest Windows releases, I don't know how this is implemented though. It seems GetACP() returns 65001 when this is enabled. Hopefully the bugs Steve Dower speaks of are fixed too.

Still, fixes in new Windows while interesting aren't something we can rely upon so we will always need fallbacks.

Again, thank you!

**Comment by blackgear** [comment]
I did some test about this:

First, `ctypes.cdll.kernel32.GetACP` return the codepage as `int`, which working as intended.

Then, let's see what codepages are available: 
```
cp950 has an alias called 950
...
cp932 has an alias called 932

cp875 has no alias (`chcp 875` should cause this bug, too)
...
cp65001 has no alias
```
https://docs.python.org/3.7/library/codecs.html#standard-encodings

It's clear that `cp` prefix is preferred, `str(GetACP)` version are some incomplete alias. **Adding `cp` prefix should always works well.**

------

One last question:

Set `PYTHONIOENCODING` to `cp65001` cause an error:

```
Parameter format not correct - cp65001
```

I found some issue in python's issue tracker about this, eg: https://bugs.python.org/issue35558

While set `PYTHONIOENCODING` to `65001` works perfectly well.

**So this part should remain the `str(GetACP)`**

**Comment by mingwandroid** [comment]
> Set `PYTHONIOENCODING` to `cp65001` cause an error:

See my patch that I was working on today semi-coincidentally (I'm looking to fix all testsuite failures on conda on Windows): https://github.com/mingwandroid/conda/commit/14f8d98b842a9dc23ba21b56a0cdc1eb6bc5a399#diff-19d07b1f2eb7bd8f0c8e967b228f57d2

> @IF DEFINED PYTHONIOENCODING chcp %PYTHONIOENCODING:~2% > NUL

This ensures we don't call `chcp` with the `cp` part still attached and seems to work!

**Comment by mingwandroid** [comment]
I think I should add some conditional logic around removing these characters though. Someone may have set PYTHONIOENCODING to just a number.

**Comment by mingwandroid** [comment]
@jjhelmus can offer any thoughts about this stuff too? From my POV I am generally a bit confused about the limits of Windows' support for full unicode on the filesystem, in terms of the encoding of filenames!

@blackgear let me know if you want to finish this stuff or whether I should! I think adding 'cp' in front of PYTHONIOENCODING is the right thing to do, we just need to account for that when calling chcp (if we've done that).

**Comment by mingwandroid** [comment]
The latest version of my patch is at https://github.com/mingwandroid/conda/commit/b62f31af1bcda45193c64f94272cc017c046ae73#diff-19d07b1f2eb7bd8f0c8e967b228f57d2

I added the 'remove cp' stuff instead of always chopping off the first two characters.

More on utf-8 in Python 3: https://vstinner.github.io/python37-new-utf8-mode.html

I ran some tests calling conda via `python -X utf8 -m conda` from an MSYS2 shell and was impressed by how much full unicode I could use, creating envs such as:

```
python -X utf8 -m conda create -n ōγђ家固한áêñßôç python=3.7.2
```

But for this to matter we must make sure activate and conda-run etc work too and that we have tests that make sure it doesn't get broken.

**Comment by blackgear** [comment]
> @blackgear let me know if you want to finish this stuff or whether I should! I think adding 'cp' in front of PYTHONIOENCODING is the right thing to do, we just need to account for that when calling chcp (if we've done that).

I still don't know why my CLA checks are not passed, althought I'm signed in webpage and checked in email...

So you could make a new pr and fix those test cases, then I could close my ones.

**Comment by msarahan** [comment]
The CLA is a manual process. I confirm that you have signed it. Do not let
that block his work from being merged.

**Comment by blackgear** [comment]
Ok, pr https://github.com/conda/conda/pull/8342 should be ready for merge. Failed test case is fixed.

**Comment by vc12345679** [comment]
In https://github.com/conda/conda/blob/master/conda/activate.py#L533-L534
modifying to `encoding = 'cp' + str(acp)` works perfectly,
while setting `PYTHONIOENCODING` to either `65001` or `cp65001` doesn't work for my case.

**Comment by mingwandroid** [comment]
@vc12345679 please test the latest: https://github.com/conda/conda/pull/8342/files

It adds 'cp' everywhere but also removes it at one crucial point.

**Comment by Robert-Lu** [comment]
I see the reference from #8327, and just copy my comments there to here:

I have the same issue when using the command `activate` if the `Beta: Use Unicode UTF-8 for worldwide language support` option is checked in the Windows Settings. Now I have to turn off this option, and everything works fine.

When the option is on, my console gives 65001 for command `chcp`, and now gives 437.

Also, I agree that this issue is not a duplicate with ticket #5448, and it should be unrelated to what terminal simulator you use. I have the same issue for CMDer, original cmd.exe, and Power Shell. Even explicitly change the code page in the terminal using something like `chcp 437` will not help.

Thanks. Hope this might help.

**Comment by vc12345679** [comment]
@Robert-Lu Maybe you can have a try with - https://github.com/conda/conda/pull/8342/files
It works for me.
