### ISSUE TITLE
Microsoft Visual C++ Runtime Library Error on Windows

### ISSUE THREAD

**Issue by rachaelph** [conda/conda#8345]
Hello,

So I am having this issue when I try to run conda commands in the command line. I have a Windows 10 OS 64-bit, I use gitbash to do my command line coding and have anaconda for python 3.7 installed. When I open the Anaconda Navigator, I am able to create environments, install packages in each environment and so forth, however, when I try to run it in the command line, I get the following error:

![image](https://user-images.githubusercontent.com/46200746/53435675-92b9ec00-39b6-11e9-877c-f2a2797bbdc4.png)

This error will keep popping up even if I keep hitting okay. Once I am done hitting the okay button enough times, the following error comes up on my gitbash:

![image](https://user-images.githubusercontent.com/46200746/53435760-cd238900-39b6-11e9-801e-ee7db262e85e.png)

My conda system information is:
![image](https://user-images.githubusercontent.com/46200746/53435804-e1678600-39b6-11e9-8fe1-9ff892794995.png)

If anyone can please help me, that would be great! It doesn't matter that I have to use Anaconda Navigator, but I would really like to be able to use the command line to use conda also.

Thank you for your help,
Rachael

**Comment by msarahan** [comment]
Have you tried anaconda prompt?

The key problem is that the default command prompt is not activated. It doesn't have necessary folders on PATH.

see https://conda.io/activation for more info.

**Comment by msarahan** [comment]
PS: to add conda to your git bash prompt, you can run:

conda init

From anaconda prompt.

**Comment by rachaelph** [comment]
I tried the conda init in the anaconda prompt and this is what I got as an output.
![image](https://user-images.githubusercontent.com/46200746/53436569-baaa4f00-39b8-11e9-9b93-6a8afaaf53be.png)

**Comment by ReddyKilowatt** [comment]
I saw very similar error messages on Windows 7, except that the text in the
dialog was mostly missing.
This only happens when I was trying to install packages in a Pythin 2.7
environment.

**Comment by rachaelph** [comment]
I think it might be an issue with the python path, but i'm not really sure how to fix it. I have uninstalled and installed anaconda a lot so there probably are some issues with the python path at this point. How do I find all of my python paths?

**Comment by msarahan** [comment]
What does

conda activate

Do in your git bash prompt?

**Comment by rachaelph** [comment]
![image](https://user-images.githubusercontent.com/46200746/53437924-dfec8c80-39bb-11e9-8905-e788587e5618.png)

**Comment by rachaelph** [comment]
Then when I run conda init, it has the same output as the last above screen shot.

**Comment by msarahan** [comment]
Can you run

```
source (your miniconda install path)/Scripts/activate
```

?

**Comment by rachaelph** [comment]
I don't have miniconda, just anaconda. Where should I run that, in gitbash?

**Comment by msarahan** [comment]
yes.  Same command, no difference between anaconda and miniconda here.

**Comment by rachaelph** [comment]
![image](https://user-images.githubusercontent.com/46200746/53438210-a6685100-39bc-11e9-86c3-76f54368e378.png)

**Comment by msarahan** [comment]
great.  From that prompt, everything should work fine.  That's how conda init should leave things (after a restart of git bash).  The major question is why that's not working.  Have you restarted git bash since running ``conda init``?

**Comment by rachaelph** [comment]
So, I have exited out and gone back into gitbash. I will try it again. I am not sure if there is another way to restart it.

**Comment by rachaelph** [comment]
Alright, so I have closed it out and restart it and I still get the same error, after running conda init
but conda init gives me No action taken at the bottom

**Comment by msarahan** [comment]
You can add that source command to ~/.bashrc to run it on git bash startup.  Otherwise, sorry, we can't help you debug this further.  You need to learn more about your system and how bash loads settings on startup.  Something in that is not working.  It could be old anaconda installs that are left and are messing things up.  You might want to try to back up your ~/.bashrc file, then start fresh and see if ``conda init`` does any better.

**Comment by rachaelph** [comment]
Okay, I added that line to the .bashrc and it still has the same issue. I guess I will have to just use anaconda navigator. I am really not sure how to fix this. I appreciate your help, have a nice day.

**Comment by rachaelph** [comment]
So, it works fine now. So, I think it did have to do with going back into the gitbash after running conda init. The reason I was still getting the same errors is because I was still trying to open the corrupted environments that had this issue. Once I created a few dummy environments to see if they worked or not, it worked just fine. No issues and no runtime errors! I think what you helped me with worked! Thank you so much for all your help!
