### ISSUE TITLE
`conda upgrade --all` doesn't upgrade packages installed from `conda install -c CHANNEL` such as conda-forge channel

### ISSUE THREAD

**Issue by c02y** [conda/conda#8355]
## Current Behavior

I use `conda upgrade --all` to upgrade all packages managed by anaconda/conda (in path ~/anaconda3/), but some of my packages are installed using `conda install -c CHANNEL pkg`, such as Emacs, tmux, fish,  channels are like conda-forge, or ripl-org which provide latest versions.

After `conda upgrade --all`, and I search my pkg using `binstar search -t conda pkg`, it shows newer version than the version I installed, so `conda upgrade --all` doesn't upgrade all my packages. I can use `conda install -c CHANNEL pkg` to install the latest version of my package.

Since the channels are different, it is inconvenient to check the channel and install from the channel manually. 

### Steps to Reproduce

```

```

## Expected Behavior

Since the channels are different, it is inconvenient to check the channel and install from the channel manually. 

So `conda upgrade --all` should upgrade all my package including those installed from  `conda install -c CHANNEL pkg`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/echecod/.condarc
 populated config files :
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /home/echecod/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/echecod/anaconda3/pkgs
                          /home/echecod/.conda/pkgs
       envs directories : /home/echecod/anaconda3/envs
                          /home/echecod/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Linux/4.10.0-42-lowlatency ubuntu/16.04.5 glibc/2.23
                UID:GID : 1009:1009
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Nothing!
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Long list, more than 300 lines.
If you really need it, please let me know, I'll do it then.
```
</p></details>

**Comment by msarahan** [comment]
Channels don't "stick" just because you installed from them once.  If you want to install from them again, add them to your more permanent configuration:

``conda config --add channels your_new_channel``
