### ISSUE TITLE
Solving environment: / last forever when trying to install a packages with anaconda

### ISSUE THREAD

**Issue by bjce** [conda/conda#8359]
So I'm on `Windows 10` and have `python 3.7` installed anaconda and I'm trying to install `PyInstaller`, I disabled the Firewall system (`pulse secure`) and trying the 2 following commands: 

- `C:\>conda install -c acellera pyinstaller`
- `C:\>conda install -c conda-forge pyinstaller=3.2.1`

But the same message `Solving environment: /` is then running for more than 15 minutes but nothing happens.

What should I do?

**Comment by jjhelmus** [comment]
The pyinstaller 3.2.1 packages in the conda-forge channel and those in the acellera channel do not support Python 3.7.  Therefore the conda solver is needing to do a lot of work to try to find a solution which includes both pyinstaller and the packages currently in your environment.  Creating a new environment using `conda create -n example -c conda-forge pyinstaller=3.2.1` gives a solution in under a minute on the machine I tested on.
