### ISSUE TITLE
Better hint error message

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#836]
We could make the hint error message better, so that users actually have an idea how to fix things. See https://github.com/astropy/astropy/issues/2759#issuecomment-50545161 for some suggestions.

**Comment by mcg1969** [comment]
This issue is old enough that Aaron's last comment is no longer true ;-) Seems to me that it could and should be closed, especially since we have other newer issues open about better solver hints.

**Comment by kalefranz** [comment]
works for me
