### ISSUE TITLE
conda list should show packages installed with develop

### ISSUE THREAD

**Issue by bilderbuchi** [conda/conda#8361]
It would be great if `conda list` would include packages that have been installed using `conda develop`.

Currently (conda 4.6.7), `conda list` shows packages from different sources (and nicely indicates "conda-forge", "pypi", etc. in the last column) , but does *not* include python packages that have been installed using `conda develop somedir`. Those packages import without problem in a python prompt, so they are definitely installed and usable.

**Comment by jjhelmus** [comment]
@bilderbuchi This would be a great addition to conda.  Unfortunately, the team at anaconda has a limited amount of time and this feature is not a priority for us at this time.  If there is interest in this feature a contribution from the community would be most welcome and appreciated.

**Comment by bilderbuchi** [comment]
Thanks, I understand. Do you think this should be implemented in conda list, or over in conda-build as the host for the conda develop command? I.e., should conda develop learn to compile this list itself (not possible, either, at this time I think), and conda list just consumes that?

**Comment by jjhelmus** [comment]
Implementing this as part of conda list would be make the most sense.  Packages installed via pip or in pip's develop mode are included in the output of conda list.  Seeing how that is accomplished would be a good start.
