### ISSUE TITLE
Conda not working in anaconda prompt but it is working in cmd

### ISSUE THREAD

**Issue by avikantwadhwa** [conda/conda#8367]
anaconda prompt was working fine until one day..
When I tried to use conda command in cmd it is working fine.But it is not working in anaconda prompt
it showing this:

(base) C:\Users\Avikant wadhwa>conda --version

'C:\Users\Avikant' is not recognized as an internal or external command,
operable program or batch file.

so when i change directory using cd:

(base) C:\Users\Avikant wadhwa>cd C:\Users\Avikant wadhwa\Anaconda3\Scripts

then conda command is working fine.
paths are already added to sytem variables as i mentioned it was working fine earlier.
is it because of space in path..?

**Comment by nehaljwani** [comment]
@avikantwadhwa Please share the output for `conda info`
