### ISSUE TITLE
compiler('haskell')

### ISSUE THREAD

**Issue by notestaff** [conda/conda#8376]
Who maintains the compiler packages gcc_linux-64 etc, installed by compiler('c'/'c++'/'fortran') macro? Would it be possible to extend this to the Haskell compiler ghc?

**Comment by msarahan** [comment]
Here's an example of how to create "activation packages" like those compilers: https://github.com/AnacondaRecipes/aggregate/tree/master/rust-activation-feedstock

Conda-build doesn't need any sort of registration.  It's just a dumb name lookup.  ``{{ compiler('haskell') }}`` would look up a package called haskell_(target platform) by default.  Read more at https://conda.io/projects/conda-build/en/latest/source/resources/compiler-tools.html
