### ISSUE TITLE
auto activate different environment at start up

### ISSUE THREAD

**Issue by ladyrick** [conda/conda#8378]
Everytime I open the terminal, the "base" environment is activated.
I want to activated different environment at start up.
It seems that in .condarc file, I can only config "auto_activate_base=True".
Why is this "base" so important?
Why not add a config like "default_env=py37-env" ?

**Comment by jjhelmus** [comment]
The `base` environment is the environment created when you first install Miniconda or Anaconda.  Other environments are created from this environment.  This environment lives in the root directory of the install where as other environments are rooted in a directory insides the env directory by default.  For these reasons many find it convenient to use this environment as their default starting environment.  

If you want to use a different starting environment you can do this by setting `auto_activate_base` to False and adding `conda activate env_name` to your .bashrc or .profile file after the conda initialization block.
