### ISSUE TITLE
libpthread problem when building haskell packages using stack

### ISSUE THREAD

**Issue by notestaff** [conda/conda#8380]
When using Haskell stack to build Haskell projects with Anaconda's gcc_linux-64 , I repeatedly run into a linking error with libpthread:

   [8 of 9] Compiling Network.Wai.Application.Static ( Network/Wai/Application/Static.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1\
/build/Network/Wai/Application/Static.o )
    <command line>: can't load .so/.DLL for: /data/n10mc3/envs/new-ghc-env/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/libpthread.so (/lib/libpthread.so.0: wrong ELF class: ELFCLASS32)

What happens is that the file
/data/n10mc3/envs/new-ghc-env/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/libpthread.so
sends the linker to /lib/libpthread rather than /lib64/libpthread
Is this an error in the gcc_linux-64 and related conda packages, or am I using them incorrectly?

**Comment by mingwandroid** [comment]
I have no idea. Please give complete reproduction steps.

**Comment by notestaff** [comment]
Commenting out the two lines starting at
https://github.com/conda-forge/git-annex-feedstock/blob/master/recipe/build.sh#L49
gives the error.
