### ISSUE TITLE
Allow debug toggle during long running processes

### ISSUE THREAD

**Issue by Shumakriss** [conda/conda#8382]
When doing `conda env create` or some other commands, the "Solving Environment" message is printed.  There are lots of tickets and posts online about this message. Sometimes this might hang but perhaps most of them are just time consuming. Users are afraid to cancel because they don't want something to break, lose progress, or ctrl-c interrupt just doesn't work. 

New, returning, or infrequent users may forget to add the debug flag or may only want to know if the process is truly hanging. I imagine there is no perfect log-level or else that would be the default. I suggest adding a key command to toggle verbose logging. For example, an interrupt for ctrl-z or some other key combination could set debug logging on and off. Including this in the "Solving Environment" message could allow users to check in on the progress.

**Comment by msarahan** [comment]
This is an excellent idea.  I'm not really sure how to implement it, though.  If anyone has ideas, please add to this discussion or submit a PR.
