### ISSUE TITLE
Anaconda should pass Ctrl-C/Ctrl-Break to the underlying python process so it could be able to handle it

### ISSUE THREAD

**Issue by agcala** [conda/conda#8396]
I think there should be an option for users to be allowed to handle **KeyboardInterrupt** themselves. I mean, there is currently no way the signal can reach the underlying python program.
When I press `Ctrl-C` I get something like
```
forrtl: error (200): program aborting due to control-BREAK event
Image              PC                Routine            Line        Source

libifcoremd.dll    000007FEE48F3B58  Unknown               Unknown  Unknown
KERNEL32.dll       0000000077A14CE3  Unknown               Unknown  Unknown
KERNEL32.dll       00000000779D59CD  Unknown               Unknown  Unknown
ntdll.dll          0000000077C3385D  Unknown               Unknown  Unknown

```
**I wish I could be able to handle the exception myself.**

**Comment by mingwandroid** [comment]
Please see https://github.com/ContinuumIO/anaconda-issues/issues/905#issuecomment-232498034
