### ISSUE TITLE
[Windows] Environment has not been activated

### ISSUE THREAD

**Issue by hagamuna** [conda/conda#8412]
Hi,

I wanted my base python version to always be updated to the latest version on my Windows machine
However in doing so, conda commands will now always return: 
"The system cannot find the path specified"

# Simple reproduction
1. install miniconda
(not Anaconda, this adds a ton of overhead)

Side note: The local user and system %path% variables have more 1048 (or 2048) characters.
(And yes, this path is already reduced by using environment variables)
So conda won't work properly unless we use the 'add to path' checkbox while installing.

2. Restart PC (to ensure path variables work properly)

3. Open a cmd.exe with Administrator

4. Update conda using:
`conda update conda`
Note: This does not seem to update everything, since python version remains 3.7.1, instead of latest 3.7.2

5.  Update all packages, to ensure python and all it's packages are updated in the base environment
`conda update --all`

6. Start python;
`python`

Result:
```
Python 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
```

At least the version seems to be correct :)
Anyway you can already see what is wrong, apparently it expects the environment to be activated.

Lets do that:
`activate base`
Result
`The system cannot find the path specified.`

Same goes for deactivation
`conda deactivate`
Result
`The system cannot find the path specified.`

**Comment by jpgill86** [comment]
I'm speculating, but this might be indirectly related to https://github.com/conda/conda/issues/8404#issuecomment-472993777, specifically the first problem described. You could try the hack described [here](https://github.com/conda/conda/issues/8404#issuecomment-472951203) to see if it fixes your problem.

**Comment by msarahan** [comment]
This is going to be pretty hard to debug with the information you've provided.  What does ``where conda`` show on your cmd.exe?

**Comment by hagamuna** [comment]
`where conda`
```
D:\Miniconda3\Library\bin\conda.bat
D:\Miniconda3\Scripts\conda.exe
```

I looked further into it and it seems that
 D:\Miniconda3\Library\bin\conda.bat
internally calls D:\Miniconda3\condabin\conda.bat

I called that second script by hand, which gives the 
`The system cannot find the path specified.`
So it's actually the second script that contains the problem.

I also looked into  #8404 (comment), they specify that CONDA_BAT variable might be empty.
In my case is, e.g:
```
echo %CONDA_BAT%
<returns nothing>

activate conda
echo %CONDA_BAT%
<returns nothing>
```

Looking further into D:\Miniconda3\condabin\conda.bat
I added echo statements and it's line 5 and 6 that cause
`The system cannot find the path specified.`

I think it's this part:
`"%~dp0_conda_activate" %*`

**Comment by hagamuna** [comment]
Update solved the second problem, e.g
`The system cannot find the path specified.`

The solution, run this command in administator cmd prompt.
`conda init`
Then close the prompt and open a new one.

**Comment by hagamuna** [comment]
when i run `python` in admin cmd prompt, I still get.
```
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation
```

Note: the warning goes away after activating an environment. (which can be base.)
```
conda activate base
python
```
```
Python 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by mingwandroid** [comment]
> when i run python in admin cmd prompt, I still get.

Activation has nothing to do with admin.

**Comment by msarahan** [comment]
admin is also called "elevation" and yes, this is very different from the "activation" that the warning message is telling you to do.

Even without any CONDA_BAT being set, running

```
<path to miniconda>\Scripts\activate base
```

works for me.  I'm not sure what's causing the system to not be able to find something.  It might be spaces or something like that in your install path.  With the information you've provided, we can't say anything more.  Please always fill out the info requested by the issue template.

**Comment by edreamleo** [comment]
@msarahan Thanks for this!

My experience today (September 12, 2019):

- Downloaded Anaconda3-2019.07-Windows-x86_64.exe
- Installed Anaconda3 in c:\Anaconda3, with raised permissions, without setting the path in the installer.  Not surprisingly, python is not found.
- Added c:\Anaconda3 and c:\Andaconda3\scripts to the path.
  Now typing python from a console gives the warning above.
  Worse, almost all conda operations crashed.  Alas, I didn't make a copy of the crash report.
- Following your suggestion, ran c:\Anaconda3\scripts\activate base.
  Now everything appears to work

I don't see anything about this topic in the [trouble shooting section](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html).

**Comment by mingwandroid** [comment]
I think we should try to make our documentation about the correct command line usage of Anaconda Distribution to a more prominent location.

**Comment by PraveenGouchandra** [comment]
c:\Anaconda3\scripts>activate base     This command worked for me too.

**Comment by Adesoji1** [comment]
C:\Users\soj4y>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>>                      

How do I  activate the environment?

**Comment by mingwandroid** [comment]
By running `conda activate` or using the `Anaconda Prompt`.

**Comment by mardhiah34** [comment]
> @msarahan Thanks for this!
> 
> My experience today (September 12, 2019):
> 
> * Downloaded Anaconda3-2019.07-Windows-x86_64.exe
> * Installed Anaconda3 in c:\Anaconda3, with raised permissions, without setting the path in the installer.  Not surprisingly, python is not found.
> * Added c:\Anaconda3 and c:\Andaconda3\scripts to the path.
>   Now typing python from a console gives the warning above.
>   Worse, almost all conda operations crashed.  Alas, I didn't make a copy of the crash report.
> * Following your suggestion, ran c:\Anaconda3\scripts\activate base.
>   Now everything appears to work
> 
> I don't see anything about this topic in the [trouble shooting section](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html).

hi can you give the proper documentation for this,because im new here. i already followed this step. but when ran the c:\Anaconda\scripts\activate base. The python still appear the same message as above. Please need your consultation.

**Comment by mardhiah34** [comment]
> admin is also called "elevation" and yes, this is very different from the "activation" that the warning message is telling you to do.
> 
> Even without any CONDA_BAT being set, running
> 
> ```
> <path to miniconda>\Scripts\activate base
> ```
> 
> works for me. I'm not sure what's causing the system to not be able to find something. It might be spaces or something like that in your install path. With the information you've provided, we can't say anything more. Please always fill out the info requested by the issue template.

need your help

**Comment by ephantusGachomba** [comment]
> * Anaconda3\scripts\activate base

thanks for this.worked perfectly
