### ISSUE TITLE
CondaDependencyError: Cannot run solver. No functioning SAT implementations available.

### ISSUE THREAD

**Issue by GodZarathustra** [conda/conda#8418]
### Steps to Reproduce

```
 few minutes ago, conda worked well, but just now, it broken.
in the env of "tensorflow" had python 3.5, but it suddenly disappeard. all of the pakages in "tensorflow" are gone. so I tried to reinstall them, I tried  below but output.......
(tensorflow) C:\Users\Admin>conda install python==3.5
Collecting package metadata: done
Solving environment: / WARNING conda.common.logic:get_sat_solver_cls(278): Could not run SAT solver through interface 'pycosat'.
failed

CondaDependencyError: Cannot run solver. No functioning SAT implementations available.
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

(tensorflow) C:\Users\Admin>conda info

     active environment : tensorflow
    active env location : F:\Anaconda3\envs\tensorflow
            shell level : 2
       user config file : C:\Users\Admin\.condarc
 populated config files : C:\Users\Admin\.condarc
          conda version : 4.6.8
    conda-build version : 3.15.1
         python version : 3.5.0.final.0
       base environment : F:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : F:\Anaconda3\pkgs
                          C:\Users\Admin\.conda\pkgs
                          C:\Users\Admin\AppData\Local\conda\conda\pkgs
       envs directories : F:\Anaconda3\envs
                          C:\Users\Admin\.conda\envs
                          C:\Users\Admin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.19.1 CPython/3.5.0 Windows/ Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(tensorflow) C:\Users\Admin>conda config --show-sources
==> C:\Users\Admin\.condarc <==
channels:
  - defaults
ssl_verify: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at F:\Anaconda3\envs\tensorflow:
#
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen    defaults
absl-py                   0.7.0                    py27_0    defaults
astor                     0.7.1                    py27_0    defaults
backports                 1.0                      py27_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports_abc             0.5              py27h0ec6b72_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py27_0    defaults
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
cloudpickle               0.8.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.6           py27hc56fc5f_0    defaults
dill                      0.2.9                    pypi_0    pypi
enum34                    1.1.6                    py27_1    defaults
freetype                  2.9.1                h4d385ea_1    defaults
functools32               3.2.3.2                  py27_1    defaults
future                    0.17.1                   pypi_0    pypi
futures                   3.2.0                    py27_0    defaults
gast                      0.2.2                    py27_0    defaults
glob2                     0.6                      pypi_0    pypi
gym                       0.12.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 h2aa20d9_1    defaults
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.1                      144    defaults
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9b                   ha175dff_2    defaults
kiwisolver                1.0.1                    pypi_0    pypi
libpng                    1.6.36               h7a46e7a_0    defaults
libprotobuf               3.5.2                hde7a951_0    defaults
markdown                  3.0.1                    py27_0    defaults
matplotlib                3.0.2                    pypi_0    pypi
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py27hac4a418_0    defaults
mpi4py                    3.0.1                    pypi_0    pypi
numpy                     1.14.5                   pypi_0    pypi
numpy-base                1.14.5           py27h0bb1d87_4    defaults
opencv-python             4.0.0.21                 pypi_0    pypi
openssl                   1.0.2r               h0c8e037_0    defaults
pandas                    0.24.1                   pypi_0    pypi
pillow                    5.4.1                    pypi_0    pypi
pip                       19.0.3                   py27_0    defaults
progressbar2              3.39.2                   pypi_0    pypi
protobuf                  3.5.2            py27hc56fc5f_1    defaults
pyglet                    1.3.2                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 2.3.1                    py27_0    defaults
pyqt                      5.6.0            py27h6e61f57_6    defaults
python                    2.7.15              hcb6e200_15    defaults
python-dateutil           2.8.0                    py27_0    defaults
python-utils              2.3.0                    pypi_0    pypi
pytz                      2018.9                   py27_0    defaults
pyzmq                     18.0.1                   pypi_0    pypi
qt                        5.6.2            vc9hc26998b_12    defaults
requests                  2.21.0                   pypi_0    pypi
scipy                     1.2.1                    pypi_0    pypi
seaborn                   0.9.0                    pypi_0    pypi
setuptools                39.1.0                   pypi_0    pypi
singledispatch            3.4.0.3          py27h3f9d112_0    defaults
sip                       4.18.1           py27hc56fc5f_2    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.27.2               h0c8e037_0    defaults
stable-baselines          2.4.1                     dev_0    <develop>
swig                      3.0.12               h5a33001_3    defaults
termcolor                 1.1.0                    py27_1    defaults
tornado                   5.1.1            py27h0c8e037_0    defaults
tqdm                      4.31.1                   pypi_0    pypi
urllib3                   1.24.1                   pypi_0    pypi
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.33.1                   py27_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
zlib                      1.2.11               h3cc03e0_3    defaults
zmq                       0.0.0                    pypi_0    pypi
```
</p></details>

**Comment by farazarbabi** [comment]
Getting the same error:
$conda update conda
Collecting package metadata: done
Solving environment: / WARNING conda.common.logic:get_sat_solver_cls(278): Could not run SAT solver through interface 'pycosat'.
failed

CondaDependencyError: Cannot run solver. No functioning SAT implementations available.

**Comment by AyrisA** [comment]
Me too.

**Comment by msarahan** [comment]
There are no official conda 4.6.8 builds for python 3.5.  It seems like conda downgraded python in the base env somehow?  This seems likely related to the work being done in #8444

**Comment by llinjupt** [comment]
Me too, any advise?
`$ conda update anaconda-navigator
Collecting package metadata: ...working... done
Solving environment: ...working... WARNING conda.common.logic:get_sat_solver_cls(278): Could not run SAT solver through interface 'pycosat'.
failed

CondaDependencyError: Cannot run solver. No functioning SAT implementations available.
`

**Comment by learningandthinking** [comment]
how to solve it? Me too.
(base) C:\WINDOWS\system32>conda update anaconda-navigator
Collecting package metadata: done
Solving environment: | WARNING conda.common.logic:get_sat_solver_cls(278): Could not run SAT solver through interface 'pycosat'.
failed

CondaDependencyError: Cannot run solver. No functioning SAT implementations available.

**Comment by mrevow** [comment]
Same thing happened to me after I upgraded my python from 3.6 to 3.7. The upgrade also broke many packages. Following [this](https://github.com/conda/conda/issues/7714#issuecomment-417553149) suggestion fixed the conda environment for me

**Comment by jgodwin** [comment]
Just had this happen to me, except I was explicitly trying to avoid upgrading my Anaconda installation. Unfortunately, Anaconda has a mind of its own, and will upgrade certain (unrelated) packages at times regardless of what else you're doing.  It seems in my case, reinstalling Spyder caused the entire ecosystem to come crashing down.

**Comment by jspindola** [comment]
I was trying to install Theano in my Anaconda environment but I got this same error. Is there a solution for this? Conda env is:

`active environment : base`
` active env location : C:\Users\Fede\Anaconda3`
           `shell level : 1`
       `user config file : C:\Users\Fede\.condarc`
` populated config files : C:\Users\Fede\.condarc`
          `conda version : 4.8.1`
   ` conda-build version : 3.18.11`
        ` python version : 3.7.6.final.0`
      ` virtual packages : __cuda=10.2`
      ` base environment : C:\Users\Fede\Anaconda3  (writable)`
          ` channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64`
                         ` https://conda.anaconda.org/anaconda-fusion/noarch`
                         ` https://repo.anaconda.com/pkgs/main/win-64`
                         ` https://repo.anaconda.com/pkgs/main/noarch`
                         ` https://repo.anaconda.com/pkgs/r/win-64`
                         ` https://repo.anaconda.com/pkgs/r/noarch`
                         ` https://repo.anaconda.com/pkgs/msys2/win-64`
                         ` https://repo.anaconda.com/pkgs/msys2/noarch`
         ` package cache : C:\Users\Fede\Anaconda3\pkgs`
                         ` C:\Users\Fede\.conda\pkgs`
                         ` C:\Users\Fede\AppData\Local\conda\conda\pkgs`
      ` envs directories : C:\Users\Fede\Anaconda3\envs`
                          `C:\Users\Fede\.conda\envs`
                          `C:\Users\Fede\AppData\Local\conda\conda\envs`
              `platform : win-64`
             `user-agent : conda/4.8.1 requests/2.21.0 CPython/3.7.6 Windows/10 Windows/10.0.18362`
          `administrator : True`
             `netrc file : None`
           `offline mode : False`
