### ISSUE TITLE
Broken link in the docs. 

### ISSUE THREAD

**Issue by kylekeppler** [conda/conda#8419]
Page that contains the link: https://conda.io/projects/conda/en/latest/commands/config.html

Broken link: https://conda.io/docs/config.html

Correct link? https://conda.io/projects/conda/en/latest/configuration.html

**Comment by rrigdon** [comment]
Thanks for catching these! I've updated the link so that it now directs to https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html
