### ISSUE TITLE
ERROR conda.core.link:_execute(568): An error occurred while installing package '<unknown>::atomicwrites-1.3.0-py_0'

### ISSUE THREAD

**Issue by tmblue** [conda/conda#8422]
I've read various bug reports and the only one that felt somewhat right was regarding conda having issues with noarch files. But a standard install works fine, but I'm working on attempting to package these. and running into quite a few issues, but lets focus on this error
-->

## Current Behavior

...
# conda install -n test --offline /modules/*
Downloading and Extracting Packages
lots of status #### 

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package '<unknown>::atomicwrites-1.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/pypricer/envs/test/bin/python3.6'")
Attempting to roll back.

Rolling back transaction: done

[Errno 2] No such file or directory: '/pypricer/envs/test/bin/python3.6': '/ipix/pypricer/envs/test/bin/python3.6'

However
@ml01.dev.ca modules # cd /pypricer/envs/test/bin/python3.6
python3.6          python3.6-config   python3.6m         python3.6m-config 

So files are there, I think the no /bin/python3.6 is a red herring and the issue is that atomicwrites is having an issue..
```
### Steps to Reproduce
```
Simple CentOS 7.2
yum install conda
conda create -n test --offline <path to packages>
This fails because it doesn't create a /bin directory with python in it..  <another weird behaviour, but not new based on searching bugs, but have not found resolution>

okay then

conda create -n test python=3.6  (this at least gives me a /bin directory under env/test/)

conda install -n test --offline <path to packages>

--- 
I should not have to run a create and an install, a create should work but again it doesn't create the bin directory even though there is a /modules/python-3.6.8-h0371630_0.tar.bz2  file in the path that I assign. Still won't create a bin directory and thus dies.

However this is more in line with "when there is a bin directory created and a python3.6 binary why is it complaining. Again my guess is this has something to do with the noarch variety of atomicwrites-1.3.0-py_0'.  But I'm not clear, just bits and pieces I'm picking up in other bug reports.
```

```

## Expected Behavior

I think it should create an environment including a /bin directory and install the packages that I've provided it :)

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
                          /root/.condarc
          conda version : 4.6.8
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /pypricer/pkgs
       envs directories : /pypricer/envs
                          /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.6.8 Linux/3.10.0-327.10.1.el7.x86_64 centos/7.2.1511 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /opt/conda/.condarc <==
envs_dirs:
  - /pypricer/envs
pkgs_dirs:
  - /pypricer/pkgs
channels:
  - defaults

==> /root/.condarc <==
envs_dirs:
  - /pypricer/envs
pkgs_dirs:
  - /pypricer/pkgs
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py36_0    defaults
cffi                      1.12.2           py36h2e261b9_1    defaults
chardet                   3.0.4                    py36_1    defaults
conda                     4.6.8                    py36_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.6.1            py36h1ba5d50_0    defaults
idna                      2.8                      py36_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pip                       19.0.3                   py36_0    defaults
pycosat                   0.6.3            py36h14c3975_0    defaults
pycparser                 2.19                     py36_0    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.8                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h14c3975_0    defaults
setuptools                40.8.0                   py36_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.24.1                   py36_0    defaults
wheel                     0.33.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by msarahan** [comment]
> conda create -n test --offline 

This creates an empty environment.  You provided no specs whatsoever, so conda didn't install anything.

> conda install -n test --offline /modules/*

By installing things this way (file path, as opposed to spec name), conda will not do any dependency resolution for you.  Things will probably not be installed in order, and it will not work.  You need to read up on "conda index" and pass a local file:/// url as a channel.

**Comment by tmblue** [comment]
Thanks msarahan, will do so!!!
