### ISSUE TITLE
pip installation failed with 'contains unsafe path' error

### ISSUE THREAD

**Issue by malmaud** [conda/conda#8423]
## Current Behavior

Running `conda install pip` in an environment produces an error 

```
CondaFileIOError: '/anaconda3/pkgs/pip-19.0.3-py37_0.tar.bz2'. contains unsafe path: bin/pip
```

### Steps to Reproduce

```
~ $ conda create -n myenv pip
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/myenv

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-19.0.3                 |           py37_0         1.8 MB
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/osx-64::certifi-2019.3.9-py37_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1b-h1de35cc_1
  pip                pkgs/main/osx-64::pip-19.0.3-py37_0
  python             pkgs/main/osx-64::python-3.7.2-haf84260_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-40.8.0-py37_0
  sqlite             pkgs/main/osx-64::sqlite-3.27.2-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.1-py37_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-19.0.3           | 1.8 MB    | ######################################################## | 100%

CondaFileIOError: '/anaconda3/pkgs/pip-19.0.3-py37_0.tar.bz2'. contains unsafe path: bin/pip

```

## Expected Behavior

Pip installs successfully.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : tftest
    active env location : /anaconda3/envs/tftest
            shell level : 2
       user config file : /Users/malmaud/.condarc
 populated config files : /Users/malmaud/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda3/pkgs
                          /Users/malmaud/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/malmaud/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/malmaud/.condarc <==
changeps1: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /anaconda3/envs/tftest:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by stephan-jacobs** [comment]
I got a similar error when I tried to create a new environment, except the unsafe path was bin/python

**Comment by s18692001** [comment]
me too!

**Comment by cphyc** [comment]
Hey I had the same issue which seemed to be due to the anaconda distribution being on a different partition as the cwd one.

At least for me, moving to the same partition as anaconda's solved the problem.

**Comment by sungwonida** [comment]
@cphyc Thank you for figuring this out. That solved my problem. Though, one should change the directory(`cd`) into the desired environment path, not the path where anaconda is installed.

```
$ cd /home/anaconda3/envs/test-env
$ conda install whatever
```

**Comment by paulraines68** [comment]
I got this issue installing pyopencl which requires you symlink $ANACONDAROOT/lib/OpenCL/vendors to your system opencl headers (e.g. /usr/include/CL).  I did that and when I tried to conda install pyopencl I got

`CondaFileIOError: '/usr/pubsw/packages/python/anaconda3-2019.03/pkgs/ocl-icd-2.2.12-h14c3975_1003.tar.bz2'. contains unsafe path: etc/OpenCL/vendors/.conda_keep`

I think this should be possible.  I worked around by copying over /usr/include/CL instead since it is small

**Comment by jasercion** [comment]
I've had a couple users of our software running into this error when creating an environment with a prefix on a different partition than the installation.  Shouldn't this be possible and didn't this work in previous releases?

Or am I just being dense?

**Comment by zkaufman** [comment]
@jasercion I frequently create environments with a prefix on a different partition than the installation. That in itself doesn't cause the problem. In my case, the issue only ever occurred when conda was installed somewhere on the network (not locally) and I was running it from a different partition. I have found the best way to avoid the error is to install conda locally, not on a network disk.

**Comment by jasercion** [comment]
@zkaufman Ah, gotcha.  IIRC in our error case the users are using a distributed computing environment so it sounds like that is in fact the root cause.
