### ISSUE TITLE
Problems with cloning conda environment

### ISSUE THREAD

**Issue by ravimulpuri** [conda/conda#8426]
I am trying to clone an existing conda environment. For some reason it is not able to find some of the packages that I have installed in my previous envrionement through `pip/pypi`. Is this behavior expected. If so, please forgive my ignorance.

I get the following error while I try to clone the environment. It can't clone some of the packages that I have installed in my previous environment using `python setup.py develop`. Is this due to corrupt behavior of my `.condarc` file ?

```
PackagesNotFoundError: The following packages are missing from the target environment:
  - sqlparse==0.2.4=pypi_0
  - sqlalchemy==1.2.18=pypi_0
  - grpcio==1.17.0=pypi_0
  - psycopg2==2.7.7=pypi_0
  - sp-io==2.0.24=dev_0
  - absl-py==0.6.1=pypi_0
  - psycopg2-binary==2.7.7=pypi_0
  - luminol==0.4=pypi_0
  - gast==0.2.0=pypi_0
  - downhill==0.4.0=pypi_0
  - html5lib==0.9999999=pypi_0
  - bokeh==1.0.4=pypi_0
  - theano==1.0.3=pypi_0
  - prettytable==0.7.2=pypi_0
  - stldecompose==0.0.3=pypi_0
  - wheel==0.32.3=pypi_0
  - isort==4.3.4=pypi_0
  - deepdish==0.3.6=pypi_0
  - future==0.16.0=pypi_0
  - fastcluster==1.1.25=pypi_0
  - pip==19.0.3=pypi_0
  - bleach==1.5.0=pypi_0
  - pyviz-comms==0.7.0=pypi_0
  - numpy==1.14.5=pypi_0
  - werkzeug==0.14.1=pypi_0
  - setuptools==39.1.0=pypi_0
  - six==1.12.0=pypi_0
  - ipython-sql==0.3.9=pypi_0
  - tensorboard==1.6.0=pypi_0
  - protobuf==3.6.1=pypi_0
  - markdown==3.0.1=pypi_0
  - fastdtw==0.3.2=pypi_0
  - swifter==0.273=pypi_0
  - imbalanced-learn==0.4.3=pypi_0
  - pandas-profiling==1.4.1=pypi_0
  - pyarrow==0.11.1=pypi_0
  - pgspecial==1.11.5=pypi_0
```

**Comment by rtmatx** [comment]
I did some digging and realized that there no urls for the packages listed above when I used `conda list explicit`. What kind of behavior invokes such thing ?

I pasted a subset of the output generated by `conda list explicit`

```
# no URL for: tensorboard-1.6.0.dist-info
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-1.10.0-gpu_py36h8dbd23f_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/umap-learn-0.3.6-py36_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xarray-0.10.9-py36_0.tar.bz2
https://conda.anaconda.org/pyviz/label/dev/noarch/datashader-0.7.0a1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fiona-1.7.12-py36h3f37509_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-4.10.0-py36_0.tar.bz2
# no URL for: ipython_sql-0.3.9.dist-info
https://repo.anaconda.com/pkgs/main/linux-64/keras-2.2.4-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/nbconvert-5.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/seaborn-0.9.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/service_identity-17.0.0-py36h28b3542_0.tar.bz2
# no URL for: stldecompose-0.0.3.dist-info
# no URL for: swifter-0.273.dist-info
```

**Comment by tjd2002** [comment]
These all appear to be pip-installed packages. I am running into the same issue when I try to clone an env that includes pip-installed packages. 

In the past I think `clone` would just copy over the packages it new about. I'm not sure how to force the clone...

**Comment by tjd2002** [comment]
Do you have `pip_interop_enabled` enabled? (`conda config --show pip_interop_enabled`). I did, and this error was resolved when I set it to false.

```conda config --set pip_interop_enabled false```

I think this is a bug (?) so will open a more specific issue. If changing this setting fixes the issue for you, I think you can close this one.

**Comment by And0k** [comment]
Confirm bug with `pip_interop_enabled true` but I have not used pip yet. After installing environment (from yml file that not contained pip section), next my command cloning this env was `conda create ... --clone ...` which fails:
```
PackagesNotFoundError: The following packages are missing from the target environment:
  - pyqtchart==5.12=pypi_0
  - pyqtwebengine==5.12.1=pypi_0
  - pyqt5-sip==4.19.18=pypi_0
```
After setting `pip_interop_enabled false` same command was executed without errors
