### ISSUE TITLE
valid 'UTF-8', 'utf8', 'UTF-7', and 'utf7' PYTHONIOENCODING cause errors in `conda`

### ISSUE THREAD

**Issue by rivy** [conda/conda#8429]
## Current Behavior

`conda` produces an error message (`Parameter format not correct - UTF-8`) when used.

### Steps to Reproduce

```
C:\>chcp
Active code page: 65001

C:\>set PYTHONIOENCODING
PYTHONIOENCODING=UTF-8

C:\>conda upgrade conda -y
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

Parameter format not correct - UTF-8
```

## Expected Behavior

No error message should be produced.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\Roy\.condarc
 populated config files : C:\Users\Roy\.condarc
          conda version : 4.6.8
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\Roy\AppData\Local\scoop\apps\python\3.7.1  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Roy\AppData\Local\scoop\apps\python\3.7.1\pkgs
                          C:\Users\Roy\.conda\pkgs
                          C:\Users\Roy\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Roy\AppData\Local\scoop\apps\python\3.7.1\envs
                          C:\Users\Roy\.conda\envs
                          C:\Users\Roy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : C:\Users\Roy/.netrc
           offline mode : False
```
</p></details>

## Discussion and Repair

'UTF-8', 'UTF8', 'UTF-7', 'UTF7' (case-insensitive) are valid, working arguments for PYTHONIOENCODING, used to avoid encoding issues for Python2.7 when using unicode code pages in windows (see <https://github.com/conda/conda/issues/5448#issuecomment-304675551> and <https://stackoverflow.com/a/12834315/43774>). The corresponding unicode code pages in Windows 10 are 65000 (ie, 'utf-7') and 65001 (ie, 'utf-8').

Using any of the above noted values for PYTHONIOENCODING will cause issues when using `conda`, specifically when `_conda_activate reactivate` is triggered (eg, by `conda upgrade`). The final line in the `_conda_activate` script executes a `chcp %PYTHONIOENCONDING%` (`chcp %PYTHONIOENCODING:cp=%` in the most recent repo code), but `chcp` doesn't understand any of the noted values ('utf8', ...). This causes an error to be printed on STDERR ('Parameter format not correct - UTF-8'). Attempted workarounds using 'cp65001' or '65001' in place of 'utf-8' for PYTHONIOENCODING don't work as Python doesn't understand those as known encodings.

Replacing ...

```
@IF DEFINED PYTHONIOENCODING chcp %PYTHONIOENCODING:cp=% > NUL
```

with ...

```
@setlocal
@set codepage=%PYTHONIOENCODING:cp=%
@if /i "%codepage:-=%" == "utf7" set codepage=65000
@if /i "%codepage:-=%" == "utf8" set codepage=65001
@endlocal & if NOT "%codepage%" == "" chcp %codepage% > NUL
```

does fix the problem.

**Comment by rivy** [comment]
@msarahan , would you like me to submit a PR with the mentioned change?

**Comment by msarahan** [comment]
Have you tried the latest conda builds? I think this might already be fixed.

**Comment by rivy** [comment]
I haven't. I'll look into it.

**Comment by rivy** [comment]
@msarahan , you're correct.
The error no longer occurs with `conda` version 4.6.14.
Thanks for the response.
👍
