### ISSUE TITLE
conda process error (3 relevant issue)

### ISSUE THREAD

**Issue by yoyocandy** [conda/conda#8442]
Hi, I am totally new for this. So I have not only one issue about conda.
first one:
I couldn't install R or other applications like orange through anconda navigator or in the pycharm terminal. It comes out kinds of problem. Error 404 or like unter. I saw many tips about the flase or invalid Channel. add or change the channel and try to figure it out. but no success.
`
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json.bz2><br>Elapsed: -<br><br>An HTTP error occurred when trying to retrieve this URL.<br>HTTP errors are often intermittent, and a simple retry will get you on your way.<br><br>If your current network has https://www.anaconda.com blocked, please file<br>a support request with your network engineering team.<br><br>ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/msys2/noarch/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002A805D8C240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"))<br>`
![conda](https://user-images.githubusercontent.com/47516521/54876647-2794f580-4e4e-11e9-8f59-9a412dccd83c.PNG)

issue 2:
I can't input any command in anaconda prompt, it always sends me the same inhalt. but I can do it through cmd. I install anaconda in E:/ but I have added its path into system env.
![prompt](https://user-images.githubusercontent.com/47516521/54876667-8eb2aa00-4e4e-11e9-85dc-7159c7afe4f4.PNG)

issue 3;
in Pycharm I couldn't add any third party package throug the lovely "+", although the conda in pycharm has already many useful packages. the only way to install those packages is through "Terminal", but only use< pip install>, not <conda install>.

at last, I installed all the anaconda, python,pycharm in the same disk, also not the C:/
please tell me what could I do. those trouble me for few days.
![pycharm](https://user-images.githubusercontent.com/47516521/54876777-7ba0d980-4e50-11e9-8012-8e5301cd3614.PNG)
![pycharm2](https://user-images.githubusercontent.com/47516521/54876780-8b202280-4e50-11e9-8981-c02c4f87a07d.PNG)

**Comment by msarahan** [comment]
Please see

https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#condahttperror-http-000-connection-failed

**Comment by yoyocandy** [comment]
> Please see
> 
> https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#condahttperror-http-000-connection-failed

thanks

**Comment by yoyocandy** [comment]
Thank you for your reply.

I red it through and did what it says. But came out the error 440 and told me all the channel of conda are invalid(I deleted them one by one and came out the same error). So, I uninstalled the anaconda and install, it became worse, I can’t use the anaconda too, no matter how many times I try to uninstall and install, or uninstall Python 3.7 and install Anaconda again then python. There is no menu of anaconda in start menu, no anaconda navigator, no any of its application or prompt.

I’m exhausted. I give up, learn the python first, when I have the basic knowledge about that I will do it again.

Thanks again, for your help.

Have a nice day.

 

发件人: noreply@github.com <noreply@github.com> 代表 Mike Sarahan
发送时间: 2019年3月25日 1:01
收件人: conda/conda <conda@noreply.github.com>
抄送: yoyocandy <candy_ue@163.com>; Author <author@noreply.github.com>
主题: Re: [conda/conda] conda process error (3 relevant issue) (#8442)

 

Please see

https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#condahttperror-http-000-connection-failed
