### ISSUE TITLE
conda install * fails when install path contains $ symbols

### ISSUE THREAD

**Issue by epignatelli** [conda/conda#8447]
## Current Behavior

Runnin `conda install` with any package fails due to a `$` symbol in the install path. 
Echoing the path from a bash returns the wrong string.

### Steps to Reproduce

Making sure to install in a path that contains `$` in the string, the following will fail.
**This is not an issue about matplotlib**.!
I used it jsut as a toy case.
```
conda install matplotlib
```
Returns:
```
ERROR conda.core.link:_execute(507): An error occurred while installing package 'None'.FileNotFoundError(2, 'No such file or directory')
```

## Expected Behavior

Installation should succeed. It may be helpful to escape any `$` character that appears in the path before any operation.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\$$epignatel\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\$epignatel\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\$epignatel\AppData\Local\conda\conda\envs
                          C:\Users\$$epignatel\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.15063
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment]
Thanks for reporting this.  We'd welcome a community contribution of a test and a fix.  We currently have issues that are affecting more people, and can't dedicate time to this.

**Comment by epignatelli** [comment]
Thanks @msarahan.
I can give it a go, any idea where I should start look into?

**Comment by msarahan** [comment]
There's a ton of places where file paths get handled.  They might all need to be escaped somehow.  I would start at the place in the traceback and work backwards.  I definitely expect this to be a huge amount of work.  Is the juice worth the squeeze?

``conda.core.link:_execute(507)``
