### ISSUE TITLE
Issue with conda and root prefix (wrong paths for user config file and env directories)

### ISSUE THREAD

**Issue by KillianPremel** [conda/conda#8458]
I have a issue with Anaconda, I can't do anything. I can't open Anaconda Navigator, the issue is "root prefix". And when I try to install things with pip and conda, the error "The current user does not have write permissions to a required path" appears because of a wrong path.

I tried to uninstall and then install anaconda again. I've tried also with the .condarc file (that now in the last installation of Anaconda doesn't appear anymore).

Example of issue :

(base) C:\Users\emac>conda update conda Solving environment: done environment location: C:\Users\emac\Anaconda3

added / updated specs: - conda

The following packages will be UPDATED:

conda: 4.5.12-py37_0 --> 4.6.8-py37_0

Proceed ([y]/n)? y

Preparing transaction: done Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path. path: C:\Users\emac\ \Users\emac.conda\environments.txt

We can see the path is wrong, but I don't know how to change it.

When I execute conda info :

(base) C:\Users\emac>conda info

 active environment : base
active env location : C:\Users\emac\Anaconda3
        shell level : 1
   **user config file : C:\Users\emac\ \Users\emac\.condarc**

populated config files : conda version : 4.5.12 conda-build version : 3.17.6 python version : 3.7.1.final.0 base environment : C:\Users\emac\Anaconda3 (writable) package cache : C:\Users\emac\Anaconda3\pkgs C:\Users\emac\AppData\Local\conda\conda\pkgs envs directories : C:\Users\emac\Anaconda3\envs C:\Users\emac\AppData\Local\conda\conda\envs C:\Users\emac\ \Users\emac.conda\envs platform : win-64 user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134 administrator : False netrc file : None offline mode : False

If someone know how to change the paths (user config file and env directories), or have another solution, please tell me how to solve it. It's part of my internship and I am stuck right now.

**Comment by felixn** [comment]
Can you check what your HOME variable is set to?
`set HOME`
I've had an issue where conda failed to work when HOME contained another variable, for example %USERPROFILE%. Set a full path in HOME

**Comment by lyjbupt** [comment]
I meet similar problem, after clean up those strange HOME env variables, it works well now!
