### ISSUE TITLE
conda init (4.6.9): minor inconvenience with zsh

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#8474]
```
➜  ~ sudo docker exec -it play /bin/zsh
(eval):61: = not found
```

If I revert the commit https://github.com/conda/conda/commit/b0c04256981dcbb5378c8177e8fc04eb983dabe3 , the problem goes away.

**Comment by tyxxzjpdez** [comment]
same issue

**Comment by blmhemu** [comment]
+1
It was working fine until I have updated (conda update conda)

**Comment by Switham007** [comment]
Same issue with me, after conda update conda: 
zsh terminal says "...miniconda3/etc/profile.d/conda.sh:61: = not found"

**Comment by msarahan** [comment]
#8475 and #8476 should fix this.

**Comment by Switham007** [comment]
Thanks, that fixed it for me

**Comment by sandacn** [comment]
I've downgrade to 4.6.8. When this release ,  I'll check this whether is fixed.
```bash
conda install conda=4.6.8 
```
