### ISSUE TITLE
sparcc.py：IndexError: tuple index out of range

### ISSUE THREAD

**Issue by JinqunHuang** [conda/conda#8497]
Dear Friends,
I install SparCC by conda with this command:
conda install -c bioconda sparcc

Then I get the example file: example/fake_data.txt from 【https://github.com/TankMermaid/sparcc】.
The help massage can be printed successsfully by: python miniconda2/bin/SparCC.py -h.

[fake_data.txt](https://github.com/conda/conda/files/3042038/fake_data.txt)

Then I type this and get the error. would you please give me a favor. Thanks

python miniconda2/bin/SparCC.py xxxx/example/fake_data.txt -i 5 --cor_file=example/basis_corr/cor_sparcc.out
reading data
Finished parsing table.
Table dimensions: (200,50)
**** Data has been transposed! ****
First 3 column labels are :0 ,1 ,10
First 3 row labels are :0 ,1 ,10

computing correlations
        Running iteration0
Traceback (most recent call last):
  File "miniconda2/bin/SparCC.py", line 322, in <module>
    cor, cov = basis_corr(counts, method=algo, **kwargs)
  File "xxxx/miniconda2/bin/analysis_methods.py", line 46, in basis_corr
    cor_med, cov_med = SparCC.main(frame, algo=algo, **kwargs)
  File "xxxx/miniconda2/bin/SparCC.py", line 254, in main
    v_sparse, cor_sparse, cov_sparse = basis_corr(fracs, method=method, **kwargs)
  File "xxxx/miniconda2/bin/SparCC.py", line 182, in basis_corr
    k = f.shape[1]
IndexError: tuple index out of range

**Comment by jjhelmus** [comment]
This does not sound like an issue with conda itself but rather with `SparCC` or the packaging of the software by bioconda.  Please engage those communities for help resolving this issue.

**Comment by qingyangosu** [comment]
> Dear Friends,
> I install SparCC by conda with this command:
> conda install -c bioconda sparcc
> 
> Then I get the example file: example/fake_data.txt from 【[https://github.com/TankMermaid/sparcc】](https://github.com/TankMermaid/sparcc%E3%80%91).
> The help massage can be printed successsfully by: python miniconda2/bin/SparCC.py -h.
> 
> [fake_data.txt](https://github.com/conda/conda/files/3042038/fake_data.txt)
> 
> Then I type this and get the error. would you please give me a favor. Thanks
> 
> python miniconda2/bin/SparCC.py xxxx/example/fake_data.txt -i 5 --cor_file=example/basis_corr/cor_sparcc.out
> reading data
> Finished parsing table.
> Table dimensions: (200,50)
> **** Data has been transposed! ****
> First 3 column labels are :0 ,1 ,10
> First 3 row labels are :0 ,1 ,10
> 
> computing correlations
> Running iteration0
> Traceback (most recent call last):
> File "miniconda2/bin/SparCC.py", line 322, in
> cor, cov = basis_corr(counts, method=algo, **kwargs)
> File "xxxx/miniconda2/bin/analysis_methods.py", line 46, in basis_corr
> cor_med, cov_med = SparCC.main(frame, algo=algo, **kwargs)
> File "xxxx/miniconda2/bin/SparCC.py", line 254, in main
> v_sparse, cor_sparse, cov_sparse = basis_corr(fracs, method=method, **kwargs)
> File "xxxx/miniconda2/bin/SparCC.py", line 182, in basis_corr
> k = f.shape[1]
> IndexError: tuple index out of range

Hi Jinqun,

Did you get this error fixed? I also run into this IndexError issue when I perform Sparcc using my own dataset. I am wondering how you solve this problem. Thank you very much for your kind help!

**Comment by nicolereynolds1** [comment]
Hello, I am having the same error.  If a solution was found could someone please post it?  Thank you
