### ISSUE TITLE
Using a fast JSON parser for repo data

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#8500]
This came up recently in our meeting at AnacondaCON. Writing it down so we can track it.

@mariusvniekerk, suggested we should look at using another faster JSON parser for reading the repo data. Here is [a blogpost]( https://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/ ) with some Python JSON parser benchmarks. All of these are in Conda-forge. It looks like we should choose between `ujson` and `python-rapidjson`. Considering loading is the priority for users loading, `ujson` looks better. Though `python-rapidjson` is a bit faster for writing.

**Comment by jjhelmus** [comment]
For reference [mamba](https://github.com/QuantStack/mamba) uses [simdjson](https://github.com/lemire/simdjson) for parsing repodata JSON files.  This is a C++ library which seems to have Python bindings via [pysimdjson](https://github.com/TkTech/pysimdjson).

**Comment by jakirkham** [comment]
Is there a benchmark for that?

**Comment by jakirkham** [comment]
@kalefranz mentioned yesterday that he looked into this before (particularly with `ujson`) and it didn't matter much. Please feel free to correct this Kale in case I'm misremembering.

**Comment by kalefranz** [comment]
Yeah I’ve timed `ujson` before, and there wasn’t any discernible improvement. New on the scene is `smdjson` which I guess could be worth a try. Just benchmark it first before you jump in. Don’t switch it out blindly.

**Comment by jakirkham** [comment]
@jaimergp do you know if this is already handle with the `libmamba` work? No worries if not 🙂

(asking as this originally came up in the context of discussing Mamba's approach and ways to speed up Conda)

**Comment by jaimergp** [comment]
There are different JSONs involved:

* Repodatas: these are loaded by libmamba
* conda-meta/*.json: these are loaded by conda, so it can be a bottleneck for REALLY large environments, but I don't think it's one of the main problems right now

**Comment by jakirkham** [comment]
How big are we thinking? TensorFlow? PyTorch? Or even larger?

**Comment by jaimergp** [comment]
Big like "this is where I have installed all my packages ever for every project ever, I don't know what environments are". Like hundreds of packages.

**Comment by jaimergp** [comment]
This repo (https://github.com/tktech/json_benchmark) might be useful if we ever decide to change JSON parsers. I am looking into this as part of other work and it might not negligible...

**Comment by jaimergp** [comment]
Orrr maybe not? I patched conda so it imports `simdjson` instead of the builtin `json` and ran some `conda install numpy --dry-run` on a base Miniconda environment with conda-libmamba-solver enabled. 

Pay attention to the 4th row and see how the solve steps take like 5 seconds (first cell), the rest is overhead of the History class loading PrefixData (second cell, json intensive), sorting records in PrefixGraph for the solution (third cell), and some housekeeping.

Without simd:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/2559438/177980317-43cb24e7-acf2-42d1-8ce1-f9a2f4da84eb.png">


With simd:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/2559438/177980359-3022b8b0-9bd1-407d-970c-1d03eb8796ce.png">


I am using the [drop-in replacement API](https://pysimdjson.tkte.ch/dropin.html), which is not as performant; but the other option involves lazy access to the attributes, and conda models end up loading everything anyway.

**Comment by jakirkham** [comment]
Ok then we may need your help in figuring out how to use it better because something looks off in these profiles if the runtime is longer when using it

**Comment by TkTech** [comment]
@jaimergp do you have a repo with your changes in it, or a patch file?

**Comment by dholth** [comment]
The other day I tried orjson for something repodata related and stdlib json worked better. For one you have to feed it a whole string.

msgspec looks promising https://github.com/jcrist/msgspec which can save memory when using a predictable schema.

On my computer it takes 2.5s to `json.load(open('repodata.json'))` for the 182M `conda-forge/linux-64/repodata.json`

**Comment by dholth** [comment]
```
In [10]: with timeme():
    ...:     json.load(open('repodata.json'))
Took 2.2460153102874756s

In [11]: with timeme():
    ...:     ujson.load(open('repodata.json'))
Took 3.087876081466675s
```

Python 3.10

**Comment by jaimergp** [comment]
> @jaimergp do you have a repo with your changes in it, or a patch file?

Not really, I only batch replaced the `json` imports with the `simdjson` equivalent ones. There's also a couple of wrapping functions in `conda.common.serialize` that a lot of conda parts rely on for their JSON needs.

**Comment by jcrist** [comment]
> msgspec looks promising https://github.com/jcrist/msgspec which can save memory when using a predictable schema.

`msgspec` has a pretty efficient parser, and should have lower memory usage than other options like `orjson` or `simdjson` which require copying the initial memory buffer. However, the main way to save memory is to only load the part of the JSON document you care about (using a schema to specify those fields) - from the above conversation it sounds like `conda` will always be accessing all fields, so this isn't really relevant.

In my benchmarks, `msgspec` _with a schema_ is generally ~2x faster than orjson, which is the next fastest JSON parser I've found. Without a schema, `msgspec` is generally on par/slightly slower than `orjson` (but uses less memory). Schemas are useful for reasons other than decoding/encoding performance too:

- The type annotations play well with editor support/mypy/pyright. Accessing fields on a well defined object is more "ergonomic" than remembering what key names exist in a dictionary.
- A schema can help catch bugs in faulty inputs by raising a nice error message for invalid JSON objects, rather than having to catch these errors later on in your application (see https://jcristharif.com/msgspec/usage.html#typed-decoding).
- A schema lets you decode into non-standard object types without having to handle the conversions later on. For example, you can decode a list of strings directly into a `set[str]` if that's the datastructure your application uses internally.

That said, all of these are deeper changes than just swapping out a `json.loads` call. If that's all you want, then `msgspec.json.decode` *may* give you a performance boost, but it'd likely be on par with that from `orjson` or `pysimdjson` too.

**Comment by jakirkham** [comment]
Jim included [an example in msgspec]( https://jcristharif.com/msgspec/examples/conda-repodata.html ) recently parsing repodata, which may be of interest here

**Comment by jaimergp** [comment]
That's great! I wonder if we can ship something like that in `conda` itself, where the accessor functions can provide which fields are needed... In practice this might mean all fields are needed, so we'll have to see how fast it is in that case.

**Comment by jaimergp** [comment]
I have taken Jim's example and added more (almost all) repodata fields, and using the full repodata for noarch we get:

<details>

<summary>Modified Struct</summary>

```python
def query_msgspec(data: bytes) -> list[tuple[int, str]]:
    # Use Struct types to define the JSON schema. For efficiency we only define
    # the fields we actually need.
    class Package(msgspec.Struct):
        name: str
        size: int
        build: str
        build_number: int
        depends: List[str]
        license: str = ""
        md5: str
        name: str
        noarch: Union[str, bool, None] = None
        sha256: str
        size: int = 0
        subdir: str
        timestamp: int = 0
        version: str

    class RepoData(msgspec.Struct):
        packages: dict[str, Package]

    # Decode the data as a `RepoData` type
    repo_data = msgspec.json.decode(data, type=RepoData)

    # Sort packages by `size`, and return the top 10
    return sorted(
        ((p.size, p.name) for p in repo_data.packages.values()), reverse=True
    )[:10]
```

</details>


```
# 5-run average
# pysimdjson is not available on osx-arm64
json: 467.33 ms
orjson: 359.37 ms
msgspec: 316.92 ms
```

So yes, still a bit faster!

**Comment by jaimergp** [comment]
I fiddled a bit more with this example just to reach the same conclusion: JSON loading is not the limiting factor, but the massaging that `conda` does after the fact.

```
libmamba: 1593.37 ms
conda+json: 4438.75 ms
conda+orjson: 4346.93 ms
conda+msgspec: 4231.74 ms
```

So yes, we can save 200ms but that's not our problem.

Code attached here:

<details>

<summary>Python script</summary>

```python
import json
import time
from typing import List, Union
from functools import partial
import os
import urllib.request
import sys

os.environ["CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY"] = "False"

import msgspec
import orjson

# import requests
# import simdjson
import libmambapy
from conda.core.subdir_data import SubdirData
from conda.models.channel import Channel
from conda.gateways.logging import initialize_logging

initialize_logging()


def _sort_key(iterable):
    return sorted(
        ((p["size"], p["depends"]) for p in iterable["packages"].values()), reverse=True
    )[:10]


def _sort_attr(iterable):
    return sorted(
        ((p.size, p.depends) for p in iterable.packages.values()), reverse=True
    )[:10]


def _sort_subdir(iterable):
    return sorted(
        ((p.size, p.depends) for p in iterable["_package_records"]), reverse=True
    )[:10]


def load_msgspec(path: str):
    with open(path, "rb") as f:
        data = f.read()
    # Use Struct types to define the JSON schema. For efficiency we only define
    # the fields we actually need.
    class Package(msgspec.Struct):
        name: str
        size: int
        build: str
        build_number: int
        depends: List[str]
        license: str = ""
        md5: str
        name: str
        noarch: Union[str, bool, None] = None
        sha256: str
        size: int = 0
        subdir: str
        timestamp: int = 0
        version: str

        # PackageRecord requires a dict-like interface...
        # You will also need to patch this method in conda:
        # conda.core.subdir_data.SubdirData._process_raw_repodata
        # (line 470) so PackageRecord is instantiated like this:
        #   package_record = PackageRecord(**dict(info.items()))

        def get(self, attr, default=None):
            return getattr(self, attr, default)

        def __getitem__(self, key):
            try:
                return getattr(self, key)
            except TypeError:
                print(self, key)
                raise

        def update(self, *args, **kwargs):
            {}.update(*args, **kwargs)

        def __len__(self):
            return len(self.__struct_fields__)

        def items(self):
            return {field: getattr(self, field) for field in self.__struct_fields__}

        def __iter__(self):
            return iter(self.__struct_fields__)

    class RepoData(msgspec.Struct):
        packages: dict[str, Package]

        def get(self, attr, default=None):
            return getattr(self, attr, default)

        def __getitem__(self, key):
            return getattr(self, key)

        def update(self, *args, **kwargs):
            {}.update(*args, **kwargs)

    # Decode the data as a `RepoData` type
    return msgspec.json.decode(data, type=RepoData)


def query_msgspec(path: str):
    repo_data = load_msgspec(path)
    # Sort packages by `size`, and return the top 10
    return _sort_attr(repo_data)


def load_orjson(path: str) -> dict:
    with open(path, "rb") as f:
        data = f.read()
    return orjson.loads(data)


def query_orjson(path: str) -> list[tuple[int, str]]:
    repo_data = load_orjson(path)
    return _sort_key(repo_data)


def load_json(path: str) -> dict:
    with open(path, "rb") as f:
        data = f.read()
    return json.loads(data)


def query_json(path: str) -> list[tuple[int, str]]:
    repo_data = load_json(path)
    return _sort_key(repo_data)


def load_simdjson(path: str) -> dict:
    with open(path, "rb") as f:
        data = f.read()
    return simdjson.Parser().parse(data)


def query_simdjson(path: str) -> list[tuple[int, str]]:
    repo_data = load_simdjson(path)
    return _sort_key(repo_data)


def query_libmamba(path: str):
    pool = libmambapy.Pool()
    libmambapy.Repo(pool, "demo", path, "")


def query_conda(path: str, func=load_json):
    SubdirData._cache_.clear()
    subdir_data = SubdirData(Channel("unused", platform="noarch"))
    data = func(path)
    state = subdir_data._process_raw_repodata(data)
    return _sort_subdir(state)


libraries = [
    # ("json", query_json),
    # ("orjson", query_orjson),
    # ("simdjson", query_simdjson),
    # ("msgspec", query_msgspec),
    ("libmamba", query_libmamba),
    ("conda+json", query_conda),
    ("conda+orjson", partial(query_conda, func=load_orjson)),
    ("conda+msgspec", partial(query_conda, func=load_msgspec)),
]

if __name__ == "__main__":
    # Download the current_repodata.json file
    print("Downloading repodata.json...")
    urllib.request.urlretrieve(
        "https://conda.anaconda.org/conda-forge/noarch/repodata.json",
        "repodata.json",
    )

    # Run the query with each JSON library, timing the execution 5 times
    for lib, func in libraries:
        timings = []
        print(f"{lib}: ", end="")
        sys.stdout.flush()
        for _ in range(5):
            start = time.perf_counter()
            func("repodata.json")
            stop = time.perf_counter()
            timings.append(stop - start)
        print(f"{(sum(timings) / len(timings)) * 1000:.2f} ms")

```

**Comment by jcrist** [comment]
> JSON loading is not the limiting factor, but the massaging that conda does after the fact.

Thanks for the write up @jaimergp. Yeah, if you're having to walk the object tree and convert to a different internal representation that'll definitely be your bottleneck. To make the best use of `msgspec` you'd want to use the `msgspec.Struct` types for processing as well, avoiding the conversion overhead. Structs are designed to be more efficient than the standard PyObject data model, and in certain cases can speed up processing time too (see benchmark [here](https://jcristharif.com/msgspec/benchmarks.html#benchmark-structs)). This would be a more invasive change though, and might not be desired/worth it :shrug:.

For completeness, I've updated the script to make use of a `TypedDict` (see [docs here](https://jcristharif.com/msgspec/usage.html#typeddict)) rather than `msgspec.Struct` - this lets you still specify a schema to `msgspec`, but the decoded object is a `dict` instance rather than a `msgspec.Struct` instance, making it play nicer with conda's current internals. This doesn't change the conclusion above, you still would want to avoid this slow conversion path if possible.

```
json: 619.55 ms
orjson: 456.29 ms
msgspec: 350.82 ms
libmamba: 1382.59 ms
conda+msgspec: 5781.57 ms
conda+orjson: 5973.79 ms
conda+json: 6180.80 ms
```

<details>
<summary>Python script</summary>

```python
import json
import time
from typing import List, Union
from functools import partial
import os
import urllib.request
import sys

os.environ["CONDA_ADD_PIP_AS_PYTHON_DEPENDENCY"] = "False"

import msgspec
import orjson

import libmambapy
from conda.core.subdir_data import SubdirData
from conda.models.channel import Channel
from conda.gateways.logging import initialize_logging

initialize_logging()


def load_msgspec_dict(path: str):
    from typing_extensions import TypedDict, NotRequired

    with open(path, "rb") as f:
        data = f.read()

    class Package(TypedDict):
        name: str
        size: int
        build: str
        build_number: int
        depends: list[str]
        license: NotRequired[str]
        md5: str
        name: str
        noarch: NotRequired[Union[str, bool, None]]
        sha256: str
        size: int
        subdir: str
        timestamp: NotRequired[int]
        version: str

    class RepoData(TypedDict):
        packages: dict[str, Package]

    # Decode the data as a `RepoData` type
    return msgspec.json.decode(data, type=RepoData)


def load_msgspec(path: str):
    with open(path, "rb") as f:
        data = f.read()

    class Package(msgspec.Struct):
        name: str
        size: int
        build: str
        build_number: int
        depends: List[str]
        license: str = ""
        md5: str
        name: str
        noarch: Union[str, bool, None] = None
        sha256: str
        size: int = 0
        subdir: str
        timestamp: int = 0
        version: str

    class RepoData(msgspec.Struct):
        packages: dict[str, Package]

    # Decode the data as a `RepoData` type
    return msgspec.json.decode(data, type=RepoData)


def load_orjson(path: str) -> dict:
    with open(path, "rb") as f:
        data = f.read()
    return orjson.loads(data)


def load_json(path: str) -> dict:
    with open(path, "rb") as f:
        data = f.read()
    return json.loads(data)


def load_libmamba(path: str):
    pool = libmambapy.Pool()
    libmambapy.Repo(pool, "demo", path, "")


def load_conda(path: str, func=load_json):
    SubdirData._cache_.clear()
    subdir_data = SubdirData(Channel("unused", platform="noarch"))
    data = func(path)
    subdir_data._process_raw_repodata(data)


libraries = [
    ("json", load_json),
    ("orjson", load_orjson),
    ("msgspec", load_msgspec),
    ("libmamba", load_libmamba),
    ("conda+msgspec", partial(load_conda, func=load_msgspec_dict)),
    ("conda+orjson", partial(load_conda, func=load_orjson)),
    ("conda+json", load_conda),
]

if __name__ == "__main__":
    # Download the current_repodata.json file
    print("Downloading repodata.json...")
    urllib.request.urlretrieve(
        "https://conda.anaconda.org/conda-forge/noarch/repodata.json",
        "repodata.json",
    )

    for lib, func in libraries:
        print(f"{lib}: ", end="")
        sys.stdout.flush()
        start = time.perf_counter()
        func("repodata.json")
        stop = time.perf_counter()
        print(f"{(stop - start) * 1000:.2f} ms")
```


</details>

**Comment by jaimergp** [comment]
If we can make the whole codebase work with the `Struct` representation, I am sure we can make it competitive with `libmamba`. However, several parts of the loading plus post-processing (at solving time) end up overwriting parts of the repodata index :/ Not saying that it's impossible, just that it'd be non-trivial. Maybe with a wrapper class for the extra / overwritten metadata? 🤔 

@dholth - this might be the kind of work you might like!

**Comment by dholth** [comment]
@jaimergp I am interested in all kinds of conda performance, but I haven't figured out the role SubdirData plays when new solvers are in use.

**Comment by jaimergp** [comment]
Yes, there's little gain when we can use `libmamba` repodata fetchers and loaders directly. However, we are still relying on `SubdirData` for S3 and FTP channels (small %, true). For conda `classic` it would save a few seconds during the `Collecting metadata...` phase.

It would be a nice a complement (technology wise) to the JLAP-driven repodata fetching, and it would also serve the basis for optimizations at the `PrefixData` level (which "can" -not measured- become a bottleneck in large environments with hundreds of packages).

Also I am not sure if `powerloader` libs would also implement `SubdirData` JSON loading or just the fetching.

**Comment by dholth** [comment]
Can we do all network access in conda and tell libmamba "here is the cached json"?

**Comment by jaimergp** [comment]
Yes, it's not as well supported API-wise right now if we compare conda's `SubdirData` with libmamba's, but it can be done.

**Comment by dholth** [comment]
https://gist.github.com/dholth/aab4f8cff8ef89806eec701da37c8727 is based on what we do for https://metayaml-conda.fly.dev/

```
% python jamie_speed.py
Have repodata.json
libmamba: 1618.15 ms
conda+json: 4572.29 ms
conda+orjson: 4457.42 ms
conda+msgspec: 4348.76 ms
sqlite: 1554.47 ms
```

**Comment by jaimergp** [comment]
Wow! JSON+sqlite is not even fair, is it? 🤣

**Comment by dholth** [comment]
I'm surprised we don't pay much for `((repodata_id, key, json.dumps(value)) for key, value in package_group.items()),`

**Comment by dholth** [comment]
IIUC most `SubdirData` queries run a `MatchSpec` against all packages of a given name. The next step would be to change out that with a query.

**Comment by jaimergp** [comment]
Ah, I understand. This would be a complete `SubdirData` overhaul where the backend is no longer a list of dicts, but the `sqlite` db.

This is where I think Wolf mentioned once that they had a `MatchSpec` implementation for sqlite somewhere.

**Comment by dholth** [comment]
Whether we could detect simple >= matchspecs and binary search on sorted packages-by-version would be another idea.

I also exposed the Python MatchSpec to sqlite, it's simple to add functions to sqlite.

**Comment by dholth** [comment]
I updated the gist to do something like this, only making `PackageRecord` for names we are interested in. 

Instead of looking for the ten largest packages, we do a more realistic `"ipython>8"` which clocks in at `98.88 ms`

Not counting building the SQL database in the first place. Cheating? Or a good cache strategy?

I was also pleasantly shocked at how fast loading the Python pickle is, if `repodata.json` has not changed. (~650ms)

```
    def index_particular_name(self, name):
        with connect() as conn:
            self._names_index[name] = [
                PackageRecord(**dict(json.loads(row[0]).items()))
                for row in conn.execute(
                    """SELECT index_json FROM repodata_packages
                    WHERE json_extract(index_json, '$.name') = ?""",
                    (name,),
                )
            ]
```

**Comment by dholth** [comment]
@jaimergp here's a try at building PackageRecord only when needed. https://github.com/conda/conda/pull/12050

On my computer this outperforms libmamba when looking for a single package, according to the gist https://gist.github.com/dholth/aab4f8cff8ef89806eec701da37c8727

```
conda: 1179.07 ms
libmamba: 1704.89 ms
```
