### ISSUE TITLE
Miniconda3 uses python2

### ISSUE THREAD

**Issue by qiulang** [conda/conda#8513]
## Current Behavior

I downloaded Miniconda3 mac 64-bit installer for python 3.7. After I installed it I found Miniconda3 used python2 instead of python 3 

```
(base) langdeMacBook:bin langqiu$ pwd
/miniconda3/bin
(base) langdeMacBook:bin langqiu$ ls -l python
lrwxr-xr-x  1 langqiu  wheel  9 Apr  7 14:21 python -> python2.7
(base) langdeMacBook:bin langqiu$ ipython
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39)
Type "copyright", "credits" or "license" for more information.

...

(base) langdeMacBook:bin langqiu$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
(base) langdeMacBook:bin langqiu$ which python3
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

```

### Steps to Reproduce
1. install python 3.7 by download the installer from https://www.python.org/downloads/mac-osx/
2. install Miniconda3 from https://docs.conda.io/en/latest/miniconda.html

PS I tried to install python3.7 by brew install python3 but the result is the same, e.g ipython still uses python 2.7.5

**Comment by soapy1** [comment]
could you provide an exact link to the address you used to download miniconda?
 I tried 
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh 
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg
and they both seemed to work

**Comment by qiulang** [comment]
Hi I checked the download links from  https://docs.conda.io/en/latest/miniconda.html, they are the same as you mentioned. I have tried them on another macbook and got the same result.

```
qiulangs-MacBook-Pro:bin qiulang$ ./ipython
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit
qiulangs-MacBook-Pro:bin qiulang$ pwd
/miniconda3/bin
qiulangs-MacBook-Pro:bin qiulang$ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```

**Comment by s22chan** [comment]
@qiulang it's because you're calling ipython, which isn't included in the miniconda package. After you do a `conda install ipython` in your environment, it will run from the correct python environment.

**Comment by qiulang** [comment]
That was exactly the problem I reported. I run` conda install ipyhton` then found out conda did not use the correct python version.

**Comment by mahdi-hosseini** [comment]
I had the same problem with continuumio/miniconda3:4.5.12 but when I pinned the version of python packages in envrionment.yml to the latest versions, the issue got resolved.

Maybe attempt doing `conda create -n mypython3 python=3` and see if you have any problem?

**Comment by s22chan** [comment]
@qiulang you should be doing this:
1. install conda
2. `conda activate base` (or another environment you created)
3. `conda install ipython`
4. `ipython`

your ipython path if you do `which ipython` should be your \<conda install directory>/envs/\<name of env>/bin/ipython

**Comment by qiulang** [comment]
@s22chan It was exactly what you had said. I failed to run `conda activate base` before so ipython used python 2.7.5 (bundled with macOS)

But I have some further questions,

1. I checked `.bash_profile` and found that b/c I run `conda activate base` this time, `# >>> conda init >>> part` was added to the part after python3 path was set. I think it is the reason ipython works correctly this time, right ?

2. But  why does “(base)” appear in front of all my terminal prompt ? How do I remove that.

**Comment by s22chan** [comment]
@qiulang 

1. (and 3.) `conda activate` setups your PATH/etc to run the programs inside your environment. This environment is isolated from other ones so you can install different things and not worry about libraries interfering with each other. See https://docs.python.org/3/library/venv.html for something similar.

2. `config config --set changeps1 0` see https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt-changeps1

**Comment by qiulang** [comment]
@s22chan 

Where does config come from ?

```
config config --set changeps1 0
-bash: config: command not found
```

**Comment by soapy1** [comment]
@qiulang I think that was just a typo. You want to run `conda config --set changeps1 0`

**Comment by qiulang** [comment]
Thanks！
