### ISSUE TITLE
reticulate conda 

### ISSUE THREAD

**Issue by carlosgino** [conda/conda#8519]
<!--
Hi!  Read this; it's important.

This is an issue tracker for conda -- the package manager.  File feature requests
for conda here, as well as bug reports about something conda has messed up.

If your issue is a bug report for:
  * a specific conda package from Anaconda ('reticulate):

  * all other conda commands that start with 'conda':
      ==> repl_python()
Error: lexical error: invalid char in json text.
                                       WARNING: The conda.compat modul
                     (right here) ------^

 rstudio generates error when running R code with python code. At first the code worked very well but in the second installation it started to generate faults. Here is the link of the code in case you want to play #https: //www.r-bloggers.com/r-and-python-using-reticulate-to-get-the-best-of-both-worlds/
```

**Comment by carlosgino** [comment]
rstudio generates error when running R code with python code. At first the code worked very well but in the second installation it started to generate faults. Here is the link of the code in case you want to play #https: //www.r-bloggers.com/r-and-python-using-reticulate-to-get-the-best-of-both-worlds/

this is the code:

### > repl_python()
Error: lexical error: invalid char in json text.
                                       WARNING: The conda.compat modul
                     (right here) ------^

**Comment by jjhelmus** [comment]
This is an issue with conda 4.6.11, see #8512.  It has been fixed in #8507 and will be included in conda 4.6.12 which will be released later this week.
