### ISSUE TITLE
conda init missing support for cmder/conemu

### ISSUE THREAD

**Issue by RoyLarson** [conda/conda#8524]
I would like support for 
https://github.com/cmderdev/cmder
which is based off of 
https://conemu.github.io/

to be added to conda init.  

These are nice shell terminals to work with.

**Comment by navneethc** [comment]
I work with conda and cmder (with cmd shell on Windows 10) daily and haven't faced any issues with respect to switching environments, updating packages and opening Jupyter, for example.

**Comment by mingwandroid** [comment]
@RoyLarson, those things are not things that conda knows about.

When we speak of shells we mean things like bash,  cmd.exe, powershell, zsh, csh and fish.

ConEmu and Cmdr are not shells. They are windows to display pseudo ttys only. Coins need do nothing to support them. It's the things they run (shells) that conda needs to support.

**Comment by RoyLarson** [comment]
Thanks I am not sure what happened to the shell, and having 32bit and 64bit anaconda installed, and I am sure I messed up something else.  After cleaning up everything (delete and reinstall) the programs worked as expected
