### ISSUE TITLE
conda activate still failed in powershell

### ISSUE THREAD

**Issue by jackwener** [conda/conda#8529]
you say that conda is supported by powershell in v4.6
but it maybe isn't really.
it doesn't work in powershell (instruction `activate` is failed)

#626 closed, but it seem isn't solved

in fact, It’s amazing to have a problem for 5 years......

——————————————————————————————
https://stackoverflow.com/questions/47800794/how-to-activate-different-anaconda-environment-from-powershell

the answer in stackoverflow is useless

```
Although Conda previously did not support PowerShell, this is now resolved in Conda 4.6.

After adding Anaconda3/Scripts/ to your PATH variable, you should be able to initialize Conda for use with powershell with:

conda init powershell
Afterwards, you can use conda normally:

conda activate base
```

**Comment by jackwener** [comment]
i reinstall anaconda three time,it occur every time

**Comment by urbanespaceman** [comment]
I have the exact same issue as of yesterday when I upgraded to conda 4.6.11. Prior to that it was all working smoothly in powershell.

**Comment by CaselIT** [comment]
This problem is also on version 4.6.9. The last working one seems to be 4.6.8

**Comment by urbanespaceman** [comment]
> This problem is also on version 4.6.9. The last working one seems to be 4.6.8

Sounds right, I think that's the version I upgraded to 4.6.11 from.

**Comment by msarahan** [comment]
There was work to fix this in conda 4.6.12.  It is on the conda-canary channel right now:

conda update conda -c conda-canary

**Comment by jackwener** [comment]
> There was work to fix this in conda 4.6.12. It is on the conda-canary channel right now:
> 
> conda update conda -c conda-canary

thanks ,it's useful

but, it is confused that maintainers don't update doc (it is essential

**Comment by musm** [comment]
how long till conda-canary is merged to conda ?

**Comment by mingwandroid** [comment]
The packages will get moved to the `main` channel once we're happy that they are free of serious known issues.

Is there any reason you cannot use `conda-canary`? It helps us if you can.

**Comment by musm** [comment]
It works, but it does not modify my REPL. How do I handle that?

**Comment by jackwener** [comment]
Unfortunately， conda still behave so badly in powershell

#8559

**Comment by sleighsoft** [comment]
When having e.g. `miniconda` installed make sure that you only have `<your_path>\Miniconda\Scripts` in your User/System variables. Remove any other path variables pointing to conda subdirectories. That solved it for me.
