### ISSUE TITLE
BUG: conda aborts package installation without any message

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda#8533]
## Current Behavior

For specifying a single package with a version range (and without quotes), the conda (4.6.11) just quits without any action or message (after doing *something* for a while)

### Steps to Reproduce

Try `conda install pytest>=4.0.0` - this just returns to REPL without any action or message.

This used to work in 4.5.*.

Adding to the confusion, it works to do `conda install -n base <package>=4.0.0` for some packages, notably conda itself.

Finally, the installation *does* with `conda install "pytest>=4.0.0"`.

## Expected Behavior

Clearer error if package specification is not parsable.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
root@89fe520a3b2d:/# conda info

     active environment : None
            shell level : 0
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.11
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-45-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by h-vetinari** [comment]
I drastically shortened the original OP, because I found out that it's a actually a more wide-reaching parser issue (and regression from 4.5.*).

**Comment by msarahan** [comment]
I'm pretty sure your shell is interpreting those brackets as redirections.  https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html

Have you switched shells recently?  Needing to quote brackets on the command line is definitely not new.

**Comment by h-vetinari** [comment]
That's a valid point to make, but it did work in conda 4.5.* (I just tested it). The shell is bash 4.4.19 which comes with ubuntu 18.04.

**Comment by mingwandroid** [comment]
`conda install blah>=4.0.0` *will* emit the stdout from `conda install blah` into a file called `=4.0.0` on any POSIX compliant shell. To pose the counter-question, how would you redirect the output of `conda install blah` to a file?

Sorry you need to use quotes, either single or double to prevent bash from interpreting > as [redirection](https://www.tldp.org/LDP/abs/html/io-redirection.html).

**Comment by h-vetinari** [comment]
@mingwandroid @msarahan
Well, this is a bit embarrassing...

I guess I didn't see the shell direction forest for the version range tree, haha.

It also didn't help that there was a difference in behaviour between conda 4.5.* and 4.6, and that I chose a test case that yielded just the same with the version range chopped off.

In any case, closing this.

**Comment by mingwandroid** [comment]
Don't worry. Glad the confusion has been addressed.
