### ISSUE TITLE
Avoid showing (base) when "base" is activated

### ISSUE THREAD

**Issue by npavlovikj** [conda/conda#8535]
Hi,

With the newer conda versions, what I have now is:
**[fedora@npavlovikj-conda ~]$ . /opt/conda/etc/profile.d/conda.sh
[fedora@npavlovikj-conda ~]$ conda activate base
_(base)_[fedora@npavlovikj-conda ~]$ conda activate bio
_(bio)_[fedora@npavlovikj-conda ~]$ conda deactivate bio
_(base)_[fedora@npavlovikj-conda ~]$ conda deactivate
[fedora@npavlovikj-conda ~]$**

What I would like to have is:
**[fedora@npavlovikj-conda ~]$ . /opt/conda/etc/profile.d/conda.sh
[fedora@npavlovikj-conda ~]$ conda activate base
[fedora@npavlovikj-conda ~]$ conda activate bio
_(bio)_[fedora@npavlovikj-conda ~]$ conda deactivate bio
[fedora@npavlovikj-conda ~]$ conda deactivate
[fedora@npavlovikj-conda ~]$**

Since using `conda activate base` is the recommended way now, is there a way to not show **(base)** when "base" is activated?
I would prefer if **(base)** is activated "silently", and the only notation I see on the screen is **(bio)** (when that environment is activated).

`conda config --set changeps1 False` does something similar, but it affects all the environments.
Is there some similar configuration only for **(base)**?

I know there is also `conda config --set auto_activate_base false`, but I do want "base" to be activated.

I tried recording "PS1" before running "conda activate base", and that worked only for that part.
On "conda deactivate bio", (base) was shown again.
Maybe that can be done with modifying the "activate.py" script, but personally, I wouldn't like to mess with that...

I would appreciate if someone has any tips on how to achieve this if it is possible.

Thank you,
Natasha

**Comment by apullin** [comment]
This behavior has definitely changed in recent versions of conda.

It would be preferable to have an easy way to suppress the "(base)" tag, so it is not omnipresent if users are using the anaconda base environment as their effective system-wide python.

**Comment by mingwandroid** [comment]
@apullin, The OP is asking for a new feature and you are reporting a regression, or at least that's how it appears at present. Those would be two different issues ideally.

Conda's activation has changed so that if you run `conda init` conda is available from then onward as a shell function even when no conda env has been activated (so you can run `conda activate`)..

If the behaviour has changed outside of this then it must be a bug. To clear out the things that `conda init` does:

```
del %UserProfile%\Documents\WindowsPowerShell\profile.ps1
reg delete "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v AutoRun /f
```

However if you have never called `conda init` then the behaviour should be the same as it was, i.e. you need to manually activate either via The Anaconda Prompt, The Anaconda Powershell Prompt, the new conda.bat in condabin or via the old activate.bat. If this is the case, then please file a new bug.

FWIW, I'm not in favour of this feature request!

**Comment by apullin** [comment]
I don't believe so.
The OP wishes to use the (base) environment with the (base) tag optionally present, with that option being confined only to the (base) environment and not other created conda environments.

One way of achieving this would be via a regression.
Another way of achieving it would be via a new feature.
I highlight the change in behavior to demonstrate that this is a newly-introduced issue that users are responding to by asking for some form of remediation.

The request for "have an easy way to suppress the (base) tag" is the latter, and the same as the OP is requesting.

On OSX, the install adds to the ~/.bash_profile:
```
# added by Anaconda3 2019.03 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/anaconda3/etc/profile.d/conda.sh" ]; then
# . "/anaconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
```

It is unclear if the appearance of the "(base)" tag is a bug or a feature.
The request is to provide a method by which the "(base)" prepended to the command line can be suppressed only for the case of the base environment, and shown for all other conda environments.

**Comment by mingwandroid** [comment]
The current conda doesn't add that. You should run conda init in this case.

**Comment by apullin** [comment]
I have a case where it reproducibly does, after installing the latest public Anaconda python distribution via the installer on the website on an OSX system.

Where could I look to troubleshoot cause is causing this injection?

Notably, the environment has the variable: `CONDA_PROMPT_MODIFIER='(base) '`

My ~/.bash_profile has the amendment shown in my above comment, and running `conda init` does not change this behavior.

This system has had previous versions of anaconda installed on it, so it is possible that this is a result of some vestigial configuration.

Running `conda --version` reports `conda 4.6.14` .

Running `python` in the "(base)" environment reports:
```
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
```

**Comment by npavlovikj** [comment]
Looks like https://github.com/conda/conda/issues/8169 and https://github.com/conda/conda/issues/8211 tackle the same request, although there is no permanent solution yet.

**Comment by tbrodbeck** [comment]
+1

**Comment by msarahan** [comment]
Consolidating to #8169

**Comment by mfansler** [comment]
The solution I came up with was to use the activation hook in **base** to undo the PS1 change. Personally, I don't use it, but it's a reliable solution that continues to be compatible. See https://stackoverflow.com/a/55172508/570918.
