### ISSUE TITLE
Conda App Store and Conda Runtime Environment

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/conda#8545]
I'm aware [how great](https://github.com/kiwi0fruit/pyappshare) it is to distribute crossplatform desktop apps via Conda.

I wonder if this could be turned into even more convenient end-user experience. Like a crossplatform App Store. And what is needed is not that many:

A small superviser app that automatically manages per-app envs (updates them, restores when Conda breaks them and itself without ability to repair, restores even root env, clears deleted env remnants and unused packages). 

Automatic updates for apps is specifically important. This should be possible as each app version would be sha-256 frozen deps. Package that creates crossplatform shortcuts is also needed. Like [shortcutter](https://github.com/kiwi0fruit/shortcutter) but much better.

That's the stuff that now is performed by power users of Conda ecosystem. But it can be automated via superviser app so that Conda distributed apps would  be available to common users.

**Comment by msarahan** [comment]
This is certainly an interesting idea.  I'm not sure we'll be able to work on it anytime soon, but I think it has potential and will try to keep it in mind.

**Comment by kiwi0fruit** [comment]
Linked discussion: https://github.com/conda/constructor/issues/251

By the way. [Pipsi](https://github.com/mitsuhiko/pipsi) is another user experience that is needed for this idea to function.

**Comment by kiwi0fruit** [comment]
Relevant issue: https://github.com/conda-forge/conda-smithy/issues/1061

**Comment by kiwi0fruit** [comment]
Another issue that spoils apps user experience is slow Conda activation (that is perfectly OK for research use-cases). That actually prevents pipsi-like UX for CLI apps.

@msarahan Am I right that if to delable per-package on activate scripts then everything that conda activate would do is to modify $PATH (and revert back on deactivate)? Or there is something more to it?
