### ISSUE TITLE
 NotWritableError: The current user does not have write permissions to a required path.

### ISSUE THREAD

**Issue by msaharia** [conda/conda#8553]
## Current Behavior

I tried installing both anaconda and miniconda. But when I try to create an environment, I get an error.

I am on a server where I am just a user and I don't have permissions to `/home/unix/acristo/`
```
Solving environment: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /home/unix/acristo/.conda/pkgs/urls.txt
  uid: 819262083
  gid: 41777
```
### Steps to Reproduce

```
conda create -n myenv
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location : /home/msaharia/miniconda3
            shell level : 1
       user config file : /home/msaharia/.condarc
 populated config files : /home/msaharia/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/msaharia/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/unix/acristo/.conda/pkgs
       envs directories : /home/msaharia/miniconda3/envs
                          /home/msaharia/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.0.101-0.47.105-default suse_linux/11 glibc/2.11.3
                UID:GID : 819262083:41777
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$              user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.0.101-0.47.105-default suse_linux/11 glibc/2.11.3
-bash: user-agent: command not found
msaharia@discover33:[~]
$                 UID:GID : 819262083:41777
-bash: UID:GID: command not found
msaharia@discover33:[~]
$              netrc file : None
-bash: netrc: command not found
msaharia@discover33:[~]
$            offline mode : False
-bash: offline: command not found
msaharia@discover33:[~]
$ conda config --show-sources
==> /home/msaharia/.condarc <==
pkgs_dirs:
  - /home/unix/acristo/.conda/pkgs
channels:
  - conda-canary
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/msaharia/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37he75722e_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.12                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1a               h7b6447c_0    defaults
pip                       18.1                     py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                h0371630_7    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by msaharia** [comment]
Would appreciate if anyone shed some info on how to fix this.

**Comment by msarahan** [comment]
Set up your envs_dirs setting to point to a location that you have write access to.

https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-environment-directories-envs-dirs

**Comment by msaharia** [comment]
@msarahan Do I create an empty `envs_dirs` and point it there?

**Comment by msaharia** [comment]
@msarahan I tried this:

```
chmod 775 pkgs/
$ CONDA_PKGS_DIRS=/home/msaharia/miniconda3/pkgs
```
But the error persists:
```
$ conda create -n myenv
Solving environment: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /home/unix/acristo/.conda/pkgs/urls.txt
  uid: 819262083
  gid: 41777

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 819262083:41777 /home/unix/acristo/.conda/pkgs/urls.txt

In general, it's not advisable to use 'sudo conda'.
```

**Comment by msarahan** [comment]
closing, this is discussed in #7267.

**Comment by alirezaseif28** [comment]
https://stackoverflow.com/questions/55290271/updating-anaconda-fails-environment-not-writable-error

**Comment by CounsellorDev** [comment]
This line of code on your terminal solves the problem

$ sudo chown -R $USER:$USER anaconda 3

For Linux users only

**Comment by chetanN02** [comment]
> This line of code on your terminal solves the problem
> 
> $ sudo chown -R $USER:$USER anaconda 3
> 
> For Linux users only

This worked for me..! Thanks

**Comment by sofianeElguendouz** [comment]
> This line of code on your terminal solves the problem
> 
> $ sudo chown -R $USER:$USER anaconda 3
> 
> For Linux users only

It worked for me, thank you !

**Comment by nlrahimi** [comment]
> This line of code on your terminal solves the problem
> 
> $ sudo chown -R $USER:$USER anaconda 3
> 
> For Linux users only

It worked for me on Ubuntu 16.04 too.
Thanks

**Comment by jakecariello** [comment]
This works on Ubuntu 18.04

**Comment by morgansobol** [comment]
@CounsellorDev is there another workaround when you do not have permission to use sudo?
"fh9393 is not in the sudoers file.  This incident will be reported."

**Comment by CounsellorDev** [comment]
Hi @morgansobol, try `apt install sudo`.
I hope this helps, do well to reach out to me if problem persists.

**Comment by Migliorin** [comment]
> This line of code on your terminal solves the problem
> 
> $ sudo chown -R $USER:$USER anaconda 3
> 
> For Linux users only

Thanks, this works for me on Ubuntu 18.04

**Comment by kingdavid72** [comment]
"sudo chown -R $USER:$USER anaconda 3" would work for a single-user case
However, for multiple users in a server environment, no one would want to install the same conda over and over again.
It should be designed to have a common environment as well as each user's own environment as well, it may be designed but hard to do because of conda documentation for multi-user cases.  

So conda got installed by system admin at /opt/anaconda3 or something...
each user will have a permission error when they use the conda command
in that case, check see if 
1)$ **conda config**
# can generate .condarc file if that file owner is root then ask admin or if you have sudo
2)$ **sudo chown your_username:your_username .condarc**
# then edit the file
3)$**vim .condarc**

# add lines to specify env and pkg information directories which you can generate yourself
envs_dirs:
  - /home/your_username/conda-env
pkgs_dirs:
  - /home/your_username/conda-env/pkgs

# Then test see if it can generate conda env on your home directory
4)$ **conda create -n test**

# check your env by 
5) **conda info --env**
# test             /home/your_username/conda-env/test

However, I have no idea How I can use --prefix with --name together
I know it is not possible 
then who will use the --prefix which is a lot more difficult to handle!

"Hope this will save someone else time and happy conda ^^"

**Comment by deepika090** [comment]
sudo chmod 777 -R ~/anaconda3/
sudo chmod 777 -R ~/.conda/

this worked for me
