### ISSUE TITLE
Packaging command-line and graphical applications with conda

### ISSUE THREAD

**Issue by paugier** [conda/conda#8556]
I think it's a feature request because I didn't manage to find how to do what I need in the doc.

I first tried to ask a question on Stackoverflow (https://stackoverflow.com/questions/55657360/conda-and-conda-forge-to-install-commands-available-from-all-conda-environments). Since I do not get any answers, it seems that at least it is not evident. 

I think conda could be used to package command-line and graphical applications and not only libraries.

It's easy with conda and conda-forge to work such that applications can be installed in a new conda environment with one command.

However, then, the applications is available only from the environment where it is installed.

To make it available outside the environment, one need to play with the PATH or/and create a shortcut. It even works when conda is not in the PATH (so that another Python can be used).

But this process is boring so it should be automatized. 

It seems to me that the concept of "conda applications" could be "created" (a conda environment + one executable), to allow cross-platform packaging with conda. Users would be able to run for example `conda-app install mercurial meld`.

The executables (or symlinks towards the executables) would be put in a special directory that could be in the PATH even when the command `conda` is not in the PATH. When conda is activated, the commands associated with the conda applications would be available from any conda environments. 

Shortcuts would be created so that the users can easily see and launch the applications.

**Comment by paugier** [comment]
I discovered that there is a way to specify in the meta.yaml file that a package is an application: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#app-section

So it may already be possible to do what I propose / need ?

**Comment by paugier** [comment]
It would be great to be able to package applications with conda and conda-forge and to be able to install them with `conda`. 

Any feedback on this issue would be greatly appreciated.

**Comment by paugier** [comment]
An update on this work:

There is now a metapackage `mercurial-app` built on conda-forge so that Mercurial can be installed in one conda environment with:

```
conda create -n env_hg mercurial-app
```

Then, to use this mercurial from other environments or even when conda is not activated, one can do (with bash):

```
conda activate env_hg
APP_DIR=$HOME/.local/bin/bin-conda-app/
mkdir -p $APP_DIR
ln -s $(which hg) $APP_DIR/hg
echo -e "\nexport PATH=\$PATH:$APP_DIR\n" >> ~/.bashrc
```

It works well but it is complicated for beginners and it is of course not cross-platform.

I tried to see if i could try to write a package providing a command `conda-app install mercurial`, but it seems difficult to use conda to get the necessary information. For example,
```
conda search mercurial-app --info --json -v
```
does not give the data contained in the file `meta.yaml`.

Same with `conda install mercurial-app  --download-only --no-deps --json`.

**Comment by nehaljwani** [comment]
Give this a try: https://stackoverflow.com/a/55900964/1005215 :stuck_out_tongue_winking_eye:

**Comment by paugier** [comment]
Thank you @nehaljwani and @mingwandroid but your solutions based on functions or aliases (with `conda run`) are

1. buggy when other scripts use `command`
2. too slow for Mercurial

```
time conda run -n env_hg hg --version
Mercurial Distributed SCM (version 4.9.1)
...
real    0m0.304s
```

0.3 s for a simple hg --version, it starts to be too long.

Now with a simple symbolic link:
```
time hg --version
Mercurial Distributed SCM (version 4.9.1)
...
real    0m0.099s
```
0.1 s is already very long for this (the infamous Python startup time) but it's more acceptable.

**Comment by paugier** [comment]
The beginning of a solution (using a new package `conda-app`):

https://stackoverflow.com/a/55955147/1779806
