### ISSUE TITLE
Path exploding on Windows due to conda init

### ISSUE THREAD

**Issue by dbwz8** [conda/conda#8566]
## Current Behavior

Every time I issue a conda command in powershell, the windows path gets extended with duplicate entries... eventutually becoming too long to set.

**BUG FIX**
Note the line below:

```
Write-Output Env:PATH is $Env:PATH;
```
It's a debug output that was never removed that's being added to the PATH and thus the system keeps adding to the PATH over and over and over...

### Steps to Reproduce
Do conda init powershell and then using commmands the path keeps growing. It appears to be happening in Conda.psm1:

```
<#
    .SYNOPSIS
        Adds the entries of sys.prefix to PATH and returns the old PATH.

    .EXAMPLE
        $OldPath = Add-Sys-Prefix-To-Path
#>
function Add-Sys-Prefix-To-Path() {
    $OldPath = $Env:PATH;
    if ($Env:_CE_CONDA -ne '' -And $Env:OS -eq 'Windows_NT') {
        # Windows has a different layout for the python exe than other platforms.
        $sysp = Split-Path $Env:CONDA_EXE -Parent;
    } else {
        $sysp = Split-Path $Env:CONDA_EXE -Parent;
        $sysp = Split-Path $sysp -Parent;
    }
    if ($Env:OS -eq 'Windows_NT') {
        $Env:PATH = $sysp + ';' +
                    $sysp + '\Library\mingw-w64\bin;' +
                    $sysp + '\Library\usr\bin;' +
                    $sysp + '\Library\bin;' +
                    $sysp + '\Scripts;' +
                    $sysp + '\bin;' + $Env:PATH;
    } else {
        $Env:PATH = $sysp + '/bin:' + $Env:PATH;
    }
    Write-Output Env:PATH is $Env:PATH;
    return $OldPath;
}

```
## Expected Behavior
Path should not lengthen with duplicates

**Comment by msarahan** [comment]
Thanks for identifying the issue.  Your proposed fix is already present in #8564 and we'll get a release out later today.
