### ISSUE TITLE
condabin dir content should contain activate script

### ISSUE THREAD

**Issue by GoodDingo** [conda/conda#8567]
Please add `activate` script to `condabin/` directory for Miniconda (Anaconda as well)
----

When using Miniconda personally, `conda init` modification of shell rc files is great thing. Overall developer's user experience is then great on all platforms.

However **usage from CI server (like Jenkins) is problematic with `conda`** and it can be made better easily by adding `activate` to `condabin/`.

##### On CI server tools exists only upon request
* command `conda` should fail on build agent when "Miniconda" is not requested as dependency or tool for CI
 ##### However when requested as tool, there is no "good" way to do so
 * Adding `${CONDA_HOME}/bin` to `PATH` to local job will also add/change `python` and lots of other binaries, this is unwanted behaviour. (I can describe why in more details later)
* Adding `${CONDA_HOME}/condabin` to `PATH` will only add `conda` but `conda activate` will fail with missing source 
  * `conda` as shell function is not good practice; it's decided after shell will start and is global to build agent (`conda init` and modifying files like `.bashrc` on CI server globally is not an option)
  * sourcing `${CONDA_HOME}/etc/profile.d/conda.sh` before running anything that requires conda environment is not convenient (shell commands don't share state on CI servers)
```
sh '''
    conda env create --force -p ./.cvenv
    run-something
   '''
  
sh '''
    source ${CONDA_HOME}/etc/profile.d/conda.sh 
    conda activate ./.cvenv
    run-something
   '''
...
sh '''
    source ${CONDA_HOME}/etc/profile.d/conda.sh 
    conda activate ./.cvenv
    run-something-else
   '''
```

What we end up doing is manualy copying `${CONDA_HOME}/bin/activate` to `${CONDA_HOME}/condabin` and adding that to `PATH`, which enable thing people are used to
```
sh '''
    source activate ./.cvenv
    run-something
   '''
```

----

P.S. Not sure if this is right place to file this feature request. Navigate me to better place if such exists. Thanks.

**Comment by msarahan** [comment]
The purpose of NOT having activate in condabin is that conda then does not interfere with virtualenv usage on the user's system, which also provides an "activate" command.  Any number of other things may also provide "activate" commands.  The idea of condabin was to avoid all of those conflicts, in addition to avoiding conflicts with python and all the other executables in bin.

Is there anything wrong with calling 

```
source ${CONDA_HOME}/bin/activate ./.cvenv
run something
```

?

I definitely think that we will not be adding activate to the condabin folder.  This seems like a "can't have your cake and eat it, too" situation.
