### ISSUE TITLE
Failure for conda to install pydicom

### ISSUE THREAD

**Issue by surnameforename** [conda/conda#857]
I'm trying to install pydicom to my Anaconda installation, and have been having some difficulty.

I was running a 1.9.x version of Anaconda, but updated to the latest (- 2.0.1 I think.)

Steps...
- Tried pip and Andconda network install of pydicom - both failed
- Downloaded pydicom.tar.gz, ungzipped it, then bzip2ed it
- Ran the command, conda install "C:\Users\gawh\Downloads\pydicom-0.9.8.tar\dist\pydicom-0.9.8.tar.bz2"
  *\* it failed (message similar to the one below)
- Upgraded to the latest Anaconda
- Ran the command again, it failed, (message similar to the one below)
- Found out that for pip I need to set up the proxy
- Set up the proxy
- Ran the command again, it failed, message pasted in below
- Ran 'pip install pydicom' it worked OK 
- Checked it is in the pip list of packages

Error return and conda info pasted in below.

(Apart from this liking Anaconda :-)

Error return -------------------------------

F:\SomeFolder>conda install "C:\Users\gawh\Downloads\pydicom-0.9.8.tar\dist\pydicom-0.9.8.tar.bz2"
Fetching package metadata: ..
[      COMPLETE      ] |#################################################| 100%
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the############| 100%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 226, in install
    install_local_packages(prefix, args.packages, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\misc.py", line 195, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 436, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 418, in execute_plan
    link(prefix, arg, index=index)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 374, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 454, in link
    files = list(yield_lines(join(info_dir, 'files')))
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 157, in yield_lines
    for line in open(path):
IOError: [Errno 2] No such file or directory: 'C:\Anaconda\pkgs\pydicom-0.9.8\info\files'

Conda info -------------------------------------------------------------

F:\SomeDirectory>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.5.5
   python version : 2.7.7.final.0
 root environment : C:\Anaconda  (writable)
```

  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

**Comment by alexvicegrab** [comment]
I'm having the same problem on Mac OS X El Capitan.

Python 2.7.10 |Anaconda 2.4.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

Conda does not have a release candidate for pydicom, but I've tried the following:

>> conda install -f --channel https://conda.anaconda.org/eivind88 pydicom

When I go into python or ipython anaconda shells, I see the following:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pydicom

**Comment by alexvicegrab** [comment]
Resolved: Problem is not with Conda but with pyDICOM package. Documentation for unreleased version 1.0 says it is importable as:

> import pydicom

But for versions 0.99 and prior, the import should be:

> import dicom
