### ISSUE TITLE
Error on   Virtual platform" conda env create -f virtual_platform_windows.yml 

### ISSUE THREAD

**Issue by raonvk** [conda/conda#8583]
Hi
Just installed Anaconda3-2019.03-Windows-x86_64.exe on Win7 x64 bit
I tried to create Virtual platform by
conda env create -f virtual_platform_windows.yml

How to fix error?
![Anaconda3_Error](https://user-images.githubusercontent.com/38853257/56506250-f253f400-652e-11e9-992f-a09937152c2c.jpg)

**Comment by msarahan** [comment]
Update conda and try again. There were bugs that should be fixed in the latest conda 4.6.14 release.

**Comment by raonvk** [comment]
Hi Mike
I have tried to update conda by
pip install conda
pip update conda
conda update conda
nothing is working
could you please send instructions? or link to download
