### ISSUE TITLE
conda run leaves conda and a shell in the process tree

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8586]
## Current Behavior

In earlier versions of conda 4.6, using `conda run` on unix used the `exec` syscall to ensure conda itself (and any other processes conda may have started) did not ultimately end up in the running process's process tree.

### Steps to Reproduce

Given the following Dockerfile
```
FROM debian:9
ARG CONDA_VERSION
RUN set -ex \
    && apt-get -qq update \
    && apt-get -qq -y install curl bzip2 psmisc \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && sh /tmp/miniconda.sh -bfp /miniconda \
    && /miniconda/bin/conda create -yq -p /conda python=3 conda=${CONDA_VERSION}
```

executing

```
$ docker build -t conda:4.6.7 --build-arg CONDA_VERSION=4.6.7 .
$ docker run --rm conda:4.6.7 /conda/bin/conda run pstree
conda---bash---pstree

$ docker build -t conda:4.6.14 --build-arg CONDA_VERSION=4.6.14 .
$ docker run --rm conda:4.6.14 /conda/bin/conda run pstree
conda---bash---pstree

```

we see active processes for both `conda` and `bash` in the process tree when using `conda run`.

Per #8585, it's also a regression to force bash as a requirement over a generic posix shell.

## Expected Behavior

Up through conda 4.6.4, `conda run` leaves itself out of the process tree.

```
$ docker build -t conda:4.6.4 --build-arg CONDA_VERSION=4.6.4 .
$ docker run --rm conda:4.6.4 /conda/bin/conda run pstree
pstree
```

**Comment by mingwandroid** [comment]
Why? It seems utterly obvious to me that having things in the process tree is preferable.

**Comment by mingwandroid** [comment]
(utterly obvious because it's called `conda run` and therefore you are asking conda to run something therefore it should be a child process of conda.

**Comment by kalefranz** [comment]
Now that we are being so dogmatic about people activating environments before they can use conda-installed software, to the point of not even being able to start an executable by just using the absolute path, we need to give users a way to start a process and get conda out of the way. Init systems (SysVinit, supervisord, etc., etc.) need to be able to send signals directly to the process they are managing, not to conda, then a shell, then a subprocess from there.

If `conda run` can’t start a process and get conda out of the way (out of the process tree, out of the allocated memory, etc), how else do we propose a user use conda environments correctly along with existing init systems?

**Comment by msarahan** [comment]
I agree with Ray that the new behavior is more intuitive, but the use case that Kale raises is important. We should provide a way for this to work. Kale, what kind of timeline/priority do you think this warrants?

**Comment by kalefranz** [comment]
Keeping conda near 4.6.0 works fine for now, I guess so long as we don't have to use all the great improvements Ray made recently with non-ascii paths and such. As soon as we pick up usage of the new package format though, it'd be nice to start building docker images with those packages and be able to use `/conda/bin/conda run ...` as the docker `CMD` directive.

**Comment by mingwandroid** [comment]
> Now that we are being so dogmatic about people activating environments before they can use conda-installed software

No we aren't being dogmatic about it, Windows is. That's how it works, we have no choice but to follow that. That this broke in conda 4.6.0 .. 4.6.13 inclusive was for me, a bit fo a disaster.

**Comment by jcrist** [comment]
I think it's important (on `*nix` systems at least) to have a way for either:
- Using `exec` to get conda out of the process tree
- Conda properly forward signals to the child. Bonus points if conda functions properly as an init process.

Either of these would make it easier to use `conda run` as a docker `entrypoint` (https://docs.docker.com/engine/reference/builder/#entrypoint) or under an init system (e.g. `supervisord`). I have a slight preference for the former, as it removes a lot of responsibility on the conda side.

Perhaps a flag `--exec` on `conda run`? Or `conda exec` as a separate command? If it's never necessary to have `conda run` keep the conda process around on `*nix` systems, perhaps default to that when possible? I personally don't find it "Utterly obvious" to keep the conda process around, unless there's a good reason for that.

**Comment by brettcannon** [comment]
Using `os.exec*()` would also probably solve https://github.com/conda/conda/issues/9412.
