### ISSUE TITLE
I am facing this message while opening my terminal 

### ISSUE THREAD

**Issue by Mehdihym** [conda/conda#8587]
`
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /home/joseph/anaconda2/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /home/joseph/anaconda2/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/home/joseph/anaconda2/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^

`

**Comment by jsh9** [comment]
I encountered a similar issue.

When opening my terminal ("git bash"), my error message was:
```
CommandNotFoundError: No command 'conda conda'
```

I installed the 2019.03 version of Anaconda on my Windows 10 computer.

I followed the advice here (https://stackoverflow.com/a/55481171/8892243) and downgraded `conda` to 4.6.8, and solved this issue.

Maybe you can try the same thing.

I'm also hoping to see a permanent solution to this issue.

**Comment by msarahan** [comment]
You should generally try updating before downgrading.  This should be fixed in recent versions.
