### ISSUE TITLE
Fish init does not work

### ISSUE THREAD

**Issue by RSully** [conda/conda#8590]
## Problem

I previously had Conda setup in fish by simply using:

```
source $CONDA_PATH/etc/fish/conf.d/conda.fish
```

Recently I found out about `conda init` and ran `conda init fish` which put the following in my fish config instead (I removed the above `source`):

```
eval (eval $CONDA_PATH/bin/conda "shell.fish" "hook" $argv)
```

When using the first method, `$CONDA_PATH/condabin/conda` is added to my PATH, which seems wrong. Using the second method, `conda activate` does not work at all, and I get an error that I should run `conda init`.

## Environment Information
<details open><summary><code>`conda info` (using first method)</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : ~/dev/opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : ~/dev/opt/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/dev/opt/miniconda3/envs
                          ~/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Darwin/18.5.0 OSX/10.14.4
                UID:GID : 501:20
             netrc file : ~/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> ~/.condarc <==
auto_update_conda: False
channel_priority: flexible
channels:
  - defaults
  - conda-forge
show_channel_urls: True
```
</p></details>

**Comment by RSully** [comment]
The documentation for fish is also inconsistent in this regard:

- [conda.fish](https://github.com/conda/conda/blob/1e0a6083a9250bd72670b958f341fd98298b1a01/conda/shell/etc/fish/conf.d/conda.fish#L6) says to use `conda init fish`
- [linux.rst](https://github.com/conda/conda/blob/2f2b0af4316b913b1acde19249a1c36691a60db3/docs/source/user-guide/install/linux.rst#using-with-fish-shell) says to use my `source` method

**Comment by ngoonee** [comment]
Same thing here. The 'funny' thing is that, based on the output of eval $CONDA_PATH/bin/conda "shell.fish" "hook" it should come out with EXACTLY the same thing as is currently contained in /etc/fish/conf.d/config.fish (except for 'conda activate base') at the end.

I don't think there's much downside to just sources config.fish for now, I guess?

**Comment by rrigdon** [comment]
https://conda.io/projects/conda/en/latest/user-guide/install/linux.html#using-with-fish-shell

**Comment by ngoonee** [comment]
> https://conda.io/projects/conda/en/latest/user-guide/install/linux.html#using-with-fish-shell

Thanks @rrigdon, but conda init fish (for me, and I guess for OP as well) just adds the line OP states to my fish.config. This results in conda activate not working etc. However, when I just source /etc/fish/conf.d/config.fish, it works as expected.

**Comment by RSully** [comment]
> However, when I just source /etc/fish/conf.d/config.fish, it works as expected.

To clarify, while conda is functional,  it actually doesn't quite work as expected, though, from what I can tell. Adding the `source` line adds `$CONDA_PATH/condabin/` to my `$PATH`, which I don't think is wanted at all.

**Comment by ngoonee** [comment]
> > However, when I just source /etc/fish/conf.d/config.fish, it works as expected.
> 
> To clarify, while conda is functional, it actually doesn't quite work as expected, though, from what I can tell. Adding the `source` line adds `$CONDA_PATH/condabin/` to my `$PATH`, which I don't think is wanted at all.

Why not though? That directory only contains the conda symlink, compared to `$CONDA_PATH/bin` which contains a whole lot more.

**Comment by soapy1** [comment]
@ngoonee this is definitely a bug in conda, @rrigdon's fix for the docs is how conda should work and resolving @RSully comment https://github.com/conda/conda/issues/8590#issuecomment-485808742.

@RSully adding condabin to path is right as far as I understand it. I did some digging and it looks like there are some environment variables that aren't quite exported right. But I haven't really tracked this all the way down.

**Comment by RSully** [comment]
@soapy1 thanks for your fix. That at least fixes the issue of "fish init does not work". 

I still disagree with conda that the proper way to initialize is to automatically activate the base environment, though. I am personally going to stick with my `source conda.fish` method.

**Comment by baloe** [comment]
@soapy1 
Where is it fixed? I don't get it. 
I just now installed the most recent miniconda (4.6.14) to a directory named `/soft/conda/`.
Running `/soft/conda/bin/conda init fish` adds 
```# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval (eval /soft/conda/bin/conda "shell.fish" "hook" $argv)
# <<< conda initialize <<<
```
to my `~/.config/fish/config.fish`, but this does not appear to be helpful:
```
> conda activate root
conda: command not found
```
and
```
> /soft/conda/bin/conda activate root

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by RSully** [comment]
A release has not been made with the change yet, I believe

**Comment by soapy1** [comment]
@baloe the fix is in the master branch of conda. It will be included in the next release. 
So, you can either setup that version of conda, or change your ~/.config/fish/config.fish from `eval (eval /Users/scastellarin/miniconda3/bin/conda "shell.fish" "hook" $argv)` to `eval %(conda_exe)s "shell.fish" "hook" $argv | source`

**Comment by tpdownes** [comment]
That's a fairly direct quote from the python code itself. It would manifest in config.fish as (using same example):
```
eval /Users/scastellarin/miniconda3/bin/conda "shell.fish" "hook" $argv | source
```

**Comment by baloe** [comment]
> the fix is in the master branch of conda. It will be included in the next release.
> So, you can either setup that version of conda, or change your ~/.config/fish/config.fish from `eval (eval /Users/scastellarin/miniconda3/bin/conda "shell.fish" "hook" $argv)` to `eval %(conda_exe)s "shell.fish" "hook" $argv | source`

@soapy1 unfortunately, this does not work. my ~/.config/fish/config.fish contains the following lines:
```
set -gx PATH $PATH /soft/conda/bin/
eval /soft/conda/bin/conda "shell.fish" "hook" $argv | source
```

but when I then call `conda activate root`, I still get:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

I guess I'll continue to switch to bash before using anaconda until the fix is released.

**Comment by kirankotari** [comment]
`set -gx PATH $PATH /soft/conda/bin`
`eval /soft/conda/bin/conda "shell.fish"  "hook" $argv | source`

It worked for me. Thanks :)
