### ISSUE TITLE
Discrepancy between success of `conda search` and `conda install` commands with trim-galore package

### ISSUE THREAD

**Issue by hannah413** [conda/conda#8594]
Hello,

I am encountering an issue wherein I can locate a package in the bioconda channel with `conda search`, but `conda install` fails. The installation command follows the format described for that package [here](https://anaconda.org/bioconda/trim-galore)) with added version information (`trim-galore=0.4.3` rather than just `trim-galore`). Note that if I run the command without the version information, it will install v0.5.0 successfully (but this is not the one we require).

### Steps to Reproduce
This command works as expected:
```
conda search -c bioconda trim-galore=0.4.3
```
Here is its output (good):
```
Loading channels: done
Name                  Version           Build  Channel
trim-galore               0.4.3      pl5.22.0_0  bioconda
trim-galore               0.4.3      pl5.22.0_1  bioconda
```
This command fails:
```
conda install -c bioconda trim-galore=0.4.3
```
Here is its output (bad):
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - trim-galore=0.4.3
  - perl=5.22.0

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

## Expected Behavior
I expect the installation command to work when given the same information as the search command.

## Environment Information
Portions of the path are redacted as I'm not permitted to share full paths, but note that REDACTED1 and REDACTED2 are internally consistent.
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : porQpine
    active env location : /REDACTED1/miniconda3/envs/porQpine
            shell level : 2
       user config file : /REDACTED2/.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.6.7.final.0
       base environment : /REDACTED1/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /REDACTED1/miniconda3/pkgs
                          /REDACTED2/.conda/pkgs
       envs directories : /REDACTED1/miniconda3/envs
                          /REDACTED2/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.7 Linux/3.10.0-862.14.4.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 5119:3010
             netrc file : /REDACTED2/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
# nothing to see here
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /REDACTED1/miniconda3/envs/porQpine:
#
# Name                    Version                   Build  Channel
argparse                  1.4.0                    py36_0    bioconda
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py36_0    defaults
hdf5                      1.8.17                        2    defaults
intel-openmp              2019.1                      144    defaults
kallisto                  0.43.1             hdf51.8.17_1    bioconda
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py36ha843d7b_0    defaults
mkl_random                1.0.2            py36hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.16.2           py36h7e9f1db_0    defaults
numpy-base                1.16.2           py36hde5b4d6_0    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pandas                    0.24.1           py36he6710b0_0    defaults
pip                       19.0.3                   py36_0    defaults
python                    3.6.8                h0371630_0    defaults
python-dateutil           2.8.0                    py36_0    defaults
pytz                      2018.9                   py36_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                40.8.0                   py36_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.33.1                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by jjhelmus** [comment]
The `bioconda` channel nor any of the other channels you have configured contain a perl 5.22.0 package which is required by trim-galore.  The error message attempting to point this out.  I believe `bioconda` expects the `conda-forge` channel to provide some of these packages.  Using `conda install -c bioconda -c conda-forge trim-galore=0.4.3` should allow the install to proceed.

**Comment by hannah413** [comment]
Ah, thank you. This error message would be more helpful if it indicated that a dependency of the requested package was not available rather than saying that both the dependency and the package itself were not available.

I have intentionally excluded conda-forge from my channel list as, in the past, it has caused some serious clobbering issues that corrupted my conda installations and required complete removal and re-installation of miniconda. I have lived relatively happily since the day I excluded it. In the interest of protecting my current installation, I will proceed by creating a separate conda installation and allowing conda-forge across _that_ doorstep, as it were.

Thank you.

**Comment by mbargull** [comment]
> This error message would be more helpful if it indicated that a dependency of the requested package was not available

Agreed. Improving the solver messaging is a reoccurring and still open topic (https://github.com/conda/conda/labels/tag-solver_messaging) .

> I have intentionally excluded conda-forge from my channel list

The current recommended setup for the channel priorities for Bioconda is `conda-forge` > `bioconda` > `defaults`, see http://bioconda.github.io/#set-up-channels.
I'd highly recommend making use of different Conda environments whenever possible. You can minimize your clobbering/corruptions issues that way. You can even customize your channel setup for each environment with `conda config --env` in an activated environment. E.g., you could do something like
```bash
conda create --name trim-galore
conda activate trim-galore
conda config --env --append channels conda-forge
conda config --env --append channels bioconda
conda config --env --append channels defaults
conda install trim-galore=0.4.3
```
to create an environment with a Bioconda-specific configuration without altering your `base` environment's configuration.
If you still encounter incompatibility issues between the `conda-forge` and `defaults` channel, you can try on of
```bash
conda config --env --remove channels defaults
```
or
```bash
conda config --env --set channel_priority strict
```
.
