### ISSUE TITLE
Support totally self contained conda install (IE doesn't touch files in '~/' or similar)

### ISSUE THREAD

**Issue by mithro** [conda/conda#8599]
## Current Behavior

Currently a conda install reads / processes a number of files from a user's home directory. These include `~/.condarc` and files user `~/.conda`. This makes it impossible to use in an environment were a user is unable to write to their home directory (IE it is readonly). This also means that a users configuration effectively 'infects' a conda environment.

It would be good to have a mode were conda is totally isolated and only reads from files inside the directory conda is installed to. The current work around is to set `$HOME` to a different value, however this has bad side affect on other programs which conda might launch.

## Proposed Solution

A quick grep through the conda source code seems to indicate that you consistently use `os.path.expanduser` and already have a `conda.common.path` package. My suggestion is that you add a `expanduser` function into the `conda.common.path` package which can then be a place to override the behaviour for the self contained system. 

Would you accept a patch which did this?

**Comment by msarahan** [comment]
I think so.  Isolation is definitely a good thing.  What we need to be careful about, though, is keeping the ability for system administrators to impose a system-wide policy.

**Comment by mithro** [comment]
I found the following code in `conda/cli/main_config.py` file;
https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/cli/main_config.py#L195-L205

Which imports via;
https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/cli/main_config.py#L19

Which comes from;
https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/base/context.py#L67-L68

There is also some duplication at;
https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/cli/conda_argparse.py#L21-L25

However, `conda/base/constants.py` contains a list of search paths;
https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/base/constants.py#L27-L55

Does anyone understand the difference and why `conda/cli/main_config.py` and `conda/cli/conda_argparse.py` seem to have a hard coded condarc file? Is this in the middle of being refactored?

**Comment by mithro** [comment]
Looks like @dhirschfeld was responsible for adding the `constants.py`'s `SEARCH_PATH`s but @kalefranz might have originally written a lot of this code.

**Comment by mithro** [comment]
FYI; 

`conda setup` uses the following arguments;

https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/cli/conda_argparse.py#L636-L662

`conda config` uses the following arguments;

https://github.com/conda/conda/blob/1cade00ff57b403e9c7a5ac2e4b61f4175721c18/conda/cli/conda_argparse.py#L389-L414

----

It seems like, 
 * `--env` and `--no-env` could be arguments to control usage of "current environment" `.condarc` and other things specific to the current "conda env".
 * `--user` and `--no-user` could be arguments to control usage of "user" `.condarc` and other things under `~` outside the conda installation
 * `--system` and `--no-system` could be arguments to control usage of "system" `.condarc` and other things shared between users outside the conda installation.

It would be good to have environment variables which allow control over the `--{no-}user` and `--{no-}system` values. It might even make sense for environments to be able to set these values? IE This environment is self contained, while this other one uses users stuff?

**Comment by mithro** [comment]
I'm unsure if `$CONDA_ROOT` and `$CONDARC` shown in conda/base/constants.py should also be affecting `conda/cli` tools?

**Comment by kalefranz** [comment]
`~/.condarc` is only written to with `conda config`. If the home directory is read-only and `conda config` fails because of it, I don’t see much of an issue.

The `.conda` directory is more interesting. It has three uses.

1. Under normal install conditions conda needs a guaranteed writable package cache. By default that’s the `pkgs` directory in the base environment, but when the base environment is read-only then we fall back to`~/.conda/pkgs`. We haven’t developed a `--no-cache` option like `apk` has. Perhaps we should, but it might be quite a lot of work and probably not a high priority. 
2. Conda needs a writable location to create environments when a user invoked `conda create -n`. We use `~/.conda/envs` as part of that search path and fall back there when the base environment is read-only. 

So for the first two, the solution seems to me to just make sure your base environment is writable if you don’t want conda falling back to the home directory. 

3. The most interesting here probably is `~/.conda/environments.txt`, which conda has long used to journal locations where it’s created environments. This especiakky applies when environments are created with `conda create -p`. Running `conda search --envs` as root gives a sysadmin the ability to search through all conda environments on the system. Without such journaling, you’d have to do a brute-force listing of the whole file system to search for conda environments.

In recent versions of conda 4.6, the requirement to write to `~/.conda/environments.txt` was relaxed and conda only emits a warning.

**Comment by mithro** [comment]
FYI, this is what I get with the currently available version of conda;
```
     active environment : None
       user config file : /home/travis/.condarc
 populated config files : /home/travis/build/timvideos/litex-buildenv/build/conda/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/travis/build/timvideos/litex-buildenv/build/conda  (writable)
           channel URLs : https://conda.anaconda.org/timvideos/linux-64
                          https://conda.anaconda.org/timvideos/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/travis/build/timvideos/litex-buildenv/build/conda/pkgs
       envs directories : /home/travis/build/timvideos/litex-buildenv/build/conda/envs
                          /home/travis/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-101-generic ubuntu/14.04.5 glibc/2.19
                UID:GID : 2000:2000
             netrc file : None
           offline mode : False
              Platform: arty
                Target: base (default: net)
                   CPU: lm32 (default: lm32)
Installing python3.6
Collecting package metadata: done
Solving environment: done
## Package Plan ##
  environment location: /home/travis/build/timvideos/litex-buildenv/build/conda
  added / updated specs:
    - python=3.6
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    asn1crypto-0.24.0          |           py36_0         155 KB
    certifi-2019.3.9           |           py36_0         155 KB
    cffi-1.12.3                |   py36h2e261b9_0         222 KB
    chardet-3.0.4              |           py36_1         189 KB
    conda-4.6.14               |           py36_0         2.1 MB
    cryptography-2.3.1         |   py36hc365091_0         585 KB
    idna-2.8                   |           py36_0         133 KB
    openssl-1.0.2r             |       h7b6447c_0         3.2 MB
    pip-19.0.3                 |           py36_0         1.9 MB
    pycosat-0.6.3              |   py36h14c3975_0         104 KB
    pycparser-2.19             |           py36_0         174 KB
    pyopenssl-19.0.0           |           py36_0          82 KB
    pysocks-1.6.8              |           py36_0          22 KB
    python-3.6.0               |                0        16.3 MB
    readline-6.2               |                2         606 KB
    requests-2.21.0            |           py36_0          85 KB
    ruamel_yaml-0.15.46        |   py36h14c3975_0         245 KB
    setuptools-41.0.0          |           py36_0         656 KB
    six-1.12.0                 |           py36_0          22 KB
    sqlite-3.13.0              |                0         4.0 MB
    tk-8.5.18                  |                0         1.9 MB
    urllib3-1.24.1             |           py36_0         149 KB
    wheel-0.33.1               |           py36_0          39 KB
    ------------------------------------------------------------
                                           Total:        32.8 MB
The following packages will be UPDATED:
  cffi                                1.12.2-py37h2e261b9_1 --> 1.12.3-py36h2e261b9_0
The following packages will be SUPERSEDED by a higher-priority channel:
  python                 pkgs/main::python-3.7.3-h0371630_0 --> pkgs/free::python-3.6.0-0
  readline               pkgs/main::readline-7.0-h7b6447c_5 --> pkgs/free::readline-6.2-2
  sqlite                pkgs/main::sqlite-3.27.2-h7b6447c_0 --> pkgs/free::sqlite-3.13.0-0
  tk                         pkgs/main::tk-8.6.8-hbc83047_0 --> pkgs/free::tk-8.5.18-0
The following packages will be DOWNGRADED:
  asn1crypto                                  0.24.0-py37_0 --> 0.24.0-py36_0
  certifi                                   2019.3.9-py37_0 --> 2019.3.9-py36_0
  chardet                                      3.0.4-py37_1 --> 3.0.4-py36_1
  conda                                       4.6.14-py37_0 --> 4.6.14-py36_0
  cryptography                         2.6.1-py37h1ba5d50_0 --> 2.3.1-py36hc365091_0
  idna                                           2.8-py37_0 --> 2.8-py36_0
  openssl                                 1.1.1b-h7b6447c_1 --> 1.0.2r-h7b6447c_0
  pip                                         19.0.3-py37_0 --> 19.0.3-py36_0
  pycosat                              0.6.3-py37h14c3975_0 --> 0.6.3-py36h14c3975_0
  pycparser                                     2.19-py37_0 --> 2.19-py36_0
  pyopenssl                                   19.0.0-py37_0 --> 19.0.0-py36_0
  pysocks                                      1.6.8-py37_0 --> 1.6.8-py36_0
  requests                                    2.21.0-py37_0 --> 2.21.0-py36_0
  ruamel_yaml                        0.15.46-py37h14c3975_0 --> 0.15.46-py36h14c3975_0
  setuptools                                  41.0.0-py37_0 --> 41.0.0-py36_0
  six                                         1.12.0-py37_0 --> 1.12.0-py36_0
  urllib3                                     1.24.1-py37_0 --> 1.24.1-py36_0
  wheel                                       0.33.1-py37_0 --> 0.33.1-py36_0
Downloading and Extracting Packages
certifi-2019.3.9     | 155 KB    | ##################################### | 100% 
wheel-0.33.1         | 39 KB     | ##################################### | 100% 
sqlite-3.13.0        | 4.0 MB    | ##################################### | 100% 
asn1crypto-0.24.0    | 155 KB    | ##################################### | 100% 
pysocks-1.6.8        | 22 KB     | ##################################### | 100% 
requests-2.21.0      | 85 KB     | ##################################### | 100% 
urllib3-1.24.1       | 149 KB    | ##################################### | 100% 
pyopenssl-19.0.0     | 82 KB     | ##################################### | 100% 
pip-19.0.3           | 1.9 MB    | ##################################### | 100% 
chardet-3.0.4        | 189 KB    | ##################################### | 100% 
openssl-1.0.2r       | 3.2 MB    | ##################################### | 100% 
pycparser-2.19       | 174 KB    | ##################################### | 100% 
readline-6.2         | 606 KB    | ##################################### | 100% 
idna-2.8             | 133 KB    | ##################################### | 100% 
six-1.12.0           | 22 KB     | ##################################### | 100% 
conda-4.6.14         | 2.1 MB    | ##################################### | 100% 
pycosat-0.6.3        | 104 KB    | ##################################### | 100% 
setuptools-41.0.0    | 656 KB    | ##################################### | 100% 
python-3.6.0         | 16.3 MB   | ##################################### | 100% 
tk-8.5.18            | 1.9 MB    | ##################################### | 100% 
cryptography-2.3.1   | 585 KB    | ##################################### | 100% 
cffi-1.12.3          | 222 KB    | ##################################### | 100% 
ruamel_yaml-0.15.46  | 245 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: \ WARNING conda.core.path_actions:verify(933): Unable to create environments file. Path not writable.
  environment location: /home/travis/.conda/environments.txt
done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'None'.
PermissionError(13, 'Permission denied')
Attempting to roll back.
Rolling back transaction: done
[Errno 13] Permission denied: '/home/travis/.conda/environments.txt'
```

I'm using;
```
./Miniconda3-latest-Linux-x86_64.sh -p $CONDA_DIR -b -f
conda config --system --set always_yes yes
conda config --system --set changeps1 no
conda config --system --add envs_dirs $CONDA_DIR/envs
conda config --system --add pkgs_dirs $CONDA_DIR/pkgs
```

**Comment by dhirschfeld** [comment]
`conda` searches for configuration in a priority order:
```
global --> base --> user --> env
```

This is fairly standard and in general allows a user to override the system (default) configuration. sysadmin policy considerations are taken into consideration with the `#!final` attribute.

The only thing missing is an `#!override` parameter - #8271

The reason this is required is because the behaviour of higher-priority configuration for channels isn't to override the inherited configuration but to *append* to the inherited channels. This effectively means the channels from a higher-priority configuration are given a lower priority by conda than the inherited channels.

Assuming the user can write a `.condarc` *somewhere* (and can tell `conda` where to find it) then the  user config taking precedence (plus the `#!override` flag) should allow the user to get the behaviour they're after

**Comment by mithro** [comment]
It appears I'm confusing two separate issues here;

 1. Having user and system settings "infect" a conda environment.
 2. Having control over where conda writes output too.

There is a little bit of a relationship here as settings in (1) can control what conda uses for (2)?

> The .conda directory is more interesting. It has three uses.
> 
> 1. Under normal install conditions conda needs a guaranteed writable package cache. By default that’s the pkgs directory in the base environment, but when the base environment is read-only then we fall back to~/.conda/pkgs. We haven’t developed a --no-cache option like apk has. Perhaps we should, but it might be quite a lot of work and probably not a high priority.
> 2. Conda needs a writable location to create environments when a user invoked conda create -n. We use ~/.conda/envs as part of that search path and fall back there when the base environment is read-only.
> So for the first two, the solution seems to me to just make sure your base environment is writable if you don’t want conda falling back to the home directory.

Is this recent behaviour? I believe that I have had to force this previously with;
```
conda config --system --add envs_dirs $CONDA_DIR/envs
conda config --system --add pkgs_dirs $CONDA_DIR/pkgs
```

> The most interesting here probably is ~/.conda/environments.txt, which conda has long used to journal locations where it’s created environments. This especiakky applies when environments are created with conda create -p. Running conda search --envs as root gives a sysadmin the ability to search through all conda environments on the system. Without such journaling, you’d have to do a brute-force listing of the whole file system to search for conda environments.
> In recent versions of conda 4.6, the requirement to write to ~/.conda/environments.txt was relaxed and conda only emits a warning.

I think there might be a bug in this code that I'm hitting?

**Comment by OliverWalter** [comment]
> > The most interesting here probably is ~/.conda/environments.txt, which conda has long used to journal locations where it’s created environments. This especiakky applies when environments are created with conda create -p. Running conda search --envs as root gives a sysadmin the ability to search through all conda environments on the system. Without such journaling, you’d have to do a brute-force listing of the whole file system to search for conda environments.
> > In recent versions of conda 4.6, the requirement to write to ~/.conda/environments.txt was relaxed and conda only emits a warning.
> 
> I think there might be a bug in this code that I'm hitting?

I am hitting the same bug. This bug prevents me from using conda on our build server at all due to a configuration change in the build server which disables write access to the users home directory.

I am trying to install miniconda
```
# NAME:  Miniconda3
# VER:   4.7.10
# PLAT:  linux-64
# MD5:   445e92c097dd461ef54ba736d5a4442c
```

With `./Miniconda3-latest-Linux-x86_64.sh -b -p $conda_dir`

which fails with
`Permission denied: '~/.conda/environments.txt'`

Where the home directory is not writeable (the files might exist though - not 100% sure)

Also setting `envs_dirs` and `pkgs_dirs` to not change this behaviour.

Unfortunately this is a serious bug for me since I'm unable to use conda at all because of this.
