### ISSUE TITLE
Not able to create virtual environment

### ISSUE THREAD

**Issue by KarthikINV** [conda/conda#8603]
* commands under 'conda env':
 
conda create -name py36 python

## Current Behavior
<!-- What actually happens?
Fetching package metadata ...........

PackageNotFoundError: Package missing in current linux-64 channels:
  - python

### Steps to Reproduce
conda create -n inv python -vv
DEBUG conda.cli.main:_main(132): verbosity set to 2
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/miniconda' using path '/opt/miniconda/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/conda-meta/history'
DEBUG conda.core.index:fetch_index(106): channel_urls=OrderedDict([(u'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64', (u'anaconda', 0)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch', (u'anaconda', 0)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64', (u'r-channel', 1)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch', (u'r-channel', 1)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64', (u'ng-custom', 2)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch', (u'ng-custom', 2)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64', (u'conda-forge', 3)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch', (u'conda-forge', 3))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/pkgs/urls.txt'
DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64 at /home/services/.conda/pkgs/cache/3fb215e0.json
DEBUG requests.packages.urllib3.connectionpool:_new_conn(212): Starting new HTTP connection (1): nguksvlrtw163.uk.corporg.net
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/anaconda/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/anaconda/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Fri, 08 Feb 2019 10:13:47 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:08 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.041434

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/3fb215e0.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch at /home/services/.conda/pkgs/cache/eb046c37.json. Timeout in 15888 sec
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/eb046c37.q
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64 at /home/services/.conda/pkgs/cache/b8b2b04c.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/r-channel/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/r-channel/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:08:59 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.031047

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/b8b2b04c.q
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch at /home/services/.conda/pkgs/cache/e29fe3be.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/r-channel/noarch/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/r-channel/noarch/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:08:59 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.039492

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch'. Updating mtime and loading from disk
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64 at /home/services/.conda/pkgs/cache/53c8f9e0.json. Timeout in 15888 sec
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/53c8f9e0.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch at /home/services/.conda/pkgs/cache/18c2e63c.json. Timeout in 15888 sec
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64 at /home/services/.conda/pkgs/cache/a328a716.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/conda-forge/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/conda-forge/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:50:35 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.033887

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/a328a716.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch at /home/services/.conda/pkgs/cache/38e2de65.json. Timeout in 15889 sec
.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/miniconda' using path '/opt/miniconda/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/miniconda' using path '/opt/miniconda/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/conda-meta/history'
Current conda install:

               platform : linux-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 2.1.4
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/miniconda  (read only)
    default environment : /opt/miniconda
       envs directories : /home/services/envs
                          /home/services/.conda/envs
                          /opt/miniconda/envs
          package cache : /opt/miniconda/pkgs
                          /home/services/.conda/pkgs
           channel URLs : http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch
            config file : /home/services/.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
                UID:GID : 513:516

`$ /opt/miniconda/bin/conda create -n inv python -vv`

    Traceback (most recent call last):
      File "/opt/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 306, in install
        raise PackageNotFoundError(error_message)
    PackageNotFoundError: Package missing in current linux-64 channels:
      - python

## Expected Behavior
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/esingh/envs/py36:

The following NEW packages will be INSTALLED:

    ca-certificates: 2019.1.23-0             anaconda
    certifi:         2018.11.29-py27_0       anaconda
    libedit:         3.1.20181209-hc058e9b_0 anaconda
    libffi:          3.2.1-hd88cf55_4        anaconda
    libgcc-ng:       8.2.0-hdf63c60_1        anaconda
    libstdcxx-ng:    8.2.0-hdf63c60_1        anaconda
    ncurses:         6.1-he6710b0_1          anaconda
    openssl:         1.1.1-h7b6447c_0        anaconda
    pip:             19.0.1-py27_0           anaconda
    python:          2.7.15-h9bab390_6       anaconda
    readline:        7.0-h7b6447c_5          anaconda
    setuptools:      40.7.3-py27_0           anaconda
    sqlite:          3.26.0-h7b6447c_0       anaconda
    tk:              8.6.8-hbc83047_0        anaconda
    wheel:           0.32.3-py27_0           anaconda
    zlib:            1.2.11-h7b6447c_3       anaconda

Proceed ([y]/n)?

## Environment Information
conda -info

Current conda install:

               platform : linux-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 2.1.4
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/miniconda  (read only)
    default environment : /opt/miniconda
       envs directories : /home/esingh/envs
                          /home/esingh/.conda/envs
                          /opt/miniconda/envs
          package cache : /opt/miniconda/pkgs
                          /home/esingh/.conda/pkgs
           channel URLs : http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64
                          http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch
            config file : /home/esingh/.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
                UID:GID : 524:526

**Comment by jjhelmus** [comment]
@KarthikINV Can you provide more details on the errors you are seeing and the environment in which this is occurring?

**Comment by KarthikINV** [comment]
# Command -

 conda create -n inv python -vv

# Present Output -

DEBUG conda.cli.main:_main(132): verbosity set to 2
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/miniconda' using path '/opt/miniconda/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/conda-meta/history'
DEBUG conda.core.index:fetch_index(106): channel_urls=OrderedDict([(u'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64', (u'anaconda', 0)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch', (u'anaconda', 0)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64', (u'r-channel', 1)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch', (u'r-channel', 1)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64', (u'ng-custom', 2)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch', (u'ng-custom', 2)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64', (u'conda-forge', 3)), (u'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch', (u'conda-forge', 3))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.gateways.disk.test:file_path_is_writable(29): [Errno 13] Permission denied: u'/opt/miniconda/pkgs/urls.txt'
DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64 at /home/services/.conda/pkgs/cache/3fb215e0.json
DEBUG requests.packages.urllib3.connectionpool:_new_conn(212): Starting new HTTP connection (1): nguksvlrtw163.uk.corporg.net
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/anaconda/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/anaconda/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Fri, 08 Feb 2019 10:13:47 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:08 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.041434

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/3fb215e0.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/anaconda/noarch at /home/services/.conda/pkgs/cache/eb046c37.json. Timeout in 15888 sec
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/eb046c37.q
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64 at /home/services/.conda/pkgs/cache/b8b2b04c.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/r-channel/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/r-channel/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:08:59 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.031047

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/b8b2b04c.q
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch at /home/services/.conda/pkgs/cache/e29fe3be.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/r-channel/noarch/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/r-channel/noarch/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:08:59 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.039492

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/r-channel/noarch'. Updating mtime and loading from disk
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/linux-64 at /home/services/.conda/pkgs/cache/53c8f9e0.json. Timeout in 15888 sec
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/53c8f9e0.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/ng-custom/noarch at /home/services/.conda/pkgs/cache/18c2e63c.json. Timeout in 15888 sec
.DEBUG conda.core.repodata:fetch_repodata(454): Locally invalidating cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64 at /home/services/.conda/pkgs/cache/a328a716.json
DEBUG requests.packages.urllib3.connectionpool:_make_request(400): http://nguksvlrtw163.uk.corporg.net:8080 "GET /conda/conda-forge/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(140):
>>GET /conda/conda-forge/linux-64/repodata.json HTTP
> User-Agent: conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-696.3.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json
> If-Modified-Since: Mon, 04 Feb 2019 14:50:35 GMT

<<HTTP 304 NOT MODIFIED
< Date: Wed, 24 Apr 2019 14:12:10 GMT
< license_expired: False
< license_valid: True
< Server: gunicorn/19.1.0
< Connection: keep-alive
< Elapsed: 00:00.033887

DEBUG conda.core.repodata:fetch_repodata(462): 304 NOT MODIFIED for 'http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/linux-64'. Updating mtime and loading from disk
DEBUG conda.core.repodata:read_pickled_repodata(339): found pickle file /home/services/.conda/pkgs/cache/a328a716.q
.DEBUG conda.core.repodata:fetch_repodata(450): Using cached repodata for http://nguksvlrtw163.uk.corporg.net:8080/conda/conda-forge/noarch at /home/services/.conda/pkgs/cache/38e2de65.json. Timeout in 15889 sec
.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

# Expected output -

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/esingh/envs/py36:

The following NEW packages will be INSTALLED:

    ca-certificates: 2019.1.23-0             anaconda
    certifi:         2018.11.29-py27_0       anaconda
    libedit:         3.1.20181209-hc058e9b_0 anaconda
    libffi:          3.2.1-hd88cf55_4        anaconda
    libgcc-ng:       8.2.0-hdf63c60_1        anaconda
    libstdcxx-ng:    8.2.0-hdf63c60_1        anaconda
    ncurses:         6.1-he6710b0_1          anaconda
    openssl:         1.1.1-h7b6447c_0        anaconda
    pip:             19.0.1-py27_0           anaconda
    python:          2.7.15-h9bab390_6       anaconda
    readline:        7.0-h7b6447c_5          anaconda
    setuptools:      40.7.3-py27_0           anaconda
    sqlite:          3.26.0-h7b6447c_0       anaconda
    tk:              8.6.8-hbc83047_0        anaconda
    wheel:           0.32.3-py27_0           anaconda
    zlib:            1.2.11-h7b6447c_3       anaconda

Proceed ([y]/n)?

**Comment by msarahan** [comment]
you have custom configured channels.  You need to figure out why your channels don't have python packages on them.

**Comment by kalefranz** [comment]
If you’re an Anaconda, Inc. customer and still having difficulties, feel free to email support@anaconda.com.

**Comment by msarahan** [comment]
Yes, please. I don't think this is a conda bug, but more a server configuration issue. The customer support team will be able to help with that more than the conda team can.
