### ISSUE TITLE
Why does conda init install to Profile.ps1 for powershell

### ISSUE THREAD

**Issue by musm** [conda/conda#8608]
Why does `conda init ` install the conda powershell script to `Profile.ps1`  CurrentUserAllHosts, instead of `CurrentUserCurrentHost`  (the more reasonable location) 

see https://devblogs.microsoft.com/scripting/understanding-the-six-powershell-profiles/

**Comment by E3V3A** [comment]
Even worse is that `conda init` overwrite both your `C:\Users\<name>\Documents\WindowsPowerShell\profile.ps1` and `C:\Users\<name>\Documents\PowerShell\profile.ps1`.
