### ISSUE TITLE
conda-build on win-64 also activate x86 environment

### ISSUE THREAD

**Issue by saedrna** [conda/conda#8610]
## Current Behavior

Hi,

I am using conda-build to prepare packages on win-64. At the last of the setup of the environment. I see this

```
C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\work>IF NOT "1" == "" (
set "INCLUDE=C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\_h_env\Library\include;C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\_h_env\Library\include;"
 set "LIB=C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\_h_env\Library\lib;C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\_h_env\Library\lib;"
 set "CMAKE_PREFIX_PATH=C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\_h_env\Library;"
)

C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\work>ECHO is on.
is on.

C:\Users\huhan\Miniconda3\conda-bld\xerces-c_1556353928221\work>pushd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>CALL "VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.11
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.11
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
```

You can see that the x86 env is initialized after x64. And then I got the wrong compilers.

I'm not sure if others can reproduce the bug, because I just get it right yesterday, but get this when using conda-build today.

My question is, is there a clue of how to fix this problem?

Thanks,

Han

**Comment by saedrna** [comment]
I think the problem is in the following file `vs2017_compiler_vars.bat` in the `_build_env`

at the end, I have
```
IF NOT "%CONDA_BUILD%" == "" (
  set "INCLUDE=%LIBRARY_INC%;%INCLUDE%"
  set "LIB=%LIBRARY_LIB%;%LIB%"
  set "CMAKE_PREFIX_PATH=%LIBRARY_PREFIX%;%CMAKE_PREFIX_PATH%"
)

:: other things added by install_activate.bat at package build time
ECHO is on.
pushd "%VSINSTALLDIR%" 
CALL "VC\Auxiliary\Build\vcvars64.bat" 
popd 
IF "%CMAKE_GENERATOR%" == "" ( 
SET "CMAKE_GENERATOR=Visual Studio 15 2017" 
) 
pushd "%VSINSTALLDIR%" 
CALL "VC\Auxiliary\Build\vcvars32.bat" 
popd 
```

**Comment by saedrna** [comment]
Seems it is the problem in `win-64/vs2017_win-64-19.15.26726-hb4ce483_3.tar.bz2` in the conda-forge repo, which is updated two hours ago,
Manually forcing to `vs2017_win-64 19.15.26726 h3c6f0ee_0` works fine for me.

**Comment by mbargull** [comment]
Please try to honor the important information from the issue template:
```
Hi!  Read this; it's important.

This is an issue tracker for conda -- the package manager.  File feature requests
for conda here, as well as bug reports about something conda has messed up.

If your issue is a bug report for:
  * a specific conda package from Anaconda ('defaults' channel):
      ==> file at https://github.com/ContinuumIO/anaconda-issues
  * a specific conda package from conda-forge:
      ==> file at the corresponding feedstock under https://github.com/conda-forge
  * repo.anaconda.com access and service:
      ==> file at https://github.com/ContinuumIO/anaconda-issues
  * anaconda.org access and service:
      ==> file at https://anaconda.org/contact/report
  * commands under 'conda build':
      ==> file at https://github.com/conda/conda-build
  * commands under 'conda env':
      ==> please file it here!
  * all other conda commands that start with 'conda':
      ==> please file it here!
...
```
=> Usually, general `conda-build` related issues should be filed here but at `conda-build`'s issue tracker.
Your specific issue is with a package from Anaconda, hence https://github.com/ContinuumIO/anaconda-issues would be the correct place to file this.

---

Nonetheless, the issue you are seeing is likely introduced by the change at https://github.com/AnacondaRecipes/aggregate/pull/138/files#diff-38bc79c9f62a3bdf8dddabd69f2686b4R11, i.e., it looks like the `)` isn't `echo`'d but interpreted as the closing parenthesis in the build script.
cc @isuruf, @msarahan, @mingwandroid 
My Windows Batch scoping/quoting knowledge is a bit rusty/gappy: Does quoting the `(` or changing the `echo ) >>` to `echo.) >>` suffice?

**Comment by isuruf** [comment]
https://github.com/AnacondaRecipes/aggregate/pull/149

**Comment by mbargull** [comment]
Great, thanks @isuruf!
Closing in favor of https://github.com/AnacondaRecipes/aggregate/pull/149.
@saedrna, feel free to follow further progress over there.
