### ISSUE TITLE
LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_6

### ISSUE THREAD

**Issue by anuragFA** [conda/conda#8617]
C:\Users\PC\Documents\Machine Learning\Tensorflow-Bootcamp-master>conda env create -f tfdl_env.yml
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: - DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\PC\Anaconda3\envs\tfdeeplearning', env_name: 'tfdeeplearning', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\PC\Anaconda3\python.exe, args are ['C:\\Users\\PC\\Anaconda3\\cwp.py', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\python.exe', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\Scripts\\ipython-script.py']
\ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\PC\Anaconda3\envs\tfdeeplearning', env_name: 'tfdeeplearning', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\PC\Anaconda3\python.exe, args are ['C:\\Users\\PC\\Anaconda3\\cwp.py', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\python.exe', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']
| DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\PC\Anaconda3\envs\tfdeeplearning', env_name: 'tfdeeplearning', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\PC\Anaconda3\pythonw.exe, args are ['C:\\Users\\PC\\Anaconda3\\cwp.py', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\pythonw.exe', 'C:\\Users\\PC\\Anaconda3\\envs\\tfdeeplearning\\Scripts\\jupyter-qtconsole-script.py']
\ ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'defaults::qt-5.6.2-vc14_6'.
LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_6
running your command again with `-v` will provide additional information
location of failed script: C:\Users\PC\Anaconda3\envs\tfdeeplearning\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'defaults::qt-5.6.2-vc14_6'.
LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_6
running your command again with `-v` will provide additional information
location of failed script: C:\Users\PC\Anaconda3\envs\tfdeeplearning\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_6
running your command again with `-v` will provide additional information
location of failed script: C:\Users\PC\Anaconda3\envs\tfdeeplearning\Scripts\.qt-post-link.bat
==> script messages <==
<None>

**Comment by anuragFA** [comment]
I am trying to run `conda env create -f tfdl_env.yml` but getting this error. I ran the command in the command prompt as an administrator to avoid all the admin related issue but still found the same error

**Comment by mingwandroid** [comment]
Update conda before updating other things.
