### ISSUE TITLE
Conda stuck at Verifying transaction for two days

### ISSUE THREAD

**Issue by danielyao12** [conda/conda#8631]
I try to install ipyrad in conda, but I am waiting for Verifying transaction for two days. Normally, this installation only needs less than 1 hour to complete in the server I used with the same version of conda and ipyrad. Should I still wait for the Verifying transaction finish? Or wait for someone finally posted the same issue and got help to solve? I have searched many information about the "speedup" complain, but no one because of two days waiting. And I'm still waiting for.

Here is my conda information, if any one can help me. Thank you.

$ conda info

    active environment : base
    active env location : /lustre/home/yaoxin/miniconda2_20190504
            shell level : 1
       user config file : /lustre/home/yaoxin/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /lustre/home/yaoxin/miniconda2_20190504  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /lustre/home/yaoxin/miniconda2_20190504/pkgs
                          /lustre/home/yaoxin/.conda/pkgs
       envs directories : /lustre/home/yaoxin/miniconda2_20190504/envs
                          /lustre/home/yaoxin/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/2.7.15 Linux/2.6.32-431.23.3.el6_lustre.x86_64 rhel/6.5 glibc/2.12
                UID:GID : 527:530
             netrc file : None
           offline mode : False

**Comment by soapy1** [comment]
Is this still a problem for you? Could you share the command you are using to do the install

**Comment by danielyao12** [comment]
The command I used was just following the instruction in the Miniconda website, which were downloading the file through command and bash the downloaded file to install. The final solution I found was that installing the Anaconda instead of the Miniconda.
