### ISSUE TITLE
Proposal: reduced views of repodata

### ISSUE THREAD

**Issue by msarahan** [conda/conda#8634]
We are currently plagued by old packages with "bad" metadata causing massively long solve times.  We're working on this issue from many sides: removing the "free" channel as part of defaults, improving index reduction in conda, and working with conda-forge to clean up old packages.  This proposal is a general approach that would apply to any index that is generated by conda-index (part of conda-build).

The goal: reduce the repodata that clients receive by default to the bare minimum needed for an up-to-date installation with current packages.

The implementation:
* start with a full index
* collect the most recent versions for every package.  This should be guided by a conda_build_config.yaml pinning file, such that we may support things like python 3.6, 3.7, 2.7, or hdf5 1.8, 1.10.
* Trim everything from the index except those latest packages
* check satisfiability of the overall system
* add any older packages that are necessary to ensure satisfiability

Additional forms:
* "archive" - the full index
* Epochs - apply the above, but within time ranges.  Filter out packages newer than the upper bound, and keep only packages that either have updates within an epoch, or were not updated within an epoch.  Epochs may need their own independent conda_build_config.yaml files.

This proposal does not affect the URL for the actual packages themselves.  They would remain in one place, but the repodata would be served from different places, or under different filenames.

**Comment by msarahan** [comment]
Conda would default to only using the most recent repodata.  It would fall back to the archive if a spec had no candidates, and then finally throw a requirement not found error if still no candidates are available.

**Comment by soapy1** [comment]
I have a couple of questions:
- Will this be done on a channel by channel basis?
- How do you decide when an epoch starts/ends
- Will this change hose any packages? I can't think of any situations off the top of my head but it seems like some packages might get in a sticky situation?
- How do you check the satisfiability of the whole system?

**Comment by msarahan** [comment]
Great questions!

1. Yes, since it is put in effect by updating the index, it will happen when a conda-build that has this logic is used to rebuild the index.
2. I was planning on just simply quarterly.  It's a bit arbitrary.  Since we're only creating alternative JSON files, we can probably do pretty arbitrary time intervals.
3. As long as we have the satisfiability of the channel done, I think the main disruption may just be unexpected updates - people being forced forwards more than they otherwise would be.  I think the local package collection will still allow the solver to function in a way that minimizes this, though.
4. My plan there was to build a graph and ensure that every dependency that should have one or more edges does have those edges.  For example, if a package has a dependency on zlib, but has no edges in the graph to a zlib package, then it's bad.  It's a great big recursive ball of find_matches() function calls.

**Comment by msarahan** [comment]
Implemented in #8670
