### ISSUE TITLE
Upgrading Python completely broke conda

### ISSUE THREAD

**Issue by SenileFelineS** [conda/conda#8646]
## Current Behavior

I upgraded Python (2.7.6 to 2.7.16) and now ```python``` and ```conda``` are broken. 

### Steps to Reproduce

When I try to run python:
```
$ python
Illegal instruction: 4
```

When I try to run conda:
```
$ conda
Illegal instruction: 4
```

Perhaps this explains the issue: https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

Nonetheless, I tried to edit the code from the ```conda``` executable file to run from a different version of python. To the beginning of ```/Users/User1/anaconda2/bin/conda```, I added:
```
#!/Users/User1/anaconda2/python.app/Contents/MacOS/python
```

Now, conda **will** run! However, I can't figure out how to revert back to my old revision of python because if I run ```$ conda list --revision``` I get: 

```
EnvironmentLocationNotFound: Not a conda environment: /Users/User1/anaconda2/python.app/Contents
```
I'm not sure how to change my revision back to undo the changes that happened when I upgraded Python 2.7.6 to Python 2.7.16

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /Users/User1/.condarc
 populated config files : /Users/User1/.condarc
          conda version : 4.6.14
    conda-build version : 2.0.2
         python version : 2.7.16.final.0
       base environment : /Users/User1/anaconda2/python.app/Contents  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/User1/anaconda2/python.app/Contents/pkgs
                          /Users/User1/.conda/pkgs
       envs directories : /Users/User1/.conda/envs
                          /Users/User1/anaconda2/python.app/Contents/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/2.7.16 Darwin/11.4.2 OSX/10.7.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/User1/.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
EnvironmentLocationNotFound: Not a conda environment: /Users/User1/anaconda2/python.app/Contents
```
</p></details>

**Comment by mingwandroid** [comment]
MacOS 10.7 is no longer supported. It is 8 years old, Apple no longer update it to address security problems and updates to new versions are free (provided your hardware is modern enough).

**Comment by SenileFelineS** [comment]
@mingwandroid I understand, and I plan to upgrade to a newer OS in the near future. I have two questions:

1. Is there anything I can do to fix my situation so I can bring python/conda back to what it was before I update it?

2. From link above https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10 , could I compile python from source by throwing the ```-mmacosx-version-min=10.7``` flag? If I understand, I simply downloaded the binary that was compiled to only work on supported OS's.

As a side note, shouldn't conda know not to upgrade packages that aren't compiled to even work on a specific OS version?

**Comment by mingwandroid** [comment]
You might be able to compile python from source on 10.7, yes, but to use any modern anaconda distribution packages with it you'd also need to rebuild those. Some of them will use APIs that were added to these sdk more recently. You'll have to rework those bits of code.

Unfortunately macOS is the os that cares least for backwards compatibility.

**Comment by SenileFelineS** [comment]
1. How can I go about compiling myself? 
2. In the meantime, do you know how I can revert my version of Python 2.7 back to 2.7.6 (the before I updated it)? If I revert it, then conda should work again.

**Comment by SenileFelineS** [comment]
@mingwandroid If I want to reinstall the proper version of python, should I install miniconda and use that to revert my environment to the previous revision number (the revision before I manually tried to update python from 2.7.6 to 2.7.16)?

**Comment by SenileFelineS** [comment]
My solution, although inelegant, to rectify my mistake (hopefully useful to future readers):

1. Edit the first line of ```/Users/User1/anaconda2/bin/conda``` to execute with another version of Python 2.7 that works. I changed the first line from ```#!/Users/User1/anaconda2/bin/python``` to ```#!/Users/User1/anaconda2/python.app/Contents/MacOS/python```. I probably could have used another python 2.7.6 interpreter, but this one was already available.

2. Create a new conda environment with ```conda create --name newenvironment python=2.7.6```.

3. I copied the newly created version of Python 2.7.6, which is the file  ```/Users/User1/.conda/envs/newenvironment/bin/python2.7``` to the directory ```/Users/User1/anaconda2/bin/```. As a safety measure, **before copying**, I renamed ```/Users/User1/anaconda2/bin/python2.7``` to ```/Users/User1/anaconda2/bin/python2.7_old```, just in case I needed it later.

4. Now I had a working version of python2.7. I reverted my actions in step 1, where I edited ```/Users/User1/anaconda2/bin/conda``` to have its first line as ```#!/Users/User1/anaconda2/bin/python``` again.

5. From here, I re-installed Python 2.7.6 and its dependents/dependencies by running ```conda install python=2.7.6```.  This reverted my conda environment back to before I updated Python to 2.7.16.

There probably was an easier way to do this, but now I'm back to a working environment.

**Comment by mingwandroid** [comment]
Great, thanks fot the howto. Hopefully some will find it useful.

**Comment by SenileFelineS** [comment]
@mingwandroid, since Anaconda allows anyone to download older versions of Anaconda, does that mean that there should be some safeguard built into Anaconda for someone to prevent this from happening, just like it happened to me when I manually updated Python 2.7 to its newest version at 2.7.16.

I think it's also worth mentioning that the issue is because conda downloads python packages that are compiled to not be backwards compatible with older versions of Mac OS X, even though than can be compiled to be backwards compatible (I can run Python 2.7.16 without errors by installing it through Macports. It's just that during compilation time, the flag that needs to be added is:```-mmacosx-version-min=10.X```, where ```X``` is a version of Mac OS X. (e.g. 10.7, as with my version of Mac OS X.))

**Comment by mingwandroid** [comment]
It would be good if our package metadata included this info so the solver can avoid breaking your install but we've not had time to do it yet. I think some progress has been made though. 

> I think it's also worth mentioning that the issue is because conda downloads python packages that are compiled to not be backwards compatible with older versions of Mac OS X, even though than can be compiled to be backwards compatible (I can run Python 2.7.16 without errors by installing it through Macports. It's just that during compilation time, the flag that needs to be added is:-mmacosx-version-min=10.X, where X is a version of Mac OS X. (e.g. 10.7, as with my version of Mac OS X.))

While that's true of python it certainly isn't true in general. In particular qt will not compile or run on macOS because it uses chromium and Google cares little about supporting old versions of macOS.
