### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by epruesse** [conda/conda#8650]
I assume this is because of the growing repodata from both Bioconda and Conda-Forge. I'm seeing 427MB RSS size for a `conda env create` with an `conda export` created fully pinned environment.

That amount of memory may not look like much, but it cloud environments are often very small as memory costs real money. In my case, my docs build fails on readthedocs: https://readthedocs.org/projects/ymp/builds/9045409/

## Steps to Reproduce

```shell
wget https://raw.githubusercontent.com/epruesse/ymp/4047870bb53603b52d7471fba0b59ffa40134f5f/pinned_env.yaml
wget https://gist.githubusercontent.com/netj/526585/raw/7f7cd17541a1d29bc978eccc80c270ab6b83ed9c/memusg
chmod +x memusg
./memusg conda env install --name latest --file pinned_env.yaml
```

**Comment by msarahan** [comment]
That seems like a reasonable diagnosis.  I'm sure there's things we could do to make the metadata handling more memory-efficient, but I think effort right now is better spent on reducing the size of the repodata.  I'm working on a way to have an "archive" with everything and a reduced view that shows only the latest.  See https://github.com/conda/conda/issues/8634

**Comment by kalefranz** [comment]
#8651 should _substantially_ reduce memory consumption.  Something else we should benchmark in addition to performance.

**Comment by epruesse** [comment]
I suppose that was my point here. It would be good to track memory usage for regressions and have tests that set bounds. Otherwise, it's easy to let it slip because a typical dev machine has ample memory.

One question: Are there any tricks in writing an env.yaml that could keep the memory requirements down? I keep getting the 427 OOM error now.

**Comment by kalefranz** [comment]
Limit your use of channels, and/or use the conda metachannel project/servers.

**Comment by epruesse** [comment]
Using only conda-forge, I need 350MB. I need one Bioconda package. Whether I use `bioconda::package` or add it to the channel and in which order I do makes no real difference. I need 410 to 450MB (pretty random). Pinning more losely or strictly, adding redundant package specifications (listing dependencies) makes little difference.

I cannot use metachannels because all I'm trying to do is getting my documentation to build again on readthedocs...

**Comment by kalefranz** [comment]
I don’t think explicit installs are supported in conda env, but that’s probably what I’d try to make work here for now. Explicit installs are where you specify the exact url or full path of the package tarball. 

    conda install https://conda.anaconda.org/bioconda/linux-64/package-version-build.tar.bz2

**Comment by epruesse** [comment]
Having `conda env install` understand the format used by `conda list --explicit` containing URLs might be a quick fix.

**Comment by epruesse** [comment]
See also https://github.com/conda/conda/issues/5003
