### ISSUE TITLE
Running conda within activated environment

### ISSUE THREAD

**Issue by epruesse** [conda/conda#8655]
```
$ conda activate tmp
$ conda env create -n test -f env.yaml
CondaValueError: prefix already exists: ...miniconda3/envs/tmp/envs/test
$ conda env remove -n test
$ conda env create -n test -f env.yaml
CondaValueError: prefix already exists: ...miniconda3/envs/tmp/envs/test
```

When running `conda env create` inside of an activated environment, the environment is created at `CONDA/envs/ENV1/envs/ENV2`, while `conda env remove` looks for the environment `CONDA/envs/ENV2` and `conda env list` shows only the outer environments and `conda clean` finds only the outer `pkgs` folder.

`conda-build` behaves similarly, as does `api.render`. The build and package cache and environments are created inside the environment and can only be removed manually.

Note - outer env `tmp` has a `conda` installed for pinning reasons.

**Comment by kalefranz** [comment]
The issue here is that the `conda` package is installed in the environment you’ve activated. Conda always thinks of the environment within which its own code is located as the base environment, and the *default* values for `envs_dirs` and `pkgs_dirs` are derived relative to that location.

At some point in the future it might make sense to create a `condalib` package that contains all of the actual conda python code, and then the `conda` package would only contain the actual entry points, and have a dependency on `condalib`.

I’d reserve the overtaking of the `libconda` name for when we someday have a single-file compiles dynamic library that provides all of the conda functionality.

**Comment by epruesse** [comment]
Agreed. The reason I would consider it a bug is that `conda env list` uses a different path than `conda env install`, and that `conda-build` uses a different path than `conda clean`. If all parts of conda would use the inner environment, that'd be ok, but the mix is at least "unexpected" and probably more difficult to document than to repair.

**Comment by kalefranz** [comment]
Can you share the output of `conda info` in a new terminal before ever invoking something like `conda activate tmp`?

**Comment by epruesse** [comment]
``
     active environment : None
            shell level : 0
       user config file : /home/epruesse/.condarc
 populated config files : /home/epruesse/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /home/epruesse/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/epruesse/miniconda3/pkgs
                          /home/epruesse/.conda/pkgs
       envs directories : /home/epruesse/miniconda3/envs
                          /home/epruesse/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Linux/4.18.0-18-generic ubuntu/18.10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : /home/epruesse/.netrc
           offline mode : False
```
