### ISSUE TITLE
make conda usable when installed from pip

### ISSUE THREAD

**Issue by davidedelvento** [conda/conda#8657]
## Current Behavior
I am following the instructions described at https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/
I know one should not do this, etc etc but I am forced to find workarounds on other issues I am encountering (e.g. https://github.com/pypa/pip/issues/6494) so this would be a great one -- if it worked. But it does not.

### Steps to Reproduce
```
pip install conda
conda install whatever
```
and it fails with

```
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
```

Same problem with `conda create --name my_env`

## Expected Behavior
Just install the `whatever` package or create `my_env` environment, probably after a very dire warning telling that this will kill of your loved ones, it is unsupported, proceed at your own risk, etc etc.

Obviously I am not the only one trying to do this, see for example [this answer](https://stackoverflow.com/a/48471693/25891) on stackoverflow. 

Is there a better workaround to make this work without the ugly editing of the binaries?

Are the conda developers interested in making this possible?

**Comment by msarahan** [comment]
There was some discussion about this here: https://discuss.python.org/t/drawing-a-line-to-the-scope-of-python-packaging/883

I think we'd be fine with supporting a restricted conda version that could only create environments and modify environments that it created, not modify the environment in which pip installed conda.  If conda is allowed to modify the environment in which pip installs it, you're basically in the same boat as people using "sudo pip install" stuff, and even though absolutely everyone says "DON'T DO THAT!!!" somehow people manage to do it anyway, and then they wind up complaining that conda or pip broke their computer.  It doesn't matter how much people say "DON'T DO THAT," some people with broken computers will always come and complain.  That's a drain on our attention, and I don't want that at all.

We're working on a standalone executable of conda, and that will make this kind of thing much more viable.
