### ISSUE TITLE
conda command disappears after installing imageio

### ISSUE THREAD

**Issue by itarec1988** [conda/conda#8658]
**I'm submitting a...**
  - [x ] bug report
  - [ ] feature request

## Current Behavior

I had a working environment with python3.6, and I did conda install -c conda-forge imageio and then the conda command was broken. It seems that the python version was downgraded in the installation. I now have python2.7. I would like to undo what I did without uninstalling anaconda. I have a backup environment that might come in handy. But I dont know how to proceed.

### Steps to Reproduce

```
conda install -c conda-forge imageio
```
Collecting package metadata: done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.6.3
  latest version: 4.6.14

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /pf/b/b301034/anaconda3

  added / updated specs:
    - imageio

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py27_0         149 KB  conda-forge
    curl-7.64.1                |       hf8cf82a_0         128 KB  conda-forge
    enum34-1.1.6               |        py27_1001          56 KB  conda-forge
    futures-3.2.0              |        py27_1000          24 KB  conda-forge
    hdf4-4.2.13                |                0         969 KB  conda-forge
    hdf5-1.10.1                |                2         5.0 MB  conda-forge
    imageio-2.5.0              |           py27_0         3.4 MB  conda-forge
    krb5-1.16.3                |    h05b26f9_1001         1.4 MB  conda-forge
    libcurl-7.64.1             |       hda55be3_0         584 KB  conda-forge
    libedit-3.1.20170329       |    hf8c457e_1001         172 KB  conda-forge
    libgcc-ng-8.2.0            |       hdf63c60_1         7.6 MB
    libnetcdf-4.4.1.1          |               10         2.0 MB  conda-forge
    libssh2-1.8.2              |       h22169c7_2         257 KB  conda-forge
    libstdcxx-ng-8.2.0         |       hdf63c60_1         2.9 MB
    lzo-2.10                   |    h14c3975_1000         319 KB  conda-forge
    ncurses-6.1                |    hf484d3e_1002         1.3 MB  conda-forge
    numpy-1.14.2               |   py27hdbf6ddf_0         4.0 MB
    openssl-1.1.1b             |       h14c3975_1         4.0 MB  conda-forge
    pillow-3.2.0               |           py27_1         785 KB  conda-forge
    pip-19.1                   |           py27_0         1.8 MB  conda-forge
    python-2.7.15              |    h721da81_1008        12.8 MB  conda-forge
    qt-4.8.7                   |                2        34.1 MB
    readline-7.0               |    hf8c457e_1001         391 KB  conda-forge
    setuptools-41.0.1          |           py27_0         650 KB  conda-forge
    sqlite-3.26.0              |    h67949de_1001         1.9 MB  conda-forge
    tk-8.6.9                   |    h84994c4_1001         3.2 MB  conda-forge
    wheel-0.33.3               |           py27_0          34 KB  conda-forge
    zlib-1.2.11                |    h14c3975_1004         101 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        89.9 MB

The following NEW packages will be INSTALLED:

  enum34             conda-forge/linux-64::enum34-1.1.6-py27_1001
  futures            conda-forge/linux-64::futures-3.2.0-py27_1000
  imageio            conda-forge/linux-64::imageio-2.5.0-py27_0
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libcurl            conda-forge/linux-64::libcurl-7.64.1-hda55be3_0
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  pip                conda-forge/linux-64::pip-19.1-py27_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.1.23-0 --> conda-forge::ca-certificates-2019.3.9-hecc5488_0
  certifi              pkgs/main::certifi-2018.11.29-py36_0 --> conda-forge::certifi-2019.3.9-py27_0
  curl                             pkgs/free::curl-7.52.1-0 --> conda-forge::curl-7.64.1-hf8cf82a_0
  hdf5                     anaconda::hdf5-1.10.1-h9caa474_1 --> conda-forge::hdf5-1.10.1-2
  libgcc-ng            anaconda::libgcc-ng-7.2.0-hdf63c60_3 --> pkgs/main::libgcc-ng-8.2.0-hdf63c60_1
  libnetcdf          anaconda::libnetcdf-4.4.1.1-h816af47_8 --> conda-forge::libnetcdf-4.4.1.1-10
  libstdcxx-ng       anaconda::libstdcxx-ng-7.2.0-hdf63c60~ --> pkgs/main::libstdcxx-ng-8.2.0-hdf63c60_1
  lzo                         anaconda::lzo-2.10-h49e0be7_2 --> conda-forge::lzo-2.10-h14c3975_1000
  numpy                               1.13.3-py36ha266831_3 --> 1.14.2-py27hdbf6ddf_0
  openssl              pkgs/main::openssl-1.0.2p-h14c3975_0 --> conda-forge::openssl-1.1.1b-h14c3975_1
  readline                        pkgs/free::readline-6.2-2 --> conda-forge::readline-7.0-hf8c457e_1001
  setuptools             anaconda::setuptools-39.0.1-py36_0 --> conda-forge::setuptools-41.0.1-py27_0
  sqlite                         pkgs/free::sqlite-3.13.0-0 --> conda-forge::sqlite-3.26.0-h67949de_1001
  tk                                 pkgs/free::tk-8.5.18-0 --> conda-forge::tk-8.6.9-h84994c4_1001
  wheel                      pkgs/free::wheel-0.29.0-py36_0 --> conda-forge::wheel-0.33.3-py27_0
  zlib                     anaconda::zlib-1.2.11-ha838bed_2 --> conda-forge::zlib-1.2.11-h14c3975_1004

The following packages will be SUPERSEDED by a higher-priority channel:

  hdf4                     anaconda::hdf4-4.2.13-h3ca952b_2 --> conda-forge::hdf4-4.2.13-0
  pillow                     pkgs/free::pillow-4.0.0-py36_0 --> conda-forge::pillow-3.2.0-py27_1
  python                          pkgs/free::python-3.6.0-0 --> conda-forge::python-2.7.15-h721da81_1008

The following packages will be DOWNGRADED:

  qt                                                5.6.2-3 --> 4.8.7-2

Proceed ([y]/n)? y

Downloading and Extracting Packages
openssl-1.1.1b       | 4.0 MB    | ################################################################################################## | 100% 
libcurl-7.64.1       | 584 KB    | ################################################################################################## | 100% 
pillow-3.2.0         | 785 KB    | ################################################################################################## | 100% 
libnetcdf-4.4.1.1    | 2.0 MB    | ################################################################################################## | 100% 
krb5-1.16.3          | 1.4 MB    | ################################################################################################## | 100% 
readline-7.0         | 391 KB    | ################################################################################################## | 100% 
lzo-2.10             | 319 KB    | ################################################################################################## | 100% 
futures-3.2.0        | 24 KB     | ################################################################################################## | 100% 
python-2.7.15        | 12.8 MB   | ################################################################################################## | 100% 
libstdcxx-ng-8.2.0   | 2.9 MB    | ################################################################################################## | 100% 
hdf5-1.10.1          | 5.0 MB    | ################################################################################################## | 100% 
qt-4.8.7             | 34.1 MB   | ################################################################################################## | 100% 
libedit-3.1.20170329 | 172 KB    | ################################################################################################## | 100% 
curl-7.64.1          | 128 KB    | ################################################################################################## | 100% 
enum34-1.1.6         | 56 KB     | ################################################################################################## | 100% 
hdf4-4.2.13          | 969 KB    | ################################################################################################## | 100% 
zlib-1.2.11          | 101 KB    | ################################################################################################## | 100% 
imageio-2.5.0        | 3.4 MB    | ################################################################################################## | 100% 
tk-8.6.9             | 3.2 MB    | ################################################################################################## | 100% 
libgcc-ng-8.2.0      | 7.6 MB    | ################################################################################################## | 100% 
libssh2-1.8.2        | 257 KB    | ################################################################################################## | 100% 
ncurses-6.1          | 1.3 MB    | ################################################################################################## | 100% 
sqlite-3.26.0        | 1.9 MB    | ################################################################################################## | 100% 
certifi-2019.3.9     | 149 KB    | ################################################################################################## | 100% 
wheel-0.33.3         | 34 KB     | ################################################################################################## | 100% 
pip-19.1             | 1.8 MB    | ################################################################################################## | 100% 
numpy-1.14.2         | 4.0 MB    | ################################################################################################## | 100% 
setuptools-41.0.1    | 650 KB    | ################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
conda list
Traceback (most recent call last):
  File "/pf/b/b301034/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
```
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

I am not able to reproduce this, but I can copy a txt file of the commands in bin of the broken environment and the backup one. Would this help?
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by ZiQiangZhou** [comment]
have you fixed it?
i have also met this problem when i update my tensorflow with the commond 'conda update tensorflow', and now, i lost my conda.

**Comment by itarec1988** [comment]
Hi... No, I actually haven't managed to fix it. Fortunately, I had a backup of my base environment and so far I have been working on that one. However, that environment doesn't have the conda command working, so I am quite limited if I need to install a new package... I stopped looking for solutions, but I fear I will have to install the entire anaconda distribution again..

**Comment by ZiQiangZhou** [comment]
hi, thanks for your reply. I have fixed it. For my problem, when I update tensorflow, maybe the lasted tensorflow version needs python 3.7, so python 3.7 was installed by conda, and the PYTHONPATH was also set to python 3.7. However, there is no conda in python 3.7, so I lost conda. When I re-add python 3.6 to the PYTHONPATH, conda can work. Hope that can help you!
