### ISSUE TITLE
Existing environments.txt (from conda < 4.6.14) may be stored in a non-utf-8 locale meaning they fail to load

### ISSUE THREAD

**Issue by epogrebnyak** [conda/conda#8662]
I would like to update conda on Windows 64 to a newer version. My paths contain non-ascii characters.

I run the following command:

```D:\Anaconda3\Scripts\conda update conda```

The update fails with following bug report.

```
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3\python.exe
               CONDA_ROOT=D:\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Евгений
                     PATH=D:\Anaconda3\Library\bin;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3;C:\Use
                          rs\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3\Library\mingw-w64\bin;C:\Users\╨Х╨▓╨│
                          ╨╡╨╜╨╕╨╣\.julia\conda\3\Library\usr\bin;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia
                          \conda\3\Library\bin;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3\Scripts;C:
                          \Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3\bin;C:\tools\ruby26\bin;C:\Progra
                          m Files\Haskell\bin;C:\Program Files\Haskell
                          Platform\8.4.3\lib\extralibs\bin;C:\Program Files\Haskell
                          Platform\8.4.3\bin;C:\Program Files (x86)\Common Files\Oracle\Java\jav
                          apath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Window
                          s\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Python33;C:\Program
                          Files\doxygen\bin;C:\ProgramData\chocolatey\bin;C:\Program Files
                          (x86)\Cyberduck CLI\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System3
                          2\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files
                          (x86)\Skype\Phone\;C:\Program Files (x86)\Windows
                          Live\Shared;D:\Programs\julia\Julia-0.4.5\bin;C:\Program
                          Files\Amazon\AWSCLI\;C:\Program
                          Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;C:\Program
                          Files\nodejs\;D:\Programs\Go\bin;D:\Programs\Microsoft VS
                          Code\bin;C:\Program Files\Haskell Platform\8.4.3\mingw\bin;C:\Program
                          Files (x86)\Brackets\command;D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anac
                          onda3\Library\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
                          bem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\jav
                          apath;C:\Program Files\Intel\Intel(R) Manage;\bin;C:\Program Files\gre
                          tl;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\AppData\Local\Julia-1.0.2\bin;C:\Users\╨Х╨▓
                          ╨│╨╡╨╜╨╕╨╣\AppData\Local\hyper\app-2.0.0\resources\bin;C:\Users\╨Х╨▓╨│
                          ╨╡╨╜╨╕╨╣\AppData\Local\GitHubDesktop\bin;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\AppDa
                          ta\Roaming\npm;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\AppData\Local\Microsoft\Windows
                          Apps;C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\AppData\Local\atom\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
         PYTHONIOENCODING=1251
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3
    active env location : C:\Users\╨Х╨▓╨│╨╡╨╜╨╕╨╣\.julia\conda\3
            shell level : 1
       user config file : C:\Users\Евгений\.condarc
 populated config files : C:\Users\Евгений\.condarc
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.0.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\envs
                          C:\Users\Евгений\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.21.0 CPython/3.6.0 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

I see two problems:

```
 File "D:\Anaconda3\lib\site-packages\chardet\charsetgroupprober.py", line 28, in <module>
        from .enums import ProbingState
ModuleNotFoundError: No module named 'chardet.enums'
```

```
      File "D:\Anaconda3\lib\site-packages\pip\_internal\download.py", line 368, in <module>
        class PipSession(requests.Session):
    AttributeError: module 'pip._vendor.requests' has no attribute 'Session'
```

Maybe I should downgrade pip?

```
λ pip -V
pip 19.1 from d:\anaconda3\lib\site-packages\pip (python 3.6)
```

**Comment by WSLUser** [comment]
For me I have a similar issue. I have this when I run `
conda update --all --no-pin --no-channel-priority`:

`Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1291, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1006, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1050, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1061, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1116, in print_unexpected_error_report
    from .base.context import context
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\base\context.py", line 28, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\common\configuration.py", line 40, in <module>
    from .serialize import yaml_load
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\common\serialize.py", line 45, in <module>
    yaml.representer.RoundTripRepresenter.add_representer(odict, represent_ordereddict)
AttributeError: module 'ruamel_yaml' has no attribute 'representer'`

Still happens when I just follow same command as the OP.

**Comment by epogrebnyak** [comment]
I made a fresh installation of conda from the binaries, and the problem now resides with `UnicodeDecodeError`. 

```
λ conda update conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: D:\Anaconda3

  added / updated specs:
    - conda


The following packages will be UPDATED:

  conda                                       4.6.11-py37_0 --> 4.6.14-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'None'.
UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
Attempting to roll back.

Rolling back transaction: done

UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
```

My system information:

```

λ conda info

     active environment : None
       user config file : C:\Users\Евгений\.condarc
 populated config files : C:\Users\Евгений\.condarc
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\Евгений\.conda\pkgs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\Евгений\.conda\envs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by stevengj** [comment]
Likely related: #7023, #8111, #7806, #8432 — it seems like using either Python 2 or Python 3 with Conda encounters problems if the user's home directory is non-ASCII.

**Comment by mingwandroid** [comment]
Fixed in conda 4.16. Please try that version instead. Just install the latest miniconda on top PDF your existing installation, then update --all

**Comment by epogrebnyak** [comment]
@mingwandroid, latest miniconda for win64 is 4.6.14 - do you suggest this version?

**Comment by mingwandroid** [comment]
Yes

**Comment by mingwandroid** [comment]
Well done in finding the place to trot bugs. Twitter is *not* that place.

**Comment by epogrebnyak** [comment]
> Well done in finding the place to report bugs. Twitter is _not_ that place.

Sarcasm?

**Comment by mingwandroid** [comment]
No, completely genuine.

**Comment by mingwandroid** [comment]
It's not IMHO polite behavior and I'm rewarding it by helping you.

**Comment by epogrebnyak** [comment]
Unfortunately, newest Miniconda did not help, maybe there is some border case on my system, but I think there still something wrong with handling the non-ASCII paths. 

Easy check with conda 4.6.14 `conda info -a` as mentioned in https://github.com/conda/conda/issues/6955, still fails uinfortunately. 

Also ```conda update --all``` fails with UnicodeDecodeError

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: | DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\pythonw.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\pythonw.exe', 'D:\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\python.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\python.exe', 'D:\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\pythonw.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\pythonw.exe', 'D:\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\python.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\python.exe', 'D:\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'None'.
UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')
Attempting to roll back.

Rolling back transaction: done

UnicodeDecodeError('utf-8', b'D:\\Anaconda3\\envs\\mxme\r\nD:\\Anaconda3\\envs\\minimal\r\nD:\\Anaconda3\\envs\\xl_env\r\nD:\\Anaconda3\\envs\\maspider\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\fx_env\r\nC:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\Anaconda3\\envs\\kmates\r\nD:\\Anaconda3\\envs\\spa\r\n', 114, 115, 'invalid continuation byte')

```

**Comment by epogrebnyak** [comment]
> It's not IMHO polite behavior and I'm rewarding it by helping you.

The best reward for me could have been fixing the issue. The UnicodeDecodeError issue https://github.com/conda/conda/issues/6955 has been sitting around since Feb 2018. I realise you have a pipeline of things to fix, Linux > Windows, etc.

This particular issue is anything but closed (al least as for things happening my system).

Anything else I can politely do to make conda work on my poor `C:\\Users\\\xc5\xe2\xe3\xe5\xed\xe8\xe9\\` or I should retreat to WSL?

**Comment by mingwandroid** [comment]
> The best reward for me could have been fixing the issue

When asking for help use the correct forum. This is clearly that and you have managed to locate it. Posting replies to entirely unrelated promotional material on twitter is bad form.

I will try to see if there's anything wrong here but this stuff is fairly well tested these days. Just about all of conda's python 3 tests are done in deliberately tricky Unicode folders.

**Comment by epogrebnyak** [comment]
> I will try to see if there's anything wrong here but this stuff is fairly well tested these days. Just about all of conda's python 3 tests are done in deliberately tricky Unicode folders.

I'm reading that as "the problem does exist, our tests pass ok". Please, no.

**Comment by mingwandroid** [comment]
I'm aware what your end goal is, working software, and we share it, but the ends do not always justify the means. You'll find people happier to help if things are kept polite.

> I'm reading that as "the problem does not exist, our tests pass ok"

I have no idea why you would take that meaning considering the first sentence "I'll try to see if there's anything wrong here". I don't disclaim people's problems like that. I assume good faith and that you are being honest.

I wrote that to make it clear (clearly it didn't work) that conda is tested in the face of Unicode extensively. We can even build packages with Unicode in their names of we want to now. That doesn't mean there are no bugs, obviously.

**Comment by stevengj** [comment]
Maybe the error occurs only in a console that is set to the UTF-8 codepage or something like that?

**Comment by mingwandroid** [comment]
I do test it with Unicode yes. But there are so many variables to encoding on python that is hard to test every case. Still if I can get anything I can reproduce (clear steps please) I'll do my best. 

If you are interested in how to run condas test suite locally then I can help with that.

There's also the new utf8 system wide locale that's now in windows 10. People have started to use it but I don't believe python 3 is ready for it yet.

Agree on keeping things pleasant! Cheers.

**Comment by mingwandroid** [comment]
Here is an example of a recipe that we use to test Unicode. The environments created during this build contain a heart symbol as does the package name and a binary in the package. This binary also emits a heart symbol. We test here that all of this works. I believe it works on Windows too.

**Comment by WSLUser** [comment]
I really didn't need this spam....but for me at least, following advice to overwrite install with fresh download of latest miniconda3 allows conda to complete the update process instead of immediately failing as shown above though it is extremely slow. If you could optimize the fix for performance somehow or improve elsewhere in conda, that would be appreciated. Maybe just one time thing but we'll see. So my issue was slightly different since it works albeit slowly.

**Comment by epogrebnyak** [comment]
I can open a separate issue, as @WSLUser original problem is looks solved, but it seems the problem is somewhere how [compat.py](https://github.com/conda/conda/blob/078fb4e541fa7c0921d321c58d7bda0725089484/conda/common/compat.py) works on overloading the `io.open` function.

I experimented with console codepages as @stevengj suggested, but to no effect, then tried to isolate where is the `conda info -a` fails (#6955). 

The error originates when `yield_lines()` tries to read a text configuration file ```C:\\Users\\Евгений\\.conda\\environments.txt```, but the error is not the filepaths, but the file content. 

https://github.com/conda/conda/blob/078fb4e541fa7c0921d321c58d7bda0725089484/conda/gateways/disk/read.py#L42-L63

`environments.txt` has non-ASCII characters:

```
D:\Anaconda3\envs\mxme
D:\Anaconda3\envs\minimal
D:\Anaconda3\envs\xl_env
D:\Anaconda3\envs\maspider
C:\Users\Евгений\Anaconda3\envs\fx_env
C:\Users\Евгений\Anaconda3\envs\kmates
D:\Anaconda3\envs\spa
```

I made a little replication and could spot the file read error:

```
from errno import ENOENT
from compat import open
#from io import open

PATH = "C:\\Users\\Евгений\\.conda\\environments.txt"

def yield_lines(path):
    """Generator function for lines in file.  Empty generator if path does not exist.
    Args:
        path (str): path to file
    Returns:
        iterator: each line in file, not starting with '#'
    """
    try:
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                yield line
    except (IOError, OSError) as e:
        if e.errno == ENOENT:
            pass
        else:
            raise
            
for line in yield_lines(PATH):
    print (line)
    

#  File "D:\Anaconda3\lib\codecs.py", line 322, in decode
#    (result, consumed) = self._buffer_decode(data, self.errors, final)

#UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 114: invalid continuation byte    
```

So, the standard library `open()`  workd well on `environments.txt`, but the overloaded function does not:

https://github.com/conda/conda/blob/078fb4e541fa7c0921d321c58d7bda0725089484/conda/common/compat.py#L170-L177

**Comment by epogrebnyak** [comment]
> I have no idea why you would take that meaning considering the first sentence "I'll try to see if there's anything wrong here". I don't disclaim people's problems like that.

On the basis that you marked this issue as closed.

**Comment by stevengj** [comment]
Ah, it looks like https://github.com/conda/conda/blob/95e80f1487f3cc72bd57137af09377290fa2db64/conda/core/envs_manager.py file creates the `environments.txt` using `open` with the default encoding, which apparently [defaults to Windows-1252](https://stackoverflow.com/questions/36303919/python-3-0-open-default-encoding) in many Windows versions.    So maybe the fix is to change envs_manager.py to call `open(..., encoding="utf-8")`.

**Comment by stevengj** [comment]
@epogrebnyak, is it possible that you have an `environments.txt` file in your `"C:\\Users\\Евгений\\.conda\\environments.txt"` directory that is leftover from an old conda version?  Maybe try deleting "C:\\Users\\Евгений\\.conda" and re-installing?

**Comment by mingwandroid** [comment]
> Shortly, io.open("enviroments.txt", encoding="utf-8") gives me UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 114: invalid continuation byte while io.open("enviroments.txt") makes no error and reads the configuration file

You have a broken environments.txt file. It may be that an old `conda` used a Cyrillic codepage, but now conda in less insane and uses 'utf-8' explicitly everywhere. Either using something like `iconv` to convert your `environments.txt` or just delete it. This is probably something we could've tried to handle, but the switch to 'utf-8' only took ages and we had to get it out, still this was something I had in the back of my head but dimissed as "I will just have to tell people to convert them".

IMHO `environments.txt` is a misfeature in `conda` and I will start proposing we remove it for the junk that it is (a *global* collection of conda environments even though each one could require a different conda to mange it?!).

**Comment by mingwandroid** [comment]
This bug was closed on the basis that latest conda does unicode a lot better and the bug tracker is a record of the bugs in the current codeebase of conda.

Thinking about whether I can fix this, it would be tricky. I suppose I could write something that tries to load it using your defaultlocaleencoding() when utf-8 fails.

I will re-open though (and re-title the bug).

**Comment by stevengj** [comment]
@mingwandroid, is there an an environment variable or a command-line switch or something that can tell Conda to ignore `environments.txt`?   Julia installs its own "private" miniconda installation and we don't want to use the global `environments.txt`.

**Comment by mingwandroid** [comment]
@setvengj, no not at present, pinging @msarahan and @kalefranz so they're aware I'm not a lone voice (actually I would like to propose we remove *all* globalization of conda too including *conda init* but, baby steps)

**Comment by epogrebnyak** [comment]
+1 for `iconv`! Converting `environments.txt` to utf-8 now helped to avoid `UnicodeDecodeError`. Also installing  conda-4.6.14 from Miniconda over Anaconda was not needed (gives some package inconsistency messages), 4.6.11 from the Anaconda distribution works.

**Comment by mingwandroid** [comment]
> installing conda-4.6.14 from Miniconda over Anaconda was not needed (gives some package inconsistency messages

I really encourage you to *not* ignore those errors and to *not* use old condas.

**Comment by epogrebnyak** [comment]
> It may be that an old `conda` used a Cyrillic codepage, but now conda in less insane and uses 'utf-8' explicitly everywhere. 

Likely `locale.getpreferredencoding()` encoding was used.

**Comment by mingwandroid** [comment]
To be clear here: you converted the file to utf-8 then downgraded to a conda that doesn't support Unicode nearly as well at all (actually this one has some of the Unicode fixes but far from all of them).

I really encourage sticking to 4.6.14, it should be the most robust conda for ages and fixes some serious bugs (ok, mainly on Windows) that have existed since 4.6.0.

I've spent a bit too long helping you now so I have to move onto other things.

**Comment by mingwandroid** [comment]
One final link: https://github.com/conda/conda/issues/8490

**Comment by epogrebnyak** [comment]
> To be clear here: you converted the file to utf-8 then downgraded to a conda that doesn't support Unicode nearly as well at all (actually this one has some of the Unicode fixes but far from all of them).

I followed your advice to drop in Miniconda  4.6.14 into existing Anaconda installation, the side-effect was the package inconsistency, similar to https://github.com/conda/conda/issues/8490. 

After fixing `environments.txt` I reinstalled 4.6.11 and updated to 4.6.14. `UnicodeDecodeError` is gone in either version, so is package inconsistency.

> I really encourage sticking to 4.6.14, it should be the most robust conda for ages and fixes some serious bugs (ok, mainly on Windows) that have existed since 4.6.0.

Maybe 4.6.14 should be a part of the Windows distribution at <https://www.anaconda.com/distribution>
then. So far it based on 4.6.11 yet. 

> I've spent a bit too long helping you now so I have to move onto other things.

Actually, none of your advice addressed a particular problem I had with `environment.txt`. For the solution I had to go to conda internals myself, review how `os.open()` works and isolate the issue.

Most of your messages concerned demands to be polite on Twitter, advocacy for how good your test suite is and that 4.6.14 is a really good version of conda (sure is). For me it seemed you wanted to show there is no problem, rather than geniunely helping and caring about a border case.   

I also find your parenting, mentoring tone and attitude (including 'I really encourage you to not ignore those errors and to not use old condas.`) very unpleasant to deal with. 

You are welcome to keep the issue closed or open, depending your procedures.

**Comment by mingwandroid** [comment]
I am sorry you misinterpreted these things. Good luck!

**Comment by epogrebnyak** [comment]
Thanks for dealing with this!

**Comment by jjhelmus** [comment]
> so is package inconsistency

The environment is likely still inconsistent, you just are not seeing the message when using an older conda.  If you add `-vv` to the install command you most likely will see that the environment is still inconsistent.  Fixing the inconsistency by re-installing the packages mentioned in the message is highly recommended.

**Comment by mingwandroid** [comment]
Just one thing "I really encourage you to not ignore those errors and to not use old condas" isn't in any way me trying to patronize you, those errors are really important and the old conda 4.6's arenpretty broken.

I only say this because it's my duty to inform our users to avoid problems (both now and future ones - the inconsistency one can become a big problem AFAIK, but it's not my area of conda-expertise, ironically, that would be Unicode handling!)

**Comment by epogrebnyak** [comment]
It is a generally good advice, but it came in a bit of a moment of helplessness, which made me upset. Thanks again for helping and making conda better.

**Comment by mingwandroid** [comment]
Yes, I understand. I could've been more welcoming too, but the initial intro got us on a bad foot here.

Without meaning to sound too "parenting" again :-), I hope I can give some maybe useful tips:

1. Use `Miniconda` rather than `Anaconda`. The big one is great for an introduction, but `Miniconda` workflows tend to be a lot more light-weight and efficient (and therefore mutable, sharable and iterable).
2. It might be good to get into the habit of exporting your environments (if you practice envs) every so often and reinstalling them into brand new installations to test that they continue to work and so you get the chance to do some testing before committing. Conda has support for this or you could just script something.

This is definitely a bug though, a fix would require a fall back that tests various other encodings like we discussed. If you are interested in a PR to conda, this could be a good first issue to tackle.

**Comment by epogrebnyak** [comment]
I think Windows users are attached to Anaconda because it gives you 'here is everything you need' feeling, but indeed looking from environments perspective Miniconda is more lightweight.

As for PR - what is a link to familiarise with a testing process? I can produce an `environments.txt` temp file of different encodings, replicating my case or similar.

**Comment by mingwandroid** [comment]
If you clone this repo, you could check CONTRIBUTING.Basically you run dev\start.bat (with some args).

Tests should be added to tests/core/test_envs_manager.py I think.

One way that I would prefer is that when we detect envionrments.txt in the legacy codepage, we convert it to utf-8 (maybe with a warning?) and save it out again so that the problem is corrected at souce.

We're "OK" from an IDE perspective. By that, I mean when I hack on conda I generally use an IDE for dev, debugging and testing (as well as CLI testing) and I switch between PyCharm and VSCode every few months fixing IDE-related issues as I find them in conda. You might have some luck with them.

Cheers.
