### ISSUE TITLE
fish: cannot create environment. cannot send report about issue

### ISSUE THREAD

**Issue by baloe** [conda/conda#8664]
### Steps to Reproduce

I just now installed the most recent miniconda (4.6.14) to a directory named `/soft/conda/`:

```
bash Miniconda3-latest-Linux-x86_64.sh -b -p /soft/conda
```

I use fish, but running `/soft/conda/bin/conda init fish` does not function as reported [here](https://github.com/conda/conda/issues/8590#issuecomment-491865533).

So instead I activate conda via these commands:
```
set -gx PATH $PATH /soft/conda/bin/
source (conda info --root)/etc/fish/conf.d/conda.fish
conda activate root
```
This appears to work fine. I can launch `python`, `conda list` works, and `(base)` is indicated in the terminal. 

Next I tried to create a new environment :
```
> conda create --name pers                                                                                                                                                              (base) 
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/loehrer/.conda/envs/pers



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pers
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
but I can't activate it:
```
> conda activate pers
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/soft/conda/lib/python3.7/site-packages/conda/cli/main.py", line 138, in main
        return activator_main()
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 955, in main
        print(activator.execute(), end='')
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 180, in execute
        return getattr(self, self.command)()
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 154, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 285, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 342, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "/soft/conda/lib/python3.7/site-packages/conda/activate.py", line 569, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /soft/conda/bin/conda shell.fish activate pers`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=/soft/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/soft/conda/bin/python
               CONDA_ROOT=/soft/conda
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
           MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
                     PATH=/soft/conda/bin:/soft/conda/condabin:/home/loehrer/bin:/home/loehrer/.
                          local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                          :/usr/games:/usr/local/games:/snap/bin:/soft/conda/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /soft/conda
            shell level : 1
       user config file : /home/loehrer/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /soft/conda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /soft/conda/pkgs
                          /home/loehrer/.conda/pkgs
       envs directories : /home/loehrer/.conda/envs
                          /soft/conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-48-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:: command not found
- (line 1): begin; [y/N]:  
                   ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 74 of file /soft/conda/etc/fish/conf.d/conda.fish

in function “conda”
	called on standard input
	with parameter list “activate pers”
```

## Expected Behavior

A new envornment named  `pers` should be created.
I should have been given the chance to type y+Enter to actually file the report instead of seeing
```
Would you like conda to send this report to the core maintainers?

[y/N]:: command not found
- (line 1): begin; [y/N]:  
                   ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /soft/conda
            shell level : 1
       user config file : /home/loehrer/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /soft/conda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /soft/conda/pkgs
                          /home/loehrer/.conda/pkgs
       envs directories : /home/loehrer/.conda/envs
                          /soft/conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-48-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

(None)
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /soft/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.2           py37h2e261b9_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.14                   py37_0    defaults
cryptography              2.6.1            py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pip                       19.0.3                   py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.3                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                41.0.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults

```
</p></details>

**Comment by calebho** [comment]
+1 for this
<details>
<summary>Here's what I get:</summary>
calebho@Calebs-MacBook-Pro ~> conda activate spie                                                                                                  (base)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 138, in main
        return activator_main()
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 996, in main
        print(activator.execute(), end='')
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 180, in execute
        return getattr(self, self.command)()
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 154, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 288, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 345, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "/miniconda3/lib/python3.7/site-packages/conda/activate.py", line 574, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /miniconda3/bin/conda shell.fish activate spie`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/miniconda3/bin/python
               CONDA_ROOT=/miniconda3
              CONDA_SHLVL=1
                     PATH=/miniconda3/bin:/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr
                          /sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:.:/miniconda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /miniconda3
            shell level : 1
       user config file : /Users/calebho/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /miniconda3/pkgs
                          /Users/calebho/.conda/pkgs
       envs directories : /miniconda3/envs
                          /Users/calebho/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?



No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


fish: Unknown command '[y/N]:'
- (line 1):
begin; [y/N]:
       ^
from sourcing file -
	called on line 61 of file /usr/local/Cellar/fish/3.0.2/share/fish/functions/eval.fish

in function 'eval'
	called on line 140 of file -

in function 'conda'
	called on standard input
	with parameter list 'activate spie'

calebho@Calebs-MacBook-Pro ~>
</details>

**Comment by calebho** [comment]
Ah I removed this line from `~/.config/fish/fish.config` and the error disappeared
```
set -gx PATH $PATH /miniconda3/bin
```

**Comment by jordansamuels** [comment]
@calebho thanks for that trick, that is exactly what fixed it for me.

**Comment by LinxiFan** [comment]
You can also run `conda init fish`, which will patch your fish config file. Re-launch the shell and everything works. No need to manually add lines to the fish config.

**Comment by stianlagstad** [comment]
I had the same error initially. What I did:
1. Install conda
2. Manually change my `~/.config/fish/config.fish` file to add conda to the path (adding `~/miniconda3/bin/` to the path)
3. Try running `conda init fish`

But I shouldn't have changed my `fish.config` file manually. What worked:
1. Install conda
2. Run ´~/miniconda/bin/conda init fish`. This changed my `~/.config/fish/config.fish` and added this:'
    ```
    # >>> conda initialize >>>
    # !! Contents within this block are managed by 'conda init' !!
    eval /home/stian/miniconda3/bin/conda "shell.fish" "hook" $argv | source
    # <<< conda initialize <<<
    ```

And now things seem to work :)

**Comment by baloe** [comment]
Yes, running `conda init fish` works fine and it indeed adds the following line to `~/.config/fish/config.fish`:

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /soft/conda/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<
```

And this woks fine in Ubuntu 18.04. For some reason however, this line simply has no effect in Ubuntu 16.04.

**Comment by nilanjanray** [comment]
Is this an issue specific to Ubuntu-20? since the below if of ```conda info```

```
  active environment : base
    active env location : /root/conda
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.4
    conda-build version : 3.20.1
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.31
       base environment : /root/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Linux/4.4.0-145-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
and unable to deactivate/activate conda within fish , after executing ```conda init fish```
