### ISSUE TITLE
Conda breaks installation when updating on computer 

### ISSUE THREAD

**Issue by vascotenner** [conda/conda#8669]
## Current Behavior

I tried to update the conda packages on a machine running low on memory:

```
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::param-1.9.0-py_0'.
OSError(12, 'Cannot allocate memory')
Attempting to roll back.

Rolling back transaction: done

[Errno 12] Cannot allocate memory
```
The installation process stopped because there was not sufficient memory. However, this broke the conda installation, my `conda/bin/directory` is empty  now

### Steps to Reproduce

```

```
Update conda  (conda install conda) on a machine with almost no free memory.

## Expected Behavior

This is a more tricky one, but damaging the whole conda installation is quite annoying.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
conda  4.6.2-py36_0 
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by mingwandroid** [comment]
There's no possible way to fix this sorry.
