### ISSUE TITLE
Add conda env to be packaged into a single zip file

### ISSUE THREAD

**Issue by arita37** [conda/conda#8673]
For backup purpose or re-deployment, it would be useful 
to be able to zip all of an conda env into a single zip file
and re-deploy from this zile file.

We can physically (file based) freeze an environnment and re-deploy.
Sometimes, we have air-gap, no access to internet for conda install...

This is very handy features...

**Comment by msarahan** [comment]
Please see conda-pack: github.com/conda/conda-pack
