### ISSUE TITLE
Not an upgrade is not a downgrade

### ISSUE THREAD

**Issue by scopatz** [conda/conda#8676]
This is more of a weird lingustic corner case, but I noticed the following:

```
$ conda install python=3.7
....
The following packages will be UPDATED:

  ipykernel                         5.1.0-py36h24bf2e0_1002 --> 5.1.1-py37h24bf2e0_0
  python                                3.6.7-hd21baee_1002 --> 3.7.1-hd21baee_1001
  requests                                 2.21.0-py36_1000 --> 2.22.0-py37_0

The following packages will be DOWNGRADED:

  absl-py                                      0.7.1-py36_0 --> 0.7.1-py37_0
  asciinema                                 2.0.2-py36_1000 --> 2.0.2-py37_1000
....
```

It seems weird that packages with the same version number and build, but for a different (higher) version of Python are considered "downgraded".  It seems like maybe the right word here is "replaced"?

**Comment by jjhelmus** [comment]
The wording is poor here.  Anything [that does not fall into another update category](https://github.com/conda/conda/blob/4.6.14/conda/plan.py#L197-L208) is labeled as a downgrade by conda.  I think these types of package changes could be added to the `updated` label or be assigned to a new `replaced` label.
