### ISSUE TITLE
conda env export fails due to incorrect PyPI spec parsing

### ISSUE THREAD

**Issue by martinkou** [conda/conda#8687]
## Current Behavior
After upgrading from conda 4.5.x to conda 4.6.x, installing certain packages from PyPI would cause `conda env export` to fail.

e.g. this is seen with installing the `eth-keyfile` package from PyPI.

### Steps to Reproduce
```
$ conda create -n eth-test python==3.6.7
$ conda activate eth-test
$ pip install eth-keyfile==0.5.1
$ conda env export

InvalidVersionSpec: Invalid version '(<1.0.0,>=0.1.0': unable to convert to expression tree: ['(']
```

This is caused by the PyPI spec parser not being able to parse certain requirement strings in the eth-keyfile package. e.g. "eth-utils>=1.0.0-beta.1,<2.0.0". You can see some of the requirement strings here: https://github.com/ethereum/eth-keyfile/blob/v0.5.1/setup.py

In particular, the `parse_specification()` function fails at parsing the spec string above.

```
>>> from conda.common.pkg_formats.python import parse_specification
>>> spec = "eth-utils>=1.0.0-beta.1,<2.0.0"
>>> parse_specification(spec)
PySpec(name='eth-utils', extras=[], constraints='>=1.0.0', marker='', url='')
```

## Expected Behavior
conda 4.5.x was able to print out the environment dependencies correctly:

```
name: eth-test
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.1.1=py36_0
  - python=3.6.7=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cytoolz==0.9.0.1
    - eth-hash==0.2.0
    - eth-keyfile==0.5.1
    - eth-keys==0.2.2
    - eth-typing==2.1.0
    - eth-utils==1.6.0
    - pycryptodome==3.8.1
    - toolz==0.9.0
```

The constraints field from `parse_specification()`  should say ">=1.0.0-beta.1,<2.0.0", not ">=1.0.0".
```
>>> from conda.common.pkg_formats.python import parse_specification
>>> spec = "eth-utils>=1.0.0-beta.1,<2.0.0"
>>> parse_specification(spec)
PySpec(name='eth-utils', extras=[], constraints='>=1.0.0-beta.1,<2.0.0', marker='', url='')
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : eth-test
    active env location : /home/martin_kou/anaconda3/envs/eth-test
            shell level : 3
       user config file : /home/martin_kou/.condarc
 populated config files : /home/martin_kou/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /home/martin_kou/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/martin_kou/anaconda3/pkgs
                          /home/martin_kou/.conda/pkgs
       envs directories : /home/martin_kou/anaconda3/envs
                          /home/martin_kou/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-50-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/martin_kou/.condarc <==
pip_interop_enabled: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/martin_kou/anaconda3/envs/eth-test:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py36_0    defaults
cytoolz                   0.9.0.1                  pypi_0    pypi
eth-hash                  0.2.0                    pypi_0    pypi
eth-keyfile               0.5.1                    pypi_0    pypi
eth-keys                  0.2.2                    pypi_0    pypi
eth-typing                2.1.0                    pypi_0    pypi
eth-utils                 1.6.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pip                       19.1.1                   py36_0    defaults
pycryptodome              3.8.1                    pypi_0    pypi
python                    3.6.7                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py36_0    defaults
sqlite                    3.28.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.9.0                    pypi_0    pypi
wheel                     0.33.4                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by musoke** [comment]
I just ran into the same issue with another package.  Downgrading conda to 4.5.12 made the problem go away for now.

**Comment by martinkou** [comment]
I've tested conda 4.7.1 after the #8688 merge. It's working now. Closing this issue.

Thanks for the help.

**Comment by jaekyeom** [comment]
@martinkou I'm using conda 4.7.12 on Ubuntu 16.04.4, but this is still a problem to me. It complains about `>=1<2` ( [https://github.com/locuslab/qpth/blob/master/setup.py](https://github.com/locuslab/qpth/blob/master/setup.py) ).

**Comment by jj-ookla** [comment]
> @martinkou I'm using conda 4.7.12 on Ubuntu 16.04.4, but this is still a problem to me. It complains about `>=1<2` ( https://github.com/locuslab/qpth/blob/master/setup.py ).

Same here. Using conda 4.7.11 on MacOS 10.14.4

**Comment by santina** [comment]
@jj-ookla  Try 
```
conda config --set pip_interop_enabled True
```
It helps me in this case. 
[Source](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/pip-interoperability.html)

**Comment by titaneric** [comment]
Same, the problem seems to be existing.
I'm using conda 4.7.12 on archlinux with LSB version 1.4

**Comment by rconjaerts** [comment]
I've got a similar issue:
InvalidVersionSpec: Invalid version '1.0<2': invalid character(s)

I'm using conda 4.7.12 on macOS Catalina

**Comment by anujdutt9** [comment]
I am getting the same error:
```
InvalidVersionSpec: Invalid version '1.0<2': invalid character(s)
```
I am using conda 4.7.12 on Windows 10.

**Comment by santina** [comment]
This is what I did to get around it. 

Like the OP said it's because of conda cannot parse some requirement file.

Go to where your packages live `/Users/<your_username>/opt/anaconda3/envs/<your_environment_name>/lib/python3.7/site-packages` 

search for that version string `grep -r "1.0<2"  .` 

Then you'll find out which package(s) is causing the issue. I was able to export the environment after uninstalling it.

**Comment by anujdutt9** [comment]
Thanks. That worked 👍 
But I now have an error creating the environment from the "env.yaml" file.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by tomliptrot** [comment]
I'm getting this as well 
`InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: [u'(']`

**Comment by JDFagan** [comment]
Still a problem for me as well after `pip install apache-airflow` (version 1.10.7) and then attempting `conda env export`:

`InvalidVersionSpec: Invalid version '1.1.1<2': invalid character(s)`

I'm using conda 4.8.1 on macOS Mojave 10.14.6

**Comment by BAFurtado** [comment]
Me too. On Conda 4.8.2 Windows 10. Clearly a problem reading the file.

**Comment by jinyeom** [comment]
We were having the same issue, and I was digging around quite a bit, and realized the package that was having the issue had a missing comma in the dependency list in `setup.py` (therefore concatenating two strings in the list together with a newline). If anybody is still having this issue, I'm fairly confident after all the digging that there's no issue with `conda-env`, and you should check your package's `setup.py` file.

**Comment by jj-ookla** [comment]
> We were having the same issue, and I was digging around quite a bit, and realized the package that was having the issue had a missing comma in the dependency list in `setup.py` (therefore concatenating two strings in the list together with a newline). If anybody is still having this issue, I'm fairly confident after all the digging that there's no issue with `conda-env`, and you should check your package's `setup.py` file.
> 
> Although, it seems that it's not the case for the original issue at the top. 🤔

@jinyeom  This was definitely the case in my issue. Thanks! 

https://github.com/apache/airflow/blob/1.10.10/setup.py#L197-L198

**Comment by jzf2101** [comment]
This is also seen in #9624. I also have the same issue.

**Comment by cpoptic** [comment]
As @santina alluded, this bug is due to the `METADATA` file in each library folder under your environment's `site-packages` folder containing a package dependency version specification such as `(>=`

if you run a `grep -r` in the `site-packages` directory for the offending string in your error message, you'll probably find it in several of these metadata files.
For example:   `METADATA:Requires-Dist:  scikit-learn (>=0.21.3)`

Unfortunately it's hard to fix, because each library in your `site-libraries` directory probably has one of these metadata files associated with it, and each of these files has a version conditional, which is breaking the `conda env export` command.  So that's what's happening.  Not sure how to fix.

**Comment by Abimael-DP** [comment]
> This is what I did to get around it.
> 
> Like the OP said it's because of conda cannot parse some requirement file.
> 
> Go to where your packages live `/Users/<your_username>/opt/anaconda3/envs/<your_environment_name>/lib/python3.7/site-packages`
> 
> search for that version string `grep -r "1.0<2" .`
> 
> Then you'll find out which package(s) is causing the issue. I was able to export the environment after uninstalling it.

############################################################################

... I did what you recommend but without uninstalling the package.

I edited the file from this:
Requires-Dist: grpcio (>=1.0<2)

to  this: 
Requires-Dist: grpcio (>=1.0, <2)

and then it let me create a .yml (typing: conda env export | grep -v "^prefix: " > tf2.yml) 
file which look like this:

name: my_enviroment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - grpcio=1.27.2=py37hf8bcb03_0

Still, I am not sure if changue  (>=1.0<2) to  (>=1.0, <2) is the right choice but it seems it worked.

**Comment by MikulasZelinka** [comment]
Here's how you could implement the fix mentioned by @abimael-dominguez:

```
grep -rl "1\.0<2" /opt/conda/envs/<your_conda_env>/lib/python3.7/site-packages | xargs sed -i 's/1.0<2/1.0, <2/g'
```

**Comment by MikulasZelinka** [comment]
By the way, the culprit (at least in my case) was tensorflow serving:
```
tensorflow_serving_api-2.4.1.dist-info/METADATA:Requires-Dist: grpcio (>=1.0<2)
```

And the problem should already be fixed on their side: https://github.com/tensorflow/serving/commit/b9ed0f80852d7a33b0745833ff9c0243178b0c5d.
