### ISSUE TITLE
resume download for big packages

### ISSUE THREAD

**Issue by abdo1819** [conda/conda#8695]
I am trying to set up an environment for [pytorch](https://pytorch.org) in my machine with cuda support using 
`conda install pytorch -c pytorch` 
the package size quiet big for my conection speed (100 KB/s)
```
pytorch-1.1.0              |py3.7_cuda10.0.130_cudnn7.5.1_0       455.0 MB  
```
when ever i download it pass about 40% or something similar then the download stops with error
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://anaconda.org/pytorch/pytorch/1.1.0/download/linux-64/pytorch-1.1.0-py3.7_cuda10.0.130_cudnn7.5.1_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

if I run the command again for installing the package it start over form zero 

so it would be great if you support download resuming like that in apt 

**I tried to download it manually  and fixing the dependency but this result another error when downloading another package that depend in it (`torchvision`), conda will redownload the whole package from higher priority mirror `pytorch` instead of using my local version**
```
 The following packages will be SUPERSEDED by a higher-priority channel:

  pytorch            <unknown>/linux-64::pytorch-1.1.0-py3.7~ --> pytorch/linux-64::pytorch-1.1.0-py3.7_cuda10.0.130_cudnn7.5.1_0
```

**Comment by crvio** [comment]
this would be super helpful for those of us with slow connections

**Comment by msarahan** [comment]
This is a good idea.  We don't have resources to work on it right now, but we would welcome a community contribution.

**Comment by DonFlymoor** [comment]
I would like to see download resume support in conda, as I can only download 100MB before the download fails.

**Comment by el-g-1** [comment]
I'll take a look.
