### ISSUE TITLE
Cannot install old noarch packages with conda 4.7.0

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#8701]
## Current Behavior
Packages that use `noarch_python: 'True'` fail to install with conda 4.7.0. 

### Steps to Reproduce
Run commands such as:
`conda create statusbar -n TestEnv1 -c https://conda.anaconda.org/gwforg`
`conda create statusbar -n TestEnv2 -c https://conda.anaconda.org/mailund`

You will see an error like this (CONDA_ROOT being wherever conda is installed):

```
LinkError: pre-link script failed for package gwforg::statusbar-0.1.4-py_0
running your command again with `-v` will provide additional information
location of failed script: CONDA_ROOT\pkgs\statusbar-0.1.4-py_0\Scripts\.statusbar-pre-link.bat
```

Running if verbose mode, you'll see output like this:

```
DEBUG conda.core.link:run_script(1128): for gwforg::statusbar-0.1.4-py_0 at CONDA_ROOT\envs\TestEnv1, executing script: $ C:\WINDOWS\system32\cmd.exe /d /c CONDA_ROOT\pkgs\statusbar-0.1.4-py_0\Scripts\.statusbar-pre-link.bat
DEBUG conda.gateways.subprocess:subprocess_call(69): executing>> C:\WINDOWS\system32\cmd.exe /d /c CONDA_ROOT\pkgs\statusbar-0.1.4-py_0\Scripts\.statusbar-pre-link.bat
INFO conda.gateways.subprocess:subprocess_call(83): $ C:\WINDOWS\system32\cmd.exe /d /c CONDA_ROOT\pkgs\statusbar-0.1.4-py_0\Scripts\.statusbar-pre-link.bat
==> cwd: CONDA_ROOT\pkgs\statusbar-0.1.4-py_0\Scripts <==
==> exit code: 1 <==
==> stdout <==

==> stderr <==
'"CONDA_ROOT\envs\TestEnv1\python.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

## Expected Behavior
The packages should be installed successfully, as they are with conda 4.6.14.

## Environment Information
```
     active environment : None
 populated config files :
          conda version : 4.7.0
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       virtual packages :
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
               platform : win-64
             user-agent : conda/4.7.0 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.15063
          administrator : False
           offline mode : False
```

**Comment by msarahan** [comment]
Yep. We'll fix this as time allows.

**Comment by msarahan** [comment]
To clarify, the problem is that the verification and execution steps each run their parts in parallel now (via concurrent.futures).  This breaks the pre-link script that the noarch stuff depends on, because that pre-link script depends on having python already installed in the target env.  That's a pretty crappy, limiting assumption.

I think the fix here will be a way to limit the parallelism to restore the old serial behavior.  I definitely don't want to get into special-casing old-style noarch so that it gets pulled into its own separate category of execution.

**Comment by gjforte** [comment]
This is marked https://github.com/conda/conda/labels/priority-low, but it has broken compatibility with a large subset of existing conda pkgs.  Also, conda-build still produces packages with "unsolicited" pre-link scripts, given the "right" settings in a meta.yaml.  So one can successfully build a package, which includes a pre-link script unbeknownst to the builder, and _may_ (or may not) fail to install in the test phase (or later).

Currently the only workarounds seem to be:
- don't upgrade to conda 4.7 (or later).
- don't use (or build) any packages that have pre-link scripts ... which practically speaking can only be determined by trial and error.
- always pre-install python (and/or any other dependencies required by pre-link scripts that might be in packages you want) before installing the packages that you determined by trial and error were problematic.

This seems like it deserves a higher priority - at the very least, some clearer indication that the pre-link script itself is the cause of the problem, not some other factor, would be very helpful.
