### ISSUE TITLE
Packages with mkl support

### ISSUE THREAD

**Issue by szs8** [conda/conda#8704]
Hi, It seems that with version 4.6.14, conda does not install mkl optimized versions of certain libs like numpy, scipy, sklearn. What is the recommended way to install optimized packages now? I would love to contribute to an updated doc somewhere. Thanks!

**Comment by msarahan** [comment]
need more details.  What OS?  What's the output of ``conda info`` and ``conda list`` as the issue template requested from you?

The MKL stuff is still the default, but you may be installing something from somewhere else that forces a particular blas implementation.
