### ISSUE TITLE
unknown build names for the conda search command

### ISSUE THREAD

**Issue by d3netxer** [conda/conda#8714]
This is a question related to the output of a conda search command. This commands outputs the available Names, Versions, Builds, and Channels of a package. However it is unknown what the Build names represent and cannot be found in the documentation. Build names such as py27_0, py34_1, py36_1, seem to infer the Python version. However what do the following Build names mean? py_0, py_1, py_2?

**Comment by mingwandroid** [comment]
the bit after the _ is the build number. py27 does == python 2.7. py on its own means "noarch python" which is a feature of conda that allows us to re-use the same packages across Python versions and OSes.

**Comment by memory-yancy** [comment]
@d3netxer  Maybe you should see https://conda.io/projects/conda-build/en/latest/concepts/package-naming-conv.html to know about conda package name conventions, and learn about `meta.yaml`. Then, something will be distinct for you

And, it also support 7 characters of the hash
