### ISSUE TITLE
MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content

### ISSUE THREAD

**Issue by alexmil2019** [conda/conda#8724]
I installed conda version 4.6.14 on mac os sierra.
it gives the error "MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content" when I try to install a package.

I solved it by removing conda using 
https://stackoverflow.com/questions/42182706/how-to-uninstall-anaconda-completely-from-macos

and  installing another version using
 conda install conda=4.5.1

**Comment by msarahan** [comment]
This was caused by a temporary problem in our metadata, not by the conda version.  You can update conda safely.
