### ISSUE TITLE
`conda install --download-only` skips download if extracted content in cache

### ISSUE THREAD

**Issue by wshanks** [conda/conda#8731]
## Current Behavior
If a package's extracted content is present in the package cache, `conda install --download-only` will not download the package tarball.

### Steps to Reproduce
```
conda create -n test0
conda install -n test0 xz=5.2.4=h14c3975_4
conda clean --tarballs
conda create -n test1
conda install -n test1 --download-only xz=5.2.4=h14c3975_4
```

## Expected Behavior
The steps to reproduce should end up with xz-5.2.4-h14c3975_4.tar.bz2 in the conda package cache but they do not. I believe the package is skipped because the extracted version is still in the cache. Sometimes it is useful to have the tarball in the cache for copying to other systems. I think `--download-only` should ensure the tarball is present in the cache.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /home/user/conda
            shell level : 2
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /home/user/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/conda/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/conda/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/5.0.16-200.fc29.x86_64 fedora/29 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</p></details>

**Comment by jgornowich** [comment]
I know this is a really old issue, but I too could benefit from this behavior.  Is there a way to somehow get the package install process to preserve the *tar.bz2 files that are pulled.  

Maybe there is an alternate process to accomplish what I could use this for, I need to be able to copy these and install them to a newly installed environment in off line mode.  I can't setup any kind of local channel or repo in this case either.
