### ISSUE TITLE
Show packages that the user has requested

### ISSUE THREAD

**Issue by quartox** [conda/conda#8735]
The `History(prefix).get_requested_specs_map()` can get all the packages that the user has requested, but this isn't available in `conda.api` or `conda.exports`. I would like to use this functionality, so would it make sense to add it to one of these modules?

One idea is to add a method to `conda.api.PrefixData` but this does not mirror a method in `conda.core.prefix_data.PrefixData`. Could also just be a function in `conda.exports`, but that module seems cluttered already. I am happy to do this work if I can get some direction (or maybe this is a bad idea and we should just close this issue).

**Comment by kalefranz** [comment]
That history.py file is much older than prefix_data.py. I agree that it makes sense for that logic to move to the newer location. In the process though the quality of the code and tests could both use some serious beefing up.

**Comment by quartox** [comment]
Are you saying the logic from `History.get_user_requests` and `History.get_requested_specs_map` should move to `prefix_data.PrefixData` (instead of these methods simply being re-used by `PrefixData`)?
