### ISSUE TITLE
Add python variant built for macOS version 10.9 or above

### ISSUE THREAD

**Issue by wonjoonSeol** [conda/conda#8753]
The compiler standard library defaults to either `libstdc++` or `libc++`, depending on the targetted macOS version - `libstdc++` for 10.8 and below, and `libc++` for 10.9 and above. This is determined by the environment variable `MACOSX_DEPLOYMENT_TARGET` or the compiler option`-mmacosx-version-min`, defaulting to the system version otherwise.

When `distuils` builds extensions on macOS, it sets`MACOSX_DEPLOYMENT_TARGET` to the version that python was compiled with, even if the host system / Xcode is newer.

Recent macOS versions of python have a 64-bit only variant built for 10.9 (python.org), and a universal 64/32-bit variant built for 10.6 (python.org) or 10.7 (conda). I am running the conda universal variant, so `distutils` targets macOS 10.7, despite my system being 10.14, with Xcode 10 which doesn't install `libstdc++`. 

Source : [https://github.com/pandas-dev/pandas/issues/23424#event-1936508189](https://github.com/pandas-dev/pandas/issues/23424#event-1936508189)

Please add python variant built for macOS version 10.9 above so it could use libc++ instead of libstdc++ which is now deprecated.

**Comment by mingwandroid** [comment]
I am sorry we cannot possibly support such old systems and in my opinion no one should run them if they are hooked up to the internet.

**Comment by msarahan** [comment]
I'm confused. I think he's asking for the newer, not the older. I think that's what we have, though. I don't understand what's going wrong here.

**Comment by mingwandroid** [comment]
Yes this is very confusing and the original comment isn't, as far as I can tell, original.

**Comment by mingwandroid** [comment]
.. and it's also full of dubious facts.

**Comment by wonjoonSeol** [comment]
Hi,

> I'm confused. I think he's asking for the newer, not the older. I think that's what we have, though. I don't understand what's going wrong here.

Thanks for prompt reply.

<img width="520" alt="Screenshot 2019-06-04 at 18 52 37" src="https://user-images.githubusercontent.com/22602022/58903563-a7b4c280-86fd-11e9-9463-45abb268e80a.png">

kindly check the image above and the related issues here:: https://github.com/conda-forge/conda-forge.github.io/issues/183
and https://github.com/python/cpython/pull/5448

**Comment by mingwandroid** [comment]
@wonjoonSeol can we take a step back here and describe what it is that you are trying to do? Posting links to *very old* and *very fixed* bugs doesn't really help.

What do you enter into your shell and what goes wrong? Also, you are reporting bugs against the Intel Distribution for Python here and this is the `conda` bug-tracker. I will get this moved to `anaconda-issues`, but I still do not have the slightest clue about what the issue is.

Please explain it to me like I am a keen-to-learn 7 year old!
