### ISSUE TITLE
Way to detect if conda has been initialized?

### ISSUE THREAD

**Issue by albertmichaelj** [conda/conda#8760]
I am a Mac OS user that also uses homebrew for package management. Brew suggests that you do not have any conda environments active when using the brew command, so I wrote a custom function that deactivates all conda environments before calling brew and reactivates them afterwards (see below).
```
brew () {
    # This function will remove anaconda from my path for the sake of the brew command
    OLD_PATH=$PATH
    PRE_BREW_CONDA_ENVS=()
    while [ ! "$CONDA_DEFAULT_ENV" = "" ]; do
        PRE_BREW_CONDA_ENVS+=($CONDA_DEFAULT_ENV)
        conda deactivate
    done
    command brew "$@"
    for (( idx=${#PRE_BREW_CONDA_ENVS[@]}-1 ; idx>=0 ; idx-- )) ; do
        conda activate ${PRE_BREW_CONDA_ENVS[idx]}
    done
    PATH=$OLD_PATH
}
```

This works fine. However, additionally, I have this next line in my .bashrc/.zshrc to get the brew prefix:
```
BREW_PREFIX=$(brew --prefix)
```
Which also works fine. However, if I start a shell, activate a conda environment, and then run something like `exec zsh` in order to restart the shell without forking (in order to reload something in my init scripts), I get the conda is not initialized warning. This is because the `exec zsh` function inherits the previous conda environments, so it has to deactivate them in order to run the `BREW_PREFIX` command, but I have not yet run the `eval "$__conda_setup"` line at the end of my `.zshrc`.

I've solved this problem by using `command brew` instead of just `brew`, but the better solution would be to add a check at the beginning of my custom `brew ()` function in order to see whether or not conda has actually been initialized. However, I cannot figure out why conda doesn't think it has been initialized. Since I'm "re-executing" the shell, all the same environmental variables are there from when I initialized conda the first time, so I can't figure out what is triggering conda to think it hasn't been initialized. Is there a way to check to see if conda has been initialized easily in this situation?

**Comment by albertmichaelj** [comment]
I think I've figured it out. Does conda think it hasn't been initialized if `conda` doesn't call the conda function? I.e., if I run `type -t conda` (at least in bash) and it returns `function`, then conda has been initialized. If it returns anything else, then conda has not been initialized. This explains why conda initialization doesn't survive the `exec zsh` command. Unless there is more to add, feel free to close this.

**Comment by soapy1** [comment]
Yep, I think the code you are looking for is here: https://github.com/conda/conda/blob/master/conda/cli/main.py#L133-L147

**Comment by kalefranz** [comment]
I would look to see if the `CONDA_SHLVL` environment variable is defined in the current process. If it is, conda has been initialized.
