### ISSUE TITLE
broken doc links

### ISSUE THREAD

**Issue by notestaff** [conda/conda#8764]
Googling for conda docs, the top hits link to pages like
https://conda.io/en/latest/user-guide/tasks/build-packages/link-scripts.html
which are broken links.

**Comment by soapy1** [comment]
There was some restructuring of the conda and conda-build docs. The link scripts and other package building related things have moved over to conda build docs. I think the page you are looking for is https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html
