### ISSUE TITLE
synchronize conda environments

### ISSUE THREAD

**Issue by allefeld** [conda/conda#8800]
This is a mix of a question and a feature request.

I do Python development and use conda on several machines. Python source files are synchronized between the machines using Seafile. Now, it would be neat if the conda environments could be synchronized as well.

I'm aware of
```
conda env export > environment.yml
conda env create -f environment.yml
```
and I can then synchronize `environment.yml` along with the Python code. But
- that's not automatic
- it cannot update an existing environment with changes, only create a new one
- if I forgot to export the environment on one machine, there's nothing I can do on another.

**Question:** If I simply synchronize the conda folder containing the environments (in my case `~/.conda`) between the machines using e.g. Seafile, will that work? System architecture, OS, etc. are the same (see below).

Even if it works, conda environments can become huge, synchronization can be slow, and cloud storage (while becoming cheaper) comes at a cost. Hence my

**Feature request:** Conda could continuously maintain an `environment.yml` file with all ongoing changes, and have an option to apply those changes on another machine.

All machines are amd64, Debian 9.9, conda 4.6.14 (installed via the deb-Package).

**Comment by allefeld** [comment]
Any news on this, or an answer to the question? I'm running into this problem again and again.

In the meantime I resorted to not using `conda install`, but to maintain hand-edited `.yml` file which is synchronized between machines, and to run `conda env update --file` on it every time I change it. But this still doesn't ensure that the environments on the different machines are in the same state. Right now I have the problem that one is using Python 3.8, while the other is stuck on 3.7.

I would really appreciate some guidance here?

**Comment by mingwandroid** [comment]
> This is a mix of a question and a feature request.
> 
> I do Python development and use conda on several machines. Python source files are synchronized between the machines using Seafile. Now, it would be neat if the conda environments could be synchronized as well.
> 
> I'm aware of
> ```
> conda env export > environment.yml
> conda env create -f environment.yml
> ```
> and I can then synchronize `environment.yml` along with the Python code. But
> - that's not automatic
> - it cannot update an existing environment with changes, only create a new one
> - if I forgot to export the environment on one machine, there's nothing I can do on another.
> 
> **Question:** If I simply synchronize the conda folder containing the environments (in my case `~/.conda`) between the machines using e.g. Seafile, will that work? System architecture, OS, etc. are the same (see below).
> 
> Even if it works, conda environments can become huge, synchronization can be slow, and cloud storage (while becoming cheaper) comes at a cost. Hence my
> 
> **Feature request:** Conda could continuously maintain an `environment.yml` file with all ongoing changes, and have an option to apply those changes on another machine.

This doesn't sound like something conda should do to me, no. Can't you setup a cron job to do this? That's how unix stuff works, cron is the most basic popular task scheduler, just make a cron job that runs conda every 5 minutes, or create a wrapper script or a shell alias around conda so that any operation on the env that mutates it causes recreation of the yml file.

**Comment by allefeld** [comment]
@mingwandroid, thanks for replying. You propose to run `conda env export > environment.yml` as a cron job?

And what about my question to use file synchronization?

I cannot believe no one else has this problem. How is this usually done, keeping environments in sync across machines?

**Comment by mingwandroid** [comment]
You would have a cron job on both sides. One to write the file to some shared location on the 'server' and one to read it and recreate the env on 'clients'.

If you don't want to use rsync, if you sync to the same absolute path the entire env using some other tool you should be fine. So long as the machines run the same major OS (at a modern enough version to be compatible with our packages) this should work out fine.


File syncing is *not* within the remit of a package manager. It's an orthogonal issue addressed by many other tools which can be used in conjuction with conda if you wish. We have at least two ways of saving and recreating envs within the ecosystem: constructor (which is used to make the official installers) and conda-pack which is probably more appropriate for your use case.

**Comment by DoubleChimera** [comment]
I had a similar problem. Perhaps this will help you also.
https://stackoverflow.com/questions/52038034/push-and-pull-my-conda-environment-using-git

**Comment by Actualization** [comment]
Coming from the Javascript and other communities it is wild to me that you wouldn't prioritize environment as code to automatically back the environment up.  For example, serverless functions on Amazon Web Services using their "SAM" tool and 3rd party services like the "serverless framework" go so far as to store anything you would need to deploy as code (files).  Deployment is out of scope for Conda but environment management seems to be in scope and other tools focused more solely on environment management such as YARN, NPM and Poetry include keeping the environment description files up to date.  I'm not sure why you would backup your code for a company using something like git and not always want to backup your environment to enable it to run.

With kindness and curiosity, is there a reason why you wouldn't want the environment to automatically save so the up to date code always has an up to date environment?

**Comment by FernandoAFOliveira** [comment]
I recently ran into the same problem. I need to work in the same GitHub repository on 3 different machines, all using conda, vs code, and GitHub, with Windows 11 as OS. It is weird that I can synchronize so many files and settings, but not the environments. As much as you try, when you create the environments one at a time, they always end up with some minor differences. 
Yes, I know I could export and import the environment, but that is not the same as synchronizing, besides the obvious hassle, installing a package in one environment does not automatically update the others. There is a loss of productivity here.
