### ISSUE TITLE
Multiple pip sections

### ISSUE THREAD

**Issue by marabout2015** [conda/conda#8815]
I would like to specify "--install-option" in a conda environment.yml for pip-installing a package, as can be done in pip requirements files. Unfortunately, specifying this on one line seems to make it apply to the entire set of packages specified in the pip section. So I would like to have multiple pip sections, each handled separately.

**Comment by msarahan** [comment]
insufficient information.

**Comment by marabout2015** [comment]
@msarahan I mistakenly pressed submit. Should I resubmit under a different ID?

**Comment by marabout2015** [comment]
An example:
name: MLHyperparameterTuningGpu
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.1
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - pip:
    - lightgbm==2.2.3 --install-option="--gpu"
  - pip:
    - prompt_toolkit==2.0.7
    - azure-cli==2.0.44
    - azureml-sdk[notebooks]
    - papermill==0.14.2
