### ISSUE TITLE
R cannot be installed with conda>=4.7

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda#8821]
Installing R in a fresh environment (using conda 4.7.5) is not possible due to:
```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/r/linux-64/_r-mutex-1.0.0-anacondar_1.conda'.
  download saved to: /opt/conda/pkgs/_r-mutex-1.0.0-anacondar_1.conda
  expected sha256: c88ec41a3c40d4d1a9071158f475f0523322151e7726d3b9636b04cb030869cc
  actual sha256: 72420ecf0b109a0b3ce245518e17cc9bd4c4adeeaa0c6e3e02a9214c2d4fcfa5
```

For more details, see ContinuumIO/anaconda-issues#11042

Not sure if this is an issue with the new metadata format...? @msarahan

**Comment by msarahan** [comment]
Looking into it.  We uploaded the converted packages yesterday, and conda 4.7 does prefer them.

**Comment by msarahan** [comment]
The mismatch is between the .tar.bz2 file and the .conda file.  The "expected sha256" here matches the .tar.bz2 file.  The "actual sha256" matches the .conda file.  There's a bug in our indexing software (conda-build).  We'll investigate.

**Comment by xwangqcom** [comment]
See the same issue with fresh conda installation:

ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/r/linux-64/_r-mutex-1.0.0-anacondar_1.conda'.
  download saved to: /home/jeffreywang/anaconda3new/pkgs/_r-mutex-1.0.0-anacondar_1.conda
  expected sha256: c88ec41a3c40d4d1a9071158f475f0523322151e7726d3b9636b04cb030869cc
  actual sha256: 72420ecf0b109a0b3ce245518e17cc9bd4c4adeeaa0c6e3e02a9214c2d4fcfa5

Tried "conda install -c r _r-mutex ", but Conda still tried to overwrite:

The following packages will be SUPERSEDED by a higher-priority channel:

  _r-mutex                          r::_r-mutex-1.0.0-mro_2 --> pkgs/r::_r-mutex-1.0.0-anacondar_1

Also tried "conda --freeze-installed", but got the same error.

I am stuck now. Please help!
