### ISSUE TITLE
Wrong package size download with conda 4.7.5

### ISSUE THREAD

**Issue by pitrou** [conda/conda#8825]
With conda 4.6.14 this package size is downloaded:
https://travis-ci.org/pitrou/arrow/jobs/550709247#L781
With conda 4.7.5 the package download size is much smaller _for the same package version and build number_:
https://travis-ci.org/apache/arrow/jobs/550633121#L888

And it is correlated for the later build failure:
https://travis-ci.org/apache/arrow/jobs/550633121#L3351

**Comment by pitrou** [comment]
Here is a diff of the package plans:
https://gist.github.com/pitrou/15db86ca50d158133f063c66356b49c9

**Comment by pitrou** [comment]
@jjhelmus explained me that this is because of the new compression format. Good! But it seems the new package is corrupt here. Simply downgrading conda fixes our build failures with the _exact same package versions_.

**Comment by msarahan** [comment]
Yes, confirmed.  We'll look into why this package got corrupted, and try to write better verification tests into our procedures.

**Comment by H0R5E** [comment]
I might have the same problem with installing gitpython-2.1.11-py27_0

Using the `-vvv` option I am stuck at:

```
TRACE conda.core.path_actions:execute(1218): extracting C:\Anaconda\pkgs\gitpython
-2.1.11-py27_0.conda => C:\Anaconda\pkgs\gitpython-2.1.11-py27_0
DEBUG conda.gateways.disk.create:extract_tarball(209): extracting C:\Anaconda\pkgs
\gitpython-2.1.11-py27_0.conda
  to C:\Anaconda\pkgs\gitpython-2.1.11-py27_0
```

Looking in the `pkg` folder there is some files, but not the complete package. Without the `-vvv` option it is just stuck at 80 something percent on the progress bar.

I can't downgrade to 4.6.14. I get an AssertionError. Grrrrr.

```
> conda info

     active environment : None
       user config file : C:\Users\Work\.condarc
 populated config files :
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 2.7.16.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda\pkgs
                          C:\Users\Work\.conda\pkgs
                          C:\Users\Work\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda\envs
                          C:\Users\Work\.conda\envs
                          C:\Users\Work\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/2.7.16 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by glemaitre** [comment]
I got the same with `scikit-learn=0.21.2`, `python=3.6.8`, and `conda=4.7.5`. All `csv` files got corrupted.
