### ISSUE TITLE
build dependencies for an environment

### ISSUE THREAD

**Issue by adrinjalali** [conda/conda#8826]
This is related to #7090 and https://github.com/conda/conda-build/issues/2791

The background is that we were thinking of having an environment file which would make it easier for our contributors (scikit-learn) to setup an environment. The main issues we encountered were the compiler across platforms and MPI. We saw that people had a hard time setting up their environments across platforms to be able to build the backage.

The recipe file allows you to specify which languages you need, and it tries to find the right compiler, and you can set certain packages to be used from the conda environment and not the system.

One way to approach the problem, is to enable those features in the environment file, instead of trying to figure that out from the recipe, which as mentioned in https://github.com/conda/conda-build/issues/2791#issuecomment-377358431 is hard to generalize. This way the maintainers can write a better more general conda environment file that can be used by contributors, and in the CI.

Ideally, I'd like to be able to do something like:

```bash
conda env create -f environment.yml
pip install -e .
```

And have something like the following in the environment file:

```yaml
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - mpi
```

**Comment by msarahan** [comment]
Have you seen this: https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/debugging.html

I think that might be what you're looking for.  You'll still need to run the `pip install -e .` manually, and there's no good way to have dev versions of more than one thing at a time, but hopefully this helps you get started.
