### ISSUE TITLE
conda 4.7.5 osx build error: error: "unknown type name '__m128i'; did you mean '__m128'"

### ISSUE THREAD

**Issue by looooo** [conda/conda#8829]
Building the freecad-feedstock on circleci for osx results in this build error:
```
In file included from ../src/Mod/Points/App/AppPointsPy.cpp:45:
In file included from ../src/Mod/Points/App/PointsAlgos.h:29:
In file included from $PREFIX/include/eigen3/Eigen/Core:198:
$BUILD_PREFIX/bin/../lib/clang/4.0.1/include/pmmintrin.h:45:19: error: unknown type name '__m128i'; did you mean '__m128'?
```
https://circleci.com/gh/looooo/freecad-feedstock/332?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Building the same feedstock two days earlier worked. Comparing the used packages result in this diff:

```
-conda                     4.6.14                   py37_0    conda-forge
-conda-build               3.18.4                   py37_0    conda-forge
+conda                     4.7.5                    py37_0    conda-forge
+conda-build               3.18.5                   py37_0    conda-forge
-conda-package-handling    1.3.9                    py37_0    conda-forge
+conda-package-handling    1.3.10                   py37_0    conda-forge
-soupsieve                 1.9.1                    py37_0    conda-forge
+soupsieve                 1.9.2                    py37_0    conda-forge
```

Reverting conda to version 4.6.* solves this issue:
https://github.com/looooo/freecad-feedstock/commit/e24bf2b3a4253f109091b1397aa76f2e72b31608
https://circleci.com/gh/looooo/freecad-feedstock/335?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jakirkham** [comment]
Can you try rebuilding? IIUC a new compiler package was published for macOS.

cc @jjhelmus

**Comment by looooo** [comment]
seems to work now:
https://circleci.com/gh/looooo/freecad-feedstock/336?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
