### ISSUE TITLE
Issue creating a conda env with a system level install that I do not own

### ISSUE THREAD

**Issue by blairjj** [conda/conda#8830]
Howdy,

I have Anaconda python installed under the account appman which owns the /app/python/blah directory.  Users can load the module and use it today without issue.  A user recently tried to create a conda env and was presented with the following:
[bj2348@altotest-c1 ~]$ conda create -y -n conda-env
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.20.1
         python version : 3.5.1.final.0
       requests version : 2.14.2
       root environment : /app/python/platform/x86-64/3.5.0  (read only)
    default environment : /app/python/platform/x86-64/3.5.0
       envs directories : /home/ebp/bj2348/.conda/envs
                          /app/python/platform/x86-64/3.5.0/envs
          package cache : /app/python/platform/x86-64/3.5.0/pkgs
                          /home/ebp/bj2348/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.5.1 Linux/3.10.0-862.14.4.el7.x86_64 Red Hat Enterprise Linux Server/7.5 glibc/2.17
                UID:GID : 54639:54639

`$ /app/python/platform/x86-64/3.5.0/bin/conda create -y -n conda-env`

    Traceback (most recent call last):
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/app/python/platform/x86-64/3.5.0/lib/python3.5/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/app/python/platform/x86-64/3.5.0/pkgs/cache/6846611e.json'

My first guess is that they don't have write permission to the ./3.5.0/pkgs/cache dir.  Is there something I am missing on how to redirect this to use their local home dir instead of the shared install dir that they dont own?

Thanks,

Jay

**Comment by rwanwork** [comment]
Hi Jay,

I know it's been 2 months so I'm not sure if you've already solved this problem.

You're a system administrator?  I was stuck on this for a bit today and was looking around and I think I figured out how to solve the problem for multi-user conda (i.e., many solutions I found on-line involved changing the owner of the Miniconda directory to the user).

For me (running as a normal user), conda tried to access the pkgs, envs, and conda-meta directory.

This is for conda version 4.7.11 and Python version 3.7.4 .  The user has to put this in their home directory's .condarc file:

-----
pkgs_dirs:
  - ~/.conda/pkgs/
envs_dirs:
  - ~/.conda/envs/
-----

This forces the packages and environment directories to look only at their home directories.  I'm not sure if putting the installation directory as the second option is a good thing.  You can consider it, but I got it working so I'm not going to play around anymore.  :-)

Next, in the installation directory (i.e., /opt/miniconda3/ for me), you need to change the permissions to 755, but only to the directories.  Lastly, for the directory /opt/miniconda3/conda-meta/, you need to change the files to 744.

This has worked for me (so far).  If you tried something else that works, feel free to let me know.  Good luck!
