### ISSUE TITLE
[4.7.5] Can't create an environment from a directory (DirectoryNotACondaEnvironmentError)

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8850]
I have an existing environment which may not have been "properly" created, but which nevertheless works if I activate it. It doesn't show up in `conda env list` though.

If I try and install a package into it I get the below error:
```
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: C:\Miniconda\envs\py-dev
```

It sounds straightforward to convert my working folder into something `conda` recognises as a *proper* environment, but following the instructions doesn't seem to work:
```
(base) C:\> conda create -p C:\Miniconda\envs\py-dev
WARNING: A directory already exists at the target location 'C:\Miniconda\envs\py-dev'
but it is not a conda environment.
Continue creating environment (y/[n])? y


CondaValueError: prefix already exists: C:\Miniconda\envs\py-dev

(base) C:\> conda env list
# conda environments:
#
base                  *  C:\Miniconda
```

How can I convert my environment into something `conda` recognises?

**Comment by dhirschfeld** [comment]
After looking at the code, the workaround is easy enough:
```
touch C:/Miniconda/envs/py-dev/conda-meta/history
```

...but it seem to me that the create command should do this itself (maybe if you specify `--force`)

**Comment by fonnesbeck** [comment]
Got this as well just now on 4.8.1

**Comment by dhirschfeld** [comment]
At least the workaround it easy enough (once you know) but it would be great if conda would Just Work in these situations

**Comment by navneethc** [comment]
I'm currently facing this issue in 4.8.1 as well. (Windows 10/Miniconda)

I created an environment specifying Python 3.8 only, but when I went to install the main library (PyTorch) it complained about a lot inconsistencies, so I decided to remove all the packages in the environment using `conda remove -n pytorch --all`. This removed all the packages as well as the environment from env list. When I tried to recreate the environment using the same name, I got the error as above. 

```
(base) C:\Users\Navneeth>conda create -n pytorch
WARNING: A directory already exists at the target location 'C:\Users\Navneeth\Miniconda3\envs\pytorch'
but it is not a conda environment.
Continue creating environment (y/[n])?


CondaSystemExit: Exiting.
```

**Comment by cmasenas** [comment]
This bit me too.  I had an existing history.bak file but history was missing.

**Comment by 1234madhav** [comment]
DirectoryNotACondaEnvironmentError ... i get this error and also it says create using 'conda create'
I have tried the code solution provided above using anaconda prompt but problem persists plz help me

**Comment by zkubin** [comment]
> After looking at the code, the workaround is easy enough:
> 
> ```
> touch C:/Miniconda/envs/py-dev/conda-meta/history
> ```
> 
> ...but it seem to me that the create command should do this itself (maybe if you specify `--force`)

I tried doing that and got: (base) C:\Users\moond>touch C:/Miniconda/envs/py-dev/conda-meta/history
'touch' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dhirschfeld** [comment]
`touch` is part of the unix tools. Just manually create the `history` file however works for you.

**Comment by zkubin** [comment]
I'm still trying to get spyder to work. Every time I open conda the spyder program is not installed. I click on it, and the warning I get says: DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
target directory: C:\Users\moond\anaconda3

but, then I do:

(base) C:\Users\moond>conda create spyder

CondaValueError: The target prefix is the base prefix. Aborting.

So, nothing happens. On the anaconda server I can't get it to open no matter what I do.

**Comment by dhirschfeld** [comment]
`conda create` will create an environment for you. Spyder should be included by default if you have `anaconda` installed. `conda list` will tell you what you have installed.

Assuming Spyder is installed it should be enough to just call it from the command line:
```
(base) C:\Users\moond>spyder
```

**Comment by Lancelof2019** [comment]
choose another path and use 'conda create --prefix=/xx/path  package_name' and after installation use source activate /xx/path
