### ISSUE TITLE
communication missing about compatibility of conda>=4.5 and `constructor`

### ISSUE THREAD

**Issue by newville** [conda/conda#8857]
There is poor coordination between `conda` and `constructor`.   See also
https://github.com/conda/constructor/issues/257

## Current Behavior

Constructor does not work well with conda>=4.5.13.    This is apparently known to some developers but not enunciated or acted upon by `conda` or by `constructor`. Some part of this was raised with https://github.com/conda/conda/issues/8479 and perhaps with https://github.com/conda/conda/pull/8759 and perhaps with other reports as well.   Some of those Issues have been closed, leading to unclear communication about the interaction of `conda` and `constructor`.  With `conda>4.6` the default in the latest Anaconda distribution and `conda>4.7` included in `conda update --all`, this leaves `constructor` broken by default, with no indication of this state and no information on how to correct it.

From outside the development teams, this behavior could be seen as consistent with `constructor` being unsupported.  Worse, it might be seen as indicating that the `conda` team has poor integration and testing practices and pushes changes that break their own downstream tools.  

It would be helpful to clarify this and why the default version of `conda` prevents `constructor` from working and whether this is intentional. 

### Steps to Reproduce

1. open issue about `constructor` not working
2. observer response of "use conda 4.5".

## Expected Behavior

Options would include:

a) `constructor` would depend a specific version of `conda`.
b) `constructor` would be included in the testing of `conda` and be kept in sync with changes to repo locations, repo formats, and so on. 
c) changes to `conda` would not break `constructor`. 

## Environment Information

conda >= 4.6

**Comment by AXGKl** [comment]
100% backing this. Constructor is perceived as an integral part of the conda ecosystem and a strong selling point of conda as such, versus alternative binary shipping formats, e.g. docker. We are currently rendered with a broken build pipeline for the first product we released in that format. Not very encouring to say the least - stuff like that is just not happening in alternative formats and the fact that there was not even communication, is hard to take.

**Comment by newville** [comment]
Almost 3 years later, I think nothing makes the point made in this issue about the poor communications and coordination between conda-based tools better than the fact that there were 0 responses from developers and that a GitHub bot proposes closing the issue due to a lack of activity.

**Comment by kenodegard** [comment]
@newville We apologize for the lack of communication. Recent changes have addressed this issue and `constructor>=3.0.1` supports `conda>=4.6`.

That being said, we agree that there has been a lack of communication across the `conda` org over the past few years. Changes were made in the past year at Anaconda to reformulate the `conda` development team and reenergize the community. This can be seen in the work on [`conda` governance](https://github.com/conda-incubator/governance) and continued work on defining a steering council to help keep all `conda` projects on track. We have made efforts to filter through our backlog of issues but have not been able to address as many as we'd like. We continue to look for opportunities to engage with the `conda` community, get their feedback, and make meaningful improvements. We appreciate your dedication to coming back and responding to this issue despite prior inactivity on our part.
