### ISSUE TITLE
conda 4.7 does not find a solution when installing two packages separately.

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda#8858]
When creating an environment with `libpysal` and then installing `geopandas`,

```shell
conda create --name TEST libpysal --yes
conda activate TEST
conda install geopandas --yes
```

`conda 4.7` returns `UnsatisfiableError` b/c it refuses to downgrade a `python` build number to get a version with `readline 7`.

This is probably an edge case that will go away once the `readline 8` migration on `conda-forge` is complete. But CIs will be broken every migration that touches a `python` dependency.

Note that creating the environment in a single go like: `conda create --name TEST libpysal geopandas --yes`, or downgrading to `conda 4.6` works as expected.

**Comment by ocefpaf** [comment]
While I understand that `conda 4.7` make it harder to downgrade the `python` version I guess that, b/c we are using build number to provide variants, a smaller build number is not a downgrade.

**Comment by jjhelmus** [comment]
I do not believe the issue here is with the Python dowgrade since the following works:
```
conda create -c conda-forge --name TEST libpysal --yes
source activate TEST
conda install -c conda-forge readline=7
```

**Comment by jjhelmus** [comment]
Odd, the following works as well:
```
conda create -c conda-forge --name TEST libpysal --yes
source activate TEST
conda install -c conda-forge readline=7 --yes
conda install -c conda-forge geopandas --yes
```

**Comment by ocefpaf** [comment]
Can you confirm that

```
conda create -c conda-forge --name TEST libpysal --yes
source activate TEST
conda install -c conda-forge geopandas --yes
```

works? I forgot to mention but I'm using `strict`.

**Comment by jjhelmus** [comment]
```
conda create -c conda-forge --name TEST libpysal --yes
source activate TEST
conda install -c conda-forge geopandas --yes
```
Does not work, I need to add `conda install -c conda-forge readline=7 --yes`  before the install of `geopandas`.   This command should not be required, conda should find the solution without it.

**Comment by msarahan** [comment]
I'll look into this.  The freezing is probably being a little aggressive.  A better way to say it is actually "the conflict finding is not working well enough" because conda tries to not freeze anything that has a conflict.

**Comment by msarahan** [comment]
conda on master doesn't show this problem anymore.  I don't understand why - I'm not sure that we've changed anything.  Perhaps the CF readline migration has just gotten far enough that it isn't an issue anymore?

**Comment by ocefpaf** [comment]
> Perhaps the CF readline migration has just gotten far enough that it isn't an issue anymore?

Yep. I was unable to reproduce it a few days ago with the current release of conda. The bug is still there, we just don't have an easy way to reproduce it :smile:

**Comment by jjhelmus** [comment]
I think this issue has to do with the change to using `FREEZE_INSTALLED` as the default for the solver's update handling in 4.7.  After the environment with `libpysal` is created those packages are frozen unless a conflict is found.  If certain packages are frozen the solver is unable to find a solution.

**Comment by jjhelmus** [comment]
Here is an example using some simple packages:

```
(base) ~$ conda --version
conda 4.7.5
(base) ~$ conda create -n test -c jjhelmus foobar qux -y --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/conda/envs/test

  added / updated specs:
    - foobar
    - qux


The following NEW packages will be INSTALLED:

  foobar             jjhelmus/linux-64::foobar-1.0-0
  libbar             jjhelmus/linux-64::libbar-1.0-0
  libfoo             jjhelmus/linux-64::libfoo-2.0-0
  qux                jjhelmus/linux-64::qux-2.0-0



DryRunExit: Dry run. Exiting.
(base) ~$ conda create -n test -c jjhelmus foobar -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/conda/envs/test

  added / updated specs:
    - foobar


The following NEW packages will be INSTALLED:

  foobar             jjhelmus/linux-64::foobar-2.0-0
  libbar             jjhelmus/linux-64::libbar-2.0-0
  libfoo             jjhelmus/linux-64::libfoo-2.0-0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ~$ conda install qux -c jjhelmus -n test
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - jjhelmus/linux-64::foobar==2.0=0
  - jjhelmus/linux-64::libbar==2.0=0
  - jjhelmus/linux-64::libfoo==2.0=0
  - qux
```

This issue here is that the `foobar` package already installed in the environment is frozen when installing  `qux` and therefore cannot be downgraded to version 1.0 which is needed for a solution.  Adding a fallback to the solver when satisfiability is not possible with FREEZE_INSTALL will address this problem.
