### ISSUE TITLE
 CondaUpgradeError: This environment has previously been operated on by a conda version that's newer than the conda currently being used. A newer version of conda is required.   target environment location: /home/hatem/anaconda3   current conda version: 4.5.12   minimum conda version: 4.7

### ISSUE THREAD

**Issue by hatemshawky4** [conda/conda#8872]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment]
You haven't provided any information here.  Please fill out the issue template.

**Comment by vtyroyal** [comment]
Hello everyone.
Please, I am facing the same problem while I'm trying to add conda packages.
Everytime I use the `conda` command, i face this prloblem:

Take a look at the ouput of this command:

> user@user-pc:~/anaconda3/bin$ conda install conda
> Solving environment: failed
> 
> CondaUpgradeError: This environment has previously been operated on by a conda version that's newer
> than the conda currently being used. A newer version of conda is required.
>   target environment location: /home/tchiozem/anaconda3
>   current conda version: 4.5.12
>   minimum conda version: 4.7


When trying the command : conda info

>  user@user-pc:~/anaconda3/bin$ conda info
>
>     active environment : None
>            shell level : 0
>       user config file : /home/user/.condarc
>  populated config files : /home/user/.condarc
>          conda version : 4.5.12
>    conda-build version : 3.17.8
>         python version : 3.7.3.final.0
>       base environment : /home/user/anaconda3  (writable)
>           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
>                          https://conda.anaconda.org/conda-forge/noarch
>                          https://repo.anaconda.com/pkgs/main/linux-64
>                          https://repo.anaconda.com/pkgs/main/noarch
>                          https://repo.anaconda.com/pkgs/free/linux-64
>                          https://repo.anaconda.com/pkgs/free/noarch
>                          https://repo.anaconda.com/pkgs/r/linux-64
>                          https://repo.anaconda.com/pkgs/r/noarch
>                          https://repo.anaconda.com/pkgs/pro/linux-64
>                          https://repo.anaconda.com/pkgs/pro/noarch
>          package cache : /home/user/anaconda3/pkgs
>                          /home/user/.conda/pkgs
>       envs directories : /home/user/anaconda3/envs
>                          /home/user/.conda/envs
>               platform : linux-64
>             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-47-generic ubuntu/18.04 glibc/2.27
>                UID:GID : 1000:1000
>             netrc file : None
>           offline mode : False


When trying the command : conda config --show-sources

>  user@user-pc:~/anaconda3/bin$ conda config --show-sources
>  ==> /home/user/.condarc <==
>  channels:
>  - conda-forge
>  - defaults


How can I solve the first problem and start using the conda command again?
Please, help me solve this issue.
Thank you.

**Comment by msarahan** [comment]
Please see https://github.com/conda/conda/issues/8080#issuecomment-453554327
