### ISSUE TITLE
Why not contain daal ?

### ISSUE THREAD

**Issue by leafonsword** [conda/conda#8877]
conda has compiled numpy、scipy、sk-learncontain with mkl(math kernel library) default  ，daal（Data Analytics Acceleration Library） is another intel lib for boosting data analysis，and it has open source edition，why not also compile scipy，sk-learn with daal default？

**Comment by msarahan** [comment]
The overall file size of the installer is a concern.  We may be able to include DAAL in a future release because our new file format has given us some headroom.  We collaborate with the Intel Python team, and we'll hope to have news for you soon.

**Comment by leafonsword** [comment]
@msarahan 
what's relationship of DAAL with  conda file size?
As I consider, conda installation is about conda itself, user just downlaod conda; if somebody want to install scipy,sk-learn these extra lib , then conda could install scipy,sk-learn with DAAL compiled~
