### ISSUE TITLE
Problem installing opencv of most of versions on anaconda

### ISSUE THREAD

**Issue by MohamadZohoori** [conda/conda#8878]
Hi,

I tried to install opencv from different versions. I read that in one of issues the problem was solved by:
conda install -c conda-forge opencv=3.2.0
But that didn't work for me.

The problem doesn't seem to be the version nor not using conda-forge.
Please help me find the real solution to the problem. 
Here are the details:

![1](https://user-images.githubusercontent.com/49280815/60756982-b272b800-a019-11e9-905c-c2a85da8538c.png)

**Comment by dwyoung** [comment]
I'm seeing the same error on the Mac (Mojave 10.14.5) version.

<img width="635" alt="Screen Shot 2019-07-10 at 7 39 15 PM" src="https://user-images.githubusercontent.com/11352113/61011914-735ea280-a34a-11e9-91fc-941c4d408338.png">

**Comment by MohamadZohoori** [comment]
installing python version 4 might solve your problem. It worked for me.
