### ISSUE TITLE
Conda does no longer show prompt in Powershell since Win 10 1903

### ISSUE THREAD

**Issue by dschreij** [conda/conda#8880]
## Current Behavior

I used to have a working conda installation that would nicely show the activated environment left of the Powershell prompt, e.g.
```
(myenv) PS >
```
but this stopped working since Windows 10 upgraded to version 1903.
The environment does get activated, but it no longer shows in the prompt. I guess this is because Windows moved around profile paths. When executing `$profile`, the location shows as
```
D:\Users\Me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

while conda init creates or alters

```
D:\Users\Me\Documents\WindowsPowerShell\profile.ps1
```
I copied the line
```
(& "C:\Users\dschr_000\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
```
to Microsoft.PowerShell_profile.ps1, and that makes the conda env prompt show again, but screws up all other settings that I have configured in that profile (e.g. showing the current Git repository if any, and printing the cwd).

### Steps to Reproduce

```
[In Powershell]
conda init powershell
conda create -n myEnv python
conda activate myEnv
```

## Expected Behavior

To see the activated environment in front of the prompt
```
(myEnv) PS >
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : C:\Users\dschr_000\.condarc
 populated config files : C:\Users\dschr_000\.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\dschr_000\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/cogsci/win-64
                          https://conda.anaconda.org/cogsci/noarch
                          https://conda.anaconda.org/dschreij/win-64
                          https://conda.anaconda.org/dschreij/noarch
          package cache : C:\Users\dschr_000\Miniconda3\pkgs
                          C:\Users\dschr_000\.conda\pkgs
                          C:\Users\dschr_000\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dschr_000\Miniconda3\envs
                          C:\Users\dschr_000\.conda\envs
                          C:\Users\dschr_000\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\dschr_000\.condarc <==
auto_activate_base: False
channels:
  - conda-forge
  - defaults
  - cogsci
  - dschreij
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
...
conda                     4.7.5                    py37_0    conda-forge
conda-build               3.18.6                   py37_0    conda-forge
conda-forge-pinning       2019.07.01                    0    conda-forge
conda-package-handling    1.3.10                   py37_0    conda-forge
conda-smithy              3.3.4                      py_0    conda-forge
conda-verify              3.1.1                 py37_1000    conda-forge
...
```
</p></details>

**Comment by dhirschfeld** [comment]
Does initing PowerShell using the `--system` flag help at all?

RE: messing up the prompts it *could* be an ordering thing (in which case the `--system` flag *may* help). To test that theory out you'll need to know the order PS profiles are loaded and where the other configuration is being set.
https://www.pdq.com/blog/powershell-profile-load-order/

**Comment by dschreij** [comment]
Sadly it doesn't. After executing `conda init powershell --system` I get to see:
```
> conda init powershell --system
... ommitted for brevity ...
no change     C:\Users\Me\Miniconda3\etc\profile.d\conda.csh
modified      C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
```
and the last profile.ps1 contains the standard:

```
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Users\Me\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion
```
These are the same contents as D:\Users\Me\Documents\WindowsPowerShell\profile.ps1

My `D:\Users\Me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` contains my custom Powershell config:

```
Set-Location D:\Users\Me

function subl { &"${Env:ProgramFiles}\Sublime Text 3\sublime_text.exe" $args }

function prompt {
  $origLastExitCode = $LASTEXITCODE
  Write-Host 'PS ' -ForegroundColor Darkcyan -nonewline
  Write-VcsStatus

  $maxPathLength = 80
  $curPath = $ExecutionContext.SessionState.Path.CurrentLocation.Path
  if ($curPath.Length -gt $maxPathLength) {
      $curPath = '...' + $curPath.SubString($curPath.Length - $maxPathLength + 3)
  }

  Write-Host $curPath -ForegroundColor White
  $LASTEXITCODE = $origLastExitCode
  "$('>' * ($nestedPromptLevel + 1)) "
}

# Enable git support
Import-Module posh-git
$global:GitPromptSettings.BeforeText = '['
$global:GitPromptSettings.AfterText  = '] '

# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```
Maybe the culprit is in there?

As per your linked article `profile | Select-Object *` outputs the following:

```
AllUsersAllHosts       : C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
AllUsersCurrentHost    : C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : D:\Users\Me\Documents\WindowsPowerShell\profile.ps1
CurrentUserCurrentHost : D:\Users\Me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```
Just to clarify, my Miniconda installation is indeed installed on the C:\ but I have moved all my documents and other big stuff over to a D: drive, so the paths are correct.

**Comment by dhirschfeld** [comment]
I think the conda initialize block has to come *after* the posh git import - IIRC doing it the other way doesn't work.

Since your posh-git import is in the last profile to get loaded that means that the conda initialize should be at the *end* of that file and not in a profile which will get loaded earlier.

FWIW it works for me:
![image](https://user-images.githubusercontent.com/881019/60928926-834a9800-a2f2-11e9-9a49-376331af5e80.png)

**Comment by dhirschfeld** [comment]
...though you're doing some other funky stuff with the prompt so YMMV.

`cmder` messes with the prompt too and [I couldn't get that to work](https://github.com/conda/conda/issues/8213). I haven't revisited since to check if that has been fixed though

**Comment by dschreij** [comment]
That actually did the trick! Placing the conda section after all the other instructions *and* removing the conda entry from the AllUsersAllHost profile fixed the problem. So my profile (CurrentUserCurrentHost) now looks like:

```
function subl { &"${Env:ProgramFiles}\Sublime Text 3\sublime_text.exe" $args }

function prompt {
  $origLastExitCode = $LASTEXITCODE
  Write-Host 'PS ' -ForegroundColor Darkcyan -nonewline
  Write-VcsStatus

  $maxPathLength = 80
  $curPath = $ExecutionContext.SessionState.Path.CurrentLocation.Path
  if ($curPath.Length -gt $maxPathLength) {
      $curPath = '...' + $curPath.SubString($curPath.Length - $maxPathLength + 3)
  }

  Write-Host $curPath -ForegroundColor White
  $LASTEXITCODE = $origLastExitCode
  "$('>' * ($nestedPromptLevel + 1)) "
}

# Enable git support
Import-Module posh-git
$global:GitPromptSettings.BeforeText = '['
$global:GitPromptSettings.AfterText  = '] '

# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}

#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Users\Me\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion

Set-Location D:\Users\Me
```
Thanks for looking into this! Any reason why `conda init` places the conda snippet at the top of the profile, and why it does this in CurrentUserAllHosts? Maybe my understanding of hosts is wrong, but I think if you install (Mini|Ana)conda in your home folder, thant conda only exists on that location on that specific machine (unless your home folder is roaming, but I rarely see this being the case for entire home folders). It seems way more appropriate to place a hardcoded path such as `C:\Users\Me\Miniconda3\Scripts\conda.exe`  in the CurrentUserCurrentHost profile.

**Comment by jdthorpe** [comment]
With the caveot that I'm not a PowerShell expert, I think this is due to [this line](https://github.com/conda/conda/blob/9584d79f978f5c319fa2e0252db07e866e796ffe/conda/shell/condabin/Conda.psm1#L269) which assigns the existing `prompt` function to a local variable which is out of scope in the replacement prompt function.   I changed it to: 

```powershell
    Rename-Item Function:\prompt global:CondaPromptBackup
```
and got my prompt back.  PS you can find this on your machine using:

```powershell
 echo "$Env:_CONDA_ROOT\shell\condabin\Conda.psm1"
````
