### ISSUE TITLE
Anaconda Prompt Access Denied: Missing Temp Files

### ISSUE THREAD

**Issue by RaufJavid** [conda/conda#8888]
Hi, I  have tried to launch Anaconda Prompt but it is giving me Error..Access Denied. Please find the attached ScreenShot as a Proof. I have also try to change TMP and TEMP but could not work.
![Errot](https://user-images.githubusercontent.com/21277031/60873877-83925700-a250-11e9-89c2-d63dd769e544.png)

**Comment by msarahan** [comment]
That's a bug in our space handling.  What version of conda is this?

**Comment by RaufJavid** [comment]
conda version : 4.6.11.PFA
![error2](https://user-images.githubusercontent.com/21277031/60894514-46dc5500-a27c-11e9-9934-c3f0fbe60282.png)

**Comment by msarahan** [comment]
Please update conda and try again

**Comment by RaufJavid** [comment]
Hi,
Respected Sir...I have updated conda using this command...But still, issue:
**conda update -n base -c defaults conda**

**Comment by RaufJavid** [comment]
I installed Anaconda again this morning (Anaconda3-2019.07-Windows-x86_64.exe) and this problem is still present when launching the anaconda prompt. I added the lines:
```
@REM Added by schuelaw, June 9, 2019 after clean install
@SET TMP=C:\CondaTmp
@REM Added by schuelaw, June 9, 2019 after clean install
@SET TEMP=C:\CondaTmp
```
to the file **[Anaconda root]\condabin\_conda_activate.bat** right after the comment:
`@REM This method will not work if %TMP% contains any spaces.
`
and created the folder "**C:\CondaTmp**".

This works perfectly...Issue Resolved.

**Comment by mingwandroid** [comment]
I am re-opening this. We need to use a temp dir without spaces I fear!

**Comment by mingwandroid** [comment]
.. but thank you for the workaround @RaufJavid, I'm sure others will find it helpful.

**Comment by RaufJavid** [comment]
Thanks, @mingwandroid...Yes, the issue is of spaces in the temp dir.

**Comment by kamosuela** [comment]
Yikes, has this been fixed? I ran into this issue trying to update my spyder and matplotlib on admin mode, and it broke everything. Would prefer not having to uninstall/reinstall Anaconda 3 but that might be my workaround for now?

**Comment by Akkarine** [comment]
conda update --prefix C:\Users\DmitryKriv\anaconda3 anaconda:

![image](https://user-images.githubusercontent.com/13115270/96914708-6372bf80-14b6-11eb-9198-b3b7eb186376.png)

**Comment by ayush7ad6** [comment]
> @REM Added by schuelaw, June 9, 2019 after clean install
> @SET TMP=C:\CondaTmp
> @REM Added by schuelaw, June 9, 2019 after clean install
> @SET TEMP=C:\CondaTmp

didn't work for me. Now showing, "failed to create process."
