### ISSUE TITLE
Forbid some python upgrades in the base env

### ISSUE THREAD

**Issue by dpryan79** [conda/conda#8894]
Many users have the unfortunate habit of running `conda install` in their root/base environment. While that works OK for a time, eventually they'll install something that will upgrade python (the most recent report I've seen caused an upgrade from 3.6 to 3.7), which will then completely bork `conda`, because python can't then find the conda module:

    $ conda
    Traceback (most recent call last):
     File "/home/some_user/anaconda3/bin/conda", line 12, in <module>
       from conda.cli import main
    ModuleNotFoundError: No module named 'conda'

Ideally `conda` could be made aware of the environment it's running in and simply forbid more than patch-level changes in python if it's in the root/base environment that aren't being invoked by `conda update conda`.

**Comment by jjhelmus** [comment]
As of conda 4.7.0, upgrades to Python beyond micro releases in any environment, including the base environment, are disallowed unless explicitly requested by the user.

**Comment by dpryan79** [comment]
Wonderful!
