### ISSUE TITLE
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by rohitsharma1415** [conda/conda#8903]
The following packages will be DOWNGRADED:

  anaconda                                   2019.03-py37_0 --> custom-py37_1

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.

**Comment by msarahan** [comment]
I'm closing this issue because you have not provided enough information.  Please open a new issue and fill out the issue template completely.

**Comment by pseudoGal** [comment]
I am needed to download Spacy. I have used following commands:


Install spacy in anaconda python

spaCy is a free open-source library for Natural Language Processing in Python
Step 1 : Install spacy

Run the below command in Anaconda Prompt (Run as administrator)

conda install -c conda-forge spacy


But somehow  compiler shows following issue:

> The following packages will be DOWNGRADED:
> 
> anaconda 2019.03-py37_0 --> custom-py37_1
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: done
> Verifying transaction: failed
> 
> RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
> conda's operating environment.



Run the below command in Anaconda Prompt (Run as administrator)..it worked for me. This command will resolve above conflict of verification failed.. And afterwards you can install whichever package you wish. I have received above error when I was installing Spacy.

conda update -n base -c defaults conda

If you want to install spacy afterwards use below commands:

Run the below command in Anaconda Prompt (Run as administrator)

conda install -c conda-forge spacy

**Comment by huynhthaihoa** [comment]
I even got the same error message "RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment." when I ran a command "conda update -n base -c defaults conda" in Anaconda Prompt (Run as adminstrator)

**Comment by thunguyen177** [comment]
I create a new enviroment and install in the new environment. It works

**Comment by minygd** [comment]
Hi, a simple `conda update --force conda` may fix this issue and go roll!
