### ISSUE TITLE
.condarc not well implemented ??

### ISSUE THREAD

**Issue by thomasdeneux** [conda/conda#8905]
Hello,

So, a weird issue i just encountered just after installing conda : 
I couldn't create env from anaconda prompt, the channel default wasn't found.

I edited my .condarc from
channels: [default]
ssl_verify: true

to 

ssl_verify: true
channels:
  -default

and it was good.

**Comment by jjhelmus** [comment]
`default` is not a valid channel.  The correct name is `defaults` with a "s".  This is likely the cause of this issue rather than the format of `.condarc`.
