### ISSUE TITLE
Avoid text "failed" when solving environment fails

### ISSUE THREAD

**Issue by mrocklin** [conda/conda#8906]
I recommend avoiding the term "failed" when we try `current_repodata.json` and then fall back to `repodata.json`.  I wonder if this might be better replaced with "failed.  Retrying" or something similar that says "we're going to try something else now instead"

```
(base) mrocklin@dgx15:~$ conda install cudatoolkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed    # <<<------ this might scare users
Collecting package metadata (repodata.json): done
Solving environment: /
```

Just a thought, please ignore if this isn't appropriate.

**Comment by msarahan** [comment]
user perception / UX is always appropriate.  Thanks for the feedback.
