### ISSUE TITLE
bad application CA Credential Manager

### ISSUE THREAD

**Issue by SandorSzalma1** [conda/conda#8913]
## Current Behavior
CA Credential Manager installs Gnome XML libraries into **C:\Windows\System32**:
- libxml2.dll
- iconv.dll
- pcre.dll
- zlib1.dll

https://docops.ca.com/ca-identity-manager/14-1/EN/third-party-software-acknowledgments
libxml2 v.2.6.27 (25.10.2006!!)

Because of this conda 4.7.x does not work.

### Steps to Reproduce
- on Windows install CA Credential Manager, Anaconda3 2019.03
- open anaconda prompt
- execute "conda update conda"
- execute "conda"

## Expected Behavior
conda still should work

## Environment Information
conda 4.6.8

## Our workaround
define environment variable 
CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1

**Comment by msarahan** [comment]
How is this an issue with conda?  The third party vendor putting stuff into System32 is at fault here.  Your workaround is your only recourse; we can't fix your third party vendor.

**Comment by mingwandroid** [comment]
Please, if you can, ask Broadcom not to do this.

**Comment by SandorSzalma1** [comment]
This is the way of the communication you recommend here:
https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html
If you find others, please let us know. If you're on this list and you want to fix things, let us know. 
In either case, the conda issue tracker at https://github.com/conda/conda/issues is the best way to reach us.
So you can out this application of the list with bad software.
My colleague will contact CA, too.

**Comment by msarahan** [comment]
My apologies. You are the first one to report things this way. The way that you filled out the issue template confused me. I think we might do better by having a dedicated issue template for this purpose.

Thanks for helping to improve the user experience.
