### ISSUE TITLE
Unable to update to the latest release

### ISSUE THREAD

**Issue by vipcxj** [conda/conda#8915]
The latest version with some very important but fix is 4.7.6. But after I type `sudo canda update canda`, Typing `canda --version` still show `4.7.5`. And the bug is still there, I am still not able to install python by canda.

**Comment by jjhelmus** [comment]
conda 4.7.6 has been tagged but packages are not yet available in the standard channels.  Please be patience, these will be available soon.

**Comment by vipcxj** [comment]
Is there a nonstandard way to update the conda to the latest version？

**Comment by msarahan** [comment]
We have an early release channel:

conda update -c conda-canary conda

**Comment by vipcxj** [comment]
> We have an early release channel:
> 
> conda update -c conda-canary conda

Thanks
