### ISSUE TITLE
Conda update is too slow - I've been waiting for > 5 mins

### ISSUE THREAD

**Issue by marivascruz** [conda/conda#8927]
(gp-estimation3) [mrivas@sh-109-55 /]$ conda update -n base -c defaults conda
hanging - taking over 10 minutes to get anything

**Comment by noragen** [comment]
try with 
```conda update -n base -c defaults conda -vvv```

and look at the output, maybe it hangs anywhere
you also should paste your

```conda --version```

**Comment by msarahan** [comment]
see also #7690 - if you need further help, please open a new issue using the "speed complaint" template and fill in as much as you can.  The more info you provide, the more anyone can do to help.
