### ISSUE TITLE
NoBaseEnvironmentError

### ISSUE THREAD

**Issue by Davidvandijcke** [conda/conda#8930]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

I am trying to update conda by running `conda update conda` but get the error:

`NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.
`
I tried installing an empty base environment by running `conda create --name myenv python`, but that didn't bring any luck. The same issue arises when I try to update conda from within anaconda-navigator. Thanks for the help.

**Comment by timsnyder** [comment]
@Davidvandijcke can you please add the output of `conda info` and `conda config --show-sources` ?  It is difficult to help without that information.  Thanks.

**Comment by msarahan** [comment]
Conda's base environment is the folder where you installed miniconda or anaconda.  This error message might indicate that you just don't have the base environment activated when you try to run `conda update conda`  You can activate that env with `conda activate` (no env argument) or `conda activate base`

**Comment by Marc-Ruebsam** [comment]
Hello,

- installed conda on my Centos7 VM
`$ sudo yum install conda`
- added the _envs_ and _pkgs_ path I would like to use (not needed for reproducing the error) (permission and ownership is set)
`$ conda config --add envs_dirs /opt/anaconda/envs
$ conda config --add pkgs_dirs /opt/anaconda/pkgs`
- reopened shell (just in case)
- trying to update conda (yes, should be up-to-date but anyway)
`$ conda update conda

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


$ conda activate
$ conda update conda

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.`

I'm sure this is due to the missing write permissions in the base environment (see conda info below) and I would love to create it somewhere else, but neither yum nor conda asks for a location. Is there a way around this, or do I have to install conda via the miniconda installer?

conda info **before** conda activate
`$ conda info

     active environment : None
            shell level : 0
       user config file : /home/bq_mruebsam/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /home/bq_mruebsam/.condarc
          conda version : 4.6.13
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /var/cache/conda/pkgs
                          /home/bq_mruebsam/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/bq_mruebsam/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.6.13 requests/2.12.5 CPython/3.6.8 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 4363:2071
             netrc file : None
           offline mode : False`

conda info **after** conda activate
`$ conda info

     active environment : base
    active env location : /usr
            shell level : 1
       user config file : /home/bq_mruebsam/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /home/bq_mruebsam/.condarc
          conda version : 4.6.13
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /var/cache/conda/pkgs
                          /home/bq_mruebsam/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/bq_mruebsam/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.6.13 requests/2.12.5 CPython/3.6.8 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 4363:2071
             netrc file : None
           offline mode : False`

conda config --show-sources
`$ conda config --show-sources
==> /usr/share/conda/condarc.d/defaults.yaml <==
pkgs_dirs:
  - /var/cache/conda/pkgs
  - ~/.conda/pkgs

==> /home/bq_mruebsam/.condarc <==
envs_dirs:
  - /opt/anaconda/envs
pkgs_dirs:
  - /opt/anaconda/pkgs`

I hope this alignes with the OPs problem. Creating environments works, but are (of cause) not used as base and conda is (of cause) not installed in them.

Best

P.S.: I think conda create would try to override my /usr folder:
`$ conda create
WARNING: A directory already exists at the target location '/usr'
but it is not a conda environment.
Continue creating environment (y/[n])?`

**Comment by Marc-Ruebsam** [comment]
update:

when I install miniconda via the installer
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh ## installed to /opt/miniconda/miniconda3
```
things work just fine. The environment gets created in /opt/miniconda/miniconda3 where permissions are set correctly. Even spares me from having to set envs_dir and pkgs_dirs.

However, I would still prefer to install my conda via a package manager ...and being able to choose the location of the base environment.

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/bq_mruebsam/.condarc
 populated config files :
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/miniconda/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda/miniconda3/pkgs
                          /home/bq_mruebsam/.conda/pkgs
       envs directories : /opt/miniconda/miniconda3/envs
                          /home/bq_mruebsam/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 4363:2071
             netrc file : None
           offline mode : False
```

**Comment by Crear12** [comment]
> Hello,
> 
> * installed conda on my Centos7 VM
>   `$ sudo yum install conda`
> * added the _envs_ and _pkgs_ path I would like to use (not needed for reproducing the error and are the only entries in the .condarc) (permission and ownership is set)
>   `$ conda config --add envs_dirs /opt/anaconda/envs`
>   `$ conda config --add pkgs_dirs /opt/anaconda/pkgs`
> * reopened shell (just in case)
> * trying to update conda (yes, should be up-to-date but anyway)
> 
> ```
> $ conda update conda
> 
> NoBaseEnvironmentError: This conda installation has no default base environment. Use
> 'conda create' to create new environments and 'conda activate' to
> activate environments.
> 
> $ conda activate
> $ conda update conda
> 
> NoBaseEnvironmentError: This conda installation has no default base environment. Use
> 'conda create' to create new environments and 'conda activate' to
> activate environments.
> ```
> 
> I'm sure this is due to the missing write permissions in the base environment (see conda info below) and I would love to create it somewhere else, but neither yum nor conda asks for a location. Is there a way around this, or do I have to install conda via the miniconda installer?
> 
> conda info **before** conda activate
> 
> ```
> $ conda info
> 
>      active environment : None
>             shell level : 0
>        user config file : /home/bq_mruebsam/.condarc
>  populated config files : /usr/share/conda/condarc.d/defaults.yaml
>                           /home/bq_mruebsam/.condarc
>           conda version : 4.6.13
>     conda-build version : not installed
>          python version : 3.6.8.final.0
>        base environment : /usr  (read only)
>            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /opt/anaconda/pkgs
>                           /var/cache/conda/pkgs
>                           /home/bq_mruebsam/.conda/pkgs
>        envs directories : /opt/anaconda/envs
>                           /home/bq_mruebsam/.conda/envs
>                           /usr/envs
>                platform : linux-64
>              user-agent : conda/4.6.13 requests/2.12.5 CPython/3.6.8 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.7.1908 glibc/2.17
>                 UID:GID : 4363:2071
>              netrc file : None
>            offline mode : False
> ```
> 
> conda info **after** conda activate
> 
> ```
> $ conda info
> 
>      active environment : base
>     active env location : /usr
>             shell level : 1
>        user config file : /home/bq_mruebsam/.condarc
>  populated config files : /usr/share/conda/condarc.d/defaults.yaml
>                           /home/bq_mruebsam/.condarc
>           conda version : 4.6.13
>     conda-build version : not installed
>          python version : 3.6.8.final.0
>        base environment : /usr  (read only)
>            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /opt/anaconda/pkgs
>                           /var/cache/conda/pkgs
>                           /home/bq_mruebsam/.conda/pkgs
>        envs directories : /opt/anaconda/envs
>                           /home/bq_mruebsam/.conda/envs
>                           /usr/envs
>                platform : linux-64
>              user-agent : conda/4.6.13 requests/2.12.5 CPython/3.6.8 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.7.1908 glibc/2.17
>                 UID:GID : 4363:2071
>              netrc file : None
>            offline mode : False
> ```
> 
> conda config --show-sources
> 
> ```
> $ conda config --show-sources
> ==> /usr/share/conda/condarc.d/defaults.yaml <==
> pkgs_dirs:
>   - /var/cache/conda/pkgs
>   - ~/.conda/pkgs
> 
> ==> /home/bq_mruebsam/.condarc <==
> envs_dirs:
>   - /opt/anaconda/envs
> pkgs_dirs:
>   - /opt/anaconda/pkgs
> ```
> 
> I hope this alignes with the OPs problem. Creating environments works, but are (of cause) not used as base and conda is (of cause) not installed in them.
> 
> Best
> 
> P.S.: I think conda create would try to override my /usr folder:
> 
> ```
> $ conda create
> WARNING: A directory already exists at the target location '/usr'
> but it is not a conda environment.
> Continue creating environment (y/[n])?
> ```

I'm having the same problem on Mac OS. Activate function doesn't work, other operations will show me this error info. Is there any solution that I can make it workable rather than reinstall the whole conda?

**Comment by puiseux** [comment]
## Current Behavior

my system is macos Catalina (version 10.15.2 (19C57))
`conda`, `anaconda2` were both working fine, with three environnements : base (python2), Axile(python2) and py3(python3) 
i had the stupid idea to install `anaconda3` (via the .pkg found here [https://repo.anaconda.com/archive/Anaconda3-2019.10-MacOSX-x86_64.pkg](https://repo.anaconda.com/archive/Anaconda3-2019.10-MacOSX-x86_64.pkg)
Installation done in `~/opt/anaconda3`

At this point my old environnements (base, Axile and py3) where not accessible anymore.

So 

- I moved `$ mv ~/opt/anaconda3 ~/opt/anaconda3_trash`
- I restored `~/.bash_profile-anaconda3.bak` (created by anaconda3 installer) as `~/.bash_profile`

Then i try to update conda...

### Steps to Reproduce

```
(base) $ conda update -n base -c defaults conda

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


```


## Expected Behavior

recognize conda base environment and update conda 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>


```
     active environment : base
    active env location : /Users/puiseux/anaconda2
            shell level : 1
       user config file : /Users/puiseux/.condarc
 populated config files : /Users/puiseux/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.5
         python version : 2.7.15.final.0
       virtual packages : 
       base environment : /Users/puiseux/anaconda2  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/puiseux/anaconda2/pkgs
                          /Users/puiseux/.conda/pkgs
       envs directories : /Users/puiseux/.conda/envs
                          /Users/puiseux/anaconda2/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.13.0 CPython/2.7.15 Darwin/19.2.0 OSX/10.15.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</p></details>


<details open><summary><code>`conda config --show-sources`</code></summary><p>


```
==> /Users/puiseux/.condarc <==
ssl_verify: True
channels:
  - defaults


```
</p></details>


<details><summary><code>`(base) $ conda list --show-channel-urls`</code></summary><p>


```
EnvironmentLocationNotFound: Not a conda environment: /Users/puiseux/anaconda2

```
nevertheless, both environnements Axile and py3 seems to work fine. For instance

```
(base) $ conda activate py3
(py3) $ conda list --show-channel-urls
# packages in environment at /Users/puiseux/anaconda2/envs/py3:
#
# Name                    Version                   Build  Channel
absl-py                   0.8.1                    pypi_0    pypi
aeropy                    0.0                       dev_0    <develop>
appdirs                   1.4.3                    pypi_0    pypi
appnope                   0.1.0                    py37_0    defaults
ascii                     3.6                      pypi_0    pypi
asn1crypto                1.3.0                    py37_0    defaults
astor                     0.8.0                    pypi_0    pypi
astroid                   2.3.3                    py37_0    defaults
atomicwrites              1.3.0                    pypi_0    pypi
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.lzma            0.0.14           py37hd0afa68_0    defaults
bdw-gc                    8.0.4                h04f5b5a_0    conda-forge
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2019.11.27                    0    defaults
certifi                   2019.11.28               py37_0    defaults
cffi                      1.13.2           py37hb5b8e2f_0    defaults
click                     7.0                      pypi_0    pypi
cloog                     0.18.0                        0    anaconda
colorama                  0.4.1                    pypi_0    pypi
colored                   1.3.93                   pypi_0    pypi
cryptography              2.8              py37ha12b0ac_0    defaults
curl                      7.67.0               ha441bb4_0    defaults
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.12              h90a0687_0    defaults
decorator                 4.4.1                      py_0    defaults
docutils                  0.14                     pypi_0    pypi
dxfgrabber                1.0.0                    pypi_0    pypi
dxfwrite                  1.2.1                    pypi_0    pypi
ecl                       16.1.2            h3123da9_1003    conda-forge
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.1.0            py37h1de35cc_0    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
future                    0.18.2                   py37_0    defaults
gast                      0.2.2                    pypi_0    pypi
gcc                       4.8.5                         8    anaconda
geos                      3.7.1                h0a44026_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
glib                      2.63.1               hd977a24_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
gmsh-interop              2019.1                   pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.24.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13               h39711bb_2    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
importlib-metadata        0.9                      pypi_0    pypi
intel-openmp              2019.4                      233    defaults
ipython                   7.11.1           py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
isl                       0.12.2                        1    anaconda
isort                     4.3.21                   py37_0    defaults
jedi                      0.15.2                   py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsoncpp                   1.8.4                h04f5b5a_0    defaults
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.1.0            py37h0a44026_0    defaults
krb5                      1.16.4               hddcf347_0    defaults
lazy-object-proxy         1.4.3            py37h1de35cc_0    defaults
libcurl                   7.67.0               h051b688_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libnetcdf                 4.6.1                hd5207e6_2    defaults
libogg                    1.3.2                h1de35cc_0    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libssh2                   1.8.2                ha12b0ac_0    defaults
libtheora                 1.1.1                hb4e5f40_1    defaults
libtiff                   4.1.0                hcb84e12_0    defaults
libvorbis                 1.3.6                h1de35cc_0    defaults
libxml2                   2.9.9                hf6e021a_1    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
markdown                  3.1.1                    pypi_0    pypi
matplotlib                3.1.0            py37h54f8f79_0    defaults
maxima                    5.42.2               h3123da9_1    conda-forge
mccabe                    0.6.1                    py37_1    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.3.0            py37hfbe908c_0    defaults
mkl_fft                   1.0.15           py37h5e564d8_0    defaults
mkl_random                1.1.0            py37ha771720_0    defaults
more-itertools            7.0.0                    pypi_0    pypi
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1    defaults
numpy                     1.16.4           py37hacdab7b_0    defaults
numpy-base                1.16.4           py37h6575580_0    defaults
openssl                   1.1.1d               h1de35cc_3    defaults
opt-einsum                3.1.0                    pypi_0    pypi
pandas                    0.25.1           py37h0a44026_0    defaults
parso                     0.5.2                      py_0    defaults
path-py                   11.5.0                   pypi_0    pypi
pcre                      8.43                 h0a44026_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.2.0                    pypi_0    pypi
pip                       19.1.1                   py37_0    defaults
plotly                    4.4.1                      py_0    defaults
pluggy                    0.9.0                    pypi_0    pypi
prompt_toolkit            3.0.2                      py_0    defaults
protobuf                  3.10.0                   pypi_0    pypi
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    pypi_0    pypi
pybind11                  2.4.3                    pypi_0    pypi
pycparser                 2.19                     py37_0    defaults
pyfiglet                  0.8.post1                pypi_0    pypi
pygments                  2.4.2                      py_0    defaults
pylint                    2.4.4                    py37_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pysocks                   1.7.1                    py37_0    defaults
pytest                    4.4.0                    pypi_0    pypi
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.1                      py_0    defaults
python.app                2                        py37_9    defaults
pytictoc                  1.5.0                    pypi_0    pypi
pytools                   2019.1                   pypi_0    pypi
pytz                      2019.3                     py_0    defaults
pyyaml                    5.1.2                    pypi_0    pypi
qt                        5.9.7                h468cd18_1    defaults
readline                  7.0                  h1de35cc_5    defaults
retrying                  1.3.3                    py37_2    defaults
scipy                     1.3.3                    pypi_0    pypi
setuptools                41.0.1                   py37_0    defaults
shapely                   1.6.4            py37he8793f5_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.13.0                   py37_0    defaults
sqlite                    3.30.1               ha441bb4_0    defaults
sympy                     1.4                      pypi_0    pypi
tbb                       2019.8               h04f5b5a_0    defaults
tensorboard               2.0.0                    pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0    defaults
tornado                   6.0.3            py37h1de35cc_0    defaults
traitlets                 4.3.3                    py37_0    defaults
urllib3                   1.24.2                   py37_0    defaults
virtualenv                16.4.3                   pypi_0    pypi
vtk                       8.2.0           py37h9bafd54_200    defaults
wcwidth                   0.1.7                    py37_0    defaults
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.4                   py37_0    defaults
wrapt                     1.11.2           py37h1de35cc_0    defaults
wxpython                  4.0.4            py37hebc47a7_0    defaults
xonsh                     0.9.13.dev1              pypi_0    pypi
xz                        5.2.4                h1de35cc_4    defaults
zipp                      0.3.3                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```
</p></details>

**Comment by shardsofblue** [comment]
I also am getting this error. In case it is useful for resolving this bug, I thought I should let you know all my details are over on a Stackoverflow, [here](https://stackoverflow.com/questions/62541017/anaconda-wont-update-no-default-base-environment-error).

**Comment by outlk** [comment]
This afternoon, when i deleted the "history" file under the directory "conda-meta", the "NoBaseEnvironmentError" error occured. When i created a new "history" file, the "base" environment works again.

**Comment by bouh2** [comment]
Have updated conda and stuck with error 'Reason: image not found':
Referenced from: /Users//anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
Reason: image not found
Temp fixed via https://github.com/conda/conda/issues/9038

Then run straight into "NoBaseEnvironmentError" error.
Thanks to @outlk , creating a new 'history' file fixed an issue with 'base' env.

**Comment by gunterfuchs** [comment]
> This afternoon, when i deleted the "history" file under the directory "conda-meta", the "NoBaseEnvironmentError" error occured. When i created a new "history" file, the "base" environment works again.

There is no conda-meta folder in my Windows 10 installation folder (anaconda3 version 4.10.3).
