### ISSUE TITLE
Conda should not try to update the 'python' package if it will cripple conda

### ISSUE THREAD

**Issue by dbsanfte** [conda/conda#8932]
## Current Behavior
We are using the conda in Miniconda 4.5.1 to develop Python 3.6 packages.

When we install new packages with `conda install`, with `auto-update-conda` false, sometimes conda decides that an upgrade to the Python major version is desireable, and attempts to install a package update e.g. from Python 3.6.6 to Python 3.7.x.

This breaks conda leading to `ModuleNotFoundError: no module named 'conda'` errors, at which point conda becomes unusable.

### Steps to Reproduce

From a default install of Miniconda 4.5.1, do this:
 
```
conda config --system --set auto_update_conda false
conda install --no-update-dependencies pyodbc requests
```

## Expected Behavior
Since conda will break if it tries to upgrade the `python` package from 3.6.x to 3.7.x, it should not do this. It should only upgrade the `python` package within the same minor version of Python (3.6.x).

**Comment by dbsanfte** [comment]
I've been able to mitigate this for now by doing `echo "python 3.6.*" > /opt/conda/conda-meta/pinned` , for anyone who lands here from Google.

**Comment by msarahan** [comment]
This behavior was changed in conda 4.7.0.
