### ISSUE TITLE
conda version 4.5.11 cripples itself when calling update

### ISSUE THREAD

**Issue by mattorourke17** [conda/conda#8944]
Using ```conda``` version 4.5.11 with python 2.7 I called
```
conda update pandas
```
in an attempt to use newer features of pandas. The update completed successfully, however I clearly did not read through all the packages as closely as I should have, because it made some drastic changes. Here is the relevant section of ```anaconda2/conda-meta/history```

```
==> 2019-07-16 00:23:33 <==
# cmd: /home/matt/anaconda2/bin/conda update pandas
# conda version: 4.5.11
-defaults::ca-certificates-2018.03.07-0
-defaults::certifi-2018.10.15-py27_0
-defaults::libedit-3.1.20170329-h6b74fdf_2
-defaults::libgcc-ng-8.2.0-hdf63c60_1
-defaults::ncurses-6.1-hf484d3e_0
-defaults::numpy-1.15.1-py27h1d66e8a_0
-defaults::openssl-1.0.2p-h14c3975_0
-defaults::pandas-0.23.4-py27h04863e7_0
-defaults::pip-10.0.1-py27_0
-defaults::python-2.7.15-h1571d57_0
-defaults::python-dateutil-2.7.3-py27_0
-defaults::pytz-2018.5-py27_0
-defaults::setuptools-40.2.0-py27_0
-defaults::six-1.11.0-py27_1
-defaults::sqlite-3.24.0-h84994c4_0
-defaults::wheel-0.31.1-py27_0
-defaults::zlib-1.2.11-ha838bed_2
+defaults::_libgcc_mutex-0.1-main
+defaults::ca-certificates-2019.5.15-0
+defaults::certifi-2019.6.16-py36_0
+defaults::libedit-3.1.20181209-hc058e9b_0
+defaults::libgcc-ng-9.1.0-hdf63c60_0
+defaults::ncurses-6.1-he6710b0_1
+defaults::numpy-1.14.2-py36hdbf6ddf_0
+defaults::openssl-1.1.1c-h7b6447c_1
+defaults::pandas-0.24.2-py36he6710b0_0
+defaults::pip-19.1.1-py36_0
+defaults::python-3.6.8-h0371630_0
+defaults::python-dateutil-2.8.0-py36_0
+defaults::pytz-2019.1-py_0
+defaults::setuptools-41.0.1-py36_0
+defaults::six-1.12.0-py36_0
+defaults::sqlite-3.28.0-h7b6447c_0
+defaults::wheel-0.33.4-py36_0
+defaults::zlib-1.2.11-h7b6447c_3
# update specs: [u'pandas']
```
Most notably (I think), ```conda``` removes python2 and replaces it with python3. I'm not sure if this is the intended behavior, but it certainly is not what I would expect. Now the default Anaconda ```python``` in ```anaconda2/bin/python``` is python 3.6 instead of python 2.7.

Normally this wouldn't be the end of the world because I should just be able to revert the update with ```conda```, however now any call to ```conda``` returns
```
Traceback (most recent call last):
  File "/home/matt/anaconda2/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```  

This seemingly prevents me from obtaining more information about the evironment details and what went wrong, but even more importantly I think it prevents me from fixing the problem without re-installing anaconda. Is this correct? That seems to be what happened here https://github.com/conda/conda/issues/2463 and here https://github.com/conda/conda/issues/1733#issuecomment-150641779. However, it was claimed here https://github.com/conda/conda/issues/5454 that conda uninstalling itself should be fixed in version 4.3 and after. Any idea what's going on here?

I'm not completely sure if the forcible change of default from ```python2``` to ```python3``` is the main culprit for this ```ModuleNotFoundError```, but either way the combination of the two have completely crippled my working environment. 

I am hoping there is a way to restore my previous environment without a complete reinstall of Anaconda.

**Comment by mattorourke17** [comment]
my PATH and PYTHONPATH are set correctly, by the way

**Comment by eduardoftoliveira** [comment]
yap, exactly the same problem here while updating nglview

**Comment by msarahan** [comment]
Conda between 4.4 and 4.7 (not including 4.7) was allowed to change python version if it was required to satisfy your requests.  Conda 4.7 no longer allows this, and presents you with an UnsatisfiableError.  So, while this is definitely broken, we won't fix it in the 4.5 series.

Sorry for the problem.  You can try to install miniconda to another path, and then use that miniconda with the -p argument to install and fix software in your other anaconda installation.

conda install -p path-to-anaconda-folder python=2.7

**Comment by mattorourke17** [comment]
Okay, it seems that the new conda from miniconda was able to repair things in my original anaconda directory. Thanks for your help.

**Comment by gautham949** [comment]
I'm currently facing the same issue. How did you use the new conda from miniconda to repair? Can you please help with the steps. I just installed Minconda
