### ISSUE TITLE
More SSL Issues. Manually updating Cert fix.

### ISSUE THREAD

**Issue by ianpepper** [conda/conda#8945]
Hi All,

Just went through a very long battle with SSL problems. I seem to have a reasonable fix (for me) that does not require `ssl_verify: false`.

I have read through a lot of posts on this problem that range over the years. For those who can't fix the problem simply by updating `conda update ca-certificates certifi openssl -k` hopefully this will help you too, but if I have learned anything SSL problems come in a lot of flavors. 

## Background
I work on a secure corporate network running windows 7 machines where I do not have administrative privileges and very minimal support from IT. 

Note: I had to install anaconda into C:\ProgramData because I couldnt run .exe out of the C:\Users folder

## Current Behavior

SSL gets a bad handshake with any conda commands that require the internet.

### Steps to Reproduce
Extra activate just to prove that wasn't the problem.
```
(base) C:\Users\IanPe>conda activate base

(base) C:\Users\IanPe>conda update conda
Collecting package metadata: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pk
gs/main/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.


If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443
): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by
 SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_serve
r_certificate\', \'certificate verify failed\')])")))'))
```

### Other Diagnostics 
When i run `conda info -s ` at the bottom the following paths are missing:
```
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
```
Not sure what this looks like for people without SSL problems, but my guess is there are problems accessing the Cert store during the installation? Others were able to solve their problems by setting it to the path to cacert.pem in pkg\certifi file path. This did not work for me. Also, using the anaconda prompt one would have to script it in every time since the set command would not stick. (maybe there is a way, but im not a compsci backround)

## Expected Behavior

SSL to verify automatically without hours of debugging

## Solution
For me the solution was to go to repo.anaconda.com and download the certificate via the web browser. Save it to some location then point the \.condarc setting at it.
```
(base) C:\Users\IanPe>conda config --set ssl_verify C:\Users\IanPe\certs\ca-cert
.cer

(base) C:\Users\IanPe>conda update conda
Collecting package metadata: done
Solving environment: done
```
### Attempts
I have tried a lot of things, but to list a few:

- update softwares ( I know the conda version below is 4.6.12 and we are on like 4.7.5 now, but I had this problem on my other VPC on 4.7.5 and this solution fixed both of them)
- point sll_verify at the cacert.pem files, but those never worked.
- install certificates to store
- tried past 6 anaconda installers
- check for the bad .dll files in the system32 folder (not present)
- able to ping repo.anaconda.com via anaconda prompt (firewall check)
- installed as administrator (not the recommended way, but worth a shot)
- a lot more I cant think of right now.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(base) C:\Users\IanPe>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 2
       user config file : C:\Users\IanPe\.condarc
 populated config files : C:\Users\IanPe\.condarc
          conda version : 4.6.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\IanPe\.conda\pkgs
                          C:\Users\IanPe\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\IanPe\.conda\envs
                          C:\Users\IanPe\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.12 requests/2.21.0 CPython/3.7.3 Windows/7 W
indows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(base) C:\Users\IanPe>conda config --show-sources
==> C:\Users\IanPe\.condarc <==
envs_dirs:
  - C:/ProgramData/Anaconda3/envs
ssl_verify: C:\Users\IanPe\certs\ca-cert.cer
channels:
  - defaults
```

**Comment by Mark531** [comment]
I tried your solution but it didn't work for me.
