### ISSUE TITLE
conda silent installer on Windows directory arg doesn't work

### ISSUE THREAD

**Issue by stevekm** [conda/conda#8946]
## Current Behavior

When trying to install conda on Windows using silent mode and directing it to install in a specific directory, it does not actually install in the specified directory and instead installs in the default directory. 

The documentation:

https://docs.anaconda.com/anaconda/install/silent-mode/

> To run the the Windows installer for Miniconda in silent mode, use the /S argument. The following optional arguments are supported:
>
>    /InstallationType=[JustMe|AllUsers]—Default is``JustMe``.
>    /AddToPath=[0|1]—Default is 1’
>    /RegisterPython=[0|1]—Make this the system’s default Python. 0 indicates JustMe, which >is the default. 1 indicates AllUsers.
>    /S—Install in silent mode.
>    /D=<installation path>—Destination installation path. Must be the last argument. Do not >wrap in quotation marks. Required if you use /S.
>
>All arguments are case-sensitive.
>
>EXAMPLE: The following command installs Miniconda for the current user without registering Python as the system’s default:
>
> `start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3`

### Steps to Reproduce

From `cmd.exe`, in the `E:\` drive, I run a command like this:

```
start /wait "" Miniconda3-4.6.14-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /S /D=E:\conda
```

This should install conda in `E:\conda`. 

However, it actually installs instead in `C:\Users\stevekm\Miniconda3`

## Expected Behavior

Its supposed to install in the directory listed by `/D` argument

## Environment Information

Windows 10

Miniconda3-4.6.14-Windows-x86_64.exe

**Comment by msarahan** [comment]
Sorry, the similar command 

```
start /wait "" Miniconda3-4.6.14-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /S /D=C:\conda_test
```

works for me.  It might have something to do with the drive letter.  Try copying the installer to the E: before running it?  Yes, that's not really ideal, but this issue is likely not important enough for us to ever have time to fix it.  If it is important to you, you can look at the source code yourself over at https://github.com/conda/constructor - pull requests are welcome.

**Comment by stevekm** [comment]
The installer is already on the E: drive when I run the command.
