### ISSUE TITLE
Packaging system .condarc

### ISSUE THREAD

**Issue by timsnyder** [conda/conda#8957]
I admin a multi-user conda install.  We've been using it since 2015 and I've kept the global .condarc under limited change with filesystem permissions.  However, I'd really like to put it under version control.

I think the best way to do this is by packaging $PREFIX/.condarc. 

If I create a package that installs $PREFIX/.condarc is that going to cause problems?  If this seems legit, I'd also be willing to submit a PR for https://conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html to document it.

I guess one thing is that I wouldn't want anyone to be able to use conda config --system --set to be able to modify the system configuration. I would want them to get a message back saying that the system config is owned by package foo and that changes require installing a new version of that package.

**Comment by timsnyder** [comment]
I guess one thing is that I wouldn't want anyone to be able to use `conda config --system --set` to be able to modify the system configuration.  I would want them to get a message back saying that the system config is owned by package foo and that changes require installing a new version of that package.

**Comment by msarahan** [comment]
You should be really, really careful about using conda packages to manage configuration.  Because you can't merge contents from other files, any other package that attempts this approach will clobber yours, or vice versa, when they are both installed.

Another way to achieve this might be to run `conda config` commands in post-link scripts.  This would let you modify the config rather than clobbering it, but it's still fairly ugly and fragile.  As for permissions, you should handle that with the OS permissions.

**Comment by timsnyder** [comment]
@msarahan I'm confused by your reply.  I would only want one package to be able to install the .condarc.  

Do you have any suggestions on how I might keep a centralized system .condarc under version control? 

This might be better done in a face2face syncup at some point.

**Comment by msarahan** [comment]
I think that problem might be better solved with a config management tool, such as salt, ansible, chef or puppet.

**Comment by timsnyder** [comment]
Ahh.  I keep forgetting how weird my usecase is.  We have a single miniconda installation on NFS that all machines in our environment see.  If it were distributed, a config management tool would make sense.

I'm going to give this a try, also changing `path_conflict` to `prevent`.
