### ISSUE TITLE
Very slow behavior of conda when installing Anaconda in C:\Program Files

### ISSUE THREAD

**Issue by wulmer** [conda/conda#896]
Hi,
I noticed that using conda commands on Windows on a normal single-user (w/o admin rights) installation works fine but does not when being run by a normal user for a multi-user installation (w/o write permissions on the installation folder, e.g. `C:\Program Files`).

I found out that the [`try_write`](https://github.com/conda/conda/blob/master/conda/utils.py#L11-L19) function from `conda.utils` **blocks conda for several seconds** before figuring out that it cannot write a file in `C:\Program Files\Anaconda`.
This is because the `tempfile.TemporaryFile` function tries up to 32767 times (`import os; os.TMP_MAX`) to create the file before it gives up.

This should definitely be changed as it **affects all conda commands and makes it awfully slow**.

Would it be acceptable to replace the `TemporaryFile` with a normal `open` and `os.remove` ?

Wolfgang

**Comment by desh2608** [comment]
I'm getting slow response even when Anaconda is installed in single user mode. Do you have any solutions to this issue?

**Comment by AmaanX5H** [comment]
> Hi,
> I noticed that using conda commands on Windows on a normal single-user (w/o admin rights) installation works fine but does not when being run by a normal user for a multi-user installation (w/o write permissions on the installation folder, e.g. `C:\Program Files`).
> 
> I found out that the [`try_write`](https://github.com/conda/conda/blob/master/conda/utils.py#L11-L19) function from `conda.utils` **blocks conda for several seconds** before figuring out that it cannot write a file in `C:\Program Files\Anaconda`.
> This is because the `tempfile.TemporaryFile` function tries up to 32767 times (`import os; os.TMP_MAX`) to create the file before it gives up.
> 
> This should definitely be changed as it **affects all conda commands and makes it awfully slow**.
> 
> Would it be acceptable to replace the `TemporaryFile` with a normal `open` and `os.remove` ?
> 
> Wolfgang

Can you please elaborate step by step how this issue would be resolved?

I'm also having this issue, either using Anaconda prompt or cmd for python commands always take while to execute.

**Comment by wulmer** [comment]
Hi @AmaanX5H, I am not sure if the current performance issues have to do with this very old issue. If you are interested in more technical details see the related issue and pull request  https://github.com/conda/conda/issues/2151. But what you could do in any case is some profiling on conda code, e.g. run conda with debug flags and see what step takes much longer than expected.
Then search through the code to find the last log message before the lag and then use `pdb` to step through the code to see where a bottleneck exists. By pinning down performance bottlenecks and providing detailed analysis reports helps the conda team a lot. Or you could even prepare your own pull request (like I did years ago).
