### ISSUE TITLE
filter strict channel priority on spec matches

### ISSUE THREAD

**Issue by minrk** [conda/conda#8960]
In repo2docker, we want to support installing frozen environments created with `conda env export`, including build string, etc. Pretty often, packages on conda-forge are found to have too-loose dependency pinning, which results in them being marked as broken, moving them from `main` to the `broken` label. This (rightly) prevents naïve installation of the 'broken' builds, but also (wrongly, according to user intent) prevents installation when the exact build of the package is requested. For this reason, repo2docker adds the conda-forge broken label as a lowest-priority channel. This is not an ideal solution, and we only really want to use the broken channel when exact requested specs can only be satisfied by these semi-revoked packages.

Here is what currently happens with strict channel priority when `pkg=version=build_1` has been marked as broken since the call to `conda env export`:

- package `pkg=version=build_1` is requested
- package `pkg` is found on conda-forge, so no other channels are consulted
- UnsatisfiableError

I think it would suit us very well if strict channel priority picked the first channel with a package *that directly matches the requested spec* rather than only filtering on the name:

- package `pkg=version=build_1` is requested
- package `pkg` is found on conda-forge, but doesn't match the spec, move on
- package `pkg=version=build_1` is found on conda-forge/broken, so only conda-forge/broken is considered
- success

At first, I thought this would be too complicated and single-use-case, but I think it generally results in strict channel priority behaving in a less surprising manner as stricter specs are requested (version only pinning or version + build).

Another option for our specific case is to change conda-forge policy to apply hotfixes much more often rather than moving broken, but I think this would be an improvement to strict channel priority in general.

See more discussion [on repo2docker](https://github.com/jupyter/repo2docker/issues/731)

**Comment by jjhelmus** [comment]
If the environment is pinned to build strings, etc why is strict channel priority needed?  Regular channel priority will select packages from higher priority channels so the conda-forge broken label will only be used if the package is not available from higher priority channels.
