### ISSUE TITLE
Conda environment name is empty when using --prefix

### ISSUE THREAD

**Issue by trbedwards** [conda/conda#8962]
The fix from #7831 didn't work for me. I have a `myenv.yml` where in which is `name: myenv`. I did the following:
```
conda env create -f myenv.yml -p ~/anaconda/envs
```
Now I have an environment with an empty name. I did the following:

```
conda config --append envs_dirs ~/anaconda/envs
conda activate myenv
```
and I get this error:

```
Invalid environment name: '/home/tedwards/anaconda/envs'
```

What is the correct way to create a named conda environment from a yaml file with a different prefix?

I'm using conda 4.6.11 on Ubuntu 16.04 64-bit

**Comment by msarahan** [comment]
You created an env named "envs"

You need to adjust your config to one folder up.

conda config --append envs_dirs ~/anaconda

Except now you might need to edit your .condarc file to remove the incorrect folder.
