### ISSUE TITLE
Can't update conda 4.5.12 to to 4.7.10

### ISSUE THREAD

**Issue by Mikejs2178** [conda/conda#8979]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

[CantUpdatge.pdf](https://github.com/conda/conda/files/3418018/CantUpdatge.pdf)

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment]
Insufficient detail.  Please fill out all requested issue template information.

**Comment by Mikejs2178** [comment]
tblib                     1.3.2            py36hda67792_0  
tensorboard               1.8.0                     <pip>
tensorflow                1.8.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py36_1  
testpath                  0.4.2                    py36_0    conda-forge
theano                    1.0.3            py36hfc679d8_1    conda-forge
Theano                    1.0.1                     <pip>
tk                        8.6.8                ha441bb4_0  
toolchain                 2.3.0                         0    conda-forge
toolchain_c_osx-64        2.3.0                         0    conda-forge
toolchain_cxx_osx-64      2.3.0                         0    conda-forge
toolz                     0.9.0                    py36_0  
tornado                   5.1.1            py36h1de35cc_0  
tqdm                      4.28.1           py36h28b3542_0  
traitlets                 4.3.2            py36h65bd3ce_0  
typed-ast                 1.1.0            py36h1de35cc_0  
typing                    3.6.4                    py36_0  
unicodecsv                0.14.1           py36he531d66_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.1                   py36_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1                    py36_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                    py36_0    conda-forge
wrapt                     1.10.11          py36h1de35cc_2  
wurlitzer                 1.0.2                    py36_0    conda-forge
xarray                    0.11.0                    <pip>
xgboost                   0.72                      <pip>
xlrd                      1.2.0                    py36_0  
xlsxwriter                1.1.2                    py36_0  
xlwings                   0.15.1                   py36_0    conda-forge
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zict                      0.1.3                    py36_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
GEB:~ schoem$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/schoem/.condarc
 populated config files : /Users/schoem/.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.6.7.final.0
       base environment : /Users/schoem/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/schoem/anaconda3/pkgs
                          /Users/schoem/.conda/pkgs
       envs directories : /Users/schoem/anaconda3/envs
                          /Users/schoem/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.7 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 502:20
             netrc file : None
           offline mode : False

GEB:~ schoem$ conda config --show-sources
==> /Users/schoem/.condarc <==
ssl_verify: True
channels:
  - defaults
  - conda-forge

GEB:~ schoem$ conda update -n base -c defaults conda
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

GEB:~ schoem$ conda update -n base -c defaults conda
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

GEB:~ schoem$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/schoem/.condarc
 populated config files : /Users/schoem/.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.6.7.final.0
       base environment : /Users/schoem/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/schoem/anaconda3/pkgs
                          /Users/schoem/.conda/pkgs
       envs directories : /Users/schoem/anaconda3/envs
                          /Users/schoem/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.7 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 502:20
             netrc file : None
           offline mode : False

GEB:~ schoem$ conda config --show-sources
==> /Users/schoem/.condarc <==
ssl_verify: True
channels:
  - defaults
  - conda-forge

GEB:~ schoem$ conda list --show-channel-urls
# packages in environment at /Users/schoem/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
absl-py                   0.2.1                     <pip>
alabaster                 0.7.12                   py36_0    defaults
anaconda                  2018.12                  py36_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.7                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    conda-forge
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h1de35cc_1    defaults
args                      0.1.0                     <pip>
arviz                     0.3.1                     <pip>
asn1crypto                0.24.0                   py36_0    defaults
astor                     0.6.2                     <pip>
astroid                   2.1.0                    py36_0    defaults
astropy                   3.1              py36h1de35cc_0    defaults
atomicwrites              1.2.1                    py36_0    conda-forge
attrs                     18.2.0           py36h28b3542_0    defaults
babel                     2.6.0                    py36_0    conda-forge
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    conda-forge
backports.os              0.1.1                    py36_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.6.3                    py36_0    conda-forge
bitarray                  0.8.3            py36h1de35cc_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    conda-forge
bleach                    3.0.2                    py36_0    defaults
bleach                    1.5.0                     <pip>
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     1.0.2                    py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.11.29               py36_0    defaults
cffi                      1.11.5           py36h6174b99_1    defaults
cftime                    1.0.3.4                   <pip>
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
clint                     0.5.1                     <pip>
cloudpickle               0.6.1                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.1                    py36_0    defaults
conda                     4.5.12                   py36_0    defaults
conda-build               3.17.6                   py36_0    defaults
conda-env                 2.6.0                         1    conda-forge
conda-verify              3.1.1                 py36_1000    conda-forge
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.4.2            py36ha12b0ac_0    defaults
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.29.2           py36h0a44026_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_1    defaults
dask                      1.0.0                    py36_0    defaults
dask-core                 1.0.0                    py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py36_0    defaults
defusedxml                0.5.0                    py36_1    defaults
distributed               1.25.1                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3                    py36_2    conda-forge
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
filelock                  3.0.10                   py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.7                    py36_0    defaults
floyd-cli                 0.10.39                   <pip>
fontconfig                2.13.1               hce039c3_0    conda-forge
freetype                  2.9.1                hb4e5f40_0    defaults
fribidi                   1.0.5                h470a237_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
gast                      0.2.0                     <pip>
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.7            py36h1de35cc_1    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py36_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36h6ef4df4_2    defaults
graphite2                 1.3.13               h7d4d677_0    conda-forge
graphviz                  2.40.1               hefbbd9a_2    defaults
greenlet                  0.4.15           py36h1de35cc_0    defaults
grpcio                    1.12.0                    <pip>
h5py                      2.8.0            py36h878fce3_3    defaults
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                    py36_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py36_0    defaults
imageio                   2.4.1                    py36_0    conda-forge
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.6                      py36_0    conda-forge
inflection                0.3.1                    py36_0    defaults
intel-openmp              2019.1                      144    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.2.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.2                   py36_0    defaults
jinja2                    2.10                     py36_0    conda-forge
joblib                    0.12.5                     py_0    conda-forge
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.2.4                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.3                   py36_0    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
Keras                     2.1.6                     <pip>
keyring                   17.0.0                   py36_0    defaults
kiwisolver                1.0.1            py36h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_0    defaults
libopenblas               0.2.20               hdc02c5d_7    defaults
libpng                    1.6.35               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.26.0           py36h8c7ce04_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.2.5            py36hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
mako                      1.0.7                      py_1    conda-forge
Markdown                  2.6.11                    <pip>
markupsafe                1.1.0            py36h1de35cc_0    defaults
marshmallow               2.15.3                    <pip>
matplotlib                3.0.2            py36h54f8f79_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h1de35cc_0    defaults
mkl                       2019.1                      144    defaults
mkl-service               1.1.2            py36hfbe908c_5    defaults
mkl_fft                   1.0.6            py36h27c97d8_0    defaults
mkl_random                1.0.2            py36h27c97d8_0    defaults
mlxtend                   0.13.0                     py_1    conda-forge
more-itertools            4.3.0                    py36_0    conda-forge
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpl-finance               0.10.0                    <pip>
mpmath                    1.1.0                    py36_0    defaults
msgpack-python            0.5.6            py36h04f5b5a_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.0                    py36_0    defaults
nbconvert                 5.4.0                    py36_1    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
netCDF4                   1.4.2                     <pip>
networkx                  2.2                      py36_1    defaults
ninja                     1.8.2            py36h04f5b5a_1    defaults
nltk                      3.4                      py36_1    defaults
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.7.4                    py36_0    defaults
numba                     0.41.0           py36h6440ff4_0    defaults
numexpr                   2.6.8            py36h7413580_0    defaults
numpy                     1.15.4           py36hacdab7b_0    defaults
numpy-base                1.15.4           py36h6575580_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.46                     py36_0    defaults
openpyxl                  2.5.12                   py36_0    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
packaging                 18.0                     py36_0    defaults
pandas                    0.23.4           py36h6440ff4_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                    py36_1    defaults
pango                     1.42.4               h060686c_0    defaults
parso                     0.3.1                    py36_0    defaults
partd                     0.3.9                    py36_0    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.3                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.5                    py36_0    conda-forge
pillow                    5.3.0            py36hb68e598_0    defaults
pip                       18.1                      <pip>
pip                       10.0.1                    <pip>
pip                       18.1                     py36_0    defaults
pixman                    0.34.0               h470a237_3    conda-forge
pkginfo                   1.4.2                    py36_1    defaults
pluggy                    0.8.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.5.0                    py36_0    defaults
prompt_toolkit            2.0.7                    py36_0    defaults
protobuf                  3.5.2.post1               <pip>
psutil                    5.4.8            py36h1de35cc_0    defaults
ptyprocess                0.6.0                    py36_0    conda-forge
pulp                      1.6.8                 py36_1000    conda-forge
py                        1.7.0                    py36_0    defaults
py-lief                   0.9.0            py36hd4eaf27_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h1de35cc_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h1de35cc_9    defaults
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pydataset                 0.2.0                     <pip>
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.3.1                    py36_0    defaults
pygpu                     0.7.6            py36h7eb728f_0    conda-forge
pylint                    2.2.2                    py36_0    defaults
pymc3                     3.6                   py36_1000    conda-forge
pyodbc                    4.0.25           py36h0a44026_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.3.0                    py36_0    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36h13cba08_0    defaults
pytest                    4.0.2                    py36_0    defaults
pytest-arraydiff          0.3              py36h39e3cac_0    defaults
pytest-astropy            0.5.0                    py36_0    defaults
pytest-doctestplus        0.2.0                    py36_0    defaults
pytest-openfiles          0.3.1                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
python                    3.6.7                haf84260_0    defaults
python-dateutil           2.7.5                    py36_0    defaults
python-graphviz           0.8.4                 py36_1002    conda-forge
python-libarchive-c       2.8                      py36_6    defaults
python.app                2                        py36_9    defaults
pytz                      2018.7                   py36_0    defaults
pywavelets                1.0.1            py36h1d22016_0    defaults
pyyaml                    3.13             py36h1de35cc_0    defaults
pyzmq                     17.1.2           py36h1de35cc_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.3                    py36_0    defaults
qtconsole                 4.4.3                    py36_0    defaults
qtpy                      1.5.2                    py36_0    defaults
quandl                    3.4.6                    py36_0    conda-forge
raven                     6.9.0                     <pip>
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py36_0    defaults
requests-toolbelt         0.8.0                     <pip>
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h1de35cc_0    defaults
scikit-image              0.14.1           py36h0a44026_0    defaults
scikit-learn              0.20.1           py36h27c97d8_0    defaults
scipy                     1.1.0            py36h1410ff5_2    defaults
seaborn                   0.9.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                40.6.3                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.12.0                   py36_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         1.0.1                    py36_0    conda-forge
sortedcontainers          2.1.0                    py36_0    defaults
sphinx                    1.8.2                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.2                    py36_0    defaults
spyder-kernels            0.3.0                    py36_0    defaults
sqlalchemy                1.2.15           py36h1de35cc_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
statsmodels               0.9.0            py36h1d22016_0    defaults
sympy                     1.3                      py36_0    conda-forge
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36hda67792_0    defaults
tensorboard               1.8.0                     <pip>
tensorflow                1.8.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    conda-forge
Theano                    1.0.1                     <pip>
theano                    1.0.3            py36hfc679d8_1    conda-forge
tk                        8.6.8                ha441bb4_0    defaults
toolchain                 2.3.0                         0    conda-forge
toolchain_c_osx-64        2.3.0                         0    conda-forge
toolchain_cxx_osx-64      2.3.0                         0    conda-forge
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36h1de35cc_0    defaults
tqdm                      4.28.1           py36h28b3542_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typed-ast                 1.1.0            py36h1de35cc_0    defaults
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py36_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                    py36_0    conda-forge
wrapt                     1.10.11          py36h1de35cc_2    defaults
wurlitzer                 1.0.2                    py36_0    conda-forge
xarray                    0.11.0                    <pip>
xgboost                   0.72                      <pip>
xlrd                      1.2.0                    py36_0    defaults
xlsxwriter                1.1.2                    py36_0    defaults
xlwings                   0.15.1                   py36_0    conda-forge
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
GEB:~ schoem$

**Comment by jorwoods** [comment]
I am having the same issue on Windows with a fresh download and install of 2019.03 from the anaconda,com website. Except my current version of conda is 4.6.11.

```
conda update -n base -c defaults conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.11
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

```

**Comment by brianmapes** [comment]
Infinite loop of failure! 

bash-3.2$ conda update -n base conda
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.12

Please update conda by running
    $ conda update -n base conda

**Comment by HeyLey** [comment]
+1
