### ISSUE TITLE
Way to list manually installed packages

### ISSUE THREAD

**Issue by niderhoff** [conda/conda#8986]
Hello,

is there a way to find out which packages of `conda list` have been installed directly/manually been requested using the `conda install` command as opposed to dependencies installed by conda automatically?

**Comment by soapy1** [comment]
I don't believe there is a convenient command for this but you can find this information out. You can see what conda has installed from the history file in your conda environments meta directory. It's located in `$ENV_PATH/conda-meta/history`. This will tell you the commands that have run for that environment so should list the explicit specs that you directly installed and the dependencies that were additionally installed.

**Comment by niderhoff** [comment]
hey did you mean `$CONDA_PREFIX/conda-meta/history`? I have no variable that's called $ENV_PATH. Looks like this so it might be possible to extract the necessary infos using awk and grep.

```
# update specs: ['python=3.7', 'tensorflow-gpu', 'jupyterlab', 'pip', 'opencv']
==> 2020-01-27 12:59:57 <==
# cmd: /home/niid/miniconda3/bin/conda install matplotlib
# conda version: 4.7.12
+conda-forge::cycler-0.10.0-py_2
+conda-forge::kiwisolver-1.1.0-py37hc9558a2_0
+conda-forge::matplotlib-3.1.2-py37_1
+conda-forge::matplotlib-base-3.1.2-py37h250f245_1
+conda-forge::pyparsing-2.4.6-py_0
+conda-forge::pyqt-5.12.3-py37hcca6a23_1
# update specs: ['matplotlib']
==> 2020-01-27 13:01:23 <==
# cmd: /home/niid/miniconda3/bin/conda install tensorflow-hub
# conda version: 4.7.12
+conda-forge::tensorflow-hub-0.7.0-pyhe1b5a44_0
# update specs: ['tensorflow-hub']
==> 2020-01-27 13:02:00 <==
# cmd: /home/niid/miniconda3/bin/conda install pandas
# conda version: 4.7.12
+conda-forge::pandas-0.25.3-py37hb3f55d8_0
+conda-forge::pytz-2019.3-py_0
# update specs: ['pandas']
(mobile) root@59afc2d80274:/home/niid#
[0] 0:python3.7- 1:bash*                                                         "59afc2d
```

**Comment by KingDarBoja** [comment]
Something like my [comment](https://github.com/conda/conda/issues/4339#issuecomment-559638258) should help. Unfortunately, you don't get the build version by using this approach.

**Comment by niderhoff** [comment]
So I found this gem in [Twitter](https://twitter.com/xhochy/status/1199405251280936960), seems like it finally solves it:

`conda env Export --from_history`
