### ISSUE TITLE
cannot install package with name ending '.conda' using 4.7

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#8987]
We have a noarch python package named `garpy.conda` and have discovered after upgrading to 4.7 that we can no longer install it:

```sh
$ conda install -c our-channel garpy.conda
...
PathNotFoundError: /Users/cbarber/garpy.conda
```

If I give it an explicit version number, then it fails in the normal way for a package that does not exist on the channel (although it does).

We have observed this on 4.7.5, 4.7.8 and 4.7.10.

It also occurs on an empty python package named 'foo.conda'.

It looks like there is something broken in the parsing of package names!

**Comment by andrew-schweitzer-analog** [comment]
'foo.condar' and 'foo.cond' both work.

**Comment by msarahan** [comment]
.conda is the extension of the new package format.  Some more details at https://github.com/conda/conda-package-handling, https://www.anaconda.com/how-we-made-conda-faster-4-7/

Conda thinks you are trying to install a .conda file.  Sorry, I don't think there's any way to fix this on our side.  Your package name will probably need to change.

**Comment by msarahan** [comment]
I take that back. If we fail to find a matching filename locally, we could try to treat it as a package name, but I'm not sure that's really a good behavior.

**Comment by analog-cbarber** [comment]
Well `foo.conda` is a perfectly valid package name according to the specification (so is `foo.tar.bz2`for that matter).

Either you need to document that those names are no longer valid, which would be an incompatible change or you need to support them.

Since installing directly from a package file is not the normal use case, it seems like it would be perfectly fine to treat it as a package name if there is no actual file with that name. Furthermore, if I write 'foo.conda =1.2.3', why should it interpret that as a filename in any case?

It really would be a lot clearer if you required an explicit syntax to install from a file, e.g.:

~~~sh
$ conda install --from-file foo.conda
~~~

That way there would be no ambiguity.

**Comment by msarahan** [comment]
Yep, sorry, we are not perfect.  We will document this change.  CC @rrigdon 

The behavior of installing from a file path is way too old to change.  Someone has to get the short end of the stick, and packages named *.conda are not common - yours is the first I've seen in 4 years of this ecosystem.  It seems to be a standard practice inside your company, though.  If you'd like to contribute a fix for treating it as a package name, we'd be glad to review it.  We will not accept just moving the file to an explicit flag, though.

**Comment by analog-cbarber** [comment]
We only have one package named `*.conda` so we can probably just rename it.

Going forward please document what package names will be valid for ALL future versions of conda!

This is third time that a new conda release has had a bug or undocumented incompatible change that has broken our code. I really would like to push conda within our company, but every time something like this happens our users get the impression that conda is more trouble than its worth.

**Comment by analog-cbarber** [comment]
Are there other places where packages with name `*.conda` will not work? It seems that it is ok as a package dependency, so we don't necessarily have to fix all recipes that depend on this.

Can we work around this simply be making an empty package with a new name that depends on our `garpy.conda` package?

**Comment by analog-cbarber** [comment]
It appears that I also cannot uninstall *.conda packages from existing environments:

~~~sh
$ garpy.conda$ conda list | grep garpy.conda
garpy.conda               0.1.13.dev7                py_0    local
$ conda uninstall garpy.conda
PackagesNotFoundError: The following packages are missing from the target environment:
  - garpy.conda
~~~

Is there a workaround?

**Comment by analog-cbarber** [comment]
I guess the workaround is to downgrade to 4.6.

**Comment by andrew-schweitzer-analog** [comment]
Sometimes you cannot downgrade if you have such a package installed. :)

I have discovered that you can uninstall such a package by appending '*' to the package name. So this works for me: 
```
conda remove garpy.conda*
```
