### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by pieterjanvc** [conda/conda#8989]
Hi,

I aligned a metagenomic file with MEGAHIT, but found this in my error report. It requested to be submitted as an issue so I'm dutifully doing so :) 

[errorReport.txt](https://github.com/conda/conda/files/3427564/errorReport.txt)

**Comment by msarahan** [comment]
Sorry, I'm not sure what to do about this.  This part:

``ValueError: failed to parse CPython sys.version: '3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) \n[GCC 7.3.0]'`` possibly suggests a very old conda being used with a very new python version.  If you can run ``conda info`` that will tell us more.  It will also help if you understand how MEGAHIT is calling conda, since it seems like you are not calling conda yourself.

**Comment by pieterjanvc** [comment]
Hi,

Now that's a fast reply ....
I'm using anaconda (anaconda 3) because it's needed for some analysis later on in the script using the AMRFinder tool. The output from MEGAHIT seems as expected, so I'm not too worried about this error, just sharing because the output asked to.

Here's the conda info
`
     active environment : None
       user config file : /users/van9wf/.condarc
 populated config files :
          conda version : 4.7.5
    conda-build version : 3.4.1
         python version : 3.6.8.final.0
       virtual packages :
       base environment : /usr/local/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /users/van9wf/.conda/pkgs
       envs directories : /users/van9wf/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.18.4 CPython/3.6.8 Linux/2.6.32-696.18.7.el6.centos.plus.x86_64 centos/6.10 glibc/2.12
                UID:GID : 41805:10000
             netrc file : None
           offline mode : False
`

**Comment by pieterjanvc** [comment]
Hi,

I was able to fix the issue. For some reason running MEGAHIT would interfere with other software downstream in my script that uses python. I simply unloaded the model from my environment after MEGAHIT finished and it solved the issue.

> module load megahit
megahit --12 sample.fastq.gz -o megahitOutput
module unload megahit

**Comment by msarahan** [comment]
Great, glad to see it.  I'll close this out.
