### ISSUE TITLE
Update diagram of package filename

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#9005]
The explanation of [a package's filename]( https://docs.conda.io/projects/conda-build/en/latest/concepts/package-naming-conv.html#index-4 ) currently doesn't show the hash or that the build number is within the string. This could be useful info for people just starting to wrap their heads around how this works. Also it might be worth noting the `.conda` extension.

**Comment by rrigdon** [comment]
I added in more content around our new .conda file format and the role that the hash and build number play. I chose to keep the graphic the same as the surrounding information clarifies that it is an example of one type of filename.

**Comment by jakirkham** [comment]
Thanks for working on this, @rrigdon 🙂
