### ISSUE TITLE
How to research known Security Issues fixed/open in each version of Anaconda/miniconda?

### ISSUE THREAD

**Issue by Michael-Angel-Sec** [conda/conda#9012]
The release notes for anaconda and miniconda appear to not mention CVEs and Security vulnerabilities.  

How can we determine which versions updates have security patches?
How do we find out which versions have Python3.x published CVE fixes?

conda release notes:
https://github.com/conda/conda/blob/master/CHANGELOG.md

For example, here is the list of published CVEs for Python 3.7.x.

https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe%3a%2fa%3apython%3apython%3a3.7.0

**Comment by msarahan** [comment]
CVE information is available to our Anaconda Enterprise customers.  We do not publish information for our free products.
