### ISSUE TITLE
Conda broke itself

### ISSUE THREAD

**Issue by MCM-Math** [conda/conda#9022]
I updated conda

`conda update conda-build`

Afterwards, I tried to install "python-pptx":

'conda install -y -c conda-forge python-pptx'

This command usually works, but instead of trying to install this package, it tries to update conda.  After that, I get messages like _"PackagesNotFoundError: The following packages are missing from the target environment:
  - conda-forge::certifi==2019.3.9=py37_0
  - conda-forge::conda-package-handling==1.3.11=py37_0
  - conda-forge::conda==4.7.5=py37_0"_

EDIT: I managed to get it functional again, with some tinkering with rollbacks, but there is definitely a bug in there.

**Comment by MCM-Math** [comment]
Okay, it broke itself again.  It seems to be random.

**Comment by msarahan** [comment]
Please fill out all the information requested in the issue template.  We can't help you without it.
