### ISSUE TITLE
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.

### ISSUE THREAD

**Issue by zeronicyber** [conda/conda#9033]
Issue is a bug report for conda command

## Current Behavior
 4.7.10-py36_0
    menuinst:               1.4.10-py36h42196fb_0 --> 1.4.14-py36hfa6e2cd_0
    openssl:                1.0.2l-vc14hcac20b0_2 --> 1.0.2p-hfa6e2cd_0
    pycosat:                0.6.2-py36hf17546d_1  --> 0.6.3-py36hfa6e2cd_0

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\miniconda3\Scripts\conda.exe
Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\miniconda3\Scripts\conda.exe

### Steps to Reproduce
1. Install Miniconda3-4.3.30-Windows-x86_64.exe as user or admin.
2. Once it is installed, run conda update conda or conda install _license

## Expected Behavior
3. CondaError: Cannot link a source that does not exist. C:\miniconda3\Scripts\conda.exe

## Environment Information
(C:\miniconda3) C:\Users\AMUTHUKU>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\miniconda3  (writable)
    default environment : C:\miniconda3
       envs directories : C:\miniconda3\envs
                          C:\Users\AMUTHUKU\AppData\Local\conda\conda\envs
                          C:\Users\AMUTHUKU\.conda\envs
          package cache : C:\miniconda3\pkgs
                          C:\Users\AMUTHUKU\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : False

<details open><summary><code>`conda config --show-sources`</code></summary><p>
(C:\miniconda3) C:\Users\AMUTHUKU>conda config --show-sources

(C:\miniconda3) C:\Users\AMUTHUKU>

(C:\miniconda3) C:\Users\AMUTHUKU>conda list --show-channel-urls
# packages in environment at C:\miniconda3:
#
asn1crypto                0.22.0           py36h8e79faa_1    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
certifi                   2017.7.27.1      py36h043bc9e_0    defaults
cffi                      1.10.0           py36hae3d1b5_1    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
conda                     4.3.27           py36hcbae3bd_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.0.3            py36h123decb_1    defaults
distlib                   0.2.5            py36h51371be_0    defaults
html5lib                  0.999999999      py36ha09b1f3_0    defaults
idna                      2.6              py36h148d497_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
msgpack-python            0.4.8            py36h58b1e9d_0    defaults
openssl                   1.0.2l           vc14hcac20b0_2  [vc14]  defaults
packaging                 16.8             py36ha0986f6_1    defaults
pip                       9.0.1            py36hadba87b_3    defaults
progress                  1.3              py36hbeca8d3_0    defaults
pycosat                   0.6.2            py36hf17546d_1    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.2.0           py36h15ca2fc_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
python                    3.6.3                h9e2ca53_1    defaults
pywin32                   221              py36h9c10281_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
six                       1.10.0           py36h2c0fdd8_1    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_1    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
wheel                     0.29.0           py36h6ce6cde_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7            vc14hb31d195_1  [vc14]  defaults

(C:\miniconda3) C:\Users\AMUTHUKU>

**Comment by Bezier89** [comment]
@zeronicyber I've hit this issue before. It's not a great solution, but as a workaround you can install tqdm=4.31, it doesn't seem to experience this issue. I wonder if it has something to do with the new tqdm=4.32 package being noarch.

**Comment by zeronicyber** [comment]
@bezier89 I want to install _license package n tqdm-4.32 is the dependency.. tqdm has to develop package which is working with conda. Or conda has to drop this package from dependency.

**Comment by kiatng** [comment]
I run into the same issue. Installing tqdm=4.31 had the same issue:

> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::tqdm-4.34.0-py_0'.
CondaError: Cannot link a source that does not exist. D:\Work\Anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
> CondaError: Cannot link a source that does not exist. D:\Work\Anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

> D:\Work\Anaconda>conda install -c conda-forge tqdm=4.31
Fetching package metadata .................
Solving package specifications: .
> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::tqdm-4.31.1-py_0'.
CondaError: Cannot link a source that does not exist. D:\Work\Anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

**Comment by antvig** [comment]
I have the same issue : 

```
>conda update conda
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\anaconda:

The following NEW packages will be INSTALLED:

    conda-package-handling: 1.3.11-py36_0         win-64/
    libarchive:             3.3.3-h798a506_1      win-64/
    lz4-c:                  1.8.1.2-h2fa13f4_0    win-64/
    lzo:                    2.10-h6df0209_2
    python-libarchive-c:    2.8-py36_11           win-64/
    tqdm:                   4.32.1-py_0           win-64/
    xz:                     5.2.4-h2fa13f4_4
    zstd:                   1.3.3-hfe6a214_0      win-64/

The following packages will be UPDATED:

    conda:                  4.3.27-py36hcbae3bd_0         --> 4.7.10-py36_0         win-64/
    libxml2:                2.9.4-vc14h8fd0f11_5          --> 2.9.9-h464c3ec_0      win-64/
    menuinst:               1.4.8-py36h870ab7d_0          --> 1.4.16-py36he774522_0
    openssl:                1.0.2l-vc14hcac20b0_2         --> 1.0.2s-he774522_0     win-64/
    pycosat:                0.6.2-py36hf17546d_1          --> 0.6.3-py36hfa6e2cd_0
    vc:                     14-h2379b0c_1                 --> 14.1-h21ff451_3       win-64/
    vs2015_runtime:         14.0.25123-hd4c4e62_1         --> 15.5.2-3              win-64/

Proceed ([y]/n)? y

menuinst-1.4.1 100% |###############################| Time: 0:00:00 980.06 kB/s
vs2015_runtime 100% |###############################| Time: 0:00:02   1.07 MB/s
vc-14.1-h21ff4 100% |###############################| Time: 0:00:00   1.56 MB/s
lz4-c-1.8.1.2- 100% |###############################| Time: 0:00:00 681.22 kB/s
lzo-2.10-h6df0 100% |###############################| Time: 0:00:00   1.90 MB/s
openssl-1.0.2s 100% |###############################| Time: 0:00:04   1.50 MB/s
xz-5.2.4-h2fa1 100% |###############################| Time: 0:00:00   1.41 MB/s
libxml2-2.9.9- 100% |###############################| Time: 0:00:02   1.45 MB/s
pycosat-0.6.3- 100% |###############################| Time: 0:00:00 796.81 kB/s
tqdm-4.32.1-py 100% |###############################| Time: 0:00:00 518.06 kB/s
zstd-1.3.3-hfe 100% |###############################| Time: 0:00:00   1.66 MB/s
libarchive-3.3 100% |###############################| Time: 0:00:02   1.57 MB/s
python-libarch 100% |###############################| Time: 0:00:00 241.38 kB/s
conda-package- 100% |###############################| Time: 0:00:00 819.60 kB/s
conda-4.7.10-p 100% |###############################| Time: 0:00:01   1.63 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'win-64/::tqdm-4.32.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\anaconda\Scripts\conda.exe
Attempting to roll back.


CondaError: Cannot link a source that does not exist. C:\anaconda\Scripts\conda.exe
```


Current conda config : 

```
C:\~\>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.22.0
       root environment : C:\anaconda  (writable)
    default environment : C:\anaconda
       envs directories : C:\anaconda\envs
                          C:\Users\SESA408771\AppData\Local\conda\conda\envs
                          C:\Users\SESA408771\.conda\envs
          package cache : C:\anaconda\pkgs
                          C:\Users\SESA408771\AppData\Local\conda\conda\pkgs
           channel URLs : https://pypi-analytics-read:XxirTpDBkKAojmVJsUzLafY19lnRQEwO@nexus.tools.struxurewarecloud.com/repository/anaconda-repo/win-64/win-64
                          https://pypi-analytics-read:XxirTpDBkKAojmVJsUzLafY19lnRQEwO@nexus.tools.struxurewarecloud.com/repository/anaconda-repo/win-64/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\SESA408771\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.22.0 CPython/3.6.2 Windows/10 Windows/10.0.17134
          administrator : True

```

**Comment by Jayleelwj** [comment]
The same issue I have:
`Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment D:\Anaconda:

The following NEW packages will be INSTALLED:

    blas:                   1.0-mkl
    blosc:                  1.17.0-h6538335_1                 conda-forge
    ca-certificates:        2019.9.11-hecc5488_0              conda-forge
    certifi:                2019.9.11-py36_0                  conda-forge
    conda-package-handling: 1.4.1-py36_0                      conda-forge
    dask-core:              2.6.0-py_0                        conda-forge
    icc_rt:                 2019.0.0-h0cc432a_1
    imageio:                2.6.1-py36_0                      conda-forge
    intel-openmp:           2019.4-245
    joblib:                 0.14.0-py_0                       conda-forge
    kiwisolver:             1.1.0-py36he980bc4_0              conda-forge
    libarchive:             3.3.3-hd1ea8e3_1002               conda-forge
    libblas:                3.8.0-14_mkl                      conda-forge
    libcblas:               3.8.0-14_mkl                      conda-forge
    libiconv:               1.15-hfa6e2cd_1005                conda-forge
    liblapack:              3.8.0-14_mkl                      conda-forge
    libxml2:                2.9.10-h9ce36c8_0                 conda-forge
    lz4-c:                  1.8.1.2-vc14_0                    conda-forge
    lzo:                    2.10-hfa6e2cd_1000                conda-forge
    mock:                   3.0.5-py36_0                      conda-forge
    pyreadline:             2.1-py36_1001                     conda-forge
    pysocks:                1.7.1-py36_0                      conda-forge
    python-libarchive-c:    2.9-py36_0                        conda-forge
    quaternion:             2019.10.3.10.26.21-py36hc8d92b1_0 conda-forge
    tqdm:                   4.36.1-py_0                       conda-forge
    urllib3:                1.25.6-py36_0                     conda-forge
    win_inet_pton:          1.1.0-py36_0                      conda-forge
    wincertstore:           0.2-py36_1003                     conda-forge
    xz:                     5.2.4-h2fa13f4_1001               conda-forge
    zstd:                   1.3.3-vc14_1                      conda-forge

The following packages will be UPDATED:

    anaconda:               4.4.0-np112py36_0                             --> custom-py36_0
    astropy:                1.3.2-np112py36_0                             --> 2.0.16-py36hfa6e2cd_0         conda-forge
    bottleneck:             1.2.1-np112py36_0                             --> 1.2.1-py36hc8d92b1_1001       conda-forge
    conda:                  4.3.30-py36h7e176b0_0                         --> 4.7.12-py36_0                 conda-forge
    conda-env:              2.6.0-0                                       --> 2.6.0-1                       conda-forge
    freetype:               2.5.5-vc14_2                                  --> 2.8.1-ha63716d_1              conda-forge
    h5py:                   2.7.0-np112py36_0                             --> 2.10.0-nompi_py36h422b98e_100 conda-forge
    hdf5:                   1.8.15.1-vc14_4                               --> 1.10.5-nompi_hcc15c50_1101    conda-forge
    libpng:                 1.6.27-vc14_0                                 --> 1.6.37-h7602738_0             conda-forge
    libtiff:                4.0.6-vc14_3                                  --> 4.0.9-hf1753bf_1              conda-forge
    llvmlite:               0.18.0-py36_0                                 --> 0.24.0-py36_1                 conda-forge
    matplotlib:             2.0.2-np112py36_0                             --> 2.2.2-py36h153e9ff_0
    menuinst:               1.4.7-py36_0                                  --> 1.4.16-py36_0                 conda-forge
    mkl:                    2017.0.1-0                                    --> 2019.4-245
    numba:                  0.33.0-np112py36_0                            --> 0.39.0-py36h830ac7b_0
    numexpr:                2.6.2-np112py36_0                             --> 2.7.0-py36h6538335_0          conda-forge
    numpy:                  1.12.1-py36_0                                 --> 1.17.3-py36hc71023c_0         conda-forge
    openssl:                1.0.2l-vc14_0                                 --> 1.0.2r-hfa6e2cd_0             conda-forge
    pandas:                 0.20.1-np112py36_0                            --> 0.24.2-py36he350917_0         conda-forge
    pillow:                 4.1.1-py36_0                                  --> 5.0.0-py36_0                  conda-forge
    pycosat:                0.6.2-py36_0                                  --> 0.6.3-py36hfa6e2cd_1002       conda-forge
    pytables:               3.2.2-np112py36_4                             --> 3.5.2-py36h26f9782_1          conda-forge
    pywavelets:             0.5.2-np112py36_0                             --> 1.1.1-py36hc8d92b1_0          conda-forge
    requests:               2.14.2-py36_0                                 --> 2.22.0-py36_1                 conda-forge
    scikit-image:           0.13.0-np112py36_0                            --> 0.14.2-py36h6538335_0         conda-forge
    scikit-learn:           0.18.1-np112py36_1                            --> 0.21.3-py36h7208079_0         conda-forge
    scipy:                  0.19.0-np112py36_0                            --> 1.2.1-py36h29ff71c_0
    setuptools:             27.2.0-py36_1                                 --> 41.6.0-py36_1                 conda-forge
    statsmodels:            0.8.0-np112py36_0                             --> 0.10.1-py36hfa6e2cd_1         conda-forge
    zlib:                   1.2.8-vc14_3                                  --> 1.2.11-h2fa13f4_1004          conda-forge

Proceed ([y]/n)? y

blas-1.0-mkl.t 100% |###############################| Time: 0:00:00   3.20 MB/s
icc_rt-2019.0. 100% |###############################| Time: 0:00:03   2.73 MB/s
intel-openmp-2 100% |###############################| Time: 0:00:00   7.58 MB/s
mkl-2019.4-245 100% |###############################| Time: 0:01:00   2.75 MB/s
blosc-1.17.0-h 100% |###############################| Time: 0:00:00  25.50 MB/s
libblas-3.8.0- 100% |###############################| Time: 0:00:02   1.50 MB/s
anaconda-custo 100% |###############################| Time: 0:00:00   7.06 MB/s
dask-core-2.6. 100% |###############################| Time: 0:00:00  27.32 MB/s
hdf5-1.10.5-no 100% |###############################| Time: 0:00:12   2.98 MB/s
kiwisolver-1.1 100% |###############################| Time: 0:00:00  15.55 MB/s
libcblas-3.8.0 100% |###############################| Time: 0:00:01   2.16 MB/s
liblapack-3.8. 100% |###############################| Time: 0:00:01   2.48 MB/s
libpng-1.6.37- 100% |###############################| Time: 0:00:00  11.92 MB/s
libtiff-4.0.9- 100% |###############################| Time: 0:00:00   2.05 MB/s
llvmlite-0.24. 100% |###############################| Time: 0:00:03   3.15 MB/s
pyreadline-2.1 100% |###############################| Time: 0:00:00   1.87 MB/s
freetype-2.8.1 100% |###############################| Time: 0:00:00   5.56 MB/s
mock-3.0.5-py3 100% |###############################| Time: 0:00:00  22.58 MB/s
bottleneck-1.2 100% |###############################| Time: 0:00:00  19.48 MB/s
h5py-2.10.0-no 100% |###############################| Time: 0:00:00   1.14 MB/s
joblib-0.14.0- 100% |###############################| Time: 0:00:00   1.14 MB/s
numba-0.39.0-p 100% |###############################| Time: 0:00:00  19.84 MB/s
numexpr-2.7.0- 100% |###############################| Time: 0:00:00 889.35 kB/s
pandas-0.24.2- 100% |###############################| Time: 0:00:03   3.28 MB/s
pillow-5.0.0-p 100% |###############################| Time: 0:00:00  20.93 MB/s
pywavelets-1.1 100% |###############################| Time: 0:00:02   1.72 MB/s
scipy-1.2.1-py 100% |###############################| Time: 0:00:04   2.97 MB/s
astropy-2.0.16 100% |###############################| Time: 0:00:02   2.83 MB/s
imageio-2.6.1- 100% |###############################| Time: 0:00:00   6.20 MB/s
matplotlib-2.2 100% |###############################| Time: 0:00:02   3.02 MB/s
pytables-3.5.2 100% |###############################| Time: 0:00:00   3.19 MB/s
scikit-learn-0 100% |###############################| Time: 0:00:01   3.36 MB/s
statsmodels-0. 100% |###############################| Time: 0:00:03   2.57 MB/s
scikit-image-0 100% |###############################| Time: 0:00:08   2.85 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::tqdm-4.36.1-py_0'.
CondaError: Cannot link a source that does not exist. D:\Anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.


CondaError: Cannot link a source that does not exist. D:\Anaconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.`

**Comment by hannesleipold2** [comment]
I tried all the above and also removed conda-forge from my channels. After this I had a similar problem except now it said 'default::tqdm-4.36-py_0' in the error. After that I tried `conda install tqdm=4.19` (after looking up all the versions of tqdm and randomly selecting an older one). This seemed to fix the issue for me. I was able to run `conda install conda` after that. I had some problem stemming from matplotlib, but I was able to fix that by running `conda install matplotlib`.

**Comment by ssinghai9** [comment]
I tried installing old version and few other version mentioned above but nothing worked for me.
Finally "conda install tqdm -f" worked for me which installed tqdm: 4.36.1-py_0

**Comment by Bella722** [comment]
first: 
`conda install tqdm -f`
second: 
`conda update conda`

**Comment by casperdcl** [comment]
looks like the `tqdm==4.32` conda package is somehow broken. Are any other version broken? The latest is `4.40.0`

**Comment by casperdcl** [comment]
I regularly have issues with `requests` and `conda`. My usual solution is

```
conda update --force conda
```

**Comment by carthurs** [comment]
> 
> 
> looks like the `tqdm==4.32` conda package is somehow broken. Are any other version broken? The latest is `4.40.0`

I had this issue with 4.39 too.

**Comment by casperdcl** [comment]
Yeah considering that `4.39` was actually released shortly after `conda-forge` admins themselves tinkered with the package (https://github.com/conda-forge/tqdm-feedstock/pulls?q=is%3Apr+is%3Aclosed), that's concerning. My feeling is it's probably the same solution as the `requests` version conflicts I get (https://github.com/conda/conda/issues/8149)

- for some reason a conda package is updated/downgraded to a version that conflicts with `conda`'s dependencies
- `conda update` attempts to update this conflicting dependency
- the update process includes attempting to uninstall the current version, which throws an error since `conda` won't uninstall it's dependencies. Or the update process somehow otherwise fails.

`conda update --force conda` or even `conda deactivate` (a few times to make sure you're out of the base env) and the `conda update -n <name_of_env> --all` should work...

**Comment by Nickl55** [comment]
> first:
> `conda install tqdm -f`
> second:
> `conda update conda`

it worked! i love you! haha thanks

**Comment by greatlse** [comment]
> The same issue I have:
> `Fetching package metadata ...............
> Solving package specifications: .
> 
> Package plan for installation in environment D:\Anaconda:
> 
> The following NEW packages will be INSTALLED:
> 
> ```
> blas:                   1.0-mkl
> blosc:                  1.17.0-h6538335_1                 conda-forge
> ca-certificates:        2019.9.11-hecc5488_0              conda-forge
> certifi:                2019.9.11-py36_0                  conda-forge
> conda-package-handling: 1.4.1-py36_0                      conda-forge
> dask-core:              2.6.0-py_0                        conda-forge
> icc_rt:                 2019.0.0-h0cc432a_1
> imageio:                2.6.1-py36_0                      conda-forge
> intel-openmp:           2019.4-245
> joblib:                 0.14.0-py_0                       conda-forge
> kiwisolver:             1.1.0-py36he980bc4_0              conda-forge
> libarchive:             3.3.3-hd1ea8e3_1002               conda-forge
> libblas:                3.8.0-14_mkl                      conda-forge
> libcblas:               3.8.0-14_mkl                      conda-forge
> libiconv:               1.15-hfa6e2cd_1005                conda-forge
> liblapack:              3.8.0-14_mkl                      conda-forge
> libxml2:                2.9.10-h9ce36c8_0                 conda-forge
> lz4-c:                  1.8.1.2-vc14_0                    conda-forge
> lzo:                    2.10-hfa6e2cd_1000                conda-forge
> mock:                   3.0.5-py36_0                      conda-forge
> pyreadline:             2.1-py36_1001                     conda-forge
> pysocks:                1.7.1-py36_0                      conda-forge
> python-libarchive-c:    2.9-py36_0                        conda-forge
> quaternion:             2019.10.3.10.26.21-py36hc8d92b1_0 conda-forge
> tqdm:                   4.36.1-py_0                       conda-forge
> urllib3:                1.25.6-py36_0                     conda-forge
> win_inet_pton:          1.1.0-py36_0                      conda-forge
> wincertstore:           0.2-py36_1003                     conda-forge
> xz:                     5.2.4-h2fa13f4_1001               conda-forge
> zstd:                   1.3.3-vc14_1                      conda-forge
> ```
> 
> The following packages will be UPDATED:
> 
> ```
> anaconda:               4.4.0-np112py36_0                             --> custom-py36_0
> astropy:                1.3.2-np112py36_0                             --> 2.0.16-py36hfa6e2cd_0         conda-forge
> bottleneck:             1.2.1-np112py36_0                             --> 1.2.1-py36hc8d92b1_1001       conda-forge
> conda:                  4.3.30-py36h7e176b0_0                         --> 4.7.12-py36_0                 conda-forge
> conda-env:              2.6.0-0                                       --> 2.6.0-1                       conda-forge
> freetype:               2.5.5-vc14_2                                  --> 2.8.1-ha63716d_1              conda-forge
> h5py:                   2.7.0-np112py36_0                             --> 2.10.0-nompi_py36h422b98e_100 conda-forge
> hdf5:                   1.8.15.1-vc14_4                               --> 1.10.5-nompi_hcc15c50_1101    conda-forge
> libpng:                 1.6.27-vc14_0                                 --> 1.6.37-h7602738_0             conda-forge
> libtiff:                4.0.6-vc14_3                                  --> 4.0.9-hf1753bf_1              conda-forge
> llvmlite:               0.18.0-py36_0                                 --> 0.24.0-py36_1                 conda-forge
> matplotlib:             2.0.2-np112py36_0                             --> 2.2.2-py36h153e9ff_0
> menuinst:               1.4.7-py36_0                                  --> 1.4.16-py36_0                 conda-forge
> mkl:                    2017.0.1-0                                    --> 2019.4-245
> numba:                  0.33.0-np112py36_0                            --> 0.39.0-py36h830ac7b_0
> numexpr:                2.6.2-np112py36_0                             --> 2.7.0-py36h6538335_0          conda-forge
> numpy:                  1.12.1-py36_0                                 --> 1.17.3-py36hc71023c_0         conda-forge
> openssl:                1.0.2l-vc14_0                                 --> 1.0.2r-hfa6e2cd_0             conda-forge
> pandas:                 0.20.1-np112py36_0                            --> 0.24.2-py36he350917_0         conda-forge
> pillow:                 4.1.1-py36_0                                  --> 5.0.0-py36_0                  conda-forge
> pycosat:                0.6.2-py36_0                                  --> 0.6.3-py36hfa6e2cd_1002       conda-forge
> pytables:               3.2.2-np112py36_4                             --> 3.5.2-py36h26f9782_1          conda-forge
> pywavelets:             0.5.2-np112py36_0                             --> 1.1.1-py36hc8d92b1_0          conda-forge
> requests:               2.14.2-py36_0                                 --> 2.22.0-py36_1                 conda-forge
> scikit-image:           0.13.0-np112py36_0                            --> 0.14.2-py36h6538335_0         conda-forge
> scikit-learn:           0.18.1-np112py36_1                            --> 0.21.3-py36h7208079_0         conda-forge
> scipy:                  0.19.0-np112py36_0                            --> 1.2.1-py36h29ff71c_0
> setuptools:             27.2.0-py36_1                                 --> 41.6.0-py36_1                 conda-forge
> statsmodels:            0.8.0-np112py36_0                             --> 0.10.1-py36hfa6e2cd_1         conda-forge
> zlib:                   1.2.8-vc14_3                                  --> 1.2.11-h2fa13f4_1004          conda-forge
> ```
> 
> Proceed ([y]/n)? y
> 
> blas-1.0-mkl.t 100% |###############################| Time: 0:00:00 3.20 MB/s
> icc_rt-2019.0. 100% |###############################| Time: 0:00:03 2.73 MB/s
> intel-openmp-2 100% |###############################| Time: 0:00:00 7.58 MB/s
> mkl-2019.4-245 100% |###############################| Time: 0:01:00 2.75 MB/s
> blosc-1.17.0-h 100% |###############################| Time: 0:00:00 25.50 MB/s
> libblas-3.8.0- 100% |###############################| Time: 0:00:02 1.50 MB/s
> anaconda-custo 100% |###############################| Time: 0:00:00 7.06 MB/s
> dask-core-2.6. 100% |###############################| Time: 0:00:00 27.32 MB/s
> hdf5-1.10.5-no 100% |###############################| Time: 0:00:12 2.98 MB/s
> kiwisolver-1.1 100% |###############################| Time: 0:00:00 15.55 MB/s
> libcblas-3.8.0 100% |###############################| Time: 0:00:01 2.16 MB/s
> liblapack-3.8. 100% |###############################| Time: 0:00:01 2.48 MB/s
> libpng-1.6.37- 100% |###############################| Time: 0:00:00 11.92 MB/s
> libtiff-4.0.9- 100% |###############################| Time: 0:00:00 2.05 MB/s
> llvmlite-0.24. 100% |###############################| Time: 0:00:03 3.15 MB/s
> pyreadline-2.1 100% |###############################| Time: 0:00:00 1.87 MB/s
> freetype-2.8.1 100% |###############################| Time: 0:00:00 5.56 MB/s
> mock-3.0.5-py3 100% |###############################| Time: 0:00:00 22.58 MB/s
> bottleneck-1.2 100% |###############################| Time: 0:00:00 19.48 MB/s
> h5py-2.10.0-no 100% |###############################| Time: 0:00:00 1.14 MB/s
> joblib-0.14.0- 100% |###############################| Time: 0:00:00 1.14 MB/s
> numba-0.39.0-p 100% |###############################| Time: 0:00:00 19.84 MB/s
> numexpr-2.7.0- 100% |###############################| Time: 0:00:00 889.35 kB/s
> pandas-0.24.2- 100% |###############################| Time: 0:00:03 3.28 MB/s
> pillow-5.0.0-p 100% |###############################| Time: 0:00:00 20.93 MB/s
> pywavelets-1.1 100% |###############################| Time: 0:00:02 1.72 MB/s
> scipy-1.2.1-py 100% |###############################| Time: 0:00:04 2.97 MB/s
> astropy-2.0.16 100% |###############################| Time: 0:00:02 2.83 MB/s
> imageio-2.6.1- 100% |###############################| Time: 0:00:00 6.20 MB/s
> matplotlib-2.2 100% |###############################| Time: 0:00:02 3.02 MB/s
> pytables-3.5.2 100% |###############################| Time: 0:00:00 3.19 MB/s
> scikit-learn-0 100% |###############################| Time: 0:00:01 3.36 MB/s
> statsmodels-0. 100% |###############################| Time: 0:00:03 2.57 MB/s
> scikit-image-0 100% |###############################| Time: 0:00:08 2.85 MB/s
> ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::tqdm-4.36.1-py_0'.
> CondaError: Cannot link a source that does not exist. D:\Anaconda\Scripts\conda.exe
> Running `conda clean --packages` may resolve your problem.
> Attempting to roll back.
> 
> CondaError: Cannot link a source that does not exist. D:\Anaconda\Scripts\conda.exe
> Running `conda clean --packages` may resolve your problem.`

the same issue

**Comment by fenglei1999** [comment]
> first:
> `conda install tqdm -f`
> second:
> `conda update conda`

That's worked,thank you very much!
