### ISSUE TITLE
optional automatic stacking

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#9036]
I like to put some common tools in my base environment rather than installing them on my machine using some other packaging mechanism and I don't want to have to add them to all my environments or have to switch back and forth or create extra shells. So my preferred practice is to use `--stack` to activate the environment when starting from base. It is easy to forget so, I wrote a bash function to automatically stack if the CONDA_SHLVL is less than 2:

~~~bash
use() {
   if [ ${CONDA_SHLVL:-0} -le 1 ]; then
      conda activate --stack $1
   else
      conda activate $1
   fi
}
~~~

This solves the problem for me, but it obviously would have to be adjusted based on your OS and shell. It would be nicer if this was just a conda config option. I don't know if there is a stong argument for autostacking more than one level but it would be easy enough to support if you wanted to.

**Comment by andrew-schweitzer-analog** [comment]
It looks like this behavior would be fairly straight forward to implement in activate.py by checking `new_conda_shlvl` at this line https://github.com/conda/conda/blob/master/conda/activate.py#L332. 

Conda people, does that seem right? If it's not much more complicated than that we could submit a PR. 

Thanks, 

Andy

**Comment by analog-cbarber** [comment]
Ok. I am working on this.

I will add a `auto_stack` config option that takes a max CONDA_SHLVL for which stacking will automatically be done. 0/False (default) turns off automatic stacking, 1/True just does one level of auto stacking (which is probably all most people will want).

I will also add a `--no-stack` option to `conda activate` so that there is a way to override auto stacking if you want.

**Comment by analog-cbarber** [comment]
See pull request https://github.com/conda/conda/pull/9168
