### ISSUE TITLE
Conda update/install not working !

### ISSUE THREAD

**Issue by singh13sagar** [conda/conda#9038]
I recently tried to open jupyter notebook but it did not work. So i tried doing conda update --all but it failed at solving environment. Now conda install or conda update conda won't even work. The following error is displayed:

Traceback (most recent call last):
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/Users/myComp/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 8, in <module>
    from .install import install
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/libarchive/entry.py", line 4, in <module>
    from ctypes import c_char_p, create_string_buffer
  File "/Users/myComp/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/myComp/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/myComp/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myComp/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/myComp/anaconda3/lib/python3.7/site-packages/libarchive/entry.py", line 4, in <module>
    from ctypes import c_char_p, create_string_buffer
  File "/Users/myComp/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/myComp/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/myComp/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

**Comment by singh13sagar** [comment]
The issue was fixed by reinstalling conda. However, root cause of that error is still unknown.

**Comment by tritemio** [comment]
I got the same error while installing/updating jupytext in the base environment. I may have mixed PIP and conda packages, no very clean I know. But the botton-line is some installation mistake  (mixing conda install/remove with pip install/remove) resulted in a breakage of conda install/remove, requiring a reinstallation.

I think it is an issue to address at some point. Let me know if I can provide more info.

**Comment by parmentelat** [comment]
same here; after upgrading conda with
```
conda update -n base -c defaults conda
```

all my `conda env` commands crash with this message

```
ImportError: dlopen(/Users/tparment/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/tparment/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found
```

I guess I'll reinstall conda then…

**Comment by gtesei** [comment]
I had the same problem and going under __/Users/<user_name>/miniconda3/lib__ I discovered that I had __libffi.7.dylib__ but not __libffi.6.dylib__. So I just created a symbolic link:
```sh
ln -s libffi.7.dylib libffi.6.dylib
``` 

which solved the issue.

**Comment by jjakenichol** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

That didn't work for me but reinstalling did. Looking into the lib directory, the latest version only contains libffi.6.dylib. Since this issue began for me right after updating conda, I suspect the update conda command is not replacing libffi.7.dylib correctly.

**Comment by discdiver** [comment]
Should this issue be reopened? Seems it is still a problem.

**Comment by horsto** [comment]
Similar problem here. MacOS Catalina. After updating to `conda 4.8.3` I could activate environments, but could not execute a `conda install` without running into this error: 
 
```
Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so 
Reason: image not found
```

running `ln -s libffi.7.dylib libffi.6.dylib` in folder `/opt/miniconda3/lib` fixed it for me (thanks @gtesei !).

**Comment by jjakenichol** [comment]
> Should this issue be reopened? Seems it is still a problem.

Yes, reinstalling is not a real solution. Creating a symlink to the wrong file seems worse.

**Comment by guillaume-heusch** [comment]
Same problem here with macOS High Sierra and after updating to conda 4.8.3
Using the simlink trick from @gtesei did work, but I agree that this should not be the solution ...

Thanks!

**Comment by Droneree** [comment]
Thanks for the discussions and answers here. I have a similar problem.
At first I was trying to update a python package using 'conda update' command. Then this catastrophic error paralysed my python related work. Hope for a better solution.

**Comment by discdiver** [comment]
@singh13sagar can you reopen this issue, please, or @kalefranz. Seems like 4.8.3 broke things for many Mac users. Not sure if that is on maintainers' radar and not sure the best way to flag it.

**Comment by pkuderov** [comment]
I have the same problem with Ubuntu after updating to conda 4.8.3
The trick from @gtesei did work for me too. As the name of the lib slightly differs for Linux, I had to update the script:

```bash
ln -s libffi.so.7 libffi.so.6
```

**Comment by hannah-trint** [comment]
I have the same problem after having run (as suggested when I created a new env):
`
conda update -n base -c defaults conda
`

This updated conda from 4.8.2 to 4.8.3.

I get the following error when running conda install, and even conda info:
`
ImportError: dlopen(/Users/hannahbacon/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/hannahbacon/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found
`
I haven't tried creating a symlink as suggested since that seems like it could cause more problems. Is there a way to downgrade my conda version?

Using pip in my conda environment is installing packages incorrectly I'm finding.

This issue should definitely be reopened!

**Comment by discdiver** [comment]
Pip in my conda environment is giving me lots of problems now, too. ☹️

**Comment by GPoloVera** [comment]
I have the same problem after updating conda (`conda update -n base conda`). I can't do any `conda info` command. I have a MacOS Catalina too.

**Comment by psthomas** [comment]
I'm experiencing the same error, on macOS Catalina 10.15.2. The problem began after I attempted to update Conda while in the base environment (`conda update conda`).

Running any command with Conda now results in the same error as many above:
```
ImportError: dlopen(/Users/psthomas/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
Referenced from: /Users/psthomas/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
Reason: image not found
```
I haven't tried the symlink option, but will probably just try reinstalling Miniconda instead.

**Comment by discdiver** [comment]
Reinstalling miniconda worked for me

**Comment by hannah-trint** [comment]
> Reinstalling miniconda worked for me

Doesn't this mean you lose all the environments you have created though? I'd rather not have to do that and wait for a fix!

**Comment by duguanyue** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

This worked for me , too.

**Comment by shikharsingla** [comment]
ln -s libffi.7.dylib libffi.6.dylib

this worked for me as well but this is not an ideal solution, can someone please reopen the issue?

**Comment by Lef-F** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

This solved it for me too on MacOS 10.15.4, but it should be fixed. 🙏 

```
conda version : 4.8.3
conda-build version : 3.18.11
python version : 3.7.7.final.0
```

**Comment by laurilli** [comment]
same. Had to reinstall anaconda as the symlink solution didn't work for me. 
Now I'm back in business but less than ideal. This happened today on MacOS Catalina after running
```conda update -n base -c defaults conda```

**Comment by grendeloz** [comment]
Same problem for me on my macOS Catalina 10.15.4.  "conda update conda" was the cause.

`cd miniconda/base/lib/
ln -s libffi.7.dylib libffi.6.dylib`

seems to fix it but that's a real bad solution.

**Comment by andfanilo** [comment]
Just here to also bump the issue, got it this morning on a CentOS 6.10 with ` conda update -n base -c defaults conda`, any `conda` command gives me `ImportError: libffi.so.7: ...`. 

Well I guess I'm reinstalling Miniconda and reconfiguring all the environments...

**Comment by pkuderov** [comment]
I guess investigation is here: #9899

**Comment by danmoore1987** [comment]
similarly here to point out the issue still exists.

**Comment by Fackor** [comment]
This issue still exists, please update when fixed.

**Comment by joehoeller** [comment]
Persistent on Mac OSX Mojave as well.

**Comment by jemisjoky** [comment]
Same issue with Mac OSX High Sierra after running `conda update -n base -c defaults conda`

**Comment by georg-cantor** [comment]
In MacOS Catalina 10.15.5
after 
`
brew cask upgrade anaconda
`
anaconda update to anaconda-2020.02，then the problem disappear.

**Comment by bouh2** [comment]
Same issue after updating conda package:
----------------------------------------------
Referenced from: /Users/<user>/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
Reason: image not found

Temp fixed with `ln -s libffi.7.dylib libffi.6.dylib` in ~/anaconda3/lib folder

**Comment by sshleifer** [comment]
I had that issue yesterday, but had both files. Then I restarted my computer and now I can't even cd into miniconda3/bin with zsh. Has anyone run into this?

**Comment by jrockwar** [comment]
Same issue here after upgrading to 4.8.3. Used the symbolic link as a workaround.

**Comment by jeongwhanchoi** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

this symbolic linking solves the above issue.
In my case, I have an error with libopenblas.dylib.
The below is the error log.
`Library not loaded: @libopenblas.dylib`
Then I could solve this error with the below command:
`ln -s libopenblas.0.dylib libopenblas.dylib`

**Comment by PearlW1** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

it do not work for me,  i create a new conda env, so sad

**Comment by ernests** [comment]
Same issue. Symlink worked for me

**Comment by mathfish** [comment]
Is there a path forward/fix for this? Just hosed my conda install as well upgrading conda base to 4.9.2 . . .

**Comment by Gtrstv** [comment]
I just had this happen to me. I installed Miniconda on my D:drive. It worked flawlessly for about 6 months until today. I stuck to environments stored in anaconda, but just last week I created some virtual environments. The premise sounds good, but Miniconda degraded fast after that. I wouldn't know where to look for a Symlink as I installed on my D drive. The good thing is I bought a larger c drive and can now move my Conda and VS Code to c drive. Thanks for the info. I'm just learning.

**Comment by jfaccioni** [comment]
Happened to me as well after updating conda today. Got `conda install` working again it by running

` ln -s libffi.so.7 libffi.so.6`

from the `~/miniconda3/lib` folder.

**Comment by hauselin** [comment]
Happened to me too after updating conda yesterday. 

I also fixed it by running `ln -s libffi.so.7 libffi.so.6` from the `/opt/anaconda3/lib` folder.

**Comment by f6v** [comment]
I ran into the same issue myself today on Big Sur. What's interesting is that I didn't perform any updates whatsoever. I might have installed a package or two into one of the environments, maybe even `base`. Creating symlink works for now though.

**Comment by Gtrstv** [comment]
I switched over to running MiniConda3 in a docker dev container with VS Code. It's not bad unless you have to add a package to your environment file. It takes about 30 minutes to spin up since cache is lost. I'm running a lot of packages since I'm studying several books at the same time.

**Comment by yxjsxy** [comment]
> I had the same problem and going under **/Users/<user_name>/miniconda3/lib** I discovered that I had **libffi.7.dylib** but not **libffi.6.dylib**. So I just created a symbolic link:
> 
> ```shell
> ln -s libffi.7.dylib libffi.6.dylib
> ```
> 
> which solved the issue.

You are damn good!!!

**Comment by Gtrstv** [comment]
I haven't had any issues since switching to linux docker containers. I did take a look at my Miniconda3 setup (outside of docker) and I only have libffi-7.dll. I'm only running Pyhton 3.7-3.9 for all the projects on my PC. I recreated some of the environments in docker, by copying my requirements from each project environment. The containers are great, since I can bring up different versions of pyrhon along with different package setups. The only bad thing is that every article I read tells me to do something different when creating a container. Its trial and error until you get something that works. It's a little easier now that there are base images for most container types. I need to learn more about security, then I'll open up my conda ennvironment.

**Comment by VladislavSmolyanoy** [comment]
For some reason I had libffi.8.dylib instead of libffi.7.dylib so I had to modify the command a bit: 
`ln -s libffi.8.dylib libffi.7.dylib`

**Comment by sammccants** [comment]
> Similar problem here. MacOS Catalina. After updating to `conda 4.8.3` I could activate environments, but could not execute a `conda install` without running into this error:
> 
> ```
> Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so 
> Reason: image not found
> ```
> 
> running `ln -s libffi.7.dylib libffi.6.dylib` in folder `/opt/miniconda3/lib` fixed it for me (thanks @gtesei !).

The problem still exists; I just encountered it after upgrading from `4.11.0` to `4.12.0`. The symlink fixed it for me

**Comment by wosiu** [comment]
Same for me after upgrading to conda 4.12 :(

**Comment by wosiu** [comment]
@singh13sagar could you please reopen to keep reports in a single ticket.

**Comment by sanurielf** [comment]
Same here after upgrading to conda-4.12.0

**Comment by zumoravc** [comment]
The same problem for me after updating to 4.12, the symbolic link fixed it (temporarily)

**Comment by aurelgriesser** [comment]
Symlink workaround worked for me. Mac OS 10.13.6, conda --version 4.13.0 (reported after applying the symlink fix, but I expected it'd still be 4.10.1 which I had before I did the `conda update -n base -c defaults conda` which caused the issue).

**Comment by catherine-martlin** [comment]
This appears to still be an issue for Mac OS 12.6 (21g115) with conda 4.12.0. I first tried reinstalling miniconda but that did not help; the symlink solution does help and I am able to use `conda` commands that were crashing now. Still seems not ideal to need to create the symlink.

**Comment by saulshanabrook** [comment]
For me running `brew upgrade miniconda` fixed it.

**Comment by codejoey** [comment]
Problem hit me today.

Symlink workaround seems unideal - especially with interactions from future updates.
I didn't install anaconda via brew so brew solution couldn't work for me.

What worked for me:
Found a copy of "libffi.6.dylib" file in one of my env's, and copied into my "/Users/Joey/anaconda3/lib/".
Please let me know if that is not ideal for some reason I didn't think of.
