### ISSUE TITLE
Removal of menus fails due to race condition

### ISSUE THREAD

**Issue by msarahan** [conda/conda#9043]
with parallel execution of "Execute Transactions" there was a bad side effect.  Because the removal of menus happens in parallel with other unlink actions, the menu removal was ending up in a situation where the python.exe that should have been there was not.  This caused scary looking dialog boxes on windows.  Ultimately, nothing terrible happens, but this is a pretty major wart.

**Comment by ashishbairwa** [comment]
How can i reproduce this error?
