### ISSUE TITLE
conda error about libopenblasp  when installing numpy

### ISSUE THREAD

**Issue by windtalker6** [conda/conda#9049]
I was installing the numpy(V1.15.4): and there was an error:
=====================================================
$conda install numpy=1.15.4
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/wubin/miniconda3

  added / updated specs:
    - numpy=1.15.4

The following NEW packages will be INSTALLED:

  libblas            conda-forge/linux-64::libblas-3.8.0-11_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-11_openblas
  liblapack          conda-forge/linux-64::liblapack-3.8.0-11_openblas
  libopenblas        anaconda/linux-64::libopenblas-0.3.6-h5a2b251_1
  numpy              conda-forge/linux-64::numpy-1.15.4-py37h8b7e671_1002

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/wubin/miniconda3/lib/libblas.so.  Please remove this file manually (you may need to reboot to free file handles)                                               done
ERROR conda.core.link:_execute(656): An error occurred while installing package 'anaconda::libopenblas-0.3.6-h5a2b251_1'.
Rolling back transaction: done

[Errno 17] File exists: 'libopenblasp-r0.3.6.so' -> '/home/wubin/miniconda3/lib/libcblas.so'
()
===================================================

the error indicated that there was a file "/home/wubin/miniconda3/lib/libcblas.so", an it could not remove or rename it. 

but I check the file and find there's no such file:

$ls /home/wubin/miniconda3/lib/libcblas.so
ls: cannot access /home/wubin/miniconda3/lib/libcblas.so: No such file or directory

then what's the problem?
I just can't install numpy due to this error!!!

**Comment by kylekeppler** [comment]
I saw this problem today. I was running a build inside a docker container and simply restarting the build worked.

**Comment by wimvanleuven-kbc** [comment]
We have this problem numerous times ... esp. in our CI jobs. Restarting, often does solve the problem; conda clean --all helps in even more cases.

However, we haven't found the root cause of the problem and we would love a fundamental solutions as right now it is a waste of time and unnecessary support requests. 

If anybody has ideas were to look or what to investigate, we can contribute our findings to help solve this. 

Many thanks!

**Comment by davidcotter** [comment]
> conda clean --all 
Thanks yes this solves it for me.
