### ISSUE TITLE
powershell activation missing PATH modification somehow

### ISSUE THREAD

**Issue by msarahan** [conda/conda#9057]
conda 4.7.10 - plus a few commits.

We've picked up a problem with the powershell command stuff.  It looks like it needs PATH modification like we did for other shells.

https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda/builds/26487461/job/vac5ytxqumyco5t3#L1344

**Comment by mingwandroid** [comment]
If posh activation is broken that needs fixing asap and is probably orthogonal to this. If it isn't orthogonal to this then it's likely the cause of this. That's how my though process works at least.

**Comment by msarahan** [comment]
I looked at the powershell activation.  I didn't see anything out of place.  The PATH modification prior to the conda call is intact.  I think the problem is that the code I have added in conda's context to determine whether or not we can use libarchive is causing the library load to happen earlier than it did before.  I'm not really sure how that could cause the problem, though, because the PATH change is before any conda call.

**Comment by msarahan** [comment]
The latest build of python-libarchive-c improves a patch that helps it load libarchive on windows: https://github.com/AnacondaRecipes/python-libarchive-c-feedstock/pull/3

If you update to python-libarchive-c build 12, you should no longer see any problems.  I'll close this issue, but we can reopen it if it is still a problem.
