### ISSUE TITLE
where do .conda compressed files live?

### ISSUE THREAD

**Issue by js3711** [conda/conda#9061]
What actually happens when you conda install something?  My understanding is that .tar.bz2 files for linux-64 distribution are pulled from: https://repo.anaconda.com/pkgs/main/linux-64/ 

I have heard about a new compression format .conda, and have seen it in the repodata.json file.  Where do these compressed files live?  I do not see them at the above url.

**Comment by soapy1** [comment]
some docs:
- https://conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format
- https://www.anaconda.com/understanding-and-improving-condas-performance/
- https://conda.io/projects/conda/en/latest/user-guide/concepts/installing-with-conda.html

The .conda packages live side by side with the .tar.bz2 packages. For example https://repo.anaconda.com/pkgs/main/linux-64/absl-py-0.1.13-py35_0.tar.bz2 vs https://repo.anaconda.com/pkgs/main/linux-64/absl-py-0.1.13-py35_0.conda
