### ISSUE TITLE
conda clone corrupts pip installed packages

### ISSUE THREAD

**Issue by kahing** [conda/conda#9063]
after using pip to update a conda package, `conda create --clone` could either silently downgrade the package, or corrupt the package.

### Steps to Reproduce

```Shell
conda create --name root_env pandas=0.24.2
conda activate root_env
pip install pandas==0.25.0
conda create --clone root_env --name user_env
conda activate user_env
python -c "import pandas"
```

## Expected Behavior

Expected behavior is in the new environment we will have a usable pandas 0.25.0

## details

Quick approximation of what conda does during clone:

1. it finds all the files in the environment that belongs to conda packages: lets call it `conda_files`
2. it finds all the files in the environment: `all_files`
3. conda copies `all_files - conda_files` to new environment
4. conda clones `conda_files` according to the conda package (hardlink, etc)

As a result, if pip updates an existing conda package, new files in the updated package will be copied, and files that exist in both versions will be hardlinked from package cache. The result is either a mix of 2 different versions, or the old conda version (if there are no new files).

We found that if we run `conda list`, conda will remove any conda package metadata (json file in <conda_env>/conda-meta/) that belongs to an updated pip package. This prevents step 4 above from happening and results in a correct conda clone.

`conda list` does that because if force enables `pip_interop_enabled`: https://github.com/conda/conda/blob/a90b0f6f7f91357b7a1ed57d82a5593421b69a22/conda/cli/main_list.py#L45 (despite the outdated comment https://github.com/conda/conda/blob/a90b0f6f7f91357b7a1ed57d82a5593421b69a22/conda/core/prefix_data.py#L233-L234 that says it doesn't).

So a current workaround is:
```Shell
conda create --name root_env pandas=0.24.2
conda activate root_env
pip install pandas==0.25.0
conda list # This fixes the problem
conda create --clone root_env --name user_env
conda activate user_env
python -c "import pandas"
```

Relying on `conda list` to magically fix the problem seems fragile. #8743 also makes us question if `pip_interop_enabled` are going to cause other issues even if it's only used for `conda list`. Because of #8372 it's also not clear if conda will retain this behavior going forward.

`conda list` essentially relies on version string comparison and that could be potentially problematic as well, since it's possible to `pip install --no-binary` to recompile a package with and conda clone will still silently overwrite it.

**Comment by msarahan** [comment]
Perhaps you should expect to need to enable `pip_interop_enabled` if you are going to operate on environments with pip packages?  I don't think that's an unreasonable expectation at all.  Perhaps we can improve messaging here, but the fix is to have that setting enabled (in condarc, not by strange proxy via conda list).  When you run conda list, you're probably making conda parse and map the pip package metadata into conda metadata.  That stuff is still around for your next operation.

**Comment by kahing** [comment]
As referenced I don't think we can enable `pip_interop_enabled` because of #8743
