### ISSUE TITLE
conda list broken after flit install --pth-file

### ISSUE THREAD

**Issue by maximlt** [conda/conda#9074]
## Current Behavior

    Traceback (most recent call last):
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 133, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 162, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 72, in load
        self._load_site_packages()
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 277, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\gateways\disk\read.py", line 257, in read_python_record
        paths_tups = pydist.get_paths()
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\pkg_formats\python.py", line 261, in get_paths
        records = tuple(process_csv_row(row) for row in record_reader if row[0])
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\pkg_formats\python.py", line 261, in <genexpr>
        records = tuple(process_csv_row(row) for row in record_reader if row[0])
    IndexError: list index out of range

`$ C:\Users\maxim\Anaconda3\envs\project\Scripts\conda-script.py list`

### Steps to Reproduce

```
conda activate myenv
cd project
flit install --pth-file
conda list
```
This raises the error printed above.

`conda remove project`  raises the following error:
```
PackagesNotFoundError: The following packages are missing from the target environment:
  - project
```

Executing `pip uninstall project` fixes `conda list`.

## Expected Behavior

`conda list` should list all the packages available in the active environment, including those in development mode installed with *flit* (I guess?). However, the problem might come from *flit*.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\Users\maxim\Anaconda3\envs\project
            shell level : 2
       user config file : C:\Users\maxim\.condarc
 populated config files : C:\Users\maxim\Anaconda3\envs\project\.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.1
       base environment : C:\Users\maxim\Anaconda3\envs\project  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\maxim\Anaconda3\envs\project\pkgs
                          C:\Users\maxim\.conda\pkgs
                          C:\Users\maxim\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\maxim\Anaconda3\envs\project\envs
                          C:\Users\maxim\.conda\envs
                          C:\Users\maxim\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\maxim\Anaconda3\envs\project\.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by flying-sheep** [comment]
This block doesn’t catch the IndexError:

https://github.com/conda/conda/blob/50093e14c6a96c7cd4f6c4570cc09bc5b763ede4/conda/core/prefix_data.py#L282-L301

it just catches `ValidationError`s.

The error probably happens when parsing the `*.dist-info/RECORD` file. For me in linux, that file looks fine. @Koncopd @maximlt is that also the case on windows?

If not, it might be a flit bug, if it’s fine, it’s a conda bug.

**Comment by Koncopd** [comment]
The same error for the new version of conda.
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in
__call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _mai
n
        exit_code = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 8
3, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 142, i
n execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 80, in
 print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 45, in
 list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_rec
ords(),
      File "C:\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 140
, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 169
, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in dec
orated
        return f(*args, **kwds)
      File "C:\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 79,
 in load
        self._load_site_packages()
      File "C:\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 284
, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_reco
rd.version)
      File "C:\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 2
47, in read_python_record
        paths_tups = pydist.get_paths()
      File "C:\Miniconda3\lib\site-packages\conda\common\pkg_formats\python.py",
 line 272, in get_paths
        records = process_csv_row(record_reader)
      File "C:\Miniconda3\lib\site-packages\conda\common\pkg_formats\python.py",
 line 247, in process_csv_row
        cleaned_path = posix_normpath("%s%s%s" % (sp_dir, path_prepender, row[0]
))
    IndexError: list index out of range
```

**Comment by Koncopd** [comment]
Found the problem.
On Windows record file has spaces between strings for some reason, deleting spaces fixes the problem.

**Comment by flying-sheep** [comment]
Yeah, maybe that’s introduced in flit, so maybe it’s a flit bug after all.

Anyway, we can handle it here: #10172

**Comment by Koncopd** [comment]
Yes, thank you.

**Comment by flying-sheep** [comment]
Great. How does the file look? You said “spaces” but I assume you mean empty lines?

**Comment by Koncopd** [comment]
Yep, you are right, these are empty lines.

```
anndata,,

anndata-0.7.5.dev12_g9ad2def.dist-info\METADATA,sha256=32b70d7f292653c19ecc3218889d26654afbab8ac6ca3751ea57f9c72e2e5477,4033

anndata-0.7.5.dev12_g9ad2def.dist-info\INSTALLER,sha256=91a475e3f8891fc45b7eb71b7c504ae31111b86ae04524763ab0e91f97f6f8df,4

anndata-0.7.5.dev12_g9ad2def.dist-info\REQUESTED,sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855,0

anndata-0.7.5.dev12_g9ad2def.dist-info\RECORD,,
```

I didn't notice them at first because standard windows notepad doesn't show them at all.

**Comment by flying-sheep** [comment]
I think I know what’s happening here.

1. Flit writes the file using system newlines. On Windows that means `\r\n` (Yes, it doesn’t appear in the code, Python does it automatically)
2. Conda reads the file assuming it has UNIX newlines, i.e. just `\n`. Its reader interprets `\r` as a second line break, generating a new line between `\r` and `\n`.

Since the RECORD file [is clearly defined as having `\r\n` or `\n`](https://www.python.org/dev/peps/pep-0376/#record), this would mean it’s a conda bug. Can you confirm that I’m right?

**Comment by Koncopd** [comment]
conda uses standard `open` and `csv`.
https://github.com/conda/conda/blob/4d3fafc879192c986d6d3e67607a8ccd71b6af8a/conda/common/compat.py#L174
There shouldn't be any problems with line delimiters from this side.

I can actually see these empty lines with Notepad++ in RECORD, i don't see empty lines with anything if i just use `f=open('test', 'w'); f.write('a\nb\nc')`.
So it seems that the problem is on the write side

**Comment by flying-sheep** [comment]
[This](https://github.com/takluyver/flit/blob/cfd71d81be95300266c6e989cf2d1bf57aa637fc/flit/install.py#L391-L406) is the code flit uses to write the data, so no:

```py
        with (dist_info / 'RECORD').open('w', encoding='utf-8') as f:
            cf = csv.writer(f)
            for path in self.installed_files:
                path = pathlib.Path(path)
                if path.is_symlink() or path.suffix in {'.pyc', '.pyo'}:
                    hash, size = '', ''
                else:
                    hash = 'sha256=' + common.hash_file(str(path))
                    size = path.stat().st_size
                try:
                    path = path.relative_to(site_pkgs)
                except ValueError:
                    pass
                cf.writerow((str(path), hash, size))

            cf.writerow(((dist_info / 'RECORD').relative_to(site_pkgs), '', ''))
```

**Comment by takluyver** [comment]
Can you inspect exactly what one of the offending RECORD files contains? It may have been changed by copy-pasting into Github. Either open it with `'rb'` mode to see the raw bytes, or use a hex editor.

**Comment by Koncopd** [comment]
```
f = open('RECORD', 'rb')
for line in f:
    print(line)
```
```
b'anndata,,\r\r\n'
b'anndata-0.7.5.dev12_g9ad2def.dist-info\\METADATA,sha256=32b70d7f292653c19ecc3218889d26654afbab8ac6ca3751ea57f9c72e2e5477,4033\r\r\n'
b'anndata-0.7.5.dev12_g9ad2def.dist-info\\INSTALLER,sha256=91a475e3f8891fc45b7eb71b7c504ae31111b86ae04524763ab0e91f97f6f8df,4\r\r\n'
b'anndata-0.7.5.dev12_g9ad2def.dist-info\\REQUESTED,sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855,0\r\r\n'
b'anndata-0.7.5.dev12_g9ad2def.dist-info\\RECORD,,\r\r\n'
```

**Comment by takluyver** [comment]
OK, so it is definitely a writing issue. It looks like both the csv module and the file I/O code try to convert newlines, so it gets done twice :-( . The docs for [csv.writer](https://docs.python.org/3/library/csv.html#csv.writer) say:

>  If csvfile is a file object, it should be opened with `newline=''`

Do you want to make a PR on Flit?

**Comment by flying-sheep** [comment]
I’ll make one, but only if you merge takluyver/flit#256 first :wink:

**Comment by flying-sheep** [comment]
This was fixed in https://github.com/pypa/flit/pull/368

**Comment by travishathaway** [comment]
Considering this has been fixed elsewhere, I will be closing this issue now.
