### ISSUE TITLE
Can't install OpenCV - caused by conflict

### ISSUE THREAD

**Issue by Sumiya1020** [conda/conda#9076]
I am trying to install OpenCV.
I get following conflict:

```
(base) C:\Users\barce>conda install -c conda-forge opencv
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package mkl-service conflicts for:
mkl-service
scikit-learn -> mkl-service[version='>=2,<3.0a0']
Package spyder-kernels conflicts for:
anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0 -> spyder-kernels[version='>=0.4.2,<1']
spyder=3.3.6 -> spyder-kernels[version='>=0.4.2,<1,>=0.5.0,<1']
spyder-kernels
Package hdf5 conflicts for:
anaconda==2019.03=py37_0 -> h5py==2.9.0=py37h5e291fa_0 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
h5py -> hdf5[version='>=1.10.1,<1.10.2.0a0,>=1.10.4,<1.10.5.0a0,>=1.8.18,<1.8.19.0a0,>=1.8.20,<1.9.0a0']
pytables -> hdf5[version='1.10.1,1.8.17|1.8.17.*,1.8.18|1.8.18.*,>=1.10.1,<1.10.2.0a0,>=1.10.2,<1.10.3.0a0,>=1.8.18,<1.8.19.0a0,>=1.8.18,<1.9.0a0']
hdf5
Package importlib_metadata conflicts for:
pytest-openfiles -> pytest[version='>=2.8.0,>=3.1'] -> importlib_metadata[version='>=0.12']
pytest-remotedata -> pytest[version='>=3.1'] -> importlib_metadata[version='>=0.12']
path.py -> importlib_metadata[version='>=0.5']
pytest-astropy -> pytest-doctestplus[version='>=0.1.2,>=0.1.3,>=0.2.0'] -> pytest[version='>=2.8'] -> importlib_metadata[version='>=0.12']
pytest -> importlib_metadata[version='>=0.12']
pytest-arraydiff -> pytest -> importlib_metadata[version='>=0.12']
pytest-doctestplus -> pytest[version='>=2.8'] -> importlib_metadata[version='>=0.12']
importlib_metadata
astropy -> pytest[version='<3.7'] -> importlib_metadata[version='>=0.12']
Package spyder conflicts for:
anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0
Package pytest conflicts for:
anaconda==2019.03=py37_0 -> pytest-astropy==0.5.0=py37_0 -> pytest-doctestplus[version='>=0.1.2,>=0.1.3,>=0.2.0'] -> pytest[version='>=2.8']
```
</p></details>

**Comment by samggggflynn** [comment]
try use

`conda update all`

update your packages in Conda, then there will be some notifications, means some packages need to be installed to satisfy the requests.just input 'y' to comfirm .

`y`

then opencv should be started installing

**Comment by Sumiya1020** [comment]
Thank you for your response.
But I found a way by creating a new environment.

**Comment by lprasanth** [comment]
I am also getting the same problem though I updated it .

**Comment by tomviolin** [comment]
@Sumiya1020 You said:

"But I found a way by creating a new environment."

Can you please share exactly what way you found?  Thank you!

**Comment by andisama** [comment]
>> following fresh install conda; I then tried to update using "conda update all", but had the following message displayed:

(base) C:\Users\andis>conda update all

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\andis\anaconda3
  package name: all

>> I issued the following then, it went ok
(base) C:\Users\andis>conda update --prefix C:\Users\andis\anaconda3 anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\andis\anaconda3

  added / updated specs:
    - anaconda
...
...
...

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.11.28 |       hecc5488_0         182 KB  conda-forge
    certifi-2019.11.28         |   py37hc8dfbb8_1         149 KB  conda-forge
    conda-4.8.3                |   py37hc8dfbb8_1         3.1 MB  conda-forge
    icu-64.2                   |       he025d50_1        14.1 MB  conda-forge
    jpeg-9c                    |    hfa6e2cd_1001         314 KB  conda-forge
    libblas-3.8.0              |           15_mkl         3.5 MB  conda-forge
    libcblas-3.8.0             |           15_mkl         3.5 MB  conda-forge
    libclang-9.0.1             |default_hf44288c_0        20.8 MB  conda-forge
    liblapack-3.8.0            |           15_mkl         3.5 MB  conda-forge
    liblapacke-3.8.0           |           15_mkl         3.5 MB  conda-forge
    libopencv-4.2.0            |           py37_3        44.9 MB  conda-forge
    libwebp-1.0.2              |       hfa6e2cd_5         356 KB  conda-forge
    opencv-4.2.0               |           py37_3          19 KB  conda-forge
    openssl-1.1.1e             |       hfa6e2cd_0         4.7 MB  conda-forge
    py-opencv-4.2.0            |   py37h43977f1_3          21 KB  conda-forge
    pyqt-5.12.3                |   py37h6538335_1         4.7 MB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    qt-5.12.5                  |       h7ef1ec2_0       104.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       211.9 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/win-64::libblas-3.8.0-15_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-15_mkl
  libclang           conda-forge/win-64::libclang-9.0.1-default_hf44288c_0
  liblapack          conda-forge/win-64::liblapack-3.8.0-15_mkl
  liblapacke         conda-forge/win-64::liblapacke-3.8.0-15_mkl
  libopencv          conda-forge/win-64::libopencv-4.2.0-py37_3
  libwebp            conda-forge/win-64::libwebp-1.0.2-hfa6e2cd_5
  opencv             conda-forge/win-64::opencv-4.2.0-py37_3
  py-opencv          conda-forge/win-64::py-opencv-4.2.0-py37h43977f1_3
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m

The following packages will be UPDATED:

  conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1
  icu                        pkgs/main::icu-58.2-ha66f8fd_1 --> conda-forge::icu-64.2-he025d50_1
  jpeg                        pkgs/main::jpeg-9b-hb83a4c4_2 --> conda-forge::jpeg-9c-hfa6e2cd_1001
  pyqt                 pkgs/main::pyqt-5.9.2-py37h6538335_2 --> conda-forge::pyqt-5.12.3-py37h6538335_1
  qt                     pkgs/main::qt-5.9.7-vc14h73c81de_0 --> conda-forge::qt-5.12.5-h7ef1ec2_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
  certifi              pkgs/main::certifi-2019.11.28-py37_1 --> conda-forge::certifi-2019.11.28-py37hc8dfbb8_1
  openssl              pkgs/main::openssl-1.1.1e-he774522_0 --> conda-forge::openssl-1.1.1e-hfa6e2cd_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
py-opencv-4.2.0      | 21 KB     | ################################################################################################################################ | 100%
ca-certificates-2019 | 182 KB    | ################################################################################################################################ | 100%
icu-64.2             | 14.1 MB   | ################################################################################################################################ | 100%
liblapack-3.8.0      | 3.5 MB    | ################################################################################################################################ | 100%
certifi-2019.11.28   | 149 KB    | ################################################################################################################################ | 100%
conda-4.8.3          | 3.1 MB    | ################################################################################################################################ | 100%
opencv-4.2.0         | 19 KB     | ################################################################################################################################ | 100%
pyqt-5.12.3          | 4.7 MB    | ################################################################################################################################ | 100%
qt-5.12.5            | 104.4 MB  | ################################################################################################################################ | 100%
libblas-3.8.0        | 3.5 MB    | ################################################################################################################################ | 100%
liblapacke-3.8.0     | 3.5 MB    | ################################################################################################################################ | 100%
libcblas-3.8.0       | 3.5 MB    | ################################################################################################################################ | 100%
python_abi-3.7       | 4 KB      | ################################################################################################################################ | 100%
libclang-9.0.1       | 20.8 MB   | ################################################################################################################################ | 100%
jpeg-9c              | 314 KB    | ################################################################################################################################ | 100%
libopencv-4.2.0      | 44.9 MB   | ################################################################################################################################ | 100%
openssl-1.1.1e       | 4.7 MB    | ################################################################################################################################ | 100%
libwebp-1.0.2        | 356 KB    | ################################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\andis>


>> Hope it helps

**Comment by RorySpeirs** [comment]
On Windows at least, OpenCV can be installed by DOWNGRADING some packages. This can be done automatically by updating _anaconda_ using the following commands:

`conda update conda`
`conda update anaconda`
`conda install opencv`

**Comment by Sakibapon** [comment]
It still dont work for me

**Comment by Sakibapon** [comment]
It still doesn't work for me
