### ISSUE TITLE
Unable to install package using conda-forge

### ISSUE THREAD

**Issue by SabaKauser** [conda/conda#9077]
Hello,
I am trying to install python ibm_db as follows:
sudo conda create --name sab_env

**(base) BLR-D-MACOS03:bin skauser$ conda activate sab_env**
**(sab_env)** BLR-D-MACOS03:bin skauser$ conda install -c conda-forge sab_env
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /Users/skauser/anaconda3/pkgs/cache/09cdf8bf.json
  uid: 975728326
  gid: 844955432

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 975728326:844955432 /Users/skauser/anaconda3/pkgs/cache/09cdf8bf.json

In general, it's not advisable to use 'sudo conda'.

Then I run with sudo:
(sab_env) BLR-D-MACOS03:bin skauser$ sudo conda install -c conda-forge sab_env
WARNING: The conda.compat module is deprecated and will be removed in a future release.

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.

If I try to update conda as:
(base) BLR-D-MACOS03:bin skauser$ conda activate sab_env
(sab_env) BLR-D-MACOS03:bin skauser$ sudo conda update -n base -c defaults conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.

I see same error stating conda installation does not have default environment.

**Comment by soapy1** [comment]
It's not advisable to use conda with sudo. You should install conda using an installer for your user (if you are using conda as an individual) without using elevated privileges. Then you will be able to create environments and install packages from whichever channel you desire. e.g. `conda create -n sab_env -c conda_forge python`
For more information on how to install and use conda see our docs https://conda.io/projects/conda/en/latest/user-guide/install/index.html
