### ISSUE TITLE
path collision while installing package

### ISSUE THREAD

**Issue by SabaKauser** [conda/conda#9078]
Hello,

I get the following error when installing IBM_db python library to anaconda 3.7

(base) phils-MBP:~ phild$ conda install -c conda-forge ibm_db
Collecting package metadata (current_repodata.json): done
Solving environment: done
Package Plan

environment location: /Users/phild/anaconda3

added / updated specs:
- ibm_db

The following packages will be downloaded:

package                    |            build
---------------------------|-----------------
certifi-2019.6.16          |           py37_0         148 KB  conda-forge
conda-4.7.10               |           py37_0         3.0 MB  conda-forge
ibm_db-3.0.1               |   py37h01d97ff_0        19.8 MB  conda-forge
------------------------------------------------------------
                                       Total:        22.9 MB

The following NEW packages will be INSTALLED:

ibm_db conda-forge/osx-64::ibm_db-3.0.1-py37h01d97ff_0

The following packages will be SUPERSEDED by a higher-priority channel:

certifi pkgs/main --> conda-forge
conda pkgs/main --> conda-forge

Proceed ([y]/n)? y

Downloading and Extracting Packages
ibm_db-3.0.1 | 19.8 MB | ##################################### | 100%
conda-4.7.10 | 3.0 MB | ##################################### | 100%
certifi-2019.6.16 | 148 KB | ##################################### | 100%
Preparing transaction: done
Verifying transaction: failed

ClobberError: The package 'conda-forge::ibm_db-3.0.1-py37h01d97ff_0' cannot be installed due to a
path collision for 'lib/python3.7/site-packages/tests/init.py'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'defaults::json5-0.8.4-py_0', which is already installed in the prefix.

ClobberError: The package 'conda-forge::ibm_db-3.0.1-py37h01d97ff_0' cannot be installed due to a
path collision for 'lib/python3.7/site-packages/tests/pycache/init.cpython-37.pyc'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'defaults::json5-0.8.4-py_0', which is already installed in the prefix.

CondaVerificationError: The package for ibm_db located at /Users/phil.downey/anaconda3/pkgs/ibm_db-3.0.1-py37h01d97ff_0
appears to be corrupted. The path 'lib/python3.7/site-packages/clidriver/db2dump/._db2diag.log'
specified in the package manifest cannot be found.

Could you please let me know what causes this error and how to overcome it.

**Comment by soapy1** [comment]
Please update your version of conda using `conda update conda -n base` and see if the problem persists

**Comment by SabaKauser** [comment]
Thanks! This has already been fixed. closing.
