### ISSUE TITLE
conda init should support modifying /etc/bashrc

### ISSUE THREAD

**Issue by skissane** [conda/conda#9083]
If I run `conda init bash` as root, then it adds conda initialization to `/root/.bashrc`.

What I'd actually like to do, is update `/etc/bashrc` instead, so all users get that config (not just root). It would be nice if `conda init` had something like a `--global` option, that made it update `/etc/bashrc` instead of `/root/.bashrc`.

(While I could manually copy the section from `/root/.bashrc` to `/etc/bashrc`, I would like to avoid that if I can. This is being run from a Dockerfile which is installing conda into a container; the Dockerfile runs as root but then conda itself will be run from some other non-root user accounts in the docker container.)

(The same point applies to `/root/.zshrc` vs `/etc/zshrc`, `/root/.config/fish/config.fish` vs `/etc/fish/config.fish`, etc. I really only care about bash, but if you were to address this, you'd want to address it for as many of your supported shells as you feasibly could.)

(I realise some would argue that sharing a conda install between multiple users is maybe not a good idea. In actuality, the users don't add any environments at runtime, nor modify any environments, the container is just being used to run an application, and if we need to modify the environment, we actually do that by modifying the container build process, rather than doing it at runtime.)

**Comment by msarahan** [comment]
We would welcome a community contribution that adds this feature. The core team does not intend on spending time to implement this ourselves in the near future.

**Comment by gmseabra** [comment]
Actually, some Linux installations discourage adding anything to the `/etc/bashrc` file. Instead, it is recommended to add the new info to `/etc/profile.d/custom.sh`, which is read automatically.

**Comment by sfehrmann** [comment]
Ubuntu manages new user profiles via skeletons in `/etc/skel/` if activated in `/etc/default/useradd` or via options, and there's `/etc/skel/.bashrc`

**Comment by shivance** [comment]
I would like to take a crack at it !

**Comment by rainu-handshake** [comment]
I'd like to give this one a go today at PyCon 🥳 🎈

**Comment by gmseabra** [comment]
Agreed. I believe the `/etc/profile.d/conda.sh` would be safer, and compliant with the newest distributions.

Thanks for tacking this!

**Comment by kathatherine** [comment]
Seeing that we seem to have an alternative that already exists in the code that works better than the proposed fix, I'll close this. Thanks, all!
