### ISSUE TITLE
Update from 3.6 to 3.7 fails

### ISSUE THREAD

**Issue by dmsolow** [conda/conda#9088]
I'm running conda 4.5.13 with Python 3.6.8

I want to update the installation to Python 3.7

In the past, this command has worked for me: `conda update python -y`

However, this is now updating to 3.6.9 which is not useful

I've tried running `conda install python=3.7 anaconda=custom` (from here: https://docs.conda.io/en/latest/miniconda.html)

However this results in the following error:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

Any ideas? This was working fine last week.

**Comment by jjhelmus** [comment]
Can you try upgrading to the latest version of conda?  There have been a number of changes to how upgrades to python work in recent conda releases but the latest should allow you to upgrade if you provided an explicit version, e.g. `conda install python=3.7`.
