### ISSUE TITLE
Conda environment configuration file

### ISSUE THREAD

**Issue by MichWeb75** [conda/conda#9102]
Currently, I have conda environments stored at different directories:
**/opt/conda/envs**
**/home/Software/envs**

`conda envs list` is able to find them all, although I cannot find a etc/profile which stores the location of all environment. How does conda determine the directories of the environments ?

`conda config --show envs_dirs` provides information about environments. How and where is the variable envs_dirs specified ?

I am using MiniConda 4.6.14  (CentOS 7)

**Comment by forrestwaters** [comment]
You should have a file at `~/.conda/environments.txt` that has a list of all your environments. You can customize that envs_dirs variable in your `.condarc` file if you'd like: https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html
