### ISSUE TITLE
How to fix ' environment error and package when installing cassandra using conda

### ISSUE THREAD

**Issue by callmekofi** [conda/conda#9109]
I'm installing Cassandra on my Mac through anaconda but i have a problem with the environment, 
1. It displays this message anytime i run ( conda install -c conda-forge cassandra-driver ) :failed with initial frozen solve. Retrying with flexible solve. 

2. furthermore it gives The following specifications were found to be incompatible with each other

3. Package ca-certificates conflicts for:

    cassandra-driver -> python=3.6 -> openssl[version='>=1.0.2p,<1.0.3a'] -> ca-certificates
    python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
    Package setuptools conflicts for:
    cassandra-driver -> python=3.6 -> pip -> setuptools
    python=3.7 -> pip -> setuptools
    Package pip conflicts for:
    python=3.7 -> pip
    cassandra-driver -> python=3.6 -> pip
    Package certifi conflicts for:
    python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
    cassandra-driver -> python=3.6 -> pip -> setuptools -> certifi[version='>=2016.09']
    Package wheel conflicts for:
    cassandra-driver -> python=3.6 -> pip -> wheel
    python=3.7 -> pip -> wheel

**Comment by forrestwaters** [comment]
cassandra-driver is not available for python 3.7 from conda-forge. If you're okay with py36 you can try:
```
conda install -c conda-forge cassandra-driver python=3.6
```

**Comment by callmekofi** [comment]
@forrestwaters  this is the result i got from running (conda install -c conda-forge cassandra-driver python=3.6)
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::anaconda==2019.07=py37_0
  - defaults/osx-64::numba==0.44.1=py37h6440ff4_0
done

**Comment by jjhelmus** [comment]
@callmekofi `conda install tbb` should address the inconsistency.  

#9124 will cause issues if you change the Python version in your base environment.  

Instead you can create a new environment with python 3.6 and cassandra-driver using `conda create -n example -c conda-forge python=3.6 cassandra-driver`

**Comment by callmekofi** [comment]
@jjhelmus thanks for your input. I rectified the problem by 
1. Downgrading my JDK 11 to 8 (Currently Cassandra 3.1 is desired to run on JDK 8 only.)
2. Edit %CASSANDRA_HOME%/conf/jvm.options file: replace -XX:ThreadPriorityPolicy=42 with -XX:ThreadPriorityPolicy=1

**Comment by alexe-bit** [comment]
> @callmekofi `conda install tbb` should address the inconsistency.
> 
> #9124 will cause issues if you change the Python version in your base environment.
> 
> Instead you can create a new environment with python 3.6 and cassandra-driver using `conda create -n example -c conda-forge python=3.6 cassandra-driver`

can I use this while installing json5 on my windows 7 32-bits too?
i keep getting' condaerror: can not link a source that does not exist' messages whenever I try to download the package
