### ISSUE TITLE
getting an error while working on excel with python

### ISSUE THREAD

**Issue by shiva2410** [conda/conda#9112]
Error

  File "<ipython-input-12-6e449fc2322a>", line 22, in <module>
    sheet['D3'] = '= SUM(G3:AZ3)'

TypeError: 'NoneType' object does not support item assignment

my code
# import openpyxl module 
import openpyxl 
sb="lists.xls"
 
wb = openpyxl.Workbook(sb) 
 
sheet = wb.active 

sheet['D3'] = '= SUM(G3:AZ3)'

wb.save(sb)

**Comment by jjhelmus** [comment]
This error seem related to your use of `openpyxl` rather than an issue with the conda package manager.  You should request assistance with this problem from the `openpyxl` community.
