### ISSUE TITLE
error in conda install cudatoolkit-7.5-2.tar.bz2

### ISSUE THREAD

**Issue by lannisite110** [conda/conda#9113]
xdlan@server-pc:~$ conda install --use-local /home/users/xdlan/Downloads/cudatoolkit-7.5-2.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

 https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /home/server/anaconda3  (read only)
    default environment : /home/users/xdlan/.conda/envs/rcfusion
       envs directories : /home/users/xdlan/.conda/envs
                          /home/server/anaconda3/envs
          package cache : /home/server/anaconda3/pkgs
                          /home/users/xdlan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/users/xdlan/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.4 Linux/4.15.0-50-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1002:1002

`$ /home/users/xdlan/.conda/envs/rcfusion/bin/conda install --use-local /home/users/xdlan/Downloads/cudatoolkit-7.5-2.tar.bz2`

    Traceback (most recent call last):
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 210, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/misc.py", line 99, in explicit
        link_names = {index[d]['name'] for d in link_dists}
      File "/home/server/anaconda3/lib/python3.6/site-packages/conda/misc.py", line 99, in <setcomp>
        link_names = {index[d]['name'] for d in link_dists}
    KeyError: Dist(_Dist__initd=True, channel='<unknown>', dist_name='cudatoolkit-7.5-2', name='cudatoolkit', version='7.5', build_string='2', build_number=2, with_features_depends=None, base_url='file:///home/users/xdlan/Downloads', platform=None)

**Comment by jjhelmus** [comment]
You conda version, 4.3.30, is outdates, the latest version is 4.7.11.  Can you try updating conda using `conda update conda` and see if that helps,
