### ISSUE TITLE
Adding cuda virtual package requirement to cudatoolkit

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#9115]
Not sure the right place to raise this. So adding it here. Plus this has higher visibility.

It would be great to have the `cudatoolkit` package rely on the `cuda` virtual package ( recently added in PR https://github.com/conda/conda/pull/8267 ). This would ensure that only a `cudatoolkit` that is supported on the user's hardware gets installed. Further this would propagate down to other packages that rely on `cudatoolkit` to ensure they are aligned to the right CUDA version. Once we have the `nvcc` wrapper package integrated ( https://github.com/conda-forge/staged-recipes/pull/8229 ), this will ensure users building CUDA packages also produce packages that will be able to take advantage of this functionality thanks to [the `run_export` of `cudatoolkit`]( https://github.com/conda-forge/staged-recipes/pull/8229/files#diff-07df8cf5d3a65ad59524ecff001534d6R22 ).

**Comment by jakirkham** [comment]
cc @jjhelmus

**Comment by jjhelmus** [comment]
I would be in favor of adding the `cuda` virtual packages as a `constrains` entry to the `cudatoolkit` packages but not a `depends` entry.  If `cuda` was added as a dependency then the packages would become unusable with older versions of conda where the `cuda` virtual package did not exist.  If added as a `constrains` entry, these packages will still work with older versions of conda where the `cuda` virtual packages does not exist but will "do the right thing" when the virtual package is available.

I assume the new entry would be greater than or equal to the major/minor `cudatoolkit` version.  So `cudatoolkit` 10.0 would have a entry of `__cuda >=10.0` and `cudatoolkit` 9.0, `__cuda>=9.0`.  Pinning to the exact version could also be done but installing older versions of cudatoolkit on system with newer drivers works fine and is helpful when testing GPU packages.  Additionally, not all packages support the latest CUDA version and older versions of packages will only support the older CUDA versions.

**Comment by jakirkham** [comment]
Yep this makes sense. Using `constrains` seems reasonable to me. As long as we are able to simplify the installation story from the end user perspective, I think we are going in the right direction here.

Yeah this also sounds reasonable to me. The solver will already bias towards newer versions of `cudatoolkit`. So users will get the newest possible `cudatoolkit` version they can. If they choose to have an older `cudatoolkit` version (or packages haven't been built for a newer one), it seems fine to go with an older version of `cudatoolkit` that will work.

**Comment by jakirkham** [comment]
cc @kkraus14 (in case you have other thoughts here 🙂)

**Comment by jjhelmus** [comment]
I downside of `constains` is that users who do not have a GPU or any driver installed will not be prevented from installing `cudatoolkit`.

**Comment by jakirkham** [comment]
> I downside of `constains` is that users who do not have a GPU or any driver installed will not be prevented from installing `cudatoolkit`.

Maybe the virtual `cuda` package should provide a different value when there is no GPU. I'm reluctant to suggest `nan`, but that might be one such value.

cc @seibert (if you have thoughts on this point or this topic more generally 🙂)

**Comment by jakirkham** [comment]
It might be worth revisiting this now that we are adding GPU builds to packages in conda-forge.

**Comment by jakirkham** [comment]
> I downside of `constains` is that users who do not have a GPU or any driver installed will not be prevented from installing `cudatoolkit`.

Thinking about this again. I'm not sure this is a downside. This is in fact something we are relying on to build GPU packages (as they are occurring on machines that also don't have GPUs).

**Comment by kkraus14** [comment]
> > I downside of `constains` is that users who do not have a GPU or any driver installed will not be prevented from installing `cudatoolkit`.
> 
> Thinking about this again. I'm not sure this is a downside. This is in fact something we are relying on to build GPU packages (as they are occurring on machines that also don't have GPUs).

I think if it returned a specific value if the user has no GPU that doesn't constrain the toolkit version then we're good, but if it blocks toolkit installation that would be a potential issue.

**Comment by jakirkham** [comment]
I'm curious how do we go about adding this constraint (assuming it is agreeable). Is there somewhere we can make a PR? 🙂

**Comment by jjhelmus** [comment]
> I'm curious how do we go about adding this constraint (assuming it is agreeable). Is there somewhere we can make a PR?

The existing `cudatoolkit` packages could be hotfixed to add a constrains entry against the `cuda` virtual package.  The hotfixes for the `defaults` channel are generated from the scripts in https://github.com/AnacondaRecipes/repodata-hotfixes/.  I can prepare a PR if desired.

**Comment by jakirkham** [comment]
That would be great @jjhelmus! Happy to review 😀

**Comment by jakirkham** [comment]
Added a rough draft of a hot-fix in PR ( https://github.com/AnacondaRecipes/repodata-hotfixes/pull/79 ). Could use a review when people have a chance 🙂

**Comment by jjhelmus** [comment]
Adding constraints to the `cudatoolkit` packages does not result in these packages being restrained by the `__cuda` virtual package.  

Reopening this issue.

**Comment by jakirkham** [comment]
Thanks Jonathan!

After doing a bit of debugging, it looks like the patch is correct, but there may be a bug in Conda.

In particular, this does not work correctly.

<details>
<summary>

```
conda create -d -n test_cuda cudatoolkit
```

</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/miniforge/envs/test_cuda

  added / updated specs:
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    cudatoolkit-10.2.89        |       hfd86e86_0       539.3 MB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         4.0 MB
    ------------------------------------------------------------
                                           Total:       551.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.2.89-hfd86e86_0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0



DryRunExit: Dry run. Exiting.
```

</details>

However adding `__cuda` to the install spec does work.

<details>
<summary>

```
conda create -d -n test_cuda __cuda cudatoolkit
```

</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/miniforge/envs/test_cuda

  added / updated specs:
    - __cuda
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.1.243       |       h6bb024c_0       513.2 MB
    ------------------------------------------------------------
                                           Total:       513.2 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.1.243-h6bb024c_0



DryRunExit: Dry run. Exiting.
```

</details>

Interestingly we also observe compiler runtime packages installed in the first case, but not in the second. Unclear on why that happens, but may also be related to the same issue.

**Comment by jakirkham** [comment]
cc @leofang (who may also be interested in this issue)

**Comment by leofang** [comment]
Thanks, @jakirkham! I happen to be puzzled by `__cuda`: when testing nsls-ii-forge/cupy-feedstock#1, I noticed that `__cuda` imposed addition constraint on the allowed NumPy version (or the other way around). Do you think it's relevant?

**Comment by leofang** [comment]
See e.g. an error log from our CI when I tried to specify the scipy version:
https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=2457&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=609
```bash
...
Package numpy conflicts for:
scipy[version='>=1.0,<1.1'] -> numpy[version='>=1.9|>=1.9.3,<2.0a0']
numpy[version='>=1.9.0']

Package libgomp conflicts for:
libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5'] -> libgomp[version='>=7.3.0']
gcc_linux-64 -> gcc_impl_linux-64=7.3.0 -> libgomp[version='>=7.3.0']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```
I would not have any idea what's going on if John had not pinged me here...

**Comment by jakirkham** [comment]
Those seem like 3 different conflicts. The first seems to be about finding `numpy` and `scipy` versions that are compatible. The second is about some conflicts satisfying the compiler runtime libraries. The third seems to be complaining about the CUDA driver's support for CUDA 10.2. Generally (and admittedly this is after years of debugging these kinds of issues) this looks like a channel is missing (at least for the first two). The last error is a bit perplexing however. Though it's probably only worth digging into after the first and second errors have been addressed.

**Comment by leofang** [comment]
The last error happens even when the requested `cudatoolkit` matches the driver version (10.2). Very confusing indeed 😂

**Comment by jakirkham** [comment]
Maybe it expects the build string of `__cuda` to include `0`, which it doesn't?

**Comment by jakirkham** [comment]
@kalefranz it is a Conda issue though as Conda is not respecting the constraint

https://github.com/conda/conda/issues/9115#issuecomment-620168193

**Comment by jjhelmus** [comment]
I suspect that an `constrains` entry is insufficient to pull a package into the set of packages considered by the solver by itself.  

Outside of virtual packages this makes sense.  If `pkg_a` is not required by any of the requested packages for an environment there is no need evaluate constrains entry that contain `pkg_a`.  Virtual packages need to be considered differently as they are always present (or not) regardless of what other packages are in the environment.

**Comment by jjhelmus** [comment]
It might be better to open new issues rather than re-open this one as the scope has changed.  For the recent discussion there seem to be two different issues:

* conda includes `__cuda` in the conflict hints for non-obvious reason.  I've seen this occasionally, I do not think `__cuda` is the source of the conflict but the hinting algorithms reports it for some reason.
* A `constrains` entry on a virtual package is insufficient to constrain that packages unless it is explicitly requests by the user.  Although this has only been seen with the `__cuda` virtual package, I suspect the same will occur with other virtual packages like `__glibc`.

**Comment by jakirkham** [comment]
> It might be better to open new issues rather than re-open this one as the scope has changed.

Ok that makes sense. Thanks Jonathan!

> * conda includes `__cuda` in the conflict hints for non-obvious reason.  I've seen this occasionally, I do not think `__cuda` is the source of the conflict but the hinting algorithms reports it for some reason.

Could you please file an issue for this @leofang?

> * A `constrains` entry on a virtual package is insufficient to constrain that packages unless it is explicitly requests by the user.  Although this has only been seen with the `__cuda` virtual package, I suspect the same will occur with other virtual packages like `__glibc`.

Have filed this as issue ( https://github.com/conda/conda/issues/9896 ).

**Comment by leofang** [comment]
Filed the first issue in #9897.
