### ISSUE TITLE
Keep getting error upon installing wordcloud

### ISSUE THREAD

**Issue by zahs123** [conda/conda#9120]
## Current Behavior
When i conda install: 

conda install -c conda-forge wordcloud 

this comes with an error: 

**('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))**

## Expected Behavior
it should just download

## Environment Information
on conda 3.7

##Steps i've tried 

i've tried to use the following commands: 

conda config --set ssl_verify False 

conda clean --source-cache

conda update conda 

the last two result in the same error i have put above! Can anybody please help.

**Comment by soapy1** [comment]
The latest version of conda is 4.7.11. Please update to that version if you are able to

**Comment by zahs123** [comment]
@soapy1 i can't even update conda, when i do conda update conda it gives me the same error
