### ISSUE TITLE
Custom scripts are not executed upon activation/deactivation of an environment

### ISSUE THREAD

**Issue by drorata** [conda/conda#9122]
## Current Behavior

When activating an environment which has a custom script defined in `$CONDA_PREFIX /etc/conda/activate.d/` the script(s) is not executed and an error is shown:

```
(eval):pwd:11: too many arguments
```

It seems like the activation/deactivating process finds the scripts but fail to run them.

#### Create an empty environment
```
conda create -n foo
```

#### Add a script
Add something like:

```bash
#!/bin/sh

echo "Foo"
```
to `$CONDA_PREFIX /etc/conda/activate.d/`.

#### Try to activate

Running `conda activate foo` works, but the error:

```
(eval):pwd:11: too many arguments
```
is emitted.

## Expected Behavior

I believe that the string `Foo` should have been printed.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : foo-test
    active env location : /Users/dror/anaconda3/envs/foo-test
            shell level : 2
       user config file : /Users/dror/.condarc
 populated config files : /Users/dror/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /Users/dror/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dror/anaconda3/pkgs
                          /Users/dror/.conda/pkgs
       envs directories : /Users/dror/anaconda3/envs
                          /Users/dror/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/dror/.condarc <==
changeps1: False
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/dror/anaconda3/envs/foo-test:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by drorata** [comment]
I suspect the problem is somehow with my shell (zsh). I tried something similar inside a clean docker container and it worked as expected. However, I was not able to understand where the problem is.

**Comment by forrestwaters** [comment]
I can't reproduce this with zsh on my mac. Do you have an alias for `pwd` or something like that? Your output seems to imply that a bad alias/shell function is being called. I don't think this is an issue with conda as far as I can tell

**Comment by drorata** [comment]
You are my hero! Indeed I had

``bash
alias .="pwd"
```

in my `.zshrc`. Removing this solved the issue.

What made you write:

>  Do you have an alias for `pwd` or something like that? 

I'm eager to learn what was the intuition behind it.

**Comment by forrestwaters** [comment]
I just noticed the output you provided:
```
(eval):pwd:11: too many arguments
```
Glad that did the trick!

**Comment by drorata** [comment]
Can you or someone else explain why exactly this alias broke the behavior of `conda activate`?

**Comment by forrestwaters** [comment]
Likely because of this: https://github.com/conda/conda/blob/master/conda/activate.py#L751

`.` is a posix built-in so I'd avoid creating an alias of the same name: https://www.gnu.org/software/bash/manual/html_node/Special-Builtins.html#Special-Builtins
