### ISSUE TITLE
Conda benchmarks that SAT Solvers are bottlenecks for solving dependencies

### ISSUE THREAD

**Issue by hgorjiara** [conda/conda#9130]
We are working on a new constraint compiler that can significantly speed up SAT solving process in Conda. I was wondering if someone can point me to different benchmarks that SAT Solvers are bottlenecks for dependency solving?

Thanks

**Comment by jjhelmus** [comment]
@mbargull has run a number of benchmarks on the solver, such as the ones in #7676, that might be of use.  I believe @msarahan has benchmarks that he may be able to share as well.
