### ISSUE TITLE
empty environment with a nonexistent folder

### ISSUE THREAD

**Issue by musm** [conda/conda#9131]
```
> conda env list
# conda environments:
#
                         C:\tools\Miniconda3
base                  *  C:\tools\miniconda3
py2                      C:\tools\miniconda3\envs\py2
```

The `C:\tools\Miniconda3` folder doesn't exist and for some reason the environment has no name?

**Comment by soapy1** [comment]
could you provide the output of `conda info`? Or try updating conda to see if the issue persists
