### ISSUE TITLE
latest R-curl

### ISSUE THREAD

**Issue by KoichiHashikawa** [conda/conda#9148]
Hellow
can you enable the installation of latest curl (version 4.0) for conda environment?
Some of analysis packages start using latest curl, but install.packages("curl") did not work in linux machine and wanted to install by conda install r-curl.

thanks.

**Comment by soapy1** [comment]
this package exists on conda-forge https://anaconda.org/conda-forge/r-curl/files you can install it with `conda install r-curl -c conda-forge`

**Comment by KoichiHashikawa** [comment]
Thanks so much!!
