### ISSUE TITLE
Unparsable versions lead to inconsistent comparison

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#915]
A version that conda can't recognize (like pyzmq 14.3.1.post26.g9d75ca2) can lead to conda choosing the wrong version as the max, as it falls back to string comparison. This leads to an inconsistent comparison. So for instance, if you don't have this package, it will correctly choose 14.3.1 as the newest version, but if you do have it, it will choose 2.2.0.1 as the newest version, becasue the final comparison in `max()` compares the strings `14.3.1.post26.g9d75ca2` and `2.2.0.1` and finds the latter to be greater. Simply put, the ordering on `conda.resolve.Package` objects is inconsistent. 

I'm not really sure how to fix this. A good idea would be to warn, if not fail, in conda-build if a version is given that verlib cannot parse.

**Comment by marscher** [comment]
another issue with verlib seems to be a prior version '1.0a3' is winning over '1.0.1' which is higher according to pep386. verlib.NormalizedVersion('1.0a3') < verlib.NormalVersion('1.0.1') holds true by the way. But conda install/update drags in the old one.
Can be reproduced with this binstar channel/package:
https://binstar.org/omnia/pyemma

**Comment by asmeurer** [comment]
I only see the one version of pyemma. I guess you removed the other one. You can add it back in and remove it from the main channel if you don't want people to get it.

**Comment by marscher** [comment]
sorry, the files are gone now and there is no way to restore them.

**Comment by marscher** [comment]
I've tried to reproduce it with the same versions (1.0a3 and 1.0.1) in a separate channel, but now it works as expected.

**Comment by asmeurer** [comment]
Can you install the 1.0.1 version on binstar? Conda does skip packages that aren't installable for one reason or another (like inconsistent dependency metadata).

**Comment by marscher** [comment]
yes, but having the omnia channel still active. So the dependencies are 
the same for both channels. I will try to reproduce the whole version 
history tomorrow.

**Comment by asmeurer** [comment]
Should be fixed by https://github.com/conda/conda/pull/1601.
