### ISSUE TITLE
A warnings field in a package

### ISSUE THREAD

**Issue by isuruf** [conda/conda#9159]
I'd like to propose a warnings field in the package repodata.
Conda would print the warnings field of a package when a package installed into an environment.

A use case would be when a package is deprecated or unmaintained, we need a mechanism to tell the users this without rebuilding the package and adding an activate script.

If there was a field like this we can patch the repodata to add to this field which would be empty by default.

**Comment by kalefranz** [comment]
I’m +1 on this, with some caveats.

Just like with post-link scripts, at some point we (the Conda community) will probably have to deal with something similar to https://news.ycombinator.com/item?id=20838078. Guess we should watch what npm does and how things work out for them, then learn from their lead.

If we do implement this, I would like to see some type of character limit being defined for the field that’s enforced by `conda index`. We need to keep repodata as slim as possible for performance reasons. I’d propose 140 characters. Worked for tweets for years; should be sufficient for this.

**Comment by isuruf** [comment]
140 characters works for me.

About ads, this is already possible with activate scripts, so I'm not sure whether this changes anything.
