### ISSUE TITLE
Theoretical improvement (for corner case of when hardlinks are not possible)

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#9171]
It seems that conda will try to hardlink every file when it installs a package falling back to copying. ISTM that this determination only need happen once.

Ping @kalefranz incase I've overlooked something and for any implementation tips (should he think this a good idea).

In all honesty it needs measuring.

**Comment by kalefranz** [comment]
If I understand the intent here correctly, it ideally does only happen once right now.

https://github.com/conda/conda/blob/258322fc72a9fd695d018f01428a511fb6212cf3/conda/core/link.py#L49-L59

Actually that's not quite true. It ends up being determined once for each package being linked.

https://github.com/conda/conda/blob/258322fc72a9fd695d018f01428a511fb6212cf3/conda/core/link.py#L290-L291

The need for once-per-package comes from dealing with multiple package caches, some of them potentially read-only (certain OSes by default do not allow creating hard links from non-writable paths).

The fallback path at

https://github.com/conda/conda/blob/258322fc72a9fd695d018f01428a511fb6212cf3/conda/gateways/disk/create.py#L359-L369

to `copy()` should really only be a safety measure when that `create_link()` function is used in UnlinkLinkTransactions.  I think there may be other cases where we create one-off hard links (not during the transaction) where we rely on the fallback behavior.

**Comment by mingwandroid** [comment]
Thanks @kalefranz I may well have been mistaken then. It probably logged once per package. Still, we could memoize which pkg_dirs are not writable but I guess it'd make little odds.
