### ISSUE TITLE
"conda env export" command errors when creating an environment using the "--prefix" flag.

### ISSUE THREAD

**Issue by zkaufman** [conda/conda#9173]
If I create a conda environment in the traditional way, I get the expected behavior when using "conda env export" command. For example:

`$> conda create -n cheetah_test1 cheetah`
`$> source activate cheetah_test1`
`$> conda env export > cheetah_test1`

But if I create the environment using the "--prefix" flag (the preferred way at my workplace), then "conda env export" command fails:

`$> conda create --prefix /tmp/cheetah_test2 cheetah`
`$> source activate /tmp/cheetah_test2`
`$> conda env export > cheetah_test2`
`CondaValueError: Invalid environment name: '/tmp/cheetah_test2'`
`  Characters not allowed: (u'/', u' ', u':')`

This is with the following version of conda:
`conda --version`
`conda 4.6.7`

**Comment by soapy1** [comment]
This is fixed in the latest conda
