### ISSUE TITLE
Channel explanation not clear

### ISSUE THREAD

**Issue by datatalking** [conda/conda#9176]
In the documentation page for 'Managing Channels'

Unless you know what a channel is, the current documentation never actually describes what a channel actually is or what traffic it is involved with.

Yes there is descriptions of parts of it but I feel it should give a quick "this is channels, they do these things and further info can be found here"

I would like to offer to complete this documentation, as a user of Conda for two years, it has really helped and I would like to give back with my time.

Can I help do this?

**Comment by rrigdon** [comment]
The docs have more info about channels now. Thanks for your contribution!
