### ISSUE TITLE
standardize activate and deactivate

### ISSUE THREAD

**Issue by spara** [conda/conda#9177]
With conda 4.5.12 and the upcoming 4.6 release, activating and deactivating for all platforms will be:

```
$ conda activate myenv

$ conda deactivate
```

replace all references to `source activate myenv` with `conda activate myenv` and remove all Windows references of `activate`

**Comment by rrigdon** [comment]
https://github.com/conda/conda/pull/9334

**Comment by rrigdon** [comment]
https://github.com/conda/conda/pull/9334
