### ISSUE TITLE
Conda tab completion

### ISSUE THREAD

**Issue by adrienpacifico** [conda/conda#9178]
[Conda doc](https://conda.io/docs/user-guide/configuration/enable-tab-completion.html) state that tab completion is deprecated since Conda 4.4 .

Does this mean that Conda is not supposed to work with tab completion ?

(Fresh install on brand new Mac, tab completion is not working) 

Why is tab completion deprecated ? I tend to expect bash command line programs to always have so sort of tab completion. Can someone explain ?

Best

**Comment by laggardkernel** [comment]
There has been a zsh completion plugin since 2015. 

https://github.com/esc/conda-zsh-completion

**Comment by imsodin** [comment]
@tartansandal I just grabbed your bash completion file - thanks a lot for it!

One issue I have is that when I do not have a conda environment activated yet, on completion I get

```
$ conda acTraceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named conda
```

What I would expect is that it simply doesn't work but doesn't throw an error (muscle memory will still make me hit TAB). Of course an alternative would be for it to determine where conda is installed and still work fine, but I guess that's a lot of work for not much gain.

**Comment by tartansandal** [comment]
Thanks for the heads up @imsodin !
There is a PR https://github.com/conda/conda/pull/9249 that fixes this and some other edges cases. 
You can grab a copy of the patched completion code from https://raw.githubusercontent.com/tartansandal/conda/harden-bash-completion/conda/shell/etc/bash_completion.d/conda

**Comment by tartansandal** [comment]
For those that are interested, you can now install the above completion facility as a conda package: 
```
conda install -c tartansandal conda-bash-completion
```
I've been testing this against conda version 4.7 and it seems pretty solid now.  If you spot any bugs, please raise an issue at https://github.com/tartansandal/conda-bash-completion.

Happy Hacking :smile:

**Comment by AMR-** [comment]
To those who have this issue, consider upgrading and looking at https://github.com/tartansandal/conda-bash-completion
