### ISSUE TITLE
Documenting conda revisions

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#9180]
An incredibly useful feature of `conda` that has been very helpful for getting out of a bind is the `conda` revision feature. However the documentation on this is relatively spartan and Google searches for this information usually turn up other people's blogposts. It would be very helpful to have this information in the `conda` docs with some examples.

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#restoring-an-environment

Thanks for the feedback!

**Comment by jakirkham** [comment]
Awesome! Thanks for those docs.

Actually found myself needing this feature the other day.

Will be good to point others here in the future 🙂
