### ISSUE TITLE
add info on shell changes from 4.4 changelog to docs

### ISSUE THREAD

**Issue by electronwill** [conda/conda#9181]
https://github.com/conda/conda/blob/master/CHANGELOG.md#recommended-change-to-enable-conda-in-your-shell

old:

```
export PATH="/opt/conda/bin:$PATH"
```

new:

```
sudo ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
```

Also info on pinning conda to a single channel.

**Comment by Anoop01234** [comment]
@electronwill please provide the necessary info for me to proceed further!
