### ISSUE TITLE
Add documentation for run_constrained feature

### ISSUE THREAD

**Issue by philippjfr** [conda/conda#9182]
Conda has had the ability to define optional dependencies for a while now, something that I completely missed because it doesn't seem to be documented anywhere. There are already a number of comments on related issues/PRs that ask if and where this feature is documented (https://github.com/conda/conda/issues/1696 and https://github.com/conda/conda-build/pull/2001), so I thought I'd open an actual issue. Apologies if I somehow missed it and it is actually documented somewhere.

**Comment by rrigdon** [comment]
Thanks for opening the issue. Documentation about run_constrained can be found at https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained

Please let me know if there is additional information about run_constrained that you need.

**Comment by philippjfr** [comment]
Thanks @rrigdon, glad this was added!
