### ISSUE TITLE
Improve documentation of "channel priority"

### ISSUE THREAD

**Issue by trendelkampschroer** [conda/conda#9183]
The channel priority documentation (https://conda.io/docs/user-guide/tasks/manage-channels.html)
states that for conda versions 4.1.0 and later 

"[...] 
Conda collects all of the packages with the same name across all listed channels and processes them as follows:

1) Sorts packages from highest to lowest channel priority.
2) Sorts tied packages—same channel priority—from highest to lowest version number.
3) Sorts still-tied packages—same channel priority and same version—from highest to lowest build number.
4) Installs the first package on the sorted list that satisfies the installation specifications.
[...]"

I am having trouble understanding 2):

When do two channels have the same priority?

If I do "conda config --get channels" then I get a list of all channels sorted from highest to lowest priority (as far as I understood the output). Is that correct? If so then how can there be two channels with the same channel priority?

Assume I have two channels "A" and "B" with channel priority "A" > "B", where "A" contains package "x" version 1.0.0" and and "B" contains package "x" with versions 1.0.0 and 1.0.1, if I do "conda install x-1.0.1" then conda will install "x" from the lower priority channel "B", is that correct? Is the same also True, if I use conda env create with an environment.yml file specifying "x-1.0.1"?

 I'd be glad, if someone could clear this up for me. Maybe it would be helpful to add some more examples to the documentation clarifying the behaviour of channel priority in these cases.

Thanks a lot for your time!

**Comment by rrigdon** [comment]
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

Thanks for your feedback!
