### ISSUE TITLE
environment.yml with channel_priority: strict

### ISSUE THREAD

**Issue by mgsnuno** [conda/conda#9189]
Hi,

It would be nice, in my opinion, to have the option to set `channel_priority` inside environment.yml, the same way it is already possible to set `channels`. This allows the user to specify in one place how he'd like that environment to be built.

This file can be committed inside a repository making it all more contained. Otherwise now I specify in README.md to run `conda config --set channel_priority strict`.

I know the plan is to make `strict` the default before 5.0, but if a user would like it not to be strict for a specific environment, this would make things very clean. Clean from the user point of view, from the conda backend point of view I do not know, hence giving my opinion here.

**Comment by soapy1** [comment]
related to https://github.com/conda/conda/issues/8675

**Comment by mgsnuno** [comment]
Sorry, missed it, closing.
