### ISSUE TITLE
Unable to Activate Environment - EC2 Ubuntu

### ISSUE THREAD

**Issue by BrianMiner** [conda/conda#9194]
I am working in an EC2 ubuntu instance and Anaconda 3 and  `conda 4.5.9`

When I create a new environment, with 

`conda create test pip`

I can see the environment:

base                  *  /home/ubuntu/anaconda3
test                     /home/ubuntu/anaconda3/envs/test

but when I run `conda activate test` I get the following error (all the way at the bottom of this post)

I followed I think the error suggestions with 
`sudo ln -s /home/ubuntu/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh`
`echo "conda activate" >> ~/.bashrc`

to no avail.

**ERROR**:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /home/ubuntu/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /home/ubuntu/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/home/ubuntu/anaconda3/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^
```

**Comment by alphapibeta** [comment]
same error, any help?
