### ISSUE TITLE
.sh extension required for environment variable scripts on *nix

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#9199]
_From @fperez on February 8, 2017 8:21_

The [docs on how to customize environment variables](https://conda.io/docs/using/envs.html#saved-environment-variables) state that "Scripts can be given any name", but through trial and error I found that at least on OSX, they *must* have a `.sh` extension, else they don't get executed.

Either the docs should specify this (for all OSes) or, even better, the restriction on a specific extension should be lifted (and then the docs would be correct).

_Copied from original issue: conda/conda#4566_

**Comment by soapy1** [comment]
this documentation needs to change as per the changes made by https://github.com/conda/conda/pull/9157. This likely won't affect versions of conda before 4.8.0

**Comment by rrigdon** [comment]
Closing this issue since this content is no longer accurate.
