### ISSUE TITLE
List of all conda environment variables

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#9201]
Add a listing in the docs of all the environment variables used by conda with a description of their purpose and an example of how to set it.  Environment variables are scattered throughout the docs are hard to find.  Having a list all in one place can be very helpful.

For example
CONDARC | Location of conda configuration file 
CONDA_ENVS_PATH | List of directories where conda environments may exists or be created.

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html
