### ISSUE TITLE
Clarify how the system .condarc file overrides the users ~/.condarc file

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#9202]
This description in the conda docs only partially explains how the system .condarc file works in conjunction with the users ~/.condarc file?  

_Each user may then use the central conda installation, which will read settings from their own “user” .condarc configuration file located in their home directory. The users’ configuration is limited by the second “system” .condarc file, and the path to it is the same as the root environment prefix displayed by conda info, as shown in the Example admin-controlled installation below._

Does the CONDARC env var override the system .condarc file?

This paragraph is also unclear.  The first sentence says the user can specify more channels but the second sentence says other channels will be blocked?

_When set to true or not specified, then each user will have access to the default channels and to any channels that the user specifies in their local .condarc file. If the user specifies other channels, the other channels will be blocked and the user will receive a message explaining this. See example below._

The Default Channels example may be incorrect.  It shows how to override the default set of available channels but not how to reset what the "defaults" channel resolves to.  I thought it was possible to change what the "defaults" channel resolves to in the .condarc file.

**Comment by rrigdon** [comment]
Info would be at this page: https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html

**Comment by csoja** [comment]
@timsnyder Do you still find the current .condarc configuration documentation confusing?  Or has it improved sufficiently since this issue was created to close it.

**Comment by soapy1** [comment]
addressed in https://github.com/conda/conda/pull/9565
