### ISSUE TITLE
More info about CONDARC env var

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#9203]
The CONDARC env var is a powerful feature of conda but I could only find one obscure reference to in the docs.

I suggested adding a comprehensive section about it and how to effectively use it in the conda Configuration section: http://conda.pydata.org/docs/config.html

When using conda in automated processes in enterprises it is often necessary to use different conda configurations depending on the process and the environment being automated.  The CONDARC env var can be used to maintain various configurations and easily switch between them.

**Comment by soapy1** [comment]
addressed in https://github.com/conda/conda/pull/9565
