### ISSUE TITLE
Include --channel-priority in help documentation for solver mode modifiers

### ISSUE THREAD

**Issue by alimanfoo** [conda/conda#9213]
There are three options that can be used to control the solver mode: ``--strict-channel-priority``, ``--no-channel-priority`` and ``--channel-priority``. Only the first two of these are reported in the output of ``conda create --help``. 

The ``--channel-priority`` option is useful because sometimes a user might want to ensure that flexible channel priority is being used, and override whatever ``channel_priority`` is set in ``.condarc``.

Suggest to include ``--channel-priority`` in the set of documented options for conda CLI, and possibly also consider renaming it to ``--flexible-channel-priority`` for clarity.

**Comment by soapy1** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#strict-channel-priority

**Comment by alimanfoo** [comment]
I meant in the command line help, i.e., what you get if invoke conda --help from the command line. The --channel-priority option is not listed.

**Comment by soapy1** [comment]
Ahh, gotcha that's my bad. Reopening issue

**Comment by alimanfoo** [comment]
No worries, thanks a lot. Also I think it would be worth consider renaming the option from --channel-priority to --flexible-channel-priority for clarity, the current naming caused me some confusion which I could only resolve by digging into the source code.
