### ISSUE TITLE
conda env create suppresses pip errors on windows

### ISSUE THREAD

**Issue by dsm054** [conda/conda#9220]
## Current Behavior

We're suppressing pip errors, making some simple bugs seem mysterious when we're crossing the conda/pip boundary.

When specifying a pip dependency section in an environment file on windows, the batch script created in `conda.utils.wrap_subprocess_call` does not propagate errors in the `python -m pip` call back to the conda process.  These batch files look like

```
@ECHO OFF
@SET PYTHONIOENCODING=utf-8
@SET PYTHONUTF8=1
@FOR /F "tokens=2 delims=:." %%A in ('chcp') do for %%B in (%%A) do set "_CONDA_OLD_CHCP=%%B"
@chcp 65001 > NUL
@CALL "C:\Users\username\Miniconda3\condabin\conda.bat" activate "C:\Users\username\Miniconda3\envs\pip_suppress"
@IF %ERRORLEVEL% NEQ 0 EXIT /b %ERRORLEVEL%
@C:\Users\username\Miniconda3\envs\pip_suppress\python.exe -m pip install -U -r C:\Users\username\condaenv.cxpbrg79.requirements.txt
@chcp %_CONDA_OLD_CHCP%>NUL
```
and we see that we reraise if _activation_ fails, but not if pip installation fails.

This means that `conda_env.pip_util.pip_subprocess`'s call of `conda.gateways.subprocess.any_subprocess`  gets a zero return code even though stderr is not empty, and the branch which _should_ show the error output does not get executed [from pip_subprocess]:

```
    stdout, stderr, rc = any_subprocess(run_args, prefix, cwd=cwd)
    print("Ran pip subprocess with arguments:")
    print(run_args)
    print("Pip subprocess output:")
    print(stdout)
    if rc != 0:
        print("Pip subprocess error:")
        print(stderr)
        raise CondaEnvException("Pip failed")
```

and we don't see what the problem is.

### Steps to Reproduce

Start with an environment.yml like

```
name: pip_suppress
dependencies:
  - python=3.7
  - pip
  - pip:
    - requests==99.99.99
```

which should obviously fail noisily as there is no satisfying version of requests.

Running

```
conda env create -v -f environment.yml
```

generates a bunch of output, ending with:

```
Ran pip subprocess with arguments:
['C:\\Users\\username\\Miniconda3\\envs\\pip_suppress\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\username\\condaenv.l56portt.requirements.txt']
Pip subprocess output:
Collecting requests==99.99.99 (from -r C:\Users\username\condaenv.l56portt.requirements.txt (line 1))

#
# To activate this environment, use
#
#     $ conda activate pip_suppress
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

with no information about the failure.

## Expected Behavior

What should happen is that we see the reason for the failure and a CondaEnvException is raised.  If we modify `wrap_subprocess_call` to include another ERRORLEVEL exit command in the batch file, i.e. if we switch to

```
            fh.write("{}IF %ERRORLEVEL% NEQ 0 EXIT /b %ERRORLEVEL%\n".format(silencer))
            fh.write('{}chcp %_CONDA_OLD_CHCP%>NUL\n'.format(silencer))
```

then we get

```
@C:\Users\username\Miniconda3\envs\pip_suppress\python.exe -m pip install -U -r C:\Users\username\condaenv.cxpbrg79.requirements.txt
@IF %ERRORLEVEL% NEQ 0 EXIT /b %ERRORLEVEL%
```

in the batch file and as a result

```
Ran pip subprocess with arguments:
['C:\\Users\\username\\Miniconda3\\envs\\pip_suppress\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\username\\condaenv.cxpbrg79.requirements.txt']
Pip subprocess output:
Collecting requests==99.99.99 (from -r C:\Users\username\condaenv.cxpbrg79.requirements.txt (line 1))

Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement requests==99.99.99 (from -r C:\Users\username\condaenv.cxpbrg79.requirements.txt (line 1)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0)
ERROR: No matching distribution found for requests==99.99.99 (from -r C:\Users\username\condaenv.cxpbrg79.requirements.txt (line 1))


CondaEnvException: Pip failed
```

in the output, which is a lot more useful.

**Comment by msarahan** [comment]
Thanks for your analysis here.  It certainly seems like you are on the right track.  As you mentioned a PR on gitter, yes please!  If you need help, please let us know.  We really appreciate your effort in improving this wart.

**Comment by dsm054** [comment]
The fix itself is straightforward; figuring out where to test it less so.  I'd have thought conda_env/test_create.py or conda_env/test_env.py would be good candidates, because of the existing example yml files in support/.  Unfortunately the run_command they use doesn't even return a value, much less make it easy to capture the output, unlike the more powerful run_command in tests/test_create.py.

Where's the appropriate place to dump an integration test?

**Comment by msarahan** [comment]
test_create is a pretty good dumpster for integration tests.  The conda_env test files would be ideal, but if their run_command function is not capable enough, then your choices are to either refactor run_command so that the more complete one is available in more places, or do your test in test_create.

The difference there is for historic reasons.  Conda and conda-env were separate projects a while back.  We're slowly working on unifying them and healing that gap, but it's very delicate work.

**Comment by okhoma** [comment]
Any updates on this issue? Was the pull request created/processed?
