### ISSUE TITLE
"Collecting package metadata" cannot proceed and never end

### ISSUE THREAD

**Issue by owenyoung75** [conda/conda#9221]
Hi all, recently updated conda to version 4.7.11, after which, however, 
when I try to install any lib or create a new virtual env, the process stays in the "Collecting package metadata" step, and cannot proceed further at all.

Specifically, when attempt with:
<details open><summary><code>`conda install anylib` or `conda create any_env`</code></summary><p>

Only the following lines appear:

```
/path/to/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Collecting package metadata (current_repodata.json): \
```
</p></details>
And nothing else proceeds (stuck here at least for hours even for a simple new virtual env).

Don't even know what steps to take for examining the case, so not sure what kind of info I should provide here. Could anyone give some hint?

**Comment by jancgreen** [comment]
I have the exact same problem. Is there a way to just reinstall conda without using conda?

**Comment by owenyoung75** [comment]
> I have the exact same problem. Is there a way to just reinstall conda without using conda?

Still not sure what happens, but eventually I just uninstalled by removing the whole anaconda package, and then reinstalled it. As mentioned in the documentation:
"This may not remove all traces of the configuration files and directories from Anaconda and its programs, but it's fine for me now." See this ref: [https://docs.anaconda.com/anaconda/install/uninstall/](url)

**Comment by stijn192** [comment]
I'm also running into the same problem, I'm running into this with conda 4.7.11 installed on Python 2.7.12.

Furthermore, I've got 2 environments a Python 2.7.12 and a Python 3.5.2, and no matter what I do I only run into the 
`Collecting package metadata (repodata.json): \ |` 
error. 

Has anybody else have been able to solve this?

**Comment by jancgreen** [comment]
It seems like a problem with conda 4.7.11.  I had to go to a saved back up to get the old version of anaconda and conda that I was using.
________________________________

**Comment by jeffreyrdcs** [comment]
I am still having the same problem with conda 4.7.12.  Did this problem ever get fixed?  I cannot downgrade my conda package or change any of my environemnts due to the 
`Collecting package metadata (repodata.json)` issue.

**Comment by christakahashi** [comment]
Same with me after updating to 4.7.12-py27_0 from 4.4.10-py27_0

**Comment by kazko** [comment]
Same problem here. Anaconda reinstall didnt solve it

**Comment by jeffreyrdcs** [comment]
I solved it by reverting it back to a very old conda revision of mine (4.3), and then "upgrading" onda to 4.6.11. 
`conda config --set restore_free_channel true
 conda install --revision 6
conda install conda=4.6.11
conda create -n newenv3 python=3.6`

 So far it is still working.  I will update my answer if I encounter further problems

**Comment by Panky03IS** [comment]
I have the same problem. I tried to upgrade python with `conda install python=3.6` and never leaves the collecting metapackage step.

**Comment by karthiknaga** [comment]
I am facing the same issue when trying to install anaconda:
sudo ./Anaconda3-2019.10-Linux-x86_64.sh
Extracting : filelock-3.0.12-py_0.tar.bz2:  96%|\u2589| 279/291 [00:02<00:00, 23.28itExtracting : prometheus_client-0.7.1-py_0.tar.bz2:  96%|\u2589| 280/291 [00:02<00:00,Extracting : traitlets-4.3.3-py37_0.tar.bz2:  97%|\u2589| 281/291 [00:02<00:00, 23.28Extracting : conda-verify-3.4.2-py_1.tar.bz2:  97%|\u2589| 282/291 [00:02<00:00, 23.2Extracting : zict-1.0.0-py_0.tar.bz2:  97%|\u2588\u2588\u2589| 283/291 [00:02<00:00, 23.28it/s]Extracting : anaconda-navigator-1.9.7-py37_0.tar.bz2:  98%|\u2589| 284/291 [00:02<00:Extracting : pytest-doctestplus-0.4.0-py_0.tar.bz2:  98%|\u2589| 285/291 [00:02<00:00Extracting : pyparsing-2.4.2-py_0.tar.bz2:  98%|\u2589| 286/291 [00:02<00:00, 23.28itExtracting : backports.functools_lru_cache-1.5-py_2.tar.bz2:  99%|\u2589| 287/291 [00Extracting : toolz-0.10.0-py_0.tar.bz2:  99%|\u2589| 288/291 [00:02<00:00, 23.28it/s]Collecting package metadata (current_repodata.json): -

**Comment by amapic** [comment]
same for me

**Comment by mmoisse** [comment]
I believe it has to do with this commit 

https://github.com/conda/conda/commit/d28220288524250e7da4ab78f6683b76d04bc07a#diff-06975a3580f21bd34a35f056511af1af

Where the variable `context.repodata_threads` is being introduced. In my enviroment `context.repodata_threads` is empty so a ThreadLimitedThreadPoolExecutor is being created with 0 threads causing an indefinite waiting time...

So I changed

https://github.com/conda/conda/blob/f1e707cf5b20a93a8376ca5b946c02944a79c0f6/conda/core/subdir_data.py#L101-L103

To

https://github.com/mmoisse/conda/blob/33f5ead15893e220c0d291b297cda5c8f4d90419/conda/core/subdir_data.py#L101-L103

```
 Executor = (DummyExecutor if context.debug or context.repodata_threads < 1 
             else partial(ThreadLimitedThreadPoolExecutor, 
                          max_workers=context.repodata_threads)) 
```

**Comment by lgsaber** [comment]
@mmoisse Thanks a lot! This fixed the problem.

**Comment by ashleymaeconard** [comment]
I am having the same problem and I want to try this solution but cannot access this file conda/conda/core/subdir_data.py. I only hav e subdir_data.pyc within for example, /anaconda2//pkgs/conda-4.5.4-py27_0/lib/python2.7/site-packages/conda/core/subdir_data.pyc. Do I need to uninstall conda and reinstall another version (say directly from GitHub) to be able to change subdir_data.py?

**Comment by mmoisse** [comment]
You can use the following command to find the file you need to edit

```
dir=$(dirname `which conda`); find ${dir}/../lib -name "subdir_data*"
```

For me it was `/local/share/bcbio/anaconda/bin/../lib/python3.6/site-packages/conda/core/subdir_data.py`

**Comment by ashleymaeconard** [comment]
This fix instantly worked for me, thank you for your prompt response!

**Comment by ceb8** [comment]
As another data point, I recently upgraded to conda 4.8.2, encountered this issue, and was able to fix it in the same way.

**Comment by NickyBar** [comment]
Thank you!! @mmoisse    I was so grateful to find this solution.  It worked for me, too.  

TIP:  Make sure you update that latest _subdir_data.py_ (the file will have the date that you last did the conda upgrade).

**Comment by ariesandes** [comment]
Well. I am a mac user. Anaconda and other Coda commands hangs too until ... I found my security network monitor (Little Snitch, Hands Off!, etc) block conda and anaconda. Solution: I stop those monitor and Anaconda-Navigator and Coda works fine! Then I stop Anaconda,  run those monitor again, run again Anaconda-Navigator and set up the permissions on my security network monitor (for python 2.7 or 3.7). From then all is ok. No more hangs.

**Comment by kalefranz** [comment]
Code change needed is as described in https://github.com/conda/conda/issues/9221#issuecomment-571161529.

**Comment by hzfmer** [comment]
I tried the fix above https://github.com/conda/conda/issues/9221#issuecomment-571161529, but only got
> TypeError: '<' not supported between instances of 'NoneType' and 'int'

It seems in my enviroment `context.repodata_threads` is also empty, but then why you have no problems comparing a "NontType" to "int"?

This doesn't work for me with conda 4.8.3 on RedHat 7.7.

**Comment by mmoisse** [comment]
@hzfmer 

You might then try the following, simply change 

https://github.com/conda/conda/blob/f1e707cf5b20a93a8376ca5b946c02944a79c0f6/conda/core/subdir_data.py#L101-L103

To

    Executor = DummyExecutor

Good luck with it.

**Comment by hzfmer** [comment]
Thanks, @mmoisse, but it doesn't  help for me..
Conda still fails because of something like frozen environment:
>conda install vtk
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

(It might successes eventually, but no one likes to wait for hours just to install one package)
I guess it is not exactly the same issue, though the variable was "Nonetype" and supposed to cause some problem there.

**Comment by SuperStacie** [comment]
What is confusing that new installation seems working as expected. But in one old installation has to change ==1 to < 1, and viola it starts working.

**Comment by SuperStacie** [comment]
How long has it been, like about 10 months and the issue is still open?

**Comment by ls-lxx** [comment]
> @hzfmer
> 
> You might then try the following, simply change
> 
> https://github.com/conda/conda/blob/f1e707cf5b20a93a8376ca5b946c02944a79c0f6/conda/core/subdir_data.py#L101-L103
> 
> To
> 
> ```
> Executor = DummyExecutor
> ```
> 
> Good luck with it.

the same problem and solve it by changing ”Executor = DummyExecutor”

**Comment by numeric-lee** [comment]
Have experienced the same problems. Today, after waiting three hours, I hit Control C (intending to execute) and it finished installing the package in a few seconds

**Comment by astooke** [comment]
hit the same problem today when trying to install anaconda in the first place, which would not complete.  worked my way backwards through the installer archive and the latest one that worked was https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh

**Comment by superbspeed** [comment]
I got this error when trying to run reticulate in Kubernetes. As others pointed out, this fixed it:

`Executor = DummyExecutor`

**Comment by chushan89** [comment]
My conda was updated from 4.8.3 to 4.9.2, by using ``` conda update -n base -c defaults conda```. This error occurs. I tried the tricks of modifying Executor in subdir_data.py, downgrading conda and etc, , however, the error was still there.

Eventually, my problem was fixed by downgrading 'urllib3' to 1.25.8. where the package was downloaded manually from [anaconda](https://repo.anaconda.com/pkgs/main/linux-64/) and installed by ```conda install ~/Downloads/urllib3-1.25.8-py37_0.tar.bz2```

Wish this mght be useful for someone. My system is  Ubuntu 20.04.1.

**Comment by zazgf** [comment]
I have the same problem, then I sovled the problem by remove added channels.
`onda config --remove channels https:xxxx`

**Comment by jbrinchmann** [comment]
I was trying to install anaconda anew on a Linux machine today and had the same experience as @astooke - only going back to the 2019.03 version allowed me to  install conda. Unfortunately upgrading conda from 2019.03 continues to hang with a 'Collecting package metadata" message but creating a new environment works fine.

**Comment by jiaxiaosong1002** [comment]
> hit the same problem today when trying to install anaconda in the first place, which would not complete. worked my way backwards through the installer archive and the latest one that worked was https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh

This solves my problem and a big thank you after trying to install anaconda3 for one night on one linux server (which I have successfully done previously for tens of times...)

**Comment by aw-west-defra** [comment]
I had this problem, it only hangs if I use `--channel defaults`.  I solved this using:
```
conda config --prepend channels conda-forge
conda config --prepend channels main
```

**Comment by aldrinfernandes** [comment]
This issue is caused due to low ram, can be be fixed in one of the blow ways

- Install more RAM
   OR
- Fix with swap location using below code [Link to post](https://paulshipley.id.au/articles/coding-tips/add-swap-space-to-amazon-lightsail/)

> `sudo fallocate -l 1G /swapfile `
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile `
> `sudo swapon /swapfile` 
> `sudo cp /etc/fstab /etc/fstab.bak`
> `echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab`

**Comment by sampellino** [comment]
> hit the same problem today when trying to install anaconda in the first place, which would not complete. worked my way backwards through the installer archive and the latest one that worked was https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh

**THANK YOU!** I installed Conda successfully for the past month or so on several different WSL and VM instances, and suddenly as of yesterday I was stuck on "collecting metadata". I even left it overnight and it never finished. 

Running this earlier this morning solved my issues:
```
wget https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
bash ./Anaconda3-2019.03-Linux-x86_64.sh
#go through prompts
sudo reboot
conda update -n base conda #update to the latest version of conda
#go through prompts
```

**Comment by justusrk** [comment]
You might also face this issue if your RAM is limited. Possibly by ulimit or something similar. 

A ulimit of 3GB was causing the issue for me. I resolved the issue by providing more RAM to the process.

**Comment by denfromufa** [comment]
same issue here - I had to completely logout and login back then it was fixed 🤷‍♂️

**Comment by chrisEisenhartBitscopic** [comment]
I just ran into this issue, none of the above fixes are working and it doesn't give me a lot to work with for debugging.
