### ISSUE TITLE
Portable miniconda install

### ISSUE THREAD

**Issue by ryancshaw** [conda/conda#9224]
I am having trouble with this one, any help would be appreciated!

I want to install and run miniconda from my flash drive. I installed in a folder using

NOTE: I changed the name of the installer to 'miniconda3_installer'.
`PS E:\CS497\miniconda> .\miniconda3_installer.exe /S /InstallationType=JustMe /RegisterPython=0 /AddTopath=0 /NoRegistry=1 /D=E:\CS497\miniconda\ | Out-Null`

Once installed, I can't use the 'conda' command as there is no path.

I am trying to get this to work because I don't have a laptop, and the computers we use reset after every sign out, so no editing registry to home files either. This includes .bashrc in '\etc\'.

Is it possible to have a fully portable miniconda install?

**Comment by mingwandroid** [comment]
Are you intending to use the same flash drive on different machines/OS installations where it will mount at different drives (or mount points in a NTFS filesystem)? If so then that will not work because the software in the Anaconda Distribution is not 'trivially' relocatable.

If you are intending to install conda to a flash drive such that it's always mounted the same way then yes, there's absolutely no problem with this. I recommend NTFS as your filesystem. You need to activate conda though. From `cmd.exe run `call E:\CS497\miniconda\Scripts\activate`.

I am not sure about your reference to `.bashrc` as you seem to be using Windows. Are you using the MSYS2 shell or Git for Windows here (or something else?)

**Comment by ryancshaw** [comment]
Do you mean the same drive letter path? If so, I only need it for in class and to hold my python files. I will be using Jupyter notebook, so that's the next step after I get this working. I am reformatting to NTFS and reinstalling.

I'm a little confused what to do once I run that command though.

**Comment by mingwandroid** [comment]
Well what you are trying to do is no different from any other installation so please just follow the instructions!

**Comment by ryancshaw** [comment]
I got it to work!

I downloaded anaconda instead of conda, just for the added capabilities. miniconda was more for testing purposes due to its smaller size.
 
Then I ran in powershell in my drive:
`.\Anaconda3_installer.exe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /InstallationType=JustMe /S /D=.\Anaconda\ | Out-Null`
NOTE: I renamed the installer to `Anaconda3_installer.exe`

This silently installed Anaconda in a folder named Anaconda in that directory.

I then used your command to activate anaconda and fully updated it.
`.\Scripts\Activate`
`conda update conda`
`conda update anaconda-navigator`

Then I restarted my computer (just to be safe), and jupyter notebook ran immediately!
`D:\CS497\ANACONDA>.\Scripts\Activate

(base) D:\CS497\ANACONDA>jupyter notebook
[I 09:10:13.083 NotebookApp] Writing notebook server cookie secret to C:\Users\rshaw\AppData\Roaming\jupyter\runtime\notebook_cookie_secret`

I tried this on the lab computer this morning and it still worked and had my test notebook saved!

I will update if I run into any other issues, but I realized today that the drive letter path for my home computer would be E: and for the lab computer, it was D: . Hopefully that doesn't matter in the long run, but it's working now!

Thank you for your help!

**Comment by mingwandroid** [comment]
If D: vs E: does matter (and it will, depending on what you run), and if your sysadmins have given you permission, you might try to mount it to the same place on each computer via https://www.windowscentral.com/how-mount-hard-drive-folder-windows-10

**Comment by mingwandroid** [comment]
After restarting, did you activate again? You need to each time (or use the Anaconda Prompt).

**Comment by ryancshaw** [comment]
I figured it out. The first lab computer I used was actually 32-bit. So if you are interested, those are the error for when you try to run 64 bit anaconda jupyter notebook on a 32 bit system.

**Comment by mingwandroid** [comment]
Great!
