### ISSUE TITLE
Issue with OS Specific Installs

### ISSUE THREAD

**Issue by achapkowski** [conda/conda#9227]
I have an environment.yml and I need to limit specific install based on OS.

In this past, we would do this:

```
name: awesome_env
channels:
- anaconda
- conda-forge
- dhirschfeld
- defaults
dependencies:
- pandas >=0.23
- pip
- python=3.6
- beautifulsoup4
- requests
- requests-kerberos==0.11.0
- requests-toolbelt
- requests_ntlm
- requests-oauthlib
- requests-negotiate-sspi  [win]
- winkerberos  [win]
- pip:
  - unittest-xml-reporting
  - setuptools >=38.6
  - sphinx-rtd-theme
  - pytest-blockage
  - junit2html

```

The `[win]` tag no longer works, so how do I limit dependencies for OS that are linux/mac based?

**Comment by mfansler** [comment]
This is supported in `conda-build` for the meta.yml, but has never been supported in `conda-env` for environment.yml. However, it is an open feature request (see Issue #8089).
