### ISSUE TITLE
Windows: All Scripts\*.exe must unset PYTHONHOME

### ISSUE THREAD

**Issue by Roffild** [conda/conda#9230]
```bat
set PYTHONHOME=123
Scripts\conda.exe

Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003618 (most recent call first):
```
PYTHONHOME should be ignored or deleted when the CLI starts. This will solve the old problem with PYTHONHOME.

The changes that I proposed in the https://github.com/conda/conda/issues/9229 should be taken into account.

**Comment by mingwandroid** [comment]
We absolutely must never mess with `PYTHONHOME` because if we do, we break people who want to use it in our ecosystem for legitimate purposes. If you have it set incorrectly then that is up to you to fix.

**Comment by Roffild** [comment]
I am using PYTHONHOME. In the example, I set PYTHONHOME to a random value. But in reality PYTHONHOME value I have the right.

PYTHONHOME = c:\Anaconda\envs\pycharm\
But Conda package in c:\Anaconda

I have to do ```bat set PYTHONHOME= ``` before upgrading Conda.

> We absolutely must never mess with PYTHONHOME because if we do, we break people who want to use it in our ecosystem for legitimate purposes.

I am from these people. When using the Conda CLI, PYTHONHOME should be ignored. If I need to use Conda with PYTHONHOME, then I will do it in myconda.py

Set the status to Open of this bug.
