### ISSUE TITLE
conda activate / source activate removes miniconda3/bin from $PATH

### ISSUE THREAD

**Issue by nelson-liu** [conda/conda#9264]
## Current Behavior
My $PATH after a fresh install (where I selected "yes" to having conda init set things up in my .bashrc):

```
(base) nfliu at sc in ~
$ echo $PATH
/u/scr/nfliu/miniconda3/bin:/u/scr/nfliu/miniconda3/condabin:/sailhome/nfliu/bin:/sailhome/nfliu/.dotfiles/bin:/sailhome/nfliu/.local/bin:~/.dotfiles-local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Note that `/u/scr/nfliu/miniconda3/bin` is there.

My $PATH after activating an environment (either with `conda activate` or `source activate`)

```
(base) nfliu at sc in ~
$ conda activate fairseq
(fairseq) nfliu at sc in ~
$ echo $PATH
/u/scr/nfliu/miniconda3/envs/fairseq/bin:/u/scr/nfliu/miniconda3/condabin:/sailhome/nfliu/bin:/sailhome/nfliu/.dotfiles/bin:/sailhome/nfliu/.local/bin:~/.dotfiles-local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

```
(base) nfliu at sc in ~
$ source activate fairseq
(fairseq) nfliu at sc in ~
$ echo $PATH
/u/scr/nfliu/miniconda3/envs/fairseq/bin:/u/scr/nfliu/miniconda3/condabin:/sailhome/nfliu/bin:/sailhome/nfliu/.dotfiles/bin:/sailhome/nfliu/.local/bin:~/.dotfiles-local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Note that `/u/scr/nfliu/miniconda3/bin` is *no longer* there, in both cases. This behavior is inconsistent with an install I did on `4.7.10`, where `/u/scr/nfliu/miniconda3/bin` remains after activating an environment.

### Steps to Reproduce
- Install miniconda3 linux 64 bit
- `echo $PATH`
- `conda create -n python=3.6 test`
- `conda activate test`
- `echo $PATH`

## Expected Behavior

`/u/scr/nfliu/miniconda3/bin` should remain in $PATH before and after activating a new environment.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : fairseq
    active env location : /u/scr/nfliu/miniconda3/envs/fairseq
            shell level : 2
       user config file : /sailhome/nfliu/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /u/scr/nfliu/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /u/scr/nfliu/miniconda3/pkgs
                          /sailhome/nfliu/.conda/pkgs
       envs directories : /u/scr/nfliu/miniconda3/envs
                          /sailhome/nfliu/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.4.0-137-generic ubuntu/16.04.5 glibc/2.23
                UID:GID : 19658:100
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /u/scr/nfliu/miniconda3/envs/fairseq:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py36_1    defaults
cffi                      1.12.3                   pypi_0    pypi
cython                    0.29.13                  pypi_0    pypi
fairseq                   0.8.0                     dev_0    <develop>
fastbpe                   0.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.17.2                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_1    defaults
pip                       19.2.2                   py36_0    defaults
portalocker               1.5.1                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
python                    3.6.9                h265db76_0    defaults
readline                  7.0                  h7b6447c_5    defaults
regex                     2019.8.19                pypi_0    pypi
sacrebleu                 1.4.1                    pypi_0    pypi
setuptools                41.0.1                   py36_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
torch                     1.2.0                    pypi_0    pypi
tqdm                      4.36.1                   pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
wheel                     0.33.4                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by douglowe** [comment]
Should this not be the expected behaviour? Otherwise there's a risk of getting conflicts between environments.

I've found that conda deactivate can, sometimes, fix the base path in $PATH, if called with an argument. Perhaps you've previously encountered this bug too? https://github.com/conda/conda/issues/9280

**Comment by nelson-liu** [comment]
Hm, I wasn't calling this with an argument. This seems like a bug because you can use `source activate x` to activate env x, but you can't use `source deactivate` to get out of `x`.

**Comment by mfansler** [comment]
This is the expected behavior. If you want to keep an env's `bin` dir on the `PATH` when activating another env, then use the `--stack` flag. E.g., `conda activate --stack fairseq`

**Comment by nelson-liu** [comment]
Maybe I'm misunderstanding, but `/u/scr/nfliu/miniconda3/bin` isn't a particular environment's `bin` dir, right?

Regardless, it seems rather un-ergonomic to be able to do: `source activate x` from (base), but not from any other environment?

**Comment by mingwandroid** [comment]
> Maybe I'm misunderstanding, but /u/scr/nfliu/miniconda3/bin isn't a particular environment's bin dir, right?

No, it absolutely is, it's the `base` environment, and, apart from not being in the `envs` subdir it is like any other environment.

**Comment by mingwandroid** [comment]
You can source activate x from any environment, yes, but to do that conda needs to be the right thing and that thing (on Unix or MSYS2) is a bash function. If your conda is *not* a bash function then you are not activating things correctly (`type conda`) to see this.

**Comment by msarahan** [comment]
`source` requires that the root folder's bin path is always on PATH. That leads to undesirable fall-through behavior. With conda 4.4+, using conda activate instead is preferable. Conda is a shell function in this implementation, so it doesn't need to be on PATH.

**Comment by nelson-liu** [comment]
So, in conda 4.4+, it's expected that the root folder's bin path is not always on $PATH (namely, it is removed from the $PATH when another environment is activated)?

**Comment by mingwandroid** [comment]
Yes, unless you use stacking as explained [here](https://github.com/conda/conda/issues/9264#issuecomment-536775273)

**Comment by nelson-liu** [comment]
Ok, got it. This answers my question, thanks for your patience!
