### ISSUE TITLE
Passing a .condarc directly into conda commands

### ISSUE THREAD

**Issue by 3tilley** [conda/conda#9269]
After many years of maintaining .condarc files in an organisation, we're coming to the opinion that it's simply too difficult to rely on users maintaining their individual condarcs, and across many different boxes it's too painful to keep those condarcs under a centrally managed folder that are acceptable to all of the different projects. We would really like to include the .condarc files along with the source code of the projects that use them. Is there a way to force conda commands (within build scripts we control) to use a .condarc we supply and override anything on the system, or in the home directory of the user?

**Comment by soapy1** [comment]
You can set the `CONDARC` environment variable to the path to your desired condarc. However, as I understand it, this will not overwrite any other condarc. So, if a user has a`~/.condarc` and an environment variable `$CONDARC=PATH_TO_PROJECT/condarc` the two configurations will be merged.

**Comment by 3tilley** [comment]
Thank you, I will give this a go!
