### ISSUE TITLE
Allow skipping channels when servname "not known"

### ISSUE THREAD

**Issue by jaklan** [conda/conda#9274]
Hi,

I've such an use-case - I have a `environment.yml` file with 4 defined channels:
```
channels:
  - http://INTERNAL_REPOSITORY/conda-main-remote
  - http://INTERNAL_REPOSITORY/conda-forge-remote
  - defaults
  - conda-forge
```

The first two repos are in our corporate Intranet. Everything works smoothly when I'm in the office or use our VPN, but when I don't - I get such an error:
```
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://repository.intranet.roche.com/artifactory/api/conda/conda-main-remote/osx-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='repository.intranet.roche.com', port=80): Max retries exceeded with url: /artifactory/api/conda/conda-main-remote/osx-64/repodata.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10377a4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"))
```

and env is not created. The error is obvious, but I imagine there should be an option (as a default or as an additional CLI flag) which allows skipping such errors and proceeding with the next channel from the list, so people would still be able to download packages from `defaults` and `conda-forge` channels for local dev needs without modifying the `environment.yml` file.

**Comment by kalefranz** [comment]
If this were me, I wouldn’t want such “magic” behavior as falling through, as your channel setup implies. I’d want to be more explicit about where packages are coming from.

One config parameter that’s helpful here is `migrated_channels` (I think that’s the correct name). However, you’d have to put in configuration for each of the channels in `defaults`, which seems cumbersome.

So, seeing what you’re doing here, the most ideal situation would be if `main` was actually a mirrored channel on anaconda.org from `pkgs/main`, and then you could just use the `channel_alias` config parameter, and switch that around based on context.

**Comment by jaklan** [comment]
@kalefranz thank you for the answer!

Such "magic" shouldn't be a real issue, because `conda-main-remote` and `conda-forge-remote` are just proxy servers for `main` and `conda-forge` (we just have to cache packages due to some validation requirements). That's why an additional flag would be great, because we would be able to use it locally and not use it e.g. when building a Docker image.

Yeah, that's exactly what I thought as a solution for now - editing `channel_alias` in .condarc file inside a project and:
- setting a `CONDARC` envar to `./.condarc` to use internal repo
- unsetting a `CONDARC` envar to use public repo

But it's still far less convenient than a potential CLI flag. 
And I see one potential problem - in such a scenario is there any way to map e.g. `conda-forge` to internal repo called e.g. `conda-forge-remote` (so to the repo with different name)? I can imagine the scenario, when we want to use some channel, but that name is already occupied in our artifactory (seems pretty unlikely, especially the namespace for conda repos is not common with other repo types, but... still possible). I know there's `custom_channels` option, but it only allows to use different alias than in `channel_alias` - I see no option to just map channel name.

**Comment by kalefranz** [comment]
In my initial reply, I saw your username and thought you were someone different; sorry bout that.

Going to talk around your reply for a second... All Conda channels get parsed into something like `channel_location` + `channel_name`. All channels have both names and locations. The name of a channel is pretty integrally linked to the identity of a package. The channel location can be moved and changed via configuration (`channel_alias`, `migrated_channels`, etc.). The importance of the channel name in a package’s identity is context for my previous response.

So:

> in such a scenario is there any way to map e.g. `conda-forge` to internal repo called e.g. `conda-forge-remote`

No. Because `conda-forge` is the name of a channel, and `conda-forge-remote` also ends up being a channel name, and it’s a different channel.

However, you _can_ change the _location_ of the channel named `conda-forge`, say to `http://internal_repository`, by using the various config parameters.

**Comment by jaklan** [comment]
@kalefranz yeah, that's exactly as I understand it. Well, the workaround seems a bit dodgy, but I'll try to set it up. I leave the request open, but if you're sure there's no way to implement such a functionality - please close it.
