### ISSUE TITLE
source deactivate. error >> -bash: deactivate: No such file or directory

### ISSUE THREAD

**Issue by CimXin** [conda/conda#9276]
Hello, I have a problem.  I use  ```conda create --name  python27  python=2.7```.
and ```source activate python27```. 
and type ```source deactivate ```.
The teminal report ```-bash: deactivate: No such file or directory ```.
I use the latest version of conda.

conda --version
conda 4.7.12

**Comment by msarahan** [comment]
More info here: https://github.com/conda/conda/pull/9233

Use `conda deactivate` instead. Be sure to read the note call section here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#deactivating-an-environment
