### ISSUE TITLE
Window environment : Not Activated

### ISSUE THREAD

**Issue by Adesoji1** [conda/conda#9277]
C:\Users\soj4y>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load. To activate this environment
please see https://conda.io/activation
Type "help", "copyright", "credits" or "license" for more information.

How do I activate the environment?

**Comment by msarahan** [comment]
Have you read through the link there?

**Comment by Adesoji1** [comment]
I read ut I didn't understand them all I know is that python runs in the base mode in the command prompt alone but complains that I need add to environment. please send the link to rectify this issue, my head is hot

**Comment by Adesoji1** [comment]
> Have you read through the link there?

please provide link

**Comment by soapy1** [comment]
please see https://conda.io/activation

**Comment by Adesoji1** [comment]
I did but still didn't get it

**Comment by soapy1** [comment]
Try a:
```
$ conda init --all
$ conda activate
```

**Comment by Adesoji1** [comment]
Ok

**Comment by Adesoji1** [comment]
Alright
