### ISSUE TITLE
Redact authentication headers in URLs

### ISSUE THREAD

**Issue by jkschin** [conda/conda#9278]
## Current Behavior
If a particular channel contains an auth header of the form `https://:<password>@<url>`, `<password>` will be leaked into the logs and this is a potential security risk.

## Expected Behavior
What should happen is that `<password>` should be redacted.

It seems like the change should be made somewhere in [Channels](https://github.com/conda/conda/blob/master/conda/models/channel.py#L69) and if someone from the team can point me in the right direction, happy to make a contribution.

**Comment by gatesn** [comment]
I think it might be sufficient to redact auth in `conda.common.url.maybe_unquote` - the two places that's called with a potentially unsafe url are when constructing a `CondaHTTPError` and a `ChecksumMismatchError`
