### ISSUE TITLE
Installing conda with "non-standard" umask

### ISSUE THREAD

**Issue by aglahe** [conda/conda#928]
OS: Centos6.5
Using Anaconda 2.0.1 x86_64 instal script

On our servers we have a fairly restrictive umask for directories and files.  Currently set to 0077.  

We noticed that the install, while ok for root, when other users attempted to use python, they would get errors.  We would then need to rectify the permissions on the newly created anaconda install directory (and sub directories).  And even then, we would still get things like:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 2.7.8 :: Continuum Analytics, Inc.

because we didn't set "everything" correct.  Another example, users would get import errors because the permissions set during the install.

Not sure what can be done to prevent, but, maybe to a umask test..and if restrictive, maybe display a warning.

Cheers,
Aaron

**Comment by asmeurer** [comment]
There has been some documentation added about this at http://conda.pydata.org/docs/troubleshooting.html#issue-permission-denied-errors-during-install.
