### ISSUE TITLE
Incorrect use of csh setenv in conda init

### ISSUE THREAD

**Issue by andreasg123** [conda/conda#9283]
## Current Behavior

The following was appended to `~/.tcshrc` (`...` indicates the path to conda):

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if ( -f ".../etc/profile.d/conda.csh" ) then
    source ".../etc/profile.d/conda.csh"
else
    setenv PATH=".../bin:$PATH"
endif
# <<< conda initialize <<<
```

The responsible line is here: https://github.com/conda/conda/blob/master/conda/core/initialize.py#L1236

### Steps to Reproduce

```
conda init tcsh
```

## Expected Behavior

`setenv PATH=` is incorrect. A space should be used instead of an equal sign. Logging in on a system where `conda.csh` doesn't exist produces this error message:

```
setenv: Variable name must contain alphanumeric characters.
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/andreasg/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.6.7.final.0
       virtual packages : __cuda=10.2
       base environment : /opt/jupyterhub/miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/jupyterhub/miniconda3/pkgs
                          /home/andreasg/.conda/pkgs
       envs directories : /home/andreasg/.conda/envs
                          /opt/jupyterhub/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.6.7 Linux/4.15.0-60-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 10094:10000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by soapy1** [comment]
@andreasg123 thanks for the detailed description and solution! Since you've done most of the work already you are more than welcome to submit a PR to fix the problem. This is probably the fastest way to get your fix in, and also you'll get more visible credit for your work. If you are too swamped to submit a PR, that's fine too, we'll get to it eventually, though no promises about when eventually is :/
