### ISSUE TITLE
conda run doesn't escape parameters passed to it

### ISSUE THREAD

**Issue by mattgodbolt** [conda/conda#9288]
## Current Behavior

Running `conda run 'echo' 'hello&goodbye'` results in an error, as the shell invoked in the generated shell file interprets the `&`.

### Steps to Reproduce

```
[mgodbolt@godbolt tmp]$ conda run 'echo' 'hello&goodbye'
hello
/home/mgodbolt/miniconda3/.tmpp12v03hs: line 3: goodbye: command not found
ERROR conda.cli.main_run:execute(39): Subprocess for 'conda run ['echo', 'hello&goodbye']' command failed.  Stderr was:
/home/mgodbolt/miniconda3/.tmpp12v03hs: line 3: goodbye: command not found
```

## Expected Behavior

The same as if `echo 'hello&goodbye'` was executed:

```
[mgodbolt@godbolt tmp]$ echo 'hello&goodbye'
hello&goodbye
```

Or, interestly, if there were spaces around the ampersand:

```
[mgodbolt@godbolt tmp]$ conda run 'echo' 'hello & goodbye'
hello & goodbye
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
[mgodbolt@godbolt tmp]$ conda info

     active environment : None
            shell level : 0
       user config file : /home/mgodbolt/.condarc
 populated config files : /home/mgodbolt/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : /home/mgodbolt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mgodbolt/miniconda3/pkgs
                          /home/mgodbolt/.conda/pkgs
       envs directories : /home/mgodbolt/miniconda3/envs
                          /home/mgodbolt/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.4 Linux/5.2.16-200.fc30.x86_64 fedora/30 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by mingwandroid** [comment]
Hey @mattgodbolt, happy to see you kicking the tyres of conda (I'm a fan of your work and believe we have a friend in common with @KevEdwards - hi Kev!)

`conda run` is quite new and I'd say not quite finished. I'm probably the last person that looked at it though so I'll assign this to myself for now.

For `conda run` to work we need a shell, so we emit a shell script. We need to jump through quite a few hoops in those code-paths too. I think the following change would fix this though:

```
diff --git a/conda/utils.py b/conda/utils.py
index 4b689f888..6e948afc1 100644
--- a/conda/utils.py
+++ b/conda/utils.py
@@ -279,7 +279,7 @@ def quote_for_shell(arguments, shell=None):
                 quote = "'"
             elif "'" in arg:
                 quote = '"'
-            elif not any(_ in arg for _ in (' ', '\n')):
+            elif not any(_ in arg for _ in (' ', '&', '\n')):
                 quote = ''
             else:
                 quote = '"'
```

.. to make poking around at what's going on under the covers of conda when it creates temp files I added an env var called `CONDA_TEST_SAVE_TEMPS`. Set this to `1` and it should prove useful:

`CONDA_TEST_SAVE_TEMPS=1 conda run 'echo' 'hello&goodbye'`

**Comment by mingwandroid** [comment]
(oh yeah, that diff I posted should clear up why adding a ' ' or two makes this work)

**Comment by mattgodbolt** [comment]
Hi @mingwandroid ! Small world, eh? :) Thanks.

Been using `conda` on and off for a few years now, thanks for your work on it!

For now we've just gone and used `<path_to_venv>/bin/thing_we_want_to_run` but it would be nice if we could rely on conda to do it for us!

I haven't thought _too_ much but as I recall escaping  for subshells is incredibly tricky to get right...if you're doing it that way then things like `$FOO` start to be a problem too. Things like `env FOO=123 conda run -- echo \$FOO` ought to output  `$FOO` but if you're not super careful it will output `123`. Maybe that's ok, but it'll be surprising the first time it bites someone :)

```
mgodbolt@a001:~$ echo \$FOO
$FOO
mgodbolt@a001:~$ env FOO=123 ./miniconda3/bin/conda run echo \$FOO
123
```
