### ISSUE TITLE
Fastest way to create a fully specified conda environment

### ISSUE THREAD

**Issue by mrocklin** [conda/conda#9293]
My apologies for misusing this issue tracker to ask a usage question (is there a better place for this?)

I have a valid conda environment on one machine.  I would like to export that environment to a file, and then recreate it as quickly as possible on another identical machine.  I can do that today as follows:

```
machine1$ conda env export -f foo.yaml
machine2$ scp machine1:foo.yaml .
machine2$ conda env create -f foo.yaml
```

However, I suspect that this does lots of safe and mature things that I, being immature and reckless, would prefer to avoid.

```
machine2$ time conda env create -f foo.yaml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.11
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate


real	0m17.120s
user	0m9.696s
sys	0m4.992s
```

Are there additional flags perhaps that I can add to my commands to remove some of these steps?  Really, I just want to get all of the packages listed (either locally, or from a conda repository), assemble them together, and then run whatever finishing up scripts are necessary.

**Comment by mrocklin** [comment]
(I had a misfire when submitting this issue.  The original comment is now a bit longer).

**Comment by jjhelmus** [comment]
There are a few configuration options that may speed up the time required to recreate the environment on the second machine.  These can be set in `.condarc`.

The "Verifying transaction: done" step can be skipped by setting `safety_checks: disabled`.  Additionally, `rollback_enabled: false` may give a slight improvement.  

conda checks for newer versions at invocation, this can be disabled by setting `notifty_outdated_conda: false`.  I do not believe setting `aggressive_update_packages: []` and `add_pip_as_python_dependency: false` will improve performance but for they will remove a few unnecessary code paths for this particular use case.

**Comment by mrocklin** [comment]
Thanks for the response @jjhelmus !  Is it possible to do this without modifying configuration files?  I may want to do this programmatically within Dask workers.

Also, is there a way to skip the solver step?  This environment has presumably already been solved.  I'm happy to have the world fall apart if the file that I pass it is wrong.

**Comment by msarahan** [comment]
Use environment variables: CONDA_SAFETY_CHECKS=0

There is no way to skip the solver, but it is practically instant for a fully determined set of specs anyway.
