### ISSUE TITLE
conda silently fails to install pip dependencies when using multiple yaml files 

### ISSUE THREAD

**Issue by covuworie** [conda/conda#9294]
## Current Behavior
`conda` silently fails to install `pip` dependencies when using multiple yml files. You must duplicate the `pip` dependencies in all yml files for the packages to correctly install. 

### Steps to Reproduce

1. Create a `prod.yml` file with the following contents:
```
name: env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7.3
    - pip=19.2.3
    - pip:
          - wordsegment==1.3.*
```
2. Create a `dev.yml` file with the following contents
```
name: env
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=19.2.3 # stops the warning about pip not being a dependency and EnvironmentLocationNotFound exception
```
3. `conda env create --file=prod.yml --file=dev.yml`
4. `conda activate env`
5. `conda list`

```
# Name                    Version                   Build  Channel
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.2.3                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
```
(pip package not installed)

6. `conda deactivate`
7. `conda remove --name env --all`1
8. Update the contents of the `dev.yml` file to:

```
name: env
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=19.2.3 # stops the warning about pip not being a dependency and EnvironmentLocationNotFound exception
    # have to duplicate the same section that is in prod.yml
    - pip:
          - wordsegment==1.3.1
```
9. Repeat steps 3, 4 and 5.

```
# Name                    Version                   Build  Channel
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.2.3                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
wordsegment               1.3.1                    pypi_0    pypi
```
(pip package installed)

## Expected Behavior

The `pip` package should have been installed at step 5. And certainly `conda`  should not have been silent when the package failed to install. This silence made it extremely difficult for me to reproduce what was happening here. Also, my "hack" of duplicating the `pip` dependencies in the yml files (step 8) shouldn't be necessary to make the packages install.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : env
active env location : C:\Users\COvuworie\Miniconda3\envs\env
shell level : 1
user config file : C:\Users\COvuworie\.condarc
populated config files :
conda version : 4.7.12
conda-build version : not installed
python version : 3.7.3.final.0
virtual packages : __cuda=10.0
base environment : C:\Users\COvuworie\Miniconda3  (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
               https://repo.anaconda.com/pkgs/main/noarch
               https://repo.anaconda.com/pkgs/r/win-64
               https://repo.anaconda.com/pkgs/r/noarch
               https://repo.anaconda.com/pkgs/msys2/win-64
               https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\Users\COvuworie\Miniconda3\pkgs
                C:\Users\COvuworie\.conda\pkgs
                C:\Users\COvuworie\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\COvuworie\Miniconda3\envs
                   C:\Users\COvuworie\.conda\envs
                   C:\Users\COvuworie\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
administrator : False
netrc file : None
offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Empty
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.2.3                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
wordsegment               1.3.1                    pypi_0    pypi
```
</p></details>

**Comment by mfansler** [comment]
The issue is that `conda create` is really only designed to take one YAML file. The example here demonstrates that if multiple files are provided, Conda uses only the last one.

While the parser doesn't seem to care, the signature of the command `conda create` clearly shows `[-f FILE]`, which specifies that there is an option to provide one file. Based on this, I'd say the expected behavior is that an error should be thrown for providing more than one `--file|-f` argument.

**Comment by covuworie** [comment]
I just followed the documentation of the `conda create` command which clearly states:

```--file```

```
   Read package versions from the given file. Repeated file specifications can be passed (e.g. --file=file1 --file=file2).
```

See: https://docs.conda.io/projects/conda/en/latest/commands/create.html

**Comment by mfansler** [comment]
@covuworie sorry I miswrote `conda create` when I meant `conda env create`. I don't think the latter has an option for multiple files. But you are correct that `conda create` indicates that it supports multiple files.  The docs for it say:

      -f FILE, --file FILE  environment definition file (default: environment.yml)

**Comment by covuworie** [comment]
@mfansler I see what you are saying about the documentation. When I try:

```
conda create --file=prod.yml
```
(notice only one file) I get this error:
```
CondaValueError: The target prefix is the base prefix. Aborting.
```
Does conda expect me to provide a prefix in this case?

When I also specify the name of the environment (which is superfluous) I get yet another error. And I certainly don't want to specify any `[package_spec [package_spec ...]]`.

What's interesting is that the main part of the documentation recommends [creating an environment from an environment.yml file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) with the `conda env create` command and only refers to doing it with one file as you say.

**Comment by soapy1** [comment]
Conda is using the name provided in your environment file. You can remove the line `name: env` and in the command line specify the name of the environment `conda create -n new-env --file=prod.yml`

**Comment by covuworie** [comment]
Using this command does not work for me. The following error is reported.

```
CondaValueError: could not parse '- conda-forge' in: prod.yml
```
It seems that the name has to be specified in the yaml file.

**Comment by samtygier-stfc** [comment]
Its worth noting that documentation is missing a section on the `conda env` commands at https://docs.conda.io/projects/conda/en/latest/commands.html . It easy to end up on the `conda create` docs when looking for info on `conda env create` which give the impression that multiple files can be used.

`conda create` can take multiple files, but just package lists not yaml files.

`conda env create` can only take a single yaml file.

So there is currently no way to stack environment files that allows including pip packages.
