### ISSUE TITLE
choice between anaconda prompt vs custom-conda profile in windows terminal

### ISSUE THREAD

**Issue by aster94** [conda/conda#9300]
[Windows Terminal](https://github.com/microsoft/terminal) have the ability to have different terminal with different settings. The anaconda prompt could be integrated "inside" the new windows terminal.
When a new installation of anaconda/conda happens the installer could ask to install the well known anaconda prompt or if we just would like to add a few lines inside our `profile.json` (if the MS terminal app is found)

**Comment by aster94** [comment]
example of a possible conda profile:

```
        {
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
	    "commandline": "powershell.exe -noExit -Command \"& {$Env:Path += '\";C:/Users/vincenzo/Miniconda3/Scripts\"'}\"",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{67fc9f2f-a840-408f-af67-01bd4c328854}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Conda",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : false
        },
```

**Comment by msarahan** [comment]
This seems like a good improvement. I don't think the conda team will have time to focus on this in the near future, though. If you'd like to take a look at a PR, I recommend starting with the recipe that implements the Anaconda prompt: https://github.com/AnacondaRecipes/aggregate/tree/master/console_shortcut-feedstock/recipe

Two tricky things to consider are that conda runs into problems quickly when it is operating on files that are system-wide (can be changed by other apps), and that conda can't directly edit files, only install/replace/remove. You can run post-link script to achieve editing, but the error handling is pretty much nonexistent.  It is extremely hard to anticipate and appropriately act on user systems given these two constraints.

**Comment by aster94** [comment]
I would like to help but unfortunately I don't have the knowledge to do it

**Comment by aster94** [comment]
even better:
`"commandline": "powershell.exe -noExit -Command \"& {$profile = '\"C:/Users/vincenzo/Documents/WindowsPowerShell/profile_conda.ps1\"'; . $profile}\"",`

this way anaconda during installation should only create a new file (better if it is inside conda folder) and write inside this file only this:

```
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Users\vincenzo\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion
```

This would solve the problem of editing/replacing users and system files!

**Comment by aster94** [comment]
ok i got a little bit more deep into it and I made this profile:
It is the same as the original powershell profile exept for the commandLine, name and guid parameters

```
	{
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
	    "commandline": "powershell.exe -noExit -Command \" (& \"$env:USERPROFILE/Miniconda3/Scripts/conda.exe\" 'shell.powershell' 'hook') | Out-String | Invoke-Expression\"",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{67fc9f2f-a840-408f-af67-01bd4c328854}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Conda",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : false
        },
```

now the biggest problem for the conda devs should be to add it to the right place inside `"$env:USERPROFILE/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/profiles.json"`
