### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by xobs** [conda/conda#9307]
The documentation has some broken links.

In particular: https://conda.readthedocs.io/en/latest/#building-your-own-packages links to http://docs.continuum.io/conda/build.html which doesn't exist

The top of the page has a link to "Edit on Github" which goes to https://github.com/ContinuumIO/conda/blob/master/index.rst which also doesn't exist.

**Comment by rrigdon** [comment]
Hi xobs, thanks for reporting this issue. 

That is a really old page that is in the process of being removed. The correct documentation for conda and conda-build is at https://conda.io/en/latest/.

For documentation on building packages, check out our conda-build site https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/index.html. 

Once this page is removed entirely, I'll close the ticket. Thanks again!

**Comment by kathatherine** [comment]
It seems that none of the links involved in this ticket exist anymore and https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/index.html does contain links to several sets of package building instructions, all of which work just fine. I'm going to close this as completed.
