### ISSUE TITLE
CONDA_ENVS_PATH behaves incorrectly in case multiple users work on the same machine

### ISSUE THREAD

**Issue by roman-turovskyy** [conda/conda#9311]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
CONDA_ENVS_PATH=E:\conda\env
When user creates virtual environment it gets created in his user directory on C drive, regardless that CONDA_ENVS_PATH points to E:\conda\env
According to trace logs, this line is executed:
log.trace("Tried envs_dir but not writable: %s", envs_dir)

### Steps to Reproduce
Because every user sees  the same value for CONDA_ENVS_PATH, once user1 created conda virtual environment, a magic file E:\conda\env\.conda_envs_dir_test gets created and stays there.
When user2 log ins to machine and creates his virtual environment, code in file https://github.com/conda/conda/blob/251e89509cdabfe2df227c1a582a3e3d320eed5d/conda/base/context.py tried to open E:\conda\env\.conda_envs_dir_test file for append and fails. The problem is that users can create folders/files on E drive, but they cannot edit/delete files created by other users (due to default permissions on Windows drives).

## Expected Behavior
When user2 creates virtual environment it gets created in E:\conda\env folder.

Possible fix - _first_writable_envs_dir() function shall try creating file which name is unique for each user.

## Environment Information
> conda info
         package cache : E:\conda\pkgs
      envs directories : E:\conda\env
                         C:\Users\turovr-ext\.conda\envs
                         C:\Anaconda\envs
                         C:\Users\turovr-ext\AppData\Local\conda\conda\envs

**Comment by okhoma** [comment]
I confirm the issue and propose instead of magic _.conda_envs_dir_test_ file, create file with random name and delete the file afterwards. The test will be executed and the issue with multi-user environment will be solved.
