### ISSUE TITLE
conda should retry failed downloads

### ISSUE THREAD

**Issue by ChemicalSailor** [conda/conda#9312]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior

When creating a new environment and downloading packages if an HTTP error is encountered the environment is not created (as expected). I have to manually retry in order for all packages to get downloaded and the environment created/updated. This is an issue for me because conda sits behind a corporate firewall that scans suspicious downloads (sophos sandstorm) which often initially blocks a download with a 403 forbidden error, but once it's had time to scan the package, retrying the download gives a 200 response.
related: https://github.com/conda/conda/issues/8477

### Steps to Reproduce

If you have a firewall that temporarily blocks packages, you can reproduce this behavior.

## Expected Behavior

conda should have the option to automatically retry failed downloads after a delay, up to a maximum number of tries. Incorporating some functionality of the retrying package would be great!

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : my-default
active env location : P:\python_envs\my-default
shell level : 2
conda version : 4.6.7
conda-build version : 3.17.6
python version : 3.7.1.final.0
base environment : C:\ProgramData\Anaconda3  (writable)
```
</p></details>

**Comment by soapy1** [comment]
Resolved by https://github.com/conda/conda/pull/9318 Thanks @WillyChen123 !
