### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by nirr3** [conda/conda#9313]
Hi I am running into issues with when attempting to import new libraries or when opening jupyter and navigator from the conda prompt:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 666, in use_only_tar_bz2
        import conda_package_handling.api
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

### Actual Behavior

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 666, in use_only_tar_bz2
        import conda_package_handling.api
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\ProgramData\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\
                          Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\
                          bin;C:\ProgramData\Anaconda3\condabin;C:\Windows\system32;C:\Windows;C
                          :\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\
                          Windows\System32\OpenSSH;C:\Program Files (x86)\Interactive
                          Intelligence\BusinessManagerApps;C:\Program Files (x86)\Common
                          Files\Sage SBD;C:\Program Files\Tableau Data Extract API;C:\Program
                          Files\Tableau Data Extract API\bin;C:\ProgramData\Jack Henry and
                          Associates\Episys For Windows\HTML
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\nankarstad\.condarc
 populated config files : C:\ProgramData\Anaconda3\.condarc
          conda version : 4.7.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://pypi.org/win-64
                          https://pypi.org/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\nankarstad\.conda\pkgs
                          C:\Users\nankarstad\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\nankarstad\.conda\envs
                          C:\Users\nankarstad\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

### Expected Behavior

It should launch jupyter/ navigator or install the library

### Steps to Reproduce

2019-09-28 12:00:44  (rev 1)
     conda  {4.6.11 -> 4.7.12}
    +conda-package-handling-1.3.11
    +lightgbm-2.2.1

2019-09-28 12:04:34  (rev 2)
     anaconda  {2019.03 -> custom}
     ca-certificates  {2019.1.23 -> 2019.8.28}
     certifi  {2019.3.9 -> 2019.9.11}
     openssl  {1.1.1b -> 1.1.1c}
    +_anaconda_depends-2019.03
    +tbb-2019.4

##### `Output of conda info`
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\nankarstad\.condarc
 populated config files : C:\ProgramData\Anaconda3\.condarc
          conda version : 4.7.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://pypi.org/win-64
                          https://pypi.org/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\nankarstad\.conda\pkgs
                          C:\Users\nankarstad\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\nankarstad\.conda\envs
                          C:\Users\nankarstad\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

Any guidance would be appreciated.

Thank you!

**Comment by ShayekhBinIslam** [comment]
@msarahan   Please help with this issue. standalone-conda is not solving this.

Error:

`Failed to load dynlib/dll 'C:\\Users\\SHAYEK~1\\AppData\\Local\\Temp\\_MEI163562\\Library\\bin\\ssleay32'. Most probably this dynlib/dll was not found when the application was frozen.`

**Comment by shazhongcheng** [comment]
> conda-package-handling

I don`t know why?
```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\sha\Anaconda3
  package name: \users\sha\anaconda3
```

**Comment by lorenzznerol** [comment]
Can anyone confirm that the promising answer of @msarahan works?

**Comment by Wasberry** [comment]
Please I have this error when trying to open the demo toolbox on anaconda;

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\WASBERRY\anaconda3\envs\VoiceCloning\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
