### ISSUE TITLE
Python cli api broken in 4.7.12

### ISSUE THREAD

**Issue by jbouzaglou** [conda/conda#9329]
I would like to use the python cli api, however it seems broken in 4.7.12
Steps to reproduce:

conda install conda=4.7.12

```
from conda.cli.python_api import run_command, Commands

if __name__ == "__main__":
    run_command(Commands.CREATE, ["-n", "newenv", "python=3", "flask"])
```
This results in a argument parsing error and an exception of :
conda.exceptions.CondaValueError: The target prefix is the base prefix. Aborting.

This example comes straight out of the documentation, i think it was working on 4.6 .

**Comment by jbouzaglou** [comment]
After some debugging it seems to come from the conversion of the *arguments in run_command , when there is arguments=list(arguments), which converts the array argument into a array of arrays with only one element

**Comment by msarahan** [comment]
Thanks for identifying the issue. We'll try to get a fix in soon.

**Comment by jbouzaglou** [comment]
Also leaving a full command line of the type "-n newenv python=3" no longer works, the run_command function doc does not show such an example anymore but it was nice to have.
