### ISSUE TITLE
Search for condarc also in ~/.config/conda/condarc

### ISSUE THREAD

**Issue by astier** [conda/conda#9333]
It would be nice if conda would search for the condarc-file also in *~/.config/conda/condarc*. This follows the XDG standard on linux and many people prefer to keep their config files in ~/.config because this helps to keep the home-directory clean. condarc is currently one of the few config-files which I still store in the home-directory.

**Comment by soapy1** [comment]
Could do. Currently conda looks in the following locations for a condarc https://github.com/conda/conda/blob/master/conda/base/constants.py#L27-L55
Do any of these locations satisfy your needs?

**Comment by astier** [comment]
I now export CONDARC as ~/.config/condarc and it works. Thx. So far I couldn't find any documentation that all this different possibilities exist which you linked. If its documented where can I find it? If is is not maybe it should be.

**Comment by soapy1** [comment]
Yup, this should go in the docs! cc @rrigdon 

`CONDA_ROOT` is the path for your base conda install. `CONDA_PREFIX` is the path to the current active environment
