### ISSUE TITLE
conda env export incorrectly exports pip dependency graphviz

### ISSUE THREAD

**Issue by caseyclements** [conda/conda#9338]
## Current Behavior
     
If one installs graphviz into a conda environment *using pip, from pypi*, conda env export and conda list incorrectly print this as python-graphviz (which is the name of a conda package, not a pip one). This subtle issue appears when one tries to create an environment from the file written by conda env export, as pip can't find python-graphviz.

### Steps to Reproduce
```
conda create -y -n graphviz.in python pip
conda activate graphviz.in
pip install graphviz
conda list | grep graphviz
pip freeze | grep graphviz
conda env export -n graphviz.in -f graphviz.out.yml
conda env create -f graphviz.out.yml -n graphviz.out
```

## Expected Behavior
- `conda list` should show the name of the pip package, `graphviz`
-  The last two commands should reproduce the environment created by the first three.

**Comment by quancore** [comment]
Still seems an issue
