### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by illgitthat** [conda/conda#9343]
Is there a timeline for python 3.8 support for anaconda or miniconda?

Or, if it is currently possible to use python 3.8 with anaconda or miniconda, is there any documentation on how to do so?

Thank you in advance.

I apologize if I am filing this in the wrong repo, but I haven't been able to find the answer elsewhere.

**Comment by underchemist** [comment]
it should be up soon, though I have seen no documentation or timeline. For example python 3.7.0 came out June 27, 2018 and the first 3.7.0 package on anaconda cloud around June 29, 2018

**Comment by pllim** [comment]
I am also looking forward to Python 3.8 in `miniconda` distribution. Particularly, I want to be able to do this:
```
conda create -n walrusworld python=3.8
```

**Comment by illgitthat** [comment]
Does anyone have any insight on what work is still needed before a 3.8 release is ready?

**Comment by illgitthat** [comment]
I found a 3.8 version here https://anaconda.org/anaconda/python

**Comment by pllim** [comment]
True, you get a Python 3.8.0 environment, but nothing else works in there currently; not `ipython` nor `numpy`. :cry:

**Comment by jjhelmus** [comment]
We are adding Python 3.8 packages to the repository as they are built and tested.  It will take a few weeks before the majority of the packages are available.

**Comment by joshualevy2** [comment]
Is there any update on a release for Anaconda 3.8?  I saw the 2020.02 update, but need to plan for the first standard Anaconda release with python 3.8.

**Comment by jjhelmus** [comment]
The Anaconda 2020.02 Individiual Edition installers are still based upon Python 3.7 as there are still a few key packages in the ecosystem which do not support Python 3.8.  

Python 3.8 `anaconda` meta-packages are available for all platforms so that you can create a environment with the packages which would be included in a Python 3.8 installer.  This can be done using:  `conda create -n example python=3.8 anaconda=2020.02`

There are also Miniconda installer based on Python 3.8 [available](https://repo.anaconda.com/miniconda/).  Use the `Miniconda3-py38_...` files.

**Comment by johnnync13** [comment]
no update when it will be python3.8 (which is a wonder) by default?

**Comment by mingwandroid** [comment]
Python 3.8 will be the 'default' (not that that matters, just download one of the [Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh) [miniconda](https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-MacOSX-x86_64.sh) [releases](url) and be happy) when the ecosystem at-large is considered ready for us to declare it our default.

**Comment by lukelbd** [comment]
Looks like [python 3.8 is now the default](https://docs.conda.io/en/latest/miniconda.html) when downloading miniconda/anaconda for the first time. This is great for speeding up python 3.8 adoption in the community/if you are planning to start new python 3.8+ projects like me.
