### ISSUE TITLE
current latest miniconda sh installer for linux hangs on Unpacking payload step

### ISSUE THREAD

**Issue by RZachLamberty** [conda/conda#9345]
## Current Behavior
any attempt to use the latest (as of earlier today) miniconda sh installer script gets to the "Unpacking payload" step and then freezes until killed

### Steps to Reproduce

in any ubuntu environment (e.g. `docker run --rm -it ubuntu bash`), run

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```

after approving the EULA, you will see

```
PREFIX=/root/miniconda3
Unpacking payload ...
  0%|                                                     | 0/35 [00:00<?, ?it/s]
```

this stays in this state until killed (`ctrl + c`)

## Expected Behavior

the downloads being performed immediately after the "Unpacking payload ..." prompt would successfully acquire the base packages and unpack them.

## Environment Information

I cannot install `conda` so `conda` commands listed here are not accessible.

```
$ uname -a
Linux ip-172-31-16-44 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RZachLamberty** [comment]
this is happening on `aws` `ec2` instances, but also the current `docker` `ubuntu` image -- perhaps this is isolated to `ubuntu`, I haven't confirmed otherwise

output of `dpkg -l | grep coreutils`:

```
ii  coreutils                      8.28-1ubuntu1                     amd64        GNU core utilities
```

**Comment by RZachLamberty** [comment]
In attempting to reproduce this on a mac I discovered that I also cannot reproduce this problem

that being said, I had several students in the class I teach run into this same problem, all on `aws` `ec2`. the problem is fully repeatable on `ec2`, but not off. I would say that this is a one-off problem but, as I said, I had multiple students experience the same issue in the last 24 hours

**Comment by RZachLamberty** [comment]
I have tried this now on several different ec2 instances across multiple aws accounts -- it appears to be a problem across ec2, at least within the us-east-1 region.

**Comment by forrestwaters** [comment]
Thanks @RZachLamberty I was able to replicate it with an Ubuntu AMI using ec2. Will look into this

**Comment by forrestwaters** [comment]
I think this is an issue with smaller EC2 instance types. Anything with a single core seems to experience this issue - if I go to `t2.medium` or larger, the installation process works. That seems to be a result of the usage of `concurrent.futures` in our installers and will require more investigation.

In the meantime, one option for bootstrapping a conda environment you may find useful is our standalone conda executable: https://repo.anaconda.com/pkgs/misc/conda-execs/

```
wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
chmod +x conda.exe
./conda.exe create -p <path/to/conda> -y
source path/to/conda/etc/profile.d/conda.sh
conda init
```

Or the 4.7.10 installer until we can get this sorted out.

**Comment by todpole3** [comment]
Also met this issue with GCP while trying to install conda in a docker image

**Comment by rajaseelan** [comment]
Came here to say the same thing as @todpole3

**Comment by todpole3** [comment]
My workaround is to use an earlier version of miniconda installation script:

`curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh`

**Comment by nishankjain** [comment]
4.7.10 works, latest doesn't work on t2.micro for me too.

**Comment by minitu** [comment]
Same problem occurs on a Ubuntu 18.04 VirtualBox instance with 1 core.

**Comment by karimeg94** [comment]
Just encountered this issue when building an Image using your dockerfile for both Debian and Alpine within Docker Toolbox VM. 

Can confirm @tadpole3 solution works by using an older version.

**Comment by ifrh** [comment]
Using download URLs from [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html) and [https://www.anaconda.com/distribution/#linux](https://www.anaconda.com/distribution/#linux)

```
wget https://repo.anaconda.com/archive/Anaconda2-2019.10-Linux-x86_64.sh
wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
```

```
-rw-rw-r-- 1  500592001 Okt 15 18:17 Anaconda2-2019.10-Linux-x86_64.sh
-rw-rw-r-- 1  530308481 Okt 15 18:20 Anaconda3-2019.10-Linux-x86_64.sh
-rw-rw-r-- 1  46957912 Okt 16 21:14 Miniconda2-latest-Linux-x86_64.sh
-rw-rw-r-- 1  70489432 Okt 16 21:15 Miniconda3-latest-Linux-x86_64.sh
```
Installation of Anaconda2 and Anaconda3 works for me behind a HTTP_PROXY.
But miniconda2 and miniconda3 is hanging:

```
Welcome to Miniconda2 4.7.12
[...]
[/home/user/miniconda2] >>> 
PREFIX=/home/user/miniconda2
Unpacking payload ...
  0%|                                                                                              | 0/37 [00:00<?, ?it/s]
```
```
Welcome to Miniconda3 4.7.12
[...]
[/home/user/miniconda3] >>> 
PREFIX=/home/user/miniconda3
Unpacking payload ...
  0%|                                                                                              | 0/35 [00:00<?, ?it/s]
```

**Comment by jspiers** [comment]
I encountered this same issue (stuck at "Unpacking payload") when attempting a Docker-in-Docker build on GitLab CI using a GitLab shared runner.
Also fails the same way when building using a kaniko image instead of DinD (again on GitLab CI, shared runner)

**Comment by kebwi** [comment]
I just ran into this on a GCP Debian VM. What is the timeline to get this fixed?

Thank you.

**Comment by forrestwaters** [comment]
Preview installers with a fix for this can be seen here if you'd like to test them: https://repo.anaconda.com/pkgs/misc/previews/miniconda/4.7.12.1/

They will be updated at https://repo.continuum.io/miniconda once they have gone through our regular QA process.

**Comment by forrestwaters** [comment]
Miniconda 4.7.12.1 which fixes this is now available here: https://repo.anaconda.com/miniconda/

**Comment by RZachLamberty** [comment]
y'all rock, thanks so much

**Comment by JohnUrban** [comment]
This was also a problem for the latest anaconda3 on the free tier Amazin EC2 ubuntu instance:
```
wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
bash Anaconda3-2019.10-Linux-x86_64.sh
```

Using the last release solved the issue:
```
wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
bash Anaconda3-2019.07-Linux-x86_64.sh
```

**Comment by andriana-modio** [comment]
I have also encountered that trying to install Anaconda on an LXD.

**Comment by taquangtrung** [comment]
I also encountered the same problem in a Virtual Box machine with single CPU core. Annaconda hanges at the "unpacking" step, but I think the packages are still downloaded in the background.

**Comment by sdeibel** [comment]
This isn't fixed in current Anaconda (non-mini) download Anaconda3-2019.10-Linux-x86_64.sh; encountered the problem in a VMWare VM and solved it by increasing process cores to 2 under Virtual Machine > Settings > Processors and Memory.

**Comment by ronhao** [comment]
> This isn't fixed in current Anaconda (non-mini) download Anaconda3-2019.10-Linux-x86_64.sh; encountered the problem in a VMWare VM and solved it by increasing process cores to 2 under Virtual Machine > Settings > Processors and Memory.

Same here.

**Comment by g24swint** [comment]
I am also seeing this problem in the current version of Anaconda attempting to install on a t2.small instance. Hangs up exactly on the "Unpacking payload..." error

**Comment by ronhao** [comment]
> > This isn't fixed in current Anaconda (non-mini) download Anaconda3-2019.10-Linux-x86_64.sh; encountered the problem in a VMWare VM and solved it by increasing process cores to 2 under Virtual Machine > Settings > Processors and Memory.
> 
> Same here.

By which I meant that I was also able to solve it by increasing processor to 2.

**Comment by wtsitp** [comment]
thanks @ronhao, problem has been solved by just increasing processor to 2

**Comment by hansintheair** [comment]
Seeing this issue on RHEL, single core as well.

**Comment by dalupus** [comment]
I ran into this issue on a vm that was setup with 4 processors of 1 core each.

I fixed it by swapping to 1 processor of 4 cores instead.

**Comment by Strateus** [comment]
Same here, t2.micro, amazon linux, used anaconda package website link

**Comment by ifrh** [comment]
perhaps some one could reopen that bug report ?

**Comment by forrestwaters** [comment]
This is fixed in the latest miniconda installer as mentioned in the above comments. Please see https://github.com/ContinuumIO/anaconda-issues/issues/11466#issuecomment-568483600 for a workaround for the Anaconda installer

It will be fixed in the next Anaconda release which will happen in the next month or so

**Comment by piskunow** [comment]
If it helps, I got this Traceback when 

```
Unpacking payload ...
  0%|

Traceback (most recent call last):                                                                       
  File "entry_point.py", line 76, in <module>
  File "concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 598, in result_iterator
  File "concurrent/futures/_base.py", line 430, in result
  File "threading.py", line 296, in wait
KeyboardInterrupt
[30257] Failed to execute script entry_point
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 104, in _python_exit
  File "threading.py", line 1044, in join
  File "threading.py", line 1060, in _wait_for_tstate_lock
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing/popen_fork.py", line 28, in poll
KeyboardInterrupt
```

**Comment by juanlet** [comment]
If you want to follow redirects when receiving 301 header use the -L option

 curl https://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh -L --output miniconda.sh
