### ISSUE TITLE
Solver crashes when constraints are unsatisfiable with ValueError: too many values to unpack

### ISSUE THREAD

**Issue by kouzant** [conda/conda#9346]
I'm running conda with the pycryptosat solver. My conda info is the following:

    anaconda/bin/conda info
    
         active environment : None
           user config file : /home/anaconda/.condarc
     populated config files : /home/anaconda/.condarc
              conda version : 4.7.12
        conda-build version : 3.18.8
             python version : 2.7.16.final.0
           virtual packages : 
           base environment : anaconda-2-2019.07  (writable)
               channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : anaconda/pkgs
           envs directories : anaconda/envs
                              anaconda-2-2019.07/envs
                              /home/anaconda/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Linux/4.15.0-62-generic ubuntu/18.04.3 glibc/2.27
                    UID:GID : 990:1009
                 netrc file : None
               offline mode : False

Then I have installed __pycryptosat__ `anaconda/bin/conda install --no-deps pycryptosat libcryptominisat` - I acknowledge that `--no-deps` flag can be dangerous but I think it's irrelevant in this case - and I set it as SAT solver `anaconda/bin/conda config --set sat_solver pycryptosat`.

When I do `anaconda/bin/conda update anaconda` I get the following error.

    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/exceptions.py", line 1074, in __call__
            return func(*args, **kwargs)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            exit_code = getattr(module, func_name)(args, parser)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/cli/main_update.py", line 20, in execute
            install(args, parser, 'update')
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/cli/install.py", line 265, in install
            should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
            should_retry_solve)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
            force_remove, should_retry_solve)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
            ssc = self._run_sat(ssc)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/core/solve.py", line 805, in _run_sat
            should_retry_solve=ssc.should_retry_solve
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/resolve.py", line 1359, in solve
            solution, obj5 = C.minimize(eq_v, solution)
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/common/logic.py", line 792, in minimize
            return bestsol, sum(abs(c) for c, a in objective) + 1 if objective else 1
          File "anaconda-2-2019.07/lib/python2.7/site-packages/conda/common/logic.py", line 792, in <genexpr>
            return bestsol, sum(abs(c) for c, a in objective) + 1 if objective else 1
        ValueError: too many values to unpack
    
    $ anaconda/bin/conda update anaconda
    
      environment variables:
                     CIO_TEST=<not set>
                   CONDA_ROOT=anaconda-2-2019.07
                         PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game
                              s:/usr/local/games
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
                 SUDO_COMMAND=/bin/su anaconda
                     SUDO_GID=1000
                     SUDO_UID=1000
                    SUDO_USER=vagrant
    
         active environment : None
           user config file : /home/anaconda/.condarc
     populated config files : /home/anaconda/.condarc
              conda version : 4.7.12
        conda-build version : 3.18.8
             python version : 2.7.16.final.0
           virtual packages : 
           base environment : anaconda-2-2019.07  (writable)
               channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : anaconda/pkgs
           envs directories : anaconda/envs
                              anaconda-2-2019.07/envs
                              /home/anaconda/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Linux/4.15.0-62-generic ubuntu/18.04.3 glibc/2.27
                    UID:GID : 990:1009
                 netrc file : None
               offline mode : False

What happens here, **from my understanding**, is that the solver fails to satisfy all the constraints and gets into https://github.com/conda/conda/blob/4.7.x/conda/common/logic.py#L792 I print the `objective` and in my case it's a dictionary like `{u'defaults::dask-2.0.0-py_0': 7, u'defaults::pytest-4.1.0-py37_0': 15}`

The line above in `logic.py` is problematic as it tries to unpack the dictionary and it raises `ValueError: too many values to unpack`.

As far as I understand it's not the solver's problem per se, although the default solver manages to satisfy all the constraints so I don't get into this issue.

**Comment by soapy1** [comment]
This issue is fixed in newest conda. Update conda by running `conda update conda -n base`
