### ISSUE TITLE
Conda remove uninstalls more packages than expected

### ISSUE THREAD

**Issue by pallgeuer** [conda/conda#9353]
## Current Behavior

Suppose I have Anaconda and do the following:

    conda create -n demo python=3.6
    conda activate demo
    conda install seaborn

The last command installs 39 new packages including ```seaborn```, ```matplotlib``` and ```pandas```. Now suppose that time passes and I continue to set up my environment and wish to explicitly install ```matplotlib``` and ```pandas```:

    conda install matplotlib pandas

This tells me "All requested packages already installed", which is okay. Now however, if I decide I don't need ```seaborn``` anymore and remove it,

    conda remove seaborn

this removes ALL 39 packages that were installed when ```seaborn``` was installed, including both ```matplotlib``` and ```pandas```, which I explicitly installed after that.

### Steps to Reproduce

See above.

## Expected Behavior

My expected behaviour would be that ```conda remove seaborn``` removes ```seaborn``` and all of its dependencies, but does *not* remove any package (or dependencies thereof) that was explicitly installed before or after ```seaborn```. Some might say just uninstall ```seaborn``` and all 39 packages, and then manually reinstall ```matplotlib``` and ```pandas```. This works in trivial cases, but once there are e.g. 25 packages with complex interdependencies, this becomes very complicated, and if doable at all, a complete nuisance to maintain.

As a concrete example of this, suppose I try to construct a full Anaconda environment minus a particular package and *only* the packages that depend on it? I can try:

    conda create -n test python=3.6 anaconda
    conda remove libtiff  # I want this to strictly only remove libtiff and its recursive dependents, but obviously this is not what happens

but the second line removes essentially every single package in the entire environment, as it resorts to removing the ```anaconda``` package.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/lpallgeuer/.condarc
 populated config files : /home/lpallgeuer/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/lpallgeuer/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/lpallgeuer/anaconda3/pkgs
                          /home/lpallgeuer/.conda/pkgs
       envs directories : /home/lpallgeuer/anaconda3/envs
                          /home/lpallgeuer/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.4.0-148-generic ubuntu/14.04.6 glibc/2.19
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/lpallgeuer/.condarc <==
auto_activate_base: False
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/lpallgeuer/anaconda3/envs/demo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py36_0    defaults
cycler                    0.10.0                   py36_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.56.2               hd408876_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
intel-openmp              2019.4                      243    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.1.0            py36he6710b0_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.1            py36h5429711_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.14           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.17.2           py36haad9e8e_0    defaults
numpy-base                1.17.2           py36hde5b4d6_0    defaults
openssl                   1.1.1d               h7b6447c_3    defaults
pandas                    0.25.1           py36he6710b0_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pip                       19.2.3                   py36_0    defaults
pyparsing                 2.4.2                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
python                    3.6.9                h265db76_0    defaults
python-dateutil           2.8.0                    py36_0    defaults
pytz                      2019.3                     py_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  7.0                  h7b6447c_5    defaults
scipy                     1.3.1            py36h7c811a0_0    defaults
seaborn                   0.9.0                    py36_0    defaults
setuptools                41.4.0                   py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.30.0               h7b6447c_0    defaults
statsmodels               0.10.1           py36hdd07704_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.3            py36h7b6447c_0    defaults
wheel                     0.33.6                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by msarahan** [comment]
This is definitely not desirable behavior. Conda should record explicit requests, even if they lead to no change as you show here. It should not record failed requests, but those are different.

I don't know when we'll be able to fix this. If you'd like, a PR would be most welcome. Otherwise we'll try to fix it as time allows.

**Comment by pallgeuer** [comment]
I am not in any way familiar with conda or its internals, so I can't really provide a PR myself, but for me (and I think enough other people) this is really problematic behaviour, especially as environments get more custom. Would be appreciative whenever this can be fixed.

**Comment by pallgeuer** [comment]
Any news on this issue?

**Comment by gh4gm** [comment]
There is a gross bug in conda remove, as it does not work as documented:
https://docs.conda.io/projects/conda/en/latest/commands/remove.html
conda remove[](https://docs.conda.io/projects/conda/en/latest/commands/remove.html#conda-remove)
Remove a list of packages from a specified conda environment.
This command will also remove any package that depends on any of the specified packages as well-

That would mean "any package that depends on seaborn".
In reality it removes "any package on which seaborn depends".
More exactly "... and has been installed when seaborn was installed.

The documentation fails to describe what really happens.

As a workaround you can "mv ~/miniconda3/conda-meta/history ~/miniconda3/conda-meta/history-before; touch ~/miniconda3/conda-meta/history"

Then "conda remove libtiff" only removes "libtiff" and packages which depend on it. That
means it then behaves as documented.

**Comment by battaglia01** [comment]
@gh4gm: I guess that's right.

I mean, it seems even worse than above. For instance, here's an extreme case I ran into today. The environment was created with

```
$ conda create --name core --channel defaults --channel conda-forge python pip xonsh Cython ipython numpy scipy matplotlib mplc
ursors numba sympy jupyter youtube-dl mido seaborn pandas pytorch spyder-kernels
```

Then I installed one package *with --no-deps* on, so there are no dependencies at all:

```
$ conda install -c esri python-sounddevice --no-deps
...
The following NEW packages will be INSTALLED:

  python-sounddevice esri/noarch::python-sounddevice-0.4.4-py_0
...
```

Then, upon trying to remove it 45 seconds later, it changes almost every single package I had in the environment:

```
$ conda uninstall python-sounddevice
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mike/Library/miniconda3/envs/core

  removed specs:
    - python-sounddevice


The following NEW packages will be INSTALLED:

  libllvm12          pkgs/main/osx-arm64::libllvm12-12.0.0-h12f7ac0_4
  pcre               pkgs/main/osx-arm64::pcre-8.45-hc377ac9_0
  sqlite             pkgs/main/osx-arm64::sqlite-3.39.3-h1058600_0

The following packages will be REMOVED:

  glib-tools-2.74.1-hb5ab8b9_0
  libclang13-14.0.6-default_hf5a4b0a_0
  libglib-2.74.1-h14ed1c1_0
  libllvm14-14.0.6-h7ec7a93_1
  libogg-1.3.5-h1a28f6b_1
  libopus-1.3.1-h27ca646_1
  libvorbis-1.3.7-h1a28f6b_0
  mysql-common-8.0.31-h518ea0a_0
  mysql-libs-8.0.31-hcb599eb_0
  pcre2-10.37-h37e8eca_1
  python-sounddevice-0.4.4-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  glib                  conda-forge::glib-2.74.1-hb5ab8b9_0 --> pkgs/main::glib-2.69.1-h98b2900_1
  gst-plugins-base   conda-forge::gst-plugins-base-1.22.0-~ --> pkgs/main::gst-plugins-base-1.14.1-hf0a386a_0
  gstreamer          conda-forge::gstreamer-1.22.0-hcb7b3d~ --> pkgs/main::gstreamer-1.14.1-he09cfb7_0
  icu                      conda-forge::icu-70.1-h6b3803e_0 --> pkgs/main::icu-68.1-hc377ac9_0
  krb5                  conda-forge::krb5-1.20.1-h69eda48_0 --> pkgs/main::krb5-1.19.4-h8380606_0
  libpng              conda-forge::libpng-1.6.39-h76d750c_0 --> pkgs/main::libpng-1.6.37-hb8d0fd4_0
  libpq                  conda-forge::libpq-15.2-h1a28acd_0 --> pkgs/main::libpq-12.9-h65cfe13_3
  nspr                    conda-forge::nspr-4.35-hb7217d7_0 --> pkgs/main::nspr-4.33-hc377ac9_0
  nss                      conda-forge::nss-3.88-h789eff7_0 --> pkgs/main::nss-3.74-h142855e_0
  openssl             conda-forge::openssl-3.0.8-h03a7124_0 --> pkgs/main::openssl-1.1.1s-h1a28f6b_0
  qt-main            conda-forge::qt-main-5.15.8-hfe8d25c_6 --> pkgs/main::qt-main-5.15.2-ha2d02b5_7
  zlib                  conda-forge::zlib-1.2.13-h03a7124_4 --> pkgs/main::zlib-1.2.12-h5a0b063_3

The following packages will be DOWNGRADED:

  freetype                                2.12.1-h1192e45_0 --> 2.11.0-h1192e45_0
  libclang                        14.0.6-default_hf5194b7_0 --> 12.0.0-default_hc321e17_4
  libprotobuf                             3.20.3-h514c7bf_0 --> 3.20.1-h98b2900_0
  libsqlite                               3.40.0-h76d750c_0 --> 3.39.4-h76d750c_0
  libtiff                                  4.5.0-h313beb8_1 --> 4.4.0-had003b8_0
  libzlib                                 1.2.13-h03a7124_4 --> 1.2.12-h03a7124_3
  pillow                              9.3.0-py310h313beb8_2 --> 9.2.0-py310h4d1bdd5_1
  pyqt                               5.15.7-py310h7aaa74b_3 --> 5.15.4-py310h1105856_0
  pyqt5-sip                         12.11.0-py310h0f1eb42_3 --> 12.9.0-py310h1105856_0
  python                          3.10.9-h3ba56d0_0_cpython --> 3.10.6-hbce4517_0_cpython
```

Some of these things are really major version changes for no reason at all (why is openssl suddenly going from 3.0.8 to 1.1.1???). I have no idea if my environment woudl have even worked after that.

**Comment by pallgeuer** [comment]
@battaglia01 I totally agree that stuff like that should not happen and be dealt with much better from the side of conda.

Out of curiosity, what happens if you:
```
conda remove -c defaults -c conda-forge python-sounddevice
```
If that helps then it's a slightly different situation than the one I initially described.

**Comment by battaglia01** [comment]
OK, I apologize, I think my example above may have been due to a config error in which the .condarc file was causing the channel priorities to change, after the initial installation when creating the environment, in ways I didn't realize. The reason it did that above is because it had `defaults` as the highest priority channel, so upon uninstalling the package, it tried re-solving the entire environment with those parameters, which is why it tried changing everything from conda-forge to defaults. So that explains that.
