### ISSUE TITLE
Solver messaging improvement

### ISSUE THREAD

**Issue by soapy1** [conda/conda#9363]
Current solver messaging for unsatisfiable cases is still pretty opaque to users. Part of the problem is around interpreting what the unsat hints actually mean. An option is to add more information around the hints. 

From conda-forge  gitter

> Christopher J. Wright @CJ-Wright 09:32
Would it be possible to a) add that description to the output (as table headers?) and b) add the offending version into the Package <thing> conflicts line?
For example:
Package readline=10.0.0 conflicts for:
Installed package -> Available versions
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']

**Comment by dhirschfeld** [comment]
Thanks for picking this up @soapy1! IMHO it would be a big win if the current situation could be improved.

Gitter link:
https://gitter.im/conda-forge/conda-forge.github.io?at=5db043c79c398215096d6f20

**Comment by dhirschfeld** [comment]
@CJ-Wright's suggestion is definitely an improvement I think, but very often it's not a user requested package which conflicts but merely a common dependency with incompatible version constraints. In this case it would be *really* useful to tie it back to the top-level (user-requested) package 

e.g. in ~an~ my ideal world the below situation:
```
package A:
    depends:
      - depA
      - commonDep =1.*,=3.*
      
package B:
    depends:
      - depB
      - C 

package C:
    depends:
      - commonDep =2.*
      - depC
```
```
conda install A B

Package Plan:
    A depA commonDep B depB C depC
```
...would give an error message similar to:
```
Incompatible version contraints for commonDep!
    requested package A -> commonDep[1.*|3.*]
    requested package B -> C -> commonDep[2.*]
```
i.e. each line shows the chain from requested package to incompatible `commonDep`

Not sure how feasible that is but at least for me that's a lot more understandable than the current output.

**Comment by dhirschfeld** [comment]
The mamba report described by @wolfv is also much clearer (to me):
```
Encountered problems while solving.
Problem: nothing provides ros-roscpp needed by ros-comm-1.14.3-he1b5a44_0
```
https://gitter.im/conda-forge/conda-forge.github.io?at=5db055bd10bd4128a149283e

**Comment by wolfv** [comment]
I just had a similar problem where I forgot to correctly build the ros-rosmake python=2.7 and 3.6 packages. 

Conda produces this output:

```
Package wheel conflicts for:
python=2.7 -> pip -> wheel
ros-core -> ros-catkin -> python[version='>=3.7,<3.8.0a0'] -> pip -> wheel
Package python conflicts for:
ros-core -> ros-catkin -> python[version='>=3.7,<3.8.0a0']
ros-core -> ros-comm -> ros-rosbag -> python
python=2.7
Package pip conflicts for:
python=2.7 -> pip
ros-core -> ros-catkin -> python[version='>=3.7,<3.8.0a0'] -> pip
Package ca-certificates conflicts for:
ros-core -> ros-catkin -> nose -> setuptools -> ca-certificates
python=2.7 -> ca-certificates
Package python-dateutil conflicts for:
ros-core -> ros-genpy -> pyyaml -> cython -> python-dateutil
Package setuptools conflicts for:
ros-core -> ros-catkin -> nose -> setuptools
python=2.7 -> pip -> setuptools
Package certifi conflicts for:
python=2.7 -> pip -> setuptools -> certifi[version='>=2016.09']
```

While mamba gives "Problem: package ros-core-1.4.1-he1b5a44_0 requires ros-ros, but none of the providers can be installed"

then trying "mamba install ros-ros python=2.7" results in "Problem: package ros-ros-1.14.6-he1b5a44_0 requires ros-rosmake, but none of the providers can be installed" which lead me to the package that is problematic. 

Just wanted to show how one can try to debug these issues with mamba as an inspiration. It's possible that there are more problematic packages, but from the conda output i don't really get any idea on what's the broken package.

**Comment by soapy1** [comment]
https://github.com/conda/conda/pull/9559 will address the formatting bit of this issue. More work coming on the content of the messaging

**Comment by msarahan** [comment]
This is the best stuff I've seen so far: “PubGrub: Next-Generation Version
Solving” by Natalie Weizenbaum https://link.medium.com/xrcK0MUbX2

**Comment by soapy1** [comment]
https://github.com/conda/conda/pull/9560 has an attempt at making the content of the unsat messaging better. Here is a comparison of results https://github.com/conda/conda/pull/9560#issuecomment-572162310
