### ISSUE TITLE
Support for conda metachannel

### ISSUE THREAD

**Issue by jeremyjliu** [conda/conda#9368]
Tracking issue for fully supporting conda metachannel (i.e. server side repodata filtering). At a high level, this involves:

1) passing package names / match specs in the network request to fetch repodata
2) caching repodata in-memory accounting for the specs passed
3) caching repodata on disk for non-metachanneled channels (and not caching metachanneled repodata)

Inherent in the approach is a way to distinguish between a metachanneled and a normal conda channel. I can think of a few approaches:

- add a configuration that identifies metachanneled channels, i.e.
```
metachanneled_channels:
    - <channel a>
    - <channel b>
```
- expand the configuration of the existing channels to have optional values, i.e.
```
channels:
    - <channel a>
         - is_metachanneled: true
```
- require metachannel to return an indicator designating the repodata is filtered, i.e. in the repodata.json add a key: `filtered: true`

Opening this issue for discussion on these ideas and more.

**Comment by jeremyjliu** [comment]
A thought that I don't think is immediately necessary: in the case of wanting / needing to support offline mode for metachannels (which I assume is the primary reason to cache repodata on disk), we could theoretically keep a merged repodata cached on disk. This would comprise all the previously fetched repodata results merged into a single entry per metachannel. Offline mode should only utilize previously fetched repodata and package results anyway, so I think this would be sufficient to power that workflow.

**Comment by jeremyjliu** [comment]
@msarahan, wondering if you had any thoughts on this? or are there maintainers who have informed opinions I should tag? thanks!

**Comment by jeremyjliu** [comment]
I like the second option as well, most extendible to future needs.

**Comment by jeremyjliu** [comment]
Having taken a brief look at the existing implementation, it appears that nested config parameters would be non-trivial to add. Does any maintainer @conda/conda-core have any tips on how to add this?

**Comment by jeremyjliu** [comment]
I've sketched out an implementation below, open to feedback! The existing implementation is limited to flat configs only, so this adds abstraction layers to enable nested configs in general. For instance, an example from Nehal:
```
{
   "defaults":{  
      "repodata_gpgcheck":1,
      "gpgkey":"https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc",
      "urls":[  
         "https://repo.anaconda.com/pkgs/main",
         "https://repo.anaconda.com/pkgs/r"
      ],
      "enabled": 1,
      "gpgcheck": 1, // whether each package has to be verified too…
      "ca_bundle": "file:///etc/pki/whatever/my-custom_ca.crt",
      "aliases": ["continuum", "basic", "base"],
      "proxies": [
          "http": "http://proxy.myorg.com:8080",
          "https": "http://proxy.myorg.com:8080",
          "no": ["*.myorg.com", "*.myorg2.com"],
      ],
      // mirrors (urls)?
   }
}
```

Essentially, we split the existing Parameter class into three parts:

```
@with_metaclass(ABCMeta)
def Parameter(object):
    name (str)
    aliases (list<str>)
    value (Parameter)

    @abstractmethod
    load(self, raw_or_str_input) -> LoadedParameter
```
This class is essentially a typing class, used for detection and loading of config values. This is meant to be extended by classes like PrimitiveParameter, MapParameter, etc.

```
@with_metaclass(ABCMeta)
def LoadedParameter(object):
    name (str)
    source (str)
    raw_value (obj)
    default (obj)
    value (obj)
    validation (?)
    priority (?)
    expandvars (?)

    @staticmethod
    merge(self, list_of_loaded_params) -> LoadedParameter

    @abstractmethod
    typify(self) -> obj
```
This class encapsulates the loaded configuration and is also meant to be extended, i.e. LoadedMapParameter.

```
def ParameterLoader(object):
    types (Parameter)

    __get__(self, instance, instance_type) -> object
```
The meat of the existing Parameter class is lifted into a ParameterLoader class, whose descriptor method handles calling the steps described above. This keeps the existing schematics for accessing config values as well as config reload / env + arg configs.

At a high level, the steps are roughly the same:
1) read config into RawParameter classes
Map<source, raw_data> -> Map<source, RawParameter>
2) (recursively) parse config from RawParameter into LoadedParameter
Map<source, RawParameter> -> Map<source, LoadedParameter>
3) find top level matches across config sources
Map<source, LoadedParameter> -> List<LoadedParameter>
4) (recursively) merge matches
List<LoadedParameter> -> LoadedParameter
5) (recursively) typify matches
LoadedParameter -> object

Note, I have not concretely thought through how validation and/or priority comments should be handled. But this should sketch out the general structure.

**Comment by msarahan** [comment]
This looks great to me.  My only comment is that we should avoid ever having values as keys.  For example:

```
{
   "defaults":{  
```

here the channel name is arguably both a value and a key.  Instead, let's move it inside the inner dict, and make the outer structure a list of dicts.  In YAML:

```
channels:
  - name: defaults
    urls:
      - https://abc
```

**Comment by jeremyjliu** [comment]
Agreed, that makes sense to me.
