### ISSUE TITLE
problem installing the latest RGI package

### ISSUE THREAD

**Issue by yuxiangtan** [conda/conda#9371]
**I'm submitting a...**
  - [ ] bug report

## Current Behavior
Using the instruction on the package website: https://anaconda.org/bioconda/rgi
I was not able to install the latest version 5.1.0.
The only success led to the installation of a very old version of 3.2.2.
However, I checked the files and the version 5.1.0 one was there.
But I got the following error and had no way to make it go through:

$ conda create -c bioconda rgi=5.1.0 -n rgi
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                  failed

PackagesNotFoundError: The following packages are not available from current channels:

  - filetype[version='>=1.0.0']

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

### Steps to Reproduce
Just try the default "conda install -c bioconda rgi" will give you the error. 
And the second recommended "conda install -c bioconda/label/cf201901 rgi" will lead a the old version.

## Expected Behavior
Get the latest version using the default command.

Best,

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

$ conda info

     active environment : base
    active env location : /home/yxtan/miniconda2
            shell level : 1
       user config file : /home/yxtan/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages :
       base environment : /home/yxtan/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/yxtan/miniconda2/pkgs
                          /home/yxtan/.conda/pkgs
       envs directories : /home/yxtan/miniconda2/envs
                          /home/yxtan/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/2.7.16 Linux/4.4.0-119-generic ubuntu/16.04.4 glibc/2.23
                UID:GID : 2043:100
             netrc file : None
           offline mode : False

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

conda config --show-sources

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

conda list --show-channel-urls
# packages in environment at /home/yxtan/miniconda2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                0.24.0                   py27_0    defaults
binutils_impl_linux-64    2.31.1               h6176602_1    defaults
binutils_linux-64         2.31.1               h6176602_8    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py27_0    defaults
cffi                      1.12.2           py27h2e261b9_1    defaults
chardet                   3.0.4                    py27_1    defaults
conda                     4.7.12                   py27_0    defaults
conda-package-handling    1.6.0            py27h7b6447c_0    defaults
cryptography              2.6.1            py27h1ba5d50_0    defaults
enum34                    1.1.6                    py27_1    defaults
futures                   3.2.0                    py27_0    defaults
gcc_impl_linux-64         7.3.0                habb00fd_1    defaults
gcc_linux-64              7.3.0                h553295d_8    defaults
gxx_impl_linux-64         7.3.0                hdf63c60_1    defaults
gxx_linux-64              7.3.0                h553295d_8    defaults
idna                      2.8                      py27_0    defaults
ipaddress                 1.0.22                   py27_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1d               h7b6447c_2    defaults
pip                       19.0.3                   py27_0    defaults
pycosat                   0.6.3            py27h14c3975_0    defaults
pycparser                 2.19                     py27_0    defaults
pyopenssl                 19.0.0                   py27_0    defaults
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.16               h9bab390_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py27_0    defaults
ruamel_yaml               0.15.46          py27h14c3975_0    defaults
setuptools                41.0.0                   py27_0    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.36.1                     py_0    defaults
urllib3                   1.24.1                   py27_0    defaults
wheel                     0.33.1                   py27_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults

</p></details>

**Comment by msarahan** [comment]
Since that is Problem with bioconda packages, you need to file an issue with bioconda. https://github.com/bioconda/bioconda-recipes
