### ISSUE TITLE
Setting new environment for Django in windows 10

### ISSUE THREAD

**Issue by niksbamne** [conda/conda#9377]
Hi,
I am simply trying to set up a new environment in conda prompt. but it gave me this error what should I do because I am very new to anaconda and Django setup

conda create -name bestofpython python=3.6
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bestofpython

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I will be very thankful in advance for help.

**Comment by asishm** [comment]
`-name bestofpython` is incorrect.

either use  `--name` or `-n` for the name of the environment. i.e. `--name bestofpython` or `-n bestofpython`
