### ISSUE TITLE
Conda hardcodes path in bashrc; could be made dynamic in most cases

### ISSUE THREAD

**Issue by Maltimore** [conda/conda#9382]
In the section of the bashrc that conda manages, it uses the full path to the conda base directory to initialize. Since the vast majority of users surely have conda installed in their home directroy, one could, in those cases, use $HOME to make that path dynamic. For all those people who manage their dotfiles with git, this would be a huge help, as it would make conda work regardless of the path to the user's home directory. If a user does not have conda in their home directory, one could fall back to the full path.

**Comment by Maltimore** [comment]
> What's the issue with this path being hardcoded?
@PertuyF if the path is hardcoded in the bashrc, and I copy my bashrc around to different servers, I wouldn't have to adapt the path each time.

**Comment by PertuyF** [comment]
I think I understand your issue, but it sounds like a very special case. I assume the vast majority of users don't have to copy their bashrc to different servers.
In a similar case I either:

 1. create a symlink for `<conda_root>/etc/profile.d/conda.sh` in `/etc/profile.d/`, which will activate conda for anyone connecting to this server, regardless of their `~/.bashrc`. *This could require elevated privileges on the server*.
 2. install conda on a network space accessible from all other servers, and use this single install from anywhere with the same `~/.bashrc`. *This requires a common network between servers*.

Anyway, ZoP:8
> Special cases aren't special enough to break the rules.

**Comment by Maltimore** [comment]
Ok, thanks for looking at this!
