### ISSUE TITLE
Where to put packages to be used across all environments?

### ISSUE THREAD

**Issue by 3tilley** [conda/conda#9386]
I'm using conda environments to manage my Python projects, and over time I have amassed a fair number. The nature of my work means jumping from project to project with lots of IDEs each using their own environment, and this separation is great. However sometimes I would like a package to be available everywhere, generally these are development tools - black, mypy, pylint, pytest. It's a problem on the command line, but it's exacerbated in the IDE, Visual Studio Code expects these to always be present in the environment, and even needs things like rope installed to do basic refactoring. In order to use my IDE, I have to installed Python packages in each environment, and inevitably they get out of sync with each other and I have different versions of black formatting and reformatting my code between styles depending which env was active.

Is there a recommended way of handling this usecase, definitely scripts but maybe even importable modules? Ideally I would use the version in the environment if there was one there, but have something to fall back on. I'm happy being a power-user with site-packages complexity, but I do need a solution that's stable (which I didn't think hacking site-packages was).

Apologies if there is already an issue about this, I'm happy to experiment with solutions and then update the documentation with my findings.

**Comment by mfansler** [comment]
Have you considered [using default packages](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#config-add-default-pkgs)?

Another option is [environment stacking/nested activation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#nested-activation), but that's experimental and you'd have to first activate the dev tools env then the actual project env every time. Also, if you're taking about things like `pytest`, then you'd need the stackable env to match the minor version of Python used in the project.
