### ISSUE TITLE
Installation of pyzmq is broken

### ISSUE THREAD

**Issue by wikiped** [conda/conda#9395]
## Current Behavior

Trying to use `import zmq` after installing it with `conda install pyzmq` leads to error:

    λ python -c "import zmq"
    _cffi_ext.c
    D:\Anaconda\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Anaconda\lib\site-packages\zmq\__init__.py", line 47, in <module>
        from zmq import backend
      File "D:\Anaconda\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
        reraise(*exc_info)
      File "D:\Anaconda\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
        raise value
      File "D:\Anaconda\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
        _ns = select_backend(first)
      File "D:\Anaconda\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
        mod = __import__(name, fromlist=public_api)
      File "D:\Anaconda\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
        from . import (constants, error, message, context,
    ImportError: DLL load failed: The specified module could not be found.

Please note that package from `defaults` channel is used in installation, not from `conda-forge`!

### Steps to Reproduce

Running the following commands:
```
conda remove pyzmq --force
conda install pyzmq -c defaults
python -c "import zmq"
```
should not produce any errors.

## Expected Behavior

No error should appear just like if `pip` was used to install `pyzmq` or `conda-forge` was used as source for `conda install`:
```
conda remove pyzmq --force
conda install pyzmq -c conda-forge
python -c "import zmq"
```
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : C:\Users\Uzer\.condarc
 populated config files : D:\Anaconda\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.10
         python version : 3.7.4.final.0
       virtual packages :
       base environment : D:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          file:///D:/Anaconda/conda-bld/win-64
                          file:///D:/Anaconda/conda-bld/noarch
                          https://conda.anaconda.org/Primer/win-64
                          https://conda.anaconda.org/Primer/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\Uzer\.conda\pkgs
                          C:\Users\Uzer\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\Uzer\.conda\envs
                          C:\Users\Uzer\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> D:\Anaconda\.condarc <==
allow_conda_downgrades: True
auto_update_conda: False
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
pinned_packages:
  - defaults::numpy
  - conda-forge::pywin32
  - conda-forge::ruamel.yamls
  - conda-forge::jupyterlab
  - conda-forge::nodejs
  - defaults::blas
track_features:
  - mkl
channel_priority: disabled
channels:
  - defaults
  - conda-forge
  - local
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/msys2
  - https://repo.anaconda.com/pkgs/r
show_channel_urls: True
restore_free_channel: True
repodata_fns:
  - repodata.json
use_only_tar_bz2: False
report_errors: False
anaconda_upload: False
conda_build:
  filename_hashing: False
```
</p></details>

**Comment by msarahan** [comment]
You need to activate your environment. https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment
