### ISSUE TITLE
Environment Location Not Found: Not a conda environment: /Users/.../anaconda3

### ISSUE THREAD

**Issue by anserwei** [conda/conda#9398]
Hi, **`conda`** doesn't work on my Mac terminal since two days ago, it is weird.

* MacOS: Catalina 10.15

* Here are some errors:

  (1) Environment Location Not Found: Not a conda environment: /Users/.../anaconda3

![image](https://user-images.githubusercontent.com/45908137/68045050-a5ec2c80-fca6-11e9-895d-9fdf0bf0e41b.png)

  (2) **`active environment : None`**  ;   
         **`base environment : /Users/jianwei/anaconda3  (read only)`**
         Why none? read only?

![image](https://user-images.githubusercontent.com/45908137/68045215-fe232e80-fca6-11e9-8a1e-04bb71d83e4a.png)

   (3) **`conda environments:`**

![image](https://user-images.githubusercontent.com/45908137/68045369-522e1300-fca7-11e9-9bc3-073960486d4c.png)

   (4) **`which conda`**

![image](https://user-images.githubusercontent.com/45908137/68045467-8c97b000-fca7-11e9-829e-8404ac3214b1.png)

   (5) **`conda --version`**

![image](https://user-images.githubusercontent.com/45908137/68045512-ad600580-fca7-11e9-961f-f09278050afa.png)

   (6) I tried to run **`conda activate base`** or  **`conda activate anaconda3`**, but the error exists.
   
     **`conda activate base`** 

![image](https://user-images.githubusercontent.com/45908137/68046183-40e60600-fca9-11e9-9d23-304d34611a42.png)

     **`conda activate anaconda3`**,

![image](https://user-images.githubusercontent.com/45908137/68046154-2b70dc00-fca9-11e9-83c7-7355d10a54ac.png)

   (6) **`vim .bash_profile`**

![image](https://user-images.githubusercontent.com/45908137/68045797-5c9cdc80-fca8-11e9-851c-a5b6d3990218.png)
![image](https://user-images.githubusercontent.com/45908137/68045841-73433380-fca8-11e9-8533-7e2b8e75fc37.png)
![image](https://user-images.githubusercontent.com/45908137/68045854-7f2ef580-fca8-11e9-8fcc-7417cc4c3ed6.png)
![image](https://user-images.githubusercontent.com/45908137/68045873-8a822100-fca8-11e9-9250-6bd45de37b01.png)
![image](https://user-images.githubusercontent.com/45908137/68045894-953cb600-fca8-11e9-8517-474e9969f189.png)

I would appreciate it if someone can tell me how to fix this if it is possible.

Thank you,

**Comment by franva** [comment]
same issue here. could anyone help please?

**Comment by bglxx** [comment]
same issue here causing lots of problems.

Working on macos catalina, starting vs-code, opening a directory in vs-code terminal activates an environment, that points to a different location.

`Users/myuser/files/vs_workspace/projects/django_test_1) myuser@Bernds-iMac projname_1 % conda info

     active environment : /Users/myuser/files/vs_workspace/projects/django_test_1
    active env location : /Users/myuser/files/vs_workspace/projects/django_test_1
            shell level : 2
       user config file : /Users/myuser/.condarc
 populated config files : /Users/myuser/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.5.final.0
       virtual packages : 
       base environment : /Users/myuser/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/myuser/anaconda3/pkgs
                          /Users/myuser/.conda/pkgs
       envs directories : /Users/myuser/.conda/envs
                          /Users/myuser/anaconda3/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.5 Darwin/19.2.0 OSX/10.15.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False`

additional problems: installing a module like mysql-connector-python works until I reboot my mac. After rebooting the module isnt available:
` import mysql.connector as mariadb
ModuleNotFoundError: No module named 'mysql'`

I think, the problem starts at the point, where the default environment points to a non existing directory.

The result is, that it needs too much time to start development work in the morning because I need to reinstall already installed modules.
