### ISSUE TITLE
No OS-agnostic way to use "conda env export"

### ISSUE THREAD

**Issue by jaklan** [conda/conda#9399]
## Current Behavior

Currently the only command which can be used to export conda env is `conda env export` (`conda list --export` is useless for many reasons, i.a. problems with pip packages). When you use it as it is, you won't be able to use the generated .yml file on other OS due to incompatibility of builds. But that's why we have `--no-builds` flag - when we use it, we get a .yml file only with pinned package versions, without build information. That sounds pretty okay, but there's one more problem with that solution - in the generated file we get all the packages from the given conda env - also these one, which are specific for the current OS (e.g. MacOS). So again - you can't use the new frozen_environment.yml file e.g. in Linux-based Docker container, because the env creation is going to fail on installing MacOS-related packages. 

The topic is discussed [here](https://stackoverflow.com/questions/39280638/how-to-share-conda-environments-across-platforms), but without a real solution. The conclusion is:
> Recommendation: manually create an environment.yaml file and specify or pin only the dependencies that you care about

So I'd like to propose the solution based on that recommendation, but deleting "manually" part from it.

The another workaround is to start a Docker container with target OS, create env from the `environment.yml` (plain, without pinned versions), run `conda env export` inside the container and put the generated file in the mounted volume. The overload of such a solution is quite huge.

## Expected Behavior

It would be hard to check, if some package is OS-specific or not, but I can imagine the existence of additional flag, `conda env export --only-listed` (or any other name), which takes the path to the `environment.yml` file (and use e.g. `./environment.yml` as a default value). The expected behaviour is: 
- you pass as an input some `environment.yml` file
- under the hood, `conda env export` is used to generate a .yml file (in-memory/temp)
- this file is checked against the input file
- as a result you receive a file with the pinned versions, but only with packages, which were listed in the input file

Of course the given file can still not work in the target OS, if e.g. one of the listed packages doesn't have a build for target OS - but that's completely different problem then, so it shouldn't bother us here. Another drawback - conda env can be not "synchronized" with the given .yml file, e.g. some package from that file was then manually removed from env or vice versa - some important package was installed, but it was not added to the file. So it needs a bit of "self-awareness" from the user side, but imho it shouldn't be a blocker for adding such an additional flag - it would only need a mention in help/docs, that given `environment.yml` file works like a `schema` and there's no guarantee it reflects the current state of the env.

**Comment by soapy1** [comment]
I think the command you want to run is `conda env export --no-builds --from-history`. This removes the build, but also only gives you the packages that you explicitly installed into your environment. That will sort out your mac specific packages being included in your environment.yaml unless you are specifically installing them.

**Comment by jaklan** [comment]
@soapy1 that's interesting one, but:

- there are no pip packages in such an export
- there's only `defaults` channel listed (in the original file was also `conda-forge`)

**Comment by jaklan** [comment]
@soapy1 any chance to move if forward? The very first step should be unifying the behaviour of `conda env export --no-builds` and `conda env export --no-builds --from-history`. The current differences:
`conda env export --no-builds` | `conda env export --no-builds --from-history`
| :-: | :-: |
environment's `name` | environment's `name`
Python version more detailed than originally specified<br>(e.g. `python=3.7.8`) | Python version as originally specified<br>(e.g. `python=3.7)`
all used channels | only the `defaults` channel
all installed packages | only originally specified packages<br>(no dependencies of these packages)
pip packages | lack of pip packages
pinned versions of packages | no versions of packages
`prefix` field | `prefix` field

The difference in handling things like channels, pip packages and versions is just meaningless.

PS There should be an option to exclude `prefix` field - it's pretty useless for collaboration purposes.

**Comment by jesshart** [comment]
@jaklan did you find a sufficient solution to this problem? We are using conda for our development and having similar issues.

**Comment by jaklan** [comment]
@jesshart unfortunately not. If you use conda just as an environment manager, then as a workaround you can specify libraries in `requirements.txt`(and use pip-tools to have pinned versions) and install them by specifying the file in pip section in `environment.yml`. But if you need to mix conda and pip packages it can fail, because pip-tools knows nothing about these conda packages and their dependencies when resolving versions...

There is also interesting library conda-pack, but it's a bit different use-case (however it still can be helpful):
https://pythonspeed.com/articles/conda-docker-image-size/

**Comment by jesshart** [comment]
@jaklan thanks for taking the time. Sounds like keeping conda and pip packages separate is key for now.

**Comment by stromal** [comment]
This have worked for me - https://github.com/jupyterhub/binder/issues/149 
``` conda env export --no-builds -f environment.yml```

than isntall normaly
```conda env create --name actual_name_of_environment --file=environment.yml```

**Comment by jaklan** [comment]
> This have worked for me - [jupyterhub/binder#149 (comment)](https://github.com/jupyterhub/binder/issues/149#issuecomment-468952049)
> ` conda env export --no-builds -f environment.yml`
> 
> than isntall normaly
> `conda env create --name actual_name_of_environment --file=environment.yml`

5 comments above... https://github.com/conda/conda/issues/9399#issuecomment-677979945

**Comment by jaklan** [comment]
Haven't tested that yet, but that's a potential solution for the problem:
https://github.com/conda-incubator/conda-lock
