### ISSUE TITLE
Non-semver miniconda version (`4.7.12.1`)

### ISSUE THREAD

**Issue by Zanadar** [conda/conda#9407]
## Current Behavior

Hey conda folks! Thanks for all the hard work. Awesome project.
The latest releases of miniconda are non-semver. We consume those releases as part of an automated process for buildpacks and this has broken basically anything that deals with a version. Any way you could just release a `4.7.13` instead of `4.7.12.1`? Seems like all the other releases have had a normal structure.

### Steps to Reproduce

```
Try and parse 4.7.12.1 with any semver library. -> 💥 (BOOM)
```

## Expected Behavior

`4.7.13`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by soapy1** [comment]
@Zanadar thanks for the issue. We realize that this is not the ideal name for the miniconda installer. Future releases will follow the regular sem ver scheme. In this case in particular, we found a regression with the miniconda installer after releasing it which required a new installer. Our versioning scheme is to follow the versioning of the included conda. In this case, conda did not change it's version number so we added the .1 to denote an updated "build number".

iirc the regression only effected single core cpu machines, so as long as you are using machines with more than 1 core I believe you can reliably use 4.7.12

**Comment by Zanadar** [comment]
Thanks! 4.7.12-regression (or whatever) would technically be semver compliant but it’s all good, esp given what you said. I’ll close this issue.
