### ISSUE TITLE
No access to an envs although it's there

### ISSUE THREAD

**Issue by Philip642** [conda/conda#9408]
Hi, I am working with Ubuntu 16.04 on python 3.7 and I don't know why it couldn't find the environment although it's there
![Screenshot from 2019-11-05 16-27-02](https://user-images.githubusercontent.com/55141900/68221727-2f269a80-ffea-11e9-86bf-ddce556e8471.png)

Thanks

**Comment by soapy1** [comment]
Your output denotes that the deepposekit3 environment is not named so you need to activate it by prefix. eg `conda activate /home/einat/miniconda2/envs/deepposekit3`

**Comment by msarahan** [comment]
Note that the key difference here is that you have 2 different install folders: ~/miniconda2 and ~/anaconda3.  Each of those will use a default envs_dirs setting (https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-env-directories) which is just the root of the install folder. Thus, even though conda info --envs shows all envs (by looking at ~/.conda/environments.txt), the name lookup is only good within the currently active base environment (~/anaconda3 for you).  If you activate ~/miniconda2, you'll find that it flips.  deepposekit3 will be activatable by name, but the other environments won't be.

You can customize and centralize this behavior using the link to the docs above.
