### ISSUE TITLE
erroneous UnsatisfiableError message when trying to install enum34

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#9417]
When trying to install enum34 via conda, I get the following `UnsatistfiableError`:
```
UnsatisfiableError: The following specifications were found                                                                                 
to be incompatible with the existing python installation in your environment:

Specifications:

  - enum34 -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.7
```
However, this does not make sense because the version satisfies the condition. 

Running conda 4.7.12 on Linux.

**Comment by fonnesbeck** [comment]
When trying to install enum34 via conda, I get the following `UnsatistfiableError`:
```
UnsatisfiableError: The following specifications were found                                                                                 
to be incompatible with the existing python installation in your environment:

Specifications:

  - enum34 -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.7
```
However, this does not make sense because the version satisfies the condition. 

Running conda 4.7.12 on Linux.

**Comment by jjhelmus** [comment]
`enum34` is only available for Python **2**.7.  The error message indicates you Python is **3**.7.

**Comment by fonnesbeck** [comment]
Sorry, misread that.

**Comment by msarahan** [comment]
Yeah, it's a little backwards, but the output is telling you what is available, not what is missing.  We haven't found a good way to tell you exactly what's missing, yet, but we're always thinking about how to improve that.  Trust me, reading those messages drives us just as crazy as anyone else.
