### ISSUE TITLE
Env isolation failure

### ISSUE THREAD

**Issue by vandesa003** [conda/conda#9426]
Hi there. I use Conda to manage 5~6 different python environments. I thought that different envs should be totally separated and independent, however, in my case, environment A use a package from environment B. 

For example, I create a new env called A, and installed Pytorch 1.0. Then I create another env called B, unexpectedly, I can directly use Pytorch 1.0 in env B without installation!

To make things clearer, I post my screenshot here, as you can see I started python in env "segmentation", and import torch, but the directory of torch is from another env "cvnet". Anyone can tell me why?

<img width="774" alt="Screenshot 2019-11-12 at 3 43 19 PM" src="https://user-images.githubusercontent.com/10252812/68652508-94d3d300-0564-11ea-9cec-70cebeaeca22.png">

**Comment by msarahan** [comment]
Please fill out all information requested in the issue template.

**Comment by vandesa003** [comment]
Thanks for your reply @msarahan! I found it was my bad. It was because I create a new env based on an existed env. I should have deactivated env when I create a new env.
