### ISSUE TITLE
Conda metapackages should support channel-specs when specifying dependencies

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#943]
All conda packages (including meta-packages) should have some mechanism for specifying where dependencies come from in it's meta-data.   In other words, the author of the package should be able to require that conda install the dependency from that channel.  

Suppose we are installing package "foo" which has a specified dependency "bar" from channel "doge"

Scenario 1:  a suitable "bar" is already installed (satisfies version)  
    conda should check to see if the package was installed already from channel "doge" if so, it proceeds.  If not, then force install "bar" again from channel "doge" (See Scenario 3)

Scenario 2:  a suitable "bar" is not installed and a suitable "bar" is not found in channel "doge"
   raise an Error

Scenario 3:  a suitable "bar" is not installed and a suitable "bar" is found in channel "doge"
    \* install any dependencies from the merged channel index and "doge"
    \* install "bar" from the "doge" channel

**Comment by kalefranz** [comment]
> We really just need this for when the meta-package is used to define an environment

We have much better ways to define an environment now.  Please shouldn't be using conda-build and metapackages for this.  Pretty old issue, so I'm guessing the alternatives hadn't been developed when the issue was created.
