### ISSUE TITLE
Cisco Intrusion Prevention system Talos has blacklsited anaconda.org

### ISSUE THREAD

**Issue by Tagar** [conda/conda#9430]
Were there some DNS changes on anaconda.org yesterday?
None of conda commands seems to work - getting timeouts [1]

`nslookup` returns first IP as IPv6 .. not sure if this is the culprit? 

> Addresses:  2001:1111:1111:1111::1
>           192.51.100.100

[1]

> Collecting package metadata (current_repodata.json): failed
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f640c0fbb38>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))",),)
>

**Comment by Tagar** [comment]
Nevermind.. our corporate IPS (intrusion prevention system) decided to block anaconda.org and conda.anaconda.org 

192.51.100.100 is an IPS "sinkhole"

**Comment by Tagar** [comment]
Our Security told that Cisco's Talos product that we use has blacklisted anaconda.org for phishing 

https://talosintelligence.com/reputation_center/lookup?search=anaconda.org

**Comment by Tagar** [comment]
```

TALOS SECURITY INTELLIGENCE BLACKLIST |  
-- | --
BLACKLISTED | Yes
CLASSIFICATION | Phishing
FIRST SEEN | 2019-11-09T10:44:35 UTC
EXPIRATION DATE | 2019-12-11T09:45:55 UTC
STATUS | ACTIVE


```

**Comment by Tagar** [comment]
Btw, this was on Anaconda blog 43 days ago - 

![image](https://user-images.githubusercontent.com/3013418/68691594-3b05e580-0531-11ea-8216-c57b9fd6d213.png)

(that deleted posted is still cached in my feedly.com subscription that I use to read blogs )

Not sure if it's related to the fact that anaconda.org is now blacklisted by Cisco Talos intrusion prevention.. just wanted to through it out there.

**Comment by tnguyen90** [comment]
This happened at my uni today, Talos seems to blacklist anaconda.org again,

https://talosintelligence.com/reputation_center/lookup?search=anaconda.org

BLACKLISTED | Yes
-- | --
CLASSIFICATION | Phishing
FIRST SEEN | 2019-11-09T10:44:35 UTC
EXPIRATION DATE | 2020-01-10T09:35:37 UTC
STATUS | ACTIVE

I'm not sure what can be done to prevent this? Perhaps the Conda dev can write to the Talos dev to stop it from blacklisting Conda? I feel like this repetitive pattern has its own set of reasons.

**Comment by Tagar** [comment]
@tnguyen90 I suggest you to reopen https://github.com/ContinuumIO/anaconda-issues/issues/11447 
and bring it up to @@csoja there 

Thanks

**Comment by tnguyen90** [comment]
> @tnguyen90 I suggest you to reopen [ContinuumIO/anaconda-issues#11447](https://github.com/ContinuumIO/anaconda-issues/issues/11447)
> and bring it up to @csoja there
> 
> Thanks


Too easy,

Will do so

**Comment by kenodegard** [comment]
Closing as this has long since been resolved.
