### ISSUE TITLE
IOError: [Errno 13] Permission denied: u'C:\\Users\\kavia\\Anaconda2\\pkgs\\python-2.7.13-1\\DLLs\\_hashlib.pyd'

### ISSUE THREAD

**Issue by kavia-ravi** [conda/conda#9437]
conda info:
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\kavia\Anaconda2  (writable)
  default environment : C:\Users\kavia\Anaconda2
     envs directories : C:\Users\kavia\Anaconda2\envs
        package cache : C:\Users\kavia\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:
#
root                  *  C:\Users\kavia\Anaconda2

sys.version: 2.7.11 |Anaconda 4.0.0 (64-bit)| (defaul...
sys.prefix: C:\Users\kavia\Anaconda2
sys.executable: C:\Users\kavia\Anaconda2\python.exe
conda location: C:\Users\kavia\Anaconda2\lib\site-packages\conda
conda-build: C:\Users\kavia\Anaconda2\Scripts\conda-build.exe
conda-convert: C:\Users\kavia\Anaconda2\Scripts\conda-convert.exe
conda-develop: C:\Users\kavia\Anaconda2\Scripts\conda-develop.exe
conda-env: C:\Users\kavia\Anaconda2\Scripts\conda-env.exe
conda-index: C:\Users\kavia\Anaconda2\Scripts\conda-index.exe
conda-inspect: C:\Users\kavia\Anaconda2\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\kavia\Anaconda2\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\kavia\Anaconda2\Scripts\conda-pipbuild.exe
conda-server: C:\Users\kavia\Anaconda2\Scripts\conda-server.exe
conda-sign: C:\Users\kavia\Anaconda2\Scripts\conda-sign.exe
conda-skeleton: C:\Users\kavia\Anaconda2\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\kavia\Anaconda2\Library\bin;C:\Users\kavia\Anaconda2;C:\Users\kavia\Anaconda2\Scripts;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\kavia\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\kavia\Anaconda2;C:\Users\kavia\Anaconda2\Scripts;C:\Users\kavia\Anaconda2\Library\bin;C:\Users\kavia\AppData\Local\Microsoft\WindowsApps
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

===================
There was a problem updating the conda package.  Restart GraphLab Create Launcher.

Unable to update conda:
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Users\kavia\Anaconda2:

The following NEW packages will be INSTALLED:

    vc:     9-0         

The following packages will be UPDATED:

    conda:  4.0.5-py27_0 --> 4.0.8-py27_0
    python: 2.7.11-4     --> 2.7.13-1    

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "C:\Users\kavia\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\instructions.py", line 63, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\kavia\Anaconda2\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Users\kavia\Anaconda2\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\kavia\Anaconda2\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\kavia\Anaconda2\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\kavia\Anaconda2\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Users\\kavia\\Anaconda2\\pkgs\\python-2.7.13-1\\DLLs\\_hashlib.pyd'

**Comment by RyanP7577** [comment]
I was able to fix an error similar to this by deleting the file mentioned and rerunning the install command.
