### ISSUE TITLE
when "conda env create -f environment.yml", Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by brandnew2017** [conda/conda#9438]
I want to use environment.yml file to create a new virtual environment in anaconda. At the first time, I input "conda env create -f environment.yml"  in the terminal, and the result is that pytorch install is incomplete because of HTTP error shown below.
![1](https://user-images.githubusercontent.com/32150277/68836746-f9726780-06f5-11ea-9f1b-2cea6dc425c7.png)
![image](https://user-images.githubusercontent.com/32150277/68836774-0c853780-06f6-11ea-8f30-a4a4e7fa8616.png)

And then I input "conda env create -f environment.yml" in the terminal again, an error occured.
![image](https://user-images.githubusercontent.com/32150277/68836833-39d1e580-06f6-11ea-8066-fc5efdd86285.png)

I guess the reason is that pytorch is incomplete. But I don't know how to solve it.
I would appreciate it if someone can help me solve this problem. Thank you!

**Comment by rjfs** [comment]
I got same error message after the creation failed due to lack of disk space. I increased the space of my virtual machine, but now I'm also getting Segmentation fault when I execute this command.

**Comment by rjfs** [comment]
I just solved the problem after running `conda clean -a`.
See #7815

**Comment by fengenxiang1123** [comment]
I got same error message

**Comment by fengenxiang1123** [comment]
> I just solved the problem after running `conda clean -a`.
> See #7815

I manually deleted the failed package in anaconda/pkgs/, then conda clean -a, you can also referred to conda下载出现连接超时怎么办 https://blog.csdn.net/weixin_41010198/article/details/87912152.
