### ISSUE TITLE
Creating and maintaining conda environment on CI server (Jenkins)

### ISSUE THREAD

**Issue by wimvanleuven-kbc** [conda/conda#9447]
## Current Behavior
On our CI server (Jenkins) all jobs share a root conda environment. The cache is configured to a central location. 

As many builds run in parallel, the cache is heavily hitted. Many times we see jobs fails with errors like 'File already exists' or 'file does not exist', where these point to some location for a package in the cache.

We know that shared writen in the cache is an issue (https://github.com/conda/conda/issues/5997), but this effectively renders conda rather useless. 

The documentation refers that conda is excellent on CI servers, but nowhere does it mention best practices on how to use conda on CI.

### Steps to Reproduce
As the errors are intermittent, it is hard to reproduce as such on single user environments.

## Expected Behavior
The docs should explain that concurrent write to the cache gives problems on CI servers and continue on giving advice on how to setup your channels, environments and caches to limit the impact of that concurrent write issue.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
00:00:02.877      active environment : /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/conda
00:00:02.877     active env location : /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/conda
00:00:02.877        user config file : /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/.condarc
00:00:02.877  populated config files : /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/.condarc
00:00:02.877           conda version : 4.7.10
00:00:02.877     conda-build version : 3.18.9
00:00:02.877          python version : 2.7.16.final.0
00:00:02.877        virtual packages : 
00:00:02.877        base environment : /opt/jenkins/tools/python-2.7.16  (writable)
00:00:02.877            channel URLs : https://*******************/nexus/repository/dqs-conda/linux-64
00:00:02.877                           https://*******************/nexus/repository/dqs-conda/noarch
00:00:02.877                           https://*******************/nexus/repository/dqs-conda-special/linux-64
00:00:02.877                           https://*******************/nexus/repository/dqs-conda-special/noarch
00:00:02.877                           https://*******************/nexus/repository/public-conda-forge-group/linux-64
00:00:02.877                           https://*******************/nexus/repository/public-conda-forge-group/noarch
00:00:02.877                           https://*******************/nexus/repository/public-conda-group/linux-64
00:00:02.877                           https://*******************/nexus/repository/public-conda-group/noarch
00:00:02.877           package cache : /mgmt/data/jenkins/python-pkgs
00:00:02.877        envs directories : /opt/jenkins/tools/python-2.7.16/envs
00:00:02.877                           /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/.conda/envs
00:00:02.877                platform : linux-64
00:00:02.877              user-agent : conda/4.7.10 requests/2.21.0 CPython/2.7.16 Linux/3.10.0-957.27.2.el7.x86_64 rhel/7.7 glibc/2.17
00:00:02.877                 UID:GID : 80000952:160128
00:00:02.877              netrc file : /mgmt/data/jenkins/workspace/DQS/pybuilder-prepare-unittest-resources/.netrc
00:00:02.877            offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
don't have access to this on server
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
don't have access to this on server
```
</p></details>

**Comment by soapy1** [comment]
the conda docs have some information on how to use conda with ci https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html. This blog post also seems good https://levelup.gitconnected.com/continuous-deployment-with-travis-and-conda-f385fec1a3f

**Comment by jbouzaglou** [comment]
The actual answer is that conda is not safe to use "concurrently", with the same package cache. The download/linking phase is not atomic/transactional, and it is easy to reproduce your bug doing multiple conda installs with the same package cache.

See in the docs, the "remove all locks" paragraph:"
https://www.anaconda.com/announcing-general-availability-conda-43/

In my experience, you can either find a way to "lock" yourself, or you can forgo the shared package cache.

**Comment by wimvanleuven-kbc** [comment]
After some testing with bringing the cache inside the workspace of every build job (equal to not using any cache, because the workspace gets cleaned on each build), we have the same results: failing builds because some files already exist.

**Comment by jbouzaglou** [comment]
Do you have both the environment folders and the caches segregated?

**Comment by wimvanleuven-kbc** [comment]
Thanks for the input, @jbouzaglou !!

Well, for a single job/project you can not have 2 simultaneous builds ... so the workspaces, hence the caches, are by definition segregated.

I wonder if the problem is not related to how conda builds and maintains the caches. If I'm not mistaken it heavily uses (though configurable) softlinks etc. it might even optimise the local caches towards the system level caches that it anyways defines. 

Would that imply that working without cache is not possible?

Does anyone have suggestion on the subject? I'm sure we are not the only ones running conda on CI tools like Jenkins or Travis.

**Comment by jbouzaglou** [comment]
Are you sure all the conda settings make it so envs and cachés are separate? Could you dump a conda info here?
We are doing exactly that(conda in ci) and it seems to work, I might run some new stress test to check if indeed we run into similar issues to you

**Comment by wimvanleuven-kbc** [comment]
Here's our adjust condarc 

```
      active environment : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/conda
     active env location : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/conda
        user config file : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/.condarc
  populated config files : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/.condarc
           conda version : 4.7.10
     conda-build version : 3.18.9
          python version : 2.7.16.final.0
        virtual packages : 
        base environment : /opt/jenkins/tools/python-2.7.16  (writable)
            channel URLs : https://anexus3.kbc.be:6087/nexus/repository/dqs-conda/linux-64
                           https://**********/nexus/repository/dqs-conda/noarch
                           https://**********/nexus/repository/dqs-conda-special/linux-64
                           https://**********/nexus/repository/dqs-conda-special/noarch
                           https://**********/nexus/repository/public-conda-forge-group/linux-64
                           https://**********/nexus/repository/public-conda-forge-group/noarch
                           https://**********/nexus/repository/public-conda-group/linux-64
                           https://**********/nexus/repository/public-conda-group/noarch
           package cache : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/.conda/pkgs
        envs directories : /opt/jenkins/tools/python-2.7.16/envs
                           /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/.conda/envs
                platform : linux-64
              user-agent : conda/4.7.10 requests/2.21.0 CPython/2.7.16 Linux/3.10.0-957.27.2.el7.x86_64 rhel/7.7 glibc/2.17
                 UID:GID : 80000952:160128
              netrc file : /mgmt/data/jenkins/workspace/DQS/oktopuss-kbc/.netrc
            offline mode : False
```

**Comment by jbouzaglou** [comment]
What do you mean by adjusted condarc? Is that the output of conda info?
The envs seem to always go to the same folder in /opt/Jenkins, couldn't it be that the nth build files are left over when you start build n+1?
What error are you getting exactly?

**Comment by wimvanleuven-kbc** [comment]
We create out conda environment as a prefix inside the conda workspace, as the first line of the output shows marked by `active environment`

**Comment by jbouzaglou** [comment]
OK, I m just not that familiar with Jenkins, is the job workspace unique for each invocation of the pipeline?

**Comment by wimvanleuven-kbc** [comment]
@jbouzaglou yes it is unique for every build, even multiple builds for the same job are either sequenced or, in case of e.g. mutli-branch build, every branch gets it workspace.

**Comment by wimvanleuven-kbc** [comment]
@soapy1 the mentioned issue #9484 is indeed related. 

We are trying to isolate the problem by not sharing the cache ... we are still facing this issue. So we are starting to think it is a lower level issue on the edge of the cache interacting with the OS / filesystem. 

Next tests we'll do is with the configurations of hardlinks, symlinks, copies, clones ... 

What do you think?

**Comment by soapy1** [comment]
@wimvanleuven-kbc  Hmmm, that is very curious. I would expect that if you change the cache location per build then you would not have errors regarding the cache. 

If you are able to handle the download bandwidth, it might be worth it to have a fresh install of conda per build that you run. This will also ensure that builds are absolutely separated from each other. One tool you can use to make this easier if you want your environment to be prepackaged with things is to use conda-pack https://github.com/conda/conda-pack/ which will allow you to create your build environment and package it as a tar ball to be shared.

**Comment by wimvanleuven-kbc** [comment]
@soapy1 in which case it would be easier to just set everything up to use prebuild docker images, no?

**Comment by soapy1** [comment]
Ya, if you are able to use docker that would be awesome

**Comment by preetamroy33** [comment]
Hi @wimvanleuven-kbc. Can you please throw some light how are you using conda and docker both inside jenkins. We are using continuumio/miniconda images inside our container template but the issue is we are not able to run docker within that container. Can you please help?
