### ISSUE TITLE
Track environments created with the -p command

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#945]
When environments are created with the -p command, they should be added to meta-data stored in a user-writeable area.   This can be a simple file with the directory to the environment listed.   This file needs to be updated when the environment is removed --- or a clean command is issued.

**Comment by mahadi** [comment]
@ilanschnell For which purpose are the environments stored in this file? I see that the file is only updated if an environment is created but not if it is deleted again?

**Comment by mollonado** [comment]
If you run "conda config --show" you will see there is a configuration parameter callled "envs_dirs". It normally points to the location where you installed conda, and the envs subdir in it. It also points to $HOME/.conda/envs as well. By default creating a conda environment add it to one of those places. If you create it in a non-standard location you have to manually add the the new environment to the end_dirs list. The way to do it is via conda off couse (or you can do it with any text editor)
conda config --add envs_dirs <directory_where_you_installed_the_new_environment>
this will add that to the "env_dirs" list inside your $HOME/.condarc file.
