### ISSUE TITLE
[macOS]Anaconda set incorrectly the hostname

### ISSUE THREAD

**Issue by carVaba** [conda/conda#9450]
I just found that the script of anaconda override the hostname incorrectly, because when I delete the lines(img2) the computer name appears correctly 
**Left(with anaconda ) Right (without anaconda)**
<img width="1459" alt="Screen Shot 2019-11-19 at 11 36 02" src="https://user-images.githubusercontent.com/16153292/69166271-f8a84f80-0ac0-11ea-86d6-610151344618.png">

<img width="829" alt="Screen Shot 2019-11-19 at 11 36 45" src="https://user-images.githubusercontent.com/16153292/69166469-4624bc80-0ac1-11ea-9c16-09d910a5f8df.png">

I tested on Macbook Pro and Mac Mini, both have the same problem

**Comment by wimvanleuven-kbc** [comment]
I'm on Mac and the hostname shows up properly ...

**Comment by kalefranz** [comment]
Probably a duplicate of https://github.com/conda/conda/issues/7031
