### ISSUE TITLE
'pip install --user conda' sets up an unknown version for 3.7.0

### ISSUE THREAD

**Issue by wking** [conda/conda#948]
Here's what I have:

```
$ pip --version
pip 1.4.1 from /usr/lib64/python3.3/site-packages (python 3.3)
$ pip install --user conda
…
  Downloading conda-3.7.0.tar.gz (160kB): 160kB downloaded
…
  Running setup.py install for conda
    no .git in /tmp/pip_build_wking/conda
    guessing rootdir is '/tmp/pip_build_wking/conda', but 'conda' doesn't start with prefix 'conda-'
    got version from default None
…
$ conda info
Current conda install:

             platform : linux-64
        conda version : unknown
  conda-build version : not installed
…
```

I think the best solution to this is just to drop versioneer from the PyPI tarballs and hard-code the version into `conda._version` at realease time.  That looks like what `sdist.sh` is trying to do, maybe it has just fallen out of the release process?

**Comment by wking** [comment]
@kalefranz, can you comment on why this was closed?  Perhaps linking to a fix?

**Comment by kalefranz** [comment]
`pip install` is unable to install conda correctly.  Not so different than trying to `pip install python3`.  Best solution is to use a miniconda or Anaconda installer.
