### ISSUE TITLE
conda uninstall will make many packages change versions

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#9488]
Installing a bunch of packages with `-c conda-forge`  and then uninstalling one of them without `-c conda-forge` causes all conda-forge packages that are also available in anaconda's channel to be replaced with the version from the main channel.

**Comment by kalefranz** [comment]
@SylvainCorlay what version of conda are you speaking to here?

**Comment by SylvainCorlay** [comment]
That was the latest at the time when I posted the issue.
