### ISSUE TITLE
conda package: py38 build?

### ISSUE THREAD

**Issue by aldanor** [conda/conda#9499]
All of the recent builds (except 4.8.0rc0 which seems like an error) of `conda` are `py27`, `py36`, `py37`.

Any chances of getting a proper `py38` build so it can be installed into a base py38 environment? (ideally, `conda-build` as well, which will require rebuilding `py-lief` for py38, the rest of dependencies are already all py38).

// Given that conda is pure-Python, wonder if it makes sense to eventually package conda itself as noarch...

**Comment by kalefranz** [comment]
I think @mingwandroid has all of this resolved by now.
