### ISSUE TITLE
Using conda from a system that just loads the libpython shared library

### ISSUE THREAD

**Issue by cnuernber** [conda/conda#9500]
We have a project where we are dynamically loading the python shared library and using the symbols out of it to provide a deep language-level integration of [python into clojure](https://github.com/cnuernber/libpython-clj/).

We are trying to expand our environment support and lots of people in the know are using Conda so we are trying to make that pathway easier to use.  

My question is very specific: how does the python executable communicate the pythonhome to the libpython3.Xm.so shared library?

Here is my current workaround for working with conda:  
https://github.com/cnuernber/libpython-clj/issues/18#issuecomment-564774861

Is there a way I can set a [command line parameter](https://github.com/cnuernber/libpython-clj/blob/master/src/libpython_clj/python/interpreter.clj#L268) or something like that in the python shared library that tells it where pythonhome is?  I think the anaconda python executable must do something like this upon startup.

Any help is greatly appreciated!  Thanks :-).

**Comment by jjtolton** [comment]
This would be very helpful -- then we can leverage `conda` to do scientific computing in Clojure using `libpython-clj`!

**Comment by cnuernber** [comment]
We have figured out pathways through this system.  The last thing we are stuck on is, after activating the environment:
```clojure
libpython-clj.python> (def mxnet (import-module "mxnet"))
Execution error at libpython-clj.python.interpreter/check-error-throw (interpreter.clj:394).
Traceback (most recent call last):
  File "/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/chrisn/.conda/envs/pyclj/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkldnn.so.0: cannot open shared object file: No such file or directory 
```

If we `export LD_LIBRARY_PATH=$(python3-config --prefix)/lib` before running our repl then mxnet imports just fine.  

Using ctypes.util/find_library works in and returns the same answer in our system and when run as python3 -c.  

Our current best recommendation is to run from a docker container for conda.

**Comment by mingwandroid** [comment]
> My question is very specific: how does the python executable communicate the pythonhome to the libpython3.Xm.so shared library?

It does not. Our Python executable does not load libpython at all. It statically links to it.

Regardless, if we did build it dynamically, then the method by which this value is calculated is no different from upstream CPython's way: https://github.com/python/cpython/search?q=PYTHONHOME&unscoped_q=PYTHONHOME

**Comment by cnuernber** [comment]
@mingwandroid - That is very helpful.  I note that if I search under my conda environment for the libpython shared library it always exists under the appropriate environment but 'ldd' agrees with your statement.  Is the shared library built so that plugins can link against it only? 

We can set python home and executable path via the C api before initialization and this mitigates some of that issue.  

Would you have any thoughs importing mxnet, which works running python3 but fails unless I explicitly set `LD_LIBRARY_PATH` if I call `import-module` after dynamically loading libpython3.6m.so?

**Comment by mingwandroid** [comment]
> @mingwandroid - That is very helpful. I note that if I search under my conda environment for the libpython shared library it always exists under the appropriate environment but 'ldd' agrees with your statement. Is the shared library built so that plugins can link against it only?

Yes, but they can also link to the static lib if they prefer. Sometimes I think providing this shared lib by default is more trouble than it's worth, the thing holding me back is that on Windows we do build our interpreter linking to python3X.dll and it's more consistent to provide the same libs by default on all platforms.

In the stack backtrace, what is lib_path[0] at this point?

`export LD_DEBUG=all` before running this (in each case, with and without `LD_LIBRARY_PATH`) and comparing the output should prove instructive.

**Comment by cnuernber** [comment]
That did it.  The key line, when running from python3 (which works) is:
>>        129:	 search path=/home/chrisn/.conda/envs/pyclj/bin/../lib		(RPATH from file python3)


I think setting LD_LIBRARY_PATH to $prefix/lib is about as good as I can get for given I am running under a java executable. 

I have included the full text at end if anyone is curious.  

Is it OK if I close this issue?  It doesn't seem addressable to me aside from the workaround we have already implemented.

```console
success:

129:	file=libmkldnn.so.0 [0];  needed by /home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/libmxnet.so [0]
       129:	find library=libmkldnn.so.0 [0]; searching
       129:	 search path=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/.		(RPATH from file /home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/libmxnet.so)
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/x86_64/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/x86_64/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/x86_64/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./x86_64/libmkldnn.so.0
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./libmkldnn.so.0
       129:	 search path=/home/chrisn/.conda/envs/pyclj/bin/../lib		(RPATH from file python3)
       129:	  trying file=/home/chrisn/.conda/envs/pyclj/bin/../lib/libmkldnn.so.0
       129:	
       129:	file=libmkldnn.so.0 [0];  generating link map
       129:	  dynamic: 0x00007f1084c5d9e0  base: 0x00007f10842ad000   size: 0x00000000009b59e8
       129:	    entry: 0x00007f108431e040  phdr: 0x00007f10842ad040  phnum:                  9
       129:



failure:

        45:     file=libmkldnn.so.0 [0];  needed by /home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/libmxnet.so [0]
        45:     find library=libmkldnn.so.0 [0]; searching
        45:      search path=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./x86_64:/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/.            (RPATH from file /home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/libmxnet.so)
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/x86_64/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/haswell/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/x86_64/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./tls/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/x86_64/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./haswell/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./x86_64/libmkldnn.so.0
        45:       trying file=/home/chrisn/.conda/envs/pyclj/lib/python3.6/site-packages/mxnet/./libmkldnn.so.0
        45:      search cache=/etc/ld.so.cache
        45:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
        45:       trying file=/lib/x86_64-linux-gnu/libmkldnn.so.0
        45:       trying file=/usr/lib/x86_64-linux-gnu/libmkldnn.so.0
        45:       trying file=/lib/libmkldnn.so.0
        45:       trying file=/usr/lib/libmkldnn.so.0
```

**Comment by mingwandroid** [comment]
You can use patchelf to add this RPATH entry to your executable. That is my recommendation here. I'm happy for you to close this.

**Comment by cnuernber** [comment]
OK, thanks.  
patchelf is a good recommendation, I appreciate that.  Another potential route I guess would be to add an openjdk or graalvm install to conda.    

Very happy with where this ended, thanks a lot!

**Comment by mingwandroid** [comment]
No problem! Happy to help.
