### ISSUE TITLE
Very old conda (4.4.x) has stopped being able to install packages

### ISSUE THREAD

**Issue by betatim** [conda/conda#9503]
Hi,

I am not sure if this is a bug report or more a "maybe you can help us" issue. 

[repo2docker](https://github.com/jupyter/repo2docker) is a tool that automatically builds docker images from repositories by inspecting the contents of the repo. It is the tool that does all the heavy lifting behind the scenes of mybinder.org. We use "build packs" to provide the actual docker commands, a build pack is triggered by detecting certain conditions 9presence of particular files, etc) in the repo.

A few days (or maybe a week, we aren't quite sure) one of the integration tests for our "legacy buildpack" started failing. This build pack detects that a repo contains a `Dockerfile` which inherits from a particular base image. It is "legacy" because we inherited it from how the very early mybinder.org worked. We can't really change much about it (other than finally retire it). This means we start with a fairly old `conda`, upgrade it in two steps, certain packages are installed in particular versions, etc.

The `Dockerfile` that repo2docker ends up generating and which doesn't run any more is pasted below. You need three files in your local directory to be able to run this: [apt-sources.list](https://github.com/jupyter/repo2docker/raw/master/repo2docker/buildpacks/legacy/apt-sources.list), [python3.frozen.yml](https://github.com/jupyter/repo2docker/raw/master/repo2docker/buildpacks/legacy/python3.frozen.yml) and [root.frozen.yml](https://github.com/jupyter/repo2docker/raw/master/repo2docker/buildpacks/legacy/root.frozen.yml).

The [error we see on travis](https://travis-ci.org/jupyter/repo2docker/jobs/622090584#L844) is

```
RemoveError: This operation will remove conda without replacing it with
another version of conda.
```

This is the `Dockerfile` we end up trying to build:
```
FROM andrewosh/binder-base@sha256:eabde24f4c55174832ed8795faa40cea62fc9e2a4a9f1ee1444f8a2e4f9710ee

USER root
# update the source list now that jessie is archived
COPY apt-sources.list /etc/apt/sources.list
USER main
COPY python3.frozen.yml /tmp/python3.frozen.yml
COPY root.frozen.yml /tmp/root.frozen.yml

# update conda in two steps because the base image
# has very old conda that can't upgrade past 4.3
RUN conda install -yq conda>=4.3 && \
    conda install -yq conda==4.4.11 && \
    conda env update -n python3 -f /tmp/python3.frozen.yml && \
    conda remove -yq -n python3 nb_conda_kernels _nb_ext_conf && \
    conda env update -n root -f /tmp/root.frozen.yml && \
    /home/main/anaconda2/envs/python3/bin/ipython kernel install --sys-prefix && \
    /home/main/anaconda2/bin/ipython kernel install --prefix=/home/main/anaconda2/envs/python3 && \
    /home/main/anaconda2/bin/ipython kernel install --sys-prefix


USER root

## Everything below here is specific to the repo we are trying to build
## probably irrelevant for this issue but wanted to include it to give
## all the information.

# Add Julia dependencies
RUN apt-get update
RUN apt-get install -y julia libnettle4 && apt-get clean

USER main

# Install Julia kernel
RUN julia -e 'Pkg.add("IJulia")'

ADD verify verify


USER root
COPY . /home/main/notebooks
RUN chown -R main:main /home/main/notebooks && \
    rm /home/main/notebooks/root.frozen.yml && \
    rm /home/main/notebooks/python3.frozen.yml && \
    rm /home/main/notebooks/apt-sources.list
USER main
WORKDIR /home/main/notebooks
ENV PATH /home/main/anaconda2/envs/python3/bin:$PATH
ENV JUPYTER_PATH /home/main/anaconda2/share/jupyter:$JUPYTER_PATH
CMD jupyter notebook --ip 0.0.0.0
```

I've started poking around/guessing how to fix this in https://github.com/jupyter/repo2docker/pull/829. It seems like the first thing to try is to use a modern version of conda. 4.7.12 just seems to hang forever when collecting the repodata.json and 4.7.10 also prints an error.

After that poking around in the dark (because I don't fully understand why our build pack is the way it is and how conda works on the inside) I thought I'd post here to see if you have an idea.

Maybe some service or format that used to exist in old conda versions has been finally turned off/been removed with the release of conda 4.8.x which caused this to break now?

Any ideas or pointers would be welcome. Also a "even with all our conda expertise we are stumped" would also be good because it would help justify removing support for this (very) old build pack. I think that would be preferred to completely changing how the build pack works by changing base images and such.

---

I am about to disconnect from the internet for three weeks so cc'ing @choldgraf and @minrk, maybe they have time to respond to questions you have. Otherwise I will be back in 2020 :) Have a nice and hopefully quiet holidays/end of the decade :)

**Comment by msarahan** [comment]
There's nothing we've done intentionally that would cause that.  Your script captures the addition of the "main" channel that happend at conda 4.3.27.  You then try to update to conda 4.4.x.  There's nothing wrong with that approach.  It keeps the "free" channel in your defaults collection.  It was removed in 4.7.0, and that caused some of these very long solve times when people needed packages that were only available on "free." However, with conda 4.4.x, that should not be the problem here.  Do you see conda being updated anywhere after you change it to 4.4.x?  If not, I think some metadata hotfixing may have broken things for you.

My recommendation is for you to try the standalone conda to create your environment:

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#bootstrap-your-environment

so your dockerfile would look something like:

```
RUN wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe && \
    chmod +x conda.exe && \
    export CONDA_ALWAYS_YES=1
    export CONDA_AUTO_UPDATE_CONDA=0
	export CONDA_RESTORE_FREE_CHANNEL=1
    ./conda.exe env create -p ~/python3 -f /tmp/python3.frozen.yml && \
    ./conda.exe remove -yq -p ~/python3 nb_conda_kernels _nb_ext_conf && \
    ./conda.exe env create -p ~/root -f /tmp/root.frozen.yml && \
    ~/python3/bin/ipython kernel install --sys-prefix && \
    ~/root/bin/ipython kernel install --prefix=~/python3 && \
    ~/root/bin/ipython kernel install --sys-prefix
```

**Comment by betatim** [comment]
Thanks a lot for the detailed reply.

We ended up opting to deprecate the buildpack which had this problem. Partly because it seems no one is complaining that it is broken and because even with your suggestion I couldn't quite get it to work. So we took the opportunity to reduce our maintenance load by deleting a whole bunch of code :)
