### ISSUE TITLE
After `conda update --all` I get `ImportError: No module named conda`

### ISSUE THREAD

**Issue by newptcai** [conda/conda#9505]
I just did a 

    conda update --all

There was no errors reported.

But now I get 

    ImportError: No module named conda

whenever I start a new terminal.  Is there anyway to find where this comes from?

I am using conda 4.8.0

**Comment by AAnzel** [comment]
Can confirm this happening on my system as well.
Whole output:
`
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named conda
`

**Comment by loveritsu929** [comment]
Seems that it's caused by the line `eval "$__conda_setup"` in `~/.bashrc`
Currently, I just comment that out and add 'conda activate' to my `.bashrc`. The error is gone.

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/cxing95/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /de$
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
    if [ -f "/home/cxing95/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/cxing95/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/cxing95/anaconda3/bin:$PATH"
    fi
#fi
conda activate
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by amoux** [comment]
> Seems that it's caused by the line `eval "$__conda_setup"` in `~/.bashrc`
> Currently, I just comment that out and add 'conda activate' to my `.bashrc`. The error is gone.
> 
> ```
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!
> __conda_setup="$('/home/cxing95/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /de$
> #if [ $? -eq 0 ]; then
> #    eval "$__conda_setup"
> #else
>     if [ -f "/home/cxing95/anaconda3/etc/profile.d/conda.sh" ]; then
>         . "/home/cxing95/anaconda3/etc/profile.d/conda.sh"
>     else
>         export PATH="/home/cxing95/anaconda3/bin:$PATH"
>     fi
> #fi
> conda activate
> unset __conda_setup
> # <<< conda initialize <<<
> ```

I had this same problem a few minutes ago. @loveritsu929 solution worked on my setup ( ` ubuntu-19.10` ). Thank you!!

**Comment by tri4hard** [comment]
> Seems that it's caused by the line `eval "$__conda_setup"` in `~/.bashrc`
> Currently, I just comment that out and add 'conda activate' to my `.bashrc`. The error is gone.
> 
> ```
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!
> __conda_setup="$('/home/cxing95/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /de$
> #if [ $? -eq 0 ]; then
> #    eval "$__conda_setup"
> #else
>     if [ -f "/home/cxing95/anaconda3/etc/profile.d/conda.sh" ]; then
>         . "/home/cxing95/anaconda3/etc/profile.d/conda.sh"
>     else
>         export PATH="/home/cxing95/anaconda3/bin:$PATH"
>     fi
> #fi
> conda activate
> unset __conda_setup
> # <<< conda initialize <<<
> ```

that works!
Thanks.

**Comment by mhangaard** [comment]
I got this on Ubuntu 18.04. My conda info:
```
     active environment : base
    active env location : /home/mh/anaconda3
            shell level : 1
       user config file : /home/mh/.condarc
 populated config files : 
          conda version : 4.8.0
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.27
       base environment : /home/mh/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mh/anaconda3/pkgs
                          /home/mh/.conda/pkgs
       envs directories : /home/mh/anaconda3/envs
                          /home/mh/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.4 Linux/5.0.0-37-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by Lumenified** [comment]
Thanks @loveritsu929 .. It worked like a charm <3

**Comment by liho98** [comment]
> Seems that it's caused by the line `eval "$__conda_setup"` in `~/.bashrc`
> Currently, I just comment that out and add 'conda activate' to my `.bashrc`. The error is gone.
> 
> ```
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!
> __conda_setup="$('/home/cxing95/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /de$
> #if [ $? -eq 0 ]; then
> #    eval "$__conda_setup"
> #else
>     if [ -f "/home/cxing95/anaconda3/etc/profile.d/conda.sh" ]; then
>         . "/home/cxing95/anaconda3/etc/profile.d/conda.sh"
>     else
>         export PATH="/home/cxing95/anaconda3/bin:$PATH"
>     fi
> #fi
> conda activate
> unset __conda_setup
> # <<< conda initialize <<<
> ```

Same issue here,
![Screenshot from 2019-12-14 16-11-38](https://user-images.githubusercontent.com/44250267/70845679-7b3be900-1e8c-11ea-89df-e0d76a5e9119.png),
![Screenshot from 2019-12-14 16-21-22](https://user-images.githubusercontent.com/44250267/70845795-e4702c00-1e8d-11ea-80b2-1c3a9ac40252.png)

After testing @loveritsu929 's solution, the problem was solved! Thank you!

**Comment by liho98** [comment]
> Seems that it's caused by the line `eval "$__conda_setup"` in `~/.bashrc`
> Currently, I just comment that out and add 'conda activate' to my `.bashrc`. The error is gone.
> 
> ```
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!
> __conda_setup="$('/home/cxing95/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /de$
> #if [ $? -eq 0 ]; then
> #    eval "$__conda_setup"
> #else
>     if [ -f "/home/cxing95/anaconda3/etc/profile.d/conda.sh" ]; then
>         . "/home/cxing95/anaconda3/etc/profile.d/conda.sh"
>     else
>         export PATH="/home/cxing95/anaconda3/bin:$PATH"
>     fi
> #fi
> conda activate
> unset __conda_setup
> # <<< conda initialize <<<
> ```

Same issue here,
![Screenshot from 2019-12-14 16-11-38](https://user-images.githubusercontent.com/44250267/70845679-7b3be900-1e8c-11ea-89df-e0d76a5e9119.png),
![Screenshot from 2019-12-14 16-21-22](https://user-images.githubusercontent.com/44250267/70845795-e4702c00-1e8d-11ea-80b2-1c3a9ac40252.png)

But. after testing @loveritsu929 's solution, the problem was solved! Thank you!

**Comment by newptcai** [comment]
I got `conda: command not found` if I try comment out `eval "$__conda_setp"`.

```
# added by Anaconda3 5.3.1 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false $HOME/anaconda3/bin/conda shell.bash hook 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
    if [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
# . "$HOME/anaconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        export PATH="$HOME/anaconda3/bin:$PATH"
    fi
#fi
unset __conda_setup
# <<< conda init <<<
```

**Comment by sharbie88** [comment]
@loveritsu929  I also get `conda: command not found` after 

> Currently, I just comment that out and add 'conda activate' to my .bashrc.

```
conda: command not found
sharb@sharb-Latitude-5490:~$ 
```

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/sharb/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/home/sharb/miniconda3/etc/profile.d/conda.sh" ]; then
#        . "/home/sharb/miniconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/home/sharb/miniconda3/bin:$PATH"
#    fi
#fi
conda activate
unset __conda_setup
# <<< conda initialize <<<
```
Im usuing Ubuntu 18.04.3

**Comment by piglesias1** [comment]
This error happens due to a execution of the python of the system, that does not have the conda package, and then we get this error message when loading the shell. The error happens in the file `<conda_install>/etc/bash_completion.d/conda` on line 36. See below:

```sh
        CONDA_SOURCE=$(
            cat - <<'            EOF' | sed 's/^ *: //g' | python - # Loading system python
            : from __future__ import print_function
            : import os
            : import conda      # Error loading conda package
            : print(os.path.dirname(conda.__file__))
            EOF
        )
```
I just changed the line 36 and loaded the `CONDA_PYTHON_EXE` that has the conda package. The line 36 changed to:
```sh
        CONDA_SOURCE=$(
            cat - <<'            EOF' | sed 's/^ *: //g' | ${CONDA_PYTHON_EXE} -  # Fix
            : from __future__ import print_function
            : import os
            : import conda
            : print(os.path.dirname(conda.__file__))
            EOF
        )
```
It seems that this change fixed the issue. See #9507.

**Comment by newptcai** [comment]
@piglesias1  Thanks! It solves my problem.

**Comment by sharbie88** [comment]
@piglesias1 thank you very much.

**Comment by sharbie88** [comment]
@mhangaard I have a newbie question - what command did you use to get the information you posted above?

**Comment by piglesias1** [comment]
Hi @sharbie88, the command is:
```sh
$ conda info
```

**Comment by kronosmot** [comment]
> @loveritsu929 I also get `conda: command not found` after
> 
> > Currently, I just comment that out and add 'conda activate' to my .bashrc.
> 
> ```
> conda: command not found
> sharb@sharb-Latitude-5490:~$ 
> ```
> 
> ```
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!
> __conda_setup="$('/home/sharb/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
> #if [ $? -eq 0 ]; then
> #    eval "$__conda_setup"
> #else
> #    if [ -f "/home/sharb/miniconda3/etc/profile.d/conda.sh" ]; then
> #        . "/home/sharb/miniconda3/etc/profile.d/conda.sh"
> #    else
> #        export PATH="/home/sharb/miniconda3/bin:$PATH"
> #    fi
> #fi
> conda activate
> unset __conda_setup
> # <<< conda initialize <<<
> ```
> 
> Im usuing Ubuntu 18.04.3. But I've just noticed my conda is in miniconda3 not anaconda3???

Be sure to not comment out the following section:

```
    if [ -f "/home/sharb/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/sharb/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/sharb/miniconda3/bin:$PATH"
```

Leaving that in the code fixed the "conda: command not found" error for me.

**Comment by virginia-m** [comment]
I have the same (or similar?) problem with miniconda (version 4.6.8) on Ubuntu 16.04, but neither @loveritsu929's nor @piglesias1's solutions work for me. I just tried to install a new module (namely qutip) using `conda install` and then conda tried to download a new python version at the same time and now it's broken. It actually broke even before finishing the installation and the error is the same error that I am seeing every time I open a new terminal now:

```
Traceback (most recent call last):
  File "/home/virginia/.miniconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

With regards to @piglesias1's suggestion:
This file uses the miniconda python as executable (first line of this file is: `#!/home/virginia/.miniconda3/bin/python`. Also, the path to the file he mentions does not exist for me- I only have a `profile.d/` directory in the `etc/` directory, which contains a conda.sh and a conda.csh file but neither of them contain the code snippet he showed, so maybe I'm looking in the wrong place?

And with regards to @loveritsu929's suggestion:
I commented out the specified lines in my .bashrc but the error persists.

Does anybody have any ideas? Thanks!!

**Comment by piglesias1** [comment]
Hi @virginia-m,

The error of this thread is related to conda version 4.8.0 after a conda update. As you commented, your version is 4.6.8. Have you tried to update miniconda to an newer version? The current version is 4.8.3.

**Comment by huckiyang** [comment]
> I tried the solutions stated but was unable to resolve the issue through them. However this [post](https://stackoverflow.com/a/54563455/12218448) worked like a charm for me.

This works for me. quote from [merv](https://stackoverflow.com/questions/54546450/how-does-using-conda-to-install-a-package-change-my-python-version-and-remove-co/54563455#54563455).

Basically the idea is on the rollback revision by a clean conda
`
wget -O conda-exec https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe
chmod +x conda-exec
export CONDA_ROOT_PREFIX=$/home/$your_username/anaconda3
./conda-exec info
./conda-exec list -n base --revisions # check your revision
./conda-exec install -n base --revision 0 # in my case only "0" and - "1" as the conflict version, so come back to 0
`

I tried many solutions but only this works for me.

**Comment by Sayyam-Jain** [comment]
> > I tried the solutions stated but was unable to resolve the issue through them. However this [post](https://stackoverflow.com/a/54563455/12218448) worked like a charm for me.
> 
> This works for me. quote from [merv](https://stackoverflow.com/questions/54546450/how-does-using-conda-to-install-a-package-change-my-python-version-and-remove-co/54563455#54563455).
> 
> Basically the idea is on the rollback revision by a clean conda
> 
> ```shell
> wget -O conda-exec https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe
> chmod +x conda-exec
> export CONDA_ROOT_PREFIX=$/home/$your_username/anaconda3
> ./conda-exec info
> ./conda-exec list -n base --revisions # check your revision
> ./conda-exec install -n base --revision 0 # in my case only "0" and - "1" as the conflict version, so come back to 0
> ```
> 
> I tried many solutions but only this works for me.

Thank you. Worked like a charm

**Comment by ShaoxuanYin** [comment]
> This error happens due to a execution of the python of the system, that does not have the conda package, and then we get this error message when loading the shell. The error happens in the file `<conda_install>/etc/bash_completion.d/conda` on line 36. See below:
> 
> ```shell
>         CONDA_SOURCE=$(
>             cat - <<'            EOF' | sed 's/^ *: //g' | python - # Loading system python
>             : from __future__ import print_function
>             : import os
>             : import conda      # Error loading conda package
>             : print(os.path.dirname(conda.__file__))
>             EOF
>         )
> ```
> 
> I just changed the line 36 and loaded the `CONDA_PYTHON_EXE` that has the conda package. The line 36 changed to:
> 
> ```shell
>         CONDA_SOURCE=$(
>             cat - <<'            EOF' | sed 's/^ *: //g' | ${CONDA_PYTHON_EXE} -  # Fix
>             : from __future__ import print_function
>             : import os
>             : import conda
>             : print(os.path.dirname(conda.__file__))
>             EOF
>         )
> ```
> 
> It seems that this change fixed the issue. See #9507.

Same issue, but I cannot find the `conda` in the directory of  `anaconda3/etc/bash_completion.d/' 
And I search the filename `conda`
only
```
import re
import sys

from conda.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
The issue is so close....

**Comment by ShaoxuanYin** [comment]
> > This error happens due to a execution of the python of the system, that does not have the conda package, and then we get this error message when loading the shell. The error happens in the file `<conda_install>/etc/bash_completion.d/conda` on line 36. See below:
> > ```shell
> >         CONDA_SOURCE=$(
> >             cat - <<'            EOF' | sed 's/^ *: //g' | python - # Loading system python
> >             : from __future__ import print_function
> >             : import os
> >             : import conda      # Error loading conda package
> >             : print(os.path.dirname(conda.__file__))
> >             EOF
> >         )
> > ```
> > 
> > 
> > I just changed the line 36 and loaded the `CONDA_PYTHON_EXE` that has the conda package. The line 36 changed to:
> > ```shell
> >         CONDA_SOURCE=$(
> >             cat - <<'            EOF' | sed 's/^ *: //g' | ${CONDA_PYTHON_EXE} -  # Fix
> >             : from __future__ import print_function
> >             : import os
> >             : import conda
> >             : print(os.path.dirname(conda.__file__))
> >             EOF
> >         )
> > ```
> > 
> > 
> > It seems that this change fixed the issue. See #9507.
> 
> Same issue, but I cannot find the `conda` in the directory of `anaconda3/etc/bash_completion.d/ And I search the filename `conda`
> only
> 
> ```
> import re
> import sys
> 
> from conda.cli import main
> 
> if __name__ == '__main__':
>     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
>     sys.exit(main())
> ```
> 
> The issue is so close...

Anyway, after I reinstall it, everything is fine~

**Comment by leleyi** [comment]
my god .  I  solve this issue  by   using  the package 

 bash Anaconda3-5.3.1-Linux-x86_64.sh  -u


Anaconda3-5.3.1-Linux-x86_64.sh  your install file


after I reinstalled it, everything is fine

**Comment by FalconBFR** [comment]
same problem today on Mac
`    from conda.cli import main
ModuleNotFoundError: No module named 'conda'`

after updating today
