### ISSUE TITLE
Override `environment.yml` configuration with command like arguments

### ISSUE THREAD

**Issue by Peque** [conda/conda#9506]
Having Travis, AppVeyor and other services configured for CI, it is required to run pipelines for different Python versions to ensure compatibility. I think that is a common use case.

Another common use case is having your dependencies defined in an `environment.yml` file. This includes the `python=3.7` line specifying a Python version.

However, if you want to (example line useful for Travis CI):

```
conda env create -f environment.yml python=$TRAVIS_PYTHON_VERSION
```

Conda will create an environment with the dependencies defined in `environment.yml`, ignoring any dependencies defined afterwards in the command line.

It would be great to be able to override dependencies with these command line arguments. In particular the Python version, although it could be useful for other packages too.

The current alternative, as far as I know, is to configure your pipelines to edit the `environment.yml` file before creating the environment. This is definitely not convenient. Specially since each service may require this manual edit to be performed differently.

**Comment by soapy1** [comment]
You can use the `conda create` command opposed to the `conda env create` command
```
$ conda create -p <path> python=$TRAVIS_PYTHON_VERSION --file <file_path>.txt
```

Note that in this case you don't have an `environment.yaml` file, but rather a text file that lists your dependencies

**Comment by Peque** [comment]
@soapy1 That text file is in the format of a classic `requirements.txt` file, right?

If that is the case, you cannot really replace an `environment.yml` file with a `requirements.txt` file.

In particular:

- Conda channels
- Conda-only dependencies (which are not available for install in PyPI)
- pip-only dependencies (which are not available for install in Conda)

Am I right? or am I missing something?

**Comment by soapy1** [comment]
@Peque yup, that's mostly right. This workaround is not without it's limitations. 
Taking the requirements approach you can get around the channels bit by specifying the channels you want in the cli `conda install -c <chn> ....`. Or you can specify it in your requirements file using the `<chn>::<pkg>` notation. So, this will enable you to install any conda package from any channel, but won't solve the pip problem.
