### ISSUE TITLE
"ImportError: No module named conda.cli" after install mgltools

### ISSUE THREAD

**Issue by mkoohim** [conda/conda#9514]
Hello everyone,

I recently installed the last version of the miniconda and after that I've installed mgltools. But now I can't run conda command and I get "ImportError: No module named conda.cli".

The whole story is here:
1- Install the last version of miniconda:
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
everything is Ok and conda and python command works. And running python command shows:
```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

2- Install mgltools using the following command:
conda install -c bioconda mgltools
https://anaconda.org/bioconda/mgltools

Now running python command shows:

```
$ python
Python 2.5.6 (r256:88840, Nov  6 2012, 15:29:26)
[GCC 4.1.2 20061115 (prerelease) (Debian 4.1.1-21)] on linux2
```

It seems python downgraded! Also conda command doesn't work and shows the following:

```
$ conda
Traceback (most recent call last):
  File "/miniconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
```

I have no idea its a bug of conda or a bug of mgltools package! I do appreciate if someone help me to fix it.

Thanks,

**Comment by mosayebi** [comment]
Same problem here. Any suggestions?

**Comment by mkoohim** [comment]
As I found its not possible to mgltools conda package on python 3 as its package is too old and its not compatible with python 3.

**Comment by Lilith-97** [comment]
I have the same problem, sadly, I haven't been able to solve it.

**Comment by ClaireLoison** [comment]
Same problem . I haven't found any solution.

**Comment by Lunathi1** [comment]
Hi all. 

I recently ran into this problem. 
It seemed to be solved by firstly creating a python 2 environment in Miniconda. Then go on to download the mgltools in the python environment you just created, which is python2. 

This would be to separate the python version that miniconda runs on with the error imposed by mgltools on python 3.  

After following these steps, my miniconda did not break, nor did I meet any import errors. 

Please do note: I am fairly new to programming so this is a solution is explained in simple terms and should be taken at your own discretion.
