### ISSUE TITLE
Allow for "transform" conda package

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#952]
In order to allow a single conda package to be used for multiple platforms, versions of dependent libraries, etc, conda needs to be able to define a conda package that requires some work to be done on install.    It is possible that this can be done with pre-link and post-link scripts --- though we should test for this use case and ensure that these scripts have relevant variables available to them.   

Also, as the "transform" may alter the untarred directory differently for different versions of Python, for example, it may be necessary to have multiple versions of the cached directory.   Alternatively, such conda packages could just copy their contents into the corresponding environment and not use linking at all.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1963
