### ISSUE TITLE
when i started anaconda prompt i have this issues how i can i sole it pls help me

### ISSUE THREAD

**Issue by kamilos18** [conda/conda#9527]
C:\Windows\system32>SET DISTUTILS_USE_SDK=1

C:\Windows\system32>SET MSSdk=1

C:\Windows\system32>SET platform=

C:\Windows\system32>IF /I [AMD64] == [amd64] set "platform=true"

C:\Windows\system32>IF /I [] == [amd64] set "platform=true"

C:\Windows\system32>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )

C:\Windows\system32>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
ERROR: The system was unable to find the specified registry key or value.

C:\Windows\system32>if "" == "" (set "VSINSTALLDIR=" )

C:\Windows\system32>if "" == "" (
ECHO "WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
 GOTO End
)
"WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
The system cannot find the batch label specified - End

**Comment by Sanardi** [comment]
Following... I have the same issue.....
