### ISSUE TITLE
Need gcc 7.4 to build Tensorflow 2.1

### ISSUE THREAD

**Issue by JonTriebenbach** [conda/conda#9528]
## Current Behavior

Tensorflow 2.1 will not build on x86 with gcc 7.2 nor with gcc 7.3.

gcc 7.2 and gcc 7.3 fail with an internal compiler failure.  See Tensorflow issue https://github.com/tensorflow/tensorflow/issues/33431.

The only work-around is to revert to the gcc 5.4.0 level to build Tensorflow 2.1.

The internal compiler failure only occurs on the x86 builds.  Does not occur on ppc64le builds with gcc 7.2 and gcc 7.3.  (No explanation why ppc64le builds succeed.)

Tensorflow 2.1 is already building release candidates.  An update to the gcc 7.4 compiler is needed soon.  Thanks.

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by BraINstinct0** [comment]
This seems like it should go to ```tensorflow``` repo not ```conda```?

**Comment by JonTriebenbach** [comment]
An updated version of the compiler is needed in the conda toolchain.  This is not a tenorflow code issue.
