### ISSUE TITLE
The Conda home page: adoption-friendliness needs improvement

### ISSUE THREAD

**Issue by gwideman** [conda/conda#954]
I applaud the motivation and mission behind Conda, as spelled out on various continuum blog pages. 

However, the Conda home page (http://conda.pydata.org, which is also the target of many links on continuum and other pages), is hurting that mission, in my view.

In general, it is far too focused on vague highlights of internal details of Conda, and not directed at the actual benefits to prospective users. Instead of encouraging the reader to take action (start down that path of trying Conda), it raises enough suspicion and confusion that it actually discourages action. 

I will elaborate in detail, in hopes that the Conda team will be moved to improve the page, and to clarify some of the key points. From the top:

**1. "Fork me on Github".**  The most eye-catching thing on the page is the "Fork me on Github" red slash in the top right corner (at least, when the browser window is relatively wide).  Right away this suggests to me that Conda is a work in progress, something that enthusiasts are still fiddling with, and is probably not ready to be used by me yet.

Later I realized that "Fork me on Github" is actually about this _page_, not Conda per se. Still, you really want that to be the first message to prospective Conda adopters?

**2. "Conda is a cross-platform, Python-agnostic, binary package manager."**
I am sure that means something to you all, but I can only guess what that is.

"Cross-platform": Ok that's good, but kind of bare minimum to be useful.

"Python-agnostic": WTF? Does this mean Conda doesn't use Python? Can install all sorts of things unrelated to Python? Does use Python but doesn't care what version? Doesn't care whether it's installing stuff for CPython or PyPy or Iron Python? Totally confusing.

"binary package manager": OK, but this runs into ongoing terminology confusions: Python module package, distribution package, and OS-level package. And "binary" in this context, so far as I can tell, doesn't actually mean the package has to include any "binary" (ie: compiled) modules. It seems to mean "doesn't require compiling on target machine", and hence could well include Python source files. But are prospective users going to know that? Heck, I don't even know myself if that's right.

**3. "It is the package manager used by Anaconda installations, but it may be used for other systems as well".**

That's encouraging, though "other systems" could mean anything.

**4. "Conda makes environments first-class citizens, making it easy to create independent environments..."**

At this point the reader has no idea what "environment" means in the Conda world, nor what "first-class citizens" means. Apparently having them be independent is good, but no idea why.

**5. "...even for C libraries."**
What would be the point of putting C libraries into an "independent environment". At face value, this would seem to make those libraries inaccessible by any other code, hence useless.

**6. "Conda is written entirely in Python,"**
OK, this finally tells us something concrete, though somewhat oblique to main points of interest. One thing we CAN infer is that Conda does not escape the need to have (or impose) a functioning Python environment as a start state, with its accompanying points of possible failure.

**7. "Installation.** Conda is a part of the Anaconda distribution. You can also download a minimal installation that only includes conda and its dependencies, called Miniconda."

A substantial fraction of readers will have come to the Conda page to learn about, well, Conda. Maybe they have a working Python environment, and want to _add_ Conda. Or maybe they just want to try Conda as a separate thing to assess how functional and unintrusive it might be.  Right away, they are stuck, because:

"Miniconda". Are there two different versions of Conda? A full Conda one and a Miniconda one? How do I choose? What do I get in Conda that is omitted from Miniconda? How do I skip fiddling around with the Mini one and get the full one? But I don't want to install full ANAconda?

I have a suspicion that "Miniconda" is just the name for the _installer_ for _full_ Conda, the exact same as in ANAconda. If so, the name is so poorly-chosen as to raise doubt about this issue, and make me postpone actually taking any action until I have time to dig around for an answer.

**8. Getting Started...** "The real power of conda comes from its ability to manage environments. In conda, an environment can be thought of as a completely separate installation. Conda installs packages into environments efficiently using hard links by default when it is possible"

Explains that an "environment" is a "completely separate installation". Installation of what? Presumably if these environments were like Python virtual envs, this blurb would say so, yet it doesn't, so they must be something different, right? Maybe they're more like VirtualBox, or Vagrant or something? Who knows?
And mentioning hard links (ie: multi hard links to single files) -- Yikes! I won't say there is no use for hard links, but the implications require careful thought. Their presence here immediately raises concerns about whether in fact those issue have been addressed. Without knowing the actual implications pertaining to Conda, "hard link" seems immediately in conflict with "independent". If I edit some file in one supposedly independent environment, is that going to impact the same file as it appears in some other linked environment? What can of worms does this open?

**----------**
The page goes on to discuss some commands one might use with Conda, which is nice, but would be more illuminating at this juncture we had more idea what Conda is and what role it tries to fulfill in the Python landscape, or the general software distribution landscape, or whatever landscape is the domain of this product.

In short, I think the mission would be better served by having this page start by telling us the landscape of use cases where this tool is beneficial, and in what way is it beneficial relative to alternatives -- and does it replace them, or work with them?. In particular, does Conda interfere with other non-Conda-associated installations of Python? To the extent it goes into the kinds of detail noted above, the page should be more careful to use terminology that is likely to be understood by readers new to the product, and avoid dwelling on internal implementation details, unless they leak problems or decisions to the users.

**-----------**
As a side note, the Contents link doesn't work when the page width is wide enough to show the menubar and red slash. And the Contents itself seems broken, not showing the headings on the pages, and instead showing only "Miniconda", which is not a heading on the page. (FF and Chrome, recent, on Windows 7)

**Comment by amfarrell** [comment]
@gwideman there now is a new page over at http://conda.io that has some improvements
