### ISSUE TITLE
Linux sh installer hangs on "Unpacking payload"

### ISSUE THREAD

**Issue by g24swint** [conda/conda#9550]
The Linux installer seems to hang at the "Unpacking payload" step when running on an AWS instance. This may or may not be related to the miniconda installer problem referenced in #9345 

This is an AWS t2.small instance 
```bash
$ uname -a
Linux ip-172-31-59-150.us-west-2.compute.internal 4.14.152-127.182.amzn2.x86_64 #1 SMP Thu Nov 14 17:32:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

And the anaconda installer was the current version as of 2019-12-27 downloaded with `curl` using:
`curl -O https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh`

Installation target directory was the default target directory of (effectively) `~/anaconda3`.

Steps to reproduce:
1. Create a new AWS t2.small instance on an Amazon Linux 2 
2. Download the current installer (2019.10)
3. Change permissions on the installer to u+x
4. Execute installer. Accept current default directory location

Thanks!

**Comment by forrestwaters** [comment]
Yes this is the same issue which will be fixed in the next Anaconda release - apologies for the troubles. Please see https://github.com/ContinuumIO/anaconda-issues/issues/11466#issuecomment-568483600 for two workarounds.
