### ISSUE TITLE
Collecting package metadata (current_repodata.json): failed

### ISSUE THREAD

**Issue by karliell** [conda/conda#9554]
Hi! I download python 3.7.6
```
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
and anaconda `conda 4.7.12`

But when I try to use 
`conda update conda`, `conda install jupyter notebook`, `conda update --all`, `conda create -n test python=3.7` 
All the commands above have the same error.
This error happens:
```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

```

![image](https://user-images.githubusercontent.com/36145675/71644860-48bc2980-2c9d-11ea-9f02-a248f9d3f565.png)

Would you please help me with this? Thank you so much for your help!!!!!

-------------------------------------------------------------------------------------------------
```

> conda info

     active environment : None
       user config file : C:\Users\Administrator\.condarc
 populated config files : C:\Users\Administrator\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Administrator\.conda\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Administrator\.conda\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by keewawa** [comment]
Same issue here.

**Comment by paulhiew** [comment]
Same here from Singapore

**Comment by paulhiew** [comment]
/app/miniconda/2/2020.01.18/bin/conda install -c conda-forge iris
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f46ec22ce90>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)

**Comment by blackmagic30** [comment]
yeah I've watched so many random videos on trying to fix it, i feel like i just downloaded 10 viruses but i just wanted it to work. Still no luck

**Comment by BerndKarlsboeck** [comment]
your SSL module is not available.
Download open SSL (Win64 OpenSSL v1.1.1d) here: [Link](https://slproweb.com/products/Win32OpenSSL.html)
Then it should work
make sure you have installed Microsoft Visual C++ installed

**Comment by karliell** [comment]
> your SSL module is not available.
> Download open SSL (Win64 OpenSSL v1.1.1d) here: [Link](https://slproweb.com/products/Win32OpenSSL.html)
> Then it should work
> make sure you have installed Microsoft Visual C++ installed

Hi! Thank you so much! But the problem is 
![image](https://user-images.githubusercontent.com/36145675/73718314-237e6900-46ea-11ea-825e-6af1bcd3f765.png)

After I click the first one. It is 404 Not Found. I'm so sad about this. Are there any other opinions to deal with that?

**Comment by BerndKarlsboeck** [comment]
Click on either one of the two. On the link that says EXE 
![Screenshot_20200204-172905_Chrome](https://user-images.githubusercontent.com/58805655/73764891-ff676a00-4773-11ea-80e7-ebe9319e4478.jpg)

**Comment by karliell** [comment]
> Click on either one of the two. On the link that says EXE
> ![Screenshot_20200204-172905_Chrome](https://user-images.githubusercontent.com/58805655/73764891-ff676a00-4773-11ea-80e7-ebe9319e4478.jpg)

Thank you so so so much! 
May I ask should I set up something after installing it? I just install the software but the still mistake:
![image](https://user-images.githubusercontent.com/36145675/73769736-2bb9c100-4749-11ea-969a-a01820e2c34e.png)

**Comment by BerndKarlsboeck** [comment]
Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.

Also i found a video that explains the openssl thing nicely.

https://youtu.be/TjNq7lFt-t0

**Comment by simoneby** [comment]
Any solutions for this problem for macs? I get the exact same as Karliell

**Comment by karliell** [comment]
> Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> 
> Also i found a video that explains the openssl thing nicely.
> 
> https://youtu.be/TjNq7lFt-t0

Thank you so much for your video! I have visual c++ and the installation is exactly the same as tutorial. 
![image](https://user-images.githubusercontent.com/36145675/74591364-66431980-4fe5-11ea-8d07-cabc0df99d05.png)


The openssl.exe can be opened well. But I still can't use `conda update conda`

The error still looks like this:
![image](https://user-images.githubusercontent.com/36145675/74591381-925e9a80-4fe5-11ea-8341-479b4581e141.png)


Thank you so much for your help!

**Comment by karliell** [comment]
> Any solutions for this problem for macs? I get the exact same as Karliell

Have you figured out this?

**Comment by zhanglithium** [comment]
Do you try to install conda in the Windows 10 Linux subsystem? I try to install ncl in ubuntu and run into the same problem.

**Comment by karliell** [comment]
> Do you try to install conda in the Windows 10 Linux subsystem? I try to install ncl in ubuntu and run into the same problem.

Windows 10. I haven't solved it and give up anaconda. I assume this is an official bug of anaconda. Would you please share here if you solve it? A lot of people are facing this.

**Comment by karliell** [comment]
> Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> 
> Also i found a video that explains the openssl thing nicely.
> 
> https://youtu.be/TjNq7lFt-t0

I haven't solved this problem. So sad...

**Comment by zhanglithium** [comment]
> 
> 
> > Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> > Also i found a video that explains the openssl thing nicely.
> > https://youtu.be/TjNq7lFt-t0
> 
> I haven't solved this problem. So sad...

Umm, actually I am using a miniconda. Before installing miniconda, I had g++ installed and it should contain  the latest c++.
![图片](https://user-images.githubusercontent.com/61615723/75618303-26fcf700-5ba7-11ea-80b1-4885fa5761d9.png)

And when I use `conda update --all`, there are no errors.
![图片](https://user-images.githubusercontent.com/61615723/75618196-c28d6800-5ba5-11ea-8a0d-19fb6dfa37d4.png)

My problem is, when I use `conda create -n ncl_stable -c conda-forge ncl`  and try to create a conda environment, this error occurs:
![图片](https://user-images.githubusercontent.com/61615723/75618376-4ba59e80-5ba8-11ea-8429-b636363c29c8.png)

And I noticed that your Python is 32-bit, which may mean that your computer is also 32-bit, but the conda you downloaded seems to be 64-bit. Perhaps this is the reason why your conda cannot 'conda update --all'?

Good luck!

**Comment by karliell** [comment]
> > > Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> > > Also i found a video that explains the openssl thing nicely.
> > > https://youtu.be/TjNq7lFt-t0
> > 
> > 
> > I haven't solved this problem. So sad...
> 
> Umm, actually I am using a miniconda. Before installing miniconda, I had g++ installed and it should contain the latest c++.
> ![图片](https://user-images.githubusercontent.com/61615723/75618303-26fcf700-5ba7-11ea-80b1-4885fa5761d9.png)
> 
> And when I use `conda update --all`, there are no errors.
> ![图片](https://user-images.githubusercontent.com/61615723/75618196-c28d6800-5ba5-11ea-8a0d-19fb6dfa37d4.png)
> 
> My problem is, when I use `conda create -n ncl_stable -c conda-forge ncl` and try to create a conda environment, this error occurs:
> ![图片](https://user-images.githubusercontent.com/61615723/75618376-4ba59e80-5ba8-11ea-8429-b636363c29c8.png)
> 
> And I noticed that your Python is 32-bit, which may mean that your computer is also 32-bit, but the conda you downloaded seems to be 64-bit. Perhaps this is the reason why your conda cannot 'conda update --all'?
> 
> Good luck!

![image](https://user-images.githubusercontent.com/36145675/75618486-00a27180-5b3d-11ea-9149-c43185a9796e.png)
Python is 64 bit.

**Comment by zhanglithium** [comment]
> 
> 
> > > > Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> > > > Also i found a video that explains the openssl thing nicely.
> > > > https://youtu.be/TjNq7lFt-t0
> > > 
> > > 
> > > I haven't solved this problem. So sad...
> > 
> > 
> > Umm, actually I am using a miniconda. Before installing miniconda, I had g++ installed and it should contain the latest c++.
> > ![图片](https://user-images.githubusercontent.com/61615723/75618303-26fcf700-5ba7-11ea-80b1-4885fa5761d9.png)
> > And when I use `conda update --all`, there are no errors.
> > ![图片](https://user-images.githubusercontent.com/61615723/75618196-c28d6800-5ba5-11ea-8a0d-19fb6dfa37d4.png)
> > My problem is, when I use `conda create -n ncl_stable -c conda-forge ncl` and try to create a conda environment, this error occurs:
> > ![图片](https://user-images.githubusercontent.com/61615723/75618376-4ba59e80-5ba8-11ea-8429-b636363c29c8.png)
> > And I noticed that your Python is 32-bit, which may mean that your computer is also 32-bit, but the conda you downloaded seems to be 64-bit. Perhaps this is the reason why your conda cannot 'conda update --all'?
> > Good luck!
> 
> ![image](https://user-images.githubusercontent.com/36145675/75618486-00a27180-5b3d-11ea-9149-c43185a9796e.png)
> Python is 64 bit.

So...you still can't use `conda update --all` ?

**Comment by karliell** [comment]
> > > > > Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> > > > > Also i found a video that explains the openssl thing nicely.
> > > > > https://youtu.be/TjNq7lFt-t0
> > > > 
> > > > 
> > > > I haven't solved this problem. So sad...
> > > 
> > > 
> > > Umm, actually I am using a miniconda. Before installing miniconda, I had g++ installed and it should contain the latest c++.
> > > ![图片](https://user-images.githubusercontent.com/61615723/75618303-26fcf700-5ba7-11ea-80b1-4885fa5761d9.png)
> > > And when I use `conda update --all`, there are no errors.
> > > ![图片](https://user-images.githubusercontent.com/61615723/75618196-c28d6800-5ba5-11ea-8a0d-19fb6dfa37d4.png)
> > > My problem is, when I use `conda create -n ncl_stable -c conda-forge ncl` and try to create a conda environment, this error occurs:
> > > ![图片](https://user-images.githubusercontent.com/61615723/75618376-4ba59e80-5ba8-11ea-8429-b636363c29c8.png)
> > > And I noticed that your Python is 32-bit, which may mean that your computer is also 32-bit, but the conda you downloaded seems to be 64-bit. Perhaps this is the reason why your conda cannot 'conda update --all'?
> > > Good luck!
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/36145675/75618486-00a27180-5b3d-11ea-9149-c43185a9796e.png)
> > Python is 64 bit.
> 
> So...you still can't use `conda update --all` ?

No

**Comment by 12avnisharma** [comment]
@karliell Have you figured the issue??

**Comment by karliell** [comment]
> @karliell Have you figured the issue??

No

**Comment by forrestwaters** [comment]
Please see https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors

**Comment by karliell** [comment]
Thank you all guys! I have solved this! If someone has trouble with this, you can also try to reinstall anaconda.

**Comment by silverkorn** [comment]
It's not an SSL issue, https://conda.anaconda.org/pytorch/win-64/current_repodata.json does not exists (anymore?).
How can we replace with the new URL https://conda.anaconda.org/pytorch/win-64/repodata.json ?

**Comment by silverkorn** [comment]
Nevermind, this (https://github.com/conda/conda/issues/8273) worked for me, although the error printed was strictly about `current_repodata.json` not found

**Comment by cynliu98** [comment]
Hello, I'm having the same error "Collecting package metadata (current_repodata.json): failed" but with different details. Instead of being a connection error, I'm getting the error `json.decoder.JSONDecodeError: Unterminated string starting at: line 95455 column 5 (char 3016469)` while handling a `raise Response304ContentUnchanged()` error.

My conda info is as follows:

```
active environment : None
       user config file : /afs/csail.mit.edu/u/c/cynliu98/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.27
       base environment : /afs/<path>/cynliu98/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /afs/<path>/cynliu98/anaconda3/pkgs
                          /afs/<path>/cynliu98/.conda/pkgs
       envs directories : /afs/<path>/cynliu98/anaconda3/envs
                          /afs/<path>/cynliu98/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Linux/4.15.0-118-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 24791:24791
             netrc file : None
```

Is the fix similar? Thank you

**Comment by BryanBYChoi100** [comment]
um... what about this? just do without ssl verification


conda config --set ssl_verify False

**Comment by AldanaCepeda** [comment]
> Do you have the latest microsoft visual c++ installed? Make sure you have it. Just google for it. The install is super easy.
> 
> Also i found a video that explains the openssl thing nicely.
> 
> https://youtu.be/TjNq7lFt-t0



> your SSL module is not available.
> Download open SSL (Win64 OpenSSL v1.1.1d) here: [Link](https://slproweb.com/products/Win32OpenSSL.html)
> Then it should work
> make sure you have installed Microsoft Visual C++ installed

Thank you so much, you really help me! Best wishes

**Comment by TheBloodthirster** [comment]
> your SSL module is not available.
> Download open SSL (Win64 OpenSSL v1.1.1d) here: [Link](https://slproweb.com/products/Win32OpenSSL.html)
> Then it should work
> make sure you have installed Microsoft Visual C++ installed

Save my life !!! Thank you !!!

**Comment by WilmerSanchezLeon** [comment]
> Hi! I download python 3.7.6
> 
> ```
> Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> ```
> 
> and anaconda `conda 4.7.12`
> 
> But when I try to use `conda update conda`, `conda install jupyter notebook`, `conda update --all`, `conda create -n test python=3.7` All the commands above have the same error. This error happens:
> 
> ```
> Collecting package metadata (current_repodata.json): failed
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com blocked, please file
> a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
> ```
> 
> ![image](https://user-images.githubusercontent.com/36145675/71644860-48bc2980-2c9d-11ea-9f02-a248f9d3f565.png)
> 
> Would you please help me with this? Thank you so much for your help!!!!!
> 
> ```
> 
> > conda info
> 
>      active environment : None
>        user config file : C:\Users\Administrator\.condarc
>  populated config files : C:\Users\Administrator\.condarc
>           conda version : 4.7.12
>     conda-build version : 3.18.9
>          python version : 3.7.4.final.0
>        virtual packages :
>        base environment : C:\ProgramData\Anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\ProgramData\Anaconda3\pkgs
>                           C:\Users\Administrator\.conda\pkgs
>                           C:\Users\Administrator\AppData\Local\conda\conda\pkgs
>        envs directories : C:\ProgramData\Anaconda3\envs
>                           C:\Users\Administrator\.conda\envs
>                           C:\Users\Administrator\AppData\Local\conda\conda\envs
>                platform : win-64
>              user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17763
>           administrator : True
>              netrc file : None
>            offline mode : False
> ```

Hello. this work for me:

To Solve Caused by SSLError(“Can't connect to HTTPS URL because the SSL module is not available.”) Error If you are using anaconda then Then add this to PATH variable <path>\Anaconda3 <path>\Anaconda3\scripts <path>\Anaconda3\Library\bin 

Second Solution is Just copy this file libcrypto-1_1-x64.* libssl-1_1-x64.* which will be located at C:\Anaconda3\Library\bin and paste these file to this location. C:\Anaconda3\DLLs.

Regards

**Comment by guidao20** [comment]
> Click on either one of the two. On the link that says EXE ![Screenshot_20200204-172905_Chrome](https://user-images.githubusercontent.com/58805655/73764891-ff676a00-4773-11ea-80e7-ebe9319e4478.jpg)

Thank you.
