### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by Entretoize** [conda/conda#9555]
####  Current Behavior
When I try to create an environnement, update, install anything with `conda ...` I have that error :
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
```

## Environment Information
I'm under Window 10, it worked a week ago, but I accidently deleted the miniconda folder.
I tried with tha latest miniconda and anaconda, I uninstalled deleting all conda folders in user folder I found, I checked that there's no proxy, I added Anaconda and Scripts folder to path, reinstalled open ssl, install the openssl package by downloading it and installing with --offline conda option, disabled ssl check, nothing works !
I also disabled my firewall of course.

**Comment by Entretoize** [comment]
I also disabled my forewall of course.

**Comment by rhkmining09101970** [comment]
Solution:
1. Open Anaconda Navigator
2. Click 'Environment'
3. Click the Green Play Button marked as 'base (root)'
4. Click 'Open Terminal'
5. The prompt looks '(base) c:'Users\Owner>'
6. To check if it is coda prompt type 'coda --v' press enter

**Comment by Entretoize** [comment]
Anaconda Navigator won't start.
If I enter 'conda --v' on a command prompt I get 'conda 4.7.12'

**Comment by StevenDaveySBSA** [comment]
Same problem. Tried a fresh install of Anaconda3-2019.10-Windows-x86_64.exe for Windows 10. I cannot launch Anaconda Navigator or Spyder (both try to start but nothing happens - retrying Spyder gives a notification that Spyder crashed during last session). If I run the Anaconda Prompt and attempt to run "conda update pkg", I receive an error that ends in:
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Things I have tried - to no effect include
1) Uninstalling and re-installing Anaconda 
2) updating openssl following the instructions here https://www.cloudinsidr.com/content/how-to-install-the-most-recent-version-of-openssl-on-windows-10-in-64-bit/
3) conda config --set ssl_verify no

pip gives the same ssl error when running from the Anaconda prompt and the traditional cmd prompt. I am on my home pc so I do not have any corporate firewall issues

**Comment by ageneslaw** [comment]
I'm having the exact same problem. I've tried each of the steps above to no avail. My installation of Anaconda was working without any issues as of about a month ago when I last used it. After I booted t up yesterday and installed updates it's been completely broken.

**Comment by Entretoize** [comment]
Good luck, I finaly reinstalled windows to make it work, as no solution
seems to exist !

Le mar. 21 janv. 2020 à 17:04, ageneslaw <notifications@github.com> a
écrit :

**Comment by ageneslaw** [comment]
I got this working by following instructions on a post from Stackoverflow:

https://github.com/ContinuumIO/anaconda-issues/issues/10576

Copy files libcrypto-1_1-x64.dll and libssl-1_1-x64.dll from the directory ./Anaconda3/Library/bin/ to ./Anaconda3/DLLs.

No idea why that worked, but it completely fixed the problem for me.

**Comment by StevenDaveySBSA** [comment]
Thanks, ageneslaw, This (Copy files libcrypto-1_1-x64.dll and libssl-1_1-x64.dll from the directory ./Anaconda3/Library/bin/ to ./Anaconda3/DLLs.) solved my problem

**Comment by ChuliangXiao** [comment]
Thanks @ageneslaw . It worked for me.
```
>conda -V
conda 4.7.12
```

**Comment by kevsieb** [comment]
If it can be of any help: like the author @Entretoize, I tried all solutions found on the internet so far for Win10-64 platform, which includes (if it can be of any help ...):
- copying files libcrypto-1_1-x64.dll and libssl-1_1-x64.dll from the directory ./Anaconda3/Library/bin/ to ./Anaconda3/DLLs.
- conda config --set ssl_verify no
- made a clean uninstall/install of Anaconda using most recent Anaconda version
- disabling firewall+antivirus (ESET in my case)
- added Anaconda3, Anaconda/Scripts and Anaconda3/Library to my environment paths
- I didn't tried the proxy configuration option since I am working from home
- any combination of the solutions above.

Like the author, I was about to fully format my windows but completely uninstall my antivirus instead, in a last desperate attempt. And it worked.

Hope it will be of some help.

**Comment by rhkmining09101970** [comment]
Hello and good day. Thank you for your solution. I would like some
suggestion from you for followings:
1. I need to design an AI based on previous data and teach that AI
2. Then I will connect the AI with the market which will be able to show
atleast 72 hours forecast of the market
3. The AI will be able to buy and sell stock of it is own in live market
4. And from the trading it will also learn and evolve itself with the
mistakes it will make during the buy and sell it will conduct.

I am familiar with:
Pycharm
Python limited way
highly familiar with MetaTrader 4 the Platform which the AI will will get
connected to place orders to the broker.

I will highly appreciate if you are kind enough to give me a guideline for
the above.

With regards
Rassel
##
Cell: +8801732944133
From Dhaka, Bangladesh

**Comment by uttamkumar41** [comment]
> #### Current Behavior
> When I try to create an environnement, update, install anything with `conda ...` I have that error :
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com blocked, please file
> a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
> ```
> 
> ## Environment Information
> I'm under Window 10, it worked a week ago, but I accidently deleted the miniconda folder.
> I tried with tha latest miniconda and anaconda, I uninstalled deleting all conda folders in user folder I found, I checked that there's no proxy, I added Anaconda and Scripts folder to path, reinstalled open ssl, install the openssl package by downloading it and installing with --offline conda option, disabled ssl check, nothing works !
> I also disabled my firewall of course.

Try this as it worked for me
copy these two dll files from C:\Anaconda3\Library\bin into C:\Anaconda3\DLLs.
libcrypto-1_1-x64.*
libssl-1_1-x64.*

**Comment by alovictor** [comment]
> I got this working by following instructions on a post from Stackoverflow:
> 
> [ContinuumIO/anaconda-issues#10576](https://github.com/ContinuumIO/anaconda-issues/issues/10576)
> 
> Copy files libcrypto-1_1-x64.dll and libssl-1_1-x64.dll from the directory ./Anaconda3/Library/bin/ to ./Anaconda3/DLLs.
> 
> No idea why that worked, but it completely fixed the problem for me.

thanks @ageneslaw !! worked for me

**Comment by 1R053** [comment]
alternatively to copying the DLLs you can add ```C:\ProgramData\Anaconda3\Library\bin``` to your PATH variable

**Comment by anner-paldor** [comment]
If anyone by any chance has another idea I'd be very happy for some help - I'm desperate. I've tried the above (copying the *.dll files from bin to DLLs, adding the subfolders to the PATH variables, clean reinstallation of both Anaconda and Miniconda). Nothing, no matter what I do I get the same error:
`Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://localhost:3141/root/pypi/ simple/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'http://localhost:3141/root/pypi/ simple/win-64'`
The weird thing is that I don't get any error relating it to the SSL server or anything like that. Plus, when I run 
`conda --version`
I get the expected:
`conda 4.8.3`
So I'm not sure this is actually related to a server failure or something. It seems that something in the environment is corrupted.
I'm not a professional in any means (using Python for scientific purposes), so I apologize in advance if any of the things above don't make sense.

Any help would be greatly appreciated!

**Comment by anner-paldor** [comment]
If anyone by any chance has another idea I'd be very happy for some help - I'm desperate. I've tried the above (copying the *.dll files from bin to DLLs, adding the subfolders to the PATH variables, clean reinstallation of both Anaconda and Miniconda). Nothing, no matter what I do I get the same error:

```
Collecting package metadata (current_repodata.json): failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://localhost:3141/root/pypi/ simple/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'http://localhost:3141/root/pypi/ simple/win-64'
```

The weird thing is that I don't get any error relating to the SSL server or anything like that. Plus, when I run 
`conda --version`
I get the expected:
`conda 4.8.3`
So I'm not sure this is actually related to a server failure or something. It seems that something in the environment is corrupted.
I'm not a professional in any means (using Python for scientific purposes), so I apologize in advance if any of the things above don't make sense.

Any help would be greatly appreciated!

**Comment by anner-paldor** [comment]
Also, if it helps narrowing the options, I've successfully installed Jupyter and Notebook packages with pip using the command prompt after installing it with Conda in the Anaconda prompt did not work. When I tried running it from the command prompt I got the following message:
`ModuleNotFoundError: No module named 'pysqlite2'`

**Comment by arizhakov** [comment]
@anner-paldor , try @uttamkumar41 's advice (https://github.com/conda/conda/issues/9555#issuecomment-631104450) again. Specifically, get both .dll and .pdb files, not just .dll's. That worked for me.

**Comment by Abb1989** [comment]
Dear all, after doing all offered ways to solve this current problem, I just found that _rep.anaconda.com_ has been blocked by some countries, so you should set a proxy to pass the filtering.

**Comment by anner-paldor** [comment]
> @anner-paldor , try @uttamkumar41 's advice ([#9555 (comment)](https://github.com/conda/conda/issues/9555#issuecomment-631104450)) again. Specifically, get both .dll and .pdb files, not just .dll's. That worked for me.

Thanks, I'm pretty sure I've got all 4 in the DLLs folder so that's probably not the problem. 
![all_4_in_DLLs](https://user-images.githubusercontent.com/62143834/87878655-aa32b400-c9b3-11ea-99c3-07ba5a93cc6a.PNG)

**Comment by anner-paldor** [comment]
> Dear all, after doing all offered ways to solve this current problem, I just found that _**rep.anaconda.com**_ has been blocked by some countries, so you should set a proxy or VPN to pass the filtering.

Thank you for the suggestions, but I am not sure that's the problem. I am able to install things from anaconda using pip. Also, I am in the US so I believe if the anaconda site was blocked here it would've been much wider then me (and maybe a couple of other folks).
Thanks again.

**Comment by anner-paldor** [comment]
UPDATE:
I was able to install everything on a different ("clean") computer in my house, so apparently the problem is not related to blockage of websites in my country or something like that. Also made sure again that all 4 .dll and .pdb files are in the DLLs folder.
Anyone??? Is this how my Python adventure ends..?

**Comment by holychowders** [comment]
@1R053's suggestion **worked for me**, the only difference being that my base was miniconda3, not Anaconda3.

> alternatively to copying the DLLs you can add C:\ProgramData\Anaconda3\Library\bin to your PATH variable

Thanks.

**Additional details**:
What I was trying to do was `conda install -c conda-forge notebook`
My particular error was `CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>`

**Comment by anner-paldor** [comment]
Thanks. It wasn't the problem in my case, though. Apparently, I was somehow referring to a local channel in my computer instead of referring to the conda website. @angloyna's [comment](https://github.com/conda/conda/issues/10067#issuecomment-662659846) in the other issue helped me figure it out, though I still have no idea what started this.

**Comment by chengjon** [comment]
> Solution:
> 
> 1. Open Anaconda Navigator
> 2. Click 'Environment'
> 3. Click the Green Play Button marked as 'base (root)'
> 4. Click 'Open Terminal'
> 5. The prompt looks '(base) c:'Users\Owner>'
> 6. To check if it is coda prompt type 'coda --v' press enter

'coda --v' or conda --v ?  it's the look conda version command, no help

**Comment by RAHULPRRAHUL** [comment]
I think it is occurring due to the "future=0.18.2" library support. This issue was solved by installing the latest version of anaconda "Anaconda3-2020.07-Linux-x86_64.sh" and then I have updated the conda, and install a new environment via the following commands:
conda update conda
conda create --name py35 python=3.5 anaconda

**Comment by Bo-Cang** [comment]
find ".condarc" file in the Administrator folder, open it with .txt file, copy the following code and try
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/

show_channel_urls: true

**Comment by madhavacv** [comment]
> Solution:
> 
> 1. Open Anaconda Navigator
> 2. Click 'Environment'
> 3. Click the Green Play Button marked as 'base (root)'
> 4. Click 'Open Terminal'
> 5. The prompt looks '(base) c:'Users\Owner>'
> 6. To check if it is coda prompt type 'coda --v' press enter

YES THIS SORTED THE ISSUE

**Comment by mmhj** [comment]
Thank you to all the contributors.

I had this issue as well, on Windows 10 Pro - Version 20H2.

Copying all four files solved my issue, however I copied them directly from the 'openssl' package folder.

You can find libcrypto-1_1-x64.dll, libcrypto-1_1-x64.pdb and libssl-1_1-x64.dll , libssl-1_1-x64.pdb in the lib other people in this thread mentioned '~\anaconda3\Library\bin', thank you to @arizhakov  for pointing out that all four are needed.

I navigated to the '~\anaconda3\pkgs\openssl-1.1.1h-he774522_0\Library\bin' folder and copied the four files from there into '~\anaconda3\DLLs', problem solved.

**Comment by fedegui-20** [comment]
I had the same issue of @anner-paldor. 
The error was 
```
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json> Elapsed: -

An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/win-64'
```

I did all these steps: 
- copying the libcrypto-1_1-x64.* libssl-1_1-x64.* files from D:\Anaconda3\Library\bin to D:\Anaconda3\DLLs;
- adding to View Advanced System Settings and then to select Environmental Variables (both for user and for system variable): C:\your_directory_to_anaconda3\Anaconda3\Scripts C:\your_directory_to_anaconda3\Anaconda3\ C:\your_directory_to_anaconda3\Anaconda3\Library\bin
- downloading OpenSSL 1.1.1 h and adding the bin folder in Environmental Variables as said before

But at the end my problem wasn't solved. 
In addiction, writing anything on Anaconda prompt was impossible, as always this error came up.

Then I uninstalled and reinstalled Anaconda in another folder. Finally Anaconda, conda and Jupiter start to work as expected. I hope this can help.

**Comment by joshmerry** [comment]
Copying the files from Library into DLLs worked for me too.  I don't like not understanding why something worked thouhg.

**Comment by charlesmwashashu** [comment]
> I got this working by following instructions on a post from Stackoverflow:
> 
> [ContinuumIO/anaconda-issues#10576](https://github.com/ContinuumIO/anaconda-issues/issues/10576)
> 
> Copy files libcrypto-1_1-x64.dll and libssl-1_1-x64.dll from the directory ./Anaconda3/Library/bin/ to ./Anaconda3/DLLs.
> 
> No idea why that worked, but it completely fixed the problem for me.

Thank you, it has worked for me too!

**Comment by pingpgao** [comment]
> Same problem. Tried a fresh install of Anaconda3-2019.10-Windows-x86_64.exe for Windows 10. I cannot launch Anaconda Navigator or Spyder (both try to start but nothing happens - retrying Spyder gives a notification that Spyder crashed during last session). If I run the Anaconda Prompt and attempt to run "conda update pkg", I receive an error that ends in:
> SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))'))
> 
> Things I have tried - to no effect include
> 
> 1. Uninstalling and re-installing Anaconda
> 2. updating openssl following the instructions here https://www.cloudinsidr.com/content/how-to-install-the-most-recent-version-of-openssl-on-windows-10-in-64-bit/
> 3. conda config --set ssl_verify no
> 
> pip gives the same ssl error when running from the Anaconda prompt and the traditional cmd prompt. I am on my home pc so I do not have any corporate firewall issues

windows update maybe need openssl update accordingly,

**Comment by haribanshagrawal** [comment]
i would rather suggest to use Ananconda Prompt. i did the Same it is working. while the same issue i am facing while using default command Prompt

**Comment by Arkaprabha1012** [comment]
As this issue has been open till now, I am just adding an answer for windows os; run your anaconda prompt as administrator. Your query will be resolved

**Comment by SVNKoch** [comment]
For me none of these worked. What hlped me was setting the proxy URL of my company, see https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/
