### ISSUE TITLE
Solver messaging to only show conflicts instead of all deps for a conflicting package

### ISSUE THREAD

**Issue by soapy1** [conda/conda#9570]
Currently if the solver hits an unsatisfiable problem it will determine the package that is unsatisfiable and the chain of packages that is associated with that package for all requested specs. This means that is sometimes also will display deps that are compatible in addition to those which are not compatible. Ideally, the solver should only show those deps which are causing issues, that is the ones that are not compatible. 

ref: https://github.com/conda/conda/pull/9560#issuecomment-572171199

**Comment by MTelling** [comment]
I think this is a dupe of https://github.com/conda/conda/issues/10247 - but very happy someone is looking into this!

**Comment by nugend** [comment]
@MTelling This was merged last year and is in place. It doesn't actually make the display more sensible.
