### ISSUE TITLE
Pip/conda best practices?

### ISSUE THREAD

**Issue by collinmccarthy** [conda/conda#9584]
Is it possible to add some documentation to the conda docs describing best practices when the user has to switch between pip and conda environments? I found documentation [here](https://www.anaconda.com/using-pip-in-a-conda-environment/) from Anaconda, but I'm not sure if it's out of date (it was written ~13 months ago).

If I'm understanding that article correctly, it said that if switching between conda and pip due to a package not being available on a conda channel, it is recommended to re-create the environment using the yaml file to ensure the pip packages are always installed last. Specifically, I'm understanding this as: 

```
# Backup environment (that already has packages installed via conda and pip)
conda create --name my_env_backup --clone my_env

# Install new conda packages
conda install <NEW_PACKAGES>

# Re-create environment using yml file
conda env export > my_env.yml
conda remove --name my_env --all
conda create --name my_env --file my_env.yml
```

Is this the right way to do this, and is it really necessary still? Thank you!

**Comment by mingwandroid** [comment]
The blog post you linked to is still relevant.
