### ISSUE TITLE
Windows: Local miniconda PATH var comes after global PATH var

### ISSUE THREAD

**Issue by srossross** [conda/conda#959]
On Windows My local miniconda `C:\Users\user\Miniconda` install comes after the global install `C:\Miniconda` and my local install is not used.

**Comment by wulmer** [comment]
Can you please check at which position the two paths appear in your user's PATH environment variable and the system's PATH variable?

**Comment by msarahan** [comment]
There are two PATH variables: one for system, another for the user. They are evaluated by the OS in a particular order: http://stackoverflow.com/a/16305526/1170370 .  The user install of miniconda only modifies the user variable, so it will always be found after any system install.

Closing this issue. Reopen if needed.
