### ISSUE TITLE
Funannotate Conda installation problem

### ISSUE THREAD

**Issue by emmannaemeka** [conda/conda#9593]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jjhelmus** [comment]
Issue is empty, please re-open with requested information.
