### ISSUE TITLE
'Fast Switcher' for Anaconda environments

### ISSUE THREAD

**Issue by Maggie-M** [conda/conda#96]
Mark Wiebe: "A follow on to the feature request for a conda command to set the environment, is to create a 'fast switcher' application that lives in the windows system tray.

The user would click on the Anaconda icon, and it would list all the available environments in a popup menu (with a checkbox showing the current one). Selecting another environment would set the default environment to that one instead.

This feature would let users rapidly switch between different anaconda environments, and launch ipython/spyder environments for these environments with ease."

**Comment by goanpeca** [comment]
Closing this as this is a very old issue, and probably Navigator is already helping users to accomplish this.
