### ISSUE TITLE
Improve unsatisfiable hints poor performance on larger number of specs

### ISSUE THREAD

**Issue by jeremyjliu** [conda/conda#9608]
I've seen cases where an unsatisfiable `install` or `create` takes a long time (>5min) to return the hints of unsatisfiable dependencies. In investigating these, I've found that the bulk of the time is spent in the computation of the unsatisfiable hints after both the pruning and sat solver have found that the desired end state is unsatisfiable. The cause seem to be tied to a large environment and/or exploding explicit specs.

Are there concrete ways to improve the performance of the unsatisfiable hints? In general, turning them off leads to a faster conflict, but the error message is typically not actionable.

Some immediate thoughts:
- limit computation of unsatisfiable hints by number of specs (say, 25 or 50)?
- improve error message when unsatisfiable hints is turned off

**Comment by soapy1** [comment]
Have you been able to play around with conda 4.8.2? There was some changes to how unsat hints are generated. You should be able to set `unsatisfiable_hints_check_depth` to indicate how deep to check dependency issues. Setting it to 1 will make the check the quickest but perhaps not super accurate. Setting it to a higher number will make is slower as it checks for unsat conditions including packages deeper in the  graph of dependencies

**Comment by jeremyjliu** [comment]
I have not yet, wasn't aware of this new feature. I will check it out!

**Comment by jeremyjliu** [comment]
Result: the depth limit helps a good amount, with depth limit 2 an example that used to run for hours finishes in around 15 minutes.
