### ISSUE TITLE
Conda Activate Changes System Path

### ISSUE THREAD

**Issue by lufol** [conda/conda#9612]
Conda is changing the $PATH on my CentOS machine.

 1. python import sys; sys.path -> OK
 2. conda activate my_env; python import sys; sys.path -> local directory added

How can I avoid or find the location where my local directory is added to the $PATH?

**Comment by forrestwaters** [comment]
This is the default behavior of python https://docs.python.org/3/library/sys.html#sys.path

**Comment by lufol** [comment]
It's not `sys.path[0]' but rather 'sys.path[-1]' thats changed. Actually a local path is appended to the list of `sys.path`.

**Comment by lufol** [comment]
Found the problem.
Apparently I had a file called easy-install.pth and the content of it was the path to the local directory.
So whenever I called `conda activate my_env` this path got appended to my sytem path.
Found the file using `find / -name *.pth` in case someone get's the same problem.
