### ISSUE TITLE
conda install should persist in environment.yml

### ISSUE THREAD

**Issue by technic** [conda/conda#9630]
Hi,
What I'd like to request is a feature similar to `npm` or `pipenv`.
When I call `conda install` it installs the package, but does not touch the `environment.yml` file.
This is annoying, because I need to install the package and then not forget to add it manually to the file.  Many other package managers maintain two files:
- general dependencies, such as `packages.json`
- specific versions of dependencies for reproducible builds, such as `package-lock.json`

I suggest to have two files  `environment.yml` and  `environment-lock.yml`, analogous to npm. The later file is what we get from `conda env export`, while in the first file we add non pinned dependencies. Then `conda install` command should automatically search for `environment.yml` in the parent folders and update it if it matches with the name of the current environment.

**Comment by jamesmyatt** [comment]
This is in anaconda-project (https://anaconda-project.readthedocs.io/en/latest/user-guide/reference.html#locking-package-versions) but anaconda-project also does a lot of other stuff! It would be good to get it into base conda too.

**Comment by technic** [comment]
@jamesmyatt That is cool, thanks! Now I wonder what is the relation between conda and anaconda-prohect. Is the latter one is an extension to conda which is recommended to use? Shall I close this issue then?

**Comment by technic** [comment]
I have rolled out my own reinvented wheel for this purpose
https://github.com/technic/cenv_script
It is very simple, but helps to reduce annoying routines in simple case scenario.

**Comment by technic** [comment]
Reopen
