### ISSUE TITLE
Running native CPython program in conda environment requires PYTHONHOME/PYTHONPATH

### ISSUE THREAD

**Issue by LeslieGerman** [conda/conda#9648]
## Current Behavior
I could compile and link my CPython native program in a conda environment, with the Python version I installed in the environment.
However when I try to run it I get Fatal Python error:
```
(palinca_dev_test) D:\Projects\Palinca\palinca_conda\CMakeBuilds\CondaTestBuild>D:\Projects\Palinca\palinca_conda\CMakeBuilds\CondaTestBuild\core\test\palinca_core_test_runner.exe

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'D:\\Projects\\Palinca\\palinca_conda\\CMakeBuilds\\CondaTestBuild\\core\\test\\palinca_core_test_runner.exe'
  sys.base_prefix = 'D:\\Programs\\Miniconda3\\envs\\palinca_dev_test'
  sys.base_exec_prefix = 'D:\\Programs\\Miniconda3\\envs\\palinca_dev_test'
  sys.executable = 'D:\\Projects\\Palinca\\palinca_conda\\CMakeBuilds\\CondaTestBuild\\core\\test\\palinca_core_test_runner.exe'
  sys.prefix = 'D:\\Programs\\Miniconda3\\envs\\palinca_dev_test'
  sys.exec_prefix = 'D:\\Programs\\Miniconda3\\envs\\palinca_dev_test'
  sys.path = [
    'D:\\Programs\\Miniconda3\\envs\\palinca_dev_test\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'D:\\Projects\\Palinca\\palinca_conda\\CMakeBuilds\\CondaTestBuild\\core\\test',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000940 (most recent call first):
<no Python frame>
```

But when I set `PYTHONHOME` to my environment directory, i.e. to `CONDA_PREFIX`, my program can run:
`set PYTHONHOME=%CONDA_PREFIX%`

But, of course, then conda cannot work anymore:
```
>conda list
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "D:\Programs\Miniconda3\envs\palinca_dev_test\lib\io.py", line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)
```

Exactly the same happens if I try with `set PYTHONPATH=%CONDA_PREFIX%\Lib` ...
## Expected Behavior
I can run CPython native program, which was linked against the Python in the current conda environment, **without setting** PYTHONHOME (or PYTHONPATH) before, and un-setting it after the execution of program.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : palinca_dev_test
    active env location : D:\Programs\Miniconda3\envs\palinca_dev_test
            shell level : 1
       user config file : C:\Users\good_user\.condarc
 populated config files : C:\Users\good_user\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : D:\Programs\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Programs\Miniconda3\pkgs
                          C:\Users\good_user\.conda\pkgs
                          C:\Users\good_user\AppData\Local\conda\conda\pkgs
       envs directories : D:\Programs\Miniconda3\envs
                          C:\Users\good_user\.conda\envs
                          C:\Users\good_user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\good_user\.condarc <==
ssl_verify: False
channel_priority: disabled
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at D:\Programs\Miniconda3\envs\palinca_dev_test:
#
# Name                    Version                   Build  Channel
boost                     1.70.0                        0    conda-forge
ca-certificates           2020.1.1                      0    defaults
certifi                   2019.11.28               py38_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pip                       20.0.2                   py38_1    conda-forge
pybind11                  2.4.2            py38h74a9793_0    defaults
python                    3.8.1                he1f5543_2    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
wheel                     0.34.1                   py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
```
</p></details>

**Comment by mingwandroid** [comment]
Unfortunately your expectations do not meet with the reality of how the python interpreter (or an executable that subsumes it) located itself and its libraries.

You need to move your executable to the same folder that python.exe is in, basically.

This has nothing to do with Anaconda's python builds, it's just how python works.

**Comment by mingwandroid** [comment]
.. and PYTHONHOME/PYTHONPATH are exactly the get outs for people who would rather not move executables like this.

That the value you need to set it to (or that you need to set it at all) interferes with conda means you need to set it in a more targeted way, i.e. not while running conda.

**Comment by LeslieGerman** [comment]
Thanks @mingwandroid for your comments!
I think you are right, and I need find some solution to not set it in the environment.
Now I'm trying to set it from code using the [Py_SetPythonHome()](https://docs.python.org/3.6/c-api/init.html#c.Py_SetPythonHome) CPython function...

BTW, 2 years ago for some other reason I debugged inside CPython and tracked why PYTHONHOME/PYTHONPATH was needed, and AFAI remember they are really hard-coded in the source...

**Comment by LeslieGerman** [comment]
The problem with the Py_SetPythonHome() based approach is that the *build-time* PYTHONHOME path is then hard-coded into the executable, and when I deploy the application into an environment, where Python is located somewhere else, i.e. the *run-time* PYTHONHOME is different
=>
bang, python packages are still not found!

Any idea @mingwandroid , about this issue, please?

**Comment by mingwandroid** [comment]
You need to put your executable in the same location that the Python executable is located because that's the expectations that the code makes.

This is how upstream Python works though. It has nothing to do with Anaconda. If you don't like this please raise it with upstream.

**Comment by mingwandroid** [comment]
You can use things such as `GetModulePathNameEx()` to form an input to `Py_SetPythonHome()` too.

**Comment by LeslieGerman** [comment]
I found two solutions:

1.
Create a file called `python36._pth` (adapt version number of course) at the root dir of your environment with this content:
```
D:/Programs/Miniconda3/envs/my_env
D:/Programs/Miniconda3/envs/my_env/Lib
D:/Programs/Miniconda3/envs/my_env/Lib/site-packages
D:/Programs/Miniconda3/envs/my_env/DLLs
```
(Where `D:/Programs/Miniconda3/envs/my_env` is your conda environment root dir.)

Then setting `PYTHONHOME` on Windows is not necessary anymore.
Strange, but works.

2.
From code:

Before initializing Python (e.g. before calling `Py_Initialize()` or instantiating a `pybind11::scoped_interpreter`):

- detect the currently loaded pythonXX.dll run-time, e.g. by using `boost::dll::shared_library`
- store its folder in a `static std::wstring` (as required by [`Py_SetPythonHome()`](https://docs.python.org/3.6/c-api/init.html#c.Py_SetPythonHome)
- set this as Python home directory by `Py_SetPythonHome()`

Of course, this pre-configuration is needed ONLY on Windows, on Linux this would confuse python and wouldn't work...

From my side approach 2 solved the issue, so I close this ticket.
Thanks for your comments @mingwandroid , anyway! 😃
