### ISSUE TITLE
When is TensorFlow 2.1.0 coming?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda/conda#9650]
It'll soon be a month since its release, but conda's still at [2.0.0](https://anaconda.org/anaconda/tensorflow); when is 2.1.0 coming?

**Comment by forrestwaters** [comment]
From the issue template:
>If your issue is a feature request for:
>  * a specific conda package from Anaconda ('defaults' channel):
>      ==> file at https://github.com/ContinuumIO/anaconda-issues
