### ISSUE TITLE
GDAL DRIVER PATH

### ISSUE THREAD

**Issue by ShraddhaPM** [conda/conda#9651]
Please help me to resolve this.
Whenever I open Anaconda Prompt the following new line is appearing from last week only, earlier it was not their.

The system cannot find the specified path.
C:\Users\Username>set "GDAL_DRIVER_PATH="
C:\Users\Username> 
![kaggle](https://user-images.githubusercontent.com/54763343/73587233-7df7a980-44df-11ea-8df2-f0210ee4812b.JPG)

**Comment by kalefranz** [comment]
Probably will go away if you uninstall gdal, and that means this is a packaging issue.

**Comment by busenmir** [comment]
Merhaba bu sorunu çözebildiniz mi aynı sorun benimde başıma geldi ve düzeltemiyorum. yardımcı olabilir misiniz ?
