### ISSUE TITLE
Conda 4.8.2 Proxy None urllib3 error

### ISSUE THREAD

**Issue by ngodber** [conda/conda#9662]
## Current Behavior

Conda install fails with following error:

C:\WINDOWS\system32>conda install verde
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\concurrent\futures\_base.py", line 428, in result
        return self.__get_result()
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\core\subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

### Steps to Reproduce
> Install miniconda on current windows 10 machine (latest download from website)
> Open conda prompt.
> Conda update --all
update will fail after pulling packages. 
reproduce above output via conda install package

## Expected Behavior
conda updates all packages are remains functiona.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\godbn9\AppData\Local\Continuum\miniconda3\condabin\..\Scripts
                          \conda.exe
               CONDA_EXES="C:\Users\godbn9\AppData\Local\Continuum\miniconda3\condabin\..\Script
                          s\conda.exe"
             CONDA_PREFIX=C:\Users\godbn9\AppData\Local\Continuum\miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\godbn9\AppData\Local\Continuum\miniconda3\python.exe
               CONDA_ROOT=C:\Users\godbn9\AppData\Local\Continuum\miniconda3
              CONDA_SHLVL=1
      FLEXID_LIBRARY_PATH=C:\WINDOWS\system32
                 HOMEPATH=\Users\godbn9
                  IWBPATH=C:\Program Files (x86)\SAP\FrontEnd\iwb
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\intel64_win_mic
                     PATH=C:\Users\godbn9\AppData\Local\Continuum\miniconda3;C:\Users\godbn9\App
                          Data\Local\Continuum\miniconda3\Library\mingw-w64\bin;C:\Users\godbn9\
                          AppData\Local\Continuum\miniconda3\Library\usr\bin;C:\Users\godbn9\App
                          Data\Local\Continuum\miniconda3\Library\bin;C:\Users\godbn9\AppData\Lo
                          cal\Continuum\miniconda3\Scripts;C:\Users\godbn9\AppData\Local\Continu
                          um\miniconda3\bin;C:\Users\godbn9\AppData\Local\Continuum\miniconda3;C
                          :\Users\godbn9\AppData\Local\Continuum\miniconda3\Library\mingw-w64\bi
                          n;C:\Users\godbn9\AppData\Local\Continuum\miniconda3\Library\usr\bin;C
                          :\Users\godbn9\AppData\Local\Continuum\miniconda3\Library\bin;C:\Users
                          \godbn9\AppData\Local\Continuum\miniconda3\Scripts;C:\Users\godbn9\App
                          Data\Local\Continuum\miniconda3\bin;C:\Users\godbn9\AppData\Local\Cont
                          inuum\miniconda3\condabin;C:\Oracle\product\12.1.0\client_1\bin;C:\Ora
                          cle\product\12.1.0\client_2\bin;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files
                          (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;
                          C:\Oracle\product\11.2.0\Client_32bit\bin;C:\Oracle\product\11.2.0\cli
                          ent_64bit\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;
                          C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerSh
                          ell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files
                          (x86)\Sennheiser\SoftphoneSDK;C:\Program Files (x86)\Webex\Webex\Appli
                          cations;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microso
                          ft\WindowsApps;C:\Program Files
                          (x86)\Adaptiva\AdaptivaClient\bin\x32;C:\Program Files
                          (x86)\Adaptiva\AdaptivaClient\bin\x64;C:\Program
                          Files\FlexNet;C:\Program Files\Git\cmd;C:\Program Files
                          (x86)\Fullagar\LogQA;C:\Program Files (x86)\Fullagar\LogTrns;C:\WINDOW
                          S\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Win
                          dowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program
                          Files\gs\gs9.27\bin;C:\Program Files\gs\gs9.27\lib;C:\Program Files
                          (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program
                          Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files
                          (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program
                          Files\MATLAB\R2018a\bin;C:\Program Files\Mira
                          Geoscience\VPmg;C:\Program Files\Mira Geoscience\VPem1D;C:\Program
                          Files\Mira Geoscience\VPutility;C:\Program Files (x86)\Windows
                          Kits\8.1\Windows Performance Toolkit;C:\Users\godbn9\AppData\Local\Con
                          tinuum\miniconda3;C:\Users\godbn9\AppData\Local\Continuum\miniconda3\L
                          ibrary\mingw-w64\bin;C:\Users\godbn9\AppData\Local\Continuum\miniconda
                          3\Library\usr\bin;C:\Users\godbn9\AppData\Local\Continuum\miniconda3\L
                          ibrary\bin;C:\Users\godbn9\AppData\Local\Continuum\miniconda3\Scripts;
                          C:\Users\godbn9\AppData\Local\Programs\Python\Launcher;C:\Users\godbn9
                          \AppData\Local\Microsoft\WindowsApps;C:\Users\godbn9\AppData\Local\Pro
                          grams\Microsoft VS
                          Code\bin;C:\Users\godbn9\AppData\Local\Continuum\miniconda3\lib\site-
                          packages\pywin32_system32
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files
                          (x86)\Adaptiva\AdaptivaClient\data\PSModules
       REQUESTS_CA_BUNDLE=<not set>
         SSF_LIBRARY_PATH=C:\Program Files (x86)\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\godbn9\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\godbn9\.condarc
 populated config files : C:\Users\godbn9\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
       base environment : C:\Users\godbn9\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\godbn9\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\godbn9\.conda\pkgs
                          C:\Users\godbn9\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\godbn9\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\godbn9\.conda\envs
                          C:\Users\godbn9\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

(base) C:\WINDOWS\system32>conda config --show-sources
==> C:\Users\godbn9\.condarc <==
ssl_verify: True
proxy_servers:
  http: proxy-bne.bhpbilliton.net:8080
  https: proxy-bne.bhpbilliton.net:8081
channel_priority: strict
channels:
  - conda-forge
  - defaults
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

# packages in environment at C:\Users\godbn9\AppData\Local\Continuum\miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                1.3.0                    py37_0    conda-forge
blas                      1.0                         mkl    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37hb32ad35_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
conda                     4.8.2                    py37_0    conda-forge
conda-package-handling    1.6.0            py37h2fa13f4_1    conda-forge
console_shortcut          0.1.1                         3    defaults
cryptography              2.8              py37hb32ad35_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37hfa6e2cd_0    conda-forge
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.4                      245    defaults
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libtiff                   4.1.0                h21b02b4_3    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
matplotlib                3.1.3                    py37_0    conda-forge
matplotlib-base           3.1.3            py37h2981e6d_0    conda-forge
menuinst                  1.4.16                   py37_0    conda-forge
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
msgpack-python            0.6.2            py37he980bc4_0    conda-forge
numpy                     1.18.1           py37hc71023c_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.0            py37he350917_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pillow                    7.0.0            py37h9ea1dd6_0    conda-forge
pip                       20.0.2                   py37_1    conda-forge
powershell_shortcut       0.0.1                         2    defaults
psutil                    5.6.7            py37hfa6e2cd_0    conda-forge
pycosat                   0.6.3           py37hfa6e2cd_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6                h5b45d93_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   225              py37hfa6e2cd_0    conda-forge
pyyaml                    5.3              py37hfa6e2cd_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.80         py37hfa6e2cd_1000    conda-forge
scipy                     1.3.1            py37h29ff71c_0    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37hfa6e2cd_0    conda-forge
tqdm                      4.42.1                     py_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.34.2                   py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_1    conda-forge
</p></details>

**Comment by erinpentecost** [comment]
Same problem here, with a fresh install.

**Comment by Shellcat-Zero** [comment]
Same problem here.  Cannot install new environments and cannot downgrade conda either, old versions are throwing the same error.  I have no other choice but to switch to [virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) until these issues are resolved.

**Comment by ShunTono** [comment]
I face same problem. I get following error.
I did not use proxy setting, however the problem is happened.
I read #5297, this is similar problem and solution we faced.

(base) C:\Users\Shungo>conda install -c vpython vpython
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\Shungo\anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "C:\Users\Shungo\anaconda3\lib\concurrent\futures\_base.py", line 435, in result
        return self.__get_result()
      File "C:\Users\Shungo\anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Users\Shungo\anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\requests\adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\urllib3\poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\Users\Shungo\anaconda3\lib\site-packages\urllib3\poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

`$ C:\Users\Shungo\anaconda3\Scripts\conda-script.py install -c vpython vpython`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Shungo\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Shungo\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\Shungo\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Shungo\anaconda3\python.exe
               CONDA_ROOT=C:\Users\Shungo\anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Shungo
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
                     PATH=C:\Users\Shungo\anaconda3;C:\Users\Shungo\anaconda3\Library\mingw-w64\
                          bin;C:\Users\Shungo\anaconda3\Library\usr\bin;C:\Users\Shungo\anaconda
                          3\Library\bin;C:\Users\Shungo\anaconda3\Scripts;C:\Users\Shungo\anacon
                          da3\bin;C:\Users\Shungo\anaconda3;C:\Users\Shungo\anaconda3\Library\mi
                          ngw-w64\bin;C:\Users\Shungo\anaconda3\Library\usr\bin;C:\Users\Shungo\
                          anaconda3\Library\bin;C:\Users\Shungo\anaconda3\Scripts;C:\Users\Shung
                          o\anaconda3\bin;C:\Users\Shungo\anaconda3\condabin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files (x86)\Symantec\VIP Access
                          Client;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common
                          Files\Intel\WirelessCommon;C:\WINDOWS\System32\OpenSSH;C:\Program
                          Files\MATLAB\R2019b\runtime\win64;C:\Program Files\MATLAB\R2019b\bin;C
                          :\Users\Shungo\anaconda3\python;C:\Users\Shungo\anaconda3\Scripts;C:\U
                          sers\Shungo\anaconda3\Lib\site-package;C:\Users\Shungo\anaconda3;C:\Us
                          ers\Shungo\anaconda3\Library\bin;C:\Users\Shungo\anaconda3\python;C:\U
                          sers\Shungo\anaconda3\Lib\site-
                          package;C:\Users\Shungo\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Shungo\anaconda3
            shell level : 1
       user config file : C:\Users\Shungo\.condarc
 populated config files : C:\Users\Shungo\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\Shungo\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/vpython/win-64
                          https://conda.anaconda.org/vpython/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : C:\Users\Shungo\anaconda3\pkgs
                          C:\Users\Shungo\.conda\pkgs
                          C:\Users\Shungo\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Shungo\anaconda3\envs
                          C:\Users\Shungo\.conda\envs
                          C:\Users\Shungo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

**Comment by ngodber** [comment]
Closing issue as I found that adding http:// and https:// fixed my issue.

**Comment by Marmeladenbrot** [comment]
> Closing issue as I found that adding http:// and https:// fixed my issue.

Adding those where??
