### ISSUE TITLE
Windows prompts, env name auto-complete

### ISSUE THREAD

**Issue by Mahelita** [conda/conda#9666]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

## Current Behavior
Env names do not auto-complete upon hitting tab key in windows anaconda prompt or power-shell prompt.

### Steps to Reproduce

```
conda activate ba<tab>
```
Nothing happens

## Expected Behavior
```
conda activate ba<tab>
```
Auto-completes to
```
conda activate base
```

## Environment Information
```
conda version : 4.7.12
conda-build version : 3.18.8
python version : 3.7.4.final.0
platform : win-64
user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17763
```

## Thank you!

**Comment by github-account1111** [comment]
It kinda is there, but it's extremely half-baked. If I hit tab after `conda activate` it freezes the window (which actually really sucks, I'd prefer it just do nothing), then sometimes 5-10 seconds later autocompletes the env name. Sometimes it doesn't. IDK what's up with that.
