### ISSUE TITLE
Warning with env.yml "Pip not listed as dependency" but it actually is listed

### ISSUE THREAD

**Issue by trallnag** [conda/conda#9668]
I have the `env.yml` (can be seen in the lower part of this post) and I use `conda env create -n myenv -f env.yml` to create new environment based on the definition in the file. Just before this command I run `conda update conda`. I'm using the official repositories and channels.

One of the dependencies is

```
- anaconda::pip=10.0.1
- pip:
  - "git+https://github.com/deepchem/deepchem.git@1.1.0#egg=deepchem"
```

It installs, but I get the following warning even though I have listed pip as a dependency.

```
Warning: you have pip-installed dependencies in your environment file, but you do
not list pip itself as one of your conda dependencies.  Conda may not use the 
correct pip to install your packages, and they may end up in the wrong place.  
Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

## Is this a bug or am I missing something?

---

Few infos:

* Ubuntu distribution.

The full `env.yml`:

```
name: myenv

channels:
  - omnia
  - rdkit
  - defaults

dependencies:
  - anaconda::python=3.5
  - anaconda::pip=10.0.1
  - anaconda::six=1.11.0

  - rdkit::rdkit=2018.03.3.0

  - anaconda::pandas=0.19.2
  - anaconda::joblib=0.12.1
  - anaconda::scikit-learn=0.19.1

  - anaconda::tensorflow=1.2.1

  - anaconda::networkx=2.1

  - omnia::pdbfixer=1.4
  - omnia::mdtraj=1.9.1

  - numpy
  - requests
  - simplejson

  - pip:
    - "git+https://github.com/deepchem/deepchem.git@1.1.0#egg=deepchem"
```

Few of the more exiOS requirements:

* libxrender1
* libxext6

**Comment by bfwi317bph** [comment]
Same problem here, did you find a solution? 

Best Regards 

Aruun Ak
