### ISSUE TITLE
Cannot uninstall anaconda in Mac using Catalina 10.15.3

### ISSUE THREAD

**Issue by ghostintheshellarise** [conda/conda#9669]
i try to use `conda install anaconda-clean` to remove the my anaconda via terminal. However, i got following message

`Last login: Sat Feb  8 15:36:45 on console
ka-mantse@Ka-mans-MBP ~ % conda install anaconda-clean
zsh: command not found: conda
ka-mantse@Ka-mans-MBP ~ % `

**Comment by acudoc** [comment]
I have small issue tried `conda install anaconda-clean`. Got `zsh: command not found: conda`

**Comment by EdenRochman** [comment]
i have the same error, did you fix it?
