### ISSUE TITLE
username and password of proxy being repeatedly asked

### ISSUE THREAD

**Issue by srooks10** [conda/conda#967]
First thanks for `conda`, it is a great improvement to distribute python packages over previous solutions.

Using `conda` 3.7.1

I am sitting behind a NTLM proxy at work and as a consequence `conda` keeps asking for my http or https proxy user name and password. See at the end of the post for an example of a session.
In my experience this happens any time conda needs to get through the proxy, being to fetch one  index or download one package. With multiple channels and tens of packages it gets quickly annoying :smile: 

1. Could `conda` somehow cache the username / password after using them successfully?
2. I have also set my `http_proxy` and `https_proxy` to contain both the username and password. They seem to be both discarded, only the proxy url and port are being used by `conda`.

```bash
$ conda create -n test ipython tornado
Fetching package metadata: .
http proxy username: my_username
Password:
..
Solving package specifications: .
Package plan for installation in environment /home/seb/anaconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipython-2.3.0              |           py27_0         2.8 MB
    tornado-4.0.2              |           py27_0         456 KB
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

    ipython:            2.3.0-py27_0  
    openssl:            1.0.1h-1      
    python:             2.7.8-1       
    readline:           6.2-2         
    sqlite:             3.8.4.1-0     
    ssl_match_hostname: 3.4.0.2-py27_0
    system:             5.8-1         
    tk:                 8.5.15-0      
    tornado:            4.0.2-py27_0  
    zlib:               1.2.7-0       

Proceed ([y]/n)? y

Fetching packages ...

http proxy username: my_username
Password:
ipython-2.3.0- 100% |#####################################################| Time: 0:00:19 151.78 kB/s

http proxy username: my_username
Password:
tornado-4.0.2- 100% |#####################################################| Time: 0:00:00 911.82 kB/s
Extracting packages ...
[      COMPLETE      ] |#######################################################################| 100%
Linking packages ...
[      COMPLETE      ] |#######################################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
```

**Comment by mahadi** [comment]
@srooks10 Can you provide a sample .condarc for the connection to your NTLM Proxy? I cant get it working with NTLM on my side. Its only claiming "407 Authorization Required" although the username and password was entered (including the special character escaping)
