### ISSUE TITLE
`conda env config vars list` not working

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda/conda#9679]
As suggested [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables). I get:

```
usage: conda-env-script.py [-h] {create,export,list,remove,update} ...
conda-env-script.py: error: invalid choice: 'config' (choose from 'create', 'export', 'list', 
'remove', 'update')
```

How can I view environment variables?

<hr>

**Additional info**:

```
     active environment : base
    active env location : D:\Anaconda
            shell level : 1
       user config file : C:\Users\OverL\.condarc
 populated config files : C:\Users\OverL\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
          administrator : True
```
Windows 10 x64

**Comment by Tetra-quark** [comment]
I have the same problem on macOS 10.15. I guess something must have changed in how to list or set environment variables...

**Comment by calvinwy** [comment]
same here, I am experiencing the same problem too.

**Comment by alistairwgillespie** [comment]
Same error my end too. The following works.

In the docs there is some initial setup for Windows and MacOS/Linux environment variables for the latest conda version [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#windows). 

Once you complete the steps at the link, the following should enable access to your environment variables through Jupyter and at the command line:
1. Restarting any Jupyter Notebook servers
2. Deactivate/activate the environment
3. Starting Jupyter again

Then you can test in a notebook with:
```
import os
print(os.environ['<ENV_NAME>'])
```

**Comment by calvinwy** [comment]
Just to update, my original purpose is to modify the environmental variables.  So...  instead of using the command, I created them in the default loading/exiting script in:

`
/opt/anaconda3/envs/<env_name>/etc/conda/activate.d/env_vars.sh
/opt/anaconda3/envs/<env_name>/etc/conda/deactivate.d/env_vars.sh
`

They serves the same purpose as '~/.bash_profile' for starting a new terminal, but instead they are loaded when starting the environment and quitting the environment.

**Comment by mbelmadani** [comment]
The [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables) still lists the `conda env config vars list` as the way to list the environments. The whole section on setting environment variables seems broken, is this really not supported any more?

**Comment by chinwobble** [comment]
also have this issue

**Comment by kevinkurek** [comment]
Any updates? Same issue here.

**Comment by fernandolkf** [comment]
Same here

**Comment by fernandolkf** [comment]
I update conda to last version and it worked

**Comment by OverLordGoldDragon** [comment]
@fernandolkf Updating did remove the error, but the command's output is empty; I followed [these](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#windows) steps for setting environment variables. Did you use a different approach to set env vars?

**Comment by fernandolkf** [comment]
@OverLordGoldDragon I followed these steps:

To create my var

`conda env config vars set my_var=value`

Listing all conda vars:

`conda env config vars list`

But on python I only manage to get the var in all caps

```
import  os

os.getenv('MY_VAR')
```

**Comment by OverLordGoldDragon** [comment]
@fernandolkf Thank you; this seems resolved - I'm migrating the issue [here](https://github.com/conda/conda/issues/9820) regarding env vars on activation.
