### ISSUE TITLE
"/AddToPath" option does not work in "Anaconda3-2019.10-Windows-x86_64.exe"

### ISSUE THREAD

**Issue by amastrobera** [conda/conda#9718]
Dear Conda,

I try to install from command line your (latest) version of windows. Like in [your example](https://docs.anaconda.com/anaconda/install/silent-mode/) I do this

`start /wait "" Anaconda3-2019.10-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /AddToPath=0 /S /D=%UserProfile%\Anaconda3`

and my `PATH` is unchanged. I tried with  `/AddToPath=1`, same result. 

uninstalling (on the other hand) does remove PATH variables (that I added myself).

**Comment by yoda-vid** [comment]
The silent installer appears to set up `PATH` for me at least when installing Miniconda Python 3.7 (Conda 4.8.3) on Windows 10 in Command Prompt.
