### ISSUE TITLE
pip should use conda when available

### ISSUE THREAD

**Issue by hughperkins** [conda/conda#9719]
I want to use conda. I do use conda. since several years. but many people around me, in my job, continue to use virtualenv. So we have a mixture of conda and virtualenv. And pip and conda dont play nicely together.

I think that when someone installs sometihng using pip, pip should *automatically* check if the package is available for conda, and install the conda version if available.

pip using a conda package when available would go a long way to ensure we dont have a mixture of conda installed and pip installed packages in our conda environments, and inconsistency between different people's conda envionrments of which packages were installed using pip, and which using conda.

**Comment by mingwandroid** [comment]
We could do that but it is quite a change to what pip is and many would hate that. Could you get some buy-in and design suggestions from the pip developers about this?

**Comment by hughperkins** [comment]
I was thinking that you could make `pip` a wrapper script, that first tries conda, then falls back to pip if the package is not in conda.

pip itself would stay unchanged (except that the actual `pip` script would be renamed to somethign like `pip_original`. )
