### ISSUE TITLE
can't  create any environment new, cant install any packges, cant update conda ,all these with the same"solving environment done "but come out nothing

### ISSUE THREAD

**Issue by colaaaaaa** [conda/conda#9723]
**_######when i install a package: it comes  out this:_**
(base) C:\Users\leimin>conda install -c anaconda anaconda-clean
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base conda
**_######Then i come to update the conda to the latest version of 4.8.2:it come out this:_**
(base) C:\Users\leimin>conda install conda=4.8.2
Collecting package metadata (repodata.json): done
Solving environment: done

**_##### when i choose to create a new env it shows nothing_** 

**At last i have no choise but to unistall the anaconda and to reinstall but when follow the tips by the offetion ways it alsoo cant do the job:
Because i cant install the package : anaconda - clean**

i hope somebody can help me, really appreciate!!!!

i hope some

**Comment by chloecwy** [comment]
I had the same issue, thought that I'd reinstall conda, and then now my conda commands don't provide any output at all. Hoping someone could fix this as well.
