### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by EricLucife** [conda/conda#9726]
I have installed PyTorch in miniconda. I can import torch in Anaconda Prompt. But when I try to import torch in IDLE, the first time there is a Warning. Then I try it again, there are nothing wrong. the path of IDLE is  "D:\Miniconda3\Lib\idlelib\idle.bat"
![image](https://user-images.githubusercontent.com/35440115/75661838-06b56100-5ca9-11ea-8abe-75fc4b5e115e.png)

**Comment by kalefranz** [comment]
Make sure you've opened idle from an activated conda environment.
