### ISSUE TITLE
Git bash and m2-bash conflict regarding cygpath

### ISSUE THREAD

**Issue by msarahan** [conda/conda#9729]
With conda 4.8.2, I wanted to use it within git bash.  I had installed m2-bash for something else recently.  When I ran "conda init bash" from within my manually-activated git bash shell, conda found the bash in the conda installation (totally expected behavior), not the bash shell that I was running.  The m2-bash package is very different from git bash at this point, though.  It has cygpath, and the `cygpath -up` check returns something starting with `/cygdrive/c`.  For git bash, though, that /cygdrive path does not exist.  Thus conda's activation scripts are written in a way that breaks them on git-bash.

I'm not sure what the right way to fix this is.  Perhaps symlinking /c to /cygdrive/c in git bash?  Maybe teaching conda to look with and without cygdrive (fallback)?  Update m2-bash so that its behavior might be uniform?

I'm up for working on it, but I'd like to talk with you guys to get your opinion on how to fix.

**Comment by mingwandroid** [comment]
Hi Mike, you need to also install m2-filesystem as that package contains the mount information that transforms /cgygdrive/x to /x. Really it'd be nice if this were a dep of all m2 packages and is something to consider upon update of these.

Cheers!

**Comment by msarahan** [comment]
Ah, that makes sense.  I remember that stuff, but missed it as m2-bash was brought in as a dep of some sort.  Thanks for straightening that out.  I'll close this issue, unless you guys want to keep it open for tracking Ray's suggestion.
