### ISSUE TITLE
All PRs blocked because checks are failing..?

### ISSUE THREAD

**Issue by LorcanHamill** [conda/conda#9731]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

Lots of tests seem to be broken on the "master" branch.  All PRs are being blocked because of test failures that seem unrelated to the contents of the PR.   For example, my #9730 just adds a method that is never called; #9689 just corrects some typos in a docstring, but both are showing multiple test failures that appear unconnected to the changes in the PRs.   All recently-submitted PRs seem to be in the same situation.

### Steps to Reproduce

Just look at one of the PRs linked above.   Or create a new, do-nothing PR.

## Expected Behavior

The tests should pass

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

N/A
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

N/A
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

N/A
</p></details>

**Comment by mingwandroid** [comment]
They are not 'blocked' due to test failures but held up by lack of reviewer time. I hope to take a look at your recent PR soon though. Thanks.

**Comment by LorcanHamill** [comment]
Thanks, @mingwandroid, for picking up on this so quickly.   But I don't understand your reply.  I understand that PRs cannot get merged without being reviewed, and of course that requires time from busy people so it can take a while.   That's all fine.  But the process also includes a whole bunch of automated checks, building the package and docs, running unit and integration tests, etc.   Unless I misunderstand the process, those should all pass, regardless of whether the code has been reviewed.   In fact, I'd expect reviewers to wait for them to pass before spending their time reviewing the code.   And right now, those automated checks are failing, for reasons that I don't understand.

Have I misunderstood how this whole process works?   (That's quite possible, as this is my first PR...)

**Comment by LorcanHamill** [comment]
Also, just to clarify, I'm not asking that #9730 be reviewed yet.  It's a draft PR, with just one small commit in it as yet.  It needs several more commits before it will be ready for review.   I wanted to create a minimal PR just to check if these test failures were due to the contents of the PR or something else...

**Comment by mingwandroid** [comment]
>  Unless I misunderstand the process, those should all pass

Ideally they would all pass yes, but things change (external to conda's source and external to it, e.g. CI system images get updated, new dependencies get pull in) so a project like conda and its testsuite do not live in isolation (though of course we try to isolate as much as we can).

You have to make a judgement call whether any tests were broken by your PR or not, but really the change PR should come with its own novel test for the change being made and you can mostly focus on that test and any you suspect could be collateral.

**Comment by mingwandroid** [comment]
Mainly, judgement is excercised when merging PRs. We will not release a new release of conda at a point when any test in CI is failing (as a general rule) but we can merge PRs without entirely green testsuite results.

**Comment by LorcanHamill** [comment]
Ah, I see.   I had assumed that merging would be mechanically blocked unless all checks were passing.   It's understandable that new dependencies can break things without any change in the project itself.  (In fact, I've been having problems running the tests locally that seem to come from "coverage" version 5.0.0 and have had to pin it to 4.5.4, though that doesn't seem to be happening in CI.)

Okay, thanks again for the replies.   I'll push more code to complete the PR.   This time, I think I'll implement it in such a way that the new caching behaviour is completely disabled during tests (by an "autouse" test fixture),  Then I'll write a single new test that enables and verifies it.    That should make it easy to be sure that any failures are not due to this PR.   It's also a safer approach anyway.

Thanks again.   I'll close this now...

**Comment by mingwandroid** [comment]
You can keep working in the same PR, and that would be preferable. Just push new commits (or force push if you want to rebase them).

**Comment by mingwandroid** [comment]
>  Then I'll write a single new test that enables and verifies it. That should make it easy to be sure that any failures are not due to this PR. It's also a safer approach anyway.

We would want to ensure at least the pertinent parts of the testsuite pass when your feature is enabled globally, and if there are no large problems or small caveats to your change then in theory it should be the default behavior anyway and all tests should pass?

**Comment by LorcanHamill** [comment]
Yes, ideally all tests should pass with this feature enabled.   But I think there may be some existing tests that rely on the fact that file:/// channels are **not** cached.   Also, tests should not depend on the initial contents of the cache (ie. on side-effects of previous tests, which have requested some data and thus loaded the cache.).  I suspect that some existing tests _are_ dependent on previous tests having cached data for HTTP channels.

Okay, I will try to have this behavior active at all times and ensure that it doesn't break any existing tests.   I will use an "autouse" test feature to discard any cached data for file:// channels before each test is run, to keep tests independent of each other.  (Ideally it should discard data for HTTP channels as well, but that would break existing tests and I don't want to open that can of worms.)

This _will_ break at least one test, as I found when working on my initial PR, (#9677).  But that can be handled by having a method to clear the cache and explicitly calling that from the affected test.  (The test is for the feature where an environment variable determines if we should prefer tarballs or .conda files; it expects different data to be returned depending on the setting of that variable, so the cache needs to be wiped when it changes the variable.)

To be clear: do you want me to resurrect #9677  (which I closed accidentally by resetting the branch all the way back to master) or to continue of #9730 ?   I have no preference either way.

And again, thanks for your time on this, @mingwandroid .

**Comment by mingwandroid** [comment]
I haven't looked at them to determine that, whatever you feel is best.
