### ISSUE TITLE
conda still doesn't retry failed package downloads

### ISSUE THREAD

**Issue by ChemicalSailor** [conda/conda#9740]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I submitted a feature request https://github.com/conda/conda/issues/9312 which led to PR https://github.com/conda/conda/pull/9318; thanks for making the effort to implement this! Unfortunately I still have the same problem, even with retries configured. The download fails once and I assume is not retried in this context because with a backoff factor of 20, I should be waiting a long time for it to finally fail, whereas this is almost immediate.

BTW, I can confirm the retries and backoff factor does work when trying to download repodata - in that case I can be waiting a long time.

### Steps to Reproduce

```
(base) C:\Users\tfletcher>conda env update -n cdt-base -f P:\cdt-base.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
_py-xgboost-mutex-2. | 12 KB     | ############################################################################ | 100%
py-xgboost-0.90      | 80 KB     | ############################################################################ | 100%
libxgboost-0.90      | 3.9 MB    |                                                                              |   0%

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://repo.anaconda.com/pkgs/main/win-64/libxgboost-0.90-1.tar.bz2>
Elapsed: 00:01.771284

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.



(base) C:\Users\tfletcher>conda config --show-sources
==> C:\ProgramData\Anaconda3\.condarc <==
remote_max_retries: 5
remote_backoff_factor: 20
```

## Expected Behavior

conda should retry the download following the backoff_factor rules. Seeing as this can occur for many packages it doing a big update, it would be nice if each package was downloaded in parallel, otherwise the wait could be long!

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\tfletcher\.condarc
 populated config files : C:\ProgramData\Anaconda3\.condarc
          conda version : 4.8.2
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\tfletcher\.conda\pkgs
                          C:\Users\tfletcher\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\tfletcher\.conda\envs
                          C:\Users\tfletcher\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\ProgramData\Anaconda3\.condarc <==
remote_max_retries: 5
remote_backoff_factor: 20
```
</p></details>

**Comment by kalefranz** [comment]
If the response code is `403 FORBIDDEN`, we should never just retry the same request and expect a different result. In general, 403 means your credentials are invalid (wrong, revoked, expired, etc) and you need to renew them.

**Comment by ChemicalSailor** [comment]
@kalefranz What you have said is correct, but I think there is a broader scope here.

In my case retrying the same request and getting a different result is exactly what does happen - the 403 is temporary whilst anti-malware tests etc are run; after a few minutes you'll get a 200 response. Now whether the firewall vendor using 403 is technically the correct thing to do is another matter (it's reasonably logical to me), but let me ask this - does conda behave differently if it was a different error code (503 for instance)?

My expectation is no, it would be exactly the same. I don't think conda should be opinionated about what to retry because there are so many reasons that conda doesn't control as to why an HTTP request can fail - it should be up to the end user to decide if they want to retry on failure. All I'm asking for is an automatic way to do this.

**Comment by chenghlee** [comment]
I would point out that [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.3), which defines HTTP message semantics, states fairly explicitly that clients receiving a 403 response should not (automatically) repeat the request without changing something:

> 6.5.3.  403 Forbidden
> 
> The 403 (Forbidden) status code indicates that the server understood
> the request but refuses to authorize it.  A server that wishes to
> make public why the request has been forbidden can describe that
> reason in the response payload (if any).
> 
> If authentication credentials were provided in the request, the
> server considers them insufficient to grant access.  The client
> SHOULD NOT automatically repeat the request with the same
> credentials.  The client MAY repeat the request with new or different
> credentials.

HTTP 403 is the only status code for which RFC 7231 defines repeat request behaviors, so I would be a little hesitant to modify conda in way that contradicts the standard.

**Comment by ChemicalSailor** [comment]
> I would point out that [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.3), which defines HTTP message semantics, states fairly explicitly that clients receiving a 403 response should not (automatically) repeat the request without changing something

That is interesting, and not something I was aware of.

I'd make three points:
1. "If authentication credentials were provided" - The "changing something" fairly explicitly states credentials. In my case conda is not providing any credentials, it's just asking for a package and there happens to be a server sitting in the middle that is forbidding that access until it knows it's safe. I know this is a bit of an edge case. If accessing a private repository then conda may be providing some credentials, in which case it would be violating this principle. I doubt telling the difference between these cases is possible in code - it should be up to the user to tell conda how to behave.
2. If "changing something" is not just credentials, then what I am changing is time. At the moment I have to repeat the request manually every few minutes. If it was implemented automatically then my settings would have to replicate this, not just make the request constantly. (As an aside, the firewall actually caches the package, so it's not the public repository taking the hit.)
3. ["Special cases aren't special enough to break the rules. Although _practicality beats purity_."](https://www.python.org/dev/peps/pep-0020/) This comes back to my earlier point of what would happen if the error code was different? If there are other cases where it's acceptable to automatically repeat requests, and it makes practical sense to be able to do so, why should it be restricted. Again, this is something the user needs to decide, and I'm not advocating that conda should automatically retry by default, just that the capability is available.

If this specific functionality doesn't get integrated into conda, would there be a way of being able to hook in with my own code to modify conda's behaviour?

**Comment by mabrow05** [comment]
I consistently have the same issues as @ChemicalSailor while working behind a firewall. This is a problem for my team as I am trying to automate and standardize around python and conda, which means creating spec files so that team members can easily create consistent environments. Having to execute `conda create` over and over again until it magically works does not give anyone confidence in what is happening behind the scenes. I would love the option to retry no matter what!
