### ISSUE TITLE
When i write python in command promt, I see this warning. Please help me remove it.                                                Warning: This Python interpreter is in a conda environment, but the environment has not been activated.  Libraries may fail to load.  To activate this environment please see https://conda.io/activation                -----      Also when I write activate base, the warning disappears. What is the issue here. Any suggestions and guidance would be appreciated.

### ISSUE THREAD

**Issue by AbhinavKumar28** [conda/conda#9742]
![Screenshot (4)](https://user-images.githubusercontent.com/55653381/76233968-05f37080-624f-11ea-8871-a0f10c46c476.png)

**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

![Screenshot (4)](https://user-images.githubusercontent.com/55653381/76233968-05f37080-624f-11ea-8871-a0f10c46c476.png)

### Steps to Reproduce

```
When I type python. The warning shows.
But when I type activate base and then python. The warning disappears.

```

## Expected Behavior
 The warning should not be there.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by mingwandroid** [comment]
You need to continue to use the activation procedure as pointed out in the message or else you can use "The Anaconda Prompt".

**Comment by AbhinavKumar28** [comment]
Thanks for your help @mingwandroid
