### ISSUE TITLE
Re-using / linking packages in (base) environment

### ISSUE THREAD

**Issue by scottyhq** [conda/conda#9743]
My understanding is that conda uses hardlinks when possible to save space when multiple environments are installed (helpful detailed explanation here https://github.com/conda/conda/issues/4881#issuecomment-294902365). However, it seems that this does not apply to packages from the (base) environment installed with miniconda (4.7.12) regardless of whether or not the pkgs/ directory exists. The easiest way to illustrate this is cloning the base environment, below is a dockerfile  that shows how the first cloned environment size is significantly larger. 

This is probably intentional design, but what if the `base` environment were installed like other environments such as `/opt/conda/envs/base`? This would be very useful to reduce docker image sizes that use conda. 

```
Environment size:
197M	/opt/conda/envs/myclone
18M	/opt/conda/envs/myclone2
```

```
FROM continuumio/miniconda3:4.7.12

# Check package re-use by creating two copies of base environment
RUN conda create --name myclone --clone base \
    && conda create --name myclone2 --clone base \
    && du -sh /opt/conda/pkgs \
    && echo 'Environment size:' \
    && du -sh /opt/conda/envs/* \
    && du -sh /opt/conda/pkgs


# Install fresh miniconda which keeps the pkgs/ directory
RUN MINICONDA_VERSION=4.7.12.1 \
    && URL="https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" \
    && INSTALLER="miniconda.sh" \
    && wget --quiet $URL -O ${HOME}/${INSTALLER}  \
    && /bin/bash ${HOME}/${INSTALLER} -b


# Check package re-use by creating two copies of base environment
RUN export PATH=${HOME}/miniconda3/bin:${PATH} \
    && which conda \
    && conda create --name myclone --clone base \
    && conda create --name myclone2 --clone base \
    && du -sh ${HOME}/miniconda3/pkgs \
    && echo 'Environment size:' \
    && du -sh ${HOME}/miniconda3/envs/* \
    && du -sh ${HOME}/miniconda3/pkgs
```

cc @jhamman, @TomAugspurger, @ocefpaf, @tjcrone, @yuvipanda. other relevant issues https://github.com/conda-forge/miniforge/issues/21, https://github.com/jupyter/repo2docker/issues/858

**Comment by tjcrone** [comment]
Is the question here whether we should be using miniforge? Seems like a good idea to me! I've often wondered why we needed a notebook env, in addition to the base env. Maybe this is why? Or maybe I'm not understanding where you are headed with this @scottyhq? What if users were launched into the base env, rather than the notebook env, and what we wanted there (everything from conda-forge) was there, and we didn't have any environments in /srv/conda/envs/? Wouldn't this be the smallest option? Or is this a bad idea?
