### ISSUE TITLE
allow conda subcommands to add keys to the .condarc file (including defaults)

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#975]
conda cluster needs to be able add it's own keys to the config file (.condarc).  Other sub-commands will need the same capability.  Having some way to allow sub-commands to add "accepted" keys os that errors can still be raised would be useful.

**Comment by pelson** [comment]
Looks like this was added at some point (e.g. https://github.com/conda/conda-build/blob/master/conda_build/config.py#L48). However, I don't think ```conda config``` knows how to get or set these, so a manual edit of the condarc is necessary.

**Comment by soapy1** [comment]
It looks like this has been added

```
conda config --help
usage: conda config [-h] [--json] [--debug] [--verbose]
                    [--system | --file FILE]
                    (--show | --show-sources | --validate | --get [KEY [KEY ...]] | --append KEY VALUE | --prepend KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]

Modify configuration values in .condarc.  This is modeled after the git
config command.  Writes to the user .condarc file (/Users/scastellarin/.condarc) by default.
```

@csoja can this issue be closed?
