### ISSUE TITLE
``pip install -e '' will break the subsequent ``cond install'' commands.

### ISSUE THREAD

**Issue by hongyi-zhao** [conda/conda#9752]
Hi,

I created a conda-based virtualenv and use the pip + conda to manage packages within it.

When I install some package with pip's develop/editable mode, then the subsequent  ``cond install'' commands will be brokened.

Any hints for this issue?

Regards

**Comment by kalefranz** [comment]
Please enable pip-interop with

```
conda config --set pip_interop_enabled true
```

Here's the help output:

```
> conda config --describe pip_interop_enabled
# # pip_interop_enabled (bool)
# #   Allow the conda solver to interact with non-conda-installed python
# #   packages.
# #
# pip_interop_enabled: false
```
