### ISSUE TITLE
Installing geopandas

### ISSUE THREAD

**Issue by brucereyes** [conda/conda#9756]
Hi All. Apologies for the n00b question. I am trying to install geopanda for my data visualization project, and I am not sure what I need to do. Is there any guide I can look at? I have been following a lot of blogs and github reports. Please help!

**Here is the Error I get:**
```
(base) C:\Users\bruce>conda install geopandas
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
```

It looks like I needed to install GDAL

This is what I get
```
(base) C:\Users\bruce>conda install gdal
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

CondaError: KeyboardInterrupt

Terminate batch job (Y/N)? y

(base) C:\Users\bruce>conda install -c-forge gdal
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: -forge
  channel url: https://conda.anaconda.org/-forge
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

Can someone please help? Or link me to a good guide  installing them from scratch? Thank you so much! I am using Anaconda 3.7 version with 64-bit

**Comment by LBainWx** [comment]
I'm also having the same issue with Geopandas and this was after I updated Anaconda and Spyder. Have been trying to roll back to previous versions of Conda/Spyder, but not having much success just yet. Any attempt to install Geopandas in Spyder, loading from Conda or at the command line have failed. Moreover, I've tried to create another environment...activate that environment at the command line and/or in Spyder and it doesn't appear to accept the new environment at all.
