### ISSUE TITLE
Clarifying -n vs -p "error" messages

### ISSUE THREAD

**Issue by ericdill** [conda/conda#9762]
New(ish) users don't always use the right flags. `-n` instead of `-p` is a pretty common failure mode. A recent interaction with a novice-ish conda user produced the following:

> The error message is perplexing given that the supplied path is a legal Windows path. (I also tried enclosing the path in double quotes, to no avail).
and the terminal output:

```
(base) C:\>conda create --clone base -n C:\ProgramData\Anaconda3\envs\py37
 
CondaValueError: Invalid environment name: 'C:\ProgramData\Anaconda3\envs\py37'
 Characters not allowed: ('/', ' ', ':', '#')
```

Suggested resolution would be to check if the argument passed to `-n` is a full path and, if so, suggest to the user that they may be meaning to use `-p` instead

**Comment by kenodegard** [comment]
@ericdill What about introducing a new argument `-e`/`--env` (`-n`/`--name`/`-p`/`--prefix` would become aliases) that accepts either a name or a prefix? If we're able to detect that we got the "wrong" value, then we can also circumvent the issue in the first place.

**Comment by travishathaway** [comment]
We need to account for the following:

- What happens when `-n` and `-p` collide? Should we prompt the user to tell us which to choose? Should there be a `--force` flag?
- Make sure that we are showing a sensible error message related to the intent of the user's command.
