### ISSUE TITLE
An unexpected error has occurred, 'conda create -n tensorflow python=3.5 anaconda ' fail.

### ISSUE THREAD

**Issue by challenge2** [conda/conda#9767]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
```
</p></details>

**Comment by kalefranz** [comment]
Empty issue. No details provided.
