### ISSUE TITLE
Shebang replacement can exceed length limit

### ISSUE THREAD

**Issue by aparashk** [conda/conda#977]
On Linux, there is a hard limit on the length of the shebang path, somewhere between 80 and 127 characters. Currently, conda performs shebang update upon installation, and that can easily exceed that limit in certain setups.

My proposal is to avoid hitting this limit by using the 'env' option for finding the Python interpreter on the path:

``` bash
#!/usr/bin/env python
...
```

I understand that may not be what one needs, but it is better than having a completely broken shebang path when the limit is exceeded.

**Comment by aldanor** [comment]
Confirming, would make sense for conda to fail early (or revert the linking stage) if a long shebang is detected. 

Sample use case: we're running a CI server that creates folder trees that are quite deep so we sometimes end up with paths like
```sh
#!/hostname/the-user-name/bamboo-home-1/xml-data/build-dir/CONDA-BR-CTLR/a-somewhat-long-project-name/.conda/envs/py2/bin/python
```

Conda happily installs such entry points but then of course you get the "bad interpreter" error when trying to run it.

**Comment by asmeurer** [comment]
I'd rather conda be agnostic about the meaning of the paths it replaces in files. We can add something to our documentation FAQ about the error message if it comes up often.

It's also worth noting that usually the package itself is still usable in such long paths. It is only the entry point scripts with the shebang lines that break, but you should still be able to start Python and execute the code manually.

**Comment by kalefranz** [comment]
Conda now falls back to `#!/usr/bin/env executable` if the shebang otherwise goes over the limit.  Still not perfect, but gets us further than we were before.

**Comment by stevekm** [comment]
@kalefranz I am using conda `Miniconda3-4.5.4` on CentOS 6 and this is not the case, it still breaks, seemingly due to the shebang line being long (in my case, 144 characters). Is there some specific mechanism you are supposed to use in order to enable this 'fix'?

**Comment by kalefranz** [comment]
@stevekm The Miniconda installer does not have the behavior I discussed in https://github.com/conda/conda/issues/977#issuecomment-298467713, only conda itself. Use the Miniconda installer to bootstrap conda to some place that has a reasonable path length, and then use conda from there to create new environments.
