### ISSUE TITLE
--singularity-args arguments not being added to singularity call by snakemake

### ISSUE THREAD

**Issue by moritzschaefer** [conda/conda#9772]
When running snakemake with use-singularity, adding a bind argument to the singularity-call using --singularity args, it does not affect the final singularity call. Snakemake call:

`snakemake --use-singularity --singularity-args '--bind /home/myhome' --cores 2 --snakefile ../src/Snakefile --configfile config.json`

Resulting singularity call (reported by snakemake after failing pipeline):

```

RuleException:
CalledProcessError in line 332 of /home/myhome/myproject/pipelines/smproject/src/Snakefile:
Command ' singularity exec --home /home/myhome/myproject/pipelines/smproject/config  --bind /home/myhome/anaconda3/envs/singularity/lib/python3.7/site-packages:/mnt/snakemake /home/myhome/myproject/pipelines/smproject/config/.snakemake/singularity/bc12f9f5dd66bf5a09489dfa07c45231.simg bash -c 'set -euo pipefail;  Rscript --vanilla /home/myhome/myproject/pipelines/smproject/config/.snakemake/scripts/tmpbg3dmmt3.checkParameterValidity.R'' returned non-zero exit status 1.
  File "/home/myhome/myproject/pipelines/smproject/src/Snakefile", line 332, in __rule_checkParameterValidity
  File "/home/myhome/anaconda3/envs/singularity/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

checkParameterValidity fails because it can't find a file, which should exist. The reason it cannot find it, is that the --bind parameter for singularity did not get passed on to singularity by snakemake. I'm digging through the snakemake source code in the hope I can find the reason for this issue. Any help is greatly appreciated.

I am using snakemake and singularity from within a conda environment.
```
(singularity) ➜  config git:(master) ✗ conda --version
conda 4.8.2
(singularity) ➜  config git:(master) ✗ singularity --version
singularity version d5eaf8a+dirty
(singularity) ➜  config git:(master) ✗ snakemake --version
5.11.1
(singularity) ➜  config git:(master) ✗
```

**Comment by moritzschaefer** [comment]
Ok, I've gone a little through it, here is what I found:

In https://github.com/snakemake/snakemake/blob/53c1589162f296dc509db26235ca6fd232814135/snakemake/script.py#L872 
an RScript executor is instantiated. Here the singularity_args argument is still present.

Later, when a shell is spawned to execute singularity, the singularity_args argument is not passed on:
https://github.com/snakemake/snakemake/blob/53c1589162f296dc509db26235ca6fd232814135/snakemake/script.py#L336 (the kwargs argument only contains the script filename)

In shell.py local variables from the script-frame are lifted up, however singularity_args is not defined as local variable there, so it won't get consumed either: https://github.com/snakemake/snakemake/blob/53c1589162f296dc509db26235ca6fd232814135/snakemake/shell.py#L88

My suggested solution would be to either pass singularity_args as part of kwargs in script.py:336 or to just define it locally in script.py such that it gets picked up by the context variable.

**Comment by sschmeier** [comment]
was this fixed?

**Comment by moritzschaefer** [comment]
@sschmeier I confused the repository and posted it here instead of looking first in the correct repository. check out https://github.com/snakemake/snakemake/issues/193
