### ISSUE TITLE
Problem HTTP Connection CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>

### ISSUE THREAD

**Issue by mateovalencia** [conda/conda#9778]
I am having this problem:

Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/win-64'

With this command: conda create -n ox --strict-channel-priority osmnx.

I am trying to install osmnx creating an env with conda.

**Comment by UniqASL** [comment]
I am getting the same error here when running

`conda update --all`

My OS is Windows 10.

**Comment by UniqASL** [comment]
I managed to solve the issue by opening the Anaconda Prompt as administrator. Maybe this might also work for you.

**Comment by kalefranz** [comment]
The url at https://conda.anaconda.org/conda-forge/win-64/current_repodata.json is working for me. It looks like there might not be a route out network connection for the location you're running that command from.

**Comment by artesim** [comment]
Hi, late to the party, but I thought I'd share : I was also having this error, but from a classic cmd prompt on win10.
Then I tried from an "anaconda prompt" and it worked immediately.

**Comment by htilquin** [comment]
Hello,
Same here. I just seem to get :

> Collecting package metadata (current_repodata.json): failed
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>

every time I try to install or update anything, from anaconda-prompt or cmd prompt, as a regular user or administrator.

When trying to launch anaconda navigator, I get :

> ImportError: cannot import name 'HTTPSHandler' from 'six.moves.urllib.request' (unknown location)

It used to work just fine until today, and my location didn't change. I didn't update anything since the last time I used Anaconda. This is getting very frustrating, as I can not work anymore and just lose time trying to solve that problem...

Thanks in advance.

**Comment by vvnykt** [comment]
On Windows 10 add 3 environment paths like the followings:
C:\Users\username\anaconda3 
C:\Users\username\anaconda3\Scripts
C:\Users\username\anaconda3\Library\bin
