### ISSUE TITLE
Issue on the Navigator start-up at Windows 10

### ISSUE THREAD

**Issue by NunoEdgarGub1** [conda/conda#9784]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by forrestwaters** [comment]
Issues related to Navigator should be opened at https://github.com/ContinuumIO/anaconda-issues/issues
Please fill out all requested information in the issue template for us to be able to help. Thanks!
