### ISSUE TITLE
Can't `conda init` on Arch Linux with zsh

### ISSUE THREAD

**Issue by marimeireles** [conda/conda#9785]
## Current Behavior

```
no change     /usr/condabin/conda
no change     /usr/bin/conda
no change     /usr/bin/conda-env
needs sudo    /usr/bin/activate
needs sudo    /usr/bin/deactivate
needs sudo    /usr/etc/profile.d/conda.sh
needs sudo    /usr/etc/fish/conf.d/conda.fish
needs sudo    /usr/shell/condabin/Conda.psm1
needs sudo    /usr/shell/condabin/conda-hook.ps1
needs sudo    /usr/lib/python3.8/site-packages/xontrib/conda.xsh
needs sudo    /usr/etc/profile.d/conda.csh
no change     /home/mariana/.bashrc
No action taken.
Operation failed.
```

### Steps to Reproduce

Download the conda package from AUR.
Install it.
Create an environment.
```
conda init
```

## Expected Behavior

Conda would initialize.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/mariana/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.2.final.0
       virtual packages : __glibc=2.31
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/pkgs
                          /home/mariana/.conda/pkgs
       envs directories : /home/mariana/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.2 Linux/5.5.10-arch1-1 arch/ glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
no output for this
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
EnvironmentLocationNotFound: Not a conda environment: /usr

```
</p></details>

**Comment by marimeireles** [comment]
Might be related to https://github.com/conda/conda/issues/8244?

**Comment by specter119** [comment]
@marimeireles  you mean the aur package https://aur.archlinux.org/packages/python-conda/ ?
there is no need for `conda init`.

**Comment by marimeireles** [comment]
Alright!
Thanks for the feedback.

**Comment by sirus20x6** [comment]
also on arch. also can't conda init or activate

**Comment by marimeireles** [comment]
It's weird, for me it works inside of `tmux`, but not in the normal terminal environment. I'm using Xfce terminal.

**Comment by specter119** [comment]
@marimeireles @sirus20x6 
Ths `conda.sh` is located in `/etc/profile.d/`, which means, you should set Bash/Zsh as login shell if you use them.
Try to command `type conda` in your default environment and then in `bash -l` or `zsh -l`

**Comment by marimeireles** [comment]
That's an actual fix for me.

**Comment by specter119** [comment]
@marimeireles @sirus20x6 https://wiki.archlinux.org/index.php/Command-line_shell#Changing_your_default_shell

**Comment by JPUnD** [comment]
Hi I'm also using `python-conda` from the AUR but I'm running Manjaro. After setting my default shell to zsh using `chsh -s /usr/bin/zsh` running `conda activate` still returns:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

Meanwhile running `zsh -l` works as a workaround as I can activate my conda environment.


Unrelated to the issue at hand but I have other problems going on with conda. I managed to create another environment using `conda create class` but after activating into said environment with `conda activate class` running `conda install python` returns:
```
Collecting package metadata (current_repodata.json): failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/pkgs/urls.txt
  uid: 1000
  gid: 1000

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1000:1000 /usr/pkgs/urls.txt

In general, it's not advisable to use 'sudo conda'.
```

However folder `/usr/pkgs` does not exist. The same error happens when trying to remove the current environment with `conda remove class`. 

Running `conda env list` yields:
```
# conda environments:
#
class                    /home/undercover/.conda/envs/class
base                  *  /usr
```

Why is base located in `/usr` and why is it asking for permissions to a file that does not exist? I only want to use conda from my terminal (which is kitty by the way) running `conda activate` on my several projects, so having them all, even base, in my home folder, would be great.

**Comment by specter119** [comment]
@JPUnD login shell again, you may examine your terminal config. You may modify the shell config as `/usr/bin/zsh`, which leads the activate function not working. leave it as default, or `/usr/bin/zsh -l` if you like.

The write permission for `/usr/pkgs/urls.txt` is a real issue of python-conda in some degree, I will submit a fix in recent days. Before that fix, you can add the following contents

```yaml
envs_dirs:
  - ~/.conda/envs
pkgs_dirs:
  - ~/.conda/pkgs
```

to your `~/.condarc` or `~/.conda/condarc` to make create function work.

**Comment by JPUnD** [comment]
I don't think I quite understood what you mean, trying to run `chsh -s /usr/bin/zsh -l` or `chsh -s "/usr/bin/zsh -l"` doesn't work, in the first case it retuns all available shells and in the second case it says `chsh: "/usr/bin/zsh -l" does not exist`.

When it comes to the second part you beat me to it, I had found that exact same workaround and I was going to post it here, my `~.condarc` looks just like that, although I still have an annoying base folder which isn't doing much and I can't delete it:
```
$ conda env list
# conda environments:
#
base                  *  /usr

$ conda activate base

$ (usr) conda install python
NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.

$ (usr) conda deactivate

$ conda env remove --name base
CondaEnvironmentError: cannot remove current environment. deactivate and run conda remove again
```

**Comment by specter119** [comment]
1. you have changed your login shell to zsh, you don't need run `chsh` again. you don't use zsh in the tty, you use it in a 
terminal emulator, try to modify its config, change the shell config into `/usr/bin/zsh -l` if necessary.
1. no need to activate `base`, `base` in python-conda is the system python. therefore, you can't remove it.

**Comment by JPUnD** [comment]
Ah I thought using `chsh` would change the behavior of all terminal emulator. Running `conda activate` after adding the line `shell /usr/bin/zsh -l` in my Kitty terminal worked. 
Thanks!

**Comment by jpmvferreira** [comment]
> The write permission for `/usr/pkgs/urls.txt` is a real issue of python-conda in some degree, I will submit a fix in recent days. 

Is there an ETA on this fix? Because although i can now create a new environment, activate it and arbitrary install packages, which is all i really wanted and this is probably a nitpick, but when using `conda activate`, followed by a tab to trigger auto complete, which has also been installed from the AUR, i get something like:
```
ls: cannot access '/usr//envs': No such file or directory base
```

Otherwise, as i said, everything seems to work great.

**Comment by specter119** [comment]
@jpmvferreira Yeah, I should add a global config to set env and pkg dirs under `~/.conda`.
