### ISSUE TITLE
Does the Miniconda EULA apply to conda itself?

### ISSUE THREAD

**Issue by wking** [conda/conda#979]
With #978, I noticed that Miniconda has an EULA, which seems strange.
I installed conda via pip (see #949), so I didn't see or sign this EULA while
installing.  Skimming through it now, it looks like it says:

* This stuff is all copyrighted by various people, and you're
  licensing it.
* Continuum isn't responsible if any of this breaks your system.
* If you redistribute this or a derivative, you must:
  * Also include this EULA
  * Mention that you're using Anaconda
* Comply with any export restrictions that your country imposes.
* Continuum isn't responsible if any of this breaks your system
  (again, but this time using the BSD phrasing ;).

Everything there except the EULA itself (and EULA-propagation) seems
like standard open-source stuff (which Linux distros generally assume
is clear without stating in an explicit EULA).  So:

* Do we really need an EULA like this?
* If we do, where does it kick in?  After I install conda via pip?
  After I install it via the Miniconda installer?  After I install it
  via an Anaconda (non-mini) installer?

**Comment by csoja** [comment]
The Anaconda & Miniconda license changed in Fall 2015 to a 3-clause BSD license with a few notices: http://docs.continuum.io/anaconda/eula
