### ISSUE TITLE
Conda graphical installation package not installing

### ISSUE THREAD

**Issue by gitgitgat** [conda/conda#9803]
It appears to somewhat install the conda package, although not completely, as it prompts that conda is already installed. The conda graphical installation package reaches the last step(Summary) in the installation and it crashes. 

<img width="622" alt="Screen Shot 2020-03-31 at 16 07 50" src="https://user-images.githubusercontent.com/48162530/78079660-c7426900-7369-11ea-8931-21d4e269a541.png"> 

<img width="431" alt="Screen Shot 2020-03-31 at 16 06 00" src="https://user-images.githubusercontent.com/48162530/78079525-864a5480-7369-11ea-9b4c-f63af038577e.png">

**Comment by kalefranz** [comment]
Apologies for the confusion, but you've filed this issue in the wrong repository. The correct issue tracker is at https://github.com/ContinuumIO/anaconda-issues.
