### ISSUE TITLE
Can't export all jupyter lab extensions via conda export

### ISSUE THREAD

**Issue by CNFeffery** [conda/conda#9804]
I tried to use `conda env export > xxx.yml ` to export a venv contains three jupyter lab extension:
```bash
(geo-spatial) C:\Users\pengz>jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: C:\Conda\envs\geo-spatial\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        @jupyterlab/toc v2.0.0 enabled  ok
        jupyter-matplotlib v0.7.2 enabled  ok

```

but after I tried to create new venv from yaml file, only got `jupyter-matplotlib`:

```
(test) C:\Users\pengz>jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: C:\Conda\envs\test\share\jupyter\lab
        jupyter-matplotlib v0.7.2 enabled  ok

Build recommended, please run `jupyter lab build`:
    jupyter-matplotlib needs to be included in build
```

**Comment by wolfv** [comment]
This is because jupyter lab extensions are _not_ installed as conda packages (but seperately as NPM packages). It's something that needs to be fixed in JuypterLab first.

**Comment by CNFeffery** [comment]
> This is because jupyter lab extensions are _not_ installed as conda packages (but seperately as NPM packages). It's something that needs to be fixed in JuypterLab first.

😢 Thanks a lot, it seems that I have to install extra extensions manually.
