### ISSUE TITLE
Issues facing installing NLTK Package 

### ISSUE THREAD

**Issue by nitinsikri** [conda/conda#9806]
Facing the below issue, please suggest:

>conda search nltk_data
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://anaconda.****:**/gtgold

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

**Comment by kalefranz** [comment]
I recommend following the instructions that were provided in the error message.

```
If the requested url is in fact a valid conda channel, please request that the
channel administrator create noarch/repodata.json and associated
noarch/repodata.json.bz2 files, even if noarch/repodata.json is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
```
