### ISSUE TITLE
How to use old conda environment from another disk

### ISSUE THREAD

**Issue by Master-cai** [conda/conda#9811]
hi everyone, I met a problem that I can\`t use my conda environment.
For some reason, I changed my computer\`s disk and I create many conda environment on that disk. I forgot to export the conda env before I change it. New I can find those env folders. I want to use the old conda environment on that disk(or just export it to a .yml or requirements.txt file). I tried to install a new conda on the new disk to export the env on the old disk, but it can\`t find the environment and didn\`t work. 
How can I do that? It\`s very important to me. Thanks a lot!!!
os: win10

**Comment by mingwandroid** [comment]
This is a place to report bugs, not request help using conda.

Your old environments will be on the old disk, listed in a file in %UserProfile% (i.e. your user directory) called environments.txt
