### ISSUE TITLE
Tie a channel to an environment

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda#982]
This is a feature request.  It would be nice if we could tie an environment to one specific channel (or more channels).  That way one can update the environment freely, without contamination from other channels.

**Comment by JanSchulz** [comment]
https://github.com/conda/conda/blob/d3a76d3a0afbd31358464216a423806bb8e97e4f/conda/api.py#L27

This could be as easy as:

```
...
    if prepend:
        if prefix:
            overwrite = os.path.join(prefix, "conda-meta", "overwrite-channels")
            if os.path.isfile(overwrite):
                 channel_urls += get_channel_urls_from_file(overwrite)
            else:
                 channel_urls += config.get_channel_urls(platform=platform)
...
```

**Comment by ocefpaf** [comment]
This is quite an old issue and I believe it is time to close it. Maybe `conda-env` already have the functionality to better manage channels in env files and I am outdated with the docs. @msarahan I would love to hear your comments.

**Comment by kalefranz** [comment]
Actually, this you can now do fairly easily.  Add a `.condarc` file to the `CONDA_PREFIX` of the environment you want to add the channel to.

**Comment by ocefpaf** [comment]
> Actually, this you can now do fairly easily

Thanks @kalefranz. Did not know that was possible. However, I do not think it is  fairly easily for most users to handle a `.condarc` file  in the `CONDA_PREFIX`. It would be nice to have a higher CLI interface to handle that.
