### ISSUE TITLE
Setting env vars via env_vars.bat doesn't work

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda/conda#9820]
Following [these](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#windows) instructions, my `my_env/etc/conda/activate.d/env_vars.bat` reads `ABC='123'`, and `deactivate.d`'s is `ABC=`. Yet, `conda env config vars list`, after `conda activate my_env`, shows no output. I'm using latest `conda --version == 4.8.3`.

I see an output if using `conda env config vars set ABC='123'`, so `vars list` either fails to detect env vars set via the .bat, or they're never set in the first place. Which of the two is it - and how can I set (and view) environment variables upon `conda activate my_env`?

**Comment by saguerraty** [comment]
Any update on this issue? I am having the same with conda 4.8.4 
If I do: `echo $var_name` it will print out my variable, but it wont list it under config vars list, also I can´t access the variables within python from the OS package using `os.environ.get('var_name')`, I get None as an output

**Comment by HDRah** [comment]
I suffer the same problem, any updates here?

**Comment by kielc** [comment]
I ran into an issue when setting environment using `conda env vars set`. It works for variable names that are in all caps but if the variable is in lower case letter it doesn't get set. The lower case named variable shows up in `conda env vars list` but cannot be accessed through the shell `echo $var_name` or `os.environ['var_name']`.

**Comment by OverLordGoldDragon** [comment]
Not stale.

**Comment by metasim** [comment]
Still not stale.

**Comment by kenodegard** [comment]
While the documentation's way of setting/unsetting environment variables will work it is incompatible with seeing the variables in `conda env config vars list`.

Please use the `conda env config vars [set|unset]` command to correctly set/unset your environment variables from your environments. These variables are actually being configured via a `state` file in the environment's `conda-meta` directory.

**Comment by bartosz-bear** [comment]
I don't think this issue was resolved.

If the proper way to set environment variable on `conda activate` is to use `conda env config vars [set|unset|' then the documentation should be updated instead of officially suggesting a solution which doesn't work.
