### ISSUE TITLE
Add env vars in enviroment.yml

### ISSUE THREAD

**Issue by fernandolkf** [conda/conda#9821]
Hi there!

I have a problem that could be transformed into a feature (like all problems in the world).

Well, I have a project divided in research and prod, so I also have two environment files. As I need to set the root path for a shared library code, I use conda vars. The main problem is that I have to first create my environment and then set the var.

Something like first

`conda create -f enviroment.yml`

and then

`conda env config vars set SOME_VAR=VALUE`

So I think it could be helpful if we can use the environment.yaml for not only dependencies but also setting environment variables. Something like 

```
name: some_environment
channels:
  - defaults
dependencies:
  - some_package
  - pip:
    - some_pip_package==1.0.0
vars:
  - SOME_VAR=VALUE
prefix: /env_path/
```

So when sharing a conda environment, one could also share all env variables needed to the project.

It makes sense? Sorry if it was already discussed but i didn't find.

**Comment by fernandolkf** [comment]
@marcelotrevisani here

**Comment by marcelotrevisani** [comment]
related to https://github.com/conda/conda/issues/6649

**Comment by marcelotrevisani** [comment]
@msarahan , I'm not sure, but I think it was discussed this thing
I do not remember the outcome of the discussion

**Comment by marcelotrevisani** [comment]
alternatively you can use ``conda devenv`` : https://github.com/ESSS/conda-devenv
