### ISSUE TITLE
conda install -c anaconda tensorflow-gpu

### ISSUE THREAD

**Issue by AlbinDavid** [conda/conda#9822]
Os:linux 18.04
Installs version 1.10.0 but the latest version is not installing
Version needed to be installed 2.1.0
conda install -c anaconda tensorflow-gpu==2.1.0 not running

**Comment by kalefranz** [comment]
When you file a bug report, there is a detailed issue template. It's important that you provide the requested information so that we can help you with your problem.

https://github.com/conda/conda/issues/new?template=Bug_report.md
