### ISSUE TITLE
conda create & update does not work.. help

### ISSUE THREAD

**Issue by woonggeol** [conda/conda#9824]
## Current Behavior

hello.. i want to make conda env, but it did not work since when..
so i erased anaconda and laid back,
and that message pop up like "conda update -n base -c defaults conda"
i entered, but update did not working..
why..? help

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/63088233/78849528-a7890000-7a4f-11ea-9cc1-f94547119495.png)
```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
![image](https://user-images.githubusercontent.com/63088233/78849785-680ee380-7a50-11ea-90d8-0e9f6f6766da.png)
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
![image](https://user-images.githubusercontent.com/63088233/78849868-a2788080-7a50-11ea-9f54-b5c0cc2833b9.png)

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
Can you provide the output of those commands with `-vvv` also included? So, for example,

```
conda create -n hong35 python=3.5 -vvv
```
