### ISSUE TITLE
any idea when conda is going to work properly again?

### ISSUE THREAD

**Issue by miramar-labs** [conda/conda#9825]
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done

from here it can go two ways ... HUGE delay or, some sort of analysis .. which is incredibly slow and ends up crashing ...

I'm doing containerized builds and the problem seems intermittent .. sometimes it will get through .. sometimes it won't ... 

all the time these days ..

**Comment by mingwandroid** [comment]
You neglected to fill in the asked for info so in closing this. I'll reopen it if you provide that info and reduce the snark.

**Comment by JivanRoquet** [comment]
@mingwandroid sorry but the "snark" is kind of understandable here.

your "asked for info" is kind of annoying and cumbersome to obtain and provide, and people have something else to do, after having waited 4 entire flippin' days for conda to "solve environment", than to take any more of their time to fill a friggin' detailed bug report.

your should be thankful to @miramar-labs to have been gentle enough to open an issue. most people would have simply silentely grumbled their way out and then taken extreme care to keep as far away from anything conda-related as possible for the rest of their life, and you wouldn't even know.

**Comment by JivanRoquet** [comment]
update: on my side, I'm very happy to find out that the stuff I need provides an alternative docker installation, which allows me to completely bypass conda, which has two advantages:

- not having to wait weeks for conda to "solve environment" anymore
- not having to hear conda's maintainers complaining about users not filing issue templates correctly

hoping to stay as far away from conda as possible for the foreseeable future

**Comment by miramar-labs** [comment]
yeah at this point i'm using pip wherever i can and avoiding conda at all costs - it's unusable 
not sure why these things are not caught in testing as they are so easy to reproduce
