### ISSUE TITLE
Updates of LIBPATH/PATH done in deactivation scripts are being cancelled

### ISSUE THREAD

**Issue by sh2ka** [conda/conda#9831]
This happens due to that Activator object sets LIBPATH/PATH to constant strings right after deactivation scripts from deactivate.d were executed. But we set/reset parts in LIBPATH/PATH in activation/deactivation scripts. 

It is expected to have:
_conda_remove_path_from_list() {
    local path_list_var="$1"
    local path="$2"
    # here some stuff to remove the specified path from the list
    # path_list_var is ${!path_list_var} here
    export ${!path_list_var}
}

_conda_deactivate() {
    ...
    _conda_remove_path_from_list LIBPATH "$CONDA_PREFIX"
    ...
}

Instead of just
export LIBPATH=<some fixed string generated by Activator object>

because that fixed string is being generated before deactivation scripts has been executed where LIBPATH/PATH were not affected by them.

Note that CONDA_PREFIX and other variables should be unset only after the LIBPATH/PATH were updated, because _conda_remove_path_from_list uses that variable.

**Comment by msviridov-rocket** [comment]
Additionally, when we remove a package that has activation/deactivation scripts we probably expect that deactivation script is executed for that package prior to its removal.
