### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/noarch/repodata.json> Elapsed: -

### ISSUE THREAD

**Issue by aamirk5** [conda/conda#9837]
Hello, I reinstall anaconda.. but still i'm getting same problem...
conda install 
conda search 
conda update
by these commands i'm getting this error...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda/noarch/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CD1FB0E7F0>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))",),)

A reportable application error has occurred. Conda has prepared the above report.
Upload successful.

(base) C:\Windows\system32>conda config --set ssl_verify no

(base) C:\Windows\system32>conda install pandas
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ C:\Users\Aamir\Anaconda3\Scripts\conda install pandas`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Aamir\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Aamir\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Aamir\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Aamir\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
                 HOMEPATH=\Users\Aamir
          MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\Aamir\Anaconda3;C:\Users\Aamir\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\Aamir\Anaconda3\Library\usr\bin;C:\Users\Aamir\Anaconda3\Li
                          brary\bin;C:\Users\Aamir\Anaconda3\Scripts;C:\Users\Aamir\Anaconda3\bi
                          n;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
                          UDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
                          bem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\Op
                          enSSH\;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2019.1\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program
                          Files\Git\cmd;F:\sdk\flutter\bin;F:\sdk\AndroidSDK\platform-
                          tools;C:\Program Files\Microsoft VS Code\bin;F:\cmder\bin;C:\Program F
                          iles\opencv\build\bin;C:\Users\Aamir\Anaconda3;C:\Users\Aamir\Anaconda
                          3\Library\mingw-w64\bin;C:\Users\Aamir\Anaconda3\Library\usr\bin;C:\Us
                          ers\Aamir\Anaconda3\Library\bin;C:\Users\Aamir\Anaconda3\Scripts;C:\Us
                          ers\Aamir\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Aamir\Anaconda3
            shell level : 1
       user config file : C:\Users\Aamir\.condarc
 populated config files : C:\Users\Aamir\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\Aamir\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/win-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Aamir\Anaconda3\pkgs
                          C:\Users\Aamir\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Aamir\Anaconda3\envs
                          C:\Users\Aamir\AppData\Local\conda\conda\envs
                          C:\Users\Aamir\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda/noarch/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000281F07634A8>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))",),)

A reportable application error has occurred. Conda has prepared the above report.
Upload successful.

(base) C:\Windows\system32>conda update openssl ca-certificates certifi
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ C:\Users\Aamir\Anaconda3\Scripts\conda update openssl ca-certificates certifi`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Aamir\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Aamir\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Aamir\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Aamir\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
                 HOMEPATH=\Users\Aamir
          MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\Aamir\Anaconda3;C:\Users\Aamir\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\Aamir\Anaconda3\Library\usr\bin;C:\Users\Aamir\Anaconda3\Li
                          brary\bin;C:\Users\Aamir\Anaconda3\Scripts;C:\Users\Aamir\Anaconda3\bi
                          n;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
                          UDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
                          bem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\Op
                          enSSH\;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2019.1\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program
                          Files\Git\cmd;F:\sdk\flutter\bin;F:\sdk\AndroidSDK\platform-
                          tools;C:\Program Files\Microsoft VS Code\bin;F:\cmder\bin;C:\Program F
                          iles\opencv\build\bin;C:\Users\Aamir\Anaconda3;C:\Users\Aamir\Anaconda
                          3\Library\mingw-w64\bin;C:\Users\Aamir\Anaconda3\Library\usr\bin;C:\Us
                          ers\Aamir\Anaconda3\Library\bin;C:\Users\Aamir\Anaconda3\Scripts;C:\Us
                          ers\Aamir\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Aamir\Anaconda3
            shell level : 1
       user config file : C:\Users\Aamir\.condarc
 populated config files : C:\Users\Aamir\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\Aamir\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/win-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Aamir\Anaconda3\pkgs
                          C:\Users\Aamir\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Aamir\Anaconda3\envs
                          C:\Users\Aamir\AppData\Local\conda\conda\envs
                          C:\Users\Aamir\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda/noarch/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000266483E9080>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))",),)

**Comment by rabahFr** [comment]
I have the same problem when I do:

> conda install tensorflow-gpu

uninstall reinstall doesn't solve the issue. Seems like the download is taking ages.

**Comment by aamirk5** [comment]
It was because of some automatically installed malware. I removed those then it was fine... Adware antivirus, web companion.. these were malware in my system.
Check also operating operating system firewall could be making problem.
