### ISSUE TITLE
Support read-only home directory on Linux

### ISSUE THREAD

**Issue by gdonval** [conda/conda#9839]
The location of `~/.conda/environments.xml` is hardcoded. As far as I can tell, whether it is written or not does not change anything and I would suggest it is completely removed.

If it is required for anything, please use the actual config location (as set in system-wide config files), not that hardcoded value.

**Comment by mingwandroid** [comment]
The *point* of it is exactly that, to be metainfo about all the conda envs on your machine and that's why it is where it is.

Personally I consider it a mis-feature though!
