### ISSUE TITLE
conda internal error in determine_constricting_specs

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#9845]
## Current Behavior
The OSX CI build for a CF feedstock is triggering an internal IndexError in `determine_constricting_specs`:
https://github.com/conda/conda/blob/f4d8ae9f4577008deddf4eb8be52e0abbacf475a/conda/core/solve.py#L313-L317
![image](https://user-images.githubusercontent.com/881019/79281451-1524a880-7ef6-11ea-84f6-864472be79c9.png)

## Environment Information
From the CI:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=144200&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=440efe7f-b653-584f-d64c-a3a7ab135523
```
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
channel_sources:
- conda-forge,defaults
CI:
- azure


     active environment : base
    active env location : /usr/local/miniconda
            shell level : 1
       user config file : /Users/runner/.condarc
 populated config files : /Users/runner/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /usr/local/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda/pkgs
                          /Users/runner/.conda/pkgs
       envs directories : /usr/local/miniconda/envs
                          /Users/runner/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

==> /Users/runner/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
channels:
  - conda-forge
  - defaults
show_channel_urls: True
```

**Comment by dhirschfeld** [comment]
Sorry, not much to go on but I'm not sure how to get more info since it's on CI & I don't have a Mac to test on :/

I figured it was better to mention it than not though.

**Comment by dhirschfeld** [comment]
It seems that this is a condition that *shouldn't* occur? i.e. some other problem is triggering this problem but because of this problem, it's impossible to debug the original issue. In that case, perhaps the only thing to do would be to guard against this with a more informative error message - e.g.
```python
matching_versions = [
    VersionOrder(sp.version)
    for sp in solution_precs
    if sp.name == spec.name
]
if not matching_versions:
    all_versions = {
        sp.name: sp.version for sp in solution_precs
    }
    msg = "No matching versions found!\n"
    msg += f"spec.name = {spec.name}\n"
    msg += f"all_versions = {all_versions!r}"
    raise RuntimeError(msg)
else:
    highest_version = matching_versions[0]
```

**Comment by dhirschfeld** [comment]
The build worked fine with 4.7.5 which predates the changes in https://github.com/conda/conda/pull/8899

**Comment by rluria14** [comment]
I emphasize a need to correct this issue as it presents an overarching osx build error to the 70+ `terraform-provider-*-feedstocks`

**Comment by rluria14** [comment]
Ping @jjhelmus @msarahan

**Comment by dhirschfeld** [comment]
From @sodre on [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5e98e7b4a1284c4f20954e94):
> *on a separate topic… I think I found the root of the problem on OSX. The newer compilers have a `__osx constraint`, and I think that is what is causing the solver to break.*
>
> *Obviously, the issue is that conda-forge is building for MacOS 10.9 and that has not been supported by golang since version 1.10.*

**Comment by dhirschfeld** [comment]
I guess that raises the question of whether `conda-forge` need to support such an ancient OS.

![image](https://user-images.githubusercontent.com/881019/79516371-8bf4a980-808e-11ea-8112-26a1e4fb6bf2.png)

**Comment by jakirkham** [comment]
It's possible to [use a newer macOS version]( https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks ) in your feedstock.

**Comment by dhirschfeld** [comment]
Thanks @jakirkham - since 10.12 is out of support already I'm inclined to bump the minimum OSX version to 10.13

**Comment by jakirkham** [comment]
Where did you find that table btw?

**Comment by dhirschfeld** [comment]
Just from Wikipedia:
https://en.wikipedia.org/wiki/MacOS_version_history

**Comment by jakirkham** [comment]
Interesting. I don't recall Apple actually releasing EOL information on OS versions. So not sure where that information comes from.

**Comment by dhirschfeld** [comment]
Looks like the `MACOSX_DEPLOYMENT_TARGET` trick didn't work:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=145733&view=logs&j=c572e5d5-7ba7-55ce-5575-7ce1d9f7161e&t=fe245b22-2f08-5a76-43b2-e02a18e3fefa&l=123

...and it appears that `10.13` *should* have worked:
![image](https://user-images.githubusercontent.com/881019/79569460-f6433380-80fa-11ea-84ba-22d407440836.png)

**Comment by jakirkham** [comment]
Can we please move this to a feedstock issue or PR?

**Comment by sodre** [comment]
At @jakirkham request, moving this discussion to conda-forge/go-feedstock#78.
