### ISSUE TITLE
Request: don't issue clobber warnings / errors for identical files

### ISSUE THREAD

**Issue by teake** [conda/conda#9849]
I've recently run into an issue where an identical file is packaged into separate packages. (conda-forge/jaraco.collections-feedstock#4 and jaraco/jaraco.collections#6). This is of course not a very big problem, but ideally I would like conda to not raise a clobber warning / error in these cases.

Would it be feasible to compare file hashes before doing the clobber check, and suppress the clobber warning if the files are identical?

**Comment by mingwandroid** [comment]
I am afraid having identical files is a big problem for conda. It uses reference counted hardlinks. This breaks that.

**Comment by teake** [comment]
That's quick and clear, thanks!
