### ISSUE TITLE
Add tab completion for zsh

### ISSUE THREAD

**Issue by pzwang** [conda/conda#985]
A user has emailed us requesting addition of tab completion for zsh as well, using e.g. https://pypi.python.org/pypi/genzshcomp/

**Comment by esc** [comment]
If anyone is still watching this thread, I have just announced a v0.1 of a zsh completion for conda: https://groups.google.com/a/continuum.io/forum/#!topic/conda/21gvhqIec9M

**Comment by Januzz** [comment]
Great, thank you!

**Comment by jezdez** [comment]
Hey all, @esc asked me to make sure everyone is aware of the implementation in https://github.com/esc/conda-zsh-completion that works as expected.
