### ISSUE TITLE
Windows Error ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by zapaishchykova** [conda/conda#9852]
Hi! 
I am using Windows 10 and had previously installed and working Python 3.7.7. When I now try to install Miniconda\Anaconda, it throws me an error:
```
  File "D:\Installed\miniconda\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
Could not find any working solution for that on the internet. Please help!

**Comment by zapaishchykova** [comment]
After few more hours i finally found a solution here https://github.com/ContinuumIO/anaconda-issues/issues/9927
TLDL : delete PYTHONPATH and PYTHONHOME in your system and user variables

**Comment by WeihengXia0123** [comment]
Thanks! Delete the exitsting PYTHONPATH and PYTHONHOME works perfect for me!

**Comment by leonpolak** [comment]
You are my personal savior.
