### ISSUE TITLE
UnavailableInvalidChannel: The channel is not accessible or is invalid.   channel name: conda-win-64

### ISSUE THREAD

**Issue by badi3-zz** [conda/conda#9856]
Hello,

Please note that I'm using Windows 10 and Anaconda to install opencv.

while trying to install opencv, I got the following error:
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: conda-win-64
  channel url: https://conda.anaconda.org/conda-win-64
  error code: 404

What's the problem ?

**Comment by angloyna** [comment]
Hi,

I don't think I see a channel named conda-win-64 on anaconda.org. Can you give an example of the command you ran to install opencv?

**Comment by badi3-zz** [comment]
Hi,
It's not related to opencv installation but for any installation. 
Thé command was conda install opencv

**Comment by mingwandroid** [comment]
Please fill in the questions asked of you in the template, otherwise we cannot help you. If you do that, I will reopen this bug report. Thanks.
