### ISSUE TITLE
After execute 'conda update setuptools', my conda can't use

### ISSUE THREAD

**Issue by lslynf** [conda/conda#9860]
when I executed the command 'conda update setuptools', whenever I used conda xxx, there is a error like:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/conda", line 22, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
I have checked my .bashrc file, the conda PATH is right, I can't use conda xxx again

**Comment by kalefranz** [comment]
Can you please share the contents of `/home/user/anaconda3/conda-meta/history`. It might be long, but that’s ok. It should really help us understand how this happened.

**Comment by lslynf** [comment]
> Can you please share the contents of `/home/user/anaconda3/conda-meta/history`. It might be long, but that’s ok. It should really help us understand how this happened.

Thanks a lot! I have uploaded the file

[history.txt](https://github.com/conda/conda/files/4500989/history.txt)
