### ISSUE TITLE
conda activate fails in windows powershell

### ISSUE THREAD

**Issue by SSmarshal** [conda/conda#9861]
## Current Behavior

     Conda activate xxx fails:CommandNotFoundError
     
![image](https://user-images.githubusercontent.com/46676996/79731136-6b458180-8324-11ea-88ec-e9d95c84f255.png)

### Steps to Reproduce

```
I run conda init powershell and it is done, and then I run conda activate xxx fails
```

## Expected Behavior

The environment is activated properly

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
conda version: 4.8.3
system: windows 10
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by SSmarshal** [comment]
I am sorry but I have to make it clear that everything is ok in anaconda prompt powershell, jupyter notebook is just fine and I have worked with it for quite a long time, however, when I use VScode to open one of my file generated by the jupter notebook, it says Jupyter server is not connected and no kernel. And the error report shows the command conda activate is not found in powershell

**Comment by kalefranz** [comment]
Did you close and re-open your shell after running `conda init powershell`?

**Comment by SSmarshal** [comment]
Yes, but there is still something wrong
----- 原始邮件 -----
发件人：Kale Franz <notifications@github.com>
收件人：conda/conda <conda@noreply.github.com>
抄送人：SSmarshal <chenzelong2000@sina.com>,  Author <author@noreply.github.com>
主题：Re: [conda/conda] conda activate fails in windows powershell (#9861)
日期：2020年04月29日 22点51分


Did you close and re-open your shell after running conda init powershell?

&mdash;
