### ISSUE TITLE
Cannot Install RStudio within GUI Navigator nor with Powershell Prompt

### ISSUE THREAD

**Issue by BeyondAntares** [conda/conda#9865]
## Current Behavior

 On a fresh install on a brand new PC, Installed Anaconda 2020.02 v1.19.12 64bit edition

Within the navigator, I cannot install RStudio, as it is constantly loading with the bottom pane showing: Installing application rstudio on _Filepath_

The loading indicator never completes and is shown indefinitely

no logs appear under the Help menu.
 
### Steps to Reproduce
I then tried through Conda Prompt

`conda install -c r rstudio`

which never resolved, showing the following errors:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
```
then tried installing it via a different environment:

`conda create --name rstudio_env -c r rstudio`

Then tried
conda create --name rstudio_env -c r rstudio

Which failed to resolve providing the following
```
conda create --name rstudio_env -c r rstudio
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
```

The environment hasn't been resolve after an hour

I have gone into a Windows firewall settings (which has worked for pip installs) to enable pythonw.exe and anaconda_navigatorscript.py in the acceptable app list. 

## Expected Behavior

RStudio installs within Navigator or through Anaconda Prompt.

**Comment by rw31415** [comment]
I have the exact same issue. Is it still a unresolved bug ?
