### ISSUE TITLE
Use custom python interpreter and packages within base and other environments

### ISSUE THREAD

**Issue by donpellegrino** [conda/conda#9866]
It would be useful if conda would recognize and use a custom, locally installed, python interpreter and its associated packages. Note that this is distinct from the conda create --use-local argument. Conda currently requires a packaged "python" from a channel. This could be the local channel or a remote one. However, it does not account for a custom build of Python that is already present on the system, which is not distributed via a conda channel.

It would be a useful capability if conda recognized a preexisting python interpreter in the PATH, and packages available to it, as available to use and fulfill requirements in the conda environments, including base.

For background see this relevant "[Using a custom Python Interpreter in a miniconda3 environment](https://groups.google.com/a/continuum.io/d/topic/anaconda/9_hYE6lPfCE/discussion)" thread in the "Anaconda - Public" forum.

Test system: conda 4.6.14, Linux

**Comment by mingwandroid** [comment]
Those interpreters are unlikely to work well with our packages. Does that matter?

**Comment by donpellegrino** [comment]
@mingwandroid, I am not sure if that matters in the general case. My thinking is that if there is a locally installed python interpreter, it could be interrogated with --version, and inventoried as a sort of virtual package fulfilling requirements for a python at that release level. If another package requires a different version, than the locally installed python would simply not qualify as fulfilling that package's requirements.

For binary incompatibilities, perhaps the way Intel has packaged [intelpython](https://anaconda.org/intel/intelpython) could be used as an example. One candidate implementation of this feature might be to treat a locally installed python as a package with the same relationship as intelpython would have to other packages.

**Comment by mingwandroid** [comment]
I didn't know that intelpython can work with any python interpreter. Can you send me some links so I can read about it?

**Comment by kalefranz** [comment]
Why should python be a special case though? Why not a custom r interpreter? Or a custom libxml2 that’s already on the system?

**Comment by donpellegrino** [comment]
@mingwandroid, see the [Intel Distribution for Python](https://software.intel.com/en-us/distribution-for-python) home page. In particular, note that their custom built binary of Python is distributed via their [Intel Channel](https://anaconda.org/intel).

@kalefranz, the scope could certainly expand to include R and other interpreters, as well packages. Most broadly, the enhancement could be to simply use stuff that is already there if it can be used to fulfill a dependency.

**Comment by mingwandroid** [comment]
@donpellegrino, you didn't show me where I can find out how to use my system Python with IDP. That's specifically what I want to look at.

**Comment by donpellegrino** [comment]
@mingwandroid, sorry if I was unclear. I don't believe you can use your system Python with IDP, or conda. Rather, you can use IDP as a packaged custom interpreter with conda. Therefore, a possible approach for implementing this issue might be to see if a local system python could play a role in conda's environment analogous to how IDP packages Python for a conda environment. IDP's approach would be an example that addresses the earlier concern:

"Those interpreters are unlikely to work well with our packages. Does that matter?"

**Comment by mingwandroid** [comment]
The reason that IDP interoperates well with the conda ecosystem is because they are built in that ecosystem in order to be compatible with it.

What you are asking for will just not work for technical ABI, software and distribution construction reasons.
