### ISSUE TITLE
Conda keeps updating to 4.8.3 and then complaining it can't find conda 4.8.1 ...

### ISSUE THREAD

**Issue by raphaeljolivet** [conda/conda#9869]
I've got a fresh install of **jupyterhub** (python 3.7, conda 4.8.1).

###  Conda keeps updating and then complaining

I've installed **_pandas_** on it and it automatically updated conda to **4.8.3**  ( --freeze-installed seemed to have no effect).

Then, whenever I try to install something, it complained about :
    **ResolvePackageNotFound**:
      - conda=4.8.1

Which lead me to rollback to conda=4.8.1 each time I install anything.
It seems like a bug to me.

**Comment by mfaafm** [comment]
Executing `conda install --no-update-deps tini` in a `continuum/miniconda:4.8.2` docker image also unexpectedly updated conda to 4.8.3 for me.
