### ISSUE TITLE
anaconda virtual environment setup error

### ISSUE THREAD

**Issue by RishiKasam** [conda/conda#9874]
Hello,
I am pretty new to the concept of tensorflow and usage of python and anaconda, so I've tried to create a virtual environment for tensorflow. At the end, this is what i got . I am attaching a screenshot below.
Please guide me 
Thanks
![Screenshot (75)](https://user-images.githubusercontent.com/64210980/80111319-5f182900-859d-11ea-97da-0118d098e610.png)

**Comment by kalefranz** [comment]
Could you please give the step-by-step instructions to reproduce your issue?

**Comment by kalefranz** [comment]
Likely a duplicate of https://github.com/conda/conda/issues/9798
