### ISSUE TITLE
Allow channel name to be part of the package name spec

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#988]
For example, to install the `gulp` package from the `javascript` channel on binstar, you would specify the dependency like this:

```
javascript/gulp
# or
https://conda.binstar.org/javascript/gulp
```

If you required a channel other than `main` (the default channel for binstar), you could specify it like this:

```
https://conda.binstar.org/javascript/channel/dev/gulp
```

**Comment by csoja** [comment]
@asmeurer this one is listed as "in progress" but looks like there hasn't been any activity in months.

**Comment by asmeurer** [comment]
It is in progress in the sense that there is a work in progress pull request. I haven't really been actively using that label for a while now, though.

**Comment by mattions** [comment]
tracking this as well.

**Comment by tetianakh** [comment]
Any progress on this issue?

**Comment by pdemarti** [comment]
Is there any documentation and examples on this new (and much appreciated) feature?
What is the format by which one may specify a channel for a dependency?

**Comment by kalefranz** [comment]
It's in the 4.4.x feature release branch, but there's not yet a 4.4.0 release available. Still working on tying up a few remaining issues. Getting the documentation done is one of them.

**Comment by pdemarti** [comment]
awesome -- thanks.

**Comment by wtgee** [comment]
Any update on how to accomplish this? I can't find anything in the docs.

**Comment by peschue** [comment]
I also found the possibility to add channel::package as requirement.

But if the channel is not registered, a not very helpful failure message occurs.

> $ conda install -c (my channel) (my package)
> PackagesNotFoundError:  The following packages are not available from current channels:
>  (my package)
>  (dependency in custom channel X)

If referring to a channel in a dependency means, that this channel must be manually added anyways, it does not make much sense to be able to refer to a channel.

I think the "install" command should either execute "$conda install -c (channel X) (dependency)" automatically.

**Comment by pdemarti** [comment]
Bumping this. Is there any realistic plan to implement this feature which was requested in 2014?

**Comment by kalefranz** [comment]
@peschue If you'r still having a problem with the latest conda version, please file a new issue.

@pdemarti This is the conda repo, not the conda-build repo.  There are ample tests for this.  It may likely sneak through if you start using it for dependency specs in meta.yaml.  Also, if we start to see this being used for run-time requirements, we'll probably make an explicit patch to conda-build to disallow it.  I don't see there being an issue for it to appear in build requirements though.  For further discussion, that would mean opening a new issue in the conda-build repo (after searching the conda-build issue tracker to ensure an open issue doesn't already exist).

**Comment by vladsaveliev** [comment]
Are there any docs for this feature? Not clear about the usage.

**Comment by certik** [comment]
I couldn't find docs, but from the PR that closed this issue, you can see the tests:

https://github.com/conda/conda/pull/5365/files#diff-53a73babc8997d224838912343c93a0aR176

and so from it it would look like you can specify the channel with the package name as `numpy[channel=conda-forge]` in `meta.yaml`. But I tried it and I get an error "Error: Invalid selector in meta.yaml line 17:". So I don't know.

**Comment by jonathaneichelberger** [comment]
@certik The issue is with the brackets. You can either wrap it in quotes (`'numpy[channel=conda-forge]'`) or you can specify it in a slightly alternate manner: `conda-forge::numpy`. Unfortunately, this new type of package specification doesn't really work with `conda build`, only with `conda install`. To clarify, if the channel you specify for a package is not listed in the channel URLs of `conda info`, then it doesn't know where to find the package, and fails with unsatisfiable dependecy errors – which tells me `conda build` is not yet configured to completely handle the channel property for this new type of package specification.

**Comment by ihnorton** [comment]
See comment about current status (Aug 2018) on the related conda-build issue:

https://github.com/conda/conda-build/issues/532#issuecomment-410244068
