### ISSUE TITLE
"which conda"  command is not working

### ISSUE THREAD

**Issue by gakabani** [conda/conda#9883]
I just recently installed conda and saw changes on my zshell command-line interface. A bug I observed is below, the command which conda does not provide a correct description of the conda package.

(base)MacBook-Pro-2017-i7 ~ % **which conda**
conda () {
	if [ "$#" -lt 1 ]
	then
		"$CONDA_EXE" $_CE_M $_CE_CONDA
	else
		\local cmd="$1"
		shift
		case "$cmd" in
			(activate | deactivate) __conda_activate "$cmd" "$@" ;;
			(install | update | upgrade | remove | uninstall) CONDA_INTERNAL_OLDPATH="${PATH}" 
				__add_sys_prefix_to_path
				"$CONDA_EXE" $_CE_M $_CE_CONDA "$cmd" "$@"
				\local t1=$?
				PATH="${CONDA_INTERNAL_OLDPATH}" 
				if [ $t1 = 0 ]
				then
					__conda_reactivate
				else
					return $t1
				fi ;;
			(*) CONDA_INTERNAL_OLDPATH="${PATH}" 
				__add_sys_prefix_to_path
				"$CONDA_EXE" $_CE_M $_CE_CONDA "$cmd" "$@"
				\local t1=$?
				PATH="${CONDA_INTERNAL_OLDPATH}" 
				return $t1 ;;
		esac
	fi
}

**Comment by kalefranz** [comment]
Zsh `whence -p` is equivalent to `which` in bash. `conda` is a shell function to enable `conda activate` and `conda deactivate` commands. This is by design.
