### ISSUE TITLE
Latest repodata.json causes issues with pip / libffi.so.6

### ISSUE THREAD

**Issue by SSchott** [conda/conda#9884]
## Current Behavior

Under OpenSuse 42.3, latest Miniconda fails to update properly, causing:

`The following packages will be REMOVED:

  pip-19.3.1-py27_0
  wheel-0.33.6-py27_0`

And at the end:
`ImportError: libffi.so.6: cannot open shared object file: No such file or directory`

### Steps to Reproduce

```
./Miniconda2-latest-Linux-x86_64.sh
......
./conda update conda -y
./conda install pip
```

## Expected Behavior

This happens after the latest change in repodata.json. I guess there is the problem. It worked before last Thursday 23.04.2020

**Comment by kalefranz** [comment]
CC @mingwandroid

**Comment by ruanima** [comment]
same issues with miniconda

**Comment by ruanima** [comment]
use base env can bypass this problem.
