### ISSUE TITLE
conda creates environment at wrong location

### ISSUE THREAD

**Issue by Hoeze** [conda/conda#9885]
Hi, I got an problem that conda chooses the home folder as environment location instead of the system-wide one. 
However, the environment paths are correctly setup to have the system-wide one as top priority and the user is able to write to this location:
```
# conda creates env in home dir:
conda create --name asdf
# conda creates env in correct location:
conda create --prefix /opt/anaconda/envs/asdf
```

Is there a possibility to determine why conda chooses the wrong location?
Maybe there is an error in the permission determination?

## Current Behavior
`conda create` creates environment in user home

### Steps to Reproduce
```
sudo chown :users /opt/anaconda/envs
# conda creates env in home dir:
conda create --name asdf
# conda creates env in correct location:
conda create --prefix /opt/anaconda/envs/asdf
```

## Expected Behavior
conda creates environment in /opt/anaconda/envs

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/<user>/.condarc
 populated config files : /opt/anaconda/3-2019.10/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /opt/anaconda/3-2019.10  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/plotly/linux-64
                          https://conda.anaconda.org/plotly/noarch
          package cache : /opt/anaconda/3-2019.10/pkgs
                          /home/<user>/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/<user>/.conda/envs
                          /opt/anaconda/3-2019.10/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/3.10.0-1062.9.1.el7.x86_64 scientific/7.7 glibc/2.17
                UID:GID : 9209:500000 (<user_id>:users)
             netrc file : None
           offline mode : False

```
</p></details>

**Comment by kalefranz** [comment]
Conda is determining that it doesn't have write access to `/opt/anaconda/envs`, so it has to fall back to `/home/<user>/.conda/envs`.  If you want to dig in a little, the code paths being used here are https://github.com/conda/conda/blob/4.8.3/conda/base/context.py#L1437-L1513

**Comment by Hoeze** [comment]
Thank you for your answer @kalefranz.
I'll try to see if I can find a way how to debug this.
However, it would be nice to have some debug message like "Prefix <...> was skipped because write test failed on path <...>" when running `conda --debug`.
