### ISSUE TITLE
Multiuser conf based on symbolic link to conda.sh in /etc/profile.d is not working

### ISSUE THREAD

**Issue by mick-d** [conda/conda#9895]
## Current Behavior

I am setting up a multiuser miniconda environment on Ubuntu linux. To store packages (and envs) I would like a "root" read-only location (as a safety measure) and a "shared" read/write location (to avoid storing the same packages installed multiple times by different users). For this purpose I installed miniconda at `/opt/conda/root`, and created `/opt/conda/shared`. 

Now i would like to setup what is necessary for users to use conda by only manipulating global configuration files (like `/etc/profile`) and without touching any personal `.bashrc`. According to conda documention i was expecting it would take only two steps:
1. Add the following to `/etc/profile`:
```
export CONDA_PKGS_DIRS="/opt/conda/shared/pkgs","/opt/conda/root/pkgs","/home/$USER/.conda/pkgs"
export CONDA_ENVS_DIRS="/home/$USER/.conda/envs":"/opt/conda/shared/envs" 
```
2. Issue the following command once (for users to automatically source the conda initialization script)
```
sudo ln -s /opt/conda/root/etc/profile.d/conda.sh /etc/profile.d/conda.sh
```
Step 1 is fine. However step 2 does not do the job: after logging in as a user, `conda` is not in the path (and just adding it to the path by updating the `PATH` variable would just create other issues).

I found out that it doesn't work because sourcing the conda initialization script `conda.sh` doesn't work: `source "/etc/profile.d/conda.sh"` (or `.  "/etc/profile.d/conda.sh"`) will not work, and neither will `source "/opt/conda/root/etc/profile.d/conda.sh"`

For conda to work for a given user, it is necessary to issue the following command after logging is as that user (inspired from result of `conda init` found in `.bashrc`):
```
__conda_setup="$('/opt/conda/root/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
eval "$__conda_setup"
```
So i found myself having to set all users' `.bashrc` to having the output of `conda init` (i.e. exactly what i wanted to avoid, and completely contrary to the conda documentation):
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/conda/root/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/conda/root/etc/profile.d/conda.sh" ]; then
        . "/opt/conda/root/etc/profile.d/conda.sh"
    else
        export PATH="/opt/conda/root/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

The question is therefore: how to avoid having to set each user's `.bashrc ` and just have the symbolic link created in step 2 be enough as the conda documentation and help suggest should be working?

### Steps to Reproduce

1. install miniconda as root in `/opt/conda/root`
2. set variables `CONDA_PKGS_DIRS` and `CONDA_ENVS_DIRS` in `/etc/profile` as described above
3. create symbolic link `/etc/profile.d/conda.sh` pointing to `/opt/conda/root/etc/profile.d/conda.sh `
4. log in as a new user (create that user and then login if necessary)
5. try to run conda (will not work)

## Expected Behavior

After steps 1 to 4, step 5 should work

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

Conda info without adding to `.bashrc` the result of `conda init`
```
conda: command not found
```
Conda info with adding to`.bashrc` the result of `conda init`
```
     active environment : base
    active env location : /opt/conda/root
            shell level : 1
       user config file : /home/me/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda/root  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/shared/pkgs
                          /opt/conda/root/pkgs
                          /home/me/.conda/pkgs
       envs directories : /home/me/.conda/envs
                          /opt/conda/shared/envs
                          /opt/conda/root/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-46-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> envvars <==
envs_dirs:
  - /home/me/.conda/envs
  - /opt/conda/shared/envs
pkgs_dirs:
  - /opt/conda/shared/pkgs
  - /opt/conda/root/pkgs
  - /home/me/.conda/pkgs

```
</p></details>

**Comment by kalefranz** [comment]
Does your `/etc/profile` have a block of code in it that sources all the `*.sh` files in `/etc/profile.d`? For example, RHEL/CentOS `/etc/profile` usually contains the following...

```
for i in /etc/profile.d/*.sh /etc/profile.d/sh.local ; do
    if [ -r "$i" ]; then
        if [ "${-#*i}" != "$-" ]; then
            . "$i"
        else
            . "$i" >/dev/null
        fi
    fi
done
```

**Comment by mick-d** [comment]
Apologies, i though i already answered this. Yes `/etc/profile` contains the block of code you mentioned. This is not a problem of `/etc/profile` because as i mentioned above:

> I found out that it doesn't work because sourcing the conda initialization script `conda.sh` doesn't work: `source "/etc/profile.d/conda.sh"` (or `. "/etc/profile.d/conda.sh"`) will not work, and neither will `source "/opt/conda/root/etc/profile.d/conda.sh"`

**Comment by mick-d** [comment]
@kalefranz The multiuser conf described by conda does not work and only the fix i described can (temporarily) solved the issue. Is there a solution for any person who wants to setup a multiuser conda environment ?

**Comment by william-r-dieter** [comment]
`/etc/profile.d/conda.sh` defines functions and environment variables needed for the `conda` command to work, but does not activate a conda environment.  Assuming your conda is installed into `$CONDA_PREFIX`, link  `$CONDA_PREFIX/bin/activate` to `/etc/profile.d/conda_activate.sh`.  The `activate` script basically sources `$CONDA_PREFX/etc/profile.d/conda.sh` and then calls `conda activate` with the parameters it is passed.  When no parameters are passed, it activates the default environment, and the default environment will be activated when the user logs in.

The name you link `$CONDA_PREFIX/bin/activate` to in `/etc/profile.d` does not have to be `conda_activate.sh`, but it does have to end in `.sh` for the default `/etc/profile` to run it.

**Comment by jccolson** [comment]
Hello
In multiuser environment, only some user want or have to use conda.
It is possible to modify the prompt only if an env exist for the user.
I don't have the file `$CONDA_PREFIX/bin/activate` in my rpm.
I have created the following /etc/profile.d/conda_activate.sh :
`if [ -f "$HOME/.conda/environments.txt" ]; then`
`    if [ $( stat -c "%s" "$HOME/.conda/environments.txt" ) -gt 1 ]; then`
`# >>> conda initialize >>>`
`# !! Contents within this block are managed by 'conda init' !!`
`__conda_setup="$('/usr/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"`
`if [ $? -eq 0 ]; then`
`    eval "$__conda_setup"`
`else`
`    if [ -f "/usr/etc/profile.d/conda.sh" ]; then`
`        . "/usr/etc/profile.d/conda.sh"`
`    else`
`        export PATH="/usr/bin:$PATH"`
`    fi`
`fi`
`unset __conda_setup`
`# <<< conda initialize <<<`
`    fi`
`fi`

Can a conditional launch of `$CONDA_PREFIX/bin/activate` be at the end of /etc/profile.d/conda.sh ?
Only if `/etc/profile.d/conda_activate.sh` don't exists ? (in case of an admin will always have a modified prompt for all users)

PS : After deleting the last env, a trailing carriage return in environments.txt don't allow to use :
`if [ -s "$HOME/.conda/environments.txt" ]; then`

**Comment by alexsuncn** [comment]
Similar issue. Anaconda was installed at `/opt/anaconda3` .
I created a file `/etc/profile.d/startup.sh`, which contains the following command:
'''bash
eval "$(/opt/anaconda3/bin/conda shell.bash hook)"
conda activate MY_ENV
'''
Also tried:
'''bash
. "/opt/anaconda3/etc/profile.d/conda.sh"
conda activate MY_ENV
'''
Both way gave me the same problem when I try to use `conda`:
'''bash
conda: command not found
'''
Oddly, run `source /etc/profile` manually, `conda` was good to go.
Then I found out that neither `/opt/anaconda3/bin` or `/opt/anaconda3/condabin` were in $PATH.
So I just added `export PATH="/opt/anaconda3/condabin:$PATH"` in `/etc/profile.d/startup.sh`, and conda works fine.

I'm still not sure what's the problem.
