### ISSUE TITLE
After running "upgrade conda", no `conda` commands work any more due to libffi

### ISSUE THREAD

**Issue by cubranic** [conda/conda#9899]
## Current Behavior
After conda warned me that "A newer version of conda exists", I ran the exact recommended command:
```
conda update -n base -c defaults conda
```

This upgraded conda from 4.8.1 to 4.8.3. After running the command, it broke conda completely, and most `conda` commands (e.g., `create`, `install`, `upgrade`) print the a long traceback ending with "ImportError: dlopen(/usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found"

### Steps to Reproduce

```
$ conda update conda
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/usr/local/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 8, in <module>
    from .install import install
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
    import ctypes
  File "/usr/local/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
    import ctypes
  File "/usr/local/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found
```

## Expected Behavior

I should be able to use conda normally.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/usr/local/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "/usr/local/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
        import ctypes
      File "/usr/local/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /usr/local/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /usr/local/miniconda3/bin/conda info`

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
# the output is empty
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /usr/local/miniconda3:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                    pypi_0    pypi
arrow                     0.15.5                   pypi_0    pypi
asn1crypto                1.3.0                    py37_0    defaults
attrs                     19.1.0                   pypi_0    pypi
black                     19.3b0                   pypi_0    pypi
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.13.2           py37hb5b8e2f_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.0                      pypi_0    pypi
conda                     4.8.3                    py37_0    defaults
conda-package-handling    1.6.0            py37h1de35cc_0    defaults
cryptography              2.8              py37ha12b0ac_0    defaults
ideal-broccoli            0.1                       dev_0    <develop>
idna                      2.9                        py_1    defaults
importlib-metadata        1.6.0                    pypi_0    pypi
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.3                  h0a44026_1    defaults
more-itertools            8.2.0                    pypi_0    pypi
ncurses                   6.2                  h0a44026_0    defaults
openssl                   1.1.1g               h1de35cc_0    defaults
packaging                 20.3                     pypi_0    pypi
pip                       20.0.2                   py37_1    defaults
pluggy                    0.13.1                   pypi_0    pypi
py                        1.8.1                    pypi_0    pypi
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    py37_0    defaults
pytest                    5.4.1                    pypi_0    pypi
python                    3.7.2                haf84260_0    defaults
python-dateutil           2.8.1                    pypi_0    pypi
readline                  7.0                  h1de35cc_5    defaults
requests                  2.23.0                   py37_0    defaults
ruamel_yaml               0.15.87          py37h1de35cc_0    defaults
setuptools                46.1.3                   py37_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h5c1f38d_1    defaults
tk                        8.6.8                ha441bb4_0    defaults
toml                      0.10.0                   pypi_0    pypi
tqdm                      4.45.0                     py_0    defaults
urllib3                   1.25.8                   py37_0    defaults
wcwidth                   0.1.9                    pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.1.7                hc338f04_2    defaults
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    defaults
```
</p></details>

**Comment by kalefranz** [comment]
CC @mingwandroid libffi issue you might want to take a look at.

**Comment by mingwandroid** [comment]
This should be hotfixed I think. Ping @jjhelmus

**Comment by jjhelmus** [comment]
@cubranic Are you setting any custom channels in your .condarc file?  The contents of that file would be helpful to diagnose this issue. 

A hotfix was applied to the package repository a few days ago to address this issue but it looks like it is not being applied here.

**Comment by jjhelmus** [comment]
@cubranic The contents of `/usr/local/miniconda3/conda-meta/history` would also be helpful if you are willing to share.

**Comment by cubranic** [comment]
My .condarc was empty, but I only checked it after I got this error. (I never knowingly added something to it, I’m just not sure if it might have been done by a past `conda` command, and/or once my system was hosed if something else could have cleared it.)

Unfortunately, because this was blocking me from doing work for my job, I had to zap my installation and reinstall conda from scratch so I can’t check my past settings.

**Comment by jjhelmus** [comment]
I can reproduce this is I install packages from the `anaconda` channel.  For example by using `conda install python -c anaconda`.  That channel does not have hotfixes applied and has never been recommended.

It is also possible that if the Python package installed in the base environment had un-corrected dependencies which caused conda to install an incompatible libffi package.  I can't easily replicate this state.

If you happen to run into an issue like this again you can typically recover your conda environment by using the stand alone conda executables.  For example:

```
wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe
chmod +x conda-latest-osx-64.exe
./conda-latest-osx-64.exe install -p /usr/local/miniconda3 libffi python
```

**Comment by cubranic** [comment]
Thank you very much! That recovery step is a lifesaver if I run into this again. (I hope I won’t, but one never knows.)

**Comment by agreen456** [comment]
Hi, I have the same issue as above, newly today.
 I'm on Mac OS-10.14.6. after running `conda update conda` I went from conda 4.8.1-py37_0 to 4.8.3-py37_0 (as well as a bunch of other package changes) and am now unable to use the basic conda commands (`conda info`, `list`, `install` etc), though I am able to activate and use existing envs. 
 I tried using the recovery step suggested by @jjhelmus , unfortunately that just reports `All requested packages already installed.`
Like @cubranic I guess I now have to zap and start over, but can hold off for a couple of days if its helpful for debugging etc.

**Comment by JDFagan** [comment]
I have the same issue after running `conda update conda` it broke most conda commands.  I did have a .condarc defined simply as follows:
```
channels:
  - defaults
  - conda-forge
```

**Comment by jjhelmus** [comment]
@JDFagan Thanks for the history files, with it I can piece together the issue in your particular environment.  If you download the stand alone conda and follow the direction in my previous comment it should be possible to fix the issue.

The details of the issue are:
The `defaults/osx-64::python-3.7.2-haf84260_0` package is incompatible with libffi >=3.3 but this information was not known when the package was built as `libffi` has historically maintained their ABI but broke it with the 3.3 release.  The information for the package (and others which require libffi) was fixed on April 22, 2020 in AnacondaRecipes/repodata-hotfixes#80.  Unfortunately since the package was installed in your environment prior to this date it contains the un-correctly libffi dependency and conda will install an libffi into the environment unaware of the incompatibility.  

Newly environments with this package have the correct libffi requirement.  I'm not sure how best to avoid this type of situation.

**Comment by brauliobarahona** [comment]
In my case I tried to update Jupyter lab in my my base environment and ended in the same situation with conda broken... and the Jupyter notebook and the lab broken. Several packages were installed when I upgraded Jupyter lab, but not sure if also conda was updated. Now I have `4.8.3`; my base environment is broken  but other one work; I am on MacOS 10.14.6 

does the recipe above apply? I did not have miniconda environment, and since I have a user in my machine, I do

```
curl https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -o conda-latest-osx-64.exe
chmod +x conda-latest-osx-64.exe
./conda-latest-osx-64.exe install -p ~/miniconda3 libffi python
```

this works to get conda back to work, thanks! - jupyter still broken

**Comment by prasanna-sk** [comment]
> I can reproduce this is I install packages from the `anaconda` channel. For example by using `conda install python -c anaconda`. That channel does not have hotfixes applied and has never been recommended.
> 
> It is also possible that if the Python package installed in the base environment had un-corrected dependencies which caused conda to install an incompatible libffi package. I can't easily replicate this state.
> 
> If you happen to run into an issue like this again you can typically recover your conda environment by using the stand alone conda executables. For example:
> 
> ```
> wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe
> chmod +x conda-latest-osx-64.exe
> ./conda-latest-osx-64.exe install -p /usr/local/miniconda3 libffi python
> ```

Hello

I am facing similar issue with my miniconda env in OSX. Do you have similar recovery steps for OSX for miniconda?

**Comment by agreen456** [comment]
fwiw, doing a clean 'from scratch' install of miniconda3 (following https://conda.io/projects/conda/en/latest/user-guide/install/macos.html)  worked for me and was very easy. I copied my `miniconda3` directory, `.condarc` file and `.conda` directory into a temp folder, then completely uninstalled and reinstalled miniconda from scratch. finally I moved the folders with important envs back into the *new* `miniconda3`, added their paths into `.conda/environments.txt`, and seem good to go with full conda functionality again.

**Comment by avalanchecoke** [comment]
same issue, is there any good solution so far?

**Comment by ptoche** [comment]
Same here. I'm on a clean/formatted install of `MacOS Catalina` (barely 2 hours old!), with basically nothing more than `Xcode Command Line Tools` and `miniconda3`. Steps to replicate, as copied from my `.zsh_history`:

    export PATH="$HOME/miniconda3/bin:$PATH"
    conda update conda
    conda install -c anaconda python=3.8
    conda update conda
    conda update -all

    (myenv) ~ conda update conda
    Traceback (most recent call last):
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
    File "/Users/username/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/main_update.py", line 8, in <module>
        from .install import install
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 19, in <module>
        from ..core.index import calculate_channel_urls, get_index
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/download.py", line 13, in <module>
        import ctypes
    File "/Users/username/miniconda3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/username/miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
    Referenced from: /Users/username/miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so
    Reason: image not found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/Users/username/miniconda3/bin/conda", line 13, in <module>
        sys.exit(main())
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 150, in main
        return conda_exception_handler(_main, *args, **kwargs)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
        return_value = exception_handler(func, *args, **kwargs)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
        return self.handle_exception(exc_val, exc_tb)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1126, in handle_exception
        return self.handle_unexpected_exception(exc_val, exc_tb)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
        self.print_unexpected_error_report(error_report)
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1207, in print_unexpected_error_report
        from .cli.main_info import get_env_vars_str, get_main_info_str
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
    File "/Users/username/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/download.py", line 13, in <module>
        import ctypes
    File "/Users/username/miniconda3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/username/miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
    Referenced from: /Users/username/miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so
    Reason: image not found

(I can never remember the difference between `conda update conda` and `conda update --all` so I usually run both, typically without problems I might add).

**Comment by YangHongshen** [comment]
Same Issue + 1

**Comment by ptoche** [comment]
Got better luck the second time!

It wasn't plain sailing. I tried to run the `.sh` again but received 

    zsh: permission denied

After some pointless `chmod`ing, I got around the problem by using the `fish` shell instead of my default `iterm2`: The good `fish` did not complain about a missing image or an absence of permissions. Ignorance is bliss. After that, I was able to upgrade the miniconda python and to update it, and at least until now, run a few scripts without problems. Only been an hour or so, but it feels like I'm leaving this issue behind.

    conda init

Usually `miniconda` will put a PATH to miniconda in my `.zshrc` (or my `.bashrc`) after `conda init`, but not today.  So here's what I did and got out of trouble:

    export PATH="$HOME/miniconda3/bin:$PATH"
    conda install python=3.8
    conda update conda
    conda create --name python38 python=3.8
    ## Hooray! So far so good!

**Comment by janosh** [comment]
Is a fix incoming? And what's the recommended workaround for the time being?

**Comment by avalanchecoke** [comment]
> same issue, is there any good solution so far?

I just uninstalled the whole miniconda, and installed again...
libffi (3.2.1) came with default installation. Everything working well so far.

**Comment by z--m-n** [comment]
Hi,

Similar issues following conda upgraded to v3.8.3 today on OSX, using

`conda update -n base -c defaults conda`

Functionality could be restored by adding a symlink in the `lib` folder of miniconda3 (for base, not the envs):

`ln -s libffi.dylib libffi.6.dylib`

The symbolic link `libffi.dylib` is itself pointing to `libffi.7.dylib`. The call to `libffi.6.dylib` was referenced in `ctypes` (`.conda/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so`).

**Comment by adrianschlatter** [comment]
I have that problem as well after upgrading to v3.8.3. @z--m-n 's solution works for me (thanks @z--m-n).

**Comment by awaemmanuel** [comment]
> Hi,
> 
> Similar issues following conda upgraded to v3.8.3 today on OSX, using
> 
> `conda update -n base -c defaults conda`
> 
> Functionality could be restored by adding a symlink in the `lib` folder of miniconda3 (for base, not the envs):
> 
> `ln -s libffi.dylib libffi.6.dylib`
> 
> The symbolic link `libffi.dylib` is itself pointing to `libffi.7.dylib`. The call to `libffi.6.dylib` was referenced in `ctypes` (`.conda/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so`).

@z--m-n  I don't have ` libffi.6.dylib` under lib anymore. All I see is libffi.7.dylib`. Is there a link I can redownload this?

**Comment by z--m-n** [comment]
> @z--m-n I don't have ` libffi.6.dylib` under lib anymore. All I see is `libffi.7.dylib`. Is there a link I can redownload this?

I don't know. 

I also did not investigate the problem. I assume `libffi.6.dylib` was removed with an upgrade of `libffi`. Downgrading `libffi` may bring you back `libffi.6.dylib` but also the removal of `libffi.7.dylib`. Alternatively, when all relevant conda libraries have been compiled against libffi>=3.3 this issue goes away too.

**Comment by Red-Eyed** [comment]
For ubuntu workaround is just to create symlink that points to default libffi
`sudo ln -sf /usr/lib/x86_64-linux-gnu/libffi.so /usr/lib/x86_64-linux-gnu/libffi.so.6`  

In general, for any UNIX like OS, just find your system `libffi` and create a symlink with name `libffi.so.6` that points to your system `libffi`. That symlink should be located i same directory as original `libffi`

**Comment by janosh** [comment]
Has anyone tried the latest [conda@4.9.1](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id1)? Are any of the commands still broken after upgrading beyond 4.8.2?

**Comment by Red-Eyed** [comment]
@janosh so, I upgraded and it works on Ubuntu 20.04

**Comment by dschreij** [comment]
I started to experience this problem after upgrading the base environment from 4.8.5 to 4.9.2, so I guess it is still not fixed.

**Comment by lightalchemist** [comment]
I managed to get it to work using the conda standalone recovery option described above and using it to upgrade python so that the newly upgraded python library will use the new libffi library.

On mac,
```
wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe
./conda-latest-osx-64.exe install -f -p ~/anaconda3 libffi python
# Simply force reinstall python did not fix the issue
./conda-latest-osx-64.exe update -f -p ~/anaconda3 python libffi
# Updating python fixes it for me for the reasons given above.
```

**Comment by solkm** [comment]
copying an old libffi.6.dylib file into the anaconda3/lib folder (which only had libffi.7.dylib) worked for me

**Comment by holmrenser** [comment]
Just had to do the symlink trick, but instead link `libffi.8.dylib` to `libffi.7.dylib`. I'm on MacOS Monterey 12.1.

**Comment by jingjieyeo** [comment]
> I managed to get it to work using the conda standalone recovery option described above and using it to upgrade python so that the newly upgraded python library will use the new libffi library.
> 
> On mac,
> 
> ```
> wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe
> ./conda-latest-osx-64.exe install -f -p ~/anaconda3 libffi python
> # Simply force reinstall python did not fix the issue
> ./conda-latest-osx-64.exe update -f -p ~/anaconda3 python libffi
> # Updating python fixes it for me for the reasons given above.
> ```

Had the same problem updating conda on MacOS Monterey and this solution was a lifesaver!

**Comment by JohnAtl** [comment]
Still an issue for me.
In my environment:
```x gsettings
gsettings: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
```
In `~/anaconda3/envs/myenv/lib` I have version 7 and 8 files.
Previously needed to install:
```
conda install -c conda-forge ncurses
conda install -c conda-forge glib
```
For other missing lib errors.
If I do, e.g.
```
LD_LIBRARY_PATH="" gsettings
```
It works fine.

```
> conda info

     active environment : myenv
    active env location : /home/john/anaconda3/envs/myenv
            shell level : 2
       user config file : /home/john/.condarc
 populated config files : 
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.10.0=0
                          __unix=0=0
       base environment : /home/john/anaconda3  (writable)
      conda av data dir : /home/john/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/john/anaconda3/pkgs
                          /home/john/.conda/pkgs
       envs directories : /home/john/anaconda3/envs
                          /home/john/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.16 Linux/5.10.0-21-amd64 debian/11 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

```
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Host: OptiPlex 7040 
Kernel: 5.10.0-21-amd64 
Uptime: 42 mins 
Packages: 2868 (dpkg) 
Shell: zsh /usr/bin/zsh: /home/john/anaconda3/envs/myenv/lib/libtinfo.so.6: no version information available 
Resolution: 3840x2160 
DE: GNOME 
WM: Mutter 
Terminal: gnome-terminal 
CPU: Intel i7-6700 (8) @ 4.000GHz 
GPU: Intel HD Graphics 530 
GPU: NVIDIA GeForce GT 1030 
Memory: 4611MiB / 48074MiB 
```

**Comment by codejoey** [comment]
Problem hit me today.

Symlink workaround seems unideal - especially with interactions from future updates.
I didn't install anaconda via brew so brew solution couldn't work for me.
And I [read](https://stackoverflow.com/a/62179041) that using `brew cask install anaconda ` isn't a good idea.

What worked for me:
Found a copy of "libffi.6.dylib" file in one of my env's, and copied into my "/Users/Joey/anaconda3/lib/".
Please let me know if that is not ideal for some reason I didn't think of.
