### ISSUE TITLE
Specify yml file AND dont install default packages. --no-default-packages doesnt work with -f environment.yml

### ISSUE THREAD

**Issue by red8888** [conda/conda#9904]
- I want to describe my dependencies in a yaml file 
- I dont want to install any default packages

Pretty straight forward use case but this seems to be impossible?

- I cant use `--no-default-packages` with `conda env create -f environment.yml` 
- I cant use `--f environment.yml` with `conda create --name myenv python`
- If I run `conda create --name myenv python` first and then run `conda env update --name myenv --file environment.yml` it installs all those default packages!!!

Am I crazy? there must be a way to do this. If I have to write my own script that parses environment.yml and runs a command to install each dep individually that would be super shitty

**Comment by mohadelrezk** [comment]
hi, why is that closed?
is there a solution or work around ?
