### ISSUE TITLE
cannot install packages

### ISSUE THREAD

**Issue by sunzhenhai** [conda/conda#9910]
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : E:\anaconda2  (writable)
    default environment : E:\anaconda2
       envs directories : E:\anaconda2\envs
                          C:\Users\Andrewuestc\AppData\Local\conda\conda\envs
                          C:\Users\Andrewuestc\.conda\envs
          package cache : E:\anaconda2\pkgs
                          C:\Users\Andrewuestc\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Andrewuestc\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Windows/10 Windows/10.0.18362
          administrator : False

`$ E:\anaconda2\Scripts\conda-script.py config --add channels https://mirrors.ustc.edu.cn/anaconda/pkgs/free/`

    Traceback (most recent call last):
      File "E:\anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "E:\anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "E:\anaconda2\lib\site-packages\conda\cli\main_config.py", line 213, in execute
        execute_config(args, parser)
      File "E:\anaconda2\lib\site-packages\conda\cli\main_config.py", line 375, in execute_config
        raise CouldntParseError("key %r should be a list, not %s." % (key, bad))
      File "E:\anaconda2\lib\site-packages\conda\exceptions.py", line 312, in __init__
        super(CouldntParseError, self).__init__(self.args[0])
    IndexError: tuple index out of range

**Comment by YuTong1999** [comment]
请问你解决了吗？我遇到了一样的问题，卸载重装也不行
