### ISSUE TITLE
InvalidArchiveError when installing yfinance library

### ISSUE THREAD

**Issue by tszwailam** [conda/conda#9913]
## Current Behavior

Just installed Conda Python 3.7, created a virtual environment, and ran the command 
`conda install -c ranaroussi yfinance`
as directed by 
https://github.com/ranaroussi/yfinance

and got an error
`InvalidArchiveError('Error with archive C:\\Users\\tlam\\Anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')`

### Steps to Reproduce

```
conda create --name quant python=3.7 

^ - to create the virtual environment

conda install pandas

^ - installing pandas

conda install -c ranaroussi yfinance

^ - installing yfinance
```

## Expected Behavior

Library successfully unzips.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : quantclass
    active env location : C:\Users\tlam\Anaconda3\envs\quantclass
            shell level : 2
       user config file : C:\Users\tlam\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\tlam\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tlam\Anaconda3\pkgs
                          C:\Users\tlam\.conda\pkgs
                          C:\Users\tlam\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tlam\Anaconda3\envs
                          C:\Users\tlam\.conda\envs
                          C:\Users\tlam\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\tlam\Anaconda3\envs\quantclass:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0    defaults
argh                      0.26.2                   py37_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
astroid                   2.3.3                    py37_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.4.4                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
bcrypt                    3.1.7            py37he774522_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.4                      py_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
cloudpickle               1.4.0                      py_0    defaults
colorama                  0.4.3                      py_0    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
docutils                  0.16                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
flake8                    3.7.9                    py37_0    defaults
future                    0.18.2                   py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.9                        py_1    defaults
imagesize                 1.2.0                      py_0    defaults
importlib_metadata        1.5.0                    py37_0    defaults
intel-openmp              2020.0                      166    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.1.4            py37h39e3cac_0    defaults
ipython                   7.13.0           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
isort                     4.3.21                   py37_0    defaults
jedi                      0.15.2                   py37_0    defaults
jinja2                    2.11.2                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter_client            6.1.3                      py_0    defaults
jupyter_core              4.6.3                    py37_0    defaults
keyring                   21.1.1                   py37_2    defaults
lazy-object-proxy         1.4.3            py37he774522_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
markupsafe                1.1.1            py37he774522_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.15           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.4                      py_0    defaults
numpy                     1.18.1           py37h93ca92e_0    defaults
numpy-base                1.18.1           py37hc3f5095_1    defaults
numpydoc                  0.9.2                      py_0    defaults
openssl                   1.1.1g               he774522_0    defaults
packaging                 20.3                       py_0    defaults
pandas                    1.0.3            py37h47e9c7a_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
paramiko                  2.7.1                      py_0    defaults
parso                     0.5.2                      py_0    defaults
pathtools                 0.1.2                      py_1    defaults
pexpect                   4.8.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       20.0.2                   py37_1    defaults
pluggy                    0.13.1                   py37_0    defaults
prompt-toolkit            3.0.4                      py_0    defaults
prompt_toolkit            3.0.4                         0    defaults
psutil                    5.7.0            py37he774522_0    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycparser                 2.20                       py_0    defaults
pydocstyle                4.0.1                      py_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.6.1                      py_0    defaults
pylint                    2.5.0                    py37_0    defaults
pynacl                    1.3.0            py37h62dcd97_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyrsistent                0.16.0           py37he774522_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.7                h60c2a47_2    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.31.10                  py37_0    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   227              py37he774522_1    defaults
pywin32-ctypes            0.2.0                 py37_1000    defaults
pyyaml                    5.3.1            py37he774522_0    defaults
pyzmq                     18.1.1           py37ha925a31_0    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.7.0                      py_0    defaults
qtconsole                 4.7.3                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.23.0                   py37_0    defaults
rope                      0.16.0                     py_0    defaults
rtree                     0.9.3            py37h21ff451_0    defaults
setuptools                46.1.3                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.14.0                   py37_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
sphinx                    3.0.3                      py_0    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
spyder                    4.1.2                    py37_0    defaults
spyder-kernels            1.9.0                    py37_0    defaults
sqlite                    3.31.1               h2a8f88b_1    defaults
testpath                  0.4.4                      py_0    defaults
tornado                   6.0.4            py37he774522_1    defaults
traitlets                 4.3.3                    py37_0    defaults
ujson                     1.35             py37hfa6e2cd_0    defaults
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
watchdog                  0.10.2                   py37_0    defaults
wcwidth                   0.1.9                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.34.2                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
wrapt                     1.12.1           py37he774522_1    defaults
yaml                      0.1.7                hc54c509_2    defaults
yapf                      0.28.0                     py_0    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults

```
</p></details>

**Comment by alejandrosantiag0** [comment]
Hello! I'm having the same issue, were you able to solve this? If so, how?

**Comment by ZelinC** [comment]
I have exactly the same issue. Can someone help? 

Many thanks

**Comment by Gares95** [comment]
Using pip in Anaconda prompt work just fine.
`conda activate<your-enviroment>`
`pip install yfinance --upgrade --no-cache-dir`

**Comment by stan255** [comment]
Try using pip install. I used conda install and got that error too.

**Comment by aashishnk** [comment]
While installing 'yfinance'in by _base environment_ using the command "conda install -c ranaroussi yfinance", I was also getting same "InvalidArchiveError".
So, then I unzipped/extracted the "yfinance-0.1.54-py_0.tar.bz2" file **manually** & then ran the same command in conda command prompt.

Hope this helps others.

**Comment by aashishnk** [comment]
While installing 'yfinance'in by **base environment** using the command "conda install -c ranaroussi yfinance", I was also getting same "InvalidArchiveError".
So, then I unzipped/extracted the "yfinance-0.1.54-py_0.tar.bz2" file **manually** & then ran the same above install command in conda command prompt. This worked for me & its api are also working fine.

Hope this helps others !!

Below image is when I re-ran the above install command after manually extracting the zip file.
![image](https://user-images.githubusercontent.com/36652458/103007052-c0dbc900-4558-11eb-8d58-b8a8cc269bcf.png)

**Comment by aashishnk** [comment]
Issue with "pip install yfinance" in conda command prompt is that its api was giving **SSL Certificate issue** by which I was not able to use its any api. Its all dependent packages might not be there.

But issue got resolved by using "conda install -c ranaroussi yfinance" . But you might get one error while installing yfinance as "InvalidArchiveError". So, please resolve this issue by manually unzipping its library file in your environment & then re-run the same install command.

**Comment by cunnial** [comment]
> While installing 'yfinance'in by **base environment** using the command "conda install -c ranaroussi yfinance", I was also getting same "InvalidArchiveError".
> So, then I unzipped/extracted the "yfinance-0.1.54-py_0.tar.bz2" file **manually** & then ran the same above install command in conda command prompt. This worked for me & its api are also working fine.
> 
> Hope this helps others !!
> 
> Below image is when I re-ran the above install command after manually extracting the zip file.
> ![image](https://user-images.githubusercontent.com/36652458/103007052-c0dbc900-4558-11eb-8d58-b8a8cc269bcf.png)

Hi There I used 7 zip to extract this file in the "\anaconda\pkgs" folder however when I went to run the install again it told me "[Errono 13] permission denied?: ...\yfinance-0-1-54.tar"

Any ideas? I have tried pip install but got an even stranger error: image 2 below:
![Screenshot 2020-12-29 224326](https://user-images.githubusercontent.com/25256375/103318866-993ca300-4a27-11eb-8239-f5c7d136b24f.jpg)
![Screenshot 2020-12-29 45645](https://user-images.githubusercontent.com/25256375/103318886-b1142700-4a27-11eb-8a11-27c6455c7793.jpg)

**Comment by bakiba** [comment]
@cunnial did you extract the "yfinance-0.1.54-py_0.tar.bz2" to folder called "yfinance-0.1.54-py_0"? Since 7zip with "extract here" will extract to "yfinance-0.1.54-py_0.tar". On top of that, do not forget to extract the .tar also inside the "yfinance-0.1.54-py_0".
You should end-up with following folder structure:
![image](https://user-images.githubusercontent.com/36819607/103666605-20809e00-4f75-11eb-9059-219b0b26e578.png)

**Comment by dynoweb** [comment]
Thanks bakiba, that worked great.   I used 7zip on Win10

**Comment by cunnial** [comment]
"> @cunnial did you extract the "yfinance-0.1.54-py_0.tar.bz2" to.."

Thanks for following up yes indeed this worked very well, now have all issues resolved on this  ticket. Thanks again

**Comment by gabbyrogers22** [comment]
Hi, I am still having this same issue. I have extracted the files as recommended above and have this result 
<img width="557" alt="invalid archive error" src="https://user-images.githubusercontent.com/57543410/105372918-1c3ebc80-5bd4-11eb-8ea4-245ba083b9b4.png"> and I am still getting the invalid archive error. Am I missing something? Should I just install with pip?

**Comment by bakiba** [comment]
Maybe the yfinance-0.1.54-py_0.tar file that you left there is causing issue... I would remove it.
I haven't tried using pip in conda since it says you should not mix the two.

**Comment by gabbyrogers22** [comment]
I have deleted that file in that folder; however, every time I run the command in the terminal it recreates yfinance-0.1.54-py_0.tar.bz2. Not within that file, but in the pkgs folder. I am also getting 4 warnings each time I run the command
<img width="890" alt="invalid archive error terminal" src="https://user-images.githubusercontent.com/57543410/105400066-70589980-5bf2-11eb-9351-bfcdd52af7cf.png">

I am really confused and do not know much about this stuff so any help is appreciated!

**Comment by bakiba** [comment]
Where did you extract yfinance-0.1.54-py_0.tar.bz2? You did not show but it should be extracted in your pkgs folder. You should have "C:\users\gabby\anaconda3\pkgs\yfinance-0.1.54-py_0" folder and inside the extracted "info", "python-scripts" and "site-packages" folders. From your earlier screenshot it is not visible the full path where those folders are residing.

**Comment by gabbyrogers22** [comment]
I tried to extract the bz2 file again, since it kept showing up. My only option for extracting the bz2 file is to a .tar file. How do I extract it to "C:\users\gabby\anaconda3\pkgs\yfinance-0.1.54-py_0" if that isn't an option?
<img width="843" alt="extract to " src="https://user-images.githubusercontent.com/57543410/105404679-3db19f80-5bf8-11eb-90f6-963b9c1b1c86.png">

**Comment by bakiba** [comment]
You can use Extract to yfinance-0.1.54-py_0.tar\ and then rename the folder to "yfinance-0.1.54-py_0". you will also then have to extract the yfinance-0.1.54-py_0.tar that will be inside the folder yfinance-0.1.54-py_0. For that just use "Extract here".
You should end up with structure as I showed in my post here https://github.com/conda/conda/issues/9913#issuecomment-754716754

**Comment by gabbyrogers22** [comment]
That fixed the problem! Thank you so much!!

**Comment by Olivair** [comment]
I am having the same issue despite adhering to the folder structure and provided solution steps. The error re-occurs and  _pip install_ returns empty dataframes. The manually created _yfinance-0.1.54-py_0_ gets deleted every time I re-run the _conda install_ command.

**Comment by dg2811** [comment]
> That fixed the problem! Thank you so much!!

I followed what ever you said and reached to a point as shown in the screenshots. But still when I run import yfinance as yf in jupyter, I get the same error that module not found. 

<img width="781" alt="Capture1" src="https://user-images.githubusercontent.com/69469318/114593069-4ec6f580-9ca9-11eb-9025-19625bd81b6b.PNG">
<img width="476" alt="Capture2" src="https://user-images.githubusercontent.com/69469318/114593075-4ff82280-9ca9-11eb-97ce-2ad5413738ae.PNG">

**Comment by Zapz21** [comment]
@dg2811, @Olivair 
Copy "yfinance" and "yfinance-0.1.54.dist-info" from "C:\...\Anaconda3\pkgs\yfinance-0.1.54-py_0\site-packages"
and paste it in 
C:\...\Anaconda3\Lib\site-packages\   
dir.
this worked for me.

**Comment by Zapz21** [comment]
@Olivair  @dg2811 

Copy "yfinance" and "yfinance-0.1.54.dist-info" from "C:...\Anaconda3\pkgs\yfinance-0.1.54-py_0\site-packages"
and paste it in
C:...\Anaconda3\Lib\site-packages\
dir.
that's it, this worked for me.
