### ISSUE TITLE
Is there a CLA option for organizations as opposed to individuals?

### ISSUE THREAD

**Issue by zhaojack** [conda/conda#9916]
Hi,

Apologies if this is not the right place for such a question.

My team has adopted conda as the tool of choice for internal package management at our organization, and we're finding opportunities where we could perhaps contribute bug fixes or implementations of new feature ideas to conda. After talking to legal department to get permission, we were asked to provide a site CLA that covers anyone in the company. All I could find from the conda docs is an individual CLA which does not satisfy the requirements we were given. Is there a "site CLA" somewhere?

For example, the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) has a checkbox that says "Click here if you are signing this form on behalf of an organization" and the language says "individual or other entity". [Django's page](https://www.djangoproject.com/foundation/cla/) also provides the option for a "Corporate Contributor License Agreement". Is there an equivalent for conda?

Thanks,
Jack

**Comment by cjmartian** [comment]
cc @kalefranz

**Comment by zhaojack** [comment]
Hi, any chance we might get an answer on this question soon?

Or, if this place is not appropriate for such a question, please let me know which other communication channel is best.

Thanks!

**Comment by zhaojack** [comment]
Hi again,

Poking this question again in the hope of receiving a response.

Thanks,
Jack

**Comment by chenghlee** [comment]
@zhaojack: apologies for the delay. At this time, we currently do not have an organization-level CLA; however, this request has been made before in other venues, so we will be revisiting it.
