### ISSUE TITLE
[Docs] CONDA 4.6 CHEAT SHEET erroneous link

### ISSUE THREAD

**Issue by Querela** [conda/conda#9920]
## Current Behavior
A link in Cheat Sheet *CONDA 4.6 CHEAT SHEET* for **Free Community Support** is broken!
- `http://bit.lyconda_list`

### Steps to Reproduce
1. Visit: https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html
2. Download PDF with Cheat Sheet
3. Scroll to end, section: **More Resources**

```
Link:
Free Community Support -- http://bit.lyconda_list
```

## Expected Behavior
Link should be: http://bit.ly/conda_list
--> Not the extra `/` !

## Environment Information
N/A

**Comment by csoja** [comment]
Thank you letting us know about this error!  We'll add it to the list for the next revision of the cheatsheet.
