### ISSUE TITLE
conda  navigator was not opening

### ISSUE THREAD

**Issue by Hemanthchowdary123** [conda/conda#9928]
C:\Users\Hemanth>conda config --show-sources
==> C:\Users\Hemanth\.condarc <==
ssl_verify: True
channels:
  - defaults
restore_free_channel: True
report_errors: False
report error was false but conda was not opening in the my OS

**Comment by cjmartian** [comment]
Hello @Hemanthchowdary123 thank you for reporting this issue. Unfortunately, there is not enough information provided for us to diagnose this problem. Please be sure to fill out the issue template in its entirety.

**Comment by Hemanthchowdary123** [comment]
Thank you sir for responding
  I was using windows 10 OS in my laptop anaconda navigator was opening more over JUPYTER NOTEBOOK and SPYDER was opening. but i want navigator
