### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HarshitaSahai** [conda/conda#9929]
python3 -m rasa_core.train -d domain.yml -s data/core -o models/current/dialogue -c core_config.yml
make: *** [train-core] Error 9009

Python 3.6
Windows 10

**Comment by cjmartian** [comment]
Hello @HarshitaSahai thank you for reporting this issue! Unfortunately, there is not enough information here for us to diagnose this issue. Please fill out the issue template in it's entirety when reporting an issue.
