### ISSUE TITLE
conda init powershell does not handle unicode path when creating profile.ps1

### ISSUE THREAD

**Issue by Japanuspus** [conda/conda#9932]
## Current Behavior
When running `conda init powershell`, the updated `profile.ps1` is created in an incorrect folder `C:\Users\yyy\OneDrive - �xxxx\WindowsPowerShell\`.

### Steps to Reproduce

Have not tried this, but I would assume running `conda init powershell` with an `Ø`-character in first path in `PSModulePath` should be enough.

## Expected Behavior
I would expect `profile.ps1` to be created in `C:\Users\yyy\OneDrive - Øxxxx\WindowsPowerShell\`.

## Environment Information
Output of `conda info`
```
     active environment : anaconda
    active env location : C:\Users\jawes\Miniconda3\envs\anaconda
            shell level : 2
       user config file : C:\Users\jawes\.condarc
 populated config files : C:\Users\jawes\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\jawes\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jawes\Miniconda3\pkgs
                          C:\Users\jawes\.conda\pkgs
                          C:\Users\jawes\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jawes\Miniconda3\envs
                          C:\Users\jawes\.conda\envs
                          C:\Users\jawes\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by ain-soph** [comment]
I suffer this issue as well when my Document folder contains characters of other languages. I change my Document location to an English name and it works. But please fix it.

**Comment by CalmJerome** [comment]
I found the solution, we can change the location of the profile.
1. test-path $profile, if not , then go to 2
2. new-item -path $profile -itemtype file -force
Then we can copy the error information into the new powershell profile, then it works.
