### ISSUE TITLE
Could not install Anaconda3-2020.02-Windows-x86_64 on Windows Server 2019

### ISSUE THREAD

**Issue by cppmyjob** [conda/conda#9953]
## Current Behavior
I could not install Anaconda3-2020.02-Windows-x86_64 on Windows Server 2019
I just installed the latest Anaconda3-2020.02-Windows-x86_64.exe with default options.

There are no menus in Start menu so I can't launch Anaconda 

I figured out that

1. Anaconda3 folder contains
Lib
pkgs
.nonadmin
_conda.exe
Uninstall-Anaconda3.exe

2. Installer log contains the next error

> Extract: anaconda-2020.02-py37_0.tar.bz2
>                                                                                            [5772] Failed to execute script entry_point
> concurrent.futures.process._RemoteTraceback: 
> '''
> Traceback (most recent call last):
>   File "concurrent\futures\process.py", line 367, in _queue_management_worker
>   File "multiprocessing\connection.py", line 251, in recv
> TypeError: __init__() missing 1 required positional argument: 'msg'
> '''
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "entry_point.py", line 69, in <module>
>   File "concurrent\futures\process.py", line 483, in _chain_from_iterable_of_lists
>   File "concurrent\futures\_base.py", line 598, in result_iterator
>   File "concurrent\futures\_base.py", line 435, in result
>   File "concurrent\futures\_base.py", line 384, in __get_result
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> Collecting package metadata (current_repodata.json): ...working... done
> Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): ...working... done
> Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
full log you can find here https://drive.google.com/open?id=11QAxOWg-yzvfl83y5uLI0Pn8uvH5vADI

## Expected Behavior
I can launch Anaconda UI

## Environment Information
OS Name	Microsoft Windows Server 2019 Standard
Version	10.0.17763 Build 17763
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	WIN-KIK834NIVK4
System Manufacturer	Microsoft Corporation
System Model	Virtual Machine
System Type	x64-based PC
System SKU	Unsupported
Processor	Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz, 3400 Mhz, 8 Core(s), 8 Logical Processor(s)
Processor	Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz, 3400 Mhz, 8 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 090006, 4/28/2016
SMBIOS Version	2.3
BIOS Mode	Legacy
BaseBoard Manufacturer	Microsoft Corporation
BaseBoard Product	Virtual Machine
BaseBoard Version	7.0
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Not Available
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17763.1131"
User Name	Not Available
Time Zone	Russia TZ 2 Standard Time
Installed Physical Memory (RAM)	4.00 GB
Total Physical Memory	4.00 GB
Available Physical Memory	1.98 GB
Total Virtual Memory	4.00 GB
Available Virtual Memory	1.96 GB
Page File Space	0 bytes
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Not Available
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

Also I have enough free space on my drive C

**Comment by cppmyjob** [comment]
I was able to install previous version Anaconda3-2019.10-Windows-x86_64 on the same machine

**Comment by Aminyazdanshenas** [comment]
I've the same issue is there any other options ?

**Comment by dirtyluke** [comment]
maybe out of space,or something like that. I've meet the same issue, and i searched the same key words , most was in linux env, and the most popular solution was about space. I didn't close my laptop for months, and the system reminds me to restart my computer becourse of the system installed patches. After i reboot my laptop, i reinstall the package, it succeed
