### ISSUE TITLE
Docs: 'conda env remove ...' should be referenced under 'conda remove ...'

### ISSUE THREAD

**Issue by ptoche** [conda/conda#9955]
A quick search for "_conda remove_" takes one to the manual page: [https://docs.conda.io/projects/conda/en/latest/commands/remove.html](https://docs.conda.io/projects/conda/en/latest/commands/remove.html), where I propose that a reference to `conda env remove...` be made near the end of the first paragraph to direct users looking to remove the environment itself. 

The more natural syntax would be `conda destroy env`, as others have [suggested in the past](https://github.com/conda/conda/issues/1269).  

The argument that the environment could be removed by simply deleting the files is weak, since the `.conda` directory contains an `environments.txt` file with the names of the environments, and the `rm -rf path/to/env` method would not affect that (and if there is an argument that the `environments.txt` file is useless, well then dot dot dot). 

Evidence that the docs could be improved in this respect may be found in the number of directionless users upvoting this comment: [https://github.com/conda/conda/issues/8351#issuecomment-502732265](https://github.com/conda/conda/issues/8351#issuecomment-502732265).

**Comment by MLaurenceFournier** [comment]
Being among those directionless users, I'm still confused has to whether simply removing a given environment with `rm -rf path/to/env` cause any problem. I've done it many times without any side effects.

After some tests, it’s true that the environment.txt file will keep a reference to my environment. However, that reference is removed after any call to `conda info --envs` or `conda env list`.

Does anyone know if there are negative consequences to deleting an environment folder manually?
