### ISSUE TITLE
Installing python library in virtual enviroment

### ISSUE THREAD

**Issue by itzAmirali** [conda/conda#9968]
Hello,

I am working on a remote system. I have installed miniconda on there, and I have created the environment with `conda create -n py3 python=3.7` in my home directory (/home/myname/miniconda3.)
After I activated this environment, I have created a virtual env in the project path with `python -m venv py3env`. 
Now, at this point, I will activate my VirtualENV and try to install a package on there with `pip`.
For installing one library called `spams` with `pip install spams`, I am receiving these errors. I will appreciate it if you can help me with the error.

> /home/myname/miniconda3/envs/py3.7/compiler_compat/ld: cannot find -lblas

> /home/myname/miniconda3/envs/py3.7/compiler_compat/ld: cannot find -llapack

> collect2: error: ld returned 1 exit status

> error: Command "g++ -pthread -shared -B /home/myname/miniconda3/envs/py3.7/compiler_compat -L/home/myname/miniconda3/envs/py3.7/lib -Wl,-rpath=/home/myname/miniconda3/envs/py3.7/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spams_wrap.o -L/project_path/Virtualenv/lib -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lstdc++ -lblas -llapack -lgomp -o build/lib.linux-x86_64-3.7/_spams_wrap.cpython-37m-x86_64-linux-gnu.so -fopenmp" failed with exit status 1

**Comment by wolfv** [comment]
you shoudl probably install this with conda: https://anaconda.org/conda-forge/python-spams

**Comment by rolweber** [comment]
Do not mix conda environments with virtual environments. Pick one or the other. Use `conda` only when you want to use conda environments.
