### ISSUE TITLE
Improve conda instructions

### ISSUE THREAD

**Issue by srossross** [conda/conda#997]
This is a meta issue to track the adding of new _instructions_\* to be handled by [execute_plan](https://github.com/conda/conda/blob/master/conda/plan.py#L537)

The goal of these improvements are to add `CONDA_NOARCH_INSTALL` and `SDIST_INSTALL` instructions to conda. This issue is to track my progress  break the work down into smaller more manageable pull requests that keep conda in a working state while making progress towards the main goal.
- [x] Refactor [The resolver](https://github.com/conda/conda/blob/master/conda/plan.py#L398-L421) so that the `sort` step at the end is not required. The results of the iterator `Resolve.solve` should return a topologically sorted object from the dependency graph. 
  
  This will be an issue for new installer types that require other packages be installed first (like setuptools) to install. Also, this has already been an issue for some conda pre_link scripts. like the `aaa_wakari` package was prefixed with `aaa` just so it would get installed first @bkreider )
- [x] Update the cmd, args in the plan to not be strings. The arguments that are passed into the `EXTRACT`, `LINK` and `FETCH` instructions should be the conda index entry. (I'm not sure why the canonical name is [serialized](https://github.com/conda/conda/blob/master/conda/plan.py#L226) into a string and then subsequently [parsed](https://github.com/conda/conda/blob/master/conda/plan.py#L527))
  
  The object argument will be required to:
  1. Inspect the metadata to create the appropriate instruction (a `CONDA_NOARCH_INSTALL` vs a `CONDA_INSTALL` - see below)
  2. Give each instruction more information about the object to be more autonomous 
- [ ] Merge the `EXTRACT` and `LINK` instructions into one instruction `CONDA_INSTALL`
- [ ] Add a new `CONDA_NOARCH_INSTALL` instruction to handle conda no-arch packages.
- [x] Refactor [the if statements](https://github.com/conda/conda/blob/master/conda/plan.py#L552-L575) of the instruction execution into a data-structure. This will allow new instructions to be added programatically. 
- [ ] Add a new `SDIST_INSTALL` instruction to install python sdists directly.

cc @tswicegood @teoliphant @asmeurer @ilanschnell

**Comment by teoliphant** [comment]
This was discussed again today.   We should perhaps generalize the SDIST_INSTALL instruction to a GENERAL_INSTALL instruction with a hookable script to execute as well as the post-install script to execute in order to create the necessary conda meta-data. 

Also, there would need to be some way to plug-in to conda index to generate the correct repodata.

**Comment by kalefranz** [comment]
Outdated. Closing.
