### ISSUE TITLE
Support for secure API-key and API-user injection

### ISSUE THREAD

**Issue by bjlittle** [conda/conda#9973]
First of all, thanks for `conda`. It's a totally invaluable tool in my workflow and I greatly appreciate all the continued efforts of the `conda` development community. Amazing.

## Context

Righty, some context... so at my current organisation I'm pushing hard to recommend the use and adoption of `conda` throughout our scientific estate; of course, why wouldn't you? Anyways, given the current local architecture and infrastructure it's a necessity that `conda` pulls all its packages from the organisations JFrog [Artifactory Cloud](https://jfrog.com/artifactory/?gclid=CjwKCAjw8df2BRA3EiwAvfZWaBLOoI9SUkD--Hy-Jm2_t_9Z7wJDiUyFfVmPI4NOc4VCcSDTRTHL1hoCcisQAvD_BwE)  instance. Our Artifactory Cloud instance not only acts as a proxy to the `anaconda` and `conda-forge` channels, but also hosts in-house `conda` channels. In addition to this, it also acts as a proxy to `pypi`. This way, there is a level of organisational control, security, resource caching and monitoring for the estates appetite for open source packages. Great.

## Problem

Now here's the rub... in order to use Artifactory Cloud, users are forced to add their personal Artifactory Cloud `API-USER` and `API-KEY` details into their local `~/.condarc` e.g.,
```bash
channel_alias: https://<API-USER>@<snip>:<API-KEY>@<snip>.jfrog.io/<snip>/api/conda/
```
The user then locks down the read permissions on their `~/.condarc` appropriately.

This is all fine and dandy, and works a treat... however, simply using the `conda info` command will now expose the users coveted `API-USER` and `API-KEY` for one and all to see and use. Bummer.

In fact, the `channel_alias` is peppered throughout various parts of the `conda` metadata, as you would expect.

## Question

Before asking for a new feature, I guess the obvious question might be, *"Could you recommend a more appropriate and secure way to do this?"*

Otherwise, would there be appetite to support additional suitable keys within the `~/.condarc` that would allow users to provide their `API-USER` and `API-KEY`, which in turn would be used internally by `conda` for a specific `channel_alias`, but in a secure way that doesn't expose those credentials from the `conda` API, or indeed within `conda` internal metadata, such as the package cache etc.

This is the biggest blocker at our organisation to provisioning a centrally managed and maintained version of `conda` (configured to use our Artifactory Cloud instance) for the users on our scientific estate.

Many thanks :smile:

**Comment by bjlittle** [comment]
See #1784

**Comment by bjlittle** [comment]
See #6969

**Comment by wagnerpeer** [comment]
There are already multiple locations, where different auth info is stripped from the URL:
* [conda/conda/common/url.py#250](https://github.com/conda/conda/blob/248741a843e8ce9283fa94e6e4ec9c2fafeb76fd/conda/common/url.py#L250)
* [conda/conda/common/url.py#L376](https://github.com/conda/conda/blob/248741a843e8ce9283fa94e6e4ec9c2fafeb76fd/conda/common/url.py#L376)
* [conda/conda/gateways/logging.py#L45](https://github.com/conda/conda/blob/248741a843e8ce9283fa94e6e4ec9c2fafeb76fd/conda/gateways/logging.py#L45)

I think it everyone would benefit from extending this concept to every location where the URL is logged. If no longer contained in logs, this would allow us to use the .condarc to contain sensitive information.

Other option is to use the .netrc file to contain the auth info. (_See original comment by @jamesp in https://github.com/conda/conda/issues/1784#issuecomment-839879431_)

**Comment by bjlittle** [comment]
We've adopted the `.netrc` file as a work around.

@jamesp Is this still a live issue, or do you think that it should be closed?

Perhaps, others find benefit, which I'm guessing @wagnerpeer you're tending towards. Although, I don't know what tangible outcomes can come from this without core dev support and effort.

**Comment by wagnerpeer** [comment]
It's a starter, that for sure. However I came to this thread, as I have identified  other locations and scenarios, where auth info and/or token are still shown.
I am going to report on this once I find the time to describe on how to recreate the behavior.

**Comment by jamesp** [comment]
@wagnerpeer I'd be keen to hear more about the other exposure you've identified.

@bjlittle until authentication without exposing credentials is, at the very least, documented in something more than an issue comment I think this is still an open concern. I'm willing to put together a PR to conda.io docs for the netrc method if the conda core devs could give a thumbs up that they'd by happy to accept it.

**Comment by wagnerpeer** [comment]
I am using `conda --version`: 4.10.3
I am user of a commercial edition token, which I want to use to connect to `https://repo.anaconda.cloud`. To test all possibilities, I set the token within my `.condarc` (not recommended), which leads to the following content:
```text
channels:
  - https://repo.anaconda.clound/t/abcdef1234567890/repo/main
```

If I run `conda info`, everything is fine. The token is obscured as `https://repo.anaconda.clound/t/<TOKEN>/repo/main`.
Same for `conda config --show`.

However, if I search for a package which is not available (e.g. typo in name), conda throws a PackagesNotFoundError, listing the channels it searched through, revealing the token!

Another case, where the token gets exposed is similar to the first one: Creating a CondaHTTPError, which can happen in the case of misconfiguration of certificates etc. 

To complete the description, I am going to repeat the original note from @bjlittle. Authentication info from basic auth encoded in an URL is exposed in both subcommands, which work fine with the token: `conda info` and `conda config --show`

---

Related, but not directly linked to this issue, is the request to standardize token and auth info within `conda info`, `conda config` and error reports.
If using the `conda token set <TOKEN>` command, the token will implicitly be added to the URL. Same for the usage of the `_netrc` auth information. Both, information about the token as well as the authentication which is used, will not be "shown" (masked) to the user, even though the combination of different parts of the conda configuration can lead to errors.
I would like to be given the information about all used parts in the following form:

```https://<USER>:<PASSWORD>@domain/t/<TOKEN>/channel```
