### ISSUE TITLE
Error running R in conda environment -  conda update -c rdonnellyr -c main --all

### ISSUE THREAD

**Issue by PJMurphy249** [conda/conda#9974]
R runs fine when installed through conda, but because there are some incompatibilities, I'm trying to run a new instance in an environment. When I activate environment and install R I get no errors, but when I try to run R it fails. I've seen many posts on this before but all the details have expired from old posts that have been closed. 

Here's the error:

dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/Shared/Conda_Python2/envs/myenv_Garrett/lib/R/lib/libR.dylib
  Reason: image not found

**Comment by HaithamMaya** [comment]
I am also running into the same issue doing the following:

```bash
conda install r-base r-essentials
```

same with
```bash
conda install -c r r
```

**Comment by HaithamMaya** [comment]
As a follow-up, I am getting this only when anaconda is installed in the same environment.

**Comment by PJMurphy249** [comment]
Same thing here. R runs fine by itself but fails to load from the environment. Same error.
