### ISSUE TITLE
Conda [4.8.3] activate fails due to unbound PROJ_LIB

### ISSUE THREAD

**Issue by am-thyst** [conda/conda#9979]
Similar to #8186

## Current Behavior
Activating a miniconda environment in a bash script:

```bash
#!/usr/bin/env bash

#$ -cwd
#$ -N jobarray
#$ -pe smp.pe 4
#$ -t 1-4

set -o errexit  # Abort script on any error
set -o nounset # Treat undefined variables as errors

. ~/miniconda3.sh
export PYTHONPATH=/mnt/seaes01-data01/dmg/dmg/e97950aj/miniconda3/envs/workenv/bin/python
conda activate workenv
```
Pulls error:
```bash
/mnt/seaes01-data01/dmg/dmg/e97950aj/miniconda3/envs/workenv/etc/conda/activate.d/proj4-activate.sh: line 6: PROJ_LIB: unbound variable
```

## Expected Behavior
`${PROJ_LIB:-}` in line 6

## Fix
Fixed by changing PROJ_LIB in line 6 to `{PROJ_LIB:-}` or removing line `set -o nounset` also solves issue.

**Comment by xhochy** [comment]
@am-thyst Did you install `proj4` from Anaconda or conda-forge? Can you provide the output of `conda list`?
