### ISSUE TITLE
Conda environment is activated, however the python console says the environment is not activated

### ISSUE THREAD

**Issue by Arpanio** [conda/conda#9982]
## Current Behavior

I am following the conda documentation as well as the troubleshooting guide in order to create a new environment on a Windows machine, activate it, and then enter into the python console.

I can see that the environment is active, however, python console gives me the warning that the environment is not active.

Furthermore, trying to import a module (numpy) that I installed in the current conda environment fails as it instead tries to load it from the base conda environment (this is a whole different headache).

### Steps to Reproduce

The following are the exact steps that I have used:

1. Install Anaconda on a Windows machine (version details in section Environment Information below)
2. Download numpy tar file from conda-forge
3. Create a project folder
4. Open Anaconda Prompt (Powershell) as an Admin and cd to project folder
5. Run the conda commands listed below

```
conda create --prefix ./envs --offline
conda activate /path/to/envs
conda install /path/to/numpy/tar/from/conda-forge
python
```

## Expected Behavior

1. The Powershell should reflect that the active conda environment is envs. This behaviour is observed:
<img width="735" alt="screenshot_env_list_remote" src="https://user-images.githubusercontent.com/7851954/83907255-0c658b80-a75d-11ea-8c7e-6c46ae2a10c5.PNG">
2. On running `python`, the python console should start without the "environment not activated" warning. This is **not the case**:
<img width="735" alt="screenshot_env_python_console_remote" src="https://user-images.githubusercontent.com/7851954/83907467-58183500-a75d-11ea-92dc-1650a0709586.PNG">

Plaintext of warning message: 

> This Python interpreter is in a conda environment, but the environment has not been activated. Libraries may fail to load. To activate this environment please see https://conda.io/activation

3. Trying to load numpy fails as it tries to load from `C:\ProgramData\Anaconda` and not from the conda environment I created.
<img width="736" alt="screenshot_env_python_numpy" src="https://user-images.githubusercontent.com/7851954/83910317-438a6b80-a762-11ea-9023-4e7f53aceeb5.PNG">

## Environment Information
1. OS: Windows Server 2016 (v10.0.14393)
2. Anaconda: V2020.02 py37_0
3. Conda: V4.8.2

I have admin access to the Windows machine. The windows machine does not have internet access (corporate environment).
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : D:\conda_project\envs
    active env location : D:\conda_project\envs
            shell level : 2
       user config file : C:\Users\daspana\.condarc
populated config files :
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\daspana\.conda\pkgs
                          C:\Users\daspana\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\daspana\.conda\envs
                          C:\Users\daspana\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.14393
          administrator : True
             netrc file : None
           offline mode : False

```

This is what the system PATH looks like:
<img width="397" alt="screenshot_env_remote" src="https://user-images.githubusercontent.com/7851954/83909656-1b4e3d00-a761-11ea-9700-d68124c61b9a.PNG">

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

Running conda config --show-sources returns nothing

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at D:\conda_project\envs:
# 
# Name                        Version                                Build                                Channel
numpy                          1.18.4               py37hae9e721_0                                <unknown>
```
</p></details>

**Comment by Arpanio** [comment]
I have asked this question on stackoverflow as well: https://stackoverflow.com/questions/62216927/conda-environment-is-activated-but-python-console-says-the-environment-has-not

In addition to the approach mentioned in the post, I have also attempted to create an env with the --name flag instead of --prefix. The end result has been the same.

**Comment by hugobuddel** [comment]
Python is not by default included in a new environment (anymore), so you should install that.

Note that Python is a dependency of numpy, as are several other packages, but these are apparently not installed automatically if you install packages manually. So you need those too.

It gets messy pretty quickly:
```
(test4) C:\Users\test\temp>conda install numpy-1.19.0-py37hae9e721_0.tar.bz2
(test4) C:\Users\test\temp>conda install python-3.7.6-cpython_h60c2a47_6.tar.bz2
(test4) C:\Users\test\temp>python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'C:\\Users\\test\\miniconda3\\envs\\test4\\python.exe'
>>> import numpy
Traceback (most recent call last):
  File "C:\Users\test\miniconda3\envs\test4\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\test\miniconda3\envs\test4\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\test\miniconda3\envs\test4\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\test\miniconda3\envs\test4\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\test\miniconda3\envs\test4\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\test\miniconda3\envs\test4\python.exe"
  * The NumPy version is: "1.19.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

>>>

**Comment by Arpanio** [comment]
I do have python on my system. If you see step 2 in my issue description, running "python" from powershell opens up the python prompt.

I couldn't resolve this problem, so went ahead with a pip venv setup instead.

I believe the root cause of this issue was due to a powershell profile variable that kept invoking the global python interpreter instead of the conda version of the python interpreter (in case someone else is facing a similar issue).

In order to diagnose whether the powershell profile is to blame:

1. Activate conda environment
2. Run `Get-Command python` (in powershell. For cmd, run `where python`)

The output of (2) will inform you if Windows is referring to the python interpreter in the conda environment. Check [here](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/) for examples.

**Comment by hugobuddel** [comment]
The global Python interpreter will indeed be invoked because, as I tried to explain, there is no Python interpreter in the environment. The global Python interpreter will not be able to find the packages installed in new environment, because the interpreter is not part of that environment, so it has no access to it.

If you want to use Python in your environment, and have it find packages that you installed in that environment, then you should install Python in the environment too. The post above contains an explicit example on how to resolve your problem, in case you are still interested.

``Get-Command python`` will only show the Python interpreter in the conda environment if you have actually installed the Python interpreter into that environment. Otherwise it will show the global one, because that is the only one there is.

As to the root cause, it seems that conda on Powershell is a confusing mess where it is all too easy to get into a weird state.

**Comment by Arpanio** [comment]
@hugobuddel sorry if I misunderstood your answer. I am a bit confused with your statement that there is no python interpreter in the environment.

Here is the conda documentation on [creating an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands).

They mention that (after step 2):

> This creates the myenv environment in /envs/. This environment uses the same version of Python that you are currently using because you did not specify a version.

Based on that, I was led to believe that:

1. I have successfully set-up a conda environment
2. The conda environment is using a copy of the global python interpreter (similar to how pip venv works)
3. Activating the conda environment will put the conda environment python interpreter on the PATH

I realize that there isn't a 1-to-1 correspondence between the documentation and my approach (I use --prefix instead of --name, I use a --offline flag etc), but what you are saying seems to be very different from what the documentation says.

**Comment by hugobuddel** [comment]
I do recall that conda always automatically added Python to the environment, but it does not do so now. What I guess happened:

* Conda started as a Python-only package manager, so it made sense to always include Python in the environment.
* [Some wrote that line.](https://github.com/conda/conda-docs/commit/247b689f6dfc6ecc7fa92445a56ec924502127ab) (Search for 'same version'.)
* Conda became a package manager for everything. So it was decided to not always include Python.
* No-one actually updated that line in the documentation.

If this is correct, then the change probably happened at the beginning of conda 4.x.

I guess it is not so important for you anymore, as you have a working solution with pip and venv. I'm mainly adding this as a reference for others. And I responded in the first place because I was having similar problems myself.

**Comment by hugobuddel** [comment]
I've created a #10089, so maybe we can prevent this confusion for others.
