### ISSUE TITLE
Adds a command line option/environment variable to skip environment registration

### ISSUE THREAD

**Issue by captainmalloc** [conda/conda#9996]
The `conda create` command always tries to register the new environment in the '~/.conda/environments.txt' DB.

There may be situations where this operation cannot be completed, i.e. environment is created by a home-less account; and/or the user executing the command doesn't not have permission in its own '~/.conda' directory for any IT reason.

Currently a 'hacking' solution for the first use-case is to create an environment containing specific substrings, i.e. 'placehold_pl' or 'skeleton_'.
Still, I am not sure there is a solution for the second use-case as `RegisterEnvironmentLocationAction` will fail on `verify()`.

It'd be good to have a command line options and/or an environment variable to allow creating new environements w/o registering them.

**Comment by nlvw** [comment]
It would be nice if the 'environments.txt' DB was stored at the 'pkgs_dirs' path were the environment is actually installed.  Then the `conda env list`, and other relevant commands, just needs to look for the DB file in each path specified then combine the results.
